### ISSUE TITLE
bug: [  MainThread] localstack.dns.plugins     : Unable to start DNS: can't start new thread on Github Actions

### ISSUE THREAD

**Issue by m4t22** [localstack/localstack#10006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While running docker localstack container with docker compose on Github Actions I am getting following error that prevents it from functioning properly:

```
LocalStack version: 3.0.0
LocalStack build date: 2023-11-16
LocalStack build git hash: 3cd32364
2024-01-05T18:58:10.464  WARN --- [  MainThread] localstack.dns.plugins     : Unable to start DNS: can't start new thread
Unexpected exception while starting infrastructure: can't start new thread Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 258, in start_infra
    hooks.on_infra_start.run()
  File "/opt/code/localstack/localstack/runtime/hooks.py", line 64, in run_in_order
    fn_plugin(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/plugin/core.py", line 223, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/runtime/analytics.py", line 86, in _publish_config_as_analytics_event
    log.event("config", env_vars=env_vars, set_vars=present_env_vars)
  File "/opt/code/localstack/localstack/utils/analytics/logger.py", line 39, in event
    self._log(event, payload=payload)
  File "/opt/code/localstack/localstack/utils/analytics/logger.py", line 42, in _log
    self.handler.handle(Event(name=event, metadata=self._metadata(), payload=payload))
  File "/opt/code/localstack/localstack/utils/analytics/publisher.py", line 235, in handle
    self._start()
  File "/opt/code/localstack/localstack/utils/analytics/publisher.py", line 250, in _start
    start_worker_thread(self._do_start_retry)
  File "/opt/code/localstack/localstack/utils/threads.py", line 109, in start_worker_thread
    return start_thread(method, *args, _shutdown_hook=False, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/utils/threads.py", line 101, in start_thread
    thread.start()
  File "/usr/local/lib/python3.11/threading.py", line 964, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
2024-01-05T18:58:11.080  INFO --- [  MainThread] l.runtime.shutdown         : [shutdown] Stopping all services
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/code/localstack/localstack/runtime/main.py", line 28, in <module>
    main()
  File "/opt/code/localstack/localstack/runtime/main.py", line 20, in main
    infra.start_infra(asynchronous=False)
  File "/opt/code/localstack/localstack/services/infra.py", line 280, in start_infra
    raise e
  File "/opt/code/localstack/localstack/services/infra.py", line 258, in start_infra
    hooks.on_infra_start.run()
  File "/opt/code/localstack/localstack/runtime/hooks.py", line 64, in run_in_order
    fn_plugin(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/plugin/core.py", line 223, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/runtime/analytics.py", line 86, in _publish_config_as_analytics_event
    log.event("config", env_vars=env_vars, set_vars=present_env_vars)
  File "/opt/code/localstack/localstack/utils/analytics/logger.py", line 39, in event
    self._log(event, payload=payload)
  File "/opt/code/localstack/localstack/utils/analytics/logger.py", line 42, in _log
    self.handler.handle(Event(name=event, metadata=self._metadata(), payload=payload))
  File "/opt/code/localstack/localstack/utils/analytics/publisher.py", line 235, in handle
    self._start()
  File "/opt/code/localstack/localstack/utils/analytics/publisher.py", line 250, in _start
    start_worker_thread(self._do_start_retry)
  File "/opt/code/localstack/localstack/utils/threads.py", line 109, in start_worker_thread
    return start_thread(method, *args, _shutdown_hook=False, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/utils/threads.py", line 101, in start_thread
    thread.start()
  File "/usr/local/lib/python3.11/threading.py", line 964, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

### Expected Behavior

Container starts without DNS issue

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

run localstack docker container with docker compose on Github Actions - issue appeared after upgrade to 3.0.0 (happens also on the newest one 3.0.2)

### Environment

```markdown
- OS: Ubuntu 20.04.5 LTS
- LocalStack: 3.0.0/3.0.2
```

**Comment by m4t22** [comment]
I got response on localstack community slack - citing it there:

```
Hi!
Please make sure that your github action has at least docker version 20.10.10 (ubuntu seems to have backported to 20.10.7) installed!
This is triggered by the upgrade to debian bookworm, and the subsequent usage of glibc 2.36. There is an issue with the default seccomp profile of docker <20.10.9 with Glibc > 2.34 running in the container image due to the usage of the clone3 syscall. 
```

I've upgraded the docker and it worked! Closing the issue.

Thanks @dfangl for your help!

**Comment by mdaraz** [comment]
Hi, I am facing the same issue on this environment:

```
CentOS Linux release 7.9.2009 (Core)
Docker version 19.03.13, build 4484c46d9d
LocalStack version: 3.0.3
```

**Comment by mdaraz** [comment]
Hi, I'm facing the same issue on this environment:
```
CentOS Linux release 7.9.2009 (Core)
Docker version 19.03.13, build 4484c46d9d
LocalStack version: 3.0.3
```
The package that is already installed on this OS can't be upgraded. Do you know a workaround that could sort it out?
