### ISSUE TITLE
secretsmanager crashing at list / update operations

### ISSUE THREAD

**Issue by sung-hwang-zocdoc** [localstack/localstack#1002]
I was able to create a secret on this localstack secrets manager via `create-secret`. 
```
$ aws --endpoint-url=http://localhost:4584 secretsmanager create-secret --name test1
{
    "VersionId": "A435958A-D821-4193-B719-B7769357AER4",
    "Name": "test1",
    "ARN": "arn:aws:secretsmanager:us-east-1:1234567890:secret:test1-rIjad"
}
```
However, when I try to list it or update it, I'm seeing:
```
$ aws --endpoint-url=http://localhost:4584 secretsmanager list-secrets

An error occurred (500) when calling the ListSecrets operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

```

I tried with awslocal instead to see if it gives any more error message. It said: 
```
$ awslocal secretsmanager list-secrets
ERROR: Unable to find LocalStack endpoint for service "secretsmanager"
```

**Comment by mmoayyed** [comment]
Same error using the AWS Java API:

```java
val request = new PutSecretValueRequest();
request.setSecretId("test");
request.setSecretString("abc");
client.putSecretValue(request);
```

**Comment by sung-hwang-zocdoc** [comment]
I'm guessing that list-secrets is just not well supported. I was able to create it, and also `client.getSecretValue({ SecretId: secretId })` from node aws-sdk api worked just fine, so I moved on. But it would be good to have this working.

**Comment by jorgetavares89** [comment]
Hello folks, I got the same error to retrieve a secret using `aws-cli`. When I use the `client.createSecret` method works fine to create a new secrete, But I can't retrieve the value, I got a `com.amazonaws.services.secretsmanager.model.ResourceNotFoundException: Secrets Manager can't find the specified secret` exception when I tries to get via Java SDK. Some one can help?

**Comment by jskrnbindra** [comment]
Same error. Any update on this?

**Comment by mmenard-bbc** [comment]
I have the same problem, I tried to use "listSecrets" method of "AWSSecretsManager" and I have this in the logs of localstack : NotImplementedError: The list_secrets action has not been implemented

**Comment by mnylen** [comment]
For me, ListSecrets and PutSecretValue don't work through through boto3  at all. They're simply not implemented in the underlying library.

I'm wondering has this broken recently, because Secrets Manager is listed as supported service. Surely it wouldn't be listed if the most basic operations had been broken all this time?

**Comment by mnylen** [comment]
Btw, the moto master branch contains some improvements to the Secrets Manager support. Unfortunately still no list / update support, but at least it supports multiple secrets - the version bundled with localstack supports only storing one secret at a time.

There's no recent pip release of moto, so getting the master of moto_server up and running with these changes is slightly more involved process, but here's a Dockerfile and a docker-compose.yml example how to do it:

**motoserver/Dockerfile**

```
FROM python:3.6

ENV MOTO_COMMIT 1095b7d94bdd46b1bb2dbff0122994baf94f2eeb

RUN curl -L https://github.com/spulec/moto/archive/$MOTO_COMMIT.zip -o $MOTO_COMMIT.zip
RUN unzip $MOTO_COMMIT.zip

WORKDIR /moto-$MOTO_COMMIT

RUN pip install -e .[server]

EXPOSE 5000

ENTRYPOINT ["moto_server"]
```

Then in docker-compose.yml you could have something like this to start the server:

```
version: "3"
services:
  secretsmanager:
    build: motoserver # the directory where the above Dockerfile is
    command: ["secretsmanager", "-H", "0.0.0.0"]
    ports:
      - "5000:5000"
```

Now, you should be able to use `http://localhost:5000` as the secrets manager endpoint.

**Comment by mmoayyed** [comment]
Trying the latest localstack docker image, using SDK version `1.11.525`, as of this morning with this piece of code:

```
val request = new PutSecretValueRequest();
request.setSecretId("test");
request.setSecretString("abc");
client.putSecretValue(request);
```

I see this:

```
 2019-03-29 11:54:49,034 DEBUG [com.amazonaws.protocol.json.JsonContent] - <Unable to parse HTTP response content>
     com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
     at [Source: (byte[])"<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
    <title>500 Internal Server Error</title>
    <h1>Internal Server Error</h1>
    <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
    "; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804) ~[jackson-core-2.9.8.jar:2.9.8]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:693) ~[jackson-core-2.9.8.jar:2.9.8]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:591) ~[jackson-core-2.9.8.jar:2.9.8]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2630) ~[jackson-core-2.9.8.jar:2.9.8]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:832) ~[jackson-core-2.9.8.jar:2.9.8]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:729) ~[jackson-core-2.9.8.jar:2.9.8]
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4042) ~[jackson-databind-2.9.8.jar:2.9.8]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2571) ~[jackson-databind-2.9.8.jar:2.9.8]
        at com.amazonaws.protocol.json.JsonContent.parseJsonContent(JsonContent.java:72) ~[aws-java-sdk-core-1.11.525.jar:?]
        at com.amazonaws.protocol.json.JsonContent.<init>(JsonContent.java:64) ~[aws-java-sdk-core-1.11.525.jar:?]
        at com.amazonaws.protocol.json.JsonContent.createJsonContent(JsonContent.java:54) ~[aws-java-sdk-core-1.11.525.jar:?]
        at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:61) ~[aws-java-sdk-core-1.11.525.jar:?]
        at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:33) ~[aws-java-sdk-core-1.11.525.jar:?]
        at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:53) ~[aws-java-sdk-core-1.11.525.jar:?]
        at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:41) ~[aws-java-sdk-core-1.11.525.jar:?]
        at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:26) ~[aws-java-sdk-core-1.11.525.jar:?]
```

It's unclear what JSON is getting parsed that has issues. Is there a log level one can turn on to see more details?

**Comment by josejc06clip** [comment]
I created again with the same name and It worked property, then get-secret-value works fine as well!

**Comment by hao4** [comment]
I am seeing the NotImplementedError too: 

2019-09-15 12:56:28,771:API: 172.17.0.1 - - [15/Sep/2019 12:56:28] "POST / HTTP/1.1" 500 -
2019-09-15 12:56:28,777:API: Error on request:
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 303, in run_wsgi
execute(self.server.app)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 291, in execute
application_iter = app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/server.py", line 104, in __call__
return backend_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/utils.py", line 140, in __call__
result = self.callback(request, request.url, {})
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 117, in dispatch
return cls()._dispatch(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 200, in _dispatch
return self.call_action()
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 296, in call_action
"The {0} action has not been implemented".format(action))
NotImplementedError: The list_secrets action has not been implemented

Did anyone figure out a solution for this yet?

**Comment by whummer** [comment]
Thanks for reporting @sung-hwang-zocdoc @mmoayyed @jorgetavares89 @jskrnbindra @mmenard-bbc @mnylen @josejc06clip @hao4 . This should be fixed in the latest version - an integration test has been added in #2223 . Please report if the problem persists. Thanks

**Comment by afbarbaro** [comment]
Same error for me!  Latest `localstack` version (`0.12.8`) and latest docker image.

![image](https://user-images.githubusercontent.com/18277423/135339328-ae4233fe-8314-447c-b357-fcf6cb671cb1.png)
