### ISSUE TITLE
bug: Localstack fails to provide Kinesis shard iterator for iterator type AT_TIMESTAMP

### ISSUE THREAD

**Issue by majk-p** [localstack/localstack#10037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm attempting to read records from shards, for that I need to obtain iterators first. When requesting `TRIM_HORIZON` everything works fine. When requesting `AT_TIMESTAMP` and providing timestamp, localstack crashes with following error in the logs:

```
2024-01-10T08:46:52.684 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain         
Traceback (most recent call last):                                                                                
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 863, in _parse_body_as_json
    return cbor2.loads(body_contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 55995 is out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 64, in __call__
    return self.parse_and_enrich(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 77, in parse_and_enrich
    operation, instance = parser.parse(context.request)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 173, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 904, in parse
    final_parsed = self._do_parse(request, shape, uri_params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 916, in _do_parse
    parsed = self._handle_json_body(request, shape, uri_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 928, in _handle_json_body
    parsed_json = self._parse_body_as_json(request)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 865, in _parse_body_as_json
    raise ProtocolParserError("HTTP body could not be parsed as CBOR.") from e
localstack.aws.protocol.parser.ProtocolParserError: HTTP body could not be parsed as CBOR.
2024-01-10T08:46:52.687  INFO --- [   asgi_gw_0] localstack.request.http    : POST / => 500
2024-01-10T08:46:52.806 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 863, in _parse_body_as_json
    return cbor2.loads(body_contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 55995 is out of range

The above exception was the direct cause of the following exception:                                              
                                                                                                                  
Traceback (most recent call last):                                                                                
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle                                         
    handler(self, self.context, response)                                                                         
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 64, in __call__                            
    return self.parse_and_enrich(context)                                                                         
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                         
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 77, in parse_and_enrich                    
    operation, instance = parser.parse(context.request)                                                           
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                           
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 173, in wrapper                             
    return func(*args, **kwargs)                                                                                  
           ^^^^^^^^^^^^^^^^^^^^^                                                                                  
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 904, in parse                               
    final_parsed = self._do_parse(request, shape, uri_params)                                                     
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                     
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 916, in _do_parse                           
    parsed = self._handle_json_body(request, shape, uri_params)                                                   
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                   
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 928, in _handle_json_body                   
    parsed_json = self._parse_body_as_json(request)                                                               
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                               
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 865, in _parse_body_as_json                 
    raise ProtocolParserError("HTTP body could not be parsed as CBOR.") from e
localstack.aws.protocol.parser.ProtocolParserError: HTTP body could not be parsed as CBOR.
2024-01-10T08:46:52.806  INFO --- [   asgi_gw_0] localstack.request.http    : POST / => 500
2024-01-10T08:46:53.023 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 863, in _parse_body_as_json
    return cbor2.loads(body_contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 55995 is out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 64, in __call__
    return self.parse_and_enrich(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 77, in parse_and_enrich
    operation, instance = parser.parse(context.request)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 173, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 904, in parse
    final_parsed = self._do_parse(request, shape, uri_params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 916, in _do_parse
    parsed = self._handle_json_body(request, shape, uri_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 928, in _handle_json_body
    parsed_json = self._parse_body_as_json(request)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 865, in _parse_body_as_json
    raise ProtocolParserError("HTTP body could not be parsed as CBOR.") from e
localstack.aws.protocol.parser.ProtocolParserError: HTTP body could not be parsed as CBOR.
2024-01-10T08:46:53.026  INFO --- [   asgi_gw_0] localstack.request.http    : POST / => 500
2024-01-10T08:46:53.265 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 863, in _parse_body_as_json
    return cbor2.loads(body_contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: year 55995 is out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 64, in __call__
    return self.parse_and_enrich(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 77, in parse_and_enrich
    operation, instance = parser.parse(context.request)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 173, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 904, in parse
    final_parsed = self._do_parse(request, shape, uri_params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 916, in _do_parse
    parsed = self._handle_json_body(request, shape, uri_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 928, in _handle_json_body
    parsed_json = self._parse_body_as_json(request)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 865, in _parse_body_as_json
    raise ProtocolParserError("HTTP body could not be parsed as CBOR.") from e
localstack.aws.protocol.parser.ProtocolParserError: HTTP body could not be parsed as CBOR.
2024-01-10T08:46:53.269  INFO --- [   asgi_gw_0] localstack.request.http    : POST / => 500
```

### Expected Behavior

I would expect localstack to return shard iterators, as it does when requesting `TRIM_HORIZON`.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

I'm starting localstack using [testcontainers](https://testcontainers.com/), that basically starts localstack in docker containers.

To reproduce the issue I've prepared a self-contained reproduction program that uses testcontainers to start localstack. 
The program:
* Starts localstack in docker in debug mode
* Creates Kinesis client
* Creates Kinesis stream
* Sends event to Kinesis stream
* Attempts to read events from Kinesis
  * If `TRIM_HORIZON` positional parameter is provided, it will request `TRIM_HORIZON` iterator type - this works fine
  * Otherwise it will try to use `AT_TIMESTAMP` with current timestamp - this fails
* Prints out found events 

The code is available in a snippet: https://gist.github.com/majk-p/558b231d0b7a73b1cd46ad39d8d438a5

You can run it using [scala-cli](https://scala-cli.virtuslab.org/install). 

To reproduce the problem locally run:
```
scala-cli https://gist.github.com/majk-p/558b231d0b7a73b1cd46ad39d8d438a5
```

To reproduce the success scenario with `TRIM_HORIZON` run:
```
scala-cli https://gist.github.com/majk-p/558b231d0b7a73b1cd46ad39d8d438a5 -- TRIM_HORIZON
```
Make sure the docker is running with `sudo systemctl docker start` (or your OS alternative) and make sure your user is allowed to start docker containers without sudo (you need to be member of `docker` OS group).

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
I'm using AWS SDK V2 for Java (wrapped with [fs2-aws](https://github.com/laserdisc-io/fs2-aws/) but it doesn't seem relevant). The piece that fails is:

```scala
kinesisClient.getShardIterator(
  GetShardIteratorRequest
    .builder()
    .streamName(streamName)
    .shardId(shard.shardId())
    .shardIteratorType(ShardIteratorType.AT_TIMESTAMP).timestamp(from)
)
```

### Environment

```markdown
- OS: Tested on Fedora Linux and Mac OS
- LocalStack: Tested both `2.3.2` and `3.0.2`, both behave the same way
```

### Anything else?

The very same client code for requesting `AT_TIMESTAMP` iterator works fine against AWS.

Regarding related issues, I've found just one that seems two are related:
- https://github.com/localstack/localstack/issues/635
- https://github.com/localstack/localstack/issues/1106

Both are years old and closed already, thus reporting a new one.

**Comment by fs-jasonc** [comment]
Year 55995 is 54 025 years since epoch-zero. You posted this roughly January 2024 is 54.02 years since epoch zero. This suggests an incorrect use of milliseconds vs seconds somewhere. Since you code works against real AWS, I suspect the bug is in LocalStack.

I am getting the same behavior from the Java AWS SDK. The returns times are off by a factor of 1000.

**Comment by alexrashed** [comment]
Hey @majk-p! This issue should be resolved in the `latest` Docker images. Please let us know if you still experience any issues. Thanks!

**Comment by birbirsbirbirs** [comment]
localstack/localstack:latest got this issue resolved. Thank you very very much much.
