### ISSUE TITLE
Kinesis persistence not working

### ISSUE THREAD

**Issue by adriangalera** [localstack/localstack#1003]
Hi there,
We are executing localstack in a docker-compose environment defined in this docker-compose.yml:
```
version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4583:4567-4583" 
    environment:
      - SERVICES=s3,dynamodb,sns,sqs,kinesis,ses
      - DEBUG=${DEBUG- } .
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- } 
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- } 
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack-persistence:/tmp/localstack/data
  ```

We enabled persistence for the localstack to persist S3 and DynamoDB. We got the side effect of storing Kinesis (we don't care about).
The Kinesis persistence seems that is broken at the startup:

How to reproduce:
Start a clean localsack container and create a kinesis stream
```
docker-compose up
aws kinesis --region us-east-1 --endpoint-url=http://localhost:4568 create-stream --stream-name test --shard-count 1
aws kinesis --region us-east-1 --endpoint-url=http://localhost:4568 list-streams
{
    "StreamNames": [
        "test"
    ]
}
^CGracefully stopping... (press Ctrl+C again to force)
```
Start again the container so it reads the persisted data:
```
docker-compose up 
localstack_1  | 2018-11-08 13:37:44,050 CRIT Supervisor running as root (no user in config file)
localstack_1  | 2018-11-08 13:37:44,052 INFO supervisord started with pid 1
localstack_1  | 2018-11-08 13:37:45,056 INFO spawned: 'dashboard' with pid 10
localstack_1  | 2018-11-08 13:37:45,058 INFO spawned: 'infra' with pid 11
localstack_1  | (. .venv/bin/activate; bin/localstack web)
localstack_1  | (. .venv/bin/activate; exec bin/localstack start)
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  | 2018-11-08T13:37:45:INFO:werkzeug:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
localstack_1  | 2018-11-08T13:37:45:INFO:werkzeug:  * Restarting with stat
localstack_1  | 2018-11-08T13:37:46:WARNING:werkzeug:  * Debugger is active!
localstack_1  | 2018-11-08 13:37:46,196 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 2018-11-08 13:37:46,196 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 2018-11-08T13:37:46:INFO:werkzeug:  * Debugger PIN: 319-990-396
localstack_1  | Starting mock DynamoDB (http port 4569)...
localstack_1  | Starting mock SES (http port 4579)...
localstack_1  | Starting mock Kinesis (http port 4568)...
localstack_1  | Starting mock S3 (http port 4572)...
localstack_1  | Starting mock SQS (http port 4576)...
localstack_1  | Starting mock SNS (http port 4575)...
localstack_1  | 2018-11-08T13:37:50:ERROR:localstack.services.generic_proxy: Error forwarding request: ('Connection aborted.', BadStatusLine("''",)) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 201, in forward
localstack_1  |     headers=forward_headers, stream=True)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 112, in post
localstack_1  |     return request('post', url, data=data, json=json, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
localstack_1  |     raise ConnectionError(err, request=request)
localstack_1  | ConnectionError: ('Connection aborted.', BadStatusLine("''",))
localstack_1  |
localstack_1  | 2018-11-08T13:37:51:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb0d286d290>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 201, in forward
localstack_1  |     headers=forward_headers, stream=True)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 112, in post
localstack_1  |     return request('post', url, data=data, json=json, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
localstack_1  |     raise ConnectionError(e, request=request)
localstack_1  | ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb0d286d290>: Failed to establish a new connection: [Errno 111] Connection refused',))
localstack_1  |
```
Can someone could take a look? At least provide a way to disable/enable persistence per service?

**Comment by mwarkentin** [comment]
Seeing similar on latest w/ persistence and kinesis/firehose services in docker, rolled back to 0.8.0 and things started working again.

Previous error:

```
localstack_1    | 2019-01-16T01:46:03:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffbb3062710>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 216, in forward
localstack_1    |     headers=forward_headers, stream=True)
localstack_1    |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
localstack_1    |     return request('post', url, data=data, json=json, **kwargs)
localstack_1    |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
localstack_1    |     return session.request(method=method, url=url, **kwargs)
localstack_1    |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
localstack_1    |     resp = self.send(prep, **send_kwargs)
localstack_1    |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
localstack_1    |     r = adapter.send(request, **kwargs)
localstack_1    |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
localstack_1    |     raise ConnectionError(e, request=request)
localstack_1    | ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffbb3062710>: Failed to establish a new connection: [Errno 111] Connection refused',))
localstack_1    |
localstack_1    | 2019-01-16T01:46:03:WARNING:infra.pyc: Service "kinesis" not yet available, retrying...
```

**Comment by whummer** [comment]
Thanks for reporting @adriangalera . Could this be a timing issue? Sometimes the stack takes a bit longer to start up, but should eventually print "`Ready.`".

Also, we've recently pushed some performance improvements - can you please give it a try with the latest version?

**Comment by adriangalera** [comment]
Same behaviour with the latests version

**Comment by Neos3452** [comment]
I am experiencing the same problem. Starting a container with
```
docker run -p 4567-4584:4567-4584 -p 7980:8080 -e DOCKER_HOST=unix:///var/run/docker.sock -e SERVICES=dynamodb,kinesis,sns,sqs -e DATA_DIR=/tmp/localstack/data localstack/localstack
```

Create a stream with terraform. (Also tried with awslocal).

```
docker stop && docker start
```

```
2019-03-11T09:12:46:ERROR:infra.pyc: Error checking state of local environment (after some retries): Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 380, in check_infra
    raise e
TypeError: 'NoneType' object has no attribute '__getitem__'

2019-03-11T09:12:57:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa1cd787150>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 216, in forward
    headers=forward_headers, stream=True)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa1cd787150>: Failed to establish a new connection: [Errno 111] Connection refused',))

2019-03-11T09:12:58:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa1cd77eb50>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 216, in forward
    headers=forward_headers, stream=True)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa1cd77eb50>: Failed to establish a new connection: [Errno 111] Connection refused',))

2019-03-11T09:12:58:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa1cd77eb90>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 216, in forward
    headers=forward_headers, stream=True)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa1cd77eb90>: Failed to establish a new connection: [Errno 111] Connection refused',))

2019-03-11T09:12:59:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa1cd77ec90>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 216, in forward
    headers=forward_headers, stream=True)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa1cd77ec90>: Failed to establish a new connection: [Errno 111] Connection refused',))

2019-03-11T09:13:03:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa1cd77ed50>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 216, in forward
    headers=forward_headers, stream=True)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa1cd77ed50>: Failed to establish a new connection: [Errno 111] Connection refused',))

2019-03-11T09:13:03:WARNING:infra.pyc: Service "kinesis" not yet available, retrying...
```

**Comment by aswingit** [comment]
I am experiencing this same problem while trying to persist s3 and dynamo data. Any workaround for this issue? docker restart is not working properly due to kinesis

**Comment by FelikZ** [comment]
@aswingit try this https://github.com/localstack/localstack/issues/918#issuecomment-468367123

**Comment by aswingit** [comment]
> @aswingit try this [#918 (comment)](https://github.com/localstack/localstack/issues/918#issuecomment-468367123)

Thanks it helped
