### ISSUE TITLE
bug: Error when creating a RDS Mysql DB Instance. The method `DBBackend.reboot_db_instance()` is failing in a loop. 

### ISSUE THREAD

**Issue by pk-hugo** [localstack/localstack#10044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating an RDS DB Instance in localstack with Pulumi, getting the below error in loop. 

```
2024-01-10 20:31:52 2024-01-10T15:01:52.940 ERROR --- [  asgi_gw_32] l.aws.handlers.logging     : exception during call chain
2024-01-10 20:31:52 Traceback (most recent call last):
2024-01-10 20:31:52   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/chain.py", line 99, in handle
2024-01-10 20:31:52     handler(self, self.context, response)
2024-01-10 20:31:52   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 112, in __call__
2024-01-10 20:31:52     handler(chain, context, response)
2024-01-10 20:31:52   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 82, in __call__
2024-01-10 20:31:52     skeleton_response = self.skeleton.invoke(context)
2024-01-10 20:31:52                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-10 20:31:52   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
2024-01-10 20:31:52     return self.dispatch_request(serializer, context, instance)
2024-01-10 20:31:52            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-10 20:31:52   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request
2024-01-10 20:31:52     result = handler(context, instance) or {}
2024-01-10 20:31:52              ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-10 20:31:52   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/forwarder.py", line 135, in _call
2024-01-10 20:31:52     return handler(context, req)
2024-01-10 20:31:52            ^^^^^^^^^^^^^^^^^^^^^
2024-01-10 20:31:52   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
2024-01-10 20:31:52     return self.fn(*args, **kwargs)
2024-01-10 20:31:52            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-10 20:31:52   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/rds/provider.py.enc", line 522, in reboot_db_instance
2024-01-10 20:31:52     A=json.loads(C.to_json());E=A[_B];F=db_utils.DBBackend.get(E);F.reboot_db_instance(A);return RebootDBInstanceResult(DBInstance=A)
2024-01-10 20:31:52                                                                   ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-10 20:31:52 TypeError: DBBackend.reboot_db_instance() missing 2 required positional arguments: 'account_id' and 'region_name'
2024-01-10 20:31:52 2024-01-10T15:01:52.942  INFO --- [  asgi_gw_32] localstack.request.aws     : AWS rds.RebootDBInstance => 500 (InternalError)
2024-01-10 20:31:53 2024-01-10T15:01:53.010 ERROR --- [  asgi_gw_74] l.aws.handlers.logging     : exception during call chain
2024-01-10 20:31:53 Traceback (most recent call last):
2024-01-10 20:31:53   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/chain.py", line 99, in handle
2024-01-10 20:31:53     handler(self, self.context, response)
2024-01-10 20:31:53   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 112, in __call__
2024-01-10 20:31:53     handler(chain, context, response)
2024-01-10 20:31:53   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 82, in __call__
2024-01-10 20:31:53     skeleton_response = self.skeleton.invoke(context)
2024-01-10 20:31:53                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-10 20:31:53   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
2024-01-10 20:31:53     return self.dispatch_request(serializer, context, instance)
2024-01-10 20:31:53            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-10 20:31:53   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request
2024-01-10 20:31:53     result = handler(context, instance) or {}
2024-01-10 20:31:53              ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-10 20:31:53   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/forwarder.py", line 135, in _call
2024-01-10 20:31:53     return handler(context, req)
2024-01-10 20:31:53            ^^^^^^^^^^^^^^^^^^^^^
2024-01-10 20:31:53   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
2024-01-10 20:31:53     return self.fn(*args, **kwargs)
2024-01-10 20:31:53            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-10 20:31:53   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/rds/provider.py.enc", line 522, in reboot_db_instance
2024-01-10 20:31:53     A=json.loads(C.to_json());E=A[_B];F=db_utils.DBBackend.get(E);F.reboot_db_instance(A);return RebootDBInstanceResult(DBInstance=A)
2024-01-10 20:31:53                                                                   ^^^^^^^^^^^^^^^^^^^^^^^
2024-01-10 20:31:53 TypeError: DBBackend.reboot_db_instance() missing 2 required positional arguments: 'account_id' and 'region_name'
```

Unable to create the DB instance in RDS. 

### Expected Behavior

Succesfully create a mysql DB instance in RDS.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    using pulumi up

### Environment

```markdown
- OS: MAC OS Ventura (Apple M1 Pro)
- LocalStack: latest
```

### Anything else?

Using pulumi with a local file system as backend. 

Able to create other AWS services like S3, SQS, KMS, SG

**Comment by bentsku** [comment]
Hello @pk-hugo and thanks again for your report!

I believe the issue is now fixed in the latest docker image. Could you give it a try and see if that fixes your issue? You can pull the `latest` image by running `docker pull localstack/localstack-pro:latest`. Thank you!

**Comment by pk-hugo** [comment]
The issue is resolved now with the latest image. I'm able to succesfully create a RDS DB instance.

**Comment by pk-hugo** [comment]
Closing the issue.
