### ISSUE TITLE
error accessing s3 object from spark structured streaming framework

### ISSUE THREAD

**Issue by vishal98** [localstack/localstack#1006]
When we are trying to access the s3 directory on localstack using the spark streaming api ,we are getting following error
```
RROR MicroBatchExecution:91 - Query s3_sDF [id = 4bf750ee-52d2-4ed6-8af6-89fadcbaf033, runId = c6b55dbf-17e3-4ce1-9379-d6f7b3522919] terminated with error
java.lang.IllegalArgumentException: Option 'basePath' must be a directory
	at org.apache.spark.sql.execution.datasources.PartitioningAwareFileIndex.basePaths(PartitioningAwareFileIndex.scala:221)
	at org.apache.spark.sql.execution.datasources.PartitioningAwareFileIndex.inferPartitioning(PartitioningAwareFileIndex.scala:156)
	at org.apache.spark.sql.execution.datasources.InMemoryFileIndex.partitionSpec(InMemoryFileIndex.scala:71)
	at org.apache.spar
```
which implies 
Path in Structured Streaming has to be a directory not a file...anything we can do to fix it

**Comment by whummer** [comment]
Thanks for reporting @vishal98 , not sure if this is specifically a LocalStack issue, or rather a general Spark configuration issue. Can you please provide a small, self-contained example to reproduce this issue? If such an example is provided, we'd be happy to look into it. Thanks
