### ISSUE TITLE
Sqs connection refused in Jenkins2 environment

### ISSUE THREAD

**Issue by kattarg** [localstack/localstack#1011]
Hello, 

In Jenkins2 environment, the SQS unable to connect to localhost with port 4576  and throws `connection refused` error.   If anyone faced this issue and resolved it, it would be highly appreciated if you could share the steps.

```fo]   com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to localhost:4576 [localhost/127.0.0.1] failed: Connection refused (Connection refused)

[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1116)

[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1066)

[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)

[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)

[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)

[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)

[info]   at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)

[info]   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)

[info]   at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2033)

[info]   at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2009)

[info]   ...

[info]   Cause: org.apache.http.conn.HttpHostConnectException: Connect to localhost:4576 [localhost/127.0.0.1] failed: Connection refused (Connection refused)

[info]   at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)

[info]   at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)

[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[info]   at java.lang.reflect.Method.invoke(Method.java:498)

[info]   at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)

[info]   at com.amazonaws.http.conn.$Proxy15.connect(Unknown Source)

[info]   at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)

[info]   at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)

[info]   ...

[info]   Cause: java.net.ConnectException: Connection refused (Connection refused)

[info]   at java.net.PlainSocketImpl.socketConnect(Native Method)

[info]   at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

[info]   at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

[info]   at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

[info]   at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

[info]   at java.net.Socket.connect(Socket.java:589)

[info]   at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)

[info]   at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)

[info]   at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)

[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)```

**Comment by kattarg** [comment]
I figured out last week This is not only for SQS and for all AWS services... I fixed by configuring `HOSTNAME_EXTERNAL=localstack` and worked fine... Remember if you running different way in localmachine, you might use as `localhost` by having different docker-compose configuration
