### ISSUE TITLE
bug: bug: event buses do not trigger target lambdas with the `event_pattern` pattern containing filtering by `details`

### ISSUE THREAD

**Issue by andrii-dovzhenko** [localstack/localstack#10147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I create an EventBridge rule that contains an event_pattern that looks like this:
```
{
  "detail": {
    "state": ["Successful"]
  },
  "source": ["myService"]
}
```
and then send the event to the event bus, the target lambda is not triggered.
But if I remove the `detail` key from the template, it will look like this:
```
{
  "source": ["myService"]
}
```
everything works just fine. 

When I use AWS, the event pattern behaves as expected.

It also can be observed when using `awslocal events test-event-pattern`.
If I run this command
```shell
aws events test-event-pattern --event-pattern '{"source": ["myService"], "detail": {"state":["Successful"]}}' --event '{"id":"id","detail-type":"My Service","source":"myService","account":"000000000000","time":"2024-01-30T14:58:35Z","region":"us-east-2","resources":[], "detail": {"state": "Successful"}}'
```
I get as excepted:
```json
{
    "Result": true
}
```

But if I run the same command with `awslocal`, I get exceptions:
```python
An error occurred (InternalError) when calling the TestEventPattern operation (reached max retries: 2): exception while calling events.TestEventPattern: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 112, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 82, in __call__
    skeleton_response = self.skeleton.invoke(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(serializer, context, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 168, in dispatch_request
    result = handler(context, instance) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/forwarder.py", line 135, in _call
    return handler(context, req)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/services/events/provider.py", line 118, in test_event_pattern
    if any(key not in evt or evt[key] not in values for key, values in evt_pattern.items()):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/services/events/provider.py", line 118, in <genexpr>
    if any(key not in evt or evt[key] not in values for key, values in evt_pattern.items()):
                             ^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
```

### Expected Behavior

Events sent to event bus should correctly match the event pattern specified in the rule.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
```shell
docker run \
    --name "localstack" \
    --detach \
    --publish 4566:4566 \
    --label "started_at=$current_date" \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --pull missing \
    --env DEBUG=1 \
    --env PROVIDER_OVERRIDE_LAMBDA=v2 \
    localstack/localstack:latest
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
You can use this command to check that event matching doesn't work properly:
```shell
aws events test-event-pattern --event-pattern '{"source": ["myService"], "detail": {"state":["Successful"]}}' --event '{"id":"id","detail-type":"My Service","source":"myService","account":"000000000000","time":"2024-01-30T14:58:35Z","region":"us-east-2","resources":[], "detail": {"state": "Successful"}}'
```
It will return exception, but it should return this:
```json
{
    "Result": true
}
```

### Environment

```markdown
- OS:Ubuntu 22.04
- LocalStack: 3.1.0
```

**Comment by andy-g** [comment]
I'm not sure if it's related, but when I tried to create this rule (which is valid on [AWS](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns-content-based-filtering.html#eb-filtering-complex-example-or))
```json
{
  "source": ["myService"],
  "$or": [
    {
      "detail-type": ["Event1"]
    },
    {
      "detail-type": ["Event2"],
      "detail.payload": {
        "type": ["Type2"]
      }
    }
  ]
}
```

it doesn't seem to trigger my lambda for either scenario. Looks like the `$or` property may not be handled.

I've also had issues with [Exists matching](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns-content-based-filtering.html#eb-filtering-exists-matching) , e.g:
```json
{
  "detail": {
    "state": [ { "exists": true  } ]
  }
}
```

**Comment by maxhoheiser** [comment]
> I'm not sure if it's related, but when I tried to create this rule (which is valid on [AWS](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns-content-based-filtering.html#eb-filtering-complex-example-or))
> 
> {
>   "source": ["myService"],
>   "$or": [
>     {
>       "detail-type": ["Event1"]
>     },
>     {
>       "detail-type": ["Event2"],
>       "detail.payload": {
>         "type": ["Type2"]
>       }
>     }
>   ]
> }
> it doesn't seem to trigger my lambda for either scenario. Looks like the `$or` property may not be handled.
> 
> I've also had issues with [Exists matching](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns-content-based-filtering.html#eb-filtering-exists-matching) , e.g:
> 
> {
>   "detail": {
>     "state": [ { "exists": true  } ]
>   }
> }
> It looks like the exists issue should have been fixed in the 3.1 milestone: [#9931](https://github.com/localstack/localstack/pull/9931), but I'm running 3.1 in docker and still having issues.

Hi @andy-g could you please check if this is still the issue with the newly released EventBridge v2 in LocaStack 3.5? You can activate the new EventBridge v2 by setting the environment variable `PROVIDER_OVERRIDE_EVENTS=v2`, if no could you please open a new issue and give us a fully working example rule pattern and event so we can fix this ASAP - thank you :)

**Comment by maxhoheiser** [comment]
@andrii-dovzhenko we released last week with LocalStack 3.5 our brand new EventBrdige v2 - this also uses our new EventRule engine, the combination of both fixes your above-described issues and is fully in line with AWS behaviour. 
You can activate the EventBridge v2 by setting the environment variable `**PROVIDER_OVERRIDE_EVENTS=v2**` - please let us know if you encounter any other issues so we can fix them ASAP :)

**Comment by henriqueleite42** [comment]
Hi, I'm facing the same issue, but it seems that the EventBridge v2 doesn't fully implement all the cli command that the previous version has.

I need to configure a connection, but the CLI doesn't support it, and `EVENT_RULE_ENGINE=java` doesn't works for me. @maxhoheiser do you have any suggestions about how to solve it for now?
