### ISSUE TITLE
bug: Unable to update stack "RemovePermission operation: No policy is associated with the given resource."

### ISSUE THREAD

**Issue by pigfrown** [localstack/localstack#10169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Updating a CDK Stack containing API Gateway + Lambda results in :

`An error occurred (ResourceNotFoundException) when calling the RemovePermission operation: No policy is associated
with the given resource.`

(this happens even when the stack has not changed)

### Expected Behavior

should be able to update the stack after initial deployment

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

CDK Stack: https://github.com/pigfrown/cdklocal-bug/blob/main/lib/cdklocal-bug-stack.ts

Recreate with:
```
git clone https://github.com/pigfrown/cdklocal-bug
cd cdklocal-bug
npm i

localstack start -d

npx cdklocal bootstrap
npx cdklocal deploy # This deployment works/curling the endpoint works
npx cdklocal deploy # This deployment fails and breaks the deployed stack
```

Error message is: 
```
npx cdklocal deploy

✨  Synthesis time: 2.54s

CdklocalBugStack: deploying... [1/1]
CdklocalBugStack: creating CloudFormation changeset...
11:17:50 | UPDATE_FAILED        | AWS::Lambda::Permission     | MyApihelloGETApiPe...C2GEThelloC0249EEE
An error occurred (ResourceNotFoundException) when calling the RemovePermission operation: No policy is associated
with the given resource.


 ❌  CdklocalBugStack failed: Error: The stack named CdklocalBugStack failed to deploy: UPDATE_FAILED (An error occurred (ResourceNotFoundException) when calling the RemovePermission operation: No policy is associated with the given resource.): An error occurred (ResourceNotFoundException) when calling the RemovePermission operation: No policy is associated with the given resource.
    at FullCloudFormationDeployment.monitorDeployment (/tmp/cdklocal-bug/node_modules/aws-cdk/lib/index.js:428:10615)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/tmp/cdklocal-bug/node_modules/aws-cdk/lib/index.js:431:182305)
    at async /tmp/cdklocal-bug/node_modules/aws-cdk/lib/index.js:431:164665

 ❌ Deployment failed: Error: The stack named CdklocalBugStack failed to deploy: UPDATE_FAILED (An error occurred (ResourceNotFoundException) when calling the RemovePermission operation: No policy is associated with the given resource.): An error occurred (ResourceNotFoundException) when calling the RemovePermission operation: No policy is associated with the given resource.
    at FullCloudFormationDeployment.monitorDeployment (/tmp/cdklocal-bug/node_modules/aws-cdk/lib/index.js:428:10615)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/tmp/cdklocal-bug/node_modules/aws-cdk/lib/index.js:431:182305)
    at async /tmp/cdklocal-bug/node_modules/aws-cdk/lib/index.js:431:164665

The stack named CdklocalBugStack failed to deploy: UPDATE_FAILED (An error occurred (ResourceNotFoundException) when calling the RemovePermission operation: No policy is associated with the given resource.): An error occurred (ResourceNotFoundException) when calling the RemovePermission operation: No policy is associated with the given resource.
```

### Environment

```markdown
- OS: Linux
- LocalStack: 3.1.0
- Node: v18.14.0

 "aws-cdk": "2.124.0",                                                                                     
 "aws-cdk-local": "^2.18.0",  
```

**Comment by Yehonal** [comment]
I have the same issue

**Comment by Yehonal** [comment]
I also think this is related to this other issue somehow: https://github.com/localstack/localstack/issues/10042

Because using the same workaround I mentioned there, it works

**Comment by hkaiser25** [comment]
Same issue here when running `samlocal deploy`

**Comment by Garethp** [comment]
@dominikschubert I'm still seeing this error on 3.1.1.dev20240223125541, which was published an hour ago. Instead of being on APIGateway Integrations, I've reproduced it for Event Rule Targets, with the following code:

```ts
export class LambdaPermissionStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const lambda = new Function(this, "lambda-handler", {
      runtime: Runtime.NODEJS_20_X,
      code: Code.fromInline("exports.handler = async () => ({ });"),
      handler: "index.handler",
    });

    new Rule(this, "ScheduleRule", {
      schedule: Schedule.cron({
        hour: process.env.SECOND_RUN ? "7" : "6",
        minute: "0",
        weekDay: "MON-FRI",
      }),
      targets: [new aws_events_targets.LambdaFunction(lambda)],
    });
  }
}
```

I've pushed a reproduction up to: https://github.com/Garethp/localstack-bugs/tree/lamda-permission-redeploy, just clone down that branch, run `yarn install && ./start.sh` and you should see the error occur.

**Comment by dominikschubert** [comment]
Thanks for reporting and providing the sample @Garethp !
I was able to reproduce your issue and will reopen this issue.

**Comment by Garethp** [comment]
Thanks @dominikschubert, that update works for my stack :)

**Comment by simonrw** [comment]
Hi @pigfrown I have tried to reproduce the issue you described, and cannot re-create the issue. Could you pull the latest docker image and try again?
