### ISSUE TITLE
bug: IMDS providerID value is a k3s URI as opposed to an AWS URI

### ISSUE THREAD

**Issue by stirlingalgermissen** [localstack/localstack#10205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

IMDS ProviderID is a value of the form k3s://$ecs_cluster_name-server-0

### Expected Behavior

IMDS ProviderID is a value of the form aws://$az/$instanceid

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Using terraform

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

N/A

### Environment

```markdown
- OS: MacOS latest
- LocalStack: latest
```

### Anything else?

Here is logging information that may be helpful:

kubectl -n kube-system logs pod/ebs-csi-controller-59bb7d8d88-6s5x6 -c ebs-plugin    
I0208 23:23:52.221811       1 driver.go:80] "Driver Information" Driver="ebs.csi.aws.com" Version="v1.27.0"
I0208 23:23:52.221883       1 metadata.go:85] "retrieving instance data from ec2 metadata"
I0208 23:23:52.789651       1 metadata.go:88] "ec2 metadata is not available"
I0208 23:23:52.789687       1 metadata.go:96] "retrieving instance data from kubernetes api"
I0208 23:23:52.790383       1 metadata.go:101] "kubernetes api is available"
E0208 23:23:52.796814       1 controller.go:86] "Could not determine region from any metadata service. The region can be manually supplied via the AWS_REGION environment variable." err="did not find aws instance ID in node providerID string"
panic: did not find aws instance ID in node providerID string

goroutine 1 [running]:
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.newControllerService(0x40000a3da0)
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/controller.go:87 +0x2fc
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.NewDriver({0x40006c1ec8, 0xb, 0x4?})
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/driver.go:100 +0x41c
main.main()
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd/main.go:64 +0x3cc
`

**Comment by stirlingalgermissen** [comment]
FYI @viren-nadkarni

**Comment by viren-nadkarni** [comment]
Hi @stirlingalgermissen, do we know which endpoint of IMDS this relates to?

**Comment by drewm-jpl** [comment]
Based on the logs listed above, we identified [the location in the AWS EFS CSI driver code base that is producing this error](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/pkg/cloud/metadata.go). It appears that if `GetNewMetadataProvider` is called from a Kubernetes node, it attempts to extract the EC2 metadata from the node information in the cluster using the Kubernetes API. The issue seems to be that the LocalStack emulated EKS node does not contain this metadata information or it is formatted incorrectly. In our case, we see the providerID of our EKS node formatted as `k3s://k3d-$clustername-server-0` which does not seem to meet the expected format of `aws://$az/$instanceid`.

Would it be possible to improve the fidelity of EKS emulation to include EC2 metadata information within the EKS nodes. This likely includes more than just the a valid provider ID field.

**Comment by theslyone** [comment]
Recently ran into similar issue. I ended up patching `aws-efs-csi-driver` to get it to work with localstack thanks to the info from @drewm-jpl. I still install from the helm chart `https://kubernetes-sigs.github.io/aws-efs-csi-driver` but override the [values](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/29583689482f8677ab3c8efc04274a75b447e197/charts/aws-efs-csi-driver/values.yaml#L13) with this [custom docker image](https://hub.docker.com/layers/theslyone/aws-efs-csi-driver/latest/images/sha256-476bf2e6962f59179280c61cbd342571bc3eeecee3d95d4200851a4b8d8e962a?context=repo) hosted on dockerhub.

**Comment by mateusmullerzetaglobal** [comment]
@theslyone do you have the source code by any chance? would like to test this docker image, but I'm on Mac M1 (arm64). Thanks!
