### ISSUE TITLE
bug: Exception while connecting with LocalStack IoT MQTT broker via MQTT library for Java

### ISSUE THREAD

**Issue by akapti** [localstack/localstack#10214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running LocalStack-Pro 2.2.0 on Docker desktop using LocalStack testcontainer library.

Getting SocketTimeoutException exception when trying to connect with LocalStack MQTT broker using [aws-iot-device-sdk-java](https://github.com/aws/aws-iot-device-sdk-java) library for Java, which internally uses [Paho MQTT Java client library](https://eclipse.org/paho/clients/java/).

```java
Caused by: MqttException (0) - java.net.SocketTimeoutException: Read timed out
	at app//org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at app//org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:736)
	at java.base@11.0.19/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:484)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1417)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:159)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(WebSocketSecureNetworkModule.java:63)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:722)
	... 1 more
```

### Expected Behavior

Should be able to connect with LocalStack MQTT Broker for publishing and subscribing to topic in MQTT broker.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

- Below code shows how I am starting the LocalStack in Docker Desktop using testcontainer library.

```java
protected static final LocalStackContainer LOCAL_STACK_CONTAINER = new LocalStackContainer(LOCAL_STACK_IMAGE)
        .withEnv("LOCALSTACK_API_KEY", <LOCALSTACK_API_KEY>)
        .withEnv("SKIP_SSL_CERT_DOWNLOAD", "1")
        .withExposedPorts(4510, 4566);
    
LOCAL_STACK_CONTAINER.setPortBindings(Arrays.asList("443:4510", "4566:4566"));

LOCAL_STACK_CONTAINER.start();
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

- Below code shows how I am creating AWS IotClient and trying to connect with LocalStack MQTT broker.

```java
// Create basic credentials
BasicAWSCredentials basicAWSCredentials = new BasicAWSCredentials(LOCAL_STACK_CONTAINER.getAccessKey(),
            LOCAL_STACK_CONTAINER.getSecretKey());

// get the LocalStack endpoint
String awsServiceEndpoint = URI.create("http://" + localStack.getHost() + ":" + localStack.getMappedPort(4566)).toString();
System.out.println("AWS IoT endpoint: " + iotEndpoint); // always http://localhost:4566

// Create AWS IoT client
AWSIot iotClient = AWSIotClientBuilder.standard()
     .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(awsServiceEndpoint, LOCAL_STACK_CONTAINER.getRegion()))
     .withCredentials(new AWSStaticCredentialsProvider(basicAWSCredentials)).build();

// Describe the IoT endpoint
DescribeEndpointRequest describeEndpointRequest = new DescribeEndpointRequest();
DescribeEndpointResult describeEndpointResult = iotClient.describeEndpoint(describeEndpointRequest);

String iotEndpoint = describeEndpointResult.getEndpointAddress();
System.out.println("AWS IoT endpoint: " + iotEndpoint); // always localhost.localstack.cloud:4510

// Create signed URL
AwsIotWebSocketUrlSigner urlSigner  = new AwsIotWebSocketUrlSigner("localhost.localstack.cloud:443", "us-east-1");
urlSigner.updateCredentials(awsIotCredentials.getAccessKey(), awsIotCredentials.getSecretKey(), null);
String serviceUri = urlSigner.getSignedUrl(null);

// Create Mqtt Client
MqttClient mqttClient = new MqttClient(serviceUri, MqttClient.generateClientId(), new MemoryPersistence());
MqttConnectOptions connectOpts = new MqttConnectOptions();
connectOpts.setCleanSession(true);

// Connec to MqttClient
mqttClient.connect(connectOpts); // Exception is thrown here -> Caused by: java.net.SocketTimeoutException: Read timed out

// Subscribe
mqttClient.subscribe("topic_name", 0);
```

The above code works fine when I connect with actual AWS IoT MQTT Broker by using appropriate AWS IoT endpoint. 
**Example:** when endpoint `<account-specific prefix>.iot.<aws-region>.amazonaws.com:443` is passed in `AwsIotWebSocketUrlSigner` constructor, then `MqttClient` connects with actual AWS MQTT broker and able to publish / subscribe to the topic.

#### Following dependencies:
```gradle
implementation 'com.amazonaws:aws-java-sdk-iot:1.12.395'
implementation 'com.amazonaws:aws-iot-device-sdk-java:1.3.11' // this library internally uses org.eclipse.paho.client.mqttv3:1.2.4

integrationTestImplementation 'org.testcontainers:testcontainers:1.18.3'
integrationTestImplementation 'org.testcontainers:junit-jupiter:1.18.3'
integrationTestImplementation 'org.testcontainers:localstack:1.18.3'

```

#### Note:
I also tried changing the endpoint in `AwsIotWebSocketUrlSigner` constructor to `localhost.localstack.cloud:4510` and `localhost:4566`, But still getting same timeout error.

Kindly correct me, if it's an issue in my code or the way I am trying to connect is wrong.

### Environment

```markdown
- OS: Windows 11 with Docker desktop 4.27.1
- LocalStack: localstack-pro 2.2.0
```

**Comment by MarcelStranak** [comment]
Hi @akapti, can you please confirm if the issue is reproducible with the `localstack/localstack-pro:latest` Docker image? Thanks

**Comment by akapti** [comment]
> Hi @akapti, can you please confirm if the issue is reproducible with the `localstack/localstack-pro:latest` Docker image? Thanks

will try and let you know.

**Comment by akapti** [comment]
Hi @MarcelStranak 

I tried using latest version of localStack pro, and now getting different error. I have started the Localstack over HTTP, as starting it over HTTPS throws 

This is how the AwsIotWebSocketUrl looks like: `ws://000000000000.iot.us-east-1.localhost.localstack.cloud:4510/mqtt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=accesskey%2F20240220%2Fus-east-1%2Fiotdata%2Faws4_request&X-Amz-Date=20240220T165821Z&X-Amz-SignedHeaders=host&X-Amz-Signature=e9c57d8e7b034734b2218be45ac842d111556954b77b6bb3e441d699835c9457`

and getting following error: `java.io.IOException: WebSocket Response header: Invalid response from Server, It may not support WebSockets.`

and if I try with `wss://` I get following error: `javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake`  which is expected.

**Comment by MarcelStranak** [comment]
Hi @akapti, we provide the documentation here https://docs.localstack.cloud/user-guide/aws/iot/#authentication

**Comment by akapti** [comment]
Hi @MarcelStranak. Finally, things worked out for me.
The main issue was missing certificates.
### Here is the working code:

```java
public class TestDockerContainer {

    private static final String FIELD_LOCALSTACK_AUTH_TOKEN = "LOCALSTACK_AUTH_TOKEN";
    private static final String LOCALSTACK_AUTH_TOKEN = "my-auth-token-xxxxxxxxxxxx";
    private static final String LOCALSTACK_PRO_VERSION_3_1_0 = "localstack/localstack-pro:3.1.0";
    private static final String CUSTOM_LOCALSTACK_PRO_VERSION_3_1_0 = "custom-localstack-pro:3.1.0";

    public static Map<String, String> envMap = new HashMap<>();

    static {
        envMap.put(FIELD_LOCALSTACK_AUTH_TOKEN, LOCALSTACK_AUTH_TOKEN);
        envMap.put("CURL_CA_BUNDLE", "/etc/ssl/certs/ca-certificates.crt");
        envMap.put("REQUESTS_CA_BUNDLE", "/etc/ssl/certs/ca-certificates.crt");
        envMap.put("NODE_EXTRA_CA_CERTS", "/etc/ssl/certs/ca-certificates.crt");
    }

    public static void main(String[] args) throws Exception {

        Path certificatePath = Paths.get(Objects.requireNonNull(TestDockerContainer.class.getResource("<path-to-ca>")).toURI());

        // Create a docker image with custom (any Org) TLS certificate
        ImageFromDockerfile imageFromDockerfile = new ImageFromDockerfile(CUSTOM_LOCALSTACK_PRO_VERSION_3_1_0, false)
                .withFileFromPath(".", certificatePath)
                .withDockerfileFromBuilder(builder -> builder.from(LOCALSTACK_PRO_VERSION_3_1_0)
                        .run("apt-get update")
                        .copy("org-ca.crt", "/usr/local/share/ca-certificates/org-ca.crt")
                        .run("update-ca-certificates")
                        .copy("zscaler-ca.crt", "/usr/local/share/ca-certificates/zscaler-ca.crt")
                        .run("update-ca-certificates")
                        .env(envMap)
                        .build());

        // Create a generic container from image
        MqttClient mqttClient = null;
        try (GenericContainer<LocalStackContainer> genericContainer = new GenericContainer<>(imageFromDockerfile)) {

            // Start the container
            genericContainer.start();

            // Wait for sometime until the custom image is ready...
            // Because image download and creation will get triggered only after starting the container
            Thread.sleep(5000);

            // Create a Localstack container using above image
            try (LocalStackContainer localStackContainer = new LocalStackContainer(DockerImageName.parse(CUSTOM_LOCALSTACK_PRO_VERSION_3_1_0)
                    .asCompatibleSubstituteFor("localstack/localstack")).withExposedPorts(4566, 4510, 443)) {

                localStackContainer.setPortBindings(Arrays.asList("4510:4510", "4566:4566", "4555:443"));

                // Wait for some more time... just to be sure that image is ready and container is started
                Thread.sleep(3000);

                // stop the generic container and start the localstack container
                genericContainer.stop();
                localStackContainer.start();

                // Create basic credentials
                BasicAWSCredentials basicAWSCredentials = new BasicAWSCredentials(localStackContainer.getAccessKey(),
                        localStackContainer.getSecretKey());

                // Get the LocalStack endpoint
                String awsServiceEndpoint = localStackContainer.getEndpoint().toString();

                // Create AWS IoT client
                AWSIot iotClient =
                        AWSIotClientBuilder.standard()
                                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(awsServiceEndpoint,
                                localStackContainer.getRegion()))
                                .withCredentials(new AWSStaticCredentialsProvider(basicAWSCredentials)).build();

                // Describe the IoT endpoint
                DescribeEndpointRequest describeEndpointRequest = new DescribeEndpointRequest();
                DescribeEndpointResult describeEndpointResult = iotClient.describeEndpoint(describeEndpointRequest);

                // not mandatory...
                String iotMqttEndpoint = describeEndpointResult.getEndpointAddress();
                System.out.println("AWS IoT mqtt endpoint: " + iotMqttEndpoint);

                // Create AWS signed URL
                AwsIotWebSocketUrlSigner urlSigner = new AwsIotWebSocketUrlSigner("localhost.localstack.cloud:4510", "us-east-1");
                urlSigner.updateCredentials(localStackContainer.getAccessKey(), localStackContainer.getSecretKey(), null);

                // Replace wss (WebSocket over TLS) with ws for test environment only
                String serviceUri = urlSigner.getSignedUrl(null).replace("wss://", "ws://");

                // Create Mqtt Client
                mqttClient = new MqttClient(serviceUri, MqttClient.generateClientId(), new MemoryPersistence());
                MqttConnectOptions connectOpts = new MqttConnectOptions();
                connectOpts.setCleanSession(true);
                connectOpts.setKeepAliveInterval(90);

                // Connect to MqttClient
                mqttClient.connect(connectOpts);

                // MqttClient callback for testing of message consumption
                mqttClient.setCallback(new MqttCallbackExtended() {

                    @Override
                    public void connectComplete(boolean reconnect, String serverURI) {
                        System.out.println("mqtt connect complete: " + serverURI);
                    }

                    @Override
                    public void connectionLost(Throwable cause) {
                        System.err.println("connection lost");
                    }

                    @Override
                    public void messageArrived(String topic, MqttMessage message) throws Exception {
                        String msgPayload = new String(message.getPayload());
                        System.out.println("Message received from MQTT topic: " + msgPayload);
                    }

                    @Override
                    public void deliveryComplete(IMqttDeliveryToken token) {
                        System.out.println("Message delivery completes: " + token.getMessageId());
                    }
                });

                int qos = 1;
                // just to check if client is connected
                System.out.println(mqttClient.isConnected());
                final String topicName = "topic_name";

                // subscribe to the topic
                mqttClient.subscribe(topicName, qos);

                // publish messages to topic
                for (int i = 0; i < 6; i++) {
                    String msg = "Testing mqtt message: " + i;
                    MqttMessage message = new MqttMessage(msg.getBytes());
                    message.setQos(qos);
                    message.setId(i);
                    mqttClient.publish(topicName, message);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

```

### Maven dependency:
```maven
    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>localstack</artifactId>
            <version>1.19.5</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-core</artifactId>
            <version>1.12.662</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-iot</artifactId>
            <version>1.12.662</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.paho</groupId>
            <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
            <version>1.2.5</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-iot-device-sdk-java</artifactId>
            <version>1.3.11</version>
        </dependency>
    </dependencies>
</project>
```

Closing the ticket.
