### ISSUE TITLE
bug: 500 error when polling using AWS SDK

### ISSUE THREAD

**Issue by germanflighel** [localstack/localstack#10247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Localstack responds with an HTML 500 error response when trying to poll using Spring Cloud AWS 3.1.0 which uses AWS SDK under the hood.

```
2024-02-14T19:24:06.491:DEBUG:localstack.services.edge: IN(sqs): "POST /" - headers: {'Remote-Addr': '192.168.65.1', 'Host': 'localhost:4566', 'Amz-Sdk-Invocation-Id': '42d3c030-4417-50e4-a06d-728cedc5c04c', 'Amz-Sdk-Request': 'attempt=4; max=4', 'Authorization': 'AWS4-HMAC-SHA256 Credential=admin/20240214/us-east-1/sqs/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date;x-amz-target, Signature=3fb7040f9e167e968ed0cc42b4216783ddd101f8d170ed4e97aa6354b274c7c5', 'Content-Length': '202', 'Content-Type': 'application/x-amz-json-1.0', 'User-Agent': 'aws-sdk-java/2.24.2 Mac_OS_X/14.3.1 OpenJDK_64-Bit_Server_VM/17.0.3+7-LTS Java/17.0.3 kotlin/1.9.0-release-358 vendor/Azul_Systems__Inc. io/async http/NettyNio cfg/retry-mode/legacy', 'X-Amz-Date': '20240214T192406Z', 'X-Amz-Target': 'AmazonSQS.ReceiveMessage', 'X-Forwarded-For': '192.168.65.1, localhost:4566', 'x-localstack-edge': 'http://localhost:4566'} - data: b'{"QueueUrl":"http://localhost:4566/000000000000/use1-dev-pp-search-trx-api-transaction-events-sqs","AttributeNames":["All"],"MessageAttributeNames":["All"],"MaxNumberOfMessages":10,"WaitTimeSeconds":10}'
2024-02-14 19:24:06,504:API: 127.0.0.1 - - [14/Feb/2024 19:24:06] "POST / HTTP/1.1" 500 -
2024-02-14T19:24:06.506:DEBUG:localstack.services.edge: OUT(sqs): "POST /" - status: 500 - response headers: {'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '290', 'Server': 'Werkzeug/2.0.2 Python/3.8.12', 'Date': 'Wed, 14 Feb 2024 19:24:06 GMT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'etag,x-amz-version-id'} - response: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n

2024-02-14 19:24:06,514:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/sqs/sqs_starter.py", line 125, in sqs_responses_get_queue_name
    queue_url = self.querystring.get("QueueUrl")[0]
TypeError: 'NoneType' object is not subscriptable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 238, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/localstack/utils/patch.py", line 35, in proxy
    return new(target, *args, **kwargs)
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 163, in convert_to_flask_response_call
    return fn(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 127, in __call__
    result = self.callback(request, request.url, dict(request.headers))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 205, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 315, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 229, in _wrapper
    response = f(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 261, in _wrapper
    response = f(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/sqs/responses.py", line 79, in call_action
    status_code, headers, body = super().call_action()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 405, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/sqs/responses.py", line 382, in receive_message
    queue_name = self._get_queue_name()
  File "/opt/code/localstack/localstack/services/sqs/sqs_starter.py", line 131, in sqs_responses_get_queue_name
    queue_name = self.path.split("/")[2]
IndexError: list index out of range
```

### Expected Behavior

I expected it to returned the enqueue messages

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
```
version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: search-trx-localstack
    environment:
      - SERVICES=sqs,sns,s3
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=true
      - EDGE_PORT=4566
      - DEBUG=1
      - LS_LOG=trace-internal
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=admin
      - AWS_ACCESS_KEY_ID=admin
    ports:
      - '4566:4566'
    volumes:
      - ./volumes/localstack:/docker-entrypoint-initaws.d
      - ${TEMPDIR:-/tmp/localstack}:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  localstack:
    external: false
    driver: bridge
    name: localstack
```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

awslocal sqs create-queue --queue-name transaction-events-sqs

### Environment

```markdown
- OS: Mac OS 14.3.1, M1
- LocalStack: latest
```

### Anything else?

Polling using awslocal works just fine:

```
2024-02-14T19:26:53.266:DEBUG:localstack.services.edge: IN(sqs): "POST /" - headers: {'Remote-Addr': '192.168.65.1', 'Host': 'localhost:4566', 'Accept-Encoding': 'identity', 'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'aws-cli/2.4.19 Python/3.8.8 Darwin/23.3.0 exe/x86_64 prompt/off command/sqs.receive-message', 'X-Amz-Date': '20240214T192653Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=test/20240214/us-east-1/sqs/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=d77ccad9eed182056fcf707524b8f01949147c8455ea7e688abbbd45b6883ab3', 'Content-Length': '146', 'X-Forwarded-For': '192.168.65.1, localhost:4566', 'x-localstack-edge': 'http://localhost:4566'} - data: b'Action=ReceiveMessage&Version=2012-11-05&QueueUrl=http%3A%2F%2Flocalhost%3A4566%2F000000000000%2Fuse1-dev-pp-search-trx-api-transaction-events-sqs'
2024-02-14 19:26:53,293:API: 127.0.0.1 - - [14/Feb/2024 19:26:53] "POST / HTTP/1.1" 200 -
2024-02-14T19:26:53.295:DEBUG:localstack.services.edge: OUT(sqs): "POST /" - status: 200 - response headers: {'server': 'amazon.com', 'x-amzn-requestid': '3TL7OE2UMGHRKEK0QEN6X163ZJA7UPUZJFDAU2PWC102OHABOOYP', 'x-amz-crc32': '747391710', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '2415', 'Access-Control-Allow-Origin': '*', 'Date': 'Wed, 14 Feb 2024 19:26:53 GMT', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'etag,x-amz-version-id'} - response: b'<ReceiveMessageResponse><ReceiveMessageResult><Message><MessageId>29547f29-5baa-0541-7240-2c0160b7423c</MessageId><ReceiptHandle>tzuigonxsjjzdydnuajldwcnwehacqdztiizsbfmuyenvozdcnzjnihupodzrezrptayvxygcvghvhufgtqcxoutgpwpdbzkfrguoyeovxvkozgpfpoaunhxmvqrvmvwkhktvemcwzdrxcezsdqsvqbwukbtvxabynnkmbenthfkoreepcpukzgdt</ReceiptHandle><MD5OfBody>8aa3c26951e2cc66ee473195130ee323</MD5OfBody><Body>{&quot;id&quot;:&quot;79019b12-7b5f-4c29-b8b0-3cb6150f78d0&quot;,&quot;timestamp&quot;:&quot;2024-02-07T12:43:23.174841Z&quot;,&quot;operation_type&quot;:&quot;insert&quot;,&quot;payload&quot;:{&quot;table&quot;:&quot;transaction&quot;,&quot;data&quot;:{&quot;id&quot;:&quot;ac9e18b7-7759-40e2-afad-beaf923c626d&quot;,&quot;public_id&quot;:&quot;ctx-2OvH9Y82Odsmzt2gcCXieKZFZ3&quot;,&quot;card_id&quot;:1833,&quot;user_id&quot;:1831,&quot;client_id&quot;:&quot;cli-1zmhPjOD2CAdCZ0Cw0dfZjp2R8F&quot;,&quot;itc&quot;:&quot;100.00&quot;,&quot;life_cycle_trace&quot;:&quot;MCC0MCC011235  &quot;,&quot;local_date_time&quot;:&quot;2023-04-25T14:46:24Z&quot;,&quot;merchant_name&quot;:&quot;TEST&quot;,&quot;merchant_category_code&quot;:&quot;6011&quot;,&quot;merchant_address&quot;:&quot;1234 Main Street&quot;,&quot;country_code&quot;:&quot;ARG&quot;,&quot;transaction_amount&quot;:1,&quot;transaction_currency_code&quot;:&quot;ARS&quot;,&quot;settlement_amount&quot;:1,&quot;settlement_currency_code&quot;:&quot;USD&quot;,&quot;local_amount&quot;:1.75,&quot;local_currency_code&quot;:&quot;ARS&quot;,&quot;exchange_rate&quot;:0,&quot;source&quot;:&quot;CLEARING&quot;,&quot;type&quot;:&quot;PURCHASE&quot;,&quot;status&quot;:&quot;APPROVED&quot;,&quot;status_detail&quot;:&quot;APPROVED&quot;,&quot;point_type&quot;:&quot;MOTO&quot;,&quot;entry_mode&quot;:&quot;CHIP&quot;,&quot;origin&quot;:&quot;INTERNATIONAL&quot;,&quot;is_purged&quot;:&quot;false&quot;,&quot;is_forced&quot;:&quot;false&quot;,&quot;created_at&quot;:&quot;2023-04-25T14:46:26Z&quot;,&quot;transaction_amount_detail_id&quot;:&quot;413f0a1f-34f9-4a52-9fbb-1848534818e1&quot;,&quot;function_code&quot;:&quot;STANDARD&quot;,&quot;usd_amount&quot;:1,&quot;is_final_auth&quot;:&quot;false&quot;,&quot;is_normal_request&quot;:&quot;false&quot;,&quot;brand&quot;:&quot;MASTERCARD&quot;}}}</Body></Message></ReceiveMessageResult><ResponseMetadata><RequestId>3TL7OE2UMGHRKEK0QEN6X163ZJA7UPUZJFDAU2PWC102OHABOOYP</RequestId></ResponseMetadata></ReceiveMessageResponse>'
2024-02-14T19:26:53.295:DEBUG:localstack.services.edge: OUT(sqs): "POST /" - status: 200 - response headers: {'server': 'amazon.com', 'x-amzn-requestid': '3TL7OE2UMGHRKEK0QEN6X163ZJA7UPUZJFDAU2PWC102OHABOOYP', 'x-amz-crc32': '747391710', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '2415', 'Access-Control-Allow-Origin': '*', 'Date': 'Wed, 14 Feb 2024 19:26:53 GMT', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'etag,x-amz-version-id'} - response: b'<ReceiveMessageResponse><ReceiveMessageResult><Message><MessageId>29547f29-5baa-0541-7240-2c0160b7423c</MessageId><ReceiptHandle>tzuigonxsjjzdydnuajldwcnwehacqdztiizsbfmuyenvozdcnzjnihupodzrezrptayvxygcvghvhufgtqcxoutgpwpdbzkfrguoyeovxvkozgpfpoaunhxmvqrvmvwkhktvemcwzdrxcezsdqsvqbwukbtvxabynnkmbenthfkoreepcpukzgdt</ReceiptHandle><MD5OfBody>8aa3c26951e2cc66ee473195130ee323</MD5OfBody><Body>{&quot;id&quot;:&quot;79019b12-7b5f-4c29-b8b0-3cb6150f78d0&quot;,&quot;timestamp&quot;:&quot;2024-02-07T12:43:23.174841Z&quot;,&quot;operation_type&quot;:&quot;insert&quot;,&quot;payload&quot;:{&quot;table&quot;:&quot;transaction&quot;,&quot;data&quot;:{&quot;id&quot;:&quot;ac9e18b7-7759-40e2-afad-beaf923c626d&quot;,&quot;public_id&quot;:&quot;ctx-2OvH9Y82Odsmzt2gcCXieKZFZ3&quot;,&quot;card_id&quot;:1833,&quot;user_id&quot;:1831,&quot;client_id&quot;:&quot;cli-1zmhPjOD2CAdCZ0Cw0dfZjp2R8F&quot;,&quot;itc&quot;:&quot;100.00&quot;,&quot;life_cycle_trace&quot;:&quot;MCC0MCC011235  &quot;,&quot;local_date_time&quot;:&quot;2023-04-25T14:46:24Z&quot;,&quot;merchant_name&quot;:&quot;TEST&quot;,&quot;merchant_category_code&quot;:&quot;6011&quot;,&quot;merchant_address&quot;:&quot;1234 Main Street&quot;,&quot;country_code&quot;:&quot;ARG&quot;,&quot;transaction_amount&quot;:1,&quot;transaction_currency_code&quot;:&quot;ARS&quot;,&quot;settlement_amount&quot;:1,&quot;settlement_currency_code&quot;:&quot;USD&quot;,&quot;local_amount&quot;:1.75,&quot;local_currency_code&quot;:&quot;ARS&quot;,&quot;exchange_rate&quot;:0,&quot;source&quot;:&quot;CLEARING&quot;,&quot;type&quot;:&quot;PURCHASE&quot;,&quot;status&quot;:&quot;APPROVED&quot;,&quot;status_detail&quot;:&quot;APPROVED&quot;,&quot;point_type&quot;:&quot;MOTO&quot;,&quot;entry_mode&quot;:&quot;CHIP&quot;,&quot;origin&quot;:&quot;INTERNATIONAL&quot;,&quot;is_purged&quot;:&quot;false&quot;,&quot;is_forced&quot;:&quot;false&quot;,&quot;created_at&quot;:&quot;2023-04-25T14:46:26Z&quot;,&quot;transaction_amount_detail_id&quot;:&quot;413f0a1f-34f9-4a52-9fbb-1848534818e1&quot;,&quot;function_code&quot;:&quot;STANDARD&quot;,&quot;usd_amount&quot;:1,&quot;is_final_auth&quot;:&quot;false&quot;,&quot;is_normal_request&quot;:&quot;false&quot;,&quot;brand&quot;:&quot;MASTERCARD&quot;}}}</Body></Message></ReceiveMessageResult><ResponseMetadata><RequestId>3TL7OE2UMGHRKEK0QEN6X163ZJA7UPUZJFDAU2PWC102OHABOOYP</RequestId></ResponseMetadata></ReceiveMessageResponse>'
```

**Comment by bentsku** [comment]
Hello! This is due to newer versions of SDK now using JSON for SQS by default. Older versions of LocalStack are still using XML. You will need to update to LocalStack >= `3.0` in order for LocalStack to support JSON for the SQS service. Thanks!
