### ISSUE TITLE
bug: OrganizationAccountAccessRole - NoSuchEntity

### ISSUE THREAD

**Issue by hans-d** [localstack/localstack#10256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
2024-02-15T20:27:11.679  WARN --- [   asgi_gw_6] l.s.i.p.handler            : IAM Enforcement failed: An error occurred (NoSuchEntity) when calling the GetRole operation: Role OrganizationAccountAccessRole not found
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/iam/policy_engine/handler.py.enc", line 25, in __call__
    try:A=C.policy_engine.is_request_allowed(B)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/iam/policy_engine/engine.py.enc", line 462, in is_request_allowed
    F=B.action_extractor.get_required_iam_actions_for_request(context=A);D=B.check_actions_allowed_for_principal(required_actions=F,source_principal=C,context=A);B.process_callbacks(D,A);return D
                                                                                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/iam/policy_engine/engine.py.enc", line 244, in process_callbacks
    for B in A.callbacks:B(evaluation_result,context)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/iam/policy_generation/policy_generator.py.enc", line 83, in engine_callback
    B=A.generate_policy(evaluation_result,context);A.update_summary(B)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/iam/policy_generation/policy_generator.py.enc", line 68, in generate_policy
    if B:N=A.source_principal.get_underlying_principal().arn if A.source_principal.is_session()else A.source_principal.arn;I.append(SinglePolicy(resource=N,request=K,policy_document=B,policy_type=_D))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/iam/policy_engine/identity_policy_retrieval.py.enc", line 66, in get_underlying_principal
    def get_underlying_principal(A):B=A.iam_client.get_role(RoleName=A.role_name)['Role']['Arn'];return Role(role_name=A.role_name,iam_client=A.iam_client,arn=B,account=A.account)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchEntityException: An error occurred (NoSuchEntity) when calling the GetRole operation: Role OrganizationAccountAccessRole not found
```

### Expected Behavior

no errors raised

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

need to determine a minimal reproducible scenario.

### Environment

```markdown
- OS: mac/linux
- LocalStack: latest (3.1.0 +), pro
```

### Anything else?

According to https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_access.html, this role should be created on account creation

**Comment by pgeadas** [comment]
Hi. 

Is this an issue still? I just created a member account and cannot use the OrganizationAccountAccessRole to access it with the root user from the master account.

I get an `An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:iam::000000000000:root is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::060846880459:role/OrganizationAccountAccessRole
` error message. 

I'm identified as the root user:
```
❯ awslocal sts get-caller-identity
{
    "UserId": "AKIAIOSFODNN7EXAMPLE",
    "Account": "000000000000",
    "Arn": "arn:aws:iam::000000000000:root"
}
```

**Comment by MarcelStranak** [comment]
Hi @pgeadas, 

Please provide a comprehensive, reproducible example, including all the steps involved in creating and deploying the organization, roles, member accounts, and assuming roles.

**Comment by pgeadas** [comment]
```bash
# 1. Create the root organization (this exists already in the real AWS infrastructure)
awslocal organizations create-organization --feature-set ALL
# 2. List the roots to get the Id
awslocal organizations list-roots
# 2.1 create an OU under the root account
awslocal organizations create-organizational-unit --parent-id r-2dfz --name SeqeraComputeOU
# 3. Create a member account
awslocal organizations create-account --account-name SeqComputeAcc --email pedro@seqera.io
# 4. Move account from root to the created account (we can't create it directly in the OU...)
awslocal organizations move-account --account-id 203588168504 --destination-parent-id ou-2dfz-nqydb47z --source-parent-id r-2dfz
```

Now this is what does not work as it does in AWS. I go to my root account and I don't have the `OrganizationAccountAccessRole` there, to attach a policy to and to use it to create the remaining resources I need.

How can I proceed to achieve the same result?
