### ISSUE TITLE
bug: S3 Provider V3 fails on Presigned Uploads

### ISSUE THREAD

**Issue by Garethp** [localstack/localstack#10309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With the new S3 Provider that Localstack V3 uses, when I try to upload a file in node using presigned S3 URLs, I receive the following error in the docker logs, but the request itself succeeds. No file is found in the bucket afterwards:

```
localstack-bugs | 2024-02-23T15:50:21.627 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
localstack-bugs | Traceback (most recent call last):
localstack-bugs |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
localstack-bugs |     handler(self, self.context, response)
localstack-bugs |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 112, in __call__
localstack-bugs |     handler(chain, context, response)
localstack-bugs |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 82, in __call__
localstack-bugs |     skeleton_response = self.skeleton.invoke(context)
localstack-bugs |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-bugs |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
localstack-bugs |     return self.dispatch_request(serializer, context, instance)
localstack-bugs |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-bugs |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request
localstack-bugs |     result = handler(context, instance) or {}
localstack-bugs |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-bugs |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
localstack-bugs |     return self.fn(*args, **kwargs)
localstack-bugs |            ^^^^^^^^^^^^^^^^^^^^^^^^
localstack-bugs |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/s3/v3/provider.py", line 3470, in post_object
localstack-bugs |     fileobj = context.request.files["file"]
localstack-bugs |               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
localstack-bugs |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/werkzeug/datastructures/structures.py", line 192, in __getitem__
localstack-bugs |     raise exceptions.BadRequestKeyError(key)
localstack-bugs | werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
localstack-bugs | 2024-02-23T15:50:21.630  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.PostObject => 500 (InternalError)
localstack-bugs | 2024-02-23T15:50:24.221  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.ListObjectsV2 => 200
```

### Expected Behavior

The file should be uploaded correctly. If you provide `PROVIDER_OVERRIDE_S3=legacy_v2`, then it does work correctly

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```ts
export class BucketStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    new Bucket(this, "s3-bucket", {
      bucketName: "test-bucket",
    });
  }
}
```

```ts
import { createPresignedPost } from "@aws-sdk/s3-presigned-post";
import { S3Client } from "@aws-sdk/client-s3";
import { promises as fs } from "fs";
import path from "path";

void (async () => {
  const s3Client = new S3Client({
    endpoint: "https://localhost.localstack.cloud:4566",
    region: "eu-west-2",
    credentials: {
      accessKeyId: "test",
      secretAccessKey: "test",
    },
  });

  const presignedUpload = await createPresignedPost(s3Client, {
    Bucket: "test-bucket",
    Key: "package.json",
  });

  const file = await fs.readFile(path.join(__dirname, "./package.json"));
  const form = new FormData();
  for (const key of Object.keys(presignedUpload.fields)) {
    form.append(key, presignedUpload.fields[key]);
  }
  // @ts-ignore
  form.append("file", file);

  await fetch("https://s3.localhost.localstack.cloud:4566/test-bucket/", {
    method: "POST",
    body: form,
  });
})();
```

```ts
#!/bin/bash

yarn ts-node test.ts

echo "The following files are in the S3 Bucket"
awslocal s3 ls test-bucket
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 3.1
```

### Anything else?

I've reproduced the issue here: https://github.com/Garethp/localstack-bugs/tree/s3-presigned-upload

If you clone down the branch `s3-presigned-upload`, run `yarn install` and then `./start.sh` you should see the issue in action

**Comment by bentsku** [comment]
Hello @Garethp and thanks for the report!

Could you confirm this work against AWS? I think the issue might stems from the lack of `Content-Type` header indicating the request contains form data. (`Content-Type: multipart/form-data;`) 

After looking at the documentation for `PresignedPost`:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/HTTPPOSTExamples.html

In the Node.js documentation, they directly call `FormData.submit` which must set the right header. 
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-s3-presigned-post/

And in our Python tests, setting files directly to the request will encode the request automatically, which is why we didn't detect this issue.

It seems the request does not succeed, as it return a 500 error code:
`AWS s3.PostObject => 500 (InternalError)`

It's possible that AWS does not need the Content-Type to be set, in which case we need to properly cover it as well, but I would like to be sure. Thanks! 

If it doesn't work against AWS either, maybe setting the following would work:
```
  await fetch("https://s3.localhost.localstack.cloud:4566/test-bucket/", {
    method: "POST",
    body: form,
    headers: {
      "Content-Type": "multipart/form-data",
    },
   // you can also use the following:
   headers: { 
     ... form.getHeaders(),
  },
  });
```

**Comment by Garethp** [comment]
Hey @bentsku, thanks for the quick response on this.

Yeah, I can confirm that this works on AWS. I copied the code almost verbatim (Just condensing it down a bit to simplify it) from some integration tests we run against dev stage after deploying into AWS.

**Comment by bentsku** [comment]
Thanks again for the reproducer!

I've found the issue, the multipart header was properly sent, it was that the file content was passed a simple field instead of a file object in the form, which we didn't support unfortunately.
I can see AWS supporting it in a different way as well, as this mode does not support the replacement of `${filename}` variable (see `The ${filename} Variable` in https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/PresignedPost.html). 

The linked PR will fix this issue once merged. 

I could validate the fix with your reproducer:
```bash
$ sh start.sh
The following files are in the S3 Bucket
2024-02-24 01:40:03        424 package.json
```

Thanks a lot for the detailed reproducer!

**Comment by cchentyro** [comment]
Hi, @bentsku , we met another issue when do GET.
```
2024-05-17T09:08:44.719 ERROR --- [et.reactor-0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/presigned_url.py", line 23, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack/services/s3/presigned_url.py", line 201, in __call__
    validate_presigned_url_s3v4(context)
  File "/opt/code/localstack/localstack/services/s3/presigned_url.py", line 425, in validate_presigned_url_s3v4
    sigv4_context, exception = _find_valid_signature_through_ports(context)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/services/s3/presigned_url.py", line 487, in _find_valid_signature_through_ports
    sigv4_context = S3SigV4SignatureContext(context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/services/s3/presigned_url.py", line 543, in __init__
    region = self._query_parameters["X-Amz-Credential"].split("/")[2]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
Guess maybe there is no url decode for those params?
Thank you

**Comment by cchentyro** [comment]
raised ticket https://github.com/localstack/localstack/issues/10844
