### ISSUE TITLE
ApiGateway doesn't work with simple AWSClient : responseTemplates should not be null

### ISSUE THREAD

**Issue by aesteve** [localstack/localstack#1030]
Hello and thanks for all the work you've done.

I'm using the APIGateway within localstack to test some integration of AWSClient.

When using `apiGatewayAsyncClient.putIntegration` the AWSAsyncClient crashes.

Here's how the request is created: 
```
                gatewayClient.putIntegration( pir ->
                    pir.restApiId(apiId)
                        .resourceId(parentId)
                        .httpMethod(METHOD.toString())
                        .integrationHttpMethod(METHOD.toString())
                        .type(IntegrationType.MOCK)
                )

```

Here's the request sent: 
```
DEBUG software.amazon.awssdk.request - Sending Request: DefaultSdkHttpFullRequest(httpMethod=PUT, protocol=http, host=localhost, port=4567, encodedPath=/restapis/4873271037/resources/3121670211/methods/GET/integration, headers=[Accept, amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent], queryParameters=[])
```

Here's the response sent by localstack's API Gateway: 
```
{
"httpMethod": "GET", 
"requestTemplates": null, 
"type": "MOCK", 
"uri": null, 
"integrationResponses": {"200": {"statusCode": 200, "responseTemplates": {"application/json": null}}}
}
```

And here's the stacktrace of the AWSAsyncClient: 

```
Caused by: java.lang.NullPointerException
	at java.util.HashMap.merge(HashMap.java:1224)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at software.amazon.awssdk.services.apigateway.model.MapOfStringToStringCopier.copy(MapOfStringToStringCopier.java:31)
	at software.amazon.awssdk.services.apigateway.model.IntegrationResponse$BuilderImpl.responseTemplates(IntegrationResponse.java:612)
	at software.amazon.awssdk.services.apigateway.model.IntegrationResponse.lambda$setter$1(IntegrationResponse.java:367)
	at software.amazon.awssdk.core.SdkField.set(SdkField.java:162)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshallStructured(JsonProtocolUnmarshaller.java:195)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshallStructured(JsonProtocolUnmarshaller.java:99)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.lambda$unmarshallMap$1(JsonProtocolUnmarshaller.java:113)
	at java.util.HashMap.forEach(HashMap.java:1288)
	at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshallMap(JsonProtocolUnmarshaller.java:111)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshallStructured(JsonProtocolUnmarshaller.java:195)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:182)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:153)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:79)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:36)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonResponseHandler.handle(AwsJsonResponseHandler.java:43)
	at software.amazon.awssdk.core.client.handler.BaseClientHandler.lambda$interceptorCalling$2(BaseClientHandler.java:117)
	at software.amazon.awssdk.core.client.handler.AttachHttpMetadataResponseHandler.handle(AttachHttpMetadataResponseHandler.java:40)
	at software.amazon.awssdk.core.client.handler.AttachHttpMetadataResponseHandler.handle(AttachHttpMetadataResponseHandler.java:28)
	at software.amazon.awssdk.core.internal.http.async.SyncResponseHandlerAdapter.lambda$prepare$0(SyncResponseHandlerAdapter.java:85)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

The client is not very resilient to nulls, well, they could improve that.

But the reponse from localstack's gateway is really weird.
Why would it add `responseTemplates` to the response ? Where does `application/json` come from ?

According to https://docs.aws.amazon.com/apigateway/latest/developerguide/create-api-using-awssdk.html , I was expecting something like :

```
{
    "httpMethod": "GET", 
    "passthroughBehavior": "WHEN_NO_MATCH", 
    "cacheKeyParameters": [], 
    "type": "MOCK", 
    "uri": null, 
    "cacheNamespace": "8sxa2j"
}
```

 which is... really different.

I must have missed something obvious, but where does this response come from ? Maybe by reading the code I could have a hint on what I need to change.
The locastack's gateway seems pre-configured with a weird `['application/json': null]` map.

**Comment by whummer** [comment]
Thanks for reporting @aesteve . It's been a while since this issue has been opened, but it has now been fixed in #2373 . The change should be available in the `latest` version of the Docker image. Please report here if the problem persists. Thanks
