### ISSUE TITLE
bug: exception while calling cloudformation.UpdateStack

### ISSUE THREAD

**Issue by Mcbeer** [localstack/localstack#10313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to deploy a Serverless Framework project to Localstack, it get's stuck on "exception while calling cloudformation.UpdateStack" - The project is using S3, SQS, DynamoDB (+ Streams), EventBridge and API Gateway V2 (HTTP API) - In case that tells you anything

### Expected Behavior

Expected behavior is for the project to just deploy as normal

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   DEBUG=1 localstack start

### Environment

```markdown
- OS: MacOS Sonoma 14.3.1
- LocalStack: 3.1.0
```

### Anything else?

Full error log:

```Using serverless-localstack
Using serverless-localstack
Using serverless-localstack
Using serverless-localstack
Using serverless-localstack
Using serverless-localstack
Using serverless-localstack
Using serverless-localstack
Using serverless-localstack
Using serverless-localstack
Using serverless-localstack
Using serverless-localstack
serverless-localstack: Reconfigured endpoints
serverless-localstack: Reconfigured endpoints
serverless-localstack: Reconfigured endpoints
serverless-localstack: Reconfigured endpoints
serverless-localstack: Reconfigured endpoints
serverless-localstack: Reconfigured endpoints
serverless-localstack: Reconfigured endpoints
serverless-localstack: Reconfigured endpoints
serverless-localstack: Reconfigured endpoints
serverless-localstack: Reconfigured endpoints
serverless-localstack: Reconfigured endpoints
serverless-localstack: Reconfigured endpoints

Deploying ugc-service to stage dev (eu-west-1)

Packaging
Excluding development dependencies for function "app"
Excluding development dependencies for function "onSQSEventHandler"
Excluding development dependencies for function "authorizerFunc"
Excluding development dependencies for function "onUserDeleted"
Excluding development dependencies for function "onAppealOrReport"
Retrieving CloudFormation stack
Uploading
Uploading CloudFormation file to S3
Uploading State file to S3
Uploading service app.zip file to S3 (805.21 kB)
Uploading service onSQSEventHandler.zip file to S3 (5.89 MB)
Uploading service authorizerFunc.zip file to S3 (135.05 kB)
Uploading service onUserDeleted.zip file to S3 (235.32 kB)
Uploading service onAppealOrReport.zip file to S3 (802.88 kB)
Skipping template validation: Unsupported in Localstack
Updating CloudFormation stack
Recoverable error occurred (exception while calling cloudformation.UpdateStack: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 112, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 82, in __call__
    skeleton_response = self.skeleton.invoke(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(serializer, context, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request
    result = handler(context, instance) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/api/core.py", line 161, in operation_marker
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/provider.py", line 339, in update_stack
    resolved_stack_conditions = resolve_stack_conditions(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_utils.py", line 108, in resolve_stack_conditions
    result[condition_name] = resolve_condition(
                             ^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_utils.py", line 214, in resolve_condition
    account_id, region_name, v[0], conditions, parameters, mappings, stack_name
                             ~^^^
KeyError: 0
), sleeping for ~6 seconds. Try 1 of 4
Recoverable error occurred (exception while calling cloudformation.UpdateStack: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 112, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 82, in __call__
    skeleton_response = self.skeleton.invoke(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(serializer, context, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request
    result = handler(context, instance) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/api/core.py", line 161, in operation_marker
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/provider.py", line 339, in update_stack
    resolved_stack_conditions = resolve_stack_conditions(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_utils.py", line 108, in resolve_stack_conditions
    result[condition_name] = resolve_condition(
                             ^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_utils.py", line 214, in resolve_condition
    account_id, region_name, v[0], conditions, parameters, mappings, stack_name
                             ~^^^
KeyError: 0
), sleeping for ~4 seconds. Try 2 of 4
Recoverable error occurred (exception while calling cloudformation.UpdateStack: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 112, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 82, in __call__
    skeleton_response = self.skeleton.invoke(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(serializer, context, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request
    result = handler(context, instance) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/api/core.py", line 161, in operation_marker
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/provider.py", line 339, in update_stack
    resolved_stack_conditions = resolve_stack_conditions(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_utils.py", line 108, in resolve_stack_conditions
    result[condition_name] = resolve_condition(
                             ^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_utils.py", line 214, in resolve_condition
    account_id, region_name, v[0], conditions, parameters, mappings, stack_name
                             ~^^^
KeyError: 0
), sleeping for ~6 seconds. Try 3 of 4
Recoverable error occurred (exception while calling cloudformation.UpdateStack: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 112, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 82, in __call__
    skeleton_response = self.skeleton.invoke(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(serializer, context, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request
    result = handler(context, instance) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/api/core.py", line 161, in operation_marker
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/provider.py", line 339, in update_stack
    resolved_stack_conditions = resolve_stack_conditions(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_utils.py", line 108, in resolve_stack_conditions
    result[condition_name] = resolve_condition(
                             ^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_utils.py", line 214, in resolve_condition
    account_id, region_name, v[0], conditions, parameters, mappings, stack_name
                             ~^^^
KeyError: 0
), sleeping for ~5 seconds. Try 4 of 4```

**Comment by Mcbeer** [comment]
Upon further inspection of the code, it appears this could be the source of the problem: https://github.com/localstack/localstack/blob/113004ccf836a15608c9dbe96a9f2ef13437dc75/localstack/services/cloudformation/engine/template_utils.py#L142

I am using conditions to filter out AWS Backup from the deployment to local, since i cannot get it to create the BackupVaults currently.
