### ISSUE TITLE
java.lang.NoSuchMethodError com/fasterxml/jackson/core/JsonToken when calling methods on DynamoDBMapper from a Java Lambda function

### ISSUE THREAD

**Issue by johncook-snap40** [localstack/localstack#1031]
When I run a Lambda function that calls methods on the `DynamoDBMapper`client my code throws this exception.

`Exception in thread "main" java.lang.NoSuchMethodError: com.amazonaws.transform.JsonUnmarshallerContext.getCurrentToken()Lcom/fasterxml/jackson/core/JsonToken;
	at com.amazonaws.services.dynamodbv2.model.transform.UpdateItemResultJsonUnmarshaller.unmarshall(UpdateItemResultJsonUnmarshaller.java:39)
	at com.amazonaws.services.dynamodbv2.model.transform.UpdateItemResultJsonUnmarshaller.unmarshall(UpdateItemResultJsonUnmarshaller.java:29)
	at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:118)
	at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:43)
	at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:70)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1545)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1270)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:3239)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:3215)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeUpdateItem(AmazonDynamoDBClient.java:2947)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.updateItem(AmazonDynamoDBClient.java:2922)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$SaveObjectHandler.doUpdateItem(DynamoDBMapper.java:854)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$2.executeLowLevelRequest(DynamoDBMapper.java:594)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$SaveObjectHandler.execute(DynamoDBMapper.java:733)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.save(DynamoDBMapper.java:623)
	at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.save(AbstractDynamoDBMapper.java:123)
	at com.snap40.functions.smoothing.dao.DefaultSingleSegmentObservationDao.store(DefaultSingleSegmentObservationDao.java:49)
	at com.snap40.functions.smoothing.services.DefaultSmoothingService.process(DefaultSmoothingService.java:48)
	at com.snap40.functions.smoothing.Main.lambda$function$0(Main.java:29)
	at org.springframework.cloud.function.core.FluxFunction.lambda$apply$0(FluxFunction.java:47)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:244)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:202)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:156)
	at reactor.core.publisher.BlockingIterable$SubscriberIterator.onSubscribe(BlockingIterable.java:218)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:140)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:64)
	at reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63)
	at reactor.core.publisher.Flux.subscribe(Flux.java:6877)
	at reactor.core.publisher.BlockingIterable.iterator(BlockingIterable.java:80)
	at org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler.result(SpringBootRequestHandler.java:54)
	at org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler.handleRequest(SpringBootRequestHandler.java:49)
	at org.springframework.cloud.function.adapter.aws.SpringBootKinesisEventHandler.handleRequest(SpringBootKinesisEventHandler.java:59)
	at org.springframework.cloud.function.adapter.aws.SpringBootKinesisEventHandler.handleRequest(SpringBootKinesisEventHandler.java:39)
	at com.snap40.functions.smoothing.handler.LocalstackHandler.handleRequest(LocalstackHandler.java:48)
	at com.snap40.functions.smoothing.handler.LocalstackHandler.handleRequest(LocalstackHandler.java:15)
	at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:100)`

I am using Spring Cloud Function, version 2.0.6.RELEASE, and version 1.11.313 of the AWS SDK Jars, including `aws-java-sdk-dynamodb`. The Localstack version is 0.8.7

**Comment by vidyaramanathan** [comment]
I get the same error when updating the item (`AmazonDynamoDB.updateItem())` in LocalStack DynamoDB. I'm using localstack:latest,  aws-java-sdk-dynamodb and other SDK jars with 1.11.354 version. 

`Exception in thread "main" java.lang.NoSuchMethodError: com.amazonaws.transform.JsonUnmarshallerContext.getCurrentToken()Lcom/fasterxml/jackson/core/JsonToken;
	at com.amazonaws.services.dynamodbv2.model.transform.UpdateItemResultJsonUnmarshaller.unmarshall(UpdateItemResultJsonUnmarshaller.java:39)
	at com.amazonaws.services.dynamodbv2.model.transform.UpdateItemResultJsonUnmarshaller.unmarshall(UpdateItemResultJsonUnmarshaller.java:29)
	at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:118)
	at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:43)
	at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:70)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1545)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1270)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:3443)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:3419)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeUpdateItem(AmazonDynamoDBClient.java:3153)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.updateItem(AmazonDynamoDBClient.java:3128)
....
	at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:100)`

**Comment by johncook-snap40** [comment]
The problem was conflicting versions of Jackson classes when mixing different AWS client jars, probably the  Kinesis and DynamoDB clients. The fix was to use the `<relocation>` configuration element in the Maven Shade Plugin. Here is the bit from my POM that works for me:
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.mycompany</groupId>
    <artifactId>mylambda</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>mylambda</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <aws-lambda-java-core.version>1.2.0</aws-lambda-java-core.version>
        <aws-java-sdk.version>1.11.313</aws-java-sdk.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-core</artifactId>
            <version>${aws-java-sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-dynamodb</artifactId>
            <version>${aws-java-sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-kinesis</artifactId>
            <version>${aws-java-sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-events</artifactId>
            <version>2.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-core</artifactId>
            <version>${aws-lambda-java-core.version}</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-log4j</artifactId>
            <version>1.0.0</version>
        </dependency>
        
        
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.1</version>
                <configuration>
                    <createDependencyReducedPom>false</createDependencyReducedPom>
                    <shadedArtifactAttached>true</shadedArtifactAttached>
                    <shadedClassifierName>aws</shadedClassifierName>
                    <relocations>
                        
                        
                        <relocation>
                            <pattern>com.fasterxml.jackson</pattern>
                            <shadedPattern>com.amazonaws.thirdparty.jackson</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.apache.http</pattern>
                            <shadedPattern>com.amazonaws.thirdparty.apache.http</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>org.apache.commons</pattern>
                            <shadedPattern>com.amazonaws.thirdparty.apache.commons</shadedPattern>
                        </relocation>
                        <relocation>
                            <pattern>software.amazon.ion</pattern>
                            <shadedPattern>com.amazonaws.thirdparty.ion</shadedPattern>
                        </relocation>
                    </relocations>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>`

**Comment by vidyaramanathan** [comment]
🏆Thank you! that works!

**Comment by johncook-snap40** [comment]
This not a Localstack bug, rather an issue with AWS client Jar dependencies. It seems that the `maven-shade-plugin` `relocations` section in the POM listed above is the fix.

**Comment by johncook-snap40** [comment]
This not a Localstack bug, as it appears to be an issue with AWS client Jar dependencies. Using the `maven-shade-plugin` `relocations` section in the POM listed above fixes the issue

**Comment by Ghilteras** [comment]
I actually have the same issue, but adding the `<relocation>` bit did not solve it. I've tried to take away the localstack-util dependency from my pom.xml either, but I still get the `NoSuchMethodError` on `getCurrentToken`

any hints?

**Comment by krrg** [comment]
> This not a Localstack bug, as it appears to be an issue with AWS client Jar dependencies. Using the `maven-shade-plugin` `relocations` section in the POM listed above fixes the issue

@johncook-snap40 You may be only half right. I still believe this is a localstack bug.

My lambda is deployed as a fat jar that contains all necessary dependencies to run on its own. However, if you look at the source for localstack_executors, you'll note that localstack also loads its own fat jar file containing a bunch of AWS classes into the classpath. 

What this means in practice is that the `com.amazonaws.transform.JsonUnmarshallerContext` is loaded from localstack's fat jar, not from your lambda jar.  You can test this easily simply by printing out the location where the problematic class is loaded from:

```
System.out.println(com.amazonaws.transform.JsonUnmarshallContext.class.getProtectionDomain().getCodeSource())
```
Outputs:
```
(file:/opt/code/localstack/localstack/infra/localstack-utils-fat.jar <no signer certificates>)
```
And so you can quickly end up in a terrible state where you've got different versions of the AWS SDKs floating around in your classpath.

We need to work out a way to force the JVM to reload the problematic classes from the lambda's jar, not the localstack jar. Shadowing/relocation sort of works, but it sounds like people have had mixed results.

**Comment by Ghilteras** [comment]
This issue should not be closed.
