### ISSUE TITLE
SQS doesn't work

### ISSUE THREAD

**Issue by realies** [localstack/localstack#1032]
How does one run SQS on localstack? Can endpoints be configured? Localstack WEB UI is always blank.

```
version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
      - 8008:8008
    environment:
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=8008
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
  sqs-insight:
    image: realies/sqs-insight
    environment:
      - mode=dynamicEndpoint
      - url=http://localstack:4576/
    command: ["/wait-for", "localstack:4576", "-t", "30", "--", "/init.sh"]
    ports:
      - 3000:3000
    depends_on:
      - localstack
```

produces

```
localstack_1_ac344c837efb | 2018-11-29 09:36:55,652 CRIT Supervisor running as root (no user in config file)
localstack_1_ac344c837efb | 2018-11-29 09:36:55,656 INFO supervisord started with pid 1
localstack_1_ac344c837efb | 2018-11-29 09:36:56,661 INFO spawned: 'dashboard' with pid 9
localstack_1_ac344c837efb | 2018-11-29 09:36:56,668 INFO spawned: 'infra' with pid 10
localstack_1_ac344c837efb | (. .venv/bin/activate; bin/localstack web)
localstack_1_ac344c837efb | (. .venv/bin/activate; exec bin/localstack start)
localstack_1_ac344c837efb | 2018-11-29 09:36:57,698 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1_ac344c837efb | 2018-11-29 09:36:57,698 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1_ac344c837efb | Starting local dev environment. CTRL-C to quit.
localstack_1_ac344c837efb | 2018-11-29T09:36:58:INFO:werkzeug:  * Running on http://0.0.0.0:8008/ (Press CTRL+C to quit)
localstack_1_ac344c837efb | 2018-11-29T09:36:58:INFO:werkzeug:  * Restarting with stat
localstack_1_ac344c837efb | 2018-11-29T09:36:59:WARNING:werkzeug:  * Debugger is active!
localstack_1_ac344c837efb | 2018-11-29T09:36:59:INFO:werkzeug:  * Debugger PIN: 238-623-801
localstack_1_ac344c837efb | Starting mock S3 (http port 4572)...
localstack_1_ac344c837efb | Starting mock SQS (http port 4576)...
sqs-insight_1_119d8941d77b | yarn run v1.12.3
sqs-insight_1_119d8941d77b | $ node index.js
sqs-insight_1_119d8941d77b | Loading config file from "/sqs-insight/lib/../config/config_local.json"
localstack_1_ac344c837efb | 2018-11-29T09:37:02:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4561): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7e2cc1cd0>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
localstack_1_ac344c837efb |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 201, in forward
localstack_1_ac344c837efb |     headers=forward_headers, stream=True)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
localstack_1_ac344c837efb |     return request('post', url, data=data, json=json, **kwargs)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
localstack_1_ac344c837efb |     return session.request(method=method, url=url, **kwargs)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
localstack_1_ac344c837efb |     resp = self.send(prep, **send_kwargs)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
localstack_1_ac344c837efb |     r = adapter.send(request, **kwargs)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
localstack_1_ac344c837efb |     raise ConnectionError(e, request=request)
localstack_1_ac344c837efb | ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4561): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7e2cc1cd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
localstack_1_ac344c837efb | 
localstack_1_ac344c837efb | 2018-11-29T09:37:02:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4561): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7e2eda110>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
localstack_1_ac344c837efb |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 201, in forward
localstack_1_ac344c837efb |     headers=forward_headers, stream=True)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
localstack_1_ac344c837efb |     return request('post', url, data=data, json=json, **kwargs)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
localstack_1_ac344c837efb |     return session.request(method=method, url=url, **kwargs)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
localstack_1_ac344c837efb |     resp = self.send(prep, **send_kwargs)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
localstack_1_ac344c837efb |     r = adapter.send(request, **kwargs)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
localstack_1_ac344c837efb |     raise ConnectionError(e, request=request)
localstack_1_ac344c837efb | ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4561): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7e2eda110>: Failed to establish a new connection: [Errno 111] Connection refused',))
localstack_1_ac344c837efb | 
localstack_1_ac344c837efb | 2018-11-29T09:37:03:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4561): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7e2eda250>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
localstack_1_ac344c837efb |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 201, in forward
localstack_1_ac344c837efb |     headers=forward_headers, stream=True)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
localstack_1_ac344c837efb |     return request('post', url, data=data, json=json, **kwargs)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
localstack_1_ac344c837efb |     return session.request(method=method, url=url, **kwargs)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
localstack_1_ac344c837efb |     resp = self.send(prep, **send_kwargs)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
localstack_1_ac344c837efb |     r = adapter.send(request, **kwargs)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
localstack_1_ac344c837efb |     raise ConnectionError(e, request=request)
localstack_1_ac344c837efb | ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4561): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7e2eda250>: Failed to establish a new connection: [Errno 111] Connection refused',))
localstack_1_ac344c837efb | 
localstack_1_ac344c837efb | 2018-11-29T09:37:03:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4561): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7e2eda390>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
localstack_1_ac344c837efb |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 201, in forward
localstack_1_ac344c837efb |     headers=forward_headers, stream=True)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
localstack_1_ac344c837efb |     return request('post', url, data=data, json=json, **kwargs)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
localstack_1_ac344c837efb |     return session.request(method=method, url=url, **kwargs)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
localstack_1_ac344c837efb |     resp = self.send(prep, **send_kwargs)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
localstack_1_ac344c837efb |     r = adapter.send(request, **kwargs)
localstack_1_ac344c837efb |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
localstack_1_ac344c837efb |     raise ConnectionError(e, request=request)
localstack_1_ac344c837efb | ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4561): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe7e2eda390>: Failed to establish a new connection: [Errno 111] Connection refused',))
localstack_1_ac344c837efb | 
sqs-insight_1_119d8941d77b | Unable to load queues for  undefined
sqs-insight_1_119d8941d77b | Config contains 0 queues.
sqs-insight_1_119d8941d77b | listening on port 3000
localstack_1_ac344c837efb | Ready.
```

**Comment by kattarg** [comment]
Your environment should Use `HOSTNAME_EXTERNAL=localstack` and try that should work...If you are running different way from local machine against your environment , try to have different docker-compose configurations for localhost vs pipelines.

**Comment by whummer** [comment]
Thanks for reporting @realies . Looks like this is only an intermittent error during startup, as the stack finally outputs `Ready.` (which indicates that the service should be available).

Can you please do another test with the latest version of the `localstack/localstack` Docker image? Please also post the image ID here. Thanks

**Comment by whummer** [comment]
Closing this issue due to inactivity. Please re-open if the problem persists.
