### ISSUE TITLE
Failed building wheel for pycryptodome for v0.8.8

### ISSUE THREAD

**Issue by mosesyu** [localstack/localstack#1038]
I just get the latest code and try to build docker image locally, and get the error below. Does anyone have the same problem?

```
make docker-build
docker build -t localstack/localstack .
Sending build context to Docker daemon   3.42MB
Step 1/24 : FROM localstack/java-maven-node-python
 ---> 9bd51dabaced
Step 2/24 : MAINTAINER Waldemar Hummer (waldemar.hummer@gmail.com)
 ---> Using cache
 ---> 854735fd9c3b
Step 3/24 : LABEL authors="Waldemar Hummer (waldemar.hummer@gmail.com), Gianluca Bortoli (giallogiallo93@gmail.com)"
 ---> Using cache
 ---> e65a31f6d2e4
Step 4/24 : ADD Makefile requirements.txt ./
 ---> Using cache
 ---> 1ebf78f1d134
Step 5/24 : RUN mkdir -p localstack/utils/kinesis/ && mkdir -p localstack/services/ &&   touch localstack/__init__.py localstack/utils/__init__.py localstack/services/__init__.py localstack/utils/kinesis/__init__.py
 ---> Using cache
 ---> 31ea57d3b676
Step 6/24 : ADD localstack/constants.py localstack/config.py localstack/
 ---> Using cache
 ---> ba9888056c2a
Step 7/24 : ADD localstack/services/install.py localstack/services/
 ---> Using cache
 ---> 1af59128d1fc
Step 8/24 : ADD localstack/utils/common.py localstack/utils/
 ---> Using cache
 ---> 5c02fd18fde0
Step 9/24 : ADD localstack/utils/kinesis/ localstack/utils/kinesis/
 ---> Using cache
 ---> af2ad3701c98
Step 10/24 : ADD localstack/ext/ localstack/ext/
 ---> Using cache
 ---> 966b42b379a6
Step 11/24 : RUN make install
 ---> Running in 3434bf74c8a8
(test `which virtualenv` || pip install --user virtualenv) && \
	(test -e .venv || virtualenv  .venv) && \
	(test ! -e requirements.txt || (. .venv/bin/activate; pip -q install -r requirements.txt) && \
	. .venv/bin/activate; PYTHONPATH=. exec python localstack/services/install.py testlibs)
  Failed building wheel for pycryptodome
awscli 1.16.67 has requirement PyYAML<=3.13,>=3.10, but you'll have pyyaml 4.2b4 which is incompatible.
Command "/opt/code/localstack/.venv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-4m5ukd/pycryptodome/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-NrcQLk/install-record.txt --single-version-externally-managed --compile --install-headers /opt/code/localstack/.venv/include/site/python2.7/pycryptodome" failed with error code 1 in /tmp/pip-install-4m5ukd/pycryptodome/
Traceback (most recent call last):
  File "localstack/services/install.py", line 9, in <module>
    from localstack.constants import (DEFAULT_SERVICE_PORTS, ELASTICMQ_JAR_URL, STS_JAR_URL,
  File "/opt/code/localstack/localstack/constants.py", line 2, in <module>
    import localstack_client.config
ImportError: No module named localstack_client.config
make: *** [Makefile:13: install] Error 1
The command '/bin/sh -c make install' returned a non-zero code: 2
Makefile:41: recipe for target 'docker-build' failed
make: *** [docker-build] Error 2
```

**Comment by mosesyu** [comment]
If I run `make install` outside of docker. It seems it works fine
```
make install
(test `which virtualenv` || pip install --user virtualenv) && \
	(test -e .venv || virtualenv  .venv) && \
	(test ! -e requirements.txt || (. .venv/bin/activate; pip -q install -r requirements.txt) && \
	. .venv/bin/activate; PYTHONPATH=. exec python localstack/services/install.py testlibs)
New python executable in /home/compliance/development/local1/localstack/.venv/bin/python
Installing setuptools, pip, wheel...
done.
awscli 1.16.67 has requirement PyYAML<=3.13,>=3.10, but you'll have pyyaml 4.2b4 which is incompatible.

```

**Comment by whummer** [comment]
Thanks for reporting @mosesyu . Please pull the latest version of the base image `localstack/java-maven-node-python:latest` - that should fix this issue.
