### ISSUE TITLE
bug: Multi-Region KMS Key does not return expected data causing AWS provider in terraform to crash

### ISSUE THREAD

**Issue by blairham** [localstack/localstack#10396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When configuring a KMS Key with multi-region the data returned does not match what the terraform provider is expecting and crashes

Terraform:
```
resource "aws_kms_key" "secure_secrets_key" {
  enable_key_rotation = true
  multi_region             = true
}
```

Terraform apply:
```
TestExamplesComplete 2024-03-05T12:35:16-05:00 logger.go:66: module.baseline.aws_kms_key.secure_secrets_key: Creating...
TestExamplesComplete 2024-03-05T12:35:16-05:00 logger.go:66: module.baseline.aws_kms_key.gitops_secrets_key: Creating...
...
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: ╷
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │ Error: Plugin did not respond
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │   with module.baseline.aws_kms_key.gitops_secrets_key,
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │   on ../../main.tf line 11, in resource "aws_kms_key" "gitops_secrets_key":
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │   11: resource "aws_kms_key" "gitops_secrets_key" {
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │ The plugin encountered an error, and failed to respond to the
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │ contain more details.
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: ╵
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: ╷
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │ Error: Plugin did not respond
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │   with module.baseline.aws_kms_key.secure_secrets_key,
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │   on ../../main.tf line 22, in resource "aws_kms_key" "secure_secrets_key":
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │   22: resource "aws_kms_key" "secure_secrets_key" {
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │ The plugin encountered an error, and failed to respond to the
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: │ contain more details.
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: ╵
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66:
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: Stack trace from the terraform-provider-aws_v5.39.1_x5 plugin:
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66:
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: panic: runtime error: invalid memory address or nil pointer dereference
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: [signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10ec42448]
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66:
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: goroutine 355 [running]:
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: github.com/hashicorp/terraform-provider-aws/internal/service/kms.resourceKeyRead({0x1153521a8, 0x14002fe6ed0}, 0x14002794980, {0x115130e60?, 0x14001d20fc0?})
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: 	github.com/hashicorp/terraform-provider-aws/internal/service/kms/key.go:235 +0x4d8
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: github.com/hashicorp/terraform-provider-aws/internal/service/kms.resourceKeyCreate({0x1153521a8, 0x140027f62a0}, 0x14002794980, {0x115130e60?, 0x14001d20fc0})
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: 	github.com/hashicorp/terraform-provider-aws/internal/service/kms/key.go:214 +0x12d0
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Create.interceptedHandler[...].func8(0x0?, {0x115130e60?, 0x14001d20fc0?})
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: 	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:112 +0x1d4
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1153521a8?, {0x1153521a8?, 0x140027d8f00?}, 0xd?, {0x115130e60?, 0x14001d20fc0?})
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:773 +0x64
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400173f5e0, {0x1153521a8, 0x140027d8f00}, 0x14003099a00, 0x14002794800, {0x115130e60, 0x14001d20fc0})
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:909 +0x86c
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400326ffe0, {0x1153521a8?, 0x140027d8e10?}, 0x140038953b0)
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:1078 +0xb08
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x1153521e0?, {0x1153521a8?, 0x140027d8b10?}, 0x140038953b0)
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: 	github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x184
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14000825d60, {0x1153521a8?, 0x140027d8300?}, 0x14000aff7a0)
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: 	github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/tf5server/server.go:846 +0x2b0
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x114edc780?, 0x14000825d60}, {0x1153521a8, 0x140027d8300}, 0x14002794500, 0x0)
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: 	github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x164
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: google.golang.org/grpc.(*Server).processUnaryRPC(0x14001544200, {0x1153521a8, 0x140027d8270}, {0x115387478, 0x14001e80680}, 0x140027d65a0, 0x14001d2ff80, 0x11d185878, 0x0)
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: 	google.golang.org/grpc@v1.62.0/server.go:1383 +0xb8c
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: google.golang.org/grpc.(*Server).handleStream(0x14001544200, {0x115387478, 0x14001e80680}, 0x140027d65a0)
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: 	google.golang.org/grpc@v1.62.0/server.go:1794 +0xc70
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: google.golang.org/grpc.(*Server).serveStreams.func2.1()
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: 	google.golang.org/grpc@v1.62.0/server.go:1027 +0x8c
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 55
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: 	google.golang.org/grpc@v1.62.0/server.go:1038 +0x150
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66:
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: Error: The terraform-provider-aws_v5.39.1_x5 plugin crashed!
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66:
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: This is always indicative of a bug within the plugin. It would be immensely
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: helpful if you could report the crash with the plugin's maintainers so that it
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66: can be fixed. The output above should help diagnose the issue.
TestExamplesComplete 2024-03-05T12:35:21-05:00 logger.go:66:
TestExamplesComplete 2024-03-05T12:35:21-05:00 retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; 
```

### Expected Behavior

The response to the request should provide correct data to prevent AWS provider crashes.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

For this I use terratest along with localstack.

starting up localstack with `localstack start -d`
Then execute terratest pointing to the localstack with the following

```
provider "aws" {
  access_key = "test"
  secret_key = "test"
  region     = var.region

  # only required for non virtual hosted-style endpoint use case.
  # https://registry.terraform.io/providers/hashicorp/aws/latest/docs#s3_force_path_style
  s3_use_path_style           = true
  skip_metadata_api_check     = true
  skip_region_validation      = true
  skip_credentials_validation = true

  endpoints {
    ec2            = "http://localhost:4566"
    iam            = "http://localhost:4566"
    organizations  = "http://localhost:4566"
    s3             = "http://localhost:4566"
    sts            = "http://localhost:4566"
    secretsmanager = "http://localhost:4566"
    kms            = "http://localhost:4566"
    sns            = "http://localhost:4566"
    config         = "http://localhost:4566"
  }
}

resource "aws_kms_key" "secure_secrets_key" {
  enable_key_rotation = true
  multi_region             = true
}
```

The result will be the crash when `mutlti_region` is set to `true`

### Environment

```markdown
- OS: macOS Sonoma 14.3.1
- LocalStack: 
-- Docker Image: localstack/localstack (image id: ac6404d9b8c1)
-- CLI: 3.1.0
```

**Comment by dfangl** [comment]
Solved by @marcciosilva in #10625.
Thank you for reporting this bug!
