### ISSUE TITLE
StartMessageMoveTask fails when optional destination ARN is not supplied

### ISSUE THREAD

**Issue by iamvinov-atlassian** [localstack/localstack#10392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently performing `StartMessageMoveTask` fails with `500 Internal Server Error` when destination queue ARN is not supplied. According to AWS [docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_StartMessageMoveTask.html), `destinationArn` is not required. 

Logs:
```
localstack.request.aws     : AWS sqs.StartMessageMoveTask => 500 (InternalError)
2024-03-04T16:12:38.862 DEBUG --- [   asgi_gw_0] rolo.gateway.wsgi          : POST 127.0.0.1:4566/
2024-03-04T16:12:38.863 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 112, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 82, in __call__
    skeleton_response = self.skeleton.invoke(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(serializer, context, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 168, in dispatch_request
    result = handler(context, instance) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/services/sqs/provider.py", line 1402, in start_message_move_task
    self._require_queue_by_arn(context, destination_arn)
  File "/opt/code/localstack/localstack/services/sqs/provider.py", line 792, in _require_queue_by_arn
    arn = parse_arn(queue_arn)
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/utils/aws/arns.py", line 38, in parse_arn
    return _arn_parser.parse_arn(arn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/utils.py", line 2096, in parse_arn
    arn_parts = arn.split(':', 5)
                ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
2024-03-04T16:12:38.867  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS sqs.StartMessageMoveTask => 500 (InternalError)
```

### Expected Behavior

The request should succeed without needing to supply `destinationArn`. 

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Create a queue and a DLQ.
2. Perform `StartMessageMoveTask` via any SQS library without supplying the `destinationQueueArn`. 

### Environment

```markdown
- OS: MacOS Sonoma 14.3 
- LocalStack: 3.1
```

**Comment by thrau** [comment]
hey @iamvinov-atlassian, do you have a scenario where you are re-driving into a single source queue, or multiple queues? this is the case when you have multiple queues that have the same DQL as redrive target.

**Comment by thrau** [comment]
@iamvinov-atlassian ok understand, then we can put it on the roadmap! should be doable in a couple of weeks.

the fix will be part of the `latest` pro image in a few hours. the next minor release is scheduled for end of march

**Comment by thrau** [comment]
The case for multiple source queues is handled with #10425
