### ISSUE TITLE
bug: CREATE_FAILED AWS::WAFv2::WebACLAssociation

### ISSUE THREAD

**Issue by ecumene** [localstack/localstack#10409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When deploying this stack to Localstack: https://github.com/cdk-patterns/serverless/tree/main/the-waf-apigateway/typescript

This error occurs:

```
2024-03-06 15:12:26  ❌  TheWafStack failed: Error: The stack named TheWafStack failed to deploy: CREATE_FAILED (Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'WebACLAssociation', 'PhysicalResourceId': None, 'ResourceType': 'AWS::WAFv2::WebACLAssociation', 'Scope': [], 'Details': []}}])
2024-03-06 15:12:26     at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:427:10615)
2024-03-06 15:12:26     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-03-06 15:12:26     at async Object.deployStack2 [as deployStack] (/usr/local/lib/node_modules/aws-cdk/lib/index.js:430:196919)
2024-03-06 15:12:26     at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:430:178888
```

**localstack/localstack-pro:3.2.1**
```
2024-03-06 15:12:21 2024-03-06T18:42:21.270  WARN --- [uncthread115] l.s.c.deployment_utils     : No resource provider found for "AWS::WAFv2::WebACL". To find out if AWS::WAFv2::WebACL is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/user-guide/aws/cloudformation/#resources-pro--enterprise-edition
```

### Expected Behavior

It deploys properly

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    cdklocal deploy --all --require-approval never

### Environment

```markdown
- OS: MacOS
- LocalStack: 3.2.1 (Pro)
```

**Comment by ecumene** [comment]
WafV2 implemented in: #7725
