### ISSUE TITLE
bug: CDKMetaData failing to delete in CFN

### ISSUE THREAD

**Issue by sam-fakhreddine** [localstack/localstack#10472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

CDKMetadata is failing to delete, the CFN stack wont delete.

### Expected Behavior

When we run cdklocal destroy it destroys the stack that was deployed.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    Localstack Desktop

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

❯ ENV=security AWS_ACCESS_KEY_ID=383xxxxxx27 cdklocal destroy --verbose

❯ AWS_ACCESS_KEY_ID=383xxxxxx27 awslocal cloudformation delete-stack --stack-name quota-monitor-email-formatting-main-security

```
2024-03-17T18:12:29.318  WARN --- [   asgi_gw_5] l.s.c.e.template_deployer  : Failed delete of resource with id CDKMetadata in iteration cycle 9. Retrying in next cycle.
2024-03-17T18:12:29.319 ERROR --- [   asgi_gw_5] l.s.c.e.template_deployer  : Last cycle failed to delete resource with id CDKMetadata. Final exception: 'NoneType' object has no attribute 'copy'
#Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 908, in delete_stack
>    executor.deploy_loop(resource, resource_provider_payload)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/resource_provider.py", line 426, in deploy_loop
>    self.extract_physical_resource_id_from_model_with_schema(
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/resource_provider.py", line 588, in extract_physical_resource_id_from_model_with_schema
U    physical_resource_id = resolve_json_pointer(resource_model, primary_id_paths[0])
U                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/resource_provider.py", line 371, in resolve_json_pointer
*    resolved_part = resource_props.copy()
(                    ^^^^^^^^^^^^^^^^^^^
:AttributeError: 'NoneType' object has no attribute 'copy'
```

### Environment

```markdown
- OS: macOS 
- LocalStack: latest (3.2.1)
```

**Comment by pinzon** [comment]
Hi @sam-fakhreddine this is an issue that's been already resolved in recent versions of LocalStack. I tested it agains the latest version.
Thank you for reporting.
