### ISSUE TITLE
bug: Localstack Glue is missing support for Postgres and Redshift JDBC driver

### ISSUE THREAD

**Issue by covatic-john** [localstack/localstack#10518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to use the Postgres or Redshift drivers in a Glue job, the job fails because the JAR for the either JDBC driver is missing from PySpark. The following stacktrace is produced for AWS Glue jobs.

```
2024-03-22 10:35:32 24/03/22 10:35:31 INFO ContextHandler: Started o.s.j.s.ServletContextHandler@412fc793{/static/sql,null,AVAILABLE,@Spark}
2024-03-22 10:35:32 Traceback (most recent call last):
2024-03-22 10:35:32   File "/tmp/script-880d0590.py", line 21, in <module>
2024-03-22 10:35:32     .load())
2024-03-22 10:35:32      ^^^^^^
2024-03-22 10:35:32   File "/var/lib/localstack/lib/spark/3.3.0/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 184, in load
2024-03-22 10:35:32   File "/var/lib/localstack/lib/spark/3.3.0/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1321, in __call__
2024-03-22 10:35:32   File "/var/lib/localstack/lib/spark/3.3.0/python/lib/pyspark.zip/pyspark/sql/utils.py", line 190, in deco
2024-03-22 10:35:32   File "/var/lib/localstack/lib/spark/3.3.0/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py", line 326, in get_return_value
2024-03-22 10:35:32 py4j.protocol.Py4JJavaError: An error occurred while calling o33.load.
2024-03-22 10:35:32 : java.sql.SQLException: No suitable driver
2024-03-22 10:35:32     at java.sql/java.sql.DriverManager.getDriver(Unknown Source)
2024-03-22 10:35:32     at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.$anonfun$driverClass$2(JDBCOptions.scala:107)
2024-03-22 10:35:32     at scala.Option.getOrElse(Option.scala:189)
2024-03-22 10:35:32     at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:107)
2024-03-22 10:35:32     at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:39)
2024-03-22 10:35:32     at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:34)
2024-03-22 10:35:32     at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:350)
2024-03-22 10:35:32     at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
2024-03-22 10:35:32     at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
2024-03-22 10:35:32     at scala.Option.getOrElse(Option.scala:189)
2024-03-22 10:35:32     at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
2024-03-22 10:35:32     at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:171)
2024-03-22 10:35:32     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-03-22 10:35:32     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2024-03-22 10:35:32     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2024-03-22 10:35:32     at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2024-03-22 10:35:32     at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
2024-03-22 10:35:32     at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
2024-03-22 10:35:32     at py4j.Gateway.invoke(Gateway.java:282)
2024-03-22 10:35:32     at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
2024-03-22 10:35:32     at py4j.commands.CallCommand.execute(CallCommand.java:79)
2024-03-22 10:35:32     at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
2024-03-22 10:35:32     at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
2024-03-22 10:35:32     at java.base/java.lang.Thread.run(Unknown Source)
2024-03-22 10:35:32 
2024-03-22 10:35:32 24/03/22 10:35:32 INFO SparkContext: Invoking stop() from shutdown hook
```

### Expected Behavior

The Glue job should not fail due to missing JDBC driver.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

running through testcontainers

```
    with (LocalStackContainer(
            image="localstack/localstack-pro:3.2.0-bigdata", privileged=True
    ).with_bind_ports(4566, 4566)
                  .with_bind_ports(4510, 4510)
                  .with_env("LOCALSTACK_AUTH_TOKEN", os.getenv('LOCALSTACK_AUTH_TOKEN'))
                  .with_env("DEBUG", "1")
                  .with_env("LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT", "30")
                  .with_env("AWS_DEFAULT_REGION", "us-west-1")
                  .with_env("CDK_DEFAULT_REGION", "us-west-1")
                  .with_volume_mapping("/var/run/docker.sock", "/var/run/docker.sock")
                  .with_volume_mapping("/Users/johnharrison/localstack/volume}", "/var/lib/localstack", mode="")

```

the using cdklocal to deploy the glue job

glue job:

```

jardrv = "/Users/johnharrison/git/database_flattening/cdk/assets/redshift-jdbc42-2.1.0.26.jar"

from pyspark.sql import SparkSession

spark = SparkSession.builder.config('spark.driver.extraClassPath', jardrv).getOrCreate()

# spark = SparkSession.builder.appName("covatic_analysis").getOrCreate()

cons = ((spark.read.format("jdbc").option("url",
                                          "jdbc:redshift://localhost.localstack.cloud:4510/covaticdata;ssl=false")
         .option("dbtable", "prod.consumptions")
         .option("user", "admin"))
        .option("password", "admin")
        .load())

```

works fine if I include the JAR and run locally

### Environment

```markdown
- OS: MAC
- LocalStack:localstack/localstack-pro:3.2.0-bigdata
```

**Comment by covatic-john** [comment]
https://github.com/localstack/localstack/issues/7064

Can someone tell me where to put the jar so I can carry on with working

**Comment by covatic-john** [comment]
would also be nice to be able to use the redshift connector  library

**Comment by macnev2013** [comment]
Hello, we are pleased to inform you that we have implemented changes that should resolve your reported issue. Kindly update to the latest LocalStack container image and let us know if your issue has been resolved. Thank you!

**Comment by covatic-john** [comment]
This is now working
