### ISSUE TITLE
bug: Cloudfront with an ARecord causes an Alias Loop when trying to hit it

### ISSUE THREAD

**Issue by Garethp** [localstack/localstack#10554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I have a Cloudfront Distribution with an ARecord for an entry in Route53, trying to hit the cloudfront from it's cloudfront URL results in a loop of 

```
localstack-bugs | 2024-03-27T12:09:24.426 DEBUG --- [uest_thread)] localstack.dns.server      : Found entry for AliasTarget 'example.test.com.' ('AliasTarget(target='cacbbcf2.cloudfront.localhost.localstack.cloud', alias_id=None, health_check=None)')
localstack-bugs | 2024-03-27T12:09:24.426 DEBUG --- [uest_thread)] localstack.dns.server      : Alias found: example.test.com.
localstack-bugs | 2024-03-27T12:09:24.461 DEBUG --- [ asgi_gw_213] l.s.cloudfront.provider    : Distribution root call; default object 
localstack-bugs | 2024-03-27T12:09:24.461  INFO --- [ asgi_gw_213] l.s.cloudfront.provider    : Forwarding CloudFront invocation: GET https://example.test.com/, Host header example.test.com
localstack-bugs | 2024-03-27T12:09:24.463 DEBUG --- [uest_thread)] localstack.dns.server      : Found entry for AliasTarget 'example.test.com.' ('AliasTarget(target='cacbbcf2.cloudfront.localhost.localstack.cloud', alias_id=None, health_check=None)')
localstack-bugs | 2024-03-27T12:09:24.463 DEBUG --- [uest_thread)] localstack.dns.server      : Alias found: example.test.com.
localstack-bugs | 2024-03-27T12:09:24.496 DEBUG --- [ asgi_gw_214] l.s.cloudfront.provider    : Distribution root call; default object 
localstack-bugs | 2024-03-27T12:09:24.496  INFO --- [ asgi_gw_214] l.s.cloudfront.provider    : Forwarding CloudFront invocation: GET https://example.test.com/, Host header example.test.com
localstack-bugs | 2024-03-27T12:09:24.498 DEBUG --- [uest_thread)] localstack.dns.server      : Found entry for AliasTarget 'example.test.com.' ('AliasTarget(target='cacbbcf2.cloudfront.localhost.localstack.cloud', alias_id=None, health_check=None)')
localstack-bugs | 2024-03-27T12:09:24.498 DEBUG --- [uest_thread)] localstack.dns.server      : Alias found: example.test.com.
localstack-bugs | 2024-03-27T12:09:24.531 DEBUG --- [ asgi_gw_215] l.s.cloudfront.provider    : Distribution root call; default object 
...
```

And a timeout error 

### Expected Behavior

The alias should resolve correctly and return the response from the lambda for that route

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```ts
export class DnsAliasStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const hostedZone = new PublicHostedZone(this, "HostedZone", {
      zoneName: "test.com",
    });

    const certificate = new Certificate(this, "Example", {
      domainName: "example.test.com",
    });

    const api = new RestApi(this, "test-api", {
      restApiName: "test-api",
      domainName: {
        domainName: "example.test.com",
        certificate,
      },
    });

    const distribution = new Distribution(this, "ApiCloudfront", {
      defaultBehavior: {
        origin: new HttpOrigin("example.test.com", {
          protocolPolicy: OriginProtocolPolicy.HTTPS_ONLY,
        }),
        allowedMethods: AllowedMethods.ALLOW_ALL,
        cachePolicy: CachePolicy.CACHING_DISABLED,
        originRequestPolicy: OriginRequestPolicy.ALL_VIEWER,
        viewerProtocolPolicy: ViewerProtocolPolicy.HTTPS_ONLY,
      },
      domainNames: ["example.test.com"],
      certificate: certificate,
    });

    new ARecord(this, "ARecord", {
      zone: hostedZone,
      recordName: "example.test.com.",
      target: RecordTarget.fromAlias(new CloudFrontTarget(distribution)),
    });

    const responseLambda = new Function(this, "hello-world", {
      runtime: Runtime.NODEJS_20_X,
      handler: "index.handler",
      code: Code.fromInline(
        "exports.handler = async (event) => ({statusCode: 201, body: JSON.stringify({ Hello: 'World' }) })",
      ),
    });

    api.root.addMethod("GET", new LambdaIntegration(responseLambda));
  }
}
```

```sh
CLOUDFRONT_URL=$(awslocal cloudfront list-distributions | jq -r .DistributionList.Items[0].DomainName)
curl "https://$CLOUDFRONT_URL/"
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```

### Anything else?

I've reproduced the issue here: https://github.com/Garethp/localstack-bugs/tree/dns-alias
If you clone down the branch `dns-alias`, run yarn install and then ./start.sh you should see the issue in action

**Comment by simonrw** [comment]
Hi @Garethp, thanks for creating this issue. I can recreate the issue with your helpful repo. I will take a look at resolving this problem, and get back to you when we have resolved the issue.

**Comment by simonrw** [comment]
Hi @Garethp, unfortunately I don't think this is a valid configuration for your three resources. You have a CloudFront distribution with domain name `example.test.com`, which has an HTTP origin of `example.test.com`, so it is its own origin. This will by definition create infinite recursion (until timeout).

One suggestion is to give your API Gateway a different domain name, e.g. `api.test.com` and use that domain name in your CloudFront origin.

Unfortunately while testing this suggestion, I discovered that we don't register domain names with the LocalStack DNS server, so the name gets resolved upstream. I will continue to fix this issue.

**Comment by Garethp** [comment]
Hey @simonrw. Thanks for looking at this. You're right that this configuration is invalid. For production, we normally do

```ts
              origin: new HttpOrigin(
                api.domainName!.domainNameAliasDomainName,
                {
                  protocolPolicy: OriginProtocolPolicy.HTTPS_ONLY,
                  originSslProtocols: [OriginSslPolicy.TLS_V1_2],
                  customHeaders: {
                    "X-Ros-Origin-Verify": originHeader.headerValue,
                  },
                }
```

But that fails with 

```
localstack-bugs | 2024-04-26T13:31:01.275 DEBUG --- [functhread75] l.s.c.e.template_deployer  : Dependencies for "ARecordE7B57761" not yet satisfied, retrying in next loop: Could not resolve attribute 'DomainName' on resource 'ApiCloudfront0ADD38B1'
localstack-bugs | 2024-04-26T13:31:01.276 DEBUG --- [functhread75] l.s.c.e.template_deployer  : Error applying changes for CloudFormation stack "dns-alias-stack": Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'ApiCloudfront0ADD38B1', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::Distribution', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'ARecordE7B57761', 'PhysicalResourceId': None, 'ResourceType': 'AWS::Route53::RecordSet', 'Scope': [], 'Details': []}}] Traceback (most recent call last):
localstack-bugs |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1185, in _run
localstack-bugs |     self.do_apply_changes_in_loop(changes, stack)
localstack-bugs |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1303, in do_apply_changes_in_loop
localstack-bugs |     raise Exception(
localstack-bugs | Exception: Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'ApiCloudfront0ADD38B1', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::Distribution', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'ARecordE7B57761', 'PhysicalResourceId': None, 'ResourceType': 'AWS::Route53::RecordSet', 'Scope': [], 'Details': []}}]
localstack-bugs | 
```

The invalid config was just our workaround that worked in 3.2 and prior. I'm assuming that this is caused by the domain names not being registered in the localstack DNS server that you're talking about? I'll look into trying your other suggested workaround

**Comment by simonrw** [comment]
Thanks for posting that sample CDK usage. Could you share a reproducible example that highlights this issue? Looks like there is something in your API Gateway REST API CDK resource definition that might be enough by itself. Something like

```typescript
const api = new RestApi(this, "RestApi", {/*...*/});
new CfnOutput(this, "ApiDomainName", {
  value: api.domainName!,
});
```

**Comment by Garethp** [comment]
Sure thing. I've put it up on the [`apigteway-domain-name-alias`](https://github.com/Garethp/localstack-bugs/tree/apigteway-domain-name-alias) branch. The full cdk is:

```ts
export class ApiGatewayDomainNameAlias extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const hostedZone = new PublicHostedZone(this, "HostedZone", {
      zoneName: "test.com",
    });

    const certificate = new Certificate(this, "Example", {
      domainName: "example.test.com",
      validation: CertificateValidation.fromDns(hostedZone),
    });

    const api = new RestApi(this, "test-api", {
      restApiName: "test-api",
      domainName: {
        domainName: "example.test.com",
        certificate,
      },
    });

    const responseLambda = new Function(this, "hello-world", {
      runtime: Runtime.NODEJS_20_X,
      handler: "index.handler",
      code: Code.fromInline(
        "exports.handler = async (event) => ({statusCode: 201, body: JSON.stringify({ Hello: 'World' }) })",
      ),
    });

    api.root.addMethod("GET", new LambdaIntegration(responseLambda));

    new CfnOutput(this, "RestApiDomainNameAlias", {
      value: api.domainName!.domainNameAliasDomainName,
    });
  }
}
```

I also deployed this into AWS (well, somewhat closely. We need to deploy using `DnsValidatedCertificate` instead of `Certificate` into AWS. But last time I tested, there were also issues around `DnsValidatedCertificate` in LocalStack that I never got around to digging into) to double check that it would output a domainNameAlias and it does.

Do you want me to file a separate issue for this?

**Comment by HarshCasper** [comment]
Due to the forthcoming changes in our distribution and development model ([read more](https://blog.localstack.cloud/the-road-ahead-for-localstack/)), this issue tracker is no longer being maintained. We've migrated this issue to our internal tracker and will continue to work on it there. If you'd like to follow up on the status or expedite this, feel free to reach out through one of our support channels:

-   💬 [GitHub Discussions](https://github.com/orgs/localstack/discussions)
-   📖 [Help & Support](https://docs.localstack.cloud/aws/getting-started/help-support/)
