### ISSUE TITLE
bug: 500 returned on TransactWriteItem when writing to DynamoDB table with Streams enabled

### ISSUE THREAD

**Issue by roemba** [localstack/localstack#10635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running Localstack locally as part of our test suite, we encountered the following exception when upgrading from 3.2 to 3.3. 

Excerpt from Localstack logs with DEBUG=1
```
 KeyError: '<redacted>.DataAccessLayer.IntegrationTests.DynamoDB-PseudoIdentityLookups'
localstack-1  | 2024-04-10T14:47:48.190  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.TransactWriteItems => 500 (InternalError)
localstack-1  | 2024-04-10T14:47:48.612 DEBUG --- [   asgi_gw_2] rolo.gateway.wsgi          : POST localhost:4566/
localstack-1  | 2024-04-10T14:47:48.631 ERROR --- [   asgi_gw_2] l.aws.handlers.logging     : exception during call chain
localstack-1  | Traceback (most recent call last):
localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
localstack-1  |     handler(self, self.context, response)
localstack-1  |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 113, in __call__
localstack-1  |     handler(chain, context, response)
localstack-1  |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 83, in __call__
localstack-1  |     skeleton_response = self.skeleton.invoke(context)
localstack-1  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-1  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 154, in invoke
localstack-1  |     return self.dispatch_request(serializer, context, instance)
localstack-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-1  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 168, in dispatch_request
localstack-1  |     result = handler(context, instance) or {}
localstack-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-1  |   File "/opt/code/localstack/localstack/aws/forwarder.py", line 136, in _call
localstack-1  |     return handler(context, req)
localstack-1  |            ^^^^^^^^^^^^^^^^^^^^^
localstack-1  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 118, in __call__
localstack-1  |     return self.fn(*args, **kwargs)
localstack-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^
localstack-1  |   File "/opt/code/localstack/localstack/aws/api/core.py", line 161, in operation_marker
localstack-1  |     return fn(*args, **kwargs)
localstack-1  |            ^^^^^^^^^^^^^^^^^^^
localstack-1  |   File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 1263, in transact_write_items
localstack-1  |     records_map = self.prepare_transact_write_item_records(
localstack-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-1  |   File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 1775, in prepare_transact_write_item_records
localstack-1  |     stream_type = tables_stream_type[table_name]
localstack-1  |                   ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
```

This exception only occurs on a specific table that has DynamoDB Streams enabled. Other tables, some of which have DynamoDB Streams enabled, do not suffer from this exception but are also not written to using `TransactWriteItem`. Not all `TransactWriteItem` operations to this table fail, just this specific one.

The `TransactWriteItem` operation that fails contains two PUT expressions. I've added a _way to reproduce this issue in a clean environment_ further down this issue.

### Expected Behavior

I expect the same behaviour as with 3.2, as in, that a 200 is returned and the TransactWriteItem creates the two items (PUT operation)

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up -d

We use the following docker-compose.yml:
```
services:
  localstack:
      image: localstack/localstack:3.3@sha256:b5c082a6d78d49fc4a102841648a8adeab4895f7d9a4ad042d7d485aed2da10d
      restart: always
      ports:
        - '4510-4559:4510-4559'
        - '4566:4566'
      environment:
        - DEBUG=1
        - ENABLE_CONFIG_UPDATES=1
        - SQS_ENDPOINT_STRATEGY=path # Makes it easier to access queues in different regions than the default region (see https://docs.localstack.cloud/user-guide/aws/sqs/#queue-urls)
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

We use the AWS SDK for .NET, but I tried creating a simple example to reproduce the issue outside of our codebase:

```bash
export AWS_ACCESS_KEY_ID="test"
export AWS_SECRET_ACCESS_KEY="test"
export AWS_DEFAULT_REGION="eu-central-1"

aws dynamodb create-table --table-name BugTest3 --attribute-definitions AttributeName=IdentityId_or_Key,AttributeType=S --key-schema AttributeName=IdentityId_or_Key,KeyType=HASH --stream-specification StreamEnabled=true,StreamViewType=NEW_AND_OLD_IMAGES --billing-mode PAY_PER_REQUEST --endpoint-url http://localhost:4566

aws dynamodb create-table --table-name BugTest2 --attribute-definitions AttributeName=PseudoId,AttributeType=S --key-schema AttributeName=PseudoId,KeyType=HASH --billing-mode PAY_PER_REQUEST --endpoint-url http://localhost:4566

aws dynamodb transact-write-items --transact-items file://twi.json --endpoint-url http://localhost:4566
```

The `twi.json` file should contain the following:
```json
[
    {
        "Put": {
            "Item": {
                "IdentityId_or_Key": {
                    "S": "1b6f1f00-159b-3bb4-f1a7-b64200a512e1"
                },
                "EmailAddress": {
                    "S": "jared.kuvalis@example.com"
                }
            },
            "TableName": "BugTest3"
        }
    },
    {
        "Put": {
            "Item": {
                "PseudoId": {
                    "S": "5652a944-14ea-4ea4-b3cf-671db106cd3f"
                },
                "IdentityId": {
                    "S": "1b6f1f00-159b-3bb4-f1a7-b64200a512e1"
                },
                "EmailAddress": {
                    "S": "jared.kuvalis@example.com"
                }
            },
            "TableName": "BugTest2",
            "ConditionExpression": "attribute_not_exists(PseudoId)"
        }
    }
]
```

In a clean environment, this always reliably reproduces the exception for me.

### Environment

```markdown
- OS: MacOs 14.4.1
- LocalStack: 3.3 (latest)
```

**Comment by bentsku** [comment]
Hello @roemba and thanks for your report! This is a duplicate from #10588, and happens when using `TransactWriteItems` on two tables, one with stream enabled and one without (it's the "without" one which makes it fail).

This has been fixed in the meantime, and is part of the `latest` Docker image. This was a regression introduced with big performance improvements around DynamoDB Streams. Sorry for that! 

You can use `latest` in the meantime or pin it with an image digest sha until the next release which should be end of the month. Thanks!

**Comment by roemba** [comment]
Thanks for the quick response! The best bug is the one already fixed 😄

Lesson for me to also search the 'closed' tickets next time before creating a new bug report.

**Comment by bentsku** [comment]
No worries 😄 Thanks a lot for the report already, it's always good to be aware of bugs, and thanks a lot for taking the time to create a reproducible sample!
