### ISSUE TITLE
bug: describe-images command not work

### ISSUE THREAD

**Issue by rimokuto** [localstack/localstack#10658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when running `awslocal ec2 describe-images`

```
An error occurred (InternalError) when calling the DescribeImages operation (reached max retries: 2): exception while calling ec2.DescribeImages: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 113, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 83, in __call__
    skeleton_response = self.skeleton.invoke(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(serializer, context, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request
    result = handler(context, instance) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/forwarder.py", line 136, in _call
    return handler(context, req)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/api/core.py", line 161, in operation_marker
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/ec2/provider.py.enc", line 52, in describe_images
    return VmManager.get_manager().describe_images(context,A)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/ec2/vmmanager/docker.py.enc", line 224, in describe_images
    if C.is_ec2_container_image(B):G=DOCKER_CLIENT.inspect_image(B,pull=_B);E=C.ami_id_from_image(B);A.amis[E]=Ami(A,ami_id=E,name=C.ami_name_from_image(B),architecture=G.get(_N),creation_date=G.get('Created'),public=_A,state=ImageState.available,image_location=_E);A.amis[E].add_tag('ec2_vm_manager',_E)
                                                                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/ec2/vmmanager/docker.py.enc", line 108, in ami_name_from_image
    return parse.parse(IMAGE_NAME_TEMPL,A)['ami_name']
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

### Expected Behavior

Normal response is obtained.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```bash
docker compose -f docker-compose.yml up -d localstack
```

docker-compose.yml

```
version: "3.8"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:4566:4566"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
awslocal ec2 describe-images
```

### Environment

```markdown
- OS: WSL Ubuntu-20.04 on Windows 11
- LocalStack: latest(3.3.1)
```

**Comment by rimokuto** [comment]
I found the cause. It occurs when the following commands are executed.
```bash
docker pull public.ecr.aws/amazonlinux/amazonlinux:2023
docker tag public.ecr.aws/amazonlinux/amazonlinux:2023 localstack-ec2:ami-local
```

Deleting the image solved the problem.
