### ISSUE TITLE
bug: lambda could not connect to rds mysql cluster

### ISSUE THREAD

**Issue by InvokedLambda** [localstack/localstack#10672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello all,

I run localsatck-pro in a docker container. Inside my docker container I run a rds cluster with mysql engine and a lambda function tries to connect to this rds cluster but I got a connection refused. I followed this example for the setup https://github.com/localstack-samples/sample-serverless-rds-proxy-demo

this is the error:
```
2024-04-16T11:37:24Z [Info] Initializing AWS X-Ray daemon unknown
2024-04-16T11:37:24Z [Debug] Listening on UDP 127.0.0.1:2000
2024-04-16T11:37:24Z [Info] Using buffer memory limit of 78 MB
2024-04-16T11:37:24Z [Info] 1248 segment buffers allocated
2024-04-16T11:37:24Z [Debug] Using Endpoint read from Config file: http://192.168.176.2:4566
2024-04-16T11:37:24Z [Debug] Using proxy address: 
2024-04-16T11:37:24Z [Debug] Fetch region eu-central-1 from commandline/config file
2024-04-16T11:37:24Z [Info] Using region: eu-central-1
2024-04-16T11:37:24Z [Info] HTTP Proxy server using X-Ray Endpoint : http://192.168.176.2:4566
2024-04-16T11:37:24Z [Debug] Using Endpoint: http://192.168.176.2:4566
2024-04-16T11:37:24Z [Debug] Batch size: 10
2024-04-16T11:37:24Z [Info] Starting proxy http server on 127.0.0.1:2000

Custom Debug print: mysql+pymysql://lambda:&&_-S_(Ks5duj5BK@192.168.176.2:3306/mydb

[ERROR] 2024-04-16T11:37:31.779Z        c5d71f71-e74d-4614-9931-35e80ac24e1e    Unhandled exception
Traceback (most recent call last):
  File "/opt/python/lib/python3.9/site-packages/pymysql/connections.py", line 644, in connect
    sock = socket.create_connection(
  File "/var/lang/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/var/lang/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3282, in raw_connection
    return self.pool.connect()
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    self._dec_overflow()
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
    return self._create_connection()
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/opt/python/lib/python3.9/site-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/opt/python/lib/python3.9/site-packages/pymysql/connections.py", line 711, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.176.2' ([Errno 111] Connection refused)")
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 12, in lambda_handler
    organization_types = session.query(OrganizationType).all()
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2672, in all
    return self._iter().all()  # type: ignore
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2826, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
  File "<string>", line 2, in _connection_for_bind
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3258, in connect
    return self._connection_cls(self)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2422, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3282, in raw_connection
    return self.pool.connect()
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    self._dec_overflow()
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 166, in _do_get
    return self._create_connection()
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 901, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/python/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/opt/python/lib/python3.9/site-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/opt/python/lib/python3.9/site-packages/pymysql/connections.py", line 711, in connect
    raise exc
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '192.168.176.2' ([Errno 111] Connection refused)")
```

Username and password are correct. I could connect from my local machine via MySQLWorkbench:
<img width="905" alt="image" src="https://github.com/localstack/localstack/assets/131391863/5415566d-8fd7-4e62-86cb-daefcc486ed3">

Running docker container:
<img width="1435" alt="image" src="https://github.com/localstack/localstack/assets/131391863/0a4d2afb-0686-4fe2-a7db-40c71c9d8d49">

DB session implementation:
```
hostname = urlparse(os.environ.get("AWS_ENDPOINT_URL")).hostname

def get_engine():
    db_uri = '{}://{}:{}@{}:{}/{}'.format(
        os.environ.get('DB_INSTANCE_DRIVER'), 
        os.environ.get('DB_INSTANCE_USER'), 
        os.environ.get('DB_INSTANCE_PASSWORD'), 
        hostname, 
        os.environ.get('DB_INSTANCE_PORT'), 
        os.environ.get('DB_INSTANCE_DATABASE_NAME')
    )

    print("Uri: " + db_uri)

    return create_engine(db_uri)
```

RDS Cluster in LocalStack container:
```
# awslocal rds describe-db-clusters
{
    "DBClusters": [
        {
            "AllocatedStorage": 1,
            "DatabaseName": "mydb",
            "DBClusterIdentifier": "rds-instance-dev",
            "DBClusterParameterGroup": "default.aurora-mysql8.0",
            "DBSubnetGroup": "rds-cluster-subnet-group-dev",
            "Status": "available",
            "Endpoint": "localhost.localstack.cloud",
            "ReaderEndpoint": "localhost.localstack.cloud",
            "MultiAZ": false,
            "Engine": "aurora-mysql",
            "EngineVersion": "8.0",
            "Port": 3306,
            "MasterUsername": "dbroot",
            "DBClusterMembers": [
                {
                    "DBInstanceIdentifier": "tf-20240416094800769300000016",
                    "IsClusterWriter": true,
                    "DBClusterParameterGroupStatus": "in-sync",
                    "PromotionTier": 0
                }
            ],
            "VpcSecurityGroups": [
                {
                    "VpcSecurityGroupId": "sg-7bf7b35fa86d85e5a",
                    "Status": "active"
                }
            ],
            "StorageEncrypted": true,
            "DbClusterResourceId": "cluster-b10833eb",
            "DBClusterArn": "arn:aws:rds:eu-central-1:000000000000:cluster:rds-instance-dev",
            "IAMDatabaseAuthenticationEnabled": true,
            "EngineMode": "provisioned",
            "DeletionProtection": false,
            "CopyTagsToSnapshot": false,
            "TagList": [
                {
                    "Key": "Name",
                    "Value": "rds-cluster-dev"
                }
            ],
            "ServerlessV2ScalingConfiguration": {
                "MinCapacity": 0.5,
                "MaxCapacity": 1.0
            }
        }
    ]
}
```

Do I miss something or is this a bug?

### Expected Behavior

I expecting, that the lambda function could connect to my rds database.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
docker build -t my-localstack-pro .
docker-compose up -d
```

Dockerfile
```
    FROM localstack/localstack-pro:3.3.0

    # Install jq
    RUN apt-get update && \
        apt-get install -y jq && \
        rm -rf /var/lib/apt/lists/*
```

docker-compose.yml
```
version: '3.8'
services:
  localstack:
    image: my-localstack-pro:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"     
      - "53:53"                # DNS config (only required for Pro)
      - "53:53/udp"            # DNS config (only required for Pro)
      - "443:443"
    environment:
      - SERVICES=ec2,lambda,s3,apigateway,apigatewaymanagementapi,cognito-idp,secretsmanager,lambda,acm,iam,route53,route53resolver,ses,ssm,ce,cloudfront,cognito-identity,rds-data,rds,wafv2
      - DISABLE_CORS_CHECKS=1
      - DEBUG=1
      - PERSISTENCE=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=eu-central-1
      - GATEWAY_LISTEN=0.0.0.0
      - LOCALSTACK_AUTH_TOKEN="<hidden>"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.volume/localstack:/var/lib/localstack"
```

### Environment

```markdown
- OS: Sonoma 14.2.1 (23C71) (Apple M2 Pro)
- LocalStack: "edition": "pro", "version": "3.3.1.dev20240328130241"
- Docker: Engine: 24.0.6
```

### Anything else?

If you need any further infos don't hesitate.

**Comment by steffyP** [comment]
Hi @InvokedLambda, 

thanks for reaching out. 

From the screenshot and the logs that you provided:
1) the database connection test with MySQLWorkbench does not use the port `3306` (which is used by the lambda), but the container port. Please consider checking that `3306` is also reachable 🙏 

2) the logs suggest that you are creating a database connection string using the SQLAlchemy syntax. It seems your database connection string results into `mysql+pymysql://lambda:<passwd>@192.168.176.2:3306/mydb`. However, your password contains some special characters. You may need to do [some URL escaping for the password](https://docs.sqlalchemy.org/en/20/core/engines.html#database-urls).

If this doesn't solve your issue already, please provide a small complete sample, e.g with a fully-working lambda, and explanation how the ENVs are set or retrieved, so we can try to reproduce the issue.

**Comment by InvokedLambda** [comment]
Hi @steffyP,

thanks for your response.

I updated my code that the password will be escaped:
Code:
```
hostname = urlparse(os.environ.get("AWS_ENDPOINT_URL")).hostname

def get_engine():
    url_object = URL.create(
        os.environ.get('DB_INSTANCE_DRIVER'), 
        username=os.environ.get('DB_INSTANCE_USER'),
        password=os.environ.get('DB_INSTANCE_PASSWORD'),  # plain (unescaped) text
        host=hostname,
        port=os.environ.get('DB_INSTANCE_PORT'),
        database=os.environ.get('DB_INSTANCE_DATABASE_NAME'),
    )

    print("Url-Object: " + url_object.render_as_string(False))

    return create_engine(url_object)
```

Output:
`2024-04-17T07:26:20.605 DEBUG --- [   asgi_gw_5] l.s.l.i.version_manager    : [cmpr-lambda-function-organization-type-get-all-dev-81d388a5-936a-4916-83e2-a149fbf93cfd] Url-Object: mysql+pymysql://lambda:%26%26_-S_%28Ks5duj5BK@192.168.192.2:3306/dbcmpr`


I also exposed the 3306 port of my LocalStack docker container. But I still got this error:
`2024-04-17T07:26:20.608 DEBUG --- [   asgi_gw_5] l.s.l.i.version_manager    : [cmpr-lambda-function-organization-type-get-all-dev-81d388a5-936a-4916-83e2-a149fbf93cfd] sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '192.168.192.2' ([Errno 111] Connection refused)")`

I create the rds cluster and my db like this with terraform:
```
resource "aws_rds_cluster" "my_rds_cluster" {
  cluster_identifier                  = "${var.project}-rds-instance-${var.namespace}"
  engine                              = "aurora-mysql"
  engine_version                      = "8.0"
  engine_mode                         = "provisioned"
  database_name                       = "db${var.project}"
  master_username                     = var.database_master_user
  master_password                     = var.db_master_pass_result
  db_subnet_group_name                = aws_db_subnet_group.private_rds_group.id
  vpc_security_group_ids              = [var.sg_rds_id]
  iam_database_authentication_enabled = true
  apply_immediately                   = true
  skip_final_snapshot                 = true
  storage_encrypted                   = true
  port                                = 3306

  serverlessv2_scaling_configuration {
    min_capacity = 0.5
    max_capacity = 1.0
  }

  tags = {
    Name = "${var.project}-rds-cluster-${var.namespace}"
  }
}

resource "aws_rds_cluster_instance" "rds_instance" {
  cluster_identifier   = aws_rds_cluster.my_rds_cluster.id
  instance_class       = "db.serverless"
  engine               = aws_rds_cluster.my_rds_cluster.engine
  engine_version       = aws_rds_cluster.my_rds_cluster.engine_version
  apply_immediately    = true
  db_subnet_group_name = aws_db_subnet_group.private_rds_group.id
  publicly_accessible  = false

  tags = {
    Name = "${var.project}-rds-instance-${var.namespace}"
  }
}


data "archive_file" "archive_src_lambda" {
  type        = "zip"
  source_dir  = "${var.lambdas_relative_path}src/${var.lambda_src_path}"
  output_path = "${var.lambdas_relative_path}zipped/${var.lambda_function_name}.zip"
}

resource "aws_s3_object" "s3_object_lambda" {
  bucket = var.s3_bucket_lambdas_id

  key    = "lambda/${var.lambda_function_name}"
  source = data.archive_file.archive_src_lambda.output_path

  etag = filemd5(data.archive_file.archive_src_lambda.output_path)

  tags = {
    Name = "${var.project}-s3-object-${var.lambda_function_name}-${var.namespace}"
  }
}

resource "aws_lambda_function" "lambda_function" {
  function_name           = "${var.project}-lambda-function-${var.lambda_function_name}-${var.namespace}"
  description             = ""
  code_signing_config_arn = ""
  source_code_hash        = filebase64sha256(data.archive_file.archive_src_lambda.output_path)

  s3_bucket = var.s3_bucket_lambdas_id
  s3_key    = aws_s3_object.s3_object_lambda.key

  handler = "lambda_function.lambda_handler"
  runtime = "python3.9"
  role    = var.iam_role_lambda_arn

  layers = var.aws_lambda_layer_arn_list

  timeout = 30

  environment {
    variables = {
        DB_INSTANCE_DRIVER          = "mysql+pymysql"
        DB_INSTANCE_ENDPOINT        = aws_rds_cluster.rds_cluster.endpoint
        DB_INSTANCE_PORT            = aws_rds_cluster.rds_cluster.port
        DB_INSTANCE_DATABASE_NAME   = aws_rds_cluster.rds_cluster.database_name
        DB_INSTANCE_USER            = "lambda"
        DB_INSTANCE_PASSWORD        = module.secrets_manager.db_lambda_pass_result
      }
  }
  vpc_config {
    subnet_ids         = var.private_subnets_ids
    security_group_ids = var.security_group_id_list_lambda
  }

  tags = {
    Name = "${var.project}-lambda-function-${var.lambda_function_name}-${var.namespace}"
  }
}
```

awslocal rds describe-db-clusters
```
{
    "DBClusters": [
        {
            "AllocatedStorage": 1,
            "DatabaseName": "dbcmpr",
            "DBClusterIdentifier": "cmpr-rds-instance-dev",
            "DBClusterParameterGroup": "default.aurora-mysql8.0",
            "DBSubnetGroup": "cmpr-rds-cluster-subnet-group-dev",
            "Status": "available",
            "Endpoint": "localhost.localstack.cloud",
            "ReaderEndpoint": "localhost.localstack.cloud",
            "MultiAZ": false,
            "Engine": "aurora-mysql",
            "EngineVersion": "8.0",
            "Port": 3306,
            "MasterUsername": "dbroot",
            "DBClusterMembers": [
                {
                    "DBInstanceIdentifier": "tf-20240417071438684800000016",
                    "IsClusterWriter": true,
                    "DBClusterParameterGroupStatus": "in-sync",
                    "PromotionTier": 0
                }
            ],
            "VpcSecurityGroups": [
                {
                    "VpcSecurityGroupId": "sg-0e7b739211a535482",
                    "Status": "active"
                }
            ],
            "StorageEncrypted": true,
            "DbClusterResourceId": "cluster-efaa4385",
            "DBClusterArn": "arn:aws:rds:eu-central-1:000000000000:cluster:cmpr-rds-instance-dev",
            "IAMDatabaseAuthenticationEnabled": true,
            "EngineMode": "provisioned",
            "DeletionProtection": false,
            "CopyTagsToSnapshot": false,
            "TagList": [
                {
                    "Key": "Name",
                    "Value": "cmpr-rds-cluster-dev"
                }
            ],
            "ServerlessV2ScalingConfiguration": {
                "MinCapacity": 0.5,
                "MaxCapacity": 1.0
            }
        }
    ]
}
```

aws_rds_cluster.rds_cluster.endpoint returns localhost.localstack.cloud but this is wrong for me because I need to connect over the docker network. Which would be accessible over the env "AWS_ENDPOINT_URL" as I already do in my code. When I use "localhost.localstack.cloud" Im getting a error that the network address could not be found.

For me it looks like that localstack starts the rds cluster in the localstack container correctly as you can see in the "awslocal rds describe-db-clusters" result. But localstack also starts the instance as a new docker container. This new docker container is not in the same network as the localstack container. When I now invoke the lambda function, the lambda function will be started in a new docker container as well but in the same network as the local stack docker container and now the lambda function tries to connect over the network on port 3306 to the rds cluster. It looks like that the cluster could be reached but the access is denied because the rds instance is not accessible. 

Docker container overview:
<img width="1510" alt="image" src="https://github.com/localstack/localstack/assets/131391863/a58b018f-1177-4146-bea2-4840283f6282">

LocalStack network conf:
<img width="910" alt="image" src="https://github.com/localstack/localstack/assets/131391863/c18b3bd4-ee6f-4015-a6d4-fa62390d943c">

MySql network conf:
<img width="914" alt="image" src="https://github.com/localstack/localstack/assets/131391863/46674fef-b045-4599-8b4c-3026a3d4c2fb">

Lambda network conf:
<img width="932" alt="image" src="https://github.com/localstack/localstack/assets/131391863/fa00cd0b-53be-4dde-8be2-d949de3c565f">

So as you can see the lambda function could never reach the mysql instance because they are in different networks. The lambda function and localstack could reach out each other over 192.168.192.0 but the mysql container is in another network 172.17.0.0 . So beside the lambda function, the rds cluster itself is not able to reach out its own instances. 

As I read here https://github.com/localstack/localstack/issues/6782 there was the Mariadb only first and then the mysql was added. The MariaDB instance was started directly in the localstack container but for the mysql engine a new docker container will be started.

**Comment by steffyP** [comment]
Hi @InvokedLambda, 

I think there might be a few misunderstandings. 

In your initial `Dockerfile` you have the following port-configuration
```
ports:
      - "4566:4566"
      - "4510-4559:4510-4559"     
      - "53:53"                # DNS config (only required for Pro)
      - "53:53/udp"            # DNS config (only required for Pro)
      - "443:443"
```

Which means that for the [port range](https://docs.localstack.cloud/references/external-ports/) of external services (like RDS mysql) you have ports 4510-4559 reserved. 
Whenever you request e.g. a new database cluster for MySQL, LocalStack will search a free port from the range 4510-4559 and select one. The MySQL container starts as a separate docker container, but LocalStack will proxy the connection. E.g. if LocalStack selects port 4510 it will automatically forward the traffic to the MySQL container. 

> I also exposed the 3306 port of my LocalStack docker container. But I still got this error:

This doesn't make any sense in that case :) You are exposing a port that is not used on LocalStack.

In your terraform-script you are requesting port `3306` but as this port is not configured for LocalStack, it should actually select and return a different one (I also tested and verified this). 

So this is where things get complicated, because you posted the output of `describe-db-clusters` which I believe cannot have the port `3306` assigned. 
Please verify the output here. If you still see this port assigned, we would need to get the logs from LocalStack (with DEBUG=1 enabled). 
If you want to be able to select the port, you either need to specify one from the range you specified for LocalStack (e.g. 4510-4559), or adapt the port range in the Dockerfile. Please [follow the docs for instructions](https://docs.localstack.cloud/references/external-ports/#configuring-the-external-service-port-range).


Your terraform snippet might contain some issues as well. In your environment section you reference `aws_rds_cluster.rds_cluster.port` but I think it should be `aws_rds_cluster.my_rds_cluster.port`.
Also it seems you are using a different password, then for the actual creation of the cluster `var.db_master_pass_result` vs `module.secrets_manager.db_lambda_pass_result`. 

```
environment {
    variables = {
        DB_INSTANCE_DRIVER          = "mysql+pymysql"
        DB_INSTANCE_ENDPOINT        = aws_rds_cluster.rds_cluster.endpoint
        DB_INSTANCE_PORT            = aws_rds_cluster.rds_cluster.port
        DB_INSTANCE_DATABASE_NAME   = aws_rds_cluster.rds_cluster.database_name
        DB_INSTANCE_USER            = "lambda"
        DB_INSTANCE_PASSWORD        = module.secrets_manager.db_lambda_pass_result
      }
  }
```

The connection-test that you are running with the MySqlDeveloper should use the port that is returned by LocalStack (which should be in the range 4510-4559). 

Could you please double check your settings and verify that 1) the returned port from LocalStack is within the range, and 2) that the variables you set for the Lambda match the actual database configuration 🙏

**Comment by InvokedLambda** [comment]
Hi @steffyP,

after using a reserved port everything works for me. Thanks a lot 🙏 and sorry for stealing your time ...
