### ISSUE TITLE
bug: Kinesis SubscribeToShard Timeouts with Java KCL Enhanced Fan-Out Consumers

### ISSUE THREAD

**Issue by mdemille** [localstack/localstack#10864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

See this [git repository](https://github.com/mdemille/simple-localstack-kinesis-efo-consumer) for a simple example demonstrating the problem. That is based on [this AWS guide](https://docs.aws.amazon.com/streams/latest/dev/building-enhanced-consumers-kcl-java.html), but tweaked to work with Localstack.

I am using the Java AWS SDK v2 KCL library to consume a Kinesis stream. When it is set up to poll, everything works just fine. When it is set up to use enhanced fan-out (which is the default KCL configuration), it fails. This failure happens after the `apiCallTimeout` specified on the Kinesis client has elapsed.

Errors from the application:
```
2024-05-21 13:49:37 INFO  l.k.e.t.Application$SampleRecordProcessor:154 - Initializing @ Sequence: {SequenceNumber: LATEST,SubsequenceNumber: 0} ShardId=shardId-000000000002 

...

2024-05-21 13:50:39 WARN  s.a.k.r.f.FanOutRecordsPublisher:350 - shardId-000000000002: [SubscriptionLifetime] - (FanOutRecordsPublisher#errorOccurred) @ 2024-05-21T19:49:39.196448Z id: shardId-000000000002-1 -- CompletionException/software.amazon.awssdk.core.exception.ApiCallTimeoutException: Client execution did not complete before the specified timeout configuration: 60000 millis. Last successful request details -- request id - UNKNOWN, timestamp - 2024-05-21T19:49:39.196448Z  java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.ApiCallTimeoutException: Client execution did not complete before the specified timeout configuration: 60000 millis
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:936)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallMetricCollectionStage.lambda$execute$0(AsyncApiCallMetricCollectionStage.java:56)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.timers.AsyncTimeoutTask.run(AsyncTimeoutTask.java:52)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: software.amazon.awssdk.core.exception.ApiCallTimeoutException: Client execution did not complete before the specified timeout configuration: 60000 millis
	at software.amazon.awssdk.core.exception.ApiCallTimeoutException$BuilderImpl.build(ApiCallTimeoutException.java:97)
	at software.amazon.awssdk.core.exception.ApiCallTimeoutException.create(ApiCallTimeoutException.java:38)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.lambda$execute$1(AsyncApiCallTimeoutTrackingStage.java:57)
	... 7 common frames omitted

2024-05-21 13:50:39 INFO  s.a.a.m.LoggingMetricPublisher:43 - Metrics published: MetricCollection(name=ApiCall, metrics=[MetricRecord(metric=MarshallingDuration, value=PT0.000144625S), MetricRecord(metric=ApiCallSuccessful, value=false), MetricRecord(metric=RetryCount, value=0), MetricRecord(metric=OperationName, value=SubscribeToShard), MetricRecord(metric=EndpointResolveDuration, value=PT0.000043666S), MetricRecord(metric=ApiCallDuration, value=PT1M0.00902625S), MetricRecord(metric=CredentialsFetchDuration, value=PT0.0000055S), MetricRecord(metric=ServiceEndpoint, value=http://localhost:4566), MetricRecord(metric=ServiceId, value=Kinesis)], children=[MetricCollection(name=ApiCallAttempt, metrics=[MetricRecord(metric=BackoffDelayDuration, value=PT0S), MetricRecord(metric=TimeToFirstByte, value=PT0.038624125S), MetricRecord(metric=SigningDuration, value=PT0.000458541S), MetricRecord(metric=ErrorType, value=Other)], children=[MetricCollection(name=HttpClient, metrics=[MetricRecord(metric=AvailableConcurrency, value=100), MetricRecord(metric=LeasedConcurrency, value=0), MetricRecord(metric=ConcurrencyAcquireDuration, value=PT0.000392S), MetricRecord(metric=PendingConcurrencyAcquires, value=0), MetricRecord(metric=LocalStreamWindowSize, value=524288), MetricRecord(metric=MaxConcurrency, value=2147483647), MetricRecord(metric=HttpClientName, value=NettyNio), MetricRecord(metric=RemoteStreamWindowSize, value=65364)], children=[])])])  

2024-05-21 13:50:39 WARN  s.a.k.l.ShardConsumerSubscriber:196 - shardId-000000000002: onError().  Cancelling subscription, and marking self as failed. KCL will recreate the subscription as necessary to continue processing. Last successful request details -- request id - UNKNOWN, timestamp - 2024-05-21T19:49:39.196448Z  java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.ApiCallTimeoutException: Client execution did not complete before the specified timeout configuration: 60000 millis
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:936)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallMetricCollectionStage.lambda$execute$0(AsyncApiCallMetricCollectionStage.java:56)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.timers.AsyncTimeoutTask.run(AsyncTimeoutTask.java:52)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: software.amazon.awssdk.core.exception.ApiCallTimeoutException: Client execution did not complete before the specified timeout configuration: 60000 millis
	at software.amazon.awssdk.core.exception.ApiCallTimeoutException$BuilderImpl.build(ApiCallTimeoutException.java:97)
	at software.amazon.awssdk.core.exception.ApiCallTimeoutException.create(ApiCallTimeoutException.java:38)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.lambda$execute$1(AsyncApiCallTimeoutTrackingStage.java:57)
	... 7 common frames omitted

2024-05-21 13:50:39 WARN  s.a.k.l.ShardConsumerSubscriber:115 - shardId-000000000002: Failure occurred in retrieval.  Restarting data requests  java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.ApiCallTimeoutException: Client execution did not complete before the specified timeout configuration: 60000 millis
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:936)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallMetricCollectionStage.lambda$execute$0(AsyncApiCallMetricCollectionStage.java:56)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.timers.AsyncTimeoutTask.run(AsyncTimeoutTask.java:52)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: software.amazon.awssdk.core.exception.ApiCallTimeoutException: Client execution did not complete before the specified timeout configuration: 60000 millis
	at software.amazon.awssdk.core.exception.ApiCallTimeoutException$BuilderImpl.build(ApiCallTimeoutException.java:97)
	at software.amazon.awssdk.core.exception.ApiCallTimeoutException.create(ApiCallTimeoutException.java:38)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.lambda$execute$1(AsyncApiCallTimeoutTrackingStage.java:57)
	... 7 common frames omitted

2024-05-21 13:50:39 WARN  s.a.k.r.f.FanOutRecordsPublisher:350 - shardId-000000000002: [SubscriptionLifetime] - (FanOutRecordsPublisher#errorOccurred) @ 2024-05-21T19:50:39.470916Z id: shardId-000000000002-2 -- CompletionException/software.amazon.awssdk.services.kinesis.model.KinesisException: exception while calling kinesis.SubscribeToShard: An error occurred (ResourceNotFoundException) when calling the GetShardIterator operation: Unable to find record with provided SequenceNumber SequenceNumber(0) in stream Some(efo-test) (Service: Kinesis, Status Code: 500, Request ID: 814b0cdd-3d75-4548-9e8b-619976495bce). Last successful request details -- request id - UNKNOWN, timestamp - 2024-05-21T19:49:39.196448Z  java.util.concurrent.CompletionException: software.amazon.awssdk.services.kinesis.model.KinesisException: exception while calling kinesis.SubscribeToShard: An error occurred (ResourceNotFoundException) when calling the GetShardIterator operation: Unable to find record with provided SequenceNumber SequenceNumber(0) in stream Some(efo-test) (Service: Kinesis, Status Code: 500, Request ID: 814b0cdd-3d75-4548-9e8b-619976495bce)
	at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:65)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:79)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:103)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:184)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:170)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$execute$0(MakeAsyncHttpRequestStage.java:110)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.completeResponseFuture(MakeAsyncHttpRequestStage.java:253)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:167)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: software.amazon.awssdk.services.kinesis.model.KinesisException: exception while calling kinesis.SubscribeToShard: An error occurred (ResourceNotFoundException) when calling the GetShardIterator operation: Unable to find record with provided SequenceNumber SequenceNumber(0) in stream Some(efo-test) (Service: Kinesis, Status Code: 500, Request ID: 814b0cdd-3d75-4548-9e8b-619976495bce)
	at software.amazon.awssdk.services.kinesis.model.KinesisException$BuilderImpl.build(KinesisException.java:104)
	at software.amazon.awssdk.services.kinesis.model.KinesisException$BuilderImpl.build(KinesisException.java:58)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.unmarshall(AwsJsonProtocolErrorUnmarshaller.java:92)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.handle(AwsJsonProtocolErrorUnmarshaller.java:66)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.handle(AwsJsonProtocolErrorUnmarshaller.java:41)
	at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.lambda$handle$0(MetricCollectingHttpResponseHandler.java:52)
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:99)
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:92)
	at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.handle(MetricCollectingHttpResponseHandler.java:52)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:92)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:135)
	at software.amazon.awssdk.core.internal.metrics.BytesReadTrackingPublisher$BytesReadTracker.onComplete(BytesReadTrackingPublisher.java:74)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$DataCountingPublisher$1.onComplete(ResponseHandler.java:519)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:254)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$600(ResponseHandler.java:77)
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:375)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.complete(HandlerPublisher.java:447)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.handlerRemoved(HandlerPublisher.java:435)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:1138)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:477)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:370)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:232)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:203)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.onDataRead(Http2ToHttpInboundAdapter.java:87)
	at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.channelRead0(Http2ToHttpInboundAdapter.java:49)
	at software.amazon.awssdk.http.nio.netty.internal.http2.Http2ToHttpInboundAdapter.channelRead0(Http2ToHttpInboundAdapter.java:42)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.doRead0(AbstractHttp2StreamChannel.java:971)
	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.doBeginRead(AbstractHttp2StreamChannel.java:876)
	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.beginRead(AbstractHttp2StreamChannel.java:839)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:845)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:824)
	at software.amazon.awssdk.http.nio.netty.internal.http2.FlushOnReadHandler.read(FlushOnReadHandler.java:40)
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:849)
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:824)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.requestDemand(HandlerPublisher.java:130)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler$1.requestDemand(HttpStreamsHandler.java:195)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.flushBuffer(HandlerPublisher.java:345)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.receivedDemand(HandlerPublisher.java:291)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.access$200(HandlerPublisher.java:61)
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:495)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 1 common frames omitted
```

Errors from the localstack container:
```
2024-05-21 13:50:39 2024-05-21T19:50:39.501  INFO --- [functhread20] l.s.k.kinesis_mock_server  : [warn] kinesis.mock.cache.Cache 2024-05-21T19:50:39.508810Z x-amz-id-2=Fvmboo1J7F8DWbnveEiROWLUf/r9pdflPj1yfXDNEwU6F2dVE0UiHhYwYuHgXyvL6VGlkBoZhTlAvLtFp8N1HIf5haiGmlMX, contentType=application/x-amz-json-1.1, x-amzn-RequestId=0684601e-8676-4ba3-a949-f6cf03edb564, action=GetShardIterator, contextId=1a7c3726-65cf-4db9-a3ab-3406e8b3ef7b, streamName=efo-test Getting the shard iterator was unuccessful
2024-05-21 13:50:39 2024-05-21T19:50:39.502  INFO --- [functhread20] l.s.k.kinesis_mock_server  : kinesis.mock.ResourceNotFoundException: Unable to find record with provided SequenceNumber SequenceNumber(0) in stream Some(efo-test)
2024-05-21 13:50:39 2024-05-21T19:50:39.502  INFO --- [functhread20] l.s.k.kinesis_mock_server  : at {anonymous}()(/var/lib/localstack/lib/kinesis-local/0.4.6/node_modules/kinesis-local/main.js:3298:404)
2024-05-21 13:50:39 2024-05-21T19:50:39.502  INFO --- [functhread20] l.s.k.kinesis_mock_server  : at w.h(/var/lib/localstack/lib/kinesis-local/0.4.6/node_modules/kinesis-local/main.js:2932:115)
2024-05-21 13:50:39 2024-05-21T19:50:39.502  INFO --- [functhread20] l.s.k.kinesis_mock_server  : at t7(/var/lib/localstack/lib/kinesis-local/0.4.6/node_modules/kinesis-local/main.js:4371:311)
2024-05-21 13:50:39 2024-05-21T19:50:39.502  INFO --- [functhread20] l.s.k.kinesis_mock_server  : at e.ml(/var/lib/localstack/lib/kinesis-local/0.4.6/node_modules/kinesis-local/main.js:4399:328)
2024-05-21 13:50:39 2024-05-21T19:50:39.502  INFO --- [functhread20] l.s.k.kinesis_mock_server  : at GN.ml(/var/lib/localstack/lib/kinesis-local/0.4.6/node_modules/kinesis-local/main.js:1366:197)
2024-05-21 13:50:39 2024-05-21T19:50:39.502  INFO --- [functhread20] l.s.k.kinesis_mock_server  : at {anonymous}()(/var/lib/localstack/lib/kinesis-local/0.4.6/node_modules/kinesis-local/main.js:3570:53)
2024-05-21 13:50:39 2024-05-21T19:50:39.502  INFO --- [functhread20] l.s.k.kinesis_mock_server  : at u.qa(/var/lib/localstack/lib/kinesis-local/0.4.6/node_modules/kinesis-local/main.js:2931:395)
2024-05-21 13:50:39 2024-05-21T19:50:39.502  INFO --- [functhread20] l.s.k.kinesis_mock_server  : at Immediate._onImmediate(/var/lib/localstack/lib/kinesis-local/0.4.6/node_modules/kinesis-local/main.js:2931:60)
2024-05-21 13:50:39 2024-05-21T19:50:39.502  INFO --- [functhread20] l.s.k.kinesis_mock_server  : at process.processImmediate(node:internal/timers:476:21)
2024-05-21 13:50:39 2024-05-21T19:50:39.506 ERROR --- [   asgi_gw_6] l.aws.handlers.logging     : exception during call chain: An error occurred (ResourceNotFoundException) when calling the GetShardIterator operation: Unable to find record with provided SequenceNumber SequenceNumber(0) in stream Some(efo-test)
2024-05-21 13:50:39 2024-05-21T19:50:39.506  INFO --- [   asgi_gw_6] localstack.request.aws     : AWS kinesis.SubscribeToShard => 500 (InternalError)
```

### Expected Behavior

Enhanced Fan-Out KCL Consumers work without any timeouts

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up --build -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws kinesis create-stream --stream-name efo-test --profile localstack

### Environment

```markdown
- OS: MacOS Sonoma 14.4.1
- LocalStack:
  LocalStack version: 3.4.0
  LocalStack Docker image sha:
  LocalStack build date: 2024-04-25
  LocalStack build git hash: 6f971ac81
```

**Comment by mdemille** [comment]
Closing this, as it seems to be the same as https://github.com/localstack/localstack/issues/10000 ... At first I didn't think it was, but I believe it is.
