### ISSUE TITLE
bug: Timeout issue while registring rotue from 000000000000.dkr.ecr.us-east-1.localhost:4566 to http://127.0.0.1:34951

### ISSUE THREAD

**Issue by rahul-huma** [localstack/localstack#10995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, I am trying to create a lambda function in localstack that pulls its code from a ecr image. But there is an issue which I am facing while creating an ecr repo. So When I try to create repository then I am getting these logs in my localstack container.

```
2024-06-10 16:09:42 2024-06-10T10:39:42.616 DEBUG --- [et.reactor-0] localstack.packages.api    : Starting installation of docker-registry...
2024-06-10 16:09:44 2024-06-10T10:39:44.342 DEBUG --- [et.reactor-0] localstack.utils.http      : Starting download from https://github.com/localstack/localstack-artifacts/raw/4e228449b7c6926a23fcf2c9cc02a95e444f7dd1/docker-registry/registry.linux-arm64.zip to /tmp/localstack/registry.linux-arm64.zip
2024-06-10 16:09:44 2024-06-10T10:39:44.571 DEBUG --- [et.reactor-0] localstack.utils.http      : Downloaded 10% (total 1024K of 10225K) to /tmp/localstack/registry.linux-arm64.zip
2024-06-10 16:09:44 2024-06-10T10:39:44.743 DEBUG --- [et.reactor-0] localstack.utils.http      : Downloaded 20% (total 2048K of 10225K) to /tmp/localstack/registry.linux-arm64.zip
2024-06-10 16:09:45 2024-06-10T10:39:45.053 DEBUG --- [et.reactor-0] localstack.utils.http      : Downloaded 30% (total 3072K of 10225K) to /tmp/localstack/registry.linux-arm64.zip
2024-06-10 16:09:45 2024-06-10T10:39:45.251 DEBUG --- [et.reactor-0] localstack.utils.http      : Downloaded 40% (total 4096K of 10225K) to /tmp/localstack/registry.linux-arm64.zip
2024-06-10 16:09:45 2024-06-10T10:39:45.528 DEBUG --- [et.reactor-0] localstack.utils.http      : Downloaded 50% (total 5120K of 10225K) to /tmp/localstack/registry.linux-arm64.zip
2024-06-10 16:09:45 2024-06-10T10:39:45.867 DEBUG --- [et.reactor-0] localstack.utils.http      : Downloaded 60% (total 6144K of 10225K) to /tmp/localstack/registry.linux-arm64.zip
2024-06-10 16:09:46 2024-06-10T10:39:46.014 DEBUG --- [et.reactor-0] localstack.utils.http      : Downloaded 70% (total 7168K of 10225K) to /tmp/localstack/registry.linux-arm64.zip
2024-06-10 16:09:46 2024-06-10T10:39:46.264 DEBUG --- [et.reactor-0] localstack.utils.http      : Downloaded 80% (total 8192K of 10225K) to /tmp/localstack/registry.linux-arm64.zip
2024-06-10 16:09:46 2024-06-10T10:39:46.465 DEBUG --- [et.reactor-0] localstack.utils.http      : Downloaded 90% (total 9216K of 10225K) to /tmp/localstack/registry.linux-arm64.zip
2024-06-10 16:09:46 2024-06-10T10:39:46.731 DEBUG --- [et.reactor-0] localstack.utils.http      : Downloaded 100% (total 10225K of 10225K) to /tmp/localstack/registry.linux-arm64.zip
2024-06-10 16:09:46 2024-06-10T10:39:46.749 DEBUG --- [et.reactor-0] localstack.utils.http      : Done downloading https://github.com/localstack/localstack-artifacts/raw/4e228449b7c6926a23fcf2c9cc02a95e444f7dd1/docker-registry/registry.linux-arm64.zip, response code 200, total 10225K
2024-06-10 16:09:46 2024-06-10T10:39:46.751 DEBUG --- [et.reactor-0] localstack.utils.run       : Executing command: ['unzip', '-o', '-q', '/tmp/localstack/registry.linux-arm64.zip']
2024-06-10 16:09:47 2024-06-10T10:39:47.058 DEBUG --- [et.reactor-0] localstack.packages.api    : Installation of docker-registry finished.
2024-06-10 16:09:47 2024-06-10T10:39:47.058  INFO --- [et.reactor-0] l.services.ecr.registry    : Starting ECR Docker registry (ECR_ENDPOINT_STRATEGY=domain) for region us-east-1 in account 000000000000
2024-06-10 16:09:47 2024-06-10T10:39:47.059 DEBUG --- [et.reactor-0] l.services.ecr.registry    : Starting registry with command: ['/var/lib/localstack/lib/docker-registry/latest/registry.linux-arm64', 'serve', '/tmp/tmpbb9ch87h']
2024-06-10 16:09:47 2024-06-10T10:39:47.060 DEBUG --- [-functhread6] localstack.utils.run       : Executing command: ['/var/lib/localstack/lib/docker-registry/latest/registry.linux-arm64', 'serve', '/tmp/tmpbb9ch87h']
2024-06-10 16:09:47 2024-06-10T10:39:47.060 DEBUG --- [et.reactor-0] l.services.ecr.registry    : Registering route from 000000000000.dkr.ecr.us-east-1.localhost:4566 to http://127.0.0.1:34951
2024-06-10 16:10:18 2024-06-10T10:40:18.280 ERROR --- [et.reactor-0] l.aws.handlers.logging     : exception during call chain
2024-06-10 16:10:18 Traceback (most recent call last):
2024-06-10 16:10:18   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
2024-06-10 16:10:18     handler(self, self.context, response)
2024-06-10 16:10:18   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 113, in __call__
2024-06-10 16:10:18     handler(chain, context, response)
2024-06-10 16:10:18   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 83, in __call__
2024-06-10 16:10:18     skeleton_response = self.skeleton.invoke(context)
2024-06-10 16:10:18                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-10 16:10:18   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
2024-06-10 16:10:18     return self.dispatch_request(serializer, context, instance)
2024-06-10 16:10:18            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-10 16:10:18   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request
2024-06-10 16:10:18     result = handler(context, instance) or {}
2024-06-10 16:10:18              ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-10 16:10:18   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/forwarder.py", line 136, in _call
2024-06-10 16:10:18     return handler(context, req)
2024-06-10 16:10:18            ^^^^^^^^^^^^^^^^^^^^^
2024-06-10 16:10:18   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
2024-06-10 16:10:18     return self.fn(*args, **kwargs)
2024-06-10 16:10:18            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-10 16:10:18   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/api/core.py", line 161, in operation_marker
2024-06-10 16:10:18     return fn(*args, **kwargs)
2024-06-10 16:10:18            ^^^^^^^^^^^^^^^^^^^
2024-06-10 16:10:18   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/ecr/provider.py.enc", line 70, in create_repository
2024-06-10 16:10:18     def create_repository(self,context,payload):B=context;A=call_moto(B);C=self._assure_registry_creation(registry_id=A[_I][_G],account_id=B.account_id,region=B.region);self._patch_repository_uri(repository=A[_I],registry=C);A.setdefault(_J,'latest');return A
2024-06-10 16:10:18                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-10 16:10:18   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/ecr/provider.py.enc", line 204, in _assure_registry_creation
2024-06-10 16:10:18     if not E:raise TimeoutError('Error while waiting to startup registry')
```

Can anyone help me out here? is there something I am configuring wrong or is it an issue in localstack?

here is my docker compose configuration for localstack image

```
localstack:
    image: localstack/localstack-pro:latest-arm64
    platform: linux/arm64
    ports:
      - "443:443"
      - "4510-4559:4510-4559"
      - "4566:4566"
    environment:
      DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      DOCKER_HOST: unix:///var/run/docker.sock
      EXTRA_CORS_ALLOWED_ORIGINS: http://localhost:3000
      LAMBDA_DOCKER_NETWORK: docker-local
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN}
      LOCALSTACK_HOST: localhost:4566
      DNS_ADDRESS: 0
      PERSISTENCE: 1
      DEBUG: 1
      HOSTNAME_EXTERNAL: localstack
      SNAPSHOT_SAVE_STRATEGY: ON_SHUTDOWN
      SNAPSHOT_LOAD_STRATEGY: ON_STARTUP
      PROVIDER_OVERRIDE_STEPFUNCTIONS: legacy
      ECR_ENDPOINT_STRATEGY: domain
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_DIRECTORY}/volume:/var/lib/localstack
```

### How are you starting LocalStack?

With a docker-compose file

**Comment by rahul-huma** [comment]
This problem did get fixed after I changed

`ECR_ENDPOINT_STRATEGY: domain`
to 
`ECR_ENDPOINT_STRATEGY: off`


can anyone help me understand what exactly does `ECR_ENDPOINT_STRATEGY` do?

**Comment by MarcelStranak** [comment]
Thank you for reaching out.

The `ECR_ENDPOINT_STRATEGY` configuration setting in LocalStack determines how the endpoints for Amazon Elastic Container Registry (ECR) are constructed. 

Below is an explanation of the different values:

- `ECR_ENDPOINT_STRATEGY=domain`: Uses a domain-based approach for the repository URIs. In this case, the URI includes the AWS account ID and the region, similar to how it would appear in a real AWS environment.
 For example:
  ```json
  "repositoryUri": "000000000000.dkr.ecr.us-east-1.localhost.localstack.cloud:4566/lambda-ecr-repo"
  ```
  This mimics the structure of real AWS ECR URIs, which can help ensure compatibility with tools and scripts that expect this format.

- `ECR_ENDPOINT_STRATEGY=off`: This strategy disables the domain-based structure and uses a simpler, direct approach. The repository URI is more straightforward and does not include the account ID or region.
 For example:
  ```json
  "repositoryUri": "localhost.localstack.cloud:4510/lambda-ecr-repo"
  ```
  This can simplify configurations and reduce potential issues with domain resolution.

Switching from `domain` to `off` likely resolved your issue by simplifying the repository URI, avoiding potential complications related to domain name resolution or formatting.

If you were using `samlocal` CLI, we are aware of this and we are working on solution https://github.com/localstack/aws-sam-cli-local/pull/20

**Comment by rahul-huma** [comment]
Thank You @MarcelStranak
