### ISSUE TITLE
bug: Invalid type for parameter stageDescription

### ISSUE THREAD

**Issue by lukasz-mazur2** [localstack/localstack#11019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Localstack complains about stageDescription parameter and is expecting a string value instead of a dictionary. 

Parameter validation failed:
Invalid type for parameter stageDescription, value: {'TracingEnabled': True, 'LoggingLevel': 'ERROR', 'DataTraceEnabled': True, 'MetricsEnabled': True, 'AccessLogSetting': {'DestinationArn': 'arn:aws:logs:eu-west-1:000000000000:log-group:/aws/apigateway/ikvj3dtbni/test:*', 'Format': '{ "xrayTraceId":"$context.xrayTraceId", "requestId":"$context.requestId",  "ip":"$context.identity.sourceIp", "caller":"$context.identity.caller",  "user":"$context.identity.user",  "userCognitoIdentityId":"$context.identity.cognitoIdentityId",  "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod",  "httpPath":"$context.path", "resourcePath":"$context.resourcePath",  "status":"$context.status", "protocol":"$context.protocol",  "responseLength":"$context.responseLength", "error":"$context.error.message",  "errorWaf":"$context.waf.error", "errorAuthorize":"$context.authorize.error",  "errorAuthorizer":"$context.authorizer.error",  "errorAuthenticate":"$context.authenticate.error",  "errorIntegration":"$context.integration.error" }'}, 'ThrottlingBurstLimit': -1, 'ThrottlingRateLimit': -1}, type: <class 'dict'>, valid types: <class 'str'> Traceback (most recent call last):

Full log:

```
LocalStack version: 3.4.1.dev20240605144018
LocalStack Docker container name: localstack-main
LocalStack Docker container id: da8acb69df1f
LocalStack Docker image sha: sha256:aaff8d61122880e2aa3fc65f53ac2c1945318dbf489000ce0c196c0319ac60fd
LocalStack build date: 2024-06-06
LocalStack build git hash: aa923d1

2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._patch_botocore_json_parser = <function _patch_botocore_json_parser at 0x7fcf6c8d36a0>)
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:_patch_botocore_json_parser
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._publish_config_as_analytics_event = <function _publish_config_as_analytics_event at 0x7fcf6c8d3a60>)
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:_publish_config_as_analytics_event
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._publish_container_info = <function _publish_container_info at 0x7fcf6c8d3d80>)
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:_publish_container_info
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._run_init_scripts_on_start = <function _run_init_scripts_on_start at 0x7fcf6c928d60>)
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:_run_init_scripts_on_start
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.apply_aws_runtime_patches = <function apply_aws_runtime_patches at 0x7fcf6c929440>)
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:apply_aws_runtime_patches
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.deprecation_warnings = <function deprecation_warnings at 0x7fcf6c9298a0>)
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:deprecation_warnings
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_cloudformation_deploy_ui = <function register_cloudformation_deploy_ui at 0x7fcf6c929bc0>)
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:register_cloudformation_deploy_ui
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_custom_endpoints = <function register_custom_endpoints at 0x7fcf6c7d9080>)
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:register_custom_endpoints
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_partition_adjusting_proxy_listener = <function register_partition_adjusting_proxy_listener at 0x7fcf6c929760>)
2024-06-12T10:15:46.021 DEBUG --- [  MainThread] plux.runtime.manager       : plugin localstack.hooks.on_infra_start:register_partition_adjusting_proxy_listener is disabled, reason: Load condition for plugin was false
2024-06-12T10:15:46.022 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.setup_dns_configuration_on_host = <function setup_dns_configuration_on_host at 0x7fcf6c7d9620>)
2024-06-12T10:15:46.022 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:setup_dns_configuration_on_host
(...)
2024-06-12T10:16:12.624 DEBUG --- [rvice-task_0] l.s.l.i.version_manager    : Version preparation of function arn:aws:lambda:eu-west-1:000000000000:function:HelloLambdaFunction:$LATEST took 1692.01ms
2024-06-12T10:16:12.624 DEBUG --- [rvice-task_0] l.s.l.i.version_manager    : Changing Lambda arn:aws:lambda:eu-west-1:000000000000:function:HelloLambdaFunction:$LATEST (id beaf58b1) to active
2024-06-12T10:16:12.624 DEBUG --- [rvice-task_0] l.s.l.i.event_manager      : Starting event manager arn:aws:lambda:eu-west-1:000000000000:function:HelloLambdaFunction:$LATEST id 140527687981648
2024-06-12T10:16:16.021 DEBUG --- [functhread81] l.s.c.e.template_deployer  : Handling "Add" for resource "lambdaApiGatewayInvoke" (2/3) type "AWS::Lambda::Permission" in loop iteration 1 (should_deploy=True)
2024-06-12T10:16:16.052 DEBUG --- [functhread81] l.s.c.e.template_deployer  : Handling "Add" for resource "RestStageDeploy" (2/2) type "AWS::CloudFormation::Stack" in loop iteration 1 (should_deploy=True)
2024-06-12T10:16:16.052 DEBUG --- [functhread81] l.s.c.e.template_deployer  : Dependency for resource {'Type': 'AWS::CloudFormation::Stack', 'Properties': {'TemplateURL': 'https://navblue-standard-common-modules.s3.localhost.localstack.cloud/templates/cloudformation-api-gateway-rest/1/0/cloudformation-api-gateway-rest-v1.0.1.yaml', 'Parameters': {'ResourceNamePrefix': 'cloudformation-api-gateway-rest', 'Phase': 'StageDeploy', 'StageName': 'test'}}, 'DependsOn': 'ProjectMethod', 'LogicalResourceId': 'RestStageDeploy', 'PhysicalResourceId': None} not yet deployed: ProjectMethod {'Type': 'AWS::ApiGateway::Method', 'Properties': {'HttpMethod': 'POST', 'Integration': {'Type': 'AWS', 'IntegrationHttpMethod': 'POST', 'IntegrationResponses': [{'StatusCode': '200'}], 'Uri': {'Fn::Sub': 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloLambdaFunction.Arn}/invocations'}}, 'MethodResponses': [{'StatusCode': '200'}], 'AuthorizationType': 'NONE', 'ResourceId': {'Ref': 'ProjectFirstResource'}, 'RestApiId': {'Fn::GetAtt': ['RestApiGateway', 'Outputs.RestApiGatewayId']}}, 'LogicalResourceId': 'ProjectMethod', 'PhysicalResourceId': None}
2024-06-12T10:16:16.138 DEBUG --- [functhread81] l.s.c.e.template_deployer  : Handling "Add" for resource "ProjectMethod" (1/2) type "AWS::ApiGateway::Method" in loop iteration 2 (should_deploy=True)
2024-06-12T10:16:16.178 DEBUG --- [functhread81] l.s.c.e.template_deployer  : Handling "Add" for resource "RestStageDeploy" (1/1) type "AWS::CloudFormation::Stack" in loop iteration 2 (should_deploy=True)
2024-06-12T10:16:16.185  INFO --- [et.reactor-1] localstack.request.aws     : AWS s3.GetObject => 200
2024-06-12T10:16:16.197 DEBUG --- [et.reactor-2] l.s.c.provider             : Creating stack "cloudformation-api-gateway-rest-RestStageDeploy-ee6a6005" with 4 resources ...
2024-06-12T10:16:16.198 DEBUG --- [functhread85] l.s.c.e.template_deployer  : Skipping deployment of "RestApiGateway", as resource condition evaluates to false
2024-06-12T10:16:16.198 DEBUG --- [functhread85] l.s.c.e.template_deployer  : Handling "Add" for resource "RestApiGateway" (1/4) type "AWS::ApiGateway::RestApi" in loop iteration 1 (should_deploy=False)
2024-06-12T10:16:16.199 DEBUG --- [functhread85] l.s.c.e.template_deployer  : Skipping deployment of "InitResource", as resource condition evaluates to false
2024-06-12T10:16:16.199 DEBUG --- [functhread85] l.s.c.e.template_deployer  : Handling "Add" for resource "InitResource" (1/3) type "AWS::ApiGateway::Resource" in loop iteration 1 (should_deploy=False)
2024-06-12T10:16:16.201 DEBUG --- [functhread85] l.s.c.e.template_deployer  : Skipping deployment of "InitMethod", as resource condition evaluates to false
2024-06-12T10:16:16.201 DEBUG --- [functhread85] l.s.c.e.template_deployer  : Handling "Add" for resource "InitMethod" (1/2) type "AWS::ApiGateway::Method" in loop iteration 1 (should_deploy=False)
2024-06-12T10:16:16.497 DEBUG --- [functhread85] l.s.c.e.template_deployer  : Handling "Add" for resource "RestApiDeployment" (1/1) type "AWS::ApiGateway::Deployment" in loop iteration 1 (should_deploy=True)
2024-06-12T10:16:16.501 DEBUG --- [functhread85] l.s.c.e.template_deployer  : Error applying changes for CloudFormation stack "cloudformation-api-gateway-rest-RestStageDeploy-ee6a6005": Parameter validation failed:
Invalid type for parameter stageDescription, value: {'TracingEnabled': True, 'LoggingLevel': 'ERROR', 'DataTraceEnabled': True, 'MetricsEnabled': True, 'AccessLogSetting': {'DestinationArn': 'arn:aws:logs:eu-west-1:000000000000:log-group:/aws/apigateway/ikvj3dtbni/test:*', 'Format': '{ "xrayTraceId":"$context.xrayTraceId", "requestId":"$context.requestId",  "ip":"$context.identity.sourceIp", "caller":"$context.identity.caller",  "user":"$context.identity.user",  "userCognitoIdentityId":"$context.identity.cognitoIdentityId",  "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod",  "httpPath":"$context.path", "resourcePath":"$context.resourcePath",  "status":"$context.status", "protocol":"$context.protocol",  "responseLength":"$context.responseLength", "error":"$context.error.message",  "errorWaf":"$context.waf.error", "errorAuthorize":"$context.authorize.error",  "errorAuthorizer":"$context.authorizer.error",  "errorAuthenticate":"$context.authenticate.error",  "errorIntegration":"$context.integration.error" }'}, 'ThrottlingBurstLimit': -1, 'ThrottlingRateLimit': -1}, type: <class 'dict'>, valid types: <class 'str'> Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1215, in _run
    self.do_apply_changes_in_loop(changes, stack)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1298, in do_apply_changes_in_loop
    self.apply_change(change, stack=stack)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1413, in apply_change
    progress_event = executor.deploy_loop(resource, resource_provider_payload)  # noqa
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/resource_provider.py", line 418, in deploy_loop
    event = self.execute_action(resource_provider, payload)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/resource_provider.py", line 491, in execute_action
    return resource_provider.create(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/apigateway/resource_providers/aws_apigateway_deployment.py", line 128, in create
    response = api.create_deployment(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 974, in _make_api_call
    request_dict = self._convert_to_request_dict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 1048, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter stageDescription, value: {'TracingEnabled': True, 'LoggingLevel': 'ERROR', 'DataTraceEnabled': True, 'MetricsEnabled': True, 'AccessLogSetting': {'DestinationArn': 'arn:aws:logs:eu-west-1:000000000000:log-group:/aws/apigateway/ikvj3dtbni/test:*', 'Format': '{ "xrayTraceId":"$context.xrayTraceId", "requestId":"$context.requestId",  "ip":"$context.identity.sourceIp", "caller":"$context.identity.caller",  "user":"$context.identity.user",  "userCognitoIdentityId":"$context.identity.cognitoIdentityId",  "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod",  "httpPath":"$context.path", "resourcePath":"$context.resourcePath",  "status":"$context.status", "protocol":"$context.protocol",  "responseLength":"$context.responseLength", "error":"$context.error.message",  "errorWaf":"$context.waf.error", "errorAuthorize":"$context.authorize.error",  "errorAuthorizer":"$context.authorizer.error",  "errorAuthenticate":"$context.authenticate.error",  "errorIntegration":"$context.integration.error" }'}, 'ThrottlingBurstLimit': -1, 'ThrottlingRateLimit': -1}, type: <class 'dict'>, valid types: <class 'str'>

2024-06-12T10:16:16.501  WARN --- [functhread85] l.s.c.engine.entities      : CFn resource failed to deploy: RestApiDeployment (Parameter validation failed:; Invalid type for parameter stageDescription, value: {'TracingEnabled': True, 'LoggingLevel': 'ERROR', 'DataTraceEnabled': True, 'MetricsEnabled': True, 'AccessLogSetting': {'DestinationArn': 'arn:aws:logs:eu-west-1:000000000000:log-group:/aws/apigateway/ikvj3dtbni/test:*', 'Format': '{ "xrayTraceId":"$context.xrayTraceId", "requestId":"$context.requestId",  "ip":"$context.identity.sourceIp", "caller":"$context.identity.caller",  "user":"$context.identity.user",  "userCognitoIdentityId":"$context.identity.cognitoIdentityId",  "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod",  "httpPath":"$context.path", "resourcePath":"$context.resourcePath",  "status":"$context.status", "protocol":"$context.protocol",  "responseLength":"$context.responseLength", "error":"$context.error.message",  "errorWaf":"$context.waf.error", "errorAuthorize":"$context.authorize.error",  "errorAuthorizer":"$context.authorizer.error",  "errorAuthenticate":"$context.authenticate.error",  "errorIntegration":"$context.integration.error" }'}, 'ThrottlingBurstLimit': -1, 'ThrottlingRateLimit': -1}, type: <class 'dict'>, valid types: <class 'str'>)
2024-06-12T10:16:21.210 DEBUG --- [functhread81] l.s.c.e.template_deployer  : Error applying changes for CloudFormation stack "cloudformation-api-gateway-rest": Resource handler returned message: "" (RequestToken: 10c10335-276a-33d3-5c07-018b684c3d26, HandlerErrorCode: InvalidRequest)None Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1215, in _run
    self.do_apply_changes_in_loop(changes, stack)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1298, in do_apply_changes_in_loop
    self.apply_change(change, stack=stack)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1426, in apply_change
    raise Exception(
Exception: Resource handler returned message: "" (RequestToken: 10c10335-276a-33d3-5c07-018b684c3d26, HandlerErrorCode: InvalidRequest)None

2024-06-12T10:16:21.210  WARN --- [functhread81] l.s.c.engine.entities      : CFn resource failed to deploy: RestStageDeploy (Resource handler returned message: "" (RequestToken: 10c10335-276a-33d3-5c07-018b684c3d26, HandlerErrorCode: InvalidRequest)None)
2024-06-12T10:16:21.210  WARN --- [functhread81] l.s.c.engine.entities      : CFn resource failed to deploy: RestStageDeploy
2024-06-12T10:16:35.591  INFO --- [et.reactor-2] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2024-06-12T10:16:35.850  INFO --- [et.reactor-1] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2024-06-12T10:16:36.110  INFO --- [et.reactor-0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
```

### Expected Behavior

StageDescription definition validation to mach the AWS one: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-deployment-stagedescription.html

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

        docker run \
          --rm \
          --name localstack-main \
          -p 4566:4566 \
          -p 4510-4559:4510-4559 \
          -e LOCALSTACK_AUTH_TOKEN="$LOCALSTACK_AUTH_TOKEN" \
          -e LS_LOG=DEBUG  \
          -e POD_LOAD_CLI_TIMEOUT=3000 \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -d \
          localstack/localstack-pro:latest

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS (5.15.146.1-microsoft-standard-WSL2)
- LocalStack:
  LocalStack version: 3.4.1.dev20240605144018
  LocalStack Docker image sha: sha256:aaff8d61122880e2aa3fc65f53ac2c1945318dbf489000ce0c196c0319ac60fd
  LocalStack build date: 2024-06-06
  LocalStack build git hash: aa923d1
```

**Comment by pinzon** [comment]
The solution of this bug has been merged. Thank you for reporting it.
