### ISSUE TITLE
kinesis get-shard-iterator --shard-iterator-type AT_TIMESTAMP not return response

### ISSUE THREAD

**Issue by krrrr38** [localstack/localstack#1106]
`kinesis get-shard-iterator --stream-name ... --shard-id ... --timestamp ... --shard-iterator-type AT_TIMESTAMP` doesn't return response.

checked with docker image `localstack/localstack` and `localstack/localstack:0.8.10`.

```sh
> docker run -p 4567-4584:4567-4584 --name localstack -d localstack/localstack
d8f8cc3812d153f5463b5479512332964e742a1039a304994c76aa00144fa957
> AWS_ACCESS_KEY_ID=a AWS_SECRET_ACCESS_KEY=b aws --region=ap-northfeast-1 --endpoint-url=http://localhost:4568 kinesis create-stream --stream-name at-timestamp-stack-test --shard-count 1
> AWS_ACCESS_KEY_ID=a AWS_SECRET_ACCESS_KEY=b aws --region=ap-northfeast-1 --endpoint-url=http://localhost:4568 kinesis list-shards --stream-name at-timestamp-stack-test
{
    "Shards": [
        {
            "ShardId": "shardId-000000000000",
            "HashKeyRange": {
                "StartingHashKey": "0",
                "EndingHashKey": "340282366920938463463374607431768211455"
            },
            "SequenceNumberRange": {
                "StartingSequenceNumber": "49592563044364750643392587126594223904872262096945938434"
            }
        }
    ]
}
>  AWS_ACCESS_KEY_ID=a AWS_SECRET_ACCESS_KEY=b aws --region=ap-northfeast-1 --endpoint-url=http://localhost:4568 kinesis get-shard-iterator --stream-name at-timestamp-stack-test --shard-id shardId-000000000000 --timestamp 2019-02-01T08:00:00.000-00:00 --shard-iterator-type AT_TIMESTAMP
(no return responses. if use sdk, get response read time out.)
```

we got error log by `docker logs localstack`

```
2019-02-01T09:02:39:ERROR:localstack.services.generic_proxy: Error forwarding request: ('Connection aborted.', BadStatusLine("''",)) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 216, in forward
    headers=forward_headers, stream=True)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

I checked following aws cli version.

```
> aws --version
aws-cli/1.16.80 Python/3.7.2 Darwin/17.7.0 botocore/1.12.70
```

**Comment by krrrr38** [comment]
ah, it might be issue on `kinesalite`. I will check it.

**Comment by whummer** [comment]
Thanks - closing this as upstream issue. We're regularly updating the kinesalite version, so we'll get the update into LocalStack once this is fixed upstream. Thanks
