### ISSUE TITLE
Authorization failed: list index out of range

### ISSUE THREAD

**Issue by petr-pokorny-1** [localstack/localstack#11116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have OpenAPI specification with two GET endpoints and request authorizer. When I import the api to API gateway, deploy it and invoke one of the method, I get `Authorization failed: list index out of range` error. The response is http 500.

I dont have this problem when doing the same on AWS.

### Expected Behavior

It should authorize the request and pass it downstream.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

```yaml
  localstack:
    container_name: "${LOCALSTACK_CONTAINER_NAME:-localstack}"
    image: "localstack/localstack-pro:${LOCALSTACK_VERSION:-latest}"  # required for Pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      #- LS_LOG=trace
      - DEBUG=${DEBUG:-1}
      - PERSISTENCE=${PERSISTENCE:-0}
      - USE_SSL=${USE_SSL:-1}
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - ECS_REMOVE_CONTAINERS=${ECS_REMOVE_CONTAINERS:-0}
      - DISABLE_EVENTS=${DISABLE_EVENTS:-0} # disable usage tracking
      - DYNAMODB_SHARE_DB=${DYNAMODB_SHARE_DB:-1}
      - DISABLE_CORS_CHECKS=1
      - DOCDB_PROXY_CONTAINER=1
      # access to tileserver data from lambda to real aws bucked
      # this settings bypass localstack transparent endpoint injection
      # https://docs.localstack.cloud/user-guide/tools/transparent-endpoint-injection/
      - DNS_NAME_PATTERNS_TO_RESOLVE_UPSTREAM=nts-location-services.s3.amazonaws.com
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:4566/_localstack/health?reload"]
      interval: 10s
      timeout: 5s
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

awslocal apigateway import-rest-api --body 'fileb://spec.yml'
awslocal apigateway create-deployment --rest-api-id "{api-id}" --stage-name "test"

and then run

curl -k https://{api-id}.execute-api.us-east-1.localhost.localstack.cloud:4566/test/data/999

The OpenApi spec is: (this one is not real, it is mock for testing)

```yaml
openapi: "3.0.1"
info:
  title: "Test API"
  version: "2024-06-05T09:45:01Z"
paths:
  /data/{id}/{z}/{x}/{proxy+}:
    get:
      summary: Test route 1
      security: [ { api-key-authorizer: [ ] } ]
      parameters:
        - { name: "id", in: "path", required: true, description: "id parameter", schema: { type: "string" } }
        - { name: "z", in: "path", required: true, description: "z parameter", schema: { type: "integer" } }
        - { name: "x", in: "path", required: true, description: "x parameter", schema: { type: "integer" } }
        - { name: "proxy", in: "path", required: true, description: "proxy parameter", schema: { type: "string" } }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: This is a mock response
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: '{"statusCode": 200}'
        responses:
          default:
            statusCode: '200'
            responseTemplates:
              application/json: |
                {
                  "message": "This is a mock response"
                }
  /data/{id}:
    get:
      summary: Test route 2
      security: [ { api-key-authorizer: [ ] } ]
      parameters:
        - { name: "id", in: "path", required: true, description: "id parameter", schema: { type: "string" } }
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: This is a mock response
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: '{"statusCode": 200}'
        responses:
          default:
            statusCode: '200'
            responseTemplates:
              application/json: |
                {
                  "message": "This is a mock response"
                }
components:
  schemas:
    MockResponse:
      type: object
      properties:
        message:
          type: string
          example: This is a mock response
  securitySchemes:
    api-key-authorizer:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
      x-amazon-apigateway-authtype: "custom"
      x-amazon-apigateway-authorizer:
        type: "request"
        authorizerUri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:location-services-local-api-key-authorizer/invocations "
        authorizerCredentials: "arn:aws:iam::000000000000:role/location-services-local-ApiKeyAuthorizerAuthoriz-e0bcd0c3"
        identitySource": "method.request.header.x-api-key, method.request.querystring.key"
        authorizerResultTtlInSeconds: 0 # non-zero value causes error "Unable to create authorizer 'api-key-authorizer': Invalid request input"
```

The request authorizer code:

```typescript
import type { APIGatewayRequestAuthorizerWithContextHandler, APIGatewayAuthorizerWithContextResult } from 'aws-lambda'
import type { ApiKeyAuthorizerContext } from '../../common/api.key.authorizer.context.js'

export const handler: APIGatewayRequestAuthorizerWithContextHandler<ApiKeyAuthorizerContext> = async (event) => {
  let apiKey: string
  if (event.queryStringParameters?.key != null) {
    apiKey = event.queryStringParameters.key
  } else {
    const headers: Record<string, string> = {}
    for (const key in event.headers) {
      const value = event.headers[key]
      if (value != null) {
        headers[key.toLowerCase()] = value
      }
    }
    apiKey = headers['x-api-key']
  }

  let result: APIGatewayAuthorizerWithContextResult<ApiKeyAuthorizerContext>
  if (apiKey != null) {
    result = {
      principalId: 'x-api-key',
      usageIdentifierKey: apiKey,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [{
          Action: 'execute-api:Invoke',
          Effect: 'Allow',
          Resource: event.methodArn
        }]
      },
      context: {
        apiKey
      }
    }
  } else {
    result = {
      principalId: 'x-api-key',
      policyDocument: {
        Version: '2012-10-17',
        Statement: [{
          Action: 'execute-api:Invoke',
          Effect: 'Deny',
          Resource: event.methodArn
        }]
      },
      context: {}
    }
  }
  return result
}

```

### Environment

```markdown
- OS: MacOS Sonoma 14.5
- LocalStack:
LocalStack version: 3.5.1.dev20240624022330
LocalStack build date: 2024-06-24
LocalStack build git hash: 51dd910
```

### Anything else?

localstack log file:

```txt
2024-07-01 01:40:14 2024-06-30T23:40:14.037 DEBUG --- [et.reactor-6] l.s.apigateway.helpers     : Match found for path: '/data/999' and method: 'GET'
2024-07-01 01:40:14 2024-06-30T23:40:14.037 DEBUG --- [et.reactor-6] l.s.apigateway.authorizers : processing API V1 invocation
2024-07-01 01:40:14 2024-06-30T23:40:14.038 DEBUG --- [et.reactor-6] l.s.apigateway.authorizers : Authorization failed: list index out of range - Traceback (most recent call last):
2024-07-01 01:40:14   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 338, in check_request_authorization
2024-07-01 01:40:14     try:C=T.get_authorizer_configuration(A)
2024-07-01 01:40:14           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-01 01:40:14   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 311, in get_authorizer_configuration
2024-07-01 01:40:14     LOG.debug('processing API V1 invocation');O=ResourcePatternMatch(I.api_object.resources);E=O.match_resource(A.invocation_path)
2024-07-01 01:40:14                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-01 01:40:14   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 293, in match_resource
2024-07-01 01:40:14     def match_resource(A,path):return A._resources[B[2]]if(B:=A._match_path(path))else _A
2024-07-01 01:40:14                                                               ^^^^^^^^^^^^^^^^^^^
2024-07-01 01:40:14   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 290, in _match_path
2024-07-01 01:40:14     return C._best_match(A)
2024-07-01 01:40:14            ^^^^^^^^^^^^^^^^
2024-07-01 01:40:14   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 292, in _best_match
2024-07-01 01:40:14     def _best_match(resource_candidates):A=BestRouteCandidate();return A.best_match(resource_candidates)
2024-07-01 01:40:14                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-01 01:40:14   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 262, in best_match
2024-07-01 01:40:14     if I==E[H]:B[A.resource_path]+=2
2024-07-01 01:40:14           ~^^^
2024-07-01 01:40:14 IndexError: list index out of range
2024-07-01 01:40:14 
2024-07-01 01:40:14 2024-06-30T23:40:14.038 DEBUG --- [et.reactor-6] l.s.apigateway.authorizers : Authorization failed: list index out of range
2024-07-01 01:40:14 Traceback (most recent call last):
2024-07-01 01:40:14   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 363, in is_request_authorized
2024-07-01 01:40:14     try:AuthorizerService().check_request_authorization(invocation_context)
2024-07-01 01:40:14         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-01 01:40:14   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 339, in check_request_authorization
2024-07-01 01:40:14     except Exception as L:LOG.debug('Authorization failed: %s - %s',L,traceback.format_exc());raise L
2024-07-01 01:40:14                                                                                               ^^^^^^^
2024-07-01 01:40:14   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 338, in check_request_authorization
2024-07-01 01:40:14     try:C=T.get_authorizer_configuration(A)
2024-07-01 01:40:14           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-01 01:40:14   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 311, in get_authorizer_configuration
2024-07-01 01:40:14     LOG.debug('processing API V1 invocation');O=ResourcePatternMatch(I.api_object.resources);E=O.match_resource(A.invocation_path)
2024-07-01 01:40:14                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-01 01:40:14   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 293, in match_resource
2024-07-01 01:40:14     def match_resource(A,path):return A._resources[B[2]]if(B:=A._match_path(path))else _A
2024-07-01 01:40:14                                                               ^^^^^^^^^^^^^^^^^^^
2024-07-01 01:40:14   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 290, in _match_path
2024-07-01 01:40:14     return C._best_match(A)
2024-07-01 01:40:14            ^^^^^^^^^^^^^^^^
2024-07-01 01:40:14   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 292, in _best_match
2024-07-01 01:40:14     def _best_match(resource_candidates):A=BestRouteCandidate();return A.best_match(resource_candidates)
2024-07-01 01:40:14                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-01 01:40:14   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 262, in best_match
2024-07-01 01:40:14     if I==E[H]:B[A.resource_path]+=2
2024-07-01 01:40:14           ~^^^
2024-07-01 01:40:14 IndexError: list index out of range
2024-07-01 01:40:14 2024-06-30T23:40:14.039  INFO --- [et.reactor-6] localstack.request.http    : GET /test/data/999 => 500
```

**Comment by bentsku** [comment]
Hello @petr-pokorny-1 and thanks for your report! 

We're currently in the process of rewriting our API Gateway implementation, and REST API are now available in the latest version. However, HTTP and WebSockets APIs (API Gateway v2) are not yet available.
If you're not using HTTP and WebSockets, could you please pull the latest or `3.7` version of LocalStack Pro with `docker pull localstack/localstack-pro:3.7` and try to start LocalStack with the following environment variable `PROVIDER_OVERRIDE_APIGATEWAY=next_gen` ?

This should fix the particular issue you've been having. 

Thanks!

**Comment by bentsku** [comment]
Hello again! The new API Gateway provider has been officially released, you can read more about it in our release announcement for 3.8: https://blog.localstack.cloud/localstack-release-v-3-8-0/#new-api-gateway-provider

This issue should now be fixed by using the feature flag. Thank you!
