### ISSUE TITLE
bug: CloudFormation and boolean parameters passed to a NestedStack

### ISSUE THREAD

**Issue by lukasz-mazur2** [localstack/localstack#11164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It appears that there is an issue passing boolean valued to a nested stack:

Main template:
```
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  TestMethod:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://common-modules.s3.localhost.localstack.cloud/child.yaml
      Parameters:
        ApiKeyRequired: true
```

Nested stack template:
```
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  RestApiId:
    Type: String
    Default: dummy-api-id
  ResourceId:
    Type: String
    Default: dummy-resource-id
  ApiKeyRequired:
    Type: String
    AllowedValues:
      - true
      - false

Resources:
  TestMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired:
        Ref: ApiKeyRequired
      AuthorizationType: AWS_IAM
      HttpMethod: GET
      ResourceId:
        Ref: ResourceId
      RestApiId:
        Ref: RestApiId
```

Outcome:
```
2024-07-09T13:58:06.748  INFO --- [et.reactor-0] l.request.internal.aws     : AWS cloudformation.CreateStack => 200
2024-07-09T13:58:06.752 DEBUG --- [et.reactor-1] rolo.gateway.wsgi          : POST localhost:4566/
2024-07-09T13:58:06.753 DEBUG --- [et.reactor-1] l.aws.protocol.serializer  : No accept header given. Using request's Content-Type (application/x-www-form-urlencoded; charset=utf-8) as preferred response Content-Type.
2024-07-09T13:58:06.754  INFO --- [et.reactor-1] l.request.internal.aws     : AWS cloudformation.DescribeStacks => 200
2024-07-09T13:58:06.780 DEBUG --- [functhread85] l.s.c.e.template_deployer  : Handling "Add" for resource "TestMethod" (1/1) type "AWS::ApiGateway::Method" (should_deploy=True)
2024-07-09T13:58:06.782 DEBUG --- [functhread85] l.s.c.e.template_deployer  : Error applying changes for CloudFormation stack "lm-test-3-TestMethod-f966bca4": Parameter validation failed:
Invalid type for parameter apiKeyRequired, value: true, type: <class 'str'>, valid types: <class 'bool'> Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1102, in _run
    self.do_apply_changes_in_loop(changes, stack)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1422, in do_apply_changes_in_loop
    self.apply_change(change, stack=stack)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1193, in apply_change
    progress_event = executor.deploy_loop(resource, resource_provider_payload)  # noqa
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/resource_provider.py", line 418, in deploy_loop
    event = self.execute_action(resource_provider, payload)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/resource_provider.py", line 491, in execute_action
    return resource_provider.create(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/apigateway/resource_providers/aws_apigateway_method.py", line 123, in create
    apigw.put_method(**params)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 974, in _make_api_call
    request_dict = self._convert_to_request_dict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 1048, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter apiKeyRequired, value: true, type: <class 'str'>, valid types: <class 'bool'>

2024-07-09T13:58:06.782  WARN --- [functhread85] l.s.c.engine.entities      : CFn resource failed to deploy: TestMethod (Parameter validation failed:; Invalid type for parameter apiKeyRequired, value: true, type: <class 'str'>, valid types: <class 'bool'>)
```

### Expected Behavior

This scenario works fine in AWS (with valid api id and resource of course).

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run \
        --rm \
        --name localstack-main \
        -p 4566:4566 \
        -p 4510-4559:4510-4559 \
        -e LOCALSTACK_AUTH_TOKEN="$LOCALSTACK_AUTH_TOKEN" \
        -e LS_LOG=DEBUG  \
        -e POD_LOAD_CLI_TIMEOUT=3000 \
        -v /var/run/docker.sock:/var/run/docker.sock \
        localstack/localstack-pro:latest

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS (5.15.153.1-microsoft-standard-WSL2)
- LocalStack:
  LocalStack 3.5.1.dev20240702032247
  LocalStack Docker image sha: 815bc086e9e138ce7b1d358b677f40592ca16ad3a9860675fbb68a16556f87af
  LocalStack build date: 2024-07-02
  LocalStack build git hash: 2ac673d
```

**Comment by pinzon** [comment]
This is a frequent issue. A lot of resources implement the transformations manually but some attributes could still be missing. For this case I made a fix for the mentioned resource. Hopefully in the future the resource providers can do the transformation automatically.
