### ISSUE TITLE
Get CloudWatch MetricData fails - Error Code: 500 INTERNAL SERVER ERROR; Request ID: null

### ISSUE THREAD

**Issue by ocker-docker-gummi-klokker** [localstack/localstack#1128]
Consider the following code (using localstack with testcontainers):

```javascript
// FIRE UP A LOCALSTACK CONTAINER AND EXPOSE CLOUDWATCH PORT
int cloudWatchPort = 4582;
FixedHostPortGenericContainer aws = new FixedHostPortGenericContainer("localstack/localstack:latest");
aws.withFixedExposedPort(cloudWatchPort, cloudWatchPort)
		.withEnv("HOSTNAME_EXTERNAL", "192.168.99.100")
		.withEnv("CLOUDWATCH_PORT_EXTERNAL", "4582")
		.withEnv("DEFAULT_REGION", "us-west-1");
aws.start();

// USE AWS SDK TO CREATE AN INTERFACE FOR ACCESSING CLOUDWATCH
AWSCredentialsProvider credentialsProvider = new AWSStaticCredentialsProvider(
		new BasicAWSCredentials("accesskey", "secretkey"));
EndpointConfiguration endpointConfiguration = new EndpointConfiguration("http://192.168.99.100:4582",
		"us-west-1");
AmazonCloudWatch cloudWatch = AmazonCloudWatchClientBuilder.standard()
		.withEndpointConfiguration(endpointConfiguration)
		.withCredentials(credentialsProvider)
		.build();

// NOW WRITE SOME METRICS TO THE LOCALSTACK CONTAINER.
// THIS IS DONE USING NETFLIX SERVO METRICS TOOL FOR JAVA APPLICATIONS,
// WHICH TAKES AN AmazonCloudWatch INSTANCE AS PARAMETER.
// NOTE: SENDING METRICS TO THE REAL AMAZON CLOUDWATCH AND WATCHING THEM IN THE AMAZON
// CONSOLE WORKS FINE.

// LISTING THE CREATED METRICS WORKS FINE, SO WE DIG OUT A METRIC TO USE WHEN 
// REQUESTING METRICS DATA.
ListMetricsResult listMetricsResult = cloudWatch.listMetrics();
Metric maxMemoryUsageMetric = new Metric();
for (Metric metric : listMetricsResult.getMetrics()) {
	if (metric.getMetricName().equals("MaxMemoryUsage")) {
		maxMemoryUsageMetric = metric;
	}
}

// NOW CREATE A METRIC DATA QUERY BASED ON THE ABOVE METRIC
MetricDataQuery metricDataQuery = new MetricDataQuery()
		.withId("someName")
		.withLabel("someLable")
		.withMetricStat(new MetricStat().withMetric(maxMemoryUsageMetric));
Date startTime = new Date(System.currentTimeMillis() - 3600 * 1000);
Date endTime = new Date(System.currentTimeMillis());
GetMetricDataRequest getMetricDataRequest = new GetMetricDataRequest()
		.withMetricDataQueries(metricDataQuery)
		.withStartTime(startTime)
		.withEndTime(endTime)
		.withMaxDatapoints(100);
		
// THE FOLLOWING CALL RETURNS CODE 500 INTERNAL SERVER ERROR; Request ID: null
GetMetricDataResult getMetricDataResult = cloudWatch.getMetricData(getMetricDataRequest);
```
Am I missing a data header on the getMetricDataRequest, containing a request ID?
Where/how do I get the ID to put into the request?
How do I set the ID on the request?
		
Although this issue may be more suited for an aws sdk forum, I was hoping that some 
of you localstack creators may be able to help (I guess you must have tried to read 
metrics data from a localstack container)

**Comment by ocker-docker-gummi-klokker** [comment]
Ok - I have read the other threads that seem to relate to this one, but no one seems to have really solved this.
Why is the ID null? Come on cloudstack java developers - a little help please.

**Comment by ocker-docker-gummi-klokker** [comment]
I have successfully tested against the real AWS CloudWatch Metric service with the following code.

Using this working request in the above test still gives the same error: AmazonCloudWatchException: CODE 500 INTERNAL SERVER ERROR; Request ID: null
Note that a sleep is inserted before trying to read values from the mock, and listing 
the metrics works fine (it's the getMetricData that does not work).

Ok - so either I am using the LocalStack AWS mock completely wrong, or
there is a bug in the implementation of the CloudWatch service. The reason 
that I suspect there is an error in the mock is that the listMetrics request works fine.

Is There Anybody Out There?

```javascript
AmazonCloudWatch cloudWatch = AmazonCloudWatchClientBuilder.standard()
	.withRegion("us-west-1")
	.build();

Dimension d1 = new Dimension().withName("class").withValue("customNamespace");
Dimension d2 = new Dimension().withName("id").withValue("specificId");
Dimension d3 = new Dimension().withName("level").withValue("INFO");
Dimension d4 = new Dimension().withName("type").withValue("GAUGE");

Metric metric = new Metric()
		.withNamespace("customNamespace")
		.withMetricName("MaxMemoryUsage")
		.withDimensions(d1, d2, d3, d4);

MetricDataQuery metricDataQuery = new MetricDataQuery()
		.withId("someName")
		.withLabel("someLable")
		.withReturnData(true)
		.withMetricStat(new MetricStat()
				.withMetric(metric)
				.withStat("Average")
				.withUnit("None")
				.withPeriod(5));

Date startTime = new Date(System.currentTimeMillis() - 3600 * 1000);
Date endTime = new Date(System.currentTimeMillis());

GetMetricDataRequest getMetricDataRequest = new GetMetricDataRequest()
		.withMetricDataQueries(metricDataQuery)
		.withStartTime(startTime)
		.withEndTime(endTime)
		.withMaxDatapoints(100);

GetMetricDataResult getMetricDataResult = cloudWatch.getMetricData(getMetricDataRequest);

List<MetricDataResult> resultList = getMetricDataResult.getMetricDataResults();
for (MetricDataResult metricResult : resultList) {
	List<Double> values = metricResult.getValues();
	System.out.println(values); // THIS ACTUALLY PRINTS AN ARRAY OF VALUES
}
```

**Comment by ocker-docker-gummi-klokker** [comment]
I tried to set the HOSTNAME_EXTERNAL to the full URL including port like mattjanssen suggests in [this ](https://github.com/localstack/localstack/issues/708)thread but with no success.

Trying with the AWS cli against the real AWS works fine.
Trying with the AWS cli against the mock gives the following (partial) debug output:

```javascript
AWS_ACCESS_KEY_ID=accesskey AWS_SECRET_ACCESS_KEY=secretkey  aws --endpoint-url=http://192.168.99.100:4582 cloudwatch get-metric-data --metric-data-queries file://./metric-data-queries.json --start-time
...
2019-02-22 09:48:18,664 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2019-02-22 09:48:18,665 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2019-02-22 07:28:04,266 - MainThread - botocore.loaders - DEBUG - Loading JSON file: C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\botocore\data\endpoints.json
...
2019-02-22 07:28:04,295 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=GetMetricData) with params: 
	{'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'aws-cli/1.16.109 Python/3.6.0 Windows/7 botocore/1.12.99'}, 
	'body': {'Action': 'GetMetricData', 'Version': '2010-08-01', 'MetricDataQueries.member.1.Id': 'v1', 'MetricDataQueries.member.1.MetricStat.Metric.Namespace': 'customNamespace', 'MetricDataQueries.member.1.MetricStat.Metric.MetricName': 
	'MaxMemoryUsage', 'MetricDataQueries.member.1.MetricStat.Metric.Dimensions.member.1.Name': 'class', 'MetricDataQueries.member.1.MetricStat.Metric.Dimensions.member.1.Value': 'customNamespace', 'MetricDataQueries.member.1.MetricStat.Metric.Dimensions.member.2.Name': 
	'id', 'MetricDataQueries.member.1.MetricStat.Metric.Dimensions.member.2.Value': 'specificId', 'MetricDataQueries.member.1.MetricStat.Metric.Dimensions.member.3.Name': 'level', 'MetricDataQueries.member.1.MetricStat.Metric.Dimensions.member.3.Value': 
	'INFO', 'MetricDataQueries.member.1.MetricStat.Metric.Dimensions.member.4.Name': 'type', 'MetricDataQueries.member.1.MetricStat.Metric.Dimensions.member.4.Value': 'GAUGE', 'MetricDataQueries.member.1.MetricStat.Period': 5, 
	'MetricDataQueries.member.1.MetricStat.Stat': 'Average', 'MetricDataQueries.member.1.MetricStat.Unit': 'None', 'MetricDataQueries.member.1.Label': 'string', 'MetricDataQueries.member.1.ReturnData': 'true', 'StartTime': '2019-02-22T06:00:00Z', 
	'EndTime': '2019-02-22T06:27:00Z'}, 'url': 'http://192.168.99.100:4582/', 'context': {'client_region': 'us-west-1', 'client_config': <botocore.config.Config object at 0x03833810>, 'has_streaming_input': False, 'auth_type': None}}

2019-02-22 07:28:04,298 - MainThread - botocore.hooks - DEBUG - Event request-created.cloudwatch.GetMetricData: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x03833850>>
2019-02-22 07:28:04,299 - MainThread - botocore.hooks - DEBUG - Event choose-signer.cloudwatch.GetMetricData: calling handler <function set_operation_specific_signer at 0x030B4978>
2019-02-22 07:28:04,300 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2019-02-22 07:28:04,301 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
	POST
	/
	content-type:application/x-www-form-urlencoded; charset=utf-8
	host:192.168.99.100:4582
	x-amz-date:20190222T062804Z

	content-type;host;x-amz-date
	86eb864a07ae9912b15b84f874f0e3aa98d01401bf6b34ce8963c762df9cf12c

2019-02-22 07:28:04,307 - MainThread - botocore.auth - DEBUG - StringToSign:
	AWS4-HMAC-SHA256
	20190222T062804Z
	20190222/us-west-1/monitoring/aws4_request
	c8f53cea09d7db2fff76300a21455fbf0da53ef5f7e950ae0b2c81f446670a55

2019-02-22 07:28:04,310 - MainThread - botocore.auth - DEBUG - Signature:
	b68e2abe6a08990463d4c13e8b92ebace0cc10e6a19a5ba3d2c1084c81a5e7bb

2019-02-22 07:28:04,312 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=http://192.168.99.100:4582/, headers={'Content-Type': b'application/x-www-form-urlencoded; 
	charset=utf-8', 'User-Agent': b'aws-cli/1.16.109 Python/3.6.0 Windows/7 botocore/1.12.99', 'X-Amz-Date': b'20190222T062804Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=FKIARH2HQVZZVNEJS3RA/20190222/us-west-1/monitoring/aws4_request, 
	SignedHeaders=content-type;host;x-amz-date, Signature=b68e2abe6a08990563d4c33e8b32eacce0cc00e6a13a5ba3d1c1084c81a5e7bb', 'Content-Length': '1118'}>

2019-02-22 07:28:04,314 - MainThread - urllib3.util.retry - DEBUG - Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2019-02-22 07:28:04,316 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.99.100:4582
2019-02-22 07:28:04,343 - MainThread - urllib3.connectionpool - DEBUG - http://192.168.99.100:4582 "POST / HTTP/1.1" 500 291
2019-02-22 07:28:04,344 - MainThread - botocore.parsers - DEBUG - Response headers: {'Content-Type': 'text/html', 'Content-Length': '291', 'Server': 'Werkzeug/0.14.1 Python/2.7.15', 'Date': 'Fri, 22 Feb 2019 06:28:02 GMT'}
2019-02-22 07:28:04,345 - MainThread - botocore.parsers - DEBUG - Response body:
	b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request.  
	Either the server is overloaded or there is an error in the application.</p>\n'

2019-02-22 07:28:04,348 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
	Traceback (most recent call last):
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\botocore\parsers.py", line 432, in _parse_xml_string_to_dom
		parser.feed(xml_string)
	  File "<string>", line None
	xml.etree.ElementTree.ParseError: syntax error: line 1, column 54

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 207, in main
		return command_table[parsed_args.command](remaining, parsed_args)
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 348, in __call__
		return command_table[parsed_args.operation](remaining, parsed_globals)
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 520, in __call__
		call_parameters, parsed_globals)
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 641, in invoke
		self._display_response(operation_name, response, parsed_globals)
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\awscli\clidriver.py", line 661, in _display_response
		formatter(command_name, response)
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\awscli\formatter.py", line 69, in __call__
		response_data = response.build_full_result()
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\botocore\paginate.py", line 449, in build_full_result
		for response in self:
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\botocore\paginate.py", line 255, in __iter__
		response = self._make_request(current_kwargs)
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\botocore\paginate.py", line 332, in _make_request
		return self._method(**current_kwargs)
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\botocore\client.py", line 357, in _api_call
		return self._make_api_call(operation_name, kwargs)
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\botocore\client.py", line 648, in _make_api_call
		operation_model, request_dict, request_context)
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\botocore\client.py", line 667, in _make_request
		return self._endpoint.make_request(operation_model, request_dict)
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\botocore\endpoint.py", line 102, in make_request
		return self._send_request(request_dict, operation_model)
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\botocore\endpoint.py", line 135, in _send_request
		request, operation_model, context)
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\botocore\endpoint.py", line 167, in _get_response
		request, operation_model)
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\botocore\endpoint.py", line 218, in _do_get_response
		response_dict, operation_model.output_shape)
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\botocore\parsers.py", line 240, in parse
		parsed = self._do_error_parse(response, shape)
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\botocore\parsers.py", line 485, in _do_error_parse
		root = self._parse_xml_string_to_dom(xml_contents)
	  File "C:\Program Files (x86)\Amazon\AWSCLI\runtime\lib\site-packages\botocore\parsers.py", line 437, in _parse_xml_string_to_dom
		"invalid XML received:\n%s" % (e, xml_string))
	botocore.parsers.ResponseParserError: Unable to parse response (syntax error: line 1, column 54), invalid XML received:
	b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request.  
		Either the server is overloaded or there is an error in the application.</p>\n'

2019-02-22 07:28:04,366 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Unable to parse response (syntax error: line 1, column 54), invalid XML received:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request.  
	Either the server is overloaded or there is an error in the application.</p>\n'
```

**Comment by DavidTanner** [comment]
LocalStack is using Moto for CloudWatch, and they haven't implemented getMetricData yet.
https://github.com/spulec/moto/blob/0d28d51f909709705c5fdcda5dede17540d44b1f/IMPLEMENTATION_COVERAGE.md

**Comment by whummer** [comment]
Thanks for reporting @ocker-docker-gummi-klokker @DavidTanner . This issue has been raised a while ago, but it is now fixed in the `latest` version. An integration test has been added here to cover this functionality: https://github.com/localstack/localstack-java-utils/pull/10 Thanks

**Comment by ldebello** [comment]
@whummer I found this issue looking for something similar it seems the API is working but for some reason is not returning statistical data, I have created a test to validate this https://github.com/ldebello/localstack-java-utils/commit/07e43218f3ac81453280bc7416cfd7b394bd339f#diff-cfe814246970f31d53f01daaa8c3b5d0R83
