### ISSUE TITLE
bug: CloudFormation fails to create AWS::StepFunctions::Activity with tags

### ISSUE THREAD

**Issue by sigpwned** [localstack/localstack#11308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a CloudFormation template that looks like this:

```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  ExampleActivity:
    Type: AWS::StepFunctions::Activity
    Properties:
      Name: ExampleActivity
      Tags:
        - Key: alpha
          Value: bravo
```

When I deploy it with localstack, I get the following error:

```
2024-08-04T19:28:24.699  WARN --- [-functhread5] l.s.c.engine.entities      : CFn resource failed to deploy: ExampleActivity (Parameter validation failed:; Unknown parameter in tags[0]: "Key", must be one of: key, value; Unknown parameter in tags[0]: "Value", must be one of: key, value)
```

### Expected Behavior

I expect the template to deploy successfully and create the given Activity.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal cloudformation create-stack --stack-name Example --template-body "$(cat template.yml")

### Environment

```markdown
- OS: MacOS 14.5
- LocalStack:
  LocalStack version: 3.6.0
  LocalStack Docker image sha: sha256:fb8addaddc0021a11f0760026635b404e3599e2d5f149dba2d7281cb1a790899
  LocalStack build date: 2024-07-25
  LocalStack build git hash: 5c077c795
```

### Anything else?

I enabled debug logs and got the following more detailed logs during the failure:

```
[main] INFO org.testcontainers.images.PullPolicy - Image pull policy will be performed by: DefaultPullPolicy()
[main] INFO org.testcontainers.utility.ImageNameSubstitutor - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
[main] INFO org.testcontainers.DockerClientFactory - Testcontainers version: 1.20.1
[main] INFO org.testcontainers.dockerclient.DockerClientProviderStrategy - Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
[main] INFO org.testcontainers.dockerclient.DockerClientProviderStrategy - Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
[main] INFO org.testcontainers.DockerClientFactory - Docker host IP address is localhost
[main] INFO org.testcontainers.DockerClientFactory - Connected to docker: 
  Server Version: 20.10.12
  API Version: 1.41
  Operating System: Docker Desktop
  Total Memory: 1988 MB
[main] INFO tc.testcontainers/ryuk:0.8.1 - Creating container for image: testcontainers/ryuk:0.8.1
[main] INFO org.testcontainers.utility.RegistryAuthLocator - Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: testcontainers/ryuk:0.8.1, configFile: /Users/aboothe/.docker/config.json, configEnv: DOCKER_AUTH_CONFIG). Falling back to docker-java default behaviour. Exception message: Could not execute [docker-credential-desktop, get]. Error=2, No such file or directory
[main] INFO tc.testcontainers/ryuk:0.8.1 - Container testcontainers/ryuk:0.8.1 is starting: e5bd137a9a55083305be95b6e4150e12dbbd2573bb9c1af86a35bf4f626aa731
[main] INFO tc.testcontainers/ryuk:0.8.1 - Container testcontainers/ryuk:0.8.1 started in PT0.407216S
[main] INFO org.testcontainers.utility.RyukResourceReaper - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
[main] INFO org.testcontainers.DockerClientFactory - Checking the system...
[main] INFO org.testcontainers.DockerClientFactory - ✔︎ Docker server version should be at least 1.6.0
[main] INFO tc.localstack/localstack:3 - LOCALSTACK_HOST environment variable set to localhost (to match host-routable address for container)
[main] INFO tc.localstack/localstack:3 - Creating container for image: localstack/localstack:3
[main] INFO tc.localstack/localstack:3 - Container localstack/localstack:3 is starting: 354118d21e065cd2edf40f6159d472d04f737b46e15a7c24a53f8c61ebd760cc
LocalStack supervisor: starting
LocalStack supervisor: localstack process (PID 19) starting
2024-08-04T19:49:36.339 DEBUG --- [  MainThread] l.utils.docker_utils       : Using SdkDockerClient. LEGACY_DOCKER_CLIENT: False, SDK installed: True
2024-08-04T19:49:36.408  WARN --- [  MainThread] l.services.internal        : Enabling diagnose endpoint, please be aware that this can expose sensitive information via your network.
2024-08-04T19:49:36.414 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.runtime.components.aws = <class 'localstack.aws.components.AwsComponents'>)
2024-08-04T19:49:36.414 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.runtime.components:aws

LocalStack version: 3.6.0
LocalStack build date: 2024-07-25
LocalStack build git hash: 5c077c795

2024-08-04T19:49:36.414 DEBUG --- [  MainThread] localstack.utils.run       : Executing command: rm -rf "/tmp/localstack"
2024-08-04T19:49:36.426 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._patch_botocore_endpoint_in_memory = <function _patch_botocore_endpoint_in_memory at 0xffffa5e891c0>)
2024-08-04T19:49:36.426 DEBUG --- [  MainThread] plux.runtime.manager       : plugin localstack.hooks.on_infra_start:_patch_botocore_endpoint_in_memory is disabled, reason: Load condition for plugin was false
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._patch_botocore_json_parser = <function _patch_botocore_json_parser at 0xffffa5e88e00>)
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:_patch_botocore_json_parser
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._patch_cbor2 = <function _patch_cbor2 at 0xffffa5e88f40>)
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:_patch_cbor2
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._publish_config_as_analytics_event = <function _publish_config_as_analytics_event at 0xffffa544c860>)
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:_publish_config_as_analytics_event
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._publish_container_info = <function _publish_container_info at 0xffffa544c4a0>)
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:_publish_container_info
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._run_init_scripts_on_start = <function _run_init_scripts_on_start at 0xffffa54272e0>)
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:_run_init_scripts_on_start
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.apply_aws_runtime_patches = <function apply_aws_runtime_patches at 0xffffa544c220>)
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:apply_aws_runtime_patches
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.apply_runtime_patches = <function apply_runtime_patches at 0xffffa544f2e0>)
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:apply_runtime_patches
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.deprecation_warnings = <function deprecation_warnings at 0xffffa544f6a0>)
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:deprecation_warnings
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_cloudformation_deploy_ui = <function register_cloudformation_deploy_ui at 0xffffa544f920>)
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:register_cloudformation_deploy_ui
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_custom_endpoints = <function register_custom_endpoints at 0xffffa5339c60>)
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:register_custom_endpoints
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_partition_adjusting_proxy_listener = <function register_partition_adjusting_proxy_listener at 0xffffa544f560>)
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : plugin localstack.hooks.on_infra_start:register_partition_adjusting_proxy_listener is disabled, reason: Load condition for plugin was false
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.setup_dns_configuration_on_host = <function setup_dns_configuration_on_host at 0xffffa533a0c0>)
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:setup_dns_configuration_on_host
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.start_dns_server = <function start_dns_server at 0xffffa5339f80>)
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:start_dns_server
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.validate_configuration = <function validate_configuration at 0xffffa5339b20>)
2024-08-04T19:49:36.427 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_start:validate_configuration
2024-08-04T19:49:36.483 DEBUG --- [  MainThread] localstack.dns.server      : Determined fallback dns: 192.168.65.5
2024-08-04T19:49:36.483 DEBUG --- [  MainThread] localstack.dns.server      : Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
2024-08-04T19:49:36.483 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*localhost.localstack.cloud pointing to LocalStack
2024-08-04T19:49:36.483 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*localhost.localstack.cloud with record DynamicRecord(record_type=<RecordType.A: 1>, record_id=None)
2024-08-04T19:49:36.483 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*localhost.localstack.cloud with record DynamicRecord(record_type=<RecordType.AAAA: 2>, record_id=None)
2024-08-04T19:49:36.483 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*localhost pointing to LocalStack
2024-08-04T19:49:36.483 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*localhost with record DynamicRecord(record_type=<RecordType.A: 1>, record_id=None)
2024-08-04T19:49:36.483 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*localhost with record DynamicRecord(record_type=<RecordType.AAAA: 2>, record_id=None)
2024-08-04T19:49:36.485 DEBUG --- [-functhread1] localstack.dns.server      : DNS Server started
2024-08-04T19:49:36.487 DEBUG --- [  MainThread] localstack.dns.server      : DNS server startup finished.
2024-08-04T19:49:36.490 DEBUG --- [  MainThread] localstack.runtime.init    : Init scripts discovered: {BOOT: [], START: [], READY: [], SHUTDOWN: []}
2024-08-04T19:49:36.490 DEBUG --- [  MainThread] localstack.plugins         : Checking for the usage of deprecated community features and configs...
2024-08-04T19:49:36.495 DEBUG --- [  MainThread] localstack.dns.server      : Overwriting container DNS server to point to localhost
2024-08-04T19:49:36.495 DEBUG --- [  MainThread] localstack.utils.ssl       : Attempting to download local SSL certificate file
2024-08-04T19:49:36.869 DEBUG --- [  MainThread] localstack.utils.http      : Starting download from https://github.com/localstack/localstack-artifacts/raw/master/local-certs/server.key to /var/lib/localstack/cache/server.test.pem
2024-08-04T19:49:36.870 DEBUG --- [  MainThread] localstack.utils.http      : Downloaded 100% (total 4K of 4K) to /var/lib/localstack/cache/server.test.pem
2024-08-04T19:49:36.874 DEBUG --- [  MainThread] localstack.utils.http      : Done downloading https://github.com/localstack/localstack-artifacts/raw/master/local-certs/server.key, response code 200, total 4K
2024-08-04T19:49:36.876 DEBUG --- [  MainThread] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.runtime.server.twisted = <class 'localstack.runtime.server.plugins.TwistedRuntimeServerPlugin'>)
2024-08-04T19:49:36.876 DEBUG --- [  MainThread] plux.runtime.manager       : loading plugin localstack.runtime.server:twisted
2024-08-04T19:49:36.985 DEBUG --- [ady_monitor)] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_ready._run_init_scripts_on_ready = <function _run_init_scripts_on_ready at 0xffffa5427420>)
2024-08-04T19:49:36.985 DEBUG --- [ady_monitor)] plux.runtime.manager       : loading plugin localstack.hooks.on_infra_ready:_run_init_scripts_on_ready
2024-08-04T19:49:36.985 DEBUG --- [ady_monitor)] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.hooks.on_infra_ready.register_virtual_host_routes = <function register_virtual_host_routes at 0xffff9d268400>)
2024-08-04T19:49:36.985 DEBUG --- [ady_monitor)] plux.runtime.manager       : plugin localstack.hooks.on_infra_ready:register_virtual_host_routes is disabled, reason: Load condition for plugin was false
Ready.
[main] INFO tc.localstack/localstack:3 - Container localstack/localstack:3 started in PT1.683799S
2024-08-04T19:49:37.361 DEBUG --- [et.reactor-0] rolo.gateway.wsgi          : POST 127.0.0.1:53512/
2024-08-04T19:49:37.361 DEBUG --- [et.reactor-0] l.a.p.service_router       : building service catalog index cache file /var/lib/localstack/cache/service-catalog-3_6_0-1_34_145.pickle
2024-08-04T19:49:38.696 DEBUG --- [et.reactor-0] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.aws.provider.cloudformation:default = <function cloudformation at 0xffff7850b2e0>)
2024-08-04T19:49:38.696 DEBUG --- [et.reactor-0] plux.runtime.manager       : loading plugin localstack.aws.provider:cloudformation:default
2024-08-04T19:49:38.807 DEBUG --- [et.reactor-0] l.s.c.provider             : Creating stack "IngestionStack" with 1 resources ...
2024-08-04T19:49:38.808 DEBUG --- [et.reactor-0] l.aws.protocol.serializer  : No accept header given. Using request's Content-Type (application/x-www-form-urlencoded; charset=utf-8) as preferred response Content-Type.
2024-08-04T19:49:38.808  INFO --- [et.reactor-0] localstack.request.aws     : AWS cloudformation.CreateStack => 200; 000000000000/us-east-1; CreateStackInput({'StackName': 'IngestionStack', 'TemplateBody': 'AWSTemplateFormatVersion: 2010-09-09\nResources:\n  ExampleActivity:\n    Type: AWS::StepFunctions::Activity\n    Properties:\n      Name: ExmapleActivity\n      Tags:\n        - Key: alpha\n          Value: bravo\n', 'Parameters': [{'ParameterKey': 'Profile', 'ParameterValue': 'test'}, {'ParameterKey': 'BuildId', 'ParameterValue': '00000000000000000000'}], 'StackId': 'arn:aws:cloudformation:us-east-1:000000000000:stack/IngestionStack/60aea265', 'StackStatus': 'CREATE_IN_PROGRESS', 'CreationTime': '2024-08-04T19:49:38.807Z', 'LastUpdatedTime': '2024-08-04T19:49:38.807Z', 'Description': None, 'RollbackConfiguration': {}, 'DisableRollback': False, 'EnableTerminationProtection': False}, headers={'amz-sdk-invocation-id': 'a52949eb-262b-4a9e-cf9f-519aa501b5a0', 'amz-sdk-request': 'attempt=1; max=4', 'Authorization': 'AWS4-HMAC-SHA256 Credential=test/20240804/us-east-1/cloudformation/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date, Signature=87fa70a0899de0613ed80edbfaf7442c44eac485778eb1266c82e14326ea4d17', 'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'aws-sdk-java/2.20.9 Mac_OS_X/14.5 Java_HotSpot_TM__64-Bit_Server_VM/17.0.2+8-LTS-86 Java/17.0.2 kotlin/1.6.20-release-275(1.6.20) vendor/Oracle_Corporation io/sync http/UrlConnection cfg/retry-mode/legacy', 'X-Amz-Date': '20240804T194937Z', 'Accept': '*/*', 'Host': '127.0.0.1:53512', 'Connection': 'keep-alive', 'Content-Length': '504', 'x-moto-account-id': '000000000000'}); CreateStackOutput({'StackId': 'arn:aws:cloudformation:us-east-1:000000000000:stack/IngestionStack/60aea265'}, headers={'Content-Type': 'text/xml', 'Content-Length': '371'})
2024-08-04T19:49:38.852 DEBUG --- [et.reactor-0] rolo.gateway.wsgi          : POST 127.0.0.1:53512/
2024-08-04T19:49:38.853 DEBUG --- [et.reactor-0] l.aws.protocol.serializer  : No accept header given. Using request's Content-Type (application/x-www-form-urlencoded; charset=utf-8) as preferred response Content-Type.
2024-08-04T19:49:38.854  INFO --- [et.reactor-0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200; 000000000000/us-east-1; DescribeStacksInput({'StackName': 'IngestionStack'}, headers={'amz-sdk-invocation-id': '8cda8be3-e4fd-4d3b-5973-5b8c00f2e865', 'amz-sdk-request': 'attempt=1; max=4', 'Authorization': 'AWS4-HMAC-SHA256 Credential=test/20240804/us-east-1/cloudformation/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date, Signature=2d07e7d9ce4ca61cff2afcfc11eab77cf16983aa39d949b7ceb8a3abe5bf768d', 'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'aws-sdk-java/2.20.9 Mac_OS_X/14.5 Java_HotSpot_TM__64-Bit_Server_VM/17.0.2+8-LTS-86 Java/17.0.2 kotlin/1.6.20-release-275(1.6.20) vendor/Oracle_Corporation io/sync http/UrlConnection cfg/retry-mode/legacy hll/waiter', 'X-Amz-Date': '20240804T194938Z', 'Accept': '*/*', 'Host': '127.0.0.1:53512', 'Connection': 'keep-alive', 'Content-Length': '65', 'x-moto-account-id': '000000000000'}); DescribeStacksOutput({'Stacks': [{'StackName': 'IngestionStack', 'StackId': 'arn:aws:cloudformation:us-east-1:000000000000:stack/IngestionStack/60aea265', 'StackStatus': 'CREATE_IN_PROGRESS', 'CreationTime': '2024-08-04T19:49:38.807Z', 'LastUpdatedTime': '2024-08-04T19:49:38.807Z', 'Description': None, 'RollbackConfiguration': {}, 'DisableRollback': False, 'EnableTerminationProtection': False, 'Tags': [], 'DriftInformation': {'StackDriftStatus': 'NOT_CHECKED'}, 'NotificationARNs': []}]}, headers={'Content-Type': 'text/xml', 'Content-Length': '859'})
2024-08-04T19:49:38.861 DEBUG --- [-functhread5] l.s.c.e.template_deployer  : Handling "Add" for resource "ExampleActivity" (1/1) type "AWS::StepFunctions::Activity" (should_deploy=True)
2024-08-04T19:49:38.875 DEBUG --- [-functhread5] plux.runtime.manager       : instantiating plugin PluginSpec(localstack.cloudformation.resource_providers.AWS::StepFunctions::Activity = <class 'localstack.services.stepfunctions.resource_providers.aws_stepfunctions_activity_plugin.StepFunctionsActivityProviderPlugin'>)
2024-08-04T19:49:38.875 DEBUG --- [-functhread5] plux.runtime.manager       : loading plugin localstack.cloudformation.resource_providers:AWS::StepFunctions::Activity
2024-08-04T19:49:39.152 DEBUG --- [-functhread5] l.s.c.e.template_deployer  : Error applying changes for CloudFormation stack "IngestionStack": Parameter validation failed:
Unknown parameter in tags[0]: "Key", must be one of: key, value
Unknown parameter in tags[0]: "Value", must be one of: key, value Traceback (most recent call last):
  File "/opt/code/localstack/localstack-core/localstack/services/cloudformation/engine/template_deployer.py", line 1116, in _run
    self.do_apply_changes_in_loop(changes, stack)
  File "/opt/code/localstack/localstack-core/localstack/services/cloudformation/engine/template_deployer.py", line 1436, in do_apply_changes_in_loop
    self.apply_change(change, stack=stack)
  File "/opt/code/localstack/localstack-core/localstack/services/cloudformation/engine/template_deployer.py", line 1207, in apply_change
    progress_event = executor.deploy_loop(resource, resource_provider_payload)  # noqa
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack-core/localstack/services/cloudformation/resource_provider.py", line 418, in deploy_loop
    event = self.execute_action(resource_provider, payload)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack-core/localstack/services/cloudformation/resource_provider.py", line 491, in execute_action
    return resource_provider.create(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack-core/localstack/services/stepfunctions/resource_providers/aws_stepfunctions_activity.py", line 62, in create
    response = step_functions.create_activity(name=model["Name"], tags=model["Tags"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 974, in _make_api_call
    request_dict = self._convert_to_request_dict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 1048, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in tags[0]: "Key", must be one of: key, value
Unknown parameter in tags[0]: "Value", must be one of: key, value

2024-08-04T19:49:39.153  WARN --- [-functhread5] l.s.c.engine.entities      : CFn resource failed to deploy: ExampleActivity (Parameter validation failed:; Unknown parameter in tags[0]: "Key", must be one of: key, value; Unknown parameter in tags[0]: "Value", must be one of: key, value)
```

I confirmed that the tags syntax is correct [per the CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-activity.html), so the current behavior of LocalStack is inconsistent with the current behavior of AWS.

Commenting the tags out allows the Activity to deploy, so there is at least a non-destructive workaround. Specifically, the following template deploys successfully:

```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  ExampleActivity:
    Type: AWS::StepFunctions::Activity
    Properties:
      Name: ExampleActivity
#       Tags:
#         - Key: alpha
#           Value: bravo
```

I saw error messages and tried pulling on that thread. It looks like the CloudFormation implementation creates the Activity resource by making a call to the Step Function API endpoint [CreateActivity](https://docs.aws.amazon.com/step-functions/latest/apireference/API_CreateActivity.html) using the request body it got from the CloudFormation template. however, the Step Function API endpoint uses lowercase `"key"` and `"value"` for tags (as opposed to uppercase `"Key"` and `"Value"` like CloudFormation does). So it looks like the issue is that the request format should be transformed between CloudFormation and the Step Function API, but it is not.

**Comment by sigpwned** [comment]
Hi @MarcelStranak, thanks for the suggestion! I commented out the tags as a workaround for now, and that works a treat. I'll try using lowercase key/value and report back.

**Comment by sigpwned** [comment]
I fixed the `LocalStack build git hash` above, which was incorrect. Sorry about that!

**Comment by pinzon** [comment]
The solution of this issue has been merged.
