### ISSUE TITLE
bug: repeated CDK deploy fails with InvalidChangeSetStatus

### ISSUE THREAD

**Issue by simonrw** [localstack/localstack#11333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When 
I run the following commands:
* `cdklocal bootstrap`
* `cdklocal deploy --require-approval never`
* `cdklocal destroy -f`
* `cdklocal
*  deploy --require-approval never` (the same as the second command)

CDK(local) fails to deploy the stack with the following error message:

```
 ❌  CdkStack failed: InvalidChangeSetStatus: ChangeSet [arn:aws:cloudformation:us-east-1:000000000000:changeSet/cdk-deploy-change-set/87846077] cannot be executed in its current status of [CREATE_COMPLETE]
    at Request.extractError (/Users/simon/work/localstack/cdk/node_modules/.pnpm/aws-cdk@2.151.0/node_modules/aws-cdk/lib/index.js:396:46723)
    at Request.callListeners (/Users/simon/work/localstack/cdk/node_modules/.pnpm/aws-cdk@2.151.0/node_modules/aws-cdk/lib/index.js:396:91777)
    at Request.emit (/Users/simon/work/localstack/cdk/node_modules/.pnpm/aws-cdk@2.151.0/node_modules/aws-cdk/lib/index.js:396:91225)
    at Request.emit (/Users/simon/work/localstack/cdk/node_modules/.pnpm/aws-cdk@2.151.0/node_modules/aws-cdk/lib/index.js:396:199828)
    at Request.transition (/Users/simon/work/localstack/cdk/node_modules/.pnpm/aws-cdk@2.151.0/node_modules/aws-cdk/lib/index.js:396:193380)
    at AcceptorStateMachine.runTo (/Users/simon/work/localstack/cdk/node_modules/.pnpm/aws-cdk@2.151.0/node_modules/aws-cdk/lib/index.js:396:158252)
    at /Users/simon/work/localstack/cdk/node_modules/.pnpm/aws-cdk@2.151.0/node_modules/aws-cdk/lib/index.js:396:158582
    at Request.<anonymous> (/Users/simon/work/localstack/cdk/node_modules/.pnpm/aws-cdk@2.151.0/node_modules/aws-cdk/lib/index.js:396:193672)
    at Request.<anonymous> (/Users/simon/work/localstack/cdk/node_modules/.pnpm/aws-cdk@2.151.0/node_modules/aws-cdk/lib/index.js:396:199903)
    at Request.callListeners (/Users/simon/work/localstack/cdk/node_modules/.pnpm/aws-cdk@2.151.0/node_modules/aws-cdk/lib/index.js:396:91945) {
  code: 'InvalidChangeSetStatus',
  time: 2024-08-09T10:41:28.662Z,
  requestId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 970.1237437233376
}
```

This workflow would be very useful when working with CloudFormation as I would not need to restart LocalStack to update my stack, which requires bootstrapping again.

### Expected Behavior

The stack deploys correctly the second time to AWS.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    npx cdk init -l typescript -t app
    npm install --save-dev aws-cdk-local
    npx cdklocal bootstrap
    npx cdklocal deploy --require-approval never
    npx cdklocal destroy -f
    npx cdklocal deploy --require-approval never

### Environment

```markdown
- OS: macOS 14.6
- LocalStack:
  LocalStack version: 3.6.1.dev
  LocalStack build date: 2024-08-09
  LocalStack build git hash: f497a6e66
  LocalStack Docker image sha: localstack/localstack@sha256:61413db7a8b511a99bb1470e78032890c9c21ef68f0814a6f002b6a6908a747c
```

**Comment by lprhodes** [comment]
I'm seeing this exact error with the same steps to reproduce. Using localstack/localstack-pro (latest) via desktop app on macOS.

Specifically I get the issue when adding a vpc to a lambda (but not when the vpc is only added to ssm and secret manager).

**Comment by lprhodes** [comment]
VPC definition:

```
import { Stack } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import {
  Vpc,
  SubnetType,
  IVpc
} from 'aws-cdk-lib/aws-ec2';
import * as path from 'path';

import { BaseStackProps } from '../../base/base-stack-props';

export class VpcStack extends Stack {
  public readonly vpc: IVpc;

  constructor(scope: Construct, id: string, props?: BaseStackProps) {
    super(scope, id, props);

    /**
     * 1) Create a VPC with public, private, and isolated subnets.
     *    Adjust NAT gateways, AZ count, etc. as you see fit.
     */
    this.vpc = new Vpc(this, id, {
      cidr: '10.0.0.0/16',
      maxAzs: props?.environment === 'dev' ? 1 : 2,
      natGateways: 0, // or 0 if you don't need NAT
      subnetConfiguration: [
        {
          name: 'Public',
          subnetType: SubnetType.PUBLIC,
          cidrMask: 24,
        },
        {
          name: 'Private',
          subnetType: SubnetType.PRIVATE_WITH_EGRESS,
          cidrMask: 24,
        },
        {
          name: 'Isolated',
          subnetType: SubnetType.PRIVATE_ISOLATED,
          cidrMask: 24,
        },
      ],
    });
  }
}
```

**Comment by lprhodes** [comment]
Error:

```
❌  DiologVpcDev failed: InvalidChangeSetStatusException: ChangeSet [arn:aws:cloudformation:ap-southeast-2:000000000000:changeSet/cdk-deploy-change-set/a0d226d4] cannot be executed in its current status of [CREATE_COMPLETE]
```

**Comment by chrisella** [comment]
I have the same issue when trying to deploy a CDK stack for a second time, on a completely new clean localstack setup and a trivial CDK stack (just 1 lambda, 1 SQS and a DDB)

**Comment by pinzon** [comment]
Hi @chrisella. could  you open an issue for that problem and provide the CDK code and LocalStack logs?
