### ISSUE TITLE
bug: NetworkInterfaceIds fails to resolve in describeNetworkInterfaces custom resource

### ISSUE THREAD

**Issue by raihan-ste** [localstack/localstack#11373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hey, a common pattern to get the private IP addresses of vpc interface endpoints at deploy-time is to call describeNetworkInterfaces using a custom resource. Localstack's cloudformation is currently throwing an error stating that  `The stack named VpcEndpointTest failed to deploy: CREATE_FAILED (Could not resolve attribute 'NetworkInterfaceIds' on resource 'VpcExecuteApiVpcEndpointDB63D92C'): Could not resolve attribute 'NetworkInterfaceIds' on resource 'VpcExecuteApiVpcEndpointDB63D92C'
`

### Expected Behavior

The expected behavior is for the custom resource to run successfully and return the relevant IP addresses

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start
    cdklocal bootstrap
    cdklocal deploy

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
Using AWS CDK v2

    const vpc = new Vpc(this, 'Vpc', {
      ipAddresses: IpAddresses.cidr('10.0.0.0/16'),
      maxAzs: 2,
      subnetConfiguration: [
        {
          subnetType: SubnetType.PUBLIC,
          name: 'ingress',
          cidrMask: 20
        },
        {
          subnetType: SubnetType.PRIVATE_WITH_EGRESS,
          name: 'egress',
          cidrMask: 20
        },
        {
          subnetType: SubnetType.PRIVATE_ISOLATED,
          name: 'isolated',
          cidrMask: 20
        }
      ]
    });

    const securityGroup = new SecurityGroup(
      this,
      `InterfaceEndpointSecurityGroup`,
      { vpc }
    );
    securityGroup.addIngressRule(Peer.ipv4(vpc.vpcCidrBlock), Port.tcp(443));

    const gatewayVpcEndpoint = vpc.addInterfaceEndpoint(
      `ExecuteApiVpcEndpoint`,
      {
        service: InterfaceVpcEndpointAwsService.APIGATEWAY,
        securityGroups: [securityGroup],
        subnets: vpc.selectSubnets({
          subnetType: SubnetType.PRIVATE_ISOLATED
        })
      }
    );

    const eni = new AwsCustomResource(this, 'DescribeNetworkInterfaces', {
      onUpdate: {
        service: 'EC2',
        action: 'describeNetworkInterfaces',
        outputPaths: [
          `NetworkInterfaces.0.PrivateIpAddress`,
          `NetworkInterfaces.1.PrivateIpAddress`
        ],
        parameters: {
          NetworkInterfaceIds: gatewayVpcEndpoint.vpcEndpointNetworkInterfaceIds
        },
        physicalResourceId: PhysicalResourceId.of(Math.random().toString())
      },
      policy: {
        statements: [
          new PolicyStatement({
            actions: ['ec2:DescribeNetworkInterfaces'],
            resources: ['*']
          })
        ]
      }
    });

    const ip1 = eni.getResponseField('NetworkInterfaces.0.PrivateIpAddress');
    const ip2 = eni.getResponseField('NetworkInterfaces.1.PrivateIpAddress');
    // use ips as targets for a load balancer, etc...

### Environment

```markdown
- OS: Windows 11/Ubuntu 22 WSL
- LocalStack:
  LocalStack version: 3.6.1.dev20240812032244
  LocalStack build date: 2024-08-12
  LocalStack build git hash: 2632325
```

### Anything else?

After enabling debug logs, this is whats reported by locastack:

```
2024-08-17 19:49:15 2024-08-17T23:49:15.773 DEBUG --- [functhread52] l.s.c.e.template_deployer  : Error applying changes for CloudFormation stack "VpcEndpointTest": Could not resolve attribute 'NetworkInterfaceIds' on resource 'VpcExecuteApiVpcEndpointDB63D92C' Traceback (most recent call last):
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1130, in _run
2024-08-17 19:49:15     self.do_apply_changes_in_loop(changes, stack)
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1420, in do_apply_changes_in_loop
2024-08-17 19:49:15     should_deploy = self.prepare_should_deploy_change(
2024-08-17 19:49:15                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1173, in prepare_should_deploy_change
2024-08-17 19:49:15     resolve_refs_recursively(
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/cloudformation/cloudformation_extended.py.enc", line 13, in resolve_refs_recursively
2024-08-17 19:49:15     G='name';B=resolve_refs_recursively_orig(*H,**I)
2024-08-17 19:49:15                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/functions.py", line 81, in func
2024-08-17 19:49:15     return wrapped(*args, **kwargs)
2024-08-17 19:49:15            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 199, in resolve_refs_recursively
2024-08-17 19:49:15     result = _resolve_refs_recursively(
2024-08-17 19:49:15              ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/functions.py", line 81, in func
2024-08-17 19:49:15     return wrapped(*args, **kwargs)
2024-08-17 19:49:15            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 661, in _resolve_refs_recursively
2024-08-17 19:49:15     value[key] = resolve_refs_recursively(
2024-08-17 19:49:15                  ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/cloudformation/cloudformation_extended.py.enc", line 13, in resolve_refs_recursively
2024-08-17 19:49:15     G='name';B=resolve_refs_recursively_orig(*H,**I)
2024-08-17 19:49:15                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/functions.py", line 81, in func
2024-08-17 19:49:15     return wrapped(*args, **kwargs)
2024-08-17 19:49:15            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 199, in resolve_refs_recursively
2024-08-17 19:49:15     result = _resolve_refs_recursively(
2024-08-17 19:49:15              ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/functions.py", line 81, in func
2024-08-17 19:49:15     return wrapped(*args, **kwargs)
2024-08-17 19:49:15            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 661, in _resolve_refs_recursively
2024-08-17 19:49:15     value[key] = resolve_refs_recursively(
2024-08-17 19:49:15                  ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/cloudformation/cloudformation_extended.py.enc", line 13, in resolve_refs_recursively
2024-08-17 19:49:15     G='name';B=resolve_refs_recursively_orig(*H,**I)
2024-08-17 19:49:15                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/functions.py", line 81, in func
2024-08-17 19:49:15     return wrapped(*args, **kwargs)
2024-08-17 19:49:15            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 199, in resolve_refs_recursively
2024-08-17 19:49:15     result = _resolve_refs_recursively(
2024-08-17 19:49:15              ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/functions.py", line 81, in func
2024-08-17 19:49:15     return wrapped(*args, **kwargs)
2024-08-17 19:49:15            ^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-17 19:49:15   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 344, in _resolve_refs_recursively
2024-08-17 19:49:15     raise DependencyNotYetSatisfied(
2024-08-17 19:49:15 localstack.services.cloudformation.service_models.DependencyNotYetSatisfied: Could not resolve attribute 'NetworkInterfaceIds' on resource 'VpcExecuteApiVpcEndpointDB63D92C'
2024-08-17 19:49:15 
2024-08-17 19:49:15 2024-08-17T23:49:15.773  WARN --- [functhread52] l.s.c.engine.entities      : CFn resource failed to deploy: CdkJsonStringify1 (Could not resolve attribute 'NetworkInterfaceIds' on resource 'VpcExecuteApiVpcEndpointDB63D92C')
```

**Comment by pinzon** [comment]
Thank you for reporting the issue. The solution has been merged recently and should be available in later docker images.
