### ISSUE TITLE
bug: Can't create a CloudWatch Alarm with a colon `:` in the name

### ISSUE THREAD

**Issue by cj-christoph-gysin** [localstack/localstack#11391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to create a CloudWatch Alarm with a colon `:` in the name:
```
$ awslocal cloudwatch put-metric-alarm --alarm-name "foo:bar" --evaluation-periods 1 --comparison-operator GreaterThanThreshold
```
 fails with:
```
localstack  | Traceback (most recent call last):
localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
localstack  |     handler(self, self.context, response)
localstack  |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 113, in __call__
localstack  |     handler(chain, context, response)
localstack  |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 83, in __call__
localstack  |     skeleton_response = self.skeleton.invoke(context)
localstack  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 154, in invoke
localstack  |     return self.dispatch_request(serializer, context, instance)
localstack  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 168, in dispatch_request
localstack  |     result = handler(context, instance) or {}
localstack  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack  |   File "/opt/code/localstack/localstack/aws/forwarder.py", line 136, in _call
localstack  |     return handler(context, req)
localstack  |            ^^^^^^^^^^^^^^^^^^^^^
localstack  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 118, in __call__
localstack  |     return self.fn(*args, **kwargs)
localstack  |            ^^^^^^^^^^^^^^^^^^^^^^^^
localstack  |   File "/opt/code/localstack/localstack/aws/api/core.py", line 161, in operation_marker
localstack  |     return fn(*args, **kwargs)
localstack  |            ^^^^^^^^^^^^^^^^^^^
localstack  |   File "/opt/code/localstack/localstack/services/cloudwatch/provider.py", line 454, in put_metric_alarm
localstack  |     self.alarm_scheduler.schedule_metric_alarm(arn)
localstack  |   File "/opt/code/localstack/localstack/services/cloudwatch/alarm_scheduler.py", line 55, in schedule_metric_alarm
localstack  |     alarm_details = get_metric_alarm_details_for_alarm_arn(alarm_arn)
localstack  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack  |   File "/opt/code/localstack/localstack/services/cloudwatch/alarm_scheduler.py", line 122, in get_metric_alarm_details_for_alarm_arn
localstack  |     alarm_name = arns.extract_resource_from_arn(alarm_arn).split(":", 1)[1]
localstack  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack  | AttributeError: 'NoneType' object has no attribute 'split'
```

### Expected Behavior

The Alarm is created.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    $ docker run -eDEBUG=1 -p4566:4566 localstack/localstack:3.6

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    $ awslocal cloudwatch put-metric-alarm --alarm-name "foo:bar" --evaluation-periods 1 --comparison-operator GreaterThanThreshold

### Environment

```markdown
- OS: macOS
- LocalStack: 
LocalStack version: 3.6.0
LocalStack build date: 2024-07-25
LocalStack build git hash: 5c077c795
```

### Anything else?

This seems to be caused by `_resource_arn()` assuming that a name with a colon is an ARN:

https://github.com/localstack/localstack/blob/master/localstack-core/localstack/utils/aws/arns.py#L522
```
def _resource_arn(name: str, pattern: str, account_id: str, region_name: str) -> str:
    if ":" in name:
        return name
```

and could be fixed by checking for the ARN prefix instead:
```diff
-    if ":" in name:
+    if name.startswith('arn:'):

**Comment by cj-christoph-gysin** [comment]
FYI: A similar check is performed here:
https://github.com/localstack/localstack/blob/master/localstack-core/localstack/utils/aws/arns.py#L522
```
def lambda_function_name(name_or_arn: str) -> str:
    if ":" in name_or_arn:
```

**Comment by steffyP** [comment]
Hi @cj-christoph-gysin,
thanks for reporting, we provided a fix for your issue. It's already available in `latest` for the community image (for pro it should be available a bit later).
