### ISSUE TITLE
bug: TypeError: argument of type 'ReplicationGroupConfiguration' is not iterable

### ISSUE THREAD

**Issue by cwells** [localstack/localstack#11447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to create a Redis cluster using `tflocal` results in the following:

```
2024-09-02T21:55:53.102 ERROR --- [et.reactor-0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 113, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 83, in __call__
    skeleton_response = self.skeleton.invoke(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(serializer, context, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request
    result = handler(context, instance) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/api/core.py", line 160, in operation_marker
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/elasticache/provider.py.enc", line 87, in create_cache_cluster
    if A.get(_E):B=D._create_cache_cluster_in_replication_group(E,A)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/elasticache/provider.py.enc", line 95, in _create_cache_cluster_in_replication_group
    if A not in C[A]:raise ReplicationGroupNotFoundFault(f"Replication group '{A}' not found")
       ^^^^^^^^^^^^^
TypeError: argument of type 'ReplicationGroupConfiguration' is not iterable
2024-09-02T21:55:53.104  INFO --- [et.reactor-0] localstack.request.aws     : AWS elasticache.CreateCacheCluster => 500 (InternalError)
```

### Expected Behavior

A Redis cluster is deployed.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    LOCALSTACK_AUTH_TOKEN="xxx" DEBUG=1 localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Terraform:

```
resource "aws_security_group" "redis" {
  vpc_id = module.vpc.vpc_id
  name   = "agent-cache"

  ingress {
    from_port       = "6379"
    to_port         = "6379"
    protocol        = "tcp"
    security_groups = [ aws_security_group.agent_cluster.id ]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_elasticache_subnet_group" "redis" {
  name       = "agent-cache"
  subnet_ids = module.vpc.private_subnets
}

resource "aws_elasticache_replication_group" "redis" {
  description                   = "agent cache"
  engine                        = "redis"
  engine_version                = "7.1"
  node_type                     = "cache.t3.micro"
  parameter_group_name          = "default.redis7"
  automatic_failover_enabled    = true
  preferred_cache_cluster_azs   = [ "${var.aws_region}a", "${var.aws_region}b" ]
  replication_group_id          = "agent-cache"
  num_cache_clusters            = 2
  security_group_ids            = [ aws_security_group.redis.id ]
  subnet_group_name             = aws_elasticache_subnet_group.redis.name

  lifecycle {
    ignore_changes = [ num_cache_clusters ]
  }
}

resource "aws_elasticache_cluster" "redis" {
  cluster_id           = "agent-cache"
  replication_group_id = aws_elasticache_replication_group.redis.id
}
```

### Environment

```markdown
- OS: Fedora 40 kernel 6.10
- LocalStack:
  LocalStack version: 3.6.0
  LocalStack Docker image sha: 911eb76990b3841bbb0932fc304f553182b6c414fbd8c05f5e6f016802215835
```

**Comment by cwells** [comment]
`if A not in C[A]:` seems unlikely to be the intended condition.

**Comment by bentsku** [comment]
Hello @cwells and thanks for your report!

You're right, the condition is wrong, I just had a look at it. However, if this condition was working, the next step is raising this exception:
`NotImplementedError("Creating a new cache cluster in an existing replication group is currently not supported")`

I'll still open a PR to fix this particular issue you've been encountering, but if you need that feature implemented, could you please open a feature request on GitHub describing your use case? 

Thank you!

**Comment by cwells** [comment]
> I'll still open a PR to fix this particular issue you've been encountering, but if you need that feature implemented, could you please open a feature request on GitHub describing your use case, and maybe reach out to our Pro support?

Thanks for looking into this. I've worked around the issue for the time being by not utilizing the replication group. I won't need this for testing anyway.

**Comment by bentsku** [comment]
Awesome, thanks for the feedback! The particular issue you've been encountering has been resolved in the `latest` image, this error should not be raised anymore. Thanks a lot for the trace, it was very helpful to reproduce. 

Should we close the issue? Do you want to quickly validate that the fix is indeed working for you? 

Thanks!

**Comment by cwells** [comment]
I can confirm I now get

`InternalFailure: Creating a new cache cluster in an existing replication group is currently not supported`

Closing, thanks for the help.
