### ISSUE TITLE
bug: RDS IAM Authentication via aws-sdk-go-v2 causes the PostgreSQL proxy to quit

### ISSUE THREAD

**Issue by ammar-elsabe** [localstack/localstack#11507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The aws-sdk-go-v2 generates the authentication token without a trailing `/` before the query string delimiter `?`:
```
localhost.localstack.cloud:4510?Action=connect&DBUser=auth_service&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=fake%2F20240912%2Fus-east-1%2Frds-db%2Faws4_request&X-Amz-Date=20240912T190910Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=f14f671c0072a48aa5d9e47a192ff8ec43ccbad75853a15933c5a2368b8803b6
```

This causes the regex in the proxy to ~~commit suicide~~ not find a match when trying to extract the port:

```
localstack-1     | 2024-09-12T19:09:10.843 ERROR --- [    Thread-9] postgresql_proxy           : PostgreSQL proxy quit unexpectedly:
localstack-1     | Traceback (most recent call last):
localstack-1     |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/postgresql_proxy/proxy.py", line 223, in listen
localstack-1     |     self.service_connection(key, mask)
localstack-1     |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/postgresql_proxy/proxy.py", line 170, in service_connection
localstack-1     |     conn.received(recv_data)
localstack-1     |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/postgresql_proxy/connection.py", line 51, in received
localstack-1     |     self.process_inbound_packet(header, body)
localstack-1     |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/postgresql_proxy/connection.py", line 58, in process_inbound_packet
localstack-1     |     body = self.interceptor.intercept(packet_type, body)
localstack-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-1     |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/patch.py", line 61, in proxy
localstack-1     |     return new(target, *args, **kwargs)
localstack-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-1     |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/utils/postgresql.py.enc", line 185, in B
localstack-1     |     C=E(A)
localstack-1     |       ^^^^
localstack-1     |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/rds/engine_postgres.py.enc", line 163, in lookup_user_password_for_iam_auth_token
localstack-1     |     B=token;E=re.match('.+DBUser=([^&]+)',B).group(1);C=int(re.match('.+:([0-9]{1,5})/',B).group(1));D=get_server_details_for_port(C)
localstack-1     |                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-1     | AttributeError: 'NoneType' object has no attribute 'group'
```

### Expected Behavior

Regex should not mandate the trailing slash, ex. [`'.+:([0-9]{1,5})(/?)\?'`](https://regex101.com/r/mDBSVm/2)

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Create an RDS PostgreSQL instance within localstack
2. Create a Postgres user and assign them the `rds_iam` role
```sql
CREATE USER 'test_user' WITH LOGIN;
GRANT 'rds_iam' TO 'test_user';
```
3. Request a password with the aws-sdk-go-v2
```go

	awsCfg, err := config.LoadDefaultConfig(
		ctx,
		config.WithEndpointResolverWithOptions(
			aws.EndpointResolverWithOptionsFunc(
				func(service, region string, options ...interface{}) (aws.Endpoint, error) {
					return aws.Endpoint{
						URL: "http://localhost.localstack.cloud:4566",
					}, nil
				},
			),
		),
	)
	if err != nil {
		panic(err)
	}
        port := 4510 // localstack default but may vary
        endpoint := fmt.Sprintf("localhost.localstack.cloud:%d", port)
        authToken, err := auth.BuildAuthToken(ctx, endpoint, region, user, awsCfg.Credentials)
        if err != nil {
	        panic(err)
        }
        user := "test_user"
        dbname := "postgres"
        dsn := fmt.Sprintf("host=localhost.localstack.cloud port=%d user=%s password=%s sslmode=disable dbname=%s", port, user, authToken, dbname)
        db, err := sqlx.Connect("postgres", dsn)
	if err != nil {
		panic(err) /// panics
	}
```

### Environment

```markdown
- OS: Fedora 39
- LocalStack:
  LocalStack version: 3.7.3.dev14
  LocalStack Docker image sha: "RepoDigests": [
            "localstack/localstack-pro@sha256:0d105b3dc1d764d8a47e6260e98eef6ce25a4e874be10287edf877fe3361e868"
        ],
  LocalStack build date: 2024-09-12
  LocalStack build git hash: 457a4875
```

### Anything else?

[IAM DB Authentication in Golang](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.Go.html)

**Comment by sno6** [comment]
Hey folks, just noting that another person (me) has ran into this issue and would love for it to be fixed :)

**Comment by sno6** [comment]
For anyone else that comes across this issue, I had to

1. Update my token in code to add a slash after the port e.g `localhost.localstack.cloud:4510?...` -> `localhost.localstack.cloud:4510/?...`
2. Grant `rds_iam` as defined in the [docs](https://docs.localstack.cloud/user-guide/aws/rds/#iam-authentication-support)

**Comment by jem-davies** [comment]
I tried the workaround of adding a \? instead of ? but still seeing:

```
2025-03-24 12:18:57 Traceback (most recent call last):
2025-03-24 12:18:57   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/postgresql_proxy/proxy.py", line 223, in listen
2025-03-24 12:18:57     self.service_connection(key, mask)
2025-03-24 12:18:57   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/postgresql_proxy/proxy.py", line 170, in service_connection
2025-03-24 12:18:57     conn.received(recv_data)
2025-03-24 12:18:57   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/postgresql_proxy/connection.py", line 51, in received
2025-03-24 12:18:57     self.process_inbound_packet(header, body)
2025-03-24 12:18:57   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/postgresql_proxy/connection.py", line 58, in process_inbound_packet
2025-03-24 12:18:57     body = self.interceptor.intercept(packet_type, body)
2025-03-24 12:18:57            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-24 12:18:57   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/patch.py", line 61, in proxy
2025-03-24 12:18:57     return new(target, *args, **kwargs)
2025-03-24 12:18:57            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-24 12:18:57   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/utils/postgresql.py.enc", line 185, in B
2025-03-24 12:18:57     C=E(A)
2025-03-24 12:18:57       ^^^^
2025-03-24 12:18:57   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/rds/engine_postgres.py.enc", line 167, in lookup_user_password_for_iam_auth_token
2025-03-24 12:18:57     B=token;E=re.match('.+DBUser=([^&]+)',B).group(1);C=int(re.match('.+:([0-9]{1,5})/',B).group(1));D=get_server_details_for_port(C)
2025-03-24 12:18:57                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-24 12:18:57 AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by cloutierMat** [comment]
Thank you @ammar-elsabe and @sno6, for reporting this issue.

I can confirm there is an issue in the rds implementation in LocalStack. I will be working on a fix shortly and update here once I have a fix merged.

**Comment by cloutierMat** [comment]
Thank you all again for your reports and patience as we resolved the issue. The fix is currently has been merged and is part of the 4.3.0 release. Please pull the newer image and try it out.

I will close this issue for now, but feel free to reopen if the problem persist.

**Comment by jem-davies** [comment]
> Thank you all again for your reports and patience as we resolved the issue. The fix is currently has been merged and is part of the 4.3.0 release. Please pull the newer image and try it out.
> 
> I will close this issue for now, but feel free to reopen if the problem persist.

Hey that's great - it's fixed on my integration test!
