### ISSUE TITLE
bug: IoT connection refused over WSS

### ISSUE THREAD

**Issue by Jeff-Cortese** [localstack/localstack#11515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading to `localstack-pro:3.7.0` docker image, I am not able to connect to IoT over WSS. The localstack container shows the following error
```
2024-09-13T22:19:14.157  INFO --- [uncthread392] localstack.utils.threads   : Thread run method <function MultiplexingServer.do_run.<locals>.<lambda> at 0x7f124858cd60>(None) failed: [Errno 111] Connection refused Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/threads.py", line 60, in run
    result = self.func(self.params, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/utils/multiplexing.py.enc", line 39, in <lambda>
    try:D,F=A.accept();start_worker_thread(lambda*A,_thread:C(D,_thread))
                                                            ^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/utils/multiplexing.py.enc", line 34, in C
    if not E:E=A.destination_selector(D);B.connect(E);G.append(B)
                                         ^^^^^^^^^^^^
ConnectionRefusedError: [Errno 111] Connection refused

2024-09-13T22:19:14.157 DEBUG --- [uncthread392] localstack.utils.threads   : FINISHED: <Future at 0x7f13043d0e50 state=finished raised ConnectionRefusedError>

```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I am attempting to connect via the aws iot client library [aws-iot-device-sdk:2.2.6](https://github.com/aws/aws-iot-device-sdk-js)

Here is a sample request that results in a connection reset error in firefox:
![image](https://github.com/user-attachments/assets/379eaa03-ba26-43e6-9296-a86df10cd3a0)
```
GET /mqtt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=LSIAQAAAAAAACKUC7ECA%2F20240913%2Fus-west-2%2Fiotdevicegateway%2Faws4_request&X-Amz-Date=20240913T223109Z&X-Amz-SignedHeaders=host&X-Amz-Signature=redacted&X-Amz-Security-Token=redacted undefined
Host: 000000000000.iot.us-west-2.localhost.localstack.cloud:4510
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br, zstd
Sec-WebSocket-Version: 13
Origin: http://localhost:4200
Sec-WebSocket-Protocol: mqttv3.1
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: gDrgWi1PRIvX4TKhwNTocA==
Connection: keep-alive, Upgrade
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: websocket
Sec-Fetch-Site: cross-site
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
```

Note: I have ensured that I imported the latest IoT cert at http://localhost.localstack.cloud:4566/_aws/iot/LocalStackIoTRootCA.pem into my browser's cert manager authorities.

I have also tried connecting via nodejs clients instead of from the browser with the same results.

### Environment

```markdown
- OS: Ubuntu:22:04
- LocalStack:
  LocalStack version: 3.7.1.dev1
  LocalStack Docker image sha: sha256:4efa49cbb948a802c3dc02964ba50d964950ee20e52910d1f822e3081b9b8eb8
  LocalStack build date: 2024-08-29
  LocalStack build git hash: a8555a9d
```

**Comment by viren-nadkarni** [comment]
Hi @Jeff-Cortese, which version of LocalStack did you upgrade from? This information will help me track down the bug.

**Comment by Jeff-Cortese** [comment]
I was previously using
```
LocalStack version: 3.0.3.dev20240115121347
LocalStack build date: 2024-01-19
LocalStack build git hash: 1b98d3e
Localstack-pro container sha: @sha256:287f0293eaf871cabcc275a223790bc397abb11913c123e53474f0c4e159760f
```

**Comment by viren-nadkarni** [comment]
We've pushed a fix that resolves this, please try the latest image. Thanks for the report
