### ISSUE TITLE
bug: ECS SSM param env var with a leading slash fails

### ISSUE THREAD

**Issue by arshsingh** [localstack/localstack#11538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an ECS task has an env var with the value stored in an SSM param whose name starts with a `/` (for e.g. `/test/some-config`), starting the task fails with the following error:

```
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the GetParameter operation: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
```

Checking the request logs, it looks like GetParameter is called without the leading slash:
```
{
  "Name": "test/some-config",
  "WithDecryption": true
}
```

### Expected Behavior

ECS should try to get the param `/test/some-config` not `test/some-config`

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

- create an SSM param `/test/some-config`
- create an ECS service and add this ssm param as an env var to the container
- deploying the service fails

### Environment

```markdown
- OS: Mac OS 14
- LocalStack:
  LocalStack version: 3.7.2
  LocalStack Docker image sha: sha256:6121fe59d0c05ccc30bee5d4f24fce23c3e3148a4438551982a5bf60657a9e8d
  LocalStack build date: 2024-09-06
  LocalStack build git hash: 854016a0
```

### Anything else?

I also see this in the logs:

```
 File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/ecs/secrets_resolver.py.enc", line 24, in resolve_secrets
    if':ssm:'in B:O=B.split(':parameter/')[1];A=N.get_parameter(Name=O,WithDecryption=True)['Parameter']['Value']
```

Which looks like could be the issue since it is splitting the arn by `:parameter/` to get the name of the SSM param. Example SSM param from my aws account (real account, not localstack):

```
Name: /cdk-bootstrap/.../version
ARN: arn:aws:ssm:us-east-1:...:parameter/cdk-bootstrap/.../version

**Comment by awkaplan** [comment]
I am seeing this as well:

```
│   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
│     handler(self, self.context, response)
│   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 113, in __call__
│     handler(chain, context, response)
│   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 83, in __call__
│     skeleton_response = self.skeleton.invoke(context)
│                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
│     return self.dispatch_request(serializer, context, instance)
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request
│     result = handler(context, instance) or {}
│              ^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
│     return self.fn(*args, **kwargs)
│            ^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/ecs/provider.py.enc", line 280, in run_task
│   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/ecs/task_executors/docker.py.enc", line 37, in run_task
│     for b in t.resolve_secrets(a):C[b[V]]=b[p]
│   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/ecs/secrets_resolver.py.enc", line 24, in resolve_secrets
│     if':ssm:'in B:O=B.split(':parameter/')[1];A=N.get_parameter(Name=O,WithDecryption=True)['Parameter']['Value']
│                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 569, in _api_call
│     return self._make_api_call(operation_name, kwargs)
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 1023, in _make_api_call
│     raise error_class(parsed_response, operation_name)
│ botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the GetParameter operation: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
```

**Comment by pflueg** [comment]
another +1 from my side. 

When using "some-config" without any path prefix it works. Otherwise starting a task fails:

```
2024-12-02T12:09:23.685 DEBUG --- [et.reactor-4] l.p.c.s.ecs.provider       : Running ECS task 'arn:aws:ecs:eu-central-1:000000000000:task-definition/fun_stuff:1' through create service action                                                        
2024-12-02T12:09:23.710 ERROR --- [et.reactor-0] l.aws.handlers.logging     : exception during call chain                                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                                                                                            
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle                                                                                                                                                   
    handler(self, self.context, response)                                                                                                                                                                                                                     
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 113, in __call__                                                                                                                                    
    handler(chain, context, response)                                                                                                                                                                                                                         
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 83, in __call__                                                                                                                                     
    skeleton_response = self.skeleton.invoke(context)                                                                                                                                                                                                         
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                         
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke                                                                                                                                              
    return self.dispatch_request(serializer, context, instance)                                                                                                                                                                                               
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                               
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request                                                                                                                                    
    result = handler(context, instance) or {}                                                                                                                                                                                                                 
             ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                       
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__                                                                                                                                            
    return self.fn(*args, **kwargs)                                                                                                                                                                                                                           
           ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                           
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/ecs/provider.py.enc", line 280, in run_task                                                                                                                      
    for B in G:C.task_executor.run_task(B)                                                                                                                                                                                                                    
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                     
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/ecs/task_executors/docker.py.enc", line 37, in run_task
    for b in t.resolve_secrets(a):C[b[V]]=b[p]                                                                                 
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/ecs/secrets_resolver.py.enc", line 24, in resolve_secrets
    if':ssm:'in B:O=B.split(':parameter/')[1];A=N.get_parameter(Name=O,WithDecryption=True)['Parameter']['Value']
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)                                                                         
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                         
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)                                                                         
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the GetParameter operation: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash
 symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
```

**Comment by dfangl** [comment]
Hi @arshsingh @pflueg !
This issue should now be resolved in the latest `localstack/localstack-pro:latest` image. Could you please verify this update fixes the issue for you?

Thank you for reporting this issue!

**Comment by pflueg** [comment]
@dfangl : I am able to add the parameter "/test/parameter" - thanks!
fyi: When naming the parameter "test/parameter" (without the leading slash) the following error occurs:

> aws_ssm_parameter.example: Refreshing state... [id=test/some-config]
> ╷
> │ Error: reading SSM Parameter (test/some-config): operation error SSM: GetParameter, https response error StatusCode: 400, RequestID: 89f64eac-f3ce-49e7-b76f-730c9831d445, api error ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_

You might want to add to the message, that a parameter name must begin with a slash, when forming a path, as described here in the "--path" query: https://docs.aws.amazon.com/cli/latest/reference/ssm/get-parameters-by-path.html#options

Thanks!

**Comment by dfangl** [comment]
Hi @pflueg ! 
This error message is on parity with AWS, and even though I agree more information would be helpful, we try to get parity with AWS also for those messages.
I will close this issue now, as it has been fixed, but thank you for the suggestion!
