### ISSUE TITLE
bug: cannot list secrets - API or object browser

### ISSUE THREAD

**Issue by arylwen** [localstack/localstack#11541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

2024-09-18 17:06:32 2024-09-19T00:06:32.212  INFO --- [t.reactor-30] localstack.request.aws     : AWS secretsmanager.ListSecrets => 500 (InternalError); 000000000000/us-east-1; ListSecretsRequest({}, headers={'Host': 'localhost:4566', 'Accept-Encoding': 'identity', 'X-Amz-Target': 'secretsmanager.ListSecrets', 'Content-Type': 'application/x-amz-json-1.1', 'User-Agent': 'Boto3/1.35.14 md/Botocore#1.35.14 ua/2.0 os/linux#5.15.153.1-microsoft-standard-WSL2 md/arch#x86_64 lang/python#3.10.14 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.35.14', 'X-Amz-Date': '20240919T000632Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=accesskey/20240919/us-east-1/secretsmanager/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=b9fdaef178c41d358212d0bf954ab5477b48ef76330bd5c6945000309475a04c', 'amz-sdk-invocation-id': 'e50fd90b-ca4f-44ed-b324-0aace833a00e', 'amz-sdk-request': 'ttl=20240919T000727Z; attempt=5; max=5', 'Content-Length': '2', 'x-moto-account-id': '000000000000'}); InternalError(exception while calling secretsmanager.ListSecrets: Traceback (most recent call last):
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
2024-09-18 17:06:32     handler(self, self.context, response)
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 113, in __call__
2024-09-18 17:06:32     handler(chain, context, response)
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 83, in __call__
2024-09-18 17:06:32     skeleton_response = self.skeleton.invoke(context)
2024-09-18 17:06:32                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
2024-09-18 17:06:32     return self.dispatch_request(serializer, context, instance)
2024-09-18 17:06:32            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request
2024-09-18 17:06:32     result = handler(context, instance) or {}
2024-09-18 17:06:32              ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/forwarder.py", line 140, in _call
2024-09-18 17:06:32     return fallthrough_handler(context, req)
2024-09-18 17:06:32            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/moto.py", line 87, in _proxy_moto
2024-09-18 17:06:32     return call_moto(context)
2024-09-18 17:06:32            ^^^^^^^^^^^^^^^^^^
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/moto.py", line 48, in call_moto
2024-09-18 17:06:32     return dispatch_to_backend(context, dispatch_to_moto, include_response_metadata)
2024-09-18 17:06:32            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/forwarder.py", line 185, in dispatch_to_backend
2024-09-18 17:06:32     http_response = http_request_dispatcher(context)
2024-09-18 17:06:32                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/moto.py", line 118, in dispatch_to_moto
2024-09-18 17:06:32     response = dispatch(request, raw_url, request.headers)
2024-09-18 17:06:32                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/core/responses.py", line 290, in dispatch
2024-09-18 17:06:32     return cls()._dispatch(*args, **kwargs)
2024-09-18 17:06:32            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/core/responses.py", line 502, in _dispatch
2024-09-18 17:06:32     return self.call_action()
2024-09-18 17:06:32            ^^^^^^^^^^^^^^^^^^
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/core/responses.py", line 588, in call_action
2024-09-18 17:06:32     response = method()
2024-09-18 17:06:32                ^^^^^^^^
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/secretsmanager/responses.py", line 178, in list_secrets
2024-09-18 17:06:32     secret_list, next_token = self.backend.list_secrets(
2024-09-18 17:06:32                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/secretsmanager/models.py", line 908, in list_secrets
2024-09-18 17:06:32     secret_list.append(secret.to_dict())
2024-09-18 17:06:32                        ^^^^^^^^^^^^^^^^
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/patch.py", line 61, in proxy
2024-09-18 17:06:32     return new(target, *args, **kwargs)
2024-09-18 17:06:32            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-18 17:06:32   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/secretsmanager/provider.py", line 546, in fake_secret_to_dict
2024-09-18 17:06:32     if self.last_accessed_date:
2024-09-18 17:06:32        ^^^^^^^^^^^^^^^^^^^^^^^
2024-09-18 17:06:32 AttributeError: 'FakeSecret' object has no attribute 'last_accessed_date'

### Expected Behavior

Object Browser displays a list of secrets or none

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

### Environment

```markdown
- OS:
- LocalStack:
  LocalStack version: 3.7.3.dev28
  LocalStack Docker image sha:
  LocalStack build date:
  LocalStack build git hash:
```

**Comment by alexrashed** [comment]
Hi @arylwen!
I just tried to reproduce this issue but was not successful. I think this might have already been resolved?
Would you mind trying this with the latest version of LocalStack?
If the issue is still reproducible, could you please explicitly mention the set of commands you used to reproduce the issue?
Thanks!
