### ISSUE TITLE
bug: API Gateway could not resolve models

### ISSUE THREAD

**Issue by InvokedLambda** [localstack/localstack#11755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I do a post request to a rest resource of an API Gateway with a request validator, the reference model could not be resolved. I think this worked in the past, but I could not specify any version because I haven't run my local development env for a long time. But I can say it works on the aws cloud.

Error message:
```
2024-10-28T16:35:57.992 ERROR --- [t.reactor-11] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.11/http/client.py", line 1303, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1349, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1058, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 996, in send
    self.connect()
  File "/usr/local/lib/python3.11/http/client.py", line 1468, in connect
    super().connect()
  File "/usr/local/lib/python3.11/http/client.py", line 962, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 863, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 848, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/referencing/_core.py", line 423, in get_or_retrieve
    resource = registry._retrieve(uri)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 113, in _warn_for_remote_retrieve
    with urlopen(request) as response:  # noqa: S310
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/referencing/_core.py", line 672, in lookup
    retrieved = self._registry.get_or_retrieve(uri)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/referencing/_core.py", line 430, in get_or_retrieve
    raise exceptions.Unretrievable(ref=uri) from error
referencing.exceptions.Unretrievable: 'https://apigateway.amazonaws.com/restapis/ihc1got0cn/models/BenutzerModel'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 463, in _validate_reference
    resolved = self._resolver.lookup(ref)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/referencing/_core.py", line 676, in lookup
    raise exceptions.Unresolvable(ref=ref) from error
referencing.exceptions.Unresolvable: https://apigateway.amazonaws.com/restapis/ihc1got0cn/models/BenutzerModel
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/handlers.py", line 27, in __call__
    router_response = self.router.dispatch(context.request)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/routing/router.py", line 326, in dispatch
    return self.dispatcher(request, handler, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/routing/handler.py", line 64, in __call__
    result = self.invoke_endpoint(request, endpoint, request_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/routing/pydantic.py", line 82, in invoke_endpoint
    return super().invoke_endpoint(request, endpoint, request_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/routing/handler.py", line 73, in invoke_endpoint
    return endpoint(request, **request_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/apigateway/legacy/router_asf.py.enc", line 31, in invoke_rest_api
    try:G=invoke_api(A);return convert_response(G)
          ^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/apigateway/legacy/integrations.py.enc", line 118, in invoke_api
    return invoke_rest_api(A)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/apigateway/legacy/invocations.py", line 287, in invoke_rest_api
    validator.validate_request()
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/apigateway/legacy/invocations.py", line 122, in validate_request
    if self.should_validate_body(validator) and not self._is_body_valid(resource):
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/apigateway/legacy/invocations.py", line 152, in _is_body_valid
    validate(
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 1330, in validate
    error = exceptions.best_match(validator.iter_errors(instance))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/exceptions.py", line 478, in best_match
    best = max(itertools.chain([best], errors), key=key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 384, in iter_errors
    for error in errors:
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/_keywords.py", line 296, in properties
    yield from validator.descend(
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 432, in descend
    for error in errors:
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/_keywords.py", line 355, in oneOf
    errs = list(validator.descend(instance, subschema, schema_path=index))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 432, in descend
    for error in errors:
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/_keywords.py", line 275, in ref
    yield from validator._validate_reference(ref=ref, instance=instance)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 465, in _validate_reference
    raise exceptions._WrappedReferencingError(err) from err
jsonschema.exceptions._WrappedReferencingError: Unresolvable: https://apigateway.amazonaws.com/restapis/ihc1got0cn/models/StatusModel
```

It could not resolve the referenced model although I see this localstack logs:
```
2024-10-28T16:28:50.973 DEBUG --- [  MainThread] localstack.dns.server      : Determined fallback dns: 127.0.0.11
2024-10-28T16:28:50.973 DEBUG --- [  MainThread] localstack.dns.server      : Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
2024-10-28T16:28:50.973 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*localhost.localstack.cloud pointing to LocalStack
2024-10-28T16:28:50.973 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*localhost.localstack.cloud with record DynamicRecord(record_type=<RecordType.A: 1>, record_id=None)
2024-10-28T16:28:50.973 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*localhost.localstack.cloud with record DynamicRecord(record_type=<RecordType.AAAA: 2>, record_id=None)
2024-10-28T16:28:50.974 DEBUG --- [-functhread1] localstack.dns.server      : DNS Server started
2024-10-28T16:28:50.977 DEBUG --- [  MainThread] localstack.dns.server      : DNS server startup finished.
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] l.pro.core.plugins         : setting up transparent endpoint injection
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*.amazonaws.com pointing to LocalStack
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*.amazonaws.com with record DynamicRecord(record_type=<RecordType.A: 1>, record_id=None)
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*.amazonaws.com with record DynamicRecord(record_type=<RecordType.AAAA: 2>, record_id=None)
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*aws.amazon.com pointing to LocalStack
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*aws.amazon.com with record DynamicRecord(record_type=<RecordType.A: 1>, record_id=None)
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*aws.amazon.com with record DynamicRecord(record_type=<RecordType.AAAA: 2>, record_id=None)
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*cloudfront.net pointing to LocalStack
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*cloudfront.net with record DynamicRecord(record_type=<RecordType.A: 1>, record_id=None)
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding host .*cloudfront.net with record DynamicRecord(record_type=<RecordType.AAAA: 2>, record_id=None)
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding skip pattern ^redshift-maven-repository\.s3(\.[^\.]+)?\.amazonaws\.com
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding skip pattern ^localstack-pods-.*\.s3(\.[^\.]+)?\.amazonaws\.com
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding skip pattern ^localstack-assets\.s3(\.[^\.]+)?\.amazonaws\.com
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding skip pattern .*captcha-prod\.s3(\.[^\.]+)?\.amazonaws\.com
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding skip pattern .*(forums|console|docs|clientvpn|sso|boto3|(signin(\-reg)?))\.([^\.]+\.)?(aws\.amazon|amazonaws)\.com
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding skip pattern ^prod-registry-k8s-io-.*\.s3\.(dualstack\.)?.*\.amazonaws\.com
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding skip pattern ^aws\.amazon\.com
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding skip pattern ^github-production-release-.*\.s3(\.[^\.]+)?\.amazonaws\.com
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding skip pattern ^prodsharedcertsstack-.*\.s3(\.[^\.]+)?\.amazonaws\.com
2024-10-28T16:28:50.990 DEBUG --- [  MainThread] localstack.dns.server      : Adding skip pattern ^aws-glue-etl-artifacts\.s3(\.[^\.]+)?\.amazonaws\.com
2024-10-28T16:28:51.869 DEBUG --- [  MainThread] l.p.c.services.iam.router  : Adding IAM policy generation routes...
2024-10-28T16:28:52.319 DEBUG --- [  MainThread] localstack.runtime.init    : Init scripts discovered: {BOOT: [], START: [], READY: [], SHUTDOWN: []}
2024-10-28T16:28:52.319 DEBUG --- [  MainThread] localstack.plugins         : Checking for the usage of deprecated community features and configs...
2024-10-28T16:28:52.339 DEBUG --- [  MainThread] localstack.dns.server      : Overwriting container DNS server to point to localhost
```

I also checked with "awslocal apigateway get-models --rest-api-id <api-id>" if the model exists and if it is correctly referenced and it is.  

### Expected Behavior

The reference model should be referenced.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
docker-compose.yml
```
version: '3.8'
services:
  localstack:
    image: localstack/localstack-pro:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=ec2,lambda,s3,apigateway,apigatewaymanagementapi,cognito-idp,secretsmanager,lambda,acm,iam,route53,route53resolver,ses,ssm,ce,cloudfront,cognito-identity,rds-data,rds,wafv2,backup
      - DISABLE_CORS_CHECKS=1
      - DEBUG=1
      - CLOUDFRONT_STATIC_PORTS=1
      - PERSISTENCE=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=eu-central-1
      - GATEWAY_LISTEN=0.0.0.0:4566
      - EXTERNAL_SERVICE_PORTS_START=4510
      - EXTERNAL_SERVICE_PORTS_END=4559
      - LOCALSTACK_AUTH_TOKEN="secret"
      - MAIN_CONTAINER_NAME=localstack-main-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.volume/localstack:/var/lib/localstack"
```

    docker-compose up -d

#### Terraform configuration (cognito)
```
resource "aws_api_gateway_model" "api_gateway_model_status" {
  name         = "StatusModel"
  rest_api_id  = var.api_gateway_id
  content_type = "application/json"
  schema = jsonencode({
    type = "object",
    properties = {
      Status      = { type = "string" },
      Order = { type = "integer" }
    },
    required = [
      "Status",
      "Order"
    ]
  })
}

resource "aws_api_gateway_model" "api_gateway_model_status_list" {
  name         = "StatusModelList"
  rest_api_id  = var.api_gateway_id
  content_type = "application/json"
  schema = jsonencode({
    "type" : "array",
    "items" : {
      "$ref" : "https://apigateway.amazonaws.com/restapis/${var.api_gateway_id}/models/${aws_api_gateway_model.api_gateway_model_status.name}"
    }
  })
  depends_on = [aws_api_gateway_model.api_gateway_model_status]
}
```

### Environment

```markdown
- OS: 14.2.1 (23C71)
- LocalStack:
  LocalStack version: 3.8.2.dev57
  LocalStack build date: 2024-10-24
  LocalStack build git hash: 0dc006cc
```

**Comment by bentsku** [comment]
Hello @InvokedLambda and thanks for the report!

I've tried to reproduce the issue but to not avail: it properly resolves and does not try to hit directly AWS to get the model (it should use some trick to resolve the model locally without doing any network requests). 

Could you please share the results of `awslocal apigateway get-models --rest-api-id <api-id>` to see how it would differ in the definition of models?

I've done the following:
```bash
awslocal apigateway get-models --rest-api-id <api-id>
{
    "items": [
        {
            "id": "58577b",
            "name": "Empty",
            "description": "This is a default empty schema model",
            "schema": "{\"$schema\": \"http://json-schema.org/draft-04/schema#\", \"title\": \"Empty Schema\", \"type\": \"object\"}",
            "contentType": "application/json"
        },
        {
            "id": "56df31",
            "name": "Error",
            "description": "This is a default error schema model",
            "schema": "{\"$schema\": \"http://json-schema.org/draft-04/schema#\", \"title\": \"Error Schema\", \"type\": \"object\", \"properties\": {\"message\": {\"type\": \"string\"}}}",
            "contentType": "application/json"
        },
        {
            "id": "90452d",
            "name": "testSchema",
            "schema": "{\"$schema\": \"http://json-schema.org/draft-04/schema#\", \"title\": \"testSchema\", \"type\": \"object\", \"properties\": {\"a\": {\"type\": \"number\"}, \"b\": {\"type\": \"number\"}}, \"required\": [\"a\", \"b\"]}",
            "contentType": "application/json"
        },
        {
            "id": "43a8a8",
            "name": "testSchemaList",
            "schema": "{\"type\": \"array\", \"items\": {\"$ref\": \"https://apigateway.amazonaws.com/restapis/kcavyutwwo/models/testSchema\"}}",
            "contentType": "application/json"
        }
    ]
}
```

Enabling the validator and setting it to the method, I could invoke the API and get success/failure depending on my request body.

Hitting the API with the following JSON body: `[{"a": 1, "b": 2}]` would be successful, but sending `{}` would fail. 

Seems like I'm missing a step, maybe the models are more nested than that and it doesn't resolve properly? 
Looking at your logs, is the `BenutzerModel` properly defined in the Terraform config?

**Comment by InvokedLambda** [comment]
Hi @bentsku , thanks for your response.

Regarding _Looking at your logs, is the BenutzerModel properly defined in the Terraform config?_ I tested with different model references and I think while writing this bug report I got the logs from a different try but none of them was working. 

_Seems like I'm missing a step, maybe the models are more nested than that and it doesn't resolve properly?_ It is a much bigger model indeed but for client data security and compliance I could not post the whole model. The model has 30 attributes and 14 references, 4 references are also referencing other models, so it is nested. For BenutzerModel or StatusModel it is not nested. 

That I can post a bit more of my environment I have created a new model where I have no compliance issues. While creating it I tested a bit more and I found the case for which I got this error when I use oneOf and defining a null type and a reference. So this is the new model:
´´´
resource "aws_api_gateway_model" "api_gateway_model_test" {
  name         = "TestModel"
  rest_api_id  = var.api_gateway_id
  content_type = "application/json"
  schema = jsonencode({
    type = "object",
    properties = {
      status = {
        "oneOf" : [
          { "type" : "null" },
          { "$ref" : "https://apigateway.amazonaws.com/restapis/${var.api_gateway_id}/models/${aws_api_gateway_model.api_gateway_model_status.name}" }
        ]
      },
    },
    required = [
      "status"
    ]
  })
  depends_on = [
    aws_api_gateway_model.api_gateway_model_status
  ]
}

resource "aws_api_gateway_model" "api_gateway_model_status" {
  name         = "StatusModel"
  rest_api_id  = var.api_gateway_id
  content_type = "application/json"
  schema = jsonencode({
    type = "object",
    properties = {
      Status      = { type = "string" },
      Order       = { type = "integer" }
    },
    required = [
      "Status",
      "Order"
    ]
  })
}
´´´
This is the new error:
´´´
2024-10-28T21:00:20.154 ERROR --- [et.reactor-6] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.11/http/client.py", line 1303, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1349, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1058, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 996, in send
    self.connect()
  File "/usr/local/lib/python3.11/http/client.py", line 1468, in connect
    super().connect()
  File "/usr/local/lib/python3.11/http/client.py", line 962, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 863, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 848, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/referencing/_core.py", line 423, in get_or_retrieve
    resource = registry._retrieve(uri)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 113, in _warn_for_remote_retrieve
    with urlopen(request) as response:  # noqa: S310
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/referencing/_core.py", line 672, in lookup
    retrieved = self._registry.get_or_retrieve(uri)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/referencing/_core.py", line 430, in get_or_retrieve
    raise exceptions.Unretrievable(ref=uri) from error
referencing.exceptions.Unretrievable: 'https://apigateway.amazonaws.com/restapis/qgwzgjrf0k/models/StatusModel'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 463, in _validate_reference
    resolved = self._resolver.lookup(ref)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/referencing/_core.py", line 676, in lookup
    raise exceptions.Unresolvable(ref=ref) from error
referencing.exceptions.Unresolvable: https://apigateway.amazonaws.com/restapis/qgwzgjrf0k/models/StatusModel
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/handlers.py", line 27, in __call__
    router_response = self.router.dispatch(context.request)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/routing/router.py", line 326, in dispatch
    return self.dispatcher(request, handler, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/routing/handler.py", line 64, in __call__
    result = self.invoke_endpoint(request, endpoint, request_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/routing/pydantic.py", line 82, in invoke_endpoint
    return super().invoke_endpoint(request, endpoint, request_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/routing/handler.py", line 73, in invoke_endpoint
    return endpoint(request, **request_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/apigateway/legacy/router_asf.py.enc", line 31, in invoke_rest_api
    try:G=invoke_api(A);return convert_response(G)
          ^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/apigateway/legacy/integrations.py.enc", line 118, in invoke_api
    return invoke_rest_api(A)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/apigateway/legacy/invocations.py", line 287, in invoke_rest_api
    validator.validate_request()
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/apigateway/legacy/invocations.py", line 122, in validate_request
    if self.should_validate_body(validator) and not self._is_body_valid(resource):
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/apigateway/legacy/invocations.py", line 152, in _is_body_valid
    validate(
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 1330, in validate
    error = exceptions.best_match(validator.iter_errors(instance))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/exceptions.py", line 475, in best_match
    best = next(errors, None)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 384, in iter_errors
    for error in errors:
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/_keywords.py", line 296, in properties
    yield from validator.descend(
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 432, in descend
    for error in errors:
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/_keywords.py", line 355, in oneOf
    errs = list(validator.descend(instance, subschema, schema_path=index))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 432, in descend
    for error in errors:
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/_keywords.py", line 275, in ref
    yield from validator._validate_reference(ref=ref, instance=instance)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonschema/validators.py", line 465, in _validate_reference
    raise exceptions._WrappedReferencingError(err) from err
jsonschema.exceptions._WrappedReferencingError: Unresolvable: https://apigateway.amazonaws.com/restapis/qgwzgjrf0k/models/StatusModel
´´´
This is the output of awslocal apigateway get-models --rest-api-id <api-id> :
´´´
# awslocal apigateway get-models --rest-api-id qgwzgjrf0k
{
    "items": [
        {
            "id": "c42d00",
            "name": "StatusModel",
            "schema": "{\"properties\":{\"Reihenfolge\":{\"type\":\"integer\"},\"Status\":{\"type\":\"string\"}},\"required\":[\"Status\",\"Reihenfolge\"],\"type\":\"object\"}",
            "contentType": "application/json"
        },
        {
            "id": "6e1340",
            "name": "TestModel",
            "schema": "{\"properties\":{\"status\":{\"oneOf\":[{\"type\":\"null\"},{\"$ref\":\"https://apigateway.amazonaws.com/restapis/qgwzgjrf0k/models/StatusModel\"}]}},\"required\":[\"status\"],\"type\":\"object\"}",
            "contentType": "application/json"
        }
    ]
}
´´´

**Comment by bentsku** [comment]
Ah, thanks a lot for the additional context: it is the same issue as #9631 then, we do not support the `oneOf` property yet. I'll look into how much it would be to implement it and I'll come back to you. Thanks again for the minimal set of reproduction!

**Comment by InvokedLambda** [comment]
Thanks for that information and your effort!

Based on the size and complexity of model and the project itself, some details are not directly visible …

**Comment by bentsku** [comment]
Thank you so much for the very contained reproducer! The fix was actually rather simple to implement, we did not replace the `$ref` inside arrays. I've pushed a fix in the linked PR, and will get it merged this week. Thank you so much!
