### ISSUE TITLE
bug: 500 InternalError when calling ec2.DescribeSubnets

### ISSUE THREAD

**Issue by mikeshultz** [localstack/localstack#11765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using Pulumi, which is calling `ec2.DescribeSubnets`. The following error shows up in the localstack console:

```
2024-10-28T18:32:01.969 ERROR --- [et.reactor-0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 113, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 83, in __call__
    skeleton_response = self.skeleton.invoke(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(serializer, context, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 168, in dispatch_request
    result = handler(context, instance) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/forwarder.py", line 133, in _call
    return handler(context, req)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/api/core.py", line 160, in operation_marker
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/ec2/provider.py", line 328, in describe_subnets
    result = call_moto(context)
             ^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/moto.py", line 48, in call_moto
    return dispatch_to_backend(context, dispatch_to_moto, include_response_metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/forwarder.py", line 185, in dispatch_to_backend
    http_response = http_request_dispatcher(context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/moto.py", line 118, in dispatch_to_moto
    response = dispatch(request, raw_url, request.headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/core/responses.py", line 291, in dispatch
    return cls()._dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/core/responses.py", line 503, in _dispatch
    return self.call_action()
           ^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/core/responses.py", line 591, in call_action
    response = method()
               ^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/ec2/responses/subnets.py", line 40, in describe_subnets
    filters = self._filters_from_querystring()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/ec2/responses/_base_response.py", line 20, in _filters_from_querystring
    return {f["Name"]: f["Value"] for f in _filters}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/ec2/responses/_base_response.py", line 20, in <dictcomp>
    return {f["Name"]: f["Value"] for f in _filters}
            ~^^^^^^^^
TypeError: string indices must be integers, not 'str'
2024-10-28T18:32:01.972  INFO --- [et.reactor-0] localstack.request.aws     : AWS ec2.DescribeSubnets => 500 (InternalError)
```

### Expected Behavior

Return the subnets or a 400 if bad input.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run -e LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN} localstack/localstack-pro:3.8.0

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Run the pulumi program in this repo: https://github.com/mikeshultz/localstack-get-subnets-bug

### Environment

```markdown
- OS: Linux
- LocalStack:
  LocalStack version: 3.8.0
  LocalStack Docker image sha: 71b22b9d2fc4bd9edadfb7502887f6507be0cccc4f76fb1a1972672845554b34
  LocalStack build date:
  LocalStack build git hash:
```

### Anything else?

I wasn't immediately able to find an equivalent aws-cli command.  Let me know if I can provide any more info.

**Comment by michal-franc** [comment]
Hey @mikeshultz I have researched this problem and it looks like problem is with how DefaultVPC behaves, `default_vpc.id` is not fully formed and returns `Output[str]` value which requires you to unwrap it.

I think the solution here is to use apply function on `default_vpc.id` to unwrap the value and make a call for subnets inside apply function.
```python
import pulumi
from pulumi import Output
from pulumi_aws import ec2, s3

default_vpc = ec2.DefaultVpc("default")

res = default_vpc.id.apply(lambda vpcId: 
    ec2.get_subnets(
        filters=[
            ec2.GetSubnetsFilterArgs(name="vpc-id", values=[vpcId]),
            ec2.GetSubnetsFilterArgs(name="map-public-ip-on-launch", values=["true"]),
        ]
    )
)
pulumi.export("vpc-ids", res.ids)
```

Let me know if this helps :)
