### ISSUE TITLE
bug: I'm having issues while using localstack SQS as my celery broker in my flask application

### ISSUE THREAD

**Issue by git-stack-debug** [localstack/localstack#11798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using the following code to create a celery app in my flask application
```python
import os
from celery import Celery

# Set environment variables for AWS credentials and region
os.environ['AWS_ACCESS_KEY_ID'] = "test"
os.environ['AWS_SECRET_ACCESS_KEY'] = "test"
os.environ['AWS_DEFAULT_REGION'] = "ap-south-1"
os.environ['AWS_SESSION_TOKEN'] = ""


def make_celery_3(app):
    # Initialize Celery with the SQS broker URL
    celery = Celery(
        app.import_name,
        broker='sqs://'
    )

    # Celery configurations with updated broker_transport_options
    celery.conf.broker_connection_retry_on_startup = True
    celery.conf.task_default_queue = "insurance_celery_queue_prod"
    celery.conf.broker_transport_options = {
        'region': 'ap-south-1',
        'visibility_timeout': 3600,
        'polling_interval': 5,
        'endpoint_url': 'http://localhost:4566',  # Match LocalStack setup
        'aws_access_key_id': 'test',
        'aws_secret_access_key': 'test',
        'aws_session_token': ''
    }

    # Debug print to verify broker_transport_options
    print("Broker transport options:", celery.conf.broker_transport_options)

    # Define a context-aware task to integrate Flask app context with Celery
    class ContextTask(celery.Task):
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return self.run(*args, **kwargs)

    celery.Task = ContextTask
    return celery
```

And i'm getting the following error:
[2024-11-07 01:29:12,371: CRITICAL/MainProcess] Unrecoverable error: ClientError('An error occurred (InvalidClientTokenId) when calling the ListQueues operation: The security token included in the request is invalid.')

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:
- LocalStack:
  LocalStack version:
  LocalStack Docker image sha:
  LocalStack build date:
  LocalStack build git hash:
```

**Comment by bentsku** [comment]
Hello, from the error, it seems that Celery is still targeting the real AWS.

I'm looking into the pytest plugin as it seems LocalStack is supported directly: https://docs.celeryq.dev/projects/pytest-celery/en/latest/getting-started/vendors.html#localstack-sqs-broker. This could be a solution for you, but for local dev, this might not be ideal.

But as it seems Celery is supporting SQS via [kombu](https://github.com/celery/kombu/blob/main/kombu/transport/SQS.py), which itself seems to use `boto3`, could you try also setting the following environment variable? 
`os.environ['AWS_ENDPOINT_URL'] = "http://localhost:4566"`

It seems the `endpoint_url` option for the `celery.conf.broker_transport_options` is not being respected, it could maybe be worth opening a feature request in the celery repo for this. 

Hopefully, this fixes the issue for you!

**Comment by git-stack-debug** [comment]
Hi
Thanks for your response. I've tried the solution that you recommended but it is throwing another error now. Following is the error that I'm getting now:

[2024-11-07 10:59:05,535: CRITICAL/MainProcess] Unrecoverable error: ImportError('The curl client requires the pycurl library.')
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/kombu/asynchronous/http/__init__.py", line 25, in get_client
    return hub._current_http_client
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Hub' object has no attribute '_current_http_client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/venv/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/venv/lib/python3.11/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
           ^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/venv/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/venv/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 746, in start
    c.loop(*c.loop_args())
  File "/venv/lib/python3.11/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/venv/lib/python3.11/site-packages/kombu/asynchronous/hub.py", line 306, in create_loop
    item()
  File "/venv/lib/python3.11/site-packages/vine/promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/vine/promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/kombu/transport/SQS.py", line 600, in _schedule_queue
    self._get_bulk_async(
  File "/venv/lib/python3.11/site-packages/kombu/transport/SQS.py", line 617, in _get_bulk_async
    return self._get_async(queue, maxcount, callback=callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/kombu/transport/SQS.py", line 628, in _get_async
    connection=self.asynsqs(queue=qname),
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/kombu/transport/SQS.py", line 827, in asynsqs
    c = self._asynsqs = AsyncSQSConnection(
                        ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/kombu/asynchronous/aws/sqs/connection.py", line 26, in __init__
    super().__init__(
  File "/venv/lib/python3.11/site-packages/kombu/asynchronous/aws/connection.py", line 182, in __init__
    super().__init__(sqs_connection, http_client,
  File "/venv/lib/python3.11/site-packages/kombu/asynchronous/aws/connection.py", line 136, in __init__
    self._httpclient = http_client or get_client()
                                      ^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/kombu/asynchronous/http/__init__.py", line 27, in get_client
    client = hub._current_http_client = Client(hub, **kwargs)
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/kombu/asynchronous/http/__init__.py", line 18, in Client
    return CurlClient(hub, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/kombu/asynchronous/http/curl.py", line 43, in __init__
    raise ImportError('The curl client requires the pycurl library.')
ImportError: The curl client requires the pycurl library.

**Comment by bentsku** [comment]
Hello! I think this is an issue in how you are using Celery probably and is unrelated to LocalStack? Could you try running `pip install pycurl` in the environment you're running the code you share?

**Comment by git-stack-debug** [comment]
Hi..
I too thought so.. and tried installing the pycurl but it is already installed in my virtualenv and I'm still getting the same error.
For your reference:
`Requirement already satisfied: pycurl in ./venv/lib/python3.11/site-packages (7.45.3)`

**Comment by bentsku** [comment]
Seems like the `kombu` library is actively working on removing it: https://github.com/celery/kombu/pull/2134, but haven't released the change yet. 

Seems like it could be linked to this blog post: https://medium.glynjackson.org/installing-pycurl-importerror-on-ventura-aff64b8dfe8b

I'd suggest to open an issue In the [kombu](https://github.com/celery/kombu) repository, as this is unrelated to LocalStack? We could re-open this issue if you still encounter an issue after getting it to run? 

Thanks!

**Comment by git-stack-debug** [comment]
So, is there any way i can test SQS based celery on my local machine.
Any suggestion/blog/article would help!!

**Comment by aashutosh-habile** [comment]
> Hello, from the error, it seems that Celery is still targeting the real AWS.
> 
> I'm looking into the pytest plugin as it seems LocalStack is supported directly: https://docs.celeryq.dev/projects/pytest-celery/en/latest/getting-started/vendors.html#localstack-sqs-broker. This could be a solution for you, but for local dev this might not be ideal.
> 
> But as it seems Celery is supporting SQS via [kombu](https://github.com/celery/kombu/blob/main/kombu/transport/SQS.py), which itself seems to use `boto3`, could you try also setting the following environment variable? `os.environ['AWS_ENDPOINT_URL'] = "http://localhost:4566"`
> 
> It seems the `endpoint_url` option for the `celery.conf.broker_transport_options` is not being respected, it could maybe be worth opening a feature request in the celery repo for this.
> 
> Hopefully, this fixes the issue for you!

This is the correct answer. Thank you
