### ISSUE TITLE
bug: "No JVM shared library file (libjvm.so) found" when publishing event to EventBus

### ISSUE THREAD

**Issue by CodeOnCoffee** [localstack/localstack#11899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This started when we upgraded to 4.0.0 (also shows in latest). Putting a message on the EventBus produces an error:

`$ awslocal events put-events --entries file://test/fixtures/workorder-eb-event.json

An error occurred (InternalError) when calling the PutEvents operation (reached max retries: 2): exception while calling events.PutEvents: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack-core/localstack/aws/handlers/service.py", line 113, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack-core/localstack/aws/handlers/service.py", line 83, in __call__
    skeleton_response = self.skeleton.invoke(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack-core/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(serializer, context, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack-core/localstack/aws/skeleton.py", line 168, in dispatch_request
    result = handler(context, instance) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack-core/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack-core/localstack/aws/api/core.py", line 163, in operation_marker
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack-core/localstack/services/events/provider.py", line 1336, in put_events
    entries, failed_entry_count = self._process_entries(context, entries)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack-core/localstack/services/events/provider.py", line 1944, in _process_entries
    self._process_entry(event, processed_entries, failed_entry_count, context)
  File "/opt/code/localstack/localstack-core/localstack/services/events/provider.py", line 1993, in _process_entry
    self._process_rules(rule, region, account_id, event_formatted)
  File "/opt/code/localstack/localstack-core/localstack/services/events/provider.py", line 2018, in _process_rules
    if matches_event(event_pattern, event_str):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack-core/localstack/utils/event_matcher.py", line 44, in matches_event
    return matches_rule(event, event_pattern)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack-core/localstack/services/events/event_ruler.py", line 55, in matches_rule
    start_jvm()
  File "/opt/code/localstack/localstack-core/localstack/utils/objects.py", line 203, in _singleton_factory
    instance.set(factory())
                 ^^^^^^^^^
  File "/opt/code/localstack/localstack-core/localstack/services/events/event_ruler.py", line 32, in start_jvm
    jpype.startJVM(jvm_lib, classpath=[event_ruler_libs_pattern], interrupt=False)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jpype/_core.py", line 238, in startJVM
    jvmpath = getDefaultJVMPath()
              ^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jpype/_jvmfinder.py", line 70, in getDefaultJVMPath
    return finder.get_jvm_path()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jpype/_jvmfinder.py", line 204, in get_jvm_path
    raise JVMNotFoundException("No JVM shared library file ({0}) "
jpype._jvmfinder.JVMNotFoundException: No JVM shared library file (libjvm.so) found. Try setting up the JAVA_HOME environment variable properly.
`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

awslocal events put-events --entries file://test/fixtures/workorder-eb-event.json

### Environment

```markdown
- OS: Mac OS X (AMD64)
- LocalStack:
  LocalStack version: 4.0.0
```

**Comment by CodeOnCoffee** [comment]
Error went away when I commented out this environment variable:

EVENT_RULE_ENGINE=java
