### ISSUE TITLE
Error: No handlers could be found for logger "infra.pyc"

### ISSUE THREAD

**Issue by ovunccetin** [localstack/localstack#119]
I have installed localstack with pip to my MacOS Sierra v10.12.4. And I run with "sudo localstack infra". It looks it is running all the services. But when I hit to a service from aws CLI, the server is terminated with an error trace like below:

`No handlers could be found for logger "infra.pyc"
Traceback (most recent call last):
  File "/usr/local/bin/localstack", line 31, in <module>
    infra.start_infra()
  File "/usr/local/lib/python2.7/site-packages/localstack/mock/infra.py", line 408, in start_infra
    check_infra(apis=apis)
  File "/usr/local/lib/python2.7/site-packages/localstack/mock/infra.py", line 343, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/mock/infra.py", line 343, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/mock/infra.py", line 343, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/mock/infra.py", line 343, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/mock/infra.py", line 343, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/mock/infra.py", line 343, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/mock/infra.py", line 343, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/mock/infra.py", line 343, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/mock/infra.py", line 341, in check_infra
    raise e
AssertionError`

**Comment by whummer** [comment]
Thanks for reporting @ovunccetin . There should be no need for `sudo` - in fact, `sudo` is not tested, unsupported, and highly discouraged! Can you please try running `localstack infra` under a non-root user account?

Also, a new version has been released, you might want to try re-installing:
```
pip install --no-cache localstack
```
Thanks

**Comment by whummer** [comment]
Any update on this issue @ovunccetin - did you have a chance to give it a try with the new version?  Thanks

**Comment by whummer** [comment]
Closing this issue as there hasn't been an update in a while. Please feel free to re-open if the problem persists. Thanks.
