### ISSUE TITLE
bug: Non- `us-west-1` region fails with ECR. Running localstack 4/latest with docker compose doesn't do networking correctly for lambda container to find ecr in non-us-east-1 region

### ISSUE THREAD

**Issue by revelfire** [localstack/localstack#12043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I fought this for awhile thinking it was me....turns out...

Using your example it is reproducible: https://github.com/localstack-samples/localstack-pro-samples/tree/master/lambda-container-image

export AWS_REGION=eu-west-1
(base) ➜  lambda-container-image git:(master) make install
/Users/cmathias/miniconda3/bin/awslocal
(base) ➜  lambda-container-image git:(master) make run
echo "Creating a new ECR repository locally"; \
	repoUri=$(awslocal ecr create-repository --repository-name repo1 | jq -r '.repository.repositoryUri'); \
	echo "Building the Docker image, pushing it to ECR URL: $repoUri"; \
	docker build -t "$repoUri" .; \
	docker push "$repoUri"; \
	docker rmi "$repoUri"; \
	echo "Deploying Lambda function from container image locally"; \
	awslocal lambda create-function --function-name ls-lambda-image --package-type Image \
		--code ImageUri=$repoUri --role arn:aws:iam::000000000000:role/lambda-r1 \
		--handler handler.handler; \
	echo "Waiting until Lambda function becomes active"; \
	awslocal lambda wait function-active-v2 --function-name ls-lambda-image; \
	echo "Invoking Lambda function from container image"; \
	awslocal lambda invoke --function-name ls-lambda-image --payload '{"test":"test"}' /tmp/lambda.out && \
	echo "Done - test successfully finished."
Creating a new ECR repository locally
Building the Docker image, pushing it to ECR URL: 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/repo1
[+] Building 1.3s (7/7) FINISHED                                                                                                                                                        docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                                                    0.0s
 => => transferring dockerfile: 198B                                                                                                                                                                    0.0s
 => [internal] load metadata for public.ecr.aws/lambda/python:3.8                                                                                                                                       1.2s
 => [internal] load .dockerignore                                                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                                                         0.0s
 => [internal] load build context                                                                                                                                                                       0.0s
 => => transferring context: 31B                                                                                                                                                                        0.0s
 => [1/2] FROM public.ecr.aws/lambda/python:3.8@sha256:8f0e2648058ec1d4a3e8e89e897f6085f93d9806a8b868066d5ba1b10b4b7392                                                                                 0.0s
 => CACHED [2/2] COPY ./handler.py ./                                                                                                                                                                   0.0s
 => exporting to image                                                                                                                                                                                  0.0s
 => => exporting layers                                                                                                                                                                                 0.0s
 => => writing image sha256:843f43b6c032923eceffc192a252ce860acb7a92620fdda8dfa96fa598a9c614                                                                                                            0.0s
 => => naming to 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/repo1                                                                                                                   0.0s

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview 
Using default tag: latest
The push refers to repository [000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/repo1]
Get "https://000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Untagged: 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/repo1:latest
Deploying Lambda function from container image locally
{
    "FunctionName": "ls-lambda-image",
    "FunctionArn": "arn:aws:lambda:eu-west-1:000000000000:function:ls-lambda-image",
    "Role": "arn:aws:iam::000000000000:role/lambda-r1",
    "Handler": "handler.handler",
    "CodeSize": 0,
    "Description": "",
    "Timeout": 3,
    "MemorySize": 128,
    "LastModified": "2024-12-16T15:18:57.131372+0000",
    "CodeSha256": "<cannot-get-image-hash>",
    "Version": "$LATEST",
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "fb0b486f-9f92-41d1-ab79-0d3709cb7b9f",
    "State": "Pending",
    "StateReason": "The function is being created.",
    "StateReasonCode": "Creating",
    "PackageType": "Image",
    "Architectures": [
        "x86_64"
    ],
    "EphemeralStorage": {
        "Size": 512
    },
    "SnapStart": {
        "ApplyOn": "None",
        "OptimizationStatus": "Off"
    },
    "LoggingConfig": {
        "LogFormat": "Text",
        "LogGroup": "/aws/lambda/ls-lambda-image"
    }
}
Waiting until Lambda function becomes active

Waiter FunctionActiveV2 failed: Waiter encountered a terminal failure state: For expression "Configuration.State" we matched expected path: "Failed"
Invoking Lambda function from container image

An error occurred (ResourceConflictException) when calling the Invoke operation: The operation cannot be performed at this time. The function is currently in the following state: Failed
make: *** [run] Error 254

### Expected Behavior

The referenced containerized-lambda demo works even if not using us-west-1 region. (in my case I was trying eu-west-1)

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
`docker-compose.yml`
    docker compose up localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

export AWS_REGION=eu-west-1
(base) ➜  lambda-container-image git:(master) make install
/Users/cmathias/miniconda3/bin/awslocal
(base) ➜  lambda-container-image git:(master) make run

### Environment

```markdown
- OS: MacOS Sonoma 14.4
- LocalStack:
  LocalStack version: 4.0.4.dev47
  LocalStack Docker image sha: sha256:a79c15eb84f3209c8f391c85a0bc23875f6f0cc5e25ac601fa2e0fc07ba09e6c
  LocalStack build date:  2024-12-13
  LocalStack build git hash: c153b79c2
```

### Anything else?

Here's the localstack-side logs:

```
lstack_main  | 2024-12-16T15:18:27.076 DEBUG --- [et.reactor-0] l.u.c.docker_sdk_client    : Pulling Docker image: 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/repo1
localstack_main  | 2024-12-16T15:18:42.100 DEBUG --- [et.reactor-0] l.s.l.i.lambda_service     : Cannot pull image 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/repo1. Maybe only available locally?
localstack_main  | 2024-12-16T15:18:42.104 DEBUG --- [et.reactor-0] l.u.c.docker_sdk_client    : Pulling Docker image: 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/repo1
localstack_main  | 2024-12-16T15:18:57.130 DEBUG --- [et.reactor-0] l.s.l.i.lambda_service     : Cannot inspect image 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/repo1. Is this image and/or docker available: 
localstack_main  | 2024-12-16T15:18:57.134  INFO --- [et.reactor-0] localstack.request.aws     : AWS lambda.CreateFunction => 201
localstack_main  | 2024-12-16T15:18:57.140 DEBUG --- [rvice-task_0] l.p.c.s.l.i.docker_runtime : Executing prepare docker executor pro-hook for function arn:aws:lambda:eu-west-1:000000000000:function:ls-lambda-image:$LATEST
localstack_main  | 2024-12-16T15:18:57.140 DEBUG --- [rvice-task_0] l.u.c.docker_sdk_client    : Pulling Docker image: 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/repo1
localstack_main  | 2024-12-16T15:18:57.910  INFO --- [et.reactor-2] localstack.request.aws     : AWS lambda.GetFunction => 200
localstack_main  | 2024-12-16T15:18:58.924  INFO --- [et.reactor-3] localstack.request.aws     : AWS lambda.GetFunction => 200

....

localstack_main  | 2024-12-16T15:19:12.170 DEBUG --- [rvice-task_0] l.s.l.i.version_manager    : Changing Lambda arn:aws:lambda:eu-west-1:000000000000:function:ls-lambda-image:$LATEST (id 57c6686c) to failed. Reason: 
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/api/client.py", line 275, in _raise_for_status
localstack_main  |     response.raise_for_status()
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
localstack_main  |     raise HTTPError(http_error_msg, response=self)
localstack_main  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.47/images/create?tag=latest&fromImage=000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud%3A4566%2Frepo1&platform=linux%2Famd64
localstack_main  | 
localstack_main  | The above exception was the direct cause of the following exception:
localstack_main  | 
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/container_utils/docker_sdk_client.py", line 271, in pull_image
localstack_main  |     self.client().images.pull(docker_image, platform=platform)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/models/images.py", line 464, in pull
localstack_main  |     pull_log = self.client.api.pull(
localstack_main  |                ^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/api/image.py", line 429, in pull
localstack_main  |     self._raise_for_status(response)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/api/client.py", line 277, in _raise_for_status
localstack_main  |     raise create_api_error_from_http_exception(e) from e
localstack_main  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
localstack_main  |     raise cls(e, response=response, explanation=explanation) from e
localstack_main  | docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=latest&fromImage=000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud%3A4566%2Frepo1&platform=linux%2Famd64: Internal Server Error ("Get "https://000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)")
localstack_main  | 
localstack_main  | The above exception was the direct cause of the following exception:
localstack_main  | 
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/lambda_/invocation/version_manager.py", line 84, in start
localstack_main  |     get_runtime_executor().prepare_version(self.function_version)  # TODO: make pluggable?
localstack_main  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/lambda_/invocation/docker_runtime_executor.py", line 478, in prepare_version
localstack_main  |     lambda_hooks.prepare_docker_executor.run(function_version)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/runtime/hooks.py", line 65, in run_in_order
localstack_main  |     fn_plugin(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/plux/core/plugin.py", line 226, in __call__
localstack_main  |     return self.fn(*args, **kwargs)
localstack_main  |            ^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/lambda_/invocation/docker_runtime_executor_hooks.py.enc", line 49, in prepare_docker_executor_hook
localstack_main  |     try:D=docker_platform(A.config.architectures[0]);CONTAINER_CLIENT.pull_image(B.image_uri,D)
localstack_main  |                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/container_utils/docker_sdk_client.py", line 275, in pull_image
localstack_main  |     raise ContainerException() from e
localstack_main  | localstack.utils.container_utils.container_client.ContainerException
localstack_main  | 2024-12-16T15:19:12.173 DEBUG --- [rvice-task_0] l.s.l.i.version_manager    : Stopping lambda version 'arn:aws:lambda:eu-west-1:000000000000:function:ls-lambda-image:$LATEST'
localstack_main  | 2024-12-16T15:19:13.099  INFO --- [et.reactor-3] localstack.request.aws     : AWS lambda.GetFunction => 200
localstack_main  | 2024-12-16T15:19:13.906 ERROR --- [et.reactor-0] l.services.lambda_.hints   : Failed to create the runtime executor for the function ls-lambda-image. Please ensure that Docker is available in the LocalStack container by adding the volume mount "/var/run/docker.sock:/var/run/docker.sock" to your LocalStack startup. Check out https://docs.localstack.cloud/user-guide/aws/lambda/#docker-not-available
localstack_main  | 2024-12-16T15:19:13.907  INFO --- [et.reactor-0] localstack.request.aws     : AWS lambda.Invoke => 409 (ResourceConflictException)
```

**Comment by joe4dev** [comment]
Hi @revelfire 

We couldn't reproduce the issue when changing `export AWS_DEFAULT_REGION = eu-west-1` in the sample or using the parameter `--region eu-west-1`. I use `LAMBDA_IGNORE_ARCHITECTURE=1` on an ARM Macbook; see [ARM64 Support](https://docs.localstack.cloud/references/arm64-support/).

A couple of guesses:

a) Does pushing succeed?
Looking at the logs suggests that the ECR image is not available/retrievable:

> Using default tag: latest
> The push refers to repository [000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/repo1]
> Get "https://000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/v2/": net/http: request canceled while > waiting for connection (Client.Timeout exceeded while awaiting headers)
> Untagged: 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/repo1:latest

b) Does DNS resolve properly? https://docs.localstack.cloud/user-guide/tools/dns-server/#dns-rebind-protection

c) Is `export AWS_REGION=eu-west-1` picked up properly (it seems so from the logs, but I had to change the value in the sample Makefile)?

d) Can you confirm that the same sample works in `us-east-1`?
