### ISSUE TITLE
HTTP2 protocol support

### ISSUE THREAD

**Issue by aslepakurov** [localstack/localstack#1218]
Right now if you try to use AWS SDK 2.x with localstack, by default SDK will use `HTTP2` and this will cause following exception

```
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 3c68656164
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85) ~[netty-codec-http2-4.1.33.Final.jar:na]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:350) ~[netty-codec-http2-4.1.33.Final.jar:na]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251) ~[netty-codec-http2-4.1.33.Final.jar:na]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450) ~[netty-codec-http2-4.1.33.Final.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-codec-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.handler.codec.http2.ForkedHttp2MultiplexCodec.channelRead(ForkedHttp2MultiplexCodec.java:359) ~[netty-nio-client-2.4.0.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	... 2 common frames omitted
```
This particular exception was thrown while trying to use kinesis (happens on ListShards)
Maybe there is point to add HTTP2 support? What are your thoughts?

**Comment by aslepakurov** [comment]
Current workaround is to set protocol in Netty http client by yourself: 
```
 val httpClient = NettyNioAsyncHttpClient.builder()
                .protocol(Protocol.HTTP1_1)
                .build()
 var kinesisClient = KinesisAsyncClient.builder().credentialsProvider(credentialsProvider())
            .region(Region.of(awsRegion)).httpClient(httpClient).build()
```

**Comment by joro550** [comment]
Is there anyway this is configurable via the MultiLangDeamon?

**Comment by davecow8** [comment]
I cannot find a way to configure this in the MultiLangDeamon either. It has code that creates the KinesisAsyncClient for you and there is no way to override it without changing the code in the project from what I can tell.

**Comment by joro550** [comment]
That's a shame, I currently can't run the KCL against localstack and I have a feeling that this may be the issue.

**Comment by khitsik** [comment]
Run in the same issue!

**Comment by fivetentaylor** [comment]
Same issue 😢

**Comment by whummer** [comment]
Thanks for reporting @aslepakurov @joro550 @khitsik @fivetentaylor . The `latest` version now contains initial support for HTTP/2. Can you please give it a try with the latest version to check if the problem still persists? Please note that CBOR encoding is currently still not supported - you'd need to configure your AWS SDK to use plain JSON payloads instead. Hope that helps - please keep us posted how it goes, thanks.

**Comment by whummer** [comment]
HTTP2 is now supported, and CBOR encoding support for Kinesis has been added in #3078 . Hope it should now be working for the use cases mentioned in this thread. Please report here if the problem persists with the `latest` version of the Docker image. Thanks!
