### ISSUE TITLE
Error while starting the local stack

### ISSUE THREAD

**Issue by Muraligowtham** [localstack/localstack#1263]
Team, I installed local stack for the first time using the pip command and tried to start it, but I am getting the following error

Starting local dev environment. CTRL-C to quit.
2019-04-18T16:59:20:INFO:localstack.services.install: Downloading and installing local Elasticsearch server. This may take some time.
2019-04-18T16:59:20:INFO:localstack.services.install: Downloading and installing local Kinesis server. This may take some time.
ERROR: 'cd "/home/boomiuser/.local/lib/python2.7/site-packages/localstack" && npm install': exit code 127; output: /bin/sh: 1: npm: not found

Error starting infrastructure: Command 'cd "/home/boomiuser/.local/lib/python2.7/site-packages/localstack" && npm install' returned non-zero exit status 127 Traceback (most recent call last):
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 567, in start_infra
    install.install_components(apis)
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/services/install.py", line 169, in install_components
    parallelize(install_component, names)
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/utils/common.py", line 986, in parallelize
    result = pool.map(func, list)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
CalledProcessError: Command 'cd "/home/boomiuser/.local/lib/python2.7/site-packages/localstack" && npm install' returned non-zero exit status 127

ERROR: Command 'cd "/home/boomiuser/.local/lib/python2.7/site-packages/localstack" && npm install' returned non-zero exit status 127

any suggestion on how this can be resolved?

**Comment by wickedgenius** [comment]
> ERROR: 'cd "/home/boomiuser/.local/lib/python2.7/site-packages/localstack" && npm install': exit code 127; output: /bin/sh: 1: npm: not found

Looks like you don't have npm installed.

**Comment by Muraligowtham** [comment]
Now I am getting this error
```

Starting mock Firehose service (http port 4573)...
 * Serving Flask app "firehose_api" (lazy loading)
 * Environment: production
Starting mock Route53 (http port 4580)...
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
Starting mock ES service (http port 4578)...
 * Debug mode: off
Starting mock IAM (http port 4593)...
 * Serving Flask app "es_api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
Starting mock DynamoDB Streams service (http port 4570)...
   Use a production WSGI server instead.
 * Debug mode: off
Starting mock S3 (http port 4572)...
 * Serving Flask app "ddb_streams_api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
Starting mock CloudWatch (http port 4582)...
   Use a production WSGI server instead.
 * Debug mode: off
Starting mock DynamoDB (http port 4569)...
Starting mock Kinesis (http port 4568)...
Starting mock SQS (http port 4576)...
Starting mock SSM (http port 4583)...
Starting mock SNS (http port 4575)...
Starting mock API Gateway (http port 4567)...
Starting mock Secrets Manager (http port 4584)...
Starting local Elasticsearch (http port 4571)...
Starting mock STS (http port 4592)...
Starting mock StepFunctions (http port 4585)...
Starting mock Lambda service (http port 4574)...
 * Serving Flask app "lambda_api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2019-05-14T17:24:17:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-05-14T17:24:31:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-05-14T17:24:45:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-05-14T17:25:00:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-05-14T17:25:14:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-05-14T17:25:28:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-05-14T17:25:42:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-05-14T17:25:56:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-05-14T17:26:10:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-05-14T17:26:24:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-05-14T17:26:38:ERROR:localstack.services.dynamodb.dynamodb_starter: DynamoDB health check failed:  Traceback (most recent call last):
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/services/dynamodb/dynamodb_starter.py", line 21, in check_dynamodb
    wait_for_port_open(DEFAULT_PORT_DYNAMODB_BACKEND, http_path='/', expect_success=False, sleep_time=1)
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/utils/common.py", line 362, in wait_for_port_open
    return retry(check, sleep=sleep_time, retries=retries)
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/utils/common.py", line 395, in retry
    raise raise_error
Exception

2019-05-14T17:26:38:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2019-05-14T17:26:38:ERROR:infra.pyc: Error checking state of local environment (after some retries): Traceback (most recent call last):
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 408, in check_infra
    raise e
TypeError: 'NoneType' object has no attribute '__getitem__'

Error starting infrastructure: 'NoneType' object has no attribute '__getitem__' Traceback (most recent call last):
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 584, in start_infra
    check_infra(apis=apis)
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 417, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/boomiuser/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 415, in check_infra
    raise e
TypeError: 'NoneType' object has no attribute '__getitem__'

ERROR: 'NoneType' object has no attribute '__getitem__'
```

**Comment by Muraligowtham** [comment]
Got this resolved my uninstalling local stack completely and reinstalling it again. Had to remove the local stack folder form python lib
