### ISSUE TITLE
java.lang.RuntimeException: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Muraligowtham** [localstack/localstack#1271]
**Issue 1:**

```
import org.junit.runner.RunWith;

import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.model.Bucket;

import antlr.collections.List;
import cloud.localstack.LocalstackTestRunner;
import cloud.localstack.TestUtils;

@RunWith(LocalstackTestRunner.class)
public class Test {

  public static final String TEST_ACCESS_KEY = "test";
  public static final String TEST_SECRET_KEY = "test";
  public static final AWSCredentials TEST_CREDENTIALS = new BasicAWSCredentials(TEST_ACCESS_KEY, TEST_SECRET_KEY);

  @org.junit.Test
  public void Test() {
    AmazonS3 s3 = TestUtils.getClientS3();
    java.util.List<Bucket> buckets = s3.listBuckets();
  }

}
```

Stack trace:
```Apr 26, 2019 4:37:12 PM cloud.localstack.Localstack ensureInstallation
INFO: Installing LocalStack to temporary directory (this may take a while): /tmp/localstack_install_dir
java.lang.RuntimeException: java.lang.IllegalStateException: Failed to run command 'bash -c cd "/tmp/localstack_install_dir"; make install', return code 2.
STDOUT: (test `which virtualenv` || pip install --user virtualenv) && \
	(test -e .venv || virtualenv  .venv) && \
	(test ! -e requirements.txt || (. .venv/bin/activate; pip -q install -r requirements.txt) && \
	. .venv/bin/activate; PYTHONPATH=. exec python localstack/services/install.py testlibs)
ERROR: 'javac -cp "/tmp/localstack_install_dir/localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-core-2.6.7.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.9.0.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/guava-18.0.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpclient-4.5.2.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-codec-1.9.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-lang-2.6.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpcore-4.4.4.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-databind-2.6.7.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jmespath-java-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.7.jar:/tmp/localstack_install_dir/localstack/utils/kinesis/java" /tmp/localstack_install_dir/localstack/utils/kinesis/java/com/atlassian/*.java': exit code 127; output: /bin/sh: 1: javac: not found

Makefile:14: recipe for target 'install' failed

STDERR: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Traceback (most recent call last):
  File "localstack/services/install.py", line 222, in <module>
    install_amazon_kinesis_client_libs()
  File "localstack/services/install.py", line 145, in install_amazon_kinesis_client_libs
    run('javac -cp "%s" %s' % (classpath, java_files))
  File "/tmp/localstack_install_dir/localstack/utils/common.py", line 847, in run
    return do_run(cmd)
  File "/tmp/localstack_install_dir/localstack/utils/common.py", line 844, in do_run
    raise e
subprocess32.CalledProcessError: Command 'javac -cp "/tmp/localstack_install_dir/localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-core-2.6.7.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.9.0.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/guava-18.0.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpclient-4.5.2.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-codec-1.9.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-lang-2.6.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpcore-4.4.4.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-databind-2.6.7.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jmespath-java-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.7.jar:/tmp/localstack_install_dir/localstack/utils/kinesis/java" /tmp/localstack_install_dir/localstack/utils/kinesis/java/com/atlassian/*.java' returned non-zero exit status 127
make: *** [install] Error 1

	at cloud.localstack.Localstack.exec(Localstack.java:346)
	at cloud.localstack.Localstack.exec(Localstack.java:314)
	at cloud.localstack.Localstack.ensureInstallation(Localstack.java:247)
	at cloud.localstack.Localstack.setupInfrastructure(Localstack.java:353)
	at cloud.localstack.LocalstackTestRunner.run(LocalstackTestRunner.java:24)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.lang.IllegalStateException: Failed to run command 'bash -c cd "/tmp/localstack_install_dir"; make install', return code 2.
STDOUT: (test `which virtualenv` || pip install --user virtualenv) && \
	(test -e .venv || virtualenv  .venv) && \
	(test ! -e requirements.txt || (. .venv/bin/activate; pip -q install -r requirements.txt) && \
	. .venv/bin/activate; PYTHONPATH=. exec python localstack/services/install.py testlibs)
ERROR: 'javac -cp "/tmp/localstack_install_dir/localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-core-2.6.7.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.9.0.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/guava-18.0.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpclient-4.5.2.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-codec-1.9.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-lang-2.6.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpcore-4.4.4.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-databind-2.6.7.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jmespath-java-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.7.jar:/tmp/localstack_install_dir/localstack/utils/kinesis/java" /tmp/localstack_install_dir/localstack/utils/kinesis/java/com/atlassian/*.java': exit code 127; output: /bin/sh: 1: javac: not found

Makefile:14: recipe for target 'install' failed

STDERR: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Traceback (most recent call last):
  File "localstack/services/install.py", line 222, in <module>
    install_amazon_kinesis_client_libs()
  File "localstack/services/install.py", line 145, in install_amazon_kinesis_client_libs
    run('javac -cp "%s" %s' % (classpath, java_files))
  File "/tmp/localstack_install_dir/localstack/utils/common.py", line 847, in run
    return do_run(cmd)
  File "/tmp/localstack_install_dir/localstack/utils/common.py", line 844, in do_run
    raise e
subprocess32.CalledProcessError: Command 'javac -cp "/tmp/localstack_install_dir/localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-core-2.6.7.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.9.0.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/guava-18.0.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpclient-4.5.2.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-codec-1.9.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/commons-lang-2.6.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/httpcore-4.4.4.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-databind-2.6.7.1.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jmespath-java-1.11.272.jar:/tmp/localstack_install_dir/.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.7.jar:/tmp/localstack_install_dir/localstack/utils/kinesis/java" /tmp/localstack_install_dir/localstack/utils/kinesis/java/com/atlassian/*.java' returned non-zero exit status 127
make: *** [install] Error 1

	at cloud.localstack.Localstack.exec(Localstack.java:332)
	... 10 more
```

**Issue 2:**

```
import org.junit.runner.RunWith;

import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.model.Bucket;

import antlr.collections.List;
import cloud.localstack.LocalstackTestRunner;
import cloud.localstack.TestUtils;
import cloud.localstack.docker.LocalstackDockerTestRunner;

@RunWith(**LocalstackDockerTestRunner**.class)
public class Test {

  public static final String TEST_ACCESS_KEY = "test";
  public static final String TEST_SECRET_KEY = "test";
  public static final AWSCredentials TEST_CREDENTIALS = new BasicAWSCredentials(TEST_ACCESS_KEY, TEST_SECRET_KEY);

  @org.junit.Test
  public void Test() {
    AmazonS3 s3 = TestUtils.getClientS3();
    java.util.List<Bucket> buckets = s3.listBuckets();
  }

}
```
Stack trace:
```INFO: Waiting for localstack container to be ready...
Apr 26, 2019 4:41:22 PM cloud.localstack.docker.Container stop
INFO: Stopped container: 06cb1e5bbb8691682339637032d8953847cfb8d400c63e68c704229deaa549e7
/usr/bin/docker: Error response from daemon: driver failed programming external connectivity on endpoint confident_torvalds (b44319f2a4ad16a523144816d96c4a059a05e87888b33dce1cb4e44da74f9f77): Error starting userland proxy: listen tcp 0.0.0.0:4583: bind: address already in use.
Apr 26, 2019 4:41:22 PM cloud.localstack.docker.Container stop
INFO: Stopped container: 06cb1e5bbb8691682339637032d8953847cfb8d400c63e68c704229deaa549e7
/usr/bin/docker: Error response from daemon: driver failed programming external connectivity on endpoint confident_torvalds (b44319f2a4ad16a523144816d96c4a059a05e87888b33dce1cb4e44da74f9f77): Error starting userland proxy: listen tcp 0.0.0.0:4583: bind: address already in use.
cloud.localstack.docker.exception.LocalstackDockerException: Could not start the localstack docker container.
	at cloud.localstack.docker.LocalstackDocker.startup(LocalstackDocker.java:77)
	at cloud.localstack.docker.LocalstackDockerTestRunner.run(LocalstackDockerTestRunner.java:42)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.lang.IllegalStateException: Could not find token: Ready\. in docker logs.
	at cloud.localstack.docker.Container.waitForLogToken(Container.java:129)
	at cloud.localstack.docker.LocalstackDocker.startup(LocalstackDocker.java:74)
	... 7 more
```

Can some one pls help me kick start with local stack?
Also is there a good documentation for local stack?

**Comment by chalocodekare** [comment]
Even I am seeing this issue
This is with the latest docker image [localstack/localstack@sha256:a2b7c1d4d21cfa6558739956f0fdeec46bc43c84410522717e25de0535d7aafb]

```
cloud.localstack.docker.exception.LocalstackDockerException: Could not start the localstack docker container.
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
Caused by: java.lang.IllegalStateException: Could not find token: Ready\. in docker logs.
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
```

**Comment by coreymeadln** [comment]
I am getting this error as well with version 0.1.21.  It looks like there's potentially an issue with how the period is being escaped at https://github.com/localstack/localstack/blob/8b5b92280f843ed7a077483af60b9951693396d8/localstack/ext/java/src/main/java/cloud/localstack/docker/LocalstackDocker.java

`private static final Pattern READY_TOKEN = Pattern.compile("Ready\\.");`

I'm guessing it should be just a single backslash?

`private static final Pattern READY_TOKEN = Pattern.compile("Ready\.");`

Though I'm not sure how to test if that's actually the fix, so any advice would be helpful.

Here are the docker logs from the container so I can confirm that the container did successfully come up and it's not an issue with the container.  See the "Ready." statement at the bottom.

$ docker logs 0066f4d39cda
Waiting for all LocalStack services to be ready
2019-05-14 19:13:25,926 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-05-14 19:13:25,932 INFO supervisord started with pid 11
2019-05-14 19:13:26,938 INFO spawned: 'dashboard' with pid 18
2019-05-14 19:13:26,941 INFO spawned: 'infra' with pid 19
2019-05-14 19:13:26,956 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; bin/localstack web)
(. .venv/bin/activate; exec bin/localstack start)
2019-05-14 19:13:27,958 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting local dev environment. CTRL-C to quit.
Starting mock S3 (http port 4572)...
Starting mock CloudFormation (http port 4581)...
Waiting for all LocalStack services to be ready
Ready.

**Comment by aesteve** [comment]
I got the same error, too.

I'm pretty sure the fix you're mentioning doesn't compile, though, unfortunately :(

```
jshell> Pattern p = Pattern.compile("Ready\.");
|  Error:
|  illegal escape character
|  Pattern p = Pattern.compile("Ready\.");
```

**Comment by artembilan** [comment]
Just for an info: I've managed to run it with this:
```
@LocalstackDockerProperties(randomizePorts = true, services = { "sqs", "kinesis", "s3", "sns", "dynamodb", "cloudwatch" })
```
This is a set of services I need in https://github.com/spring-projects/spring-integration-aws project.

After some debugging on the:
```
    private boolean logContainsPattern(Pattern pattern) {
        String logs = new LogCommand(containerId).withNumberOfLines(NUM_LOG_LINES).execute();
        return pattern.matcher(logs).find();
    }
```
I have realized that *ElasticSearch* is not able to start, so i decided to try with some minimal required set of services.

Works on Linux as well as on Windows.

**Comment by whummer** [comment]
Thanks for reporting @Muraligowtham @chalocodekare @coreymeadln @aesteve @artembilan .

Can you please try upgrading to the latest version `0.2.0` of the localstack-utils Maven module. The code has been significantly refactored, and execution in Docker is now the default method. The previous version of the `LocalstackTestRunner` JUnit test runner (the one that installs the LocalStack dependencies on the local machine) has been deprecated.

> Error starting userland proxy: listen tcp 0.0.0.0:4583: bind: address already in use.

@Muraligowtham Please ensure that the port is available and no LocalStack background processes/containers are still running.

Regarding the `"Ready\\."` issue - if this problem persists in the latest version, please report here with a small sample to reproduce this error. Thanks!
