### ISSUE TITLE
Localstack docker failed starting in version 0.9.2

### ISSUE THREAD

**Issue by zhiweil** [localstack/localstack#1297]
Localstack failed starting by docker-compose this morning (with docker tag 0.9.2). The same code worked for version 0.9.1. The error shown in the log file:

```
Waiting for all LocalStack services to be ready
2019-05-08T22:24:52:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4561): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f739d97ecd0>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 220, in forward
    headers=modified_request.headers, stream=True)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4561): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f739d97ecd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
 
```

**Comment by whummer** [comment]
Seems to be fixed in the meantime - can you please give it a try with the `latest` version @zhiweil ? thanks

**Comment by zhiweil** [comment]
Hi Whummer, I tried with the "latest" version, the problem has gone away. I'm going to close this task. 

Regards
Zhiwei
