### ISSUE TITLE
AWS Java SDK trown "The Content-MD5 you specified was invalid" while working with s3 localstack

### ISSUE THREAD

**Issue by asaushkin** [localstack/localstack#1307]
There are two almost identical methods - `testS3localstack` and `tests3aws`. Both of it do the same thing - create a bucket and put an object into it. The difference in the endpoint configuration. The first one uses localstack as s3 backend and the second one establish connection the real aws s3.

```java
public class TestS3Client {

    final static AwsClientBuilder.EndpointConfiguration S3_ENDPOINT_CONFIGURATION
            = new AwsClientBuilder.EndpointConfiguration("http://localhost:4572", "us-east-1");

    // This method throws an error
    @Test
    public void testS3localstack() {

        final AmazonS3Client s3client = (AmazonS3Client) AmazonS3ClientBuilder.standard()
                .withEndpointConfiguration(S3_ENDPOINT_CONFIGURATION)
                .build();

        s3client.createBucket("my-bucket-euayayyyaya");

        s3client.putObject("my-bucket-euayayyyaya", "my-password",
                new File("/etc/passwd"));


        assertNotNull(s3client);
    }

    //This method works without any problems
    @Test
    public void tests3aws() {

        final AmazonS3Client s3client = (AmazonS3Client) AmazonS3ClientBuilder.standard()
                .withRegion("us-west-2")
                .build();

        s3client.createBucket("my-bucket-euayayyyaya");

        s3client.putObject("my-bucket-euayayyyaya", "my-password",
                new File("/etc/passwd"));
        assertNotNull(s3client);
    }

}
```

The first method throws an exception... 

```
com.amazonaws.services.s3.model.AmazonS3Exception: The Content-MD5 you specified was invalid (Service: Amazon S3; Status Code: 400; Error Code: InvalidDigest; Request ID: null; S3 Extended Request ID: null)
, S3 Extended Request ID: null
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4325)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4272)
    at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1749)
    at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1604)
    at me.asaushkin.TestS3Client.testS3localstack(TestS3Client.java:26)
    ...
```

Localstack has been running as: `SERVICES=s3 DEBUG=1 localstack start` in virtualenv (without docker)
Localstack version tested: 0.9.1, 0.9.0
AWS SDK: 1.11.253 (I've just tested it with the latest java sdk - 1.11.550 but it also has no effect).

Could anybody give me a piece of advice about why this exception happen?

**Comment by 14423** [comment]
Hi Iam also facing the same issue. please let me know if it is resolved

**Comment by whummer** [comment]
Thanks for reporting @asaushkin . I was able to run your test - only had to make a slight extension to the S3 client (enabling `withPathStyleAccessEnabled`):
```
final AmazonS3Client s3client = (AmazonS3Client) AmazonS3ClientBuilder.standard()
                .withEndpointConfiguration(S3_ENDPOINT_CONFIGURATION)
                .withPathStyleAccessEnabled(true)
                .build();
```
Can you try again with the `latest` version of the Docker image (version `0.9.5`)?

**Comment by asaushkin** [comment]
Yes, currently it works as expected, thank you!
