### ISSUE TITLE
Error with running localstack in mhart/alpine-node:5.11 for s3

### ISSUE THREAD

**Issue by ww-jesusaguilar** [localstack/localstack#1334]
```
core-localstack-asdf | Starting localstack server for s3
core-localstack-asdf | 2019-05-27T19:16:16:INFO:localstack.services.install: Downloading and installing LocalStack Java libraries. This may take some time.
core-localstack-asdf | Starting local dev environment. CTRL-C to quit.
core-localstack-asdf | Starting mock S3 (http port 4572)...
core-localstack-asdf | 2019-05-27T19:16:39:WARNING:infra.py: Service "s3" not yet available, retrying...
core-localstack-asdf | 2019-05-27T19:18:04:ERROR:localstack.services.s3.s3_starter: S3 health check failed:  Traceback (most recent call last):
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 411, in check_infra
core-localstack-asdf |     raise e
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 408, in check_infra
core-localstack-asdf |     plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 93, in check
core-localstack-asdf |     return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/s3/s3_starter.py", line 32, in check_s3
core-localstack-asdf |     assert isinstance(out['Buckets'], list)
core-localstack-asdf | TypeError: 'NoneType' object is not subscriptable
core-localstack-asdf |
core-localstack-asdf | During handling of the above exception, another exception occurred:
core-localstack-asdf |
core-localstack-asdf | Traceback (most recent call last):
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 611, in start_infra
core-localstack-asdf |     check_infra(apis=apis)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 420, in check_infra
core-localstack-asdf |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 420, in check_infra
core-localstack-asdf |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 420, in check_infra
core-localstack-asdf |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 420, in check_infra
core-localstack-asdf |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 420, in check_infra
core-localstack-asdf |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 420, in check_infra
core-localstack-asdf |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 420, in check_infra
core-localstack-asdf |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 420, in check_infra
core-localstack-asdf |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 420, in check_infra
core-localstack-asdf |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 420, in check_infra
core-localstack-asdf |     check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 418, in check_infra
core-localstack-asdf |     raise e
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 411, in check_infra
core-localstack-asdf |     raise e
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 408, in check_infra
core-localstack-asdf |     plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 93, in check
core-localstack-asdf |     return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/s3/s3_starter.py", line 32, in check_s3
core-localstack-asdf |     assert isinstance(out['Buckets'], list)
core-localstack-asdf | TypeError: 'NoneType' object is not subscriptable
core-localstack-asdf |
core-localstack-asdf | ERROR: 'NoneType' object is not subscriptable
core-localstack-asdf exited with code 1
```

docker-compose.yml

```
version: '2.1'

services:
  core-localstack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: core-localstack-asdf
    ports:
      - "4568-4584:4568-4584"
      - "8055:8080"
    environment:
      - SERVICES=s3
      - LOCALSTACK_DATA_DIR=/var/lib/localstack/data
      - LOCALSTACK_DEFAULT_REGION=us-east-1
      - LOCALSTACK_HOSTNAME=core-localstack-asdf
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
```

Docker file:

```
FROM mhart/alpine-node:5.11

EXPOSE 8080 8055 4572 443 80

ENV DATADIR /var/lib/localstack

## temporal variables
ENV LSTACK_HOST localstack-server
ENV LSTACK_PORT 4572
ENV LSTACK_BUCKET demo-bucket
ENV LSTACK_SERVICES s3

#ENV AWS_DEFAULT_REGION us-east-1
ENV AWS_ACCESS_KEY_ID foo
ENV AWS_SECRET_ACCESS_KEY foo

# Variables for localstack services
ENV LOCALSTACK_SERVICES $LSTACK_SERVICES
ENV LOCALSTACK_DEBUG 1
ENV LOCALSTACK_DATA_DIR /var/lib/localstack/data
ENV LOCALSTACK_DEFAULT_REGION us-east-1
ENV LOCALSTACK_HOSTNAME core-localstack

# Dependencies for localstack
RUN apk --no-cache update && \
    apk --no-cache add bash && \
    apk --no-cache add openjdk8-jre && \
    apk --no-cache add python3 python3-dev libstdc++ openssl-dev linux-headers libffi-dev clang make g++ gcc curl groff less && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 --no-cache-dir install --upgrade pip wheel && \
    pip3 --no-cache-dir install -U setuptools && \
    pip3 --no-cache-dir install psutil awscli urllib3 python-coveralls cfn-lint==0.20.0 && \
    rm -rf /var/cache/apk/*

ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk/jre
ENV PATH $PATH:$JAVA_HOME/bin

ENV MAVEN_VERSION 3.5.4

RUN wget http://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz && \
    tar -zxvf apache-maven-${MAVEN_VERSION}-bin.tar.gz && \
    rm apache-maven-${MAVEN_VERSION}-bin.tar.gz && \
    mv apache-maven-${MAVEN_VERSION} /usr/lib/mvn

ENV MAVEN_HOME /usr/lib/mvn
ENV PATH $PATH:$MAVEN_HOME/bin

RUN mkdir $DATADIR

ENV ELASTIC_VERSION 7.1.0

RUN wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ELASTIC_VERSION}-linux-x86_64.tar.gz && \
    tar -zxvf elasticsearch-${ELASTIC_VERSION}-linux-x86_64.tar.gz && \
    rm elasticsearch-${ELASTIC_VERSION}-linux-x86_64.tar.gz && \
    mv elasticsearch-${ELASTIC_VERSION} $DATADIR

ENV ES_HOME ${DATADIR}/elasticsearch-${ELASTIC_VERSION}
ENV PATH $PATH:$ES_HOME/bin

RUN ls $DATADIR

RUN ls ${DATADIR}/elasticsearch-${ELASTIC_VERSION}/bin

RUN ${DATADIR}/elasticsearch-${ELASTIC_VERSION}/bin/elasticsearch-plugin install analysis-icu

RUN pip3 --no-cache-dir install localstack

WORKDIR $DATADIR

VOLUME $DATADIR

COPY scripts/localstack_init.sh ${DATADIR}/localstack_init.sh

CMD ["./localstack_init.sh"]
```
localstackinit.sh have the next code:

```
#!/bin/sh

echo -e "Starting localstack server for $LOCALSTACK_SERVICES"

localstack start
```

How this can be solved?

**Comment by ww-jesusaguilar** [comment]
Also if i don't specify the service, obtain:

```
core-localstack-asdf | 2019-05-27T20:08:24:INFO:localstack.services.install: Downloading and installing local DynamoDB server. This may take some time.
core-localstack-asdf | 2019-05-27T20:08:24:INFO:localstack.services.install: Downloading and installing local Elasticsearch server. This may take some time.
core-localstack-asdf | 2019-05-27T20:08:24:INFO:localstack.services.install: Downloading and installing local ElasticMQ server. This may take some time.
core-localstack-asdf | 2019-05-27T20:08:24:INFO:localstack.services.install: Downloading and installing local Kinesis server. This may take some time.
core-localstack-asdf | 2019-05-27T20:08:24:INFO:localstack.services.install: Downloading and installing local Step Functions server. This may take some time.
core-localstack-asdf | Starting local dev environment. CTRL-C to quit.
core-localstack-asdf | ERROR: 'cd "/usr/lib/python3.5/site-packages/localstack" && npm install': exit code 1; output: b'npm WARN deprecated node-uuid@1.4.8: Use uuid module instead\n\n> leveldown@4.0.2 install /usr/lib/python3.5/site-packages/localstack/node_modules/kinesalite/node_modules/leveldown\n> prebuild-install || node-gyp rebuild\n\nprebuild-install WARN install No prebuilt binaries found (target=5.11.1 runtime=node arch=x64 libc=musl platform=linux)\ngyp ERR! configure error \ngyp ERR! stack Error: Can\'t find Python executable "python", you can set the PYTHON env variable.\ngyp ERR! stack     at failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:401:14)\ngyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:330:11\ngyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:63:16)\ngyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:72:29)\ngyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:81:16\ngyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5\ngyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5\ngyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)\ngyp ERR! System Linux 4.9.125-linuxkit\ngyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"\ngyp ERR! cwd /usr/lib/python3.5/site-packages/localstack/node_modules/kinesalite/node_modules/leveldown\ngyp ERR! node -v v5.11.1\ngyp ERR! node-gyp -v v3.3.1\ngyp ERR! not ok \nnpm WARN install:leveldown@4.0.2 leveldown@4.0.2 install: `prebuild-install || node-gyp rebuild`\nnpm WARN install:leveldown@4.0.2 Exit status 1\n\n> leveldown@3.0.1 install /usr/lib/python3.5/site-packages/localstack/node_modules/leveldown\n> prebuild-install || node-gyp rebuild\n\nprebuild-install WARN install No prebuilt binaries found (target=5.11.1 runtime=node arch=x64 platform=linux)\ngyp ERR! configure error \ngyp ERR! stack Error: Can\'t find Python executable "python", you can set the PYTHON env variable.\ngyp ERR! stack     at failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:401:14)\ngyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:330:11\ngyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:63:16)\ngyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:72:29)\ngyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:81:16\ngyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5\ngyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5\ngyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)\ngyp ERR! System Linux 4.9.125-linuxkit\ngyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"\ngyp ERR! cwd /usr/lib/python3.5/site-packages/localstack/node_modules/leveldown\ngyp ERR! node -v v5.11.1\ngyp ERR! node-gyp -v v3.3.1\ngyp ERR! not ok \nlocalstack@0.0.1 /usr/lib/python3.5/site-packages/localstack\n`-- kinesalite@1.14.0 \n  +-- async@2.6.2 \n  | `-- lodash@4.17.11 \n  +-- bignumber.js@7.2.1 \n  +-- lazy@1.0.11 \n  +-- level-sublevel@6.6.5 \n  | +-- bytewise@1.1.0 \n  | | +-- bytewise-core@1.2.3 \n  | | | `-- typewise-core@1.2.0 \n  | | `-- typewise@1.0.3 \n  | +-- levelup@0.19.1 \n  | | +-- bl@0.8.2 \n  | | +-- deferred-leveldown@0.2.0 \n  | | | `-- abstract-leveldown@0.12.4 \n  | | |   `-- xtend@3.0.0 \n  | | +-- errno@0.1.7 \n  | | | `-- prr@1.0.1 \n  | | +-- prr@0.0.0 \n  | | +-- readable-stream@1.0.34 \n  | | | +-- core-util-is@1.0.2 \n  | | | +-- isarray@0.0.1 \n  | | | `-- string_decoder@0.10.31 \n  | | +-- semver@5.1.1 \n  | | `-- xtend@3.0.0 \n  | +-- ltgt@2.1.3 \n  | +-- pull-defer@0.2.3 \n  | +-- pull-level@2.0.4 \n  | | +-- level-post@1.0.7 \n  | | +-- pull-cat@1.1.11 \n  | | +-- pull-live@1.0.1 \n  | | +-- pull-pushable@2.2.0 \n  | | +-- pull-window@2.1.4 \n  | | | `-- looper@2.0.0 \n  | | `-- stream-to-pull-stream@1.7.3 \n  | |   `-- looper@3.0.0 \n  | +-- pull-stream@3.6.11 \n  | +-- typewiselite@1.0.0 \n  | `-- xtend@4.0.1 \n  +-- levelup@3.1.1 \n  | +-- deferred-leveldown@4.0.2 \n  | | `-- abstract-leveldown@5.0.0 \n  | +-- level-errors@2.0.1 \n  | `-- level-iterator-stream@3.0.1 \n  |   `-- readable-stream@2.3.6 \n  |     +-- isarray@1.0.0 \n  |     +-- process-nextick-args@2.0.0 \n  |     +-- string_decoder@1.1.1 \n  |     `-- util-deprecate@1.0.2 \n  +-- lock@1.1.0 \n  +-- memdown@3.0.0 \n  | +-- abstract-leveldown@5.0.0 \n  | +-- functional-red-black-tree@1.0.1 \n  | +-- immediate@3.2.3 \n  | +-- inherits@2.0.3 \n  | +-- ltgt@2.2.1 \n  | `-- safe-buffer@5.1.2 \n  +-- minimist@1.2.0 \n  +-- node-uuid@1.4.8 \n  `-- once@1.4.0 \n    `-- wrappy@1.0.2 \n\nnpm WARN localstack@0.0.1 No repository field.\nnpm WARN localstack@0.0.1 No license field.\nnpm ERR! Linux 4.9.125-linuxkit\nnpm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"\nnpm ERR! node v5.11.1\nnpm ERR! npm  v3.8.9\nnpm ERR! code ELIFECYCLE\n\nnpm ERR! leveldown@3.0.1 install: `prebuild-install || node-gyp rebuild`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the leveldown@3.0.1 install script \'prebuild-install || node-gyp rebuild\'.\nnpm ERR! Make sure you have the latest version of node.js and npm installed.\nnpm ERR! If you do, this is most likely a problem with the leveldown package,\nnpm ERR! not with npm itself.\nnpm ERR! Tell the author that this fails on your system:\nnpm ERR!     prebuild-install || node-gyp rebuild\nnpm ERR! You can get information on how to open an issue for this project with:\nnpm ERR!     npm bugs leveldown\nnpm ERR! Or if that isn\'t available, you can get their info via:\nnpm ERR!     npm owner ls leveldown\nnpm ERR! There is likely additional logging output above.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /usr/lib/python3.5/site-packages/localstack/npm-debug.log\n'
core-localstack-asdf | Error starting infrastructure: Command 'cd "/usr/lib/python3.5/site-packages/localstack" && npm install' returned non-zero exit status 1 Traceback (most recent call last):
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/infra.py", line 594, in start_infra
core-localstack-asdf |     install.install_components(apis)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/install.py", line 169, in install_components
core-localstack-asdf |     parallelize(install_component, names)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/utils/common.py", line 991, in parallelize
core-localstack-asdf |     result = pool.map(func, list)
core-localstack-asdf |   File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
core-localstack-asdf |     return self._map_async(func, iterable, mapstar, chunksize).get()
core-localstack-asdf |   File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
core-localstack-asdf |     raise self._value
core-localstack-asdf |   File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
core-localstack-asdf |     result = (True, func(*args, **kwds))
core-localstack-asdf |   File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
core-localstack-asdf |     return list(map(*args))
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/install.py", line 165, in install_component
core-localstack-asdf |     installer()
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/services/install.py", line 83, in install_kinesalite
core-localstack-asdf |     run('cd "%s" && npm install' % ROOT_PATH)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/utils/common.py", line 852, in run
core-localstack-asdf |     return do_run(cmd)
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/utils/common.py", line 849, in do_run
core-localstack-asdf |     raise e
core-localstack-asdf |   File "/usr/lib/python3.5/site-packages/localstack/utils/common.py", line 812, in do_run
core-localstack-asdf |     output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
core-localstack-asdf |   File "/usr/lib/python3.5/subprocess.py", line 629, in check_output
core-localstack-asdf |     **kwargs).stdout
core-localstack-asdf |   File "/usr/lib/python3.5/subprocess.py", line 711, in run
core-localstack-asdf |     output=stdout, stderr=stderr)
core-localstack-asdf | subprocess.CalledProcessError: Command 'cd "/usr/lib/python3.5/site-packages/localstack" && npm install' returned non-zero exit status 1
core-localstack-asdf |
core-localstack-asdf | ERROR: Command 'cd "/usr/lib/python3.5/site-packages/localstack" && npm install' returned non-zero exit status 1
core-localstack-asdf exited with code 1
```

**Comment by whummer** [comment]
Thanks for reporting @ww-jesusaguilar . I'm assuming you are aware that LocalStack is provided as a Docker image [`localstack/localstack`](https://hub.docker.com/r/localstack/localstack). Would it be an option to use that as the base image, and then add any customizations, if needed?
