### ISSUE TITLE
Connection Error Calling S3 From Lambda When Using LOCALSTACK_HOSTNAME

### ISSUE THREAD

**Issue by kevinswarner** [localstack/localstack#1359]
I am having trouble calling S3 running in Localstack from Lambda running in Localstack. I have seen many issues related to this online, and have attempted to resolve the issue following the suggestions in those issues, but am still having problems.

I have created a simple project to illustrate the issue.

https://github.com/kevinswarner/localstack-test

### TLDR;

I am getting an error "connect ECONNREFUSED 172.17.0.1:4572". I am using LOCALSTACK_HOSTNAME to build the endpoint to S3 in my Lambda. It looks like LOCALSTACK_HOSTMAME is "172.17.0.1".

I was under the impression that this should use the bridge from the lambda Docker container to the host that is running the other localstack services. I am not a Docker expert by any means, so I may be missing something.

### Environment

- Mac OSX Mojave 10.14.5
- 16 GB Memory
- Docker version 18.09.2, build 6247962
- Localstack version 0.9.1
- serverless version 1.44.1
- serverless-localstack version 0.4.15
- aws-sdk version 2.467.0

### Starting Localstack

I am starting localstack like this...

```
$ LAMBDA_EXECUTOR=Docker SERVICES=lambda,cloudformation,s3,sts localstack start
Starting local dev environment. CTRL-C to quit.
Starting mock CloudWatch Logs (http port 4586)...
Starting mock CloudFormation (http port 4581)...
Starting mock S3 (http port 4572)...
Starting mock STS (http port 4592)...
Starting mock Lambda service (http port 4574)...
 * Serving Flask app "lambda_api" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Ready.
```

I have tested that I can access Localstack S3 from my system at http://localhost:4572.

### Deploying Lambda Using Serverless Localstack Plugin

My serverless.yml file...

```
service: localstack-test

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-localstack

custom:
  localstack:
    host: http://localhost
    autostart: false
    stages:
      - local
    lambda:
      mountCode: true

functions:
  listBuckets:
    handler: index.handler
```

Next, I deploy my lambda using the serverless-localstack plugin with serverless. Note I am using an AWS profile for dummy credentials.

```
$ SLS_DEBUG=* AWS_PROFILE=foobar sls deploy -s local
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command deploy
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Using serverless-localstack
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Skip plugin function Package.packageService (lambda.mountCode flag is enabled)
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
Serverless: Invoke aws:common:validate
Serverless: Skip plugin function AwsDeploy.extendedValidate (lambda.mountCode flag is enabled)
Serverless: Invoke aws:deploy:deploy
Serverless: [AWS cloudformation 400 0.033s 0 retries] describeStacks({ StackName: 'localstack-test-local' })
Serverless: Creating Stack...
Serverless: [AWS cloudformation 200 0.158s 0 retries] createStack({ StackName: 'localstack-test-local',
  OnFailure: 'DELETE',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateBody: '{"AWSTemplateFormatVersion":"2010-09-09","Description":"The AWS CloudFormation template for this Serverless application","Resources":{"ServerlessDeploymentBucket":{"Type":"AWS::S3::Bucket","Properties":{"BucketEncryption":{"ServerSideEncryptionConfiguration":[{"ServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}}}},"Outputs":{"ServerlessDeploymentBucketName":{"Value":{"Ref":"ServerlessDeploymentBucket"}}}}',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ] })
Serverless: Checking Stack create progress...
Serverless: [AWS cloudformation 200 0.015s 0 retries] describeStackEvents({ StackName: 'arn:aws:cloudformation:us-east-1:123456789:stack/localstack-test-local/8fdb8514-8291-4a7c-a64c-4037354981c7' })
..
Serverless: Stack create finished...
Serverless: [AWS cloudformation 200 0.014s 0 retries] describeStackResource({ StackName: 'localstack-test-local',
  LogicalResourceId: 'ServerlessDeploymentBucket' })
Serverless: [AWS s3 200 0.013s 0 retries] listObjectsV2({ Bucket: 'localstack-test-local-ServerlessDeploymentBucket-81482A-Z502883',
  Prefix: 'serverless/localstack-test/local' })
Serverless: [AWS sts 200 0.019s 0 retries] getCallerIdentity({})
Serverless: Uploading CloudFormation file to S3...
Serverless: [AWS s3 200 0.01s 0 retries] putObject({ Body: <Buffer 7b 22 41 57 53 54 65 6d 70 6c 61 74 65 46 6f 72 6d 61 74 56 65 72 73 69 6f 6e 22 3a 22 32 30 31 30 2d 30 39 2d 30 39 22 2c 22 44 65 73 63 72 69 70 74 ... >,
  Bucket: 'localstack-test-local-ServerlessDeploymentBucket-81482A-Z502883',
  Key: 'serverless/localstack-test/local/1559773087226-2019-06-05T22:18:07.226Z/compiled-cloudformation-template.json',
  ContentType: 'application/json',
  Metadata: { filesha256: 'fLFRDAANCpPTFNU2C14ZoFiuXoPHv0BMdwqfkeHZZFo=' } })
Serverless: Skip plugin function AwsDeploy.uploadFunctionsAndLayers (lambda.mountCode flag is enabled)
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
Serverless: [AWS cloudformation 200 0.252s 0 retries] updateStack({ StackName: 'localstack-test-local',
  Capabilities: [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', [length]: 2 ],
  Parameters: [ [length]: 0 ],
  TemplateURL: 'https://s3.amazonaws.com/localstack-test-local-ServerlessDeploymentBucket-81482A-Z502883/serverless/localstack-test/local/1559773087226-2019-06-05T22:18:07.226Z/compiled-cloudformation-template.json',
  Tags: [ { Key: 'STAGE', Value: 'local' }, [length]: 1 ] })
Serverless: Checking Stack update progress...
Serverless: [AWS cloudformation 200 0.018s 0 retries] describeStackEvents({ StackName: 'arn:aws:cloudformation:us-east-1:123456789:stack/localstack-test-local/8fdb8514-8291-4a7c-a64c-4037354981c7' })
..
Serverless: Stack update finished...
Serverless: Invoke aws:info
Serverless: [AWS cloudformation 200 0.022s 0 retries] describeStacks({ StackName: 'localstack-test-local' })
Serverless: [AWS cloudformation 200 0.016s 0 retries] listStackResources({ StackName: 'localstack-test-local' })
Service Information
service: localstack-test
stage: local
region: us-east-1
stack: localstack-test-local
resources: 5
api keys:
  None
endpoints:
  None
functions:
  listBuckets: localstack-test-local-listBuckets
layers:
  None
Serverless: Invoke aws:deploy:finalize
Serverless: [AWS s3 200 0.007s 0 retries] listObjectsV2({ Bucket: 'localstack-test-local-ServerlessDeploymentBucket-81482A-Z502883',
  Prefix: 'serverless/localstack-test/local' })
Serverless Enterprise: Run `serverless login` and deploy again to explore, monitor, secure your serverless project for free.
```

My lambda function is...

```
const AWS = require('aws-sdk');

module.exports.handler = () => {
  return new Promise((resolve, reject) => {
    const { LOCALSTACK_HOSTNAME } = process.env;
    const s3 = new AWS.S3({ endpoint: `http://${LOCALSTACK_HOSTNAME}:4572` });
    s3.listBuckets()
      .promise()
      .then(results => {
        console.log(results);
        resolve(results);
      })
      .catch(err => {
        console.log(err);
        reject(err);
      });
  });
};
```

### Invoking the Lamnda

Finally, I attempt to invoke the lambda by running the test file.

```
$ AWS_PROFILE=foobar node test.js
{ InternalFailure: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:localstack-test-local-listBuckets: Lambda process returned error status code: 1. Output:
START RequestId: 0cc05d90-6d72-1cc5-a959-05232d98acfb Version: $LATEST
2019-06-05T22:22:56.818Z	0cc05d90-6d72-1cc5-a959-05232d98acfb	{ Error: connect ECONNREFUSED 172.17.0.1:4572
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  message: 'connect ECONNREFUSED 172.17.0.1:4572',
  code: 'NetworkingError',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.17.0.1',
  port: 4572,
  region: 'us-east-1',
  hostname: '172.17.0.1',
  retryable: true,
  time: 2019-06-05T22:22:56.817Z }
2019-06-05T22:22:56.825Z	0cc05d90-6d72-1cc5-a959-05232d98acfb	{"errorMessage":"connect ECONNREFUSED 172.17.0.1:4572","errorType":"NetworkingError","stackTrace":["Object._errnoException (util.js:1022:11)","_exceptionWithHostPort (util.js:1044:20)","TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)"]}
END RequestId: 0cc05d90-6d72-1cc5-a959-05232d98acfb
REPORT RequestId: 0cc05d90-6d72-1cc5-a959-05232d98acfb	Duration: 1698.90 ms	Billed Duration: 1700 ms	Memory Size: 1536 MB	Max Memory Used: 43 MB	 Traceback (most recent call last):
  File "/Users/kevinwarner/Library/Python/2.7/lib/python/site-packages/localstack/services/awslambda/lambda_api.py", line 311, in run_lambda
    event, context=context, version=version, asynchronous=asynchronous)
  File "/Users/kevinwarner/Library/Python/2.7/lib/python/site-packages/localstack/services/awslambda/lambda_executors.py", line 58, in execute
    result, log_output = self._execute(func_arn, func_details, event, context, version, asynchronous)
  File "/Users/kevinwarner/Library/Python/2.7/lib/python/site-packages/localstack/services/awslambda/lambda_executors.py", line 201, in _execute
    result, log_output = self.run_lambda_executor(cmd, environment, asynchronous)
  File "/Users/kevinwarner/Library/Python/2.7/lib/python/site-packages/localstack/services/awslambda/lambda_executors.py", line 133, in run_lambda_executor
    (return_code, log_output))
Exception: Lambda process returned error status code: 1. Output:
START RequestId: 0cc05d90-6d72-1cc5-a959-05232d98acfb Version: $LATEST
2019-06-05T22:22:56.818Z	0cc05d90-6d72-1cc5-a959-05232d98acfb	{ Error: connect ECONNREFUSED 172.17.0.1:4572
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  message: 'connect ECONNREFUSED 172.17.0.1:4572',
  code: 'NetworkingError',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.17.0.1',
  port: 4572,
  region: 'us-east-1',
  hostname: '172.17.0.1',
  retryable: true,
  time: 2019-06-05T22:22:56.817Z }
2019-06-05T22:22:56.825Z	0cc05d90-6d72-1cc5-a959-05232d98acfb	{"errorMessage":"connect ECONNREFUSED 172.17.0.1:4572","errorType":"NetworkingError","stackTrace":["Object._errnoException (util.js:1022:11)","_exceptionWithHostPort (util.js:1044:20)","TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)"]}
END RequestId: 0cc05d90-6d72-1cc5-a959-05232d98acfb
REPORT RequestId: 0cc05d90-6d72-1cc5-a959-05232d98acfb	Duration: 1698.90 ms	Billed Duration: 1700 ms	Memory Size: 1536 MB	Max Memory Used: 43 MB

    at Object.extractError (/Users/kevinwarner/Documents/Projects/logicbox/localstack-test/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/Users/kevinwarner/Documents/Projects/logicbox/localstack-test/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/Users/kevinwarner/Documents/Projects/logicbox/localstack-test/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/kevinwarner/Documents/Projects/logicbox/localstack-test/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/kevinwarner/Documents/Projects/logicbox/localstack-test/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/kevinwarner/Documents/Projects/logicbox/localstack-test/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/kevinwarner/Documents/Projects/logicbox/localstack-test/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/kevinwarner/Documents/Projects/logicbox/localstack-test/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/kevinwarner/Documents/Projects/logicbox/localstack-test/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/kevinwarner/Documents/Projects/logicbox/localstack-test/node_modules/aws-sdk/lib/request.js:685:12)
  message: 'Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:localstack-test-local-listBuckets: Lambda process returned error status code: 1. Output:\n\u001b[32mSTART RequestId: 0cc05d90-6d72-1cc5-a959-05232d98acfb Version: $LATEST\u001b[0m\n\u001b[34m2019-06-05T22:22:56.818Z\t0cc05d90-6d72-1cc5-a959-05232d98acfb\t\u001b[0m{ Error: connect ECONNREFUSED 172.17.0.1:4572\n    at Object._errnoException (util.js:1022:11)\n    at _exceptionWithHostPort (util.js:1044:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)\n  message: \'connect ECONNREFUSED 172.17.0.1:4572\',\n  code: \'NetworkingError\',\n  errno: \'ECONNREFUSED\',\n  syscall: \'connect\',\n  address: \'172.17.0.1\',\n  port: 4572,\n  region: \'us-east-1\',\n  hostname: \'172.17.0.1\',\n  retryable: true,\n  time: 2019-06-05T22:22:56.817Z }\n\u001b[34m2019-06-05T22:22:56.825Z\t0cc05d90-6d72-1cc5-a959-05232d98acfb\t\u001b[0m{"errorMessage":"connect ECONNREFUSED 172.17.0.1:4572","errorType":"NetworkingError","stackTrace":["Object._errnoException (util.js:1022:11)","_exceptionWithHostPort (util.js:1044:20)","TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)"]}\n\u001b[32mEND RequestId: 0cc05d90-6d72-1cc5-a959-05232d98acfb\u001b[0m\n\u001b[32mREPORT RequestId: 0cc05d90-6d72-1cc5-a959-05232d98acfb\tDuration: 1698.90 ms\tBilled Duration: 1700 ms\tMemory Size: 1536 MB\tMax Memory Used: 43 MB\t\u001b[0m Traceback (most recent call last):\n  File "/Users/kevinwarner/Library/Python/2.7/lib/python/site-packages/localstack/services/awslambda/lambda_api.py", line 311, in run_lambda\n    event, context=context, version=version, asynchronous=asynchronous)\n  File "/Users/kevinwarner/Library/Python/2.7/lib/python/site-packages/localstack/services/awslambda/lambda_executors.py", line 58, in execute\n    result, log_output = self._execute(func_arn, func_details, event, context, version, asynchronous)\n  File "/Users/kevinwarner/Library/Python/2.7/lib/python/site-packages/localstack/services/awslambda/lambda_executors.py", line 201, in _execute\n    result, log_output = self.run_lambda_executor(cmd, environment, asynchronous)\n  File "/Users/kevinwarner/Library/Python/2.7/lib/python/site-packages/localstack/services/awslambda/lambda_executors.py", line 133, in run_lambda_executor\n    (return_code, log_output))\nException: Lambda process returned error status code: 1. Output:\n\u001b[32mSTART RequestId: 0cc05d90-6d72-1cc5-a959-05232d98acfb Version: $LATEST\u001b[0m\n\u001b[34m2019-06-05T22:22:56.818Z\t0cc05d90-6d72-1cc5-a959-05232d98acfb\t\u001b[0m{ Error: connect ECONNREFUSED 172.17.0.1:4572\n    at Object._errnoException (util.js:1022:11)\n    at _exceptionWithHostPort (util.js:1044:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)\n  message: \'connect ECONNREFUSED 172.17.0.1:4572\',\n  code: \'NetworkingError\',\n  errno: \'ECONNREFUSED\',\n  syscall: \'connect\',\n  address: \'172.17.0.1\',\n  port: 4572,\n  region: \'us-east-1\',\n  hostname: \'172.17.0.1\',\n  retryable: true,\n  time: 2019-06-05T22:22:56.817Z }\n\u001b[34m2019-06-05T22:22:56.825Z\t0cc05d90-6d72-1cc5-a959-05232d98acfb\t\u001b[0m{"errorMessage":"connect ECONNREFUSED 172.17.0.1:4572","errorType":"NetworkingError","stackTrace":["Object._errnoException (util.js:1022:11)","_exceptionWithHostPort (util.js:1044:20)","TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)"]}\n\u001b[32mEND RequestId: 0cc05d90-6d72-1cc5-a959-05232d98acfb\u001b[0m\n\u001b[32mREPORT RequestId: 0cc05d90-6d72-1cc5-a959-05232d98acfb\tDuration: 1698.90 ms\tBilled Duration: 1700 ms\tMemory Size: 1536 MB\tMax Memory Used: 43 MB\t\u001b[0m\n',
  code: 'InternalFailure',
  time: 2019-06-05T22:22:57.403Z,
  requestId: undefined,
  statusCode: 500,
  retryable: true }
```

My test file that invokes the lambda is...

```
const AWS = require('aws-sdk');

const lambda = new AWS.Lambda({
  region: 'us-east-1',
  endpoint: 'http://localhost:4574'
});

lambda
  .invoke({
    FunctionName: 'localstack-test-local-listBuckets'
  })
  .promise()
  .then(data => {
    console.log(data);
  })
  .catch(err => console.log(err));
```

I appreciate any help at all on this. Thanks!

**Comment by stevenhunter** [comment]
I had similar issue with .Net Lambda invoking other localstack services on host, failing with connection refused error when using LOCALSTACK_HOSTNAME environment variable. Eventually I discovered that using AWSSDK client object simply required me to pass nonsense credentials using constructor overload as follows.  Using default version of AmazonLambdaClient constructor without these credentials always fails.

var client = new AmazonLambdaClient("abc", "def", new AmazonLambdaConfig
            {
                ServiceURL = $@"http://{Environment.GetEnvironmentVariable("LOCALSTACK_HOSTNAME")}:4574",
                UseHttp = true
            });

**Comment by kevinswarner** [comment]
Thanks @stevenhunter. I would think that a missing credentials would result in a different error. I get a ECONNREFUSED 172.17.0.1:4572 which in Node, normally means that there is nothing running or available at that address and port. I will check into this solution. Thanks.

**Comment by whummer** [comment]
Hi @kevinswarner . The problem is that you're starting the LocalStack services on the host system (on Mac OS), whereas your Lambda functions are running in Docker.

When the Lambdas in Docker are trying to access the services (e.g., S3), we would have to give them access from inside your container to the network ports running on the host.

This is not easily achievable on Mac OS, due to the way the networking is set up, and due to the fact that Docker itself is running on a VM. If you are aware of a simple/stable solution to achieve this, I'd be happy to accept a pull request.

Meanwhile, I've added a warning message to inform the user about this limitation in this PR: #1380

**Comment by whummer** [comment]
By the way, I believe the `LAMBDA_EXECUTOR` variable should be lower-case, i.e., `LAMBDA_EXECUTOR=docker ...`

**Comment by kevinswarner** [comment]
@stevenhunter @whummer Thank you. I will attempt to start the services in docker as you suggested. I will update this thread with my results. Thanks!

**Comment by abhyuditjain** [comment]
I am facing the same issue. Is there any update on this?

**Comment by whummer** [comment]
@abhyuditjain The configuration around `LOCALSTACK_HOSTNAME` has recently been improved. Can you please give it a chance with the latest Docker image?

If the problem persists, please provide a more detailed report about:
1. your environment (OS, environment variables, etc)
2. the command used to deploy your Lambdas/application
3. the command used to invoke your Lambdas/application

Thanks
