### ISSUE TITLE
Fedora: permission error writing to /tmp/locasltack with docker-compose up 

### ISSUE THREAD

**Issue by pablohalamaj** [localstack/localstack#1374]
Hello, 

I just pulled the commit 718bf8228ed942b66e6e745073ad9373f6c19f32 and when i run docker-compose up, i got the following error:

> [phalamaj@skylark localstack]$ docker-compose up --remove-orphans --force-recreate 
Recreating localstack_localstack_1 ... done
Attaching to localstack_localstack_1
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2019-06-13 19:26:56,930 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_1  | 2019-06-13 19:26:56,933 INFO supervisord started with pid 12
localstack_1  | 2019-06-13 19:26:57,938 INFO spawned: 'dashboard' with pid 20
localstack_1  | 2019-06-13 19:26:57,951 INFO spawned: 'infra' with pid 21
localstack_1  | (. .venv/bin/activate; bin/localstack web)
localstack_1  | 2019-06-13 19:26:57,970 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_1  | (. .venv/bin/activate; exec bin/localstack start)
localstack_1  | 2019-06-13 19:26:58,974 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  | Starting mock ES service (http port 4578)...
localstack_1  | Starting local Elasticsearch (http port 4571)...
localstack_1  | Starting mock S3 (http port 4572)...
localstack_1  | Starting mock SNS (http port 4575)...
localstack_1  | *Error starting infrastructure: [Errno 13] Permission denied: '/tmp/localstack/sqs.725ed06b.conf' Traceback (most recent call last):*
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 611, in start_infra
localstack_1  |     t1 = plugin.start(asynchronous=True)
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 88, in start
localstack_1  |     return self.start_function(**kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/sqs/sqs_starter.py", line 38, in start_sqs
localstack_1  |     save_file(config_file, config_params)
localstack_1  |   File "/opt/code/localstack/localstack/utils/common.py", line 582, in save_file
localstack_1  |     with open(file, mode) as f:
localstack_1  |* PermissionError: [Errno 13] Permission denied: '/tmp/localstack/sqs.725ed06b.conf'*
localstack_1  | 

If i check the /tmp/localstack directory at the hostmachine it doesn't have any file, also a _chmod -R 777 /tmp/localstack_ didn't help.

I was able to fix it in two different ways:

*  Removing the TMP volume definition:

`[phalamaj@skylark` localstack]$ git diff docker-compose.yml

diff --git a/docker-compose.yml b/docker-compose.yml
index 20ba875..5ba8714 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -15,5 +15,4 @@ services:
       - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
       - DOCKER_HOST=unix:///var/run/docker.sock
     volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
       - "/var/run/docker.sock:/var/run/docker.sock"

* disabling SELINUX

`[phalamaj@skylark` localstack]$ sudo setenforce 0

I'm running a fedora 29 with the latest updates and the following rpms:

* docker-rhel-push-plugin-1.13.1-67.git1185cfd.fc29.x86_64
* docker-common-1.13.1-67.git1185cfd.fc29.x86_64
* docker-compose-1.22.0-2.fc29.noarch
* docker-1.13.1-67.git1185cfd.fc29.x86_64

**Comment by pablohalamaj** [comment]
Finally fix on the Fedora side.

with SELINUX enabled find the line that show you when localstack got blocked, in my case:

```
[phalamaj@skylark ~]$ sudo ausearch -c 'python' --raw |audit2allow 


#============= container_t ==============
allow container_t container_runtime_tmp_t:dir { add_name write };
allow container_t container_runtime_tmp_t:file { create write };
allow container_t user_tmp_t:dir write;
[phalamaj@skylark ~]$ sudo ausearch -c 'python' --raw |audit2allow -M localstack 
******************** IMPORTANT ***********************
To make this policy package active, execute:

semodule -i localstack.pp
[phalamaj@skylark ~]$ sudo semodule -i localstack.pp
```

Then you are good to go!
