### ISSUE TITLE
Dynamodb - ReturnValuesOnConditionCheckFailure Results in 500

### ISSUE THREAD

**Issue by pulltab** [localstack/localstack#1384]
On localstack/localstack:latest (docker) I am encountering a 500 error code when processing an Update action which has a [ReturnValuesOnConditionCheckFailure](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/Update.html#withReturnValuesOnConditionCheckFailure--) clause.

The following error is reported by the daemon:

```
localstack_1            | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
localstack_1            | 2019-06-18T22:55:59:ERROR:localstack.services.generic_proxy: Error forwarding request: object of type 'NoneType' has no len() Traceback (most recent call last):
localstack_1            |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 241, in forward
localstack_1            |     updated_response = self.proxy.update_listener.return_response(**kwargs)
localstack_1            |   File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 202, in return_response
localstack_1            |     if len(records) > 0 and 'eventName' in records[0]:
localstack_1            | TypeError: object of type 'NoneType' has no len()
```

**Comment by pulltab** [comment]
This issue seems specific to my client (alpakka-dynamodb) and this issue occurs with dynamodb-local as well.

Closing this issue as localstack isn't the culprit.
