### ISSUE TITLE
The tag_log_group action has not been implemented

### ISSUE THREAD

**Issue by arichiardi** [localstack/localstack#1386]
Dear Localstack team, you are great :rainbow: 

This is more of a feature request rather than a bug as the message is pretty clear (thanks for this time saver as well!) :smile: 

```
NotImplementedError: The tag_log_group action has not been implemented
172.17.0.1 - - [19/Jun/2019 19:40:55] "POST / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 303, in run_wsgi
execute(self.server.app)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 291, in execute
application_iter = app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/server.py", line 104, in __call__
return backend_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/utils.py", line 140, in __call__
result = self.callback(request, request.url, {})
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 117, in dispatch
return cls()._dispatch(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 200, in _dispatch
return self.call_action()
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 296, in call_action
"The {0} action has not been implemented".format(action))
NotImplementedError: The tag_log_group action has not been implemented
```

The operation that triggers this might be the log side of my current API Gateway + Lambda setup. I am using `terraform` so I need a bit of time to disentangle what is the actual resource but I figured I should open the issue first and see.

Thank you for your great work on `localstack`!

**Comment by whummer** [comment]
Thanks for reporting @arichiardi . This should be fixed in the latest version:
```
$ awslocal logs create-log-group --log-group-name g1
$ awslocal logs tag-log-group --log-group-name g1 --tags t1=t2
$ awslocal logs list-tags-log-group --log-group-name g1
{
    "tags": {
        "t1": "t2"
    }
}
```
Please report here if the problem persists. Thanks
