### ISSUE TITLE
Cloudformation unsuported version 'eu-north-1'

### ISSUE THREAD

**Issue by Arthamys** [localstack/localstack#1390]
I have an issue calling  into cloudformation when using the `eu-north-1` region.
It seems that his region is not yet supported in cloudformation, and yields the following: `KeyError: 'eu-north-1'`

I am running localstack 0.9.5, python 3.7.3 and  starting localstack through:
`localstack

Full relevant logs:
```
2019-06-21T07:35:52:DEBUG:localstack.services.s3.s3_listener: Found no <LastModified>(.*)</LastModified> inside response_content: list index out of range
2019-06-21T07:36:55:INFO:werkzeug: 127.0.0.1 - - [21/Jun/2019 07:36:55] "POST / HTTP/1.1" 500 -
2019-06-21T07:36:55:ERROR:werkzeug: Error on request:
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 303, in run_wsgi
execute(self.server.app)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 291, in execute
application_iter = app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/server.py", line 104, in __call__
return backend_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/utils.py", line 140, in __call__
result = self.callback(request, request.url, {})
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 117, in dispatch
return cls()._dispatch(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 200, in _dispatch
return self.call_action()
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 274, in call_action
response = method()
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/cloudformation/responses.py", line 171, in describe_stacks
stacks = self.cloudformation_backend.describe_stacks(stack_name_or_id)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/cloudformation/responses.py", line 18, in cloudformation_backend
return cloudformation_backends[self.region]
KeyError: 'eu-north-1'
```

**Comment by whummer** [comment]
Thanks for reporting @Arthamys . This should be fixed in #1863 . Can you please give it a try with the latest version of the Docker image? Please report here if the problem persists.
