### ISSUE TITLE
dynamodb calls fail w/ aws golang library

### ISSUE THREAD

**Issue by herriojr** [localstack/localstack#1391]
I'm using the aws's golang library, no third party. When making a request, it fails in the localstack generic proxy as seen by these logs:
```
2019-06-21T22:52:04:ERROR:localstack.services.generic_proxy: Error forwarding request: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 202, in forward
    path=path, data=data, headers=forward_headers)
  File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 36, in forward_request
    data = json.loads(to_str(data))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
using awslocal has no issues.

the code I'm doing is the following:
```
struct Model {
	db *dynamodb.DynamoDB
	tableName string
}

func newModel() *Model {
	sess := session.Must(session.NewSessionWithOptions(session.Options{
		Config: aws.Config{
			Endpoint: aws.String("http://localhost:4569/"),
			Region: aws.String(endpoints.UsWest2RegionID),
		},
		SharedConfigState: session.SharedConfigEnable,
	}))

	return &Model {
		db: dynamodb.New(sess)
	}
}

func (m *Model) streamData() <-chan Data {
	dataCh := make(chan Data)
	go func() {
		defer close(dataCh)

		err := c.db.ScanPages(
			&dynamodb.ScanInput{
				TableName: aws.String(tableName),
			},
			func(output *dynamodb.ScanOutput, lastPage bool) bool {
				log.Print("Processing page")
				for _, item := range output.Items {
					data := &Data{}
					_ = dynamodbattribute.UnmarshalMap(item, data)
					dataCh <- *data
				}
				return true
			})
		if err != nil {
			log.Print(err.Error())
		}
		return
	}()
	return dataCh
}
```

Is there any extra configuration required to get this working? Thanks in advance!

**Comment by whummer** [comment]
Thanks for reporting @herriojr. To help reproduce this issue, can you please extend your code snippet and provide a self-contained sample that can be easily run, e.g., with `go test`? Thanks!

**Comment by whummer** [comment]
Any updates on this issue @herriojr - does it persist with the `latest` version of the LocalStack Docker image? Thanks

**Comment by herriojr** [comment]
I had gotten it working at some point and forgot all about this post. If I remembered what I did, I'd post it here, but I no longer remember. I'll close it.
