### ISSUE TITLE
Localstack Lambda Java8 ClassNotFoundException

### ISSUE THREAD

**Issue by sbilello** [localstack/localstack#1400]
docker-compose.yml

```
version: "3.2"
services:
  localstack:
    image: localstack/localstack
    container_name: localstack_demo
    ports:
      - "4567-4584:4567-4584"
      - "8055:8080"
    environment:
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3:4572,kinesis:4568,lambda:4574
      - DEFAULT_REGION=us-east-1
      - LOCALSTACK_HOSTNAME=localstack
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- docker-reuse}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/private${TMPDIR}:/tmp/localstack"
    networks:
      - my_awesome_network

  setup-resources:
    image: mesosphere/aws-cli
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/private${TMPDIR}:/tmp/localstack"
    environment:
      - AWS_ACCESS_KEY_ID=dummyaccess
      - AWS_SECRET_ACCESS_KEY=dummysecret
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    entrypoint: /bin/sh -c
    command: >
      "
        # Needed so all localstack components will startup correctly (i'm sure there's a better way to do this)
        sleep 20;
        # Create s3 demo-bucket
        aws --endpoint-url=http://localstack:4572 s3 mb s3://demo-bucket
        # Create s3 bucket policy
        aws --endpoint-url=http://localstack:4572 s3api put-bucket-acl --bucket demo-bucket --acl public-read        
        # Create kinesis stream
        aws kinesis create-stream --endpoint-url=http://localstack:4568 --stream-name my_stream --shard-count 1;
      "
    networks:
      - my_awesome_network
    depends_on:
      - localstack

networks:
  my_awesome_network:
```

Function deployment to localstack lambda
```
aws lambda --endpoint=http://localhost:4574 create-function \
--region us-east-1 \
--function-name hellociao \
--zip-file fileb:///Users/sergio.bilello/Documents/repositories/search-jobs-lambda-eventbus-fallback/sam-app/HelloWorldFunction/target/HelloWorld-1.0.jar \
--role whatever \
--handler  helloworld.App::handleRequest \
--runtime java8
{
    "FunctionName": "hellociao",
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:hellociao",
    "Runtime": "java8",
    "Role": "whatever",
    "Handler": "helloworld.App::handleRequest",
    "CodeSize": 11503,
    "Description": "",
    "Timeout": 3,
    "LastModified": "2019-06-27T23:55:00.749+0000",
    "CodeSha256": "gYdtaERQ7t5XOaV4rvYw+ZmVs/zAyf1XByPMuFDegCI=",
    "Version": "$LATEST",
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "3bac595b-2568-4ba2-8dd8-e5fcea2e71f8"
} 
```

ERROR

```
 2019-06-27T23:55:17:WARNING:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:hellociao: Lambda process returned error status code: 1. Output:
localstack_demo    | Exception in thread "main" java.lang.ClassNotFoundException: helloworld.App::handleRequest
localstack_demo    | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
localstack_demo    | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
localstack_demo    | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
localstack_demo    | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
localstack_demo    | 	at java.lang.Class.forName0(Native Method)
localstack_demo    | 	at java.lang.Class.forName(Class.java:264)
localstack_demo    | 	at cloud.localstack.LambdaExecutor.getHandler(LambdaExecutor.java:150)
localstack_demo    | 	at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:64) Traceback (most recent call last):
localstack_demo    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 320, in run_lambda
localstack_demo    |     event, context=context, version=version, asynchronous=asynchronous)
localstack_demo    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 62, in execute
localstack_demo    |     result, log_output = self._execute(func_arn, func_details, event, context, version, asynchronous)
localstack_demo    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 204, in _execute
localstack_demo    |     result, log_output = self.run_lambda_executor(cmd, environment, asynchronous)
localstack_demo    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 137, in run_lambda_executor
localstack_demo    |     (return_code, log_output))
localstack_demo    | Exception: Lambda process returned error status code: 1. Output:
localstack_demo    | Exception in thread "main" java.lang.ClassNotFoundException: helloworld.App::handleRequest
localstack_demo    | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
localstack_demo    | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
localstack_demo    | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
localstack_demo    | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
localstack_demo    | 	at java.lang.Class.forName0(Native Method)
localstack_demo    | 	at java.lang.Class.forName(Class.java:264)
localstack_demo    | 	at cloud.localstack.LambdaExecutor.getHandler(LambdaExecutor.java:150)
localstack_demo    | 	at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:64)
localstack_demo    |
```
INFO
MACOSX Mojave 10.14.3
Docker Engine: 18.09.2
Docker Compose: 1.23.2
Machine: 0.16.1

The jar used has been created with `sam init --runtime java8` and built with `mvn package`
I used the official HelloWorld template from AWS

**Comment by ajthomp2** [comment]
It doesn't look like localstack supports "class::handlerMethod". Try using "--handler helloworld.App".

**Comment by jmallar3** [comment]
This may be your issue: https://github.com/localstack/localstack/issues/385?

**Comment by whummer** [comment]
Thanks for reporting @sbilello . Issue #385 related to Java Lambdas should be fixed in #1486 . Were you able to get it working with the hint from @ajthomp2 ?

**Comment by sbilello** [comment]
```aws lambda --endpoint=http://localhost:4574 create-function \
--region us-east-1 \
--function-name hellociao \
--zip-file fileb:///Users/sergio.bilello/Documents/repositories/sam-app/HelloWorldFunction/target/HelloWorld-1.0.jar \
--role whatever \
--handler  helloworld.App \
--runtime java8
```
This worked.

**Comment by ajthomp2** [comment]
Thanks @whummer got it working now.

**Comment by shorobura-mykola** [comment]
@sbilello Thank you for it. Well done.
