### ISSUE TITLE
500 error when uploading file on s3 bucket

### ISSUE THREAD

**Issue by amitheda** [localstack/localstack#1410]
Hello Team,

I am using the latest localstack docker image and trying to upload image/file on the s3 bucket through node js. 
Sample code is,

```
const fs = require('fs');
const AWS = require('aws-sdk');

const s3 = new AWS.S3({
   endpoint: 'http://localhost:4572'
});

const fileName = './test.jpg';   //  image file path

const uploadFile = () => {
  fs.readFile(fileName, (err, data) => {
     if (err) throw err;
     const params = {
         Bucket: "image", 
         Key: "test.jpg", 
         Body: data
     };
     s3.putObject(params, function(err, data) {
         if (err) throw err
         console.log(`File uploaded successfully`)
     });
  });
};

uploadFile();
```

when I ran this nodejs code, I got the following error on the terminal.

```
500: null
    at Request.extractError (/test/node_modules/aws-sdk/lib/services/s3.js:585:35)
    at Request.callListeners (test/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (test/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (test/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (test/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (test/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at test/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (test/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (test/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (test/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

and the localstack log is (after docker logs {container_id} ),

```
2019-07-03T11:05:17:INFO:werkzeug: 127.0.0.1 - - [03/Jul/2019 11:05:17] "PUT /test.jpg HTTP/1.1" 500 -
2019-07-03T11:05:17:ERROR:werkzeug: Error on request:
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 303, in run_wsgi
execute(self.server.app)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 291, in execute
application_iter = app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/server.py", line 104, in __call__
return backend_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/utils.py", line 140, in __call__
result = self.callback(request, request.url, {})
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/s3/responses.py", line 112, in ambiguous_response
return self.bucket_response(request, full_url, headers)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/s3/responses.py", line 116, in bucket_response
response = self._bucket_response(request, full_url, headers)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/s3/responses.py", line 149, in _bucket_response
body = body.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 10: invalid start byte
```

But when the same file uploaded through awslocal cli it gets uploaded.

> awslocal  s3  test.jpg  s3://image

**Comment by dolsem** [comment]
I'm experiencing the same issue. Any ideas on how to fix?

**Comment by amitheda** [comment]
Set `s3ForcePathStyle`  to true  while creating s3 object.

` const s3 = new AWS.S3({
     endpoint: 'http://localhost:4572',
     s3ForcePathStyle: true
  });
`

**Comment by whummer** [comment]
Thanks for providing a fix @amitheda . Closing this issue as resolved 👍

**Comment by yemzybhin** [comment]
good

**Comment by yemzybhin** [comment]
good
![Uploading Vector.png…]()

**Comment by yemzybhin** [comment]
good

**Comment by yemzybhin** [comment]
good
![Uploading Vector.png…]()

**Comment by yemzybhin** [comment]
good

**Comment by yemzybhin** [comment]
good
![Uploading Vector.png…]()
