### ISSUE TITLE
Connection error on startup

### ISSUE THREAD

**Issue by Prachi481992** [localstack/localstack#1412]
[https://github.com/localstack/localstack/issues/781#issue-325750550](Connection error on startup)
I'm facing the same issue in image tag 0.9.0.
I have a startup shell script which creates an s3 bucket on container startup. it works fine when the container starts for the first time but start failing with below error when the container is restarted.
```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initaws.d/create-s3-bucket.sh
2019-07-04 07:43:45,156 INFO Set uid to user 0 succeeded
2019-07-04 07:43:45,183 INFO supervisord started with pid 7
2019-07-04 07:43:46,185 INFO spawned: 'dashboard' with pid 12
2019-07-04 07:43:46,187 INFO spawned: 'infra' with pid 13
(. .venv/bin/activate; bin/localstack web)
2019-07-04 07:43:47,205 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-07-04 07:43:47,205 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-07-04T07:43:53:INFO:werkzeug:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
2019-07-04T07:43:53:INFO:werkzeug:  * Restarting with stat
2019-07-04T07:43:54:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: /demo-bucket (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ba0416290>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 216, in forward
    headers=forward_headers, stream=True)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 131, in put
    return request('put', url, data=data, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: /demo-bucket (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0ba0416290>: Failed to establish a new connection: [Errno 111] Connection refused',))


An error occurred (502) when calling the CreateBucket operation (reached max retries: 4): Bad Gateway
```

From what I saw in entrypoint.sh, the issue seems to be because the startup of services depends on occurence of the word "Ready" in the console. 
When I stop the container and start it again, the logs already have the word "Ready" from the previous startup, thus the services are not started and the program tries to create the s3 bucket directly thus failing.
I'm unable to run my application with the latest version of localstack due to some other application-level errors.
Can anybody please help?

**Comment by Tochemey** [comment]
Hello,

Please can someone help us fix this issue.

**Comment by whummer** [comment]
Thanks for reporting @Prachi481992 @Tochemey . Closing this issue as outdated, but please report here if the problem persists. Thanks!
