### ISSUE TITLE
Error trying to list buckets in latest docker image

### ISSUE THREAD

**Issue by chrisjcodes** [localstack/localstack#1449]
Trying to run `aws s3 ls --endpoint-url http://0.0.0.0:4569` and getting the following output:

```
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | Ready.
localstack_1  | 2019-07-30T23:03:34:ERROR:localstack.services.generic_proxy: Error forwarding request: the JSON object must be str, bytes or bytearray, not 'NoneType' Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 210, in forward
localstack_1  |     path=path, data=data, headers=forward_headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 36, in forward_request
localstack_1  |     data = json.loads(to_str(data))
localstack_1  |   File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
localstack_1  |     'not {!r}'.format(s.__class__.__name__))
localstack_1  | TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
localstack_1  | 
localstack_1  | 2019-07-30T23:03:34:ERROR:localstack.services.generic_proxy: Error forwarding request: the JSON object must be str, bytes or bytearray, not 'NoneType' Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 210, in forward
localstack_1  |     path=path, data=data, headers=forward_headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 36, in forward_request
localstack_1  |     data = json.loads(to_str(data))
localstack_1  |   File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
localstack_1  |     'not {!r}'.format(s.__class__.__name__))
localstack_1  | TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
localstack_1  | 
localstack_1  | 2019-07-30T23:03:36:ERROR:localstack.services.generic_proxy: Error forwarding request: the JSON object must be str, bytes or bytearray, not 'NoneType' Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 210, in forward
localstack_1  |     path=path, data=data, headers=forward_headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 36, in forward_request
localstack_1  |     data = json.loads(to_str(data))
localstack_1  |   File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
localstack_1  |     'not {!r}'.format(s.__class__.__name__))
localstack_1  | TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
localstack_1  | 
localstack_1  | 2019-07-30T23:03:36:ERROR:localstack.services.generic_proxy: Error forwarding request: the JSON object must be str, bytes or bytearray, not 'NoneType' Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 210, in forward
localstack_1  |     path=path, data=data, headers=forward_headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 36, in forward_request
localstack_1  |     data = json.loads(to_str(data))
localstack_1  |   File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
localstack_1  |     'not {!r}'.format(s.__class__.__name__))
localstack_1  | TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
localstack_1  | 
localstack_1  | 2019-07-30T23:03:39:ERROR:localstack.services.generic_proxy: Error forwarding request: the JSON object must be str, bytes or bytearray, not 'NoneType' Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 210, in forward
localstack_1  |     path=path, data=data, headers=forward_headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 36, in forward_request
localstack_1  |     data = json.loads(to_str(data))
localstack_1  |   File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
localstack_1  |     'not {!r}'.format(s.__class__.__name__))
localstack_1  | TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
localstack_1  | 
```

**Comment by ciaranevans** [comment]
@chrisjcodes you're pointing to the wrong URL.

`:4569` is dynamodb, as you can see in the output you've provided.

`:4572` is the S3 port 😄

**Comment by chrisjcodes** [comment]
Welp sometimes you just need a second set of eyes. Derp.
