### ISSUE TITLE
API Gateway get_method does not return correct errors

### ISSUE THREAD

**Issue by eliasbrange** [localstack/localstack#1454]
API Gateway `get_method` endpoint does not properly return `NotFoundException`.

While setting up local tests I''ve run into some problems when testing API Gateway methods. We check for method existence with `apigateway.get_method` which should raise a `NotFoundException` if the method does not exist.

Localstack seems to behave differently depending on whether the requested method is `GET` vs `POST/DELETE/...`.

After creating a resource (and before creating any methods), Localstack's `get_method(api, resource, "GET")` successfully returns, but missing all the response parameters listed [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apigateway.html#APIGateway.Client.get_method).

Trying to do `get_method(..., "POST")` or `get_method(..., "DELETE")` also does not raise the expected `NotFoundException` but rather generates an `Internal Server Error` inside localstack with the following logs:

```syslog
127.0.0.1 - - [02/Aug/2019 09:27:46] "GET /restapis/2177854513/resources/57A-Z4A-Z95A-Z43/methods/DELETE HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 303, in run_wsgi
execute(self.server.app)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 291, in execute
application_iter = app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/server.py", line 104, in __call__
return backend_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/utils.py", line 140, in __call__
result = self.callback(request, request.url, {})
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/apigateway/responses.py", line 86, in resource_methods
function_id, resource_id, method_type)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/apigateway/models.py", line 486, in get_method
return resource.get_method(method_type)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/apigateway/models.py", line 155, in get_method
return self.resource_methods[method_type]
KeyError: 'DELETE'
```

Below is a simple reproduction test suite that works fine when using AWS but fails on all three tests when running against Localstack.

```python
import boto3
import pytest


@pytest.fixture(scope='module')
def setup():
    # remove endpoint_url below to run against AWS
    apigateway = boto3.client('apigateway',
                              endpoint_url='http://localhost:4567',
                              region_name='eu-west-1')
    res = apigateway.create_rest_api(name='test')
    rest_api_id = res.get('id')

    assert rest_api_id is not None
    print('API Gateway created with ID {}'.format(rest_api_id))

    res = apigateway.get_resources(restApiId=rest_api_id, limit=10)
    root_id = None

    for resource in res['items']:
        if resource['path'] == '/':
            root_id = resource['id']
            break

    res = apigateway.create_resource(restApiId=rest_api_id, parentId=root_id,
                                     pathPart='test')

    yield {
        'client': apigateway,
        'api_id': rest_api_id,
        'resource_id': res.get('id')
    }

    apigateway.delete_rest_api(restApiId=rest_api_id)


def test_get_non_existing_get(setup):
    client = setup.get('client')
    resource_id = setup.get('resource_id')
    api_id = setup.get('api_id')

    with pytest.raises(client.exceptions.NotFoundException):
        client.get_method(restApiId=api_id, resourceId=resource_id,
                          httpMethod='GET')


def test_get_non_existing_post(setup):
    client = setup.get('client')
    resource_id = setup.get('resource_id')
    api_id = setup.get('api_id')

    with pytest.raises(client.exceptions.NotFoundException):
        client.get_method(restApiId=api_id, resourceId=resource_id,
                          httpMethod='POST')


def test_get_non_existing_delete(setup):
    client = setup.get('client')
    resource_id = setup.get('resource_id')
    api_id = setup.get('api_id')

    with pytest.raises(client.exceptions.NotFoundException):
        client.get_method(restApiId=api_id, resourceId=resource_id,
                          httpMethod='DELETE')
```

**Comment by eliasbrange** [comment]
Seems like there might be a fix for this over at https://github.com/whummer/moto/commit/8f50c4e7dfcbec92286fbf52e9b31758b854aba7? Any chance to get that into the `moto` version running in the `locatstack/localstack` image?

**Comment by whummer** [comment]
Thanks for reporting and pointing out the existing commit, @eliasbrange .

The change should have been included [here](https://github.com/localstack/localstack/pull/1467/files#diff-b4ef698db8ca845e5845c4618278f29aR30). Can you please give it a try with the latest version of the code (Docker image tagged `latest`)? Thanks

**Comment by eliasbrange** [comment]
Seems to work a bit better now. However the exception is `botocore.exceptions.ClientError` and not `apigatewayclient.exceptions.NotFoundError`. It seems to work correctly for the exception thrown for `get_stage`.

The following test passes (with the same setup as above):

```python
def test_get_non_existing_stage(setup):
    client = setup.get('client')
    api_id = setup.get('api_id')

    with pytest.raises(client.exceptions.NotFoundException):
        client.get_stage(restApiId=api_id, stageName='default')
```

**Comment by eliasbrange** [comment]
From which repository/branch is `moto-ext` released?

**Comment by eliasbrange** [comment]
@whummer This change in `moto/apigateway/responses.py` seems to do the trick:

```diff
diff --git a/moto/apigateway/responses.py b/moto/apigateway/responses.py
index bc4d262..da42911 100644
--- a/moto/apigateway/responses.py
+++ b/moto/apigateway/responses.py
@@ -4,8 +4,8 @@ import json

 from moto.core.responses import BaseResponse
 from .models import apigateway_backends
-from .exceptions import StageNotFoundException, ApiKeyNotFoundException
-
+from .exceptions import (StageNotFoundException, ApiKeyNotFoundException,
+                         MethodNotFoundException)

 class APIGatewayResponse(BaseResponse):

@@ -82,9 +82,13 @@ class APIGatewayResponse(BaseResponse):
         method_type = url_path_parts[6]

         if self.method == 'GET':
-            method = self.backend.get_method(
-                function_id, resource_id, method_type)
-            return 200, {}, json.dumps(method)
+            try:
+                method = self.backend.get_method(
+                    function_id, resource_id, method_type)
+                return 200, {}, json.dumps(method)
+            except MethodNotFoundException as error:
+                return error.code, {}, '{{"message":"{0}","code":"{1}"}}'.format(error.message, error.error_type)
+
         elif self.method == 'PUT':
             authorization_type = self._get_param("authorizationType")
             method = self.backend.create_method(
```

**Comment by eliasbrange** [comment]
Any update on this @whummer?

**Comment by whummer** [comment]
Hi @eliasbrange , apologies for the long delay. If you could please raise a PR against the `localstack` branch here: https://github.com/localstack/moto , that would be great. Thanks!

**Comment by eliasbrange** [comment]
Will do whenever I find the time. What is the state of `make test`? Just cloned a fresh repository and got the following:

```
--------------------------------------------------------------------------
TOTAL                                                  32541   6258    81%
----------------------------------------------------------------------
Ran 2359 tests in 256.862s

FAILED (SKIP=1, errors=788, failures=52)
```

**Comment by whummer** [comment]
> Just cloned a fresh repository and got the following

Thanks @eliasbrange . Did you run `make install` as well? Also, you could simply run `docker build`, which produces the Docker image and also runs the tests as the last build step.
