### ISSUE TITLE
Error Starting Localstack Elasticsearch in Custom Docker Container

### ISSUE THREAD

**Issue by kevinswarner** [localstack/localstack#1468]
I have the following Docker file.

```
FROM circleci/node:10.16.0-stretch

USER root

##### SYSTEM TOOLS #####

# Update Apt cache

RUN apt-get update

# Install PIP

RUN apt-get install -qq -y python-pip libpython-dev \
  && curl -O https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py

# Install Pypa Setuptools

RUN pip install --upgrade setuptools

# Install Java

RUN sudo apt-get install openjdk-8-jdk

##### CUSTOM TOOLS #####

# Install Terraform

RUN wget --quiet https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip \
  && unzip terraform_0.12.3_linux_amd64.zip \
  && mv terraform /usr/bin \
  && rm terraform_0.12.3_linux_amd64.zip

# Install serverless
# See https://github.com/serverless/serverless/issues/4319

RUN npm install -g try-thread-sleep
RUN npm install -g serverless --ignore-scripts spawn-sync

# Install Mocha

RUN npm install -g mocha

# Install ESLint

RUN npm install -g eslint

# Install AWSCLI

RUN pip install -q awscli --upgrade

# Install jq and zip

RUN apt-get install -qq -y jq zip

# Install localstack

RUN pip install localstack==0.9.6

```

We use this Docker file for our Circle CI host. We need to run localstack so we can then run our integration tests. We are installing localstack version 0.9.6 because when we tried to install the latest, we had all kinds of problems.

So, with the above Docker container, we can successfully run localstack DynamoDB, and even S3. But, when we try to run Elasticsearch, we get the following. To test locally, I started the docker container, and then attempted to start localstack.

```
docker run -i -t c92934d45643 /bin/bash
```
where c92934d45643 is the image built with the above Docker file. This starts a bash session.

```
root@247903e7a720:/# SERVICES=es localstack start
Starting local dev environment. CTRL-C to quit.
Starting mock ES service (http port 4578)...
Starting local Elasticsearch (http port 4571)...
2019-08-08T03:27:12:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2019-08-08T03:27:26:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2019-08-08T03:27:40:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2019-08-08T03:27:54:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2019-08-08T03:28:08:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2019-08-08T03:28:23:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2019-08-08T03:28:37:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2019-08-08T03:28:51:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2019-08-08T03:29:05:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2019-08-08T03:29:19:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2019-08-08T03:29:33:ERROR:localstack.services.es.es_starter: Elasticsearch health check failed (retrying...): TransportError(502, u'') Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/es/es_starter.py", line 65, in check_elasticsearch
    out = es.cat.aliases()
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/cat.py", line 24, in aliases
    "GET", _make_path("_cat", "aliases", name), params=params
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 353, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 141, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 162, in _raise_error
    status_code, error_message, additional_info
TransportError: TransportError(502, u'')

2019-08-08T03:29:33:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2019-08-08T03:29:33:ERROR:infra.pyc: Error checking state of local environment (after some retries): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 416, in check_infra
    raise e
AssertionError

Error starting infrastructure:  Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 616, in start_infra
    check_infra(apis=apis)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 425, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 425, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 425, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 425, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 425, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 425, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 425, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 425, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 425, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 425, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 423, in check_infra
    raise e
AssertionError

ERROR:
root@247903e7a720:/#
```

So, again, running just SERVICES=dynamodb works, but Elasticsearch is causing issues. In Circle CI, I get a slightly different error when attempting to start the service...

```
#!/bin/bash -eo pipefail
SERVICES=dynamodb,es localstack start
Starting local dev environment. CTRL-C to quit.
2019-08-08T02:45:13:INFO:localstack.services.install: Downloading and installing local DynamoDB server. This may take some time.
2019-08-08T02:45:13:INFO:localstack.services.install: Downloading and installing local Elasticsearch server. This may take some time.
install elasticsearch-plugin analysis-icu
install elasticsearch-plugin ingest-attachment
install elasticsearch-plugin analysis-kuromoji
install elasticsearch-plugin mapper-murmur3
install elasticsearch-plugin mapper-size
install elasticsearch-plugin analysis-phonetic
install elasticsearch-plugin analysis-smartcn
install elasticsearch-plugin analysis-stempel
install elasticsearch-plugin analysis-ukrainian
2019-08-08T02:45:39:INFO:localstack.services.install: Downloading and installing LocalStack Java libraries. This may take some time.
Starting mock ES service (http port 4578)...
Starting mock DynamoDB (http port 4569)...
Starting local Elasticsearch (http port 4571)...
2019-08-08T02:45:39:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccc3d7fc50>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/generic_proxy.py", line 224, in forward
    headers=forward_headers, stream=True)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccc3d7fc50>: Failed to establish a new connection: [Errno 111] Connection refused',))

2019-08-08T02:45:39:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccc3d7f9d0>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/generic_proxy.py", line 224, in forward
    headers=forward_headers, stream=True)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fccc3d7f9d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

2019-08-08T02:46:00:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2019-08-08T02:46:14:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
```

And the Circle CI task eventually gets cancelled.

If anyone has any insights on what we might try to resolve this, using version 0.9.6 of localstack, that would be great. Thanks!

**Comment by kevinswarner** [comment]
I decided to create a much simplified use case. I have a very simple Docker file as follows...

```
FROM circleci/node:10.16.0-stretch
USER root
RUN apt-get update
RUN apt-get install -y python-pip
RUN pip install localstack
```

Then, I start the container. I have run some commands to show versions of python and pip. Then, I attempt to start localstack and get the error below.

```
$ docker run -i -t 9a8f82c5618e /bin/bash
root@319123b92dd5:/# python --version
Python 2.7.13
root@319123b92dd5:/# which python
/usr/bin/python
root@319123b92dd5:/# pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
root@319123b92dd5:/# which pip
/usr/bin/pip
root@319123b92dd5:/# localstack start
Traceback (most recent call last):
  File "/usr/local/bin/localstack", line 35, in <module>
    from localstack.utils import cli, bootstrap
  File "/usr/local/lib/python2.7/dist-packages/localstack/utils/cli.py", line 4, in <module>
    from localstack.utils import bootstrap
  File "/usr/local/lib/python2.7/dist-packages/localstack/utils/bootstrap.py", line 4, in <module>
    import pip as pip_mod
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
ImportError: No module named requests.packages.urllib3.exceptions
root@319123b92dd5:/#
```

I cannot find much information about installing and running localstack "inside" another Docker container.

If anyone can provide some help, I would be very grateful.

**Comment by kevinswarner** [comment]
I did not resolve this issue specifically, but for my use case (running localstack in my CircleCI environment), I simply am spinning up the official localstack/localstack Docker image within my CircleCI environment. Works like a charm.

**Comment by ciaranevans** [comment]
> I did not resolve this issue specifically, but for my use case (running localstack in my CircleCI environment), I simply am spinning up the official localstack/localstack Docker image within my CircleCI environment. Works like a charm.

That's what we've opted to do within our Azure Pipelines. We spin up LocalStack and a slim Python container beside it that runs our integration tests, using docker-compose.

**Comment by netmailgopi** [comment]
ES has it's set of requirements, you need to have maven, jdk (and VC++ build tools if windows) it's on an issue or the docs. It's tricky to get it to work even if you have everything. I do what you do as well. spin up localstack/localstack which works.

**Comment by whummer** [comment]
Thanks for reporting and for providing your solutions @kevinswarner @ciaranevans @netmailgopi . Seems like things are working for everyone at this point - closing this issue. Please re-open if the problem persists. Thanks

**Comment by sirkuttin** [comment]
> > I did not resolve this issue specifically, but for my use case (running localstack in my CircleCI environment), I simply am spinning up the official localstack/localstack Docker image within my CircleCI environment. Works like a charm.
> 
> @kevinswarner that's what we've opted to do within our Azure Pipelines. We spin up LocalStack and a slim Python container beside it that runs our integration tests, using docker-compose.

@ciaranevans I have been trying to do this very thing without much luck. Can you provide some example code to help me please :)

**Comment by ciaranevans** [comment]
> > > I did not resolve this issue specifically, but for my use case (running localstack in my CircleCI environment), I simply am spinning up the official localstack/localstack Docker image within my CircleCI environment. Works like a charm.
> > 
> > 
> > @kevinswarner that's what we've opted to do within our Azure Pipelines. We spin up LocalStack and a slim Python container beside it that runs our integration tests, using docker-compose.
> 
> @ciaranevans I have been trying to do this very thing without much luck. Can you provide some example code to help me please :)

I can certainly try and point you in the right direction @sirkuttin - What have you tried so far?

There wasn't anything that special about our method, merely just using docker compose to have LocalStack running in one instance and a container running tests in another..
