### ISSUE TITLE
Docker toolbox + WSL keeps crashing

### ISSUE THREAD

**Issue by ilan-deepreach** [localstack/localstack#1476]
The server is stuck in a loop `localstack start` or docker-compose from ubuntu (with windows subsystem linux) up with minimal services in the files gives : 

```
Starting local dev environment. CTRL-C to quit.
localstack    | cannot import name 'cognito_starter'
localstack    | Starting mock S3 (http port 4572)...
localstack    | Starting mock SQS (http port 4576)...
localstack    | Starting mock DynamoDB (http port 4569)...
localstack    | Starting mock Lambda service (http port 4574)...
localstack    | Starting mock CloudFormation (http port 4581)...
localstack    | Starting mock CloudWatch Logs (http port 4586)...
localstack    | 2019-08-10T12:53:19:INFO:localstack.multiserver: Starting multi API server process on port 51492
localstack    | Initializing DynamoDB Local with the following configuration:
localstack    | Port:   4564
localstack    | InMemory:       false
localstack    | DbPath: /tmp/localstack/data/dynamodb
localstack    | SharedDb:       true
localstack    | shouldDelayTransientStatuses:   false
localstack    | CorsParams:     *
localstack    |
localstack    | 12:53:23.965 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.14.5) ...
localstack    | 12:53:27.072 [elasticmq-akka.actor.default-dispatcher-3] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
localstack    | Error starting infrastructure:  Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/services/infra.py", line 385, in start_infra
localstack    |     t1 = plugin.start(asynchronous=True)
localstack    |   File "/opt/code/localstack/localstack/services/infra.py", line 63, in start
localstack    |     return self.start_function(**kwargs)
localstack    |   File "/opt/code/localstack/localstack/services/infra.py", line 134, in start_cloudwatch_logs
localstack    |     return start_moto_server('logs', port, name='CloudWatch Logs', asynchronous=asynchronous)
localstack    |   File "/opt/code/localstack/localstack/services/infra.py", line 264, in start_moto_server
localstack    |     return multiserver.start_api_server(key, backend_port or port)
localstack    |   File "/opt/code/localstack/localstack/utils/server/multiserver.py", line 70, in start_api_server
localstack    |     start_server_process(server_port)
localstack    |   File "/opt/code/localstack/localstack/utils/server/multiserver.py", line 97, in start_server_process
localstack    |     wait_for_port_open(port, retries=10, sleep_time=1)
localstack    |   File "/opt/code/localstack/localstack/utils/common.py", line 375, in wait_for_port_open
localstack    |     return retry(check, sleep=sleep_time, retries=retries)
localstack    |   File "/opt/code/localstack/localstack/utils/common.py", line 408, in retry
localstack    |     raise raise_error
localstack    |   File "/opt/code/localstack/localstack/utils/common.py", line 404, in retry
localstack    |     return function(**kwargs)
localstack    |   File "/opt/code/localstack/localstack/utils/common.py", line 373, in check
localstack    |     raise Exception()
localstack    | Exception
localstack    |
localstack    | 2019-08-10 12:53:32,931 INFO exited: infra (exit status 2; not expected)
localstack    | 2019-08-10 12:53:32,933 INFO spawned: 'infra' with pid 7473
localstack    | Traceback (most recent call last):
localstack    |   File "bin/localstack", line 86, in <module>
localstack    |     subcommand['function'](argv, args)
localstack    |   File "/opt/code/localstack/localstack/utils/cli.py", line 34, in cmd_infra
localstack    |     bootstrap.start_infra_locally()
localstack    |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 216, in start_infra_locally
localstack    |     return infra.start_infra()
localstack    |   File "/opt/code/localstack/localstack/services/infra.py", line 407, in start_infra
localstack    |     raise e
localstack    |   File "/opt/code/localstack/localstack/services/infra.py", line 385, in start_infra
localstack    |     t1 = plugin.start(asynchronous=True)
localstack    |   File "/opt/code/localstack/localstack/services/infra.py", line 63, in start
localstack    |     return self.start_function(**kwargs)
localstack    |   File "/opt/code/localstack/localstack/services/infra.py", line 134, in start_cloudwatch_logs
localstack    |     return start_moto_server('logs', port, name='CloudWatch Logs', asynchronous=asynchronous)
localstack    |   File "/opt/code/localstack/localstack/services/infra.py", line 264, in start_moto_server
localstack    |     return multiserver.start_api_server(key, backend_port or port)
localstack    |   File "/opt/code/localstack/localstack/utils/server/multiserver.py", line 70, in start_api_server
localstack    |     start_server_process(server_port)
localstack    |   File "/opt/code/localstack/localstack/utils/server/multiserver.py", line 97, in start_server_process
localstack    |     wait_for_port_open(port, retries=10, sleep_time=1)
localstack    |   File "/opt/code/localstack/localstack/utils/common.py", line 375, in wait_for_port_open
localstack    |     return retry(check, sleep=sleep_time, retries=retries)
localstack    |   File "/opt/code/localstack/localstack/utils/common.py", line 408, in retry
localstack    |     raise raise_error
localstack    |   File "/opt/code/localstack/localstack/utils/common.py", line 404, in retry
localstack    |     return function(**kwargs)
localstack    |   File "/opt/code/localstack/localstack/utils/common.py", line 373, in check
localstack    |     raise Exception()
localstack    | Exception
localstack    |
localstack    | ERROR:
localstack    | (. .venv/bin/activate; exec bin/localstack start --host)
localstack    | make: *** [Makefile:47: infra] Error 1
localstack    | 2019-08-10 12:53:33,938 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack    | Starting local dev environment. CTRL-C to quit.
localstack    | cannot import name 'cognito_starter'
localstack    | Starting mock S3 (http port 4572)...
localstack    | Starting mock SQS (http port 4576)...
localstack    | Starting mock DynamoDB (http port 4569)...
localstack    | Starting mock Lambda service (http port 4574)...
localstack    | Starting mock CloudFormation (http port 4581)...
localstack    | Starting mock CloudWatch Logs (http port 4586)...
localstack    | Initializing DynamoDB Local with the following configuration:
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-109) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Hi @ilan-deepreach apologies for the long delay on this one. We believe that this issue should be fixed in the meantime (we've moved away from ElasticMQ in the meanwhile). Can you please pull the `latest` image and give it another try? Please let us know if the problem persists. Thanks
