### ISSUE TITLE
Lambda Permission Issue

### ISSUE THREAD

**Issue by Deblob12** [localstack/localstack#1488]
Getting this error trying to deploy lambda functions

```
localstack_1  | 2019-08-14T22:38:36:WARNING:localstack.utils.common: Unable to open zip file: /tmp/localstack/zipfile.8b4355ad/original_lambda_archive.zip: [Errno 13] Permission denied: '/tmp/localstack/zipfile.8b4355ad/original_lambda_archive.zip'
localstack_1  | 2019-08-14T22:38:36:WARNING:localstack.services.awslambda.lambda_api: Unknown error: [Errno 13] Permission denied: '/tmp/localstack/zipfile.8b4355ad/original_lambda_archive.zip' Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 652, in create_function
localstack_1  |     result = set_function_code(data['Code'], lambda_name)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 516, in set_function_code
localstack_1  |     unzip(tmp_file, lambda_cwd)
localstack_1  |   File "/opt/code/localstack/localstack/utils/common.py", line 673, in unzip
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/utils/common.py", line 670, in unzip
localstack_1  |     zip_ref = zipfile.ZipFile(path, 'r')
localstack_1  |   File "/usr/lib/python3.6/zipfile.py", line 1113, in __init__
localstack_1  |     self.fp = io.open(file, filemode)
localstack_1  | PermissionError: [Errno 13] Permission denied: '/tmp/localstack/zipfile.8b4355ad/original_lambda_archive.zip'
```

My docker-compose file is as follow
```
version: "3"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4568-4597:4568-4597"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=dynamodb,s3,lambda,cloudwatchlogs,iam,sqs,kinesis,sns
      - DEFAULT_REGION=us-west-2
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_EXECUTION_ENV=True
      #- LAMBDA_EXECUTOR=docker-reuse
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
    user: root
```

**Comment by Deblob12** [comment]
Managed to solve problem by setting up file sharing with /tmp/localstack instead of just /tmp
