### ISSUE TITLE
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://4667708e29b6:0/rules/myTestIot"

### ISSUE THREAD

**Issue by wesselvdv** [localstack/localstack#1531]
Using the new IoT core implementation I am running into this error when trying to deploy a lambda with an iot event.

The `4667708e29b6` is the docker container id.

```
2019-09-03T09:44:09:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response from CloudFormation (500) POST /: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
2019-09-03 09:44:09,432:API: Error on request:
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 303, in run_wsgi
  execute(self.server.app)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 291, in execute
  application_iter = app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/server.py", line 132, in __call__
  return backend_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
  return self.wsgi_app(environ, start_response)
stack_1  |
File "/usr/lib/python3.6/_collections_abc.py", line 762, in __iter__
  yield self._mapping[key]
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/cloudformation/parsing.py", line 410, in __getitem__
  resource_logical_id, resource_json, self, self._region_name)
File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 102, in parse_and_create_resource
  return _parse_and_create_resource(logical_id, resource_json, resources_map, region_name)
File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 157, in _parse_and_create_resource
  result = deploy_func(logical_id, resource_wrapped, stack_name=stack_name)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 608, in deploy_resource
  raise e
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 605, in deploy_resource
  result = function(**params)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
  return self._make_api_call(operation_name, kwargs)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/client.py", line 648, in _make_api_call
  operation_model, request_dict, request_context)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/client.py", line 667, in _make_request
  return self._endpoint.make_request(operation_model, request_dict)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
  return self._send_request(request_dict, operation_model)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/endpoint.py", line 137, in _send_request
  success_response, exception):
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/endpoint.py", line 231, in _needs_retry
  caught_exception=caught_exception, request_dict=request_dict)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
  return self._emitter.emit(aliased_event_name, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
  return self._emit(event_name, kwargs)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
  response = handler(**kwargs)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
  if self._checker(attempts, response, caught_exception):
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
  caught_exception)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 277, in _should_retry
  return self._checker(attempt_number, response, caught_exception)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
  caught_exception)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
  attempt_number, caught_exception)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
  raise caught_exception
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/endpoint.py", line 200, in _do_get_response
  http_response = self._send(request)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/endpoint.py", line 244, in _send
  return self.http_session.send(request)
File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/httpsession.py", line 282, in send
  raise EndpointConnectionError(endpoint_url=request.url, error=e)
stack_1  | botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://4667708e29b6:0/rules/myTestIot"
```

serverless.yml:
```yaml
service: api

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1

package:
  individually: true

plugins:
  - serverless-localstack

functions:
  userGet:
    handler: apiUserGet/index.handler
    events:
      - iot:
          name: "myTestIot"
          sql: "SELECT * FROM 'some_topic'"
          enabled: true
    environment:
      REGION: eu-central-1
      POOL_ID: eu-central-1_4c5bd1ada5514a6f859a1eb6a81467e4
custom:
  localstack:
    lambda:
      # Enable this flag to improve performance
      mountCode: False
    stages:
      - local
      - dev
      - staging
      - production
```

I monkey patched the error in #1530 which then results in the above error.

**Comment by whummer** [comment]
@wesselvdv  The port `0` in the output indicates that `iot` has not been configured/started. Can you see it in the list of services in the log output when starting up?

**Comment by wesselvdv** [comment]
@whummer You're completely right, total noob here. Forgot to add the iot service to the services env variable.
