### ISSUE TITLE
elastic search is not reachable from lamda

### ISSUE THREAD

**Issue by chrisrana** [localstack/localstack#1544]
I have lamda which create index in elastic search.I installed localstack using docker-compose in my local window 10 machine.
I create a lamda using aws create-function
`aws --endpoint-url=http://localhost:4574 lambda create-function --function-name=dev-dcindexer --runtime=python3.6 --role=r1 --handler=data-collection-indexerdata_collection_indexer/data_collection_indexer.lambda_handler --environment "Variables={AppName=myapp,EnvName=dev,LOG_LEVEL=DEBUG,UnitName=dcindexer,aws_region=us-west-2,es_endpoint=http://localhost:4571}" --zip-file fileb://c:/projects/data-services/data-collection-indexer.zip`

When i invoke the lamda it get error
 `aws --endpoint-url http://localhost:4574 lambda invoke --function-name lambda2 --payload '{....}'`

```
localstack_1  | [DEBUG] 2019-09-05T11:05:16.918Z        ca788f06-0974-4ec0-8adb-2cef7293e72b    Starting new HTTP connection (1): localhost:4571
localstack_1  |
localstack_1  | [WARNING]       2019-09-05T11:05:16.919Z        ca788f06-0974-4ec0-8adb-2cef7293e72b    HEAD http://localhost:4571/eai-c3585c2f-fc83-4b5e-873a-e0e6cd77c0b2-datacollection-index [status:N/A request:0.001s]
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/var/task/urllib3/connection.py", line 160, in _new_conn
localstack_1  |     (self._dns_host, self.port), self.timeout, **extra_kw)
localstack_1  |   File "/var/task/urllib3/util/connection.py", line 80, in create_connection
localstack_1  |     raise err
localstack_1  |   File "/var/task/urllib3/util/connection.py", line 70, in create_connection
localstack_1  |     sock.connect(sa)
localstack_1  | ConnectionRefusedError: [Errno 111] Connection refused
localstack_1  |
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  |
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/var/task/elasticsearch/connection/http_urllib3.py", line 217, in perform_request
localstack_1  |     method, url, body, retries=Retry(False), headers=request_headers, **kw
localstack_1  |   File "/var/task/urllib3/connectionpool.py", line 641, in urlopen
localstack_1  |     _stacktrace=sys.exc_info()[2])
localstack_1  |   File "/var/task/urllib3/util/retry.py", line 344, in increment
localstack_1  |     raise six.reraise(type(error), error, _stacktrace)
localstack_1  |   File "/var/task/urllib3/packages/six.py", line 686, in reraise
localstack_1  |     raise value
localstack_1  |   File "/var/task/urllib3/connectionpool.py", line 603, in urlopen
localstack_1  |     chunked=chunked)
localstack_1  |   File "/var/task/urllib3/connectionpool.py", line 355, in _make_request
localstack_1  |     conn.request(method, url, **httplib_request_kw)
localstack_1  |   File "/var/lang/lib/python3.6/http/client.py", line 1239, in request
localstack_1  |     self._send_request(method, url, body, headers, encode_chunked)
localstack_1  |   File "/var/lang/lib/python3.6/http/client.py", line 1285, in _send_request
localstack_1  |     self.endheaders(body, encode_chunked=encode_chunked)
localstack_1  |   File "/var/lang/lib/python3.6/http/client.py", line 1234, in endheaders
localstack_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
localstack_1  |   File "/var/lang/lib/python3.6/http/client.py", line 1026, in _send_output
localstack_1  |     self.send(msg)
localstack_1  |   File "/var/lang/lib/python3.6/http/client.py", line 964, in send
localstack_1  |     self.connect()
localstack_1  |   File "/var/task/urllib3/connection.py", line 183, in connect
localstack_1  |     conn = self._new_conn()
localstack_1  |   File "/var/task/urllib3/connection.py", line 169, in _new_conn
localstack_1  |     self, "Failed to establish a new connection: %s" % e)
localstack_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fba41862e10>: Failed to establish a new connection: [Errno 111] Connection refused
```

```
version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4597:4567-4597"
      - "${PORT_WEB_UI-8082}:${PORT_WEB_UI-8082}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker-reuse }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```

dc_index_body={"mapping":{....}}
I am able to connect to same elasticsearch using my sample program from my local machine
ES_CLUSTER_END_POINT = 'http://localhost:4571'
es = elasticsearch.Elasticsearch([ES_CLUSTER_END_POINT])
es.indices.create(index_name, dc_index_body)

Looks like issue because of  docker container  ? is

**Comment by chrisrana** [comment]
I was trying with elastic search url as http://localhost:4571 it didn't worked.
I did ifconfg and took  the IPv4 Address and it worked.
