### ISSUE TITLE
Issue with SQS Set Queue Attributes

### ISSUE THREAD

**Issue by adriangalera** [localstack/localstack#1551]
We are having an issue with the latest image of localstack (bc991b0bc3ce).
While creating an SQS and setting parameters we experience the following error:

```
localstack_1        | 2019-09-09T10:46:22:ERROR:localstack.services.generic_proxy: Error forwarding request: 'QueueUrl' Traceback (most recent call last):
localstack_1        |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 234, in forward
localstack_1        |     path=path, data=data, headers=forward_headers)
localstack_1        |   File "/opt/code/localstack/localstack/services/sqs/sqs_listener.py", line 53, in forward_request
localstack_1        |     self._set_queue_attributes(req_data)
localstack_1        |   File "/opt/code/localstack/localstack/services/sqs/sqs_listener.py", line 245, in _set_queue_attributes
localstack_1        |     queue_url = req_data['QueueUrl'][0]
localstack_1        | KeyError: 'QueueUrl'
```

From the logs I guess the `QueueUrl` is expected and it's not there. We don't see this behaviour in the last version (0.10.2).

**Comment by whummer** [comment]
Thanks for reporting @adriangalera . Can you please provide a small project, or sequence of CLI commands to reproduce this issue? Thanks!

**Comment by adriangalera** [comment]
I could not make it fail with aws-cli.
I was able to reproduce the issue using Java AWS SQS library:

```java
        AwsClientBuilder.EndpointConfiguration endpoint = new AwsClientBuilder.EndpointConfiguration(
            "http://localstack:4576", "us-east-1");

        ClientConfiguration cc = new ClientConfiguration();
        cc.setProtocol(Protocol.HTTP);

        AmazonSQSAsync sqsAsync = AmazonSQSAsyncClientBuilder.standard()
            .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials("foo", "foo")))
            .withEndpointConfiguration(endpoint)
            .withClientConfiguration(cc)
            .build();

        CreateQueueResult result1 = sqsAsync.createQueue("1551-test");
        CreateQueueResult result2 = sqsAsync.createQueue("1551-test-dlq");

        final String queueArn = "QueueArn";
        GetQueueAttributesResult dlqQueueAttributes = sqsAsync.getQueueAttributes(result2.getQueueUrl(),
                                                                                  Collections.singletonList(queueArn));
        final String dlqQueueArn = dlqQueueAttributes.getAttributes().get(queueArn);

        final Map<String, String> attributes = new HashMap<>();
        attributes.put("VisibilityTimeout", "60");
        attributes.put("MessageRetentionPeriod", "345600");
        attributes.put("RedrivePolicy", "{\"deadLetterTargetArn\":"
            + "\" " + dlqQueueArn + " \","
            + "\"maxReceiveCount\":\"20\"}");
        final String queueUrl = result1.getQueueUrl();

        sqsAsync.setQueueAttributes(queueUrl, attributes);
```

**Comment by HealthPDU** [comment]
I concur... using docker and the `localstack/localstack:0.10.2` the following test class runs correctly and I can verify the `VisibilityTimeout` has been amended.

```
public class LocalstackQueueAttributesIssue {
    private static final String LS_ENDPOINT = "http://localhost:4576";
    private static final String LS_REGION = "us-east-1";
    private final AmazonSQS sqs;

    public LocalstackQueueAttributesIssue() {
        System.setProperty("aws.accessKeyId", "test");
        System.setProperty("aws.secretKey", "test");

        sqs = AmazonSQSClientBuilder
                .standard()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(LS_ENDPOINT, LS_REGION))
                .withCredentials(new DefaultAWSCredentialsProviderChain())
                .build();
    }

    public void createQueue(String queueName) {
        try {
            CreateQueueResult createResult = sqs.createQueue(queueName);

            Map<String, String> mapItems = new HashMap<>();
            mapItems.put(QueueAttributeName.VisibilityTimeout.toString(), String.valueOf(60));

            SetQueueAttributesRequest request = new SetQueueAttributesRequest().withQueueUrl(createResult.getQueueUrl()).withAttributes(mapItems);
            sqs.setQueueAttributes(request);

        } catch (AmazonSQSException e) {
            if (!e.getErrorCode().equals("QueueAlreadyExists")) {
                throw e;
            }
        }
    }
}
```
yielding the following queue output attributes (all good 😄 )
```
{
   "ResponseMetadata": {
      "RequestId": "00000000-0000-0000-0000-000000000000"
   },
   "Attributes": {
      "VisibilityTimeout": "60",
      "DelaySeconds": "0",
      "ReceiveMessageWaitTimeSeconds": "0",
      "ApproximateNumberOfMessages": "0",
      "ApproximateNumberOfMessagesNotVisible": "0",
      "ApproximateNumberOfMessagesDelayed": "0",
      "CreatedTimestamp": "1568196860",
      "LastModifiedTimestamp": "1568196860",
      "QueueArn": "arn:aws:sqs:us-east-1:000000000000:test"
   }
}
```

**however**, with `localstack/localstack:latest` the same process throws the following stacktrace with the same errors noted in the docker logs as @adriangalera.
```
com.amazonaws.services.sqs.model.AmazonSQSException: null (Service: AmazonSQS; Status Code: 502; Error Code: 502 Bad Gateway; Request ID: null)

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2215)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2182)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2171)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeSetQueueAttributes(AmazonSQSClient.java:1921)
	at com.amazonaws.services.sqs.AmazonSQSClient.setQueueAttributes(AmazonSQSClient.java:1893)
	at uk.gov.health.sqs.LocalstackQueueAttributesIssue.createQueue(LocalstackQueueAttributesIssue.java:39)
	at uk.gov.health.sqs.LocalstackQueueAttributesIssueTest.successfulQueueCreate(LocalstackQueueAttributesIssueTest.java:10)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

fyi we are using the following sqs lib
```
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-sqs</artifactId>
            <version>1.11.505</version>
        </dependency>
```

**Comment by whummer** [comment]
Thanks for the detailed report @adriangalera @HealthPDU . This issue should be fixed in #1626 - can you please give it a try with the `latest` version of the Docker image?

**Comment by HealthPDU** [comment]
working fine for me with `latest` docker image (`sha256:fd759752748f2b6db024f17a449b18982c04e1e1a1e468647718bea27698dd76`) using the above scenario for update/set QueueAttributes

**Comment by whummer** [comment]
Awesome - thanks for confirming 👍
