### ISSUE TITLE
SdkClientException: Unable to verify integrity of data upload

### ISSUE THREAD

**Issue by tmohme-hypoport** [localstack/localstack#1552]
When trying to upload a simple ascii text document with the last line ending with a 0x0A character, I get the following error:

```
Caused by: com.amazonaws.SdkClientException: Unable to verify integrity of data upload. Client calculated content hash (contentMD5: opmPBimuydwwFlbLCEwgOA== in base 64) didn't match hash (etag: 1ee0a10dde358142a020b13bbfdbf831 in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (metadata.contentMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@76ab3d5, bucketName: fundingport.test, key: d2e22e95-1678-4fa7-8688-05b5b0ba4d2d)
	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1815) ~[aws-java-sdk-s3-1.11.626.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1749) ~[aws-java-sdk-s3-1.11.626.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1687) ~[aws-java-sdk-s3-1.11.626.jar:na]
```

If I remove the last 0x0A or add one character to the upload-file (i.e. It no longer ends with 0x0A), everything work well.

We're using `aws-java-sdk-s3:1.11.626`.
I got the hint for the possible reason/workaround from issue #359 ([thx blakeney](https://github.com/localstack/localstack/issues/359#issuecomment-519256329))

[uploadFailure.txt](https://github.com/localstack/localstack/files/3590075/uploadFailure.txt)

**Comment by whummer** [comment]
Thanks for reporting @tmohme-hypoport . The S3 upload logic has been significantly reworked in the meantime, particularly around leading and trailing newlines (`0x0A`).

This should be fixed in the latest version - please re-open this issue if the problem persists. Thanks
