### ISSUE TITLE
Failed to wire queue to topic

### ISSUE THREAD

**Issue by SachinJoshiTest** [localstack/localstack#1576]
I have created a queue as simple_queue on localstack SQS and a Topic as simple_topic on localstack SNS. While binding the queue to topic i am getting below error in my application.

```
Failed to wire http://localhost:4576/queue/simple_queue SQS queue to topic Topic(simple_topic,Some(http://localhost:4576/queue/simple_queue))
! com.amazonaws.services.sqs.model.AmazonSQSException: null (Service: AmazonSQS; Status Code: 502; Error Code: 502 Bad Gateway; Request ID: null)
```

Also on the localstack front i see below error.

```
2019-09-19T15:19:13:ERROR:localstack.services.generic_proxy: Error forwarding request: 'QueueUrl' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 239, in forward
    path=path, data=data, headers=forward_headers)
  File "/opt/code/localstack/localstack/services/sqs/sqs_listener.py", line 53, in forward_request
    self._set_queue_attributes(req_data)
  File "/opt/code/localstack/localstack/services/sqs/sqs_listener.py", line 245, in _set_queue_attributes
    queue_url = req_data['QueueUrl'][0]
KeyError: 'QueueUrl'

```

Note : I am using Mac OS version 10.14.6

**Comment by whummer** [comment]
Thanks for reporting @SachinJoshiTest . Please note that the format for queue URLs has changed recently, and we believe this issue should be fixed in the meantime. Can you please pull the `latest` version of the Docker image and give it another try? Please report here or re-open this issue if the problem persists. Thanks!
