### ISSUE TITLE
localstack errors when trying to connect from an iOS app 

### ISSUE THREAD

**Issue by jules15** [localstack/localstack#1578]
I'm trying to test an iOS app connection to Kinesis using localstack.

I'm using the latest localstack from master:

```
% git log| head
commit 6a2a26fbc5043f30e76b92456643339f6abf034d
Author: Sean Löfgren <SeanBE@users.noreply.github.com>
Date:   Wed Sep 18 16:07:27 2019 +0100

    clear tmp supervisord logs at container startup (#1567 )
```

For docker, I'm using `Docker Desktop (macos) 2.1.0.3 (38240/stable)`

On the client side, I'm using Amazon's iOS library: `aws-amplify/aws-sdk-ios v2.11.0`

This is the output from localstack the first time the client tries to send:

```% localstack start
!WARNING! - Running outside of Docker with LAMBDA_EXECUTOR=docker can lead to problems on your OS. The environment variable $LOCALSTACK_HOSTNAME may not be properly set in your Lambdas.
Starting local dev environment. CTRL-C to quit.
docker run -it -e SERVICES="kinesis" -e LOCALSTACK_HOSTNAME="localhost" -e DEFAULT_REGION="us-east-1" -e LOCALSTACK_HOSTNAME="localhost" --rm --privileged --name localstack_main -p 8080:8080   -p 4568:4568  -v "/private/var/folders/yg/rg_bfj255679vg3hz1p6l2100000gp/T/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/private/var/folders/yg/rg_bfj255679vg3hz1p6l2100000gp/T/localstack" "localstack/localstack" 
Waiting for all LocalStack services to be ready
2019-09-19 17:20:57,620 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-09-19 17:20:57,623 INFO supervisord started with pid 12
2019-09-19 17:20:58,629 INFO spawned: 'dashboard' with pid 20
2019-09-19 17:20:58,631 INFO spawned: 'infra' with pid 21
(. .venv/bin/activate; bin/localstack web)
2019-09-19 17:20:58,635 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; exec bin/localstack start --host)
2019-09-19 17:20:59,639 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cannot import name 'dns_server'
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
Starting local dev environment. CTRL-C to quit.
cannot import name 'dns_server'
Starting mock Kinesis (http port 4568)...
Waiting for all LocalStack services to be ready
Ready.
2019-09-19T17:26:50:ERROR:localstack.services.generic_proxy: Error forwarding request: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 239, in forward
    path=path, data=data, headers=forward_headers)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py", line 22, in forward_request
    data = json.loads(to_str(data))
  File "/opt/code/localstack/localstack/utils/common.py", line 640, in to_str
    return obj.decode(encoding, errors) if isinstance(obj, six.binary_type) else obj
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

On the client, this is the error from the API:

```The operation couldn’t be completed. (com.amazonaws.AWSFirehoseErrorDomain error 0.)```

I'm configuring the client to point to an address on a LAN:
```
        let endPoint = AWSEndpoint(region: .USEast1,
                                   service: .Firehose,
                                   url: URL(string: "http://172.16.222.23:4568/"))
        
        let credentialsProvider = AWSStaticCredentialsProvider(accessKey: "AWS_ACCESS_KEY", secretKey: "AWS_SECRET_KEY")

        guard let serviceConfiguration = AWSServiceConfiguration(region: .USEast1,
                                                                 endpoint:endPoint,
                                                                 credentialsProvider: credentialsProvider) else
        { fatalError("Could not initialize AWSServiceConfiguration") }
```

Any pointers?

**Comment by jules15** [comment]
I forgot to add, this is what gets sent by the client as seen by `nc`:

```% nc -l -p 4568
POST / HTTP/1.1
Host: 172.16.222.23
Accept: */*
Authorization: AWS4-HMAC-SHA256 Credential=AWS_ACCESS_KEY/20190919/us-east-1/firehose/aws4_request, SignedHeaders=content-encoding;content-type;host;user-agent;x-amz-date;x-amz-target, Signature=51b11da7694a245e610559da825267a2136a85d413982b748d48db9437830893
Content-Encoding: gzip
X-Amz-Date: 20190919T180522Z
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Content-Type: application/x-amz-json-1.1
Content-Length: 485
User-Agent: aws-sdk-iOS/2.7.3 iOS/12.4.1 en_US
Connection: keep-alive
X-Amz-Target: Firehose_20150804.PutRecordBatch
<elided binary crap>
```
