### ISSUE TITLE
ElastiCache mock service

### ISSUE THREAD

**Issue by whummer** [localstack/localstack#158]
We should mock out the ElastiCache API and spin up a local Redis as backend implementation.

**Comment by musketyr** [comment]
Thanks for reposting this issue @whummer

**Comment by yandreiy** [comment]
+1

**Comment by kotowick** [comment]
+1

**Comment by alex-birch** [comment]
+1

**Comment by namitcy** [comment]
+1

**Comment by zachschultz** [comment]
+1

**Comment by rafunchik** [comment]
+1

**Comment by mapyo** [comment]
+1

**Comment by jonathanhle** [comment]
+1

**Comment by xiangzprime8** [comment]
+1 
Having trouble connecting to redis container from within localstack Lambda. Tried localhost/127.0.0.1/redis with no luck.

	{ Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379 }

**Comment by nhiguchi** [comment]
+1

**Comment by Tarakan1992** [comment]
+1

**Comment by Larkhis** [comment]
+1

**Comment by whummer** [comment]
Hi @musketyr @yandreiy @kotowick @alex-birch @namitcy @zachschultz @mapyo @rafunchik @jonathanhle @xiangzprime8 @nhiguchi @Tarakan1992 @Larkhis 

Initial support for ElastiCache has been added to the LocalStack Pro edition. 🎉 If you want to check it out, please head over to the website and sign up for private beta access: https://localstack.cloud

**Comment by mmanikar** [comment]
Is there a plan for this to be made available on the free version as well?
