### ISSUE TITLE
Local stack is not starting throwing different errors `Error forwarding request: ` 

### ISSUE THREAD

**Issue by Techno-Medha** [localstack/localstack#1587]
Hi team,
I am getting this when I start `make infra` 

> Starting local dev environment. CTRL-C to quit.
cannot import name 'dns_server' from 'localstack_ext.services' (unknown location)
Starting mock S3 (http port 4572)...
Starting mock SNS (http port 4575)...
2019-09-21T13:11:08:INFO:localstack.multiserver: Starting multi API server process on port 51492
Starting mock SQS (http port 4576)...
Starting mock DynamoDB (http port 4569)...
Starting mock Lambda service (http port 4574)...
Starting mock CloudWatch Logs (http port 4586)...
Ready.

But when I do `http://localhost:4569` it throws error and doesnt show it started.
Below are the errors I am getting

I am getting these errors 

> 2019-09-21T13:15:05:ERROR:localstack.services.generic_proxy: Error forwarding request: the JSON object must be str, bytes or bytearray, not NoneType Traceback (most recent call last):
  File "/Users/****/workspaces/others/localstack/localstack/services/generic_proxy.py", line 240, in forward
    path=path, data=data, headers=forward_headers)
  File "/Users/****/workspaces/others/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 35, in forward_request
    data = json.loads(to_str(data))
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

Error 2:

> 2019-09-21T13:14:11:ERROR:localstack.services.generic_proxy: Error forwarding request: 'QueueUrl' Traceback (most recent call last):
  File "/Users/******/workspaces/others/localstack/localstack/services/generic_proxy.py", line 240, in forward
    path=path, data=data, headers=forward_headers)
  File "/Users/*****/workspaces/others/localstack/localstack/services/sqs/sqs_listener.py", line 53, in forward_request
    self._set_queue_attributes(req_data)
  File "/Users/******/workspaces/others/localstack/localstack/services/sqs/sqs_listener.py", line 245, in _set_queue_attributes
    queue_url = req_data['QueueUrl'][0]
KeyError: 'QueueUrl'`

Please help on this its a been a blocker for me.

**Comment by Techno-Medha** [comment]
This is because I was hitting http://localhost:4569 which isn't a user interface. So its throwing error.But if I create tables using aws cli and do some operations it just works fine without any issue.
