### ISSUE TITLE
Can't invoke API gateways created on localstack

### ISSUE THREAD

**Issue by larquin** [localstack/localstack#1593]
If i stand up localstack (using `docker-compose`, `localstack/localstack:latest`), I can create an API gateway with the following: 

```
aws api-gateway --endpoint=http://localhost:4567 create-rest-api --region us-west-2 --name test
```

This seems to succeed: 

```
{
    "id": "ou9h9fggf0",
    "name": "test2",
    "createdDate": 1569362068
}
```

I can verify it was created with another AWS CLI call: 

```
aws apigateway --endpoint=http://localhost:4567 get-rest-apis
```

which returns as expected: 

```
{
    "items": [
          {
            "id": "ou9h9fggf0",
            "name": "test2",
            "createdDate": 1569362080
        }
    ]
}
```

However, when I ask localstack to show me restapis: 

`curl http://localhost:4567/restapis`

I get a blank return value: 

`{"item":[]}`

Since localstack isn't picking this up, I'm not super surprised that when I attempt to curl any endpoints I've associated with this API, I get a `404` not found: 

`curl http://localhost:4567/restapis/ou9h9fggf0/test`

Similarly, if I request this particular rest API directly from localstack via: 

`curl http://locahost:4567/restapis/ou9h9fggf0`

It returns a status `500` issue. The log for such a request looks like this: 

```
2019-09-24 21:58:52,630:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/server.py", line 132, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/utils.py", line 140, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/apigateway/responses.py", line 46, in restapis_individual
    rest_api = self.backend.get_rest_api(function_id)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/apigateway/models.py", line 525, in get_rest_api
    rest_api = self.apis[function_id]
KeyError: 'ou9h9fggf0'
```

Any suggestions on something I might have missed?

**Comment by jgwconsulting** [comment]
I'm having exactly the same problem.

**Comment by ballwood** [comment]
@larquin we had this problem too. We have our terraform scripts set to eu-west-1 whereas the DEFAULT_REGION is set in docker.compose.yml is us-east-1. changed it to eu-west-1 and it worked fine.

**Comment by kvillega** [comment]
Hi, I'm encountering the same problem with serverless, it seems to work and i get the endpoints back but /restapis is blank. What version of localstack are you guys using? I used 0.10.5

**Comment by jrindfleisch** [comment]
@kvillega i am in the same boat.  Localstack doesn't seem to be honoring the DEFAULT_REGION I have set in docker-compose.  The `/restapis` seems to always just pull back those apis created in `us-east-1`.  If you create a gateway through the cli in the `us-east-1` region, it pulls it back on `/restapis`.

**Comment by jrindfleisch** [comment]
looks like there is already an issue around this: https://github.com/localstack/localstack/issues/2004

**Comment by whummer** [comment]
Thanks for reporting @larquin @jgwconsulting @ballwood @kvillega @jrindfleisch . This could be a region issue, as @ballwood mentioned. Can you please make sure that the region of your client (i.e., in the serverless config) matches the `DEFAULT_REGION` configured on the server side? Please let us know if that solves your issue. If not, then please share a small, self-contained example (including region configs) to help reproduce this issue. Thanks!
