### ISSUE TITLE
ERROR:localstack.services.generic_proxy  on win10 when setting data direcotory

### ISSUE THREAD

**Issue by wubigo** [localstack/localstack#1598]
```
git clone git@github.com:localstack/localstack.git
git fetch --all
git checkout tags/v0.10.3 -b v0.10.3
```

change docker-compose.yml

```
 DATA_DIR=${DATA_DIR-/tmp/localstack/data }


 volumes:
      - "${TMPDIR:-d:/tmp/localstack}:/tmp/localstack"
```

```
localstack_1  | 2019-09-26T09:59:38:ERROR:localstack.services.generic_proxy: Error forwarding request: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
localstack_1  |     chunked=chunked)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
localstack_1  |     six.raise_from(e, None)
localstack_1  |   File "<string>", line 2, in raise_from
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
localstack_1  |     httplib_response = conn.getresponse()
localstack_1  |   File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
localstack_1  |     response.begin()
localstack_1  |   File "/usr/lib/python3.6/http/client.py", line 297, in begin
localstack_1  |     version, status, reason = self._read_status()
localstack_1  |   File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
localstack_1  |     raise RemoteDisconnected("Remote end closed connection without"
localstack_1  | http.client.RemoteDisconnected: Remote end closed connection without response
localstack_1  |
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  |
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
localstack_1  |     timeout=timeout
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
localstack_1  |     _stacktrace=sys.exc_info()[2])
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 368, in increment
localstack_1  |     raise six.reraise(type(error), error, _stacktrace)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
localstack_1  |     raise value.with_traceback(tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
localstack_1  |     chunked=chunked)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
localstack_1  |     six.raise_from(e, None)
localstack_1  |   File "<string>", line 2, in raise_from
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
localstack_1  |     httplib_response = conn.getresponse()
localstack_1  |   File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
localstack_1  |     response.begin()
localstack_1  |   File "/usr/lib/python3.6/http/client.py", line 297, in begin
localstack_1  |     version, status, reason = self._read_status()
localstack_1  |   File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
localstack_1  |     raise RemoteDisconnected("Remote end closed connection without"
localstack_1  | urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
localstack_1  |
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  |
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 266, in forward
localstack_1  |     headers=forward_headers, stream=True)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/requests/api.py", line 116, in post
localstack_1  |     return request('post', url, data=data, json=json, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/requests/api.py", line 60, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
localstack_1  |     raise ConnectionError(err, request=request)
localstack_1  | requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
localstack_1  |
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | Waiting for all LocalStack services to be ready
Gracefully stopping... (press Ctrl+C again to force)
Stopping localstack_localstack_1 ... done

```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-123) by [Unito](https://www.unito.io/learn-more)

**Comment by wubigo** [comment]
there is no error if the DATA_DIR is empty or not set

**Comment by whummer** [comment]
Thanks for reporting @wubigo - this is a pretty old issue, and there have been various enhancements in the startup logic in the meantime. Closing - please let us know if the problem persists. (Please note that persistence support is currently limited to a few basic APIs only in the open source version of LocalStack.) Thanks
