### ISSUE TITLE
Resource Not Found - DynamoDbStreams

### ISSUE THREAD

**Issue by thecherrytree** [localstack/localstack#1655]
I'm running serverless offline with localstack and I'm trying to get Dynamodb Streams to trigger a lambda function. I've really not had any success getting my functions to register after enabling the stream and creating the event-source-mapping. 

As you can see below:

I can enable the stream:

```
awslocal dynamodbstreams list-streams
{
    "Streams": [
        {
            "StreamArn": "arn:aws:dynamodb:us-east-1:000000000000:table/fte-dev/stream/2019-10-16T14:24:00.499",
            "TableName": "fte-dev",
            "StreamLabel": "2019-10-16T14:24:00.499"
        }
    ],
    "LastEvaluatedStreamArn": "TODO"
}

```

I have registered event-source-mappings:
```
awslocal lambda list-event-source-mappings
{
    "EventSourceMappings": [
        {
            "UUID": "0e34b584-1260-4c4e-8f85-665d62d83517",
            "BatchSize": 100,
            "EventSourceArn": "arn:aws:dynamodb:us-east-1:000000000000:table/fte-dev",
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:dynamodb-events-trigger",
            "LastModified": 1571235856.0,
            "LastProcessingResult": "OK",
            "State": "Enabled",
            "StateTransitionReason": "User action"
        }
    ]
}
```

But no functions:
```
awslocal lambda list-functions --endpoint-url http://localhost:4574
{
    "Functions": []
}
```

So the result is that no lambda is ever triggered. There are no logs in the localstack container either.

So I decided to go another route and use **serverless-plugin-offline-dynamodb-stream**.

When I did this, I started getting error logging. Essentially, I can see the same event-source-mappings, stream, and no functions. But I ended up getting a new error which I registered here (https://github.com/orchestrated-io/serverless-plugin-offline-dynamodb-stream/issues/14), but I noticed that in my localstack container logging there was a new error, and the the errors show by the **serverless-plugin-offiline-dynamodb-stream** seem to be bubbling up errors from localstack. Here is what I saw in the container:

```
Waiting for all LocalStack services to be ready
2019-10-16 14:23:54,654 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-10-16 14:23:54,659 INFO supervisord started with pid 17
2019-10-16 14:23:55,662 INFO spawned: 'dashboard' with pid 23
2019-10-16 14:23:55,670 INFO spawned: 'infra' with pid 25
(. .venv/bin/activate; bin/localstack web)
2019-10-16 14:23:55,671 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; exec bin/localstack start --host)
2019-10-16 14:23:56,678 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-10-16T14:23:57:WARNING:bootstrap.py: Unable to load plugins from file /opt/code/localstack/.venv/lib/python3.6/site-packages/localstack_ext/plugins.py: No module named 'localstack_ext.utils.aws.aws_models'
Starting local dev environment. CTRL-C to quit.
Starting mock S3 (http port 4572)...
Starting mock SNS (http port 4575)...
Starting mock STS (http port 4592)...
Starting mock IAM (http port 4593)...
Starting mock API Gateway (http port 4567)...
Starting mock DynamoDB (http port 4569)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Lambda service (http port 4574)...
Starting mock Kinesis (http port 4568)...
Starting mock CloudFormation (http port 4581)...
Starting mock CloudWatch (http port 4582)...
Starting mock CloudWatch Logs (http port 4586)...
Starting mock StepFunctions (http port 4585)...
Initializing DynamoDB Local with the following configuration:
Listening at http://:::4565
Port:   4564
InMemory:       true
DbPath: null
SharedDb:       true
shouldDelayTransientStatuses:   false
CorsParams:     *

Step Functions Local
Version: 1.4.0
Build: 2019-09-18
2019-10-16 14:23:59.358: Configure [Account] to [000000000000]
2019-10-16 14:23:59.359: Configure [Region] to [us-east-1]
2019-10-16 14:23:59.359: Configure [Lambda Endpoint] to [http://localhost:4574]
2019-10-16 14:23:59.359: Configure [DynamoDB Endpoint] to [http://localhost:4569]
2019-10-16 14:23:59.360: Configure [SQS Endpoint] to [http://localhost:0]
2019-10-16 14:23:59.360: Configure [SNS Endpoint] to [http://localhost:4575]
2019-10-16 14:23:59.366: Loaded credentials from environment
2019-10-16 14:23:59.366: Starting server on port 8083 with account 000000000000, region us-east-1
2019-10-16T14:23:58:INFO:localstack.multiserver: Starting multi API server process on port 51492
2019-10-16 14:23:58,931:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
2019-10-16 14:23:58,931:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
2019-10-16 14:23:58,931:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
2019-10-16 14:23:58,934:API:  * Running on http://0.0.0.0:4592/ (Press CTRL+C to quit)
2019-10-16 14:23:58,934:API:  * Running on http://0.0.0.0:4592/ (Press CTRL+C to quit)
2019-10-16 14:23:58,934:API:  * Running on http://0.0.0.0:4592/ (Press CTRL+C to quit)
2019-10-16 14:23:58,938:API:  * Running on http://0.0.0.0:4557/ (Press CTRL+C to quit)
2019-10-16 14:23:58,938:API:  * Running on http://0.0.0.0:4557/ (Press CTRL+C to quit)
2019-10-16 14:23:58,938:API:  * Running on http://0.0.0.0:4557/ (Press CTRL+C to quit)
2019-10-16 14:23:58,948:API:  * Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
2019-10-16 14:23:58,948:API:  * Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
2019-10-16 14:23:58,948:API:  * Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
2019-10-16T14:23:58:DEBUG:localstack.services.awslambda.lambda_executors: Getting all lambda containers names.
2019-10-16T14:23:58:DEBUG:localstack.services.awslambda.lambda_executors: docker ps -a --filter="name=localstack_lambda_*" --format "{{.Names}}"
2019-10-16T14:23:58:DEBUG:localstack.services.awslambda.lambda_executors: Removing 0 containers.
2019-10-16T14:23:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
Waiting for all LocalStack services to be ready
2019-10-16 14:24:04,087:API: 127.0.0.1 - - [16/Oct/2019 14:24:04] "GET / HTTP/1.1" 200 -
Ready.
14:24:22.825 [qtp555273695-19] WARN  com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler - DynamoDBLocalServiceException exception occured
com.amazonaws.services.dynamodbv2.exceptions.DynamoDBLocalServiceException: Requested resource not found: Stream: arn:aws:dynamodb:us-east-1:000000000000:table/fte-dev/stream/2019-10-16T14:24:00.499 not found
at com.amazonaws.services.dynamodbv2.exceptions.AWSExceptionFactory.buildLocalServiceException(AWSExceptionFactory.java:93) ~[DynamoDBLocal.jar:?]
at com.amazonaws.services.dynamodbv2.exceptions.AWSExceptionFactory.buildAWSException(AWSExceptionFactory.java:58) ~[DynamoDBLocal.jar:?]
at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.describeStream(LocalDynamoDBStreamsClient.java:138) ~[DynamoDBLocal.jar:?]
at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.describeStream(LocalDynamoDBRequestHandler.java:266) ~[DynamoDBLocal.jar:?]
at com.amazonaws.services.dynamodbv2.local.dispatchers.DescribeStreamDispatcher.enact(DescribeStreamDispatcher.java:19) ~[DynamoDBLocal.jar:?]
at com.amazonaws.services.dynamodbv2.local.dispatchers.DescribeStreamDispatcher.enact(DescribeStreamDispatcher.java:11) ~[DynamoDBLocal.jar:?]
at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.packageDynamoDBResponse(LocalDynamoDBServerHandler.java:373) [DynamoDBLocal.jar:?]
at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.handle(LocalDynamoDBServerHandler.java:460) [DynamoDBLocal.jar:?]
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1024) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.Server.handle(Server.java:370) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jetty-http-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668) [jetty-io-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) [jetty-io-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.12.v20130726.jar:8.1.12.v20130726]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
2019-10-16T14:24:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:25:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:26:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:27:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:28:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:29:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:30:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:31:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:32:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:33:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:34:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:35:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:36:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:37:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:38:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:39:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:40:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:41:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:42:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:43:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:44:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:45:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:46:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:47:58:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:48:57:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:49:57:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:50:57:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:51:57:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:52:57:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:53:57:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:54:57:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:55:57:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2019-10-16T14:56:57:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.

```

**Comment by workmanw** [comment]
@thecherrytree We also ran into this. I went back to when it was working and noticed that the problem is the list-streams endpoint returns a region when it should return `ddblocal`. 

It looks like starting with 0.10.3 the `list-streams` action would return `us-east-1` instead of `ddblocal`. If I replace that it continues to work.
