### ISSUE TITLE
The assume_role action has not been implemented error

### ISSUE THREAD

**Issue by jbentus** [localstack/localstack#1663]
Hello,

I am running the dockerd version of `localstack:0.10.3` and when I do:
 `aws sts assume-role --role-arn arn:aws:iam::000000000000:role/rd_role --role-session-name s3-access-example --endpoint-url http://localhost:4593` localstack returns http 500 error with the following stacktrace:

```
localstack    | 2019-10-19 23:19:43,352:API: 127.0.0.1 - - [19/Oct/2019 23:19:43] "POST / HTTP/1.1" 500 -
localstack    | 2019-10-19 23:19:43,360:API: Error on request:                     localstack    | Traceback (most recent call last):                                 localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 303, in run_wsgi
localstack    |     execute(self.server.app)                                       localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 291, in execute
localstack    |     application_iter = app(environ, start_response)                localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/server.py", line 132, in __call__
localstack    |     return backend_app(environ, start_response)                    localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
localstack    |     return self.wsgi_app(environ, start_response)                  localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
localstack    |     response = self.handle_exception(e)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
localstack    |     reraise(exc_type, exc_value, tb)                               localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
localstack    |     raise value                                                    localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
localstack    |     response = self.full_dispatch_request()                        localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
localstack    |     rv = self.handle_user_exception(e)                             localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
localstack    |     reraise(exc_type, exc_value, tb)                               localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
localstack    |     raise value                                                    localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
localstack    |     rv = self.dispatch_request()
localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
localstack    |     return self.view_functions[rule.endpoint](**req.view_args)     localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/utils.py", line 140, in __call__
localstack    |     result = self.callback(request, request.url, {})               localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 168, in dispatch
localstack    |     return cls()._dispatch(*args, **kwargs)                        localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 259, in _dispatch
localstack    |     return self.call_action()                                      localstack    |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 353, in call_action
localstack    |     "The {0} action has not been implemented".format(action)) 
localstack    | NotImplementedError: The assume_role action has not been implemented
```

The repo's readme file says v0.2.10: Added AWS assume role functionality.

I appreciate your help. Thank you.

**Comment by whummer** [comment]
Thanks for reporting @jbentus . This should be fixed in #2317 - can you please give it a try with the latest version of the Docker image? Please report here if the problem persists. Thanks!
