### ISSUE TITLE
Lambdas fail to return result seemingly due to attempting to recreate their own log-group.

### ISSUE THREAD

**Issue by Jaystified** [localstack/localstack#1686]
Probably related to #1643 , but what appears to happen seems different (at least the error is).

From what I can see, the lambda executes successfully, but then fails to return the result, returning the following instead:
```json
{
    "Type": "Server",
    "message": "Error executing Lambda function arn:aws:lambda:ap-northeast-1:000000000000:function:service-stage-functionName: module 'botocore.errorfactory' has no attribute 'ResourceAlreadyExistsException' Traceback (most recent call last):\n  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 106, in _store_logs\n    logs_client.create_log_group(logGroupName=log_group_name)\n  File \"/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/client.py\", line 661, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.errorfactory.ResourceAlreadyExistsException: An error occurred (ResourceAlreadyExistsException) when calling the CreateLogGroup operation: The specified log group already exists\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 339, in run_lambda\n    event, context=context, version=version, asynchronous=asynchronous)\n  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 81, in execute\n    return do_execute()\n  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 70, in do_execute\n    self._store_logs(func_details, log_output, invocation_time)\n  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 107, in _store_logs\n    except botocore.errorfactory.ResourceAlreadyExistsException:\nAttributeError: module 'botocore.errorfactory' has no attribute 'ResourceAlreadyExistsException'\n",
    "__type": "InternalFailure"
}
```

Looking at the localstack end I see the following log:

```
...(lambda execution log, SUCCESS etc)...
> REPORT RequestId: 00e1e000-0e00-000c-0000-8ccf00ab00ba	Duration: 52.74 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 5 MB	
> nohup: failed to run command 'python': No such file or directory
2019-10-25T11:46:25:WARNING:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:ap-northeast-1:000000000000:function:service-stage-functionName: module 'botocore.errorfactory' has no attribute 'ResourceAlreadyExistsException' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 106, in _store_logs
    logs_client.create_log_group(logGroupName=log_group_name)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceAlreadyExistsException: An error occurred (ResourceAlreadyExistsException) when calling the CreateLogGroup operation: The specified log group already exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 339, in run_lambda
    event, context=context, version=version, asynchronous=asynchronous)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 81, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 70, in do_execute
    self._store_logs(func_details, log_output, invocation_time)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 107, in _store_logs
    except botocore.errorfactory.ResourceAlreadyExistsException:
AttributeError: module 'botocore.errorfactory' has no attribute 'ResourceAlreadyExistsException'
```

Will update if I am able to create an easily reproducible case!

**Comment by whummer** [comment]
Thanks for the error report @Jaystified . This should be fixed in #1690 - we should now be more resilient to duplicate creation of log groups. Please report here if the problem persists.
