### ISSUE TITLE
Can't create an ec2 instance with  terraform

### ISSUE THREAD

**Issue by gberlotperalta** [localstack/localstack#1692]
I was able to create a simple S3 bucket with terraform.

How long it could take to create an ec2 instance, I tried to create one with terraform and It has been running for more than 0.5hrs and is still trying to create it.
Is there a way to see a log about it or something to do in order to understand why this process never ends ? Any suggestion, idea, etc will be really appreciated.

**Comment by bgaisford** [comment]
I'm seeing the same behavior using pro version installed/setup today - within the logstack console I'm seeing:
```
2019-11-07T18:09:20:ERROR:localstack.services.generic_proxy: Error forwarding request: Unsupported operating system Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 240, in forward
    path=path, data=data, headers=forward_headers)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/localstack_ext/services/ec2/ec2_listener.py", line 29, in forward_request
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/localstack_ext/services/ec2/ec2_listener.py", line 16, in install_vm_env
Exception: Unsupported operating system
```
The terraform resource config looks like this:
```
resource "aws_instance" "web" {
  ami           = "ami-123"
  instance_type = "t2.micro"

  tags = {
    Name = "HelloLocalStack"
  }
}
```

**Comment by stebo23** [comment]
Same here on Linux. I cannot create an EC2 instance, because terraform always tries to create a new instance and then waits for completion forever.

My terraform script:

```
provider "aws" {
  access_key                  = "000000000000"
  region                       = "us-east-1"
  s3_force_path_style         = true
  secret_key                  = "000000000000"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    apigateway     = "http://localhost:4567"
    cloudformation = "http://localhost:4581"
    cloudwatch     = "http://localhost:4582"
    dynamodb       = "http://localhost:4569"
    es             = "http://localhost:4578"
    firehose       = "http://localhost:4573"
    iam            = "http://localhost:4593"
    kinesis        = "http://localhost:4568"
    lambda         = "http://localhost:4574"
    route53        = "http://localhost:4580"
    redshift       = "http://localhost:4577"
    s3             = "http://localhost:4572"
    secretsmanager = "http://localhost:4584"
    ses            = "http://localhost:4579"
    sns            = "http://localhost:4575"
    sqs            = "http://localhost:4576"
    ssm            = "http://localhost:4583"
    stepfunctions  = "http://localhost:4585"
    sts            = "http://localhost:4592"
    ec2            = "http://localhost:4597"
  }
}

resource "aws_instance" "example" {
  ami           = "ami-b374d5a5"
  instance_type = "t2.micro"
}
```

I use docker to start localstack:

`docker run -p 4592:4592 -p 4597:4597 -p 4572:4572 -p 8080:8080 -e SERVICES=sts,ec2,s3 -e DEFAULT_REGION=us-east-1 localstack/localstack`

**Comment by usmangani1** [comment]
@stebo23 @gberlotperalta 

Thanks for raising the issue.We have tried to reproduce the issue with the script attached here with the latest version of localstack and we are not able to reproduce the issue.Please find the response of the command below.

```
 $ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_instance.example will be created
  + resource "aws_instance" "example" {
      + ami                          = "ami-b374d5a5"
      + arn                          = (known after apply)
      + associate_public_ip_address  = (known after apply)
      + availability_zone            = (known after apply)
      + cpu_core_count               = (known after apply)
      + cpu_threads_per_core         = (known after apply)
      + get_password_data            = false
      + host_id                      = (known after apply)
      + id                           = (known after apply)
      + instance_state               = (known after apply)
      + instance_type                = "t2.micro"
      + ipv6_address_count           = (known after apply)
      + ipv6_addresses               = (known after apply)
      + key_name                     = (known after apply)
      + outpost_arn                  = (known after apply)
      + password_data                = (known after apply)
      + placement_group              = (known after apply)
      + primary_network_interface_id = (known after apply)
      + private_dns                  = (known after apply)
      + private_ip                   = (known after apply)
      + public_dns                   = (known after apply)
      + public_ip                    = (known after apply)
      + secondary_private_ips        = (known after apply)
      + security_groups              = (known after apply)
      + source_dest_check            = true
      + subnet_id                    = (known after apply)
      + tenancy                      = (known after apply)
      + volume_tags                  = (known after apply)
      + vpc_security_group_ids       = (known after apply)

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
 }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_instance.example: Creating...
aws_instance.example: Still creating... [10s elapsed]
aws_instance.example: Creation complete after 10s [id=i-4124ebb8bdcf0c017]
```
Please try this with the latest version of localstack and let us know in case if you see any issues with the same.Thanks.

**Comment by whummer** [comment]
Thanks for reporting @gberlotperalta @bgaisford @stebo23  , and thanks for providing a working solution @usmangani1 . This should be working on the `latest` version in the meantime - please report here if the problem persists. Thanks!
