### ISSUE TITLE
LocalStack Pro: Unable to successfully run/deploy Lambda function with Layers from the Pro Samples

### ISSUE THREAD

**Issue by kinan-ellevation** [localstack/localstack#1694]
Steps to reproduce:
1) I cloned the [Lambda layers repo](https://github.com/localstack/localstack-pro-samples/tree/master/serverless-lambda-layers) and added a docker-compose file to be able to init local stack on Windows and test Layers. [The repo is on GitHub](https://github.com/kinan-ellevation/localstack-layers-sample).
2) I signed up for a Localstack API key to access the pro features (namely Lambda Layers). I added the API key to docker-compose.
3) When I run `docker-compose up` and ssh into the container to run `make install` and `make run` from /app, I encounter a bunch of errors: 

* None object has no attr: stack_resources
```
2019-10-29T14:40:32:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource test-layers-local/ApiGatewayRestApi: None
2019-10-29 14:40:32,701:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/werkzeug/serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/server.py", line 132, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/utils.py", line 140, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 168, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 259, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/core/responses.py", line 340, in call_action
    response = method()
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 561, in describe_stack_resource
    for stack_resource in stack.stack_resources:
AttributeError: 'NoneType' object has no attribute 'stack_resources'
```
* Cannot connect to http://706502d3dd40:0/restapi where I assume the hostname is the docker container id. Please note that I tried to specify the localstack hostname in the docker-compose file and that did not help either. 
```
2019-10-29T14:40:38:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected error retrieving details for resource ApiGateway::RestApi: Could not connect to the endpoint URL: "http://706502d3dd40:0/restapis" Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```
* Then CloudFormation throws a `Function already exist` exception when it tries to create the stack
```
2019-10-29T14:40:44:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource test-layers-local/HelloLogGroup: False
2019-10-29T14:40:44:DEBUG:localstack.services.cloudformation.cloudformation_starter: Resource HelloLogGroup need not be deployed: {'Type': 'AWS::Logs::LogGroup', 'Properties': {'LogGroupName': '/aws/lambda/test-layers-local-hello'}}
2019-10-29T14:40:44:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False): {'Type': 'AWS::Logs::LogGroup', 'Properties': {'LogGroupName': '/aws/lambda/test-layers-local-hello'}}
2019-10-29T14:40:44:WARNING:localstack.utils.cloudformation.template_deployer: Resource type not yet implemented: Logs::LogGroup
2019-10-29T14:40:44:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource test-layers-local/IamRoleLambdaExecution: False
2019-10-29T14:40:44:DEBUG:localstack.services.cloudformation.cloudformation_starter: Resource IamRoleLambdaExecution need not be deployed: {'Type': 'AWS::IAM::Role', 'Properties': {'AssumeRolePolicyDocument': {'Version': '2012-10-17', 'Statement': [{'Effect': 'Allow', 'Principal': {'Service': ['lambda.amazonaws.com']}, 'Action': ['sts:AssumeRole']}]}, 'Policies': [{'PolicyName': 'local-test-layers-lambda', 'PolicyDocument': {'Version': '2012-10-17', 'Statement': [{'Effect': 'Allow', 'Action': ['logs:CreateLogStream'], 'Resource': ['arn:aws:logs:us-east-1:123456789012:log-group:/aws/lambda/test-layers-local*:*']}, {'Effect': 'Allow', 'Action': ['logs:PutLogEvents'], 'Resource': ['arn:aws:logs:us-east-1:123456789012:log-group:/aws/lambda/test-layers-local*:*:*']}]}}], 'Path': '/', 'RoleName': 'test-layers-local-us-east-1-lambdaRole'}}
2019-10-29T14:40:44:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False): {'Type': 'AWS::IAM::Role', 'Properties': {'AssumeRolePolicyDocument': {'Version': '2012-10-17', 'Statement': [{'Effect': 'Allow', 'Principal': {'Service': ['lambda.amazonaws.com']}, 'Action': ['sts:AssumeRole']}]}, 'Policies': [{'PolicyName': 'local-test-layers-lambda', 'PolicyDocument': {'Version': '2012-10-17', 'Statement': [{'Effect': 'Allow', 'Action': ['logs:CreateLogStream'], 'Resource': ['arn:aws:logs:us-east-1:123456789012:log-group:/aws/lambda/test-layers-local*:*']}, {'Effect': 'Allow', 'Action': ['logs:PutLogEvents'], 'Resource': ['arn:aws:logs:us-east-1:123456789012:log-group:/aws/lambda/test-layers-local*:*:*']}]}}], 'Path': '/', 'RoleName': 'test-layers-local-us-east-1-lambdaRole'}}
2019-10-29T14:40:44:WARNING:localstack.utils.cloudformation.template_deployer: Resource type not yet implemented: IAM::Role
2019-10-29T14:40:44:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource test-layers-local/TestLambdaLayer: False
2019-10-29T14:40:44:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type Lambda::LayerVersion when resolving references of resource TestLambdaLayer: {'Type': 'AWS::Lambda::LayerVersion', 'Properties': {'Content': {'S3Bucket': 'testbucket', 'S3Key': 'serverless/test-layers/local/1572360030904-2019-10-29T14:40:30.904Z/test.zip'}, 'LayerName': 'test'}}
2019-10-29T14:40:44:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False): {'Type': 'AWS::Lambda::LayerVersion', 'Properties': {'Content': {'S3Bucket': 'testbucket', 'S3Key': 'serverless/test-layers/local/1572360030904-2019-10-29T14:40:30.904Z/test.zip'}, 'LayerName': 'test'}}
2019-10-29T14:40:44:DEBUG:localstack.utils.cloudformation.template_deployer: Deploying resource type "Lambda::LayerVersion" id "TestLambdaLayer"
2019-10-29T14:40:44:DEBUG:localstack.utils.cloudformation.template_deployer: Request for creating resource type "Lambda::LayerVersion" in region us-east-1: publish_layer_version {'Content': {'S3Bucket': 'testbucket', 'S3Key': 'serverless/test-layers/local/1572360030904-2019-10-29T14:40:30.904Z/test.zip'}, 'LayerName': 'test'}
2019-10-29T14:40:44:DEBUG:localstack.services.awslambda.lambda_executors: Getting status for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_layer_test": docker ps -a --filter name='localstack_lambda_arn_aws_lambda_us-east-1_000000000000_layer_test' --format "{{ .Status }} - {{ .Names }}" | grep -w "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_layer_test" | cat
2019-10-29T14:40:44:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource test-layers-local/HelloLambdaFunction: False
2019-10-29T14:40:44:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False): {'Type': 'AWS::Lambda::Function', 'Properties': {'Code': {'S3Bucket': 'testbucket', 'S3Key': 'serverless/test-layers/local/1572360030904-2019-10-29T14:40:30.904Z/test-layers.zip'}, 'FunctionName': 'test-layers-local-hello', 'Handler': 'handler.hello', 'MemorySize': 1024, 'Role': 'arn:aws:iam::000000000000:role/test-layers-local-IamRoleLambdaExecution-QLBR0X53PN74', 'Runtime': 'nodejs10.x', 'Timeout': 6, 'Layers': ['arn:aws:lambda:us-east-1:000000000000:layer:test']}, 'DependsOn': ['HelloLogGroup', 'IamRoleLambdaExecution']}
2019-10-29T14:40:44:DEBUG:localstack.utils.cloudformation.template_deployer: Deploying resource type "Lambda::Function" id "HelloLambdaFunction"
2019-10-29T14:40:44:DEBUG:localstack.utils.cloudformation.template_deployer: Request for creating resource type "Lambda::Function" in region us-east-1: create_function {'FunctionName': 'test-layers-local-hello', 'Runtime': 'nodejs10.x', 'Role': 'test_role', 'Handler': 'handler.hello', 'Code': {'S3Bucket': 'testbucket', 'S3Key': 'serverless/test-layers/local/1572360030904-2019-10-29T14:40:30.904Z/test-layers.zip'}, 'Timeout': 6, 'MemorySize': 1024, 'Layers': ['arn:aws:lambda:us-east-1:000000000000:layer:test']}
2019-10-29T14:40:44:WARNING:localstack.services.awslambda.lambda_api: Function already exist: test-layers-local-hello
2019-10-29T14:40:44:WARNING:localstack.utils.cloudformation.template_deployer: Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.Lambda object at 0x7f7614c4b4a8>> with params: {'FunctionName': 'test-layers-local-hello', 'Runtime': 'nodejs10.x', 'Role': 'test_role', 'Handler': 'handler.hello', 'Code': {'S3Bucket': 'testbucket', 'S3Key': 'serverless/test-layers/local/1572360030904-2019-10-29T14:40:30.904Z/test-layers.zip'}, 'Timeout': 6, 'MemorySize': 1024, 'Layers': ['arn:aws:lambda:us-east-1:000000000000:layer:test']} for resource: {'Type': 'AWS::Lambda::Function', 'Properties': {'Code': {'S3Bucket': 'testbucket', 'S3Key': 'serverless/test-layers/local/1572360030904-2019-10-29T14:40:30.904Z/test-layers.zip'}, 'FunctionName': 'test-layers-local-hello', 'Handler': 'handler.hello', 'MemorySize': 1024, 'Role': 'arn:aws:iam::000000000000:role/test-layers-local-IamRoleLambdaExecution-QLBR0X53PN74', 'Runtime': 'nodejs10.x', 'Timeout': 6, 'Layers': ['arn:aws:lambda:us-east-1:000000000000:layer:test']}, 'DependsOn': ['HelloLogGroup', 'IamRoleLambdaExecution']}
2019-10-29T14:40:44:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "HelloLambdaFunction": An error occurred (ResourceConflictException) when calling the CreateFunction operation: Function already exist: test-layers-local-hello Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 172, in parse_and_create_resource
    return _parse_and_create_resource(logical_id, resource_json, resources_map, region_name)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 246, in _parse_and_create_resource
    result = deploy_func(logical_id, resource_wrapped, stack_name=stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 657, in deploy_resource
    result = deploy_resource_via_sdk_function(resource_id, resources, resource_type, func, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 725, in deploy_resource_via_sdk_function
    raise e
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 722, in deploy_resource_via_sdk_function
    result = function(**params)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the CreateFunction operation: Function already exist: test-layers-local-hello
```
The end result is that the function is not created and is not invoked in localstack. My question is: Shouldn't the sample example run out of the box? Is there a step I am missing to have layers working with Serverless?

**Comment by whummer** [comment]
Thanks for reporting @kinan-ellevation . This appears to be an issue with non-matching regions. I was able to get your example to work with a few small changes, basically setting `AWS_DEFAULT_REGION=us-east-1` and adding `apigateway` to the list of SERVICES.

(Note that you can also use `SERVICES=serverless` which starts a few commonly used services including Lambda, API Gateway, CloudFormation, etc)

We'll look into the region issue shortly.

**Comment by whummer** [comment]
Should be fixed in the latest version - please re-open this issue if the problem persists. Thanks
