### ISSUE TITLE
Unable to execute lambda function

### ISSUE THREAD

**Issue by sakopov** [localstack/localstack#1724]
I have a very simple .NET Core 2.1 lambda function that is attached to a DynamoDB stream. The lambda fails to execute when it receives a stream event from DynamoDB. The following gets logged. 

```
Waiting for all LocalStack services to be ready
2019-11-05 19:50:28,135 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-11-05 19:50:28,139 INFO supervisord started with pid 13
2019-11-05 19:50:29,141 INFO spawned: 'dashboard' with pid 19
2019-11-05 19:50:29,142 INFO spawned: 'infra' with pid 20
2019-11-05 19:50:29,152 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; bin/localstack web)
(. .venv/bin/activate; exec bin/localstack start --host)
2019-11-05 19:50:30,153 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-11-05T19:50:32:WARNING:bootstrap.py: Unable to load plugins from file /opt/code/localstack/.venv/lib/python3.6/site-packages/localstack_ext/plugins.py: No module named 'localstack_ext.utils.aws.aws_models'
Starting local dev environment. CTRL-C to quit.
Starting mock SNS (http port 4575)...
Starting mock SQS (http port 4576)...
Starting mock SSM (http port 4583)...
Starting mock IAM (http port 4593)...
Starting mock DynamoDB (http port 4569)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Lambda service (http port 4574)...
Starting mock Kinesis (http port 4568)...
Starting mock CloudWatch Logs (http port 4586)...
Listening at http://:::4565
Initializing DynamoDB Local with the following configuration:
Port:   4564
InMemory:       true
DbPath: null
SharedDb:       true
shouldDelayTransientStatuses:   false
CorsParams:     *

2019-11-05T19:50:32:INFO:localstack.multiserver: Starting multi API server process on port 51492
2019-11-05 19:50:32,607:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
2019-11-05 19:50:32,607:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
2019-11-05 19:50:32,607:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
2019-11-05 19:50:32,616:API:  * Running on http://0.0.0.0:4583/ (Press CTRL+C to quit)
2019-11-05 19:50:32,616:API:  * Running on http://0.0.0.0:4583/ (Press CTRL+C to quit)
2019-11-05 19:50:32,616:API:  * Running on http://0.0.0.0:4583/ (Press CTRL+C to quit)
2019-11-05 19:50:32,630:API:  * Running on http://0.0.0.0:4557/ (Press CTRL+C to quit)
2019-11-05 19:50:32,630:API:  * Running on http://0.0.0.0:4557/ (Press CTRL+C to quit)
2019-11-05 19:50:32,630:API:  * Running on http://0.0.0.0:4557/ (Press CTRL+C to quit)
19:50:33.998 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.14.5) ...
Waiting for all LocalStack services to be ready
19:50:34.977 [elasticmq-akka.actor.default-dispatcher-6] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
19:50:36.119 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.14.5) started in 3202 ms ===
19:50:36.120 [elasticmq-akka.actor.default-dispatcher-3] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:4561, visible server address http://d88130eb534c:4576
Ready.
19:50:53.041 [elasticmq-akka.actor.default-dispatcher-4] INFO  o.elasticmq.actor.QueueManagerActor - Creating queue QueueData(TestQueue,MillisVisibilityTimeout(30000),PT0S,PT0S,2019-11-05T19:50:52.997Z,2019-11-05T19:50:52.997Z,None,false,false,None,None,Map())
19:50:53.990 [elasticmq-akka.actor.default-dispatcher-10] WARN  o.e.r.s.TheSQSRestServerBuilder$$anon$1 - Ignored attribute "Policy" (supported by SQS but not ElasticMQ)
2019-11-05T19:50:56:DEBUG:localstack.services.awslambda.lambda_executors: Running lambda cmd: CONTAINER_ID="$(docker create -i   -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN"  --rm "lambci/lambda:dotnetcore2.1" "BI.Safe.EventPublisher::BI.Safe.EventPublisher.LambdaFunction::HandleAsync")";docker cp "/tmp/localstack/zipfile.12076f37/." "$CONTAINER_ID:/var/task"; docker start -ai "$CONTAINER_ID";
2019-11-05T19:50:56:WARNING:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:7486f14c-13fb-4a7e-83b4-9e94e25b0e1a: Lambda process returned error status code: 1. Output:Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
must specify at least one container source
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 343, in run_lambda
    event, context=context, version=version, asynchronous=asynchronous)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 80, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 65, in do_execute
    result, log_output = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 232, in _execute
    result, log_output = self.run_lambda_executor(cmd, stdin, environment)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 153, in run_lambda_executor
    (return_code, log_output))
Exception: Lambda process returned error status code: 1. Output:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
must specify at least one container source
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

The container is running in privileged mode. Not sure if there is anything else that's missing.

Thank you

**Comment by hartmannr76** [comment]
did you map the docker socket? `docker run ... -v /var/run/docker.sock:/var/run/docker.sock`

**Comment by whummer** [comment]
Thanks for reporting @sakopov . As @hartmannr76 mentioned, the docker socket needs to be mounted into the container.

The recommended way of starting LocalStack is via `localstack start` - this command will automatically take care of passing the required Docker flags. Hope that helps.

**Comment by sakopov** [comment]
Yep, that did it. Thank you!
