### ISSUE TITLE
cannot import name python_2_unicode_compatible

### ISSUE THREAD

**Issue by jperez-dx** [localstack/localstack#1730]
I'm getting the following error when running integration tests in a maven project with the `@RunWith(LocalstackTestRunner.class)` annotation:

```
java.lang.RuntimeException: 
Unable to start local infrastructure. Debug output: (. .venv/bin/activate; exec bin/localstack start --host)
Starting local dev environment. CTRL-C to quit.
Requirement already satisfied: airspeed==0.5.10 in ./.venv/lib/python2.7/site-packages (0.5.10)
...
Requirement already satisfied: more-itertools in ./.venv/lib/python2.7/site-packages (from zipp>=0.5->importlib-metadata->jsonschema~=3.0->cfn-lint>=0.4.0->moto-ext>=1.3.14.2) (5.0.0)
ERROR: cannot import name python_2_unicode_compatible

	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
```

**Comment by jperez-dx** [comment]
Upgrading the `localstack-utils` maven dependency from `0.1.21` to `0.1.22` solved this issue.
