### ISSUE TITLE
Unable to create cache cluster

### ISSUE THREAD

**Issue by nukopian** [localstack/localstack#1747]
Hey team,

Running a freshly minted install of localstack pro under macOS 10.14.6 and docker desktop 2.1.0.4 stable. I have 2 cores, 4.0 GiB memory and 1.0 GiB swap allocated to docker.

Just trying to follow one of the examples in the documentation:

```
$ awslocal elasticache create-cache-cluster --cache-cluster-id i1
{
    "CacheCluster": {
        "CacheClusterId": "i1",
        "ConfigurationEndpoint": {
            "Address": "localhost",
            "Port": 4511
        }
    }
}
$ redis-cli -p 4511 ping
Error: Server closed the connection
```

I started localstack in another window with `DEBUG=1 localstack start --docker` and the `awslocal` command triggered the following log output:

```
/bin/sh: /opt/code/localstack/localstack/infra/redis/miniredis.linux.bin: not found
2019-11-10T15:02:49:DEBUG:localstack_ext.services.elasticache.elasticache_api: Start Redis server on port 4511
2019-11-10T15:02:49:INFO:hbmqtt.broker: Listener 'default': 3 connections acquired
2019-11-10T15:02:49:INFO:hbmqtt.broker: Connection from 127.0.0.1:49996 on listener 'default'
2019-11-10T15:02:49:ERROR:asyncio: Task exception was never retrieved
future: <Task finished coro=<Broker.stream_connected() done, defined at /opt/code/localstack/.venv/lib/python3.6/site-packages/hbmqtt/broker.py:341> exception=IncompleteReadError('0 bytes read on a total of 1 expected bytes',)>
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/hbmqtt/broker.py", line 343, in stream_connected
    yield from self.client_connected(listener_name, StreamReaderAdapter(reader), StreamWriterAdapter(writer))
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/hbmqtt/broker.py", line 358, in client_connected
    handler, client_session = yield from BrokerProtocolHandler.init_from_connect(reader, writer, self.plugins_manager, loop=self._loop)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/hbmqtt/mqtt/protocol/broker_handler.py", line 129, in init_from_connect
    connect = yield from ConnectPacket.from_stream(reader)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/hbmqtt/mqtt/packet.py", line 225, in from_stream
    fixed_header = yield from cls.FIXED_HEADER.from_stream(reader)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/hbmqtt/mqtt/packet.py", line 104, in from_stream
    byte1 = yield from read_or_raise(reader, 1)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/hbmqtt/codecs.py", line 52, in read_or_raise
    data = yield from reader.read(n)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/hbmqtt/adapters.py", line 146, in read
    data = yield from self._reader.readexactly(n)
  File "/usr/lib/python3.6/asyncio/streams.py", line 672, in readexactly
    raise IncompleteReadError(incomplete, n)
```

I can ssh into the localstack container and see `/opt/code/localstack/localstack/infra/redis/miniredis.linux.bin` right there.

Not super urgent, but thought you may wish to know.

**Comment by whummer** [comment]
Thanks for reporting @nukopian . This should be fixed in the `latest` version of the Docker image. Please report here if the problem comes up again. Thanks
