### ISSUE TITLE
Dashboard error with pip installed localstack

### ISSUE THREAD

**Issue by kpadmawa** [localstack/localstack#175]
Hi,

I installed localstack and started web client. But whenever I am trying to access it getting following error on browser
`
![image](https://user-images.githubusercontent.com/14889902/28256345-140f68d2-6adf-11e7-8729-72bf5b366319.png)

And error in the console is
`
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.4/site-packages/localstack/dashboard/api.py", line 34, in get_graph
    data = json.loads(request.data)
  File "/usr/local/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

Please help to resolve this.

**Comment by kpadmawa** [comment]
Please can anyone take a look ASAP.

**Comment by whummer** [comment]
Thanks for reporting @kpadmawa , this looks like a Python compatibility issue. The dashboard code has not been fully ported to Python 3.x yet. We'll try to tackle that soon - but also happy to accept pull requests if you manage to get it working! Thanks

**Comment by whummer** [comment]
This issue should be fixed in https://github.com/localstack/localstack/issues/189 . Can you please try pulling the latest version of the code and try if it works now. Thanks

Also, it seems that your browser is unable to load some of the CSS resources (the screenshot looks like there is something wrong). Can you please open the console output of your browser and check if there are any error messages?

**Comment by whummer** [comment]
Closing this issue for now, as this appears to be fixed. Please re-open if the problem persists.

The UI code has been recently refactored (in particular some heavy-weight dependencies have been removed to reduce the Docker image size). Having said that, the UI needs a major overhaul and we need to decide on the next features.
