### ISSUE TITLE
Bug: handler paths which contain periods do not work

### ISSUE THREAD

**Issue by JakeChampion** [localstack/localstack#1774]
If the handler_name is a relative path, localstack will error because it currently assumes there will be only one period in handler_name, for the extension.

Here is a small project to test with, it is similar to the example serverless-localstack project except it uses a relative path for the handler: https://gist.github.com/JakeChampion/1684dd8c3cba95c2be39949d8bed256d

Here is the error I have from localstack with `DEBUG=true`:
<details>
<summary>Click to view localstack logs</summary>
<code><pre>botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateFunction operation: Unable to find handler script (/tmp/localstack/zipfile.9b5922dc/.js) in Lambda archive. Config for local mount, docker, remote: "False", "True", "True"
2019-11-19 11:47:35,133:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 132, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 140, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 168, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 259, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 340, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/responses.py", line 294, in update_stack
    tags=tags,
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/models.py", line 536, in update_stack
    stack.update(template, role_arn, parameters=parameters, tags=tags)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/models.py", line 257, in update
    self.output_map = self._create_output_map()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/models.py", line 200, in _create_output_map
    output_map.create()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/parsing.py", line 632, in create
    self[output]
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/parsing.py", line 605, in __getitem__
    output_logical_id, output_json, self._resource_map)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 354, in parse_output
    return parse_output_orig(output_logical_id, output_json, resources_map)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/parsing.py", line 370, in parse_output
    output_json = clean_json(output_json, resources_map)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 152, in clean_json
    result = clean_json_orig(resource_json, resources_map)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/parsing.py", line 229, in clean_json
    cleaned_val = clean_json(value, resources_map)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 152, in clean_json
    result = clean_json_orig(resource_json, resources_map)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/parsing.py", line 143, in clean_json
    resource = resources_map[resource_json['Ref']]
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/parsing.py", line 415, in __getitem__
    resource_logical_id, resource_json, self, self._region_name)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 173, in parse_and_create_resource
    return _parse_and_create_resource(logical_id, resource_json, resources_map, region_name)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 199, in _parse_and_create_resource
    resource_tuple = parsing.parse_resource(logical_id, resource_json, resources_map)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/parsing.py", line 279, in parse_resource
    resource_json = clean_json(resource_json, resources_map)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 152, in clean_json
    result = clean_json_orig(resource_json, resources_map)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/parsing.py", line 229, in clean_json
    cleaned_val = clean_json(value, resources_map)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 152, in clean_json
    result = clean_json_orig(resource_json, resources_map)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/parsing.py", line 229, in clean_json
    cleaned_val = clean_json(value, resources_map)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 152, in clean_json
    result = clean_json_orig(resource_json, resources_map)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/parsing.py", line 143, in clean_json
    resource = resources_map[resource_json['Ref']]
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/parsing.py", line 415, in __getitem__
    resource_logical_id, resource_json, self, self._region_name)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 173, in parse_and_create_resource
    return _parse_and_create_resource(logical_id, resource_json, resources_map, region_name)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 260, in _parse_and_create_resource
    result = deploy_func(logical_id, resource_wrapped, stack_name=stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 713, in deploy_resource
    result = deploy_resource_via_sdk_function(resource_id, resources, resource_type, func, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 783, in deploy_resource_via_sdk_function
    raise e
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 780, in deploy_resource_via_sdk_function
    result = function(**params)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateFunction operation: Unable to find handler script (/tmp/localstack/zipfile.9b5922dc/.js) in Lambda archive. Config for local mount, docker, remote: "False", "True", "True"
</pre></code></details>

Here is the output of Serverless with debug enabled:
<details>
<summary>Click to view serverless logs</summary>
<code><pre>
DEBUG=serverless,serverless:* serverless deploy                                   
Serverless: Using serverless-localstack
Serverless: Reconfiguring service apigateway to use http://localhost:4567
Serverless: Reconfiguring service cloudformation to use http://localhost:4581
Serverless: Reconfiguring service cloudwatch to use http://localhost:4582
Serverless: Reconfiguring service lambda to use http://localhost:4574
Serverless: Reconfiguring service dynamodb to use http://localhost:4569
Serverless: Reconfiguring service kinesis to use http://localhost:4568
Serverless: Reconfiguring service route53 to use http://localhost:4580
Serverless: Reconfiguring service firehose to use http://localhost:4573
Serverless: Reconfiguring service stepfunctions to use http://localhost:4585
Serverless: Reconfiguring service es to use http://localhost:4578
Serverless: Reconfiguring service s3 to use http://localhost:4572
Serverless: Reconfiguring service ses to use http://localhost:4579
Serverless: Reconfiguring service sns to use http://localhost:4575
Serverless: Reconfiguring service sqs to use http://localhost:4576
Serverless: Reconfiguring service sts to use http://localhost:4592
Serverless: Reconfiguring service iam to use http://localhost:4593
Serverless: Reconfiguring service ssm to use http://localhost:4583
Serverless: Reconfiguring service rds to use http://localhost:4594
Serverless: Reconfiguring service ec2 to use http://localhost:4597
Serverless: Reconfiguring service elasticache to use http://localhost:4598
Serverless: Reconfiguring service kms to use http://localhost:4599
Serverless: Reconfiguring service secretsmanager to use http://localhost:4584
Serverless: Reconfiguring service logs to use http://localhost:4586
Serverless: Reconfiguring service cloudwatchlogs to use http://localhost:4586
Serverless: Reconfiguring service iot to use http://localhost:4589
Serverless: Reconfiguring service cognito-idp to use http://localhost:4590
Serverless: Reconfiguring service cognito-identity to use http://localhost:4591
Serverless: Reconfiguring service ecs to use http://localhost:4601
Serverless: Reconfiguring service eks to use http://localhost:4602
Serverless: Reconfiguring service xray to use http://localhost:4603
Serverless: Reconfiguring service appsync to use http://localhost:4605
Serverless: Reconfiguring service cloudfront to use http://localhost:4606
Serverless: Reconfiguring service athena to use http://localhost:4607
Serverless: config.options_stage: dev
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: dev
Serverless: config.stage: dev
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service aws-nodejs.zip file to S3 (47.29 KB)...
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 1 of 4
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 2 of 4
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 3 of 4
Serverless: Recoverable error occurred (500), sleeping for 5 seconds. Try 4 of 4
 
  Serverless Error ---------------------------------------
 
  500
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.15.3
     Framework Version:         1.57.0
     Plugin Version:            3.2.3
     SDK Version:               2.2.1
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
 

</pre></code></details>

If there is any other information I should/could provide to help, please let me know, I tried to debug this myself but couldn't see much in the logs to pinpoint what is ging wrong.

Here is the full localstack log https://gist.github.com/JakeChampion/4ec5dbd3b682a7dc37b63aa8774ad366

**Comment by macnev2013** [comment]
Hey @JakeChampion , Thanks for reporting. This issue has been fixed in the `latest` version of `localstack`.
Can you please give it a try adding custom stage something like this:
```
service: aws-nodejs

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    debug: true
    host: http://localhost

functions:
  hello:
    handler: ./hello.hello
    events:
      - http:
          path: /hello
          method: get
```
**Command to deploy:** 
`sls deploy --stage local`

Thanks.

**Comment by JakeChampion** [comment]
I no longer use localstack in any projects, I trust your judgement if you say it is fixed 👍

**Comment by macnev2013** [comment]
Thanks for the feedback @JakeChampion .
