### ISSUE TITLE
ERROR:localstack.services.generic_proxy: Error forwarding request: Unable to fetch template body (code 404)

### ISSUE THREAD

**Issue by nitinjaiswal** [localstack/localstack#1778]
I am recieving the following error when i am deploying the serverless. All other actions like entry in s3, dynamodb are working fine.

This has happened after I pulled the latest localstack code.

2019-11-20T06:47:36:ERROR:localstack.services.generic_proxy: Error forwarding request: Unable to fetch template body (code 404) from URL https://s3.amazonaws.com/ingestor-deployment-bucket/serverless/ingestor/local/1574232413242-2019-11-20T06:46:53.242Z/compiled-cloudformation-template.json Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 240, in forward
    path=path, data=data, headers=forward_headers)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 151, in forward_request
    modified_request = transform_template(req_data)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 70, in transform_template
    template_body = get_template_body(req_data)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 105, in get_template_body
    raise Exception('Unable to fetch template body (code %s) from URL %s' % (response.status_code, url[0]))
Exception: Unable to fetch template body (code 404) from URL https://s3.amazonaws.com/ingestor-deployment-bucket/serverless/ingestor/local/1574232413242-2019-11-20T06:46:53.242Z/compiled-cloudformation-template.json

**Comment by nitinjaiswal** [comment]
Its resolved in the latest devlopement.

If any one is still getting it just run "docker pull localstack/localstack".  And restart the docker container.
