### ISSUE TITLE
S3 SSL unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by igor-dmitriev** [localstack/localstack#178]
I am using `atlassianlabs/localstack:0.5.5` and I need the S3 service.
When I try to use Service Side Encryption of Amazon S3 objects I get an exception:

```
PutObjectRequest putObjectRequest = new PutObjectRequest(
          bucket, key, inputStream, metadata)
          .withSSEAwsKeyManagementParams(new SSEAwsKeyManagementParams(kmsKeyId));
amazonS3Client.putObject(putObjectRequest);

```

```
AmazonS3ClientBuilder.standard()
        .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("https://localhost:4572", "us-west-2"))
        .withChunkedEncodingDisabled(true)
        .withPathStyleAccessEnabled(true) 
        .build();
```

```
USE_SSL=true
```

```
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:132)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy153.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1190)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
	... 49 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
	... 76 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 82 more

```

**Comment by whummer** [comment]
Thanks for reporting @igor-dmitriev . There is a Java system property you can set to disable certificate validation: http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/SDKGlobalConfiguration.html#DISABLE_CERT_CHECKING_SYSTEM_PROPERTY
We also use it here: 
https://github.com/localstack/localstack/blob/master/localstack/utils/kinesis/java/com/atlassian/KinesisStarter.java#L35
Hope that helps

**Comment by igor-dmitriev** [comment]
hello @whummer, unfortunately, it does not work. The issue is still reproducable

**Comment by whummer** [comment]
I have added your test class to the code base for better reproducibility: https://github.com/localstack/localstack/blob/master/localstack/ext/java/src/test/java/com/atlassian/localstack/S3HttpsConnectionTest.java

You can kick off the Java tests by running the following command (this will kick off the tests twice, both with and without SSL enabled):
```
make test-java
```

The Java tests are now also executed in Travis CI. See, for instance, this log output on travis: https://travis-ci.org/localstack/localstack/builds/255253008#L1952-L2043

Can you please try one more time with the latest version of the Docker image. Also, if you are using the `localstack-utils` Maven artifact, please make sure to clean your maven cache to reload the latest snapshot version. If you still run into issues, please post a complete and self-contained sample project to reproduce the issue. Thanks

**Comment by igor-dmitriev** [comment]
@whummer you are right, now it works, I've found an issue with my code, I had to set up this flag in before class section:
```
  @BeforeClass
  public static void init() {
    System.setProperty(SDKGlobalConfiguration.DISABLE_CERT_CHECKING_SYSTEM_PROPERTY, "true");
  }
```
cause I use TestContainers 

 ```
@ClassRule
  public static GenericContainer s3Container = new GenericContainer("atlassianlabs/localstack:0.5.5")
      .withEnv("S3", "s3")
      .withExposedPorts(4572);
```

**Comment by whummer** [comment]
Awesome, that's great to hear @igor-dmitriev . Please note that the image name has recently changed to `localstack/localstack` (if you want to continue receiving updates). Thanks

**Comment by igor-dmitriev** [comment]
@whummer ooh my god, thank you, you made my day, I've been struggling today to figure out what's going on and why I always get `tag not found`
