### ISSUE TITLE
Terraform can't create aws_vpc resource in localstack

### ISSUE THREAD

**Issue by ilija1** [localstack/localstack#1794]
I'm using this terraform code to try to create a simple VPC:
```hcl
provider "aws" {
  region = "us-east-1"

  endpoints {
    ec2      = "http://localhost:4597"
    dynamodb = "http://localhost:4569"
    s3       = "http://localhost:4572"
  }
}

resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"

  tags = {
    Name = "main"
  }
}
```

But terraform keeps getting stuck on `terraform apply`. I ran localstack with `DEBUG=1` and this error just keeps popping up over and over:

```2019-11-23 13:50:37,300:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 132, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 140, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 168, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 259, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 353, in call_action
    "The {0} action has not been implemented in class {1}".format(action, self.__class__))
NotImplementedError: The describe_vpc_classic_link action has not been implemented in class <class 'moto.ec2.responses.EC2Response'>
```

`terraform apply` is just stuck in a loop and even after 5.5 minutes of running it's unable to create the VPC (in the localstack log it's just that same error from above getting spammed over and over).

```
NotImplementedError: The describe_vpc_classic_link action has not been implemented in class <class 'moto.ec2.responses.EC2Response'>
```

**Comment by whummer** [comment]
Thanks for reporting @ilija1 . This should be fixed in the meantime - I was able to deploy your TF config with the `latest` version. Please report here if the problem persists. Thanks

**Comment by Amrutavd** [comment]
I am facing same issue, terraform apply keeps running for 8-10 mins while trying to create vpc using aws_vpc. Please suggest.

**Comment by lincze** [comment]
> I am facing same issue, terraform apply keeps running for 8-10 mins while trying to create vpc using aws_vpc. Please suggest.

i've reported this issue at hashicorp (https://github.com/terraform-providers/terraform-provider-aws/issues/13253). according to the debug log the aws provider sets a clumsy availability zone when no availability zone is specified. it seems to me an aws provider error, tough the real ec2/vpc service (not the localstack mock) may compensate for it and selects an appropriate zone (if not so, the terraform were almost useless in aws, i don't have an account to check it).

so, there is a workaround, for the moment: set an appropriate availability zone in your ".tf" recipe.
