### ISSUE TITLE
localhost:4569/shell is broken

### ISSUE THREAD

**Issue by mark-pearlpay** [localstack/localstack#1803]
Started with `localstack start` then navigated to `http://localhost:4569/shell`

Localstack version is `0.10.5`

![Screenshot from 2019-11-26 08-15-03](https://user-images.githubusercontent.com/57932946/69588919-24798700-1025-11ea-94d2-9cfb6dd20004.png)

Console log below, its all the same so I am just posting one

```2019-11-26T00:13:18:ERROR:localstack.services.generic_proxy: Error forwarding request: the JSON object must be str, bytes or bytearray, not NoneType Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 240, in forward
    path=path, data=data, headers=forward_headers)
  File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 44, in forward_request
    data = json.loads(to_str(data))
  File "/usr/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType```

**Comment by vuchau-agilityio** [comment]
me too
