### ISSUE TITLE
Node JS Giving InvalidBucketName after recent update

### ISSUE THREAD

**Issue by thepont** [localstack/localstack#1813]
The following is no longer working although was working yesterday, I feel it's a regression due to recent changes.

Below is the example code that reproduces the issues I have been having since today. ( we have not version locked the docker container we are using and I think it's todo with the most recent push to the latest tag )

```javascript
const AWS = require('aws-sdk');
const S3_ENDPOINT = "http://localhost:4572/"
const S3_BUCKET = "testhello"
let S3 = new AWS.S3({
    endpoint: S3_ENDPOINT
})

const setupMockS3 = async () => {
    try{          
        await S3.createBucket({
            Bucket: S3_BUCKET
        }).promise();  
    } catch (ee){
        console.error('Error seting up tests', S3_BUCKET, ee);
        throw ee;
    }
};

setupMockS3();
```

Running the above code results in, although "testhello" is a valid bucket name

```
node test  
Error seting up tests testhello { InvalidBucketName: The specified bucket is not valid.
    at Request.extractError (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/services/s3.js:577:35)
    at Request.callListeners (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'The specified bucket is not valid.',
  code: 'InvalidBucketName',
  region: null,
  time: 2019-11-28T03:58:34.278Z,
  requestId: null,
  extendedRequestId: undefined,
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 4.182550026460574 }
(node:115069) UnhandledPromiseRejectionWarning: InvalidBucketName: The specified bucket is not valid.
    at Request.extractError (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/services/s3.js:577:35)
    at Request.callListeners (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/pont/projects/possum/packages/elearning-lambda/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
(node:115069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:115069) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

using the aws-cli does not result in this issue

```
aws s3api create-bucket --endpoint http://localhost:4572/ --bucket testhello
```

I don't know if this is helpful, but the following is the Request that is constructed, also it might be worth noting that localstack doesn't print any debug trace on this request when `DEBUG=1`

```
**Request {
  domain: null,
  service: 
   Service {
     config: 
      Config {
        credentials: [Object],
        credentialProvider: [Object],
        region: 'us-east-1',
        logger: null,
        apiVersions: {},
        apiVersion: null,
        endpoint: 'http://localhost:4572/',
        httpOptions: [Object],
        maxRetries: undefined,
        maxRedirects: 10,
        paramValidation: true,
        sslEnabled: true,
        s3ForcePathStyle: false,
        s3BucketEndpoint: false,
        s3DisableBodySigning: true,
        computeChecksums: true,
        convertResponseTypes: true,
        correctClockSkew: false,
        customUserAgent: null,
        dynamoDbCrc32: true,
        systemClockOffset: 0,
        signatureVersion: null,
        signatureCache: true,
        retryDelayOptions: {},
        useAccelerateEndpoint: false },
     endpoint: 
      Endpoint {
        protocol: 'http:',
        host: 'localhost:4572',
        port: 4572,
        hostname: 'localhost',
        pathname: '/',
        path: '/',
        href: 'http://localhost:4572/' },
     _clientId: 1 },
  operation: 'createBucket',
  params: 
   { Bucket: 'thisisatestbucketname',
     CreateBucketConfiguration: { LocationConstraint: 'us-east-1' } },
  httpRequest: 
   HttpRequest {
     method: 'POST',
     path: '/',
     headers: { 'User-Agent': 'aws-sdk-nodejs/2.171.0 linux/v8.11.4' },
     body: '',
     endpoint: 
      Endpoint {
        protocol: 'http:',
        host: 'localhost:4572',
        port: 4572,
        hostname: 'localhost',
        pathname: '/',
        path: '/',
        href: 'http://localhost:4572/',
        constructor: [Object] },
     region: 'us-east-1',
     _userAgent: 'aws-sdk-nodejs/2.171.0 linux/v8.11.4' },
  startTime: 2019-11-28T04:29:28.200Z,
....

```

**Comment by Dimwest** [comment]
Exact same issue happened for us with Python 3.6, since two days

**Comment by whummer** [comment]
Thanks for reporting @thepont @Dimwest . Can you please run LocalStack with `DEBUG=1` and post the debug logs here? Thanks

**Comment by thepont** [comment]
@whummer this is the trace, It's not very useful tough since nothing seems to be logged when the request is sent. ( the 200 is from before ).  `s3ForcePathStyle` seems to be a valid work around, this also worked for me.

```
localstack_1  | 2019-11-28 23:58:07,493 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_1  | 2019-11-28 23:58:07,496 INFO supervisord started with pid 13
localstack_1  | 2019-11-28 23:58:08,503 INFO spawned: 'dashboard' with pid 19
localstack_1  | 2019-11-28 23:58:08,508 INFO spawned: 'infra' with pid 20
localstack_1  | 2019-11-28 23:58:08,515 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_1  | (. .venv/bin/activate; bin/localstack web)
localstack_1  | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_1  | 2019-11-28 23:58:09,517 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 2019-11-28T23:58:11:WARNING:bootstrap.py: Unable to load plugins from file /opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/plugins.py: No module named 'localstack_ext.utils.aws.aws_models'
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  | Starting mock S3 (http port 4572)...
localstack_1  | Starting mock DynamoDB (http port 4569)...
localstack_1  | Initializing DynamoDB Local with the following configuration:
localstack_1  | Port:	4564
localstack_1  | InMemory:	false
localstack_1  | DbPath:	/tmp/dynamodb
localstack_1  | SharedDb:	true
localstack_1  | shouldDelayTransientStatuses:	false
localstack_1  | CorsParams:	*
localstack_1  | 
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2019-11-28 23:58:18,526:API: 127.0.0.1 - - [28/Nov/2019 23:58:18] "GET / HTTP/1.1" 200 -                                     
localstack_1  | Ready.
```

Here is the docker file I am using to launch localstack with debug trace, Is there something wrong with this configuration ?

```
version: '2'
services:
  localstack:
    image: localstack/localstack
    ports:
    - "4567-4584:4567-4584"
    environment:
    - SERVICES=s3,dynamodb
    - DEBUG=1
    - DATA_DIR=/tmp
```

**Comment by whummer** [comment]
> `s3ForcePathStyle` seems to be a valid work around, this also worked for me.

Thanks for confirming. Currently LocalStack requires S3 path style addressing, as otherwise the AWS SDK sends a request to a potentially invalid or non-resolvable DNS names.

Unfortunately, path style addressing has been deprecated by AWS recently, so we'll have to find a new solution soon. You can track the status of that work stream in this ticket: #1792 Thanks
