### ISSUE TITLE
Cannot read from s3 using Spark

### ISSUE THREAD

**Issue by skliarpawlo** [localstack/localstack#183]
**Problem**: Not sure if this is a bug, or is it not implemented part of s3 protocol: I'm not able to read from localstack's s3 using spark. 

**Use case**: stubbing s3 in tests of my spark job. I first put some test data to s3 using 'aws cp' with custom endpoint which works perfectly well. But then when I'm trying to read data from s3 using spark it fails with XML parse error. 

**Error  log**
```
spark.read.parquet('s3://some-bucket/some-local-stack-path')

*** py4j.protocol.Py4JJavaError: An error occurred while calling o37.parquet.
: com.amazonaws.AmazonClientException: Unable to unmarshall response (Failed to parse XML document with handler class com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser$ListBucketHandler). Response Code: 200, Response Text: OK
	at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:738)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:399)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:232)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3528)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3480)
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:604)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:962)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:77)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1426)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$12.apply(DataSource.scala:389)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$12.apply(DataSource.scala:379)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:344)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:379)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:439)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.amazonaws.AmazonClientException: Failed to parse XML document with handler class com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser$ListBucketHandler
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.parseXmlInputStream(XmlResponsesSaxParser.java:150)
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.parseListBucketObjectsResponse(XmlResponsesSaxParser.java:279)
	at com.amazonaws.services.s3.model.transform.Unmarshallers$ListObjectsUnmarshaller.unmarshall(Unmarshallers.java:75)
	at com.amazonaws.services.s3.model.transform.Unmarshallers$ListObjectsUnmarshaller.unmarshall(Unmarshallers.java:72)
	at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:62)
	at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:31)
	at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:712)
	... 29 more
Caused by: java.lang.RuntimeException: Invalid value for IsTruncated field:
  false
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser$ListBucketHandler.endElement(XmlResponsesSaxParser.java:647)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.parseXmlInputStream(XmlResponsesSaxParser.java:141)
	... 35 more
```

**Comment by whummer** [comment]
Thanks for reporting @skliarpawlo . Can you please provide a self-contained example to reproduce the issue? Thanks

**Comment by skliarpawlo** [comment]
@whummer here it is: https://github.com/skliarpawlo/localstack_s3_issue

**Comment by whummer** [comment]
@skliarpawlo Thanks for providing the example - it made debugging a lot easier. This issue should be fixed in https://github.com/localstack/localstack/pull/197 .

Can you please give it a try with the latest version (`0.7.0`). Please note that the Docker image has moved to a new repository: `localstack/localstack`

Btw, a similar problem has also happened elsewhere: https://github.com/jserver/mock-s3/pull/9

**Comment by skliarpawlo** [comment]
@whummer that worked, thanks! updated the example to work. It was really stupid not verifying latest docker version. Will push using localstack in our company further!

**Comment by skliarpawlo** [comment]
btw @whummer just wonder if you know a convenient way to refer a running docker container by several host names, like in case of s3 where client refers it via both <s3-docker-name> and <bucket-name>.<s3-docker-name>. Did you encounter such problem?

**Comment by ciprianaradulescu** [comment]
Shouldn't this have been an open bug in spark?
Since localstack is a framework that should replicate AWS services it's a bit odd that it presents a different behaviour for this use case. Amazon's S3 leaves XML content untouched when fetching it to the client.
Also, I ran into a problem with this because I was uploading an XML file to localstack and then fetching it to check the content. I was very surprised to notice that somehow my content had changed.
