### ISSUE TITLE
Cognito Support in Docker Does Not Work

### ISSUE THREAD

**Issue by miles-po** [localstack/localstack#1867]
I purchased the Pro version that has Cognito support.

OS: MacOS 10.15.2 Catalina
Docker Desktop: 2.1.0.5
Docker Engine: 19.03.5
Docker Compose: 1.24.1

The examples provided don't work. Tried multiple versions of Localstack, including the latest image pushed to Docker yesterday.  Temporary volumes/folders removed before run as was docker system prune -f. docker-compose.yml file is bare minimum.
```yml
version: "2.4"

services:
  aws:
    image: localstack/localstack:latest
    container_name: aws
    hostname: aws
    ports:
      - "4567-4607:4567-4607"
      - "9080:8080"
    environment:
      - SERVICES=cognito
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - LOCALSTACK_API_KEY=<api code omitted for bug report>
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
Then ran the following:
```sh
POOL_ID=$(awslocal cognito-idp create-user-pool --pool-name my_user_pool | jq .UserPool.Id)
POOL_CLIENT_INFO=$(awslocal cognito-idp create-user-pool-client --user-pool-id $POOL_ID --client-name my_user_pool_client)
```
Received from create-user-pool-client
```
An error occurred (502) when calling the CreateUserPoolClient operation (reached max retries: 4): Bad Gateway
```
That's about as simple a test case as I can think of. `list-user-pools` returns
```
{
    "UserPools": [
        {
            "CreationDate": 1576522548.0, 
            "LastModifiedDate": 1576522548.0, 
            "LambdaConfig": {}, 
            "Id": "us-east-1_e97003467d4c451fbe4597cc3d232bb4", 
            "Name": "my_user_pool"
        }
    ]
}
```
Server output:
```
Waiting for all LocalStack services to be ready
2019-12-16 18:54:57,981 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-12-16 18:54:57,984 INFO supervisord started with pid 13
2019-12-16 18:54:58,992 INFO spawned: 'dashboard' with pid 19
2019-12-16 18:54:58,995 INFO spawned: 'infra' with pid 20
2019-12-16 18:54:59,002 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; bin/localstack web)
(. .venv/bin/activate; exec bin/localstack start --host)
Starting local dev environment. CTRL-C to quit.
2019-12-16 18:55:00,384 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-12-16T18:55:01:WARNING:bootstrap.py: Unable to load plugins from file /opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/plugins.py: No module named 'localstack_ext.utils.aws.aws_models'
2019-12-16T18:55:03:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
Waiting for all LocalStack services to be ready
2019-12-16T18:55:04:DEBUG:asyncio: Using selector: EpollSelector
Starting mock Cognito Identity Provider (IdP) (http port 4590)...
2019-12-16T18:55:06:INFO:localstack.multiserver: Starting multi API server process on port 51492
Starting mock Cognito Identity (http port 4591)...
2019-12-16 18:55:07,669:API:  * Running on http://0.0.0.0:4546/ (Press CTRL+C to quit)
2019-12-16 18:55:07,669:API:  * Running on http://0.0.0.0:4546/ (Press CTRL+C to quit)
2019-12-16 18:55:07,669:API:  * Running on http://0.0.0.0:4546/ (Press CTRL+C to quit)
2019-12-16 18:55:07,674:API:  * Running on http://0.0.0.0:4545/ (Press CTRL+C to quit)
2019-12-16 18:55:07,674:API:  * Running on http://0.0.0.0:4545/ (Press CTRL+C to quit)
2019-12-16 18:55:07,674:API:  * Running on http://0.0.0.0:4545/ (Press CTRL+C to quit)
Waiting for all LocalStack services to be ready
Ready.
2019-12-16 18:55:48,129:API: 127.0.0.1 - - [16/Dec/2019 18:55:48] "POST / HTTP/1.1" 200 -
2019-12-16 18:55:48,129:API: 127.0.0.1 - - [16/Dec/2019 18:55:48] "POST / HTTP/1.1" 200 -
2019-12-16 18:55:48,129:API: 127.0.0.1 - - [16/Dec/2019 18:55:48] "POST / HTTP/1.1" 200 -
2019-12-16 18:56:06,288:API: 127.0.0.1 - - [16/Dec/2019 18:56:06] "POST / HTTP/1.1" 200 -
2019-12-16 18:56:06,288:API: 127.0.0.1 - - [16/Dec/2019 18:56:06] "POST / HTTP/1.1" 200 -
2019-12-16 18:56:06,288:API: 127.0.0.1 - - [16/Dec/2019 18:56:06] "POST / HTTP/1.1" 200 -
2019-12-16 18:56:22,117:API: 127.0.0.1 - - [16/Dec/2019 18:56:22] "POST / HTTP/1.1" 400 -
2019-12-16 18:56:22,117:API: 127.0.0.1 - - [16/Dec/2019 18:56:22] "POST / HTTP/1.1" 400 -
2019-12-16 18:56:22,117:API: 127.0.0.1 - - [16/Dec/2019 18:56:22] "POST / HTTP/1.1" 400 -
2019-12-16T18:56:22:ERROR:localstack.services.generic_proxy: Error forwarding request: 'UserPoolClient' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 297, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/cognito/cognito_listener.py", line 94, in return_response
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/cognito/cognito_helpers.py", line 49, in user_pool_client_created
KeyError: 'UserPoolClient'
2019-12-16T18:56:22.708521500Z 
2019-12-16 18:56:22,271:API: 127.0.0.1 - - [16/Dec/2019 18:56:22] "POST / HTTP/1.1" 400 -
2019-12-16 18:56:22,271:API: 127.0.0.1 - - [16/Dec/2019 18:56:22] "POST / HTTP/1.1" 400 -
2019-12-16 18:56:22,271:API: 127.0.0.1 - - [16/Dec/2019 18:56:22] "POST / HTTP/1.1" 400 -
2019-12-16T18:56:22:ERROR:localstack.services.generic_proxy: Error forwarding request: 'UserPoolClient' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 297, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/cognito/cognito_listener.py", line 94, in return_response
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/cognito/cognito_helpers.py", line 49, in user_pool_client_created
KeyError: 'UserPoolClient'
2019-12-16T18:56:22.708972800Z 
2019-12-16 18:56:23,715:API: 127.0.0.1 - - [16/Dec/2019 18:56:23] "POST / HTTP/1.1" 400 -
2019-12-16 18:56:23,715:API: 127.0.0.1 - - [16/Dec/2019 18:56:23] "POST / HTTP/1.1" 400 -
2019-12-16 18:56:23,715:API: 127.0.0.1 - - [16/Dec/2019 18:56:23] "POST / HTTP/1.1" 400 -
2019-12-16T18:56:23:ERROR:localstack.services.generic_proxy: Error forwarding request: 'UserPoolClient' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 297, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/cognito/cognito_listener.py", line 94, in return_response
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/cognito/cognito_helpers.py", line 49, in user_pool_client_created
KeyError: 'UserPoolClient'
2019-12-16T18:56:24.710575400Z 
2019-12-16 18:56:27,080:API: 127.0.0.1 - - [16/Dec/2019 18:56:27] "POST / HTTP/1.1" 400 -
2019-12-16 18:56:27,080:API: 127.0.0.1 - - [16/Dec/2019 18:56:27] "POST / HTTP/1.1" 400 -
2019-12-16 18:56:27,080:API: 127.0.0.1 - - [16/Dec/2019 18:56:27] "POST / HTTP/1.1" 400 -
2019-12-16T18:56:27:ERROR:localstack.services.generic_proxy: Error forwarding request: 'UserPoolClient' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 297, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/cognito/cognito_listener.py", line 94, in return_response
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/cognito/cognito_helpers.py", line 49, in user_pool_client_created
KeyError: 'UserPoolClient'
2019-12-16T18:56:27.715405700Z 
2019-12-16 18:56:32,915:API: 127.0.0.1 - - [16/Dec/2019 18:56:32] "POST / HTTP/1.1" 400 -
2019-12-16 18:56:32,915:API: 127.0.0.1 - - [16/Dec/2019 18:56:32] "POST / HTTP/1.1" 400 -
2019-12-16 18:56:32,915:API: 127.0.0.1 - - [16/Dec/2019 18:56:32] "POST / HTTP/1.1" 400 -
2019-12-16T18:56:32:ERROR:localstack.services.generic_proxy: Error forwarding request: 'UserPoolClient' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 297, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/cognito/cognito_listener.py", line 94, in return_response
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/cognito/cognito_helpers.py", line 49, in user_pool_client_created
KeyError: 'UserPoolClient'
2019-12-16T18:56:33.719327500Z 
```

**Comment by miles-po** [comment]
Received a very fast response from the Localstack folks. Looks like an issue with jq and unwanted quoting. The following with `jq -r` works.
```sh
POOL_ID=$(awslocal cognito-idp create-user-pool --pool-name my_user_pool | jq -r .UserPool.Id)
```
