### ISSUE TITLE
An error occurred (ResourceAlreadyExistsException) when calling the CreateElasticsearchDomain operation

### ISSUE THREAD

**Issue by miron4dev** [localstack/localstack#1870]
After LocalStack upgrade to the latest version, I started receiving the next error message, when I create a new elastic search domain:
```
An error occurred (ResourceAlreadyExistsException) when calling the CreateElasticsearchDomain operation
```

Command that was executed:
```
aws --endpoint-url http://localhost:4578 es create-elasticsearch-domain --domain-name test-domain --elasticsearch-version 6.7 --elasticsearch-cluster-config InstanceType=m4.large.elasticsearch,InstanceCount=1 --ebs-options EBSEnabled=true,VolumeType=standard,VolumeSize=10
```

Debug log in Docker container:
```
rm-localstack | 2019-12-17T12:44:50:ERROR:infra.py: Error checking state of local environment (after some retries): Traceback (most recent call last):
rm-localstack |   File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
rm-localstack |     additional(expect_shutdown=expect_shutdown)
rm-localstack |   File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
rm-localstack |     assert isinstance(out, six.string_types)
rm-localstack | AssertionError
rm-localstack | 
rm-localstack | During handling of the above exception, another exception occurred:
rm-localstack | 
rm-localstack | Traceback (most recent call last):
rm-localstack |   File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
rm-localstack |     additional(expect_shutdown=expect_shutdown)
rm-localstack |   File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
rm-localstack |     assert isinstance(out, six.string_types)
rm-localstack | AssertionError
```

**Comment by miron4dev** [comment]
This issue is a duplicate of https://github.com/localstack/localstack/issues/1881 

I fixed my problem by explicitly adding `elasticsearch` to my docker-compose.yml file.
