### ISSUE TITLE
Error deploying lambda using serverless-localstack plugin

### ISSUE THREAD

**Issue by spinlud** [localstack/localstack#1884]
I am trying to deploy a lambda using `serverless-localstack` plugin, but I get always the following error:

```
localstack_1  | 2019-12-19 15:30:43,891:API: 127.0.0.1 - - [19/Dec/2019 15:30:43] "PUT /serverless-deploy-bucket/serverless/myservice/dev/1576769443675-2019-12-19T15%3A30%3A43.675Z/compiled-cloudformation-template.json HTTP/1.1" 200 -
localstack_1  | 2019-12-19T15:30:43:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response from CloudFormation (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id myservice-dev does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
localstack_1  | 2019-12-19T15:30:43:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:myservice-dev-mylambda
localstack_1  | 2019-12-19T15:30:44:ERROR:localstack.services.generic_proxy: Error forwarding request: 'str' object has no attribute 'get' Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 242, in forward
localstack_1  |     path=path, data=data, headers=forward_headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 159, in forward_request
localstack_1  |     modified_request = transform_template(req_data)
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 83, in transform_template
localstack_1  |     if parsed.get('Transform') == 'AWS::Serverless-2016-10-31':
localstack_1  | AttributeError: 'str' object has no attribute 'get'

localstack_1  | 2019-12-19T15:30:45:ERROR:localstack.services.generic_proxy: Error forwarding request: 'str' object has no attribute 'get' Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 242, in forward
localstack_1  |     path=path, data=data, headers=forward_headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 159, in forward_request
localstack_1  |     modified_request = transform_template(req_data)
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 83, in transform_template
localstack_1  |     if parsed.get('Transform') == 'AWS::Serverless-2016-10-31':
localstack_1  | AttributeError: 'str' object has no attribute 'get'

[...]
```

This is the launch command for `localstack` (no errors):

```
SERVICES="iam,s3,sns,lambda,sts,cloudformation" LAMBDA_REMOTE_DOCKER=false LAMBDA_DOCKER_NETWORK=host \
LAMBDA_EXECUTOR=docker DEBUG=1 localstack start --docker
```

This is the `serverless` configuration:
```
service: myservice

provider:
  name: aws
  runtime: nodejs10.x
  deploymentBucket:
    name: serverless-deploy-bucket
  environment:
    NODE_ENV: ${env:NODE_ENV}

plugins:
  - serverless-localstack

custom:
  localstack:
    debug: true
    host: http://localhost
    lambda:
      mountCode: true

functions:
  mylambda:
    handler: index.handler
    events:
        - sns: ${env:SNS_INPUT_TOPIC_ARN}
```

This is the deploy command for `serverless` (all needed S3 buckets and SNS topics are created before deploy):

```
NODE_ENV=local SNS_INPUT_TOPIC_ARN="arn:aws:sns:us-east-1:000000000000:mytopic" node node_modules/serverless/bin/serverless.js deploy --noTimeout
```

I've tried also to set `mountCode` to false in serverless configuration, but same result.

`os`: MacOS 10.15
`Docker`: 2.1.0.5
`Python`: 3.7.4
`localstack`: 0.10.6
`serverless`: 1.59.3
`serverless-localstack`: 0.4.22

**Comment by whummer** [comment]
Thanks for reporting @spinlud . This should be fixed in #1889 - can you please give it a try with the latest version. Please report here if the problem persists. Thanks
