### ISSUE TITLE
Consecutive executions of lambda with LAMBDA_EXECUTOR="docker-reuse" cause "bind: address already in use" exception

### ISSUE THREAD

**Issue by spinlud** [localstack/localstack#1892]
Not sure if this is an issue or expected behaviour. I have a test suite which triggers consecutive executions of the same lambda function.  To speedup I have set `LAMBDA_EXECUTOR="docker-reuse"` to use the same container for the lambda execution. I've noticed the following exception at runtime:

```
2019-12-20T09:45:49:DEBUG:localstack.services.awslambda.lambda_executors: Using entrypoint "/var/rapid/init --bootstrap /var/runtime/bootstrap" for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_rb-files-hub-service-dev-rb-files-hub" on network "host".
2019-12-20T09:45:49:DEBUG:localstack.services.awslambda.lambda_executors: Command for docker-reuse Lambda executor:  docker exec -e NODE_ENV="$NODE_ENV" -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e _LAMBDA_SERVER_PORT="$_LAMBDA_SERVER_PORT" localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_rb-files-hub-service-dev-rb-files-hub /var/rapid/init --bootstrap /var/runtime/bootstrap index.handler
2019-12-20T09:45:49:DEBUG:localstack.services.awslambda.lambda_executors: Running lambda cmd:  docker exec -e NODE_ENV="$NODE_ENV" -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e _LAMBDA_SERVER_PORT="$_LAMBDA_SERVER_PORT" localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_rb-files-hub-service-dev-rb-files-hub /var/rapid/init --bootstrap /var/runtime/bootstrap index.handler
2019-12-20T09:45:49:WARNING:bootstrap.py: Thread run method <function LambdaExecutor.execute.<locals>.do_execute at 0x7f59b11db4d0>(None) failed: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 413, in run
    self.func(self.params)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 70, in do_execute
    result, log_output = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 241, in _execute
    result, log_output = self.run_lambda_executor(cmd, stdin, environment)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 161, in run_lambda_executor
    (return_code, result, log_output))
Exception: Lambda process returned error status code: 1. Result: . Output:
2019/12/20 09:45:49 listen tcp :9001: bind: address already in use
```

Is the execution of the lambda handled in a different process inside the lambda container or it is the same process when using `LAMBDA_EXECUTOR="docker-reuse"`? If the latter is true, I suspect that the reason for this exception could be probably that the previous lambda invocation has not finished when the next invocation occurs.

`os`: MacOS 10.15
`Docker`: 2.1.0.5
`Python`: 3.7.4
`localstack`: 0.10.6
`serverless`: 1.59.3
`serverless-localstack`: 0.4.22

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-143) by [Unito](https://www.unito.io/learn-more)

**Comment by juanibiapina** [comment]
I'm getting this without setting `LAMBDA_EXECUTOR`

**Comment by charlie-harvey** [comment]
When I set `LAMBDA_EXECUTOR=docker-reuse` I get the Bind :9001: error. When I set `LAMBDA_EXECUTOR=docker` I get nothing. As in, nothing executes and it never returns.

This is what shows in the terminal:

`
2020-03-31T19:17:44:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: docker run -i  -v "/Users/charlieharvey/workspace/assessment-service":/var/task -e NODE_ENV="$NODE_ENV" -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e NODE_TLS_REJECT_UNAUTHORIZED="$NODE_TLS_REJECT_UNAUTHORIZED" -e DOCKER_LAMBDA_API_PORT="$DOCKER_LAMBDA_API_PORT" -e DOCKER_LAMBDA_RUNTIME_PORT="$DOCKER_LAMBDA_RUNTIME_PORT" --network="host"  "lambci/lambda:nodejs12.x" "dist/src/lambda.handler"
`

But nothing ever returns in the browser. I am using serverless-localstack to deploy my app.

```
  localstack:
    image: "localstack/localstack:latest"
    ports:
      - "4567-4599:4567-4599"
      - "${PORT_WEB_UI:-8080}:8080"
    environment:
      - SERVICES=serverless,apigateway,dynamodb,iam,lambda,s3,ses,sns,sqs,cloudformation,sts
      - DEFAULT_REGION=us-east-2
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      # - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOVE_CONTAINERS=false
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_DOCKER_NETWORK=host
      - LAMBDA_API_PORT=8001
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
```

serverless.yml:
```
service:
  name: awesome-service

plugins:
  - serverless-localstack
  - serverless-deployment-bucket

custom:
  localstack:
    autostart: false
    debug: true
    host: http://localhost
    lambda:
      mountCode: true
    stages:
      - serverless

provider:
  name: aws
  region: us-east-2
  runtime: nodejs12.x
  stage: ${opt:stage, 'serverless'}
  deploymentBucket:
    name: deployment-bucket
    maxPreviousDeploymentArtifacts: 0
  environment:
    NODE_ENV: serverless

functions:
  main: # The name of the lambda function
    handler: dist/src/lambda.handler # The module 'handler' is exported in the file 'dist/src/lambda'
    events:
      - http:
          method: any
          path: /{any+}
```

I've been at this for days. I have tried every configuration under the sun.

**Comment by JCFerrerG** [comment]
I think this is a recurrence of the issue as described in https://github.com/localstack/localstack/issues/1777#issuecomment-663713399, at least for anyone using nodejs12.x.

**Comment by mattsoftware** [comment]
FYI I am getting this with the Nodejs container, as well as the 'provided' container. Seems to work great one at a time, as soon as a second parallel invoke hits it I get the 9001 address in use error.

**Comment by whummer** [comment]
Thanks for the update @mattsoftware @JCFerrerG . This issue should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please report here or create a follow-up ticket with updated details if the problem persists. Thanks!
