### ISSUE TITLE
S3 ListAllMyBucketsResult response CreationDate Invalid format

### ISSUE THREAD

**Issue by mardeswararao** [localstack/localstack#1899]
can someone please advise  here-

I am using the S3 service on the latest localstack version,and using the Amazon's S3 Java SDK to perform all the operations with Java 8 (Additional configuration info : aws-sdk-java/1.11.542 Windows_10/10.0 Java_HotSpot(TM)_64-Bit_Server_VM/25.60-b23 java/1.8.0_60 scala/2.10.5 groovy/2.4.10 vendor/Oracle_Corporation)

Although creating a new bucket seems to working as expected, retrieving the buckets via list buckets operation throws the following exception through the SDK:

 java.lang.IllegalArgumentException: Invalid format: "2019-12-23 05:12:26.039447" is malformed at " 05:12:26.039447"). Response Code: 200, Response Text: OK

response-

<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01"><Owner><ID>bcaf1ffd86f41161ca5fb16fd081034f</ID><DisplayName>webfile</DisplayName></Owner><Buckets><Bucket><Name>tst-adapter-us-west-2</Name><CreationDate>2019-12-23 02:17:43.014814</CreationDate></Bucket></Buckets></ListAllMyBucketsResult>

trace-

Caused by:
        java.lang.IllegalArgumentException: Invalid format: "2019-12-23 05:12:26.039447" is malformed at " 05:12:26.039447"
            at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
            at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:826)
            at com.amazonaws.util.DateUtils.doParseISO8601Date(DateUtils.java:98)
            at com.amazonaws.util.DateUtils.parseISO8601Date(DateUtils.java:77)
            at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser$ListAllMyBucketsHandler.doEndElement(XmlResponsesSaxParser.java:996)
            at com.amazonaws.services.s3.model.transform.AbstractHandler.endElement(AbstractHandler.java:52)
            at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
            at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
            at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
            at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
            at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
            at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
            at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
            at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
            at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
            at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
            at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.parseXmlInputStream(XmlResponsesSaxParser.java:152)
            ... 31 more

**Comment by sunnylbk** [comment]
I am encountering a similar issue while listing objects in S3

```
    Expected
        <*awserr.requestError | 0xc0003ea640>: {
            awsError: {
                code: "SerializationError",
                message: "failed to decode REST XML response",
                errs: [
                    {
                        Layout: "2006-01-02T15:04:05Z",
                        Value: "2019-12-24 13:08:13.979175",
                        LayoutElem: "T",
                        ValueElem: " 13:08:13.979175",
                        Message: "",
                    },
                ],
            },
            statusCode: 200,
            requestID: "",
            bytes: nil,
        }
    to be nil
```

**Comment by rnorth** [comment]
Same here; this is happening for me when trying out the new [0.10.6](https://github.com/localstack/localstack/releases/tag/v0.10.6) release. It does not happen with the 0.10.5 image, so perhaps there's a regression?

Based on [where the failure is occurring within Testcontainers' test suite](https://github.com/testcontainers/testcontainers-java/blob/master/modules/localstack/src/test/java/org/testcontainers/containers/localstack/LocalstackContainerTest.java#L65) it seems that this problem afflicts Java clients (tested with AWS Java SDK `1.11.683` and `1.11.699`) but _not_ AWS CLI (tested with `aws-cli/1.16.185 Python/2.7.15 Linux/4.9.184-linuxkit botocore/1.12.175`).

**Comment by rnorth** [comment]
I think the problem is probably in a recent-ish change to `moto-ext`: https://github.com/spulec/moto/commit/ab0853cddc6bf9a0789999751a5d698186b8ebd0#diff-f28b3d402b1d050e247f518f3b94865bR1313

The `created_date` value is, as far as I can tell, just string-formatted in the templated XML, resulting in a string that is not in the proper ISO8601 format:
```
>>> a = datetime.datetime.utcnow()
>>> str(a)
'2020-01-02 16:36:09.523540'
```

I'll raise an issue in the `moto-ext` repo...

**Comment by schleumer** [comment]
I can relate the same issue with localstack 0.10.6 using the AWS Java SDK

**Comment by whummer** [comment]
Thanks for reporting @mardeswararao @sunnylbk @rnorth @schleumer . This should be fixed in #1983 - can you please give it a try with the `latest` version of the Docker image and report here if the problem persists. Thanks

**Comment by williamokano** [comment]
@whummer after updating the localstack to latest version, I can confirm that the problem still persist.

**Comment by whummer** [comment]
Thanks for the hint @williamokano , seems like there's been an issue with our CI pipeline - re-running the build helped. The `latest` image tag should be up to date now.
