### ISSUE TITLE
Cloudformation create-stack 502 BadGateway error

### ISSUE THREAD

**Issue by naomijoshi** [localstack/localstack#1910]
I am using the **latest** localstack docker image to test aws s3, lambda and cloudformation locally. s3 and lambda seems to be working fine but when I call cloudformation **create-stack** api it gives me a 502 BadGateway error. This is the command I am using

`aws cloudformation create-stack \
  --template-body template.yaml \
  --stack-name cfn-test \
  --parameters ParameterKey=BucketPrefix,ParameterValue=demo-bucket \
  --endpoint-url=http://localhost:4581`

This is the error I get:
`An error occurred (502) when calling the CreateStack operation (reached max retries: 4): Bad Gateway`

From docker logs I got the following error
`2019-12-31T22:12:09:ERROR:localstack.services.generic_proxy: Error forwarding request: 'str' object has no attribute 'get' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 242, in forward
    path=path, data=data, headers=forward_headers)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 164, in forward_request
    modified_request = transform_template(req_data)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 83, in transform_template
    if parsed.get('Transform') == 'AWS::Serverless-2016-10-31':
AttributeError: 'str' object has no attribute 'get'`

Although, when I try the **list-stacks** api it seems to be working fine
`aws --endpoint-url=http://localhost:4581 cloudformation list-stacks`

`{
    "StackSummaries": []
}`

`2019-12-31 22:10:51,865:API: 127.0.0.1 - - [31/Dec/2019 22:10:51] "GET / HTTP/1.1" 200 -`

I could not find a solution in any of the past issues or anywhere on the internet. Please assist

**Comment by naomijoshi** [comment]
After adding file:// to the template body which I was missing earlier I got this error

``2020-01-02T19:35:51:ERROR:localstack.services.generic_proxy: Error forwarding request: 'list' object has no attribute 'split' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 342, in parse_template
    return json.loads(template)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 346, in parse_template
    return yaml.safe_load(template)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/yaml/constructor.py", line 52, in construct_document
    for dummy in generator:
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/yaml/constructor.py", line 404, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/yaml/constructor.py", line 210, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/yaml/constructor.py", line 135, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/yaml/constructor.py", line 94, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/utils.py", line 61, in yaml_tag_constructor
    return {key: _f(loader, tag, node)}
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/utils.py", line 50, in _f
    return node.value.split(".")
AttributeError: 'list' object has no attribute 'split'``

**Comment by whummer** [comment]
Thanks for reporting @naomijoshi . Can you please provide a small, self-contained example to help reproduce this issue?

Please include:
* a minimal version of the cloudformation yaml that exposes the error
* the exact command you're using to deploy the stack
* the full output and error logs of the LocalStack process

Thanks

**Comment by naomijoshi** [comment]
@whummer Thanks for responding. Yes, the same configuration in the YAML template works in real AWS via aws cli. 
Adding the example files here shortly

**Comment by naomijoshi** [comment]
@whummer I was able to get it working after removing the managed policy line and LambdaInvokePermission !GetAtt (other !GetAtt s are working fine though). My stack deployed the s3 bucket and lambda function. I am assuming IAM role and LambdaInvokePermission is not needed by localstack that it why it was ignored (please confirm).

Now the issue is, I think the NotificationConfiguration is not being attached to my bucket via cloudformation. My lambda is not being invoked when I upload an object to s3 and when I tried fetching the notification configuration using s3api cli locally, it didn't return anything. One reason I could think of is that the lambda arn returned from !GetAtt of NotificationConfiguration is `arn:aws:lambda:us-east-1:123456789012:function:triggered-lambda`, however the lambda I see on the console has account id as `000000000000`. How do I make this notification work so that my s3 bucket upload can trigger a lambda?
Latest cloudformation
```
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Testing the localstack cloudformation stack'
Parameters:
  BucketPrefix:
    Type: String
    Default: demo-bucket
Resources:
  DemoBucket:
    DependsOn: LambdaInvokePermission
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketPrefix}-localstack-service'
      NotificationConfiguration:
        LambdaConfigurations:
        - Event: "s3:ObjectCreated:*"
          Function: !GetAtt S3TriggeredLambda.Arn        
  S3TriggeredLambda:
    Type: AWS::Lambda::Function
    Properties:
      MemorySize: 256
      Timeout: 10
      Runtime: python3.6
      FunctionName: triggered-lambda
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: function.lambda_handler
      Code:
        S3Bucket: localstack-testing
        S3Key: function.py.zip
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: triggered-lambda
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Join 
        - ''
        - - 'arn:aws:s3:::'
          - !Sub '${BucketPrefix}-localstack-service'
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: {Service: [lambda.amazonaws.com]}
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: S3Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:PutObject'
                - 'S3:DeleteObject'
              Resource: !Sub "arn:aws:s3:::${BucketPrefix}-localstack-service/*"
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 'S3:ListBucket'
              Resource: 
                - !Sub "arn:aws:s3:::localstack-testing/*"
                - !Sub "arn:aws:s3:::localstack-testing"
```

Logs after the create-stack call:

```
2020-01-06T20:33:13:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource cfn-test/DemoBucket: None
2020-01-06T20:33:13:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource cfn-test/S3TriggeredLambda: None
2020-01-06T20:33:13:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource cfn-test/LambdaExecutionRole: None
2020-01-06T20:33:13:DEBUG:localstack.services.cloudformation.cloudformation_starter: Resource LambdaExecutionRole need not be deployed: {'Type': 'AWS::IAM::Role', 'Properties': {'AssumeRolePolicyDocument': {'Version': '2012-10-17', 'Statement': [{'Effect': 'Allow', 'Principal': {'Service': ['lambda.amazonaws.com']}, 'Action': ['sts:AssumeRole']}]}, 'Path': '/', 'Policies': [{'PolicyName': 'S3Policy', 'PolicyDocument': {'Version': '2012-10-17', 'Statement': [{'Effect': 'Allow', 'Action': ['s3:PutObject', 'S3:DeleteObject'], 'Resource': 'arn:aws:s3:::demo-bucket-test-localstack-service/*'}]}}]}} True
2020-01-06T20:33:13:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:triggered-lambda
2020-01-06T20:33:13:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::Lambda::Function', 'Properties': {'MemorySize': 256, 'Timeout': 10, 'Runtime': 'python3.6', 'FunctionName': 'triggered-lambda', 'Role': 'arn:aws:iam::000000000000:role/cfn-test-LambdaExecutionRole-AEEAA64URO79', 'Handler': 'function.lambda_handler', 'Code': {'S3Bucket': 'localstack-testing', 'S3Key': 'function.py.zip'}}}
2020-01-06T20:33:13:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "Lambda::Function" id "S3TriggeredLambda"
2020-01-06T20:33:13:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "Lambda::Function" in region us-east-1: create_function {'FunctionName': 'triggered-lambda', 'Runtime': 'python3.6', 'Role': 'test_role', 'Handler': 'function.lambda_handler', 'Code': {'S3Bucket': 'localstack-testing', 'S3Key': 'function.py.zip'}, 'Timeout': 10, 'MemorySize': 256}
2020-01-06T20:33:13:DEBUG:localstack.services.awslambda.lambda_executors: Getting status for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_triggered-lambda": docker ps -a --filter name='localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_triggered-lambda' --format "{{ .Status }} - {{ .Names }}" | grep -w "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_triggered-lambda" | cat
2020-01-06T20:33:13:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'DependsOn': 'LambdaInvokePermission', 'Type': 'AWS::S3::Bucket', 'Properties': {'BucketName': 'demo-bucket-test-localstack-service', 'NotificationConfiguration': {'LambdaConfigurations': [{'Event': 's3:ObjectCreated:*', 'Function': 'arn:aws:lambda:us-east-1:123456789012:function:triggered-lambda'}]}}}
2020-01-06T20:33:13:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "S3::Bucket" id "DemoBucket"
2020-01-06T20:33:13:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "S3::Bucket" in region us-east-1: create_bucket {'Bucket': 'demo-bucket-test-localstack-service', 'ACL': 'public-read', 'CreateBucketConfiguration': {'LocationConstraint': 'us-east-1'}}
2020-01-06T20:33:13:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource cfn-test/LambdaInvokePermission: None
2020-01-06T20:33:13:DEBUG:localstack.services.cloudformation.cloudformation_starter: Resource LambdaInvokePermission need not be deployed: {'Type': 'AWS::Lambda::Permission', 'Properties': {'FunctionName': 'triggered-lambda', 'Action': 'lambda:InvokeFunction', 'Principal': 's3.amazonaws.com', 'SourceAccount': '123456789012', 'SourceArn': 'arn:aws:s3:::demo-bucket-test-localstack-service'}} True
```
Thanks

**Comment by ashu2108** [comment]
> I am using the **latest** localstack docker image to test aws s3, lambda and cloudformation locally. s3 and lambda seems to be working fine but when I call cloudformation **create-stack** api it gives me a 502 BadGateway error. This is the command I am using
> 
> `aws cloudformation create-stack \ --template-body template.yaml \ --stack-name cfn-test \ --parameters ParameterKey=BucketPrefix,ParameterValue=demo-bucket \ --endpoint-url=http://localhost:4581`
> 
> This is the error I get:
> `An error occurred (502) when calling the CreateStack operation (reached max retries: 4): Bad Gateway`
> 
> From docker logs I got the following error
> `2019-12-31T22:12:09:ERROR:localstack.services.generic_proxy: Error forwarding request: 'str' object has no attribute 'get' Traceback (most recent call last): File "/opt/code/localstack/localstack/services/generic_proxy.py", line 242, in forward path=path, data=data, headers=forward_headers) File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 164, in forward_request modified_request = transform_template(req_data) File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 83, in transform_template if parsed.get('Transform') == 'AWS::Serverless-2016-10-31': AttributeError: 'str' object has no attribute 'get'`
> 
> Although, when I try the **list-stacks** api it seems to be working fine
> `aws --endpoint-url=http://localhost:4581 cloudformation list-stacks`
> 
> `{ "StackSummaries": [] }`
> 
> `2019-12-31 22:10:51,865:API: 127.0.0.1 - - [31/Dec/2019 22:10:51] "GET / HTTP/1.1" 200 -`
> 
> I could not find a solution in any of the past issues or anywhere on the internet. Please assist


I'm getting an error while creating an s3 bucket using cloud formation on the local stack 
error:
An error occurred (502) when calling the CreateStack operation (reached max retries: 4): Bad Gateway
