### ISSUE TITLE
Unable to start localstack in gitlab runner

### ISSUE THREAD

**Issue by kobik** [localstack/localstack#1926]
HI, I'm trying to start localstack in gitlab runner without any success.

Using the same docker-compose file locally on my mac with network-mode bridge without any issue.
It seems like SQS rest service is up and reachable from inside the runner and other services on the same docker network, but it doesn't pass the localstack infra check.

docker-compose file

```yaml
  localstack:
    image: localstack/localstack
    network_mode: host
    ports:
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=${SQS_REGION:-eu-central-1}
      - DEBUG=${DEBUG:-1}
      - DOCKER_HOST=unix:///var/run/docker.sock
```

```log
/ # docker logs -f scripts_localstack_1
Waiting for all LocalStack services to be ready
2020-01-06 14:26:52,509 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-01-06 14:26:52,512 INFO supervisord started with pid 13
2020-01-06 14:26:53,514 INFO spawned: 'dashboard' with pid 19
2020-01-06 14:26:53,516 INFO spawned: 'infra' with pid 20
2020-01-06 14:26:53,523 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; bin/localstack web)
(. .venv/bin/activate; exec bin/localstack start --host)
Starting local dev environment. CTRL-C to quit.
2020-01-06 14:26:55,004 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-01-06T14:26:57:WARNING:bootstrap.py: Unable to load plugins from file /opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/plugins.py: No module named 'localstack_ext.utils.aws.aws_models'
Waiting for all LocalStack services to be ready
Starting mock SQS (http port 4576)...
14:27:00.252 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.2) ...
14:27:00.903 [elasticmq-akka.actor.default-dispatcher-3] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
14:27:02.296 [elasticmq-akka.actor.default-dispatcher-3] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:4561, visible server address http://runner-gn1eaflj-project-1729-concurrent-02q8b4:4576
14:27:02.298 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.15.2) started in 2811 ms ===
14:27:04.129 [elasticmq-akka.actor.default-dispatcher-3] INFO  o.elasticmq.actor.QueueManagerActor - Creating queue QueueData(eks-qa-payouts-sandbox-default-queue.fifo,MillisVisibilityTimeout(30000),PT0S,PT0S,2020-01-06T14:27:04.076Z,2020-01-06T14:27:04.076Z,None,false,false,None,None,Map())
Waiting for all LocalStack services to be ready
2020-01-06T14:27:10:WARNING:infra.py: Service "sqs" not yet available, retrying...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2020-01-06T14:27:21:WARNING:infra.py: Service "sqs" not yet available, retrying...
Waiting for all LocalStack services to be ready
2020-01-06T14:27:31:WARNING:infra.py: Service "sqs" not yet available, retrying...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2020-01-06T14:27:42:WARNING:infra.py: Service "sqs" not yet available, retrying...
Waiting for all LocalStack services to be ready
2020-01-06T14:27:49:WARNING:infra.py: Service "sqs" not yet available, retrying...
Waiting for all LocalStack services to be ready
2020-01-06T14:28:02:WARNING:infra.py: Service "sqs" not yet available, retrying...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2020-01-06T14:28:16:WARNING:infra.py: Service "sqs" not yet available, retrying...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2020-01-06T14:28:23:WARNING:infra.py: Service "sqs" not yet available, retrying...
Waiting for all LocalStack services to be ready
2020-01-06T14:28:31:WARNING:infra.py: Service "sqs" not yet available, retrying...
Waiting for all LocalStack services to be ready
2020-01-06T14:28:44:WARNING:infra.py: Service "sqs" not yet available, retrying...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Error starting infrastructure: 'NoneType' object has no attribute 'get' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 384, in check_infra
    raise e
  File "/opt/code/localstack/localstack/services/infra.py", line 381, in check_infra
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/infra.py", line 69, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/sqs/sqs_starter.py", line 31, in check_sqs
    assert out.get('ResponseMetadata', {}).get('HTTPStatusCode') == 200
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 384, in check_infra
    raise e
  File "/opt/code/localstack/localstack/services/infra.py", line 381, in check_infra
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/infra.py", line 69, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/sqs/sqs_starter.py", line 31, in check_sqs
    assert out.get('ResponseMetadata', {}).get('HTTPStatusCode') == 200
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 384, in check_infra
    raise e
  File "/opt/code/localstack/localstack/services/infra.py", line 381, in check_infra
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/infra.py", line 69, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/sqs/sqs_starter.py", line 31, in check_sqs
    assert out.get('ResponseMetadata', {}).get('HTTPStatusCode') == 200
AttributeError: 'NoneType' object has no attribute 'get'
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-145) by [Unito](https://www.unito.io/learn-more)

**Comment by kag0** [comment]
Similarly, I'm unable to run localstack on gitlab runner (self hosted) from the java/junit library.

I'm seeing 

```
Feb 19, 2020 1:49:43 AM cloud.localstack.docker.annotation.LocalstackDockerAnnotationProcessor getExternalHostName
INFO: External host name is set to: localhost
Feb 19, 2020 1:50:08 AM cloud.localstack.docker.Container createLocalstackContainer
INFO: Started container: Unable to find image 'localstack/localstack:latest' locally
latest: Pulling from localstack/localstack
d82b0d0113f3: Pulling fs layer
d82b0d0113f3: Verifying Checksum
d82b0d0113f3: Download complete
d82b0d0113f3: Pull complete
Digest: sha256:1b90af056378529aa36d378f9a1ae69148642fc2002605643cae752979ce14ab
Status: Downloaded newer image for localstack/localstack:latest
4aeb799d48f0a0f66bb4c5d3a73e5733ff3efa49ffcecb46928a75e06b0c335b
Feb 19, 2020 1:50:08 AM cloud.localstack.Localstack startup
INFO: Waiting for LocalStack container to be ready...
Feb 19, 2020 1:52:16 AM cloud.localstack.docker.Container stop
INFO: Stopped container: Unable to find image 'localstack/localstack:latest' locally
latest: Pulling from localstack/localstack
d82b0d0113f3: Pulling fs layer
d82b0d0113f3: Verifying Checksum
d82b0d0113f3: Download complete
d82b0d0113f3: Pull complete
Digest: sha256:1b90af056378529aa36d378f9a1ae69148642fc2002605643cae752979ce14ab
Status: Downloaded newer image for localstack/localstack:latest
4aeb799d48f0a0f66bb4c5d3a73e5733ff3efa49ffcecb46928a75e06b0c335b
Feb 19, 2020 1:52:16 AM cloud.localstack.docker.Container stop
INFO: Stopped container: Unable to find image 'localstack/localstack:latest' locally
latest: Pulling from localstack/localstack
d82b0d0113f3: Pulling fs layer
d82b0d0113f3: Verifying Checksum
d82b0d0113f3: Download complete
d82b0d0113f3: Pull complete
Digest: sha256:1b90af056378529aa36d378f9a1ae69148642fc2002605643cae752979ce14ab
Status: Downloaded newer image for localstack/localstack:latest
4aeb799d48f0a0f66bb4c5d3a73e5733ff3efa49ffcecb46928a75e06b0c335b
Test *** ABORTED ***
  cloud.localstack.docker.exception.LocalstackDockerException: Could not start the localstack docker container.
  at cloud.localstack.Localstack.startup(Localstack.java:86)
  ...
  Cause: java.lang.IllegalStateException: Could not find token: Ready\. in docker logs.
  at cloud.localstack.docker.Container.waitForLogToken(Container.java:136)
  at cloud.localstack.Localstack.startup(Localstack.java:83)
  ...
```

"works on my machine", but it's weird that it seems to try repeatedly to download the image on gitlab.

**Comment by delijati** [comment]
try my repo [1] ... but unfortunately you will into a s3 problem after too many requests :/ [2]

[1] https://gitlab.com/delijati/localstack-gitlabci-test
[2] https://gitlab.com/gitlab-org/gitlab-runner/issues/16946

**Comment by delijati** [comment]
@whummer should i make a separate ticket out of it ? [1]
[1] https://github.com/localstack/localstack/issues/1926#issuecomment-594919002

**Comment by delijati** [comment]
One thing more when i run it without docker aka `unittest` it works [1]

[1] https://gitlab.com/delijati/localstack-gitlabci-test-host/

**Comment by delijati** [comment]
here a update ... i got it working by using the default port and not specificity any port for s3. This is a  bug in localstack docker or localstack.

https://gitlab.com/delijati/localstack-gitlabci-test/-/commit/5044bdc7f380879731e9ae59a8caebd94642a42e

**Comment by whummer** [comment]
Thanks for the detailed report @delijati . In the meantime we have changed the layout of default ports in LocalStack - requests are now routed through a single edge service (port `4566` by default), and the service-specific ports are now obsolete/deprecated. Please let us know if the problem persists in the `latest` version. Thanks!
