### ISSUE TITLE
Errors when creating Elasticsearch domain

### ISSUE THREAD

**Issue by AntonFagerberg** [localstack/localstack#1931]
I'm following up on #1881 and trying the suggested solution for creating an Elasticsearch domain (I'm running the latest version of LocalStack as of what's published to DockerHub today).

My `docker-compose.yml` is defined as:
```yml
  localstack:
    image: localstack/localstack
    container_name: localstack-xyz
    ports:
      - "8000:4569"
      - "8001:4571"
    environment:
      - SERVICES=dynamodb,es
      - DEFAULT_REGION=eu-west-1
      - START_WEB=0
    volumes:
      - ./init-scripts:/docker-entrypoint-initaws.d
```

I'm using this to create the Elasticsearch domain:
`awslocal es create-elasticsearch-domain --domain-name xyz`

This is the logs I'm getting:

```
Waiting for all LocalStack services to be ready
2020-01-07 14:04:19,282 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-01-07 14:04:19,285 INFO supervisord started with pid 13
2020-01-07 14:04:20,290 INFO spawned: 'dashboard' with pid 19
2020-01-07 14:04:20,293 INFO spawned: 'infra' with pid 20
2020-01-07 14:04:20,298 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-01-07 14:04:20,298 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
Starting local dev environment. CTRL-C to quit.
2020-01-07 14:04:21,656 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting mock DynamoDB (http port 4569)...
Starting mock ES service (http port 4578)...
Waiting for all LocalStack services to be ready
Ready.
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initaws.d/create-elasticsearch.sh
Starting local Elasticsearch (http port 4571)...

An error occurred (ResourceAlreadyExistsException) when calling the CreateElasticsearchDomain operation: 
2020-01-07T14:07:13:ERROR:infra.py: Error checking state of local environment (after some retries): Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

2020-01-07T14:07:13:ERROR:flask.app: Exception on /2015-01-01/es/domain [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/services/es/es_api.py", line 201, in create_domain
    start_elasticsearch_instance()
  File "/opt/code/localstack/localstack/services/es/es_api.py", line 173, in start_elasticsearch_instance
    check_infra(apis=apis, additional_checks=[es_starter.check_elasticsearch])
  File "/opt/code/localstack/localstack/services/infra.py", line 393, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 393, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 393, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  [Previous line repeated 7 more times]
  File "/opt/code/localstack/localstack/services/infra.py", line 391, in check_infra
    raise e
  File "/opt/code/localstack/localstack/services/infra.py", line 387, in check_infra
    additional(expect_shutdown=expect_shutdown)
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 91, in check_elasticsearch
    assert isinstance(out, six.string_types)
AssertionError
Waiting for all LocalStack services to be ready
2020-01-07 14:26:05,559 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-01-07 14:26:05,564 INFO supervisord started with pid 13
2020-01-07 14:26:06,568 INFO spawned: 'dashboard' with pid 19
2020-01-07 14:26:06,569 INFO spawned: 'infra' with pid 20
2020-01-07 14:26:06,573 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-01-07 14:26:06,573 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
Starting local dev environment. CTRL-C to quit.
2020-01-07 14:26:08,338 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by AntonFagerberg** [comment]
This was caused by a full `Docker.raw` file so it had nothing to do with LocalStack itself.
Increasing it solved my issue.

**Comment by whummer** [comment]
Great, thanks for posting the solution here @AntonFagerberg 👍
