### ISSUE TITLE
Unable to create Cloudwatch event with terraform

### ISSUE THREAD

**Issue by jamestaylordev** [localstack/localstack#1958]
We're using localstack `0.10.6` and are running into issues when creating a Cloudwatch event rule using the AWS terraform provider (`2.44.0`).

We have the following event rule defined in terraform:
```
resource "aws_cloudwatch_event_rule" "every_five_seconds" {
    name = "every-five-seconds"
    description = "Fires every five seconds"
    schedule_expression = "rate(5 seconds)"
}
```

When we run terraform apply against our local Cloudwatch Events it just hangs with `Still creating...`.  On inspecting the localstack logs we can see the following `NotImplementedError`:

```
localstack_1           | 2020-01-16 17:23:07,572:API: Error on request:
localstack_1           | Traceback (most recent call last):
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 304, in run_wsgi
localstack_1           |     execute(self.server.app)
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 292, in execute
localstack_1           |     application_iter = app(environ, start_response)
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 135, in __call__
localstack_1           |     return backend_app(environ, start_response)
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
localstack_1           |     return self.wsgi_app(environ, start_response)
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
localstack_1           |     response = self.handle_exception(e)
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_1           |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
localstack_1           |     reraise(exc_type, exc_value, tb)
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
localstack_1           |     raise value
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
localstack_1           |     response = self.full_dispatch_request()
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
localstack_1           |     rv = self.handle_user_exception(e)
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_1           |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
localstack_1           |     reraise(exc_type, exc_value, tb)
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
localstack_1           |     raise value
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
localstack_1           |     rv = self.dispatch_request()
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
localstack_1           |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 146, in __call__
localstack_1           |     result = self.callback(request, request.url, {})
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 197, in dispatch
localstack_1           |     return cls()._dispatch(*args, **kwargs)
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 295, in _dispatch
localstack_1           |     return self.call_action()
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 393, in call_action
localstack_1           |     "The {0} action has not been implemented".format(action)
localstack_1           | NotImplementedError: The list_tags_for_resource action has not been implemented
```

Using the AWS CLI to create the event rule works fine, just not when using a Terraform `aws_cloudwatch_event_rule` resource.

**Comment by whummer** [comment]
Thanks for reporting @jamestaylordev - this should have been fixed in the meantime. Can you please give it a try with the `latest` version? Please report here if the problem persists. Thanks

Side note: It seems that `seconds` is not a valid time unit - highest precision is `minutes`: https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#RateExpressions
