### ISSUE TITLE
Firehose Update Destination Kwarg Mismatch

### ISSUE THREAD

**Issue by triplejay2013** [localstack/localstack#2020]
## Description
In an attempt to update Destinations for Kinesis Firehose, the update failed due to an internal error. After some inspection it seems to be a simple kwarg mismatch? (see below)

## Related Issues
I am using terraform to deploy resources, and everything deploys fine. But I am experiencing similar issues as @taylorperkins [496](https://github.com/localstack/localstack/issues/496). These failures led me to discovering this bug.

## Problematic LOC
localstack/services/firehose/firehose_api.py:275
```
update_destination(stream_name=stream_name, destination_id=destination_id,
                           es_update=es_update, version_id=version_id)
```

AND 

localstack/services/firehose/firehose_api.py:128
```
def update_destination(stream_name, destination_id,
                       s3_update=None, elasticsearch_update=None, version_id=None):
```
Note that `update_destination` references kwarg `es_update` which doesn't exist (should be `elasticsearch_update`?)

## Stack Trace
```
2020-02-05T17:05:30:ERROR:flask.app: Exception on / [POST]                                                                                                                                    
Traceback (most recent call last):                                                                                                                                                            
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app                                                                                          
    response = self.full_dispatch_request()                                                                                                                                                   
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request                                                                             
    rv = self.handle_user_exception(e)                                                                                                                                                        
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function                                                                        
    return cors_after_request(app.make_response(f(*args, **kwargs)))                                                                                                                          
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception                                                                             
    reraise(exc_type, exc_value, tb)                                                                                                                                                          
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise                                                                                         
    raise value                                                                                                                                                                               
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 276, in post_request
    es_update=es_update, version_id=version_id)
TypeError: update_destination() got an unexpected keyword argument 'es_update'

```

**Comment by whummer** [comment]
Thanks for the detailed report @triplejay2013 . This should be fixed in #2040 - can you please give it a try with the `latest` version, and report here if the problem persists. Thanks
