### ISSUE TITLE
localstack 0.10.2 doesn't start anymore

### ISSUE THREAD

**Issue by razorree** [localstack/localstack#2023]
when i try to start 
 `docker run localstack/localstack:0.10.2`

at the end i have logs:

```
cannot import name 'dns_server'
Starting mock ES service (http port 4578)...
Starting local Elasticsearch (http port 4571)...
Starting mock S3 (http port 4572)...
Starting mock SNS (http port 4575)...
2020-02-06T10:14:01:INFO:localstack.multiserver: Starting multi API server process on port 51492
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Error starting infrastructure:  Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 385, in start_infra
    t1 = plugin.start(asynchronous=True)
  File "/opt/code/localstack/localstack/services/infra.py", line 63, in start
    return self.start_function(**kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 124, in start_sns
    backend_port=DEFAULT_PORT_SNS_BACKEND, update_listener=update_listener)
  File "/opt/code/localstack/localstack/services/infra.py", line 264, in start_moto_server
    return multiserver.start_api_server(key, backend_port or port)
  File "/opt/code/localstack/localstack/utils/server/multiserver.py", line 70, in start_api_server
    thread = start_server_process(server_port)
  File "/opt/code/localstack/localstack/utils/server/multiserver.py", line 98, in start_server_process
    wait_for_port_open(port, retries=10, sleep_time=1)
  File "/opt/code/localstack/localstack/utils/common.py", line 376, in wait_for_port_open
    return retry(check, sleep=sleep_time, retries=retries)
  File "/opt/code/localstack/localstack/utils/common.py", line 409, in retry
    raise raise_error
  File "/opt/code/localstack/localstack/utils/common.py", line 405, in retry
    return function(**kwargs)
  File "/opt/code/localstack/localstack/utils/common.py", line 374, in check
    raise Exception()
Exception
```

(before October'19 it worked). is it a case with new kernel ?
`Linux 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
`Ubuntu 18.04 LTS`

**Comment by whummer** [comment]
Thanks for reporting @razorree . We've meanwhile made some improvements in the startup procedure - can you please give it a try with the latest release (`0.10.8`) or the `latest` version of the Docker image? Please report here if the problem persists. Thanks!
