### ISSUE TITLE
Support Java 11 in Local Lambda Executor

### ISSUE THREAD

**Issue by hisener** [localstack/localstack#2093]
Invoking a lambda that has been compiled by JDK 9+ with the following options causes `UnsupportedClassVersionError`. I think it's because of the fat jar compiled by JDK 8.

```
- LAMBDA_EXECUTOR=local
- LAMBDA_REMOTE_DOCKER=false
```

`
Exception in thread "main" java.lang.UnsupportedClassVersionError: ImageTransformer has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
`

The full log:
```
localstack_1               | 2020-02-26T09:29:49:WARNING:localstack.services.awslambda.lambda_executors: java  -cp /opt/code/localstack/localstack/infra/localstack-utils-fat.jar:/tmp/localstack/zipfile.ebe369ca/original_lambda_archive.zip:.:<classpath> cloud.localstack.LambdaExecutor ImageTransformer /tmp/localstack/lambda.event.b904f671.json
localstack_1               | 2020-02-26T09:29:50:WARNING:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:eu-west-1:000000000000:function:image-manager-lambda-local: Lambda process returned error status code: 1. Result: . Output:
localstack_1               | Exception in thread "main" java.lang.UnsupportedClassVersionError: ImageTransformer has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
localstack_1               | 	at java.lang.ClassLoader.defineClass1(Native Method)
localstack_1               | 	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
localstack_1               | 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
localstack_1               | 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
localstack_1               | 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
localstack_1               | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
localstack_1               | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
localstack_1               | 	at java.security.AccessController.doPrivileged(Native Method)
localstack_1               | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
localstack_1               | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
localstack_1               | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
localstack_1               | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
localstack_1               | 	at java.lang.Class.forName0(Native Method)
localstack_1               | 	at java.lang.Class.forName(Class.java:264)
localstack_1               | 	at cloud.localstack.LambdaExecutor.getHandler(LambdaExecutor.java:150)
localstack_1               | 	at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:64) Traceback (most recent call last):
localstack_1               |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 379, in run_lambda
localstack_1               |     result, log_output = LAMBDA_EXECUTOR.execute(func_arn, func_details,
localstack_1               |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 116, in execute
localstack_1               |     return do_execute()
localstack_1               |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 101, in do_execute
localstack_1               |     raise e
localstack_1               |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 90, in do_execute
localstack_1               |     result, log_output = self._execute(func_arn, func_details, event, context, version)
localstack_1               |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 657, in _execute
localstack_1               |     process.run()
localstack_1               |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
localstack_1               |     self._target(*self._args, **self._kwargs)
localstack_1               |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 652, in do_execute
localstack_1               |     result = lambda_function(event, context)
localstack_1               |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 494, in execute
localstack_1               |     result, log_output = lambda_executors.EXECUTOR_LOCAL.execute_java_lambda(
localstack_1               |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 675, in execute_java_lambda
localstack_1               |     result, log_output = self.run_lambda_executor(cmd)
localstack_1               |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 153, in run_lambda_executor
localstack_1               |     raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
localstack_1               | Exception: Lambda process returned error status code: 1. Result: . Output:
localstack_1               | Exception in thread "main" java.lang.UnsupportedClassVersionError: ImageTransformer has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
localstack_1               | 	at java.lang.ClassLoader.defineClass1(Native Method)
localstack_1               | 	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
localstack_1               | 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
localstack_1               | 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
localstack_1               | 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
localstack_1               | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
localstack_1               | 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
localstack_1               | 	at java.security.AccessController.doPrivileged(Native Method)
localstack_1               | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
localstack_1               | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
localstack_1               | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
localstack_1               | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
localstack_1               | 	at java.lang.Class.forName0(Native Method)
localstack_1               | 	at java.lang.Class.forName(Class.java:264)
localstack_1               | 	at cloud.localstack.LambdaExecutor.getHandler(LambdaExecutor.java:150)
localstack_1               | 	at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:64)
localstack_1               | 
```

**Comment by whummer** [comment]
Thanks for reporting @hisener . Do you think you could help resolve this issue by raising a pull request against this repo: https://github.com/localstack/localstack-java-utils . That would be much appreciated, thanks!

**Comment by hisener** [comment]
I might take a look later. I think we need to do two things:
1. Upgrade JVM version in localstack docker image.
2. Compile `localstack-java-utils` using JDK 11.

**Comment by moritzzimmer** [comment]
@whummer @hisener any updates on this issue? Would be great to be able to invoke java Lambda functions with version 55 (java 11) on localstack

**Comment by harryurban** [comment]
following up on the java11 runtime issue: 
I noticed `- add support for Java11 Lambda runtime` in the release message of `v0.10.8`. 
Does this mean that using docker images from 0.10.8 and upwards should support invoking lambda functions written in java11? 
Do we need to use the full image for that, because recent testing resulted in the error mentioned above.

**Comment by ashameem123** [comment]
Getting the same error "Exception in thread "main" java.lang.UnsupportedClassVersionError: publisFunction has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0" 
Any workaround ?

**Comment by hisener** [comment]
Created https://github.com/localstack/localstack/pull/3166 to upgrade the JRE version, it should solve this issue. cc @whummer @moritzzimmer @harryurban @ashameem123
