### ISSUE TITLE
DynamoDBStream.describeStream - TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by MatheusVellone** [localstack/localstack#210]
I'm working on a way to retrieve all stream data from a local dynamodb table. So I developed this little function to get stream data based on the tableName.
The `dynamoStream.describeStream` method call is resulting in an `INTERNAL SERVER ERROR` in the application scope, and the folowing error pops out in the terminal running localstack

    ERROR:ddb_streams_api:Exception on / [POST]
    Traceback (most recent call last):
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
    File "/opt/code/localstack/localstack/services/dynamodbstreams/dynamodbstreams_api.py", line 89, in post_request
    return jsonify(result)
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/json.py", line 237, in jsonify
    return current_app.response_class(dumps(dict(*args, **kwargs),
    TypeError: 'NoneType' object is not iterable
    ERROR:ddb_streams_api:Exception on / [POST]
    Traceback (most recent call last):
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
    File "/opt/code/localstack/localstack/services/dynamodbstreams/dynamodbstreams_api.py", line 89, in post_request
    return jsonify(result)
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/json.py", line 237, in jsonify
    return current_app.response_class(dumps(dict(*args, **kwargs),
    TypeError: 'NoneType' object is not iterable
    ERROR:ddb_streams_api:Exception on / [POST]
    Traceback (most recent call last):
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
    File "/opt/code/localstack/localstack/services/dynamodbstreams/dynamodbstreams_api.py", line 89, in post_request
    return jsonify(result)
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/json.py", line 237, in jsonify
    return current_app.response_class(dumps(dict(*args, **kwargs),
    TypeError: 'NoneType' object is not iterable
    ERROR:ddb_streams_api:Exception on / [POST]
    Traceback (most recent call last):
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
    File "/opt/code/localstack/localstack/services/dynamodbstreams/dynamodbstreams_api.py", line 89, in post_request
    return jsonify(result)
    File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/json.py", line 237, in jsonify
    return current_app.response_class(dumps(dict(*args, **kwargs),
    TypeError: 'NoneType' object is not iterable

The code i'm running is here, and I've added a comment to where the error occurs

    module.exports.getDynamoDBStreamData = (dynamoTableName) => {
        return dynamo.describeTable({
            TableName: dynamoTableName,
        }).promise()
            .then((tableData) => {
                const streamArn = tableData.Table.LatestStreamArn;
    
                return dynamoStream.describeStream({ // HERE THE ERROR OCCURS
                    StreamArn: streamArn,
                }).promise()
                    .then((streamData) => {
                        const shardIds = streamData.StreamDescription.Shards.map((shard) => {
                            return shard.ShardId;
                        });
    
                        return Promise.all(shardIds.map((shardId) => {
                            return dynamoStream.getShardIterator({
                                ShardId: shardId,
                                ShardIteratorType: 'TRIM_HORIZON',
                                StreamArn: streamArn,
                            }).promise()
                                .then((shardIteratorData) => {
                                    return dynamoStream.getRecords({
                                        ShardIterator: shardIteratorData.ShardIterator,
                                    });
                                });
                        }));
                    });
            })
            .then((batchOfStreams) => {
                return batchOfStreams.reduce((result, streams) => {
                    return result.concat(streams);
                });
            });
    };

Related to the DynamoStream, a simple question about localstack functionality: if I create, update or delete any dynamodb data, the event can be retrieved via `dynamoStream.getRecords` ?

**Comment by whummer** [comment]
Thanks for reporting @MatheusVellone . Without knowing all the details of your configuration, my guess would be that your client is using a region that is different from `us-east-1` and then the stream cannot be found (resulting in the exception above, which should not happen).

Two things:
* This PR contains a fix to return a proper "not found" error message to the client: https://github.com/localstack/localstack/pull/225
* Regarding the region, currently only `us-east-1` is supported (we're working on multi-region support). Can you make sure that your client is configured accordingly and give it a try. Thanks

**Comment by MatheusVellone** [comment]
Yes, you're correct, I'm using the region `us-west-2`.
I'll change to `us-east-1`, since region doesn't break my app, to be able to use it and keep an eye to the multi-region support.

Thanks for the quick response and "fix" @whummer! You're doing a great job with Localstack!
