### ISSUE TITLE
Region ignored when using ${AWS::Region} in template

### ISSUE THREAD

**Issue by SaMnCo** [localstack/localstack#2115]
Hi there! 

I am using a template with 

```Resources
  GlobalDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub local-local-${AWS::Region}-DLQ
```

(local-local comes from a build phase that happens prior to this template and is expected even if weird)

This is then being reused as a DLQ for other resources. First of all I thought I was stumbling on #1416 since I effectively got the error message: 

```

An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the CreateStack operation: Could not find DLQ for arn:aws:sqs:eu-west-1:000000000000:local-local-us-east-1-DLQ
```

However, I then noticed that the ARN for that error queue is **arn:aws:sqs:eu-west-1:000000000000:local-local-us-east-1-DLQ** where you can see the region of the ARN is _eu-west-1_ (effectively what I set as DEFAULT_REGION), while the name of the queue contains _us-east-1_

So it seems there is a discrepancy. Localstack logs show something like: 

```
localstack_main | 2020-03-02T11:22:29:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "AmazonAPIQueue": 400 Bad Request: <?xml version="1.0" encoding="UTF-8"?>
localstack_main |   <ErrorResponse>
localstack_main |     <Errors>
localstack_main |       <Error>
localstack_main |         <Code>AWS.SimpleQueueService.NonExistentQueue</Code>
localstack_main |         <Message>Could not find DLQ for arn:aws:sqs:eu-west-1:123456789012:local-local-us-east-1-DLQ</Message>
localstack_main |         
localstack_main |       </Error>
localstack_main |     </Errors>
localstack_main |   <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
localstack_main | </ErrorResponse> Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 186, in parse_and_create_resource
localstack_main |     return _parse_and_create_resource(logical_id, resource_json,
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 244, in _parse_and_create_resource
localstack_main |     resource = parse_and_create_resource_orig(logical_id,
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 338, in parse_and_create_resource
localstack_main |     resource = resource_class.create_from_cloudformation_json(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/sqs/models.py", line 353, in create_from_cloudformation_json
localstack_main |     return sqs_backend.create_queue(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/sqs/models.py", line 523, in create_queue
localstack_main |     new_queue = Queue(name, region=self.region_name, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/sqs/models.py", line 242, in __init__
localstack_main |     self._set_attributes(defaults, now)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/sqs/models.py", line 288, in _set_attributes
localstack_main |     self._setup_dlq(attributes["RedrivePolicy"])
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/sqs/models.py", line 339, in _setup_dlq
localstack_main |     raise RESTError(
localstack_main | moto.core.exceptions.RESTError: 400 Bad Request: <?xml version="1.0" encoding="UTF-8"?>
localstack_main |   <ErrorResponse>
localstack_main |     <Errors>
localstack_main |       <Error>
localstack_main |         <Code>AWS.SimpleQueueService.NonExistentQueue</Code>
localstack_main |         <Message>Could not find DLQ for arn:aws:sqs:eu-west-1:123456789012:local-local-us-east-1-DLQ</Message>
localstack_main |         
localstack_main |       </Error>
localstack_main |     </Errors>
localstack_main |   <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
localstack_main | </ErrorResponse>
```

where again we can see that difference. This time btw the AccountID is also different and points to _123456789012_

Not sure what more I should do to help, I am using the daily Localstack Docker image that I pulled minutes ago.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-160) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @SaMnCo . This should be fixed in the meantime - a small integration test has been added in #3761 . Please let us know if the problem persists with the `latest` version. Thanks for your help
