### ISSUE TITLE
ssl.SSLError docker compose service

### ISSUE THREAD

**Issue by abinhho** [localstack/localstack#2128]
Hello again,
I am using docker service and env variable `USE_SSL=true`.

I use this command to generate ssl key files:
```
openssl req -x509 -nodes -new -sha256 -days 1024 -newkey rsa:2048 -keyout server.test.pem.key -out RootCA.pem -subj "/C=US/CN=Example-Root-CA"
openssl x509 -outform pem -in server.test..pem -out server.test.pem.crt
```
```
$ ls -al
...
server.test.pem
server.test.pem.crt
server.test.pem.key
```
Then I run docker-compose up again and got error
```
localstack | 2020-03-04T14:47:57:ERROR:localstack.services.generic_proxy: Exception running proxy on port 4572: [SSL] PEM lib (_ssl.c:4012) Traceback (most recent call last):
localstack |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 418, in run_cmd
localstack |     self.httpd.socket = ssl.wrap_socket(self.httpd.socket,
localstack |   File "/usr/lib/python3.8/ssl.py", line 1402, in wrap_socket
localstack |     context.load_cert_chain(certfile, keyfile)
localstack | ssl.SSLError: [SSL] PEM lib (_ssl.c:4012)
 Waiting for all LocalStack services to be ready
 Waiting for all LocalStack services to be ready
 Waiting for all LocalStack services to be ready
 Waiting for all LocalStack services to be ready
 Waiting for all LocalStack services to be ready
 Waiting for all LocalStack services to be ready
...
```

This is my docker-compose file
```
version: '3.5'
services:
  myproject_api:
    container_name: myproject_api
    build:
      context: .
      dockerfile: Dockerfile.local
      target: dev
    restart: always
    depends_on:
      - localstack
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/myproject_api/src
      - ./dist:/myproject_api/dist

  localstack:
    image: localstack/localstack:latest
    container_name: myproject_localstack
    ports:
      - "4569:4569"
      - "4582:4582"
      - "4574:4574"
      - "4572:4572"
      - "8055:8080"
    environment:
      - SERVICES=dynamodb,cloudwatch,lambda,s3
      - DEBUG=1
      - USE_SSL=true
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - myproject

networks:
  myproject:
    driver: bridge
```

This is s3 init code
```
private s3 = new AWS.S3({
    endpoint: process.env.NODE_ENV !== 'production' ? `localstack:4572` : undefined,
    s3ForcePathStyle: true
  });
```

Please help!

**Comment by whummer** [comment]
Thanks for reporting @abinhho . If you're using `USE_SSL=1`, then you need to instruct your S3 SDK to ignore validation of SSL certificates (because we're using self-signed certificates for localhost).

Something like this should work, but please refer to the AWS docs for details:
```
const AWS = require('aws-sdk')
var https = require('https');
AWS.config.update({ httpOptions: { agent: new https.Agent({ rejectUnauthorized: false }) } });
```

Please keep us posted how it goes and whether you're able to get it working with SSL validation disabled. Thanks
