### ISSUE TITLE
CloudFormation does not properly handle deleted resources.

### ISSUE THREAD

**Issue by Isnor** [localstack/localstack#2189]
# Type of request: This is a ...

[x] bug report

# Detailed description

CloudFormation does not seem to properly handle resources that were deleted as a result of stack updates or deletions. Though resources _do_ seem to be removed - calling the list API in, say S3 would tell us that, for example, a bucket was no longer present - further interaction with that same resource yields an error until localstack has been restarted. For example:

```
2020-03-23T23:46:11:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "bucket": 409 Conflict: <?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>BucketAlreadyExists</Code>
    <Message>The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again</Message>
    <BucketName>test-bucket</BucketName>
    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Error>
```

In my particular case, with the following template:

```json
{
    "Resources": {
        "bucket": {
            "Type": "AWS::S3::Bucket",
            "Properties": {
                "BucketName": "test-bucket"
            }
        }
    }
}
```

I ran,

```bash
awslocal cloudformation create-stack \
  --stack-name test-stack \
  --template-body file://template.json
```

Which prints the following in the localstack log (using `DEBUG=1`):

```
2020-03-23T23:39:06:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource test-stack/bucket: None
2020-03-23 23:39:06,961:API: 127.0.0.1 - - [23/Mar/2020 23:39:06] "GET /test-bucket?location HTTP/1.1" 404 -
2020-03-23 23:39:06,969:API: 127.0.0.1 - - [23/Mar/2020 23:39:06] "HEAD /test-bucket HTTP/1.1" 404 -
2020-03-23 23:39:06,985:API: 127.0.0.1 - - [23/Mar/2020 23:39:06] "PUT /test-bucket HTTP/1.1" 200 -
2020-03-23T23:39:06:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::S3::Bucket', 'Properties': {'BucketName': 'test-bucket'}}
2020-03-23T23:39:06:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "S3::Bucket" id "bucket"
2020-03-23T23:39:06:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "S3::Bucket" in region us-east-1: create_bucket {'Bucket': 'test-bucket', 'ACL': 'public-read', 'CreateBucketConfiguration': {'LocationConstraint': 'us-east-1'}}
2020-03-23 23:39:33,375:API: 127.0.0.1 - - [23/Mar/2020 23:39:33] "GET / HTTP/1.1" 200 -
```

Then, I delete the stack and recreate it:

```bash
awslocal cloudformation delete-stack --stack-name test-stack
awslocal cloudformation create-stack \
  --stack-name test-stack \
  --template-body file://template.json
```

And see the following log:

```
2020-03-23 23:48:54,596:API: 127.0.0.1 - - [23/Mar/2020 23:48:54] "DELETE /test-bucket-two HTTP/1.1" 204 -
2020-03-23T23:48:54:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "delete" for resource type "S3::Bucket" id "bucket"
2020-03-23T23:48:54:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "S3::Bucket" in region us-east-1: delete_bucket {'Bucket': 'test-bucket-two'}
2020-03-23 23:49:12,610:API: 127.0.0.1 - - [23/Mar/2020 23:49:12] "GET / HTTP/1.1" 200 -
2020-03-23 23:49:42,509:API: 127.0.0.1 - - [23/Mar/2020 23:49:42] "PUT /test-bucket-two HTTP/1.1" 200 -
2020-03-23 23:49:52,105:API: 127.0.0.1 - - [23/Mar/2020 23:49:52] "DELETE /test-bucket-two HTTP/1.1" 204 - [ *Note the delete taking place* ]
2020-03-23 23:49:57,442:API: 127.0.0.1 - - [23/Mar/2020 23:49:57] "GET /test-bucket?location HTTP/1.1" 404 -
2020-03-23 23:49:57,453:API: 127.0.0.1 - - [23/Mar/2020 23:49:57] "HEAD /test-bucket HTTP/1.1" 404 - [ *Note the 404s here - S3 is responding correctly* ]
2020-03-23T23:49:57:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource test-stack/bucket: False
2020-03-23T23:49:57:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "bucket": 409 Conflict: <?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>BucketAlreadyExists</Code>
    <Message>The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again</Message>
    <BucketName>test-bucket</BucketName>
    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Error>
```

CloudFormation seems to be incorrectly keeping its own record of resources

## Expected behavior

Resources created and then deleted by CloudFormation should be able to be created again. My simple test uses an S3 bucket but I assume this carries to all resources.

## Actual behavior

CloudFormation fails when trying to recreate a previously deleted resource

# Steps to reproduce

1. create a CloudFormation stack using the `template.json` pasted above
2. delete the stack
3. Recreate the stack

## Command used to start LocalStack

`DEBUG=1 localstack start`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
#!/bin/bash

echo "creating example stack"
awslocal cloudformation create-stack \
  --stack-name test-stack \
  --template-body file://template.json

sleep 5s

echo "expect: single resource; s3 bucket named 'test-bucket'"
awslocal cloudformation describe-stack-resources --stack-name test-stack

echo "expect: single bucket named 'test-bucket'"
awslocal s3 ls

echo "deleting example stack"
awslocal cloudformation delete-stack --stack-name test-stack
sleep 3s

echo "expect: no stacks"
awslocal cloudformation describe-stacks

echo "expect: 0 buckets: '`awslocal s3 ls`'"

echo "recreating example stack - this fails"
awslocal cloudformation create-stack \
  --stack-name test-stack \
  --template-body file://template.json
```

Produces the output:
```
creating example stack
{
    "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/test-stack/ca37360f-b311-4bc2-b34d-1eec3fb44b8a"
}
expect: single resource; s3 bucket named 'test-bucket'
{
    "StackResources": [
        {
            "StackName": "test-stack",
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/test-stack/ca37360f-b311-4bc2-b34d-1eec3fb44b8a",
            "LogicalResourceId": "bucket",
            "PhysicalResourceId": "test-bucket",
            "ResourceType": "AWS::S3::Bucket",
            "Timestamp": "2010-07-27T22:27:28Z",
            "ResourceStatus": "CREATE_COMPLETE"
        }
    ]
}
expect: single bucket named 'test-bucket'
2020-03-24 00:24:01 test-bucket
deleting example stack
expect: no stacks
{
    "Stacks": []
}
expect: 0 buckets: ''
recreating example stack - this fails

An error occurred (Unknown) when calling the CreateStack operation: Unknown
``` 

And the `localstack` logs:

```
2020-03-24 00:21:04,255:API: 127.0.0.1 - - [24/Mar/2020 00:21:04] "GET / HTTP/1.1" 200 -
2020-03-24 00:24:01,464:API: 127.0.0.1 - - [24/Mar/2020 00:24:01] "GET /test-bucket?location HTTP/1.1" 404 -
2020-03-24 00:24:01,475:API: 127.0.0.1 - - [24/Mar/2020 00:24:01] "HEAD /test-bucket HTTP/1.1" 404 -
2020-03-24 00:24:01,493:API: 127.0.0.1 - - [24/Mar/2020 00:24:01] "PUT /test-bucket HTTP/1.1" 200 -
2020-03-24T00:24:01:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource test-stack/bucket: None
2020-03-24T00:24:01:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::S3::Bucket', 'Properties': {'BucketName': 'test-bucket'}}
2020-03-24T00:24:01:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "S3::Bucket" id "bucket"
2020-03-24T00:24:01:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "S3::Bucket" in region us-east-1: create_bucket {'Bucket': 'test-bucket', 'ACL': 'public-read', 'CreateBucketConfiguration': {'LocationConstraint': 'us-east-1'}}
2020-03-24 00:24:07,967:API: 127.0.0.1 - - [24/Mar/2020 00:24:07] "GET / HTTP/1.1" 200 -
2020-03-24 00:24:08,519:API: 127.0.0.1 - - [24/Mar/2020 00:24:08] "DELETE /test-bucket HTTP/1.1" 204 -
2020-03-24T00:24:08:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "delete" for resource type "S3::Bucket" id "bucket"
2020-03-24T00:24:08:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "S3::Bucket" in region us-east-1: delete_bucket {'Bucket': 'test-bucket'}
2020-03-24 00:24:12,808:API: 127.0.0.1 - - [24/Mar/2020 00:24:12] "GET / HTTP/1.1" 200 -
2020-03-24 00:24:13,344:API: 127.0.0.1 - - [24/Mar/2020 00:24:13] "GET /test-bucket?location HTTP/1.1" 404 -
2020-03-24 00:24:13,353:API: 127.0.0.1 - - [24/Mar/2020 00:24:13] "HEAD /test-bucket HTTP/1.1" 404 -
2020-03-24T00:24:13:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently updating stack resource test-stack/bucket: False
2020-03-24T00:24:13:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "bucket": 409 Conflict: <?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>BucketAlreadyExists</Code>
    <Message>The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again</Message>
    <BucketName>test-bucket</BucketName>
    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Error> Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 178, in parse_and_create_resource
    return _parse_and_create_resource(logical_id, resource_json, resources_map, region_name)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 234, in _parse_and_create_resource
    resource_json_arns_fixed, resources_map, region_name)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/cloudformation/parsing.py", line 339, in parse_and_create_resource
    resource_name, resource_json, region_name
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/models.py", line 1079, in create_from_cloudformation_json
    bucket = s3_backend.create_bucket(resource_name, region_name)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/models.py", line 1169, in create_bucket
    raise BucketAlreadyExists(bucket=bucket_name)
moto.s3.exceptions.BucketAlreadyExists: 409 Conflict: <?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>BucketAlreadyExists</Code>
    <Message>The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again</Message>
    <BucketName>test-bucket</BucketName>
    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Error>

2020-03-24T00:24:13:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response from CloudFormation (409) POST /: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error>\n    <Code>BucketAlreadyExists</Code>\n    <Message>The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again</Message>\n    <BucketName>test-bucket</BucketName>\n    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>\n</Error>'
```

**Comment by whummer** [comment]
Thanks for reporting @Isnor . Can you please do a `docker images | grep localstack` and report which image version you're using? This appears to be fixed in the `latest` version (at least for S3 buckets created/deleted via CloudFormation) - an integration test has been added in #2236 . Please report here if the problem persists, thanks.
