### ISSUE TITLE
CreateElasticsearchDomain request fails

### ISSUE THREAD

**Issue by BloodChiefStromberg** [localstack/localstack#2196]
# Type of request: This is a bug report

# Detailed description
I have some integration tests that use the ElasticSearch service. I am trying to follow the advice from [this comment](https://github.com/localstack/localstack/issues/1881#issuecomment-567495056):

> ...the latest version does not start the Elasticsearch Java process by default. It does start up the Elasticsearch Service (ES) API, which can be used to create a new Elasticsearch domain (i.e., cluster instance) via the CreateElasticsearchDomain API call...You can easily achieve the same behavior by adding a small startup script to your tests that creates an instance via CreateElasticsearchDomain.

Here is my code:
```
    @BeforeClass
    public static void startElasticSearch() {
        final String esEndpoint = Localstack.INSTANCE.getEndpointElasticsearch();
        final AwsClientBuilder.EndpointConfiguration esEndpointConfiguration = new AwsClientBuilder.EndpointConfiguration(esEndpoint, DEFAULT_REGION);
        final AWSElasticsearch esClient = AWSElasticsearchClientBuilder.standard().
                withEndpointConfiguration(esEndpointConfiguration).
                withCredentials(getCredentialsProvider()).build();

        final CreateElasticsearchDomainRequest createElasticsearchDomainRequest = new CreateElasticsearchDomainRequest();
        createElasticsearchDomainRequest.setDomainName("es1");
        esClient.createElasticsearchDomain(createElasticsearchDomainRequest);
    }
```

## Expected behavior
I would expect this to create an ES domain and allow me to connect to it.

## Actual behavior
I recieve this error: 
```
com.amazonaws.SdkClientException: Unable to execute HTTP request: The target server failed to respond

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1163)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1109)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520)
	at com.amazonaws.services.elasticsearch.AWSElasticsearchClient.doInvoke(AWSElasticsearchClient.java:1874)
	at com.amazonaws.services.elasticsearch.AWSElasticsearchClient.invoke(AWSElasticsearchClient.java:1841)
	at com.amazonaws.services.elasticsearch.AWSElasticsearchClient.invoke(AWSElasticsearchClient.java:1830)
	at com.amazonaws.services.elasticsearch.AWSElasticsearchClient.executeCreateElasticsearchDomain(AWSElasticsearchClient.java:507)
	at com.amazonaws.services.elasticsearch.AWSElasticsearchClient.createElasticsearchDomain(AWSElasticsearchClient.java:477)
	at com.zift.digitalasset.service.PlaybookTests.startElasticSearch(PlaybookTests.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.springframework.test.context.junit4.statements.ProfileValueChecker.evaluate(ProfileValueChecker.java:101)
	at org.springframework.test.context.junit4.rules.SpringClassRule$TestContextManagerCacheEvictor.evaluate(SpringClassRule.java:242)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cloud.localstack.LocalstackTestRunner.run(LocalstackTestRunner.java:42)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1285)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101)
	... 32 more

Mar 25, 2020 2:26:21 PM cloud.localstack.docker.Container stop
INFO: Stopped container: 1e9015010200472fdb2a2ab3128a3409737a07b36f31dad1b4ff00eafa391061
Disconnected from the target VM, address: '127.0.0.1:52026', transport: 'socket'

Process finished with exit code 255
```

## Command used to start LocalStack
I'm using `LocalStackTestRunner` which is starting localstack in docker (I have it configured to pull the latest image as well).

Any ideas? Am I trying the right stuff, or is it obvious why this is failing? My goal is that I would have an elastic search started behind localstack's API. 

Thanks for the great product :)

**Comment by whummer** [comment]
Thanks for reporting @BloodChiefStromberg - could this be a timing issue? Can you please check  whether the Elasticsearch process is started eventually, probably a couple of seconds after the `createElasticsearchDomain(..)` call finishes? Also, can you please report the port bindings of the LocalStack Docker container, and post the logs of the container as well. Thanks

**Comment by whummer** [comment]
Any updates on this issue @BloodChiefStromberg . This seems to be working well in our integration tests here: https://github.com/localstack/localstack/blob/master/tests/integration/test_elasticsearch.py#L123-L137 Presumably, this could be an issue related to the port being used to connect. Have you been able to dig a bit more into this? Please let us know if there are any updates or new insights. Thanks

**Comment by whummer** [comment]
Closing this issue due to inactivity - please feel free to reopen if more details are available to consistently reproduce this issue. Thanks!
