### ISSUE TITLE
IoT error creating thing

### ISSUE THREAD

**Issue by jafl** [localstack/localstack#2207]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

I created a subscription, installed my API key in the environment variable, downloaded the latest localstack image, added "iot" to the requested services.

```
$ awslocal iot create-thing --thing-name jolindal-laptop

Connection was closed before we received a valid response from endpoint URL: "http://localhost:4589/things/jolindal-laptop".
```

I verified that port 4589 is listening, via netstat.

## Expected behavior

Successful creation of an IoT thing.

## Actual behavior

Error message given above.

# Steps to reproduce

## Command used to start LocalStack

`docker-compose up -d`

```
version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_asgard
    ports:
      - '4563-4599:4563-4599'
      - '8081:8080'
    environment:
      - SERVICES=s3,sqs,sns,lambda,iot,events,logs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
```

**Comment by jafl** [comment]
```
Error: No such container: localstack_asgard
Creating localstack_asgard ... done
Waiting for all LocalStack services to be ready
2020-03-27 17:41:59,872 INFO Set uid to user 0 succeeded
2020-03-27 17:41:59,877 INFO supervisord started with pid 13
2020-03-27 17:42:00,884 INFO spawned: 'dashboard' with pid 19
2020-03-27 17:42:00,887 INFO spawned: 'infra' with pid 20
(. .venv/bin/activate; bin/localstack web)
2020-03-27 17:42:00,894 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; exec bin/localstack start --host)
Starting local dev environment. CTRL-C to quit.
2020-03-27 17:42:02,434 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for all LocalStack services to be ready
Starting mock Lambda service (http port 4574)...
Starting mock CloudWatch Logs (http port 4586)...
2020-03-27T17:42:09:DEBUG:localstack.utils.common: Starting download from https://github.com/localstack/localstack-artifacts/raw/master/local-certs/server.key to /tmp/localstack/server.test.pem (2703 bytes)
2020-03-27T17:42:09:DEBUG:localstack.utils.common: Writing 3644 bytes (total 3644) to /tmp/localstack/server.test.pem
2020-03-27T17:42:09:DEBUG:localstack.utils.common: Done downloading https://github.com/localstack/localstack-artifacts/raw/master/local-certs/server.key, response code 200, total bytes 3644
2020-03-27T17:42:09:INFO:localstack.multiserver: Starting multi API server process on port 51492
Starting mock S3 (http port 4572)...
Starting mock SNS (http port 4575)...
Starting mock SQS (http port 4576)...
Starting mock Cloudwatch Events (http port 4587)...
17:42:12.209 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.5) ...
17:42:13.304 [elasticmq-akka.actor.default-dispatcher-5] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
Waiting for all LocalStack services to be ready
17:42:15.498 [elasticmq-akka.actor.default-dispatcher-5] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:4561, visible server address http://713e753ec68d:4576
17:42:15.501 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.15.5) started in 4319 ms ===
Ready.
```

**Comment by jafl** [comment]
Doh!  I need to set the environment variable inside the container.  It seems to work now, but I still get an error:

```
Creating localstack_asgard ... done
Waiting for all LocalStack services to be ready
2020-03-28 17:41:45,408 INFO Set uid to user 0 succeeded
2020-03-28 17:41:45,412 INFO supervisord started with pid 14
2020-03-28 17:41:46,415 INFO spawned: 'dashboard' with pid 20
2020-03-28 17:41:46,418 INFO spawned: 'infra' with pid 21
(. .venv/bin/activate; bin/localstack web)
2020-03-28 17:41:46,425 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; exec bin/localstack start --host)
Starting local dev environment. CTRL-C to quit.
2020-03-28 17:41:47,947 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for all LocalStack services to be ready
2020-03-28T17:41:54:DEBUG:localstack.utils.common: Starting download from https://github.com/localstack/localstack-artifacts/raw/master/local-certs/server.key to /tmp/localstack/server.test.pem (2669 bytes)
2020-03-28T17:41:54:DEBUG:localstack.utils.common: Writing 3644 bytes (total 3644) to /tmp/localstack/server.test.pem
2020-03-28T17:41:54:DEBUG:localstack.utils.common: Done downloading https://github.com/localstack/localstack-artifacts/raw/master/local-certs/server.key, response code 200, total bytes 3644
2020-03-28T17:41:57:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
2020-03-28T17:41:57:DEBUG:asyncio: Using selector: EpollSelector
Waiting for all LocalStack services to be ready
Starting mock Lambda service (http port 4574)...
Starting mock CloudWatch Logs (http port 4586)...
Starting mock S3 (http port 4572)...
Starting mock SNS (http port 4575)...
Starting mock SQS (http port 4576)...
Starting mock Cloudwatch Events (http port 4587)...
Starting mock IoT, IoT Analytics (http port 4589)...
Starting mock IoT Data (http port 4543)...
2020-03-28T17:41:58:INFO:localstack.multiserver: Starting multi API server process on port 51492
2020-03-28T17:41:58:INFO:hbmqtt.broker: Listener 'default' bind to 0.0.0.0:4510 (max_connections=-1)
17:41:59.985 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.5) ...
2020-03-28T17:41:59:INFO:hbmqtt.broker: Listener 'default': 1 connections acquired
2020-03-28T17:41:59:INFO:hbmqtt.broker: Connection from 127.0.0.1:60084 on listener 'default'
2020-03-28T17:41:59:ERROR:asyncio: Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Broker.stream_connected() done, defined at /opt/code/localstack/.venv/lib/python3.8/site-packages/hbmqtt/broker.py:342> exception=IncompleteReadError('0 bytes read on a total of 1 expected bytes')>
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hbmqtt/broker.py", line 344, in stream_connected
    yield from self.client_connected(listener_name, StreamReaderAdapter(reader), StreamWriterAdapter(writer))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hbmqtt/broker.py", line 359, in client_connected
    handler, client_session = yield from BrokerProtocolHandler.init_from_connect(reader, writer, self.plugins_manager, loop=self._loop)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hbmqtt/mqtt/protocol/broker_handler.py", line 129, in init_from_connect
    connect = yield from ConnectPacket.from_stream(reader)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hbmqtt/mqtt/packet.py", line 225, in from_stream
    fixed_header = yield from cls.FIXED_HEADER.from_stream(reader)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hbmqtt/mqtt/packet.py", line 104, in from_stream
    byte1 = yield from read_or_raise(reader, 1)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hbmqtt/codecs.py", line 52, in read_or_raise
    data = yield from reader.read(n)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hbmqtt/adapters.py", line 145, in read
    data = yield from self._reader.readexactly(n)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 1 expected bytes
2020-03-28T17:41:59:INFO:hbmqtt.broker: Listener 'default': 2 connections acquired
2020-03-28T17:41:59:INFO:hbmqtt.broker: Connection from 172.19.0.2:35096 on listener 'default'
17:42:01.054 [elasticmq-akka.actor.default-dispatcher-5] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
17:42:03.223 [elasticmq-akka.actor.default-dispatcher-5] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:4561, visible server address http://e3979a987905:4576
17:42:03.226 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.15.5) started in 4262 ms ===
Ready.
```

**Comment by whummer** [comment]
Hi @jafl , thanks for the detailed report. Glad you were able to get it working. I believe the error message you're seeing (`IncompleteReadError`) is more of a warning that should (hopefully) not have functional implications. We'll work on pushing a change that fixes this error message. Closing this issue for now - but please do report here if there are any other issues. Thanks!
