### ISSUE TITLE
Unable to invoke lambda - receiving 500 error

### ISSUE THREAD

**Issue by victoriangtempus** [localstack/localstack#2239]
# Type of request: This is a

[x ] bug report
[ ] feature request

# Detailed description

UPDATE: Now receiving a different error after I was provided an updated docker compose file. Detailed in comments below.

I'm receiving the following error when trying to invoke a simple hello world nodejs lambda in the cli when using localstack via docker. The lambda seems to have been successfully created and localstack seems to be running smoothly as well. I believe I've read through all the threads and tickets around others' lambda invocation errors, and no one seems to have the same problem. I'm wondering if there's a setting I'm missing or need to change in my Docker Compose? I allocated 12 cpu and 16gb memory to Docker and I'm running on a mac OS Mojave 10.14.6

Invocation

```
// Ran this command
awslocal lambda invoke \                                                                                            
--function-name exampleLambda \
testExampleLambda.txt
// Received this error
An error occurred (500) when calling the Invoke operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

List Functions
```
// Ran this command
awslocal lambda list-functions
// Received this response
{
    "Functions": [
        {
            "FunctionName": "exampleLambda",
            "FunctionArn": "arn:aws:lambda:\"us-east-1\":000000000000:function:exampleLambda",
            "Runtime": "nodejs8.10",
            "Role": "arn:aws:iam::000000000000:role/lambda-basic-execution",
            "Handler": "exampleLambda.handler",
            "CodeSize": 315,
            "Description": "",
            "Timeout": 3,
            "LastModified": "2020-03-30T20:14:43.116+0000",
            "CodeSha256": "feR0FxQIszbf/TeHuZE6ziMNZLEgYXPuFf8c5Dk2Qls=",
            "Version": "$LATEST",
            "TracingConfig": {
                "Mode": "PassThrough"
            },
            "RevisionId": "52873143-2e97-4620-b2ec-1b98b06fed7f"
        }
    ]
}
```

Debugging
```
//Ran this command
docker run -it -e DEBUG=1 localstack/localstack
//Received this response
Waiting for all LocalStack services to be ready
2020-03-30 20:16:41,838 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-03-30 20:16:41,843 INFO supervisord started with pid 13
2020-03-30 20:16:42,851 INFO spawned: 'dashboard' with pid 19
2020-03-30 20:16:42,856 INFO spawned: 'infra' with pid 20
(. .venv/bin/activate; bin/localstack web)
2020-03-30 20:16:42,863 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; exec bin/localstack start --host)
2020-03-30 20:16:43,865 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting local dev environment. CTRL-C to quit.
Waiting for all LocalStack services to be ready
2020-03-30T20:16:53:DEBUG:localstack.utils.common: Starting download from https://github.com/localstack/localstack-artifacts/raw/master/local-certs/server.key to /tmp/localstack/server.test.pem (2669 bytes)
2020-03-30T20:16:53:DEBUG:localstack.utils.common: Writing 3644 bytes (total 3644) to /tmp/localstack/server.test.pem
2020-03-30T20:16:53:DEBUG:localstack.utils.common: Done downloading https://github.com/localstack/localstack-artifacts/raw/master/local-certs/server.key, response code 200, total bytes 3644
Starting mock API Gateway (http port 4567)...
2020-03-30T20:16:53:INFO:localstack.multiserver: Starting multi API server process on port 51492
Waiting for all LocalStack services to be ready
Starting mock CloudFormation (http port 4581)...
Starting mock CloudWatch (http port 4582)...
Starting mock DynamoDB (http port 4569)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock EC2 (http port 4597)...
Starting mock ES service (http port 4578)...
Starting mock Firehose service (http port 4573)...
Starting mock IAM (http port 4593)...
Starting mock Kinesis (http port 4568)...
Starting mock KMS (http port 4599)...
Starting mock Lambda service (http port 4574)...
Starting mock CloudWatch Logs (http port 4586)...
Starting mock Redshift (http port 4577)...
Starting mock Route53 (http port 4580)...
Starting mock S3 (http port 4572)...
Starting mock Secrets Manager (http port 4584)...
Starting mock SES (http port 4579)...
Starting mock SNS (http port 4575)...
Starting mock SQS (http port 4576)...
INFO[2020-03-30 20:16:54.619] No file found at path /init/seed.yaml; skipping seeding.
INFO[2020-03-30 20:16:54.620] Data will be stored in /tmp/local-kms
INFO[2020-03-30 20:16:54.620] Local KMS started on 0.0.0.0:4555
Starting mock SSM (http port 4583)...
Starting mock STS (http port 4592)...
Starting mock Cloudwatch Events (http port 4587)...
Starting mock StepFunctions (http port 4585)...
Initializing DynamoDB Local with the following configuration:
Port:	4564
InMemory:	true
DbPath:	null
SharedDb:	true
shouldDelayTransientStatuses:	false
CorsParams:	*
Listening at http://:::4565
Step Functions Local
Version: 1.5.0
Build: 2020-02-15
2020-03-30 20:16:55.198: Configure [Account] to [000000000000]
2020-03-30 20:16:55.201: Configure [Region] to [us-east-1]
2020-03-30 20:16:55.201: Configure [Lambda Endpoint] to [http://e74fbb32d01a:4574]
2020-03-30 20:16:55.202: Configure [DynamoDB Endpoint] to [http://e74fbb32d01a:4569]
2020-03-30 20:16:55.206: Configure [SQS Endpoint] to [http://e74fbb32d01a:4576]
2020-03-30 20:16:55.207: Configure [SNS Endpoint] to [http://e74fbb32d01a:4575]
2020-03-30 20:16:55.208: Configure [Step Functions Endpoint] to [http://e74fbb32d01a:4585]
2020-03-30 20:16:55.230: Loaded credentials from environment
2020-03-30 20:16:55.232: Starting server on port 8083 with account 000000000000, region us-east-1
2020-03-30 20:16:54,350:API:  * Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
2020-03-30 20:16:54,350:API:  * Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
2020-03-30 20:16:54,350:API:  * Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
2020-03-30 20:16:54,394:API:  * Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
2020-03-30 20:16:54,394:API:  * Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
2020-03-30 20:16:54,394:API:  * Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
2020-03-30 20:16:54,413:API:  * Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
2020-03-30 20:16:54,413:API:  * Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
2020-03-30 20:16:54,413:API:  * Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
20:16:55.701 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.5) ...
Mar 30, 2020 8:16:56 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Mar 30, 2020 8:16:56 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
20:16:56.647 [elasticmq-akka.actor.default-dispatcher-5] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
Mar 30, 2020 8:16:56 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Mar 30, 2020 8:16:56 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Mar 30, 2020 8:16:56 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Mar 30, 2020 8:16:56 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Mar 30, 2020 8:16:56 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Mar 30, 2020 8:16:56 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Mar 30, 2020 8:16:57 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
20:16:58.293 [elasticmq-akka.actor.default-dispatcher-5] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:4561, visible server address http://e74fbb32d01a:4576
20:16:58.294 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.15.5) started in 3476 ms ===
Ready.
```

Docker Compose
```
version: '2.1'
services:
  localstack:
    privileged: true
    container_name: localstack-main
    image: localstack/localstack:0.10.5
    ports:
      - "4567-4599:4567-4599"
      - 8080:8080
    environment:
      - SERVICES=lambda,sns,stepfunctions,cloudwatch,iam
      - LAMBDA_REMOTE_DOCKER=false
      - DATA_DIR=./data
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG="1"
      - DEFAULT_REGION="us-east-1"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"`
```

Example Lambda that was zipped up
```
exports.handler = async (event) => {
    const response = {
        statusCode: 200,
        body: JSON.stringify('Hello from Lambda!'),
    };
    return response;
}
```

How I'm starting localstack
```
env TMPDIR=/private$TMPDIR docker-compose up -d
```
...

## Expected behavior
Able to invoke the lambda. I was able to do so when I connect directly to my personal AWS account via the CLI, but I'm unable to do it via Localstack.
...

## Actual behavior
```
// Ran this command
awslocal lambda invoke \                                                                                            
--function-name exampleLambda \
testExampleLambda.txt
// Received this error
An error occurred (500) when calling the Invoke operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```
...

# Steps to reproduce
Listed above
## Command used to start LocalStack
```
env TMPDIR=/private$TMPDIR docker-compose up -d
```
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
listed above
...

**Comment by rayjlinden** [comment]
I am seeing the same problem.  In fact, my simple test case was working just a few days ago so I think this may be a new bug.  The error I'm seeing is a little different (but that might be because my lamba is written in GO and using the docker launcher...

I get this error:
```
An error occurred (500) when calling the Invoke operation (reached max retries: 2): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

Also doing docker logs on loclstack I see this stack trace:
```
2020-04-04T07:22:16:ERROR:lambda_api: Exception on /2015-03-31/functions/webhook-lambda/invocations [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1105, in invoke_function
    data = to_str(data)
  File "/opt/code/localstack/localstack/utils/common.py", line 743, in to_str
    return obj.decode(encoding, errors) if isinstance(obj, six.binary_type) else obj
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 1: invalid start byte
2020-04-04T07:22:17:ERROR:lambda_api: Exception on /2015-03-31/functions/webhook-lambda/invocations [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1105, in invoke_function
    data = to_str(data)
  File "/opt/code/localstack/localstack/utils/common.py", line 743, in to_str
    return obj.decode(encoding, errors) if isinstance(obj, six.binary_type) else obj
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 1: invalid start byte
2020-04-04T07:22:18:ERROR:lambda_api: Exception on /2015-03-31/functions/webhook-lambda/invocations [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1105, in invoke_function
    data = to_str(data)
  File "/opt/code/localstack/localstack/utils/common.py", line 743, in to_str
    return obj.decode(encoding, errors) if isinstance(obj, six.binary_type) else obj
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 1: invalid start byte
```

**Comment by rayjlinden** [comment]
Ah! In my case - I discovered it was because I updated to awscli v2.  One of it's breaking changes is it will send binary data as base 64 by default.

I added this to the command line: --cli-binary-format raw-in-base64-out

and things are working again.

So there is certainly a bug in there for how localstack handles the invoke function when called by awscli v2.

**Comment by victoriangtempus** [comment]
Thanks for the advice! I have awscli version 1.17.10, but it's good to know once I upgrade!

**Comment by victoriangtempus** [comment]
Was provided the following updated docker-compose from someone on Localstack, and now I'm receiving the following errors instead:

Docker compose
`version: '2.1'
services:
  localstack:
    privileged: true
    container_name: localstack-main
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - 8080:8080
    environment:
      - SERVICES=lambda,sns,stepfunctions,cloudwatch,iam
      - LAMBDA_REMOTE_DOCKER=false
      - DATA_DIR=./data
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - DEFAULT_REGION=us-east-1 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"`

Error
`An error occurred (InternalFailure) when calling the Invoke operation (reached max retries: 4): Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:exampleLambda: Lambda process returned error status code: 1. Result: {"errorType":"Error","errorMessage":"Cannot find module '/var/task/exampleLambda'","stackTrace":["Function.Module._load (module.js:474:25)","Module.require (module.js:596:17)","require (internal/module.js:11:18)"]}. Output:
START RequestId: e6d966c4-058f-1434-9b53-0dedd58132b2 Version: $LATEST
Unable to import module 'exampleLambda': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
END RequestId: e6d966c4-058f-1434-9b53-0dedd58132b2
REPORT RequestId: e6d966c4-058f-1434-9b53-0dedd58132b2	Init Duration: 3000.00 ms	Duration: 8.16 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 40 MB	 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 457, in run_lambda
    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 132, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 119, in do_execute
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 107, in do_execute
    result = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 256, in _execute
    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 169, in run_lambda_executor
    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
Exception: Lambda process returned error status code: 1. Result: {"errorType":"Error","errorMessage":"Cannot find module '/var/task/exampleLambda'","stackTrace":["Function.Module._load (module.js:474:25)","Module.require (module.js:596:17)","require (internal/module.js:11:18)"]}. Output:
START RequestId: e6d966c4-058f-1434-9b53-0dedd58132b2 Version: $LATEST
Unable to import module 'exampleLambda': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
END RequestId: e6d966c4-058f-1434-9b53-0dedd58132b2
REPORT RequestId: e6d966c4-058f-1434-9b53-0dedd58132b2	Init Duration: 3000.00 ms	Duration: 8.16 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 40 MB`

**Comment by whummer** [comment]
Thanks for the detailed report @victoriangtempus . The sample docker-compose.yml has been updated and checks have been added in #2239 , which should hopefully prevent this configuration issue from happening in the future. Closing this issue - please report here if the problem persists. Thanks

**Comment by joshluisaac** [comment]
Upgraded AWS CLI to v2 and started getting this error
```
2020-09-07T15:16:59:ERROR:lambda_api: Exception on /2015-03-31/functions/opb-redisloader-LFunction/invocations [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1147, in invoke_function
    data = to_str(data)
  File "/opt/code/localstack/localstack/utils/common.py", line 764, in to_str
    return obj.decode(encoding, errors) if isinstance(obj, six.binary_type) else obj
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9d in position 0: invalid start byte
```
