### ISSUE TITLE
Unable to uploade image to S3 - 500 error

### ISSUE THREAD

**Issue by marselmustafin** [localstack/localstack#2254]
# Type of request: This is a ...
[ X] bug report
[ ] feature request

# Detailed description
I'm using Ruby on Rails with Carrierwave library and trying to set up file uploading to Localstack.
My RoR project already works on production and there're lots of uploadings happen with real S3.
I've specified all required parameters required by Carrierwave (aws_acces_key, region, endpoint, bucket, etc.) and tried to make first file upload using small .jpg image.

## Expected behavior
File uploaded successfully to S3 localstack bucket.

## Actual behavior
Server error, here're some logs:

```
2020-04-05 12:27:29,868:API: 127.0.0.1 - - [05/Apr/2020 12:27:29] "PUT /my-directory/image/f69fbe12-1614-4963-94fb-41abf3a32209.1586089649.jpg HTTP/1.1" 500 -
2020-04-05 12:27:29,868:API: 127.0.0.1 - - [05/Apr/2020 12:27:29] "PUT /my-directory/image/f69fbe12-1614-4963-94fb-41abf3a32209.1586089649.jpg HTTP/1.1" 500 -
2020-04-05 12:27:29,868:API: 127.0.0.1 - - [05/Apr/2020 12:27:29] "PUT /my-directory/image/f69fbe12-1614-4963-94fb-41abf3a32209.1586089649.jpg HTTP/1.1" 500 -
2020-04-05T12:27:29:WARNING:localstack.services.generic_proxy: Expected Content-Length header not found in POST/PUT request
2020-04-05 12:27:29,907:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 124, in read_chunk_len
    _len = int(line.strip(), 16)
ValueError: invalid literal for int() with base 16: '5139ÿØÿà\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00ÿþ\x00;CREATOR: gd-jpeg v1.0 (using IJG JPEG v80), quality = 75'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 135, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 146, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 897, in key_or_control_response
    response = self._key_response(request, full_url, headers)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1033, in _key_response
    body = request.data
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/utils.py", line 90, in __get__
    value = self.func(obj)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/wrappers/base_request.py", line 426, in data
    return self.get_data(parse_form_data=True)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/wrappers/base_request.py", line 457, in get_data
    rv = self.stream.read()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 137, in readinto
    self._len = self.read_chunk_len()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 126, in read_chunk_len
    raise IOError("Invalid chunk header")
OSError: Invalid chunk header
```

Some info about the request:

```
 :chunk_size          => 1048576
  :ciphers             => "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS"
  :connect_timeout     => 60
  :debug_request       => true
  :debug_response      => true
  :expects             => 200
  :headers             => {
    "Authorization"                => "REDACTED"
    "Content-Type"                 => "image/jpeg"
    "Host"                         => "localhost"
    "User-Agent"                   => "fog-core/2.1.2"
    "x-amz-acl"                    => "public-read"
    "x-amz-content-sha256"         => "STREAMING-AWS4-HMAC-SHA256-PAYLOAD"
    "x-amz-date"                   => "20200405T125203Z"
    "x-amz-decoded-content-length" => 20704
  }
  :host                => "localhost"
  :hostname            => "localhost"
  :idempotent          => true
  :instrumentor        => Excon::StandardInstrumentor
  :instrumentor_name   => "excon"
  :method              => "PUT"
  :middlewares         => [
    Excon::Middleware::ResponseParser
    Excon::Middleware::Expects
    Excon::Middleware::Idempotent
    Excon::Middleware::Instrumentor
    Excon::Middleware::Mock
  ]
  :mock                => false
  :nonblock            => true
  :omit_default_port   => false
  :path                => "/topcontrol-dev0/image/84b44b87-366b-4e6d-8442-801d9f8fa302.1586091123.jpg"
  :persistent          => false
  :port                => 4572
  :query               => nil
  :read_timeout        => 60
```

I see that localstack expects `Content-Length`, but fog client (which CarrierWave uses) sends `x-amz-decoded-content-length` header instead. Is this can be the cause?

# Steps to reproduce
Try to upload any image with Carrierwave to Localstack S3

## Command used to start LocalStack
`DEBUG=1 PORT_WEB_UI=8090 SERVICES=s3 localstack start`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-174) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @marselmustafin - looks like this could be a HTTP/1.1 versus HTTP/2 issue. We have recently added significant improvements to the proxy/API layer - can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? Please let us know if the problem persists. Thanks

**Comment by pinzon** [comment]
After recreating this issue, I found out that the only extra parameter to set up correctly the ruby-aws-sdk is just the force_path_style.
I setted up the library carrierwave-aws like this:
```
 config.storage    = :aws
 config.aws_bucket = 'test'
 config.aws_acl    = 'public-read'
 config.aws_authenticated_url_expiration = 60 * 60 * 24 * 7
config.aws_credentials = {
    access_key_id:     'test',
    secret_access_key: 'test',
    region:            'us-east-1',
    endpoint:          'http://localhost:4566',
    force_path_style: true 
  }
```

I took this [example](https://github.com/bodrovis/TutsPlusSource/tree/master/Uploading_with_Carrierwave) and used carrierwave-aws instead of fog-aws.
[example.zip](https://github.com/localstack/localstack/files/5661878/example.zip)
