### ISSUE TITLE
CloudFormation Extended called lower function with SmoothStreaming boolean type?

### ISSUE THREAD

**Issue by msiu-takeda** [localstack/localstack#2277]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

An error occurred inside cloudformtion_extended.py.enc.
```
AttributeError: 'bool' object has no attribute 'lower'
  in /opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py
```

I have written a json file for cloudformation and tried to run "aws cloudformation create-stack" with the template file.
> Resources.CloudFront.Properties.DistributionConfig.DefaultCacheBehavior.SmoothStreaming
```
"DistributionConfig": {
  "DefaultCacheBehavior": {
    "SmoothStreaming": false,
```

It looks like **cloudformation_extended** adapted a lower function to "SmoothStreaming(boolean)" .

AWS says that it's boolean.
> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-defaultcachebehavior.html#cfn-cloudfront-distribution-defaultcachebehavior-smoothstreaming
> type: Boolean

Could you check this situation?
Thank you.

Full traceback is here.
```
localstack_1  | 2020-04-10 15:14:21,683:API: Error on request:
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
localstack_1  |     execute(self.server.app)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
localstack_1  |     application_iter = app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 135, in __call__
localstack_1  |     return backend_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
localstack_1  |     return self.wsgi_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
localstack_1  |     response = self.handle_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_1  |     raise value
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
localstack_1  |     response = self.full_dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
localstack_1  |     rv = self.handle_user_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_1  |     raise value
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
localstack_1  |     rv = self.dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
localstack_1  |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 146, in __call__
localstack_1  |     result = self.callback(request, request.url, {})
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 197, in dispatch
localstack_1  |     return cls()._dispatch(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 295, in _dispatch
localstack_1  |     return self.call_action()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 380, in call_action
localstack_1  |     response = method()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/responses.py", line 64, in create_stack
localstack_1  |     stack = self.cloudformation_backend.create_stack(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/models.py", line 564, in create_stack
localstack_1  |     new_stack.initialize_resources()
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 748, in initialize_resources
localstack_1  |     self.resource_map.create()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 561, in create
localstack_1  |     if isinstance(self[resource], ec2_models.TaggedEC2Resource):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 472, in __getitem__
localstack_1  |     new_resource = parse_and_create_resource(
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 185, in parse_and_create_resource
localstack_1  |     return _parse_and_create_resource(
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 213, in _parse_and_create_resource
localstack_1  |     resource_tuple = parsing.parse_resource(logical_id, resource_json, resources_map)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 315, in parse_resource
localstack_1  |     resource_json = clean_json(resource_json, resources_map)
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 169, in clean_json
localstack_1  |     result = clean_json_orig(resource_json, resources_map)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 260, in clean_json
localstack_1  |     cleaned_val = clean_json(value, resources_map)
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 169, in clean_json
localstack_1  |     result = clean_json_orig(resource_json, resources_map)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 260, in clean_json
localstack_1  |     cleaned_val = clean_json(value, resources_map)
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 169, in clean_json
localstack_1  |     result = clean_json_orig(resource_json, resources_map)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 260, in clean_json
localstack_1  |     cleaned_val = clean_json(value, resources_map)
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 169, in clean_json
localstack_1  |     result = clean_json_orig(resource_json, resources_map)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 170, in clean_json
localstack_1  |     resource = resources_map.get(resource_json["Fn::GetAtt"][0])
localstack_1  |   File "/usr/lib/python3.8/_collections_abc.py", line 660, in get
localstack_1  |     return self[key]
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 472, in __getitem__
localstack_1  |     new_resource = parse_and_create_resource(
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 185, in parse_and_create_resource
localstack_1  |     return _parse_and_create_resource(
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 294, in _parse_and_create_resource
localstack_1  |     result = deploy_func(logical_id, resource_map_new, stack_name=stack_name)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 961, in deploy_resource
localstack_1  |     return execute_resource_action(resource_id, resources, stack_name, ACTION_CREATE)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 987, in execute_resource_action
localstack_1  |     result = configure_resource_via_sdk(resource_id, resources, resource_type, func, stack_name)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1015, in configure_resource_via_sdk
localstack_1  |     prop_value = prop_key(resource_props, stack_name=stack_name, resources=resources)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py", line 87, in lambda_get_distribution_config
localstack_1  |
localstack_1  | AttributeError: 'bool' object has no attribute 'lower'
```

## Expected behavior

do not call lower.

## Actual behavior

AttributeError: 'bool' object has no attribute 'lower'

# Steps to reproduce

sample.json
```
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "Cloud Front definition for sample",
    "Parameters": {
        "SystemName": {
            "Type": "String",
            "Description": "System Name"
        },
        "Environment": {
            "Type": "String",
            "Description": "Environment Name"
        },
        "BucketName": {
            "Type": "String",
            "Description": "Bucket name"
        },
        "HostedZoneId": {
            "Type": "String",
            "Description": "Route53 Hosted Zone Id"
        },
        "Cname": {
            "Type": "String",
            "Description": "Access Domain Name"
        },
        "Contents": {
            "Type": "String",
            "Description": "Origin Path"
        },
        "LogBucketName": {
            "Type": "String",
            "Description": "Log Bucket Name"
        },
        "OriginAccessIdentity": {
            "Type": "String",
            "Description": "Access Identity"
        },
        "AcmArn": {
            "Type": "String",
            "Description": "Amazon Certificate Manager ARN"
        }
    },
    "Resources": {
        "Route53": {
            "Type": "AWS::Route53::RecordSet",
            "DependsOn": "CloudFront",
            "Properties": {
                "Name": { "Ref": "Cname" },
                "Type": "A",
                "HostedZoneId": { "Ref": "HostedZoneId" },
                "AliasTarget": {
                    "DNSName": { "Fn::GetAtt": [ "CloudFront", "DomainName" ] },
                    "HostedZoneId": "SomeZoneId"
                }
            }
        },
        "CloudFront": {
            "Type": "AWS::CloudFront::Distribution",
            "Properties": {
                "DistributionConfig": {
                    "Aliases": [
                        { "Ref": "Cname" }
                    ],
                    "Origins": [ {
                        "DomainName": { "Fn::Join": [ ".", [
                            { "Ref": "BucketName" },
                            "s3",
                            "amazonaws",
                            "com"
                        ] ] },
                        "Id": { "Fn::Join": [ "-", [
                            { "Ref": "SystemName" },
                            { "Ref": "Environment" },
                            "video"
                        ] ] },
                        "OriginPath": { "Fn::Join": [ "", [
                            "/",
                            { "Ref": "Contents" }
                        ] ] },
                        "S3OriginConfig": {
                            "OriginAccessIdentity": { "Fn::Join": [ "/", [
                                "origin-access-identity",
                                "cloudfront",
                                { "Ref": "OriginAccessIdentity" }
                            ] ] }
                        }
                    } ],
                    "Enabled": true,
                    "Comment": "Video CloudFront",
                    "DefaultCacheBehavior": {
                        "TargetOriginId": { "Fn::Join": [ "-", [
                            { "Ref": "SystemName" },
                            { "Ref": "Environment" },
                            "video"
                        ] ] },
                        "AllowedMethods": [ "GET", "HEAD" ],
                        "SmoothStreaming": false,
                        "DefaultTTL": 31536000,
                        "MinTTL": 31536000,
                        "MaxTTL": 31536000,
                        "ForwardedValues": {
                            "QueryString": false,
                            "Cookies": {
                                "Forward": "none"
                            },
                            "Headers": [
                                "Access-Control-Request-Headers",
                                "Access-Control-Request-Method",
                                "Origin"
                            ]
                        },
                        "ViewerProtocolPolicy": "redirect-to-https"
                    },
                    "ViewerCertificate": {
                        "AcmCertificateArn": { "Ref": "AcmArn" },
                        "SslSupportMethod": "sni-only",
                        "MinimumProtocolVersion": "TLSv1.1_2016"
                    },
                    "Logging": {
                        "Bucket": { "Fn::Join": [ "", [
                            { "Ref": "LogBucketName" },
                            ".s3.amazonaws.com"
                        ] ] },
                        "Prefix": "video/"
                    }
                }
            }
        }
    },
    "Outputs": {
        "ID": {
            "Value": { "Ref": "CloudFront" }
        },
        "DomainName": {
            "Value": { "Fn::GetAtt": [ "CloudFront", "DomainName" ] }
        }
    }
}
```

## Command used to start LocalStack

> TMPDIR=/private$TMPDIR docker-compose up

```
version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "443:443"
      - "4510-4520:4510-4520"
      - "4567-4615:4567-4615"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=secret
      - DEFAULT_REGION=ap-northeast-1
      - SERVICES=rds,s3,apigateway,lambda,dynamodb,kinesis,ses,cloudformation,cloudwatch,cognito,kms,cloudfront,route53,stepfunctions,sns,logs,events
      - DEBUG=1
      - LANG=ja_JP.UTF-8
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

> aws --endpoint-url=http://localhost:4581 --profile localstack cloudformation create-stack --stack-name test-cloudfront-video --template-body file://./sample.json --parameters ParameterKey=SystemName,ParameterValue="video" ParameterKey=Environment,ParameterValue="test" ParameterKey=BucketName,ParameterValue="my-test-bucket" ParameterKey=HostedZoneId,ParameterValue="SomeZoneId" ParameterKey=Cname,ParameterValue="video.test.mydomain.net" ParameterKey=Contents,ParameterValue="contents" ParameterKey=LogBucketName,ParameterValue="video-test-log" ParameterKey=OriginAccessIdentity,ParameterValue="SomeIdentity" ParameterKey=AcmArn,ParameterValue="arn:aws:acm:us-east-1:0000000000:certificate/00000000-0000-0000-0000-000000000000"

**Comment by whummer** [comment]
Thanks a lot for the detailed report @ msiu-takeda . This should be fixed in the latest version - can you please do a `docker pull localstack/localstack` and give it another try? Please report here if the problem persists. Thanks!
