### ISSUE TITLE
sqs does not work with fifo queues

### ISSUE THREAD

**Issue by cbarbara-okta** [localstack/localstack#232]
When using fifo queues amazon requires them to end with `.fifo` but it looks like that suffix causes problems when making a `ReceiveMessageRequest` against that queue.

Run the following sample code
```
        String queueName = "localstack.fifo";
        CreateQueueRequest createQueueRequest = new CreateQueueRequest();
        createQueueRequest.setQueueName(queueName);
        CreateQueueResult newQueue = sqsClient.createQueue(createQueueRequest);
        String queueUrl = newQueue.getQueueUrl();
        System.out.println("Just created the queueName=" + queueName + " queueUrl=" + queueUrl);

        ReceiveMessageRequest request = new ReceiveMessageRequest(queueUrl);
        request.setWaitTimeSeconds(20);
        request.setMaxNumberOfMessages(1);
        request.setMessageAttributeNames(Lists.newArrayList("All"));
        request.setAttributeNames(Lists.newArrayList("All"));

        ReceiveMessageResult result = sqsClient.receiveMessage(request);
```
And the `receiveMessage` will result in a 404 error on the localstack server.

```
awsstack_1  | 127.0.0.1 - - [04/Aug/2017 21:41:16] "POST / HTTP/1.1" 200 -
awsstack_1  | 127.0.0.1 - - [04/Aug/2017 21:41:18] "POST /123456789012/localstack.fifo HTTP/1.1" 404 -


INFO  [2017-08-04 21:40:51,961] com.amazonaws.http.DefaultErrorResponseHandler: Unable to parse HTTP response (Invocation Id:08fd5a7e-3970-2fb9-c41a-d7837d25a3f1) content to XML document '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
' 
! org.xml.sax.SAXParseException: White spaces are required between publicId and systemId.
! at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257) ~[na:1.7.0_80]
! at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347) ~[na:1.7.0_80]
! at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121) ~[na:1.7.0_80]
! at com.amazonaws.util.XpathUtils.documentFrom(XpathUtils.java:133) ~[aws-java-sdk-core-1.11.58.jar:na]
! at com.amazonaws.util.XpathUtils.documentFrom(XpathUtils.java:140) ~[aws-java-sdk-core-1.11.58.jar:na]
! at com.amazonaws.http.DefaultErrorResponseHandler.parseXml(DefaultErrorResponseHandler.java:124) [aws-java-sdk-core-1.11.58.jar:na]
! at com.amazonaws.http.DefaultErrorResponseHandler.documentFromContent(DefaultErrorResponseHandler.java:105) [aws-java-sdk-core-1.11.58.jar:na]
! at com.amazonaws.http.DefaultErrorResponseHandler.createAse(DefaultErrorResponseHandler.java:84) [aws-java-sdk-core-1.11.58.jar:na]
! at com.amazonaws.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:71) [aws-java-sdk-core-1.11.58.jar:na]
! at com.amazonaws.http.DefaultErrorResponseHandler.handle(DefaultErrorResponseHandler.java:47) [aws-java-sdk-core-1.11.58.jar:na]
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1511) [aws-java-sdk-core-1.11.58.jar:na]
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1183) [aws-java-sdk-core-1.11.58.jar:na]
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:964) [aws-java-sdk-core-1.11.58.jar:na]
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:676) [aws-java-sdk-core-1.11.58.jar:na]
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:650) [aws-java-sdk-core-1.11.58.jar:na]
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:633) [aws-java-sdk-core-1.11.58.jar:na]
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:601) [aws-java-sdk-core-1.11.58.jar:na]
! at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:583) [aws-java-sdk-core-1.11.58.jar:na]
! at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:447) [aws-java-sdk-core-1.11.58.jar:na]
! at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1555) [aws-java-sdk-sqs-1.11.58.jar:na]
! at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1531) [aws-java-sdk-sqs-1.11.58.jar:na]
! at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:1228) [aws-java-sdk-sqs-1.11.58.jar:na]
```

If you change `queueName` and remove the `.fifo` suffix things work fine.

**Comment by whummer** [comment]
Thanks for reporting. This should be fixed in https://github.com/localstack/localstack/pull/234 . Can you please pull the latest version of the Docker image and give it a try. Thanks

**Comment by cbarbara-okta** [comment]
👍  - latest master works for me. thanks for the quick fix.
