### ISSUE TITLE
Pro versions ports do not show as open (ECS, ECR)

### ISSUE THREAD

**Issue by joseflexadaitan** [localstack/localstack#2325]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Looking at https://github.com/localstack/localstack/blob/master/Dockerfile#L39 the ports for Pro services are not exposed. The following docker-compose.yml was used:
```
version: '3.5'
services:
  localstack:
    image: localstack/localstack:0.11.0
    container_name: localstack
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SERVICES=cloudwatch,dynamodb,ecs,ecr,edge,iam,s3,sqs,sns,sts
      - USE_SSL=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=127.0.0.1
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEBUG=${DEBUG}
    ports:
      - "4566:4566"
      - "4567:4567"
      - "4601:4601"
      - "4610:4610"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      localstack:
        ipv4_address: 127.0.0.1
```

## Expected behavior

ECR, ECS default ports are exposed and accepting connections 

## Actual behavior

Ports are not accepting connections althought they are open on docker ps 
```
$ docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                                                                                     NAMES
f1c5c8d11496        localstack/localstack:0.11.0   "docker-entrypoint.sh"   9 seconds ago       Up 6 seconds        0.0.0.0:4566-4567->4566-4567/tcp, 0.0.0.0:4601->4601/tcp, 0.0.0.0:4610->4610/tcp, 0.0.0.0:8080->8080/tcp, 4568-4597/tcp   localstack

```

# Steps to reproduce

* Run docker-compose
* Try to create an ECR with awslocal.

## Command used to start LocalStack

`DEBUG=1 LOCALSTACK_API_KEY=3q4zKFlID8 docker-compose up
`
## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
$ awslocal ecr create-repository --endpoint-url=http://127.0.0.1:4566 --repository-name mock-repo

An error occurred (502) when calling the CreateRepository operation (reached max retries: 4): Bad Gateway
```

**Comment by whummer** [comment]
Thanks for reporting this issue @joseflexadaitan . I just gave it a try with the docker-compose config you posed, and haven't been able to reproduce this issue. Here is the output of the `awslocal` command I'm seeing:
```
$ awslocal ecr create-repository --endpoint-url=http://127.0.0.1:4566 --repository-name mock-repo
{
    "repository": {
        "repositoryArn": "arn:aws:ecr:eu-central-1:000000000000:repository/mock-repo",
        "registryId": "be8db0d7",
        "repositoryName": "mock-repo",
        "repositoryUri": "db087d4c7e58:4510/mock-repo"
    }
}
```
Can you please enable `DEBUG=1` and post the log output from the container? Also, we've just sent you an invite to join our Slack channel - might be easier to debug and discuss the details there. Thanks!

**Comment by joseflexadaitan** [comment]
@whummer thanks for the invite. Just joined. Bellow are the logs. An important update is that now I am able to create the repository using awslocal, but the error bellow occurs when I try to create a terraform ecr resource like the following
```
resource "aws_ecr_repository" "mock_ecr_repository" {
  name                 = var.ecr_repository_name
}
```

```
Starting localstack     ... done
Starting stack_consul_1 ... done
Attaching to stack_consul_1, localstack
localstack    | Waiting for all LocalStack services to be ready
localstack    | 2020-04-22 22:50:45,094 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack    | 2020-04-22 22:50:45,096 INFO supervisord started with pid 14
localstack    | 2020-04-22 22:50:46,099 INFO spawned: 'dashboard' with pid 20
localstack    | 2020-04-22 22:50:46,100 INFO spawned: 'infra' with pid 21
localstack    | 2020-04-22 22:50:46,106 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack    | (. .venv/bin/activate; bin/localstack web)
localstack    | (. .venv/bin/activate; exec bin/localstack start --host)
localstack    | 2020-04-22 22:50:47,107 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack    | Starting local dev environment. CTRL-C to quit.
localstack    | Waiting for all LocalStack services to be ready
localstack    | 2020-04-22T22:50:55:INFO:localstack.utils.common: Unable to store key/cert files for custom SSL certificate: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem.key'
localstack    | Waiting for all LocalStack services to be ready
localstack    | 2020-04-22T22:50:59:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
localstack    | 2020-04-22T22:50:59:DEBUG:asyncio: Using selector: EpollSelector
localstack    | Starting edge router (http port 4566)...
localstack    | Starting edge router (https port 443)...
localstack    | Starting mock CloudWatch (http port 4582)...
localstack    | Starting mock DynamoDB (http port 4569)...
localstack    | Starting mock IAM (http port 4593)...
localstack    | Starting mock S3 (http port 4572)...
localstack    | Starting mock SNS (http port 4575)...
localstack    | Starting mock SQS (http port 4576)...
localstack    | Starting mock STS service (http port 4592)...
localstack    | Starting mock ECR (http port 4610)...
localstack    | Starting mock ECS (http port 4601)...
localstack    | Initializing DynamoDB Local with the following configuration:
localstack    | Port:	4563
localstack    | InMemory:	true
localstack    | DbPath:	null
localstack    | SharedDb:	true
localstack    | shouldDelayTransientStatuses:	false
localstack    | CorsParams:	*
localstack    | 
localstack    | 2020-04-22T22:51:01:DEBUG:bootstrap.py: Plugin loading took 6.304811954498291 sec
localstack    | 2020-04-22T22:51:01:INFO:localstack.multiserver: Starting multi API server process on port 51492
localstack    | 2020-04-22 22:51:01,612:API:  * Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
localstack    | 2020-04-22 22:51:01,612:API:  * Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
localstack    | 2020-04-22 22:51:01,612:API:  * Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
localstack    | 2020-04-22 22:51:01,664:API:  * Running on http://0.0.0.0:4556/ (Press CTRL+C to quit)
localstack    | 2020-04-22 22:51:01,664:API:  * Running on http://0.0.0.0:4556/ (Press CTRL+C to quit)
localstack    | 2020-04-22 22:51:01,664:API:  * Running on http://0.0.0.0:4556/ (Press CTRL+C to quit)
localstack    | 2020-04-22 22:51:01,673:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
localstack    | 2020-04-22 22:51:01,673:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
localstack    | 2020-04-22 22:51:01,673:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
localstack    | 2020-04-22 22:51:01,680:API:  * Running on http://0.0.0.0:4561/ (Press CTRL+C to quit)
localstack    | 2020-04-22 22:51:01,680:API:  * Running on http://0.0.0.0:4561/ (Press CTRL+C to quit)
localstack    | 2020-04-22 22:51:01,680:API:  * Running on http://0.0.0.0:4561/ (Press CTRL+C to quit)
localstack    | 22:51:02.360 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.5) ...
localstack    | 22:51:02.789 [elasticmq-akka.actor.default-dispatcher-5] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
localstack    | 22:51:03.590 [elasticmq-akka.actor.default-dispatcher-6] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:4560, visible server address http://f806e52e55c2:4576
localstack    | 22:51:03.591 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.15.5) started in 1759 ms ===
localstack    | 2020-04-22T22:51:05:INFO:localstack_ext.services.ecr.ecr_listener: Starting ECR Docker registry on port 4510
localstack    | Waiting for all LocalStack services to be ready
localstack    | Ready.
localstack    | 2020-04-22T22:51:07:DEBUG:localstack.utils.common: Starting download from https://github.com/localstack/localstack-artifacts/raw/master/docker-registry/registry.alpine to /tmp/localstack/docker.registry.bin (20079264 bytes)
localstack    | 2020-04-22T22:51:07:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 1048576) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:07:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 2097152) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:07:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 3145728) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:07:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 4194304) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:07:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 5242880) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:07:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 6291456) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:07:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 7340032) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:07:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 8388608) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:08:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 9437184) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:08:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 10485760) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:08:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 11534336) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:08:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 12582912) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:08:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 13631488) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:08:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 14680064) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:08:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 15728640) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:08:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 16777216) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:08:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 17825792) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:08:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 18874368) to /tmp/localstack/docker.registry.bin
localstack    | time="2020-04-22T22:51:09.055351723Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.11.2 instance.id=e3c0eabc-0d02-4df6-b59b-1f173d1f42a8 service=registry version=v2.7.1
localstack    | time="2020-04-22T22:51:09.055401055Z" level=info msg="redis not configured" go.version=go1.11.2 instance.id=e3c0eabc-0d02-4df6-b59b-1f173d1f42a8 service=registry version=v2.7.1
localstack    | time="2020-04-22T22:51:09.055519713Z" level=info msg="Starting upload purge in 23m0s" go.version=go1.11.2 instance.id=e3c0eabc-0d02-4df6-b59b-1f173d1f42a8 service=registry version=v2.7.1
localstack    | time="2020-04-22T22:51:09.066004412Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.11.2 instance.id=e3c0eabc-0d02-4df6-b59b-1f173d1f42a8 service=registry version=v2.7.1
localstack    | time="2020-04-22T22:51:09.066122152Z" level=info msg="listening on [::]:4510" go.version=go1.11.2 instance.id=e3c0eabc-0d02-4df6-b59b-1f173d1f42a8 service=registry version=v2.7.1
localstack    | 2020-04-22T22:51:08:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 19922944) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:08:DEBUG:localstack.utils.common: Writing 156320 bytes (total 20079264) to /tmp/localstack/docker.registry.bin
localstack    | 2020-04-22T22:51:08:DEBUG:localstack.utils.common: Done downloading https://github.com/localstack/localstack-artifacts/raw/master/docker-registry/registry.alpine, response code 200, total bytes 20079264
localstack    | time="2020-04-22T22:52:04.189408615Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.11.2 instance.id=e28ad8c8-7f59-4c60-a5d9-f2932e4e559d service=registry version=v2.7.1
localstack    | time="2020-04-22T22:52:04.189454913Z" level=info msg="redis not configured" go.version=go1.11.2 instance.id=e28ad8c8-7f59-4c60-a5d9-f2932e4e559d service=registry version=v2.7.1
localstack    | time="2020-04-22T22:52:04.189502527Z" level=info msg="Starting upload purge in 17m0s" go.version=go1.11.2 instance.id=e28ad8c8-7f59-4c60-a5d9-f2932e4e559d service=registry version=v2.7.1
localstack    | 22:52:04.180 [elasticmq-akka.actor.default-dispatcher-13] INFO  o.elasticmq.actor.QueueManagerActor - Creating queue QueueData(us-east-1_dev-sym-df2-mt-broadcast-subscription,MillisVisibilityTimeout(30000),PT0S,PT0S,2020-04-22T22:52:04.141Z,2020-04-22T22:52:04.141Z,None,false,false,None,None,Map())
localstack    | time="2020-04-22T22:52:04.199229465Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.11.2 instance.id=e28ad8c8-7f59-4c60-a5d9-f2932e4e559d service=registry version=v2.7.1
localstack    | time="2020-04-22T22:52:04.199355613Z" level=info msg="listening on [::]:4511" go.version=go1.11.2 instance.id=e28ad8c8-7f59-4c60-a5d9-f2932e4e559d service=registry version=v2.7.1
localstack    | 2020-04-22T22:52:04:INFO:localstack_ext.services.ecr.ecr_listener: Starting ECR Docker registry on port 4511
localstack    | 2020-04-22 22:52:04,186:API: Error on request:
localstack    | Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
localstack    |     execute(self.server.app)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
localstack    |     application_iter = app(environ, start_response)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 135, in __call__
localstack    |     return backend_app(environ, start_response)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
localstack    |     return self.wsgi_app(environ, start_response)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
localstack    |     response = self.handle_exception(e)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack    |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
localstack    |     reraise(exc_type, exc_value, tb)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack    |     raise value
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
localstack    |     response = self.full_dispatch_request()
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
localstack    |     rv = self.handle_user_exception(e)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack    |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
localstack    |     reraise(exc_type, exc_value, tb)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack    |     raise value
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
localstack    |     rv = self.dispatch_request()
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
localstack    |     return self.view_functions[rule.endpoint](**req.view_args)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 146, in __call__
localstack    |     result = self.callback(request, request.url, {})
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 197, in dispatch
localstack    |     return cls()._dispatch(*args, **kwargs)
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 295, in _dispatch
localstack    |     return self.call_action()
localstack    |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 392, in call_action
localstack    |     raise NotImplementedError(
localstack    | NotImplementedError: The list_tags_for_resource action has not been implemented

```

**Comment by joseflexadaitan** [comment]
@whummer also of mention: ecr is shown as running on health

```
$ curl -s http://10.0.0.20:8080/health|jq
{
  "services": {
    "cloudwatch": "running",
    "dynamodb": "running",
    "ecr": "running",
    "ecs": "running",
    "edge": "running",
    "iam": "running",
    "s3": "running",
    "sns": "running",
    "sqs": "running",
    "sts": "running"
  }
}

```

**Comment by whummer** [comment]
Thanks for reporting this issue @joseflexadaitan . This should be fixed in the latest version - can you please do a `docker pull localstack/localstack` and give it another try? Please report here if the problem persists. Thanks!

**Comment by AvianDo** [comment]
@whummer can you please give me an Slack invitation?

**Comment by srujansurapaneni** [comment]
@whummer - I'm seeing issues running ecr with the pro version too. I work for a major health insurance company and have got an evaluation key from localstack recently. Can you send me the slack invite too. Thank You
