### ISSUE TITLE
Crash localstack with docket push of a 736MB image

### ISSUE THREAD

**Issue by joseflexadaitan** [localstack/localstack#2345]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I created a ubuntu based image and we tried to push it to the ECR repository we created on localstack and which we added as a insecure registry. When we run the push we get the following stack trace and the docker-composer process ends:

The image we are trying to push is bellow

REPOSITORY                                                    TAG                 IMAGE ID            CREATED             SIZE
10.0.0.20:4510/repo1                                         latest              4d2d91b762ba        6 hours ago         736MB

Here is the stack trace:
```
localstack    | Ready.
Exception in thread Thread-7:
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 672, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 421, in _make_request
  File "<string>", line 3, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 416, in _make_request
  File "http/client.py", line 1344, in getresponse
  File "http/client.py", line 306, in begin
  File "http/client.py", line 267, in _read_status
  File "socket.py", line 589, in readinto
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 720, in urlopen
  File "site-packages/urllib3/util/retry.py", line 400, in increment
  File "site-packages/urllib3/packages/six.py", line 734, in reraise
  File "site-packages/urllib3/connectionpool.py", line 672, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 421, in _make_request
  File "<string>", line 3, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 416, in _make_request
  File "http/client.py", line 1344, in getresponse
  File "http/client.py", line 306, in begin
  File "http/client.py", line 267, in _read_status
  File "socket.py", line 589, in readinto
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "compose/cli/log_printer.py", line 217, in watch_events
  File "compose/project.py", line 510, in yield_loop
  File "compose/project.py", line 478, in build_container_event
  File "compose/container.py", line 48, in from_id
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 758, in inspect_container
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 230, in _get
  File "site-packages/requests/sessions.py", line 546, in get
  File "site-packages/requests/sessions.py", line 533, in request
  File "site-packages/requests/sessions.py", line 646, in send
  File "site-packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Exception in thread Thread-5:
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 672, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 421, in _make_request
  File "<string>", line 3, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 416, in _make_request
  File "http/client.py", line 1344, in getresponse
  File "http/client.py", line 306, in begin
  File "http/client.py", line 267, in _read_status
  File "socket.py", line 589, in readinto
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 720, in urlopen
  File "site-packages/urllib3/util/retry.py", line 400, in increment
  File "site-packages/urllib3/packages/six.py", line 734, in reraise
  File "site-packages/urllib3/connectionpool.py", line 672, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 421, in _make_request
  File "<string>", line 3, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 416, in _make_request
  File "http/client.py", line 1344, in getresponse
  File "http/client.py", line 306, in begin
  File "http/client.py", line 267, in _read_status
  File "socket.py", line 589, in readinto
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "compose/cli/log_printer.py", line 169, in tail_container_logs
  File "compose/cli/log_printer.py", line 200, in wait_on_exit
  File "compose/container.py", line 281, in wait
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1289, in wait
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 226, in _post
  File "site-packages/requests/sessions.py", line 581, in post
  File "site-packages/requests/sessions.py", line 533, in request
  File "site-packages/requests/sessions.py", line 646, in send
  File "site-packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Exception in thread Thread-6:
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 672, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 421, in _make_request
  File "<string>", line 3, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 416, in _make_request
  File "http/client.py", line 1344, in getresponse
  File "http/client.py", line 306, in begin
  File "http/client.py", line 267, in _read_status
  File "socket.py", line 589, in readinto
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 720, in urlopen
  File "site-packages/urllib3/util/retry.py", line 400, in increment
  File "site-packages/urllib3/packages/six.py", line 734, in reraise
  File "site-packages/urllib3/connectionpool.py", line 672, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 421, in _make_request
  File "<string>", line 3, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 416, in _make_request
  File "http/client.py", line 1344, in getresponse
  File "http/client.py", line 306, in begin
  File "http/client.py", line 267, in _read_status
  File "socket.py", line 589, in readinto
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "compose/cli/log_printer.py", line 169, in tail_container_logs
  File "compose/cli/log_printer.py", line 200, in wait_on_exit
  File "compose/container.py", line 281, in wait
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1289, in wait
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 226, in _post
  File "site-packages/requests/sessions.py", line 581, in post
  File "site-packages/requests/sessions.py", line 533, in request
  File "site-packages/requests/sessions.py", line 646, in send
  File "site-packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

## Expected behavior

push image to ecr

## Actual behavior

local stack process ends

# Steps to reproduce

## Command used to start LocalStack

`AWS_REGION=us-east-1 LOCALSTACK_API_KEY=GuessMe docker-compose up
`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

`docker push 10.0.0.20:4510/repo1
`

**Comment by whummer** [comment]
Thanks for reporting @joseflexadaitan . This looks very closely related to #2324 (likely due to the same root cause) - please see my response there. Let's try to continue the conversation on #2324 and get this resolved for you soon. Thanks!
