### ISSUE TITLE
Version 0.2.1 - Unknown port mapping for service: dynamodb

### ISSUE THREAD

**Issue by mickog** [localstack/localstack#2368]
Really strange behaviour, what is working on a colleagues machine is not working on mine which i thought was not meant to be the case when running docker images.

Maven Dependency

```
 <dependency>
            <groupId>cloud.localstack</groupId>
            <artifactId>localstack-utils</artifactId>
            <version>0.2.1</version>
            <scope>test</scope>
        </dependency>
```

Getting the error

```
Apr 29, 2020 2:07:18 PM cloud.localstack.docker.annotation.LocalstackDockerAnnotationProcessor getExternalHostName
INFO: External host name is set to: localhost
Apr 29, 2020 2:07:21 PM cloud.localstack.docker.Container createLocalstackContainer
INFO: Started container: c356b2e82a2acbeefb4cb1f1032d814886b6474639476bc400dffb75124e02f8
Apr 29, 2020 2:07:21 PM cloud.localstack.Localstack startup
INFO: Waiting for LocalStack container to be ready...

java.lang.IllegalArgumentException: Unknown port mapping for service: dynamodb

	at cloud.localstack.Localstack.endpointForService(Localstack.java:204)
	at cloud.localstack.Localstack.getEndpointDynamoDB(Localstack.java:131)
	at cloud.localstack.TestUtils.getEndpointConfigurationDynamoDB(TestUtils.java:187)
	at cloud.localstack.TestUtils.getClientDynamoDB(TestUtils.java:143)
	at com.lmig.global.eventframeworktrackerinfra.DyamodbCRUDTest.setUp(DyamodbCRUDTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cloud.localstack.LocalstackTestRunner.run(LocalstackTestRunner.java:42)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Apr 29, 2020 2:07:50 PM cloud.localstack.docker.Container stop
INFO: Stopped container: c356b2e82a2acbeefb4cb1f1032d814886b6474639476bc400dffb75124e02f8

Process finished with exit code 255
```

Here is my class if it helps

```
import cloud.localstack.LocalstackTestRunner;
import cloud.localstack.TestUtils;
import cloud.localstack.docker.annotation.LocalstackDockerProperties;
import com.amazonaws.services.dynamodbv2.document.DynamoDB;
import com.amazonaws.services.dynamodbv2.document.Item;
import com.amazonaws.services.dynamodbv2.document.PutItemOutcome;
import com.amazonaws.services.dynamodbv2.document.Table;
import com.amazonaws.services.dynamodbv2.model.*;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.ActiveProfiles;
import software.amazon.ion.Timestamp;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

/**
 * This class is not unit testing any Java classes, But it test out if INSERT
 * operation of the following fields possible while executing
 */
@RunWith(LocalstackTestRunner.class)
@LocalstackDockerProperties(services = {"dynamodb"})
@ActiveProfiles("test")
public class DyamodbCRUDTest {

	public static final String ERROR_TRACKER = "error-tracker";
	DynamoDB dynamoDB;

	@Before
	public void setUp() throws InterruptedException {
		dynamoDB = new DynamoDB(TestUtils.getClientDynamoDB());
		List<KeySchemaElement> keySchema = new ArrayList<KeySchemaElement>();
		keySchema.add(new KeySchemaElement().withAttributeName("messageId").withKeyType(KeyType.HASH));

		List<AttributeDefinition> attributeDefinitions = new ArrayList<AttributeDefinition>();
		attributeDefinitions.add(new AttributeDefinition().withAttributeName("messageId").withAttributeType("S"));

		CreateTableRequest request = new CreateTableRequest()
				.withTableName(ERROR_TRACKER)
				.withKeySchema(keySchema)
				.withAttributeDefinitions(attributeDefinitions)
				.withProvisionedThroughput(new ProvisionedThroughput()
						.withReadCapacityUnits(5L)
						.withWriteCapacityUnits(6L));

		Table table = dynamoDB.createTable(request);
		table.waitForActive();
		TimeUnit.SECONDS.sleep(5);
	}

	/**
	 * This test is to test the dynamo db INSERT operation with the db created through the setUp
	 */
	@Test
	public void testInsertIntoTable() {

		Table table = dynamoDB.getTable(ERROR_TRACKER);

		// Build the item
		Item item = new Item()
				.withPrimaryKey("messageId", "f46gsfkv789")
				.withString("Subscriber", "FivaTestSubscriber")
				.withString("Timestamp", Timestamp.now().toString())
				.withString("Status", "Failure")
				.withString("Description", String.valueOf(new IOException("Error accessing file").getStackTrace()));

		// Write the item to the table
		PutItemOutcome outcome = table.putItem(item);
	}
}
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-178) by [Unito](https://www.unito.io/learn-more)

**Comment by usmangani1** [comment]
@mickog Thanks for reporting the issue here.

Can you please help us with the command which you are using to spin up the localstack ?

**Comment by thrau** [comment]
Closing this issue due to inactivity. Please let us know if the problem persists with the latest version.
