### ISSUE TITLE
SQS fails to create deadqueue/redrive policy

### ISSUE THREAD

**Issue by Saqibm128** [localstack/localstack#238]
Happens whether redrive policy attribute is attached when queue is created or if queue is already created and set-queue-attributes is used.

```
aws sqs --endpoint-url http://192.168.99.101:4576 create-queue --queue-name test-dead-queue
aws sqs --endpoint-url http://192.168.99.101:4576 create-queue --queue-name test-queue --attributes '{"RedrivePolicy": "{\"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:123456789012:test-dead-queue\",\"maxReceiveCount\":5}"}'
```
While other attributes will show up, redrivePolicy is missing when we run this command
```
aws sqs --endpoint-url http://192.168.99.101:4576 get-queue-attributes --queue-url http://192.168.99.101:4576/123456789012/test-queue --attribute-names All
```

Similar if we set queue attributes as well

```
aws sqs --endpoint-url http://192.168.99.101:4576 set-attributes --queue-url http://192.168.99.101:4576/123456789012/test-queue --attributes '{"RedrivePolicy": "{\"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:123456789012:test-dead-queue\",\"maxReceiveCount\":5}"}'

aws sqs --endpoint-url http://192.168.99.101:4576 get-queue-attributes --queue-url http://192.168.99.101:4576/123456789012/test-queue --attribute-names All
```

Output
```
{
    "Attributes": {
        "ApproximateNumberOfMessagesNotVisible": "0", 
        "MessageRetentionPeriod": "345600", 
        "ApproximateNumberOfMessagesDelayed": "0", 
        "MaximumMessageSize": "65536", 
        "CreatedTimestamp": "1502311544.78", 
        "ApproximateNumberOfMessages": "0", 
        "DelaySeconds": "0", 
        "ReceiveMessageWaitTimeSeconds": "0", 
        "WaitTimeSeconds": "0", 
        "VisibilityTimeout": "30", 
        "LastModifiedTimestamp": "1502311544.78", 
        "QueueArn": "arn:aws:sqs:us-east-1:123456789012:test-queue"
    }
}
```

**Comment by ambrusadrianz** [comment]
@whummer maybe integrating ElasticMQ instead of moto sqs would resolve this issue altogether

**Comment by kprzerwa-r7** [comment]
Is there an ETA on when this feature is going to be worked on?

**Comment by whummer** [comment]
I'm currently looking into this, initial PR for replacing moto SQS with ElasticMQ is up here: #287 . Still need to do a bit more testing, but looks promising so far.

**Comment by whummer** [comment]
@Saqibm128 This should be fixed in #287 . Note that I had to slightly modify your command to get this working:
```
aws sqs --endpoint-url http://192.168.99.101:4576 create-queue --queue-name test-dead-queue
aws sqs --endpoint-url http://192.168.99.101:4576 create-queue --queue-name test-queue --attributes '{"RedrivePolicy": "{\"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:123456789012:test-dead-queue\",\"maxReceiveCount\":\"5\"}"}'
```
Note `\"5\"` instead of `5` - it seems that ElasticMQ expects strings for queue attribute values.

Can you please give it a try and confirm that it works for you? Thanks

**Comment by kprzerwa-r7** [comment]
@whummer I created my queues (in Java) as usual and noticed a weird endpoint in queue URLs which can't be resolved:
```
# awslocal sqs list-queues
{
    "QueueUrls": [
        "http://e0a775077866:4576/queue/new-result",
        "http://e0a775077866:4576/queue/dead-letter"
    ]
}
```
so for example, the requests:
```
AmazonSQS sqsClient = TestUtils.getClientSQS();
sqsClient.getQueueAttributes(new GetQueueAttributesRequest(sqsClient.getQueueUrl("dead-letter").getQueueUrl()))
```
fails with:
```
com.amazonaws.SdkClientException: Unable to execute HTTP request: e0a775077866
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1068)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1034)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1740)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1716)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeGetQueueAttributes(AmazonSQSClient.java:1013)
	at com.amazonaws.services.sqs.AmazonSQSClient.getQueueAttributes(AmazonSQSClient.java:989)
```
Do I need to set endpoint to `localhost` now in AmazonSQSClient? This would defeat the purpose of `TestUtils.getClientSQS()` which is really handy... or maybe I am missing something?

**Comment by whummer** [comment]
@kprzerwa-r7 This should be fixed in #301 . You can now set the environment variable `HOSTNAME_EXTERNAL` to customize the hostname to be returned for the SQS queue URLs. Can you please give that a try with the latest version of the Docker image. Thanks

**Comment by kprzerwa-r7** [comment]
Thanks @whummer, I'll give this a go and let you know.

**Comment by richfromm** [comment]
Is this supposed to be fixed? I'm trying to create a queue in localstack via boto3 (python), and it fails if I specify a redrive policy:
```
>>> queue_name = 'test_queue'
>>> redrive_policy = r'{"maxReceiveCount": 10, "deadLetterTargetArn": "arn:aws:sqs:elasticmq:000000000000:test-queue-DLQ"}'
>>> attributes = dict(ReceiveMessageWaitTimeSeconds='20', RedrivePolicy=redrive_policy)
>>> attributes
{'RedrivePolicy': '{"maxReceiveCount": 10, "deadLetterTargetArn": "arn:aws:sqs:elasticmq:000000000000:test-queue-DLQ"}', 'ReceiveMessageWaitTimeSeconds': '20'}
>>> queue = sqs.create_queue(QueueName=queue_name, Attributes=attributes)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rich/git/ll/ring/activity_importer/build/tox/test/local/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/rich/git/ll/ring/activity_importer/build/tox/test/local/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/home/rich/git/ll/ring/activity_importer/build/tox/test/local/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/rich/git/ll/ring/activity_importer/build/tox/test/local/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (MalformedQueryString) when calling the CreateQueue operation: MalformedQueryString; see the SQS docs.
>>> 
```

It works fine if I leave off the redrive policy:
```
>>> attributes = dict(ReceiveMessageWaitTimeSeconds='20')
>>> queue = sqs.create_queue(QueueName=queue_name, Attributes=attributes)
>>> queue
sqs.Queue(url='http://localhost:4576/queue/test_queue')
>>> 
```

This is with the following localstack docker container:
```
REPOSITORY                                                                TAG                   IMAGE ID            CREATED             SIZE
localstack/localstack                                                     latest                e7338550cf7f        18 hours ago        723MB
```

And the following client libraries:
```
boto3==1.4.8
botocore==1.8.6
```

It's possible that I really am specifying the query wrong, although I compared the format to an actual SQS queue in real AWS (the queue and DLQ were both created with terraform; I queried the info with boto3), and AFAICT I'm specifying the attributes in the same way.

**Comment by richfromm** [comment]
I enabled logging in the localstack container via `DEBUG=1` as suggested at https://bitbucket.org/atlassian/localstack/issues/17/how-to-debug-failing-features

Creating the DLQ (that does **not** have a `RedrivePolicy`) works fine, and is logged as follows:
```
 23:40:01.486 [elasticmq-akka.actor.default-dispatcher-16] INFO  o.elasticmq.actor.QueueManagerActor - Creating queue QueueData(test_queue-DLQ,MillisVisibilityTimeout(30000),PT0S,PT20S,2017-12-11T23:40:01.485Z,2017-12-11T23:40:01.485Z,None,None)
```

Here's the stack trace from localstack trying to create the queue with the `RedrivePolicy` pointing to the previously created DLQ:
```
23:41:05.759 [elasticmq-akka.actor.default-dispatcher-17] WARN  o.e.r.s.TheSQSRestServerBuilder$$anon$1 - Cannot deserialize the redrive policy attribute
spray.json.DeserializationException: Expected fields: 'deadLetterTargetArn' (JSON string) and 'maxReceiveCount' (JSON number)
at spray.json.package$.deserializationError(package.scala:23)
at org.elasticmq.rest.sqs.RedrivePolicyJson$$anon$1.read(CreateQueueDirectives.scala:135)
at org.elasticmq.rest.sqs.RedrivePolicyJson$$anon$1.read(CreateQueueDirectives.scala:131)
at spray.json.JsValue.convertTo(JsValue.scala:31)
at org.elasticmq.rest.sqs.CreateQueueDirectives.$anonfun$createQueue$3(CreateQueueDirectives.scala:29)
at scala.Option.map(Option.scala:146)
at org.elasticmq.rest.sqs.CreateQueueDirectives.$anonfun$createQueue$2(CreateQueueDirectives.scala:29)
at akka.http.scaladsl.server.util.ApplyConverterInstances$$anon$1.$anonfun$apply$1(ApplyConverterInstances.scala:14)
at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$tprovide$1(BasicDirectives.scala:138)
at akka.http.scaladsl.server.Directive$$anon$1.tapply(Directive.scala:115)
at akka.http.scaladsl.server.Directive$.$anonfun$addDirectiveApply$1(Directive.scala:127)
at org.elasticmq.rest.sqs.CreateQueueDirectives.$anonfun$createQueue$1(CreateQueueDirectives.scala:23)
at akka.http.scaladsl.server.Directive$.$anonfun$addByNameNullaryApply$2(Directive.scala:134)
at akka.http.scaladsl.server.Directive$.$anonfun$Empty$1(Directive.scala:120)
at akka.http.scaladsl.server.Directive$$anon$1.tapply(Directive.scala:115)
at akka.http.scaladsl.server.Directive$.$anonfun$addByNameNullaryApply$1(Directive.scala:134)
at org.elasticmq.rest.sqs.CreateQueueDirectives.createQueue(CreateQueueDirectives.scala:22)
at org.elasticmq.rest.sqs.CreateQueueDirectives.createQueue$(CreateQueueDirectives.scala:20)
at org.elasticmq.rest.sqs.TheSQSRestServerBuilder$$anon$1.createQueue(SQSRestServerBuilder.scala:98)
at org.elasticmq.rest.sqs.TheSQSRestServerBuilder.rawRoutes$1(SQSRestServerBuilder.scala:137)
at org.elasticmq.rest.sqs.TheSQSRestServerBuilder.$anonfun$start$3(SQSRestServerBuilder.scala:160)
at org.elasticmq.rest.sqs.directives.AnyParamDirectives.$anonfun$anyParamsMap$3(AnyParamDirectives.scala:19)
at akka.http.scaladsl.server.util.ApplyConverterInstances$$anon$1.$anonfun$apply$1(ApplyConverterInstances.scala:14)
at akka.http.scaladsl.server.Directive.$anonfun$recover$4(Directive.scala:93)
at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:61)
at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37)
at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$2(FutureDirectives.scala:37)
at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
at akka.http.scaladsl.server.Directive.$anonfun$recover$2(Directive.scala:93)
at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:67)
at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:67)
at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:154)
at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
at akka.http.scaladsl.server.Route$.$anonfun$asyncHandler$1(Route.scala:79)
at akka.stream.impl.fusing.MapAsync$$anon$23.onPush(Ops.scala:1172)
at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)
at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)
at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)
at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740)
at akka.actor.Actor.aroundReceive(Actor.scala:513)
at akka.actor.Actor.aroundReceive$(Actor.scala:511)
at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
at akka.actor.ActorCell.invoke(ActorCell.scala:496)
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
at akka.dispatch.Mailbox.run(Mailbox.scala:224)
at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by kprzerwa-r7** [comment]
Apologies for not giving a promised update...

Creating queue with redrive policy works for me. See my Java snippet below:
```
      String deadletterQueueUrl = sqsClient.createQueue(testErrorQueue).getQueueUrl();

      // get queue attributes
      GetQueueAttributesRequest getAttributesRequest = new GetQueueAttributesRequest(deadletterQueueUrl)
         .withAttributeNames(QueueAttributeName.QueueArn);
      GetQueueAttributesResult queueAttributesResult = sqsClient.getQueueAttributes(getAttributesRequest);

      // set redrive policy to new asset queue
      String redrivePolicy = "{\"maxReceiveCount\":\"1\", \"deadLetterTargetArn\":\"" +
         queueAttributesResult.getAttributes().get(QueueAttributeName.QueueArn.name()) + "\"}";
      Map<String,String> attributes = new HashMap<>();
      attributes.put(QueueAttributeName.RedrivePolicy.name(), redrivePolicy);

      sqsClient.createQueue(new CreateQueueRequest(newAssetQueue).withAttributes(attributes));
```

**Comment by jonaskint** [comment]
Having the same issue. 100% sure mine is escaped as it should as i verified it against the real aws endpoint. I'm using terraform to provision the localstack resources.

```
provider "aws" {
  region                      = "us-east-1"
  access_key                  = "anaccesskey"
  secret_key                  = "asecretkey"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  s3_force_path_style         = true

  endpoints {
    s3     = "http://localhost:4572"
    sns    = "http://localhost:4575"
    sqs    = "http://localhost:4576"
    lambda = "http://localhost:4574"
    iam    = "http://localhost:4574"
  }
}
resource "aws_sqs_queue" "testdlq" {
  name                       = "testdlq"
  message_retention_seconds  = 1209600
  receive_wait_time_seconds  = 20
  visibility_timeout_seconds = 120
}

resource "aws_sqs_queue" "test" {
  name                       = "test"
  message_retention_seconds  = 1209600
  receive_wait_time_seconds  = 20
  visibility_timeout_seconds = 1800
  redrive_policy             = "{\"deadLetterTargetArn\":\"${aws_sqs_queue.testdlq.arn}\",\"maxReceiveCount\":20}"
}
```

Current output in terraform is:
```
Error: Error applying plan:

1 error(s) occurred:

* aws_sqs_queue.pdfoptimize: 1 error(s) occurred:

* aws_sqs_queue.pdfoptimize: Error creating SQS queue: MalformedQueryString: MalformedQueryString; see the SQS docs.
	status code: 400, request id: 00000000-0000-0000-0000-000000000000
```

**Comment by ssjoleary** [comment]
Ah, looks like prior to ElasticMQ 0.13.9 the `RedrivePolicy` was an ignored attribute: https://github.com/adamw/elasticmq/issues/132
`localstack` is using [0.13.8](https://github.com/localstack/localstack/blob/master/bin/Dockerfile.base#L60) so I guess that explains that!

It seems like it has actually been implemented in ElasticMQ 0.13.9 even though the ignored attribute warning still exists.

**Comment by imankulov** [comment]
Hey everyone!

Just came across this issue and changing 5 to "5", as explained in [this comment](https://github.com/localstack/localstack/issues/238#issuecomment-326729327) by @whummer, works like a charm. 

> localstack is using 0.13.8 

At the time of writing it's v0.14.2 already (upgraded in #880). I would say, the issue can probably be closed.

**Comment by dusinof** [comment]
Hi, 
I'm having same issue now. Dead letter queue is not working. Even if i raise the exception 3,4,5...x times and threshold is 2, message is never sent to dead letter q. More over, aws cli command:`list-dead-letter-source-queues` is not working, neither his JAVA version. Is this some limitation on localstack side ? I don't have access to aws currently, so, I can't validate it there. 

```
aws --endpoint-url=http://localhost:4576 sqs get-queue-attributes --queue-url=http://localhost:4576/queue/standard-Q

{
    "Attributes": {
        "RedrivePolicy": "{\"maxReceiveCount\":\"2\", \"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:000000000000:deadLetter-Q\"}"
    }
}

aws --endpoint-url=http://localhost:4576 sqs list-queues
{
    "QueueUrls": [
        "http://localhost:4576/queue/standard-Q",
        "http://localhost:4576/queue/deadLetter-Q"
    ]
}

aws --endpoint-url=http://localhost:4576 sqs list-dead-letter-source-queues --queue-url http://localhost:4576/queue/deadLetter-Q

An error occurred (InvalidAction) when calling the ListDeadLetterSourceQueues operation: InvalidAction; see the SQS docs.
```

```
  @Bean
    public AmazonSQSAsync amazonSqs() {

        AmazonSQSAsync client = AmazonSQSAsyncClientBuilder.standard()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(localStackSqsUrl, awsRegion))
                .build();

        createQueue(client);
        return client;
    }

public void createQueue(AmazonSQSAsync amazonSqs) {
        amazonSqs.createQueue(queue);
        amazonSqs.createQueue(dqueue);

        String dl_queue_url = amazonSqs.getQueueUrl(dqueue).getQueueUrl();

        GetQueueAttributesResult queue_attrs = amazonSqs.getQueueAttributes(
                new GetQueueAttributesRequest(dl_queue_url)
                        .withAttributeNames("QueueArn"));

        String dl_queue_arn = queue_attrs.getAttributes().get("QueueArn");

        // Set dead letter queue with redrive policy on source queue.
        String src_queue_url = amazonSqs.getQueueUrl(queue).getQueueUrl();


        final SetQueueAttributesRequest request = new SetQueueAttributesRequest()
                .withQueueUrl(src_queue_url)
                .addAttributesEntry(QueueAttributeName.RedrivePolicy.toString(),
                        "{\"maxReceiveCount\":\"2\", \"deadLetterTargetArn\":\""
                                + dl_queue_arn + "\"}");

        amazonSqs.setQueueAttributes(request);

    }
```
