### ISSUE TITLE
can't delete stack (cloudformation

### ISSUE THREAD

**Issue by ozbillwang** [localstack/localstack#2380]
# Type of request: This is a ...

[X] bug report

# Detailed description

created stack with this template:

https://s3.ap-southeast-2.amazonaws.com/cloudformation-templates-ap-southeast-2/EC2InstanceWithSecurityGroupSample.template

Now I want to delete the stack

```
$ aws cloudformation delete-stack --stack-name my-stack

An error occurred (502) when calling the DeleteStack operation (reached max retries: 4): Bad Gateway
$
```
## Expected behavior

the stack should be deleted.

## Actual behavior

get error

    An error occurred (502) when calling the DeleteStack operation (reached max retries: 4): Bad Gateway

**Comment by whummer** [comment]
Thanks for reporting @ozbillwang . Can you please try running LocalStack with `DEBUG=1` enabled, and then post any error messages or stack traces logged in the container output? Thanks

**Comment by ozbillwang** [comment]
Here are the debug logs

```
$ docker-compose logs
WARNING: The TMPDIR variable is not set. Defaulting to a blank string.
Attaching to localstack_main
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | 2020-05-03 23:28:23,429 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_main | 2020-05-03 23:28:23,433 INFO supervisord started with pid 13
localstack_main | 2020-05-03 23:28:24,436 INFO spawned: 'dashboard' with pid 19
localstack_main | 2020-05-03 23:28:24,439 INFO spawned: 'infra' with pid 20
localstack_main | (. .venv/bin/activate; bin/localstack web)
localstack_main | 2020-05-03 23:28:24,446 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_main | 2020-05-03T23:28:25:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext":<function register_localstack_commands at 0x7f9d86dc0790>
localstack_main | LocalStack version: 0.11.1
localstack_main | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_main | 2020-05-03T23:28:25:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f9d86df1310>
localstack_main | 2020-05-03 23:28:25,772 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_main | LocalStack version: 0.11.1
localstack_main | Starting local dev environment. CTRL-C to quit.
localstack_main | !WARNING! - Looks like you have configured $LAMBDA_REMOTE_DOCKER=1 - please make sure to configure $HOST_TMP_FOLDER to point to your host's $TMPDIR
localstack_main | 2020-05-03T23:28:25:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext":<function register_localstack_commands at 0x7f691673e790>
localstack_main | 2020-05-03T23:28:25:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f691676f310>
localstack_main | 2020-05-03T23:28:29:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext":<function register_localstack_plugins at 0x7f9d86633b80>
localstack_main | 2020-05-03T23:28:29:INFO:localstack.utils.common: Unable to store key/cert files for custom SSL certificate: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem.key'
localstack_main | 2020-05-03T23:28:29:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext":<function register_localstack_plugins at 0x7f6915fb1b80>
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | Starting edge router (https port 4566)...
localstack_main | Starting mock API Gateway service in http ports 4566 (recommended) and 4567 (deprecated)...
localstack_main | 2020-05-03T23:28:32:INFO:localstack.multiserver: Starting multi API server process on port 51492
localstack_main | Starting mock CloudFormation service in http ports 4566 (recommended) and 4581 (deprecated)...
localstack_main | Starting mock CloudWatch service in http ports 4566 (recommended) and 4582 (deprecated)...
localstack_main | Starting mock DynamoDB service in http ports 4566 (recommended) and 4569 (deprecated)...
localstack_main | Starting mock DynamoDB Streams service in http ports 4566 (recommended) and 4570 (deprecated)...
localstack_main | Starting mock EC2 service in http ports 4566 (recommended) and 4597 (deprecated)...
localstack_main | Starting mock ES service in http ports 4566 (recommended) and 4578 (deprecated)...
localstack_main | Starting mock Firehose service in http ports 4566 (recommended) and 4573 (deprecated)...
localstack_main | Starting mock IAM service in http ports 4566 (recommended) and 4593 (deprecated)...
localstack_main | Starting mock STS service in http ports 4566 (recommended) and 4592 (deprecated)...
localstack_main | Starting mock Kinesis service in http ports 4566 (recommended) and 4568 (deprecated)...
localstack_main | Starting mock KMS service in http ports 4566 (recommended) and 4599 (deprecated)...
localstack_main | Starting mock Lambda service in http ports 4566 (recommended) and 4574 (deprecated)...
localstack_main | Starting mock CloudWatch Logs service in http ports 4566 (recommended) and 4586 (deprecated)...
localstack_main | Starting mock Redshift service in http ports 4566 (recommended) and 4577 (deprecated)...
localstack_main | INFO[2020-05-03 23:28:33.525] No file found at path /init/seed.yaml; skipping seeding.
localstack_main | INFO[2020-05-03 23:28:33.525] Data will be stored in /tmp/local-kms
localstack_main | INFO[2020-05-03 23:28:33.525] Local KMS started on 0.0.0.0:4554
localstack_main | Starting mock Route53 service in http ports 4566 (recommended) and 4580 (deprecated)...
localstack_main | Starting mock S3 service in http ports 4566 (recommended) and 4572 (deprecated)...
localstack_main | Initializing DynamoDB Local with the following configuration:
localstack_main | Port: 4563
localstack_main | InMemory:     true
localstack_main | DbPath:       null
localstack_main | SharedDb:     true
localstack_main | shouldDelayTransientStatuses: false
localstack_main | CorsParams:   *
localstack_main | Starting mock Secrets Manager service in http ports 4566 (recommended) and 4584 (deprecated)...
localstack_main |
localstack_main | Listening at http://:::4564
localstack_main | Starting mock SES service in http ports 4566 (recommended) and 4579 (deprecated)...
localstack_main | Starting mock SNS service in http ports 4566 (recommended) and 4575 (deprecated)...
localstack_main | Starting mock SQS service in http ports 4566 (recommended) and 4576 (deprecated)...
localstack_main | Starting mock SSM service in http ports 4566 (recommended) and 4583 (deprecated)...
localstack_main | Starting mock Cloudwatch Events service in http ports 4566 (recommended) and 4587 (deprecated)...
localstack_main | Starting mock StepFunctions service in http ports 4566 (recommended) and 4585 (deprecated)...
localstack_main | 2020-05-03 23:28:33,270:API:  * Running on http://0.0.0.0:4565/ (Press CTRL+C to quit)
localstack_main | 2020-05-03 23:28:33,270:API:  * Running on http://0.0.0.0:4565/ (Press CTRL+C to quit)
localstack_main | 2020-05-03 23:28:33,270:API:  * Running on http://0.0.0.0:4565/ (Press CTRL+C to quit)
localstack_main | 2020-05-03 23:28:33,323:API:  * Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
localstack_main | 2020-05-03 23:28:33,323:API:  * Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
localstack_main | 2020-05-03 23:28:33,323:API:  * Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
localstack_main | 2020-05-03 23:28:33,339:API:  * Running on http://0.0.0.0:4558/ (Press CTRL+C to quit)
localstack_main | 2020-05-03 23:28:33,339:API:  * Running on http://0.0.0.0:4558/ (Press CTRL+C to quit)
localstack_main | 2020-05-03 23:28:33,339:API:  * Running on http://0.0.0.0:4558/ (Press CTRL+C to quit)
localstack_main | Step Functions Local
localstack_main | Version: 1.5.0
localstack_main | Build: 2020-02-15
localstack_main | 2020-05-03 23:28:34.589: Configure [Account] to [000000000000]
localstack_main | 2020-05-03 23:28:34.591: Configure [Region] to [us-east-1]
localstack_main | 2020-05-03 23:28:34.591: Configure [Lambda Endpoint] to [http://08a8408966d1:4574]
localstack_main | 2020-05-03 23:28:34.591: Configure [DynamoDB Endpoint] to [http://08a8408966d1:4569]
localstack_main | 2020-05-03 23:28:34.592: Configure [SQS Endpoint] to [http://08a8408966d1:4576]
localstack_main | 2020-05-03 23:28:34.592: Configure [SNS Endpoint] to [http://08a8408966d1:4575]
localstack_main | 2020-05-03 23:28:34.592: Configure [Step Functions Endpoint] to [http://08a8408966d1:4585]
localstack_main | 2020-05-03 23:28:34.627: Loaded credentials from environment
localstack_main | 2020-05-03 23:28:34.628: Starting server on port 8083 with account 000000000000, region us-east-1
localstack_main | 23:28:35.618 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.5) ...
localstack_main | May 03, 2020 11:28:36 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
localstack_main | WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
localstack_main | May 03, 2020 11:28:36 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
localstack_main | WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
localstack_main | May 03, 2020 11:28:36 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
localstack_main | WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
localstack_main | May 03, 2020 11:28:36 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
localstack_main | WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
localstack_main | May 03, 2020 11:28:36 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
localstack_main | WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
localstack_main | 23:28:36.689 [elasticmq-akka.actor.default-dispatcher-6] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
localstack_main | May 03, 2020 11:28:36 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
localstack_main | WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
localstack_main | May 03, 2020 11:28:36 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
localstack_main | WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
localstack_main | May 03, 2020 11:28:36 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
localstack_main | WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
localstack_main | May 03, 2020 11:28:36 PM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
localstack_main | WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | 23:28:38.122 [elasticmq-akka.actor.default-dispatcher-7] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:4560, visible server address http://08a8408966d1:4576
localstack_main | 23:28:38.123 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.15.5) started in 3973ms ===
localstack_main | Ready.
localstack_main | 2020-05-03T23:28:52:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource my-stack/EC2Instance: None
localstack_main | 2020-05-03T23:28:52:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource my-stack/InstanceSecurityGroup: None
localstack_main | 2020-05-03T23:28:52:WARNING:localstack.utils.cloudformation.template_deployer: Unknown resource type"EC2::SecurityGroup": {'Type': 'AWS::EC2::SecurityGroup', 'Properties': {'GroupDescription': 'Enable SSH access via port 22', 'SecurityGroupIngress': [{'IpProtocol': 'tcp', 'FromPort': '22', 'ToPort': '22', 'CidrIp': '0.0.0.0/0'}]}}
localstack_main | 2020-05-03T23:28:52:WARNING:localstack.utils.cloudformation.template_deployer: Unknown resource type"EC2::SecurityGroup": {'Type': 'AWS::EC2::SecurityGroup', 'Properties': {'GroupDescription': 'Enable SSH access via port 22', 'SecurityGroupIngress': [{'IpProtocol': 'tcp', 'FromPort': '22', 'ToPort': '22', 'CidrIp': '0.0.0.0/0'}]}}
localstack_main | 2020-05-03T23:28:52:DEBUG:localstack.services.cloudformation.cloudformation_starter: Resource InstanceSecurityGroup need not be deployed (is_updateable=False): {'Type': 'AWS::EC2::SecurityGroup', 'Properties': {'GroupDescription': 'Enable SSH access via port 22', 'SecurityGroupIngress': [{'IpProtocol': 'tcp', 'FromPort': '22', 'ToPort':'22', 'CidrIp': '0.0.0.0/0'}]}} True
localstack_main | 2020-05-03T23:28:52:WARNING:localstack.utils.cloudformation.template_deployer: Unknown resource type"EC2::Instance": {'Type': 'AWS::EC2::Instance', 'Properties': {'InstanceType': 't2.small', 'SecurityGroups': ['sg-9d8709f5'], 'KeyName': 'MyKeyPair', 'ImageId': 'ami-02fd0b06f06d93dfc'}}
localstack_main | 2020-05-03T23:28:52:DEBUG:localstack.services.cloudformation.cloudformation_starter: Updating incorrect region from us-east-1 to ap-southeast-2
localstack_main | 2020-05-03T23:28:52:WARNING:localstack.utils.cloudformation.template_deployer: Unknown resource type"EC2::Instance": {'Type': 'AWS::EC2::Instance', 'Properties': {'InstanceType': 't2.small', 'SecurityGroups': ['sg-9d8709f5'], 'KeyName': 'MyKeyPair', 'ImageId': 'ami-02fd0b06f06d93dfc'}}
localstack_main | 2020-05-03T23:28:52:DEBUG:localstack.services.cloudformation.cloudformation_starter: Resource EC2Instance need not be deployed (is_updateable=False): {'Type': 'AWS::EC2::Instance', 'Properties': {'InstanceType': 't2.small', 'SecurityGroups': ['sg-9d8709f5'], 'KeyName': 'MyKeyPair', 'ImageId': 'ami-02fd0b06f06d93dfc'}} True
localstack_main | 2020-05-03T23:28:52:DEBUG:localstack.services.cloudformation.cloudformation_starter: Running CloudFormation stack deployment loop iteration 1
localstack_main | 2020-05-03T23:29:00:DEBUG:localstack.services.cloudformation.cloudformation_starter: Running CloudFormation stack deployment loop iteration 1
localstack_main | 2020-05-03T23:29:06:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error responsefor CloudFormation action "ListStackResources" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id my-stack does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
localstack_main | 2020-05-03T23:29:06:ERROR:localstack.services.generic_proxy: Error forwarding request: An error occurred (ValidationError) when calling the ListStackResources operation: Stack with id my-stack does not exist Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 248, in forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 193, in forward_request
localstack_main |     stack_resources = client.list_stack_resources(StackName=stack_name)['StackResourceSummaries']
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
localstack_main |     return self._make_api_call(operation_name, kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 626, in _make_api_call
localstack_main |     raise error_class(parsed_response, operation_name)
localstack_main | botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the ListStackResources operation: Stack with id my-stack does not exist
localstack_main |
localstack_main | 2020-05-03T23:29:07:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error responsefor CloudFormation action "ListStackResources" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id my-stack does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
localstack_main | 2020-05-03T23:29:07:ERROR:localstack.services.generic_proxy: Error forwarding request: An error occurred (ValidationError) when calling the ListStackResources operation: Stack with id my-stack does not exist Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 248, in forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 193, in forward_request
localstack_main |     stack_resources = client.list_stack_resources(StackName=stack_name)['StackResourceSummaries']
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
localstack_main |     return self._make_api_call(operation_name, kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 626, in _make_api_call
localstack_main |     raise error_class(parsed_response, operation_name)
localstack_main | botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the ListStackResources operation: Stack with id my-stack does not exist
localstack_main |
localstack_main | 2020-05-03T23:29:07:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error responsefor CloudFormation action "ListStackResources" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id my-stack does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
localstack_main | 2020-05-03T23:29:07:ERROR:localstack.services.generic_proxy: Error forwarding request: An error occurred (ValidationError) when calling the ListStackResources operation: Stack with id my-stack does not exist Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 248, in forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 193, in forward_request
localstack_main |     stack_resources = client.list_stack_resources(StackName=stack_name)['StackResourceSummaries']
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
localstack_main |     return self._make_api_call(operation_name, kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 626, in _make_api_call
localstack_main |     raise error_class(parsed_response, operation_name)
localstack_main | botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the ListStackResources operation: Stack with id my-stack does not exist
localstack_main |
localstack_main | 2020-05-03T23:29:08:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error responsefor CloudFormation action "ListStackResources" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id my-stack does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
localstack_main | 2020-05-03T23:29:08:ERROR:localstack.services.generic_proxy: Error forwarding request: An error occurred (ValidationError) when calling the ListStackResources operation: Stack with id my-stack does not exist Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 248, in forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 193, in forward_request
localstack_main |     stack_resources = client.list_stack_resources(StackName=stack_name)['StackResourceSummaries']
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
localstack_main |     return self._make_api_call(operation_name, kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 626, in _make_api_call
localstack_main |     raise error_class(parsed_response, operation_name)
localstack_main | botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the ListStackResources operation: Stack with id my-stack does not exist
localstack_main |
localstack_main | 2020-05-03T23:29:12:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error responsefor CloudFormation action "ListStackResources" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id my-stack does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
localstack_main | 2020-05-03T23:29:12:ERROR:localstack.services.generic_proxy: Error forwarding request: An error occurred (ValidationError) when calling the ListStackResources operation: Stack with id my-stack does not exist Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 248, in forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 193, in forward_request
localstack_main |     stack_resources = client.list_stack_resources(StackName=stack_name)['StackResourceSummaries']
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
localstack_main |     return self._make_api_call(operation_name, kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 626, in _make_api_call
localstack_main |     raise error_class(parsed_response, operation_name)
localstack_main | botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the ListStackResources operation: Stack with id my-stack does not exist
localstack_main |
```

**Comment by ozbillwang** [comment]
Seems I found the issue. 

I set aws configuration as below: 
```
$ cat ~/.aws/credentials
# localstack test
# https://github.com/localstack/localstack
[default]
region                = ap-southeast-2
aws_secret_access_key = localstack
aws_access_key_id     = localstack
```

with some unkow reasons, the stack was created in region `us-east-1`. 

After I change it back to `us-east-1` in ~/.aws/credentials, I can delete this stack now.
