### ISSUE TITLE
Getting Bad Gateway error when tried to delete the cloudformation stack

### ISSUE THREAD

**Issue by ebalakumar** [localstack/localstack#2393]
[X] bug report 

# Detailed description

Unable to delete the AWS cloudformation stack. The error log from localstack mentions the below

`aws --profile=personal --endpoint-url=http://localhost:4581 cloudformation delete-stack --stack-name myteststack2`

**An error occurred (502) when calling the DeleteStack operation (reached max retries: 4): Bad Gateway**

Error log from localstack container:
```
2020-05-05T14:44:09:ERROR:localstack.services.generic_proxy: Error forwarding request: An error occurred (ValidationError) when calling the ListStackResources operation: Stack with id myteststack2 does not exist Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 248, in forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 193, in forward_request
    stack_resources = client.list_stack_resources(StackName=stack_name)['StackResourceSummaries']
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the ListStackResources operation: Stack with id myteststack2 does not exist
```
**But the stack exists.** 

`aws --profile=personal --endpoint-url=http://localhost:4581 cloudformation list-stacks 
`

```
{
    "StackSummaries": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/myteststack/f5339fd7-d969-4e71-b6c5-efccfbb90427",
            "StackName": "myteststack",
            "TemplateDescription": "AWS CloudFormation Sample Template S3_Website_Bucket_With_Retain_On_Delete: Sample template showing how to create a publicly accessible S3 bucket configured for website access with a deletion policy of retain on delete. **WARNING** This template creates an S3 bucket that will NOT be deleted when the stack is deleted. You will be billed for the AWS resources used if you create a stack from this template.",
            "CreationTime": "2020-05-05T14:21:53Z",
            "StackStatus": "UPDATE_COMPLETE"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/myteststack2/b44988ac-c8ef-4ce9-a494-aa787d2ed557",
            "StackName": "myteststack2",
            "TemplateDescription": "AWS CloudFormation Sample Template S3_Website_Bucket_With_Retain_On_Delete: Sample template showing how to create a publicly accessible S3 bucket configured for website access with a deletion policy of retain on delete. **WARNING** This template creates an S3 bucket that will NOT be deleted when the stack is deleted. You will be billed for the AWS resources used if you create a stack from this template.",
            "CreationTime": "2020-05-05T14:43:49Z",
            "StackStatus": "CREATE_COMPLETE"
        }
    ]
}
```

## Expected behavior

Delete the stack

## Actual behavior

`An error occurred (502) when calling the DeleteStack operation (reached max retries: 4): Bad Gateway`

# Steps to reproduce

- Create a stack
- Delete the stack

## Command used to start LocalStack
localstack start

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

- aws --profile=personal --endpoint-url=http://localhost:4581 cloudformation create-stack --stack-name myteststack2 --template-body file://cft.json
-  aws --profile=personal --endpoint-url=http://localhost:4581 cloudformation delete-stack --stack-name myteststack2

**Comment by whummer** [comment]
Thanks for reporting @ebalakumar . Still haven't been able to reproduce this, unfortunately. A simple integration test has been added in #2614 to cover this functionality. Can you please pull the `latest` Docker image and verify if the problem still persists. Thanks!
