### ISSUE TITLE
S3 about multipart upload throws 500 instead of 404 for a bad upload ID

### ISSUE THREAD

**Issue by efenderbosch** [localstack/localstack#2401]
# Type of request: Bug Report

# Detailed description
S3 Abort Multipart Upload throws 500 instead of 404 when the key and/or upload-id is invalid.

## Expected behavior
Match the behavior of the official S3 API, returning 404.

## Actual behavior
Throws 500.

# Steps to reproduce
Running against official S3 service:
``aws s3api abort-multipart-upload --bucket foo --key bar --upload-id baz``

```An error occurred (NoSuchUpload) when calling the AbortMultipartUpload operation: The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.```

Running against Localstack:
``aws s3api abort-multipart-upload --bucket foo --key bar --upload-id baz --endpoint-url=http://localstack:4566``

```An error occurred (500) when calling the AbortMultipartUpload operation (reached max retries: 2): Internal Server Error```

If there is an upload for the key and the correct upload-id is submitted, then it performs the abort multipart upload correctly.

## Command used to start LocalStack
docker-compose
```
localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      SERVICES: s3
      DEBUG: 1
```

## Traceback
``` 2020-05-06 18:57:55,840:API: Error on request:
 Traceback (most recent call last):
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
     execute(self.server.app)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
     application_iter = app(environ, start_response)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 163, in __call__
     return backend_app(environ, start_response)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
     return self.wsgi_app(environ, start_response)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
     response = self.handle_exception(e)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
     return cors_after_request(app.make_response(f(*args, **kwargs)))
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
     reraise(exc_type, exc_value, tb)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
     raise value
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
     response = self.full_dispatch_request()
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
     return cors_after_request(app.make_response(f(*args, **kwargs)))
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
     raise value
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
     rv = self.dispatch_request()
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 146, in __call__
     result = self.callback(request, request.url, {})
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 912, in key_or_control_response
     response = self._key_response(request, full_url, headers)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1065, in _key_response
     return self._key_response_delete(bucket_name, query, key_name)
   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 149, in s3_key_response_delete
     result = s3_key_response_delete_orig(bucket_name, query, key_name, *args, **kwargs)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1556, in _key_response_delete
     self.backend.cancel_multipart(bucket_name, upload_id)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/models.py", line 1481, in cancel_multipart
     del bucket.multiparts[multipart_id]
 KeyError: 'baz'
```

**Comment by whummer** [comment]
Thanks for reporting this issue @efenderbosch . This should be fixed in the meantime, can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Comment by efenderbosch** [comment]
Working as expect now, thanks!

**Comment by TheCanay** [comment]
Experiencing same issue now while uploading 5.4 gb What can I do with this?

my docker-compose.yml file:

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=s3, s3api, cloudwatch, logs, lambda
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobaraccess

    volumes:
      - "aws-volume:/tmp/localstack"
      - "aws-sock:/var/run/docker.sock"
      - "aws-bin:/docker-entrypoint-initaws.d"

volumes:
  aws-volume:
  aws-sock:
  aws-bin:
