### ISSUE TITLE
localstack does not comply with amazon S3 HTTP URL

### ISSUE THREAD

**Issue by yamil-rivera** [localstack/localstack#2413]
This is a bug report.

# Detailed description
I'm using the Amazon Java SDK to retrieve objects from a certain bucket. The SDK works fine when making a request to amazon but isn't working properly when talking to localstack. It appears that the Amazon API for S3 is of the form: 

https://{bucket-name}.{amazon-domain}/

For my use case, I'm running both the client and localstack in the same docker network called `flowable`. I tried also accessing localstack with the client running directly on the host and I get the exact same error. (Just replace `flowable.localstack` with `flowable.localhost` in the logs)

## Expected behavior
The Amazon Java SDK should retrieve my object from my bucket in localstack.

## Actual behavior
I'm getting a java.net.UnknownHostException exception and these are the logs:

`2020-05-11 11:29:01.237 DEBUG 46 --- [nio-443-exec-10] com.amazonaws.request                    : Sending Request: GET http://flowable.localstack:4566 /local/omc-provisioning.p12 Headers: (amz-sdk-invocation-id: 932b1c01-eb5d-a8e3-9902-ee5f2225f902, Content-Type: application/octet-stream, User-Agent: aws-sdk-java/1.11.774 Linux/4.19.76-linuxkit OpenJDK_64-Bit_Server_VM/25.242-b08 java/1.8.0_242 groovy/3.0.2 vendor/Amazon.com_Inc., ) 
2020-05-11 11:29:01.244 DEBUG 46 --- [nio-443-exec-10] com.amazonaws.auth.AWS4Signer            : AWS4 Canonical Request: '"GET
/local/omc-provisioning.p12

amz-sdk-invocation-id:932b1c01-eb5d-a8e3-9902-ee5f2225f902
amz-sdk-request:attempt=1;max=4
amz-sdk-retry:0/0/485
content-type:application/octet-stream
host:flowable.localstack:4566
user-agent:aws-sdk-java/1.11.774 Linux/4.19.76-linuxkit OpenJDK_64-Bit_Server_VM/25.242-b08 java/1.8.0_242 groovy/3.0.2 vendor/Amazon.com_Inc.
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20200511T152901Z

amz-sdk-invocation-id;amz-sdk-request;amz-sdk-retry;content-type;host;user-agent;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
20200511T152901Z
20200511/us-east-1/s3/aws4_request
11175386044168f212ef34e8ccb79c003cad3fd70d889e141b3756e1981afeda"
2020-05-11 11:29:01.257 DEBUG 46 --- [nio-443-exec-10] o.a.h.client.protocol.RequestAddCookies  : CookieSpec selected: default
2020-05-11 11:29:01.257 DEBUG 46 --- [nio-443-exec-10] o.a.h.client.protocol.RequestAuthCache   : Auth cache not set in the context
2020-05-11 11:29:01.260 DEBUG 46 --- [nio-443-exec-10] h.i.c.PoolingHttpClientConnectionManager : Connection request: [route: {}->http://flowable.localstack:4566][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
2020-05-11 11:29:01.262 DEBUG 46 --- [nio-443-exec-10] h.i.c.PoolingHttpClientConnectionManager : Connection leased: [id: 4][route: {}->http://flowable.localstack:4566][total kept alive: 0; route allocated: 1 of 50; total allocated: 1 of 50]
2020-05-11 11:29:01.262 DEBUG 46 --- [nio-443-exec-10] o.a.http.impl.execchain.MainClientExec   : Opening connection {}->http://flowable.localstack:4566
2020-05-11 11:29:01.287 DEBUG 46 --- [nio-443-exec-10] c.a.h.c.ClientConnectionManagerFactory   : 

java.lang.reflect.InvocationTargetException: null
...
Caused by: **java.net.UnknownHostException: flowable.localstack: Name or service not known**
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_242]
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[na:1.8.0_242]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[na:1.8.0_242]
        at java.net.InetAddress.getAllByName0(InetAddress.java:1277) ~[na:1.8.0_242]
        at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[na:1.8.0_242]
        at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[na:1.8.0_242]
        at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27) ~[aws-java-sdk-core-1.11.774.jar!/:na]
        at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38) ~[aws-java-sdk-core-1.11.774.jar!/:na]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.10.jar!/:4.5.10]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374) ~[httpclient-4.5.10.jar!/:4.5.10]
        ... 137 common frames omitted`

# Steps to reproduce
Create a bucket and object on localstack using:
`aws s3 mb s3://flowable --endpoint-url=http://localhost:4566`
`aws s3 cp <my-file> s3://flowable/<my-file> --endpoint-url=http://localhost:4566`

Use the amazon Java SDK version 1.11.774 to try to retrieve it. Exact configuration code in the section below.

## Command used to start LocalStack
`docker run -e SERVICES=s3,secretsmanager -e DEFAULT_REGION=us-east-1 -p 4566:4566 --network=flowable --name=localstack localstack/localstack-light`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
`public AmazonS3 amazonS3LocalStack() {
	return AmazonS3ClientBuilder.standard()
			.withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localstack:4566", "us-east-1"))
			.withCredentials(new DefaultAWSCredentialsProviderChain())
			.build();
}`

**Comment by whummer** [comment]
Thanks for reporting @yamil-rivera - can you please try enabling _path-style addressing_ in your client SDK - see also the Troubleshooting section in the README. Thanks

**Comment by yamil-rivera** [comment]
That one did the trick! Thank you very much for the quick and effective answer. I had a hard time finding that configuration. I'm assuming localstack will not be supporting the SDK default addressing style so I'm closing this one as it is not an issue.
