### ISSUE TITLE
Unable to create python lambda functions that use pip installed modules

### ISSUE THREAD

**Issue by hjb417** [localstack/localstack#2414]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

I get the error when uploading a lambda that uses pip installed packages (The pip installed packages are included in the zip file I upload). It also looks like it's trying to invoke the lambda when creating it.
[replicate.py.txt](https://github.com/localstack/localstack/files/4610575/replicate.py.txt)

## Expected behavior

The lambda function to be created

## Actual behavior
```
Traceback (most recent call last):
  File "C:\dev\leo\pipelines\replicate.py", line 77, in <module>
    main()
  File "C:\dev\leo\pipelines\replicate.py", line 73, in main
    output = lambda_client.invoke(FunctionName="invoke")
  File "C:\dev\leo\pipelines\env\lib\site-packages\botocore\client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\dev\leo\pipelines\env\lib\site-packages\botocore\client.py", line 586, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InternalFailure) when calling the Invoke operation (reached max retries: 4): Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:invoke: No module named 'rx' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 488, in run_lambda
    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 133, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 120, in do_execute
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 108, in do_execute
    result = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 671, in _execute
    process.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 666, in do_execute
    result = lambda_function(event, context)
  File "/tmp/localstack/lambda_script_l_b27314da.py", line 9, in invoke
    from rx import operators, from_iterable
ModuleNotFoundError: No module named 'rx'
```

# Steps to reproduce

Run the below python script (you need to copy paste to a file but I also upload it to this ticket). It will create a zip file with the rx module and use it to create a lambda function.

```python
import os
import venv
import uuid
import subprocess
import logging as log
from pathlib import Path

def invoke(event, context):
    log.info(f"*******STARTING*******")
    from rx import operators, from_iterable
    items = from_iterable([4, 5, 6])
    first = items.pipe(operators.first()).run()
    log.info(f"*******ENDING*******")
    return first

def read_all_bytes(path: str):
    with open(path, "rb") as src:
        return src.read()

def make_tmp_file() -> str:
    tmp_dir = get_tmp_dir()
    tmp_dir = os.path.join(tmp_dir, f"{uuid.uuid4()}.tmp")
    return tmp_dir

def get_root_dir() -> str:
    root_dir = os.path.dirname(os.path._getfullpathname(__file__))
    root_dir = os.path.abspath(root_dir)
    return root_dir

def get_tmp_dir() -> str:
    root_dir = get_root_dir()
    tmp_dir = os.path.join(root_dir, "tmp")
    return tmp_dir

def make_tmp_dir() -> str:
    tmp_dir = get_tmp_dir()
    tmp_dir = os.path.join(tmp_dir, str(uuid.uuid4()))
    os.mkdir(tmp_dir)
    return tmp_dir

def create_virtual_env() -> str:
    env_dir = make_tmp_dir()
    venv.create(env_dir=env_dir, with_pip=True)
    return env_dir

def pip_install_rx(env_dir: str, dest_dir: str) -> str:
    python_file_path = os.path.join(env_dir, "Scripts", "python")
    pip_install_args = [python_file_path, "-u", "-m", "pip", "install", "--no-cache-dir", "rx", "-t", dest_dir]
    subprocess.check_call(pip_install_args)

def main():
    log.info(f"CREATING LAMBDA")
    import boto3
    import gzip
    import zipfile
    import shutil

    lambda_client = boto3.client("lambda", aws_access_key_id="a", aws_secret_access_key="a", endpoint_url="http://localhost:4566", region_name="us-east-1")

    # create tmp dir to make zip file
    lambda_code_dir = make_tmp_dir()
    shutil.copy(__file__, lambda_code_dir)

    # pip install rx module
    env_dir = create_virtual_env()
    pip_install_rx(env_dir, lambda_code_dir)
    
    code_zip_file = make_tmp_file()
    code_zip_file = shutil.make_archive(code_zip_file, "zip", lambda_code_dir)
    zipped_code = read_all_bytes(code_zip_file)

    try:
       lambda_client.delete_function(FunctionName="invoke")
    except:
        pass
    
    handler = f"{Path(__file__).stem}.invoke"
    func = lambda_client.create_function(FunctionName="invoke", Runtime="python3.8", Role="lambda_executor", Handler=handler, Code={"ZipFile": zipped_code})
    del func["ResponseMetadata"] 
    output = lambda_client.invoke(FunctionName="invoke")
    print(output)

if __name__ == "__main__":
    main()
```

## Command used to start LocalStack

docker container rm localstack -f
docker image rm localstack -f
docker pull localstack/localstack
docker run -d -p "4566-4599:4566-4599" -p "8080:8080" --name localstack localstack/localstack
docker logs -f localstack

**Comment by whummer** [comment]
Thanks for reporting @hjb417 . This should be fixed in f23eec4481a2726f71fc3422fc5908ed86464b19 - can you please give it another try with the `latest` version of the Docker image? Please report here if the problem persists.

Note that if you use the `docker run ...` command as above, the `local` Lambda executor is used (not the Docker-based executor, which is the recommended option). The recommended way to start up is by using the command line `localstack start`, which will set a couple of additional Docker flags and will allow LocalStack to run Lambdas inside Docker containers.
