### ISSUE TITLE
cloudformation create-stack failed to satisfy regular expression pattern ARN

### ISSUE THREAD

**Issue by mzavaletavargas** [localstack/localstack#2431]
# Type of request: 

[ x ] bug report

# Detailed description
I would like to create a local environment for lambdas that includes api gateway, respective roles (dummies), and test it locally.

I created a role because I was getting an error for not send it or putting a random name.

## Expected behavior
Cloud Formation create stack. 

## Actual behavior

Fails to create due to regular expression pattern error

# Steps to reproduce

## Command used to start LocalStack

1. I created an s3 locally `locals3` and upload a `cloudformation.yml` file.
file:
```
AWSTemplateFormatVersion: 2010-09-09
Description: My description

Resources:
  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs10.x
      Handler: index.handler
      Role: arn:aws:iam::000000000000:role/lambda-ex
      Code:
        ZipFile: |
          // inline code sample
          var aws = require('aws-sdk')
          var response = require('cfn-response')
          exports.handler = function(event, context) {
              var responseStatus = "FAILED"
              var responseData = {}
              response.send(event, context, responseStatus, responseData)
          }
```

2. I create a role using the following command

```
awslocal iam create-role --role-name lambda-ex --assume-role-policy-document '{"Version": "2012-10-17","Statement": [{ "Effect": "Allow", "Principal": {"Service": "lambda.amazonaws.com"}, "Action": "sts:AssumeRole"}]}'
```
Result:
```
{
    "Role": {
        "Path": "/",
        "RoleName": "lambda-ex",
        "RoleId": "7dpa5a4c4679ytt94a2n",
        "Arn": "arn:aws:iam::000000000000:role/lambda-ex",
        "CreateDate": "2020-05-15T23:16:08.817Z",
        "AssumeRolePolicyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {
                        "Service": "lambda.amazonaws.com"
                    },
                    "Action": "sts:AssumeRole"
                }
            ]
        },
        "MaxSessionDuration": 3600
    }
}
```

3. Once everything is created I run `create-stack`:
```
awslocal cloudformation create-stack --stack-name example --template-body http://localhost:4572/locals3/cloudformation.yml --stack-name single-instance
```
Error:
```
Unable to parse response (syntax error: line 1, column 0), invalid XML received. Further retries may succeed:
b"1 validation error detected: Value 'arn:aws:iam:123456789012:role/lambda-ex' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws[a-zA-Z-]*)?:iam::(\\d{12}):role/?[a-zA-Z_0-9+=,.@\\-_/]+"
```

Debug:

``` 2020-05-15T18:23:34:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "lambdaFunction": An error occurred (ValidationException) when calling the None operation: 1 2validation error detected: Value 'arn:aws:iam:123456789012:role/lambda-ex' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws[a-zA-Z-]*)?:iam::(\d{12}):role/?[a-zA-Z_0-9+=,.@\-_/]+ Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/localstack/services/cloudformation/cloudformation_starter.py", line 202, in parse_and_create_resource
    logical_id, resource_json, resources_map, region_name, force_create=force_create
  File "/usr/local/lib/python3.7/site-packages/localstack/services/cloudformation/cloudformation_starter.py", line 282, in _parse_and_create_resource
    raise moto_create_error
  File "/usr/local/lib/python3.7/site-packages/localstack/services/cloudformation/cloudformation_starter.py", line 268, in _parse_and_create_resource
    logical_id, resource_json_arns_fixed, resources_map, region_name
  File "/usr/local/lib/python3.7/site-packages/moto/cloudformation/parsing.py", line 346, in parse_and_create_resource
    resource_name, resource_json, region_name
  File "/usr/local/lib/python3.7/site-packages/localstack/services/cloudformation/cloudformation_starter.py", line 617, in Lambda_create_from_cloudformation_json
    return Lambda_create_from_cloudformation_json_orig(resource_name, cloudformation_json, region_name)
  File "/usr/local/lib/python3.7/site-packages/moto/awslambda/models.py", line 516, in create_from_cloudformation_json
    fn = backend.create_function(spec)
  File "/usr/local/lib/python3.7/site-packages/moto/awslambda/models.py", line 824, in create_function
    self._lambdas.put_function(fn)
  File "/usr/local/lib/python3.7/site-packages/moto/awslambda/models.py", line 698, in put_function
    raise InvalidRoleFormat(fn.role)
moto.awslambda.exceptions.InvalidRoleFormat: An error occurred (ValidationException) when calling the None operation: 1 2validation error detected: Value 'arn:aws:iam:123456789012:role/lambda-ex' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws[a-zA-Z-]*)?:iam::(\d{12}):role/?[a-zA-Z_0-9+=,.@\-_/]+

2020-05-15T18:23:34:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "CreateStack" (400) POST /: b"1 2validation error detected: Value 'arn:aws:iam:123456789012:role/lambda-ex' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws[a-zA-Z-]*)?:iam::(\\d{12}):role/?[a-zA-Z_0-9+=,.@\\-_/]+"
```
Observations: arn is changing

## Versions
`localstack: 0.11.1.1` installed via `pip3`
using awslocal 
`aws-cli/1.18.60 Python/3.7.6 Darwin/18.7.0 botocore/1.16.10`

**Comment by whummer** [comment]
Thanks for reporting @mzavaletavargas . This should be fixed in the meantime - can you please do a `docker pull localstack/localstack` and give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks!
