### ISSUE TITLE
Issues starting localstack with dynamodb, s3 or kinesis on Linux

### ISSUE THREAD

**Issue by mrangel** [localstack/localstack#2457]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
Evaluating the Pro version for work and personal use, I have found that I cannot get localstack to run on my machine (specs below). Running `localstack start` hangs on creating certain services. I have noticed the same behavior with at least 3 services (dynamodb, kinesis and s3). I have tried running localstack with `serverless-localstack`, `localstack start` and `docker-compose`

Python 3.7.7
Localstack 0.11.1.1
localstack/localstack:latest  (87885e6f2e37)
$ cat /etc/os-release

NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
<snip>

...

## Expected behavior
Expect all services to run (checking /health endpoint or trying to access them with awslocal), looking at https://app.localstack.cloud/resources if any resources are created, but nothing shows up.

...

## Actual behavior
```
$ localstack start                                    
LocalStack version: 0.11.1.1
Starting local dev environment. CTRL-C to quit.
ERROR: 'chmod -R 777 "/tmp/localstack"': exit code 1; output: b"chmod: changing permissions of '/tmp/localstack': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/sqs.63ae6ccd.conf': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/sqs.c6b16e13.conf': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/sqs.31cc0a13.conf': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/server.test.pem.crt': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/server.test.pem.key': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/server.test.pem': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/.localstack': Operation not permitted\n"
docker run -it -e HOSTNAME="localhost.localdomain" -e TEST_AWS_ACCOUNT_ID="000000000000" -e DEFAULT_REGION="us-east-1" -e LOCALSTACK_HOSTNAME="localhost.localdomain" --rm --privileged --name localstack_main -p 8080-8081:8080-8081 -p 4567-4620:4567-4620 -p 12121:12121  -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack" 
Waiting for all LocalStack services to be ready
2020-05-26 15:25:44,855 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-05-26 15:25:44,859 INFO supervisord started with pid 13
2020-05-26 15:25:45,861 INFO spawned: 'dashboard' with pid 19
2020-05-26 15:25:45,863 INFO spawned: 'infra' with pid 20
2020-05-26 15:25:45,869 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; bin/localstack web)
(. .venv/bin/activate; exec bin/localstack start --host)
2020-05-26 15:25:46,872 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for all LocalStack services to be ready
LocalStack version: 0.11.1
LocalStack version: 0.11.1
Starting local dev environment. CTRL-C to quit.
2020-05-26T15:25:55:INFO:localstack.utils.common: Unable to store key/cert files for custom SSL certificate: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem.key'
2020-05-26T15:25:56:INFO:localstack_ext.bootstrap.install: Unable to download local test SSL certificate: MyHTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /localstack/localstack-artifacts/raw/master/local-certs/server.key (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4f74a0d130>: Failed to establish a new connection: [Errno -3] Try again'))
Waiting for all LocalStack services to be ready
Starting edge router (https port 4566)...
Starting mock API Gateway service in http ports 4566 (recommended) and 4567 (deprecated)...
2020-05-26T15:26:02:INFO:localstack.multiserver: Starting multi API server process on port 42361
Starting mock CloudFormation service in http ports 4566 (recommended) and 4581 (deprecated)...
Starting mock CloudWatch service in http ports 4566 (recommended) and 4582 (deprecated)...
Starting mock DynamoDB service in http ports 4566 (recommended) and 4569 (deprecated)...
Starting mock DynamoDB Streams service in http ports 4566 (recommended) and 4570 (deprecated)...
Starting mock EC2 service in http ports 4566 (recommended) and 4597 (deprecated)...
Starting mock ES service in http ports 4566 (recommended) and 4578 (deprecated)...
Starting mock Firehose service in http ports 4566 (recommended) and 4573 (deprecated)...
Starting mock IAM service in http ports 4566 (recommended) and 4593 (deprecated)...
Starting mock STS service in http ports 4566 (recommended) and 4592 (deprecated)...
Starting mock Kinesis service in http ports 4566 (recommended) and 4568 (deprecated)...
Starting mock KMS service in http ports 4566 (recommended) and 4599 (deprecated)...
Starting mock Lambda service in http ports 4566 (recommended) and 4574 (deprecated)...
Starting mock CloudWatch Logs service in http ports 4566 (recommended) and 4586 (deprecated)...
Starting mock Redshift service in http ports 4566 (recommended) and 4577 (deprecated)...
Starting mock Route53 service in http ports 4566 (recommended) and 4580 (deprecated)...
Starting mock S3 service in http ports 4566 (recommended) and 4572 (deprecated)...
Starting mock Secrets Manager service in http ports 4566 (recommended) and 4584 (deprecated)...
Starting mock SES service in http ports 4566 (recommended) and 4579 (deprecated)...
Starting mock SNS service in http ports 4566 (recommended) and 4575 (deprecated)...
Starting mock SQS service in http ports 4566 (recommended) and 4576 (deprecated)...
Starting mock SSM service in http ports 4566 (recommended) and 4583 (deprecated)...
Starting mock Cloudwatch Events service in http ports 4566 (recommended) and 4587 (deprecated)...
Starting mock StepFunctions service in http ports 4566 (recommended) and 4585 (deprecated)...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2020-05-26T15:27:24:WARNING:localstack.services.plugins: Service "dynamodb" not yet available, retrying...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2020-05-26T15:28:43:WARNING:localstack.services.plugins: Service "dynamodb" not yet available, retrying...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready

```

Eventually I get this error:
During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/plugins.py", line 94, in check_infra
    check_service_health(api=name, print_error=print_error)
  File "/opt/code/localstack/localstack/services/plugins.py", line 113, in check_service_health
    raise e
  File "/opt/code/localstack/localstack/services/plugins.py", line 109, in check_service_health
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/plugins.py", line 45, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_starter.py", line 32, in check_dynamodb
    assert isinstance(out['TableNames'], list)
TypeError: 'NoneType' object is not subscriptable

```

...

# Steps to reproduce
Run `localstack start`

## Command used to start LocalStack
`localstack start`
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-187) by [Unito](https://www.unito.io/learn-more)

**Comment by mrangel** [comment]
I just tried to run localstack on a fresh Ubuntu VM and it seems to start just fine. Perhaps it's an issue with Fedora or something else in my environment?

Python 3.8.2
Localstack 0.11.2
localstack/localstack:latest (93771078243b)
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

It seems like localstack and the image have been updated, I will run this on my Fedora host and post an update.

Command:
`SERVICES=edge,dynamodb,s3,serverless DEBUG=1 localstack start`
localstack/localstack:latest 93771078243b

**Comment by mrangel** [comment]
I have updated Fedora to the new localstack image and binary. I still have the same issue.

Command:
`SERVICES=edge,dynamodb,s3,serverless DEBUG=1 localstack start`

I did compare the output between my working Ubuntu VM and my Fedora host of the same command and found this piece different between the two (present in Fedora, but not Ubuntu):

```
INFO:localstack.utils.common: Unable to store key/cert files for custom SSL certificate: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem.key' |   |   |  
-- | -- | -- | --
  | 29 | 2020-05-27T20:45:36:INFO:localstack_ext.bootstrap.install: Unable to download local test SSL certificate: MyHTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /localstack/localstack-artifacts/raw/master/local-certs/server.key (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe7f6194610>: Failed to establish a new connection: [Errno -3] Try again')) |   |   |  
```
And on Fedora:
```
ERROR: 'chmod -R 777 "/tmp/localstack"': exit code 1; output: b"chmod: changing permissions of '/tmp/localstack': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/sqs.c13d90e7.conf': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/sqs.069a9884.conf': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/sqs.63ae6ccd.conf': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/sqs.c6b16e13.conf': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/sqs.31cc0a13.conf': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/server.test.pem.crt': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/server.test.pem.key': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/server.test.pem': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/.localstack': Operation not permitted\n"
```
VS Ubuntu
```
ERROR: 'chmod -R 777 "/tmp/localstack"': exit code 1; output: b"chmod: changing permissions of '/tmp/localstack/server.test.pem.crt': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/.localstack': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/server.test.pem.key': Operation not permitted\nchmod: changing permissions of '/tmp/localstack/server.test.pem': Operation not permitted\n"
--
```

**Comment by han-so1omon** [comment]
@mrangel Do you know what that error about changing permissions means for the execution environment?

**Comment by mrangel** [comment]
@han-so1omon I don't have a clue as to the source of the error nor the effect. At this point I'm stumped, I've updated my localstack binaries and images, to no avail.

**Comment by han-so1omon** [comment]
ok. I assume that the error is taking place within the mounted localstack container, which would mean that the localstack user is not root and otherwise does not have file modification permissions for the /tmp/localstack folder. Have you tried starting through docker-compose.yml?

some people were saying in other threads that reverting to v0.19 solved some possibly related issues, which is the version from late 2019 I believe.

**Comment by mrangel** [comment]
I dont have selinux issues. Firewall maybe, but IDK where to start with that.

As for the docker-compose route, we may have some traction there:

```
WARNING: The TMPDIR variable is not set. Defaulting to a blank string.
Creating test_localstack_1 ... done
Waiting for all LocalStack services to be ready
2020-05-30 04:07:33,599 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-05-30 04:07:33,602 INFO supervisord started with pid 13
2020-05-30 04:07:34,607 INFO spawned: 'dashboard' with pid 19
2020-05-30 04:07:34,612 INFO spawned: 'infra' with pid 20
(. .venv/bin/activate; bin/localstack web)
2020-05-30 04:07:34,620 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; exec bin/localstack start --host)
2020-05-30 04:07:35,622 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for all LocalStack services to be ready
2020-05-30T04:07:46:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext": <function register_localstack_commands at 0x7fbfd66de550>
LocalStack version: 0.11.2
LocalStack version: 0.11.2
Starting local dev environment. CTRL-C to quit.
2020-05-30T04:07:46:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext": <function register_localstack_commands at 0x7f9916c13550>
2020-05-30T04:07:46:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7fbfd6a8e3a0>
2020-05-30T04:07:46:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7fbfd6a8e1f0>
!WARNING! - Looks like you have configured $LAMBDA_REMOTE_DOCKER=1 - please make sure to configure $HOST_TMP_FOLDER to point to your host's $TMPDIR
2020-05-30T04:07:46:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7f9916fc33a0>
Waiting for all LocalStack services to be ready
2020-05-30T04:07:51:INFO:localstack_ext.bootstrap.install: Unable to download local test SSL certificate: MyHTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /localstack/localstack-artifacts/raw/master/local-certs/server.key (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9916730670>: Failed to establish a new connection: [Errno -3] Try again'))
Waiting for all LocalStack services to be ready
2020-05-30T04:07:56:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f9916fc31f0>
2020-05-30T04:08:00:DEBUG:bootstrap.py: Plugin loading took 13.54987382888794 sec
Waiting for all LocalStack services to be ready
Starting edge router (https port 4566)...
Starting mock API Gateway service in http ports 4566 (recommended) and 4567 (deprecated)...
2020-05-30T04:08:02:INFO:localstack.multiserver: Starting multi API server process on port 40659
Starting mock CloudFormation service in http ports 4566 (recommended) and 4581 (deprecated)...
2020-05-30 04:08:03,305:API:  * Running on http://0.0.0.0:55073/ (Press CTRL+C to quit)
2020-05-30 04:08:03,305:API:  * Running on http://0.0.0.0:55073/ (Press CTRL+C to quit)
2020-05-30 04:08:03,305:API:  * Running on http://0.0.0.0:55073/ (Press CTRL+C to quit)
Starting mock CloudWatch service in http ports 4566 (recommended) and 4582 (deprecated)...
Starting mock DynamoDB service in http ports 4566 (recommended) and 4569 (deprecated)...
Starting mock DynamoDB Streams service in http ports 4566 (recommended) and 4570 (deprecated)...
Starting mock EC2 service in http ports 4566 (recommended) and 4597 (deprecated)...
Starting mock ES service in http ports 4566 (recommended) and 4578 (deprecated)...
Starting mock Firehose service in http ports 4566 (recommended) and 4573 (deprecated)...
Starting mock IAM service in http ports 4566 (recommended) and 4593 (deprecated)...
Starting mock STS service in http ports 4566 (recommended) and 4592 (deprecated)...
Starting mock Kinesis service in http ports 4566 (recommended) and 4568 (deprecated)...
Starting mock KMS service in http ports 4566 (recommended) and 4599 (deprecated)...
Starting mock Lambda service in http ports 4566 (recommended) and 4574 (deprecated)...
Starting mock CloudWatch Logs service in http ports 4566 (recommended) and 4586 (deprecated)...
Starting mock Redshift service in http ports 4566 (recommended) and 4577 (deprecated)...
Starting mock Route53 service in http ports 4566 (recommended) and 4580 (deprecated)...
Starting mock S3 service in http ports 4566 (recommended) and 4572 (deprecated)...
Starting mock Secrets Manager service in http ports 4566 (recommended) and 4584 (deprecated)...
Starting mock SES service in http ports 4566 (recommended) and 4579 (deprecated)...
INFO[2020-05-30 04:08:03.586] No file found at path /init/seed.yaml; skipping seeding.
INFO[2020-05-30 04:08:03.586] Data will be stored in /tmp/local-kms
INFO[2020-05-30 04:08:03.586] Local KMS started on 0.0.0.0:48563
Starting mock SNS service in http ports 4566 (recommended) and 4575 (deprecated)...
Starting mock SQS service in http ports 4566 (recommended) and 4576 (deprecated)...
Initializing DynamoDB Local with the following configuration:
Port:	38629
InMemory:	true
DbPath:	null
SharedDb:	true
shouldDelayTransientStatuses:	false
CorsParams:	*
Starting mock SSM service in http ports 4566 (recommended) and 4583 (deprecated)...
Listening at http://:::35895

Starting mock Cloudwatch Events service in http ports 4566 (recommended) and 4587 (deprecated)...
Starting mock StepFunctions service in http ports 4566 (recommended) and 4585 (deprecated)...
2020-05-30 04:08:03,354:API:  * Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
2020-05-30 04:08:03,354:API:  * Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
2020-05-30 04:08:03,354:API:  * Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
2020-05-30 04:08:03,376:API:  * Running on http://0.0.0.0:45501/ (Press CTRL+C to quit)
2020-05-30 04:08:03,376:API:  * Running on http://0.0.0.0:45501/ (Press CTRL+C to quit)
2020-05-30 04:08:03,376:API:  * Running on http://0.0.0.0:45501/ (Press CTRL+C to quit)
Step Functions Local
Version: 1.5.1
Build: 2020-05-20
2020-05-30 04:08:04.428: Configure [Account] to [000000000000]
2020-05-30 04:08:04.430: Configure [Region] to [us-east-1]
2020-05-30 04:08:04.430: Configure [Lambda Endpoint] to [http://localhost:4574]
2020-05-30 04:08:04.431: Configure [DynamoDB Endpoint] to [http://localhost:4569]
2020-05-30 04:08:04.432: Configure [SQS Endpoint] to [http://localhost:4576]
2020-05-30 04:08:04.432: Configure [SNS Endpoint] to [http://localhost:4575]
2020-05-30 04:08:04.433: Configure [Step Functions Endpoint] to [http://localhost:4585]
2020-05-30 04:08:04.443: Loaded credentials from environment
2020-05-30 04:08:04.443: Starting server on port 8083 with account 000000000000, region us-east-1
04:08:05.097 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.15.5) ...
May 30, 2020 4:08:05 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
May 30, 2020 4:08:05 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
May 30, 2020 4:08:05 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
May 30, 2020 4:08:05 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
May 30, 2020 4:08:05 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
May 30, 2020 4:08:05 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
May 30, 2020 4:08:05 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
May 30, 2020 4:08:05 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
May 30, 2020 4:08:06 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
04:08:06.119 [elasticmq-akka.actor.default-dispatcher-6] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
04:08:07.328 [elasticmq-akka.actor.default-dispatcher-7] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:50295, visible server address http://localhost:4576
04:08:07.329 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.15.5) started in 3462 ms ===
Waiting for all LocalStack services to be ready
Ready.

```
Services report as `Ready` according to the logs, but I cannot seem to get to the health page now on localhost. Furthermore, no startup events are being reported on https://app.localstack.cloud/dashboard

**Comment by mrangel** [comment]
@han-so1omon After restarting my machine, I was able to get my `health` page up when running via docker-compose. The only service NOT available is Edge, so the dashboard isn't getting any feedback. I am going to try and see if I can deploy serverless to my container and see how that goes, however, I presume that to use the Pro features, we need edge up and running.

**Comment by fredliporace** [comment]
having the same issue here with CentOS8, downgraded to 0.9.6 and the services started.

**Comment by srp** [comment]
I'm having the same problem. Was working fine with localstack 0.11.2, but 0.11.3 and 0.11.4 won't. Running Fedora 32, but just installed OpenSuse leap 15.2 on another laptop and it's hitting this same problem.

**Comment by jchanam** [comment]
I'm facing the same issue.

I'm using localstack docker image on Kubernetes: `localstack/localstack:0.12.2` with the services `kinesis,dynamodb,s3,sqs`

**Comment by mikekauffman** [comment]
Facing the same issue. Pasted logs here: https://github.com/localstack/localstack/issues/808#issuecomment-811117474

**Comment by elizeire** [comment]
Same issue here, but for s3 service...

![image](https://user-images.githubusercontent.com/1172098/116058334-041d8400-a680-11eb-91fe-cf39a4dc1987.png)

**Comment by whummer** [comment]
Thanks all for reporting. Regarding the S3 issue - can you please double-check if the `mybucket.s3.localhost.localstack.cloud` hostname resolves on your machine @elizeire ? Thanks

We have recently reworked the entire service lifecycle, and startup of the different services has (hopefully) become much more stable in the meantime. We'll continue to invest time and effort to make things even more reliable and to further improve the startup performance. Please let us know if the problem persists.. Thanks!
