### ISSUE TITLE
Trying to show a lambda function's code in the web ui yields an error

### ISSUE THREAD

**Issue by tobilg** [localstack/localstack#249]
When I select the lambda function and then on the right-hand menu click on "show code", I see the following error in the localstack logs:

```bash
localstack_1  | 2017-08-18T13:21:12:INFO:werkzeug: 172.18.0.1 - - [18/Aug/2017 13:21:12] "POST /lambda/helloworld/code HTTP/1.1" 500 -
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
localstack_1  |     return self.wsgi_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
localstack_1  |     response = self.make_response(self.handle_exception(e))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
localstack_1  |     response = self.full_dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
localstack_1  |     rv = self.handle_user_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
localstack_1  |     rv = self.dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
localstack_1  |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  |   File "/opt/code/localstack/localstack/dashboard/api.py", line 74, in get_lambda_code
localstack_1  |     return jsonify(result)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/json.py", line 238, in jsonify
localstack_1  |     indent=indent),
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/json.py", line 126, in dumps
localstack_1  |     rv = _json.dumps(obj, **kwargs)
localstack_1  |   File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
localstack_1  |     sort_keys=sort_keys, **kw).encode(obj)
localstack_1  |   File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
localstack_1  |     chunks = list(chunks)
localstack_1  |   File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
localstack_1  |     for chunk in _iterencode_dict(o, _current_indent_level):
localstack_1  |   File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
localstack_1  |     yield _encoder(value)
localstack_1  | UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 37: invalid start byte
```

**Comment by whummer** [comment]
Thanks for reporting @tobilg . Can you please provide a test lambda archive to reproduce the error? Please note that this feature currently works only for Lambda zip archives that contain text files _only_ (e.g., Python or Node.js source files).
