### ISSUE TITLE
generic_proxy exception when sends message to SQS

### ISSUE THREAD

**Issue by drizzef** [localstack/localstack#2516]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
OS: macOS Catalina 10.15.4
Machine: Macbook Pro

I'm using the Docker version on development environment and after creating queues with `awslocal` successfully i tried to send a new message to the queue with the following URL: 
`http://localhost:4576/queue/links` but i got the following error and 502 error code on the response without any message:  
```
localstack_main | 2020-06-05T10:08:25:ERROR:localstack.services.generic_proxy: Error forwarding request: Failed to parse: http://7511408c7e52:4576%27%20 Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 380, in prepare_url
localstack_main |     scheme, auth, host, port, path, query, fragment = parse_url(url)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/url.py", line 392, in parse_url
localstack_main |     return six.raise_from(LocationParseError(source_url), None)
localstack_main |   File "<string>", line 3, in raise_from
localstack_main | urllib3.exceptions.LocationParseError: Failed to parse: http://7511408c7e52:4576%27%20
localstack_main | 
localstack_main | During handling of the above exception, another exception occurred:
localstack_main | 
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 248, in forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/edge.py", line 65, in forward_request
localstack_main |     response = function(url, data=data, headers=headers, verify=False)
localstack_main |   File "/opt/code/localstack/localstack/utils/common.py", line 1090, in _wrapper
localstack_main |     return method(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack_main |     return request('post', url, data=data, json=json, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_main |     return session.request(method=method, url=url, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
localstack_main |     prep = self.prepare_request(req)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
localstack_main |     p.prepare(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
localstack_main |     self.prepare_url(url, params)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 382, in prepare_url
localstack_main |     raise InvalidURL(*e.args)
localstack_main | requests.exceptions.InvalidURL: Failed to parse: http://7511408c7e52:4576%27%20
localstack_main | 
localstack_main | 2020-06-05T10:08:25:ERROR:localstack.services.generic_proxy: Error forwarding request: Failed to parse: http://7511408c7e52:4576%27%20 Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 380, in prepare_url
localstack_main |     scheme, auth, host, port, path, query, fragment = parse_url(url)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/url.py", line 392, in parse_url
localstack_main |     return six.raise_from(LocationParseError(source_url), None)
localstack_main |   File "<string>", line 3, in raise_from
localstack_main | urllib3.exceptions.LocationParseError: Failed to parse: http://7511408c7e52:4576%27%20
localstack_main | 
localstack_main | During handling of the above exception, another exception occurred:
localstack_main | 
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 248, in forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/edge.py", line 65, in forward_request
localstack_main |     response = function(url, data=data, headers=headers, verify=False)
localstack_main |   File "/opt/code/localstack/localstack/utils/common.py", line 1090, in _wrapper
localstack_main |     return method(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack_main |     return request('post', url, data=data, json=json, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_main |     return session.request(method=method, url=url, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
localstack_main |     prep = self.prepare_request(req)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
localstack_main |     p.prepare(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
localstack_main |     self.prepare_url(url, params)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 382, in prepare_url
localstack_main |     raise InvalidURL(*e.args)
localstack_main | requests.exceptions.InvalidURL: Failed to parse: http://7511408c7e52:4576%27%20
localstack_main | 
localstack_main | 2020-06-05T10:08:26:ERROR:localstack.services.generic_proxy: Error forwarding request: Failed to parse: http://7511408c7e52:4576%27%20 Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 380, in prepare_url
localstack_main |     scheme, auth, host, port, path, query, fragment = parse_url(url)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/url.py", line 392, in parse_url
localstack_main |     return six.raise_from(LocationParseError(source_url), None)
localstack_main |   File "<string>", line 3, in raise_from
localstack_main | urllib3.exceptions.LocationParseError: Failed to parse: http://7511408c7e52:4576%27%20
localstack_main | 
localstack_main | During handling of the above exception, another exception occurred:
localstack_main | 
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 248, in forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/edge.py", line 65, in forward_request
localstack_main |     response = function(url, data=data, headers=headers, verify=False)
localstack_main |   File "/opt/code/localstack/localstack/utils/common.py", line 1090, in _wrapper
localstack_main |     return method(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack_main |     return request('post', url, data=data, json=json, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_main |     return session.request(method=method, url=url, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
localstack_main |     prep = self.prepare_request(req)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
localstack_main |     p.prepare(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
localstack_main |     self.prepare_url(url, params)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 382, in prepare_url
localstack_main |     raise InvalidURL(*e.args)
localstack_main | requests.exceptions.InvalidURL: Failed to parse: http://7511408c7e52:4576%27%20
localstack_main | 
localstack_main | 2020-06-05T10:08:26:ERROR:localstack.services.generic_proxy: Error forwarding request: Failed to parse: http://7511408c7e52:4576%27%20 Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 380, in prepare_url
localstack_main |     scheme, auth, host, port, path, query, fragment = parse_url(url)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/url.py", line 392, in parse_url
localstack_main |     return six.raise_from(LocationParseError(source_url), None)
localstack_main |   File "<string>", line 3, in raise_from
localstack_main | urllib3.exceptions.LocationParseError: Failed to parse: http://7511408c7e52:4576%27%20
localstack_main | 
localstack_main | During handling of the above exception, another exception occurred:
localstack_main | 
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 248, in forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/edge.py", line 65, in forward_request
localstack_main |     response = function(url, data=data, headers=headers, verify=False)
localstack_main |   File "/opt/code/localstack/localstack/utils/common.py", line 1090, in _wrapper
localstack_main |     return method(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack_main |     return request('post', url, data=data, json=json, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_main |     return session.request(method=method, url=url, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
localstack_main |     prep = self.prepare_request(req)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
localstack_main |     p.prepare(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
localstack_main |     self.prepare_url(url, params)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 382, in prepare_url
localstack_main |     raise InvalidURL(*e.args)
localstack_main | requests.exceptions.InvalidURL: Failed to parse: http://7511408c7e52:4576%27%20
localstack_main | 
localstack_main | 2020-06-05T10:08:26:ERROR:localstack.services.generic_proxy: Error forwarding request: Failed to parse: http://7511408c7e52:4576%27%20 Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 380, in prepare_url
localstack_main |     scheme, auth, host, port, path, query, fragment = parse_url(url)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/url.py", line 392, in parse_url
localstack_main |     return six.raise_from(LocationParseError(source_url), None)
localstack_main |   File "<string>", line 3, in raise_from
localstack_main | urllib3.exceptions.LocationParseError: Failed to parse: http://7511408c7e52:4576%27%20
localstack_main | 
localstack_main | During handling of the above exception, another exception occurred:
localstack_main | 
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 248, in forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/edge.py", line 65, in forward_request
localstack_main |     response = function(url, data=data, headers=headers, verify=False)
localstack_main |   File "/opt/code/localstack/localstack/utils/common.py", line 1090, in _wrapper
localstack_main |     return method(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack_main |     return request('post', url, data=data, json=json, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_main |     return session.request(method=method, url=url, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
localstack_main |     prep = self.prepare_request(req)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
localstack_main |     p.prepare(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
localstack_main |     self.prepare_url(url, params)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 382, in prepare_url
localstack_main |     raise InvalidURL(*e.args)
localstack_main | requests.exceptions.InvalidURL: Failed to parse: http://7511408c7e52:4576%27%20
localstack_main | 
localstack_main | 2020-06-05T10:08:26:ERROR:localstack.services.generic_proxy: Error forwarding request: Failed to parse: http://7511408c7e52:4576%27%20 Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 380, in prepare_url
localstack_main |     scheme, auth, host, port, path, query, fragment = parse_url(url)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/url.py", line 392, in parse_url
localstack_main |     return six.raise_from(LocationParseError(source_url), None)
localstack_main |   File "<string>", line 3, in raise_from
localstack_main | urllib3.exceptions.LocationParseError: Failed to parse: http://7511408c7e52:4576%27%20
localstack_main | 
localstack_main | During handling of the above exception, another exception occurred:
localstack_main | 
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 248, in forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/edge.py", line 65, in forward_request
localstack_main |     response = function(url, data=data, headers=headers, verify=False)
localstack_main |   File "/opt/code/localstack/localstack/utils/common.py", line 1090, in _wrapper
localstack_main |     return method(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack_main |     return request('post', url, data=data, json=json, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_main |     return session.request(method=method, url=url, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
localstack_main |     prep = self.prepare_request(req)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
localstack_main |     p.prepare(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
localstack_main |     self.prepare_url(url, params)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 382, in prepare_url
localstack_main |     raise InvalidURL(*e.args)
localstack_main | requests.exceptions.InvalidURL: Failed to parse: http://7511408c7e52:4576%27%20
localstack_main | 
localstack_main | 2020-06-05T10:08:26:ERROR:localstack.services.generic_proxy: Error forwarding request: Failed to parse: http://7511408c7e52:4576%27%20 Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 380, in prepare_url
localstack_main |     scheme, auth, host, port, path, query, fragment = parse_url(url)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/url.py", line 392, in parse_url
localstack_main |     return six.raise_from(LocationParseError(source_url), None)
localstack_main |   File "<string>", line 3, in raise_from
localstack_main | urllib3.exceptions.LocationParseError: Failed to parse: http://7511408c7e52:4576%27%20
localstack_main | 
localstack_main | During handling of the above exception, another exception occurred:
localstack_main | 
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 248, in forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/edge.py", line 65, in forward_request
localstack_main |     response = function(url, data=data, headers=headers, verify=False)
localstack_main |   File "/opt/code/localstack/localstack/utils/common.py", line 1090, in _wrapper
localstack_main |     return method(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack_main |     return request('post', url, data=data, json=json, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_main |     return session.request(method=method, url=url, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
localstack_main |     prep = self.prepare_request(req)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
localstack_main |     p.prepare(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
localstack_main |     self.prepare_url(url, params)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 382, in prepare_url
localstack_main |     raise InvalidURL(*e.args)
localstack_main | requests.exceptions.InvalidURL: Failed to parse: http://7511408c7e52:4576%27%20
localstack_main | 
```

## Expected behavior

Save message to the queue.

## Actual behavior

python code failed on generic proxy exception.

# Steps to reproduce

1. docker-compose up (with the docker-compose.yml on the latest repo)
2. create a new queue
3. save a message to the queue.

## Command used to start LocalStack
docker-compose up

**Comment by whummer** [comment]
Thanks for reporting this issue @drizzef . Can you please share some details about your environment - which client library or SDK are you using to talk to the SQS API? Using the regular `aws` CLI or `boto3` Python libraries, it seems to be working fine. Are you using version 2 of the AWS SDKs, by any chance? Please note that v2 SDKs are not fully supported yet, due to their use of extended mechanisms like HTTP/2 protocol, etc. If you could share a small example to help reproduce this issue, that would be great. Thanks!

**Comment by whummer** [comment]
Any updates on this one @drizzef ? Can you please share the relevant portion of your client code to help reproduce this issue? Thanks

**Comment by whummer** [comment]
Closing this for now, due to inactivity - please feel free to re-open this issue if more details are available. Thanks!
