### ISSUE TITLE
Docker build: Test Failures - test_domain_es_version

### ISSUE THREAD

**Issue by harrydaniels-IW** [localstack/localstack#2532]
[ X] bug report
[ ] feature request

# Detailed description

I'm trying to build a local container for dev, however whenever I try to build a container from the dockerfile I get an elastic search test-error. The build commands are as follows:

```
git clone https://github.com/localstack/localstack.git

cd localstack

TMPDIR=/private$TMPDIR docker build -t localstack_dev .

```

The test is failing here:

```
======================================================================
FAIL: test_domain_es_version (tests.integration.test_elasticsearch.ElasticsearchTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/code/localstack/tests/integration/test_elasticsearch.py", line 53, in test_domain_es_version
    self._create_domain(name=domain_name, version='6.8')
  File "/opt/code/localstack/tests/integration/test_elasticsearch.py", line 137, in _create_domain
    retry(check_cluster_ready, sleep=10, retries=6)
  File "/opt/code/localstack/localstack/utils/common.py", line 470, in retry
    raise raise_error
  File "/opt/code/localstack/localstack/utils/common.py", line 466, in retry
    return function(**kwargs)
  File "/opt/code/localstack/tests/integration/test_elasticsearch.py", line 135, in check_cluster_ready
    assert status['DomainStatus']['Created']
AssertionError: 
-------------------- >> begin captured logging << --------------------
l_16a62a9a: INFO: Lambda log message - logging module
bootstrap.py: WARNING: Thread run method <function LambdaExecutor.execute.<locals>.do_execute at 0x7fb015959f70>(None) failed: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 492, in run
    self.func(self.params)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 120, in do_execute
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 108, in do_execute
    result = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 672, in _execute
    process.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 667, in do_execute
    result = lambda_function(event, context)
  File "/tmp/localstack/lambda_script_l_16a62a9a.py", line 102, in handler
    forward_events(raw_event_messages)
  File "/tmp/localstack/lambda_script_l_16a62a9a.py", line 139, in forward_events
    kinesis.put_records(StreamName=KINESIS_STREAM_NAME, Records=records)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the PutRecords operation: Stream test_stream_1 under account 000000000000 not found.
```

The reason for this is I'd like to install a dev version of Moto: (1.3.15.dev887) over moto-ext to test some of the new features with my tech stack. QQ Is there a fundamental difference between moto and moto-ext?

## Expected behaviour

The container tests execute successfully and the container is built.

## Actual behaviour

One of the tests fails causing the build to fail.

**Comment by whummer** [comment]
Thanks for reporting this issue @harrydaniels-IW . Can you please try pulling the latest version of the base image and give it another try?
```
$ docker pull localstack/java-maven-node-python
$ docker build -t localstack_dev .
```

**Comment by whummer** [comment]
Btw, another recommendation - you can tag and use the image layer that gets created before the tests are kicked off. During the Docker build you'll observe some output like this: 
```
...
 ---> Running in f2d067b5b8c1
Removing intermediate container f2d067b5b8c1
 ---> 8dc22a562f8f
Step 34/36 : ADD tests/ tests/
 ---> b1c3ccffa59a
Step 35/36 : RUN LAMBDA_EXECUTOR=local make test
 ---> Running in 307ebde7526b
make lint && \
...
```
Note the image layer ID `8dc22a562f8f` before the Docker build runs the `ADD tests/ tests/` command. You can then create a tagged image from this layer like this:
```
docker tag 8dc22a562f8f localstack_dev
```
Hope that helps - please let us know if there are any other issues. Thanks
