### ISSUE TITLE
Elastisearch not starting on Mac El Capitan

### ISSUE THREAD

**Issue by jenkink** [localstack/localstack#254]
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock CloudWatch (http port 4582)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudFormation (http port 4581)...
Starting mock DynamoDB (http port 4569)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
2017-08-23T10:36:47:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2017-08-23T10:36:50:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2017-08-23T10:36:53:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2017-08-23T10:36:56:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2017-08-23T10:36:59:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2017-08-23T10:37:02:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2017-08-23T10:37:05:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2017-08-23T10:37:08:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2017-08-23T10:37:11:ERROR:localstack.services.es.es_starter: Elasticsearch health check failed (retrying...): TransportError(502, u'') Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/localstack/services/es/es_starter.py", line 55, in check_elasticsearch
    out = es.cat.aliases()
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/cat.py", line 23, in aliases
    'aliases', name), params=params)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 124, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
TransportError: TransportError(502, u'')
2017-08-23T10:37:11:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2017-08-23T10:37:11:ERROR:infra.pyc: Error checking state of local environment (after some retries): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 327, in check_infra
    raise e
AssertionError
Error starting infrastructure:  Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 462, in start_infra
    check_infra(apis=apis)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 336, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 336, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 336, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 336, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 336, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 336, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 336, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 336, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/site-packages/localstack/services/infra.py", line 334, in check_infra
    raise e
AssertionError
ERROR:

also ive installed localstack on windows however when i run 'localstack start' i get a message saying that its not recognixed as an internal or external command, where does it get installed so i can add it to the path?

**Comment by whummer** [comment]
Thanks for reporting @jenkink , can you please post the detailed debug output:
```
localstack --version
DEBUG=1 localstack start
```

**Comment by Dogzhou** [comment]
Fix this issue by updating Java version to 8
