### ISSUE TITLE
Connection Timeout when trying to use S3 or SQS from lambda deployed to LocalStack

### ISSUE THREAD

**Issue by DVader666** [localstack/localstack#2554]
This is a follow up on issue #1359.

# Detailed description

I wanted to test, in LocalStack, a Java 8 Lambda function that sends some messages to SQS. I tested the same function in my AWS account and it works fine there.

When I invoke the function deployed in LocalStack, I get a connection timeout when trying to get the URL for a given queue name deployed in the same serverless.yml that deploys the function. Looking for answers on the web, I found reported LocalStack issue #1359 from last year about a timeout on S3 trying just to list buckets. Seeing the issue was closed without a resolution I decided to try the Node sample discussed in issue #1359 to validate if my problem was isolated to SQS, my Java code or a general issue of some sort. In the end I got the same result as in issue #1359: a timeout trying to connect from a deployed lambda function in LocalStack to the service I was trying to use, also in LocalStack.

I decided to follow up on #1359 using the Node code for listing available S3 buckes instead of my Java code, because a far better example for just testing connectivity inside LocalStack and because I believe finding the answer to the S3 timeout will also solve my original SQS timeout issue.

Help will be most appreciated.

-----------------------------------------------
OS: Ubuntu v18.10 (16 GB laptop)
LocalStack v0.11.2 (pip 19.3.1; python 3.7.5; LinuxBrew v2.1.16)
Node v12.9.1 (npm v6.14.5)
Serverless (framework code v1.72.0; plugin v3.6.13; SDK v2.3.1)
Serverless-LocalStack v0.4.24
AWS-SDK (Node): v2.695.0
Docker v19.03.6

## Command used to start LocalStack

```
$ PORT_WEB_UI=8082 localstack start --docker

LocalStack version: 0.11.2
Starting local dev environment. CTRL-C to quit.
docker run -it -e PORT_WEB_UI="8082" -e DEFAULT_REGION="us-east-1" -e LOCALSTACK_HOSTNAME="localhost" -e TEST_AWS_ACCOUNT_ID="000000000000" -p 4566:4566 --rm --privileged --name localstack_main -p 8080:8080 -p 4567-4620:4567-4620 -p 10000:10000 -p 8082-8083:8082-8083  -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack" 
Waiting for all LocalStack services to be ready
2020-06-12 21:33:55,406 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-06-12 21:33:55,408 INFO supervisord started with pid 13
2020-06-12 21:33:56,414 INFO spawned: 'dashboard' with pid 19
2020-06-12 21:33:56,422 INFO spawned: 'infra' with pid 20
(. .venv/bin/activate; bin/localstack web)
2020-06-12 21:33:56,451 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
LocalStack version: 0.11.2
(. .venv/bin/activate; exec bin/localstack start --host)
LocalStack version: 0.11.2
Starting local dev environment. CTRL-C to quit.
2020-06-12 21:33:58,108 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-06-12T21:33:59:INFO:localstack_ext.bootstrap.install: Unable to download local test SSL certificate: [Errno 2] No such file or directory: ''
Running on 0.0.0.0:8083 over https (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Starting edge router (https port 4566)...
Starting mock API Gateway service in http ports 4566 (recommended) and 4567 (deprecated)...
Running on 0.0.0.0:4566 over https (CTRL + C to quit)
2020-06-12T21:34:04:INFO:localstack.multiserver: Starting multi API server process on port 37333
Running on 0.0.0.0:4567 over http (CTRL + C to quit)
Running on 0.0.0.0:37333 over http (CTRL + C to quit)
Starting mock CloudFormation service in http ports 4566 (recommended) and 4581 (deprecated)...
Starting mock CloudWatch service in http ports 4566 (recommended) and 4582 (deprecated)...
Starting mock DynamoDB service in http ports 4566 (recommended) and 4569 (deprecated)...
Starting mock DynamoDB Streams service in http ports 4566 (recommended) and 4570 (deprecated)...
Starting mock EC2 service in http ports 4566 (recommended) and 4597 (deprecated)...
Starting mock ES service in http ports 4566 (recommended) and 4578 (deprecated)...
Starting mock Firehose service in http ports 4566 (recommended) and 4573 (deprecated)...
Starting mock IAM service in http ports 4566 (recommended) and 4593 (deprecated)...
Starting mock STS service in http ports 4566 (recommended) and 4592 (deprecated)...
Starting mock Kinesis service in http ports 4566 (recommended) and 4568 (deprecated)...
Starting mock KMS service in http ports 4566 (recommended) and 4599 (deprecated)...
Starting mock Lambda service in http ports 4566 (recommended) and 4574 (deprecated)...
Starting mock CloudWatch Logs service in http ports 4566 (recommended) and 4586 (deprecated)...
Starting mock Redshift service in http ports 4566 (recommended) and 4577 (deprecated)...
Starting mock Route53 service in http ports 4566 (recommended) and 4580 (deprecated)...
Starting mock S3 service in http ports 4566 (recommended) and 4572 (deprecated)...
Starting mock Secrets Manager service in http ports 4566 (recommended) and 4584 (deprecated)...
Starting mock SES service in http ports 4566 (recommended) and 4579 (deprecated)...
Starting mock SNS service in http ports 4566 (recommended) and 4575 (deprecated)...
Starting mock SQS service in http ports 4566 (recommended) and 4576 (deprecated)...
Starting mock SSM service in http ports 4566 (recommended) and 4583 (deprecated)...
Starting mock Cloudwatch Events service in http ports 4566 (recommended) and 4587 (deprecated)...
Starting mock StepFunctions service in http ports 4566 (recommended) and 4585 (deprecated)...
Running on 0.0.0.0:4581 over http (CTRL + C to quit)
Running on 0.0.0.0:4569 over http (CTRL + C to quit)
Running on 0.0.0.0:4593 over http (CTRL + C to quit)
Running on 0.0.0.0:4568 over http (CTRL + C to quit)
Running on 0.0.0.0:4599 over http (CTRL + C to quit)
Running on 0.0.0.0:4586 over http (CTRL + C to quit)
Running on 0.0.0.0:4572 over http (CTRL + C to quit)
Running on 0.0.0.0:4584 over http (CTRL + C to quit)
Running on 0.0.0.0:4575 over http (CTRL + C to quit)
Running on 0.0.0.0:4576 over http (CTRL + C to quit)
Running on 0.0.0.0:4583 over http (CTRL + C to quit)
Running on 0.0.0.0:4587 over http (CTRL + C to quit)
Running on 0.0.0.0:4585 over http (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Ready.
```

(I had set PORT_WEB_UI to 8082 because I have something else running in ports 8080 and 8081.)

Dummy AWS config in .aws/credentials file as:

```
[default]
aws_access_key_id=000000000000
aws_secret_access_key=xyz
region=us-east-1
```

I have tested LocalStack is available from my command-line:

```
$ aws --endpoint-url http://localhost:4566 s3 mb s3://local-sls-bucket
make_bucket: local-sls-bucket

$ aws --endpoint-url http://localhost:4566 s3 ls
2020-06-12 15:35:24 local-sls-bucket
```

## For deploying the testing code to LocalStack

My serverles.yml file:

```
service: test-sls-s3

plugins:
    - serverless-localstack

custom:
    localstack:
        stages:
            - local
        host: http://localhost
        debug: true

provider:
    name: aws
    runtime: nodejs12.x
    stage: ${opt:stage, 'local'}
    region: ${opt:region, 'us-east-1'}
    deploymentBucket:
        name: ${self:provider.stage}-sls-bucket

functions:
    hello:
        handler: handler.hello
```

Deployment command:

```
$ sls deploy --verbose

Serverless: config.options_stage: undefined
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: ${opt:stage, 'local'}
Serverless: config.stage: ${opt:stage, 'local'}
Serverless: config.options_stage: undefined
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: local
Serverless: config.stage: local
Serverless: Using serverless-localstack
Serverless: Reconfiguring service apigateway to use http://localhost:4567
Serverless: Reconfiguring service cloudformation to use http://localhost:4581
Serverless: Reconfiguring service cloudwatch to use http://localhost:4582
Serverless: Reconfiguring service lambda to use http://localhost:4574
Serverless: Reconfiguring service dynamodb to use http://localhost:4569
Serverless: Reconfiguring service kinesis to use http://localhost:4568
Serverless: Reconfiguring service route53 to use http://localhost:4580
Serverless: Reconfiguring service firehose to use http://localhost:4573
Serverless: Reconfiguring service stepfunctions to use http://localhost:4585
Serverless: Reconfiguring service es to use http://localhost:4578
Serverless: Reconfiguring service s3 to use http://localhost:4572
Serverless: Reconfiguring service ses to use http://localhost:4579
Serverless: Reconfiguring service sns to use http://localhost:4575
Serverless: Reconfiguring service sqs to use http://localhost:4576
Serverless: Reconfiguring service sts to use http://localhost:4592
Serverless: Reconfiguring service iam to use http://localhost:4593
Serverless: Reconfiguring service ssm to use http://localhost:4583
Serverless: Reconfiguring service rds to use http://localhost:4594
Serverless: Reconfiguring service ec2 to use http://localhost:4597
Serverless: Reconfiguring service elasticache to use http://localhost:4598
Serverless: Reconfiguring service kms to use http://localhost:4599
Serverless: Reconfiguring service secretsmanager to use http://localhost:4584
Serverless: Reconfiguring service logs to use http://localhost:4586
Serverless: Reconfiguring service cloudwatchlogs to use http://localhost:4586
Serverless: Reconfiguring service iot to use http://localhost:4589
Serverless: Reconfiguring service cognito-idp to use http://localhost:4590
Serverless: Reconfiguring service cognito-identity to use http://localhost:4591
Serverless: Reconfiguring service ecs to use http://localhost:4601
Serverless: Reconfiguring service eks to use http://localhost:4602
Serverless: Reconfiguring service xray to use http://localhost:4603
Serverless: Reconfiguring service appsync to use http://localhost:4605
Serverless: Reconfiguring service cloudfront to use http://localhost:4606
Serverless: Reconfiguring service athena to use http://localhost:4607
Serverless: Warning: Unable to find plugin named: TypeScriptPlugin
Serverless: config.options_stage: undefined
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: local
Serverless: config.stage: local
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service test-sls-s3.zip file to S3 (5.34 KB)...
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - test-sls-s3-local
Serverless: Stack create finished...
Service Information
service: test-sls-s3
stage: local
region: us-east-1
stack: test-sls-s3-local
resources: 4
api keys:
  None
endpoints:
  None
functions:
  hello: test-sls-s3-local-hello
layers:
  None

Stack Outputs
ServerlessDeploymentBucketName: local-sls-bucket
HelloLambdaFunctionQualifiedArn: HelloLambdaVersiontKjNMf4xSm87qVYfC9YIrj51duylTwTW3YHIkGe6X24

Serverless: Run the "serverless" command to setup monitoring, troubleshooting and testing.
```

## The testing code (mostly taken from issue #1359)

package.json

```
{
    "name": "test-sls-s3",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "devDependencies": {
        "serverless-localstack": "^0.4.24"
    },
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "keywords": [],
    "author": "",
    "license": "ISC"
}
```

handler.js

```
'use strict';

const AWS = require('aws-sdk');

module.exports.hello = () => {

    return new Promise((resolve, reject) => {
        const {LOCALSTACK_HOSTNAME} = process.env;
        const s3 = new AWS.S3({endpoint: `http://${LOCALSTACK_HOSTNAME}:4572`});
        s3.listBuckets()
                .promise()
                .then(results => {
                    console.log(results);
                    resolve(results);
                })
                .catch(err => {
                    console.log(err);
                    reject(err);
                });
    });
};
```

test.js

```
'use strict';

const AWS = require('aws-sdk');

const lambda = new AWS.Lambda({
    region: 'us-east-1',
    endpoint: 'http://localhost:4566'
});

lambda.invoke({FunctionName: 'test-sls-s3-local-hello'})
        .promise()
        .then(data => {
            console.log(data);
        })
        .catch(err => console.log(err));
```

## Test code invoked as

```
$ node test.js

Error [TimeoutError]: Connection timed out after 120000ms
    at ClientRequest.<anonymous> (/home/myuser/projects/test-sls-s3/node_modules/aws-sdk/lib/http/node.js:86:34)
    at Object.onceWrapper (events.js:297:20)
    at ClientRequest.emit (events.js:209:13)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at Socket.emitRequestTimeout (_http_client.js:687:40)
    at Object.onceWrapper (events.js:297:20)
    at Socket.emit (events.js:209:13)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at Socket._onTimeout (net.js:434:8)
    at listOnTimeout (internal/timers.js:531:17) {
  message: 'Connection timed out after 120000ms',
  code: 'TimeoutError',
  time: 2020-06-12T21:45:54.488Z,
  region: 'us-east-1',
  hostname: 'localhost',
  retryable: true
}
```

## Output in LocalStack (only for one of the retries)

```
2020-06-12T21:43:54:WARNING:localstack.services.awslambda.lambda_executors: Empty event body specified for invocation of Lambda "arn:aws:lambda:us-east-1:000000000000:function:test-sls-s3-local-hello"
2020-06-12T21:43:54:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: CONTAINER_ID="$(docker create -i   -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e NODE_TLS_REJECT_UNAUTHORIZED="$NODE_TLS_REJECT_UNAUTHORIZED"  --rm "lambci/lambda:nodejs12.x" "handler.hello")";docker cp "/tmp/localstack/zipfile.aa794252/." "$CONTAINER_ID:/var/task"; docker start -ai "$CONTAINER_ID";
2020-06-12T21:46:38:WARNING:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:test-sls-s3-local-hello: Lambda process returned error status code: 1. Result: {"errorType":"NetworkingError","errorMessage":"connect ETIMEDOUT 172.17.0.1:4572"}. Output:
START RequestId: a948fb2d-6d4d-1f01-b22b-49696274c658 Version: $LATEST
2020-06-12T21:46:37.706Z	a948fb2d-6d4d-1f01-b22b-49696274c658	INFO	Error: connect ETIMEDOUT 172.17.0.1:4572
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'NetworkingError',
  syscall: 'connect',
  address: '172.17.0.1',
  port: 4572,
  region: 'us-east-1',
  hostname: '172.17.0.1',
  retryable: true,
  time: 2020-06-12T21:46:37.689Z
}
2020-06-12T21:46:37.711Z	a948fb2d-6d4d-1f01-b22b-49696274c658	ERROR	Invoke Error 	{"errorType":"NetworkingError","errorMessage":"connect ETIMEDOUT 172.17.0.1:4572","code":"NetworkingError","message":"connect ETIMEDOUT 172.17.0.1:4572","errno":"ETIMEDOUT","syscall":"connect","address":"172.17.0.1","port":4572,"region":"us-east-1","hostname":"172.17.0.1","retryable":true,"time":"2020-06-12T21:46:37.689Z","stack":["Error: connect ETIMEDOUT 172.17.0.1:4572","    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)"]}
END RequestId: a948fb2d-6d4d-1f01-b22b-49696274c658
REPORT RequestId: a948fb2d-6d4d-1f01-b22b-49696274c658	Init Duration: 630.20 ms	Duration: 6000.00 ms	Billed Duration: 6000 ms	Memory Size: 1536 MB	Max Memory Used: 28 MB	 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 499, in run_lambda
    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 133, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 120, in do_execute
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 108, in do_execute
    result = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 257, in _execute
    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 170, in run_lambda_executor
    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
Exception: Lambda process returned error status code: 1. Result: {"errorType":"NetworkingError","errorMessage":"connect ETIMEDOUT 172.17.0.1:4572"}. Output:
```

Notice that when started via Docker in command line, the LOCALSTACK_HOSTNAME read-only env variable is automatically set to "localhost", but when used in the function code to set the endpoint for S3 service the value is 172.17.0.1 which I guess it's the internal address for the container. In the test code I used legacy port number 4572 for S3 service but I also tested with the new edge port 4566 and got the same result (tiimeout).

----------------------------------------------------------
## On a separate but maybe related note...

In the past, when used LocalStack in some integration tests via TestContainers LocalStack module, I remember I had to ask the newly created container instance for its current endpoint (say for the S3 service), and the port number returned was anything but 4572 (legacy S3 port) and neither 4566 (new Edge port), so apparently the TestContainers LocalStack container instance was randomizing the port numbers... but for a "normal" LocalStack instance manually started in command line I never expected for port number to change internally in the container for a deployed lambda function to connect to the needed services. But if that would be the case, how do we get the actual endpoint to use from a deployed lambda function? The LOCALSTACK_HOSTNAME read-only env variable only returns the host. What about the port number?

**Comment by DVader666** [comment]
The question still remains: why I can connect and use LocalStack services like S3 and SQS from outside LocalStack via code (Node.js, Java, etc.) or command line like AWS-CLI, but not from inside the same LocalStack "instance" via a deployed lambda function?

If this is not the right place to ask for such questions (I was just following on previously reported issue #1359) then, please, someone point me in the right direction.

**Comment by whummer** [comment]
Thanks for reporting @DVader666 . As you mentioned, the `LOCALSTACK_HOSTNAME` variable should be used inside the Lambda to point your AWS SDK clients to the correct endpoint.

A change has been pushed recently in #2633 which should improve the way we determine the target IP address of the LocalStack Docker container. Can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? Please let us know if this problem still persists with latest. Thanks

**Comment by DVader666** [comment]
Thank you for answering. I did as instructed, and the test code finally worked!
```
$ docker pull localstack/localstack
Using default tag: latest
latest: Pulling from localstack/localstack

$ docker image ls --all | grep localstack
localstack/localstack         latest              853431303ed4        18 hours ago        897MB
localstack/localstack         <none>              34fb813a1697        4 weeks ago         891MB
```

I also proceeded to delete the previous LocalStack image just to play safe (yeah, I'm paranoid):
```
$ docker image rm 34fb813a1697
Untagged: localstack/localstack@sha256:af43bf0d05f925e0838c6434079422e80006b0554fe40430eed00d8a7a2b741a
Deleted: sha256:34fb813a1697fa4a002b3477d8924c37db1c166cf2711b91480d5d3b58f33e62
Deleted: sha256:97e598f58b6a90bc7cf7be41ffee1610923e553938723c5f367ca6dde4b676d9

$ docker image ls --all | grep localstack
localstack/localstack         latest              853431303ed4        18 hours ago        897MB
```

Then I started LocalStack and deployed the test project as described in my initial post.

Finally, I invoked the test code and tears of joy!
```
$ node test.js

{
  StatusCode: 200,
  LogResult: '',
  ExecutedVersion: '$LATEST',
  Payload: '{"Buckets":[{"CreationDate":"2020-07-08T18:22:33.026Z","Name":"local-sls-bucket"}],"Owner":{"DisplayName":"webfile","ID":"bcaf1ffd86f41161ca5fb16fd081034f"}}\n'
}
```

I still need to test other services like SQS and DynamoDB from deployed lambdas, but I can only hope that if it worked for S3 then it will work for the rest of the stack.

Thank you again :)

**Comment by whummer** [comment]
Great - glad you were able to get it working!
