### ISSUE TITLE
Cloudformation create-stack for SNS with yaml causes TypeError

### ISSUE THREAD

**Issue by pzrq** [localstack/localstack#2568]
# Type of request: This is a ...

[ ] bug report
[x] feature request

# Detailed description

Thanks for the good project, I've been able to get some other bits and pieces working for my use cases, similar to #2125 so far.

However as @erkkikeranen [commented](https://github.com/localstack/localstack/issues/438#issuecomment-371393832), which has been upvoted 28+ times:

> I am also experiencing this same issue, cannot deploy cloudformation template. Is there a complete documentation somewhere what localstack supports and what it does not? For example if our cloudformation template that is generated by serverless plugin is too complicated to work, how can I know that?

In my case, I'm basically trying the command as [AWS documents](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-cli-creating-stack.html) to try to get started:

```
$ aws --endpoint-url=http://localhost:4566 \
 cloudformation create-stack --stack-name "Infra-SNS-defaultd" \
 --template-body "file:///Users/pzrq/Projects/projectinfra/sns/aws-foundation-sns.template.yaml" \
 --parameters ParameterKey=CompanyName,ParameterValue=MyCompany \
              ParameterKey=MyEmail1,ParameterValue=my@email.com
```
This is causing a server error.

I suspect from the server stack trace below, that this is because it's using a YAML instead of JSON template, but it'd be nice to know for sure before I start transcoding that template to JSON, or if there's some other detail or workaround I've missed that could help me 😄 

<details>
  <summary>Click to expand: aws-foundation-sns.template.yaml</summary>
  
```
---
AWSTemplateFormatVersion: '2010-09-09'
Description:
  SNS Topics for stuff

Parameters:

  CompanyName:
    Type: String
    Description: 'Customer/Company name, commonly known-by name'
    AllowedPattern: '[A-Za-z0-9-]{5,}'
    ConstraintDescription: 'String must be 5 or more characters, letters, numbers and -'

  MyEmail1:
    Type: String
    Description: Email address for stuff
    Default: ""

  MyEmail2:
    Type: String
    Description: Email address for stuff
    Default: ""

Conditions:
  HasMyEmail1: !Not [!Equals [!Ref MyEmail1, '']]
  HasMyEmail2: !Not [!Equals [!Ref MyEmail2, '']]

  SetupMy: !Or
                - Condition: HasMyEmail1
                - Condition: HasMyEmail2

Resources:

  MyTopic:
    Condition: SetupMy
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub "${CompanyName} AWS MyTopic"
      Subscription:
        - !If
          - HasMyEmail1
          -
            Endpoint: !Ref MyEmail1
            Protocol: email
          - !Ref AWS::NoValue
        - !If
          - HasMyEmail2
          -
            Endpoint: !Ref MyEmail2
            Protocol: email
          - !Ref AWS::NoValue

Outputs:
  StackName:
    Description: 'Stack name'
    Value: !Sub '${AWS::StackName}'
    Export:
      Name: !Sub '${AWS::StackName}-StackName'

  MyTopic:
    Condition: SetupMy
    Description: 'My arn'
    Value: !Ref MyTopic
    Export:
      Name: !Sub '${AWS::StackName}-MyTopicArn'

  MyTopicName:
    Condition: SetupMy
    Description: 'My Name'
    Value: !GetAtt MyTopic.TopicName
    Export:
      Name: !Sub '${AWS::StackName}-MyTopicName'
```
</details>

## Expected behavior

Either:
- the localstack SNS Topic / stack is created, or
- a more useful message displayed, like `YAML is not currently supported` or `YAML is only supported in the extended version, please purchase at https://localstack.cloud/`

### Client
```
$ aws --endpoint-url=http://localhost:4566 \
 cloudformation create-stack --stack-name "Infra-SNS-defaultd" \
 --template-body "file:///Users/pzrq/Projects/projectinfra/sns/aws-foundation-sns.template.yaml" \
 --parameters ParameterKey=CompanyName,ParameterValue=MyCompany \
              ParameterKey=MyEmail1,ParameterValue=my@email.com

Unable to parse response (syntax error: line 1, column 54), invalid XML received:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

### Server
```
2020-06-17T00:57:34:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "MyTopic": 'NoneType' object is not subscriptable Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 202, in parse_and_create_resource
    return _parse_and_create_resource(
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 283, in _parse_and_create_resource
    raise moto_create_error
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 268, in _parse_and_create_resource
    resource = parse_and_create_resource_orig(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 371, in parse_and_create_resource
    resource = resource_class.create_from_cloudformation_json(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/sns/models.py", line 100, in create_from_cloudformation_json
    topic.arn, subscription["Endpoint"], subscription["Protocol"]
TypeError: 'NoneType' object is not subscriptable
```

# Steps to reproduce

## Command used to start LocalStack

```
APIGATEWAY_PORT=4467 SERVICES=apigateway,cloudformation,sns,sqs localstack start
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
$ aws --endpoint-url=http://localhost:4566 \
 cloudformation create-stack --stack-name "Infra-SNS-defaultd" \
 --template-body "file:///Users/pzrq/Projects/projectinfra/sns/aws-foundation-sns.template.yaml" \
 --parameters ParameterKey=CompanyName,ParameterValue=MyCompany \
              ParameterKey=MyEmail1,ParameterValue=my@email.com
```

**Comment by whummer** [comment]
Thanks for reporting @pzrq . This should be fixed in #2621 - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
