### ISSUE TITLE
Differences with the lambda invoke api using aws cli

### ISSUE THREAD

**Issue by jjaniec** [localstack/localstack#2572]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Hi, I'm currently looking for solutions to develop step functions workflows locally and doing unit tests of my lambda functions in a local environment as close as using the real aws environment.

One way of doing this would be to trigger my lambda functions using different payloads using the cli and perform tests against the output in the outfile.

The issue is that I've no way of being sure my lambda was executed or not as the return code of the cli is different with localstack if the lambda functions returns an error, the outfile telling how the lambda function failed is also not created

## Expected behavior

When making the lambda function execution unsuccessful, (eg by raising an exception in the code), the cli should have the same return code, print the same json document in stdout and save the same contents in the outfile using the localstack endpoint or aws

```python
❯ cat ./handler.py
#!/usr/bin/env python3

def handler(event, context):
    class TestException(Exception):
        pass

    raise TestException('Bad things happened')
```

```bash
❯ cat exec_lambda.sh
#!/bin/bash

rm outfile > /dev/null 2>&1

stdout=$(aws \
        lambda invoke \
        --function-name test-lambda \
        outfile
)
echo "Return code: $?"
echo "Stdout: \"${stdout}\""
echo "Outfile: \"$(cat outfile)\""
```

After deploying the lambda function

```bash
❯ ./exec_lambda.sh
Return code: 0
Stdout: "{
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "ExecutedVersion": "$LATEST"
}"
Outfile: "{"errorMessage": "Bad things happened", "errorType": "TestException", "stackTrace": ["  File \"/var/task/handler.py\", line 7, in handler\n    raise TestException('Bad things happened')\n"]}"
```

## Actual behavior

```bash
❯ cat exec_lambda.sh
#!/bin/bash

rm outfile > /dev/null 2>&1

stdout=$(aws \
        --endpoint "http://localhost:4574" \
        lambda invoke \
        --function-name test-lambda \
        outfile
)
echo "Return code: $?"
echo "Stdout: \"${stdout}\""
echo "Outfile: \"$(cat outfile)\""
```

```bash
❯ ./exec_lambda.sh

An error occurred (InternalFailure) when calling the Invoke operation (reached max retries: 4): Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:test-lambda: Lambda process returned error status code: 1. Result: {"errorType":"TestException","errorMessage":"Bad things happened","stackTrace":["  File \"/var/task/handler.py\", line 7, in handler\n    raise TestException('Bad things happened')\n"]}. Output:
START RequestId: d58a5a03-5c05-1bd0-d357-8a9fcaaac4fa Version: $LATEST
    raise TestException('Bad things happened')ler
END RequestId: d58a5a03-5c05-1bd0-d357-8a9fcaaac4fa
REPORT RequestId: d58a5a03-5c05-1bd0-d357-8a9fcaaac4fa  Init Duration: 152.90 ms        Duration: 8.91 ms       Billed Duration: 100 ms Memory Size: 1536 MB    Max Memory Used: 23 MB  Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 496, in run_lambda
    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 138, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 130, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 143, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 139, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 123, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 111, in _run
    result = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 262, in _execute
    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 175, in run_lambda_executor
    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
Exception: Lambda process returned error status code: 1. Result: {"errorType":"TestException","errorMessage":"Bad things happened","stackTrace":["  File \"/var/task/handler.py\", line 7, in handler\n    raise TestException('Bad things happened')\n"]}. Output:
START RequestId: d58a5a03-5c05-1bd0-d357-8a9fcaaac4fa Version: $LATEST
    raise TestException('Bad things happened')ler
END RequestId: d58a5a03-5c05-1bd0-d357-8a9fcaaac4fa
REPORT RequestId: d58a5a03-5c05-1bd0-d357-8a9fcaaac4fa  Init Duration: 152.90 ms        Duration: 8.91 ms       Billed Duration: 100 ms Memory Size: 1536 MB    Max Memory Used: 23 MB

Return code: 255
Stdout: ""
cat: outfile: No such file or directory
Outfile: ""
```

# Steps to reproduce

## Command used to start LocalStack

```bash
❯ cat dev.docker-compose.yml
version: '3.7'

services:
  localstack:
    image: localstack/localstack
    environment:
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=lambda
      - TZ=America/New_York
      - LAMBDA_EXECUTOR=docker
    ports:
      - '4574:4574'
    volumes:
      - /tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  stepfunctions:
    container_name: stepfunctions
    image: amazon/aws-stepfunctions-local:latest
    environment:
      - LAMBDA_ENDPOINT=http://localstack:4574
    ports:
      - '8083:8083'
```

```bash
❯ docker-compose -f dev.docker-compose.yml up -d
```

At the time of my tests, the output of `./bin/localstack -v` in the container was `0.11.2`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Script used to create the lambda function (minus the endpoint option for aws)

```bash
#!/bin/bash

ROLE_ARN="arn:aws:iam::123456789123:role/stepfunctions_dev_demo"

zip -r9 lambda.zip handler.py

aws \
	--endpoint "http://localhost:4574" \
	lambda create-function \
	--function-name test-lambda \
	--runtime python3.7 \
	--handler handler.handler \
	--role ${ROLE_ARN} \
	--zip-file fileb://lambda.zip
```

**Comment by whummer** [comment]
Thanks for the detailed report @jjaniec . This should be fixed in #2586 - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks

**Comment by jjaniec** [comment]
Hi @whummer, thank you very much for answering this fast and taking the time to work on this !

I just tried with the `latest` version of the docker image and it seems the outfile is now created but the content of it is still not really the same, we may use the content of this file in a ci pipeline be sure the tests went well

I did the following with the exact same lambda code & scripts of my 1st message:

AWS:
```
❯ ./exec_lambda.sh 
Return code: 0
Stdout: "{
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "ExecutedVersion": "$LATEST"
}"
Outfile: "{"errorMessage": "Bad things happened", "errorType": "TestException", "stackTrace": ["  File \"/var/task/handler.py\", line 7, in handler\n    raise TestException('Bad things happened')\n"]}"
```

Localstack:
```bash
❯ ./exec_lambda.sh
Return code: 0
Stdout: "{
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}"
Outfile: "{"errorMessage":"Lambda process returned error status code: 1. Result: {\"errorType\":\"TestException\",\"errorMessage\":\"Bad things happened\",\"stackTrace\":[\"  File \\\"/var/task/handler.py\\\", line 7, in handler\\n    raise TestException('Bad things happened')\\n\"]}. Output:\n\u001b[32mSTART RequestId: 15f70b68-e795-1e5d-fc40-7ff7aa4df650 Version: $LATEST\u001b[0m\n[ERROR] TestException: Bad things happened\rTraceback (most recent call last):\r\u00a0\u00a0File \"/var/task/handler.py\", line 7, in handler\r\u00a0\u00a0\u00a0\u00a0raise TestException('Bad things happened')\n\u001b[32mEND RequestId: 15f70b68-e795-1e5d-fc40-7ff7aa4df650\u001b[0m\n\u001b[32mREPORT RequestId: 15f70b68-e795-1e5d-fc40-7ff7aa4df650\tInit Duration: 82.84 ms\tDuration: 4.12 ms\tBilled Duration: 100 ms\tMemory Size: 1536 MB\tMax Memory Used: 23 MB\t\u001b[0m","errorType":"Exception","stackTrace":["  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 527, in run_lambda\n    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 136, in execute\n    return do_execute()\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 128, in do_execute\n    return _run(func_arn=func_arn)\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 143, in wrapped\n    raise e\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 139, in wrapped\n    result = func(*args, **kwargs)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 121, in _run\n    raise e\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 109, in _run\n    result = self._execute(func_arn, func_details, event, context, version)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 264, in _execute\n    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 173, in run_lambda_executor\n    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\\n%s' %\n"]}"
```

Output of `docker logs stepfunctions_dev_demo_localstack_1` while executing the lambda function

```bash
2020-06-22T05:24:40:WARNING:localstack.services.awslambda.lambda_executors: Empty event body specified for invocation of Lambda "arn:aws:lambda:us-east-1:000000000000:function:test-lambda"
2020-06-22T05:24:40:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: CONTAINER_ID="$(docker create -i   -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN"  --rm "lambci/lambda:20191117-python3.7" "handler.handler")";docker cp "/tmp/localstack/zipfile.4c826628/." "$CONTAINER_ID:/var/task"; docker start -ai "$CONTAINER_ID";
2020-06-22T05:24:42:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:test-lambda: Lambda process returned error status code: 1. Result: {"errorType":"TestException","errorMessage":"Bad things happened","stackTrace":["  File \"/var/task/handler.py\", line 7, in handler\n    raise TestException('Bad things happened')\n"]}. Output:
START RequestId: 15f70b68-e795-1e5d-fc40-7ff7aa4df650 Version: $LATEST
    raise TestException('Bad things happened')ler
END RequestId: 15f70b68-e795-1e5d-fc40-7ff7aa4df650
REPORT RequestId: 15f70b68-e795-1e5d-fc40-7ff7aa4df650	Init Duration: 82.84 ms	Duration: 4.12 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 23 MB	 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 527, in run_lambda
    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 136, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 128, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 143, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 139, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 121, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 109, in _run
    result = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 264, in _execute
    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 173, in run_lambda_executor
    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
Exception: Lambda process returned error status code: 1. Result: {"errorType":"TestException","errorMessage":"Bad things happened","stackTrace":["  File \"/var/task/handler.py\", line 7, in handler\n    raise TestException('Bad things happened')\n"]}. Output:
START RequestId: 15f70b68-e795-1e5d-fc40-7ff7aa4df650 Version: $LATEST
    raise TestException('Bad things happened')ler
END RequestId: 15f70b68-e795-1e5d-fc40-7ff7aa4df650
REPORT RequestId: 15f70b68-e795-1e5d-fc40-7ff7aa4df650	Init Duration: 82.84 ms	Duration: 4.12 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 23 MB
```

I deleted my local images of localstack & `lambci/lambda:20191117-python3.7` before doing my tests to be sure I was on the latest versions and have no cache on my machine

**Comment by jjaniec** [comment]
@whummer Do you have any updates on this please ?
