### ISSUE TITLE
Can not connect to kinesalite running with --ssl

### ISSUE THREAD

**Issue by tigstep** [localstack/localstack#2574]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description
When I run the localstack through docker compose like so
` TMPDIR=/private$TMPDIR docker-compose up`
ssh into the docker container, stop the kinesalite service, start it back with --ssh flag
and try to connect to kinesis using aws like this
`AWS_ACCESS_KEY_ID=x AWS_SECRET_ACCESS_KEY=x aws --region us-east-1 --endpoint-url https://localhost:4568 kinesis create-stream --stream-name myStreamName --shard-count 1 --no-verify-ssl`

It throws
```
SSL validation failed for https://localhost:4568/ EOF occurred in violation of protocol (_ssl.c:727)
```

On the docker side I can also see
```
 2020-06-17T17:29:35:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4568/: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
localstack_main |     httplib_response = self._make_request(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
localstack_main |     six.raise_from(e, None)
localstack_main |   File "<string>", line 3, in raise_from
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
localstack_main |     httplib_response = conn.getresponse()
localstack_main |   File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
localstack_main |     response.begin()
localstack_main |   File "/usr/lib/python3.8/http/client.py", line 303, in begin
localstack_main |     version, status, reason = self._read_status()
localstack_main |   File "/usr/lib/python3.8/http/client.py", line 272, in _read_status
localstack_main |     raise RemoteDisconnected("Remote end closed connection without"
localstack_main | http.client.RemoteDisconnected: Remote end closed connection without response
localstack_main | 
localstack_main | During handling of the above exception, another exception occurred:
localstack_main | 
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
localstack_main |     resp = conn.urlopen(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
localstack_main |     retries = retries.increment(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
localstack_main |     raise six.reraise(type(error), error, _stacktrace)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
localstack_main |     raise value.with_traceback(tb)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
localstack_main |     httplib_response = self._make_request(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
localstack_main |     six.raise_from(e, None)
localstack_main |   File "<string>", line 3, in raise_from
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
localstack_main |     httplib_response = conn.getresponse()
localstack_main |   File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
localstack_main |     response.begin()
localstack_main |   File "/usr/lib/python3.8/http/client.py", line 303, in begin
localstack_main |     version, status, reason = self._read_status()
localstack_main |   File "/usr/lib/python3.8/http/client.py", line 272, in _read_status
localstack_main |     raise RemoteDisconnected("Remote end closed connection without"
localstack_main | urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
localstack_main | 
localstack_main | During handling of the above exception, another exception occurred:
localstack_main | 
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 53, in index
localstack_main |     result = await run_sync(handler, request, data)
localstack_main |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 46, in run_sync
localstack_main |     return await loop.run_in_executor(THREAD_POOL, copy_context().run, func, *args)
localstack_main |   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
localstack_main |     result = self.fn(*self.args, **self.kwargs)
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 550, in handler
localstack_main |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 371, in modify_and_forward
localstack_main |     response = requests_method(request_url, data=data_to_send,
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack_main |     return request('post', url, data=data, json=json, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_main |     return session.request(method=method, url=url, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
localstack_main |     resp = self.send(prep, **send_kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
localstack_main |     r = adapter.send(request, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
localstack_main |     raise ConnectionError(err, request=request)
localstack_main | requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))


...

## Expected behavior
I would expect the `--no-verify-ssl` to make this call succeed
...

## Actual behavior
The connection is failing.
...

# Steps to reproduce
1) ` TMPDIR=/private$TMPDIR docker-compose up`

2) `AWS_ACCESS_KEY_ID=x AWS_SECRET_ACCESS_KEY=x aws --region us-east-1 --endpoint-url https://localhost:4568 kinesis create-stream --stream-name myStreamName --shard-count 1 --no-verify-ssl`

## Command used to start LocalStack
` TMPDIR=/private$TMPDIR docker-compose up`
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
I have also installed and ran 
`awslocal kinesis list-streams`
Getting 
`An error occurred (500) when calling the ListStreams operation (reached max retries: 4): `
...

**Comment by tigstep** [comment]
Another thing that I am noticing is than while starting the container

I see there are exceptions like so

```
2020-06-17T20:34:21:INFO:localstack_ext.bootstrap.install: Unable to download local test SSL certificate to /tmp/localstack/server.test.pem: MyHTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /localstack/localstack-artifacts/raw/master/local-certs/server.key (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')"))) Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 488, in wrap_socket
localstack_main |     cnx.do_handshake()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1806, in do_handshake
localstack_main |     self._raise_ssl_error(self._ssl, result)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1539, in _raise_ssl_error
localstack_main |     raise SysCallError(-1, "Unexpected EOF")
localstack_main | OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')
localstack_main | 
localstack_main | During handling of the above exception, another exception occurred:
localstack_main | 
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
localstack_main |     httplib_response = self._make_request(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
localstack_main |     self._validate_conn(conn)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
localstack_main |     conn.connect()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 361, in connect
localstack_main |     self.sock = ssl_wrap_socket(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
localstack_main |     return context.wrap_socket(sock, server_hostname=server_hostname)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 494, in wrap_socket
localstack_main |     raise ssl.SSLError("bad handshake: %r" % e)
localstack_main | ssl.SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)
localstack_main | 
localstack_main | During handling of the above exception, another exception occurred:
localstack_main | 
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
localstack_main |     resp = conn.urlopen(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
localstack_main |     retries = retries.increment(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
localstack_main |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
localstack_main | urllib3.exceptions.MaxRetryError: MyHTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /localstack/localstack-artifacts/raw/master/local-certs/server.key (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
localstack_main | 
localstack_main | During handling of the above exception, another exception occurred:
localstack_main | 
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/bootstrap/install.py", line 66, in setup_ssl_cert
localstack_main |     download(SSL_CERT_URL,target_file)
localstack_main |   File "/opt/code/localstack/localstack/utils/common.py", line 628, in download
localstack_main |     r = s.get(url, stream=True, verify=verify_ssl)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
localstack_main |     return self.request('GET', url, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
localstack_main |     resp = self.send(prep, **send_kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
localstack_main |     r = adapter.send(request, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
localstack_main |     raise SSLError(e, request=request)
localstack_main | requests.exceptions.SSLError: MyHTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /localstack/localstack-artifacts/raw/master/local-certs/server.key (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
```

**Comment by whummer** [comment]
Thanks for reporting this issue @tigstep . The change in #2584 should fix the permission issue - we'll also push another fix soon to resolve the download issue from github.com (I'm assuming you are in a corporate or private network that doesn't permit access to certain domains like github.com?). Can you please give it another try with the `latest` Docker image - please report here if the permission issue persists. Thanks

**Comment by tigstep** [comment]
Thanks 👍
