### ISSUE TITLE
Cloudformation does not work

### ISSUE THREAD

**Issue by murali2904** [localstack/localstack#2607]
# Type of request: This is a ...

[ ] bug report
[ ] feature request

# Detailed description

Not able to run cloudformation and it is not listing any buckets as well.

...'Status'
[ec2-user@ip-172-31-92-0 ~]$ aws --endpoint-url=http://localhost:4566 cloudformation deploy --template-file /home/ec2-user/Rootstack-amplify.yaml --stack-name TestStack3

Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

[ec2-user@ip-172-31-92-0 ~]$ aws --endpoint-url=http://localhost:4566 s3 ls
[ec2-user@ip-172-31-92-0 ~]$

[ec2-user@ip-172-31-92-0 ~]$

## Expected behavior

...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack
docker run -d -e HOSTNAME="localhost" -e LOCALSTACK_HOSTNAME="localhost" -e TEST_AWS_ACCOUNT_ID="480757267634" -e AWS_DEFAULT_REGION="eu-west-1" -e REGION="eu-west-1" -p 4566:4566 --rm --privileged --name localstack_main -p 4608-4610:4608-4610 -p 4611-4612:4611-4612 -p 4613-4616:4613-4616 -p 4617-4619:4617-4619 -p 4620:4620 -p 8080-8081:8080-8081 -p 12121:12121 -p 4567-4570:4567-4570 -p 4571-4574:4571-4574 -p 4575:4575 -p 4576-4578:4576-4578 -p 4579-4580:4579-4580 -p 4581-4585:4581-4585 -p 4586-4588:4586-4588 -p 4589-4592:4589-4592 -p 4593:4593 -p 4594-4596:4594-4596 -p 4597-4598:4597-4598 -p 4599-4601:4599-4601 -p 4602-4603:4602-4603 -p 4604-4606:4604-4606 -p 4607:4607  -v "/opt/localstack:/opt/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/opt/localstack" "localstack/localstack"

I have installed docker on ec2 instance and have enabled tunneling to my localhost and able to access from web browser and it says services is running.
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by murali2904** [comment]
I enabled debug mode for the command and found this output.

access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'content-type': 'text/html; charset=utf-8'}
2020-06-23 10:29:33,426 - MainThread - botocore.parsers - DEBUG - Response body:
<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
  <Error>
    <Type>Sender</Type>
    <Code>ValidationError</Code>
    <Message>Stack with id arn:aws:cloudformation:eu-west-1:480757267634:changeSet/awscli-cloudformation-package-deploy-1592908173/3379f7e7-725b-430d-b9e1-ee6dbb124113 does not exist</Message>
  </Error>
  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>
</ErrorResponse>
2020-06-23 10:29:33,427 - MainThread - botocore.hooks - DEBUG - Event needs-retry.cloudformation.DescribeChangeSet: calling handler <botocore.retryhandler.RetryHandler object at 0x7f11ca4ce210>
2020-06-23 10:29:33,427 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2020-06-23 10:29:33,427 - MainThread - awscli.customizations.cloudformation.deployer - DEBUG - Create changeset waiter exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/awscli/customizations/cloudformation/deployer.py", line 163, in wait_for_changeset
    WaiterConfig=waiter_config)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/botocore/waiter.py", line 53, in wait
    Waiter.wait(self, **kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/botocore/waiter.py", line 323, in wait
    last_response=response,
WaiterError: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state
2020-06-23 10:29:33,429 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 217, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 358, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/lib/python2.7/dist-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/lib/python2.7/dist-packages/awscli/customizations/cloudformation/deploy.py", line 295, in _run_main
    parsed_args.fail_on_empty_changeset)
  File "/usr/lib/python2.7/dist-packages/awscli/customizations/cloudformation/deploy.py", line 310, in deploy
    tags=tags
  File "/usr/lib/python2.7/dist-packages/awscli/customizations/cloudformation/deployer.py", line 227, in create_and_wait_for_changeset
    self.wait_for_changeset(result.changeset_id, stack_name)
  File "/usr/lib/python2.7/dist-packages/awscli/customizations/cloudformation/deployer.py", line 168, in wait_for_changeset
    status = resp["Status"]
KeyError: 'Status'
2020-06-23 10:29:33,432 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255
====================================================

This one for s3 bucket command

aws --debug --endpoint-url=http://localhost:4566 s3 ls

7f410>
2020-06-23 10:38:45,510 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.ListBuckets: calling handler <bound method S3EndpointSetter.set_endpoint of <botocore.utils.S3EndpointSetter object at 0x7f63b995cbd0>>
2020-06-23 10:38:45,510 - MainThread - botocore.utils - DEBUG - Using S3 path style addressing.
2020-06-23 10:38:45,510 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2020-06-23 10:38:45,510 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/

host:localhost:4566
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20200623T103845Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2020-06-23 10:38:45,511 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20200623T103845Z
20200623/eu-west-1/s3/aws4_request
0016696bca76bde9af53930f06cbcfb948dc9cdf109db11ac54a44c2548eaa6a
2020-06-23 10:38:45,511 - MainThread - botocore.auth - DEBUG - Signature:
34814530311f087c4b35cdd93ab736ee2e6f193e0fe45ffbbd39f2455b521b98
2020-06-23 10:38:45,511 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=GET, url=http://localhost:4566/, headers={'X-Amz-Content-SHA256': 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': 'AWS4-HMAC-SHA256 Credential=temp/20200623/eu-west-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=34814530311f087c4b35cdd93ab736ee2e6f193e0fe45ffbbd39f2455b521b98', 'X-Amz-Date': '20200623T103845Z', 'User-Agent': 'aws-cli/1.18.13 Python/2.7.16 Linux/4.14.177-107.254.amzn1.x86_64 botocore/1.17.8'}>
2020-06-23 10:38:45,512 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:4566
2020-06-23 10:38:45,526 - MainThread - urllib3.connectionpool - DEBUG - http://localhost:4566 "GET / HTTP/1.1" 200 None
2020-06-23 10:38:45,527 - MainThread - botocore.parsers - DEBUG - Response headers: {'transfer-encoding': 'chunked', 'access-control-allow-headers': 'authorization,content-type,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'content-language': 'en-US', 'access-control-expose-headers': 'x-amz-version-id', 'x-amz-id-2': 'MzRISOwyjmnupF6B540264FC67C237/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp', 'accept-ranges': 'bytes', 'server': 'hypercorn-h11', 'last-modified': 'Tue, 23 Jun 2020 10:38:45 GMT', 'connection': 'close', 'x-amz-request-id': 'F6B540264FC67C23', 'cache-control': 'no-cache', 'date': 'Tue, 23 Jun 2020 10:38:45 GMT', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'content-type': 'application/xml; charset=utf-8'}
2020-06-23 10:38:45,528 - MainThread - botocore.parsers - DEBUG - Response body:
<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01"><Owner><ID>bcaf1ffd86f41161ca5fb16fd081034f</ID><DisplayName>webfile</DisplayName></Owner><Buckets></Buckets></ListAllMyBucketsResult>
2020-06-23 10:38:45,528 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListBuckets: calling handler <botocore.retryhandler.RetryHandler object at 0x7f63b995ca50>
2020-06-23 10:38:45,529 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2020-06-23 10:38:45,529 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListBuckets: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7f63b995ca90>>
2020-06-23 10:38:45,529 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListBuckets: calling handler <function enhance_error_msg at 0x7f63ba0c7500>

**Comment by bitnot** [comment]
Hey @murali2904 , which version are you running?

**Comment by murali2904** [comment]
(. .venv/bin/activate; bin/localstack web)
(. .venv/bin/activate; exec bin/localstack start --host)
2020-06-23 09:26:50,753 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
LocalStack version: 0.11.2
LocalStack version: 0.11.2

**Comment by pavel-is24** [comment]
never mind, I see it's the latest. Could you try `localstack/localstack:0.11.2`?
I have seen some weird behaviour with the `latest` tag today, not sure if it's related.

**Comment by bitnot** [comment]
Could you try localstack/localstack:0.11.2?
I have seen some weird behaviour with the latest tag today, not sure if it's related.

**Comment by murali2904** [comment]
ok let me try and update.

**Comment by murali2904** [comment]
Thanks it worked.

Now i am getting different issue when creating DynamoDB .

localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 374, in parse_and_create_resource
localstack_1  |     resource.type = resource_type
localstack_1  | AttributeError: 'NoneType' object has no attribute 'type'


![image](https://user-images.githubusercontent.com/60002593/85543017-96449e00-b611-11ea-9a93-b3bfc6b93735.png)
[
![dberror](https://user-images.githubusercontent.com/60002593/85543191-bd02d480-b611-11ea-8335-7cd4a141123c.png)
](url)


Thanks

Murali

**Comment by murali2904** [comment]
The same stack works fine in cloudformation without any issues but it fails with localstack.

**Comment by whummer** [comment]
Thanks for reporting this issue @murali2904 . Do you think you could share the relevant portion(s) of your `Rootstack-amplify.yaml` CloudFormation stack file, to help reproduce this issue? Thanks

**Comment by murali2904** [comment]
[

](url)

**Comment by murali2904** [comment]
[DynamoDBstack-amplify.txt](https://github.com/localstack/localstack/files/4827099/DynamoDBstack-amplify.txt)
[Rootstack-amplify.txt](https://github.com/localstack/localstack/files/4827100/Rootstack-amplify.txt)

**Comment by murali2904** [comment]
Hi Team,

Any update on this issue?

Thanks
Murali

**Comment by denissabramovs** [comment]
bump

**Comment by denissabramovs** [comment]
bump

**Comment by denissabramovs** [comment]
bump

**Comment by whummer** [comment]
@denissabramovs Please stop bumping this thread - we are aware of this issue and will tackle it asap, based on priority of other issues in the backlog. If it is very urgent for you, please feel free to look into this issue yourself - pull requests are very much appreciated! Thanks

**Comment by whummer** [comment]
Thanks for the update @murali2904 @denissabramovs . This issue should be fixed in #2644 - can you please give it another try with the `latest` version of the Docker image. Please report here if the problem persists. Thanks

**Comment by murali2904** [comment]
Sure, we will give a try and let you know.

**Comment by denissabramovs** [comment]
Thank you.
