### ISSUE TITLE
Question: NewConnectionError when running from master but not at version 0.7.4.3

### ISSUE THREAD

**Issue by migurski** [localstack/localstack#261]
I’m seeing a `NewConnectionError` error when I run localstack from Github at ae72427 that doesn’t occur when I run it from PyPI at 0.7.4.3. This exception is logged at start time, prior to any requests. Subsequent requests work just fine, but the stack trace is alarming. Why is this different between these two versions?

- Python: 3.6.0 under virtualenv
- OS: Mac 10.12.5 Sierra
- Installed with: `pip install -e .`
- Command: `env SERVICES=s3,lambda LAMBDA_EXECUTOR=docker localstack start`

Output:

```
Starting local dev environment. CTRL-C to quit.
Starting mock S3 (http port 4572)...
Starting mock Lambda service (http port 4574)...

2017-08-24T15:54:07:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110ddbbe0>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/private/tmp/.venv-locallocalstack/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/private/tmp/.venv-locallocalstack/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/private/tmp/.venv-locallocalstack/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/.venv-locallocalstack/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/private/tmp/.venv-locallocalstack/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/private/tmp/.venv-locallocalstack/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/private/tmp/.venv-locallocalstack/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x110ddbbe0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/.venv-locallocalstack/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/private/tmp/.venv-locallocalstack/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/private/tmp/.venv-locallocalstack/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110ddbbe0>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/localstack/localstack/services/generic_proxy.py", line 185, in forward
    headers=forward_headers)
  File "/private/tmp/.venv-locallocalstack/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/private/tmp/.venv-locallocalstack/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/private/tmp/.venv-locallocalstack/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/private/tmp/.venv-locallocalstack/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/private/tmp/.venv-locallocalstack/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110ddbbe0>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

**Comment by migurski** [comment]
I think I’ve tracked this down to a faulty `LOCALSTACK_VENV_FOLDER`: `bin/moto_server` is not correctly found when the virtualenv directory is named something other than `.venv` or location in the current working directory.

**Comment by whummer** [comment]
Thanks for the detailed report @migurski . Generally it's not recommended to mix the two installation approaches (pip install and git clone).

General recommendation is to use either:
* `pip install` and `localstack start` If you simply want to _use_ LocalStack
* `git clone`, `make install` and `make infra` if you want a development environment and make changes to the code.

Have you been able to get it working in your local environment? Would be great if you could raise a PR with a few notes in the Troubleshooting section of the README. I'm leaning towards closing this issue, but please let us know if you have any specific suggestions how we could improve the dev environment setup. Thanks!

**Comment by migurski** [comment]
I’ve been able to get it working, once I determined that the venv directory name was an issue. I’ll try to modify my local setup to follow your suggestions.

**Comment by migurski** [comment]
Followup question: is `LOCALSTACK_VENV_FOLDER` needed at all to find `moto_server`? It’s in the `$PATH` and should be executable directly. Maybe this venv directory detection can be entirely removed?

**Comment by whummer** [comment]
Closing this as outdated - recommended installation these days is to start in Docker.
