### ISSUE TITLE
Serverless Api resource creation errors without explicit Name property in CloudFormation template

### ISSUE THREAD

**Issue by rikbruil** [localstack/localstack#2641]
# Type of request: This is a ...

[x] bug report
[  ] feature request

# Detailed description

When creating a CloudFormation stack in Localstack using a Serverless Api resource, it requires us to explicitly pass a Name property on the Api resource. This conflicts with how real AWS CloudFormation behaves, where it won't complain about a missing name but will autogenerate one for you.

## Expected behavior

When executing the template against real AWS CloudFormation, it will auto-generate a name for the Api resource. We normally leave the Name property blank, since passing this property will prevent resources from being updated in the future.

The expected behaviour would be that Localstack follows the real AWS implementation here.

## Actual behavior

Localstack errors with a `KeyError: Name` error during stack creation instead of generating a name automagically:

```
localstack_main | 2020-06-29T11:57:11:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected error retrieving details for resource ApiGateway::RestApi: 'Name' Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 737, in retrieve_resource_details
localstack_main |     api_name = resource_props['Name'] if resource else resource_id
localstack_main | KeyError: 'Name'
localstack_main |  - {'Type': 'AWS::ApiGateway::RestApi', 'Properties': {'Body': {'swagger': '2.0', 'info': {'version': '1.0', 'title': 'automation'}, 'paths': {'/': {'get': {'x-amazon-apigateway-integration': {'type': 'aws_proxy', 'httpMethod': 'POST', 'uri': 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:automation-Lambda-4F0VUFQ6EM0M/invocations'}, 'responses': {}}}}}}} {}
localstack_main | 2020-06-29T11:57:11:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "Api": 'Name' Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 215, in parse_and_create_resource
localstack_main |     return _parse_and_create_resource(
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 299, in _parse_and_create_resource
localstack_main |     raise moto_create_error
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 281, in _parse_and_create_resource
localstack_main |     resource = parse_and_create_resource_orig(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 372, in parse_and_create_resource
localstack_main |     resource = resource_class.create_from_cloudformation_json(
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 700, in RestAPI_create_from_cloudformation_json
localstack_main |     name = props['Name']
localstack_main | KeyError: 'Name'
localstack_main | 
localstack_main | 2020-06-29T11:57:11:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "LambdaApiEventPermissionprod": 'Name' Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 215, in parse_and_create_resource
localstack_main |     return _parse_and_create_resource(
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 244, in _parse_and_create_resource
localstack_main |     resource_tuple = parsing.parse_resource(logical_id, resource_json, resources_map)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 341, in parse_resource
localstack_main |     resource_json = clean_json(resource_json, resources_map)
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 199, in clean_json
localstack_main |     result = clean_json_orig(resource_json, resources_map)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 286, in clean_json
localstack_main |     cleaned_val = clean_json(value, resources_map)
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 199, in clean_json
localstack_main |     result = clean_json_orig(resource_json, resources_map)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 286, in clean_json
localstack_main |     cleaned_val = clean_json(value, resources_map)
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 199, in clean_json
localstack_main |     result = clean_json_orig(resource_json, resources_map)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 286, in clean_json
localstack_main |     cleaned_val = clean_json(value, resources_map)
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 199, in clean_json
localstack_main |     result = clean_json_orig(resource_json, resources_map)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 293, in clean_json
localstack_main |     return [clean_json(val, resources_map) for val in resource_json]
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 293, in <listcomp>
localstack_main |     return [clean_json(val, resources_map) for val in resource_json]
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 199, in clean_json
localstack_main |     result = clean_json_orig(resource_json, resources_map)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 286, in clean_json
localstack_main |     cleaned_val = clean_json(value, resources_map)
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 199, in clean_json
localstack_main |     result = clean_json_orig(resource_json, resources_map)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 179, in clean_json
localstack_main |     resource = resources_map[resource_json["Ref"]]
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 499, in __getitem__
localstack_main |     new_resource = parse_and_create_resource(
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 215, in parse_and_create_resource
localstack_main |     return _parse_and_create_resource(
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 299, in _parse_and_create_resource
localstack_main |     raise moto_create_error
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 281, in _parse_and_create_resource
localstack_main |     resource = parse_and_create_resource_orig(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 372, in parse_and_create_resource
localstack_main |     resource = resource_class.create_from_cloudformation_json(
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 700, in RestAPI_create_from_cloudformation_json
localstack_main |     name = props['Name']
localstack_main | KeyError: 'Name'
```

# Steps to reproduce

## Command used to start LocalStack

Using the Docker image (latest version we tried was 0.11.3, but this behaviour also occurs in 0.10.x range).

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal cloudformation create-stack --stack-name "automation"  --template-body "file://cloudformation.yaml"
```

Sample CloudFormation template to trigger the error (taken from [AWS documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-resource-api--examples--simpleapiexample)):

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with a simple API definition
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: Api
      Runtime: python3.7
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
            return {'body': 'Hello World!', 'statusCode': 200}
```

**Comment by whummer** [comment]
Thanks for the detailed report @rikbruil . This should be fixed in #2848 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks
