### ISSUE TITLE
simple async lambda client throws NPE via TransformingAsyncResponseHandler#onError

### ISSUE THREAD

**Issue by bmiddleb** [localstack/localstack#2654]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
LocalStack subscription: Pro Edition
MacBook Pro: Catalina
IntelliJ 2020.1
SpringBoot 2.3.1
Gradle 6
Java 8

I am getting “Error thrown from TransformingAsyncResponseHandler#onError” along with an NPE in AsyncResponseHandler.onError. There is a known problem with the AWS SDK but changing version, as suggested, didn’t resolve the problem. It occurs for all 5 of the versions I spot-checked all the way back to 2.5.1

build.gradle:
dependencies {
    implementation platform('software.amazon.awssdk:bom:2.13.47')
    implementation platform('com.amazonaws:aws-xray-recorder-sdk-bom:2.6.1')
    implementation 'software.amazon.awssdk:lambda'
starting with the aws GitHub “blank_java” sample project as the code base. (edited) 
...

## Expected behavior
return valid response from lambdaAsyncClient.getAccountSettings
...

## Actual behavior
2020-06-30 17:01:04.235 ERROR 37227 --- [    Test worker] s.a.a.c.i.h.BaseAsyncClientHandler       : Error thrown from TransformingAsyncResponseHandler#onError, ignoring.

java.lang.NullPointerException: null
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.onError(AsyncResponseHandler.java:76) ~[sdk-core-2.13.47.jar:na]
	at software.amazon.awssdk.core.internal.http.async.CombinedResponseAsyncHttpResponseHandler.onError(CombinedResponseAsyncHttpResponseHandler.java:70) ~[sdk-core-2.13.47.jar:na]
	at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.lambda$doExecute$3(BaseAsyncClientHandler.java:223) [sdk-core-2.13.47.jar:na]
	at software.amazon.awssdk.utils.FunctionalUtils.runAndLogError(FunctionalUtils.java:40) ~[utils-2.13.47.jar:na]
	at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.doExecute(BaseAsyncClientHandler.java:220) [sdk-core-2.13.47.jar:na]
	at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.execute(BaseAsyncClientHandler.java:86) [sdk-core-2.13.47.jar:na]
	at software.amazon.awssdk.awscore.client.handler.AwsAsyncClientHandler.execute(AwsAsyncClientHandler.java:52) [aws-core-2.13.47.jar:na]
	at software.amazon.awssdk.services.lambda.DefaultLambdaAsyncClient.getAccountSettings(DefaultLambdaAsyncClient.java:1035) [lambda-2.13.47.jar:na]
	at example.Handler.<init>(Handler.java:38) [main/:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_131]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_131]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_131]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [na:1.8.0_131]
...

# Steps to reproduce
Clone AWS samples here: https://github.com/awsdocs/aws-lambda-developer-guide/tree/master/sample-apps/blank-java
Import the "blank-java" project into IntelliJ
Either use docker-compose or an initializer to start the localstack docker container. I used the latter (see below)
resulting in: 17:01:02.894 [Test worker] INFO 🐳 [localstack/localstack:0.8.6] - Container **localstack/localstack:0.8.6** started

## Command used to start LocalStack
Test extends the following class...
@ContextConfiguration(initializers = BaseTestAwsIntegrator.Initializer.class )
public class BaseTestAwsIntegrator
{
    private static LocalStackContainer localStackContainer =
        new LocalStackContainer().withServices( LocalStackContainer.Service.LAMBDA );

    static { localStackContainer.start(); }

    @Configuration
    public static class Initializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {
        @Override
        public void initialize( ConfigurableApplicationContext configurableApplicationContext ) {
            TestPropertyValues values = TestPropertyValues.of(
                "aws-access.endpointUri"
                    + localStackContainer.getEndpointConfiguration( LocalStackContainer.Service.LAMBDA )
                    .getServiceEndpoint() );

                values.applyTo( configurableApplicationContext );
        }
    }
}
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
@Component
public class Handler implements RequestHandler<SQSEvent, String> {
    private static final Logger logger = LoggerFactory.getLogger(Handler.class);
    private static final Gson gson = new GsonBuilder().setPrettyPrinting().create();
    private final LambdaAsyncClient lambdaAsyncClient;

    @Autowired
    public Handler(LambdaAsyncClient lambdaAsyncClient) {
        if ( lambdaAsyncClient == null ) throw new IllegalArgumentException("lambdaAsyncClient "
            + "not autowired");
        else log.debug( "lambdaAsyncClient autowired" );

        GetAccountSettingsResponse settings;
        this.lambdaAsyncClient = lambdaAsyncClient;

        CompletableFuture<GetAccountSettingsResponse> accountSettings =
            this.lambdaAsyncClient.getAccountSettings(
                GetAccountSettingsRequest.builder().build());

        try {
            if ( accountSettings != null ) {
                while( ! accountSettings.isDone() ) Thread.sleep(1000);
                settings = accountSettings.get();

                String statusMsg = "Lambda ";
                if ( settings.sdkHttpResponse().isSuccessful() ) statusMsg += "succeeded";
                else statusMsg += "failed";
                log.debug( statusMsg );
                log.debug( settings.sdkHttpResponse().toString() );
            }
            else {
                throw new IllegalStateException("accountSettings null");
            }

        } catch (InterruptedException e) {
            log.error( e.getMessage() );
        } catch (Exception e) {
            log.error( e.getMessage() );
        }
    }

    @Override
    public String handleRequest(SQSEvent event, Context context) {
        String response = new String();

        // call Lambda API
        logger.info("Getting account settings");

        CompletableFuture<GetAccountSettingsResponse> accountSettings =
                lambdaAsyncClient.getAccountSettings(GetAccountSettingsRequest.builder().build());

        // log execution details
        logger.info("ENVIRONMENT VARIABLES: {}", gson.toJson(System.getenv()));
        logger.info("CONTEXT: {}", gson.toJson(context));
        logger.info("EVENT: {}", gson.toJson(event));

        // process event
        for (SQSMessage msg : event.getRecords()) {
            logger.info(msg.getBody());
        }

        // process Lambda API response
        try {
            GetAccountSettingsResponse settings = accountSettings.get();
            response = gson.toJson(settings.accountUsage());
            logger.info("Account usage: {}", response);

        } catch (Exception e) {
            e.getStackTrace();
        }

        return response;
    }
}
...

**Comment by bmiddleb** [comment]
This turned out to be a TestContainer version mismatch issue.
