### ISSUE TITLE
cloudformation updateStack: type object 'FakeBucket' has no attribute 'update_from_cloudformation_json'

### ISSUE THREAD

**Issue by Mindez** [localstack/localstack#2658]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

Localstack CloudFormation returns a 500 error on the updateStack operation in cloudformation, even for very simple stacks consisting of just one S3 bucket. I have tried this using Route53 Hosted Zones as well, and get the same error with 'FakeZone' instead of 'FakeBucket'. Update Stack operations always seem to fail with this error.

## Expected behavior

The stack successfully updates with the new parameters provided in the updateStack operation.

## Actual behavior

A 500 error is returned with no message.
In the debug logs the following error is displayed:
```
localstack                   | 2020-07-02 06:53:18,229:API: Error on request:
localstack                   | Traceback (most recent call last):
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
localstack                   |     execute(self.server.app)
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
localstack                   |     application_iter = app(environ, start_response)
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 163, in __call__
localstack                   |     return backend_app(environ, start_response)
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
localstack                   |     return self.wsgi_app(environ, start_response)
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
localstack                   |     response = self.handle_exception(e)
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack                   |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
localstack                   |     reraise(exc_type, exc_value, tb)
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack                   |     raise value
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
localstack                   |     response = self.full_dispatch_request()
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
localstack                   |     rv = self.handle_user_exception(e)
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack                   |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
localstack                   |     reraise(exc_type, exc_value, tb)
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack                   |     raise value
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
localstack                   |     rv = self.dispatch_request()
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
localstack                   |     return self.view_functions[rule.endpoint](**req.view_args)
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 146, in __call__
localstack                   |     result = self.callback(request, request.url, {})
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 199, in dispatch
localstack                   |     return cls()._dispatch(*args, **kwargs)
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 304, in _dispatch
localstack                   |     return self.call_action()
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 389, in call_action
localstack                   |     response = method()
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/responses.py", line 321, in update_stack
localstack                   |     stack = self.cloudformation_backend.update_stack(
localstack                   |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 458, in cf_update_stack
localstack                   |     stack = cf_update_stack_orig(*args, **kwargs)
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/models.py", line 711, in update_stack
localstack                   |     stack.update(template, role_arn, parameters=parameters, tags=tags)
localstack                   |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 831, in update
localstack                   |     stack_update_orig(self, *args, **kwargs)
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/models.py", line 354, in update
localstack                   |     self.resource_map.update(self.template_dict, parameters)
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 705, in update
localstack                   |     raise last_exception
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 693, in update
localstack                   |     changed_resource = parse_and_update_resource(
localstack                   |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 225, in parse_and_update_resource
localstack                   |     return _parse_and_create_resource(logical_id, resource_json, resources_map, region_name, update=True)
localstack                   |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 278, in _parse_and_create_resource
localstack                   |     parse_and_update_resource_orig(logical_id, resource_json_arns_fixed, resources_map, region_name)
localstack                   |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 390, in parse_and_update_resource
localstack                   |     new_resource = resource_class.update_from_cloudformation_json(
localstack                   | AttributeError: type object 'FakeBucket' has no attribute 'update_from_cloudformation_json'
```

# Steps to reproduce

## Command used to start LocalStack

The following docker-compose parameters are used to start LocalStack:
```
  localstack:
    container_name: localstack
    image: localstack/localstack
    privileged: true
    ports:
      - "4566:4566"
      - "9070:9070"
    environment:
      SERVICES: route53,sqs,cloudformation,s3
      PORT_WEB_UI: 9070
      DEBUG: cloudformation
      NODE_ENV: 'local'
      HOSTNAME: 'localhost'
      DEFAULT_REGION: 'eu-west-1'
      HOSTNAME_EXTERNAL: 'localstack'
    networks:
      my_network:
        aliases:
          - localstack
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/localstack:/tmp/localstack
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

The following simple parameterised stack is used:

```
AWSTemplateFormatVersion: "2010-09-09"
Description: Test Stack for Localstack

Parameters:
  DummyParam:
    Type: String

Resources:
  HelloBucket:
    Type: AWS::S3::Bucket
    Parameters:
      BucketName: !Ref DummyParam
```

The stack is created using the following in nodeJS:

```
   import { CloudFormation } from 'aws-sdk'
   ...
   this.cloudFormation = new CloudFormation({ endpoint: 'http://localhost:4566', region: 'eu-west-1'})
   ...
   await this.cloudFormation.createStack({
      StackName: 'dummy-stack',
      TemplateBody: await this.getStackTemplate(),
      Parameters: { ParameterKey: 'DummyParam', ParameterValue: 'test' }
   }).promise()
```

The stack is then updated using the following in nodeJS:

```
   import { CloudFormation } from 'aws-sdk'
   ...
   this.cloudFormation = new CloudFormation({ endpoint: 'http://localhost:4566', region: 'eu-west-1'})
   ...
   await this.cloudFormation.updateStack({
      StackName: 'dummy-stack',
      TemplateBody: await this.getStackTemplate(),
      Parameters: { ParameterKey: 'DummyParam', ParameterValue: 'test2' }
   }).promise()
```

**Comment by Mindez** [comment]
Apologies, this was an issue on my end - issue has now been fixed.

Stack was not a valid stack. I had 'Parameters' instead of 'Properties' in the bucket.

Issue closed.
