### ISSUE TITLE
Cannot create multiple permissions for lambda

### ISSUE THREAD

**Issue by loganasherjones** [localstack/localstack#2661]
# Type of request: This is a ...

[ x ] bug report
[ ] feature request

# Detailed description

I tried to allow two different AWS accounts to execute the same lambda but get this error when trying to create the 2nd permission:

```
An error occurred (500) when calling the AddPermission operation (reached max retries: 2): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

## Expected behavior

I expected to be able to create both permissions.

## Actual behavior

When trying to create the 2nd permission, I get the following error

```
An error occurred (500) when calling the AddPermission operation (reached max retries: 2): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

And here is the stack trace in localstack:

```
localstack_1     | 2020-07-02T13:59:34:ERROR:lambda_api: Exception on /2015-03-31/functions/my-function/policy [POST]
localstack_1     | Traceback (most recent call last):
localstack_1     |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
localstack_1     |     response = self.full_dispatch_request()
localstack_1     |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
localstack_1     |     rv = self.handle_user_exception(e)
localstack_1     |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_1     |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1     |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
localstack_1     |     reraise(exc_type, exc_value, tb)
localstack_1     |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_1     |     raise value
localstack_1     |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
localstack_1     |     rv = self.dispatch_request()
localstack_1     |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
localstack_1     |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_1     |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1148, in add_permission
localstack_1     |     iam_client.create_policy(PolicyName=POLICY_NAME_PATTERN % function,
localstack_1     |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
localstack_1     |     return self._make_api_call(operation_name, kwargs)
localstack_1     |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 635, in _make_api_call
localstack_1     |     raise error_class(parsed_response, operation_name)
localstack_1     | botocore.errorfactory.EntityAlreadyExistsException: An error occurred (EntityAlreadyExists) when calling the CreatePolicy operation: A policy called lambda_policy_my-function already exists. Duplicate names are not allowed.

```

# Steps to reproduce

## Command used to start LocalStack

**docker-compose.yml**
```
version: "2.1"

services:
  localstack:
    image: localstack/localstack:0.11.3
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=lambda,iam,kinesis
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker-reuse
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Spin everything up:

```
docker-compose up - d
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

**policy.json**
```
{
    "Version": "2012-10-17",
    "Statement": [
      {
        "Action": "sts:AssumeRole",
        "Principal": {
          "Service": "lambda.amazonaws.com"
        },
        "Effect": "Allow",
        "Sid": ""
      }
    ]
}
```

Create the IAM Policy:
```
aws iam create-role --role-name Test-Role --assume-role-policy-document file://policy.json
```

Create the lambda function:

```
echo "def handler(event, context): pass" > my_function.py
zip my_function.zip my_function.py
aws lambda create-function \
    --function-name my-function \
    --runtime python3.8 \
    --zip-file fileb://my_function.zip \
    --handler my_function.handler \
    --role arn:aws:iam::000000000000:role/Test-Role
```

Add permissions for cloudwatch logs

```
aws lambda add-permission \
    --function-name my-function \
    --action lambda:InvokeFunction \
    --statement-id logs \
    --principal logs.amazonaws.com
{
    "Statement": "logs"
}
```

Try to create another permission for kinesis:

```
aws lambda add-permission \
    --function-name my-function \
    --action lambda:InvokeFunction \
    --statement-id kinesis \
    --principal kinesis.amazonaws.com

An error occurred (500) when calling the AddPermission operation (reached max retries: 2): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

**Comment by whummer** [comment]
Thanks for reporting @loganasherjones . This should be fixed in #2663 - can you please give it a try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
