### ISSUE TITLE
[bug report] 500 error with POST 0.0.0.0/graph endpoint to get the resources graph

### ISSUE THREAD

**Issue by Vaunorage** [localstack/localstack#2675]
# Detailed description
500 error with POST 0.0.0.0/graph endpoint to get the resources graph

# Steps to reproduce

curl http://127.0.0.1:4566/graph -X POST
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

# Result
Waiting for all LocalStack services to be ready
2020-07-05 18:09:45,830 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-07-05 18:09:45,836 INFO supervisord started with pid 14
2020-07-05 18:09:46,841 INFO spawned: 'dashboard' with pid 20
2020-07-05 18:09:46,851 INFO spawned: 'infra' with pid 21
2020-07-05 18:09:46,877 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; bin/localstack web)
(. .venv/bin/activate; exec bin/localstack start --host)
2020-07-05 18:09:47,893 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
LocalStack version: 0.11.3
LocalStack version: 0.11.3
Starting local dev environment. CTRL-C to quit.
Waiting for all LocalStack services to be ready
2020-07-05T18:09:56:INFO:localstack.utils.common: Error storing key/cert SSL files (falling back to random tmp file names): [Errno 13] Permission denied: '/tmp/localstack/server.test.pem.key'
Running on 0.0.0.0:8081 over https (CTRL + C to quit)
2020-07-05T18:09:58:INFO:localstack.services.install: Downloading and installing local KMS server. This may take some time.
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Starting edge router (https port 4566)...
Starting mock API Gateway service on http ports 4566 (recommended) and 4567 (deprecated)...
Starting mock CloudFormation service in http ports 4566 (recommended) and 4581 (deprecated)...
Starting mock CloudWatch service on http ports 4566 (recommended) and 4582 (deprecated)...
Starting mock DynamoDB service in http ports 4566 (recommended) and 4569 (deprecated)...
Starting mock DynamoDB Streams service on http ports 4566 (recommended) and 4570 (deprecated)...
Starting mock EC2 service on http ports 4566 (recommended) and 4597 (deprecated)...
Starting mock ES service on http ports 4566 (recommended) and 4578 (deprecated)...
Starting mock Firehose service on http ports 4566 (recommended) and 4573 (deprecated)...
Running on 0.0.0.0:4566 over https (CTRL + C to quit)
Running on 0.0.0.0:4567 over http (CTRL + C to quit)
2020-07-05T18:10:39:INFO:localstack.multiserver: Starting multi API server process on port 57845
Running on 0.0.0.0:57845 over http (CTRL + C to quit)
Running on 0.0.0.0:4581 over http (CTRL + C to quit)
Running on 0.0.0.0:4569 over http (CTRL + C to quit)
Starting mock IAM service on http ports 4566 (recommended) and 4593 (deprecated)...
Starting mock STS service on http ports 4566 (recommended) and 4592 (deprecated)...
Starting mock Kinesis service in http ports 4566 (recommended) and 4568 (deprecated)...
Starting mock KMS service in http ports 4566 (recommended) and 4599 (deprecated)...
Starting mock Lambda service on http ports 4566 (recommended) and 4574 (deprecated)...
Starting mock CloudWatch Logs service on http ports 4566 (recommended) and 4586 (deprecated)...
Starting mock Redshift service on http ports 4566 (recommended) and 4577 (deprecated)...
Starting mock Route53 service on http ports 4566 (recommended) and 4580 (deprecated)...
Starting mock S3 service on http ports 4566 (recommended) and 4572 (deprecated)...
Starting mock Secrets Manager service on http ports 4566 (recommended) and 4584 (deprecated)...
Starting mock SES service on http ports 4566 (recommended) and 4579 (deprecated)...
Starting mock SNS service on http ports 4566 (recommended) and 4575 (deprecated)...
Starting mock SQS service on http ports 4566 (recommended) and 4576 (deprecated)...
Starting mock SSM service on http ports 4566 (recommended) and 4583 (deprecated)...
Starting mock Cloudwatch Events service on http ports 4566 (recommended) and 4587 (deprecated)...
Starting mock StepFunctions service in http ports 4566 (recommended) and 4585 (deprecated)...
Running on 0.0.0.0:4593 over http (CTRL + C to quit)
Running on 0.0.0.0:4568 over http (CTRL + C to quit)
Running on 0.0.0.0:4599 over http (CTRL + C to quit)
Running on 0.0.0.0:4586 over http (CTRL + C to quit)
Running on 0.0.0.0:4572 over http (CTRL + C to quit)
Running on 0.0.0.0:4584 over http (CTRL + C to quit)
Running on 0.0.0.0:4575 over http (CTRL + C to quit)
Running on 0.0.0.0:4576 over http (CTRL + C to quit)
Running on 0.0.0.0:4583 over http (CTRL + C to quit)
Running on 0.0.0.0:4587 over http (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Running on 0.0.0.0:4585 over http (CTRL + C to quit)
Ready.
2020-07-05T18:13:13:INFO:localstack.services.edge: Unable to find forwarding rule for host "127.0.0.1:4566", path "/favicon.ico", target header "", auth header "", data "b''"
2020-07-05T18:15:02:INFO:localstack.services.edge: Unable to find forwarding rule for host "127.0.0.1:4566", path "/grap", target header "", auth header "", data "b''"
2020-07-05T18:15:06:ERROR:app: Exception on /graph [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/dashboard/api.py", line 39, in get_graph
    data = get_payload()
  File "/opt/code/localstack/localstack/dashboard/api.py", line 121, in get_payload
    return json.loads(common.to_str(request.data))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

## Command used to start LocalStack
docker run -it -e LOCALSTACK_HOSTNAME="localhost" -e DEFAULT_REGION="us-east-1" -e TEST_AWS_ACCOUNT_ID="000000000000" -p 4566:4566 --rm --privileged --name localstack_main -p 4567-4620:4567-4620 -p 12121:12121 -p 8080-8081:8080-8081  -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack" -e SERVICES="edge,dynamodb,cognito"

**Comment by Vaunorage** [comment]
It actually works when I do a post request with the payload : 

{
    "nameFilter":".*",
    "awsEnvironment":"dev"
}

and returns 

{
    "edges": [],
    "nodes": []
}
