### ISSUE TITLE
Restoring data for elasticsearch by persistence.py fails with UnicodeEncodeError

### ISSUE THREAD

**Issue by unimatrix01** [localstack/localstack#2679]
# Type of request: This is a bug with localstack es not starting up while trying to restore data
[x] bug report
[ ] feature request

# Detailed description
Hi,
I started localstack using the sample docker-compose, added a datadir and specified a volume.
After creating an es domain using

I inserted a lot of data using python. Data can then be queried just fine.
After stopping localstack and starting up again, restoring the data for es fails and es hangs in a startup loop with stacktrace (see below)

## Expected behavior
Localstack starting up having data from previous run restored in elasticsearch. As the data could have been inserted and queried before, restoring shouldn't hava a problem with encodings.

## Actual behavior
No startup of es, with loop of 

```
localstack_1  | 2020-07-06T06:43:19:DEBUG:localstack.services.es.es_starter: Starting local Elasticsearch (http port 4571)
localstack_1  | Running on 0.0.0.0:4571 over http (CTRL + C to quit)
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | [2020-07-06T06:43:23,377][INFO ][o.e.e.NodeEnvironment    ] [ec4ffabc1af7] using [1] data paths, mounts [[/tmp/localstack (osxfs)]], net usable_space [119.5gb], net total_space [406gb], types [fuse.osxfs]
localstack_1  | [2020-07-06T06:43:23,392][INFO ][o.e.e.NodeEnvironment    ] [ec4ffabc1af7] heap size [583.3mb], compressed ordinary object pointers [true]
localstack_1  | [2020-07-06T06:43:23,459][INFO ][o.e.n.Node               ] [ec4ffabc1af7] node name [ec4ffabc1af7], node ID [sRlFeKGpROOc40Kw2H7k6w], cluster name [elasticsearch]
localstack_1  | [2020-07-06T06:43:23,461][INFO ][o.e.n.Node               ] [ec4ffabc1af7] version[7.1.0], pid[3650], build[default/tar/606a173/2019-05-16T00:43:15.323135Z], OS[Linux/4.19.76-linuxkit/amd64], JVM[IcedTea/OpenJDK 64-Bit Server VM/1.8.0_242/25.242-b08]
localstack_1  | [2020-07-06T06:43:23,463][INFO ][o.e.n.Node               ] [ec4ffabc1af7] JVM home [/usr/lib/jvm/java-1.8-openjdk/jre]
localstack_1  | [2020-07-06T06:43:23,463][INFO ][o.e.n.Node               ] [ec4ffabc1af7] JVM arguments [-XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/opt/code/localstack/localstack/infra/elasticsearch/tmp, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Xms200m, -Xmx600m, -Des.path.home=/opt/code/localstack/localstack/infra/elasticsearch, -Des.path.conf=/opt/code/localstack/localstack/infra/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=tar, -Des.bundled_jdk=true]
localstack_1  | Error starting infrastructure: 'latin-1' codec can't encode character '\u0161' in position 110982: Body ('š') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8. Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 342, in start_infra
localstack_1  |     do_start_infra(asynchronous, apis, is_in_docker)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py", line 48, in do_start_infra
localstack_1  |     return do_start_infra_orig(asynchronous,*args,**kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 390, in do_start_infra
localstack_1  |     persistence.restore_persisted_data(apis=apis)
localstack_1  |   File "/opt/code/localstack/localstack/utils/persistence.py", line 170, in restore_persisted_data
localstack_1  |     return replay('_all_')
localstack_1  |   File "/opt/code/localstack/localstack/utils/persistence.py", line 161, in replay
localstack_1  |     replay_command(command)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/persistence.py", line 76, in replay_command
localstack_1  |   File "/opt/code/localstack/localstack/utils/persistence.py", line 145, in replay_command
localstack_1  |     response = function(full_url, data=data, headers=command['h'], verify=False)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 134, in put
localstack_1  |     return request('put', url, data=data, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
localstack_1  |     resp = conn.urlopen(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
localstack_1  |     httplib_response = self._make_request(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
localstack_1  |     conn.request(method, url, **httplib_request_kw)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1230, in request
localstack_1  |     self._send_request(method, url, body, headers, encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1275, in _send_request
localstack_1  |     body = _encode(body, 'body')
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 160, in _encode
localstack_1  |     raise UnicodeEncodeError(
localstack_1  | UnicodeEncodeError: 'latin-1' codec can't encode character '\u0161' in position 110982: Body ('š') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/cli.py", line 157, in main
localstack_1  |     subcommand['function'](argv, args)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cli.py", line 60, in cmd_infra
localstack_1  |     start_infra_locally()
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 279, in start_infra_locally
localstack_1  |     return infra.start_infra()
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 349, in start_infra
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 342, in start_infra
localstack_1  |     do_start_infra(asynchronous, apis, is_in_docker)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py", line 48, in do_start_infra
localstack_1  |     return do_start_infra_orig(asynchronous,*args,**kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 390, in do_start_infra
localstack_1  |     persistence.restore_persisted_data(apis=apis)
localstack_1  |   File "/opt/code/localstack/localstack/utils/persistence.py", line 170, in restore_persisted_data
localstack_1  |     return replay('_all_')
localstack_1  |   File "/opt/code/localstack/localstack/utils/persistence.py", line 161, in replay
localstack_1  |     replay_command(command)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/persistence.py", line 76, in replay_command
localstack_1  |   File "/opt/code/localstack/localstack/utils/persistence.py", line 145, in replay_command
localstack_1  |     response = function(full_url, data=data, headers=command['h'], verify=False)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 134, in put
localstack_1  |     return request('put', url, data=data, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
localstack_1  |     resp = conn.urlopen(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
localstack_1  |     httplib_response = self._make_request(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
localstack_1  |     conn.request(method, url, **httplib_request_kw)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1230, in request
localstack_1  |     self._send_request(method, url, body, headers, encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1275, in _send_request
localstack_1  |     body = _encode(body, 'body')
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 160, in _encode
localstack_1  |     raise UnicodeEncodeError(
localstack_1  | UnicodeEncodeError: 'latin-1' codec can't encode character '\u0161' in position 110982: Body ('š') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
localstack_1  | 
localstack_1  | ERROR: 'latin-1' codec can't encode character '\u0161' in position 110982: Body ('š') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
localstack_1  | 2020-07-06 06:43:27,189 INFO exited: infra (exit status 2; not expected)
```

# Steps to reproduce
## Command used to start LocalStack
docker-compose up

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Create elasticsearch:
`awslocal es create-elasticsearch-domain --domain-name mydomain`

index_definition.json:

```
{
  "mappings": {
    "properties": {
      "id":    { "type": "integer" },
      "author": {"type": "keyword"},
      "timestamp": {"type": "date"},
      "lead": {"type": "keyword"},
      "topic":  { "type": "text" }, 
      "url":   { "type": "keyword" },
      "related": { "type": "keyword" }
    }
  }
}
```

`http PUT http://localhost:4571/articles < ~/Downloads/index_definition.json`

testdata.json

```
  {
    "id": 666,
    "headline": "Lorem ipsum dolor",
    "author": "Mušin Žundavić",
    "timestamp": "2018-09-15T00:00:00+02:00",
    "lead": "",
    "text": "Lorem ipsum. (mz) (Mušin Žundavić) / (mz)",
    "topic": "",
    "url": "https://example.org/-666",
    "related": [

    ]
  },
```

Load data:

```
import json
import os
from elasticsearch import Elasticsearch

es = Elasticsearch(['localhost'], port=4571)
for dirname, dirnames, filenames in os.walk('/Users/test/filepath/'):
    for filename in filenames:
        if not filename.endswith(".DS_Store"):
            print(filename)
            currentfile = "/Users/test/filepath/" + filename
            contents = json.load(open(currentfile, ))
            for article in contents:
                es.index(index="articles", id=article["id"], body=article)
```

Verify:

```
import pprint
import elasticsearch
from elasticsearch_dsl import Search

es = elasticsearch.Elasticsearch(['localhost'], port=4571)
search = Search(using=es, index="articles")
res = search.query("match", headline="Lorem")
for r in res:
    pprint.pprint(r)
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-210) by [Unito](https://www.unito.io/learn-more)

**Comment by macnev2013** [comment]
Thanks for reporting @unimatrix01 . We tried to reproduce the issue, but its working properly. Can you give it another try with the `latest` docker image of `localstack`? 
Please let us know if the issue still persists in `latest` version.
Thanks.
