### ISSUE TITLE
Lambda's can't call out to other localstack services like SQS

### ISSUE THREAD

**Issue by phillip-haydon** [localstack/localstack#2732]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

When a lambda is invoked in LocalStack like so:

`awslocal lambda invoke --function-name workflow-begin-qc --payload '{ "fileId": 12345 }'`

If it attempts to call out to another service (SQS) it fails.

## Expected behavior

Should put a message in SQS.

## Actual behavior

Throws an exception:

> Cannot assign requested address

```
localstack_main | START RequestId: db9d26ce-aa87-1c80-f7af-912d985e357b Version: $LATEST
localstack_main | Executing Lambda::BeginQCHandler | FileId: 12345Cannot assign requested address: HttpRequestException
localstack_main |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
localstack_main |    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
localstack_main |    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
localstack_main |    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
localstack_main |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
localstack_main |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
localstack_main |    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
localstack_main |    at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
localstack_main |    at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
localstack_main |    at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
localstack_main |    at Amazon.SQS.Internal.ValidationResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
localstack_main |    at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
localstack_main |    at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
localstack_main |    at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
localstack_main |    at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
localstack_main |    at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
localstack_main |    at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
localstack_main |    at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
localstack_main |    at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
localstack_main |    at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
localstack_main |    at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
localstack_main |    at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
localstack_main |    at TestLocalStack.Workflows.QCWorkflowHandler.BeginQCHandler(QCRequestEvent request, ILambdaContext context) in /media/phillip/codez/github/TestLocalStack.workflows/src/TestLocalStack.Workflows.MediaServices/QCWorkflowHandler.cs:line 32
localstack_main |    at lambda_method(Closure , Stream , Stream , LambdaContextInternal )
localstack_main | 
localstack_main |    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
localstack_main | 
localstack_main | END RequestId: db9d26ce-aa87-1c80-f7af-912d985e357b
localstack_main | REPORT RequestId: db9d26ce-aa87-1c80-f7af-912d985e357b	Init Duration: 208.60 ms	Duration: 35247.63 ms	Billed Duration: 35300 ms	Memory Size: 1536 MB	Max Memory Used: 63 MB
```

If I execute the lambda as a unit test, it puts the message on the queue just fine. It appears that inside localstack the lambda container cannot call out to SQS. 

There's also a second bug which is sort of related. If a lambda executes successfully, it does not show the execution in the terminal. For example, a successful execution just shows:

```
localstack_main | 2020-07-16T15:14:11:INFO:localstack.services.awslambda.lambda_executors: Determined main container target IP: 172.21.0.2
localstack_main | 2020-07-16T15:14:11:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: CONTAINER_ID="$(docker create -i   -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN"  --rm "lambci/lambda:dotnetcore3.1" "TestLocalStack.Workflows.MediaServices::TestLocalStack.Workflows.QCWorkflowHandler::BeginQCHandler")";docker cp "/tmp/localstack/zipfile.52243f21/." "$CONTAINER_ID:/var/task"; docker start -ai "$CONTAINER_ID";
```

While a failed execution will include the cloudwatch logs, with START/END/REPORT

# Steps to reproduce

## Command used to start LocalStack

docker-compose up

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```csharp
using System.Text.Json;
using System.Threading.Tasks;
using Amazon.Lambda.Core;
using Amazon.SQS;
using Amazon.SQS.Model;
using TestLocalStack.Events;
using TestLocalStack.Workflows.MediaServices.QCWorkflow;

[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

namespace TestLocalStack.Workflows.MediaServices
{
    public class QCWorkflowHandler
    {
        public QCWorkflowHandler()
        {
        }

        public async Task<RequestQCResponse> BeginQCHandler(QCRequestEvent request, ILambdaContext context)
        {
            context.Logger.Log($"Executing Lambda::BeginQCHandler | FileId: {request.FileId}");

            var client = new AmazonSQSClient(new AmazonSQSConfig
            {
                ServiceURL = "http://localhost:4566"
            });

            var queueUrl = await client.GetQueueUrlAsync(new GetQueueUrlRequest("qc-request"));

            context.Logger.Log($"Queue Url: {queueUrl}");

            var result = await client.SendMessageAsync(new SendMessageRequest
            {
                QueueUrl = queueUrl.QueueUrl,
                MessageBody = JsonSerializer.Serialize(request)
            });

            context.Logger.Log($"MessageId: {result.MessageId}");

            return new RequestQCResponse
            {
                MessageId = result.MessageId,
                Message = $"The requested FileId = {request.FileId}"
            };
        }
    }

    public class QCRequestEvent : EventBase
    {
        public int FileId { get; set; }
    }

    public class RequestQCResponse
    {
        public string MessageId { get; set; } = null!;

        public string Message { get; set; } = null!;
    }
}
```
```
awslocal sqs create-queue --queue-name qc-request
awslocal iam create-role --role-name lambda-role --assume-role-policy-document file://testrole.json

dotnet tool run dotnet-lambda package -pl ./src/TestLocalStack.Workflows.MediaServices/ -o ./output/QCWorkflowBeginQCHandler.zip -c Release -f netcoreapp3.1 --msbuild-parameters "--self-contained true"

awslocal lambda create-function --function-name workflow-begin-qc --runtime dotnetcore3.1 --memory-size 256 --timeout 60 --zip-file fileb://output/QCWorkflowBeginQCHandler.zip --handler TestLocalStack.Workflows.MediaServices::TestLocalStack.Workflows.MediaServices.QCWorkflowHandler::BeginQCHandler --role arn:aws:iam::000000000000:role/lambda-role

awslocal lambda invoke --function-name workflow-begin-qc --payload '{ "fileId": 12345 }'
```

testrole.json

```
{
	"Version": "2012-10-17",
	"Statement": {
		"Effect": "Allow",
		"Principal": { "AWS": "arn:aws:iam::000000000000:root" },
		"Action": "sts:AssumeRole"
	}
}
```

Note: I'm trying to simulate `Event Bridge > Rule > Lambda` and `Event Bridge > Rule > Step Function > SQS > Lambda`

**Comment by whummer** [comment]
Thanks for reporting @phillip-haydon . Please note that the Lambdas are running inside their own container by default, hence the services are not available on `localhost`. Can you please try reading the `LOCALSTACK_HOSTNAME` environment variable in your Lambda handler, and then connect to the following endpoint URL: `http:://$LOCALSTACK_HOSTNAME:4566` . Hope  that helps - please keep us posted. Thanks

**Comment by phillip-haydon** [comment]
So the environment variable is there, but now instead of erroring out, it hangs for 60 seconds (duration of the lambda) and never does anything. 

I will do some further testing on Monday, it's most likely down to weekend tiredness.

**Comment by macnev2013** [comment]
Thanks for the update @phillip-haydon . This should be fixed in the `latest` version - can you please pull the latest docker image and give it another try? Let us know if the problem persists.

**Comment by phillip-haydon** [comment]
@macnev2013 I lost my test for this one so I need to rewrite it. (my SSD died last week and the stuff not in git was lost :cry:) I will try verify this in the next couple of days. Sorry!

**Comment by macnev2013** [comment]
Hey @phillip-haydon , Can you verify if the issue still persists or not?

**Comment by phillip-haydon** [comment]
SORRY @macnev2013 I completely forgot. Was so busy with stuff. Let me do a test right now. I'll try reply in the next hour.

**Comment by macnev2013** [comment]
Sounds great. Thanks @phillip-haydon .

**Comment by phillip-haydon** [comment]
```
phillip@migu:/media/phillip/ubuntu-storage-2/GitHub/LocalStackTests$ awslocal lambda invoke --function-name test-lambda-event --payload '{ "value": "Bob" }' response.json
{
    "StatusCode": 200,
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
phillip@migu:/media/phillip/ubuntu-storage-2/GitHub/LocalStackTests$ awslocal sqs receive-message --queue-url http://localhost:4566/000000000000/banana
{
    "Messages": [
        {
            "MessageId": "56e0d4b7-abc4-daac-11bd-2261c1bbf453",
            "ReceiptHandle": "ppmyfwmlvzcobynavqjsqniebrtpjzvuoxbkcttbqjibkzncfqyhlrfaxnjxpiyzxpffaasoyussbgdoptuclwjhgskvthyogbclwomqfjvenxrwujxgfgxfxzhdfvvvbpldagonougnsvutoenneolvcfmbkmoutiiqnwyzzkevouojrwudhxouj",
            "MD5OfBody": "eadc11d1ff21ba217386ed84bbec5d24",
            "Body": "{\"Value\":\"Bob\"}",
            "Attributes": {
                "SenderId": "AIDAIT2UOQQY3AUEKVGXU",
                "SentTimestamp": "1600921006787",
                "ApproximateReceiveCount": "1",
                "ApproximateFirstReceiveTimestamp": "1600921013431"
            }
        }
    ]
}
```

Can confirm in 0.11.4 it's working perfectly!

Thank you!

**Comment by macnev2013** [comment]
Thanks for confirming @phillip-haydon.

**Comment by evbo** [comment]
@macnev2013 sorry to revive an old issue, but I'm wondering if the situation has changed now that AWS is deprecating `path style` in the S3 service? Just like the OP, my docker container starts 

I am using terraform and ensure that `s3_use_path_style` is set to true in my `provider` for localstack (because otherwise there are networking issues - and I don't bother with `tflocal` due to this same issue I believe because it doesn't enable this setting).

If my lambda uses an s3 endpoint of `http://localhost:4566` I get:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Io, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" })) } })

Or, if my lambda uses an s3 endpoint of `http://localstack:4566` I get:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Io, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: Name or service not known" })) } })

Or ([per this blog](https://www.benscobie.com/aws-lambda-localstack-cannot-assign-requested-address-httprequestexception/), if I use: `http://host.docker.internal:4566` I get:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Io, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup

**Comment by evbo** [comment]
@macnev2013 there's probably a cleaner way, but someone else had this exact same issue here: https://github.com/localstack/localstack/issues/1277#issuecomment-497194309

The trick was to `exec` onto the running `localstack-main` container, `apt-get install net-tools` and then run `ifconfig`

The resulting ip address WORKS as the `endpoint_url` for my lambda.

My only question is, could this be more ergonomic? Could localstack automatically set `etc/hosts` file to point `localhost` to the proper ip address?

Happy to open a separate issue, but thought I'd check if this is the right thinking or not. Thanks!
