### ISSUE TITLE
Cloudfront create distribution with custom JSON

### ISSUE THREAD

**Issue by MrDeLeTeD** [localstack/localstack#2737]
Hi,
i have to create a distribution with S3 origin (if possible with private ACL).

I have a 500 error while creating the distribution.

[X] bug report
[ ] feature request

# Detailed description

Distribution JSON: 
```
{
  "Tags": {
    "Items": [
      {
        "Key": "Name",
        "Value": "SSGDistribution"
      },
      {
        "Key": "Project",
        "Value": "ssg-cf"
      }
    ]
  },
  "DistributionConfig": {
    "CallerReference": "cli-example",
    "Aliases": {
      "Quantity": 0
    },
    "DefaultRootObject": "index.html",
    "Origins": {
      "Quantity": 1,
      "Items": [
        {
          "Id": "ssg.s3.amazonaws.com-cli-example",
          "DomainName": "ssg.s3.amazonaws.com",
          "OriginPath": "",
          "CustomHeaders": {
            "Quantity": 0
          },
          "S3OriginConfig": {
            "OriginAccessIdentity": ""
          }
        }
      ]
    },
    "OriginGroups": {
      "Quantity": 0
    },
    "DefaultCacheBehavior": {
      "TargetOriginId": "ssg.s3.amazonaws.com-cli-example",
      "ForwardedValues": {
        "QueryString": false,
        "Cookies": {
          "Forward": "none"
        },
        "Headers": {
          "Quantity": 0
        },
        "QueryStringCacheKeys": {
          "Quantity": 0
        }
      },
      "TrustedSigners": {
        "Enabled": false,
        "Quantity": 0
      },
      "ViewerProtocolPolicy": "allow-all",
      "MinTTL": 0,
      "AllowedMethods": {
        "Quantity": 2,
        "Items": [
          "HEAD",
          "GET"
        ],
        "CachedMethods": {
          "Quantity": 2,
          "Items": [
            "HEAD",
            "GET"
          ]
        }
      },
      "SmoothStreaming": false,
      "DefaultTTL": 86400,
      "MaxTTL": 31536000,
      "Compress": false,
      "LambdaFunctionAssociations": {
        "Quantity": 0
      },
      "FieldLevelEncryptionId": ""
    },
    "CacheBehaviors": {
      "Quantity": 0
    },
    "CustomErrorResponses": {
      "Quantity": 0
    },
    "Comment": "",
    "Logging": {
      "Enabled": false,
      "IncludeCookies": false,
      "Bucket": "",
      "Prefix": ""
    },
    "PriceClass": "PriceClass_All",
    "Enabled": true,
    "ViewerCertificate": {
      "CloudFrontDefaultCertificate": true,
      "MinimumProtocolVersion": "TLSv1",
      "CertificateSource": "cloudfront"
    },
    "Restrictions": {
      "GeoRestriction": {
        "RestrictionType": "none",
        "Quantity": 0
      }
    },
    "WebACLId": "",
    "HttpVersion": "http2",
    "IsIPV6Enabled": true
  }
}
```

local command : 
```
awslocal cloudfront create-distribution-with-tags --distribution-config-with-tags file://cloudfront.json
```

Error log on docker : 
```
2020-07-17T12:17:49:ERROR:cloudfront_api: Exception on /2019-03-26/distribution [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cloudfront/cloudfront_api.py", line 77, in create_distribution
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cloudfront/cloudfront_api.py", line 73, in fix_keys
KeyError: 'Items'
```

Command return : 
```
An error occurred (500) when calling the CreateDistributionWithTags operation (reached max retries: 4): Internal Server Error
```
## Expected behavior
- Cloudfront distribution is created
...

## Actual behavior
- Error on call, CF distribution is not created
...

# Steps to reproduce

## Command used to start LocalStack

docker-compose service description:
```
localstack:
    image: localstack/localstack
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "8001:8080"
    environment:
      - SERVICES=cloudfront,s3,edge,lambda
      - DEBUG=1
      #- DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DNS_LOCAL_NAME_PATTERNS='.*cloudfront\.net'
      - CLOUDFRONT_STATIC_PORTS= 1
    volumes:
      - "./tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

...

**Comment by whummer** [comment]
Thanks for reporting this issue @MrDeLeTeD  . This should be fixed in the meantime - can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? Please let us know if the problem persists. Many thanks for your help!
