### ISSUE TITLE
Docker-compose dashboard start_web not working

### ISSUE THREAD

**Issue by rodrigondec** [localstack/localstack#2749]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
I'm running the localstack with `docker-compose`.

The dashboard web crashes after spawning. Due to missing [`web`](https://github.com/localstack/localstack/tree/master/localstack/dashboard/web) folder on the path `/opt/code/localstack/localstack/dashboard/`.

My docker-compose:

```
version: "3.7"

services:
    localstack:
        image: localstack/localstack
        container_name: "service-localstack-dev"
        ports:
            - "4566-4599:4566-4599"
            - "8080:8080"
        environment:
            - SERVICES=sns
            - DEFAULT_REGION=us-east-1
            - DEBUG=1
            - START_WEB=1
            - DATA_DIR=/tmp/localstack/data
            - DOCKER_HOST=unix:///var/run/docker.sock
            - HOST_TMP_FOLDER=/tmp/localstack
        volumes:
            - "/tmp/localstack:/tmp/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
```

## Expected behavior
The dashboard web to be up and running.

## Actual behavior
The dashboard web crashes with the output:

```
service-localstack-dev | 2020-07-20T16:35:25:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f0d1550aee0>
service-localstack-dev | ERROR: 'cd "/opt/code/localstack/localstack/dashboard/web"; npm install': exit code 243; output: b'/bin/sh: cd: line 1: can\'t cd to /opt/code/localstack/localstack/dashboard/web: No such file or directory
npm WARN locking Error: EACCES: permission denied, open \'/root/.npm/_locks/staging-9bb89b2aa202b609.lock\'\nnpm WARN locking  /root/.npm/_locks/staging-9bb89b2aa202b609.lock failed [Error: EACCES: permission denied, open \'/root/.npm/_locks/staging-9bb89b2aa202b609.lock\'] {\nnpm WARN locking   stack: "Error: EACCES: permission denied, open \'/root/.npm/_locks/staging-9bb89b2aa202b609.lock\'",\nnpm WARN locking   errno: -13,\nnpm WARN locking   code: \'EACCES\',\nnpm WARN locking   syscall: \'open\',\nnpm WARN locking   path: \'/root/.npm/_locks/staging-9bb89b2aa202b609.lock\'\nnpm WARN locking }\nnpm WARN enoent ENOENT: no such file or directory, open \'/opt/code/localstack/package.json\'\nnpm WARN localstack No description\nnpm WARN localstack No repository field.\nnpm WARN localstack No README data\nnpm WARN localstack No license field.\n\nnpm ERR! code EACCES\nnpm ERR! syscall open\nnpm ERR! path /root/.npm/_locks/staging-9bb89b2aa202b609.lock\nnpm ERR! errno -13\nnpm ERR! \nnpm ERR! Your cache folder contains root-owned files, due to a bug in\nnpm ERR! previous versions of npm which has since been addressed.\nnpm ERR! \nnpm ERR! To permanently fix this problem, please run:\nnpm ERR!   sudo chown -R 1001:1001 "/root/.npm"\n'
service-localstack-dev | Traceback (most recent call last):
service-localstack-dev |   File "/opt/code/localstack/localstack/utils/cli.py", line 157, in main
service-localstack-dev |     subcommand['function'](argv, args)
service-localstack-dev |   File "/opt/code/localstack/localstack/utils/cli.py", line 82, in cmd_web
service-localstack-dev |     localstack.dashboard.api.serve(port)
service-localstack-dev |   File "/opt/code/localstack/localstack/dashboard/api.py", line 134, in serve
service-localstack-dev |     ensure_webapp_installed()
service-localstack-dev |   File "/opt/code/localstack/localstack/dashboard/api.py", line 129, in ensure_webapp_installed
service-localstack-dev |     common.run('cd "%s"; npm install' % web_dir)
service-localstack-dev |   File "/opt/code/localstack/localstack/utils/common.py", line 1056, in run
service-localstack-dev |     return do_run(cmd)
service-localstack-dev |   File "/opt/code/localstack/localstack/utils/common.py", line 1053, in do_run
service-localstack-dev |     return bootstrap.run(cmd, **kwargs)
service-localstack-dev |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 579, in run
service-localstack-dev |     raise e
service-localstack-dev |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 539, in run
service-localstack-dev |     output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
service-localstack-dev |   File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
service-localstack-dev |     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
service-localstack-dev |   File "/usr/lib/python3.8/subprocess.py", line 512, in run
service-localstack-dev |     raise CalledProcessError(retcode, process.args,
service-localstack-dev | subprocess.CalledProcessError: Command 'cd "/opt/code/localstack/localstack/dashboard/web"; npm install' returned non-zero exit status 243.
service-localstack-dev | ERROR: Command 'cd "/opt/code/localstack/localstack/dashboard/web"; npm install' returned non-zero exit status 243.
service-localstack-dev | make: *** [Makefile:109: web] Error 1
```

From the stacktrace the tips I found were from this line 

```
service-localstack-dev | ERROR: 'cd "/opt/code/localstack/localstack/dashboard/web"; npm install': exit code 243; output: b'/bin/sh: cd: line 1: can\'t cd to /opt/code/localstack/localstack/dashboard/web: No such file or directory
```

I jumped into the container created and did some digging

![image](https://user-images.githubusercontent.com/3301060/87963221-c1929f80-ca8e-11ea-8bd2-848af7eb855b.png)

On my container there's no folder `web`!

# Steps to reproduce

## Command used to start LocalStack
`docker-compose up`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
N/A

**Comment by whummer** [comment]
Thanks for reporting @rodrigondec . Please note that we have recently starting using a stripped-down "light" version of the Docker image as the default image. In order to use the Web dashboard, the "full" version of the Docker image needs to be used instead: `localstack/localstack-full`.

The README has been updated accordingly: https://github.com/localstack/localstack#web-dashboard-deprecated . Hope that helps - please re-open this issue if the problem persists. Thanks

**Comment by ManfredLange** [comment]
@whummer 

> The README has been updated accordingly: https://github.com/localstack/localstack#web-dashboard-deprecated . Hope that helps - please re-open this issue if the problem persists. Thanks

Looks as if the anchor in that README has vanished.... No mentioning of the web ui.

**Comment by jimmykirk** [comment]
> @whummer
> 
> > The README has been updated accordingly: https://github.com/localstack/localstack#web-dashboard-deprecated . Hope that helps - please re-open this issue if the problem persists. Thanks
> 
> Looks as if the anchor in that README has vanished.... No mentioning of the web ui.

Yup. I just found this project and was kicking the tires on it. Not going to jump on Commandeer for $30/mo to do the 1 hour dive into this.
