### ISSUE TITLE
Attempt to create duplicate api-key returns 500 error

### ISSUE THREAD

**Issue by marcuswr** [localstack/localstack#2753]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description
Attempting to create a second api-key with the same name and value crashes localstack and results in 500 error.

## Expected behavior
ConflictException to be thrown by aws java sdk

## Actual behavior
SdkClientException thrown by aws java sdk

# Steps to reproduce
Start localstack
Create new api-key
Attempt to create same api-key a second time

## Command used to start LocalStack
docker-compose up

docker-compose.yaml
```
version: '3'
services:
localstack:
image: localstack/localstack
ports:
- "4567:4567"
environment:
- SERVICES=apigateway
volumes:
- "/private${TMPDIR}/localstack:/tmp/localstack"
- "/var/run/docker.sock:/var/run/docker.sock"
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

aws --endpoint http://localhost:4567 apigateway create-api-key --name foo --value bar
aws --endpoint http://localhost:4567 apigateway create-api-key --name foo --value bar

## LocalStack log output
```
localstack_1  | 2020-07-21 13:54:55,770:API: 127.0.0.1 - - [21/Jul/2020 13:54:55] "POST /apikeys HTTP/1.1" 500 -
localstack_1  | 2020-07-21 13:54:55,778:API: Error on request:
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
localstack_1  |     execute(self.server.app)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
localstack_1  |     application_iter = app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 135, in __call__
localstack_1  |     return backend_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__
localstack_1  |     return self.wsgi_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app
localstack_1  |     response = self.handle_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_1  |     raise value
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
localstack_1  |     response = self.full_dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
localstack_1  |     rv = self.handle_user_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_1  |     raise value
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
localstack_1  |     rv = self.dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
localstack_1  |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 155, in __call__
localstack_1  |     response = Response(response=content, status=status, headers=headers)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/wrappers/base_response.py", line 196, in __init__
localstack_1  |     self.headers["Content-Type"] = content_type
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 1397, in __setitem__
localstack_1  |     is_immutable(self)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 36, in is_immutable
localstack_1  |     raise TypeError("%r objects are immutable" % self.__class__.__name__)
localstack_1  | TypeError: 'EnvironHeaders' objects are immutable
```

**Comment by whummer** [comment]
Thanks for reporting @marcuswr  . This should be fixed upstream in  spulec/moto#3162 - the change should be available in the `latest` version of the LocalStack Docker image. Please report here if the problem persists. Thanks
