### ISSUE TITLE
Cloudformation fails to update stack with sqs dependency. Unable to resolve all CloudFormation resources after traversing dependency tree

### ISSUE THREAD

**Issue by hudovisk** [localstack/localstack#2772]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
When running `aws cloudformation update-stack` which adds 2 SQS Queues, where one is a dlq for the other, localstack fails to resolve the dependency between the two and raises the exception: `Unable to resolve all CloudFormation resources after traversing dependency tree (maximum depth 40 reached): `
...

## Expected behavior
...

## Actual behavior
```
2020-07-26T14:43:45:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource mystack/ServerlessDeploymentBucket: None
2020-07-26T14:43:45:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::S3::Bucket', 'Properties': {'BucketEncryption': {'ServerSideEncryptionConfiguration': [{'ServerSideEncryptionByDefault': {'SSEAlgorithm': 'AES256'}}]}, 'BucketName': 'mystack-ServerlessDeploymentBucket-2UMFDVR31WG6'}}
2020-07-26T14:43:45:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "S3::Bucket" id "ServerlessDeploymentBucket"
2020-07-26T14:43:45:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "S3::Bucket" in region us-east-1: create_bucket {'Bucket': 'mystack-ServerlessDeploymentBucket-2UMFDVR31WG6', 'ACL': 'public-read'}
2020-07-26T14:43:45:DEBUG:localstack.services.cloudformation.cloudformation_starter: Running CloudFormation stack deployment loop iteration 1
2020-07-26T14:44:14:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource mystack/EventSQSQueue: None
2020-07-26T14:44:14:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource mystack/EventSQSQueueDLQ: None
2020-07-26T14:44:14:DEBUG:localstack.services.cloudformation.cloudformation_starter: Deploying CloudFormation resource (update=False, exists=False, updateable=False): {'Type': 'AWS::SQS::Queue', 'Properties': {'QueueName': 'hermes-development-events-dlq', 'MessageRetentionPeriod': 1209600}}
2020-07-26T14:44:14:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "SQS::Queue" id "EventSQSQueueDLQ"
2020-07-26T14:44:14:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "SQS::Queue" in region us-east-1: create_queue {'QueueName': 'hermes-development-events-dlq', 'Attributes': {'MessageRetentionPeriod': '1209600'}, 'tags': {}}
2020-07-26T14:44:14:DEBUG:localstack.utils.cloudformation.template_deployer: Dependency for resource EventSQSQueue not yet deployed: EventSQSQueueDLQ
2020-07-26T14:44:14:DEBUG:localstack.utils.cloudformation.template_deployer: Dependency for resource EventSQSQueue not yet deployed: EventSQSQueueDLQ
2020-07-26T14:44:14:INFO:localstack.services.cloudformation.cloudformation_starter: Resource EventSQSQueue cannot be deployed, found unsatisfied dependencies. {'Type': 'AWS::SQS::Queue', 'DependsOn': ['EventSQSQueueDLQ'], 'Properties': {'QueueName': 'hermes-development-events.fifo', 'RedrivePolicy': {'deadLetterTargetArn': 'arn:aws:sqs:us-east-1:000000000000:hermes-development-events-dlq', 'maxReceiveCount': 5}}}
2020-07-26T14:44:14:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource mystack/EventSQSQueueDLQ: False
2020-07-26T14:44:14:DEBUG:localstack.services.cloudformation.cloudformation_starter: Running CloudFormation stack deployment loop iteration 1
2020-07-26T14:44:14:DEBUG:localstack.services.cloudformation.cloudformation_starter: Currently processing stack resource mystack/EventSQSQueue: None
2020-07-26T14:44:14:DEBUG:localstack.utils.cloudformation.template_deployer: Dependency for resource EventSQSQueue not yet deployed: EventSQSQueueDLQ
2020-07-26T14:44:14:DEBUG:localstack.utils.cloudformation.template_deployer: Dependency for resource EventSQSQueue not yet deployed: EventSQSQueueDLQ
2020-07-26T14:44:14:INFO:localstack.services.cloudformation.cloudformation_starter: Resource EventSQSQueue cannot be deployed, found unsatisfied dependencies. {'Type': 'AWS::SQS::Queue', 'DependsOn': ['EventSQSQueueDLQ'], 'Properties': {'QueueName': 'hermes-development-events.fifo', 'RedrivePolicy': {'deadLetterTargetArn': 'arn:aws:sqs:us-east-1:000000000000:hermes-development-events-dlq', 'maxReceiveCount': 5}}}
2020-07-26T14:44:14:WARNING:localstack.services.cloudformation.cloudformation_starter: Unresolvable dependencies, there may be undeployed stack resources: {'EventSQSQueue': ['EventSQSQueue', {'Type': 'AWS::SQS::Queue', 'DependsOn': ['EventSQSQueueDLQ'], 'Properties': {'QueueName': 'hermes-development-events.fifo', 'RedrivePolicy': {'deadLetterTargetArn': 'arn:aws:sqs:us-east-1:000000000000:hermes-development-events-dlq', 'maxReceiveCount': 5}}}, <moto.cloudformation.parsing.ResourceMap object at 0x7f7875618370>, 'us-east-1']}
2020-07-26T14:44:14:WARNING:bootstrap.py: Thread run method <function apply_patches.<locals>.run_dependencies_deployment_loop.<locals>.run_loop at 0x7f787378a790>(None) failed: Traceback (most recent call last):
  File "/mnt/data/hudo/Projects/localstask-original/localstack/utils/bootstrap.py", line 510, in run
    self.func(self.params)
  File "/mnt/data/hudo/Projects/localstask-original/localstack/services/cloudformation/cloudformation_starter.py", line 847, in run_loop
    raise Exception('Unable to resolve all CloudFormation resources after traversing ' +
Exception: Unable to resolve all CloudFormation resources after traversing dependency tree (maximum depth 40 reached): ['EventSQSQueue']
```

...

# Steps to reproduce
## Command used to start LocalStack
DEBUG=1 make infra

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
cloudformation-template-create-stack.json

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "ServerSideEncryptionByDefault": {
                "SSEAlgorithm": "AES256"
              }
            }
          ]
        }
      }
    }
  }
}
```

cloudformation-template-update-stack.json

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "ServerSideEncryptionByDefault": {
                "SSEAlgorithm": "AES256"
              }
            }
          ]
        }
      }
    },
    "EventSQSQueueDLQ": {
      "Type": "AWS::SQS::Queue",
      "Properties": {
        "QueueName": "hermes-development-events-dlq",
        "MessageRetentionPeriod": 1209600
      }
    },
    "EventSQSQueue": {
      "Type": "AWS::SQS::Queue",
      "DependsOn": ["EventSQSQueueDLQ"],
      "Properties": {
        "QueueName": "hermes-development-events.fifo",
        "RedrivePolicy": {
          "deadLetterTargetArn": {
            "Fn::GetAtt": ["EventSQSQueueDLQ", "Arn"]
          },
          "maxReceiveCount": 5
        }
      }
    }
  }
}
```

`aws cloudformation create-stack --stack-name mystack --template-body file://cloudformation-template-create-stack.json --endpoint-url http://localhost:4566`

`aws cloudformation update-stack --stack-name mystack --template-body file://cloudformation-template-update-stack.json --endpoint-url http://localhost:4566`
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-226) by [Unito](https://www.unito.io/learn-more)

**Comment by macnev2013** [comment]
Thanks for reporting @hudovisk . This should be fixed in the `latest` version of `localstack` - can you please do a `docker pull localstack/localstack` and give it another try? Please report here if the problem persists. Thanks
