### ISSUE TITLE
Add more docs for HOST_TMP_FOLDER

### ISSUE THREAD

**Issue by Veetaha** [localstack/localstack#2808]
# This is a feature request

If I don't need any persistence for my use case, do I still need to mount the temp dir and specify the `HOST_TMP_FOLDER` env var? I haven't found any docs on this.
I could only dig small info from this PR: https://github.com/localstack/localstack/pull/2271 at most, where I suppose `HOST_TMP_DIR` is needed by `LAMBDA_REMOTE_DOCKER`

I also have this warning:
```
!WARNING! - Looks like you have configured $LAMBDA_REMOTE_DOCKER=1 - please make sure to configure $HOST_TMP_FOLDER to point to your host's $TMPDIR
```

However, everything works fine, lambdas seem to be running well.
Setting `LAMBDA_REMOTE_DOCKER=false` starts to break things (lambda service cannot find the bootstrap binary)...

In fact, I wouldn't even bother creating an issue, but the problem with having the `tmp/localstack` mounted in the docker container is that `localstack` puts root-owned files into it and this means permission errors when trying to remove that temp dir on host.

I also tried passing `--user $(id -u):$(id -g)` parameter to docker, but then other permission errors occur:

<details>
<summary> See the logs </summary>

```bash
docker run \
    -p 4566:4566 \
    --user=$(id -u):$(id -g) \
    -e SERVICES=s3 \
    -e EDGE_PORT=4566 \
    -e START_WEB=0 \
    -e DEBUG=1 \
    -e HOST_TMP_FOLDER=/tmp/localstack \
    -e DOCKER_HOST=unix:///var/run/docker.sock \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/localstack:/tmp/localstack \
    localstack/localstack:latest

Waiting for all LocalStack services to be ready
2020-08-04 11:15:50,771 INFO supervisord started with pid 14
2020-08-04 11:15:51,776 INFO spawned: 'dashboard' with pid 20
2020-08-04 11:15:51,778 INFO spawned: 'infra' with pid 21
supervisor: couldn't setuid to 1001: Can't drop privilege as nonroot user
supervisor: child process was not spawned
2020-08-04 11:15:51,780 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-08-04 11:15:51,781 INFO exited: dashboard (exit status 127; not expected)
(. .venv/bin/activate; exec bin/localstack start --host)
LocalStack version: 0.11.3
Starting local dev environment. CTRL-C to quit.
2020-08-04T11:15:52:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext": <function register_localstack_commands at 0x7f89a15f4670>
2020-08-04T11:15:52:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7f89a17e2af0>
2020-08-04 11:15:52,794 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-04T11:15:52:DEBUG:localstack.utils.common: Starting download from https://github.com/localstack/localstack-artifacts/raw/master/local-certs/server.key to /tmp/localstack/server.test.pem (2659 bytes)
2020-08-04T11:15:52:DEBUG:localstack.utils.common: Starting download from https://cdn.jsdelivr.net/gh/localstack/localstack-artifacts/local-certs/server.key to /tmp/localstack/server.test.pem (3643 bytes)
2020-08-04T11:15:52:INFO:localstack_ext.bootstrap.install: Unable to download local test SSL certificate from https://cdn.jsdelivr.net/gh/localstack/localstack-artifacts/local-certs/server.key to /tmp/localstack/server.test.pem: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem' Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/bootstrap/install.py", line 69, in do_download
    download(url,target_file)
  File "/opt/code/localstack/localstack/utils/common.py", line 646, in download
    with open(path, 'wb') as f:
PermissionError: [Errno 13] Permission denied: '/tmp/localstack/server.test.pem'

2020-08-04T11:15:52:DEBUG:bootstrap.py: Loading 
```
</details>

So as a workaround I am currently ignoring the waring with `LAMBDA_REMOTE_DOCKER` and proceed without mounting the temp dir...

@whummer I would be very grateful if you could clarify things here :d

**Comment by whummer** [comment]
Thanks for reporting @Veetaha . Good catch - this log output was actually incorrect. `HOST_TMP_FOLDER` is generally only required/recommended if a local (non-remote) Docker instance is being used. The log message has now been changed to `Looks like you have configured $LAMBDA_REMOTE_DOCKER=0 ...`, see here: https://github.com/localstack/localstack/blob/master/localstack/services/infra.py#L355-L357 Hope that helps - if you can raise a small PR to add any missing notes to the README, that would be much appreciated. Thanks
