### ISSUE TITLE
HOSTNAME_EXTERNAL prevents range request to S3 service

### ISSUE THREAD

**Issue by okkez** [localstack/localstack#2812]
# Type of request: This is a bug report

# Detailed description

Failed to send the range request to S3 when setting `HOSTNAME_EXTERNAL` environment variable.

## Expected behavior

Succeed in sending the range request to S3 with `HOSTNAME_EXTERNAL` environment variable.

## Actual behavior

Failed to send the range request to S3. localstack logs below:

```
2020-08-05T05:38:21:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request GET http://localhost/bucket-name/xxx: An error occurred (404) when calling the HeadObject operation: Not Found Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 66, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 46, in run_sync
    return await loop.run_in_executor(THREAD_POOL, copy_context().run, func, *args)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 555, in handler
    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 398, in modify_and_forward
    updated_response = update_listener.return_response(**kwargs)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1193, in return_response
    fix_range_content_type(bucket_name, path, headers, response)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 443, in fix_range_content_type
    result = s3_client.head_object(Bucket=bucket_name, Key=key_name)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```

# Steps to reproduce

1. Use docker-compose.yml in this repository with the following diff.

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 12e0e6f..d15097c 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -16,6 +16,7 @@ services:
       - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
       - DOCKER_HOST=unix:///var/run/docker.sock
       - HOST_TMP_FOLDER=${TMPDIR}
+      - HOSTNAME_EXTERNAL=localstack
     volumes:
       - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
       - "/var/run/docker.sock:/var/run/docker.sock"
```

2. Run localstack

```
docker-compose up -d localstack
```

3. Run this script

```ruby
equire "bundler/inline"
require "stringio"

gemfile do
  source "https://rubygems.org"
  gem "aws-sdk-s3"
end

Aws.config.update(
  region: "ap-northeast-1",
  credentials: Aws::Credentials.new("dummy", "dummy"),
)

s3_client = Aws::S3::Client.new(endpoint: "http://localstack:4566", force_path_style: true)

begin
  s3_client.create_bucket(bucket: "test-bucket")
rescue
end
s3_client.put_object(bucket: "test-bucket", key: "test-object", body: StringIO.new("xxx\n" * 100))

res = s3_client.list_objects_v2(bucket: "test-bucket")
pp res.to_h
puts 
res = s3_client.get_object(bucket: "test-bucket", key: "test-object", range: "bytes=10-100")
pp res.to_h
```

4. Got errors

## Command used to start LocalStack

```
docker-compose up -d localstack
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```ruby
equire "bundler/inline"
require "stringio"

gemfile do
  source "https://rubygems.org"
  gem "aws-sdk-s3"
end

Aws.config.update(
  region: "ap-northeast-1",
  credentials: Aws::Credentials.new("dummy", "dummy"),
)

s3_client = Aws::S3::Client.new(endpoint: "http://localstack:4566", force_path_style: true)

begin
  s3_client.create_bucket(bucket: "test-bucket")
rescue
end
s3_client.put_object(bucket: "test-bucket", key: "test-object", body: StringIO.new("xxx\n" * 100))

res = s3_client.list_objects_v2(bucket: "test-bucket")
pp res.to_h
puts 
res = s3_client.get_object(bucket: "test-bucket", key: "test-object", range: "bytes=10-100")
pp res.to_h
```

**Comment by whummer** [comment]
Thanks for reporting @okkez . This should be fixed in #2823 - can you please pull the Docker image one more time and give it a try with the `latest` version? Please report here if the problem persists. Thanks
