### ISSUE TITLE
Bucket HEAD request is not properly forwarded to S3 through edge router

### ISSUE THREAD

**Issue by artamonovkirill** [localstack/localstack#2832]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I get a 404 when bucket HEAD request is executed.
This only happens when using the edge router port.

## Expected behavior

2xx is returned if the bucket exists

## Actual behavior

A 404 on HEAD request through the edge router port.

From Localstack container logs:
> 2020-08-10T19:20:00:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "/a-bucket", target header "", auth header "", data "b''"

Request details (from Terraform debug logs):
```
2020-08-10T21:20:18.414+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: ---[ REQUEST POST-SIGN ]-----------------------------
2020-08-10T21:20:18.414+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: HEAD /a-bucket HTTP/1.1
2020-08-10T21:20:18.414+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: Host: localhost:4566
2020-08-10T21:20:18.414+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: User-Agent: aws-sdk-go/1.33.21 (go1.14.5; darwin; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.28 (+https://www.terraform.io)
2020-08-10T21:20:18.414+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: 
2020-08-10T21:20:18.414+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: 
2020-08-10T21:20:18.414+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: -----------------------------------------------------
2020-08-10T21:20:18.422+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: 2020/08/10 21:20:18 [DEBUG] [aws-sdk-go] DEBUG: Response s3/HeadBucket Details:
2020-08-10T21:20:18.422+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: ---[ RESPONSE ]--------------------------------------
2020-08-10T21:20:18.422+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: HTTP/1.1 404 
2020-08-10T21:20:18.422+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: Connection: close
2020-08-10T21:20:18.422+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: Content-Length: 21
2020-08-10T21:20:18.422+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: Content-Type: text/html; charset=utf-8
2020-08-10T21:20:18.422+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: Date: Mon, 10 Aug 2020 19:20:18 GMT
2020-08-10T21:20:18.422+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: Server: hypercorn-h11
2020-08-10T21:20:18.422+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: 
2020-08-10T21:20:18.422+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: 
2020-08-10T21:20:18.422+0200 [DEBUG] plugin.terraform-provider-aws_v3.1.0_x5: -----------------------------------------------------
```

The bucket is created without errors if I use S3 port (4572)

# Steps to reproduce

## Command used to start LocalStack

docker run -p 4566:4566 -e SERVICES=s3 localstack/localstack:0.11.3

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

main.tf:
```
resource "aws_s3_bucket" "_" {
  bucket = "a-bucket"
}
```

provider.tf:
```
terraform {
  required_providers {
    aws = "3.1.0"
  } 
}

provider "aws" {
  endpoints {
    s3 = "http://localhost:4566"
  }
  
  region = "eu-west-1"
  
  access_key = "foo"
  secret_key = "bar"
  skip_credentials_validation = true
  skip_requesting_account_id = true
   
  s3_force_path_style = true
}
```

commands:
```bash
terraform init
terraform apply
```

**Comment by artamonovkirill** [comment]
I'm not sure whether it's the same as https://github.com/localstack/localstack/issues/2506 or not.

**Comment by artamonovkirill** [comment]
Here's also a repository with an automated test: https://github.com/artamonovkirill/terraform-localstack

**Comment by whummer** [comment]
Thanks for reporting @artamonovkirill . This should be fixed in #2903 - can you please give it another try with the `latest` version of the Docker image. Please report here if the problem persists. Thanks

**Comment by artamonovkirill** [comment]
@whummer , thanks!
It works with the `latest` image, e.g.: https://scans.gradle.com/s/7ku53226rlgpg/tests#:-test-default-package-awsproviderspec-creates-an-s3-bucket-with-3.4.0-aws-provider-and-latest-localstack-3

**Comment by artamonovkirill** [comment]
@whummer, @ninhkd, my test is failing again with latest localstack.
* Setup is the same
* Works fine with 0.11.5
* The exception in the log is now different:

```
2020-09-25T12:00:47:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request HEAD http://localhost:36877/a-bucket: cannot unpack non-iterable int object Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 94, in index
    raise result
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 533, in run
    result = self.func(self.params)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 557, in handler
    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 332, in modify_and_forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/edge.py", line 56, in forward_request
    api, port = get_api_from_custom_rules(method, path, data, headers) or (api, port)
TypeError: cannot unpack non-iterable int object
```

Can you reopen this ticket or should I rather create a new one?
