### ISSUE TITLE
Error while creating userpool

### ISSUE THREAD

**Issue by limenutt** [localstack/localstack#2869]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

[Localstack 1.11.5 (docker)](https://hub.docker.com/layers/localstack/localstack/latest/images/sha256-09d29cccd781c0478d6e4146c18ce27bd464d3f8d4339bf51118754e7ad1d10c?context=explore)

There is a crash when I'm trying to create a Cognito user pool using aws cli
**This is a new behaviour comparing to version 1.11.4.**

docker-compose.yml
```
version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=****
      - SERVICES=cognito-idp,iam,lambda
      - DEBUG=1
      - DATA_DIR=/tmp/local stack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

## Expected behavior

The user pool should be created

## Actual behavior

There is an error in response to the aws-cli issued command:
```
An error occurred (500) when calling the CreateUserPool operation (reached max retries: 4): 
```
There is also an error in the docker container log
```
localstack_1  | 2020-08-23T23:40:32:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: MyHTTPConnectionPool(host='100245e05df7', port=4590): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4bd52e44c0>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
localstack_1  |     conn = connection.create_connection(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
localstack_1  |     raise err
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
localstack_1  |     sock.connect(sa)
localstack_1  | ConnectionRefusedError: [Errno 111] Connection refused
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
localstack_1  |     httplib_response = self._make_request(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
localstack_1  |     conn.request(method, url, **httplib_request_kw)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1230, in request
localstack_1  |     self._send_request(method, url, body, headers, encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
localstack_1  |     self.endheaders(body, encode_chunked=encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
localstack_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
localstack_1  |     self.send(msg)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 944, in send
localstack_1  |     self.connect()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
localstack_1  |     conn = self._new_conn()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
localstack_1  |     raise NewConnectionError(
localstack_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4bd52e44c0>: Failed to establish a new connection: [Errno 111] Connection refused
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
localstack_1  |     resp = conn.urlopen(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
localstack_1  |     retries = retries.increment(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
localstack_1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
localstack_1  | urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='100245e05df7', port=4590): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4bd52e44c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 86, in index
localstack_1  |     result = await run_sync(handler, request, data)
localstack_1  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 54, in run_sync
localstack_1  |     return await loop.run_in_executor(thread_pool, copy_context().run, func, *args)
localstack_1  |   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
localstack_1  |     result = self.fn(*self.args, **self.kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 555, in handler
localstack_1  |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 332, in modify_and_forward
localstack_1  |     listener_result = listener.forward_request(method=method,
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 70, in forward_request
localstack_1  |     response = function(url, data=data, headers=headers, verify=False, stream=True)
localstack_1  |   File "/opt/code/localstack/localstack/utils/common.py", line 1153, in _wrapper
localstack_1  |     return method(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack_1  |     return request('post', url, data=data, json=json, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
localstack_1  |     raise ConnectionError(e, request=request)
localstack_1  | requests.exceptions.ConnectionError: MyHTTPConnectionPool(host='100245e05df7', port=4590): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4bd52e44c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack_1  | 
localstack_1  | 2020-08-23T23:40:40:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: MyHTTPConnectionPool(host='100245e05df7', port=4590): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4bd518f2b0>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
localstack_1  |     conn = connection.create_connection(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
localstack_1  |     raise err
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
localstack_1  |     sock.connect(sa)
localstack_1  | ConnectionRefusedError: [Errno 111] Connection refused
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
localstack_1  |     httplib_response = self._make_request(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
localstack_1  |     conn.request(method, url, **httplib_request_kw)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1230, in request
localstack_1  |     self._send_request(method, url, body, headers, encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
localstack_1  |     self.endheaders(body, encode_chunked=encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
localstack_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
localstack_1  |     self.send(msg)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 944, in send
localstack_1  |     self.connect()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
localstack_1  |     conn = self._new_conn()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
localstack_1  |     raise NewConnectionError(
localstack_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4bd518f2b0>: Failed to establish a new connection: [Errno 111] Connection refused
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
localstack_1  |     resp = conn.urlopen(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
localstack_1  |     retries = retries.increment(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
localstack_1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
localstack_1  | urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='100245e05df7', port=4590): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4bd518f2b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 86, in index
localstack_1  |     result = await run_sync(handler, request, data)
localstack_1  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 54, in run_sync
localstack_1  |     return await loop.run_in_executor(thread_pool, copy_context().run, func, *args)
localstack_1  |   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
localstack_1  |     result = self.fn(*self.args, **self.kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 555, in handler
localstack_1  |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 332, in modify_and_forward
localstack_1  |     listener_result = listener.forward_request(method=method,
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 70, in forward_request
localstack_1  |     response = function(url, data=data, headers=headers, verify=False, stream=True)
localstack_1  |   File "/opt/code/localstack/localstack/utils/common.py", line 1153, in _wrapper
localstack_1  |     return method(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack_1  |     return request('post', url, data=data, json=json, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
localstack_1  |     raise ConnectionError(e, request=request)
localstack_1  | requests.exceptions.ConnectionError: MyHTTPConnectionPool(host='100245e05df7', port=4590): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4bd518f2b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack_1  | 
```

# Steps to reproduce

## Command used to start LocalStack

```
docker-compose up
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal cognito-idp create-user-pool --pool-name=my-pool
```

**Comment by whummer** [comment]
Thanks for reporting @limenutt . This appears to be an issue with the host name setup inside your Docker container. Can you please try and see if it works with this additional environment configuration:
```
    environment:
        - HOSTNAME=localhost
```
and/or
```
    environment:
        - LOCALSTACK_HOSTNAME=localhost
```
Hope that helps in debugging the issue - please keep us posted. Thanks for your help.

**Comment by limenutt** [comment]
Hi @whummer , thank you for getting back to me. I've checked with the latest image and looks like the issue has been fixed now.
