### ISSUE TITLE
Localstack deployment fails with API GW HTTP_PROXY integration.

### ISSUE THREAD

**Issue by jonni-larjomaa** [localstack/localstack#2930]
# Type of request: This is a ...

bug report

# Detailed description

following cloudformation stack ends up in error.

```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "AuthorizerLogGroup": {
      "Type": "AWS::Logs::LogGroup",
      "Properties": {
        "LogGroupName": "/aws/lambda/hofund-local-authorizer"
      }
    },
    "IamRoleLambdaExecution": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": {
              "Fn::Join": [
                "-",
                [
                  "hofund",
                  "local",
                  "lambda"
                ]
              ]
            },
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:CreateLogStream",
                    "logs:CreateLogGroup"
                  ],
                  "Resource": [
                    {
                      "Fn::Sub": "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/hofund-local*:*"
                    }
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:PutLogEvents"
                  ],
                  "Resource": [
                    {
                      "Fn::Sub": "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/hofund-local*:*:*"
                    }
                  ]
                }
              ]
            }
          }
        ],
        "Path": "/",
        "RoleName": {
          "Fn::Join": [
            "-",
            [
              "hofund",
              "local",
              {
                "Ref": "AWS::Region"
              },
              "lambdaRole"
            ]
          ]
        },
        "ManagedPolicyArns": [
          {
            "Fn::Join": [
              "",
              [
                "arn:",
                {
                  "Ref": "AWS::Partition"
                },
                ":iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
              ]
            ]
          }
        ]
      }
    },
    "AuthorizerLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": "hofund-local-deployment",
          "S3Key": "serverless/hofund/local/1599143878432-2020-09-03T14:37:58.432Z/authorizer.zip"
        },
        "FunctionName": "hofund-local-authorizer",
        "Handler": "src/handlers/authorizer.handler",
        "MemorySize": 128,
        "Role": {
          "Fn::GetAtt": [
            "IamRoleLambdaExecution",
            "Arn"
          ]
        },
        "Runtime": "nodejs12.x",
        "Timeout": 10,
        "Tags": [
          {
            "Key": "env",
            "Value": "local"
          }
        ],
        "Environment": {
          "Variables": {
            "SESSION_URL": "https://example.com/api/session"
          }
        }
      },
      "DependsOn": [
        "AuthorizerLogGroup"
      ]
    },
    "AuthorizerLambdaVersionVumzx5NsNjF8c8NmvUEtuiwF3vxgvSRAvSmkFWlajA": {
      "Type": "AWS::Lambda::Version",
      "DeletionPolicy": "Retain",
      "Properties": {
        "FunctionName": {
          "Ref": "AuthorizerLambdaFunction"
        },
        "CodeSha256": "VcNU1m3qztfvKKOrt8vp5l7stHIP95RtEmgdK96vtHg="
      }
    },
    "ApiGatewayRestApi": {
      "Type": "AWS::ApiGateway::RestApi",
      "Properties": {
        "Name": "ApiGatewayRestApi",
        "EndpointConfiguration": {
          "Types": [
            "EDGE"
          ]
        }
      }
    },
    "ProxyResource": {
      "Type": "AWS::ApiGateway::Resource",
      "Properties": {
        "ParentId": {
          "Fn::GetAtt": [
            "ApiGatewayRestApi",
            "RootResourceId"
          ]
        },
        "PathPart": "testproxy",
        "RestApiId": {
          "Ref": "ApiGatewayRestApi"
        }
      }
    },
    "ProxyMethod": {
      "Type": "AWS::ApiGateway::Method",
      "Properties": {
        "AuthorizationType": "NONE",
        "ResourceId": {
          "Ref": "ProxyResource"
        },
        "RestApiId": {
          "Ref": "ApiGatewayRestApi"
        },
        "HttpMethod": "GET",
        "MethodResponses": [
          {
            "StatusCode": 200
          }
        ],
        "Integration": {
          "IntegrationHttpMethod": "GET",
          "Type": "HTTP_PROXY",
          "Uri": "http://example.com",
          "IntegrationResponses": [
            {
              "StatusCode": 200
            }
          ]
        }
      }
    },
    "ApiGWDeployment": {
      "Type": "AWS::ApiGateway::Deployment",
      "Properties": {
        "Description": "foobar",
        "RestApiId": {
          "Ref": "ApiGatewayRestApi"
        },
        "StageName": "local"
      },
      "DependsOn": [
        "ProxyMethod"
      ]
    }
  },
  "Outputs": {
    "ServerlessDeploymentBucketName": {
      "Value": "hofund-local-deployment"
    },
    "AuthorizerLambdaFunctionQualifiedArn": {
      "Description": "Current Lambda function version",
      "Value": {
        "Ref": "AuthorizerLambdaVersionVumzx5NsNjF8c8NmvUEtuiwF3vxgvSRAvSmkFWlajA"
      }
    }
  }
}
```

## Expected behavior

Stack creation works in AWS environment. stack created with http_proxy implementation deployed.

## Actual behavior
 
Deployment in local stack ends up in following error

```
2020-09-03T14:22:39:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "ApiGateway::Method" id "ProxyMethod"
2020-09-03T14:22:39:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "ApiGateway::Method" in region eu-north-1: put_method {'restApiId': 'y4fnek6cpw', 'resourceId': '7tj2ijegfm', 'httpMethod': 'GET', 'authorizationType': 'NONE'}
2020-09-03T14:22:39:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "ProxyMethod": An error occurred (BadRequestException) when calling the PutIntegration operation: Invalid HTTP endpoint specified for URI Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 278, in parse_and_create_resource
    return _parse_and_create_resource(
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 391, in _parse_and_create_resource
    result = deploy_func(logical_id, resource_map_new, stack_name=stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1132, in deploy_resource
    return execute_resource_action(resource_id, resources, stack_name, ACTION_CREATE)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1175, in execute_resource_action
    result = configure_resource_via_sdk(resource_id, resources, resource_type, func, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1267, in configure_resource_via_sdk
    apigateway.put_integration(restApiId=api_id, resourceId=res_id,
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 656, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the PutIntegration operation: Invalid HTTP endpoint specified for URI

2020-09-03T14:22:39:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "CreateStack" (400) POST /: b'Invalid HTTP endpoint specified for URI'
```

If I deploy this to the AWS it works but does not work on localstack. So I'm quite sure this is valid cloudformation.

**Comment by whummer** [comment]
Thanks for reporting @jonni-larjomaa . This should be fixed in #2954 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks
