### ISSUE TITLE
PRO: Issue with latest localstack docker image?

### ISSUE THREAD

**Issue by aaron-parsons** [localstack/localstack#2937]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
I have some version controlled code that was working this morning, but since I pulled the latest image it is not.
The code uses SNS to trigger a lambda, which is in turn supposed to push another SNS message using a boto3 call.

The boto3 call now returns a credentials error (see below), and if I print some environment variables from the lambda(using os.environ[key], it's true that the AWS credentials aren't set. When using >>localstack start I get a message saying:

2020-09-04 12:27:18.888: Loaded credentials from environment

but this seems to not follow through.

FOUND LOCALSTACK_HOSTNAME, IT WAS: 172.17.0.2
FOUND AWS_SECRET_ACCESS_KEY, IT WAS: 
FOUND AWS_ACCESS_KEY_ID, IT WAS: 

[ERROR] NoCredentialsError: Unable to locate credentials
Traceback (most recent call last):
  File "/var/task/launch_algorithmia.py", line 82, in handler
    sns_client.publish(**response_notification)
  File "/var/task/botocore/client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 642, in _make_api_call
    http, parsed_response = self._make_request(
  File "/var/task/botocore/client.py", line 662, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/var/task/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/var/task/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/var/task/botocore/endpoint.py", line 115, in create_request
    self._event_emitter.emit(event_name, request=request,
  File "/var/task/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/var/task/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/var/task/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/var/task/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/var/task/botocore/signers.py", line 160, in sign
    auth.add_auth(request)
  File "/var/task/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError

...

## Expected behavior
boto3 should find the credentials in the server-side environment
...

## Actual behavior
It doesn't find the credentials in the server-side environment (even when I naively set them in the shell before >>localstack start, or in the docker file for docker-compose).
...

# Steps to reproduce

## Command used to start LocalStack
DEBUG=1 localstack start 2>&1

or

docker-compose up 2>&1 (using the docker file in this repo)

**Comment by aaron-parsons** [comment]
The boto3 call I am using is similar to:
end_point = None if "LOCALSTACK_HOSTNAME" not in os.environ else "http://%s:4575" % os.environ["LOCALSTACK_HOSTNAME"] sns_client = boto3.client('sns', endpoint_url=end_point)
sns_client.publish(**response_notification)

and I can confirm that my build passes if I hardcode some dummy credentials into the lambda and set with os.environ[key]=

**Comment by yonahforst** [comment]
I'm getting a similar error in nodejs using the latest image:
```
START RequestId: cefa3d14-5314-1e35-bc07-e437a7be8c95 Version: $LATEST
2020-09-04T13:31:04.096Z	cefa3d14-5314-1e35-bc07-e437a7be8c95	ERROR	Invoke Error 	{"errorType":"CredentialsError","errorMessage":"Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1","code":"CredentialsError","message":"Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1","statusCode":404,"retryable":false,"time":"2020-09-04T13:31:04.092Z","originalError":{"message":"Could not load credentials from any providers","statusCode":404,"retryable":false,"time":"2020-09-04T13:31:04.092Z","code":"CredentialsError","originalError":{"message":"EC2 Metadata roleName request returned error","statusCode":404,"retryable":false,"time":"2020-09-04T13:31:04.091Z"}},"stack":["CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1","    at IncomingMessage.<anonymous> (/var/task/node_modules/aws-sdk/lib/util.js:895:34)","    at IncomingMessage.emit (events.js:327:22)","    at IncomingMessage.EventEmitter.emit (domain.js:482:12)","    at endReadableNT (_stream_readable.js:1221:12)","    at processTicksAndRejections (internal/process/task_queues.js:84:21)"]}
END RequestId: cefa3d14-5314-1e35-bc07-e437a7be8c95
REPORT RequestId: cefa3d14-5314-1e35-bc07-e437a7be8c95	Init Duration: 326.77 ms	Duration: 4342.82 ms	Billed Duration: 4400 ms	Memory Size: 1536 MB	Max Memory Used: 56 MB	
```

**Comment by aaron-parsons** [comment]
Hi. Was there any progress with this bug yet?

**Comment by whummer** [comment]
Hi @aaron-parsons we recently pushed a fix to set missing AWS environment variables in Lambda Docker containers - can you please verify/confirm that the issue still persists after pulling the `latest` Docker image? Also, can you please share the relevant part of your Lambda handler, in particular how the boto3 client is being configured. Thanks for your help.
