### ISSUE TITLE
Wrong region on SQS redrive

### ISSUE THREAD

**Issue by Lastin** [localstack/localstack#2943]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
Using redrive policy to move message from primary SQS to dead-letter SQS uses wrong region.
It tries to use _us-east-1_ (found thanks to commandeer), but terraform and serverless are pointed at eu-west-2
When I created queue with expected name in region _us-east-1_ it stopped throwing this error.
Similarly awslocal tries to use us-east-1 by default.
...

## Expected behavior
Moves message correctly when redrive condition met.
...

## Actual behavior
Throws an error, message remains in primary queue:

```
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 514, in run
localstack_1  |     self.func(self.params)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 160, in do_execute
localstack_1  |     return _run(func_arn=func_arn)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 146, in wrapped
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 142, in wrapped
localstack_1  |     result = func(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 149, in _run
localstack_1  |     dlq_sent = sqs_error_to_dead_letter_queue(sqs_queue_arn, event, e)
localstack_1  |   File "/opt/code/localstack/localstack/utils/aws/dead_letter_queue.py", line 25, in sqs_error_to_dead_letter_queue
localstack_1  |     return _send_to_dead_letter_queue('SQS', queue_arn, target_arn, event, error)
localstack_1  |   File "/opt/code/localstack/localstack/utils/aws/dead_letter_queue.py", line 68, in _send_to_dead_letter_queue
localstack_1  |     raise Exception(msg)
localstack_1  | Exception: Unable to send message to dead letter queue http://localhost:4576/000000000000/emailDeadLetter (code None): Unable to parse response (no element found: line 1, column 0), invalid XML received. Further retries may succeed:
localstack_1  | b''

```

...

# Steps to reproduce
1. Start below config.
1. Add message to queue, and make sure your handler fails.
1. See above error

## Command used to start LocalStack
`docker-compose up -d`
`terraform apply --auto-approve`
`sls deploy --stage local`

docker-compose.yml

```
version: "3.7"
services:
  localstack:
    image: localstack/localstack:0.11.4
    ports: [ "4566-4599:4566-4599" ]
    environment:
      - DEBUG=1
      - SERVICES=sqs,sns,dynamodb,apigateway,ssm,lambda,s3,cloudformation,sts,iam,cloudwatch,logs
      - DEFAULT_REGION=eu-west-2
      - LAMBDA_EXECUTOR=docker-reuse
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

terraform.tf part:

```
provider "aws" {
  region                      = "eu-west-2"
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true
  s3_force_path_style         = true
  access_key                  = "mock_access_key"
  secret_key                  = "mock_secret_key"

  endpoints {
    sns            = "http://localhost:4566"
    sqs            = "http://localhost:4566"
    dynamodb       = "http://localhost:4566"
    s3             = "http://localhost:4572"
    cloudwatch     = "http://localhost:4566"
    ssm            = "http://localhost:4566"
  }
}
resource "aws_sqs_queue" "email_dead_letter" {
  name = "emailDeadLetter"
  receive_wait_time_seconds = 20
}

resource "aws_sqs_queue" "email" {
  name = "email"
  visibility_timeout_seconds = 120
  receive_wait_time_seconds = 10
  redrive_policy = jsonencode({
    deadLetterTargetArn = aws_sqs_queue.email_dead_letter.arn
    maxReceiveCount = 2
  })
}
resource "aws_ssm_parameter" "event_queue" {
  name = "/email_module/event_queue_arn"
  description = "Queue from which email service should consume"
  type = "String"
  value = aws_sqs_queue.email.arn
}
```

serverless.yml part:

```
provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage,'dev'}
  region: eu-west-2

service: email-service
functions:
  eventQueueHandler:
    handler: bin/handler
    events:
      - sqs: ${ssm:/email_module/event_queue_arn}
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-252) by [Unito](https://www.unito.io/learn-more)

**Comment by macnev2013** [comment]
Hey, @Lastin Thanks for reporting. Can you give it a try with the latest version of `localstack`.

**Comment by whummer** [comment]
Thanks for reporting @Lastin - this should be resolved in the meantime, support for multi-region setups has been added in 59294e6ffef64244d383c4c4467d1c65caa8c87a . Please let us know if the problem persists. Thanks!
