### ISSUE TITLE
S3 POST Browser direct upload fails to create file on the bucket and return the proper HTTP code

### ISSUE THREAD

**Issue by julianguinard** [localstack/localstack#2948]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

[Browser uploads](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingHTTPPOST.html) done by POSTing files directly from the browser to the S3 bucket using an AWS presigned POST Policy do not save the files nor return the status_code requested by the signature

## Expected behavior

Browser-based upload should result in the uploaded file being stored in the bucket with an HTTP 201 CREATED return code

## Actual behavior

browser POST request to the S3 bucket does not save the file and returns a 200 HTTP code while having the following warning logged in the localstack_main docker container

```
2020-09-07T10:15:03:WARNING:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7f945dfd50d0>(None) failed: can only concatenate str (not "Header") to str Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 521, in run
    result = self.func(self.params)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 555, in handler
    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 332, in modify_and_forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1028, in forward_request
    expanded_data = multipart_content.expand_multipart_filename(original_data, headers)
  File "/opt/code/localstack/localstack/services/s3/multipart_content.py", line 54, in expand_multipart_filename
    for (disposition, _) in _iter_multipart_parts(data_bytes, boundary):
  File "/opt/code/localstack/localstack/services/s3/multipart_content.py", line 33, in _iter_multipart_parts
    _, params = cgi.parse_header(head_parsed['Content-Disposition'])
  File "/usr/lib/python3.8/cgi.py", line 226, in parse_header
    parts = _parseparam(';' + line)
TypeError: can only concatenate str (not "Header") to str
```

# Steps to reproduce

1. Create the `s3-bucket`

```
aws --profile localstack --endpoint-url http://localhost:4566 s3api create-bucket --bucket s3-bucket
```

2. Get an S3 presigned POST policy from a backend which has credentials to localstack.

Example of JSON-formatted, backend-returned AWS presigned POST policy

```json
{
  "data": {
    "getS3PostPolicy": {
      "url": "http://localstack_main:4566/s3-bucket",
      "key": "uploads/2020/09/07/569a8732-f13c-44af-af66-7dd26fe1fd2a.png",
      "acl": "bucket-owner-full-control",
      "successActionStatus": "201",
      "fields": {
        "bucket": "s3-bucket",
        "XAmzAlgorithm": "AWS4-HMAC-SHA256",
        "XAmzSignature": "9fc4d4516eae42c8348eb85990269132b7b7b35c23c8facd067adca6e86ee1dd",
        "XAmzCredential": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/20200907/eu-west-3/s3/aws4_request",
        "XAmzDate": "20200907T102225Z",
        "Policy": "eyJleHBpcmF0aW9uIjoiMjAyMC0wOS0wN1QxMDoyNzoyNVoiLCJjb25kaXRpb25zIjpbeyJhY2wiOiJidWNrZXQtb3duZXItZnVsbC1jb250cm9sIn0seyJrZXkiOiJ1cGxvYWRzLzIwMjAvMDkvMDcvNTY5YTg3MzItZjEzYy00NGFmLWFmNjYtN2RkMjZmZTFmZDJhLnBuZyJ9LHsic3VjY2Vzc19hY3Rpb25fc3RhdHVzIjoiMjAxIn0sWyJjb250ZW50LWxlbmd0aC1yYW5nZSIsMCwxMDAwMDAwMF0sWyJzdGFydHMtd2l0aCIsIiRDb250ZW50LVR5cGUiLCJpbWFnZS9wbmciXSx7ImJ1Y2tldCI6InMzLWJ1Y2tldCJ9LHsiWC1BbXotQWxnb3JpdGhtIjoiQVdTNC1ITUFDLVNIQTI1NiJ9LHsiWC1BbXotQ3JlZGVudGlhbCI6ImFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhLzIwMjAwOTA3L2V1LXdlc3QtMy9zMy9hd3M0X3JlcXVlc3QifSx7IlgtQW16LURhdGUiOiIyMDIwMDkwN1QxMDIyMjVaIn1dfQ==",
        "__typename": "S3PostPolicyFields"
      },
      "__typename": "S3PostPolicy"
    }
  }
}
```

3. POST file direcly using the above presigned POST Policy

CURL call
```
curl 'http://localstack_main:4566/s3-bucket' \
  -H 'Connection: keep-alive' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36' \
  -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundary0kzUj8XiEaOk8AZG' \
  -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
  --data-binary $'------WebKitFormBoundary0kzUj8XiEaOk8AZG\r\nContent-Disposition: form-data; name="key"\r\n\r\nuploads/2020/09/07/3b52cfed-88b9-4258-960a-1b4fddf06fc5.png\r\n------WebKitFormBoundary0kzUj8XiEaOk8AZG\r\nContent-Disposition: form-data; name="policy"\r\n\r\neyJleHBpcmF0aW9uIjoiMjAyMC0wOS0wN1QxMDoyNzoxNloiLCJjb25kaXRpb25zIjpbeyJhY2wiOiJidWNrZXQtb3duZXItZnVsbC1jb250cm9sIn0seyJrZXkiOiJ1cGxvYWRzLzIwMjAvMDkvMDcvM2I1MmNmZWQtODhiOS00MjU4LTk2MGEtMWI0ZmRkZjA2ZmM1LnBuZyJ9LHsic3VjY2Vzc19hY3Rpb25fc3RhdHVzIjoiMjAxIn0sWyJjb250ZW50LWxlbmd0aC1yYW5nZSIsMCwxMDAwMDAwMF0sWyJzdGFydHMtd2l0aCIsIiRDb250ZW50LVR5cGUiLCJpbWFnZS9wbmciXSx7ImJ1Y2tldCI6InMzLWJ1Y2tldCJ9LHsiWC1BbXotQWxnb3JpdGhtIjoiQVdTNC1ITUFDLVNIQTI1NiJ9LHsiWC1BbXotQ3JlZGVudGlhbCI6ImFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhLzIwMjAwOTA3L2V1LXdlc3QtMy9zMy9hd3M0X3JlcXVlc3QifSx7IlgtQW16LURhdGUiOiIyMDIwMDkwN1QxMDIyMTZaIn1dfQ==\r\n------WebKitFormBoundary0kzUj8XiEaOk8AZG\r\nContent-Disposition: form-data; name="x-amz-algorithm"\r\n\r\nAWS4-HMAC-SHA256\r\n------WebKitFormBoundary0kzUj8XiEaOk8AZG\r\nContent-Disposition: form-data; name="x-amz-credential"\r\n\r\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/20200907/eu-west-3/s3/aws4_request\r\n------WebKitFormBoundary0kzUj8XiEaOk8AZG\r\nContent-Disposition: form-data; name="x-amz-date"\r\n\r\n20200907T102216Z\r\n------WebKitFormBoundary0kzUj8XiEaOk8AZG\r\nContent-Disposition: form-data; name="x-amz-signature"\r\n\r\nc3cbac3ca89a90381701b1057fea9111db254e01c1ceb4ef94290cb2777ecbd6\r\n------WebKitFormBoundary0kzUj8XiEaOk8AZG\r\nContent-Disposition: form-data; name="acl"\r\n\r\nbucket-owner-full-control\r\n------WebKitFormBoundary0kzUj8XiEaOk8AZG\r\nContent-Disposition: form-data; name="Content-Type"\r\n\r\nimage/png\r\n------WebKitFormBoundary0kzUj8XiEaOk8AZG\r\nContent-Disposition: form-data; name="success_action_status"\r\n\r\n201\r\n------WebKitFormBoundary0kzUj8XiEaOk8AZG\r\nContent-Disposition: form-data; name="file"; filename="Sélection_763.png"\r\nContent-Type: image/png\r\n\r\n\r\n------WebKitFormBoundary0kzUj8XiEaOk8AZG--\r\n' \
  --compressed \
  --insecure -vvv
```

## Command used to start LocalStack

docker-compose up -d

**Comment by whummer** [comment]
Thanks for reporting @julianguinard . This should be fixed in #3220 - can you please pull the `latest` Docker image and give it another try..? Please report here if the problem persists. Thanks
