### ISSUE TITLE
404 with DynamoDB Stream to Lambda

### ISSUE THREAD

**Issue by rcoundon** [localstack/localstack#2959]
# Type of request: This is a (possibly) a defect

[x] bug report
[ ] feature request

# Detailed description
I have a DynamoDB table with a stream targeting a lambda function. When data is written to the table an error is written to the log and the target lambda is not called
...

## Expected behavior
Expect the target lambda to be called
...

## Actual behavior
The data is written but the stream doesn't reach the lambda
...

# Steps to reproduce
Run the following script to create resources.
Then add the event source

## Command used to start LocalStack
docker-compose up

```
version: '2.1'
services:
  localstack:
    image: localstack/localstack
    privileged: true
    container_name: localstack-main
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=OMITTED
      - LAMBDA_REMOTE_DOCKER=false
      - SERVICES=serverless,cloudwatch
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```
The script for creating the entities is:

```
#!/bin/bash

FUNCTION_NAME=my-func
REGION=eu-west-2
STAGE=dev
TABLE_NAME=my-table
ROLE_NAME=MyRole
POLICY_NAME=MyPolicy
AWS_ENDPOINT=http://localhost:4566

aws dynamodb create-table \
  --endpoint ${AWS_ENDPOINT} \
  --table-name ${TABLE_NAME} \
  --region ${REGION} \
  --attribute-definitions \
    AttributeName=PK,AttributeType=S \
    AttributeName=SK,AttributeType=S \
  --key-schema \
    AttributeName=PK,KeyType=HASH \
    AttributeName=SK,KeyType=RANGE \
  --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
  --stream-specification StreamEnabled=true,StreamViewType=NEW_AND_OLD_IMAGES \
  --global-secondary-indexes \
    "[
        {
            \"IndexName\": \"GSI1\",
            \"KeySchema\": [
                {\"AttributeName\":\"SK\",\"KeyType\":\"HASH\"},
                {\"AttributeName\":\"PK\",\"KeyType\":\"RANGE\"}
            ],
            \"Projection\": {
                \"ProjectionType\":\"ALL\"
            },
            \"ProvisionedThroughput\": {
                \"ReadCapacityUnits\": 5,
                \"WriteCapacityUnits\": 5
            }
        }
    ]"

aws iam create-role \
  --endpoint ${AWS_ENDPOINT} \
  --role-name ${ROLE_NAME} \
  --path "/service-role/" \
  --assume-role-policy-document file://deploy/dev/role/trust-relationship.json

aws iam put-role-policy \
  --endpoint ${AWS_ENDPOINT} \
  --role-name ${ROLE_NAME} \
  --policy-name ${POLICY_NAME} \
  --policy-document file://deploy/dev/role/role-policy.json

aws lambda publish-layer-version \
    --endpoint ${AWS_ENDPOINT} \
    --region ${REGION} \
    --layer-name sharp \
    --compatible-runtimes nodejs12.x \
    --zip-file fileb://src/sharpLayer/Archive.zip

aws lambda create-function \
  --endpoint ${AWS_ENDPOINT} \
  --region ${REGION} \
  --role arn:aws:iam::000000000000:role/service-role/${ROLE_NAME} \
  --function-name ${FUNCTION_NAME} \
  --zip-file fileb://build.zip \
  --handler build/psoServer/functions/processActivityStreamEvent.handler \
  --layers arn:aws:lambda:eu-west-2:000000000000:layer:sharp:1 \
  --timeout 10 \
  --runtime nodejs12.x

```
The event source is added:

```
aws lambda create-event-source-mapping \
  --endpoint ${AWS_ENDPOINT} \
  --region ${REGION} \
  --function-name ${FUNCTION_NAME} \
  --event-source arn:aws:dynamodb:eu-west-2:000000000000:table/${FUNCTION_NAME}/stream/2020-09-08T21:58:27.986  \
  --batch-size 5 \
  --starting-position TRIM_HORIZON

```
The error is:
```
localstack-main | 2020-09-08T22:00:03:WARNING:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fe2abffc4c0>(None) failed: An error occurred (404) when calling the PutRecord operation:  Traceback (most recent call last):
localstack-main |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 521, in run
localstack-main |     result = self.func(self.params)
localstack-main |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack-main |     return fn(*args, **kwargs)
localstack-main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 555, in handler
localstack-main |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack-main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/aws/aws_utils.py", line 22, in modify_and_forward
localstack-main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 398, in modify_and_forward
localstack-main |     updated_response = update_listener.return_response(**kwargs)
localstack-main |   File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 364, in return_response
localstack-main |     forward_to_ddb_stream(records)
localstack-main |   File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 635, in forward_to_ddb_stream
localstack-main |     dynamodbstreams_api.forward_events(records)
localstack-main |   File "/opt/code/localstack/localstack/services/dynamodbstreams/dynamodbstreams_api.py", line 55, in forward_events
localstack-main |     kinesis.put_record(StreamName=stream_name, Data=json.dumps(record), PartitionKey='TODO')
localstack-main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
localstack-main |     return self._make_api_call(operation_name, kwargs)
localstack-main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 656, in _make_api_call
localstack-main |     raise error_class(parsed_response, operation_name)
localstack-main | botocore.exceptions.ClientError: An error occurred (404) when calling the PutRecord operation: 
localstack-main | 
```

**Comment by rcoundon** [comment]
I'm not able to tag as PRO, hopefully somebody spots this :-D

**Comment by rcoundon** [comment]
I've tried recreating the table with no stream and I don't see the error. So it would appear the issue is with something in the DynamoDB stream implementation

**Comment by rcoundon** [comment]
Interestingly, only if I have the stream enabled, some of my tests that run to write data to the table fail.
For example, a PutItem result is not returned e.g. this result is undefined here:
```
const result = await ddb?.putItem(params).promise();
```

**Comment by whummer** [comment]
Thanks for reporting @rcoundon . The issue here could be that the Kinesis service is not started up. (An integration test has been added in #2966 to cover this functionality.) Can you please try updating the `environment` section in your Docker-compose with this: 
```
- SERVICES=serverless,dynamodb,dynamodbstreams,kinesis,cloudwatch
```
Hope that helps - please keep us posted. Thanks!
