### ISSUE TITLE
Cannot invoke a zip deployed nodejs or python lambda deployed into localstack

### ISSUE THREAD

**Issue by togakangaroo** [localstack/localstack#2969]
# Type of request: This is a ...

[x] bug report

# Detailed description

I am trying to deploy a very simple lambda to localstack and then invoke it

My localstack is set up with the following compose service

```yaml
  localstack:
    image: localstack/localstack-full:latest
    depends_on:
      - db
    ports:
      - "4563-4599:4563-4599"
      - "8055:8080"
    environment:
      - SERVICES=s3,sqs,sns,lambda
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

I create a file `index.js`
```js
     exports.handler = async (event) => {
       console.log(`Localstack lambda`, JSON.stringify(event))
       return {
         statusCode: 200,
         body: JSON.stringify(`yo yo, from localstack lambda`)
       }
     }
```

I zip it up

```shell
     zip loggingLambda.zip index.js
```

I then create the function
```shell
     aws lambda create-function \
         --endpoint http://localhost:4566 \
         --function-name loggingLambda \
         --runtime nodejs12.x \
         --role arn:aws:iam::000000000000:role/lambda-ex \
         --zip-file fileb://loggingLambda.zip \
         --handler index.handler
```

and try to invoke it
```shell
     aws lambda invoke \
         --endpoint http://localhost:4566 \
         --function-name loggingLambda \
         out \
         --log-type Tail
```

## Expected behavior
I expected the lambda to return and log

## Actual behavior

Unfortunately it does not
```json
   {
       "StatusCode": 200,
       "FunctionError": "Unhandled",
       "LogResult": "",
       "ExecutedVersion": "$LATEST"
   }
```

What shows up in the localstack log indicates that the issue is `index.handler is undefined or not exported` but it is!

```
localstack_1  | 2020-09-10T20:31:44:WARNING:localstack.services.awslambda.lambda_executors: Empty event body specified for invocation of Lambda "arn:aws:lambda:us-east-1:000000000000:function:loggingLambda"
localstack_1  | 2020-09-10T20:31:44:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: docker run -i  -v "/tmp/localstack/zipfile.c9303c10":/var/task -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e NODE_TLS_REJECT_UNAUTHORIZED="$NODE_TLS_REJECT_UNAUTHORIZED"  --rm "lambci/lambda:nodejs12.x" "index.handler"
localstack_1  | 2020-09-10T20:31:45:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:loggingLambda result / log output:
localstack_1  | {"errorType":"Runtime.HandlerNotFound","errorMessage":"index.handler is undefined or not exported"}
localstack_1  | > 2020-09-10T20:31:45.203Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.HandlerNotFound","errorMessage":"index.handler is undefined or not exported","stack":["Runtime.HandlerNotFound: index.handler is undefined or not exported","    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1138:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)","    at Module.load (internal/modules/cjs/loader.js:986:32)","    at Function.Module._load (internal/modules/cjs/loader.js:879:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)","    at internal/main/run_main_module.js:17:47"]}
localstack_1  | > START RequestId: 1f202203-3539-18dc-febd-292a260d803f Version: $LATEST
localstack_1  | > END RequestId: 1f202203-3539-18dc-febd-292a260d803f
localstack_1  | > REPORT RequestId: 1f202203-3539-18dc-febd-292a260d803f	Init Duration: 122.47 ms	Duration: 2.52 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 40 MB	
localstack_1  | 2020-09-10T20:31:45:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:loggingLambda: Lambda process returned error status code: 1. Result: {"errorType":"Runtime.HandlerNotFound","errorMessage":"index.handler is undefined or not exported"}. Output:
localstack_1  | 2020-09-10T20:31:45.203Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.HandlerNotFound","errorMessage":"index.handler is undefined or not exported","stack":["Runtime.HandlerNotFound: index.handler is undefined or not exported","    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1138:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)","    at Module.load (internal/modules/cjs/loader.js:986:32)","    at Function.Module._load (internal/modules/cjs/loader.js:879:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)","    at internal/main/run_main_module.js:17:47"]}
localstack_1  | START RequestId: 1f202203-3539-18dc-febd-292a260d803f Version: $LATEST
localstack_1  | END RequestId: 1f202203-3539-18dc-febd-292a260d803f
localstack_1  | REPORT RequestId: 1f202203-3539-18dc-febd-292a260d803f	Init Duration: 122.47 ms	Duration: 2.52 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 40 MB	 Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 529, in run_lambda
localstack_1  |     result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 166, in execute
localstack_1  |     return do_execute()
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 158, in do_execute
localstack_1  |     return _run(func_arn=func_arn)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 146, in wrapped
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 142, in wrapped
localstack_1  |     result = func(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 151, in _run
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 139, in _run
localstack_1  |     result = self._execute(func_arn, func_details, event, context, version)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 296, in _execute
localstack_1  |     result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 203, in run_lambda_executor
localstack_1  |     raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
localstack_1  | Exception: Lambda process returned error status code: 1. Result: {"errorType":"Runtime.HandlerNotFound","errorMessage":"index.handler is undefined or not exported"}. Output:
localstack_1  | 2020-09-10T20:31:45.203Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.HandlerNotFound","errorMessage":"index.handler is undefined or not exported","stack":["Runtime.HandlerNotFound: index.handler is undefined or not exported","    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1138:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)","    at Module.load (internal/modules/cjs/loader.js:986:32)","    at Function.Module._load (internal/modules/cjs/loader.js:879:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)","    at internal/main/run_main_module.js:17:47"]}
localstack_1  | START RequestId: 1f202203-3539-18dc-febd-292a260d803f Version: $LATEST
localstack_1  | END RequestId: 1f202203-3539-18dc-febd-292a260d803f
localstack_1  | REPORT RequestId: 1f202203-3539-18dc-febd-292a260d803f	Init Duration: 122.47 ms	Duration: 2.52 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 40 MB	
localstack_1  | 
```

**Comment by togakangaroo** [comment]
I just checked, the exact same zip file deployed to real aws in the exact same manner worked just fine. This definitely makes me think the issue is with localstack

**Comment by togakangaroo** [comment]
Tried a python lambda as well. The exact same code and the exact same uploading and invocation scripts against real aws work, against localstack generate 

```
localstack_1  | 2020-09-11T03:16:42:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:python_lambda: Lambda process returned error status code: 1. Result: {"errorType":"Runtime.ImportModuleError","errorMessage":"Unable to import module 'handler': No module named 'handler'"}. Output:
```

Do lambdas not work at all in localstack?

**Comment by togakangaroo** [comment]
I take it the activity means that this is a legitimate issue? Is there a workaround for the time being?

**Comment by whummer** [comment]
Thanks for reporting @togakangaroo . The problem is that if `LAMBDA_REMOTE_DOCKER=false` is specified, then LocalStack is mounting the code from the local file system into the Lambda container, and hence needs to know about the location of the tmp folder on the host system (via `HOST_TMP_FOLDER`).

Can you please try adding the following to your docker-compose config:
```
environment:
- HOST_TMP_FOLDER=${PWD}/.localstack
...
```

We'll add a note to the README (and a warning message to the startup logs) to further clarify this point.

Please report here if the problem persists. Thanks!
