### ISSUE TITLE
SNS Exception thrown while subscribing a queue to SNS topic

### ISSUE THREAD

**Issue by a-wi** [localstack/localstack#2972]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

While attempting to subscribe a queue to SNS topic with SubscribeQueue()  (AWS SDK .NET) there is thrown ThirdParty.Json.LitJson.JsonException.
This doesn't occur with AWS Services.

## Expected behavior

No exception should be thrown while subscribing a queue to the SNS topic.

## Actual behavior

Following exception is thrown while attempting to subscribe a queue to the SNS topic:
````
ThirdParty.Json.LitJson.JsonException: Invalid character 'N' in input string
   at ThirdParty.Json.LitJson.Lexer.NextToken()
   at ThirdParty.Json.LitJson.JsonReader.ReadToken()
   at ThirdParty.Json.LitJson.JsonReader.Read()
   at ThirdParty.Json.LitJson.JsonMapper.ReadValue(WrapperFactory factory, JsonReader reader)
   at ThirdParty.Json.LitJson.JsonMapper.ToWrapper(WrapperFactory factory, String json)
   at ThirdParty.Json.LitJson.JsonMapper.ToObject(String json)
   at Amazon.Auth.AccessControlPolicy.Internal.JsonPolicyReader.ReadJsonStringToPolicy(String jsonString)
   at Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceClient.SubscribeQueueToTopicsAsync(IList`1 topicArns, ICoreAmazonSQS sqsClient, String sqsQueueUrl)
   at Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceClient.SubscribeQueueAsync(String topicArn, ICoreAmazonSQS sqsClient, String sqsQueueUrl)
   at TestSNS_Subscription.Program.TestSubscribingToSNS() in Program.cs:line 42
````

# Steps to reproduce

LocalStack 0.11.4
AWSSDK.SimpleNotificationService 3.5.0.11
AWSSDK.SQS 3.5.0.11
Target framework .NET Core 3.1

## Command used to start LocalStack

docker run -p 4566:4566 -p 8080:8080 --rm -e SERVICES=sqs,sns -e DEBUG=1 -e DATA_DIR=/tmp/localstack/data localstack/localstack:0.11.4

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
````
static async Task TestSubscribingToSNS()
{
    AmazonSQSConfig sqsConfig = new AmazonSQSConfig
    {
        ServiceURL = "http://localhost:4566"
    };
    AmazonSimpleNotificationServiceConfig snsConfig = new AmazonSimpleNotificationServiceConfig
    {
        ServiceURL = "http://localhost:4566"
    };

    using (AmazonSQSClient SQS = new AmazonSQSClient("ignore", "ignore", sqsConfig))
    using (AmazonSimpleNotificationServiceClient SNS = new AmazonSimpleNotificationServiceClient("ignore", "ignore", snsConfig))
//    using (AmazonSQSClient SQS = new AmazonSQSClient())
//    using (AmazonSimpleNotificationServiceClient SNS = new AmazonSimpleNotificationServiceClient())
    {
        CreateTopicResponse createTopicResp = await SNS.CreateTopicAsync(string.Format("testTopic_{0}", Guid.NewGuid().ToString()));
        CreateQueueResponse createQueueResp = await SQS.CreateQueueAsync(string.Format("testQueue_{0}", Guid.NewGuid().ToString()));
        await Task.Delay(5000);

        try
        {
            string subscriptionArn = await SNS.SubscribeQueueAsync(createTopicResp.TopicArn, SQS, createQueueResp.QueueUrl);
            Console.WriteLine("Subscribed to the topic.");

            await Task.Delay(5000);
            await SNS.UnsubscribeAsync(subscriptionArn);
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.ToString());
        }

        await SQS.DeleteQueueAsync(createQueueResp.QueueUrl);
        await SNS.DeleteTopicAsync(createTopicResp.TopicArn);
    }
}
````

**Comment by whummer** [comment]
Thanks for reporting @a-wi . Any chance you can enable debug mode in your client code, and share a dump of the messages that are getting sent over the wire? Thanks

**Comment by a-wi** [comment]
Exception is thrown while calling to `AmazonSimpleNotificationServiceClient.SubscribeQueueAsync()` so the issue occurs before sending a message.

**Comment by kkolstad** [comment]
I just ran across this as well. The problem is that the call to `sqsClient.GetAttributesAsync(sqsQueueUrl)` (I'm using the C# client) inside `snsClient.SubscribeQueueToTopicsAsync` returns a dictionary containing the key `Policy` with the value `None`. The SNS client assumes any string is valid JSON and attempts to parse the policy [`Policy.FromJson(json)`](https://github.com/aws/aws-sdk-net/blob/7c88eeceb52869892adb1fe50c3f06c8f1a6b126/sdk/src/Services/SimpleNotificationService/Custom/_async/AmazonSimpleNotificationServiceClient.Extensions.cs#L126)

@a-wi I have a custom SQS client and was able to use the following as a workaround:

```
internal class MySqsClient : AmazonSQSClient, ICoreAmazonSQS
{
...
  async Task<Dictionary<string, string>> ICoreAmazonSQS.GetAttributesAsync(
      string queueUrl)
  {
      var result = (await this.GetQueueAttributesAsync(
              new GetQueueAttributesRequest()
              {
                  AttributeNames = new List<string>() { "All" },
                  QueueUrl = queueUrl
              })
          .ConfigureAwait(false)).Attributes;

      if (result.ContainsKey("Policy") && result["Policy"] == "None")
      {
          result["Policy"] = string.Empty;
      }

      return result;
  }
...
}
```

**Comment by kkolstad** [comment]
You can repro using the CLI as follows:

```
$ aws --region=us-east-1 --endpoint-url=http://localhost:4566 sqs create-queue --queue-name foo
{
    "QueueUrl": "http://localhost:4566/000000000000/foo"
}

$ aws --region=us-east-1 --endpoint-url=http://localhost:4566 sqs get-queue-attributes --queue-url http://localhost:4566/000000000000/foo --attribute-names All
{
    "Attributes": {
        "ApproximateNumberOfMessagesNotVisible": "0",
        "Policy": "None",
        "VisibilityTimeout": "30",
        "ApproximateNumberOfMessagesDelayed": "0",
        "RedrivePolicy": "None",
        "MaximumMessageSize": "262144",
        "CreatedTimestamp": "1601681749.433461",
        "ApproximateNumberOfMessages": "0",
        "ReceiveMessageWaitTimeSeconds": "0",
        "DelaySeconds": "0",
        "MessageRetentionPeriod": "345600",
        "LastModifiedTimestamp": "1601681749.433461",
        "QueueArn": "arn:aws:sqs:us-east-1:000000000000:foo"
    }
}
```

**Comment by usmangani1** [comment]
@a-wi 
Thanks for reporting the issue. @kkolstad  thanks for the digging deep into it.
Some fixes have been made in the upstream moto relating to the same functionality.
Can you please pull the latest version of localstack and let us know if you still see the issue? Thanks

**Comment by a-wi** [comment]
I can confirm this issue is no longer seen with LS 0.11.5 and 0.11.6.
