### ISSUE TITLE
localstack/athena can't retrieve query-results

### ISSUE THREAD

**Issue by ChristopherMacGown** [localstack/localstack#2980]
# Type of request: This is a ...
[X] bug report
[ ] feature request

# Detailed description
After a query-execution has completed, calling `get-query-results` blows up with a 500 Internal error.

...

## Expected behavior
```
    $ awslocal athena get-query-results --query-execution-id=429f6a99
{
    "ResultSet": {
        "Rows": [{
            "Data": [
                { "VarCharValue": "1" },
                { "VarCharValue": "2" },
                { "VarCharValue": "3" }
            ]
        }],
        "ResultSetMetadata": { "ColumnInfo": [] }
    },
    "UpdateCount": 0
}
    
```

## Actual behavior
```
    $ awslocal athena get-query-results --query-execution-id=429f6a99

    An error occurred (500) when calling the GetQueryResults operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
    <title>500 Internal Server Error</title>
    <h1>Internal Server Error</h1>
    <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

And the logs from the running container:

```
localstack_main | 2020-09-14T23:37:40:ERROR:athena_api: Exception on / [POST]
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
localstack_main |     response = self.full_dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
localstack_main |     rv = self.handle_user_exception(e)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
localstack_main |     reraise(exc_type, exc_value, tb)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_main |     raise value
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
localstack_main |     rv = self.dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
localstack_main |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/athena/athena_api.py", line 197, in api_entrypoint
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
localstack_main |     dumps(data, indent=indent, separators=separators) + "\n",
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
localstack_main |     rv = _json.dumps(obj, **kwargs)
localstack_main |   File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
localstack_main |     return cls(
localstack_main |   File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
localstack_main |     chunks = self.iterencode(o, _one_shot=True)
localstack_main |   File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
localstack_main |     return _iterencode(o, 0)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/json/__init__.py", line 100, in default
localstack_main |     return _json.JSONEncoder.default(self, o)
localstack_main |   File "/usr/lib/python3.8/json/encoder.py", line 179, in default
localstack_main |     raise TypeError(f'Object of type {o.__class__.__name__} '
localstack_main | TypeError: Object of type Response is not JSON serializable
```

# Steps to reproduce
## Command used to start LocalStack
I started localstack with the following docker-compose configuration.

```
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=edge,cognito,serverless,athena,s3
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=[ELIDED]
      - DNS_RESOLVE_IP=172.23.0.1
      - AUTOSTART_UTIL_CONTAINERS
    volumes:
      - "./build/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
$ awslocal athena start-query-execution --query-string="SELECT 1, 2,3;"
{
    "QueryExecutionId": "429f6a99"
}


$ awslocal athena list-query-executions
{
    "QueryExecutionIds": [
        "429f6a99"
    ]
}
$ awslocal athena get-query-results --query-execution-id=429f6a99
{
    "ResultSet": {
        "Rows": [],
        "ResultSetMetadata": {
            "ColumnInfo": []
        }
    },
    "UpdateCount": 0
}

# ... WAIT UNTIL THE QUERY IS NO LONGER EXECUTING ...
$ awslocal athena list-query-executions{
    "QueryExecutionIds": []
}

$ awslocal athena get-query-results --query-execution-id=429f6a99

An error occurred (500) when calling the GetQueryResults operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-264) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @ChristopherMacGown . Not sure if related, but can you please try one more time without the trailing semicolon:

```
awslocal athena start-query-execution --query-string="SELECT 1, 2, 3"
```
(If that fixes the issue, we'll push a fix to allow semicolons).

Thanks for your help.

**Comment by ChristopherMacGown** [comment]
Hi @whummer,

I just ran that query without the trailing semi-colon with the same result.

```
# awslocal athena start-query-execution --query-string "SELECT 1,2,3"
{
    "QueryExecutionId": "ca442fa0"
}
# awslocal athena list-query-executions{
    "QueryExecutionIds": [
        "ca442fa0"
    ]
}
...  time passed ...
# awslocal athena list-query-executions
{
    "QueryExecutionIds": []
}
# awslocal athena get-query-results --query-execution-id=ca442fa0

An error occurred (500) when calling the GetQueryResults operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

The docker image is the latest as far as I can tell:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/43081/93271387-f9088a00-f767-11ea-9ca2-e6ad7c266516.png">

Thanks!

**Comment by whummer** [comment]
Thanks for the quick response @ChristopherMacGown - one more thing, which version/ID of the LocalStack image are you using?
```
docker images | grep localstack/localstack
```
Thanks

**Comment by ChristopherMacGown** [comment]
```
docker images | grep localstack/localstack
localstack/localstack                           latest              1370f9ca4c48        27 hours ago        668MB
```

**Comment by whummer** [comment]
This should be (hopefully) fixed in the meantime. Please let us know if the problem persists with the `latest` Docker image. Thanks for your help!
