### ISSUE TITLE
localstack/cloudfront throws an error on startup

### ISSUE THREAD

**Issue by piekarskid** [localstack/localstack#2986]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description

There's error being thrown when I launch localstack with `cloudfront` service. Without it everything runs smoothly

## Expected behavior

No error is being thrown and everything works fine

## Actual behavior
Log from container, it's thrown in a loop
```
2020-09-16 10:26:12,899:API:  * Running on http://0.0.0.0:54011/ (Press CTRL+C to quit)
2020-09-16T10:26:12:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 1057.2130680084229ms
2020-09-16 10:26:15,283 INFO exited: infra (exit status 2; not expected)
2020-09-16 10:26:15,284 INFO spawned: 'infra' with pid 5869
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/cli.py", line 157, in main
    subcommand['function'](argv, args)
  File "/opt/code/localstack/localstack/utils/cli.py", line 60, in cmd_infra
    start_infra_locally()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 300, in start_infra_locally
    return infra.start_infra()
  File "/opt/code/localstack/localstack/services/infra.py", line 378, in start_infra
    raise e
  File "/opt/code/localstack/localstack/services/infra.py", line 371, in start_infra
    do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/plugins.py", line 172, in do_start_infra
    return do_start_infra_orig(asynchronous,apis,is_in_docker,*args,**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py", line 61, in do_start_infra
    return do_start_infra_orig(asynchronous,*args,**kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 433, in do_start_infra
    thread = start_api_services()
  File "/opt/code/localstack/localstack/utils/analytics/profiler.py", line 156, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 421, in start_api_services
    t1 = plugin.start(asynchronous=True)
  File "/opt/code/localstack/localstack/services/plugins.py", line 40, in start
    return self.start_function(**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cloudfront/cloudfront_starter.py", line 9, in start_cloudfront
TypeError: start_local_api() missing 1 required positional argument: 'api'

ERROR: start_local_api() missing 1 required positional argument: 'api'
(. .venv/bin/activate; exec bin/localstack start --host)
make: *** [Makefile:47: infra] Error 1
LocalStack version: 0.11.5
Starting local dev environment. CTRL-C to quit.
2020-09-16T10:26:15:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext": <function register_localstack_commands at 0x7f8681220430>
2020-09-16T10:26:15:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7f8682aeb160>
Waiting for all LocalStack services to be ready
2020-09-16 10:26:16,880 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-09-16T10:26:20:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
Waiting for all LocalStack services to be ready
2020-09-16T10:26:24:INFO:localstack.utils.analytics.profiler: Execution of "load_plugin_from_path" took 8864.413022994995ms
2020-09-16T10:26:24:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f8682aeae50>
2020-09-16T10:26:24:DEBUG:bootstrap.py: Plugin loading took 9.084558010101318 sec
2020-09-16T10:26:24:INFO:localstack.utils.analytics.profiler: Execution of "load_plugins" took 9084.67411994934ms
2020-09-16T10:26:24:INFO:localstack_ext.utils.aws.metadata_service: Starting AWS instance metadata service on port 80
Starting mock Cognito Identity Provider (IdP) service on http port 443 ...
2020-09-16T10:26:27:INFO:botocore.credentials: Found credentials in environment variables.
2020-09-16T10:26:27:INFO:localstack.utils.analytics.profiler: Execution of "prepare_environment" took 2068.398952484131ms
2020-09-16T10:26:27:INFO:localstack.multiserver: Starting multi API server process on port 51833
Running on 0.0.0.0:51833 over http (CTRL + C to quit)
Starting mock Cognito Identity service on http port 443 ...
Error starting infrastructure: start_local_api() missing 1 required positional argument: 'api' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 371, in start_infra
    do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/plugins.py", line 172, in do_start_infra
    return do_start_infra_orig(asynchronous,apis,is_in_docker,*args,**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py", line 61, in do_start_infra
    return do_start_infra_orig(asynchronous,*args,**kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 433, in do_start_infra
    thread = start_api_services()
  File "/opt/code/localstack/localstack/utils/analytics/profiler.py", line 156, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 421, in start_api_services
    t1 = plugin.start(asynchronous=True)
  File "/opt/code/localstack/localstack/services/plugins.py", line 40, in start
    return self.start_function(**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cloudfront/cloudfront_starter.py", line 9, in start_cloudfront
TypeError: start_local_api() missing 1 required positional argument: 'api'
```

# Steps to reproduce

I simply did `docker-compose up -d`

## Command used to start LocalStack

`docker-compose up -d` where `docker-compose.yml` looks like 
```
version: '2.1'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=xxxxxxxxx
      - SERVICES=edge,lambda,s3,cognito,cloudformation,dynamodb,dynamodbstreams,apigateway,apigatewayv2,es,ses,route53,cloudwatch,cloudwatchlogs,cognitoidentity,cognitoidentityprovider,cloudfront
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DNS_ADDRESS=127.0.0.53
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

**Comment by whummer** [comment]
Thanks for reporting @piekarskid . This should be fixed in the `latest` version. Can you please pull the Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
