### ISSUE TITLE
Connection Error 

### ISSUE THREAD

**Issue by yashwanth2804** [localstack/localstack#300]
I ran the pip install --user localstack and npm but got this problem,is there any way out .

Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock CloudWatch (http port 4582)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudFormation (http port 4581)...
Starting mock DynamoDB (http port 4569)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
2017-09-04T19:30:31:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e60045fd0>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/home/exa6vm/.local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 185, in forward
    headers=forward_headers)
  File "/home/exa6vm/.local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/exa6vm/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/exa6vm/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/exa6vm/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/exa6vm/.local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9e60045fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by whummer** [comment]
Thanks for reporting @yashwanth2804 , can you please post the output with debug info enabled:
```
localstack --debug start
```
Thanks

**Comment by yashwanth2804** [comment]
**localstack --debug start**
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
2017-09-04T19:52:34:ERROR:localstack.services.generic_proxy: Exception running proxy on port 4567: Traceback (most recent call last):
  File "/home/exa6vm/.local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 243, in run_cmd
    self.httpd = ThreadedHTTPServer((self.listen_host, self.port), GenericProxyHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Starting mock CloudWatch (http port 4582)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
2017-09-04T19:52:34:ERROR:localstack.services.generic_proxy: Exception running proxy on port 4568: Traceback (most recent call last):
  File "/home/exa6vm/.local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 243, in run_cmd
    self.httpd = ThreadedHTTPServer((self.listen_host, self.port), GenericProxyHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudFormation (http port 4581)...
2017-09-04T19:52:34:ERROR:localstack.services.generic_proxy: Exception running proxy on port 4572: Traceback (most recent call last):
  File "/home/exa6vm/.local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 243, in run_cmd
    self.httpd = ThreadedHTTPServer((self.listen_host, self.port), GenericProxyHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-09-04T19:52:34:ERROR:localstack.services.generic_proxy: Exception running proxy on port 4581: Traceback (most recent call last):
  File "/home/exa6vm/.local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 243, in run_cmd
    self.httpd = ThreadedHTTPServer((self.listen_host, self.port), GenericProxyHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Starting mock DynamoDB (http port 4569)...
2017-09-04T19:52:34:ERROR:localstack.services.generic_proxy: Exception running proxy on port 4569: Traceback (most recent call last):
  File "/home/exa6vm/.local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 243, in run_cmd
    self.httpd = ThreadedHTTPServer((self.listen_host, self.port), GenericProxyHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Starting mock SQS (http port 4576)...
2017-09-04T19:52:34:ERROR:localstack.services.generic_proxy: Exception running proxy on port 4576: Traceback (most recent call last):
  File "/home/exa6vm/.local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 243, in run_cmd
    self.httpd = ThreadedHTTPServer((self.listen_host, self.port), GenericProxyHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Error: Unable to access jarfile DynamoDBLocal.jar
Starting local Elasticsearch (http port 4571)...
2017-09-04T19:52:34:ERROR:localstack.services.generic_proxy: Exception running proxy on port 4571: Traceback (most recent call last):
  File "/home/exa6vm/.local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 243, in run_cmd
    self.httpd = ThreadedHTTPServer((self.listen_host, self.port), GenericProxyHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Starting mock SNS (http port 4575)...
2017-09-04T19:52:34:ERROR:localstack.services.generic_proxy: Exception running proxy on port 4575: Traceback (most recent call last):
  File "/home/exa6vm/.local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 243, in run_cmd
    self.httpd = ThreadedHTTPServer((self.listen_host, self.port), GenericProxyHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
module.js:491
throw err;
^

Error: Cannot find module 'core-util-is'
at Function.Module._resolveFilename (module.js:489:15)
at Function.Module._load (module.js:439:25)
at Module.require (module.js:517:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/home/exa6vm/.local/lib/python2.7/site-packages/localstack/node_modules/readable-stream/lib/_stream_readable.js:46:12)
at Module._compile (module.js:573:30)
at Object.Module._extensions..js (module.js:584:10)
at Module.load (module.js:507:32)
at tryModuleLoad (module.js:470:12)
at Function.Module._load (module.js:462:3)
Traceback (most recent call last):
Traceback (most recent call last):
File "/home/exa6vm/.local/bin/moto_server", line 11, in <module>
sys.exit(main())
File "/home/exa6vm/.local/lib/python2.7/site-packages/moto/server.py", line 196, in main
ssl_context='adhoc' if args.ssl else None)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 739, in run_simple
inner()
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 699, in inner
fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 587, in make_server
passthrough_errors, ssl_context, fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 504, in __init__
HTTPServer.__init__(self, (host, int(port)), handler)
File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
self.server_bind()
File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
SocketServer.TCPServer.server_bind(self)
File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
self.socket.bind(self.server_address)
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
File "/home/exa6vm/.local/bin/moto_server", line 11, in <module>
sys.exit(main())
File "/home/exa6vm/.local/lib/python2.7/site-packages/moto/server.py", line 196, in main
ssl_context='adhoc' if args.ssl else None)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 739, in run_simple
inner()
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 699, in inner
fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 587, in make_server
passthrough_errors, ssl_context, fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 504, in __init__
HTTPServer.__init__(self, (host, int(port)), handler)
File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
self.server_bind()
File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
SocketServer.TCPServer.server_bind(self)
File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
self.socket.bind(self.server_address)
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
Traceback (most recent call last):
File "/home/exa6vm/.local/bin/moto_server", line 11, in <module>
sys.exit(main())
File "/home/exa6vm/.local/lib/python2.7/site-packages/moto/server.py", line 196, in main
ssl_context='adhoc' if args.ssl else None)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 739, in run_simple
inner()
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 699, in inner
fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 587, in make_server
passthrough_errors, ssl_context, fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 504, in __init__
HTTPServer.__init__(self, (host, int(port)), handler)
File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
self.server_bind()
File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
SocketServer.TCPServer.server_bind(self)
File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
self.socket.bind(self.server_address)
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
File "/home/exa6vm/.local/bin/moto_server", line 11, in <module>
sys.exit(main())
File "/home/exa6vm/.local/lib/python2.7/site-packages/moto/server.py", line 196, in main
ssl_context='adhoc' if args.ssl else None)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 739, in run_simple
inner()
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 699, in inner
fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 587, in make_server
passthrough_errors, ssl_context, fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 504, in __init__
HTTPServer.__init__(self, (host, int(port)), handler)
File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
self.server_bind()
File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
SocketServer.TCPServer.server_bind(self)
File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
self.socket.bind(self.server_address)
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
File "/home/exa6vm/.local/bin/moto_server", line 11, in <module>
sys.exit(main())
File "/home/exa6vm/.local/lib/python2.7/site-packages/moto/server.py", line 196, in main
ssl_context='adhoc' if args.ssl else None)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 739, in run_simple
inner()
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 699, in inner
fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 587, in make_server
passthrough_errors, ssl_context, fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 504, in __init__
HTTPServer.__init__(self, (host, int(port)), handler)
File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
self.server_bind()
File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
SocketServer.TCPServer.server_bind(self)
File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
self.socket.bind(self.server_address)
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
File "/home/exa6vm/.local/bin/moto_server", line 11, in <module>
sys.exit(main())
File "/home/exa6vm/.local/lib/python2.7/site-packages/moto/server.py", line 196, in main
ssl_context='adhoc' if args.ssl else None)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 739, in run_simple
inner()
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 699, in inner
fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 587, in make_server
passthrough_errors, ssl_context, fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 504, in __init__
HTTPServer.__init__(self, (host, int(port)), handler)
File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
self.server_bind()
File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
SocketServer.TCPServer.server_bind(self)
File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
self.socket.bind(self.server_address)
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
File "/home/exa6vm/.local/bin/moto_server", line 11, in <module>
sys.exit(main())
File "/home/exa6vm/.local/lib/python2.7/site-packages/moto/server.py", line 196, in main
ssl_context='adhoc' if args.ssl else None)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 739, in run_simple
inner()
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 699, in inner
fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 587, in make_server
passthrough_errors, ssl_context, fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 504, in __init__
HTTPServer.__init__(self, (host, int(port)), handler)
File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
self.server_bind()
File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
SocketServer.TCPServer.server_bind(self)
File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
self.socket.bind(self.server_address)
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
File "/home/exa6vm/.local/bin/moto_server", line 11, in <module>
sys.exit(main())
File "/home/exa6vm/.local/lib/python2.7/site-packages/moto/server.py", line 196, in main
ssl_context='adhoc' if args.ssl else None)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 739, in run_simple
inner()
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 699, in inner
fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 587, in make_server
passthrough_errors, ssl_context, fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 504, in __init__
HTTPServer.__init__(self, (host, int(port)), handler)
File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
self.server_bind()
File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
SocketServer.TCPServer.server_bind(self)
File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
self.socket.bind(self.server_address)
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
File "/home/exa6vm/.local/bin/moto_server", line 11, in <module>
sys.exit(main())
File "/home/exa6vm/.local/lib/python2.7/site-packages/moto/server.py", line 196, in main
ssl_context='adhoc' if args.ssl else None)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 739, in run_simple
inner()
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 699, in inner
fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 587, in make_server
passthrough_errors, ssl_context, fd=fd)
File "/home/exa6vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 504, in __init__
HTTPServer.__init__(self, (host, int(port)), handler)
File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
self.server_bind()
File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
SocketServer.TCPServer.server_bind(self)
File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
self.socket.bind(self.server_address)
File "/usr/lib/python2.7/socket.py", line 228, in meth
return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
[2017-09-04T19:52:41,886][INFO ][o.e.n.Node               ] [] initializing ...
[2017-09-04T19:52:42,094][INFO ][o.e.e.NodeEnvironment    ] [YHXgrQj] using [1] data paths, mounts [[/ (/dev/sda1)]], net usable_space [902.1mb], net total_space [5.7gb], spins? [possibly], types [ext4]
[2017-09-04T19:52:42,095][INFO ][o.e.e.NodeEnvironment    ] [YHXgrQj] heap size [491.6mb], compressed ordinary object pointers [true]
[2017-09-04T19:52:42,097][INFO ][o.e.n.Node               ] node name [YHXgrQj] derived from node ID [YHXgrQjsSDOYywk5MDtsLw]; set [node.name] to override
[2017-09-04T19:52:42,098][INFO ][o.e.n.Node               ] version[5.3.0], pid[23472], build[3adb13b/2017-03-23T03:31:50.652Z], OS[Linux/4.10.0-28-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b11]
[2017-09-04T19:52:43,532][INFO ][o.e.p.PluginsService     ] [YHXgrQj] loaded module [aggs-matrix-stats]
[2017-09-04T19:52:43,536][INFO ][o.e.p.PluginsService     ] [YHXgrQj] loaded module [ingest-common]
[2017-09-04T19:52:43,538][INFO ][o.e.p.PluginsService     ] [YHXgrQj] loaded module [lang-expression]
[2017-09-04T19:52:43,539][INFO ][o.e.p.PluginsService     ] [YHXgrQj] loaded module [lang-groovy]
[2017-09-04T19:52:43,539][INFO ][o.e.p.PluginsService     ] [YHXgrQj] loaded module [lang-mustache]
[2017-09-04T19:52:43,539][INFO ][o.e.p.PluginsService     ] [YHXgrQj] loaded module [lang-painless]
[2017-09-04T19:52:43,539][INFO ][o.e.p.PluginsService     ] [YHXgrQj] loaded module [percolator]
[2017-09-04T19:52:43,540][INFO ][o.e.p.PluginsService     ] [YHXgrQj] loaded module [reindex]
[2017-09-04T19:52:43,540][INFO ][o.e.p.PluginsService     ] [YHXgrQj] loaded module [transport-netty3]
[2017-09-04T19:52:43,540][INFO ][o.e.p.PluginsService     ] [YHXgrQj] loaded module [transport-netty4]
[2017-09-04T19:52:43,541][INFO ][o.e.p.PluginsService     ] [YHXgrQj] no plugins loaded
[2017-09-04T19:52:46,779][INFO ][o.e.n.Node               ] initialized
[2017-09-04T19:52:46,779][INFO ][o.e.n.Node               ] [YHXgrQj] starting ...
[2017-09-04T19:52:47,082][INFO ][o.e.t.TransportService   ] [YHXgrQj] publish_address {127.0.0.1:9301}, bound_addresses {[::1]:9301}, {127.0.0.1:9301}
[2017-09-04T19:52:47,105][WARN ][o.e.b.BootstrapChecks    ] [YHXgrQj] initial heap size [209715200] not equal to maximum heap size [524288000]; this can cause resize pauses and prevents mlockall from locking the entire heap
[2017-09-04T19:52:47,106][WARN ][o.e.b.BootstrapChecks    ] [YHXgrQj] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2017-09-04T19:52:50,411][INFO ][o.e.c.s.ClusterService   ] [YHXgrQj] detected_master {dw9mwRC}{dw9mwRCsSNK7JMNkE9gaGQ}{JAcTQiYeSvCcyTpnI6xo_g}{127.0.0.1}{127.0.0.1:9300}, added {{dw9mwRC}{dw9mwRCsSNK7JMNkE9gaGQ}{JAcTQiYeSvCcyTpnI6xo_g}{127.0.0.1}{127.0.0.1:9300},}, reason: zen-disco-receive(from master [master {dw9mwRC}{dw9mwRCsSNK7JMNkE9gaGQ}{JAcTQiYeSvCcyTpnI6xo_g}{127.0.0.1}{127.0.0.1:9300} committed version [3]])
[2017-09-04T19:52:50,568][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: BindHttpException[Failed to bind to [4560]]; nested: BindException[Address already in use];
at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.0.jar:5.3.0]
at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.0.jar:5.3.0]
at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.0.jar:5.3.0]
at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.0.jar:5.3.0]
at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.0.jar:5.3.0]
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.0.jar:5.3.0]
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.0.jar:5.3.0]
Caused by: org.elasticsearch.http.BindHttpException: Failed to bind to [4560]
at org.elasticsearch.http.netty4.Netty4HttpServerTransport.bindAddress(Netty4HttpServerTransport.java:451) ~[?:?]
at org.elasticsearch.http.netty4.Netty4HttpServerTransport.createBoundHttpAddress(Netty4HttpServerTransport.java:352) ~[?:?]
at org.elasticsearch.http.netty4.Netty4HttpServerTransport.doStart(Netty4HttpServerTransport.java:329) ~[?:?]
at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:69) ~[elasticsearch-5.3.0.jar:5.3.0]
at org.elasticsearch.node.Node.start(Node.java:661) ~[elasticsearch-5.3.0.jar:5.3.0]
at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:287) ~[elasticsearch-5.3.0.jar:5.3.0]
at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:370) ~[elasticsearch-5.3.0.jar:5.3.0]
at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.0.jar:5.3.0]
... 6 more
Caused by: java.net.BindException: Address already in use
at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
at sun.nio.ch.Net.bind(Net.java:433) ~[?:?]
at sun.nio.ch.Net.bind(Net.java:425) ~[?:?]
at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:?]
at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:127) ~[?:?]
at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554) ~[?:?]
at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:502) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:487) ~[?:?]
at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980) ~[?:?]
at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250) ~[?:?]
at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:363) ~[?:?]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[?:?]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[?:?]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445) ~[?:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[?:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[2017-09-04T19:52:50,598][INFO ][o.e.n.Node               ] [YHXgrQj] stopping ...
[2017-09-04T19:52:50,688][INFO ][o.e.n.Node               ] [YHXgrQj] stopped
[2017-09-04T19:52:50,689][INFO ][o.e.n.Node               ] [YHXgrQj] closing ...
[2017-09-04T19:52:50,751][INFO ][o.e.n.Node               ] [YHXgrQj] closed

**Comment by whummer** [comment]
Have you been able to get it working? The `Address already in use` errors look like LocalStack hasn't been terminated properly. Can you make sure that all processes are killed by checking `ps aux | grep localstack`.

For the other error (`Cannot find module 'core-util-is'`), it looks like one of the npm packages has not been installed correctly. Can you give this a try:
```
rm -rf /home/exa6vm/.local/lib/python2.7/site-packages/localstack/infra
localstack --debug start
```

**Comment by whummer** [comment]
Closing this issue as outdated - for housekeeping reasons. Assuming that this has been fixed in the meantime.
