### ISSUE TITLE
Cognito initiate_auth throws 500

### ISSUE THREAD

**Issue by limenutt** [localstack/localstack#3010]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
In Localstack Docker image **0.11.5**
1) sign up a user with Cognito
2) sign in with the same user

## Expected behavior

The authentication is successful if the username/password are correct
...

## Actual behavior
500 error is thrown by the Cognito API
The following error is seen in the container logs
```
2020-09-19T10:03:14:INFO:localstack_ext.services.cognito.cognito_helpers: Error in Cognito action "InitiateAuth": '__salt__' Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_listener.py", line 106, in forward_request
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_helpers.py", line 114, in initiate_auth
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_helpers.py", line 189, in initiate_auth_srp
KeyError: '__salt__'
```
...

# Steps to reproduce

## Command used to start LocalStack
docker-compose up
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by Gidmark-wowgroup** [comment]
Getting the same error. I can log in with the user using USER_PASSWORD_AUTH

**Comment by quincyreid** [comment]
I'm getting this same error. I also got the same error when trying USER_PASSWORD_AUTH

**Comment by whummer** [comment]
Thanks again for reporting @quincyreid @Gidmark-wowgroup @limenutt , and apologies for the delay. This issue should be fixed in the `latest` version - can you please pull the latest Docker image and give it another try? Please let us know if the problem persists. Thanks for your support in resolving this.
