### ISSUE TITLE
SQS does not start from python module

### ISSUE THREAD

**Issue by manjula-chikkanagappa** [localstack/localstack#3015]
# Type of request: This is a ...

[yes] bug report
[ ] feature request

# Detailed description

SQS does not start from python module. The program hangs.

Below are the errors
```
Traceback (most recent call last):
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/localstack/services/infra.py", line 384, in check_infra
    raise e
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/localstack/services/infra.py", line 381, in check_infra
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/localstack/services/infra.py", line 69, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/localstack/services/sqs/sqs_starter.py", line 31, in check_sqs
    assert out.get('ResponseMetadata', {}).get('HTTPStatusCode') == 200
AttributeError: 'NoneType' object has no attribute 'get'

```

```
unable to create context store: $HOME is not defined
Starting edge router (https port 4566)...
Running on 0.0.0.0:4566 over https (CTRL + C to quit)
Starting mock SNS service on http ports 4566 (recommended) and 4566 (deprecated)...
Running on 0.0.0.0:57888 over http (CTRL + C to quit)
ASGI Framework Lifespan error, shutdown without Lifespan support
Traceback (most recent call last):
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/localstack/utils/server/http2_server.py", line 132, in run_app_sync
    return loop.run_until_complete(serve(app, config, **run_kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/hypercorn/asyncio/__init__.py", line 39, in serve
    await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/hypercorn/asyncio/run.py", line 69, in worker_serve
    sockets = config.create_sockets()
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/hypercorn/config.py", line 166, in create_sockets
    insecure_sockets = self._create_sockets(self.bind)
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/hypercorn/config.py", line 214, in _create_sockets
    sock.bind(binding)
OSError: [Errno 48] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/hypercorn/asyncio/lifespan.py", line 30, in handle_lifespan
    await invoke_asgi(self.app, scope, self.asgi_receive, self.asgi_send)
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/hypercorn/utils.py", line 219, in invoke_asgi
    await app(scope, receive, send)
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/quart/app.py", line 2068, in __call__
    await self.asgi_app(scope, receive, send)
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/quart/app.py", line 2091, in asgi_app
    await asgi_handler(receive, send)
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/quart/asgi.py", line 209, in __call__
    event = await receive()
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/hypercorn/asyncio/lifespan.py", line 68, in asgi_receive
    return await self.app_queue.get()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/queues.py", line 159, in get
    await getter
concurrent.futures._base.CancelledError
Starting mock SQS service on http ports 4566 (recommended) and 4566 (deprecated)...
ASGI Framework Lifespan error, shutdown without Lifespan support
Traceback (most recent call last):
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/localstack/utils/server/http2_server.py", line 132, in run_app_sync
    return loop.run_until_complete(serve(app, config, **run_kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/hypercorn/asyncio/__init__.py", line 39, in serve
    await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/hypercorn/asyncio/run.py", line 69, in worker_serve
    sockets = config.create_sockets()
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/hypercorn/config.py", line 166, in create_sockets
    insecure_sockets = self._create_sockets(self.bind)
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/hypercorn/config.py", line 214, in _create_sockets
    sock.bind(binding)
OSError: [Errno 48] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/hypercorn/asyncio/lifespan.py", line 30, in handle_lifespan
    await invoke_asgi(self.app, scope, self.asgi_receive, self.asgi_send)
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/hypercorn/utils.py", line 219, in invoke_asgi
    await app(scope, receive, send)
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/quart/app.py", line 2068, in __call__
    await self.asgi_app(scope, receive, send)
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/quart/app.py", line 2091, in asgi_app
    await asgi_handler(receive, send)
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/quart/asgi.py", line 209, in __call__
    event = await receive()
  File "/Users/workdir/.tox/pytest/lib/python3.7/site-packages/hypercorn/asyncio/lifespan.py", line 68, in asgi_receive
    return await self.app_queue.get()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/queues.py", line 159, in get
    await getter
concurrent.futures._base.CancelledError
```

## Expected behavior
localstack start SQS service successfully from python module
...

## Actual behavior
localstack start SQS service fails from python module

# Steps to reproduce

## Command used to start LocalStack
localstack starts successfully from command line. But fails when doing the same from python module. This is happening with new release of localstack on Sep 16th 2020
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
from localstack.services import infra
infra.start_infra(asynchronous=True, apis=services_to_start)
```
...

**Comment by whummer** [comment]
Thanks for reporting @manjula-chikkanagappa . Please note that starting LocalStack outside of Docker (directly from Python) is not supported anymore. We had to drop the support, as it became too complex and error prone to maintain the various different python versions, operating systems, etc.

The recommended (and only supported) way of starting LocalStack these days is using Docker (the default when starting via the command line). We'll be very happy to accept a pull request, though, if you can manage to contribute a fix for this issue. Thanks for your support.
