### ISSUE TITLE
Docker container fails to start WebUI

### ISSUE THREAD

**Issue by bravecobra** [localstack/localstack#3046]
# Type of request: This is a bug report

[x ] bug report
[ ] feature request

# Detailed description

Starting the docker container version 0.11.5 from docker-compose fails to start the web-ui since the `/root/.npm/` folder in read-only. Version 0.11.5
```
services:
  localstack:
    image: localstack/localstack:0.11.5
    container_name: localstack
    # user: root # -> this does not help either
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=1
      - DATA_DIR=${DATA_DIR-/tmp/localstack/data}
      - PORT_WEB_UI=8080
      - START_WEB=1
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=http://localhost:2375
    volumes:
      - "${TMPDIR:-./.localstack}:/tmp/localstack"
```

Log output :

```
Starting local dev environment. CTRL-C to quit.

2020-09-28T08:02:00:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext": <function register_localstack_commands at 0x7f14b20f1ca0>
2020-09-28T08:02:00:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7f14b2d209d0>
Initializing installation of Web application (this could take a long time, please be patient)
2020-09-28T08:02:00:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f14b2d20700>
Waiting for all LocalStack services to be ready
ERROR: 'cd "/opt/code/localstack/localstack/dashboard/web"; npm install': exit code 243; output: b'/bin/sh: cd: line 1: can\'t cd to /opt/code/localstack/localstack/dashboard/web: No such file or directory\nnpm WARN locking Error: EACCES: permission denied, open \'/root/.npm/_locks/staging-9bb89b2aa202b609.lock\'\nnpm WARN locking /root/.npm/_locks/staging-9bb89b2aa202b609.lock failed [Error: EACCES: permission denied, open \'/root/.npm/_locks/staging-9bb89b2aa202b609.lock\'] {\nnpm WARN locking errno: -13,\nnpm WARN locking code: \'EACCES\',\nnpm WARN locking syscall: \'open\',\nnpm WARN locking path: \'/root/.npm/_locks/staging-9bb89b2aa202b609.lock\'\nnpm WARN locking }\nnpm WARN enoent ENOENT: no such file or directory, open \'/opt/code/localstack/package.json\'\nnpm WARN localstack No description\nnpm WARN localstack No repository field.\nnpm WARN localstack No README data\nnpm WARN localstack No license field.\n\nnpm ERR! code EACCES\nnpm ERR! syscall open\nnpm ERR! path /root/.npm/_locks/staging-9bb89b2aa202b609.lock\nnpm ERR! errno -13\nnpm ERR! \nnpm ERR! Your cache folder contains root-owned files, due to a bug in\nnpm ERR! previous versions of npm which has since been addressed.\nnpm ERR! \nnpm ERR! To permanently fix this problem, please run:\nnpm ERR! sudo chown -R 1001:1001 "/root/.npm"\n'
Traceback (most recent call last):
File "/opt/code/localstack/localstack/utils/cli.py", line 157, in main
subcommand['function'](argv, args)
File "/opt/code/localstack/localstack/utils/cli.py", line 82, in cmd_web
localstack.dashboard.api.serve(port)
File "/opt/code/localstack/localstack/dashboard/api.py", line 134, in serve
ensure_webapp_installed()
File "/opt/code/localstack/localstack/dashboard/api.py", line 129, in ensure_webapp_installed
common.run('cd "%s"; npm install' % web_dir)
File "/opt/code/localstack/localstack/utils/common.py", line 1114, in run
return do_run(cmd)
File "/opt/code/localstack/localstack/utils/common.py", line 1111, in do_run
return bootstrap.run(cmd, **kwargs)
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 595, in run
raise e
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 555, in run
output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/lib/python3.8/subprocess.py", line 512, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd "/opt/code/localstack/localstack/dashboard/web"; npm install' returned non-zero exit status 243.
ERROR: Command 'cd "/opt/code/localstack/localstack/dashboard/web"; npm install' returned non-zero exit status 243.
make: *** [Makefile:109: web] Error 1
2020-09-28 08:02:06,583 INFO exited: dashboard (exit status 2; not expected)
Waiting for all LocalStack services to be ready
```
...

## Expected behavior

A working WebUI on port 8080

## Actual behavior

docker container on 8080 sends empty response.

# Steps to reproduce

## Command used to start LocalStack

See above

**Comment by nolazybits** [comment]
seeing the same problem...

**Comment by ashlux** [comment]
You need to use image `localstack/localstack-full` instead.

FYI: The web dashboard is deprecated: https://github.com/localstack/localstack#web-dashboard-deprecated

**Comment by whummer** [comment]
Thanks for reporting @bravecobra @nolazybits - does the fix/workaround provided by @ashlux work for you? Please note that the Web dashboard is deprecated and no longer developed (it uses very outdated libraries and the code is not really maintainable) - if you'd like to pick up the task of revamping/modernizing the Web UI code, that would be much appreciated. Thanks!

**Comment by bravecobra** [comment]
No, even the full version is broken at the moment.

**Comment by ismet55555** [comment]
Same here, `localstack/localstack-full` doesn't show up anything either on port `8080`. 
The site cannot be reached on `localhost:8080`

**Comment by Hector1567XD** [comment]
Any news on this matter?

localstack/localstack-full is also not showing me anything on port 8080 or any other port right now.

**Comment by TataSary** [comment]
I run

**Comment by jimmykirk** [comment]
> Any news on this matter?
> 
> localstack/localstack-full is also not showing me anything on port 8080 or any other port right now.

Last I saw was them removing it from the docs and recommending a $30/month service. Honestly, I can test all my stuff on AWS' free tier for less than $30 and use their UI. Sad really.

**Comment by mojtabaPourmirzaei** [comment]
hi.
use **localstack/localstack-full:0.11.6** image instead

**Comment by esimonov** [comment]
I ended up using [awslocal CLI](https://github.com/localstack/awscli-local).
