### ISSUE TITLE
Cannot use KMS GenerateDataKeyPair or GenerateDataKeyPairWithoutPlaintext command with localstack & testcontainers

### ISSUE THREAD

**Issue by gaggarwal21** [localstack/localstack#3056]
# Type of request: This is a ...
[X] bug report
[ ] feature request

# Detailed description
I am using localstack & testcontainers for mocking KMS locally to test my APIs and I need to generate data key "pairs". When calling generateDataKeyPair() or GenerateDataKeyPairWithoutPlaintext() API, I get the following exception. I am not sure if my code is incorrect or if it is not supported currently.
Version I am using: 
"localstack/localstack:0.11.0"

gradle file:
testImplementation("org.testcontainers:localstack:1.15.+")
// for aws KMS
implementation("com.amazonaws:aws-java-sdk-kms:1.11.869")

FYI - I am using Kotlin for this. 
...

## Expected behavior
I should be able to create a data key pair.
...

## Actual behavior
Getting the following exception when using these APIs:
com.amazonaws.services.kms.model.AWSKMSException: null (Service: AWSKMS; Status Code: 501; Error Code: null; Request ID: null; Proxy: null)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
    at com.amazonaws.services.kms.AWSKMSClient.doInvoke(AWSKMSClient.java:5863)
    at com.amazonaws.services.kms.AWSKMSClient.invoke(AWSKMSClient.java:5830)
    at com.amazonaws.services.kms.AWSKMSClient.invoke(AWSKMSClient.java:5819)
    at com.amazonaws.services.kms.AWSKMSClient.executeGenerateDataKeyPair(AWSKMSClient.java:3047)
    at com.amazonaws.services.kms.AWSKMSClient.generateDataKeyPair(AWSKMSClient.java:3018)
...

# Steps to reproduce
## Command used to start LocalStack
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
LocalStackContainer = LocalStackContainer(DockerImageName.parse("localstack/localstack:0.11.0"))
            .withServices(KMS)
            .also { it.start() }

val awskms: AWSKMS = AWSKMSClientBuilder.standard()
                .withEndpointConfiguration(localstack.getEndpointConfiguration(KMS))
                .withCredentials(localstack.getDefaultCredentialsProvider())
                .build()
val desc: String = String.format("AWS CMK Description")
val req: CreateKeyRequest = CreateKeyRequest().withDescription(desc)
val key: CreateKeyResult = awskms.createKey(req)
val request : GenerateDataKeyPairRequest = GenerateDataKeyPairRequest().withKeyId(key.getKeyMetadata().getArn()).withKeyPairSpec("RSA_2048")
val dataKeyResult: GenerateDataKeyPairResult = awskms.generateDataKeyPair(request)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-275) by [Unito](https://www.unito.io/learn-more)

**Comment by nsmithuk** [comment]
I suspect the issue is because local-kms doesn't yet support RSA keys with a usage set to ENCRYPT_DECRYPT, which is what GenerateDataKeyPair or GenerateDataKeyPairWithoutPlaintext depend on.

I've started work on it. I'll drop a note here once it's done. Should be some time in the next few weeks.

**Comment by nsmithuk** [comment]
@gaggarwal21 GenerateDataKeyPair and GenerateDataKeyPairWithoutPlaintext have been added in the latest version of Local KMS, and should be available in LocalStack in any build done as of now.

Please let me know if you have any issues with the new endpoints.

**Comment by whummer** [comment]
Awesome, thanks for adding this functionality @nsmithuk ! 🚀
