### ISSUE TITLE
Unable to trigger LAMBDA with ECONNREFUSED on edge port 4566

### ISSUE THREAD

**Issue by leungas** [localstack/localstack#3068]
# Type of request: This is a ...
[X] bug report
[ ] feature request

# Detailed description
When upgrade to 0.11.6, client cannot connect to localstack via edge port 4566. Requests came back as ECONNREFUSED. 

```
      errorMessage: 'Lambda process returned error status code: 1. Result: {"errorMessage":"2020-10-04T03:40:37.328Z 0bbc9c6c-2a40-1ba1-4133-a3e711cc82dd Task timed out after 6.00 seconds"}. Output:\n' +
        '\u001b[32mSTART RequestId: 0bbc9c6c-2a40-1ba1-4133-a3e711cc82dd Version: $LATEST\u001b[0m\n' +
        '2020-10-04T03:40:37.323Z\t0bbc9c6c-2a40-1ba1-4133-a3e711cc82dd\tINFO\tError: connect ECONNREFUSED 127.0.0.1:4566\n' +
        '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {\n' +
        "  errno: 'ECONNREFUSED',\n" +
        "  code: 'NetworkingError',\n" +
        "  syscall: 'connect',\n" +
        "  address: '127.0.0.1',\n" +
        '  port: 4566,\n' +
        "  region: 'us-east-1',\n" +
        "  hostname: 'localhost',\n" +
        '  retryable: true,\n' +
        '  time: 2020-10-04T03:40:37.318Z\n' +
        '} Error: connect ECONNREFUSED 127.0.0.1:4566\n' +
        '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)\n' +
        '\u001b[32mEND RequestId: 0bbc9c6c-2a40-1ba1-4133-a3e711cc82dd\u001b[0m\n' +
        '\u001b[32mREPORT RequestId: 0bbc9c6c-2a40-1ba1-4133-a3e711cc82dd\tInit Duration: 6000.00 ms\tDuration: 6000.00 ms\tBilled Duration: 6000 ms\tMemory Size: 1536 MB\tMax Memory Used: 60 MB\t\u001b[0m',
      errorType: 'Exception',
      stackTrace: [
        '  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 541, in run_lambda\n' +
          '    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,\n',
        '  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 169, in execute\n' +
          '    return do_execute()\n',
        '  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 161, in do_execute\n' +
          '    return _run(func_arn=func_arn)\n',
        '  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 146, in wrapped\n' +
          '    raise e\n',
        '  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 142, in wrapped\n' +
          '    result = func(*args, **kwargs)\n',
        '  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 154, in _run\n' +
          '    raise e\n',
        '  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 142, in _run\n' +
          '    result = self._execute(func_arn, func_details, event, context, version)\n',
        '  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 300, in _execute\n' +
          '    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)\n',
        '  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 206, in run_lambda_executor\n' +
          "    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\\n%s' %\n"
      ]
```

## Expected behavior
The lambda should execute as per prior to 0.11.6

## Actual behavior
# Steps to reproduce
1. Use docker-compose.yml

```
version: '3.3'

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack-full:latest
    ports:
      - "${EDGE_PORT-4566}:4566"
    environment:
      - SERVICES=${SERVICES:-}
      - LAMBDA_EXECUTOR=docker-reuse
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_REMOVE_CONTAINERS=false
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

1. Load CloudFormation onto Localstack (using serverless)

```
service:
  name: 'jizo-accts'

frameworkVersion:  '>=1.72.0'

plugins:
  - serverless-webpack  
  - serverless-dynamodb-local
  - serverless-offline-sqs
  - serverless-offline  
  - serverless-localstack

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
  serverless-offline-sqs:
    autoCreate: false
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:4576
    region: us-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false    
  serverless-offline:
    stage:
      -local
    lambdaPort: 4574
  dynamodb:
    stages:
      - local      
    start:
      port: 4569
      inMemory: true
      heapInitial: 128m
      heapMax: 1g
      migrate: true
  localstack:
    docker:
      sudo: false
    debug: true
    endpoints:
      S3: http://localhost:4566
      DynamoDB: http://localhost:4566
      CloudFormation: http://localhost:4566
      Elasticsearch: http://localhost:4566
      ES: http://localhost:4566
      SNS: http://localhost:4566
      SQS: http://localhost:4566
      Lambda: http://localhost:4566
      Kinesis: http://localhost:4566
    host: "http://localhost"
    lambda:
      mountCode: false
    stages:
      - dev

provider:
  name: 'aws'
  apiGateway: 
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    ML_EXT_LOOPBACK: 'NO'
    ML_EXT_DEBUG: 'YES'
    ML_EXT_SYSENV: ${opt:stage}
    ML_CLOUD_REGION: ${opt:region}       
  runtime: 'nodejs12.x'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sqs:ReceiveMessage'
        - 'sqs:DeleteMessage'
      Resource:
        - "arn:aws:sqs:${opt:region}:027377181697:${self:service}-${opt:stage}-RescopeQueue"
        - "arn:aws:sqs:${opt:region}:027377181697:${self:service}-${opt:stage}-UncopeQueue"
    - Effect: 'Allow'
      Action:
        - 'sqs:SendMessage'
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'dynamodb:DeleteItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
      Resource:
        - "arn:aws:dynamodb:${opt:region}:027377181697:table/jizo.${opt:stage}.accountsTable"
        - "arn:aws:dynamodb:${opt:region}:027377181697:table/jizo.${opt:stage}.identitiesTable"
        - "arn:aws:dynamodb:${opt:region}:027377181697:table/jizo.${opt:stage}.acctsAuditTrialTable"
        - "arn:aws:dynamodb:${opt:region}:027377181697:table/jizo.${opt:stage}.usersTable"
    - Effect: 'Allow'
      Action: 
        - 's3:GetObject'
      Resource:
        - "arn:aws:s3:::${self:service}.${opt:stage}.identity"
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
      Resource:
        - "arn:aws:sns:${opt:region}:027377181697:${self:service}-${opt:stage}-registerAccount"
        - "arn:aws:sns:${opt:region}:027377181697:${self:service}-${opt:stage}-unregisterAccount"
    - Effect: 'Allow'
      Action:
        - 'sns:Subscribe'
      Resource: '*'       
        
functions:
  identify: 
    handler: src/s3.identify
    description: "Trigger identity creation and validation when receiving files upload to bucket"
    events:
      - s3:
        bucket: "${self:service}.${opt:stage}.identity"
        event: s3:ObjectCreate:*
  router:
    handler: src/http.router
    description: 'primary REST related handlers for this service'
    events:
      - http:
          path: 'v1/{proxy+}'
          method: any
  userGet:
      handler: src/lambda.userGet
      description: 'provide sync call to get user data'
  rescope:
    handler: src/sqs.rescope
    description: "To handle rescoping account via the invoicing service"
    events:
      - sqs:
          arn: 
            Fn::GetAtt:
              - RescopeQueue
              - Arn
  unscope:
    handler: src/sqs.unscope
    description: "To handle unscoping account via the invoicing service"
    events:
      - sqs:
          arn: 
            Fn::GetAtt:
              - UnscopeQueue
              - Arn

resources:
  Resources:
    # s3 configuration
    identityBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "${self:service}.${opt:stage}.identity"

    # dynamodb configuration
    accountsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "jizo.${opt:stage}.accountsTable"
        AttributeDefinitions:
          - AttributeName: object_id
            AttributeType: S
        KeySchema:
          - AttributeName: object_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    identitiesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "jizo.${opt:stage}.identitiesTable"
        AttributeDefinitions:
          - AttributeName: object_id
            AttributeType: S
        KeySchema:
          - AttributeName: object_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    acctTrailTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "jizo.${opt:stage}.acctsAuditTrialTable"
        AttributeDefinitions:
          - AttributeName: object_id
            AttributeType: S
        KeySchema:
          - AttributeName: object_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1        
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "jizo.${opt:stage}.usersTable"
        AttributeDefinitions:
          - AttributeName: object_id
            AttributeType: S
        KeySchema:
          - AttributeName: object_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    # incoming SQS configuration      
    RescopeQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "${self:service}-${opt:stage}-RescopeQueue"
        VisibilityTimeout: 1080
        MessageRetentionPeriod: 2160
        RedrivePolicy:
          deadLetterTargetArn: 
            Fn::GetAtt:
              - RescopeBackupQueue
              - Arn
          maxReceiveCount: 3
    RescopeBackupQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "${self:service}-${opt:stage}-RescopeBackupQueue"
    UnscopeQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "${self:service}-${opt:stage}-UnscopeQueue"
        VisibilityTimeout: 1080
        MessageRetentionPeriod: 2160
        RedrivePolicy:
          deadLetterTargetArn: 
            Fn::GetAtt:
              - UnscopeBackupQueue
              - Arn
          maxReceiveCount: 3
    UnscopeBackupQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "${self:service}-${opt:stage}-UnscopeBackupQueue"

    # SNS Definitions
    registerAccountTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: "${self:service}-${opt:stage}-registerAccount"

    unregisterAccountTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: "${self:service}-${opt:stage}-unregisterAccount"
```

1. Check if functions are loaded onto localstack
`aws --endpoint-url http://localhost:4566 lambda list-functions`
1. Now try to trigger the funciton via js lambda client

## Command used to start LocalStack
`docker-compose up`

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-277) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @leungas . Can you please share the relevant part of your Lambda handler code? Looks like your Lambda is connecting to `127.0.0.1:4566` - can you please print the value of the `LOCALSTACK_HOSTNAME` environment variable in your handler (and try to use it as the endpoint, if you haven't done so already)? Thanks

**Comment by leungas** [comment]
@whummer here comes the data you requested:
```
Marks-MacBook-Pro-2:accounts leungas$ docker ps
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                                             NAMES
961d8b12c73a        lambci/lambda:nodejs12.x            "/bin/bash"              34 hours ago        Up 34 hours                                                           localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_jizo-accts-dev-userGet
d2495f690d7e        localstack/localstack-full:latest   "docker-entrypoint.sh"   34 hours ago        Up 34 hours         4567-4597/tcp, 0.0.0.0:4566->4566/tcp, 8080/tcp   localstack_main
Marks-MacBook-Pro-2:accounts leungas$ npm run test tests/integrated/private.test.ts 

> @jizo/accounts@1.0.0 test /Users/leungas/Documents/Development/Jizo/Services/accounts
> jest --ci --verbose "tests/integrated/private.test.ts"

  console.log
    LOCALSTACK_HOST: undefined

      at Object.<anonymous> (tests/integrated/private.test.ts:5:17)

  console.log
    Lambda Config: http://localhost:4566

      at new LambdaClient (node_modules/@leungas/aws-orm/src/clients/function.client.ts:37:17)

 FAIL  tests/integrated/private.test.ts (5.696 s)
  testing direct invoke lambda
    ✕ get user data from lambda (5041 ms)

  ● testing direct invoke lambda › get user data from lambda

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      2 | 
      3 | describe("testing direct invoke lambda", () => {
    > 4 |     test("get user data from lambda", async () => {
        |     ^
      5 |         console.log(`LOCALSTACK_HOST: ${JSON.stringify(process.env.LOCALSTACK_HOST)}`)
      6 |         Application.configure(require('../../src/configuration'))
      7 |         let client = new LambdaClient()

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tests/integrated/private.test.ts:4:5)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.734 s, estimated 7 s
Ran all test suites matching /tests\/integrated\/private.test.ts/i.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "{
      errorMessage: 'Lambda process returned error status code: 1. Result: {"errorMessage":"2020-10-05T13:18:40.182Z 7f039a64-284e-13de-1b60-8e5403e126ef Task timed out after 6.00 seconds"}. Output:\n' +
        '\u001b[32mSTART RequestId: 7f039a64-284e-13de-1b60-8e5403e126ef Version: $LATEST\u001b[0m\n' +
        '2020-10-05T13:18:40.178Z\t7f039a64-284e-13de-1b60-8e5403e126ef\tINFO\tError: connect ECONNREFUSED 127.0.0.1:4566\n' +
        '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {\n' +
        "  errno: 'ECONNREFUSED',\n" +
        "  code: 'NetworkingError',\n" +
        "  syscall: 'connect',\n" +
        "  address: '127.0.0.1',\n" +
        '  port: 4566,\n' +
        "  region: 'us-east-1',\n" +
        "  hostname: 'localhost',\n" +
        '  retryable: true,\n' +
        '  time: 2020-10-05T13:18:40.173Z\n' +
        '} Error: connect ECONNREFUSED 127.0.0.1:4566\n' +
        '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)\n' +
        '\u001b[32mEND RequestId: 7f039a64-284e-13de-1b60-8e5403e126ef\u001b[0m\n' +
        '\u001b[32mREPORT RequestId: 7f039a64-284e-13de-1b60-8e5403e126ef\tInit Duration: 6000.00 ms\tDuration: 6000.00 ms\tBilled Duration: 6000 ms\tMemory Size: 1536 MB\tMax Memory Used: 60 MB\t\u001b[0m',
      errorType: 'Exception',
      stackTrace: [
        '  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 541, in run_lambda\n' +
          '    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,\n',
        '  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 169, in execute\n' +
          '    return do_execute()\n',
        '  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 161, in do_execute\n' +
          '    return _run(func_arn=func_arn)\n',
        '  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 146, in wrapped\n' +
          '    raise e\n',
        '  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 142, in wrapped\n' +
          '    result = func(*args, **kwargs)\n',
        '  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 154, in _run\n' +
          '    raise e\n',
        '  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 142, in _run\n' +
          '    result = self._execute(func_arn, func_details, event, context, version)\n',
        '  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 300, in _execute\n' +
          '    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)\n',
        '  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 206, in run_lambda_executor\n' +
          "    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\\n%s' %\n"
      ]
    }".

       7 |         let client = new LambdaClient()
       8 |         let response = await client.run("userGet", {user: "66d956b0-8ffd-49ab-b023-10923e208d0d"})
    >  9 |         console.log(response)
         |                 ^
      10 |         expect(response).toBeDefined()
      11 |         expect(response).toBeInstanceOf(Object)
      12 |     })

      at CustomConsole.log (node_modules/@jest/console/build/CustomConsole.js:186:10)
      at Object.<anonymous> (tests/integrated/private.test.ts:9:17)
```

As for the handler setup, it reads from LOCALSTACK_HOST first and use localhost if is undefined:
```
        if (setup.endpoint !== undefined) {
            let port = setup.endpoint.port.lambda !== undefined ? setup.endpoint.port.lambda : 4566
            let host = process.env.LOCALSTACK_HOSTNAME !== undefined ? process.env.LOCALSTACK_HOSTNAME : "localhost"
            config.endpoint = `http://${host}:${port}`
        }

```

**Comment by leungas** [comment]
Hi @whummer,

Tried to use the localstack/locakstack:latest and the same issue is still there,  but there are a little more from CloudWatch this time round:

```
localstack_main | {"errorMessage":"2020-10-17T11:03:58.632Z 362148a5-88ec-1e25-3197-6ea9d94e38fd Task timed out after 6.00 seconds"}
localstack_main | > START RequestId: 362148a5-88ec-1e25-3197-6ea9d94e38fd Version: $LATEST
localstack_main | > 2020-10-17T11:03:58.629Z    362148a5-88ec-1e25-3197-6ea9d94e38fd    INFO    Error: connect ECONNREFUSED 127.0.0.1:4566
localstack_main | >     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
localstack_main | >   errno: 'ECONNREFUSED',
localstack_main | >   code: 'NetworkingError',
localstack_main | >   syscall: 'connect',
localstack_main | >   address: '127.0.0.1',
localstack_main | >   port: 4566,
localstack_main | >   region: 'us-east-1',
localstack_main | >   hostname: 'localhost',
localstack_main | >   retryable: true,
localstack_main | >   time: 2020-10-17T11:03:58.625Z
localstack_main | > } Error: connect ECONNREFUSED 127.0.0.1:4566
localstack_main | >     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
localstack_main | > END RequestId: 362148a5-88ec-1e25-3197-6ea9d94e38fd
localstack_main | > REPORT RequestId: 362148a5-88ec-1e25-3197-6ea9d94e38fd      Init Duration: 5375.37 ms       Duration: 6000.00 ms    Billed Duration: 6000 ms        Memory Size: 1536 MB    Max Memory Used: 59 MB
localstack_main | 2020-10-17T11:03:58:INFO:localstack.services.edge: Unable to find forwarding rule for host "0c72ce0c74ea:4566", path "/", target header "", auth header "", data "b''"
localstack_main | 2020-10-17T11:03:58:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:jizo-accts-dev-userGet: Lambda process returned error status code: 1. Result: {"errorMessage":"2020-10-17T11:03:58.632Z 362148a5-88ec-1e25-3197-6ea9d94e38fd Task timed out after 6.00 seconds"}. Output:
localstack_main | START RequestId: 362148a5-88ec-1e25-3197-6ea9d94e38fd Version: $LATEST
localstack_main | 2020-10-17T11:03:58.629Z      362148a5-88ec-1e25-3197-6ea9d94e38fd    INFO    Error: connect ECONNREFUSED 127.0.0.1:4566
localstack_main |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
localstack_main |   errno: 'ECONNREFUSED',
localstack_main |   code: 'NetworkingError',
localstack_main |   syscall: 'connect',
localstack_main |   address: '127.0.0.1',
localstack_main |   port: 4566,
localstack_main |   region: 'us-east-1',
localstack_main |   hostname: 'localhost',
localstack_main |   retryable: true,
localstack_main |   time: 2020-10-17T11:03:58.625Z
localstack_main | } Error: connect ECONNREFUSED 127.0.0.1:4566
localstack_main |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
localstack_main | END RequestId: 362148a5-88ec-1e25-3197-6ea9d94e38fd
localstack_main | REPORT RequestId: 362148a5-88ec-1e25-3197-6ea9d94e38fd        Init Duration: 5375.37 ms       Duration: 6000.00 ms    Billed Duration: 6000 ms        Memory Size: 1536 MB    Max Memory Used: 59 MB   Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 541, in run_lambda
localstack_main |     result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 173, in execute
localstack_main |     return do_execute()
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 165, in do_execute
localstack_main |     return _run(func_arn=func_arn)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
localstack_main |     raise e
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 145, in wrapped
localstack_main |     result = func(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 158, in _run
localstack_main |     raise e
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 146, in _run
localstack_main |     result = self._execute(func_arn, func_details, event, context, version)
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 302, in _execute
localstack_main |     result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 210, in run_lambda_executor
localstack_main |     raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
localstack_main | Exception: Lambda process returned error status code: 1. Result: {"errorMessage":"2020-10-17T11:03:58.632Z 362148a5-88ec-1e25-3197-6ea9d94e38fd Task timed out after 6.00 seconds"}. Output:
localstack_main | START RequestId: 362148a5-88ec-1e25-3197-6ea9d94e38fd Version: $LATEST
localstack_main | 2020-10-17T11:03:58.629Z      362148a5-88ec-1e25-3197-6ea9d94e38fd    INFO    Error: connect ECONNREFUSED 127.0.0.1:4566
localstack_main |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
localstack_main |   errno: 'ECONNREFUSED',
localstack_main |   code: 'NetworkingError',
localstack_main |   syscall: 'connect',
localstack_main |   address: '127.0.0.1',
localstack_main |   port: 4566,
localstack_main |   region: 'us-east-1',
localstack_main |   hostname: 'localhost',
localstack_main |   retryable: true,
localstack_main |   time: 2020-10-17T11:03:58.625Z
localstack_main | } Error: connect ECONNREFUSED 127.0.0.1:4566
localstack_main |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
localstack_main | END RequestId: 362148a5-88ec-1e25-3197-6ea9d94e38fd
localstack_main | REPORT RequestId: 362148a5-88ec-1e25-3197-6ea9d94e38fd        Init Duration: 5375.37 ms       Duration: 6000.00 ms    Billed Duration: 6000 ms        Memory Size: 1536 MB    Max Memory Used: 59 MB
```

**Comment by Kavyeshs41** [comment]
Hi @leungas ,

Is it possible to provide a small git repository or zipped code that consist of handler functions for lambda with compilation/running instruction to reproduce this issue?

Thanks.

**Comment by carlosschuenck** [comment]
I had the same problem and I tried to use S3. I solved doing this:

const s3 = new S3({
  s3ForcePathStyle: true,
  accessKeyId: 'S3RVER',
  secretAccessKey: 'S3RVER',
  endpoint: new Endpoint('host.docker.internal:4566'),
});

**Comment by whummer** [comment]
Thanks for the updates @leungas , and thanks for providing the workaround @carlosschuenck . 👍 

For any future readers of this thread - please make sure to use the `LOCALSTACK_HOSTNAME` environment variable in your Lambda handlers.

Also, this command may come in handy to debug common networking issues, in case you're using docker-compose for configuration:
```
$ pip install --upgrade localstack
$ localstack config validate
```
Please let us know if the problem persists. Thanks!
