### ISSUE TITLE
Fail to install on Max OS X EI Capitan Version 10.11.6

### ISSUE THREAD

**Issue by Dogzhou** [localstack/localstack#307]
This is error log(Red line):
```
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/localstack/__init__.py'
```

I tried pip install --user localstack, log seemingly succeed:
```
react-native ➤ pip install --user localstack
Collecting localstack
Requirement already satisfied: airspeed==0.5.5.dev20160812 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: subprocess32-ext==3.2.8.2 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: coverage==4.0.3 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: nose==1.3.7 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: pyYAML==3.12 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: flask==0.10.1 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: six==1.10.0 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: requests-aws4auth==0.9 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: awscli==1.11.86 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: docopt==0.6.2 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: boto==2.46.1 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: localstack-ext in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: requests==2.18.4 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: psutil==5.2.0 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: boto3==1.4.4 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: jsonpath-rw==1.4.0 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: elasticsearch==5.3.0 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: pyOpenSSL==17.0.0 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: flask-cors==3.0.3 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: moto-ext==1.0.1.7 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: pep8==1.7.0 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: python-coveralls==2.7.0 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: flask-swagger==0.2.12 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: xmltodict==0.10.2 in /usr/local/lib/python2.7/site-packages (from localstack)
Requirement already satisfied: cachetools==0.8.0 in /usr/local/lib/python2.7/site-packages (from airspeed==0.5.5.dev20160812->localstack)
Requirement already satisfied: Jinja2>=2.4 in /usr/local/lib/python2.7/site-packages (from flask==0.10.1->localstack)
Requirement already satisfied: Werkzeug>=0.7 in /usr/local/lib/python2.7/site-packages (from flask==0.10.1->localstack)
Requirement already satisfied: itsdangerous>=0.21 in /usr/local/lib/python2.7/site-packages (from flask==0.10.1->localstack)
Requirement already satisfied: colorama<=0.3.7,>=0.2.5 in /usr/local/lib/python2.7/site-packages (from awscli==1.11.86->localstack)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.9 in /usr/local/lib/python2.7/site-packages (from awscli==1.11.86->localstack)
Requirement already satisfied: docutils>=0.10 in /usr/local/lib/python2.7/site-packages (from awscli==1.11.86->localstack)
Requirement already satisfied: rsa<=3.5.0,>=3.1.2 in /usr/local/lib/python2.7/site-packages (from awscli==1.11.86->localstack)
Requirement already satisfied: botocore==1.5.49 in /usr/local/lib/python2.7/site-packages (from awscli==1.11.86->localstack)
Requirement already satisfied: dnslib==0.9.7 in /usr/local/lib/python2.7/site-packages (from localstack-ext->localstack)
Requirement already satisfied: pyminifier==2.1 in /usr/local/lib/python2.7/site-packages (from localstack-ext->localstack)
Requirement already satisfied: pyaes==1.6.0 in /usr/local/lib/python2.7/site-packages (from localstack-ext->localstack)
Requirement already satisfied: warrant-ext>=0.2.0.3 in /usr/local/lib/python2.7/site-packages (from localstack-ext->localstack)
Requirement already satisfied: srp-ext==1.0.7.1 in /usr/local/lib/python2.7/site-packages (from localstack-ext->localstack)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/site-packages (from requests==2.18.4->localstack)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/site-packages (from requests==2.18.4->localstack)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/site-packages (from requests==2.18.4->localstack)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/site-packages (from requests==2.18.4->localstack)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python2.7/site-packages (from boto3==1.4.4->localstack)
Requirement already satisfied: ply in /usr/local/lib/python2.7/site-packages (from jsonpath-rw==1.4.0->localstack)
Requirement already satisfied: decorator in /usr/local/lib/python2.7/site-packages (from jsonpath-rw==1.4.0->localstack)
Requirement already satisfied: cryptography>=1.7 in /usr/local/lib/python2.7/site-packages (from pyOpenSSL==17.0.0->localstack)
Requirement already satisfied: python-dateutil in /usr/local/lib/python2.7/site-packages (from moto-ext==1.0.1.7->localstack)
Requirement already satisfied: pytz in /usr/local/lib/python2.7/site-packages (from moto-ext==1.0.1.7->localstack)
Requirement already satisfied: pyaml in /usr/local/lib/python2.7/site-packages (from moto-ext==1.0.1.7->localstack)
Requirement already satisfied: dicttoxml in /usr/local/lib/python2.7/site-packages (from moto-ext==1.0.1.7->localstack)
Requirement already satisfied: mock in /usr/local/lib/python2.7/site-packages (from moto-ext==1.0.1.7->localstack)
Requirement already satisfied: cookies in /usr/local/lib/python2.7/site-packages (from moto-ext==1.0.1.7->localstack)
Requirement already satisfied: sh in /usr/local/lib/python2.7/site-packages (from python-coveralls==2.7.0->localstack)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python2.7/site-packages (from Jinja2>=2.4->flask==0.10.1->localstack)
Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in /usr/local/lib/python2.7/site-packages (from s3transfer<0.2.0,>=0.1.9->awscli==1.11.86->localstack)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python2.7/site-packages (from rsa<=3.5.0,>=3.1.2->awscli==1.11.86->localstack)
Requirement already satisfied: python-jose-ext>=1.3.2.2 in /usr/local/lib/python2.7/site-packages (from warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already satisfied: envs>=0.3.0 in /usr/local/lib/python2.7/site-packages (from warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already satisfied: enum34 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.7->pyOpenSSL==17.0.0->localstack)
Requirement already satisfied: cffi>=1.7 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.7->pyOpenSSL==17.0.0->localstack)
Requirement already satisfied: ipaddress in /usr/local/lib/python2.7/site-packages (from cryptography>=1.7->pyOpenSSL==17.0.0->localstack)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.7->pyOpenSSL==17.0.0->localstack)
Requirement already satisfied: pbr>=0.11 in /usr/local/lib/python2.7/site-packages (from mock->moto-ext==1.0.1.7->localstack)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /usr/local/lib/python2.7/site-packages (from mock->moto-ext==1.0.1.7->localstack)
Requirement already satisfied: pycryptodome<3.4.0,>=3.3.1 in /usr/local/lib/python2.7/site-packages (from python-jose-ext>=1.3.2.2->warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already satisfied: ecdsa<1.0 in /usr/local/lib/python2.7/site-packages (from python-jose-ext>=1.3.2.2->warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already satisfied: future<1.0 in /usr/local/lib/python2.7/site-packages (from python-jose-ext>=1.3.2.2->warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already satisfied: terminaltables>=3.0.0 in /usr/local/lib/python2.7/site-packages (from envs>=0.3.0->warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already satisfied: click>=6.6 in /usr/local/lib/python2.7/site-packages (from envs>=0.3.0->warrant-ext>=0.2.0.3->localstack-ext->localstack)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/site-packages (from cffi>=1.7->cryptography>=1.7->pyOpenSSL==17.0.0->localstack)
Installing collected packages: localstack
Successfully installed localstack-0.7.5
```

but cannot find command `localstack`

**Comment by Dogzhou** [comment]
Succeed with `sudo` which is the last option, while come across https://github.com/localstack/localstack/issues/254

**Comment by migurski** [comment]
@Dogzhou, the system `pip` installs into the root-only directory `/usr/local`.  You’ll either need to `sudo pip install` for it to work (as you found), or try the [cleaner approach of using virtualenv](http://docs.python-guide.org/en/latest/dev/virtualenvs/#virtualenv) to get an installation of LocalStack specific to a single directory or user.

**Comment by whummer** [comment]
Closing this issue, as the problem appears to be solved. @Dogzhou Ideally, LocalStack should be installed without `sudo` - either by giving non-root users access to `/usr/local` (preferred), or by using a `virtualenv`, as suggested by @migurski . Thanks
