### ISSUE TITLE
After couple of successful requests S3 service is blocked and requests timeout

### ISSUE THREAD

**Issue by el-chuck** [localstack/localstack#3071]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
I run localstack in a docker container alongside multiple java applications running in a different docker container on a Ubuntu 18.04 host machine to execute tests. 
After preparation of test buckets and data is complete, the java applications will start to read that test data in parallel via java s3 client into memory. A few of them can read the data successfully, but after some time localstack seems to be blocked and stops processing further requests. Requests from host to localstack container or from the java container to localstack container will then timeout. Also request to localstack health endpoint will fail with a timeout.

netstat shows a high recv-q on the edge port 4566, executing strace on the localstack python process "unblocks" localstack probably because of restarting the syscall

## Expected behavior
* connections to s3 localstack and health endpoint do not timeout

## Actual behavior
* connections to s3 localstack and health endpoint do timeout

# Steps to reproduce
Start localstack container with s3 service
From a different container request data from s3 in parallel

## Command used to start LocalStack
localstack Dockerfile

```
FROM localstack/localstack:latest

COPY prepare_s3.sh /docker-entrypoint-initaws.d/01-prepare_s3.sh

ENV SERVICES=s3
ENV DATA_DIR=/tmp/localstack/data
```

docker-compose.yml

```
localstack-mock:
  image: <localstack image>
  environment:
    - SERVICES=s3
    - DATA_DIR=/tmp/localstack/data
    - DEBUG=1
  ports:
    - "4566:4566"

java:
  image: <java image>
    depends_on:
      - "localstack-mock"
    links:
      - "localstack-mock:s3"    
    environment:
      AWS_ACCESS_KEY_ID: "dummy"
      AWS_SECRET_ACCESS_KEY: "dummy"
```

and then `docker-compose up -d`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
with aws sdk

```
s3 = AmazonS3ClientBuilder
                .standard()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://s3:4566", "us-east-1"))
                .withPathStyleAccessEnabled(true)
                .withChunkedEncodingDisabled(true)
                .build();

s3.doesObjectExist(this.bucketName, objectName);
...
s3.getObject(this.bucketName, objectName).getObjectContent();
...
s3.getObjectMetadata(this.bucketName, objectName)
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-279) by [Unito](https://www.unito.io/learn-more)

**Comment by chezsmithy** [comment]
We are seeing a similar issue under high load with SQS queues. I suspect there is a tuning issue either in the edge router or the proxy. Is it possible to tune the number of of listener threads somehow to see if this increases throughput?

**Comment by AlexisWilke** [comment]
I ran in a similar issue, copying much data and at some point all connections fail.

Then I noticed that the VM running the localstack Docker would run out of memory and started to swap. So the slowdown was due to that. Did you check that on your end?

**Comment by linhx** [comment]
In my case, I'm using the `pre-signed url` to request the resources. The request from the browser's address bar blocks the others request.
Sometime it stops blocking after a few minutes, but sometime doesn't.
As the case I recorded in the video below, the blocking stop after I stop the request on the browser.
https://youtu.be/_YWXHDOYGnY

**Comment by lmarsden** [comment]
Switching to running on a machine with >=4 vCPUs (vs. 2 previously) fixed this issue in our case.

**Comment by el-chuck** [comment]
> I ran in a similar issue, copying much data and at some point all connections fail.
> 
> Then I noticed that the VM running the localstack Docker would run out of memory and started to swap. So the slowdown was due to that. Did you check that on your end?

yes, we checked that on our end. we have lots of free system memory available, no swapping, and actually the file sizes are pretty small.

> Switching to running on a machine with >=4 vCPUs (vs. 2 previously) fixed this issue in our case.

also in our case we have way more than 4 vCPUs and still get the issue

**Comment by BenderRodrigez** [comment]
We are facing the same issue. We have localstack deployed in Kubernetes to serve to the number application instances in our QA environment. 

What I see in localstack logs:

```
2020-11-05T08:13:21:WARNING:urllib3.connectionpool: Connection pool is full, discarding connection: localstack-aws-64684f674c-5mnzq
2020-11-05T08:13:21:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request GET http://localhost/defaultconfig-store/properties: Read timeout on endpoint URL: "http://localstack-aws-64684f674c-5mnzq:4572/defaultconfig-store?website" Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/httpsession.py", line 254, in send
    urllib_response = conn.urlopen(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: AWSHTTPConnectionPool(host='localstack-aws-64684f674c-5mnzq', port=4572): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 53, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 46, in run_sync
    return await loop.run_in_executor(THREAD_POOL, copy_context().run, func, *args)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 550, in handler
    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 393, in modify_and_forward
    updated_response = update_listener.return_response(**kwargs)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1171, in return_response
    website_config = s3_client.get_bucket_website(Bucket=bucket_name)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 621, in _make_api_call
    http, parsed_response = self._make_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 641, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 136, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 253, in _needs_retry
    responses = self._event_emitter.emit(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 269, in _send
    return self.http_session.send(request)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/httpsession.py", line 289, in send
    raise ReadTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "http://localstack-aws-64684f674c-5mnzq:4572/defaultconfig-store?website"
```

This is my test code (cleaned to simplify understanding):

```java
public class AmazonS3ConfigTest {

    private AmazonS3 client;
    private Bucket currentBucket;

    @Before
    public void setupBucket() {
        client = getClient(getLocalstackUrl());

        currentBucket = client.createBucket(getTeamcityRandomSessionKey().toLowerCase() + "config-store");

        client.putObject(currentBucket.getName(), "properties", "test=true");
    }

    @Test
    public void readPropertiesFromS3WithBasicCredentials() {
        AmazonS3 client = getClient(getLocalstackUrl());
            final S3Object download = client.getObject(getTeamcityRandomSessionKey().toLowerCase() + "config-store", "properties");

            Properties props = new Properties();

            try {
                props.load(download.getObjectContent());
            } catch (IOException e) {
                throw new ConfigurationPollingException("Can't pull S3 Bucket for config", e);
            }

            HashMap<String, String> result = new HashMap<>();
            props.forEach((k,v) -> result.put(k.toString(), v.toString()));
    }

    @After
    public void cleanupBucket() {
        client.deleteObject(currentBucket.getName(), "properties");
        client.deleteBucket(currentBucket.getName());
    }

    private AmazonS3 getClient(String localstackHost) {
        AWSCredentialsProvider provider = new AWSStaticCredentialsProvider(new BasicAWSCredentials("accessKey", "secretKey"));

        final AmazonS3ClientBuilder builder = AmazonS3ClientBuilder.standard()
                .withPathStyleAccessEnabled(true)
                .withCredentials(provider)
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(localstackHost, Regions.US_EAST_1.getName()));

        return builder.build();
    }
}
```

After about 1 thousand test repeats, the issue is arising.

**Comment by whummer** [comment]
Thanks for the update @BenderRodrigez . It looks like you're still using an oder version of LocalStack (still using the old/legacy port `4572`) - can you please give it a try with the `latest` Docker image? Please let us know if the problem still persists with the latest version. Thanks

**Comment by BenderRodrigez** [comment]
@whummer We are currently on: `localstack/localstack:0.11.3` and using CentralEdgePort feature. But as I see there are few minor versions available, so I'll do the tests and let you know.
Thank you!

**Comment by BenderRodrigez** [comment]
@whummer After ~1500 iterations, I can't reproduce this issue on version `0.11.6`. I hope it will be sufficient fix for my issue.

Thank you very much for your advise!

**Comment by AlexisWilke** [comment]
I tried again today with [the latest (v0.12.2)](https://hub.docker.com/layers/localstack/localstack/0.12.2/images/sha256-d4e15a305a6fc3dddde26097dd6d18fbee378180e55ca2047cb51d417e713486?context=explore) and it still leaks for me.

**Comment by whummer** [comment]
Hi @BenderRodrigez, thanks for the update. There's been several enhancements to the S3 implementation (and performance improvements in general) - can you please pull the `latest` Docker image and let us know if the problem still persists? Thanks for your help!

**Comment by BenderRodrigez** [comment]
@whummer I just tested the same test case as before with the `latest` version of Localstack and everything looks fine to me. No more issues. Thank you!
