### ISSUE TITLE
localstack.services.infra.start_infra() dependent directory structure not created.

### ISSUE THREAD

**Issue by i-ghost** [localstack/localstack#309]
# Affected platforms
* Windows 10, Python 3.6.2
* Ubuntu 16.04.3 LTS, Python 3.6.1

# Reproduction steps
Run the following on Windows 10 Python 3.6.2 in a virtualenv:

```text
>>> from localstack.services import infra
>>> infra.start_infra()
2017-09-10T22:30:07:INFO:localstack.services.install: Downloading and installing local Elasticsearch server. This may take some time.
ERROR: 'mkdir -p E:\Users\user\dev\project\.env\lib\site-packages\localstack/infra': b'The syntax of the command is incorrect.\r\n'
Error starting infrastructure: Command 'mkdir -p E:\Users\user\dev\project\.env\lib\site-packages\localstack/infra' returned non-zero exit status 1. Traceback (most recent call last):
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\services\infra.py", line 445, in start_infra
    install.install_components(apis)
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\services\install.py", line 106, in install_components
    parallelize(install_component, names)
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\utils\common.py", line 670, in parallelize
    result = pool.map(func, list)
  File "c:\python36-2\Lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "c:\python36-2\Lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "c:\python36-2\Lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "c:\python36-2\Lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\services\install.py", line 102, in install_component
    install_elasticsearch()
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\services\install.py", line 35, in install_elasticsearch
    run('mkdir -p %s' % INSTALL_DIR_INFRA)
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\utils\common.py", line 572, in run
    return do_run(cmd)
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\utils\common.py", line 569, in do_run
    raise e
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\utils\common.py", line 554, in do_run
    output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
  File "c:\python36-2\Lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "c:\python36-2\Lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'mkdir -p E:\Users\user\dev\project\.env\lib\site-packages\localstack/infra' returned non-zero exit status 1.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\services\infra.py", line 479, in start_infra
    raise e
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\services\infra.py", line 445, in start_infra
    install.install_components(apis)
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\services\install.py", line 106, in install_components
    parallelize(install_component, names)
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\utils\common.py", line 670, in parallelize
    result = pool.map(func, list)
  File "c:\python36-2\Lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "c:\python36-2\Lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "c:\python36-2\Lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "c:\python36-2\Lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\services\install.py", line 102, in install_component
    install_elasticsearch()
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\services\install.py", line 35, in install_elasticsearch
    run('mkdir -p %s' % INSTALL_DIR_INFRA)
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\utils\common.py", line 572, in run
    return do_run(cmd)
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\utils\common.py", line 569, in do_run
    raise e
  File "E:\Users\user\dev\project\.env\lib\site-packages\localstack\utils\common.py", line 554, in do_run
    output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
  File "c:\python36-2\Lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "c:\python36-2\Lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'mkdir -p E:\Users\user\dev\project\.env\lib\site-packages\localstack/infra' returned non-zero exit status 1.
```

# Analysis
It's specifying an option that doesn't exist on Windows:
```test
mkdir -p
The syntax of the command is incorrect.
```

# Workaround
Creating the directory manually allows the program/tests to run. Not ideal in a CI testing environment running with Tox.

# Other
Doing a quick search on the codebase shows a few of these:

* https://github.com/localstack/localstack/blob/9ce1eb0f2fe80a613ff97e17ee8b4ca99370c0ef/localstack/services/install.py#L38
* https://github.com/localstack/localstack/blob/9ce1eb0f2fe80a613ff97e17ee8b4ca99370c0ef/localstack/services/es/es_starter.py#L41
*  https://github.com/localstack/localstack/blob/9ce1eb0f2fe80a613ff97e17ee8b4ca99370c0ef/localstack/services/infra.py#L421
* https://github.com/localstack/localstack/blob/9ce1eb0f2fe80a613ff97e17ee8b4ca99370c0ef/localstack/services/awslambda/lambda_api.py#L422

Why not just use `os.makedirs`/other Python abstractions?

**Comment by whummer** [comment]
Thanks for reporting @i-ghost , we should definitely avoid calling `mkdir` as a shell command. There is already a utility function in [common.py](https://github.com/localstack/localstack/blob/master/localstack/utils/common.py#L308) that we can reuse - would you be able to raise a pull request to fix this? Thanks!

**Comment by TheMasquerader** [comment]
- localstack 0.8.5
- python 3.6 / 3.5 (tried both, same results)

Having the same issue with `mkdir -p` and also with:

```
Starting local dev environment. CTRL-C to quit.
ERROR: 'cd "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\site-packages\localstack/infra/dynamodb" && zip -u DynamoDBLocal.jar log4j2.xml || true': b"'zip' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n'true' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
Error starting infrastructure: Command 'cd "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\site-packages\localstack/infra/dynamodb" && zip -u DynamoDBLocal.jar log4j2.xml || true' returned non-zero exit status 1 Traceback (most recent call last):
  File "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\site-packages\localstack\services\infra.py", line 465, in start_infra
    install.install_components(apis)
  File "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\site-packages\localstack\services\install.py", line 136, in install_components
    parallelize(install_component, names)
  File "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\site-packages\localstack\utils\common.py", line 716, in parallelize
    result = pool.map(func, list)
  File "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\multiprocessing\pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\multiprocessing\pool.py", line 608, in get
    raise self._value
  File "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\site-packages\localstack\services\install.py", line 128, in install_component
    install_dynamodb_local()
  File "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\site-packages\localstack\services\install.py", line 98, in install_dynamodb_local
    run('cd "%s" && zip -u DynamoDBLocal.jar log4j2.xml || true' % INSTALL_DIR_DDB)
  File "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\site-packages\localstack\utils\common.py", line 618, in run
    return do_run(cmd)
  File "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\site-packages\localstack\utils\common.py", line 615, in do_run
    raise e
  File "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\site-packages\localstack\utils\common.py", line 600, in do_run
    output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
  File "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'cd "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\site-packages\localstack/infra/dynamodb" && zip -u DynamoDBLocal.jar log4j2.xml || true' returned non-zero exit status 1

ERROR: Command 'cd "C:\Users\Atodic\AppData\Local\Programs\Python\Python35\lib\site-packages\localstack/infra/dynamodb" && zip -u DynamoDBLocal.jar log4j2.xml || true' returned non-zero exit status 1
```

**Comment by whummer** [comment]
Closing as outdated / obsolete. Starting in Docker is the default in the latest version of LocalStack on Windows.
