### ISSUE TITLE
SES sendEmail fails with 500 error

### ISSUE THREAD

**Issue by danielblignaut** [localstack/localstack#3095]
# Type of request: This is a bug with SES sendEmail resulting in 500 responses
[x] bug report
[ ] feature request

# Detailed description
When running the sendEmail function from aws javascript sdk, the localstack proxy server responds with 500 error and the docker logs reflect an issue with the edge proxy, proxying the request to ses.

localstack.sh

```bash
TMPDIR=/private$TMPDIR docker-compose up
```

docker-compose.yml

```yml
version: "2.1"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY={KEY VALUE}
      - SERVICES=sns,ses,dynamodb,cognito,kinesis
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
      - AWS_DEFAULT_REGION=eu-west-2
      - SMTP_HOST=email-smtp.eu-west-2.amazonaws.com
      - SMTP_USER={AWS SES USER}
      - SMTP_PASS={AWS SES USER PASS}
      - SMTP_EMAIL={email address to send from}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```

example lambda function snippet sending an email:

```typescript
let endpoint = 'http://localhost:4566'

const ses = new SES({
		endpoint: endpoint,
		region: 'eu-west-2'
	})

await ses.sendEmail({
			Destination: {
				ToAddresses: [
					email
				]
			},
			Message: {
				Body: {
					Text: {
						Charset: 'UTF-8',
						Data: `Account verification code: ${confirmationCode}`
					}
				},
				Subject: {
					Charset: 'UTF-8',
					Data: `Counterweight Account verification code: ${confirmationCode}`
				}
			},
			Source: {email address},
		})
			.promise()
```

lambda logs:

```log
500: 
    at Request.extractError (/Users/user/Documents/Development/counterweightuk/counterweightuk-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/Users/user/Documents/Development/counterweightuk/counterweightuk-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/user/Documents/Development/counterweightuk/counterweightuk-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/user/Documents/Development/counterweightuk/counterweightuk-cdk/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/user/Documents/Development/counterweightuk/counterweightuk-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/user/Documents/Development/counterweightuk/counterweightuk-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/user/Documents/Development/counterweightuk/counterweightuk-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/user/Documents/Development/counterweightuk/counterweightuk-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/user/Documents/Development/counterweightuk/counterweightuk-cdk/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/user/Documents/Development/counterweightuk/counterweightuk-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: '',
  code: 500,
  time: 2020-10-13T15:36:30.945Z,
  requestId: undefined,
  statusCode: 500,
  retryable: true
}
```

docker logs... the command executed multiple times so I'm hoping I've given the correct excerpt

```log
localstack_1  | 2020-10-13T15:36:39:WARNING:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fc2c6c23e50>(None) failed: MyHTTPConnectionPool(host='d81c12092ff8', port=47127): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2c6c265e0>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
localstack_1  |     conn = connection.create_connection(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
localstack_1  |     raise err
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
localstack_1  |     sock.connect(sa)
localstack_1  | ConnectionRefusedError: [Errno 111] Connection refused
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
localstack_1  |     httplib_response = self._make_request(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
localstack_1  |     conn.request(method, url, **httplib_request_kw)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1230, in request
localstack_1  |     self._send_request(method, url, body, headers, encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
localstack_1  |     self.endheaders(body, encode_chunked=encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
localstack_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
localstack_1  |     self.send(msg)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 944, in send
localstack_1  |     self.connect()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
localstack_1  |     conn = self._new_conn()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
localstack_1  |     raise NewConnectionError(
localstack_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc2c6c265e0>: Failed to establish a new connection: [Errno 111] Connection refused
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
localstack_1  |     resp = conn.urlopen(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
localstack_1  |     retries = retries.increment(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
localstack_1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
localstack_1  | urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='d81c12092ff8', port=47127): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2c6c265e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 533, in run
localstack_1  |     result = self.func(self.params)
localstack_1  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack_1  |     return fn(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 560, in handler
localstack_1  |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/aws/aws_utils.py", line 22, in modify_and_forward
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 333, in modify_and_forward
localstack_1  |     listener_result = listener.forward_request(method=method,
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 81, in forward_request
localstack_1  |     return do_forward_request(api, port, method, path, data, headers)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py", line 130, in do_forward_request
localstack_1  |     return do_forward_request_orig(api,port,method,path,data,headers,*args,**kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 86, in do_forward_request
localstack_1  |     result = do_forward_request_inmem(api, port, method, path, data, headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 106, in do_forward_request_inmem
localstack_1  |     response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 375, in modify_and_forward
localstack_1  |     response = requests_method(request_url, data=data_to_send,
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack_1  |     return request('post', url, data=data, json=json, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
localstack_1  |     raise ConnectionError(e, request=request)
localstack_1  | requests.exceptions.ConnectionError: MyHTTPConnectionPool(host='d81c12092ff8', port=47127): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2c6c265e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack_1  | 
localstack_1  | 2020-10-13T15:36:39:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: MyHTTPConnectionPool(host='d81c12092ff8', port=47127): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2c6c265e0>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
localstack_1  |     conn = connection.create_connection(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
localstack_1  |     raise err
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
localstack_1  |     sock.connect(sa)
localstack_1  | ConnectionRefusedError: [Errno 111] Connection refused
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
localstack_1  |     httplib_response = self._make_request(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
localstack_1  |     conn.request(method, url, **httplib_request_kw)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1230, in request
localstack_1  |     self._send_request(method, url, body, headers, encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
localstack_1  |     self.endheaders(body, encode_chunked=encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
localstack_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
localstack_1  |     self.send(msg)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 944, in send
localstack_1  |     self.connect()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
localstack_1  |     conn = self._new_conn()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
localstack_1  |     raise NewConnectionError(
localstack_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc2c6c265e0>: Failed to establish a new connection: [Errno 111] Connection refused
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
localstack_1  |     resp = conn.urlopen(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
localstack_1  |     retries = retries.increment(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
localstack_1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
localstack_1  | urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='d81c12092ff8', port=47127): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2c6c265e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 94, in index
localstack_1  |     raise result
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 533, in run
localstack_1  |     result = self.func(self.params)
localstack_1  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack_1  |     return fn(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 560, in handler
localstack_1  |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/aws/aws_utils.py", line 22, in modify_and_forward
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 333, in modify_and_forward
localstack_1  |     listener_result = listener.forward_request(method=method,
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 81, in forward_request
localstack_1  |     return do_forward_request(api, port, method, path, data, headers)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py", line 130, in do_forward_request
localstack_1  |     return do_forward_request_orig(api,port,method,path,data,headers,*args,**kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 86, in do_forward_request
localstack_1  |     result = do_forward_request_inmem(api, port, method, path, data, headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 106, in do_forward_request_inmem
localstack_1  |     response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 375, in modify_and_forward
localstack_1  |     response = requests_method(request_url, data=data_to_send,
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack_1  |     return request('post', url, data=data, json=json, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
localstack_1  |     raise ConnectionError(e, request=request)
localstack_1  | requests.exceptions.ConnectionError: MyHTTPConnectionPool(host='d81c12092ff8', port=47127): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2c6c265e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack_1  | 
localstack_1  | 2020-10-13T15:36:39:WARNING:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fc2c6c230d0>(None) failed: MyHTTPConnectionPool(host='d81c12092ff8', port=47127): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2c6c21a90>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
localstack_1  |     conn = connection.create_connection(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
localstack_1  |     raise err
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
localstack_1  |     sock.connect(sa)
localstack_1  | ConnectionRefusedError: [Errno 111] Connection refused
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
localstack_1  |     httplib_response = self._make_request(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
localstack_1  |     conn.request(method, url, **httplib_request_kw)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1230, in request
localstack_1  |     self._send_request(method, url, body, headers, encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
localstack_1  |     self.endheaders(body, encode_chunked=encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
localstack_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
localstack_1  |     self.send(msg)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 944, in send
localstack_1  |     self.connect()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
localstack_1  |     conn = self._new_conn()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
localstack_1  |     raise NewConnectionError(
localstack_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc2c6c21a90>: Failed to establish a new connection: [Errno 111] Connection refused
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
localstack_1  |     resp = conn.urlopen(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
localstack_1  |     retries = retries.increment(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
localstack_1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
localstack_1  | urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='d81c12092ff8', port=47127): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2c6c21a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 533, in run
localstack_1  |     result = self.func(self.params)
localstack_1  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack_1  |     return fn(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 560, in handler
localstack_1  |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/aws/aws_utils.py", line 22, in modify_and_forward
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 333, in modify_and_forward
localstack_1  |     listener_result = listener.forward_request(method=method,
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 81, in forward_request
localstack_1  |     return do_forward_request(api, port, method, path, data, headers)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py", line 130, in do_forward_request
localstack_1  |     return do_forward_request_orig(api,port,method,path,data,headers,*args,**kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 86, in do_forward_request
localstack_1  |     result = do_forward_request_inmem(api, port, method, path, data, headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 106, in do_forward_request_inmem
localstack_1  |     response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 375, in modify_and_forward
localstack_1  |     response = requests_method(request_url, data=data_to_send,
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack_1  |     return request('post', url, data=data, json=json, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
localstack_1  |     raise ConnectionError(e, request=request)
localstack_1  | requests.exceptions.ConnectionError: MyHTTPConnectionPool(host='d81c12092ff8', port=47127): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2c6c21a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack_1  | 
localstack_1  | 2020-10-13T15:36:39:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: MyHTTPConnectionPool(host='d81c12092ff8', port=47127): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2c6c21a90>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
localstack_1  |     conn = connection.create_connection(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
localstack_1  |     raise err
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
localstack_1  |     sock.connect(sa)
localstack_1  | ConnectionRefusedError: [Errno 111] Connection refused
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
localstack_1  |     httplib_response = self._make_request(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
localstack_1  |     conn.request(method, url, **httplib_request_kw)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1230, in request
localstack_1  |     self._send_request(method, url, body, headers, encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
localstack_1  |     self.endheaders(body, encode_chunked=encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
localstack_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
localstack_1  |     self.send(msg)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 944, in send
localstack_1  |     self.connect()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
localstack_1  |     conn = self._new_conn()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
localstack_1  |     raise NewConnectionError(
localstack_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc2c6c21a90>: Failed to establish a new connection: [Errno 111] Connection refused
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
localstack_1  |     resp = conn.urlopen(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
localstack_1  |     retries = retries.increment(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
localstack_1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
localstack_1  | urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='d81c12092ff8', port=47127): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2c6c21a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 94, in index
localstack_1  |     raise result
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 533, in run
localstack_1  |     result = self.func(self.params)
localstack_1  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack_1  |     return fn(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 560, in handler
localstack_1  |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/aws/aws_utils.py", line 22, in modify_and_forward
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 333, in modify_and_forward
localstack_1  |     listener_result = listener.forward_request(method=method,
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 81, in forward_request
localstack_1  |     return do_forward_request(api, port, method, path, data, headers)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py", line 130, in do_forward_request
localstack_1  |     return do_forward_request_orig(api,port,method,path,data,headers,*args,**kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 86, in do_forward_request
localstack_1  |     result = do_forward_request_inmem(api, port, method, path, data, headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 106, in do_forward_request_inmem
localstack_1  |     response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 375, in modify_and_forward
localstack_1  |     response = requests_method(request_url, data=data_to_send,
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack_1  |     return request('post', url, data=data, json=json, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
localstack_1  |     raise ConnectionError(e, request=request)
localstack_1  | requests.exceptions.ConnectionError: MyHTTPConnectionPool(host='d81c12092ff8', port=47127): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc2c6c21a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

## Expected behavior
200 response and an email sent.

## Actual behavior
...

# Steps to reproduce
./localstack.sh

execute the above lambda snippet

## Command used to start LocalStack
./localstack.sh (see bash file above)

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
not necessary

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-286) by [Unito](https://www.unito.io/learn-more)

**Comment by QuattroViper** [comment]
I am having the same issue on version 1.23.1.

**Comment by whummer** [comment]
Thanks for reporting @danielblignaut @QuattroViper . Apologies for the delay on this one - this issue should be fixed in the `latest` version. Can you please pull the Docker image and give it a try? Please let us know if the problem persists. Thanks for your help!
