### ISSUE TITLE
ModuleNotFoundError: No module named 'pwd' on Windows 10

### ISSUE THREAD

**Issue by chrillejb** [localstack/localstack#3107]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

Trying to start localstack (0.11.6) that's been downloaded on a Windows 10 machine with the help of pip. In fact, trying to run just: `localstack`, which should print the usage, results in the same output.

Output from a PowerShell prompt:

```
P:\>python C:\Users\user\AppData\Local\Programs\Python\Python39\Scripts\\localstack start
'uname' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\Scripts\localstack", line 18, in <module>
    cli.main()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\utils\cli.py", line 130, in main
    bootstrap.load_plugins(scope=bootstrap.PLUGIN_SCOPE_COMMANDS)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\utils\analytics\profiler.py", line 153, in wrapped
    from localstack.utils.common import now_utc
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\utils\common.py", line 4, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'
```

From my understanding windows might not be compatible with the `pwd` module.

Official Python docs:

> This module provides access to the Unix user account and password database. It is available on all Unix versions.

But this is just guesswork...

---

I've tried with lower version of localstack (0.11.2 and 0.11.5) on the same setup, and they work just fine.

### Versions

* Python 3.9.0
* pip 20.2.3
* Docker version 19.03.13, build 4484c46d9d
* Windows 10 Enterprise, Version 1809, OS build 17763.1457

## Expected behavior

Localstack starts

## Actual behavior

Localstack does not start

# Steps to reproduce

## Command used to start LocalStack

`localstack start`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

none

**Comment by nicotk** [comment]
Hello @chrillejb,

I exactly had the same error as you when trying to start Localstack on my computer:

```
C:\Users\[...]>localstack start

C:\Users\[...]>python C:\Users\[...]\AppData\Local\Programs\Python\Python39\Scripts\\localstack start
'uname' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
Traceback (most recent call last):
  File "C:\Users\[...]\AppData\Local\Programs\Python\Python39\Scripts\localstack", line 18, in <module>
    cli.main()
  File "C:\Users\[...]\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\utils\cli.py", line 130, in main
    bootstrap.load_plugins(scope=bootstrap.PLUGIN_SCOPE_COMMANDS)
  File "C:\Users\[...]\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\utils\analytics\profiler.py", line 153, in wrapped
    from localstack.utils.common import now_utc
  File "C:\Users\[...]\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\utils\common.py", line 4, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'
```

I quite have the same configuration as you: Python 3.9.0, pip 20.2.3, Docker version 19.03.8, Windows 10.

I was able to start the server with this little trick: I went on the file which produced the error, that is to say _[...]\Python\Python39\lib\site-packages\localstack\utils\common.py_ and commented these following lines:

```
line 4 #import pwd
line 5 #import grp
[...]

line 601 #uid = pwd.getpwnam(user).pw_uid
line 602 #gid = grp.getgrnam(user).gr_gid
```

I tried again and even though I still have some errors, the Localstack server started for me as you can see below:

```
C:\Users\[...]>localstack start

C:\Users\[...]>python C:\Users\[...]\AppData\Local\Programs\Python\Python39\Scripts\\localstack start
'uname' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
Traceback (most recent call last):
  File "C:\Users\[...]\AppData\Local\Programs\Python\Python39\Scripts\localstack", line 18, in <module>
    cli.main()
  File "C:\Users\[...]\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\utils\cli.py", line 130, in main
    bootstrap.load_plugins(scope=bootstrap.PLUGIN_SCOPE_COMMANDS)
  File "C:\Users\[...]\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\utils\analytics\profiler.py", line 153, in wrapped
    from localstack.utils.common import now_utc
  File "C:\Users\[...]\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\utils\common.py", line 4, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'

C:\Users\[...]>localstack start

C:\Users\[...]>python C:\Users\[...]\AppData\Local\Programs\Python\Python39\Scripts\\localstack start
'uname' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
LocalStack version: 0.11.6
Starting local dev environment. CTRL-C to quit.
ERROR: 'chmod -R 777 "C:\Users\0[...]~1\AppData\Local\Temp\localstack"': exit code 1; output: b"'chmod' n'est pas reconnu en tant que commande interne\r\nou externe, un programme ex\x82cutable ou un fichier de commandes.\r\n"
docker run -it -e TEST_AWS_ACCOUNT_ID="000000000000" -e LOCALSTACK_HOSTNAME="localhost" -e DEFAULT_REGION="us-east-1" --rm --privileged --name localstack_main -p 4566:4566 -p 4571:4571 -p 8080-8081:8080-8081  -v "C:\Users\0[...]~1\AppData\Local\Temp\localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="C:\Users\0[...]~1\AppData\Local\Temp\localstack" "localstack/localstack"
'uname' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
'uname' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
Waiting for all LocalStack services to be ready
2020-10-16 17:31:21,671 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-10-16 17:31:21,673 INFO supervisord started with pid 13
2020-10-16 17:31:22,677 INFO spawned: 'dashboard' with pid 19
2020-10-16 17:31:22,681 INFO spawned: 'infra' with pid 20
2020-10-16 17:31:22,694 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-10-16 17:31:22,695 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
LocalStack version: 0.11.6
Starting local dev environment. CTRL-C to quit.
2020-10-16 17:31:24,047 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting edge router (https port 4566)...
Starting mock ACM service on http port 4566 ...
2020-10-16T17:31:25:INFO:localstack.utils.analytics.profiler: Execution of "load_plugin_from_path" took 2503.1180381774902ms
2020-10-16T17:31:25:INFO:localstack.utils.analytics.profiler: Execution of "load_plugins" took 2503.3228397369385ms
2020-10-16T17:31:25:INFO:localstack.multiserver: Starting multi API server process on port 58705
[2020-10-16 17:31:25 +0000] [21] [INFO] Running on http://0.0.0.0:58705 (CTRL + C to quit)
2020-10-16T17:31:25:INFO:hypercorn.error: Running on http://0.0.0.0:58705 (CTRL + C to quit)
[2020-10-16 17:31:25 +0000] [21] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2020-10-16T17:31:25:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
Starting mock API Gateway service on http port 4566 ...
Starting mock CloudFormation service on http port 4566 ...
Starting mock CloudWatch service on http port 4566 ...
Starting mock DynamoDB service on http port 4566 ...
Starting mock DynamoDB Streams service on http port 4566 ...
Starting mock EC2 service on http port 4566 ...
Starting mock ES service on http port 4566 ...
Starting mock Firehose service on http port 4566 ...
Starting mock IAM service on http port 4566 ...
Starting mock STS service on http port 4566 ...
Starting mock Kinesis service on http port 4566 ...
Starting mock KMS service on http port 4566 ...
Waiting for all LocalStack services to be ready
Starting mock Lambda service on http port 4566 ...
Starting mock CloudWatch Logs service on http port 4566 ...
Starting mock Redshift service on http port 4566 ...
Starting mock Route53 service on http port 4566 ...
Starting mock S3 service on http port 4566 ...
Starting mock Secrets Manager service on http port 4566 ...
Starting mock SES service on http port 4566 ...
Starting mock SNS service on http port 4566 ...
Starting mock SQS service on http port 4566 ...
Starting mock SSM service on http port 4566 ...
Starting mock Cloudwatch Events service on http port 4566 ...
Starting mock StepFunctions service on http port 4566 ...
Waiting for all LocalStack services to be ready
Ready.
2020-10-16T17:31:36:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 10164.353132247925ms
```

Hope that this can help you as well with your issue :)

Best regards,

Nicolas

**Comment by whummer** [comment]
Thanks for reporting @chrillejb @nicotk . This should be fixed in #3118. Can you please try installing the latest version `0.12.0` of the `localstack` pip package? Please report here if the problem persists. Thanks

**Comment by chrillejb** [comment]
A fresh install of `0.12.0` gives me the following instead:

```
ModuleNotFoundError: No module named 'grp'
```

Looking back at @nicotk's answer I think it's easy to see why 😉

Commenting the line

```py
import grp
```

in common.py works for now, but I think it would be nice if #3118 could solve this as well 😃

Thx for the awesome work!

**Comment by 00005555** [comment]
Just go to the file C:\Users\Fixxo\AppData\Local\Programs\Python\Python310\Lib\site-packages\binwalk-2.3.3-py3.10.egg\binwalk\modules\extractor.py , open with Notepad and DELETE the 7 LINE  " import pwd " SAVE AND DONE

OR

  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\utils\common.py", 
and delete de 4 line " import pwd " SAVE AND DONE
