### ISSUE TITLE
Failed to unmarshall event using KCL 2.0/Java and Latest Localstack

### ISSUE THREAD

**Issue by neilmatthewlott** [localstack/localstack#3134]
# Type of request: This is a ...
[X ] bug report
[ ] feature request

# Detailed description
Using Java 1.8 / KCL 2.0 / Localstack-light (0.12.0) as a Docker Image -- this is the latest I'm seeing the following exception when attempting to marshall an event that was put a on a Kinesis.

amazon-kinesis-producer-version 0.14.1
amazon-kinesis-client-version 2.3.0
aws-core-version 2.15.8

Note the exception is occurring with ApproximateArrivalTimestamp field.

2020-10-19 17:19:51.397  ERROR 8032 --- [0000000000-0000] s.a.k.r.p.PrefetchRecordsPublisher       : practice-neil2:shardId-000000000000 :  Exception thrown while fetching records from Kinesis

software.amazon.awssdk.core.exception.SdkClientException: Unable to parse date : 1.603149588042E9
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98) ~[sdk-core-2.15.8.jar:na]
	at software.amazon.awssdk.protocols.core.StringToInstant.lambda$safeParseDate$0(StringToInstant.java:77) ~[protocol-core-2.15.8.jar:na]
	at software.amazon.awssdk.protocols.core.StringToInstant.convert(StringToInstant.java:56) ~[protocol-core-2.15.8.jar:na]
	at software.amazon.awssdk.protocols.core.StringToInstant.convert(StringToInstant.java:32) ~[protocol-core-2.15.8.jar:na]
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller$SimpleTypeJsonUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:161) ~[aws-json-protocol-2.15.8.jar:na]
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshallStructured(JsonProtocolUnmarshaller.java:213) ~[aws-json-protocol-2.15.8.jar:na]
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshallStructured(JsonProtocolUnmarshaller.java:115) ~[aws-json-protocol-2.15.8.jar:na]
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.lambda$unmarshallList$2(JsonProtocolUnmarshaller.java:144) ~[aws-json-protocol-2.15.8.jar:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_265]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[na:1.8.0_265]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_265]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_265]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_265]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_265]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[na:1.8.0_265]
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshallList(JsonProtocolUnmarshaller.java:146) ~[aws-json-protocol-2.15.8.jar:na]
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshallStructured(JsonProtocolUnmarshaller.java:213) ~[aws-json-protocol-2.15.8.jar:na]
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:199) ~[aws-json-protocol-2.15.8.jar:na]
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:169) ~[aws-json-protocol-2.15.8.jar:na]
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:82) ~[aws-json-protocol-2.15.8.jar:na]
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:36) ~[aws-json-protocol-2.15.8.jar:na]
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonResponseHandler.handle(AwsJsonResponseHandler.java:44) ~[aws-json-protocol-2.15.8.jar:na]
	at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.lambda$handle$0(MetricCollectingHttpResponseHandler.java:52) ~[sdk-core-2.15.8.jar:na]
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:64) ~[sdk-core-2.15.8.jar:na]
	at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.handle(MetricCollectingHttpResponseHandler.java:52) ~[sdk-core-2.15.8.jar:na]
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$resultTransformationResponseHandler$6(BaseClientHandler.java:246) ~[sdk-core-2.15.8.jar:na]
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:88) ~[sdk-core-2.15.8.jar:na]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[na:1.8.0_265]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[na:1.8.0_265]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[na:1.8.0_265]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[na:1.8.0_265]
	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:129) ~[sdk-core-2.15.8.jar:na]
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:179) ~[netty-nio-client-2.15.8.jar:na]
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$500(ResponseHandler.java:69) ~[netty-nio-client-2.15.8.jar:na]
	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:295) ~[netty-nio-client-2.15.8.jar:na]
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.complete(HandlerPublisher.java:447) ~[netty-nio-client-2.15.8.jar:na]
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.handlerRemoved(HandlerPublisher.java:435) ~[netty-nio-client-2.15.8.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:946) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:477) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:362) ~[netty-nio-client-2.15.8.jar:na]
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:223) ~[netty-nio-client-2.15.8.jar:na]
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:199) ~[netty-nio-client-2.15.8.jar:na]
	at software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:173) ~[netty-nio-client-2.15.8.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at software.amazon.awssdk.http.nio.netty.internal.LastHttpContentHandler.channelRead(LastHttpContentHandler.java:43) ~[netty-nio-client-2.15.8.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) ~[netty-handler-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[netty-codec-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_265]
Caused by: java.lang.NumberFormatException: For input string: "1.603149588042E9"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_265]
	at java.lang.Long.parseLong(Long.java:589) ~[na:1.8.0_265]
	at java.lang.Long.parseLong(Long.java:631) ~[na:1.8.0_265]
	at software.amazon.awssdk.utils.DateUtils.parseUnixTimestampMillisInstant(DateUtils.java:146) ~[utils-2.15.8.jar:na]
	at software.amazon.awssdk.protocols.core.StringToInstant.lambda$safeParseDate$0(StringToInstant.java:72) ~[protocol-core-2.15.8.jar:na]

## Expected behavior
Event should be unmarshalled without an exception.

## Actual behavior
Notice that when using AWS-Kinesis (not localstack) 
the value of the ApproximateArrivalTimestamp = ApproximateArrivalTimestamp -> {software.amazon.awssdk.protocols.json.internal.dom.SdkScalarNode@20220} ""1603152823565""

whereas with Localstack the value is this

1.603149588042E9

...

# Steps to reproduce
## Command used to start LocalStack
Started in Docker Container
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Note, I'm using the new AWS client libs (the below works with AWS)

DefaultAWSCredentialsProviderChain defaultAWSCredentialsProviderChain = new DefaultAWSCredentialsProviderChain();
                                StaticCredentialsProvider awsCredentials = StaticCredentialsProvider.create(
                                        AwsBasicCredentials.create(defaultAWSCredentialsProviderChain.getCredentials().getAWSAccessKeyId(),
                                                defaultAWSCredentialsProviderChain.getCredentials().getAWSSecretKey()));

```
                            SdkAsyncHttpClient nettyNioAsyncHttpClient = NettyNioAsyncHttpClient
                                    .builder().maxConcurrency(Integer.MAX_VALUE)
                                    .protocol(Protocol.HTTP1_1)
                                    .buildWithDefaults(
                                            AttributeMap
                                                    .builder()
                                                    .put(
                                                            SdkHttpConfigurationOption.TRUST_ALL_CERTIFICATES,
                                                            Boolean.TRUE
                                                    )
                                                    .build()
                                    );
```

```
                            ClientOverrideConfiguration.Builder tracingInterceptorBuilder = ClientOverrideConfiguration.builder()
                                    .addExecutionInterceptor(new TracingInterceptor());
                            ClientOverrideConfiguration tracingInterceptor = tracingInterceptorBuilder.build();
```

```
                            KinesisAsyncClient kinesisAsyncClient = KinesisAsyncClient
                                    .builder()
                                    .endpointOverride(
                                            URI.create(url)
                                    )
                                    .region(Region.US_EAST_1)
                                    .httpClient(nettyNioAsyncHttpClient)
                                    .credentialsProvider(awsCredentials)
                                    .overrideConfiguration(tracingInterceptor)
                                    .build();
```

...

![](https://user-images.githubusercontent.com/1881815/96524883-b0486300-1236-11eb-8f04-b4e222d6dfaa.png)
![](https://user-images.githubusercontent.com/1881815/96524890-b4748080-1236-11eb-80d8-8c030eeb475e.png)

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-294) by [Unito](https://www.unito.io/learn-more)

**Comment by neilmatthewlott** [comment]
Hey All, it looks like this is a straightforward fix to localstack/utils/commons.py and changing the method 

epoch_timestamp to be this:

def epoch_timestamp():
    return time.time_ns() // 1000000

Given that the kinesis_listener.py calls this method from here

'approximateArrivalTimestamp': epoch_timestamp(),

And that the kinesis_listener.py is the only one that calls this.

Would you be able to verify this fix?

**Comment by joroKr21** [comment]
Is there a workaround in the meantime?

**Comment by neilmatthewlott** [comment]
We can close this -- this was an issue on our side.

We had to do this in our java code....

System.setProperty("aws.cborEnabled", "false");
LOGGER.info("END: Set aws.cborEnabled to [{}]", System.getProperty("aws.cborEnabled"));

#otherwise when you use localstack you will get this message from your consumer
java.lang.NumberFormatException: For input string: "1.60530539166E9"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_265]

**Comment by joroKr21** [comment]
CBOR is supported though: https://github.com/localstack/localstack/releases/tag/v0.12.0

**Comment by joroKr21** [comment]
Thanks for the workaround though. For people migrating from SDK 1.x here are more details:
https://docs.aws.amazon.com/sdk-for-java/latest/migration-guide/client-updates.html

**Comment by neilmatthewlott** [comment]
How do I enable localstack to work with CBOR?  I've been using the latest version of localstack and the above is what happens.

**Comment by pinzon** [comment]
@neilmatthewlott 
CBOR is enable by the default in AWS SDK.

@joroKr21 
```
Caused by: java.lang.NumberFormatException: For input string: "1.603149588042E9"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_265]
at java.lang.Long.parseLong(Long.java:589) ~[na:1.8.0_265]
at java.lang.Long.parseLong(Long.java:631) ~[na:1.8.0_265]
at software.amazon.awssdk.utils.DateUtils.parseUnixTimestampMillisInstant(DateUtils.java:146) ~[utils-2.15.8.jar:na]
at software.amazon.awssdk.protocols.core.StringToInstant.lambda$safeParseDate$0(StringToInstant.java:72) ~[protocol-core-2.15.8.jar:na]
```
There's still work in progress to deal with the new Date format introduced in AWS SDK v2 you could look into the PR #3263

**Comment by joroKr21** [comment]
But is KCL 2.0 working for you? I'm having trouble configuring it in a way that it would work with localstack.
