### ISSUE TITLE
Class not found exception - triggering lambda function when it is created with zip file

### ISSUE THREAD

**Issue by dingwenxiao** [localstack/localstack#3138]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
1) In lambda function, it receives dynamodb events and sends message to sqs.

2) Compress lambda function into zip file and uploading the zip file to s3.

3) Creating dynamodb table, Sqs queue; creating lambda function and lambda function source mapping.

4) Saving data into the dynamodb table.

Notes:the lambda function doesn't work when it is created with zip file, but works on jar file. It turns out it is irrelevant to s3, since I created it directly using zip without uploading to s3, and I got the same error.

## Expected behavior
Sqs queue receives message.
...

## Actual behavior
START RequestId: 37dfd824-313d-1456-a980-c75da4c213d4 Version: $LATEST
localstack_main | > java.lang.ClassNotFoundException
localstack_main | > Class not found: com.test.Handler
localstack_main | > java.lang.ClassNotFoundException: com.test.Handler
localstack_main | > 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

...

# Steps to reproduce
1) In lambda function, it receives dynamodb events and sends message to sqs.

```
package com.test;

import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.DynamodbEvent;
public class Handler implements RequestHandler<DynamodbEvent, String> {
    @Override
    public String handleRequest(final DynamodbEvent dynamodbEvent, final Context context) {
        LambdaLogger logger = context.getLogger();
        String response = new String("200 OK");
        logger.log("ENVIRONMENT VARIABLES: " + System.getenv());
        // process event
        logger.log("EVENT: " + dynamodbEvent);
        logger.log("EVENT TYPE: " + dynamodbEvent.getClass().toString());
        System.out.println("test lambda");
        String localstackHost = System.getenv("LOCALSTACK_HOSTNAME");
        AmazonSQS amazonSQS = AmazonSQSClientBuilder.standard().withEndpointConfiguration(
                new AwsClientBuilder.EndpointConfiguration("http://" + localstackHost + ":4566",
                        "us-west-2")).build();
        String queueUrl = null;
        for (DynamodbEvent.DynamodbStreamRecord record : dynamodbEvent.getRecords()) {
            logger.log(record.getEventID());
            logger.log(record.getEventName());
            logger.log(record.getDynamodb().toString());
            queueUrl = amazonSQS.getQueueUrl("Verification").getQueueUrl();
            logger.log("queueUrl " + queueUrl);
            amazonSQS.sendMessage(new SendMessageRequest(queueUrl, "gogogo"));
        }
        return response;
    }

```

2) Compress lambda function into zip file and uploading the zip file to s3.

```
awslocal --endpoint-url="http://localhost:4566" s3 mb s3://test
awslocal --endpoint-url="http://localhost:4566" s3 cp /Users/test/Documents/projects/test_lambda-1.0-SNAPSHOT.zip s3://test

```

3) Creating dynamodb table, Sqs queue; creating lambda function and lambda function source mapping.

```
awslocal dynamodb create-table \
    --table-name Music \
    --attribute-definitions \
        AttributeName=Artist,AttributeType=S \
        AttributeName=SongTitle,AttributeType=S \
    --key-schema \
        AttributeName=Artist,KeyType=HASH \
        AttributeName=SongTitle,KeyType=RANGE \
--provisioned-throughput \
        ReadCapacityUnits=10,WriteCapacityUnits=5 \
--endpoint-url http://localhost:4566
```

`awslocal sqs create-queue --queue-name Verification --endpoint-url http://localhost:4566
`

```
awslocal lambda create-function \
--function-name testLambda2 \
--code S3Bucket=test,S3Key=test_lambda-1.0-SNAPSHOT.zip \
--handler com.test.Handler \
--runtime 'java8' \
--role a \
--endpoint-url http://localhost:4566
```

```
awslocal lambda create-event-source-mapping \
--function-name testLambda2 \
--event-source arn:aws:dynamodb:us-east-1:000000000000:table/Music \
--batch-size 10 \
--starting-position TRIM_HORIZON \
--endpoint-url http://localhost:4566
```

4) Saving data into the dynamodb table.

5) Result:

```
localstack_main | 2020-10-20T16:25:40:INFO:localstack.services.awslambda.lambda_executors: Determined main container target IP: 172.17.0.2
localstack_main | 2020-10-20T16:25:40:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: CONTAINER_ID="$(docker create -i   -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY"   --rm "lambci/lambda:java8" "com.test.Handler")";docker cp "/tmp/localstack/zipfile.31f1efce/." "$CONTAINER_ID:/var/task"; docker start -ai "$CONTAINER_ID";
localstack_main | 2020-10-20T16:25:43:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:testLambda2 result / log output:
localstack_main | {"errorMessage":"java.lang.ClassNotFoundException\nClass not found: com.test.Handler\njava.lang.ClassNotFoundException: com.test.Handler\n\tat java.net.URLClassLoader.findClass(URLClassLoader.java:382)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:424)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:357)\n\tat java.lang.Class.forName0(Native Method)\n\tat java.lang.Class.forName(Class.java:348)\n"}
localstack_main | > START RequestId: 37dfd824-313d-1456-a980-c75da4c213d4 Version: $LATEST
localstack_main | > java.lang.ClassNotFoundException
localstack_main | > Class not found: com.test.Handler
localstack_main | > java.lang.ClassNotFoundException: com.test.Handler
localstack_main | > 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
localstack_main | > 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
localstack_main | > 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
localstack_main | > 	at java.lang.Class.forName0(Native Method)
localstack_main | > 	at java.lang.Class.forName(Class.java:348)
localstack_main | > 
localstack_main | > END RequestId: 37dfd824-313d-1456-a980-c75da4c213d4
localstack_main | > REPORT RequestId: 37dfd824-313d-1456-a980-c75da4c213d4	Init Duration: 523.75 ms	Duration: 16.11 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 52 MB	
```

## Command used to start LocalStack
`TMPDIR=/private$TMPDIR DEBUG=1 docker-compose up
`...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-297) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @dingwenxiao - can you please share your compiled Lambda zip file, to help us reproduce this issue? Thanks for your help

**Comment by whummer** [comment]
Closing due to inactivity - please feel free to re-open (with details of your compiled Lambda zip file) if the problem persists. Thanks!
