### ISSUE TITLE
Unable to execute Lambda - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by TheGeekPharaoh** [localstack/localstack#3140]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

Environment:  Docker v19.03.12, docker-compose v1.27.2, macOS Catalina

I've created a simple Lambda function to listen to DynamoDB stream events and deployed it successfully to Localstack.  When an event triggers it, however, the call falls with a number of exceptions.  I am starting localstack using Docker and docker-compose.  The stack trace is below:

```
localstack_1  | ERROR: 'docker inspect -f '{{ .Name }}' 4086ae693003': exit code 1; output: b'\nCannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n'
localstack_1  | ERROR: 'docker inspect -f '{{ .Name }}' 4086ae693003': exit code 1; output: b'\nCannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n'
localstack_1  | 2020-10-20T18:32:51:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:DynamodbEventHandlerNative: Command 'docker inspect -f '{{ .Name }}' 4086ae693003' returned non-zero exit status 1. Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 108, in get_main_endpoint_from_container
localstack_1  |     DOCKER_MAIN_CONTAINER_IP = bootstrap.get_main_container_ip()
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 200, in get_main_container_ip
localstack_1  |     container_name = get_main_container_name()
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 208, in get_main_container_name
localstack_1  |     return run(cmd).strip().lstrip('/')
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 609, in run
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 569, in run
localstack_1  |     output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
localstack_1  |   File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
localstack_1  |     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
localstack_1  |   File "/usr/lib/python3.8/subprocess.py", line 512, in run
localstack_1  |     raise CalledProcessError(retcode, process.args,
localstack_1  | subprocess.CalledProcessError: Command 'docker inspect -f '{{ .Name }}' 4086ae693003' returned non-zero exit status 1.
localstack_1  | 
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  | 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 541, in run_lambda
localstack_1  |     result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 173, in execute
localstack_1  |     return do_execute()
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 165, in do_execute
localstack_1  |     return _run(func_arn=func_arn)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 145, in wrapped
localstack_1  |     result = func(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 158, in _run
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 146, in _run
localstack_1  |     result = self._execute(func_arn, func_details, event, context, version)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 256, in _execute
localstack_1  |     main_endpoint = get_main_endpoint_from_container()
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 111, in get_main_endpoint_from_container
localstack_1  |     container_name = bootstrap.get_main_container_name()
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 208, in get_main_container_name
localstack_1  |     return run(cmd).strip().lstrip('/')
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 609, in run
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 569, in run
localstack_1  |     output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
localstack_1  |   File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
localstack_1  |     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
localstack_1  |   File "/usr/lib/python3.8/subprocess.py", line 512, in run
localstack_1  |     raise CalledProcessError(retcode, process.args,
localstack_1  | subprocess.CalledProcessError: Command 'docker inspect -f '{{ .Name }}' 4086ae693003' returned non-zero exit status 1.
localstack_1  | 

```
## Command used to start LocalStack

The relevant portion of my docker-compose.yml file:

```
    localstack:
        image: localstack/localstack-full
        privileged: true
        ports:
          - 4566:4566
        environment:
          - LAMBDA_EXECUTOR=docker
          - DOCKER_HOST=unix:///var/run/docker.sock
          - SERVICES=s3,dynamodb,dynamodbstreams,secretsmanager,sns,sqs,lambda
        #volumes:
          - /tmp:/tmp/localstack
          - /var/run/docker.sock:/var/run/docker.sock


```

**Comment by soulpainter** [comment]
I am also having this issue and unsure exactly what to do about it. Lots of random info on the web but nothing concrete that works.

**Comment by shenie** [comment]
‘  #volumes:’ you should remove the ‘#’ char

**Comment by TheGeekPharaoh** [comment]
@shenie shit.  You may be right.  I can't imagine how I missed that.  I'll make the change and run it again.

**Comment by TheGeekPharaoh** [comment]
Okay, I got past that issue.  Now I'm seeing an error that I believe is related to the development framework I'm using.  Closing.  Thanks for your help on my dumb mistake :)

**Comment by satish2832** [comment]
What is issue here ?
