### ISSUE TITLE
Localstack java lambda functions failing with dynamodb stream event triggers

### ISSUE THREAD

**Issue by hewe** [localstack/localstack#3157]
# Type of request: This is a ...
[X] bug report
[ ] feature request

# Detailed description
Java based lambda functions configured for dynamodb stream events are failing when run under localstack. The logs from the lambda function shows this particular error:

```
$ aws --endpoint-url=http://localhost:4566 logs tail /aws/lambda/localstack-issue
2020-10-22T20:59:53.926000+00:00 2020/10/22/[LATEST]2eecaed2 Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/services/dynamodbv2/model/OperationType
2020-10-22T20:59:53.933000+00:00 2020/10/22/[LATEST]2eecaed2 	at cloud.localstack.lambda.DDBEventParser.parse(DDBEventParser.java:24)
2020-10-22T20:59:53.940000+00:00 2020/10/22/[LATEST]2eecaed2 	at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:103)
2020-10-22T20:59:53.947000+00:00 2020/10/22/[LATEST]2eecaed2 Caused by: java.lang.ClassNotFoundException: com.amazonaws.services.dynamodbv2.model.OperationType
2020-10-22T20:59:53.954000+00:00 2020/10/22/[LATEST]2eecaed2 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
2020-10-22T20:59:53.961000+00:00 2020/10/22/[LATEST]2eecaed2 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
2020-10-22T20:59:53.968000+00:00 2020/10/22/[LATEST]2eecaed2 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
2020-10-22T20:59:53.975000+00:00 2020/10/22/[LATEST]2eecaed2 	... 2 more
```

From what I have found so far is that the `cloud.localstack.lambda.DDBEventParser` is using older versions of the aws libraries and so the dependencies necessary for my lambda project may have mismatching classes with localstack when run under localstack docker container. My suspicion is that the dynamodb model classes have been moved to another package namespace in newer versions of `aws-lambda-java-events` library. It has been relocated to `com.amazonaws.services.lambda.runtime.events.models.dynamodb.OperationType`, so my guess the error has to do with this change. 

...

## Expected behavior
Lambda function should be processed successfully for dynamodb stream events. 
...

## Actual behavior
Lambda function is failing and does not reach to the handler code at all. 
...

# Steps to reproduce
I have created a code sample that produces this error, please see this code repo: https://github.com/hewe/localstack-issue

## Command used to start LocalStack
Start localstack using docker-compose.yml file of the following:

```
version: '3.8'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: "localstack/localstack:0.11.6"
    network_mode: "bridge"
    ports:
      - "4566-4587:4566-4587"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES-dynamodb, dynamodbstreams, lambda, logs}
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker-reuse }
      - LAMBDA_REMOTE_DOCKER=false
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - DEFAULT_REGION=us-east-1
      - AWS_CBOR_DISABLE=true
      - USE_SSL=false
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Localstack interaction command used:

```
aws --endpoint-url=http://localhost:4566 lambda create-function \
    --region us-east-1 \
    --function-name localstack-issue \
    --runtime java11 \
    --handler localstack.issue.Handler \
    --memory-size 512 \
    --zip-file fileb://build/libs/localstack-issue-all.jar \
    --timeout 60 \
    --role arn:aws:iam::123456:role/irrelevant

aws --endpoint-url=http://localhost:4566 lambda invoke \
    --function-name localstack-issue \
    --cli-binary-format raw-in-base64-out --payload file://input.json response.json

cat response.json

aws --endpoint-url=http://localhost:4566 logs tail /aws/lambda/localstack-issue
```

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
package localstack.issue;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.DynamodbEvent;

public class Handler implements RequestHandler<DynamodbEvent, String> {
    @Override
    public String handleRequest(DynamodbEvent dynamodbEvent, final Context context) {
        LambdaLogger logger = context.getLogger();
        logger.log("Event: " + dynamodbEvent);
        logger.log("Yay issue is fixed!");
        return "Thank you";
    }
}
```

AWS JAVA SDK V2 libs: 

```
    implementation("com.amazonaws:aws-lambda-java-core:1.2.1")
    implementation("com.amazonaws:aws-lambda-java-events:3.4.0")
    implementation("com.amazonaws:aws-lambda-java-events-sdk-transformer:2.0.6")
    implementation("software.amazon.awssdk:sdk-core:2.15.11")
    implementation("software.amazon.awssdk:dynamodb:2.15.11")
    implementation("software.amazon.awssdk:dynamodb-enhanced:2.15.11")
```

...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-301) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @hewe . This should be fixed in the meantime, as we have recently switched from our custom Java Lambda executor to using the [Lambci](https://github.com/lambci/docker-lambda) Docker images. Can you please pull the `latest` image and give it another try - please report here if the problem persists. Thanks
