### ISSUE TITLE
Not able to access S3 file from AWS SDK API in node js application

### ISSUE THREAD

**Issue by tilakbhanu** [localstack/localstack#3162]
# Type of request:

[ ] bug report

# Detailed description
I have created S3 bucket and file from localstack command line. I am trying to access the same file from node js application using AWS SDK. 

...

## Expected behavior
It should list objects
...

## Actual behavior
UnhandledPromiseRejectionWarning: UnknownEndpoint: Inaccessible host: `mytestbucket1.localhost'. This service may not be available in the `us-east-1' region.
    at Request.ENOTFOUND_ERROR (/Users/bhanubalaji/Printdeal/repoistories/authentication/code/node_modules/aws-sdk/lib/event_listeners.js:507:46)
    at Request.callListeners (/Users/bhanubalaji/Printdeal/repoistories/authentication/code/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/bhanubalaji/Printdeal/repoistories/authentication/code/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/bhanubalaji/Printdeal/repoistories/authentication/code/node_modules/aws-sdk/lib/request.js:688:14)
    at ClientRequest.error (/Users/bhanubalaji/Printdeal/repoistories/authentication/code/node_modules/aws-sdk/lib/event_listeners.js:339:22)
    at ClientRequest.<anonymous> (/Users/bhanubalaji/Printdeal/repoistories/authentication/code/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:486:12)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)

# Steps to reproduce
Code is placed.
## Command used to start LocalStack
localstack start
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
AWS.config.update({
        region: "us-east-1",
        endpoint: "http://localhost:4566"
      });
    const s3 = new AWS.S3({ apiVersion: '2006-03-01' });
    // Create the parameters for calling listObjects
    var bucketParams = {
      Bucket: 'mytestbucket1',
      //Key: 'ValidIPAddresses.txt'
    };
    
    // Call S3 to obtain a list of the objects in the bucket
    var data = await s3.listObjects(bucketParams).promise();
...

**Comment by tilakbhanu** [comment]
I was able to make it work in node js by setting s3ForcePathStyle: true : here is an example 
AWS.config.update({
          region: "us-east-1",
          endpoint: "http://localhost:4566",
          s3ForcePathStyle: true
        });
