### ISSUE TITLE
S3: Crash when returning 412 errors

### ISSUE THREAD

**Issue by gilbsgilbs** [localstack/localstack#3168]
# Type of request: This is a ...

- [x] bug report
- [ ] feature request

# Detailed description

When S3 returns a 412 HTTP status code (Precondition Failed), localstack abruptly closes the connection and shows the following traceback in logs:

```
[2020-10-25 17:16:14 +0000] [21] [ERROR] Error in ASGI Framework
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/context.py", line 28, in _handle
    await invoke_asgi(app, scope, receive, send)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/utils.py", line 219, in invoke_asgi
    await app(scope, receive, send)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/quart/app.py", line 2068, in __call__
    await self.asgi_app(scope, receive, send)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/quart/app.py", line 2091, in asgi_app
    await asgi_handler(receive, send)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/quart/asgi.py", line 31, in __call__
    _raise_exceptions(done)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/quart/asgi.py", line 240, in _raise_exceptions
    raise task.exception()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/quart/asgi.py", line 79, in handle_request
    await asyncio.wait_for(self._send_response(send, response), timeout=timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/quart/asgi.py", line 95, in _send_response
    await send({"type": "http.response.body", "body": b"", "more_body": False})
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/protocol/http_stream.py", line 157, in app_send
    await self.send(EndBody(stream_id=self.stream_id))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/protocol/h11.py", line 130, in stream_send
    await self._send_h11_event(h11.EndOfMessage())
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/protocol/h11.py", line 224, in _send_h11_event
    data = self.connection.send(event)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/h11/_connection.py", line 469, in send
    data_list = self.send_with_data_passthrough(event)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/h11/_connection.py", line 502, in send_with_data_passthrough
    writer(event, data_list.append)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/h11/_writers.py", line 79, in __call__
    self.send_eom(event.headers, write)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/h11/_writers.py", line 102, in send_eom
    raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
```

## Expected behavior

Localstack should respond with a valid body and not crash.

## Actual behavior

Connection is closed with a traceback shown in localstack logs.

# Steps to reproduce

- Call S3 with something expected to result in a 412 error (e.g. `getObject` with `If-Match` set to a wrong ETag).
- See localstack logs.

boto3 doesn't seem to crash to this for some reason. Doing the same with the Go SDK makes the client crash.

## Command used to start LocalStack

`docker run --rm -it -e LOCALSTACK_SERVICES=s3 -p 3000:4566 --name localstack localstack/localstack`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```python
import uuid
import boto3

client = boto3.client('s3', endpoint_url="http://localhost:4566")

bucket = str(uuid.uuid4())
client.create_bucket(Bucket=bucket)
client.put_object(Bucket=bucket, Key="foo", Body=b'{"foo": "bar"}')

# this line makes localstack crash:
client.get_object(Bucket=bucket, Key="foo", IfMatch='"not good etag"')
```

**Comment by whummer** [comment]
Thanks for reporting @gilbsgilbs . This should be fixed in the meantime - a small integration test has been added in #3169 . Can you please pull the `latest` image and give it another try? Please report here if the problem persists. Thanks
