### ISSUE TITLE
localstack start reports Ready, exits with SUCCESS code and disappears

### ISSUE THREAD

**Issue by strk** [localstack/localstack#3182]
Localstack 0.10.8 fails to start, but says it started fine...

```
localstack) runner@fv-az29:~/work/bde-processor-deployment/bde-processor-deployment$ /opt/localstack/bin/localstack -d start --host
Starting local dev environment. CTRL-C to quit.
Unable to register plugins: No module named 'docker'
2020-10-27T12:11:13:WARNING:bootstrap.py: Unable to load plugins from file /opt/localstack/lib/python3.6/site-packages/localstack/plugins.py: No module named 'docker'
2020-10-27T12:11:13:INFO:localstack.services.install: Downloading and installing local DynamoDB server. This may take some time.
2020-10-27T12:11:13:INFO:localstack.services.install: Downloading and installing local Step Functions server. This may take some time.
2020-10-27T12:11:13:INFO:localstack.services.install: Downloading and installing local Kinesis server. This may take some time.
2020-10-27T12:11:13:INFO:localstack.services.install: Downloading and installing local ElasticMQ server. This may take some time.
2020-10-27T12:11:13:INFO:localstack.services.install: Downloading and installing local Elasticsearch server. This may take some time.
2020-10-27T12:11:13:INFO:localstack.services.install: Downloading and installing local KMS server. This may take some time.
install elasticsearch-plugin analysis-icu
install elasticsearch-plugin ingest-attachment
install elasticsearch-plugin analysis-kuromoji
install elasticsearch-plugin mapper-murmur3
install elasticsearch-plugin mapper-size
install elasticsearch-plugin analysis-phonetic
install elasticsearch-plugin analysis-smartcn
install elasticsearch-plugin analysis-stempel
install elasticsearch-plugin analysis-ukrainian
Ready.
(localstack) runner@fv-az29:~/work/bde-processor-deployment/bde-processor-deployment$ echo $?
0
(localstack) runner@fv-az29:~/work/bde-processor-deployment/bde-processor-deployment$ sudo netstat -tnl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 127.0.0.1:46705         0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
(localstack) runner@fv-az29:~/work/bde-processor-deployment/bde-processor-deployment$ ps xa | grep local
26550 pts/0    S+     0:00 grep local
```

**Comment by strk** [comment]
Python version is 3.6.9

**Comment by canpan14** [comment]
Try installing docker first?
`sudo pip install docker`

This error concerns me `Unable to register plugins: No module named 'docker'`

**Comment by strk** [comment]
I'll try and report outcome, but what concerns me the most is reading the `Ready` label at the end, when in fact localstack is NOT ready. It would greatly help to have failures properly reported, and their reasons

**Comment by strk** [comment]
Installing docker module moves forward some more:
```
(localstack) runner@fv-az54:~/work/bde-processor-deployment/bde-processor-deployment$ /opt/localstack/bin/localstack start --host                        
2020-10-27T12:52:14:DEBUG:bootstrap.py: Unable to load plugins from module localstack_ext: module 'localstack.config' has no attribute 'is_env_true'
Starting local dev environment. CTRL-C to quit.                                                                                                          
2020-10-27T12:52:16:DEBUG:bootstrap.py: Unable to load plugins from module localstack_ext: module 'localstack.config' has no attribute 'is_env_true'
Starting mock CloudWatch (http port 4566)...                                                                                                             
2020-10-27T12:52:16:INFO:localstack.multiserver: Starting multi API server process on port 51492
Starting mock S3 (http port 4566)...                                                                                                                     
Starting mock SNS (http port 4566)...
2020-10-27 12:52:17,917:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
2020-10-27 12:52:17,917:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
2020-10-27 12:52:17,917:API:  * Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
```

It then reports a new WARNING:
```
2020-10-27T12:52:17:WARNING:bootstrap.py: Thread run method <function start_api_server_locally.<locals>.thread_func at 0x7f4565c6ca60>(None) failed: Traceback (most recent call last):                                                                                                                             File "/opt/localstack/lib/python3.6/site-packages/localstack/utils/bootstrap.py", line 442, in run
    self.func(self.params)                                                                                                                                 File "/opt/localstack/lib/python3.6/site-packages/localstack/utils/server/multiserver.py", line 48, in thread_func
    return moto_server.main([api, '-p', str(port), '-H', constants.BIND_HOST])
  File "/opt/localstack/lib/python3.6/site-packages/moto/server.py", line 298, in main
    ssl_context=ssl_context,
  File "/opt/localstack/lib/python3.6/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/opt/localstack/lib/python3.6/site-packages/werkzeug/serving.py", line 1005, in inner
    fd=fd,
  File "/opt/localstack/lib/python3.6/site-packages/werkzeug/serving.py", line 848, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/opt/localstack/lib/python3.6/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
```

And eventually fails with:
```
OSError: [Errno 98] Address already in use
```

I don't know why it tries to listen on the same port (4566) multiple times

**Comment by canpan14** [comment]
Might have something stuck on that port from prior attempts. Trying killing everything on that port.

`lsof -t -i tcp:4566 | xargs kill`

**Comment by strk** [comment]
I read from CHANGELOG that starting with localstack 0.11.5+ the same tcp port is used, but I'm running 0.10.8 so I would not expect this. Which component is actually responsible for deciding on which ports to open for which service ?

There's nothing listening on port 4566 prior to the `locastack start` call, it's all done internally by localstack itself:
```
$ SERVICES=s3,cloudwatch,sns /opt/localstack/bin/localstack start --h
ost 2>&1 | tee /tmp/log 
2020-10-27T13:56:32:INFO:localstack.multiserver: Starting multi API server process on port 51492
Starting local dev environment. CTRL-C to quit.
Starting mock CloudWatch (http port 4566)...
Starting mock S3 (http port 4566)...
2020-10-27T13:56:33:ERROR:localstack.services.generic_proxy: Exception running proxy on port 4566: [Errno 98] Address already in use Traceback (most rece
nt call last):
  File "/opt/localstack/lib/python3.6/site-packages/localstack/services/generic_proxy.py", line 414, in run_cmd
    self.httpd = ThreadedHTTPServer((self.listen_host, self.port), GenericProxyHandler)
  File "/usr/lib/python3.6/socketserver.py", line 457, in __init__
    self.server_activate()
  File "/usr/lib/python3.6/socketserver.py", line 479, in server_activate
    self.socket.listen(self.request_queue_size)
OSError: [Errno 98] Address already in use

2020-10-27T13:56:33:ERROR:localstack.services.generic_proxy: Exception running proxy on port 4566: [Errno 98] Address already in use Traceback (most rece
nt call last):
  File "/opt/localstack/lib/python3.6/site-packages/localstack/services/generic_proxy.py", line 414, in run_cmd
    self.httpd = ThreadedHTTPServer((self.listen_host, self.port), GenericProxyHandler)
  File "/usr/lib/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

As I'm requesting 3 services, it successfully starts the first and fails when attempting to start the second (finding the port already used by the previous one!).

Limiting the call to a single service works fine.

**Comment by canpan14** [comment]
My mistake, I didn't look what version you are running on. What does your docker-compose look like? You might need to set the ports you want each service to run on. I personally haven't used a version that old.

**Comment by strk** [comment]
I'm not specifying any port, and not using docker-compose.
It looks like USE_LEGACY_PORTS=1 fixes it, I'm just surprised to see this in 0.10.8

**Comment by strk** [comment]
In any case I think this ticket should stay open until localstack exits with a FAILURE exit code when this happens

**Comment by canpan14** [comment]
You should close this ticket, something like that would be a feature request or a bug if it was expected that would happen. Also it's an issue with an older version. If you want to open a new ticket with that intention, that would make more sense.

**Comment by strk** [comment]
Ok, will open a new ticket shall I hit this with a newer version. Thanks for your support !
