### ISSUE TITLE
Runtime.HandlerNotFound

### ISSUE THREAD

**Issue by larose** [localstack/localstack#3185]
I get a `Runtime.HandlerNotFound` error when invoking a lambda function:

```
2020-10-27T22:06:10.894Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.HandlerNotFound","errorMessage":"index.main is undefined or not exported","stack":["Runtime.HandlerNotFound: index.main is undefined or not exported","    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1137:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)","    at Module.load (internal/modules/cjs/loader.js:985:32)","    at Function.Module._load (internal/modules/cjs/loader.js:878:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)","    at internal/main/run_main_module.js:17:47"]}
```

## Repro steps

Execute the workflow defined https://github.com/larose/localstack-lambda-handler-not-found

Logs: https://github.com/larose/localstack-lambda-handler-not-found/runs/1317629697?check_suite_focus=true

Relevant files:

`docker-compose.yml`:

```
version: "3"
services:
  localstack:
    image: localstack/localstack:0.12.1
    container_name: localstack
    ports:
      - 127.0.0.1:4566:4566
    environment:
      - DEBUG=1
      - LAMBDA_DOCKER_NETWORK=host
      - LAMBDA_EXECUTOR=docker
      - SERVICES=lambda
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

GitHub Actions script:

```
set -o xtrace

docker-compose up --build --detach localstack

zip lambda.zip index.js
unzip -l lambda.zip
unzip -c lambda.zip

sleep 10

aws --version
aws --endpoint http://localhost:4566 lambda create-function --function-name fn --runtime nodejs12.x --zip-file fileb://lambda.zip --handler index.main --role arn:aws:iam::123456:role/irrelevant
aws --endpoint http://localhost:4566 lambda get-function --function-name fn
aws --endpoint http://localhost:4566 lambda invoke --function-name fn --payload '[]' result.txt

cat result.txt
docker logs localstack
```

`index.js`:

```
exports.main = async function (event) {
  console.log(JSON.stringify(event, null, 2));
};
```

## Notes

It works on my machine™, but not in GitHub Actions. I'm probably missing something super obvious. Do you see why it fails?

**Comment by larose** [comment]
Explicitly setting `LAMBDA_REMOTE_DOCKER` to `true` fixed the issue, even though it should be true by default according to the readme.

**Comment by artamonovkirill** [comment]
@larose thanks for raising this and posting a solution - it saved me quite some time once I pinpointed the issue.

**Comment by artamonovkirill** [comment]
@whummer do you think it is worth mentioning the specific problem and the solution in the localstack documentation/README?
