### ISSUE TITLE
Terraform triggers NotImplementedError: The delete_resource_policy action has not been implemented

### ISSUE THREAD

**Issue by couling** [localstack/localstack#3195]
Bug report.

I get frequent errors with terraform when trying to modify a secret.  Concrete terraform script to follow.  Terraform gets stuck in a loop.  This seems to only happen when a resource get's modified. The only thing I've been able to do is tear down the docker container and start agian.

    aws_secretsmanager_secret.emulator_password: Still modifying.. [id=arn:aws:secretsmanager:eu-west-2:123456...secret:emulator-JqEOp, 30s elapsed]

And debug output from local stack keeps showing this:

```
local-aws_1       | 2020-10-28 22:56:20,853:API: 172.28.0.5 - - [28/Oct/2020 22:56:20] "POST / HTTP/1.1" 500 -
local-aws_1       | 2020-10-28 22:56:20,862:API: Error on request:
local-aws_1       | Traceback (most recent call last):
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
local-aws_1       |     execute(self.server.app)
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
local-aws_1       |     application_iter = app(environ, start_response)
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 168, in __call__
local-aws_1       |     return backend_app(environ, start_response)
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
local-aws_1       |     return self.wsgi_app(environ, start_response)
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
local-aws_1       |     response = self.handle_exception(e)
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
local-aws_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
local-aws_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
local-aws_1       |     reraise(exc_type, exc_value, tb)
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
local-aws_1       |     raise value
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
local-aws_1       |     response = self.full_dispatch_request()
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
local-aws_1       |     rv = self.handle_user_exception(e)
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
local-aws_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
local-aws_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
local-aws_1       |     reraise(exc_type, exc_value, tb)
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
local-aws_1       |     raise value
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
local-aws_1       |     rv = self.dispatch_request()
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
local-aws_1       |     return self.view_functions[rule.endpoint](**req.view_args)
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 151, in __call__
local-aws_1       |     result = self.callback(request, request.url, {})
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 202, in dispatch
local-aws_1       |     return cls()._dispatch(*args, **kwargs)
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 312, in _dispatch
local-aws_1       |     return self.call_action()
local-aws_1       |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 409, in call_action
local-aws_1       |     raise NotImplementedError(
local-aws_1       | NotImplementedError: The delete_resource_policy action has not been implemented
```

docker-compose
```
services:
  local-aws:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "8081:8080"
    environment:
      EDGE_PORT: 4566
      SERVICES: sqs, secretsmanager, sts
      DEFAULT_REGION: eu-west-2
      HOSTNAME: local-aws
      HOSTNAME_EXTERNAL: local-aws
      START_WEB: 0
      DEBUG: 1
    networks:
      - habitat-local-stack-network
```

Terraform script:
```
resource "aws_secretsmanager_secret_version" "emulator" {
  secret_id = aws_secretsmanager_secret.emulator_password.id
  secret_string = random_password.emulator_password.result
}

resource "aws_secretsmanager_secret" "emulator_password" {
    name = "emulator_pw"
}

resource "random_password" "emulator_password" {
  length = 16
  upper = true
  lower = true
  special = true
  number = true
}

terraform {
  required_providers {
    random = {
      source = "hashicorp/random"
    }
    time = {
      source = "hashicorp/time"
    }
    aws = {
      source = "hashicorp/aws"
    }
  }
  required_version = ">= 0.13"
}

```

**Comment by whummer** [comment]
Thanks for reporting @couling . This should be fixed in #3215 - can you please give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks
