### ISSUE TITLE
Cant list sqs queues with latest localstack version

### ISSUE THREAD

**Issue by DiesDasJenes** [localstack/localstack#3207]
Aloha,

[x] bug report
[ ] feature request

# Detailed description
I tried to create two simple sqs and make one them to a DLQ with the latest version of the localstack image. I can't get an answer from the localstack endpoint. I am on a Macbook Catalina version 10.15.7 and i use the awscli version aws-cli/2.0.61 Python/3.9.0 Darwin/19.6.0 source/x86_64 with the localstack image 0.11.6. I tried to access the health endpoint(http://localhost:4566/health) with chrome but this also didn't work. 

## Expected behavior
`
aws --endpoint-url=http://localhost:4566 --region=eu-central-1 --no-sign-request --no-paginate sqs list-queues
`
should return something like:
`
{
  ....aws queue information
}
`

## Actual behavior
```
aws --endpoint-url=http://localhost:4566 --region=eu-central-1 --no-sign-request --no-paginate sqs list-queues

Connection was closed before we received a valid response from endpoint URL: "http://localhost:4566/".
```

# Steps to reproduce
Use this docker compose file and just call a aws list-queue.

```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

## Command used to start LocalStack
```
docker-compose --file docker-compose-localstackyaml up --build --detach

CONTAINER ID        IMAGE                   COMMAND                  CREATED             STATUS              PORTS                                                                                                  NAMES
f1828d2cb029        localstack/localstack   "/usr/bin/supervisor…"   28 minutes ago      Up 28 minutes       0.0.0.0:4566->4566/tcp, 4567-4570/tcp, 0.0.0.0:4571->4571/tcp, 0.0.0.0:8080->8080/tcp, 4572-4583/tcp   localstack_main
```

Logs of the container seem to be fine:

```
2020-11-01 14:40:25,610 CRIT Supervisor running as root (no user in config file)
2020-11-01 14:40:25,612 INFO supervisord started with pid 1
2020-11-01 14:40:26,616 INFO spawned: 'dashboard' with pid 8
2020-11-01 14:40:26,618 INFO spawned: 'infra' with pid 9
(. .venv/bin/activate; bin/localstack web)
(. .venv/bin/activate; exec bin/localstack start)
Starting local dev environment. CTRL-C to quit.
2020-11-01T14:40:27:INFO:werkzeug:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
2020-11-01T14:40:27:INFO:werkzeug:  * Restarting with stat
2020-11-01T14:40:27:WARNING:werkzeug:  * Debugger is active!
2020-11-01 14:40:27,951 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-01 14:40:27,951 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-01T14:40:27:INFO:werkzeug:  * Debugger PIN: 230-653-362
Starting mock SQS (http port 4576)...
Ready.
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Try to list your queues:

```
aws --endpoint-url=http://localhost:4566 --region=eu-central-1 --no-sign-request --no-paginate sqs list-queues
```

or try to create a queue:

```
aws --endpoint-url=http://localhost:4566 --region=eu-central-1 --no-sign-request --no-paginate sqs create-queue --queue-name mcqueue
```

Thanks for any help on this. :)

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-70) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @DiesDasJenes . Please note that LocalStack relies on the `Authorization` header to be present in all requests (even if it contains only a dummy signature/credentials), in order to be able to determine the target service - since we're using a single entrypoint proxy service (on edge port `4566`) .

Therefore, it does not play well with the `aws` CLI's `--no-sign-request` flag. Is there a particular reason why you're using this flag?

We generally recommend setting dummy credentials (`AWS_ACCESS_KEY_ID=test`, `AWS_SECRET_ACCESS_KEY=test`) and then leaving out that flag. Hope that helps, please let us know if that doesn't work or if there are any other issues. Thanks

**Comment by DiesDasJenes** [comment]
Hi thanks for the answer.

Primarily I used the flag to avoid setting the dummy credentials. It was easier for me to create requests as didn't had to set the credentials through a script every time i would automate something. In my first post i used the latest localstack version and i did it again without the flag and get the same results on the same machine with the same setup. 

`
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test

aws --endpoint-url=http://localhost:4576 --region=eu-central-1 --no-paginate sqs create-queue --queue-name herbert

Could not connect to the endpoint URL: "http://localhost:4576/"
`

**Comment by usmangani1** [comment]
@DiesDasJenes Thanks for reporting the issue.I tried to reproduce the issue on the latest version of localstack (0.12.2) but the given command works fine and creates the queue.

```
$ aws --endpoint-url=http://localhost:4566 --region=eu-central-1 --no-paginate sqs create-queue --queue-name herbert
{
    "QueueUrl": "http://localhost:4566/000000000000/herbert"
}

```
Can you please pull the latest version of localstack and let us know if the issue still persists.Thanks

**Comment by DiesDasJenes** [comment]
Aloha,
just pulled the latest image, exported the env_keys and ran the command. Everything with the same setup as the first example. 
It worked with localstack 12.02. Thanks for your patience with me. :)

**Comment by whummer** [comment]
Thanks for the update @DiesDasJenes .

You reported that you're seeing the "Connection closed" error below - can you please share the logs from your LocalStack container, to see if there are any relevant error messages being printed in the logs? Does the request actually reach the APIs inside the container? Thanks
```
Connection was closed before we received a valid response from endpoint URL: "http://localhost:4566/".
```

**Comment by DiesDasJenes** [comment]
Aloha,

sorry for taking so long. I tried to reproduce the problem today with the localstack version 0.11.6 but was unable to do so. This baffles me as a colleague had the same issue on a different mac system back in November. Only i can say is that with version 0.12.0 the problem vanished for me. I asked my colleague to try it on his machine and send me the log message. Hope that helps.

**Comment by DiesDasJenes** [comment]
Aloha,
i got to understand what the problem was. The problem is the no-sign-request parameter with versions above 10.6. Without the parameter all is well and as designed the parameter "no-sign-request" shouldn't be used. Here is the debug log:
```
$ aws --endpoint-url=http://localhost:4566 --no-sign-request --region=eu-central-1 --no-cli-pager --debug sqs list-queues

### DEBUG LOG
2020-12-16 09:40:18,600 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.0.62 Python/3.9.0 Darwin/19.6.0 source/x86_64
2020-12-16 09:40:18,600 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--endpoint-url=http://localhost:4566', '--no-sign-request', '--region=eu-central-1', '--no-cli-pager', '--debug', 'sqs', 'list-queues']
2020-12-16 09:40:18,600 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x1023c04c0>
2020-12-16 09:40:18,600 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x101c32b80>
2020-12-16 09:40:18,600 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x102409b80>
2020-12-16 09:40:18,601 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x101c2f310>
2020-12-16 09:40:18,601 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x101c8a5e0>
2020-12-16 09:40:18,602 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2020-12-16 09:40:18,608 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x10227e430>
2020-12-16 09:40:18,608 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x102228820>
2020-12-16 09:40:18,630 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/data/sqs/2012-11-05/service-2.json
2020-12-16 09:40:18,633 - MainThread - botocore.hooks - DEBUG - Event building-command-table.sqs: calling handler <function add_waiters at 0x1023c6a60>
2020-12-16 09:40:18,656 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('queue-name-prefix', <awscli.arguments.CLIArgument object at 0x102541a00>), ('next-token', <awscli.arguments.CLIArgument object at 0x102541a30>), ('max-results', <awscli.arguments.CLIArgument object at 0x102541a60>)])
2020-12-16 09:40:18,656 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sqs.list-queues: calling handler <function add_streaming_output_arg at 0x1023c0790>
2020-12-16 09:40:18,656 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sqs.list-queues: calling handler <function add_cli_input_json at 0x101c8adc0>
2020-12-16 09:40:18,656 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sqs.list-queues: calling handler <function add_cli_input_yaml at 0x101c95040>
2020-12-16 09:40:18,656 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sqs.list-queues: calling handler <function unify_paging_params at 0x10222bf70>
2020-12-16 09:40:18,679 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/data/sqs/2012-11-05/paginators-1.json
2020-12-16 09:40:18,679 - MainThread - awscli.customizations.paginate - DEBUG - Modifying paging parameters for operation: ListQueues
2020-12-16 09:40:18,679 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sqs.list-queues: calling handler <function add_generate_skeleton at 0x102326550>
2020-12-16 09:40:18,679 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.sqs.list-queues: calling handler <function add_auto_prompt at 0x102409af0>
2020-12-16 09:40:18,679 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sqs.list-queues: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x1025418b0>>
2020-12-16 09:40:18,679 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sqs.list-queues: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x102541ac0>>
2020-12-16 09:40:18,680 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sqs.list-queues: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x102541df0>>
2020-12-16 09:40:18,680 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.sqs.list-queues: calling handler <bound method AutoPromptArgument.override_required_args of <awscli.customizations.autoprompt.AutoPromptArgument object at 0x102541e50>>
2020-12-16 09:40:18,680 - MainThread - botocore.hooks - DEBUG - Event operation-args-parsed.sqs.list-queues: calling handler functools.partial(<function check_should_enable_pagination at 0x10223b0d0>, ['next-token', 'max-results'], {}, OrderedDict([('queue-name-prefix', <awscli.arguments.CLIArgument object at 0x102541a00>), ('next-token', <awscli.arguments.CLIArgument object at 0x102541a30>), ('max-results', <awscli.arguments.CLIArgument object at 0x102541a60>), ('cli-input-json', <awscli.customizations.cliinput.CliInputJSONArgument object at 0x1025418b0>), ('cli-input-yaml', <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x102541ac0>), ('starting-token', <awscli.customizations.paginate.PageArgument object at 0x102541c10>), ('page-size', <awscli.customizations.paginate.PageArgument object at 0x102541d60>), ('max-items', <awscli.customizations.paginate.PageArgument object at 0x102541b50>), ('generate-cli-skeleton', <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x102541df0>), ('cli-auto-prompt', <awscli.customizations.autoprompt.AutoPromptArgument object at 0x102541e50>)]))
2020-12-16 09:40:18,680 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sqs.list-queues.queue-name-prefix: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10247e970>
2020-12-16 09:40:18,680 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sqs.list-queues.next-token: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10247e970>
2020-12-16 09:40:18,681 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sqs.list-queues.max-results: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10247e970>
2020-12-16 09:40:18,681 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sqs.list-queues.cli-input-json: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10247e970>
2020-12-16 09:40:18,681 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sqs.list-queues.cli-input-yaml: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10247e970>
2020-12-16 09:40:18,681 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sqs.list-queues.starting-token: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10247e970>
2020-12-16 09:40:18,681 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sqs.list-queues.page-size: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10247e970>
2020-12-16 09:40:18,681 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sqs.list-queues.max-items: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10247e970>
2020-12-16 09:40:18,681 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sqs.list-queues.generate-cli-skeleton: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10247e970>
2020-12-16 09:40:18,681 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.sqs.list-queues.cli-auto-prompt: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10247e970>
2020-12-16 09:40:18,681 - MainThread - botocore.hooks - DEBUG - Event calling-command.sqs.list-queues: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputJSONArgument object at 0x1025418b0>>
2020-12-16 09:40:18,681 - MainThread - botocore.hooks - DEBUG - Event calling-command.sqs.list-queues: calling handler <bound method CliInputArgument.add_to_call_parameters of <awscli.customizations.cliinput.CliInputYAMLArgument object at 0x102541ac0>>
2020-12-16 09:40:18,681 - MainThread - botocore.hooks - DEBUG - Event calling-command.sqs.list-queues: calling handler <bound method GenerateCliSkeletonArgument.generate_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x102541df0>>
2020-12-16 09:40:18,681 - MainThread - botocore.hooks - DEBUG - Event calling-command.sqs.list-queues: calling handler <bound method AutoPromptArgument.auto_prompt_arguments of <awscli.customizations.autoprompt.AutoPromptArgument object at 0x102541e50>>
2020-12-16 09:40:18,682 - MainThread - botocore.hooks - DEBUG - Event calling-command.sqs.list-queues: calling handler functools.partial(<function check_should_enable_pagination_call_parameters at 0x10223b4c0>, ['NextToken', 'MaxResults'])
2020-12-16 09:40:18,682 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2020-12-16 09:40:18,682 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2020-12-16 09:40:18,682 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2020-12-16 09:40:18,682 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2020-12-16 09:40:18,682 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2020-12-16 09:40:18,683 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2020-12-16 09:40:18,683 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/data/endpoints.json
2020-12-16 09:40:18,688 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x1015e0790>
2020-12-16 09:40:18,689 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.sqs: calling handler <function add_generate_presigned_url at 0x10158b040>
2020-12-16 09:40:18,692 - MainThread - botocore.endpoint - DEBUG - Setting sqs timeout as (60, 60)
2020-12-16 09:40:18,693 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.sqs.ListQueues: calling handler <function base64_decode_input_blobs at 0x10240f430>
2020-12-16 09:40:18,693 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.sqs.ListQueues: calling handler <function generate_idempotent_uuid at 0x1015fd820>
2020-12-16 09:40:18,693 - MainThread - botocore.hooks - DEBUG - Event before-call.sqs.ListQueues: calling handler <function inject_api_version_header_if_needed at 0x1016030d0>
2020-12-16 09:40:18,693 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=ListQueues) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'aws-cli/2.0.62 Python/3.9.0 Darwin/19.6.0 source/x86_64 command/sqs.list-queues'}, 'body': {'Action': 'ListQueues', 'Version': '2012-11-05'}, 'url': 'http://localhost:4566/', 'context': {'client_region': 'eu-central-1', 'client_config': <botocore.config.Config object at 0x1037a6310>, 'has_streaming_input': False, 'auth_type': None}}
2020-12-16 09:40:18,693 - MainThread - botocore.hooks - DEBUG - Event request-created.sqs.ListQueues: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x1037a62e0>>
2020-12-16 09:40:18,693 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sqs.ListQueues: calling handler <function set_operation_specific_signer at 0x1015fd700>
2020-12-16 09:40:18,693 - MainThread - botocore.hooks - DEBUG - Event choose-signer.sqs.ListQueues: calling handler <function disable_signing at 0x1015fdca0>
2020-12-16 09:40:18,693 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=http://localhost:4566/, headers={'Content-Type': b'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': b'aws-cli/2.0.62 Python/3.9.0 Darwin/19.6.0 source/x86_64 command/sqs.list-queues', 'Content-Length': '36'}>
2020-12-16 09:40:18,695 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:4566
2020-12-16 09:40:18,704 - MainThread - urllib3.connectionpool - DEBUG - http://localhost:4566 "POST / HTTP/1.1" 400 2
2020-12-16 09:40:18,705 - MainThread - botocore.parsers - DEBUG - Response headers: {'content-type': 'text/html; charset=utf-8', 'content-length': '2', 'date': 'Wed, 16 Dec 2020 08:40:18 GMT', 'server': 'hypercorn-h11'}
2020-12-16 09:40:18,705 - MainThread - botocore.parsers - DEBUG - Response body:
b'{}'
2020-12-16 09:40:18,705 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/parsers.py", line 451, in _parse_xml_string_to_dom
    parser.feed(xml_string)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 386, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 558, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 735, in __call__
    return self._operation_caller.invoke(
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 868, in invoke
    self._display_response(operation_name, response, parsed_globals)
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/awscli/clidriver.py", line 890, in _display_response
    formatter(command_name, response, stream)
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/awscli/formatter.py", line 82, in __call__
    response_data = response.build_full_result()
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/paginate.py", line 449, in build_full_result
    for response in self:
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/client.py", line 249, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/client.py", line 554, in _make_api_call
    http, parsed_response = self._make_request(
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/client.py", line 574, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/endpoint.py", line 134, in _send_request
    success_response, exception = self._get_response(
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/endpoint.py", line 166, in _get_response
    success_response, exception = self._do_get_response(
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/endpoint.py", line 217, in _do_get_response
    parsed_response = parser.parse(
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/parsers.py", line 243, in parse
    parsed = self._do_error_parse(response, shape)
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/parsers.py", line 505, in _do_error_parse
    root = self._parse_xml_string_to_dom(xml_contents)
  File "/usr/local/Cellar/awscli/2.0.62/libexec/lib/python3.9/site-packages/botocore/parsers.py", line 454, in _parse_xml_string_to_dom
    raise ResponseParserError(
botocore.parsers.ResponseParserError: Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
b'{}'
2020-12-16 09:40:18,709 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
b'{}'

### OUTPUT
Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
b'{}'
```
