### ISSUE TITLE
JSON parsing problems when using jackson 2.11 in a Kinesis Consumer

### ISSUE THREAD

**Issue by jbartok** [localstack/localstack#3208]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
When developing a Kinesis Data Stream Consumer using `com.amazonaws:aws-java-sdk-kinesis:1.11.887` I'm encountering following error:

```
com.amazonaws.SdkClientException: Unable to marshall request to JSON: Jackson jackson-core/jackson-dataformat-cbor incompatible library version detected.
You have two possible resolutions:
		1) Ensure the com.fasterxml.jackson.core:jackson-core & com.fasterxml.jackson.dataformat:jackson-dataformat-cbor libraries on your classpath have the same version number
		2) Disable CBOR wire-protocol by passing the -Dcom.amazonaws.sdk.disableCbor property or setting the AWS_CBOR_DISABLE environment variable (warning this may affect performance)
```

The direct cause of this is that I have different versions of the jackson libraries on my classpath (they are both transitive dependencies of the above mentioned aws library and they are also included for unrelated reasons in our project, hence the mismatch):

* `com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.6.7`
* `com.fasterxml.jackson.core:jackson-core:jar:2.11.2`

I can't downgrade the core version so in order to address the problem, I've forced both to version `2.11.2`. This produces the problem I want to report (and ask for help on):

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: Current token (START_OBJECT) not VALUE_EMBEDDED_OBJECT, can not access as binary
 at [Source: (com.amazonaws.event.ResponseProgressInputStream); line: -1, column: 297]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:373) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:1.8.0_202]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:346) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_202]
Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Current token (START_OBJECT) not VALUE_EMBEDDED_OBJECT, can not access as binary
 at [Source: (com.amazonaws.event.ResponseProgressInputStream); line: -1, column: 297]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1207) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1153) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2866) ~[aws-java-sdk-kinesis-1.11.887.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2833) ~[aws-java-sdk-kinesis-1.11.887.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2822) ~[aws-java-sdk-kinesis-1.11.887.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.executeGetRecords(AmazonKinesisClient.java:1307) ~[aws-java-sdk-kinesis-1.11.887.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisAsyncClient$12.call(AmazonKinesisAsyncClient.java:757) ~[aws-java-sdk-kinesis-1.11.887.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisAsyncClient$12.call(AmazonKinesisAsyncClient.java:751) ~[aws-java-sdk-kinesis-1.11.887.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_202]
	... 1 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Current token (START_OBJECT) not VALUE_EMBEDDED_OBJECT, can not access as binary
 at [Source: (com.amazonaws.event.ResponseProgressInputStream); line: -1, column: 297]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851) ~[jackson-core-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:707) ~[jackson-core-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.dataformat.cbor.CBORParser.getBinaryValue(CBORParser.java:1660) ~[jackson-dataformat-cbor-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.core.JsonParser.getBinaryValue(JsonParser.java:1495) ~[jackson-core-2.11.2.jar:2.11.2]
	at com.amazonaws.transform.SimpleTypeCborUnmarshallers$ByteBufferCborUnmarshaller.unmarshall(SimpleTypeCborUnmarshallers.java:198) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.transform.SimpleTypeCborUnmarshallers$ByteBufferCborUnmarshaller.unmarshall(SimpleTypeCborUnmarshallers.java:196) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.services.kinesis.model.transform.RecordJsonUnmarshaller.unmarshall(RecordJsonUnmarshaller.java:61) ~[aws-java-sdk-kinesis-1.11.887.jar:?]
	at com.amazonaws.services.kinesis.model.transform.RecordJsonUnmarshaller.unmarshall(RecordJsonUnmarshaller.java:29) ~[aws-java-sdk-kinesis-1.11.887.jar:?]
	at com.amazonaws.transform.ListUnmarshaller.unmarshallJsonToList(ListUnmarshaller.java:92) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.transform.ListUnmarshaller.unmarshall(ListUnmarshaller.java:46) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.services.kinesis.model.transform.GetRecordsResultJsonUnmarshaller.unmarshall(GetRecordsResultJsonUnmarshaller.java:55) ~[aws-java-sdk-kinesis-1.11.887.jar:?]
	at com.amazonaws.services.kinesis.model.transform.GetRecordsResultJsonUnmarshaller.unmarshall(GetRecordsResultJsonUnmarshaller.java:29) ~[aws-java-sdk-kinesis-1.11.887.jar:?]
	at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:118) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:43) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:69) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1743) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleSuccessResponse(AmazonHttpClient.java:1463) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530) ~[aws-java-sdk-core-1.11.887.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2866) ~[aws-java-sdk-kinesis-1.11.887.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2833) ~[aws-java-sdk-kinesis-1.11.887.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2822) ~[aws-java-sdk-kinesis-1.11.887.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisClient.executeGetRecords(AmazonKinesisClient.java:1307) ~[aws-java-sdk-kinesis-1.11.887.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisAsyncClient$12.call(AmazonKinesisAsyncClient.java:757) ~[aws-java-sdk-kinesis-1.11.887.jar:?]
	at com.amazonaws.services.kinesis.AmazonKinesisAsyncClient$12.call(AmazonKinesisAsyncClient.java:751) ~[aws-java-sdk-kinesis-1.11.887.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_202]
	... 1 more
```

**I think this is a problem inside Localstack, because if I run the same on an actual AWS backend, then it works, no Exception is thrown.**

# Steps to reproduce
Just run [this test](https://github.com/jbartok/hazelcast-jet/blob/localstack-issue/extensions/kinesis/src/test/java/com/hazelcast/jet/kinesis/KinesisIntegrationTest.java
) and it will result in the exception I've described.

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-69) by [Unito](https://www.unito.io/learn-more)

**Comment by jmoteka** [comment]
Same issue here - Fix is appreciated

**Comment by whummer** [comment]
Thanks for reporting @jbartok @jmoteka . We believe that this should be fixed in #3278 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by jbartok** [comment]
Hi. Unfortunately `latest` Docker image doesn't fix the problem. I don't get the above mentioned error, just a very generic one (`com.amazonaws.services.kinesis.model.AmazonKinesisException: null (Service: AmazonKinesis; Status Code: 500; Error Code: null; Request ID: null; Proxy: null)`) and things don't work.

**Comment by pinzon** [comment]
Hi, I just recently wrote two Kinesis Consumer tests for each Java AWS SDK version, and both work with CBOR and JSON encoding.
Could you provide me with more info about your set up? Maybe this code can help you  [Kinesis consumer Test](https://github.com/localstack/localstack-java-utils/blob/master/src/test/java/cloud/localstack/KinesisConsumerTest.java)

**Comment by jbartok** [comment]
Hi @pinzon. Sorry for taking my sweet time to come back to you... So. Yes, you did improve something. Things work now in the sense that data comes in and no exceptions are thrown. But I don't think the data is ok. 

To illustrate pls. see this reproducer I wrote for it: https://github.com/jbartok/cbor-issue-reproducer/blob/master/src/test/java/SimpleDataflowTest.java

It's just a simple test that writes some data into KDS and then reads it back. If you run it as is, it works. They bytes written match the bytes read. But if you uncomment the line setting the `AWS_CBOR_DISABLE_SYSTEM_PROPERTY`, then it stops working. The bytes read no longer match the bytes written. 

It's true that I don't fully understand how CBOR encoding is supposed to be used, but still, I would say that this behaviour is not correct, because it differs from how the actual AWS backend behaves, if you run the same test on it. 

Hope this helps, let me know.

**Comment by pinzon** [comment]
Hi @jbartok Don't worry and thank you.
As soon as I'm able to run your code and validate what you're saying, I'll reopen the issue and continue to work on it.
I'll keep you updated.

**Comment by pinzon** [comment]
@jbartok You're right, testing your reproducer shows that when working with CBOR the returning messages are wrong.
I'll go back to work on it. 
Thank you.

**Comment by pinzon** [comment]
My last PR has been merge. The problem should be fix now.
Thank you for your help.

**Comment by jbartok** [comment]
My problem has disappered with the `0.12.6` release. Thank you for your help!

**Comment by jbartok** [comment]
Actually no... The reproducer works, but real test still don't.... I just get a very generic error, which doesn't provide clues: com.amazonaws.services.kinesis.model.AmazonKinesisException: null (Service: AmazonKinesis; Status Code: 500; Error Code: null; Request ID: null; Proxy: null)

I think I just give up and use Localstack with CBOR disabled.

**Comment by pinzon** [comment]
Mmmm could you give me more details in what does your real test do different?
