### ISSUE TITLE
DynamoDB BatchGetItem ResourceNotFoundException: Cannot do operations on a non-existent table

### ISSUE THREAD

**Issue by mariaines** [localstack/localstack#3236]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
Hi again :wave: 

I am seeing this error from localstack dynamo after pulling the latest (0.12.2, was on 0.11.2 before). I am also newly on a pro trial.
I see it only for BatchGetItem operations:

```
ResourceNotFoundException: Cannot do operations on a non-existent table
```

The table definitely exists:

```
$ aws dynamodb --endpoint-url http://localhost:4566 list-tables
{
    "TableNames": [
        "table2"
    ]
}
```

and I'm able to do UpdateItem and Query operations on the same table.

## Expected behavior
Able to do all operations on local dynamo table

## Actual behavior
ResourceNotFoundException for BatchGetItem operations

Full error logs:

```
localstack_1           | 23:22:42.279 [qtp1099552523-31] WARN  com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler - DynamoDBLocalServiceException exception occured
localstack_1           | com.amazonaws.services.dynamodbv2.exceptions.DynamoDBLocalServiceException: Cannot do operations on a non-existent table
localstack_1           | at com.amazonaws.services.dynamodbv2.exceptions.AWSExceptionFactory.buildLocalServiceException(AWSExceptionFactory.java:93) ~[DynamoDBLocal.jar:?]
localstack_1           | at com.amazonaws.services.dynamodbv2.exceptions.AWSExceptionFactory.buildAWSException(AWSExceptionFactory.java:58) ~[DynamoDBLocal.jar:?]
localstack_1           | at com.amazonaws.services.dynamodbv2.local.shared.access.api.DynamoDbApiFunction.validateTableExists(DynamoDbApiFunction.java:66) ~[DynamoDBLocal.jar:?]
localstack_1           | at com.amazonaws.services.dynamodbv2.local.shared.access.api.dp.BatchGetItemFunction.validateBatchGetEntry(BatchGetItemFunction.java:196) ~[DynamoDBLocal.jar:?]
localstack_1           | at com.amazonaws.services.dynamodbv2.local.shared.access.api.dp.BatchGetItemFunction.apply(BatchGetItemFunction.java:61) ~[DynamoDBLocal.jar:?]
localstack_1           | at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBClient.batchGetItem(LocalDynamoDBClient.java:174) ~[DynamoDBLocal.jar:?]
localstack_1           | at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.batchGetItem(LocalDynamoDBRequestHandler.java:222) ~[DynamoDBLocal.jar:?]
localstack_1           | at com.amazonaws.services.dynamodbv2.local.dispatchers.BatchGetItemDispatcher.enact(BatchGetItemDispatcher.java:18) ~[DynamoDBLocal.jar:?]
localstack_1           | at com.amazonaws.services.dynamodbv2.local.dispatchers.BatchGetItemDispatcher.enact(BatchGetItemDispatcher.java:12) ~[DynamoDBLocal.jar:?]
localstack_1           | at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.packageDynamoDBResponse(LocalDynamoDBServerHandler.java:373) [DynamoDBLocal.jar:?]
localstack_1           | at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.handle(LocalDynamoDBServerHandler.java:460) [DynamoDBLocal.jar:?]
localstack_1           | at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
localstack_1           | at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1024) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
localstack_1           | at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
localstack_1           | at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
localstack_1           | at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
localstack_1           | at org.eclipse.jetty.server.Server.handle(Server.java:370) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
localstack_1           | at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
localstack_1           | at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
localstack_1           | at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
localstack_1           | at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jetty-http-8.1.12.v20130726.jar:8.1.12.v20130726]
localstack_1           | at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-8.1.12.v20130726.jar:8.1.12.v20130726]
localstack_1           | at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
localstack_1           | at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668) [jetty-io-8.1.12.v20130726.jar:8.1.12.v20130726]
localstack_1           | at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) [jetty-io-8.1.12.v20130726.jar:8.1.12.v20130726]
localstack_1           | at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.12.v20130726.jar:8.1.12.v20130726]
localstack_1           | at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.12.v20130726.jar:8.1.12.v20130726]
localstack_1           | at java.lang.Thread.run(Unknown Source) [?:?]
```

# Steps to reproduce
## Command used to start LocalStack
docker-compose up

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
    aws dynamodb create-table \
        --endpoint-url=http://$HOST:4566 \
        --table-name table2 \
        --attribute-definitions \
            AttributeName=_pk,AttributeType=S \
            AttributeName=_sk,AttributeType=S \
            AttributeName=_gsi1_pk,AttributeType=S \
            AttributeName=_gsi1_sk,AttributeType=S \
            AttributeName=_gsi2_pk,AttributeType=S \
            AttributeName=_gsi2_sk,AttributeType=S \
        --key-schema \
            AttributeName=_pk,KeyType=HASH \
            AttributeName=_sk,KeyType=RANGE \
        --provisioned-throughput \
            ReadCapacityUnits=5,WriteCapacityUnits=5 \
        --global-secondary-indexes \
            'IndexName=_gsi1_pk-_gsi1_sk-index,KeySchema=[{AttributeName=_gsi1_pk,KeyType=HASH},{AttributeName=_gsi1_sk,KeyType=RANGE}],Projection={ProjectionType=ALL},ProvisionedThroughput={ReadCapacityUnits=5,WriteCapacityUnits=5}'\
            'IndexName=_gsi2_pk-_gsi2_sk-index,KeySchema=[{AttributeName=_gsi2_pk,KeyType=HASH},{AttributeName=_gsi2_sk,KeyType=RANGE}],Projection={ProjectionType=ALL},ProvisionedThroughput={ReadCapacityUnits=5,WriteCapacityUnits=5}'\
        --stream-specification \
            StreamEnabled=true,StreamViewType=NEW_AND_OLD_IMAGES
```

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-57) by [Unito](https://www.unito.io/learn-more)

**Comment by mariaines** [comment]
Some further logs from calling GetItem vs BatchGetItem:

```sh
$ aws dynamodb --endpoint-url http://localhost:4566 get-item --table-name table2 --key "{\"_pk\":{\"S\":\"conv.01EPWTN9RPHRX38FEWNDYR1KJE\"}, \"_sk\":{\"S\":\"conv.01EPWTN9RPHRX38FEWNDYR1KJE\"}}"
{
    "Item": {
        "_model_name": {
            "S": "conv"
        },
        "_sk": {
            "S": "conv.01EPWTN9RPHRX38FEWNDYR1KJE"
        },
        "conversation_id": {
            "S": "conv.01EPWTN9RPHRX38FEWNDYR1KJE"
        },
        "_create_date": {
            "N": "1605137770268"
        },
        "_pk": {
            "S": "conv.01EPWTN9RPHRX38FEWNDYR1KJE"
        },
        "author_id": {
            "S": "person.1e9cafd3-18a1-4ff2-8e94-7bfc1014c764"
        },
        "_version": {
            "N": "1605137770268"
        }
    }
}
$ aws dynamodb --endpoint-url http://localhost:4566 batch-get-item --request-items "{\"table2\":{\"Keys\":[{\"_pk\":{\"S\":\"conv.01EPWTN9RPHRX38FEWNDYR1KJE\"}, \"_sk\":{\"S\":\"conv.01EPWTN9RPHRX38FEWNDYR1KJE\"}}]}}"

An error occurred (ResourceNotFoundException) when calling the BatchGetItem operation: Cannot do operations on a non-existent table
```

**Comment by mariaines** [comment]
I think this was introduced in 0.12.2 -- seems to work on 0.12.1. (But 0.12.2 includes some websocket fixes I need 😄) 

Let me know if I can help debug further!

**Comment by mariaines** [comment]
Interesting, it seems related to the localstack API key for pro access. If I remove that, then BatchGetItem works on 0.12.2

**Comment by danielblignaut** [comment]
I am getting the same issue on BatchWriteItem

**Comment by whummer** [comment]
Thanks for reporting @mariaines @danielblignaut . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!

**Comment by gruckionvit** [comment]
Issue doesn't appear to be fixed.

https://github.com/localstack/localstack/issues/4459
