### ISSUE TITLE
testing multilangdaemon kcl with localstack.

### ISSUE THREAD

**Issue by mhd21** [localstack/localstack#3271]
Hi,

I'm trying to test multilangdaemon kcl with localstack.
but when kcl connects to sync kinesis shards, it gives me this error

```
2020-11-24T08:49:43:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: 'utf-8' codec can't decode byte 0xa2 in position 0: invalid start byte Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 107, in index
    raise result
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 578, in run
    result = self.func(self.params)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
    return fn(_args, *_kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 571, in handler
    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 341, in modify_and_forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/edge.py", line 81, in forward_request
    return do_forward_request(api, port, method, path, data, headers)
  File "/opt/code/localstack/localstack/services/edge.py", line 86, in do_forward_request
    result = do_forward_request_inmem(api, port, method, path, data, headers)
  File "/opt/code/localstack/localstack/services/edge.py", line 106, in do_forward_request_inmem
    response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 409, in modify_and_forward
    updated_response = update_listener.return_response(**kwargs)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py", line 81, in return_response
    to_str(response.content or ''))
  File "/opt/code/localstack/localstack/utils/common.py", line 845, in to_str
    return obj.decode(encoding, errors) if isinstance(obj, six.binary_type) else obj
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 0: invalid start byte
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-348) by [Unito](https://www.unito.io/learn-more)

**Comment by whummer** [comment]
Thanks for reporting @mhd21 - looks like the multilangdaemon kcl is connecting using the CBOR protocol (rather than JSON). This should have been fixed in the meantime via https://github.com/localstack/localstack/pull/3078 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks
