### ISSUE TITLE
localstack start fails

### ISSUE THREAD

**Issue by gpolyn** [localstack/localstack#3287]
# Type of request: This is a ...

[X] bug report

# Detailed description

`localstack start` fails.

## Expected behavior

Here is the result of `$ docker-compose up`, using the reference [docker-compose.yml](https://github.com/localstack/localstack/blob/master/docker-compose.yml) in the same environment.

```
[ec2-user@ip-172-31-91-233 ~]$ docker-compose up
WARNING: The TMPDIR variable is not set. Defaulting to a blank string.
Creating localstack_main ... done
Attaching to localstack_main
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | 2020-11-29 00:31:57,287 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_main | 2020-11-29 00:31:57,289 INFO supervisord started with pid 13
localstack_main | 2020-11-29 00:31:58,291 INFO spawned: 'dashboard' with pid 19
localstack_main | 2020-11-29 00:31:58,292 INFO spawned: 'infra' with pid 20
localstack_main | 2020-11-29 00:31:58,296 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_main | 2020-11-29 00:31:58,296 INFO exited: dashboard (exit status 0; expected)
localstack_main | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_main | Starting local dev environment. CTRL-C to quit.
localstack_main | LocalStack version: 0.12.2
localstack_main | 2020-11-29 00:31:59,628 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_main | Starting edge router (https port 4566)...
localstack_main | Starting mock ACM service on http port 4566 ...
localstack_main | [2020-11-29 00:32:02 +0000] [21] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main | 2020-11-29T00:32:02:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main | [2020-11-29 00:32:02 +0000] [21] [INFO] Running on http://0.0.0.0:57513 (CTRL + C to quit)
localstack_main | 2020-11-29T00:32:02:INFO:hypercorn.error: Running on http://0.0.0.0:57513 (CTRL + C to quit)
localstack_main | Starting mock API Gateway service on http port 4566 ...
localstack_main | Starting mock CloudFormation service on http port 4566 ...
localstack_main | Starting mock CloudWatch service on http port 4566 ...
localstack_main | Starting mock DynamoDB service on http port 4566 ...
localstack_main | Starting mock DynamoDB Streams service on http port 4566 ...
localstack_main | Starting mock EC2 service on http port 4566 ...
localstack_main | Starting mock ES service on http port 4566 ...
localstack_main | Starting mock Firehose service on http port 4566 ...
localstack_main | Starting mock IAM service on http port 4566 ...
localstack_main | Starting mock STS service on http port 4566 ...
localstack_main | Starting mock Kinesis service on http port 4566 ...
localstack_main | Starting mock KMS service on http port 4566 ...
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | Starting mock Lambda service on http port 4566 ...
localstack_main | Starting mock CloudWatch Logs service on http port 4566 ...
localstack_main | Starting mock Redshift service on http port 4566 ...
localstack_main | Starting mock Route53 service on http port 4566 ...
localstack_main | Starting mock S3 service on http port 4566 ...
localstack_main | Starting mock Secrets Manager service on http port 4566 ...
localstack_main | Starting mock SES service on http port 4566 ...
localstack_main | Starting mock SNS service on http port 4566 ...
localstack_main | Starting mock SQS service on http port 4566 ...
localstack_main | Starting mock SSM service on http port 4566 ...
localstack_main | Starting mock Cloudwatch Events service on http port 4566 ...
localstack_main | Starting mock StepFunctions service on http port 4566 ...
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | Ready.
```

## Actual behavior

```
Starting local dev environment. CTRL-C to quit.
ERROR: 'chmod -R 777 "/tmp/localstack"': exit code 1; output: b'chmod: changing permissions of \xe2\x80\x98/tmp/localstack/server.test.pem\xe2\x80\x99: Operation not permitted\nchmod: changing permissions of \xe2\x80\x98/tmp/localstack/server.test.pem.key\xe2\x80\x99: Operation not permitted\nchmod: changing permissions of \xe2\x80\x98/tmp/localstack/server.test.pem.crt\xe2\x80\x99: Operation not permitted\n'
Waiting for all LocalStack services to be ready
2020-11-29 00:48:34,653 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-11-29 00:48:34,655 INFO supervisord started with pid 13
2020-11-29 00:48:35,657 INFO spawned: 'dashboard' with pid 19
2020-11-29 00:48:35,658 INFO spawned: 'infra' with pid 20
2020-11-29 00:48:35,662 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2020-11-29 00:48:35,662 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
Starting local dev environment. CTRL-C to quit.
LocalStack version: 0.12.2
2020-11-29 00:48:36,996 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-11-29T00:48:38:INFO:localstack.utils.analytics.profiler: Execution of "load_plugin_from_path" took 2510.7369422912598ms
2020-11-29T00:48:38:INFO:localstack.utils.analytics.profiler: Execution of "load_plugins" took 2511.070966720581ms
Starting edge router (https port 4566)...
Starting mock ACM service on http port 4566 ...
2020-11-29T00:48:39:INFO:localstack.utils.analytics.profiler: Execution of "prepare_environment" took 1033.6101055145264ms
2020-11-29T00:48:40:INFO:localstack.multiserver: Starting multi API server process on port 39935
[2020-11-29 00:48:40 +0000] [21] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2020-11-29T00:48:40:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
[2020-11-29 00:48:40 +0000] [21] [INFO] Running on http://0.0.0.0:39935 (CTRL + C to quit)
2020-11-29T00:48:40:INFO:hypercorn.error: Running on http://0.0.0.0:39935 (CTRL + C to quit)
Starting mock API Gateway service on http port 4566 ...
Starting mock CloudFormation service on http port 4566 ...
Starting mock CloudWatch service on http port 4566 ...
Starting mock DynamoDB service on http port 4566 ...
Starting mock DynamoDB Streams service on http port 4566 ...
Starting mock EC2 service on http port 4566 ...
Starting mock ES service on http port 4566 ...
Starting mock Firehose service on http port 4566 ...
Starting mock IAM service on http port 4566 ...
Starting mock STS service on http port 4566 ...
Starting mock Kinesis service on http port 4566 ...
Starting mock KMS service on http port 4566 ...
INFO[2020-11-29 00:48:41.218] No file found at path /init/seed.yaml; skipping seeding.
INFO[2020-11-29 00:48:41.218] Data will be stored in /tmp/local-kms
INFO[2020-11-29 00:48:41.218] Local KMS started on 0.0.0.0:42041
Listening at http://:::41739
Initializing DynamoDB Local with the following configuration:
Port:   38587
InMemory:       true
DbPath: null
SharedDb:       true
shouldDelayTransientStatuses:   false
CorsParams:     *

2020-11-29 00:48:41,044:API:  * Running on http://0.0.0.0:36003/ (Press CTRL+C to quit)
2020-11-29 00:48:41,108:API:  * Running on http://0.0.0.0:46005/ (Press CTRL+C to quit)
Waiting for all LocalStack services to be ready
Starting mock Lambda service on http port 4566 ...
Starting mock CloudWatch Logs service on http port 4566 ...
Starting mock Redshift service on http port 4566 ...
Starting mock Route53 service on http port 4566 ...
Starting mock S3 service on http port 4566 ...
Starting mock Secrets Manager service on http port 4566 ...
Starting mock SES service on http port 4566 ...
Starting mock SNS service on http port 4566 ...
Starting mock SQS service on http port 4566 ...
Starting mock SSM service on http port 4566 ...
Starting mock Cloudwatch Events service on http port 4566 ...
Starting mock StepFunctions service on http port 4566 ...
Step Functions Local
Version: 1.7.3
Build: 2020-10-29
2020-11-29 00:48:42.173: Configure [Account] to [000000000000]
2020-11-29 00:48:42.174: Configure [Region] to [us-east-1]
2020-11-29 00:48:42.174: Configure [Lambda Endpoint] to [http://ip-172-31-91-233.ec2.internal:4566]
2020-11-29 00:48:42.175: Configure [DynamoDB Endpoint] to [http://ip-172-31-91-233.ec2.internal:4566]
2020-11-29 00:48:42.175: Configure [SQS Endpoint] to [http://ip-172-31-91-233.ec2.internal:4566]
2020-11-29 00:48:42.175: Configure [SNS Endpoint] to [http://ip-172-31-91-233.ec2.internal:4566]
2020-11-29 00:48:42.175: Configure [Step Functions Endpoint] to [http://ip-172-31-91-233.ec2.internal:4566]
2020-11-29 00:48:42.180: Loaded credentials from environment
2020-11-29 00:48:42.181: Starting server on port 8083 with account 000000000000, region us-east-1
Nov 29, 2020 12:48:42 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Nov 29, 2020 12:48:42 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Nov 29, 2020 12:48:42 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Nov 29, 2020 12:48:42 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Nov 29, 2020 12:48:42 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Nov 29, 2020 12:48:42 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Nov 29, 2020 12:48:42 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Nov 29, 2020 12:48:42 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Nov 29, 2020 12:48:42 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Nov 29, 2020 12:48:42 AM com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.jetty.util.BufferUtil (file:/opt/code/localstack/localstack/infra/stepfunctions/jetty-util-9.3.x.jar) to field java.nio.MappedByteBuffer.fd
WARNING: Please consider reporting this to the maintainers of org.eclipse.jetty.util.BufferUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-11-29T00:48:47:WARNING:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fbc84817670>(None) failed: MyHTTPConnectionPool(host='ip-172-31-91-233.ec2.internal', port=38587): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc83c08760>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fbc83c08760>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='ip-172-31-91-233.ec2.internal', port=38587): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc83c08760>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 578, in run
    result = self.func(self.params)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 571, in handler
    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 341, in modify_and_forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/edge.py", line 81, in forward_request
    return do_forward_request(api, port, method, path, data, headers)
  File "/opt/code/localstack/localstack/services/edge.py", line 86, in do_forward_request
    result = do_forward_request_inmem(api, port, method, path, data, headers)
  File "/opt/code/localstack/localstack/services/edge.py", line 106, in do_forward_request_inmem
    response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 383, in modify_and_forward
    response = requests_method(request_url, data=data_to_send,
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: MyHTTPConnectionPool(host='ip-172-31-91-233.ec2.internal', port=38587): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc83c08760>: Failed to establish a new connection: [Errno 111] Connection refused'))

2020-11-29T00:48:47:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://ip-172-31-91-233.ec2.internal:4566/: MyHTTPConnectionPool(host='ip-172-31-91-233.ec2.internal', port=38587): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc83c08760>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
```
# Steps to reproduce

Amazon Linux release 2 (Karoo) # ID_LIKE="centos rhel fedora"
Python 3.7.9
Docker version 19.03.13-ce, build 4484c46
localstack Version: 0.12.2

## Command used to start LocalStack

`$ localstack start`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

**N/A**

**Comment by whummer** [comment]
Thanks for reporting @gpolyn . This should (hopefully) be fixed in #3379 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks!
