### ISSUE TITLE
LocalStack Lambda does not support custom errors

### ISSUE THREAD

**Issue by gpolyn** [localstack/localstack#3296]
# Type of request: This is a ...

**[X] feature request**

# Detailed description

When seeking to dupe https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-handling-error-conditions.html, Node.js Lambda custom errors raised as generic **`Exception`** types.

## Expected behavior

Expect Step Function to catch custom error, for example, as shown:
```json
   "States": {
      "CreateAccount": {
         "Type": "Task",
         "Resource": "arn:aws:lambda:us-east-1:123456789012:function:FailFunction",
         "Catch": [ {
            "ErrorEquals": ["CustomError"],
            "Next": "CustomErrorFallback"
         }, 
       ...
```
## Actual behavior

The following attempt at throwing a custom error fails the CustomError gate in the State Machine, because the Error is always "Error=Exception", and never "Error=MyCustomException".

```
localstack_main | 2020-12-02T00:08:57.416Z      fe244734-83d3-1744-2c2e-14d74da89074    ERROR   Invoke Error    {"errorType":"CustomError","errorMessage":"This is a custom error!","name":"CustomError","message":"This is a custom error!","stack":["Error","    at Runtime.exports.handler (/var/task/app.js:13:29)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}
localstack_main | END RequestId: fe244734-83d3-1744-2c2e-14d74da89074
localstack_main | REPORT RequestId: fe244734-83d3-1744-2c2e-14d74da89074        Init Duration: 102.24 ms        Duration: 9.20 msBilled Duration: 100 ms  Memory Size: 1536 MB    Max Memory Used: 41 MB
localstack_main | 
localstack_main | 2020-12-02T00:08:57:DEBUG:localstack.services.sns.sns_listener: Publishing message to TopicArn: arn:aws:sns:us-east-1:000000000000:results-updates-topic | Message: Error {Error=Exception, Cause={"errorMessage":"Lambda process returned error status code: 1. Result: {\"errorType\":\"CustomError\",\"errorMessage\":\"This is a custom error!\"} ...
```

# Steps to reproduce

Amazon Linux release 2 (Karoo) # ID_LIKE="centos rhel fedora"
Python 3.7.9
Docker version 19.03.13-ce, build 4484c46
localstack Version: 0.12.2

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

As given at https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-handling-error-conditions.html .

## Resolution option?

Is the handling for non-Python Lambda runtimes fully supported? In my logs I see reference to https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_executors.py#L210 , which appears to wrap all errors in a generic Python Exception type. I guess you could resolve by disclaiming responsibility for supporting something like what is shown at https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-handling-error-conditions.html ?

**Comment by gpolyn** [comment]
For me, the limitation at [awslambda/lambda_executors.py#L210](https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_executors.py#L210) meant I could not use my preferred approach of Terraform provisioning.

For my workaround,
- `sam local start-lambda --host 172.31.34.224`
- In my `docker-compose.yml`, `services > localstack > environment > STEPFUNCTIONS_LAMBDA_ENDPOINT=http://172.31.34.224:3001`
