### ISSUE TITLE
Lambda can't convert EncryptionType property inside record in KinesisEvent 

### ISSUE THREAD

**Issue by tomaz-tekavec-cko** [localstack/localstack#3326]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description

I've created minimal Lambda function which can be connected to Kinesis stream via source event mapping and triggered upon new records on the stream. The only thing it does is logs the count of incoming records:

```
    public class Function
    {
        public async Task FunctionHandler(KinesisEvent kinesisEvent)
        {
            LambdaLogger.Log($"{kinesisEvent.Records.Count} records received");
            await Task.Delay(10);
        }
    }
```

I'm using the recommended `DefaultLambdaJsonSerializer` (https://aws.amazon.com/blogs/developer/one-month-update-to-net-core-3-1-lambda/) and the latest AWS nuget packages (as of 2020-12-08).

Lambda is written in C# and targeting .NET Core 3.1.

I setup localstack (v0.12.2), create Kinesis stream, register Lambda function and map Lambda to the stream.

## Expected behavior

When I put a record to Kinesis stream, Lambda should be triggered and number of records detected should be logged. The same code works fine in real AWS environment.

## Actual behavior

When I put a record to Kinesis stream, Lambda is triggered but it crashes before it reaches logging command with:

```
localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:test-lambda: Lambda process returned error status code: 

1. Result: {"errorType":"JsonSerializerException","errorMessage":"Error converting the Lambda event JSON payload to type Amazon.Lambda.KinesisEvents.KinesisEvent: The JSON value could not be converted to Amazon.Kinesis.EncryptionType. Path: $.Records[0].kinesis.encryptionType | LineNumber: 0 | BytePositionInLine: 481.","stackTrace":["at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.Deserialize[T](Stream requestStream)","at lambda_method(Closure , Stream , Stream , LambdaContextInternal )"],"cause":{"errorType":"JsonException","errorMessage":"The JSON value could not be converted to Amazon.Kinesis.EncryptionType. Path: $.Records[0].kinesis.encryptionType | LineNumber: 0 | BytePositionInLine: 481.","stackTrace":["at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)","at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack\u0026 state, Utf8JsonReader\u0026 reader)","at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack\u0026 state, Utf8JsonReader\u0026 reader)","at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader\u0026 reader, ReadStack\u0026 readStack)","at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader\u0026 reader)","at System.Text.Json.JsonSerializer.ParseCore(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)","at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)","at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.Deserialize[T](Stream requestStream)"]}}
```

# Steps to reproduce

## Command used to start LocalStack

Via `docker-compose` file:

```
version: "3.7"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack-light:0.12.2
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - SERVICES=kinesis,lambda,kms
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker-reuse
      - KINESIS_ERROR_PROBABILITY=0.0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
    volumes:
      - ./localstack/:/docker-entrypoint-initaws.d/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp/localstack:/tmp/localstack
      - ./tmp/lambdas:/tmp/lambdas
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

`Function.cs`:

```
[assembly: Amazon.Lambda.Core.LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

namespace TestLambda
{
    using System.Threading.Tasks;
    using Amazon.Lambda.Core;
    using Amazon.Lambda.KinesisEvents;

    public class Function
    {
        public async Task FunctionHandler(KinesisEvent kinesisEvent)
        {
            LambdaLogger.Log($"{kinesisEvent.Records.Count} records received");
            await Task.Delay(10);
        }
    }
}
```

csproj project file:

```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <AWSProjectType>Lambda</AWSProjectType>
        <LangVersion>8</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.Kinesis" Version="3.5.0.47" />
        <PackageReference Include="Amazon.Lambda.Core" Version="1.2.0" />
        <PackageReference Include="Amazon.Lambda.KinesisEvents" Version="1.2.0" />
        <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.1.0" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>
```

appsettings.json file:

```
{
  "AWS": {
    "ServiceURL": "http://localstack:4566",
    "Region": "us-east-1"
  }
}
```

Kinesis stream creation:
```
awslocal kinesis create-stream --stream-name test-lambda --shard-count 1
```

Lambda create:
```
awslocal lambda create-function --function-name test-lambda --runtime dotnetcore3.1 --zip-file fileb:///tmp/lambdas/TestLambda.zip --handler TestLambda::TestLambda.Function::FunctionHandler --role local-role 
```

Event source mapping:
```
awslocal lambda create-event-source-mapping --function-name test-lambda --batch-size 1 --starting-position LATEST --event-source-arn arn:aws:kinesis:us-east-1:000000000000:stream/test-lambda	
```

Command for publishing record:
```
awslocal kinesis put-record --stream-name test-lambda --data sampledatarecord --partition-key '1234'
```

Output after `put-record` command (note there's no `EncryptionType` value displayed):

```
{
    "ShardId": "shardId-000000000000",
    "SequenceNumber": "49613413014762796818433895223846930877417262467596156930"
}
```

Sample solution & setup provided in [lambda-event-sourcing.zip](https://github.com/localstack/localstack/files/5660622/lambda-event-sourcing.zip). Usage:
* `make publish`
* `make zip-lambdas-win` (for Windows users with 7-zip installed) or `make zip-lambda-ux` (for unix users with zip installed)
* `docker-compose build`
* `docker-compose up -d`
* `sh  put-record.sh`

**Comment by tomaz-tekavec-cko** [comment]
Btw, the same sample works fine with localstack `0.11.2`, output:

```
2020-12-08T17:28:21:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:test-lambda result / log output:
null
START RequestId: 46625884-3e2e-1a7b-06b0-e4c98a170bc5 Version: $LATEST
1 records receivedEND RequestId: 46625884-3e2e-1a7b-06b0-e4c98a170bc5
REPORT RequestId: 46625884-3e2e-1a7b-06b0-e4c98a170bc5	
Init Duration: 1535.14 ms	
Duration: 51.04 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 53 MB	
```

**Comment by whummer** [comment]
Thanks for reporting @tomaz-tekavec-cko . This should be fixed in #3346 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by tomaz-tekavec-cko** [comment]
Thank you very much @whummer for such quick response! I've just tested the same setup but with the latest localstack (currently 0.12.3) but the problem still persist:

```
2020-12-16T17:34:03:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:test-lambda: Lambda process returned error status code: 1. Result: 
{"errorType":"JsonSerializerException",
"errorMessage":"Error converting the Lambda event JSON payload to type Amazon.Lambda.KinesisEvents.KinesisEvent: The JSON value could not be converted to Amazon.Kinesis.EncryptionType. Path: $.Records[0].kinesis.encryptionType | LineNumber: 0 | BytePositionInLine: 308.",
"stackTrace":[
"at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.Deserialize[T](Stream requestStream)",
"at lambda_method(Closure , Stream , Stream , LambdaContextInternal )"],"cause":{"errorType":"JsonException","errorMessage":"The JSON value could not be converted to Amazon.Kinesis.EncryptionType. Path: $.Records[0].kinesis.encryptionType | LineNumber: 0 | BytePositionInLine: 308.","stackTrace":[
"at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)",
"at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack\u0026 state, Utf8JsonReader\u0026 reader)",
"at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack\u0026 state, Utf8JsonReader\u0026 reader)",
"at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader\u0026 reader, ReadStack\u0026 readStack)",
"at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader\u0026 reader)",
"at System.Text.Json.JsonSerializer.ParseCore(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)",
"at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)",
"at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.Deserialize[T](Stream requestStream)"]}}. 
Output:
START RequestId: 5aab3e77-1f04-13a9-0ec8-d8ca8d247c71 Version: $LATEST

Error converting the Lambda event JSON payload to type Amazon.Lambda.KinesisEvents.KinesisEvent: The JSON value could not be converted to Amazon.Kinesis.EncryptionType. Path: $.Records[0].kinesis.encryptionType | LineNumber: 0 | BytePositionInLine: 308.: JsonSerializerException
   at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.Deserialize[T](Stream requestStream)
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ParseCore(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.Deserialize[T](Stream requestStream)
```

**Comment by whummer** [comment]
Thanks for the update @tomaz-tekavec-cko . Can you please share some details about ? Please note that this change may not have been added to a tagged release yet. Can you please try pulling the `latest` image using this command:
```
docker pull localstack/localstack:latest
```
... and then use the `latest` tag in your docker-compose:
```
    image: localstack/localstack-light:latest
```
Hope that helps - please keep us posted. Thanks

**Comment by tomaz-tekavec-cko** [comment]
Sorry for a late response - I've tested the same setup with v0.12.7 and it works fine. Many thanks!
