### ISSUE TITLE
Issue with using lambci/lambda as lambda executor

### ISSUE THREAD

**Issue by njcongtou** [localstack/localstack#333]
I created one Lambda function in NodeJS and setup a separate Elasticsearch container using docker-compose file. I encountered the following issues:

1. My lambda is not able to access s3 bucket in localstack. 

I was changed to s3 client creation to this : 
`
s3 = new aws.S3({ apiVersion: '2006-03-01', endpoint: 'http://localstack:4572' });
`

I have also tried: http://localhost:4572 but still does not work. Even though I know I should not use localhost, since Lambda runs in a separeate container from Localstack one.

`
err: 'UnknownEndpoint: Inaccessible host: 'events-bucket-dev.localhost\'. This service may not be available in the `us-east-1\' region.
`

Since there is no official awslocal client lib in NodeJS, maybe there needs some hacking ?

2. I sent a valid json file to my lambda, which saves this doc into local ES. but I got this error. 

  { message: '[parse_exception] Failed to derive xcontent',
     name: 'Error',
     stack: '[parse_exception] Failed to derive xcontent :: {"path":"/_bulk","query":{},"body":"","statusCode":400,"response":"{\\"error\\":{\\"root_cause\\":[{\\"type\\":\\"parse_exception\\",\\"reason\\":\\"Failed to derive xcontent\\"}],\\"type\\":\\"parse_exception\\",\\"reason\\":\\"Failed to derive xcontent\\"},\\"status\\":400}"}\n    at respond (/var/task/node_modules/elasticsearch/src/lib/transport.js:307:15)\n    at checkRespForFailure (/var/task/node_modules/elasticsearch/src/lib/transport.js:266:7)\n    at HttpConnector.<anonymous> (/var/task/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)\n    at IncomingMessage.bound (/var/task/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)',
     code: undefined,
     signal: undefined },
  msg: '[parse_exception] Failed to derive xcontent',
  time: 2017-09-20T00:52:08.242Z,

3. I triggered lambda using invoke command through Localstack, but I only see some commands printed on the localstack console and it is hard to check the actual logs which should contain the console.log() messages. 

so, I trigger lambda using this command directly in command line : 

docker run -l 883ae42c7bc0,995194d9ec0c --network mynetwork -v "/tmp/localstack/zipfile.176e269b":/var/task --env "AWS_LAMBDA_EVENT_BODY=$(</path/sample_doc.json)" -e HOSTNAME="$HOSTNAME",LOCALSTACK_HOSTNAME="http://localstack:4572" "lambci/lambda:nodejs6.10" "phoenix-pipeline.handler"

At this point, I can see the console.log() messages on the console since I start the lambda using 
lambci/docker-lambda not using Localstack. 

My docker compose file is as follows:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - mynetwork

  lambci:
    image: lambci/lambda:nodejs6.10
    ports:
      - "9900:9900"
    networks:
      - mynetwork
    links:
      - localstack
      - elasticsearch

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4582:4567-4582"
      - "8080:8080"
    environment:
      - DEFAULT_REGION=us-east-1
      - SERVICES=${SERVICES-lambda, kinesis, s3}
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - mynetwork
    links:
      - elasticsearch

networks:
  mynetwork:
    driver: bridge
`

**Comment by njcongtou** [comment]
instead of asking multiple questions, I decide to ask one question at a time.

**Comment by njcongtou** [comment]
https://github.com/localstack/localstack/issues/338
