### ISSUE TITLE
s3_object.get raises internal server error when Range parameter is passed

### ISSUE THREAD

**Issue by mpenkov** [localstack/localstack#3351]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

My lambda function is trying to read an S3 object. When no Range keyword parameter is specified, the reading works fine. When the Range keyword parameter is specified, the lambda code crashes with a ClientError.

## Expected behavior

The read should complete successfully.

## Actual behavior

Uncaught exception is raised.

# Steps to reproduce

## Command used to start LocalStack

    localstack start

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

My handler:

```python
def lambda_handler(*args, **kwargs):
    import os
    import boto3
    os.environ['AWS_ACCESS_KEY_ID'] = os.environ['AWS_SECRET_ACCESS_KEY'] = 'dummy'
    s3 = boto3.resource('s3', endpoint_url='http://172.17.0.2:4566')
    obj = s3.Object('mybucket', 'hello.txt')
    print(obj.get().read())
    print(obj.get(Range='bytes=0-'))  # BOOM!
```

Init:

```
$ awslocal s3api create-bucket --bucket mybucket
$ echo "hello world!" | awslocal s3 cp - s3://mybucket/hello.txt
$ awslocal iam create-role --role-name test-role --assume-role-policy-document '{"Version": "2012-10-17", "Statement": [{"Action": "s3:*", "Effect": "Allow", "Resource": "*"}]}'
$ zip lambda_function.zip lambda_function.py 
$ awslocal s3 cp lambda_function.zip s3://mybucket/lambda_function.zip
$ awslocal lambda create-function --function-name myfunction --runtime python3.8 --role test-role --handler lambda_function.lambda_handler --code S3Bucket=mybucket,S3Key=lambda_function.zip
```

Invoking the function:

    $ awslocal lambda invoke --function-name "arn:aws:lambda:us-east-1:000000000000:function:myfunction" out

In the localstack console, I can see the output of the first print statement:

    b'hello world!\n'

but the second call raises an exception that I can see by examining the output file:

```
$ jq .errorMessage out -r 
Lambda process returned error status code: 1. Result: {"errorType":"ClientError","errorMessage":"An error occurred (500) when calling the GetObject operation (reached max retries: 4): Internal Server Error","stackTrace":["  File \"/var/task/lambda_function.py\", line 8, in lambda_handler\n    print(obj.get(Range='bytes=0-')['Body'].read())  # BOOM!\n","  File \"/var/runtime/boto3/resources/factory.py\", line 520, in do_action\n    response = action(self, *args, **kwargs)\n","  File \"/var/runtime/boto3/resources/action.py\", line 83, in __call__\n    response = getattr(parent.meta.client, operation_name)(*args, **params)\n","  File \"/var/runtime/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n","  File \"/var/runtime/botocore/client.py\", line 676, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}. Output:
START RequestId: d417497a-7478-1502-1881-c8dd7a4f0df1 Version: $LATEST
b'hello world!\n'
[ERROR] ClientError: An error occurred (500) when calling the GetObject operation (reached max retries: 4): Internal Server Error
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 8, in lambda_handler
    print(obj.get(Range='bytes=0-')['Body'].read())  # BOOM!
  File "/var/runtime/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/var/runtime/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/var/runtime/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
END RequestId: d417497a-7478-1502-1881-c8dd7a4f0df1
REPORT RequestId: d417497a-7478-1502-1881-c8dd7a4f0df1  Init Duration: 182.91 ms        Duration: 2805.16 ms    Billed Duration: 2900 ms        Memory Size: 1536 MB    Max Memory Used: 41 MB
```

Of course, when used against live AWS, the above code (reading with a Range parameter) does not raise the error.

**Comment by macnev2013** [comment]
Thanks for reporting the issue @mpenkov . We tried to reproduce the issue with the commands and the lambda function you have provided. But it is working as expected without any errors. Can you give it another try with the latest version of `localstack` ? Thanks.

**Comment by mpenkov** [comment]
I tried with localstack 0.12.4, but the problem is still there.

I upgraded using `pip install -U localstack` and restarted using `localstack start`. Is there anything else I should have done?

**Comment by macnev2013** [comment]
Hey @mpenkov, thanks for the feedback.

Here's the commands which I have used.

Localstack Version
```
localstack --version
0.12.4
```

To start localstack
```
$ DEBUG=1 localstack start
```

Lambda function: **lambda_function.py**
```
def lambda_handler(*args, **kwargs):
    import os
    import boto3
    os.environ['AWS_ACCESS_KEY_ID'] = os.environ['AWS_SECRET_ACCESS_KEY'] = 'test'
    s3 = boto3.resource('s3', endpoint_url='http://172.17.0.2:4566')
    obj = s3.Object('mybucket', 'hello.txt')
    print(obj.get())
    print(obj.get(Range='bytes=0-'))
```

Commands used for deployment
```
$ awslocal s3api create-bucket --bucket mybucket
$ echo "hello world!" >> test.txt
$ awslocal s3 cp hello.txt s3://mybucket/hello.txt
$ awslocal iam create-role --role-name test-role --assume-role-policy-document '{"Version": "2012-10-17", "Statement": [{"Action": "s3:*", "Effect": "Allow", "Resource": "*"}]}'
$ zip lambda_function.zip lambda_function.py 
$ awslocal s3 cp lambda_function.zip s3://mybucket/lambda_function.zip
$ awslocal lambda create-function --function-name myfunction --runtime python3.8 --role test-role --handler $ lambda_function.lambda_handler --code S3Bucket=mybucket,S3Key=lambda_function.zip
```

Invoking lambda function
```
$ awslocal lambda invoke --function-name "arn:aws:lambda:us-east-1:000000000000:function:myfunction" out
```

Output From Localstack
```
> {'ResponseMetadata': {'RequestId': 'FD401A40B31EF203', 'HostId': 'MzRISOwyjmnupFD401A40B31EF2037/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'text/plain', 'content-length': '12', 'content-md5': '/D/5joxqDTCH1RXARz+Gdw==', 'etag': '"fc3ff98e8c6a0d3087d515c0473f8677"', 'last-modified': 'Mon, 04 Jan 2021 17:22:27 GMT', 'access-control-allow-origin': '*', 'x-amz-request-id': 'FD401A40B31EF203', 'x-amz-id-2': 'MzRISOwyjmnupFD401A40B31EF2037/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp', 'accept-ranges': 'bytes', 'content-language': 'en-US', 'cache-control': 'no-cache', 'content-encoding': 'identity', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Mon, 04 Jan 2021 17:22:37 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}, 'AcceptRanges': 'bytes', 'LastModified': datetime.datetime(2021, 1, 4, 17, 22, 27, tzinfo=tzutc()), 'ContentLength': 12, 'ETag': '"fc3ff98e8c6a0d3087d515c0473f8677"', 'CacheControl': 'no-cache', 'ContentEncoding': 'identity', 'ContentLanguage': 'en-US', 'ContentType': 'text/plain', 'Metadata': {}, 'Body': <botocore.response.StreamingBody object at 0x7fd79dcbeca0>}
> {'ResponseMetadata': {'RequestId': 'B81BF7E4F6A703CC', 'HostId': 'MzRISOwyjmnupB81BF7E4F6A703CC7/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp', 'HTTPStatusCode': 206, 'HTTPHeaders': {'content-type': 'text/plain', 'content-length': '12', 'content-range': 'bytes 0-11/12', 'etag': '"fc3ff98e8c6a0d3087d515c0473f8677"', 'last-modified': 'Mon, 04 Jan 2021 17:22:27 GMT', 'access-control-allow-origin': '*', 'x-amz-request-id': 'B81BF7E4F6A703CC', 'x-amz-id-2': 'MzRISOwyjmnupB81BF7E4F6A703CC7/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp', 'accept-ranges': 'bytes', 'content-language': 'en-US', 'cache-control': 'no-cache', 'content-encoding': 'identity', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Mon, 04 Jan 2021 17:22:37 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}, 'AcceptRanges': 'bytes', 'LastModified': datetime.datetime(2021, 1, 4, 17, 22, 27, tzinfo=tzutc()), 'ContentLength': 12, 'ETag': '"fc3ff98e8c6a0d3087d515c0473f8677"', 'CacheControl': 'no-cache', 'ContentEncoding': 'identity', 'ContentLanguage': 'en-US', 'ContentRange': 'bytes 0-11/12', 'ContentType': 'text/plain', 'Metadata': {}, 'Body': <botocore.response.StreamingBody object at 0x7fd79dcbedc0>}
```

**Comment by whummer** [comment]
Thanks for the update @mpenkov - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by mpenkov** [comment]
I updated my image:

```
$ docker images | grep localstack
localstack/localstack   latest      c987fcbeb6ae   8 hours ago    653MB
localstack/localstack   <none>      01144a07c6d9   5 weeks ago    646MB
```

I also noticed that my example below had several typos, so I'm not sure how you guys managed to run it and get the expected output. With the example fixed, I now see a different problem. The invoke call completes successfully, but the output file is completely empty:

```
$ awslocal lambda invoke --function-name "arn:aws:lambda:us-east-1:000000000000:function:myfunction" out
{
    "StatusCode": 200,
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
$ cat out
null
```

and inside the localstack console window I see this:

```
2021-01-16T07:27:22:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "GET /", target header "", auth header "", data "b''"
```

So there are two problems now:

1. No output from the lambda function invocation
2. Unable to read from S3 within the lambda function

Can you please suggest how to work around this? What endpoint_url should I use to read from S3 within the lambda function code?

Updated example below.

---

lambda_function.py:

```python
def lambda_handler(*args, **kwargs):
    print('lambda_handler started')
    import os
    import boto3
    os.environ['AWS_ACCESS_KEY_ID'] = os.environ['AWS_SECRET_ACCESS_KEY'] = 'dummy'
    s3 = boto3.resource('s3', endpoint_url='http://172.17.0.2:4566')
    obj = s3.Object('mybucket', 'hello.txt')
    print(obj.get()['Body'].read())
    print(obj.get(Range='bytes=0-'))  # BOOM!
    print('lambda_handler finished')
```

init.sh:

```bash
awslocal s3api create-bucket --bucket mybucket
echo "hello world!" | awslocal s3 cp - s3://mybucket/hello.txt
awslocal iam create-role --role-name test-role --assume-role-policy-document '{"Version": "2012-10-17", "Statement": [{"Action": "s3:*", "Effect": "Allow", "Resource": "*"}]}'
zip lambda_function.zip lambda_function.py
awslocal s3 cp lambda_function.zip s3://mybucket/lambda_function.zip
awslocal lambda create-function --function-name myfunction --runtime python3.8 --role test-role --handler lambda_function.lambda_handler --code S3Bucket=mybucket,S3Key=lambda_function.zip
awslocal lambda invoke --function-name "arn:aws:lambda:us-east-1:000000000000:function:myfunction" out
```

**Comment by whummer** [comment]
Thanks for the update @mpenkov . Can you try `return`ing a value from your Lambda function handler? The handler result should then get printed to the `out` file. The Lambda logs are by default stored to CloudWatch Logs. You can also retrieve them on the command liny by adding the `--log-type Tail` flag to the `invoke` command.

Please also try to run your Lambda against real AWS and let us know if there are any discrepancies with LocalStack. Thanks

**Comment by mpenkov** [comment]
OK, after using `return` in the lambda function, I can confirm that the object is being read correctly. Thanks for your help!
