### ISSUE TITLE
can not connect to Redshift Cluster

### ISSUE THREAD

**Issue by Am1rr3zA** [localstack/localstack#3359]
# Type of request: This is a ...

[x] bug report
[x] feature request

# Detailed description

I am following all the resource/guide that I could find to work with a localstack's Redshift and so far I only can create a cluster, but can not do anything else.
My goal is to bring up an S3 and Redshift and try to copy data from S3 (CSV file) into Redshift and see it as a table.

I have created the cluster with this command
```
aws --endpoint-url=http://localhost:4566 redshift create-cluster --node-type dc2.large --number-of-nodes 2 --master-username redshift --master-user-password dummy --cluster-identifier localhost --publicly-accessible
```
and I am using this simple python code to connect to my redshfit cluster 

```python
import os
import json
import uuid
import boto3
import psycopg2

redshift = boto3.client('redshift', endpoint_url='http://localhost:4566/')
print (redshift.describe_clusters())
con = psycopg2.connect(dbname='dev', host='localhost.cg034hpkmmjt.us-east-1.redshift.amazonaws.com', port=5439, user='redshift', password='dummy', connect_timeout=10)

```

But I am getting this error
```
Traceback (most recent call last):
  File "src/redshift/localstack.py", line 31, in <module>
    con = psycopg2.connect(dbname='dev', host='localhost.cg034hpkmmjt.us-east-1.redshift.amazonaws.com', port=5439, user='redshift', password='dummy', connect_timeout=10)
  File "/Users/xxx/.pyenv/versions/redshift-sink/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "localhost.cg034hpkmmjt.us-east-1.redshift.amazonaws.com" to address: nodename nor servname provided, or not known
```
...

## Expected behaviour

could connect to Redshift

...

## Actual behaviour

```
Traceback (most recent call last):
  File "src/redshift/localstack.py", line 31, in <module>
    con = psycopg2.connect(dbname='dev', host='localhost.cg034hpkmmjt.us-east-1.redshift.amazonaws.com', port=5439, user='redshift', password='dummy', connect_timeout=10)
  File "/Users/xxx/.pyenv/versions/redshift-sink/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "localhost.cg034hpkmmjt.us-east-1.redshift.amazonaws.com" to address: nodename nor servname provided, or not known
```

...

# Steps to reproduce

```
aws --endpoint-url=http://localhost:4566 redshift create-cluster --node-type dc2.large --number-of-nodes 2 --master-username redshift --master-user-password dummy --cluster-identifier localhost --publicly-accessible
```

## Command used to start LocalStack

I am using docker-compose

```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,redshift
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```python
import os
import json
import uuid
import boto3
import psycopg2

redshift = boto3.client('redshift', endpoint_url='http://localhost:4566/')
print (redshift.describe_clusters())
con = psycopg2.connect(dbname='dev', host='localhost.cg034hpkmmjt.us-east-1.redshift.amazonaws.com', port=5439, user='redshift', password='dummy', connect_timeout=10)

```
...

**Comment by Am1rr3zA** [comment]
@whummer I have seen you have assigned available-in-pro but I don't see this in the services tab?
![Screen Shot 2020-12-15 at 5 22 12 PM](https://user-images.githubusercontent.com/3633422/102377331-85f2f780-3f92-11eb-9cd9-97539507adde.png)

**Comment by greg-md** [comment]
Same issue here. Seems like no one wants to fix it.

**Comment by whummer** [comment]
Thanks for the update @Am1rr3zA , and apologies for the delay. Please note that not all Pro services are represented in the UI yet - we're continuously working on adding new Pro/UI features (we'll also planning to add UI support for Redshift in the near future). Thanks

**Comment by 959210490** [comment]
### Dear @Am1rr3zA 
I see you can connent RedShift by python  ，I want to connent by java or local serve  connent  ,but throw 
`[HY000][500150] [Amazon](500150) Error setting/closing connection: The server closed the connection..`
![image](https://user-images.githubusercontent.com/27666935/108961196-f4021c00-76b1-11eb-958d-d6029a6048b0.png)

### Below is my question:
[https://github.com/localstack/localstack/issues/3637](url)

Hope can help me，thank you

**Comment by Abhishek-kumar-samsung** [comment]
Any solution found for this issue?

I also got similar problem.
