### ISSUE TITLE
"make install" failure on macOS Sierra with complaints about empty files

### ISSUE THREAD

**Issue by biggianteye** [localstack/localstack#337]
I am trying to run `make install` but it consistently fails because apparently the jar files for `amazon_kclpy` are empty:

```bash
ERROR: 'javac -cp "/Users/burhan/projects/localstack/localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.7.6.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.151.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.151.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.151.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.151.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.151.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.151.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/commons-codec-1.9.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/commons-lang-2.6.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/guava-18.0.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/httpclient-4.5.2.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/httpcore-4.4.4.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-core-2.6.6.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-databind-2.6.6.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.6.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jmespath-java-1.11.151.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar:/Users/burhan/projects/localstack/localstack/utils/kinesis/java" /Users/burhan/projects/localstack/localstack/utils/kinesis/java/com/atlassian/*.java': error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.7.6.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.151.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.151.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.151.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.151.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.151.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.151.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/commons-codec-1.9.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/commons-lang-2.6.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/guava-18.0.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/httpclient-4.5.2.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/httpcore-4.4.4.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-core-2.6.6.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-databind-2.6.6.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.6.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jmespath-java-1.11.151.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar; zip file is empty
error: error reading /Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar; zip file is empty
21 errors

Traceback (most recent call last):
  File "localstack/services/install.py", line 169, in <module>
    install_amazon_kinesis_client_libs()
  File "localstack/services/install.py", line 100, in install_amazon_kinesis_client_libs
    run('javac -cp "%s" %s' % (classpath, java_files))
  File "/Users/burhan/projects/localstack/localstack/utils/common.py", line 594, in run
    return do_run(cmd)
  File "/Users/burhan/projects/localstack/localstack/utils/common.py", line 591, in do_run
    raise e
subprocess32.CalledProcessError: Command 'javac -cp "/Users/burhan/projects/localstack/localstack/infra/amazon-kinesis-client/aws-java-sdk-sts.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/amazon-kinesis-client-1.7.6.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-cloudwatch-1.11.151.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-core-1.11.151.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-dynamodb-1.11.151.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kinesis-1.11.151.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-kms-1.11.151.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/aws-java-sdk-s3-1.11.151.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/commons-codec-1.9.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/commons-lang-2.6.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/commons-logging-1.1.3.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/guava-18.0.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/httpclient-4.5.2.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/httpcore-4.4.4.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/ion-java-1.0.2.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-annotations-2.6.0.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-core-2.6.6.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-databind-2.6.6.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jackson-dataformat-cbor-2.6.6.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/jmespath-java-1.11.151.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/joda-time-2.8.1.jar:/Users/burhan/projects/localstack/.venv/lib/python2.7/site-packages/amazon_kclpy/jars/protobuf-java-2.6.1.jar:/Users/burhan/projects/localstack/localstack/utils/kinesis/java" /Users/burhan/projects/localstack/localstack/utils/kinesis/java/com/atlassian/*.java' returned non-zero exit status 1
make: *** [install] Error 1
```

This happens even after having run `make clean` and removing the pip cache (`~/Library/Caches/pip`).

I've checked the files and they are indeed zero byte files. I'm not sure what generates them and therefore don't know what to look at next.

**Comment by whummer** [comment]
Thanks for reporting @biggianteye . Can you please try a fresh install via 
```
make reinstall-p2
```
If that doesn't work, then maybe this does:
```
(. .venv/bin/activate; pip install --no-cache amazon-kclpy)
make install
```

**Comment by biggianteye** [comment]
Both sets of command result in the same error, as above.

**Comment by biggianteye** [comment]
Here's the output.

```
make reinstall-p2
```
[output.txt](https://github.com/localstack/localstack/files/1321327/output.txt)

```
(. .venv/bin/activate; pip install --no-cache amazon-kclpy)
make install
```
[output2.txt](https://github.com/localstack/localstack/files/1321335/output2.txt)

**Comment by whummer** [comment]
`output2.txt` does not seem to contain the output of `(. .venv/bin/activate; pip install --no-cache amazon-kclpy)`. Did you run this command as well? The installation of `amazon-kclpy` is a bit annoying sometimes, but there should be a way to delete the cache of your local python/pip installation, in order to force `pip install` to re-download the jar files.

**Comment by biggianteye** [comment]
It's the first seven lines of the file. I chained the two commands together (using `&&`), hence why all the output is in the file without separators. Not helpful of me in hindsight.

Here are the lines you were asking about:

```
Requirement already satisfied: amazon-kclpy in ./.venv/lib/python2.7/site-packages
Requirement already satisfied: boto in ./.venv/lib/python2.7/site-packages (from amazon-kclpy)
Requirement already satisfied: mock in ./.venv/lib/python2.7/site-packages (from amazon-kclpy)
Requirement already satisfied: argparse in ./.venv/lib/python2.7/site-packages (from amazon-kclpy)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in ./.venv/lib/python2.7/site-packages (from mock->amazon-kclpy)
Requirement already satisfied: pbr>=0.11 in ./.venv/lib/python2.7/site-packages (from mock->amazon-kclpy)
Requirement already satisfied: six>=1.9 in ./.venv/lib/python2.7/site-packages (from mock->amazon-kclpy)
```

> The installation of amazon-kclpy is a bit annoying sometimes, but there should be a way to delete the cache of your local python/pip installation, in order to force pip install to re-download the jar files.

I mentioned that I removed my pip cache by deleting `~/Library/Caches/pip`. Is this what you are suggesting?

One thing that may be of note is that the build step for `amazon-kclpy` has consistently taken a surprisingly long time. Long enough that I have stopped watching it and gone off to do other things (and therefore I have no measurement to provide)

```
Building wheels for collected packages: airspeed, amazon-kclpy, docopt, flask, flask-swagger, jsonpath-rw, localstack-ext, psutil, pyYAML, subprocess32-ext, xmltodict, itsdangerous, ply, dnslib, pyaes, pyminifier, srp-ext, warrant-ext, dicttoxml, configparser, MarkupSafe, python-jose-ext, pycryptodome, future, pycparser
  Running setup.py bdist_wheel for airspeed ... done
  Stored in directory: /Users/burhan/Library/Caches/pip/wheels/a5/2f/6e/5779d7a7d4b619c8db34be4721eb3dc27d8c8754a3f7ae26c5
  Running setup.py bdist_wheel for amazon-kclpy ... -
```

**Comment by whummer** [comment]
Ah sorry, my bad. I think it needs to be un-installed first:
```
(. .venv/bin/activate; pip uninstall -y amazon-kclpy; pip install --no-cache amazon-kclpy)
make install
```

**Comment by biggianteye** [comment]
I fired off the first command and then forgot about it as I was getting on with some work. Coming back to it a couple of hours later I see that the command still has not completed. This does not seem correct:

```
Uninstalling amazon-kclpy-1.4.5:
  Successfully uninstalled amazon-kclpy-1.4.5
Collecting amazon-kclpy
  Downloading amazon_kclpy-1.4.5.tar.gz
Requirement already satisfied: boto in ./.venv/lib/python2.7/site-packages (from amazon-kclpy)
Requirement already satisfied: argparse in ./.venv/lib/python2.7/site-packages (from amazon-kclpy)
Requirement already satisfied: mock in ./.venv/lib/python2.7/site-packages (from amazon-kclpy)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in ./.venv/lib/python2.7/site-packages (from mock->amazon-kclpy)
Requirement already satisfied: pbr>=0.11 in ./.venv/lib/python2.7/site-packages (from mock->amazon-kclpy)
Requirement already satisfied: six>=1.9 in ./.venv/lib/python2.7/site-packages (from mock->amazon-kclpy)
Installing collected packages: amazon-kclpy
  Running setup.py install for amazon-kclpy: started
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
    Running setup.py install for amazon-kclpy: still running...
```

**Comment by biggianteye** [comment]
Typical that the moment I post that, it finishes! Here's the output of the commands including uninstallation of `amazon-kclpy`. Unfortunately the result is the same failure.

[output.txt](https://github.com/localstack/localstack/files/1329176/output.txt)

I've included the commands in the output this time.

**Comment by biggianteye** [comment]
@whummer Is there anything else you would like me to try, or any further information I can provide?

**Comment by avizana** [comment]
@biggianteye did you find a solution eventually?

**Comment by JsonFn** [comment]
An observation is the empty zip files are located under `.venv/local/lib/python2.7/site-packages/amazon_kclpy/jars`, which actually should be symbolic links from `.venv/lib/python2.7/site-packages/amazon_kclpy/jars`. In fact it's .venv/local/lib symbolic linked from .venv/lib. 

But not sure why pip within localstack venv installs empty jar files because (after failing first time then) doing

1. source .venv/bin/activate 

2. pip uninstall amazon_kclpy 

3. pip install amazon_kclpy 

shows installed amazon_kclpy jars are NOT empty. This is the reason why localstack execution fails.  

A temporary solution I find is 

1. Reinstall amazon_kclpy within /tmp/localstack_install_dir's venv environment (it could be done by reinstalling amazon_kclpy mentioned above)

2. Comment out the end line in Makefile **install** task. 
    install:           ## Install dependencies in virtualenv
    ...
    (test ! -e requirements.txt || ($(VENV_RUN); $(PIP_CMD) install -q six==1.10.0 ; $(PIP_CMD) -q install -r requirements.txt) # && \
    ## $(VENV_RUN); PYTHONPATH=. exec python localstack/services/install.py testlibs)

A precondition is you need to have a successful built version of $HOME/.local

**Comment by biggianteye** [comment]
@avizana No, and I gave up after I stopped getting responses.

**Comment by whummer** [comment]
Closing as outdated / obsolete. Please create a follow-up issue if the problem persists. Thanks
