### ISSUE TITLE
botocore.parsers.ResponseParserError on RDS instance creation

### ISSUE THREAD

**Issue by holyoaks** [localstack/localstack#3386]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description

Receiving an error when trying to create an RDS instance
```python
botocore.parsers.ResponseParserError: Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
b'{}'
```

## Expected behavior

My code attempts to bootstrap a default RDS instance via a Celery task after the Docker container starts up and all localstack services are available. The code is very basic:

```python
        client = boto3.client(
            "rds",
            region_name="us-east-1",
            endpoint_url="http://host.docker.internal:4566/",
        )
        response = client.create_db_instance(
            DBName=client_settings["database_name"],
            DBInstanceIdentifier=client_settings["database_identifier"],
            AllocatedStorage=100,
            DBInstanceClass="db.t3.small",
            Engine="postgres",
            MasterUsername=client_settings["database_username"],
            MasterUserPassword=client_settings["database_password"],
            EngineVersion="12.4",
            AutoMinorVersionUpgrade=True,
            PubliclyAccessible=True,
        )
```

## Actual behavior

The RDS instance is ACTUALLY created, but the response received is invalid (appears to be empty json bytes). The full celery trace is below:

```
[2020-12-21 16:44:23,816: ERROR/ForkPoolWorker-2] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/botocore/parsers.py", line 451, in _parse_xml_string_to_dom
    parser.feed(xml_string)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/app/tasks/celery_tasks.py", line 130, in create_client_database
    response = client.create_db_instance(
  File "/usr/local/lib/python3.8/dist-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/botocore/client.py", line 662, in _make_api_call
    http, parsed_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/botocore/client.py", line 682, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.8/dist-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.8/dist-packages/botocore/endpoint.py", line 134, in _send_request
    success_response, exception = self._get_response(
  File "/usr/local/lib/python3.8/dist-packages/botocore/endpoint.py", line 166, in _get_response
    success_response, exception = self._do_get_response(
  File "/usr/local/lib/python3.8/dist-packages/botocore/endpoint.py", line 217, in _do_get_response
    parsed_response = parser.parse(
  File "/usr/local/lib/python3.8/dist-packages/botocore/parsers.py", line 243, in parse
    parsed = self._do_error_parse(response, shape)
  File "/usr/local/lib/python3.8/dist-packages/botocore/parsers.py", line 505, in _do_error_parse
    root = self._parse_xml_string_to_dom(xml_contents)
  File "/usr/local/lib/python3.8/dist-packages/botocore/parsers.py", line 454, in _parse_xml_string_to_dom
    raise ResponseParserError(
botocore.parsers.ResponseParserError: Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
b'{}'
```

# Steps to reproduce

## Command used to start LocalStack

docker-compose

docker-compose.yml shown below:
```
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRON: dev
    depends_on:
      - localstack
      - rabbitmq
      - redis
    environment:
      - AWS_ACCESS_KEY_ID='FakeAccessKey'
      - AWS_SECRET_ACCESS_KEY='FakeSecretAccessKey'
      - AWS_DEFAULT_REGION=us-east-1
      - WAIT_HOSTS=rabbitmq:4369, rabbitmq:5672, rabbitmq:25672, rabbitmq:15672, redis:6379, db:5432, localstack:4566
      - WAIT_HOSTS_TIMEOUT=60
      - WAIT_BEFORE_HOSTS=30
    ports:
      - "8001:80"
    command: sh -c "/wait && circusd /srv/circus.ini --log-output /var/log/circusd.log"

  rabbitmq:
    image: "bitnami/rabbitmq:3.7"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"

  redis:
    image: "bitnami/redis:6.0.9"
    environment:
      - REDIS_PASSWORD=password123
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "443:443"
      - "4510-4520:4510-4520"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,dynamodb,rds
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - LOCALSTACK_API_KEY=########
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "s3data:/tmp/localstack/data/s3"
      - "dynamodata:/tmp/localstack/data/ddb"
      - "rdsdata:/tmp/localstack/data/rds"

  celery-flower:
    image: gregsi/latest-celery-flower-docker:latest
    environment:
      - AMQP_USERNAME=user
      - AMQP_PASSWORD=bitnami
      - AMQP_ADMIN_USERNAME=user
      - AMQP_ADMIN_PASSWORD=bitnami
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_ADMIN_HOST=rabbitmq
      - AMQP_ADMIN_PORT=15672
      - FLOWER_BASIC_AUTH=user:test
    ports:
      - "5555:5555"

volumes:
  dynamodata:
  rdsdata:
  s3data:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local

```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

see above

**Comment by holyoaks** [comment]
@whummer , I am unable to recreate this behavior at this time. The script is running fine with no errors. The only thing I can think of is that since celery caches the task code, somehow I had a bug in the task that caused this response (what, I have no idea, as the RDS instance was actually created). I've rebuilt my Docker app 5 times and run this script 5 times since reporting the issue and I cannot reproduce it. I'll let you decide whether or not to close the issue. Thanks.

**Comment by whummer** [comment]
Thanks for the update @holyoaks - going to close the issue for now, but please feel free to re-open with steps to reproduce if the problem occurs again. Thanks for your help!
