### ISSUE TITLE
Deleting dynamodb tables is broken on 0.12.5

### ISSUE THREAD

**Issue by canassa** [localstack/localstack#3467]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When you try to delete a non-existing dynamodb table localstack crashes with the following error

```
 2021-01-14T10:21:22:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: 'NoneType' object has no attribute 'split' Traceback (most recent call last):
   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 107, in index
     raise result
   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 581, in run
     result = self.func(self.params)
   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
     return fn(*args, **kwargs)
   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 597, in handler
     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 365, in modify_and_forward
     listener_result = listener.forward_request(method=method,
   File "/opt/code/localstack/localstack/services/edge.py", line 104, in forward_request
     return do_forward_request(api, method, path, data, headers, port=port)
   File "/opt/code/localstack/localstack/services/edge.py", line 115, in do_forward_request
     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
   File "/opt/code/localstack/localstack/services/edge.py", line 135, in do_forward_request_inmem
     response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 433, in modify_and_forward
     updated_response = update_listener.return_response(**kwargs)
   File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_listener.py", line 358, in return_response
     dynamodbstreams_api.delete_streams(table_arn)
   File "/opt/code/localstack/localstack/services/dynamodbstreams/dynamodbstreams_api.py", line 64, in delete_streams
     table_arn = aws_stack.dynamodb_table_arn(table_arn)
   File "/opt/code/localstack/localstack/utils/aws/aws_stack.py", line 412, in dynamodb_table_arn
     table_name = table_name.split(':table/')[-1]
 AttributeError: 'NoneType' object has no attribute 'split'
 ```

## Expected behavior

Localstack should return a `ResourceNotFoundException` error instead

## Actual behavior

Localstack crashes

# Steps to reproduce

It's fairly easy to reproduce:

```
import boto3

client = boto3.client(
    "dynamodb",
    endpoint_url="http://localhost:4566",
    aws_access_key_id="aaa",
    aws_secret_access_key="aaa",
    aws_session_token="bbb"
)

client.delete_table(TableName="aaa")
```

## Command used to start LocalStack

Via docker-compose:

```
services:
  localstack:
    image: localstack/localstack:0.12.4
    ports:
      # Edge
      - 4566:4566
    environment:
      - SERVICES=sqs,kinesis,sts,dynamodb
      - DEFAULT_REGION=eu-west-1
```

**Comment by whummer** [comment]
Thanks for reporting @canassa . This should be fixed in #3484 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks
