### ISSUE TITLE
Lambda event notification

### ISSUE THREAD

**Issue by udadi-az** [localstack/localstack#3511]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
I am facing an issue with create object event on an S3 bucket which would invoke a lambda function. I have this code snippet which is written in Typescript and deployed using aws-cdk-local:

```
const bucket = new s3.Bucket(this, 'SampleBucket', {bucketName: 'bucket'});
const notification = new s3n.LambdaDestination(s3notificationLambda);
bucket.addEventNotification(s3.EventType.OBJECT_CREATED, notification);
```

But this doesn't work. I see the following in the logs:

```
> 2021-01-26T00:22:19.862Z	a1288e3b-02c3-1dc0-f45c-87bf77674b40	ERROR	2e110d2b arn:aws:cloudformation:us-east-1:000000000000:stack/HelloWorldStack/id-123 SampleBucketNotifications33C0B0AB {
>   "RequestType": "Create",
>   "ResponseURL": "http://172.17.0.2:4566/localstack-cf-custom-resources-results/059cd382?AWSAccessKeyId=test&Signature=aa%2FNC%2BATVkPY%2BLWYOiX5bPcLF20%3D&Expires=1611624136",
>   "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/HelloWorldStack/id-123",
>   "RequestId": "2e110d2b",
>   "ResourceType": "Custom::S3BucketNotifications",
>   "LogicalResourceId": "SampleBucketNotifications33C0B0AB",
>   "ResourceProperties": {
>     "ServiceToken": "arn:aws:lambda:us-east-1:000000000000:function:HelloWorldStack-lambda-ecd259a4",
>     "BucketName": "bucket",
>     "NotificationConfiguration": {
>       "LambdaFunctionConfigurations": [
>         {
>           "Events": [
>             "s3:ObjectCreated:*"
>           ],
>           "LambdaFunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:lambda-name"
>         }
>       ]
>     }
>   }
> }
> 2021-01-26T00:22:19.926Z	a1288e3b-02c3-1dc0-f45c-87bf77674b40	ERROR	2e110d2b arn:aws:cloudformation:us-east-1:000000000000:stack/HelloWorldStack/id-123 SampleBucketNotifications33C0B0AB { err: null, data: {} }
> 2021-01-26T00:22:19.927Z	a1288e3b-02c3-1dc0-f45c-87bf77674b40	ERROR	2e110d2b arn:aws:cloudformation:us-east-1:000000000000:stack/HelloWorldStack/id-123 SampleBucketNotifications33C0B0AB { responseBody:
>    '{"Status":"SUCCESS","Reason":"See the details in CloudWatch Log Stream: 2021/01/26/[$LATEST]fffbbc77054649908dc532e12f6c1561","PhysicalResourceId":"SampleBucketNotifications33C0B0AB","StackId":"arn:aws:cloudformation:us-east-1:000000000000:stack/HelloWorldStack/id-123","RequestId":"2e110d2b","LogicalResourceId":"SampleBucketNotifications33C0B0AB","NoEcho":false}' }
> 2021-01-26T00:22:19.968Z	a1288e3b-02c3-1dc0-f45c-87bf77674b40	ERROR	2e110d2b arn:aws:cloudformation:us-east-1:000000000000:stack/HelloWorldStack/id-123 SampleBucketNotifications33C0B0AB { statusCode: 200, statusMessage: '' }
```
I also tried this based on what I found here: https://stackoverflow.com/questions/58087772/aws-cdk-how-to-add-an-event-notification-to-an-existing-s3-bucket

```
const bucket = new s3.Bucket(this, 'SampleBucket', {bucketName: 'bucket'});
const rsrc = new AwsCustomResource(this, 'S3NotificationResource', {
          onCreate: {
              service: 'S3',
              action: 'putBucketNotificationConfiguration',
              parameters: {
                  // This bucket must be in the same region you are deploying to
                  Bucket: bucket.bucketName,
                  NotificationConfiguration: {
                      LambdaFunctionConfigurations: [
                          {
                              Events: ['s3:ObjectCreated:*'],
                              LambdaFunctionArn: s3notificationLambda.functionArn
                          }
                      ]
                  }
              },
              // Always update physical ID so function gets executed
              physicalResourceId: PhysicalResourceId.of('S3NotifCustomResource' + Date.now().toString())
          },
          policy: AwsCustomResourcePolicy.fromStatements([new iam.PolicyStatement({
              actions: ["S3:PutBucketNotification"],
              // allow this custom resource to modify this bucket
              resources: [bucket.bucketArn],
          })]),
          logRetention: logs.RetentionDays.ONE_DAY,
      });

      s3notificationLambda.addPermission('AllowS3Invocation', {
          action: 'lambda:InvokeFunction',
          principal: new iam.ServicePrincipal('s3.amazonaws.com'),
          sourceArn: bucket.bucketArn
      });

      rsrc.node.addDependency(s3notificationLambda.permissionsNode.findChild('AllowS3Invocation'));
```

This doesn't work either. Here is a snippet from the logs:

```
> START RequestId: 4b006b83-f5b2-1a02-0430-a470c16754c1 Version: $LATEST
> 2021-01-25T23:00:01.236Z	4b006b83-f5b2-1a02-0430-a470c16754c1	INFO	{"RequestType":"Create","ResponseURL":"http://172.17.0.2:4566/localstack-cf-custom-resources-results/607074ae?AWSAccessKeyId=test&Signature=wjt2%2FSYoWQptRzeH4eNXCwK2i6k%3D&Expires=1611619198","StackId":"arn:aws:cloudformation:eu-west-1:000000000000:stack/HelloWorldStack/id-123","RequestId":"5205fc30","ResourceType":"Custom::AWS","LogicalResourceId":"S3NotificationResourceF98D77E7","ResourceProperties":{"ServiceToken":"arn:aws:lambda:us-east-1:000000000000:function:HelloWorldStack-lambda-9265d656","Create":{"service":"S3","action":"putBucketNotificationConfiguration","parameters":{"Bucket":"inbound","NotificationConfiguration":{"LambdaFunctionConfigurations":[{"Events":["s3:ObjectCreated:*"],"LambdaFunctionArn":"arn:aws:lambda:us-east-1:000000000000:function:lambda-name"}]}},"physicalResourceId":{"id":"S3NotifCustomResource1611615589200"}},"InstallLatestAwsSdk":true}}
> 2021-01-25T23:00:01.240Z	4b006b83-f5b2-1a02-0430-a470c16754c1	INFO	AWS SDK VERSION: 2.631.0
> 2021-01-25T23:00:01.348Z	4b006b83-f5b2-1a02-0430-a470c16754c1	INFO	Responding {"Status":"SUCCESS","Reason":"OK","PhysicalResourceId":"S3NotifCustomResource1611615589200","StackId":"arn:aws:cloudformation:us-east-1:000000000000:stack/HelloWorldStack/id-123","RequestId":"5205fc30","LogicalResourceId":"S3NotificationResourceF98D77E7","NoEcho":false,"Data":{"apiVersion":null,"region":"us-east-1"}}
> END RequestId: 4b006b83-f5b2-1a02-0430-a470c16754c1
> REPORT RequestId: 4b006b83-f5b2-1a02-0430-a470c16754c1	Init Duration: 2144.10 ms	Duration: 458.57 ms	Billed Duration: 500 ms	Memory Size: 1536 MB	Max Memory Used: 0 MB	
> Starting daemons...
> Starting server loop on UDP port 2000
> Starting DNS server loop on UDP port 53
> Starting DNS server loop on UDP port 53
2021-01-25T23:00:02:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Custom::AWS PhysicalResourceId
2021-01-25T23:00:02:INFO:localstack.utils.cloudformation.template_deployer: Unable to determine PhysicalResourceId for "Custom::AWS" resource, ID "S3NotificationResourceF98D77E7"
```

But if I use cli to create the notification:

```
awslocal s3api put-bucket-notification-configuration --bucket bucket --notification-configuration file://notification.json
```
where notification.json looks like this:
```
{
    "LambdaFunctionConfigurations": [
        {
            "LambdaFunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:lambda-name",
            "Events": [
                "s3:ObjectCreated:*"
            ]
        }
    ]
}
```
this works. It creates the notification on the bucket and the lambda gets invoked whenever I put add a file in the bucket.
I tried a couple of alternative ways of creating the notification in Typescript:
```
   //Method 3
   s3notificationLambda.addEventSource(new S3EventSource(bucket, {events: [s3.EventType.OBJECT_CREATED]}));

    //Method 4
    const topic = new sns.Topic(this, 'Topic');
    bucket.addEventNotification(s3.EventType.OBJECT_CREATED, new s3n.SnsDestination(topic));
    s3notificationLambda.addEventSource(new SnsEventSource(topic));
```
None of these alternatives work.
...

## Expected behavior
Adding any file into a bucket with put bucket notification event on it should invoke the associated Lambda function. This command should show the notification event created:
```
awslocal s3api get-bucket-notification-configuration --bucket bucket
```
...

## Actual behavior
Notification event is not getting created. The above command returns empty response:

...

# Steps to reproduce
Described above

## Command used to start LocalStack
LOCALSTACK_API_KEY=...
DEBUG=1 localstack start
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by mgagliardo** [comment]
Hey @udadi-az can you please take a look at https://github.com/localstack/localstack/issues/3183 and see if it helps you? I feel that (besides you are using the CDK) the issue is tightly coupled to this one. Let me know. Cheers.

**Comment by udadi-az** [comment]
@mgagliardo It is working for me if I am using cli command and perhaps it will work if using serverless.yml. But it is not working when using aws-cdk-local for deployment. Perhaps it is not Localstack issue, but aws-cdk-local issue or CloudFormation related issue. We use aws-cdk for infrastructure code and we want to make it work with it if possible.  
If there is a good workaround while using aws-cdk-local, I would take it.

**Comment by udadi-az** [comment]
It believe this is related to CloudFormation custom resources:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources.html

Does Localstack CloudFormation have support for custom resources?

**Comment by phillippbertram** [comment]
Is there any news here? Unfortunately it still doesn't work for me with `localstack:0.12.11` and a valid api key when trying to add a `S3EventSource` to my lambda function 😕 

```typescript
myLambda.addEventSource(
    new S3EventSource(uploadBucket, {
        events: [s3.EventType.OBJECT_CREATED, s3.EventType.OBJECT_REMOVED],
    })
 );
```

I am getting the following errors during deployment:

```
localstack_main | > INIT: Using Lambda API Runtime target host: 'cdklocalstackplayground-lambda-73b4d8e9.eu-central-1.localhost.localstack.cloud:4566'

localstack_main | > INIT: Starting daemons...

localstack_main | > INIT: Host 'cdklocalstackplayground-lambda-73b4d8e9.eu-central-1.localhost.localstack.cloud' resolves to '172.17.0.2'

localstack_main | > Starting XRay server loop on UDP port 2000

localstack_main | > Starting DNS server loop on UDP port 53

localstack_main | > -----

localstack_main | 2021-05-20T08:35:36:INFO:localstack_ext.services.cloudformation.service_models: Unable to fetch CF custom resource result from s3://localstack-cf-custom-resources-results/ae739270 . Existing keys: []

localstack_main | 2021-05-20T08:35:36:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "CDKLocalStackPlayground": An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist. Traceback (most recent call last):

localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1816, in _run

localstack_main | self.do_apply_changes_in_loop(changes, stack, stack_name)

localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1867, in do_apply_changes_in_loop

localstack_main | self.apply_change(change, stack, new_resources, stack_name=stack_name)

localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1920, in apply_change

localstack_main | result = deploy_resource(resource_id, new_resources, stack_name)

localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 933, in deploy_resource

localstack_main | return execute_resource_action(resource_id, resources, stack_name, ACTION_CREATE)

localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1032, in execute_resource_action

localstack_main | result = func['function'](resource_id, resources, resource_type, func, stack_name)

localstack_main | File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cloudformation/service_models.py", line 73, in create_custom_resource

localstack_main | File "/opt/code/localstack/localstack/utils/common.py", line 630, in retry

localstack_main | raise raise_error

localstack_main | File "/opt/code/localstack/localstack/utils/common.py", line 626, in retry

localstack_main | return function(**kwargs)

localstack_main | File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cloudformation/service_models.py", line 70, in fetch_result

localstack_main | File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/aws/aws_utils.py", line 106, in download_s3_object

localstack_main | File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call

localstack_main | return self._make_api_call(operation_name, kwargs)

localstack_main | File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call

localstack_main | raise error_class(parsed_response, operation_name)

localstack_main | botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

localstack_main |
```

**Comment by whummer** [comment]
Thanks for the update @phillippbertram . This is an issue related to S3 presigned URLs - we're currently looking into it. In the meantime, can you please try enabling `S3_SKIP_SIGNATURE_VALIDATION=1` in the LocalStack container, to disable the signature validation? Thanks

**Comment by phillippbertram** [comment]
Thanks @whummer for the quick reply. With `S3_SKIP_SIGNATURE_VALIDATION=1` enabled, I now can successfully deploy the local stack 👌  
Unfortunately, the EventSource configuration is missing (nothing is listed in the `Event Sources Mappings` tab for the lambda function on https://app.localstack.cloud) after deployment, and the Lambda function is not called after an upload to the s3 bucket. However, the Cloudformation template contains the corresponding configuration.

I will see if this is a layer 8 problem. But if you have any advice there directly as well, feel free to share 🙂

**Comment by abbaseya** [comment]
I'm having the same issue and setting `S3_SKIP_SIGNATURE_VALIDATION =1` does not resolve anything. I'm getting the following error when deploying lambda functions using serverless:
```
2021-11-20T02:34:03.803:INFO:localstack_ext.services.cloudformation.service_models: Unable to fetch CF custom resource result from s3://localstack-cf-custom-resources-results/96ae0cb4 . Existing keys: []
```
Any idea how to get around this?

**Comment by phackwer** [comment]
I have same error, and as @abbaseya I already setup the s3 skip signature validation parameter. Is there any other things that we can do?

I'm currently trying to deploy AWS FHIR Works locally, I've had to change the install script to call awslocal instead of aws cli, and I also added the Serverless-localstack plugin set for local stage, I've put my trial key to get Cognito, and the scripts goes quite well till I've have this error coming up and it stops and I can't go any further. Resources allocated everywhere: cognito, s3, lambas, etc, but then it dies on this error and the serveless cloudformation is not created.

Help on this would be really appreciated.

**Comment by whummer** [comment]
Hi @phackwer , thanks for the update, and apologies for the long delay. Can you please share your full configuration (e.g., `docker-compose.yml`) - the error message `Unable to fetch CF custom resource result` often indicates that the Lambda function that deploys a CloudFormation Custom Resource is unable to connect to the LocalStack APIs, potentially because it relies on the DNS to be available and exposed on port 53. 

If you can share a few more details about the config and sample app, that would be super useful for us to replicate the use case end-to-end.. Thanks!
