### ISSUE TITLE
Cannot redeploy lambda after function code change using CDK (specific to MacOS Catalina)

### ISSUE THREAD

**Issue by minhio** [localstack/localstack#3516]
[localstack.zip](https://github.com/localstack/localstack/files/5874812/localstack.zip)
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

OS: MacOS Catalina 10.15.7
localstack 0.12.5
CDK 1.86.0

When deploying lambda via cdklocal with legacy bootstrapping, the first deployment deploys successfully. Subsequent deployments also works, as long as no changes are made to the lambda function codes. When changes are made to the function codes, localstack will throw an exception when trying to redeploy.

This happens on MacOS Catalina. On MacOS Big Sur, the first deployment failed altogether, issue reported here https://github.com/localstack/localstack/issues/3510
 
## Expected behavior

Successful redeployment of lambda after code changes.

## Actual behavior

- cdklocal stuck at "creating CloudFormation changeset"

- localstack throws exception

```
my-localstack | 2021-01-26T16:28:15:ERROR:cloudformation_api: Exception on / [POST]
my-localstack | Traceback (most recent call last):
my-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
my-localstack |     response = self.full_dispatch_request()
my-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
my-localstack |     rv = self.handle_user_exception(e)
my-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
my-localstack |     return cors_after_request(app.make_response(f(*args, **kwargs)))
my-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
my-localstack |     reraise(exc_type, exc_value, tb)
my-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
my-localstack |     raise value
my-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
my-localstack |     rv = self.dispatch_request()
my-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
my-localstack |     return self.view_functions[rule.endpoint](**req.view_args)
my-localstack |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 529, in handle_request
my-localstack |     result = func(req_params)
my-localstack |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 420, in execute_change_set
my-localstack |     deployer.apply_change_set(change_set)
my-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1656, in apply_change_set
my-localstack |     change_set.changes = self.apply_changes(change_set.stack, change_set, stack_name=change_set.stack_name)
my-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1847, in apply_changes
my-localstack |     return self.apply_changes_in_loop(changes, old_stack, stack_name)
my-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1893, in apply_changes_in_loop
my-localstack |     raise Exception('Resource deployment loop completed, pending resource changes: %s' % changes)
my-localstack | Exception: Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Modify', 'LogicalResourceId': 'lambda8B5974B5', 'PhysicalResourceId': None, 'ResourceType': 'AWS::Lambda::Function', 'Replacement': 'False', 'ChangeSetId': None}}]
```

# Steps to reproduce

## Command used to start LocalStack

`docker-compose up` 

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Please see attached zip file for all files.

1. `npm install`
2. `cdklocal bootstrap`
3. `cdklocal deploy`
4. make changes to lambda/main.py
5. `cdklocal deploy` (fails here)

docker-compose.yml

```
version: '3'
services:
  localstack:
    container_name: my-localstack
    image: localstack/localstack:0.12.5
    ports:
      - '4566:4566'
    environment:
      - SERVICES=iam,cloudformation,sts,s3,lambda
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      - HOST_TMP_FOLDER=$TMPDIR
      - START_WEB=0
      - DEBUG=1
    volumes:
      - './docker/localstack/data:/tmp/localstack'
```

package.json

```
{
  "name": "localstack",
  "version": "1.0.0",
  "description": "",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@aws-cdk/aws-lambda": "^1.86.0",
    "@aws-cdk/core": "^1.86.0",
    "@types/node": "^14.14.22",
    "aws-cdk": "^1.86.0",
    "aws-cdk-local": "^1.65.3",
    "source-map-support": "^0.5.19",
    "ts-node": "^9.1.1",
    "typescript": "^4.1.3"
  }
}
```

cdk.json

```
{
  "app": "npx ts-node --prefer-ts-exts app.ts",
  "context": {
    "@aws-cdk/core:enableStackNameDuplicates": "true",
    "aws-cdk:enableDiffNoFail": "true",
    "@aws-cdk/core:stackRelativeExports": "true",
    "@aws-cdk/aws-ecr-assets:dockerIgnoreSupport": true,
    "@aws-cdk/aws-secretsmanager:parseOwnedSecretName": true,
    "@aws-cdk/aws-kms:defaultKeyPolicies": true
  }
}
```

app.ts

```
#!/usr/bin/env node

import {App, Stack, StackProps} from "@aws-cdk/core";
import * as lambda from '@aws-cdk/aws-lambda';
import path from "path";

export class Localstack extends Stack {
    constructor (scope: App, id: string, props?: StackProps) {
        super(scope, id, props);

        new lambda.Function(this, 'lambda', {
            runtime: lambda.Runtime.PYTHON_3_8,
            handler: 'main.lambda_handler',
            code: lambda.Code.fromAsset(path.join(__dirname, 'lambda'))
        });
    }
}

const app = new App();
new Localstack(app, 'localstack')
```

**Comment by whummer** [comment]
Thanks for sharing these details @minhio . Can you please pull the `latest` Docker image and give it another try? Seems like re-deploys (with changes in the Lambda handler) are now working (we've pushed a few CloudFormation fixes recently):

```
2021-01-28T18:30:15:DEBUG:localstack.services.cloudformation.service_models: Updating code for Lambda "localstack-lambda-abd98abd" from location: {'S3Bucket': 'cdktoolkit-stagingbucket-2249f8aa', 'S3Key': 'assets/1bc4a08143f73c836586df1641ac948009ab9c246220252394cd23a80de0dbff.zip'}
```

Hope that helps - please keep us posted. Thanks

**Comment by minhio** [comment]
> Thanks for sharing these details @minhio . Can you please pull the `latest` Docker image and give it another try? Seems like re-deploys (with changes in the Lambda handler) are now working (we've pushed a few CloudFormation fixes recently):
> 
> ```
> 2021-01-28T18:30:15:DEBUG:localstack.services.cloudformation.service_models: Updating code for Lambda "localstack-lambda-abd98abd" from location: {'S3Bucket': 'cdktoolkit-stagingbucket-2249f8aa', 'S3Key': 'assets/1bc4a08143f73c836586df1641ac948009ab9c246220252394cd23a80de0dbff.zip'}
> ```
> 
> Hope that helps - please keep us posted. Thanks

hey @whummer, just tested this with latest image and it is working as expected. thanks!
