### ISSUE TITLE
Cannot access web UI - index.html not found

### ISSUE THREAD

**Issue by selketdaly** [localstack/localstack#3551]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

After starting LocalStack, and then trying to access the UI, a 500 error is thrown. The following appears in the logs:

```
2021-02-03T15:13:33:ERROR:app: Exception on / [GET]

Traceback (most recent call last):

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/code/localstack/localstack/dashboard/api.py", line 113, in hello
return render_template('index.html')
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
ctx.app.jinja_env.get_or_select_template(template_name_or_list),
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
return self.get_template(template_name_or_list, parent, globals)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
return self._load_template(name, self.make_globals(globals))
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
template = self.loader.load(self, name, globals)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/jinja2/loaders.py", line 115, in load
source, filename, uptodate = self.get_source(environment, name)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
return self._get_source_fast(environment, template)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
```

See docker snippet in client code below for docker-compose configuration

## Expected behavior
To see the LocalStack UI at http://localhost:9000

## Actual behavior
A white label error page for 500 error

# Steps to reproduce
Using Docker Desktop 3.0.1

## Command used to start LocalStack
`docker-compose -up -d`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Docker snippet:
```
s3:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "9000:9000"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-west-1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=9000
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=1
    volumes:
      - ./aws:/docker-entrypoint-initaws.d
```

./aws/bucket.sh
```
#!/bin/bash
set -x
awslocal s3 mb s3://bucket
aws configure set aws_access_key_id localstack
aws configure set aws_secret_access_key localstack123
set +x
```

**Comment by whummer** [comment]
Thanks for reporing @selketdaly . Please note that the Web dashboard is now deprecated and not maintained anymore - please refer to this section in the README: https://github.com/localstack/localstack#web-dashboard-deprecated . It is still available in the `localstack/localstack-full` image for backwards compatibility reasons, but no longer maintained. Hope that helps, thanks.

**Comment by johndpope** [comment]
in the docker compose file - 
just include a commented out line below the main one 
 #    image: localstack/localstack-full - use this to interact with full web ui - https://0.0.0.0:4566/
