### ISSUE TITLE
Lambda fails on running with io.quarkus hibernate orm and jpa

### ISSUE THREAD

**Issue by michaelgloeckner** [localstack/localstack#3578]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description

I created a lambda function which uses quarkus hibernate orm and deployed it to localstack.  
After the lambda is triggered by s3 event exception is thrown.

Caused by: java.lang.ClassNotFoundException: java.rmi.RemoteException

[error.log](https://github.com/localstack/localstack/files/5945104/error.log)

Same implementation but without the following dependencies works like expected.

            
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-hibernate-orm</artifactId>
            </dependency>
        
            
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-jdbc-postgresql</artifactId>
            </dependency>

Deploying the lambda with orm to AWS works.

## Expected behavior

No Exception is thrown and handleRequest is called.

## Actual behavior

Caused by: java.lang.ClassNotFoundException: `java.rmi.RemoteException is thrown

# Steps to reproduce

## Command used to start LocalStack

using localstack/localstack:latest

`helm upgrade --install localstack $HELM_REPO_PATH/localstack --namespace=$APP_PAR --set debug=true
`
Helm configuration values are:

   - name: SERVICES
     value: "s3,lambda,sqs,iam"
   - name: AWS_DEFAULT_REGION
     value: "us-east-1"
   - name: DEFAULT_REGION
     value: "us-east-1"
   - name: AWS_REGION
     value: "us-east-1"
   - name: AWS_ACCESS_KEY_ID
     value: "test"
   - name: AWS_SECRET_ACCESS_KEY
     value: "test"

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

`aws --endpoint-url http://localhost:4566 --profile localstack lambda create-function \
	--region us-east-1 \
    --function-name JPALambda \
    --runtime java11 \
	--timeout 60 \
	--memory-size 512 \
    --zip-file fileb://./lambda/JPALambda/function_jpa.zip \
    --handler io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest \
    --environment "Variables={DB_URL=$DB_ADDRESS, DB_USERNAME=user, DB_PASSWORD=pwd, LAMBDA_ARCFOLDER=archive, AWS_REGION=us-east-1, AWS_ACCESS_KEY_ID=test, AWS_SECRET_ACCESS_KEY=test}" \
	--role arn:aws:iam::000000000000:role/lambda-ex
`
[function_jpa.zip](https://github.com/localstack/localstack/files/5945118/function_jpa.zip)

I added a notification configuration which triggers the lambda.

`aws --endpoint-url http://localhost:4566 --profile localstack s3api put-bucket-notification-configuration \
	--region $AWS_REGION \
	--notification-configuration file://./lambda/s3triggerlambdaconfig.json \
	--bucket $AWS_BUCKET_NAME
`

But it fails with:

`Exception` in thread "main" java.lang.ExceptionInInitializerError
>       at java.base/java.lang.Class.forName0(Native Method)
>       at java.base/java.lang.Class.forName(Unknown Source)
>       at io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler.<clinit>(QuarkusStreamHandler.java:30)
>       at java.base/java.lang.Class.forName0(Native Method)
>       at java.base/java.lang.Class.forName(Unknown Source)
>       at cloud.localstack.LambdaExecutor.getHandler(LambdaExecutor.java:131)
>       at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:59)
> Caused by: java.lang.RuntimeException: Failed to start quarkus
>       at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:216)
>       ... 7 more
> Caused by: java.lang.NoClassDefFoundError: java/rmi/RemoteException
>       at java.base/java.lang.ClassLoader.defineClass1(Native Method)
>       at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
>       at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
>       at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
>       at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
>       at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
>       at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
>       at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
>       at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
>       at io.quarkus.deployment.steps.SmallRyeContextPropagationProcessor$buildStatic-850855720.deploy_0(SmallRyeContextPropagationProcessor$buildStatic-850855720.zig:79)
>       at io.quarkus.deployment.steps.SmallRyeContextPropagationProcessor$buildStatic-850855720.deploy(SmallRyeContextPropagationProcessor$buildStatic-850855720.zig:40)
>       at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:86)
>       ... 7 more
> Caused by: java.lang.ClassNotFoundException: `java.rmi.RemoteException
`

**Comment by michaelgloeckner** [comment]
Using the lambda executor "docker" solved the problem for me.

   - name: LAMBDA_EXECUTOR
     value: "docker"
   - name: DOCKER_HOST
     value: "unix:///var/run/docker.sock"
