### ISSUE TITLE
Cannot bootstrap using modern bootstrap template via the cdklocal bootstrap command [localstack pro]

### ISSUE THREAD

**Issue by minhio** [localstack/localstack#3601]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

OS: MacOS BigSur 11.2.1
CDK: 1.89.0

Bootstrapping failed with the modern bootstrap template. Appears to be ECR related. This is while using localstack pro with ECR support.

## Expected behavior

Successfully bootstrap localstack using the modern bootstrap template.

## Actual behavior

`cdklocal bootstrap` command hangs, localstack produced the following

```
orleans-sandbox-localstack | 2021-02-13T05:10:13:INFO:localstack.utils.cloudformation.template_deployer: Unable to apply change set CDK-997a260c-a811-4aa7-a680-3f3a454b3e8c: Unable to extract attribute "Arn" from "ECR::Repository" model class <class 'moto.ecr.models.Repository'>
orleans-sandbox-localstack | 2021-02-13T05:10:13:ERROR:cloudformation_api: Exception on / [POST]
orleans-sandbox-localstack | Traceback (most recent call last):
orleans-sandbox-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
orleans-sandbox-localstack |     response = self.full_dispatch_request()
orleans-sandbox-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
orleans-sandbox-localstack |     rv = self.handle_user_exception(e)
orleans-sandbox-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
orleans-sandbox-localstack |     return cors_after_request(app.make_response(f(*args, **kwargs)))
orleans-sandbox-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
orleans-sandbox-localstack |     reraise(exc_type, exc_value, tb)
orleans-sandbox-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
orleans-sandbox-localstack |     raise value
orleans-sandbox-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
orleans-sandbox-localstack |     rv = self.dispatch_request()
orleans-sandbox-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
orleans-sandbox-localstack |     return self.view_functions[rule.endpoint](**req.view_args)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 546, in handle_request
orleans-sandbox-localstack |     result = func(req_params)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 437, in execute_change_set
orleans-sandbox-localstack |     deployer.apply_change_set(change_set)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1723, in apply_change_set
orleans-sandbox-localstack |     change_set.changes = self.apply_changes(change_set.stack, change_set, stack_name=change_set.stack_name)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1940, in apply_changes
orleans-sandbox-localstack |     return self.apply_changes_in_loop(changes, old_stack, stack_name)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1966, in apply_changes_in_loop
orleans-sandbox-localstack |     should_deploy = self.prepare_should_deploy_change(
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2001, in prepare_should_deploy_change
orleans-sandbox-localstack |     resolve_refs_recursively(stack.stack_name, resource, new_resources)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/common.py", line 390, in func
orleans-sandbox-localstack |     return wrapped(*args, **kwargs)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1054, in resolve_refs_recursively
orleans-sandbox-localstack |     value[key] = resolve_refs_recursively(stack_name, val, resources)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/common.py", line 390, in func
orleans-sandbox-localstack |     return wrapped(*args, **kwargs)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1054, in resolve_refs_recursively
orleans-sandbox-localstack |     value[key] = resolve_refs_recursively(stack_name, val, resources)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/common.py", line 390, in func
orleans-sandbox-localstack |     return wrapped(*args, **kwargs)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1054, in resolve_refs_recursively
orleans-sandbox-localstack |     value[key] = resolve_refs_recursively(stack_name, val, resources)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/common.py", line 390, in func
orleans-sandbox-localstack |     return wrapped(*args, **kwargs)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1058, in resolve_refs_recursively
orleans-sandbox-localstack |     value[i] = resolve_refs_recursively(stack_name, value[i], resources)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/common.py", line 390, in func
orleans-sandbox-localstack |     return wrapped(*args, **kwargs)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1054, in resolve_refs_recursively
orleans-sandbox-localstack |     value[key] = resolve_refs_recursively(stack_name, val, resources)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/common.py", line 390, in func
orleans-sandbox-localstack |     return wrapped(*args, **kwargs)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 988, in resolve_refs_recursively
orleans-sandbox-localstack |     result = resolve_placeholders_in_string(result, stack_name=stack_name, resources=resources)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1083, in resolve_placeholders_in_string
orleans-sandbox-localstack |     result = re.sub(regex, _replace, result)
orleans-sandbox-localstack |   File "/usr/lib/python3.8/re.py", line 208, in sub
orleans-sandbox-localstack |     return _compile(pattern, flags).sub(repl, string, count)
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1067, in _replace
orleans-sandbox-localstack |     resolved = resolve_ref(stack_name, parts[0].strip(), resources, attribute=parts[1].strip())
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 922, in resolve_ref
orleans-sandbox-localstack |     return determine_resource_physical_id(resource_id=ref,
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1568, in determine_resource_physical_id
orleans-sandbox-localstack |     result = extract_resource_attribute(resource_type, {}, attribute or 'PhysicalResourceId',
orleans-sandbox-localstack |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py", line 654, in extract_resource_attribute
orleans-sandbox-localstack |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 785, in extract_resource_attribute
orleans-sandbox-localstack |     raise Exception('Unable to extract attribute "%s" from "%s" model class %s' % (
orleans-sandbox-localstack | Exception: Unable to extract attribute "Arn" from "ECR::Repository" model class <class 'moto.ecr.models.Repository'>
```

# Steps to reproduce

## Command used to start LocalStack

`docker-compose up`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

`cdklocal bootstrap`

cdk.json
note that `@aws-cdk/core:newStyleStackSynthesis` is set to `true` to bootstrap using the modern bootstrap template

```
{
  "app": "npx ts-node --prefer-ts-exts bin/localstack.ts",
  "context": {
    "@aws-cdk/core:enableStackNameDuplicates": "true",
    "aws-cdk:enableDiffNoFail": "true",
    "@aws-cdk/core:stackRelativeExports": "true",
    "@aws-cdk/core:newStyleStackSynthesis": "true",
    "@aws-cdk/aws-ecr-assets:dockerIgnoreSupport": true,
    "@aws-cdk/aws-secretsmanager:parseOwnedSecretName": true,
    "@aws-cdk/aws-kms:defaultKeyPolicies": true,
    "@aws-cdk/aws-s3:grantWriteWithoutAcl": true
  }
}
```

docker-compose.yml

```
version: '3'
services:
  localstack:
    container_name: orleans-sandbox-localstack
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
      - '443:443'
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - >-
          SERVICES=serverless,sts,cloudformation,
          cognito,cloudwatch,apigatewayv2,stepfunctions,ecr,ecs
          sqs,kinesis,firehose,dynamodbstreams,rds,es,elasticache
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      - HOST_TMP_FOLDER=$TMPDIR
      - DEBUG=1
    volumes:
      - './docker/localstack/data:/tmp/localstack'
```

**Comment by birhanuwondimu** [comment]
I have  the same issue trying to bootstrap localstack when  'newStyleStackSynthesis' set to true( new style synthesizer ).

**Comment by whummer** [comment]
Thanks for reporting  @minhio and apologies for the delay. The issue with `ECR::Repository` CloudFormation should now (hopefully) be resolved. Can you please pull the `latest` Docker image and create follow-up tickets if there are any other issues running a CDK template with `newStyleStackSynthesis` enabled? Thanks for your help!

**Comment by riceyrice** [comment]
Still seeing exactly this using `localstack/localstack:latest` with no API key, should I be?

**Comment by riceyrice** [comment]
Still seeing this with latest image (no API key):
```

**Comment by fazal-kh4n** [comment]
+1 Having the same issue with using v2 of aws-cdk

**Comment by fazal-kh4n** [comment]
I am having the same issue with v2:

`2021-07-27T14:34:26:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "CDKToolkit": Unable to extract attribute "Arn" from "ECR::Repository" model class <class 'moto.ecr.models.Repository'>`

**Comment by BStenfors9119** [comment]
I am seeing the same behavior.  

I have @aws-cdk/core:newStyleStackSynthesis set to "true" and also setting CDK_NEW_BOOTSTRAP=1 in environment vars.

```
 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "CDKToolkit": Unable to extract attribute "Arn" from "ECR::
Repository" model class <class 'moto.ecr.models.Repository'> Traceback (most recent call last):
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2109, in _run
docker_localstack_2 |     self.do_apply_changes_in_loop(changes, stack, stack_name)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2159, in do_apply_changes_in_loop
docker_localstack_2 |     resource_id, change, stack, new_resources
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2218, in prepare_should_deploy_change
docker_localstack_2 |     resolve_refs_recursively(stack.stack_name, resource, new_resources)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/common.py", line 461, in func
docker_localstack_2 |     return wrapped(*args, **kwargs)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 933, in resolve_refs_recursively
docker_localstack_2 |     value[key] = resolve_refs_recursively(stack_name, val, resources)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/common.py", line 461, in func
docker_localstack_2 |     return wrapped(*args, **kwargs)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 933, in resolve_refs_recursively
docker_localstack_2 |     value[key] = resolve_refs_recursively(stack_name, val, resources)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/common.py", line 461, in func
docker_localstack_2 |     return wrapped(*args, **kwargs)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 933, in resolve_refs_recursively
docker_localstack_2 |     value[key] = resolve_refs_recursively(stack_name, val, resources)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/common.py", line 461, in func
docker_localstack_2 |     return wrapped(*args, **kwargs)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 937, in resolve_refs_recursively
docker_localstack_2 |     value[i] = resolve_refs_recursively(stack_name, value[i], resources)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/common.py", line 461, in func
docker_localstack_2 |     return wrapped(*args, **kwargs)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 933, in resolve_refs_recursively
docker_localstack_2 |     value[key] = resolve_refs_recursively(stack_name, val, resources)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/common.py", line 461, in func
docker_localstack_2 |     return wrapped(*args, **kwargs)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 855, in resolve_refs_recursively
docker_localstack_2 |     result, stack_name=stack_name, resources=resources
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 976, in resolve_placeholders_in_string
docker_localstack_2 |     result = re.sub(regex, _replace, result)
docker_localstack_2 |   File "/usr/lib/python3.7/re.py", line 194, in sub
docker_localstack_2 |     return _compile(pattern, flags).sub(repl, string, count)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 948, in _replace
docker_localstack_2 |     stack_name, resource_name.strip(), resources, attribute=attr_name.strip()
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 771, in resolve_ref
docker_localstack_2 |     stack_name=stack_name,
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1591, in determine_resource_physical_id
docker_localstack_2 |     resources=resources,
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 611, in extract_resource_attribute
docker_localstack_2 |     % (attribute, resource_type, type(resource_state))
docker_localstack_2 | Exception: Unable to extract attribute "Arn" from "ECR::Repository" model class <class 'moto.ecr.models.Repository'>
```
