### ISSUE TITLE
PRO: Unable to invoke image based Lambda function (Python)

### ISSUE THREAD

**Issue by kevindixon** [localstack/localstack#3638]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
Image-based Python Lambda functions using the official AWS runtime cannot be invoked - they just time out.

## Expected behavior
Can invoke an image-based Python Lambda function and get a result.

## Actual behavior
Timeout

# Steps to reproduce

## Command used to start LocalStack
`docker-compose up localstack`

`docker-compose.yml`:

```
version: "3.5"

services:
  localstack:
    # See https://github.com/localstack/localstack/blob/master/docker-compose.yml
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.12.6
    privileged: true
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "443:443"
      - "4510:4510" # ECR
    # Expose for local testing
    expose:
      - 4566
      - 443 # For localstack PRO
    hostname: localstack
    environment:
      - AWS_DEFAULT_REGION=us-east-1    
      - SERVICES=logs,cloudwatch,ecr,ecs,edge,dynamodb,iam,kms,lambda,sqs,ssm,stepfunctions
      - DEBUG=${DEBUG-true}
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker}
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Create an ECR repo:
```
awslocal ecr create-repository --repository-name my_image
```
Create a dummy Lambda image:
```
FROM public.ecr.aws/lambda/python:3.7 AS base

RUN echo "def handle(event, context): \
    return True" >> handler.py

CMD ["handler.handle"]
```
```
docker build -t localhost:4510/my_image:latest .
```
Push the image
```
awslocal ecr get-login-password | docker login --username AWS --password-stdin localhost:4510
docker push localhost:4510/my_image:latest
```
Create a role for the Lambda:
```
awslocal iam create-role --role-name lambda-ex --assume-role-policy-document '{
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": "lambda.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
            }
        ]
    }'
```
Create the Lambda: 
```
awslocal lambda create-function --function-name test-local --package-type Image --code ImageUri=localhost:4510/my_image:latest --role arn:aws:iam::000000000:role/lambda-ex
```
Execute the Lambda:
```
awslocal lambda invoke --function-name test-local --payload '{"lovely":"biscuits"}' out.txt
```

Eventually you will see:
```
Read timeout on endpoint URL: "http://localhost:4566/2015-03-31/functions/test-local/invocations"
```

Debug output from Localstack (repeated 5 times):
```
localstack_main        | 2021-02-24T09:41:44:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: docker run -d -e AWS_LAMBDA_RUNTIME_API="172.17.0.2:4566/us-east-1:test-local" localhost:4510/my_image:latest
```

If you run that `docker` command locally:
```
docker run -e AWS_LAMBDA_RUNTIME_API="172.17.0.2:4566/us-east-1:test-local" localhost:4510/my_image:latest

Traceback (most recent call last):
  File "/var/lang/lib/python3.7/http/client.py", line 893, in _get_hostport
    port = int(host[i+1:])
ValueError: invalid literal for int() with base 10: 'test-local'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/runtime/bootstrap", line 9, in <module>
    main()
  File "/var/runtime/bootstrap.py", line 321, in main
    lambda_runtime_client = LambdaRuntimeClient(lambda_runtime_api_addr)
  File "/var/runtime/lambda_runtime_client.py", line 36, in __init__
    self.runtime_connection = http.client.HTTPConnection(lambda_runtime_address)
  File "/var/lang/lib/python3.7/http/client.py", line 855, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "/var/lang/lib/python3.7/http/client.py", line 898, in _get_hostport
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
http.client.InvalidURL: nonnumeric port: 'test-local'
```
So it looks as though the Lambda runtime library doesn't cope with a URL that includes a `:` (other than the port).

As discussed with @whummer

**Comment by whummer** [comment]
Thanks for reporting @kevindixon . Turns out that this is a bug in older versions of the AWS Lambda Python Runtime image, which fails to parse URLs with paths (e.g., `AWS_LAMBDA_RUNTIME_API="172.17.0.2:4566/func123`) properly.

This appears to be fixed in the [source code repo](https://github.com/aws/aws-lambda-python-runtime-interface-client/), so I'd assume that future builds of the Lambda runtime images (e.g., `public.ecr.aws/lambda/python:3.7`) will fix this issue.

Meanwhile, we have created a custom image which contains a fix - can you please change your Dockerfile to inherit from this base image:
```
FROM localstack/lambda-runtime-python
```

Hope that helps - please keep us posted how it goes. Thanks!
