### ISSUE TITLE
[EventBridge] deleteRule results in KeyError

### ISSUE THREAD

**Issue by danielblignaut** [localstack/localstack#3646]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
Running this code, the deleteRule request fails. In the nodeJS console I get unknownError, but see localstack trace below.

Example:
```typescript

const queue = await sqsClient.createQueue({
			QueueName: 'test-1'
		}).promise()


		const queueAttributes = await sqsClient.getQueueAttributes({
			QueueUrl: queue.QueueUrl,
		}).promise()

		
		const rule = await eventBridge.putRule({
			Name: 'test',
			EventBusName: 'conductor-bridge',
			EventPattern: JSON.stringify({
				source: [event.source],
				['detail-type']: [event.type]
				
			})
			
		}).promise()

		await eventBridge.putTargets({
			Rule: 'test',

			Targets: [
				{
					Id: 'test',
					Arn: queueAttributes.Attributes.QueueArn
				}
			]
		}).promise()

		const targets = await eventBridge.listTargetsByRule({
			Rule: 'test',
			EventBusName: 'conductor-bridge'
		}).promise()

               await sqsClient.deleteQueue({
			QueueUrl: queue.QueueUrl
		}).promise()

		await eventBridge.removeTargets({
			Rule: 'test',
			EventBusName: 'conductor-bridge',
			Ids: targets.Targets.map((t)=> t.Id)
		}).promise()

//THIS FAILS
                await eventBridge.deleteRule({
				Name: 'test',
				EventBusName: 'conductor-brdige'
			}).promise()
```

...

## Expected behavior
Expect the above code not to fail
...

## Actual behavior
it fails
...

# Steps to reproduce

1. Run localstack with required services (eventbridge, sqs)
2. execute the above code where AWS clients are configured for localstack endpoint

# Localstack trace:

```
localstack_1  | 2021-02-25 14:59:48,855:API: Error on request:
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
localstack_1  |     execute(self.server.app)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
localstack_1  |     application_iter = app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 168, in __call__
localstack_1  |     return backend_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
localstack_1  |     return self.wsgi_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
localstack_1  |     response = self.handle_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_1  |     raise value
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
localstack_1  |     response = self.full_dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
localstack_1  |     rv = self.handle_user_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_1  |     raise value
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
localstack_1  |     rv = self.dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
localstack_1  |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 151, in __call__
localstack_1  |     result = self.callback(request, request.url, {})
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 202, in dispatch
localstack_1  |     return cls()._dispatch(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 312, in _dispatch
localstack_1  |     return self.call_action()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 397, in call_action
localstack_1  |     response = method()
localstack_1  |   File "/opt/code/localstack/localstack/services/events/events_starter.py", line 142, in events_handler_delete_rule
localstack_1  |     EVENT_RULES.get(event_bus, set()).remove(name)
localstack_1  | KeyError: 'test'
```

**Comment by usmangani1** [comment]
@danielblignaut  Thanks for reporting the issue.
We tried to reproduce the issue on the current version of localstack and are not able to reproduce it.Can you please let us know if you are using the latest version of localstack ? If not can you please try this on the latest version of localstack and report here if the issue persists.

The following is the test case covering the functionality mentioned above
https://github.com/localstack/localstack/blob/master/tests/integration/test_events.py#L112-L184
