### ISSUE TITLE
CloudFormation - Unable to deploy template in S3

### ISSUE THREAD

**Issue by Tobolov** [localstack/localstack#3695]
# Type of request: This is a ...

[ X] bug report
[ ] feature request

# Detailed description
Unable to deploy Cloudformation template stored in S3.

## Expected behavior
Able to deploy Cloudformation template stored in S3. 

## Actual behavior
API call fails with response "500 Internal Server Error". Following error found in logs.
```
2021-03-08T05:10:59:ERROR:cloudformation_api: Exception on / [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 549, in handle_request
    result = func(req_params)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 305, in create_stack
    template = template_preparer.parse_template(req_params['TemplateBody'])
KeyError: 'TemplateBody'
```

# Steps to reproduce
Deploy a CloudFormation template stored in S3.
Note: There is no way to use the AWS CLI to deploy a CF template already stored in S3. It does has functionality to upload a CF template to s3 then deploy it in one command, however this does not work with localstack due to S3 dns restrictions.

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```C#
            var client = new AmazonCloudFormationClient(credentials);
            var request = new CreateStackRequest() {
                TemplateURL = "http://127.0.0.1:9999/awswrappers-cf-templates/template.yml",
                Capabilities = new List<string>() { "CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND" },
                Tags = new List<Tag>(),
                Parameters = new List<Parameter>(),
                StackName = "stack-name"
            };
            var response = await client.CreateStackAsync(request);
            return response.StackId;
```

**Comment by whummer** [comment]
Thanks for reporting @Tobolov . Can you please share some more details about your environment setup. 

Which server is running on port 9999 - is this your LocalStack container, or some other service? In case of the latter, please note that the template download URL needs to be accessible from the LocalStack container (which it probably isn't in this case). 

If you can help us provide a small, isolated example to reproduce this use case, we'll be happy to look into it.. Thanks

Also, this may likely already be fixed with the `latest` Docker image - can you please try again with enabling the `DEBUG=1` configuration in the environment, and share the full logs with us? Thanks!

**Comment by Tobolov** [comment]
Fixed in the latest version. Thanks!
