### ISSUE TITLE
Lambda environment variables not available to Container Image invocation [Pro]

### ISSUE THREAD

**Issue by klaymo** [localstack/localstack#3727]
[x ] bug report

# Detailed description
Creating a lambda container image function, the environment variables configured with the function do not seem to be passed to the Docker invocation of the associated container image. 

## Expected behavior

Any configured environment variables in the lambda function configuration (get-function) should be passed to the container image via `docker run` (I assume that is where they would be passed)

## Actual behavior

It could be that I am missing something but it doesn't appear that the environment variables are passed. I tried to follow the code in LambdaExecutor, and while it looks like it is pulling the function details, the `docker run` command does not include them.

# Steps to reproduce

## Command used to start LocalStack

Localstack: latest version 0.12.7

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

`awslocal lambda get-function --function-name test-local`

```
{
    "Configuration": {
        "FunctionName": "test-local",
        "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:test-local",
        "Runtime": "python3.8",
        "Role": "arn:aws:iam::000000000000:role/test-local-lambda-exec",
        "Handler": "handler.lambda_handler",
        "Timeout": 30,
        "MemorySize": 512,
        "LastModified": "2021-03-14T21:33:52.903+0000",
        "Version": "$LATEST",
        "VpcConfig": {},
        "Environment": {
            "Variables": {
                "CUSTOM_VARIABLE": "testing123"
            }
        },
        "TracingConfig": {
            "Mode": "PassThrough"
        },
        "RevisionId": "b6dd4629-4da2-4221-a91b-bb19c1165b63",
        "Layers": [],
        "State": "Active",
        "LastUpdateStatus": "Successful",
        "PackageType": "Image"
    },
    "Code": {
        "Location": "http://localhost:4566/2015-03-31/functions/test-local/code"
    },
    "Tags": {}
}
```
The variable is added properly when creating the function when referenced with awslocal or boto...

Invoking the function
`awslocal lambda invoke --function-name test-local testout`

There isn't a lot of debug messaging here, but the `docker run` command shows as follows: 
`docker run -d -e AWS_LAMBDA_RUNTIME_API="172.17.0.2:4566/us-east-1_test-local" localhost:4510/test-local-ecr:latest`

This does invoke the function, but it fails because I am expecting the `CUSTOM_VARIABLE` to be set, which throws a `KeyError` exception when referencing `os.environ` in the function code itself.

If I log the `os.environ` within the function is does not show the custom variable from the function settings:
```
{
  "HOSTNAME": "2c782d9fcada",
  "LD_LIBRARY_PATH": "/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib",
  "LAMBDA_TASK_ROOT": "/var/task",
  "AWS_LAMBDA_RUNTIME_API": "172.17.0.2:4566/us-east-1_test-local",
  "PATH": "/var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin",
  "PWD": "/var/task",
  "LANG": "en_US.UTF-8",
  "LAMBDA_RUNTIME_DIR": "/var/runtime",
  "TZ": ":/etc/localtime",
  "HOME": "/root",
  "SHLVL": "0",
  "_HANDLER": "handler.lambda_handler",
  "AWS_EXECUTION_ENV": "AWS_Lambda_python3.8",
  "PYTHONPATH": "/var/runtime",
  "_X_AMZN_TRACE_ID": "6c2e228d"
}
```

**Comment by whummer** [comment]
Thanks for reporting @klaymo . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!

(Btw, we're also still working on making the `LOCALSTACK_HOSTNAME` env variable available in the Lambda container image function - will be pushed in a follow-up version shortly. Thanks)

**Comment by klaymo** [comment]
Thanks @whummer this does look like it is passing the variables now, however now I'm not able to invoke the function. I get a `ReadTimeout` connecting to the lambda invocations API. Note: this could be because I made some configuration adjustments when trying to troubleshoot above and haven't reset things properly, but I've tried tweaking the localstack main container variables to no success.

Here is the log output from the `aws invoke` call in case that provides some insight:

```
2021-03-16 16:11:49,098 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.19.28 Python/3.7.4 Darwin/19.6.0 botocore/1.20.28
2021-03-16 16:11:49,098 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--endpoint-url=http://localhost:4566', 'lambda', 'invoke', '--function-name', 'test-local', '--invocation-type', 'RequestResponse', '--payload', '{}', 'testout', '--debug']
2021-03-16 16:11:49,098 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x10c1afdd0>
2021-03-16 16:11:49,099 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x10ac41680>
2021-03-16 16:11:49,099 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x10be0b200>
2021-03-16 16:11:49,100 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2021-03-16 16:11:49,104 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x10bfe24d0>
2021-03-16 16:11:49,105 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /venv/lib/python3.7/site-packages/botocore/data/lambda/2015-03-31/service-2.json
2021-03-16 16:11:49,111 - MainThread - botocore.hooks - DEBUG - Event building-command-table.lambda: calling handler <function add_waiters at 0x10c1c1a70>
2021-03-16 16:11:49,130 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /venv/lib/python3.7/site-packages/botocore/data/lambda/2015-03-31/waiters-2.json
2021-03-16 16:11:49,131 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('function-name', <awscli.arguments.CLIArgument object at 0x10c3c88d0>), ('invocation-type', <awscli.arguments.CLIArgument object at 0x10c3c89d0>), ('log-type', <awscli.arguments.CLIArgument object at 0x10c3c8ad0>), ('client-context', <awscli.arguments.CLIArgument object at 0x10c3c8b50>), ('payload', <awscli.arguments.CLIArgument object at 0x10c3c8b10>), ('qualifier', <awscli.arguments.CLIArgument object at 0x10c3c8bd0>)])
2021-03-16 16:11:49,132 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.lambda.invoke: calling handler <function add_streaming_output_arg at 0x10c1b4440>
2021-03-16 16:11:49,132 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.lambda.invoke: calling handler <function add_cli_input_json at 0x10be0f8c0>
2021-03-16 16:11:49,132 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.lambda.invoke: calling handler <function unify_paging_params at 0x10c130560>
2021-03-16 16:11:49,155 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /venv/lib/python3.7/site-packages/botocore/data/lambda/2015-03-31/paginators-1.json
2021-03-16 16:11:49,155 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.lambda.invoke: calling handler <function add_generate_skeleton at 0x10c10ee60>
2021-03-16 16:11:49,156 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.lambda.invoke.function-name: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10c032690>
2021-03-16 16:11:49,157 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.lambda.invoke: calling handler <awscli.argprocess.ParamShorthandParser object at 0x10bd97a90>
2021-03-16 16:11:49,157 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'test-local' for parameter "function_name": 'test-local'
2021-03-16 16:11:49,157 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.lambda.invoke.invocation-type: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10c032690>
2021-03-16 16:11:49,157 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.lambda.invoke: calling handler <awscli.argprocess.ParamShorthandParser object at 0x10bd97a90>
2021-03-16 16:11:49,157 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'RequestResponse' for parameter "invocation_type": 'RequestResponse'
2021-03-16 16:11:49,157 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.lambda.invoke.log-type: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10c032690>
2021-03-16 16:11:49,158 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.lambda.invoke.client-context: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10c032690>
2021-03-16 16:11:49,158 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.lambda.invoke.payload: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10c032690>
2021-03-16 16:11:49,164 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.lambda.invoke: calling handler <awscli.argprocess.ParamShorthandParser object at 0x10bd97a90>
2021-03-16 16:11:49,164 - MainThread - awscli.argprocess - DEBUG - Param payload looks like JSON, not considered for param shorthand.
2021-03-16 16:11:49,164 - MainThread - awscli.arguments - DEBUG - Unpacked value of '{}' for parameter "payload": '{}'
2021-03-16 16:11:49,165 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.lambda.invoke.qualifier: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10c032690>
2021-03-16 16:11:49,165 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.lambda.invoke.outfile: calling handler <awscli.paramfile.URIArgumentHandler object at 0x10c032690>
2021-03-16 16:11:49,165 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2021-03-16 16:11:49,165 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2021-03-16 16:11:49,167 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /venv/lib/python3.7/site-packages/botocore/data/endpoints.json
2021-03-16 16:11:49,192 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x10b8364d0>
2021-03-16 16:11:49,194 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.lambda: calling handler <function add_generate_presigned_url at 0x10b7e45f0>
2021-03-16 16:11:49,197 - MainThread - botocore.endpoint - DEBUG - Setting lambda timeout as (60, 60)
2021-03-16 16:11:49,199 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /venv/lib/python3.7/site-packages/botocore/data/_retry.json
2021-03-16 16:11:49,200 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: lambda
2021-03-16 16:11:49,201 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.lambda.Invoke: calling handler <function generate_idempotent_uuid at 0x10b86ab00>
2021-03-16 16:11:49,201 - MainThread - botocore.hooks - DEBUG - Event before-call.lambda.Invoke: calling handler <function inject_api_version_header_if_needed at 0x10b8723b0>
2021-03-16 16:11:49,201 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=Invoke) with params: {'url_path': '/2015-03-31/functions/test-local/invocations', 'query_string': {}, 'method': 'POST', 'headers': {'X-Amz-Invocation-Type': 'RequestResponse', 'User-Agent': 'aws-cli/1.19.28 Python/3.7.4 Darwin/19.6.0 botocore/1.20.28'}, 'body': b'{}', 'url': 'http://localhost:4566/2015-03-31/functions/test-local/invocations', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x10c641550>, 'has_streaming_input': True, 'auth_type': None}}
2021-03-16 16:11:49,201 - MainThread - botocore.hooks - DEBUG - Event request-created.lambda.Invoke: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x10c641510>>
2021-03-16 16:11:49,202 - MainThread - botocore.hooks - DEBUG - Event choose-signer.lambda.Invoke: calling handler <function set_operation_specific_signer at 0x10b86a9e0>
2021-03-16 16:11:49,209 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2021-03-16 16:11:49,209 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/2015-03-31/functions/test-local/invocations

host:localhost:4566
x-amz-date:20210316T201149Z
x-amz-invocation-type:RequestResponse

host;x-amz-date;x-amz-invocation-type
44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
2021-03-16 16:11:49,209 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20210316T201149Z
20210316/us-east-1/lambda/aws4_request
347c9a7bee746dd41759ce58da13b2916294a22d6a8ea5ea196bf5ef8d4c7f34
2021-03-16 16:11:49,210 - MainThread - botocore.auth - DEBUG - Signature:
f383254c3deaa54dd156d5f4833a65ff956077b024465b3e3cb2bef51a4862a3
2021-03-16 16:11:49,210 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=True, method=POST, url=http://localhost:4566/2015-03-31/functions/test-local/invocations, headers={'X-Amz-Invocation-Type': b'RequestResponse', 'User-Agent': b'aws-cli/1.19.28 Python/3.7.4 Darwin/19.6.0 botocore/1.20.28', 'X-Amz-Date': b'20210316T201149Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=local/20210316/us-east-1/lambda/aws4_request, SignedHeaders=host;x-amz-date;x-amz-invocation-type, Signature=f383254c3deaa54dd156d5f4833a65ff956077b024465b3e3cb2bef51a4862a3', 'Content-Length': '2'}>
2021-03-16 16:11:49,211 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:4566
2021-03-16T20:11:49:WARNING:localstack.services.awslambda.lambda_executors: Empty event body specified for invocation of Lambda "arn:aws:lambda:us-east-1:000000000000:function:test-local"
2021-03-16T20:11:49:INFO:localstack.services.awslambda.lambda_executors: Determined main container target IP: 172.17.0.2
2021-03-16T20:11:49:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: docker run -d -e AWS_LAMBDA_RUNTIME_API="172.17.0.2:4566/us-east-1_test-local" -e CUSTOM_VARIABLE="$CUSTOM_VARIABLE" localhost:4510/test-local-ecr:latest
2021-03-16 16:12:49,219 - MainThread - botocore.hooks - DEBUG - Event needs-retry.lambda.Invoke: calling handler <botocore.retryhandler.RetryHandler object at 0x10c6418d0>
2021-03-16 16:12:49,219 - MainThread - botocore.retryhandler - DEBUG - retry needed, retryable exception caught: Read timeout on endpoint URL: "http://localhost:4566/2015-03-31/functions/test-local/invocations"
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/.pyenv/versions/3.7.4/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/.pyenv/versions/3.7.4/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/.pyenv/versions/3.7.4/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/.pyenv/versions/3.7.4/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
∂
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/botocore/httpsession.py", line 320, in send
    chunked=self._chunked(request.headers),
  File "/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 386, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/venv/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: AWSHTTPConnectionPool(host='localhost', port=4566): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/venv/lib/python3.7/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/venv/lib/python3.7/site-packages/botocore/endpoint.py", line 269, in _send
    return self.http_session.send(request)
  File "/venv/lib/python3.7/site-packages/botocore/httpsession.py", line 346, in send
    raise ReadTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "http://localhost:4566/2015-03-31/functions/test-local/invocations"
```

And I noticed similar issues you've commented on where you asked for the /health endpoint...
