### ISSUE TITLE
Async Lambda support

### ISSUE THREAD

**Issue by kprzerwa-r7** [localstack/localstack#373]
At the moment we always wait for a result from lambda, while some lambdas might return null or could be invoked asynchronously -> https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_api.py#L408
`awslocal lambda invoke --function-name=assessment-on-demand --payload='{"Records":[{"Sns":{"Message":"{}"}}]}' --invocation-type Event out.txt --debug`

```
POST
/2015-03-31/functions/assessment-on-demand/invocations

host:localhost:4574
x-amz-date:20171004T140936Z
x-amz-invocation-type:Event
```

I does not work with `invoke-async` either.
```
$:awslocal lambda invoke-async --function-name=<lambda_name> --invoke-args ~/example_sns.json --debug
2017-10-04 14:52:48,411 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.161 Python/3.4.4 Linux/4.10.0-35-generic botocore/1.7.19
2017-10-04 14:52:48,411 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--endpoint-url=http://localhost:4574', 'lambda', 'invoke-async', '--function-name=assessment-on-demand', '--invoke-args', '/home/kprzerwa/example_sns.json', '--debug']
2017-10-04 14:52:48,411 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7fc1936f0840>
2017-10-04 14:52:48,411 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-04 14:52:48,411 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fc1920bc158>
2017-10-04 14:52:48,411 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-04 14:52:48,411 - MainThread - botocore.session - DEBUG - Loading variable credentials_file from defaults.
2017-10-04 14:52:48,411 - MainThread - botocore.session - DEBUG - Loading variable config_file from defaults.
2017-10-04 14:52:48,411 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-04 14:52:48,412 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_timeout from defaults.
2017-10-04 14:52:48,412 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-04 14:52:48,412 - MainThread - botocore.session - DEBUG - Loading variable metadata_service_num_attempts from defaults.
2017-10-04 14:52:48,412 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-04 14:52:48,412 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-04 14:52:48,412 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2017-10-04 14:52:48,413 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /home/kprzerwa/.pyenv/versions/3.4.4/lib/python3.4/site-packages/botocore/data/lambda/2015-03-31/service-2.json
2017-10-04 14:52:48,425 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.lambda: calling handler <function register_retries_for_service at 0x7fc192a0e0d0>
2017-10-04 14:52:48,425 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: lambda
2017-10-04 14:52:48,427 - MainThread - botocore.hooks - DEBUG - Event building-command-table.lambda: calling handler <function add_waiters at 0x7fc1937089d8>
2017-10-04 14:52:48,430 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('function-name', <awscli.arguments.CLIArgument object at 0x7fc1911af6d8>), ('invoke-args', <awscli.arguments.CLIArgument object at 0x7fc1911af710>)])
2017-10-04 14:52:48,430 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.lambda.invoke-async: calling handler <function add_streaming_output_arg at 0x7fc1936f0a60>
2017-10-04 14:52:48,430 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.lambda.invoke-async: calling handler <function add_cli_input_json at 0x7fc1920bcae8>
2017-10-04 14:52:48,431 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.lambda.invoke-async: calling handler <function unify_paging_params at 0x7fc1937962f0>
2017-10-04 14:52:48,433 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /home/kprzerwa/.pyenv/versions/3.4.4/lib/python3.4/site-packages/botocore/data/lambda/2015-03-31/paginators-1.json
2017-10-04 14:52:48,434 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.lambda.invoke-async: calling handler <function add_generate_skeleton at 0x7fc19377b9d8>
2017-10-04 14:52:48,434 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.lambda.invoke-async: calling handler <bound method CliInputJSONArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fc1911af748>>
2017-10-04 14:52:48,434 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.lambda.invoke-async: calling handler <bound method GenerateCliSkeletonArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fc1911af9e8>>
2017-10-04 14:52:48,435 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.lambda.invoke-async.function-name: calling handler <function uri_param at 0x7fc192166158>
2017-10-04 14:52:48,435 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.lambda.invoke-async: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fc1920fcef0>
2017-10-04 14:52:48,435 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'assessment-on-demand' for parameter "function_name": 'assessment-on-demand'
2017-10-04 14:52:48,435 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.lambda.invoke-async.invoke-args: calling handler <function uri_param at 0x7fc192166158>
2017-10-04 14:52:48,435 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.lambda.invoke-async: calling handler <awscli.argprocess.ParamShorthandParser object at 0x7fc1920fcef0>
2017-10-04 14:52:48,435 - MainThread - awscli.arguments - DEBUG - Unpacked value of '/home/kprzerwa/example_sns.json' for parameter "invoke_args": <_io.BufferedReader name='/home/kprzerwa/example_sns.json'>
2017-10-04 14:52:48,435 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.lambda.invoke-async.cli-input-json: calling handler <function uri_param at 0x7fc192166158>
2017-10-04 14:52:48,435 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.lambda.invoke-async.generate-cli-skeleton: calling handler <function uri_param at 0x7fc192166158>
2017-10-04 14:52:48,435 - MainThread - botocore.hooks - DEBUG - Event calling-command.lambda.invoke-async: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fc1911af748>>
2017-10-04 14:52:48,435 - MainThread - botocore.hooks - DEBUG - Event calling-command.lambda.invoke-async: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fc1911af9e8>>
2017-10-04 14:52:48,436 - MainThread - botocore.session - DEBUG - Loading variable region from environment with value 'us-east-1'.
2017-10-04 14:52:48,436 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-04 14:52:48,436 - MainThread - botocore.session - DEBUG - Loading variable ca_bundle from defaults.
2017-10-04 14:52:48,436 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-04 14:52:48,436 - MainThread - botocore.session - DEBUG - Loading variable api_versions from defaults.
2017-10-04 14:52:48,436 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2017-10-04 14:52:48,436 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2017-10-04 14:52:48,436 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /home/kprzerwa/.pyenv/versions/3.4.4/lib/python3.4/site-packages/botocore/data/endpoints.json
2017-10-04 14:52:48,466 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2017-10-04 14:52:48,467 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.lambda: calling handler <function add_generate_presigned_url at 0x7fc192a7d268>
2017-10-04 14:52:48,467 - MainThread - botocore.args - DEBUG - The s3 config key is not a dictionary type, ignoring its value of: None
2017-10-04 14:52:48,471 - MainThread - botocore.endpoint - DEBUG - Setting lambda timeout as (60, 60)
2017-10-04 14:52:48,472 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: lambda
2017-10-04 14:52:48,472 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.lambda.InvokeAsync: calling handler <function generate_idempotent_uuid at 0x7fc192a3a9d8>
2017-10-04 14:52:48,472 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=InvokeAsync) (verify_ssl=True) with params: {'headers': {'User-Agent': 'aws-cli/1.11.161 Python/3.4.4 Linux/4.10.0-35-generic botocore/1.7.19'}, 'url_path': '/2014-11-13/functions/assessment-on-demand/invoke-async/', 'query_string': {}, 'url': 'http://localhost:4574/2014-11-13/functions/assessment-on-demand/invoke-async/', 'method': 'POST', 'body': <_io.BufferedReader name='/home/kprzerwa/example_sns.json'>, 'context': {'client_config': <botocore.config.Config object at 0x7fc1910863c8>, 'auth_type': None, 'client_region': 'us-east-1', 'has_streaming_input': True}}
2017-10-04 14:52:48,473 - MainThread - botocore.hooks - DEBUG - Event request-created.lambda.InvokeAsync: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fc191086358>>
2017-10-04 14:52:48,473 - MainThread - botocore.hooks - DEBUG - Event choose-signer.lambda.InvokeAsync: calling handler <function set_operation_specific_signer at 0x7fc192a3a8c8>
2017-10-04 14:52:48,473 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2017-10-04 14:52:48,473 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
POST
/2014-11-13/functions/assessment-on-demand/invoke-async/

host:localhost:4574
x-amz-date:20171004T135248Z

host;x-amz-date
ba127cad9e254809adbf7bd0b6659b2882e9fa7da80103ee627015e5e646219a
2017-10-04 14:52:48,473 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20171004T135248Z
20171004/us-east-1/lambda/aws4_request
32a6992b1bb807f597337de484410e204ea80d5868c223d7df50e096b9a95ba7
2017-10-04 14:52:48,473 - MainThread - botocore.auth - DEBUG - Signature:
9185c7f7b9b1840525add69bf96d55040d0c4e1ce65e9e26e6eaa6715fbeed41
2017-10-04 14:52:48,475 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [POST]>
2017-10-04 14:52:48,475 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2017-10-04 14:52:48,479 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "POST /2014-11-13/functions/assessment-on-demand/invoke-async/ HTTP/1.1" 404 233
2017-10-04 14:52:48,480 - MainThread - botocore.parsers - DEBUG - Response headers: {'content-length': '233', 'content-type': 'text/html', 'server': 'Werkzeug/0.12.2 Python/2.7', 'date': 'Wed, 04 Oct 2017 13:52:48 GMT', 'access-control-allow-origin': '*'}
2017-10-04 14:52:48,480 - MainThread - botocore.parsers - DEBUG - Response body:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\n'
2017-10-04 14:52:48,480 - MainThread - botocore.hooks - DEBUG - Event needs-retry.lambda.InvokeAsync: calling handler <botocore.retryhandler.RetryHandler object at 0x7fc191193d30>
2017-10-04 14:52:48,480 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2017-10-04 14:52:48,481 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/home/kprzerwa/.pyenv/versions/3.4.4/lib/python3.4/site-packages/awscli/clidriver.py", line 200, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/home/kprzerwa/.pyenv/versions/3.4.4/lib/python3.4/site-packages/awscli/clidriver.py", line 338, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/home/kprzerwa/.pyenv/versions/3.4.4/lib/python3.4/site-packages/awscli/clidriver.py", line 508, in __call__
    call_parameters, parsed_globals)
  File "/home/kprzerwa/.pyenv/versions/3.4.4/lib/python3.4/site-packages/awscli/clidriver.py", line 627, in invoke
    client, operation_name, parameters, parsed_globals)
  File "/home/kprzerwa/.pyenv/versions/3.4.4/lib/python3.4/site-packages/awscli/clidriver.py", line 639, in _make_client_call
    **parameters)
  File "/home/kprzerwa/.pyenv/versions/3.4.4/lib/python3.4/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/kprzerwa/.pyenv/versions/3.4.4/lib/python3.4/site-packages/botocore/client.py", line 601, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the InvokeAsync operation: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

2017-10-04 14:52:48,485 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

An error occurred (404) when calling the InvokeAsync operation: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

```

My main goal would be to subscribe lambda to a topic and have it executed asynchronously

**Comment by kprzerwa-r7** [comment]
I did some digging and it looks like lambdas subscribed to topics should be executed asynchronously

**Comment by whummer** [comment]
Yes good point @kprzerwa-r7 , this feature is currently missing. Would you be able to submit a PR? Thanks!

**Comment by kprzerwa-r7** [comment]
I am working on it now ;)
