### ISSUE TITLE
API Gateway: cannot POST base64 encoded data using LocalStack Pro

### ISSUE THREAD

**Issue by rldw** [localstack/localstack#3767]
# Type of request: This is a ...

[ x ] bug report
[ ] feature request

# Detailed description

## Expected behavior

POSTing base64 encoded data to an API Gateway endpoint with a Lambda integration works as it does on AWS.

## Actual behavior

LocalStack throws the following error when POSTing a file as `multipart/form-data`. I tried this with both jpeg and png.

```
localstack_main                | 2021-03-22T15:46:46:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/restapis/lbw1u0rw5s/dev/_user_request_/test: 'utf-8' codec can't decode byte 0xff in position 140: invalid start byte Traceback (most recent call last):
localstack_main                |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 107, in index
localstack_main                |     raise result
localstack_main                |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 581, in run
localstack_main                |     result = self.func(self.params)
localstack_main                |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack_main                |     return fn(*args, **kwargs)
localstack_main                |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 597, in handler
localstack_main                |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_main                |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 365, in modify_and_forward
localstack_main                |     listener_result = listener.forward_request(method=method,
localstack_main                |   File "/opt/code/localstack/localstack/services/edge.py", line 104, in forward_request
localstack_main                |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_main                |   File "/opt/code/localstack/localstack/services/edge.py", line 115, in do_forward_request
localstack_main                |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_main                |   File "/opt/code/localstack/localstack/services/edge.py", line 135, in do_forward_request_inmem
localstack_main                |     response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
localstack_main                |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 365, in modify_and_forward
localstack_main                |     listener_result = listener.forward_request(method=method,
localstack_main                |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 44, in forward_request
localstack_main                |     return invoke_rest_api_from_request(method, path, data, headers)
localstack_main                |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 240, in invoke_rest_api_from_request
localstack_main                |     return invoke_rest_api(api_id, stage, method, relative_path_w_query_params,
localstack_main                |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 279, in invoke_rest_api
localstack_main                |     data_str = json.dumps(data) if isinstance(data, (dict, list)) else to_str(data)
localstack_main                |   File "/opt/code/localstack/localstack/utils/common.py", line 968, in to_str
localstack_main                |     return obj.decode(encoding, errors) if isinstance(obj, six.binary_type) else obj
localstack_main                | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 140: invalid start byte
```

# Steps to reproduce

## Command used to start LocalStack

Docker compose file:
```
version: '2.1'

services:  
  localstack-container:
    # this is the container name that localstack expects internally
    container_name: "localstack_main"
    image: localstack/localstack:0.12.5
    networks:
      - localstack_network
    hostname: localstack_main
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    # https://github.com/localstack/localstack#configurations
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
        # LAMBDA_EXECUTOR: Method to use for executing Lambda functions. Possible values are:
        #   local: run Lambda functions in a temporary directory on the local machine
        #   docker: run each function invocation in a separate Docker container
        #   docker-reuse: create one Docker container per function and reuse it across invocations
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=localstack_network
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-central-1
      - LOCALSTACK_API_KEY=xxx
      - START_WEB=1
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Terraform file that creates a minimal setup. Use any zip file named `test.zip`. The content is not important, since the function is not called, because LocalStack throws the error before function is being invoked. 

```
provider "aws" {
  region                      = "eu-central-1"
  access_key                  = "test"
  s3_force_path_style         = true
  secret_key                  = "test"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    apigateway     = "http://localhost:4566"
    cloudformation = "http://localhost:4566"
    cloudwatch     = "http://localhost:4566"
    dynamodb       = "http://localhost:4566"
    es             = "http://localhost:4566"
    firehose       = "http://localhost:4566"
    iam            = "http://localhost:4566"
    kinesis        = "http://localhost:4566"
    lambda         = "http://localhost:4566"
    route53        = "http://localhost:4566"
    redshift       = "http://localhost:4566"
    s3             = "http://localhost:4566"
    secretsmanager = "http://localhost:4566"
    ses            = "http://localhost:4566"
    sns            = "http://localhost:4566"
    sqs            = "http://localhost:4566"
    ssm            = "http://localhost:4566"
    stepfunctions  = "http://localhost:4566"
    sts            = "http://localhost:4566"
  }
}

resource "aws_iam_role" "service_api_role" {
  name               = "ls-debug"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "apigateway.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_api_gateway_rest_api" "service_api" {
  name           = "ls-debug"
  api_key_source = "HEADER"
}

resource "aws_api_gateway_deployment" "service_api_deployment" {
  rest_api_id = aws_api_gateway_rest_api.service_api.id

  triggers = {
    redeployment = sha1(join(",", list(
      jsonencode(aws_api_gateway_rest_api.service_api),
      jsonencode(aws_iam_role.service_api_role),
      jsonencode(aws_api_gateway_resource.service_proxy_resource),
      jsonencode(aws_api_gateway_method.service_proxy_method),
      jsonencode(aws_api_gateway_integration.service_proxy_method_integration),
    )))
  }

  lifecycle {
    create_before_destroy = true
  }

  depends_on = [
    aws_api_gateway_method.service_proxy_method,
    aws_api_gateway_integration.service_proxy_method_integration
  ]
}

resource "aws_api_gateway_stage" "service_api_stage" {
  stage_name           = "test"
  rest_api_id          = aws_api_gateway_rest_api.service_api.id
  deployment_id        = aws_api_gateway_deployment.service_api_deployment.id
  xray_tracing_enabled = true
  # needed to prevent Terraform from updating this resource every time
  cache_cluster_size = "0.5"
}

resource "aws_api_gateway_resource" "service_proxy_resource" {
  rest_api_id = aws_api_gateway_rest_api.service_api.id
  parent_id   = aws_api_gateway_rest_api.service_api.root_resource_id
  path_part   = "{proxy+}"
}

resource "aws_api_gateway_method" "service_proxy_method" {
  rest_api_id   = aws_api_gateway_rest_api.service_api.id
  resource_id   = aws_api_gateway_resource.service_proxy_resource.id
  authorization = "NONE"
  http_method   = "ANY"
}

resource "aws_api_gateway_integration" "service_proxy_method_integration" {
  rest_api_id = aws_api_gateway_rest_api.service_api.id
  resource_id = aws_api_gateway_resource.service_proxy_resource.id
  http_method = aws_api_gateway_method.service_proxy_method.http_method
  /* credentials             = "DO NOT SET" */
  integration_http_method = "POST"
  type                    = "AWS_PROXY"
  uri                     = aws_lambda_function.service_function.invoke_arn

  depends_on = [
    aws_iam_role.service_api_role,
    aws_api_gateway_method.service_proxy_method
  ]
}




resource "aws_lambda_function" "service_function" {
  filename      = "test.zip"
  function_name = "ls-debug-lambda"
  role          = aws_iam_role.service_function_role.arn
  handler       = "handler"
  runtime       = "dotnetcore3.1"
  memory_size   = 256
  timeout       = "300"
  publish       = true

  tracing_config {
    mode = "Active"
  }
}

resource "aws_iam_role" "service_function_role" {
  name = "ls-debug-lambda"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

`curl -X POST "http://localhost:4566/restapis/<API_GATEWAY_ID>/dev/_user_request_/test" -H  "Content-Type: multipart/form-data" -F "file=@/path/to/your/sample.jpg;type=image/jpeg"`

**Comment by rldw** [comment]
I noticed this might be related to https://github.com/localstack/localstack/issues/3649

**Comment by whummer** [comment]
Thanks for reporting @rldw . We've pushed a couple of changes which should (hopefully) resolve this issue. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists - let's continue the conversation on issue #3649. Thanks!
