### ISSUE TITLE
Java Lambda service + java.lang.NoClassFoundError (SLF4j)

### ISSUE THREAD

**Issue by petervalencic** [localstack/localstack#3768]
# Type of request: This is a

[X] bug report
[ ] feature request

# Detailed description

I have a simple lambda service in Java that uses org.sl4j.LoggerFactoryClass. The code is compiled with maven using maven-shade-plugin v.3.0. The built JAR contains all dependencies and also the org.sl4j.LoggerFactoryClass (have checked manually). 
When I try to invoke the lambda service I get this kind of error message:

```
HybridCollection-Localstack |
HybridCollection-Localstack | > START RequestId: 4c296eb1-fa89-13bd-88a7-2ee5cb49b47d Version: $LATEST
HybridCollection-Localstack | > java.lang.NoClassDefFoundError
HybridCollection-Localstack | > Error loading class com.demo.eng.collection.handler.LambdaFunctionHandler: org/slf4j/LoggerFactory
HybridCollection-Localstack | > java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
HybridCollection-Localstack | >         at com.demo.eng.collection.handler.LambdaFunctionHandler.<clinit>(LambdaFunctionHandler.java:29)
HybridCollection-Localstack | >         at java.lang.Class.forName0(Native Method)
HybridCollection-Localstack | >         at java.lang.Class.forName(Class.java:348)
HybridCollection-Localstack | > Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
HybridCollection-Localstack | >         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
HybridCollection-Localstack | >         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
HybridCollection-Localstack | >         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
HybridCollection-Localstack | >         ... 3 more
HybridCollection-Localstack | >
```

## Expected behavior
The expected behavior is that slf4j should be used for logging events from the code.
...

## Actual behavior
The actual behavior is that I get java.lang.NoClassDefFoundError

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
deployment of lambda function:
`aws --endpoint-url=$AWS_ENDPOINT --region $AWS_REGION lambda create-function --function-name $LambdaFuncNameProtoBuff --runtime java8 --handler com.demo.eng.collection.handler.LambdaFunctionHandler::handleRequest --memory-size 128 --zip-file fileb://$DestZipFileProtoBuff --role arn:aws:iam::123456:role/role-name --timeout 30000`

The lambda is triggered when a new file arrives in S3 bucket with this command

`aws --endpoint-url=http://localhost:4566 --region us-east-1 s3 cp c:/brisi/test.bin s3://localstack-mbo-s3-useast1-shared-timelines-protobuff`
...

**Comment by petervalencic** [comment]
Solved the problem..
In my pom.xml have used maven-shade-plugin and compiled with:

`mvn clean package shade:shade -Dmaven.test.skip=true`

**Comment by petervalencic** [comment]
Hi, have noticed that the problem I have is related to slf4j. 
In my pom.xml I have:

```
    <dependencies>
        <dependency>
            <artifactId>aws-java-sdk-ses</artifactId>
            <groupId>com.amazonaws</groupId>
            <optional>false</optional>
            <version>1.11.197</version>
        </dependency>
      
        <dependency>
            <groupId>com.demo.eng.meters.nano</groupId>
            <artifactId>nano-events-transcoder</artifactId>
            <version>5.0.3.1</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>2.7.22</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-events</artifactId>
            <version>1.3.0</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-core</artifactId>
            <version>1.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jcl-over-slf4j</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-log4j</artifactId>
            <version>1.0.0</version>
        </dependency>
        
    </dependencies>
```

In the lambda function I have:

`private static final Logger LOG = LoggerFactory.getLogger(LambdaFunctionHandler.class);`

everything from the slf4j is included in the "built" jar archive.

**Comment by petervalencic** [comment]
Have found this strange situation.. If I wait for a while (5 minutes)  after the lambda has been deployed the service will work without any "Class not found exception" (which is strange) but If I deploy the service and invoke it just after that, I will get the error.

**Comment by petervalencic** [comment]
And here is the example If I invoke the lambda right after it was deployed:

```
HybridCollection-Localstack | 2021-03-28T11:57:01:DEBUG:localstack.services.awslambda.lambda_executors: Starting container: localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_apiProtoBuffHandler
HybridCollection-Localstack | 2021-03-28T11:57:01:DEBUG:localstack.services.awslambda.lambda_executors: docker start localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_apiProtoBuffHandler
HybridCollection-Localstack | 2021-03-28T11:57:04:DEBUG:localstack.services.awslambda.lambda_executors: Getting the entrypoint for image: "lambci/lambda:java8"
HybridCollection-Localstack | 2021-03-28T11:57:04:DEBUG:localstack.services.awslambda.lambda_executors: docker image inspect --format="{{ .Config.Entrypoint }}" "lambci/lambda:java8"
HybridCollection-Localstack | 2021-03-28T11:57:05:DEBUG:localstack.services.awslambda.lambda_executors: Getting status for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_apiProtoBuffHandler": docker ps -a --filter name='localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_apiProtoBuffHandler' --format "{{ .Status }} - {{ .Names }}" | grep -w "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_apiProtoBuffHandler" | cat
HybridCollection-Localstack | 2021-03-28T11:57:05:DEBUG:localstack.services.awslambda.lambda_executors: Getting container network: localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_apiProtoBuffHandler
HybridCollection-Localstack | 2021-03-28T11:57:05:DEBUG:localstack.services.awslambda.lambda_executors: docker inspect localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_apiProtoBuffHandler --format "{{ .HostConfig.NetworkMode }}"
HybridCollection-Localstack | 2021-03-28T11:57:05:DEBUG:localstack.services.awslambda.lambda_executors: Using entrypoint "/usr/bin/java -XX:MaxHeapSize=2834432k -XX:MaxMetaspaceSize=163840k -XX:ReservedCodeCacheSize=81920k -XX:+UseSerialGC -Xshare:on -XX:-TieredCompilation -Djava.net.preferIPv4Stack=true -jar /var/runtime/lib/LambdaJavaRTEntry-1.0.jar" for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_apiProtoBuffHandler" on network "host".
HybridCollection-Localstack | 2021-03-28T11:57:05:DEBUG:localstack.services.awslambda.lambda_executors: Command for docker-reuse Lambda executor:  docker exec -e SQS_QUEUE="$SQS_QUEUE" -e DYNAMODB_TABLE="$DYNAMODB_TABLE" -e BUCKET_EVENTS_PROTOBUFF="$BUCKET_EVENTS_PROTOBUFF" -e BUCKET_EVENTS="$BUCKET_EVENTS" -e BUCKET_NAME="$BUCKET_NAME" -e AWS_ENDPOINT="$AWS_ENDPOINT" -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" -e AWS_REGION="$AWS_REGION" -e CF_SERVER_URL="$CF_SERVER_URL" -e USE_SSL="$USE_SSL" -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" -e _LAMBDA_SERVER_PORT="$_LAMBDA_SERVER_PORT" localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_apiProtoBuffHandler /usr/bin/java -XX:MaxHeapSize=2834432k -XX:MaxMetaspaceSize=163840k -XX:ReservedCodeCacheSize=81920k -XX:+UseSerialGC -Xshare:on -XX:-TieredCompilation -Djava.net.preferIPv4Stack=true -jar /var/runtime/lib/LambdaJavaRTEntry-1.0.jar com.nielsen.eng.collection.handler.LambdaFunctionHandler::handleRequest
HybridCollection-Localstack | 2021-03-28T11:57:05:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd:  docker exec -e SQS_QUEUE="$SQS_QUEUE" -e DYNAMODB_TABLE="$DYNAMODB_TABLE" -e BUCKET_EVENTS_PROTOBUFF="$BUCKET_EVENTS_PROTOBUFF" -e BUCKET_EVENTS="$BUCKET_EVENTS" -e BUCKET_NAME="$BUCKET_NAME" -e AWS_ENDPOINT="$AWS_ENDPOINT" -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" -e AWS_REGION="$AWS_REGION" -e CF_SERVER_URL="$CF_SERVER_URL" -e USE_SSL="$USE_SSL" -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" -e _LAMBDA_SERVER_PORT="$_LAMBDA_SERVER_PORT" localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_apiProtoBuffHandler /usr/bin/java -XX:MaxHeapSize=2834432k -XX:MaxMetaspaceSize=163840k -XX:ReservedCodeCacheSize=81920k -XX:+UseSerialGC -Xshare:on -XX:-TieredCompilation -Djava.net.preferIPv4Stack=true -jar /var/runtime/lib/LambdaJavaRTEntry-1.0.jar com.nielsen.eng.collection.handler.LambdaFunctionHandler::handleRequest
HybridCollection-Localstack | 2021-03-28T11:57:08:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:apiProtoBuffHandler result / log output:
HybridCollection-Localstack |
HybridCollection-Localstack | > START RequestId: 69655a09-c714-1cbd-b911-e30d769a4deb Version: $LATEST
HybridCollection-Localstack | > java.lang.NoClassDefFoundError
HybridCollection-Localstack | > Error loading class com.nielsen.eng.collection.handler.LambdaFunctionHandler: org/slf4j/LoggerFactory
HybridCollection-Localstack | > java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
HybridCollection-Localstack | >         at com.nielsen.eng.collection.handler.LambdaFunctionHandler.<clinit>(LambdaFunctionHandler.java:34)
HybridCollection-Localstack | >         at java.lang.Class.forName0(Native Method)
HybridCollection-Localstack | >         at java.lang.Class.forName(Class.java:348)
HybridCollection-Localstack | > Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
HybridCollection-Localstack | >         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
HybridCollection-Localstack | >         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
HybridCollection-Localstack | >         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
HybridCollection-Localstack | >         ... 3 more
HybridCollection-Localstack | >
HybridCollection-Localstack | 2021-03-28T11:57:23:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
```

**Comment by AmitJ95** [comment]
@petervalencic Hello Peter. This issue still persists in gradle. Below are the error logs.  
Error loading class org.example.Hello: org/slf4j/LoggerFactory: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.example.Hello.<clinit>(Hello.java:18)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 3 more

My build.gradle file
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    implementation 'com.amazonaws:aws-lambda-java-core:1.2.2'
    implementation 'com.amazonaws:aws-lambda-java-events:3.11.1'
    runtimeOnly 'com.amazonaws:aws-lambda-java-log4j2:1.5.1'
    implementation 'org.apache.logging.log4j:log4j-api:2.12.4'
    implementation 'org.apache.logging.log4j:log4j-core:2.12.4'
    implementation 'software.amazon.awssdk:s3:2.30.33'
}

test {
    useJUnitPlatform()
}

task buildZip(type: Zip){

    into('lib'){
        from(jar)
        from(configurations.runtimeClasspath)
    }
}
