### ISSUE TITLE
Error InvalidLocationConstraint when creating S3 bucket with aws-sdk

### ISSUE THREAD

**Issue by gsf4726** [localstack/localstack#3774]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

As of latest version 0.12.8 of localstack docker image, started receiving errors from the aws-sdk node module in javascript when attempting to create a bucket.

If I revert back to 0.12.7 the error does *not* occur.

Interestingly, the 0.12.8 release is not tagged in github so I cannot easily see what has changed in this version.

## Expected behavior

S3 bucket is created

## Actual behavior

Error from aws-sdk:

```
InvalidLocationConstraint: The specified location-constraint is not valid
    at Request.extractError (/app/node_modules/aws-sdk/lib/services/s3.js:712:35)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/app/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/app/node_modules/aws-sdk/lib/event_listeners.js:313:13)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'InvalidLocationConstraint',
  region: null,
  time: 2021-03-24T11:51:50.704Z,
  requestId: '92193FE00B19D3F5',
  extendedRequestId: 'MzRISOwyjmnup92193FE00B19D3F57/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 23.449074765149902
}
```

# Steps to reproduce

1. Start localstack with S3 service
2. Call aws-sdk method `createBucket` to create a new S3 bucket

## Command used to start LocalStack

docker-compose.yml:

```
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "8081:8080"
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - HOSTNAME=localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
const AWS = require('aws-sdk');

const s3 = new AWS.S3({
  apiVersion: '2006-03-01',
  accessKeyId: 'test',
  secretAccessKey: 'test',
  s3ForcePathStyle: true,
  s3BucketEndpoint: false,
  endpoint: new AWS.Endpoint('http://localstack:4566'),
  sslEnabled: false
});

const params = { Bucket: bucket };

await s3.createBucket(params).promise();
```

**Comment by macnev2013** [comment]
Thanks for reporting @gsf4726 . We have recently made some changes in S3 bucket location constraint to make it more inline with AWS. Can you please confirm if its working against the real AWS ?

Thanks.

**Comment by t2farrell** [comment]
Looks like I'll need this too... when will these changes make it through into the `localstack/localstack` docker image?

**Comment by macnev2013** [comment]
Hi @t2farrell , This will be fixed in #3778. Thanks.

**Comment by t2farrell** [comment]
One thing I found interesting, this issue was not present when running localstack via docker on windows in WSL2 using Ubuntu, but it was failing when running in docker on a Virtualbox VM running Ubuntu.

**Comment by gsf4726** [comment]
> Thanks for reporting @gsf4726 . We have recently made some changes in S3 bucket location constraint to make it more inline with AWS. Can you please confirm if its working against the real AWS ?
> 
> Thanks.

@macnev2013 I see things have been reverted since you asked so maybe no longer needed, but I'm actually not in a great position to actually repro in AWS as we only use the create bucket call in tests where localstack is used, and I don't have access to create buckets in our AWS environments. But, I may be able to come up with something so let me know if it's still needed or if there's anything else I can help with.

Thanks for the quick response!

**Comment by whummer** [comment]
Should be fixed in `latest` - please report here if the problem persists. Thanks!
