### ISSUE TITLE
Error when creating mock ECR

### ISSUE THREAD

**Issue by conan19842002** [localstack/localstack#3776]
# Type of request: This is a bug

[x] bug report
[ ] feature request

# Detailed description

I've tried to create a mock repo ECR with PRO version of localstack but got error 'An error occurred (400) when calling the CreateRepository operation'. Even though there was a similar issue #2324 and it was claimed to be fixed in the latest version.

## Expected behavior

A mock repo should be created
...

## Actual behavior
Error logs:
```
2021-03-24T13:48:41:WARNING:localstack.services.edge: Unable to find listener for service "ecr" - please make sure to include it in $SERVICES
2021-03-24T13:48:41:WARNING:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7ff2708c4ca0>(None) failed: Unable to find listener for service "ecr" - please make sure to include it in $SERVICES Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 644, in run
    result = self.func(self.params)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 607, in handler
    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 373, in modify_and_forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/edge.py", line 105, in forward_request
    return do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 116, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 130, in do_forward_request_inmem
    raise HTTPErrorResponse(message, code=400)
localstack.utils.server.http2_server.HTTPErrorResponse: Unable to find listener for service "ecr" - please make sure to include it in $SERVICES

2021-03-24T13:48:41:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: Unable to find listener for service "ecr" - please make sure to include it in $SERVICES Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 117, in index
    raise result
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 644, in run
    result = self.func(self.params)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 607, in handler
    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 373, in modify_and_forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/edge.py", line 105, in forward_request
    return do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 116, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 130, in do_forward_request_inmem
    raise HTTPErrorResponse(message, code=400)
localstack.utils.server.http2_server.HTTPErrorResponse: Unable to find listener for service "ecr" - please make sure to include it in $SERVICES

```

# Steps to reproduce
1. Start localstack
2. Create a mock ECR repo
## Command used to start LocalStack
docker-compose.yml:
```
version: '3.5'

services:
  localstack:
    image: localstack/localstack:0.12.7
    container_name: localstack
    ports:
      - "4566-4599:4566-4599"    
    environment:
      - SERVICES=s3,lambda,iam,ecr 
      - LAMBDA_EXECUTOR=local
      - HOSTNAME_EXTERNAL=localstack
      - DEFAULT_REGION=eu-west-1
      - LAMBDA_REMOVE_CONTAINERS=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=${DEBUG}
    volumes:
      - "${TMPDIR}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Create a mock repo:
```
awslocal ecr create-repository --endpoint-url=http://localhost:4566 --repository-name mock-repo
```

**Comment by fugitive90** [comment]
I have almost identical setup and every operation with ecr fails with code 400, liike:
`
aws ecr get-login-password --region eu-central-1  --endpoint-url=http://localhost:4566
An error occurred (400) when calling the GetAuthorizationToken operation:`
I am using the latest docker image.

**Comment by whummer** [comment]
Thanks for reporting @conan19842002 , and apologies for the long delay. We haven't been able to replicate the issue you've been facing - potentially there could be an issue with your API key. Can you please get in touch with us directly to discuss the details (via email or Slack)? Thanks for your help!

**Comment by conan19842002** [comment]
Hello,

Thank you for your reply. However, the issue still persists. Can you let me
know what steps you have done to reproduce the issue please?

Best wishes,
An

---



An Nguyen


https://www.linkedin.com/in/annguyen1984

**Comment by whummer** [comment]
Hi @conan19842002 , thanks for your message. Looks like the `LOCALSTACK_API_KEY` environment variable is missing in the `docker-compose` config above. Can you please reach out via email to `info@localstack.cloud` - we'll be very happy to look into it! Thanks for your help.
