### ISSUE TITLE
Lambda Container Image invalid docker command [pro]

### ISSUE THREAD

**Issue by klaymo** [localstack/localstack#3790]
[x] bug report

# Detailed description

Related to #3727 I am still having issues getting a container image lambda to invoke correctly.
Changes in the latest docker tag seem to have addressed some issues, however, and it is failing in a new way.

The container image does not execute and it appears that the `docker run` command is incorrect/invalid

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Using `awslocal` to invoke a lambda function results in the following traceback:

```
ERROR: 'docker pull docker run -d -e AWS_LAMBDA_FUNCTION_MEMORY_SIZE=123 -e _LAMBDA_RUNTIME=python3.7 -e AWS_LAMBDA_LOG_GROUP_NAME="/aws/lambda/test-local" -e AWS_LAMBDA_LOG_STREAM_NAME=test -e AWS_LAMBDA_RUNTIME_API="test-local.us-east-1.localhost.localstack.cloud:4566" -e LOCALSTACK_HOSTS_ENTRY="test-local.us-east-1.localhost.localstack.cloud" -e CUSTOM_VARIABLE="$CUSTOM_VARIABLE" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" localstack-test:4510/test-local-ecr': exit code 125; output: b"unknown shorthand flag: 'd' in -d\nSee 'docker pull --help'.\n"
2021-03-26T12:59:51:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:test-local: Command 'docker pull docker run -d -e AWS_LAMBDA_FUNCTION_MEMORY_SIZE=123 -e _LAMBDA_RUNTIME=python3.7 -e AWS_LAMBDA_LOG_GROUP_NAME="/aws/lambda/test-local" -e AWS_LAMBDA_LOG_STREAM_NAME=test -e AWS_LAMBDA_RUNTIME_API="test-local.us-east-1.localhost.localstack.cloud:4566" -e LOCALSTACK_HOSTS_ENTRY="test-local.us-east-1.localhost.localstack.cloud" -e CUSTOM_VARIABLE="$CUSTOM_VARIABLE" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" localstack-test:4510/test-local-ecr' returned non-zero exit status 125. Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 581, in run_lambda
    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 176, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 168, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 145, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 159, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 147, in _run
    result = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 321, in _execute
    cmd = self.prepare_execution(func_details, environment, command)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_launcher.py", line 163, in prepare_execution
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_launcher.py", line 124, in get_image_entrypoint_cmd
  File "/opt/code/localstack/localstack/utils/common.py", line 1358, in run
    return do_run(cmd)
  File "/opt/code/localstack/localstack/utils/common.py", line 1355, in do_run
    return bootstrap.run(cmd, **kwargs)
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 746, in run
    raise e
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 706, in run
    output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'docker pull docker run -d -e AWS_LAMBDA_FUNCTION_MEMORY_SIZE=123 -e _LAMBDA_RUNTIME=python3.7 -e AWS_LAMBDA_LOG_GROUP_NAME="/aws/lambda/test-local" -e AWS_LAMBDA_LOG_STREAM_NAME=test -e AWS_LAMBDA_RUNTIME_API="test-local.us-east-1.localhost.localstack.cloud:4566" -e LOCALSTACK_HOSTS_ENTRY="test-local.us-east-1.localhost.localstack.cloud" -e CUSTOM_VARIABLE="$CUSTOM_VARIABLE" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" localstack-test:4510/test-local-ecr' returned non-zero exit status 125.
```

I don't know where the `lambda_launcher.py` file lives, but it appears that it is prepending `docker pull` to the `docker run` command

**Comment by whummer** [comment]
Thanks for reporting @klaymo . This should (hopefully) be fixed in the meantime. Can you please pull the `latest` Docker image and give it another try? Please keep us posted how it goes. Thanks!
