### ISSUE TITLE
ClassNotFoundException triggering Lambda from SQS

### ISSUE THREAD

**Issue by SaxyPandaBear** [localstack/localstack#3793]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
I'm testing out a lambda function locally. This is a rewrite of something that I had before, which I  had written in NodeJS previously. Now, I have a Scala lambda function, running in Java8. I have a CloudFormation template that I'm using to stand up everything that I need:

```json
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Parameters": {
        "TwitchClientId": {
            "Type": "String"
        },
        "TwitchClientSecret": {
            "Type": "String"
        },
        "SpotifyClientId": {
            "Type": "String"
        },
        "SpotifyClientSecret": {
            "Type": "String"
        }
    },
    "Resources": {
        "SongRequestQueue": {
            "Type": "AWS::SQS::Queue",
            "Properties": {
                "MaximumMessageSize": 1024,
                "MessageRetentionPeriod": 3600,
                "QueueName": "song-requests",
                "VisibilityTimeout": 60,
                "DependsOn": "ConnectionsTable"
            }
        },
        "ConnectionsTable": {
            "Type": "AWS::DynamoDB::Table",
            "Properties": {
                "TableName": "connections",
                "BillingMode": "PAY_PER_REQUEST",
                "AttributeDefinitions": [
                    {
                        "AttributeName": "channelId",
                        "AttributeType": "S"
                    }
                ],
                "KeySchema": [
                    {
                        "AttributeName": "channelId",
                        "KeyType": "HASH"
                    }
                ],
                "TimeToLiveSpecification": {
                    "AttributeName": "expires",
                    "Enabled": true
                }
            }
        },
        "SongRequestFunction": {
            "Type": "AWS::Lambda::Function",
            "Properties": {
                "Description": "Lambda function that accepts messages from SQS, in order to queue songs to Spotify",
                "Handler": "com.github.saxypandabear.songrequests.spotify.Handler::handle",
                "Role": {
                    "Fn::GetAtt": [
                        "LambdaExecutionRole",
                        "Arn"
                    ]
                },
                "Code": {
                    "S3Bucket": "twitch-song-requests",
                    "S3Key": "queue-song-lambda.zip"
                },
                "Runtime": "java8",
                "MemorySize": 512,
                "Timeout": 30,
                "Environment": {
                    "Variables": {
                        "SpotifyClientId": {
                            "Ref": "SpotifyClientId"
                        },
                        "SpotifyClientSecret": {
                            "Ref": "SpotifyClientSecret"
                        },
                        "SpotifyApiUrl": "https://api.spotify.com/v1/me/player",
                        "SpotifyOauthUrl": "something",
                        "env": "localstack"
                    }
                },
                "DependsOn": "LambdaExecutionRole"
            }
        },
        "SongRequestListener": {
            "Type": "AWS::Lambda::EventSourceMapping",
            "Properties": {
                "BatchSize": 1,
                "Enabled": true,
                "EventSourceArn": {
                    "Fn::GetAtt": [
                        "SongRequestQueue",
                        "Arn"
                    ]
                },
                "FunctionName": {
                    "Fn::GetAtt": [
                        "SongRequestFunction",
                        "Arn"
                    ]
                },
                "DependsOn": "SongRequestFunction"
            }
        },
        "LambdaExecutionRole": {
            "Type": "AWS::IAM::Role",
            "Properties": {
                "AssumeRolePolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Principal": {
                                "Service": [
                                    "lambda.amazonaws.com"
                                ]
                            },
                            "Action": [
                                "sts:AssumeRole"
                            ]
                        }
                    ]
                },
                "Path": "/",
                "Policies": [
                    {
                        "PolicyName": "accessLogs",
                        "PolicyDocument": {
                            "Version": "2012-10-17",
                            "Statement": [
                                {
                                    "Effect": "Allow",
                                    "Action": [
                                        "logs:*"
                                    ],
                                    "Resource": "arn:aws:logs:*:*:*"
                                }
                            ]
                        }
                    },
                    {
                        "PolicyName": "accessQueue",
                        "PolicyDocument": {
                            "Version": "2012-10-17",
                            "Statement": [
                                {
                                    "Effect": "Allow",
                                    "Action": [
                                        "sqs:ReceiveMessage",
                                        "sqs:DeleteMessage",
                                        "sqs:GetQueueAttributes"
                                    ],
                                    "Resource": {
                                        "Fn::GetAtt": [
                                            "SongRequestQueue",
                                            "Arn"
                                        ]
                                    }
                                }
                            ]
                        }
                    },
                    {
                        "PolicyName": "accessDynamo",
                        "PolicyDocument": {
                            "Version": "2012-10-17",
                            "Statement": [
                                {
                                    "Effect": "Allow",
                                    "Action": [
                                        "dynamodb:GetItem"
                                    ],
                                    "Resource": {
                                        "Fn::GetAtt": [
                                            "ConnectionsTable",
                                            "Arn"
                                        ]
                                    }
                                }
                            ]
                        }
                    }
                ],
                "DependsOn": "SongRequestQueue"
            }
        }
    }
}
```

There's no errors creating the CF stack, but when I send a message to the SQS that the Lambda is listening on:
```bash
aws sqs send-message \
    --endpoint-url http://localhost:4566 \
    --message-body spotify:track:5Cjkfft7iRWJp4elZXgjkc \
    --message-attributes '{"channelId": {"DataType": "String", "StringValue": "REDACTED"}}' \
    --queue-url http://localhost:4566/000000000000/song-requests
```

I get this exception stacktrace from Localstack:
```
2021-03-28T02:24:47:WARNING:bootstrap.py: Thread run method <function LambdaExecutor.execute.<locals>.do_execute at 0x7efd3ba43700>(None) failed: Lambda process returned error status code: 1. Result: . Output:
Exception in thread "main" java.lang.ClassNotFoundException: com.github.saxypandabear.songrequests.spotify.Handler::handle
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at cloud.localstack.LambdaExecutor.getHandler(LambdaExecutor.java:150)
        at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:64) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 521, in run
    result = self.func(self.params)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 159, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 146, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 142, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 152, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 140, in _run
    result = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 297, in _execute
    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 204, in run_lambda_executor
    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
Exception: Lambda process returned error status code: 1. Result: . Output:
Exception in thread "main" java.lang.ClassNotFoundException: com.github.saxypandabear.songrequests.spotify.Handler::handle
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at cloud.localstack.LambdaExecutor.getHandler(LambdaExecutor.java:150)
        at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:64)
```

I saw some older issues, and this looks like the same issue described in #3138.  

...

## Expected behavior
The lambda should be able to intercept the SQS message and act on it.
...

## Actual behavior
The lambda fails to execute because the underlying localstack executor cannot find the handler class
...

# Steps to reproduce

## Command used to start LocalStack
`pipenv run localstack start`
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
1. Create CF stack
```bash
# Using the above CF template json
aws cloudformation create-stack \
    --region us-east-1 \
    --endpoint-url http://localhost:4566 \
    --stack-name song-requests \
    --template-body file://services.json \
    --parameters ParameterKey=TwitchClientId,ParameterValue="$TWITCH_CLIENT_ID" \
                 ParameterKey=TwitchClientSecret,ParameterValue="$TWITCH_CLIENT_SECRET" \
                 ParameterKey=SpotifyClientId,ParameterValue="$SPOTIFY_CLIENT_ID" \
                 ParameterKey=SpotifyClientSecret,ParameterValue="$SPOTIFY_CLIENT_SECRET"
```
2. Send message to SQS
```bash
aws sqs send-message \
    --endpoint-url http://localhost:4566 \
    --message-body spotify:track:5Cjkfft7iRWJp4elZXgjkc \
    --message-attributes '{"channelId": {"DataType": "String", "StringValue": "REDACTED"}}' \
    --queue-url http://localhost:4566/000000000000/song-requests
```
...

**Comment by petervalencic** [comment]
Have you tried to wait for aprox. 5-10 minutes? I have almost the same problem.. I have an S3 bucket that triggers a Lambda service.. If I Invoke the service right after deployment I get almost the same error.. If I wait for a while then everything works well..

**Comment by SaxyPandaBear** [comment]
If that's what works, I'd like to understand why. I can try it tonight and see

**Comment by SaxyPandaBear** [comment]
Waited 25 minutes and got the same issue. Don't think that solves it.

**Comment by scottkennedy** [comment]
I'm also seeing this issue.

**Comment by scottkennedy** [comment]
I got it working.

Replace `"Handler": "com.github.saxypandabear.songrequests.spotify.Handler::handle",` with `"Handler": "com.github.saxypandabear.songrequests.spotify.Handler",`, and possibly change the function name to `handleRequest()`.

Though localstack should support specifying a function name with that notation.
