### ISSUE TITLE
Java Lambda, java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by ryantw** [localstack/localstack#3818]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

When trying to invoke a java8 lambda a java.lang.ClassNotFoundException is thrown.

## Expected behavior

Lambda execution succeeds.

## Actual behavior

Localstack claims that the Handler class can not be found.

# Steps to reproduce

Upload Lambda code:

$ aws --endpoint-url=http://localhost:4566 --region=us-east-1 lambda create-function --function-name mylambda --handler com.package.example.Handler --runtime java8 --role testwhatever --zip-file fileb://./build/libs/exampleHandler-uber.jar

After it is succeeds, Invoke the lambda:

$ aws --endpoint-url=http://localhost:4566 lambda invoke --region=us-east-1 --function-name mylambda --invocation-type Event response.json

localstack-msgpreproc | START RequestId: 04ba0c50-75fc-103d-3b26-b15a7c88ec59 Version: $LATEST
localstack-msgpreproc | java.lang.ClassNotFoundException
localstack-msgpreproc | Class not found: com.package.example.Handler 
localstack-msgpreproc | java.lang.ClassNotFoundException: com.package.example.Handler 
localstack-msgpreproc |         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
localstack-msgpreproc |         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
localstack-msgpreproc |         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
localstack-msgpreproc |         at java.lang.Class.forName0(Native Method)
localstack-msgpreproc |         at java.lang.Class.forName(Class.java:348)

## Command used to start LocalStack

docker-compose up

**Comment by ryantw** [comment]
Serverless can invoke the lambda & code without any issues via:

$ serverless invoke local -f process

**Comment by ryantw** [comment]
Here is my docker-compose.yml

version: '3'

services:

  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566-4599:4566-4599
      - 8080:8080 # the localstack admin portal
    container_name: localstack-msgpreproc
    networks:
      - frontend
    environment:
      - SERVICES=sqs,lambda,s3
      - HOSTNAME_EXTERNAL=localstack
      - DEBUG=1
      - DEFAULT_REGION=us-east-1 # Won't have to specify w/ aws local?
      - LAMBDA_EXECUTER=docker-reuse # separate containers for each function & reuse
      - LAMBDA_REMOTE_DOCKER=false
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./entrypoint-debug.sh:/docker-entrypoint-initaws.d/entrypoint-debug.sh # Run script on startup...
      - /var/run/docker.sock:/var/run/docker.sock

**Comment by ryantw** [comment]
I'm dumb. In my docker-compose.yml I needed to set LAMBDA_REMOTE_DOCKER to true to copy the code to the separate container........
