### ISSUE TITLE
SubscribeToShardRequest only supports LATEST iterator type on Kinesis

### ISSUE THREAD

**Issue by wem** [localstack/localstack#3823]
[x] bug report
[ ] feature request

# Detailed description

The SubscribeToShardRequest has the same capabilities to parameterize shard iterator type and sequence as getShardIterator requests. Unfortunately, the Localstack kinesis_listener don't use the sequence number of the incoming SubscribeToShardRequest on subsequent requests.

localstack/services/kinesis/kinesis_listener.py
```python
def subscribe_to_shard(data, headers):
    kinesis = aws_stack.connect_to_service('kinesis')
    stream_name = find_stream_for_consumer(data['ConsumerARN'])
    iter_type = data['StartingPosition']['Type']
    iterator = kinesis.get_shard_iterator(StreamName=stream_name,
        ShardId=data['ShardId'], ShardIteratorType=iter_type)['ShardIterator']
```

## Expected behavior

All shard iterator types: LATEST, AFTER_SEQUENCE_NUMBER, AT_SEQUENCE_NUMBER are supported and sequence number should get considered.

## Actual behavior

SubscribeToShardRequest is only supported to latest shard iterator. Any other provided shard iterator parameter combination will result in a failing subscription and the container log:

```bash
2021-04-03T05:07:53:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://127.0.0.1:49229/: An error occurred (InvalidArgumentException) when calling the GetShardIterator operation: Must either specify (1) AT_SEQUENCE_NUMBER or AFTER_SEQUENCE_NUMBER and StartingSequenceNumber or (2) TRIM_HORIZON or LATEST and no StartingSequenceNumber. Request specified AFTER_SEQUENCE_NUMBER and no StartingSequenceNumber. Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 129, in index
    raise result
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 682, in run
    result = self.func(self.params)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 607, in handler
    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 373, in modify_and_forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/edge.py", line 108, in forward_request
    return do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 119, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 139, in do_forward_request_inmem
    response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 373, in modify_and_forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py", line 94, in forward_request
    result = subscribe_to_shard(data, headers)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py", line 246, in subscribe_to_shard
    iterator = kinesis.get_shard_iterator(StreamName=stream_name,
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidArgumentException: An error occurred (InvalidArgumentException) when calling the GetShardIterator operation: Must either specify (1) AT_SEQUENCE_NUMBER or AFTER_SEQUENCE_NUMBER and StartingSequenceNumber or (2) TRIM_HORIZON or LATEST and no StartingSequenceNumber. Request specified AFTER_SEQUENCE_NUMBER and no StartingSequenceNumber.

```

Localstack version: 0.12.9.1
AWS SDK V2 Java: 2.16.19

**Comment by whummer** [comment]
Thanks for reporting @wem . This should be fixed in #3875 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks!
