### ISSUE TITLE
Localstack does not allow SES Template with HtmlPart but no TextPart despite AWS allowing it

### ISSUE THREAD

**Issue by hackerhasid** [localstack/localstack#3850]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description

Cannot create SES Template via Cloudformation without Text Part.

A simple CDK stack with only a single resource - an SES Template - fails to deploy to localstack unless the TextPart of the template is set. This behavior differs from that of actual AWS which allows the template to be deployed.

The error message from localstack is

```
Ready.
2021-04-08T13:31:09:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 13390.988111495972ms
2021-04-08T13:31:32:DEBUG:localstack.services.cloudformation.cloudformation_api: Executing change set "cdk-deploy-change-set" for stack "CDKToolkit" with 2 resources ...
2021-04-08T13:31:33:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
2021-04-08T13:31:33:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "StagingBucket" (1/2) type "AWS::S3::Bucket" in loop iteration 1
2021-04-08T13:31:33:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "S3::Bucket" id "StagingBucket"
2021-04-08T13:31:33:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "S3::Bucket" in region us-east-1: create_bucket {'Bucket': 'cdktoolkit-none-b45da2a6', 'ACL': 'private'}
2021-04-08T13:31:33:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
2021-04-08T13:31:33:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: S3::Bucket RegionalDomainName
2021-04-08T13:31:33:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "StagingBucketPolicy" (1/1) type "AWS::S3::BucketPolicy" in loop iteration 1
2021-04-08T13:31:33:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "S3::BucketPolicy" id "StagingBucketPolicy"
2021-04-08T13:31:33:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "S3::BucketPolicy" in region us-east-1: put_bucket_policy {'Bucket': 'cdktoolkit-none-b45da2a6', 'Policy': '{"Id": "AccessControl", "Version": "2012-10-17", "Statement": [{"Sid": "AllowSSLRequestsOnly", "Action": "s3:*", "Effect": "Deny", "Resource": ["arn:aws:s3:::cdktoolkit-none-b45da2a6", "arn:aws:s3:::cdktoolkit-none-b45da2a6/*"], "Condition": {"Bool": {"aws:SecureTransport": "false"}}, "Principal": "*"}]}'}
2021-04-08T13:31:33:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: S3::BucketPolicy PhysicalResourceId
2021-04-08T13:31:33:INFO:localstack.utils.cloudformation.template_deployer: Unable to determine PhysicalResourceId for "S3::BucketPolicy" resource, ID "StagingBucketPolicy"
2021-04-08T13:31:46:DEBUG:localstack.services.cloudformation.cloudformation_api: Executing change set "cdk-deploy-change-set" for stack "MyAppStack" with 2 resources ...
2021-04-08T13:31:46:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type SES::Template when resolving references of resource LeadEmail: {'Type': 'AWS::SES::Template', 'Metadata': {'aws:cdk:path': 'MyAppStack/LeadEmail'}, 'LogicalResourceId': 'LeadEmail', 'Properties': {'Template': {'HtmlPart': '<html><body>Test</body></html>', 'SubjectPart': 'Thank You For Contacting Us', 'TemplateName': 'Confirmation-Lead'}}}
2021-04-08T13:31:46:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "LeadEmail" (1/2) type "AWS::SES::Template" in loop iteration 1
2021-04-08T13:31:46:INFO:localstack.utils.cloudformation.template_deployer: Action "create" for resource type SES::Template not yet implemented - using fallback mechanism
2021-04-08T13:31:46:DEBUG:localstack.utils.cloudformation.template_deployer: Unable to extract name for resource type "AWS::SES::Template"
2021-04-08T13:31:46:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: SES::Template PhysicalResourceId
2021-04-08T13:31:46:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "MyAppStack": Unable to extract attribute "PhysicalResourceId" from "SES::Template" model class <class 'localstack.services.cloudformation.service_models.GenericBaseModel'> Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1952, in _run
    self.do_apply_changes_in_loop(changes, stack, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1999, in do_apply_changes_in_loop
    self.apply_change(change, stack, new_resources, stack_name=stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2059, in apply_change
    self.update_resource_details(resource_id, result, stack=old_stack, action=stack_action)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1824, in update_resource_details
    physical_id = physical_id or determine_resource_physical_id(resource_id, stack=stack)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1523, in determine_resource_physical_id
    result = extract_resource_attribute(resource_type, {}, attribute or 'PhysicalResourceId',
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py", line 636, in extract_resource_attribute
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 706, in extract_resource_attribute
    raise Exception('Unable to extract attribute "%s" from "%s" model class %s' % (
Exception: Unable to extract attribute "PhysicalResourceId" from "SES::Template" model class <class 'localstack.services.cloudformation.service_models.GenericBaseModel'>
```

## Expected behavior

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ses-template-template.html#cfn-ses-template-template-textpart specifies that the TextPart is optional. And in fact, `cdk deploy` using the template below works fine, it only fails against localstack.

## Actual behavior

`cdklocal deploy` fails 

# Steps to reproduce

1. Start localstack (`localstack start`)
2. Create CDK stack with an SES template with an HtmlPart but no TextPart
3. run `cdk bootstrap`
4. run `cdk deploy`

## Command used to start LocalStack

> localstack start

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```typescript
export class MyAppStack extends cdk.Stack {

  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    new ses.CfnTemplate(this, 'LeadEmail', {
      template: {
        templateName: 'Test',
        subjectPart: 'Test',
        htmlPart:'<html><body>test</body></html>'
      }
    });
  }
}
```

## Workaround

The current workaround is to add a TextPart property to the template. So unlike the Client code above, the following does deploy:

```typescript
export class MyAppStack extends cdk.Stack {

  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    new ses.CfnTemplate(this, 'LeadEmail', {
      template: {
        templateName: 'Test',
        subjectPart: 'Test',
        htmlPart:'<html><body>test</body></html>',
        textPart: 'test'
      }
    });
  }
}
```

**Comment by whummer** [comment]
Thanks for reporting @hackerhasid . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please keep us posted how it goes. Thanks for your help!
