### ISSUE TITLE
Cognito user pool not getting created and awslocal command failing

### ISSUE THREAD

**Issue by rnjailamba** [localstack/localstack#3861]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
We started localstack as normal today with latest tag and then with 0.12.9 tag version. The result of http://localhost:4566/health is `{"services": {"apigateway": "running", "cloudformation": "running", "cloudwatch": "running", "lambda": "running", "logs": "running", "cognito-identity": "running", "cognito-idp": "running"}}`. After this we tried running our standard scripts to create user pools using cognito but after trying to run a command line command -  AWS_DEFAULT_REGION=us-east-2 awslocal cognito-idp list-user-pools --max-results 10 we got the following output
`An error occurred (500) when calling the ListUserPools operation (reached max retries: 2): `

## Expected behavior
An error is not expected

## Actual behavior
Here are the logs besides the error mentioned above - 
```
localstack | Waiting for all LocalStack services to be ready
localstack | Ready.
localstack | 2021-04-11T20:19:53:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 6291.6600704193115ms
localstack | 2021-04-11T20:20:48:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
localstack | 2021-04-11T20:21:48:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
localstack | 2021-04-11T20:22:44:WARNING:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fb31e1ca0d0>(None) failed: name 'jcNQq' is not defined Traceback (most recent call last):
localstack | File "/opt/code/localstack/localstack/utils/bootstrap.py", line 672, in run
localstack | result = self.func(self.params)
localstack | File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack | return fn(*args, **kwargs)
localstack | File "/opt/code/localstack/localstack/services/generic_proxy.py", line 607, in handler
localstack | response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack | File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/aws/aws_utils.py", line 25, in modify_and_forward
localstack | File "/opt/code/localstack/localstack/services/generic_proxy.py", line 443, in modify_and_forward
localstack | updated_response = update_listener.return_response(**kwargs)
localstack | File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py", line 147, in return_response
localstack | update_func(rwlock,method,path,data=data,headers=headers)
localstack | File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/base.py", line 124, in update_backend_state
localstack | File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_helpers.py", line 87, in should_persist_state_for_request
localstack | NameError: name 'jcNQq' is not defined
localstack | 2021-04-11T20:22:44:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: name 'jcNQq' is not defined Traceback (most recent call last):
localstack | File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 129, in index
```

# Steps to reproduce
docker-compose.yml
```
version: "3.7"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack:0.12.9
    networks:
      - mynet
    ports:
      - "4566-4599:4566-4599"
      - 443:443
    environment:
      - SERVICES=lambda,cognito,apigateway,cloudformation
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_DOCKER_NETWORK=host
      - LAMBDA_REMOVE_CONTAINERS=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d
networks:
  mynet:
    name: mynet
```

## Command used to start LocalStack
docker-compose up -d

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Reporduce with following `awslocal` command - 
`AWS_DEFAULT_REGION=us-east-2 awslocal cognito-idp list-user-pools --max-results 10
`
Optionally, same error can be recreated by following `index.js` -
```
const {
    CognitoIdentityServiceProvider,
    CognitoIdentity
} = require('aws-sdk');
var AWS = require('aws-sdk');

(async function() {
            //TODO: cant share this code but just loads AWS SDK credentials
            process.env.STAGE = 'dev';
            const endpoint = 'http://localhost:4566';
            const region = 'us-east-2';

            AWS.config = {
                credentials: {
                    accessKeyId: "local",
                    secretAccessKey: "local",
                },
                endpoint: endpoint,
                region: region,
            }

            console.log('-- STARTING --');

            const cognito = new CognitoIdentityServiceProvider({
                endpoint,
                region
            });
            const identity = new CognitoIdentity({
                endpoint,
                region
            });
            let userpool = null;
            const poolName = 'sunroom-dev';
            console.log('-- CREATING USER POOL OR FINDING IT --');
            try {
                userpool = await cognito.createUserPool({
                    PoolName: poolName,
                    LambdaConfig: {
                        'PreTokenGeneration': "arn:aws:lambda:us-east-2:000000000000:function:addHasuraClaims",
                        'PostConfirmation': "arn:aws:lambda:us-east-2:000000000000:function:syncToHasura"
                    }
                }).promise();
            } catch (err) {
                console.log(err);
                const pools = await cognito.listUserPools({
                    MaxResults: 25
                }).promise();
                const pool = pools.UserPools.find((p) => p.Name == poolName);
                userpool = await cognito.describeUserPool({
                    UserPoolId: pool.Id
                }).promise();
            }
            const pools = await cognito.listUserPools({
                MaxResults: 25
            }).promise();
            console.log(pools);
            if (userpool == null) {
                throw new Error('cant find pool at all');
            }
            let client = null;
            const clientName = 'sunroom-dev-client';
            console.log('-- CREATING USERPOOL CLIENT OR FINDING IT --');
            try {
                client = await cognito.createUserPoolClient({
                    UserPoolId: userpool.UserPool.Id,
                    ClientName: clientName,
                    GenerateSecret: false,
                    ExplicitAuthFlows: [
                        'ALLOW_ADMIN_USER_PASSWORD_AUTH'
                    ]
                }).promise();
            } catch (err) {
                console.log(err);
                const clients = await cognito.listUserPoolClients({
                    UserPoolId: userpool.UserPool.Id
                }).promise();
                const tempClient = clients.UserPoolClients.find((c) => c.ClientName == clientName);
                client = await cognito.describeUserPoolClient({
                    UserPoolId: userpool.UserPool.Id,
                    ClientId: tempClient.ClientId
                }).promise();
            }
            const clients = await cognito.listUserPoolClients({
                UserPoolId: userpool.UserPool.Id
            }).promise();
            console.log(clients);

            if (client == null) {
                throw new Error('cant find client');
            }
            console.log('-- CREATING IDENTITY POOL CLIENT OR CREATING IT --');
            let identitypool = null;
            const identitypoolName = 'sunroom-dev-identity-pool';
            try {
                identitypool = await identity.createIdentityPool({
                    IdentityPoolName: identitypoolName,
                    AllowUnauthenticatedIdentities: true,
                    CognitoIdentityProviders: [{
                        ProviderName: 'test',
                        ClientId: client.UserPoolClient.ClientId
                    }]
                }).promise();
            } catch (err) {
                console.log(err);
                const idpools = await identity.listIdentityPools({
                    MaxResults: 25
                }).promise();
                const id = idpools.IdentityPools.find((i) => i.IdentityPoolName == identitypoolName);
                identitypool = await identity.describeIdentityPool({
                    IdentityPoolId: id.IdentityPoolId
                }).promise();
            }
            const idpools = await identity.listIdentityPools({
                MaxResults: 25
            }).promise();
            console.log(idpools);
            if (identitypool == null) {
                throw new Error('cant find ID pool');
            }
```

**Comment by whummer** [comment]
Thanks for reporting @rnjailamba. There appears to have been a temporary glitch in our CI build pipeline. This should be fixed in the `latest` Docker image in the meantime.

```
$ AWS_DEFAULT_REGION=us-east-2 awslocal cognito-idp list-user-pools --max-results 10 
{
    "UserPools": []
}
```

```
LocalStack version: 0.12.9.1
LocalStack Docker image id: 7f4a11bee5f9
LocalStack build date: 2021-04-11
LocalStack build git hash: 8987e5a7
```

Please let us know if the problem persists. Thanks for your help!

**Comment by rnjailamba** [comment]
A laptop restart fixed this (trying to find out why) but additional information on the case is that earlier in the day i had run the following to clean all images, volumes -
```
docker rm -vf $(docker ps -a -q)
docker rmi -f $(docker images -a -q)
```
