### ISSUE TITLE
MalformedPolicyDocumentException Resource must be in ARN format or <wildcard>

### ISSUE THREAD

**Issue by johnmee** [localstack/localstack#3863]
I'm a little stuck with this one and appsync.  I am using the "pro" version under the free trial period.

`botocore.errorfactory.MalformedPolicyDocumentException: An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy operation: Resource /aws/appsync/apis/3908675c must be in ARN format or "*"`

The Cloudformation template, at the offensive point, reads

```    
"GraphQlApiLogGroup": {
      "Type": "AWS::Logs::LogGroup",
      "Properties": {
        "LogGroupName": {
          "Fn::Join": [
            "/",
            [
              "/aws/appsync/apis",
              {
                "Fn::GetAtt": [
                  "GraphQlApi",
                  "ApiId"
                ]
              }
            ]
```

Which appears verbatim (the same) when deploying to aws; which doesn't seem to mind getting the filepath.

I am using serveless localstack to generate the templates.  The only mention of LogGroup in the serverless.yml is in a PolicyDocument->Action.  I've asked this question over there but no reaction as yet.

```
              Action:
                - logs:CreateLogGroup
```

The log goes like this

```
localstack_main | 2021-04-09T07:09:46:DEBUG:localstack.utils.cloudformation.template_deployer: Action "update" not yet implemented for CF resource type AWS::Lambda::LayerVersion
localstack_main | 2021-04-09T07:09:46:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Modify" for resource "PythonRequirementsLambdaLayer" (1/13) type "AWS::Lambda::LayerVersion" in loop iteration 1
localstack_main | 2021-04-09T07:09:46:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Modify" for resource "ActiveLifeBaseServiceRole" (1/12) type "AWS::IAM::Role" in loop iteration 1
localstack_main | 2021-04-09T07:09:46:INFO:localstack.utils.cloudformation.template_deployer: Updating resource ActiveLifeBaseServiceRole of type IAM::Role
localstack_main | 2021-04-09T07:09:46:DEBUG:localstack.utils.cloudformation.template_deployer: Action "update" not yet implemented for CF resource type AWS::IAM::ManagedPolicy
localstack_main | 2021-04-09T07:09:46:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Modify" for resource "ActiveLifeBasePolicy" (1/11) type "AWS::IAM::ManagedPolicy" in loop iteration 1
localstack_main | 2021-04-09T07:09:46:DEBUG:localstack.utils.cloudformation.template_deployer: Action "update" not yet implemented for CF resource type AWS::AppSync::GraphQLApi
localstack_main | 2021-04-09T07:09:46:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Modify" for resource "GraphQlApi" (1/10) type "AWS::AppSync::GraphQLApi" in loop iteration 1
localstack_main | 2021-04-09T07:09:46:DEBUG:localstack.utils.cloudformation.template_deployer: Action "update" not yet implemented for CF resource type AWS::Logs::LogGroup
localstack_main | 2021-04-09T07:09:46:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Modify" for resource "GraphQlApiLogGroup" (1/9) type "AWS::Logs::LogGroup" in loop iteration 1
localstack_main | 2021-04-09T07:09:46:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Modify" for resource "GraphQlApiCloudWatchLogsPolicy" (1/8) type "AWS::IAM::Policy" in loop iteration 1
localstack_main | 2021-04-09T07:09:46:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "IAM::Policy" id "GraphQlApiCloudWatchLogsPolicy"
localstack_main | 2021-04-09T07:09:46:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "activelife-base-local": An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy operation: Resource /aws/appsync/apis/3908675c must be in ARN format or "*". Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1952, in _run
localstack_main |     self.do_apply_changes_in_loop(changes, stack, stack_name)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1999, in do_apply_changes_in_loop
localstack_main |     self.apply_change(change, stack, new_resources, stack_name=stack_name)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2052, in apply_change
localstack_main |     result = deploy_resource(resource_id, new_resources, stack_name)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1097, in deploy_resource
localstack_main |     return execute_resource_action(resource_id, resources, stack_name, ACTION_CREATE)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1196, in execute_resource_action
localstack_main |     result = func['function'](resource_id, resources, resource_type, func, stack_name)
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/service_models.py", line 599, in _create
localstack_main |     iam.put_role_policy(RoleName=role, PolicyName=policy_name, PolicyDocument=policy_doc)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
localstack_main |     return self._make_api_call(operation_name, kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
localstack_main |     raise error_class(parsed_response, operation_name)
localstack_main | botocore.errorfactory.MalformedPolicyDocumentException: An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy operation: Resource /aws/appsync/apis/3908675c must be in ARN format or "*".
localstack_main | 
```

Is it an issue with the Layer?
You want me to post more logs?

Key question is whether to keep banging my head on this wall (ie my issue), or is it a localstack issue?

**Comment by johnmee** [comment]
I might add that the pathname `/aws/appsync/apis` is encoded into the serverless appsync plugin here:
https://github.com/sid88in/serverless-appsync-plugin/blob/ff5d166edb75e9d10fc1f8af3bf64784f19cfb33/src/index.js#L431

**Comment by johnmee** [comment]
@duongpv7 Are you looking at this? Can you shed any light on the problem?

**Comment by whummer** [comment]
Thanks for reporting this issue @johnmee . We have pushed a few minor enhancements in the meantime - can you please do a `docker pull localstack/localstack` and give it another try with the `latest` Docker image? 

If the problem persists - do you think you could share a small sample project to help us replicate the issue end-to-end? Thanks for your help

**Comment by johnmee** [comment]
Thanks for the effort.   Sorry (I assume) I cannot test as my trial version expired.  Additionally my boss is doubtful about buying a license to find out, or even whether to invest more time into this solution.
