### ISSUE TITLE
RDS Missing required parameter in input: "DBSubnetGroupName"

### ISSUE THREAD

**Issue by ShaunParsons** [localstack/localstack#3874]
# Type of request: This is a ...

[ x ] bug report
[ ] feature request

# Detailed description

Unable to create an RDS instance. I'm not sure if I'm missing something here?

## Expected behavior

RDS instance created.

## Actual behavior

```bash
localstack_1             | 2021-04-14T18:59:23:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected error retrieving details for resource RDS::DBSubnetGroup: Parameter validation failed:
localstack_1             | Missing required parameter in input: "DBSubnetGroupName"   File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
localstack_1             |     self._bootstrap_inner()
localstack_1             |   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
localstack_1             |     self.run()
localstack_1             |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/aws/aws_utils.py", line 85, in thread_run
localstack_1             |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 682, in run
localstack_1             |     result = self.func(self.params)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1925, in _run
localstack_1             |     self.do_apply_changes_in_loop(changes, stack, stack_name)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1976, in do_apply_changes_in_loop
localstack_1             |     self.apply_change(change, stack, new_resources, stack_name=stack_name)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2031, in apply_change
localstack_1             |     result = delete_resource(resource_id, old_stack.resources, stack_name)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1127, in delete_resource
localstack_1             |     return execute_resource_action(resource_id, resources, stack_name, ACTION_DELETE)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1167, in execute_resource_action
localstack_1             |     result = configure_resource_via_sdk(resource_id, resources, resource_type, func, stack_name, action_name)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1275, in configure_resource_via_sdk
localstack_1             |     if action_name == 'delete' and check_not_found_exception(e, resource_type, resource):
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 645, in check_not_found_exception
localstack_1             |     (resource_type, e, ''.join(traceback.format_stack()), resource, resource_status))
localstack_1             |  - {'Type': 'AWS::RDS::DBSubnetGroup', 'Metadata': {'aws:cdk:path': 'vpc-test/vpc-test-database/SubnetGroup/Default'}, 'LogicalResourceId': 'vpctestdatabaseSubnetGroupED34A978', 'Properties': {'DBSubnetGroupDescription': 'Subnet group for vpc-test-database database', 'SubnetIds': ['subnet-5f6cafd0', 'subnet-c6828d46', 'subnet-1617edfc']}, '_state_': {}, 'PhysicalResourceId': None} None
localstack_1             | 2021-04-14T18:59:23:WARNING:localstack.utils.cloudformation.template_deployer: Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.RDS object at 0x7f803f7f0190>> with params: {} for resource: {'Type': 'AWS::RDS::DBSubnetGroup', 'Metadata': {'aws:cdk:path': 'vpc-test/vpc-test-database/SubnetGroup/Default'}, 'LogicalResourceId': 'vpctestdatabaseSubnetGroupED34A978', 'Properties': {'DBSubnetGroupDescription': 'Subnet group for vpc-test-database database', 'SubnetIds': ['subnet-5f6cafd0', 'subnet-c6828d46', 'subnet-1617edfc']}, '_state_': {}, 'PhysicalResourceId': None}
localstack_1             | 2021-04-14T18:59:23:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "vpc-test": Parameter validation failed:
localstack_1             | Missing required parameter in input: "DBSubnetGroupName" Traceback (most recent call last):
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1925, in _run
localstack_1             |     self.do_apply_changes_in_loop(changes, stack, stack_name)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1976, in do_apply_changes_in_loop
localstack_1             |     self.apply_change(change, stack, new_resources, stack_name=stack_name)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2031, in apply_change
localstack_1             |     result = delete_resource(resource_id, old_stack.resources, stack_name)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1127, in delete_resource
localstack_1             |     return execute_resource_action(resource_id, resources, stack_name, ACTION_DELETE)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1167, in execute_resource_action
localstack_1             |     result = configure_resource_via_sdk(resource_id, resources, resource_type, func, stack_name, action_name)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1278, in configure_resource_via_sdk
localstack_1             |     raise e
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1273, in configure_resource_via_sdk
localstack_1             |     result = function(**params)
localstack_1             |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
localstack_1             |     return self._make_api_call(operation_name, kwargs)
localstack_1             |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 648, in _make_api_call
localstack_1             |     request_dict = self._convert_to_request_dict(
localstack_1             |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 696, in _convert_to_request_dict
localstack_1             |     request_dict = self._serializer.serialize_to_request(
localstack_1             |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/validate.py", line 293, in serialize_to_request
localstack_1             |     raise ParamValidationError(report=report.generate_report())
localstack_1             | botocore.exceptions.ParamValidationError: Parameter validation failed:
localstack_1             | Missing required parameter in input: "DBSubnetGroupName"
```

# Steps to reproduce

## CDK

```typescript
    const vpc = new ec2.Vpc(this, "vpc", {
      cidr: "10.0.0.0/16",
      maxAzs: 3,
      natGateways: props.natGateways,
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: "public",
          subnetType: ec2.SubnetType.PUBLIC
        },
        {
          cidrMask: 24,
          name: "application",
          subnetType: ec2.SubnetType.PRIVATE
        },
        {
          cidrMask: 24,
          name: "rds",
          subnetType: ec2.SubnetType.ISOLATED
        }
      ]
    });

    const applicationSecurityGroup = new ec2.SecurityGroup(
      this,
      `${id}-application-security-group`,
      {
        vpc: vpc,
        securityGroupName: `${id}-application-security-group`
      }
    );

    const databaseSecurityGroup = new ec2.SecurityGroup(
      this,
      `${id}-database-security-group`,
      {
        vpc: vpc,
        securityGroupName: `${id}-database-security-group`,
        allowAllOutbound: false
      }
    );

    databaseSecurityGroup.addIngressRule(
      applicationSecurityGroup,
      ec2.Port.tcp(5432)
    );

    this.database = new rds.DatabaseInstance(this, `${id}-database`, {
      allocatedStorage: 20,
      multiAz: false,
      backupRetention: cdk.Duration.days(1),
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.BURSTABLE3,
        ec2.InstanceSize.MICRO
      ),
      credentials: rds.Credentials.fromPassword(
        "user",
        new cdk.SecretValue(process.env.DATABASE_PASSWORD)
      ),
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_12_5
      }),
      vpc: vpc,
      subnetGroup: new rds.SubnetGroup(this, `${id}-database-subnet-group`, {
        description: `${id}-database-subnet-group`,
        subnetGroupName: `${id}-database-subnet-group`,
        vpc: vpc,
        vpcSubnets: {
          subnetGroupName: "rds"
        }
      }),
      securityGroups: [databaseSecurityGroup]
    });
```

## Command used to start LocalStack

`docker-compose up -d localstack`

### docker-compose.yml
```yml
  localstack:
    image: 'localstack/localstack'
    ports:
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SERVICES=s3,sqs,rds,sns,cloudformation,ec2,iam,lambda,kms,cognito,apigatewayv2,secretsmanager,route53
      - DEBUG=true
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
      - LOCALSTACK_HOSTNAME=localhost
      - HOSTNAME=localhost
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

**Comment by whummer** [comment]
Thanks for reporting @ShaunParsons . This should (hopefully) be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please keep us posted how it goes. Thanks for your help!

**Comment by ShaunParsons** [comment]
Thanks @whummer I can confirm thats fixed.
