### ISSUE TITLE
Feature Request: ApiGatewayV2::Authorizer

### ISSUE THREAD

**Issue by ShaunParsons** [localstack/localstack#3880]
# Type of request: This is a ...

- [ ] bug report
- [x] feature request

# Detailed description

ApiGatewayV2::Authorizer not implemented

## Actual behavior

```bash
localstack_1             | 2021-04-15T18:03:36:INFO:localstack.utils.cloudformation.template_deployer: Action "create" for resource type ApiGatewayV2::Authorizer not yet implemented - using fallback mechanism
localstack_1             | 2021-04-15T18:03:36:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: ApiGatewayV2::Authorizer PhysicalResourceId
localstack_1             | 2021-04-15T18:03:36:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "dev-application": Unable to extract attribute "PhysicalResourceId" from "ApiGatewayV2::Authorizer" model class <class 'localstack.services.cloudformation.service_models.GenericBaseModel'> Traceback (most recent call last):
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1936, in _run
localstack_1             |     self.do_apply_changes_in_loop(changes, stack, stack_name)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1987, in do_apply_changes_in_loop
localstack_1             |     self.apply_change(change, stack, new_resources, stack_name=stack_name)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2047, in apply_change
localstack_1             |     self.update_resource_details(resource_id, result, stack=old_stack, action=stack_action)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1808, in update_resource_details
localstack_1             |     physical_id = physical_id or determine_resource_physical_id(resource_id, stack=stack)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1500, in determine_resource_physical_id
localstack_1             |     result = extract_resource_attribute(resource_type, {}, attribute or 'PhysicalResourceId',
localstack_1             |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py", line 637, in extract_resource_attribute
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 672, in extract_resource_attribute
localstack_1             |     raise Exception('Unable to extract attribute "%s" from "%s" model class %s' % (
localstack_1             | Exception: Unable to extract attribute "PhysicalResourceId" from "ApiGatewayV2::Authorizer" model class <class 'localstack.services.cloudformation.service_models.GenericBaseModel'>
```

# Steps to reproduce

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```typescript
new apigatewayv2Authorizers.HttpUserPoolAuthorizer({
    userPool: props.userPool,
    userPoolClient: props.userPoolClient,
    identitySource: ["$request.header.Authorization"]
})
```

**Comment by whummer** [comment]
Thanks for reporting @ShaunParsons . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
