### ISSUE TITLE
CDK::Metadata

### ISSUE THREAD

**Issue by ShaunParsons** [localstack/localstack#3894]
# Type of request: This is a ...

- [x] bug report
- [ ] feature request

# Detailed description

Unable to deploy

## Expected behavior

...

## Actual behavior
```bash
localstack_1             | 2021-04-19T19:21:20:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "CDKMetadata" (1/1) type "AWS::CDK::Metadata" in loop iteration 2
localstack_1             | 2021-04-19T19:21:20:INFO:localstack.utils.cloudformation.template_deployer: Action "create" for resource type CDK::Metadata not yet implemented - using fallback mechanism
localstack_1             | 2021-04-19T19:21:20:DEBUG:localstack.utils.cloudformation.template_deployer: Unable to extract name for resource type "AWS::CDK::Metadata"
localstack_1             | 2021-04-19T19:21:20:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: CDK::Metadata PhysicalResourceId
localstack_1             | 2021-04-19T19:21:20:DEBUG:localstack.utils.cloudformation.template_deployer: Dependencies for "CDKMetadata" not yet satisfied, retrying in next loop: Unable to fetch details for resource "CDKMetadata" (attribute "PhysicalResourceId")
localstack_1             | 2021-04-19T19:21:20:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "CDKMetadata" (1/1) type "AWS::CDK::Metadata" in loop iteration 3
localstack_1             | 2021-04-19T19:21:20:INFO:localstack.utils.cloudformation.template_deployer: Action "create" for resource type CDK::Metadata not yet implemented - using fallback mechanism
localstack_1             | 2021-04-19T19:21:20:DEBUG:localstack.utils.cloudformation.template_deployer: Unable to extract name for resource type "AWS::CDK::Metadata"
localstack_1             | 2021-04-19T19:21:20:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: CDK::Metadata PhysicalResourceId
localstack_1             | 2021-04-19T19:21:20:DEBUG:localstack.utils.cloudformation.template_deployer: Dependencies for "CDKMetadata" not yet satisfied, retrying in next loop: Unable to fetch details for resource "CDKMetadata" (attribute "PhysicalResourceId")
localstack_1             | 2021-04-19T19:21:20:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "dev-data-stores": Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'CDKMetadata', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CDK::Metadata', 'Replacement': 'False', 'ChangeSetId': None}}] Traceback (most recent call last):
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1936, in _run
localstack_1             |     self.do_apply_changes_in_loop(changes, stack, stack_name)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1997, in do_apply_changes_in_loop
localstack_1             |     raise Exception('Resource deployment loop completed, pending resource changes: %s' % changes)
localstack_1             | Exception: Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'CDKMetadata', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CDK::Metadata', 'Replacement': 'False', 'ChangeSetId': None}}]
localstack_1             | 
```

# Steps to reproduce

## Command used to start LocalStack

```bash
docker-compose up -d localstack
```

### docker-compose.yml
```yml
 localstack:
    image: 'localstack/localstack'
    ports:
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SERVICES=s3,sqs,rds,sns,cloudformation,ec2,iam,lambda,kms,cognito,apigatewayv2,secretsmanager,route53,apigateway
      - DEBUG=true
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
      - LOCALSTACK_HOSTNAME=localhost
      - HOSTNAME=localhost
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
 ```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```typescript
import * as cdk from "@aws-cdk/core";
import * as ec2 from "@aws-cdk/aws-ec2";
import * as cognito from "@aws-cdk/aws-cognito";
import * as rds from "@aws-cdk/aws-rds";
import * as s3 from "@aws-cdk/aws-s3";
import * as kms from "@aws-cdk/aws-kms";
import * as iam from "@aws-cdk/aws-iam";

export interface DatabaseProps {
  readonly allocatedStorage?: number;
  readonly multiAz?: boolean;
  readonly backupRetention?: cdk.Duration;
  readonly instanceType?: ec2.InstanceType;
}

export interface DataStoresStackProps extends cdk.StackProps {
  readonly prefix?: string;
  readonly env?: object;
  readonly natGateways?: number;
  readonly databaseProps?: DatabaseProps;
}

export interface DataStoresSecurityGroups {
  readonly application: ec2.SecurityGroup;
  readonly database: ec2.SecurityGroup;
}

export interface DataStoresBuckets {
  readonly importExport: s3.Bucket;
  readonly nonSensitiveData: s3.Bucket;
  readonly sensitiveData: s3.Bucket;
  readonly temporaryData: s3.Bucket;
}

const DataStoresStackPropsDefaults: DataStoresStackProps = {
  natGateways: 1,
  databaseProps: {
    allocatedStorage: 20,
    multiAz: false,
    backupRetention: cdk.Duration.days(1),
    instanceType: ec2.InstanceType.of(
      ec2.InstanceClass.BURSTABLE3,
      ec2.InstanceSize.MICRO
    )
  }
};

export class DataStoresStack extends cdk.Stack {
  public vpc: ec2.Vpc;

  public securityGroup: DataStoresSecurityGroups;

  public bucket: DataStoresBuckets;

  public userPool: cognito.UserPool;

  public userPoolClient: cognito.UserPoolClient;

  public databaseUser: string;

  public databaseName: string;

  public database: rds.DatabaseInstance;

  constructor(scope: cdk.App, id: string, props: DataStoresStackProps) {
    props = { ...DataStoresStackPropsDefaults, ...props };
    super(scope, id, props);
    this.vpc = new ec2.Vpc(this, "vpc", {
      cidr: "10.0.0.0/16",
      maxAzs: 3,
      natGateways: props.natGateways,
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: "public",
          subnetType: ec2.SubnetType.PUBLIC
        },
        {
          cidrMask: 24,
          name: "application",
          subnetType: ec2.SubnetType.PRIVATE
        },
        {
          cidrMask: 24,
          name: "rds",
          subnetType: ec2.SubnetType.ISOLATED
        }
      ]
    });

    const applicationSecurityGroup = new ec2.SecurityGroup(
      this,
      `${id}-application-security-group`,
      {
        vpc: this.vpc,
        securityGroupName: `${id}-application-security-group`
      }
    );

    const databaseSecurityGroup = new ec2.SecurityGroup(
      this,
      `${id}-database-security-group`,
      {
        vpc: this.vpc,
        securityGroupName: `${id}-database-security-group`,
        allowAllOutbound: false
      }
    );

    databaseSecurityGroup.addIngressRule(
      applicationSecurityGroup,
      ec2.Port.tcp(5432)
    );

    this.securityGroup = {
      application: applicationSecurityGroup,
      database: databaseSecurityGroup
    };

    this.userPool = new cognito.UserPool(this, `${id}-user-pool`, {
      userPoolName: `${id}-user-pool`,
      autoVerify: {
        email: true,
        phone: false
      },
      signInAliases: {
        email: true,
        phone: false,
        username: false,
        preferredUsername: false
      }
    });

    this.userPoolClient = new cognito.UserPoolClient(
      this,
      `${id}-user-pool-client`,
      {
        userPoolClientName: `${id}-user-pool-client`,
        userPool: this.userPool,
        generateSecret: false
      }
    );

    // RDS
    this.databaseUser = `db_${props.prefix}_user`.replace(/-/g, "_");
    this.databaseName = `db_${props.prefix}`.replace(/-/g, "_");
    this.database = new rds.DatabaseInstance(this, `${id}-database`, {
      ...props.databaseProps,
      credentials: rds.Credentials.fromPassword(
        this.databaseUser,
        new cdk.SecretValue(process.env.DATABASE_PASSWORD)
      ),
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_12_5
      }),
      vpc: this.vpc,
      subnetGroup: new rds.SubnetGroup(this, `${id}-database-subnet-group`, {
        description: `${id}-database-subnet-group`,
        subnetGroupName: `${id}-database-subnet-group`,
        vpc: this.vpc,
        vpcSubnets: {
          subnetGroupName: "rds"
        }
      }),
      securityGroups: [this.securityGroup.database]
    });

    // S3
    const importExportBucket = new s3.Bucket(this, `${id}-import-export`, {
      bucketName: `${id}-import-export`,
      accessControl: s3.BucketAccessControl.PRIVATE,
      blockPublicAccess: new s3.BlockPublicAccess({
        blockPublicAcls: true,
        blockPublicPolicy: true,
        ignorePublicAcls: true,
        restrictPublicBuckets: true
      }),
      lifecycleRules: [
        {
          abortIncompleteMultipartUploadAfter: cdk.Duration.days(2),
          enabled: true,
          expiration: cdk.Duration.days(14)
        }
      ],
      encryption: s3.BucketEncryption.S3_MANAGED
    });

    const sensitiveDataBucket = new s3.Bucket(this, `${id}-sensitive-data`, {
      bucketName: `${id}-sensitive-data`,
      accessControl: s3.BucketAccessControl.PRIVATE,
      blockPublicAccess: new s3.BlockPublicAccess({
        blockPublicAcls: true,
        blockPublicPolicy: true,
        ignorePublicAcls: true,
        restrictPublicBuckets: true
      }),
      lifecycleRules: [
        {
          abortIncompleteMultipartUploadAfter: cdk.Duration.days(2),
          enabled: true,
          expiration: cdk.Duration.days(28)
        }
      ],
      encryption: s3.BucketEncryption.S3_MANAGED
    });

    const nonSensitiveDataBucket = new s3.Bucket(
      this,
      `${id}-non-sensitive-data`,
      {
        bucketName: `${id}-non-sensitive-data`,
        accessControl: s3.BucketAccessControl.PRIVATE,
        blockPublicAccess: new s3.BlockPublicAccess({
          blockPublicAcls: true,
          blockPublicPolicy: true,
          ignorePublicAcls: true,
          restrictPublicBuckets: true
        }),
        lifecycleRules: [
          {
            abortIncompleteMultipartUploadAfter: cdk.Duration.days(2),
            enabled: true
          }
        ],
        encryption: s3.BucketEncryption.S3_MANAGED,
        versioned: true
      }
    );

    const temporaryDataBucket = new s3.Bucket(this, `${id}-temporary-data`, {
      bucketName: `${id}-temporary-data`,
      accessControl: s3.BucketAccessControl.PRIVATE,
      blockPublicAccess: new s3.BlockPublicAccess({
        blockPublicAcls: true,
        blockPublicPolicy: true,
        ignorePublicAcls: true,
        restrictPublicBuckets: true
      }),
      lifecycleRules: [
        {
          abortIncompleteMultipartUploadAfter: cdk.Duration.days(1),
          enabled: true,
          expiration: cdk.Duration.days(1)
        }
      ],
      encryption: s3.BucketEncryption.S3_MANAGED,
      cors: [
        {
          allowedMethods: [s3.HttpMethods.POST, s3.HttpMethods.GET],
          allowedOrigins: ["*"],
          allowedHeaders: ["*"]
        }
      ]
    });

    this.bucket = {
      importExport: importExportBucket,
      sensitiveData: sensitiveDataBucket,
      nonSensitiveData: nonSensitiveDataBucket,
      temporaryData: temporaryDataBucket
    };

    const user = iam.User.fromUserArn(
      this,
      `${id}-username`,
      `arn:aws:iam::${this.account}:user/username
    );

    const encryptionKey = new kms.Key(this, `${id}-encryption-key`, {
      enabled: true,
      enableKeyRotation: false,
      policy: new iam.PolicyDocument({
        statements: [
          new iam.PolicyStatement({
            effect: iam.Effect.ALLOW,
            principals: [user],
            actions: [
              "kms:Create*",
              "kms:Describe*",
              "kms:Enable*",
              "kms:List*",
              "kms:Put*",
              "kms:Update*",
              "kms:Get*"
            ],
            resources: ["*"]
          })
        ]
      })
    });

    encryptionKey.addAlias(`alias/${id}-refresh-token-key`);
  }
}
```

**Comment by whummer** [comment]
Thanks for reporting @ShaunParsons . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!

**Comment by ShaunParsons** [comment]
Yep I can confirm this now works.
