### ISSUE TITLE
AWS::ApiGatewayV2::Authorizer: Parameter validation failed: Missing required parameter in input: "ApiId"

### ISSUE THREAD

**Issue by ShaunParsons** [localstack/localstack#3900]
# Type of request: This is a ...

- [x] bug report
- [ ] feature request

# Detailed description

Unable to add routes to an ApiGatewayV2 with Authorizer.

## Expected behavior

ApiGatewayV2 routed added with Authorizer

## Actual behavior

```bash
localstack_1             | 2021-04-20T18:29:14:DEBUG:localstack.services.cloudformation.service_models: Unable to fetch state for resource <localstack_ext.services.cloudformation.service_models.ApiGatewayV2Authorizer object at 0x7fed1ee35eb0>: Parameter validation failed:
localstack_1             | Missing required parameter in input: "ApiId"
localstack_1             | 2021-04-20T18:29:14:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: ApiGatewayV2::Authorizer Ref
localstack_1             | 2021-04-20T18:29:14:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected error retrieving details for resource AWS::ApiGatewayV2::Authorizer: Parameter validation failed:
localstack_1             | Missing required parameter in input: "ApiId"   File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
localstack_1             |     self._bootstrap_inner()
localstack_1             |   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
localstack_1             |     self.run()
localstack_1             |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/aws/aws_utils.py", line 85, in thread_run
localstack_1             |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 681, in run
localstack_1             |     result = self.func(self.params)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1936, in _run
localstack_1             |     self.do_apply_changes_in_loop(changes, stack, stack_name)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1977, in do_apply_changes_in_loop
localstack_1             |     should_deploy = self.prepare_should_deploy_change(
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2017, in prepare_should_deploy_change
localstack_1             |     resolve_refs_recursively(stack.stack_name, resource, new_resources)
localstack_1             |   File "/opt/code/localstack/localstack/utils/common.py", line 400, in func
localstack_1             |     return wrapped(*args, **kwargs)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 943, in resolve_refs_recursively
localstack_1             |     value[key] = resolve_refs_recursively(stack_name, val, resources)
localstack_1             |   File "/opt/code/localstack/localstack/utils/common.py", line 400, in func
localstack_1             |     return wrapped(*args, **kwargs)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 943, in resolve_refs_recursively
localstack_1             |     value[key] = resolve_refs_recursively(stack_name, val, resources)
localstack_1             |   File "/opt/code/localstack/localstack/utils/common.py", line 400, in func
localstack_1             |     return wrapped(*args, **kwargs)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 846, in resolve_refs_recursively
localstack_1             |     ref = resolve_ref(stack_name, value['Ref'], resources, attribute='Ref')
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 812, in resolve_ref
localstack_1             |     return determine_resource_physical_id(resource_id=ref,
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1500, in determine_resource_physical_id
localstack_1             |     result = extract_resource_attribute(resource_type, {}, attribute or 'PhysicalResourceId',
localstack_1             |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py", line 630, in extract_resource_attribute
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 659, in extract_resource_attribute
localstack_1             |     resource_state = retrieve_resource_details(resource_id, {}, resources, stack_name) or {}
localstack_1             |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py", line 384, in retrieve_resource_details
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 613, in retrieve_resource_details
localstack_1             |     state = instance.fetch_and_update_state(stack_name=stack_name, resources=resources)
localstack_1             |   File "/opt/code/localstack/localstack/services/cloudformation/service_models.py", line 121, in fetch_and_update_state
localstack_1             |     if not template_deployer.check_not_found_exception(e, self.resource_type, self.properties):
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 644, in check_not_found_exception
localstack_1             |     (resource_type, e, ''.join(traceback.format_stack()), resource, resource_status))
localstack_1             |  - {'ApiId': 'd7b630a1', 'AuthorizerType': 'JWT', 'IdentitySource': ['$request.header.Authorization'], 'Name': 'UserPoolAuthorizer', 'JwtConfiguration': {'Audience': ['jhjvtqpvwf6gftpljddy45urfc'], 'Issuer': 'https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_3beab2207d6d4ba28b106187aff81524'}} None
localstack_1             | 2021-04-20T18:29:14:DEBUG:localstack.services.cloudformation.service_models: Unable to fetch state for resource <localstack_ext.services.cloudformation.service_models.ApiGatewayV2Authorizer object at 0x7fed1e7addc0>: Parameter validation failed:
localstack_1             | Missing required parameter in input: "ApiId"
localstack_1             | 2021-04-20T18:29:14:DEBUG:localstack.utils.cloudformation.template_deployer: Dependencies for "testappapiGETprofileAD843515" not yet satisfied, retrying in next loop: Unable to fetch details for resource "testappapiGETprofileUserPoolAuthorizer3B35C8BC" (attribute "Ref")
localstack_1             | 2021-04-20T18:29:14:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "test": Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'testappapiGETprofileUserPoolAuthorizer3B35C8BC', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGatewayV2::Authorizer', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'testappapiGETprofileAD843515', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGatewayV2::Route', 'Replacement': 'False', 'ChangeSetId': None}}] Traceback (most recent call last):
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1936, in _run
localstack_1             |     self.do_apply_changes_in_loop(changes, stack, stack_name)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1997, in do_apply_changes_in_loop
localstack_1             |     raise Exception('Resource deployment loop completed, pending resource changes: %s' % changes)
localstack_1             | Exception: Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'testappapiGETprofileUserPoolAuthorizer3B35C8BC', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGatewayV2::Authorizer', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'testappapiGETprofileAD843515', 'PhysicalResourceId': None, 'ResourceType': 'AWS::ApiGatewayV2::Route', 'Replacement': 'False', 'ChangeSetId': None}}]

```

# Steps to reproduce

## Command used to start LocalStack

```bash
docker-compose up -d localstack
```

### docker-compose.yml

```yml
  localstack:
    image: 'localstack/localstack'
    ports:
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SERVICES=s3,sqs,rds,sns,cloudformation,ec2,iam,lambda,kms,cognito,apigatewayv2,secretsmanager,route53,apigateway
      - DEBUG=true
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
      - LOCALSTACK_HOSTNAME=localhost
      - HOSTNAME=localhost
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"


```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Stack definition:

```typescript
import * as cdk from "@aws-cdk/core";
import * as cognito from "@aws-cdk/aws-cognito";
import * as apigatewayv2 from "@aws-cdk/aws-apigatewayv2";
import * as apigatewayv2Authorizers from "@aws-cdk/aws-apigatewayv2-authorizers";
import * as apigatewayv2Integrations from "@aws-cdk/aws-apigatewayv2-integrations";
import * as lambda from "@aws-cdk/aws-lambda";
import * as lambdaNodeJs from "@aws-cdk/aws-lambda-nodejs";

export class TestStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const userPool = new cognito.UserPool(this, `${id}-user-pool`, {
      userPoolName: `${id}-user-pool`,
      autoVerify: {
        email: true,
        phone: false
      },
      signInAliases: {
        email: true,
        phone: false,
        username: false,
        preferredUsername: false
      }
    });

    const userPoolClient = new cognito.UserPoolClient(
      this,
      `${id}-user-pool-client`,
      {
        userPoolClientName: `${id}-user-pool-client`,
        userPool: userPool,
        generateSecret: false
      }
    );

    const httpApi = new apigatewayv2.HttpApi(this, `${id}-app-api`, {
      apiName: `${id}-app-api`,
      corsPreflight: {
        allowOrigins: ["*"],
        allowHeaders: [
          "content-type",
          "authorization",
          "x-amz-date",
          "x-api-key",
          "x-amz-security-token",
          "x-amz-user-agent"
        ],
        allowMethods: [
          apigatewayv2.CorsHttpMethod.GET,
          apigatewayv2.CorsHttpMethod.POST,
          apigatewayv2.CorsHttpMethod.PUT,
          apigatewayv2.CorsHttpMethod.DELETE,
          apigatewayv2.CorsHttpMethod.OPTIONS
        ]
      },
      defaultAuthorizer: new apigatewayv2Authorizers.HttpUserPoolAuthorizer({
        userPool: userPool,
        userPoolClient: userPoolClient,
        identitySource: ["$request.header.Authorization"]
      })
    });

    const handler = new lambdaNodeJs.NodejsFunction(this, `${id}-profile`, {
      functionName: `${id}-profile`,
      awsSdkConnectionReuse: true,
      handler: "read",
      entry: "services/api/routes/profile.js",
      memorySize: 128,
      bundling: {
        externalModules: ["pg-native"]
      },
      timeout: cdk.Duration.seconds(10),
      runtime: lambda.Runtime.NODEJS_12_X
    });

    const proxy = new apigatewayv2Integrations.LambdaProxyIntegration({
      handler
    });

    httpApi.addRoutes({
      integration: proxy,
      path: "/profile",
      methods: [apigatewayv2.HttpMethod.GET]
    });
  }
}

```

**Comment by whummer** [comment]
Thanks for reporting @ShaunParsons . This should be (hopefully) fixed in the meantime - please let us know if the problem persists in the `latest` Docker image. Thanks!
