### ISSUE TITLE
Can not deploy Lambda inside VPC

### ISSUE THREAD

**Issue by ShaunParsons** [localstack/localstack#3901]
# Type of request: This is a ...

- [x] bug report
- [ ] feature request

# Detailed description
I'm trying to deploy a lambda inside a VPC, but I'm getting the below error. I am able to deploy an RDS instance inside the VPC (commented out in the sample code, commenting that and removing the lambda should succeed)

## Expected behavior

Lambda deployed inside the VPC.

## Actual behavior

```bash
localstack_1             | 2021-04-20T19:20:40:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: EC2::SubnetRouteTableAssociation PhysicalResourceId
localstack_1             | 2021-04-20T19:20:40:DEBUG:localstack.utils.cloudformation.template_deployer: Dependencies for "vpcrdsSubnet2RouteTableAssociationA8E58271" not yet satisfied, retrying in next loop: Unable to fetch details for resource "vpcrdsSubnet2RouteTableAssociationA8E58271" (attribute "PhysicalResourceId")
localstack_1             | 2021-04-20T19:20:40:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "vpcrdsSubnet3RouteTableAssociation88A812D3" (9/9) type "AWS::EC2::SubnetRouteTableAssociation" in loop iteration 3
localstack_1             | 2021-04-20T19:20:40:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "EC2::SubnetRouteTableAssociation" id "vpcrdsSubnet3RouteTableAssociation88A812D3"
localstack_1             | 2021-04-20T19:20:40:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "EC2::SubnetRouteTableAssociation" in region eu-west-2: associate_route_table {'RouteTableId': 'rtb-db13b9f4', 'SubnetId': 'subnet-7df04052'}
localstack_1             | 2021-04-20T19:20:40:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: EC2::SubnetRouteTableAssociation PhysicalResourceId
localstack_1             | 2021-04-20T19:20:40:DEBUG:localstack.utils.cloudformation.template_deployer: Dependencies for "vpcrdsSubnet3RouteTableAssociation88A812D3" not yet satisfied, retrying in next loop: Unable to fetch details for resource "vpcrdsSubnet3RouteTableAssociation88A812D3" (attribute "PhysicalResourceId")
localstack_1             | 2021-04-20T19:20:40:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "test": Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcpublicSubnet1RouteTableAssociationB46101B8', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcpublicSubnet2RouteTableAssociation73F6478A', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcpublicSubnet3RouteTableAssociationF6210B68', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcapplicationSubnet1RouteTableAssociation5A0D1F15', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcapplicationSubnet2RouteTableAssociationA86DC03C', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcapplicationSubnet3RouteTableAssociationE6997878', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcrdsSubnet1RouteTableAssociation3E946461', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcrdsSubnet2RouteTableAssociationA8E58271', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcrdsSubnet3RouteTableAssociation88A812D3', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}] Traceback (most recent call last):
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1936, in _run
localstack_1             |     self.do_apply_changes_in_loop(changes, stack, stack_name)
localstack_1             |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1997, in do_apply_changes_in_loop
localstack_1             |     raise Exception('Resource deployment loop completed, pending resource changes: %s' % changes)
localstack_1             | Exception: Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcpublicSubnet1RouteTableAssociationB46101B8', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcpublicSubnet2RouteTableAssociation73F6478A', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcpublicSubnet3RouteTableAssociationF6210B68', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcapplicationSubnet1RouteTableAssociation5A0D1F15', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcapplicationSubnet2RouteTableAssociationA86DC03C', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcapplicationSubnet3RouteTableAssociationE6997878', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcrdsSubnet1RouteTableAssociation3E946461', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcrdsSubnet2RouteTableAssociationA8E58271', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'vpcrdsSubnet3RouteTableAssociation88A812D3', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::SubnetRouteTableAssociation', 'Replacement': 'False', 'ChangeSetId': None}}]

```

# Steps to reproduce

## Command used to start LocalStack

```bash
docker-compose up -d localstack
```

### docker-compose.yml

```yml
  localstack:
    image: 'localstack/localstack'
    ports:
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SERVICES=s3,sqs,rds,sns,cloudformation,ec2,iam,lambda,kms,cognito,apigatewayv2,secretsmanager,route53,apigateway
      - DEBUG=true
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
      - LOCALSTACK_HOSTNAME=localhost
      - HOSTNAME=localhost
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```typescript
import * as cdk from "@aws-cdk/core";
import * as lambda from "@aws-cdk/aws-lambda";
import * as lambdaNodeJs from "@aws-cdk/aws-lambda-nodejs";
import * as ec2 from "@aws-cdk/aws-ec2";
import * as rds from "@aws-cdk/aws-rds";

export class TestStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vpc = new ec2.Vpc(this, "vpc", {
      cidr: "10.0.0.0/16",
      maxAzs: 3,
      natGateways: 1,
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: "public",
          subnetType: ec2.SubnetType.PUBLIC
        },
        {
          cidrMask: 24,
          name: "application",
          subnetType: ec2.SubnetType.PRIVATE
        },
        {
          cidrMask: 24,
          name: "rds",
          subnetType: ec2.SubnetType.ISOLATED
        }
      ]
    });

    const applicationSecurityGroup = new ec2.SecurityGroup(
      this,
      `${id}-application-security-group`,
      {
        vpc: vpc,
        securityGroupName: `${id}-application-security-group`
      }
    );

    const databaseSecurityGroup = new ec2.SecurityGroup(
      this,
      `${id}-database-security-group`,
      {
        vpc: vpc,
        securityGroupName: `${id}-database-security-group`,
        allowAllOutbound: false
      }
    );

    databaseSecurityGroup.addIngressRule(
      applicationSecurityGroup,
      ec2.Port.tcp(5432)
    );

    /*
    // RDS
    const databaseUser = "db_user";
    const databaseName = "db_name";
    const database = new rds.DatabaseInstance(this, `${id}-database`, {
      allocatedStorage: 20,
      multiAz: false,
      backupRetention: cdk.Duration.days(1),
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.BURSTABLE3,
        ec2.InstanceSize.MICRO
      ),
      credentials: rds.Credentials.fromPassword(
        databaseUser,
        new cdk.SecretValue(process.env.DATABASE_PASSWORD)
      ),
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_12_5
      }),
      vpc: vpc,
      subnetGroup: new rds.SubnetGroup(this, `${id}-database-subnet-group`, {
        description: `${id}-database-subnet-group`,
        subnetGroupName: `${id}-database-subnet-group`,
        vpc: vpc,
        vpcSubnets: {
          subnetGroupName: "rds"
        }
      }),
      securityGroups: [databaseSecurityGroup]
    });
    */

    new lambdaNodeJs.NodejsFunction(this, `${id}-profile`, {
      functionName: `${id}-profile`,
      awsSdkConnectionReuse: true,
      handler: "read",
      entry: "services/api/routes/profile.js",
      memorySize: 128,
      bundling: {
        externalModules: ["pg-native"]
      },
      timeout: cdk.Duration.seconds(10),
      runtime: lambda.Runtime.NODEJS_12_X,
      vpc: vpc,
      vpcSubnets: {
        subnetGroupName: "application"
      },
      securityGroups: [applicationSecurityGroup]
    });
  }
}
```

**Comment by whummer** [comment]
Thanks for reporting @ShaunParsons . This should (hopefully) be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please keep us posted how it goes. Thanks for your help!

**Comment by ShaunParsons** [comment]
Thanks. I can confirm thats resolved.
