### ISSUE TITLE
Error invoking docker container lambda function 

### ISSUE THREAD

**Issue by cbellinz** [localstack/localstack#3903]
# Type of request: This is a ...

[*] bug report
[ ] feature request

# Detailed description

This pertains to:

Localstack Pro 
LocalStack build date: 2021-04-20
LocalStack build git hash: de598454

Goal: Use Localstack to host a lambda function that uses a docker container as execution environment

I have successfully done the following:

1. Uploaded docker container to Localstack ECR using aws cli commands.
2. Created a lambda function that uses this container using serverless

I can see the function as follows:

```
{
    "Functions": [
        {
            "FunctionName": "xxx-lambda-local-1",
            "FunctionArn": "arn:aws:lambda:eu-west-1:000000000000:function:xxx-lambda-local-1",
            "Role": "arn:aws:iam::000000000000:role/xxx-lambda-exec-role-1",
            "Handler": "handler.handler",
            "Description": "",
            "Timeout": 60,
            "MemorySize": 1024,
            "LastModified": "2021-04-20T15:56:40.340+0000",
            "Version": "$LATEST",
            "VpcConfig": {},
            "TracingConfig": {
                "Mode": "PassThrough"
            },
            "RevisionId": "6e5d3b70-7567-40de-9087-8403ec3dffbe",
            "Layers": [],
            "State": "Active",
            "LastUpdateStatus": "Successful"
        }
    ]
}

```
It should be noted that the same process has been proven to work on AWS with the function working successfully.

On Localstack, when i invoke the function using boto3, as below i get an error.

Invoke code:

```
response = client.invoke(
  FunctionName='xxx-lambda-local-1',
  LogType='Tail',
  InvocationType='RequestResponse',
  Payload=json.dumps(message).encode('utf-8'),
  Qualifier='$LATEST'
)
```

...

## Expected behavior

The function executes and returns response
...

## Actual behavior

The error seen is:

```
localstack_1                   | 2021-04-20T18:30:07:INFO:localstack.services.awslambda.lambda_executors: Error executing Lambda "arn:aws:lambda:eu-west-1:000000000000:function:xxx-lambda-local-1": 'NoneType' object is not callable   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 780, in _execute
localstack_1                   |     process.run()
localstack_1                   |   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
localstack_1                   |     self._target(*self._args, **self._kwargs)
localstack_1                   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 766, in do_execute
localstack_1                   |     result = lambda_function(event, context)
localstack_1                   |
localstack_1                   | 2021-04-20T18:30:07:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:eu-west-1:000000000000:function:xxx-lambda-local-1: 'NoneType' object is not callable Traceback (most recent call last):
localstack_1                   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 587, in run_lambda
localstack_1                   |     result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
localstack_1                   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 176, in execute
localstack_1                   |     return do_execute()
localstack_1                   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 168, in do_execute
localstack_1                   |     return _run(func_arn=func_arn)
localstack_1                   |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
localstack_1                   |     raise e
localstack_1                   |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 145, in wrapped
localstack_1                   |     result = func(*args, **kwargs)
localstack_1                   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 159, in _run
localstack_1                   |     raise e
localstack_1                   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 147, in _run
localstack_1                   |     result = self._execute(func_arn, func_details, event, context, version)
localstack_1                   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 804, in _execute
localstack_1                   |     raise InvocationException(result, log_output)
localstack_1                   | localstack.services.awslambda.lambda_executors.InvocationException: 'NoneType' object is not callable
```
...

# Steps to reproduce

1. Create a docker container that supports lambda use
2. Upload to ECR repository on Localstack using standard CLI commands
3. Create function on Localstack that uses this container using serverless framework. I can post an example of this if required.
4. Invoke the function from boto3

## Command used to start LocalStack

Docker compose:

```
services:
  localstack:
    image: localstack/localstack
    ports:
      - "8080:8080"
      - "4566:4566"
      - "4510:4510"
    environment:
      - LOCALSTACK_API_KEY=123456
      - DEFAULT_REGION=eu-west-1
      - HOSTNAME_EXTERNAL=aws.xxx.local
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - LAMBDA_REMOTE_DOCKER=0
      - SERVICES="edge,serverless,kms,secretsmanager,s3,ecr,cloudformation,cloudwatch,sts,logs,sqs,ssm,events"
      - LAMBDA_EXECUTOR=local
    volumes:
      - "${PWD}/localstack/tmp:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - inzura-docker-dev
```

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

To be updated if necessary as many moving parts with serverless involved etc.
...

**Comment by whummer** [comment]
Thanks for reporting @cbellinz . Can you please try commenting out this line:
```
# - LAMBDA_EXECUTOR=local
```
This should (hopefully) fix the issue you're seeing. We'll push a change to fix this bug shortly. Thanks

**Comment by whummer** [comment]
Hi again @cbellinz . This should (hopefully) be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please keep us posted how it goes. Thanks for your help!
