### ISSUE TITLE
Service not yet available errors

### ISSUE THREAD

**Issue by mingrammer** [localstack/localstack#393]
I've got following errors when had been ran `DEBUG=1 HOSTNAME=localstackhost DEFAULT_REGION=ap-northeast-2 SERVICES=kinesis,es,lambda,s3,ses localstack start --docker` command. (I installed it with pip.)

```
Starting local dev environment. CTRL-C to quit.
docker run -it -e SERVICES="kinesis,es,lambda,s3,ses" -e HOSTNAME="localstackhost" -e LOCALSTACK_HOSTNAME="localstackhost" -e DEBUG="1" -p 8080:8080  -p 4568:4568 -p 4578:4578 -p 4574:4574 -p 4572:4572 -p 4579:4579 -p 4571:4571 -v "/private/var/folders/ct/ktjbwstj1gjd_qcj8sb7rltm0000gn/T/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/private/var/folders/ct/ktjbwstj1gjd_qcj8sb7rltm0000gn/T/localstack" "localstack/localstack"
Unable to find image 'localstack/localstack:latest' locally
latest: Pulling from localstack/localstack
a27b82f559a7: Pulling fs layer
0a8dd813c5b6: Pulling fs layer
0a8dd813c5b6: Verifying Checksum
0a8dd813c5b6: Download complete
a27b82f559a7: Verifying Checksum
a27b82f559a7: Download complete
a27b82f559a7: Pull complete
0a8dd813c5b6: Pull complete
Digest: sha256:642e21f53c8d330e62f4eb4b29b6b7fab80d4431597e8f60a230da138e948c4c
Status: Downloaded newer image for localstack/localstack:latest
2017-10-10 15:03:52,344 CRIT Supervisor running as root (no user in config file)
2017-10-10 15:03:52,346 INFO supervisord started with pid 1
2017-10-10 15:03:53,348 INFO spawned: 'dashboard' with pid 7
2017-10-10 15:03:53,350 INFO spawned: 'infra' with pid 8
(. .venv/bin/activate; exec bin/localstack start)
(. .venv/bin/activate; bin/localstack web)
Starting local dev environment. CTRL-C to quit.
2017-10-10T15:03:54:INFO:werkzeug:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
2017-10-10T15:03:54:INFO:werkzeug:  * Restarting with stat
2017-10-10T15:03:54:WARNING:werkzeug:  * Debugger is active!
2017-10-10 15:03:54,415 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-10-10 15:03:54,415 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-10-10T15:03:54:INFO:werkzeug:  * Debugger PIN: 324-739-655
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock S3 (http port 4572)...
Starting local Elasticsearch (http port 4571)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
Listening at http://:::4565
* Running on http://0.0.0.0:4579/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4563/ (Press CTRL+C to quit)
[2017-10-10T15:03:58,850][INFO ][o.e.n.Node               ] [] initializing ...
[2017-10-10T15:03:58,989][INFO ][o.e.e.NodeEnvironment    ] [hCzsQ8n] using [1] data paths, mounts [[/ (none)]], net usable_space [15.8gb], net total_space [17.8gb], spins? [possibly], types [aufs]
[2017-10-10T15:03:58,992][INFO ][o.e.e.NodeEnvironment    ] [hCzsQ8n] heap size [491.6mb], compressed ordinary object pointers [true]
[2017-10-10T15:03:58,995][INFO ][o.e.n.Node               ] node name [hCzsQ8n] derived from node ID [hCzsQ8nbQnyha-q-KhpuUA]; set [node.name] to override
[2017-10-10T15:03:58,996][INFO ][o.e.n.Node               ] version[5.3.0], pid[70], build[3adb13b/2017-03-23T03:31:50.652Z], OS[Linux/4.4.89-boot2docker/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b11]
[2017-10-10T15:04:00,576][INFO ][o.e.p.PluginsService     ] [hCzsQ8n] loaded module [aggs-matrix-stats]
[2017-10-10T15:04:00,577][INFO ][o.e.p.PluginsService     ] [hCzsQ8n] loaded module [ingest-common]
[2017-10-10T15:04:00,578][INFO ][o.e.p.PluginsService     ] [hCzsQ8n] loaded module [lang-expression]
[2017-10-10T15:04:00,578][INFO ][o.e.p.PluginsService     ] [hCzsQ8n] loaded module [lang-groovy]
[2017-10-10T15:04:00,578][INFO ][o.e.p.PluginsService     ] [hCzsQ8n] loaded module [lang-mustache]
[2017-10-10T15:04:00,579][INFO ][o.e.p.PluginsService     ] [hCzsQ8n] loaded module [lang-painless]
[2017-10-10T15:04:00,579][INFO ][o.e.p.PluginsService     ] [hCzsQ8n] loaded module [percolator]
[2017-10-10T15:04:00,579][INFO ][o.e.p.PluginsService     ] [hCzsQ8n] loaded module [reindex]
[2017-10-10T15:04:00,580][INFO ][o.e.p.PluginsService     ] [hCzsQ8n] loaded module [transport-netty3]
[2017-10-10T15:04:00,581][INFO ][o.e.p.PluginsService     ] [hCzsQ8n] loaded module [transport-netty4]
[2017-10-10T15:04:00,582][INFO ][o.e.p.PluginsService     ] [hCzsQ8n] no plugins loaded
[2017-10-10T15:04:04,322][INFO ][o.e.n.Node               ] initialized
[2017-10-10T15:04:04,328][INFO ][o.e.n.Node               ] [hCzsQ8n] starting ...
[2017-10-10T15:04:04,464][WARN ][i.n.u.i.MacAddressUtil   ] Failed to find a usable hardware address from the network interfaces; using random bytes: 7e:86:f0:2a:b9:39:f8:0e
[2017-10-10T15:04:04,577][INFO ][o.e.t.TransportService   ] [hCzsQ8n] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
[2017-10-10T15:04:04,593][WARN ][o.e.b.BootstrapChecks    ] [hCzsQ8n] initial heap size [209715200] not equal to maximum heap size [524288000]; this can cause resize pauses and prevents mlockall from locking the entire heap
[2017-10-10T15:04:04,594][WARN ][o.e.b.BootstrapChecks    ] [hCzsQ8n] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2017-10-10T15:04:07,691][INFO ][o.e.c.s.ClusterService   ] [hCzsQ8n] new_master {hCzsQ8n}{hCzsQ8nbQnyha-q-KhpuUA}{F_0GCg_RT8WIZtzR2Fou0A}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-10-10T15:04:07,749][INFO ][o.e.h.n.Netty4HttpServerTransport] [hCzsQ8n] publish_address {127.0.0.1:4560}, bound_addresses {127.0.0.1:4560}
[2017-10-10T15:04:07,755][INFO ][o.e.n.Node               ] [hCzsQ8n] started
[2017-10-10T15:04:07,756][INFO ][o.e.g.GatewayService     ] [hCzsQ8n] recovered [0] indices into cluster_state
2017-10-10T15:04:09:WARNING:infra.pyc: Service "kinesis" not yet available, retrying...
2017-10-10T15:04:20:WARNING:infra.pyc: Service "kinesis" not yet available, retrying...
2017-10-10T15:04:27:WARNING:infra.pyc: Service "kinesis" not yet available, retrying...
2017-10-10T15:04:33:WARNING:infra.pyc: Service "kinesis" not yet available, retrying...
2017-10-10T15:04:39:WARNING:infra.pyc: Service "kinesis" not yet available, retrying...
2017-10-10T15:04:49:WARNING:infra.pyc: Service "kinesis" not yet available, retrying...
2017-10-10T15:04:55:WARNING:infra.pyc: Service "kinesis" not yet available, retrying...
2017-10-10T15:05:07:WARNING:infra.pyc: Service "kinesis" not yet available, retrying...
2017-10-10T15:05:19:ERROR:localstack.services.kinesis.kinesis_starter: Kinesis health check failed: Could not connect to the endpoint URL: "http://localstackhost:4568/" Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 33, in check_kinesis
out = aws_stack.connect_to_service(service_name='kinesis').list_streams()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 586, in _make_api_call
operation_model, request_dict)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
return self._send_request(request_dict, operation_model)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 170, in _send_request
success_response, exception):
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/endpoint.py", line 249, in _needs_retry
caught_exception=caught_exception, request_dict=request_dict)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
return self._emit(event_name, kwargs)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
response = handler(**kwargs)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
if self._checker(attempts, response, caught_exception):
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
caught_exception)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
return self._checker(attempt_number, response, caught_exception)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
caught_exception)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
attempt_number, caught_exception)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "http://localstackhost:4568/"

2017-10-10T15:05:19:WARNING:infra.pyc: Service "kinesis" not yet available, retrying...
2017-10-10T15:05:19:ERROR:infra.pyc: Error checking state of local environment (after some retries): Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/infra.py", line 344, in check_infra
raise e
TypeError: 'NoneType' object has no attribute '__getitem__'

Error starting infrastructure: 'NoneType' object has no attribute '__getitem__' Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/infra.py", line 481, in start_infra
check_infra(apis=apis)
File "/opt/code/localstack/localstack/services/infra.py", line 353, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 353, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 353, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 353, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 353, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 353, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 353, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 353, in check_infra
check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
File "/opt/code/localstack/localstack/services/infra.py", line 351, in check_infra
raise e
TypeError: 'NoneType' object has no attribute '__getitem__'

Killed
Killed
Killed
Killed
...
```

I can't resolve it even if re-create the docker instance and re-run the above command. 

How can I solve it?

**Comment by whummer** [comment]
Thanks for reporting @mingrammer . If you remove the `HOSTNAME=localstackhost` then it should work. Are you trying to achieve something specific with regards to the `localstackhost` host name?

**Comment by mingrammer** [comment]
No I don't have. And It works when removed the `HOSTNAME` variable.

But, I want to change the `HOSTNAME` to other than `localhost`, Can't I do this now? Is it a bug?

**Comment by RosenPIvanov** [comment]
Hello, 

I am using windows 10 (do not ask why), latest docker, docker toolbox. When I try just to run I got the same error. For me the resolution with removing the host is not working. I tried both python 3.6 and python 2.7.

Any ideas how to use this product?

**Comment by saadbinakhlaq** [comment]
I am kind of facing a similar issue, my use case is to connect to dynamodb through lambda, but there is connection issue
```
Error raised from handler method
{
"errorMessage": "Failed to open TCP connection to localhost:4569 (Cannot assign requested address - connect(2) for \"localhost\" port 4569)",
"errorType": "Function<Errno::EADDRNOTAVAIL>",
"stackTrace": [
```

so I have tried LOCALSTACK_HOSTNAME but then I am getting this error like dynamodb is not yet available.

**Comment by usmanovbf** [comment]
Same error when I am trying to execute JUnit tests
`фев 04, 2019 2:49:24 PM cloud.localstack.Localstack setupInfrastructure
INFO: /var/folders/hw/xb511sv57ql39b2st3vh66jh0000gn/T//localstack_install_dir
фев 04, 2019 2:49:24 PM cloud.localstack.Localstack setupInfrastructure
INFO: Waiting for infrastructure to be spun up
java.lang.RuntimeException: Unable to start local infrastructure. Debug output: (. .venv/bin/activate; exec bin/localstack start)
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock DynamoDB (http port 4569)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudWatch (http port 4582)...
Starting mock CloudFormation (http port 4581)...
Starting mock SSM (http port 4583)...
Starting mock SQS (http port 4576)...
Starting mock Secrets Manager (http port 4584)...
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
Error starting infrastructure: 'NoneType' object has no attribute '__getitem__' Traceback (most recent call last):
  File "/private/var/folders/hw/xb511sv57ql39b2st3vh66jh0000gn/T/localstack_install_dir/localstack/services/infra.py", line 487, in start_infra
    check_infra(apis=apis)
  File "/private/var/folders/hw/xb511sv57ql39b2st3vh66jh0000gn/T/localstack_install_dir/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/private/var/folders/hw/xb511sv57ql39b2st3vh66jh0000gn/T/localstack_install_dir/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/private/var/folders/hw/xb511sv57ql39b2st3vh66jh0000gn/T/localstack_install_dir/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/private/var/folders/hw/xb511sv57ql39b2st3vh66jh0000gn/T/localstack_install_dir/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/private/var/folders/hw/xb511sv57ql39b2st3vh66jh0000gn/T/localstack_install_dir/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/private/var/folders/hw/xb511sv57ql39b2st3vh66jh0000gn/T/localstack_install_dir/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/private/var/folders/hw/xb511sv57ql39b2st3vh66jh0000gn/T/localstack_install_dir/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/private/var/folders/hw/xb511sv57ql39b2st3vh66jh0000gn/T/localstack_install_dir/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/private/var/folders/hw/xb511sv57ql39b2st3vh66jh0000gn/T/localstack_install_dir/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/private/var/folders/hw/xb511sv57ql39b2st3vh66jh0000gn/T/localstack_install_dir/localstack/services/infra.py", line 358, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/private/var/folders/hw/xb511sv57ql39b2st3vh66jh0000gn/T/localstack_install_dir/localstack/services/infra.py", line 356, in check_infra
    raise e
TypeError: 'NoneType' object has no attribute '__getitem__'

ERROR: 'NoneType' object has no attribute '__getitem__'

	at cloud.localstack.Localstack.setupInfrastructure(Localstack.java:277)
	at cloud.localstack.LocalstackTestRunner.run(LocalstackTestRunner.java:24)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)`

**Comment by anjit181996** [comment]
Waiting for all LocalStack services to be ready
localstack_1  | 2019-03-08T02:00:47:WARNING:infra.pyc: Service "s3" not yet available, retrying...
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2019-03-08T02:00:56:WARNING:infra.pyc: Service "s3" not yet available, retrying...
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2019-03-08T02:01:04:ERROR:localstack.services.s3.s3_starter: S3 health check failed:  Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 14, in check_s3
localstack_1  |     wait_for_port_open(DEFAULT_PORT_S3_BACKEND)
localstack_1  |   File "/opt/code/localstack/localstack/utils/common.py", line 365, in wait_for_port_open
localstack_1  |     return retry(check, sleep=sleep_time, retries=retries)
localstack_1  |   File "/opt/code/localstack/localstack/utils/common.py", line 390, in retry
localstack_1  |     raise raise_error
localstack_1  | Exception
localstack_1  |


I am getting this error.　can somebody help me?

**Comment by whummer** [comment]
Can we please confirm that the problem still persists with the `latest` version of the code?

@usmanovbf 
You may have to delete `/private/var/folders/hw/xb511sv57ql39b2st3vh66jh0000gn/T/localstack_install_dir` and then re-run the test..


@anjit181996 Please try `docker pull localstack/localstack` and then run `docker-compose up` again. It can take a couple of seconds until the full stack becomes available. Does it work?

**Comment by whummer** [comment]
Closing this issue, as the issues reported by @usmanovbf and @anjit181996 don't seem to be related to the original issue reported by @mingrammer . Please create follow-up issues as needed.
