### ISSUE TITLE
s3api put-bucket-notification-configuration does not add filters

### ISSUE THREAD

**Issue by nsalhaji** [localstack/localstack#396]
Hi guys,

Localstack does not add filters while configuring S3 bucket Events for QueueConfiguration.

### Commands I'm using:
```
awslocal sqs create-queue --queue-name devInventoryLoaderEvents
awslocal s3api create-bucket --bucket dev-inventory-loader 
awslocal s3api put-bucket-notification-configuration --bucket dev-inventory-loader --notification-configuration file://s3_notif.json
```

### Content of s3_notif.json:

```
{
   "QueueConfigurations":[
      {
         "Id":"S3EventsSQSNotification",
         "QueueArn":"arn:aws:sqs:us-east-1:queue:devInventoryLoaderEvents",
         "Events":[
            "s3:ObjectCreated:*"
         ],
         "Filter":{
            "Key":{
               "FilterRules":[
                  {
                     "Name":"prefix",
                     "Value":"workspace/"
                  }
              ]
            }
         }
      }
   ]
}
```

### And when I run:
`awslocal s3api get-bucket-notification-configuration --bucket dev-inventory-loader`
I got:

```
{
    "QueueConfigurations": [
        {
            "Id": "50468ed6-2f66-44c2-91ad-a683782eee1b",
            "QueueArn": "arn:aws:sqs:us-east-1:queue:devInventoryLoaderEvents",
            "Events": [
                "s",
                "3",
                ":",
                "O",
                "b",
                "j",
                "e",
                "c",
                "t",
                "C",
                "r",
                "e",
                "a",
                "t",
                "e",
                "d",
                ":",
                "*"
            ]
        }
    ]
}
```
### and when I try to add object to my bucket:
`awslocal s3api put-object --bucket dev-inventory-loader --key workspace/my_file.txt --body my_file.txt`

I got this error:

```
2017-10-10T10:58:34:ERROR:localstack.services.generic_proxy: Error forwarding request: string indices must be integers Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/localstack/services/generic_proxy.py", line 194, in forward
    path=path, data=data, headers=forward_headers, response=response)
  File "/usr/local/lib/python3.6/site-packages/localstack/services/s3/s3_listener.py", line 436, in return_response
    send_notifications(method, bucket_name, object_path)
  File "/usr/local/lib/python3.6/site-packages/localstack/services/s3/s3_listener.py", line 122, in send_notifications
    filter_rules_match(config.get('Filter'), object_path)):
  File "/usr/local/lib/python3.6/site-packages/localstack/services/s3/s3_listener.py", line 50, in filter_rules_match
    if rule['Name'] == 'prefix':
TypeError: string indices must be integers
```

**I use the last version of localstack (0.8.1).**

Thanks.

**Comment by whummer** [comment]
Thanks for reporting @nsalhaji , this should be fixed in #419. Closing this issue now, please re-open if the problem persists. Thanks

**Comment by nsalhaji** [comment]
Hi @whummer,

I've checkout master and I tested the fix:

Unfortunatly, the issue persist. Filters aren't added while configuring S3 bucket Events for QueueConfiguration.

Thanks.

**Comment by whummer** [comment]
Ah, that was an oversight @nsalhaji , fixed in cb19434b12bc5cefc65f64505b1f824332b5d53e . I'm re-opening this one - please confirm and close the ticket. Thanks

**Comment by nsalhaji** [comment]
Hi @whummer,

With this fix cb19434 filters are correctly saved and added to S3 Bucket Config. Good job guys. Many thanks.

But I still have error when I try to add object to bucket :-(

**Used command:**
`awslocal s3api put-object --bucket dev-inventory-loader --key workspace/my_file.txt --body my_file.txt`

**Error:**
```
2017-10-25T11:01:51:ERROR:localstack.services.generic_proxy: Error forwarding request: string indices must be integers Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/localstack/services/generic_proxy.py", line 194, in forward
    path=path, data=data, headers=forward_headers, response=response)
  File "/usr/local/lib/python3.6/site-packages/localstack/services/s3/s3_listener.py", line 441, in return_response
    send_notifications(method, bucket_name, object_path)
  File "/usr/local/lib/python3.6/site-packages/localstack/services/s3/s3_listener.py", line 122, in send_notifications
    filter_rules_match(config.get('Filter'), object_path)):
  File "/usr/local/lib/python3.6/site-packages/localstack/services/s3/s3_listener.py", line 50, in filter_rules_match
    if rule['Name'] == 'prefix':
TypeError: string indices must be integers
```

I described in my previous comments how to reproduce it.

Thanks.

**Comment by nsalhaji** [comment]
Hi guys,

After some tests I've got why I had this error. It happens when Filter contains one FilterRules.

```
{
   "QueueConfigurations":[
      {
         "Id":"S3EventsSQSNotification",
         "QueueArn":"arn:aws:sqs:us-east-1:queue:devInventoryLoaderEvents",
         "Events":[
            "s3:ObjectCreated:*"
         ],
         "Filter":{
            "Key":{
               "FilterRules":[
                  {
                     "Name":"prefix",
                     "Value":"workspace"
                  }
             ]
            }
         }
      }
   ]
}
```
When I update my configuration like that, all works fine.

```
{
   "QueueConfigurations":[
      {
         "Id":"S3EventsSQSNotification",
         "QueueArn":"arn:aws:sqs:us-east-1:queue:devInventoryLoaderEvents",
         "Events":[
            "s3:ObjectCreated:*"
         ],
         "Filter":{
            "Key":{
               "FilterRules":[
                  {
                     "Name":"prefix",
                     "Value":"workspace"
                  }, {
                    "Name":"prefix",
                    "Value":"workspace"
                 }
             ]
            }
         }
      }
   ]
}

```

I think, this ticket #276 needs some work.

Thanks guys.

**Comment by whummer** [comment]
@nsalhaji The issue with a single filter rule should now be fixed (#431). The integration tests have been extended to cover this feature. Please confirm that it works for you now.

**Comment by nsalhaji** [comment]
Hi @whummer,

It works for me.
Can I ask when the next release 0.8.2 will be published ?

Many thanks.

**Comment by whummer** [comment]
Thanks for confirming. I'll try to publish a release later today.

**Comment by nsalhaji** [comment]
Awesome. many thanks.
