### ISSUE TITLE
S3 Put Life Cycle Policy fails so bucket creation fails with terraform

### ISSUE THREAD

**Issue by synfinatic** [localstack/localstack#3963]
# Type of request: This is a ...

[ X] bug report
[ ] feature request

# Detailed description

Unable to create an S3 Life Cycle policy via terraform which results in the bucket failing to be created.  To be clear, this works fine via the `aws` cli tool, but fails with terraform, because it appears that terraform is using the alternative API endpoint from what I can tell in the localstack logs:

Example terraform error:
```
Error: Error putting S3 lifecycle: timeout while waiting for state to become 'success' (timeout: 2m0s)
```

Example localstack_infra.err error:
```
2021-05-04T22:28:49:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request PUT http://example-s3-bucket.localhost:4566/?lifecycle=: Parameter validation failed:
Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0
-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-
]{1,63}$" Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 129, in index
    raise result
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 689, in run
    result = self.func(self.params)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 352, in handler
    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 171, in modify_and_forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/edge.py", line 118, in forward_request
    return do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 137, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 157, in do_forward_request_inmem
    response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 171, in modify_and_forward
    listener_result = listener.forward_request(method=method,
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1094, in forward_request
    return set_lifecycle(bucket_name, data)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 679, in set_lifecycle
    exists, code, body = is_bucket_available(bucket_name)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 744, in is_bucket_available
    exists, code = bucket_exists(bucket_name)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 765, in bucket_exists
    s3_client.head_bucket(Bucket=bucket_name)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 648, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 694, in _convert_to_request_dict
    api_params = self._emit_api_params(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 723, in _emit_api_params
    self.meta.events.emit(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/handlers.py", line 236, in validate_bucket_name
    raise ParamValidationError(report=error_msg)
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0
-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-
]{1,63}$"
```

basic terraform code, you may need to edit a bit?
```
resource "aws_s3_bucket" "this" {
  bucket = "example-s3-bucket"

   versioning {
    enabled = true
  }

  lifecycle_rule {
    id      = "Server Access Logs Lifecycle rule"
    enabled = true

    abort_incomplete_multipart_upload_days = 7

    expiration {
      days = 1
    }
    noncurrent_version_expiration {
      days = 1
    }
  }
}

```

## Expected behavior

create s3 bucket with a life cycle policy just like with the `aws` cli tool.

## Actual behavior

put s3 life cycle policy fails with terraform 

# Steps to reproduce

## Command used to start LocalStack

```
docker run -d --name baseline --rm --mount type=bind,src=$(pwd)/localstack,dst=/tmp/localstack/data -p4566:4566 --env DATA_DIR=/tmp/localstack/data localstack/localstack:latest
```

**Comment by usmangani1** [comment]
@synfinatic  Thanks for reporting this issue. Can you please let us know which version of local stack you are using ?

We tried to reproduce this on current version of local stack but this doesn't throw any errors.

usman@ugLocalstack % terraform apply -auto-approve
```
aws_s3_bucket.this: Refreshing state... [id=example-s3-bucket]

aws_s3_bucket.this: Creating...
aws_s3_bucket.this: Creation complete after 0s [id=example-s3-bucket]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
usman@ugLocalstack % awslocal s3api list-buckets
```
{
    "Buckets": [
        {
            "Name": "example-s3-bucket",
            "CreationDate": "2021-05-05T18:12:00+00:00"
        }
    ],
    "Owner": {
        "DisplayName": "webfile",
        "ID": "bcaf1ffd86f41161ca5fb16fd081034f"
    }
}
```
usman@ugLocalstack % awslocal s3api get-bucket-lifecycle --bucket example-s3-bucket
```
{
    "Rules": [
        {
            "Expiration": {
                "Days": 1
            },
            "ID": "Server Access Logs Lifecycle rule",
            "Status": "Enabled",
            "NoncurrentVersionExpiration": {
                "NoncurrentDays": 1
            },
            "AbortIncompleteMultipartUpload": {
                "DaysAfterInitiation": 7
            }
        }
    ]
}
```

Can you please try this on the latest version and update here if issue persists ?

**Comment by synfinatic** [comment]
```
$  docker image ls
REPOSITORY                                   TAG           IMAGE ID       CREATED        SIZE
localstack/localstack                        latest        49a9bd72e268   21 hours ago   684MB
```

**Comment by usmangani1** [comment]
Sure that should help, Also which version of terraform are you using ?

**Comment by synfinatic** [comment]
tracked down the problem.  need to set:

```
provider "aws" {
   s3_force_path_style         = true
}
```

which [is documented](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/custom-service-endpoints#localstack) but wasn't set for this project.

anyways, might be useful to add a note to the log message?

**Comment by usmangani1** [comment]
Sure, The setting is required on terraform's end we can add that as a warning.

**Comment by synfinatic** [comment]
FYI for anyone reading this- you have to set the same flag in the AWS Go SDK or you will get the same error.
