### ISSUE TITLE
Creating an IoT topic rule with Terraform crashes

### ISSUE THREAD

**Issue by j-sv** [localstack/localstack#3966]
# Type of request: This is a ...

[*] bug report
[ ] feature request

# Detailed description

Creating an IoT topic rule with an SQS target using Terraform makes the AWS provider segfault

## Expected behavior

The topic rule is created.

## Actual behavior

The AWS provider segfaults and prints this stack trace:
```
Stack trace from the terraform-provider-aws_v3.36.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x499edbd]

goroutine 199 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsIotTopicRuleRead(0xc0001a3280, 0x5d93800, 0xc000452680, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_iot_topic_rule.go:1118 +0x33d
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsIotTopicRuleCreate(0xc0001a3280, 0x5d93800, 0xc000452680, 0x1, 0xffffffffffffffff)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_iot_topic_rule.go:1100 +0x330
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00095afc0, 0x757e148, 0xc001141540, 0xc0001a3280, 0x5d93800, 0xc000452680, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00095afc0, 0x757e148, 0xc001141540, 0xc00256ad90, 0xc000e701a0, 0x5d93800, 0xc000452680, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000304738, 0x757e148, 0xc001141540, 0xc0000b60a0, 0xc001141540, 0x68ce5a0, 0xc0013c9600)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc001cc19c0, 0x757e1f0, 0xc001141540, 0xc00256ac40, 0xc001cc19c0, 0xc0013c9650, 0xc00111cba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x68ce5a0, 0xc001cc19c0, 0x757e1f0, 0xc0013c9650, 0xc001595c20, 0x0, 0x757e1f0, 0xc0013c9650, 0xc001166700, 0x6b8)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000239500, 0x759e078, 0xc001112480, 0xc00115e100, 0xc00110aae0, 0xaa22400, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000239500, 0x759e078, 0xc001112480, 0xc00115e100, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000e0c160, 0xc000239500, 0x759e078, 0xc001112480, 0xc00115e100)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.36.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

It seems to segfault [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_iot_topic_rule.go#L1100), which would indicate that `ruleName` isn't available.

Running `awslocal` to list created rules returns this:
```
awslocal iot list-topic-rules
{
    "rules": [
        {
            "ruleDisabled": false
        }
    ]
}
```

Which should explain why the `ruleName` is unset.

# Steps to reproduce

## Command used to start LocalStack

```
docker run --rm -it -e SERVICES=sqs,iot,iam -e DEBUG=1 -e LS_LOG=debug -e LOCALSTACK_API_KEY=xxx -p 4566:4566 localstack/localstack:0.12.10
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Minimal Terraform code
```terraform
provider "aws" {
  region                      = "us-east-1"
  access_key                  = "0"
  secret_key                  = "0"
  s3_force_path_style         = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    iam            = "http://localhost:4566"
    iot            = "http://localhost:4566"
    sqs            = "http://localhost:4566"
  }
}

resource "aws_sqs_queue" "sqs_queue" {
  name = "the-queue"
}

resource "aws_iam_role" "iot_rule_role" {
  name_prefix        = "iot-rule-action-role-"
  assume_role_policy = data.aws_iam_policy_document.assume_role_policy.json
}

data "aws_iam_policy_document" "assume_role_policy" {
  version = "2012-10-17"
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["iot.amazonaws.com"]
    }
  }
}

data "aws_iam_policy_document" "rule_action_policy_document" {
  version = "2012-10-17"
  statement {
    effect  = "Allow"
    actions = ["sqs:SendMessage*"]
    resources = [
      aws_sqs_queue.sqs_queue.arn
    ]
  }
}

resource "aws_iam_role_policy" "rule_action_policy" {
  name_prefix = "rule-action-policy-"
  role        = aws_iam_role.iot_rule_role.id

  policy = data.aws_iam_policy_document.rule_action_policy_document.json
}

resource "aws_iot_topic_rule" "rule" {
  name        = "iot_topic_rule"
  enabled     = true
  sql         = <<EOF
    SELECT
        floor(timestamp() / 1E3) AS timestamp
    FROM 'tm/+/+/+/+'
  EOF
  sql_version = "2016-03-23"

  sqs {
    queue_url  = aws_sqs_queue.sqs_queue.id
    role_arn   = aws_iam_role.iot_rule_role.arn
    use_base64 = true
  }
}
```

```
$ terraform apply --auto-approve
aws_sqs_queue.sqs_queue: Creating...
aws_iam_role.iot_rule_role: Creating...
aws_sqs_queue.sqs_queue: Creation complete after 0s [id=http://localhost:4566/000000000000/the-queue]
data.aws_iam_policy_document.rule_action_policy_document: Reading...
data.aws_iam_policy_document.rule_action_policy_document: Read complete after 0s [id=123194672]
aws_iam_role.iot_rule_role: Creation complete after 0s [id=iot-rule-action-role-20210505092540912400000001]
aws_iam_role_policy.rule_action_policy: Creating...
aws_iot_topic_rule.rule: Creating...
╷
│ Error: Plugin did not respond
│
│   with aws_iam_role_policy.rule_action_policy,
│   on main.tf line 49, in resource "aws_iam_role_policy" "rule_action_policy":
│   49: resource "aws_iam_role_policy" "rule_action_policy" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with aws_iot_topic_rule.rule,
│   on main.tf line 56, in resource "aws_iot_topic_rule" "rule":
│   56: resource "aws_iot_topic_rule" "rule" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v3.38.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x4adfc7c]

goroutine 134 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsIotTopicRuleRead(0xc001a9cf80, 0x5f2f3c0, 0xc001d90600, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_iot_topic_rule.go:1124 +0x35c
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsIotTopicRuleCreate(0xc001a9cf80, 0x5f2f3c0, 0xc001d90600, 0x0, 0xffffffffffffffff)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_iot_topic_rule.go:1105 +0x365
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000640380, 0x77701e8, 0xc001b9ff00, 0xc001a9cf80, 0x5f2f3c0, 0xc001d90600, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000640380, 0x77701e8, 0xc001b9ff00, 0xc001e4cee0, 0xc001d13440, 0x5f2f3c0, 0xc001d90600, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000ced0, 0x77701e8, 0xc001b9ff00, 0xc001e8a000, 0xc001b9ff00, 0x6a8a620, 0xc001e6fd00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc001edc360, 0x7770290, 0xc001b9ff00, 0xc001e4cd90, 0xc001edc360, 0xc001e6fd10, 0xc0000baba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x6a8a620, 0xc001edc360, 0x7770290, 0xc001e6fd10, 0xc001bb59e0, 0x0, 0x7770290, 0xc001e6fd10, 0xc001bde480, 0x456)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000237500, 0x7790758, 0xc00130fb00, 0xc001fdaa00, 0xc0007acae0, 0xacd2dc0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000237500, 0x7790758, 0xc00130fb00, 0xc001fdaa00, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000ea4930, 0xc000237500, 0x7790758, 0xc00130fb00, 0xc001fdaa00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.38.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

```
$ awslocal iot list-topic-rules
{
    "rules": [
        {
            "ruleDisabled": false
        }
    ]
}
```

Logs from `localstack`
```
2021-05-05T09:25:48:DEBUG:localstack.services.edge: IN(iot): "GET /rules" - headers: {'Remote-Addr': '172.17.0.1', 'Host': 'localhost:4566', 'Accept-Encoding': 'identity', 'User-Agent': 'aws-cli/2.1.27 Python/3.7.3 Linux/5.4.0-58-generic exe/x86_64.ubuntu.20 prompt/off command/iot.list-topic-rules', 'X-Amz-Date': '20210505T092548Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=_not_needed_locally_/20210505/us-east-1/execute-api/aws4_request, SignedHeaders=host;x-amz-date, Signature=cf149c9d71829e1c0a139820fc2cee568d1deca40ae18581dfaa7bd8feff0f37', 'X-Forwarded-For': '172.17.0.1, localhost:4566', 'x-localstack-edge': 'http://localhost:4566'} - data: b''
2021-05-05T09:25:48:DEBUG:localstack.services.edge: OUT(iot): "GET /rules" - status: 200 - response headers: {'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'Access-Control-Expose-Headers': 'x-amz-version-id'} - response: {"rules": [{"ruleDisabled": false}]}
2021-05-05T09:29:56:DEBUG:localstack.services.edge: IN(iot): "GET /rules" - headers: {'Remote-Addr': '172.17.0.1', 'Host': 'localhost:4566', 'Accept-Encoding': 'identity', 'User-Agent': 'aws-cli/2.1.27 Python/3.7.3 Linux/5.4.0-58-generic exe/x86_64.ubuntu.20 prompt/off command/iot.list-topic-rules', 'X-Amz-Date': '20210505T092956Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=_not_needed_locally_/20210505/us-east-1/execute-api/aws4_request, SignedHeaders=host;x-amz-date, Signature=b5e9f9a6cbf592d95fddc0fa2a7236452dd41d2760bf096b5815df66b6905cc1', 'X-Forwarded-For': '172.17.0.1, localhost:4566', 'x-localstack-edge': 'http://localhost:4566'} - data: b''
2021-05-05T09:29:56:DEBUG:localstack.services.edge: OUT(iot): "GET /rules" - status: 200 - response headers: {'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'Access-Control-Expose-Headers': 'x-amz-version-id'} - response: {"rules": [{"ruleDisabled": false}]}
```

**Comment by whummer** [comment]
Thanks for reporting @j-sv - this should be fixed in the meantime. Can you please pull the `latest` Docker image and give it another try? Thanks for your help!
