### ISSUE TITLE
Uploading a binary file from a Java app to localstack S3 fails

### ISSUE THREAD

**Issue by alek-sys** [localstack/localstack#397]
When uploading binary files (e.g. zip archives) to localstack S3 from Java test using `LocalstackTestRunner` localstack fails and upload times out.

Sample test: 
```java
@RunWith(LocalstackTestRunner.class)
public class SimpleTest {

    @Test
    public void shouldAllowToUploadFileToLocalstackS3() throws IOException {
        AmazonS3 clientS3 = TestUtils.getClientS3();
        clientS3.createBucket("bucket1");

        File file = Files.createTempFile("localstack", "s3").toFile();
        ZipOutputStream zipOutputStream = new ZipOutputStream(new FileOutputStream(file));
        zipOutputStream.putNextEntry(new ZipEntry("Some content"));
        zipOutputStream.write("Some text content".getBytes());
        zipOutputStream.closeEntry();
        zipOutputStream.close();

        file.deleteOnExit();

        clientS3.putObject("bucket1", file.getName(), file);
    }
}
```

Exception in localstack console:
```
2017-10-11T22:00:33:ERROR:localstack.services.generic_proxy: Error forwarding request: cannot use a string pattern on a bytes-like object Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/localstack/services/generic_proxy.py", line 171, in forward
    path=path, data=data, headers=forward_headers)
  File "/usr/local/lib/python3.6/site-packages/localstack/services/s3/s3_listener.py", line 342, in forward_request
    modified_data = strip_chunk_signatures(data)
  File "/usr/local/lib/python3.6/site-packages/localstack/services/s3/s3_listener.py", line 210, in strip_chunk_signatures
    data_new = re.sub(r'^[0-9a-fA-F]+;chunk-signature=[0-9a-f]{64}', '', data, flags=re.MULTILINE)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object
```

Replacing ZIP file with simple text file works ok. 

Possible workaround is to build a client manually and switch it to anonymous authentication, as it seems like the issue happens when parsing authentications headers.

Localstack version: 0.1.7, jdk1.8.0_144, macOs High Sierra, Python 3.6

**Comment by whummer** [comment]
Thanks for reporting @alek-sys . Unfortunately I haven't been able to reproduce this issue under Mac OS Sierra, Python 3.6.2, LocalStack v. 0.8.2. Can you please give it a try with the latest version? Thanks

**Comment by alek-sys** [comment]
@whummer Yep, works fine in 0.8.2!
