### ISSUE TITLE
Error when sending SQS message to DLQ

### ISSUE THREAD

**Issue by kimberlyamandalu** [localstack/localstack#3981]
##### Type of request: 
This is a bug report

# Detailed description
We use Lambda Powertools SQS batch processor. As we understand, messages that fail to process successfully can be sent to a DLQ. We have our architecture configured this way. However, when a message tries to be sent to the DLQ, we keep seeing this error in the Lambda logs:

localstack    | 2021-05-06T18:57:29:INFO:localstack.utils.aws.dead_letter_queue: Sending failed execution arn:aws:sqs:us-east-1:000000000000:rmd-aircraft-sqs to dead letter queue arn:aws:sqs:us-east-1:000000000000:rmd-aircraft-dlq
localstack    | 2021-05-06T18:57:29:INFO:localstack.utils.aws.dead_letter_queue: Unable to send message to dead letter queue http://localhost:4566/000000000000/rmd-aircraft-dlq (code None): An error occurred (InvalidMessageContents) when calling the SendMessage operation: Message contains invalid characters

Here is some info about the Lambda function and the SQS Queues

SQS Queues:
# Primary
```
aws --endpoint-url=http://localhost:4566 \
    sqs get-queue-attributes \
    --queue-url http://localhost:4566/000000000000/rmd-aircraft-sqs
{
    "Attributes": {
        "ApproximateNumberOfMessages": "0",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "CreatedTimestamp": "1620326629.651314",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1620326629.651314",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:us-east-1:000000000000:rmd-aircraft-sqs",
        "RedrivePolicy": "{\"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:000000000000:rmd-aircraft-dlq\",\"maxReceiveCount\":1}",
        "ReceiveMessageWaitTimeSeconds": "15",
        "VisibilityTimeout": "10"
    }
}

```
# DLQ
```
aws --endpoint-url=http://localhost:4566 \
     sqs get-queue-attributes \
     --queue-url http://localhost:4566/000000000000/rmd-aircraft-dlq
{
    "Attributes": {
        "ApproximateNumberOfMessages": "1",
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "CreatedTimestamp": "1620326592.312234",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1620326592.312234",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:us-east-1:000000000000:rmd-aircraft-dlq",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "30"
    }
}
```

# Lambda function
```
> aws --endpoint-url=http://localhost:4566 lambda get-function --function-name rmd-air
{
    "Configuration": {
        "FunctionName": "rmd-air",
        "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:rmd-air",
        "Runtime": "python3.8",
        "Role": "arn:aws:iam::000000000000:role/irrelevant:role/irrelevant",
        "Handler": "app.handler",
        "CodeSize": 97112632,
        "Description": "",
        "Timeout": 3,
        "LastModified": "2021-05-06T18:46:16.084+0000",
        "CodeSha256": "TxB220OjwTZZvcdjTRHTsr5hQWtaia3A13ws2yUIuo0=",
        "Version": "$LATEST",
        "VpcConfig": {},
        "Environment": {
            "Variables": {
                "AWS_SAM_LOCAL": "True",
                "LOG_LEVEL": "INFO",
                "ORACLE_DB_CONN_SECRET": "<>",
                "POWERTOOLS_SERVICE_NAME": "<>",
                "RMD_DB_DATABASE": "XE",
                "RMD_DB_HOST": "host.docker.internal",
                "RMD_DB_PASSWORD": "<>",
                "RMD_DB_PORT": "1521",
                "RMD_DB_USERNAME": "<>"
            }
        },
        "TracingConfig": {
            "Mode": "PassThrough"
        },
        "RevisionId": "111823b3-c5cb-4911-ba91-afa7e8f1294d",
        "State": "Active",
        "LastUpdateStatus": "Successful",
        "PackageType": "Zip"
    },
    "Code": {
        "Location": "http://localhost:4566/2015-03-31/functions/rmd-air/code"
    },
    "Tags": {}
}
```

# Event Source Mapping
```
> aws --endpoint-url=http://localhost:4566 lambda list-event-source-mappings
{
    "EventSourceMappings": [
        {
            "UUID": "49e75dd6-aaf6-4722-a03c-66a29ab413b4",
            "StartingPosition": "LATEST",
            "BatchSize": 10,
            "EventSourceArn": "arn:aws:sqs:us-east-1:000000000000:rmd-aircraft-sqs",
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:rmd-air",
            "LastModified": "2021-05-06T14:47:15-04:00",
            "LastProcessingResult": "OK",
            "State": "Enabled",
            "StateTransitionReason": "User action"
        }
    ]
}

> aws --endpoint-url=http://localhost:4566 lambda get-event-source-mapping --uuid 49e75dd6-aaf6-4722-a03c-66a29ab413b4
{
    "UUID": "49e75dd6-aaf6-4722-a03c-66a29ab413b4",
    "StartingPosition": "LATEST",
    "BatchSize": 10,
    "EventSourceArn": "arn:aws:sqs:us-east-1:000000000000:rmd-aircraft-sqs",
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:rmd-air",
    "LastModified": "2021-05-06T14:47:15-04:00",
    "LastProcessingResult": "OK",
    "State": "Enabled",
    "StateTransitionReason": "User action"
}
```

We send messages by batch via the SQS CLI using a JSON file:
```
aws --endpoint-url=http://localhost:4566 sqs send-message-batch --queue-url http://localhost:4576/000000000000/av-core-asset-etl-rmd-aircraft-sqs-nonprod --entries file://./rmd_aircraft_sqs_batch_fail.json
{
    "Successful": [
        {
            "Id": "bad-message",
            "MessageId": "80d9eb52-247f-7441-e546-5f8615a72d73",
            "MD5OfMessageBody": "94e14d87d234ee260b9e7480cdbdb1d3"
        }
    ]
}
```

Here are the contents of the json file:
```
[
    {
        "Id": "bad-message",
        "MessageBody": "{\"key\": \"val\"}"
    }
]
```

Here is the complete error from when the lambda function gets triggered up to when message tries to get to DLQ:
```
localstack    | 2021-05-06T18:57:03:DEBUG:localstack.services.awslambda.lambda_executors: Checking if there are idle containers ...
localstack    | 2021-05-06T18:57:29:DEBUG:localstack.services.awslambda.lambda_api: Found 1 source mappings for event from SQS queue arn:aws:sqs:us-east-1:000000000000:rmd-aircraft-sqs: ['arn:aws:lambda:us-east-1:000000000000:function:rmd-air']
localstack    | 2021-05-06T18:57:29:DEBUG:localstack.services.awslambda.lambda_api: Sending event from event source arn:aws:sqs:us-east-1:000000000000:rmd-aircraft-sqs to Lambda arn:aws:lambda:us-east-1:000000000000:function:rmd-air
localstack    | 2021-05-06T18:57:29:DEBUG:localstack.services.awslambda.lambda_executors: Lambda executed in Event (asynchronous) mode, no response will be returned to caller
localstack    | 2021-05-06T18:57:29:DEBUG:localstack.services.awslambda.lambda_executors: Priming docker container with runtime "python3.8" and arn "arn:aws:lambda:us-east-1:000000000000:function:rmd-air".
localstack    | 2021-05-06T18:57:29:DEBUG:localstack.services.awslambda.lambda_executors: Getting status for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_rmd-air": docker ps -a --filter name='localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_rmd-air' --format "{{ .Status }} - {{ .Names }}" | grep -w "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_rmd-air" | cat
localstack    | 2021-05-06T18:57:29:DEBUG:localstack.services.awslambda.lambda_executors: Priming docker container (status "1"): localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_rmd-air
localstack    | 2021-05-06T18:57:29:DEBUG:localstack.services.awslambda.lambda_executors: Getting the entrypoint for image: "lambci/lambda:python3.8"
localstack    | 2021-05-06T18:57:29:DEBUG:localstack.services.awslambda.lambda_executors: docker image inspect --format="{{ .Config.Entrypoint }}" "lambci/lambda:python3.8"
localstack    | 2021-05-06T18:57:29:DEBUG:localstack.services.awslambda.lambda_executors: Getting status for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_rmd-air": docker ps -a --filter name='localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_rmd-air' --format "{{ .Status }} - {{ .Names }}" | grep -w "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_rmd-air" | cat
localstack    | 2021-05-06T18:57:29:DEBUG:localstack.services.awslambda.lambda_executors: Getting container network: localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_rmd-air
localstack    | 2021-05-06T18:57:29:DEBUG:localstack.services.awslambda.lambda_executors: docker inspect localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_rmd-air --format "{{ .HostConfig.NetworkMode }}"
localstack    | 2021-05-06T18:57:29:DEBUG:localstack.services.awslambda.lambda_executors: Using entrypoint "/var/rapid/init --bootstrap /var/runtime/bootstrap --enable-msg-logs" for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_rmd-air" on network "docker_default".
localstack    | 2021-05-06T18:57:29:DEBUG:localstack.services.awslambda.lambda_executors: Command for docker-reuse Lambda executor:  docker exec -e AWS_SAM_LOCAL="$AWS_SAM_LOCAL" -e RMD_DB_HOST="$RMD_DB_HOST" -e RMD_DB_PORT="$RMD_DB_PORT" -e RMD_DB_DATABASE="$RMD_DB_DATABASE" -e RMD_DB_USERNAME="$RMD_DB_USERNAME" -e RMD_DB_PASSWORD="$RMD_DB_PASSWORD" -e ORACLE_DB_CONN_SECRET="$ORACLE_DB_CONN_SECRET" -e LOG_LEVEL="$LOG_LEVEL" -e POWERTOOLS_SERVICE_NAME="$POWERTOOLS_SERVICE_NAME" -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" -e AWS_REGION="$AWS_REGION" -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e HTTP_PROXY="$HTTP_PROXY" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" -e _LAMBDA_SERVER_PORT="$_LAMBDA_SERVER_PORT" localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_rmd-air /var/rapid/init --bootstrap /var/runtime/bootstrap --enable-msg-logs app.handler
localstack    | 2021-05-06T18:57:29:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd:  docker exec -e AWS_SAM_LOCAL="$AWS_SAM_LOCAL" -e RMD_DB_HOST="$RMD_DB_HOST" -e RMD_DB_PORT="$RMD_DB_PORT" -e RMD_DB_DATABASE="$RMD_DB_DATABASE" -e RMD_DB_USERNAME="$RMD_DB_USERNAME" -e RMD_DB_PASSWORD="$RMD_DB_PASSWORD" -e ORACLE_DB_CONN_SECRET="$ORACLE_DB_CONN_SECRET" -e LOG_LEVEL="$LOG_LEVEL" -e POWERTOOLS_SERVICE_NAME="$POWERTOOLS_SERVICE_NAME" -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" -e AWS_REGION="$AWS_REGION" -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e HTTP_PROXY="$HTTP_PROXY" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" -e _LAMBDA_SERVER_PORT="$_LAMBDA_SERVER_PORT" localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_rmd-air /var/rapid/init --bootstrap /var/runtime/bootstrap --enable-msg-logs app.handler
localstack    | 2021-05-06T18:57:29:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:rmd-air result / log output:
localstack    | {"errorType":"SQSBatchProcessingError","errorMessage":"[KeyError('detail-type')]","stackTrace":["  File \"/var/task/aws_lambda_powertools/tracing/tracer.py\", line 282, in decorate\n    response = lambda_handler(event, context)\n","  File \"/var/task/aws_lambda_powertools/logging/logger.py\", line 247, in decorate\n    return lambda_handler(event, context)\n","  File \"/var/task/aws_lambda_powertools/middleware_factory/factory.py\", line 130, in wrapper\n    response = middleware()\n","  File \"/var/task/aws_lambda_powertools/utilities/batch/sqs.py\", line 181, in sqs_batch_processor\n    processor.process()\n","  File \"/var/task/aws_lambda_powertools/utilities/batch/base.py\", line 58, in __exit__\n    self._clean()\n","  File \"/var/task/aws_lambda_powertools/utilities/batch/sqs.py\", line 126, in _clean\n    raise SQSBatchProcessingError(list(self.exceptions))\n"]}
localstack    | > START RequestId: b1559c0d-71f7-1d50-94fe-a29dedf6a2f0 Version: $LATEST
localstack    | > {"level": "INFO", "location": "decorate:245", "message": {"Records": [{"body": "{\"key\": \"val\"}", "receiptHandle": "jrzfbkdgkwmfyoldgwekuhkevkdbalhrukummmlpbjhxlugprialwmhhztmwwagnmngsdaogurawdqddsvpshngqiguitutgskmzquqxcezeocrulacyfltbwnkvlzsqnjednpobhjkqitkxpqlzyvkqzazhddoperuvhpwlkvveyekegjjieebkr", "md5OfBody": "94e14d87d234ee260b9e7480cdbdb1d3", "eventSourceARN": "arn:aws:sqs:us-east-1:000000000000:rmd-aircraft-sqs", "eventSource": "aws:sqs", "awsRegion": "us-east-1", "messageId": "049eb94b-b20f-0942-a030-d00dec465d5f", "attributes": {}, "messageAttributes": {}, "md5OfMessageAttributes": null, "sqs": true}]}, "timestamp": "2021-05-06 18:57:29,763", "service": "av-core-asset-etl-rmd-aircraft-qa", "sampling_rate": 0.0, "cold_start": true, "function_name": "rmd-air", "function_memory_size": "1536", "function_arn": "arn:aws:lambda:us-east-1:000000000000:function:rmd-air", "function_request_id": "b1559c0d-71f7-1d50-94fe-a29dedf6a2f0", "xray_trace_id": "1-dc99d00f-c079a84d433534434534ef0d"}
localstack    | > [ERROR] SQSBatchProcessingError: [KeyError('detail-type')]
localstack    | > Traceback (most recent call last):
localstack    | >   File "/var/task/aws_lambda_powertools/tracing/tracer.py", line 282, in decorate
localstack    | >     response = lambda_handler(event, context)
localstack    | >   File "/var/task/aws_lambda_powertools/logging/logger.py", line 247, in decorate
localstack    | >     return lambda_handler(event, context)
localstack    | >   File "/var/task/aws_lambda_powertools/middleware_factory/factory.py", line 130, in wrapper
localstack    | >     response = middleware()
localstack    | >   File "/var/task/aws_lambda_powertools/utilities/batch/sqs.py", line 181, in sqs_batch_processor
localstack    | >     processor.process()
localstack    | >   File "/var/task/aws_lambda_powertools/utilities/batch/base.py", line 58, in __exit__
localstack    | >     self._clean()
localstack    | >   File "/var/task/aws_lambda_powertools/utilities/batch/sqs.py", line 126, in _clean
localstack    | >     raise SQSBatchProcessingError(list(self.exceptions))
localstack    | > END RequestId: b1559c0d-71f7-1d50-94fe-a29dedf6a2f0
localstack    | > REPORT RequestId: b1559c0d-71f7-1d50-94fe-a29dedf6a2f0        Init Duration: 3000.00 ms   Duration: 28.84 ms      Billed Duration: 29 ms  Memory Size: 1536 MB    Max Memory Used: 44 MB      
localstack    | 2021-05-06T18:57:29:INFO:localstack.utils.aws.dead_letter_queue: Sending failed execution arn:aws:sqs:us-east-1:000000000000:rmd-aircraft-sqs to dead letter queue arn:aws:sqs:us-east-1:000000000000:rmd-aircraft-dlq
localstack    | 2021-05-06T18:57:29:INFO:localstack.utils.aws.dead_letter_queue: Unable to send message to dead letter queue http://localhost:4566/000000000000/rmd-aircraft-dlq (code None): An error occurred (InvalidMessageContents) when calling the SendMessage operation: Message contains invalid characters
localstack    | 2021-05-06T18:57:29:WARNING:bootstrap.py: Thread run method <function LambdaExecutor.execute.<locals>.do_execute at 0x7f6fffc96f70>(None) failed: Unable to send message to dead letter queue http://localhost:4566/000000000000/rmd-aircraft-dlq (code None): An error occurred (InvalidMessageContents) when calling the SendMessage operation: Message contains invalid characters Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 147, in _run
localstack    |     result = self._execute(func_arn, func_details, event, context, version)
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 397, in _execute
localstack    |     return super(LambdaExecutorReuseContainers, self)._execute(func_arn, *args, **kwargs)
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 325, in _execute
localstack    |     result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 231, in run_lambda_executor
localstack    |     raise InvocationException('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
localstack    | localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned error status code: 1. Result: {"errorType":"SQSBatchProcessingError","errorMessage":"[KeyError('detail-type')]","stackTrace":["  File \"/var/task/aws_lambda_powertools/tracing/tracer.py\", line 282, in decorate\n    response = lambda_handler(event, context)\n","  File \"/var/task/aws_lambda_powertools/logging/logger.py\", line 247, in decorate\n    return lambda_handler(event, context)\n","  File \"/var/task/aws_lambda_powertools/middleware_factory/factory.py\", line 130, in wrapper\n    response = middleware()\n","  File \"/var/task/aws_lambda_powertools/utilities/batch/sqs.py\", line 181, in sqs_batch_processor\n    processor.process()\n","  File \"/var/task/aws_lambda_powertools/utilities/batch/base.py\", line 58, in __exit__\n    self._clean()\n","  File \"/var/task/aws_lambda_powertools/utilities/batch/sqs.py\", line 126, in _clean\n    raise SQSBatchProcessingError(list(self.exceptions))\n"]}. Output:
localstack    | START RequestId: b1559c0d-71f7-1d50-94fe-a29dedf6a2f0 Version: $LATEST
localstack    | {"level": "INFO", "location": "decorate:245", "message": {"Records": [{"body": "{\"key\": \"val\"}", "receiptHandle": "jrzfbkdgkwmfyoldgwekuhkevkdbalhrukummmlpbjhxlugprialwmhhztmwwagnmngsdaogurawdqddsvpshngqiguitutgskmzquqxcezeocrulacyfltbwnkvlzsqnjednpobhjkqitkxpqlzyvkqzazhddoperuvhpwlkvveyekegjjieebkr", "md5OfBody": "94e14d87d234ee260b9e7480cdbdb1d3", "eventSourceARN": "arn:aws:sqs:us-east-1:000000000000:rmd-aircraft-sqs", "eventSource": "aws:sqs", "awsRegion": "us-east-1", "messageId": "049eb94b-b20f-0942-a030-d00dec465d5f", "attributes": {}, "messageAttributes": {}, "md5OfMessageAttributes": null, "sqs": true}]}, "timestamp": "2021-05-06 18:57:29,763", "service": "av-core-asset-etl-rmd-aircraft-qa", "sampling_rate": 0.0, "cold_start": true, "function_name": "rmd-air", "function_memory_size": "1536", "function_arn": "arn:aws:lambda:us-east-1:000000000000:function:rmd-air", "function_request_id": "b1559c0d-71f7-1d50-94fe-a29dedf6a2f0", "xray_trace_id": "1-dc99d00f-c079a84d433534434534ef0d"}
localstack    | [ERROR] SQSBatchProcessingError: [KeyError('detail-type')]
localstack    | Traceback (most recent call last):
localstack    |   File "/var/task/aws_lambda_powertools/tracing/tracer.py", line 282, in decorate
localstack    |     response = lambda_handler(event, context)
localstack    |   File "/var/task/aws_lambda_powertools/logging/logger.py", line 247, in decorate
localstack    |     return lambda_handler(event, context)
localstack    |   File "/var/task/aws_lambda_powertools/middleware_factory/factory.py", line 130, in wrapper
localstack    |     response = middleware()
localstack    |   File "/var/task/aws_lambda_powertools/utilities/batch/sqs.py", line 181, in sqs_batch_processor
localstack    |     processor.process()
localstack    |   File "/var/task/aws_lambda_powertools/utilities/batch/base.py", line 58, in __exit__
localstack    |     self._clean()
localstack    |   File "/var/task/aws_lambda_powertools/utilities/batch/sqs.py", line 126, in _clean
localstack    |     raise SQSBatchProcessingError(list(self.exceptions))
localstack    | END RequestId: b1559c0d-71f7-1d50-94fe-a29dedf6a2f0
localstack    | REPORT RequestId: b1559c0d-71f7-1d50-94fe-a29dedf6a2f0  Init Duration: 3000.00 ms  Duration: 28.84 ms       Billed Duration: 29 ms  Memory Size: 1536 MB    Max Memory Used: 44 MB  
localstack    | 
localstack    | During handling of the above exception, another exception occurred:
localstack    | 
localstack    | Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 689, in run
localstack    |     result = self.func(self.params)
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 168, in do_execute
localstack    |     return _run(func_arn=func_arn)
localstack    |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
localstack    |     raise e
localstack    |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 145, in wrapped
localstack    |     result = func(*args, **kwargs)
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 155, in _run
localstack    |     dlq_sent = sqs_error_to_dead_letter_queue(sqs_queue_arn, event, e)
localstack    |   File "/opt/code/localstack/localstack/utils/aws/dead_letter_queue.py", line 25, in sqs_error_to_dead_letter_queue
localstack    |     return _send_to_dead_letter_queue('SQS', queue_arn, target_arn, event, error)
localstack    |   File "/opt/code/localstack/localstack/utils/aws/dead_letter_queue.py", line 68, in _send_to_dead_letter_queue
localstack    |     raise Exception(msg)
localstack    | Exception: Unable to send message to dead letter queue http://localhost:4566/000000000000/rmd-aircraft-dlq (code None): An error occurred (InvalidMessageContents) when calling the SendMessage operation: Message contains invalid characters
localstack    | 
```

What's even more unusual is, if we check the attributes for the DLQ at this time, it shows that there is 1 message in the queue. When we retrieve that message, it is the bad message we sent:
```
aws --endpoint-url=http://localhost:4566 \
>     sqs get-queue-attributes \
>     --queue-url http://localhost:4566/000000000000/rmd-aircraft-dlq
{
    "Attributes": {
        "**ApproximateNumberOfMessages": "1",**
        "ApproximateNumberOfMessagesDelayed": "0",
        "ApproximateNumberOfMessagesNotVisible": "0",
        "CreatedTimestamp": "1620326592.312234",
        "DelaySeconds": "0",
        "LastModifiedTimestamp": "1620326592.312234",
        "MaximumMessageSize": "262144",
        "MessageRetentionPeriod": "345600",
        "QueueArn": "arn:aws:sqs:us-east-1:000000000000:rmd-aircraft-dlq",
        "ReceiveMessageWaitTimeSeconds": "0",
        "VisibilityTimeout": "30"
    }
}

> aws --endpoint-url=http://localhost:4566 \
    sqs receive-message \
    --queue-url http://localhost:4566/000000000000/rmd-aircraft-dlq \
    --max-number-of-messages 10
{
    "Messages": [
        {
            "MessageId": "049eb94b-b20f-0942-a030-d00dec465d5f",
            "ReceiptHandle": "wjuivytwgkkrpmerpnwigipugzlinkrackuiuajgsmbrguzyeponwbukowrcziqdvrhhrrzgtfgkwpobjewxvdugfqgpelqkksprrhpympiuginslbsnczstbrglusgwnivrxytfvwqmrqjdysqvzivdlknwvxkqrkfglebelllmmrrmefhrshfsm",
            "MD5OfBody": "94e14d87d234ee260b9e7480cdbdb1d3",
            "Body": "{\"key\": \"val\"}"
        }
    ]
}
```

## Expected behavior
The message seems to flow to DLQ successfully so no errors should be logged. 

...

## Actual behavior
An error is logged about failed message sending to DLQ. But message seems to have been delivered.

...

# Steps to reproduce
1. Create SQS to be used as DLQ
2. Create Primary SQS queue and set DLQ target
3. Create Lambda function
4. Create Event Source Mapping between lambda function and primary sqs
5. Send message to SQS that fails so that SQSBatchProcessingError exception is raised causing the message to be sent to the DLQ

## Command used to start LocalStack
docker-compose up -d

docker-compose file:
```
version: '3.9'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      AWS_DEFAULT_REGION: us-east-1
      EDGE_PORT: 4566
      SERVICES: sqs,lambda,s3,secretsmanager
      LAMBDA_EXECUTOR: docker-reuse
      DEBUG: 1
      LAMBDA_DOCKER_NETWORK: docker_default
      LOCALSTACK_HOSTNAME: 127.0.0.1
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Provided in the detailed description above.

...

**Comment by whummer** [comment]
Thanks for reporting @kimberlyamandalu . This should be fixed in #3999 - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks
