### ISSUE TITLE
Cognito - InitiateAuth fails with "InternalServerError" on existing user

### ISSUE THREAD

**Issue by John-D8** [localstack/localstack#3987]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Calling `InitiateAuth()` with an existing username & password causes an InternalServerError to be thrown to the client.

## Expected behavior

Should return a successful response with tokens.

## Actual behavior

InternalServerError is thrown.
See localstack log on the bottom.

# Steps to reproduce

1) Define a user pool, add a user and set a password (with AdminSetUserPassword).
2) Call InitiateAuth with the created user and password.

## Command used to start LocalStack

docker-compose

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
      res = await cognito.initiateAuth({
        ClientId: clientId,
        AuthFlow: 'USER_PASSWORD_AUTH',
        AuthParameters: {
          USERNAME: 'user@example.com',
          PASSWORD: 'pass',
        },
        ClientMetadata: {
          'role': 'admin'
        }
      }).promise();
```

User pool UsernameAttributes: ['email']
User pool schema:
```
        {
            'Name': 'email',
            'AttributeDataType': 'String',
            'StringAttributeConstraints': {
                'MinLength': '1',
                'MaxLength': '100',
            },
            'Mutable': False,
            'Required': True,
            'DeveloperOnlyAttribute': False,
        },
        {
            'Name': 'given_name',
            'AttributeDataType': 'String',
            'StringAttributeConstraints''': {
                'MinLength': '1',
                'MaxLength': '200',
            },
            'Mutable': True,
            'Required': False,
            'DeveloperOnlyAttribute': False,
        }, {
            'Name': 'family_name',
            'AttributeDataType': 'String',
            'StringAttributeConstraints': {
                'MinLength': '1',
                'MaxLength': '200',
            },
            'Mutable': True,
            'Required': False,
            'DeveloperOnlyAttribute': False,
        }, {
            'Name': 'gender',
            'AttributeDataType': 'String',
            'StringAttributeConstraints': {
                'MinLength': '1',
                'MaxLength': '50',
            },
            'Mutable': True,
            'Required': False,
            'DeveloperOnlyAttribute': False,
        }, {
            'Name': 'birthdate',
            'Mutable': False,
            'Required': False,
        }, {
            'Name': 'userId',
            'AttributeDataType': 'Number',
            'NumberAttributeConstraints': {
                'MinValue': '0',
                'MaxValue': '10000000',
            },
            'Mutable': False,
        },
        {
            'Name': 'role',
            'AttributeDataType': 'String',
            'StringAttributeConstraints': {
                'MinLength': '1',
                'MaxLength': '100',
            },
            'Mutable': True,
        },
        {
            'Name': 'status',
            'AttributeDataType': 'String',
            'StringAttributeConstraints': {
                'MinLength': '1',
                'MaxLength': '100',
            },
            'Mutable': True,
        },
        {
            'Name': 'accountId',
            'AttributeDataType': 'Number',
            'StringAttributeConstraints': {
                'MinLength': '1',
                'MaxLength': '10000',
            },
            'Mutable': False,
        },
        {
            'Name': 'accountName',
            'AttributeDataType': 'String',
            'StringAttributeConstraints': {
                'MinLength': '1',
                'MaxLength': '100',
            },
            'Mutable': False,
        }
    ]
```

Cognito lambda triggers:
PreAuthentication, PostAuthentication, PostConfirmation, CustomEmailSender, KMSKeyID

User attributes as appears in the user pool:
```
email: user@example.com
sub: eefbe013-0e37-4924-b8aa-6e1a2022ad39
username: eefbe013-0e37-4924-b8aa-6e1a2022ad39
```

Localstack error in logs:
```
2021-05-07T13:08:28:DEBUG:localstack.services.edge: OUT(cognito-idp): "POST /" - status: 500 - response headers: {'x-amzn-errortype': 'InternalServerError', 'x-amzn-errormessage': 'Error in Cognito action "InitiateAuth": \'Username\' Traceback (most recent call last):\n File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_listener.py", line 108, in forward_request\n File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_helpers.py", line 161, in initiate_auth\n File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_helpers.py", line 254, in initiate_auth_user_pass\n File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_helpers.py", line 1182, in issue_token\n File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_helpers.py", line 1115, in create_jwt_token\n File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_helpers.py", line 1061, in get_user_sub\n File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_helpers.py", line 1231, in find_user\nKeyError: \'Username\'\n', 'x-amzn-requestid': 'ec5c0589-4a33-492b-8256-77560ba4d6a7', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'Access-Control-Expose-Headers': 'x-amz-version-id'} - response: {"__type": "InternalServerError", "message": "Error in Cognito action \"InitiateAuth\": 'Username' Traceback (most recent call last):\n File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_listener.py\", line 108, in forward_request\n File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_helpers.py\", line 161, in initiate_auth\n File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_helpers.py\", line 254, in initiate_auth_user_pass\n File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_helpers.py\", line 1182, in issue_token\n File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_helpers.py\", line 1115, in create_jwt_token\n File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_helpers.py\", line 1061, in get_user_sub\n File \"/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_helpers.py\", line 1231, in find_user\nKeyError: 'Username'\n"
```

**Comment by whummer** [comment]
Thanks for reporting @John-D8 . This should (hopefully) be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
