### ISSUE TITLE
HTTP 500 status code when trying to delete a batch of messages from a SQS queue

### ISSUE THREAD

**Issue by v1nc3n4** [localstack/localstack#3993]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

Hi, I'm facing an issue in a Spring Boot application, when trying to delete a batch of messages previously received from a SQS queue. I provide the receipt handle as expected for all messages, but Localstack returns an HTTP 500 status code. Surprisingly, messages seem to be effectively deleted from the queue (subsequent calls to receive messages return no message).

Note: if I replace batch deletion with an individual deletion request for each message, everything works as expected, and Localstack returns a HTTP 200 status code.

I'm working with the latest Docker image, and started with the following configuration:

```yml
localstack:
    container_name: infrastructure
    image: localstack/localstack:latest
    environment:
        DATA_DIR: /tmp/localstack/data
        DEBUG: 1
        SERVICES: sns,sqs
    ports:
        - 4566:4566
        - 4571:4571
```

Please find below the stack trace in Localstack:

```
2021-05-09 16:34:14,015:API: 127.0.0.1 - - [09/May/2021 16:34:14] "POST / HTTP/1.1" 500 -
2021-05-09 16:34:14,026:API: Error on request:
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
execute(self.server.app)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
application_iter = app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 177, in __call__
return backend_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 156, in __call__
result = self.callback(request, request.url, {})
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 205, in dispatch
return cls()._dispatch(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 315, in _dispatch
return self.call_action()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 259, in _wrapper
response = f(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 291, in _wrapper
response = f(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/sqs/responses.py", line 76, in call_action
status_code, headers, body = super(SQSResponse, self).call_action()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 405, in call_action
response = method()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/sqs/responses.py", line 350, in delete_message_batch
message_user_id = self.querystring.get(message_user_id_key)[0]
TypeError: 'NoneType' object is not subscriptable
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Below is the code used to delete the batch of messages in the Spring Boot application, with AWS SDK v2.16.40:

```java
sqsAsyncClient.deleteMessageBatch(
    DeleteMessageBatchRequest.builder().queueUrl(queueUrl).entries(receiptHandles).build()
);
```

What am I doing wrong?

Thanks in advance for your help.
BR

**Comment by v1nc3n4** [comment]
Hi,
I must apologize, I forgot to provide the `id` parameter for each entry in the batch. Once fixed, Localstack deletes messages as expected.
Sorry for the inconvenience 😕.
BR
