### ISSUE TITLE
Creating Document response CreatedDate Invalid Format

### ISSUE THREAD

**Issue by STRRL** [localstack/localstack#3997]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
Hi, I am testing https://github.com/amzn/awsssmchaosrunner with localstack, it will create new Documents, and localstack return an invalid datetime just likes https://github.com/localstack/localstack/issues/981;

AWS java SDK failed to parse it by ISO8601 format or epoch seconds.

## Expected behavior
The document could be created and the no exception raised by java SDK.

## Actual behavior
Java SDK raises an exception:
```
com.amazonaws.SdkClientException: Unable to unmarshall response (Invalid format: "2021-05-11 03:10:07" is malformed at " 03:10:07"). Response Code: 200, Response Text: 
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1758)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleSuccessResponse(AmazonHttpClient.java:1454)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1369)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClient.doInvoke(AWSSimpleSystemsManagementClient.java:10299)
	at com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClient.invoke(AWSSimpleSystemsManagementClient.java:10266)
	at com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClient.invoke(AWSSimpleSystemsManagementClient.java:10255)
	at com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClient.executeCreateDocument(AWSSimpleSystemsManagementClient.java:1262)
	at com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClient.createDocument(AWSSimpleSystemsManagementClient.java:1231)
	at software.amazon.awsssmchaosrunner.attacks.SSMAttack$Companion.createCommandDocument(SSMAttack.kt:92)
	at software.amazon.awsssmchaosrunner.attacks.SSMAttack$DefaultImpls.start(SSMAttack.kt:43)
	at software.amazon.awsssmchaosrunner.attacks.CPUHogAttack.start(CPUHogAttack.kt:12)
	at org.chaosmesh.runner.commands.Attack.run(Attack.kt:71)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.chaosmesh.runner.MainKt.main(Main.kt:14)
Caused by: java.lang.IllegalArgumentException: Invalid format: "2021-05-11 03:10:07" is malformed at " 03:10:07"
	at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
	at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:780)
	at com.amazonaws.util.DateUtils.doParseISO8601Date(DateUtils.java:98)
	at com.amazonaws.util.DateUtils.parseISO8601Date(DateUtils.java:77)
	at com.amazonaws.transform.SimpleTypeJsonUnmarshallers$DateJsonUnmarshaller.unmarshall(SimpleTypeJsonUnmarshallers.java:193)
	at com.amazonaws.transform.SimpleTypeJsonUnmarshallers$DateJsonUnmarshallerFactory.unmarshall(SimpleTypeJsonUnmarshallers.java:237)
	at com.amazonaws.services.simplesystemsmanagement.model.transform.DocumentDescriptionJsonUnmarshaller.unmarshall(DocumentDescriptionJsonUnmarshaller.java:77)
	at com.amazonaws.services.simplesystemsmanagement.model.transform.CreateDocumentResultJsonUnmarshaller.unmarshall(CreateDocumentResultJsonUnmarshaller.java:53)
	at com.amazonaws.services.simplesystemsmanagement.model.transform.CreateDocumentResultJsonUnmarshaller.unmarshall(CreateDocumentResultJsonUnmarshaller.java:29)
	at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:118)
	at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:43)
	at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:69)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1734)
	... 27 more
```

# Steps to reproduce
Trying to using the example of the awsssmchaosrunner

## Command used to start LocalStack

`docker run --rm -it -p 4566:4566 -p 4571:4571 localstack/localstac`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```kotlin
val request = CreateDocumentRequest()
    .withDocumentFormat(DocumentFormat.YAML)
    .withContent(documentContent)
    .withDocumentType(DocumentType.Command)
    .withTargetType(EC2TargetType)
    .withName(documentName)
return ssm.createDocument(request)
```

**Comment by STRRL** [comment]
It seems localstack uses a private fork of upstream moto called `moto-ext`, I think it might be the reason.

**Comment by whummer** [comment]
Thanks for reporting @STRRL . This should be fixed in the meantime - the date is now returned in the format "YYYY-mm-ddThh:mm:ssZ", which should be compatible with the Java SDK.

```
$ awslocal ssm --debug create-document --document-format JSON --document-type Policy --content '{"schemaVersion":"1"}' --name test1
...
... "CreatedDate": "2021-12-13T19:14:47Z" ...
```

Hope that helps - please let us know if the problem persists.. Thanks!
