### ISSUE TITLE
Webpack + Typescript - Runtime.ImportModuleError

### ISSUE THREAD

**Issue by ThomasLabstep** [localstack/localstack#4000]
I've been trying to setup localstack for 2 weeks without luck to replace serverless-offline and all of its weird plugins to simulate dynamodb streams and sqs triggers.

I'm on Mac OSX.

If you can spot the issue, let me know. I'm hopeless at this stage (pun intended).

serverless.ts
```
import type { Serverless } from 'serverless/aws';

// Load dotenv
require('dotenv').config({
  path: __dirname + '/.env.' + process.env.NODE_ENV
});

const serverlessConfiguration: Serverless = {
  service: {
    name: 'pathofchild',
  },
  frameworkVersion: '2',
  package: {
    individually: true
  },
  custom: {
    webpack: {
      webpackConfig: './webpack.config.js',
      includeModules: true,
      keepoutputDirectory: true
    },
    localstack: {
      stages: ['local'],
      host: 'http://localhost',
      edgePort: 4566,
      autostart: true,
      debug: true,
      lambda: {
        mountCode: true
      },
      docker: {
        sudo: false
      }
    },
  },
  plugins: [
    'serverless-webpack',
    'serverless-localstack',
  ],
  provider: {
    name: 'aws',
    region: process.env.AWS_REGION,
    runtime: 'nodejs12.x',
    apiGateway: {
      minimumCompressionSize: 1024,
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
    },
  },
  functions: {
    graphql: {
      handler: 'lib/handler.graphql',
      events: [
        {
          http: {
            path: 'graphql',
            method: 'post',
            cors: true,
          }
        }
      ]
    }
  }
}

module.exports = serverlessConfiguration;
```

tsconfig.js
```
{
  "compilerOptions": {
    "lib": ["es2017", "dom", "esnext"],
    "removeComments": true,
    "moduleResolution": "node",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "sourceMap": true,
    "esModuleInterop": true,
    "target": "es2017",
    "outDir": ".webpack"
  },
  "include": ["./**/*.ts"],
  "exclude": [
    "node_modules/**/*",
    ".serverless/**/*",
    ".webpack/**/*"
  ]
}
```

webpack.config.js
```
const path = require('path');
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

module.exports = {
  context: __dirname,
  mode: 'development', // slsw.lib.webpack.isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  devtool: 'cheap-module-eval-source-map', // slsw.lib.webpack.isLocal ? 'cheap-module-eval-source-map' : 'source-map',
  resolve: {
    extensions: ['.mjs', '.json', '.ts'],
    symlinks: false,
    cacheWithContext: false,
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  target: 'node',
  externals: [nodeExternals()],
  module: {
    rules: [
      // all files with a `.ts` or `.tsx` extension will be handled by `ts-loader`
      {
        test: /\.(tsx?)$/,
        loader: 'ts-loader',
        exclude: [
          [
            path.resolve(__dirname, 'node_modules'),
            path.resolve(__dirname, '.serverless'),
            path.resolve(__dirname, '.webpack'),
            path.resolve(__dirname, 'data'),
            path.resolve(__dirname, 'e2e'),
            path.resolve(__dirname, 'localstack-data'),
          ],
        ],
        options: {
          transpileOnly: true,
          experimentalWatchApi: true,
        },
      },
    ],
  },
  plugins: [
    new ForkTsCheckerWebpackPlugin({
      eslint: true,
      eslintOptions: {
        cache: true
      }
    })
  ],
  optimization: {
    minimize: false,
  },
};
```

webpack output
```
Built at: 10/05/2021 16:26:17
         Asset     Size       Chunks             Chunk Names
lib/handler.js  171 KiB  lib/handler  [emitted]  lib/handler
Entrypoint lib/handler = lib/handler.js
[./lib/handler.ts] 910 bytes {lib/handler} [built]
```

curl -X POST http://localhost:4566/restapis/4lsj8aqf3g/local/_user_request_/graphql
```
{
	"errorType": "InvocationException",
	"errorMessage": "Lambda process returned error status code: 1. Result: {
errorType
:
Runtime.ImportModuleError
,
errorMessage
:
Error: Cannot find module '/var/task/lib/handler'\\nRequire stack:\\n- /var/runtime/UserFunction.js\\n- /var/runtime/index.js
}. Output:\n2021-05-10T15:37:04.379Z\tundefined\tERROR\tUncaught Exception \t{
errorType
:
Runtime.ImportModuleError
,
errorMessage
:
Error: Cannot find module '/var/task/lib/handler'\\nRequire stack:\\n- /var/runtime/UserFunction.js\\n- /var/runtime/index.js
,
stack
:[
Runtime.ImportModuleError: Error: Cannot find module '/var/task/lib/handler'
,
Require stack:
,
- /var/runtime/UserFunction.js
,
- /var/runtime/index.js
,
    at _loadUserApp (/var/runtime/UserFunction.js:100:13)
,
    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)
,
    at Object.<anonymous> (/var/runtime/index.js:43:30)
,
    at Module._compile (internal/modules/cjs/loader.js:999:30)
,
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
,
    at Module.load (internal/modules/cjs/loader.js:863:32)
,
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
,
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
,
    at internal/main/run_main_module.js:17:47
]}\n\u001b[32mSTART RequestId: 9401b9d2-aea5-1673-00d5-d4fcdd96508c Version: $LATEST\u001b[0m\n\u001b[32mEND RequestId: 9401b9d2-aea5-1673-00d5-d4fcdd96508c\u001b[0m\n\u001b[32mREPORT RequestId: 9401b9d2-aea5-1673-00d5-d4fcdd96508c\tInit Duration: 495.68 ms\tDuration: 2.69 ms\tBilled Duration: 3 ms\tMemory Size: 1536 MB\tMax Memory Used: 39 MB\t\u001b[0m",
	"stackTrace": [
		"  File 
/opt/code/localstack/localstack/services/awslambda/lambda_api.py
, line 602, in run_lambda\n    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,\n",
		"  File 
/opt/code/localstack/localstack/services/awslambda/lambda_executors.py
, line 176, in execute\n    return do_execute()\n",
		"  File 
/opt/code/localstack/localstack/services/awslambda/lambda_executors.py
, line 168, in do_execute\n    return _run(func_arn=func_arn)\n",
		"  File 
/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py
, line 149, in wrapped\n    raise e\n",
		"  File 
/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py
, line 145, in wrapped\n    result = func(*args, **kwargs)\n",
		"  File 
/opt/code/localstack/localstack/services/awslambda/lambda_executors.py
, line 159, in _run\n    raise e\n",
		"  File 
/opt/code/localstack/localstack/services/awslambda/lambda_executors.py
, line 147, in _run\n    result = self._execute(func_arn, func_details, event, context, version)\n",
		"  File 
/opt/code/localstack/localstack/services/awslambda/lambda_executors.py
, line 325, in _execute\n    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)\n",
		"  File 
/opt/code/localstack/localstack/services/awslambda/lambda_executors.py
, line 231, in run_lambda_executor\n    raise InvocationException('Lambda process returned error status code: %s. Result: %s. Output:\\n%s' %\n"
	]
}

```

My hunch tells me that it's an issue with how docker mounts the lambda code.
I think for some reason it's empty and that's why it's not finding the handler defined in my serverless.ts.

Because the .webpack folder looks perfectly fine with lib/handler.js

I'm rebuilding from a hello world sample slowly until I reach my setup to see where it's failing.

**Comment by ThomasLabstep** [comment]
Thank you @pandomic !

This is quality feedback. You gave me many good ideas to explore.

I will remove webpack as a last resort.

**Comment by ThomasLabstep** [comment]
Classic but that was the solution:
```
-    "fork-ts-checker-webpack-plugin": "^3.0.1",
+    "fork-ts-checker-webpack-plugin": "^6.2.6",
-    "serverless-localstack": "^0.4.30",
+    "serverless-localstack": "^0.4.32",
-    "serverless-webpack": "^5.2.0",
+    "serverless-webpack": "^5.5.0",
-    "ts-loader": "^5.3.3",
+    "ts-loader": "^9.1.2",
-    "webpack": "^4.29.0",
+    "webpack": "^5.37.0",
+    "webpack-node-externals": "^3.0.0"
-    "webpack-node-externals": "^1.7.2"
```

-_-
