### ISSUE TITLE
Localstack Docker image - incorrect parsing for "SERVICES" env var

### ISSUE THREAD

**Issue by mikalai-t** [localstack/localstack#4006]
Thank you for the such a great tool! Honestly I'm not sure this is a bug, feel free to close if it's not:

# Type of request: This is a ...

[**X**] bug report
[ ] feature request

# Detailed description

It seems SERVICES env variable value is being parsed incorrectly which causes the listeners for the first and the last in the string AWS services are not started

## Expected behavior

Each of the enumerated AWS services listeners must start

## Actual behavior

A listener for the first service in the SERVICES string is not started, as well as for the last one

# Steps to reproduce

1. Create a `docker-compose.yaml` file:

```yaml
# docker-compose.yaml
version: "3.1"

services:
  localstack:
    image: localstack/localstack:0.12.10
    ports:
        # default edge port for all API invocations
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES="iam,kms,ssm,sts"
      - DEFAULT_REGION="eu-west-1"
      - HOSTNAME="localhost"
      - HOSTNAME_EXTERNAL="localhost"
      - FORCE_NONINTERACTIVE="true"
      - MAIN_CONTAINER_NAME="localstack"
      - LS_LOG="debug"
```

2. Run:
`docker-compose up --force-recreate`

3. Watch the logs from the container (notice absence of `Starting mock XXX service on http port 4566 ...` for `IAM` and `STS`!
```
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2021-05-12 12:04:21,102 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_1  | 2021-05-12 12:04:21,105 INFO supervisord started with pid 13
localstack_1  | 2021-05-12 12:04:22,108 INFO spawned: 'dashboard' with pid 19
localstack_1  | 2021-05-12 12:04:22,112 INFO spawned: 'infra' with pid 20
localstack_1  | 2021-05-12 12:04:22,121 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_1  | 2021-05-12 12:04:22,121 INFO exited: dashboard (exit status 0; expected)
localstack_1  | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  | 2021-05-12 12:04:24,091 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 
localstack_1  | LocalStack version: 0.12.11
localstack_1  | LocalStack build date: 2021-05-06
localstack_1  | LocalStack build git hash: 0728a51c
localstack_1  | 
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | Starting edge router (https port 4566)...
localstack_1  | Starting mock KMS service on http port 4566 ...
localstack_1  | Starting mock SSM service on http port 4566 ...
localstack_1  | [2021-05-12 12:04:28 +0000] [21] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_1  | 2021-05-12T12:04:28:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_1  | 2021-05-12T12:04:28:INFO:localstack.multiserver: Starting multi API server process on port 38043
localstack_1  | [2021-05-12 12:04:28 +0000] [21] [INFO] Running on http://0.0.0.0:38043 (CTRL + C to quit)
localstack_1  | 2021-05-12T12:04:28:INFO:hypercorn.error: Running on http://0.0.0.0:38043 (CTRL + C to quit)
localstack_1  | Ready.
localstack_1  | 2021-05-12T12:04:34:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 6774.351119995117ms
```

## Client code

`Terraform ver.0.12.29` snippet:
```hcl
provider "aws" {
  region     = "eu-west-1"
  access_key = "mock_access_key"
  secret_key = "mock_secret_key"

  s3_force_path_style         = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    ec2 = "http://localhost:4566"
    iam = "http://localhost:4566"
    kms = "http://localhost:4566"
    sts = "http://localhost:4566"
  }
}

data "aws_caller_identity" "current" {}

data "aws_iam_account_alias" "current" {}
```

2. The error I faced from the local terminal running `terraform plan`:
```hcl
data.aws_caller_identity.current: Refreshing state...
data.aws_iam_account_alias.current: Refreshing state...

Error: Error getting Caller Identity: : 
        status code: 400, request id: 

  on main.tf line ...

Error: : 
        status code: 400, request id: 

```

In the meantime the errors appeared in the `localstack` Docker container logs:
```python
localstack_1  | 2021-05-12T12:07:37:WARNING:localstack.services.edge: Unable to find listener for service "iam" - please make sure to include it in $SERVICES
localstack_1  | 2021-05-12T12:07:37:WARNING:localstack.services.edge: Unable to find listener for service "sts" - please make sure to include it in $SERVICES
localstack_1  | 2021-05-12T12:07:37:WARNING:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7f54aeb839d0>(None) failed: Unable to find listener for service "iam" - please make sure to include it in $SERVICES Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 689, in run
localstack_1  |     result = self.func(self.params)
localstack_1  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack_1  |     return fn(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 352, in handler
localstack_1  |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 171, in modify_and_forward
localstack_1  |     listener_result = listener.forward_request(method=method,
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 118, in forward_request
localstack_1  |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 137, in do_forward_request
localstack_1  |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 151, in do_forward_request_inmem
localstack_1  |     raise HTTPErrorResponse(message, code=400)
localstack_1  | localstack.utils.server.http2_server.HTTPErrorResponse: Unable to find listener for service "iam" - please make sure to include it in $SERVICES
localstack_1  | 
localstack_1  | 2021-05-12T12:07:37:WARNING:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7f54aeb83dc0>(None) failed: Unable to find listener for service "sts" - please make sure to include it in $SERVICES Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 689, in run
localstack_1  |     result = self.func(self.params)
localstack_1  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack_1  |     return fn(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 352, in handler
localstack_1  |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 171, in modify_and_forward
localstack_1  |     listener_result = listener.forward_request(method=method,
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 118, in forward_request
localstack_1  |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 137, in do_forward_request
localstack_1  |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 151, in do_forward_request_inmem
localstack_1  |     raise HTTPErrorResponse(message, code=400)
localstack_1  | localstack.utils.server.http2_server.HTTPErrorResponse: Unable to find listener for service "sts" - please make sure to include it in $SERVICES
localstack_1  | 
localstack_1  | 2021-05-12T12:07:37:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: Unable to find listener for service "iam" - please make sure to include it in $SERVICES Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 129, in index
localstack_1  |     raise result
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 689, in run
localstack_1  |     result = self.func(self.params)
localstack_1  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack_1  |     return fn(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 352, in handler
localstack_1  |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 171, in modify_and_forward
localstack_1  |     listener_result = listener.forward_request(method=method,
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 118, in forward_request
localstack_1  |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 137, in do_forward_request
localstack_1  |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 151, in do_forward_request_inmem
localstack_1  |     raise HTTPErrorResponse(message, code=400)
localstack_1  | localstack.utils.server.http2_server.HTTPErrorResponse: Unable to find listener for service "iam" - please make sure to include it in $SERVICES
localstack_1  | 
localstack_1  | 2021-05-12T12:07:37:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: Unable to find listener for service "sts" - please make sure to include it in $SERVICES Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 129, in index
localstack_1  |     raise result
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 689, in run
localstack_1  |     result = self.func(self.params)
localstack_1  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack_1  |     return fn(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 352, in handler
localstack_1  |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 171, in modify_and_forward
localstack_1  |     listener_result = listener.forward_request(method=method,
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 118, in forward_request
localstack_1  |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 137, in do_forward_request
localstack_1  |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 151, in do_forward_request_inmem
localstack_1  |     raise HTTPErrorResponse(message, code=400)
localstack_1  | localstack.utils.server.http2_server.HTTPErrorResponse: Unable to find listener for service "sts" - please make sure to include it in $SERVICES
localstack_1  | 
```

## Workarounds
1. This works (no quotes around `SERVICES` string):
  ```yaml
  # docker-compose.yaml

  # ...

  localstack:
    environment:
      - SERVICES=iam,kms,ssm,sts
      # ...
  ```

2. And this works (additional commas):
  ```yaml
  # docker-compose.yaml

  # ...

  localstack:
    environment:
      - SERVICES=",iam,kms,ssm,sts,"
      # ...
  ```

**Comment by mgagliardo** [comment]
Hello @mikalai-t, I was able to reproduce but this is not a localstack issue, if you look at the YAML standard and even at the [docker compose environment](https://docs.docker.com/compose/environment-variables/) standard examples there are two ways of adding lists of dictionaries to a YAML file, being:

```
localstack:
  ...
  environment:
    - SERVICES=iam,kms,ssm,sts
```

Or:
```
localstack:
  ...
  environment:
    SERVICES: "ec2,iam,kms,ssm,sts"
```

No quotes needed on the first place as the yaml standard structure already recognizes it as a string, so when you run both of these examples you get:

```
localstack_1  | Starting mock EC2 service on http port 4566 ...
localstack_1  | Starting mock IAM service on http port 4566 ...
localstack_1  | Starting mock STS service on http port 4566 ...
localstack_1  | Starting mock KMS service on http port 4566 ...
```

Which shows the correct amount of services, so this in fact is not a localstack issue but a syntax issue.
Offtopic: If you are testing that terraform file you are missing the `ec2` service as you are calling it on line 12.
