### ISSUE TITLE
500 Error: PutObject to S3 bucket contains dots by virtual hosted-style endpoint

### ISSUE THREAD

**Issue by yh1224** [localstack/localstack#4025]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

- LocalStack 0.12.11
- AWS SDK for PHP 3.181.1
- Bucket name: `test.test`

# Steps to reproduce

 1. Prepare files.

    docker-compose.yml

    ```yml
    version: '3'
    services:
      localstack:
        image: localstack/localstack:0.12.11
        environment:
          - DEFAULT_REGION=ap-northeast-1
          - SERVICES=s3
          - DEBUG=1
        hostname: localstack
        networks:
          default:
            aliases:
              - s3.localhost.localstack.cloud
              - test.s3.localhost.localstack.cloud
              - test.test.s3.localhost.localstack.cloud
      main:
        build: .
        volumes:
          - ${HOME}/.aws:/root/.aws
        links:
          - localstack:localstack
    ```

    Dockerfile (Ubuntu + PHP + AWS CLI)

    ```dockerfile
    FROM ubuntu:20.04
    ENV DEBIAN_FRONTEND noninteractive
    RUN set -ex \
        && apt-get update \
        && apt-get upgrade \
        && apt-get install -y curl php-cli php-xml unzip
    RUN set -ex \
        && curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php \
        && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer \
        && rm -f /tmp/composer-setup.php
    RUN set -ex \
        && curl "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" -o /tmp/awscliv2.zip \
        && unzip -d /tmp /tmp/awscliv2.zip \
        && /tmp/aws/install \
        && rm -fr /tmp/aws /tmp/awscliv2.zip
    ```

 2. Run containers.

    ```shell
    docker-compose run main bash
    ```

 3. Create bucket containing dots.

    ```shell
    aws --endpoint=http://s3.localhost.localstack.cloud:4566 s3 mb s3://test.test
    ```

 4. Install AWS SDK for PHP.

    ```shell
    composer require aws/aws-sdk-php
    ```

 5. PutObject (by virtual hosted-style endpoint).

    ```php
    <?php
    require 'vendor/autoload.php';
    
    $s3 = new Aws\S3\S3Client([
        'version' => '2006-03-01',
        'region' => 'ap-northeast-1',
        'endpoint' => 'http://s3.localhost.localstack.cloud:4566',
    ]);
    $s3->putObject([
        'Bucket' => 'test.test',
        'Key' => 'test.txt',
        'Body' => 'Hello',
    ]);
    ```

Result

```
PHP Fatal error:  Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "PutObject" on "http://test.test.s3.localhost.localstack.cloud:4566/test.txt"; AWS HTTP error: Server error: `PUT http://test.test.s3.localhost.localstack.cloud:4566/test.txt` resulted in a `500 Internal Server Error` response:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><title>500 Internal Server Error</title><h1>Internal Server Error (truncated...)
 Unable to parse error information from response - Error parsing XML: String could not be parsed as XML'

GuzzleHttp\Exception\ServerException: Server error: `PUT http://test.test.s3.localhost.localstack.cloud:4566/test.txt` resulted in a `500 Internal Server Error` response:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><title>500 Internal Server Error</title><h1>Internal Server Error (truncated...)
 in /vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestExce in /vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 195
```

Stack trace of LocalStack

```
localstack_1  | 2021-05-14 12:27:41,099:API: 127.0.0.1 - - [14/May/2021 12:27:41] "PUT /test.txt HTTP/1.1" 500 -
localstack_1  | 2021-05-14 12:27:41,110:API: Error on request:
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
localstack_1  |     execute(self.server.app)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
localstack_1  |     application_iter = app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 177, in __call__
localstack_1  |     return backend_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
localstack_1  |     return self.wsgi_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
localstack_1  |     response = self.handle_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_1  |     raise value
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
localstack_1  |     response = self.full_dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
localstack_1  |     rv = self.handle_user_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
localstack_1  |     reraise(exc_type, exc_value, tb)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
localstack_1  |     raise value
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
localstack_1  |     rv = self.dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
localstack_1  |     return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 156, in __call__
localstack_1  |     result = self.callback(request, request.url, {})
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 256, in ambiguous_response
localstack_1  |     return self.bucket_response(request, full_url, headers)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 265, in bucket_response
localstack_1  |     response = self._bucket_response(request, full_url, headers)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 311, in _bucket_response
localstack_1  |     return self._bucket_response_put(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 773, in _bucket_response_put
localstack_1  |     if self._create_bucket_configuration_is_empty(body):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 645, in _create_bucket_configuration_is_empty
localstack_1  |     create_bucket_configuration = xmltodict.parse(body)[
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/xmltodict.py", line 327, in parse
localstack_1  |     parser.Parse(xml_input, True)
localstack_1  | xml.parsers.expat.ExpatError: syntax error: line 1, column 0
```

**Comment by macnev2013** [comment]
Thanks for reporting the issue @yh1224 .

If your bucket name is not DNS compatible, the bucket name cannot be part of the hostname and must be in the path - which requires `use_path_style_endpoint => true`.

Thanks.

[AWS Documentation: addressing_style](https://docs.aws.amazon.com/sdkref/latest/guide/setting-s3-addressing_style.html)
