### ISSUE TITLE
DATA_DIR and volume causes Elasticsearch Exception

### ISSUE THREAD

**Issue by Dgame** [localstack/localstack#4041]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

If I specify `DATA_DIR=/tmp/localstack/data` and in volumes `"./data:/tmp/localstack"` I get 
>[ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [e31e531003a6] uncaught exception in thread [main]\norg.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unable to access 'path.repo' (/tmp/localstack/es_backup)

# Steps to reproduce

## Command used to start LocalStack

Use the following docker-compose.yml
```yml
version: "3.7"

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "${LOCALSTACK_EDGE_PORT-4566}:4566"
      - "${LOCALSTACK_ELASTICSEARCH_PORT-4571}:4571"
    environment:
      - SERVICES=${LOCALSTACK_SERVICES- }
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=/tmp
    volumes:
      - "./data:/tmp/localstack"
```

and run `docker-compose up -d`. It works if I omit `DATA_DIR`.

**Comment by Dgame** [comment]
I may have to correct myself: I probably need to omit the volume AND `DATA_DIR`.

**Comment by mgagliardo** [comment]
Hello @Dgame, may I ask you for your directory structure? I was unable to reproduce this. 

My directory structure.

I've created a folder `/tmp/issue4041` and inside it put the `docker-compose.yml` file.
```
$ ls -l
total 8
drwxr-xr-x  9 miguelgagliardo  wheel  288 May 17 21:38 data
-rw-r--r--  1 miguelgagliardo  wheel  392 May 17 21:32 docker-compose.yml
drwxr-xr-x  2 miguelgagliardo  wheel   64 May 17 21:29 tmp
```

You can see the directory structure looks fine:
```
$ tree -d -L 2
.
├── data
│   ├── data
│   ├── elasticsearch
│   └── es_backup
└── tmp

5 directories
```

docker-compose.yml:
```
$ cat docker-compose.yml
version: "3.9"

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "${LOCALSTACK_EDGE_PORT-4566}:4566"
      - "${LOCALSTACK_ELASTICSEARCH_PORT-4571}:4571"
    environment:
      - SERVICES=es
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=/tmp
    volumes:
      - "./data:/tmp/localstack"
```

AWS ES seems to be starting normally:
```
localstack_main | Starting edge router (https port 4566)...
localstack_main | Starting mock ES service on http port 4566 ...
localstack_main | [2021-05-17 19:32:18 +0000] [22] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main | 2021-05-17T19:32:18:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main | Waiting for all LocalStack services to be ready
localstack_main | Ready.
localstack_main | 2021-05-17T19:32:23:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 5153.332948684692ms
localstack_main | 2021-05-17T19:32:41:INFO:localstack.services.es.es_api: Elasticsearch is starting for the first time, please wait..
localstack_main | 2021-05-17T19:32:41:INFO:localstack.services.install: Downloading and installing local Elasticsearch (7.7.0) server. This may take some time.
localstack_main | 2021-05-17T19:33:58:INFO:localstack.services.install: Installing Elasticsearch plugin analysis-icu
localstack_main | 2021-05-17T19:34:44:INFO:localstack.services.install: Installing Elasticsearch plugin ingest-attachment
localstack_main | 2021-05-17T19:35:56:INFO:localstack.services.install: Installing Elasticsearch plugin analysis-kuromoji
localstack_main | 2021-05-17T19:36:18:INFO:localstack.services.install: Installing Elasticsearch plugin mapper-murmur3
localstack_main | 2021-05-17T19:36:33:INFO:localstack.services.install: Installing Elasticsearch plugin mapper-size
localstack_main | 2021-05-17T19:36:48:INFO:localstack.services.install: Installing Elasticsearch plugin analysis-phonetic
localstack_main | 2021-05-17T19:37:04:INFO:localstack.services.install: Installing Elasticsearch plugin analysis-smartcn
localstack_main | 2021-05-17T19:37:24:INFO:localstack.services.install: Installing Elasticsearch plugin analysis-stempel
localstack_main | 2021-05-17T19:37:45:INFO:localstack.services.install: Installing Elasticsearch plugin analysis-ukrainian
localstack_main | [2021-05-17 19:38:10 +0000] [22] [INFO] Running on http://0.0.0.0:4571 (CTRL + C to quit)
localstack_main | 2021-05-17T19:38:10:INFO:hypercorn.error: Running on http://0.0.0.0:4571 (CTRL + C to quit)
```

```
$ awslocal es create-elasticsearch-domain --domain-name test
{
    "DomainStatus": {
        "DomainId": "000000000000/test",
        "DomainName": "test",
        "ARN": "arn:aws:es:us-east-1:000000000000:domain/test",
        "Created": true,
        "Deleted": false,
        "Endpoint": "http://localhost:4571",
        "Processing": false,
        "ElasticsearchVersion": "7.7",
        "ElasticsearchClusterConfig": {
            "InstanceType": "m3.medium.elasticsearch",
            "InstanceCount": 1,
            "DedicatedMasterEnabled": true,
            "ZoneAwarenessEnabled": false,
            "DedicatedMasterType": "m3.medium.elasticsearch",
            "DedicatedMasterCount": 1
        },
        "EBSOptions": {
            "EBSEnabled": true,
            "VolumeType": "gp2",
            "VolumeSize": 10,
            "Iops": 0
        },
        "CognitoOptions": {
            "Enabled": false
        }
    }
}

$ awslocal es list-domain-names
{
    "DomainNames": [
        {
            "DomainName": "test"
        }
    ]
}

$ curl http://localhost:4571/_cluster/health
{"cluster_name":"elasticsearch","status":"green","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":0,"active_shards":0,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0
```

**Comment by Dgame** [comment]
The structure looks like this:
```
$ ls -lsa
total 28
4 drwxr-xr-x 5 dgame dgame 4096 May 17 21:46 .
4 drwxr-xr-x 7 dgame dgame 4096 May 13 22:04 ..
4 drwxr-xr-x 4 dgame dgame 4096 May 17 21:13 data
4 -rw-r--r-- 1 dgame dgame  165 May 17 21:53 .env
4 drwxr-xr-x 3 dgame dgame 4096 May 11 21:40 aws
4 -rw-r--r-- 1 dgame dgame  489 May 17 21:49 docker-compose.yml
```

If I'm just restarting, I get A LOT of these errors:
>  Max retries exceeded with url: /_cluster/health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f96e5d47940>: Failed to establish a new connection: [Errno -3] Try again'))

But if I clean volumes and DATA_DIR and run `docker-compose stop` AND `docker-compose down -v` it works.

**Comment by mgagliardo** [comment]
Yes that is because elasticsearch is asynchronously brought up, you will see the `create-elasticsearch-domain` command response instantly, but on the background you can see localstack's logs bringing up the service.
As Elasticsearch is a pretty heavy workload you need to wait up for it to come up, it usually takes a few more minutes after the last plugin is up and running and you are seeing:
`localstack_main | 2021-05-17T19:38:10:INFO:hypercorn.error: Running on http://0.0.0.0:4571 (CTRL + C to quit)`

On the other hand, when you run elasticsearch for the first time there is a tarball download executed (corresponding to your chosen release version) and that is why on the 2nd try (if you bring down and up localstack) you will see it up "faster" or, if you did not remove the data directory you will see some inconsistent data on it.

**Comment by Dgame** [comment]
I will try to make it more reproducible when it happens again. But since I will be using an external ES cluster, I am not so worried that localstack will not persist my data.

**Comment by mgagliardo** [comment]
Hello @Dgame, just to let you know we created a guide for integrating localstack and ES, you can find it [here](https://github.com/localstack/localstack/blob/master/doc/external_services_integration/elasticsearch/HOWTO.md). Hope it helps you out. Cheers!

**Comment by Dgame** [comment]
Very nice, thank you very much for that. I really appreciate that.

**Comment by Dgame** [comment]
I did it again. I created a `.localstack/tmp` and a `.localstack/data` folder by running `sudo mkdir -p $PWD/.localstack/data` and `sudo mkdir -p $PWD/.localstack/tmp` and I made sure both have full access by running `sudo chmod 777 -R $PWD/.localstack`.  My `docker-compose.yml` file looks like this:

```yml
version: "3.7"

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    ports:
      - "${LOCALSTACK_EDGE_PORT-4566}:4566"
      - "${LOCALSTACK_ELASTICSEARCH_PORT-4571}:4571"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/.localstack/tmp
      - SERVICES=es
      - DATA_DIR=/.localstack/data
      - DEBUG=${DEBUG- }
    volumes:
      - "/.localstack/tmp:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - elastic-net

networks:
  elastic-net:
    name: elastic-net
    driver: bridge
```

After executing `docker-compose up -d` and executing
```sh
aws --endpoint-url http://127.0.0.1:4566 es create-elasticsearch-domain --domain-name es_local
```

I got this:
```
2021-05-23T11:21:11:INFO:localstack.services.install: Downloading and installing local Elasticsearch (7.7.0) server. This may take some time.

2021-05-23T11:21:11:INFO:localstack.services.es.es_api: Elasticsearch is starting for the first time, please wait..

2021-05-23T11:21:51:INFO:localstack.services.install: Installing Elasticsearch plugin analysis-icu

2021-05-23T11:21:59:INFO:localstack.services.install: Installing Elasticsearch plugin ingest-attachment

2021-05-23T11:22:06:INFO:localstack.services.install: Installing Elasticsearch plugin analysis-kuromoji

2021-05-23T11:22:11:INFO:localstack.services.install: Installing Elasticsearch plugin mapper-murmur3

2021-05-23T11:22:15:INFO:localstack.services.install: Installing Elasticsearch plugin mapper-size

2021-05-23T11:22:19:INFO:localstack.services.install: Installing Elasticsearch plugin analysis-phonetic

2021-05-23T11:22:24:INFO:localstack.services.install: Installing Elasticsearch plugin analysis-smartcn

2021-05-23T11:22:28:INFO:localstack.services.install: Installing Elasticsearch plugin analysis-stempel

2021-05-23T11:22:33:INFO:localstack.services.install: Installing Elasticsearch plugin analysis-ukrainian

[2021-05-23 11:22:38 +0000] [23] [INFO] Running on http://0.0.0.0:4571 (CTRL + C to quit)

2021-05-23T11:22:38:INFO:hypercorn.error: Running on http://0.0.0.0:4571 (CTRL + C to quit)

ERROR: 'su localstack -c '/tmp/localstack/elasticsearch/7.7.0/bin/elasticsearch -E http.port=46013 -E http.publish_port=46013 -E http.compression=false -E path.data=/.localstack/data/elasticsearch -E path.repo=/tmp/localstack/es_backup -E xpack.ml.enabled=false'': exit code 1; output: b"OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.\n[2021-05-23T11:22:40,619][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [5498b08c1836] uncaught exception in thread [main]\norg.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unable to access 'path.repo' (/tmp/localstack/es_backup)\n\tat org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) ~[elasticsearch-cli-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.7.0.jar:7.7.0]\nCaused by: java.lang.IllegalStateException: Unable to access 'path.repo' (/tmp/localstack/es_backup)\n\tat org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:70) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:313) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.bootstrap.Security.createPermissions(Security.java:252) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.bootstrap.Security.configure(Security.java:121) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:222) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.7.0.jar:7.7.0]\n\t... 6 more\nCaused by: java.nio.file.AccessDeniedException: /tmp/localstack/es_backup\n\tat sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]\n\tat sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]\n\tat sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]\n\tat sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source) ~[?:?]\n\tat java.nio.file.Files.createDirectory(Unknown Source) ~[?:?]\n\tat java.nio.file.Files.createAndCheckIsDirectory(Unknown Source) ~[?:?]\n\tat java.nio.file.Files.createDirectories(Unknown Source) ~[?:?]\n\tat org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:389) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:68) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:313) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.bootstrap.Security.createPermissions(Security.java:252) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.bootstrap.Security.configure(Security.java:121) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:222) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.7.0.jar:7.7.0]\n\tat org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.7.0.jar:7.7.0]\n\t... 6 more\nuncaught exception in thread [main]\njava.lang.IllegalStateException: Unable to access 'path.repo' (/tmp/localstack/es_backup)\nLikely root cause: java.nio.file.AccessDeniedException: /tmp/localstack/es_backup\n\tat java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)\n\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)\n\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)\n\tat java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source)\n\tat java.base/java.nio.file.Files.createDirectory(Unknown Source)\n\tat java.base/java.nio.file.Files.createAndCheckIsDirectory(Unknown Source)\n\tat java.base/java.nio.file.Files.createDirectories(Unknown Source)\n\tat org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:389)\n\tat org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:68)\n\tat org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:313)\n\tat org.elasticsearch.bootstrap.Security.createPermissions(Security.java:252)\n\tat org.elasticsearch.bootstrap.Security.configure(Security.java:121)\n\tat org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:222)\n\tat org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)\n\tat org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)\n\tat org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)\n\tat org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)\n\tat org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)\n\tat org.elasticsearch.cli.Command.main(Command.java:90)\n\tat org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)\n\tat org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)\nFor complete error details, refer to the log at /tmp/localstack/elasticsearch/7.7.0/logs/elasticsearch.log\n"

2021-05-23T11:22:40:WARNING:bootstrap.py: Thread run method <function create_domain.<locals>.do_start at 0x7f65cc669f70>(None) failed: Command 'su localstack -c '/tmp/localstack/elasticsearch/7.7.0/bin/elasticsearch -E http.port=46013 -E http.publish_port=46013 -E http.compression=false -E path.data=/.localstack/data/elasticsearch -E path.repo=/tmp/localstack/es_backup -E xpack.ml.enabled=false'' returned non-zero exit status 1. Traceback (most recent call last):

File "/opt/code/localstack/localstack/utils/bootstrap.py", line 695, in run

result = self.func(self.params, **kwargs)

File "/opt/code/localstack/localstack/services/es/es_api.py", line 250, in do_start

start_elasticsearch_instance(version=version)

File "/opt/code/localstack/localstack/services/es/es_api.py", line 219, in start_elasticsearch_instance

es_starter.start_elasticsearch(asynchronous=False, version=install_version)

File "/opt/code/localstack/localstack/services/es/es_starter.py", line 82, in start_elasticsearch

thread = do_run(cmd, asynchronous, env_vars=env_vars)

File "/opt/code/localstack/localstack/services/infra.py", line 249, in do_run

return run(cmd, env_vars=env_vars)

File "/opt/code/localstack/localstack/utils/common.py", line 1428, in run

return do_run(cmd)

File "/opt/code/localstack/localstack/utils/common.py", line 1425, in do_run

return bootstrap.run(cmd, **kwargs)

File "/opt/code/localstack/localstack/utils/bootstrap.py", line 775, in run

raise e

File "/opt/code/localstack/localstack/utils/bootstrap.py", line 735, in run

output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)

File "/usr/lib/python3.8/subprocess.py", line 411, in check_output

return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,

File "/usr/lib/python3.8/subprocess.py", line 512, in run

raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command 'su localstack -c '/tmp/localstack/elasticsearch/7.7.0/bin/elasticsearch -E http.port=46013 -E http.publish_port=46013 -E http.compression=false -E path.data=/.localstack/data/elasticsearch -E path.repo=/tmp/localstack/es_backup -E xpack.ml.enabled=false'' returned non-zero exit status 1.
```

**Comment by Dgame** [comment]
@mgagliardo I'm not able to reopen the issue, but perhaps you can reproduce it with the information provided.

**Comment by mgagliardo** [comment]
Hello @Dgame, I think you are using the `DATA_DIR` parameter the wrong way, also the `HOST_TMP_FOLDER` is not needed in this case.

```
version: "3.7"

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    ports:
      - "${LOCALSTACK_EDGE_PORT-4566}:4566"
      - "${LOCALSTACK_ELASTICSEARCH_PORT-4571}:4571"
    environment:
      - DEBUG=1
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - elastic-net

networks:
  elastic-net:
    name: elastic-net
    driver: bridge
```

This should work. Let me know how it goes for you.

```
$ ls -la /tmp/localstack/data/elasticsearch/nodes/0/
total 0
drwxr-xr-x  4 miguelgagliardo  wheel  128 May 25 10:19 .
drwxr-xr-x  3 miguelgagliardo  wheel   96 May 25 10:19 ..
drwxr-xr-x  9 miguelgagliardo  wheel  288 May 25 10:19 _state
-rw-r--r--  1 miguelgagliardo  wheel    0 May 25 10:19 node.lock
```

**Comment by Dgame** [comment]
@mgagliardo Thanks for your reply, I will try that as soon as possible. But if I understand you correctly: if I want to use a local storage path inside my repository, it should be enough to adjust the volume from `- "/tmp/localstack:/tmp/localstack"` to `- "/.localstack:/tmp/localstack"'`, right?

**Comment by mgagliardo** [comment]
That is correct, please note `/.localstack` is a path to your host's root filesystem and a folder in there called `.localstack`

Here's another working example I am using, with a folder `/tmp/test/localstack`.

```
version: "3.9"

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    ports:
      - "${LOCALSTACK_EDGE_PORT-4566}:4566"
      - "${LOCALSTACK_ELASTICSEARCH_PORT-4571}:4571"
    environment:
      - DEBUG=1
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/test/localstack/data
      - HOST_TMP_FOLDER=/tmp/test/localstack
    volumes:
      - "/tmp/test/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - elastic-net

networks:
  elastic-net:
    name: elastic-net
    driver: bridge
```

**Comment by Dgame** [comment]
So `DATA_DIR` is referring to my host system and it is a subfolder inside of `HOST_TMP_FOLDER`, yes? If so, I think `HOST_DATA_DIR` would be more intuitive, as it confused me quite a bit. :D What if I want to store the data in my repository in the `.localstack` folder? Do I need to specify `HOST_TMP_FOLDER`? Would the following `docker-compose.yml` be valid?

```yml
version: "3.9"

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    ports:
      - "${LOCALSTACK_EDGE_PORT-4566}:4566"
      - "${LOCALSTACK_ELASTICSEARCH_PORT-4571}:4571"
    environment:
      - DEBUG=1
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=.localstack/data
    volumes:
      - ".localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - elastic-net

networks:
  elastic-net:
    name: elastic-net
    driver: bridge
```

**Comment by mgagliardo** [comment]
No, you don't need `HOST_TMP_FOLDER` unless you are using a lambda specific onfig, as the doc states.

Yes, that config should be valid (have not tested it though) but `I strongly recommend` not using relative paths, you can mitigate that with `$PWD` or full paths for example.

**Comment by Dgame** [comment]
Thank you for the explanation :)

**Comment by Dgame** [comment]
@mgagliardo It worked! Thank you for your patience and help! Actually, if I could put the records in the Firehose stream now, I would explode from happiness 😄
