### ISSUE TITLE
Lambda python handler path cannot use dot notation on deeply-nested modules

### ISSUE THREAD

**Issue by benjyw** [localstack/localstack#405]
AWS Lambda allows (at least a python) handler in a deeply-nested modules to be specified with dotted notation. E.g.,`foo.bar.baz.handler`, where `handler` is a method in `foo/bar/baz.py`.

However localstack fails on `awslocal lambda create-function` with "Unable to find handler script in Lambda archive." unless the handler is in a top-level module (e.g., `foo.handler`, where `handler` is a method in `foo.py`.

As a workaround,`foo/bar/baz.handler` works on both localstack and AWS. But this seems inelegant, as that notation isn't meaningful anywhere else in pythonland.

Suggestion: 

The `split` stanza at the following line:

https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_api.py#L392

Could be changed to something like:

`handler_name.rpartition('.')[0].replace('.', '/')`

although I'm not sure if that logic is apropos for JavaScript or not.

**Comment by whummer** [comment]
Thanks for reporting @benjyw . I also believe that your suggested approach should work. Would you be able to create a pull request?

We could change or extend our integration tests to run an example with a nested module handler:
https://github.com/localstack/localstack/blob/master/tests/integration/test_lambda.py#L70-L71

We can for example pass in a new parameter to `create_lambda_archive` in `testutil.py`:
https://github.com/localstack/localstack/blob/master/localstack/utils/testutil.py#L51-L74

**Comment by benjyw** [comment]
Happy to, but alas I couldn't get the tests to pass in a clean client (on MacOS), at bd92399b8c4b. Got:

```
............FE..........Shutdown
.........................
======================================================================
ERROR: tests.integration.test_integration.test_kinesis_lambda_forward_chain
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/benjyw/src/localstack/.venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/benjyw/src/localstack/tests/integration/test_integration.py", line 214, in test_kinesis_lambda_forward_chain
    testutil.assert_objects(test_data, all_objects)
  File "/Users/benjyw/src/localstack/localstack/utils/testutil.py", line 131, in assert_objects
    assert_object(obj, all_objects)
  File "/Users/benjyw/src/localstack/localstack/utils/testutil.py", line 144, in assert_object
    raise Exception('Expected object not found: %s in list %s' % (expected_object, all_objects))
Exception: Expected object not found: {'test_data': 'forward_chain_data_7ae4770b'} in list [{u'test': u'firehose_data_f25c27e9'}]

======================================================================
FAIL: tests.integration.test_integration.test_kinesis_lambda_sns_ddb_streams
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/benjyw/src/localstack/.venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/benjyw/src/localstack/tests/integration/test_integration.py", line 178, in test_kinesis_lambda_sns_ddb_streams
    retry(check_events, retries=7, sleep=3)
  File "/Users/benjyw/src/localstack/localstack/utils/common.py", line 270, in retry
    raise raise_error
AssertionError: 
```

**Comment by whummer** [comment]
That might be a timing issue, although I can't recall having seen this error before. Can you try running the tests with `DEBUG` flag enabled and post any relevant output please.
```
DEBUG=1 make test
```

**Comment by benjyw** [comment]
Error happens consistently, but I see nothing relevant in the DEBUG output. 

The lines near the occurrence of the error are:

```
27.0.0.1 - - [16/Oct/2017 16:35:52] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:35:52] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:35:53] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:35:53] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:35:53] "POST / HTTP/1.1" 200 -
F127.0.0.1 - - [16/Oct/2017 16:36:29] "PUT /test_bucket HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:36:35] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:36:35] "GET /test_bucket?encoding-type=url HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:36:35] "HEAD /test_bucket//testdata8c94e1a6-b6f1-4259-b810-cbc3b9a631db HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:36:35] "GET /test_bucket//testdata8c94e1a6-b6f1-4259-b810-cbc3b9a631db HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:36:35] "GET /cf-test-bucket-1?encoding-type=url HTTP/1.1" 200 -
E127.0.0.1 - - [16/Oct/2017 16:36:36] "PUT /test_bucket_lambda HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:36:36] "PUT /test_bucket_lambda/test_lambda.zip HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:36:36] "HEAD /test_bucket_lambda/test_lambda.zip HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:36:36] "GET /test_bucket_lambda/test_lambda.zip HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:36:36] "POST / HTTP/1.1" 200 -
.127.0.0.1 - - [16/Oct/2017 16:36:37] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:36:37] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:36:37] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:36:38] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Oct/2017 16:36:38] "POST / HTTP/1.1" 200 -
.127.0.0.1 - - [16/Oct/2017 16:36:39] "POST / HTTP/1.1" 200 -
```

**Comment by whummer** [comment]
Maybe there are still some leftover processes that have not been terminated properly from a previous run?
```
ps aux | grep localstack
```

**Comment by benjyw** [comment]
Nope!

**Comment by benjyw** [comment]
Let me see if it happens at the most recent release.

**Comment by benjyw** [comment]
At 27b4ec690382c2b3c9d7c2858f4b41c2662389d7 (release 0.8.1) I get a different error:

```
FAIL: tests.integration.test_lambda.test_lambda_runtimes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/benjyw/src/localstack/.venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/benjyw/src/localstack/tests/integration/test_lambda.py", line 99, in test_lambda_runtimes
    assert to_str(result_data).strip() == '{}'
AssertionError
```

**Comment by whummer** [comment]
Closing as outdated / obsolete. Please create a follow-up issue if the problem persists.
