### ISSUE TITLE
Lambda function name clashing for similar names

### ISSUE THREAD

**Issue by pandomic** [localstack/localstack#4050]
# Type of request: This is a ...

- [x] bug report
- [ ] feature request

# Detailed description

For some reason, lambda functions with similar names are not getting deployed properly. This behaviour is at least reproducible using serverless and serverless-localstack. I haven't dive into details yet, but it could be we are using some sort of matching somewhere which assumes lambda with a similar name is already deployed. In the example below I have `lambda_getDocuments` and `lambda_getDocument` where the second one is not getting deployed.

In the given sample project it is possible to rerun deployment to "fix" the issue, but in a real project with a bit more functions, resources and subscriptions this trick does not work.

## Expected behavior

The serverless stack is deployed normally.

## Actual behavior

Thes serverless stack fails due to a missing lambda function that didn't get deployed.

```
localstack_1           | Ready.
localstack_1           | 2021-05-19T10:21:30:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 14668.55001449585ms
localstack_1           | 2021-05-19T10:22:03:DEBUG:localstack.services.cloudformation.cloudformation_api: Creating stack "sample-service-local" with 2 resources ...
localstack_1           | 2021-05-19T10:22:03:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "ServerlessDeploymentBucket" (1/4) type "AWS::S3::Bucket" in loop iteration 1
localstack_1           | 2021-05-19T10:22:03:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "S3::Bucket" id "ServerlessDeploymentBucket"
localstack_1           | 2021-05-19T10:22:03:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "S3::Bucket" in region eu-central-1: create_bucket {'Bucket': 'sample-service-local-serverlessdeploymentbucket-b0f3bfb3', 'ACL': 'public-read', 'CreateBucketConfiguration': {'LocationConstraint': 'eu-central-1'}}
localstack_1           | 2021-05-19T10:22:04:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "ServerlessDeploymentBucketPolicy" (1/3) type "AWS::S3::BucketPolicy" in loop iteration 1
localstack_1           | 2021-05-19T10:22:04:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "S3::BucketPolicy" id "ServerlessDeploymentBucketPolicy"
localstack_1           | 2021-05-19T10:22:04:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "S3::BucketPolicy" in region eu-central-1: put_bucket_policy {'Bucket': 'sample-service-local-serverlessdeploymentbucket-b0f3bfb3', 'Policy': '{"Statement": [{"Action": "s3:*", "Effect": "Deny", "Principal": "*", "Resource": ["arn:aws:s3:::sample-service-local-serverlessdeploymentbucket-b0f3bfb3/*", "arn:aws:s3:::sample-service-local-serverlessdeploymentbucket-b0f3bfb3"], "Condition": {"Bool": {"aws:SecureTransport": false}}}]}'}
localstack_1           | 2021-05-19T10:22:04:DEBUG:localstack.utils.cloudformation.template_deployer: Action "update" not yet implemented for CF resource type AWS::S3::Bucket
localstack_1           | 2021-05-19T10:22:04:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Modify" for resource "ServerlessDeploymentBucket" (1/2) type "AWS::S3::Bucket" in loop iteration 1
localstack_1           | 2021-05-19T10:22:04:DEBUG:localstack.utils.cloudformation.template_deployer: Action "update" not yet implemented for CF resource type AWS::S3::BucketPolicy
localstack_1           | 2021-05-19T10:22:04:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Modify" for resource "ServerlessDeploymentBucketPolicy" (1/1) type "AWS::S3::BucketPolicy" in loop iteration 1
localstack_1           | 2021-05-19T10:22:08:DEBUG:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:eu-central-1:000000000000:function:sample-service-local-lambda_getDocuments
localstack_1           | 2021-05-19T10:22:08:DEBUG:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:eu-central-1:000000000000:function:sample-service-local-lambda_getDocument
localstack_1           | 2021-05-19T10:22:09:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "LambdaUnderscoregetDocumentsLogGroup" (1/9) type "AWS::Logs::LogGroup" in loop iteration 1
localstack_1           | 2021-05-19T10:22:09:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "Logs::LogGroup" id "LambdaUnderscoregetDocumentsLogGroup"
localstack_1           | 2021-05-19T10:22:09:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "Logs::LogGroup" in region eu-central-1: create_log_group {'logGroupName': '/aws/lambda/sample-service-local-lambda_getDocuments'}
localstack_1           | 2021-05-19T10:22:09:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "LambdaUnderscoregetDocumentLogGroup" (1/8) type "AWS::Logs::LogGroup" in loop iteration 1
localstack_1           | 2021-05-19T10:22:09:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "Logs::LogGroup" id "LambdaUnderscoregetDocumentLogGroup"
localstack_1           | 2021-05-19T10:22:09:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "Logs::LogGroup" in region eu-central-1: create_log_group {'logGroupName': '/aws/lambda/sample-service-local-lambda_getDocument'}
localstack_1           | 2021-05-19T10:22:09:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "IamRoleLambdaExecution" (1/7) type "AWS::IAM::Role" in loop iteration 1
localstack_1           | 2021-05-19T10:22:09:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "IAM::Role" id "IamRoleLambdaExecution"
localstack_1           | 2021-05-19T10:22:09:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "IAM::Role" in region eu-central-1: create_role {'AssumeRolePolicyDocument': '{"Version": "2012-10-17", "Statement": [{"Effect": "Allow", "Principal": {"Service": ["lambda.amazonaws.com"]}, "Action": ["sts:AssumeRole"]}]}', 'Path': '/', 'RoleName': 'sample-service-local-eu-central-1-lambdaRole'}
localstack_1           | 2021-05-19T10:22:09:DEBUG:localstack.utils.cloudformation.template_deployer: Running put_role_policy(...) for IAM::Role policy: sample-service-local-eu-central-1-lambdaRole sample-service-local-lambda {"Version": "2012-10-17", "Statement": [{"Effect": "Allow", "Action": ["logs:CreateLogStream", "logs:CreateLogGroup"], "Resource": ["arn:aws:logs:eu-central-1:000000000000:log-group:/aws/lambda/sample-service-local*:*"]}, {"Effect": "Allow", "Action": ["logs:PutLogEvents"], "Resource": ["arn:aws:logs:eu-central-1:000000000000:log-group:/aws/lambda/sample-service-local*:*:*"]}]}
localstack_1           | 2021-05-19T10:22:09:DEBUG:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:eu-central-1:000000000000:function:sample-service-local-lambda_getDocuments
localstack_1           | 2021-05-19T10:22:09:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "LambdaUnderscoregetDocumentsLambdaFunction" (1/6) type "AWS::Lambda::Function" in loop iteration 1
localstack_1           | 2021-05-19T10:22:09:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "Lambda::Function" id "LambdaUnderscoregetDocumentsLambdaFunction"
localstack_1           | 2021-05-19T10:22:09:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "Lambda::Function" in region eu-central-1: create_function {'FunctionName': 'sample-service-local-lambda_getDocuments', 'Runtime': 'nodejs12.x', 'Role': 'arn:aws:iam::000000000000:role/sample-service-local-eu-central-1-lambdaRole', 'Handler': 'src/events/lambda/documents.getDocuments', 'Code': {'S3Bucket': '__local__', 'S3Key': '/Volumes/Seagate/work/localstack/sample-project'}, 'Timeout': 6, 'MemorySize': 1024}
localstack_1           | 2021-05-19T10:22:09:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "LambdaUnderscoregetDocumentLambdaFunction" (1/5) type "AWS::Lambda::Function" in loop iteration 1
localstack_1           | 2021-05-19T10:22:10:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "LambdaUnderscoregetDocumentsLambdaVersion8hwT26XuHjIII4Ybi7pvLw0pkhShE0E3GTIiQYmCEY" (1/4) type "AWS::Lambda::Version" in loop iteration 1
localstack_1           | 2021-05-19T10:22:10:DEBUG:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:eu-central-1:000000000000:function:sample-service-local-lambda_getDocument
localstack_1           | 2021-05-19T10:22:10:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "LambdaUnderscoregetDocumentLambdaVersion6eigRLkyAOQQd0SPKi3plwUV4EsT0lNGot9vA" (1/3) type "AWS::Lambda::Version" in loop iteration 1
localstack_1           | 2021-05-19T10:22:10:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "Lambda::Version" id "LambdaUnderscoregetDocumentLambdaVersion6eigRLkyAOQQd0SPKi3plwUV4EsT0lNGot9vA"
localstack_1           | 2021-05-19T10:22:10:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "Lambda::Version" in region eu-central-1: publish_version {'FunctionName': 'sample-service-local-lambda_getDocument', 'CodeSha256': '2nnq7zwS9x96TiUYYJ4Tf90WPBUwWEXRIQkXZQSHGyc='}
localstack_1           | 2021-05-19T10:22:10:DEBUG:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:eu-central-1:000000000000:function:sample-service-local-lambda_getDocument
localstack_1           | 2021-05-19T10:22:10:WARNING:localstack.utils.cloudformation.template_deployer: Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.Lambda object at 0x7f4cf2c56550>> with params: {'FunctionName': 'sample-service-local-lambda_getDocument', 'CodeSha256': '2nnq7zwS9x96TiUYYJ4Tf90WPBUwWEXRIQkXZQSHGyc='} for resource: {'Type': 'AWS::Lambda::Version', 'DeletionPolicy': 'Retain', 'LogicalResourceId': 'LambdaUnderscoregetDocumentLambdaVersion6eigRLkyAOQQd0SPKi3plwUV4EsT0lNGot9vA', 'Properties': {'FunctionName': 'sample-service-local-lambda_getDocument', 'CodeSha256': '2nnq7zwS9x96TiUYYJ4Tf90WPBUwWEXRIQkXZQSHGyc='}, '_state_': {}}
localstack_1           | 2021-05-19T10:22:10:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "sample-service-local": An error occurred (ResourceNotFoundException) when calling the PublishVersion operation: Function not found: arn:aws:lambda:eu-central-1:000000000000:function:sample-service-local-lambda_getDocument Traceback (most recent call last):
localstack_1           |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1816, in _run
localstack_1           |     self.do_apply_changes_in_loop(changes, stack, stack_name)
localstack_1           |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1867, in do_apply_changes_in_loop
localstack_1           |     self.apply_change(change, stack, new_resources, stack_name=stack_name)
localstack_1           |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1920, in apply_change
localstack_1           |     result = deploy_resource(resource_id, new_resources, stack_name)
localstack_1           |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 933, in deploy_resource
localstack_1           |     return execute_resource_action(resource_id, resources, stack_name, ACTION_CREATE)
localstack_1           |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1037, in execute_resource_action
localstack_1           |     result = configure_resource_via_sdk(resource_id, resources, resource_type, func, stack_name, action_name)
localstack_1           |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1158, in configure_resource_via_sdk
localstack_1           |     raise e
localstack_1           |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1153, in configure_resource_via_sdk
localstack_1           |     result = function(**params)
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
localstack_1           |     return self._make_api_call(operation_name, kwargs)
localstack_1           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
localstack_1           |     raise error_class(parsed_response, operation_name)
localstack_1           | botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the PublishVersion operation: Function not found: arn:aws:lambda:eu-central-1:000000000000:function:sample-service-local-lambda_getDocument
```

# Steps to reproduce

1. Create a new folder and `cd` into it
2. Create the following `package.json`
```JSON
{
  "name": "sample-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "deploy": "serverless deploy"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "serverless": "^2.41.2",
    "serverless-localstack": "^0.4.32"
  }
}
```
3. Create the following `serverless.yml`:
```yml
service: sample-service

custom:
  defaultStage: local
  localstack:
    debug: true
    stages:
      - local
    lambda:
      mountCode: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage, self:custom.defaultStage}

plugins:
  - serverless-localstack

functions:
  lambda_getDocuments:
    handler: src/events/lambda/documents.getDocuments
  lambda_getDocument:
    handler: src/events/lambda/documents.getDocument
```
4. Add a standard `docker-compose.yml`:
```yml
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
5. Install deps & try to deploy the stack
```bash
npm install
npm run deploy -- --stage local
```

## Command used to start LocalStack

```bash
docker compose up
or
docker-compose up
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Haven't tried with pure awslocal or aws-sdk

**Comment by pandomic** [comment]
@whummer I was able to "fix" the issue by reordering lambda functions so that the shorter name goes before the longer one. Not sure if want to close the issue or keep it in low prior, wdyt?

**Comment by djoe1** [comment]
Keep it open.  I just ran into this myself.
