### ISSUE TITLE
EventBridge put-events failure

### ISSUE THREAD

**Issue by svenlito** [localstack/localstack#4053]
# Type of request: This is a bug report

[x] bug report
[ ] feature request

# Detailed description

put-events call against a bus that has policy attached fails

## Expected behavior

event is being accepted.

## Actual behavior

localstack error:

```sh
localstack         |     if rule_information.event_pattern._filter:
localstack         | AttributeError: 'str' object has no attribute '_filter'
localstack         | 2021-05-20 06:48:16,226:API: Error on request:
localstack         | Traceback (most recent call last):
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 319, in run_wsgi
localstack         |     execute(self.server.app)
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 308, in execute
localstack         |     application_iter = app(environ, start_response)
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 178, in __call__
localstack         |     return backend_app(environ, start_response)
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2069, in __call__
localstack         |     return self.wsgi_app(environ, start_response)
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2054, in wsgi_app
localstack         |     response = self.handle_exception(e)
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack         |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack         |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
localstack         |     response = self.full_dispatch_request()
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
localstack         |     rv = self.handle_user_exception(e)
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack         |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack         |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
localstack         |     rv = self.dispatch_request()
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request
localstack         |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 156, in __call__
localstack         |     result = self.callback(request, request.url, {})
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 205, in dispatch
localstack         |     return cls()._dispatch(*args, **kwargs)
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 315, in _dispatch
localstack         |     return self.call_action()
localstack         |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 405, in call_action
localstack         |     response = method()
localstack         |   File "/opt/code/localstack/localstack/services/events/events_starter.py", line 217, in events_handler_put_events
localstack         |     if filter_event_based_on_event_format(self, rule, formatted_event):
localstack         |   File "/opt/code/localstack/localstack/services/events/events_starter.py", line 113, in filter_event_based_on_event_format

```

# Steps to reproduce

## Command used to start LocalStack

- create event bus
- attach permissions
- put-events

```sh
➔ awslocal events list-event-buses | jq .
{
  "EventBuses": [
    {
      "Name": "default",
      "Arn": "arn:aws:events:ap-southeast-1:000000000000:event-bus/default"
    },
    {
      "Name": "products",
      "Arn": "arn:aws:events:ap-southeast-1:000000000000:event-bus/products",
      "Policy": "{\"Version\": \"2012-10-17\", \"Statement\": [{\"Sid\": \"master-account\", \"Effect\": \"Allow\", \"Principal\": {\"AWS\": \"arn:aws:iam::000000000000:root\"}, \"Action\": \"events:PutEvents\", \"Resource\": \"arn:aws:events:ap-southeast-1:000000000000:event-bus/products\"}]}"
    }
  ]
}
```

```sh
➔ awslocal events put-events --entries '[{"DetailType": "xxxx", "Source": "xxxxxx", "Detail": "{ }", "EventBusName": "products"}]'

An error occurred (500) when calling the PutEvents operation (reached max retries: 2): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

**Comment by usmangani1** [comment]
@svenlito Thanks for reporting the issue. Can you please let us know which version of localstack are you using ?

**Comment by svenlito** [comment]
@usmangani1 Sure, I'm currently running what's tagged as `latest`.

**Comment by usmangani1** [comment]
@svenlito Thanks for the info. Could you give us the sequence of cli commands using which you are trying exactly ?

**Comment by usmangani1** [comment]
@svenlito Please share the sequence of commands in which you are facing the issue. Thanks
