### ISSUE TITLE
Amazon KCL Consumer RetryableRetrievalException: ReadTimeout when using LocalStack

### ISSUE THREAD

**Issue by cjgordon** [localstack/localstack#4063]
[X ] bug report
[ ] feature request

# Detailed description
Trying to use localstack to create test environment for a Kinesis stream with a consumer that uses Amazon KCL v2 and Python.

My producer is happily able to put records to LocalStack Kinesis stream and the consumer is able to start and process the first couple of records before it fails. Worth noting that the same consumer works correctly with real Kinesis stream.

## Expected behavior
Amazon KCL consumer will start and process records until such time as it is stopped.

## Actual behavior
After processing the first couple of records it fails with error:
### Consumer Output
```
2021-05-23 05:38:11,174 [main] INFO  s.a.k.l.d.DynamoDBLeaseCoordinator [NONE] - With failover time 10000 ms and epsilon 25 ms, LeaseCoordinator will renew leases every 3308 ms, takeleases every 20050 ms, process maximum of 2147483647 leases and steal 1 lease(s) at a time. 
2021-05-23 05:38:11,179 [multi-lang-daemon-0000] INFO  s.a.kinesis.coordinator.Scheduler [NONE] - Initialization attempt 1 
2021-05-23 05:38:11,180 [multi-lang-daemon-0000] INFO  s.a.kinesis.coordinator.Scheduler [NONE] - Initializing LeaseCoordinator 
2021-05-23 05:38:12,744 [multi-lang-daemon-0000] INFO  s.a.kinesis.coordinator.Scheduler [NONE] - Syncing Kinesis shard info 
2021-05-23 05:38:12,987 [multi-lang-daemon-0000] INFO  s.a.kinesis.coordinator.Scheduler [NONE] - Starting LeaseCoordinator 
2021-05-23 05:38:23,027 [multi-lang-daemon-0000] INFO  s.a.kinesis.coordinator.Scheduler [NONE] - Initialization complete. Starting worker loop. 
2021-05-23 05:38:33,149 [LeaseCoordinator-0000] INFO  s.a.k.l.dynamodb.DynamoDBLeaseTaker [NONE] - Worker f911359d-0b91-4f48-9e16-e06ded03651c saw 1 total leases, 1 available leases, 1 workers. Target is 1 leases, I have 0 leases, I will take 1 leases 
2021-05-23 05:38:33,271 [LeaseCoordinator-0000] INFO  s.a.k.l.dynamodb.DynamoDBLeaseTaker [NONE] - Worker f911359d-0b91-4f48-9e16-e06ded03651c successfully took 1 leases: shardId-000000000000 
2021-05-23 05:38:34,177 [multi-lang-daemon-0000] INFO  s.a.k.r.f.FanOutConsumerRegistration [NONE] - StreamConsumer not found, need to create it. 
2021-05-23 05:38:34,236 [multi-lang-daemon-0000] INFO  s.a.kinesis.coordinator.Scheduler [NONE] - Created new shardConsumer for : ShardInfo(shardId=shardId-000000000000, concurrencyToken=b805d0aa-beda-4908-be90-e094648c1e25, parentShardIds=[], checkpoint={SequenceNumber: TRIM_HORIZON,SubsequenceNumber: 0}) 
2021-05-23 05:38:34,238 [ShardRecordProcessor-0000] INFO  s.a.k.l.BlockOnParentShardTask [NONE] - No need to block on parents [] of shard shardId-000000000000 
2021-05-23 05:38:35,342 [multi-lang-daemon-0001] INFO  s.a.kinesis.multilang.LineReaderTask [NONE] - Starting: Reading STDERR for shardId-000000000000 
2021-05-23 05:38:35,346 [ShardRecordProcessor-0000] INFO  s.a.kinesis.multilang.MessageWriter [NONE] - Writing InitializeMessage to child process for shard shardId-000000000000 
2021-05-23 05:38:35,441 [multi-lang-daemon-0002] INFO  s.a.kinesis.multilang.MessageWriter [NONE] - Message size == 110 bytes for shard shardId-000000000000 
2021-05-23 05:38:35,442 [multi-lang-daemon-0002] INFO  s.a.kinesis.multilang.LineReaderTask [NONE] - Starting: Reading next message from STDIN for shardId-000000000000 
2021-05-23 05:38:35,642 [ShardRecordProcessor-0000] INFO  s.a.k.multilang.MultiLangProtocol [NONE] - Received response {"action":"status","responseFor":"initialize"} from subprocess while waiting for initialize while processing shard shardId-000000000000 
2021-05-23 05:38:37,927 [ShardRecordProcessor-0000] INFO  s.a.kinesis.multilang.MessageWriter [NONE] - Writing ProcessRecordsMessage to child process for shard shardId-000000000000 
2021-05-23 05:38:37,975 [multi-lang-daemon-0003] INFO  s.a.kinesis.multilang.LineReaderTask [NONE] - Starting: Reading next message from STDIN for shardId-000000000000 
2021-05-23 05:38:37,987 [multi-lang-daemon-0002] INFO  s.a.kinesis.multilang.MessageWriter [NONE] - Message size == 656554 bytes for shard shardId-000000000000 
2021-05-23 05:38:38,054 [ShardRecordProcessor-0000] INFO  s.a.k.multilang.MultiLangProtocol [NONE] - Received response {"action":"status","responseFor":"processRecords"} from subprocess while waiting for processRecords while processing shard shardId-000000000000 
2021-05-23 05:38:54,490 [ShardRecordProcessor-0000] INFO  s.a.kinesis.multilang.MessageWriter [NONE] - Writing o child process for shard shardId-000000000000 
2021-05-23 05:38:54,496 [multi-lang-daemon-0002] INFO  s.a.kinesis.multilang.LineReaderTask [NONE] - Starting: Reading next message from STDIN for shardId-000000000000 
2021-05-23 05:38:54,499 [multi-lang-daemon-0003] INFO  s.a.kinesis.multilang.MessageWriter [NONE] - Message size == 1754 bytes for shard shardId-000000000000 
2021-05-23 05:38:54,520 [ShardRecordProcessor-0000] INFO  s.a.k.multilang.MultiLangProtocol [NONE] - Received response {"action":"status","responseFor":"processRecords"} from subprocess while waiting for processRecords while processing shard shardId-000000000000 
ogconsumer_1  | 2021-05-23 05:41:05,623 [ShardRecordProcessor-0001] WARN  s.a.k.l.ShardConsumerSubscriber [NONE] - shardId-000000000000: onError().  Cancelling subscription, and marking self as failed. 
software.amazon.kinesis.retrieval.RetryableRetrievalException: ReadTimeout
 	at software.amazon.kinesis.retrieval.fanout.FanOutRecordsPublisher.errorOccurred(FanOutRecordsPublisher.java:163)
 	at software.amazon.kinesis.retrieval.fanout.FanOutRecordsPublisher.access$700(FanOutRecordsPublisher.java:54)
 	at software.amazon.kinesis.retrieval.fanout.FanOutRecordsPublisher$RecordFlow.exceptionOccurred(FanOutRecordsPublisher.java:553)
 	at software.amazon.awssdk.services.kinesis.DefaultKinesisAsyncClient.lambda$subscribeToShard$1(DefaultKinesisAsyncClient.java:2238)
 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.lambda$execute$1(AsyncApiCallTimeoutTrackingStage.java:62)
 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryErrorIfNeeded(AsyncRetryableStage.java:167)
 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryIfNeeded(AsyncRetryableStage.java:119)
 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.lambda$execute$0(AsyncRetryableStage.java:104)
 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
 	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$ResponseHandler.onError(MakeAsyncHttpRequestStage.java:236)
 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.lambda$onError$2(ResponseHandler.java:258)
 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:164)
 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$700(ResponseHandler.java:64)
 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onError(ResponseHandler.java:257)
 	at com.typesafe.netty.HandlerPublisher.exceptionCaught(HandlerPublisher.java:432)
 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
 	at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
 	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
 	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
 	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
 	....

```

### LocalStack Output
```
2021-05-23T05:46:52:WARNING:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fd2b610e0d0>(None) failed: An error occurred (InvalidArgumentException) when calling the GetShardIterator operation: StartingSequenceNumber AAAAAAAAAAG6dAzSlAs4Pmcf+a+IF07fBupg3+aEs3PSP87cc2swhBeZmCFDPa8dS0uAMqClcJuAtdGBtaVVbLuQSGYZPd9uw2NaR0X0ELXy4eXdstwlapQ3ah4CYL7fbKxFwRg5S8s8188jmgOI7DW1ZOUGZa6BgqgauU7K4Y4EUQX6+ytdX/HNIJh/Eczd+9kTssUG+Hv+VjgP7S7Z7FRn0jh5Dec6 used in GetShardIterator on shard shardId-000000000000 in stream Logs-Dev under account 000000000000 is invalid. Traceback (most recent call last):
   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 681, in run
     result = self.func(self.params)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
     return fn(*args, **kwargs)
   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 352, in handler
     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 171, in modify_and_forward
     listener_result = listener.forward_request(method=method,
   File "/opt/code/localstack/localstack/services/edge.py", line 117, in forward_request
     return do_forward_request(api, method, path, data, headers, port=port)
   File "/opt/code/localstack/localstack/services/edge.py", line 136, in do_forward_request
     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
   File "/opt/code/localstack/localstack/services/edge.py", line 156, in do_forward_request_inmem
     response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 171, in modify_and_forward
     listener_result = listener.forward_request(method=method,
   File "/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py", line 97, in forward_request
     result = subscribe_to_shard(data, headers)
   File "/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py", line 257, in subscribe_to_shard
     iterator = kinesis.get_shard_iterator(StreamName=stream_name,
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
     return self._make_api_call(operation_name, kwargs)
      File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidArgumentException: An error occurred (InvalidArgumentException) when calling the GetShardIterator operation: StartingSequenceNumber AAAAAAAAAAG6dAzSlAs4Pmcf+a+IF07fBupg3+aEs3PSP87cc2swhBeZmCFDPa8dS0uAMqClcJuAtdGBtaVVbLuQSGYZPd9uw2NaR0X0ELXy4eXdstwlapQ3ah4CYL7fbKxFwRg5S8s8188jmgOI7DW1ZOUGZa6BgqgauU7K4Y4EUQX6+ytdX/HNIJh/Eczd+9kTssUG+Hv+VjgP7S7Z7FRn0jh5Dec6 used in GetShardIterator on shard shardId-000000000000 in stream Logs-Dev under account 000000000000 is invalid.
2021-05-23T05:46:52:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://dev.local:4566/: An error occurred (InvalidArgumentException) when calling the GetShardIterator operation: StartingSequenceNumber AAAAAAAAAAG6dAzSlAs4Pmcf+a+IF07fBupg3+aEs3PSP87cc2swhBeZmCFDPa8dS0uAMqClcJuAtdGBtaVVbLuQSGYZPd9uw2NaR0X0ELXy4eXdstwlapQ3ah4CYL7fbKxFwRg5S8s8188jmgOI7DW1ZOUGZa6BgqgauU7K4Y4EUQX6+ytdX/HNIJh/Eczd+9kTssUG+Hv+VjgP7S7Z7FRn0jh5Dec6 used in GetShardIterator on shard shardId-000000000000 in stream Logs-Dev under account 000000000000 is invalid. Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 129, in index
     raise result
   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 681, in run
     result = self.func(self.params)
   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
     return fn(*args, **kwargs)
   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 352, in handler
     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 171, in modify_and_forward
     listener_result = listener.forward_request(method=method,
   File "/opt/code/localstack/localstack/services/edge.py", line 117, in forward_request
     return do_forward_request(api, method, path, data, headers, port=port)
   File "/opt/code/localstack/localstack/services/edge.py", line 136, in do_forward_request
     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
   File "/opt/code/localstack/localstack/services/edge.py", line 156, in do_forward_request_inmem
     response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,
   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 171, in modify_and_forward
     listener_result = listener.forward_request(method=method,
   File "/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py", line 97, in forward_request
     result = subscribe_to_shard(data, headers)
   File "/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py", line 257, in subscribe_to_shard
     iterator = kinesis.get_shard_iterator(StreamName=stream_name,
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
     return self._make_api_call(operation_name, kwargs)
   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
     raise error_class(parsed_response, operation_name)
 botocore.errorfactory.InvalidArgumentException: An error occurred (InvalidArgumentException) when calling the GetShardIterator operation: StartingSequenceNumber AAAAAAAAAAG6dAzSlAs4Pmcf+a+IF07fBupg3+aEs3PSP87cc2swhBeZmCFDPa8dS0uAMqClcJuAtdGBtaVVbLuQSGYZPd9uw2NaR0X0ELXy4eXdstwlapQ3ah4CYL7fbKxFwRg5S8s8188jmgOI7DW1ZOUGZa6BgqgauU7K4Y4EUQX6+ytdX/HNIJh/Eczd+9kTssUG+Hv+VjgP7S7Z7FRn0jh5Dec6 used in GetShardIterator on shard shardId-000000000000 in stream Logs-Dev under account 000000000000 is invalid.
```

# Steps to reproduce
Start localstack and create the stream.
Start producer.
Start consumer.

## Command used to start LocalStack
```
version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4563-4599:4563-4599'
      - '8855:8080'
    environment:
      - SERVICES=s3,kinesis,dynamodb,cloudwatch
      - DEBUG=1
      - USE_SSL=1
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME=dev.local
      - DEFAULT_REGION=ap-southeast-2
      - KINESIS_LATENCY=0
      - KINESIS_SHARD_LIMIT=1
      - KINESIS_ERROR_PROBABILITY=0.0
      - DYNAMODB_ERROR_PROBABILITY=0.0
    volumes:
      - './localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
```
```
$ docker-compose up
$ aws --endpoint-url=http://localhost:4566 kinesis create-stream --stream-name Logs-Dev --shard-count 1
```

## Steps Taken
Stopping localstack, clearing all data and restarting.

**Comment by cjgordon** [comment]
Also note I believe RetryableRetrievalException: ReadTimeout usually indicates process records took longer than 35 seconds. This is definitely not the case - I have removed logic so it just loops through the records and does nothing.

**Comment by SwatsonCodes** [comment]
Are you still experiencing this issue? I am unable to reproduce it using the python KCL. If you could please provide a minimal example of a Kinesis consumer using the Java KCL that can be used to reproduce your error I will be happy to assist you further.

**Comment by cjgordon** [comment]
Happy to close this, appears to work with the latest version of KCL/LocalStack.
