### ISSUE TITLE
ConnectionError - Connection refused while using Firehose and Elasticsearch

### ISSUE THREAD

**Issue by Dgame** [localstack/localstack#4064]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I am trying to put records into a Firehose stream to be delivered to my Elastic Search cluster, but as soon as I put data into the stream I get the following error response:

```
An error occurred (500) when calling the PutRecord operation (reached max retries: 2): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

When I look into the Docker container of localstack, I see this:
```
2021-05-23T18:37:17:ERROR:firehose_api: Exception on / [POST]

Traceback (most recent call last):

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn

conn = connection.create_connection(

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection

raise err

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection

sock.connect(sa)

ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen

httplib_response = self._make_request(

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request

conn.request(method, url, **httplib_request_kw)

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request

super(HTTPConnection, self).request(method, url, body=body, headers=headers)

File "/usr/lib/python3.8/http/client.py", line 1230, in request

self._send_request(method, url, body, headers, encode_chunked)

File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request

self.endheaders(body, encode_chunked=encode_chunked)

File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders

self._send_output(message_body, encode_chunked=encode_chunked)

File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output

self.send(msg)

File "/usr/lib/python3.8/http/client.py", line 944, in send

self.connect()

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect

conn = self._new_conn()

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn

raise NewConnectionError(

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f35762cef40>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send

resp = conn.urlopen(

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen

retries = retries.increment(

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment

raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /de/_create/632ebf4c-d5d0-44a5-8658-69ce58c92835 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f35762cef40>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/elasticsearch/connection/http_requests.py", line 166, in perform_request

response = self.session.send(prepared_request, **send_kwargs)

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send

r = adapter.send(request, **kwargs)

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send

raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: MyHTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /de/_create/632ebf4c-d5d0-44a5-8658-69ce58c92835 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f35762cef40>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app

response = self.full_dispatch_request()

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request

rv = self.handle_user_exception(e)

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function

return cors_after_request(app.make_response(f(*args, **kwargs)))

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request

rv = self.dispatch_request()

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request

return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 285, in post_request

response = put_record(stream_name, record)

File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 56, in put_record

return put_records(stream_name, [record])

File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 85, in put_records

raise e

File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 82, in put_records

es.create(index=es_index, doc_type=es_type, id=obj_id, body=body)

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 153, in _wrapped

return func(*args, params=params, headers=headers, **kwargs)

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 338, in create

return self.transport.perform_request(

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 413, in perform_request

raise e

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 381, in perform_request

status, headers_response, data = connection.perform_request(

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/elasticsearch/connection/http_requests.py", line 182, in perform_request

raise ConnectionError("N/A", str(e), e)

elasticsearch.exceptions.ConnectionError: ConnectionError(MyHTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /de/_create/632ebf4c-d5d0-44a5-8658-69ce58c92835 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f35762cef40>: Failed to establish a new connection: [Errno 111] Connection refused'))) caused by: ConnectionError(MyHTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /de/_create/632ebf4c-d5d0-44a5-8658-69ce58c92835 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f35762cef40>: Failed to establish a new connection: [Errno 111] Connection refused')))
```

## Expected behavior

The data is inserted into the stream and delivered (and inserted) into the Elasticsearch cluster

# Steps to reproduce
 - Create the Elasticsearch Domain
`aws --endpoint-url http://127.0.0.1:4566 es create-elasticsearch-domain --domain-name es_local`
 - Create the S3 Bucket( just in case)
`aws --endpoint-url http://127.0.0.1:4566 s3api create-bucket --bucket kinesis-es-backup-local --region us-east-1`
 - Define the Firehose Stream and link it to the Elasticsearch Domain
`aws --endpoint-url http://127.0.0.1:4566 firehose create-delivery-stream --delivery-stream-name firehose_es_local_stream --delivery-stream-type DirectPut --elasticsearch-destination-configuration "RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role,DomainARN=arn:aws:es:us-east-1:000000000000:domain/es_local,IndexName=de,S3Configuration={RoleARN=arn:aws:iam::000000000000:role/Firehose-Reader-Role,BucketARN=arn:aws:s3:::000000000000:kinesis-es-backup-local,CompressionFormat=UNCOMPRESSED,EncryptionConfiguration={NoEncryptionConfig=NoEncryption},CloudWatchLoggingOptions={Enabled=false}},ProcessingConfiguration={Enabled=false}"`
 - Put some record into the stream
`aws --endpoint-url http://127.0.0.1:4566 firehose put-record --delivery-stream-name firehose_es_local_stream --record '{"Data":"SGVsbG8gd29ybGQ="}'`
which results in 
```
An error occurred (500) when calling the PutRecord operation (reached max retries: 2): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

If you then look into the Docker container of localstack, you will see the above connection exception.

**Comment by Dgame** [comment]
I'm pretty sure the problem is the attempted connection to http://localhost:9200 according to 
```
urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /de/_create/632ebf4c-d5d0-44a5-8658-69ce58c92835 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f35762cef40>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

but I'm not sure why this is being tried, since Elasticsearch runs on `http://http://localhost:4571`. 🤔 I'm a little confused. Is there anything I can do?

**Comment by Dgame** [comment]
It seems that the built-in Elasticsearch functionality is not recognised and needs to be fixed. But I can work around the problem by creating an external ES cluster and specifying the `ELASTICSEARCH_BACKEND` with the **docker-internal** host (e.g. `http://es` - but pay attention that the port is not specified as in `http://es:9200` as this does not seem to work) _AND_ by specifying `ELASTICSEARCH_PORT` (only found this in the python code) as `9200` (default is - for some strange reason - 80). So my `docker-compose.yml` file looks like this:

```yml
version: "3.7"

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    ports:
      - "${LOCALSTACK_EDGE_PORT-4566}:4566"
      - "${LOCALSTACK_ELASTICSEARCH_PORT-4571}:4571"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=.localstack/data
      - SERVICES=${LOCALSTACK_SERVICES}
      - ELASTICSEARCH_BACKEND=${LOCALSTACK_ELASTICSEARCH_HOST}
      - ELASTICSEARCH_PORT=${LOCALSTACK_ELASTICSEARCH_PORT}
    volumes:
      - ".localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - elastic-net

networks:
  elastic-net:
    name: elastic-net
    driver: bridge
```

Now I'm getting the error
>$ aws --endpoint-url http://127.0.0.1:4566 firehose put-record --delivery-stream-name firehose_es_local_stream --record '{"Data":"SGVsbG8gd29ybGQ="}'

>An error occurred (ResourceNotFoundException) when calling the PutRecord operation: Firehose firehose_es_local_stream under account 000000000000 not found.

as specified in #4057. I'm leaving this issue open as the internal/built-in Elasticsearch still doesn't work and needs to be fixed.
I strongly recommend more documentation / tutorials, as it would have helped me _very_ much instead of reading python code and doing try-and-error all the time. 😄

**Comment by mgagliardo** [comment]
Hello @Dgame, as specified in my comment [here](https://github.com/localstack/localstack/issues/4057#issuecomment-851992897) this is an issue of the data you are trying to push, `not` a proper localstack issue.

Even if we would add documentation, we would not be able to cover every corner case out there for every internal AWS application/service. Either way, in this case it was an internal Elastisearch/Firehose usage, and again, not a localstack one. Cheers
