### ISSUE TITLE
NotImplementedError: The start_query action has not been implemented

### ISSUE THREAD

**Issue by carru93** [localstack/localstack#4078]
# Type of request: This is a ...

- [ ] bug report
- [x] feature request

# Detailed description
I'm using localstack to emulate the cloudwatch logs environment, the getLogEvents and the putLogEvents work from both cli and aws-sdk for nodeJs, but if I try to use the startQuery command it gives me this:

```
2021-05-28 11:04:30,063:API: Error on request:

Traceback (most recent call last):

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 319, in run_wsgi

execute(self.server.app)

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 308, in execute

application_iter = app(environ, start_response)

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 178, in __call__

return backend_app(environ, start_response)

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2069, in __call__

return self.wsgi_app(environ, start_response)

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2054, in wsgi_app

response = self.handle_exception(e)

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function

return cors_after_request(app.make_response(f(*args, **kwargs)))

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function

return cors_after_request(app.make_response(f(*args, **kwargs)))

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app

response = self.full_dispatch_request()

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request

rv = self.handle_user_exception(e)

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function

return cors_after_request(app.make_response(f(*args, **kwargs)))

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function

return cors_after_request(app.make_response(f(*args, **kwargs)))

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request

rv = self.dispatch_request()

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1485, in dispatch_request

return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 156, in __call__

result = self.callback(request, request.url, {})

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 205, in dispatch

return cls()._dispatch(*args, **kwargs)

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 315, in _dispatch

return self.call_action()

File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 417, in call_action

raise NotImplementedError(

NotImplementedError: The start_query action has not been implemented

```

## Expected behavior
I need to query logs depending on the content

## Actual behavior

...

# Steps to reproduce
It happens trying to do a start-query command

## Command used to start LocalStack
I'm using a docker compose file with 
```
localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4563-4599:4563-4599"
      - "8055:8080"
    environment:
      - SERVICES=s3,lambda,cloudwatch,logs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./.localstack:/tmp/localstack"
    networks:
      - boilerplate-network
```
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```sh
aws --endpoint-url=http://localhost:4566 logs start-query --log-group-name fullstack --query-string 307 --start-time 1622198402 --end-time 1622199302 --limit 1
```

```js
const credentials = {
	accessKeyId: process.env.AWS_SECRET_ACCESS_KEY,
	secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY
};

const settings = {
	credentials,
	endpoint: process.env.AWS_ENDPOINT,
	s3ForcePathStyle: true,
	region: 'eu-west-1',
	sslEnabled: false // ???
};

const cloudwatchlogs = new AWS.CloudWatchLogs(settings);


cloudwatchlogs
		.startQuery({
			endTime: Math.floor(Date.now() / 1000),
			queryString: '',
			startTime: Math.floor(Date.now() / 1000) - 15 * 60, // last 15 mins
			logGroupName: process.env.AWS_LOGS_GROUP
		})
		.promise()
```
...

**Comment by whummer** [comment]
Thanks for reporting @carru93 . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!

**Comment by carru93** [comment]
> Thanks for reporting @carru93 . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!

Thanks for the functionality, it seems working properly, but the problem now is 
```
NotImplementedError: The get_query_results action has not been implemented
```
!!!
Without the get_query_result, the start_query command is quite useless 😅 should I open a new issue?

**Comment by usmangani1** [comment]
Thanks for the confirmation.I think it would be better if you can add the necessary functions here and reopen the same issue or create a new one.Thanks

 
 
  On Sat, 12 Jun 2021 at 12:06 pm, Emanuele ***@***.***> wrote:   



Thanks for reporting @carru93 . This should be fixed in the meantime - can you please pull the latest Docker image and give it another try? Please let us know if the problem persists. Thanks!


Thanks for the functionality, it seems working properly, but the problem now is
NotImplementedError: The get_query_results action has not been implemented

!!!
Without the get_query_result, the start_query command is quite useless 😅 should I open a new issue?

**Comment by terence-cevo** [comment]
Can we reopen this issue? `get_query_result` is not implemented.
