### ISSUE TITLE
AWS Lambda PutFunctionEventInvokeConfig returns LastModified timestamp in incorrect format

### ISSUE THREAD

**Issue by cjwooo** [localstack/localstack#4079]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
When I call the Lambda PutFunctionEventInvokeConfig API using the aws-java-sdk, the sdk throws an exception claiming it cannot parse the LastModified timestamp in the response:
```
software.amazon.awssdk.core.exception.SdkClientException: Unable to parse date : 2021-05-28T16:02:30.018Z
        at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)
        at software.amazon.awssdk.protocols.core.StringToInstant.lambda$safeParseDate$0(StringToInstant.java:77)
        at software.amazon.awssdk.protocols.core.StringToInstant.convert(StringToInstant.java:54)
        at software.amazon.awssdk.protocols.core.StringToInstant.convert(StringToInstant.java:32)
```

For comparison, the response for a getting a FunctionEventInvokeConfig for a Lambda of a real AWS account using the aws-cli is the following:
```
{
    "LastModified": "2021-05-27T19:26:43.454000-07:00",
    "FunctionArn": "...",
    ...
}
```

## Expected behavior
LambdaAsyncClient in aws-java-sdk should correctly parse the response for a PutFunctionEventInvokeConfig request.

## Actual behavior
LambdaAsyncClient in aws-java-sdk throws an exception when parsing the LastModified field in the response.

# Steps to reproduce

## Command used to start LocalStack
```
docker run -d --rm --name localstack -p 4566:4566 localstack/localstack:latest
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
val putEventInvokeConfigRequest =
  PutFunctionEventInvokeConfigRequest.builder
    .functionName(functionName)
    .maximumEventAgeInSeconds(21600)
    .maximumRetryAttempts(0)
    .build
lambdaClient.putFunctionEventInvokeConfig(putEventInvokeConfigRequest)
```

**Comment by tovbinm** [comment]
The same error happens with `CreateQueueRequest` (SQS queue creation request) now:
```
software.amazon.awssdk.core.exception.SdkClientException: Unable to parse date : 2021-07-13T16:31:56.461+0000
//...
Caused by: java.lang.NumberFormatException: Character array is missing "e" notation exponential mark.
```

**Comment by tovbinm** [comment]
cc @mgagliardo

**Comment by mgagliardo** [comment]
Hello @tovbinm, thanks for pinging me. 
First of all please create a new issue for this, as this one is closed already.
Second, I was unable to reproduce this issue:

```
package com.example.sqs;

import java.net.URI;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.services.sqs.model.CreateQueueRequest;
import software.amazon.awssdk.services.sqs.model.CreateQueueResponse;
import software.amazon.awssdk.services.sqs.model.GetQueueUrlRequest;
import software.amazon.awssdk.services.sqs.model.SendMessageRequest;

public class SendMessages {

    public static void main(String[] args) {

        SqsClient sqsClient = SqsClient.builder()
                .region(Region.US_WEST_2)
                .credentialsProvider((()->AwsBasicCredentials.create("ignored", "bySim")))
                .endpointOverride(URI.create("http://localhost:4566"))
                .build();

        String queueName = "potato";
        String message = "tomato";

        sendMessage(sqsClient, queueName, message);
        sqsClient.close();
    }

    public static void sendMessage(SqsClient sqsClient, String queueName, String message) {
        CreateQueueRequest request = CreateQueueRequest.builder()
                .queueName(queueName)
                .build();
        CreateQueueResponse createResult = sqsClient.createQueue(request);

        GetQueueUrlRequest getQueueRequest = GetQueueUrlRequest.builder()
                .queueName(queueName)
                .build();

        String queueUrl = sqsClient.getQueueUrl(getQueueRequest).queueUrl();
        SendMessageRequest sendMsgRequest = SendMessageRequest.builder()
                .queueUrl(queueUrl)
                .messageBody(message)
                .delaySeconds(5)
                .build();

        sqsClient.sendMessage(sendMsgRequest);
    }
}
```

```
$ aws --endpoint-url=http://localhost:4566 sqs list-queues
{
    "QueueUrls": [
        "http://localhost:4566/000000000000/potato"
    ]
}

$ aws --endpoint-url=http://localhost:4566 sqs receive-message --queue-url http://localhost:4566/000000000000/potato
{
    "Messages": [
        {
            "MessageId": "be6b6eb2-40ba-51b7-9d90-70b3caa0228d",
            "ReceiptHandle": "wgwuijyixwuykcjonjeyjivsgwvgslbbdypvehwuufytytfviiyqbaqvgxagjxhpqeztqtkxudchawrssctuasofgwrkkdkmtxmzvzivibqckeruawxzdwuucqmygrfaiebehjzwqwyuljhezcrmldnibeydgipxltnczwmufahdakjmkggewuyod",
            "MD5OfBody": "006f87892f47ef9aa60fa5ed01a440fb",
            "Body": "tomato"
        }
    ]
}
```

Please create a new issue and share the code you have used as you can see this one already is compatible with Java SDK v2. Cheers

**Comment by tovbinm** [comment]
Weird. We had to downgrade to `0.12.12` to make this work. We are using aws sdk v2 `2.13.9` with Zulu Java 11.

**Comment by tovbinm** [comment]
```
 software.amazon.awssdk.core.exception.SdkClientException: Unable to parse date : 2021-07-12T16:11:54.858+0000
    at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)
    at software.amazon.awssdk.protocols.core.StringToInstant.lambda$safeParseDate$0(StringToInstant.java:77)
    at software.amazon.awssdk.protocols.core.StringToInstant.convert(StringToInstant.java:54)
    at software.amazon.awssdk.protocols.core.StringToInstant.convert(StringToInstant.java:32)
    at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller$SimpleTypeJsonUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:160)
    at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshallStructured(JsonProtocolUnmarshaller.java:210)
    at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:197)
    at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:168)
    at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:79)
    at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:36)
    at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonResponseHandler.handle(AwsJsonResponseHandler.java:43)
    at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$resultTransformationResponseHandler$5(BaseClientHandler.java:231)
    at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:88)
    at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
    at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:129)
    at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:179)
    at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$500(ResponseHandler.java:69)
    at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:295)
    at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.publishMessage(HandlerPublisher.java:402)
    at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.flushBuffer(HandlerPublisher.java:338)
    at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.receivedDemand(HandlerPublisher.java:291)
    at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.access$200(HandlerPublisher.java:61)
    at software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:495)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Thread.java:829)
    at async @ monix.catnap.internal.FutureLiftForPlatform.$anonfun$javaCompletableToAsync$1(FutureLiftForPlatform.scala:44)
    at flatMap @ monix.catnap.internal.FutureLiftForPlatform.javaCompletableToAsync(FutureLiftForPlatform.scala:43)
Caused by: java.lang.NumberFormatException: Character array is missing "e" notation exponential mark.
```

**Comment by mgagliardo** [comment]
I am using latest (so I guess `2.6.100`):

```
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>sqs</artifactId>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>auth</artifactId>
        </dependency>
```

Can you try upgrading to latest? Should be backward compatible with your implementation

**Comment by mgagliardo** [comment]
On the other hand, can you tell me what are the `attributes`, `tags` and what is `lambdaClients`?

**Comment by tovbinm** [comment]
Updating aws v2 sdk to `2.6.100` did not help.

**Comment by tovbinm** [comment]
aws v2 sdk `2.6.100` works with `localstack/localstack:0.12.15`, but fails with the `localstack/localstack:latest`

**Comment by mgagliardo** [comment]
@tovbinm I need you to open a new issue to follow this up and give me a full example (or at least something similar) of your code to reproduce this, as you can see mine was implementing the same method you mentioned before and was compliant with the change,.
