### ISSUE TITLE
API Gateway, occasional broken pipe when proxying lambda.

### ISSUE THREAD

**Issue by vangorra** [localstack/localstack#408]
I have api gateway proxying a lambda function. That lambda function can take a while sometimes. Occasionally, api gateway fails to return the lambda result and instead throws an exception. You will notice the lambda ran and returned properly.

```
START RequestId: 0d4f42a2-b0d0-1ee8-710e-8f5359ae4f66 Version: $LATEST
2017-10-16T14:36:58.338Z        0d4f42a2-b0d0-1ee8-710e-8f5359ae4f66    NOTICE: Overriding the AWS config to use locastack.
2017-10-16T14:36:58.544Z        0d4f42a2-b0d0-1ee8-710e-8f5359ae4f66    Setting up DI
2017-10-16T14:36:59.976Z        0d4f42a2-b0d0-1ee8-710e-8f5359ae4f66    Connecting to DB
2017-10-16T14:37:00.004Z        0d4f42a2-b0d0-1ee8-710e-8f5359ae4f66    Connected
2017-10-16T14:38:02.587Z        0d4f42a2-b0d0-1ee8-710e-8f5359ae4f66    Graphql function returned.
2017-10-16T14:38:02.588Z        0d4f42a2-b0d0-1ee8-710e-8f5359ae4f66    Disconnecting from DB.
2017-10-16T14:38:02.590Z        0d4f42a2-b0d0-1ee8-710e-8f5359ae4f66    Disconnection from DB.
2017-10-16T14:38:02.591Z        0d4f42a2-b0d0-1ee8-710e-8f5359ae4f66    Disconnect successful.
2017-10-16T14:38:02.592Z        0d4f42a2-b0d0-1ee8-710e-8f5359ae4f66    Returning data. { statusCode: 200,
  headers: 
   { 'Content-Type': 'application/json',
     'Access-Control-Allow-Origin': '*',
     'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept, Authorization, Identification' },
  body: [ { data: [Object] } ] }
END RequestId: 0d4f42a2-b0d0-1ee8-710e-8f5359ae4f66
REPORT RequestId: 0d4f42a2-b0d0-1ee8-710e-8f5359ae4f66  Duration: 64736.79 ms   Billed Duration: 64800 ms       Memory Size: 1536 MB    Max Memory Used: 95 MB  

172.18.0.2 - - [16/Oct/2017 14:38:03] "POST / HTTP/1.1" 200 -
2017-10-16T14:38:03:ERROR:localstack.services.generic_proxy: Error forwarding request: [Errno 32] Broken pipe Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 199, in forward
    self.send_response(response.status_code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 406, in send_response
    self.send_header('Server', self.version_string())
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
  File "/usr/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 80, in __init__
    BaseHTTPRequestHandler.__init__(self, request, client_address, server)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
Exception happened during processing of request from ('172.18.0.4', 50470)
----------------------------------------

```

**Comment by vangorra** [comment]
I looked into this a bit more. It appears to happen when the lambda takes 30 seconds to a minute.

**Comment by whummer** [comment]
Which client are you using to invoke the API Gateway endpoint? The server-side output seems to indicate that it was actually the client that closed the connection (?). Are you also receiving an error on the client side?

I was able to to reproduce the issue with a long-running Lambda that is triggered from an S3 notification, however, that case is different because the S3->Lambda integration uses an actual Lambda `invoke` service invocation, whereas the API Gateway->Lambda integration in fact performs an in-memory call and not a invocation over the network (which is actually an anti-pattern, but that's a different issue :) ).

Is it possible that your client uses a socket read timeout and then fails (closes the connection) after not receiving any data for 60 seconds?

**Comment by vangorra** [comment]
This one was my fault. I'm using an nginx container to proxy the localstack calls and supplement missing functionality. In this case, nginx was killing the proxy connection too early.
