### ISSUE TITLE
s3 files bigger then 21 mb delete after container restart

### ISSUE THREAD

**Issue by dolevhadad** [localstack/localstack#4087]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
files bigger then 21 mb desapird after container restart 

## Expected behavior

...

## Actual behavior

...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by mgagliardo** [comment]
Hello @dolevhadad, could you please share your `docker compose` or how are you running localstack?
On the other hand, are you setting `DATA_DIR` for persistence?

```
DATA_DIR: Local directory for saving persistent data (currently only supported for these services: Kinesis, DynamoDB, Elasticsearch, S3, Secretsmanager, SSM, SQS, SNS). Set it to /tmp/localstack/data to enable persistence (/tmp/localstack is mounted into the Docker container), leave blank to disable persistence (default).
```

**Comment by dolevhadad** [comment]
Hi, @mgagliardo 
The problems occurs **only**  if you upload large files to the s3, 20mb and up and when its upload you can see a few PUT request the file in the log is AWSCLIV2.msi .

if you upload small files 1mb everything work properly .

`
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Ready.
2021-05-31 08:14:09,503:API: 127.0.0.1 - - [31/May/2021 08:14:09] "GET / HTTP/1.1" 200 -
2021-05-31 08:14:09,536:API: 127.0.0.1 - - [31/May/2021 08:14:09] "POST / HTTP/1.1" 200 -
2021-05-31T08:14:09:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 8599.83515739441ms
2021-05-31 08:14:59,856:API: 127.0.0.1 - - [31/May/2021 08:14:59] "POST /my-bucket/AWSCLIV2.msi?uploads HTTP/1.1" 404 -
2021-05-31 08:15:27,871:API: 127.0.0.1 - - [31/May/2021 08:15:27] "PUT /my-bucket HTTP/1.1" 200 -
2021-05-31 08:15:40,271:API: 127.0.0.1 - - [31/May/2021 08:15:40] "POST /my-bucket/AWSCLIV2.msi?uploads HTTP/1.1" 200 -
2021-05-31 08:15:40,422:API: 127.0.0.1 - - [31/May/2021 08:15:40] "PUT /my-bucket/AWSCLIV2.msi?partNumber=4&uploadId=Ax7m7AUzt14ALWNBQG7kbCwD4RD1stjiVrht6VeKfMjSPRBTCrp6nBQ HTTP/1.1" 200 -
2021-05-31 08:15:41,162:API: 127.0.0.1 - - [31/May/2021 08:15:41] "PUT /my-bucket/AWSCLIV2.msi?partNumber=1&uploadId=Ax7m7AUzt14ALWNBQG7kbCwD4RD1stjiVrht6VeKfMjSPRBTCrp6nBQ HTTP/1.1" 200 -
2021-05-31 08:15:41,163:API: 127.0.0.1 - - [31/May/2021 08:15:41] "PUT /my-bucket/AWSCLIV2.msi?partNumber=2&uploadId=Ax7m7AUzt14ALWNBQG7kbCwD4RD1stjiVrht6VeKfMjSPRBTCrp6nBQ HTTP/1.1" 200 -
2021-05-31 08:15:41,180:API: 127.0.0.1 - - [31/May/2021 08:15:41] "PUT /my-bucket/AWSCLIV2.msi?partNumber=3&uploadId=Ax7m7AUzt14ALWNBQG7kbCwD4RD1stjiVrht6VeKfMjSPRBTCrp6nBQ HTTP/1.1" 200 -
2021-05-31 08:15:41,447:API: 127.0.0.1 - - [31/May/2021 08:15:41] "POST /my-bucket/AWSCLIV2.msi?uploadId=Ax7m7AUzt14ALWNBQG7kbCwD4RD1stjiVrht6VeKfMjSPRBTCrp6nBQ HTTP/1.1" 200 -
2021-05-31 08:16:08,003:API: 127.0.0.1 - - [31/May/2021 08:16:08] "PUT /my-bucket/anaconda-ks.cfg HTTP/1.1" 200 -
2021-05-31 08:16:26,384:API: 127.0.0.1 - - [31/May/2021 08:16:26] "GET / HTTP/1.1" 200 -
2021-05-31 08:16:43,912:API: 127.0.0.1 - - [31/May/2021 08:16:43] "GET /my-bucket?list-type=2&delimiter=%2F&prefix=&encoding-type=url HTTP/1.1" 200 -
`

If you don't restart the container everting is ok because the file is in the memory, and you can download it or delete it .

When you restart the container it will try to load the AWSCLIV2.msi file from the file outside the container , but you receive an errors as number as PUT you have in the upload.
Example of one of the error

`
2021-05-31 08:17:25,665:API: 127.0.0.1 - - [31/May/2021 08:17:25] "PUT /my-bucket/AWSCLIV2.msi?partNumber=4&uploadId=Ax7m7AUzt14ALWNBQG7kbCwD4RD1stjiVrht6VeKfMjSPRBTCrp6nBQ HTTP/1.1" 500 -
2021-05-31 08:17:25,671:API: Error on request:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 178, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 156, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1004, in key_or_control_response
    response = self._key_response(request, full_url, headers)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1165, in _key_response
    return self._key_response_put(
  File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 154, in s3_key_response_put
    result = s3_key_response_put_orig(request, body, bucket_name, query, key_name, headers, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1287, in _key_response_put
    key = self.backend.set_part(bucket_name, upload_id, part_number, body)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/models.py", line 1622, in set_part
    multipart = bucket.multiparts[multipart_id]
KeyError: 'Ax7m7AUzt14ALWNBQG7kbCwD4RD1stjiVrht6VeKfMjSPRBTCrp6nBQ'
` 

**_My docker compose file :_**

`
version: '3'
services:
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack
    privileged: true
    ports:
      - "443:4566"
      - "80:4566"
      - "4571:4571"
      - "8080-8081:8080-8081"
    environment:
      - TEST_AWS_ACCOUNT_ID="000000000000"
      - DEFAULT_REGION=us-east-1
      - HOSTNAME=localstack.qalab.vmm
      - LOCALSTACK_HOSTNAME=localstack
      - SERVICES=secretsmanager,s3
      - DATA_DIR=/opt/code/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - "/root/data/localstack_data:/opt/code/localstack/data"
      - "/root/data/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
`

To work around this issue you will need to change the **multipart_threshold** parameter in the .aws/config file to value bigger then the file you want to upload 

It means if the file is 21MB you need to change the parameter to 25MB 

Only this way the container work properly with big files and the file don't corrupts after restart.

**Example of  .aws/config file**

 `
[profile us]
region = eu-west-1
output = json
s3 =
  multipart_threshold = 64MB
`

**Comment by tai2** [comment]
I confirmed the same issue happen in my environment.
Here is steps to reproduce.

```
# docker-compose.yml
version: "3"

services:
  localstack:
    image: localstack/localstack:0.12.16
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DATA_DIR: /tmp/localstack/data
    volumes:
      - "./tmp/localstack:/tmp/localstack"
```

```
# Run docker-compose up in another terminal

$ dd if=/dev/random of=7MB.img bs=1048576 count=7
7+0 records in
7+0 records out
7340032 bytes transferred in 0.026214 secs (280002961 bytes/sec)
$ dd if=/dev/random of=8MB.img bs=1048576 count=8
8+0 records in
8+0 records out
8388608 bytes transferred in 0.030799 secs (272364915 bytes/sec)
$ awslocal s3 cp 7MB.img s3://test-bucket/
upload: ./7MB.img to s3://test-bucket/7MB.img
$ awslocal s3 cp 8MB.img s3://test-bucket/
upload: ./8MB.img to s3://test-bucket/8MB.img
$ awslocal s3 ls s3://test-bucket
2021-08-02 10:35:09    7340032 7MB.img
2021-08-02 10:35:14    8388608 8MB.img

# Stop and start the s3 container

$ awslocal s3 ls s3://test-bucket
2021-08-02 10:36:22    7340032 7MB.img
```

It restores the 8MB.img properly if you set the `multipart_threahold` more than 8MB.

**Comment by tai2** [comment]
Its default is 8MB.

https://docs.aws.amazon.com/sdkref/latest/guide/setting-s3-multipart_threshold.html

**Comment by benediktbrandt** [comment]
The root cause for this issue is in the constructor of the `FakeMultipart` object in the moto library which is used by localstack. The issue is the call to `os.urandum`:

```
class FakeMultipart(BaseModel):
    def __init__(self, key_name, metadata):
        self.key_name = key_name
        self.metadata = metadata
        self.parts = {}
        self.partlist = []  # ordered list of part ID's
        rand_b64 = base64.b64encode(os.urandom(UPLOAD_ID_BYTES))
        self.id = (
            rand_b64.decode("utf-8").replace("=", "").replace("+", "").replace("/", "")
        )
```

The call to `urandum` ensures that there is a random id every time a `FakeMultipart` upload is initiated. 

A Multipart upload is a series of API calls where the later API calls reference the ID that is contained in the response to the first API call. When localstack replays the API calls, the first API call gets a new ID (bc of the `urandum`), but the replay of the remaining API calls still references the old ID. This is why multipart uploads aren't correctly restored. 

One possible fix is to make the id generation pseudo random (based on the key). For instance one can do something like:

```
self.id = base64.b64encode(key_name.ljust(UPLOAD_ID_BYTES,"A")[:UPLOAD_ID_BYTES].replace("=", "").replace("+", "").replace("/", "")).decode("utf-8").replace("=", "").replace("+", "").replace("/", "")
```   

I tried that a little while back and it worked fine for my use case. However every multipart upload to the same key will have the same request id which is not ideal (it deviates from how AWS behaves). 

Ultimately the correct solution for this problem would be to modify the localstack replay code so that it supports the change in IDs.

**Comment by giograno** [comment]
Hi @dolevhadad, does the problem still persist? With today's `latest` it seems I can persist large files. Would you please pull the `latest` Docker image and give it another try? Thanks for the patience 🙏
