### ISSUE TITLE
cloud.localstack.TestUtils.getClientS3 throws git: command not found

### ISSUE THREAD

**Issue by boker** [localstack/localstack#410]
Hi I'm using Java to write integration tests against the localstack on mac.

Am using @RunWith(LocalstackTestRunner.class) on the test class.

I get error on the line AmazonS3 client = TestUtils.getClientS3();

Note: I do have git installed and am constantly using the same.

The console trace at the time of error is:

```
:processTestResources NO-SOURCE
:testClasses
:junitPlatformTest
Oct 17, 2017 12:14:03 PM cloud.localstack.LocalstackTestRunner ensureInstallation
INFO: Installing LocalStack to temporary directory (this may take a while): /var/folders/w2/lhpp_h_s6450nvvrdrrvxwnr0000gn/T//localstack_install_dir
java.lang.RuntimeException: java.lang.IllegalStateException: Failed to run command 'bash -c git clone https://github.com/localstack/localstack /var/folders/w2/lhpp_h_s6450nvvrdrrvxwnr0000gn/T//localstack_install_dir', return code 127.
STDOUT:
STDERR: bash: git: command not found

        at cloud.localstack.LocalstackTestRunner.exec(LocalstackTestRunner.java:233)
        at cloud.localstack.LocalstackTestRunner.exec(LocalstackTestRunner.java:202)
        at cloud.localstack.LocalstackTestRunner.ensureInstallation(LocalstackTestRunner.java:147)
        at cloud.localstack.LocalstackTestRunner.ensureInstallationAndGetEndpoint(LocalstackTestRunner.java:174)
        at cloud.localstack.LocalstackTestRunner.getEndpointS3(LocalstackTestRunner.java:51)
        at cloud.localstack.TestUtils.getEndpointConfigurationS3(TestUtils.java:83)
        at cloud.localstack.TestUtils.getClientS3(TestUtils.java:54)
        at S3HelperTests.ReturnStreamInCaseFileExists(S3HelperTests.java:33)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:389)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:167)
        at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:163)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:110)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:83)
        at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$null$2(HierarchicalTestExecutor.java:92)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)
        at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$null$2(HierarchicalTestExecutor.java:92)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)
        at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:65)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:57)
        at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:57)
        at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:84)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:74)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:47)
        at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)
Caused by: java.lang.IllegalStateException: Failed to run command 'bash -c git clone https://github.com/localstack/localstack /var/folders/w2/lhpp_h_s6450nvvrdrrvxwnr0000gn/T//localstack_install_dir', return code 127.
STDOUT:
STDERR: bash: git: command not found

        at cloud.localstack.LocalstackTestRunner.exec(LocalstackTestRunner.java:220)
```

**Comment by whummer** [comment]
Thanks for reporting @boker . Can you please post the output of these commands:
```
which git
bash -c 'which git'
bash -c 'echo $PATH'
```

Instead of relying on the `git` command to be available, we could use a java-native implementation of git. However, we should also be able to fix this problem by fixing the `$PATH` in your system.

**Comment by whummer** [comment]
Closing as outdated / `won't fix` for now.
