### ISSUE TITLE
Cannot load Java Class: java.net.http.httpRequest on localstack lambda with java 11 runtime.

### ISSUE THREAD

**Issue by Jimon-s** [localstack/localstack#4102]
# Type of request: This is a ...

[☓] bug report
[ ] feature request

# Detailed description
When I run a lambda function with java 11 runtime, lambda can't load java class `java.net.http.httpRequest` which is native java class implemented after java version 11.

If I deploy same jar file to a real aws lambda function, no errors have been happened.

Strangely enough, when I check the version of java of the lambda, it appears to be java 11 in both cases.
...

## Expected behavior
Both a localstack lambda and a real lambda can load java class and launch with no errors. 
...

## Actual behavior
There is a difference between a localstack lambda and a real lambda.

On the localstack lambda.

```
2021-06-05T14:06:34.840000+00:00 2021/06/05/[LATEST]2fe8c31e Exception in thread "main" java.lang.NoClassDefFoundError: java/net/http/HttpRequest
2021-06-05T14:06:35.371000+00:00 2021/06/05/[LATEST]2fe8c31e 	at org.example.Handler.handleRequest(Handler.java:21)
2021-06-05T14:06:35.902000+00:00 2021/06/05/[LATEST]2fe8c31e 	at org.example.Handler.handleRequest(Handler.java:13)
2021-06-05T14:06:36.433000+00:00 2021/06/05/[LATEST]2fe8c31e 	at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:94)
2021-06-05T14:06:36.964000+00:00 2021/06/05/[LATEST]2fe8c31e Caused by: java.lang.ClassNotFoundException: java.net.http.HttpRequest
2021-06-05T14:06:37.496000+00:00 2021/06/05/[LATEST]2fe8c31e 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
2021-06-05T14:06:38.027000+00:00 2021/06/05/[LATEST]2fe8c31e 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
2021-06-05T14:06:38.558000+00:00 2021/06/05/[LATEST]2fe8c31e 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
2021-06-05T14:06:39.089000+00:00 2021/06/05/[LATEST]2fe8c31e 	... 3 more
```

On the real lambda.

```
2021-06-05T14:04:12.378000+00:00 2021/06/05/[$LATEST]42ed09f66caf49298fa4dc56ac277f7e START RequestId: 7a9aeb0e-e4c1-4ddd-bfe4-5c0f040dd9f3 Version: $LATEST
2021-06-05T14:04:12.641000+00:00 2021/06/05/[$LATEST]42ed09f66caf49298fa4dc56ac277f7e Java version11.0.11
2021-06-05T14:04:15.387000+00:00 2021/06/05/[$LATEST]42ed09f66caf49298fa4dc56ac277f7e END RequestId: 7a9aeb0e-e4c1-4ddd-bfe4-5c0f040dd9f3
2021-06-05T14:04:15.387000+00:00 2021/06/05/[$LATEST]42ed09f66caf49298fa4dc56ac277f7e REPORT RequestId: 7a9aeb0e-e4c1-4ddd-bfe4-5c0f040dd9f3	Duration: 3003.55 ms	Billed Duration: 3000 ms	Memory Size: 128 MB	Max Memory Used: 28 MB
2021-06-05T14:04:15.387000+00:00 2021/06/05/[$LATEST]42ed09f66caf49298fa4dc56ac277f7e 2021-06-05T14:04:15.387Z 7a9aeb0e-e4c1-4ddd-bfe4-5c0f040dd9f3 Task timed out after 3.00 seconds
```
...

# Steps to reproduce

## Command used to start LocalStack
I prepare an evironment to reproduce this issue.
Please check [a repository](https://github.com/Jimon-s/localstack-issue-lambda-httpclient).

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
I prepare an evironment to reproduce this issue.
Please check [a repository](https://github.com/Jimon-s/localstack-issue-lambda-httpclient).
...

**Comment by mgagliardo** [comment]
Hello @Jimon-s, you need to do a slight change to your docker compose, the following should work:

```
version: "3.9"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

The important variables here are `LAMBDA_EXECUTOR=docker` and `LAMBDA_REMOTE_DOCKER=true`, both under the main documentation:

```
$ aws lambda create-function --function-name=SampleFunction --runtime=java11 --role=dummy --handler=org.example.Handler::handleRequest --zip-file fileb://target/localstack-issue-lambda-httpclient-1.0-SNAPSHOT.jar --endpoint-url=http://localhost:4566
{
    "FunctionName": "SampleFunction",
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:SampleFunction",
    "Runtime": "java11",
    "Role": "dummy",
    "Handler": "org.example.Handler::handleRequest",
    "CodeSize": 3769,
    "Description": "",
    "Timeout": 3,
    "LastModified": "2021-06-06T18:23:54.819+0000",
    "CodeSha256": "uxyoMJBTVSF1mZ1S1N1X03ao7JdJGR3ThYXH9dYAvb0=",
    "Version": "$LATEST",
    "VpcConfig": {},
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "915829b2-e848-46ce-adc6-0e32442f5516",
    "State": "Active",
    "LastUpdateStatus": "Successful",
    "PackageType": "Zip"
}

$ aws lambda invoke --function-name SampleFunction --payload '{}' --cli-binary-format raw-in-base64-out --endpoint-url=http://localhost:4566 result.log
{
    "StatusCode": 200,
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
```

Then on the localstack logs:
```
localstack_main | 2021-06-06T18:23:58:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:SampleFunction result / log output:
localstack_main | "(GET https://github.com/localstack/localstack) 200"
localstack_main | > START RequestId: 81f9411b-95c3-1696-0f97-ec1c6f3243b0 Version: $LATEST
localstack_main | > Java version11.0.8
localstack_main | > (GET https://github.com/localstack/localstack) 200
localstack_main | > END RequestId: 81f9411b-95c3-1696-0f97-ec1c6f3243b0
localstack_main | > REPORT RequestId: 81f9411b-95c3-1696-0f97-ec1c6f3243b0	Init Duration: 145.32 ms	Duration: 1195.54 ms	Billed Duration: 1196 ms	Memory Size: 1536 MB	Max Memory Used: 117 MB	
```

That should do the trick for you. Cheers

**Comment by Jimon-s** [comment]
Hello, @mgagliardo ! Thank you for your answer! My lambda function works correctly by attempting your advice.

By the way, I have an question. According to the document, the default value of  `LAMBDA_EXECUTOR` and `LAMBDA_REMOTE_DOCKER` are 

- `LAMBDA_EXECUTOR=docker`
- `LAMBDA_REMOTE_DOCKER=true`

These values are same as your example.

What makes difference by apparently specify these values?

**Comment by mgagliardo** [comment]
Ah, none, but for the sake of specifying it I always do it as good practice. Glad it works!
