### ISSUE TITLE
ModuleNotFoundError while running awslocal with Docker image 0.12.12

### ISSUE THREAD

**Issue by ldrag** [localstack/localstack#4108]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
When using latest Localstack Docker image - version 0.12.12 - running any 'awslocal' command fails with:
```
ModuleNotFoundError: No module named 'localstack_client'

```

## Expected behavior
Running 'awslocal' executes without errors.

## Actual behavior
The following error is raised:
```
Traceback (most recent call last):
  File "/usr/bin/awslocal", line 34, in <module>
    from localstack_client import config  # noqa: E402
ModuleNotFoundError: No module named 'localstack_client'

```

**Comment by mgagliardo** [comment]
Hey @ldrag, would you please be a bit more specific? Sample codes, how are you running localstack, etc? I could not reproduce your issue:

command:
```
$ awslocal s3 mb s3://test-bucket
make_bucket: test-bucket
$ awslocal s3api list-buckets
{
    "Buckets": [
        {
            "Name": "test-bucket",
            "CreationDate": "2021-06-07T07:28:15.000Z"
        }
    ],
    "Owner": {
        "DisplayName": "webfile",
        "ID": "bcaf1ffd86f41161ca5fb16fd081034f"
    }
}
```

debug:
```
2021-06-07T07:27:57:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 10382.086992263794ms
2021-06-07 07:28:15,698:API: 127.0.0.1 - - [07/Jun/2021 07:28:15] "PUT /test-bucket HTTP/1.1" 200 -
2021-06-07 07:29:14,886:API: 127.0.0.1 - - [07/Jun/2021 07:29:14] "GET / HTTP/1.1" 200 -
```

**Comment by ilgrosso** [comment]
I am getting the same error by running a sh script named `awsinit.sh` with content like:

```
#!/bin/bash
  
awslocal sqs create-queue --queue-name MyQueue.fifo --attributes FifoQueue=true,ContentBasedDeduplication=tru
```

mounted under `/docker-entrypoint-initaws.d`.

This works fine with 0.10

**Comment by Prillan** [comment]
Expected:
```
% docker run --entrypoint awslocal -it localstack/localstack:0.12.11
Unable to find image 'localstack/localstack:0.12.11' locally
0.12.11: Pulling from localstack/localstack
49dd2c8ce29a: Pull complete 
Digest: sha256:a403cab0daa5ccfe8f9af6067f8165e9c82a0e626211b8442163300921e7e0cb
Status: Downloaded newer image for localstack/localstack:0.12.11
Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: too few arguments
```
Current version (0.12.12):
```
% docker run --entrypoint awslocal -it localstack/localstack:0.12.12
Unable to find image 'localstack/localstack:0.12.12' locally
0.12.12: Pulling from localstack/localstack
fbb526754542: Pull complete 
Digest: sha256:a0906bb165fb370c897368918fb3987c72161e0cd7be5aa9a4bc902112c228af
Status: Downloaded newer image for localstack/localstack:0.12.12
Traceback (most recent call last):
  File "/usr/bin/awslocal", line 34, in <module>
    from localstack_client import config  # noqa: E402
ModuleNotFoundError: No module named 'localstack_client'
```

**Comment by Jurigag** [comment]
Have the same issue.

**Comment by mgagliardo** [comment]
Found the issue, it looks like the [localstack python client lib](https://github.com/localstack/localstack-python-client) is not being correctly installed, in the meantime you all can rollback to a previous version or do the following inside your custom script:

If you are using an script you are mounting:
```
#!/bin/bash
# Do this before running anything
pip install localstack-client

# Run your custom command
awslocal sqs create-queue --queue-name MyQueue.fifo --attributes FifoQueue=true,ContentBasedDeduplication=tru
```

Mount your script as usual:
```
      - "./script.sh:/docker-entrypoint-initaws.d/script.sh"
```

If you are running some custom command inside localstack container just executing `pip install localstack-client` should be enough.

I am working on a PR to fix this ASAP. Thanks for posting.

**Comment by mgagliardo** [comment]
Update: https://github.com/localstack/localstack/pull/4109 has been created to fix this, once it's plugged in you all should be able to pull the `latest` localstack image and keep working as usual :) 
Cheers!
