### ISSUE TITLE
API Gateway Lambda integration throws 500

### ISSUE THREAD

**Issue by ktamilvanan** [localstack/localstack#411]
I have created an api gateway integration with lambda. When i try to test the integration with test-invoke-method, it throws 500 on the console,

```
127.0.0.1 - - [17/Oct/2017 17:03:43] "POST /restapis/485A-Z9A-Z5A-Z24/resources/9690A-Z0A-Z571/methods/POST HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
execute(self.server.app)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 197, in execute
application_iter = app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 93, in __call__
return backend_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 133, in __call__
if len(result) == 3:
TypeError: object of type 'NoneType' has no len()
```

doing a curl with this format gives 404 - http://localhost:4567/restapis/485A-Z9A-Z5A-Z24/prod/jira

I use this script to create the gateway integrations 

```
#!/usr/bin/env bash

NAME=Metrics_Jira_Handler
INDEX_NAME=Metrics_Jira_Index
LAMBDA_FILE=metrics_jira_handler.zip
APINAME=METRICS
REGION=us-east-1

#Remove the existing lambda if it is already installed
EXISTING=$(awslocal apigateway get-rest-apis --query "items[?name==\`${APINAME}\`].id" --output text --region ${REGION})
echo "Existing REST APIs ${EXISTING}"
array=( $EXISTING )
for element in "${array[@]}"
do
	echo "Deleting ${element}"
    awslocal apigateway delete-rest-api --rest-api-id "${element}"
done

awslocal lambda delete-function --function-name "${NAME}"

awslocal lambda delete-function --function-name "${INDEX_NAME}"

awslocal lambda create-function --function-name "${NAME}" --runtime python3.6 --handler lambda.lambda_handler --zip-file fileb://"${LAMBDA_FILE}" --role metrics_role

awslocal lambda create-function --function-name "${INDEX_NAME}" --runtime python3.6 --handler lambda.index --zip-file fileb://"${LAMBDA_FILE}" --role metrics_role

LAMBDAARN=$(awslocal lambda list-functions --query "Functions[?FunctionName==\`${NAME}\`].FunctionArn" --output text)

INDEX_LAMBDA_ARN=$(awslocal lambda list-functions --query "Functions[?FunctionName==\`${INDEX_NAME}\`].FunctionArn" --output text)

echo "Created the Lambda ${NAME} with ARN ${LAMBDAARN}"
echo "Created the Index Lambda ${INDEX_LAMBDA_ARN}"

awslocal apigateway create-rest-api --name "${APINAME}" --description "Api for ${NAME}" --region ${REGION}

APIID=$(awslocal apigateway get-rest-apis --query "items[?name==\`${APINAME}\`].id" --output text --region ${REGION})

PARENTRESOURCEID=$(awslocal apigateway get-resources --rest-api-id ${APIID} --query "items[?path=='/'].id" --output text --region ${REGION})

awslocal apigateway create-resource --rest-api-id ${APIID} --parent-id ${PARENTRESOURCEID} --path-part "jira" --region ${REGION}

RESOURCEID=$(awslocal apigateway get-resources --rest-api-id ${APIID} --query "items[?path=='/jira'].id" --output text --region ${REGION})

echo "Creating GET Method for JIRA Data"
awslocal apigateway put-method --rest-api-id ${APIID} --resource-id ${RESOURCEID} --http-method GET --authorization-type NONE --region ${REGION}

awslocal apigateway put-integration --rest-api-id ${APIID} \
	--resource-id ${RESOURCEID} \
	--http-method GET \
	--type AWS_PROXY \
	--integration-http-method POST \
	--uri arn:aws:apigateway:${REGION}:lambda:path/2015-03-31/functions/${INDEX_LAMBDA_ARN}/invocations \
	--region ${REGION} \
	--passthrough-behavior WHEN_NO_MATCH

	# --request-templates '{"application/x-www-form-urlencoded":"{\"body\": $input.json(\"$\")}"}' \

awslocal apigateway put-method-response \
	--rest-api-id ${APIID} \
	--resource-id ${RESOURCEID} \
	--http-method GET \
	--status-code 200 \
	--response-models "{\"application/json\": \"Empty\"}" \
	--region ${REGION}
		# --response-models "{}" \

awslocal apigateway put-integration-response \
	--rest-api-id ${APIID} \
	--resource-id ${RESOURCEID} \
	--http-method GET \
	--status-code 200 \
	--response-templates "{\"application/json\": \"\"}" \
	--selection-pattern ".*" \
	--region ${REGION}

echo "Creating POST Method for JIRA Data"

awslocal apigateway put-method --rest-api-id ${APIID} --resource-id ${RESOURCEID} --http-method POST --authorization-type NONE --region ${REGION}

awslocal apigateway put-integration --rest-api-id ${APIID} \
	--resource-id ${RESOURCEID} \
	--http-method POST \
	--type AWS_PROXY \
	--integration-http-method POST \
	--uri arn:aws:apigateway:${REGION}:lambda:path/2015-03-31/functions/${LAMBDAARN}/invocations \
	--region ${REGION}

	# --request-templates '{"application/x-www-form-urlencoded":"{\"body\": $input.json(\"$\")}"}' \

awslocal apigateway put-method-response \
	--rest-api-id ${APIID} \
	--resource-id ${RESOURCEID} \
	--http-method POST \
	--status-code 200 \
	--response-models "{\"application/json\": \"Empty\"}" \
	--region ${REGION}
		# --response-models "{}" \

awslocal apigateway put-integration-response \
	--rest-api-id ${APIID} \
	--resource-id ${RESOURCEID} \
	--http-method POST \
	--status-code 200 \
	--response-templates "{\"application/json\": \"\"}" \
	--selection-pattern ".*" \
	--region ${REGION}

echo "Deploying the ${APINAME} to the ${REGION} region";

awslocal apigateway create-deployment --rest-api-id ${APIID} --stage-name prod --region ${REGION}

echo "Adding permission to the lambda to be executed by the apigateway"

APIARN=$(echo ${LAMBDAARN} | sed -e 's/lambda/execute-api/' -e "s/function:${NAME}/${APIID}/")
awslocal lambda add-permission \
	--function-name ${NAME} \
	--statement-id apigateway-jira-test-2 \
	--action lambda:InvokeFunction \
	--principal apigateway.amazonaws.com \
	--source-arn "${APIARN}/*/POST/jira" \
	--region ${REGION}

awslocal lambda add-permission \
	--function-name ${NAME} \
	--statement-id apigateway-jira-prod-2 \
	--action lambda:InvokeFunction \
	--principal apigateway.amazonaws.com \
	--source-arn "${APIARN}/prod/POST/jira" \
	--region ${REGION}

echo "Starting the Gateway GET endpoint test"

curl "http://localhost:4567/restapis/${APIID}/prod/_user_request_/jira"

#awslocal apigateway test-invoke-method --rest-api-id ${APIID} --resource-id ${RESOURCEID} --http-method GET --path-with-query-string ""

echo "Finished the Gateway endpoint test"

echo "Starting the Gateway POST endpoint test"

curl -H 'content-type: application/json' -X POST "http://localhost:4567/restapis/${APIID}/prod/_user_request_/jira" -d "{\"first_name\":\"passive\", \"last_name\":\"kathiravan\"}"
#awslocal apigateway test-invoke-method --rest-api-id ${APIID} --resource-id ${RESOURCEID} --http-method POST --path-with-query-string "" --body "{\"first_name\":\"passive\", \"last_name\":\"kathiravan\"}"

echo "Finished the Gateway endpoint test"

echo "The url you have to use in your Slack settings is:
http://localhost:4567/restapis/${APIID}/prod/_user_request_/jira"
```

**Comment by ktamilvanan** [comment]
test-invoke-method does not work. But when i curl the http://localhost:4567/restapis/${APIID}/prod/_user_request_/jira GET endpoints work. But I can't invoke POST endpoints. 

`curl -H 'content-type: application/json' -X POST "http://localhost:4567/restapis/${APIID}/prod/_user_request_/jira" -d "{\"first_name\":\"abcd\", \"last_name\":\"efgh\"}"`

With my lambda 
```
def lambda_handler(event, context):
    message = 'Hello {} {}!'.format(event['first_name'],event['last_name'])
    return { 'statusCode':200, 'body' : message }  

def index(event,context):
    return { 'statusCode':200, 'body': 'Hello World'}
```
throws the following exceptions on the console,
```
017-10-18T07:15:20:WARNING:localstack.services.awslambda.lambda_api: Error executing Lambda function: 'first_name' Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 343, in run_lambda
process.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 339, in do_execute
result = func(event, context)
File "/tmp/localstack/lambda_script_l_5a687dc9.py", line 3, in lambda_handler
message = 'Hello {} {}!'.format(event['first_name'],event['last_name'])
KeyError: 'first_name'

2017-10-18T07:15:20:WARNING:localstack.services.awslambda.lambda_api: Unable to run Lambda function on API Gateway message: working outside of application context Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 157, in process_apigateway_invocation
return run_lambda(lambda_function, event=event, context={}, func_arn=func_arn)
File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 107, in wrapped
raise e
RuntimeError: working outside of application context

2017-10-18T07:15:20:ERROR:localstack.services.generic_proxy: Error forwarding request: expected string or buffer Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 171, in forward
path=path, data=data, headers=forward_headers)
File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 181, in forward_request
parsed_result = result if isinstance(result, dict) else json.loads(result)
File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

**Comment by whummer** [comment]
Thanks for reporting @ktamilvanan - have you been able to fix this issue?

**Comment by DmPanov** [comment]
I'm experiencing similar problem. @ktamilvanan, please provide some feedback
