### ISSUE TITLE
404 error from s3.amazonaws.com endpoint

### ISSUE THREAD

**Issue by kwinwithak** [localstack/localstack#4118]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

I'm attempting to download an object from a real S3 bucket in AWS using a Lambda function in LocalStack. The target objects and bucket permit public read access. I'm setting the `endpoint_url` for my boto3 s3 client to the AWS service endpoint, but I seem to be missing something because my request returns _"An error occurred (404) when calling the HeadObject operation: Not Found"_. Below I'm using `head_object` but the principle is the same as `download_fileobj`.

I've also tested my lambda against a LocalStack S3 bucket and can successfully download objects from there, so the issue seems to be how I'm accessing the external service endpoint. Are there any gotchas when making requests to the s3.amazonaws.com service endpoint? In general I find it challenging to integrate LocalStack with real/external AWS resources. Localizing everything works great but it's not always practical.

# Steps to reproduce

## Command used to start LocalStack

`docker-compose up` with the following docker-compose.yml:
```
version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SERVICES=iam,s3,cloudformation,lambda,sqs,dynamodb,efs,ec2
      - DEFAULT_REGION=us-west-2
      - DEBUG=1
      - LS_LOG=trace
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=stack_default
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
def lambda_handler(event, context):
    s3_client = boto3.client('s3', endpoint_url="https://s3.amazonaws.com", verify=False) 
    bucket_name = "landsat-pds"
    input_key = "c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF"
    response = s3_client.head_object(Bucket=bucket_name, Key=input_key)
```
A test to prove this object really exists:
```
aws s3 cp s3://landsat-pds/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF test.tif
```

**Comment by macnev2013** [comment]
Thanks for reporting @kwinwithak.
Yes it is possible to access production resources from a local lambda function.

Command to create lambda function:
```
awslocal lambda create-function \
    --function-name myfunction \
    --runtime python3.8 \
    --timeout 300 \
    --role test-role \
    --environment "Variables={AWS_ACCESS_KEY_ID=ACTUAL_KEY,AWS_SECRET_ACCESS_KEY=ACTUAL_KEY}" \
    --handler lambda_function.lambda_handler \
    --zip-file fileb://my-deployment-package.zip
```

Lambda Function:
```
def lambda_handler(*args, **kwargs):
    import boto3
    s3 = boto3.client('s3')
    bucket_name = "landsat-pds"
    input_key = "c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF"
    response = s3.head_object(Bucket=bucket_name, Key=input_key)
    print(response)
```

Thanks.

**Comment by kwinwithak** [comment]
@macnev2013 I confirmed this works on another machine using your snippets, but something is still causing the HeadObject 404 "Not Found" error on my target machine. I noticed the boto3 client doesn't require specifying an endpoint URL, and yet LocalStack figures out that the bucket is external. I can see in the botocore logs that the object URI that LS settles on is correct (you can paste it into a browser and download the object). Despite all that, it seems my access key is rejected by AWS. Any ideas? If I know what clues to follow next I'll open a new issue. Your help is much appreciated 🙏 

```
localstack_1  | START RequestId: 36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa Version: $LATEST
localstack_1  | [DEBUG] 2021-06-11T19:39:12.823Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Event before-parameter-build.s3.HeadObject: calling handler <function sse_md5 at 0x7fb366e990d0>
localstack_1  | 2021-06-11 19:39:12,823 botocore.hooks [DEBUG] Event before-parameter-build.s3.HeadObject: calling handler <function sse_md5 at 0x7fb366e990d0>
localstack_1  | 2021-06-11 19:39:12,823 botocore.hooks [DEBUG] Event before-parameter-build.s3.HeadObject: calling handler <function validate_bucket_name at 0x7fb366e99040>
localstack_1  | [DEBUG] 2021-06-11T19:39:12.823Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Event before-parameter-build.s3.HeadObject: calling handler <function validate_bucket_name at 0x7fb366e99040>
localstack_1  | 2021-06-11 19:39:12,823 botocore.hooks [DEBUG] Event before-parameter-build.s3.HeadObject: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7fb365d0ff40>>
localstack_1  | 2021-06-11 19:39:12,823 botocore.hooks [DEBUG] Event before-parameter-build.s3.HeadObject: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x7fb365cc6040>>
localstack_1  | [DEBUG] 2021-06-11T19:39:12.823Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Event before-parameter-build.s3.HeadObject: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7fb365d0ff40>>
localstack_1  | [DEBUG] 2021-06-11T19:39:12.823Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Event before-parameter-build.s3.HeadObject: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x7fb365cc6040>>
localstack_1  | 2021-06-11 19:39:12,824 botocore.hooks [DEBUG] Event before-parameter-build.s3.HeadObject: calling handler <function generate_idempotent_uuid at 0x7fb366e94e50>
localstack_1  | [DEBUG] 2021-06-11T19:39:12.824Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Event before-parameter-build.s3.HeadObject: calling handler <function generate_idempotent_uuid at 0x7fb366e94e50>
localstack_1  | [DEBUG] 2021-06-11T19:39:12.824Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Event before-call.s3.HeadObject: calling handler <function add_expect_header at 0x7fb366e993a0>
localstack_1  | [DEBUG] 2021-06-11T19:39:12.824Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Event before-call.s3.HeadObject: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x7fb365d0ff40>>
localstack_1  | 2021-06-11 19:39:12,824 botocore.hooks [DEBUG] Event before-call.s3.HeadObject: calling handler <function add_expect_header at 0x7fb366e993a0>
localstack_1  | 2021-06-11 19:39:12,824 botocore.hooks [DEBUG] Event before-call.s3.HeadObject: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x7fb365d0ff40>>
localstack_1  | 2021-06-11 19:39:12,825 botocore.hooks [DEBUG] Event before-call.s3.HeadObject: calling handler <function inject_api_version_header_if_needed at 0x7fb366e9a700>
localstack_1  | [DEBUG] 2021-06-11T19:39:12.825Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Event before-call.s3.HeadObject: calling handler <function inject_api_version_header_if_needed at 0x7fb366e9a700>
localstack_1  | 2021-06-11 19:39:12,825 botocore.endpoint [DEBUG] Making request for OperationModel(name=HeadObject) with params: {'url_path': '/landsat-pds/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF', 'query_string': {}, 'method': 'HEAD', 'headers': {'User-Agent': 'Boto3/1.14.48 Python/3.8.5 Linux/5.4.72-microsoft-standard-WSL2 exec-env/AWS_Lambda_python3.8 Botocore/1.17.48'}, 'body': b'', 'url': 'https://s3.us-west-2.amazonaws.com/landsat-pds/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF', 'context': {'client_region': 'us-west-2', 'client_config': <botocore.config.Config object at 0x7fb366adc1c0>, 'has_streaming_input': False, 'auth_type': None, 'signing': {'bucket': 'landsat-pds'}}}
localstack_1  | [DEBUG] 2021-06-11T19:39:12.825Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Making request for OperationModel(name=HeadObject) with params: {'url_path': '/landsat-pds/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF', 'query_string': {}, 'method': 'HEAD', 'headers': {'User-Agent': 'Boto3/1.14.48 Python/3.8.5 Linux/5.4.72-microsoft-standard-WSL2 exec-env/AWS_Lambda_python3.8 Botocore/1.17.48'}, 'body': b'', 'url': 'https://s3.us-west-2.amazonaws.com/landsat-pds/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF', 'context': {'client_region': 'us-west-2', 'client_config': <botocore.config.Config object at 0x7fb366adc1c0>, 'has_streaming_input': False, 'auth_type': None, 'signing': {'bucket': 'landsat-pds'}}}
localstack_1  | 2021-06-11 19:39:12,825 botocore.hooks [DEBUG] Event request-created.s3.HeadObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fb366adc1f0>>
localstack_1  | [DEBUG] 2021-06-11T19:39:12.825Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Event request-created.s3.HeadObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fb366adc1f0>>
localstack_1  | 2021-06-11 19:39:12,826 botocore.hooks [DEBUG] Event choose-signer.s3.HeadObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x7fb3692a0880>>
localstack_1  | [DEBUG] 2021-06-11T19:39:12.826Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Event choose-signer.s3.HeadObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x7fb3692a0880>>
localstack_1  | [DEBUG] 2021-06-11T19:39:12.826Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Event choose-signer.s3.HeadObject: calling handler <function set_operation_specific_signer at 0x7fb366e94d30>
localstack_1  | 2021-06-11 19:39:12,826 botocore.hooks [DEBUG] Event choose-signer.s3.HeadObject: calling handler <function set_operation_specific_signer at 0x7fb366e94d30>
localstack_1  | 2021-06-11 19:39:12,826 botocore.hooks [DEBUG] Event before-sign.s3.HeadObject: calling handler <bound method S3EndpointSetter.set_endpoint of <botocore.utils.S3EndpointSetter object at 0x7fb365cc60d0>>
localstack_1  | [DEBUG] 2021-06-11T19:39:12.826Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Event before-sign.s3.HeadObject: calling handler <bound method S3EndpointSetter.set_endpoint of <botocore.utils.S3EndpointSetter object at 0x7fb365cc60d0>>
localstack_1  | 2021-06-11 19:39:12,826 botocore.utils [DEBUG] Defaulting to S3 virtual host style addressing with path style addressing fallback.
localstack_1  | [DEBUG] 2021-06-11T19:39:12.826Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Defaulting to S3 virtual host style addressing with path style addressing fallback.
localstack_1  | 2021-06-11 19:39:12,826 botocore.utils [DEBUG] Checking for DNS compatible bucket for: https://s3.us-west-2.amazonaws.com/landsat-pds/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF
localstack_1  | [DEBUG] 2021-06-11T19:39:12.826Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Checking for DNS compatible bucket for: https://s3.us-west-2.amazonaws.com/landsat-pds/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF
localstack_1  | 2021-06-11 19:39:12,827 botocore.utils [DEBUG] URI updated to: https://landsat-pds.s3.us-west-2.amazonaws.com/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF
localstack_1  | [DEBUG] 2021-06-11T19:39:12.827Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    URI updated to: https://landsat-pds.s3.us-west-2.amazonaws.com/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF
localstack_1  | 2021-06-11 19:39:12,827 botocore.auth [DEBUG] Calculating signature using v4 auth.
localstack_1  | [DEBUG] 2021-06-11T19:39:12.827Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Calculating signature using v4 auth.
localstack_1  | 2021-06-11 19:39:12,827 botocore.auth [DEBUG] CanonicalRequest:
localstack_1  | HEAD
localstack_1  | /c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF
localstack_1  |
localstack_1  | host:landsat-pds.s3.us-west-2.amazonaws.com
localstack_1  | x-amz-content-sha256:REDACTED_AMZ_CONTENT_SHA
localstack_1  | x-amz-date:20210611T193912Z
localstack_1  |
localstack_1  | host;x-amz-content-sha256;x-amz-date
localstack_1  | REDACTED_AMZ_CONTENT_SHA
localstack_1  | [DEBUG] 2021-06-11T19:39:12.827Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    CanonicalRequest:
localstack_1  | HEAD
localstack_1  | /c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF
localstack_1  |
localstack_1  | host:landsat-pds.s3.us-west-2.amazonaws.com
localstack_1  | x-amz-content-sha256:REDACTED_AMZ_CONTENT_SHA
localstack_1  | x-amz-date:20210611T193912Z
localstack_1  |
localstack_1  | host;x-amz-content-sha256;x-amz-date
localstack_1  | REDACTED_AMZ_CONTENT_SHA
localstack_1  | 2021-06-11 19:39:12,827 botocore.auth [DEBUG] StringToSign:
localstack_1  | AWS4-HMAC-SHA256
localstack_1  | 20210611T193912Z
localstack_1  | 20210611/us-west-2/s3/aws4_request
localstack_1  | 702d1a515aea87cadd2295003320ff44bdd478ad567b2a7dd7c7962c6d2ba00d
localstack_1  | [DEBUG] 2021-06-11T19:39:12.827Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    StringToSign:
localstack_1  | AWS4-HMAC-SHA256
localstack_1  | 20210611T193912Z
localstack_1  | 20210611/us-west-2/s3/aws4_request
localstack_1  | 702d1a515aea87cadd2295003320ff44bdd478ad567b2a7dd7c7962c6d2ba00d
localstack_1  | 2021-06-11 19:39:12,827 botocore.auth [DEBUG] Signature:
localstack_1  | REDACTED_SIGNATURE
localstack_1  | [DEBUG] 2021-06-11T19:39:12.827Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Signature:
localstack_1  | REDACTED_SIGNATURE
localstack_1  | 2021-06-11 19:39:12,828 botocore.endpoint [DEBUG] Sending http request: <AWSPreparedRequest stream_output=False, method=HEAD, url=https://landsat-pds.s3.us-west-2.amazonaws.com/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF, headers={'User-Agent': b'Boto3/1.14.48 Python/3.8.5 Linux/5.4.72-microsoft-standard-WSL2 exec-env/AWS_Lambda_python3.8 Botocore/1.17.48', 'X-Amz-Date': b'20210611T193912Z', 'X-Amz-Content-SHA256': b'REDACTED_AMZ_CONTENT_SHA', 'Authorization': b'AWS4-HMAC-SHA256 Credential=REDACTED_AWS_ACCESS_KEY_ID/20210611/us-west-2/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=REDACTED_SIGNATURE'}>
localstack_1  | [DEBUG] 2021-06-11T19:39:12.828Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Sending http request: <AWSPreparedRequest stream_output=False, method=HEAD, url=https://landsat-pds.s3.us-west-2.amazonaws.com/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF, headers={'User-Agent': b'Boto3/1.14.48 Python/3.8.5 Linux/5.4.72-microsoft-standard-WSL2 exec-env/AWS_Lambda_python3.8 Botocore/1.17.48', 'X-Amz-Date': b'20210611T193912Z', 'X-Amz-Content-SHA256': b'REDACTED_AMZ_CONTENT_SHA', 'Authorization': b'AWS4-HMAC-SHA256 Credential=REDACTED_AWS_ACCESS_KEY_ID/20210611/us-west-2/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=REDACTED_SIGNATURE'}>
localstack_1  | /var/runtime/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'landsat-pds.s3.us-west-2.amazonaws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
localstack_1  |   warnings.warn(
localstack_1  | 2021-06-11 19:39:12,858 botocore.parsers [DEBUG] Response headers: {'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '248', 'Access-Control-Allow-Origin': '*', 'Last-Modified': 'Fri, 11 Jun 2021 19:39:12 GMT', 'x-amz-request-id': '135D45E5F26BA9BD', 'x-amz-id-2': 'MzRISOwyjmnup135D45E5F26BA9BD7/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'Access-Control-Expose-Headers': 'x-amz-version-id', 'Connection': 'close', 'date': 'Fri, 11 Jun 2021 19:39:12 GMT', 'server': 'hypercorn-h11'}
localstack_1  | [DEBUG] 2021-06-11T19:39:12.858Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Response headers: {'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '248', 'Access-Control-Allow-Origin': '*', 'Last-Modified': 'Fri, 11 Jun 2021 19:39:12 GMT', 'x-amz-request-id': '135D45E5F26BA9BD', 'x-amz-id-2': 'MzRISOwyjmnup135D45E5F26BA9BD7/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'Access-Control-Expose-Headers': 'x-amz-version-id', 'Connection': 'close', 'date': 'Fri, 11 Jun 2021 19:39:12 GMT', 'server': 'hypercorn-h11'}
localstack_1  | [DEBUG] 2021-06-11T19:39:12.858Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Response body:
localstack_1  | b''
localstack_1  | 2021-06-11 19:39:12,858 botocore.parsers [DEBUG] Response body:
localstack_1  | b''
localstack_1  | 2021-06-11 19:39:12,860 botocore.hooks [DEBUG] Event needs-retry.s3.HeadObject: calling handler <botocore.retryhandler.RetryHandler object at 0x7fb365d0fee0>
localstack_1  | [DEBUG] 2021-06-11T19:39:12.860Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Event needs-retry.s3.HeadObject: calling handler <botocore.retryhandler.RetryHandler object at 0x7fb365d0fee0>
localstack_1  | [DEBUG] 2021-06-11T19:39:12.860Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    No retry needed.
localstack_1  | [DEBUG] 2021-06-11T19:39:12.860Z        36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa    Event needs-retry.s3.HeadObject: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7fb365d0ff40>>
localstack_1  | 2021-06-11 19:39:12,860 botocore.retryhandler [DEBUG] No retry needed.
localstack_1  | 2021-06-11 19:39:12,860 botocore.hooks [DEBUG] Event needs-retry.s3.HeadObject: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7fb365d0ff40>>
localstack_1  | [ERROR] ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/var/task/lambda_function.py", line 10, in lambda_handler
localstack_1  |     response = s3.head_object(Bucket=bucket_name, Key=input_key)
localstack_1  |   File "/var/runtime/botocore/client.py", line 316, in _api_call
localstack_1  |     return self._make_api_call(operation_name, kwargs)
localstack_1  |   File "/var/runtime/botocore/client.py", line 635, in _make_api_call
localstack_1  |     raise error_class(parsed_response, operation_name)
localstack_1  | END RequestId: 36d7aa97-828d-1d2a-9f89-a9d2b7ad59aa
```

P.S. I should note that the machine where this is failing uses a custom certificate authority bundle. I haven't yet brought this CA bundle into my LocalStack docker setup, hence the use of `verify=False`. But, my testing on the other machine (no custom CA bundle) worked regardless of whether SSL verification was used or not, so perhaps that's unrelated.

**Comment by macnev2013** [comment]
Thanks for the feedback @kwinwithak . Apologies for the delay. You require a valid access/secret key to access the object (even its public). As described above you need to add valid keys, However **WE DO NOT RECOMMEND IT.** 
Thanks.

**Comment by kwinwithak** [comment]
@macnev2013 The issue is not the access key. As I said, I got this working on another machine, but on my primary machine I get the HeadObject error shown above even with a valid access key supplied to the lambda. I'm trying to resolve whatever issue is causing this error despite following your guidance so far.

Also, why does LocalStack warn against using AWS access keys? Is it inherently unsafe to interact with AWS resources through LS?

**Comment by whummer** [comment]
Thanks for the update @kwinwithak

> Also, why does LocalStack warn against using AWS access keys? Is it inherently unsafe to interact with AWS resources through LS?

The reason why we're warning against using real credentials with LocalStack is that we don't want to be in any shape or form associated with real production access. It is not inherently unsafe, but at the same time we want to express that we're not covering these cases in our testing, and it is entirely at your own risk to access real cloud resources from within LocalStack. 

For example, there may be certain tear-down logic in place which could result in loss of some of your AWS cloud resources (again, we're not actively deleting resources per se, but we also can't guarantee that it is not the case). Generally, we'd advise against using this pattern, as it may be potentially unsafe (erring more on the safe side here, and making people aware of the risks). Thanks!

---
Also, please note that we have a DNS integration feature in our Pro version, which essentially resolves all `amazonaws.com` domain names to a local IP address. Are you using the Pro version, by any chance? In this case, you could try disabling the DNS server by setting DNS_ADDRESS=0 in your environment. Hope that helps - please keep us posted how it goes. Thanks
