### ISSUE TITLE
Missing trailing slash causes endpoint mismatch

### ISSUE THREAD

**Issue by DavidTanner** [localstack/localstack#4124]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

The new `@aws-sdk` for javascript has left off some of the trailing slashes in URLs.  for example `/2015-03-31/event-source-mappings?FunctionName=some-function`.  Localstack returns an incorrect body when the trailing slash is left off.  Here are the logs from the docker image when the trailing slash is left off.

## Expected behavior

Response body
```json
{"EventSourceMappings":[]}
```

## Actual behavior

Response body
```json
{}
```

Logs from Docker localstack/localstack:0.12.12
```
2021-06-10T00:29:43:WARNING:localstack.services.edge: Unable to find listener for service "s3" - please make sure to include it in $SERVICES

2021-06-10T00:29:43:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request GET http://localhost:4566/2015-03-31/event-source-mappings/?FunctionName=life-social-queries-service: Unable to find listener for service "s3" - please make sure to include it in $SERVICES Traceback (most recent call last):

File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 127, in index

result = await run_sync(handler, request, data)

File "/opt/code/localstack/localstack/utils/async_utils.py", line 84, in run_sync

return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)

File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run

result = self.fn(*self.args, **self.kwargs)

File "/opt/code/localstack/localstack/services/generic_proxy.py", line 366, in handler

client_address=request.remote_addr, server_address=parsed_url.netloc)

File "/opt/code/localstack/localstack/services/generic_proxy.py", line 184, in modify_and_forward

path=path, data=data, headers=headers)

File "/opt/code/localstack/localstack/services/edge.py", line 122, in forward_request

return do_forward_request(api, method, path, data, headers, port=port)

File "/opt/code/localstack/localstack/services/edge.py", line 143, in do_forward_request

result = do_forward_request_inmem(api, method, path, data, headers, port=port)

File "/opt/code/localstack/localstack/services/edge.py", line 157, in do_forward_request_inmem

raise HTTPErrorResponse(message, code=400)

localstack.utils.server.http2_server.HTTPErrorResponse: Unable to find listener for service "s3" - please make sure to include it in $SERVICES
```

# Steps to reproduce

Make call to 
`http://localstack:4566/2015-03-31/event-source-mappings/?FunctionName=some-function-name`
or 
`http://localstack:4566/2015-03-31/event-source-mappings?FunctionName=some-function-name`

## Command used to start LocalStack

```sh
docker run -d -p "4566:4566" -v /var/run/docker.sock:/var/run/docker.sock -e SERVICES=lambda 'localstack/localstack:0.12.12'
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```javascript
const http = require("http");

const withSlash = '/2015-03-31/event-source-mappings/?FunctionName=some-function-name';
const withoutSlash = '/2015-03-31/event-source-mappings?FunctionName=some-function-name';

const options = {
  "headers": {
    "host": "localhost",
    "x-amz-user-agent": "aws-sdk-js/3.17.0",
    "user-agent": "aws-sdk-js/3.17.0 os/darwin/20.3.0 lang/js md/nodejs/14.16.0 api/lambda/3.17.0",
    "amz-sdk-invocation-id": "91812516-4ef6-412c-b200-12914e118c3b",
    "amz-sdk-request": "attempt=1; max=3",
    "x-amz-date": "20210609T220616Z",
    "x-amz-content-sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "authorization": "AWS4-HMAC-SHA256 Credential=bogus/20210609/us-east-1/lambda/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date;x-amz-user-agent, Signature=5de8e6de5ec6d57786876445a29f3db119def18a52be2dbae55c86f3eb73970d"
  },
  "host": "localhost",
  "method": "GET",
  "port": 4566,
  "agent": new http.Agent({ keepAlive: false, maxSockets: 50 })
}

async function makeGet(path) {
  const promise = new Promise((resolve, reject) => {
    const req = http.request({...options, path}, (res) => {
      const chunks: any[] = [];
      res.on('end', () => {
        console.log(chunks.join());
        resolve();
      });
      res.on('data', (chunk) => chunks.push(chunk.toString()));
    });
    req.on('error', (err: any) => {
      reject(err);
    });
    req.end();
  });
  await promise;
}

async function get() {
  console.log('with slash');
  await makeGet(withSlash);
  console.log('without slash');
  await makeGet(withoutSlash);
}

get().then(() => console.log('done'), (err) => console.error(err));
```

# Unit Test

```python
    def test_create_event_source_mapping_no_slash(self):
        self.client.post('{0}/event-source-mappings'.format(lambda_api.PATH_ROOT),
            data=json.dumps({'FunctionName': 'test-lambda-function', 'EventSourceArn': TEST_EVENT_SOURCE_ARN}))

        listResponse = self.client.get('{0}/event-source-mappings'.format(lambda_api.PATH_ROOT))
        listResult = json.loads(listResponse.get_data())

        eventSourceMappings = listResult.get('EventSourceMappings')

        self.assertEqual(1, len(eventSourceMappings))
        self.assertEqual('Enabled', eventSourceMappings[0]['State'])

```

**Comment by whummer** [comment]
Thanks for reporting @DavidTanner . This should be fixed in #4153 - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!

**Comment by DavidTanner** [comment]
Progress.  I don't get any errors about S3 not running, but I am getting a 500 error.  I'll see if I can figure out what it is and open a new issue if there is something to it.

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

**Comment by DavidTanner** [comment]
Yeah, that is my issue. 
```
'Lambda %s name should not contain a colon ":": %s' % (type, entity_name))
localstack_1  | Exception: Lambda function name should not contain a colon ":": df45c0c6-e05a-4d4a-94be-044568ee1029:deployed
```
