### ISSUE TITLE
NotImplementedError: The get_query_results action has not been implemented 

### ISSUE THREAD

**Issue by carru93** [localstack/localstack#4143]
# Type of request: This is a ...

- [ ] bug report
- [x] feature request

# Detailed description
I am using localstack to emulate the cloudwatch logs environment, some days ago I opened a issue #4078  about the implementation of start_query, but in order to use it, I need also the ```get_query_results``` command.

## Expected behavior
I need to read the result of the query started with the start_query command

## Actual behavior
When I try to use the command the localstack console prints
```sh
Error on request:

Traceback (most recent call last):

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi

execute(self.server.app)

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute

application_iter = app(environ, start_response)

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 178, in __call__

return backend_app(environ, start_response)

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__

return self.wsgi_app(environ, start_response)

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app

response = self.handle_exception(e)

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function

return cors_after_request(app.make_response(f(*args, **kwargs)))

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function

return cors_after_request(app.make_response(f(*args, **kwargs)))

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app

response = self.full_dispatch_request()

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request

rv = self.handle_user_exception(e)

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function

return cors_after_request(app.make_response(f(*args, **kwargs)))

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function

return cors_after_request(app.make_response(f(*args, **kwargs)))

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request

rv = self.dispatch_request()

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request

return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 156, in __call__

result = self.callback(request, request.url, {})

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 205, in dispatch

return cls()._dispatch(*args, **kwargs)

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 315, in _dispatch

return self.call_action()

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 418, in call_action

"The {0} action has not been implemented".format(action)

NotImplementedError: The get_query_results action has not been implemented
```

# Steps to reproduce
Lunch the get_query_result command from cli or nodejs

## Command used to start LocalStack
I use docker as described in  #4078 
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by terence-cevo** [comment]
> Hello 👋! It looks like this issue hasn’t been active in longer than five months. We encourage you to check if this is still an issue in the latest release. In the absence of more information, we will be closing this issue soon. If you find that this is still a problem, please feel free to provide a comment or upvote with a reaction on the initial post to prevent automatic closure. If the issue is already closed, please feel free to open a new one.

This issue is not fixed

**Comment by gerald-wol** [comment]
Unfortunately still an issue today! get_query_results is not implemented :(
