### ISSUE TITLE
[PRO] CDK deploy failure after CDK delete -- even with empty CDK stack

### ISSUE THREAD

**Issue by beegeevee** [localstack/localstack#4154]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

1. Create empty CDK project: `cdk init app -l typescript`
2. Configure docker-compose.yml, localstack API key
3. Start localstack: `TMPDIR=/private$TMPDIR docker-compose up`
4. Wait for localstack 'Ready.'
5. Bootstrap CDK: `CDK_NEW_BOOTSTRAP=1 cdklocal bootstrap`
6. Deploy empty CDK stack: `cdklocal deploy`
7. Destroy empty CDK stack: `cdklocal destroy`
8. Deploy again: `cdklocal deploy`

## Expected behavior

CDK Deploy completes successfully.

## Actual behavior

CDK deploy hangs; exceptions in localstack log.

localstack log shows this exception, repeated 9 times:
```
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
localstack_main |     response = self.full_dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
localstack_main |     rv = self.handle_user_exception(e)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
localstack_main |     rv = self.dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
localstack_main |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 747, in handle_request
localstack_main |     result = func(req_params)
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 593, in execute_change_set
localstack_main |     deployer.apply_change_set(change_set)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1602, in apply_change_set
localstack_main |     self.apply_changes(change_set.stack, change_set, stack_name=change_set.stack_name, action=action)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1835, in apply_changes
localstack_main |     raise NoStackUpdates('No updates are to be performed.')
localstack_main | localstack.utils.cloudformation.template_deployer.NoStackUpdates: No updates are to be performed.
```

# Steps to reproduce

See above.

## Command used to start LocalStack
`TMPDIR=/private$TMPDIR docker-compose up`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

docker-compose.yml:
```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "4566:4566"
      - "4571:4571"
      - "4514:4514"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - .env
```

**Comment by whummer** [comment]
Thanks for reporting @beegeevee . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks!
