### ISSUE TITLE
[PRO] Neptune ServerDisconnectError using gremlin-client

### ISSUE THREAD

**Issue by klaymo** [localstack/localstack#4189]
[x] bug report
[ ] feature request

# Detailed description

Trying to use the example referenced here: https://github.com/localstack/localstack-pro-samples/tree/master/neptune-graph-db I am unable to issue request with the local Neptune/Tinkerpop server, commands receive `aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected`

It does appear to create the "cluster" and I can run awslocal commands for neptune, but cannot connect or at least make requests to the instance. Fair warning, I am not a neptune or tinkerpop expert by any stretch, I was just trying to test things out. I am happy to try any changes you recommend to test out more.

I am able to run Tinkerpop locally using `tinkerpop/gremlin-server:latest` and can confirm that requests work and create vertices. Since I can run it locally this isn't really a big deal, but wanted to share my experience.

# Steps to reproduce

## Command used to start LocalStack

`make run` from the repo above

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Using `gremlinpython==3.5.0` `localstack==0.12.13` `localstack-client==1.20` `localstack-ext==0.12.10.7`

Container Details:
LocalStack version: 0.12.12
LocalStack Docker container id: 1b2d13062e44
LocalStack build date: 2021-06-16
LocalStack build git hash: 4b1169f9

Command and Traceback
```
$ make run
Creating Neptune Graph DB cluster "cluster123" - this may take a few moments ...
Connecting to Neptune Graph DB cluster URL: ws://localhost:4510/gremlin
Submitting values: [1,2,3,4]
Traceback (most recent call last):
  File "query.py", line 77, in <module>
    main()
  File "query.py", line 71, in main
    run_queries(instance)
  File "query.py", line 21, in run_queries
    result_set = graph_client.submit(values)
  File "<WORKDIR>/venv/lib/python3.8/site-packages/gremlin_python/driver/client.py", line 132, in submit
    return self.submitAsync(message, bindings=bindings, request_options=request_options).result()
  File "<WORKDIR>/venv/lib/python3.8/site-packages/gremlin_python/driver/client.py", line 153, in submitAsync
    return conn.write(message)
  File "<WORKDIR>/venv/lib/python3.8/site-packages/gremlin_python/driver/connection.py", line 55, in write
    self.connect()
  File "<WORKDIR>/venv/lib/python3.8/site-packages/gremlin_python/driver/connection.py", line 45, in connect
    self._transport.connect(self._url, self._headers)
  File "<WORKDIR>/venv/lib/python3.8/site-packages/gremlin_python/driver/aiohttp/transport.py", line 77, in connect
    self._loop.run_until_complete(async_connect())
  File "/Users/kmoore/.pyenv/versions/3.8.2/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "<WORKDIR>/venv/lib/python3.8/site-packages/gremlin_python/driver/aiohttp/transport.py", line 67, in async_connect
    self._websocket = await self._client_session.ws_connect(url, **self._aiohttp_kwargs, headers=headers)
  File "<WORKDIR>/venv/lib/python3.8/site-packages/aiohttp/client.py", line 754, in _ws_connect
    resp = await self.request(
  File "<WORKDIR>/venv/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "<WORKDIR>/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "<WORKDIR>/venv/lib/python3.8/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x108568a90>
make: *** [run] Error 1```

**Comment by whummer** [comment]
Thanks for reporting @klaymo . This issue should already be fixed in the meantime - can you please do a `docker pull localstack/localstack` and give it another try with the `latest` Docker image? Please let us know if the problem persists. Thanks for your help!

**Comment by klaymo** [comment]
@whummer this is working for me now, thanks!
