### ISSUE TITLE
Support DocumentDB

### ISSUE THREAD

**Issue by matthewvalimaki** [localstack/localstack#4201]
# Type of request:

[ ] bug report
[X] feature request

# Detailed description
Can we consider adding support for DocumentDB? At some point it was supported it would seem as `docdb` service exists but it causes the following exception. I do understand that there's no ready package for mongodb in Alpine community anymore but perhaps it could be built by LocalStack team?
```
ERROR: 'apk add mongodb': exit code 1; output: b'fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz\nfetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz\nERROR: unable to select packages:\n  mongodb (no such package):\n    required by: world[mongodb]\n'
2021-06-24T22:42:15:INFO:localstack_ext.services.rds.rds_listener: Error processing response for RDS API request "CreateDBCluster": Command 'apk add mongodb' returned non-zero exit status 1. Traceback (most recent call last):  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/rds/rds_listener.py", line 153, in return_response
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/rds/rds_listener.py", line 225, in create_db_cluster_response
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/rds/rds_listener.py", line 607, in startup_db_instance
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/rds/db_utils.py", line 60, in start_db_instance_async
  File "/opt/code/localstack/localstack/utils/common.py", line 1463, in run_for_max_seconds
    raise result
  File "/opt/code/localstack/localstack/utils/common.py", line 1446, in _worker
    result = _function(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/rds/db_utils.py", line 57, in do_startup
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/docdb/docdb_api.py", line 15, in start_db_instance
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/docdb/docdb_api.py", line 27, in install_doc_db
  File "/opt/code/localstack/localstack/utils/common.py", line 1475, in run
    return do_run(cmd)
  File "/opt/code/localstack/localstack/utils/common.py", line 1472, in do_run
    return bootstrap.run(cmd, **kwargs)
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 776, in run
    raise e
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 736, in run
    output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'apk add mongodb' returned non-zero exit status 1.
```

**Comment by whummer** [comment]
Thanks for reporting @matthewvalimaki . This should be (hopefully) fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please keep us posted how it goes. Thanks for your help!
