### ISSUE TITLE
Add required new Lambda managed policies, warn about deprecated ones being used

### ISSUE THREAD

**Issue by delitescere** [localstack/localstack#4202]
# Type of request: This is a ...

[❌] bug report
[ ] feature request

# Detailed description

According to https://docs.aws.amazon.com/lambda/latest/dg/access-control-identity-based.html

> The AWS managed policies AWSLambdaFullAccess and AWSLambdaReadOnlyAccess will be deprecated on March 1, 2021. After this date, you cannot attach these policies to new IAM users. For more information, see the related [troubleshooting topic](https://docs.aws.amazon.com/lambda/latest/dg/security_iam_troubleshoot.html#security_iam_troubleshoot-admin-deprecation).

I was having problems creating a new Lambda (from Pulumi) and the following appeared (many times) in the LocalStack log (the last line is the clue):

```shell
2021-06-25 01:39:40,086:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 173, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 151, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 202, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 312, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 397, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/iam/responses.py", line 12, in attach_role_policy
    iam_backend.attach_role_policy(policy_arn, role_name)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/iam/models.py", line 1425, in attach_role_policy
    policy = arns[policy_arn]
KeyError: 'arn:aws:iam::aws:policy/AWSLambda_FullAccess'
```

## Expected behavior

The new managed policy names should exist.

## Actual behavior

I checked if LocalStack uses the new managed policy name or not. It's "not":

```shell
awslocal iam list-policies | grep AWSLambda
            "PolicyName": "AWSLambdaBasicExecutionRole",
            "Arn": "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
            "PolicyName": "AWSLambdaDynamoDBExecutionRole",
            "Arn": "arn:aws:iam::aws:policy/service-role/AWSLambdaDynamoDBExecutionRole",
            "PolicyName": "AWSLambdaENIManagementAccess",
            "Arn": "arn:aws:iam::aws:policy/service-role/AWSLambdaENIManagementAccess",
            "PolicyName": "AWSLambdaExecute",
            "Arn": "arn:aws:iam::aws:policy/AWSLambdaExecute",
            "PolicyName": "AWSLambdaFullAccess",
            "Arn": "arn:aws:iam::aws:policy/AWSLambdaFullAccess",
            "PolicyName": "AWSLambdaInvocation-DynamoDB",
            "Arn": "arn:aws:iam::aws:policy/AWSLambdaInvocation-DynamoDB",
            "PolicyName": "AWSLambdaKinesisExecutionRole",
            "Arn": "arn:aws:iam::aws:policy/service-role/AWSLambdaKinesisExecutionRole",
            "PolicyName": "AWSLambdaReadOnlyAccess",
            "Arn": "arn:aws:iam::aws:policy/AWSLambdaReadOnlyAccess",
            "PolicyName": "AWSLambdaReplicator",
            "Arn": "arn:aws:iam::aws:policy/aws-service-role/AWSLambdaReplicator",
            "PolicyName": "AWSLambdaRole",
            "Arn": "arn:aws:iam::aws:policy/service-role/AWSLambdaRole",
            "PolicyName": "AWSLambdaSQSQueueExecutionRole",
            "Arn": "arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole",
            "PolicyName": "AWSLambdaVPCAccessExecutionRole",
            "Arn": "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole",
```

# Steps to reproduce

## Command used to start LocalStack

`DEBUG=1 SERVICES=serverless localstack start`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

`aws --endpoint-url http://localhost:4566 iam list-policies | grep AWSLambda`

**Comment by delitescere** [comment]
This could be an issue in the downstream dependency https://github.com/aws-cloudformation/cfn-lint

**Comment by delitescere** [comment]
I've confirmed that changing the `ManagedPolicies.json` file in `cfn-lint` is all that's needed to have LocalStack work as expected. See https://github.com/aws-cloudformation/cfn-lint/pull/2062

**Comment by whummer** [comment]
Awesome, thanks for raising the upstream PR @delitescere ! 👍  The next release of `cfn-lint` should automatically get released into the LocalStack Docker image. Please let us know if there's anything else required on our end. Thanks for your help!
