### ISSUE TITLE
Startup fails with DATA_DIR and kinesis-mock

### ISSUE THREAD

**Issue by thrau** [localstack/localstack#4227]
# Type of request: This is a ...

bug report

# Detailed description

localstack fails to start correctly with `DATA_DIR` and the kinesis-mock kinesis provider

## Expected behavior

localstack should start correctly

## Actual behavior

instead the startup throws error messages like these:

```
76b772e7226f_localstackmain  | 
76b772e7226f_localstackmain  | Traceback (most recent call last):
76b772e7226f_localstackmain  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 129, in index
76b772e7226f_localstackmain  |     raise result
76b772e7226f_localstackmain  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 701, in run
76b772e7226f_localstackmain  |     result = self.func(self.params, **kwargs)
76b772e7226f_localstackmain  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 29, in _run
76b772e7226f_localstackmain  |     return fn(*args, **kwargs)
76b772e7226f_localstackmain  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 428, in handler
76b772e7226f_localstackmain  |     client_address=request.remote_addr, server_address=parsed_url.netloc)
76b772e7226f_localstackmain  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 244, in modify_and_forward
76b772e7226f_localstackmain  |     listener_result = listener.forward_request(method=method, path=path, data=data, headers=headers)
76b772e7226f_localstackmain  |   File "/opt/code/localstack/localstack/services/edge.py", line 122, in forward_request
76b772e7226f_localstackmain  |     return do_forward_request(api, method, path, data, headers, port=port)
76b772e7226f_localstackmain  |   File "/opt/code/localstack/localstack/services/edge.py", line 143, in do_forward_request
76b772e7226f_localstackmain  |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
76b772e7226f_localstackmain  |   File "/opt/code/localstack/localstack/services/edge.py", line 165, in do_forward_request_inmem
76b772e7226f_localstackmain  |     client_address=client_address, server_address=server_address)
76b772e7226f_localstackmain  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 290, in modify_and_forward
76b772e7226f_localstackmain  |     response = requests.request(method, request_url, data=data_to_send, headers=headers, stream=True, verify=False)
76b772e7226f_localstackmain  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/api.py", line 61, in request
76b772e7226f_localstackmain  |     return session.request(method=method, url=url, **kwargs)
76b772e7226f_localstackmain  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
76b772e7226f_localstackmain  |     resp = self.send(prep, **send_kwargs)
76b772e7226f_localstackmain  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
76b772e7226f_localstackmain  |     r = adapter.send(request, **kwargs)
76b772e7226f_localstackmain  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
76b772e7226f_localstackmain  |     raise ConnectionError(e, request=request)
76b772e7226f_localstackmain  | requests.exceptions.ConnectionError: MyHTTPConnectionPool(host='localhost', port=56787): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbe40c9aed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
76b772e7226f_localstackmain  | 
76b772e7226f_localstackmain  | 2021-06-28T17:54:34:WARNING:localstack.services.plugins: Service "kinesis" not yet available, retrying...
^CGracefully stopping... (press Ctrl+C again to force)
```

# Steps to reproduce

## Command used to start LocalStack

    DATA_DIR=/tmp/localstack/data DEBUG=1 bin/localstack start --host

**Comment by thrau** [comment]
The root cause is https://github.com/etspaceman/kinesis-mock/issues/129, as kinesis-mock fails to start and then it can't connect to the service

once fixed and released, we should update to kinsesis-mock 0.1.3.

moreover we should consider improving the logging output of the starting procedure. the log output is spammed with unhelpful `ConnectionError` traces.

**Comment by thrau** [comment]
as a workaround, in older localstack versions, you can use kinesalite as a provider. set the environment variable `KINESIS_PROVIDER=kinesalite`, in `:latest` we have a workaround

**Comment by etspaceman** [comment]
I've created #4268 to fix this.

**Comment by thrau** [comment]
thanks @etspaceman! i'll remove the workaround and test it with the new version.
