### ISSUE TITLE
The create_managed_prefix_list action has not been implemented

### ISSUE THREAD

**Issue by SagarKadambi** [localstack/localstack#4229]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

While trying to create a managed prefix list, i am getting the following error : 
```The create_managed_prefix_list action has not been implemented```

This is the debug  output i get when trying to create the ressource : 
```
$ docker run --rm -it -p 4566:4566 -e DEBUG=1 -e DEFAULT_REGION=us-west-2 -e SERVICES=ec2,s3,kms,iam,lambda,secretsmanager,cloudwatch,cloudwatchevents,dynamodb,sts localstack/localstack
Waiting for all LocalStack services to be ready
2021-06-28 19:34:41,624 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-06-28 19:34:41,627 INFO supervisord started with pid 14
2021-06-28 19:34:42,631 INFO spawned: 'dashboard' with pid 20
2021-06-28 19:34:42,633 INFO spawned: 'infra' with pid 21
2021-06-28 19:34:42,638 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-06-28 19:34:42,638 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
Starting local dev environment. CTRL-C to quit.
2021-06-28 19:34:44,321 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

LocalStack version: 0.12.13
LocalStack build date: 2021-06-24
LocalStack build git hash: a08b3239

2021-06-28T19:34:47:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f9c6e6c2dd0>
Starting edge router (https port 4566)...
Starting mock CloudWatch service on http port 4566 ...
Starting mock DynamoDB service on http port 4566 ...
Starting mock DynamoDB Streams service on http port 4566 ...
Starting mock EC2 service on http port 4566 ...
Starting mock IAM service on http port 4566 ...
Starting mock STS service on http port 4566 ...
Starting mock KMS service on http port 4566 ...
INFO[2021-06-28 19:34:47.886] Local KMS 3.9.1 (4e5eb289efb23f9059ae4b1f9896bad6c9a499f2)
INFO[2021-06-28 19:34:47.896] No file found at path /init/seed.yaml; skipping seeding.
INFO[2021-06-28 19:34:47.896] Data will be stored in /tmp/local-kms
INFO[2021-06-28 19:34:47.897] Local KMS started on 0.0.0.0:45653
Initializing DynamoDB Local with the following configuration:
Port:	42119
InMemory:	true
DbPath:	null
SharedDb:	false
shouldDelayTransientStatuses:	false
CorsParams:	*

[ioapp-compute-1] INFO  2021-06-28 19:34:48 k.m.KinesisMockService contextId=e62fa80f-d847-11eb-b2e0-05d1fccc6cbc, cacheConfig={"awsAccountId":"000000000000","awsRegion":"us-west-2","createStreamDuration":{"length":500,"unit":"MILLISECONDS"},"deleteStreamDuration":{"length":500,"unit":"MILLISECONDS"},"deregisterStreamConsumerDuration":{"length":500,"unit":"MILLISECONDS"},"initializeStreams":null,"mergeShardsDuration":{"length":500,"unit":"MILLISECONDS"},"persistConfig":{"fileName":"kinesis-data.json","interval":{"length":5,"unit":"SECONDS"},"loadIfExists":true,"path":"data","shouldPersist":false},"registerStreamConsumerDuration":{"length":500,"unit":"MILLISECONDS"},"shardLimit":100,"splitShardDuration":{"length":500,"unit":"MILLISECONDS"},"startStreamEncryptionDuration":{"length":500,"unit":"MILLISECONDS"},"stopStreamEncryptionDuration":{"length":500,"unit":"MILLISECONDS"},"updateShardCountDuration":{"length":500,"unit":"MILLISECONDS"}} - Logging Cache Config
[ioapp-compute-0] INFO  2021-06-28 19:34:48 k.m.KinesisMockService  - Starting Kinesis TLS Mock Service on port 4567
[ioapp-compute-0] INFO  2021-06-28 19:34:48 k.m.KinesisMockService  - Starting Kinesis Plain Mock Service on port 37391
[ioapp-compute-0] INFO  2021-06-28 19:34:48 k.m.KinesisMockService contextId=e64b1551-d847-11eb-b2e0-05d1fccc6cbc - Not configured to persist data, persist loop not started
2021-06-28T19:34:47:DEBUG:localstack.services.install: getting kinesis-mock for linux x86_64
2021-06-28T19:34:47:DEBUG:localstack.services.install: kinesis-mock found at /opt/code/localstack/localstack/infra/kinesis-mock/kinesis-mock-linux-amd64-static
2021-06-28T19:34:47:INFO:localstack.multiserver: Starting multi API server process on port 40309
[2021-06-28 19:34:47 +0000] [22] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-06-28T19:34:47:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
[2021-06-28 19:34:47 +0000] [22] [INFO] Running on http://0.0.0.0:40309 (CTRL + C to quit)
2021-06-28T19:34:47:INFO:hypercorn.error: Running on http://0.0.0.0:40309 (CTRL + C to quit)
2021-06-28 19:34:47,610:API:  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-06-28 19:34:47,610:API:  * Running on http://172.17.0.2:55267/ (Press CTRL+C to quit)
2021-06-28T19:34:47:DEBUG:localstack.services.install: getting kinesis-mock for linux x86_64
2021-06-28T19:34:47:DEBUG:localstack.services.install: kinesis-mock found at /opt/code/localstack/localstack/infra/kinesis-mock/kinesis-mock-linux-amd64-static
2021-06-28T19:34:47:INFO:localstack.services.kinesis.kinesis_starter: starting kinesis-mock proxy 4566:37391 with cmd: KINESIS_MOCK_PLAIN_PORT=37391 SHARD_LIMIT=100 CREATE_STREAM_DURATION=500ms DELETE_STREAM_DURATION=500ms REGISTER_STREAM_CONSUMER_DURATION=500ms START_STREAM_ENCRYPTION_DURATION=500ms STOP_STREAM_ENCRYPTION_DURATION=500ms DEREGISTER_STREAM_CONSUMER_DURATION=500ms MERGE_SHARDS_DURATION=500ms SPLIT_SHARD_DURATION=500ms UPDATE_SHARD_COUNT_DURATION=500ms  LOG_LEVEL=INFO  /opt/code/localstack/localstack/infra/kinesis-mock/kinesis-mock-linux-amd64-static --gc=G1
Waiting for all LocalStack services to be ready
Starting mock Lambda service on http port 4566 ...
Starting mock CloudWatch Logs service on http port 4566 ...
Starting mock S3 service on http port 4566 ...
Starting mock Secrets Manager service on http port 4566 ...
Waiting for all LocalStack services to be ready
Ready.
2021-06-28T19:34:58:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 11154.03ms
2021-06-28 19:36:30,935:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 177, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 156, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 205, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 315, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 420, in call_action
    "The {0} action has not been implemented".format(action)
NotImplementedError: The create_managed_prefix_list action has not been implementedSRKADAMB-M-309Z:dlp-policy-propagation srkadamb$ docker run --rm -it -p 4566:4566 -e DEBUG=1 -e DEFAULT_REGION=us-west-2 -e SERVICES=ec2,s3,kms,iam,lambda,secretsmanager,cloudwatch,cloudwatchevents,dynamodb,sts localstack/localstack
Waiting for all LocalStack services to be ready
2021-06-28 19:34:41,624 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-06-28 19:34:41,627 INFO supervisord started with pid 14
2021-06-28 19:34:42,631 INFO spawned: 'dashboard' with pid 20
2021-06-28 19:34:42,633 INFO spawned: 'infra' with pid 21
2021-06-28 19:34:42,638 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-06-28 19:34:42,638 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
Starting local dev environment. CTRL-C to quit.
2021-06-28 19:34:44,321 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

LocalStack version: 0.12.13
LocalStack build date: 2021-06-24
LocalStack build git hash: a08b3239

2021-06-28T19:34:47:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f9c6e6c2dd0>
Starting edge router (https port 4566)...
Starting mock CloudWatch service on http port 4566 ...
Starting mock DynamoDB service on http port 4566 ...
Starting mock DynamoDB Streams service on http port 4566 ...
Starting mock EC2 service on http port 4566 ...
Starting mock IAM service on http port 4566 ...
Starting mock STS service on http port 4566 ...
Starting mock KMS service on http port 4566 ...
INFO[2021-06-28 19:34:47.886] Local KMS 3.9.1 (4e5eb289efb23f9059ae4b1f9896bad6c9a499f2)
INFO[2021-06-28 19:34:47.896] No file found at path /init/seed.yaml; skipping seeding.
INFO[2021-06-28 19:34:47.896] Data will be stored in /tmp/local-kms
INFO[2021-06-28 19:34:47.897] Local KMS started on 0.0.0.0:45653
Initializing DynamoDB Local with the following configuration:
Port:	42119
InMemory:	true
DbPath:	null
SharedDb:	false
shouldDelayTransientStatuses:	false
CorsParams:	*

[ioapp-compute-1] INFO  2021-06-28 19:34:48 k.m.KinesisMockService contextId=e62fa80f-d847-11eb-b2e0-05d1fccc6cbc, cacheConfig={"awsAccountId":"000000000000","awsRegion":"us-west-2","createStreamDuration":{"length":500,"unit":"MILLISECONDS"},"deleteStreamDuration":{"length":500,"unit":"MILLISECONDS"},"deregisterStreamConsumerDuration":{"length":500,"unit":"MILLISECONDS"},"initializeStreams":null,"mergeShardsDuration":{"length":500,"unit":"MILLISECONDS"},"persistConfig":{"fileName":"kinesis-data.json","interval":{"length":5,"unit":"SECONDS"},"loadIfExists":true,"path":"data","shouldPersist":false},"registerStreamConsumerDuration":{"length":500,"unit":"MILLISECONDS"},"shardLimit":100,"splitShardDuration":{"length":500,"unit":"MILLISECONDS"},"startStreamEncryptionDuration":{"length":500,"unit":"MILLISECONDS"},"stopStreamEncryptionDuration":{"length":500,"unit":"MILLISECONDS"},"updateShardCountDuration":{"length":500,"unit":"MILLISECONDS"}} - Logging Cache Config
[ioapp-compute-0] INFO  2021-06-28 19:34:48 k.m.KinesisMockService  - Starting Kinesis TLS Mock Service on port 4567
[ioapp-compute-0] INFO  2021-06-28 19:34:48 k.m.KinesisMockService  - Starting Kinesis Plain Mock Service on port 37391
[ioapp-compute-0] INFO  2021-06-28 19:34:48 k.m.KinesisMockService contextId=e64b1551-d847-11eb-b2e0-05d1fccc6cbc - Not configured to persist data, persist loop not started
2021-06-28T19:34:47:DEBUG:localstack.services.install: getting kinesis-mock for linux x86_64
2021-06-28T19:34:47:DEBUG:localstack.services.install: kinesis-mock found at /opt/code/localstack/localstack/infra/kinesis-mock/kinesis-mock-linux-amd64-static
2021-06-28T19:34:47:INFO:localstack.multiserver: Starting multi API server process on port 40309
[2021-06-28 19:34:47 +0000] [22] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-06-28T19:34:47:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
[2021-06-28 19:34:47 +0000] [22] [INFO] Running on http://0.0.0.0:40309 (CTRL + C to quit)
2021-06-28T19:34:47:INFO:hypercorn.error: Running on http://0.0.0.0:40309 (CTRL + C to quit)
2021-06-28 19:34:47,610:API:  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-06-28 19:34:47,610:API:  * Running on http://172.17.0.2:55267/ (Press CTRL+C to quit)
2021-06-28T19:34:47:DEBUG:localstack.services.install: getting kinesis-mock for linux x86_64
2021-06-28T19:34:47:DEBUG:localstack.services.install: kinesis-mock found at /opt/code/localstack/localstack/infra/kinesis-mock/kinesis-mock-linux-amd64-static
2021-06-28T19:34:47:INFO:localstack.services.kinesis.kinesis_starter: starting kinesis-mock proxy 4566:37391 with cmd: KINESIS_MOCK_PLAIN_PORT=37391 SHARD_LIMIT=100 CREATE_STREAM_DURATION=500ms DELETE_STREAM_DURATION=500ms REGISTER_STREAM_CONSUMER_DURATION=500ms START_STREAM_ENCRYPTION_DURATION=500ms STOP_STREAM_ENCRYPTION_DURATION=500ms DEREGISTER_STREAM_CONSUMER_DURATION=500ms MERGE_SHARDS_DURATION=500ms SPLIT_SHARD_DURATION=500ms UPDATE_SHARD_COUNT_DURATION=500ms  LOG_LEVEL=INFO  /opt/code/localstack/localstack/infra/kinesis-mock/kinesis-mock-linux-amd64-static --gc=G1
Waiting for all LocalStack services to be ready
Starting mock Lambda service on http port 4566 ...
Starting mock CloudWatch Logs service on http port 4566 ...
Starting mock S3 service on http port 4566 ...
Starting mock Secrets Manager service on http port 4566 ...
Waiting for all LocalStack services to be ready
Ready.
2021-06-28T19:34:58:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 11154.03ms
2021-06-28 19:36:30,935:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 177, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 156, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 205, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 315, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 420, in call_action
    "The {0} action has not been implemented".format(action)
NotImplementedError: The create_managed_prefix_list action has not been implemented
```
```
$ aws --version
aws-cli/2.2.14 Python/3.8.8 Darwin/19.6.0 exe/x86_64 prompt/off
```

## Expected behavior

Should be able to create the managed prefix list within localstack.

## Actual behavior

Get a 500 error when i try to create the managed prefix list :
```
$ awslocal ec2 create-managed-prefix-list     --address-family IPv4     --max-entries 10     --entries Cidr=10.0.0.0/16,Description=vpc-a Cidr=10.2.0.0/16,Description=vpc-b     --prefix-list-name vpc-cidrs

Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

# Steps to reproduce

## Command used to start LocalStack

```$ docker run --rm -it -p 4566:4566 -e DEBUG=1 -e DEFAULT_REGION=us-west-2 -e SERVICES=ec2,s3,kms,iam,lambda,secretsmanager,cloudwatch,cloudwatchevents,dynamodb,sts localstack/localstack```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by usmangani1** [comment]
@SagarKadambi  Thanks for reporting the issue. 

We are working on implementing the given functionality. Please let us know if you need any other functionalities related to create-managed-prefix-list to be also implemented.Thanks
