### ISSUE TITLE
Failed installation on MacOS Sierra 

### ISSUE THREAD

**Issue by jeson114** [localstack/localstack#423]
```bash
Installing collected packages: six, cachetools, airspeed, docutils, jmespath, python-dateutil, botocore, pyYAML, pyasn1, rsa, futures, s3transfer, colorama, awscli, boto, boto3, coverage, docopt, urllib3, elasticsearch, pycodestyle, enum34, configparser, pyflakes, mccabe, flake8, flake8-quotes, Werkzeug, MarkupSafe, Jinja2, itsdangerous, flask, flask-cors, flask-swagger, ply, decorator, jsonpath-rw, dnslib, pyaes, pyminifier, srp-ext, envs, funcsigs, pbr, mock, pycryptodome, ecdsa, future, python-jose-ext, idna, certifi, chardet, requests, warrant-ext, localstack-ext, cookies, dicttoxml, pytz, pyaml, xmltodict, moto-ext, nose, psutil, pycparser, cffi, asn1crypto, ipaddress, cryptography, pyOpenSSL, sh, python-coveralls, requests-aws4auth, subprocess32-ext, localstack
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/six.py'
```
Something with the version of six i suppose ?

**Comment by arnocornette** [comment]
Try checking this issue: #260

**Comment by jeson114** [comment]
Yup that worked for me . Thanks

**Comment by whummer** [comment]
Great, glad it works. Added a note to the [Troubleshooting section](https://github.com/localstack/localstack/blob/master/README.md#troubleshooting) of the README.
