### ISSUE TITLE
CloudFormationTest::test_create_delete_stack fails with kinesis-mock 0.1.1

### ISSUE THREAD

**Issue by thrau** [localstack/localstack#4233]
When updating kinesis-mock to 0.1.1, and running the test `DEBUG=1 TEST_PATH='-k test_create_delete_stack' make test`, it fails because it cannot delete the kinesis stream:

```
DEBUG    localstack.utils.cloudformation.template_deployer:template_deployer.py:1044 Running action "delete" for resource type "Kinesis::Stream" id "KinesisStream"
DEBUG    localstack.utils.cloudformation.template_deployer:template_deployer.py:1171 Request for resource type "Kinesis::Stream" in region us-east-1: delete_stream {'StreamName': 'cf-test-stream-1'}
WARNING  localstack.utils.cloudformation.template_deployer:template_deployer.py:520 Unexpected error retrieving details for resource type Kinesis::Stream: Exception: An error occurred (ResourceInUseException) when calling the DeleteStream operation: Consumers exist in stream cf-test-stream-1 and enforceConsumerDeletion is either not set or is false - {'Type': 'AWS::Kinesis::Stream', 'Properties': {'Name': 'cf-test-stream-1'}, 'LogicalResourceId': 'KinesisStream', 'PhysicalResourceId': 'arn:aws:kinesis:us-east-1:000000000000:stream/cf-test-stream-1', '_state_': {'StreamDescription': {'StreamName': 'cf-test-stream-1', 'StreamARN': 'arn:aws:kinesis:us-east-1:000000000000:stream/cf-test-stream-1', 'StreamStatus': 'ACTIVE', 'Shards': [{'ShardId': 'shardId-000000000000', 'HashKeyRange': {'StartingHashKey': '0', 'EndingHashKey': '340282366920938463463374607431768211455'}, 'SequenceNumberRange': {'StartingSequenceNumber': '49619661137645182639008499027312543635082646823651770370'}}], 'HasMoreShards': False, 'RetentionPeriodHours': 24, 'StreamCreationTimestamp': '2021-06-29T10:47:13.935Z', 'EnhancedMonitoring': [{'ShardLevelMetrics': []}], 'EncryptionType': 'NONE'}, 'ResponseMetadata': {'RequestId': '9a425e3f-d8b6-11eb-b1d8-9ffd1d777bd2', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1', 'content-length': '661', 'x-amz-id-2': 'CrGSLMObuxZb2rbbgMKPmOAb28XPDB1+CInsnH62nOU63GqJUs+Agw7doeCih/7rGPU5wFDsaqm1S+EWXQoOqqbQOMOKhkbh', 'x-amzn-requestid': '9a425e3f-d8b6-11eb-b1d8-9ffd1d777bd2', 'connection': 'close', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'date': 'Tue, 29 Jun 2021 08:47:14 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}, 'ResourceType': 'AWS::Kinesis::Stream'} - status: None
WARNING  localstack.utils.cloudformation.template_deployer:template_deployer.py:1177 Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.Kinesis object at 0x7fdb4cb79d60>> with params: {'StreamName': 'cf-test-stream-1'} for resource: {'Type': 'AWS::Kinesis::Stream', 'Properties': {'Name': 'cf-test-stream-1'}, 'LogicalResourceId': 'KinesisStream', 'PhysicalResourceId': 'arn:aws:kinesis:us-east-1:000000000000:stream/cf-test-stream-1', '_state_': {'StreamDescription': {'StreamName': 'cf-test-stream-1', 'StreamARN': 'arn:aws:kinesis:us-east-1:000000000000:stream/cf-test-stream-1', 'StreamStatus': 'ACTIVE', 'Shards': [{'ShardId': 'shardId-000000000000', 'HashKeyRange': {'StartingHashKey': '0', 'EndingHashKey': '340282366920938463463374607431768211455'}, 'SequenceNumberRange': {'StartingSequenceNumber': '49619661137645182639008499027312543635082646823651770370'}}], 'HasMoreShards': False, 'RetentionPeriodHours': 24, 'StreamCreationTimestamp': '2021-06-29T10:47:13.935Z', 'EnhancedMonitoring': [{'ShardLevelMetrics': []}], 'EncryptionType': 'NONE'}, 'ResponseMetadata': {'RequestId': '9a425e3f-d8b6-11eb-b1d8-9ffd1d777bd2', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/x-amz-json-1.1', 'content-length': '661', 'x-amz-id-2': 'CrGSLMObuxZb2rbbgMKPmOAb28XPDB1+CInsnH62nOU63GqJUs+Agw7doeCih/7rGPU5wFDsaqm1S+EWXQoOqqbQOMOKhkbh', 'x-amzn-requestid': '9a425e3f-d8b6-11eb-b1d8-9ffd1d777bd2', 'connection': 'close', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'date': 'Tue, 29 Jun 2021 08:47:14 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}, 'ResourceType': 'AWS::Kinesis::Stream'}
ERROR    cloudformation_api:app.py:1454 Exception on / [POST]
Traceback (most recent call last):
  File "/home/thomas/workspace/localstack/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thomas/workspace/localstack/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thomas/workspace/localstack/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/thomas/workspace/localstack/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thomas/workspace/localstack/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/thomas/workspace/localstack/localstack/localstack/services/cloudformation/cloudformation_api.py", line 747, in handle_request
    result = func(req_params)
  File "/home/thomas/workspace/localstack/localstack/localstack/services/cloudformation/cloudformation_api.py", line 430, in delete_stack
    deployer.delete_stack()
  File "/home/thomas/workspace/localstack/localstack/localstack/utils/cloudformation/template_deployer.py", line 1634, in delete_stack
    delete_resource(resource_id, resources, stack_name)
  File "/home/thomas/workspace/localstack/localstack/localstack/utils/cloudformation/template_deployer.py", line 1015, in delete_resource
    return execute_resource_action(resource_id, resources, stack_name, ACTION_DELETE)
  File "/home/thomas/workspace/localstack/localstack/localstack/utils/cloudformation/template_deployer.py", line 1055, in execute_resource_action
    result = configure_resource_via_sdk(resource_id, resources, resource_type, func, stack_name, action_name)
  File "/home/thomas/workspace/localstack/localstack/localstack/utils/cloudformation/template_deployer.py", line 1178, in configure_resource_via_sdk
    raise e
  File "/home/thomas/workspace/localstack/localstack/localstack/utils/cloudformation/template_deployer.py", line 1173, in configure_resource_via_sdk
    result = function(**params)
  File "/home/thomas/workspace/localstack/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/thomas/workspace/localstack/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceInUseException: An error occurred (ResourceInUseException) when calling the DeleteStream operation: Consumers exist in stream cf-test-stream-1 and enforceConsumerDeletion is either not set or is false
```

Seems to be related to/caused by:
https://github.com/etspaceman/kinesis-mock/pull/121
https://github.com/etspaceman/kinesis-mock/issues/120

**Comment by thrau** [comment]
any ideas for a fix @whummer ?

currently this blocks #4232 needed for #4227

**Comment by whummer** [comment]
Should be fixed in the meantime 👍. Thanks @thrau
