### ISSUE TITLE
bug: Kibana endpoint not working as expected

### ISSUE THREAD

**Issue by csnick93** [localstack/localstack#4234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am setting up an elastic search cluster using terraform. The elastic search cluster is working as expected; however, the kibana endpoint is not (while with AWS + Terraform it's working). When navigating to `http://localhost:4571/_plugin/kibana`, the response is `{"error":"Incorrect HTTP method for uri [/_plugin/kibana] and method [GET], allowed: [POST]","status":405}`. 

### Expected Behavior

When navigating to `http://localhost:4571/_plugin/kibana`, I was expecting to be forwarded to a login page for the Kibana dashboard.

### How are you starting LocalStack?

With the `localstack` script

## How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

export SERVICES=sqs,sns,s3,firehose,iam,kinesis,ssm,es,sts
localstack start 

## Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Terraform File to set up infrastructure

```
variable "common_prefix"{
    type = string
    description = "Prefix to use for resources"
    default = "brand-monitoring"
}

locals {
  common_prefix = "brand_monitoring"
  elk_domain = "${var.common_prefix}-elk-domain"
}

data "aws_region" "current" {}

data "aws_caller_identity" "current" {}



## elastic search

resource "aws_elasticsearch_domain" "es" {
  domain_name = "${local.elk_domain}"
  elasticsearch_version = "7.10"

  cluster_config {
      instance_count = 1 
      instance_type = "t3.medium.elasticsearch"
      zone_awareness_enabled = false
  }

  ebs_options {
      ebs_enabled = true
      volume_size = 10
  }

  node_to_node_encryption {
    enabled = true
  }

  encrypt_at_rest {
    enabled = true
  }

  domain_endpoint_options {
    enforce_https = true
    tls_security_policy = "Policy-Min-TLS-1-0-2019-07"
  }

  advanced_security_options {
      enabled = true
      internal_user_database_enabled = true
      master_user_options {
          master_user_name = "foo"
          master_user_password = "bar"
      }
  }
  access_policies = <<CONFIG
  {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "es:*",
            "Principal": "*",
            "Effect": "Allow",
            "Resource": "arn:aws:es:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:domain/${local.elk_domain}/*"
        }
    ]
  }
    CONFIG
  
    snapshot_options {
        automated_snapshot_start_hour = 23
    }

  tags = {
      Domain = local.elk_domain
  }
}

output "elk_endpoint" {
  value = aws_elasticsearch_domain.es.endpoint
}

output "elk_kibana_endpoint" {
  value = aws_elasticsearch_domain.es.kibana_endpoint
}
```

Run `terraform init && terraform apply` to launch elastic search cluster.

### Environment

```markdown
- OS: macOs Big Sur, Version 11.2.3
- LocalStack: 

localstack                        0.12.13.1
localstack-client              1.20
localstack-ext                  0.12.10.11
```
```


### Anything else?

_No response_

**Comment by mgagliardo** [comment]
Hello @csnick93, problem is kibana does not come integrated out of the box, only elasticsearch as adding kibana on top of this would even add more overhead, also is not one of the core elements of ES. You can do two things:

1. Use the embedded elasticsearch + run your own kibana container, something like this should work:

```
# Run localstack (whatever you are using)..

# Check localstack's IP:

docker inspect localstack (check the right container name)

# Run your own kibana container (make sure kibana's version matches ES), for example:

docker run --name kibana  -p 5601:5601 -e "ELASTICSEARCH_HOSTS=http://localstack:4571" docker.elastic.co/kibana/kibana:7.7.1
```

Then you should be able to access to it over `http://localhost:5601`.

<img width="805" alt="Screenshot 2021-06-29 at 16 16 44" src="https://user-images.githubusercontent.com/11886625/123813721-6bacb580-d8f5-11eb-91cf-9e34f86e7b29.png">


2. Option 2 is to run [your own elasticsearch node](https://github.com/localstack/localstack/blob/master/doc/external_services_integration/elasticsearch/HOWTO.md) and add the kibana container to run on top of it, I will eventually add it to the documentation for further use.


Let me know if this helped you. Cheers!

**Comment by csnick93** [comment]
Hi @mgagliardo,
thanks a lot for your swift reply/help and sorry the delay on my end. I attempted your solution 1. as it seemed pretty straightforward, but I am having trouble getting the connection to the ElasticSearch node working. My ElasticSearch endpoint is `http://localhost:4571` and I verified it's running, which yields the following info:
```
{
  "name" : "09c5ac2a2128",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "RErB9-mhSVy-e-2mwsDBwQ",
  "version" : {
    "number" : "7.7.0",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "81a1e9eda8e6183f5237786246f6dced26a10eaf",
    "build_date" : "2020-05-12T02:01:37.602180Z",
    "build_snapshot" : false,
    "lucene_version" : "8.5.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

I then tried starting up Kibana with the command `docker run --name kibana --rm -p 5601:5601 -e "ELASTICSEARCH_HOSTS=http://localhost:4571" docker.elastic.co/kibana/kibana:7.7.0`. 
You actually wrote `ELASTICSEARCH_HOSTS=http://localstack:4571`, was that on purpose? For me the container is called `localstack_main`, but also replacing `localhost` with `localstack_main` did not change anything.

In any case, I am getting the following (error) logs:

```
{"type":"log","@timestamp":"2021-06-30T09:12:18Z","tags":["warning","plugins-discovery"],"pid":7,"message":"Expect plugin \"id\" in camelCase, but found: apm_oss"}                                   
{"type":"log","@timestamp":"2021-06-30T09:12:18Z","tags":["warning","plugins-discovery"],"pid":7,"message":"Expect plugin \"id\" in camelCase, but found: file_upload"}                               
{"type":"log","@timestamp":"2021-06-30T09:12:18Z","tags":["warning","plugins-discovery"],"pid":7,"message":"Expect plugin \"id\" in camelCase, but found: triggers_actions_ui"}                       
{"type":"log","@timestamp":"2021-06-30T09:12:40Z","tags":["info","plugins-system"],"pid":7,"message":"Setting up [76] plugins: [taskManager,siem,licensing,encryptedSavedObjects,eventLog,code,visType
Vega,usageCollection,metrics,ossTelemetry,lens,telemetryCollectionManager,telemetry,telemetryCollectionXpack,timelion,features,kibanaLegacy,devTools,apm_oss,rollup,translations,observability,uiActio
ns,statusPage,share,savedObjects,newsfeed,kibanaUtils,kibanaReact,inspector,maps,embeddable,drilldowns,advancedUiActions,discover,esUiShared,bfetch,expressions,visualizations,data,home,cloud,console
,consoleExtensions,searchprofiler,painlessLab,canvas,management,upgradeAssistant,security,snapshotRestore,transform,licenseManagement,indexManagement,remoteClusters,reporting,advancedSettings,spaces
,actions,case,alerting,apm,alertingBuiltins,uptime,ml,telemetryManagementSection,file_upload,dataEnhanced,navigation,graph,dashboard,charts,watcher,triggers_actions_ui,infra,monitoring]"}           
{"type":"log","@timestamp":"2021-06-30T09:12:40Z","tags":["warning","plugins","encryptedSavedObjects","config"],"pid":7,"message":"Generating a random key for xpack.encryptedSavedObjects.encryptionK
ey. To be able to decrypt encrypted saved objects attributes after restart, please set xpack.encryptedSavedObjects.encryptionKey in kibana.yml"}                                                      
{"type":"log","@timestamp":"2021-06-30T09:12:40Z","tags":["warning","plugins","security","config"],"pid":7,"message":"Generating a random key for xpack.security.encryptionKey. To prevent sessions fr
om being invalidated on restart, please set xpack.security.encryptionKey in kibana.yml"}                                                                                                              
{"type":"log","@timestamp":"2021-06-30T09:12:40Z","tags":["warning","plugins","security","config"],"pid":7,"message":"Session cookies will be transmitted over insecure connections. This is not recom
mended."}                                                                                                                                                                                             
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["warning","plugins","actions","actions"],"pid":7,"message":"APIs are disabled due to the Encrypted Saved Objects plugin using an ephemeral e
ncryption key. Please set xpack.encryptedSavedObjects.encryptionKey in kibana.yml."}                                                                                                                  
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["warning","plugins","alerting","plugins","alerting"],"pid":7,"message":"APIs are disabled due to the Encrypted Saved Objects plugin using an
 ephemeral encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in kibana.yml."}                                                                                                      
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["info","plugins","monitoring","monitoring"],"pid":7,"message":"config sourced from: production cluster"}                                    
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["warning","plugins","monitoring","monitoring"],"pid":7,"message":"X-Pack Monitoring Cluster Alerts will not be available: undefined"}       
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["error","elasticsearch","data"],"pid":7,"message":"Request error, retrying\nHEAD http://localhost:4571/.apm-agent-configuration => connect E
CONNREFUSED 127.0.0.1:4571"}                                                                                                                                                                          
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["error","elasticsearch","data"],"pid":7,"message":"Request error, retrying\nHEAD http://localhost:4571/.apm-custom-link => connect ECONNREFU
SED 127.0.0.1:4571"}                                                                                                                                                                                  
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["error","elasticsearch","monitoring"],"pid":7,"message":"Request error, retrying\nGET http://localhost:4571/_xpack => connect ECONNREFUSED 1
27.0.0.1:4571"}                                                                                                                                                                                       
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["error","elasticsearch","monitoring"],"pid":7,"message":"Request error, retrying\nGET http://localhost:4571/_xpack => connect ECONNREFUSED 1
27.0.0.1:4571"}                                                                                                                                                                                       
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["error","elasticsearch","data"],"pid":7,"message":"Request error, retrying\nGET http://localhost:4571/_xpack => connect ECONNREFUSED 127.0.0
.1:4571"}                                                                                                                                                                                             
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["warning","elasticsearch","data"],"pid":7,"message":"Unable to revive connection: http://localhost:4571/"}                                  
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["warning","elasticsearch","data"],"pid":7,"message":"No living connections"}                                                                
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["warning","elasticsearch","data"],"pid":7,"message":"Unable to revive connection: http://localhost:4571/"}                                  
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["warning","elasticsearch","data"],"pid":7,"message":"No living connections"}                                                                
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["warning","elasticsearch","monitoring"],"pid":7,"message":"Unable to revive connection: http://localhost:4571/"}                            
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["warning","elasticsearch","monitoring"],"pid":7,"message":"No living connections"}                                                          
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["warning","plugins","licensing"],"pid":7,"message":"License information could not be obtained from Elasticsearch due to Error: No Living con
nections error"}                                                                                                                                                                                      
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["info","savedobjects-service"],"pid":7,"message":"Waiting until all Elasticsearch nodes are compatible with Kibana before starting saved obj
ects migrations..."}                                                                                                                                                                                  
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["warning","elasticsearch","monitoring"],"pid":7,"message":"Unable to revive connection: http://localhost:4571/"}                            
{"type":"log","@timestamp":"2021-06-30T09:12:41Z","tags":["warning","elasticsearch","monitoring"],"pid":7,"message":"No living connections"}    
```

I checked the connections that it's being refused according to the log:
* http://localhost:4571/.apm-custom-link: 
```
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [.apm-custom-link]","resource.type":"index_or_alias","resource.id":".apm-custom-link","index_uuid":"_na_","index":".apm-custom-link"}],"type":"index_not_found_exception","reason":"no such index [.apm-custom-link]","resource.type":"index_or_alias","resource.id":".apm-custom-link","index_uuid":"_na_","index":".apm-custom-link"},"status":404}
```
* http://localhost:4571/.apm-agent-configuration:
```
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [.apm-agent-configuration]","resource.type":"index_or_alias","resource.id":".apm-agent-configuration","index_uuid":"_na_","index":".apm-agent-configuration"}],"type":"index_not_found_exception","reason":"no such index [.apm-agent-configuration]","resource.type":"index_or_alias","resource.id":".apm-agent-configuration","index_uuid":"_na_","index":".apm-agent-configuration"},"status":404}
```
* http://localhost:4571/_xpack:
```
{"build":{"hash":"81a1e9eda8e6183f5237786246f6dced26a10eaf","date":"2020-05-12T02:01:37.602180Z"},"license":{"uid":"e1717b5d-a995-459e-a0e1-e04f52eb2651","type":"basic","mode":"basic","status":"active"},"features":{"analytics":{"available":true,"enabled":true},"ccr":{"available":false,"enabled":true},"enrich":{"available":true,"enabled":true},"eql":{"available":true,"enabled":false},"flattened":{"available":true,"enabled":true},"frozen_indices":{"available":true,"enabled":true},"graph":{"available":false,"enabled":true},"ilm":{"available":true,"enabled":true},"logstash":{"available":false,"enabled":true},"ml":{"available":false,"enabled":false,"native_code_info":{"version":"N/A","build_hash":"N/A"}},"monitoring":{"available":true,"enabled":true},"rollup":{"available":true,"enabled":true},"security":{"available":true,"enabled":false},"slm":{"available":true,"enabled":true},"spatial":{"available":true,"enabled":true},"sql":{"available":true,"enabled":true},"transform":{"available":true,"enabled":true},"vectors":{"available":true,"enabled":true},"voting_only":{"available":true,"enabled":true},"watcher":{"available":false,"enabled":true}},"tagline":"You know, for X"}
```

I apologize for the verbosity of the logs, but I was wondering if you've encountered similar issues or rather what kind of responses you get when launching the kibana docker?

I appreciate your help! :)

**Comment by mgagliardo** [comment]
Hello @csnick93, problem is you are using `ELASTICSEARCH_HOSTS=http://localhost:4571` and that points to the localhost of the actual container.

You could either start your localstack container on the bridge and then point `ELASTICSEARCH_HOSTS` to the localstack container name/ip (that is why I am using `localstack`) or start both of them on the `host` net (using `--net=host`) and then `localhost` should work. Let me know if you have any troubles with this.

**Comment by csnick93** [comment]
Hey @mgagliardo ,
thanks for your patient help! As you might have noticed, I am not too proficient on the whole network topic. So I went with your second option, as `localstack start` seems to launch the container on the `host` network. This seemed quite promising at first (lots of green state changes):
```
{"type":"log","@timestamp":"2021-06-30T12:26:13Z","tags":["status","plugin:vis_default_editor@7.7.0","info"],"pid":7,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2021-06-30T12:26:13Z","tags":["status","plugin:vis_type_vega@7.7.0","info"],"pid":7,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
```
But at the end, I am getting the following errors:
```
{"type":"log","@timestamp":"2021-06-30T12:26:15Z","tags":["error","reporting"],"pid":7,"message":"Error: Found
 'server.host: \"0\"' in settings. This is incompatible with Reporting. To enable Reporting to work,
 'xpack.reporting.kibanaServer.hostname: 0.0.0.0' is being automatically to the configuration. You can change to 'server.host:
 0.0.0.0' or add 'xpack.reporting.kibanaServer.hostname: 0.0.0.0' in kibana.yml to prevent this message.\n    at 
validateServerHost (/usr/share/kibana/x-pack/legacy/plugins/reporting/server/lib/validate/validate_server_host.js:24:11)\n    at
 runValidations (/usr/share/kibana/x-pack/legacy/plugins/reporting/server/lib/validate/index.js:25:256)\n    at 
ReportingPlugin.setup (/usr/share/kibana/x-pack/legacy/plugins/reporting/server/plugin.js:40:5)"}

{"type":"log","@timestamp":"2021-06-30T12:26:15Z","tags":["warning","reporting"],"pid":7,"message":"Reporting plugin 
self-check generated a warning: Error: Found 'server.host: \"0\"' in settings. This is incompatible with Reporting. To enable 
Reporting to work, 'xpack.reporting.kibanaServer.hostname: 0.0.0.0' is being automatically to the configuration. You can 
change to 'server.host: 0.0.0.0' or add 'xpack.reporting.kibanaServer.hostname: 0.0.0.0' in kibana.yml to prevent this 
message."}

{"type":"log","@timestamp":"2021-06-30T12:26:15Z","tags":
["status","plugin:reporting@7.7.0","info"],"pid":7,"state":"green","message":"Status changed from uninitialized to green - 
Ready","prevState":"uninitialized","prevMsg":"uninitialized"}

{"type":"log","@timestamp":"2021-06-30T12:26:15Z","tags":["listening","info"],"pid":7,"message":"Server running at 
http://0:5601"}
{"type":"log","@timestamp":"2021-06-30T12:26:16Z","tags":["info","http","server","Kibana"],"pid":7,"message":"http server
 running at http://0:5601"}
{"type":"log","@timestamp":"2021-06-30T12:26:19Z","tags":["warning","plugins","apm"],"pid":7,"message":"Failed executing
 APM telemetry task integrations"}
{"type":"log","@timestamp":"2021-06-30T12:26:19Z","tags":["warning","plugins","apm"],"pid":7,"message":"{ Error: 
[index_not_found_exception] no such index [_ml], with { resource.type=\"index_expression\" & resource.id=\"_ml\" & 
index_uuid=\"_na_\" & index=\"_ml\" }\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure 
(/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> 
(/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper 
(/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4929:19)\n    at IncomingMessage.emit 
(events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback 
(internal/process/next_tick.js:63:19)\n  status: 404,\n  displayName: 'NotFound',\n  message:\n   
'[index_not_found_exception] no such index [_ml], with { resource.type=\"index_expression\" & resource.id=\"_ml\" & 
index_uuid=\"_na_\" & index=\"_ml\" }',\n  path: '/_ml/anomaly_detectors/*-high_mean_response_time',\n  query: undefined,\n  body:\n   { error:\n      { root_cause: [Array],\n        type: 'index_not_found_exception',\n        reason: 'no such index [_ml]',\n        'resource.type': 'index_expression',\n        'resource.id': '_ml',\n        index_uuid: '_na_',\n        index: '_ml' },\n     status: 404 },\n  statusCode: 404,\n  response:\n   '{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such 
index [_ml]\",\"resource.type\":\"index_expression\",\"resource.id\":\"_ml\",\"index_uuid\":\"_na_\",\"index\":\"_ml\"}],\"type\":\"index
_not_found_exception\",\"reason\":\"no such index 
[_ml]\",\"resource.type\":\"index_expression\",\"resource.id\":\"_ml\",\"index_uuid\":\"_na_\",\"index\":\"_ml\"},\"status\":404}',\
n  toString: [Function],\n  toJSON: [Function] }"}
{"type":"log","@timestamp":"2021-06-30T12:32:21Z","tags":
["warning","plugins","taskManager","taskManager"],"pid":7,"message":"The task vis_telemetry \"oss_telemetry-
vis_telemetry\" is not cancellable."}
{"type":"log","@timestamp":"2021-06-30T12:32:21Z","tags":
["warning","plugins","taskManager","taskManager"],"pid":7,"message":"The task lens_telemetry \"Lens-lens_telemetry\" is
 not cancellable."}
{"type":"log","@timestamp":"2021-06-30T12:36:21Z","tags":
["warning","plugins","taskManager","taskManager"],"pid":7,"message":"The task lens_telemetry \"Lens-lens_telemetry\" is 
not cancellable."}
{"type":"log","@timestamp":"2021-06-30T12:43:24Z","tags":
["warning","plugins","taskManager","taskManager"],"pid":7,"message":"The task vis_telemetry \"oss_telemetry-
vis_telemetry\" is not cancellable."}
{"type":"log","@timestamp":"2021-06-30T12:51:24Z","tags":
["warning","plugins","taskManager","taskManager"],"pid":7,"message":"The task lens_telemetry \"Lens-lens_telemetry\" is
not cancellable."}
```

So:
* Can I ignore the problem with the host being set to `0` and then automatically being changed to `0.0.0.0`? Or should/can I set this manually on startup? 
* The index `_ml` does indeed not exist, not sure why this index is needed though...

I feel my issues don't have much to do with LocalStack anymore at this point, so I appreciate your help very much if you are able to spot the problem. But I don't want to cost you time on an issue that does not really relate to the LocalStack project.

**Comment by mgagliardo** [comment]
Hello @csnick93, no worries at all, we are here to help.

1. For the following:

```
Can I ignore the problem with the host being set to 0 and then automatically being changed to 0.0.0.0? Or should/can I set this manually on startup?
```

So as far as I can see on this message:

```
{"type":"log","@timestamp":"2021-06-30T12:26:15Z","tags":["error","reporting"],"pid":7,"message":"Error: Found
 'server.host: \"0\"' in settings. This is incompatible with Reporting. To enable Reporting to work,
 'xpack.reporting.kibanaServer.hostname: 0.0.0.0' is being automatically to the configuration. You can change to 'server.host:
 0.0.0.0' or add 'xpack.reporting.kibanaServer.hostname: 0.0.0.0' in kibana.yml to prevent this message.\n    at 
validateServerHost (/usr/share/kibana/x-pack/legacy/plugins/reporting/server/lib/validate/validate_server_host.js:24:11)\n    at
 runValidations (/usr/share/kibana/x-pack/legacy/plugins/reporting/server/lib/validate/index.js:25:256)\n    at 
ReportingPlugin.setup (/usr/share/kibana/x-pack/legacy/plugins/reporting/server/plugin.js:40:5)"}
````

You should be able to mitigate it by setting (for example in this case): `xpack.reporting.kibanaServer.hostname: 0.0.0.0`, you can achieve that by doing:

```
docker run "Lots of options here" -e xpack.reporting.kibanaServer.hostname=0.0.0.0 docker.elastic.co/kibana/kibana:7.7.1
```

Either that or (if the above does not work) you should be able to setup a `kibana.yml` file as well and override the default as stated [here](https://www.elastic.co/guide/en/kibana/current/docker.html).

2. For the latter:
```
The index _ml does indeed not exist, not sure why this index is needed though...
```

I guess that is because the `_ml` does not exist as elasticsearch does not come with indexes created out of the box, if that bothers you (other than the error message) you can create it yourself using the [elasticsearch API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html)


Finally, I don't have a problem with helping you ever so you don't have to worry about asking for help, but just in case Elastic's docs are usually pretty great in this case (and it is where I am getting most of my answers actually heheh):

* [Docker ES + Kibana](https://www.elastic.co/guide/en/kibana/current/docker.html)
* [Kibana settings](https://www.elastic.co/guide/en/kibana/current/settings.html)
* [Kibana reporting settings configs](https://www.elastic.co/guide/en/kibana/current/reporting-settings-kb.html#reporting-kibana-server-settings)
* [kibana.yml example](https://github.com/elastic/kibana/blob/master/config/kibana.yml)

Let me know if this helps you or you need a hand with anything else. Cheers!

**Comment by csnick93** [comment]
Hey @mgagliardo,
just wanted to document a finding of mine here (especially in case other people struggling with this, read this thread): With the command `docker run --name kibana --rm  --net=host -e "SERVER_HOST=127.0.0.1" -e "ELASTICSEARCH_HOSTS=http://localhost:4571" docker.elastic.co/kibana/kibana:7.7.0 ` I get it running and can reach Kibana in the browser. But only on my private **Ubuntu** machine, with my business mac it's not working yet. I guess there are some other docker quirks on macOS that prevent Kibana from being reachable in the browser... But at least now I know what to search for :)

**Comment by mgagliardo** [comment]
If you are using mac you can try with `host.docker.internal` as well :) 

https://docs.docker.com/docker-for-mac/networking/

**Comment by csnick93** [comment]
@mgagliardo wow, you just don't run out of advice :D So, I finally got it working on my mac as well with the following command:
`docker run --name kibana --rm -p 5601:5601  -e "SERVER_HOST=0.0.0.0" -e "ELASTICSEARCH_HOSTS=http://host.docker.internal:4571" docker.elastic.co/kibana/kibana:7.7.0`

So not running the kibana docker on the host network after all, but instead doing a port forward and making the elastic search service visible using `host.docker.internal`. 

Thanks a ton @mgagliardo for your patient help, wouldn't have gotten there without :)
