### ISSUE TITLE
Error putting record in Kinesis

### ISSUE THREAD

**Issue by burm87** [localstack/localstack#424]
I am running localstack with Docker with `SERVICES: kinesis`.
When I try to add a record like this:
```
final ByteBuffer data = ByteBuffer.wrap("{\"test\":\"test\"}".getBytes());
kinesisClient.putRecord("my-stream-name", data, "partition-key");
```

I get this in the container log:  
```localstack_1      | 2017-10-25T13:02:33:ERROR:localstack.services.generic_proxy: Error forwarding request: No JSON object could be decoded Traceback (most recent call last):
localstack_1      |   File "/usr/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 194, in forward
localstack_1      |     path=path, data=data, headers=forward_headers, response=response)
localstack_1      |   File "/usr/lib/python2.7/site-packages/localstack/services/kinesis/kinesis_listener.py", line 34, in return_response
localstack_1      |     response_body = json.loads(to_str(response.content))
localstack_1      |   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
localstack_1      |     return _default_decoder.decode(s)
localstack_1      |   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
localstack_1      |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
localstack_1      |   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
localstack_1      |     raise ValueError("No JSON object could be decoded")
localstack_1      | ValueError: No JSON object could be decoded
localstack_1      | 
localstack_1      | 2017-10-25T13:03:23:ERROR:localstack.services.generic_proxy: Error forwarding request: No JSON object could be decoded Traceback (most recent call last):
localstack_1      |   File "/usr/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 194, in forward
localstack_1      |     path=path, data=data, headers=forward_headers, response=response)
localstack_1      |   File "/usr/lib/python2.7/site-packages/localstack/services/kinesis/kinesis_listener.py", line 34, in return_response
localstack_1      |     response_body = json.loads(to_str(response.content))
localstack_1      |   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
localstack_1      |     return _default_decoder.decode(s)
localstack_1      |   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
localstack_1      |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
localstack_1      |   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
localstack_1      |     raise ValueError("No JSON object could be decoded")
localstack_1      | ValueError: No JSON object could be decoded
```

Any ideas?

**Comment by whummer** [comment]
Thanks for reporting @burm87 . Just to confirm - are you using the `localstack/localstack` Docker image, and which version are you using?

I haven't been able to reproduce your issue (your Java test code works for me), can you please give it a try with the latest version? Thanks

**Comment by burm87** [comment]
I have found out that we were not using the latest image, thank you, I think we can close this.
