### ISSUE TITLE
Unexpected resource type CertificateManager::Certificate

### ISSUE THREAD

**Issue by Thanados** [localstack/localstack#4244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Docker log
2021-07-01T10:27:20:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type CertificateManager::Certificate when resolving references of resource AppFrontendCoreCertificateFE66BC07: {'Type': 'AWS::CertificateManager::Certificate', 'Metadata': {'aws:cdk:path': 'App-Frontend-Core/App-Frontend-Core-Certificate/Resource'}, 'LogicalResourceId': 'AppFrontendCoreCertificateFE66BC07', 'Properties': {'DomainName': 'app./lz/pp/blueprints/dev/bootstrapping/app/DNS_PUBLIC_HOSTED_ZONE', 'DomainValidationOptions': [{'DomainName': 'app./lz/pp/blueprints/dev/bootstrapping/app/DNS_PUBLIC_HOSTED_ZONE', 'HostedZoneId': '/lz/pp/blueprints/dev/bootstrapping/app/DNS_PUBLIC_HOSTED_ZONE_ID'}], 'ValidationMethod': 'DNS'}}

2021-07-01T10:27:20:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "AppFrontendCoreCertificateFE66BC07" (1/36) type "AWS::CertificateManager::Certificate" in loop iteration 1

2021-07-01T10:27:20:INFO:localstack.utils.cloudformation.template_deployer: Action "create" for resource type CertificateManager::Certificate not yet implemented - using fallback mechanism

2021-07-01T10:27:20:DEBUG:localstack.utils.cloudformation.template_deployer: Unable to extract name for resource type "AWS::CertificateManager::Certificate"

2021-07-01T10:27:20:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: CertificateManager::Certificate PhysicalResourceId

2021-07-01T10:27:20:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "App-Frontend-Core": Unable to extract attribute "PhysicalResourceId" from "CertificateManager::Certificate" model class <class 'localstack.services.cloudformation.service_models.GenericBaseModel'> Traceback (most recent call last):

File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1847, in _run
self.do_apply_changes_in_loop(changes, stack, stack_name)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1900, in do_apply_changes_in_loop
self.apply_change(change, stack, new_resources, stack_name=stack_name)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1960, in apply_change
self.update_resource_details(resource_id, result, stack=old_stack, action=stack_action)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1714, in update_resource_details
physical_id = physical_id or determine_resource_physical_id(resource_id, stack=stack)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1389, in determine_resource_physical_id
stack_name=stack_name, resource_id=resource_id, resource=resource, resources=resources)
File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py", line 461, in extract_resource_attribute
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 539, in extract_resource_attribute
attribute, resource_type, type(resource_state)))
Exception: Unable to extract attribute "PhysicalResourceId" from "CertificateManager::Certificate" model class <class 'localstack.services.cloudformation.service_models.GenericBaseModel'>

### Expected Behavior

I would expect that the deployment succeeds without error.

### How are you starting LocalStack?

With a docker-compose file

## docker-compose.yml
```
services:
  dev-backend-infrastructure:
      container_name: dev-backend-infrastructure-container # should be constant (e.g. for copying aws credentials)
      build: #./backend
        context: ./dev-backend-infrastructure
        args:
          - HTTP_PROXY=${HTTP_PROXY} # Env.-var from host (can be empty or not existing, will be set in docker container)
          - HTTPS_PROXY=${HTTPS_PROXY} # Env.-var from host (can be empty or not existing, will be set in docker container)
          - NO_PROXY=localhost,127.0.0.1,localstack # name of compose service for the localstack container
          - CDK_VERSION=1.109 # cdk version to install
          - PYTHON_VERSION=3.8 # python version to install
      volumes:
        - ..:/workspace:cached # map complete project into container
      tty: true # important, otherwise container will be closed immediately
      environment:
        - LOCALSTACK_HOST=localstack # name of compose service (will be used in aws v1 commands), only needed for localstack communication
        - LOCALSTACK_HOSTNAME=localstack # only needed for localstack communication
      networks:
        - backend-nw # in bridge mode
        - aws-nw # in bridge mode
    localstack: #https://github.com/localstack/localstack
      container_name: localstack
      domainname: localstack
      image: localstack/localstack
      ports:
        - 443:443
        - 4566:4566
        - 4571:4571
      volumes:
        - ../dev-backend-infrastructure/localstack-share:/tmp/localstack
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - SERVICES=${SERVICES- } # start all service for testing
        - DEBUG=1
        - DATA_DIR=/tmp/localstack/data
        - DOCKER_HOST=unix:///var/run/docker.sock
        - HOSTNAME=localstack # Name of the host to expose the services internally (default: localhost). Use this to customize the framework-internal communication, e.g., if services are started in different containers using docker-compose.
        - HOSTNAME_EXTERNAL=localstack # Name of the host to expose the services externally (default: localhost). This host is used, e.g., when returning queue URLs from the SQS service to the client.
        - LOCALSTACK_HOSTNAME=localstack # Name of the host where LocalStack services are available
        - MAIN_CONTAINER_NAME=localstack # Specify the main docker container name (default: localstack_main).
        - HTTP_PROXY=${HTTP_PROXY} # Env.-var from host (can be empty or not existing, will be set in docker container)
        - HTTPS_PROXY=${HTTPS_PROXY} # Env.-var from host (can be empty or not existing, will be set in docker container)
        - LAMBDA_EXECUTOR=docker
        - LAMBDA_REMOTE_DOCKER=true # needed to avoid Runtime.HandlerNotFound -> https://github.com/localstack/localstack/issues/3185
        - LAMBDA_REMOVE_CONTAINERS=true
        - LAMBDA_DOCKER_FLAGS=-e IS_OFFLINE=active -e TABLE_NAME=MyTable # env variable in lambda docker container
        - LAMBDA_DOCKER_NETWORK=devcontainer_backend-nw #set docker network
        - LOCALSTACK_API_KEY=<key>
      networks:
        - backend-nw
        - aws-nw
        - frontend-nw
```

## cdk app.ts (shorted)

```
onst app = new cdk.App();


// **********************************************************************************************
// deserialize parameter data (cdk context file, arguments), manipulate them for dev issues only
// **********************************************************************************************

const params: ContextParameter = app.node.tryGetContext('parameters');
const { projectParameter } = params;
const { platformParameter } = params;
const { certificateParameter } = params;
const { identityProviderParameter } = params;
platformParameter.stage = app.node.tryGetContext('stage');

const accountEnv: AccountParameter = {
  accountId: app.node.tryGetContext('accountId'), // process.env.CDK_DEFAULT_ACCOUNT,
  accountRegion: app.node.tryGetContext('accountRegion') // process.env.CDK_DEFAULT_REGION
};

const env: Environment = {
  account: process.env.CDK_DEFAULT_ACCOUNT,
  region: process.env.CDK_DEFAULT_REGION
};

const devPrefix: string = app.node.tryGetContext('devPrefix');
if (devPrefix) {
  projectParameter.projectName = `${devPrefix}-${projectParameter.projectName}`;
  projectParameter.frontendSubdomain = `${devPrefix}-${projectParameter.frontendSubdomain}`;
  projectParameter.backendSubdomain = `${devPrefix}-${projectParameter.backendSubdomain}`;
}

// **********************************************************************************************
// build context based on given parameters (e.g. deploy locally, cloud, ...)
// **********************************************************************************************

const appContext: AppContext = new AppContext();
appContext.pathToBackendDist = `${__dirname}/../../app-backend/dist`;
appContext.timeoutForOutgoingRequestForLambdaMs = 10000;
appContext.welcomePath = 'welcome';

const appCoreToolsStack = new CoreTools(app, `${projectParameter.projectName}-Core-Tools`, {
  projectParameter,
  platformParameter,
  tags: {
    app: tag
  },
  env
});

appContext.backendDomain = appCoreToolsStack.backendDomain;
appContext.frontendDomain = appCoreToolsStack.frontendDomain;
appContext.hostedZone = appCoreToolsStack.hostedZone;
appContext.hostedZoneId = appCoreToolsStack.hostedZoneId;

appContext.backendDomain = appCoreToolsStack.backendDomain;
appContext.frontendDomain = appCoreToolsStack.frontendDomain;
appContext.hostedZone = appCoreToolsStack.hostedZone;
appContext.hostedZoneId = appCoreToolsStack.hostedZoneId;

appContext.backendUrl = `http://${appContext.backendDomain}`;
appContext.frontendUrl = `http://${appContext.frontendDomain}`;

appContext.welcomeUrl = `${appContext.frontendUrl}/${appContext.welcomePath}`;

AppContextService.createContext(appContext);

// **********************************************************************************************
// deployment of stacks starts here ...
// **********************************************************************************************

let welcomeLambda: IFunction | undefined;
let authorizerLambda: IFunction | undefined;
const loginPage: string = 'http://localstack:4566'; // default for local development
let apiGatewayInvokeLambdaRole: IRole | undefined;

const frontendCoreStack = new FrontendCore(app, `App-Frontend-Core`, {
  platformParameter,
  projectParameter,
  certificateParameter,
  welcomeLambda,
  loginPageUrl: loginPage,
  apiGatewayInvokeLambdaRole,
  authorizerLambda,
  accountEnv,
  env
});
```

## cdk FrontendCore Stack

```

export interface FrontendCoreProps extends cdk.StackProps {
  /**
  * project parameter
  */
  projectParameter: ProjectParameter;

  /**
   * platform parameter
   */
  platformParameter: PlatformParameter;

  /**
   * role to invoke the authorizer lambda
   */
  apiGatewayInvokeLambdaRole?: IRole;

  /**
   * authorizer lambda (optional)
   */
  authorizerLambda?: IFunction;

  /**
   * welcome lambda (optional)
   */
  welcomeLambda?: IFunction;

  /**
   * login page url
   */
  loginPageUrl: string;

  /**
   * certificate parameter
   */
  certificateParameter: CertificateParameter;

  /**
   * account parameter
   */
  accountEnv: AccountParameter;

  /**
   * aws environment variables
   */
  env: Environment;
}

export class FrontendCore extends cdk.Stack {
  /**
   * @param scope default parameter
   * @param id default parameter
   * @param props custom stack properties
   */
  constructor(scope: cdk.Construct, id: string, props: FrontendCoreProps) {
    super(scope, id, props);


    // *********************************************************************************************
    // domain and certificate
    // *********************************************************************************************

    const hostedZoneCert = PublicHostedZone.fromPublicHostedZoneId(this,
      'PublicHostedZone', AppContextService.getContext.hostedZoneId);

    const certificate = new Certificate(this, `${id}-Certificate`, {
      domainName: AppContextService.getContext.frontendDomain,
      validation: CertificateValidation.fromDns(hostedZoneCert)
    });

    const frontendDomainName = new DomainName(this, `${id}-DomainName`, {
      certificate,
      domainName: AppContextService.getContext.frontendDomain,
      endpointType: EndpointType.REGIONAL,
      securityPolicy: SecurityPolicy.TLS_1_2
    });

    new CfnOutput(this, 'FrontendUrl', {
      value: AppContextService.getContext.frontendUrl
    });

    // *********************************************************************************************
    // frontend api
    // *********************************************************************************************

    const binaryMediaTypes: string[] = [
      'application/javascript',
      'application/octet-stream',
      'application/vnd.ms-fontobject',
      'text/css',
      'text/html',
      'binary/octet-stream',
      'image/png',
      'image/jpeg',
      'image/webp',
      'image/svg+xml',
      'image/vnd.microsoft.icon',
      'image/x-icon',
      'font/woff',
      'font/woff2',
      'font/ttf'
    ];

    this.frontendApi = new RestApi(this, 'FrontendApi', {
      description: 'Website api for internet access.',
      cloudWatchRole: true,
      deploy: false,
      binaryMediaTypes,
      endpointTypes: [EndpointType.REGIONAL]
    });

    const apiGatewayPrinicpal = new ServicePrincipal('apigateway.amazonaws.com');

    const randomPostfix = Math.random().toString();

    this.frontendApiStage = new Stage(this, 'FrontendApiStage', {
      stageName: `${props.platformParameter.stage}`,
      accessLogDestination: new LogGroupLogDestination(
        new LogGroup(this, 'ProjectApiLogGroup', { logGroupName: `API-Gateway-Execution-Logs_${this.frontendApi.restApiId}/${props.platformParameter.stage}` })
      ),
      accessLogFormat: AccessLogFormat.custom(
        '{ "stage" : "$context.stage", "request_id" : "$context.requestId", "resource_path" : "$context.resourcePath", "resource": "$context.path", "user" : "$context.identity.user" }'
      ),
      methodOptions: {
        '/*/*': {
          dataTraceEnabled: xRayTracingActivated(props.platformParameter.logLevel),
          loggingLevel: convertToApiGatewayLogLevel(props.platformParameter.logLevel)
        }
      },
      tracingEnabled: xRayTracingActivated(props.platformParameter.logLevel),
      deployment: new Deployment(this, `FrontendApiDeployment${randomPostfix}`, {
        api: this.frontendApi
      })
    });

    this.frontendApi.addUsagePlan('FrontendApiUsagePlan', {
      description: 'Usage plan to enable Throttling for frontend api.',
      apiStages: [{
        api: this.frontendApi,
        stage: this.frontendApiStage
      }],
      throttle: {
        burstLimit: 200,
        rateLimit: 100
      }
    });

    new CfnRecordSet(this, `${props.projectParameter.projectName}-Frontend-Record`, {
      aliasTarget: {
        dnsName: frontendDomainName.domainNameAliasDomainName,
        hostedZoneId: frontendDomainName.domainNameAliasHostedZoneId,
      },
      hostedZoneId: AppContextService.getContext.hostedZoneId,
      type: 'A',
      name: frontendDomainName.domainName
    });

    frontendDomainName.addBasePathMapping(this.frontendApi, {
      stage: this.frontendApiStage
    });

    const apiGwLambdaInvokeRole = new Role(this, 'ApiGwInvokeRole', {
      assumedBy: apiGatewayPrinicpal
    });


    // *********************************************************************************************
    // root paths
    // *********************************************************************************************

    const rootRes = this.frontendApi.root;
    const staticPathRes = rootRes.addResource('{path+}');
    const welcomePathRes = rootRes.addResource(AppContextService.getContext.welcomePath);
    const versionPathRes = rootRes.addResource('v1');
    const configPathRes = versionPathRes.addResource('config');


    // *********************************************************************************************
    // config
    // *********************************************************************************************

    const appConfigParameter: NonRotationSecret = new NonRotationSecret(this, 'AppConfig', {
      secretName: `${props.projectParameter.projectName.toLowerCase()}-app-config`,
      secretValues: { backendApiUrl: AppContextService.getContext.backendUrl }
    });

    const getAppConfigRole: Role = new Role(this, 'GetAppConfigRole', {
      assumedBy: apiGatewayPrinicpal
    });
    appConfigParameter.secret.grantRead(getAppConfigRole);
    appConfigParameter.key.grantDecrypt(getAppConfigRole);

    // description: https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html#API_GetSecretValue_Examples
    // request/response template: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration-requestTemplates.html
    const secretManagerIntegration = new AwsIntegration({
      service: 'secretsmanager',
      path: '/',
      integrationHttpMethod: 'POST',
      options: {
        credentialsRole: getAppConfigRole,
        requestParameters: {
          'integration.request.header.Content-Type': "'application/x-amz-json-1.1'",
          'integration.request.header.X-Amz-Target': "'secretsmanager.GetSecretValue'"
        },
        requestTemplates: {
          // eslint-disable-next-line @typescript-eslint/naming-convention
          'application/json': JSON.stringify({ SecretId: appConfigParameter.secret.secretArn })
        },
        integrationResponses: [
          {
            selectionPattern: '2\\d{2}',
            statusCode: StatusCodes.OK.toString(),
            responseTemplates: {
              'application/json': '#set($inputRoot = $input.path(\'$\')) $inputRoot.SecretString'
            }
          },
          {
            selectionPattern: '4\\d{2}',
            statusCode: StatusCodes.BAD_REQUEST.toString()
          },
          {
            selectionPattern: '5\\d{2}',
            statusCode: StatusCodes.INTERNAL_SERVER_ERROR.toString(),
            responseTemplates: {
              'application/json': 'ERROR SERVER'
            }
          }
        ]
      }
    });

    configPathRes.addMethod('GET', secretManagerIntegration, {
      authorizationType: AuthorizationType.CUSTOM,
      authorizer,
      operationName: 'GetAppConfig',
      methodResponses: [
        {
          statusCode: StatusCodes.OK.toString()
        },
        {
          statusCode: StatusCodes.BAD_REQUEST.toString()
        },
        {
          statusCode: StatusCodes.INTERNAL_SERVER_ERROR.toString()
        }
      ]
    });

    // *********************************************************************************************
    // index.html
    // *********************************************************************************************

    this.websiteBucket = new NonPublicS3Construct(this, 'WebsiteBucket', {
      bucketName: buildResourceName(props.projectParameter, 'website-bucket'),
      emptyBucketOnDeletion: true,
      versioningEnabled: true
    });

    const websiteApiExecutionRole = new Role(this, 'WebsiteApiExecutionRole', {
      assumedBy: apiGatewayPrinicpal
    });
    this.websiteBucket.bucket.grantRead(websiteApiExecutionRole);
    this.websiteBucket.key.grantDecrypt(websiteApiExecutionRole);

    const s3IndexIntegration = new AwsIntegration({
      service: 's3',
      integrationHttpMethod: 'GET',
      path: `${this.websiteBucket.bucket.bucketName}/index.html`,
      options: {
        credentialsRole: websiteApiExecutionRole,
        passthroughBehavior: PassthroughBehavior.WHEN_NO_MATCH,
        integrationResponses: [
          {
            selectionPattern: '4\\d{2}',
            statusCode: StatusCodes.BAD_REQUEST.toString()
          },
          {
            selectionPattern: '5\\d{2}',
            statusCode: StatusCodes.INTERNAL_SERVER_ERROR.toString()
          },
          {
            selectionPattern: '2\\d{2}',
            statusCode: StatusCodes.OK.toString(),
            responseParameters: {
              'method.response.header.Timestamp': 'integration.response.header.Date',
              'method.response.header.Content-Type': 'integration.response.header.Content-Type'
            }
          }
        ]
      }
    });

    rootRes.addMethod('GET', s3IndexIntegration, {
      authorizationType: AuthorizationType.CUSTOM,
      authorizer,
      operationName: 'GetIndexPage',
      methodResponses: [
        {
          statusCode: StatusCodes.OK.toString(),
          responseParameters: {
            'method.response.header.Timestamp': true,
            'method.response.header.Content-Type': true
          }
        }
      ]
    });

    // *********************************************************************************************
    // static content (all excluded index.html)
    // *********************************************************************************************

    const s3StaticContentIntegration = new AwsIntegration({
      service: 's3',
      integrationHttpMethod: 'GET',
      path: `${this.websiteBucket.bucket.bucketName}/{path}`,
      options: {
        credentialsRole: websiteApiExecutionRole,
        passthroughBehavior: PassthroughBehavior.WHEN_NO_MATCH,
        requestParameters: {
          'integration.request.path.path': 'method.request.path.path'
        },
        integrationResponses: [
          {
            selectionPattern: '4\\d{2}',
            statusCode: StatusCodes.BAD_REQUEST.toString()
          },
          {
            selectionPattern: '5\\d{2}',
            statusCode: StatusCodes.INTERNAL_SERVER_ERROR.toString()
          },
          {
            selectionPattern: '2\\d{2}',
            statusCode: StatusCodes.OK.toString(),
            responseParameters: {
              'method.response.header.Timestamp': 'integration.response.header.Date',
              'method.response.header.Content-Type': 'integration.response.header.Content-Type'
            }
          }
        ]
      }
    });

    staticPathRes.addMethod('GET', s3StaticContentIntegration, {
      operationName: 'GetStaticFiles',
      requestParameters: {
        'method.request.path.path': true
      },
      methodResponses: [
        {
          statusCode: StatusCodes.OK.toString(),
          responseParameters: {
            'method.response.header.Timestamp': true,
            'method.response.header.Content-Type': true
          }
        }
      ],
    });

    // *********************************************************************************************
    // map gateway responses
    // *********************************************************************************************

    this.frontendApi.addGatewayResponse(`AccessDeniedGatewayResponse${randomPostfix}`, {
      type: ResponseType.ACCESS_DENIED,
      statusCode: StatusCodes.MOVED_TEMPORARILY.toString(), // 302
      responseHeaders: {
        // eslint-disable-next-line @typescript-eslint/naming-convention
        Location: `'${props.loginPageUrl}'`,
        // eslint-disable-next-line @typescript-eslint/naming-convention
        'Access-Control-Allow-Origin': "'*'"
      }
    });

    this.frontendApi.addGatewayResponse(`UnauthorizedGatewayResponse${randomPostfix}`, {
      type: ResponseType.UNAUTHORIZED,
      statusCode: StatusCodes.MOVED_TEMPORARILY.toString(), // 302
      responseHeaders: {
        // eslint-disable-next-line @typescript-eslint/naming-convention
        Location: `'${props.loginPageUrl}'`,
        // eslint-disable-next-line @typescript-eslint/naming-convention
        'Access-Control-Allow-Origin': "'*'"
      }
    });

    // *********************************************************************************************
    // output values
    // *********************************************************************************************
    new CfnOutput(this, 'FrontendBucketOutput', {
      value: this.websiteBucket.bucket.bucketName,
      exportName: `${props.projectParameter.projectName}-frontend-bucket-name`
    });
  }

  /**
   * Website bucket of app frontend
   */
  readonly websiteBucket: NonPublicS3Construct;

  /**
   * Frontend api of frontend core
   */
  readonly frontendApi: RestApi;

  /**
   * Frontend api stage of frontend core
   */
  readonly frontendApiStage: Stage;
}
```

## Command in vscode devcontainer -> name of the container from compose file dev-backend-infrastructure-container

    cdklocal deploy --all --require-approval never --verbose

### Environment

```markdown
- OS: macOS Big SUr 11.4
- LocalStack version: 0.12.14
- VScode devcontainer env
- aws --version -> aws-cli/2.1.26 Python/3.7.3 Linux/5.10.25-linuxkit exe/x86_64.ubuntu.16 prompt/off
```

**Comment by whummer** [comment]
Thanks for reporting @Thanados . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
