### ISSUE TITLE
bug: lambda (localstack, python) unable to connect to s3 (localstack) SSLCertVerificationError

### ISSUE THREAD

**Issue by sidthakur** [localstack/localstack#4245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lambda function (using python, s3fs specifically to access an archive file on s3) is unable to connect to S3. This is the response I receive on Lambda invocation 

```
{
  "errorMessage": "Lambda runtime error. Result: {'errorMessage': 'Cannot connect to host test-input-bucket.s3.amazonaws.com:443 ssl:True [SSLCertVerificationError: (1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for \\'test-input-bucket.s3.amazonaws.com\\'. (_ssl.c:1091)\")]', 'errorType': 'ClientConnectorCertificateError', 'stackTrace': ['  File \"/var/task/prepare_parallel_executors/app.py\", line 21, in handler\\n    images = get_list_of_images_with_file_size(event[\\'inputArchiveFile\\'][\\'Bucket\\'], event[\\'inputArchiveFile\\'][\\'Key\\'])\\n', '  File \"/var/task/prepare_parallel_executors/app.py\", line 30, in get_list_of_images_with_file_size\\n    if not s3fs_client.exists(full_path):\\n', '  File \"/var/task/fsspec/asyn.py\", line 87, in wrapper\\n    return sync(self.loop, func, *args, **kwargs)\\n', '  File \"/var/task/fsspec/asyn.py\", line 68, in sync\\n    raise result[0]\\n', '  File \"/var/task/fsspec/asyn.py\", line 24, in _runner\\n    result[0] = await coro\\n', '  File \"/var/task/s3fs/core.py\", line 802, in _exists\\n    await self._info(path, bucket, key, version_id=version_id)\\n', '  File \"/var/task/s3fs/core.py\", line 1057, in _info\\n    out = await self._simple_info(path)\\n', '  File \"/var/task/s3fs/core.py\", line 977, in _simple_info\\n    **self.req_kw,\\n', '  File \"/var/task/s3fs/core.py\", line 265, in _call_s3\\n    raise translate_boto_error(err)\\n', '  File \"/var/task/s3fs/core.py\", line 246, in _call_s3\\n    out = await method(**additional_kwargs)\\n', '  File \"/var/task/aiobotocore/client.py\", line 141, in _make_api_call\\n    operation_model, request_dict, request_context)\\n', '  File \"/var/task/aiobotocore/client.py\", line 160, in _make_request\\n    return await self._endpoint.make_request(operation_model, request_dict)\\n', '  File \"/var/task/aiobotocore/endpoint.py\", line 91, in _send_request\\n    exception):\\n', '  File \"/var/task/aiobotocore/endpoint.py\", line 200, in _needs_retry\\n    caught_exception=caught_exception, request_dict=request_dict)\\n', '  File \"/var/task/aiobotocore/hooks.py\", line 29, in _emit\\n    response = handler(**kwargs)\\n', '  File \"/var/task/botocore/retryhandler.py\", line 183, in __call__\\n    if self._checker(attempts, response, caught_exception):\\n', '  File \"/var/task/botocore/retryhandler.py\", line 251, in __call__\\n    caught_exception)\\n', '  File \"/var/task/botocore/retryhandler.py\", line 277, in _should_retry\\n    return self._checker(attempt_number, response, caught_exception)\\n', '  File \"/var/task/botocore/retryhandler.py\", line 317, in __call__\\n    caught_exception)\\n', '  File \"/var/task/botocore/retryhandler.py\", line 223, in __call__\\n    attempt_number, caught_exception)\\n', '  File \"/var/task/botocore/retryhandler.py\", line 359, in _check_caught_exception\\n    raise caught_exception\\n', '  File \"/var/task/aiobotocore/endpoint.py\", line 156, in _do_get_response\\n    http_response = await self._send(request)\\n', '  File \"/var/task/aiobotocore/endpoint.py\", line 242, in _send\\n    request.method, url=url, headers=headers_, data=data, proxy=proxy)\\n', '  File \"/var/task/aiohttp/client.py\", line 521, in _request\\n    req, traces=traces, timeout=real_timeout\\n', '  File \"/var/task/aiohttp/connector.py\", line 535, in connect\\n    proto = await self._create_connection(req, traces, timeout)\\n', '  File \"/var/task/aiohttp/connector.py\", line 892, in _create_connection\\n    _, proto = await self._create_direct_connection(req, traces, timeout)\\n', '  File \"/var/task/aiohttp/connector.py\", line 1051, in _create_direct_connection\\n    raise last_exc\\n', '  File \"/var/task/aiohttp/connector.py\", line 1032, in _create_direct_connection\\n    client_error=client_error,\\n', '  File \"/var/task/aiohttp/connector.py\", line 971, in _wrap_create_connection\\n    raise ClientConnectorCertificateError(req.connection_key, exc) from exc\\n']}. Output:\nINIT: Using Lambda API Runtime target host: 'prepare_parallel_executors.us-east-1.localhost.localstack.cloud:4566'\nINIT: Starting daemons...\nINIT: Host 'prepare_parallel_executors.us-east-1.localhost.localstack.cloud' resolves to '172.17.0.2'\n-----\nls-daemon: Starting XRay server loop on UDP port 2000\nls-daemon: Starting DNS server loop on UDP port 53\n[WARNING]\t2021-07-01T13:17:38.445Z\t164d5183\ttype of event: <class 'bytes'>\n\n[ERROR]\t2021-07-01T13:17:38.446Z\t164d5183\tevent: {'inputArchiveFile': {'Bucket': 'test-input-bucket', 'Key': 'test-file.zip'}, 'partitionSizeInMb': 3}\n\n[ERROR] ClientConnectorCertificateError: Cannot connect to host test-input-bucket.s3.amazonaws.com:443 ssl:True [SSLCertVerificationError: (1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'test-input-bucket.s3.amazonaws.com'. (_ssl.c:1091)\")]\rTraceback (most recent call last):\r\u00a0\u00a0File \"/var/task/prepare_parallel_executors/app.py\", line 21, in handler\r\u00a0\u00a0\u00a0\u00a0images = get_list_of_images_with_file_size(event['inputArchiveFile']['Bucket'], event['inputArchiveFile']['Key'])\r\u00a0\u00a0File \"/var/task/prepare_parallel_executors/app.py\", line 30, in get_list_of_images_with_file_size\r\u00a0\u00a0\u00a0\u00a0if not s3fs_client.exists(full_path):\r\u00a0\u00a0File \"/var/task/fsspec/asyn.py\", line 87, in wrapper\r\u00a0\u00a0\u00a0\u00a0return sync(self.loop, func, *args, **kwargs)\r\u00a0\u00a0File \"/var/task/fsspec/asyn.py\", line 68, in sync\r\u00a0\u00a0\u00a0\u00a0raise result[0]\r\u00a0\u00a0File \"/var/task/fsspec/asyn.py\", line 24, in _runner\r\u00a0\u00a0\u00a0\u00a0result[0] = await coro\r\u00a0\u00a0File \"/var/task/s3fs/core.py\", line 802, in _exists\r\u00a0\u00a0\u00a0\u00a0await self._info(path, bucket, key, version_id=version_id)\r\u00a0\u00a0File \"/var/task/s3fs/core.py\", line 1057, in _info\r\u00a0\u00a0\u00a0\u00a0out = await self._simple_info(path)\r\u00a0\u00a0File \"/var/task/s3fs/core.py\", line 977, in _simple_info\r\u00a0\u00a0\u00a0\u00a0**self.req_kw,\r\u00a0\u00a0File \"/var/task/s3fs/core.py\", line 265, in _call_s3\r\u00a0\u00a0\u00a0\u00a0raise translate_boto_error(err)\r\u00a0\u00a0File \"/var/task/s3fs/core.py\", line 246, in _call_s3\r\u00a0\u00a0\u00a0\u00a0out = await method(**additional_kwargs)\r\u00a0\u00a0File \"/var/task/aiobotocore/client.py\", line 141, in _make_api_call\r\u00a0\u00a0\u00a0\u00a0operation_model, request_dict, request_context)\r\u00a0\u00a0File \"/var/task/aiobotocore/client.py\", line 160, in _make_request\r\u00a0\u00a0\u00a0\u00a0return await self._endpoint.make_request(operation_model, request_dict)\r\u00a0\u00a0File \"/var/task/aiobotocore/endpoint.py\", line 91, in _send_request\r\u00a0\u00a0\u00a0\u00a0exception):\r\u00a0\u00a0File \"/var/task/aiobotocore/endpoint.py\", line 200, in _needs_retry\r\u00a0\u00a0\u00a0\u00a0caught_exception=caught_exception, request_dict=request_dict)\r\u00a0\u00a0File \"/var/task/aiobotocore/hooks.py\", line 29, in _emit\r\u00a0\u00a0\u00a0\u00a0response = handler(**kwargs)\r\u00a0\u00a0File \"/var/task/botocore/retryhandler.py\", line 183, in __call__\r\u00a0\u00a0\u00a0\u00a0if self._checker(attempts, response, caught_exception):\r\u00a0\u00a0File \"/var/task/botocore/retryhandler.py\", line 251, in __call__\r\u00a0\u00a0\u00a0\u00a0caught_exception)\r\u00a0\u00a0File \"/var/task/botocore/retryhandler.py\", line 277, in _should_retry\r\u00a0\u00a0\u00a0\u00a0return self._checker(attempt_number, response, caught_exception)\r\u00a0\u00a0File \"/var/task/botocore/retryhandler.py\", line 317, in __call__\r\u00a0\u00a0\u00a0\u00a0caught_exception)\r\u00a0\u00a0File \"/var/task/botocore/retryhandler.py\", line 223, in __call__\r\u00a0\u00a0\u00a0\u00a0attempt_number, caught_exception)\r\u00a0\u00a0File \"/var/task/botocore/retryhandler.py\", line 359, in _check_caught_exception\r\u00a0\u00a0\u00a0\u00a0raise caught_exception\r\u00a0\u00a0File \"/var/task/aiobotocore/endpoint.py\", line 156, in _do_get_response\r\u00a0\u00a0\u00a0\u00a0http_response = await self._send(request)\r\u00a0\u00a0File \"/var/task/aiobotocore/endpoint.py\", line 242, in _send\r\u00a0\u00a0\u00a0\u00a0request.method, url=url, headers=headers_, data=data, proxy=proxy)\r\u00a0\u00a0File \"/var/task/aiohttp/client.py\", line 521, in _request\r\u00a0\u00a0\u00a0\u00a0req, traces=traces, timeout=real_timeout\r\u00a0\u00a0File \"/var/task/aiohttp/connector.py\", line 535, in connect\r\u00a0\u00a0\u00a0\u00a0proto = await self._create_connection(req, traces, timeout)\r\u00a0\u00a0File \"/var/task/aiohttp/connector.py\", line 892, in _create_connection\r\u00a0\u00a0\u00a0\u00a0_, proto = await self._create_direct_connection(req, traces, timeout)\r\u00a0\u00a0File \"/var/task/aiohttp/connector.py\", line 1051, in _create_direct_connection\r\u00a0\u00a0\u00a0\u00a0raise last_exc\r\u00a0\u00a0File \"/var/task/aiohttp/connector.py\", line 1032, in _create_direct_connection\r\u00a0\u00a0\u00a0\u00a0client_error=client_error,\r\u00a0\u00a0File \"/var/task/aiohttp/connector.py\", line 971, in _wrap_create_connection\r\u00a0\u00a0\u00a0\u00a0raise ClientConnectorCertificateError(req.connection_key, exc) from exc\nTraceback (most recent call last):\n  File \"/var/runtime/bootstrap\", line 9, in <module>\n    main()\n  File \"/var/runtime/bootstrap.py\", line 360, in main\n    event_request.deadline_time_in_ms)\n  File \"/var/runtime/bootstrap.py\", line 136, in handle_event_request\n    lambda_runtime_client.post_invocation_error(invoke_id, to_json(error_result))\n  File \"/var/runtime/lambda_runtime_client.py\", line 93, in post_invocation_error\n    raise LambdaRuntimeClientError(endpoint, response.code, response_body)\nlambda_runtime_client.LambdaRuntimeClientError: Request to Lambda Runtime '/2018-06-01/runtime/invocation/164d5183/error' endpoint failed. Reason: '200'. Response body: 'b'{}\\n''\n",
  "errorType": "InvocationException",
  "stackTrace": [
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 607, in run_lambda\n    version=version, asynchronous=asynchronous, callback=callback)\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 183, in execute\n    return do_execute()\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 175, in do_execute\n    return _run(func_arn=func_arn)\n",
    "  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 149, in wrapped\n    raise e\n",
    "  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 145, in wrapped\n    result = func(*args, **kwargs)\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 166, in _run\n    raise e\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 154, in _run\n    result = self._execute(func_arn, func_details, event, context, version)\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 375, in _execute\n    result = self.run_lambda_executor(cmd, event=stdin, env_vars=environment, func_details=func_details)\n",
    "  File \"/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/awslambda/lambda_extended.py\", line 357, in run_lambda_executor\n",
    "  File \"/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/awslambda/lambda_extended.py\", line 246, in run_lambda_executor\n",
    "  File \"/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/awslambda/lambda_extended.py\", line 276, in do_run_lambda_executor\n"
  ]
}
```

### Expected Behavior

Lambda function deployed in localstack env to be able to access files stored on localstack s3 without any modification to the application code.

### How are you starting LocalStack?

With the `localstack` script

## How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

I am using the localstack cli.
```
LOCALSTACK_API_KEY=xxxxxx SERVICES=s3,lambda,sqs,sns DEBUG=1 START_WEB=1 \
    IMAGE_NAME=localstack/localstack-full localstack start
```

Below is the log output once localstack starts

```
2021-07-01T06:16:20:INFO:localstack.utils.analytics.profiler: Execution of "load_plugin_from_path" took 586.06ms
2021-07-01T06:16:20:INFO:localstack.utils.analytics.profiler: Execution of "load_plugins" took 587.27ms
Starting local dev environment. CTRL-C to quit.
2021-07-01T06:16:23:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
2021-07-01T06:16:24:INFO:localstack.utils.analytics.profiler: Execution of "load_plugin_from_path" took 4417.45ms
2021-07-01T06:16:24:INFO:localstack.utils.analytics.profiler: Execution of "load_plugins" took 4418.20ms
docker run -it -e DEFAULT_REGION="us-east-1" -e START_WEB="1" -e TEST_AWS_ACCOUNT_ID="000000000000" -e LOCALSTACK_HOSTNAME="localhost" -e DEBUG="1" -e LOCALSTACK_API_KEY="xxxxxxxx" -e SERVICES="s3,lambda,sqs,sns" -p 0.0.0.0:53:53/udp   --rm --privileged --name localstack_main -p 443:443 -p 4566:4566 -p 8080-8081:8080-8081  -v "/private/var/folders/ht/y4094xf15lq89k6rllc8g1k83brh14/T/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/private/var/folders/ht/y4094xf15lq89k6rllc8g1k83brh14/T/localstack" "localstack/localstack-full" 
Waiting for all LocalStack services to be ready
2021-07-01 13:16:31,000 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-07-01 13:16:31,002 INFO supervisord started with pid 14
2021-07-01 13:16:32,012 INFO spawned: 'dashboard' with pid 20
2021-07-01 13:16:32,015 INFO spawned: 'infra' with pid 21
(. .venv/bin/activate; bin/localstack web)
2021-07-01 13:16:32,021 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
(. .venv/bin/activate; exec bin/localstack start --host)
Starting local dev environment. CTRL-C to quit.
2021-07-01T13:16:32:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext": <function register_localstack_commands at 0x7f42fe3b1440>
2021-07-01 13:16:33,728 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2021-07-01 13:16:36 +0000] [23] [INFO] Running on https://0.0.0.0:8081 (CTRL + C to quit)
2021-07-01T13:16:36:INFO:hypercorn.error: Running on https://0.0.0.0:8081 (CTRL + C to quit)

LocalStack version: 0.12.14
LocalStack Docker container id: 8bc8646d5c4c
LocalStack build date: 2021-06-30
LocalStack build git hash: 2b16692b

2021-07-01T13:16:36:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7f42fe82f9e0>
Waiting for all LocalStack services to be ready
2021-07-01T13:16:43:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
Waiting for all LocalStack services to be ready
Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
Starting edge router (http port 4566)...
Starting edge router (https port 443)...
Starting mock CloudWatch service on http ports 443/4566 ...
2021-07-01T13:16:46:INFO:localstack.utils.analytics.profiler: Execution of "load_plugin_from_path" took 9494.77ms
2021-07-01T13:16:46:INFO:localstack.utils.analytics.profiler: Execution of "load_plugins" took 9528.21ms
2021-07-01T13:16:46:INFO:localstack_ext.utils.aws.metadata_service: Starting AWS instance metadata service on port 80
2021-07-01T13:16:46:INFO:botocore.credentials: Found credentials in environment variables.
2021-07-01T13:16:46:INFO:botocore.credentials: Found credentials in environment variables.
[2021-07-01 13:16:46 +0000] [24] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-07-01T13:16:46:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
[2021-07-01 13:16:46 +0000] [24] [INFO] Running on https://0.0.0.0:443 (CTRL + C to quit)
2021-07-01T13:16:46:INFO:hypercorn.error: Running on https://0.0.0.0:443 (CTRL + C to quit)
2021-07-01T13:16:46:INFO:localstack.multiserver: Starting multi API server process on port 36949
[2021-07-01 13:16:46 +0000] [24] [INFO] Running on http://0.0.0.0:36949 (CTRL + C to quit)
2021-07-01T13:16:46:INFO:hypercorn.error: Running on http://0.0.0.0:36949 (CTRL + C to quit)
Starting mock Lambda service on http ports 443/4566 ...
Starting mock CloudWatch Logs service on http ports 443/4566 ...
Starting mock S3 service on http ports 443/4566 ...
Starting mock SNS service on http ports 443/4566 ...
Starting mock SQS service on http ports 443/4566 ...
2021-07-01 13:16:47,400:API:  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-07-01 13:16:47,402:API:  * Running on http://172.17.0.2:58345/ (Press CTRL+C to quit)
Waiting for all LocalStack services to be ready
2021-07-01T13:16:52:INFO:botocore.credentials: Found credentials in environment variables.
Ready.
2021-07-01T13:16:56:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 9747.97ms
```

### Setup S3 and test file

```
awslocal s3 mb s3://test-input-bucket/
awslocal s3 cp tests/common/test-file.zip s3://test-input-bucket/
```

### Deploy Lambda

```
awslocal lambda create-function --function-name prepare_parallel_executors \
    --code ImageUri=prepare_parallel_executors:latest \
    --role arn:aws:iam::000000000:role/lambda-ex \
    --timeout 900
```

### Invoke Lambda

```
awslocal lambda invoke --function-name prepare_parallel_executors \
    --payload fileb://tests/integration/test_event-prepare_parallel_executors.json \
    tests/integration/prepare_parallel_executors-response.json
```

#### Error log in localstack after Lambda invocation

```
2021-07-01T13:17:36:INFO:localstack.services.awslambda.lambda_executors: Determined main container target IP: 172.17.0.2
2021-07-01T13:17:36:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: docker run --user=root --cap-add=NET_ADMIN --entrypoint=/tmp/8cf79775.sh --dns 127.0.0.1 -e LOCALSTACK_DEBUG=1 -v /private/var/folders/ht/y4094xf15lq89k6rllc8g1k83brh14/T/localstack:/tmp -e AWS_LAMBDA_FUNCTION_MEMORY_SIZE=1536 -e _LAMBDA_RUNTIME=None -e AWS_LAMBDA_LOG_GROUP_NAME="/aws/lambda/prepare_parallel_executors" -e AWS_LAMBDA_LOG_STREAM_NAME=test -e AWS_LAMBDA_RUNTIME_API="prepare_parallel_executors.us-east-1.localhost.localstack.cloud:4566" -e LOCALSTACK_HOSTS_ENTRY="prepare_parallel_executors.us-east-1.localhost.localstack.cloud" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" prepare_parallel_executors:latest "prepare_parallel_executors.app.handler"
2021-07-01T13:17:38:INFO:botocore.credentials: Found credentials in environment variables.
ls-daemon: Starting XRay server loop on UDP port 2000
ls-daemon: Starting DNS server loop on UDP port 53
[ERROR] ClientConnectorCertificateError: Cannot connect to host test-input-bucket.s3.amazonaws.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_F    raise ClientConnectorCertificateError(req.connection_key, exc) from exconionnges_with_file_sizehiveFile']['Key'])'. (_ssl.c:1091)")]
Traceback (most recent call last):
  File "/var/runtime/bootstrap", line 9, in <module>
    main()
  File "/var/runtime/bootstrap.py", line 360, in main
    event_request.deadline_time_in_ms)
  File "/var/runtime/bootstrap.py", line 136, in handle_event_request
    lambda_runtime_client.post_invocation_error(invoke_id, to_json(error_result))
  File "/var/runtime/lambda_runtime_client.py", line 93, in post_invocation_error
    raise LambdaRuntimeClientError(endpoint, response.code, response_body)
lambda_runtime_client.LambdaRuntimeClientError: Request to Lambda Runtime '/2018-06-01/runtime/invocation/164d5183/error' endpoint failed. Reason: '200'. Response body: 'b'{}\n''
```

### Environment

```markdown
- OS: MacOS
- LocalStack: latest 

LocalStack version: 0.12.14
LocalStack Docker container id: 8bc8646d5c4c
LocalStack build date: 2021-06-30
LocalStack build git hash: 2b16692b
```

### Anything else?

I tried using the docker compose launch configuration. In that case, Lambda invocation itself would fail. With localstack cli, I was able to see my lambda start as a docker container but it is unable to connect to S3.

**Comment by whummer** [comment]
Thanks for reporting @sidthakur . This is likely related to the SSL certificates we're using for the local APIs in LocalStack.

In your Lambda handler, can you please try adding the `verify=False` flag when creating the boto3 S3 client
```
s3 = boto3.client('s3', verify=False)
```

Hope that helps - please keep us posted how it goes. Thanks!

**Comment by sidthakur** [comment]
Hi @whummer!

Thank you for the quick response. I was able to pass the `verify=False` to `boto3` through `s3fs`. For others coming to this issue
```
s3fs_client = s3fs.S3FileSystem(anon=False, client_kwargs={'verify': False})
```

Thank you for the help!

I have a related question: turning off the ssl verification does not sound like a good idea for production. What is the recommended best practice? Do folks using localstack for testing have a separate initialization with `verify=False` for test env?

**Comment by sub007** [comment]
@sidthakur : Yes, you are right. `verify=False` isn't suggested in production. 
When you move away from localstack and start using actual AWS S3 service, you must have the Amazon published certificates in the client's certificate truststore.
