### ISSUE TITLE
question: possible workaround for RDS::DBParameterGroup not yet implemented

### ISSUE THREAD

**Issue by nealbrown** [localstack/localstack#4248]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Hi I'm evaluating Pro and was wondering if there is a workaround for the following limitation, such as a way I can manually populate these missing attributes perhaps?  Thank you in advance!

`2021-07-01T16:37:04:INFO:localstack.utils.cloudformation.template_deployer: Action "create" for resource type RDS::DBParameterGroup not yet implemented - using fallback mechanism`

which appears to lead to 

`2021-07-01T16:37:04:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "CdkDevelopmentAuroraCluster7C8F76B0": Unable to extract attribute "PhysicalResourceId" from "RDS::DBParameterGroup" model class <class 'moto.rds2.models.DBParameterGroup'> Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1847, in _run
    self.do_apply_changes_in_loop(changes, stack, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1900, in do_apply_changes_in_loop
    self.apply_change(change, stack, new_resources, stack_name=stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1960, in apply_change
    self.update_resource_details(resource_id, result, stack=old_stack, action=stack_action)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1714, in update_resource_details
    physical_id = physical_id or determine_resource_physical_id(resource_id, stack=stack)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1389, in determine_resource_physical_id
    stack_name=stack_name, resource_id=resource_id, resource=resource, resources=resources)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py", line 461, in extract_resource_attribute
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 539, in extract_resource_attribute
    attribute, resource_type, type(resource_state)))
Exception: Unable to extract attribute "PhysicalResourceId" from "RDS::DBParameterGroup" model class <class 'moto.rds2.models.DBParameterGroup'>
`

**Comment by whummer** [comment]
Thanks for reporting @nealbrown . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
