### ISSUE TITLE
bug: Localstack return a 500 exception  when attempting to create an ALB listener with multiple target groups

### ISSUE THREAD

**Issue by fokion** [localstack/localstack#4275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when attempting to create an ALB Listener with multiple target groups (i.e using ForwardConfig instead of specifying simply targetgrouparn) localstack returns a 500 exception and the following stack trace is shown in the logs:
 ```shell
2021-07-08 09:06:03,663:API: 127.0.0.1 - - [08/Jul/2021 09:06:03] "POST / HTTP/1.1" 500 -
2021-07-08 09:06:03,680:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 183, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 156, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/elb/urls.py", line 33, in api_version_elb_backend
    return ELBV2Response.dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 205, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 315, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 405, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 291, in _wrapper
    response = f(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/elbv2/responses.py", line 255, in create_listener
    default_actions=default_actions,
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/elb/elb_starter.py", line 25, in create_listener
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/elbv2/models.py", line 915, in create_listener
    target_group = self.target_groups[action.data["target_group_arn"]]
KeyError: 'target_group_arn'
  ``` 
The CLI returns the following:
```shell
 aws elbv2 create-listener --load-balancer-arn arn:aws:elasticloadbalancing:eu-west-1:000000000000:loadbalancer/test-balancer/50dc6c495c0c9188 --default-actions '[{"Type": "forward", "Order": 1, "ForwardConfig": {"TargetGroups": [{"TargetGroupArn": "arn:aws:elasticloadbalancing:eu-west-1:000000000000:targetgroup/atn-2884-ST3-3000-bluegreen-blu/50dc6c495c0c9188", "Weight": 50}, {"TargetGroupArn": "arn:aws:elasticloadbalancing:eu-west-1:000000000000:targetgroup/atn-2884-ST3-3000-bluegreen-grn/50dc6c495c0c9188", "Weight": 50}]}}]' --endpoint-url http://localhost:4566```

Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:

b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'

It also fails with the same exception when using terraform.

### Expected Behavior

create a listener with 2 target group mappings 

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

- JUnit test with a spring boot application 
```
@ExtendWith(LocalstackDockerExtension.class)
@LocalstackDockerProperties(
services = { "elasticloadbalancing", "elbv2", "ec2", "autoscaling", "iam", "route53", "sts", "rds" },
environmentVariableProvider = LocalStackEnvironmentProvider.class)
@DisabledIfEnvironmentVariable(named = "DISABLE_LOCALSTACK_TESTS", matches = "TRUE")
@SpringBootTest(properties ="spring.main.allow-bean-definition-overriding=true",
args = {<arguments>})
```
- Create 2 subnets
- Create 2 target groups
- Create 1 listener
- Attempt to create a listener with 2 target group mappings , weight 0 on one and weight 1 on the other. The command should be similar to this one 

```shell
aws elbv2 create-listener --load-balancer-arn arn:aws:elasticloadbalancing:eu-west-1:000000000000:loadbalancer/test-balancer/50dc6c495c0c9188 --default-actions '[{"Type": "forward", "Order": 1, "ForwardConfig": {"TargetGroups": [{"TargetGroupArn": "arn:aws:elasticloadbalancing:eu-west-1:000000000000:targetgroup/atn-2884-ST3-3000-bluegreen-blu/50dc6c495c0c9188", "Weight": 0}, {"TargetGroupArn": "arn:aws:elasticloadbalancing:eu-west-1:000000000000:targetgroup/atn-2884-ST3-3000-bluegreen-grn/50dc6c495c0c9188", "Weight": 1}]}}]' --endpoint-url http://localhost:4566

```

### Environment

```markdown
- Dockerised localstack
- Docker 19.03.5
- AWS CLI version 1.19.58
- Terraform 0.13
- Terraform AWS Provider version 3.48.0
```

### Anything else?

```shell
2021-07-08T12:21:41:DEBUG:localstack.services.edge: IN(elbv2): "POST /" - headers: {'Remote-Addr': '172.17.0.1', 'Host': 'localhost:4566', 'User-Agent': 'APN/1.0 HashiCorp/1.0 Terraform/0.15.1 (+https://www.terraform.io) terraform-provider-aws/3.48.0 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.38.68 (go1.16; darwin; amd64)', 'Content-Length': '1144', 'Authorization': 'AWS4-HMAC-SHA256 Credential=mock_access_key/20210708/eu-west-1/elasticloadbalancing/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=9db307a0919306722e4ca69156b0d6e2755b9039cd968ab7f42c288c96debbe7', 'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'X-Amz-Date': '20210708T122141Z', 'Accept-Encoding': 'gzip', 'Connection': 'close', 'X-Forwarded-For': '172.17.0.1, localhost:4566', 'x-localstack-edge': 'http://localhost:4566'} - data: b'Action=CreateListener&Certificates.member.1.CertificateArn=arn%3Aaws%3Aacm%3Aeu-west-1%3A000000000000%3Acertificate%2Fc25ba462-8a59-4702-935d-608433e82d90&DefaultActions.member.1.ForwardConfig.TargetGroupStickinessConfig.DurationSeconds=600&DefaultActions.member.1.ForwardConfig.TargetGroupStickinessConfig.Enabled=true&DefaultActions.member.1.ForwardConfig.TargetGroups.member.1.TargetGroupArn=arn%3Aaws%3Aelasticloadbalancing%3Aeu-west-1%3A000000000000%3Atargetgroup%2Fatn-2884-ST3-3000-bluegreen-grn%2F50dc6c495c0c9188&DefaultActions.member.1.ForwardConfig.TargetGroups.member.1.Weight=0&DefaultActions.member.1.ForwardConfig.TargetGroups.member.2.TargetGroupArn=arn%3Aaws%3Aelasticloadbalancing%3Aeu-west-1%3A000000000000%3Atargetgroup%2Fatn-2884-ST3-3000-bluegreen-blu%2F50dc6c495c0c9188&DefaultActions.member.1.ForwardConfig.TargetGroups.member.2.Weight=1&DefaultActions.member.1.Order=1&DefaultActions.member.1.Type=forward&LoadBalancerArn=arn%3Aaws%3Aelasticloadbalancing%3Aeu-west-1%3A000000000000%3Aloadbalancer%2Fatn-2884-ST3-bluegreen%2F50dc6c495c0c9188&Port=443&Protocol=HTTPS&SslPolicy=ELBSecurityPolicy-2016-08&Version=2015-12-01'
 ```
 ```shell
2021-07-08 12:21:41,559:API: 127.0.0.1 - - [08/Jul/2021 12:21:41] "POST / HTTP/1.1" 500 -
2021-07-08T12:21:41:DEBUG:localstack.services.edge: OUT(elbv2): "POST /" - status: 500 - response headers: {'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '290', 'Server': 'Werkzeug/2.0.1 Python/3.7.10', 'Date': 'Thu, 08 Jul 2021 12:21:41 GMT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'Access-Control-Expose-Headers': 'x-amz-version-id'} - response: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
 ```
 
 
 
 
 ```
[
    {
        "Id": "526948d5f2256c3b0bb6dd16946f617c42ae7d891c86bc4ed50c95691dd17bc6",
        "Created": "2021-07-08T12:18:54.0904789Z",
        "Path": "docker-entrypoint.sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 47955,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-07-08T12:18:54.7476295Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:cfd7dc63ac1a4dc5e967e794d5c433d5e4cdf2a3567d26b99e189dd9d17bab6b",
        "ResolvConfPath": "/var/lib/docker/containers/526948d5f2256c3b0bb6dd16946f617c42ae7d891c86bc4ed50c95691dd17bc6/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/526948d5f2256c3b0bb6dd16946f617c42ae7d891c86bc4ed50c95691dd17bc6/hostname",
        "HostsPath": "/var/lib/docker/containers/526948d5f2256c3b0bb6dd16946f617c42ae7d891c86bc4ed50c95691dd17bc6/hosts",
        "LogPath": "/var/lib/docker/containers/526948d5f2256c3b0bb6dd16946f617c42ae7d891c86bc4ed50c95691dd17bc6/526948d5f2256c3b0bb6dd16946f617c42ae7d891c86bc4ed50c95691dd17bc6-json.log",
        "Name": "/pensive_allen",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "4566/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "4566"
                    }
                ],
                "4571/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "4571"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": true,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/a1c86ac41227e594b4d2a92073673bc86eaca4371ae51fdc14be4b2843b56e05-init/diff:/var/lib/docker/overlay2/2b03903e93e3dc2d7f295681109045b344ff43c03a7ae671ad9d33f7f6940743/diff",
                "MergedDir": "/var/lib/docker/overlay2/a1c86ac41227e594b4d2a92073673bc86eaca4371ae51fdc14be4b2843b56e05/merged",
                "UpperDir": "/var/lib/docker/overlay2/a1c86ac41227e594b4d2a92073673bc86eaca4371ae51fdc14be4b2843b56e05/diff",
                "WorkDir": "/var/lib/docker/overlay2/a1c86ac41227e594b4d2a92073673bc86eaca4371ae51fdc14be4b2843b56e05/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "526948d5f225",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "4566/tcp": {},
                "4571/tcp": {},
                "5678/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "LS_LOG=debug",
                "https_proxy=http://xx.yy.zz.aa:3128",
                "DEBUG=1",
                "USE_SSL=0",
                "no_proxy=example.com",
                "DEFAULT_REGION=eu-west-1",
                "HOSTNAME_EXTERNAL=localhost",
                "LOCALSTACK_API_KEY=<KEY>",
                "SERVICES=elasticloadbalancing,elbv2,ec2,autoscaling,iam,route53,sts,rds,acm",
                "START_WEB=1",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-11/bin:/opt/terraform",
                "NODE_VERSION=14.17.1",
                "YARN_VERSION=1.22.5",
                "LANG=C.UTF-8",
                "JAVA_HOME=/usr/lib/jvm/java-11",
                "MAVEN_HOME=/usr/share/maven",
                "MAVEN_CONFIG=/opt/code/localstack",
                "ES_TMPDIR=/tmp",
                "LOCALSTACK_BUILD_DATE=2021-07-08",
                "LOCALSTACK_BUILD_GIT_HASH=fd3f3852",
                "LD_LIBRARY_PATH=/usr/lib/jvm/java-11/lib:/usr/lib/jvm/java-11/lib/server",
                "LOCALSTACK_HOSTNAME=localhost",
                "EDGE_BIND_HOST=0.0.0.0",
                "USER=localstack",
                "PYTHONUNBUFFERED=1",
                "PYTHONPATH=/opt/code/localstack/.venv/lib/python3.8/site-packages:/opt/code/localstack/.venv/lib/python3.7/site-packages"
            ],
            "Cmd": null,
            "Image": "localstack/localstack",
            "Volumes": null,
            "WorkingDir": "/opt/code/localstack",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "authors": "LocalStack Contributors"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "775d854f9532dee60ca88b3fc993a62ef752a23075e454c4449c3c6580f23b0c",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "4566/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4566"
                    }
                ],
                "4571/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "4571"
                    }
                ],
                "5678/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/775d854f9532",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "db655f34520113af426ed2fe2e7023d70d183773cb7bd12be14a5e9c982d0573",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "de6f6b4981e23685f319fdf59deea15588d883bd23943e686f5d5e8f41b157b8",
                    "EndpointID": "db655f34520113af426ed2fe2e7023d70d183773cb7bd12be14a5e9c982d0573",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by mmarod** [comment]
Possibly related -- I am seeing errors when modifying the access log attributes on an existing ELB

```
bash-5.0# awslocal elb modify-load-balancer-attributes --load-balancer-name moo --load-balancer-attributes "{\"AccessLog\":{\"Enabled\":false}}"

Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

Other attributes work fine:

```
bash-5.0# awslocal elb modify-load-balancer-attributes --load-balancer-name moo --load-balancer-attributes "{\"ConnectionSettings\":{\"IdleTimeout\":90}}"
{
    "LoadBalancerName": "moo",
    "LoadBalancerAttributes": {
        "AccessLog": {
            "Enabled": false
        },
        "ConnectionSettings": {
            "IdleTimeout": 90
        }
    }
}
```

**Comment by HarshCasper** [comment]
Thank you for reaching out.

This issue will be closed because the LocalStack version that was reported is no longer supported.

If you're still experiencing this issue on a [supported version](https://hub.docker.com/r/localstack/localstack/tags) of LocalStack, please file a new issue for that version of LocalStack.

Thank you in advance. Your assistance is appreciated.
