### ISSUE TITLE
question: How do I bypass "InvocationException" thrown by "lambda_executors.py" for Step Functions retry/catch functionality?

### ISSUE THREAD

**Issue by joffarex** [localstack/localstack#4303]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

So today I have a lambda, which throws an Error. This lambda is part of State Machine, which has a configuration to retry/catch on this Error, however, it is not happening as lambda is actually throwing `InvocationException` insead of my defined error to the infra and State Machine only sees that error.

example lambda code: 
```javascript
module.exports.handler = (event, context, callback) => {
    class CustomError extends Error {
      constructor() {
        super("Custom error message");
        this.name = "CustomError";
      }
    }

    throw new CustomError();
  }
```

Response I get from invoking lambda manually by `awslocal lambda invoke --function-name <name> <output-path>`:
```json
{
  "errorMessage": "Lambda process returned error status code: 1. Result: {\"errorType\":\"CustomError\",\"errorMessage\":\"Custom error message\"}. Output:\n\u001b[32mSTART RequestId: 9f066cef-1163-174a-5dea-2c4a5964df4c Version: $LATEST\u001b[0m\n2021-07-14T10:23:39.066Z\t9f066cef-1163-174a-5dea-2c4a5964df4c\tERROR\tInvoke Error \t{\"errorType\":\"CustomError\",\"errorMessage\":\"Custom error message\",\"name\":\"CustomError\",\"stack\":[\"CustomError: Custom error message\",\"    at Runtime.test1 [as handler] (/var/task/handlers.js:25:11)\",\"    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)\"]}\n\u001b[32mEND RequestId: 9f066cef-1163-174a-5dea-2c4a5964df4c\u001b[0m\n\u001b[32mREPORT RequestId: 9f066cef-1163-174a-5dea-2c4a5964df4c\tInit Duration: 114.64 ms\tDuration: 5.23 ms\tBilled Duration: 100 ms\tMemory Size: 1536 MB\tMax Memory Used: 48 MB\t\u001b[0m",
  "errorType": "InvocationException",
  "stackTrace": [
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 739, in run_lambda\n    callback=callback,\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 224, in execute\n    return do_execute()\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 214, in do_execute\n    return _run(func_arn=func_arn)\n",
    "  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 157, in wrapped\n    raise e\n",
    "  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 153, in wrapped\n    result = func(*args, **kwargs)\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 201, in _run\n    raise e\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 189, in _run\n    result = self._execute(func_arn, func_details, event, context, version)\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 451, in _execute\n    cmd, event=stdin, env_vars=environment, func_details=func_details\n",
    "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 342, in run_lambda_executor\n    result,\n"
  ]
}
```

This is also the response seen by State Machine, hence it does not retry nor catch the `CustomError`. What could a workaround be with this? 

From the `lambda_executors.py` at [line 337](https://github.com/localstack/localstack/blob/master/localstack/services/awslambda/lambda_executors.py) I can see that it throws `InvocationException` if lambda's return error code is not equal to 0. I suppose 0 means success, and because my lambda throws an error, it fails because of it, but I don't want that to happen. What could I do?

**Comment by joffarex** [comment]
I am kind of blocked by this thing. have not been able to resolve it.

**Comment by DevairS** [comment]
I have this problem too

**Comment by eRobertsRGARE** [comment]
My state machines depend on error handling and routing logic for different error types coming out of lambda. This all works in AWS, but upgrading localstack to 0.11 or later has broken this by converting all our custom errors to InvocationException.

I haven't been able to find a work around for this yet.
