### ISSUE TITLE
Dynambodb: Cannot do operations on a non-existent table

### ISSUE THREAD

**Issue by fazal-kh4n** [localstack/localstack#4306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I carry out 3 distinct steps:

1. create a table
2. list all tables that have been created
3. delete the table I just created

I can carry out the first 2 steps without any issues, but step 3 throws an error. I am using `boto3` to make all the calls, but I do not think the issue is with `boto3`.

Terminal output when I carry out steps 1-3:

1. `Table succesfully created`
2. `[dynamodb.Table(name='example')]`
3. 
```
Traceback (most recent call last):
  File "/src/src/dynamo.py", line 59, in <module>
    delete_table()
  File "/src/src/dynamo.py", line 43, in delete_table
    table.delete()
  File "/usr/local/lib/python3.9/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DeleteTable operation: Cannot do operations on a non-existent table
```

### Expected Behavior

I would expect to see the following terminal output:

1. `Table succesfully created`
2. `[dynamodb.Table(name='example')]`
3. `Table has been deleted`

The table should be deleted without throwing an error as it exists.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

My yaml file:

```
version: "3.9"
services:
    localstack:
        image: "localstack/localstack"
        container_name: "localstack"
        environment:
            - SERVICES=sns,lambda,dynamodb
        ports:
            - '4563-4599:4563-4599'
        stdin_open: true
        tty: true
        volumes:
            - "${PWD}/ls_tmp:/tmp/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
        environment: 
            - DEBUG=1
            - LAMBDA_EXECUTOR=docker-reuse
            - KINESIS_PROVIDER=kinesalite
            - LAMBDA_DOCKER_NETWORK=example_network
        networks:
            - example

    app_layer:
        image: 'integration-layer'
        container_name: 'integration-layer'
        build: ./app_layer
        ports: 
            - "8888:8888"
        volumes:
            - ./app_layer:/src
        env_file: ./common.env
        stdin_open: true
        tty: true
        networks:
            - example
networks:
    example:
        name: example_network
```

My actual code to run steps 1-3 is as follows:

```
TABLE_NAME = "example"

dynamodb = boto3.resource(
    "dynamodb",
    aws_access_key_id="",
    aws_secret_access_key="",
    endpoint_url="http://localstack:4566",
    region_name="us-east-1",
)


def create_table(table_name):
    dynamodb.create_table(
        TableName=table_name,
        KeySchema=[
            {"AttributeName": "id", "KeyType": "HASH"},
        ],
        AttributeDefinitions=[
            {"AttributeName": "id", "AttributeType": "S"},
        ],
        ProvisionedThroughput={"ReadCapacityUnits": 10, "WriteCapacityUnits": 10},
    )
    print("Table succesfully created")


def delete_table():
    table = dynamodb.Table(TABLE_NAME)
    table.delete()
    print("Table has been deleted")


def list_tables():
    tables = list(dynamodb.tables.all())
    print(tables)
```

### Environment

```markdown
- OS: macOS Big Sur, v. 11.4
- LocalStack: latest
```

**Comment by mgagliardo** [comment]
Thanks for reporting this @fazal-kh4n, there seems to be a weird issue which requires further investigation this, as an example executing your code successfully returns the listed tables, however the AWS CLI does not:


And then, if you create a DynamoDB table using the AWS CLI:
```
$ aws --endpoint-url http://localhost:4566     dynamodb create-table     --table-name "example-table"     --attribute-definitions AttributeName=pk,AttributeType=S AttributeName=sk,AttributeType=S     --key-schema AttributeName=pk,KeyType=HASH AttributeName=sk,KeyType=RANGE     --provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=5

$ awslocal dynamodb list-tables
{
    "TableNames": [
        "example-table"
    ]
}
```

However it still does not return the table created via boto3. Same backwards:

```
client.list_tables()['TableNames']
['example']
```

I'll dig a bit more into this issue and why is this inconsistency happening.

**Comment by mgagliardo** [comment]
Hello @fazal-kh4n, I have just ran through your code again and seems either boto3 internally works very weird or there's something else, per boto3's dynamodb doc I have found the following working without any issues (even creating tables with aws cli), please run it with the `latest` localstack image as well and let me know:

```
import boto3

TABLE_NAME = "example"

dynamodb = boto3.client(
    "dynamodb",
    aws_access_key_id="test",
    aws_secret_access_key="test",
    endpoint_url="http://localhost:4566",
    region_name="us-east-1",
)

def create_table():
    dynamodb.create_table(
        TableName=TABLE_NAME,
        KeySchema=[
            {"AttributeName": "id", "KeyType": "HASH"},
        ],
        AttributeDefinitions=[
            {"AttributeName": "id", "AttributeType": "S"},
        ],
        ProvisionedThroughput={"ReadCapacityUnits": 10, "WriteCapacityUnits": 10},
    )
    print("Table succesfully created")


def delete_table():
    dynamodb.delete_table(TableName=TABLE_NAME)
    print("Table has been deleted")


def list_tables():
    tables = dynamodb.list_tables()
    print(tables)

list_tables()
create_table()
list_tables()
delete_table()
list_tables()
```

Just a couple changes, so it seems you explicitly need to pass an `aws_access_key_id` and `aws_secret_access_key`.

Output:
```
>>> list_tables()
{'TableNames': [], 'ResponseMetadata': {'RequestId': 'b75f73fd-8a7d-45e0-b595-d393f427be4e', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/x-amz-json-1.0', 'content-length': '17', 'x-amz-crc32': '1315925753', 'x-amzn-requestid': 'b75f73fd-8a7d-45e0-b595-d393f427be4e', 'connection': 'close', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging,amz-sdk-invocation-id,amz-sdk-request', 'access-control-expose-headers': 'x-amz-version-id', 'date': 'Mon, 19 Jul 2021 08:30:20 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}

>>> create_table()
Table succesfully created

>>> list_tables()
{'TableNames': ['example'], 'ResponseMetadata': {'RequestId': '53e71e1b-76a9-425c-893e-d57c12041549', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/x-amz-json-1.0', 'content-length': '26', 'x-amz-crc32': '4095288248', 'x-amzn-requestid': '53e71e1b-76a9-425c-893e-d57c12041549', 'connection': 'close', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging,amz-sdk-invocation-id,amz-sdk-request', 'access-control-expose-headers': 'x-amz-version-id', 'date': 'Mon, 19 Jul 2021 08:30:20 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}

>>> delete_table()
Table has been deleted

>>> list_tables()
{'TableNames': [], 'ResponseMetadata': {'RequestId': 'e0704133-f30e-4dc8-98c5-93ccf9e64104', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/x-amz-json-1.0', 'content-length': '17', 'x-amz-crc32': '1315925753', 'x-amzn-requestid': 'e0704133-f30e-4dc8-98c5-93ccf9e64104', 'connection': 'close', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging,amz-sdk-invocation-id,amz-sdk-request', 'access-control-expose-headers': 'x-amz-version-id', 'date': 'Mon, 19 Jul 2021 08:30:20 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
```

And now you can see both when creating (additionally) a table with the CLI:
```
>>> list_tables()
{'TableNames': ['example', 'example-table'], 'ResponseMetadata': {'RequestId': '94c81a09-9da1-4b06-88af-fe087cd8560a', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/x-amz-json-1.0', 'content-length': '42', 'x-amz-crc32': '4044939065', 'x-amzn-requestid': '94c81a09-9da1-4b06-88af-fe087cd8560a', 'connection': 'close', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging,amz-sdk-invocation-id,amz-sdk-request', 'access-control-expose-headers': 'x-amz-version-id', 'date': 'Mon, 19 Jul 2021 08:30:43 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
```

In any case, give it a try and let me know. Cheers

**Comment by fazal-kh4n** [comment]
Hi @mgagliardo,

Thank you very much for the response. Your suggestion has indeed fixed the issue, I have no idea why it does not work with an empty string but the workaround looks to be good.

This resolves all the issues.

**Comment by mgagliardo** [comment]
Glad it worked, cheers mate.
