### ISSUE TITLE
aws s3api delete-objects errors

### ISSUE THREAD

**Issue by allenbenz** [localstack/localstack#432]
I looks like `aws s3api delete-objects` sends a POST request with no Content-Type headers.

:ERROR:localstack.services.generic_proxy: Error forwarding request: cannot concatenate 'str' and 'NoneType' objects Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 171, in forward
    path=path, data=data, headers=forward_headers)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 348, in forward_request
    expanded_data = expand_multipart_filename(original_data, headers)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 260, in expand_multipart_filename
    _, params = cgi.parse_header(headers.get('Content-Type'))
  File "/usr/lib/python2.7/cgi.py", line 309, in parse_header
    parts = _parseparam(';' + line)
TypeError: cannot concatenate 'str' and 'NoneType' objects

adding 
```
if not 'Content-Type' in headers:
    return ...
```

before the two `headers.get('Content-Type')` in s3_listener.py makes it work again.

**Comment by allenbenz** [comment]
Nevermind, looks like it was fixed in #431
