### ISSUE TITLE
Unable to invoke lambda, getting time out message after sometime

### ISSUE THREAD

**Issue by ashameem123** [localstack/localstack#4337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a Lambda function which is feeding an event to SNS topic. 
Steps:
1. Create Lambda function
2. Create SNS topic
3. Subscribe lambda to topic
4. Invoke lambda

After running invoke command, getting below message in docker but nothing is happening and in the terminal getting Time out after few seconds:

 2021-07-21T21:36:17:INFO:localstack.services.awslambda.lambda_executors: Running lambda: arn:aws:lambda:us-east-1:000000000000:function:SnsPublishFunction

Timeout msg:
Read timeout on endpoint URL: "http://localhost:4566/2015-03-31/functions/SnsPublishFunction/invocations"

### Expected Behavior

Lambda should successfully be invoked and SNS should receive an event from lambda (as per the handler function written)

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose up -d

Commands:

aws --endpoint-url=http://localhost:4566 lambda create-function --function-name SnsPublishFunction --runtime java11 --handler Functions.SnsPublishFunction --zip-file fileb://bpx-aws-automation.jar --role arn:aws:iam::1234567:role/anything123 --environment Variables="{PROFILE=LOCAL,AWS_REGION=us-east-1}"

aws sns create-topic --name mySnsTopic --endpoint-url=http://localhost:4566

aws --endpoint-url=http://localhost:4566 sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:mySnsTopic --protocol lambda --notification-endpoint arn:aws:lambda:us-east-1:000000000000:function:SnsPublishFunction

aws --endpoint-url=http://localhost:4566 lambda invoke --function-name SnsPublishFunction --payload fileb://lambda-event.json /tmp/outfile.txt

### Environment

```markdown
- OS: windows 10
- LocalStack: latest
```

### Anything else?

docker-compose.yml File content:
version: '2.1'

services:

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LAMBDA_DOCKER_NETWORK=localstack_default
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  localstack_default:
    driver: bridge

volumes:
  data01:
    driver: local

![image](https://user-images.githubusercontent.com/54183749/126564317-05c1ae6e-bfae-4f68-959a-333294317e78.png)

![image](https://user-images.githubusercontent.com/54183749/126564362-f3243693-43bf-48e5-bd20-3b5d2f36ee3b.png)

Project SNAPSHOT:
[bpx-aws-automation.zip](https://github.com/localstack/localstack/files/6858983/bpx-aws-automation.zip)

**Comment by mgagliardo** [comment]
Hello @ashameem123, looks like your payload in the following command is missing, can you please add it?

```
aws --endpoint-url=http://localhost:4566 lambda invoke --function-name SnsPublishFunction --payload fileb://lambda-event.json /tmp/outfile.txt
```

**Comment by ashameem123** [comment]
@mgagliardo - Attached is the json I  am using.
![image](https://user-images.githubusercontent.com/54183749/126646041-66cab825-276e-4ee9-9800-762ccd2f696a.png)



json content:

{
  "colors": [
    {
      "color": "black",
      "category": "hue",
      "type": "primary",
      "code": {
        "rgba": [
          255,
          255,
          255,
          1
        ],
        "hex": "#000"
      }
    },
    {
      "color": "yellow",
      "category": "hue",
      "type": "primary",
      "code": {
        "rgba": [
          255,
          255,
          0,
          1
        ],
        "hex": "#FF0"
      }
    }
    
  ]
}

**Comment by ashameem123** [comment]
@mgagliardo - Any update please?

**Comment by mgagliardo** [comment]
Hello @ashameem123, sorry for the delay, it looks like you need to change your docker compose a little bit, the following should work:

```
version: '3.9'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  data01:
    driver: local
```

I have only added `LAMBDA_EXECUTOR=docker` and `LAMBDA_REMOTE_DOCKER=false` to execute the function on a remote container instead of doing a local execution. Either way it looks like the handler `--handler Functions.SnsPublishFunction` is not correct, but that is unrelated to the localstack config:

```
localstack_main  | localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: {"errorType":"java.lang.ClassNotFoundException","errorMessage":"Class not found: Functions.SnsPublishFunction"}. Output:

...

localstack_main  | Class not found: Functions.SnsPublishFunction: java.lang.ClassNotFoundException
localstack_main  | java.lang.ClassNotFoundException: Functions.SnsPublishFunction
localstack_main  | 	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
localstack_main  | 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
localstack_main  | 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
localstack_main  | 	at java.base/java.lang.Class.forName0(Native Method)
localstack_main  | 	at java.base/java.lang.Class.forName(Unknown Source)
```

In any case, give it a try and let me know. Cheers!
