### ISSUE TITLE
bug: Can't run localstack start on macbook pro m1

### ISSUE THREAD

**Issue by levrado** [localstack/localstack#4358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Macbook pro m1

Big Sur 11.4

```
> docker --version
Docker version 20.10.7, build f0df350
> pip --version
pip 21.1.2 from /Users/levrado/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pip (python 3.9)
> python --version
Python 3.9.5
> javac -version
javac 16.0.1
> java -version
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

Running `SERVICES=dynamodb,s3 localstack --debug start` 

Getting 
```
2021-07-25T17:31:13:ERROR:localstack.services.kinesis.kinesis_starter: kinesis terminated with return code -11
...
Waiting for all LocalStack services to be ready
2021-07-25 17:33:59,022 INFO exited: infra (exit status 2; not expected)
Error starting infrastructure: kinesis backend has stopped Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/plugins.py", line 105, in check_infra
    api=name, print_error=print_error, expect_shutdown=expect_shutdown
  File "/opt/code/localstack/localstack/services/plugins.py", line 147, in check_service_health
    raise e
  File "/opt/code/localstack/localstack/services/plugins.py", line 140, in check_service_health
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/plugins.py", line 45, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 174, in check_kinesis
    raise AssertionError("kinesis backend has stopped")
AssertionError: kinesis backend has stopped
```

Full logs: https://gist.github.com/levrado/8330deaaa9582bfba6959fab76ae1148

### Expected Behavior

Expecting to be able to connect to localstack dynamodb and s3 on macbook pro m1

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Macbook pro m1

Big Sur 11.4

```
> docker --version
Docker version 20.10.7, build f0df350
> pip --version
pip 21.1.2 from /Users/levrado/.pyenv/versions/3.9.5/lib/python3.9/site-packages/pip (python 3.9)
> python --version
Python 3.9.5
> javac -version
javac 16.0.1
> java -version
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

Running `SERVICES=dynamodb,s3 localstack --debug start` 

### Environment

```markdown
- Machine: macbook pro m1
- OS: Big Sur 11.4
- LocalStack: 0.12.15.1
- Docker: Docker version 20.10.7, build f0df350
- Python: 3.9.5
- Pip: pip 21.1.2
- javac: javac 16.0.1
- java: java version "16.0.1" 2021-04-20 (Java(TM) SE Runtime Environment (build 16.0.1+9-24), Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing))
```

**Comment by elbaulp** [comment]
I'm facing the same exception, also running a M1

**Comment by zale144** [comment]
Same for me, I didn't even run Kinesis, so not sure why it says it's crashing

**Comment by zwing99** [comment]
I just confirmed that some change made in https://github.com/localstack/localstack/releases/tag/v0.12.13 blocks the use of kinesis which seems to kill lots. version 0.12.12 seems to work for me.

**Comment by chris-planetly** [comment]
I can confirm this problem. 

I see a bunch of these errors:
```
2021-08-25T08:58:16:INFO:localstack.utils.common: Restarting process (received exit code 1): 
cd /opt/code/localstack/localstack/infra/dynamodb/; 
java -Djava.library.path=./DynamoDBLocal_lib -Xmx256m -jar DynamoDBLocal.jar -port 58237 -inMemory
```

and a Kinesis Error message in the logs:
```
2021-08-25T08:58:11:ERROR:localstack.services.kinesis.kinesis_starter: kinesis terminated with return code -11
```

For reference, I'm running LocalStack version: 0.12.17 (build git hash: a5fa3838)

**Comment by whummer** [comment]
Thanks for reporting @chris-planetly @zwing99 @zale144 @elbaulp @levrado . It seems that we're facing quite a few issues with JVM processes in M1 macbooks. We have added an option that allows you to switch back to an alternative Kinesis provider implementation (kinesalite). Can you please try setting the `KINESIS_PROVIDER=kinesalite` option in the LocalStack Docker container environment? Thanks

**Comment by elbaulp** [comment]
Still does not work for me. If I try to enable `kinesis` or `dynamodb` I keep getting this errors:

```
2021-08-30T13:17:33:INFO:localstack.utils.common: Restarting process (received exit code 1): cd /opt/code/localstack/localstack/infra/dynamodb/; java -Djava.library.path=./DynamoDBLocal_lib -Xmx256m -jar DynamoDBLocal.jar -port 32951 -inMemory
localstack_1  | Waiting for all LocalStack services to be ready
```

This is my docker-compose:

```
version: "3"

services:
  redis:
    image: redis:4.0.10-alpine
    ports:
      - xxxx:xxxx
  localstack:
    image: localstack/localstack:0.12.17
    environment:
      SERVICES: "dynamodb, kinesis, s3, sqs"
      KINESIS_PROVIDER: "kinesalite"
    ports:
      - xxxx:xxxx
```

The error is the same for kinesis and dynamodb.

If I wait enough, I get this traceback:

```
localstack_1  | Error starting infrastructure: 'NoneType' object is not subscriptable Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/plugins.py", line 196, in check_infra
localstack_1  |     api=name, print_error=print_error, expect_shutdown=expect_shutdown
localstack_1  |   File "/opt/code/localstack/localstack/services/plugins.py", line 238, in check_service_health
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/services/plugins.py", line 231, in check_service_health
localstack_1  |     plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
localstack_1  |   File "/opt/code/localstack/localstack/services/plugins.py", line 132, in check
localstack_1  |     return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
localstack_1  |   File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_starter.py", line 35, in check_dynamodb
localstack_1  |     assert isinstance(out["TableNames"], list)
localstack_1  | TypeError: 'NoneType' object is not subscriptable
```

**Comment by expelledboy** [comment]
The `KINESIS_PROVIDER=kinesalite` does not work for me.

I am getting the same error as above, but I have attached the one that is raised through `bin/localstack`

<details>
  <summary>TypeError: 'NoneType' object is not subscriptable</summary>



```
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "bin/localstack", line 23, in <module>
localstack_1  |     main()
localstack_1  |   File "bin/localstack", line 19, in main
localstack_1  |     main.main()
localstack_1  |   File "/opt/code/localstack/localstack/cli/main.py", line 6, in main
localstack_1  |     cli()
localstack_1  |   File "/opt/code/localstack/localstack/cli/plugin.py", line 30, in __call__
localstack_1  |     self.group(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
localstack_1  |     return self.main(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/click/core.py", line 1062, in main
localstack_1  |     rv = self.invoke(ctx)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
localstack_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
localstack_1  |     return ctx.invoke(self.callback, **ctx.params)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/click/core.py", line 763, in invoke
localstack_1  |     return __callback(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/cli/localstack.py", line 107, in cmd_start
localstack_1  |     bootstrap.start_infra_locally()
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 412, in start_infra_locally
localstack_1  |     return infra.start_infra()
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 485, in start_infra
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 471, in start_infra
localstack_1  |     thread = do_start_infra(asynchronous, apis, is_in_docker)
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 563, in do_start_infra
localstack_1  |     thread = start_api_services()
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 133, in wrapped
localstack_1  |     return f(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/infra.py", line 550, in start_api_services
localstack_1  |     check_infra(apis=apis)
localstack_1  |   File "/opt/code/localstack/localstack/services/plugins.py", line 210, in check_infra
localstack_1  |     additional_checks=additional_checks,
localstack_1  |   File "/opt/code/localstack/localstack/services/plugins.py", line 210, in check_infra
localstack_1  |     additional_checks=additional_checks,
localstack_1  |   File "/opt/code/localstack/localstack/services/plugins.py", line 210, in check_infra
localstack_1  |     additional_checks=additional_checks,
localstack_1  |   [Previous line repeated 7 more times]
localstack_1  |   File "/opt/code/localstack/localstack/services/plugins.py", line 204, in check_infra
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/services/plugins.py", line 196, in check_infra
localstack_1  |     api=name, print_error=print_error, expect_shutdown=expect_shutdown
localstack_1  |   File "/opt/code/localstack/localstack/services/plugins.py", line 238, in check_service_health
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/services/plugins.py", line 231, in check_service_health
localstack_1  |     plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
localstack_1  |   File "/opt/code/localstack/localstack/services/plugins.py", line 132, in check
localstack_1  |     return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
localstack_1  |   File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_starter.py", line 35, in check_dynamodb
localstack_1  |     assert isinstance(out["TableNames"], list)
localstack_1  | TypeError: 'NoneType' object is not subscriptable
localstack_1  | 2021-08-31 10:50:13,349 INFO exited: infra (exit status 2; not expected)
localstack_1  | make: *** [Makefile:57: infra] Error 1
localstack_1  | 2021-08-31 10:50:14,367 INFO spawned: 'infra' with pid 693
```
 

</details>

**Comment by ptz0n** [comment]
FYI: We've successfully run on M1 using version `localstack/localstack:0.12.18`.

**Comment by marcelja** [comment]
> FYI: We've successfully run on M1 using version `localstack/localstack:0.12.18`.

Is 0.12.18 some unreleased version?

**Comment by whummer** [comment]
Hi @chris-planetly @zwing99 @zale144 @elbaulp @levrado @carmonac @expelledboy @ptz0n @marcelja , we have recently introduced a multi-arch build for ARM64+AMD64, which is available from LocalStack version 0.13.0 onwards (and in the `latest` Docker image). 

Apple M1 notebooks should now be natively supported. There are still a few limitations (documented [here](https://github.com/localstack/localstack/issues/4921)) which we'll continue to tackle in the coming weeks. 

If you're experiencing any issues running LocalStack on M1, then please report here or create a new issue with details on how to reproduce. Thanks for your help!

**Comment by alexrashed** [comment]
Hi there.
With 0.13.0 (released last week) we now have an arm64-native Docker image of LocalStack. This version contains the workaround of using `kinesalite` for the arm64 version (as described by @whummer above).
But this actually isn't necessary anymore, since `kinesis-mock` should work as expected when running natively.
Therefore, we removed the workaround again with #4980. All `latest` versions now use `kinesis-mock` (while you can still change it by using the environment variable `KINESIS_PROVIDER`).
So - long story short - these changes should hopefully fix your issues. Could you give the `latest` version a try and tell us if this issue has been fixed?

**Comment by carmonac** [comment]
Hi, I had this bug in Intel based.

**Comment by alexrashed** [comment]
> Hi, I had this bug in Intel based.

Ah, okay, I see. Do you still have this issue? If so, could you please file a new issue? This one explicitly addresses problems on Apple M1 / arm64, and it feels like we'd be mixing up different issues in here.

**Comment by b7rnee** [comment]
Try it. :)
pip uninstall localstack and then
pip3 install localstack worked for me
