### ISSUE TITLE
bug: [PRO] Unable to parse date : 2021-07-27T05:19:31.726Z when Creating QLDB Ledger with Java QldbClient

### ISSUE THREAD

**Issue by richardkabiling** [localstack/localstack#4367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a ledger using the following dependency:
```
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>qldb</artifactId>
      <version>2.17.2</version>
    </dependency>
```

The SDK throws an error
```
software.amazon.awssdk.core.exception.SdkClientException: Unable to unmarshall response (Unable to parse date : 2021-07-27T05:27:20.925Z). Response Code: 200, Response Text: 

```

```
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to parse date : 2021-07-27T05:19:31.726Z
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)
	at software.amazon.awssdk.protocols.core.StringToInstant.lambda$safeParseDate$0(StringToInstant.java:77)
	at software.amazon.awssdk.protocols.core.StringToInstant.convert(StringToInstant.java:54)
	at software.amazon.awssdk.protocols.core.StringToInstant.convert(StringToInstant.java:32)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller$SimpleTypeJsonUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:179)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshallStructured(JsonProtocolUnmarshaller.java:231)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:217)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonProtocolUnmarshaller.unmarshall(JsonProtocolUnmarshaller.java:187)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:82)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.JsonResponseHandler.handle(JsonResponseHandler.java:36)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonResponseHandler.handle(AwsJsonResponseHandler.java:44)
	at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.lambda$handle$0(MetricCollectingHttpResponseHandler.java:52)
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:64)
	at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.handle(MetricCollectingHttpResponseHandler.java:52)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:94)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$resultTransformationResponseHandler$7(BaseClientHandler.java:287)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleSuccessResponse(CombinedResponseHandler.java:97)
	... 102 more
Caused by: java.lang.NumberFormatException: Character array is missing "e" notation exponential mark.
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:570)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:394)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:827)
	at software.amazon.awssdk.utils.DateUtils.parseUnixTimestampInstant(DateUtils.java:159)
	at software.amazon.awssdk.protocols.core.StringToInstant.lambda$safeParseDate$0(StringToInstant.java:72)
	... 117 more
```

### Expected Behavior

The ledger should be created without any exception being thrown by the SDK

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up
    
#### Steps
1. Bring up environment using `docker compose up`
```
version: '2.1'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "443:443"
    environment:
      SERVICES: "qldb"
      START_WEB: "0"
      DEFAULT_REGION: "eu-west-1"
      LOCALSTACK_API_KEY: "..."
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "./init.d:/docker-entrypoint-initaws.d"
```
2. Send `CreateLedgerRequest` via the configured SDK
```
client.createLedger(CreateLedgerRequest.builder()
        .name(props.getLedger())
        .permissionsMode("ALLOW_ALL")
        .deletionProtection(false)
        .build());
```
3. Check exception

### Environment

```markdown
- OS: MacOS Big Sur
- LocalStack: latest,0.12.15,0.12.10,0.11.6,0.11.2
- Language: Java
- AWS SDK (QLDB): 2.17.2
```

**Comment by richardkabiling** [comment]
This has already been resolved in `latest` docker image (0.12.16)
