### ISSUE TITLE
Call to AmazonS3Util.DoesS3BucketExistV2Async comes back with MethodNotAllowed error

### ISSUE THREAD

**Issue by aiampogi** [localstack/localstack#4375]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I'm using https (https://localhost:4566) Then, when calling the C# SDK AmazonS3Util.DoesS3BucketExistV2Async, it returns a MethodNotAllowed error.

Stacktrace looks like this:
```
Amazon.S3.AmazonS3Exception: Error making request with Error Code MethodNotAllowed and Http Status Code MethodNotAllowed. No further error information was returned by the service.
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Util.AmazonS3Util.DoesS3BucketExistV2Async(IAmazonS3 s3Client, String bucketName)
```

### Expected Behavior

It should just return bucket not found error if the bucket is not existing. Or should just succeed.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    Use C# SDK AmazonS3Util.DoesS3BucketExistV2Async and use any string as bucket.

### Environment

```markdown
- OS: Windows 10
- LocalStack: latest
```
DockerHub link: [https://hub.docker.com/layers/localstack/localstack/latest/images/sha256-f6a93d243a427af2e99bf9f283843497081659a50f9f7955bd4ce4aded874347?context=explore](https://hub.docker.com/layers/localstack/localstack/latest/images/sha256-f6a93d243a427af2e99bf9f283843497081659a50f9f7955bd4ce4aded874347?context=explore)

**Comment by aiampogi** [comment]
I saw this issue: #4289 but I'm already using the latest image (4 hours ago).

**Comment by pinzon** [comment]
@aiampogi I just finished triaging your issue with version 0.12.16 and both versions works fine using this code:

```csharp
using Amazon;
using Amazon.S3;
using Amazon.S3.Model;
using Amazon.S3.Util;
using System;
using System.Threading.Tasks;

class CreateBucketTest
{
	private const string bucketName = "kevs-bucket-test";
	private static readonly RegionEndpoint bucketRegion = RegionEndpoint.USEast1;
	private static IAmazonS3 s3Client;


	public static void Main()
	{
		AmazonS3Config config = new AmazonS3Config { ServiceURL = "http://localhost:4566", ForcePathStyle = true};
		s3Client = new AmazonS3Client(config);
		CreateBucketAsync().Wait();
	}

	static async Task CreateBucketAsync()
	{
		try
		{
			if (await AmazonS3Util.DoesS3BucketExistV2Async(s3Client, bucketName))
			{
				Console.WriteLine("Bucket does exists");
				await s3Client.DeleteBucketAsync(bucketName);
				Console.WriteLine("Now is deleted");
			}else{
				Console.WriteLine("Bucket does not exists");
				await s3Client.PutBucketAsync(bucketName);
				Console.WriteLine("Now exists");
			}
		}
		catch (Exception e)
		{
			Console.WriteLine("Unknown encountered on server. Message:'{0}'", e.Message);
		}
	}
}
```
In version 0.12.15 doesn't seem to work so sure to pull the latest version. 
Let me know if I can help with anything else.

**Comment by aiampogi** [comment]
hi @pinzon , you've missed one significant detail in my issue. I'm using HTTPS. How can I reopen this issue?

**Comment by pinzon** [comment]
Hi @aiampogi, you're right, I focused on the wrong thing on this issue.
I'll look more into it.

**Comment by aiampogi** [comment]
thanks @pinzon ! I wonder what the issue is? Will this be resolved in the next release? thanks!

**Comment by pinzon** [comment]
Hi @aiampogi, thank you for your patience, while going back to triage again (some months ago) my GNU/Linux dev set up presented some problems with SSL and Localstack. After talking with other devs some fixes were recommended before I can triage correctly your situation. 

I'll see again if I can finally work to reproduce your issue exactly or if have to pass it to another developer.

**Comment by pinzon** [comment]
@aiampogi after testing with the latest version of Localstack, the `HTTPS` issue has been fixed, and the response for the `AmazonS3Util.DoesS3BucketExistV2Async` method is correct.
Thank you for reporting this issue.
