### ISSUE TITLE
Bootstrapping with modern 

### ISSUE THREAD

**Issue by BStenfors9119** [localstack/localstack#4388]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I am trying to bootstrap with the modern template but I keep getting the following error/issue.  I am wondering what I might do?

I am seeing the same behavior.

I have @aws-cdk/core:newStyleStackSynthesis set to "true" and also setting CDK_NEW_BOOTSTRAP=1 in environment vars.

Sorry for the long post but posting the whole debug output from trying to bootstrap in hopes it will help :).

```
docker_localstack_2 | 2021-07-29 17:38:56,513:API: 127.0.0.1 - - [29/Jul/2021 17:38:56] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29 17:38:56,669:API: 127.0.0.1 - - [29/Jul/2021 17:38:56] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29 17:39:15,224:API: 127.0.0.1 - - [29/Jul/2021 17:39:15] "POST / HTTP/1.1" 400 -
docker_localstack_2 | 2021-07-29 17:39:15,257:API: 127.0.0.1 - - [29/Jul/2021 17:39:15] "POST / HTTP/1.1" 400 -
docker_localstack_2 | 2021-07-29 17:39:15,682:API: 127.0.0.1 - - [29/Jul/2021 17:39:15] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29 17:39:15,704:API: 127.0.0.1 - - [29/Jul/2021 17:39:15] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29T17:39:15:DEBUG:localstack.services.cloudformation.cloudformation_api: Executing change set "cdk-deploy-change-set" for stack "CDKToolkit" with 13 resources ...
docker_localstack_2 | 2021-07-29 17:39:15,739:API: 127.0.0.1 - - [29/Jul/2021 17:39:15] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Skipping deployment of "FileAssetsBucketEncryptionKey", as resource condition evaluates to false
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "FileAssetsBucketEncryptionKey" (1/13) type "AWS::KMS::Key" in loop iteration 1
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Skipping deployment of "FileAssetsBucketEncryptionKeyAlias", as resource condition evaluates to false
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "FileAssetsBucketEncryptionKeyAlias" (1/12) type "AWS::KMS::Alias" in loop iteration 1
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: AWS::S3::Bucket Ref
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29 17:39:16,679:API: 127.0.0.1 - - [29/Jul/2021 17:39:16] "GET /cdk-cfd-local-assets-000000000000-us-east-1?location HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Description': 'The name of the S3 bucket owned by the 
CDK toolkit stack', 'Value': {'Fn::Sub': '${StagingBucket}'}} - Unable to resolve attribute ref StagingBucket
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29 17:39:16,768:API: 127.0.0.1 - - [29/Jul/2021 17:39:16] "GET /cdk-cfd-local-assets-000000000000-us-east-1?location HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: S3::Bucket RegionalDomainName
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29 17:39:16,863:API: 127.0.0.1 - - [29/Jul/2021 17:39:16] "GET /cdk-cfd-local-assets-000000000000-us-east-1?location HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "StagingBucket" (1/11) type "AWS::S3::Bucket" in loop iteration 1
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:16:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: AWS::ECR::Repository Ref
docker_localstack_2 | 2021-07-29T17:39:17:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type ECR::Repository when resolving references of resource ContainerAssetsRepository:
 {'Type': 'AWS::ECR::Repository', 'LogicalResourceId': 'ContainerAssetsRepository', 'Properties': {'RepositoryName': {'Fn::If': ['HasCustomContainerAssetsRepositoryName', {'Fn::Sub': '${ContainerAssetsRepos
itoryName}'}, {'Fn::Sub': 'cdk-${Qualifier}-container-assets-${AWS::AccountId}-${AWS::Region}'}]}}}
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Description': 'The name of the ECR repository which ho
sts docker image assets', 'Value': {'Fn::Sub': '${ContainerAssetsRepository}'}} - Unable to fetch details for resource "ContainerAssetsRepository" (attribute "Ref")
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29 17:39:17,288:API: 127.0.0.1 - - [29/Jul/2021 17:39:17] "POST / HTTP/1.1" 400 -
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Description': 'The version of the bootstrap resources 
that are currently mastered in this stack', 'Value': {'Fn::GetAtt': ['CdkBootstrapVersion', 'Value']}} - Unable to fetch details for resource "CdkBootstrapVersion" (resolving attribute "Value")
docker_localstack_2 | 2021-07-29 17:39:17,312:API: 127.0.0.1 - - [29/Jul/2021 17:39:17] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29 17:39:17,532:API: 127.0.0.1 - - [29/Jul/2021 17:39:17] "GET /cdk-cfd-local-assets-000000000000-us-east-1?policy HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "StagingBucketPolicy" (1/10) type "AWS::S3::BucketPolicy" in loop iteration 1
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:17:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type ECR::Repository when resolving references of resource ContainerAssetsRepository:
 {'Type': 'AWS::ECR::Repository', 'LogicalResourceId': 'ContainerAssetsRepository', 'Properties': {'RepositoryName': 'cdk-cfd-local-container-assets-000000000000-us-east-1'}}
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "ContainerAssetsRepository" (1/9) type "AWS::ECR::Repository" in loop iteration
 1
docker_localstack_2 | 2021-07-29T17:39:17:INFO:localstack.utils.cloudformation.template_deployer: Action "create" for resource type ECR::Repository not yet implemented - using fallback mechanism
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Unable to extract name for resource type "AWS::ECR::Repository"
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: ECR::Repository PhysicalResourceId
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29 17:39:17,708:API: 127.0.0.1 - - [29/Jul/2021 17:39:17] "POST / HTTP/1.1" 404 -
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "FilePublishingRole" (1/8) type "AWS::IAM::Role" in loop iteration 1
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "IAM::Role" id "FilePublishingRole"
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "IAM::Role" in region us-east-1: create_role {'AssumeRolePolicyDocument': '{"Stat
ement": [{"Action": "sts:AssumeRole", "Effect": "Allow", "Principal": {"AWS": "000000000000"}}, {"Action": "sts:AssumeRole", "Effect": "Allow", "Principal": {"AWS": ""}}]}', 'RoleName': 'cdk-cfd-local-file-
publishing-role-000000000000-us-east-1', 'Tags': [{'Key': 'aws-cdk:bootstrap-role', 'Value': 'file-publishing'}]}
docker_localstack_2 | 2021-07-29 17:39:17,764:API: 127.0.0.1 - - [29/Jul/2021 17:39:17] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29 17:39:17,788:API: 127.0.0.1 - - [29/Jul/2021 17:39:17] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29 17:39:17,823:API: 127.0.0.1 - - [29/Jul/2021 17:39:17] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29 17:39:17,921:API: 127.0.0.1 - - [29/Jul/2021 17:39:17] "POST / HTTP/1.1" 404 -
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "ImagePublishingRole" (1/7) type "AWS::IAM::Role" in loop iteration 1
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "IAM::Role" id "ImagePublishingRole"
docker_localstack_2 | 2021-07-29T17:39:17:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "IAM::Role" in region us-east-1: create_role {'AssumeRolePolicyDocument': '{"Stat
ement": [{"Action": "sts:AssumeRole", "Effect": "Allow", "Principal": {"AWS": "000000000000"}}, {"Action": "sts:AssumeRole", "Effect": "Allow", "Principal": {"AWS": ""}}]}', 'RoleName': 'cdk-cfd-local-image
-publishing-role-000000000000-us-east-1', 'Tags': [{'Key': 'aws-cdk:bootstrap-role', 'Value': 'image-publishing'}]}
docker_localstack_2 | 2021-07-29 17:39:17,957:API: 127.0.0.1 - - [29/Jul/2021 17:39:17] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29 17:39:17,982:API: 127.0.0.1 - - [29/Jul/2021 17:39:17] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29 17:39:18,097:API: 127.0.0.1 - - [29/Jul/2021 17:39:18] "POST / HTTP/1.1" 404 -
docker_localstack_2 | 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "LookupRole" (1/6) type "AWS::IAM::Role" in loop iteration 1
docker_localstack_2 | 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "IAM::Role" id "LookupRole"
docker_localstack_2 | 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "IAM::Role" in region us-east-1: create_role {'AssumeRolePolicyDocument': '{"Stat
ement": [{"Action": "sts:AssumeRole", "Effect": "Allow", "Principal": {"AWS": "000000000000"}}, {"Action": "sts:AssumeRole", "Effect": "Allow", "Principal": {"AWS": ""}}, {"Action": "sts:AssumeRole", "Effec
t": "Allow", "Principal": {"AWS": ""}}]}', 'RoleName': 'cdk-cfd-local-lookup-role-000000000000-us-east-1', 'Tags': [{'Key': 'aws-cdk:bootstrap-role', 'Value': 'lookup'}]}
docker_localstack_2 | 2021-07-29 17:39:18,123:API: 127.0.0.1 - - [29/Jul/2021 17:39:18] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Running put_role_policy(...) for IAM::Role policy: cdk-cfd-local-lookup-role-000000000000-us-east-1 LookupR
olePolicy {"Statement": [{"Sid": "DontReadSecrets", "Effect": "Deny", "Action": ["kms:Decrypt"], "Resource": "*"}], "Version": "2012-10-17"}
docker_localstack_2 | 2021-07-29 17:39:18,140:API: 127.0.0.1 - - [29/Jul/2021 17:39:18] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29 17:39:18,163:API: 127.0.0.1 - - [29/Jul/2021 17:39:18] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29 17:39:18,466:API: 127.0.0.1 - - [29/Jul/2021 17:39:18] "POST / HTTP/1.1" 404 -
docker_localstack_2 | 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "FilePublishingRoleDefaultPolicy" (1/5) type "AWS::IAM::Policy" in loop iterati
on 1
docker_localstack_2 | 2021-07-29 17:39:18,489:API: 127.0.0.1 - - [29/Jul/2021 17:39:18] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "IAM::Policy" id "FilePublishingRoleDefaultPolicy"
docker_localstack_2 | 2021-07-29 17:39:18,538:API: 127.0.0.1 - - [29/Jul/2021 17:39:18] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29 17:39:18,556:API: 127.0.0.1 - - [29/Jul/2021 17:39:18] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: ECR::Repository Arn
docker_localstack_2 | 2021-07-29T17:39:18:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "CDKToolkit": Unable to extract attribute "Arn" from "ECR::
Repository" model class <class 'moto.ecr.models.Repository'> Traceback (most recent call last):
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2109, in _run
docker_localstack_2 |     self.do_apply_changes_in_loop(changes, stack, stack_name)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2159, in do_apply_changes_in_loop
docker_localstack_2 |     resource_id, change, stack, new_resources
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2218, in prepare_should_deploy_change
docker_localstack_2 |     resolve_refs_recursively(stack.stack_name, resource, new_resources)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/common.py", line 461, in func
docker_localstack_2 |     return wrapped(*args, **kwargs)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 933, in resolve_refs_recursively
docker_localstack_2 |     value[key] = resolve_refs_recursively(stack_name, val, resources)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/common.py", line 461, in func
docker_localstack_2 |     return wrapped(*args, **kwargs)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 933, in resolve_refs_recursively
docker_localstack_2 |     value[key] = resolve_refs_recursively(stack_name, val, resources)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/common.py", line 461, in func
docker_localstack_2 |     return wrapped(*args, **kwargs)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 933, in resolve_refs_recursively
docker_localstack_2 |     value[key] = resolve_refs_recursively(stack_name, val, resources)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/common.py", line 461, in func
docker_localstack_2 |     return wrapped(*args, **kwargs)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 937, in resolve_refs_recursively
docker_localstack_2 |     value[i] = resolve_refs_recursively(stack_name, value[i], resources)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/common.py", line 461, in func
docker_localstack_2 |     return wrapped(*args, **kwargs)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 933, in resolve_refs_recursively
docker_localstack_2 |     value[key] = resolve_refs_recursively(stack_name, val, resources)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/common.py", line 461, in func
docker_localstack_2 |     return wrapped(*args, **kwargs)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 855, in resolve_refs_recursively
docker_localstack_2 |     result, stack_name=stack_name, resources=resources
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 976, in resolve_placeholders_in_string
docker_localstack_2 |     result = re.sub(regex, _replace, result)
docker_localstack_2 |   File "/usr/lib/python3.7/re.py", line 194, in sub
docker_localstack_2 |     return _compile(pattern, flags).sub(repl, string, count)
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 948, in _replace
docker_localstack_2 |     stack_name, resource_name.strip(), resources, attribute=attr_name.strip()
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 771, in resolve_ref
docker_localstack_2 |     stack_name=stack_name,
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1591, in determine_resource_physical_id
docker_localstack_2 |     resources=resources,
docker_localstack_2 |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 611, in extract_resource_attribute
docker_localstack_2 |     % (attribute, resource_type, type(resource_state))
docker_localstack_2 | Exception: Unable to extract attribute "Arn" from "ECR::Repository" model class <class 'moto.ecr.models.Repository'>
docker_localstack_2 | 
docker_localstack_2 | 2021-07-29 17:39:19,852:API: 127.0.0.1 - - [29/Jul/2021 17:39:19] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29 17:39:21,889:API: 127.0.0.1 - - [29/Jul/2021 17:39:21] "POST / HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29T17:39:22:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: AWS::S3::Bucket Ref
docker_localstack_2 | 2021-07-29 17:39:22,372:API: 127.0.0.1 - - [29/Jul/2021 17:39:22] "GET /cdk-cfd-local-assets-000000000000-us-east-1?location HTTP/1.1" 200 -
docker_localstack_2 | 2021-07-29T17:39:22:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Description': 'The name of the S3 bucket owned by the 
CDK toolkit stack', 'Value': {'Fn::Sub': '${StagingBucket}'}} - Unable to resolve attribute ref StagingBucket
docker_localstack_2 | 2021-07-29T17:39:22:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: AWS::ECR::Repository Ref
docker_localstack_2 | 2021-07-29T17:39:22:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
docker_localstack_2 | 2021-07-29 17:39:22,434:API: 127.0.0.1 - - [29/Jul/2021 17:39:22] "POST / HTTP/1.1" 400 -
docker_localstack_2 | 2021-07-29T17:39:22:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Description': 'The version of the bootstrap resources 
that are currently mastered in this stack', 'Value': {'Fn::GetAtt': ['CdkBootstrapVersion', 'Value']}} - Unable to fetch details for resource "CdkBootstrapVersion" (resolving attribute "Value")
docker_localstack_2 | 2021-07-29 17:39:22,443:API: 127.0.0.1 - - [29/Jul/2021 17:39:22] "POST / HTTP/1.1" 200 -
```

**Comment by whummer** [comment]
Thanks for reporting @BStenfors9119 , and apologies for the delay. Can you please share the version/age of the Docker image you're using - it should get printed in the LocalStack container startup logs, something like:
```
LocalStack version: 0.12.16
LocalStack Docker container id: ...
LocalStack build date: 2021-08-05
LocalStack build git hash: 42b46c2a
```

We've recently made a couple of enhancements to CloudFormation - can you please pull the `latest` Docker image and check if the problem still persists? If you could share a copy of your template, we'll be happy to look into it in more detail.. Thanks for your help!

**Comment by BStenfors9119** [comment]
@whummer thanks for the reply and no worries on the delay.  We're all busy :D.

Here is the info:

docker_localstack_1 | LocalStack version: 0.12.16
docker_localstack_1 | LocalStack Docker container id: 9dd39ede468d
docker_localstack_1 | LocalStack build date: 2021-08-03
docker_localstack_1 | LocalStack build git hash: 09397616


Just started it back up via docker-compose so will give it another try and see if anything has changed.

Thanks,
B
