### ISSUE TITLE
awslocal S3 put-bucket-cors error

### ISSUE THREAD

**Issue by Manriquedev** [localstack/localstack#439]
Hi,

I run this comand line:

>  awslocal s3api put-bucket-cors --bucket test --cors-configuration file://cors.json

and I saw this on runner container log.
```
localstack_1  | 2017-11-02T16:57:35:ERROR:localstack.services.generic_proxy: Error forwarding request: 'unicode' object has no attribute 'get' Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 185, in forward
localstack_1  |     path=path, data=data, headers=forward_headers, response=response)
localstack_1  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 470, in return_response
localstack_1  |     append_cors_headers(bucket_name, request_method=method, request_headers=headers, response=response)
localstack_1  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 197, in append_cors_headers
localstack_1  |     allowed_methods = rule.get('AllowedMethod', [])
localstack_1  | AttributeError: 'unicode' object has no attribute 'get'

```

my cors.json file :
```

{
   "CORSRules":[
      {
         "AllowedOrigins":[
            "*"
         ],
         "AllowedHeaders":[
            "x-amz-meta-name"
         ],
         "AllowedMethods":[
            "PUT", "GET"
         ],
         "MaxAgeSeconds":3000,
         "ExposeHeaders": ["x-amz-meta-name"]
      } 
   ]
}

```

I just update the project today 2017/11/02

**Comment by whummer** [comment]
Thanks for reporting @Manriquedev . This is fixed in the latest version. Closing this issue - please re-open or comment here if this problem persists. Thanks
