### ISSUE TITLE
bug: creating eks cluster with aws-sdk-go is not working

### ISSUE THREAD

**Issue by tomerber2** [localstack/localstack#4407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi !
When I am creating an EKS cluster using aws go sdk with this code:
```
eksInput := eks.CreateClusterInput{
		ClientRequestToken: aws.String("1d2129a1-3d38-460a-9756-e5b91fddb951"),
		Name:               aws.String(eksClusterName),
		ResourcesVpcConfig: &eks.VpcConfigRequest{
			SecurityGroupIds: []*string{eksSecurityGroupId},
			SubnetIds:        []*string{eksSubnet1Id, eksSubnet2Id},
		},
		RoleArn: eksRoleArn,
		Version: aws.String(eksVersion),
	}
	_, err = eksSvc.CreateCluster(&eksInput)
	if err != nil {
		log.Info(err.Error())
		return err
	}
```
I am getting the following error:
```
time="2021-08-03T14:27:38+03:00" level=info msg="SerializationError: failed to unmarshal response error\n\tstatus code: 500, request id: \ncaused by: UnmarshalError: failed decoding error message
```
and I am getting this error in the docker container:
```
2021-08-03T11:27:37:ERROR:eks_api: Exception on /clusters [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/eks/eks_api.py", line 62, in load_config
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 815, in load_kube_config
    persist_config=persist_config)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 773, in _get_kube_config_loader
    'Invalid kube-config file. '
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/eks/eks_api.py", line 103, in create_cluster
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/eks/eks_api.py", line 67, in load_config
Exception: Unable to connect to local Kubernetes cluster: Invalid kube-config file. No configuration found.
2021-08-03T11:27:37:ERROR:eks_api: Exception on /clusters [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/eks/eks_api.py", line 62, in load_config
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 815, in load_kube_config
    persist_config=persist_config)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 773, in _get_kube_config_loader
    'Invalid kube-config file. '
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.


```
Same code is working for me with real AWS resources. 

Thanks, Tomer.

### Expected Behavior

Expected behavior is that the EKS cluster will be created

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

### Environment

```markdown
- OS: ubuntu 20.04
- LocalStack: latest
```

**Comment by alexrashed** [comment]
Hi @tomerber2!

I just tried to reproduce your issue, but I wasn't successful.
I created a minimal sample using the `aws-sdk-go` v1:
```
package main

import (
	"fmt"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/endpoints"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/eks"
)

func main() {
	sess := session.Must(session.NewSession(&aws.Config{
		Region:   aws.String(endpoints.UsWest2RegionID),
		Endpoint: aws.String("localhost.localstack.cloud:443"),
	}))
	eksSvc := eks.New(sess)
	eksRoleArn := aws.String("arn:aws:iam::012345678910:role/eks-service-role-AWSServiceRoleForAmazonEKS")
	eksSecurityGroupId := aws.String("test-security-group-id")
	eksSubnet1Id := aws.String("test-subnet-id-1")
	eksSubnet2Id := aws.String("test-subnet-id-2")
	eksVersion := "1.10"
	eksClusterName := "TestCluster"
	eksInput := eks.CreateClusterInput{
		ClientRequestToken: aws.String("1d2129a1-3d38-460a-9756-e5b91fddb951"),
		Name:               aws.String(eksClusterName),
		ResourcesVpcConfig: &eks.VpcConfigRequest{
			SecurityGroupIds: []*string{eksSecurityGroupId},
			SubnetIds:        []*string{eksSubnet1Id, eksSubnet2Id},
		},
		RoleArn: eksRoleArn,
		Version: aws.String(eksVersion),
	}
	_, err := eksSvc.CreateCluster(&eksInput)
	if err != nil {
		fmt.Println(err.Error())
	}
}
```

Running this MWE against a running instance of LocalStack Pro is successful on my end:
```
$ LOCALSTACK_API_KEY=xxxxxx localstack start -d
$ localstack wait
$ go run main.go
$ awslocal eks describe-cluster --region us-west-2 --name "TestCluster"
{
    "cluster": {
        "name": "TestCluster",
        "arn": "arn:aws:eks:us-west-2:000000000000:cluster/TestCluster",
        "createdAt": 1659533596.881,
        "version": "1.10",
        "roleArn": "arn:aws:iam::012345678910:role/eks-service-role-AWSServiceRoleForAmazonEKS-J7ONKE3BQ4PI",
        "resourcesVpcConfig": {
            "subnetIds": [
                "test-subnet-id-1",
                "test-subnet-id-2"
            ],
            "securityGroupIds": [
                "test-security-group-id"
            ]
        },
        "identity": {
            "oidc": {
                "issuer": "https://localhost.localstack.cloud/eks-oidc"
            }
        },
        "status": "CREATING",
        "clientRequestToken": "1d2129a1-3d38-460a-9756-e5b91fddb951"
    }
}
```

Could you maybe give it a try with the latest version?
Thanks!

**Comment by thrau** [comment]
Closing this for staleness. Please give it a try with the latest of localstack. You are welcome to open a new issue if the problem persists.
