### ISSUE TITLE
bug: [PRO] 400 returned when selecting from an from QLDB Table

### ISSUE THREAD

**Issue by richardkabiling** [localstack/localstack#4418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An execute select statement throws the following exception (query in exception below):

```
Caused by: software.amazon.awssdk.services.qldbsession.model.BadRequestException: Unable to execute query: Command '['/tmp/localstack/partiql/partiql-cli-0.2.1/bin/partiql', '-q', 'SELECT * FROM Wallet WHERE id = `"company::843f7222-4a42-4478-81a1-39bbdcbe2571"`', '-e', '/tmp/tmp__t7hke5', '-i', '/tmp/tmpfek1ievi', '-o', '/tmp/tmp_tw1npug', '--of', 'ION_TEXT']' returned non-zero exit status 1. (Service: QldbSession, Status Code: 400, Request ID: null, Extended Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123) ~[sdk-core-2.17.2.jar:?]
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:79) ~[sdk-core-2.17.2.jar:?]
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59) ~[sdk-core-2.17.2.jar:?]
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40) ~[sdk-core-2.17.2.jar:?]
```

### Expected Behavior

The query should return the results.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

docker-compose.yml

```
version: '2.1'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "443:443"
    environment:
      SERVICES: "qldb"
      START_WEB: "0"
      DEFAULT_REGION: "eu-west-1"
      LOCALSTACK_API_KEY: "..."
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "./init.d:/docker-entrypoint-initaws.d"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
try {
        var r = txn.execute("""
                SELECT * FROM Wallet WHERE id = ?
                """,
              mapper.writeValueAsIonValue("id::" + id));

          var iterator = r.iterator();
          if (iterator.hasNext()) {
            var wallet = mapper.readValue(iterator.next(), Wallet.class);
            return Optional.of(wallet);
          } else {
            return Optional.empty();
          }
        } catch (IOException e) {
          throw new UncheckedIOException(e);
      }
```

This yields the following exception
```
Caused by: software.amazon.awssdk.services.qldbsession.model.BadRequestException: Unable to execute query: Command '['/tmp/localstack/partiql/partiql-cli-0.2.1/bin/partiql', '-q', 'SELECT * FROM Wallet WHERE id = `"company::843f7222-4a42-4478-81a1-39bbdcbe2571"`', '-e', '/tmp/tmp__t7hke5', '-i', '/tmp/tmpfek1ievi', '-o', '/tmp/tmp_tw1npug', '--of', 'ION_TEXT']' returned non-zero exit status 1. (Service: QldbSession, Status Code: 400, Request ID: null, Extended Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123) ~[sdk-core-2.17.2.jar:?]
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:79) ~[sdk-core-2.17.2.jar:?]
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59) ~[sdk-core-2.17.2.jar:?]
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40) ~[sdk-core-2.17.2.jar:?]
```

Note: it is unclear yet why this is happening. I think this only happens in this specific query, but this passes in real QLDB.

Additional info
* tables are newly created
* table creation have been verified by querying the driver
* this is executed as an integration test that also has stream processing in it (Kafka)

### Environment

```markdown
- OS: MacOS Big Sur
- LocalStack: latest
- Language: Java
- QldbDriver: 2.3.1
```

**Comment by whummer** [comment]
Thanks for reporting @richardkabiling . Looks like we haven't been able to replicate this issue so far - can you please also share the state of the table - i.e., which items are written to the table before the `SELECT` query gets executed? Thanks for your help!

**Comment by richardkabiling** [comment]
@whummer It's starting to look like some kind of race condition.

In this scenario a previous write has succeeded and then a succeeding fetch failed

In some attempts, I've also gotten the following error (which looks a little more obfuscated) and it looks like it is selecting from an anonymous table that looks like the structure of one of my tables where I've written data in:

```
Caused by: software.amazon.awssdk.services.qldbsession.model.BadRequestException: Unable to execute query: Command '['/tmp/localstack/partiql/partiql-cli-0.2.1/bin/partiql', '-q', 'select * from `{id:"comany::767d3553-0505-4aa9-ace0-f849844aff93:7313e2a6-becf-4e98-9e84-fe6db4622940",assetId:"comany::767d3553-0505-4aa9-ace0-f849844aff93",key:"7313e2a6-becf-4e98-9e84-fe6db4622940"}`', '-e', '/tmp/tmpt57k0ipv', '-i', '/tmp/tmp9gwan_8_', '-o', '/tmp/tmp84761gsx', '--of', 'ION_TEXT']' returned non-zero exit status 1. (Service: QldbSession, Status Code: 400, Request ID: null, Extended Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:79)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40)
```

**Comment by whummer** [comment]
Thanks for the update @richardkabiling . As per your feedback on Slack, this seems to be resolved in the meantime - please keep us posted if the problem persists.. Thanks for your help!
