### ISSUE TITLE
bug: KMS sign does not work in 0.12.16

### ISSUE THREAD

**Issue by mwidner** [localstack/localstack#4419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

KMS signing no longer works in 0.12.16. The logs show this:
`2021-08-05 22:10:00,809:API: 127.0.0.1 - - [05/Aug/2021 22:10:00] "POST / HTTP/1.1" 500 -
2021-08-05 22:10:00,814:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 181, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 148, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 205, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 315, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 420, in call_action
    "The {0} action has not been implemented".format(action)
NotImplementedError: The sign action has not been implemented
`

Downgrading to 0.12.15 makes the error go away.

### Expected Behavior

KMS signing requests work.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    Set up in docker-compose.yml

`localstack:
    container_name: ${COMPOSE_PROJECT_NAME}-localstack-container
    build:
      context: ./localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,kms,dynamodb,sqs,serverless
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ../container-files/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 1g`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    Using the AWS SDK for PHP:
`$this->client->sign([
            'KeyId' => $keyId,
            'Message' => $payload,
            'MessageType' => self::MESSAGE_TYPE,
            'SigningAlgorithm' => $signingAlgo
        ]);`

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest (0.12.16)
```

**Comment by silv-io** [comment]
Hello, have you tried using the `local-kms` provider for KMS? You can activate it by setting the environment variable `KMS_PROVIDER` to `local-kms`.
