### ISSUE TITLE
bug: different behaviour against AWS lambda with python runtime and Docker image

### ISSUE THREAD

**Issue by FPRM** [localstack/localstack#4432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I build my moock lambda image.
process is in an app.py and execute as following:
```
import json
def handler(event, context):
    data=context
    return {
        'statusCode': 200,
        'body': json.dumps({"event":event,"message":"hello from localstack"})
            }
```
then in launch my local stack with the following docker compose.

```
version: '3.3'
services:
  localstack:
    image: localstack/localstack:0.12.15
    ports:
      - "53:53"
      - "443:443"
      - "4566-4583:4566-4583"
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - DEFAULT_REGION=eu-west-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER= E:/Sources/container_Lambda/storage_localstack
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOVE_CONTAINERS=true
      - LAMBDA_REMOTE_DOCKER=false
      - SERVICES=lambda,s3,iam,cloudwatch,dynamodb
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "E:/Sources/container_Lambda/storage_localstack/TMP:/tmp/localstack"
    networks:
      - localstacknet
    privileged: true
  test-lambda:
    image: test-lambda:latest
    build:
      context: ./
    networks:
      - localstacknet
  
networks:
  localstacknet:
    external: false
    driver : bridge
    name: localstacknet
```

from my terminal i create the function in my local stack.
The response confirm the function creation

When i invoke it
the image spawn to execute the lambda, terminal inside docker container shows:

```
2021-08-12 08:18:16,034:API: 127.0.0.1 - - [12/Aug/2021 08:18:16] "POST / HTTP/1.1" 200 -

2021-08-12 08:18:16,064:API: 127.0.0.1 - - [12/Aug/2021 08:18:16] "POST / HTTP/1.1" 200 -

2021-08-12 08:18:16,094:API: 127.0.0.1 - - [12/Aug/2021 08:18:16] "POST / HTTP/1.1" 200 -

2021-08-12 08:18:16,122:API: 127.0.0.1 - - [12/Aug/2021 08:18:16] "POST / HTTP/1.1" 200 -

2021-08-12 08:18:16,150:API: 127.0.0.1 - - [12/Aug/2021 08:18:16] "POST / HTTP/1.1" 200 -

2021-08-12T08:18:16:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:eu-west-1:000000000000:function:testlambdabis: Lambda process returned error status code: 1. Result: {"errorType":"Runtime.ImportModuleError","errorMessage":"Unable to import module 'app': No module named 'app'"}. Output:

START RequestId: f426bee4-2e3e-1c0d-1e3d-5d598e2dafbb Version: $LATEST

[ERROR] Runtime.ImportModuleError: Unable to import module 'app': No module named 'app'

END RequestId: f426bee4-2e3e-1c0d-1e3d-5d598e2dafbb

REPORT RequestId: f426bee4-2e3e-1c0d-1e3d-5d598e2dafbb Init Duration: 119.69 ms Duration: 7.84 ms Billed Duration: 100 ms Memory Size: 1536 MB Max Memory Used: 28 MB Traceback (most recent call last):

File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 734, in run_lambda

callback=callback,

File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 224, in execute

return do_execute()

File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 214, in do_execute

return _run(func_arn=func_arn)

File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 157, in wrapped

raise e

File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 153, in wrapped

result = func(*args, **kwargs)

File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 201, in _run

raise e

File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 189, in _run

result = self._execute(func_arn, func_details, event, context, version)

File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 451, in _execute

cmd, event=stdin, env_vars=environment, func_details=func_details

File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 342, in run_lambda_executor

result,

localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned error status code: 1. Result: {"errorType":"Runtime.ImportModuleError","errorMessage":"Unable to import module 'app': No module named 'app'"}. Output:

START RequestId: f426bee4-2e3e-1c0d-1e3d-5d598e2dafbb Version: $LATEST

[ERROR] Runtime.ImportModuleError: Unable to import module 'app': No module named 'app'

END RequestId: f426bee4-2e3e-1c0d-1e3d-5d598e2dafbb

REPORT RequestId: f426bee4-2e3e-1c0d-1e3d-5d598e2dafbb Init Duration: 119.69 ms Duration: 7.84 ms Billed Duration: 100 ms Memory Size: 1536 MB Max Memory Used: 28 MB
```

And the Request response shows me the same.

### Expected Behavior

When i reproduce the process but this time with the AWS VPC

- Build the same image
- push it to ECR registry
- Create AWS function with my image
When i test it from the console i achieve the execution.
Same succes when trying the lambda locally directly with a container and pass a localhost API query

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

from the terminal at the root of my project.
`docker compose -f local_stack_compose.yml up`

docker compose is:
```
version: '3.3'
services:
  localstack:
    image: localstack/localstack:0.12.15
    
    ports:
      - "53:53"
      - "443:443"
      - "4566-4583:4566-4583"
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - DEFAULT_REGION=eu-west-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER= E:/Sources/container_Lambda/storage_localstack
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOVE_CONTAINERS=true
      - LAMBDA_REMOTE_DOCKER=false
      - SERVICES=lambda,s3,iam,cloudwatch,dynamodb
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "E:/Sources/container_Lambda/storage_localstack/TMP:/tmp/localstack"
    networks:
      - localstacknet
    
    privileged: true
  test-lambda:
    image: test-lambda:latest
    build:
      context: ./
    networks:
      - localstacknet
  
networks:
  localstacknet:
    external: false
    driver : bridge
    name: localstacknet
```

Then from python in an anaconda virtual env

```
import boto3
import json

lambda_client = boto3.client('lambda',region_name="eu-west-1",endpoint_url='https://localhost:4566',verify=False)
response_lambda_create = lambda_client.create_function(
                                        FunctionName="testlambda",
                                       
                                        Publish=True,
                                        Handler='app.handler',
                                        Role= "arn:aws:iam::000000000:role/lambda-ex",
                                        Code={
                                            'ImageUri':'test-lambda:latest',
                                            },
                                        Description="test" ,
                                        PackageType='Image',
                                        Runtime='python3.7',
                                    )
```

the response of lambda creation is confirmed by request response

```
{'ResponseMetadata': {'HTTPStatusCode': 200,
  'HTTPHeaders': {'content-type': 'application/json',
   'content-length': '565',
   'access-control-allow-origin': '*',
   'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH',
   'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging',
   'access-control-expose-headers': 'x-amz-version-id',
   'connection': 'close',
   'date': 'Thu, 12 Aug 2021 08:26:04 GMT',
   'server': 'hypercorn-h11'},
  'RetryAttempts': 0},
 'FunctionName': 'testlambda',
 'FunctionArn': 'arn:aws:lambda:eu-west-1:000000000000:function:testlambda',
 'Runtime': 'python3.7',
 'Role': 'arn:aws:iam::000000000:role/lambda-ex',
 'Handler': 'app.handler',
 'Description': 'test',
 'Timeout': 3,
 'LastModified': '2021-08-12T08:26:04.520+0000',
 'Version': '1',
 'VpcConfig': {},
 'TracingConfig': {'Mode': 'PassThrough'},
 'RevisionId': '3f0c8108-439d-4fb5-9940-054eae38d4dc',
 'State': 'Active',
 'LastUpdateStatus': 'Successful',
 'PackageType': 'Image'}
```

trying to invoke the function after

```
response_invoke = lambda_client.invoke(
    FunctionName='arn:aws:lambda:eu-west-1:000000000000:function:testlambda',
    InvocationType='RequestResponse',
    LogType='None',
    Payload=json.dumps({"address": "Passeig del Born, 5, 08003 Barcelona, Espagne"}).encode()
)

```

receive the response request saying unable to import module app
same showed in the docker terminal

### Environment

```markdown
- os : Windows 10
- Docker Desktop
- Docker Engine V 20.10.7
- Docker engine config: 

{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": false,
  "experimental": false,
  "features": {
    "buildkit": true
  },
  "builder": {
    "gc": {
      "enabled": true,
      "defaultKeepStorage": "20GB"
    }
  }
}
```

- python 3.7
- localstack 0.12.15
```


### Anything else?

I'm pretty sure the solution could be a workaround, by rewrapping the code or change some configuration.
My point in this bug is to fix the delta between the AWS lambda behavior and the local stack behavior.
Both should be the same.

**Comment by FPRM** [comment]
Lambda execution wasn't on the same network as local stack.
Correct by modifying the docker compose, and force the selection of the runtime when create lambda function

**Comment by vrbrito** [comment]
@FPRM Did you edit the docker-compose to show the latest one?
I'm having a similar problem, I think, but I'm getting the error below:

![image](https://user-images.githubusercontent.com/44675971/129377656-533a59be-fa5d-4e51-a795-8c85d2877e08.png)

Here is my docker-compose.yml:

```
localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sqs,lambda
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_REMOVE_CONTAINERS=true
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=/tmp/localstack/lambda
    volumes:
      - /tmp/localstack/lambda:/tmp/localstack
      - localstack_data:/tmp/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4566:4566
```

I'm new to LocalStack, so I appreciate the help :)

**Comment by Jyazzie69** [comment]
Buy

**Comment by IBRAHIMU1** [comment]
version: '3.3'
services:
  localstack:
    image: localstack/localstack:0.12.15
    
    ports:
      - "53:53"
      - "443:443"
      - "4566-4583:4566-4583"
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - DEFAULT_REGION=eu-west-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER= E:/Sources/container_Lambda/storage_localstack
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOVE_CONTAINERS=true
      - LAMBDA_REMOTE_DOCKER=false
      - SERVICES=lambda,s3,iam,cloudwatch,dynamodb
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "E:/Sources/container_Lambda/storage_localstack/TMP:/tmp/localstack"
    networks:
      - localstacknet
    
    privileged: true
  test-lambda:
    image: test-lambda:latest
    build:
      context: ./
    networks:
      - localstacknet
  
networks:
  localstacknet:
    external: false
    driver : bridge
    name: localstacknet

**Comment by vrbrito** [comment]
@FPRM Changed my docker-compose according to yours including **privileged: true** and **LAMBDA_EXECUTOR=docker** and started having the exact same problem as yours, 

`{"errorType":"Runtime.ImportModuleError","errorMessage":"Unable to import module 'handler': No module named 'handler'"}`

I appreciate it a lot if you can provide your updated docker-compose.yml and py script;

**Comment by FPRM** [comment]
Hi.
For the workaround.

First create à docker network

`docker network create -d bridge localstacknet`

Then according to the Docker-compose.yml with the props 

```
version: '3.3'
services:
  localstack:
    image: localstack/localstack:0.12.15
    
    ports:
      - "53:53"
      - "443:443"
      - "4566-4583:4566-4583"
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
      - HOST_TMP_FOLDER= E:/Sources/container_Lambda/storage_localstack
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOVE_CONTAINERS=true
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_DOCKER_NETWORK= localstacknet
      - SERVICES=lambda,s3,iam,cloudwatch,dynamodb
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "E:/Sources/container_Lambda/storage_localstack/TMP:/tmp/localstack"
    networks:
      - localstacknet
    
    privileged: true

  
networks:
  localstacknet:
    external: true
    driver : bridge
    name: localstacknet

```

start the stack with
`docker compose up`

create your function from image with boto3

```
lambda_client = boto3.client('lambda',region_name="us-west-1",endpoint_url='https://localhost:4566',verify=False)
response_lambda_create = lambda_client.create_function(
                                        FunctionName="testlambda2",                                 
                                        Publish=True,
                                        Handler='app.handler',
                                        Role= "arn:aws:iam::000000000:role/lambda-ex",
                                        Code={
                                            'ImageUri':'testlambda:latest',
                                            },
                                        Description="test2" ,
                                        PackageType='Image',
                                        Runtime='python3.7'
                                    )
```

and try to invoke it

```
response_invoke = lambda_client.invoke(
    FunctionName='arn:aws:lambda:us-east-1:000000000000:function:testlambda2',
    InvocationType='RequestResponse',
    Payload=json.dumps({"address": "Passeig del Born, 5, 08003 Barcelona, Espagne"}).encode()
)
```

I didn't have the unknown app.handler error anymore but a new one.

localstack_1  | 2021-08-16T12:25:45:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:testlambda2: expected string or bytes-like object Traceback (most recent call last):

**Comment by FPRM** [comment]
@Jyazzie69. Sorry I didn't get your comment. Does it mean we should buy something instead of understand what's going on ?
