### ISSUE TITLE
bug: NotImplementedError when creating auth and pushing using ampllifylocal

### ISSUE THREAD

**Issue by sikandarali94** [localstack/localstack#4440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I executed these commands in order:

`amplifylocal add auth` [executes successfully]

`amplifylocal push` [errors]

TraceStack
```
2021-08-13T11:25:27:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected error retrieving details for resource type Cognito::IdentityPool: Exception: An error occurred (500) when calling the ListIdentityPools operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
2021-08-13T11:25:28.098171000Z <title>500 Internal Server Error</title>
2021-08-13T11:25:28.098174700Z <h1>Internal Server Error</h1>
2021-08-13T11:25:28.098178100Z <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
2021-08-13T11:25:28.098183300Z  - {'Type': 'AWS::Cognito::IdentityPool', 'Properties': {'IdentityPoolName': 'nzf5d6b0321_identitypool_5d6b0321__dev', 'CognitoIdentityProviders': [{'ClientId': {'Ref': 'UserPoolClient'}, 'ProviderName': {'Fn::Sub': ['cognito-idp.${region}.amazonaws.com/${client}', {'region': {'Ref': 'AWS::Region'}, 'client': {'Ref': 'UserPool'}}]}}, {'ClientId': {'Ref': 'UserPoolClientWeb'}, 'ProviderName': {'Fn::Sub': ['cognito-idp.${region}.amazonaws.com/${client}', {'region': {'Ref': 'AWS::Region'}, 'client': {'Ref': 'UserPool'}}]}}], 'AllowUnauthenticatedIdentities': {'Ref': 'allowUnauthenticatedIdentities'}}, 'DependsOn': 'UserPoolClientInputs', 'LogicalResourceId': 'IdentityPool', 'PhysicalResourceId': None} - status: {}
2021-08-13T11:25:28.098216300Z 2021-08-13T11:25:27:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['IdentityPool', 'Name']}} - Unable to fetch details for resource "IdentityPool" (resolving attribute "Name")
2021-08-13T11:25:28.098227300Z 2021-08-13 11:25:27,614:API: Error on request:
2021-08-13T11:25:28.098236400Z Traceback (most recent call last):
2021-08-13T11:25:28.098239900Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
2021-08-13T11:25:28.098243500Z     execute(self.server.app)
2021-08-13T11:25:28.098246700Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute
2021-08-13T11:25:28.098270500Z     application_iter = app(environ, start_response)
2021-08-13T11:25:28.098279600Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 181, in __call__
2021-08-13T11:25:28.098285700Z     return backend_app(environ, start_response)
2021-08-13T11:25:28.098291000Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
2021-08-13T11:25:28.098296200Z     return self.wsgi_app(environ, start_response)
2021-08-13T11:25:28.098301000Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
2021-08-13T11:25:28.098308900Z     response = self.handle_exception(e)
2021-08-13T11:25:28.098319500Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
2021-08-13T11:25:28.098323300Z     return cors_after_request(app.make_response(f(*args, **kwargs)))
2021-08-13T11:25:28.098326900Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
2021-08-13T11:25:28.098330600Z     return cors_after_request(app.make_response(f(*args, **kwargs)))
2021-08-13T11:25:28.098333900Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
2021-08-13T11:25:28.098337400Z     response = self.full_dispatch_request()
2021-08-13T11:25:28.098340500Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
2021-08-13T11:25:28.098343900Z     rv = self.handle_user_exception(e)
2021-08-13T11:25:28.098348500Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
2021-08-13T11:25:28.098355900Z     return cors_after_request(app.make_response(f(*args, **kwargs)))
2021-08-13T11:25:28.098365900Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
2021-08-13T11:25:28.098371300Z     return cors_after_request(app.make_response(f(*args, **kwargs)))
2021-08-13T11:25:28.098376500Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
2021-08-13T11:25:28.098382000Z     rv = self.dispatch_request()
2021-08-13T11:25:28.098386900Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
2021-08-13T11:25:28.098392300Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2021-08-13T11:25:28.098408800Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 148, in __call__
2021-08-13T11:25:28.098418100Z     result = self.callback(request, request.url, {})
2021-08-13T11:25:28.098429100Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 205, in dispatch
2021-08-13T11:25:28.098435300Z     return cls()._dispatch(*args, **kwargs)
2021-08-13T11:25:28.098447000Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 315, in _dispatch
2021-08-13T11:25:28.098456300Z     return self.call_action()
2021-08-13T11:25:28.098464400Z   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 420, in call_action
2021-08-13T11:25:28.098469900Z     "The {0} action has not been implemented".format(action)
2021-08-13T11:25:28.098474800Z NotImplementedError: The list_identity_pools action has not been implemented
2021-08-13T11:25:28.098479700Z 2021-08-13T11:25:27:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
2021-08-13T11:25:28.098485000Z 2021-08-13T11:25:27:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
2021-08-13T11:25:28.098490500Z 2021-08-13T11:25:27:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Ref': 'UserPool'}, 'Description': 'Id for the user pool'} - list indices must be integers or slices, not str
2021-08-13T11:25:28.098496000Z 2021-08-13T11:25:27:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
2021-08-13T11:25:28.098501400Z 2021-08-13T11:25:27:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
2021-08-13T11:25:28.098508100Z 2021-08-13T11:25:27:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['UserPool', 'Arn']}, 'Description': 'Arn for the user pool'} - list indices must be integers or slices, not str
2021-08-13T11:25:28.098513200Z 2021-08-13T11:25:27:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
2021-08-13T11:25:28.098517400Z 2021-08-13T11:25:27:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
2021-08-13T11:25:28.098522000Z 2021-08-13T11:25:28:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Ref': 'UserPoolClientWeb'}, 'Description': 'The user pool app client id for web'} - list indices must be integers or slices, not str
2021-08-13T11:25:29.098628800Z 2021-08-13T11:25:28:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
2021-08-13T11:25:29.098709200Z 2021-08-13T11:25:28:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
2021-08-13T11:25:29.098721000Z 2021-08-13T11:25:28:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Ref': 'UserPoolClient'}, 'Description': 'The user pool app client id'} - list indices must be integers or slices, not str
2021-08-13T11:25:29.098725100Z 2021-08-13T11:25:28:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['UserPoolClientInputs', 'appSecret']}, 'Condition': 'ShouldOutputAppClientSecrets'} - Unable to fetch details for resource "UserPoolClientInputs" (resolving attribute "appSecret")
```

### Expected Behavior

I expect the auth resources for amplify to be created successfully rather than giving a NotImplementedError.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    I am starting localstack via docker-compose using the latest image

```
version: '2.1'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4510-4530:4510-4530"
      - "127.0.0.1:4566-4620:4566-4620"
    environment:
      - DEFAULT_REGION=ap-southeast-2
      - LOCALSTACK_API_KEY={hidden}
      - SERVICES=amplify,cloudformation,iam,s3,lambda,apigateway,cognito-identity,appsync
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    `amplifylocal add auth` [executes successfully]

    `amplifylocal push` [errors]

### Environment

```markdown
- OS: Windows 10
- LocalStack: latest [DIGEST:sha256:7ea1e076b6ea84e03f833e6e437c7818b1cce857afdb7785c2900c97faef9cb]
```

**Comment by Blockhead85** [comment]
I have no ideal what I'm doing

**Comment by Blockhead85** [comment]
I really need help

**Comment by whummer** [comment]
Thanks for reporting @sikandarali94 , and apologies for the long delay on this one. In the meantime, we have pushed a number of enhancements for the Amplify and Cognito APIs (in particular, `ListIdentityPools` and related APIs are now implemented). Were you able to get things working with the `latest` Docker image? Please keep us posted how it goes - we'll be happy to provide more help and guidance, in case the problem still persists.. Thanks for your help!

(@Blockhead85 - please note that Amplify and Cognito are services that are only available in the Pro version. If you have any questions we can help out with, please let us know.. Thanks!)
