### ISSUE TITLE
bug: API Gateway import of OpenAPI schema fails

### ISSUE THREAD

**Issue by mengelseatz** [localstack/localstack#4444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to import a REST API using aws CLI in OpenAPI 3 format. 

### Expected Behavior

Running  `awslocal apigateway import-rest-api`, should create an  REST API in the API Gateway service with all the proper resources created.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker compose up`
```
  localstack:
    privileged: true
    image: localstack/localstack:latest
    ports:
    - 4566:4566
    environment:
    - SERVICES=sqs,sns,s3,cloudformation,dynamodb,iam,apigateway,lambda,cloudwatch,events
    - HOST_TMP_FOLDER=/tmp
    - HOSTNAME=localstack
    - DOCKER_HOST=unix:///var/run/docker.sock
    - LAMBDA_EXECUTOR=docker-reuse
    - DEBUG=0
    volumes:
    - "./cloudformation:/root/cloudformation"
    - "./public/openapi/v1:/root/schema"
    - "./localstack:/docker-entrypoint-initaws.d"
    - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
I shell into the localstack container with docker exec

and run 
`awslocal apigateway import-rest-api --body 'file:///root/schema/openapi.yaml'`

The localstack container spits out
```
localstack_1    | 2021-08-13T21:19:21:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/restapis?mode=import&failonwarnings=true: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):
localstack_1    |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 129, in index
localstack_1    |     result = await run_sync(handler, request, data)
localstack_1    |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 85, in run_sync
localstack_1    |     return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
localstack_1    |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 790, in run
localstack_1    |     result = self.func(self.params, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 30, in _run
localstack_1    |     return fn(*args, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 525, in handler
localstack_1    |     server_address=parsed_url.netloc,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 157, in forward_request
localstack_1    |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 185, in do_forward_request
localstack_1    |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 217, in do_forward_request_inmem
localstack_1    |     server_address=server_address,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 81, in forward_request
localstack_1    |     data = data and json.loads(to_str(data))
localstack_1    |   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
localstack_1    |     return _default_decoder.decode(s)
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
localstack_1    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
localstack_1    |     raise JSONDecodeError("Expecting value", s, err.value) from None
localstack_1    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
localstack_1    | 
localstack_1    | 2021-08-13T21:19:21:INFO:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fd43863b830>(None) failed: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):
localstack_1    |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 790, in run
localstack_1    |     result = self.func(self.params, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 30, in _run
localstack_1    |     return fn(*args, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 525, in handler
localstack_1    |     server_address=parsed_url.netloc,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 157, in forward_request
localstack_1    |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 185, in do_forward_request
localstack_1    |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 217, in do_forward_request_inmem
localstack_1    |     server_address=server_address,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 81, in forward_request
localstack_1    |     data = data and json.loads(to_str(data))
localstack_1    |   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
localstack_1    |     return _default_decoder.decode(s)
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
localstack_1    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
localstack_1    |     raise JSONDecodeError("Expecting value", s, err.value) from None
localstack_1    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
localstack_1    | 
localstack_1    | 2021-08-13T21:19:22:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/restapis?mode=import&failonwarnings=true: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):
localstack_1    |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 129, in index
localstack_1    |     result = await run_sync(handler, request, data)
localstack_1    |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 85, in run_sync
localstack_1    |     return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
localstack_1    |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 790, in run
localstack_1    |     result = self.func(self.params, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 30, in _run
localstack_1    |     return fn(*args, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 525, in handler
localstack_1    |     server_address=parsed_url.netloc,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 157, in forward_request
localstack_1    |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 185, in do_forward_request
localstack_1    |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 217, in do_forward_request_inmem
localstack_1    |     server_address=server_address,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 81, in forward_request
localstack_1    |     data = data and json.loads(to_str(data))
localstack_1    |   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
localstack_1    |     return _default_decoder.decode(s)
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
localstack_1    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
localstack_1    |     raise JSONDecodeError("Expecting value", s, err.value) from None
localstack_1    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
localstack_1    | 
localstack_1    | 2021-08-13T21:19:22:INFO:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fd43863bb00>(None) failed: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):
localstack_1    |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 790, in run
localstack_1    |     result = self.func(self.params, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 30, in _run
localstack_1    |     return fn(*args, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 525, in handler
localstack_1    |     server_address=parsed_url.netloc,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 157, in forward_request
localstack_1    |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 185, in do_forward_request
localstack_1    |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 217, in do_forward_request_inmem
localstack_1    |     server_address=server_address,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 81, in forward_request
localstack_1    |     data = data and json.loads(to_str(data))
localstack_1    |   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
localstack_1    |     return _default_decoder.decode(s)
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
localstack_1    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
localstack_1    |     raise JSONDecodeError("Expecting value", s, err.value) from None
localstack_1    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
localstack_1    | 
localstack_1    | 2021-08-13T21:19:23:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/restapis?mode=import&failonwarnings=true: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):
localstack_1    |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 129, in index
localstack_1    |     result = await run_sync(handler, request, data)
localstack_1    |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 85, in run_sync
localstack_1    |     return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
localstack_1    |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 790, in run
localstack_1    |     result = self.func(self.params, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 30, in _run
localstack_1    |     return fn(*args, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 525, in handler
localstack_1    |     server_address=parsed_url.netloc,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 157, in forward_request
localstack_1    |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 185, in do_forward_request
localstack_1    |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 217, in do_forward_request_inmem
localstack_1    |     server_address=server_address,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 81, in forward_request
localstack_1    |     data = data and json.loads(to_str(data))
localstack_1    |   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
localstack_1    |     return _default_decoder.decode(s)
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
localstack_1    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
localstack_1    |     raise JSONDecodeError("Expecting value", s, err.value) from None
localstack_1    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
localstack_1    | 
localstack_1    | 2021-08-13T21:19:23:INFO:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fd43863b950>(None) failed: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):
localstack_1    |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 790, in run
localstack_1    |     result = self.func(self.params, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 30, in _run
localstack_1    |     return fn(*args, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 525, in handler
localstack_1    |     server_address=parsed_url.netloc,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 157, in forward_request
localstack_1    |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 185, in do_forward_request
localstack_1    |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 217, in do_forward_request_inmem
localstack_1    |     server_address=server_address,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 81, in forward_request
localstack_1    |     data = data and json.loads(to_str(data))
localstack_1    |   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
localstack_1    |     return _default_decoder.decode(s)
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
localstack_1    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
localstack_1    |     raise JSONDecodeError("Expecting value", s, err.value) from None
localstack_1    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
localstack_1    | 
localstack_1    | 2021-08-13T21:19:24:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/restapis?mode=import&failonwarnings=true: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):
localstack_1    |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 129, in index
localstack_1    |     result = await run_sync(handler, request, data)
localstack_1    |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 85, in run_sync
localstack_1    |     return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
localstack_1    |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 790, in run
localstack_1    |     result = self.func(self.params, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 30, in _run
localstack_1    |     return fn(*args, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 525, in handler
localstack_1    |     server_address=parsed_url.netloc,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 157, in forward_request
localstack_1    |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 185, in do_forward_request
localstack_1    |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 217, in do_forward_request_inmem
localstack_1    |     server_address=server_address,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 81, in forward_request
localstack_1    |     data = data and json.loads(to_str(data))
localstack_1    |   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
localstack_1    |     return _default_decoder.decode(s)
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
localstack_1    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
localstack_1    |     raise JSONDecodeError("Expecting value", s, err.value) from None
localstack_1    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
localstack_1    | 
localstack_1    | 2021-08-13T21:19:24:INFO:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fd43863b290>(None) failed: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):
localstack_1    |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 790, in run
localstack_1    |     result = self.func(self.params, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 30, in _run
localstack_1    |     return fn(*args, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 525, in handler
localstack_1    |     server_address=parsed_url.netloc,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 157, in forward_request
localstack_1    |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 185, in do_forward_request
localstack_1    |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 217, in do_forward_request_inmem
localstack_1    |     server_address=server_address,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 81, in forward_request
localstack_1    |     data = data and json.loads(to_str(data))
localstack_1    |   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
localstack_1    |     return _default_decoder.decode(s)
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
localstack_1    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
localstack_1    |     raise JSONDecodeError("Expecting value", s, err.value) from None
localstack_1    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
localstack_1    | 
localstack_1    | 2021-08-13T21:19:29:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/restapis?mode=import&failonwarnings=true: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):
localstack_1    |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 129, in index
localstack_1    |     result = await run_sync(handler, request, data)
localstack_1    |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 85, in run_sync
localstack_1    |     return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
localstack_1    |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 790, in run
localstack_1    |     result = self.func(self.params, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 30, in _run
localstack_1    |     return fn(*args, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 525, in handler
localstack_1    |     server_address=parsed_url.netloc,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 157, in forward_request
localstack_1    |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 185, in do_forward_request
localstack_1    |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 217, in do_forward_request_inmem
localstack_1    |     server_address=server_address,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 81, in forward_request
localstack_1    |     data = data and json.loads(to_str(data))
localstack_1    |   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
localstack_1    |     return _default_decoder.decode(s)
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
localstack_1    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
localstack_1    |     raise JSONDecodeError("Expecting value", s, err.value) from None
localstack_1    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
localstack_1    | 
localstack_1    | 2021-08-13T21:19:29:INFO:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fd43a07f950>(None) failed: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):
localstack_1    |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 790, in run
localstack_1    |     result = self.func(self.params, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 30, in _run
localstack_1    |     return fn(*args, **kwargs)
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 525, in handler
localstack_1    |     server_address=parsed_url.netloc,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 157, in forward_request
localstack_1    |     return do_forward_request(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 185, in do_forward_request
localstack_1    |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_1    |   File "/opt/code/localstack/localstack/services/edge.py", line 217, in do_forward_request_inmem
localstack_1    |     server_address=server_address,
localstack_1    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 310, in modify_and_forward
localstack_1    |     method=method, path=path, data=data, headers=headers
localstack_1    |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 81, in forward_request
localstack_1    |     data = data and json.loads(to_str(data))
localstack_1    |   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
localstack_1    |     return _default_decoder.decode(s)
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
localstack_1    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
localstack_1    |   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
localstack_1    |     raise JSONDecodeError("Expecting value", s, err.value) from None
localstack_1    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
localstack_1    | 



```

### Environment

```markdown
- OS: Mac OS 10.15.7
- LocalStack: latest
```

### Anything else?

I tried using a JSON version of the OpenAPI yaml file as well and got no output in the container logs but the awslocal command prints out

```
~/schema # awslocal apigateway import-rest-api --fail-on-warnings --body 'file:///root/schema/openapi.json'

An error occurred (500) when calling the ImportRestApi operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

```

At first I assumed this was a problem with my Schema so I went over to swaggerhub.io and grabbed the simplest API doc I could find and also tested that in the AWS Console I was able to import this same YAML listed below without errors.

```
openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /list:
    get:
      description: Returns a list of stuff              
      responses:
        '200':
          description: Successful response
```

**Comment by danw-mpl** [comment]
Try converting your spec to JSON.  We used yamljs to do it in a script:

```
npm install yamljs -g
yaml2json /path/to/template.yml -p -i4 > "/tmp/ConvertedOpenAPITemplate.json"
```

However, you may hit another issue I'm having where the Rest API ID isn't recognised: https://github.com/localstack/localstack/issues/4619

**Comment by mengelseatz** [comment]
Converting to JSON doesn't work either.. and i see this just got tagged "available-in-pro"

**Comment by calvernaz** [comment]
Hi @mengelseatz thanks for reporting this. I will suggest to try with the `latest` version because this feature as moved to the community version 👍 

I've an example of the well-known PetStore and the instructions in the comments ready to go https://gist.github.com/calvernaz/737625957a947b1e1fb460f4015a8059

Please give it a try and tell me if it's working for you!
