### ISSUE TITLE
If ServiceURL is using HTTPS: call to AmazonS3Util.DoesS3BucketExistV2Async comes back with MethodNotAllowed error

### ISSUE THREAD

**Issue by aiampogi** [localstack/localstack#4468]
My previous issue #4375 was prematurely closed. The reason was that it wasn't reproducible. A significant detail was missed. I was using **HTTPS** because I need to use server-side encryption using KMS keys. Using plain HTTP won't work because HTTPS is required when using KMS. See [this](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingKMSEncryption.html#aws-signature-version-4-sse-kms) from AWS.

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I'm using **HTTPS** (https://localhost:4566) Then, when calling the C# SDK AmazonS3Util.DoesS3BucketExistV2Async, it returns a MethodNotAllowed error.

Stacktrace looks like this:
```
Amazon.S3.AmazonS3Exception: Error making request with Error Code MethodNotAllowed and Http Status Code MethodNotAllowed. No further error information was returned by the service.
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Util.AmazonS3Util.DoesS3BucketExistV2Async(IAmazonS3 s3Client, String bucketName)
```

### Expected Behavior

It should just return bucket not found error if the bucket is not existing. Or should just succeed.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    Use C# SDK AmazonS3Util.DoesS3BucketExistV2Async and use any string as bucket. Make sure to use **HTTPS**.

### Environment

```markdown
- OS: Windows 10
- LocalStack: latest
```
DockerHub link: [https://hub.docker.com/layers/localstack/localstack/latest/images/sha256-f6a93d243a427af2e99bf9f283843497081659a50f9f7955bd4ce4aded874347?context=explore](https://hub.docker.com/layers/localstack/localstack/latest/images/sha256-f6a93d243a427af2e99bf9f283843497081659a50f9f7955bd4ce4aded874347?context=explore)

**Comment by pinzon** [comment]
Duplicated of #4375
