### ISSUE TITLE
bug: Java 11 Lambda incorrect handler specification

### ISSUE THREAD

**Issue by ilgrosso** [localstack/localstack#4512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Up to localstack 0.12.15 (I haven't checked with 0.12.16), Java 11 Lambda function handler was correctly specified according to [AWS docs](https://docs.aws.amazon.com/lambda/latest/dg/lambda-java.html) e.g.

```
example.Hello::handleRequest
```

With 0.12.17, instead, such specification leads to error during Lambda execution, with stacktrace:

```
2021-08-30T14:08:01:INFO:localstack.utils.run: Thread run method <function LambdaExecutor.execute.<locals>.do_execute at 0x7fc385d26560>(None) failed: Lambda process returned error status code: 1. Result: . Output:
Exception in thread "main" java.lang.ClassNotFoundException: example.Hello::handleRequest
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at cloud.localstack.LambdaExecutor.getHandler(LambdaExecutor.java:142)
        at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:69) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/run.py", line 138, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 326, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 157, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 153, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 313, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 299, in _run
    result = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1101, in _execute
    raise InvocationException(result, log_output)
localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned error status code: 1. Result: . Output:
Exception in thread "main" java.lang.ClassNotFoundException: example.Hello::handleRequest
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at cloud.localstack.LambdaExecutor.getHandler(LambdaExecutor.java:142)
        at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:69)
```

I would say that this line in the test case is incorrect: https://github.com/localstack/localstack/blob/master/tests/integration/test_lambda.py#L1711

### Expected Behavior

I would expect to specify Java 11 Lambda handlers as it used to be at least until localstack 0.12.15 and according to AWS docs.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.12.17
```

**Comment by silv-io** [comment]
Thanks for reporting @ilgrosso! Can you please share a few more details about your docker-compose setup (especially your lambda executor mode settings i.e. LAMBDA_EXECUTOR). Then we can look into it.

**Comment by ilgrosso** [comment]
hi @silv-io my `LAMBDA_EXECUTOR` is `local`.

**Comment by silv-io** [comment]
Hi @ilgrosso, we're working on better support for the `local` executor mode. In the meantime you can try using one of the Docker-based modes which already have more extensive support. If you still have problems with that, feel free to report back. Thank you!

**Comment by dfangl** [comment]
Hi @dbes-gds @ilgrosso !
With the recent changes, this behavior should be fixed. Can you pull from :latest and check if the issue is now fixed for you? Thanks for the wait!

**Comment by ilgrosso** [comment]
Hi @dfangl it works like a charm now, thanks!
Looking forward to next release.

**Comment by dbes-gds** [comment]
It's working now, thanks for fixing :)
