### ISSUE TITLE
bug: Lambada not triggered by SQS event

### ISSUE THREAD

**Issue by renato04** [localstack/localstack#4513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The localstack container can't create a container to run the lambda function.
I start the localstack using docker-compose.

### Expected Behavior

The lambda function run with success.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I'm starting the `localstack` with this `docker-compose`
```docker
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

I'm creating an SQS with this command
`aws --endpoint http://localhost:4566 sqs create-queue --queue-name TEST_QUEUE`

Here it is my python code (`handler.py`)
```python
import json
import logging
import os

logger = logging.getLogger()
logger.setLevel(logging.INFO)

def handler(event, context):
    try:
        logger.info(f"### ENV VARS {os.environ}")
        logger.info(f"### EVENT {event}")
        logger.info(f"### ENV VARS {context}")

        if event and "Records" in event:
            for elt in event["Records"]:
                logger.info(elt["body"])
        
        return True
    except Exception as e:
        logger.error(e)
        raise e

```

I'm building a image with this `Dockerfile`

```Dockerfile
FROM public.ecr.aws/lambda/python:3.9

RUN python -m pip install --upgrade pip

COPY requirements.txt ${LAMBDA_TASK_ROOT}
RUN pip install -r ${LAMBDA_TASK_ROOT}/requirements.txt --quiet

COPY src/ ${LAMBDA_TASK_ROOT}

CMD ["handler.handler"]

```

To create the lambda in the localstack I'm using this command:
`aws --endpoint http://localhost:4566 lambda create-function --timeout 120 --function-name python-lambda-test --handler handler.handler --code ImageUri=python-lambda-test:latest --role arn:aws:iam::000000000:role/lambda-ex`

To create the event source the following command
`aws --endpoint http://localhost:4566 lambda create-event-source-mapping --function-name python-lambda-test --batch-size 1 --event-source-arn arn:aws:sqs:sa-east-1:000000000000:TEST_QUEUE`

And finally, this command to send the message to the queue
`aws --endpoint http://localhost:4566 sqs send-message --queue-url  http://localhost:4566/000000000000/TEST_QUEUE --message-body 'this is a message'`

I'm receiving this logs with the error

```
2021-08-30 18:30:23,439:API: 127.0.0.1 - - [30/Aug/2021 18:30:23] "POST / HTTP/1.1" 200 -

2021-08-30T18:30:23:DEBUG:localstack.services.awslambda.lambda_api: Found 1 source mappings for event from SQS queue arn:aws:sqs:sa-east-1:000000000000:TEST_QUEUE: ['arn:aws:lambda:sa-east-1:000000000000:function:python-lambda-test']

2021-08-30T18:30:23:DEBUG:localstack.services.awslambda.lambda_api: Starting SQS message polling thread for Lambda API

2021-08-30 18:30:23,467:API: 127.0.0.1 - - [30/Aug/2021 18:30:23] "POST / HTTP/1.1" 200 -

2021-08-30 18:30:23,520:API: 127.0.0.1 - - [30/Aug/2021 18:30:23] "POST / HTTP/1.1" 200 -

2021-08-30T18:30:23:DEBUG:localstack.services.awslambda.lambda_api: Sending event from event source arn:aws:sqs:sa-east-1:000000000000:TEST_QUEUE to Lambda arn:aws:lambda:sa-east-1:000000000000:function:python-lambda-test

2021-08-30T18:30:23:DEBUG:localstack.services.awslambda.lambda_executors: Lambda executed in Event (asynchronous) mode, no response will be returned to caller

2021-08-30T18:30:23:INFO:localstack.services.awslambda.lambda_executors: Determined main container target IP: 172.17.0.2

2021-08-30T18:30:23:INFO:localstack.services.awslambda.lambda_executors: Running lambda: arn:aws:lambda:sa-east-1:000000000000:function:python-lambda-test

2021-08-30T18:30:23:DEBUG:localstack.utils.docker: Running container with image: lambci/lambda:

2021-08-30T18:30:23:DEBUG:localstack.utils.docker: Creating container with image: lambci/lambda:

2021-08-30T18:30:23:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:sa-east-1:000000000000:function:python-lambda-test result / log output:


>

2021-08-30 18:30:23,635:API: 127.0.0.1 - - [30/Aug/2021 18:30:23] "POST / HTTP/1.1" 200 -

2021-08-30 18:30:23,658:API: 127.0.0.1 - - [30/Aug/2021 18:30:23] "POST / HTTP/1.1" 200 -

2021-08-30 18:30:23,677:API: 127.0.0.1 - - [30/Aug/2021 18:30:23] "POST / HTTP/1.1" 200 -

2021-08-30 18:30:23,701:API: 127.0.0.1 - - [30/Aug/2021 18:30:23] "POST / HTTP/1.1" 200 -

2021-08-30 18:30:23,734:API: 127.0.0.1 - - [30/Aug/2021 18:30:23] "POST / HTTP/1.1" 200 -

2021-08-30 18:30:23,754:API: 127.0.0.1 - - [30/Aug/2021 18:30:23] "POST / HTTP/1.1" 200 -

2021-08-30T18:30:23:INFO:localstack.utils.run: Thread run method <function LambdaExecutor.execute.<locals>.do_execute at 0x7f69de3770e0>(None) failed: Lambda process returned with error. Result: . Output:

Traceback (most recent call last):

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/docker/api/client.py", line 268, in _raise_for_status

response.raise_for_status()

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status

raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/create


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

File "/opt/code/localstack/localstack/utils/docker.py", line 1230, in create_container

container = create_container()

File "/opt/code/localstack/localstack/utils/docker.py", line 1226, in create_container

**kwargs,

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/docker/models/containers.py", line 870, in create

resp = self.client.api.create_container(**create_kwargs)

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/docker/api/container.py", line 430, in create_container

return self.create_container_from_config(config, name)

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/docker/api/container.py", line 441, in create_container_from_config

return self._result(res, True)

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/docker/api/client.py", line 274, in _result

self._raise_for_status(response)

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/docker/api/client.py", line 270, in _raise_for_status

raise create_api_error_from_http_exception(e)

File "/opt/code/localstack/.venv/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception

raise cls(e, response=response, explanation=explanation)

docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/create: Bad Request ("invalid reference format")


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 336, in run_lambda_executor

func_details, env_vars, command, docker_flags=docker_flags, stdin=event_stdin_bytes

File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 815, in execute_in_container

stdin=stdin,

File "/opt/code/localstack/localstack/utils/docker.py", line 1280, in run_container

additional_flags=additional_flags,

File "/opt/code/localstack/localstack/utils/docker.py", line 1238, in create_container

raise ContainerException()

localstack.utils.docker.ContainerException



The above exception was the direct cause of the following exception:


Traceback (most recent call last):

File "/opt/code/localstack/localstack/utils/run.py", line 138, in run

result = self.func(self.params, **kwargs)

File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 247, in do_execute

return _run(func_arn=func_arn)

File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 157, in wrapped

raise e

File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 153, in wrapped

result = func(*args, **kwargs)

File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 234, in _run

raise e

File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 220, in _run

result = self._execute(func_arn, func_details, event, context, version)

File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 450, in _execute

event=stdin, env_vars=environment, func_details=func_details, docker_flags=docker_flags

File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 375, in run_lambda_executor

) from error

localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: . Output:
```

### Environment

```markdown
- OS: Windows 10 19043
- WSL 2: Ubuntu 20.04
- LocalStack: latest
- Docker: version 20.10.7, build f0df350
```

### Anything else?

If this is not a bug, I'm sorry.

**Comment by dfangl** [comment]
Hi @renato04 !
I sadly cannot reproduce your issue, but it seems like your custom lambda image is not executed correctly.
Please confirm you are using Localstack Pro, as only this version has support for lambda docker images.
Also, please check if your TMPDIR environment variable is set correctly, as this can make some problems when using Lambdas.

I tested your configuration on LocalStack Pro version: 0.12.17.5, on both Linux and Windows, with the commands you provided.

**Comment by renato04** [comment]
@dfangl 
I don't have the pro version. I didn't know that.

Thank you!
