### ISSUE TITLE
bug: AWS::NoValue produces error when used in IAM policy template

### ISSUE THREAD

**Issue by jjsakuraiii** [localstack/localstack#4517]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When I try to create a role with S3 resource and I use `!Ref AWS::NoValue` for its resource, it fails with errors. It is supposed to be removed from array entry, but it looks like it evaluates as `__aws_no_value__`, which then fails to validate because the value is not in acceptable format for ARN.
(Message: `Resource __aws_no_value__ must be in ARN format or "*".`)

template file `test.template` :
```
AWSTemplateFormatVersion: 2010-09-09

Conditions:
  someCondition: false

Resources:
  SomeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SomeRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: SomePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource:
                  - arn:aws:s3:::some-prefix-*/*
                  - !If
                    - someCondition
                    - !Ref arn:aws:s3:::another-prefix-*/*
                    - !Ref AWS::NoValue
```
Executed command:
```
awslocal cloudformation deploy \
  --no-fail-on-empty-changeset \
  --capabilities CAPABILITY_NAMED_IAM \
  --template-file test.template \
  --stack-name "test-stack"
```
Error log produced:
```
2021-08-30T07:38:54:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "test-resources-iam": An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy operation: Resource __aws_no_value__ must be in ARN format or "*". Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2083, in _run
    self.do_apply_changes_in_loop(changes, stack, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2154, in do_apply_changes_in_loop
    self.apply_change(change, stack, new_resources, stack_name=stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 2218, in apply_change
    result = deploy_resource(resource_id, new_resources, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1037, in deploy_resource
    return execute_resource_action(resource_id, resources, stack_name, ACTION_CREATE)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1152, in execute_resource_action
    resource_id, resources, resource_type, func, stack_name, action_name
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1314, in configure_resource_via_sdk
    run_post_create_actions(action_name, resource_id, resources, resource_type, stack_name, result)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1414, in run_post_create_actions
    PolicyDocument=doc,
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.MalformedPolicyDocumentException: An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy operation: Resource __aws_no_value__ must be in ARN format or "*".
```

### Expected Behavior

Create stack without failing

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
FORCE_NONINTERACTIVE=1 \
SERVICES=iam,s3,lambda,cloudformation \
localstack infra start &
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal cloudformation deploy \
  --no-fail-on-empty-changeset \
  --capabilities CAPABILITY_NAMED_IAM \
  --template-file test.template \
  --stack-name "test-stack"
```

### Environment

```markdown
- OS:  Ubuntu 20.04
- LocalStack: latest
```

**Comment by thaifp** [comment]
Any update on this one? 
I got some issues when trying to deploy datadog forwarder to localstack, the template here: https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml
This template uses a lot of AWS::NoValue, for many resources, then it's failed when deploy to localstack in the end.

**Comment by dominikschubert** [comment]
@jjsakuraiii @thaifp The handling of `AWS::NoValue` has been improved in the meantime.

I could not reproduce the issue @jjsakuraiii  reported with the provided sample template. Please let us know if you're experiencing any other related issues!
