### ISSUE TITLE
NotImplementedError: Called get_bucket_versions with some of delimiter, encoding_type, key_marker, version_id_marker

### ISSUE THREAD

**Issue by linkyndy** [localstack/localstack#452]
My application is issuing S3 requests like:

```
127.0.0.1 - - [08/Nov/2017 13:45:44] "GET /bucket?versions&encoding-type=url HTTP/1.1" 500 -
```

Using debug mode, I get this error:

```
Error on request:
Traceback (most recent call last):
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
execute(self.server.app)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/werkzeug/serving.py", line 197, in execute
application_iter = app(environ, start_response)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/moto/server.py", line 93, in __call__
return backend_app(environ, start_response)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/moto/core/utils.py", line 137, in __call__
result = self.callback(request, request.url, {})
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/moto/s3/responses.py", line 106, in ambiguous_response
return self.bucket_response(request, full_url, headers)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/moto/s3/responses.py", line 110, in bucket_response
response = self._bucket_response(request, full_url, headers)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/moto/s3/responses.py", line 148, in _bucket_response
return self._bucket_response_get(bucket_name, querystring, headers)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/moto/s3/responses.py", line 250, in _bucket_response_get
prefix=prefix
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/moto/s3/models.py", line 517, in get_bucket_versions
"Called get_bucket_versions with some of delimiter, encoding_type, key_marker, version_id_marker")
NotImplementedError: Called get_bucket_versions with some of delimiter, encoding_type, key_marker, version_id_marker
```

What am I doing wrong? And how can I fix this issue?

**Comment by whummer** [comment]
Thanks for reporting @linkyndy . This is an upstream issue in `moto`, see [here](https://github.com/spulec/moto/blob/master/moto/s3/models.py#L515-L517). As a temporary workaround, you can probably change your client code not to use the `encoding-type` parameter.

Can you please raise a ticket with `moto` - once this feature is implemented there, we can integrate it into LocalStack. Thanks

**Comment by linkyndy** [comment]
The issue is that I cannot change the client code, as much of its functionality is based on it. Will open an issue upstream, hopefully it'll be addressed soon. Thanks!

**Comment by whummer** [comment]
This issue has been fixed in the meantime - an integration test has been added in this PR: #2201 Thanks
