### ISSUE TITLE
bug: S3 Select

### ISSUE THREAD

**Issue by gnwlyonme** [localstack/localstack#4551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Localstack starts successfully:
```
     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 LocalStack CLI 0.12.17.3

[12:52:19] starting LocalStack in host mode 💻                 localstack.py:101
──────────────── LocalStack Runtime Log (press CTRL-C to quit) ─────────────────
2021-09-07 12:52:20,579 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

LocalStack version: 0.12.17.3
LocalStack Docker container id: 5f7ec2db98b4
LocalStack build date: 2021-08-30
LocalStack build git hash: 7037c03a

2021-09-07T12:52:23:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7f95511ff830>
2021-09-07T12:52:23:DEBUG:localstack.utils.run: Executing command: which postgres
2021-09-07T12:52:23:DEBUG:localstack.utils.run: Executing command: which pg_config
2021-09-07T12:52:23:DEBUG:localstack.utils.run: Executing command: which redis-server
2021-09-07T12:52:23:DEBUG:localstack.utils.run: Executing command: which mosquitto
Waiting for all LocalStack services to be ready
Starting edge router (https port 4566)...
Starting mock CloudWatch service on http port 4566 ...
2021-09-07T12:52:24:INFO:botocore.credentials: Found credentials in environment variables.
2021-09-07T12:52:25:INFO:botocore.credentials: Found credentials in environment variables.
2021-09-07T12:52:25:INFO:localstack.multiserver: Starting multi API server process on port 33787
[2021-09-07 12:52:25 +0000] [21] [INFO] Running on http://0.0.0.0:33787 (CTRL + C to quit)
2021-09-07T12:52:25:INFO:hypercorn.error: Running on http://0.0.0.0:33787 (CTRL + C to quit)
[2021-09-07 12:52:25 +0000] [21] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-09-07T12:52:25:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-09-07 12:52:25,163:API:  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-09-07 12:52:25,166:API:  * Running on http://172.17.0.2:37883/ (Press CTRL+C to quit)
Starting mock IAM service on http port 4566 ...
Starting mock KMS service on http port 4566 ...
Starting mock Lambda service on http port 4566 ...
Starting mock CloudWatch Logs service on http port 4566 ...
Starting mock S3 service on http port 4566 ...
Starting mock SSM service on http port 4566 ...
2021-09-07 12:52:25,350:API:  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-09-07 12:52:25,351:API:  * Running on http://172.17.0.2:59387/ (Press CTRL+C to quit)
Ready.
```

But getting the following  error when testing S3 Select:

```
botocore.exceptions.ClientError: An error occurred (500) when calling the SelectObjectContent operation (reached max retries: 4): Internal Server Error
```

Localstack debug shows the following:

```
2021-09-07 12:33:55,221:API: 127.0.0.1 - - [07/Sep/2021 12:33:55] "POST /localstack-bucket/file.csv.gz?select&select-type=2 HTTP/1.1" 500 -
2021-09-07 12:33:55,230:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 268, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 148, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 282, in _wrapper
    response = f(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py", line 1033, in key_or_control_response
    response = self._key_response(request, full_url, self.headers)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py", line 1219, in _key_response
    return self._key_response_post(request, body, bucket_name, query, key_name)
  File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 166, in s3_key_response_post
    request, body, bucket_name, query, key_name, *args, **kwargs
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py", line 1908, in _key_response_post
    self._set_action("KEY", "POST", query)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py", line 561, in _set_action
    self.data["Action"] = ACTION_MAP[action_resource_type][method]["DEFAULT"]
KeyError: 'DEFAULT'
```

### Expected Behavior

Sample code should get the headers from the S3 file but instead getting errors.
When I switch from s3 localhost endpoint to use AWS account and same code works successfully and am able to query the same file, get the headers and run SQL against the file to generate a csv result.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
export SERVICES=lambda,s3,iam,cloudwatch
export LOCALSTACK_API_KEY=xxxxxxxxxxxx
export DEBUG=1
localstack start
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Make a local S3 bucket and copy file:
```
aws --profile localstack --endpoint-url=http://localhost:4566 s3 mb s3://localstack-bucket
aws --profile localstack --endpoint-url=http://localhost:4566 s3 cp file.csv.gz  s3://localstack-bucket/
```

File is uploaded successfully (  183 MB gzip and 1 GB unzipped ) .

Make the following call:

```python
bucket = 'localstack-bucket'
key = "file.csv.gz"

s = boto3.Session(profile_name="localstack", region_name="us-east-1")
s3 = s.client(service_name = 's3', endpoint_url='http://localhost:4566' )
bucket = 'localstack-bucket'
key = "file.csv.gz"

resp = s3.select_object_content(
        Bucket=bucket,
        Key=key,
        ExpressionType='SQL',
        Expression="SELECT * FROM s3object s limit 1",
        InputSerialization={
            'CSV': {"FileHeaderInfo": "NONE"}, 'CompressionType': 'GZIP'},
        OutputSerialization={'CSV': {}} )
```

And getting the above error.
Switch from s3 localhost end point to use AWS account and same code works successfully.

### Environment

```markdown
- OS: macOS Catalina 10.15.4
- LocalStack: 0.12.17.3
```

**Comment by whummer** [comment]
Thanks for reporting @gnwlyonme . Looks like there may potentially be an issue with your API key (would have expected to see a message like `Successfully activated API key` in the log output). Can you please get in touch with us directly by email or via the Slack channel? Thanks for your help!

**Comment by gnwlyonme** [comment]
@whummer , thanks for the tip, there was a space after the key in my startup sctipt.
The API Key is now showing as activated.
I'm getting [SSL: CERTIFICATE_VERIFY_FAILED]  errors on startup ( we're behind corporate proxy ) so I manually  downloaded the server.test.pem file and put it in /tmp/localstack.
However, I still am seeing the same errors as above.


     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.12.17.3

[09:21:30] starting LocalStack in Docker mode 🐳                                                                                                                                                                                        localstack.py:103
───────────────────────────────────────────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ─────────────────────────────────────────────────────────────────────────────────────────────────────
2021-09-10T09:21:30:DEBUG:localstack.utils.docker: Running container with image: localstack/localstack
2021-09-10T09:21:30:DEBUG:localstack.utils.docker: Creating container with image: localstack/localstack
2021-09-10T09:21:30:DEBUG:localstack.utils.docker: Starting container 3aea5280aa6618f8e20722215739b763ab39579b1ad71232326384752897b32f
2021-09-10T09:21:30:DEBUG:localstack.utils.docker: Removing container: 3aea5280aa6618f8e20722215739b763ab39579b1ad71232326384752897b32f
2021-09-10T09:21:30:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x10d0591e0>
2021-09-10T09:21:35:INFO:localstack_ext.bootstrap.licensing: **Successfully activated API key**
2021-09-10T09:21:35:DEBUG:localstack.utils.run: Executing command: ifconfig | grep 0.0.0.0
2021-09-10T09:21:36:DEBUG:localstack.utils.run: Executing command: ['chmod', '-R', '777', '/private/var/folders/fg/65172mmd7bg22q4_2t3ym7hh680_x0/T/localstack']
['docker', 'run', '-it', '-e', 'DEFAULT_REGION=us-east-1', '-e', 'LOCALSTACK_API_KEY=XXXXXXXXXX', '-e', 'SERVICES=kms,ssm,lambda,s3,iam,cloudwatch', '-e', 'DEBUG=1', '-e', 'LOCALSTACK_HOSTNAME=localhost', '-e', 'TEST_AWS_ACCOUNT_ID=000000000000', '-e', 'DATA_DIR=/tmp/localstack_data', '-e', 'DOCKER_HOST=unix:///var/run/docker.sock', '-e', 'HOST_TMP_FOLDER=/private/var/folders/fg/65172mmd7bg22q4_2t3ym7hh680_x0/T/localstack', '-p', '0.0.0.0:53:53', '-p', '0.0.0.0:53:53/udp', '--rm', '--privileged', '--name', 'localstack_main', '-p', '127.0.0.1:4566:4566', '-v', '/tmp/localstack/data:/tmp/localstack_data', '-v', '/private/var/folders/fg/65172mmd7bg22q4_2t3ym7hh680_x0/T/localstack:/tmp/localstack', '-v', '/var/run/docker.sock:/var/run/docker.sock', 'localstack/localstack']
2021-09-10T09:21:36:DEBUG:localstack.utils.run: Executing command: ['docker', 'run', '-it', '-e', 'DEFAULT_REGION=us-east-1', '-e', 'LOCALSTACK_API_KEY=XXXXXXXXXX', '-e', 'SERVICES=kms,ssm,lambda,s3,iam,cloudwatch', '-e', 'DEBUG=1', '-e', 'LOCALSTACK_HOSTNAME=localhost', '-e', 'TEST_AWS_ACCOUNT_ID=000000000000', '-e', 'DATA_DIR=/tmp/localstack_data', '-e', 'DOCKER_HOST=unix:///var/run/docker.sock', '-e', 'HOST_TMP_FOLDER=/private/var/folders/fg/65172mmd7bg22q4_2t3ym7hh680_x0/T/localstack', '-p', '0.0.0.0:53:53', '-p', '0.0.0.0:53:53/udp', '--rm', '--privileged', '--name', 'localstack_main', '-p', '127.0.0.1:4566:4566', '-v', '/tmp/localstack/data:/tmp/localstack_data', '-v', '/private/var/folders/fg/65172mmd7bg22q4_2t3ym7hh680_x0/T/localstack:/tmp/localstack', '-v', '/var/run/docker.sock:/var/run/docker.sock', 'localstack/localstack']
Waiting for all LocalStack services to be ready
2021-09-10 13:21:37,555 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-09-10 13:21:37,557 INFO supervisord started with pid 14
2021-09-10 13:21:38,559 INFO spawned: 'infra' with pid 20
(. .venv/bin/activate; exec bin/localstack start --host)

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.12.17.3

[13:21:39] starting LocalStack in host mode 💻                 localstack.py:101
──────────────── LocalStack Runtime Log (press CTRL-C to quit) ─────────────────
2021-09-10 13:21:40,131 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

LocalStack version: 0.12.17.3
LocalStack Docker container id: 2294c09895e9
LocalStack build date: 2021-08-30
LocalStack build git hash: 7037c03a

2021-09-10T13:21:42:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7fabb11437a0>
2021-09-10T13:21:42:DEBUG:localstack.utils.run: Executing command: which postgres
2021-09-10T13:21:42:DEBUG:localstack.utils.run: Executing command: which pg_config
2021-09-10T13:21:42:DEBUG:localstack.utils.run: Executing command: which redis-server
2021-09-10T13:21:42:DEBUG:localstack.utils.run: Executing command: which mosquitto
2021-09-10T13:21:43:INFO:localstack_ext.bootstrap.install: Unable to download local test SSL certificate from https://cdn.jsdelivr.net/gh/localstack/localstack-artifacts@master/local-certs/server.key to /tmp/localstack/server.test.pem: MyHTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/localstack/localstack-artifacts@master/local-certs/server.key (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)'))) Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: MyHTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/localstack/localstack-artifacts@master/local-certs/server.key (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/bootstrap/install.py", line 87, in do_download
    download(url,target_file)
  File "/opt/code/localstack/localstack/utils/common.py", line 967, in download
    r = s.get(url, stream=True, verify=os.getenv("REQUESTS_CA_BUNDLE", verify_ssl))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: MyHTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/localstack/localstack-artifacts@master/local-certs/server.key (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

Waiting for all LocalStack services to be ready
Starting edge router (https port 4566)...
Starting mock CloudWatch service on http port 4566 ...
Starting mock IAM service on http port 4566 ...
Starting mock KMS service on http port 4566 ...
Starting mock Lambda service on http port 4566 ...
Starting mock CloudWatch Logs service on http port 4566 ...
Starting mock S3 service on http port 4566 ...
Starting mock SSM service on http port 4566 ...
2021-09-10T13:21:44:INFO:botocore.credentials: Found credentials in environment variables.
2021-09-10T13:21:44:INFO:botocore.credentials: Found credentials in environment variables.
2021-09-10T13:21:44:INFO:localstack.multiserver: Starting multi API server process on port 44747
[2021-09-10 13:21:44 +0000] [21] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-09-10T13:21:44:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
[2021-09-10 13:21:44 +0000] [21] [INFO] Running on http://0.0.0.0:44747 (CTRL + C to quit)
2021-09-10T13:21:44:INFO:hypercorn.error: Running on http://0.0.0.0:44747 (CTRL + C to quit)
2021-09-10 13:21:44,923:API:  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-09-10 13:21:44,925:API:  * Running on http://172.17.0.2:58869/ (Press CTRL+C to quit)
2021-09-10 13:21:45,122:API:  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2021-09-10 13:21:45,123:API:  * Running on http://172.17.0.2:49843/ (Press CTRL+C to quit)
Ready.
2021-09-10T13:21:50:INFO:botocore.credentials: Found credentials in environment variables.
2021-09-10 13:21:50,286:API: 127.0.0.1 - - [10/Sep/2021 13:21:50] "GET / HTTP/1.1" 200 -
2021-09-10T13:21:50:DEBUG:localstack.utils.persistence: saving startup info StartupInfo(timestamp='2021-09-10T13:21:50.317325', localstack_version='0.12.17.3', localstack_ext_version='0.12.16.3', pro_activated=False)

**Comment by whummer** [comment]
Thanks for the update @gnwlyonme . I believe the issue is that LocalStack attempts to re-download the cert file if the creation/modification timestamp is more than a certain time in the past (6 hours by default). Do you think you could try adjusting the modification timestamp of `server.test.pem` after downloading?

In general, the missing SSL cert should not have a huge functional impact on the behavior - you should still be able to use most of the features (incl. Pro features). Mid-term, it would be good to find a mechanism to - do you have access to some proxy from your corporate network that allows downloading files from Github? 

Hope that helps - please keep us posted how it goes.. Thanks!

**Comment by whummer** [comment]
Hi @gnwlyonme , we have recently fixed a couple of enhancements and made the SSL certificate installation more reliable. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks!
