### ISSUE TITLE
Unable to create AWS::Serverless::Api with Domain configuration 

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#4559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to deploy AWS::Serverless::Api resource with `Domain` configuration. To be honest, I don't expect the custom domain to work in localstack (although I see you have [examples of this working](https://github.com/localstack/localstack-pro-samples/tree/master/apigw-custom-domain)). The frustrating part is that I can't conditionally remove the `Domain` configuration for LocalStack via a CloudFormation condition because [AWS SAM lacks support for Intrinsic functions in this location](https://github.com/aws/serverless-application-model/issues/1859).

Template:
```
---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  Zone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: test.com.
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: app.test.com
      DomainValidationOptions:
      - DomainName: app.test.com
        ValidationDomain: app.test.com
      ValidationMethod: EMAIL
  Api:
    Type: "AWS::Serverless::Api"
    Properties:
      Name: test-app
      StageName: Prod
      # ------------------------------------
      # THIS IS THE OFFENDING CONFIG
      Domain:
        CertificateArn: !Ref Certificate
        DomainName: app.test.com
        SecurityPolicy: TLS_1_2
        Route53: 
          HostedZoneName: app.test.com
      # ------------------------------------
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Handler: index.handler
      Events: 
        ApiEvent:
          Type: Api
          Properties:
            Method: GET
            Path: /test
            RestApiId: !Ref Api
      FunctionName: test-function
      InlineCode: |
        def handler(event, context):
          print('hello world')
      PackageType: Zip
```

Notable log entries:
```
localstack_main   | 2021-09-08T03:45:45:INFO:localstack.utils.cloudformation.template_deployer: Action "create" for resource type ApiGateway::DomainName not yet implemented - using fallback mechanism
localstack_main   | 2021-09-08T03:45:45:DEBUG:localstack.utils.cloudformation.template_deployer: Unable to extract name for resource type "AWS::ApiGateway::DomainName"
localstack_main   | 2021-09-08T03:45:45:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: ApiGateway::DomainName PhysicalResourceId
localstack_main   | 2021-09-08T03:45:45:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "sam-custom-domain": Unable to extract attribute "PhysicalResourceId" from "ApiGateway::DomainName" model class <class 'localstack.services.cloudformation.service_models.GenericBaseModel'> Traceback (most recent call last):
localstack_main   |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1826, in _run
localstack_main   |     self.do_apply_changes_in_loop(changes, stack, stack_name)
localstack_main   |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1897, in do_apply_changes_in_loop
localstack_main   |     self.apply_change(change, stack, new_resources, stack_name=stack_name)
localstack_main   |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1968, in apply_change       
localstack_main   |     self.update_resource_details(resource_id, result, stack=old_stack, action=stack_action)
localstack_main   |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1648, in update_resource_details
localstack_main   |     physical_id = physical_id or determine_resource_physical_id(resource_id, stack=stack)
localstack_main   |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1280, in determine_resource_physical_id
localstack_main   |     resources=resources,
localstack_main   |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py", line 458, in extract_resource_attribute
localstack_main   |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 313, in extract_resource_attribute
localstack_main   |     % (attribute, resource_type, type(resource_state))
localstack_main   | Exception: Unable to extract attribute "PhysicalResourceId" from "ApiGateway::DomainName" model class <class 'localstack.services.cloudformation.service_models.GenericBaseModel'>
```

### Expected Behavior

I don't know exactly what I expect to happen when it "successfully deploys", I actually don't mind / care - I just want it to deploy. I don't even want the custom domain to be deployed, I just can't remove it without manually commenting out a section of the template which is less than ideal.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose.yml 
(lots of junk not related to this example, sorry)

Using `samlocal` https://github.com/localstack/aws-sam-cli-local

Template provided in Current Behavior section.

1. docker-compose up
2. samlocal deploy --stack-name sam-custom-domain -t sam-custom-domain.yml

```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510:4510"
      - "4513:4513"
      - "4514:4514"
      - "4571:4571"
      - "4572:4572"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=serverless,sns,sqs,kms,route53,acm
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=...
      - DEBUG=true
      # - KMS_PROVIDER=local-kms
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    tmpfs:
      - /tmp/localstack:exec,mode=600
    network_mode: bridge
  dynamodb-admin:
    depends_on:
      - localstack
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - localstack
    network_mode: bridge
```

### Environment

```markdown
- OS: Windows
- LocalStack: latest  sha256:4509c5e014a7412c58b59029a2ab7e1b5ca7312f5ba1139e546040a07ed06120
```

### Anything else?

Thanks for your help!

**Comment by calvernaz** [comment]
Works in the latest version 👍 

Example,
```
curl http://localhost:4566/test -H "host: app.test.com"
```
