### ISSUE TITLE
501 exception while connecting to localstack services programmatically using Java

### ISSUE THREAD

**Issue by maheshtruecar** [localstack/localstack#456]
Following command works fine on terminal but get the error below when try to connect programatically
aws --endpoint-url=http://localhost:4568 kinesis describe-stream --stream-name test-stream

`[Nov 10 20:26:02] INFO  (ApacheHttpClientFactory.java:91) - Configuring Proxy. Proxy Host: localhost Proxy Port: 4568
[Nov 10 20:26:02] INFO  (JsonContent.java:74) - Unable to parse HTTP response content
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: [B@264f218; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:462)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2613)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:841)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:737)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3776)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2294)
	at com.amazonaws.protocol.json.JsonContent.parseJsonContent(JsonContent.java:72)
	at com.amazonaws.protocol.json.JsonContent.<init>(JsonContent.java:64)
	at com.amazonaws.protocol.json.JsonContent.createJsonContent(JsonContent.java:54)
	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:61)
	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:33)
	at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:50)
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:38)
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:24)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1570)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2219)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2195)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.executeDescribeStream(AmazonKinesisClient.java:738)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:714)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:750)
	at com.truecar.de.wormhole.kinesis.examples.simple.KinesisSimpleProducer.validateStream(KinesisSimpleProducer.java:85)
	at com.truecar.de.wormhole.kinesis.examples.simple.KinesisSimpleProducer.run(KinesisSimpleProducer.java:68)
	at com.truecar.de.wormhole.kinesis.examples.simple.KinesisSimpleProducer.main(KinesisSimpleProducer.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Error found while describing the stream test-stream
com.amazonaws.services.kinesis.model.AmazonKinesisException: null (Service: AmazonKinesis; Status Code: 501; Error Code: null; Request ID: null)`

I tried putting a breakpoint inside AmazonHttpClient and see below
`HTTP/1.1 501 Unsupported method ('CONNECT') [Server: BaseHTTP/0.3 Python/2.7.10, Date: Fri, 10 Nov 2017 15:03:16 GMT, Content-Type: text/html, Connection: close] org.apache.http.entity.BufferedHttpEntity@2f40a43`

I spent considerable time googling on this. Any help is really appreciated.

I also tried connection to localstack s3 but get similar exception
`[Nov 10 20:43:01] INFO  (ApacheHttpClientFactory.java:91) - Configuring Proxy. Proxy Host: localhost Proxy Port: 4572
Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: Unsupported method ('CONNECT') (Service: Amazon S3; Status Code: 501; Error Code: 501 Unsupported method ('CONNECT'); Request ID: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1588)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4187)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4134)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4128)
	at com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:928)
	at com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:934)
	at com.truecar.de.wormhole.kinesis.examples.simple.KinesisSimpleProducer.run(KinesisSimpleProducer.java:73)
	at com.truecar.de.wormhole.kinesis.examples.simple.KinesisSimpleProducer.main(KinesisSimpleProducer.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)`

**Comment by maheshtruecar** [comment]
I figured this out, I was doing it wrong. It started working after using AmazonKinesisClientBuilder setEndpointConfiguration correctly.

**Comment by micd** [comment]
@mahesh-ogale, could you, please, share what was wrong with your endpoint configuration?
