### ISSUE TITLE
Spark Localstack S3 read file error AmazonS3Exception Error Code: 500

### ISSUE THREAD

**Issue by mehmet1092** [localstack/localstack#4562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

In my spark app, when I try to read a file in a localstack s3 bucket, I get an AmazonS3Exception (Status Code: 500).
The localstack is running on a remote server. I am able to list the files with 
`aws --endpoint-url=hostname:4566 s3 ls s3://bucket_name/`

I deployed localstack locally and I am able to read the same file. 

This is my spark configuration  
```
spark.sparkContext.hadoopConfiguration.set("fs.s3a.endpoint", "hostname:4566")
spark.sparkContext.hadoopConfiguration.set("fs.s3a.access.key", "acces_key")
spark.sparkContext.hadoopConfiguration.set("fs.s3a.secret.key", "secret_key")
spark.sparkContext.hadoopConfiguration.set("fs.s3a.path.style.access", "true")
spark.read.csv("s3a://bucket_name/file_name.csv")
```
Here is the error when I try to read the file from the s3 localstack on the remote server :
```
21/09/08 09:33:39 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
org.apache.hadoop.fs.s3a.AWSS3IOException: Reopen at position 0 on s3a://bucket_name/file_name.csv: com.amazonaws.services.s3.model.AmazonS3Exception:  (Service: Amazon S3; Status Code: 500; Error Code: 500 ; Request ID: null; S3 Extended Request ID: null), S3 Extended Request ID: null:  (Service: Amazon S3; Status Code: 500; Error Code: 500 ; Request ID: null; S3 Extended Request ID: null)
	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:194)
	at org.apache.hadoop.fs.s3a.S3AInputStream.reopen(S3AInputStream.java:167)
	at org.apache.hadoop.fs.s3a.S3AInputStream.lazySeek(S3AInputStream.java:293)
	at org.apache.hadoop.fs.s3a.S3AInputStream.read(S3AInputStream.java:376)
	at java.io.DataInputStream.read(DataInputStream.java:149)
	at org.apache.hadoop.mapreduce.lib.input.UncompressedSplitLineReader.fillBuffer(UncompressedSplitLineReader.java:62)
	at org.apache.hadoop.util.LineReader.readDefaultLine(LineReader.java:218)
	at org.apache.hadoop.util.LineReader.readLine(LineReader.java:176)
	at org.apache.hadoop.mapreduce.lib.input.UncompressedSplitLineReader.readLine(UncompressedSplitLineReader.java:94)
	at org.apache.hadoop.mapreduce.lib.input.LineRecordReader.skipUtfByteOrderMark(LineRecordReader.java:152)
	at org.apache.hadoop.mapreduce.lib.input.LineRecordReader.nextKeyValue(LineRecordReader.java:192)
	at org.apache.spark.sql.execution.datasources.RecordReaderIterator.hasNext(RecordReaderIterator.scala:39)
	at org.apache.spark.sql.execution.datasources.HadoopFileLinesReader.hasNext(HadoopFileLinesReader.scala:69)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:93)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:173)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:93)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:340)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
### How are you starting LocalStack?

With a docker-compose file

### Environment

- OS: Ubuntu 20.04.3
- LocalStack: 0.12.2

**Comment by ackdav** [comment]
Hi @mehmet1092 - thank you for raising this issue, and apologies for the late response. Since raising this issue, localstack and s3 went through numerous improvements - can you please pull the latest version and double-check whether this issue still persists?
Thank you!
