### ISSUE TITLE
Unable to start Localstack in Docker - Kinesis Fails to Start/Errors

### ISSUE THREAD

**Issue by cbellinz** [localstack/localstack#4592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Localstack in Docker startup fails with kinesis error:

```
localstack_1               | Traceback (most recent call last):
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 196, in check_infra
localstack_1               |     api=name, print_error=print_error, expect_shutdown=expect_shutdown
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 238, in check_service_health
localstack_1               |     raise e
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 231, in check_service_health
localstack_1               |     plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 132, in check
localstack_1               |     return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
localstack_1               |   File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 168, in check_kinesis
localstack_1               |     raise AssertionError("kinesis backend has stopped")
localstack_1               | AssertionError: kinesis backend has stopped
localstack_1               |
localstack_1               | During handling of the above exception, another exception occurred:
localstack_1               |
localstack_1               | Traceback (most recent call last):
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 196, in check_infra
localstack_1               |     api=name, print_error=print_error, expect_shutdown=expect_shutdown
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 238, in check_service_health
localstack_1               |     raise e
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 231, in check_service_health
localstack_1               |     plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 132, in check
localstack_1               |     return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
localstack_1               |   File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 168, in check_kinesis
localstack_1               |     raise AssertionError("kinesis backend has stopped")
localstack_1               | AssertionError: kinesis backend has stopped
localstack_1               |
localstack_1               | During handling of the above exception, another exception occurred:
localstack_1               |
localstack_1               | Traceback (most recent call last):
localstack_1               |   File "bin/localstack", line 23, in <module>
localstack_1               |     main()
localstack_1               |   File "bin/localstack", line 19, in main
localstack_1               |     main.main()
localstack_1               |   File "/opt/code/localstack/localstack/cli/main.py", line 6, in main
localstack_1               |     cli()
localstack_1               |   File "/opt/code/localstack/localstack/cli/plugin.py", line 30, in __call__
localstack_1               |     self.group(*args, **kwargs)
localstack_1               |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
localstack_1               |     return self.main(*args, **kwargs)
localstack_1               |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/click/core.py", line 1062, in main
localstack_1               |     rv = self.invoke(ctx)
localstack_1               |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
localstack_1               |     return _process_result(sub_ctx.command.invoke(sub_ctx))
localstack_1               |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
localstack_1               |     return ctx.invoke(self.callback, **ctx.params)
localstack_1               |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/click/core.py", line 763, in invoke
localstack_1               |     return __callback(*args, **kwargs)
localstack_1               |   File "/opt/code/localstack/localstack/cli/localstack.py", line 111, in cmd_start
localstack_1               |     bootstrap.start_infra_locally()
localstack_1               |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 365, in start_infra_locally
localstack_1               |     return infra.start_infra()
localstack_1               |   File "/opt/code/localstack/localstack/services/infra.py", line 492, in start_infra
localstack_1               |     raise e
localstack_1               |   File "/opt/code/localstack/localstack/services/infra.py", line 478, in start_infra
localstack_1               |     thread = do_start_infra(asynchronous, apis, is_in_docker)
localstack_1               |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/plugins.py", line 225, in do_start_infra
localstack_1               |     return do_start_infra_orig(asynchronous,apis,is_in_docker,*args,**kwargs)
localstack_1               |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/edge.py", line 76, in do_start_infra
localstack_1               |     return do_start_infra_orig(asynchronous,*args,**kwargs)
localstack_1               |   File "/opt/code/localstack/localstack/services/infra.py", line 570, in do_start_infra
localstack_1               |     thread = start_api_services()
localstack_1               |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 87, in wrapped
localstack_1               |     return f(*args, **kwargs)
localstack_1               |   File "/opt/code/localstack/localstack/services/infra.py", line 557, in start_api_services
localstack_1               |     check_infra(apis=apis)
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 210, in check_infra
localstack_1               |     additional_checks=additional_checks,
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 210, in check_infra
localstack_1               |     additional_checks=additional_checks,
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 210, in check_infra
localstack_1               |     additional_checks=additional_checks,
localstack_1               |   [Previous line repeated 7 more times]
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 204, in check_infra
localstack_1               |     raise e
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 196, in check_infra
localstack_1               |     api=name, print_error=print_error, expect_shutdown=expect_shutdown
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 238, in check_service_health
localstack_1               |     raise e
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 231, in check_service_health
localstack_1               |     plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
localstack_1               |   File "/opt/code/localstack/localstack/services/plugins.py", line 132, in check
localstack_1               |     return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
localstack_1               |   File "/opt/code/localstack/localstack/services/kinesis/kinesis_starter.py", line 168, in check_kinesis
localstack_1               |     raise AssertionError("kinesis backend has stopped")
localstack_1               | AssertionError: kinesis backend has stopped
```

### Expected Behavior

Localstack would start normally

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Docker compose

```
services:
  localstack:
    image: localstack/localstack:0.12.17.5
    ports:
      - "8080:8080"
      - "4566:4566"
      - "4510:4510"
      - "4571:4571"
    environment:
      - LOCALSTACK_API_KEY=123456
      - DEFAULT_REGION=eu-west-1
      - HOSTNAME_EXTERNAL=aws.xxx.local
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - LAMBDA_REMOTE_DOCKER=0
      - SERVICES="edge,serverless,kms,secretsmanager,s3,ecr,cloudformation,cloudwatch,sts,logs,sqs,sns,ssm,events"
      - LAMBDA_EXECUTOR=local
    volumes:
      - "${PWD}/localstack/tmp:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```

### Environment

```markdown
- OS: Mac OS 11.6
- Docker Desktop: 4.0.1 (68347) 
- LocalStack: 0.12.17.5
```

### Anything else?

Issue also present on "latest" image version (as of 14 Sep 10:00 UTC)

I believe this could be a docker/OS issue as was working yesterday prior to doing an OS/Docker update.

Things tried:
 - Docker restart
 - OS reboot
 - Previous version of localstack = 0.12.17.4

**Comment by cbellinz** [comment]
OK, i've fixed it.

In my host` localstack/tmp folder`, the following file existed:

`data/kinesis/kinesis-data.json`

It was a blank file, no content at all.

I removed the kinesis directory and it's contents, restarted Localstack and now the file contains the following content:

`{"streams":{}}`

I hope this helps anyone else facing the same issue.

Chris
