### ISSUE TITLE
bug: type hinting in python code prevents to run lambda

### ISSUE THREAD

**Issue by aspacca** [localstack/localstack#4593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When lambda in python uses type hinting `lambda_executors.py` raise a `TypeError` exception: `'type' object is not subscriptable`

### Expected Behavior

In can run python lambda with type hinting on localstack

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=docker
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/private/tmp/localstack
    volumes:
      - /private/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - 
```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal iam create-role --role-name lambda-role --assume-role-policy-document file://role.json

zip lambda.zip lambda.py
awslocal s3 mb s3://lambda
awslocal s3 cp lambda.zip s3://lambda/lambda.zip

awslocal lambda create-function --function-name myLambda --code S3Bucket="lambda",S3Key="lambda.zip" --handler lambda.lambda_handler --runtime python3.8 --role arn:aws:iam::000000000000:role/lambda-role

awslocal lambda invoke --cli-binary-format raw-in-base64-out --function myLambda --invocation-type Event --payload '{ "name": "Bob" }' response.json
```

Localstack logs:
```
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/utils/run.py", line 150, in run
localstack_main |     result = self.func(self.params, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 335, in do_execute
localstack_main |     return _run(func_arn=func_arn)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 157, in wrapped
localstack_main |     raise e
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 153, in wrapped
localstack_main |     result = func(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 322, in _run
localstack_main |     raise e
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 308, in _run
localstack_main |     result = self._execute(func_arn, func_details, event, context, version)
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 594, in _execute
localstack_main |     event=event_bytes_for_stdin, env_vars=environment, func_details=func_details
localstack_main |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 524, in run_lambda_executor
localstack_main |     ) from error
localstack_main | localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: {"errorType":"TypeError","errorMessage":"'type' object is not subscriptable","stackTrace":["  File \"/var/lang/lib/python3.8/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n","  File \"/var/lang/lib/python3.8/imp.py\", line 171, in load_source\n    module = _load(spec)\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 702, in _load\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 671, in _load_unlocked\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 783, in exec_module\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 219, in _call_with_frames_removed\n","  File \"/var/task/lambda.py\", line 3, in \u003cmodule\u003e\n    def lambda_handler(lambda_event: dict[str, Any], lambda_context: Any):\n"]}. Output:
localstack_main | [ERROR] TypeError: 'type' object is not subscriptable
localstack_main | Traceback (most recent call last):
localstack_main |   File "/var/lang/lib/python3.8/imp.py", line 234, in load_module
localstack_main |     return load_source(name, filename, file)
localstack_main |   File "/var/lang/lib/python3.8/imp.py", line 171, in load_source
localstack_main |     module = _load(spec)
localstack_main |   File "<frozen importlib._bootstrap>", line 702, in _load
localstack_main |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
localstack_main |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
localstack_main |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
localstack_main |   File "/var/task/lambda.py", line 3, in <module>
localstack_main |     def lambda_handler(lambda_event: dict[str, Any], lambda_context: Any):
```

lambda.py:
```
from typing import Any

def lambda_handler(lambda_event: dict[str, Any], lambda_context: Any):
    print(lambda_event, lambda_context)

```

### Environment

```markdown
- OS: 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
- LocalStack: latest
```

**Comment by pinzon** [comment]
Hi this seems to me an usage problem. **The solution for this is to use python3.9 as runtime for your lambda.**
The error your showing also happens when using AWS so there's no change needed for this issue.
Thank you for your interest in the project.

**Comment by aspacca** [comment]
@pinzon you right, sorry for the misreport.
I was using python3.9 runtime on AWS and when testing localstack it was not still available: I run on python3.8 and missing to figure out the problem could be in the runtime version

thanks for checking the issue anyway :)
