### ISSUE TITLE
bug: persistence doesn't work when I start the container again

### ISSUE THREAD

**Issue by alexserver** [localstack/localstack#4613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using localstack as a docker compose container

If I stop the container with `docker compose stop s3-localstack` and then I restart it again, it doesn't recognize the previously saved transactions in `recorded_api_calls.json`
It throws error in the console:

```
KeyError: '6atqPqtceCOSpYDsEgORcL28bsKicpGU7YUfkwU3eOM6RmxpD4PfCQ'
s3_1       | 2021-09-18 02:53:45,170:API: 127.0.0.1 - - [18/Sep/2021 02:53:45] "POST /spot2nite/uploads/photo/attachments/c62278d0-1822-11ec-a464-1e00d9367a51/original.jpg?uploadId=x6vLomyQ8YuCLJB5pSLN3OhcwYe7AYyYlDsI0sYLJPWyZBb8XjewrCDA HTTP/1.1" 500 -
s3_1       | 2021-09-18 02:53:45,256:API: 127.0.0.1 - - [18/Sep/2021 02:53:45] "POST /spot2nite/uploads/photo/attachments/c62278d0-1822-11ec-a464-1e00d9367a51/thumb.png?uploadId=9z2HckzJno2hmDY3HjcixRHWfxTLYnovf3PySBm14ow5PuyfSZn90MFzA HTTP/1.1" 500 -
s3_1       | 2021-09-18 02:53:45,264:API: Error on request:
s3_1       | Traceback (most recent call last):
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
s3_1       |     execute(self.server.app)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute
s3_1       |     application_iter = app(environ, start_response)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 268, in __call__
s3_1       |     return backend_app(environ, start_response)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
s3_1       |     return self.wsgi_app(environ, start_response)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
s3_1       |     response = self.handle_exception(e)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
s3_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
s3_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
s3_1       |     response = self.full_dispatch_request()
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
s3_1       |     rv = self.handle_user_exception(e)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
s3_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
s3_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
s3_1       |     rv = self.dispatch_request()
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
s3_1       |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 148, in __call__
s3_1       |     result = self.callback(request, request.url, {})
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 282, in _wrapper
s3_1       |     response = f(*args, **kwargs)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py", line 1034, in key_or_control_response
s3_1       |     response = self._key_response(request, full_url, self.headers)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py", line 1220, in _key_response
s3_1       |     return self._key_response_post(request, body, bucket_name, query, key_name)
s3_1       |   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 166, in s3_key_response_post
s3_1       |     request, body, bucket_name, query, key_name, *args, **kwargs
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py", line 1933, in _key_response_post
s3_1       |     bucket_name, multipart_id, body
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/models.py", line 1741, in complete_multipart_upload
s3_1       |     multipart = bucket.multiparts[multipart_id]
s3_1       | KeyError: 'x6vLomyQ8YuCLJB5pSLN3OhcwYe7AYyYlDsI0sYLJPWyZBb8XjewrCDA'
s3_1       | 2021-09-18T02:53:45:INFO:localstack.utils.persistence: Restored 19 API calls from persistent file: /tmp/localstack/data/recorded_api_calls.json
s3_1       | 2021-09-18 02:53:45,311:API: Error on request:
s3_1       | Traceback (most recent call last):
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
s3_1       |     execute(self.server.app)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute
s3_1       |     application_iter = app(environ, start_response)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 268, in __call__
s3_1       |     return backend_app(environ, start_response)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
s3_1       |     return self.wsgi_app(environ, start_response)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
s3_1       |     response = self.handle_exception(e)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
s3_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
s3_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
s3_1       |     response = self.full_dispatch_request()
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
s3_1       |     rv = self.handle_user_exception(e)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
s3_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
s3_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
s3_1       |     rv = self.dispatch_request()
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
s3_1       |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 148, in __call__
s3_1       |     result = self.callback(request, request.url, {})
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 282, in _wrapper
s3_1       |     response = f(*args, **kwargs)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py", line 1034, in key_or_control_response
s3_1       |     response = self._key_response(request, full_url, self.headers)
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py", line 1220, in _key_response
s3_1       |     return self._key_response_post(request, body, bucket_name, query, key_name)
s3_1       |   File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 166, in s3_key_response_post
s3_1       |     request, body, bucket_name, query, key_name, *args, **kwargs
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py", line 1933, in _key_response_post
s3_1       |     bucket_name, multipart_id, body
s3_1       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/models.py", line 1741, in complete_multipart_upload
s3_1       |     multipart = bucket.multiparts[multipart_id]
s3_1       | KeyError: '9z2HckzJno2hmDY3HjcixRHWfxTLYnovf3PySBm14ow5PuyfSZn90MFzA'
s3_1       | 2021-09-18T02:53:45:INFO:bootstrap.py: Execution of "start_api_services" took 8588.90ms
```

### Expected Behavior

I expect that localstack recognizes previously uploaded resources and restored to the bucket when container restarts with `docker compose up s3`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up s3

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

aws s3api list-buckets --endpoint-url http://localhost:4566 (works fine)

aws s3api list-objects --bucket my-bucket --endpoint-utl http://localhost:4566 (fails, return empty bucket)

### Environment

```markdown
- OS: MacOs Big Sur Chip M1
- LocalStack: Docker Compose:

docker-compose.yaml


  s3:
    # this s3 server is possible thanks to localstack https://github.com/localstack/localstack
    image: localstack/localstack:0.12.17.5
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=spot2nite
      - AWS_SECRET_ACCESS_KEY=spot2nite
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
    ports:
      # localstack uses a range of ports
      # s3 uses only 4566
      - '4563-4584:4563-4584'
      - '8008:8080'
    volumes:
      # we need to share this volume to start spot2nite volume
      - "./volumes/s3/.init:/docker-entrypoint-initaws.d"
      # to host .pem and data dir
      - "./volumes/s3/.localstack:/tmp/localstack"
```
```


### Anything else?

I'm using version `0.12.17.5` . I tried with `10.5` and didn't work either.

If you need more information I'm happy to provide more.

**Comment by giograno** [comment]
Hi @alexserver. Unfortunately, we discontinued the record/replay-based persistence mechanism implemented in the community version in [0.13.1](https://github.com/localstack/localstack/releases/tag/v0.13.1). You can find a detailed explanation of our reasoning in this comment: https://github.com/localstack/localstack/issues/3881#issuecomment-1004009450.
Such a persistence mechanism has been completely removed with [v.1.0.0](https://github.com/localstack/localstack/releases/tag/v1.0.0). However, we now offer a more robust and advanced persisting mechanism that you can enable with the `PERSISTENCE=1` environment variable. Please be aware that this is a Pro-only feature. Thank you very much 🙏
