### ISSUE TITLE
bug: DynamoDb can't start on mac m1

### ISSUE THREAD

**Issue by Paparama** [localstack/localstack#4625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

services:
  localstack:
    image: localstack/localstack:m1-jre-fix # also use latest  - 0.12.17.5 same behavior
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
    ports:
      - '4566:4566'
    networks:
      - localstack-network

`Exception in thread "main" java.lang.ExceptionInInitializerError
2021-09-21T12:43:47.983286584Z at org.eclipse.jetty.http.MimeTypes.<clinit>(MimeTypes.java:191)
2021-09-21T12:43:47.983290834Z at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:836)
2021-09-21T12:43:47.983293126Z at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
2021-09-21T12:43:47.983295251Z at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
2021-09-21T12:43:47.983305876Z at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
2021-09-21T12:43:47.983307959Z at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
2021-09-21T12:43:47.983309876Z at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
2021-09-21T12:43:47.983311793Z at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
2021-09-21T12:43:47.983313751Z at org.eclipse.jetty.server.Server.start(Server.java:418)
2021-09-21T12:43:47.983315584Z at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
2021-09-21T12:43:47.983317543Z at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
2021-09-21T12:43:47.983543751Z at org.eclipse.jetty.server.Server.doStart(Server.java:382)
2021-09-21T12:43:47.983550751Z at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
2021-09-21T12:43:47.983553209Z at com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer.start(DynamoDBProxyServer.java:83)
2021-09-21T12:43:47.983555418Z at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.main(ServerRunner.java:76)
2021-09-21T12:43:47.983557501Z Caused by: java.nio.charset.IllegalCharsetNameException: l;charset=iso-8859-1
2021-09-21T12:43:47.983559418Z at java.base/java.nio.charset.Charset.checkName(Unknown Source)
2021-09-21T12:43:47.983561293Z at java.base/java.nio.charset.Charset.lookup2(Unknown Source)
2021-09-21T12:43:47.983563293Z at java.base/java.nio.charset.Charset.lookup(Unknown Source)
2021-09-21T12:43:47.983565209Z at java.base/java.nio.charset.Charset.forName(Unknown Source)
2021-09-21T12:43:47.983567084Z at org.eclipse.jetty.http.MimeTypes$Type.<init>(MimeTypes.java:113)
2021-09-21T12:43:47.983569084Z at org.eclipse.jetty.http.MimeTypes$Type.<clinit>(MimeTypes.java:69)
2021-09-21T12:43:47.983570959Z ... 15 more
2021-09-21T12:43:47.984108293Z 2021-09-21T12:43:47:INFO:localstack.utils.common: Restarting process (received exit code 1): cd /opt/code/localstack/localstack/infra/dynamodb/; java -Djava.library.path=./DynamoDBLocal_lib -Xmx256m -jar DynamoDBLocal.jar -port 34205 -dbPath /tmp/localstack/data/dynamodb
2021-09-21T12:43:47.984124043Z 2021-09-21T12:43:47:DEBUG:localstack.utils.run: Executing command: cd /opt/code/localstack/localstack/infra/dynamodb/; java -Djava.library.path=./DynamoDBLocal_lib -Xmx256m -jar DynamoDBLocal.jar -port 34205 -dbPath /tmp/localstack/data/dynamodb
2021-09-21T12:43:48.984092751Z Initializing DynamoDB Local with the following configuration:
2021-09-21T12:43:48.984119210Z Port:	34205
2021-09-21T12:43:48.984123501Z InMemory:	false
2021-09-21T12:43:48.984135668Z DbPath:	/tmp/localstack/data/dynamodb
2021-09-21T12:43:48.984138668Z SharedDb:	false
2021-09-21T12:43:48.984150626Z shouldDelayTransientStatuses:	false
2021-09-21T12:43:48.984153960Z CorsParams:	*
2021-09-21T12:43:48.984156043Z 
2021-09-21T12:43:50.417877710Z Waiting for all LocalStack services to be ready
2021-09-21T12:43:54.994787254Z 2021-09-21T12:43:54:WARNING:localstack.services.plugins: Service "dynamodb" not yet available, retrying...`

### Expected Behavior

dynamodb up and work fine

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

### Environment

```markdown
- OS: macOS Big Sur 11.3.1 (20E241)
- LocalStack: latest/m1-jre-fix
```

**Comment by Geooorg** [comment]
I can confirm the issue.

In org.eclipse.jetty.http.MimeTypes, the Charset ist created that way:

```        
Type(String s, Type base)
        {
            _string = s;
            _buffer = BufferUtil.toBuffer(s);
            _base = base;
            int i = s.indexOf(";charset=");
            _charset = Charset.forName(s.substring(i + 9));
            _charsetString = _charset.toString().toLowerCase(Locale.ENGLISH);
            _assumedCharset = false;
            _field = new PreEncodedHttpField(HttpHeader.CONTENT_TYPE, _string);
        }
```
       
        
Obviously, the string 's' **should** contain "text/html;charset=iso-8859-1".
Then the first part "text/html;charset=" should be cut off.
However, it looks like this substring operation does not work as expected, as the exception thrown reports

> java.nio.charset.IllegalCharsetNameException: l;charset=iso-8859-1

This can be verified in Charset.java:

```private static void checkName(String s) {
        int n = s.length();
        if (n == 0) {
            throw new IllegalCharsetNameException(s);
        }
        for (int i = 0; i < n; i++) {
            char c = s.charAt(i);
            if (c >= 'A' && c <= 'Z') continue;
            if (c >= 'a' && c <= 'z') continue;
            if (c >= '0' && c <= '9') continue;
            if (c == '-' && i != 0) continue;
            if (c == '+' && i != 0) continue;
            if (c == ':' && i != 0) continue;
            if (c == '_' && i != 0) continue;
            if (c == '.' && i != 0) continue;
            throw new IllegalCharsetNameException(s);
        }```

So the question is why the substring operation fails.

**Comment by joakime** [comment]
Have you confirmed that the String actually is `"text/html;charset=iso-8859-1"` ?

Has anyone here walked through the behavior with a debugger yet?
The input `s` should be `"text/html;charset=iso-8859-1"`.
The value of `i` should be `9`.
The `s.substring(i+9)` should result in `"iso-8859-1"`.

Can anyone with an M1 macbook replicate in a smaller testcase?

``` java
package charsets;

import java.nio.charset.Charset;

public class CharsetForNameDemo
{
    public static void main(String[] args)
    {
        String s = "text/html;charset=iso-8859-1";
        int i = s.indexOf(";charset=");
        String substring = s.substring(i+9);
        Charset charset = Charset.forName(substring);
        System.out.println("charset = " + charset);
    }
}
```

Either the input String is `"text/html;charset=l;charset=iso-8859-1"` which means you have a corrupt Jetty.
Or the result of `s.indexOf(";charset=")` is not 9, which means you have a corrupt Java.
Or the result of `s.substring(i+9)` is bad, which also means you have a corrupt Java.

Speaking of Jetty, version 9.4.18 that you are running is subject to several security vulnerabilities.
You should upgrade - https://www.eclipse.org/jetty/security_reports.php

**Comment by joakime** [comment]
Some other things to consider.

Using docker on an M1 macbook means that your images should be based on ARM64 for success. (all other image types are currently broken/unreliable)
See: https://docs.docker.com/desktop/mac/apple-silicon/#:~:text=We%20recommend%20running%20arm64%20containers,are%20rebuilt%20supporting%20multiple%20architectures.

I see `-alpine` in the jvm `11.0.12+7-alpine-r0`.
That's unlikely to be ARM64 based.

Another thing to try, disable the JIT on your Java installation and see if it happens again.
If that fixes it, the fault is in your JVM. (Use a different JVM? non-alpine? from a different vendor? azul?)

**Comment by Paparama** [comment]
I find solution - just use localstack/localstack:0.12.12, so probably image changes led to error

**Comment by mark-brooks-roostify** [comment]
> I find solution - just use localstack/localstack:0.12.12, so probably image changes led to error

I'm going to give your suggestion a try, as I'm experiencing this on apple m1 as well.

**Comment by mark-brooks-roostify** [comment]
Please note -- I'm using the Docker image, not raw on Apple M1.  Yet I'm getting the error trying to run DynamoDB.  So the problem lies in the image in some sense.

**Comment by mark-brooks-roostify** [comment]
@Paparama @Geooorg @joakime I can report that in fact using the docker image tagged 0.12.12 fixes the issue, so the problem lies with the latest.

**Comment by joakime** [comment]
Note that even docker themselves say its unreliable to run non-ARM64 docker images on Mac M1.
If that docker image isn't ARM64 based, then you just got lucky this run.
If that docker image is not ARM64 based, run a longer term test before declaring success.

**Comment by mark-brooks-roostify** [comment]
> Note that even docker themselves say its unreliable to run non-ARM64 docker images on Mac M1. If that docker image isn't ARM64 based, then you just got lucky this run. If that docker image is not ARM64 based, run a longer term test before declaring success.

I'm only seeing that localstack has linux/AMD64 images.  I'll run it longer term and see what happens, but so far it is working.

**Comment by navels** [comment]
There is an open issue for ARM64 support: https://github.com/localstack/localstack/issues/2550

Meanwhile, I've been using the x86_64 image on my M1 daily for months with no issues.

**Comment by alexrashed** [comment]
Hi @Paparama! We just released 0.13, where we are now providing a native arm64 image. This issue should hopefully be fixed with the native image. Could you give it a try to verify that it now works as expected? Thanks!

**Comment by prashil-g** [comment]
+1

**Comment by alexrashed** [comment]
Hi @prashil-g!
Since this ticket is already quite old and we now directly support ARM-64 (i.e. M1 without the usage of Rosetta), could you please provide a description of your issues with M1 and DynamoDB in LocalStack?

**Comment by prashil-g** [comment]
We are on 0.11 localstack docker image. I see that migrating from 0.11 to 0.13 isnt straightforward. I tried to find documentation for migration but coudnt. As a result I would request to provide arm64 image for 0.11 version

**Comment by alexrashed** [comment]
Unfortunately, that's not something we can easily do. As you can see in the PR (https://github.com/localstack/localstack/pull/4754), the native ARM64 support in LocalStack was quite a heavy lifting with lots of code-changes.
If you need help with your upgrade, please reach out to the community or the Pro support in our Slack channel.
