### ISSUE TITLE
bug: Lambda Node Function with synchronous handler function ERROR

### ISSUE THREAD

**Issue by wesleymilan** [localstack/localstack#4633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lambda functions are not running due to Python error

### Expected Behavior

Lambda function should return a simple response

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
 localstack.docker:
    container_name: "localstack"
    image: localstack/localstack
    expose:
      - 53
      - 443
      - 4510-4530
      - 4566-4620
    ports:
      - "53:53"
      - "443:443"
      - "4510-4530:4510-4530"
      - "4566-4620:4566-4620"
    environment:
      - LOCALSTACK_API_KEY=XXXXXXX
      - SERVICES=iam,sqs,sns,cloudwatch,lambda,elasticache,rds,appconfig,iot,neptune,apigateway,cloudformation
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "./localstack/tmp:/tmp/localstack"
```

#### Lambda code
```
'use strict';

exports.handler = function(event, context, callback) {

    const result = {
        statusCode: 200,
        headers: {
            'Access-Control-Allow-Origin': '*'
        },
        body: ""
    };

    callback(null, result);

};
```

#### Lambda Creation Command
```
aws lambda create-function \
    --endpoint-url=http://localhost:4566 \
    --function-name WebsocketLambda \
    --runtime nodejs8.x \
    --zip-file fileb://lambda/websocket/websocket.zip \
    --handler handler \
    --timeout 10 \
    --memory-size 128 \
    --role arn:aws:iam::000000000000:role/service-role/WebsocketRole
```

#### Lambda error response
```
<div class="MuiGrid-root jss351 MuiGrid-container MuiGrid-spacing-xs-2" style="box-sizing: border-box; margin: -8px; padding: 24px; width: calc(100% + 16px); display: flex; flex-wrap: wrap; color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-12 MuiGrid-grid-lg-6 MuiGrid-grid-xl-6" style="box-sizing: border-box; margin: 0px; padding: 8px; flex-grow: 0; max-width: 50%; flex-basis: 50%;"><div class="MuiPaper-root MuiCard-root MuiPaper-elevation1 MuiPaper-rounded" style="box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(18, 22, 27); transition: box-shadow 300ms cubic-bezier(0.4, 0, 0.2, 1) 0ms; background-color: rgb(255, 255, 255); border-radius: 4px; box-shadow: rgba(0, 0, 0, 0.2) 0px 2px 1px -1px, rgba(0, 0, 0, 0.14) 0px 1px 1px 0px, rgba(0, 0, 0, 0.12) 0px 1px 3px 0px; overflow: hidden;"><div class="MuiCardContent-root" style="box-sizing: border-box; margin: 0px; padding: 16px 16px 24px;"><div class="MuiTypography-root MuiTypography-body1" aria-labelledby="simple-tab-1" id="simple-tabpanel-1" role="tabpanel" style="box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(18, 22, 27); font-size: 14px; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; line-height: 21px; letter-spacing: -0.05px;"><div class="MuiBox-root jss425" style="box-sizing: border-box; margin: 0px; padding: 24px;">

{"errorType":"InvocationException","errorMessage":"Lambda process returned error status code: 1. Result: . Output:\n/tmp/localstack/zipfile.d6919b72/handler.js:13\n callback(null, result);\n ^\n\nTypeError: callback is not a function\n at Object.exports.handler (/tmp/localstack/zipfile.d6919b72/handler.js:13:5)\n at [eval]:1:56\n at Script.runInThisContext (vm.js:134:12)\n at Object.runInThisContext (vm.js:310:38)\n at internal/process/execution.js:81:19\n at [eval]-wrapper:6:22\n at evalScript (internal/process/execution.js:80:60)\n at internal/main/eval_string.js:27:3","stackTrace":[" File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 840, in run_lambda\n lock_discriminator=lock_discriminator,\n"," File \"/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/awslambda/lambda_extended.py\", line 529, in execute_local_executor\n"," File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 346, in execute\n return do_execute()\n"," File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 336, in do_execute\n return _run(func_arn=func_arn)\n"," File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 157, in wrapped\n raise e\n"," File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 153, in wrapped\n result = func(*args, **kwargs)\n"," File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 323, in _run\n raise e\n"," File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 309, in _run\n result = self._execute(func_arn, func_details, event, context, version)\n"," File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1114, in _execute\n raise InvocationException(result, log_output)\n"]}
--


</div></div></div></div></div></div><br class="Apple-interchange-newline">
```

#### Docker Terminal Output
```
localstack    | 2021-09-22T00:10:43:DEBUG:localstack.services.awslambda.lambda_api: Running Lambda function arn:aws:lambda:us-east-1:000000000000:function:WebsocketLambda from API Gateway invocation: GET /websocket
localstack    | 2021-09-22T00:10:43:INFO:localstack.services.awslambda.lambda_executors: node -e 'require("/tmp/localstack/zipfile.d6919b72/handler.js").handler({"path": "/websocket", "headers": {"remote-addr": "172.18.0.1", "host": "localhost:4566", "connection": "keep-alive", "sec-ch-ua": "\"Google Chrome\";v=\"93\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"93\"", "accept": "application/json, text/plain, */*", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36", "sec-ch-ua-platform": "\"macOS\"", "origin": "https://app.localstack.cloud", "sec-fetch-site": "cross-site", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "accept-encoding": "gzip, deflate, br", "accept-language": "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7", "x-forwarded-for": "172.18.0.1, localhost:4566, 127.0.0.1, localhost:4566", "x-localstack-edge": "http://localhost:4566", "authorization": "AWS4-HMAC-SHA256 Credential=__internal_call__/20160623/us-east-1/apigateway/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=1234", "x-localstack-tgt-api": "apigateway", "__apigw_request_region__": "us-east-1"}, "multiValueHeaders": {"remote-addr": ["172.18.0.1"], "host": ["localhost:4566"], "connection": ["keep-alive"], "sec-ch-ua": ["\"Google Chrome\";v=\"93\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"93\""], "accept": ["application/json, text/plain, */*"], "sec-ch-ua-mobile": ["?0"], "user-agent": ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"], "sec-ch-ua-platform": ["\"macOS\""], "origin": ["https://app.localstack.cloud"], "sec-fetch-site": ["cross-site"], "sec-fetch-mode": ["cors"], "sec-fetch-dest": ["empty"], "accept-encoding": ["gzip, deflate, br"], "accept-language": ["pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7"], "x-forwarded-for": ["172.18.0.1, localhost:4566, 127.0.0.1, localhost:4566"], "x-localstack-edge": ["http://localhost:4566"], "authorization": ["AWS4-HMAC-SHA256 Credential=__internal_call__/20160623/us-east-1/apigateway/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=1234"], "x-localstack-tgt-api": ["apigateway"], "__apigw_request_region__": ["us-east-1"]}, "body": "", "isBase64Encoded": false, "httpMethod": "GET", "queryStringParameters": {}, "multiValueQueryStringParameters": {}, "pathParameters": {}, "resource": "/websocket", "requestContext": {"path": "/dev/websocket", "resourcePath": "/websocket", "apiId": "db7b92ubkw", "domainPrefix": "db7b92ubkw", "domainName": "db7b92ubkw.execute-api.localhost.localstack.cloud", "accountId": "000000000000", "resourceId": "wi0vq3pjgg", "stage": "dev", "identity": {"accountId": "000000000000", "sourceIp": "127.0.0.1", "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"}, "httpMethod": "GET", "protocol": "HTTP/1.1", "requestTime": "2021-09-22T00:10:43.807Z", "requestTimeEpoch": 1632269443807}, "stageVariables": {}},{"function_name": "WebsocketLambda", "function_version": "$LATEST", "client_context": null, "invoked_function_arn": "arn:aws:lambda:us-east-1:000000000000:function:WebsocketLambda", "cognito_identity": null, "aws_request_id": "f8ce6134-c4e8-4c58-9d10-c901a0fa0e51", "memory_limit_in_mb": 128, "log_group_name": "/aws/lambda/WebsocketLambda", "log_stream_name": "2021/09/22/[1]0ac0b021"}).then(r => process.stdout.write(JSON.stringify(r)))'
localstack    | 2021-09-22T00:10:43:DEBUG:localstack.utils.run: Executing command: node -e 'require("/tmp/localstack/zipfile.d6919b72/handler.js").handler({"path": "/websocket", "headers": {"remote-addr": "172.18.0.1", "host": "localhost:4566", "connection": "keep-alive", "sec-ch-ua": "\"Google Chrome\";v=\"93\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"93\"", "accept": "application/json, text/plain, */*", "sec-ch-ua-mobile": "?0", "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36", "sec-ch-ua-platform": "\"macOS\"", "origin": "https://app.localstack.cloud", "sec-fetch-site": "cross-site", "sec-fetch-mode": "cors", "sec-fetch-dest": "empty", "accept-encoding": "gzip, deflate, br", "accept-language": "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7", "x-forwarded-for": "172.18.0.1, localhost:4566, 127.0.0.1, localhost:4566", "x-localstack-edge": "http://localhost:4566", "authorization": "AWS4-HMAC-SHA256 Credential=__internal_call__/20160623/us-east-1/apigateway/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=1234", "x-localstack-tgt-api": "apigateway", "__apigw_request_region__": "us-east-1"}, "multiValueHeaders": {"remote-addr": ["172.18.0.1"], "host": ["localhost:4566"], "connection": ["keep-alive"], "sec-ch-ua": ["\"Google Chrome\";v=\"93\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"93\""], "accept": ["application/json, text/plain, */*"], "sec-ch-ua-mobile": ["?0"], "user-agent": ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"], "sec-ch-ua-platform": ["\"macOS\""], "origin": ["https://app.localstack.cloud"], "sec-fetch-site": ["cross-site"], "sec-fetch-mode": ["cors"], "sec-fetch-dest": ["empty"], "accept-encoding": ["gzip, deflate, br"], "accept-language": ["pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7"], "x-forwarded-for": ["172.18.0.1, localhost:4566, 127.0.0.1, localhost:4566"], "x-localstack-edge": ["http://localhost:4566"], "authorization": ["AWS4-HMAC-SHA256 Credential=__internal_call__/20160623/us-east-1/apigateway/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=1234"], "x-localstack-tgt-api": ["apigateway"], "__apigw_request_region__": ["us-east-1"]}, "body": "", "isBase64Encoded": false, "httpMethod": "GET", "queryStringParameters": {}, "multiValueQueryStringParameters": {}, "pathParameters": {}, "resource": "/websocket", "requestContext": {"path": "/dev/websocket", "resourcePath": "/websocket", "apiId": "db7b92ubkw", "domainPrefix": "db7b92ubkw", "domainName": "db7b92ubkw.execute-api.localhost.localstack.cloud", "accountId": "000000000000", "resourceId": "wi0vq3pjgg", "stage": "dev", "identity": {"accountId": "000000000000", "sourceIp": "127.0.0.1", "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"}, "httpMethod": "GET", "protocol": "HTTP/1.1", "requestTime": "2021-09-22T00:10:43.807Z", "requestTimeEpoch": 1632269443807}, "stageVariables": {}},{"function_name": "WebsocketLambda", "function_version": "$LATEST", "client_context": null, "invoked_function_arn": "arn:aws:lambda:us-east-1:000000000000:function:WebsocketLambda", "cognito_identity": null, "aws_request_id": "f8ce6134-c4e8-4c58-9d10-c901a0fa0e51", "memory_limit_in_mb": 128, "log_group_name": "/aws/lambda/WebsocketLambda", "log_stream_name": "2021/09/22/[1]0ac0b021"}).then(r => process.stdout.write(JSON.stringify(r)))'
localstack    | 2021-09-22T00:10:43:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:WebsocketLambda result / log output:
localstack    | 
localstack    | > /tmp/localstack/zipfile.d6919b72/handler.js:13
localstack    | >     callback(null, result);
localstack    | >     ^
localstack    | > 
localstack    | > TypeError: callback is not a function
localstack    | >     at Object.exports.handler (/tmp/localstack/zipfile.d6919b72/handler.js:13:5)
localstack    | >     at [eval]:1:56
localstack    | >     at Script.runInThisContext (vm.js:134:12)
localstack    | >     at Object.runInThisContext (vm.js:310:38)
localstack    | >     at internal/process/execution.js:81:19
localstack    | >     at [eval]-wrapper:6:22
localstack    | >     at evalScript (internal/process/execution.js:80:60)
localstack    | >     at internal/main/eval_string.js:27:3
localstack    | 2021-09-22T00:10:43:INFO:localstack.services.awslambda.lambda_executors: Error executing Lambda "arn:aws:lambda:us-east-1:000000000000:function:WebsocketLambda": Lambda process returned error status code: 1. Result: . Output:
localstack    | /tmp/localstack/zipfile.d6919b72/handler.js:13
localstack    |     callback(null, result);
localstack    |     ^
localstack    | 
localstack    | TypeError: callback is not a function
localstack    |     at Object.exports.handler (/tmp/localstack/zipfile.d6919b72/handler.js:13:5)
localstack    |     at [eval]:1:56
localstack    |     at Script.runInThisContext (vm.js:134:12)
localstack    |     at Object.runInThisContext (vm.js:310:38)
localstack    |     at internal/process/execution.js:81:19
localstack    |     at [eval]-wrapper:6:22
localstack    |     at evalScript (internal/process/execution.js:80:60)
localstack    |     at internal/main/eval_string.js:27:3   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1082, in _execute
localstack    |     process.run()
localstack    |   File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
localstack    |     self._target(*self._args, **self._kwargs)
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1069, in do_execute
localstack    |     result = lambda_function(event, context)
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1163, in execute
localstack    |     event, context, main_file=main_file, func_details=lambda_details
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1177, in execute_javascript_lambda
localstack    |     result = self._execute_in_custom_runtime(cmd, func_details=func_details)
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1032, in _execute_in_custom_runtime
localstack    |     result,
localstack    | 
localstack    | 2021-09-22T00:10:43:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:WebsocketLambda: Lambda process returned error status code: 1. Result: . Output:
localstack    | /tmp/localstack/zipfile.d6919b72/handler.js:13
localstack    |     callback(null, result);
localstack    |     ^
localstack    | 
localstack    | TypeError: callback is not a function
localstack    |     at Object.exports.handler (/tmp/localstack/zipfile.d6919b72/handler.js:13:5)
localstack    |     at [eval]:1:56
localstack    |     at Script.runInThisContext (vm.js:134:12)
localstack    |     at Object.runInThisContext (vm.js:310:38)
localstack    |     at internal/process/execution.js:81:19
localstack    |     at [eval]-wrapper:6:22
localstack    |     at evalScript (internal/process/execution.js:80:60)
localstack    |     at internal/main/eval_string.js:27:3 Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 840, in run_lambda
localstack    |     lock_discriminator=lock_discriminator,
localstack    |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/awslambda/lambda_extended.py", line 529, in execute_local_executor
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 346, in execute
localstack    |     return do_execute()
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 336, in do_execute
localstack    |     return _run(func_arn=func_arn)
localstack    |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 157, in wrapped
localstack    |     raise e
localstack    |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 153, in wrapped
localstack    |     result = func(*args, **kwargs)
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 323, in _run
localstack    |     raise e
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 309, in _run
localstack    |     result = self._execute(func_arn, func_details, event, context, version)
localstack    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1114, in _execute
localstack    |     raise InvocationException(result, log_output)
localstack    | localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned error status code: 1. Result: . Output:
localstack    | /tmp/localstack/zipfile.d6919b72/handler.js:13
localstack    |     callback(null, result);
localstack    |     ^
localstack    | 
localstack    | TypeError: callback is not a function
localstack    |     at Object.exports.handler (/tmp/localstack/zipfile.d6919b72/handler.js:13:5)
localstack    |     at [eval]:1:56
localstack    |     at Script.runInThisContext (vm.js:134:12)
localstack    |     at Object.runInThisContext (vm.js:310:38)
localstack    |     at internal/process/execution.js:81:19
localstack    |     at [eval]-wrapper:6:22
localstack    |     at evalScript (internal/process/execution.js:80:60)
localstack    |     at internal/main/eval_string.js:27:3
```

### Environment

```markdown
- OS: MacOS with Docker
- LocalStack: latest
```

### Anything else?

I've debugged and found the problem happens when using synchronous handler function (https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html)

**Comment by pinzon** [comment]
Hi @wesleymilan.  I've been trying to find a solution to this issue for while after assigning it to me, from the start the problem was reproducable. But This should be working since an integration tests uses it.

The solution I found to this was to **run first the lambda with nodejs8.10 specifically** and then run it in the desired version .

Hopefully this will fix it for you too.  I'll keep this issue open for a while.
