### ISSUE TITLE
bug: Error thrown when S3 object deletion event is triggered

### ISSUE THREAD

**Issue by tobilg** [localstack/localstack#4639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to delete a key in a bucket with activated S3 Event Notifications, an error is thrown:

```bash
localstack  | 2021-09-22T14:01:35:INFO:localstack.utils.run: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7f955e7238c0>(None) failed: 'NoneType' object has no attribute 'get' Traceback (most recent call last):
localstack  |   File "/opt/code/localstack/localstack/utils/run.py", line 150, in run
localstack  |     result = self.func(self.params, **kwargs)
localstack  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
localstack  |     return fn(*args, **kwargs)
localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 521, in handler
localstack  |     server_address=parsed_url.netloc,
localstack  |   File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 139, in modify_and_forward
localstack  |     method, path, data_bytes=data_bytes, headers=headers, *args, **kwargs
localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 306, in modify_and_forward
localstack  |     method=method, path=path, data=data, headers=headers
localstack  |   File "/opt/code/localstack/localstack/services/edge.py", line 167, in forward_request
localstack  |     return do_forward_request(api, method, path, data, headers, port=port)
localstack  |   File "/opt/code/localstack/localstack/services/edge.py", line 195, in do_forward_request
localstack  |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack  |   File "/opt/code/localstack/localstack/services/edge.py", line 227, in do_forward_request_inmem
localstack  |     server_address=server_address,
localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 381, in modify_and_forward
localstack  |     updated_response = update_listener.return_response(**kwargs)
localstack  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1521, in return_response
localstack  |     fix_delete_objects_response(bucket_name, method, parsed, data, headers, response)
localstack  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 651, in fix_delete_objects_response
localstack  |     errors = result.get("Error")
localstack  | AttributeError: 'NoneType' object has no attribute 'get'
```

### Expected Behavior

No error is thrown when a key in a bucket is deleted.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
# Create S3 Bucket
aws --endpoint-url=http://localhost:4566 s3 mb s3://test-bucket

# Create incoming events SQS Queue
aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name incoming-events

# Create S3 Bucket Event Notification
aws --endpoint-url=http://localhost:4566 s3api put-bucket-notification-configuration --bucket test-bucket --notification-configuration '{"QueueConfigurations":[{"QueueArn":"arn:aws:sqs:eu-central-1:000000000000:incoming-events","Events":["s3:ObjectCreated:*","s3:ObjectRemoved:*"]}]}'
```

### Environment

```markdown
- OS: MacOS Big Sur
- LocalStack: latest Docker image
```

**Comment by tobilg** [comment]
I ran this with `LS_LOG=trace`, and this is the last AWS SDK call log before the error is thrown:

```bash
localstack  | 2021-09-23T08:09:22:DEBUG:localstack.services.edge: IN(s3): "POST /test-bucket?delete" - headers: {'Remote-Addr': '172.24.0.1', 'User-Agent': 'aws-sdk-nodejs/2.944.0 darwin/v12.20.1 promise', 'Content-Type': 'application/octet-stream', 'Content-Md5': 'aRmiGoB8C72au3G6rzB+qQ==', 'Content-Length': '57', 'Host': 'localhost:4566', 'X-Amz-Content-Sha256': 'UNSIGNED-PAYLOAD', 'X-Amz-Date': '20210923T080922Z', 'X-Amz-Security-Token': 'READACTED', 'Authorization': 'AWS4-HMAC-SHA256 Credential=REDACTED/20210923/eu-central-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=f9f085c9a5749bfd444137960e8dec92541e70cc4fbc120528d3135e673a6c27', 'Connection': 'keep-alive', 'X-Forwarded-For': '172.24.0.1, localhost:4566', 'x-localstack-edge': 'https://localhost:4566'} - data: b'<Delete xmlns="http://s3.amazonaws.com/doc/2006-03-01/"/>'
```

My application throws the following error:

```bash
XMLParserError: Non-whitespace before first tag.
    Line: 0
    Column: 1
    Char: {

      at error (node_modules/sax/lib/sax.js:667:10)
      at strictFail (node_modules/sax/lib/sax.js:693:7)
      at beginWhiteSpace (node_modules/sax/lib/sax.js:967:7)
      at SAXParser.write (node_modules/sax/lib/sax.js:1019:11)
      at Parser.Object.<anonymous>.exports.Parser.Parser.parseString (node_modules/xml2js/lib/parser.js:322:31)
      at Parser.parseString (node_modules/xml2js/lib/parser.js:5:59)
      at NodeXmlParser.Object.<anonymous>.NodeXmlParser.parse (node_modules/aws-sdk/lib/xml/node_parser.js:31:10)
      at Request.extractError (node_modules/aws-sdk/lib/services/s3.js:700:39)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (node_modules/aws-sdk/lib/sequential_executor.js:78:10
```

**Comment by naspeh** [comment]
Hi @tobilg, I'm trying to reproduce the issue with these commands:
```sh
awslocal s3 mb s3://test-bucket
awslocal sqs create-queue --queue-name incoming-events
awslocal s3api put-bucket-notification-configuration --bucket test-bucket --notification-configuration '{"QueueConfigurations":[{"QueueArn":"arn:aws:sqs:eu-central-1:000000000000:incoming-events","Events":["s3:ObjectCreated:*","s3:ObjectRemoved:*"]}]}'
touch /tmp/test.txt
awslocal s3 cp /tmp/test.txt s3://test-bucket/test.txt
awslocal s3 rm s3://test-bucket/test.txt
awslocal sqs receive-message --queue-url=http://localhost:4566/000000000000/incoming-events
awslocal sqs receive-message --queue-url=http://localhost:4566/000000000000/incoming-events
```
It works and I get output like this:
```
make_bucket: test-bucket
{
    "QueueUrl": "http://localhost:4566/000000000000/incoming-events"
}
upload: ../../../tmp/test.txt to s3://test-bucket/test.txt
delete: s3://test-bucket/test.txt
{
    "Messages": [
        {
            "MessageId": "e827b2f4-0ea5-12de-1de4-8d09ec5047b8",
            "ReceiptHandle": "dbsfeamdcldzsxzhnbnjafvzbnjgsvnrwxhyxiqakdvgofdehccyasrgjeswbicggqumquzjviosmnwmbkaamlqorxnsirxrtvxpwrwqfjtsirqsdzxzsepcauvxhfonmwpeujzogrueqehhgztqkwbcqnuaeqeqnvrgwxjyefzcuqfrpflabachh",
            "MD5OfBody": "87f51989c5e9156b518f388a4a6ceabc",
            "Body": "{\"Records\": [{\"eventVersion\": \"2.1\", \"eventSource\": \"aws:s3\", \"awsRegion\": \"eu-central-1\", \"eventTime\": \"2021-11-16T08:39:04.698Z\", \"eventName\": \"ObjectCreated:Put\", \"userIdentity\": {\"principalId\": \"AIDAJDPLRKLG7UEXAMPLE\"}, \"requestParameters\": {\"sourceIPAddress\": \"127.0.0.1\"}, \"responseElements\": {\"x-amz-request-id\": \"9a00b12e\", \"x-amz-id-2\": \"eftixk72aD6Ap51TnqcoF8eFidJG9Z/2\"}, \"s3\": {\"s3SchemaVersion\": \"1.0\", \"configurationId\": \"testConfigRule\", \"bucket\": {\"name\": \"test-bucket\", \"ownerIdentity\": {\"principalId\": \"A3NL1KOZZKExample\"}, \"arn\": \"arn:aws:s3:::test-bucket\"}, \"object\": {\"key\": \"test.txt\", \"size\": 0, \"eTag\": \"\\\"d41d8cd98f00b204e9800998ecf8427e\\\"\", \"versionId\": null, \"sequencer\": \"0055AED6DCD90281E5\"}}}]}"
        }
    ]
}
{
    "Messages": [
        {
            "MessageId": "3b245471-1ec3-68c5-4174-7c16cd10dce0",
            "ReceiptHandle": "unjlszbziozmeavmiyroltjkynyslfzhaycvsijgsvygbtkvnaarcqdecdfatndhvdeutzrpjjodwqcostkajabbbksmkbchnvedstqawziwabctsyxpnulbpsajhbsexbopjxzyyzopbezbntihenixvzhftsuojwoonzyvgvrnianlpfhszlbee",
            "MD5OfBody": "a7496d55d63de4cc3de2624bafacf16c",
            "Body": "{\"Records\": [{\"eventVersion\": \"2.1\", \"eventSource\": \"aws:s3\", \"awsRegion\": \"eu-central-1\", \"eventTime\": \"2021-11-16T08:39:05.118Z\", \"eventName\": \"ObjectRemoved:Delete\", \"userIdentity\": {\"principalId\": \"AIDAJDPLRKLG7UEXAMPLE\"}, \"requestParameters\": {\"sourceIPAddress\": \"127.0.0.1\"}, \"responseElements\": {\"x-amz-request-id\": \"d589658f\", \"x-amz-id-2\": \"eftixk72aD6Ap51TnqcoF8eFidJG9Z/2\"}, \"s3\": {\"s3SchemaVersion\": \"1.0\", \"configurationId\": \"testConfigRule\", \"bucket\": {\"name\": \"test-bucket\", \"ownerIdentity\": {\"principalId\": \"A3NL1KOZZKExample\"}, \"arn\": \"arn:aws:s3:::test-bucket\"}, \"object\": {\"key\": \"test.txt\", \"size\": 0, \"eTag\": \"\", \"versionId\": null, \"sequencer\": \"0055AED6DCD90281E5\"}}}]}"
        }
    ]
}
```

Could you please run these commands locally? Do you still see the error?

----

I have tested with the latest version 
```
$ LS_LOG=trace DEBUG=1 localstack start
...
LocalStack version: 0.12.20
LocalStack Docker container id: 34a533a65080
LocalStack build date: 2021-11-14
LocalStack build git hash: cd464b91
...
```

and the `0.12.19.1`
```
$ LS_LOG=trace DEBUG=1 IMAGE_NAME=localstack/localstack:0.12.19.1 localstack start
...
LocalStack version: 0.12.19.1
LocalStack Docker container id: 05a5055aa578
LocalStack build date: 2021-10-18
LocalStack build git hash: dcbb4900
...
```

**Comment by naspeh** [comment]
Hi @tobilg, I could reproduce the server error like you shared by deleting objects from the non-existing bucket. I have prepared the fix here https://github.com/localstack/localstack/pull/4948

**Comment by tobilg** [comment]
Thank you very much @naspeh for the find and the upcoming fix!

**Comment by naspeh** [comment]
@tobilg thank you for reporting, I'm going to close this issue. Please try the latest docker image `localstack/localstack:latest` with the mentioned fix. Let me know if you still can reproduce the issue from the description.
