### ISSUE TITLE
bug: Not able to create an appsync Graphql api using cdklocal

### ISSUE THREAD

**Issue by magallegos1996** [localstack/localstack#4645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've created a new cdk project using aws cdk cli. Then I created the following code in the main file under the `lib` folder

```
import * as iam from "@aws-cdk/aws-iam";
import * as cdk from "@aws-cdk/core";
import * as appsync from "@aws-cdk/aws-appsync";
import * as lambda from "@aws-cdk/aws-lambda";
import * as ec2 from "@aws-cdk/aws-ec2";
import * as neptune from "@aws-cdk/aws-neptune";

export class CdkLocalStack extends cdk.Stack {
  constructor(scope: cdk.App, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const api = new appsync.GraphqlApi(this, 'ApiLocal', {
      name: 'NeptuneAPILocal',
      schema: appsync.Schema.fromAsset("graphql/schema.graphql"),
    });
  }
}
```

The api is created. However, I'm receiving this error (something related with the` API_KEY`):

```
localstack_1  | 2021-09-24T15:10:55:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "ApiLocalDefaultApiKeyC7FB0002" (1/2) type "AWS::AppSync::ApiKey" in loop iteration 1
localstack_1  | 2021-09-24T15:10:55:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "AppSync::ApiKey" id "ApiLocalDefaultApiKeyC7FB0002"
localstack_1  | 2021-09-24T15:10:55:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "AppSync::ApiKey" in region us-east-2: create_api_key {'apiId': 'ca067b1f'}
localstack_1  | 2021-09-24T15:10:55:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: AppSync::ApiKey PhysicalResourceId
localstack_1  | 2021-09-24T15:10:56:DEBUG:localstack.utils.cloudformation.template_deployer: Dependencies for "ApiLocalDefaultApiKeyC7FB0002" not yet satisfied, retrying in next loop: Unable to fetch details for resource "ApiLocalDefau
ltApiKeyC7FB0002" (attribute "PhysicalResourceId")
localstack_1  | 2021-09-24T15:10:56:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
localstack_1  | 2021-09-24T15:10:56:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "CDKMetadata" (2/2) type "AWS::CDK::Metadata" in loop iteration 1
localstack_1  | 2021-09-24T15:10:56:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "ApiLocalDefaultApiKeyC7FB0002" (1/1) type "AWS::AppSync::ApiKey" in loop iteration 2
localstack_1  | 2021-09-24T15:10:56:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "AppSync::ApiKey" id "ApiLocalDefaultApiKeyC7FB0002"
localstack_1  | 2021-09-24T15:10:56:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "AppSync::ApiKey" in region us-east-2: create_api_key {'apiId': 'ca067b1f'}
localstack_1  | 2021-09-24T15:10:56:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: AppSync::ApiKey PhysicalResourceId
localstack_1  | 2021-09-24T15:10:56:DEBUG:localstack.utils.cloudformation.template_deployer: Dependencies for "ApiLocalDefaultApiKeyC7FB0002" not yet satisfied, retrying in next loop: Unable to fetch details for resource "ApiLocalDefau
ltApiKeyC7FB0002" (attribute "PhysicalResourceId")
localstack_1  | 2021-09-24T15:10:56:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "CdkLocalStack": Resource deployment loop completed, pending resource changes: [{'Type': 'Reso
urce', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'ApiLocalDefaultApiKeyC7FB0002', 'PhysicalResourceId': None, 'ResourceType': 'AWS::AppSync::ApiKey', 'Replacement': 'False', 'ChangeSetId': None}}] Traceback (most recent
call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1682, in _run
localstack_1  |     self.do_apply_changes_in_loop(changes, stack, stack_name)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1767, in do_apply_changes_in_loop
localstack_1  |     "Resource deployment loop completed, pending resource changes: %s" % changes
localstack_1  | Exception: Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'ApiLocalDefaultApiKeyC7FB0002', 'PhysicalResourceId': None, 'Resou
rceType': 'AWS::AppSync::ApiKey', 'Replacement': 'False', 'ChangeSetId': None}}]
localstack_1  |
```

An this are the logs for `cdkdeploy`

```
90/296 |21:54:29 | CREATE_FAILED        | AWS::CloudFormation::Stack            | CdkLocalStack

Failed resources:

 ❌  CdkLocalStack failed: Error: The stack named CdkLocalStack failed to deploy: CREATE_FAILED (Deployment failed)
    at Object.waitForStackDeploy (C:\Users\Marcelo\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\util\cloudformation.ts:307:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at prepareAndExecuteChangeSet (C:\Users\Marcelo\AppData\Roaming\npm\node_modules\aws-cdk\lib\api\deploy-stack.ts:342:26)
    at CdkToolkit.deploy (C:\Users\Marcelo\AppData\Roaming\npm\node_modules\aws-cdk\lib\cdk-toolkit.ts:189:24)
    at initCommandLine (C:\Users\Marcelo\AppData\Roaming\npm\node_modules\aws-cdk\bin\cdk.ts:225:9)
The stack named CdkLocalStack failed to deploy: CREATE_FAILED (Deployment failed)
```

### Expected Behavior

When executing `cdklocal deploy` the AppSync Graphql query creates the api and creates the stack without errors.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

```
version: '2.1'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4510-4530:4510-4530"
      - "127.0.0.1:4566-4620:4566-4620"
    environment:
      - LOCALSTACK_API_KEY=xxx
      - SERVICES=serverless,cognito,rds,cloudformation,appsync,ec2,sqs,neptune
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LAMBDA_EXECUTOR=docker
      - DEFAULT_REGION=us-east-2
      - MAIN_CONTAINER_NAME=aws_backend_stack_main
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### Environment

```markdown
TMPDIR=C:\Users\Marcelo\AppData\Local\Temp
```

**Comment by whummer** [comment]
Thanks for reporting @magallegos1996 . This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!
