### ISSUE TITLE
bug: Localstack Pods - Git backend broken

### ISSUE THREAD

**Issue by Tobolov** [localstack/localstack#4649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems that the git backend for pods is currently broken. When going to push a cloudpod using the git backend for the first time, I received the bellow exception. The managed backend works without issue.

```
Checking out 525becda6c2e7b5202f63d3a0c017806d2dbcaf1
Push to ssh://git@bitbucket.org/<removed>/<removed>.git successful.
Ref refs/heads/master updated
Traceback (most recent call last):
  File "/home/tobolov/.local/bin/localstack", line 23, in <module>
    main()
  File "/home/tobolov/.local/bin/localstack", line 19, in main
    main.main()
  File "/home/tobolov/.local/lib/python3.8/site-packages/localstack/cli/main.py", line 6, in main
    cli()
  File "/home/tobolov/.local/lib/python3.8/site-packages/localstack/cli/plugin.py", line 16, in __call__
    self.group(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/tobolov/.local/lib/python3.8/site-packages/localstack_ext/cli/localstack.py", line 102, in cmd_pod_push
    pods_client.push_state(name,lwpNv)
  File "/home/tobolov/.local/lib/python3.8/site-packages/localstack_ext/bootstrap/pods_client.py", line 308, in push_state
    pod_config["size"]=pod_info.pod_size or pod_info.pod_size_compressed
AttributeError: 'NoneType' object has no attribute 'pod_size'
```

### Expected Behavior

The pod is pushed successfully to git and the command exits with status code 0 gracefully.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose.yml:

```yml
version: "3.8"

services:
  localstack:
    container_name: "localstack-a"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:5001:5001"
      - "127.0.0.1:5002:5002"
      - "127.0.0.1:5003:5003"
    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack-data
      - LOCALSTACK_API_KEY=<removed>
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack/
      - SERVICE_INSTANCES_PORTS_START=5000
      - SERVICE_INSTANCES_PORTS_END=5003
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/localstack-data:/tmp/localstack-data"
```

1. Run the docker compose file as above
2.  Set DATA_DIR, EDGE_PORT, and LOCALSTACK_API_KEY
3. localstack login
4. localstack pod push test

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 
LocalStack build git hash: af13fb23
LocalStack build date: 2021-09-13
LocalStack version: 0.12.17.5

- Pip Package Versions (Cli):
localstack             0.12.18
localstack-client      1.25
localstack-ext         0.12.17.7
```

### Anything else?

I had a poke around bootstrap/pods_client.py in localstack-ext, and it looks like CloudPodManagerGit isn't returning PodInfo at the end of the function call.

**Comment by whummer** [comment]
Thanks for reporting @Tobolov . This should be fixed in the meantime - can you please upgrade to the latest version of the CLI and give it another try:
```
pip install --upgrade localstack localstack-ext
```
Hope that helps - please let us know if the problem persists. Thanks for your help!
