### ISSUE TITLE
question: make docker-build not working throwing all kind of error messages

### ISSUE THREAD

**Issue by manas86** [localstack/localstack#4680]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I categorize this as a question instead of a bug. (or maybe it's a bug)
I hope this is not a bug and my workstation is Mac. 
As per the documentation, I have cloned the repo, and then I tried to build the docker image using the command 
`make docker-build` 
I'm getting the below error at the location for the dockerfile: 
Is there any way to fix this issue? 
```
RUN LAMBDA_EXECUTOR=local \
    PYTEST_LOGLEVEL=info \
    PYTEST_ARGS='--junitxml=target/test-report.xml' \
    make test-coverage
```
```
#40 11.31 LocalStack version: 0.12.15
#40 11.52 LocalStack build date: 2021-10-01
#40 11.52 LocalStack build git hash: 8240d0a
#40 11.52 
#40 11.63 Unable to register plugins: cannot import name 'undo_clean_key_name' from 'moto.s3.responses' (/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py)
#40 11.63 WARNING  bootstrap.py:bootstrap.py:154 Unable to load plugins from file /opt/code/localstack/localstack/plugins.py: cannot import name 'undo_clean_key_name' from 'moto.s3.responses' (/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py)
#40 16.94 INFO     localstack.utils.analytics.profiler:profiler.py:174 Execution of "start_api_services" took 5017.02ms
#40 16.94 Ready.
#40 17.82 INFO     tests.integration.test_elasticsearch:test_elasticsearch.py:44 installing elasticsearch
#40 17.82 INFO     tests.integration.conftest:conftest.py:154 waiting for infra to be ready
#40 17.82 INFO     tests.integration.conftest:conftest.py:158 waiting for shutdown
#40 17.82 INFO     tests.integration.conftest:conftest.py:160 waiting for watchdog to join
#40 18.07 
#40 18.07 ==================================== ERRORS ====================================
#40 18.07 ____________________ ERROR collecting tests/unit/test_s3.py ____________________
#40 18.07 ImportError while importing test module '/opt/code/localstack/tests/unit/test_s3.py'.
#40 18.07 Hint: make sure your test modules/packages have valid Python names.
#40 18.07 Traceback:
#40 18.07 /usr/lib/python3.7/importlib/__init__.py:127: in import_module
#40 18.07     return _bootstrap._gcd_import(name[level:], package, level)
#40 18.07 tests/unit/test_s3.py:10: in <module>
#40 18.07     from localstack.services.s3 import multipart_content, s3_listener, s3_starter, s3_utils
#40 18.07 localstack/services/s3/s3_starter.py:10: in <module>
#40 18.07     from moto.s3.responses import (
#40 18.07 E   ImportError: cannot import name 'undo_clean_key_name' from 'moto.s3.responses' (/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py)
#40 18.07 ------- generated xml file: /opt/code/localstack/target/test-report.xml --------
#40 18.07 =========================== short test summary info ============================
#40 18.07 ERROR tests/unit/test_s3.py
#40 18.07 !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
#40 18.07 ============================== 1 error in 15.53s ===============================
#40 18.46 make: *** [Makefile:150: test-coverage] Error 2
```

### Anything else?

after getting this error: I tried below options: 
1) I ran `make install ` to make sure all the dependencies are installed prior docker-build, however, this throws me an error:  for package `amazon-kclpy-ext` 
2)After this I commented the `test-coverage`   and build the docker image using `make docker-build` , it build successfully however, after building the image when I refer that same image to the docker-compose then I'm getting all kind of nasty errors: 
```
localstack                  | Traceback (most recent call last):
localstack                  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
localstack                  |     timeout=timeout
localstack                  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
localstack                  |     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
localstack                  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
localstack                  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
localstack                  | urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='localhost', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1e127e9150>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack                  | 
localstack                  | During handling of the above exception, another exception occurred:
localstack                  | 
localstack                  | Traceback (most recent call last):
localstack                  |   File "/opt/code/localstack/localstack/utils/cli.py", line 218, in main
localstack                  |     subcommand["function"](argv, args)
localstack                  |   File "/opt/code/localstack/localstack/utils/cli.py", line 72, in cmd_infra
localstack                  |     start_infra_locally()
localstack                  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 412, in start_infra_locally
localstack                  |     return infra.start_infra()
localstack                  |   File "/opt/code/localstack/localstack/services/infra.py", line 460, in start_infra
localstack                  |     raise e
localstack                  |   File "/opt/code/localstack/localstack/services/infra.py", line 446, in start_infra
localstack                  |     thread = do_start_infra(asynchronous, apis, is_in_docker)
localstack                  |   File "/opt/code/localstack/localstack/services/infra.py", line 537, in do_start_infra
localstack                  |     thread = start_api_services()
localstack                  |   File "/opt/code/localstack/localstack/utils/analytics/profiler.py", line 168, in wrapped
localstack                  |     return f(*args, **kwargs)
localstack                  |   File "/opt/code/localstack/localstack/services/infra.py", line 529, in start_api_services
localstack                  |     persistence.restore_persisted_data(apis=apis)
localstack                  |   File "/opt/code/localstack/localstack/utils/persistence.py", line 196, in restore_persisted_data
localstack                  |     replay("_all_")
localstack                  |   File "/opt/code/localstack/localstack/utils/persistence.py", line 185, in replay
localstack                  |     replay_command(command)
localstack                  |   File "/opt/code/localstack/localstack/utils/persistence.py", line 169, in replay_command
localstack                  |     response = function(full_url, data=data, headers=headers, verify=False)
localstack                  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/api.py", line 119, in post
localstack                  |     return request('post', url, data=data, json=json, **kwargs)
localstack                  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/api.py", line 61, in request
localstack                  |     return session.request(method=method, url=url, **kwargs)
localstack                  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
localstack                  |     resp = self.send(prep, **send_kwargs)
localstack                  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
localstack                  |     r = adapter.send(request, **kwargs)
localstack                  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
localstack                  |     raise ConnectionError(e, request=request)
localstack                  | requests.exceptions.ConnectionError: MyHTTPConnectionPool(host='localhost', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1e127e9150>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack                  | 
localstack                  | ERROR: MyHTTPConnectionPool(host='localhost', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1e127e9150>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack                  | (. .venv/bin/activate; exec bin/localstack start --host)
localstack                  | 2021-10-01T10:35:03:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 5005.11ms
localstack                  | 2021-10-01T10:35:03:DEBUG:localstack.services.infra: [shutdown] Cleaning up files ...
localstack                  | 2021-10-01T10:35:03:DEBUG:localstack.services.infra: [shutdown] Cleaning up resources ...
localstack                  | 2021-10-01T10:35:03:DEBUG:localstack.utils.common: [shutdown] Done cleaning up threads / processes / tasks
localstack                  | 2021-10-01T10:35:03:DEBUG:localstack.services.infra: [shutdown] Cleaning up Lambda resources ...
localstack                  | 2021-10-01T10:35:03:DEBUG:localstack.services.infra: [shutdown] Force shutdown, not waiting for infrastructure to shut down
localstack                  | make: *** [Makefile:57: infra] Error 1
localstack                  | Starting local dev environment. CTRL-C to quit.
localstack                  | 2021-10-01 10:35:05,690 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack                  | Waiting for all LocalStack services to be ready
```

**Comment by manas86** [comment]
I tried to fix the issue, it seems moto lib has changed `undo_clean_key_name` to `clean_key_name` and the same goes for `copy_key` which is now `copy_object`. so after changing these names in s3_starter.py, I moved past the error however now I'm getting an error for the integration test for api.  Is it fine to omit the test completely and move on directly build and use that local build image to your docker-compose?

**Comment by whummer** [comment]
Thanks for reporting @manas86 . There should not be a need to build the Docker image as a user (unless you're developing on LocalStack). 

We recommend referencing the pre-built `localstack/localstack:latest` image directly in your docker-compose config - this image is automatically built and pushed by our CI pipeline and is always up-to-date with the latest changes on the `master` branch in this repo. 

Hope that helps - please keep us posted how it goes.. Thanks!
