### ISSUE TITLE
StepFunctions can't start on mac M1 (confirmed ok on intel MAC)

### ISSUE THREAD

**Issue by nghia11110** [localstack/localstack#4697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- docker-compose
```
version: "3.8"

services:
  localstack:
    container_name: AWS-DEVELOPMENT-WITH-LOCALSTACK
    image: localstack/localstack:0.12.18
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=stepfunctions
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=xxxxxx
      - HOST_TMP_FOLDER=./.localstack
    volumes:
      - './.localstack:/tmp/localstack'
      - "/var/run/docker.sock:/var/run/docker.sock"
```
-  starting log
```
Exception in thread "main" java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in authority at index 8: https://emr-containers.{region}.{dnsSuffix}
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.internal.DefaultServiceEndpointBuilder.toURI(DefaultServiceEndpointBuilder.java:75)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.internal.DefaultServiceEndpointBuilder.getServiceEndpoint(DefaultServiceEndpointBuilder.java:63)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.AmazonWebServiceClient.setRegion(AmazonWebServiceClient.java:525)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:456)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.dagger.ClientModule.emrContainersClient(ClientModule.java:333)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.dagger.ClientModule_EmrContainersClientFactory.get(ClientModule_EmrContainersClientFactory.java:37)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.dagger.ClientModule_EmrContainersClientFactory.get(ClientModule_EmrContainersClientFactory.java:11)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.runtime.executors.task.external.emrcontainers.DescribeVirtualCluster_Factory.get(DescribeVirtualCluster_Factory.java:38)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.runtime.executors.task.external.emrcontainers.DescribeVirtualCluster_Factory.get(DescribeVirtualCluster_Factory.java:11)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.runtime.executors.task.external.Service_Factory.get(Service_Factory.java:400)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.runtime.executors.task.external.Service_Factory.get(Service_Factory.java:57)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.dagger.ConnectorModule_WorkflowValidatorFactory.get(ConnectorModule_WorkflowValidatorFactory.java:30)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.dagger.ConnectorModule_WorkflowValidatorFactory.get(ConnectorModule_WorkflowValidatorFactory.java:10)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.operation.CreateStateMachine_Factory.get(CreateStateMachine_Factory.java:53)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.operation.CreateStateMachine_Factory.get(CreateStateMachine_Factory.java:13)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.http.RequestHandlers_Factory.get(RequestHandlers_Factory.java:151)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.http.RequestHandlers_Factory.get(RequestHandlers_Factory.java:29)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.http.HttpRequestHandlers_Factory.get(HttpRequestHandlers_Factory.java:30)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.http.HttpRequestHandlers_Factory.get(HttpRequestHandlers_Factory.java:9)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.http.HttpServer_Factory.get(HttpServer_Factory.java:27)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.http.HttpServer_Factory.get(HttpServer_Factory.java:8)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.dagger.DaggerSfnLocalComponent.httpServer(DaggerSfnLocalComponent.java:1242)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.StepFunctionsLocal.server(StepFunctionsLocal.java:57)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.StepFunctionsLocal.start(StepFunctionsLocal.java:73)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.StepFunctionsLocal.start(StepFunctionsLocal.java:65)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.stepfunctions.local.Launcher.main(Launcher.java:15)
AWS-DEVELOPMENT-WITH-LOCALSTACK | Caused by: java.net.URISyntaxException: Illegal character in authority at index 8: https://emr-containers.{region}.{dnsSuffix}
AWS-DEVELOPMENT-WITH-LOCALSTACK | at java.base/java.net.URI$Parser.fail(Unknown Source)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at java.base/java.net.URI$Parser.parseAuthority(Unknown Source)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at java.base/java.net.URI$Parser.parseHierarchical(Unknown Source)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at java.base/java.net.URI$Parser.parse(Unknown Source)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at java.base/java.net.URI.<init>(Unknown Source)
AWS-DEVELOPMENT-WITH-LOCALSTACK | at com.amazonaws.internal.DefaultServiceEndpointBuilder.toURI(DefaultServiceEndpointBuilder.java:73)
AWS-DEVELOPMENT-WITH-LOCALSTACK | ... 34 more
```
- "services": {"stepfunctions": "running"} is shown at http://localhost:4566/health but awscli has 500 error:
```
aws stepfunctions --endpoint http://localhost:4566 list-state-machines
An error occurred (500) when calling the ListStateMachines operation (reached max retries: 2)
```

### Expected Behavior

stepfunctions up and work fine

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose up
aws stepfunctions --endpoint http://localhost:4566 list-state-machines

### Environment

```markdown
- OS: macOS Big Sur 11.4 (M1)
- LocalStack: 0.12.18
```

**Comment by thujikun** [comment]
Any update?

**Comment by alexrashed** [comment]
Hi @nghia11110! We just released 0.13, where we are now providing a native arm64 image. This issue might be fixed with the native image. Could you give it a try and tell us if it works with 0.13? Thanks!

**Comment by nghia11110** [comment]
@alexrashed thank you so much. I will check and feedback to you soon!

**Comment by nghia11110** [comment]
@alexrashed now working as expected with Localstack 0.13.0
thanks for your support
