### ISSUE TITLE
question: How do I pull a LocalStack image from like five days ago, whereas localstack/localstack image is always tagged as "latest"?

### ISSUE THREAD

**Issue by DVader666** [localstack/localstack#4708]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

**How do I pull a LocalStack image from like five days ago, whereas localstack/localstack image is always tagged as "latest"?**

I'm having an issue with our current project where we deploy to LocalStack (and later to AWS) via Serverless Framework. Using the same SLS template and project files (basically NodeJS code and some JSON models), I have different team members with different results when triggering the SLS deploy. People with a LocalStack image from five days ago don't have any issues. But for people with latest LocalStack image (from today), the exact same deploy fails with something like:

```
2021-10-06T22:21:38:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "local-whatever-stack": 'properties' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1485, in _run
    self.do_apply_changes_in_loop(changes, stack, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1518, in do_apply_changes_in_loop
    existing_resources=new_resources,
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1129, in add_default_resource_props
    resource_class.add_defaults(resource, stack_name)
  File "/opt/code/localstack/localstack/services/cloudformation/models/apigateway.py", line 63, in add_defaults
    role_name = resource["properties"].get("Name")
KeyError: 'properties'
```
For the team members where our SLS deployment is successful, the LocalStack version and build read as:

```
LocalStack version: 0.12.18
LocalStack Docker container id: 65df8c5709ed
LocalStack build date: 2021-10-01
LocalStack build git hash: 69dd7992
```

For the team member where the same SLS deployment fails with the mentioned issue, the LocalStack version and build read as:

```
LocalStack version: 0.12.18
LocalStack Docker container id: bb70217f8621
LocalStack build date: 2021-10-06
LocalStack build git hash: 487e80ce
```

The LocalStack build version is the only thing I found to be different between the two scenarios ("deployment works vs. deployment does not work"). I'd like to be able to pull a previous LocalStack image, both to reproduce the "working" scenario conditions and also to move forward with our project.

**Comment by DVader666** [comment]
Further research shows the issue is specific to API gateway endpoints (http events in Serverless framework template terms) with defined path request parameters, like for example:

```
functions:
    hello:
        handler: handler.hello
        events:
            - http:
                path: test/api/{id}
                method: post
                request:
                    parameters:
                        paths:
                            id: true
```
As previously described, deployment for something like the above sample was working OK. After updating LocalStack yesterday, the deployment fails.
