### ISSUE TITLE
Error sending event to eventbus

### ISSUE THREAD

**Issue by lorenzozamponi** [localstack/localstack#4724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using localstack:latest docker image with deployed eventbus (tried with custom and default), trying to send new event:

```
[
  {
    "Source": "test",
    "Time": "2021-10-05T17:17:48Z",
    "Detail": "{ \"test\": \"test\"}",
    "Resources": [],
    "DetailType": "Test"
  }
]
```
with aws command cli command:
**awslocal events put-events --entries file://test.json --cli-binary-format raw-in-base64-out --region eu-west-1**

This is the 500 error response:
```
An error occurred (500) when calling the PutEvents operation (reached max retries: 2): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

Debugging in localstack, there is the following error:

```
Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
localstack_1  |     execute(self.server.app)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute
localstack_1  |     application_iter = app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 273, in __call__
localstack_1  |     return backend_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
localstack_1  |     return self.wsgi_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
localstack_1  |     response = self.handle_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
localstack_1  |     response = self.full_dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
localstack_1  |     rv = self.handle_user_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
localstack_1  |     rv = self.dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
localstack_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 148, in __call__
localstack_1  |     result = self.callback(request, request.url, {})
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 205, in dispatch
localstack_1  |     return cls()._dispatch(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 315, in _dispatch
localstack_1  |     return self.call_action()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 405, in call_action
localstack_1  |     response = method()
localstack_1  |   File "/opt/code/localstack/localstack/services/events/events_starter.py", line 235, in events_handler_put_events
localstack_1  |     process_events(formatted_event, targets)
localstack_1  |   File "/opt/code/localstack/localstack/services/events/events_starter.py", line 131, in process_events
localstack_1  |     arn, changed_event, aws_stack.get_events_target_attributes(target)
localstack_1  |   File "/opt/code/localstack/localstack/utils/aws/aws_stack.py", line 756, in send_event_to_target
localstack_1  |     "Detail": event.get("detail"),
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 386, in _api_call
localstack_1  |     return self._make_api_call(operation_name, kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 678, in _make_api_call
localstack_1  |     api_params, operation_model, context=request_context)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 726, in _convert_to_request_dict
localstack_1  |     api_params, operation_model)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/validate.py", line 319, in serialize_to_request
localstack_1  |     raise ParamValidationError(report=report.generate_report())
localstack_1  | botocore.exceptions.ParamValidationError: Parameter validation failed:
localstack_1  | Invalid type for parameter Entries[0].Detail, value: ...  type: <class 'dict'>, valid types: <class 'str'>
```

(Also tried to send event only with Detail: "test", but got another error).

The event, however, sometimes is received 4 or 5 times (not just one and always with the same generated event id and version) also if this error appears

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal events put-events --entries file://test.json --region eu-west-1

### Environment

```markdown
- OS: 
- LocalStack:
```

**Comment by raul-j** [comment]
I am having a simmilar issue with version 0.14.2

```

2022-04-30T00:37:17.872:INFO:localstack.services.events.events_starter: Unable to send event notification {'version': '0', 'id': 'd5e07ae5-37b6-411f-8fb8-5743ecd2b981', 'detail-type': 'xxxxxxx ... to target {'Id': 'name-id', 'Arn': 'arn:aws:events:my-sqs-queue'}: Parameter validation failed:
Invalid type for parameter Entries[0].Detail, value: **JSON object here**, type: <class 'dict'>, valid types: <class 'str'>
```

**Comment by thrau** [comment]
I tried to reproduce this with a standard `localstack start` but was not able to with the latest image (based on LocalStack 2.3)

```console
 % AWS_ENDPOINT_URL=http://localhost.localstack.cloud:4566 aws events put-events --cli-binary-format base64 --entries file://test.json --region eu-west-1
{
    "FailedEntryCount": 0,
    "Entries": [
        {
            "EventId": "830b992e-f2d2-4895-a5dd-912de03d6b66"
        }
    ]
}
```

Looks like this issue is resolved. Please update localstack to the latest image and update your startup config according to the migration guides. If the issue persists, please open a new issue with updated reproduction instructions.
