### ISSUE TITLE
bug: extra chunk-signature data in s3

### ISSUE THREAD

**Issue by herrlegno** [localstack/localstack#4743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Note: I create this bug as I didn't get an answer in another related [issue](https://github.com/localstack/localstack/issues/98#issuecomment-929993979) (#98).

After restarting localstorage, when I do a S3 getObject of a file, it gives me the file with some extra chunk-signature data. Example: 
```json
1e5;chunk-signature=83a45ce7e9db52171538036b946102068a9f2005c53049b23c63515f1c048fbc
{ "test": "this is a test json" }
0;chunk-signature=bd812928970799e2d5d16a86900629155d7d38aba42ed2dcbc7d6559c364671f
```

### Expected Behavior

The behaviour expected is getting the object without the extra chunk-signature data as it breaks parsing the file after.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

In order to easily reproduce this bug, I've created a [repository](https://github.com/herrlegno/localstack-s3-signature-error).

# Steps:
* Create a s3 bucket named: test
* Run 1º test (the one with (Order(1) decorator)
* After the test has successfully passed, restart the localstack container.
* Run only the "extendsS3Object" (Order(2) decorator) test or download the file "test.json" from s3 through awscli.

The file will look like something like this:
```json
19;chunk-signature=f64cba77c6523187a1448fd7bd9cd739ce9d953c951af6fe34ac787b8b8f60d6
{"foo":"bar"}
0;chunk-signature=fcc672670aab469d7e23cd6eeea9cb5639feca2f065510bcfb77f057bb391c9b
```

### Environment

```markdown
- OS: Pengwin WSL (but also tried in a native ubuntu 20.10)
- LocalStack: latest
- AWS Java S3 Client: 1.11.73
```

**Comment by naspeh** [comment]
Hi @herrlegno, thank you for the detailed description and test repo!

I'm trying to reproduce it, but it works for me for some reasons
```sh
## created bucket
awslocal s3 mb s3://test

## running server with
DATA_DIR=/opt/localstack/data LS_LOG=trace DEBUG=1 localstack start

$ ./gradlew test --stacktrace --tests com.example.demo.DemoApplicationTests*putAndGetToS3

# got output like this
#> Task :test
#Executing test putAndGetToS3() [com.example.demo.DemoApplicationTests] with result: SUCCESS
#
#BUILD SUCCESSFUL in 3s
#4 actionable tasks: 1 executed, 3 up-to-date


## stoped server and started again

$ ./gradlew test --stacktrace --tests com.example.demo.DemoApplicationTests*extendS3Object

# got output like this
#> Task :test
#Executing test extendS3Object() [com.example.demo.DemoApplicationTests] with result: SUCCESS
#
#BUILD SUCCESSFUL in 3s
#4 actionable tasks: 1 executed, 3 up-to-date

## checking also manually
$ aws --endpoint=http://localhost:4566 s3 cp s3://test/test.json /tmp/t
$ cat /tmp/t
#{"bar":"baz","foo":"bar"} 
```

I also checked the code, and we are stripping the  `chunk-signature`: https://github.com/localstack/localstack/blob/ab8d5597d7e7b4caee393b3cbc7ad62f9877763a/localstack/services/s3/s3_listener.py#L852-L868

I need some additional information to properly reproduce it.

----
I test it on Linux with localstack:
```
LocalStack version: 0.12.20
LocalStack Docker container id: c1c6a0f24e3e
LocalStack build date: 2021-11-14
LocalStack build git hash: cd464b91
```

**Comment by herrlegno** [comment]
Thank you @naspeh for answering. I just cloned my repo again and run the same steps as I described and gave me the error.

Could it be that the localstack version you are using is not the same as I am? I put localstack latest one month ago, so maybe could it be already fixed?

I ran `docker images` and it gives me this one: 
`localstack/localstack                                       latest    008340d6fa79   4 weeks ago    817MB`

I don't know how to get all the info you got.

Also ran `./gradlew --version`:

```
------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (AdoptOpenJDK 11.0.11+9)
OS:           Linux 5.10.16.3-microsoft-standard-WSL2 amd64
```

**Comment by naspeh** [comment]
If you run `localstack` using docker: https://github.com/localstack/localstack#using-docker
```
$ docker run --rm -it -p 4566:4566 -p 4571:4571 localstack/localstack
Waiting for all LocalStack services to be ready
2021-11-16 13:15:23,149 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-11-16 13:15:23,153 INFO supervisord started with pid 15
2021-11-16 13:15:24,160 INFO spawned: 'infra' with pid 21
(. .venv/bin/activate; exec bin/localstack start --host --no-banner)
2021-11-16 13:15:25,200 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

LocalStack version: 0.13.0
LocalStack build date: 2021-11-15
LocalStack build git hash: 595eaef0
```
You will see LocalStack version in logs.

To update your `localstack`, this should work
```
docker pull localstack/localstack
``` 

Maybe it is fixed already, please check your version and share it with me for history purposes, and then please try to update `localstack` and run your tests once again.

**Comment by herrlegno** [comment]
I record a brief [video ](https://streamable.com/cfodih) to show the process I'm doing, just in case I'm doing something wrong.

The localstack version I'm currently running is: 
```
LocalStack version: 0.12.18
LocalStack build date: 2021-10-16
LocalStack build git hash: 457506b0
```

**Comment by herrlegno** [comment]
I can't get it working on latest 0.13 release: It just gives this:
```
The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: null)
com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: null), S3 Extended Request ID: null
	at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
	at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at app//com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at app//com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at app//com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at app//com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4137)
	at app//com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1685)
	at app//com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:3249)
	at com.amazonaws.services.s3.AmazonS3$putObject.call(Unknown Source)
	at app//org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at app//org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at app//org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
	at app//com.example.demo.DemoApplicationTests.putAndGetToS3(DemoApplicationTests.groovy:54)
	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.11/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at app//org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at app//org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at app//org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at app//org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base@11.0.11/java.util.ArrayList.forEach(ArrayList.java:1541)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base@11.0.11/java.util.ArrayList.forEach(ArrayList.java:1541)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.11/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

I noticed that if I restart localstack I can't even run the 1st test, it throws same error.

**Comment by naspeh** [comment]
Have you created a `test` bucket once again?

```
aws --endpoint=http://localhost:4566 s3 mb s3://test
```

I'm also trying to reproduce it with `0.12.18` and will check `0.13.0` as well.

Could you please share the `docker-compose` section related to `localstack`?

**Comment by herrlegno** [comment]
Summary after doing some more testing:
* v0.12.18 and 0.12.20 is giving me the extra-chunk signature
* v0.13 is giving me 404 in bucket after restart (created before restart)

Docker-Compose:
```yaml
version: '3.9'
services:
  localstack:
    image: localstack/localstack:0.12.20 # Changed for latest (0.13) and 0.12.18 for previous
    container_name: localstack
    restart: always
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb, s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-west-2
    volumes:
      - ./data/localstack:/tmp/localstack

```

**Comment by herrlegno** [comment]
Thank you @naspeh!

**Comment by naspeh** [comment]
For the history, in my first comment, I was running `localstack start` in docker mode.

I was able to reproduce it by running and stopping `docker` container manually:
```sh
docker run -it -p 4566:4566 -p 4571:4571 -e DATA_DIR=/tmp/localstack/data -e DEBUG=1 -e localstack/localstack:0.12.20
```

**Comment by naspeh** [comment]
Hi @herrlegno, one quick observation, if you try to register and create a trial key https://app.localstack.cloud/ (no credit card is needed) and update your `docker-compose.yaml` with 
```
    environment:
      - LOCALSTACK_API_KEY=<you-key>
```
Your test case should work with `0.12.20`.

If you could try this and confirm it is working, that would be great.

Meanwhile, I'm trying to investigate the root cause of this issue.

**Comment by naspeh** [comment]
Hi @herrlegno,

One note, you should update your `docker-compose.yaml` with `EAGER_SERVICE_LOADING=1` env var, then the persistence mechanism will work on the latest images.
