### ISSUE TITLE
question: Starting localstack without docker installation

### ISSUE THREAD

**Issue by bcv** [localstack/localstack#4748]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I want to start localstack on the host without docker. (For some reasons i dont want to install docker). 
However, if I issue the command 

```localstack start --host```
I get this error 

```
     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 ? LocalStack CLI 0.13.0.dev9

[18:21:35] starting LocalStack in host mode ?                                                                                                                                                                          localstack.py:104
????????????????????????????????????????????????????????????????????????????????????????????? LocalStack Runtime Log (press CTRL-C to quit) ?????????????????????????????????????????????????????????????????????????????????????????????

LocalStack version: 0.13.0.dev9

2021-10-18T18:21:35:INFO:localstack.services.install: Downloading and installing local Step Functions server. This may take some time.
Error starting infrastructure: Docker not available Traceback (most recent call last):
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 369, in start_infra
    thread = do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 474, in do_start_infra
    prepare_installation()
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/utils/bootstrap.py", line 91, in wrapped
    return f(*args, **kwargs)
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 427, in prepare_installation
    install.install_components(apis)
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 474, in install_components
    parallelize(install_component, names)
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/utils/common.py", line 1877, in parallelize
    return pool.map(func, arr)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 470, in install_component
    installer()
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 319, in install_stepfunctions_local
    DOCKER_CLIENT.pull_image(IMAGE_NAME_SFN_LOCAL)
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/utils/docker_utils.py", line 1150, in pull_image
    self.client().images.pull(repository, tag)
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/utils/docker_utils.py", line 1003, in client
    raise ContainerException("Docker not available")
localstack.utils.docker_utils.ContainerException: Docker not available

Traceback (most recent call last):
  File "/opt/localstack/ve/bin/localstack", line 23, in <module>
    main()
  File "/opt/localstack/ve/bin/localstack", line 19, in main
    main.main()
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/cli/main.py", line 6, in main
    cli()
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/opt/localstack/ve/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/localstack/ve/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/localstack/ve/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/localstack/ve/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/localstack/ve/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/cli/localstack.py", line 111, in cmd_start
    bootstrap.start_infra_locally()
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/utils/bootstrap.py", line 405, in start_infra_locally
    return infra.start_infra()
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 383, in start_infra
    raise e
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 369, in start_infra
    thread = do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 474, in do_start_infra
    prepare_installation()
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/utils/bootstrap.py", line 91, in wrapped
    return f(*args, **kwargs)
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 427, in prepare_installation
    install.install_components(apis)
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 474, in install_components
    parallelize(install_component, names)
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/utils/common.py", line 1877, in parallelize
    return pool.map(func, arr)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 470, in install_component
    installer()
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 319, in install_stepfunctions_local
    DOCKER_CLIENT.pull_image(IMAGE_NAME_SFN_LOCAL)
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/utils/docker_utils.py", line 1150, in pull_image
    self.client().images.pull(repository, tag)
  File "/opt/localstack/ve/lib/python3.9/site-packages/localstack/utils/docker_utils.py", line 1003, in client
    raise ContainerException("Docker not available")
localstack.utils.docker_utils.ContainerException: Docker not available
```

Am I doing anything wrong ? Can i not use localstack without docker ?

**Comment by bcv** [comment]
Thanks @thrau  but that did not work either
```

(ve) root@localstack:/opt/lstack# localstack start  --host

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 ? LocalStack CLI 0.12.19

[05:52:51] starting LocalStack in host mode ?                                                                                                                                                                                                                                       localstack.py:104
??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? LocalStack Runtime Log (press CTRL-C to quit) ????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

LocalStack version: 0.12.19

2021-10-19T05:52:53:INFO:bootstrap.py: Execution of "load_plugin_from_path" took 2224.68ms
2021-10-19T05:52:53:INFO:bootstrap.py: Execution of "load_plugins" took 2225.58ms
2021-10-19T05:52:53:INFO:localstack.services.install: Downloading and installing local Step Functions server. This may take some time.
2021-10-19T05:52:53:INFO:localstack.services.install: Downloading and installing local DynamoDB server. This may take some time.
2021-10-19T05:52:53:WARNING:localstack.utils.common: Unable to open zip file: /tmp/localstack.ddb.zip: File is not a zip file
2021-10-19T05:52:53:INFO:localstack.services.install: Unable to extract file, re-downloading ZIP archive /tmp/localstack.ddb.zip: File is not a zip file
2021-10-19T05:53:12:INFO:bootstrap.py: Execution of "prepare_installation" took 18304.17ms
Error starting infrastructure: Docker not available Traceback (most recent call last):
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 484, in start_infra
    thread = do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 574, in do_start_infra
    prepare_installation()
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/bootstrap.py", line 88, in wrapped
    return f(*args, **kwargs)
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 544, in prepare_installation
    install.install_components(apis)
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 474, in install_components
    parallelize(install_component, names)
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/common.py", line 1872, in parallelize
    return pool.map(func, arr)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 470, in install_component
    installer()
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 319, in install_stepfunctions_local
    DOCKER_CLIENT.pull_image(IMAGE_NAME_SFN_LOCAL)
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/docker_utils.py", line 1150, in pull_image
    self.client().images.pull(repository, tag)
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/docker_utils.py", line 1003, in client
    raise ContainerException("Docker not available")
localstack.utils.docker_utils.ContainerException: Docker not available

Traceback (most recent call last):
  File "/opt/lstack/ve/bin/localstack", line 23, in <module>
    main()
  File "/opt/lstack/ve/bin/localstack", line 19, in main
    main.main()
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/cli/main.py", line 6, in main
    cli()
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/cli/plugin.py", line 16, in __call__
    self.group(*args, **kwargs)
  File "/opt/lstack/ve/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/lstack/ve/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/lstack/ve/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/lstack/ve/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/lstack/ve/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/cli/localstack.py", line 111, in cmd_start
    bootstrap.start_infra_locally()
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/bootstrap.py", line 370, in start_infra_locally
    return infra.start_infra()
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 498, in start_infra
    raise e
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 484, in start_infra
    thread = do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 574, in do_start_infra
    prepare_installation()
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/bootstrap.py", line 88, in wrapped
    return f(*args, **kwargs)
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 544, in prepare_installation
    install.install_components(apis)
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 474, in install_components
    parallelize(install_component, names)
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/common.py", line 1872, in parallelize
    return pool.map(func, arr)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 470, in install_component
    installer()
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 319, in install_stepfunctions_local
    DOCKER_CLIENT.pull_image(IMAGE_NAME_SFN_LOCAL)
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/docker_utils.py", line 1150, in pull_image
    self.client().images.pull(repository, tag)
  File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/docker_utils.py", line 1003, in client
    raise ContainerException("Docker not available")
localstack.utils.docker_utils.ContainerException: Docker not available
(ve) root@localstack:/opt/lstack# 
```

However if I start individual services it works fine 
like 

``` 
(ve) root@localstack:/opt/lstack# SERVICES=s3,ses,SQS,iam localstack   start  --host 

    __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 ? LocalStack CLI 0.12.19

[06:13:39] starting LocalStack in host mode ?                                                                                                                                                                                                                                       localstack.py:104
??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? LocalStack Runtime Log (press CTRL-C to quit) ????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

LocalStack version: 0.12.19

2021-10-19T06:13:41:INFO:bootstrap.py: Execution of "load_plugin_from_path" took 2122.01ms
2021-10-19T06:13:41:INFO:bootstrap.py: Execution of "load_plugins" took 2122.94ms
Starting edge router (https port 4566)...
[2021-10-19 06:13:41 +0100] [34281] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-10-19T06:13:41:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
Starting mock IAM service on http port 4566 ...
2021-10-19T06:13:41:INFO:localstack.multiserver: Starting multi API server process on port 40999
[2021-10-19 06:13:41 +0100] [34281] [INFO] Running on http://0.0.0.0:40999 (CTRL + C to quit)
2021-10-19T06:13:41:INFO:hypercorn.error: Running on http://0.0.0.0:40999 (CTRL + C to quit)
Starting mock S3 service on http port 4566 ...
Starting mock SES service on http port 4566 ...
2021-10-19T06:13:48:INFO:localstack.utils.persistence: Restored 2 API calls from persistent file: /opt/lstack/data/recorded_api_calls.json
2021-10-19T06:13:48:INFO:bootstrap.py: Execution of "start_api_services" took 7285.78ms
Ready.
 
```

**Comment by dfangl** [comment]
Hi!
Installing the dependencies for StepFunctions currently only works with docker available.
If you do not need that functionality, you can try enabling every service but StepFunctions, to get it to work.
If StepFunctions are needed, I am afraid you currently need docker to download them.
You could, however startup LocalStack on a Host with docker, and copy the `infra` directory under your localstack installation path (should be the path to the installed pip package if pip is used, otherwise the source directory of LocalStack) to your docker-less installation, it should work then, as long as no update is required.

**Comment by whummer** [comment]
Thanks @dfangl for providing the details. Closing, as a workaround has been provided (customizing `SERVICES=...` to exclude stepfunctions). Please let us know if there are any other issues @bcv . Thanks!

**Comment by kiendoan-techie** [comment]
hi @bcv,
Which python version were you using?
I want to run localstack on host too, but it is not working.

> Thanks @thrau but that did not work either
> 
> ```
> 
> (ve) root@localstack:/opt/lstack# localstack start  --host
> 
>      __                     _______ __             __
>     / /   ____  _________ _/ / ___// /_____ ______/ /__
>    / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
>   / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
>  /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|
> 
>  ? LocalStack CLI 0.12.19
> 
> [05:52:51] starting LocalStack in host mode ?                                                                                                                                                                                                                                       localstack.py:104
> ??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? LocalStack Runtime Log (press CTRL-C to quit) ????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
> 
> LocalStack version: 0.12.19
> 
> 2021-10-19T05:52:53:INFO:bootstrap.py: Execution of "load_plugin_from_path" took 2224.68ms
> 2021-10-19T05:52:53:INFO:bootstrap.py: Execution of "load_plugins" took 2225.58ms
> 2021-10-19T05:52:53:INFO:localstack.services.install: Downloading and installing local Step Functions server. This may take some time.
> 2021-10-19T05:52:53:INFO:localstack.services.install: Downloading and installing local DynamoDB server. This may take some time.
> 2021-10-19T05:52:53:WARNING:localstack.utils.common: Unable to open zip file: /tmp/localstack.ddb.zip: File is not a zip file
> 2021-10-19T05:52:53:INFO:localstack.services.install: Unable to extract file, re-downloading ZIP archive /tmp/localstack.ddb.zip: File is not a zip file
> 2021-10-19T05:53:12:INFO:bootstrap.py: Execution of "prepare_installation" took 18304.17ms
> Error starting infrastructure: Docker not available Traceback (most recent call last):
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 484, in start_infra
>     thread = do_start_infra(asynchronous, apis, is_in_docker)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 574, in do_start_infra
>     prepare_installation()
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/bootstrap.py", line 88, in wrapped
>     return f(*args, **kwargs)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 544, in prepare_installation
>     install.install_components(apis)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 474, in install_components
>     parallelize(install_component, names)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/common.py", line 1872, in parallelize
>     return pool.map(func, arr)
>   File "/usr/lib/python3.9/multiprocessing/pool.py", line 364, in map
>     return self._map_async(func, iterable, mapstar, chunksize).get()
>   File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
>     raise self._value
>   File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
>     return list(map(*args))
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 470, in install_component
>     installer()
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 319, in install_stepfunctions_local
>     DOCKER_CLIENT.pull_image(IMAGE_NAME_SFN_LOCAL)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/docker_utils.py", line 1150, in pull_image
>     self.client().images.pull(repository, tag)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/docker_utils.py", line 1003, in client
>     raise ContainerException("Docker not available")
> localstack.utils.docker_utils.ContainerException: Docker not available
> 
> Traceback (most recent call last):
>   File "/opt/lstack/ve/bin/localstack", line 23, in <module>
>     main()
>   File "/opt/lstack/ve/bin/localstack", line 19, in main
>     main.main()
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/cli/main.py", line 6, in main
>     cli()
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/cli/plugin.py", line 16, in __call__
>     self.group(*args, **kwargs)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
>     return self.main(*args, **kwargs)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/click/core.py", line 1053, in main
>     rv = self.invoke(ctx)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/opt/lstack/ve/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/click/core.py", line 754, in invoke
>     return __callback(*args, **kwargs)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/cli/localstack.py", line 111, in cmd_start
>     bootstrap.start_infra_locally()
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/bootstrap.py", line 370, in start_infra_locally
>     return infra.start_infra()
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 498, in start_infra
>     raise e
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 484, in start_infra
>     thread = do_start_infra(asynchronous, apis, is_in_docker)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 574, in do_start_infra
>     prepare_installation()
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/bootstrap.py", line 88, in wrapped
>     return f(*args, **kwargs)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/infra.py", line 544, in prepare_installation
>     install.install_components(apis)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 474, in install_components
>     parallelize(install_component, names)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/common.py", line 1872, in parallelize
>     return pool.map(func, arr)
>   File "/usr/lib/python3.9/multiprocessing/pool.py", line 364, in map
>     return self._map_async(func, iterable, mapstar, chunksize).get()
>   File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
>     raise self._value
>   File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
>     result = (True, func(*args, **kwds))
>   File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
>     return list(map(*args))
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 470, in install_component
>     installer()
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/services/install.py", line 319, in install_stepfunctions_local
>     DOCKER_CLIENT.pull_image(IMAGE_NAME_SFN_LOCAL)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/docker_utils.py", line 1150, in pull_image
>     self.client().images.pull(repository, tag)
>   File "/opt/lstack/ve/lib/python3.9/site-packages/localstack/utils/docker_utils.py", line 1003, in client
>     raise ContainerException("Docker not available")
> localstack.utils.docker_utils.ContainerException: Docker not available
> (ve) root@localstack:/opt/lstack# 
> ```
> 
> However if I start individual services it works fine like
> 
> ```
> (ve) root@localstack:/opt/lstack# SERVICES=s3,ses,SQS,iam localstack   start  --host 
> 
>     __                     _______ __             __
>     / /   ____  _________ _/ / ___// /_____ ______/ /__
>    / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
>   / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
>  /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|
> 
>  ? LocalStack CLI 0.12.19
> 
> [06:13:39] starting LocalStack in host mode ?                                                                                                                                                                                                                                       localstack.py:104
> ??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? LocalStack Runtime Log (press CTRL-C to quit) ????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
> 
> LocalStack version: 0.12.19
> 
> 2021-10-19T06:13:41:INFO:bootstrap.py: Execution of "load_plugin_from_path" took 2122.01ms
> 2021-10-19T06:13:41:INFO:bootstrap.py: Execution of "load_plugins" took 2122.94ms
> Starting edge router (https port 4566)...
> [2021-10-19 06:13:41 +0100] [34281] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
> 2021-10-19T06:13:41:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
> Starting mock IAM service on http port 4566 ...
> 2021-10-19T06:13:41:INFO:localstack.multiserver: Starting multi API server process on port 40999
> [2021-10-19 06:13:41 +0100] [34281] [INFO] Running on http://0.0.0.0:40999 (CTRL + C to quit)
> 2021-10-19T06:13:41:INFO:hypercorn.error: Running on http://0.0.0.0:40999 (CTRL + C to quit)
> Starting mock S3 service on http port 4566 ...
> Starting mock SES service on http port 4566 ...
> 2021-10-19T06:13:48:INFO:localstack.utils.persistence: Restored 2 API calls from persistent file: /opt/lstack/data/recorded_api_calls.json
> 2021-10-19T06:13:48:INFO:bootstrap.py: Execution of "start_api_services" took 7285.78ms
> Ready.
>  
> ```

**Comment by HarshCasper** [comment]
Hi @kiendoan-techie — It is not recommended to run LocalStack on the host mode, and we do not support it any longer!

**Comment by mnm364** [comment]
Hey! Localstack is great. I use it for local development and have also been trying to use it for testing as well. However, It's a bit of an unfortunate situation that Localstack cannot be run without Docker - as Docker cannot be run within a macOS VM due to nested virtualization constraints. 

In order to support a macOS-dependent CI workflow (iOS integration tests), I've had to jump through quite a few hoops to get things working. I have Docker running on the host machine which has a port open to accept docker commands from the guest VM. This adds quite a bit of complexity to my CI workflow and management.

<img width="1400" height="1002" alt="Image" src="https://github.com/user-attachments/assets/d68aea1c-cf62-4ddf-90c4-21b28571f2a6" />

I'm sure others have found themselves in similar situations given the response to this thread. Is there any alternative to this or any further consideration for supporting localstack on the host mode? Appreciate your time, thanks!
