### ISSUE TITLE
bug: Unknown Parameter error being thrown in 0.12.12 with ECS clusterSetting CloudFormation template.

### ISSUE THREAD

**Issue by mark-brooks-roostify** [localstack/localstack#4749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running Localstack using `docker compose`, and I am encountering an error trying to run the following AWS example:

https://aws.amazon.com/blogs/containers/automated-software-delivery-using-docker-compose-and-amazon-ecs/

I'm running version 0.12.12.

The Github repo for the example in question is here:

https://github.com/aws-containers/demo-app-for-docker-compose.git

The cloudformation.yaml file is located in the infrastructure/ subdirectory.

There is an error because of the `name` parameter.  The error indicates that `name` is not expected for a `clusterSettings` section:

```
2021-10-18T19:31:07:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "ECS::Cluster" in region us-east-1: create_cluster {'clusterName': 'compose-infrastructure-cluster', 'clusterSettings': [{'name': 'containerInsights', 'value': 'enabled'}], 'capacityProviders': ['FARGATE', 'FARGATE_SPOT'], 'defaultCapacityProviderStrategy': [{'capacityProvider': 'FARGATE', 'weight': 1}, {'capacityProvider': 'FARGATE_SPOT', 'weight': 2}]}
2021-10-18T19:31:07:WARNING:localstack.utils.cloudformation.template_deployer: Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.ECS object at 0x4042eb7ed0>> with params: {'clusterName': 'compose-infrastructure-cluster', 'clusterSettings': [{'name': 'containerInsights', 'value': 'enabled'}], 'capacityProviders': ['FARGATE', 'FARGATE_SPOT'], 'defaultCapacityProviderStrategy': [{'capacityProvider': 'FARGATE', 'weight': 1}, {'capacityProvider': 'FARGATE_SPOT', 'weight': 2}]} for resource: {'Type': 'AWS::ECS::Cluster', 'Properties': {'ClusterName': 'compose-infrastructure-cluster', 'ClusterSettings': [{'name': 'containerInsights', 'value': 'enabled'}], 'CapacityProviders': ['FARGATE', 'FARGATE_SPOT'], 'DefaultCapacityProviderStrategy': [{'capacityProvider': 'FARGATE', 'weight': 1}, {'capacityProvider': 'FARGATE_SPOT', 'weight': 2}]}, 'LogicalResourceId': 'ECSCluster', 'PhysicalResourceId': None, '_state_': {}}
2021-10-18T19:31:07:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "compose-infrastructure": Parameter validation failed:
roostify2-localstack-1  | Unknown parameter in input: "clusterSettings", must be one of: clusterName, tags, settings, configuration, capacityProviders, defaultCapacityProviderStrategy Traceback (most recent call last):

```

However, the AWS documentation doesn't appear to comport with this, and the cloudformation.yaml file appears correct:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-cluster-clustersettings.html

### Expected Behavior

It is expected that the CFN stack will be created and run correctly.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    `docker compose up`

```
    localstack:
      image: localstack/localstack:0.12.12
      ports:
        - "443:443"
        - "4510-4530:4510-4530"
        - "4566-4620:4566-4620"
      environment:
        - TMPDIR=${TMPDIR:-tmp/localstack}
        - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
        - HOSTNAME=localhost
        - SERVICES=ec2, elbv2, ecs, s3, cognito, apigateway, sns, sns, sqs, apigatewayv2, dynamodb, dynamodbstreams, cloudformation, documentdb, logs, lambda, stepfunctions, iam
        - DEBUG=1
        - DATA_DIR=/tmp/localstack/data
        - DOCKER_HOST=unix:///var/run/docker.sock
        - HOST_TMP_FOLDER=${TMPDIR}
      volumes:
        - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"
      networks:
        - roostify2-net
```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws --endpoint-url http://localhost:4566 cloudformation create-stack --stack-name compose-infrastructure --template-body file://cloudformation.yaml --capabilities CAPABILITY_IAM

### Environment

```markdown
- OS: macOS Big Sur 11.5.2
- LocalStack: 0.12.12
```

### Anything else?

```
2021-10-18T19:31:07:WARNING:localstack.utils.cloudformation.template_deployer: Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.ECS object at 0x4042eb7ed0>> with params: {'clusterName': 'compose-infrastructure-cluster', 'clusterSettings': [{'name': 'containerInsights', 'value': 'enabled'}], 'capacityProviders': ['FARGATE', 'FARGATE_SPOT'], 'defaultCapacityProviderStrategy': [{'capacityProvider': 'FARGATE', 'weight': 1}, {'capacityProvider': 'FARGATE_SPOT', 'weight': 2}]} for resource: {'Type': 'AWS::ECS::Cluster', 'Properties': {'ClusterName': 'compose-infrastructure-cluster', 'ClusterSettings': [{'name': 'containerInsights', 'value': 'enabled'}], 'CapacityProviders': ['FARGATE', 'FARGATE_SPOT'], 'DefaultCapacityProviderStrategy': [{'capacityProvider': 'FARGATE', 'weight': 1}, {'capacityProvider': 'FARGATE_SPOT', 'weight': 2}]}, 'LogicalResourceId': 'ECSCluster', 'PhysicalResourceId': None, '_state_': {}}
2021-10-18T19:31:07:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "compose-infrastructure": Parameter validation failed:
Unknown parameter in input: "clusterSettings", must be one of: clusterName, tags, settings, configuration, capacityProviders, defaultCapacityProviderStrategy Traceback (most recent call last):
   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1848, in _run
     self.do_apply_changes_in_loop(changes, stack, stack_name)
   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1899, in do_apply_changes_in_loop
     self.apply_change(change, stack, new_resources, stack_name=stack_name)
   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1952, in apply_change
     result = deploy_resource(resource_id, new_resources, stack_name)
   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 950, in deploy_resource
     return execute_resource_action(resource_id, resources, stack_name, ACTION_CREATE)
   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1054, in execute_resource_action
     result = configure_resource_via_sdk(resource_id, resources, resource_type, func, stack_name, action_name)
   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1177, in configure_resource_via_sdk
     raise e
   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1172, in configure_resource_via_sdk
     result = function(**params)
   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 386, in _api_call
     return self._make_api_call(operation_name, kwargs)
   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 678, in _make_api_call
     api_params, operation_model, context=request_context)
   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 726, in _convert_to_request_dict
     api_params, operation_model)
   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/validate.py", line 319, in serialize_to_request
     raise ParamValidationError(report=report.generate_report())
 botocore.exceptions.ParamValidationError: Parameter validation failed:
 Unknown parameter in input: "clusterSettings", must be one of: clusterName, tags, settings, configuration, capacityProviders, defaultCapacityProviderStrategy 
```

**Comment by trevordilley** [comment]
+1 from me!

**Comment by finwo** [comment]
@fricorico The issue we ran into
