### ISSUE TITLE
Cognito forgotPassword returns 500

### ISSUE THREAD

**Issue by ronpbinahai** [localstack/localstack#4790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sending forgotPassword request fails with 500 error

### Expected Behavior

response 200

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
Running from nodejs aws-sdk the following request to localstask:
```
            await this.cognitoIdentityServiceProvider.forgotPassword({
              ClientId: userClientId,
              Username: username,
              ClientMetadata: {
                type: 'resetPassword',
                actorId: context?.actorId.toString(),
              }
            }).promise();
```

Results in the following error:
```
statusCode = 500
message = Error in Cognito action "ForgotPassword": 'dict' object has no attribute 'split' 
stack = InternalServerError: Error in Cognito action "ForgotPassword": 'dict' object has no attribute 'split' 
    at Request.extractError (/app/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
```

### Environment

```markdown
- OS: 
- LocalStack: latest
```

**Comment by whummer** [comment]
Quick follow-up on this issue - can you please confirm if this issue still persists with the `latest` Docker image? Please keep us posted how it goes.. Thanks!

**Comment by whummer** [comment]
Closing due to inactivity - please let us know if the problem persists with the `latest` Docker image. Thanks!
