### ISSUE TITLE
bug: SSM PutParameter from AWS JavaScript SDK v2 returns an error in latest docker version

### ISSUE THREAD

**Issue by tinaboyce** [localstack/localstack#4795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This bug appeared in the latest version of the docker image (digest: 83a486229d5a) but it was working fine in the docker image with the tag 0.12.19.1

I am receiving the following error in the `console.log(err)`

```
Error [UnknownError]: null
    at Request.extractError (/Users/tina/workspace/ping/ppc-api/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/Users/tina/workspace/ping/ppc-api/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/tina/workspace/ping/ppc-api/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/tina/workspace/ping/ppc-api/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/tina/workspace/ping/ppc-api/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/tina/workspace/ping/ppc-api/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/tina/workspace/ping/ppc-api/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/tina/workspace/ping/ppc-api/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/tina/workspace/ping/ppc-api/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/tina/workspace/ping/ppc-api/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'UnknownError',
  time: 2021-10-27T04:38:57.584Z,
  requestId: undefined,
  statusCode: 500,
  retryable: true
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml

```
version: '3'

services:
  localstack:
    image: localstack/localstack:latest
    
    restart: always
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - SERVICES=dynamodb,ssm,stepfunctions,lambda,iam
      - DEFAULT_REGION=${AWS_REGION}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - local_network

networks:
  local_network:
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```
AWS.config.update({
  region: process.env.AWS_REGION,
  endpoint: process.env.SSM_ENDPOINT,
  secretAccessKey: *snip*
  accessKeyId:  *snip*,
});

const getSsmClient = () =>
  new AWS.SSM({
    apiVersion: '2014-11-06',
  });

const putParameter = async param => {
  const ssm = getSsmClient();
  try {
    return await ssm.putParameter(param).promise();
  } catch (err) {
    console.log(err);
    throw err;
  }
};
```

### Environment

```markdown
- OS: macOS Big Sur Version 11.1
- LocalStack: latest
- AWS JavaScript SDK: 2.485.0

Also affected CI/CD environment
- OS: Amazon Linux AMI 2
- LocalStack: latest
```

**Comment by pinzon** [comment]
Hi @tinaboyce this code seems to work in the latest version so I'm gonna close this issue.
Thanks for using Localstack.
