### ISSUE TITLE
bug: ssm put-parameter failing - failed to get service for events: service events is disabled

### ISSUE THREAD

**Issue by sparrowt** [localstack/localstack#4827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following is failing on `localstack/localstack:latest` since 2021-10-26 (first noticed 18:00 UTC)
```
awslocal ssm put-parameter --name FOO --value "BAR"
```
Errors in the logs:
```
2021-10-26T18:06:36:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: failed to get service for events: service events is disabled Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/edge.py", line 223, in _require_service
    self.service_manager.require(api)
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/plugins.py", line 277, in require
    raise ServiceDisabled("service %s is disabled" % name)
localstack.services.plugins.ServiceDisabled: service events is disabled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 159, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 86, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 545, in handler
    server_address=parsed_url.netloc,
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 206, in modify_and_forward
    method, path, data_bytes=data_bytes, headers=headers, *args, **kwargs
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 330, in modify_and_forward
    method=method, path=path, data=data, headers=headers
  File "/opt/code/localstack/localstack/services/edge.py", line 172, in forward_request
    self._require_service(api)
  File "/opt/code/localstack/localstack/services/edge.py", line 225, in _require_service
    raise HTTPErrorResponse("failed to get service for %s: %s" % (api, e), code=500)
localstack.utils.server.http2_server.HTTPErrorResponse: failed to get service for events: service events is disabled


2021-10-26T18:06:44:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: An error occurred (500) when calling the PutEvents operation (reached max retries: 4):  Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 159, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 86, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 545, in handler
    server_address=parsed_url.netloc,
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 206, in modify_and_forward
    method, path, data_bytes=data_bytes, headers=headers, *args, **kwargs
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 330, in modify_and_forward
    method=method, path=path, data=data, headers=headers
  File "/opt/code/localstack/localstack/services/edge.py", line 179, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 230, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 262, in do_forward_request_inmem
    server_address=server_address,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 330, in modify_and_forward
    method=method, path=path, data=data, headers=headers
  File "/opt/code/localstack/localstack/services/ssm/ssm_listener.py", line 210, in forward_request
    notify_event_subscribers(data, target)
  File "/opt/code/localstack/localstack/services/ssm/ssm_listener.py", line 158, in notify_event_subscribers
    events.put_events(Entries=[event])
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 708, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (500) when calling the PutEvents operation (reached max retries: 4): 
```
Based on what was merged around that time #4788 may be the cause (also given [this comment](https://github.com/localstack/localstack/pull/4788#issuecomment-953086573) on that PR)?

This _may_ also be the same issue that is behind #4795 but there isn't enough on that issue to be sure.

### Expected Behavior

`awslocal ssm put-parameter` to succeed without error

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    mylocalstack:
      image: localstack/localstack
      environment:
        - SERVICES=sqs,s3,ssm
        - HOSTNAME_EXTERNAL=mylocalstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal ssm put-parameter --name FOO --value "BAR"

### Environment

```markdown
- OS: amazonlinux
- LocalStack: latest
```

**Comment by silv-io** [comment]
Hi @sparrowt and thanks for reporting this issue. I can't reproduce your error, so I need a bit more information from you. 

Have you made sure to `docker pull` the latest localstack image?
Is this your complete `docker-compose.yml` and have you tried using [sample for it](https://github.com/localstack/localstack/blob/master/docker-compose.yml)?
Also, are you starting localstack with pro services enabled or do you use the community edition?

**Comment by noone234** [comment]
I experienced this issue yesterday (2 November 2021).

I can also answer 2 out of 3 of @silv-io's questions.
- Yes, I `docker pull`ed the latest localstack image.
- I am using the community edition.

To work around the issue, I added `events` to `SERVICES` environment variable.

**Comment by sparrowt** [comment]
Yes this was happening on latest since 26th Oct per original report - in order to avoid the issue we then pinned to `0.12.19.1` where this bug doesn't occur.

That is the localstack part of docker-compose.yml yes (there are other parts for my project which is talking to it) - I didn't realise some of the things in the sample docker-compose.yml were required; now that I've discovered `localstack config validate` I will try some of the things it suggests to see if that helps.

Community Edition.

Thanks!

**Comment by sparrowt** [comment]
For now I have also added `events` to `SERVICES` (thanks @noone234 for the suggestion).

It seems like the issue is that `ssm` has a new undocumented dependency on `events` - if this is to be expected, could localstack be taught about this so that it automatically starts `events` if a service that requires it has been requested?

**Comment by thrau** [comment]
i can no longer reproduce this issue with the latest version of localstack.
in general, the use of the `SERVICES` variable is deprecated since we now lazy-load services on demand.
