### ISSUE TITLE
bug: Unable to resolve references in stack outputs when deploying with cdk

### ISSUE THREAD

**Issue by jappyjan** [localstack/localstack#4829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running cdklocal deploy results in "CREATE_FAILED"

when adding --debug to "localstack start" i get the following error messages:

```
2021-11-01T14:25:35:DEBUG:localstack.services.cloudformation.cloudformation_api: Executing change set "cdk-deploy-change-set" for stack "jappyjan-local-NFT-Marketplace-Shared" with 42 resources ...
2021-11-01T14:25:35:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type Route53::HostedZone when resolving references of resource SubzoneDelegationHostedZone39E7A604: {'Type': 'AWS::Route53::HostedZone', 'Metadata': {'aws:cdk:path': 'jappyjan-local-NFT-Marketplace-Shared/SubzoneDelegation/HostedZone/Resource'}, 'LogicalResourceId': 'SubzoneDelegationHostedZone39E7A604', 'Properties': {'Name': 'jappyjan-local.dev.nifty.store.'}}
2021-11-01T14:25:35:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "SubzoneDelegationHostedZone39E7A604" (1/42) type "AWS::Route53::HostedZone" in loop iteration 1 (should_deploy=True)
2021-11-01T14:25:35:INFO:localstack.utils.cloudformation.template_deployer: Action "create" for resource type Route53::HostedZone not yet implemented - using fallback mechanism
2021-11-01T14:25:35:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Route53::HostedZone PhysicalResourceId
2021-11-01T14:25:35:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: EC2::VPC Ref
2021-11-01T14:25:36:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Ref': 'VPCB9E5F0B4'}} - Unable to fetch details for resource "VPCB9E5F0B4" (attribute "Ref")
2021-11-01T14:25:36:DEBUG:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:eu-central-1:000000000000:function:jappyjan-local-NFT-Marketplac-CrossAccountZoneDelegati-fd090758
2021-11-01T14:25:36:DEBUG:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:eu-central-1:000000000000:function:jappyjan-local-NFT-Marketplac-CrossAccountZoneDelegati-96872b52
2021-11-01T14:25:36:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Route53::HostedZone NameServers
2021-11-01T14:25:36:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "jappyjan-local-NFT-Marketplace-Shared": Unable to extract attribute "NameServers" from "Route53::HostedZone" model class <class 'moto.route53.models.FakeZone'> Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1496, in _run
    self.do_apply_changes_in_loop(changes, stack, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1546, in do_apply_changes_in_loop
    resource_id, change, stack, new_resources
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1606, in prepare_should_deploy_change
    resolve_refs_recursively(stack.stack_name, resource, new_resources)
  File "/opt/code/localstack/localstack/utils/common.py", line 518, in func
    return wrapped(*args, **kwargs)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 635, in resolve_refs_recursively
    value[key] = resolve_refs_recursively(stack_name, val, resources)
  File "/opt/code/localstack/localstack/utils/common.py", line 518, in func
    return wrapped(*args, **kwargs)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 635, in resolve_refs_recursively
    value[key] = resolve_refs_recursively(stack_name, val, resources)
  File "/opt/code/localstack/localstack/utils/common.py", line 518, in func
    return wrapped(*args, **kwargs)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 520, in resolve_refs_recursively
    return resolve_ref(stack_name, attr_ref[0], resources, attribute=attr_ref[1])
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 488, in resolve_ref
    stack_name=stack_name,
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 300, in extract_resource_attribute
    % (attribute, resource_type, type(resource_state))
Exception: Unable to extract attribute "NameServers" from "Route53::HostedZone" model class <class 'moto.route53.models.FakeZone'>

2021-11-01T14:25:41:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: EC2::VPC Ref
2021-11-01T14:25:41:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Ref': 'VPCB9E5F0B4'}} - Unable to fetch details for resource "VPCB9E5F0B4" (attribute "Ref")

``` 

### Expected Behavior

it deploys

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack cli -> localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    cdklocal deploy

### Environment

```markdown
- OS: MacOS 11.6 (Big Sur)
- LocalStack: 0.12.19.3
```

### Anything else?

[cdk.out.zip](https://github.com/localstack/localstack/files/7453955/cdk.out.zip)

**Comment by jappyjan** [comment]
any updates?

**Comment by AnjaneyuluBatta505** [comment]
same issue for me as well. any fixes?

**Comment by nahue** [comment]
Same issue here

**Comment by ryuseongryong** [comment]
I've got the same issue.
run as docker compose and added all the necessary services, but I have the same issue.

**Comment by dominikschubert** [comment]
The `AWS::Route53::HostedZone` is only available with a PRO subscription right now.

You can check the availability of certain resources in our [CloudFormation docs](https://docs.localstack.cloud/aws/cloudformation/#resources-pro--enterprise-edition)

I'm unfortunately not able to reproduce the issue when running PRO. If you still see the same issue using a newer version of Localstack (v1+), please feel free to reopen this issue!
