### ISSUE TITLE
bug: POST to lambda fails, while GET succeeds

### ISSUE THREAD

**Issue by snowe2010** [localstack/localstack#4830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

From [Slack](https://localstack-community.slack.com/archives/CMAFN2KSP/p1635372677052200), using [this gist](https://gist.github.com/crypticmind/c75db15fd774fe8f53282c3ccbe3d7ad) (just with `localstack start`, not docker compose), a GET call will succeed, while a POST fails with

```
{"Type": "User", "message": "Unable to find path /restapis/kn6x76s4wy/prod/_user_request_/debug", "__type":
"NotFoundException"}
```

partial log from localstack without DEBUG on. 
```

API available at: http://q7m5shrp7u.execute-api.localhost.localstack.cloud:4566/test/HowMuchIsTheFish
Testing GET:
HTTP/1.1 201
Content-Type: text/html; charset=utf-8
Content-Length: 25
X-Custom-Header: ASDF
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Headers: authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request
Access-Control-Expose-Headers: etag,x-amz-version-id
Connection: close
date: Mon, 01 Nov 2021 16:36:37 GMT
server: hypercorn-h11

{"message":"Hello World"}Testing POST:
HTTP/1.1 404
Content-Type: text/html; charset=utf-8
Content-Length: 120
x-amzn-errortype: NotFoundException
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Headers: authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request
Access-Control-Expose-Headers: etag,x-amz-version-id
Connection: close
date: Mon, 01 Nov 2021 16:36:37 GMT
server: hypercorn-h11

{"Type": "User", "message": "Unable to find integration for path /test/HowMuchIsTheFish", "__type": "NotFoundException"}
```

### Expected Behavior

I would expect the POST to succeed as well. I didn't write the above gist, it's just an example I found of how to hit a lambda in localstack over http. It appears to match what I think the calls and setup should be, so I can only assume it's a bug of some sort. 

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
brew install localstack
docker pull localstack/localstack
localstack start
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
#!/bin/sh

API_NAME=api
REGION=us-east-1
STAGE=test

function fail() {
    echo $2
    exit $1
}

awslocal lambda create-function \
    --region ${REGION} \
    --function-name ${API_NAME} \
    --runtime nodejs8.10 \
    --handler lambda.apiHandler \
    --memory-size 128 \
    --zip-file fileb://api-handler.zip \
    --role arn:aws:iam::123456:role/irrelevant

[ $? == 0 ] || fail 1 "Failed: AWS / lambda / create-function"

LAMBDA_ARN=$(awslocal lambda list-functions --query "Functions[?FunctionName==\`${API_NAME}\`].FunctionArn" --output text --region ${REGION})

awslocal apigateway create-rest-api \
    --region ${REGION} \
    --name ${API_NAME}

[ $? == 0 ] || fail 2 "Failed: AWS / apigateway / create-rest-api"

API_ID=$(awslocal apigateway get-rest-apis --query "items[?name==\`${API_NAME}\`].id" --output text --region ${REGION})
PARENT_RESOURCE_ID=$(awslocal apigateway get-resources --rest-api-id ${API_ID} --query 'items[?path==`/`].id' --output text --region ${REGION})

awslocal apigateway create-resource \
    --region ${REGION} \
    --rest-api-id ${API_ID} \
    --parent-id ${PARENT_RESOURCE_ID} \
    --path-part "{somethingId}"

[ $? == 0 ] || fail 3 "Failed: AWS / apigateway / create-resource"

RESOURCE_ID=$(awslocal apigateway get-resources --rest-api-id ${API_ID} --query 'items[?path==`/{somethingId}`].id' --output text --region ${REGION})

awslocal apigateway put-method \
    --region ${REGION} \
    --rest-api-id ${API_ID} \
    --resource-id ${RESOURCE_ID} \
    --http-method GET \
    --request-parameters "method.request.path.somethingId=true" \
    --authorization-type "NONE" \

[ $? == 0 ] || fail 4 "Failed: AWS / apigateway / put-method"

awslocal apigateway put-integration \
    --region ${REGION} \
    --rest-api-id ${API_ID} \
    --resource-id ${RESOURCE_ID} \
    --http-method GET \
    --type AWS_PROXY \
    --integration-http-method POST \
    --uri arn:aws:apigateway:${REGION}:lambda:path/2015-03-31/functions/${LAMBDA_ARN}/invocations \
    --passthrough-behavior WHEN_NO_MATCH \

[ $? == 0 ] || fail 5 "Failed: AWS / apigateway / put-integration"

awslocal apigateway create-deployment \
    --region ${REGION} \
    --rest-api-id ${API_ID} \
    --stage-name ${STAGE} \

[ $? == 0 ] || fail 6 "Failed: AWS / apigateway / create-deployment"

ENDPOINT=http://localhost:4567/restapis/${API_ID}/${STAGE}/_user_request_/HowMuchIsTheFish

echo "API available at: ${ENDPOINT}"

echo "Testing GET:"
curl -i ${ENDPOINT}

echo "Testing POST:"
curl -iX POST ${ENDPOINT}
```

### Environment

```markdown
- OS: macOS Big Sur 11.6
- LocalStack: 

❯ localstack --version
0.12.18.5
```
```


### Anything else?

_No response_

**Comment by whummer** [comment]
Hi @snowe2010 , thanks for reporting and for providing the detailed reproducible sample 👍 . Looks like your API is defining a method for GET, but the method and method integration for the POST route seems to be missing.

We were able to get this working by adding the following commands prior to the call to `create-deployment` (note that only `GET` has been replaced by `POST`):
```
awslocal apigateway put-method \
    --region ${REGION} \
    --rest-api-id ${API_ID} \
    --resource-id ${RESOURCE_ID} \
    --http-method POST \
    --request-parameters "method.request.path.somethingId=true" \
    --authorization-type "NONE" \

[ $? == 0 ] || fail 4 "Failed: AWS / apigateway / put-method"

awslocal apigateway put-integration \
    --region ${REGION} \
    --rest-api-id ${API_ID} \
    --resource-id ${RESOURCE_ID} \
    --http-method POST \
    --type AWS_PROXY \
    --integration-http-method POST \
    --uri arn:aws:apigateway:${REGION}:lambda:path/2015-03-31/functions/${LAMBDA_ARN}/invocations \
    --passthrough-behavior WHEN_NO_MATCH \

[ $? == 0 ] || fail 5 "Failed: AWS / apigateway / put-integration"
```

Can you please pull the `latest` Docker image and try with adding the commands above? Hope that helps - please let us know if the problem persists with the latest version. Thanks for your help!

**Comment by snowe2010** [comment]
@whummer It did work with that. I didn't realize the script was setting it up as a GET rather than ANY. This was _supposed_ to replicate the cdk deploy I am running my lambda with. I will try to get a working example with cdk, rather than the gist above, as it still fails with pretty much what looks like the same deploy, but with CDK instead.

**Comment by snowe2010** [comment]
I'm wondering if it's because my cdk is requiring an auth key...

```json
{
    "items": [
        {
            "id": "nm1rr9f9s9",
            "path": "/",
            "resourceMethods": {
                "ANY": {
                    "httpMethod": "ANY",
                    "authorizationType": "NONE",
                    "apiKeyRequired": true,
                    "methodIntegration": {
                        "type": "AWS",
                        "httpMethod": "POST",
                        "uri": "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:000000000000:function:local-proposal-change-order-ChangeOrderFn/invocations",
                        "requestParameters": {},
                        "passthroughBehavior": "WHEN_NO_MATCH",
                        "cacheNamespace": "2fd42c0c",
                        "cacheKeyParameters": []
                    }
                }
            }
        }
    ]
}
```

**Comment by snowe2010** [comment]
@whummer I managed to duplicate my exact setup with the script. The differences are that I used an http method type of `ANY`, and that I am creating the resource on `/`, _not_ using `/` as the parent. I think this is the key issue. We just proxy all calls to `/` straight through to the lambda, we don't care what it is, whether it's a POST or not, or what the parameters are. The _only_ difference I've found between the two resources is that my CDK build has apiKeyRequired set to true, but that doesn't seem to be affecting the problem.

Note: It seems that the original bug title `POST to lambda fails, while GET succeeds` was an error in the gist I was using, and not related to the actual error I was having. I thought they were one and the same, but I was not testing with a GET against my lambda, so I didn't realize that 

```bash
#!/bin/sh

API_NAME=api
REGION=us-east-1
STAGE=test

function fail() {
    echo $2
    exit $1
}

awslocal lambda create-function \
    --region ${REGION} \
    --function-name ${API_NAME} \
    --runtime nodejs8.10 \
    --handler lambda.apiHandler \
    --memory-size 128 \
    --zip-file fileb://api-handler.zip \
    --role arn:aws:iam::123456:role/irrelevant

[ $? == 0 ] || fail 1 "Failed: AWS / lambda / create-function"

LAMBDA_ARN=$(awslocal lambda list-functions --query "Functions[?FunctionName==\`${API_NAME}\`].FunctionArn" --output text --region ${REGION})

awslocal apigateway create-rest-api \
    --region ${REGION} \
    --name ${API_NAME}

[ $? == 0 ] || fail 2 "Failed: AWS / apigateway / create-rest-api"

API_ID=$(awslocal apigateway get-rest-apis --query "items[?name==\`${API_NAME}\`].id" --output text --region ${REGION})
RESOURCE_ID=$(awslocal apigateway get-resources --rest-api-id ${API_ID} --query 'items[?path==`/`].id' --output text --region ${REGION})

awslocal apigateway put-method \
    --region ${REGION} \
    --rest-api-id ${API_ID} \
    --resource-id ${RESOURCE_ID} \
    --http-method ANY \
    --authorization-type "NONE" \

[ $? == 0 ] || fail 4 "Failed: AWS / apigateway / put-method"

awslocal apigateway put-integration \
    --region ${REGION} \
    --rest-api-id ${API_ID} \
    --resource-id ${RESOURCE_ID} \
    --http-method ANY \
    --type AWS \
    --integration-http-method POST \
    --uri arn:aws:apigateway:${REGION}:lambda:path/2015-03-31/functions/${LAMBDA_ARN}/invocations \
    --passthrough-behavior WHEN_NO_MATCH \

[ $? == 0 ] || fail 5 "Failed: AWS / apigateway / put-integration"

awslocal apigateway create-deployment \
    --region ${REGION} \
    --rest-api-id ${API_ID} \
    --stage-name ${STAGE} \

[ $? == 0 ] || fail 6 "Failed: AWS / apigateway / create-deployment"

# ENDPOINT=http://localhost:4566/restapis/${API_ID}/${STAGE}/_user_request_/HowMuchIsTheFish
ENDPOINT=http://${API_ID}.execute-api.localhost.localstack.cloud:4566/${STAGE}/HowMuchIsTheFish

echo "API available at: ${ENDPOINT}"

echo "Testing GET:"
curl -i ${ENDPOINT}

echo "Testing POST:"
curl -iX POST ${ENDPOINT}
```

The only difference between the above script and my cdk deploy is that when I hit the POST above I get a very simple error message about the endpoint being not found while with my cdk deploy I get a much larger deploy error:

```
2021-11-03T17:10:47:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type CDK::Metadata when resolving references of resource CDKMetadata: {'Type': 'AWS::CDK::Metadata', 'Metadata': {'aws:cdk:path': 'local-proposal-change-order/CDKMetadata/Default'}, 'Condition': 'CDKMetadataAvailable', 'LogicalResourceId': 'CDKMetadata', 'Properties': {'Modules': 'aws-cdk=1.129.0,@aws-cdk/assets=1.80.0,@aws-cdk/aws-apigateway=1.80.0,@aws-cdk/aws-applicationautoscaling=1.80.0,@aws-cdk/aws-autoscaling-common=1.80.0,@aws-cdk/aws-certificatemanager=1.80.0,@aws-cdk/aws-cloudformation=1.80.0,@aws-cdk/aws-cloudwatch=1.80.0,@aws-cdk/aws-codeguruprofiler=1.80.0,@aws-cdk/aws-ec2=1.80.0,@aws-cdk/aws-ecr=1.80.0,@aws-cdk/aws-ecr-assets=1.80.0,@aws-cdk/aws-efs=1.80.0,@aws-cdk/aws-elasticloadbalancingv2=1.80.0,@aws-cdk/aws-events=1.80.0,@aws-cdk/aws-iam=1.80.0,@aws-cdk/aws-kms=1.80.0,@aws-cdk/aws-lambda=1.80.0,@aws-cdk/aws-logs=1.80.0,@aws-cdk/aws-route53=1.80.0,@aws-cdk/aws-s3=1.80.0,@aws-cdk/aws-s3-assets=1.80.0,@aws-cdk/aws-sns=1.80.0,@aws-cdk/aws-sqs=1.80.0,@aws-cdk/aws-ssm=1.80.0,@aws-cdk/cloud-assembly-schema=1.80.0,@aws-cdk/core=1.80.0,@aws-cdk/custom-resources=1.80.0,@aws-cdk/cx-api=1.80.0,@aws-cdk/region-info=1.80.0,jsii-runtime=Java/11.0.10'}}
2021-11-03T17:10:47:WARNING:localstack.utils.cloudformation.template_deployer: Unable to deploy resource type "CDK::Metadata": {'Type': 'AWS::CDK::Metadata', 'Metadata': {'aws:cdk:path': 'local-proposal-change-order/CDKMetadata/Default'}, 'Condition': 'CDKMetadataAvailable', 'LogicalResourceId': 'CDKMetadata', 'Properties': {'Modules': 'aws-cdk=1.129.0,@aws-cdk/assets=1.80.0,@aws-cdk/aws-apigateway=1.80.0,@aws-cdk/aws-applicationautoscaling=1.80.0,@aws-cdk/aws-autoscaling-common=1.80.0,@aws-cdk/aws-certificatemanager=1.80.0,@aws-cdk/aws-cloudformation=1.80.0,@aws-cdk/aws-cloudwatch=1.80.0,@aws-cdk/aws-codeguruprofiler=1.80.0,@aws-cdk/aws-ec2=1.80.0,@aws-cdk/aws-ecr=1.80.0,@aws-cdk/aws-ecr-assets=1.80.0,@aws-cdk/aws-efs=1.80.0,@aws-cdk/aws-elasticloadbalancingv2=1.80.0,@aws-cdk/aws-events=1.80.0,@aws-cdk/aws-iam=1.80.0,@aws-cdk/aws-kms=1.80.0,@aws-cdk/aws-lambda=1.80.0,@aws-cdk/aws-logs=1.80.0,@aws-cdk/aws-route53=1.80.0,@aws-cdk/aws-s3=1.80.0,@aws-cdk/aws-s3-assets=1.80.0,@aws-cdk/aws-sns=1.80.0,@aws-cdk/aws-sqs=1.80.0,@aws-cdk/aws-ssm=1.80.0,@aws-cdk/cloud-assembly-schema=1.80.0,@aws-cdk/core=1.80.0,@aws-cdk/custom-resources=1.80.0,@aws-cdk/cx-api=1.80.0,@aws-cdk/region-info=1.80.0,jsii-runtime=Java/11.0.10'}}
2021-11-03T17:29:16:INFO:localstack.utils.run: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7f282b3395f0>(None) failed: An error occurred (NotFoundException) when calling the GetResources operation: Invalid Rest API Id specified Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/run.py", line 150, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 545, in handler
    server_address=parsed_url.netloc,
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 206, in modify_and_forward
    method, path, data_bytes=data_bytes, headers=headers, *args, **kwargs
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 330, in modify_and_forward
    method=method, path=path, data=data, headers=headers
  File "/opt/code/localstack/localstack/services/edge.py", line 179, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 230, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 262, in do_forward_request_inmem
    server_address=server_address,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 330, in modify_and_forward
    method=method, path=path, data=data, headers=headers
  File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 89, in forward_request
    result = invoke_rest_api_from_request(method, path, data, headers)
  File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 311, in invoke_rest_api_from_request
    auth_info=auth_info,
  File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 325, in invoke_rest_api
    path_map = helpers.get_rest_api_paths(rest_api_id=api_id)
  File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 919, in get_rest_api_paths
    resources = apigateway.get_resources(restApiId=rest_api_id, limit=100)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 708, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NotFoundException: An error occurred (NotFoundException) when calling the GetResources operation: Invalid Rest API Id specified

2021-11-03T17:29:16:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/restapis/gze1w6fdpg/prod/_user_request_/debug: An error occurred (NotFoundException) when calling the GetResources operation: Invalid Rest API Id specified Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 159, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 86, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/opt/code/localstack/localstack/utils/run.py", line 150, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 545, in handler
    server_address=parsed_url.netloc,
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 206, in modify_and_forward
    method, path, data_bytes=data_bytes, headers=headers, *args, **kwargs
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 330, in modify_and_forward
    method=method, path=path, data=data, headers=headers
  File "/opt/code/localstack/localstack/services/edge.py", line 179, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 230, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 262, in do_forward_request_inmem
    server_address=server_address,
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 330, in modify_and_forward
    method=method, path=path, data=data, headers=headers
  File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 89, in forward_request
    result = invoke_rest_api_from_request(method, path, data, headers)
  File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 311, in invoke_rest_api_from_request
    auth_info=auth_info,
  File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 325, in invoke_rest_api
    path_map = helpers.get_rest_api_paths(rest_api_id=api_id)
  File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 919, in get_rest_api_paths
    resources = apigateway.get_resources(restApiId=rest_api_id, limit=100)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 708, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NotFoundException: An error occurred (NotFoundException) when calling the GetResources operation: Invalid Rest API Id specified

2021-11-03T17:29:16:ERROR:asyncio: Exception in callback _chain_future.<locals>._set_state(<Future finis...d specified')>, <Future at 0x...oundException>) at /usr/lib/python3.7/asyncio/futures.py:345
handle: <Handle _chain_future.<locals>._set_state(<Future finis...d specified')>, <Future at 0x...oundException>) at /usr/lib/python3.7/asyncio/futures.py:345>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.7/asyncio/futures.py", line 347, in _set_state
    _copy_future_state(other, future)
  File "/usr/lib/python3.7/asyncio/futures.py", line 317, in _copy_future_state
    assert not dest.done()
AssertionError
```

Note that my CDK deploy works perfectly fine in AWS, so it does appear to be something with localstack, or something I'm not understanding about localstack. If providing the cdk deploy would help, I can try to create a sample project demonstrating the issue.
