### ISSUE TITLE
Lambda create/update failed due to LogGroup exception

### ISSUE THREAD

**Issue by abbaseya** [localstack/localstack#4893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating and/or updating Lambda functions in docker does not work after updating LocalStack image to the latest version with the following error in LocalStack logs:
```
2021-11-10T14:41:27:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "lambda-http-local": An error occurred (ResourceAlreadyExistsException) when calling the CreateLogGroup operation: The specified log group already exists Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1482, in _run
    self.do_apply_changes_in_loop(changes, stack, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1554, in do_apply_changes_in_loop
    self.apply_change(change, stack, new_resources, stack_name=stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1619, in apply_change
    result = deploy_resource(resource_id, new_resources, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 778, in deploy_resource
    result = execute_resource_action(resource_id, resources, stack_name, ACTION_CREATE)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 835, in execute_resource_action
    resource_id, resources, resource_type, func, stack_name, action_name
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 963, in configure_resource_via_sdk
    raise e
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 951, in configure_resource_via_sdk
    result = function(**params)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceAlreadyExistsException: An error occurred (ResourceAlreadyExistsException) when calling the CreateLogGroup operation: The specified log group already exists
```

### Expected Behavior

Lambda create and/or update operations should pass successfully all the way to the end without any errors.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yml
services:
    localstack:
        container_name: localstack
        image: localstack/localstack
        ports:
            - 443:443
            - 4510-4530:4510-4530
            - 4566:4566
            - 4571:4571
        environment:
            - LOCALSTACK_API_KEY=${LOCALSTACK_LICENSE}
            - USE_LIGHT_IMAGE=0
            - IMAGE_NAME=localstack/localstack
            - MAIN_CONTAINER_NAME=localstack
            - SERVICES=cloudformation,cloudfront,apigateway,apigatewayv2,iam,secretsmanager,lambda,s3,sqs,sts,ec2,kafka,elb,elbv2
            - DEFAULT_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=test
            - AWS_SECRET_ACCESS_KEY=test
            - S3_SKIP_SIGNATURE_VALIDATION=1
            - DEBUG=1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        network_mode: bridge
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

A test case available at [GitHub](https://github.com/abbaseya/localstack-msk-lambda-test) - test command `./localstack.sh --use-hostname` or `./socket.sh`

### Environment

```markdown
- OS: macOS 12.0.1
- LocalStack: latest
- AWS CLI: 2.2.35
```

**Comment by abbaseya** [comment]
Issue appears to be resolved after updating LocalStack image!
