### ISSUE TITLE
bug: lambda requestContext.requestTime is a Datetime object, should be a string

### ISSUE THREAD

**Issue by matthewbentley** [localstack/localstack#4898]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Using the local lambda executor, the field `event["requestContex"]["requestTime"]` (code [here](https://github.com/localstack/localstack/blob/52cf2106097c4a46aa9c87095b8682d68c22ed93/localstack/services/apigateway/apigateway_listener.py#L941)) is being passed as a datetime object.  This is breaking lambda code that tries to log the event as in json format.

### Expected Behavior

The AWS behavior (documented [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html)) is for requestTime to be a string in the format `"04/Mar/2020:19:15:17 +0000"`.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run -it -e TEST_AWS_ACCOUNT_ID="000000000000" -e LOCALSTACK_HOSTNAME="localhost" -e LAMBDA_EXECUTOR="local" -e DEFAULT_REGION="us-west-1" --rm --name localstack_main -p 4566:4566 -p 4571:4571 -p 4590-4593:4590-4593 -p 12121:12121 -p 8080-8081:8080-8081  -v "$(pwd)/localstack:$(pwd)/localstack" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="$(pwd)/localstack" "localstack/localstack"

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

my full environment right now is a bit complex; I could try to make a minimal replication, but I hope this info is enough for now?

### Environment

```markdown
- OS: Ubuntu 18.04
- LocalStack: localstack==0.12.20
```

### Anything else?

Log output
```
2021-11-10T00:25:07:INFO:localstack.services.awslambda.lambda_executors: Error executing Lambda "arn:aws:lambda:us-west-1:000000000000:function:incoming": Object of type datetime is not JSON serializable   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1232, in _execute
    process.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1219, in do_execute
    result = lambda_function_callable(inv_context.event, context)
  File "/tmp/localstack/lambda_script_l_cdec33c8.py", line 565, in lambda_handler
    LOGGER.info(f"Incoming event: {json.dumps(event)}")
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

2021-11-10T00:25:07:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-west-1:000000000000:function:incoming: Object of type datetime is not JSON serializable Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 813, in run_lambda
    lock_discriminator=lock_discriminator,
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 429, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 419, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 158, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 154, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 406, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 402, in _run
    result = self._execute(lambda_function, inv_context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1268, in _execute
    raise InvocationException(result, log_output)
localstack.services.awslambda.lambda_executors.InvocationException: Object of type datetime is not JSON serializable
```

**Comment by whummer** [comment]
Thanks for reporting @matthewbentley , and thanks @flaviusemil for the fix in #5078 ! This fix should now be available in the `latest` Docker image - can you please pull the image and give it another try? Please let us know if the problem persists. Thanks!
