### ISSUE TITLE
SSM: creating an SSM parameter via awslocal breaks SSM

### ISSUE THREAD

**Issue by adammcnabb** [localstack/localstack#4899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Summary: Creating an SSM parameter after Localstack starts, creates an internal server error.

Details:
After starting Localstack via Docker plugin for Maven, creating an SSM parameter via awslocal causes an error within Localstack System Parameters service.  

Deploying Localstack via Maven:
```
[INFO] DOCKER> [docker.io/localstack/localstack:0.12.18] "localstack-deploy": Start container 485cd81ba250
[INFO] DOCKER> [docker.io/localstack/localstack:0.12.18] "localstack-deploy": Waiting on url http://localhost:4566/health with method GET for status 200.
```

The creation of the parameter is successful, returning:
```
{
    "Version": 1
}
```

Attempting to load the Terraform infra, returns an error with SSM parameter not found.
Attempting to view the System Parameters in the UI (https://app.localstack.cloud/resources/params) returns an internal server error.
Attempting to get the parameter via awslocal returns an error:
```
An error occurred (ParameterNotFound) when calling the GetParameter operation: Parameter /org/local/vpc/subnet/private not found.
```

### Expected Behavior

awslocal should return a value for the parameter created.

UI should be able to display the parameters.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

As my use case involves Maven, AWS CLI, and Terraform, I've attempted to consolidate in to a single script:

local-deploy.sh
```
#! /bin/bash
mvn docker:build docker:start -pl terraform-application

alias awslocal="AWS_ACCESS_KEY_ID=mock_access_key AWS_SECRET_ACCESS_KEY=mock_secret_key AWS_DEFAULT_REGION=ap-southeast-2 aws --endpoint-url=http://localhost:4566"

awslocal ssm put-parameter \
    --name "/org/local/vpc/subnet/private" \
    --value "some-test-value" \
    --type String \

(cd terraform-application/src/main/resources/local || exit ; terraform init)
(cd terraform-application/src/main/resources/local || exit ; terraform apply -auto-approve)
```

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Fabric8 Docker for Maven plugin:
The Fabric8 Docker setup:
```
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.37.0</version>
                <configuration>
                    <imagePullPolicy>IfNotPresent</imagePullPolicy>
                    <images>
                        <image>
                            <alias>localstack-deploy</alias>
                            <name>docker.io/localstack/localstack:0.12.18</name>
                            <run>
                                <network>
                                    <mode>custom</mode>
                                    <name>localstack</name>
                                </network>
                                <ports>
                                    <port>4566:4566</port>
                                    <port>443:443</port>
                                    <port>4571:4571</port>
                                </ports>
                                <env>
                                    <LOCALSTACK_API_KEY><redacted></LOCALSTACK_API_KEY>
                                    <AWS_ACCESS_KEY_ID>mock_access_key</AWS_ACCESS_KEY_ID>
                                    <AWS_SECRET_ACCESS_KEY>mock_secret_key</AWS_SECRET_ACCESS_KEY>
                                    <DEBUG>1</DEBUG>
                                    <LAMBDA_EXECUTOR>docker_reuse</LAMBDA_EXECUTOR>
                                    <DEFAULT_REGION>ap-southeast-2</DEFAULT_REGION>
                                    <SERVICES>lambda,s3,apigateway,iam,stepfunctions,sts,ssm,sns,sqs,cloudwatchlogs,cloudwatch,cloudformation,
                                    dynamodb,es,firehose,kinesis,route53,redshift,secretsmanager,ses</SERVICES>
                                    <LAMBDA_DOCKER_NETWORK>localstack</LAMBDA_DOCKER_NETWORK>
                                    <HOSTNAME_FROM_LAMBDA>localstack</HOSTNAME_FROM_LAMBDA>
                                </env>
                                <wait>
                                    <log>Server startup</log>
                                    <http>
                                        <url>http://localhost:4566/health</url>
                                        <method>GET</method>
                                        <status>200</status>
                                    </http>
                                    <time>60000</time>
                                    <shutdown>500</shutdown>
                                </wait>
                            </run>
                        </image>
                    </images>
                    <useColor>true</useColor>
                </configuration>
            </plugin>
```

Build and run:
```
docker:build docker:start
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```
awslocal ssm put-parameter \
    --name "/org/local/vpc/subnet/private" \
    --value "some-test-value" \
    --type String \
    --tags "Key=env,Value=local"
```

### Environment

```markdown
- OS: Windows 10.0.19041
- LocalStack: 0.12.18
- Docker Daemon (Docker version 20.10.10, build e2f740d)
- WSL2 (for dockerd) Default Distribution: Ubuntu
   Default Version: 2
   Kernel version: 5.10.16
```

### Anything else?

From UI > System Parameters:
```
json.js:52 Uncaught (in promise) UnknownError
    at constructor.extractError (json.js:52)
    at constructor.callListeners (sequential_executor.js:106)
    at constructor.emit (sequential_executor.js:78)
    at constructor.emitEvent (request.js:688)
    at constructor.e (request.js:22)
    at r.runTo (state_machine.js:14)
    at state_machine.js:26
    at constructor.<anonymous> (request.js:38)
    at constructor.<anonymous> (request.js:690)
    at constructor.callListeners (sequential_executor.js:116)
```

From Docker logs:
```
2021-11-10 20:13:36,076:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 183, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 148, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 205, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 315, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 405, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/ssm/responses.py", line 262, in describe_parameters
    response["Parameters"].append(parameter.describe_response_object(False))
AttributeError: 'NoneType' object has no attribute 'describe_response_object'
```

**Comment by debu99** [comment]
any update?
