### ISSUE TITLE
bug: AWS Batch RegisterJobDefinition using deprecated resource specification

### ISSUE THREAD

**Issue by bforcier1** [localstack/localstack#4933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When registering a jobDefinition against localstack batch, using the Java SDK:
```
		RegisterJobDefinitionRequest jobDefRequest = new RegisterJobDefinitionRequest()
		  .withType("container").withPlatformCapabilities("EC2")
		  .withTimeout(new JobTimeout().withAttemptDurationSeconds(jobTimeoutInSeconds))
		  .withContainerProperties(new ContainerProperties()
				  .withCommand("exit", "1")
				  .withResourceRequirements(
						  new ResourceRequirement()
								  .withType(ResourceType.VCPU)
								  .withValue("2"),
						  new ResourceRequirement()
								  .withType(ResourceType.MEMORY)
								  .withValue("4000")
					          )
                );
		awsBatchClient.registerJobDefinition(jobDefRequest);
```

Localstack throws an error, indicating a `TypeError` comparing memory values
```
localstack_1  | 2021-11-15 18:41:09,397:API: Error on request:
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
localstack_1  |     execute(self.server.app)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute
localstack_1  |     application_iter = app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 192, in __call__
localstack_1  |     return backend_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2091, in __call__
localstack_1  |     return self.wsgi_app(environ, start_response)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2076, in wsgi_app
localstack_1  |     response = self.handle_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
localstack_1  |     response = self.full_dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
localstack_1  |     rv = self.handle_user_exception(e)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
localstack_1  |     rv = self.dispatch_request()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
localstack_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
localstack_1  |   File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 161, in convert_flask_to_httpretty_response_call
localstack_1  |     return convert_flask_to_httpretty_response_call_orig(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 147, in __call__
localstack_1  |     result = self.callback(request, request.url, {})
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 203, in dispatch
localstack_1  |     return cls()._dispatch(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 313, in _dispatch
localstack_1  |     return self.call_action()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 403, in call_action
localstack_1  |     response = method()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/batch/responses.py", line 189, in registerjobdefinition
localstack_1  |     container_properties=container_properties,
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/batch/models.py", line 1295, in register_job_definition
localstack_1  |     retry_strategy=retry_strategy,
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/batch/models.py", line 216, in __init__
localstack_1  |     self._validate()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/batch/models.py", line 288, in _validate
localstack_1  |     if memory < 4:
localstack_1  | TypeError: '<' not supported between instances of 'str' and 'int'
```

### Expected Behavior

This same `RegisterJobDefinitionRequest` operation completes successfully when running against AWS Batch. This request is within spec for the Java SDK and should be valid

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up --build 

```
version: '2.1'

services:
  localstack:
    image: localstack/localstack:0.12.20
    ports:
      - "4566:4566" # omnibus port
    environment:
      - SERVICES=sqs,s3,sns,cloudwatch,batch,dynamodb,cloudwatch,ec2,route53,ssm,iam,events,logs,sts
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - LOCALSTACK_API_KEY=XXX
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   see `Current Behavior` for Java SDK call

### Environment

```markdown
- OS: MacOS Catalina 10.15.7 
- LocalStack: 0.12.20
```

### Anything else?

Replacing the `ResourceRequirement` section in the `RegisterJobDefinitionRequest` with the deprecated style fixes this, likely indicating that `moto` is just out of date?

This request is accepted:
```
		RegisterJobDefinitionRequest jobDefRequest = new RegisterJobDefinitionRequest()
		  .withType("container").withPlatformCapabilities("EC2")
		  .withTimeout(new JobTimeout().withAttemptDurationSeconds(jobTimeoutInSeconds))
		  .withContainerProperties(new ContainerProperties()
				  .withMemory(4000)
				  .withVcpus(2)
				  .withCommand("exit", "1")
                );
		awsBatchClient.registerJobDefinition(jobDefRequest);
```

**Comment by whummer** [comment]
Hi @bforcier1 , thanks for reporting, and apologies for the long delay. This should be (hopefully) fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!

**Comment by whummer** [comment]
Closing this issue due to inactivity. Please let us know if the problem persists with the `latest` Docker image. Thanks!
