### ISSUE TITLE
Can not import external library 

### ISSUE THREAD

**Issue by fatihtekin** [localstack/localstack#494]
I get an error as below when I want to import google library in the Python3.6 environment. I am giving google in the libs array while calling 'create_lambda_archive' and I checked that I have it installed so it goes into the zip file. Can someone please help me to fix? 

Probably related to below ticket but I don't know which version I should use I am using 0.8.3
https://github.com/localstack/localstack/issues/53

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/localstack/services/awslambda/lambda_api.py", line 378, in exec_lambda_code
    handler_module = imp.load_source(lambda_id, lambda_file)
  File "/private/var/folders/2c/v8br1429019337b13gt1xph40000gp/T/localstack/lambda_script_l_e9092860.py", line 12, in <module>
    from google.cloud.bigquery.job import ExtractJobConfig, DestinationFormat
ImportError: No module named google.cloud.bigquery.job

2017-12-04T15:22:13:WARNING:localstack.services.awslambda.lambda_api: Unknown error: ('Unable to get handler function from lambda code.', ImportError('No module named google.cloud.bigquery.job',))
```

```
localstack --version
0.8.3
```

LAMBDA_RUNTIME_PYTHON36

**Comment by whummer** [comment]
Thanks for reporting @fatihtekin . Any chance you can share your zip file, or at least list the contents like so:
```
unzip -t <your_zip_archive>
```
If you want to import an external library in your lambda, you may need to create an `__init__.py` file in each folder along the import path - is that the case?

**Comment by fatihtekin** [comment]
that issue not happening in integration test only happens with docker so closing

**Comment by whummer** [comment]
Thanks for confirming that it now works for you. Closing this issue.
