### ISSUE TITLE
Issue with python 3.6 runtime

### ISSUE THREAD

**Issue by fatihtekin** [localstack/localstack#495]
when trying  https://github.com/localstack/localstack/blob/master/tests/integration/lambdas/lambda_python3.py getting below error. Can someone let me know what I am doing wrong?

```
2017-12-04T22:39:32:ERROR:localstack.services.awslambda.lambda_api: Unable to exec: def handler(event, context):
    # the following line is Python 3.6+ specific
    msg = f'Successfully processed {event}'  # noqa This code is Python 3.6+ only
    return event Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/localstack/services/awslambda/lambda_api.py", line 378, in exec_lambda_code
    handler_module = imp.load_source(lambda_id, lambda_file)
  File "/private/var/folders/2c/v8br1429019337b13gt1xph40000gp/T/localstack/lambda_script_l_d01e07c9.py", line 3
    msg = f'Successfully processed {event}'  # noqa This code is Python 3.6+ only
                                          ^
SyntaxError: invalid syntax
```

Test Code
```
def test_upload_lambda_from_s3():

    s3_client = aws_stack.connect_to_service('s3')
    lambda_client = aws_stack.connect_to_service('lambda')

    lambda_name = 'test_lambda_%s' % short_uid()
    bucket_name = 'test_bucket_lambda'
    bucket_key = 'test_lambda.zip'

    # upload zip file to S3
    zip_file = testutil.create_lambda_archive(load_file(TEST_LAMBDA_PYTHON), get_content=True,
                                              libs=TEST_LAMBDA_LIBS, runtime=LAMBDA_RUNTIME_PYTHON36)
    s3_client.create_bucket(Bucket=bucket_name)
    s3_client.upload_fileobj(BytesIO(zip_file), bucket_name, bucket_key)
    # create lambda function
    lambda_client.create_function(
        FunctionName=lambda_name, Handler='handler.handler',
        Runtime=lambda_api.LAMBDA_RUNTIME_PYTHON36, Role='r1',
        Code={
            'S3Bucket': bucket_name,
            'S3Key': bucket_key
        }
    )
```

**Comment by whummer** [comment]
Thanks for reporting @fatihtekin . Which version of Python are you using? I'd assume your Python version is lower than 3.6?
```
python --version
```
Note that we added this test Lambda specifically to test compatibility with specific versions of Python. To make this Lambda executable in your Python environment, you could simply comment out this line in `lambda_python3.py`:
```
msg = f'Successfully processed {event}'
```

**Comment by fatihtekin** [comment]
Hi

I am using python3.6 in my environment.
