### ISSUE TITLE
bug: license key activation apparently fails DNS resolution

### ISSUE THREAD

**Issue by BatmanAoD** [localstack/localstack#4958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After launching `localstack` with either the light or the full image, during the `Waiting for all LocalStack services to be ready` setup, I see the following error:

```
2021-11-18T23:02:49.618:WARNING:localstack_ext.bootstrap.licensing: Error activating API key <redacted>(10): MyHTTPSConnectionPool(host='api.localstack.cloud', port=443): Max retries exceeded with url: /v1/activate (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1469f5f460>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')) Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/bootstrap/licensing.py", line 54, in fetch_key
    result=requests.post("%s/activate"%config.API_URL,json.dumps(data),verify=vfCaA)
  File "/opt/code/localstack/localstack/utils/common.py", line 1915, in _wrapper
    return method(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: MyHTTPSConnectionPool(host='api.localstack.cloud', port=443): Max retries exceeded with url: /v1/activate (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9e598612b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

From the Ubuntu command line, `curl api.localstack.cloud:443` returns `400 Bad Request`, so the host appears to be reachable.

### Expected Behavior

Successful validation of license key

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

With `LOCALSTACK_API_KEY` exported as an environment variable:

    USE_LIGHT_IMAGE=0 DATA_DIR=$PWD/localstack-data/ localstack start

### Environment

```markdown
- OS: Ubuntu 20.04.3 on WSL (5.10.60.1-microsoft-standard-WSL2, Windows 11 host)
- LocalStack: 0.13.0
```

**Comment by mgagliardo** [comment]
Hello @BatmanAoD, can you share a bit more details? What does your DNS resolve if you run `nslookup api.localstack.cloud`? Maybe testing with Google or Cloudflare's DNS?

I have just tested this on two different computers and worked ok:

```
$ LOCALSTACK_API_KEY=123.. USE_LIGHT_IMAGE=0 DATA_DIR=$PWD/localstack-data/ localstack start
...
[23:23:05] starting LocalStack in Docker mode 🐳                                                                              localstack.py:106
──────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ────────────────────────────────────────────────
2021-11-18T23:23:11:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
```

**Comment by BatmanAoD** [comment]
That's odd...I can't reproduce the issue from my current internet connection. It must have something to do with the specific network I was on.
