### ISSUE TITLE
bug: Containers are not deleted after calling ECS Run-Task

### ISSUE THREAD

**Issue by JacobReynolds** [localstack/localstack#4967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When calling `awslocal ecs run-task...` the container is not deleted after completion. This causes a naming collision and future calls to `run-task` fail. 

### Expected Behavior

The container should be deleted when execution is finished, so future calls to `run-task` succeed. Alternatively, the container names should include a random identifier, so you can have multiple occurrences of the same task running.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

1) Create an ECS task definition and cluster. Apologies, but I don't have any good templates to share for these at the moment
2) `awslocal ecs run-task --task-definition <task-definition> --cluster <cluster>`
3) Wait for completion, and run again
4) Observe error

```
2021-11-19T21:12:22:INFO:localstack_ext.services.ecs.ecs_listener: Starting ECS task in Docker: image "localhost:4510/image_name", container "container_name", command "index.js"
2021-11-19T21:12:22:DEBUG:localstack_ext.services.ecs.ecs_listener: Image: localhost:4510/repo/task-name-ecs Name: localstack_task-name_1_0 Cmd: index.js kwargs: {'command': 'index.js'}
2021-11-19T21:12:22:DEBUG:localstack.utils.docker_utils: Running container with image: localhost:4510/repo/task-name-ecs
2021-11-19T21:12:22:DEBUG:localstack.utils.docker_utils: Creating container with image localhost:4510/repo/task-name-ecs, command 'index.js', volumes None, env vars [REDACTED[]]
2021-11-19T21:12:22:ERROR:localstack_ext.services.ecs.ecs_listener: Execution of ECS task f31ae9da failed:  - Output: 
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.41/containers/create?name=localstack_task-name_1_0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/docker_utils.py", line 1414, in create_container
    container = create_container()
  File "/opt/code/localstack/localstack/utils/docker_utils.py", line 1396, in create_container
    return self.client().containers.create(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/models/containers.py", line 870, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=localstack_task-name_1_0: Conflict ("Conflict. The container name "/localstack_task-name_1_0" is already in use by container "5479d00ad99f73482f5d7e56d54652bd6905a9706ec9a18049410c8dec45866a". You have to remove (or rename) that container to be able to reuse that name.")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/ecs/ecs_listener.py.enc", line 75, in do_run
  File "/opt/code/localstack/localstack/utils/docker_utils.py", line 1449, in run_container
    container = self.create_container(
  File "/opt/code/localstack/localstack/utils/docker_utils.py", line 1422, in create_container
    raise ContainerException()
localstack.utils.docker_utils.ContainerException
```

### Environment

```markdown
- OS: 
MacOS Big Sur 11.1

- LocalStack: 
0.13.0
```

**Comment by dfangl** [comment]
This should be fixed in the newest docker release. Thanks for reporting this! If you have any more issues with this, please do not hesitate to reopen.
