### ISSUE TITLE
bug: Lambda service start unreliable on 0.13.0

### ISSUE THREAD

**Issue by dmarkey** [localstack/localstack#4973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

50% of the time, using the localstack docker container, the lambda service does not come up reliably:

```
2021-11-20T15:06:49:ERROR:localstack.services.awslambda.lambda_starter: Lambda health check failed
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_starter.py", line 37, in check_lambda
    wait_for_port_open(port)  # TODO get lambda port in a cleaner way
  File "/opt/code/localstack/localstack/utils/common.py", line 660, in wait_for_port_open
    return wait_for_port_status(
  File "/opt/code/localstack/localstack/utils/common.py", line 693, in wait_for_port_status
    return retry(check, sleep=sleep_time, retries=retries)
  File "/opt/code/localstack/localstack/utils/common.py", line 796, in retry
    raise raise_error
  File "/opt/code/localstack/localstack/utils/common.py", line 792, in retry
    return function(**kwargs)
  File "/opt/code/localstack/localstack/utils/common.py", line 688, in check
    raise Exception(
Exception: Port 34547 (path: None) was not open
2021-11-20T15:06:49:ERROR:localstack.services.plugins: error while checking service lambda:
2021-11-20T15:06:49:INFO:bootstrap.py: Execution of "require" took 5589.73ms
2021-11-20T15:06:49:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localstack.mise.rrilabs.co/2015-03-31/functions: failed to get service for lambda:  Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/edge.py", line 220, in _require_service
    self.service_manager.require(api)
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/plugins.py", line 331, in require
    raise container.errors[-1]
  File "/opt/code/localstack/localstack/services/plugins.py", line 239, in check
    self.service.check(print_error=True)
  File "/opt/code/localstack/localstack/services/plugins.py", line 184, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_starter.py", line 49, in check_lambda
    assert out and isinstance(out.get("Functions"), list)
AssertionError
```

### Expected Behavior

That the lambda service comes up and does not spew exceptions.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Start localstack on Kubernetes(k3s) with the "serverless" suite

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I'm using company terraform that I cannot share.

### Environment

```markdown
- OS: Official Docker container on K3s on ubuntu 21.04, dind side-car.
- LocalStack: v0.13.0
```

### Anything else?

Tried with Eager both on and off, seems as unreliable either way. Works fine on v0.12.20 from what I can see.

**Comment by dmarkey** [comment]
Actually, after a few tries, I'm seeing the same problem on 0.12.20 :(

```
2021-11-20T15:22:55:INFO:bootstrap.py: Execution of "prepare_environment" took 1372.76ms
[2021-11-20 15:22:56 +0000] [21] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-11-20T15:22:56:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-11-20T15:22:56:INFO:bootstrap.py: Execution of "start_runtime_components" took 613.68ms
2021-11-20T15:22:58:INFO:bootstrap.py: Execution of "_load_service_plugin" took 1453.97ms
2021-11-20T15:22:58:INFO:bootstrap.py: Execution of "require" took 1454.59ms
2021-11-20T15:22:58:INFO:localstack.services.infra: Starting mock API Gateway service on http port 4566 ...
2021-11-20T15:22:58:INFO:localstack.services.motoserver: starting moto server on http://0.0.0.0:35157
2021-11-20T15:23:02:INFO:bootstrap.py: Execution of "_load_service_plugin" took 4317.02ms
2021-11-20T15:23:02:INFO:localstack.services.infra: Starting mock CloudFormation service on http port 4566 ...
2021-11-20T15:23:02:INFO:bootstrap.py: Execution of "require" took 4591.53ms
2021-11-20T15:23:02:INFO:localstack.services.infra: Starting mock CloudWatch service on http port 4566 ...
2021-11-20T15:23:03:INFO:localstack.services.infra: Starting mock DynamoDB service on http port 4566 ...
2021-11-20T15:23:04:INFO:localstack.services.dynamodb.server: Initializing DynamoDB Local with the following configuration:
2021-11-20T15:23:04:INFO:localstack.services.dynamodb.server: Port:	32967
2021-11-20T15:23:04:INFO:localstack.services.dynamodb.server: InMemory:	true
2021-11-20T15:23:04:INFO:localstack.services.dynamodb.server: DbPath:	null
2021-11-20T15:23:04:INFO:localstack.services.dynamodb.server: SharedDb:	false
2021-11-20T15:23:04:INFO:localstack.services.dynamodb.server: shouldDelayTransientStatuses:	false
2021-11-20T15:23:04:INFO:localstack.services.dynamodb.server: CorsParams:	*
2021-11-20T15:23:04:INFO:localstack.services.dynamodb.server:
2021-11-20T15:23:07:INFO:bootstrap.py: Execution of "require" took 4472.61ms
2021-11-20T15:23:07:INFO:localstack.services.infra: Starting mock DynamoDB Streams service on http port 4566 ...
2021-11-20T15:23:07:INFO:localstack.services.infra: Starting mock EC2 service on http port 4566 ...
2021-11-20T15:23:07:INFO:localstack.services.infra: Starting mock Cloudwatch Events service on http port 4566 ...
2021-11-20T15:23:07:INFO:localstack.services.infra: Starting mock IAM service on http port 4566 ...
2021-11-20T15:23:07:INFO:localstack.services.infra: Starting mock Kinesis service on http port 4566 ...
2021-11-20T15:23:08:INFO:bootstrap.py: Execution of "require" took 1247.18ms
2021-11-20T15:23:08:INFO:localstack.services.infra: Starting mock KMS service on http port 4566 ...
2021-11-20T15:23:08:INFO:localstack.services.infra: Starting mock Lambda service on http port 4566 ...
2021-11-20T15:23:14:ERROR:localstack.services.awslambda.lambda_starter: Lambda health check failed
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_starter.py", line 37, in check_lambda
    wait_for_port_open(port)  # TODO get lambda port in a cleaner way
  File "/opt/code/localstack/localstack/utils/common.py", line 660, in wait_for_port_open
    sleep_time=sleep_time,
  File "/opt/code/localstack/localstack/utils/common.py", line 688, in wait_for_port_status
    return retry(check, sleep=sleep_time, retries=retries)
  File "/opt/code/localstack/localstack/utils/common.py", line 791, in retry
    raise raise_error
  File "/opt/code/localstack/localstack/utils/common.py", line 787, in retry
    return function(**kwargs)
  File "/opt/code/localstack/localstack/utils/common.py", line 685, in check
    % (port, http_path, "closed" if expect_closed else "open")
Exception: Port 55275 (path: None) was not open
2021-11-20T15:23:14:ERROR:localstack.services.plugins: error while checking service lambda:
2021-11-20T15:23:14:INFO:bootstrap.py: Execution of "require" took 5519.35ms
2021-11-20T15:23:14:ERROR:localstack.services.infra: could not load service plugin lambda
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 475, in preload_services
    SERVICE_PLUGINS.require(api)
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 91, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/plugins.py", line 331, in require
    raise container.errors[-1]
  File "/opt/code/localstack/localstack/services/plugins.py", line 239, in check
    self.service.check(print_error=True)
  File "/opt/code/localstack/localstack/services/plugins.py", line 184, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_starter.py", line 49, in check_lambda
    assert out and isinstance(out.get("Functions"), list)
AssertionError
```

**Comment by whummer** [comment]
Hi @dmarkey , thanks for reporting. We have recently added a couple of enhancements for the startup/lifecycle of individual services. Can you please pull the `latest` Docker image (or latest tagged version `0.13.2`) and confirm if this is fixed in the meantime? Thanks!

**Comment by teodorescuserban** [comment]
Same issue persists on 0.14.
Running your official docker image.

**Comment by Napas** [comment]
@teodorescuserban I had exactly the same issue. In my case, it was because of misconfiguration of the path to the Docker socket.

Easy way to check if it's the same issue - execute `docker ps` from the localstack container.

**Comment by teodorescuserban** [comment]
Thank you for input, @Napas. Unfortunately no, nothing is wrong with my docker socket path. I ended up using the 0.12.18 version which worked fine. I will go back to the issue in the future to upgrade and see if the last version then works.

**Comment by pennytextures** [comment]
This is an issue for me when I use LAMBDA_DOCKER_NETWORK, it works ok if this option isn't used, however this isn't an acceptable workaround for me, I need lambdas to be on the same network as the rest of my compose environment.

**Comment by pennytextures** [comment]
This is really easy to replicate

[recreate_issue.sh.txt](https://github.com/localstack/localstack/files/8124123/recreate_issue.sh.txt)

**Comment by vogje01** [comment]
Same issue persists on 0.14.1.

**Comment by cheungnj** [comment]
I'm seeing this issue on 0.14.3 and 0.14.4.dev with different git hashes.
