### ISSUE TITLE
bug: Error in AWS SDK for JS when using the Cognito emulator.

### ISSUE THREAD

**Issue by david-wb** [localstack/localstack#4975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using the AWS SDK for JS v3 with a localstack Cognito endpoint, like so

```typescript
import {
  CognitoIdentityProviderClient,
  ListUserPoolsCommand,
} from "@aws-sdk/client-cognito-identity-provider";

const client = new CognitoIdentityProviderClient({
  region: "us-west-2",
  endpoint: "http://localhost:4566",
});

const getUserPoolId = async () => {
  const command = new ListUserPoolsCommand({
    MaxResults: 1,
  });
  const response = await client.send(command);
  const poolId = response.UserPools?.[0]?.Id;
  if (!poolId) {
    throw new Error("No user pool was found.");
  }
  return poolId;
};


getUserPoolId();
```

This throws an error from within the AWS SDK:
```bash
TypeError: Expected number, got string
    at Object.expectNumber (node_modules/@aws-sdk/smithy-client/dist-cjs/parse-utils.js:32:11)
    at deserializeAws_json1_1UserPoolDescriptionType (node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/protocols/Aws_json1_1.js:15077:97)
    at /node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/protocols/Aws_json1_1.js:15097:16
    at Array.map (<anonymous>)
    at deserializeAws_json1_1UserPoolListType (node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/protocols/Aws_json1_1.js:15093:10)
    at deserializeAws_json1_1ListUserPoolsResponse (node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/protocols/Aws_json1_1.js:14383:15)
    at Object.deserializeAws_json1_1ListUserPoolsCommand (node_modules/@aws-sdk/client-cognito-identity-provider/dist-cjs/protocols/Aws_json1_1.js:8327:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:6:20
    at async /node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
```

Interestingly, running other commands such as `ListUserPoolClientsCommand` works with out issues, as does using the `awslocal` cli, so I believe this is a bug in the cognito emulator.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Here's an AWS SDK code snippet you can use to reproduce the error.
```typescript
import {
  CognitoIdentityProviderClient,
  ListUserPoolsCommand,
} from "@aws-sdk/client-cognito-identity-provider";

const client = new CognitoIdentityProviderClient({
  region: "us-west-2",
  endpoint: "http://localhost:4566",
});

const getUserPoolId = async () => {
  const command = new ListUserPoolsCommand({
    MaxResults: 1,
  });
  const response = await client.send(command);
  const poolId = response.UserPools?.[0]?.Id;
  if (!poolId) {
    throw new Error("No user pool was found.");
  }
  return poolId;
};


getUserPoolId();
```

And here is the compose file:
```yml
version: "3.0"
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    environment:
      SERVICES: cognito,s3
      LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY}
      AWS_DEFAULT_REGION: us-west-2
```

### Environment

```markdown
- OS: MacOS
- LocalStack: Latest
```

### Anything else?

Thanks for your help and for providing this excellent tool.

**Comment by whummer** [comment]
Hi @david-wb , thanks for reporting. We have now pushed a few enhancements in Cognito which should (hopefully) resolve this issue. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks for your help!
