### ISSUE TITLE
question: is there a hard limit to the number of ECR repositories that can be created?

### ISSUE THREAD

**Issue by mattfiocca** [localstack/localstack#4991]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Are we limited to 30 ECR repos with a PRO key?

When creating ECR repositories, it appears that localstack is earmarking ports 4510-4539, one for each repo, with a hard stop at port 4539. The problem is that I have 34 repos that I need to create, one for each of my lambdas. (maybe i'm using ECR incorrectly, but that's just where i'm at right now).

So, when attempting to create the 31st repo, it looks like localstack is saying that i've run out of ports:
```
2021-11-23T15:24:03.536:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: No free network ports available to start service instance: [] Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 159, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 86, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/opt/code/localstack/localstack/utils/run.py", line 153, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 669, in handler
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 205, in modify_and_forward
    result = modify_and_forward_orig(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 338, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py.enc", line 197, in forward_request
  File "/opt/code/localstack/localstack/services/edge.py", line 169, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py.enc", line 191, in do_forward_request
  File "/opt/code/localstack/localstack/services/edge.py", line 224, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 247, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 414, in modify_and_forward
    updated_response = update_listener.return_response(**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/ecr/ecr_listener.py.enc", line 112, in return_response
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/ecr/ecr_listener.py.enc", line 199, in start_repository
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/common.py.enc", line 244, in get_available_service_instance_port
Exception: No free network ports available to start service instance: []
```

Is this because port 4540 onward conflicts with other services?

I am also noticing that when trying to create repositories that extend past port 4539, the repo descriptions start changing from this:
```json
{
	"repositoryArn": "arn:aws:ecr:us-west-2:000000000000:repository/<repo-name>",
	"registryId": "<unique-registry-id>",
	"repositoryName": "<repo-name>",
	"repositoryUri": "localhost:4539/<repo-name>",
	"createdAt": "2021-11-23T09:12:48-06:00",
	"imageTagMutability": "MUTABLE",
	"imageScanningConfiguration": {
		"scanOnPush": false
	},
	"encryptionConfiguration": {
		"encryptionType": "AES256"
	}
}
```

to this:
```json
{
	"repositoryArn": "arn:aws:ecr:us-west-2:000000000000:repository/<repo-name>",
	"registryId": "000000000000",
	"repositoryName": "<repo-name>",
	"repositoryUri": "000000000000.dkr.ecr.us-west-2.amazonaws.com/<repo-name>",
	"createdAt": "2021-11-23T09:13:31-06:00",
	"imageTagMutability": "MUTABLE",
	"imageScanningConfiguration": {
		"scanOnPush": false
	},
	"encryptionConfiguration": {
		"encryptionType": "AES256"
	}
}
```

Noting that the URI changes from localhost to AWS' remote ECR uri. This makes sense i guess if we can't host the repo locally because ports are out range. 

So, is it true that we are limited to 30 ECR repos/ports, or am I missing something important in configuration?

**Comment by whummer** [comment]
Hi @mattfiocca , thanks for reaching out. Please note that you can customize the service port range via:
```
export SERVICE_INSTANCES_PORTS_START=4510
export SERVICE_INSTANCES_PORTS_END=4550
```
Hope that helps. We'll make sure to better highlight this in our documentation.. Thanks!

**Comment by mattfiocca** [comment]
That works perfectly; thank you!
