### ISSUE TITLE
Cannot use KMS Sign command with localstack & testcontainers

### ISSUE THREAD

**Issue by danilopereira** [localstack/localstack#4992]
# Type of request: This is a ...
[X] bug report
[ ] feature request

# Detailed description
I am using localstack & testcontainers for mocking KMS locally to test my APIs and I need to generate data key "pairs". When calling sign() API, I get the following exception. I see that is not supported currently. Do you have any precision to add it?
Version I am using:
"localstack/localstack:0.13.0"

gradle file:
testImplementation("org.testcontainers:localstack:1.16.12")
// for aws KMS
implementation("com.amazonaws:aws-java-sdk-kms:1.12.115")

## Expected behavior
I should be able to retrieve a sign.
...

## Actual behavior
Getting the following exception when using these APIs:
```API action 'TrentService.Sign' for service 'kms' not yet implemented (Service: Kms, Status Code: 501, Request ID: null, Extended Request ID: null)
software.amazon.awssdk.services.kms.model.KmsException: API action 'TrentService.Sign' for service 'kms' not yet implemented (Service: Kms, Status Code: 501, Request ID: null, Extended Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:79)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
```
...

# Steps to reproduce
## Command used to start LocalStack
...

Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```kotlin
LocalStackContainer = LocalStackContainer(DockerImageName.parse("localstack/localstack:0.13.0"))
.withServices(KMS)
.also { it.start() }

val desc = String.format("AWS CMK Description")
val createdByTag: Tag = Tag.builder().tagKey("CreatedBy").tagValue("StorageService").build()
val req: CreateKeyRequest = CreateKeyRequest.builder()
            .description(desc).tags(createdByTag)
            .keySpec(KeySpec.ECC_NIST_P256)
            .keyUsage(KeyUsageType.SIGN_VERIFY)
            .build()
val key = kmsClient.createKey(req)

val signRequest = SignRequest.builder().keyId(key.keyMetadata().keyId()).message(SdkBytes.fromString("something", 
    Charsets.UTF_8)).signingAlgorithm("ECC_NIST_P256").build()
val signResponse = kmsClient.sign { signRequest }
```
...

**Comment by whummer** [comment]
Thanks for reporting @danilopereira . This should be (hopefully) fixed in the meantime (via #5021) - can you please pull the `latest` Docker image and give it another try?

Please let us know if the problem persists with the latest version. Alternatively, you could try switching to a different KMS provider, by setting `KMS_PROVIDER=local-kms` in your LocalStack container environment. The `local-kms` provider likely has the functionality you require (but it may be missing a few other features, like multi-region or persistence support). Thanks!
