### ISSUE TITLE
bug: timeout accessing s3 from Lambda container

### ISSUE THREAD

**Issue by whiterice42** [localstack/localstack#4995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Containerized Python lambda function times out when accessing s3 bucket.  The lambda function can successfully write to the s3 bucket with boto3 put_object, but attempts to access s3 (including put_object and get_object) do not return/finish, meaning that the lambda hangs on the call to put_object or get_object.

```
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2021-11-23 20:13:38,224 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_1  | 2021-11-23 20:13:38,226 INFO supervisord started with pid 15
localstack_1  | 2021-11-23 20:13:39,231 INFO spawned: 'infra' with pid 21
localstack_1  | (. .venv/bin/activate; exec bin/localstack start --host --no-banner)
localstack_1  |
localstack_1  | LocalStack version: 0.13.0
localstack_1  | LocalStack Docker container id: 581da81f0cab
localstack_1  | LocalStack build date: 2021-11-15
localstack_1  | LocalStack build git hash: 595eaef0
localstack_1  |
localstack_1  | 2021-11-23T20:13:39:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7f30c0ccf670>
localstack_1  | 2021-11-23T20:13:39:DEBUG:localstack.utils.run: Executing command: which psql
localstack_1  | 2021-11-23T20:13:39:DEBUG:localstack.utils.run: Executing command: which pg_config
localstack_1  | 2021-11-23T20:13:39:DEBUG:localstack.utils.run: Executing command: which redis-server
localstack_1  | 2021-11-23T20:13:39:DEBUG:localstack.utils.run: Executing command: which mosquitto
localstack_1  | 2021-11-23 20:13:40,848 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 2021-11-23T20:13:40:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
localstack_1  | 2021-11-23T20:13:41:DEBUG:localstack.utils.run: Executing command: whoami
localstack_1  | 2021-11-23T20:13:41:DEBUG:localstack.utils.run: Executing command:  python -c "import sys; f=open(sys.argv[1]).read(); open(sys.argv[1], 'w').write('\n' + f)" /etc/resolv.conf
localstack_1  | 2021-11-23T20:13:41:DEBUG:localstack.utils.run: Executing command:  python -c "import sys; f=open(sys.argv[1]).read(); open(sys.argv[1], 'w').write('nameserver 0.0.0.0\n' + f)" /etc/resolv.conf
localstack_1  | 2021-11-23T20:13:41:DEBUG:localstack.utils.run: Executing command:  python -c "import sys; f=open(sys.argv[1]).read(); open(sys.argv[1], 'w').write('# The following line is required by LocalStack\n' + f)" /etc/resolv.conf
localstack_1  | Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
localstack_1  | Starting edge router (http port 4566)...
localstack_1  | Starting edge router (https port 443)...
localstack_1  | Ready.
localstack_1  | 2021-11-23T20:13:44:INFO:localstack_ext.utils.aws.metadata_service: Starting AWS instance metadata service on port 80
localstack_1  | 2021-11-23T20:13:44:INFO:botocore.credentials: Found credentials in environment variables.
localstack_1  | 2021-11-23T20:13:44:INFO:botocore.credentials: Found credentials in environment variables.
localstack_1  | [2021-11-23 20:13:44 +0000] [23] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_1  | 2021-11-23T20:13:44:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_1  | [2021-11-23 20:13:44 +0000] [23] [INFO] Running on https://0.0.0.0:443 (CTRL + C to quit)
localstack_1  | 2021-11-23T20:13:44:INFO:hypercorn.error: Running on https://0.0.0.0:443 (CTRL + C to quit)
localstack_1  | 2021-11-23T20:13:44:DEBUG:localstack.utils.persistence: saving startup info StartupInfo(timestamp='2021-11-23T20:13:44.848945', localstack_version='0.13.0', localstack_ext_version='0.13.0', pro_activated=True)
localstack_1  | 2021-11-23T20:13:58:INFO:localstack.services.infra: Starting mock Lambda service on http ports 443/4566 ...
localstack_1  | 2021-11-23 20:13:58,942:API:  * Running on all addresses.
localstack_1  |    WARNING: This is a development server. Do not use it in a production deployment.
localstack_1  | 2021-11-23T20:13:59:INFO:botocore.credentials: Found credentials in environment variables.
localstack_1  | 2021-11-23T20:13:59:INFO:localstack.services.awslambda.lambda_executors: Empty event body specified for invocation of Lambda "arn:aws:lambda:us-west-2:000000000000:function:test-lambda"
localstack_1  | 2021-11-23T20:13:59:INFO:localstack.services.awslambda.lambda_utils: Determined main container target IP: 172.21.0.2
localstack_1  | 2021-11-23T20:13:59:INFO:localstack.services.awslambda.lambda_executors: Running lambda: arn:aws:lambda:us-west-2:000000000000:function:test-lambda
localstack_1  | 2021-11-23T20:13:59:DEBUG:localstack_ext.services.awslambda.lambda_extended: Putting invocation event (request ID 3a83695c) for Lambda 'arn:aws:lambda:us-west-2:000000000000:function:test-lambda' to queue
localstack_1  | 2021-11-23T20:13:59:DEBUG:localstack_ext.services.awslambda.lambda_launcher: Executing custom image execution for image test-lambda:latest
localstack_1  | 2021-11-23T20:13:59:DEBUG:localstack.utils.docker_utils: Getting the entrypoint for image: test-lambda:latest
localstack_1  | 2021-11-23T20:13:59:DEBUG:localstack.utils.docker_utils: Running container with image: test-lambda:latest
localstack_1  | 2021-11-23T20:13:59:DEBUG:localstack.utils.docker_utils: Creating container with image test-lambda:latest, command '['handler.handler']', volumes [('C:\\Users\\WhiteRice~1\\AppData\\Local\\Temp/localstack', '/tmp')], env vars {'AWS_ACCESS_KEY_ID': 'test', 'AWS_SECRET_ACCESS_KEY': 'test', 'AWS_REGION': 'us-west-2', 
'DOCKER_LAMBDA_USE_STDIN': '1', 'LOCALSTACK_HOSTNAME': '172.21.0.2', 'AWS_ENDPOINT_URL': 'http://172.21.0.2:4566', 'EDGE_PORT': '443', '_HANDLER': 'handler.handler', 'AWS_LAMBDA_FUNCTION_TIMEOUT': '120', 'AWS_LAMBDA_FUNCTION_NAME': 'test-lambda', 'AWS_LAMBDA_FUNCTION_VERSION': '$LATEST', 'AWS_LAMBDA_FUNCTION_INVOKED_ARN': 'arn:aws:lambda:us-west-2:000000000000:function:test-lambda', 'AWS_LAMBDA_COGNITO_IDENTITY': '{}', 'AWS_LAMBDA_FUNCTION_MEMORY_SIZE': 1536, '_LAMBDA_RUNTIME': None, 'AWS_LAMBDA_LOG_GROUP_NAME': '/aws/lambda/test-lambda', 'AWS_LAMBDA_LOG_STREAM_NAME': 'test', 'AWS_LAMBDA_RUNTIME_API': 'test-lambda.us-west-2.localhost.localstack.cloud:4566', 'LOCALSTACK_HOSTS_ENTRY': 'test-lambda.us-west-2.localhost.localstack.cloud', 'LOCALSTACK_DEBUG': '1'}
localstack_1  | 2021-11-23T20:13:59:DEBUG:localstack.utils.docker_utils: Starting container 93e35ea46053d1a42233cca41f1bb6d5b9566a052c2a95788419d624064f1bbf
localstack_1  | 2021-11-23T20:14:00:DEBUG:localstack_ext.services.awslambda.lambda_extended: Waiting for Lambda invocation result of request ID 3a83695c
localstack_1  | 2021-11-23T20:14:01:INFO:botocore.credentials: Found credentials in environment variables.
localstack_1  | 2021-11-23T20:14:01:DEBUG:localstack_ext.services.awslambda.lambda_extended: Received /invocation/next call from Lambda container, waiting for invocation of "arn:aws:lambda:us-west-2:000000000000:function:test-lambda" in us-west-2
localstack_1  | 2021-11-23T20:14:01:DEBUG:localstack_ext.services.awslambda.lambda_extended: Sending next invocation event (request ID 3a83695c) for Lambda "arn:aws:lambda:us-west-2:000000000000:function:test-lambda": {}
localstack_1  | 2021-11-23T20:14:01:INFO:localstack.services.motoserver: starting moto server on http://0.0.0.0:32903
localstack_1  | 2021-11-23T20:14:01:INFO:localstack.services.infra: Starting mock S3 service on http ports 443/4566 ...
localstack_1  | 2021-11-23T20:14:10:ERROR:localstack_ext.services.awslambda.lambda_extended: Unable to invoke Lambda "arn:aws:lambda:us-west-2:000000000000:function:test-lambda": 
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 454, in do_run_lambda_executor
localstack_1  |   File "/usr/local/lib/python3.8/queue.py", line 178, in get
localstack_1  |     raise Empty
localstack_1  | _queue.Empty
localstack_1  | 2021-11-23T20:14:10:DEBUG:localstack_ext.services.awslambda.lambda_extended: Log output for invocation of Lambda "test-lambda": INIT: Using Lambda API Runtime target host: 'test-lambda.us-west-2.localhost.localstack.cloud:4566'
localstack_1  | cat: -: No such file or directory
localstack_1  | INIT: Host 'test-lambda.us-west-2.localhost.localstack.cloud' resolves to '172.21.0.2'
localstack_1  |
localstack_1  | 2021-11-23T20:14:10:INFO:localstack.services.infra: Starting mock CloudWatch Logs service on http ports 443/4566 ...
localstack_1  | 2021-11-23T20:14:10:DEBUG:localstack.services.plugins: checking service health logs:32903
localstack_1  | 2021-11-23T20:14:10:DEBUG:localstack.utils.docker_utils: Removing container: 93e35ea46053d1a42233cca41f1bb6d5b9566a052c2a95788419d624064f1bbf
localstack_1  | 2021-11-23T20:14:10:INFO:localstack.services.infra: Starting mock CloudWatch service on http ports 443/4566 ...
localstack_1  | 2021-11-23T20:14:10:DEBUG:localstack.services.plugins: checking service health cloudwatch:32903
localstack_1  | 2021-11-23T20:14:10:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-west-2:000000000000:function:test-lambda: Timeout - Lambda container did not report result after 120 secs Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 454, in do_run_lambda_executor
localstack_1  |   File "/usr/local/lib/python3.8/queue.py", line 178, in get
localstack_1  |     raise Empty
localstack_1  | _queue.Empty
localstack_1  |
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  |
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 809, in run_lambda
localstack_1  |     result = LAMBDA_EXECUTOR.execute(
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 429, in execute
localstack_1  |     return do_execute()
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 419, in do_execute
localstack_1  |     return _run(func_arn=func_arn)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 158, in wrapped
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 154, in wrapped
localstack_1  |     result = func(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 406, in _run
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 402, in _run
localstack_1  |     result = self._execute(lambda_function, inv_context)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 710, in _execute
localstack_1  |     result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 540, in run_lambda_executor
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 436, in run_lambda_executor
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 461, in do_run_lambda_executor
localstack_1  | localstack.services.awslambda.lambda_executors.InvocationException: Timeout - Lambda container did not report result after 120 secs
```

### Expected Behavior

The lambda can access s3 without timing out.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose.yml
```
version: "3.8"
services:
  localstack:
    image: localstack/localstack:0.13.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,s3
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=localstack-test
      - HOST_TMP_FOLDER=$TEMP/localstack
    volumes:
      - "$TEMP/localstack:/tmp/localstack"
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - localstack-test
    env_file:
      - .env
networks:
  localstack-test:
    driver: bridge
    external: false
    name: localstack-test
```

handler.py
```
import os
import json
import boto3


s3_client = boto3.client('s3', region_name='us-west-2', aws_access_key_id="test", aws_secret_access_key="test",
                         endpoint_url=f'http://{os.getenv("LOCALSTACK_HOSTNAME")}:4566')


def handler(event, context):
    bucket = 'test-bucket'
    body = 'hello world'.encode('utf-8')
    key = 'hello.txt'

    s3_client.put_object(
        Bucket=bucket,
        Body=body,
        Key=key,
    )

    return {
        'statusCode': 200,
        'headers': {'Content-Type': 'application/json; charset=utf-8'},
        'body': json.dumps({'response': 'successful'})
    }
```

Dockerfile
```
FROM public.ecr.aws/lambda/python:3.8
WORKDIR /TestLambda
RUN pip install requests
COPY ./handler.py ./handler.py
CMD ["handler.handler"]
```

Client code: 
awslocal lambda create-function --function-name test-lambda --code ImageUri=test-lambda:latest --role arn:aws:iam::000000000:role/lambda-role --timeout 120

awslocal s3api create-bucket --bucket test-bucket --region us-west-2

(times out)
awslocal lambda invoke --function-name arn:aws:lambda:us-west-2:000000000000:function:test-lambda response.json

awslocal s3api list-objects --bucket test-bucket
returns
```
{
    "Contents": [
        {
            "Key": "hello.txt",
            "LastModified": "2021-11-23T19:50:15+00:00",
            "ETag": "\"5eb63bbbe01eeed093cb22bb8f5acdc3\"",
            "Size": 11,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "webfile",
                "ID": "75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a"
            }
        }
    ]
}
```

### Environment

```markdown
- OS: Windows 10
- LocalStack: 0.13.0
```

**Comment by whummer** [comment]
Thanks for reporting @whiterice42 , and apologies for the delay. 

We have recently added a small CLI command to perform basic validation of docker-compose configs. Can you please try running `localstack config validate`:
```
$ localstack config validate
⚠ Please use "container_name: localstack_main" or add "MAIN_CONTAINER_NAME" in "environment".
```

Looks like adding the `container_name` attribute may potentially help.

Also, we have recently pushed a couple of enhancements related to Lambda execution and networking - can you please pull the `latest` Docker image and use `localstack/localstack:latest` in your compose-config, to see if that resolves the issue? Thanks for your help!

**Comment by mikebridge** [comment]
I'm having  similar error while following [these instructions](https://docs.localstack.cloud/tools/lambda-tools/hot-swapping/#creating-the-lambda-function):

```bash
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test
export AWS_REGION=us-west-2

aws lambda create-function \
    --code S3Bucket="__local__",S3Key="/home/bridge/work/hello_world/lambdas"\
    --region us-west-2 \
    --function-name "hello-world" \
    --runtime "nodejs14.x" \
    --handler "helloWorld.handler" \
    --memory-size 128 \
    --role arn:aws:iam::123456:role/example \
    --endpoint-url="http://localhost:4566" \
    --query "FunctionArn" \
    --output text
```

```
An error occurred (InternalFailure) when calling the CreateFunction operation (reached max retries: 2): Unknown error: [Errno 2] No such file or directory: '/home/bridge/work/hello-world/lambdas/helloWorld.js' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/files.py", line 118, in ensure_readable
    with open(file_path, "rb"):
FileNotFoundError: [Errno 2] No such file or directory: '/home/bridge/work/hello-world/lambdas/helloWorld.js'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1392, in create_function
    result = set_function_code(lambda_function)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 970, in set_function_code
    run_for_max_seconds(config.LAMBDA_CODE_EXTRACT_TIME, _set_and_configure)
  File "/opt/code/localstack/localstack/utils/run.py", line 146, in run_for_max_seconds
    raise result
  File "/opt/code/localstack/localstack/utils/run.py", line 127, in _worker
    fn_result = _function(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 964, in _set_and_configure
    do_set_function_code(lambda_function)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1104, in do_set_function_code
    ensure_readable(main_file)
  File "/opt/code/localstack/localstack/utils/files.py", line 122, in ensure_readable
    os.chmod(file_path, default_perms)
FileNotFoundError: [Errno 2] No such file or directory: '/home/bridge/work/hello-world/lambdas/helloWorld.js'
```

The file is definitely there and world-readable.  I pulled the latest version out of docker, and the config seems ok:

```
$ localstack config validate
config valid
```

```yaml
# docker-compose.yml

  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - EDGE_PORT=4566
      # Set LAMBDA_REMOTE_DOCKER to false for hot-redeploying
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_DOCKER_NETWORK=development
      - SERVICES=s3,lambda,apigateway,sqs
      - DEBUG=1
      - HOST_TMP_FOLDER=${TEMPDIR:-/tmp/localstack}
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Oddly, I have had this working before---it was when I updated the localstack docker image that it stopped working.  Reverting hasn't helped, so I'm guessing maybe I had some configuration in my old localstack container....

**Comment by mikebridge** [comment]
@whummer Reverting to `localstack/localstack:0.14.0` seems to work.  It's just the `localstack/localstack:latest` that isn't working for me.

**Comment by JackWillz** [comment]
Is this issue still outstanding? I believe I am experiencing the same.

**Comment by dfangl** [comment]
Hi! Can you try our new lambda provider, by using `PROVIDER_OVERRIDE_LAMBDA=asf` and check again?
It should provide better parity for all lambda operations.

Also, please double check if your `LAMBDA_DOCKER_NETWORK` variable is set correctly, or, in the best case, use our provided `docker-compose.yml` (https://github.com/localstack/localstack/blob/master/docker-compose.yml) to check if it fixes the issue.
