### ISSUE TITLE
bug: SES service fails to start in version 0.13.0

### ISSUE THREAD

**Issue by samlaycock** [localstack/localstack#5012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `localstack/localstack:0.13.0` on an M1 Mac with `ses` as an enabled service, any requests that are proxied to SES fail because the SES services fails to start (I think it fails it's initial health check):

```
2021-11-25T22:19:57:INFO:localstack.services.infra: Starting mock SES service on http port 4566 ...

2021-11-25T22:19:57:INFO:localstack.services.motoserver: starting moto server on http://0.0.0.0:51805

2021-11-25T22:19:57:DEBUG:localstack.services.plugins: checking service health ses:51805

2021-11-25T22:19:57:DEBUG:localstack.services.edge: OUT(ses): "POST /" - status: 500 - response headers: {'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '339', 'Server': 'Werkzeug/2.0.2 Python/3.8.12', 'Date': 'Thu, 25 Nov 2021 22:19:57 GMT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'etag,x-amz-version-id'} - response: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title xmlns="http://ses.amazonaws.com/doc/2010-01-31/">500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'

2021-11-25T22:19:57:DEBUG:localstack.services.edge: OUT(ses): "POST /" - status: 500 - response headers: {'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '339', 'Server': 'Werkzeug/2.0.2 Python/3.8.12', 'Date': 'Thu, 25 Nov 2021 22:19:57 GMT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'etag,x-amz-version-id'} - response: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title xmlns="http://ses.amazonaws.com/doc/2010-01-31/">500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'

2021-11-25 22:19:57,807:API: Error on request:

Traceback (most recent call last):

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 319, in run_wsgi

    execute(self.server.app)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 308, in execute

    application_iter = app(environ, start_response)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 205, in __call__

    return backend_app(environ, start_response)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__

    return self.wsgi_app(environ, start_response)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app

    response = self.handle_exception(e)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function

    return cors_after_request(app.make_response(f(*args, **kwargs)))

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app

    response = self.full_dispatch_request()

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function

    return cors_after_request(app.make_response(f(*args, **kwargs)))

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request

    rv = self.dispatch_request()

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 161, in convert_flask_to_httpretty_response_call

    return convert_flask_to_httpretty_response_call_orig(*args, **kwargs)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 147, in __call__

    result = self.callback(request, request.url, {})

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 203, in dispatch

    return cls()._dispatch(*args, **kwargs)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 313, in _dispatch

    return self.call_action()

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 403, in call_action

    response = method()

  File "/opt/code/localstack/localstack/services/ses/ses_starter.py", line 83, in email_responses_send_email

    body = self.querystring.get(bodydatakey)[0]

TypeError: 'NoneType' object is not subscriptable

```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
localstack:
    image: localstack/localstack:0.13.0
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb,kinesis,s3,ses,sns,sqs
      - LS_LOG=trace
```

I'm using the above `docker compose` config, but the problem can be replicated with the `docker run` command below as well.

`docker run -e SERVICES=ses -p 4566:4566 localstack/localstack:0.13.0`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```js
const AWS = require("@aws-sdk/client-ses");

const sesClient = new AWS.SES({
  endpoint: "http://localhost:4566",
  region: "us-east-1",
  credentials: {
    accessKeyId: "access_key",
    secretAccessKey: "secret_key"
  }
});

(async () => {
  await sesClient.sendEmail({ Destination : { ToAddresses: ["test@test.com"], Content: { Body: { Text: "test" } } } });
})();
```

### Environment

```markdown
- OS: MacOS 12.1 (21C5039b) (ARM 64)
- LocalStack: 0.13.0
```

**Comment by whummer** [comment]
Thanks for reporting @samlaycock . Looks like some input parameters for sendEmail are missing, according to the docs [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html#sendEmail-property). 

This seems to be working if we slightly adjust your sample as follows:
```
(async () => {
  await sesClient.sendEmail({
    Destination : { ToAddresses: ["test@test.com"] },
    Message: { Body: { Text: { Data: "test" } }, Subject: { Data: "Test subject" } },
    Source: "sender@example.com"
  });
})();
```

(Please note that the source/sender address must have been verified via the API, prior to sending an email from it.)

We've also pushed a few minor enhancements in 8ff9c27195ceb3ea6a597dd98db486dceea8385c to improve the error reporting in case (should become available in the `latest` Docker image shortly). Hope that helps - please let us know if the problem persists.. Thanks!

**Comment by samlaycock** [comment]
@whummer Sorry I meant `client-sesv2` in my trivial (and seemingly useless) example. As it turns out, I still had missed things from the docs. Thanks!
