### ISSUE TITLE
bug: API-Gateway-v2 mistakes HTTP-API for WebSocket-API

### ISSUE THREAD

**Issue by awehrung** [localstack/localstack#5027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When making a request to the API-Gateway-v2 using an HTTP-API with Lambda-integration, I get the following logs:

```
Unsupported integration type "AWS" for Websocket API ID "my-api"
```

Complete logs:

<details>
  <summary>Click to expand</summary>
  
```
2021-11-29T13:21:05.435:DEBUG:localstack_ext.services.apigateway.invocations: Using stage 'local' extracted from invocation path: /local/test
2021-11-29T13:21:05.435:DEBUG:localstack_ext.services.apigateway.invocations: Using $default stage for API Gateway invocation path: /test
2021-11-29T13:21:05.442:INFO:localstack.utils.run: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7f9f256d0940>(None) failed: Unsupported integration type "AWS" for Websocket API ID "my-api" Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/run.py", line 153, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 669, in handler
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 205, in modify_and_forward
    result = modify_and_forward_orig(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 338, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py.enc", line 197, in forward_request
  File "/opt/code/localstack/localstack/services/edge.py", line 169, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py.enc", line 191, in do_forward_request
  File "/opt/code/localstack/localstack/services/edge.py", line 224, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 247, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 338, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/apigateway_extended.py.enc", line 109, in forward_request
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/invocations.py.enc", line 162, in invoke_api_from_execute_api_domain_invocation
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/invocations.py.enc", line 171, in invoke_api
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/invocations.py.enc", line 219, in invoke_http_api_v2
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/invocations.py.enc", line 272, in v2_invoke_integration_request
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/invocations.py.enc", line 312, in v2_do_invoke_integration_request
Exception: Unsupported integration type "AWS" for Websocket API ID "my-api"

2021-11-29T13:21:05.442:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request GET http://my-api.execute-api.localhost.localstack.cloud:4566/local/test: Unsupported integration type "AWS" for Websocket API ID "my-api" Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 159, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 86, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/opt/code/localstack/localstack/utils/run.py", line 153, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 669, in handler
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 205, in modify_and_forward
    result = modify_and_forward_orig(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 338, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py.enc", line 197, in forward_request
  File "/opt/code/localstack/localstack/services/edge.py", line 169, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py.enc", line 191, in do_forward_request
  File "/opt/code/localstack/localstack/services/edge.py", line 224, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 247, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 338, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/apigateway_extended.py.enc", line 109, in forward_request
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/invocations.py.enc", line 162, in invoke_api_from_execute_api_domain_invocation
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/invocations.py.enc", line 171, in invoke_api
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/invocations.py.enc", line 219, in invoke_http_api_v2
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/invocations.py.enc", line 272, in v2_invoke_integration_request
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/invocations.py.enc", line 312, in v2_do_invoke_integration_request
Exception: Unsupported integration type "AWS" for Websocket API ID "my-api"
```

</details>

See steps to reproduce below

### Expected Behavior

This should not trigger an error (it worked last week), as I am using an HTTP-API and not a WebSocket-API. Instead, it should call the Lambda function normally.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
localstack:
  image: localstack/localstack:latest  # sha256:b8a3ca9cec87d3b619cf50b446805a0fbe4989866c8973c5c5a74a641c41d78a
  container_name: "localstack"
  networks:
    default:
      aliases:
        - redacted.localstack  # for s3 routing with spring-boot
  env_file:
    - configuration/environment/localstack.env
    - ../localstack_api_key.env
  ports:
    - "4566:4566"
    - "443:443"  # for localstack.cloud UI
  volumes:
    - "./configuration/localstack/scripts:/docker-entrypoint-initaws.d"  # this is where the scripts for apigatewayv2 creation are located
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./configuration/localstack/kms/seed.yaml:/init/seed.yaml:ro"
    - "../redacted/dist:/opt/code/lambda_import"
    - "localstack_persistence:/tmp/localstack"
```

Contents of `localstack.env`:

```env
SERVICES=s3,kms,cognito,serverless
HOSTNAME=localstack
HOSTNAME_EXTERNAL=localstack
DEFAULT_REGION=eu-central-1
DEBUG=1
KMS_SEED_PATH=/init/seed.yaml
KMS_PROVIDER=local-kms
LS_LOG=info
DATA_DIR=/tmp/localstack/data
LAMBDA_EXECUTOR=local
EAGER_SERVICE_LOADING=1
DNS_SERVER=127.0.0.11
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

In the following steps, a valid ZIP-file for a lambda function has been mounted to `/opt/code/lambda_import/my-function.zip` in the Localstack container.

Localstack setup:

```bash
# Create the HTTP-API with custom ID
awslocal apigatewayv2 create-api --name=my-api --protocol-type=HTTP --tags="_custom_id_=my-api"
# Create an auto-deployed stage to avoid name conflicts
awslocal apigatewayv2 create-stage --api-id=my-api --stage-name=local --auto-deploy
# Create a lambda function that will be our target
awslocal lambda create-function --function-name="my-function" --zip-file="fileb:///opt/code/lambda_import/my-function.zip" --role="test-role" --handler="handler.lambda_handler" --runtime="python3.8"
# Create the integration, save ID for route creation
awslocal apigatewayv2 create-integration --api-id="my-api" --integration-type="AWS" --integration-uri="arn:aws:lambda:eu-central-1:000000000000:function:my-function"
# Add a route
awslocal apigatewayv2 create-route --api-id="my-api" --route-key="GET /test" --target="integrations/717ff494"  # replace ID here
```

When calling `GET http://my-api.execute-api.localhost.localstack.cloud:4566/local/test`, I get the error mentioned above.

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest (Nov 29)
```

### Anything else?

I hope this is just a temporary instability in the latest version and not some more serious problem. Thanks in advance for the support!

**Comment by whummer** [comment]
Thanks @awehrung - the log message mentioning `Websocket` is in fact misleading (will get fixed shortly).

Looks like the `AWS` integration needs to be mapped out properly - we'll push an update shortly. As a workaround for now, can you please using the `AWS_PROXY` integration type for now:
```
--integration-type="AWS_PROXY"
```
Hope that helps - will provide an update here soon.. Thanks!

**Comment by awehrung** [comment]
Ok, works for now, thanks @whummer. Can you please ping me here when it is "back to normal"?

**Comment by calvernaz** [comment]
Hi @awehrung, first of all thanks for the reproducible steps. In the latest version I couldn't reproduce the issue, could you give a try with the latest image?

**Comment by awehrung** [comment]
Yep @calvernaz, it works now :slightly_smiling_face: Thanks again!

**Comment by calvernaz** [comment]
Thanks @awehrung!
