### ISSUE TITLE
bug: docker-reuse lambda mode does not work when running on CircleCI arm machine images

### ISSUE THREAD

**Issue by jakedaleweb** [localstack/localstack#5045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running localstack on CircleCI ARM machine images and invoking a lambda function `exec_in_container` fails on this line https://github.com/localstack/localstack/blob/595eaef0d4aea92b2930aa5a288eab407effc88e/localstack/utils/docker_utils.py#L1491 with the error

```
localstack_1                | docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/containers/my-very-cool-lambda/json: Not Found ("No such container: my-very-cool-lambda")
```

What's really strange is that the same container listing logic is used in `start_container` but it passes there. So I'm wondering if it's a timing issue. I noticed that `remove=True` is passed in to the command to create the container (here: https://github.com/localstack/localstack/blob/595eaef0d4aea92b2930aa5a288eab407effc88e/localstack/services/awslambda/lambda_executors.py#L905) I could be misunderstanding this, but is it possible when running on the arm machine image this is faster than usual and the container is removed before the execution can occur? Perhaps this call should consider using `LAMBDA_REMOVE_CONTAINERS `?

If you run the lambdas in `docker` mode there is no issue. Have tried running with `LEGACY_DOCKER_CLIENT=true` too but no luck.

### Expected Behavior

Lambda function container should be found and then the function should run (:

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml

```
  localstack:
    build: ./services/localstack
    shm_size: 512mb
    ports:
      - '${PORT_LOCALSTACK}:4566'
    environment:
      - SERVICES=sns,s3,sqs,dynamodb,lambda,kinesis
      - DEBUG=1
      - KINESIS_PROVIDER=kinesalite
      - LAMBDA_EXECUTOR=docker-reuse # works in "docker" mode
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_DOCKER_NETWORK=host
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
```

Dockerfile:
```
FROM localstack/localstack:0.13.0

# added for the benefit of the init scripts
RUN apt-get -y update && apt-get -y install jq
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

`awslocal lambda create-function` and `awslocal lambda invoke`

### Environment

```markdown
Using machine image on CircleCI i.e. https://circleci.com/docs/2.0/arm-resources/#using-arm-resources
```

### Anything else?

Thanks (:

**Comment by jakedaleweb** [comment]
Full stack trace
```
2021-12-01T02:40:16:INFO:localstack.services.awslambda.lambda_executors: Running lambda: arn:aws:lambda:*********:000000000000:function:my-cool-function
2021-12-01T02:40:16:DEBUG:localstack.services.awslambda.lambda_executors: Priming docker container with runtime "nodejs14.x" and arn "arn:aws:lambda:*********:000000000000:function:my-cool-function".
2021-12-01T02:40:16:DEBUG:localstack.services.awslambda.lambda_executors: Priming Docker container (status "0"): localstack_1_lambda_arn_aws_lambda_*********_000000000000_function_my-cool-function
2021-12-01T02:40:16:DEBUG:localstack.services.awslambda.lambda_executors: Creating container: localstack_1_lambda_arn_aws_lambda_*********_000000000000_function_my-cool-function
2021-12-01T02:40:16:DEBUG:localstack.services.awslambda.lambda_executors: Creating docker-reuse Lambda container localstack_1_lambda_arn_aws_lambda_*********_000000000000_function_my-cool-function from image localstack/lambda-js:nodejs14.x
2021-12-01T02:40:16:DEBUG:localstack.utils.docker_utils: Creating container with image localstack/lambda-js:nodejs14.x, command 'None', volumes None, env vars {REDACTED}
2021-12-01T02:40:16:DEBUG:localstack.services.awslambda.lambda_executors: Copying files to container "localstack_1_lambda_arn_aws_lambda_*********_000000000000_function_my-cool-function" from "/tmp/localstack/zipfile.c9158dfa".
2021-12-01T02:40:16:DEBUG:localstack.utils.docker_utils: Copying file /tmp/localstack/zipfile.c9158dfa/. into localstack_1_lambda_arn_aws_lambda_*********_000000000000_function_my-cool-function:/var/task
2021-12-01T02:40:23:DEBUG:localstack.services.awslambda.lambda_executors: Starting docker-reuse Lambda container: localstack_1_lambda_arn_aws_lambda_*********_000000000000_function_my-cool-function
2021-12-01T02:40:23:DEBUG:localstack.utils.docker_utils: Starting container localstack_1_lambda_arn_aws_lambda_*********_000000000000_function_my-cool-function
2021-12-01T02:40:25:DEBUG:localstack.utils.docker_utils: Getting the entrypoint for image: localstack/lambda-js:nodejs14.x
2021-12-01T02:40:25:DEBUG:localstack.services.awslambda.lambda_executors: Using entrypoint "/var/rapid/init --bootstrap /var/runtime/bootstrap --enable-msg-logs" for container "localstack_1_lambda_arn_aws_lambda_*********_000000000000_function_my-cool-function" on network "".
2021-12-01T02:40:25:DEBUG:localstack.utils.docker_utils: Executing command in container localstack_1_lambda_arn_aws_lambda_*********_000000000000_function_my-cool-function: ['/var/rapid/init', '--bootstrap', '/var/runtime/bootstrap', '--enable-msg-logs', 'dist/handler.handler']
2021-12-01T02:40:25:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:*********:000000000000:function:my-cool-function result / log output:

> 
2021-12-01T02:40:25:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:*********:000000000000:function:my-cool-function: Lambda process returned with error. Result: . Output:
 Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/containers/localstack_1_lambda_arn_aws_lambda_*********_000000000000_function_my-cool-function/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/docker_utils.py", line 1491, in exec_in_container
    container: Container = self.client().containers.get(container_name_or_id)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/models/containers.py", line 889, in get
    resp = self.client.api.inspect_container(container_id)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/api/container.py", line 773, in inspect_container
    return self._result(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/containers/localstack_1_lambda_arn_aws_lambda_*********_000000000000_function_my-cool-function/json: Not Found ("No such container: localstack_1_lambda_arn_aws_lambda_*********_000000000000_function_my-cool-function")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 596, in run_lambda_executor
    result, log_output = self.execute_in_container(
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 786, in execute_in_container
    return DOCKER_CLIENT.exec_in_container(
  File "/opt/code/localstack/localstack/utils/docker_utils.py", line 1532, in exec_in_container
    raise ContainerException()
localstack.utils.docker_utils.ContainerException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 809, in run_lambda
    result = LAMBDA_EXECUTOR.execute(
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 429, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 419, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 158, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 154, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 406, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 402, in _run
    result = self._execute(lambda_function, inv_context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 799, in _execute
    return super(LambdaExecutorReuseContainers, self)._execute(func_arn, *args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 710, in _execute
    result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 633, in run_lambda_executor
    raise InvocationException(
localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: . Output:
```

**Comment by jakedaleweb** [comment]
Update: there is no issue when using `localstack/localstack:latest` I suppose this issue must have been addressed already so I will close this off. Looking forward to that next release! 🙏  😄
