### ISSUE TITLE
Makefile Install fails: No module named localstack_client.config

### ISSUE THREAD

**Issue by crw-riviere** [localstack/localstack#505]
When I run `make install` after pulling the repository I get the following error:

```(test `which virtualenv` || pip install --user virtualenv) && \
                (test -e .venv || virtualenv  .venv) && \
                (. .venv/bin/activate && pip install --upgrade pip) && \
                (test ! -e requirements.txt || (. .venv/bin/activate; pip install six==1.10.0 ; pip -q install -r requirements.txt) && \
                . .venv/bin/activate; PYTHONPATH=. exec python localstack/services/install.py testlibs)
Requirement already up-to-date: pip in ./.venv/lib/python2.7/site-packages
Requirement already satisfied: six==1.10.0 in ./.venv/lib/python2.7/site-packages
Command "/mnt/c/Dev/localstack/.venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-H6HTvc/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-CRoWOe-record/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/c/Dev/localstack/.venv/include/site/python2.7/psutil" failed with error code 1 in /tmp/pip-build-H6HTvc/psutil/
Traceback (most recent call last):
  File "localstack/services/install.py", line 9, in <module>
    from localstack.constants import (DEFAULT_SERVICE_PORTS, ELASTICMQ_JAR_URL, STS_JAR_URL,
  File "/mnt/c/Dev/localstack/localstack/constants.py", line 2, in <module>
    import localstack_client.config
ImportError: No module named localstack_client.config
make: *** [install] Error 1```

**Comment by crw-riviere** [comment]
Didn't follow the prerequisite of installing the localstack package. Running `pip install localstack` resolved the issue.
