### ISSUE TITLE
question: How to disable analytics?

### ISSUE THREAD

**Issue by kigawas** [localstack/localstack#5061]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Related #4840 

If it cannot connect to the `analytics.localstack.cloud` when starting, an error will be raised like:

```python
2021-12-03T08:09:08.312:INFO:bootstrap.py: Execution of "start_runtime_components" took 5050.28ms
Traceback (most recent call last):
  File "bin/localstack", line 23, in <module>
    main()
  File "bin/localstack", line 19, in main
    main.main()
  File "/opt/code/localstack/localstack/cli/main.py", line 6, in main
    cli()
  File "/opt/code/localstack/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/code/localstack/localstack/cli/localstack.py", line 123, in cmd_start
    bootstrap.start_infra_locally()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 299, in start_infra_locally
    return infra.start_infra()
  File "/opt/code/localstack/localstack/services/infra.py", line 411, in start_infra
    raise e
  File "/opt/code/localstack/localstack/services/infra.py", line 397, in start_infra
    thread = do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/code/localstack/localstack/services/infra.py", line 512, in do_start_infra
    thread = start_runtime_components()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 78, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 504, in start_runtime_components
    raise TimeoutError(
TimeoutError: gave up waiting for edge server on 0.0.0.0:4566
```

Is there any configuration to opt out?

**Comment by kigawas** [comment]
OK I see. With `DISABLE_EVENTS=1`
