### ISSUE TITLE
Service elasticsearch not yet available

### ISSUE THREAD

**Issue by SQLadmin** [localstack/localstack#508]
Im trying to start localhost. 

Im getting the below error

**:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...**

I have reinstalled node modules and localstack.

Output of sudo localstack --debug start  (getting the below output from roor and non-root user)

```
root@lin:/home/ubuntu/localstack# sudo localstack --debug start
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock DynamoDB (http port 4569)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudWatch (http port 4582)...
Starting mock CloudFormation (http port 4581)...
Starting mock SSM (http port 4583)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
No passwd entry for user 'localstack'
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
Initializing DynamoDB Local with the following configuration:
Port:   4564
InMemory:       true
DbPath: null
SharedDb:       true
shouldDelayTransientStatuses:   false
CorsParams:     *

Listening at http://:::4565
11:17:54.598 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.13.8) ...
* Running on http://0.0.0.0:4579/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4563/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4577/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4583/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4580/ (Press CTRL+C to quit)
11:17:56.142 [elasticmq-akka.actor.default-dispatcher-2] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
11:17:57.068 [elasticmq-akka.actor.default-dispatcher-2] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:4561, visible server address http://localhost:4576
11:17:57.068 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.13.8) started in 5670 ms ===
127.0.0.1 - - [13/Dec/2017 11:17:59] "GET / HTTP/1.1" 200 -
2017-12-13T11:17:59:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
127.0.0.1 - - [13/Dec/2017 11:18:02] "GET / HTTP/1.1" 200 -
2017-12-13T11:18:02:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
127.0.0.1 - - [13/Dec/2017 11:18:05] "GET / HTTP/1.1" 200 -
2017-12-13T11:18:05:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
127.0.0.1 - - [13/Dec/2017 11:18:08] "GET / HTTP/1.1" 200 -
2017-12-13T11:18:08:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
127.0.0.1 - - [13/Dec/2017 11:18:11] "GET / HTTP/1.1" 200 -
2017-12-13T11:18:11:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
127.0.0.1 - - [13/Dec/2017 11:18:14] "GET / HTTP/1.1" 200 -
2017-12-13T11:18:14:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
127.0.0.1 - - [13/Dec/2017 11:18:17] "GET / HTTP/1.1" 200 -
2017-12-13T11:18:17:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
127.0.0.1 - - [13/Dec/2017 11:18:20] "GET / HTTP/1.1" 200 -
2017-12-13T11:18:20:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
127.0.0.1 - - [13/Dec/2017 11:18:23] "GET / HTTP/1.1" 200 -
2017-12-13T11:18:24:ERROR:localstack.services.es.es_starter: Elasticsearch health check failed (retrying...): TransportError(502, u'') Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/es/es_starter.py", line 56, in check_elasticsearch
    out = es.cat.aliases()
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/cat.py", line 23, in aliases
    'aliases', name), params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 89, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 124, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
TransportError: TransportError(502, u'')

2017-12-13T11:18:24:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2017-12-13T11:18:24:ERROR:infra.pyc: Error checking state of local environment (after some retries): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 344, in check_infra
    raise e
AssertionError

Error starting infrastructure:  Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 481, in start_infra
    check_infra(apis=apis)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 353, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 353, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 353, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 353, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 353, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 353, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 353, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 353, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 351, in check_infra
    raise e
AssertionError

ERROR:

```

**Comment by whummer** [comment]
Thanks for reporting @SqlAdmin . Please see the note in the README:
> Note: Please do not use sudo or the root user - LocalStack should be installed and started entirely under a local non-root user.

In fact, Elasticsearch does not allow running the server as `root`. Can you please try running LocalStack under a non-root user, and report back here whether it works.

**Comment by SqlAdmin** [comment]
Whummer, I tried both root and non root user. Getting the same error on non root user.

**Comment by chenrui333** [comment]
Having the same issue:

python 3.6
localstack 0.8.6.2

**Comment by zhoub** [comment]
Bump, installed from pip on CentOS 6 for Python 2.7.15, same issue.

**Comment by aw230012** [comment]
I'm having this issue in the localstack/localstack Docker container.  Does this project even work?  I can't get it to work on a Windows VM so I tried Docker thinking the container would be managed better and it doesn't work either.

**Comment by whummer** [comment]
Closing as inactive/outdated. Should be fixed in the latest version.
