### ISSUE TITLE
Connection Refused When Creating SQS Queue on MacOS 10.12.6

### ISSUE THREAD

**Issue by mam8cc** [localstack/localstack#509]
I'm getting this stack whenever I attempt to call `create-queue` with `awslocal sqs create-queue --queue-name=my-test-queue`.

```
2017-12-13T16:22:45:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4561): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1095334a8>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/venv/batch-jobs/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/venv/batch-jobs/lib/python3.5/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/venv/batch-jobs/lib/python3.5/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/batch-jobs/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/venv/batch-jobs/lib/python3.5/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/.pyenv/versions/3.5.2/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/.pyenv/versions/3.5.2/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/.pyenv/versions/3.5.2/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/.pyenv/versions/3.5.2/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/.pyenv/versions/3.5.2/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/venv/batch-jobs/lib/python3.5/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/venv/batch-jobs/lib/python3.5/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1095334a8>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/batch-jobs/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/venv/batch-jobs/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/venv/batch-jobs/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4561): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1095334a8>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.5/site-packages/localstack/services/generic_proxy.py", line 190, in forward
    headers=forward_headers)
  File "/venv/lib/python3.5/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/venv/batch-jobs/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/venv/batch-jobs/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/venv/batch-jobs/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/venv/batch-jobs/lib/python3.5/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4561): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1095334a8>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

I am running `DEFAULT_REGION=us-west-2 SERVICES=sqs localstack start` but it happens with `localstack start` as well.  I am able to create queues when I run the docker container, however the `async` ability of the python test library isn't available for the docker container.

Things I've tried:
- Deleting the `/infra` dir as mentioned in other issues.
- Downgrading `localstack`
- Running `localstack` in debug mode, however this floods my terminal with white space and is useless (would be helpful to know the cause of this?).  I've tried using different terminal emulators and different shells (zsh and bash).

**Update:**

I wrote the `--debug` output to a file:
```
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock Kinesis (http port 4568)...
Starting mock SNS (http port 4575)...
Starting mock Redshift (http port 4577)...
Starting mock CloudFormation (http port 4581)...
Starting mock SQS (http port 4576)...
Starting mock Route53 (http port 4580)...
Starting mock CloudWatch (http port 4582)...
Starting mock SSM (http port 4583)...
Starting mock Firehose service (http port 4573)...
Starting mock SES (http port 4579)...
Starting local Elasticsearch (http port 4571)...
Error: Invalid or corrupt jarfile /venv/batch-jobs/lib/python3.5/site-packages/localstack/infra/elasticmq/elasticmq-server.jar
```
So I tried to download a clean jar per https://github.com/localstack/localstack/issues/435 to no avail, same issue.
I'm able to run the elasticmq jar by itself:
```
$ java -jar ~/Envs/batch-jobs/lib/python3.5/site-packages/localstack/infra/elasticmq-server.jar
21:37:34.169 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.13.8) ...
21:37:35.019 [elasticmq-akka.actor.default-dispatcher-2] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
21:37:36.073 [elasticmq-akka.actor.default-dispatcher-2] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:9324, visible server address http://localhost:9324
21:37:36.073 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.13.8) started in 2503 ms ===
^C21:37:50.220 [Thread-1] INFO  org.elasticmq.server.Main$ - ElasticMQ server stopping ...
21:37:50.223 [elasticmq-akka.actor.default-dispatcher-2] INFO  akka.actor.CoordinatedShutdown - Starting coordinated shutdown from JVM shutdown hook
21:37:50.308 [Thread-1] INFO  org.elasticmq.server.Main$ - === ElasticMQ server stopped ===
```

System Information:
```
macOS 10.12.6

$ node -v
v6.9.4
$ npm -v
5.6.0
$ python --version
Python 3.5.2
$ localstack -v
0.8.3
```

**Comment by mam8cc** [comment]
I should note I've tried running the debug mode as `DEBUG=1` and `--debug`.  Whatever it is doing actually causes my terminal to crash entirely after a few seconds.

**Comment by whummer** [comment]
Closing this issue as outdated/obsolete. Please open a follow-up issue if the problem persists. Thanks
