### ISSUE TITLE
SNS-SQS Fanout fails with an error

### ISSUE THREAD

**Issue by lobster1234** [localstack/localstack#510]
I am trying to set up a SNS-SQS fanout scheme using localstack. Here are the steps -

```
aws> sqs create-queue --queue-name localhost --endpoint-url http://localhost:4576

aws> sns create-topic --name fan-out-topic --endpoint-url http://localhost:4575

aws> sns subscribe --protocol sqs --topic-arn "arn:aws:sns:us-east-1:123456789012:fan-out-topic" --endpoint-url http://localhost:4575 --notification-endpoint " http://localhost:4576/queue/localhost"
aws> sns list-subscriptions --endpoint-url http://localhost:4575
{
    "Subscriptions": [
        {
            "Owner": "",
            "Endpoint": " http://localhost:4576/queue/localhost",
            "Protocol": "sqs",
            "TopicArn": "arn:aws:sns:us-east-1:123456789012:fan-out-topic",
            "SubscriptionArn": "arn:aws:sns:us-east-1:123456789012:fan-out-topic:f2cbed3c-bec5-4a10-8382-6d620491d2df"
        }
    ]
}
aws> sns  publish --topic-arn "arn:aws:sns:us-east-1:123456789012:fan-out-topic" --message "for fanout" --endpoint-url http://localhost:4575

```
At this point aws-shell hangs, and the `make infra` console prints this error -
```

2017-12-13T18:10:44:ERROR:localstack.services.generic_proxy: Error forwarding request: list index out of range Traceback (most recent call last):
  File "/Users/mpandit/work/localstack/localstack/services/generic_proxy.py", line 181, in forward
    path=path, data=data, headers=forward_headers)
  File "/Users/mpandit/work/localstack/localstack/services/sns/sns_listener.py", line 63, in forward_request
    queue_name = subscriber['Endpoint'].split(':')[5]
IndexError: list index out of range
```

**Comment by ellisonleao** [comment]
having this issue as well

**Comment by jk2l** [comment]
+1 for me

I created a PR for this

**Comment by whummer** [comment]
This should be fixed in #523, can you please give it a try with the latest version @lobster1234 @ellisonleao @jk2l

**Comment by jk2l** [comment]
yes it seem to be working

**Comment by lobster1234** [comment]
Can confirm - it works. Resuming the test from where it was crashing earlier -

```
aws>  sns  publish --topic-arn "arn:aws:sns:us-east-1:123456789012:fan-out-topic --message "for fanout" --endpoint-url http://localhost:4575

{
    "MessageId": "e29582d6"
}
sqs receive-message --queue-url http://localhost:4576/queue/localhost --endpoint-url http://localhost:4576
{
    "Messages": [
        {
            "Body": "{\"Message\": \"for fanout\", \"Type\": \"Notification\", \"TopicArn\": \"arn:aws:sns:us-east-1:123456789012:fan-out-topic\", \"MessageId\": \"6df1ccfd-23d3-4f7a-bf39-5bbb6e1a4eec\"}",
            "ReceiptHandle": "d450aec4-a191-48c6-8eb4-2e1d8cf4dbc4#e17a8741-217d-422f-aec0-dd34f795c3d5",
            "MD5OfBody": "17732e41d607c18ba9576b3aebce748e",
            "MessageId": "d450aec4-a191-48c6-8eb4-2e1d8cf4dbc4"
        }
    ]
}
aws>
```

Thanks so much @whummer and @jk2l!
