### ISSUE TITLE
bug: Urgent!!! Get issue "Unable to find forwarding rule for host..." when use listObjectsV2/listBuckets

### ISSUE THREAD

**Issue by zhuzhenguang** [localstack/localstack#5111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using the latest localstack:0.13.1, so it is not an version problem

A bucket named test-bucket has existed in the localstack, and I want to list all object in it using the java sdk:

```
S3Client s3Client = S3Client.builder()
    .serviceConfiguration(S3Configuration.builder().pathStyleAccessEnabled(true).build())
    .credentialsProvider(AnonymousCredentialsProvider.create())
    .region(Region.of(region))
    .endpointOverride(URI.create("http://localhost:4566"))
    .build();
ListObjectsV2Request request = ListObjectsV2Request.builder().bucket("test-bucket").build();
List<S3Object> collect = s3Client.listObjectsV2(request).contents();
```

But get the exception:
software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 404, Request ID: null, Extended Request ID: null)

	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:106)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:84)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:42)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:94)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$6(BaseClientHandler.java:270)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:135)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:161)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:114)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:169)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:95)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.s3.DefaultS3Client.listObjectsV2(DefaultS3Client.java:6028)

And in the localstack log:
2021-12-13T07:43:49.672:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "GET /test-bucket?list-type=2", target header "", auth header "", data ""

And the listBuckets api in the Java sdk returns the similar error.

### Expected Behavior

It is ok when use aws-cli to list object, it can return the correct response:
```
aws --endpoint-url=http://localhost:4566 s3api list-objects-v2 --bucket test-bucket
```
And it is also ok if I access the file directly using the java sdk:
```
S3Client s3Client = S3Client.builder()
    .serviceConfiguration(S3Configuration.builder().pathStyleAccessEnabled(true).build())
    .credentialsProvider(AnonymousCredentialsProvider.create())
    .region(Region.of(region))
    .endpointOverride(URI.create("http://localhost:4566"))
    .build();
var objectRequest = GetObjectRequest.builder()
     .bucket("test-bucket")
     .key("xx.json")
     .build();
String strings = s3Client.getObjectAsBytes(objectRequest).asUtf8String();
```
I think list object code should also return the correct response.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. docker-compose:
```
  localstack:
    restart: unless-stopped
    image: localstack/localstack:latest
    container_name: xxx
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
```

2. create-bucket
```
aws --endpoint-url=http://localhost:4566 s3api create-bucket --bucket test-bucket --region us-east-1
```

3. Put json files to the test-bucket

4. list object from bucket using java sdk
```
S3Client s3Client = S3Client.builder()
    .serviceConfiguration(S3Configuration.builder().pathStyleAccessEnabled(true).build())
    .credentialsProvider(AnonymousCredentialsProvider.create())
    .region(Region.of(region))
    .endpointOverride(URI.create("http://localhost:4566"))
    .build();
ListObjectsV2Request request = ListObjectsV2Request.builder().bucket("test-bucket").build();
List<S3Object> collect = s3Client.listObjectsV2(request).contents();
```

### Environment

```markdown
- OS: Mac
- LocalStack: 0.13.1
```

**Comment by zhuzhenguang** [comment]
Resolved. It need using a Credential not Anonymous. I instead
```
S3Client.builder().credentialsProvider(AnonymousCredentialsProvider.create())
```
with
```
S3Client.builder().credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create("xx", "yyyy")))
```
The access key and secret key can be any string.

But, it is so strange that it worked ok when using Anonymous for getObject and putObject APIs not for listXX api.

Is anyone know why?

**Comment by pinzon** [comment]
The fix to this issue has been merged. Thank you for reporting it.
