### ISSUE TITLE
bug: Cloudwatch error on lambdas when using custom region

### ISSUE THREAD

**Issue by toadzky** [localstack/localstack#5114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lambda invocations generate the following stacktrace. The lambda invocation seems to complete successfully, but afterwards the invocation is considered a failure because it can't access the logs from cloudwatch. the rest of localstack supports custom regions without issue as far as i've seen.

### Expected Behavior

No stacktrace and the invocation should not be considered a failure

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
Using testcontainers java test library, which uses the docker apis

### Environment

```markdown
- OS: Ubuntu 21.10
- LocalStack version: 0.12.20
- LocalStack Docker container id: 06fdf1e315a3
- LocalStack build date: 2021-11-09
- LocalStack build git hash: cfdca7ba
```

### Anything else?

```2021-12-13 15:02:24,658:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 236, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 161, in convert_flask_to_httpretty_response_call
    return convert_flask_to_httpretty_response_call_orig(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 147, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 203, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 313, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 403, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 281, in _wrapper
    response = f(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudwatch/responses.py", line 158, in put_metric_data
    self.cloudwatch_backend.put_metric_data(namespace, metric_data)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudwatch/responses.py", line 13, in cloudwatch_backend
    return cloudwatch_backends[self.region]
KeyError: 'test-region'```

**Comment by steffyP** [comment]
Hi @toadzky,

do you still encounter this problem with the `lastest` localstack image?

If yes, could you please share the content of the lambda (or a simplified example) so we can reproduce this behavior? Thank you!
