### ISSUE TITLE
bug: Failed to download spec from Azure/azure-rest-api-specs github

### ISSUE THREAD

**Issue by billcchung** [localstack/localstack#5136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

seeing an error mocking Autosacling service: 
```
Starting mock Autoscaling service on http ports 443/4566 ...
Error starting infrastructure: Failed to download https://raw.githubusercontent.com/Azure/azure-rest-api-specs/storage-dataplane-preview//specification/storage/data-plane/Microsoft.BlobStorage/preview/2019-12-12/blob.json, response code 404 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 482, in start_infra
    thread = do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/plugins.py", line 220, in do_start_infra
    return do_start_infra_orig(asynchronous,apis,is_in_docker,*args,**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/edge.py", line 69, in do_start_infra
    return do_start_infra_orig(asynchronous,*args,**kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 573, in do_start_infra
    thread = start_api_services()
  File "/opt/code/localstack/localstack/utils/analytics/profiler.py", line 168, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 555, in start_api_services
    t1 = plugin.start(asynchronous=True)
  File "/opt/code/localstack/localstack/services/plugins.py", line 41, in start
    return self.start_function(**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/azure/azure_starter.py", line 134, in start_azure
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/azure/api_specs.py", line 90, in download_api_specs
  File "/opt/code/localstack/localstack/utils/common.py", line 940, in download
    raise Exception("Failed to download %s, response code %s" % (url, r.status_code))
Exception: Failed to download https://raw.githubusercontent.com/Azure/azure-rest-api-specs/storage-dataplane-preview//specification/storage/data-plane/Microsoft.BlobStorage/preview/2019-12-12/blob.json, response code 404
```

due to the file https://raw.githubusercontent.com/Azure/azure-rest-api-specs/storage-dataplane-preview//specification/storage/data-plane/Microsoft.BlobStorage/preview/2019-12-12/blob.json has been removed from https://github.com/Azure/azure-rest-api-specs/tree/main/specification/storage/data-plane/Microsoft.BlobStorage/preview

### Expected Behavior

expected to mock autoscaling service without errors.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: localstack/localstack:0.12.15
- LocalStack: docker image with tag 0.12.15
```

**Comment by dfangl** [comment]
Hi @billcchung !
This issue should be fixed in the `:latest` tag or in `:0.13.2`. Sorry for the inconvenience.
Thanks for bringing this to our attention! If you have any more problems, please do not hesitate to open another issue!
