### ISSUE TITLE
bug: NoneType object has no attribute 'get'

### ISSUE THREAD

**Issue by javabudd** [localstack/localstack#5143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Setting up a delivery stream with kinesisStreamAsSource causes a 500 error when POST'ing to the Firehose API.

Here is the output of the error:
```
localstack_main | 2021-12-17T18:11:16.707:ERROR:firehose_api: Exception on / [POST]
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
localstack_main |     response = self.full_dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
localstack_main |     rv = self.handle_user_exception(e)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
localstack_main |     rv = self.dispatch_request()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
localstack_main |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
localstack_main |   File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 410, in post_request
localstack_main |     response = create_stream(
localstack_main |   File "/opt/code/localstack/localstack/services/firehose/firehose_api.py", line 342, in create_stream
localstack_main |     kinesis_stream_name = delivery_stream_type_configuration.get("KinesisStreamARN").split("/")[
localstack_main | AttributeError: 'NoneType' object has no attribute 'get'
```
```
2021-12-17T18:11:16.721:WARNING:localstack.utils.cloudformation.template_deployer: Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.Firehose object at 0x7f36351bb820>> with params: {'DeliveryStreamName': 'development-delivery-stream', 'DeliveryStreamType': 'KinesisStreamAsSource'} for resource: {'Type': 'AWS::KinesisFirehose::DeliveryStream', 'Metadata': {'aws:cdk:path': 'SCStack/DeliveryStream'}, 'LogicalResourceId': 'DeliveryStream', 'Properties': {'DeliveryStreamName': 'development-delivery-stream', 'DeliveryStreamType': 'KinesisStreamAsSource', 'ExtendedS3DestinationConfiguration': {'BucketARN': 'arn:aws:s3:::servicecore-data-pipeline-development', 'BufferingHints': {'IntervalInSeconds': 60, 'SizeInMBs': 64}, 'CloudWatchLoggingOptions': {'Enabled': True, 'LogGroupName': 'arn:aws:logs:us-west-2:000000000000:log-group:/aws/lambda/delivery-stream'}, 'CompressionFormat': 'GZIP', 'DataFormatConversionConfiguration': {'Enabled': True}, 'DynamicPartitioningConfiguration': {'Enabled': True}, 'ErrorOutputPrefix': 'firehoseTest-errors/!{firehose:error-output-type}/', 'Prefix': 'firehoseTest/!{partitionKeyFromQuery:s3Prefix}/!{partitionKeyFromLambda:companyId}/!{partitionKeyFromLambda:year}/!{partitionKeyFromLambda:month}/', 'ProcessingConfiguration': {'Enabled': True, 'Processors': [{'Parameters': [{'ParameterName': 'MetadataExtractionQuery', 'ParameterValue': '{s3Prefix: .tableName}'}, {'ParameterName': 'JsonParsingEngine', 'ParameterValue': 'JQ-1.6'}], 'Type': 'MetadataExtraction'}]}, 'RoleARN': 'arn:aws:iam::000000000000:role/SCStack-FireHoseDeliveryRole-a6db5922'}, 'KinesisStreamSourceConfiguration': {'KinesisStreamARN': 'arn:aws:kinesis:us-west-2:000000000000:stream/development-stream', 'RoleARN': 'arn:aws:iam::000000000000:role/SCStack-FireHoseDeliveryRole-a6db5922'}}, '_state_': {}}
```
Here is the output of the local stack delivery stream configuration
```
{
                deliveryStreamName: environment + "-delivery-stream",
                deliveryStreamType: 'KinesisStreamAsSource',
                kinesisStreamSourceConfiguration: {
                    kinesisStreamArn: kinesisDataStreamArn,
                    roleArn: deliveryRoleArn
                },
                extendedS3DestinationConfiguration: {
                    bucketArn: pipelineBucketArn,
                    bufferingHints: {
                        intervalInSeconds: 60,
                        sizeInMBs: 64
                    },
                    dynamicPartitioningConfiguration: {
                        enabled: true
                    },
                    processingConfiguration: {
                        enabled: true,
                        processors: [
                            {
                                parameters: [
                                    {
                                        parameterName: "MetadataExtractionQuery",
                                        parameterValue: "{s3Prefix: .tableName}"
                                    },
                                    {
                                        parameterName: "JsonParsingEngine",
                                        parameterValue: "JQ-1.6"
                                    }
                                ],
                                type: "MetadataExtraction"
                            }
                        ],
                    },
                    dataFormatConversionConfiguration: {
                        enabled: true
                    },
                    compressionFormat: 'GZIP',
                    prefix: 'firehoseTest/!{partitionKeyFromQuery:s3Prefix}/!{partitionKeyFromLambda:companyId}/!{partitionKeyFromLambda:year}/!{partitionKeyFromLambda:month}/',
                    errorOutputPrefix: 'firehoseTest-errors/!{firehose:error-output-type}/',
                    roleArn: deliveryRoleArn,
                    cloudWatchLoggingOptions: {
                        enabled: true,
                        logGroupName: deliveryStreamLogGroupArn
                    }
                }
            }
```

### Expected Behavior

The delivery stream should be created without a 500 error from the API

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

See template above and then run a `cdklocal deploy` to trigger the error

### Environment

```markdown
- OS: 
- LocalStack:
```

**Comment by pinzon** [comment]
The PR that addresses this issue has been merged. 
Thank you for reporting it!.
