### ISSUE TITLE
lambda create fails on Pro when DATA_DIR is set

### ISSUE THREAD

**Issue by navels** [localstack/localstack#5202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When `DATA_DIR` is set, creating a lambda function fails (in Pro only).  This does not fail in `0.13.1`.

The error message is
```
An error occurred (InternalFailure) when calling the CreateFunction operation (reached max retries: 2): Unknown error: [Errno 2] No such file or directory: '/home/navels/code/localstack-test/original_lambda_archive.zip' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1380, in create_function
    result = set_function_code(lambda_function)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 958, in set_function_code
    run_for_max_seconds(config.LAMBDA_CODE_EXTRACT_TIME, _set_and_configure)
  File "/opt/code/localstack/localstack/utils/common.py", line 1946, in run_for_max_seconds
    raise result
  File "/opt/code/localstack/localstack/utils/common.py", line 1927, in _worker
    fn_result = _function(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 952, in _set_and_configure
    do_set_function_code(lambda_function)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1020, in do_set_function_code
    _result = store_and_get_lambda_code_archive(lambda_function)
  File "/opt/code/localstack/localstack/utils/patch.py", line 34, in proxy
    return new(target, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 314, in store_and_get_lambda_code_archive
  File "/opt/code/localstack/localstack/utils/common.py", line 1131, in cp_r
    return shutil.copytree(src, dst, **kwargs)
  File "/usr/local/lib/python3.8/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/home/navels/code/localstack-test/original_lambda_archive.zip'
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Starting with `docker compose up -d` using this compose file:
```
version: "3"
services:
  localstack:
    image: localstack/localstack:0.13.2
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,lambda
      LOCALSTACK_API_KEY: <here is my api key>
      DATA_DIR: ${TMPDIR:-/tmp}/localstack/data
      LAMBDA_REMOTE_DOCKER: 0
      LAMBDA_CONTAINER_REGISTRY: "mlupin/docker-lambda"
    volumes:
      - ${TMPDIR:-/tmp}/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```
and then creating a lambda using this command:
```
awslocal lambda create-function --function-name foo --runtime python3.8 --handler handler.handler --role test --code "S3Bucket=__local__,S3Key=$(pwd)"
```
and this as `handler.py`:
```
def handler(event, context):
    return {"message": "handled"}
```

### Environment

```markdown
- OS: Ubuntu 21.10 ARM64
- LocalStack: 0.13.2
```

**Comment by navels** [comment]
Verified that the latest image works.

**Comment by whummer** [comment]
Great, thanks for confirming the fix @navels ! 👍
