### ISSUE TITLE
bug: StateMachine yaml Definition is not supported (DefinitionString works)

### ISSUE THREAD

**Issue by sema4-dmytrobazulin** [localstack/localstack#5204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when describing using cloudformation YAML with Definition, LocalStack fails to create StateMachine. Switching to YAML with DefinitionString works as expected. 

Examples taken from here
https://docs.aws.amazon.com/step-functions/latest/dg/development-options.html#development-options-format

Attaching working example 
[localstack_stepfunctions_and_serverless.zip](https://github.com/localstack/localstack/files/7791134/localstack_stepfunctions_and_serverless.z

### Expected Behavior

YAML with Definition is much more preferable in a complex state machine description with bunch of substitutions, references and parameters

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack --debug start -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   awslocal s3 mb s3://s4-echo-serverless-deployment-share-local
sls deploy --stage local

### Environment

```markdown
- OS: OSX Monterey
- LocalStack: latest
```

### Anything else?

Error when using YAML with Definition
[error.txt](https://github.com/localstack/localstack/files/7791149/error.txt)

Success when using YAML with DefinitionString
[success.txt](https://github.com/localstack/localstack/files/7791151/success.txt)

**Comment by davidjb** [comment]
The same issue applies to `DefinitionUri` as well when used with YAML, although with a more specific error. Tested with the latest LocalStack, 2.2.0, and in this case my YAML starts with a comment `#`:

`template.yaml`: 

```yaml
MyStateMachine:
  Type: AWS::Serverless::StateMachine
  Properties:
    DefinitionUri: mystatemachine.asl.yaml
```

```python
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1265, in _run
    self.do_apply_changes_in_loop(changes, stack)
  File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1338, in do_apply_changes_in_loop
    self.apply_change(change, stack=stack)
  File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1468, in apply_change
    executor.deploy_loop(resource_provider_payload)  # noqa
  File "/opt/code/localstack/localstack/services/cloudformation/resource_provider.py", line 601, in deploy_loop
    event = self.execute_action(resource_provider, payload)
  File "/opt/code/localstack/localstack/services/cloudformation/resource_provider.py", line 650, in execute_action
    return resource_provider.create(request)
  File "/opt/code/localstack/localstack/services/cloudformation/resource_provider.py", line 394, in create
    return self.create_or_delete(request)
  File "/opt/code/localstack/localstack/services/cloudformation/resource_provider.py", line 516, in create_or_delete
    result = invoke_function(
  File "/opt/code/localstack/localstack/services/cloudformation/resource_provider.py", line 258, in invoke_function
    raise e
  File "/opt/code/localstack/localstack/services/cloudformation/resource_provider.py", line 238, in invoke_function
    result = function(**params)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 534, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 976, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidDefinition: An error occurred (InvalidDefinition) when calling the CreateStateMachine operation: Invalid State Machine Definition: ''INVALID_JSON_DESCRIPTION: Unexpected character ('#' (code 35)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
```
