### ISSUE TITLE
bug: CDK/CF deploy fails on Pro version when adding SNS event notification to S3 Bucket

### ISSUE THREAD

**Issue by jcpage** [localstack/localstack#5210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am getting the following error when deploying my CDK app via "cdklocal deploy"

```
 ❌  TinyStack failed: Error: The stack named TinyStack failed to deploy: CREATE_FAILED (Deployment failed)
    at Object.waitForStackDeploy (/Users/jake/.nvm/versions/node/v16.13.1/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:309:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareAndExecuteChangeSet (/Users/jake/.nvm/versions/node/v16.13.1/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:351:26)
    at CdkToolkit.deploy (/Users/jake/.nvm/versions/node/v16.13.1/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:194:24)
    at initCommandLine (/Users/jake/.nvm/versions/node/v16.13.1/lib/node_modules/aws-cdk/bin/cdk.ts:267:9)
The stack named TinyStack failed to deploy: CREATE_FAILED (Deployment failed)
```
I minimized the CDK app as much as possible and found it happens in a small test case when adding an SNS event notification to a bucket with (also attached the full file):

```
    bucket.addEventNotification(
      EventType.OBJECT_CREATED,
      new SnsDestination(topic)
    )
```
Interestingly, it only happens with the Pro version, when unset LOCALSTACK_API_KEY it succeeds.

### Expected Behavior

Should deploy successfully as it does with the open source version of localstack.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
    export LOCALSTACK_API_KEY=...
    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
  make sure aws-sdk, cdk , awslocal, and cdklocal are installed
  unzip attached tinycdk.zip
  npm install
  cdklocal bootstrap
  cdklocal synth
  cdklocal deploy

[tinycdk.zip](https://github.com/localstack/localstack/files/7797202/tinycdk.zip)

### Environment

```markdown
- OS: MacOS 12.1 M1 Max (arm64)
- LocalStack: 0.13.2
```

**Comment by whummer** [comment]
Hi @jcpage , thanks for providing the reproducible example - much appreciated. 👍 This should be (hopefully) fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks!

**Comment by jcpage** [comment]
I got too ambitious and re-enabled more of my CDK app, which had some issues (I'm simplifying now to re-test the original case).  Basically it seems like Postgres can't start because it's trying to use a port that is already in use.  Two different cases:

1. when starting both Elasticache and Postgres, EC/Redis takes port 4511, then PG tries to take the same port and fails
2. when removing ES and just starting PG, it binds to port 4511, then tries to bind to port 4511 *again*.  It looks like for some reason it's trying to start 2 databases - the one I configured, and another one named "test" with user "test - but with a completely different server instance...

First case:

```
022-01-07T03:52:56.394:INFO:localstack_ext.services.elasticache.elasticache_api: Waiting for Redis server on tcp://localhost:4511 to start
2022-01-07T03:52:56.400:INFO:localstack_ext.services.elasticache.elasticache_api: 1541:C 07 Jan 2022 03:52:56.400 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
2022-01-07T03:52:56.401:INFO:localstack_ext.services.elasticache.elasticache_api: 1541:C 07 Jan 2022 03:52:56.400 # Redis version=5.0.14, bits=64, commit=00000000, modified=0, pid=1541, just started
2022-01-07T03:52:56.401:INFO:localstack_ext.services.elasticache.elasticache_api: 1541:C 07 Jan 2022 03:52:56.400 # Configuration loaded
2022-01-07T03:52:56.402:INFO:localstack_ext.services.elasticache.elasticache_api: 1541:M 07 Jan 2022 03:52:56.401 * Running mode=standalone, port=4511.
2022-01-07T03:52:56.402:INFO:localstack_ext.services.elasticache.elasticache_api: 1541:M 07 Jan 2022 03:52:56.401 # Server initialized
2022-01-07T03:52:56.402:INFO:localstack_ext.services.elasticache.elasticache_api: 1541:M 07 Jan 2022 03:52:56.401 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
2022-01-07T03:52:56.403:INFO:localstack_ext.services.elasticache.elasticache_api: 1541:M 07 Jan 2022 03:52:56.402 * Ready to accept connections
2022-01-07T03:53:00.206:INFO:localstack_ext.utils.postgresql: Starting PostgreSQL query listener/rewriter on port 4511->48617
2022-01-07T03:53:00.206:ERROR:postgresql_proxy.proxy: Can't establish PostgreSQL proxy listener on port 4511
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/postgresql_proxy/proxy.py", line 136, in listen
    self.sock.bind((ip, port))
OSError: [Errno 98] Address already in use
```

Second case:

```
2022-01-07T04:51:59.150:INFO:localstack_ext.services.rds.db_utils: Starting RDS server on port 4511 (backend port 60487) - database "splyce", user "splycer"
2022-01-07T04:52:06.845:INFO:localstack_ext.services.rds.db_utils: Starting RDS server on port 4511 (backend port 54765) - database "test", user "test"
2022-01-07T04:52:17.543:INFO:localstack_ext.utils.postgresql: Starting PostgreSQL query listener/rewriter on port 4511->60487
2022-01-07T04:52:26.246:INFO:localstack_ext.utils.postgresql: Starting PostgreSQL query listener/rewriter on port 4511->54765
2022-01-07T04:52:26.247:ERROR:postgresql_proxy.proxy: Can't establish PostgreSQL proxy listener on port 4511
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/postgresql_proxy/proxy.py", line 136, in listen
self.sock.bind((ip, port))
OSError: [Errno 98] Address already in use
```

**Comment by jcpage** [comment]
It looks like the specific issue re: adding SNS event notification to S3 via CDK is fixed.

**Comment by whummer** [comment]
Thanks for confirming the fix @jcpage . We've recently pushed a couple of fixes for RDS - can you please give it another try after pulling the `latest` Docker image? Please let us know if the problem persists.. Thanks for your help!
