### ISSUE TITLE
bug: unable to delete cloudformation

### ISSUE THREAD

**Issue by AnjaneyuluBatta505** [localstack/localstack#5214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to delete existing cloudformation stack. but it's throwing 500 error

I've tried
### command

```
aws --endpoint  http://localhost:4566/  cloudformation delete-stack  --stack-name pigeon-dev
```
### Error  output

```Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
```

### Docker container logs
```
avails-localstack       | 2022-01-02T15:09:08:ERROR:cloudformation_api: Exception on / [POST]
avails-localstack       | Traceback (most recent call last):
avails-localstack       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
avails-localstack       |     response = self.full_dispatch_request()
avails-localstack       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
avails-localstack       |     rv = self.handle_user_exception(e)
avails-localstack       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
avails-localstack       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
avails-localstack       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
avails-localstack       |     rv = self.dispatch_request()
avails-localstack       |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
avails-localstack       |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
avails-localstack       |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 978, in handle_request
avails-localstack       |     result = func(req_params)
avails-localstack       |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 554, in delete_stack
avails-localstack       |     deployer.delete_stack()
avails-localstack       |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1404, in delete_stack
avails-localstack       |     self.stack.set_resource_status(resource_id, "DELETE_COMPLETE")
avails-localstack       |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 153, in set_resource_status
avails-localstack       |     state = self.resource_states.setdefault(resource_id, {})
avails-localstack       |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 181, in resource_states
avails-localstack       |     self._set_resource_status_details(resource_id)
avails-localstack       |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 161, in _set_resource_status_details
avails-localstack       |     resource = self.resources[resource_id]
avails-localstack       | KeyError: 'ApiGatewayDeployment1641135317513'
```

### Expected Behavior

It should  delete the given cloudformation stack name.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: macOS Big Sur (MacBook Air (M1, 2020))
- LocalStack: latest
```

**Comment by dominikschubert** [comment]
Thanks for reporting this issue. The affected code path has already been fixed and made more robust in case the ID can't be found. If you still experience any related issues, please let us know.
