### ISSUE TITLE
bug: Local install for two user impossible

### ISSUE THREAD

**Issue by fletort** [localstack/localstack#5260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I alrady install localstack locally for one user on a machine with `pip3 install --user localstack`
On the same machine when i try to install it locally fir a second user, i have the following error at the end of the installation:

```
  Running setup.py install for psutil ... done
  Running setup.py install for tailer ... done
  Running setup.py install for localstack-client ... done
  Running setup.py install for ordered-set ... done
  Running setup.py install for dill ... done
  Running setup.py install for dnslib ... done
  Running setup.py install for pyaes ... done
  Running setup.py install for localstack-ext ... done
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 854, in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1069, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 351, in move_wheel_files
    console, gui = get_entrypoints(ep_file)
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 229, in get_entrypoints
    cp.readfp(data)
  File "/usr/lib64/python3.6/configparser.py", line 763, in readfp
    self.read_file(fp, source=filename)
  File "/usr/lib64/python3.6/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib64/python3.6/configparser.py", line 1092, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '<???>' [line 28]: option 'sqs' in section 'localstack.aws.provider' already exists
```

### Expected Behavior

The installation should be succefull.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

 pip3 install --user localstack

### Environment

```markdown
- OS: ReadHat 7.9
- LocalStack: latest
```

**Comment by devk86** [comment]
i am facing the same issue, and i am doing fresh installation on centos 8 for non-root user

Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 854, in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1069, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 351, in move_wheel_files
    console, gui = get_entrypoints(ep_file)
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 229, in get_entrypoints
    cp.readfp(data)
  File "/usr/lib64/python3.6/configparser.py", line 763, in readfp
    self.read_file(fp, source=filename)
  File "/usr/lib64/python3.6/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib64/python3.6/configparser.py", line 1092, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '<???>' [line 28]: option 'sqs' in section 'localstack.aws.provider' already exists

**Comment by HassanAhamed24** [comment]
Facing same problem.
Any workaround for this?

**Comment by johndotcocking** [comment]
In Ubuntu 18.04, with Python3 installed, I was able to work around this by installing version 0.13.0
`python3 -m pip install localstack==0.13.0`
This did not set the path properly, but I was able to call localstack via
`python3 -m localstack.cli.main`
