### ISSUE TITLE
Error when using localstack pro to test AWS Organizations 

### ISSUE THREAD

**Issue by ashmantak** [localstack/localstack#5263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

COMMAND - 
`awslocal organizations create-account --email susan@example.com --account-name "Test Account"
`

ERROR - 

```
An error occurred (500) when calling the CreateAccount operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

```

### Expected Behavior

Pro version should support AWS Organizations. 

https://github.com/localstack/localstack/issues/1268

Expected - 

AWS Organizations commands should run fine 

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`    docker run --rm -it -p 4566:4566 -p 4571:4571 -p 443:443 -e LOCALSTACK_API_KEY=<KEY> localstack/localstack:0.13.2`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal organizations create-account --email susan@example.com --account-name "Test Account"

### Environment

```markdown
- OS: 
- LocalStack:
```

**Comment by thrau** [comment]
This was an issue related to our fork of moto, which should be fixed now. Please give the latest image a try!

**Comment by ashmantak** [comment]
I tried with the latest image (0.13.3) but it gives the same error.

**Comment by thrau** [comment]
the latest image would be in the `latest` tag. could you run `docker pull localstack/localstack:latest`, and use that version for starting localstack?

**Comment by ashmantak** [comment]
Yes i did use this command to run - 

`docker run --rm -it -p 4566:4566 -p 4571:4571 -p 443:443 -e LOCALSTACK_API_KEY=<KEY> localstack/localstack:latest`

This is the error i am getting when i run command - 

`awslocal organizations create-account --email susan@example.com --account-name "Test Account"`

Error - 

`Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 239, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 161, in convert_flask_to_httpretty_response_call
    return convert_flask_to_httpretty_response_call_orig(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 147, in __call__
    result = self.callback(request, request.url, dict(request.headers))
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 203, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 313, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 403, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/organizations/responses.py", line 69, in create_account
    self.organizations_backend.create_account(**self.request_params)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/organizations/models.py", line 437, in create_account
    new_account = FakeAccount(self.org, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/organizations/models.py", line 62, in __init__
    self.organization_id = organization.id
AttributeError: 'NoneType' object has no attribute 'id'`

**Comment by thrau** [comment]
I can reproduce the error when starting localstack and immediately calling `awslocal organizations create-account --email susan@example.com --account-name "Test Account"`. If I run `awslocal organizations create-organization` first, then it seems to work fine. This makes sense as the error is telling me that it's trying to access an organization ID which doesn't exist yet.

Does that solve the issue? I agree that this could be more fault tolerant, maybe by automatically creating a default organization

**Comment by ashmantak** [comment]
if i run `awslocal organizations create-organization` first and then the command 
`awslocal organizations create-account --email susan@example.com --account-name "Test Account"` , it works. 

It would be great if we handle this use case gracefully though.

**Comment by jackos** [comment]
@thrau I get the same problem using both the `localstack start` and the latest docker image via:
```
docker run --rm -it -p 4566:4566 -p 4571:4571 -p 443:443 -e LOCALSTACK_API_KEY=4yUrNt151n localstack/localstack:latest
```
Your workaround still returns the same error for me when trying to create an organization with a working pro key:
```plaintext
Waiting for all LocalStack services to be ready
2022-05-22T05:51:15:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
```
```bash
awslocal organizations create-organization
```
```html
An error occurred (500) when calling the CreateOrganization operation (reached max retries: 2): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

**Comment by jackos** [comment]
@ashmantak an additional note is that this works when I use the image: [0.13.3.3](https://hub.docker.com/layers/localstack/localstack/localstack/0.13.3.3/images/sha256-6b7280f1728721e333be9741ebcd5de4d5561b2ad1c4139eae2ef30f12ac9e13?context=explore)

Which was around the time you made you comment with the workaround, so something must have changed since then
