### ISSUE TITLE
bug: 500 error when rotating secret

### ISSUE THREAD

**Issue by benallred** [localstack/localstack#5279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`awslocal secretsmanager rotate-secret ...` is returning `An error occurred (500) when calling the RotateSecret operation (reached max retries: 2)`

### Expected Behavior

Successful secret rotation or documentation somewhere that secret rotation is not supported.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=${SERVICES- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - DEFAULT_REGION=us-west-2
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

	  awslocal iam create-role --role-name ben-role --assume-role-policy-document $policy # comments on policy below
	  awslocal iam attach-role-policy --role-name ben-role --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
	  awslocal lambda create-function --function-name ben-lambda --zip-file fileb://lambda-function.zip --handler ApiKeyRotator::ApiKeyRotator.Function::FunctionHandler --runtime dotnetcore3.1 --role arn:aws:iam::000000000000:role/ben-role
	  awslocal secretsmanager create-secret --name ben-secret --secret-string "{'apikey': 'The API key!'}"
	  awslocal lambda add-permission --function-name arn:aws:lambda:us-west-2:000000000000:function:ben-lambda --principal secretsmanager.amazonaws.com --action lambda:InvokeFunction --statement-id SecretsManagerAccess
	  awslocal secretsmanager rotate-secret --secret-id ben-secret --rotation-lambda-arn arn:aws:lambda:us-west-2:000000000000:function:ben-lambda --rotation-rules AutomaticallyAfterDays=1

### Environment

```markdown
- OS: Windows 11
- LocalStack: `latest` (`docker inspect` tells me it is this commit: https://github.com/localstack/localstack/commit/6285b43bec57435a2179310a8de2af8d8d8cf8dd)
```

#### docker compose log of error

```
localstack_main  | 2022-01-14 18:49:45,835:API: Error on request:
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 319, in run_wsgi
localstack_main  |     execute(self.server.app)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 308, in execute
localstack_main  |     application_iter = app(environ, start_response)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 239, in __call__
localstack_main  |     return backend_app(environ, start_response)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
localstack_main  |     return self.wsgi_app(environ, start_response)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
localstack_main  |     response = self.handle_exception(e)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
localstack_main  |     response = self.full_dispatch_request()
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
localstack_main  |     rv = self.handle_user_exception(e)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
localstack_main  |     rv = self.dispatch_request()
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
localstack_main  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
localstack_main  |   File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 161, in convert_flask_to_httpretty_response_call
localstack_main  |     return convert_flask_to_httpretty_response_call_orig(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 147, in __call__
localstack_main  |     result = self.callback(request, request.url, dict(request.headers))
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 203, in dispatch
localstack_main  |     return cls()._dispatch(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 313, in _dispatch
localstack_main  |     return self.call_action()
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/responses.py", line 403, in call_action
localstack_main  |     response = method()
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/secretsmanager/responses.py", line 102, in rotate_secret
localstack_main  |     return secretsmanager_backends[self.region].rotate_secret(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/secretsmanager/models.py", line 515, in rotate_secret
localstack_main  |     func.invoke(
localstack_main  | AttributeError: 'dict' object has no attribute 'invoke'
```

#### Policy

This is the last policy I tried (the policy we finally got working in real AWS):

```
$policy = '{
    "Version": "2012-10-17",
    "Statement": [
    {
        "Action": [
        "secretsmanager:*",
        "cloudformation:CreateChangeSet",
        "cloudformation:DescribeChangeSet",
        "cloudformation:DescribeStackResource",
        "cloudformation:DescribeStacks",
        "cloudformation:ExecuteChangeSet",
        "ec2:DescribeSecurityGroups",
        "ec2:DescribeSubnets",
        "ec2:DescribeVpcs",
        "kms:DescribeKey",
        "kms:ListAliases",
        "kms:ListKeys",
        "lambda:ListFunctions",
        "rds:DescribeDBClusters",
        "rds:DescribeDBInstances",
        "redshift:DescribeClusters",
        "tag:GetResources"
        ],
        "Effect": "Allow",
        "Resource": "*"
    },
    {
        "Action": [
        "lambda:AddPermission",
        "lambda:CreateFunction",
        "lambda:GetFunction",
        "lambda:InvokeFunction",
        "lambda:UpdateFunctionConfiguration"
        ],
        "Effect": "Allow",
        "Resource": "arn:aws:lambda:*:*:function:SecretsManager*"
    },
    {
        "Action": [
        "serverlessrepo:CreateCloudFormationChangeSet",
        "serverlessrepo:GetApplication"
        ],
        "Effect": "Allow",
        "Resource": "arn:aws:serverlessrepo:*:*:applications/SecretsManager*"
    },
    {
        "Action": [
        "s3:GetObject"
        ],
        "Effect": "Allow",
        "Resource": [
        "arn:aws:s3:::awsserverlessrepo-changesets*",
        "arn:aws:s3:::secrets-manager-rotation-apps-*/*"
        ]
    }
    ]
}'
```

But I have also tried other, simpler things I've found in examples, such as:

`'{"Version": "2012-10-17", "Statement": [{ "Effect": "Allow", "Principal": {"Service": "lambda.amazonaws.com"}, "Action": "sts:AssumeRole"}]}'`

**Comment by pinzon** [comment]
The PR that addresses this issue has been merged. Thank you for reporting it.
