### ISSUE TITLE
botocore.exceptions.NoCredentialsError

### ISSUE THREAD

**Issue by sfdye** [localstack/localstack#528]
So I started localstack from docker-compose:
```yml
 localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=ap-southeast-1
    ports:
      - "4567-4582:4567-4582"
      - "8081:8081"
```

and I am able to use localstack from awslocal cli:
```bash
awslocal sqs list-queues
```
However I can't access it from my python code by using boto3:
```python
import boto3
client = boto3.client('sqs', endpoint_url='http://localhost:4576')
```
or using the python client:
```python
import localstack_client.session

session = localstack_client.session.Session()
sqs = session.client('sqs')
assert sqs.list_queues() is not None
```

> File "/usr/local/lib/python3.5/site-packages/botocore/auth.py", line 352, in add_auth
django_1        |     raise NoCredentialsError
django_1        | botocore.exceptions.NoCredentialsError: Unable to locate credentials

Why am I getting this in local environment? I thought the aws_id and aws_key are mocked in local environment?

**Comment by whummer** [comment]
Thanks for reporting @sfdye . That should indeed not happen. Can you please post the full stack trace for the second example where you have `import localstack_client.session`? Thanks

**Comment by rclmenezes** [comment]
I have the same setup and this is what I get:

```
>>> import localstack_client.session
>>> 
>>> session = localstack_client.session.Session()
>>> sqs = session.client('sqs')
>>> assert sqs.list_queues() is not None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 317, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 602, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 168, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 152, in create_request
    operation_name=operation_model.name)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python2.7/site-packages/botocore/signers.py", line 154, in sign
    auth.add_auth(request)
  File "/usr/local/lib/python2.7/site-packages/botocore/auth.py", line 352, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

**Comment by rclmenezes** [comment]
I fixed it by assigning some mock AWS creds in the environment:

```
myapp:
  build: ./myapp
  links:
    - localstack
  environment:
    - AWS_ACCESS_KEY_ID=foobar
    - AWS_DEFAULT_REGION=foobar
    - AWS_SECRET_ACCESS_KEY=foobar
```

But now I get `cannot assign requested address`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 317, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 602, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 172, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 265, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
botocore.vendored.requests.exceptions.ConnectionError: ('Connection aborted.', error(99, 'Cannot assign requested address'))
```

**Comment by rclmenezes** [comment]
Ah, the `Cannot assign requested address` comes from the fact that `localstack_client` tries to connect to `localhost`. If you're running localstack in your docker-compose under the name `localstack`, you need to connect to http://localstack:4576 :)

**Comment by whummer** [comment]
This should be fixed in https://github.com/localstack/localstack-python-client/pull/8 - can you please give it a try with the latest version `0.5` of localstack-client:
```
pip install --upgrade localstack-client
```

(The version of `localstack-client` still needs to be bumped in LocalStack, will be done in a follow-up PR)

**Comment by sfdye** [comment]
Thanks for the pointers @rclmenezes and @whummer for the fix ! Finally made it work work nicely with my other docker compose services. 

It seems that if you want to use localstack with docker compose, you must set the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables on the service that's linked with localstack in docker compose, even with random values, otherwise localstack could not successful mock the boto3 client. 

If this if the case, maybe it's both mentioning such behaviour in the docker compose section of the documentation?

**Comment by murari-goswami** [comment]
Hi @sfdye will it be possible to share the final docker-compose file. I am stuck with same issues.

**Comment by sfdye** [comment]
@murari-goswami I don't have it anymore but I think it's something like:

```
- environment:
  - AWS_ACCESS_KEY_ID=XXX
  - AWS_SECRET_ACCESS_KEY=XXX
```

**Comment by kjenney** [comment]
I ended up passing fake credentials to boto and that worked for me:
```
....
ENDPOINT_URL = "http://localhost.localstack.cloud:4566/"
AWS_S3_CREDS = {
    "aws_access_key_id":"foobar",
    "aws_secret_access_key":"foobar"
}

client = boto3.client("lambda", endpoint_url=ENDPOINT_URL, **AWS_S3_CREDS)
print(client.list_functions())
```
