### ISSUE TITLE
Creation of ElastiCache clusters fails when creating multiple standalone clusters in sequence

### ISSUE THREAD

**Issue by spasam** [localstack/localstack#5280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Always getting error when creating new Elasticache CreateCacheClusterCommand  with redis engine. Following is observed in localstack logs:

```
localstack_main | 2022-01-14T19:35:08.825:INFO:localstack_ext.services.elasticache.elasticache_api: Waiting for Redis server on tcp://localhost:4510 to start
localstack_main | 2022-01-14T19:35:08.847:INFO:localstack_ext.services.elasticache.elasticache_api: 1202:C 14 Jan 2022 19:35:08.846 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
localstack_main | 2022-01-14T19:35:08.847:INFO:localstack_ext.services.elasticache.elasticache_api: 1202:C 14 Jan 2022 19:35:08.846 # Redis version=5.0.14, bits=64, commit=00000000, modified=0, pid=1202, just started
localstack_main | 2022-01-14T19:35:08.847:INFO:localstack_ext.services.elasticache.elasticache_api: 1202:C 14 Jan 2022 19:35:08.846 # Configuration loaded
localstack_main | 2022-01-14T19:35:08.848:INFO:localstack_ext.services.elasticache.elasticache_api: 1202:M 14 Jan 2022 19:35:08.848 * Running mode=standalone, port=4510.
localstack_main | 2022-01-14T19:35:08.848:INFO:localstack_ext.services.elasticache.elasticache_api: 1202:M 14 Jan 2022 19:35:08.848 # Server initialized
localstack_main | 2022-01-14T19:35:08.848:INFO:localstack_ext.services.elasticache.elasticache_api: 1202:M 14 Jan 2022 19:35:08.848 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
localstack_main | 2022-01-14T19:35:08.848:INFO:localstack_ext.services.elasticache.elasticache_api: 1202:M 14 Jan 2022 19:35:08.848 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
localstack_main | 2022-01-14T19:35:08.848:INFO:localstack_ext.services.elasticache.elasticache_api: 1202:M 14 Jan 2022 19:35:08.848 * Ready to accept connections
localstack_main | 2022-01-14T19:35:09.333:WARNING:localstack_ext.services.elasticache.elasticache_api: Error handling request: 'RedisServer' object has no attribute 'add_node' Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/elasticache/elasticache_api.py.enc", line 394, in handle_request
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/elasticache/elasticache_api.py.enc", line 218, in create_cache_cluster
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/elasticache/elasticache_api.py.enc", line 191, in startup_cache_cluster
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/elasticache/elasticache_api.py.enc", line 172, in startup_cache_cluster_node
localstack_main | AttributeError: 'RedisServer' object has no attribute 'add_node'
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal elasticache create-cache-cluster --cache-cluster-id blah
```

An error occurred (CacheClusterAlreadyExists) when calling the CreateCacheCluster operation: You already have a cluster with the given identifier.

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```

**Comment by whummer** [comment]
Thanks for reporting @spasam . We have pushed a few enhancements for the ElastiCache API which should (hopefully) resolve this issue. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!

**Comment by spasam** [comment]
Ooops, missed your comments. Thanks @whummer . Checking it out.
