### ISSUE TITLE
bug: localstack stacktrace from apigateway get-integration-response

### ISSUE THREAD

**Issue by shield007** [localstack/localstack#5290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using boto3 I have some code that registers a service with the API Gateway. Upon querying the integration and integration responses, localstack throws a exception if they can't be found. When using real AWS, it gives a response.

This is the code that throws an exception for getting the integration response:
```
response = apigateway_client.get_integration_response(
            restApiId=rest_apigw_id,
            resourceId=resourceId,
            httpMethod=httpMethod,
            statusCode=statusCode,
        )
```

In localstack logs, I can see this: 
```
localstack_main           | Traceback (most recent call last):
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 319, in run_wsgi
localstack_main           |     execute(self.server.app)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 308, in execute
localstack_main           |     application_iter = app(environ, start_response)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 239, in __call__
localstack_main           |     return backend_app(environ, start_response)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
localstack_main           |     return self.wsgi_app(environ, start_response)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
localstack_main           |     response = self.handle_exception(e)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main           |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
localstack_main           |     response = self.full_dispatch_request()
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
localstack_main           |     rv = self.handle_user_exception(e)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main           |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
localstack_main           |     rv = self.dispatch_request()
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
localstack_main           |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
localstack_main           |   File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 161, in convert_flask_to_httpretty_response_call
localstack_main           |     return convert_flask_to_httpretty_response_call_orig(*args, **kwargs)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 147, in __call__
localstack_main           |     result = self.callback(request, request.url, dict(request.headers))
localstack_main           |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_starter.py", line 242, in apigateway_response_integration_responses
localstack_main           |     result = apigateway_response_integration_responses_orig(self, request, *args, **kwargs)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/apigateway/responses.py", line 519, in integration_responses
localstack_main           |     integration_response = self.backend.get_integration_response(
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/apigateway/models.py", line 1466, in get_integration_response
localstack_main           |     integration_response = integration.get_integration_response(status_code)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/apigateway/models.py", line 150, in get_integration_response
localstack_main           |     result = self.get("integrationResponses", {}).get(status_code)
localstack_main           | AttributeError: 'NoneType' object has no attribute 'get'
```

This can also be reporuced from within the local stack container, though in both of these examples you will need something registed with the api GW:
```
root@f4b8c5fb3f06:/opt/code/localstack# awslocal apigateway get-integration-response  --rest-api-id "$REST_API_ID" --resource-id "0zdwvrzgum" --http-method ANY --status-code 200

An error occurred (500) when calling the GetIntegrationResponse operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

As you can see, this return a 500 error and the localstack log simlar to the above.

### Expected Behavior

Dose not produce a local stack stacktrac

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

 awslocal apigateway get-integration-response  --rest-api-id "$REST_API_ID" --resource-id "0zdwvrzgum" --http-method ANY --status-code 200

### Environment

```markdown
- OS: 
- LocalStack:
```

### Anything else?

Using localstack 0.13.3

**Comment by calvernaz** [comment]
Hi @shield007, do you have the infrastructure code and steps to recreate the scenario?

**Comment by shield007** [comment]
@calvernaz It's part of our code base at the moment, so not easy to share the code. What we are doing is attempting to register a lambda with the API Gateway. So we setup all the resource, integrations and integration responses needed todo that. We have this method that handles the integration response:

```
def get_integration_response(
    apigateway_client, rest_apigw_id, resourceId, httpMethod, statusCode
):
    try:
        response = apigateway_client.get_integration_response(
            restApiId=rest_apigw_id,
            resourceId=resourceId,
            httpMethod=httpMethod,
            statusCode=statusCode,
        )
        return response
    except Exception:
        # Local stack's handling of it not been found is not very good. So just catch all exceptions
        return None
```

the exception catch at the end is handle when things go wrong and localstack response with a 500 error.  So in order to test this you'd need something that sets up a API Gateway, adds the methods, integrations etc....

**Comment by calvernaz** [comment]
Hi @shield007, I can't reproduce the same issue but i created a scenario that has all the resources you mentioned, so I'd like you to try and see if it works for you.

[scenario-5290.zip](https://github.com/localstack/localstack/files/7892455/scenario-5290.zip)

Unzip the run the following commands with LocalStack up:

```
terraform init; terraform plan; terraform apply --auto-approve
```

Then run the following
```
awslocal apigateway get-rest-apis
```
Get the `id` from the result of the command above,

```
awslocal apigateway get-resources  --rest-api-id $REST_API_ID
```

You should see something like this, 
```
 ...
 "id": "5fv1u9zd27",
...
 "ANY": {
          "httpMethod": "ANY",
          "authorizationType": "NONE",
          "apiKeyRequired": false,
          "methodIntegration": {
          "type": "AWS_PROXY",
          "httpMethod": "ANY",
          "uri": "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:000000000000:function:mylambda/invocations",
          "requestParameters": {},
          "passthroughBehavior": "WHEN_NO_MATCH",
          "timeoutInMillis": 29000,
           "cacheNamespace": "b54fb96b",
          "cacheKeyParameters": [],
          "integrationResponses": {
           "200": {
                   "statusCode": "200",
                   "responseTemplates": {
                  "application/xml": "#set($inputRoot = $input.path('$'))\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<message>\n    $inputRoot.body\n</message>\n"
                   }
            }
           }
   }
```

You should see the integration (lambda in this case) and the integration response. Now the litmus test,


```
awslocal apigateway get-integration-response --rest-api-id $REST_API_ID --resource-id $RESOURCE_ID --http-method ANY --status-code 200
```
Note: the resource id from the command above.

And get a response like this,

```
{
    "statusCode": "200",
    "responseTemplates": {
        "application/xml": "#set($inputRoot = $input.path('$'))\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<message>\n    $inputRoot.body\n</message>\n"
    }
}
```

**Comment by shield007** [comment]
Yes, I can frim that your test case works. So I'll go back and have another look at our code, maybe something is wrong. I did see this is the localstack log however when running the about test case:

```
localstack_main           | Traceback (most recent call last):
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 319, in run_wsgi
localstack_main           |     execute(self.server.app)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 308, in execute
localstack_main           |     application_iter = app(environ, start_response)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 239, in __call__
localstack_main           |     return backend_app(environ, start_response)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
localstack_main           |     return self.wsgi_app(environ, start_response)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
localstack_main           |     response = self.handle_exception(e)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main           |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
localstack_main           |     response = self.full_dispatch_request()
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
localstack_main           |     rv = self.handle_user_exception(e)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main           |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
localstack_main           |     rv = self.dispatch_request()
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
localstack_main           |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
localstack_main           |   File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 161, in convert_flask_to_httpretty_response_call
localstack_main           |     return convert_flask_to_httpretty_response_call_orig(*args, **kwargs)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 147, in __call__
localstack_main           |     result = self.callback(request, request.url, dict(request.headers))
localstack_main           |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_starter.py", line 242, in apigateway_response_integration_responses
localstack_main           |     result = apigateway_response_integration_responses_orig(self, request, *args, **kwargs)
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/apigateway/responses.py", line 529, in integration_responses
localstack_main           |     integration_response = self.backend.put_integration_response(
localstack_main           |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/apigateway/models.py", line 1457, in put_integration_response
localstack_main           |     integration_response = integration.create_integration_response(
localstack_main           | AttributeError: 'NoneType' object has no attribute 'create_integration_response'

```

**Comment by calvernaz** [comment]
It's hard to pinpoint exactly what is happening to you because I got no errors when trying this out and the error that is happening to you should be enough to make my test fail and seems like it's not falling for you.

Do you have another environment you can test this out?
