### ISSUE TITLE
bug: <localstack status docker not working>

### ISSUE THREAD

**Issue by johnnywiller** [localstack/localstack#5364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi I'm experiencing some incompatibility between `localstack-cli` and `docker`. My docker is running through [Colima](https://github.com/abiosoft/colima) so maybe this could be the cause.

I have localstack running via docker-compose, as
```
docker ps
CONTAINER ID   IMAGE                   COMMAND                  CREATED          STATUS          PORTS                                                                                                                                                             NAMES
ebe53d8dcb87   localstack_localstack   "docker-entrypoint.sh"   16 minutes ago   Up 16 minutes   0.0.0.0:4566-4599->4566-4599/tcp, :::4566-4599->4566-4599/tcp, 5678/tcp, 0.0.0.0:49175->7000/tcp, :::49175->7000/tcp, 0.0.0.0:9999->8080/tcp, :::9999->8080/tcp   localstack-localstack-1
```

if I run `localstack status services`, it works as expected showing the running services. But when run 
`localstack status docker` I get this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/localstack", line 23, in <module>
    main()
  File "/usr/local/bin/localstack", line 19, in main
    main.main()
  File "/usr/local/lib/python3.9/site-packages/localstack/cli/main.py", line 6, in main
    cli()
  File "/usr/local/lib/python3.9/site-packages/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/localstack/cli/localstack.py", line 67, in cmd_status_docker
    print_docker_status()
  File "/usr/local/lib/python3.9/site-packages/localstack/cli/localstack.py", line 343, in print_docker_status
    "Docker image", "tag: %s, id: %s, :calendar: %s" % (img["tag"], img["id"], img["created"])
KeyError: 'tag'
```

Localstack is started via `docker-compose` with `docker` inside `colima`.

Another problem worth noting is that when I try to start localstack with `localstack start`, I'm also getting an error like:
```
localstack start

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.13.3.3

[09:56:27] starting LocalStack in Docker mode 🐳                                                                       localstack.py:115
──────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ─────────────────────────────────────────────
Traceback (most recent call last):
  File "/usr/local/bin/localstack", line 23, in <module>
    main()
  File "/usr/local/bin/localstack", line 19, in main
    main.main()
  File "/usr/local/lib/python3.9/site-packages/localstack/cli/main.py", line 6, in main
    cli()
  File "/usr/local/lib/python3.9/site-packages/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/localstack/cli/localstack.py", line 128, in cmd_start
    bootstrap.start_infra_in_docker()
  File "/usr/local/lib/python3.9/site-packages/localstack/utils/bootstrap.py", line 663, in start_infra_in_docker
    prepare_docker_start()
  File "/usr/local/lib/python3.9/site-packages/localstack/utils/bootstrap.py", line 564, in prepare_docker_start
    if DOCKER_CLIENT.is_container_running(container_name):
  File "/usr/local/lib/python3.9/site-packages/localstack/utils/docker_utils.py", line 381, in is_container_running
    return container_name in self.get_running_container_names()
  File "/usr/local/lib/python3.9/site-packages/localstack/utils/docker_utils.py", line 375, in get_running_container_names
    result = self.list_containers(all=False)
  File "/usr/local/lib/python3.9/site-packages/localstack/utils/docker_utils.py", line 1266, in list_containers
    container_list = self.client().containers.list(filters=filter, all=all)
  File "/usr/local/lib/python3.9/site-packages/localstack/utils/docker_utils.py", line 1183, in client
    raise ContainerException("Docker not available")
localstack.utils.docker_utils.ContainerException: Docker not available
```

But docker is indeed available, since `docker info` shows me this
```
docker info
Client:
 Context:    colima
 Debug Mode: false

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 29
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1e5ef943eb76627a6d3b6de8cd1ef6537f393a71
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version:
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.88-0-virt
 Operating System: Alpine Linux v3.14
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.942GiB
 Name: colima
 ID: RW72:SHZO:YBCY:KSB4:7TGI:XSMA:KQGK:6MOZ:K6XU:AFWG:UOXS:7ZUF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

  localstack status 

### Environment

```markdown
- OS: 
- LocalStack:
```

**Comment by jloustel** [comment]
I was able to work around this by setting the `DOCKER_HOST` environment variable to the colima unix socket.

1. Find out the endpoint
```
> docker context list

NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                      KUBERNETES ENDPOINT   ORCHESTRATOR
colima              moby                colima                                    unix:///Users/<user>/.colima/docker.sock
default *           moby                Current DOCKER_HOST based configuration   unix://var/run/docker.sock                             swarm
desktop-linux       moby                                                          unix:///Users/<user>/.docker/run/docker.sock
```

2. Export the variable
```
> export DOCKER_HOST=unix:///Users/<user>/.colima/docker.sock
```
