### ISSUE TITLE
bug: can't create AWS EKS (k3s) cluster on localstack

### ISSUE THREAD

**Issue by slimdevl** [localstack/localstack#5373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using trial-pro license to evaluate cluster creation.

It fails (localstack backtrace observed) and then hangs the deployment automation.

See `reproduction` for a quick setup.

### Expected Behavior

Mock EKS cluster is created - and can deploy a k8s deployment

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

# Reproduction
Please see this reproduction repository: https://github.com/slimdevl/localstack-pulumi-eks-repo

### Environment

```markdown
* Running with Docker Compose
* OS: Ubuntu 21.10
* Localstack: latest (today)
```

### Anything else?

# Logs
```
Waiting for all LocalStack services to be ready
2022-01-27 00:32:00,402 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-01-27 00:32:00,403 INFO supervisord started with pid 14
2022-01-27 00:32:01,407 INFO spawned: 'infra' with pid 20
. .venv/bin/activate; LOCALSTACK_INFRA_PROCESS=1 exec bin/localstack start --host --no-banner
2022-01-27 00:32:02,421 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

LocalStack version: 0.13.3.3
LocalStack Docker container id: c51cc7988d28
LocalStack build date: 2022-01-25
LocalStack build git hash: 5cb915bd

2022-01-27T00:32:02.526:DEBUG:stevedore.extension: found extension EntryPoint(name='register_partition_adjusting_proxy_listener', value='localstack.plugins:register_partition_adjusting_proxy_listener', group='localstack.hooks.on_infra_start')
2022-01-27T00:32:02.527:DEBUG:stevedore.extension: found extension EntryPoint(name='setup_pro_infra', value='localstack_ext.plugins:setup_pro_infra', group='localstack.hooks.on_infra_start')
2022-01-27T00:32:02.533:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_partition_adjusting_proxy_listener = <function register_partition_adjusting_proxy_listener at 0x7fa87f7ff040>)
2022-01-27T00:32:02.533:DEBUG:plugin.manager: plugin localstack.hooks.on_infra_start:register_partition_adjusting_proxy_listener is disabled
2022-01-27T00:32:02.534:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.on_infra_start.setup_pro_infra = <function setup_pro_infra at 0x7fa87f748b80>)
2022-01-27T00:32:02.534:DEBUG:plugin.manager: loading plugin localstack.hooks.on_infra_start:setup_pro_infra
2022-01-27T00:32:02.535:DEBUG:localstack_ext.bootstrap.install: Attempting to download local SSL certificate file
2022-01-27T00:32:02.683:DEBUG:localstack.utils.common: Starting download from https://github.com/localstack/localstack-artifacts/raw/master/local-certs/server.key to /var/lib/localstack/cache/server.test.pem (5163 bytes)
2022-01-27T00:32:02.689:DEBUG:localstack.utils.common: Done downloading https://github.com/localstack/localstack-artifacts/raw/master/local-certs/server.key, response code 200, total bytes 7575
2022-01-27T00:32:02.695:WARNING:localstack_ext.plugins: !! Configuring EDGE_PORT=4566 without setting EDGE_PORT_HTTP may lead to issues; better leave the defaults, or set EDGE_PORT=443 and EDGE_PORT_HTTP=4566
2022-01-27T00:32:03.279:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
2022-01-27T00:32:03.461:DEBUG:localstack.utils.run: Executing command: whoami
2022-01-27T00:32:03.466:DEBUG:localstack.utils.run: Executing command:  python -c "import sys; f=open(sys.argv[1]).read(); open(sys.argv[1], 'w').write('\n' + f)" /etc/resolv.conf
2022-01-27T00:32:03.491:DEBUG:localstack.utils.run: Executing command:  python -c "import sys; f=open(sys.argv[1]).read(); open(sys.argv[1], 'w').write('nameserver 0.0.0.0\n' + f)" /etc/resolv.conf
2022-01-27T00:32:03.517:DEBUG:localstack.utils.run: Executing command:  python -c "import sys; f=open(sys.argv[1]).read(); open(sys.argv[1], 'w').write('# The following line is required by LocalStack\n' + f)" /etc/resolv.conf
Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
Starting edge router (https port 4566)...
2022-01-27T00:32:06.040:INFO:localstack_ext.utils.aws.metadata_service: Starting AWS instance metadata service on port 80
2022-01-27T00:32:06.052:INFO:botocore.credentials: Found credentials in environment variables.
2022-01-27T00:32:06.060:INFO:botocore.credentials: Found credentials in environment variables.
2022-01-27T00:32:06.069:DEBUG:localstack.services.install: getting kinesis-mock for linux x86_64
2022-01-27T00:32:06.069:DEBUG:localstack.services.install: kinesis-mock found at /opt/code/localstack/localstack/infra/kinesis-mock/kinesis-mock-linux-amd64-static
2022-01-27T00:32:06.070:DEBUG:localstack.utils.run: Executing command: cd "/opt/code/localstack/localstack/infra/dynamodb" && zip -u DynamoDBLocal.jar log4j2.xml || true
2022-01-27T00:32:06.124:DEBUG:localstack_ext.bootstrap.install: Using cached SSL certificate (less than 6hrs since last update).
[2022-01-27 00:32:06 +0000] [21] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2022-01-27T00:32:06.129:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
Ready.
2022-01-27T00:32:17.038:DEBUG:localstack_ext.services.dns_server: Determined fallback dns: 127.0.0.11
2022-01-27T00:33:04.846:WARNING:localstack_ext.services.ec2.ec2_starter: VM manager not reachable: MyHTTPConnectionPool(host='172.17.0.1', port=4600): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa877a801f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2022-01-27T00:33:04.846:INFO:localstack.services.infra: Starting mock EC2 service on http port 4566 ...
2022-01-27T00:33:04.847:INFO:localstack.services.motoserver: starting moto server on http://0.0.0.0:52167
2022-01-27T00:33:04.847:DEBUG:localstack.services.plugins: checking service health ec2:52167
2022-01-27T00:33:08.073:INFO:localstack.services.infra: Starting mock IAM service on http port 4566 ...
2022-01-27T00:33:08.073:DEBUG:localstack.services.plugins: checking service health iam:52167
2022-01-27T00:33:10.075:INFO:localstack.services.infra: Starting mock EKS service on http port 4566 ...
2022-01-27T00:33:10.076:DEBUG:localstack.services.plugins: checking service health eks:41835
2022-01-27 00:33:10,076:API:  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2022-01-27T00:33:10.579:DEBUG:localstack.utils.docker_utils: Getting networks for container: localstack-pulumi-eks-repo_localstack_1
2022-01-27T00:33:10.581:INFO:localstack.services.awslambda.lambda_utils: Determined lambda container network: localstack-pulumi-eks-repo_internal
2022-01-27T00:33:10.581:DEBUG:localstack.utils.docker_utils: Getting ipv4 address for container localstack-pulumi-eks-repo_localstack_1 in network localstack-pulumi-eks-repo_internal.
2022-01-27T00:33:10.584:INFO:localstack.services.awslambda.lambda_utils: Determined main container target IP: 172.22.0.2
2022-01-27T00:33:11.008:DEBUG:localstack.utils.common: Starting download from https://github.com/rancher/k3d/releases/download/v5.0.1-rc.1/k3d-linux-amd64 to /var/lib/localstack/var_libs/k3d.linux.bin (17125376 bytes)
2022-01-27T00:33:11.088:DEBUG:localstack.utils.common: Written 1048576 bytes (total 1048576) to /var/lib/localstack/var_libs/k3d.linux.bin
2022-01-27T00:33:11.131:DEBUG:localstack.utils.common: Written 1048576 bytes (total 2097152) to /var/lib/localstack/var_libs/k3d.linux.bin
2022-01-27T00:33:11.168:DEBUG:localstack.utils.common: Written 1048576 bytes (total 3145728) to /var/lib/localstack/var_libs/k3d.linux.bin
2022-01-27T00:33:11.206:DEBUG:localstack.utils.common: Written 1048576 bytes (total 4194304) to /var/lib/localstack/var_libs/k3d.linux.bin
2022-01-27T00:33:11.241:DEBUG:localstack.utils.common: Written 1048576 bytes (total 5242880) to /var/lib/localstack/var_libs/k3d.linux.bin
2022-01-27T00:33:11.285:DEBUG:localstack.utils.common: Written 1048576 bytes (total 6291456) to /var/lib/localstack/var_libs/k3d.linux.bin
2022-01-27T00:33:11.319:DEBUG:localstack.utils.common: Written 1048576 bytes (total 7340032) to /var/lib/localstack/var_libs/k3d.linux.bin
2022-01-27T00:33:11.345:DEBUG:localstack.utils.common: Written 1048576 bytes (total 8388608) to /var/lib/localstack/var_libs/k3d.linux.bin
2022-01-27T00:33:11.379:DEBUG:localstack.utils.common: Written 1048576 bytes (total 9437184) to /var/lib/localstack/var_libs/k3d.linux.bin
2022-01-27T00:33:11.420:DEBUG:localstack.utils.common: Written 1048576 bytes (total 10485760) to /var/lib/localstack/var_libs/k3d.linux.bin
2022-01-27T00:33:11.455:DEBUG:localstack.utils.common: Written 1048576 bytes (total 11534336) to /var/lib/localstack/var_libs/k3d.linux.bin
2022-01-27T00:33:11.492:DEBUG:localstack.utils.common: Written 1048576 bytes (total 12582912) to /var/lib/localstack/var_libs/k3d.linux.bin
2022-01-27T00:33:11.526:DEBUG:localstack.utils.common: Written 1048576 bytes (total 13631488) to /var/lib/localstack/var_libs/k3d.linux.bin
2022-01-27T00:33:11.602:DEBUG:localstack.utils.common: Written 1048576 bytes (total 14680064) to /var/lib/localstack/var_libs/k3d.linux.bin
2022-01-27T00:33:11.635:DEBUG:localstack.utils.common: Written 1048576 bytes (total 15728640) to /var/lib/localstack/var_libs/k3d.linux.bin
2022-01-27T00:33:11.680:DEBUG:localstack.utils.common: Written 1048576 bytes (total 16777216) to /var/lib/localstack/var_libs/k3d.linux.bin
2022-01-27T00:33:11.716:DEBUG:localstack.utils.common: Done downloading https://github.com/rancher/k3d/releases/download/v5.0.1-rc.1/k3d-linux-amd64, response code 200, total bytes 17125376
2022-01-27T00:33:11.718:DEBUG:localstack.utils.run: Executing command: ['/var/lib/localstack/var_libs/k3d.linux.bin', 'cluster', 'create', 'eks-cluster-44b8be3', '--api-port', '6443', '-p', '8081:80@loadbalancer']
2022-01-27T00:33:41.718:INFO:localstack_ext.services.eks.k8s_utils: Error creating cluster eks-cluster-44b8be3 - deleting and retrying: 
2022-01-27T00:33:41.719:DEBUG:localstack.utils.run: Executing command: ['/var/lib/localstack/var_libs/k3d.linux.bin', 'cluster', 'delete', 'eks-cluster-44b8be3']
2022-01-27T00:33:42.776:DEBUG:localstack.utils.run: Executing command: ['/var/lib/localstack/var_libs/k3d.linux.bin', 'cluster', 'create', 'eks-cluster-44b8be3', '--api-port', '6443', '-p', '8081:80@loadbalancer']
2022-01-27T00:34:12.778:INFO:localstack_ext.services.eks.k8s_utils: Error creating cluster eks-cluster-44b8be3 - deleting and retrying: 
2022-01-27T00:34:12.779:DEBUG:localstack.utils.run: Executing command: ['/var/lib/localstack/var_libs/k3d.linux.bin', 'cluster', 'delete', 'eks-cluster-44b8be3']
2022-01-27T00:34:13.826:DEBUG:localstack.utils.run: Executing command: ['/var/lib/localstack/var_libs/k3d.linux.bin', 'cluster', 'create', 'eks-cluster-44b8be3', '--api-port', '6443', '-p', '8081:80@loadbalancer']
2022-01-27T00:34:43.835:INFO:localstack_ext.services.eks.k8s_utils: Error creating cluster eks-cluster-44b8be3 - deleting and retrying: 
2022-01-27T00:34:43.836:DEBUG:localstack.utils.run: Executing command: ['/var/lib/localstack/var_libs/k3d.linux.bin', 'cluster', 'delete', 'eks-cluster-44b8be3']
2022-01-27T00:34:44.881:INFO:localstack.utils.run: Thread run method <function start_cluster.<locals>._startup at 0x7fa87feade50>(None) failed:  Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/run.py", line 153, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/eks/eks_api.py.enc", line 50, in _startup
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/eks/k8s_utils.py.enc", line 109, in create_cluster
  File "/opt/code/localstack/localstack/utils/common.py", line 945, in retry
    raise raise_error
  File "/opt/code/localstack/localstack/utils/common.py", line 941, in retry
    return function(**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/eks/k8s_utils.py.enc", line 104, in _try
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/eks/k8s_utils.py.enc", line 127, in _try_create_cluster
AssertionError
```

**Comment by whummer** [comment]
Thanks for reporting @slimdevl , and for providing the reproducible example. We have now pushed a few enhancements for the EKS API - can you please pull the `latest` Docker image and give it another try?

Please note that we had to make a small change in the service spec in your `main.go` file:
```
				// Type:     pulumi.String("LoadBalancer"),
				Type:     pulumi.String("ClusterIP"),
```
.. and then create an ingress definition to allow in-bound access to the created service (e.g., using a path mapping `/test123`):
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /test123
        pathType: Prefix
        backend:
          serviceName: app-service-rn3t7mc3  # <- this line may need to be adjusted!
          servicePort: 80
```
Assuming this file is stored as `/tmp/test.yml`, then this ingress can be created via:
```
kubectl apply -f /tmp/test.yml  --namespace joe-duffy
```

After deploying the Pulumi stack and applying the ingress, the app can then be accessed as follows:
```
% curl localhost:8081/test123
Hello Kubernetes bootcamp! | Running on: app-dep-6bppnmc4-5ddf7b8bdd-phjwb | v=2
```

Hope that helps - please keep us posted on how it goes.. Thanks for your help!

**Comment by whummer** [comment]
Hi @slimdevl , apologies for the long radio silence. Have you been able to give it a try with the `latest` Docker image? Please let us know if the problem is resolved, so we can close this issue.. Thanks!

**Comment by slimdevl** [comment]
Yes, I'm sorry also - been heads down on a project for a bit. I did try this with the suggested changes - and it worked well. Thank you for the follow up. Our team works on Win/Mac/Linux - would you expect any differences between those envs that I should keep an eye open for?
