### ISSUE TITLE
bug: SQS FIFO Queue Does Not Support Message Group ID Parameter

### ISSUE THREAD

**Issue by blairehh** [localstack/localstack#5374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When posting a message to a FIFO SQS group with a message group ID specified an exception is thrown due to parameter not valid for this queue type.

Stack trace
```
Value ffadbccdbbfcfaf for parameter MessageGroupId is invalid. Reason: The request include parameter that is not valid for this queue type. (Service: AmazonSQS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 7U7UIF4KFXSTNOVI8AGKP5SMTMA21PRAUSLD1TF5M3DQ2GCRKIQM; Proxy: null)
com.amazonaws.services.sqs.model.AmazonSQSException: Value ffadbccdbbfcfaf for parameter MessageGroupId is invalid. Reason: The request include parameter that is not valid for this queue type. (Service: AmazonSQS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 7U7UIF4KFXSTNOVI8AGKP5SMTMA21PRAUSLD1TF5M3DQ2GCRKIQM; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1819)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1403)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1372)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2283)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2250)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2239)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeSendMessage(AmazonSQSClient.java:1826)
	at com.amazonaws.services.sqs.AmazonSQSClient.sendMessage(AmazonSQSClient.java:1795)
	at BugDemo.fails(BugDemo.java:37)
```

### Expected Behavior

SQS FIFO queues should support messages with message group id

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker compose file
```docker
version: '3'
services:
  aws:
    image: localstack/localstack:0.13.3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - SKIP_SSL_CERT_DOWNLOAD=1
    networks:
      - net
networks:
  net:
    driver: bridge
```

java test showing one that works without message group and one that fails that uses message group id
```java
import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.SendMessageRequest;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.util.UUID;

public class BugDemo {

    private static AmazonSQS sqs;

    @BeforeAll
    static void setup() {
         sqs = AmazonSQSClientBuilder.standard()
            .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localhost:4566", "eu-west-1"))
            .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials("test", "test")))
            .build();
    }

    @Test
    void fails() {
        String queueName = randomString();
        CreateQueueRequest createQueue = new CreateQueueRequest();
        createQueue.setQueueName(queueName + ".fifo");
        String queueUrl = sqs.createQueue(createQueue).getQueueUrl();

        final SendMessageRequest request = new SendMessageRequest();
        request.setQueueUrl(queueUrl);
        request.setMessageGroupId(randomString());
        request.setMessageDeduplicationId(randomString());
        request.setMessageBody("this is the message");

        sqs.sendMessage(request);
    }

    @Test
    void works() {
        String queueName = randomString();
        CreateQueueRequest createQueue = new CreateQueueRequest();
        createQueue.setQueueName(queueName + ".fifo");
        String queueUrl = sqs.createQueue(createQueue).getQueueUrl();

        final SendMessageRequest request = new SendMessageRequest();
        request.setQueueUrl(queueUrl);
        request.setMessageDeduplicationId(randomString());
        request.setMessageBody("this is the message");

        sqs.sendMessage(request);
    }
    private static String randomString() {
        return UUID.randomUUID().toString()
            .replace("-", "")
            .replace("0", "")
            .replace("1", "")
            .replace("2", "")
            .replace("3", "")
            .replace("4", "")
            .replace("5", "")
            .replace("6", "")
            .replace("7", "")
            .replace("8", "")
            .replace("9", "");
    }
}
```

### Environment

```markdown
- OS: ubuntu 21.10
- LocalStack: 0.13.3
```

### Anything else?

This was working but has broken in recent version

**Comment by blairehh** [comment]
In the test I wrote i was not creating FIFO queues so the message group id was not valid. As for the actual system I was working on that experienced this I found at that I now need to pass `--attributes FifoQueue=true`  into the cli command when creating queues
