### ISSUE TITLE
bug: Cloudtrail fails with an invalid timestamp None

### ISSUE THREAD

**Issue by abarbu** [localstack/localstack#5431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This happens when attempting to create a trail with CloudTrail from Terraform with the Pro version of localstack. The creation is successful but then Terrraform attempts to verify that the trail is created by doing the equivalent of:

```
aws cloudtrail get-trail-status --name trail-name --endpoint-url=http://localhost:4566
``` 

This results in the following error

```
2022-02-06 05:00:28,044 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-02-06T05:00:28.043:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
Starting mock Azure APIs (port 12121)
[2022-02-06 05:00:30 +0000] [21] [INFO] Running on https://0.0.0.0:12121 (CTRL + C to quit)
2022-02-06T05:00:30.282:INFO:hypercorn.error: Running on https://0.0.0.0:12121 (CTRL + C to quit)
Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
Starting edge router (http port 4566)...
Starting edge router (https port 443)...
Ready.
2022-02-06T05:00:30.483:INFO:localstack_ext.utils.aws.metadata_service: Starting AWS instance metadata service on port 80
2022-02-06T05:00:30.525:INFO:botocore.credentials: Found credentials in environment variables.
2022-02-06T05:00:30.540:INFO:botocore.credentials: Found credentials in environment variables.
[2022-02-06 05:00:30 +0000] [21] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2022-02-06T05:00:30.611:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
[2022-02-06 05:00:30 +0000] [21] [INFO] Running on https://0.0.0.0:443 (CTRL + C to quit)
2022-02-06T05:00:30.614:INFO:hypercorn.error: Running on https://0.0.0.0:443 (CTRL + C to quit)
2022-02-06T05:00:43.651:INFO:botocore.credentials: Found credentials in environment variables.
2022-02-06T05:00:46.211:INFO:localstack_ext.utils.websockets: Starting websocket server on port 4510
2022-02-06T05:00:46.249:INFO:websockets.server: server listening on 0.0.0.0:4510
2022-02-06T05:01:01.932:WARNING:localstack_ext.services.ec2.ec2_starter: VM manager not reachable: MyHTTPConnectionPool(host='172.17.0.1', port=4600): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3cf2436640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2022-02-06T05:01:04.737:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: Invalid timestamp "None": Parser must be a string or character stream, not NoneType Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/utils.py", line 848, in _parse_timestamp_with_tzinfo
return dateutil.parser.parse(value, tzinfos={'GMT': tzutc()})
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 1368, in parse
return DEFAULTPARSER.parse(timestr, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 640, in parse
res, skipped_tokens = self._parse(timestr, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 719, in _parse
l = _timelex.split(timestr)         # Splits the timestr into tokens
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 201, in split
return list(cls(s))
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/dateutil/parser/_parser.py", line 69, in __init__
raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 159, in index
result = await run_sync(handler, request, data)
File "/opt/code/localstack/localstack/utils/async_utils.py", line 86, in run_sync
return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
File "/opt/code/localstack/localstack/utils/run.py", line 153, in run
result = self.func(self.params, **kwargs)
File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
return fn(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 960, in handler
response = modify_and_forward(
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 513, in wrapper
value = func(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 593, in modify_and_forward
listener_result = listener.forward_request(
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py.enc", line 198, in forward_request
File "/opt/code/localstack/localstack/services/edge.py", line 173, in forward_request
result = do_forward_request(api, method, path, data, headers, port=port)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py.enc", line 192, in do_forward_request
File "/opt/code/localstack/localstack/services/edge.py", line 228, in do_forward_request
result = do_forward_request_inmem(api, method, path, data, headers, port=port)
File "/opt/code/localstack/localstack/services/edge.py", line 252, in do_forward_request_inmem
response = modify_and_forward(
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 513, in wrapper
value = func(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 593, in modify_and_forward
listener_result = listener.forward_request(
File "/opt/code/localstack/localstack/aws/proxy.py", line 48, in forward_request
response = self.skeleton.invoke(context)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
return self.dispatch_request(context, instance)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 167, in dispatch_request
return self.serializer.serialize_to_response(result, operation)
File "/opt/code/localstack/localstack/aws/protocol/serializer.py", line 125, in serialize_to_response
self._serialize_payload(
File "/opt/code/localstack/localstack/aws/protocol/serializer.py", line 732, in _serialize_payload
self._serialize(body, parameters, shape)
File "/opt/code/localstack/localstack/aws/protocol/serializer.py", line 738, in _serialize
method(body, value, shape, key)
File "/opt/code/localstack/localstack/aws/protocol/serializer.py", line 766, in _serialize_type_structure
self._serialize(body, member_value, member_shape, member_key)
File "/opt/code/localstack/localstack/aws/protocol/serializer.py", line 738, in _serialize
method(body, value, shape, key)
File "/opt/code/localstack/localstack/aws/protocol/serializer.py", line 790, in _serialize_type_timestamp
body[key] = self._convert_timestamp_to_str(
File "/opt/code/localstack/localstack/aws/protocol/serializer.py", line 245, in _convert_timestamp_to_str
datetime_obj = parse_to_aware_datetime(value)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/utils.py", line 908, in parse_to_aware_datetime
datetime_obj = parse_timestamp(value)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/utils.py", line 867, in parse_timestamp
return _parse_timestamp_with_tzinfo(value, tzinfo)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/utils.py", line 850, in _parse_timestamp_with_tzinfo
raise ValueError('Invalid timestamp "%s": %s' % (value, e))
ValueError: Invalid timestamp "None": Parser must be a string or character stream, not NoneType
```

This keeps repeating as the aws command repeatedly attempts get-trail-status.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Create a cloud trail. Then run

```
aws cloudtrail get-trail-status --name trail-name --endpoint-url=http://localhost:4566
```

### Environment

```markdown
- OS: Ubuntu 18.04
- LocalStack: latest

LocalStack version: 0.14.0
LocalStack Docker container id: 3a13e05083de
LocalStack build date: 2022-02-04
LocalStack build git hash: e023c9bd
```

**Comment by whummer** [comment]
Thanks for reporting @abarbu , and apologies for the delay. In the meantime we have fixed a couple of enhancements for CloudTrail, as well as the general response parsing. Can you please pull the `latest` Docker image and give it another try?

With `latest` and the following Terraform script:
```
resource "aws_cloudtrail" "foobar" {
  name                          = "tf-trail-foobar"
  s3_bucket_name                = aws_s3_bucket.foo.id
  s3_key_prefix                 = "prefix"
  include_global_service_events = false
}

resource "aws_s3_bucket" "foo" {
  bucket        = "tf-test-trail"
}
```
... it seems to be working:
```
$ awslocal cloudtrail get-trail-status --name tf-trail-foobar
{
    "IsLogging": true,
    "StartLoggingTime": 1648845738.681,
    "LatestDeliveryAttemptTime": "",
    "LatestNotificationAttemptTime": "",
    "LatestNotificationAttemptSucceeded": "",
    "LatestDeliveryAttemptSucceeded": "",
    "TimeLoggingStarted": "2022-04-01T20:42:18Z",
    "TimeLoggingStopped": ""
}
```
Please let us know if the problem persists on your end.. Thanks!
