### ISSUE TITLE
AWS SAM CLI for LocalStack: Could not connect to the endpoint URL: "http://localhost:4566/"

### ISSUE THREAD

**Issue by gc2000** [localstack/localstack#5435]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

## AWS SAM for LocalStack

I've successfully installed and run LocalStack via LocalStack CLI.
I'm testing AWS SAM based on the guideline in [https://docs.localstack.cloud/integrations/aws-sam/](https://docs.localstack.cloud/integrations/aws-sam/).
 and [https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html)

- [ ] step1: samlocal init -> successful
- [ ] step2: samlocal build -> successful
- [ ] step3: samlocal deploy --guided -> failed
>> **python C:\Python38\Scripts\\samlocal deploy --guided**

The error shows "EndpointConnectionError: Could not connect to the endpoint URL: "http://localhost:4566/"".

Any idea how to address this issue?

Thanks!

### Anything else?

Configuring SAM deploy
```
Looking for config file [samconfig.toml] :  Not found

 Setting default arguments for 'sam deploy'
        =========================================
        Stack Name [sam-app]: sam-app1
        AWS Region [us-east-1]: us-east-1
        #Shows you resources changes to be deployed and require a 'Y' to initiate deploy
        Confirm changes before deploy [y/N]: N
        #SAM needs permission to be able to create roles to connect to the resources in your template
        Allow SAM CLI IAM role creation [Y/n]: Y
        #Preserves the state of previously provisioned resources when an operation fails
        Disable rollback [y/N]: N
        HelloWorldFunction may not have authorization defined, Is this okay? [y/N]: y
        Save arguments to configuration file [Y/n]: Y
        SAM configuration file [samconfig.toml]: samconfig.toml
        SAM configuration environment [default]: default

Looking for resources needed for deployment:
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Python38\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Python38\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\botocore\httpsession.py", line 403, in send
    urllib_response = conn.urlopen(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Python38\lib\site-packages\urllib3\util\retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python38\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Python38\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python38\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Python38\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python38\lib\site-packages\botocore\awsrequest.py", line 92, in _send_request
    rval = super(AWSConnection, self)._send_request(
  File "C:\Python38\lib\http\client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python38\lib\site-packages\botocore\awsrequest.py", line 120, in _send_output
    self.send(msg)
  File "C:\Python38\lib\site-packages\botocore\awsrequest.py", line 204, in send
    return super(AWSConnection, self).send(str)
  File "C:\Python38\lib\http\client.py", line 946, in send
    self.connect()
  File "C:\Python38\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "C:\Python38\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPConnection object at 0x000001E9ED4FF880>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\Scripts\\samlocal", line 41, in <module>
    main.cli()
  File "C:\Python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Python38\lib\site-packages\samcli\lib\cli_validation\image_repository_validation.py", line 92, in wrapped
    return func(*args, **kwargs)
  File "C:\Python38\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Python38\lib\site-packages\samcli\lib\telemetry\metric.py", line 166, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Python38\lib\site-packages\samcli\lib\telemetry\metric.py", line 124, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Python38\lib\site-packages\samcli\lib\utils\version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Python38\lib\site-packages\samcli\cli\main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Python38\lib\site-packages\samcli\commands\_utils\cdk_support_decorators.py", line 38, in wrapped
    return func(*args, **kwargs)
  File "C:\Python38\lib\site-packages\samcli\commands\deploy\command.py", line 165, in cli
    do_cli(
  File "C:\Python38\lib\site-packages\samcli\commands\deploy\command.py", line 255, in do_cli
    guided_context.run()
  File "C:\Python38\lib\site-packages\samcli\commands\deploy\guided_context.py", line 559, in run
    self.guided_prompts(_parameter_override_keys)
  File "C:\Python38\lib\site-packages\samcli\commands\deploy\guided_context.py", line 181, in guided_prompts
    s3_bucket = manage_stack(profile=self.profile, region=region)
  File "C:\Python38\lib\site-packages\samcli\lib\bootstrap\bootstrap.py", line 22, in manage_stack
    outputs: StackOutput = manage_cloudformation_stack(
  File "C:\Python38\lib\site-packages\samcli\lib\utils\managed_cloudformation_stack.py", line 86, in manage_stack
    return _create_or_get_stack(cloudformation_client, stack_name, template_body, parameter_overrides)
  File "C:\Python38\lib\site-packages\samcli\lib\utils\managed_cloudformation_stack.py", line 97, in _create_or_get_stack
    ds_resp = cloudformation_client.describe_stacks(StackName=stack_name)
  File "C:\Python38\lib\site-packages\botocore\client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Python38\lib\site-packages\botocore\client.py", line 705, in _make_api_call
    http, parsed_response = self._make_request(
  File "C:\Python38\lib\site-packages\botocore\client.py", line 725, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "C:\Python38\lib\site-packages\botocore\endpoint.py", line 106, in make_request
    return self._send_request(request_dict, operation_model)
  File "C:\Python38\lib\site-packages\botocore\endpoint.py", line 182, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "C:\Python38\lib\site-packages\botocore\endpoint.py", line 301, in _needs_retry
    responses = self._event_emitter.emit(
  File "C:\Python38\lib\site-packages\botocore\hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\Python38\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "C:\Python38\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "C:\Python38\lib\site-packages\botocore\retryhandler.py", line 192, in __call__
    if self._checker(**checker_kwargs):
  File "C:\Python38\lib\site-packages\botocore\retryhandler.py", line 265, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "C:\Python38\lib\site-packages\botocore\retryhandler.py", line 292, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "C:\Python38\lib\site-packages\botocore\retryhandler.py", line 331, in __call__
    checker_response = checker(attempt_number, response,
  File "C:\Python38\lib\site-packages\botocore\retryhandler.py", line 231, in __call__
    return self._check_caught_exception(
  File "C:\Python38\lib\site-packages\botocore\retryhandler.py", line 374, in _check_caught_exception
    raise caught_exception
  File "C:\Python38\lib\site-packages\botocore\endpoint.py", line 248, in _do_get_response
    http_response = self._send(request)
  File "C:\Python38\lib\site-packages\botocore\endpoint.py", line 317, in _send
    return self.http_session.send(request)
  File "C:\Python38\lib\site-packages\botocore\httpsession.py", line 432, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://localhost:4566/"
```

**Comment by whummer** [comment]
Thanks for reporting @gc2000 . Looks like `samlocal` is unable to connect to the LocalStack edge port `4566` - can you please share your LocalStack configuration, and double-check if LocalStack is up and running on port 4566? Thanks

**Comment by gc2000** [comment]
Hi @whummer ,
**1.  Can run "localstack start", but with error "INFO:hypercorn.error: Running on https://0.0.0.0:4566"**
>> python C:\Python38\Scripts\\localstack start

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.14.0

[20:35:48] starting LocalStack in Docker mode 🐳                                                                                           localstack.py:115
2022-02-07T20:35:53.361:INFO:bootstrap.py: Execution of "prepare_host" took 5111.77ms
────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ───────────────────────────────────────────────────────
Waiting for all LocalStack services to be ready
2022-02-07 12:35:57,175 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-02-07 12:35:57,181 INFO supervisord started with pid 15
2022-02-07 12:35:58,183 INFO spawned: 'infra' with pid 21
. .venv/bin/activate; LOCALSTACK_INFRA_PROCESS=1 exec bin/localstack start --host --no-banner
2022-02-07 12:35:59,194 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
LocalStack version: 0.14.0
LocalStack Docker container id: 8fcf7d9f144f
LocalStack build date: 2022-02-06
LocalStack build git hash: d9dfacfe

Starting edge router (https port 4566)...
Ready.
[2022-02-07 12:36:00 +0000] [22] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2022-02-07T12:36:00.707:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
2022-02-07T12:40:17.457:INFO:localstack.services.motoserver: starting moto server on http://0.0.0.0:40613
2022-02-07T12:40:17.458:INFO:localstack.services.infra: Starting mock S3 service on http port 4566 ...

**2. Can create S3 bucket successfully**
>> aws --endpoint-url=http://localhost:4566/ s3 mb s3://test-bucket
File association not found for extension .py
make_bucket: test-bucket

**3. >>localstack config show**
![image](https://user-images.githubusercontent.com/12391578/152790576-dbc1c83e-9a44-4902-b71c-225444e5c5a2.png)

**Comment by gc2000** [comment]
@whummer 
Sorry, it probably was because I didn't run "localstack start", before run "samlocal deploy --guided". 
I re-run the whole process, the issue is resolved now.

Thanks!
