### ISSUE TITLE
bug: Unable to start Localstack on proxy server

### ISSUE THREAD

**Issue by Rontala** [localstack/localstack#5450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to start localstack on a proxy server.

[root@p-build localstack]# localstack start

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.14.0

[13:58:52] starting LocalStack in Docker mode 🐳                                                                                                                        localstack.py:115
───────────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ─────────────────────────────────────────────────────────────────────
Waiting for all LocalStack services to be ready
2022-02-08 18:58:54,030 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-02-08 18:58:54,032 INFO supervisord started with pid 15
2022-02-08 18:58:55,035 INFO spawned: 'infra' with pid 21
. .venv/bin/activate; LOCALSTACK_INFRA_PROCESS=1 exec bin/localstack start --host --no-banner
2022-02-08 18:58:56,042 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

LocalStack version: 0.14.0
LocalStack Docker container id: f165ebf7ee34
LocalStack build date: 2022-02-07
LocalStack build git hash: 4aa29eea

Starting edge router (https port 4566)...
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2022-02-08 18:59:11,483 INFO exited: infra (exit status 2; not expected)
2022-02-08 18:59:11,485 INFO spawned: 'infra' with pid 146
Error starting infrastructure: gave up waiting for edge server on 0.0.0.0:4566 Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/infra.py", line 414, in start_infra
thread = do_start_infra(asynchronous, apis, is_in_docker)
File "/opt/code/localstack/localstack/services/infra.py", line 528, in do_start_infra
thread = start_runtime_components()
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/infra.py", line 520, in start_runtime_components
raise TimeoutError(
TimeoutError: gave up waiting for edge server on 0.0.0.0:4566

. .venv/bin/activate; LOCALSTACK_INFRA_PROCESS=1 exec bin/localstack start --host --no-banner
2022-02-08T18:59:11.262:INFO:bootstrap.py: Execution of "start_runtime_components" took 14737.30ms
Traceback (most recent call last):
File "bin/localstack", line 23, in <module>
main()
File "bin/localstack", line 19, in main
main.main()
File "/opt/code/localstack/localstack/cli/main.py", line 6, in main
cli()
File "/opt/code/localstack/localstack/cli/plugin.py", line 15, in __call__
self.group(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
return self.main(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 1053, in main
rv = self.invoke(ctx)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/click/core.py", line 754, in invoke
return __callback(*args, **kwargs)
File "/opt/code/localstack/localstack/cli/localstack.py", line 123, in cmd_start
bootstrap.start_infra_locally()
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 299, in start_infra_locally
return infra.start_infra()
File "/opt/code/localstack/localstack/services/infra.py", line 428, in start_infra
raise e
File "/opt/code/localstack/localstack/services/infra.py", line 414, in start_infra
thread = do_start_infra(asynchronous, apis, is_in_docker)
File "/opt/code/localstack/localstack/services/infra.py", line 528, in do_start_infra
thread = start_runtime_components()
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 79, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/infra.py", line 520, in start_runtime_components
raise TimeoutError(
TimeoutError: gave up waiting for edge server on 0.0.0.0:4566
make: *** [Makefile:284: infra] Error 1
2022-02-08 18:59:12,492 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

[root@p-build localstack]# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.45.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 5.669GiB
 Name: pcs-build
 ID: 5KJB:26DI:6YMP:5ER3:DC2Y:MDPC:WK7N:QTUF:GMF2:K456:GZFP:FZMA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://p-prox01-lab.net:3128/
 HTTPS Proxy: http://p-prox01-lab.net:3128/
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

I also tried with the docker-compose file, If the use SQS service, i get the below error:

localstack_main | 2022-02-08T18:51:42.317:INFO:localstack.services.infra: Starting mock SQS service on http port 4566 ...
localstack_main | 2022-02-08T18:51:42.318:INFO:localstack.services.motoserver: starting moto server on http://0.0.0.0:36018/
localstack_main | 2022-02-08T18:51:42.561:INFO:localstack.utils.run: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7f908c1955e0>(None) failed: not well-formed (invalid token): line 1, column 95 Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/utils/run.py", line 153, in run
localstack_main |     result = self.func(self.params, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
localstack_main |     return fn(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 960, in handler
localstack_main |     response = modify_and_forward(
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 513, in wrapper
localstack_main |     value = func(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 593, in modify_and_forward
localstack_main |     listener_result = listener.forward_request(
localstack_main |   File "/opt/code/localstack/localstack/services/edge.py", line 173, in forward_request
localstack_main |     result = do_forward_request(api, method, path, data, headers, port=port)
localstack_main |   File "/opt/code/localstack/localstack/services/edge.py", line 228, in do_forward_request
localstack_main |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_main |   File "/opt/code/localstack/localstack/services/edge.py", line 252, in do_forward_request_inmem
localstack_main |     response = modify_and_forward(
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 513, in wrapper
localstack_main |     value = func(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 686, in modify_and_forward
localstack_main |     updated_response = listener.return_response(
localstack_main |   File "/opt/code/localstack/localstack/services/sqs/sqs_listener.py", line 386, in return_response
localstack_main |     _fire_event(req_data, response)
localstack_main |   File "/opt/code/localstack/localstack/services/sqs/sqs_listener.py", line 174, in _fire_event
localstack_main |     response_data = xmltodict.parse(response.content)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/xmltodict.py", line 327, in parse
localstack_main |     parser.Parse(xml_input, True)
localstack_main | xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 95
localstack_main | 
localstack_main | 2022-02-08T18:51:42.561:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://X.9.X.X:4566/: not well-formed (invalid token): line 1, column 95 Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 159, in index
localstack_main |     result = await run_sync(handler, request, data)
localstack_main |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 86, in run_sync
localstack_main |     return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
localstack_main |   File "/opt/code/localstack/localstack/utils/run.py", line 153, in run
localstack_main |     result = self.func(self.params, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
localstack_main |     return fn(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 960, in handler
localstack_main |     response = modify_and_forward(
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 513, in wrapper
localstack_main |     value = func(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 593, in modify_and_forward
localstack_main |     listener_result = listener.forward_request(
localstack_main |   File "/opt/code/localstack/localstack/services/edge.py", line 173, in forward_request
localstack_main |     result = do_forward_request(api, method, path, data, headers, port=port)
localstack_main |   File "/opt/code/localstack/localstack/services/edge.py", line 228, in do_forward_request
localstack_main |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_main |   File "/opt/code/localstack/localstack/services/edge.py", line 252, in do_forward_request_inmem
localstack_main |     response = modify_and_forward(
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 513, in wrapper
localstack_main |     value = func(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 686, in modify_and_forward
localstack_main |     updated_response = listener.return_response(
localstack_main |   File "/opt/code/localstack/localstack/services/sqs/sqs_listener.py", line 386, in return_response
localstack_main |     _fire_event(req_data, response)
localstack_main |   File "/opt/code/localstack/localstack/services/sqs/sqs_listener.py", line 174, in _fire_event
localstack_main |     response_data = xmltodict.parse(response.content)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/xmltodict.py", line 327, in parse
localstack_main |     parser.Parse(xml_input, True)
localstack_main | xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 95

### Expected Behavior

Localstack should start normally on the proxy server too.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    pip install localstack
    localstack start

OR 

     docker-compose up

### Environment

```markdown
- OS: 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- LocalStack: 0.14.0
```

**Comment by steffyP** [comment]
Hi @Rontala, 
do you still see this error with recent versions of LocalStack?
