### ISSUE TITLE
bug: CustomErrorResponses and default root object for cloudfront do not appear to be triggered

### ISSUE THREAD

**Issue by paulrobello** [localstack/localstack#5496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have an SPA application served via CloudFront from S3. As the SPA uses custom urls that do not exist I have created a custom error response in CloudFront to redirect requests that are not found to the index.html page that contains the SPA so it can handle the virtual routing. When I make a request to an item that does not exist the custom error response is not being triggered.
Also the default root object of index.html is not activated when the url does not contain a path or object

### Expected Behavior

When requesting a route such as / the default root object of index.html should be served. Also when using a route that does not exist such as /debug which does not exist it should use the custom error response and load /index.html which will then handle the virtual routing within the SPA and load the users view within the SPA.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Used Pulumi Typescript.
Created repo to reproduce errors here:

[https://github.com/paulrobello/localstack_cloud_front_bug](https://github.com/paulrobello/localstack_cloud_front_bug)

run make file with with target  ups  to bring up localstack build and deploy pulumi project
once up and deployed use 

`make get-da-link`  to get the host record that must be used in your hosts file pointing to 127.0.0.1. 

Then use https://LINK and https://LINK/ to see that default root object is not working. Then use https://LINK/debug to see that custom error handler is not working.

### Environment

```markdown
- OS: OSX 12.2 and Windows 11 Pro
- LocalStack: latest
- Docker Desktop: Latest
```

**Comment by whummer** [comment]
Thanks @paulrobello - this issue should be (hopefully) fixed in the `latest` image by now. Please let us know if the problem persists.. Thanks for your help!

**Comment by paulrobello** [comment]
I just tested with latest and my stack fails to deploy now. the local stacks logs contain this

> 2022-02-25T16:47:56.943:INFO:localstack.utils.threads: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7f508d872670>(None) failed: no provider exists for service cloudfront Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 32, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 966, in handler
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 512, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 592, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request
    self._require_service(api)
  File "/opt/code/localstack/localstack/services/edge.py", line 222, in _require_service
    raise HTTPErrorResponse("no provider exists for service %s" % api, code=500)
localstack.utils.server.http2_server.HTTPErrorResponse: no provider exists for service cloudfront

**Comment by paulrobello** [comment]
new error with latest latest:
>2022-02-25T21:55:59.523:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request GET http://localhost:4566/2020-05-31/origin-access-identity/cloudfront/5dab5f2c: get_cloud_front_origin_access_identity() got an unexpected keyword argument 'id' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 159, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 87, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 32, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 966, in handler
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 512, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 592, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py.enc", line 212, in forward_request
  File "/opt/code/localstack/localstack/services/edge.py", line 177, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py.enc", line 206, in do_forward_request
  File "/opt/code/localstack/localstack/services/edge.py", line 232, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 256, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 512, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 592, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/http/adapters.py", line 34, in forward_request
    response = self.request(request)
  File "/opt/code/localstack/localstack/aws/proxy.py", line 42, in request
    response = self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
    return self.fn(*args, **kwargs)
TypeError: get_cloud_front_origin_access_identity() got an unexpected keyword argument 'id'

**Comment by paulrobello** [comment]
confirmed fixed with latest
