### ISSUE TITLE
bug: unable to create subnet with terraform

### ISSUE THREAD

**Issue by JSanchezIO** [localstack/localstack#5504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm unable to create a `subnet` resource when `private_dns_hostname_type_on_launch` is set to `ip-name`

<details>
<summary>Error Message</summary>
<pre>
Error: Plugin did not respond

  with aws_subnet.my_subnet,
  on vpc.tf line 38, in resource "aws_subnet" "my_subnet":
  38: resource "aws_subnet" "my_subnet" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ApplyResourceChange call. The plugin
logs may contain more details.
</pre>
</details>

<details>
<summary>Trace Logs</summary>
<pre>
Stack trace from the terraform-provider-aws_v3.74.2_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x105463f48]

goroutine 335 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ec2.StatusSubnetPrivateDNSHostnameTypeOnLaunch.func1(0x1400292bed8, 0x1400292be90, 0x0, 0x0, 0x2, 0x10df3de01)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/ec2/status.go:463 +0xa8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1(0x14002234d20, 0x1400208ec40, 0x140028c7440, 0x140022339c0, 0x140012eb6c8, 0x140012eb6c0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/resource/state.go:110 +0x240
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/resource/state.go:83 +0x16c
</pre>
</details>

### Expected Behavior

I'm able to create a `subnet` resource when `private_dns_hostname_type_on_launch` is set to `ip-name`

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

1. Create Terraform Resources
   ```
   terraform {
     required_providers {
       aws = {
         source  = "hashicorp/aws"
         version = "~> 3"
       }
     }
   }
   
   provider "aws" {
     endpoints {
       ec2                      = "http://localhost:4566"
     }
   
     access_key                  = "test"
     region                      = "us-east-1"
     secret_key                  = "test"
     skip_credentials_validation = true
     skip_metadata_api_check     = true
     skip_requesting_account_id  = true
   }

    resource "aws_vpc" "default" {
     cidr_block = "some-cidr"
   }
   
   resource "aws_subnet" "my_subnet" {
     availability_zone                   = "us-east-1a"
     cidr_block                          = "some-cidr"
     private_dns_hostname_type_on_launch = "ip-name"
     vpc_id                              = aws_vpc.default.id
   }
   ```
2. Start LocalStack
3. Apply Terraform

### Environment

```markdown
- OS: M1 Mac Monterey
- LocalStack: latest
```

**Comment by Cesarsk** [comment]
Hello,

I have tried the following and apparently it is working with the latest docker-compose.yml

```
resource "aws_vpc" "test_vpc" {
  cidr_block = "10.0.100.0/24"
}

resource "aws_subnet" "main" {
  vpc_id     = aws_vpc.test_vpc.id
  cidr_block = "10.0.100.0/28"
  availability_zone                   = "us-east-1a"
  private_dns_hostname_type_on_launch = "ip-name"
}
```

![image](https://user-images.githubusercontent.com/3224160/164943564-7ae58d99-bdba-4313-8c14-243aab722e73.png)
