### ISSUE TITLE
Issue while invoking lambda from SNS

### ISSUE THREAD

**Issue by ShashiUpadhyay** [localstack/localstack#554]
Hi,

I am facing an issue when I am trying to invoke a node js lambda function from SNS. 

I have set ARN of node js lambda function as an endpoint for SNS topic. I am getting below error when I tried to publish message on the SNS topic.

Below are the steps which I have followed to create and invoke lambda function.

Command to start localstack:
```
linux-tzkf:/tmp/localstack # export LAMBDA_EXECUTOR=docker
linux-tzkf:/tmp/localstack # export SERVICES=s3,sqs,sns,lambda
linux-tzkf:/tmp/localstack # /usr/local/bin/localstack start
Starting local dev environment. CTRL-C to quit.
Starting mock S3 (http port 4572)...
Starting mock SNS (http port 4575)...
Starting mock SQS (http port 4576)...
Starting mock Lambda service (http port 4574)...
Ready.
```

Step 1: I created node js function helloworld.js. Below is it's code snippet.
```
console.log('Loading function'); 
exports.handler = function(event, context, callback) { 
console.log('value1 =', event.key1); 
console.log('value2 =', event.key2); 
console.log('value3 =', event.key3); 
callback(null,"Success");
};
```
Step 2: Zipped this file as helloworld.zip

Step 3: Create lambda function using the below-mentioned command.

Command: 
```
aws --endpoint-url=http://localhost:4574 lambda create-function --region us-east-1 --function-name helloworld --zip-file fileb://helloworld.zip --role arn:aws:iam::000000000000:role/lambda_basic_execution --handler helloworld.handler --runtime nodejs6.10 --profile default --description "SNS X Account Test Function" --timeout 60 --memory-size 128 --environment Variables={LAMBDA_EXECUTOR=docker}
```

Below is the output of list-function command 
```
aws --endpoint-url=http://localhost:4574 lambda list-functions 
```
Output:
```
{ 
"Functions": [ 
 { "Version": "$LATEST", 
"FunctionName": "helloworld", 
"FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:helloworld", 
"Handler": "helloworld.handler", 
"Timeout": 60, 
"Runtime": "nodejs6.10" } ]
 }
```
Step 4: Trying to invoke lambda function

Below is the Java code to invoke Lambda Function:
```
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.regions.Region;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.sns.AmazonSNS;
import com.amazonaws.services.sns.AmazonSNSClient;
import com.amazonaws.services.sns.model.CreateTopicRequest;
import com.amazonaws.services.sns.model.CreateTopicResult;
import com.amazonaws.services.sns.model.PublishRequest;
import com.amazonaws.services.sns.model.PublishResult;
import com.amazonaws.services.sns.model.SubscribeRequest;

public class LambdaDriver {
	
	public static final String LAMBDA_FUNCTION_ARN = "arn:aws:lambda:us-east-1:000000000000:function:helloworld";
	
	public static void main(String[] args){
		AmazonSNS snsEndpoint = new AmazonSNSClient(new BasicAWSCredentials("test", "test"));
		snsEndpoint.setRegion(Region.getRegion(Regions.US_EAST_1));
		snsEndpoint.setEndpoint("http://localhost:4575");
		
		//create a new SNS topic
		CreateTopicRequest createTopicRequest = new CreateTopicRequest("MyNewTopic");
		CreateTopicResult createTopicResult = snsEndpoint.createTopic(createTopicRequest);
		//print TopicArn
		System.out.println("createTopicResult --> " + createTopicResult);
		
		//get request id for CreateTopicRequest from SNS metadata		
		System.out.println("CreateTopicRequest - " + snsEndpoint.getCachedResponseMetadata(createTopicRequest));
		
		String topicArn = createTopicResult.getTopicArn();
		System.out.println("Topic ARN --> " + topicArn);		
		SubscribeRequest subscriberequest = new SubscribeRequest(topicArn, "lambda", LAMBDA_FUNCTION_ARN);
		String subscriptionArn = snsEndpoint.subscribe(subscriberequest).getSubscriptionArn();
		
		//get request id for SubscribeRequest from SNS metadata
		System.out.println("SubscribeRequest - " + snsEndpoint.getCachedResponseMetadata(subscriberequest));
		System.out.println("Check aws console for subscription.");
		
		
		//publish to an SNS topic
		String msg = "My text published to SNS topic with email endpoint";
		PublishRequest publishRequest = new PublishRequest(topicArn, msg);
		PublishResult publishResult = snsEndpoint.publish(publishRequest);
		//print MessageId of message published to SNS topic
		System.out.println("MessageId - " + publishResult.getMessageId());
		
	}
}
```

**## Error which I am getting on console:**
```
WARNING:localstack.services.awslambda.lambda_api:Error executing Lambda function: Unable to find executor for Lambda function "helloworld". Note that Node.js Lambdas currently require LAMBDA_EXECUTOR=docker Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/localstack/services/awslambda/lambda_api.py", line 296, in run_lambda
    process.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/localstack/services/awslambda/lambda_api.py", line 292, in do_execute
    result = func(event, context)
  File "/usr/local/lib/python3.6/site-packages/localstack/services/awslambda/lambda_api.py", line 370, in generic_handler
    'Note that Node.js Lambdas currently require LAMBDA_EXECUTOR=docker') % lambda_name)
Exception: Unable to find executor for Lambda function "helloworld". Note that Node.js Lambdas currently require LAMBDA_EXECUTOR=docker

WARNING:localstack.services.awslambda.lambda_api:Unable to run Lambda function on SNS message: working outside of application context Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/localstack/services/awslambda/lambda_api.py", line 296, in run_lambda
    process.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/localstack/services/awslambda/lambda_api.py", line 292, in do_execute
    result = func(event, context)
  File "/usr/local/lib/python3.6/site-packages/localstack/services/awslambda/lambda_api.py", line 370, in generic_handler
    'Note that Node.js Lambdas currently require LAMBDA_EXECUTOR=docker') % lambda_name)
Exception: Unable to find executor for Lambda function "helloworld". Note that Node.js Lambdas currently require LAMBDA_EXECUTOR=docker

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/localstack/services/awslambda/lambda_api.py", line 181, in process_sns_notification
    run_lambda(lambda_function, event=event, context={}, func_arn=func_arn)
  File "/usr/local/lib/python3.6/site-packages/localstack/utils/cloudwatch/cloudwatch_util.py", line 108, in wrapped
    raise e
  File "/usr/local/lib/python3.6/site-packages/localstack/utils/cloudwatch/cloudwatch_util.py", line 104, in wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/localstack/services/awslambda/lambda_api.py", line 300, in run_lambda
    return error_response("Error executing Lambda function: %s %s" % (e, traceback.format_exc()))
  File "/usr/local/lib/python3.6/site-packages/localstack/services/awslambda/lambda_api.py", line 350, in error_response
    return make_response((jsonify(result), code, headers))
  File "/usr/local/lib/python3.6/site-packages/flask/json.py", line 234, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] \
  File "/usr/local/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python3.6/site-packages/flask/globals.py", line 34, in _find_app
    raise RuntimeError('working outside of application context')
RuntimeError: working outside of application context
```

**Comment by whummer** [comment]
Thanks for reporting @ShashiUpadhyay .

> Step 2: Zipped this file as helloworld.zip

Can you please double-check the contents of your zip file, sometimes the filesystem structure gets mirrored into the zip file. What is the output of:
```
unzip -l helloworld.zip
```

**Comment by whummer** [comment]
Closing this issue as outdated/obsolete. Please create a follow-up issue with error details if the problem persists. Thanks
