### ISSUE TITLE
bug: Cognito Custom Email Sender raises exceptions

### ISSUE THREAD

**Issue by merowinger92** [localstack/localstack#5540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

us-east-1

```
2022-02-17T17:44:47.779:DEBUG:localstack_ext.services.cognito.cognito_idp_api: Encrypting Cognito activation code with KMS key ID arn:aws:kms:us-east-1:000000000000:key/afa4cc56-a43d-4a81-957d-51ac4347874f
2022-02-17T17:44:48.141:INFO:localstack_ext.services.cognito.cognito_idp_api: Error in Cognito action "SignUp": 'dict' object has no attribute 'split' Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_idp_api.py.enc", line 1752, in forward_request
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_idp_api.py.enc", line 800, in signup_user
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_idp_api.py.enc", line 707, in send_confirmation_email
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_triggers.py.enc", line 53, in call_cognito_trigger
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 778, in run_lambda
    region_name = func_arn.split(":")[3]
AttributeError: 'dict' object has no attribute 'split'
```

eu-central-1

```
2022-02-17T20:02:58.936:DEBUG:localstack_ext.services.cognito.cognito_idp_api: Encrypting Cognito activation code with KMS key ID arn:aws:kms:eu-central-1:000000000000:key/badacfa9-4703-4d68-bcb8-a1845edcba2e
2022-02-17T20:02:58.968:INFO:localstack_ext.services.cognito.cognito_idp_api: Error in Cognito action "SignUp": An error occurred (NotFoundException) when calling the Encrypt operation: Key 'arn:aws:kms:eu-central-1:000000000000:key/badacfa9-4703-4d68-bcb8-a1845edcba2e' does not exist Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_idp_api.py.enc", line 1752, in forward_request
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_idp_api.py.enc", line 800, in signup_user
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/cognito/cognito_idp_api.py.enc", line 704, in send_confirmation_email
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NotFoundException: An error occurred (NotFoundException) when calling the Encrypt operation: Key 'arn:aws:kms:eu-central-1:000000000000:key/badacfa9-4703-4d68-bcb8-a1845edcba2e' does not exist
```

### Expected Behavior

No Exceptions are raised and the Lambda Function is correctly triggered.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run --rm -it -p 4566:4566 -p 4571:4571 -e LOCALSTACK_API_KEY=api_key -e DEBUG=1 localstack/localstack

Localstack was started with `DEBUG` enabled in order to get the provided stack trace. 

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Repository to reproduce the bug: https://github.com/merowinger92/localstack-custom-mail-sender-bug

Steps:
1. Run localstack: `docker run --rm -it -p 4566:4566 -p 4571:4571 -e LOCALSTACK_API_KEY=api_key -e DEBUG=1 localstack/localstack`
2. Install dependencies: `npm run setup`
3. Create Localstack stack: `npm run cdk-local-stack`
4. Run `npm run test-bug` to see the bug in console.

### Environment

```markdown
- OS: Windows 11/ Ubuntu 20.04
- LocalStack: 0.14
```

### Anything else?

Using different `CDK_DEFAULT_REGION` produces different Exceptions as shown in the bug report.

**Comment by merowinger92** [comment]
For the first error the suspected problem is that a special handling is needed for `CustomEmailSender` and `CustomSmsSender` Trigger, since they are not coming in a form of a single `String` but rather in a form of 
```
{
  "LambdaArn" : String,
  "LambdaVersion" : String
}
```

See documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html
