### ISSUE TITLE
bug: is 'Invalid bucket name "?acl=": Bucket name must match the regex' issue localstack?

### ISSUE THREAD

**Issue by patsevanton** [localstack/localstack#5566]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Hello! Thanks for localstack
I try to create a bucket by example: https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html

My terraform code in main.tf
```
# Create a bucket
resource "aws_s3_bucket" "bucket1" {
  bucket = "my-hosted-content"
}

# Upload an object
resource "aws_s3_bucket_object" "object" {
  bucket = aws_s3_bucket.bucket1.id
  key    = "test.txt"
  source = "test.txt"
}
```

But localstack have an issue/error:

```
docker-compose up
[+] Running 1/1
 ⠿ Container localstack_main  Created                                                                                                             1.0s
Attaching to localstack_main
localstack_main  | Waiting for all LocalStack services to be ready
localstack_main  | 2022-02-24 08:33:06,308 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_main  | 2022-02-24 08:33:06,310 INFO supervisord started with pid 14
localstack_main  | 2022-02-24 08:33:07,313 INFO spawned: 'infra' with pid 20
localstack_main  |
localstack_main  | LocalStack version: 0.14.0
localstack_main  | LocalStack Docker container id: 1c2faf75475e
localstack_main  | LocalStack build date: 2022-02-23
localstack_main  | LocalStack build git hash: 9c0cf677
localstack_main  |
localstack_main  | Starting edge router (https port 4566)...
localstack_main  | 2022-02-24 08:33:08,955 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_main  | [2022-02-24 08:33:08 +0000] [20] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main  | 2022-02-24T08:33:08.955:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main  | Ready.
localstack_main  | 2022-02-24T08:33:09.233:INFO:bootstrap.py: Execution of "start_runtime_components" took 1205.99ms


localstack_main  | 2022-02-24T08:33:32.631:INFO:localstack.services.infra: Starting mock EC2 service on http port 4566 ...
localstack_main  | 2022-02-24T08:33:32.632:INFO:localstack.services.motoserver: starting moto server on http://0.0.0.0:35739
localstack_main  | 2022-02-24T08:33:33.091:INFO:localstack.services.infra: Starting mock S3 service on http port 4566 ...
localstack_main  | 2022-02-24T08:33:33.354:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request GET http://test-s3-bucket.localhost:4566/?acl=: Parameter validation failed:
localstack_main  | Invalid bucket name "?acl=": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$" Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 159, in index
localstack_main  |     result = await run_sync(handler, request, data)
localstack_main  |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 87, in run_sync
localstack_main  |     return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
localstack_main  |   File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
localstack_main  |     result = self.func(self.params, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 32, in _run
localstack_main  |     return fn(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 966, in handler
localstack_main  |     response = modify_and_forward(
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 512, in wrapper
localstack_main  |     value = func(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 592, in modify_and_forward
localstack_main  |     listener_result = listener.forward_request(
localstack_main  |   File "/opt/code/localstack/localstack/services/edge.py", line 177, in forward_request
localstack_main  |     result = do_forward_request(api, method, path, data, headers, port=port)
localstack_main  |   File "/opt/code/localstack/localstack/services/edge.py", line 232, in do_forward_request
localstack_main  |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_main  |   File "/opt/code/localstack/localstack/services/edge.py", line 256, in do_forward_request_inmem
localstack_main  |     response = modify_and_forward(
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 512, in wrapper
localstack_main  |     value = func(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 685, in modify_and_forward
localstack_main  |     updated_response = listener.return_response(
localstack_main  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1536, in return_response
localstack_main  |     exists, code, body = is_bucket_available(bucket_name)
localstack_main  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 855, in is_bucket_available
localstack_main  |     exists, code = bucket_exists(bucket_name)
localstack_main  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 877, in bucket_exists
localstack_main  |     s3_client.head_bucket(Bucket=bucket_name)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
localstack_main  |     return self._make_api_call(operation_name, kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 691, in _make_api_call
localstack_main  |     request_dict = self._convert_to_request_dict(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 737, in _convert_to_request_dict
localstack_main  |     api_params = self._emit_api_params(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 766, in _emit_api_params
localstack_main  |     self.meta.events.emit(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 357, in emit
localstack_main  |     return self._emitter.emit(aliased_event_name, **kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
localstack_main  |     return self._emit(event_name, kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
localstack_main  |     response = handler(**kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/handlers.py", line 253, in validate_bucket_name
localstack_main  |     raise ParamValidationError(report=error_msg)
localstack_main  | botocore.exceptions.ParamValidationError: Parameter validation failed:
localstack_main  | Invalid bucket name "?acl=": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
localstack_main  |
localstack_main  | 2022-02-24T08:33:33.354:INFO:localstack.utils.threads: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7f4f4f1f1280>(None) failed: Parameter validation failed:
```

Version:
localstack
```
localstack_main  | LocalStack version: 0.14.0
localstack_main  | LocalStack Docker container id: 1c2faf75475e
localstack_main  | LocalStack build date: 2022-02-23
localstack_main  | LocalStack build git hash: 9c0cf677
```

Terraform 
```
Terraform v1.1.4
on linux_amd64
```

plugins
```
Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/aws v4.2.0...
- Installed hashicorp/aws v4.2.0 (signed by HashiCorp)
```

provider.tf
```
provider "aws" {
  access_key                  = "test"
  secret_key                  = "test"
  region                      = "us-east-1"
  s3_force_path_style         = false
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    ec2 = "http://localhost:4566"
    s3  = "http://localhost:4566"
  }
}
```

**Comment by patsevanton** [comment]
If i use bucket name my_hosted_content then get error
```
│ Error: Error creating S3 bucket: InvalidBucketName: The specified bucket is not valid.
│       status code: 400, request id: 3DCCE1B27109D63E, host id: MzRISOwyjmnup3DCCE1B27109D63E7/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp
```

**Comment by patsevanton** [comment]
Same issue with simple code
```
# Create a bucket
resource "aws_s3_bucket" "bucket1" {
  bucket = "tests3bucket"
}

# Upload an object
resource "aws_s3_bucket_object" "object" {
  bucket = aws_s3_bucket.bucket1.id
  key    = "test.txt"
  source = "test.txt"
}
```

**Comment by patsevanton** [comment]
I run 
```
awslocal s3 mb s3://tests3bucket
```
The bucket tests3bucket will create without error.

**Comment by dmueller-tetra** [comment]
I am also experiencing a very similar problem. 

This works
```
aws --endpoint-url=http://localhost:4566 s3 mb s3://mwaa1
make_bucket: mwaa1
```

I have tried to create the bucket with terraform

```
provider "aws" {
  access_key                  = "dummyaccess"
  region                      = "us-east-1"
  secret_key                  = "dummysecret"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    dynamodb = "http://localhost:4566"
    lambda   = "http://localhost:4566"
    kinesis  = "http://localhost:4566"
    kms      = "http://localhost:4566"
    s3       = "http://localhost:4566"
  }
}

resource "aws_s3_bucket" "this" {
  bucket = "mwaa1"
}
```
Here is the Terraform Plan

```
Terraform will perform the following actions:

  # module.dfir_infra.aws_s3_bucket.this will be created
  + resource "aws_s3_bucket" "this" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "mwaa1"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

I get an error about Reg and the Bucket Name. but you can see `mwaa1` is allowed.

```
localstack      |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/handlers.py", line 253, in validate_bucket_name
localstack      |     raise ParamValidationError(report=error_msg)
localstack      | botocore.exceptions.ParamValidationError: Parameter validation failed:
localstack      | Invalid bucket name "?acl=": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
```

**Comment by adrianoavelino** [comment]
for me only works if I use the property  ` s3_use_path_style = true` in my provider. Ex:

```
provider "aws" {
  region                      = "us-east-1"
  access_key                  = "teste"
  secret_key                  = "teste"
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true
  profile                     = "localstack"
  s3_use_path_style           = true
  endpoints {
    ec2 = "http://localhost:4566"
    s3 = "http://localhost:4566"
  }
}
```

**Comment by patsevanton** [comment]
Yes.
I checked without profile.
Worked code
```
provider "aws" {
  access_key                  = "test"
  secret_key                  = "test"
  region                      = "us-east-1"
  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    ec2 = "http://localhost:4566"
    s3  = "http://localhost:4566"
  }
}
```

**Comment by patsevanton** [comment]
Thanks!
