### ISSUE TITLE
bug: botocore.errorfactory.NoSuchKey: When get index.html after create static s3 website

### ISSUE THREAD

**Issue by patsevanton** [localstack/localstack#5579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Open in browser
```
http://mypublicbucket.s3-website.localhost.localstack.cloud:4566/
```

Output in browser:
```
{}
```

Log in docker localstack
```
localstack_main  | 2022-02-26T07:47:28.695:DEBUG:localstack.services.edge: IN(s3): "GET /" - headers: {'Remote-Addr': '172.17.0.1', 'Host': 'mypublicbucket.s3-website.localhost.localstack.cloud:4566', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7', 'Cookie': '_ga=GA1.2.1301292805.1643956631', 'X-Forwarded-For': '172.17.0.1, mypublicbucket.s3-website.localhost.localstack.cloud:4566', 'x-localstack-edge': 'http://mypublicbucket.s3-website.localhost.localstack.cloud:4566'} - data: b''
localstack_main  | 2022-02-26T07:47:28.927:INFO:localstack.utils.threads: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7f571bff5c10>(None) failed: Parameter validation failed:
localstack_main  | Invalid length for parameter Key, value: 0, valid min length: 1 Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1627, in serve_static_website
localstack_main  |     return respond_with_key(status_code=200, key=index_document)
localstack_main  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1600, in respond_with_key
localstack_main  |     obj = s3_client.get_object(Bucket=bucket_name, Key=key)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 395, in _api_call
localstack_main  |     return self._make_api_call(operation_name, kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 725, in _make_api_call
localstack_main  |     raise error_class(parsed_response, operation_name)
localstack_main  | botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
localstack_main  |
localstack_main  | During handling of the above exception, another exception occurred:
localstack_main  |
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
localstack_main  |     result = self.func(self.params, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 32, in _run
localstack_main  |     return fn(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 966, in handler
localstack_main  |     response = modify_and_forward(
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 512, in wrapper
localstack_main  |     value = func(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 592, in modify_and_forward
localstack_main  |     listener_result = listener.forward_request(
localstack_main  |   File "/opt/code/localstack/localstack/services/edge.py", line 177, in forward_request
localstack_main  |     result = do_forward_request(api, method, path, data, headers, port=port)
localstack_main  |   File "/opt/code/localstack/localstack/services/edge.py", line 232, in do_forward_request
localstack_main  |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_main  |   File "/opt/code/localstack/localstack/services/edge.py", line 256, in do_forward_request_inmem
localstack_main  |     response = modify_and_forward(
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 512, in wrapper
localstack_main  |     value = func(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 592, in modify_and_forward
localstack_main  |     listener_result = listener.forward_request(
localstack_main  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1258, in forward_request
localstack_main  |     return serve_static_website(headers=headers, path=path, bucket_name=bucket_name)
localstack_main  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1631, in serve_static_website
localstack_main  |     return respond_with_key(status_code=404, key=error_document)
localstack_main  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1600, in respond_with_key
localstack_main  |     obj = s3_client.get_object(Bucket=bucket_name, Key=key)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 395, in _api_call
localstack_main  |     return self._make_api_call(operation_name, kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 695, in _make_api_call
localstack_main  |     request_dict = self._convert_to_request_dict(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 745, in _convert_to_request_dict
localstack_main  |     request_dict = self._serializer.serialize_to_request(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/validate.py", line 360, in serialize_to_request
localstack_main  |     raise ParamValidationError(report=report.generate_report())
localstack_main  | botocore.exceptions.ParamValidationError: Parameter validation failed:
localstack_main  | Invalid length for parameter Key, value: 0, valid min length: 1
localstack_main  |
localstack_main  | 2022-02-26T07:47:28.927:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request GET http://mypublicbucket.s3-website.localhost.localstack.cloud:4566/: Parameter validation failed:
localstack_main  | Invalid length for parameter Key, value: 0, valid min length: 1 Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1627, in serve_static_website
localstack_main  |     return respond_with_key(status_code=200, key=index_document)
localstack_main  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1600, in respond_with_key
localstack_main  |     obj = s3_client.get_object(Bucket=bucket_name, Key=key)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 395, in _api_call
localstack_main  |     return self._make_api_call(operation_name, kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 725, in _make_api_call
localstack_main  |     raise error_class(parsed_response, operation_name)
localstack_main  | botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
localstack_main  |
localstack_main  | During handling of the above exception, another exception occurred:
localstack_main  |
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 159, in index
localstack_main  |     result = await run_sync(handler, request, data)
localstack_main  |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 87, in run_sync
localstack_main  |     return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
localstack_main  |   File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
localstack_main  |     result = self.func(self.params, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 32, in _run
localstack_main  |     return fn(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 966, in handler
localstack_main  |     response = modify_and_forward(
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 512, in wrapper
localstack_main  |     value = func(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 592, in modify_and_forward
localstack_main  |     listener_result = listener.forward_request(
localstack_main  |   File "/opt/code/localstack/localstack/services/edge.py", line 177, in forward_request
localstack_main  |     result = do_forward_request(api, method, path, data, headers, port=port)
localstack_main  |   File "/opt/code/localstack/localstack/services/edge.py", line 232, in do_forward_request
localstack_main  |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack_main  |   File "/opt/code/localstack/localstack/services/edge.py", line 256, in do_forward_request_inmem
localstack_main  |     response = modify_and_forward(
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 512, in wrapper
localstack_main  |     value = func(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 592, in modify_and_forward
localstack_main  |     listener_result = listener.forward_request(
localstack_main  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1258, in forward_request
localstack_main  |     return serve_static_website(headers=headers, path=path, bucket_name=bucket_name)
localstack_main  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1631, in serve_static_website
localstack_main  |     return respond_with_key(status_code=404, key=error_document)
localstack_main  |   File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1600, in respond_with_key
localstack_main  |     obj = s3_client.get_object(Bucket=bucket_name, Key=key)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 395, in _api_call
localstack_main  |     return self._make_api_call(operation_name, kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 695, in _make_api_call
localstack_main  |     request_dict = self._convert_to_request_dict(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 745, in _convert_to_request_dict
localstack_main  |     request_dict = self._serializer.serialize_to_request(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/validate.py", line 360, in serialize_to_request
localstack_main  |     raise ParamValidationError(report=report.generate_report())
localstack_main  | botocore.exceptions.ParamValidationError: Parameter validation failed:
localstack_main  | Invalid length for parameter Key, value: 0, valid min length: 1
localstack_main  |
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose:
```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "53:53"                # only required for Pro (DNS)
      - "53:53/udp"            # only required for Pro (DNS)
      - "127.0.0.1:443:443"              # only required for Pro (LocalStack HTTPS Edge Proxy)
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - SERVICES=${SERVICES-}
      - DEBUG=1
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LS_LOG=trace
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Version localstack
```
localstack_main  | LocalStack version: 0.14.0
localstack_main  | LocalStack Docker container id: b461402e240e
localstack_main  | LocalStack build date: 2022-02-26
localstack_main  | LocalStack build git hash: 5379cbfd
```

Install awslocal
```
pip3 install awscli-local[ver1]
```

Create a new AWS S3 Bucket
```
awslocal s3 mb s3://mypublicbucket
```

## Make an S3 Bucket Permissions Public Access to 'Everyone' using CLI
```
awslocal s3api put-bucket-acl --bucket mypublicbucket --acl public-read
```

## Synchronize between AWS S3 and Local Directory with Permissions Public Access
```
awslocal s3 sync . s3://mypublicbucket --acl public-read
```
Output:
```
upload: ./main.tf to s3://mypublicbucket/main.tf
upload: ./index.html to s3://mypublicbucket/index.html
upload: ./error.html to s3://mypublicbucket/error.html
upload: ./readme.md to s3://mypublicbucket/readme.md
upload: ./provider.tf to s3://mypublicbucket/provider.tf
```

Check IndexDocument and ErrorDocument
```
awslocal s3api get-bucket-website --bucket mypublicbucket
```
Output:
```json
{
    "IndexDocument": {
        "Suffix": "index.html"
    }
}
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```

**Comment by pinzon** [comment]
The solution of this issue has been merge. Thank you for reporting the problem.
