### ISSUE TITLE
bug: Support Load Balancer

### ISSUE THREAD

**Issue by patsevanton** [localstack/localstack#5586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello! Thanks for the localstack.

I don't find Load Balancer in https://docs.localstack.cloud/aws/feature-coverage/

I try to create a Load Balancer

But get the error:
```
localstack_main  | 2022-02-28T15:18:21.568:DEBUG:localstack.services.edge: IN(ec2): "POST /" - headers: {'Remote-Addr': '172.17.0.1', 'Host': 'localhost:4566', 'Accept-Encoding': 'identity', 'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'aws-cli/1.22.54 Python/3.8.10 Linux/5.10.60.1-microsoft-standard-WSL2 botocore/1.23.54', 'X-Amz-Date': '20220228T151821Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=test/20220228/us-east-1/ec2/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=712873ddc4b028da59b1b0fb60a7aa1ed578cb548b01ec351d2be803b166ac24', 'Amz-Sdk-Invocation-Id': '49b1b108-b7a3-4760-bc95-f5b046e4a195', 'Amz-Sdk-Request': 'attempt=1', 'Content-Length': '41', 'X-Forwarded-For': '172.17.0.1, localhost:4566', 'x-localstack-edge': 'http://localhost:4566'} - data: b'Action=DescribeSubnets&Version=2016-11-15'
localstack_main  | 2022-02-28T15:18:21.568:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.aws.provider.ec2:default = <function ec2 at 0x7ff4d341f280>)
localstack_main  | 2022-02-28T15:18:21.568:DEBUG:plugin.manager: loading plugin localstack.aws.provider:ec2:default
localstack_main  | 2022-02-28T15:18:21.943:INFO:localstack.services.infra: Starting mock EC2 service on http port 4566 ...
localstack_main  | 2022-02-28T15:18:21.943:INFO:localstack.services.motoserver: starting moto server on http://0.0.0.0:57595
localstack_main  | 2022-02-28T15:18:21.944:DEBUG:localstack.services.plugins: checking service health ec2:57595
localstack_main  | 2022-02-28T15:18:21.963:DEBUG:localstack.services.edge: OUT(ec2): "POST /" - status: 200 - response headers: {'server': 'amazon.com', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '3792', 'Access-Control-Allow-Origin': '*', 'Date': 'Mon, 28 Feb 2022 15:18:21 GMT', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'etag,x-amz-version-id'} - response: <DescribeSubnetsResponse xmlns="http://ec2.amazonaws.com/doc/2013-10-15/"><requestId>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</requestId><subnetSet><item><subnetId>subnet-de3dbdc6</subnetId><state>available</state><vpcId>vpc-845dba26</vpcId><cidrBlock>172.31.0.0/20</cidrBlock><availableIpAddressCount>4091</availableIpAddressCount><availabilityZone>us-east-1a</availabilityZone><availabilityZoneId>use1-az6</availabilityZoneId><defaultForAz>true</defaultForAz><mapPublicIpOnLaunch>true</mapPublicIpOnLaunch><ownerId>000000000000</ownerId><assignIpv6AddressOnCreation>false</assignIpv6AddressOnCreation><ipv6CidrBlockAssociationSet></ipv6CidrBlockAssociationSet><subnetArn>arn:aws:ec2:us-east-1:000000000000:subnet/subnet-de3dbdc6</subnetArn></item><item><subnetId>subnet-e71fcba0</subnetId><state>available</state><vpcId>vpc-845dba26</vpcId><cidrBlock>172.31.16.0/20</cidrBlock><availableIpAddressCount>4091</availableIpAddressCount><availabilityZone>us-east-1b</availabilityZone><availabilityZoneId>use1-az1</availabilityZoneId><defaultForAz>true</defaultForAz><mapPublicIpOnLaunch>true</mapPublicIpOnLaunch><ownerId>000000000000</ownerId><assignIpv6AddressOnCreation>false</assignIpv6AddressOnCreation><ipv6CidrBlockAssociationSet></ipv6CidrBlockAssociationSet><subnetArn>arn:aws:ec2:us-east-1:000000000000:subnet/subnet-e71fcba0</subnetArn></item><item><subnetId>subnet-d595ccb0</subnetId><state>available</state><vpcId>vpc-845dba26</vpcId><cidrBlock>172.31.32.0/20</cidrBlock><availableIpAddressCount>4091</availableIpAddressCount><availabilityZone>us-east-1c</availabilityZone><availabilityZoneId>use1-az2</availabilityZoneId><defaultForAz>true</defaultForAz><mapPublicIpOnLaunch>true</mapPublicIpOnLaunch><ownerId>000000000000</ownerId><assignIpv6AddressOnCreation>false</assignIpv6AddressOnCreation><ipv6CidrBlockAssociationSet></ipv6CidrBlockAssociationSet><subnetArn>arn:aws:ec2:us-east-1:000000000000:subnet/subnet-d595ccb0</subnetArn></item><item><subnetId>subnet-9d8d3c64</subnetId><state>available</state><vpcId>vpc-845dba26</vpcId><cidrBlock>172.31.48.0/20</cidrBlock><availableIpAddressCount>4091</availableIpAddressCount><availabilityZone>us-east-1d</availabilityZone><availabilityZoneId>use1-az4</availabilityZoneId><defaultForAz>true</defaultForAz><mapPublicIpOnLaunch>true</mapPublicIpOnLaunch><ownerId>000000000000</ownerId><assignIpv6AddressOnCreation>false</assignIpv6AddressOnCreation><ipv6CidrBlockAssociationSet></ipv6CidrBlockAssociationSet><subnetArn>arn:aws:ec2:us-east-1:000000000000:subnet/subnet-9d8d3c64</subnetArn></item><item><subnetId>subnet-418c6371</subnetId><state>available</state><vpcId>vpc-845dba26</vpcId><cidrBlock>172.31.64.0/20</cidrBlock><availableIpAddressCount>4091</availableIpAddressCount><availabilityZone>us-east-1e</availabilityZone><availabilityZoneId>use1-az3</availabilityZoneId><defaultForAz>true</defaultForAz><mapPublicIpOnLaunch>true</mapPublicIpOnLaunch><ownerId>000000000000</ownerId><assignIpv6AddressOnCreation>false</assignIpv6AddressOnCreation><ipv6CidrBlockAssociationSet></ipv6CidrBlockAssociationSet><subnetArn>arn:aws:ec2:us-east-1:000000000000:subnet/subnet-418c6371</subnetArn></item><item><subnetId>subnet-21a268a0</subnetId><state>available</state><vpcId>vpc-845dba26</vpcId><cidrBlock>172.31.80.0/20</cidrBlock><availableIpAddressCount>4091</availableIpAddressCount><availabilityZone>us-east-1f</availabilityZone><availabilityZoneId>use1-az5</availabilityZoneId><defaultForAz>true</defaultForAz><mapPublicIpOnLaunch>true</mapPublicIpOnLaunch><ownerId>000000000000</ownerId><assignIpv6AddressOnCreation>false</assignIpv6AddressOnCreation><ipv6CidrBlockAssociationSet></ipv6CidrBlockAssociationSet><subnetArn>arn:aws:ec2:us-east-1:000000000000:subnet/subnet-21a268a0</subnetArn></item></subnetSet></DescribeSubnetsResponse>
localstack_main  | 2022-02-28T15:18:21.963:DEBUG:localstack.services.edge: OUT(ec2): "POST /" - status: 200 - response headers: {'server': 'amazon.com', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '3792', 'Access-Control-Allow-Origin': '*', 'Date': 'Mon, 28 Feb 2022 15:18:21 GMT', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'etag,x-amz-version-id'} - response: <DescribeSubnetsResponse xmlns="http://ec2.amazonaws.com/doc/2013-10-15/"><requestId>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</requestId><subnetSet><item><subnetId>subnet-de3dbdc6</subnetId><state>available</state><vpcId>vpc-845dba26</vpcId><cidrBlock>172.31.0.0/20</cidrBlock><availableIpAddressCount>4091</availableIpAddressCount><availabilityZone>us-east-1a</availabilityZone><availabilityZoneId>use1-az6</availabilityZoneId><defaultForAz>true</defaultForAz><mapPublicIpOnLaunch>true</mapPublicIpOnLaunch><ownerId>000000000000</ownerId><assignIpv6AddressOnCreation>false</assignIpv6AddressOnCreation><ipv6CidrBlockAssociationSet></ipv6CidrBlockAssociationSet><subnetArn>arn:aws:ec2:us-east-1:000000000000:subnet/subnet-de3dbdc6</subnetArn></item><item><subnetId>subnet-e71fcba0</subnetId><state>available</state><vpcId>vpc-845dba26</vpcId><cidrBlock>172.31.16.0/20</cidrBlock><availableIpAddressCount>4091</availableIpAddressCount><availabilityZone>us-east-1b</availabilityZone><availabilityZoneId>use1-az1</availabilityZoneId><defaultForAz>true</defaultForAz><mapPublicIpOnLaunch>true</mapPublicIpOnLaunch><ownerId>000000000000</ownerId><assignIpv6AddressOnCreation>false</assignIpv6AddressOnCreation><ipv6CidrBlockAssociationSet></ipv6CidrBlockAssociationSet><subnetArn>arn:aws:ec2:us-east-1:000000000000:subnet/subnet-e71fcba0</subnetArn></item><item><subnetId>subnet-d595ccb0</subnetId><state>available</state><vpcId>vpc-845dba26</vpcId><cidrBlock>172.31.32.0/20</cidrBlock><availableIpAddressCount>4091</availableIpAddressCount><availabilityZone>us-east-1c</availabilityZone><availabilityZoneId>use1-az2</availabilityZoneId><defaultForAz>true</defaultForAz><mapPublicIpOnLaunch>true</mapPublicIpOnLaunch><ownerId>000000000000</ownerId><assignIpv6AddressOnCreation>false</assignIpv6AddressOnCreation><ipv6CidrBlockAssociationSet></ipv6CidrBlockAssociationSet><subnetArn>arn:aws:ec2:us-east-1:000000000000:subnet/subnet-d595ccb0</subnetArn></item><item><subnetId>subnet-9d8d3c64</subnetId><state>available</state><vpcId>vpc-845dba26</vpcId><cidrBlock>172.31.48.0/20</cidrBlock><availableIpAddressCount>4091</availableIpAddressCount><availabilityZone>us-east-1d</availabilityZone><availabilityZoneId>use1-az4</availabilityZoneId><defaultForAz>true</defaultForAz><mapPublicIpOnLaunch>true</mapPublicIpOnLaunch><ownerId>000000000000</ownerId><assignIpv6AddressOnCreation>false</assignIpv6AddressOnCreation><ipv6CidrBlockAssociationSet></ipv6CidrBlockAssociationSet><subnetArn>arn:aws:ec2:us-east-1:000000000000:subnet/subnet-9d8d3c64</subnetArn></item><item><subnetId>subnet-418c6371</subnetId><state>available</state><vpcId>vpc-845dba26</vpcId><cidrBlock>172.31.64.0/20</cidrBlock><availableIpAddressCount>4091</availableIpAddressCount><availabilityZone>us-east-1e</availabilityZone><availabilityZoneId>use1-az3</availabilityZoneId><defaultForAz>true</defaultForAz><mapPublicIpOnLaunch>true</mapPublicIpOnLaunch><ownerId>000000000000</ownerId><assignIpv6AddressOnCreation>false</assignIpv6AddressOnCreation><ipv6CidrBlockAssociationSet></ipv6CidrBlockAssociationSet><subnetArn>arn:aws:ec2:us-east-1:000000000000:subnet/subnet-418c6371</subnetArn></item><item><subnetId>subnet-21a268a0</subnetId><state>available</state><vpcId>vpc-845dba26</vpcId><cidrBlock>172.31.80.0/20</cidrBlock><availableIpAddressCount>4091</availableIpAddressCount><availabilityZone>us-east-1f</availabilityZone><availabilityZoneId>use1-az5</availabilityZoneId><defaultForAz>true</defaultForAz><mapPublicIpOnLaunch>true</mapPublicIpOnLaunch><ownerId>000000000000</ownerId><assignIpv6AddressOnCreation>false</assignIpv6AddressOnCreation><ipv6CidrBlockAssociationSet></ipv6CidrBlockAssociationSet><subnetArn>arn:aws:ec2:us-east-1:000000000000:subnet/subnet-21a268a0</subnetArn></item></subnetSet></DescribeSubnetsResponse>
localstack_main  | 2022-02-28T15:18:39.536:DEBUG:localstack.services.edge: IN(elasticloadbalancing): "POST /" - headers: {'Remote-Addr': '172.17.0.1', 'Host': 'localhost:4566', 'Accept-Encoding': 'identity', 'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'aws-cli/1.22.54 Python/3.8.10 Linux/5.10.60.1-microsoft-standard-WSL2 botocore/1.23.54', 'X-Amz-Date': '20220228T151839Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=test/20220228/us-east-1/elasticloadbalancing/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=6d1f987336bf3672c761cea2e77f706a1011ae7943681311f6c74d592f1833f0', 'Amz-Sdk-Invocation-Id': '7c9d5122-4663-4562-ae55-a7c7a374edda', 'Amz-Sdk-Request': 'attempt=1', 'Content-Length': '99', 'X-Forwarded-For': '172.17.0.1, localhost:4566', 'x-localstack-edge': 'http://localhost:4566'} - data: b'Action=CreateLoadBalancer&Version=2015-12-01&Name=my-load-balancer&Subnets.member.1=subnet-de3dbdc6'
localstack_main  | 2022-02-28T15:18:39.538:INFO:localstack.utils.threads: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7ff4d0e5ce50>(None) failed: no provider exists for service elasticloadbalancing Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
localstack_main  |     result = self.func(self.params, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 32, in _run
localstack_main  |     return fn(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 966, in handler
localstack_main  |     response = modify_and_forward(
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 512, in wrapper
localstack_main  |     value = func(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 592, in modify_and_forward
localstack_main  |     listener_result = listener.forward_request(
localstack_main  |   File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request
localstack_main  |     self._require_service(api)
localstack_main  |   File "/opt/code/localstack/localstack/services/edge.py", line 222, in _require_service
localstack_main  |     raise HTTPErrorResponse("no provider exists for service %s" % api, code=500)
localstack_main  | localstack.utils.server.http2_server.HTTPErrorResponse: no provider exists for service elasticloadbalancing
localstack_main  |
localstack_main  | 2022-02-28T15:18:39.538:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: no provider exists for service elasticloadbalancing Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 159, in index
localstack_main  |     result = await run_sync(handler, request, data)
localstack_main  |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 87, in run_sync
localstack_main  |     return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
localstack_main  |   File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
localstack_main  |     result = self.func(self.params, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 32, in _run
localstack_main  |     return fn(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 966, in handler
localstack_main  |     response = modify_and_forward(
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 512, in wrapper
localstack_main  |     value = func(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 592, in modify_and_forward
localstack_main  |     listener_result = listener.forward_request(
localstack_main  |   File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request
localstack_main  |     self._require_service(api)
localstack_main  |   File "/opt/code/localstack/localstack/services/edge.py", line 222, in _require_service
localstack_main  |     raise HTTPErrorResponse("no provider exists for service %s" % api, code=500)
localstack_main  | localstack.utils.server.http2_server.HTTPErrorResponse: no provider exists for service elasticloadbalancing
```

### Expected Behavior

Do localstack have plan for Support Load Balancer ?

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```
awslocal ec2 describe-subnets  --query "Subnets[*].SubnetId" --output text
```

```
awslocal elbv2 create-load-balancer --name my-load-balancer --subnets subnet-de3dbdc6
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest

localstack_main  | LocalStack version: 0.14.0
localstack_main  | LocalStack Docker container id: 5ba6a3f8b746
localstack_main  | LocalStack build date: 2022-02-28
localstack_main  | LocalStack build git hash: 57954f72
```

**Comment by patsevanton** [comment]
Same feature https://github.com/localstack/localstack/issues/25

**Comment by patsevanton** [comment]
Close by https://github.com/localstack/localstack/issues/25
