### ISSUE TITLE
Exception in thread "main" com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain

### ISSUE THREAD

**Issue by dingwen150** [localstack/localstack#559]
in the lambda function, there is logic of sending message to sqs, but got following exceptions.

```
 (return_code, log_output))
localstack_1  | Exception: Lambda process returned error status code: 1. Output:
localstack_1  | Exception in thread "main" com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
localstack_1  | 	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
localstack_1  | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1119)
localstack_1  | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:759)
localstack_1  | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:723)
localstack_1  | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
localstack_1  | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
localstack_1  | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
localstack_1  | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
localstack_1  | 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
localstack_1  | 	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2013)
localstack_1  | 	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1989)
localstack_1  | 	at com.amazonaws.services.sqs.AmazonSQSClient.executeGetQueueUrl(AmazonSQSClient.java:1075)
localstack_1  | 	at com.amazonaws.services.sqs.AmazonSQSClient.getQueueUrl(AmazonSQSClient.java:1052)
localstack_1  | 	at com.amazonaws.services.sqs.AmazonSQSClient.getQueueUrl(AmazonSQSClient.java:1087)
localstack_1  | 	at example.HelloWorld.handleRequest(HelloWorld.java:35)
localstack_1  | 	at example.HelloWorld.handleRequest(HelloWorld.java:19)
localstack_1  | 	at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:110)
```

the lambda java code is following:
```java
public Object handleRequest(DynamodbEvent input, Context context) {
    AmazonSQS amazonSQS = AmazonSQSClientBuilder.standard().withEndpointConfiguration(
        new AwsClientBuilder.EndpointConfiguration("http://localhost:4576",
            "us-west-2")).build();
    String queueUrl = null;
    for (DynamodbEvent.DynamodbStreamRecord record : input.getRecords()) {
      System.out.println(record.getEventID());
      System.out.println(record.getEventName());
      System.out.println(record.getDynamodb().toString());
      Map<String, AttributeValue> values = record.getDynamodb().getNewImage();
      queueUrl = amazonSQS.getQueueUrl("Verification").getQueueUrl();
      amazonSQS.sendMessage(new SendMessageRequest(queueUrl, "gogogo"));
    }
    return queueUrl;
  }
```

**Comment by Matt-st** [comment]
@dingwen150 Did you ever find a solution here?

**Comment by Thijsvandepoll** [comment]
I am having a similar issue with pyspark reading a csv file from a (fake) bucket on localstack. Did anyone find a solution to this?

**Comment by dingwenxiao** [comment]
@Matt-st @Thijsvandepoll it was resolved in latest image.
