### ISSUE TITLE
bug: lambda fails to deploy when using lambda layers

### ISSUE THREAD

**Issue by paulrobello** [localstack/localstack#5593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using Pulumi typescript to create simple python lambda with its dependencies in a layer. Build fails with lambda unable to find dependencies. 

**Pulumi Log**
```
Updating (portal.local):
     Type                             Name                           Status                  Info
 +   pulumi:pulumi:Stack              lambda-layer-bug-portal.local  **creating failed**     1 error
 +   ├─ pulumi:providers:aws          localstack                     created
 +   ├─ aws:iam:Role                  lambdaRole                     created
 +   ├─ aws:iam:Policy                lambdaLoggingPolicy            created
 +   ├─ aws:lambda:LayerVersion       lambdaDeps                     created
 +   ├─ aws:iam:RolePolicyAttachment  lambdaLoggingRoleAttachment    created
 +   └─ aws:lambda:Function           uploadLambda                   **creating failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (lambda-layer-bug-portal.local):
    error: update failed

  aws:lambda:Function (uploadLambda):
    error: 1 error occurred:
        * error creating Lambda Function (1): InternalFailure:
        status code: 400, request id:

Resources:
    + 6 created

Duration: 8s
```

**Localstack Log**
```
2022-03-01T20:57:55.317:INFO:localstack.services.infra: Starting mock EC2 service on http ports 443/4566 ...
2022-03-01T20:57:55.318:DEBUG:localstack.services.plugins: checking service health ec2:39181
2022-03-01T20:57:55.756:INFO:botocore.credentials: Found credentials in environment variables.
2022-03-01T20:58:12.602:DEBUG:localstack.utils.run: Executing command: cd /tmp/localstack/zipfile.cdf66b9c; unzip -o -q /tmp/localstack/zipfile.cdf66b9c/original_lambda_archive.zip
2022-03-01T20:58:12.610:ERROR:localstack.services.awslambda.lambda_api: Unable to exec: b'import json\r\nfrom dynamodb_json import json_util as dynamo_json\r\n\r\ndef lambda_handler(event, context):\r\n    print(json.dumps(event))\r\n\r\n' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 853, in _do_exec_lambda_code
    handler_module = load_source(lambda_id, lambda_file)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 825, in load_source
    return importlib.machinery.SourceFileLoader(name, file).load_module()
  File "<frozen importlib._bootstrap_external>", line 522, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1022, in load_module
  File "<frozen importlib._bootstrap_external>", line 847, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/localstack/lambda_script_l_b51a6b3b.py", line 2, in <module>
    from dynamodb_json import json_util as dynamo_json
ModuleNotFoundError: No module named 'dynamodb_json'

2022-03-01T20:58:13.091:DEBUG:localstack.services.awslambda.lambda_utils: Unable to get handler function from lambda code: No module named 'dynamodb_json'
```

### Expected Behavior

Lambda to deploy along with its layer and function

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up -d

Created repo to showcase bug:

[https://github.com/paulrobello/localstack-lambda-layer-bug](https://github.com/paulrobello/localstack-lambda-layer-bug)

### Environment

```markdown
- OS: OSX and Windows 11
- LocalStack: latest
```

### Anything else?

Confirmed it was working in with localstack docker version 0.14.0 but fails with latest.

**Comment by rshedzer** [comment]
I'm having this exact issue, you can verify it using the AWS CDK [example](https://github.com/aws-samples/aws-cdk-examples/tree/master/python/lambda-layer).
I'm using Pro, on version 0.14.0, run from the cli rather than docker.

**Comment by paulrobello** [comment]
> I'm having this exact issue, you can verify it using the AWS CDK [example](https://github.com/aws-samples/aws-cdk-examples/tree/master/python/lambda-layer). I'm using Pro, on version 0.14.0, run from the cli rather than docker.

I am using localstack pro as well, but I have never messed with aws cdk before. Mine is a house of Pulumi ;) let me see what it will take to get the cdk samples up and running,

**Comment by paulrobello** [comment]
Confirmed aws cdk lambda layer example fails to deploy using latest localstack docker image.

**Comment by whummer** [comment]
Thanks for reporting @paulrobello @rshedzer . Can you please confirm if you can run this sequence of commands (minimum working example for MacOS/Linux):
```
mkdir -p /tmp/python/
echo 'def util():' > /tmp/python/testlayer.py
echo '  print("Output from Lambda layer util function")' >> /tmp/python/testlayer.py
(cd /tmp; zip -r testlayer.zip python)
awslocal lambda publish-layer-version --layer-name layer1 --zip-file fileb:///tmp/testlayer.zip
echo 'def handler(*args, **kwargs):' > /tmp/testlambda.py
echo '  import testlayer; testlayer.util()' >> /tmp/testlambda.py
echo '  print("Debug output from Lambda function")' >> /tmp/testlambda.py
(cd /tmp; zip testlambda.zip testlambda.py)
awslocal lambda create-function --function-name func1 --runtime python3.6 --role r1 --handler testlambda.handler --timeout 30 --zip-file fileb:///tmp/testlambda.zip --layers arn:aws:lambda:$AWS_DEFAULT_REGION:000000000000:layer:layer1
funcArn=$(awslocal lambda get-function --function-name func1 | jq -r .Configuration.FunctionArn)
awslocal lambda invoke --function-name func1 /tmp/tmp.out
```
If all goes well, the last command should output something like: 
```
{
    "StatusCode": 200,
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
```
... and the LocalStack output (with `DEBUG=1` enabled) should contain something like:
```
>START RequestId: 98780a53-c235-1bce-f27d-ec31d2682802 Version: $LATEST
> Output from Lambda layer util function
> Debug output from Lambda function
> END RequestId: 98780a53-c235-1bce-f27d-ec31d2682802
```

Are you able to replicate these results? If not, then please share the detailed startup configuration and container logs here with us. Thanks!

**Comment by paulrobello** [comment]
**command failed:** 
```
awslocal lambda create-function --function-name func1 --runtime python3.6 --role r1 --handler testlambda.handler --timeout 30 --zip-file fileb:///tmp/testlambda.zip --layers arn:aws:lambda:$AWS_DEFAULT_REGION:000000000000:layer:layer1

An error occurred (InternalFailure) when calling the CreateFunction operation (reached max retries: 2): Unknown error: Unable to find code for Lambda function ARN arn:aws:lambda::000000000000:layer:layer1 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1392, in create_function
    result = set_function_code(lambda_function)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 970, in set_function_code
    run_for_max_seconds(config.LAMBDA_CODE_EXTRACT_TIME, _set_and_configure)
  File "/opt/code/localstack/localstack/utils/run.py", line 146, in run_for_max_seconds
    raise result
  File "/opt/code/localstack/localstack/utils/run.py", line 127, in _worker
    fn_result = _function(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 967, in _set_and_configure
    plugin.init_function_code(lambda_function)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 89, in init_function_code
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 269, in copy_function_code
Exception: Unable to find code for Lambda function ARN arn:aws:lambda::000000000000:layer:layer1
```
```
2022-03-03T04:58:18.490:DEBUG:localstack.utils.run: Executing command: cd /tmp/localstack/zipfile.dc63c938; unzip -o -q /tmp/localstack/zipfile.dc63c938/original_lambda_archive.zip
2022-03-03T04:58:18.501:DEBUG:localstack_ext.services.awslambda.lambda_extended: Copy function code layer arn:aws:lambda::000000000000:layer:layer1 to /tmp/localstack/lambda-with-layers.21ea2cf6/__layers__
2022-03-03T04:58:18.502:WARNING:localstack_ext.services.awslambda.lambda_extended: Unable to find Lambda function arn:aws:lambda::000000000000:layer:layer1 in ['arn:aws:lambda:us-east-1:000000000000:layer:layer1', 'arn:aws:lambda:us-east-1:000000000000:function:func1']
2022-03-03T04:58:18.959:DEBUG:localstack.services.awslambda.lambda_utils: Unknown error: Unable to find code for Lambda function ARN arn:aws:lambda::000000000000:layer:layer1 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1392, in create_function
    result = set_function_code(lambda_function)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 970, in set_function_code
    run_for_max_seconds(config.LAMBDA_CODE_EXTRACT_TIME, _set_and_configure)
  File "/opt/code/localstack/localstack/utils/run.py", line 146, in run_for_max_seconds
    raise result
  File "/opt/code/localstack/localstack/utils/run.py", line 127, in _worker
    fn_result = _function(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 967, in _set_and_configure
    plugin.init_function_code(lambda_function)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 89, in init_function_code
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 269, in copy_function_code
Exception: Unable to find code for Lambda function ARN arn:aws:lambda::000000000000:layer:layer1
```

**Comment by paulrobello** [comment]
Any updates on this? This is a pretty big blocker on my stack testing since I need the CloudFront Fixes in latest, but also need lambda layers which is now broken.

**Comment by inverseProton** [comment]
I am having this issue as well.

**Comment by whummer** [comment]
Hi @paulrobello  @rshedzer , apologies for the long delay on this one. We have pushed a number of enhancements for Lambda layer handling (also in combination with persistence, in case you have `DATA_DIR` enabled). Can you please let us know if the problem is resolved with the `latest` image? 

Please note that in the latest version you'll also need to specify the specific version in the Lambda layer ARN (e.g., `arn:aws:lambda::000000000000:layer:layer1:1`), which is in line with the behavior on AWS. Please keep us posted on how it goes, thanks!

**Comment by paulrobello** [comment]
Confirmed working on latest

**Comment by magzim21** [comment]
I've realized that it does not work because it simply a PRO feature.
