### ISSUE TITLE
bug: Can't interface with Cloudpods using the localstack client

### ISSUE THREAD

**Issue by Tobolov** [localstack/localstack#5629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to list available cloudpods or push to an existing cloudpod both fail.

localstack pod list:
```
error during PodConfigManager call chain
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/bootstrap/pods_client.py", line 642, in _call
    tmp=getattr(manager,attr)(*args,**kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/bootstrap/pods_client.py", line 690, in list_pods
    remote_pods=json.loads(to_str(content)).get("cloudpods",[])
AttributeError: 'list' object has no attribute 'get'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                                                                                  │
│ /home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/cli/localstack.py:260 in          │
│ cmd_pod_list                                                                                     │
│                                                                                                  │
│   257  from localstack.utils.common import format_bytes                                          │
│   258  from localstack_ext.bootstrap import pods_client                                          │
│   259  try:                                                                                      │
│ ❱ 260   result=pods_client.list_pods(None)                                                       │
│   261   status.stop()                                                                            │
│   262   columns={"pod_name":"Name","backend":"Backend","url":"URL","size":"Size","state":"Stat   │
│   263   print_table(columns,result,formatters={"size":format_bytes})                             │
│ /home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/bootstrap/pods_client.py:786 in   │
│ list_pods                                                                                        │
│                                                                                                  │
│   783   raise Exception("Unable to reset service state via local management API %s (code %s):    │
│   784  print("Done.")                                                                            │
│   785 def list_pods(args):                                                                       │
│ ❱ 786  return PodConfigManager.list_pods()                                                       │
│   787 def get_data_dir_from_container()->str:                                                    │
│   788  try:                                                                                      │
│   789   details=DOCKER_CLIENT.inspect_container(config.MAIN_CONTAINER_NAME)                      │
│                                                                                                  │
│ /home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/bootstrap/pods_client.py:653 in   │
│ _call                                                                                            │
│                                                                                                  │
│   650 │     LOG.exception("error during PodConfigManager call chain")                            │
│   651    if result is not None:                                                                  │
│   652 │   return result                                                                          │
│ ❱ 653    raise Exception('Unable to run operation "%s" for local or remote configuration'%attr   │
│   654   return _call                                                                             │
│   655 class PodConfigManager(object,metaclass=PodConfigManagerMeta):                             │
│   656  CHAIN=[]                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
Exception: Unable to run operation "list_pods" for local or remote configuration
```

localstack pod push test-pod:
```
error during PodConfigManager call chain
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/bootstrap/pods_client.py", line 642, in _call
    tmp=getattr(manager,attr)(*args,**kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/bootstrap/pods_client.py", line 690, in list_pods
    remote_pods=json.loads(to_str(content)).get("cloudpods",[])
AttributeError: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/localstack", line 23, in <module>
    main()
  File "/home/ubuntu/.local/bin/localstack", line 19, in main
    main.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack/cli/main.py", line 6, in main
    cli()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/cli/localstack.py", line 278, in cmd_pod_push
    pods_client.push_state(name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/bootstrap/pods_client.py", line 758, in push_state
    backend=CloudPodManager.get(pod_name=pod_name,pre_config=pre_config)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/bootstrap/pods_client.py", line 90, in get
    pod_config=pre_config if pre_config else PodConfigManager.pod_config(pod_name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/bootstrap/pods_client.py", line 659, in pod_config
    pods=PodConfigManager.list_pods()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/bootstrap/pods_client.py", line 653, in _call
    raise Exception('Unable to run operation "%s" for local or remote configuration'%attr)
Exception: Unable to run operation "list_pods" for local or remote configuration
```

### Expected Behavior

Listing available pods and pushing pods work as documented.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

1. Run `export DATA_DIR="/tmp/localstack"`
2. Run `export LOCALSTACK_API_KEY="##########"`
3. Run `localstack login`
4. Run `localstack pod list`

### Environment

```markdown
- OS: Windows 10
- LocalStack: 
localstack               0.14.0.9
localstack-client        1.32
localstack-ext           0.14.0.24
localstack-plugin-loader 1.1.1
localstack/localstack   latest           34b112ea49a0
```

**Comment by giograno** [comment]
Hi @Tobolov, many thanks for your issue report. 
We are currently going under some restructuring of the pods CLI. We will release soon updated documentation. 
In the meanwhile, you can already try out the new version by updating to the latest version of the `ext` package (`pip install --upgrade localstack-ext`).

**Comment by Tobolov** [comment]
Hi @giograno,
I was successfully able to get `localstack pod list --remote` working after upgrading the packages.
Pushing to pods still seems to be broken.

Package versions: 
localstack               0.14.1.3
localstack-client        1.33
localstack-ext           0.14.1.9
localstack-plugin-loader 1.1.1

Commands:
1. Run `export DATA_DIR="/tmp/localstack"`
2. Run `export LOCALSTACK_API_KEY="##########"`
3. Run `localstack login`
4. Run `localstack pod push --name example-pod`


Stack trace:
```
ubuntu@ip-10-70-0-251:~$ localstack pod push --name tradingtool-common-aws
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7c4b0ea4c0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4566): Max retries exceeded with url: /_pods/state (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c4b0ea4c0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/localstack", line 23, in <module>
    main()
  File "/home/ubuntu/.local/bin/localstack", line 19, in main
    main.main()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack/cli/main.py", line 6, in main
    cli()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/cli/localstack.py", line 148, in cmd_pod_push
    result=pods_client.push_state(pod_name=name,pre_config={"backend":"cpvcs"},squash_commits=squash,comment=message,register=register)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/bootstrap/pods_client.py", line 576, in push_state
    pod_info=backend.push(comment=comment,three_way=three_way)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/bootstrap/pods_client.py", line 275, in push
    self._add_state_to_cpvcs_store(extract_assets=True)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/bootstrap/pods_client.py", line 201, in _add_state_to_cpvcs_store
    zip_file=self.get_state_zip_from_instance()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/localstack_ext/bootstrap/pods_client.py", line 115, in get_state_zip_from_instance
    result=requests.get(url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=4566): Max retries exceeded with url: /_pods/state (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c4b0ea4c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by giograno** [comment]
Hi @Tobolov, with [v.1.0.0.](https://github.com/localstack/localstack/releases/tag/v1.0.0) we deeply re-worked the Cloud Pods implementation. The experience should now be much smoother and more pleasant. I would ask you to please update to `latest` Docker image and give it another try.
We are looking forward to receiving feedback about the new version. Please note that some commands have slightly changed in the process. You can have a look at our [documentation](https://docs.localstack.cloud/tools/cloud-pods/pods-cli/).
Please feel free to re-open this ticket if you keep experiencing issues. Thanks for your patience 🙏
