### ISSUE TITLE
bug: Can't install 0.14.0.10 via pip

### ISSUE THREAD

**Issue by stevesuh** [localstack/localstack#5649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was on 0.13.3.6 and I can't seem to upgrade or install to 0.14.0.10 via pip. 

### Expected Behavior

I can upgrade or install latest version of localstack.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: OS X 12.2
- LocalStack: 0.14.0.10
```

### Anything else?

```
12:01 $ pip3 install --upgrade localstack
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: localstack in /opt/homebrew/lib/python3.9/site-packages (0.13.3.6)
Collecting localstack
  Downloading localstack-0.14.0.10-py3-none-any.whl (679 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.3/679.3 KB 15.9 MB/s eta 0:00:00
Requirement already satisfied: pyyaml>=5.1 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (6.0)
Requirement already satisfied: rich>=10.7.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (11.1.0)
Requirement already satisfied: boto3>=1.20 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (1.20.46)
Requirement already satisfied: localstack-client>=1.31 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (1.31)
Requirement already satisfied: python-dotenv>=0.19.1 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (0.19.2)
Requirement already satisfied: requests<2.26,>=2.20.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (2.25.1)
Requirement already satisfied: psutil<6.0.0,>=5.4.8 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (5.9.0)
Requirement already satisfied: stevedore>=3.4.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (3.5.0)
Requirement already satisfied: click>=7.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (8.0.3)
Requirement already satisfied: cachetools<4.0.0,>=3.1.1 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (3.1.1)
Requirement already satisfied: tailer>=0.4.1 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (0.4.1)
Requirement already satisfied: semver>=2.10 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (2.13.0)
Collecting localstack-ext>=0.14.0
  Downloading localstack-ext-0.14.0.26.tar.gz (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 31.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running egg_info
      Traceback (most recent call last):
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2473, in resolve
          return functools.reduce(getattr, self.attrs, module)
      AttributeError: module 'plugin.setuptools' has no attribute 'load_plux_entrypoints'

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 4, in <module>
          setup()
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 291, in run
          writer = ep.resolve()
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2475, in resolve
          raise ImportError(str(exc)) from exc
      ImportError: module 'plugin.setuptools' has no attribute 'load_plux_entrypoints'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I uninstalled localstack and tried from scratch but same error:
```
12:03 $ pip3 install localstack
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting localstack
  Using cached localstack-0.14.0.10-py3-none-any.whl (679 kB)
Requirement already satisfied: stevedore>=3.4.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (3.5.0)
Requirement already satisfied: boto3>=1.20 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (1.20.46)
Requirement already satisfied: tailer>=0.4.1 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (0.4.1)
Requirement already satisfied: cachetools<4.0.0,>=3.1.1 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (3.1.1)
Requirement already satisfied: pyyaml>=5.1 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (6.0)
Requirement already satisfied: click>=7.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (8.0.3)
Requirement already satisfied: psutil<6.0.0,>=5.4.8 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (5.9.0)
Requirement already satisfied: requests<2.26,>=2.20.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (2.25.1)
Requirement already satisfied: rich>=10.7.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack) (11.1.0)
Collecting localstack-ext>=0.14.0
  Using cached localstack-ext-0.14.0.26.tar.gz (1.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running egg_info
      Traceback (most recent call last):
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2473, in resolve
          return functools.reduce(getattr, self.attrs, module)
      AttributeError: module 'plugin.setuptools' has no attribute 'load_plux_entrypoints'

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 4, in <module>
          setup()
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 291, in run
          writer = ep.resolve()
        File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2475, in resolve
          raise ImportError(str(exc)) from exc
      ImportError: module 'plugin.setuptools' has no attribute 'load_plux_entrypoints'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by stevesuh** [comment]
Looks like 0.14.0 works but any of the 0.14.0.x versions do not work.

```
13:23 $ pip3 install localstack==0.14.0
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting localstack==0.14.0
  Using cached localstack-0.14.0-py3-none-any.whl (598 kB)
Requirement already satisfied: requests<2.26,>=2.20.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack==0.14.0) (2.25.1)
Requirement already satisfied: click>=7.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack==0.14.0) (8.0.3)
Requirement already satisfied: cachetools<4.0.0,>=3.1.1 in /opt/homebrew/lib/python3.9/site-packages (from localstack==0.14.0) (3.1.1)
Requirement already satisfied: localstack-ext>=0.13.3 in /opt/homebrew/lib/python3.9/site-packages (from localstack==0.14.0) (0.13.3.12)
Requirement already satisfied: localstack-plugin-loader>=0.1.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack==0.14.0) (1.1.1)
Requirement already satisfied: tailer>=0.4.1 in /opt/homebrew/lib/python3.9/site-packages (from localstack==0.14.0) (0.4.1)
Requirement already satisfied: docker==5.0.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack==0.14.0) (5.0.0)
Requirement already satisfied: python-dotenv>=0.19.1 in /opt/homebrew/lib/python3.9/site-packages (from localstack==0.14.0) (0.19.2)
Requirement already satisfied: rich>=10.7.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack==0.14.0) (11.1.0)
Requirement already satisfied: semver>=2.10 in /opt/homebrew/lib/python3.9/site-packages (from localstack==0.14.0) (2.13.0)
Requirement already satisfied: six>=1.12.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack==0.14.0) (1.16.0)
Requirement already satisfied: pyyaml>=5.1 in /opt/homebrew/lib/python3.9/site-packages (from localstack==0.14.0) (6.0)
Requirement already satisfied: boto3>=1.20 in /opt/homebrew/lib/python3.9/site-packages (from localstack==0.14.0) (1.20.46)
Requirement already satisfied: localstack-client>=1.31 in /opt/homebrew/lib/python3.9/site-packages (from localstack==0.14.0) (1.31)
Requirement already satisfied: psutil<6.0.0,>=5.4.8 in /opt/homebrew/lib/python3.9/site-packages (from localstack==0.14.0) (5.9.0)
Requirement already satisfied: stevedore>=3.4.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack==0.14.0) (3.5.0)
Requirement already satisfied: websocket-client>=0.32.0 in /opt/homebrew/lib/python3.9/site-packages (from docker==5.0.0->localstack==0.14.0) (1.2.3)
Requirement already satisfied: botocore<1.24.0,>=1.23.46 in /opt/homebrew/lib/python3.9/site-packages (from boto3>=1.20->localstack==0.14.0) (1.23.46)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/homebrew/lib/python3.9/site-packages (from boto3>=1.20->localstack==0.14.0) (0.10.0)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in /opt/homebrew/lib/python3.9/site-packages (from boto3>=1.20->localstack==0.14.0) (0.5.0)
Requirement already satisfied: dill==0.3.2 in /opt/homebrew/lib/python3.9/site-packages (from localstack-ext>=0.13.3->localstack==0.14.0) (0.3.2)
Requirement already satisfied: dnslib>=0.9.10 in /opt/homebrew/lib/python3.9/site-packages (from localstack-ext>=0.13.3->localstack==0.14.0) (0.9.19)
Requirement already satisfied: pyaes>=1.6.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack-ext>=0.13.3->localstack==0.14.0) (1.6.1)
Requirement already satisfied: tabulate in /opt/homebrew/lib/python3.9/site-packages (from localstack-ext>=0.13.3->localstack==0.14.0) (0.8.9)
Requirement already satisfied: dnspython>=1.16.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack-ext>=0.13.3->localstack==0.14.0) (2.2.0)
Requirement already satisfied: deepdiff>=5.5.0 in /opt/homebrew/lib/python3.9/site-packages (from localstack-ext>=0.13.3->localstack==0.14.0) (5.7.0)
Requirement already satisfied: dulwich>=0.19.16 in /opt/homebrew/lib/python3.9/site-packages (from localstack-ext>=0.13.3->localstack==0.14.0) (0.20.32)
Requirement already satisfied: idna<3,>=2.5 in /opt/homebrew/lib/python3.9/site-packages (from requests<2.26,>=2.20.0->localstack==0.14.0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.9/site-packages (from requests<2.26,>=2.20.0->localstack==0.14.0) (2021.10.8)
Requirement already satisfied: chardet<5,>=3.0.2 in /opt/homebrew/lib/python3.9/site-packages (from requests<2.26,>=2.20.0->localstack==0.14.0) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/homebrew/lib/python3.9/site-packages (from requests<2.26,>=2.20.0->localstack==0.14.0) (1.26.8)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /opt/homebrew/lib/python3.9/site-packages (from rich>=10.7.0->localstack==0.14.0) (2.11.2)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /opt/homebrew/lib/python3.9/site-packages (from rich>=10.7.0->localstack==0.14.0) (0.4.4)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /opt/homebrew/lib/python3.9/site-packages (from rich>=10.7.0->localstack==0.14.0) (0.9.1)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /opt/homebrew/lib/python3.9/site-packages (from stevedore>=3.4.0->localstack==0.14.0) (5.8.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/homebrew/lib/python3.9/site-packages (from botocore<1.24.0,>=1.23.46->boto3>=1.20->localstack==0.14.0) (2.8.2)
Requirement already satisfied: ordered-set==4.0.2 in /opt/homebrew/lib/python3.9/site-packages (from deepdiff>=5.5.0->localstack-ext>=0.13.3->localstack==0.14.0) (4.0.2)
Installing collected packages: localstack
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed localstack-0.14.0
```

**Comment by OryJonay** [comment]
> Hi there! Am I right in the assumption that you already installed localstack before in that environment? The `localstack-plugin-loader` was recently repackaged as `plux` (see https://github.com/localstack/plux) to make it more reusable for other projects. Sadly, the folder structure has not changed, so it might overlap with the old `localstack-plugin-loader`. Would it be possible for you to execute `pip uninstall localstack-plugin-loader`, `pip install --force-reinstall plux`, and then try installing localstack again (in its newest version?). Please report back if this solves your problem, and sorry for the inconvenience.

@dfangl Hi,

Thank you for tip to uninstall `localstack-plugin-loader` and reinstalling `plux`- I can confirm that it works as expected (although I had reinstall `localstack` with `plux` with `python3 -m pip install --force-reinstall localstack plux`) and installed and updated version of `localstack`.

Thanks again for the tip, can you please also add this as a documentation note in the README?

**Comment by dfangl** [comment]
A note is now available in the docs, located here: https://docs.localstack.cloud/get-started/#updating-localstack-using-pip-does-not-work . Thanks for your feedback and reporting this!
