### ISSUE TITLE
UnicodeDecodeError after Lambda handling

### ISSUE THREAD

**Issue by zlackbrq** [localstack/localstack#5689]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Hello,

I am new in localstack and AWS too. I created AWS Lambda handler, which is integrated with APIGateway. This handler accepts multipart/form-data, because request has to have image in it. If request has all required data in right form and right values, which refer to some data in DynamoDB, then everything is fine, lambda returns response with 200 status code. When data are not in right form, Lambda returns response with 400 status code, but still nothing crashes. But when values stated above are not valid, specifically that values refer to other items in database, which do not exist, my lambda finds that out and returns response with 404 status code and error message in JSON form (Content-Type in header is set to JSON too). After that I see in localstack logs my "Not Found" response, so i assume that lambda successfully handled request, but then there is UnicodeDecodeError, which you can see on image. When I changed status code from 404 to 200 or even 403, I didn't get that error. What am I doing wrong?

Thank you.

![image](https://user-images.githubusercontent.com/93795128/158701029-b595d6af-7897-49a5-92dc-2c51a292a9bc.png)

**Comment by calvernaz** [comment]
Hi @zlackbrq thanks for reporting this! In order to help you and understand to issue a bit better it would help if you could provide a way to reproduce the issue (aws cli command or terraform, the lambda code). Do you think you can do that?

**Comment by zlackbrq** [comment]
Hello, 

thank you for your fast answer. Yes of course, I created some small example, where it happens. Here is process how to reproduce it. All required code is stated below. First you start localstack using `docker-compose up localstack`, then you will run `bash ./test.sh`, after that it will print URL to make request to. I was creating multipart request in Postman just like on the picture below. Then you should see error in logs of localstack. If you change statusCode from 404 to 200 in lambda, then that error is not invoked. If I am missing something, tell me and i will add it here.

Thank you :).

![image](https://user-images.githubusercontent.com/93795128/159003522-f0cb5130-e6d3-4c73-a95b-d9781be4cd0c.png)


- Lambda code:

```
public class SavePostHandler implements RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {

    public APIGatewayProxyResponseEvent handleRequest(final APIGatewayProxyRequestEvent event, final Context context) {
        Map<String, String> headers = new HashMap<>();
        headers.put("Content-Type", "application/json");

        APIGatewayProxyResponseEvent response = new APIGatewayProxyResponseEvent()
                .withHeaders(headers);

        try {
            return response.withStatusCode(404).withBody("{\"error\":\"error\"}");
        } catch (final Exception e) {
            return response.withStatusCode(500).withBody("{}");
        }
    }
}
```

- docker-compose.yml:
```
version: '3.3'
services:
  localstack:
    container_name: instamini_localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,lambda,apigateway
      - DEBUG=1
      - DEFAULT_REGION=eu-central-1
      - LAMBDA_EXECUTOR=docker
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - LAMBDA_DOCKER_NETOWRK=instamini_aws_localstack_aws-localstack-network
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - aws-localstack-network
  aws-cli:
    container_name: instamini_aws_cli
    image: amazon/aws-cli
    environment:
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - "./lambda/test/build/distributions:/tmp/lambda/test/build/distributions"
    networks:
      - aws-localstack-network

networks:
  aws-localstack-network:
```
- build.gradle:

```
plugins {
    id 'java'
}

group 'zlack.bra.instamini'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.amazonaws:aws-lambda-java-core:1.2.1'
    implementation 'com.amazonaws:aws-lambda-java-events:3.11.0'
    implementation platform('com.amazonaws:aws-java-sdk-bom:1.11.1000')
    implementation 'com.amazonaws:aws-java-sdk-lambda:1.12.172'
    testImplementation 'junit:junit:4.13.2'
}

sourceCompatibility = 11
targetCompatibility = 11

task buildZip(type: Zip) {
    from compileJava
    from processResources
    into('lib') {
        from configurations.runtimeClasspath
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '7.1' //version required
}

test {
    useJUnitPlatform()
}
```
- test.sh
```
docker-compose run --rm aws-cli --endpoint-url http://localstack:4566 lambda create-function --function-name Test --runtime java11 --handler zlack.bra.instamini.SavePostHandler::handleRequest --zip-file fileb:///tmp/lambda/test/build/distributions/lambda_test-1.0-SNAPSHOT.zip --role arn:aws:iam::000000000:role/dummy --timeout 60 1>/dev/null

REST_API_ID=$(docker-compose run --rm aws-cli apigateway create-rest-api --region eu-central-1 --name "test" --endpoint-url=http://localstack:4566 | jq '.id' | tr -d '"')

PARENT_RESOURCE_ID=$(docker-compose run --rm aws-cli apigateway get-resources --region eu-central-1 --rest-api-id "${REST_API_ID}" --endpoint-url=http://localstack:4566 | jq '.items[] | select(.path == "/") | .id' | tr -d '"')

RESOURCE_ID=$(docker-compose run --rm aws-cli apigateway create-resource --region eu-central-1 --rest-api-id "${REST_API_ID}" --parent-id "${PARENT_RESOURCE_ID}" --path-part "post" --endpoint-url=http://localstack:4566 | jq '.id' | tr -d '"')

docker-compose run --rm aws-cli apigateway put-method --region eu-central-1 --rest-api-id "${REST_API_ID}" --resource-id "${RESOURCE_ID}" --http-method "POST" --authorization-type "NONE" --endpoint-url=http://localstack:4566 1>/dev/null

docker-compose run --rm aws-cli apigateway put-integration --region eu-central-1 --rest-api-id "${REST_API_ID}" --resource-id "${RESOURCE_ID}" --http-method "POST" --type AWS_PROXY --integration-http-method "POST" --uri arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-central-1:000000000000:function:Test/invocations --passthrough-behavior WHEN_NO_MATCH --endpoint-url=http://localstack:4566 1>/dev/null

docker-compose run --rm aws-cli apigateway create-deployment --region eu-central-1 --rest-api-id "${REST_API_ID}" --stage-name "test" --endpoint-url=http://localstack:4566 1>/dev/null

echo "   - URL: http://localhost:4566/restapis/${REST_API_ID}/test/_user_request_/post"
```

**Comment by calvernaz** [comment]
Hi @zlackbrq thanks for reporting this and for the detailed instructions. Do you mind to give it a try with the latest docker image?

**Comment by zlackbrq** [comment]
Hello, of course. I will let you know about result.

**Comment by zlackbrq** [comment]
Hello, so i tried it with latest version 0.14.1 and still getting same error. In sample code above and in my own code too... But only if binary data are sent to server. When i tried to send json, it went well.

**Comment by calvernaz** [comment]
Hi @zlackbrq, it could be something else in play here. I'm just curious if you still see the same error or something like the below message?

```
{"Type": "User", "message": "The resource specified in the request does not exist.", "__type": "ResourceNotFoundException"}
```

**Comment by zlackbrq** [comment]
Hello :).

Unfortunately no, the error message is same as stated above.

![image](https://user-images.githubusercontent.com/93795128/160898444-f4baa79c-b9b4-4aca-873e-407e32cbc76e.png)

**Comment by calvernaz** [comment]
Hi @zlackbrq, I'll investigate further and try to reproduce it.

**Comment by zlackbrq** [comment]
Thank you for your answer. I used example above, I think that everything important is stated there. If you miss something, just let me know and I will add it here.

**Comment by calvernaz** [comment]
Hi @zlackbrq, could you try the code from this repository https://github.com/localstack/troubleshooting-issues/tree/main/issue_5689? 

Just run the `run.sh` script, I took your example and works fine. Could you try in your environment.

**Comment by zlackbrq** [comment]
Hello, 

sorry for probably stupid question, but awslocal command is not found. I was running it through docker. So how should i run that script? Edit it myself and put there my aws-cli container?

Thank you.

**Comment by zlackbrq** [comment]
Hello,

so I only added endpoint url to run.sh commands, so aws cli can refer to my localstack and error is still there.

Thank you

**Comment by calvernaz** [comment]
Hi @zlackbrq, yes that works, awslocal is just a wrapper pointing to localstack endpoint.

Hum...so it's not a different use case because this example runs fine for me. Can you remove the docker image, and pull a new one? Just to make sure you don't have anything cached.

**Comment by zlackbrq** [comment]
Hello, 

yes of course. I am working on it :). Can I have one question? Did you get this error with my example before latest release too?

Thank you.

**Comment by zlackbrq** [comment]
So I deleted all localstack images I had with different versions, I pulled the latest one again and error still remains.

**Comment by calvernaz** [comment]
> Hello,
> 
> yes of course. I am working on it :). Can I have one question? Did you get this error with my example before latest release too?
> 
> Thank you.

Yes, I could reproduce the issue, the response status code `404` was being captured and failing to decode. You can see the fix [here](https://github.com/localstack/localstack/pull/5721)

**Comment by calvernaz** [comment]
This is the output i have,

```
{
    "FunctionName": "Test",
    "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:Test",
    "Runtime": "java11",
    "Role": "arn:aws:iam::000000000:role/dummy",
    "Handler": "SavePostHandler::handleRequest",
    "CodeSize": 6460221,
    "Description": "",
    "Timeout": 60,
    "LastModified": "2022-03-30T22:07:53.319+0000",
    "CodeSha256": "3PReyw27kzGo6O600WD+D1edmkQZobzkA3G2tU3WcBc=",
    "Version": "$LATEST",
    "VpcConfig": {},
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "8a7c2cfa-9817-4d4b-bff2-f63355b1830c",
    "Layers": [],
    "State": "Active",
    "LastUpdateStatus": "Successful",
    "PackageType": "Zip",
    "Architectures": [
        "x86_64"
    ]
}
{
    "type": "AWS_PROXY",
    "httpMethod": "POST",
    "uri": "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:Test/invocations",
    "requestParameters": {},
    "passthroughBehavior": "WHEN_NO_MATCH",
    "cacheNamespace": "d5f60076",
    "cacheKeyParameters": []
}
{
    "id": "wjk1sif1cw",
    "createdDate": 1648678077
}
{"error":"error"}
```

and localstack logs,

```
{"statusCode":404,"headers":{"Content-Type":"application/json"},"body":"{\"error\":\"error\"}"}
>START RequestId: 7abf044d-4ceb-106c-17ae-2939bc70d26b Version: $LATEST
> END RequestId: 7abf044d-4ceb-106c-17ae-2939bc70d26b
> REPORT RequestId: 7abf044d-4ceb-106c-17ae-2939bc70d26b	Init Duration: 855.63 ms	Duration: 83.57 ms	Billed Duration: 84 ms	Memory Size: 1536 MB
```

**Comment by zlackbrq** [comment]
These are mine:

```
{
    "FunctionName": "Test",
    "FunctionArn": "arn:aws:lambda:eu-central-1:000000000000:function:Test",
    "Runtime": "java11",
    "Role": "arn:aws:iam::000000000:role/dummy",
    "Handler": "SavePostHandler::handleRequest",
    "CodeSize": 6460212,
    "Description": "",
    "Timeout": 60,
    "LastModified": "2022-03-30T22:22:53.390+0000",
    "CodeSha256": "Y86WpAE3tPvgrl8NxPTTl9+4TT7jBrMHxFMCqoO9GRc=",
    "Version": "$LATEST",
    "VpcConfig": {},
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "14fdf796-dab7-4920-9a57-dfbde04cc14b",
    "State": "Active",
    "LastUpdateStatus": "Successful"
}
{
    "type": "AWS_PROXY",
    "httpMethod": "POST",
    "uri": "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:Test/invocations",
    "requestParameters": {},
    "passthroughBehavior": "WHEN_NO_MATCH",
    "cacheNamespace": "79712862",
    "cacheKeyParameters": []
}
{
    "id": "g392b0fowd",
    "createdDate": 1648678978
}
{}
```

Localstack logs:

```
instamini_localstack  | 2022-03-30T22:22:58.595:INFO:localstack.services.apigateway.integration: Method request body before transformations: LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0yZDFkODU2YzI4NWM1MzJkDQpDb250ZW50LURpc3Bvc2l0aW9uOiBmb3JtLWRhdGE7IG5hbWU9ImltYWdlIjsgZmlsZW5hbWU9Im55YW4tY2F0LmpwZyINCkNvbnRlbnQtVHlwZTogaW1hZ2UvanBlZw0KDQqJUE5HDQoaCgAAAA1JSERSAAAA4QAAAOEIAwAAAAltIkgAAAIEUExURQAzZgAAAP0AAP2Y/ZiYmGYz/TP9AP39AP2YAACY/f2Z/QA0aAAYMP2XAP///wCY/pcYMGxVQJubmwEzaQAvXfoBAf0sAACc/g2M/cQVKf3DAHEz//7YAGUz+0Azv+rHlQATJW0k/fzRjqSkpF1D/fLEkwCS/+z+AFL9AP6R//2FAP6eAAytzvzMmnz9AEBAQC8zrQAzU/22vwApUxcXF3R0dPyxyv2QAP+YmAEMGDc3N9vbAElJSRUMFRvDsgAiXaqGZWdnZwApYQAKU8t7y1VVVf6c9FhYAImJiRRkAP3Gof/apIGBgSAgIBOtsbnH1OTq7wAXV1g1AP2r2/1Vuv2k4/2D6JNZk+mZmceYmKawwC1Fb0BSeAAAT1x9nP0+pP0sk/1x1W5uARyGALW1tc/PzwB7ziMVFRkMQI6iuE9wknKNqM/c5ICUrKSzxEdZfYMbNVsYMN0AADQqVZoAANYOG+UAAK0AAIcwJE9FPJNxVcsAAIgfF/29sdWsggAaPD8AAP/0uFsAAP1uAL9zv3pJelhEAG1Mbf1kxTc9R/3vAP6rAEkrSduOxDMzAbu7AFpaAEdHDdDRACUlAND/AP4chf+u/z6+AMpmtI8XUCzbAAUYABzMkgQrLA2uy8iPjwJdna+ZmY5VVU9V/Vcqyxd+/ysVbkczyywjhUhbcAMzeBgqPNuvyvIAAAx0SURBVHic7Z2NXxvlHcBzJp0lCZc1F0edtkVDWaFlkSYpg6VLc20wg2QJA0EKkqQDLRBgm85Onc2cdNK66ZxrnXWbbdc5rf/kntd7y/MESi6jPH2+fAj38lz6fPP8npe7ey71eHgEtlnf52i63rhJ0/YiK21iYXl5xe6ogU2rDdr7FW2uqKrLads2HWyqnd+jDLnO42C4XCyu6ra2RVsrFh3S+5q5ubkdbZNIJP8PhOrmmczPz+91FtqKvlKs1eaFGcow0BdKqrohDfcz2vzq2tqc0I0NOI0SuQQlEolEIpFIXEXThR4aetBlLsFuG9gIaHpJrQk9wNfT0FDoIb5Wg2UoapzqK+vFIjgNXS+ur4gZqPqaqqraKxslVRXn5pYNfbWklgITKzW1tCCmoWduY2OjViqCV2FvjGikLRWzFiJwfyhoiCI0bW19LSBwEQImJtJiC0okEolEIpFIJBKJRCKRCIWoNzYIejot9tUqfW5hYUXoQkwvqGpN6ImgyFDo6cril6EnIPhshsdiMm9A7BKU7GMmJiac1S89MSHOk5BaYL1YdExgSC8Xi2vijN8CpYYHdidqqloUplnVGIbnhTL0BIq1omMiUXq9VlsWJ0phs8JoacQpQolkf6GLPC0MEggIPvR+TM7xWzIMcNnNMbtkO8NWrmIEfvldHhFeBY9wj/lVcHc0yaA+v7a6sJsptvTT0379BI/XNfbnHfBwj3lD2RXDkWaK6fSuzpkiBM87TzzF5onXjUROfsM8pgXDba5U7KotfZryFLcMn+byJjP9m1eu/PbQrngrHo+73iNwvXYJKMMrivL2sV1xrqB0uy3ouiHgHWg4AHl+x6Dk4+deU7o1zeWO3W29K2+88btDh86hHA+8e3qn4PRXDx2K1ev1Zu3N3hv+XlEOjb83jnM82bdTxvAB4++dA+2Nu3XRbcM/AMPjA4RJr3+HEMPj4200/B4Xvg4jsWk4NjY26QWKXviCX73T01684EULeBH8+t8FqXFVbJ/h+0P9HPiG7zcm/jk1HBsdHUVe5BcyVS5X/Wh1qzyFZckLSHy63Yb9H57kwDfsb0xsGnr7vE7KlcoWLrqpm+Vpv33nmTYZGuHVf7KTycGD/PjtP+hMbRg+P+DFlXCHhn7/GdhntMFwaAhnbeggl06YBPwOgbToD16Eyw1pieHpyUlQB73VqamqGaV+/3S1Oo1Xp6u4IvrNl5cmJ8+MtcGQL2YIbp+kwfAMNpqqVKZsLY2x4PV7jUWjqva91BbDThRpB80f2wJdtSQxFjstaWlqaohLjRo6AHa3EH4v8SdFaRoGNIgrpg9TQA9Rhthrq1zeYhh6/ZvKWYAyM4pWp0EnAgvYNAwE0blGs/PFnRt24kBsFotkNykrWsy2Y+ii3dDZ0lgMEdegob9auVmBzY6/r8HQjfGbmUcufHNGWquh8eK31znT8BaM2GqlAgxhmsYydGEUTnM79H0uJzmOnQcZif/INCQliuugf3NzJpWFfLC5uQla2K2tLVuUBuPx62j/9Xo87p7hjSd5fMjpSTpPMo55kW9Ii/OCooz4wuAnmlKUP12AaqjJoVEKyUZ94XA4A5YirZbiEKG/mSGHzm0MHZWPtJj+C2eRoc8XjQFDMLajH4DVEO53x/BZClfwyWe5MBLzDcmw22sahvOZTObatc1REsUkShPZTCbvniFfbHfwDacqeKBmGsJAzMMWlZxgEMNCPhrGux95Q3JqRF6wod8SpagYkSGBGCbpzr03/LGV5oZ+7xTq9RoMC4kPLlD+fPXY28OJkfwjY3jjI+vFzo8bDB3VsFr1OqIUBWo0Y32XERChxr69N/zEkrWPsOFfnIbGqMaPz4gdhsTDNDR3uG34Ay4cPxCYnwwnEkoCAHLy6cc3wJYbTdpSatxgCN4DvQv820bDH3JhK/710qVLmSQhC9r4Fy9BPrXXQ/80PkU0Tpr8jYa5pIV8+wy/w4Vt+DH413NRWGucVclahnDQ6Ti9cBr6wjZ8TsMWBT1GLJ7gGv6NGbvQMJnLMaqSw/DmljFoA1VxdPSW05ALeltPq2eJJyj8MjzB5DPwrxcKIzmcVaCa8yULjYbTW/hCBqJarf59ZuZaKpbdgR8wTKZSsWC93tqTJHyxbfgM2SRylsJwGqKKB1tQ2p6WK5XPQYJwNGrEJ9OMboYJE8pwa1WxRcOzvqhJ3mno7DHKlfLn8FMxXMASqMoNirlcmG7O7Z3h7V8gUtmUCTilKxiGjPP7KWxomCwuLS1mUxmHX3RpaSmfSuHB9x4aEqxNTAG0rSPE0N9Xxhe4rfRNe2dMw3BuSVWXFCXmNCypalJRMtFHwvC2bTwCgsswnK5UKg5D2Bk2GCaUlLUChh81wxM/NfhCKWTy+YLT0HrfAizN2KJ0cTFsNcyjHj8MNmfbYPiPn/Dg+4FjfmbwT0XB4zdSD6vGBW7zOo2tDH3RbKEAPhFqGPbFEolYOJyLFQrgfTJu18NTh0O9bG5zDU/1hroMBh09vvMCm8WQtJ7wOo0CDcPUEI68wzncJLtehqd6uzpYhHr5ZXiqtyNE6epmjWmsVRD9sZVhDKWPGWUIKnHBNHSpDE8R/tUV6gjB/HagF7zQgV5PcelCidARXR2vIgZZhmD8XUaXMKjh3ZcRs8k8wOwe4VoY/8nnv8RpXmvV0IhFYsQw5AQvOob8wHRGrLIMy6TZIYazP0LMwo7d0uPjfh6M5OHCyzhNy4YwZzBzzAildKE0eIGkZhwCS5MaOoITG5otzV1i6GsCNmy9DFHWQlw3useSJNSwYP0sBq33D+H9QlSaYPw9Nc0yDIPuhbSlWSWRxFVvJAEroVuGOCxJhPIgSbAmXWUcYBjie8CWu2t0CNdoaLQ0oAskhgV0RditKMU5B35dXGhF66CyIWrISEwNB8a8rPuH0PALX9hmmMLnwMgQkhtx1dCIr8NcQvaQNKM01GtP+OqdO3e6rXMx6P1D886M/8LM5kw2m5lF3EWGBXQXJgu8YmghlUCGd2dnv7x37169Hm/t/JDEXKjr3z08DneFjCi1NrcdvY5jjl6m/SGdTwNvfdpmDYGVUXSOT1vPvMIE3bfwuXKdxgivnucOcDjMC99QzzPWdM/cJ4YD43ROFJxw0gd/IF4vekHXaWgf0cSQXP5p2dAIRXturfyn1xm3mN7DPdZkZhlevUrmfZ0ZZQENc7kcuTmTYBqCthQkybph+ByF53fgwHNcbILdlgy+fbzZ7Mvx8asKaThhJ88CFCFoUesBF2Yr8MUekp7LVsNjA83Ad5jC6DYpj/CISzMV3NE70tNz/3KCoGw/RxjeJUw2G9AQw5ZD1DXD+1999VU2mUE/8AL4W9tN6IZXBGLN+Tbuwk18m+ERyAH6QlbRYpOywxw4CsokD8fLUdACJtnN48NSd2nGkJHZZ7jwBY0kR8+SQSVsOVozHB4exgtuzf0ycvvfozy4hXjEOOZrWK/QOXkyk0kFgzCT+ALjCJw90ghIMIL2x/B+kL4A1r755jpYiZNHQNzhCA20B4OcB0cG79NgbOABfRylrtATA2DU7QmAdQVPt8gklKDW+IBUN2pLcY8fBKMyhQxjohkyr829CftGoD3gPd4UOcIN369JW6fVYeu/CKrhIjSMeGCZoH5tMQkMGZntVhI5lCCHDCMKvC6D0rs+N/EFisZrmSMvcHlAIgkakqj7NhisewJxEGtGlAYZH109GLxu7AdlGMTrMRTV7hoOUvhdzyAXWlWQobUF1DQtYmxilWFA8xhjINivgwOM93DZUKPsIEkDRgqLIcldIG4aMt87PmzsRx9uJNgmQ1cIxLspNHeBiLGpzjSMBOl+MjarG+uPoKH5kF+EsYnT7Dv3b5d+j2E857rds68Nu3fyrKxEIpFIJBKJRCKRSCQSiaS9ML4tWCy01bVVQf/Laoymq6p6UeRC1PSaWloW2xB+H7I03M8gQ7Hroba+vr4gclsq2b/o5yHwOzsn0B99Aq5PiBOu6dUSZHkO9Iel0pqub9TgelGc/y8nvaxC1ud03FvoKyW4XlsRx3CNGGqiGuorFyGroLdYvnhxQdPn0PryvDgVEX41cDqtoyX4Xx1peF0cQQu68F8pPzc/v5tvst43gJamJP7Zk/iGj8HZk9CGHuEN4bi0tiayocezsrIyv9d5aC/i9/gSiUQikUgkEolEInnk0EQ/G9XnisWL4tzBY6BvqGppQRruZ/T5Wq0ozj1KFvorr5wXWlAikUgkkseP/wEksPgyDqkcXQAAAABJRU5ErkJggg0KLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0yZDFkODU2YzI4NWM1MzJkLS0NCg==
instamini_localstack  | 2022-03-30T22:22:58.596:DEBUG:localstack.services.awslambda.lambda_api: Running Lambda function arn:aws:lambda:us-east-1:000000000000:function:Test from API Gateway invocation: POST /post
instamini_localstack  | 2022-03-30T22:22:59.073:DEBUG:localstack.services.awslambda.lambda_api: Unable to find details for Lambda arn:aws:lambda:us-east-1:000000000000:function:Test in region us-east-1
instamini_localstack  | 2022-03-30T22:22:59.078:INFO:localstack.utils.threads: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7ff2102d7430>(None) failed: 'utf-8' codec can't decode byte 0x89 in position 143: invalid start byte Traceback (most recent call last):
instamini_localstack  |   File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
instamini_localstack  |     result = self.func(self.params, **kwargs)
instamini_localstack  |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
instamini_localstack  |     return fn(*args, **kwargs)
instamini_localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 965, in handler
instamini_localstack  |     response = modify_and_forward(
instamini_localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 509, in wrapper
instamini_localstack  |     value = func(*args, **kwargs)
instamini_localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 589, in modify_and_forward
instamini_localstack  |     listener_result = listener.forward_request(
instamini_localstack  |   File "/opt/code/localstack/localstack/services/edge.py", line 175, in forward_request
instamini_localstack  |     result = do_forward_request(api, method, path, data, headers, port=port)
instamini_localstack  |   File "/opt/code/localstack/localstack/services/edge.py", line 230, in do_forward_request
instamini_localstack  |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
instamini_localstack  |   File "/opt/code/localstack/localstack/services/edge.py", line 254, in do_forward_request_inmem
instamini_localstack  |     response = modify_and_forward(
instamini_localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 509, in wrapper
instamini_localstack  |     value = func(*args, **kwargs)
instamini_localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 682, in modify_and_forward
instamini_localstack  |     updated_response = listener.return_response(
instamini_localstack  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 155, in return_response
instamini_localstack  |     data = data and json.loads(to_str(data))
instamini_localstack  |   File "/opt/code/localstack/localstack/utils/strings.py", line 31, in to_str
instamini_localstack  |     return obj.decode(encoding, errors) if isinstance(obj, bytes) else obj
instamini_localstack  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 143: invalid start byte
instamini_localstack  | 
instamini_localstack  | 2022-03-30T22:22:59.079:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/restapis/cj23c9elzh/test/_user_request_/post: 'utf-8' codec can't decode byte 0x89 in position 143: invalid start byte Traceback (most recent call last):
instamini_localstack  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 185, in index
instamini_localstack  |     result = await run_sync(handler, request, data)
instamini_localstack  |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 85, in run_sync
instamini_localstack  |     return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
instamini_localstack  |   File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
instamini_localstack  |     result = self.func(self.params, **kwargs)
instamini_localstack  |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
instamini_localstack  |     return fn(*args, **kwargs)
instamini_localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 965, in handler
instamini_localstack  |     response = modify_and_forward(
instamini_localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 509, in wrapper
instamini_localstack  |     value = func(*args, **kwargs)
instamini_localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 589, in modify_and_forward
instamini_localstack  |     listener_result = listener.forward_request(
instamini_localstack  |   File "/opt/code/localstack/localstack/services/edge.py", line 175, in forward_request
instamini_localstack  |     result = do_forward_request(api, method, path, data, headers, port=port)
instamini_localstack  |   File "/opt/code/localstack/localstack/services/edge.py", line 230, in do_forward_request
instamini_localstack  |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
instamini_localstack  |   File "/opt/code/localstack/localstack/services/edge.py", line 254, in do_forward_request_inmem
instamini_localstack  |     response = modify_and_forward(
instamini_localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 509, in wrapper
instamini_localstack  |     value = func(*args, **kwargs)
instamini_localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 682, in modify_and_forward
instamini_localstack  |     updated_response = listener.return_response(
instamini_localstack  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 155, in return_response
instamini_localstack  |     data = data and json.loads(to_str(data))
instamini_localstack  |   File "/opt/code/localstack/localstack/utils/strings.py", line 31, in to_str
instamini_localstack  |     return obj.decode(encoding, errors) if isinstance(obj, bytes) else obj
instamini_localstack  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 143: invalid start byte
instamini_localstack  | 
```

**Comment by calvernaz** [comment]
Thanks, now I'm certain that is something wrong with the version:
If you look to your logs and compare to the code that line doesn't exist anymore
```
instamini_localstack  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 155, in return_response
instamini_localstack  |     data = data and json.loads(to_str(data))
```

and the code https://github.com/localstack/localstack/blob/master/localstack/services/apigateway/apigateway_listener.py#L155

**Comment by zlackbrq** [comment]
Yeah, I see that now... I will try to clear all docker's data and try again. Rest is my problem, so I think this issue is done.

Thank you very much for help! :)

**Comment by calvernaz** [comment]
No problem! By the end of the day we will have another release, you can give it a go as well
