### ISSUE TITLE
bug: Cannot donwload S3 files uploaded with a pre-signed URL

### ISSUE THREAD

**Issue by ypicard** [localstack/localstack#5699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am uploading files to S3 using pre-signed URLs.
First surprising behaviour:
- If I use the localstack [dashboard](https://app.localstack.cloud/dashboard), I do not see the files showing up in the S3 resources.
- If I use the AWS CLI to list the resources from my localstack bucket, they do show up.
Second surprising behaviour:
- I cannot download a file from my localstack S3 bucket which was uploaded using a pre-signed URL. It gives the following error:
```
2022-03-18T04:22:39.664:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request GET http://localhost:4566/uploads.us.localstack.magnus/6233c94187dc8d69af653709/C%23%207.0%20in%20a%20Nutshell_%20The%20Definitive%20Reference%20%28%20PDFDrive%20%29.pdf: An error occurred (404) when calling the HeadObject operation: Not Found Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 185, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 85, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 965, in handler
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 509, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 589, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 175, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 230, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 254, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 509, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 682, in modify_and_forward
    updated_response = listener.return_response(
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1495, in return_response
    fix_range_content_type(bucket_name, path, headers, response)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 657, in fix_range_content_type
    result = s3_client.head_object(Bucket=bucket_name, Key=key_name)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found

2022-03-18T04:22:39.665:INFO:localstack.utils.threads: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0xffff9483b790>(None) failed: An error occurred (404) when calling the HeadObject operation: Not Found Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 965, in handler
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 509, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 589, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 175, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 230, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 254, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 509, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 682, in modify_and_forward
    updated_response = listener.return_response(
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1495, in return_response
    fix_range_content_type(bucket_name, path, headers, response)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 657, in fix_range_content_type
    result = s3_client.head_object(Bucket=bucket_name, Key=key_name)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```

### Expected Behavior

- Be able to see files uploaded with pre-signed URLs on the localstack dashboard
- Be able to download files uploaded with pre-signed URLs to a localstack instance with the CLI, or any other AWS SDK when specifying the endpoint URL.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run --rm -it -p 4566:4566 --network my_network --name localstack localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws s3 cp --endpoint-url http://localhost:4566 "s3://my_bucket/my_file.pdf" ~/Downloads

### Environment

```markdown
- OS: MacOS Big Sur 11.6
- LocalStack: 0.14.1
```

**Comment by whummer** [comment]
Thanks for reporting @ypicard . Haven't been able to replicate this issue - can you please share the commands used to upload the file via the presigned URL?

Can you please verify if you are able to replicate the following sequence of commands:
```
$ awslocal s3 mb s3://test
$ awslocal s3 presign s3://test/test
http://localhost:4566/test/test?X-Amz-Algorithm=...
$ curl -XPUT -d 'foobar' 'http://localhost:4566/test/test?X-Amz-Algorithm=...'
$ awslocal s3 ls s3://test
2022-04-01 19:45:46          6 test
$ awslocal s3 cp s3://test/test /tmp/test
download: s3://test/test to ../../../../tmp/test/test
```
Thanks!

**Comment by ypicard** [comment]
Hi @whummer ,

Thank you for your reply. I tried your snippet and everything works fine with it.
Then, I went back to my code and somehow... it works. I have not updated anything from my end, so I cannot really provide any additional information concerning the initial situation...

I noticed the local stack dashboard has been updated and I can see my files being uploaded in it now. As expected.
I think you can close this issue. I'll come back if I need to.

I really appreciate the time and effort, thank you.

**Comment by whummer** [comment]
Thanks for confirming that it is fixed @ypicard  - please do let us know if there are any other issues. Thanks!
