### ISSUE TITLE
Unable to correctly import OpenAPI spec into APIGatewayV2

### ISSUE THREAD

**Issue by jrauen** [localstack/localstack#5759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm attempting to create an HTTP API using an OpenAPI 3.0 spec file but am encountering the following error when I do so:
```
Traceback (most recent call last):
2022-03-28T13:21:56.129098900Z   File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
2022-03-28T13:21:56.129112700Z     result = self.func(self.params, **kwargs)
2022-03-28T13:21:56.129145800Z   File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
2022-03-28T13:21:56.129161500Z     return fn(*args, **kwargs)
2022-03-28T13:21:56.129176300Z   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 965, in handler
2022-03-28T13:21:56.129192900Z     response = modify_and_forward(
2022-03-28T13:21:56.129210100Z   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 509, in wrapper
2022-03-28T13:21:56.129227100Z     value = func(*args, **kwargs)
2022-03-28T13:21:56.129243300Z   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 589, in modify_and_forward
2022-03-28T13:21:56.129259500Z     listener_result = listener.forward_request(
2022-03-28T13:21:56.129288300Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py.enc", line 202, in forward_request
2022-03-28T13:21:56.129305100Z   File "/opt/code/localstack/localstack/services/edge.py", line 178, in forward_request
2022-03-28T13:21:56.129320200Z     result = do_forward_request(api, method, path, data, headers, port=port)
2022-03-28T13:21:56.129336900Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py.enc", line 196, in do_forward_request
2022-03-28T13:21:56.129370200Z   File "/opt/code/localstack/localstack/services/edge.py", line 243, in do_forward_request
2022-03-28T13:21:56.129385500Z     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
2022-03-28T13:21:56.129423500Z   File "/opt/code/localstack/localstack/services/edge.py", line 267, in do_forward_request_inmem
2022-03-28T13:21:56.129440900Z     response = modify_and_forward(
2022-03-28T13:21:56.129453500Z   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 509, in wrapper
2022-03-28T13:21:56.129489900Z     value = func(*args, **kwargs)
2022-03-28T13:21:56.129504800Z   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 589, in modify_and_forward
2022-03-28T13:21:56.129520100Z     listener_result = listener.forward_request(
2022-03-28T13:21:56.129532200Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/apigateway_extended.py.enc", line 86, in forward_request
2022-03-28T13:21:56.129548900Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/invocations.py.enc", line 135, in invoke_api
2022-03-28T13:21:56.129565000Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/invocations.py.enc", line 180, in invoke_http_api_v2
2022-03-28T13:21:56.129581700Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/invocations.py.enc", line 231, in v2_invoke_integration_request
2022-03-28T13:21:56.129594500Z   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/invocations.py.enc", line 284, in v2_do_invoke_integration_request
2022-03-28T13:21:56.129612000Z Exception: Unsupported integration type "" for API ID "81f3070b"
```

It appears that the integration type of `AWS_PROXY` is not being properly added from the openapi.yaml file below.
```yaml
openapi: 3.0.3
info:
  title: MTS Customer API
  description: MTS Customer API
  version: 1.0.0
paths:
  /cases:
    get:
      x-amazon-apigateway-integration:
        $ref: "#/components/x-amazon-apigateway-integrations/getCases"
      summary: Get all cases
      operationId: getCases
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
components:
  x-amazon-apigateway-integrations:
    getCases:
      type: "aws_proxy"
      httpMethod: "POST"
      payloadFormatVersion: "2.0"
      uri: "arn:$${AWS::Partition}:apigateway:$${AWS::Region}:lambda:path/2015-03-31/functions/${snow_cases}/invocations"
      requestParameters:
        overwrite:header.operation: "getCases"
```

When executing `awslocal apigatewayv2 get-integrations --api-id 81f3070b` I receive the following output:
```
{
    "Items": [
        {
            "IntegrationId": "d013d126",
            "IntegrationType": "",
            "TimeoutInMillis": 30000
        }
    ]
}
```

### Expected Behavior

The above should produce the same results as using the command like which does work correctly.

```
awslocal apigatewayv2 create-integration --api-id 81f3070b --integration-type AWS_PROXY --integration-uri arn:aws:lambda:us-east-1:000000000000:function:my-function

{
    "Items": [
        {
            "IntegrationId": "fa27db35",
            "IntegrationMethod": "POST",
            "IntegrationType": "AWS_PROXY",
            "IntegrationUri": "arn:aws:lambda:us-east-1:000000000000:function:snow-cases",
            "TimeoutInMillis": 30000
        }
    ]
}
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

version: "3.3"
services:
  localstack:
    image: localstack/localstack
    environment:
      HOSTNAME: "localstack"
      HOSTNAME_EXTERNAL: "localstack"
      SERVICES: "apigateway,lambda,cloudwatch,iam"
      LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY}
      DEBUG: "1"
      LS_LOG: "trace"
      TEST_AWS_ACCOUNT_ID: "000000000000"
    ports:
      - "443:443"
      - "4566:4566"
      - "4571:4571"

### Environment

```markdown
- OS: MacOS Monterey 12.3
- LocalStack: latest - d293a86d1bbf
```

**Comment by calvernaz** [comment]
Hi @jrauen, I created an example to test the import and it works as expected. 

You can find the example [here](https://gist.github.com/calvernaz/1bd00e7568b6f86dcb5f7e7e4ad56672).

Import the API,
```
awslocal apigatewayv2 import-api --body file://file.yaml
```

Then describe,
```
 awslocal apigatewayv2 get-integrations --api-id <api-id>
```

**Comment by jrauen** [comment]
I tested out your file and it worked so I played around a bit and found that if I put the integrations directly under the path operations it works. So it looks like localstack/moto is unable to handle the `$ref` keys. I'll close this out and put in a feature request for the `$ref` issue.
