### ISSUE TITLE
bug: localstack logs command fails: no module named 'cryptography'

### ISSUE THREAD

**Issue by SwatsonCodes** [localstack/localstack#5761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `localstack logs` command fails with the following exception:
```
Traceback (most recent call last):
  File "/usr/local/bin/localstack", line 23, in <module>
    main()
  File "/usr/local/bin/localstack", line 19, in main
    main.main()
  File "/usr/local/lib/python3.9/site-packages/localstack/cli/main.py", line 6, in main
    cli()
  File "/usr/local/lib/python3.9/site-packages/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/localstack/cli/localstack.py", line 175, in cmd_logs
    from localstack.utils.common import FileListener
  File "/usr/local/lib/python3.9/site-packages/localstack/utils/common.py", line 27, in <module>
    from localstack.utils.crypto import (  # noqa
  File "/usr/local/lib/python3.9/site-packages/localstack/utils/crypto.py", line 7, in <module>
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
ModuleNotFoundError: No module named 'cryptography'
```

### Expected Behavior

The localstack container logs are displayed

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`localstack start -d`
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
`localstack logs`

### Environment

```markdown
- OS: 
- LocalStack: latest
```

**Comment by mbaeuerle** [comment]
Having the same issue on Mac using:
Localstack 0.14.2.1
Python 3.9.12

**Comment by silv-io** [comment]
Hi @mbaeuerle, I cannot reproduce this issue. Can you confirm that it still happens with `localstack/localstack:1.0.3` and the corresponding cli version?
