### ISSUE TITLE
bug: ImportError: cannot import name 'OrderedDict' from 'typing_extensions

### ISSUE THREAD

**Issue by johanburati** [localstack/localstack#5797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting an `ImportError`: 
```
$ localstack start -d
Traceback (most recent call last):
  File "/home/job/.local/bin/localstack", line 23, in <module>
    main()
  File "/home/job/.local/bin/localstack", line 17, in main
    from localstack.cli import main
  File "/home/job/.local/lib/python3.8/site-packages/localstack/cli/__init__.py", line 1, in <module>
    from .console import console
  File "/home/job/.local/lib/python3.8/site-packages/localstack/cli/console.py", line 1, in <module>
    from rich.console import Console
  File "/home/job/.local/lib/python3.8/site-packages/rich/console.py", line 46, in <module>
    from ._log_render import FormatTimeCallable, LogRender
  File "/home/job/.local/lib/python3.8/site-packages/rich/_log_render.py", line 5, in <module>
    from .text import Text, TextType
  File "/home/job/.local/lib/python3.8/site-packages/rich/text.py", line 5, in <module>
    from rich.emoji import EmojiVariant
  File "/home/job/.local/lib/python3.8/site-packages/rich/emoji.py", line 4, in <module>
    from .jupyter import JupyterMixin
  File "/home/job/.local/lib/python3.8/site-packages/rich/jupyter.py", line 4, in <module>
    from .segment import Segment
  File "/home/job/.local/lib/python3.8/site-packages/rich/segment.py", line 19, in <module>
    from .cells import (
  File "/home/job/.local/lib/python3.8/site-packages/rich/cells.py", line 6, in <module>
    from ._lru_cache import LRUCache
  File "/home/job/.local/lib/python3.8/site-packages/rich/_lru_cache.py", line 8, in <module>
    from typing_extensions import OrderedDict
ImportError: cannot import name 'OrderedDict' from 'typing_extensions' (/usr/local/lib/python3.8/dist-packages/typing_extensions.py)
```

### Expected Behavior

Start the container without error:
```
% localstack start -d

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.13.0.11

[20:22:20] starting LocalStack in Docker mode 🐳
[20:22:21] detaching
```

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Followed the instructions in [README.md](https://github.com/localstack/localstack/blob/master/README.md)
```
$ pip install localstack
$ localstack start -d
```

### Environment

```markdown
- OS:                  Ubuntu 20.04.4 LTS
- LocalStack: 
localstack             0.14.1.3
localstack-client      1.33
localstack-ext         0.14.1.9
typing-extensions      3.7.4.3
- Python:              3.8.10
- Podman:              3.4.2 (`docker` is an alias to `podman` command)
```

**Comment by MarcelStranak** [comment]
Hello @johanburati,
I've attempted to reproduce the issue. I was unable to get the error you received.
Can you please try updating the LocalStack and the required modules?
```bash
#remove the localstack and the module
python3 -m pip uninstall localstack typing_extensions
#install them again
python3 -m pip install localstack typing_extensions
```

If that does not help, you might want to try force reinstall.
```
--force-reinstall
Reinstall all packages even if they are already up-to-date.
```
```bash
#force reinstall the module
python3 -m pip install --force-reinstall typing_extensions
#force reinstall localstack and all other modules
python3 -m pip install --force-reinstall localstack
```

**Comment by johanburati** [comment]
Thank you I have uninstall and reinstalled the modules and it is working now. I had to uninstall the modules using sudo so I had probably installed some module using root which could explain the issue I had. Thank you !
