### ISSUE TITLE
question: does localstack support all services (e.g. rds) on a container running on windows?

### ISSUE THREAD

**Issue by yangzhang21** [localstack/localstack#5862]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

i used to run localstack container on linux or macOS, which works perfectly. 
today i tried the same code on an ubuntu 20.0.4 wsl in a windows 11 pro. same docker container but get a lot errors. 
like this 
```
14T07:47:35:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localstack:4566/: Unable to find listener for service "rds" - please make sure to include it in $SERVICES Traceback (most recent call last):

  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 129, in index

    raise result

  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 681, in run

    result = self.func(self.params)

  File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run

    return fn(*args, **kwargs)

  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 352, in handler

    response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,

  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 171, in modify_and_forward

    listener_result = listener.forward_request(method=method,

  File "/opt/code/localstack/localstack/services/edge.py", line 117, in forward_request

    return do_forward_request(api, method, path, data, headers, port=port)

  File "/opt/code/localstack/localstack/services/edge.py", line 136, in do_forward_request

    result = do_forward_request_inmem(api, method, path, data, headers, port=port)

  File "/opt/code/localstack/localstack/services/edge.py", line 150, in do_forward_request_inmem

    raise HTTPErrorResponse(message, code=400)

localstack.utils.server.http2_server.HTTPErrorResponse: Unable to find listener for service "rds" - please make sure to include it in $SERVICES
``` 
I double checked that I have rds in the $SERVICES in dockerfile. and the same dockerfile works perfectly in macOS
have no idea what could be the issue.  any thoughts? Thanks!

**Comment by yangzhang21** [comment]
also the s3 bucket works fine. it is created and runs properly.

**Comment by dfangl** [comment]
Hi! Yes, theoretically, RDS should also be supported on Windows, like practically every other functionality.
Would it be possible for you to share the way you are starting up LocalStack? Also, please try completely removing the `SERVICES` variable, as it is not recommended anymore (due to service lazyloading).

**Comment by yangzhang21** [comment]
Thanks @dfangl 

This is part of the yml where I bring up localstack container. I am using `0.12.0`. should I upgrade to the latest release? 
```
  localstack:
    image: localstack/localstack:0.12.10
    container_name: customer-env
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - EDGE_PORT=4566
      - SERVICES=ec2,iam,lambda,route53,s3,sts,redshift,route53,es,cloudtrail,rds,organizations,elbv2,elb
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - LAMBDA_DOCKER_NETWORK=docker-compose_default
      - MAIN_CONTAINER_NAME=customer-env
      - LOCALSTACK_API_KEY=<my pro key>
      - HOSTNAME_EXTERNAL=customer-env
    ports:
      - 443:443
      - 4566:4566
      - 4571:4571
    volumes:
      - "./customer-env:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./customer-env-scripts:/docker-entrypoint-initaws.d
   ```

**Comment by dfangl** [comment]
Yes, please upgrade to the latest release, and please also adopt your docker-compose file to the provided one (https://github.com/localstack/localstack/blob/master/docker-compose.yml) .
With the new docker image, things like SERVICES should not be needed any more. Also, LAMBDA_DOCKER_NETWORK is not needed if you only have one network connected to your container (you can remove network_mode: bridge from the just provided default docker-compose file).
There were huge improvements to the general architecture of LocalStack since 0.12.0, including security improvements, so please go ahead and upgrade to :latest. Please do not forget to run `docker-compose pull` as well!

**Comment by yangzhang21** [comment]
here is the error i got when i run with `0.12.10`. I also tried the latest release `0.14.2` just now but got the license activation error. I will post the error msg shortly  @dfangl 
```
Traceback (most recent call last):

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 451, in _parse_xml_string_to_dom

    parser.feed(xml_string)

xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/docker-entrypoint-initaws.d/create_postgres.py", line 49, in <module>

    main()

  File "/docker-entrypoint-initaws.d/create_postgres.py", line 43, in main

    instance = create_db()

  File "/docker-entrypoint-initaws.d/create_postgres.py", line 27, in create_db

    instance = client.create_db_instance(DBName='test', Engine='postgres', DBInstanceClass='c1', DBInstanceIdentifier='postgres-test', MasterUsername='test', MasterUserPassword='test')

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call

    return self._make_api_call(operation_name, kwargs)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 662, in _make_api_call

    http, parsed_response = self._make_request(

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 682, in _make_request

    return self._endpoint.make_request(operation_model, request_dict)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request

    return self._send_request(request_dict, operation_model)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 134, in _send_request

    success_response, exception = self._get_response(

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 166, in _get_response

    success_response, exception = self._do_get_response(

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 217, in _do_get_response

    parsed_response = parser.parse(

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 243, in parse

    parsed = self._do_error_parse(response, shape)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 505, in _do_error_parse

    root = self._parse_xml_string_to_dom(xml_contents)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/parsers.py", line 454, in _parse_xml_string_to_dom

    raise ResponseParserError(

botocore.parsers.ResponseParserError: Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
```

**Comment by yangzhang21** [comment]
here is the license activate exception with `0.14.2`. i have the pro account. did we change the key activation process after `0.12.10`?

```
2022-04-14T17:00:39.420:WARNING:localstack_ext.bootstrap.licensing: Error activating API key "16w..."(10): MyHTTPSConnectionPool(host='api.localstack.cloud', port=443): Max retries exceeded with url: /v1/activate (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0877038280>: Failed to establish a new connection: [Errno -2] Name or service not known')) Traceback (most recent call last):

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn

    conn = connection.create_connection(

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection

    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo

    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

socket.gaierror: [Errno -2] Name or service not known


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen

    httplib_response = self._make_request(

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request

    self._validate_conn(conn)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn

    conn.connect()

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect

    self.sock = conn = self._new_conn()

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn

    raise NewConnectionError(

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f0877038280>: Failed to establish a new connection: [Errno -2] Name or service not known


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send

    resp = conn.urlopen(

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen

    retries = retries.increment(

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment

    raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: MyHTTPSConnectionPool(host='api.localstack.cloud', port=443): Max retries exceeded with url: /v1/activate (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0877038280>: Failed to establish a new connection: [Errno -2] Name or service not known'))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/bootstrap/licensing.py", line 51, in fetch_key

    result=requests.post("%s/activate"%config.API_URL,json.dumps(data),verify=False,proxies=proxies)

  File "/opt/code/localstack/localstack/utils/http.py", line 125, in _wrapper

    return method(*args, **kwargs)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post

    return request('post', url, data=data, json=json, **kwargs)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request

    return session.request(method=method, url=url, **kwargs)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request

    resp = self.send(prep, **send_kwargs)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send

    r = adapter.send(request, **kwargs)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send

    raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: MyHTTPSConnectionPool(host='api.localstack.cloud', port=443): Max retries exceeded with url: /v1/activate (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0877038280>: Failed to establish a new connection: [Errno -2] Name or service not known'))


2022-04-14T17:00:39.420:WARNING:localstack_ext.bootstrap.licensing: Looking for cached key as fallback...

2022-04-14T17:00:39.421:ERROR:localstack_ext.bootstrap.licensing: exception while activating key

Traceback (most recent call last):

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn

    conn = connection.create_connection(

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection

    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo

    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

socket.gaierror: [Errno -2] Name or service not known


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen

    httplib_response = self._make_request(

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request

    self._validate_conn(conn)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn

    conn.connect()

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect

    self.sock = conn = self._new_conn()

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn

    raise NewConnectionError(

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f0877038280>: Failed to establish a new connection: [Errno -2] Name or service not known


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send

    resp = conn.urlopen(

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen

    retries = retries.increment(

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment

    raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: MyHTTPSConnectionPool(host='api.localstack.cloud', port=443): Max retries exceeded with url: /v1/activate (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0877038280>: Failed to establish a new connection: [Errno -2] Name or service not known'))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/bootstrap/licensing.py", line 51, in fetch_key

    result=requests.post("%s/activate"%config.API_URL,json.dumps(data),verify=False,proxies=proxies)

  File "/opt/code/localstack/localstack/utils/http.py", line 125, in _wrapper

    return method(*args, **kwargs)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post

    return request('post', url, data=data, json=json, **kwargs)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request

    return session.request(method=method, url=url, **kwargs)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request

    resp = self.send(prep, **send_kwargs)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send

    r = adapter.send(request, **kwargs)

  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send

    raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: MyHTTPSConnectionPool(host='api.localstack.cloud', port=443): Max retries exceeded with url: /v1/activate (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0877038280>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by dfangl** [comment]
It seems `api.localstack.cloud` does not resolve on your machine. Can you check, using ping, if it works correctly on your host? Could it be blocked in your environment?

**Comment by yangzhang21** [comment]
looks true. `api.localstack.cloud` not resolved. tried other sites like google.com, yahoo.com work fine. let me figure it out

**Comment by yangzhang21** [comment]
never mind @dfangl  after I fix the dns issue, it works fine with the latest release. still see issue with ec2, but i just want to test rds and s3, so not a blocker :)
i am going to close the ticket
