### ISSUE TITLE
question: Why is my localstack container not accepting these AWS credentials?

### ISSUE THREAD

**Issue by johngribbin** [localstack/localstack#5863]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Hey team, 

First off, congrats on a cool product! 

I am building out a CMS for my company using a combination of Strapi (CMS) and Angular (front end). I added a plugin to Strapi to automatically add images to our AWS S3 buckets. Locally I am using Docker containers (with the official lockstack image) with the aim of emulating AWS using localstack.   

Locally everything is up and running with no errors, however when I add an image I get the following error: 

```
lima-cms-strapi | [2022-04-14 12:22:06.705] http: GET /upload/files?sort=updatedAt:DESC&page=1&pageSize=10 (30 ms) 200
lima-cms-strapi | [2022-04-14 12:22:13.474] error: The AWS Access Key Id you provided does not exist in our records.
lima-cms-strapi | InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
lima-cms-strapi |     at Request.extractError (/app/node_modules/aws-sdk/lib/services/s3.js:718:35)
lima-cms-strapi |     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
lima-cms-strapi |     at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
lima-cms-strapi |     at Request.emit (/app/node_modules/aws-sdk/lib/request.js:688:14)
lima-cms-strapi |     at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
lima-cms-strapi |     at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
lima-cms-strapi |     at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
lima-cms-strapi |     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
lima-cms-strapi |     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:690:12)
lima-cms-strapi |     at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
lima-cms-strapi |     at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
lima-cms-strapi |     at Request.emit (/app/node_modules/aws-sdk/lib/request.js:688:14)
lima-cms-strapi |     at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
lima-cms-strapi |     at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
lima-cms-strapi |     at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
lima-cms-strapi |     at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
```

Any ideas? Thanks in advance!

### Anything else?

After some digging, I accessed the localstack container directly to check if my env vars were being passed to the container correctly: 

<img width="1089" alt="Screen Shot 2022-04-14 at 8 07 45 AM" src="https://user-images.githubusercontent.com/30157175/163389774-0ffc8e8f-9ac4-4305-9a83-2e2b4b268459.png">

^ but as you can see, the same error is returned when attempted to list all the S3 buckets. 

These are the env vars I am passing to both Strapi and localstack:
```
#AWS
AWS_ACCESS_KEY_ID=test
AWS_SECRET_ACCESS_KEY=test
AWS_DOMAIN=localhost:4566
AWS_REGION=us-east-1
AWS_BUCKET=lima-cms-development
```

**Comment by johngribbin** [comment]
@thrau oh interesting! thanks for the quick reply. Ill keep digging and see if I can configure Strapi to use the `awslocal` cli instead of `aws`!
