### ISSUE TITLE
bug: local lambda executor fails to call localstack with InvalidClientTokenId

### ISSUE THREAD

**Issue by mathiaHT** [localstack/localstack#5866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have an
- apigateway rest api v1 event with a proxy event
- an api written with falcon

When invoking api endpoint with LAMBDA_EXECUTOR=local:

```bash
$ curl https://c4ai72hqa4.execute-api.localhost.localstack.cloud:4566/integration/health-check

...
Running Lambda function arn:aws:lambda:us-west-2:000000000000:function:lc-dl-api-integration-integration from API Gateway invocation: HEAD /health-check
Unable to put metric data for metric "Invocations" to CloudWatch: An error occurred (InvalidClientTokenId) when calling the PutMetricData operation: The security token included in the request is invalid.
Unable to put metric data for metric "Errors" to CloudWatch: An error occurred (InvalidClientTokenId) when calling the PutMetricData operation: The security token included in the request is invalid.
Error executing Lambda function arn:aws:lambda:us-west-2:000000000000:function:lc-dl-api-integration-integration: An error occurred (UnrecognizedClientException) when calling the DescribeLogGroups operation: The security token included in the request is invalid. Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 794, in run_lambda
    result = LAMBDA_EXECUTOR.execute(
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 460, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 450, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 170, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 166, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 437, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 433, in _run
    result = self._execute(lambda_function, inv_context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1414, in _execute
    store_lambda_logs(lambda_function, log_output)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_utils.py", line 176, in store_lambda_logs
    return store_cloudwatch_logs(log_group_name, log_stream_name, log_output, invocation_time)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 80, in store_cloudwatch_logs
    log_groups = logs_client.describe_log_groups()["logGroups"]
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 725, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.UnrecognizedClientException: An error occurred (UnrecognizedClientException) when calling the DescribeLogGroups operation: The security token included in the request is invalid.
```
 I also observed some connection to amazon: 52.94.181.80
```bash
$ netstat -ac
...
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:54241           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:50665           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:55819           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:40049           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:4566            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:4567            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:46939           0.0.0.0:*               LISTEN     
tcp        0      0 localhost:40049         localhost:46316         TIME_WAIT  
tcp       58      0 localhost:47900         localhost:50665         CLOSE_WAIT 
tcp        0      0 localhost:4566          localhost:53924         TIME_WAIT  
tcp        0      0 localhost:59614         localhost:46939         TIME_WAIT  
tcp        0      0 localhost:4566          localhost:53958         TIME_WAIT  
tcp        0      0 localhost:4566          localhost:53928         TIME_WAIT  
tcp        0      0 localhost:40049         localhost:46296         TIME_WAIT  
tcp        0      0 localhost:40049         localhost:46312         TIME_WAIT  
tcp        0      0 localhost:4566          localhost:53920         TIME_WAIT  
tcp        0      0 localhost:4566          localhost:53956         TIME_WAIT  
tcp        0      0 localhost:4566          localhost:53970         TIME_WAIT  
tcp        0      0 localhost:4566          localhost:53974         TIME_WAIT  
tcp        0      0 localhost:4566          localhost:53940         TIME_WAIT  
tcp        0      0 localhost:40049         localhost:46338         TIME_WAIT  
tcp        0      0 localhost:53962         localhost:4566          TIME_WAIT  
tcp        0      0 dca97dade20f:4566       172.17.0.1:62348        TIME_WAIT  
tcp        0      0 localhost:40049         localhost:46304         TIME_WAIT  
tcp       32      0 dca97dade20f:59550      52.94.181.80:https      CLOSE_WAIT 
tcp        0      0 localhost:40049         localhost:46300         TIME_WAIT  
tcp        0      0 localhost:40049         localhost:46288         TIME_WAIT  
tcp        1      0 localhost:44638         localhost:40049         CLOSE_WAIT 
tcp        0      0 localhost:4566          localhost:53932         TIME_WAIT  
tcp        0      0 localhost:4566          localhost:53944         TIME_WAIT  
tcp        0      0 localhost:40049         localhost:46292         TIME_WAIT  
tcp        0      0 localhost:4566          localhost:53948         TIME_WAIT  
tcp        0      0 localhost:4566          localhost:53936         TIME_WAIT  
tcp        0      0 localhost:40049         localhost:46346         TIME_WAIT  
tcp        0      0 localhost:46939         localhost:59610         TIME_WAIT  
tcp        0      0 localhost:4566          localhost:53978         TIME_WAIT  
tcp        0      0 localhost:40049         localhost:46308         TIME_WAIT  
tcp        0      0 localhost:40049         localhost:46342         TIME_WAIT  
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ]         STREAM     CONNECTED     617630   
unix  3      [ ]         STREAM     CONNECTED     617564   
unix  3      [ ]         STREAM     CONNECTED     616160   
unix  3      [ ]         STREAM     CONNECTED     616637   
unix  3      [ ]         STREAM     CONNECTED     617540   /run/host-services/docker.proxy.sock
unix  3      [ ]         STREAM     CONNECTED     616638   
unix  3      [ ]         STREAM     CONNECTED     615299   /run/host-services/docker.proxy.sock
unix  3      [ ]         STREAM     CONNECTED     616151   
unix  3      [ ]         STREAM     CONNECTED     616161   
unix  3      [ ]         STREAM     CONNECTED     615296   /run/host-services/docker.proxy.sock
unix  3      [ ]         STREAM     CONNECTED     617565   
unix  2      [ ]         STREAM     CONNECTED     618518
```

### Expected Behavior

I expect the lambda to return code 200 instead of 500 internal error

### How are you starting LocalStack?

With a docker-compose file

#### Docker compose

```yaml
version: '2'
services:
  localstack:
    image: git.apps.airliquide.com:5000/gdo/xdp/tools/image-ci/localstack:0.14.1
    network_mode: bridge
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=local
      - SERVICES=ec2,ecr,dynamodb,s3,sqs,cloudformation,sts,iam,apigateway,logs,lambda,secretsmanager,ssm
    ports:
      - 4566:4566
      - 4571:4571
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - |
          awslocal dynamodb list-tables
          && awslocal s3 ls
          && awslocal sqs list-queues
      interval: 5s
      timeout: 10s
      start_period: 10s
```

#### Serverless config

```yaml
service: datalake-api

frameworkVersion: "2"
variablesResolutionMode: 20210326

package:
  individually: true

custom:
  pythonRequirements:
    dockerizePip: non-linux
    usePoetry: false
    usePipenv: true
  localstack:
    edgePort: ${env:LocalStackPort, '4566'}
    host: ${env:LocalStackHost, 'http://localhost'}
    stages:
      - local
      - integration

plugins:
  - serverless-deployment-bucket
  - serverless-localstack
  - serverless-python-requirements

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: python3.7
  apiName: api
  memorySize: 512
  timeout: 30
  apiGateway:
    description: API Gateway for Data Lake API
    apiKeySourceType: HEADER
    minimumCompressionSize: 0
    resourcePolicy:
      - Effect: Deny
        Principal: "*"
        Action: execute-api:Invoke
        Resource: execute-api:/*
        Condition:
          StringNotEquals:
            aws:sourceVpc: ${env:VpcStack}
    binaryMediaTypes:
      - '*/*'
  endpointType: PRIVATE
  deploymentBucket:
    name: ${env:StagingBucketName}
  
functions:
  api:
    name: ${env:Instance}-api-${opt:stage}-${env:Env}
    handler: lambda_handler.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          private: true
    package:
      patterns:
        - "!**"
        - api/**
        - ./lambda_handler.py
```

### Environment

```markdown
- OS: macos
- LocalStack: 0.14.2
```

**Comment by mathiaHT** [comment]
I think i solved my problem by taking into account the function `is_local_env` in `localstack/utils/aws/aws_utils.py`:

```python
# constant to represent the "local" region, i.e., local machine
REGION_LOCAL = "local"

# dev environment
ENV_DEV = "dev"

def is_local_env(env):
    return not env or env.region == REGION_LOCAL or env.prefix == ENV_DEV
```

Both my code and localstack were using the environment variable `ENV`  which is not referenced here https://docs.localstack.cloud/localstack/configuration/. Then, the function mentionned above was indicating to localstack the environment was not local.

**Comment by whummer** [comment]
Thanks for confirming the fix @mathiaHT , glad you were able to get it working! 👍 Please note that in general you need to configure the `endpoint_url` to point to `http://$LOCALSTACK_HOSTNAME:4566` if you're using AWS SDK clients in your Lambda function. Please let us know if there are any other issues. Thanks
