### ISSUE TITLE
bug: rds-data execute-statement causes 'CREATE DATABASE cannot run inside a transaction block'

### ISSUE THREAD

**Issue by ronaldvaneede** [localstack/localstack#5896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I try to use `awslocal rds-data execute-statement` (without providing a transaction id) to create a database it fails with a `An error occurred (500) when calling the ExecuteStatement operation (reached max retries: 2):` message.
In the localstack logging I see this:
```
2022-04-20T13:05:02.419:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/Execute: CREATE DATABASE cannot run inside a transaction block
Traceback (most recent call last):
File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 185, in index
result = await run_sync(handler, request, data)
File "/opt/code/localstack/localstack/utils/asyncio.py", line 85, in run_sync
return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
result = self.func(self.params, **kwargs)
File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
return fn(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 970, in handler
return modify_and_forward(
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 514, in wrapper
value = func(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 594, in modify_and_forward
listener_result = listener.forward_request(
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py.enc", line 202, in forward_request
File "/opt/code/localstack/localstack/services/edge.py", line 178, in forward_request
result = do_forward_request(api, method, path, data, headers, port=port)
File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
return new(target, *args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py.enc", line 198, in do_forward_request
File "/opt/code/localstack/localstack/services/edge.py", line 233, in do_forward_request
result = do_forward_request_inmem(api, method, path, data, headers, port=port)
File "/opt/code/localstack/localstack/services/edge.py", line 257, in do_forward_request_inmem
response = modify_and_forward(
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 514, in wrapper
value = func(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 594, in modify_and_forward
listener_result = listener.forward_request(
File "/opt/code/localstack/localstack/http/adapters.py", line 38, in forward_request
response = self.request(request)
File "/opt/code/localstack/localstack/aws/proxy.py", line 42, in request
response = self.skeleton.invoke(context)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
return self.dispatch_request(context, instance)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
result = handler(context, instance) or {}
File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
return self.fn(*args, **kwargs)
File "/opt/code/localstack/localstack/aws/api/core.py", line 95, in operation_marker
return fn(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/rds_data/provider.py.enc", line 8, in execute_statement
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/rds_data/provider.py.enc", line 54, in execute_data_api_request
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/rds/db_utils.py.enc", line 187, in query_postgres
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/postgres/cursors.py", line 204, in run
TupleCursor.execute(self, sql, parameters)
psycopg2.errors.ActiveSqlTransaction: CREATE DATABASE cannot run inside a transaction block
```

### Expected Behavior

I expect it to create the database with success and no error :)

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal rds create-db-cluster --db-cluster-identifier db1 --engine aurora-postgresql --master-user-password test --database-name test
    awslocal secretsmanager create-secret --name myadminsecret --secret-string '{ "username": "test", "password": "test" }'
    awslocal rds-data execute-statement --resource-arn "arn:aws:rds:us-east-1:000000000000:cluster:db1" --database "test" --secret-arn "arn:aws:secretsmanager:us-east-1:000000000000:secret:myadminsecret" --sql "CREATE DATABASE foo;"

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.14.2.1
```

**Comment by whummer** [comment]
Hi @ronaldvaneede , thanks for reporting. This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks for your help!

**Comment by ronaldvaneede** [comment]
@whummer thanks for the quick fix. 
Using the `latest` docker image does not give me that error anymore.
