### ISSUE TITLE
Kinesis calls returning 502 Bad Gateway

### ISSUE THREAD

**Issue by warabak** [localstack/localstack#592]
## Summary
While running Kinesis & DynamoDB via docker-compose Localstack, a Java application is trying to use the AWS SDK to simply interact with the local Kinesis stream via `listStreams` or `createStream`. Upon invocation, the Java logger emits a 502 Bad Gateway and the Localstack logs emit a `UnicodeDecodeError`.

## Docker Compose file
```
version: '2'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4567-4583:4567-4583"
      - "8080:8080"
    environment:
      - SERVICES=kinesis:4568,dynamodb:4569
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

## Dummy Java Application
```
public static void main(final String... args) {
        final String testAccessKey = "test";
        final String testSecretKey = "test";

        final AWSCredentialsProvider awsCredentialsProvider = new AWSStaticCredentialsProvider(
                new BasicAWSCredentials(testAccessKey, testSecretKey));

        final AmazonKinesis amazonKinesis = AmazonKinesisClientBuilder.standard()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localhost:4568", "us-east-1"))
                .withCredentials(awsCredentialsProvider)
                .build();

        logger.info("Listing streams....");
        logger.info(amazonKinesis.listStreams().getStreamNames());

        logger.info("Finished!");
    }
```

## Localstack error logs
```
localstack_1  | 2018-01-31T16:45:42:ERROR:localstack.services.generic_proxy: Error forwarding request: 'utf8' codec can't decode byte 0xbf in position 0: invalid start byte Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 181, in forward
localstack_1  |     path=path, data=data, headers=forward_headers)
localstack_1  |   File "/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py", line 21, in forward_request
localstack_1  |     data = json.loads(to_str(data))
localstack_1  |   File "/opt/code/localstack/localstack/utils/common.py", line 432, in to_str
localstack_1  |     return obj.decode(encoding, errors) if isinstance(obj, six.binary_type) else obj
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/encodings/utf_8.py", line 16, in decode
localstack_1  |     return codecs.utf_8_decode(input, errors, True)
localstack_1  | UnicodeDecodeError: 'utf8' codec can't decode byte 0xbf in position 0: invalid start byte
```

## Java error logs
```
11:52:52.213 [main] DEBUG com.amazonaws.AmazonWebServiceClient - Internal logging successfully configured to commons logger: true
11:52:52.752 [main] INFO LocalKinesisReader - Listing streams....
11:52:52.886 [main] DEBUG com.amazonaws.metrics.AwsSdkMetrics - Admin mbean registered under com.amazonaws.management:type=AwsSdkMetrics
11:52:52.981 [main] DEBUG com.amazonaws.request - Sending Request: POST http://localhost:4568 / Headers: (User-Agent: aws-sdk-java/1.11.259 Mac_OS_X/10.13.2 Java_HotSpot(TM)_64-Bit_Server_VM/25.74-b02 java/1.8.0_74, amz-sdk-invocation-id: ---, Content-Length: 2, X-Amz-Target: Kinesis_20131202.ListStreams, Content-Type: application/x-amz-cbor-1.1, ) 
11:52:53.062 [main] DEBUG com.amazonaws.auth.AWS4Signer - AWS4 Canonical Request: '"POST
/

amz-sdk-invocation-id:---
amz-sdk-retry:0/0/500
content-length:2
content-type:application/x-amz-cbor-1.1
host:localhost:4568
user-agent:aws-sdk-java/1.11.259 Mac_OS_X/10.13.2 Java_HotSpot(TM)_64-Bit_Server_VM/25.74-b02 java/1.8.0_74
x-amz-date:20180131T165252Z
x-amz-target:Kinesis_20131202.ListStreams

amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-target
---"
11:52:53.062 [main] DEBUG com.amazonaws.auth.AWS4Signer - AWS4 String to Sign: '"AWS4-HMAC-SHA256
20180131T165252Z
20180131/us-east-1/kinesis/aws4_request
---"
11:52:53.076 [main] DEBUG com.amazonaws.auth.AWS4Signer - Generating a new signing key as the signing key not available in the cache for the date 1517356800000
11:52:53.250 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: default
11:52:53.259 [main] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
11:52:53.260 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://localhost:4568][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
11:52:53.276 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {}->http://localhost:4568][total kept alive: 0; route allocated: 1 of 50; total allocated: 1 of 50]
11:52:53.278 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Opening connection {}->http://localhost:4568
11:52:53.281 [main] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connecting to localhost/127.0.0.1:4568
11:52:53.287 [main] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connection established 127.0.0.1:50251<->127.0.0.1:4568
11:52:53.288 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 50000
11:52:53.288 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Executing request POST / HTTP/1.1
11:52:53.288 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
11:52:53.291 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> POST / HTTP/1.1
11:52:53.291 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Host: localhost:4568
11:52:53.291 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Authorization: AWS4-HMAC-SHA256 Credential=test/20180131/us-east-1/kinesis/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-target, Signature=---
11:52:53.291 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> X-Amz-Date: 20180131T165252Z
11:52:53.291 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: aws-sdk-java/1.11.259 Mac_OS_X/10.13.2 Java_HotSpot(TM)_64-Bit_Server_VM/25.74-b02 java/1.8.0_74
11:52:53.291 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> amz-sdk-invocation-id: 1341be32-b832-42c0-2d72-db430d85658b
11:52:53.291 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> amz-sdk-retry: 0/0/500
11:52:53.292 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> X-Amz-Target: Kinesis_20131202.ListStreams
11:52:53.292 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Type: application/x-amz-cbor-1.1
11:52:53.292 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Length: 2
11:52:53.292 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
11:52:53.293 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "POST / HTTP/1.1[\r][\n]"
11:52:53.293 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: localhost:4568[\r][\n]"
11:52:53.293 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=test/20180131/us-east-1/kinesis/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-target, Signature=---[\r][\n]"
11:52:53.293 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "X-Amz-Date: 20180131T165252Z[\r][\n]"
11:52:53.293 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: aws-sdk-java/1.11.259 Mac_OS_X/10.13.2 Java_HotSpot(TM)_64-Bit_Server_VM/25.74-b02 java/1.8.0_74[\r][\n]"
11:52:53.293 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "amz-sdk-invocation-id: ---[\r][\n]"
11:52:53.293 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "amz-sdk-retry: 0/0/500[\r][\n]"
11:52:53.293 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "X-Amz-Target: Kinesis_20131202.ListStreams[\r][\n]"
11:52:53.293 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Type: application/x-amz-cbor-1.1[\r][\n]"
11:52:53.293 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Length: 2[\r][\n]"
11:52:53.293 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
11:52:53.293 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
11:52:53.293 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[0xbf][0xff]"
11:52:53.296 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 502 Bad Gateway[\r][\n]"
11:52:53.297 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Server: BaseHTTP/0.3 Python/2.7.13[\r][\n]"
11:52:53.297 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Date: Wed, 31 Jan 2018 16:52:56 GMT[\r][\n]"
11:52:53.297 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
11:52:53.301 [main] DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 502 Bad Gateway
11:52:53.302 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Server: BaseHTTP/0.3 Python/2.7.13
11:52:53.302 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Date: Wed, 31 Jan 2018 16:52:56 GMT
11:53:43.311 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[read] I/O error: Read timed out"
11:53:43.311 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
11:53:43.313 [main] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection discarded
11:53:43.313 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://localhost:4568][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
11:53:43.316 [main] INFO com.amazonaws.protocol.json.JsonContent - Unable to read HTTP response content
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:84)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:198)
	at org.apache.http.impl.io.IdentityInputStream.read(IdentityInputStream.java:93)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:148)
	at com.amazonaws.util.IOUtils.toByteArray(IOUtils.java:44)
	at com.amazonaws.protocol.json.JsonContent.createJsonContent(JsonContent.java:48)
	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:61)
	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:33)
	at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:50)
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:38)
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:24)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1621)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2219)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2195)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.executeListStreams(AmazonKinesisClient.java:1249)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.listStreams(AmazonKinesisClient.java:1225)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.listStreams(AmazonKinesisClient.java:1261)
	at LocalKinesisReader.main(LocalKinesisReader.java:26)
```

**Comment by whummer** [comment]
Thanks for reporting @warabak . Please refer to the [Troubleshooting section](https://github.com/localstack/localstack#troubleshooting) in the README:

> If you're using AWS Java libraries with Kinesis, please, refer to CBOR protocol issues with the Java SDK guide how to disable CBOR protocol which is not supported by kinesalite.

See also how we set the `AWS_CBOR_DISABLE` environment variable in our tests:
https://github.com/localstack/localstack/blob/e479afa41df908305c4177276237925accc77e10/localstack/ext/java/src/test/java/cloud/localstack/BasicFunctionalityTest.java#L54

Hope that helps.

**Comment by sivaprasadreddy** [comment]
For me setting the following env variable worked.

`System.setProperty("com.amazonaws.sdk.disableCbor", "true");`

**Comment by sharmaritesh** [comment]
I was using the SDK v2 and faced the same issue and found the flag which SDK uses is `aws.cborEnabled` . Refer to class `software.amazon.awssdk.core.SdkSystemSetting`.

**Comment by eduardompinto** [comment]
Thanks for this :) 
Helped me to solve my problem.
