### ISSUE TITLE
bug: Can't add `_custom_id_` tag using CDK

### ISSUE THREAD

**Issue by mikestopcontinues** [localstack/localstack#5926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to add a `_custom_id_` tag to my RestApi construct in CDK for a static api endpoint.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

This is my best guess for how to add the tag:

```ts
Tags.of(new RestApi(...)).add('_custom_id_', 'myapi');
```

But it doesn't seem to get added. Or rather, I still can't access my API at a static location.

### Environment

```markdown
- OS: OSX 12.3.1
- LocalStack: 0.14.2.3
- CDK: 2.x
```

### Anything else?

I'm also finding it impossible to access my API at the local address, with or without the static id. I'm definitely using api-gateway v1.

**Comment by whummer** [comment]
Hi @mikestopcontinues, thanks for reporting. Can you please share a minimal working example to reproduce your use case? That would be very helpful and will allow us to address your request more efficiently. Thanks!

**Comment by pinzon** [comment]
Hi @mikestopcontinues, I'm closing this issue due it seems like an usage problem. For an Apigateway.RestApi to be deployed, needs to have at least one method. And the tags are being created.


Here's the code I use to test this problem:
```typescript
import { Stack, StackProps, Tags } from 'aws-cdk-lib';
import { RestApi } from 'aws-cdk-lib/aws-apigateway';
import { Construct } from 'constructs';

export class TestStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const restapi = new RestApi(this, "test", {
      restApiName: 'Example api'
    })

    restapi.root.addMethod('GET')
    Tags.of(restapi).add('_custom_id_', 'my_api')
  }
}
```
And these are the Logs from LocalStack:
```logs
2022-05-13T12:11:18.790:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "IAM::Role" in region us-east-1: create_role {'AssumeRolePolicyDocument': '{"Statement": [{"Action": "sts:AssumeRole", "Effect": "Allow", "Principal": {"Service": "apigateway.amazonaws.com"}}], "Version": "2012-10-17"}', 'Tags': [{'Key': '_custom_id_', 'Value': 'my_api'}], 'RoleName': 'TestStack-testCloudWatchRoleA75779-56cf0705'}
2022-05-13T12:11:19.071:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: ApiGateway::Deployment Ref
2022-05-13T12:11:19.102:DEBUG:localstack.services.cloudformation.provider: Unable to resolve references in stack outputs: {'Value': {'Fn::Join': ['', ['https://', {'Ref': 'testAF53AC38'}, '.execute-api.', {'Ref': 'AWS::Region'}, '.', {'Ref': 'AWS::URLSuffix'}, '/', {'Ref': 'testDeploymentStageprodA2EB4366'}, '/']]}} - Unable to fetch details for resource "testDeployment7D7F980740c14cb72f39aad92f96d481ad95d2c2" (attribute "Ref")
2022-05-13T12:11:19.151:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "testAccount14B58214" (1/5) type "AWS::ApiGateway::Account" in loop iteration 1 (should_deploy=False)
2022-05-13T12:11:19.197:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "testDeployment7D7F980740c14cb72f39aad92f96d481ad95d2c2" (1/4) type "AWS::ApiGateway::Deployment" in loop iteration 1 (should_deploy=True)
2022-05-13T12:11:19.269:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: ApiGateway::RestApi RootResourceId
2022-05-13T12:11:19.295:DEBUG:localstack.utils.cloudformation.template_deployer: Dependency for resource {'Type': 'AWS::ApiGateway::Deployment', 'DependsOn': ['testGET854B1EC3'], 'Metadata': {'aws:cdk:path': 'TestStack/test/Deployment/Resource'}, 'LogicalResourceId': 'testDeployment7D7F980740c14cb72f39aad92f96d481ad95d2c2', 'Properties': {'RestApiId': '774tsg7fsq', 'Description': 'Automatically created by the RestApi construct'}, '_state_': {}} not yet deployed: testGET854B1EC3 {'Type': 'AWS::ApiGateway::Method', 'Properties': {'HttpMethod': 'GET', 'ResourceId': {'Fn::GetAtt': ['testAF53AC38', 'RootResourceId']}, 'RestApiId': {'Ref': 'testAF53AC38'}, 'AuthorizationType': 'NONE', 'Integration': {'Type': 'MOCK'}}, 'Metadata': {'aws:cdk:path': 'TestStack/test/Default/GET/Resource'}, 'LogicalResourceId': 'testGET854B1EC3'}
2022-05-13T12:11:19.354:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: ApiGateway::Deployment Ref
2022-05-13T12:11:19.372:DEBUG:localstack.utils.cloudformation.template_deployer: Dependencies for "testDeploymentStageprodA2EB4366" not yet satisfied, retrying in next loop: Unable to fetch details for resource "testDeployment7D7F980740c14cb72f39aad92f96d481ad95d2c2" (attribute "Ref")
2022-05-13T12:11:19.411:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: ApiGateway::RestApi RootResourceId
2022-05-13T12:11:19.489:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "testGET854B1EC3" (3/4) type "AWS::ApiGateway::Method" in loop iteration 1 (should_deploy=True)
2022-05-13T12:11:19.507:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "ApiGateway::Method" id "testGET854B1EC3"
2022-05-13T12:11:19.518:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "ApiGateway::Method" in region us-east-1: put_method {'restApiId': '774tsg7fsq', 'resourceId': 'fbvfjsl2a7', 'httpMethod': 'GET', 'authorizationType': 'NONE'}
2022-05-13T12:11:20.088:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
2022-05-13T12:11:20.523:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "CDKMetadata" (3/3) type "AWS::CDK::Metadata" in loop iteration 1 (should_deploy=False)
2022-05-13T12:11:20.567:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "testDeployment7D7F980740c14cb72f39aad92f96d481ad95d2c2" (1/2) type "AWS::ApiGateway::Deployment" in loop iteration 2 (should_deploy=True)
2022-05-13T12:11:20.602:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "ApiGateway::Deployment" id "testDeployment7D7F980740c14cb72f39aad92f96d481ad95d2c2"
2022-05-13T12:11:20.607:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "ApiGateway::Deployment" in region us-east-1: create_deployment {'restApiId': '774tsg7fsq', 'description': 'Automatically created by the RestApi construct'}
2022-05-13T12:11:20.714:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "testDeploymentStageprodA2EB4366" (1/1) type "AWS::ApiGateway::Stage" in loop iteration 2 (should_deploy=True)
2022-05-13T12:11:20.746:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "ApiGateway::Stage" id "testDeploymentStageprodA2EB4366"
2022-05-13T12:11:20.760:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "ApiGateway::Stage" in region us-east-1: create_stage {'restApiId': '774tsg7fsq', 'deploymentId': 'v1v8l0r9cn', 'tags': {'_custom_id_': 'my_api'}, 'stageName': 'prod'}
```

If you think that is not the case, please provide more info to replicate the situation, like your code and logs, and I'll reopen the Issue.

**Comment by mikestopcontinues** [comment]
I'm sorry I didn't get back to you sooner, but thank you. I was just able to circle back to the project today. I'll give it a go. Thanks!

**Comment by mikestopcontinues** [comment]
@pinzon I discovered an interesting wrinkle in this issue. There's definitely something wrong here.

Previously, I was deploying with `cdklocal deploy --watch`, which seems to deploy without error—but was causing the above issue. However, when testing today with `cdklocal deploy`, I'm unable to deploy, receiving the below error.

With a fresh localstack instance, disabling the tag line, it deploys fine. Any ideas what's going on here?

```
2022-05-13T20:11:18.770:WARNING:localstack.utils.cloudformation.template_deployer: Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.APIGateway object at 0x7fd962840fa0>> with params: {'domainName': 'api.dev.sitearcade.com', 'endpointConfiguration': {'types': ['REGIONAL']}, 'regionalCertificateArn': 'arn:aws:acm:us-east-1:000000000000:certificate/85b24330-e4c7-45b6-a23c-d56e759f7a95', 'tags': [{'key': '_custom_id_', 'value': 'arc-api'}]} for resource: {'Type': 'AWS::ApiGateway::DomainName', 'Metadata': {'aws:cdk:path': 'ArcApi/ArcApi/ApiDomainName/Resource'}, 'LogicalResourceId': 'ArcApiApiDomainName3BA9B9E5', 'Properties': {'DomainName': 'api.dev.sitearcade.com', 'EndpointConfiguration': {'types': ['REGIONAL']}, 'RegionalCertificateArn': 'arn:aws:acm:us-east-1:000000000000:certificate/85b24330-e4c7-45b6-a23c-d56e759f7a95', 'Tags': [{'key': '_custom_id_', 'value': 'arc-api'}]}, '_state_': {}}
2022-05-13T20:11:18.771:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "ArcApi": Parameter validation failed:
Invalid type for parameter tags, value: [{'key': '_custom_id_', 'value': 'arc-api'}], type: <class 'list'>, valid types: <class 'dict'> Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1529, in _run
    self.do_apply_changes_in_loop(changes, stack, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1601, in do_apply_changes_in_loop
    self.apply_change(change, stack=stack)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1667, in apply_change
    result = deploy_resource(self, resource_id)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 844, in deploy_resource
    result = execute_resource_action(resource_id, stack, ACTION_CREATE)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 885, in execute_resource_action
    result = configure_resource_via_sdk(
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1018, in configure_resource_via_sdk
    raise e
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1008, in configure_resource_via_sdk
    result = function(**params)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 874, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 935, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter tags, value: [{'key': '_custom_id_', 'value': 'arc-api'}], type: <class 'list'>, valid types: <class 'dict'>
```

Some versions for additional context...

```
┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Runtime version ┃ 0.14.2                                                ┃
│ Docker image    │ tag: latest, id: d2866f561145, 📆 2022-05-13T18:33:35 │
│ Runtime status  │ ✔ running (name: "localstack_main", IP: 172.17.0.2)   │
└─────────────────┴───────────────────────────────────────────────────────┘
```

```
    "aws-cdk": "2.24.0",
    "aws-cdk-lib": "2.24.0",
    "aws-cdk-local": "2.15.0",
```

**Comment by pinzon** [comment]
@mikestopcontinues , could you provide your exact code? 
I just re-deployed my code from above using the cdk versions you specified, and both `deploy` and `deploy --watch` work.
What language are you using?

**Comment by mikestopcontinues** [comment]
All TS with Node 14.x. Would my cloudformation templates help any? To my eye, they don't say anything meaningful—tags there when I `synth` with, and without without.

**Comment by mikestopcontinues** [comment]
@pinzon I found the issue. In the following example, if you disable either the tag OR the `api.addDomainName()`, the stack will deploy. I think this still counts as a bug, or at least worthy of documentation. 

Ideally localstack should accept the same stacks or CF templates as prod, even if it doesn't use certain structs. E.G., I know I'm not going to get a custom domain in this env—but I would rather not fill templates with increasingly complex conditionals. I hit a similar issue with auto-scaling config on lambda funcs.

What do you think?

```ts
// import

import {Construct} from 'constructs';
import {App, StackProps, Tags, Stack} from 'aws-cdk-lib';
import * as API from 'aws-cdk-lib/aws-apigateway';
import * as CM from 'aws-cdk-lib/aws-certificatemanager';

// structs

export class ErrStack extends Stack {
  constructor(scope: Construct, props: StackProps) {
    super(scope, 'ErrStack', props);

    const api = new API.RestApi(this, 'Api', {
      restApiName: 'Api',
    });

    api.root.addMethod('ANY');
    Tags.of(api).add('_custom_id_', 'api');

    api.addDomainName('ApiDomainName', {
      domainName: 'example.com',
      certificate: new CM.Certificate(this, 'ApiCert', {
        domainName: 'example.com',
        subjectAlternativeNames: [`*.example.com`],
      }),
    });
  }
}

// synth

const app = new App();
new ErrStack(app, {});
```

**Comment by mikestopcontinues** [comment]
Also, the initial problem still stands. I can access the API using the generated ID, via either URL format, but I can't access it using the value of `_custom_id_` instead.

**Comment by pinzon** [comment]
@mikestopcontinues thanks for the info. I'll see what I can do about it.

**Comment by pinzon** [comment]
Hi @mikestopcontinues, the code you provide really showed me what's the problem with Localstack. It seems that when you add tags to the API, CDK also adds it to the DomainName and Localstack is not supporting it right now. 

I already have a solution but before I make a Pull Request, I'm trying to fix a problem with another CFN model that emerged after fixing this one.

**Comment by mikestopcontinues** [comment]
Thanks @pinzon. I'm glad I could help. I'll keep my eyes peeled, but I at least I can use the UID url for now. :)

**Comment by pinzon** [comment]
The solution to this issue has been merged. Thank you for reporting it @mikestopcontinues.
