### ISSUE TITLE
Cannot run, issue -  RuntimeException

### ISSUE THREAD

**Issue by tzvetkovg** [localstack/localstack#593]
I've tried testing localstack using the following java test

```
@RunWith(LocalstackTestRunner.class)
public class DoATest {

  public static final String TEST_ACCESS_KEY = "test";
  public static final String TEST_SECRET_KEY = "test";
  public static final AWSCredentials TEST_CREDENTIALS = new BasicAWSCredentials(TEST_ACCESS_KEY, TEST_SECRET_KEY);

  @Test
  public void testLocalS3API() {
    AmazonS3 s3 = TestUtils.getClientS3();
    List<Bucket> buckets = s3.listBuckets();
  }

}

```
my pom.xml has the following dependencies

```
 <dependencies>
    <dependency>
      <groupId>cloud.localstack</groupId>
      <artifactId>localstack-utils</artifactId>
      <version>0.1.9</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-s3 -->
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-s3</artifactId>
      <version>1.11.271</version>
    </dependency>

  </dependencies>

```
And I am getting the error without anything else

```
java.lang.RuntimeException: java.lang.IllegalStateException: Failed to run command 'bash -c cd "/tmp/localstack_install_dir"; make install', return code 2.
STDOUT: (test `which virtualenv` || pip install --user virtualenv) && \
	(test -e .venv || virtualenv  .venv) && \
	(. .venv/bin/activate && pip -q install --upgrade pip) && \
	(test ! -e requirements.txt || (. .venv/bin/activate; pip install -q six==1.10.0 ; pip -q install -r requirements.txt) && \
	. .venv/bin/activate; PYTHONPATH=. exec python localstack/services/install.py testlibs)
Makefile:13: recipe for target 'install' failed

STDERR:   Could not find a version that satisfies the requirement backports.tempfile; python_version < "3.3" (from moto-ext==1.1.25.3->-r requirements.txt (line 20)) (from versions: )
No matching distribution found for backports.tempfile; python_version < "3.3" (from moto-ext==1.1.25.3->-r requirements.txt (line 20))
Traceback (most recent call last):
  File "localstack/services/install.py", line 9, in <module>
    from localstack.constants import (DEFAULT_SERVICE_PORTS, ELASTICMQ_JAR_URL, STS_JAR_URL,
  File "/tmp/localstack_install_dir/localstack/constants.py", line 2, in <module>
    import localstack_client.config
ImportError: No module named localstack_client.config
make: *** [install] Error 1

	at cloud.localstack.LocalstackTestRunner.exec(LocalstackTestRunner.java:233)
	at cloud.localstack.LocalstackTestRunner.exec(LocalstackTestRunner.java:202)
	at cloud.localstack.LocalstackTestRunner.ensureInstallation(LocalstackTestRunner.java:154)
	at cloud.localstack.LocalstackTestRunner.setupInfrastructure(LocalstackTestRunner.java:240)
	at cloud.localstack.LocalstackTestRunner.run(LocalstackTestRunner.java:128)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalStateException: Failed to run command 'bash -c cd "/tmp/localstack_install_dir"; make install', return code 2.
STDOUT: (test `which virtualenv` || pip install --user virtualenv) && \
	(test -e .venv || virtualenv  .venv) && \
	(. .venv/bin/activate && pip -q install --upgrade pip) && \
	(test ! -e requirements.txt || (. .venv/bin/activate; pip install -q six==1.10.0 ; pip -q install -r requirements.txt) && \
	. .venv/bin/activate; PYTHONPATH=. exec python localstack/services/install.py testlibs)
Makefile:13: recipe for target 'install' failed

STDERR:   Could not find a version that satisfies the requirement backports.tempfile; python_version < "3.3" (from moto-ext==1.1.25.3->-r requirements.txt (line 20)) (from versions: )
No matching distribution found for backports.tempfile; python_version < "3.3" (from moto-ext==1.1.25.3->-r requirements.txt (line 20))
Traceback (most recent call last):
  File "localstack/services/install.py", line 9, in <module>
    from localstack.constants import (DEFAULT_SERVICE_PORTS, ELASTICMQ_JAR_URL, STS_JAR_URL,
  File "/tmp/localstack_install_dir/localstack/constants.py", line 2, in <module>
    import localstack_client.config
ImportError: No module named localstack_client.config
make: *** [install] Error 1

	at cloud.localstack.LocalstackTestRunner.exec(LocalstackTestRunner.java:220)
	... 9 more
```

I have python installed. When I start localstack from command line it works fine..any ideas?

**Comment by whummer** [comment]
Thanks for reporting @tzvetkovg . Can you please post the output of the following commands:
```
python --version
bash -c 'python --version'
```
Also, there are two ways of running LocalStack on the command line:

1. Using pip install:
```
pip install localstack
localstack start
```

2. By cloning the repo and running from source:
```
git clone https://github.com/localstack/localstack
cd localstack
make install
make infra
```

Can you confirm that both methods work for you?

**Comment by whummer** [comment]
Closing due to inactivity.
