### ISSUE TITLE
bug: Cannot delete stack 

### ISSUE THREAD

**Issue by jamieforrest** [localstack/localstack#5949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to delete a local stack using `samlocal delete`, I get the following error trace:

```
samlocal delete
	Are you sure you want to delete the stack [XXXXXX] in the region us-east-1 ? [y/N]: y
Traceback (most recent call last):
  File "/opt/homebrew/bin/samlocal", line 41, in <module>
    main.cli()
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/samcli/cli/main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/samcli/commands/delete/command.py", line 77, in cli
    do_cli(
  File "/opt/homebrew/lib/python3.9/site-packages/samcli/commands/delete/command.py", line 101, in do_cli
    delete_context.run()
  File "/opt/homebrew/lib/python3.9/site-packages/samcli/commands/delete/delete_context.py", line 345, in run
    is_deployed = self.cf_utils.has_stack(stack_name=self.stack_name)
  File "/opt/homebrew/lib/python3.9/site-packages/samcli/lib/delete/cfn_utils.py", line 33, in has_stack
    if stack["EnableTerminationProtection"]:
KeyError: 'EnableTerminationProtection'
```

### Expected Behavior

Expected to be able to delete the stack.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
    export LOCALSTACK_API_KEY=[XXXXXX]
    localstack start

### Environment

```markdown
- OS: macOS 12.3.1
- LocalStack: 0.14.1.3
```

**Comment by dfangl** [comment]
Hi! This issue should be resolved with #6584.
The fix is available with `localstack/localstack:latest`!
Thanks for reporting this!
