### ISSUE TITLE
bug: Cloudformation failed to deploy

### ISSUE THREAD

**Issue by ellisium** [localstack/localstack#5961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, 

I'm trying to deploy a new stack on cloudformation composed with nested stacks.

### Expected Behavior

Deploy my new stack on localstack cloudformation

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

step to reproduce:

npm install -g aws-cdk-local aws-cdk@1.95.0 

start localstack via docker-compose:
`version: "3.8"
services:
localstack:
container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
image: localstack/localstack:latest
ports:
- "127.0.0.1:4510-4559:4510-4559" # external service port range
- "127.0.0.1:4566:4566" # LocalStack Edge Proxy
environment:
- DEBUG=1
- DATA_DIR=${DATA_DIR-}
- LAMBDA_EXECUTOR=local
- LAMBDA_REMOTE_DOCKER=0
- HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
- AWS_SECRET_ACCESS_KEY=local
- DOCKER_HOST=unix:///var/run/docker.sock
volumes:
- "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
- "/var/run/docker.sock:/var/run/docker.sock"`

CDK part:

Boostrap: AWS creds locally cdklocal bootstrap (default aws profile) or cdklocal bootstrap --profile profileName

Deploy: cdklocal deploy --outputs-file config.json

Error stack:
localstack_main | 2022-04-29T07:13:10.946:DEBUG:localstack.services.cloudformation.cloudformation_api: Executing change set "cdk-deploy-change-set" for stack "xxx-platform-local" with 10 resources ... localstack_main | 2022-04-29T07:13:36.221:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['appNestedStackappNestedStackResource9524848D', 'Outputs.xxxplatformlocalappstaticsitebucket9264F310Ref']}} - Unable to fetch details for resource "appNestedStackappNestedStackResource9524848D" (resolving attribute "Outputs.xxxplatformlocalappstaticsitebucket9264F310Ref") localstack_main | 2022-04-29T07:13:36.285:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref localstack_main | 2022-04-29T07:13:36.401:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref localstack_main | 2022-04-29T07:13:36.482:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['graphqlNestedStackgraphqlNestedStackResource6CA1E289', 'Outputs.xxxplatformlocalgraphqlcustomdata034612EFRef']}} - Unable to fetch details for resource "graphqlNestedStackgraphqlNestedStackResource6CA1E289" (resolving attribute "Outputs.xxxplatformlocalgraphqlcustomdata034612EFRef") localstack_main | 2022-04-29T07:13:36.576:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref localstack_main | 2022-04-29T07:13:36.609:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "xxx-platform-local": list index out of range Traceback (most recent call last): localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1529, in _run localstack_main | self.do_apply_changes_in_loop(changes, stack, stack_name) localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1580, in do_apply_changes_in_loop localstack_main | should_deploy = self.prepare_should_deploy_change( localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1639, in prepare_should_deploy_change localstack_main | resolve_refs_recursively(stack, resource) localstack_main | File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func localstack_main | return wrapped(*args, **kwargs) localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 479, in resolve_refs_recursively localstack_main | result = _resolve_refs_recursively(stack, value) localstack_main | File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func localstack_main | return wrapped(*args, **kwargs) localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 675, in _resolve_refs_recursively localstack_main | value[key] = resolve_refs_recursively(stack, val) localstack_main | File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func localstack_main | return wrapped(*args, **kwargs) localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 479, in resolve_refs_recursively localstack_main | result = _resolve_refs_recursively(stack, value) localstack_main | File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func localstack_main | return wrapped(*args, **kwargs) localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 675, in _resolve_refs_recursively localstack_main | value[key] = resolve_refs_recursively(stack, val) localstack_main | File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func localstack_main | return wrapped(*args, **kwargs) localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 479, in resolve_refs_recursively localstack_main | result = _resolve_refs_recursively(stack, value) localstack_main | File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func localstack_main | return wrapped(*args, **kwargs) localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 570, in _resolve_refs_recursively localstack_main | join_values = [resolve_refs_recursively(stack, v) for v in join_values] localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 570, in <listcomp> localstack_main | join_values = [resolve_refs_recursively(stack, v) for v in join_values] localstack_main | File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func localstack_main | return wrapped(*args, **kwargs) localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 479, in resolve_refs_recursively localstack_main | result = _resolve_refs_recursively(stack, value) localstack_main | File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func localstack_main | return wrapped(*args, **kwargs) localstack_main | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 653, in _resolve_refs_recursively localstack_main | return values[index] localstack_main | IndexError: list index out of range localstack_main | localstack_main | 2022-04-29T07:13:36.728:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['apiNestedStackapiNestedStackResourceDFDE5E1E', 'Outputs.xxxplatformlocalapitooling1AB6E167Ref']}} - Unable to fetch details for resource "apiNestedStackapiNestedStackResourceDFDE5E1E" (resolving attribute "Outputs.xxxplatformlocalapitooling1AB6E167Ref") localstack_main | 2022-04-29T07:13:41.892:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['appNestedStackappNestedStackResource9524848D', 'Outputs.xxxplatformlocalappstaticsitebucket9264F310Ref']}} - Unable to fetch details for resource "appNestedStackappNestedStackResource9524848D" (resolving attribute "Outputs.xxxplatformlocalappstaticsitebucket9264F310Ref") localstack_main | 2022-04-29T07:13:41.939:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['graphqlNestedStackgraphqlNestedStackResource6CA1E289', 'Outputs.xxxplatformlocalgraphqlcustomdata034612EFRef']}} - Unable to fetch details for resource "graphqlNestedStackgraphqlNestedStackResource6CA1E289" (resolving attribute "Outputs.xxxplatformlocalgraphqlcustomdata034612EFRef") localstack_main | 2022-04-29T07:13:41.993:DEBUG:localstack.services.cloudformation.cloudformation_api: Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['apiNestedStackapiNestedStackResourceDFDE5E1E', 'Outputs.xxxplatformlocalapitooling1AB6E167Ref']}} - Unable to fetch details for resource "apiNestedStackapiNestedStackResourceDFDE5E1E" (resolving attribute "Outputs.xxxplatformlocalapitooling1AB6E167Ref")

This kind of errors Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['appNestedStackappNestedStackResource9524848D', 'Outputs.xxxplatformlocalappstaticsitebucket9264F310Ref']}} - Unable to fetch details for resource "appNestedStackappNestedStackResource9524848D" (resolving attribute "Outputs.xxxplatformlocalappstaticsitebucket9264F310Ref")
=> https://github.com/xxx-insurance/xxx-platform/blob/main/packages/deploy/src/stacks/platform_stack.ts#L165

CfnOutput generate this section in cdk.out xxx.template.json
"Outputs": { "apiUrl": { "Value": "platform-local-api.xxx.eu" }, "graphQLApiUrl": { "Value": "platform-local-graphql.xxx.eu" }, "appBucket": { "Value": { "Fn::GetAtt": [ "appNestedStackappNestedStackResource9524848D", "Outputs.xxxplatformlocalappstaticsitebucket9264F310Ref" ] } }, "graphqlCustomDataBucketName": { "Value": { "Fn::GetAtt": [ "graphqlNestedStackgraphqlNestedStackResource6CA1E289", "Outputs.xxxplatformlocalgraphqlcustomdata034612EFRef" ] } }, "apiToolingFunctionName": { "Value": { "Fn::GetAtt": [ "apiNestedStackapiNestedStackResourceDFDE5E1E", "Outputs.xxxplatformlocalapitooling1AB6E167Ref" ] } } },

### Environment

```markdown
- OS: centos 8
- LocalStack: lastest
```

**Comment by ellisium** [comment]
Migration to CDK V2 seems to fix partially this issue. cdklocal deploy command run successfully however still issue related to the CfnOutput 

`    new CfnOutput(this, 'apiUrl', {
      value: this.api.domain.name,
    });

    new CfnOutput(this, 'graphQLApiUrl', {
      value: this.graphql.domain.name,
    });`

domain.name refering to 
`import {
  CorsHttpMethod,
  DomainName,
  HttpApi,
  HttpMethod,
} from '@aws-cdk/aws-apigatewayv2-alpha';

this.domain = new DomainName(this, 'domain', {
      domainName,
      certificate: Certificate.fromCertificateArn(
        this,
        'certificate',
        props.certificateArn,
      ),
    });`

same with `new CfnOutput(this, 'apiToolingFunctionName', {
      value: this.api.functions.tooling?.functionName || '',
    });` referencing lambda function

**Comment by lukqw** [comment]
Hi @ellisium!
I played around with your example a bit and found the following:

```
# environment
aws-cdk: 2.24.1
aws-cdk-lib: 2.24.1
OS: windows 10 + WSL2
LocalStack: 0.14.2
```

```
import { CfnOutput } from 'aws-cdk-lib';
import { DomainName } from 'aws-cdk-lib/aws-apigateway';
import { Certificate } from 'aws-cdk-lib/aws-certificatemanager';

    const domain = new DomainName(this, 'domain', {
      domainName: "test",
      certificate: Certificate.fromCertificateArn(
        this,
        'certificate',
        ""
      ),
    });

    new CfnOutput(this, 'apiUrl', {
      value: domain.name, <<<<<<<< should be domain.domainName
    });
```

Looks like you are trying to access a non-existent field `domain.name` instead of `domain.domainName`

Could you try to fix this reference in your code and report back?
Regarding your problem with the lambda function I would kindly ask you to provide more code, similar to the domain example, as it is hard to pinpoint the root of error for this example.
Also, if you could include your CDK version It would greatly aid me in reproducing your error.

**Comment by ellisium** [comment]
@lukqw name is = domainName used by class instanciation extending IDomainName. It's working on awscloud but not via localstack. I tried with basic string and it doesn't work as well

with bucket it's ok : 
`new CfnOutput(this, 'subscriptionAppBucket', {
      value: this.subscription.site.bucket.bucketName,
    });`

`Outputs:
seyna-platform-localstack-cdk-v2.apiToolingFunctionName = undefined
seyna-platform-localstack-cdk-v2.apiUrl = undefined
seyna-platform-localstack-cdk-v2.appBucket = seyna-platform-localstack-cdk-staticsitebuckete0cc210f-c745632a
seyna-platform-localstack-cdk-v2.graphQLApiUrl = undefined
seyna-platform-localstack-cdk-v2.graphqlCustomDataBucketName = seyna-platform-localstack-cdk-graph-customdata8889cb63-29bfbef0
seyna-platform-localstack-cdk-v2.subscriptionAppBucket = seyna-platform-localstack-cdk-generatorsitebucket87e6a-ac918cb9`

Is it a limitation on free version? I see ApiGateway V2 is under pro version?

**Comment by ellisium** [comment]
if hardcoding value, it's working as expected, it looks like a gap between nodejs execution on our pipeline runner and local execution.

Thx for support
