### ISSUE TITLE
bug: Localstack in multi account mode doesn't work properly

### ISSUE THREAD

**Issue by raulsh** [localstack/localstack#5966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The command that I used to start Localstack is:
`TEST_AWS_ACCOUNT_ID=000000000001,000000000002 SERVICES=s3 LOCALSTACK_API_KEY=XXXXXXX DEBUG=1 localstack start`

This is the specific error when I try to create S3 bucket in "multi account" mode:

```
AWS_ACCESS_KEY_ID=000000000002 AWS_SECRET_ACCESS_KEY=test aws --endpoint-url=http://localhost:4566 s3 mb s3://bucket-account-two
make_bucket failed: s3://bucket-account-two An error occurred (500) when calling the CreateBucket operation (reached max retries: 2): Internal Server Error
```

```
2022-04-30T16:14:41.878:INFO:localstack.services.infra: Starting mock S3 service on http ports 443/4566 ...
2022-04-30T16:14:41.881:INFO:localstack.services.motoserver: starting moto server on http://0.0.0.0:39483
2022-04-30T16:14:41.882:INFO:localstack.utils.server.http2_server: Error running server event loop on port 4566: [Errno 98] Address already in use Traceback (most recent call last):
File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 252, in run_app_sync
return loop.run_until_complete(serve(app, config, **run_kwargs))
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/__init__.py", line 41, in serve
await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 88, in worker_serve
sockets = config.create_sockets()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/config.py", line 196, in create_sockets
insecure_sockets = self._create_sockets(self.bind)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/config.py", line 259, in _create_sockets
sock.bind(binding)
OSError: [Errno 98] Address already in use

2022-04-30T16:14:41.883:INFO:localstack.utils.threads: Thread run method <bound method run_server.<locals>.ProxyThread.run_proxy of <ProxyThread(Thread-9, started daemon 140036571936512)>>(None) failed: [Errno 98] Address already in use Traceback (most recent call last):
File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
result = self.func(self.params, **kwargs)
File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 292, in run_proxy
run_app_sync(loop=self.loop, shutdown_event=self.shutdown_event)
File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 252, in run_app_sync
return loop.run_until_complete(serve(app, config, **run_kwargs))
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/__init__.py", line 41, in serve
await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 88, in worker_serve
sockets = config.create_sockets()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/config.py", line 196, in create_sockets
insecure_sockets = self._create_sockets(self.bind)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/config.py", line 259, in _create_sockets
sock.bind(binding)
OSError: [Errno 98] Address already in use
```

The startup log (if is neccesary)

```
     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.14.2.4

[12:14:17] starting LocalStack in Docker mode 🐳                                                                    localstack.py:131
2022-04-30T12:14:17.993:DEBUG:stevedore.extension: found extension EntryPoint(name='prepare_host_machine_id', value='localstack.utils.analytics.metadata:prepare_host_machine_id', group='localstack.hooks.prepare_host')
2022-04-30T12:14:17.996:DEBUG:stevedore.extension: found extension EntryPoint(name='activate_pro_key_on_host', value='localstack_ext.plugins:activate_pro_key_on_host', group='localstack.hooks.prepare_host')
2022-04-30T12:14:17.997:ERROR:plugin.manager: error importing entrypoint EntryPoint(name='activate_pro_key_on_host', value='localstack_ext.plugins:activate_pro_key_on_host', group='localstack.hooks.prepare_host'): No module named 'werkzeug'
2022-04-30T12:14:17.997:DEBUG:stevedore.extension: found extension EntryPoint(name='create_dns_forward', value='localstack_ext.plugins:create_dns_forward', group='localstack.hooks.prepare_host')
2022-04-30T12:14:17.997:ERROR:plugin.manager: error importing entrypoint EntryPoint(name='create_dns_forward', value='localstack_ext.plugins:create_dns_forward', group='localstack.hooks.prepare_host'): No module named 'werkzeug'
2022-04-30T12:14:17.997:DEBUG:stevedore.extension: found extension EntryPoint(name='start_ec2_daemon', value='localstack_ext.plugins:start_ec2_daemon', group='localstack.hooks.prepare_host')
2022-04-30T12:14:17.998:ERROR:plugin.manager: error importing entrypoint EntryPoint(name='start_ec2_daemon', value='localstack_ext.plugins:start_ec2_daemon', group='localstack.hooks.prepare_host'): No module named 'werkzeug'
2022-04-30T12:14:17.998:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.prepare_host.prepare_host_machine_id = <function prepare_host_machine_id at 0x7f9cb59aa440>)
2022-04-30T12:14:17.998:DEBUG:plugin.manager: loading plugin localstack.hooks.prepare_host:prepare_host_machine_id
─────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ───────────────────────────────────────────
2022-04-30T12:14:17.999:DEBUG:localstack.utils.container_utils.docker_sdk_client: Listing containers with filters: None
2022-04-30T12:14:18.004:DEBUG:stevedore.extension: found extension EntryPoint(name='configure_edge_port', value='localstack.plugins:configure_edge_port', group='localstack.hooks.configure_localstack_container')
2022-04-30T12:14:18.004:DEBUG:stevedore.extension: found extension EntryPoint(name='configure_pro_container', value='localstack_ext.plugins:configure_pro_container', group='localstack.hooks.configure_localstack_container')
2022-04-30T12:14:18.005:ERROR:plugin.manager: error importing entrypoint EntryPoint(name='configure_pro_container', value='localstack_ext.plugins:configure_pro_container', group='localstack.hooks.configure_localstack_container'): No module named 'werkzeug'
2022-04-30T12:14:18.005:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.configure_localstack_container.configure_edge_port = <function configure_edge_port at 0x7f9cb59c8a60>)
2022-04-30T12:14:18.005:DEBUG:plugin.manager: loading plugin localstack.hooks.configure_localstack_container:configure_edge_port
2022-04-30T12:14:18.005:DEBUG:localstack.plugins: configuring container with edge ports: [4566, 0]
2022-04-30T12:14:18.006:DEBUG:localstack.utils.run: Executing command: which tail
2022-04-30T12:14:18.007:DEBUG:localstack.utils.run: Executing command: ['tail', '-f', '/tmp/localstack/localstack_main_container.log']
2022-04-30T12:14:18.008:DEBUG:localstack.utils.container_utils.docker_sdk_client: Listing containers with filters: None
2022-04-30T12:14:18.011:DEBUG:localstack.utils.container_utils.docker_cmd_client: Run container with cmd: ['docker', 'run', '--rm', '--name', 'localstack_main', '-v', '/tmp/localstack/var_libs:/var/lib/localstack/var_libs', '-v', '/tmp/localstack/cache:/var/lib/localstack/cache', '-v', '/tmp/localstack:/tmp/localstack', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-p', '127.0.0.1:4566:4566', '-p', '127.0.0.1:4510-4559:4510-4559', '-e', 'LOCALSTACK_API_KEY=75MqSbTdzX', '-e', 'SERVICES=s3', '-e', 'TEST_AWS_ACCOUNT_ID=000000000001,000000000002', '-e', 'DEFAULT_REGION=us-east-1', '-e', 'DEBUG=1', '-e', 'DOCKER_HOST=unix:///var/run/docker.sock', '-e', 'HOST_TMP_FOLDER=/tmp/localstack', '-e', 'SET_TERM_HANDLER=1', '--privileged', 'localstack/localstack']
2022-04-30T12:14:18.012:DEBUG:localstack.utils.run: Executing command: ['docker', 'run', '--rm', '--name', 'localstack_main', '-v', '/tmp/localstack/var_libs:/var/lib/localstack/var_libs', '-v', '/tmp/localstack/cache:/var/lib/localstack/cache', '-v', '/tmp/localstack:/tmp/localstack', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-p', '127.0.0.1:4566:4566', '-p', '127.0.0.1:4510-4559:4510-4559', '-e', 'LOCALSTACK_API_KEY=75MqSbTdzX', '-e', 'SERVICES=s3', '-e', 'TEST_AWS_ACCOUNT_ID=000000000001,000000000002', '-e', 'DEFAULT_REGION=us-east-1', '-e', 'DEBUG=1', '-e', 'DOCKER_HOST=unix:///var/run/docker.sock', '-e', 'HOST_TMP_FOLDER=/tmp/localstack', '-e', 'SET_TERM_HANDLER=1', '--privileged', 'localstack/localstack']
Waiting for all LocalStack services to be ready
2022-04-30 16:14:19,135 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-04-30 16:14:19,136 INFO supervisord started with pid 14
2022-04-30 16:14:20,140 INFO spawned: 'infra' with pid 20

LocalStack version: 0.14.2
LocalStack Docker container id: 0b0c3b6dcde3
LocalStack build date: 2022-04-22
LocalStack build git hash: 4b88a7bf

2022-04-30T16:14:20.636:DEBUG:stevedore.extension: found extension EntryPoint(name='register_partition_adjusting_proxy_listener', value='localstack.plugins:register_partition_adjusting_proxy_listener', group='localstack.hooks.on_infra_start')
2022-04-30T16:14:20.636:DEBUG:stevedore.extension: found extension EntryPoint(name='add_custom_edge_routes', value='localstack_ext.plugins:add_custom_edge_routes', group='localstack.hooks.on_infra_start')
2022-04-30T16:14:20.746:DEBUG:stevedore.extension: found extension EntryPoint(name='setup_pro_infra', value='localstack_ext.plugins:setup_pro_infra', group='localstack.hooks.on_infra_start')
2022-04-30T16:14:20.746:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_partition_adjusting_proxy_listener = <function register_partition_adjusting_proxy_listener at 0x7f5cd36274c0>)
2022-04-30T16:14:20.746:DEBUG:plugin.manager: plugin localstack.hooks.on_infra_start:register_partition_adjusting_proxy_listener is disabled
2022-04-30T16:14:20.746:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.on_infra_start.add_custom_edge_routes = <function add_custom_edge_routes at 0x7f5cd32f6ee0>)
2022-04-30T16:14:20.747:DEBUG:plugin.manager: loading plugin localstack.hooks.on_infra_start:add_custom_edge_routes
2022-04-30T16:14:20.747:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.hooks.on_infra_start.setup_pro_infra = <function setup_pro_infra at 0x7f5cd32f24c0>)
2022-04-30T16:14:20.747:DEBUG:plugin.manager: loading plugin localstack.hooks.on_infra_start:setup_pro_infra
2022-04-30T16:14:20.747:DEBUG:localstack_ext.bootstrap.install: Using cached SSL certificate (less than 6hrs since last update).
2022-04-30 16:14:21,748 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-04-30T16:14:21.928:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
2022-04-30T16:14:21.959:DEBUG:localstack.utils.run: Executing command: whoami
2022-04-30T16:14:21.963:DEBUG:localstack.utils.run: Executing command:  python -c "import sys; f=open(sys.argv[1]).read(); open(sys.argv[1], 'w').write('\n' + f)" /etc/resolv.conf
2022-04-30T16:14:21.974:DEBUG:localstack.utils.run: Executing command:  python -c "import sys; f=open(sys.argv[1]).read(); open(sys.argv[1], 'w').write('nameserver 0.0.0.0\n' + f)" /etc/resolv.conf
2022-04-30T16:14:21.986:DEBUG:localstack.utils.run: Executing command:  python -c "import sys; f=open(sys.argv[1]).read(); open(sys.argv[1], 'w').write('# The following line is required by LocalStack\n' + f)" /etc/resolv.conf
Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
Starting edge router (http port 4566)...
Starting edge router (https port 443)...
Traceback (most recent call last):
File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
__import__(pkg_name)
File "/opt/code/localstack/localstack/cli/__init__.py", line 1, in <module>
from .console import console
File "/opt/code/localstack/localstack/cli/console.py", line 1, in <module>
from rich.console import Console
ModuleNotFoundError: No module named 'rich'
Traceback (most recent call last):
File "/usr/local/lib/python3.8/runpy.py", line 185, in _run_module_as_main
mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
File "/usr/local/lib/python3.8/runpy.py", line 111, in _get_module_details
__import__(pkg_name)
File "/opt/code/localstack/localstack/cli/__init__.py", line 1, in <module>
from .console import console
File "/opt/code/localstack/localstack/cli/console.py", line 1, in <module>
from rich.console import Console
ModuleNotFoundError: No module named 'rich'
2022-04-30T16:14:23.663:INFO:localstack_ext.utils.aws.metadata_service: Starting AWS instance metadata service on port 80
2022-04-30T16:14:23.663:DEBUG:localstack_ext.services.edge: Using random service ports for account ID 000000000001: s3
2022-04-30T16:14:23.664:DEBUG:localstack.utils.run: Executing command: ['/usr/local/bin/python3', '-m', 'localstack.cli.main', 'start', '--host']
2022-04-30T16:14:23.666:DEBUG:localstack_ext.services.edge: Using random service ports for account ID 000000000002: s3
2022-04-30T16:14:23.667:DEBUG:localstack.utils.run: Executing command: ['/usr/local/bin/python3', '-m', 'localstack.cli.main', 'start', '--host']
2022-04-30T16:14:23.674:WARNING:localstack.services.internal: Enabling diagnose endpoint, please be aware that this can expose sensitive information via your network.
2022-04-30T16:14:23.675:DEBUG:localstack_ext.bootstrap.install: Using cached SSL certificate (less than 6hrs since last update).
2022-04-30T16:14:23.680:DEBUG:localstack_ext.bootstrap.install: Using cached SSL certificate (less than 6hrs since last update).
[2022-04-30 16:14:23 +0000] [20] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2022-04-30T16:14:23.681:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
[2022-04-30 16:14:23 +0000] [20] [INFO] Running on https://0.0.0.0:443 (CTRL + C to quit)
2022-04-30T16:14:23.686:INFO:hypercorn.error: Running on https://0.0.0.0:443 (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2022-04-30T16:14:41.878:INFO:localstack.services.infra: Starting mock S3 service on http ports 443/4566 ...
2022-04-30T16:14:41.881:INFO:localstack.services.motoserver: starting moto server on http://0.0.0.0:39483
2022-04-30T16:14:41.882:INFO:localstack.utils.server.http2_server: Error running server event loop on port 4566: [Errno 98] Address already in use Traceback (most recent call last):
File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 252, in run_app_sync
return loop.run_until_complete(serve(app, config, **run_kwargs))
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/__init__.py", line 41, in serve
await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 88, in worker_serve
sockets = config.create_sockets()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/config.py", line 196, in create_sockets
insecure_sockets = self._create_sockets(self.bind)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/config.py", line 259, in _create_sockets
sock.bind(binding)
OSError: [Errno 98] Address already in use

2022-04-30T16:14:41.883:INFO:localstack.utils.threads: Thread run method <bound method run_server.<locals>.ProxyThread.run_proxy of <ProxyThread(Thread-9, started daemon 140036571936512)>>(None) failed: [Errno 98] Address already in use Traceback (most recent call last):
File "/opt/code/localstack/localstack/utils/threads.py", line 38, in run
result = self.func(self.params, **kwargs)
File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 292, in run_proxy
run_app_sync(loop=self.loop, shutdown_event=self.shutdown_event)
File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 252, in run_app_sync
return loop.run_until_complete(serve(app, config, **run_kwargs))
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/__init__.py", line 41, in serve
await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 88, in worker_serve
sockets = config.create_sockets()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/config.py", line 196, in create_sockets
insecure_sockets = self._create_sockets(self.bind)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/config.py", line 259, in _create_sockets
sock.bind(binding)
OSError: [Errno 98] Address already in use
```

### Expected Behavior

Localstack, following the documentation, in multi account doesnt work at all for me. Not only with S3.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    TEST_AWS_ACCOUNT_ID=000000000001,000000000002 SERVICES=s3 LOCALSTACK_API_KEY=XXXXXXX DEBUG=1 localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    AWS_ACCESS_KEY_ID=000000000002 AWS_SECRET_ACCESS_KEY=test aws --endpoint-url=http://localhost:4566 s3 mb s3://bucket-account-two

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: latest
```

### Anything else?

I have this problem ONLY with multi account mode. In single account mode Localstack works perfect.

**Comment by whummer** [comment]
Hi @raulsh , thanks for reporting. In the meantime, we have fundamentally reworked the way how multi-account requests are supported in LocalStack - a new version has been released in our version 1.0.0 release. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks!
