### ISSUE TITLE
Step functions and lambda callback pattern

### ISSUE THREAD

**Issue by guillemsola** [localstack/localstack#5989]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I'm trying to call a lambda from a step function locally using the `TaskToken` callback

This is my dockerized file

```docker
version: "3.8"

services:
  localstack:
    image: localstack/localstack
    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=lambda
      - LAMBDA_EXECUTOR=docker
    ports:
      - '4566:4566'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - /tmp/localstack:/tmp/localstack
  stepfunctions:
    container_name: stepfunctions
    image: amazon/aws-stepfunctions-local:latest
    environment:
      - LAMBDA_ENDPOINT=http://localstack:4566
    ports:
      - '8083:8083'
```

Then I have a simple state machine like this

```json
{
  "Comment": "LocalStack example of the Amazon States Language",
  "StartAt": "Pending",
  "TimeoutSeconds": 30,
  "States": {
    "Pending": {
      "Type": "Task",
      "Resource": "arn:aws:states:::lambda:invoke.waitForTaskToken",
      "Parameters": {
        "FunctionName": "helloWorld",
        "Payload": {
          "TaskToken.$": "$$.Task.Token",
          "Input.$": "$"
        }
      },
      "End": true
    }
  }
}
```

And finally a lambda

```js
exports.lambda_handler = async event => {
    const taskToken = event['TaskToken'];
    const stepfunctions = new aws.StepFunctions();

    const params = {
        output: JSON.stringify({ message: "Callback task completed successfully." }),
        taskToken: taskToken
    };

    await stepfunctions.sendTaskSuccess(params).promise();
};
```

When I execute the step function through aws cli the lambda is being executed

I can even see the task token being passed and I return it in the output params `"taskToken":"0136a2f2-91c8-4ab7-9084-3a37835df854"`

But I always end up with this error that is frustrating me

```json
{"errorType":"UnrecognizedClientException","errorMessage":"The security token included in the request is invalid."}
```

I would appreciate any help/ideas as after spending some days with it I'm not being able to figure out what could be wrong. Thanks!!

The task token seems to be doing something as if I don't include it it complains correctly that it cannot be found on the `sendTaskSuccess`

### Anything else?

```
stepfunctions    | 2022-05-02 21:27:01.485: StartExecution => {"requestClientOptions":{"readLimit":131073,"skipAppendUriPath":false},"requestMetricCollector":null,"customRequestHeaders":null,"customQueryParameters":null,"cloneSource":null,"sdkRequestTimeout":null,"sdkClientExecutionTimeout":null,"stateMachineArn":"arn:aws:states:us-east-1:123456789012:stateMachine:HelloWorldStateMachine","name":"test","input":null,"traceHeader":null,"requestCredentials":null,"requestCredentialsProvider":null,"generalProgressListener":{"syncCallSafe":true},"readLimit":131073,"cloneRoot":null}
stepfunctions    | 2022-05-02 21:27:01.518: [200] StartExecution <= {"sdkResponseMetadata":null,"sdkHttpMetadata":null,"executionArn":"arn:aws:states:us-east-1:123456789012:execution:HelloWorldStateMachine:test","startDate":1651526821512}
stepfunctions    | 2022-05-02 21:27:01.545: arn:aws:states:us-east-1:123456789012:execution:HelloWorldStateMachine:test : {"Type":"ExecutionStarted","PreviousEventId":0,"ExecutionStartedEventDetails":{"Input":"{}","RoleArn":"arn:aws:iam::012345678901:role/DummyRole"}}
stepfunctions    | 2022-05-02 21:27:01.549: arn:aws:states:us-east-1:123456789012:execution:HelloWorldStateMachine:test : {"Type":"TaskStateEntered","PreviousEventId":0,"StateEnteredEventDetails":{"Name":"Pending","Input":"{}"}}
stepfunctions    | 2022-05-02 21:27:01.673: arn:aws:states:us-east-1:123456789012:execution:HelloWorldStateMachine:test : {"Type":"TaskScheduled","PreviousEventId":2,"TaskScheduledEventDetails":{"ResourceType":"lambda","Resource":"invoke.waitForTaskToken","Region":"us-east-1","Parameters":"{\"FunctionName\":\"helloWorld\",\"Payload\":{\"Input\":{},\"TaskToken\":\"0136a2f2-91c8-4ab7-9084-3a37835df854\"}}"}}
stepfunctions    | 2022-05-02 21:27:01.675: arn:aws:states:us-east-1:123456789012:execution:HelloWorldStateMachine:test : {"Type":"TaskStarted","PreviousEventId":3,"TaskStartedEventDetails":{"ResourceType":"lambda","Resource":"invoke.waitForTaskToken"}}
localstack_1     | 2022-05-02T21:27:02.457:DEBUG:localstack.utils.container_utils.container_client: Getting networks for container: stepfunctions_localstack_1
localstack_1     | 2022-05-02T21:27:02.482:INFO:localstack.services.awslambda.lambda_utils: Determined lambda container network: stepfunctions_default
localstack_1     | 2022-05-02T21:27:02.482:DEBUG:localstack.utils.container_utils.container_client: Getting ipv4 address for container stepfunctions_localstack_1 in network stepfunctions_default.
localstack_1     | 2022-05-02T21:27:02.516:INFO:localstack.services.awslambda.lambda_utils: Determined main container target IP: 172.21.0.3
localstack_1     | 2022-05-02T21:27:02.516:INFO:localstack.services.awslambda.lambda_executors: Running lambda: arn:aws:lambda:us-east-1:000000000000:function:helloWorld
localstack_1     | 2022-05-02T21:27:02.517:DEBUG:stevedore.extension: found extension EntryPoint(name='docker_separate_lambda_execution', value='localstack_ext.services.awslambda.lambda_launcher:docker_separate_lambda_execution', group='localstack.hooks.on_docker_separate_execution')
localstack_1     | 2022-05-02T21:27:02.518:ERROR:plugin.manager: error importing entrypoint EntryPoint(name='docker_separate_lambda_execution', value='localstack_ext.services.awslambda.lambda_launcher:docker_separate_lambda_execution', group='localstack.hooks.on_docker_separate_execution'): No module named 'localstack_ext.services.awslambda.lambda_launcher'
localstack_1     | 2022-05-02T21:27:02.519:DEBUG:plugin.manager: no extensions found in namespace localstack.hooks.on_docker_separate_execution
localstack_1     | 2022-05-02T21:27:02.519:DEBUG:localstack.utils.container_utils.docker_sdk_client: Creating container with attributes: {'mount_volumes': None, 'ports': <PortMappings: {}>, 'cap_add': None, 'cap_drop': None, 'dns': '', 'additional_flags': '', 'workdir': None, 'command': 'helloWorld.lambda_handler', 'detach': False, 'entrypoint': None, 'env_vars': {'AWS_ACCESS_KEY_ID': 'test', 'AWS_SECRET_ACCESS_KEY': 'test', 'AWS_REGION': 'us-east-1', 'DOCKER_LAMBDA_USE_STDIN': '1', 'LOCALSTACK_HOSTNAME': '172.21.0.3', 'EDGE_PORT': '4566', '_HANDLER': 'helloWorld.lambda_handler', 'AWS_LAMBDA_FUNCTION_TIMEOUT': '3', 'AWS_LAMBDA_FUNCTION_NAME': 'helloWorld', 'AWS_LAMBDA_FUNCTION_VERSION': '$LATEST', 'AWS_LAMBDA_FUNCTION_INVOKED_ARN': 'arn:aws:lambda:us-east-1:000000000000:function:helloWorld', 'NODE_TLS_REJECT_UNAUTHORIZED': '0'}, 'image_name': 'lambci/lambda:nodejs12.x', 'interactive': True, 'name': None, 'network': 'stepfunctions_default', 'remove': True, 'self': <localstack.utils.container_utils.docker_sdk_client.SdkDockerClient object at 0x7f6452294790>, 'tty': False, 'user': None}
localstack_1     | 2022-05-02T21:27:02.597:DEBUG:localstack.utils.container_utils.docker_sdk_client: Copying file /tmp/localstack/zipfile.8a41587d/. into 4608a772009b9d7d942e45d56a6310464d43e3ebf6bdda63d9014a6d21985b0c:/var/task
localstack_1     | 2022-05-02T21:27:02.960:DEBUG:localstack.utils.container_utils.docker_sdk_client: Starting container 4608a772009b9d7d942e45d56a6310464d43e3ebf6bdda63d9014a6d21985b0c
stepfunctions    | 2022-05-02 21:27:07.051: arn:aws:states:us-east-1:123456789012:execution:HelloWorldStateMachine:test : {"Type":"TaskSubmitFailed","PreviousEventId":4,"TaskSubmitFailedEventDetails":{"ResourceType":"lambda","Resource":"invoke.waitForTaskToken","Error":"UnrecognizedClientException","Cause":"{\"errorMessage\":\"The security token included in the request is invalid.\",\"errorType\":\"UnrecognizedClientException\"}\n"}}
stepfunctions    | 2022-05-02 21:27:07.057: arn:aws:states:us-east-1:123456789012:execution:HelloWorldStateMachine:test : {"Type":"ExecutionFailed","PreviousEventId":5,"ExecutionFailedEventDetails":{"Error":"UnrecognizedClientException","Cause":"{\"errorMessage\":\"The security token included in the request is invalid.\",\"errorType\":\"UnrecognizedClientException\"}\n"}}
localstack_1     | 2022-05-02T21:27:06.821:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:helloWorld result / log output:
localstack_1     | {"errorType":"UnrecognizedClientException","errorMessage":"The security token included in the request is invalid."}
localstack_1     | >2022-05-02T21:27:04.121Z    undefined       INFO    @@@@ Loading function
localstack_1     | > START RequestId: 1a65db29-132a-1849-6003-d9c763290e34 Version: $LATEST
localstack_1     | > 2022-05-02T21:27:04.536Z   1a65db29-132a-1849-6003-d9c763290e34    INFO    @@@@ Lambda has being call
localstack_1     | > 2022-05-02T21:27:04.537Z   1a65db29-132a-1849-6003-d9c763290e34    INFO    @@@@ event message: {"Input":{},"TaskToken":"0136a2f2-91c8-4ab7-9084-3a37835df854"}

localstack_1     | > 2022-05-02T21:27:04.551Z   1a65db29-132a-1849-6003-d9c763290e34    INFO    @@@@ Some seconds sleep to simulate a long running task
localstack_1     | > 2022-05-02T21:27:05.553Z   1a65db29-132a-1849-6003-d9c763290e34    INFO    @@@@ Calling Step Functions to complete callback task with params {"output":"{\"message\":\"Callback task completed successfully.\"}","taskToken":"0136a2f2-91c8-4ab7-9084-3a37835df854"}
localstack_1     | > 2022-05-02T21:27:05.600Z   1a65db29-132a-1849-6003-d9c763290e34    ERROR   (node:14) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
localstack_1     | > 2022-05-02T21:27:06.376Z   1a65db29-132a-1849-6003-d9c763290e34    ERROR   Invoke Error    {"errorType":"UnrecognizedClientException","errorMessage":"The security token included in the request is invalid.","code":"UnrecognizedClientException","message":"The security token included in the request is invalid.","time":"2022-05-02T21:27:06.369Z","requestId":"7837ee6c-8303-4ad0-a2ff-0dd5ea7ec87f","statusCode":400,"retryable":false,"retryDelay":5.558751787084604,"stack":["UnrecognizedClientException: The security token included in the request is invalid.","    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)","    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)","    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)","    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)","    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/...
localstack_1     | 2022-05-02T21:27:06.870:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.aws.provider.logs:default = <function logs at 0x7f6451835700>)
localstack_1     | 2022-05-02T21:27:06.871:DEBUG:plugin.manager: loading plugin localstack.aws.provider:logs:default
localstack_1     | 2022-05-02T21:27:06.908:DEBUG:localstack.services.plugins: checking service health logs:4566
localstack_1     | 2022-05-02T21:27:06.945:INFO:localstack.services.awslambda.lambda_executors: writing log to file '/tmp/localstack/lambda_10wzeile.log'
localstack_1     | 2022-05-02T21:27:06.950:DEBUG:plugin.manager: instantiating plugin PluginSpec(localstack.aws.provider.cloudwatch:default = <function cloudwatch at 0x7f6451845a60>)
localstack_1     | 2022-05-02T21:27:06.950:DEBUG:plugin.manager: loading plugin localstack.aws.provider:cloudwatch:default
localstack_1     | 2022-05-02T21:27:06.963:DEBUG:localstack.services.plugins: checking service health cloudwatch:4566
localstack_1     | 2022-05-02T21:27:06.994:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:helloWorld: Lambda process returned with error. Result: {"errorType":"UnrecognizedClientException","errorMessage":"The security token included in the request is invalid."}. Output:
localstack_1     | b'2022-05-02T21:27:04.121Z\tundefined\tINFO\t@@@@ Loading function\n\x1b[32mSTART RequestId: 1a65db29-132a-1849-6003-d9c763290e34 Version: $LATEST\x1b[0m\n2022-05-02T21:27:04.536Z\t1a65db29-132a-1849-6003-d9c763290e34\tINFO\t@@@@ Lambda has being call\n2022-05-02T21:27:04.537Z\t1a65db29-132a-1849-6003-d9c763290e34\tINFO\t@@@@ event message: {"Input":{},"TaskToken":"0136a2f2-91c8-4ab7-9084-3a37835df854"}\n2022-05-02T21:27:04.551Z\t1a65db29-132a-1849-6003-d9c763290e34\tINFO\t@@@@ Some seconds sleep to simulate a long running task\n2022-05-02T21:27:05.553Z\t1a65db29-132a-1849-6003-d9c763290e34\tINFO\t@@@@ Calling Step Functions to complete callback task with params {"output":"{\\"message\\":\\"Callback task completed successfully.\\"}","taskToken":"0136a2f2-91c8-4ab7-9084-3a37835df854"}\n2022-05-02T21:27:05.600Z\t1a65db29-132a-1849-6003-d9c763290e34\tERROR\t(node:14) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to \'0\' makes TLS connections and HTTPS requests insecure by disabling certificate verification.\n2022-05-02T21:27:06.376Z\t1a65db29-132a-1849-6003-d9c763290e34\tERROR\tInvoke Error \t{"errorType":"UnrecognizedClientException","errorMessage":"The security token included in the request is invalid.","code":"UnrecognizedClientException","message":"The security token included in the request is invalid.","time":"2022-05-02T21:27:06.369Z","requestId":"7837ee6c-8303-4ad0-a2ff-0dd5ea7ec87f","statusCode":400,"retryable":false,"retryDelay":5.558751787084604,"stack":["UnrecognizedClientException: The security token included in the request is invalid.","    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)","    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)","    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)","    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)","    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)","    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)","    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10","    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)","    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)","    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"]}\n\x1b[32mEND RequestId: 1a65db29-132a-1849-6003-d9c763290e34\x1b[0m\n\x1b[32mREPORT RequestId: 1a65db29-132a-1849-6003-d9c763290e34\tInit Duration: 608.04 ms\tDuration: 1850.24 ms\tBilled Duration: 1851 ms\tMemory Size: 1536 MB\tMax Memory Used: 46 MB\t\x1b[0m\n' Traceback (most recent call last):
localstack_1     |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 633, in run_lambda_executor
localstack_1     |     result, log_output = self.execute_in_container(
localstack_1     |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1260, in execute_in_container
localstack_1     |     return DOCKER_CLIENT.start_container(
localstack_1     |   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 451, in start_container
localstack_1     |     raise ContainerException(
localstack_1     | localstack.utils.container_utils.container_client.ContainerException: Docker container returned with exit code 1
localstack_1     |
localstack_1     | The above exception was the direct cause of the following exception:
localstack_1     |
localstack_1     | Traceback (most recent call last):
localstack_1     |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 794, in run_lambda
localstack_1     |     result = LAMBDA_EXECUTOR.execute(
localstack_1     |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 460, in execute
localstack_1     |     return do_execute()
localstack_1     |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 450, in do_execute
localstack_1     |     return _run(func_arn=func_arn)
localstack_1     |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 170, in wrapped
localstack_1     |     raise e
localstack_1     |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 166, in wrapped
localstack_1     |     result = func(*args, **kwargs)
localstack_1     |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 437, in _run
localstack_1     |     raise e
localstack_1     |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 433, in _run
localstack_1     |     result = self._execute(lambda_function, inv_context)
localstack_1     |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 756, in _execute
localstack_1     |     result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
localstack_1     |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 678, in run_lambda_executor
localstack_1     |     raise InvocationException(
localstack_1     | localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: {"errorType":"UnrecognizedClientException","errorMessage":"The security token included in the request is invalid."}. Output:
localstack_1     | b'2022-05-02T21:27:04.121Z\tundefined\tINFO\t@@@@ Loading function\n\x1b[32mSTART RequestId: 1a65db29-132a-1849-6003-d9c763290e34 Version: $LATEST\x1b[0m\n2022-05-02T21:27:04.536Z\t1a65db29-132a-1849-6003-d9c763290e34\tINFO\t@@@@ Lambda has being call\n2022-05-02T21:27:04.537Z\t1a65db29-132a-1849-6003-d9c763290e34\tINFO\t@@@@ event message: {"Input":{},"TaskToken":"0136a2f2-91c8-4ab7-9084-3a37835df854"}\n2022-05-02T21:27:04.551Z\t1a65db29-132a-1849-6003-d9c763290e34\tINFO\t@@@@ Some seconds sleep to simulate a long running task\n2022-05-02T21:27:05.553Z\t1a65db29-132a-1849-6003-d9c763290e34\tINFO\t@@@@ Calling Step Functions to complete callback task with params {"output":"{\\"message\\":\\"Callback task completed successfully.\\"}","taskToken":"0136a2f2-91c8-4ab7-9084-3a37835df854"}\n2022-05-02T21:27:05.600Z\t1a65db29-132a-1849-6003-d9c763290e34\tERROR\t(node:14) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to \'0\' makes TLS connections and HTTPS requests insecure by disabling certificate verification.\n2022-05-02T21:27:06.376Z\t1a65db29-132a-1849-6003-d9c763290e34\tERROR\tInvoke Error \t{"errorType":"UnrecognizedClientException","errorMessage":"The security token included in the request is invalid.","code":"UnrecognizedClientException","message":"The security token included in the request is invalid.","time":"2022-05-02T21:27:06.369Z","requestId":"7837ee6c-8303-4ad0-a2ff-0dd5ea7ec87f","statusCode":400,"retryable":false,"retryDelay":5.558751787084604,"stack":["UnrecognizedClientException: The security token included in the request is invalid.","    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)","    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)","    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)","    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)","    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)","    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)","    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10","    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)","    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)","    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"]}\n\x1b[32mEND RequestId: 1a65db29-132a-1849-6003-d9c763290e34\x1b[0m\n\x1b[32mREPORT RequestId: 1a65db29-132a-1849-6003-d9c763290e34\tInit Duration: 608.04 ms\tDuration: 1850.24 ms\tBilled Duration: 1851 ms\tMemory Size: 1536 MB\tMax Memory Used: 46 MB\t\x1b[0m\n'
localstack_1     |
```

**Comment by dominikschubert** [comment]
Hi @guillemsola!
Is there a reason you're not using the stepfunctions service in LocalStack?

**Comment by cormac-yobota** [comment]
@guillemsola did you find an fix for the issue?

**Comment by djpentz** [comment]
@dominikschubert I'm having similar issues with localstacks stepfunctions and having to run aws-stepfunctions-local just like the OP. When I use localstack for the step function it doesn't seem to create the state machine because `awslocal stepfunctions list-state-machines` renders an empty array, whereas using AWS local it does work. So I assumed localstack's implementation was just buggy/incomplete. Are you saying that it *should* work, say, with `awslocal`?

**Comment by djpentz** [comment]
@guillemsola How did you create your state machine? Did you use `samlocal` or just create from the command line using `awslocal stepfunctions create-state-machine`?

**Comment by dominikschubert** [comment]
> Are you saying that it should work, say, with awslocal?

@djpentz 
Yes, we're basically using a slightly adjusted version anyway and if you try to use the stepfunctions-local container directly you won't have these changes which will most likely lead to compatibility issues.

You can check the logs of the localstack container for any indications on why your state machine wasn't created. It might very well just be an issue of unintentionally using different versions for example since our version of stepfunctions supports multi-region while the container does not.
