### ISSUE TITLE
bug: update CDK exists stack resources on next run

### ISSUE THREAD

**Issue by ParisNakitaKejser-EB** [localstack/localstack#6009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have my code here, its working perfect first time i run cdklocal deploy, if i run it again and remove eg. s3 bucket or my codeartifact domain its will sending a lots of error in my docker container.

```python
from constructs import Construct
from aws_cdk import (
    App, Stack,
    aws_codeartifact as codeartifact,
    aws_s3 as s3,
)


class LocalTestStack(Stack):
    def __init__(self, scope: Construct, id: str, **kwargs):
        super().__init__(scope, id, **kwargs)

        cfn_domain = codeartifact.CfnDomain(
            self,
            "TestCodeArtifactDomain",
            domain_name="DemoDomain"
        )

        s3_bucket_test = s3.Bucket(self, 'TestBucket')
        s3_bucket_test.grant_public_access()

        s3_bucket_test2 = s3.Bucket(self, 'HestBucket')
        s3_bucket_test2.grant_public_access()


app = App()
LocalTestStack(app, "LocalTestStack")
app.synth()
```

my log look like this, look like some localhost proxy post request there are failed.

```
2022-05-04T12:56:44.202:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: 'ParameterValue' Traceback (most recent call last):

  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 185, in index

    result = await run_sync(handler, request, data)

  File "/opt/code/localstack/localstack/utils/asyncio.py", line 85, in run_sync

    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)

  File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run

    result = self.func(self.params, **kwargs)

  File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run

    return fn(*args, **kwargs)

  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 973, in handler

    return modify_and_forward(

  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 514, in wrapper

    value = func(*args, **kwargs)

  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 594, in modify_and_forward

    listener_result = listener.forward_request(

  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/edge.py.enc", line 132, in forward_request

  File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request

    result = do_forward_request(api, method, path, data, headers, port=port)

  File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy

    return new(target, *args, **kwargs)

  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/edge.py.enc", line 128, in do_forward_request

  File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request

    result = do_forward_request_inmem(api, method, path, data, headers, port=port)

  File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem

    response = modify_and_forward(

  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 514, in wrapper

    value = func(*args, **kwargs)

  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 594, in modify_and_forward

    listener_result = listener.forward_request(

  File "/opt/code/localstack/localstack/http/adapters.py", line 51, in forward_request

    response = self.request(request)

  File "/opt/code/localstack/localstack/aws/proxy.py", line 42, in request

    response = self.skeleton.invoke(context)

  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke

    return self.dispatch_request(context, instance)

  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request

    result = handler(context, instance) or {}

  File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__

    return self.fn(*args, **kwargs)

  File "/opt/code/localstack/localstack/aws/api/core.py", line 95, in operation_marker

    return fn(*args, **kwargs)

  File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 951, in execute_change_set

    deployer.apply_change_set(change_set)

  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1219, in apply_change_set

    self.apply_changes(

  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1490, in apply_changes

    self.init_resource_status(old_resources, action="UPDATE")

  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1338, in init_resource_status

    stack.set_resource_status(resource_id, "%s_IN_PROGRESS" % action)

  File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 183, in set_resource_status

    self._set_resource_status_details(resource_id, physical_res_id=physical_res_id)

  File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 192, in _set_resource_status_details

    resource = self.resources.get(resource_id)

  File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 255, in resources

    add_params(defaults=False)

  File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 250, in add_params

    else param["ParameterValue"]

KeyError: 'ParameterValue'
```

### Expected Behavior

Expect to keep my stack up to date, its very important when you need to test a new configuration from time to time, and not a "fresh" run.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Steps are wirte in the start.

### Environment

```markdown
- OS: macOS 12.3.1
- LocalStack: 0.14.2.7
- cdklocal: 2.22.0 (build 1db4b16)
- Docker Desktop: 4.7.1
- Docker Engine: 20.10.14
```

**Comment by thantos** [comment]
I am also seeing this. After updating localstack to `latest` I can no longer re-deploy the CDK bootstrap, which is run currently for all test runs.

```
2022-05-06T18:43:35.693:INFO:localstack.utils.threads: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7f62a3a96320>(None) failed: 'ParameterValue' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 973, in handler
    return modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 514, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 594, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 514, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 594, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/http/adapters.py", line 51, in forward_request
    response = self.request(request)
  File "/opt/code/localstack/localstack/aws/proxy.py", line 42, in request
    return self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/aws/api/core.py", line 95, in operation_marker
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 951, in execute_change_set
    deployer.apply_change_set(change_set)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1219, in apply_change_set
    self.apply_changes(
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1490, in apply_changes
    self.init_resource_status(old_resources, action="UPDATE")
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1338, in init_resource_status
    stack.set_resource_status(resource_id, "%s_IN_PROGRESS" % action)
  File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 183, in set_resource_status
    self._set_resource_status_details(resource_id, physical_res_id=physical_res_id)
  File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 192, in _set_resource_status_details
    resource = self.resources.get(resource_id)
  File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 255, in resources
    add_params(defaults=False)
  File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 250, in add_params
    else param["ParameterValue"]
KeyError: 'ParameterValue'

2022-05-06T18:43:35.693:DEBUG:localstack.utils.threads: FINISHED: <Future at 0x7f62c0de82b0 state=finished raised KeyError>
2022-05-06T18:43:35.694:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: 'ParameterValue' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 185, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 85, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 973, in handler
    return modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 514, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 594, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 514, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 594, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/http/adapters.py", line 51, in forward_request
    response = self.request(request)
  File "/opt/code/localstack/localstack/aws/proxy.py", line 42, in request
    return self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/aws/api/core.py", line 95, in operation_marker
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 951, in execute_change_set
    deployer.apply_change_set(change_set)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1219, in apply_change_set
    self.apply_changes(
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1490, in apply_changes
    self.init_resource_status(old_resources, action="UPDATE")
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1338, in init_resource_status
    stack.set_resource_status(resource_id, "%s_IN_PROGRESS" % action)
  File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 183, in set_resource_status
    self._set_resource_status_details(resource_id, physical_res_id=physical_res_id)
  File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 192, in _set_resource_status_details
    resource = self.resources.get(resource_id)
  File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 255, in resources
    add_params(defaults=False)
  File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 250, in add_params
    else param["ParameterValue"]
KeyError: 'ParameterValue'
```

**Comment by thantos** [comment]
Stopping `localstack` and restarting seems to be the only way to get around this.

**Comment by thantos** [comment]
Should also note that CDK hangs

```
Bootstrapping CDK...
 ⏳  Bootstrapping environment aws://000000000000/us-east-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
CDKToolkit: creating CloudFormation changeset...
```

**Comment by dominikschubert** [comment]
This should be patched in the most recent build now. Please pull `localstack/localstack:latest` again and let us know if you're still experiencing these issues. :+1:

**Comment by parisnakitakejser** [comment]
> This should be patched in the most recent build now. Please pull `localstack/localstack:latest` again and let us know if you're still experiencing these issues. 👍

Thanks a lot for fast react, I will check on work on Monday :)

**Comment by lukqw** [comment]
Hi @ParisNakitaKejser-EB!

AWS CodeArtifact is currently not supported by LocalStack, which results in the error message you are facing.
This can also be found in the logs during deployment via `cdklocal deploy`.

For example, this is the output during deployment of your Stack:
```
localstack_main | 2022-05-19T10:26:15.212:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type CodeArtifact::Domain when resolving references of resource TestCodeArtifactDomain: {"Type": "AWS::CodeArtifact::Domain", "Metadata": {"aws:cdk:path": "UpdateCdkStack/TestCodeArtifactDomain"}, "LogicalResourceId": "TestCodeArtifactDomain", "Properties": {"DomainName": "DemoDomain"}}. To find out if CodeArtifact::Domain is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
localstack_main | 2022-05-19T10:26:15.212:WARNING:localstack.utils.cloudformation.template_deployer: Unable to deploy resource type "CodeArtifact::Domain": {"Type": "AWS::CodeArtifact::Domain", "Metadata": {"aws:cdk:path": "UpdateCdkStack/TestCodeArtifactDomain"}, "LogicalResourceId": "TestCodeArtifactDomain", "Properties": {"DomainName": "DemoDomain"}}
```

The log output during the deployment attempting to delete the CodeArtifact:
```
localstack_main | 2022-05-19T10:30:32.697:WARNING:localstack.utils.cloudformation.template_deployer: Action delete for resource type CodeArtifact::Domain not available. To find out if CodeArtifact::Domain is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
localstack_main | 2022-05-19T10:30:32.734:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type CodeArtifact::Domain when resolving references of resource TestCodeArtifactDomain: {"Type": "AWS::CodeArtifact::Domain", "Metadata": {"aws:cdk:path": "UpdateCdkStack/TestCodeArtifactDomain"}, "LogicalResourceId": "TestCodeArtifactDomain", "Properties": {"DomainName": "DemoDomain"}, "PhysicalResourceId": null}. To find out if CodeArtifact::Domain is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
```

**Comment by ParisNakitaKejser-EB** [comment]
> Hi @ParisNakitaKejser-EB!
> 
> AWS CodeArtifact is currently not supported by LocalStack, which results in the error message you are facing. This can also be found in the logs during deployment via `cdklocal deploy`.
> 
> For example, this is the output during deployment of your Stack:
> 
> ```
> localstack_main | 2022-05-19T10:26:15.212:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type CodeArtifact::Domain when resolving references of resource TestCodeArtifactDomain: {"Type": "AWS::CodeArtifact::Domain", "Metadata": {"aws:cdk:path": "UpdateCdkStack/TestCodeArtifactDomain"}, "LogicalResourceId": "TestCodeArtifactDomain", "Properties": {"DomainName": "DemoDomain"}}. To find out if CodeArtifact::Domain is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
> localstack_main | 2022-05-19T10:26:15.212:WARNING:localstack.utils.cloudformation.template_deployer: Unable to deploy resource type "CodeArtifact::Domain": {"Type": "AWS::CodeArtifact::Domain", "Metadata": {"aws:cdk:path": "UpdateCdkStack/TestCodeArtifactDomain"}, "LogicalResourceId": "TestCodeArtifactDomain", "Properties": {"DomainName": "DemoDomain"}}
> ```
> 
> The log output during the deployment attempting to delete the CodeArtifact:
> 
> ```
> localstack_main | 2022-05-19T10:30:32.697:WARNING:localstack.utils.cloudformation.template_deployer: Action delete for resource type CodeArtifact::Domain not available. To find out if CodeArtifact::Domain is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
> localstack_main | 2022-05-19T10:30:32.734:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type CodeArtifact::Domain when resolving references of resource TestCodeArtifactDomain: {"Type": "AWS::CodeArtifact::Domain", "Metadata": {"aws:cdk:path": "UpdateCdkStack/TestCodeArtifactDomain"}, "LogicalResourceId": "TestCodeArtifactDomain", "Properties": {"DomainName": "DemoDomain"}, "PhysicalResourceId": null}. To find out if CodeArtifact::Domain is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
> ```

Its sad its sound break a redeploy, its fine its not supported but its stille a bug you can deploy first time and then its break secound time, becures then its mean you can run a test run in localstack as you want before sending to AWS.
