### ISSUE TITLE
AttributeError on describing Kinesis streaming destination for DynamoDB tables

### ISSUE THREAD

**Issue by anekar3416** [localstack/localstack#6031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to describe the kinesis streaming destination for one of the DynamoDB tables for which Kinesis Stream is enabled. 
I have setup localstack and started it using the command `localstack start` 

When I try to describe the table streaming destination using `awslocal` it displays the StreamARN details for the dynamodb table.
However when I try to do the same programatically I am facing below issue, can someone please help me with this?

Java throws the below error:

```
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: null (Service: AmazonDynamoDBv2; Status Code: 500; Error Code: null; Request ID: null; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1862) ~[aws-java-sdk-core-1.12.187.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1415) ~[aws-java-sdk-core-1.12.187.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1384) ~[aws-java-sdk-core-1.12.187.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154) ~[aws-java-sdk-core-1.12.187.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811) ~[aws-java-sdk-core-1.12.187.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779) ~[aws-java-sdk-core-1.12.187.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753) ~[aws-java-sdk-core-1.12.187.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713) ~[aws-java-sdk-core-1.12.187.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695) ~[aws-java-sdk-core-1.12.187.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559) ~[aws-java-sdk-core-1.12.187.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539) ~[aws-java-sdk-core-1.12.187.jar:?]
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:6258) ~[aws-java-sdk-dynamodb-1.12.187.jar:?]
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:6225) ~[aws-java-sdk-dynamodb-1.12.187.jar:?]
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeDescribeKinesisStreamingDestination(AmazonDynamoDBClient.java:2034) ~[aws-java-sdk-dynamodb-1.12.187.jar:?]
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.describeKinesisStreamingDestination(AmazonDynamoDBClient.java:1995) ~[aws-java-sdk-dynamodb-1.12.187.jar:?]
	at com.vmware.idm.gaz.resource.DummyStreamProcessorKCLv1.createWorker(DummyStreamProcessorKCLv1.java:135) ~[main/:?]
	at com.vmware.idm.gaz.resource.DummyStreamProcessorKCLv1.startKinesisStreamConsumptionKCLv1(DummyStreamProcessorKCLv1.java:268) ~[main/:?]
```

And in the localstack stacktrace I see this error:

```
2022-05-09T06:08:52.953:INFO:localstack.utils.threads: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0xffff05cd8af0>(None) failed: 'NoneType' object has no attribute 'get' Traceback (most recent call last):
File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run
result = self.func(self.params, **kwargs)
File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
return fn(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 973, in handler
return modify_and_forward(
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 514, in wrapper
value = func(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 594, in modify_and_forward
listener_result = listener.forward_request(
File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request
result = do_forward_request(api, method, path, data, headers, port=port)
File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
result = do_forward_request_inmem(api, method, path, data, headers, port=port)
File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
response = modify_and_forward(
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 514, in wrapper
value = func(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 594, in modify_and_forward
listener_result = listener.forward_request(
File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 296, in forward_request
return super().forward_request(method, path, data, headers)
File "/opt/code/localstack/localstack/http/adapters.py", line 51, in forward_request
response = self.request(request)
File "/opt/code/localstack/localstack/aws/proxy.py", line 42, in request
return self.skeleton.invoke(context)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
return self.dispatch_request(context, instance)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
result = handler(context, instance) or {}
File "/opt/code/localstack/localstack/aws/forwarder.py", line 57, in _call
return handler(context, req)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
return self.fn(*args, **kwargs)
File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 1024, in describe_kinesis_streaming_destination
stream_destinations = table_def.get("KinesisDataStreamDestinations") or []
AttributeError: 'NoneType' object has no attribute 'get'
```

This is how I am trying to describe the Kinesis destination:

```
DescribeKinesisStreamingDestinationRequest request = new DescribeKinesisStreamingDestinationRequest()
                .withTableName(tableName);
DescribeKinesisStreamingDestinationResult result = amazonDynamoDB.describeKinesisStreamingDestination(request);
```

### Expected Behavior

The error should not appear and the Kinesis Streaming Destination result should be returned.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

### Environment

```markdown
- OS: macOS
- LocalStack: latest
```

**Comment by whummer** [comment]
Thanks for reporting @anekar3416 . This should be fixed via #6063 - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks!
