### ISSUE TITLE
bug: Running localstack with 'localstack start' on windows 10 in git bash throws an encoding error

### ISSUE THREAD

**Issue by FlorianSchneiderMsgDavid** [localstack/localstack#6051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I installed localstack via pip on git bash on windows 10 
python version 3.9.10

I run 'localstack start'

Instead of starting localstack I got the following error:

```
     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

Traceback (most recent call last):
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\Scripts\localstack", line 23, in <module>
    main()
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\Scripts\localstack", line 19, in main
    main.main()
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\cli\main.py", line 6, in main
    cli()
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\cli\plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\cli\localstack.py", line 122, in cmd_start
    print_version()
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\lib\site-packages\localstack\cli\localstack.py", line 435, in print_version
    console.print(" :laptop_computer: [bold]LocalStack CLI[/bold] [blue]%s[/blue]" % __version__)
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\lib\site-packages\rich\console.py", line 1773, in print
    self._buffer.extend(new_segments)
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\lib\site-packages\rich\console.py", line 972, in __exit__
    self._exit_buffer()
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\lib\site-packages\rich\console.py", line 930, in _exit_buffer
    self._check_buffer()
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\lib\site-packages\rich\console.py", line 2078, in _check_buffer
    legacy_windows_render(
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\lib\site-packages\rich\_windows_renderer.py", line 19, in legacy_windows_render
    term.write_text(text)
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\lib\site-packages\rich\_win32_console.py", line 379, in write_text
    self.write(text)
  File "C:\Users\schnef2\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f4bb' in position 1: character maps to <undefined>
```

### Expected Behavior

After installing localstack via pip on git bash on windows 10
and running 'localstack start'

I expect it to run

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
After installing python 3.9.10 with pip
go into git bash (windows 10) and run

localstack start

### Environment

```markdown
- OS: Windows 10
- LocalStack: 0.14.2.1
- Python: 3.9.10
```

**Comment by igoragueme** [comment]
Same error here.

**Comment by MarcelStranak** [comment]
Hi @FlorianSchneiderMsgDavid, @igoragueme,  to mitigate this error you can run LocalStack with a command:
 `localstack start --no-banner` this will stop showing the banner which contains the problematic unicode.

For a more in-depth fix, you can have a look at this [stackoverflow discussion](https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window) how to enable UTF-8 on Windows and PowerShell console.

**Comment by MarcelStranak** [comment]
A FAQ section was added in documentation https://docs.localstack.cloud/getting-started/faq/#how-to-fix-localstack-cli-python-utf-8-encoding-issue-under-windows
