### ISSUE TITLE
feature request: KMS multi-region replicateKey function

### ISSUE THREAD

**Issue by CaptchaTW** [localstack/localstack#6101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Hello, 

Currently when using localstack there seems to be no implementation for `replicateKey()` that is necessary to put the a multi-region KMS key in another region. Are there any plans for this?

Thanks

**Comment by rmdanaasd** [comment]
مرحبًا بك في LocalStack! نشكرك على الإبلاغ عن مشكلتك الأولى وسيعمل فريقنا على إصلاح المشكلة نيابةً عنك أو التواصل للحصول على مزيد من المعلومات

**Comment by taras-kobernyk-localstack** [comment]
Created a PR [https://github.com/spulec/moto/pull/5288](url) for moto upstream to add replicate_key there first. When localstack catches up with the change there - will add then the code on our side utilizing this new feature in moto.

**Comment by whummer** [comment]
Hi @CaptchaTW , thanks for reporting - this should be (hopefully) fixed in the meantime. Can you please pull the `latest` Docker image and give it another try? Please let us know if the issue persists.. Thanks!

**Comment by taras-kobernyk-localstack** [comment]
Might be useful to wait for a few more days. We have a new version of our KMS code incoming. Better to check then if this key replication works to your satisfaction, or if something is still missing.

**Comment by taras-kobernyk-localstack** [comment]
Apologies for the delay. But the code is finally there.

I am going to close the ticket. But please let us know if there is something wrong with the implementation.

**Comment by kingan379** [comment]
Replicating key works for me through the aws sdk (using localstack), but from command line im getting 500 exceptions

aws  kms --endpoint-url=http://localhost:4566 replicate-key --key-id mrk-<ID> --replica-region ca-central-1

An error occurred (InternalError) when calling the ReplicateKey operation (reached max retries: 2): exception while calling kms.ReplicateKey: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 122, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 92, in __call__
    skeleton_response = self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/aws/api/core.py", line 151, in operation_marker
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/kms/provider.py", line 252, in replicate_key
    replica_key = copy.deepcopy(key)
  File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.10/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_cffi_backend.FFI' object
