### ISSUE TITLE
api-gateway from api.json: timeout

### ISSUE THREAD

**Issue by gergopapi** [localstack/localstack#611]
Hi there,

I am trying to create a simple rest api via cli.
Localstack is started via docker-compose (latest installed some days ago), not through local installation.
OS: win 10 Professional.
Terminal: cmd, cmder

**Command:**

```
aws --endpoint-url=http://localhost:4567 --region=us-east-1 apigateway import-rest-api --body 'file:///restapi.json'
```

The command takes ages, after which I get this message:
HTTPConnectionPool(host='localhost', port=4567): Read timed out.

**Meanwhile, I see following lines in local-stack:**

```
localstack_1  | 2018-02-13T09:15:33:ERROR:localstack.services.generic_proxy: Error forwarding request: No JSON object could be decoded Traceback (most recent call last):           
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 181, in forward                                                                            
localstack_1  |     path=path, data=data, headers=forward_headers)                                                                                                                  
localstack_1  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 158, in forward_request                                                   
localstack_1  |     data = data and json.loads(to_str(data))                                                                                                                        
localstack_1  |   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads                                                                                                    
localstack_1  |     return _default_decoder.decode(s)                                                                                                                               
localstack_1  |   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode                                                                                                    
localstack_1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                               
localstack_1  |   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode                                                                                                
localstack_1  |     raise ValueError("No JSON object could be decoded")                                                                                                             
localstack_1  | ValueError: No JSON object could be decoded                                                                                                                         
localstack_1  |                                                                                                                                                                     
localstack_1  | 2018-02-13T09:16:34:ERROR:localstack.services.generic_proxy: Error forwarding request: No JSON object could be decoded Traceback (most recent call last):           
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 181, in forward                                                                            
localstack_1  |     path=path, data=data, headers=forward_headers)                                                                                                                  
localstack_1  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 158, in forward_request                                                   
localstack_1  |     data = data and json.loads(to_str(data))                                                                                                                        
localstack_1  |   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads                                                                                                    
localstack_1  |     return _default_decoder.decode(s)                                                                                                                               
localstack_1  |   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode                                                                                                    
localstack_1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                               
localstack_1  |   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode                                                                                                
localstack_1  |     raise ValueError("No JSON object could be decoded")                                                                                                             
localstack_1  | ValueError: No JSON object could be decoded                                                                                                                         
localstack_1  |                                                                                                                                                                     
localstack_1  | 2018-02-13T09:17:35:ERROR:localstack.services.generic_proxy: Error forwarding request: No JSON object could be decoded Traceback (most recent call last):           
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 181, in forward                                                                            
localstack_1  |     path=path, data=data, headers=forward_headers)                                                                                                                  
localstack_1  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 158, in forward_request                                                   
localstack_1  |     data = data and json.loads(to_str(data))                                                                                                                        
localstack_1  |   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads                                                                                                    
localstack_1  |     return _default_decoder.decode(s)                                                                                                                               
localstack_1  |   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode                                                                                                    
localstack_1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                               
localstack_1  |   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode                                                                                                
localstack_1  |     raise ValueError("No JSON object could be decoded")                                                                                                             
localstack_1  | ValueError: No JSON object could be decoded                                                                                                                         
localstack_1  |                                                                                                                                                                     
localstack_1  | 2018-02-13T09:18:36:ERROR:localstack.services.generic_proxy: Error forwarding request: No JSON object could be decoded Traceback (most recent call last):           
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 181, in forward                                                                            
localstack_1  |     path=path, data=data, headers=forward_headers)                                                                                                                  
localstack_1  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 158, in forward_request                                                   
localstack_1  |     data = data and json.loads(to_str(data))                                                                                                                        
localstack_1  |   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads                                                                                                    
localstack_1  |     return _default_decoder.decode(s)                                                                                                                               
localstack_1  |   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode                                                                                                    
localstack_1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                               
localstack_1  |   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode                                                                                                
localstack_1  |     raise ValueError("No JSON object could be decoded")                                                                                                             
localstack_1  | ValueError: No JSON object could be decoded                                                                                                                         
localstack_1  |                                                                                                                                                                     
localstack_1  | 2018-02-13T09:19:40:ERROR:localstack.services.generic_proxy: Error forwarding request: No JSON object could be decoded Traceback (most recent call last):           
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 181, in forward                                                                            
localstack_1  |     path=path, data=data, headers=forward_headers)                                                                                                                  
localstack_1  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 158, in forward_request                                                   
localstack_1  |     data = data and json.loads(to_str(data))                                                                                                                        
localstack_1  |   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads                                                                                                    
localstack_1  |     return _default_decoder.decode(s)                                                                                                                               
localstack_1  |   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode                                                                                                    
localstack_1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                               
localstack_1  |   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode                                                                                                
localstack_1  |     raise ValueError("No JSON object could be decoded")                                                                                                             
localstack_1  | ValueError: No JSON object could be decoded                                                                                                                         
localstack_1  |                                                                                                                                                                     
localstack_1  | 2018-02-13T09:22:42:ERROR:localstack.services.generic_proxy: Error forwarding request: No JSON object could be decoded Traceback (most recent call last):           
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 181, in forward                                                                            
localstack_1  |     path=path, data=data, headers=forward_headers)                                                                                                                  
localstack_1  |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 158, in forward_request                                                   
localstack_1  |     data = data and json.loads(to_str(data))                                                                                                                        
localstack_1  |   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads                                                                                                    
localstack_1  |     return _default_decoder.decode(s)                                                                                                                               
localstack_1  |   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode                                                                                                    
localstack_1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                               
localstack_1  |   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode                                                                                                
localstack_1  |     raise ValueError("No JSON object could be decoded")                                                                                                             
localstack_1  | ValueError: No JSON object could be decoded                                                                                                                         
localstack_1  |                         
```                                                                                                                                            

After this when I check the created api:

```
 aws --endpoint-url=http://localhost:4567 --region=us-east-1 apigateway get-rest-apis

I get:
{                    
    "items": []      
}                    


**Finally my json (created on AWS apigateway site, deployment exported to json):**

{
  "swagger": "2.0",
  "info": {
    "version": "2018-02-12T15:45:21Z",
    "title": "infinity_gergo_test"
  },
  "basePath": "/test",
  "schemes": [
    "https"
  ],
  "paths": {
    "/thing": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/Empty"
            }
          }
        },
        "x-amazon-apigateway-integration": {
          "responses": {
            "default": {
              "statusCode": "200"
            }
          },
          "passthroughBehavior": "when_no_match",
          "requestTemplates": {
            "application/json": "{\"statusCode\": 200}"
          },
          "type": "mock"
        }
      }
    }
  },
  "definitions": {
    "Empty": {
      "type": "object",
      "title": "Empty Schema"
    }
  }
}
```

What am I doing wrong? 

Thank you in advance!

Best Regards,

    Gergely

**Comment by whummer** [comment]
This should be fixed in the meantime - default method is to start LocalStack in Docker under Windows. Closing - please re-open if the problem persists.
