### ISSUE TITLE
DynamoDb PutItem - Object of type bytes is not JSON serializable Traceback

### ISSUE THREAD

**Issue by arnaldobadin** [localstack/localstack#6141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using `Docker version 20.10.16, build aa7e414` and the latest localstack [0.14.3](https://hub.docker.com/layers/localstack/localstack/localstack/0.14.3/images/sha256-c47f5ede1e5fc4fec941ef8605e0b85be66f8b61ed20828e2ea1e51581637932?context=explore).

When I am calling DynamoDB PutItem, it yields this error:

```
2022-05-25T01:57:42.357:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: Object of type bytes is not JSON serializable Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 185, in index
localstack    |     result = await run_sync(handler, request, data)
localstack    |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 85, in run_sync
localstack    |     return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
localstack    |   File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run
localstack    |     result = self.func(self.params, **kwargs)
localstack    |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
localstack    |     return fn(*args, **kwargs)
localstack    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 992, in handler
localstack    |     return modify_and_forward(
localstack    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
localstack    |     value = func(*args, **kwargs)
localstack    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
localstack    |     listener_result = listener.forward_request(
localstack    |   File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request
localstack    |     result = do_forward_request(api, method, path, data, headers, port=port)
localstack    |   File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
localstack    |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
localstack    |   File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
localstack    |     response = modify_and_forward(
localstack    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
localstack    |     value = func(*args, **kwargs)
localstack    |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
localstack    |     listener_result = listener.forward_request(
localstack    |   File "/opt/code/localstack/localstack/http/adapters.py", line 51, in forward_request
localstack    |     response = self.request(request)
localstack    |   File "/opt/code/localstack/localstack/aws/proxy.py", line 42, in request
localstack    |     return self.skeleton.invoke(context)
localstack    |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
localstack    |     return self.dispatch_request(context, instance)
localstack    |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
localstack    |     result = handler(context, instance) or {}
localstack    |   File "/opt/code/localstack/localstack/aws/forwarder.py", line 57, in _call
localstack    |     return handler(context, req)
localstack    |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
localstack    |     return self.fn(*args, **kwargs)
localstack    |   File "/opt/code/localstack/localstack/aws/api/core.py", line 95, in operation_marker
localstack    |     return fn(*args, **kwargs)
localstack    |   File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 752, in transact_write_items
localstack    |     records = self.prepare_transact_write_item_records(
localstack    |   File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 1094, in prepare_transact_write_item_records
localstack    |     new_record["dynamodb"]["SizeBytes"] = len(json.dumps(put_request["Item"]))
localstack    |   File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
localstack    |     return _default_encoder.encode(obj)
localstack    |   File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
localstack    |     chunks = self.iterencode(o, _one_shot=True)
localstack    |   File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
localstack    |     return _iterencode(o, 0)
localstack    |   File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
localstack    |     raise TypeError(f'Object of type {o.__class__.__name__} '
localstack    | TypeError: Object of type bytes is not JSON serializable
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
version: "2.1"

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566-4599:4566-4599"
      - "9000:9000"
    volumes:
      - localstack:/tmp/localstack/data
      - /dev/null:/tmp/localstack/data/recorded_api_calls.json
    environment:
      - SERVICES=sqs,dynamodb,s3
      - AWS_DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=9000
      - LAMBDA_EXECUTOR=local
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=1
        
volumes:
  localstack:
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   i am using golang aws sdk (but it was working and I didn't update anything here)

### Environment

```markdown
- OS: Ubuntu
- LocalStack: 0.14.3
```

**Comment by thrau** [comment]
hi @arnaldobadin , thanks for reporting. could you please share the CreateTable and the concrete PutItem command you are running so we can try to reproduce it?

**Comment by mgurov** [comment]
Same problem, a regression on 0.14.3 - worked OK on 0.14.2 

Narrowed down to a transactional write of an item with a byte array, e.g. (Kotlin): 

````kotlin
        amazonDynamoDb.transactWriteItems(
            TransactWriteItemsRequest().withTransactItems(
                TransactWriteItem().withPut(
                    Put().withTableName(tableName)
                        .withItem(
                            mapOf(
                                "id" to AttributeValue(UUID.randomUUID().toString()),
                                "byteArray" to AttributeValue().withB(ByteBuffer.wrap("abcd".toByteArray())),
                            )
                        )
                )
            )
        )

````

**Comment by calvin-pietersen** [comment]
This still seems to be an issue on localstack `1.0.4`?

**Comment by calvin-pietersen** [comment]
Okay, I just tested all the way back to `0.14.2` from `1.0.4`.. and `0.14.2` is the only working version. So it seems this is still an issue.

**Comment by ilyatikhonov** [comment]
This is still an issue for the latest (v1.2.0) release
