### ISSUE TITLE
bug: MSK API Missing Response Members

### ISSUE THREAD

**Issue by mviamari** [localstack/localstack#6149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the MSK API, the following errors/warnings are printed in the localstack docker logs

```
2022-05-25T20:47:53.952:ERROR:localstack.aws.protocol.serializer: Response object ClusterInfo contains a member which is not specified: ConfigurationInfo

Traceback (most recent call last):

  File "/opt/code/localstack/localstack/aws/protocol/serializer.py", line 1165, in _serialize_type_structure

    member_shape = members[member_key]

KeyError: 'ConfigurationInfo'

2022-05-25T20:47:53.952:ERROR:localstack.aws.protocol.serializer: Response object ClusterInfo contains a member which is not specified: KafkaVersion

Traceback (most recent call last):

  File "/opt/code/localstack/localstack/aws/protocol/serializer.py", line 1165, in _serialize_type_structure

    member_shape = members[member_key]

KeyError: 'KafkaVersion'
```

It seems that the API Response object either finds or is looking for members that are not recognized.

### Expected Behavior

The appropriate members for the Response objects are serialized and no errors/warnings are shown in the logs.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

This is generated when creating an MSK cluster through terraform, but it's not clear to me which terraform resource (the cluster itself, or a supporting resource such as the cluster configuration) generates the error in the API

### Environment

```markdown
- OS: Mac OS X
- LocalStack: 
LocalStack version: 0.14.3
LocalStack Docker container id: 69f5f1533850
LocalStack build date: 2022-05-24
LocalStack build git hash: 732f9cbe
```

### Anything else?

This doesn't appear to be breaking any usage but since it appears to represent an incomplement implementation of an API, I've submitted it as a bug.

**Comment by thrau** [comment]
hi @mviamari!

the log errors, while a bit annoying, are safe to ignore. it just means that our implementation of the API is returning superfluous attributes which the serializer ignores, but complains very loudly about it (so we find them and fix them). it should not affect the behavior at al.

are you missing any specific response attributes that are required by the API?

**Comment by mviamari** [comment]
Good to know. It seems I got the relationship backwards.

I don't think there are any missing members, but it's mostly done through terraform right now so I don't inspect the actual responses. The logs messages were all I had to go on while I was debugging my terraform.
