### ISSUE TITLE
bug: lambda create-function resulting in error and no function created

### ISSUE THREAD

**Issue by tuxagon** [localstack/localstack#6204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current behavior is that using `lambda create-function` always ends in an error and no function created.

### Expected Behavior

The expected behavior is that the lambda would get created within localstack.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    DEBUG=1 localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws --region us-west-2 --endpoint-url http://localhost:4566 --no-sign-request lambda create-function --function-name test-func --role arn:aws:iam::000000000000:role/lambda-role --handler lambda.handler --zip-file fileb:///tmp/lambda.zip --runtime nodejs14.x

#### Error encountered
The error I kept receiving was 

    An error occurred (500) when calling the CreateFunction operation (reached max retries: 2): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><title>500 Internal Server Error</title><h1>Internal Server Error</h1><p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

From the localstack logs, this stack trace shows up
```
2022-06-04 00:25:36,300:API: Error on request:
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 319, in run_wsgi
execute(self.server.app)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 308, in execute
application_iter = app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 205, in __call__
return backend_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 161, in convert_flask_to_httpretty_response_call
return convert_flask_to_httpretty_response_call_orig(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 147, in __call__
result = self.callback(request, request.url, {})
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/core/utils.py", line 281, in _wrapper
response = f(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1110, in key_or_control_response
response = self._key_response(request, full_url, self.headers)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 1296, in _key_response
return self._key_response_post(request, body, bucket_name, query, key_name)
File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 167, in s3_key_response_post
result = s3_key_response_post_orig(
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 2007, in _key_response_post
self._set_action("KEY", "POST", query)
File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/s3/responses.py", line 623, in _set_action
self.data["Action"] = ACTION_MAP[action_resource_type][method]["DEFAULT"]
KeyError: 'DEFAULT'
```

### Environment

```markdown
- OS: MacOS 12.4
- LocalStack: latest
```

### Anything else?

For simplicity, here is some lambda code to and the zip command to match the above client command.

```javascript
exports.handler = (event, context) => {
  return ""
}
```
and
```
zip /tmp/lambda.zip lambda.js
```

**Comment by whummer** [comment]
Thanks for reporting @tuxagon . Please note that if you add the `--no-sign-request` option, LocalStack is no longer able to detect which API is being targeted by your request (it falsely assumes that this is an S3 request in this case, which then leads to an error).

Can you try removing the `--no-sign-request` in your command (also, we recommend installing the [`awslocal`](https://github.com/localstack/aws-cdk-local) command line):
```
awslocal --region us-west-2 lambda create-function --function-name test-func --role arn:aws:iam::000000000000:role/lambda-role --handler lambda.handler --zip-file fileb:///tmp/lambda.zip --runtime nodejs14.x
```

Hope that helps - please keep us posted on how it goes.. Thanks!

**Comment by tuxagon** [comment]
Interesting. The only reason `--no-sign-request` is provided is because I get 
```
Unable to locate credentials. You can configure credentials by running "aws configure".
```

How could I get localstack to work without `--no-sign-request`?

**Comment by evbo** [comment]
@tuxagon thank you for demonstrating clearly and concisely how to do a basic operation using localstack, such as create a lambda.

I've spent 3 hours reading docs and wall-head-banging, just to finally get a working command for creating a bucket using docker-compose (this command is run from a separate `service` defined alongside localstack `service`):

```
AWS_PAGER="" \
AWS_ACCESS_KEY_ID=none \
AWS_SECRET_ACCESS_KEY=none \
aws \
  s3api create-bucket \
    --endpoint-url http://localstack-dev:4566 \
    --bucket my-bucket-3 \
    --create-bucket-configuration '{"LocationConstraint": "us-west-2"}'
```

@lukqw thanks for the wrapper suggestion. Sometimes though, it's nice seeing bare-bones how to do things.
