### ISSUE TITLE
SQS health check failed

### ISSUE THREAD

**Issue by softwareken** [localstack/localstack#6274]
I see this problem was addressed before but it still persists.  Please let me know how to resolve this issue.

The following are the steps and the response I received:

>>>>In the podman terminal:
>>>>>podman run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 docker.io/localstack/localstack:latest

Waiting for all LocalStack services to be ready
2022-06-15 13:33:07,038 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-06-15 13:33:07,042 INFO supervisord started with pid 14
2022-06-15 13:33:08,046 INFO spawned: 'infra' with pid 19
2022-06-15 13:33:09,048 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready

**LocalStack version: 0.14.2**
LocalStack build date: 2022-05-05
LocalStack build git hash: f7b06dec

Starting edge router (https port 4566)...
2022-06-15T13:33:32.159:INFO:bootstrap.py: Execution of "prepare_installation" took 532.28ms
Waiting for all LocalStack services to be ready
[2022-06-15 13:33:34 +0000] [19] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2022-06-15T13:33:34.945:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
2022-06-15T13:33:35.168:INFO:bootstrap.py: Execution of "start_runtime_components" took 3008.96ms
Ready.
2022-06-15T13:33:35.982:INFO:bootstrap.py: Execution of "_resolve_api_provider_specs" took 813.50ms
2022-06-15T13:33:35.982:INFO:bootstrap.py: Execution of "preload_services" took 813.72ms

>>>>In another terminal:
>>>>>aws --endpoint-url=http://localhost:4566 sqs list-queues --queue-name-prefix q1
>>>>>Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
b'{}'

>>>>In the podman terminal:
2022-06-15T13:35:34.689:INFO:bootstrap.py: Execution of "_load_service_plugin" took 539.01ms
2022-06-15T13:35:34.690:INFO:localstack.services.infra: Starting mock SQS service on http port 4566 ...
2022-06-15T13:35:34.690:INFO:localstack.services.motoserver: starting moto server on http://0.0.0.0:43090
2022-06-15T13:35:34.703:ERROR:localstack.services.sqs.sqs_starter: **SQS health check failed**
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/sqs/sqs_starter.py", line 43, in check_sqs
    out = aws_stack.connect_to_service(
  File "/opt/code/localstack/localstack/utils/aws/aws_stack.py", line 354, in connect_to_service
    new_client = boto_factory(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/session.py", line 840, in create_client
    region_name = self._resolve_region_name(region_name, config)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/session.py", line 903, in _resolve_region_name
    validate_region_name(region_name)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/utils.py", line 1218, in validate_region_name
    raise InvalidRegionError(region_name=region_name)
botocore.exceptions.InvalidRegionError: Provided region_name 'Hf7OltHC6W3tmQUVCiivWCpLtHMYT02suYde3B+g0GSCmEC' doesn't match a supported format.
2022-06-15T13:35:34.706:ERROR:localstack.services.plugins: error while checking service sqs:
2022-06-15T13:35:34.706:INFO:bootstrap.py: Execution of "require" took 555.65ms
2022-06-15T13:35:34.710:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: failed to get service for sqs:  Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/edge.py", line 218, in _require_service
    self.service_manager.require(api)
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 82, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/plugins.py", line 337, in require
    raise container.errors[-1]
  File "/opt/code/localstack/localstack/services/plugins.py", line 241, in check
    self.service.check(print_error=True)
  File "/opt/code/localstack/localstack/services/plugins.py", line 186, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/sqs/sqs_starter.py", line 52, in check_sqs
    assert out is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 185, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 85, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 973, in handler
    return modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 514, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 594, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 163, in forward_request
    self._require_service(api)
  File "/opt/code/localstack/localstack/services/edge.py", line 220, in _require_service
    raise HTTPErrorResponse("failed to get service for %s: %s" % (api, e), code=500)
localstack.utils.server.http2_server.HTTPErrorResponse: failed to get service for sqs:

2022-06-15T13:35:34.710:INFO:localstack.utils.threads: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7f585d1843a0>(None) failed: failed to get service for sqs:  Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/edge.py", line 218, in _require_service
    self.service_manager.require(api)
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 82, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/plugins.py", line 337, in require
    raise container.errors[-1]
  File "/opt/code/localstack/localstack/services/plugins.py", line 241, in check
    self.service.check(print_error=True)
  File "/opt/code/localstack/localstack/services/plugins.py", line 186, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/sqs/sqs_starter.py", line 52, in check_sqs
    assert out is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 973, in handler
    return modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 514, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 594, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 163, in forward_request
    self._require_service(api)
  File "/opt/code/localstack/localstack/services/edge.py", line 220, in _require_service
    raise HTTPErrorResponse("failed to get service for %s: %s" % (api, e), code=500)
localstack.utils.server.http2_server.HTTPErrorResponse: failed to get service for sqs:

**Comment by MarcelStranak** [comment]
Hi, can you please follow this documentation article that we are providing for podman?
https://docs.localstack.cloud/localstack/podman/
If you'll still have issues, please let me know.

**Comment by thrau** [comment]
the problematic code is no longer used with 1.0.0, so the problem should be resolved. if the problem resurfaces, please open up a new issue report with the latest version of localstack. thanks!
