### ISSUE TITLE
TestRunner fails on Windows machines

### ISSUE THREAD

**Issue by jonassvalin** [localstack/localstack#628]
We're attempting to run tests on Windows machines using the LocalstackTestRunner / LocalstackDockerTestRunner but they fail due to dependency on "bash".

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [software.amazon.awssdk.services.s3.S3Client]: Factory method 's3Client' threw exception; nested exception is java.lang.RuntimeException: java.io.IOException: Cannot run program "bash": CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 138 more
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "bash": CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at cloud.localstack.LocalstackTestRunner.exec(LocalstackTestRunner.java:235)
	at cloud.localstack.LocalstackTestRunner.exec(LocalstackTestRunner.java:204)
	at cloud.localstack.LocalstackTestRunner.ensureInstallation(LocalstackTestRunner.java:149)
	at cloud.localstack.LocalstackTestRunner.ensureInstallationAndGetEndpoint(LocalstackTestRunner.java:176)
	at cloud.localstack.LocalstackTestRunner.getEndpointS3(LocalstackTestRunner.java:51)
	at SOMEPACKAGE.SOMECLASS.s3Client(SOMECLASS.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 139 more
```

Version:
`cloud.localstack:localstack-utils:0.1.11`

**Comment by rjackson64840** [comment]
If it's Windows 10 you can install the linux subsystem for windows which will give you bash capability:

https://docs.microsoft.com/en-us/windows/wsl/install-win10

I was able to get past the issue you describe, but now my tests lock up when initializing the LocalstackTestRunner
