### ISSUE TITLE
bug: persistence for SQS queues with ReceiveMessageWaitTimeSeconds is broken

### ISSUE THREAD

**Issue by nerochiaro** [localstack/localstack#6282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I create a queue that has the `ReceiveMessageWaitTimeSeconds` attribute set to any non-zero value.
It works OK until I restart localstack. Then as soon as I try to receive messages localstack errors out and returns an invalid response.

### Expected Behavior

I expected the queue to be able to keep functioning even after restarting localstack.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker-compose up`

This is the `docker-compose.yml` file:
```
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "443:443"
    env_file:
      - localstack-secrets.env
    environment:
      - LOCALSTACK_SERVICES=sqs
      - HOST_TMP_FOLDER=./persist/tmp
      - DATA_DIR=/tmp/localstack-data
      - LS_LOG=info
    volumes:
      - ./persist/data:/tmp/localstack-data
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I create a FIFO queue like this
```
AWS_REGION=eu-west-3 awslocal sqs create-queue --queue-name=test-queue.fifo \
--attributes='{"ReceiveMessageWaitTimeSeconds": "5"}'

```

then restart localstack (with docker-compose `down` and `up` commands), then try to read from the queue:
```
$ AWS_REGION=eu-west-3 awslocal sqs receive-message \
--queue=http://localhost:4566/000000000000/test_queue.fifo

Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
b'{}'
```

This is the error in localstack's log:
```
Waiting for all LocalStack services to be ready
2022-06-16 11:23:05,204 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-06-16 11:23:05,207 INFO supervisord started with pid 14
2022-06-16 11:23:06,210 INFO spawned: 'infra' with pid 19
2022-06-16 11:23:07,213 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

LocalStack version: 0.14.4.dev
LocalStack build date: 2022-06-15
LocalStack build git hash: 4d7a256e

2022-06-16T11:23:09.374:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
Waiting for all LocalStack services to be ready
Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
Starting edge router (http port 4566)...
Starting edge router (https port 443)...
Ready.
2022-06-16T11:23:12.594:INFO:localstack_ext.utils.aws.metadata_service: Starting AWS instance metadata service on port 80
2022-06-16T11:23:12.609:INFO:botocore.credentials: Found credentials in environment variables.
2022-06-16T11:23:12.624:INFO:botocore.credentials: Found credentials in environment variables.
[2022-06-16 11:23:12 +0000] [19] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2022-06-16T11:23:12.636:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
[2022-06-16 11:23:12 +0000] [19] [INFO] Running on https://0.0.0.0:443 (CTRL + C to quit)
2022-06-16T11:23:12.639:INFO:hypercorn.error: Running on https://0.0.0.0:443 (CTRL + C to quit)
2022-06-16T11:23:16.006:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: cannot wait on un-acquired lock Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 185, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 85, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 993, in handler
    return modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
    return new(target, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/edge.py.enc", line 71, in E
  File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/http/adapters.py", line 51, in forward_request
    response = self.request(request)
  File "/opt/code/localstack/localstack/aws/proxy.py", line 43, in request
    return self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/sqs/provider.py", line 1111, in receive_message
    standard_message = queue.get(
  File "/opt/code/localstack/localstack/services/sqs/provider.py", line 414, in get
    standard_message: SqsMessage = self.visible.get(block=block, timeout=timeout)
  File "/usr/local/lib/python3.10/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/local/lib/python3.10/threading.py", line 312, in wait
    raise RuntimeError("cannot wait on un-acquired lock")
RuntimeError: cannot wait on un-acquired lock

2022-06-16T11:23:16.007:INFO:localstack.utils.threads: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7ffba5f6e170>(None) failed: cannot wait on un-acquired lock Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 993, in handler
    return modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
    return new(target, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/edge.py.enc", line 71, in E
  File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/http/adapters.py", line 51, in forward_request
    response = self.request(request)
  File "/opt/code/localstack/localstack/aws/proxy.py", line 43, in request
    return self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/sqs/provider.py", line 1111, in receive_message
    standard_message = queue.get(
  File "/opt/code/localstack/localstack/services/sqs/provider.py", line 414, in get
    standard_message: SqsMessage = self.visible.get(block=block, timeout=timeout)
  File "/usr/local/lib/python3.10/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/local/lib/python3.10/threading.py", line 312, in wait
    raise RuntimeError("cannot wait on un-acquired lock")
RuntimeError: cannot wait on un-acquired lock
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack docker image: latest
- LocalStack version: 0.14.4.dev
- LocalStack build date: 2022-06-15
- LocalStack build git hash: 4d7a256e
```

**Comment by silv-io** [comment]
seems related with #6281

**Comment by thrau** [comment]
i'm no longer able to reproduce this issue with 1.0.3. could you please pull the latest image, follow the [migration guide](https://github.com/localstack/localstack/releases/tag/v1.0.0), and try again? should the problem resurface, please re-open the issue and ping @giograno or @thrau. thanks!

**Comment by nerochiaro** [comment]
Confirming as fixed. Thank you. :pray:
