### ISSUE TITLE
Unable to forward SNS message to SQS

### ISSUE THREAD

**Issue by thanh-doan-cko** [localstack/localstack#6315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Setup localstack docker version 0.12.15.

Init the following sns topic, sqs queues for my local testing

```

awslocal sns create-topic --name "local-test" --region "eu-west-1"

awslocal sqs create-queue --queue-name "local-test" --region "eu-west-1";

awslocal sns subscribe --topic-arn "arn:aws:sns:eu-west-1:000000000000:local-test" \
--protocol sqs --notification-endpoint "arn:aws:sqs:eu-west-1:000000000000:local-test" --region "eu-west-1"
```

Then I build a NET Core application to publish the message to SNS topic. It is working well, however the message is not able to forward to SQS due to the following issue

```
2022-06-21T16:04:28:INFO:localstack.services.sns.sns_listener: Unable to forward SNS message to SQS: Unable to find 'default' key in message payload Traceback (most recent call last):

File "/opt/code/localstack/localstack/services/sns/sns_listener.py", line 742, in create_sns_message_body

message = message.get(protocol, message["default"])

KeyError: 'default'

During handling of the above exception, another exception occurred:

File "/opt/code/localstack/localstack/services/sns/sns_listener.py", line 440, in message_to_subscriber

MessageBody=create_sns_message_body(subscriber, req_data, message_id),

File "/opt/code/localstack/localstack/services/sns/sns_listener.py", line 744, in create_sns_message_body

raise Exception("Unable to find 'default' key in message payload")
```

I tried with latest version of localstack and is having same issue.

Any ideas?

### Expected Behavior

Expected to see the messages in the SQS queue after execute the following command line

`awslocal sqs receive-message --queue-url http://localhost:4566/000000000000/local-test`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack 
 `docker-compose.yml`

```
version: "3.5"

services:
  localstack:
    hostname: localstack
    container_name: localstack
    restart: always
    image: localstack/localstack:0.12.15
    environment:
      - SERVICES=sqs,sns
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME=localstack
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - 4566:4566
    volumes:
    - ./images/localstack/scripts:/docker-entrypoint-initaws.d
```

Init.sh

```
awslocal sns create-topic --name "local-test" --region "eu-west-1"

awslocal sqs create-queue --queue-name "local-test" --region "eu-west-1";

awslocal sns subscribe --topic-arn "arn:aws:sns:eu-west-1:000000000000:local-test" \
--protocol sqs --notification-endpoint "arn:aws:sqs:eu-west-1:000000000000:local-test" --region "eu-west-1"

```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Run NET CORE app

Run 

`awslocal sqs receive-message --queue-url http://localhost:4566/000000000000/local-test`

Cannot find any messages due to

`Exception: Unable to find 'default' key in message payload`

### Environment

```markdown
- OS: Windows 11
- LocalStack: 0.12.15 and latest
```

**Comment by thanh-doan-cko** [comment]
@bentsku  thank you for your reply.

You are right. I set the  parameter `MessageStructure` to `json` then it is not working. I then removed it then it is working, I think I sent a string not a json.

Here is my codes

 ```
if (message == null)
        {
            throw new ArgumentNullException(nameof(message));
        }

         JsonSerializerOptions options = new() { DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull };
          var jsonMessage = JsonSerializer.Serialize(message, options);
        _logger.Information("Publishing the following message {Message} to  SnS topic",jsonMessage);

        var pubRequest = new PublishRequest(_financePaymentSnSSettings.TopicArn, jsonMessage)
        {
            MessageStructure = "json",
            MessageAttributes = GetSnsMessageTypeAttribute(AwsMessageType.Test)
        };
        var response = await _snsService.PublishAsync(pubRequest);
        return response;
```
I removed it then it is working now. 

I will have a look at your examples. 

Thanks
