### ISSUE TITLE
Does not start in 0.8.5 on Linux

### ISSUE THREAD

**Issue by StephanPraetsch** [localstack/localstack#634]
Hi,

I just installed localstack in version 0.8.5 and it does not start completely

```
stephan@lin-praetschs:~> DEBUG=1 localstack start
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock DynamoDB (http port 4569)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Error: Invalid or corrupt jarfile DynamoDBLocal.jar
Starting mock CloudWatch (http port 4582)...
Starting mock CloudFormation (http port 4581)...
Starting mock SSM (http port 4583)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Error: Unable to access jarfile /home/stephan/.local/lib/python2.7/site-packages/localstack/infra/elasticmq/elasticmq-server.jar
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
Listening at http://:::4565
* Running on http://0.0.0.0:4563/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4579/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4577/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4583/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4580/ (Press CTRL+C to quit)
[2018-03-02T11:14:19,263][INFO ][o.e.n.Node               ] [] initializing ...
[2018-03-02T11:14:19,331][INFO ][o.e.e.NodeEnvironment    ] [5CpZx5I] using [1] data paths, mounts [[/home/stephan (/home/stephan/.Private)]], net usable_space [133.6gb], net total_space [210.9gb], spins? [possibly], types [ecryptfs]
[2018-03-02T11:14:19,331][INFO ][o.e.e.NodeEnvironment    ] [5CpZx5I] heap size [483.3mb], compressed ordinary object pointers [true]
[2018-03-02T11:14:19,332][INFO ][o.e.n.Node               ] node name [5CpZx5I] derived from node ID [5CpZx5IFQuCCrsHk_fe3-w]; set [node.name] to override
[2018-03-02T11:14:19,332][INFO ][o.e.n.Node               ] version[5.3.0], pid[8689], build[3adb13b/2017-03-23T03:31:50.652Z], OS[Linux/4.13.0-36-generic/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_144/25.144-b01]
[2018-03-02T11:14:19,930][INFO ][o.e.p.PluginsService     ] [5CpZx5I] loaded module [aggs-matrix-stats]
[2018-03-02T11:14:19,930][INFO ][o.e.p.PluginsService     ] [5CpZx5I] loaded module [ingest-common]
[2018-03-02T11:14:19,930][INFO ][o.e.p.PluginsService     ] [5CpZx5I] loaded module [lang-expression]
[2018-03-02T11:14:19,930][INFO ][o.e.p.PluginsService     ] [5CpZx5I] loaded module [lang-groovy]
[2018-03-02T11:14:19,930][INFO ][o.e.p.PluginsService     ] [5CpZx5I] loaded module [lang-mustache]
[2018-03-02T11:14:19,930][INFO ][o.e.p.PluginsService     ] [5CpZx5I] loaded module [lang-painless]
[2018-03-02T11:14:19,930][INFO ][o.e.p.PluginsService     ] [5CpZx5I] loaded module [percolator]
[2018-03-02T11:14:19,931][INFO ][o.e.p.PluginsService     ] [5CpZx5I] loaded module [reindex]
[2018-03-02T11:14:19,931][INFO ][o.e.p.PluginsService     ] [5CpZx5I] loaded module [transport-netty3]
[2018-03-02T11:14:19,931][INFO ][o.e.p.PluginsService     ] [5CpZx5I] loaded module [transport-netty4]
[2018-03-02T11:14:19,931][INFO ][o.e.p.PluginsService     ] [5CpZx5I] no plugins loaded
[2018-03-02T11:14:21,323][INFO ][o.e.n.Node               ] initialized
[2018-03-02T11:14:21,323][INFO ][o.e.n.Node               ] [5CpZx5I] starting ...
[2018-03-02T11:14:21,437][INFO ][o.e.t.TransportService   ] [5CpZx5I] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2018-03-02T11:14:21,443][WARN ][o.e.b.BootstrapChecks    ] [5CpZx5I] initial heap size [209715200] not equal to maximum heap size [524288000]; this can cause resize pauses and prevents mlockall from locking the entire heap
[2018-03-02T11:14:21,444][WARN ][o.e.b.BootstrapChecks    ] [5CpZx5I] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2018-03-02T11:14:24,494][INFO ][o.e.c.s.ClusterService   ] [5CpZx5I] new_master {5CpZx5I}{5CpZx5IFQuCCrsHk_fe3-w}{idwG765eRRaJlsD7_OWlTQ}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2018-03-02T11:14:24,512][INFO ][o.e.h.n.Netty4HttpServerTransport] [5CpZx5I] publish_address {127.0.0.1:4560}, bound_addresses {[::1]:4560}, {127.0.0.1:4560}
[2018-03-02T11:14:24,515][INFO ][o.e.n.Node               ] [5CpZx5I] started
[2018-03-02T11:14:24,532][INFO ][o.e.g.GatewayService     ] [5CpZx5I] recovered [0] indices into cluster_state
2018-03-02T11:14:30:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f11006dca90>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/home/stephan/.local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 201, in forward
    headers=forward_headers)
  File "/home/stephan/.local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/stephan/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/stephan/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/stephan/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/stephan/.local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f11006dca90>: Failed to establish a new connection: [Errno 111] Connection refused',))

^C[2018-03-02T11:15:00,747][INFO ][o.e.n.Node               ] [5CpZx5I] stopping ...
[2018-03-02T11:15:00,850][INFO ][o.e.n.Node               ] [5CpZx5I] stopped
[2018-03-02T11:15:00,850][INFO ][o.e.n.Node               ] [5CpZx5I] closing ...
[2018-03-02T11:15:00,859][INFO ][o.e.n.Node               ] [5CpZx5I] closed
```

What do I see?

**DynamoDB**
```
Error: Invalid or corrupt jarfile DynamoDBLocal.jar`
```
This jar does only contain a log config - can't be intended?!
```
stephan@lin-praetschs:~> unzip -t .local/lib/python2.7/site-packages/localstack/infra/dynamodb/DynamoDBLocal.jar 
Archive:  .local/lib/python2.7/site-packages/localstack/infra/dynamodb/DynamoDBLocal.jar
    testing: log4j2.xml               OK
No errors detected in compressed data of .local/lib/python2.7/site-packages/localstack/infra/dynamodb/DynamoDBLocal.jar.
```

**ElasticMQ Server**
```
Error: Unable to access jarfile /home/stephan/.local/lib/python2.7/site-packages/localstack/infra/elasticmq/elasticmq-server.jar
```
The directory /home/stephan/.local/lib/python2.7/site-packages/localstack/infra/elasticmq/ is empty.

**Port 4564**
```
2018-03-02T11:12:53:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff26047de10>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/home/stephan/.local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 201, in forward
    headers=forward_headers)
```
Don't understand this as the port is not used by another process.
```
stephan@lin-praetschs:~> sudo netstat -tulpen | grep 4564
stephan@lin-praetschs:~> 
```

**My versions**
```
stephan@lin-praetschs:~> python --version
Python 2.7.12
stephan@lin-praetschs:~> pip --version
pip 9.0.1 from /home/stephan/.local/lib/python2.7/site-packages (python 2.7)
stephan@lin-praetschs:~> localstack --version
0.8.5
```

Can I support you with any other informations?

Kind regards
Stephan

**Comment by whummer** [comment]
Thanks for reporting @StephanPraetsch . Can you try deleting these two files, then starting up LocalStack again:
* .local/lib/python2.7/site-packages/localstack/infra/dynamodb/DynamoDBLocal.jar
* /home/stephan/.local/lib/python2.7/site-packages/localstack/infra/elasticmq/elasticmq-server.jar

**Comment by StephanPraetsch** [comment]
After deleting dynamodb jar (the elasticmq jar does not exist, even parent folder doesnt exist) there is no difference

```
stephan@lin-praetschs:~> rm .local/lib/python2.7/site-packages/localstack/infra/dynamodb/DynamoDBLocal.jar
stephan@lin-praetschs:~> rm /home/stephan/.local/lib/python2.7/site-packages/localstack/infra/elasticmq/elasticmq-server.jar
rm: cannot remove '/home/stephan/.local/lib/python2.7/site-packages/localstack/infra/elasticmq/elasticmq-server.jar': No such file or directory
stephan@lin-praetschs:~> 
stephan@lin-praetschs:~> 
stephan@lin-praetschs:~> 
stephan@lin-praetschs:~> DEBUG=1 localstack start
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock DynamoDB (http port 4569)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Error: Invalid or corrupt jarfile DynamoDBLocal.jar
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudWatch (http port 4582)...
Starting mock CloudFormation (http port 4581)...
Starting mock SSM (http port 4583)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Error: Unable to access jarfile /home/stephan/.local/lib/python2.7/site-packages/localstack/infra/elasticmq/elasticmq-server.jar
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
Listening at http://:::4565
* Running on http://0.0.0.0:4563/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4579/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4577/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4583/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4580/ (Press CTRL+C to quit)
[2018-03-05T10:25:28,524][INFO ][o.e.n.Node               ] [] initializing ...
[2018-03-05T10:25:28,595][INFO ][o.e.e.NodeEnvironment    ] [WMth8Jj] using [1] data paths, mounts [[/home/stephan (/home/stephan/.Private)]], net usable_space [133.6gb], net total_space [210.9gb], spins? [possibly], types [ecryptfs]
[2018-03-05T10:25:28,595][INFO ][o.e.e.NodeEnvironment    ] [WMth8Jj] heap size [483.3mb], compressed ordinary object pointers [true]
[2018-03-05T10:25:28,596][INFO ][o.e.n.Node               ] node name [WMth8Jj] derived from node ID [WMth8JjuRg6DBwrFr2VBnA]; set [node.name] to override
[2018-03-05T10:25:28,597][INFO ][o.e.n.Node               ] version[5.3.0], pid[9544], build[3adb13b/2017-03-23T03:31:50.652Z], OS[Linux/4.13.0-36-generic/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_144/25.144-b01]
[2018-03-05T10:25:29,124][INFO ][o.e.p.PluginsService     ] [WMth8Jj] loaded module [aggs-matrix-stats]
[2018-03-05T10:25:29,124][INFO ][o.e.p.PluginsService     ] [WMth8Jj] loaded module [ingest-common]
[2018-03-05T10:25:29,125][INFO ][o.e.p.PluginsService     ] [WMth8Jj] loaded module [lang-expression]
[2018-03-05T10:25:29,125][INFO ][o.e.p.PluginsService     ] [WMth8Jj] loaded module [lang-groovy]
[2018-03-05T10:25:29,125][INFO ][o.e.p.PluginsService     ] [WMth8Jj] loaded module [lang-mustache]
[2018-03-05T10:25:29,125][INFO ][o.e.p.PluginsService     ] [WMth8Jj] loaded module [lang-painless]
[2018-03-05T10:25:29,125][INFO ][o.e.p.PluginsService     ] [WMth8Jj] loaded module [percolator]
[2018-03-05T10:25:29,125][INFO ][o.e.p.PluginsService     ] [WMth8Jj] loaded module [reindex]
[2018-03-05T10:25:29,125][INFO ][o.e.p.PluginsService     ] [WMth8Jj] loaded module [transport-netty3]
[2018-03-05T10:25:29,125][INFO ][o.e.p.PluginsService     ] [WMth8Jj] loaded module [transport-netty4]
[2018-03-05T10:25:29,126][INFO ][o.e.p.PluginsService     ] [WMth8Jj] no plugins loaded
[2018-03-05T10:25:30,579][INFO ][o.e.n.Node               ] initialized
[2018-03-05T10:25:30,579][INFO ][o.e.n.Node               ] [WMth8Jj] starting ...
[2018-03-05T10:25:30,679][INFO ][o.e.t.TransportService   ] [WMth8Jj] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2018-03-05T10:25:30,685][WARN ][o.e.b.BootstrapChecks    ] [WMth8Jj] initial heap size [209715200] not equal to maximum heap size [524288000]; this can cause resize pauses and prevents mlockall from locking the entire heap
[2018-03-05T10:25:30,685][WARN ][o.e.b.BootstrapChecks    ] [WMth8Jj] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2018-03-05T10:25:33,722][INFO ][o.e.c.s.ClusterService   ] [WMth8Jj] new_master {WMth8Jj}{WMth8JjuRg6DBwrFr2VBnA}{T8SaSeWHRDiA-timo30ymw}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2018-03-05T10:25:33,738][INFO ][o.e.h.n.Netty4HttpServerTransport] [WMth8Jj] publish_address {127.0.0.1:4560}, bound_addresses {[::1]:4560}, {127.0.0.1:4560}
[2018-03-05T10:25:33,740][INFO ][o.e.n.Node               ] [WMth8Jj] started
[2018-03-05T10:25:33,757][INFO ][o.e.g.GatewayService     ] [WMth8Jj] recovered [0] indices into cluster_state
2018-03-05T10:25:39:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8b7818da90>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/home/stephan/.local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 201, in forward
    headers=forward_headers)
  File "/home/stephan/.local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/stephan/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/stephan/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/stephan/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/stephan/.local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8b7818da90>: Failed to establish a new connection: [Errno 111] Connection refused',))

^C[2018-03-05T10:26:05,171][INFO ][o.e.n.Node               ] [WMth8Jj] stopping ...
[2018-03-05T10:26:05,325][INFO ][o.e.n.Node               ] [WMth8Jj] stopped
[2018-03-05T10:26:05,325][INFO ][o.e.n.Node               ] [WMth8Jj] closing ...
[2018-03-05T10:26:05,333][INFO ][o.e.n.Node               ] [WMth8Jj] closed
stephan@lin-praetschs:~> 
```

the dynamodb jar still / again contains only log4j config
```
stephan@lin-praetschs:~> unzip -t .local/lib/python2.7/site-packages/localstack/infra/dynamodb/DynamoDBLocal.jar 
Archive:  .local/lib/python2.7/site-packages/localstack/infra/dynamodb/DynamoDBLocal.jar
    testing: log4j2.xml               OK
No errors detected in compressed data of .local/lib/python2.7/site-packages/localstack/infra/dynamodb/DynamoDBLocal.jar.
```

**Comment by whummer** [comment]
Can you please post the output of this:
```
echo $TMPDIR
ls -la $TMPDIR/localstack.es.zip
rm $TMPDIR/localstack.es.zip
rm .local/lib/python2.7/site-packages/localstack/infra/dynamodb/DynamoDBLocal.jar
DEBUG=1 localstack start
```

**Comment by StephanPraetsch** [comment]
There is no TMPDIR environment variable or anything similiar on my Ubuntu 16.04
```
stephan@lin-praetschs:~> env | grep -i mp
ORBIT_SOCKETDIR=/tmp/orbit-stephan
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SESSION_MANAGER=local/lin-praetschs:@/tmp/.ICE-unix/2335,unix/lin-praetschs:/tmp/.ICE-unix/2335
COMPIZ_CONFIG_PROFILE=ubuntu
COMPIZ_BIN_PATH=/usr/bin/
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-HaY7yQcbR4
```

Current state in /tmp is
```
stephan@lin-praetschs:~> ls -la /tmp/localstack/
total 44
drwxrwxr-x  2 stephan stephan  4096 Mär  5 10:29 .
drwxrwxrwt 21 root    root    32768 Mär  5 14:20 ..
-rw-rw-r--  1 stephan stephan     2 Mär  5 10:23 .localstack
stephan@lin-praetschs:~> cat /tmp/localstack/.localstack 
{}
```

Might you adjust your commands?

**Comment by whummer** [comment]
I see. This should print the temp folder that python is using:
```
python -c 'import tempfile; print(tempfile.gettempdir())'
```

**Comment by StephanPraetsch** [comment]
Yup, that's /tmp
```
stephan@lin-praetschs:~> python -c 'import tempfile; print(tempfile.gettempdir())'
/tmp
```

**Comment by nseilaz** [comment]
I'm also having difficulty with DynamoDB.  My configuration is CENTOS 

Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: /usr/local/maven
Java version: 1.8.0_161, vendor: Oracle Corporation
Java home: /opt/jdk1.8.0_161/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-693.21.1.el7.x86_64", arch: "amd64", family: "unix"
The DynamoDB reports --> WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...

I was able to connect to S3 and create folder and put a file without an issue before it crashes out.

I am running it under a non root user

-------------------------------
Here is the output 

[localstack@localstack bin]$ ./localstack start
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock DynamoDB (http port 4569)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudWatch (http port 4582)...
Starting mock CloudFormation (http port 4581)...
Starting mock SSM (http port 4583)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
2018-03-14T21:00:11:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2018-03-14T21:00:40:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2018-03-14T21:01:09:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2018-03-14T21:01:37:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2018-03-14T21:02:06:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2018-03-14T21:02:35:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2018-03-14T21:03:03:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2018-03-14T21:03:32:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2018-03-14T21:04:01:ERROR:localstack.services.dynamodb.dynamodb_starter: DynamoDB health check failed: Could not connect to the endpoint URL: "http://localstack.local:4569/" Traceback (most recent call last):
  File "/home/localstack/.local/lib/python2.7/site-packages/localstack/services/dynamodb/dynamodb_starter.py", line 20, in check_dynamodb
    out = aws_stack.connect_to_service(service_name='dynamodb').list_tables()
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 172, in _send_request
    success_response, exception):
  File "/usr/lib/python2.7/site-packages/botocore/endpoint.py", line 265, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "http://localstack.local:4569/"

2018-03-14T21:04:01:WARNING:infra.pyc: Service "dynamodb" not yet available, retrying...
2018-03-14T21:04:01:ERROR:infra.pyc: Error checking state of local environment (after some retries): Traceback (most recent call last):
  File "/home/localstack/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 344, in check_infra
    raise e
TypeError: 'NoneType' object has no attribute '__getitem__'

Error starting infrastructure: 'NoneType' object has no attribute '__getitem__' Traceback (most recent call last):
  File "/home/localstack/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 482, in start_infra
    check_infra(apis=apis)
  File "/home/localstack/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 353, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/localstack/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 353, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/localstack/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 353, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/localstack/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 353, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/localstack/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 353, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/localstack/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 353, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/localstack/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 353, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/localstack/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 353, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/home/localstack/.local/lib/python2.7/site-packages/localstack/services/infra.py", line 351, in check_infra
    raise e
TypeError: 'NoneType' object has no attribute '__getitem__'

ERROR: 'NoneType' object has no attribute '__getitem__'
[localstack@localstack bin]$

**Comment by insanitybit** [comment]
I'm also getting the same error with corrupt dynamodb jar file. I tried deleting it, didn't help.

**Comment by giannisbetas** [comment]
@StephanPraetsch did you manage to solve this?
I am getting the same error with `localstack-0.8.7`.

```
$ DEBUG=1 localstack start
Starting local dev environment. CTRL-C to quit.
Starting mock DynamoDB (http port 4569)...
Starting mock Kinesis (http port 4568)...
Error: Invalid or corrupt jarfile DynamoDBLocal.jar
Listening at http://:::4565
2018-08-22T18:29:20:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10664df90>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

**Comment by StephanPraetsch** [comment]
Nope, didn't solve that yet. Unfortunately I didn't have time to redo some tests. I just tried with ubuntu 18.04 within docker (https://github.com/StephanPraetsch/dockers/blob/master/localstack/Dockerfile) but the error is different now: elasticsearch is unavailable
```
2018-08-23T09:16:12:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
127.0.0.1 - - [23/Aug/2018 09:16:15] "GET / HTTP/1.1" 200 -
2018-08-23T09:16:15:ERROR:localstack.services.es.es_starter: Elasticsearch health check failed (retrying...): TransportError(502, u'') Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/es/es_starter.py", line 59, in check_elasticsearch
    out = es.cat.aliases()
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/cat.py", line 23, in aliases
    'aliases', name), params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
TransportError: TransportError(502, u'')

2018-08-23T09:16:15:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2018-08-23T09:16:15:ERROR:infra.pyc: Error checking state of local environment (after some retries): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/localstack/services/infra.py", line 344, in check_infra
    raise e
AssertionError
```

**Comment by whummer** [comment]
Closing this as outdated/obsolete. Recommended (and default) option is to start in Docker, which should fix the issues mentioned here.
