### ISSUE TITLE
bug: SQS doesn't work with PROVIDER_OVERRIDE_SQS=asf

### ISSUE THREAD

**Issue by a-wi** [localstack/localstack#6358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

SQS is not operational when `asf` provider is selected with environment variable `PROVIDER_OVERRIDE_SQS=asf`.
On every attempt to access to SQS there is logged error message on the localstack console:
```
2022-06-28T07:46:50.669:DEBUG:localstack.utils.threads: FINISHED: <Future at 0x7f063bfe5600 state=finished raised HTTPErrorResponse>
2022-06-28T07:46:50.669:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: no provider exists for service sqs Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 185, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 85, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 993, in handler
    return modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 163, in forward_request
    self._require_service(api)
  File "/opt/code/localstack/localstack/services/edge.py", line 215, in _require_service
    raise HTTPErrorResponse("no provider exists for service %s" % api, code=500)
localstack.utils.server.http2_server.HTTPErrorResponse: no provider exists for service sqs
```

### Expected Behavior

SQS should be operational when `PROVIDER_OVERRIDE_SQS=asf` is set.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   docker run -p 4566:4566 --rm -e SERVICES=sqs -e DEBUG=1 -e PROVIDER_OVERRIDE_SQS=asf  localstack/localstack:0.14.4

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws sqs create-queue --queue-name testQueue --endpoint-url http://localhost:4566

   Returns:
   `Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
b'{}'`

### Environment

```markdown
- OS:Win 10
- LocalStack: 0.14.4
- AWS CLI: 2.7.6
```

**Comment by thrau** [comment]
hi @a-wi, the sqs provider you are trying to activate is now the default, simply remove the provider override config and you should be good to go

**Comment by a-wi** [comment]
Default provider indeed seems to work fine. I'm glad it's ASF.
