### ISSUE TITLE
Error while creating the dynamodb table using python3 in the latest version 0.14.4

### ISSUE THREAD

**Issue by anekar3416** [localstack/localstack#6364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a python script which inserts data into the existing dynamo table.
Earlier I was using the localstack version 0.14.2 and the script was executing smoothly always. Now with the latest 0.14.4 version I am getting following error:

```
my-localstack  | 2022-06-28T14:58:49.942:INFO:localstack.utils.threads: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0xffff1c7f25f0>(None) failed: Object of type bytes is not JSON serializable Traceback (most recent call last):
my-localstack  |   File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run
my-localstack  |     result = self.func(self.params, **kwargs)
my-localstack  |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
my-localstack  |     return fn(*args, **kwargs)
my-localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 993, in handler
my-localstack  |     return modify_and_forward(
my-localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
my-localstack  |     value = func(*args, **kwargs)
my-localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
my-localstack  |     listener_result = listener.forward_request(
my-localstack  |   File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request
my-localstack  |     result = do_forward_request(api, method, path, data, headers, port=port)
my-localstack  |   File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
my-localstack  |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
my-localstack  |   File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
my-localstack  |     response = modify_and_forward(
my-localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
my-localstack  |     value = func(*args, **kwargs)
my-localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
my-localstack  |     listener_result = listener.forward_request(
my-localstack  |   File "/opt/code/localstack/localstack/http/adapters.py", line 51, in forward_request
my-localstack  |     response = self.request(request)
my-localstack  |   File "/opt/code/localstack/localstack/aws/proxy.py", line 43, in request
my-localstack  |     return self.skeleton.invoke(context)
my-localstack  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
my-localstack  |     return self.dispatch_request(context, instance)
my-localstack  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
my-localstack  |     result = handler(context, instance) or {}
my-localstack  |   File "/opt/code/localstack/localstack/aws/forwarder.py", line 57, in _call
my-localstack  |     return handler(context, req)
my-localstack  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
my-localstack  |     return self.fn(*args, **kwargs)
my-localstack  |   File "/opt/code/localstack/localstack/aws/api/core.py", line 99, in operation_marker
my-localstack  |     return fn(*args, **kwargs)
my-localstack  |   File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 553, in put_item
my-localstack  |     "SizeBytes": len(json.dumps(item)),
my-localstack  |   File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
my-localstack  |     return _default_encoder.encode(obj)
my-localstack  |   File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
my-localstack  |     chunks = self.iterencode(o, _one_shot=True)
my-localstack  |   File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
my-localstack  |     return _iterencode(o, 0)
my-localstack  |   File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
my-localstack  |     raise TypeError(f'Object of type {o.__class__.__name__} '
my-localstack  | TypeError: Object of type bytes is not JSON serializable
my-localstack  |
my-localstack  | 2022-06-28T14:58:49.943:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: Object of type bytes is not JSON serializable Traceback (most recent call last):
my-localstack  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 185, in index
my-localstack  |     result = await run_sync(handler, request, data)
my-localstack  |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 85, in run_sync
my-localstack  |     return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
my-localstack  |   File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run
my-localstack  |     result = self.func(self.params, **kwargs)
my-localstack  |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
my-localstack  |     return fn(*args, **kwargs)
my-localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 993, in handler
my-localstack  |     return modify_and_forward(
my-localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
my-localstack  |     value = func(*args, **kwargs)
my-localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
my-localstack  |     listener_result = listener.forward_request(
my-localstack  |   File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request
my-localstack  |     result = do_forward_request(api, method, path, data, headers, port=port)
my-localstack  |   File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
my-localstack  |     result = do_forward_request_inmem(api, method, path, data, headers, port=port)
my-localstack  |   File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
my-localstack  |     response = modify_and_forward(
my-localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
my-localstack  |     value = func(*args, **kwargs)
my-localstack  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
my-localstack  |     listener_result = listener.forward_request(
my-localstack  |   File "/opt/code/localstack/localstack/http/adapters.py", line 51, in forward_request
my-localstack  |     response = self.request(request)
my-localstack  |   File "/opt/code/localstack/localstack/aws/proxy.py", line 43, in request
my-localstack  |     return self.skeleton.invoke(context)
my-localstack  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
my-localstack  |     return self.dispatch_request(context, instance)
my-localstack  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
my-localstack  |     result = handler(context, instance) or {}
my-localstack  |   File "/opt/code/localstack/localstack/aws/forwarder.py", line 57, in _call
my-localstack  |     return handler(context, req)
my-localstack  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
my-localstack  |     return self.fn(*args, **kwargs)
my-localstack  |   File "/opt/code/localstack/localstack/aws/api/core.py", line 99, in operation_marker
my-localstack  |     return fn(*args, **kwargs)
my-localstack  |   File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 553, in put_item
my-localstack  |     "SizeBytes": len(json.dumps(item)),
my-localstack  |   File "/usr/local/lib/python3.10/json/__init__.py", line 231, in dumps
my-localstack  |     return _default_encoder.encode(obj)
my-localstack  |   File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
my-localstack  |     chunks = self.iterencode(o, _one_shot=True)
my-localstack  |   File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
my-localstack  |     return _iterencode(o, 0)
my-localstack  |   File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
my-localstack  |     raise TypeError(f'Object of type {o.__class__.__name__} '
my-localstack  | TypeError: Object of type bytes is not JSON serializable
my-localstack  |
my-localstack  | 2022-06-28T14:58:49.996:INFO:localstack.services.dynamodb.server: 14:58:49.988 [qtp1213871206-19] WARN  com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler - DynamoDBLocalServiceException exception occured
my-localstack  | 2022-06-28T14:58:49.996:INFO:localstack.services.dynamodb.server: com.amazonaws.services.dynamodbv2.exceptions.DynamoDBLocalServiceException: The conditional request failed
my-localstack  | 2022-06-28T14:58:49.996:INFO:localstack.services.dynamodb.server: at com.amazonaws.services.dynamodbv2.exceptions.AWSExceptionFactory.buildLocalServiceException(AWSExceptionFactory.java:93) ~[DynamoDBLocal.jar:?]
my-localstack  | 2022-06-28T14:58:49.996:INFO:localstack.services.dynamodb.server: at com.amazonaws.services.dynamodbv2.exceptions.AWSExceptionFactory.buildAWSException(AWSExceptionFactory.java:58) ~[DynamoDBLocal.jar:?]
my-localstack  | 2022-06-28T14:58:49.996:INFO:localstack.services.dynamodb.server: at com.amazonaws.services.dynamodbv2.local.shared.access.api.dp.PutItemFunction.putItemConditionalOperator(PutItemFunction.java:153) ~[DynamoDBLocal.jar:?]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at com.amazonaws.services.dynamodbv2.local.shared.access.api.dp.PutItemFunction.access$000(PutItemFunction.java:28) ~[DynamoDBLocal.jar:?]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at com.amazonaws.services.dynamodbv2.local.shared.access.api.dp.PutItemFunction$3.criticalSection(PutItemFunction.java:108) ~[DynamoDBLocal.jar:?]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDBAccess$WriteLockWithTimeout.execute(LocalDBAccess.java:361) ~[DynamoDBLocal.jar:?]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at com.amazonaws.services.dynamodbv2.local.shared.access.api.dp.PutItemFunction.apply(PutItemFunction.java:111) ~[DynamoDBLocal.jar:?]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at com.amazonaws.services.dynamodbv2.local.shared.access.awssdkv1.client.LocalAmazonDynamoDB.putItem(LocalAmazonDynamoDB.java:289) ~[DynamoDBLocal.jar:?]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.putItem(LocalDynamoDBRequestHandler.java:359) ~[DynamoDBLocal.jar:?]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at com.amazonaws.services.dynamodbv2.local.dispatchers.PutItemDispatcher.enact(PutItemDispatcher.java:18) ~[DynamoDBLocal.jar:?]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at com.amazonaws.services.dynamodbv2.local.dispatchers.PutItemDispatcher.enact(PutItemDispatcher.java:12) ~[DynamoDBLocal.jar:?]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.packageDynamoDBResponse(LocalDynamoDBServerHandler.java:395) [DynamoDBLocal.jar:?]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.handle(LocalDynamoDBServerHandler.java:482) [DynamoDBLocal.jar:?]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) [jetty-server-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345) [jetty-server-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:205) [jetty-server-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247) [jetty-server-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [jetty-server-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220) [jetty-server-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.server.Server.handle(Server.java:505) [jetty-server-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370) [jetty-server-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267) [jetty-server-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [jetty-io-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [jetty-io-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698) [jetty-util-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804) [jetty-util-9.4.18.v20190429.jar:9.4.18.v20190429]
my-localstack  | 2022-06-28T14:58:49.997:INFO:localstack.services.dynamodb.server: at java.lang.Thread.run(Unknown Source) [?:?]
```

The table gets created but the response code from the dynamodb is 409 ! 

This is the structure of my table:

```

{
    "Table": {
        "AttributeDefinitions": [
            {
                "AttributeName": "attr1",
                "AttributeType": "S"
            },
            {
                "AttributeName": "attr2",
                "AttributeType": "S"
            },
            {
                "AttributeName": "attr3",
                "AttributeType": "S"
            }
        ],
        "TableName": "myTable",
        "KeySchema": [
            {
                "AttributeName": "attr2",
                "KeyType": "HASH"
            },
            {
                "AttributeName": "attr1",
                "KeyType": "RANGE"
            }
        ],
        "TableStatus": "ACTIVE",
        "CreationDateTime": 1656428276.912,
        "ProvisionedThroughput": {
            "LastIncreaseDateTime": 0.0,
            "LastDecreaseDateTime": 0.0,
            "NumberOfDecreasesToday": 0,
            "ReadCapacityUnits": 5,
            "WriteCapacityUnits": 5
        },
        "TableSizeBytes": 0,
        "ItemCount": 0,
        "TableArn": "arn:aws:dynamodb:us-east-1:000000000000:table/myTable",
        "GlobalSecondaryIndexes": [
            {
                "IndexName": "myTable-id",
                "KeySchema": [
                    {
                        "AttributeName": "attr2",
                        "KeyType": "HASH"
                    },
                    {
                        "AttributeName": "attr3",
                        "KeyType": "RANGE"
                    }
                ],
                "Projection": {
                    "ProjectionType": "ALL"
                },
                "IndexStatus": "ACTIVE",
                "ProvisionedThroughput": {
                    "ReadCapacityUnits": 5,
                    "WriteCapacityUnits": 5
                },
                "IndexSizeBytes": 0,
                "ItemCount": 0,
                "IndexArn": "arn:aws:dynamodb:ddblocal:000000000000:table/myTable/index/myTable-id"
            }
        ],
        "StreamSpecification": {
            "StreamEnabled": true,
            "StreamViewType": "NEW_AND_OLD_IMAGES"
        },
        "LatestStreamLabel": "2022-06-28T14:57:56.912",
        "LatestStreamArn": "arn:aws:dynamodb:us-east-1:000000000000:table/myTable/stream/2022-06-28T14:57:56.912"
    }
}
```

I am using Python 3.9.13

### Expected Behavior

The table should be created with a proper response code of 201 or 200.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

My docker compose compose file looks like this:
```
version: '3.8'
services:
  my--localstack:
    container_name: my-localstack
    image: localstack/localstack:0.14.4
    ports:
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:4566:4566"
    volumes:
      - "localstack-data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  localstack-data:
```

### Environment

```markdown
- OS: MAC OS, M1 Chip
- LocalStack: 0.14.4
```

**Comment by anekar3416** [comment]
I am facing same issue with the 0.14.3 as well.

**Comment by giograno** [comment]
Hi @anekar3416, we released a fix that should the errors in the logs you mentioned. Could you please give it a try by pulling the `latest` docker images and let us know? Thank you very much.

**Comment by macsj200** [comment]
I have seen this error on localstack `1.0.1`:
`com.amazonaws.services.dynamodbv2.exceptions.DynamoDBLocalServiceException: The conditional request failed`

I will try it with `1.0.3` and see what happens.

For some reason, the integration test suite seems to run fine locally on my Mac, but when I push it up to Jenkins (linux) it fails.

**Comment by giograno** [comment]
Going to close this one, as it seems solved from our side. Please feel free to re-open it if any other issue occurs.
