### ISSUE TITLE
bug: cannot create GrahpQL API Resource

### ISSUE THREAD

**Issue by ginger-OS** [localstack/localstack#6367]
### Is there an existing issue for this?

- [X] I have searched the existing issues:

https://github.com/localstack/localstack/issues/4645 - closed as fixed, but doesn't seem to be the case

### Current Behavior

When creating a graphQLApi like this:

```
// lib/appsync-cdk-app-stack.ts
import * as cdk from 'aws-cdk-lib';
import * as appsync from '@aws-cdk/aws-appsync-alpha';
import { Construct } from 'constructs';
import { join } from 'path';

export class AppsynctestStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Creates the AppSync API
    const api = new appsync.GraphqlApi(this, 'Api', {
      name: 'cdk-notes-appsync-api',
      schema: appsync.Schema.fromAsset(
        join(__dirname, 'schema.graphql')
     ),
      authorizationConfig: {
        defaultAuthorization: {
          authorizationType: appsync.AuthorizationType.API_KEY,
          apiKeyConfig: {
            expires: cdk.Expiration.after(cdk.Duration.days(365))
          }
        },
      },
      xrayEnabled: true,
    });

    // Prints out the AppSync GraphQL endpoint to the terminal
    new cdk.CfnOutput(this, "GraphQLAPIURL", {
     value: api.graphqlUrl
    });

    // Prints out the AppSync GraphQL API key to the terminal
    new cdk.CfnOutput(this, "GraphQLAPIKey", {
      value: api.apiKey || ''
    });

    // Prints out the stack region to the terminal
    new cdk.CfnOutput(this, "Stack Region", {
      value: this.region
    });
  }
}
```

Stack creation fails with the following error (Schema definiton cut out):

```
localstack_main  | 2022-06-28T17:55:42.402:DEBUG:localstack.services.plugins: checking service health sts:4566
localstack_main  | 2022-06-28T17:55:42.968:WARNING:localstack.aws.protocol.serializer: Response object DescribeChangeSetOutput contains a member which is not specified: RoleARN
localstack_main  | 2022-06-28T17:55:42.968:WARNING:localstack.aws.protocol.serializer: Response object DescribeChangeSetOutput contains a member which is not specified: ChangeSetType
localstack_main  | 2022-06-28T17:55:42.968:WARNING:localstack.aws.protocol.serializer: Response object DescribeChangeSetOutput contains a member which is not specified: StackStatus
localstack_main  | 2022-06-28T17:55:43.009:DEBUG:localstack.services.cloudformation.provider: Executing change set "cdk-deploy-change-set" for stack "AppSyncStack" with 4 resources ...
localstack_main  | 2022-06-28T17:55:44.158:INFO:localstack_ext.utils.websockets: Starting websocket server on port 4511
localstack_main  | 2022-06-28T17:55:44.170:INFO:websockets.server: server listening on 0.0.0.0:4511
localstack_main  | 2022-06-28T17:55:44.675:DEBUG:localstack.services.plugins: checking service health appsync:4566
localstack_main  | 2022-06-28T17:55:44.716:DEBUG:localstack.services.cloudformation.provider: Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['graphqlapi8420BC4B', 'GraphQLUrl']}} - Unable to fetch details for resource "graphqlapi8420BC4B" (resolving attribute "GraphQLUrl")
localstack_main  | 2022-06-28T17:55:44.717:INFO:localstack_ext.utils.websockets: Starting websocket server on port 4512
localstack_main  | 2022-06-28T17:55:44.718:INFO:websockets.server: server listening on 0.0.0.0:4512
localstack_main  | 2022-06-28T17:55:44.732:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "graphqlapi8420BC4B" (1/4) type "AWS::AppSync::GraphQLApi" in loop iteration 1 (should_deploy=True)
localstack_main  | 2022-06-28T17:55:44.732:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "AppSync::GraphQLApi" id "graphqlapi8420BC4B"
localstack_main  | 2022-06-28T17:55:44.744:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "AppSync::GraphQLApi" in region eu-central-1: create_graphql_api {'authenticationType': 'API_KEY', 'name': 'graphql-api-Local', 'xrayEnabled': True}
localstack_main  | 2022-06-28T17:55:44.867:DEBUG:localstack.services.cloudformation.provider: Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['graphqlapiDefaultApiKey96890FAB', 'ApiKey']}} - Unable to fetch details for resource "graphqlapiDefaultApiKey96890FAB" (resolving attribute "ApiKey")
localstack_main  | 2022-06-28T17:55:44.919:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "graphqlapiSchema91C9E870" (1/3) type "AWS::AppSync::GraphQLSchema" in loop iteration 1 (should_deploy=True)
localstack_main  | 2022-06-28T17:55:44.945:DEBUG:localstack.utils.cloudformation.template_deployer: Running action "create" for resource type "AppSync::GraphQLSchema" id "graphqlapiSchema91C9E870"
localstack_main  | 2022-06-28T17:55:44.959:DEBUG:localstack.utils.cloudformation.template_deployer: Request for resource type "AppSync::GraphQLSchema" in region eu-central-1: start_schema_creation {'apiId': 'd0766572', 'definition': '...'}
localstack_main  | 2022-06-28T17:55:45.161:DEBUG:localstack.services.cloudformation.provider: Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['graphqlapiDefaultApiKey96890FAB', 'ApiKey']}, 'Export': {'Name': 'AppSyncStack:ExportsOutputFnGetAttgraphqlapiDefaultApiKey96890FABApiKeyD43FD91E'}} - Unable to fetch details for resource "graphqlapiDefaultApiKey96890FAB" (resolving attribute "ApiKey")
localstack_main  | 2022-06-28T17:55:45.176:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "graphqlapiDefaultApiKey96890FAB" (1/2) type "AWS::AppSync::ApiKey" in loop iteration 1 (should_deploy=True)
localstack_main  | 2022-06-28T17:55:45.233:DEBUG:localstack.utils.cloudformation.template_deployer: Dependency for resource {'Type': 'AWS::AppSync::ApiKey', 'DependsOn': ['graphqlapiSchema91C9E870'], 'Metadata': {'aws:cdk:path': 'AppSyncStack/graphql-api/DefaultApiKey'}, 'LogicalResourceId': 'graphqlapiDefaultApiKey96890FAB', 'Properties': {'ApiId': 'd0766572', 'Expires': 1687974935}, '_state_': {}} not yet deployed: graphqlapiSchema91C9E870 {'Type': 'AWS::AppSync::GraphQLSchema', 'Properties': {'ApiId': {'Fn::GetAtt': ['graphqlapi8420BC4B', 'ApiId']}, 'Definition': '...'}, 'Metadata': {'aws:cdk:path': 'AppSyncStack/graphql-api/Schema'}, 'LogicalResourceId': 'graphqlapiSchema91C9E870'}
localstack_main  | 2022-06-28T17:55:45.527:DEBUG:localstack.utils.cloudformation.template_deployer: Extract resource attribute: Parameter Ref
localstack_main  | 2022-06-28T17:55:45.773:WARNING:localstack.utils.cloudformation.template_deployer: Unable to deploy resource type "CDK::Metadata": {"Type": "AWS::CDK::Metadata", "Metadata": {"aws:cdk:path": "AppSyncStack/CDKMetadata/Default"}, "Condition": "CDKMetadataAvailable", "LogicalResourceId": "CDKMetadata", "Properties": {"Analytics": "v2:deflate64:H4sIAAAAAAAA/0WNyw6CMBBFv4V9O1CirjUsXGhihA8wtdQwPNpKWw0h/Lutkri6d85N5uQwsy1kCX9bKuqO9niHuXJcdCSgGzfGTkrAXDzUceSmuZ4PBsn/qkQjBx5B4Cc5LbFevDPexVZKq/0oZOyFVjU61GohLIeM8t40PKj3qzuNuQrX8St59uH1QpSuJbQ2fbEdsA3kSWsR6eiVw0FC+csPQXWyW88AAAA=", "PhysicalResourceId": "cdk-meta-265916bb"}, "_state_": {"type": "AWS::CDK::Metadata"}}
localstack_main  | 2022-06-28T17:55:45.774:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "CDKMetadata" (2/2) type "AWS::CDK::Metadata" in loop iteration 1 (should_deploy=False)
localstack_main  | 2022-06-28T17:55:45.798:DEBUG:localstack.utils.cloudformation.template_deployer: Handling "Add" for resource "graphqlapiDefaultApiKey96890FAB" (1/1) type "AWS::AppSync::ApiKey" in loop iteration 2 (should_deploy=True)
localstack_main  | 2022-06-28T17:55:45.818:DEBUG:localstack.utils.cloudformation.template_deployer: Dependency for resource {'Type': 'AWS::AppSync::ApiKey', 'DependsOn': ['graphqlapiSchema91C9E870'], 'Metadata': {'aws:cdk:path': 'AppSyncStack/graphql-api/DefaultApiKey'}, 'LogicalResourceId': 'graphqlapiDefaultApiKey96890FAB', 'Properties': {'ApiId': 'd0766572', 'Expires': 1687974935}, '_state_': {}} not yet deployed: graphqlapiSchema91C9E870 {'Type': 'AWS::AppSync::GraphQLSchema', 'Properties': {'ApiId': {'Fn::GetAtt': ['graphqlapi8420BC4B', 'ApiId']}, 'Definition': '...'}, 'Metadata': {'aws:cdk:path': 'AppSyncStack/graphql-api/Schema'}, 'LogicalResourceId': 'graphqlapiSchema91C9E870'}
localstack_main  | 2022-06-28T17:55:45.818:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "AppSyncStack": Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'graphqlapiDefaultApiKey96890FAB', 'PhysicalResourceId': None, 'ResourceType': 'AWS::AppSync::ApiKey', 'Replacement': 'False', 'ChangeSetId': None}}] Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1548, in _run
localstack_main  |     self.do_apply_changes_in_loop(changes, stack, stack_name)
localstack_main  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1639, in do_apply_changes_in_loop
localstack_main  |     raise Exception(
localstack_main  | Exception: Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'graphqlapiDefaultApiKey96890FAB', 'PhysicalResourceId': None, 'ResourceType': 'AWS::AppSync::ApiKey', 'Replacement': 'False', 'ChangeSetId': None}}]
localstack_main  |
localstack_main  | 2022-06-28T17:55:50.268:DEBUG:localstack.services.cloudformation.provider: Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['graphqlapiDefaultApiKey96890FAB', 'ApiKey']}} - Unable to fetch details for resource "graphqlapiDefaultApiKey96890FAB" (resolving attribute "ApiKey")
localstack_main  | 2022-06-28T17:55:50.304:DEBUG:localstack.services.cloudformation.provider: Unable to resolve references in stack outputs: {'Value': {'Fn::GetAtt': ['graphqlapiDefaultApiKey96890FAB', 'ApiKey']}, 'Export': {'Name': 'AppSyncStack:ExportsOutputFnGetAttgraphqlapiDefaultApiKey96890FABApiKeyD43FD91E'}} - Unable to fetch details for resource "graphqlapiDefaultApiKey96890FAB" (resolving attribute "ApiKey")
```

### Expected Behavior

Stakc is created like on AWS.

### How are you starting LocalStack?

With a docker-compose file:

```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"                # only required for Pro (DNS)
      - "127.0.0.1:53:53/udp"            # only required for Pro (DNS)
      - "127.0.0.1:443:443"              # only required for Pro (LocalStack HTTPS Edge Proxy)
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-/tmp/localstack/data}
#     - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - REQUIRE_PRO=1
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "localstack-vol:/tmp/localstack"            # Windows: use a volume not a path
#     - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
#     - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  localstack-vol: #declare the volume for the compose file
```

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker-compose up`

### Environment

```markdown
- OS: Windows
- LocalStack: 0.14.4.dev
```

**Comment by ginger-OS** [comment]
I found that if I uncomment line 145 of node/modules/@aws-cdk/aws-appsync-alpha//graphqlapi.js:

`           // this.apiKeyResource.addDependsOn(this.schemaResource);`

Then the stack will deploy. I don't know the reason for this dependency?

**Comment by ginger-OS** [comment]
I dug a bit deeper into the template_deployer code. For some reason TemplateDeployer::is_deployed always returns false for ApiSchema Resources. what puzzles me is that retrieve_resource_details() does not output log lines when TemplateDeployer::is_deployed from TemplateDeployer::get_unsatisfied_dependencies_for_resources. So I copied the code of retrieve_resource_details into is_deployed to then find out that instance.fetch_and_update_state return None for the ApiSchema  resource. This appears to be Pro code that I cannot access so kind of stuck here.

**Comment by whummer** [comment]
Hi @ginger-OS, thanks for the detailed report. Looks like we've been able to replicate this issue - we're working on a fix and will ping you soon with an update. Thanks!

**Comment by whummer** [comment]
Closing as resolved - please let us know if the problem persists.
