### ISSUE TITLE
bug: .NET6.0 Lambda fails to process message from Dynamo Stream 

### ISSUE THREAD

**Issue by kongo23** [localstack/localstack#6369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Updating lambda to.NET6.0 requires updating Localstack to 0.14.3 
- Deployed to localstack lambda fails to process dynamo events through DynamoStream - **at the same time in AWS account lambda works fine**
- Error returns: `Amazon.Lambda.DynamoDBEvents.DynamoDBEvent: Value to add was out of range`

### How are you starting LocalStack?

Via docker-compose file
  
  ```
version: '3.0'

services:
  localstack:
    image: localstack/localstack:0.14.3
    networks:
      - local
    healthcheck:
      test: awslocal dynamodb list-tables
      interval: 3s
      timeout: 10s
      retries: 5
    ports:
      - 4566:4566
    environment:
      - SERVICES=sns,sqs,dynamodb,dynamodbstreams,iam,lambda
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=liveordersoutboxrelay_local
      - HOSTNAME_FROM_LAMBDA=localstack
      - DEFAULT_REGION=us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  local:
    driver: bridge
```

#### create table with stream
`aws --endpoint-url=http://localhost:4566 --region=us-east-1 dynamodb create-table --table-name outbox --attribute-definitions AttributeName=messageId,AttributeType=S --key-schema AttributeName=messageId,KeyType=HASH --stream-specification StreamEnabled=true,StreamViewType=NEW_AND_OLD_IMAGES --provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=10 --query 'TableDescription.LatestStreamArn' --output text`

#### create lambda role
`aws --endpoint-url=http://localhost:4566 iam create-role --role-name lambda-dotnet-ex --assume-role-policy-document '{"Version": "2012-10-17", "Statement": [{ "Effect": "Allow", "Principal": {"Service": "lambda.amazonaws.com"}, "Action": "sts:AssumeRole"}]}'`

#### attach lambda role
`aws --endpoint-url=http://localhost:4566 iam attach-role-policy --role-name lambda-dotnet-ex --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole `

#### create lambda function
`aws --endpoint-url=http://localhost:4566 --region=us-east-1 lambda create-function --function-name petlambda --zip-file fileb://bin/deployment-archive.zip --handler PetLambda::PetLambda.Function::FunctionHandler --runtime dotnet6 --role arn:aws:iam::000000000000:role/lambda-dotnet-ex --environment 'Variables={ LOCAL_STACK_HOSTNAME=localstack,AWS_REGION=us-east-1,AWS_DEFAULT_REGION=us-east-1,USE_LOCALSTACK=true,AWS_ACCOUNT_ID=000000000000,FEATURE=petlambda,ENVIRONMENT=local }'`

#### subscribe lambda to stream arn - which is taken from the 1st output 
`aws --endpoint-url=http://localhost:4566 --region=us-east-1 lambda create-event-source-mapping --function-name petlambda --event-source arn:aws:dynamodb:us-east-1:000000000000:table/outbox/stream/2022-06-29T10:33:44.728 --batch-size 1 --starting-position LATEST`

### Environment

```markdown
- OS: Windows
- LocalStack:latest (0.14.3)
```

### Anything else?

Test lambda project: https://github.com/kongo23/petlambda

Full Error Log

```
petlambda-localstack-1  | localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: {"errorType":"JsonSerializerException","errorMessage":"Error converting the Lambda event JSON payload to type Amazon.Lambda.DynamoDBEvents.DynamoDBEvent: Value to add was out of range. (Parameter 'value')","stackTrace":["at Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer.Deserialize[T](Stream requestStream)","at lambda_method1(Closure , Stream , ILambdaContext , Stream 
)","at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.Invoke(Stream lambdaData, ILambdaContext lambdaContext, Stream outStream) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 145","at Amazon.Lambda.RuntimeSupport.HandlerWrapper.\u003c\u003ec__DisplayClass8_0.\u003cGetHandlerWrapper\u003eb__0(InvocationRequest invocation) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/HandlerWrapper.cs:line 56","at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 176"],"cause":{"errorType":"ArgumentOutOfRangeException","errorMessage":"Value to add was out of range. (Parameter 'value')","stackTrace":["at System.DateTime.\u003cAdd\u003eg__ThrowOutOfRange|75_0()","at System.DateTime.Add(Double value, Int32 scale)","at System.DateTime.AddSeconds(Double value)","at Amazon.Lambda.Serialization.SystemTextJson.Converters.DateTimeConverter.Read(Utf8JsonReader\u0026 reader, Type typeToConvert, JsonSerializerOptions options)","at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader\u0026 reader, Type typeToConvert, JsonSerializerOptions options, ReadStack\u0026 state, T\u0026 value)","at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack\u0026 state, Utf8JsonReader\u0026 reader)","at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader\u0026 reader, Type typeToConvert, JsonSerializerOptions options, ReadStack\u0026 state, T\u0026 value)","at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader\u0026 reader, Type typeToConvert, JsonSerializerOptions options, ReadStack\u0026 state, T\u0026 value)","at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack\u0026 state, Utf8JsonReader\u0026 reader)","at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader\u0026 reader, Type typeToConvert, JsonSerializerOptions options, ReadStack\u0026 state, T\u0026 value)","at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader\u0026 reader, Type typeToConvert, JsonSerializerOptions options, ReadStack\u0026 state, T\u0026 value)","at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader\u0026 reader, Type typeToConvert, JsonSerializerOptions 
options, ReadStack\u0026 state, TCollection\u0026 value)","at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader\u0026 reader, Type typeToConvert, JsonSerializerOptions options, ReadStack\u0026 state, T\u0026 value)","at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack\u0026 state, Utf8JsonReader\u0026 reader)","at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader\u0026 reader, Type typeToConvert, JsonSerializerOptions options, ReadStack\u0026 state, T\u0026 value)","at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader\u0026 reader, Type typeToConvert, JsonSerializerOptions options, ReadStack\u0026 state, T\u0026 value)","at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader\u0026 reader, JsonSerializerOptions options, ReadStack\u0026 state)","at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)","at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)","at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.InternalDeserialize[T](Byte[] utf8Json)","at Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer.Deserialize[T](Stream requestStream)"]}}. Output:
petlambda-localstack-1  | START RequestId: 46859b9c-2c1f-189e-df8b-2f88ef14539e Version: $LATEST
petlambda-localstack-1  | 2022-06-29T10:36:45.011Z      46859b9c-2c1f-189e-df8b-2f88ef14539e    fail    Amazon.Lambda.Serialization.SystemTextJson.JsonSerializerException: Error 
converting the Lambda event JSON payload to type Amazon.Lambda.DynamoDBEvents.DynamoDBEvent: Value to add was out of range. (Parameter 'value')
petlambda-localstack-1  |  ---> System.ArgumentOutOfRangeException: Value to add was out of range. (Parameter 'value')
petlambda-localstack-1  |    at System.DateTime.<Add>g__ThrowOutOfRange|75_0()
petlambda-localstack-1  |    at System.DateTime.Add(Double value, Int32 scale)
petlambda-localstack-1  |    at System.DateTime.AddSeconds(Double value)
petlambda-localstack-1  |    at Amazon.Lambda.Serialization.SystemTextJson.Converters.DateTimeConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
petlambda-localstack-1  |    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
petlambda-localstack-1  |    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
petlambda-localstack-1  |    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
petlambda-localstack-1  |    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
petlambda-localstack-1  |    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
petlambda-localstack-1  |    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
petlambda-localstack-1  |    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
petlambda-localstack-1  |    at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
petlambda-localstack-1  |    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
petlambda-localstack-1  |    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
petlambda-localstack-1  |    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
petlambda-localstack-1  |    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
petlambda-localstack-1  |    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
petlambda-localstack-1  |    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
petlambda-localstack-1  |    at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
petlambda-localstack-1  |    at Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer.InternalDeserialize[T](Byte[] utf8Json)
petlambda-localstack-1  |    at Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer.Deserialize[T](Stream requestStream)
petlambda-localstack-1  |    --- End of inner exception stack trace ---
petlambda-localstack-1  |    at Amazon.Lambda.Serialization.SystemTextJson.AbstractLambdaJsonSerializer.Deserialize[T](Stream requestStream)
petlambda-localstack-1  |    at lambda_method1(Closure , Stream , ILambdaContext , Stream )
petlambda-localstack-1  |    at Amazon.Lambda.RuntimeSupport.Bootstrap.UserCodeLoader.Invoke(Stream lambdaData, ILambdaContext lambdaContext, Stream outStream) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/UserCodeLoader.cs:line 145
petlambda-localstack-1  |    at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass8_0.<GetHandlerWrapper>b__0(InvocationRequest invocation) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/HandlerWrapper.cs:line 56
petlambda-localstack-1  |    at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken) in /src/Repo/Libraries/src/Amazon.Lambda.RuntimeSupport/Bootstrap/LambdaBootstrap.cs:line 176
petlambda-localstack-1  | END RequestId: 46859b9c-2c1f-189e-df8b-2f88ef14539e
petlambda-localstack-1  | REPORT RequestId: 46859b9c-2c1f-189e-df8b-2f88ef14539e        Init Duration: 209.73 ms        Duration: 57.56 ms      Billed Duration: 58 ms  Memory Size: 1536 MB      Max Memory Used: 58 MB
```

**Comment by shooresh-golzari-cko** [comment]
Looks related to https://github.com/localstack/localstack/issues/6355 if an Event Mapping resource is being used here too.

**Comment by dfangl** [comment]
This is now fixed on master, the images should be available in around 1 hour.
I have tested it with the given sample and the new `PROVIDER_OVERRIDE_LAMBDA=asf` provider.
If there are any more issues, please do not hesitate to reach out!
Thank you for reporting this.
