### ISSUE TITLE
bug: Cannot invoke lambda with destinations

### ISSUE THREAD

**Issue by denisdifazio** [localstack/localstack#6381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've created a simple lambda that has a `onSuccess` and `onFailure` destinations, both pointing to different SQS queues. I can deploy this lambda successfully using `cdklocal`, but when I try to invoke it, I get the following error:

```
localstack_main  | 2022-06-30T17:27:23.908:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:ca-central-1:000000000000:function:rds-stripe-lambda: Expecting value: line 1 column 1 (char 0) Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 801, in run_lambda
localstack_main  |     result = LAMBDA_EXECUTOR.execute(
localstack_main  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 460, in execute
localstack_main  |     return do_execute()
localstack_main  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 450, in do_execute
localstack_main  |     return _run(func_arn=func_arn)
localstack_main  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 170, in wrapped
localstack_main  |     raise e
localstack_main  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 166, in wrapped
localstack_main  |     result = func(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 443, in _run
localstack_main  |     lambda_result_to_destination(
localstack_main  |   File "/opt/code/localstack/localstack/utils/aws/message_forwarding.py", line 65, in lambda_result_to_destination
localstack_main  |     payload["responsePayload"] = json.loads(error.result)
localstack_main  |   File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
localstack_main  |     return _default_decoder.decode(s)
localstack_main  |   File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
localstack_main  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
localstack_main  |   File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
localstack_main  |     raise JSONDecodeError("Expecting value", s, err.value) from None
localstack_main  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I'm invoking the lambda with:
```
aws --endpoint-url=http://localhost:4566 lambda invoke --function-name rds-stripe-lambda --cli-binary-format raw-in-base64-out --payload '{"key": "value"}' response.json
```

### Expected Behavior

The lambda should be invoked successfully

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    cdklocal bootstrap

    cdklocal deploy

#### AWS Components

This is the the CDK stack that I'm currently using:
```ts
export class TestStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const stripeDLQ = new sqs.Queue(this, 'StripeQueueDLQ', {
      queueName: 'stripe-queue-dlq',
      retentionPeriod: Duration.days(7),
    });

    const stripeQueue = new sqs.Queue(this, 'StripeQueue', {
      queueName: 'stripe-queue',
      deadLetterQueue: {
        queue: stripeDLQ,
        maxReceiveCount: 5,
      },
    });

    new nodeLambda.NodejsFunction(this, 'RDSLambda', {
      functionName: 'rds-stripe-lambda',
      runtime: lambda.Runtime.NODEJS_16_X,
      architecture: lambda.Architecture.X86_64,
      timeout: Duration.seconds(5),
      entry: 'src/lambdas/rds-lambda.ts',
      onSuccess: new destinations.SqsDestination(stripeQueue),
      onFailure: new destinations.SqsDestination(stripeDLQ),
    });
  }
}
```

rds-lambda.ts
```ts
export async function handler(event: any) {
  return event;
}
```

### Environment

```markdown
- OS: WSL 2 (Ubuntu 20)
- LocalStack: docker image localstack/localstack
```

**Comment by dominikschubert** [comment]
Hi @denisdifazio! This should be fixed in our new Lambda provider now. You can set `PROVIDER_OVERRIDE_LAMBDA=asf` to opt-in to the new provider.

Please make sure to update the image to the latest available version first by running `docker pull localstack/localstack:latest`.
