### ISSUE TITLE
PRO: bug: Setting up aws_db_subnet_group through terraform causes "list index out of range" bug

### ISSUE THREAD

**Issue by zacherystuart** [localstack/localstack#6382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am attempting to spin up an aws lambda that talks to rds within localstack. I have set up the vpc and all the associated routing to allow for this to happen, but whenever I attempt to set up a subnet group to attach to the rds instance, I get a "list index out of range" error. 

**main.tf**
```
provider "aws" {
  profile = "default"
  region  = var.region

  access_key = "test"
  secret_key = "test"

  s3_force_path_style         = false
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  endpoints {
    apigateway     = "http://localhost:4566"
    apigatewayv2   = "http://localhost:4566"
    cloudformation = "http://localhost:4566"
    cloudwatch     = "http://localhost:4566"
    dynamodb       = "http://localhost:4566"
    ec2            = "http://localhost:4566"
    es             = "http://localhost:4566"
    elasticache    = "http://localhost:4566"
    firehose       = "http://localhost:4566"
    iam            = "http://localhost:4566"
    kinesis        = "http://localhost:4566"
    lambda         = "http://localhost:4566"
    rds            = "http://localhost:4566"
    redshift       = "http://localhost:4566"
    route53        = "http://localhost:4566"
    s3             = "http://s3.localhost.localstack.cloud:4566"
    secretsmanager = "http://localhost:4566"
    ses            = "http://localhost:4566"
    sns            = "http://localhost:4566"
    sqs            = "http://localhost:4566"
    ssm            = "http://localhost:4566"
    stepfunctions  = "http://localhost:4566"
    sts            = "http://localhost:4566"
  }
}

provider "archive" {}

# data "archive_file" "test_code" {
#   type = "zip"
#   source_file = "../test"
#   output_path = "test.zip"
# }

data "aws_iam_policy_document" "AWSLambdaTrustPolicy" {
  version = "2012-10-17"
  statement {
    actions = ["sts:AssumeRole"]
    effect  = "Allow"
    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "iam_role" {
  assume_role_policy = data.aws_iam_policy_document.AWSLambdaTrustPolicy.json
  name               = "${var.project}-iam-role-lambda-trigger"
}

resource "aws_iam_role_policy_attachment" "iam_role_policy_attachment_lambda_basic_execution" {
  role       = aws_iam_role.iam_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

# commented out lambda as code not included
# resource "aws_lambda_function" "test_func" {
#  function_name = "test_func"
#  filename      = "test.zip"
#  handler       = "test"
#  role          = aws_iam_role.iam_role.arn
#  runtime       = "go1.x"
#  source_code_hash = "data.archive_file.zip.output_base64sha256"
#
#  vpc_config {
#    subnet_ids         = [aws_subnet.subnet_private.id]
#    security_group_ids = [aws_default_security_group.default_security_group.id]
#  }
#}

resource "aws_db_instance" "default" {
  allocated_storage    = 10
  engine               = "postgres"
  engine_version       = "14.1"
  instance_class       = "db.t3.micro"
  name                 = "mydb"
  username             = "foo"
  password             = "foobarbaz"
  skip_final_snapshot  = true
  vpc_security_group_ids = [aws_default_security_group.default_security_group.id]
  db_subnet_group_name = aws_db_subnet_group.db_subnet.name
}

resource "aws_db_subnet_group" "db_subnet" {
  name = "${var.project}-aws-db-subnet"
  subnet_ids = ["${aws_subnet.subnet_public.id}", "${aws_subnet.subnet_private.id}"]

  tags = {
    Name = "${var.project}-aws-db-subnet"
  }
}

resource "aws_vpc" "vpc" {
  cidr_block = var.vpc_cidr_block
  tags = {
    Name = "${var.project}-vpc"
  }
}

resource "aws_subnet" "subnet_public" {
  vpc_id                  = aws_vpc.vpc.id
  cidr_block              = var.subnet_public_cidr_block
  map_public_ip_on_launch = true
  tags = {
    Name = "${var.project}-subnet-public"
  }
}

resource "aws_internet_gateway" "internet_gateway" {
  vpc_id = aws_vpc.vpc.id

  tags = {
    Name = "${var.project}-internet-gateway"
  }
}

resource "aws_route_table" "route_table_public" {
  vpc_id = aws_vpc.vpc.id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.internet_gateway.id
  }

  tags = {
    Name = "${var.project}-route-table-public"
  }
}

resource "aws_route_table_association" "route_table_association_public" {
  subnet_id      = aws_subnet.subnet_public.id
  route_table_id = aws_route_table.route_table_public.id
}

resource "aws_eip" "eip" {
  vpc        = true
  depends_on = [aws_internet_gateway.internet_gateway]
  tags = {
    Name = "${var.project}-eip"
  }
}

resource "aws_nat_gateway" "nat_gateway" {
  allocation_id = aws_eip.eip.id
  subnet_id     = aws_subnet.subnet_public.id

  tags = {
    Name = "${var.project}-nat-gateway"
  }
}

resource "aws_subnet" "subnet_private" {
  vpc_id                  = aws_vpc.vpc.id
  cidr_block              = var.subnet_private_cidr_block
  map_public_ip_on_launch = false
  tags = {
    Name = "${var.project}-subnet-private"
  }
}

resource "aws_route_table" "route_table_private" {
  vpc_id = aws_vpc.vpc.id

  route {
    cidr_block     = "0.0.0.0/0"
    nat_gateway_id = aws_nat_gateway.nat_gateway.id
  }

  tags = {
    Name = "${var.project}-route-table-private"
  }
}

resource "aws_route_table_association" "route_table_association_private" {
  subnet_id      = aws_subnet.subnet_private.id
  route_table_id = aws_route_table.route_table_private.id
}

resource "aws_default_network_acl" "default_network_acl" {
  default_network_acl_id = aws_vpc.vpc.default_network_acl_id
  subnet_ids             = [aws_subnet.subnet_public.id, aws_subnet.subnet_private.id]

  ingress {
    protocol   = -1
    rule_no    = 100
    action     = "allow"
    cidr_block = "0.0.0.0/0"
    from_port  = 0
    to_port    = 0
  }

  egress {
    protocol   = -1
    rule_no    = 100
    action     = "allow"
    cidr_block = "0.0.0.0/0"
    from_port  = 0
    to_port    = 0
  }

  tags = {
    Name = "${var.project}-default-network-acl"
  }
}

resource "aws_default_security_group" "default_security_group" {
  vpc_id = aws_vpc.vpc.id

  ingress {
    protocol  = -1
    self      = true
    from_port = 0
    to_port   = 0
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "${var.project}-default-security-group"
  }
}

resource "aws_iam_role_policy_attachment" "iam_role_policy_attachment_lambda_vpc_access_execution" {
  role       = aws_iam_role.iam_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
}

```
**variables.tf**
```
variable "project" {
  type        = string
  description = "test"
  default = "test"
}

variable "region" {
  type        = string
  description = "LocalStack"
  default     = "us-east-1"
}

variable "vpc_cidr_block" {
  type        = string
  description = "VPC CIDR"
}

variable "subnet_public_cidr_block" {
  type        = string
  description = "Public subnet CIDR"
}

variable "subnet_private_cidr_block" {
  type        = string
  description = "Private subnet CIDR"
}
```
**terraform.tfvars**
```
project = "test"
vpc_cidr_block = "10.0.0.0/16"
subnet_public_cidr_block = "10.0.0.0/21"
subnet_private_cidr_block = "10.0.8.0/21"
```

**error from localstack when attempting to run `terraform apply`**
```
2022-06-30T18:40:30.859:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/: list index out of range Traceback (most recent call last):
File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 185, in index
result = await run_sync(handler, request, data)
File "/opt/code/localstack/localstack/utils/asyncio.py", line 85, in run_sync
return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run
result = self.func(self.params, **kwargs)
File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
return fn(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 993, in handler
return modify_and_forward(
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
value = func(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
listener_result = listener.forward_request(
File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request
result = do_forward_request(api, method, path, data, headers, port=port)
File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
return new(target, *args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/edge.py.enc", line 71, in E
File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
result = do_forward_request_inmem(api, method, path, data, headers, port=port)
File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
response = modify_and_forward(
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
value = func(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
listener_result = listener.forward_request(
File "/opt/code/localstack/localstack/http/adapters.py", line 51, in forward_request
response = self.request(request)
File "/opt/code/localstack/localstack/aws/proxy.py", line 43, in request
return self.skeleton.invoke(context)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
return self.dispatch_request(context, instance)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
result = handler(context, instance) or {}
File "/opt/code/localstack/localstack/aws/forwarder.py", line 57, in _call
return handler(context, req)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
return self.fn(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/rds/provider.py.enc", line 249, in list_tags_for_resource
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/rds/provider.py.enc", line 135, in find_resource_for_tagging
IndexError: list index out of range
```

### Expected Behavior

The subnet group to be created and assigned to the rds db instance.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

See below...

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

With localstack installed via homebrew: `localstack start`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Once localstack is running...
`terraform init`
`terraform apply`

### Environment

```markdown
- OS: MacOS Monterey 12.3.1
- LocalStack: 0.14.4
```

**Comment by zacherystuart** [comment]
I also tried this with `LEGACY_EDGE_PROXY=0` and got the same error:
```
2022-07-01T15:37:28.694:INFO:localstack.aws.handlers.logging: POST rds.ListTagsForResource => 500
2022-07-01T15:37:30.204:DEBUG:localstack.aws.serving.wsgi: [asgi-gw_0] POST localhost:4566/
2022-07-01T15:37:30.207:ERROR:localstack.aws.handlers.logging: exception during call chain
Traceback (most recent call last):
File "/opt/code/localstack/localstack/aws/chain.py", line 57, in handle
handler(self, self.context, response)
File "/opt/code/localstack/localstack/aws/handlers/service.py", line 120, in __call__
handler(chain, context, response)
File "/opt/code/localstack/localstack/aws/handlers/service.py", line 90, in __call__
skeleton_response = self.skeleton.invoke(context)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
return self.dispatch_request(context, instance)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
result = handler(context, instance) or {}
File "/opt/code/localstack/localstack/aws/forwarder.py", line 57, in _call
return handler(context, req)
File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
return self.fn(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/rds/provider.py.enc", line 249, in list_tags_for_resource
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/rds/provider.py.enc", line 135, in find_resource_for_tagging
IndexError: list index out of range
```

**Comment by bentsku** [comment]
@zacherystuart , the fix is now deployed in the latest docker image in `localstack/localstack:latest`, you can run `docker pull localstack/localstack:latest` to download it. Could you please give it a try?

**Comment by GeorgePals** [comment]
> @zacherystuart, thanks again for your report, I was able to easily reproduce the issue! The fix is now deployed in the latest docker image in `localstack/localstack:latest`, you can run `docker pull localstack/localstack:latest` to download it. Could you please give it a try?

Had the same issue that @zacherystuart had. With the latest image, it seems okay. Thank you @bentsku!

**Comment by bentsku** [comment]
@zacherystuart yes, you need to update the docker image as well. You can pull the docker image with the command from my comment above, and it should use the latest image. Sorry for the inconvenience!

**Comment by zacherystuart** [comment]
no worries! thank you for the clarification 😄

**Comment by zacherystuart** [comment]
@bentsku it's working! thank you for getting this resolved so quickly.
