### ISSUE TITLE
Unable to run localstack on mac after (apparently!) successful install

### ISSUE THREAD

**Issue by kellyfj** [localstack/localstack#642]
Environment: MacOS 10.12.6 Sierra

See

```[14:07:57 kellyfj:/usr/local/scbe/source ] $ pip install --user localstack
Downloading/unpacking localstack
  Downloading localstack-0.8.5.tar.gz (185kB): 185kB downloaded
  Running setup.py (path:/private/var/folders/q_/c02p37nx3sg6nztkzcs1xz800000gn/T/pip_build_kellyfj/localstack/setup.py) egg_info for package localstack
    
    no previously-included directories found matching 'localstack/dashboard/web/node_modules'
Requirement already satisfied (use --upgrade to upgrade): airspeed==0.5.5.dev20160812 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): awscli>=1.14.18 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): boto==2.46.1 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): boto3>=1.4.4 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): coverage==4.0.3 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.2 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): elasticsearch==5.3.0 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): flake8>=3.5.0 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): flake8-quotes>=0.11.0 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): flask==0.10.1 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): flask-cors==3.0.3 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): flask-swagger==0.2.12 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): jsonpath-rw==1.4.0 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): localstack-ext>=0.8.1 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): localstack-client==0.4 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): moto-ext==1.1.25.3 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): nose==1.3.7 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): psutil==5.4.3 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL==17.0.0 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): python-coveralls==2.7.0 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): pyYAML==3.12 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): requests==2.18.4 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): requests-aws4auth==0.9 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): subprocess32-ext==3.2.8.2 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): xmltodict==0.10.2 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): cachetools==0.8.0 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from airspeed==0.5.5.dev20160812->localstack)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from flask==0.10.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from flask==0.10.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from flask==0.10.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): ply in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from jsonpath-rw==1.4.0->localstack)
Requirement already satisfied (use --upgrade to upgrade): decorator in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from jsonpath-rw==1.4.0->localstack)
Requirement already satisfied (use --upgrade to upgrade): dnslib==0.9.7 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): pyaes==1.6.0 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): pyminifier==2.1 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): srp-ext==1.0.7.1 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): warrant-ext>=0.2.0.5 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): envs>=0.3.0 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from warrant-ext>=0.2.0.5->localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): mock>=2.0.0 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from warrant-ext>=0.2.0.5->localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): python-jose-ext>=1.3.2.4 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from warrant-ext>=0.2.0.5->localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex==3.4.9 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from python-jose-ext>=1.3.2.4->warrant-ext>=0.2.0.5->localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): ecdsa<1.0 in /Library/Python/2.7/site-packages (from python-jose-ext>=1.3.2.4->warrant-ext>=0.2.0.5->localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): future<1.0 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from python-jose-ext>=1.3.2.4->warrant-ext>=0.2.0.5->localstack-ext>=0.8.1->localstack)
Installing collected packages: localstack
  Running setup.py install for localstack
    changing mode of build/scripts-2.7/localstack from 644 to 755
    
    no previously-included directories found matching 'localstack/dashboard/web/node_modules'
    changing mode of /Users/kellyfj/Library/Python/2.7/bin/localstack to 755
Successfully installed localstack
Cleaning up...
[14:08:29 kellyfj:/usr/local/scbe/source ] $ localstack start
-bash: /usr/local/bin/localstack: No such file or directory
[14:09:02 kellyfj:/usr/local/scbe/source ] $ sudo localstack start
Traceback (most recent call last):
  File "/Users/kellyfj/Library/Python/2.7/bin/localstack", line 30, in <module>
    from localstack.services import infra
  File "/Users/kellyfj/Library/Python/2.7/lib/python/site-packages/localstack/services/infra.py", line 25, in <module>
    from localstack.services import generic_proxy, install
  File "/Users/kellyfj/Library/Python/2.7/lib/python/site-packages/localstack/services/generic_proxy.py", line 10, in <module>
    from flask_cors import CORS
  File "/Library/Python/2.7/site-packages/flask_cors/__init__.py", line 11, in <module>
    from .decorator import cross_origin
  File "/Library/Python/2.7/site-packages/flask_cors/decorator.py", line 13, in <module>
    from flask import make_response, request, current_app
  File "/Library/Python/2.7/site-packages/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
  File "/Users/kellyfj/Library/Python/2.7/lib/python/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/Users/kellyfj/Library/Python/2.7/lib/python/site-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/Users/kellyfj/Library/Python/2.7/lib/python/site-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/Users/kellyfj/Library/Python/2.7/lib/python/site-packages/jinja2/utils.py", line 647, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: No module named markupsafe
```

I had to do 
```pip install --user markupsafe```

But then it would not start upon subsequent run

```
[14:22:24 kellyfj:/usr/local/scbe/source ] $ pip install --user localstack
Downloading/unpacking localstack
  Downloading localstack-0.8.5.tar.gz (185kB): 185kB downloaded
  Running setup.py (path:/private/var/folders/q_/c02p37nx3sg6nztkzcs1xz800000gn/T/pip_build_kellyfj/localstack/setup.py) egg_info for package localstack
    
    no previously-included directories found matching 'localstack/dashboard/web/node_modules'
Requirement already satisfied (use --upgrade to upgrade): airspeed==0.5.5.dev20160812 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): awscli>=1.14.18 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): boto==2.46.1 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): boto3>=1.4.4 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): coverage==4.0.3 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.2 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): elasticsearch==5.3.0 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): flake8>=3.5.0 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): flake8-quotes>=0.11.0 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): flask==0.10.1 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): flask-cors==3.0.3 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): flask-swagger==0.2.12 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): jsonpath-rw==1.4.0 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): localstack-ext>=0.8.1 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): localstack-client==0.4 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): moto-ext==1.1.25.3 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): nose==1.3.7 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): psutil==5.4.3 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL==17.0.0 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): python-coveralls==2.7.0 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): pyYAML==3.12 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): requests==2.18.4 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): requests-aws4auth==0.9 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in /Library/Python/2.7/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): subprocess32-ext==3.2.8.2 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): xmltodict==0.10.2 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack)
Requirement already satisfied (use --upgrade to upgrade): cachetools==0.8.0 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from airspeed==0.5.5.dev20160812->localstack)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from flask==0.10.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from flask==0.10.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from flask==0.10.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): ply in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from jsonpath-rw==1.4.0->localstack)
Requirement already satisfied (use --upgrade to upgrade): decorator in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from jsonpath-rw==1.4.0->localstack)
Requirement already satisfied (use --upgrade to upgrade): dnslib==0.9.7 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): pyaes==1.6.0 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): pyminifier==2.1 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): srp-ext==1.0.7.1 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): warrant-ext>=0.2.0.5 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): envs>=0.3.0 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from warrant-ext>=0.2.0.5->localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): mock>=2.0.0 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from warrant-ext>=0.2.0.5->localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): python-jose-ext>=1.3.2.4 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from warrant-ext>=0.2.0.5->localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex==3.4.9 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from python-jose-ext>=1.3.2.4->warrant-ext>=0.2.0.5->localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): ecdsa<1.0 in /Library/Python/2.7/site-packages (from python-jose-ext>=1.3.2.4->warrant-ext>=0.2.0.5->localstack-ext>=0.8.1->localstack)
Requirement already satisfied (use --upgrade to upgrade): future<1.0 in /Users/kellyfj/Library/Python/2.7/lib/python/site-packages (from python-jose-ext>=1.3.2.4->warrant-ext>=0.2.0.5->localstack-ext>=0.8.1->localstack)
Installing collected packages: localstack
  Running setup.py install for localstack
    changing mode of build/scripts-2.7/localstack from 644 to 755
    
    no previously-included directories found matching 'localstack/dashboard/web/node_modules'
    changing mode of /Users/kellyfj/Library/Python/2.7/bin/localstack to 755
Successfully installed localstack
Cleaning up...
[14:22:48 kellyfj:/usr/local/scbe/source ] $ localstack start
-bash: /usr/local/bin/localstack: No such file or directory
```

**Comment by johnstew** [comment]
I'm having what I think is a similar issue.

I ran `pip install --user localstack`. This was successful.

Updated my $PATH variable to

```
export PATH="$HOME/.yarn/bin:$HOME/Library/Python/2.7/bin:$PATH"
```

Run `localstack start` and get the following:

```
Traceback (most recent call last):
  File "/Users/johnathan.stewart/Library/Python/2.7/bin/localstack", line 30, in <module>
    from localstack.services import infra
  File "/Users/johnathan.stewart/Library/Python/2.7/lib/python/site-packages/localstack/services/infra.py", line 25, in <module>
    from localstack.services import generic_proxy, install
  File "/Users/johnathan.stewart/Library/Python/2.7/lib/python/site-packages/localstack/services/generic_proxy.py", line 1, in <module>
    from six.moves.BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer
ImportError: No module named BaseHTTPServer
```

Any ideas?

**Comment by NKeerthi** [comment]
@johnstew even I am getting the same error. Where you able to pass through that?

**Comment by johnstew** [comment]
@NKeerthi nope, I gave up for now. I am going to come back to it soon but was unable to get this working.

**Comment by warnerpinz** [comment]
MacOs High Sierra user here. Everyone of us are getting the same error.

**Comment by fa-ericaselis** [comment]
I have a similar issue but I have MacOs Sierra

**Comment by mgable** [comment]
same here. Any resolution?

**Comment by MaximusHaximus** [comment]
Same here.

**Comment by yussinsharp** [comment]
macOS Version: 10.12.16

Same here. Unable to run `localstack start`

```bash
~ $ localstack start
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/localstack", line 30, in <module>
    from localstack.services import infra
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/localstack/services/infra.py", line 69
    def start(self, async):
                        ^
SyntaxError: invalid syntax
```

**Comment by aldegoeij** [comment]
Seems to be introduced with python 3.7 (having same issue on fresh brew install)

looking at https://docs.python.org/3/whatsnew/3.7.html:

> Backwards incompatible syntax changes:
>  - async and await are now reserved keywords.

Looks like `infra` is using a reserved keyword under 3.7, which should work fine under 3.6?

Start your refactoring engines!

**Comment by aldegoeij** [comment]
Filed https://github.com/localstack/localstack/pull/827 to fix issue of @yussinsharp

**Comment by vibhuyadav** [comment]
+1 Same issue on Windows 10 running Python 3.7! Sorry for using Windows

**Comment by josivan** [comment]
+1 Same issue on Windows 7 SP 1 running Python 3.7.1!

**Comment by anandbose** [comment]
+1 Same issue on Mac Sierra OS. 
Another alternative is to run the docker-compose.yml which will pull down the local stack container which contains the right versions of python. This works!

**Comment by bjm88** [comment]
mac OS latest 10.14.2, pip3 install --user localstack
after success...can't find localstack anywhere in path (other pip3 installs work fine....)

**Comment by MaximusHaximus** [comment]
For anyone still running into this problem, this was a PATH issue. I had to add the correct path to my environment PATH variable for localstack to be discoverable. I think it was related to multiple Python installed versions.

**Comment by biniama** [comment]
`pip uninstall localstack` and `pip2 install localstack` worked for me

**Comment by r-daluz** [comment]
Here's what I've done:

Installed using pip3
- `pip3 install localstack `

Run the following:
export PATH=$PATH:/Users/xxxx/Library/Python/3.7/bin
localstack start

Initial start throws an error, but it's ok after that.

**Comment by whummer** [comment]
Thanks all for posting the solutions here. Closing this issue as fixed. Please open a follow-up issue if the problem persists. Thanks

**Comment by paulo-digital** [comment]
This solution should be updated into the documentation.

**Comment by whummer** [comment]
Great suggestion @paulo-digital - would you be able to create a small pull request with a note in the Troubleshooting section of the README? That would be much appreciated, thanks!
