### ISSUE TITLE
bug: s3 get-object-attributes throws Unable to parse response, invalid XML received error 

### ISSUE THREAD

**Issue by manju2791** [localstack/localstack#6422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is an issue with `get-object-attributes` command which results in below error always: 
`aws --endpoint-url=http://localhost:4566 s3api get-object-attributes --bucket s3mock --key 20.txt --object-attributes "ObjectSize"`
````

> Response:  Unable to parse response (syntax error: line 1, column 0), invalid XML received. Further retries may succeed:
b'98\n5\n'
````

### How are you starting LocalStack?

With a docker-compose file

#### Using docker-compse.yaml to start localstack

docker-compse.yaml:

```
localstack:
    image: localstack/localstack:latest
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - LS_LOG=error
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=eu-west-1
      # - EDGE_PORT=4566
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### cli commands to reproduce the issue

1. Create a Bucket: `aws --endpoint-url=http://localhost:4566 s3 mb s3://s3mock`
2. Create an Object: `aws --endpoint-url=http://localhost:4566 s3 cp data/20.txt s3://s3mock`

File 20.txt content are 2-digit numbers separated by newline.

3. get-object-attributes for object 20.txt :
```

 aws --endpoint-url=http://localhost:4566 s3api get-object-attributes --bucket s3mock --key 20.txt --object-attributes "ObjectSize"

```
Results in error:

> Unable to parse response (syntax error: line 1, column 0), invalid XML received. Further retries may succeed:
b'98\n5\n'

### Environment

```markdown
- OS:Mac 12.x
- LocalStack:latest
- Node 14
```

**Comment by thrau** [comment]
thanks for the report @manju2791, and the excellent reproduction instructions! i can confirm the issue with `latest`.

here's the stack trace:
```
2022-07-12T10:31:55.042 DEBUG --- [   asgi_gw_0] l.aws.serving.wsgi         : GET localhost:4566/s3mock/20.txt?attributes
2022-07-12T10:31:55.050 ERROR --- [   asgi_gw_0] localstack.aws.chain       : exception while running response handler
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/parsers.py", line 502, in _parse_xml_string_to_dom
parser.feed(xml_string)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/code/localstack/localstack/aws/chain.py", line 122, in _call_response_handlers
handler(self, self.context, response)
File "/opt/code/localstack/localstack/aws/handlers/service.py", line 268, in __call__
parsed = parse_response(context.operation, response)
File "/opt/code/localstack/localstack/aws/client.py", line 95, in parse_response
return parser.parse(response_dict, operation.output_shape)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/parsers.py", line 251, in parse
parsed = self._do_parse(response, shape)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/parsers.py", line 871, in _do_parse
self._add_modeled_parse(response, shape, final_parsed)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/parsers.py", line 881, in _add_modeled_parse
self._parse_payload(response, shape, member_shapes, final_parsed)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/parsers.py", line 922, in _parse_payload
original_parsed = self._initial_body_parse(response['body'])
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/parsers.py", line 1023, in _initial_body_parse
return self._parse_xml_string_to_dom(xml_string)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/parsers.py", line 505, in _parse_xml_string_to_dom
raise ResponseParserError(
botocore.parsers.ResponseParserError: Unable to parse response (syntax error: line 1, column 0), invalid XML received. Further retries may succeed:
b'98\n5\n'
2022-07-12T10:31:55.052  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.GetObjectAttributes => 200; GetObjectAttributesRequest({'Bucket': 's3mock', 'Key': '20.txt', 'VersionId': None, 'MaxParts': None, 'PartNumberMarker': None, 'SSECustomerAlgorithm': None, 'SSECustomerKey': None, 'SSECustomerKeyMD5': None, 'RequestPayer': None, 'ExpectedBucketOwner': None, 'ObjectAttributes': ['O', 'b', 'j', 'e', 'c', 't', 'S', 'i', 'z', 'e']}, headers={'Host': 'localhost:4566', 'Accept-Encoding': 'identity', 'x-amz-object-attributes': 'ObjectSize', 'User-Agent': 'aws-cli/1.25.27 Python/3.10.4 Linux/5.15.0-33-generic botocore/1.27.27', 'X-Amz-Date': '20220712T103155Z', 'X-Amz-Content-SHA256': 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': 'AWS4-HMAC-SHA256 Credential=test/20220712/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-object-attributes, Signature=07424ea35aa620ad820fd1bcb2ad324f1cd18f2d08e387f51c742cab929b8516', 'amz-sdk-invocation-id': '121c16d8-924d-439b-8364-c3983e788eef', 'amz-sdk-request': 'attempt=1', 'x-localstack-tgt-api': 's3', 'x-localstack-edge': 'http://localhost:4566', 'X-Forwarded-For': '127.0.0.1, localhost:4566', 'Connection': 'close'}); GetObjectAttributesOutput(None, headers={'content-type': 'text/plain', 'Content-Length': '5', 'Server': 'Werkzeug/2.1.2 Python/3.10.5', 'Date': 'Tue, 12 Jul 2022 10:31:55 GMT', 'x-amz-version-id': 'null', 'content-md5': 'QPtU6dMtWL1SrMVGdVXyGQ==', 'ETag': '"40fb54e9d32d58bd52acc5467555f219"', 'last-modified': 'Tue, 12 Jul 2022 10:31:45 GMT', 'x-amzn-requestid': 'LRZSCRRXRN6OXWG54R1700U97VMU8NAJ8QFMUOZ5EEW311MB51HB', 'Access-Control-Allow-Origin': '*', 'Connection': 'close', 'x-amz-request-id': 'BFBA0D0D48BE19CE', 'x-amz-id-2': 'MzRISOwyjmnupBFBA0D0D48BE19CE7/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp', 'accept-ranges': 'bytes', 'content-language': 'en-US', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'etag,x-amz-version-id'})
```

there's obviously an issue with our response parser and the getobjectattributes response coming from the backend (see `'ObjectAttributes': ['O', 'b', 'j', 'e', 'c', 't', 'S', 'i', 'z', 'e']` in the trace). there also seems to be an issue with the error reporting, since the client is receiving this nonsensical response although an exception is raised in the chain.

**Comment by thrau** [comment]
seems like we are also missing the feature upstream in moto

**Comment by benhowes** [comment]
I ran in to this problem today when trying to use `get-object-attributes` via boto. I ended up catching the `botocore.parsers.ResponseParserError` and using that to pull the file and calculate the SHA256 checksum (since this was the part I needed). It's a nasty hack, but it works until this bug is resolved

**Comment by roip890** [comment]
Still got this error:
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/16388656/211819853-fe7db281-ce30-4a52-b0da-ca7edcb83531.png">

**Comment by alexrashed** [comment]
Unfortunately, I cannot reproduce your issue on my machine (with the latest version of LocalStack). The operation does not work correctly (as mentioned above it's not supported in the current default S3 provider), but I don't see the parser error when using the CLI.

But, there is a new implementation of S3 (which will become the default with the next major version, but is already available as an opt-in). This new implementation now supports `s3api#get-object-attributes`:
- Make sure that you are using the latest version of LocalStack (explicitly pull the latest image).
- Enable the new S3 provider with the environment variable `PROVIDER_OVERRIDE="asf"` (or `PROVIDER_OVERRIDE="asf-pro"` if you are using LocalStack Pro).
- Test the API:
  ```
  awslocal s3 mb s3://test-bucket
  awslocal s3 cp ./test.txt s3://test-bucket
  awslocal s3api get-object-attributes --bucket test-bucket --key test.txt --object-attributes "StorageClass" "ETag" "ObjectSize"
  ```

**Comment by mmoales** [comment]
I still see this issue with the latest docker image:

LocalStack version: 1.3.2.dev
LocalStack build date: 2023-01-30
LocalStack build git hash: 082ff87e

I have PROVIDER_OVERRIDE set to asf:
root@localstack-86679d5f5d-kbrrm:/opt/code/localstack# echo $PROVIDER_OVERRIDE
asf

When I test the API, the API returns the content of the file rather than the object attributes:

```
PS D:\scratch> awslocal s3api get-object-attributes --bucket test-bucket --key test.txt --object-attributes "StorageClass" "ETag" "ObjectSize"

Unable to parse response (syntax error: line 1, column 0), invalid XML received. Further retries may succeed:
b'This is some test data.\r\n\r\nIt is being used to test get-object-attributes API in localstack.\r\n\r\nThe end.\r\n'

```

**Comment by ketola** [comment]
As a workaround, you can make a HeadObject request. It also contains many of the attributes mentioned here, like storage class and object size. See: [HeadObjectRequest](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3Client.html#headObject(software.amazon.awssdk.services.s3.model.HeadObjectRequest)), [cli](https://awscli.amazonaws.com/v2/documentation/api/2.0.34/reference/s3api/head-object.html), [java sdk](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3Client.html#headObject(software.amazon.awssdk.services.s3.model.HeadObjectRequest))

**Comment by kd73** [comment]
Just tested that the latest version v1.4.0 also has this issue.

**Comment by alexrashed** [comment]
I am sorry for the inconvenience. I referenced the wrong environment variables to switch to the new provider, which will be the default with the next major release.
Please use `PROVIDER_OVERRIDE_S3=asf` to enable the new provider.
With 1.4.0, there's no need to distinct between pro and community anymore.
I adjusted my comment above and verified again just now that it returns a proper response:
```
$ awslocal s3 mb s3://test-bucket 
$ awslocal s3 cp ./test.txt s3://test-bucket
$ awslocal s3api get-object-attributes --bucket test-bucket --key test.txt --object-attributes "StorageClass" "ETag" "ObjectSize"
make_bucket: test-bucket
upload: ./test.txt to s3://test-bucket/test.txt                  
{
    "LastModified": "Thu, 16 Feb 2023 08:11:27 GMT",
    "ETag": "193f3b0734b306d0f86e77d671b36b97",
    "StorageClass": "STANDARD",
    "ObjectSize": 1778196
}

```

**Comment by mmoales** [comment]
I'm still seeing the error with PROVIDER_OVERRIDE_S3=asf

```
root@localstack-5b9c9bfb6-f8q9h:/opt/code/localstack# echo $PROVIDER_OVERRIDE_S3
asf

```

```
PS D:\scratch\GoS3Playground> awslocal s3api get-object-attributes --bucket test-bucket --key /go.sum --object-attributes "ETag"

An error occurred (InternalError) when calling the GetObjectAttributes operation (reached max retries: 2): exception while calling s3.GetObjectAttributes
```

**Comment by alexrashed** [comment]
Hi @mmoales!
As I mentioned above, I am not able to reproduce any issues with the `get-object-attributes` operation with the new S3 provider.
Could you please create a new issue with a detailed description on the version you are using, the steps to reproduce your issue, and the logs you are seeing in your localstack container?
Thanks!

**Comment by mmoales** [comment]
Hi @alexrashed , Sorry, I've been sidetracked by other issues. This is working for me now. .Thanks!
