### ISSUE TITLE
bug: CreateVirtualMFADevice via the AWS SDK v3 (nodejs) fails with Error (CLI works fine)

### ISSUE THREAD

**Issue by jogura** [localstack/localstack#6450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
import { IAM } from '@aws-sdk/client-iam';

const iamClient = new IAM({ endpoint: 'http://localhost:4566' });

try {
  const mfaDeviceInfo = await iamClient.createVirtualMFADevice({ VirtualMFADeviceName: username });
} catch (err) {
  console.error(err);
}
```

Results in this stacktrace:

```
TypeError: Incorrect padding on base64 string.
    at Object.fromBase64 [as base64Decoder] (/Users/jogura/Dev/cloudops-framework-ng/node_modules/@aws-sdk/util-base64-node/dist-cjs/index.js:8:15)
    at deserializeAws_queryVirtualMFADevice (/Users/jogura/Dev/cloudops-framework-ng/node_modules/@aws-sdk/client-iam/dist-cjs/protocols/Aws_query.js:14413:38)
    at deserializeAws_queryCreateVirtualMFADeviceResponse (/Users/jogura/Dev/cloudops-framework-ng/node_modules/@aws-sdk/client-iam/dist-cjs/protocols/Aws_query.js:11414:37)
    at deserializeAws_queryCreateVirtualMFADeviceCommand (/Users/jogura/Dev/cloudops-framework-ng/node_modules/@aws-sdk/client-iam/dist-cjs/protocols/Aws_query.js:3005:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at /Users/jogura/Dev/cloudops-framework-ng/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at /Users/jogura/Dev/cloudops-framework-ng/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at StandardRetryStrategy.retry (/Users/jogura/Dev/cloudops-framework-ng/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at /Users/jogura/Dev/cloudops-framework-ng/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at AwsIamService.createVirtualMfaDeviceForUser (/Users/jogura/Dev/cloudops-framework-ng/apps/api/.webpack/service/src/app/api-graphql-lambda/webpack:/libs/cloudops-services/src/lib/services/aws-iam/index.js:598:17) {$metadata: {…}, stack: 'TypeError: Incorrect padding on base64 string…ces/src/lib/services/aws-iam/index.js:598:17)', message: 'Incorrect padding on base64 string.', $response: HttpResponse}
```

The issue is with the `qrCodePng` value returning a string with a `b'` prefix (i.e. - "b'ybHWiuPYdqPWYn31wBYsF7UWPWDzDaFEmIKZ5GfPD99BlK3eNJQoi5KCjmTPStoxZe7aQuC9gS4wktSIlq0n0w=='")

This is causing the `fromBase64()` function to throw the error above. If you strip the `b'` and the extra `'`'s off the string the function successfully completes.

### Expected Behavior

The call to `createVirtualMFADevice()` returns the MFA device info successfully.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal iam create-user --user-name <username>

    # run the code snippet above (using the SDK) the CLI command works

### Environment

```markdown
- OS: MacOS 11.6.5
- LocalStack: 0.14.4 (PRO)
```

**Comment by jogura** [comment]
Verified with the `latest` this functionality works as designed.

Thanks! Feel free to close out the ticket.

**Comment by jogura** [comment]
Verified with the `latest` this functionality works as designed.

Thanks! I'll close out the ticket.
