### ISSUE TITLE
bug: localstack 1.0.0 will not start

### ISSUE THREAD

**Issue by thantos** [localstack/localstack#6465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```console

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 1.0.0

[07:07:33] starting LocalStack in Docker mode 🐳  localstack.py:140
────────── LocalStack Runtime Log (press CTRL-C to quit) ──────────
Waiting for all LocalStack services to be ready
2022-07-16 11:07:44,423 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-07-16 11:07:44,424 INFO supervisord started with pid 16
2022-07-16 11:07:45,426 INFO spawned: 'infra' with pid 21
2022-07-16 11:07:46,429 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for all LocalStack services to be ready

LocalStack version: 1.0.1.dev
LocalStack Docker container id: 4ac356693dc3
LocalStack build date: 2022-07-15
LocalStack build git hash: a09af417

Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
2022-07-16T11:08:11.484  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "start_runtime_components" took 14782.17ms
Error starting infrastructure: gave up waiting for edge server on 0.0.0.0:4566 Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/infra.py", line 419, in start_infra
thread = do_start_infra(asynchronous, apis, is_in_docker)
File "/opt/code/localstack/localstack/services/infra.py", line 521, in do_start_infra
thread = start_runtime_components()
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 77, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/infra.py", line 513, in start_runtime_components
raise TimeoutError(
TimeoutError: gave up waiting for edge server on 0.0.0.0:4566

Traceback (most recent call last):
File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/opt/code/localstack/localstack/cli/main.py", line 10, in <module>
main()
File "/opt/code/localstack/localstack/cli/main.py", line 6, in main
cli()
File "/opt/code/localstack/localstack/cli/plugin.py", line 15, in __call__
self.group(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/analytics/cli.py", line 66, in publisher_wrapper
return fn(*args, **kwargs)
File "/opt/code/localstack/localstack/cli/localstack.py", line 148, in cmd_start
bootstrap.start_infra_locally()
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 260, in start_infra_locally
return infra.start_infra()
File "/opt/code/localstack/localstack/services/infra.py", line 433, in start_infra
raise e
File "/opt/code/localstack/localstack/services/infra.py", line 419, in start_infra
thread = do_start_infra(asynchronous, apis, is_in_docker)
File "/opt/code/localstack/localstack/services/infra.py", line 521, in do_start_infra
thread = start_runtime_components()
File "/opt/code/localstack/localstack/utils/bootstrap.py", line 77, in wrapped
return f(*args, **kwargs)
File "/opt/code/localstack/localstack/services/infra.py", line 513, in start_runtime_components
raise TimeoutError(
TimeoutError: gave up waiting for edge server on 0.0.0.0:4566
2022-07-16 11:08:11,669 INFO exited: infra (exit status 1; not expected)
Waiting for all LocalStack services to be ready
2022-07-16 11:08:12,673 INFO spawned: 'infra' with pid 161
2022-07-16 11:08:13,676 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for all LocalStack services to be ready

LocalStack version: 1.0.1.dev
LocalStack Docker container id: 4ac356693dc3
LocalStack build date: 2022-07-15
LocalStack build git hash: a09af417

Waiting for all LocalStack services to be ready
```

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker pull localstack/localstack
    pip install localstack --upgrade
    localstack start

### Environment

```markdown
- OS: WSL2 - Ubuntu
- LocalStack: 1.0.0
```

### Anything else?

CLI and images are latest. Cleared the `/temp/localstack` and `~/.cache/localstack` directories.

**Comment by thantos** [comment]
Downgraded to 0.14.5 and its still not starting

```console
error importing entrypoint EntryPoint(name='login', value='localstack_ext.cli.localstack:LoginCliPlugin', group='localstack.plugins.cli'): module 'functools' has no attribute 'cache'
error importing entrypoint EntryPoint(name='pro', value='localstack_ext.cli.localstack:ProCliPlugin', group='localstack.plugins.cli'): module 'functools' has no attribute 'cache'
```

```console
pip install localstack==0.14.5 --upgrade awscli-local[ver1]
# Make sure to pull the latest version of the image
docker pull localstack/localstack:0.14.5
# Start LocalStack in the background
IMAGE_NAME=localstack/localstack:0.14.5 localstack start -d
```

**Comment by thantos** [comment]
Resolved this. I had to uninstall `localstack` and re-install.

`> pip uninstall localstack`
`> pip install localstack`

`Successfully installed cachetools-5.0.0 localstack-1.0.0 localstack-ext-1.0.0`

Appears that `cachetools` and `localstack-ext` were missing before.
