### ISSUE TITLE
bug: Installation via pip fails

### ISSUE THREAD

**Issue by peteraba** [localstack/localstack#6484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
$ pip install localstack
Defaulting to user installation because normal site-packages is not writeable
Collecting localstack
  Using cached localstack-1.0.0-py3-none-any.whl (1.0 MB)
Collecting localstack-client>=1.31
  Using cached localstack-client-1.35.tar.gz (9.0 kB)
  Preparing metadata (setup.py) ... done
Collecting semver>=2.10
  Downloading semver-2.13.0-py2.py3-none-any.whl (12 kB)
Collecting cachetools~=5.0.0
  Downloading cachetools-5.0.0-py3-none-any.whl (9.1 kB)
Collecting localstack-ext==1.0.0
  Using cached localstack-ext-1.0.0.tar.gz (2.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      running egg_info
      writing localstack_ext.egg-info/PKG-INFO
      writing dependency_links to localstack_ext.egg-info/dependency_links.txt
      deleting localstack_ext.egg-info/entry_points.txt
      writing requirements to localstack_ext.egg-info/requires.txt
      writing top-level names to localstack_ext.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 147, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 128, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 4, in <module>
          setup()
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 288, in run
          ep.require(installer=installer)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2467, in require
          items = working_set.resolve(reqs, env, installer, extras=self.extras)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
          raise VersionConflict(dist, req).with_context(dependent_req)
      pkg_resources.VersionConflict: (stevedore 1.32.0 (/usr/lib/python3/dist-packages), Requirement.parse('stevedore>=3.4'))
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

### Expected Behavior

localstack installed

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:Ubuntu 20.04.4 LTS
- LocalStack:latest?
- Python: Python 3.10.5
- pip: pip 22.1.2 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)
```

**Comment by alexrashed** [comment]
Hi @peteraba!

It seems like you already have another package installed globally which depends on a version of `stevedore` which is lower than the minimum version necessary for localstack.
This is a common problem with Python environments in general, and there isn't really anything we can do about.

You have different options to tackle this problem:
- Use an isolated package manager like https://github.com/pypa/pipx which creates separate environments for each package.
  - Imho, this is the best option if you are regularly installing and using different python tools.
- Create an isolated environment for localstack on your own by using venv.
  - You could do this with the following steps:
    ```
    python -m venv .venv      # <- create a new isolated environment
    source .venv/bin/activate # <- activate it
    pip install localstack    # <- install localstack in that environment
    localstack                # <- run localstack
    deactivate                # <- deactivate the environment
    ```
  - Please be aware that localstack will only be available in your shell when the environment is activated (`source .venv/bin/activate`).
  - This is the most common option if you are developing, or to just quickly resolve your issue (because it uses more-or-less out-of-the-box python features).
- Find the package which creates the conflict and uninstall it.

Let me know if that solves your issues. 🙂

**Comment by alexrashed** [comment]
`pipx` is built around `venv` and it seems like the `venv` call fails.
Here's the official troubleshooting guide of `pipx`: https://pypa.github.io/pipx/troubleshooting/

It's hard to say what could cause your issue, but I guess it might be the missing venv package (as mentioned in the troubleshooting guide). You can install it on Ubuntu 20.04 with:
```
sudo apt install python3-venv
```

I'll close the issue here for now.

**Comment by Sekomer** [comment]
hey, I encountered the same error, upgrading setuptools solved my problem

`pip install -U setuptools`
