### ISSUE TITLE
Running locally for dev, Permission denied errors when uploading lambda

### ISSUE THREAD

**Issue by aventurella** [localstack/localstack#650]
If I `sudo localstack start` as expected the permission denied goes away. I have also tried changing `TMPDIR=$PWD/localstack_tmp localstack start` and I get the same issue.
When I `sudo localstack start` with the remapped TMPDIR or the default TMPDIR everything starts, BUT, Elasticsearch fails to start and then Localstack quits after trying to start it a few times.

```
2018-03-08T13:08:58:WARNING:localstack.services.awslambda.lambda_api: Unknown error: [Errno 13] Permission denied: '/private/var/folders/vt/bfmnjpcj65b66sbpbgzd_mgw0000gn/T/localstack/zipfile.5d3e53eb/arrow-0.12.1.dist-info/DESCRIPTION.rst' Traceback (most recent call last):
  File "/Users/aventurella/github/localstack/localstack/services/awslambda/lambda_api.py", line 468, in create_function
    result = set_function_code(data['Code'], lambda_name)
  File "/Users/aventurella/github/localstack/localstack/services/awslambda/lambda_api.py", line 365, in set_function_code
    unzip(tmp_file, tmp_dir)
  File "/Users/aventurella/github/localstack/localstack/utils/common.py", line 503, in unzip
    _unzip_file_entry(zip_ref, file_entry, target_dir)
  File "/Users/aventurella/github/localstack/localstack/utils/common.py", line 511, in _unzip_file_entry
    zip_ref.extract(file_entry.filename, path=target_dir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 1083, in _extract_member
    file(targetpath, "wb") as target:
IOError: [Errno 13] Permission denied: '/private/var/folders/vt/bfmnjpcj65b66sbpbgzd_mgw0000gn/T/localstack/zipfile.5d3e53eb/arrow-0.12.1.dist-info/DESCRIPTION.rst'
```

**Comment by aventurella** [comment]
Turns out this has to do with how my zip is zipped.

If i user Archive utility on macos to zip my contents it's fine. If I have `System.IO.Compression.ZipArchive` ( .NET Standard 2) zip my files I get the permission error.
