### ISSUE TITLE
bug: AWS Kinesis get-records fails with a `JSONDecodeError`

### ISSUE THREAD

**Issue by kingkupps** [localstack/localstack#6504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Retrieving certain records from Kinesis through `GetRecord` like so:
```
#!/bin/bash

SHARD_ITERATOR=$(aws kinesis get-shard-iterator \
    --endpoint-url=http://localhost:4566 \
    --shard-id shardId-000000000000 \
    --shard-iterator-type TRIM_HORIZON \
    --stream-name dbsync.events \
    --query 'ShardIterator')

aws --endpoint-url=http://localhost:4566 kinesis get-records --shard-iterator $SHARD_ITERATOR 
```
seems to fail consistently with the following error message:
```
An error occurred (InternalError) when calling the GetRecords operation (reached max retries: 2): exception while calling kinesis.GetRecords: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 57, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 121, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 69, in __call__
    result = self.forward_request(
  File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 129, in forward_request
    return do_forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 604, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 777, in modify_and_forward
    updated_response = listener.return_response(
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py", line 187, in return_response
    results, encoding_type = self.decode_content(response.content, True)
  File "/opt/code/localstack/localstack/services/kinesis/kinesis_listener.py", line 264, in decode_content
    decoded = json.loads(to_str(data))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

My compose file includes the following entry for LocalStack:
```
localstack:
    container_name: localstack # required to run correctly
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      DEBUG: 1
      DOCKER_HOST: unix:///var/run/docker.sock
      KINESIS_INITIALIZE_STREAMS: dbsync:1,dbsync.events:1
    volumes:
      - ./dbsync/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```

### Expected Behavior

I would expect the call to `GetRecords` to succeed given this works with production Kinesis.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

See Current Behavior

### Environment

```markdown
- OS: MacOS Monterey (12.4)
- LocalStack: latest
```

**Comment by kingkupps** [comment]
Potential workaround from @alexrashed in https://github.com/localstack/localstack/issues/6492:

>It seems like our underlying infrastructure expects the ShardCount to be set, so a quick workaround would be to add a --shard-count 1 to your commands.

Adding `--shard-count 1` doesn't appear to be accepted in either `GetRecords` or `GetShardIterator`. Which command are you referring to?

**Comment by alexrashed** [comment]
Oh, sorry, I was basically side-tracked by another issue when trying to reproduce yours (`create-stream` does not work without a `shard-count`, created https://github.com/etspaceman/kinesis-mock/issues/336 to address this).

I can reproduce your issue with a trivial stream, i.e. when executing the following script:
```
#!/bin/bash
aws --endpoint-url=http://localhost:4566  kinesis create-stream --stream-name dbsync.events --shard-count 1
SHARD_ITERATOR=$(aws kinesis get-shard-iterator \
    --endpoint-url=http://localhost:4566 \
    --shard-id shardId-000000000000 \
    --shard-iterator-type TRIM_HORIZON \
    --stream-name dbsync.events \
    --query 'ShardIterator')
aws --endpoint-url=http://localhost:4566 kinesis get-records --shard-iterator $SHARD_ITERATOR 
```

**Comment by alexrashed** [comment]
Hi @kingkupps!
The fix is merged and is already contained in the latest version of the Docker image on DockerHub.
Could you please check if it works for you now? Please make sure to use `--output test` on `get-shard-iterator` to create a proper request (otherwise the shard iterator will be invalid because it will be embedded in quotes).
Thanks!

**Comment by kingkupps** [comment]
Just confirmed, thanks for quick fix!
