### ISSUE TITLE
bug: RDS fails in arm64 docker image

### ISSUE THREAD

**Issue by hans-d** [localstack/localstack#6511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
ERROR: '['apt-get', 'update']': exit code 100; output: b'Hit:1 http://deb.debian.org/debian buster InRelease\nGet:2 http://deb.debian.org/debian-security buster/updates InRelease [73.5 kB]\nGet:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]\nHit:4 https://deb.nodesource.com/node_14.x buster InRelease\nGet:5 http://deb.debian.org/debian-security buster/updates/main arm64 Packages [330 kB]\nReading package lists...\nE: Release file for http://deb.debian.org/debian/dists/buster-updates/InRelease is not valid yet (invalid for another 4h 31min 21s). Updates for this repository will not be applied.\n'
2022-07-23T16:02:33.438  WARN --- [  Thread-310] l.services.rds.db_utils    : Unable to startup DB instance: The installation failed (MariaDB). Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/bootstrap/installer.py", line 43, in install
    try:A.logger.debug('Preparing the installation of %s.',A.log_package_name);A._prepare_installation();A.logger.debug('Starting to install %s.',A.log_package_name);A._install_package();A.logger.debug('Executing post-processing of %s.',A.log_package_name);A._post_process()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/bootstrap/installer.py", line 122, in _install_package
    def _install_package(A):A._install_os_packages(['mariadb-server','mariadb-client'])
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/bootstrap/installer.py", line 83, in _install_os_packages
    with INSTALL_LOCK:C=B._download_os_packages(A);D=B.cmd_prefix(C)+[_C]+A;run(D)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/bootstrap/installer.py", line 87, in _download_os_packages
    D='--'.join(A);B=C.get_download_path(D);mkdir(B);run(['apt-get','update']);LOG.debug('Downloading packages %s to folder: %s',A,B)
  File "/opt/code/localstack/localstack/utils/run.py", line 119, in run
    raise e
  File "/opt/code/localstack/localstack/utils/run.py", line 69, in run
    output = subprocess.check_output(cmd, shell=shell, stderr=stderr, env=env_dict, cwd=cwd)
  File "/usr/local/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['apt-get', 'update']' returned non-zero exit status 100.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/rds/db_utils.py.enc", line 35, in B
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/rds/engine_mysql.py.enc", line 13, in start_db_instance
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/bootstrap/installer.py", line 74, in install
    else:super(OSSpecificPackageInstaller,A).install(raise_on_error=B)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/bootstrap/installer.py", line 62, in install
    for B in A.package_installers:B.install(raise_on_error=raise_on_error)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/bootstrap/installer.py", line 46, in install
    else:C=f" ({A.log_package_name})."if A.log_package_name is not _A else'.';raise PackageInstallationException(f"The installation failed{C}") from B
localstack_ext.bootstrap.installer.PackageInstallationException: The installation failed (MariaDB).
```

### Expected Behavior

RDS can be used on arm64

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`podman run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 -e LOCALSTACK_API_KEY=redacted localstack/localstack:1.0.1`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

snippet from terraform json
```
   "aws_db_instance": {
      "db": {
        "//": {
          "metadata": {
            "path": "proj1/db",
            "uniqueId": "db"
          }
        },
        "allocated_storage": 10,
        "db_name": "AppDb",
        "engine": "mysql",
        "instance_class": "db.t2.micro",
        "password": "This$hou1dBe$ecr3t",
        "username": "app"
      }
```

### Environment

```markdown
- OS: Mac Monterey M1
- LocalStack: 1.0.1
```

**Comment by hans-d** [comment]
also on latest

**Comment by hans-d** [comment]
output using localstack-full
```
ERROR: '['apt-get', 'update']': exit code 100; output: b'Hit:1 http://deb.debian.org/debian buster InRelease\nHit:2 http://deb.debian.org/debian-security buster/updates InRelease\nGet:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]\nHit:4 https://deb.nodesource.com/node_14.x buster InRelease\nReading package lists...\nE: Release file for http://deb.debian.org/debian/dists/buster-updates/InRelease is not valid yet (invalid for another 4h 11min 58s). Updates for this repository will not be applied.\n'
2022-07-23T16:21:56.526  WARN --- [  Thread-148] l.services.rds.db_utils    : Unable to startup DB instance: The installation failed (MariaDB). Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/bootstrap/installer.py", line 43, in install
    try:A.logger.debug('Preparing the installation of %s.',A.log_package_name);A._prepare_installation();A.logger.debug('Starting to install %s.',A.log_package_name);A._install_package();A.logger.debug('Executing post-processing of %s.',A.log_package_name);A._post_process()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/bootstrap/installer.py", line 122, in _install_package
    def _install_package(A):A._install_os_packages(['mariadb-server','mariadb-client'])
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/bootstrap/installer.py", line 83, in _install_os_packages
    with INSTALL_LOCK:C=B._download_os_packages(A);D=B.cmd_prefix(C)+[_C]+A;run(D)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/bootstrap/installer.py", line 87, in _download_os_packages
    D='--'.join(A);B=C.get_download_path(D);mkdir(B);run(['apt-get','update']);LOG.debug('Downloading packages %s to folder: %s',A,B)
  File "/opt/code/localstack/localstack/utils/run.py", line 119, in run
    raise e
  File "/opt/code/localstack/localstack/utils/run.py", line 69, in run
    output = subprocess.check_output(cmd, shell=shell, stderr=stderr, env=env_dict, cwd=cwd)
  File "/usr/local/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['apt-get', 'update']' returned non-zero exit status 100.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/rds/db_utils.py.enc", line 35, in B
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/rds/engine_mysql.py.enc", line 13, in start_db_instance
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/bootstrap/installer.py", line 74, in install
    else:super(OSSpecificPackageInstaller,A).install(raise_on_error=B)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/bootstrap/installer.py", line 62, in install
    for B in A.package_installers:B.install(raise_on_error=raise_on_error)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/bootstrap/installer.py", line 46, in install
    else:C=f" ({A.log_package_name})."if A.log_package_name is not _A else'.';raise PackageInstallationException(f"The installation failed{C}") from B
localstack_ext.bootstrap.installer.PackageInstallationException: The installation failed (MariaDB).
```

**Comment by hans-d** [comment]
running apt-get update in a -full container? Not a "fan" of that practice...

**Comment by thrau** [comment]
thanks @hans-d. RDS installation has been bugging us for a while and we've been exploring alternatives. your issue report may give this another push.

**Comment by hans-d** [comment]
suggestion:
- use a fake db service by default, eg it now it has a db with the instantiated name, but cannot provide actual db services
- provide an additional docker image with the actual db software + config in the main image to enable this image

**Comment by steffyP** [comment]
Hi @hans-d, 
thanks for reporting. Agreed, the current setup, e.g. running `apt-get update` isn't ideal.

However, I tested your scenario on a M1 machine (MacOS Monterey) and it worked for me.

From your logs it seems there might be an issue with the system time? Does this problem persist when you restart the machine?

```
ERROR: '['apt-get', 'update']': exit code 100; output: [....]
Release file for http://deb.debian.org/debian/dists/buster-updates/InRelease is not valid yet (invalid for another 4h 31min 21s). Updates for this repository will not be applied.
```

**Comment by hans-d** [comment]
ah crap, https://github.com/containers/podman/issues/11541 might be playing up.

**Comment by steffyP** [comment]
Hi @hans-d,

thanks for getting back us!

Regarding your remaining questions:

> There is indeed no Docker as I run podman. Why does it need that here?

We recommend and fully support running LocalStack in Docker. Some features might need a mounted docker-socket, and other docker features to fully work. 
Podman is currently in a experimental phase. You can read details about r[ecommended and required setup when using Podman in our docs](https://docs.localstack.cloud/localstack/podman/).



> Only doing a resource "aws_db_instance" "db_5DB842E6", so why the ec2 ?

This request is sent by Terraform. If you are interested in verbose logs, you could set the envs `DEBUG=1` and `LS_LOG=TRACE` (see also [docs on configuration](https://docs.localstack.cloud/localstack/configuration/)). The later one give you details about requests/responses.

When I run your example with trace enabled, the LocalStack logs show something like this:
```
AWS ec2.DescribeAccountAttributes => 200; DescribeAccountAttributesRequest({'AttributeNames': ['supported-platforms']}, headers={'Host': 'localhost:4566', 'User-Agent': 'APN/1.0 HashiCorp/1.0 Terraform/1.2.5 (+https://www.terraform.io) terraform-provider-aws/dev (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.44.57 (go1.17.12; darwin; amd64)', 'Content-Length': '87', 'Authorization': 'AWS4-HMAC-SHA256 Credential=test/20220726/us-east-1/ec2/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=a618f0805fd0c8355954a7d6c3c277198cc4e86ee2ca84033f6f2fc4bc24ba14', 'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'X-Amz-Date': '20220726T074114Z', 'Accept-Encoding': 'gzip', 'x-localstack-tgt-api': 'ec2'}); 
```
The user-agent is stated as terraform. 

[In the terraform docs it states, that the flag `skip_get_ec2_platforms` can be set](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#skip_get_ec2_platforms).

When running your example with the flag enabled, the logs don't reveal any ec2 calls. Please get in touch with terraform team if you have more questions in that regard. 🙂 
```
{
    "provider": {
        "aws": [
            {
                "skip_get_ec2_platforms": true
            }
        ]
        },
        "resource": {
            "aws_db_instance": {
             ...
          }
     }
}

```


Given your original problem is not related to LocalStack, I would close the issue.
