### ISSUE TITLE
bug: S3 internalError when try to get an object which was deleted before instead of error code NoSuchKey

### ISSUE THREAD

**Issue by SchmitzChristian** [localstack/localstack#6553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have some tests which are creating and deleting objects at s3. This tests are failing with localstack version 0.14.4 and newer.

Because of an internalError we get as error null instead of NoSuchKey as error code.

Logs of localstack:

```
2022-07-29T14:44:55.319 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: 'FakeDeleteMarker' object has no attribute '_expiry'
2022-07-29T14:44:55.325  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.GetObject => 500 (InternalError)
2022-07-29T14:44:55.463 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain: 'FakeDeleteMarker' object has no attribute '_expiry'
2022-07-29T14:44:55.464  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.GetObject => 500 (InternalError)
2022-07-29T14:44:57.444 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain: 'FakeDeleteMarker' object has no attribute '_expiry'
2022-07-29T14:44:57.445  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.GetObject => 500 (InternalError)
2022-07-29T14:45:00.403 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: 'FakeDeleteMarker' object has no attribute '_expiry'
2022-07-29T14:45:00.404  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.GetObject => 500 (InternalError)
2022-07-29T14:45:06.976 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain: 'FakeDeleteMarker' object has no attribute '_expiry'
2022-07-29T14:45:06.977  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.GetObject => 500 (InternalError)

An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): exception while calling s3.GetObject: 'FakeDeleteMarker' object has no attribute '_expiry'
```

### Expected Behavior

We would expect to get an error code NoSuchKey instead of null.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-conpose.yml:
> version: '3.5'
> services:
>   localstack:
>     image: localstack/localstack:1.0.2
>     volumes:
>       - ./localstack/init-localstack.sh:/docker-entrypoint-initaws.d/init-localstack.sh
>     environment:
>       - DEFAULT_REGION=eu-central-1
>       - SERVICES=s3

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

init-localstack.sh: 
```
awslocal s3api create-bucket --bucket test-bucket --create-bucket-configuration LocationConstraint=eu-central-1
awslocal s3api put-object --bucket test-bucket --key test.json
awslocal s3api get-object --bucket test-bucket --key test.json test.json
awslocal s3api delete-object --bucket test-bucket --key test.json
awslocal s3api get-object --bucket test-bucket --key test.json test.json
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 1.0.2
```

**Comment by cjphillips** [comment]
Running into this as well. Full stack here:

```
2022-09-13T17:21:33.625 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
File "/opt/code/localstack/localstack/aws/chain.py", line 57, in handle
handler(self, self.context, response)
File "/opt/code/localstack/localstack/aws/handlers/service.py", line 121, in __call__
handler(chain, context, response)
File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 81, in __call__
result = self.forward_request(
File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 141, in forward_request
return do_forward_request(
File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
result = do_forward_request_inmem(api, method, path, data, headers, port=port)
File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
response = modify_and_forward(
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 604, in wrapper
value = func(*args, **kwargs)
File "/opt/code/localstack/localstack/services/generic_proxy.py", line 777, in modify_and_forward
updated_response = listener.return_response(
File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 1643, in return_response
if key_name and is_object_expired(bucket_name, key_name):
File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 626, in is_object_expired
if not key_obj or not key_obj._expiry:
AttributeError: 'FakeDeleteMarker' object has no attribute '_expiry'
2022-09-13T17:21:33.626  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.GetObject => 500 (InternalError)
```

Any ideas for a workaround aside from disabling versioning on the bucket?
