### ISSUE TITLE
bug: organizations list-tags-for-resource returns HTTP 500

### ISSUE THREAD

**Issue by xanol** [localstack/localstack#6556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After creating and AWS Organizations SCP policy with no tags, I call the organizations:list-tags-for-resource API on the resource and get the following error:

```
An error occurred (InternalError) when calling the ListTagsForResource operation (reached max retries: 4): exception while calling organizations.ListTagsForResource: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 57, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 121, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 91, in __call__
    skeleton_response = self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/forwarder.py", line 59, in _call
    return fallthrough_handler(context, req)
  File "/opt/code/localstack/localstack/services/moto.py", line 84, in proxy_moto
    status, headers, content = dispatch_to_moto(context)
  File "/opt/code/localstack/localstack/services/moto.py", line 114, in dispatch_to_moto
    return dispatch(request, request.url, request.headers)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/responses.py", line 205, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/responses.py", line 315, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/responses.py", line 405, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/organizations/responses.py", line 177, in list_tags_for_resource
    self.organizations_backend.list_tags_for_resource(**self.request_params)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/organizations/models.py", line 733, in list_tags_for_resource
    tags = [{"Key": key, "Value": value} for key, value in resource.tags.items()]
AttributeError: 'FakePolicy' object has no attribute 'tags'

```

### Expected Behavior

The expected response is:

```
{
    "Tags": []
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
version: "3.6"

services:
  localstack:
    container_name: localstack-aws-org
    environment:
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=localhost
      - TEST_AWS_ACCOUNT_ID=000000000000
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - REQUESTS_CA_BUNDLE=/usr/local/share/ca-certificates/ZscalerRootCertificate-2048-SHA256.pem
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - REQUIRE_PRO=1
      - PERSISTENCE=0
      - DATA_DIR=
      - PERSIST_ALL=false
    image: localstack/localstack:1.0.2
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/usr/local/share/ca-certificates
      - ./bin:/docker-entrypoint-initaws.d
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Create an organization:
`awslocal organizations create-organization`

Create an Organization SCP:
```

$ awslocal organizations create-policy --content "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":[\"s3:*\"],\"Resource\":[\"*\"]}]}" --name test-scp --type SERVICE_CONTROL_POLICY --description "test-scp"
{
    "Policy": {
        "PolicySummary": {
            "Id": "p-kxqo1w4t",
            "Arn": "arn:aws:organizations::000000000000:policy/o-vnpflmfqiu/service_control_policy/p-kxqo1w4t",
            "Name": "test-scp",
            "Description": "test-scp",
            "Type": "SERVICE_CONTROL_POLICY",
            "AwsManaged": false
        },
        "Content": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":[\"s3:*\"],\"Resource\":[\"*\"]}]}"
    }
}

```

Attempt to list the tags for the SCP you just created:
```
$ awslocal organizations list-tags-for-resource --resource-id p-kxqo1w4t

An error occurred (InternalError) when calling the ListTagsForResource operation (reached max retries: 4): exception while calling organizations.ListTagsForResource: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 57, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 121, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 91, in __call__
    skeleton_response = self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/forwarder.py", line 59, in _call
    return fallthrough_handler(context, req)
  File "/opt/code/localstack/localstack/services/moto.py", line 84, in proxy_moto
    status, headers, content = dispatch_to_moto(context)
  File "/opt/code/localstack/localstack/services/moto.py", line 114, in dispatch_to_moto
    return dispatch(request, request.url, request.headers)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/responses.py", line 205, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/responses.py", line 315, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/responses.py", line 405, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/organizations/responses.py", line 177, in list_tags_for_resource
    self.organizations_backend.list_tags_for_resource(**self.request_params)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/organizations/models.py", line 733, in list_tags_for_resource
    tags = [{"Key": key, "Value": value} for key, value in resource.tags.items()]
AttributeError: 'FakePolicy' object has no attribute 'tags'
```

    

### Environment

```markdown
- OS: OSX BigSur
- LocalStack: 1.0.2
```

### Anything else?

There are a few additional log messages in the Localstack stdout:

localstack-aws-org | AttributeError: 'FakePolicy' object has no attribute 'tags'
localstack-aws-org | 2022-07-29T22:56:48.049  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS organizations.ListTagsForResource => 500 (InternalError)
localstack-aws-org | 2022-07-29T22:56:55.747 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain

**Comment by thrau** [comment]
we deployed a fix and this should now work with the latest image.
