### ISSUE TITLE
bug: Presigned S3 upload issues

### ISSUE THREAD

**Issue by krystof-k** [localstack/localstack#6588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

_I have no idea if I'm doing something wrong, before it worked fine (unfortunately I don't have any idea about the version), but all I get is meaningless error._

I'm unable to upload file to a S3 presigned URL (URL is created via Ruby). The file is then uploaded via Dropzone.js. It is working fine against AWS.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Here is the cURL:

```console
curl 'http://localstack.localhost.localstack.cloud:4566/' \
  -H 'Accept: application/json' \
  -H 'Accept-Language: cs,en;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryy88aMIk453wF82qw' \
  -H 'Origin: http://localhost:3000' \
  -H 'Referer: http://localhost:3000/' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36' \
  --data-raw $'------WebKitFormBoundaryy88aMIk453wF82qw\r\nContent-Disposition: form-data; name="policy"\r\n\r\neyJleHBpcmF0aW9uIjoiMjAyMi0wOC0wM1QxODoyOToyNloiLCJjb25kaXRpb25zIjpbeyJidWNrZXQiOiJsb2NhbHN0YWNrIn0sWyJzdGFydHMtd2l0aCIsIiRrZXkiLCJyb29tLXRlc3QtODQ3Mjc1NTQ3L3RtcC91cGxvYWQvMjAyMi8wOC8wMy9kMTZiZDZkMi1lMzVhLTRlMDYtYjUxYy1iMGE4NmVkMGYzNDcvIl0sWyJjb250ZW50LWxlbmd0aC1yYW5nZSIsMCwyNTAwMDAwMDBdLFsic3RhcnRzLXdpdGgiLCIkdXRmOCIsIiJdLFsic3RhcnRzLXdpdGgiLCIkYXV0aGVudGljaXR5X3Rva2VuIiwiIl0seyJ4LWFtei1jcmVkZW50aWFsIjoidGVzdC8yMDIyMDgwMy9ldS1jZW50cmFsLTEvczMvYXdzNF9yZXF1ZXN0In0seyJ4LWFtei1hbGdvcml0aG0iOiJBV1M0LUhNQUMtU0hBMjU2In0seyJ4LWFtei1kYXRlIjoiMjAyMjA4MDNUMTcyOTI2WiJ9XX0=\r\n------WebKitFormBoundaryy88aMIk453wF82qw\r\nContent-Disposition: form-data; name="x-amz-credential"\r\n\r\ntest/20220803/eu-central-1/s3/aws4_request\r\n------WebKitFormBoundaryy88aMIk453wF82qw\r\nContent-Disposition: form-data; name="x-amz-algorithm"\r\n\r\nAWS4-HMAC-SHA256\r\n------WebKitFormBoundaryy88aMIk453wF82qw\r\nContent-Disposition: form-data; name="x-amz-date"\r\n\r\n20220803T172926Z\r\n------WebKitFormBoundaryy88aMIk453wF82qw\r\nContent-Disposition: form-data; name="x-amz-signature"\r\n\r\nc4c407840936a3c5293899010d259a8ce662a2429247d2beac8142b36e005285\r\n------WebKitFormBoundaryy88aMIk453wF82qw\r\nContent-Disposition: form-data; name="key"\r\n\r\nroom-test-847275547/tmp/upload/2022/08/03/d16bd6d2-e35a-4e06-b51c-b0a86ed0f347/sni_mek_obrazovky_2022_08_01_v_18_01_32_png\r\n------WebKitFormBoundaryy88aMIk453wF82qw\r\nContent-Disposition: form-data; name="utf8"\r\n\r\n✓\r\n------WebKitFormBoundaryy88aMIk453wF82qw\r\nContent-Disposition: form-data; name="authenticity_token"\r\n\r\n0JVk7R/FRnfXFCT1k1RllpZ2BFjaWh9+6bNLYgn8iAiB7tZ7hjS6ZTx22Jl4iEqcw0y1G8oAkU+RF1cQbLKmuQ==\r\n------WebKitFormBoundaryy88aMIk453wF82qw\r\nContent-Disposition: form-data; name="file"; filename="Snímek obrazovky 2022-08-01 v 18.01.32.png"\r\nContent-Type: image/png\r\n\r\n\r\n------WebKitFormBoundaryy88aMIk453wF82qw--\r\n' \
  --compressed \
  --insecure
```

All I get is error 500 with this payload

```json
{"message": "Unexpected exception", "error": "400 Bad Request: The browser (or proxy) sent a request that this server could not understand.", "type": "ClientDisconnected"}
```

This is in the LocalStack console:

```
2022-08-03T17:29:26.445 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 57, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 31, in __call__
    service = determine_aws_service_name(context.request)
  File "/opt/code/localstack/localstack/aws/protocol/service_router.py", line 314, in determine_aws_service_name
    values = request.values
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/utils.py", line 107, in __get__
    value = self.fget(obj)  # type: ignore
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 448, in values
    sources.append(self.form)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/utils.py", line 107, in __get__
    value = self.fget(obj)  # type: ignore
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 428, in form
    self._load_form_data()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 266, in _load_form_data
    data = parser.parse(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 263, in parse
    return parse_func(self, stream, mimetype, content_length, options)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 140, in wrapper
    return f(self, stream, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 290, in _parse_multipart
    form, files = parser.parse(stream, boundary, content_length)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 418, in parse
    for data in iterator:
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 653, in _make_chunk_iter
    item = _read(buffer_size)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 925, in read
    return self.on_disconnect()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 893, in on_disconnect
    raise ClientDisconnected()
werkzeug.exceptions.ClientDisconnected: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2022-08-03T17:29:26.447 DEBUG --- [   asgi_gw_0] l.aws.handlers.fallback    : setting internal failure response for 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2022-08-03T17:29:26.449 ERROR --- [   asgi_gw_0] localstack.aws.chain       : exception while running response handler
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 122, in _call_response_handlers
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/logging.py", line 47, in __call__
    self._log(context, response)
  File "/opt/code/localstack/localstack/aws/handlers/logging.py", line 142, in _log
    "input": restore_payload(context.request),
  File "/opt/code/localstack/localstack/http/request.py", line 220, in restore_payload
    data = request.data
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/utils.py", line 107, in __get__
    value = self.fget(obj)  # type: ignore
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 354, in data
    return self.get_data(parse_form_data=True)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 404, in get_data
    self._load_form_data()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 266, in _load_form_data
    data = parser.parse(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 263, in parse
    return parse_func(self, stream, mimetype, content_length, options)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 140, in wrapper
    return f(self, stream, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 290, in _parse_multipart
    form, files = parser.parse(stream, boundary, content_length)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 418, in parse
    for data in iterator:
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 653, in _make_chunk_iter
    item = _read(buffer_size)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 925, in read
    return self.on_disconnect()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 893, in on_disconnect
    raise ClientDisconnected()
werkzeug.exceptions.ClientDisconnected: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

### Environment

```markdown
- OS: macOS Monterey 12.5 (21G72)
- LocalStack: 1.0.4.dev
```

**Comment by krystof-k** [comment]
If I use s3.localhost.localstack.cloud:4566, I get this response instead:

```xml
<?xml version='1.0' encoding='utf-8'?>
<Error>
    <Code>InternalError</Code>
    <Message>exception while calling s3 with unknown operation: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 57, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/auth.py", line 27, in __call__
    headers["Authorization"] = aws_stack.mock_aws_request_headers(api)["Authorization"]
  File "/opt/code/localstack/localstack/utils/aws/aws_stack.py", line 919, in mock_aws_request_headers
    region_name = region_name or get_region()
  File "/opt/code/localstack/localstack/utils/aws/aws_stack.py", line 200, in get_region
    region = get_region_from_request_context()
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 109, in get_region_from_request_context
    request_context = get_request_context()
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 84, in get_request_context
    candidates = [get_proxy_request_for_thread(), get_flask_request_for_thread()]
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 46, in get_flask_request_for_thread
    data=request.data,
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/utils.py", line 107, in __get__
    value = self.fget(obj)  # type: ignore
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 354, in data
    return self.get_data(parse_form_data=True)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 404, in get_data
    self._load_form_data()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 266, in _load_form_data
    data = parser.parse(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 263, in parse
    return parse_func(self, stream, mimetype, content_length, options)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 140, in wrapper
    return f(self, stream, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 290, in _parse_multipart
    form, files = parser.parse(stream, boundary, content_length)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 418, in parse
    for data in iterator:
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 653, in _make_chunk_iter
    item = _read(buffer_size)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 925, in read
    return self.on_disconnect()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 893, in on_disconnect
    raise ClientDisconnected()
werkzeug.exceptions.ClientDisconnected: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
</Message>
    <RequestId>0Z6T6Y7ZMECDKZ0CC0D47UPI42219B6U0JWC9Q26USDC3ZOTX1NP</RequestId>
</Error>
```

**Comment by pinzon** [comment]
@krystof-k if you're using `presign_url` you should add -X PUT, if you're using `presign_post` (which seems to be the case), you should add -X POST to the cURL command.

**Comment by krystof-k** [comment]
POST, yes, but that's not the case, it is just missing in the cURL from Chrome.

**Comment by pinzon** [comment]
**Could you provide an example code on how you create your client, generate the curl command and how you start localstack?** just recently closed #5554 (another issue with presign urls) and the problem was with user's code.

Just for reference, I run your command with my Localstack setup (before, I created the bucket with awscli) and the error I get is the expiration of the token, understandable but my Localstack didn't crash.
```xml
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>ExpiredToken</Code><Message>The provided token has expired.</Message><Resource>/</Resource><RequestId></RequestId></Error>%    
```

**Comment by krystof-k** [comment]
I know, sorry, but that is hard, it is wired up in the Ruby app. I'll try to create a separate example.

LocalStack is started via Docker Compose:

```yaml
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      DEBUG: 1
      DISABLE_CORS_CHECKS: '1'
      PERSISTENCE: '1'
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - .localstack:/docker-entrypoint-initaws.d
      - localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: awslocal s3 ls localstack
      interval: 5s
      timeout: 5s
      retries: 15
```

I've tried adding various `HOSTNAME_EXTERNAL` values but it didn't help.

The S3 endpoint for the SDK `http://s3.localhost.localstack.cloud:4566` is OK? Thanks!

**Comment by pinzon** [comment]
Could you try just `http://localhost.localstack.cloud:4566` as the endpoint?

**Comment by krystof-k** [comment]
Yes, that was what I've started with (the JSON error) which crashes on `determine_aws_service_name` if I understand the trace correctly.

**Comment by pinzon** [comment]
mmm this could be an issue with your setup, docker or docker compose, not much with the Ruby AWS SDK, but either way I'll have to test it. It would help if you could write a small ruby project that crashes for you when using LocalStack ([here is an amazing reproducer another user wrote for his issue](https://github.com/kingster307/localstack_onObjectCreated_bug)).

Here is the reproducer I wrote (hopefully it works for you too):
```python
import boto3
import requests
import curlify

with open('file.txt', 'r') as object_file:
    object_text = object_file.read()

s3 = boto3.client('s3', endpoint_url="http://s3.localhost.localstack.cloud:4566")


bucket_name = "test-bucket"
key_name = f"example.file"

s3.create_bucket(Bucket=bucket_name)

presigned_post = s3.generate_presigned_post(Bucket=bucket_name, Key=key_name)

curl_command =curlify.to_curl(requests.post(
    presigned_post['url'], 
    data=presigned_post['fields']
    ,files={"file": open("file.txt",'r') }
    ).request)

print(curl_command)
```

**Comment by krystof-k** [comment]
OK, this is insane. It's because of the PNG file probably. Just a sec, I have the reproducer too.

**Comment by krystof-k** [comment]
Here it is: https://github.com/krystof-k/localstack-bug.

Just `docker compose up --build` and then try running both cURL from `curl.txt` from the host. Text file works, PNG fails.

**Comment by krystof-k** [comment]
I just tried it in the full-scale Rails app and the text file works too. I really don't get it. It's just a normal PNG, macOS screenshot… Of course when uploading directly to AWS it works fine.

**Comment by pinzon** [comment]
thanks @krystof-k I'll work on this as soon as I can.

**Comment by krystof-k** [comment]
Awesome, thanks so much!

**Comment by krystof-k** [comment]
Actually it looks like it's not working with anything except text files.

**Comment by krystof-k** [comment]
I'm probably slowly starting to understand :) You released completely reworked version few weeks ago and that broke a lot of things. Except this bug (I can confirm in 0.14.5 working just fine with all filetypes), it also removes persistence from the community version, which is exactly the only thing we were using LocalStack for (except CI).

So for now I'm switching back to the 0.14.5, so no need to hurry with the fix @pinzon. Thanks for your quick support!

**Comment by pinzon** [comment]
awesome! thanks for looking into it! Sorry about the persistence mechanism, you can read more about it [here](https://docs.localstack.cloud/localstack/persistence-mechanism/).

**Comment by daveykane** [comment]
we are having the same issue with image files, for now we'll also go back to 0.14.5

**Comment by proserve** [comment]
I'm also facing the issue, any workaround until you release the fix?

**Comment by proserve** [comment]
Thanks, @henriacle downgrading works for me multipart upload with the presigned URL is working, but SQS messages configured with the bucket are not triggered.

**Comment by arnaldop** [comment]
I can confirm the following behavior:
- File type: XLSX
- File size: 163,768 bytes

Localstack:
- 1.2.0 - fails
- 1.1.0 - fails
- 0.14.5 - passes

**Comment by Meemaw** [comment]
@thrau any update on this?

**Comment by Meemaw** [comment]
> @Meemaw i made that works uploading via put with the presigned url, just generate the links using bucket as host in true and virtual host in false
> 
> But presents persistence probles with mac os with m1 computers, the call gives an 200 but the file isnt saved in the bucket

This isn't really helpful, we need the file to be stored correctly for post processing.

**Comment by nicolkill** [comment]
> This isn't really helpful, we need the file to be stored correctly for post processing.

I know, but yesterday testing with an m1 and m1pro macbooks we discovered that the problem its just with m1pro, and in the m1pro we tests in terminal generating an presigned url and with curl uploading an file and works, so means that its an specific configuration that its causing the error, for today we will tests again until find the bug, so when had the results ill push the response here

**Comment by lorenmh** [comment]
FWIW, as a rando who set up notifications for this issue, I hit this bug on MacBoo Pro Intel (not Apple silicon), seems to not be related to me but I did not dig

**Comment by ramnes** [comment]
We're also hitting this. The OS is unrelated since we're experiencing the issue on both macOS and Linux.

**Comment by ramnes** [comment]
Also happens on M1, it's not architecture-related.

**Comment by bentsku** [comment]
Hello and thank you all for your reports!

After investigating, it seems the issue came from the underlying Werkzeug implementation. You can read more about it in [this PR](https://github.com/localstack/localstack/pull/7365).

I'll come back to this issue as soon as the fix is part of our latest Docker image to notify you.

**Comment by bentsku** [comment]
Hello again,

The fix is now part of the latest Docker image, you can get it by running `docker pull localstack/localstack:latest`.

In the meantime, we have been working on a new implementation of S3, and it is now available under a feature flag. Could you try starting LocalStack with PROVIDER_OVERRIDE_S3=asf (for configuration of LocalStack, you can see [here](https://docs.localstack.cloud/references/configuration/)). We have overhauled the service globally, and pre-signed URL are part of it, and our efforts to increase parity will be directed towards this new implementation. It will become the default in the next major release.
We'd appreciate the feedback as well!

Thanks again to everybody for your reports.

**Comment by Meemaw** [comment]
@bentsku is this part of `1.3.1`?

**Comment by bentsku** [comment]
Hi @Meemaw,

Unfortunately no, it is not part of a tagged release yet. The next minor release (`1.4.0`) should be in February.

**Comment by Achiever223** [comment]
Oh really ?

**Comment by thhung** [comment]
@bentsku Do you have any update for this isssue? I have the same problem with image/png and on MacOS M1: 
My config: 
LocalStack version: 3.1.1.dev
LocalStack Docker container id: c319c997bb58
LocalStack build date: 2024-02-07
LocalStack build git hash: 361abbf98

**Comment by bentsku** [comment]
Hi @thhung!

This particular issue was fixed early 2023.
Could you please open a new issue with some steps to reproduce the issue? This could be a regression. Thanks!

**Comment by thhung** [comment]
Thanks @bentsku for your super quick reply. I found the fix for my problem. I confirm localstack now works correctly on my setup.

**Comment by bentsku** [comment]
Awesome @thhung, thanks for the feedback and glad that your issue is solved!

**Comment by jamesybarra1141** [comment]
Hi, @ramnes @daveykane  @whummer  @lorenmh 
How is it going?
I have one issues as you like.
I am facing cors error from localhost to aws s3 bucket.
Please help me quickly.
Thank you for your time.
