### ISSUE TITLE
bug: Attempting to deploy a Cloudfront Distribution CDK Construct with enableLogging: true throws an error

### ISSUE THREAD

**Issue by Garethp** [localstack/localstack#6599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to deploy a Cloudfront Distribution construct with CDK:

```ts
    new Distribution(this, "ApiCloudFrontDistribution", {
      defaultBehavior: {
        origin: new HttpOrigin("test.com"),
      },
      enableLogging: true,
      domainNames: ["test.com"],
      certificate: new Certificate(this, "Cert", {
        domainName: "test.com",
      }),
    });
```

I get the following error from LocalStack even though the same construct deploys to AWS without issue

However when I do so it fails to deploy and I get this error in LocalStack:

```
2022-08-05T11:30:45.521 DEBUG --- [  Thread-279] l.u.c.template_deployer    : Handling "Add" for resource "testApiCloudFrontDistributionA3B25A8A" (1/2) type "AWS::CloudFront::Distribution" in loop iteration 1 (should_deploy=True)
2022-08-05T11:30:45.537 DEBUG --- [  Thread-279] l.u.c.template_deployer    : Running action "create" for resource type "CloudFront::Distribution" id "testApiCloudFrontDistributionA3B25A8A"
2022-08-05T11:30:45.648 DEBUG --- [  Thread-279] l.u.c.template_deployer    : Request for resource type "CloudFront::Distribution" in region eu-west-2: create_distribution_with_tags {'DistributionConfigWithTags': {'DistributionConfig': {'Aliases': {'Quantity': 1, 'Items': ['test.com']}, 'DefaultCacheBehavior': {'CachePolicyId': '658327ea-f89d-4fab-a63d-7e88639e58f6', 'Compress': True, 'TargetOriginId': 'stacktestApiCloudFrontDistributionOrigin14911EF32', 'ViewerProtocolPolicy': 'allow-all', 'TrustedSigners': {'Quantity': 0, 'Enabled': False}, 'MinTTL': 600, 'ForwardedValues': {'QueryString': False, 'Cookies': {'Forward': 'All'}}, 'AllowedMethods': {'Quantity': 0, 'Items': [], 'CachedMethods': {'Quantity': 0, 'Items': []}}}, 'Enabled': True, 'HttpVersion': 'http2', 'Logging': {'Bucket': 'stack-testapicloudfrontdistrib-da4dad12.s3.localhost.localstack.cloud'}, 'Origins': {'Quantity': 1, 'Items': [{'CustomOriginConfig': {'OriginProtocolPolicy': 'https-only', 'OriginSslProtocols': {'Quantity': 1, 'Items': ['TLSv1.2']}, 'HTTPPort': 80, 'HTTPSPort': 443}, 'DomainName': 'test.com', 'Id': 'stacktestApiCloudFrontDistributionOrigin14911EF32'}]}, 'ViewerCertificate': {'MinimumProtocolVersion': 'TLSv1.2_2021', 'ACMCertificateArn': 'arn:aws:acm:eu-west-2:000000000000:certificate/569d197e-a2bc-4eef-af9e-2612c4cf2124', 'SSLSupportMethod': 'sni-only'}, 'CallerReference': 'af0ba54b', 'Comment': '', 'IsIPV6Enabled': True, 'OriginGroups': {'Quantity': 0, 'Items': []}, 'CustomErrorResponses': {'Quantity': 0, 'Items': []}, 'CacheBehaviors': {'Quantity': 0, 'Items': []}}, 'Tags': {'Items': []}}}
2022-08-05T11:30:45.649 DEBUG --- [  Thread-279] l.u.c.template_deployer    : Trying original parameters: {'DistributionConfigWithTags': {'DistributionConfig': {'Aliases': {'Quantity': 1, 'Items': ['test.com']}, 'DefaultCacheBehavior': {'CachePolicyId': '658327ea-f89d-4fab-a63d-7e88639e58f6', 'Compress': True, 'TargetOriginId': 'stacktestApiCloudFrontDistributionOrigin14911EF32', 'ViewerProtocolPolicy': 'allow-all', 'TrustedSigners': {'Quantity': 0, 'Enabled': False}, 'MinTTL': 600, 'ForwardedValues': {'QueryString': False, 'Cookies': {'Forward': 'All'}}, 'AllowedMethods': {'Quantity': 0, 'Items': [], 'CachedMethods': {'Quantity': 0, 'Items': []}}}, 'Enabled': True, 'HttpVersion': 'http2', 'Logging': {'Bucket': 'stack-testapicloudfrontdistrib-da4dad12.s3.localhost.localstack.cloud'}, 'Origins': {'Quantity': 1, 'Items': [{'CustomOriginConfig': {'OriginProtocolPolicy': 'https-only', 'OriginSslProtocols': {'Quantity': 1, 'Items': ['TLSv1.2']}, 'HTTPPort': 80, 'HTTPSPort': 443}, 'DomainName': 'test.com', 'Id': 'stacktestApiCloudFrontDistributionOrigin14911EF32'}]}, 'ViewerCertificate': {'MinimumProtocolVersion': 'TLSv1.2_2021', 'ACMCertificateArn': 'arn:aws:acm:eu-west-2:000000000000:certificate/569d197e-a2bc-4eef-af9e-2612c4cf2124', 'SSLSupportMethod': 'sni-only'}, 'CallerReference': 'af0ba54b', 'Comment': '', 'IsIPV6Enabled': True, 'OriginGroups': {'Quantity': 0, 'Items': []}, 'CustomErrorResponses': {'Quantity': 0, 'Items': []}, 'CacheBehaviors': {'Quantity': 0, 'Items': []}}, 'Tags': {'Items': []}}}
2022-08-05T11:30:45.649  WARN --- [  Thread-279] l.u.c.template_deployer    : Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.CloudFront object at 0x7f03f5b41540>> with params: {'DistributionConfigWithTags': {'DistributionConfig': {'Aliases': {'Quantity': 1, 'Items': ['test.com']}, 'DefaultCacheBehavior': {'CachePolicyId': '658327ea-f89d-4fab-a63d-7e88639e58f6', 'Compress': True, 'TargetOriginId': 'stacktestApiCloudFrontDistributionOrigin14911EF32', 'ViewerProtocolPolicy': 'allow-all', 'TrustedSigners': {'Quantity': 0, 'Enabled': False}, 'MinTTL': 600, 'ForwardedValues': {'QueryString': False, 'Cookies': {'Forward': 'All'}}, 'AllowedMethods': {'Quantity': 0, 'Items': [], 'CachedMethods': {'Quantity': 0, 'Items': []}}}, 'Enabled': True, 'HttpVersion': 'http2', 'Logging': {'Bucket': 'stack-testapicloudfrontdistrib-da4dad12.s3.localhost.localstack.cloud'}, 'Origins': {'Quantity': 1, 'Items': [{'CustomOriginConfig': {'OriginProtocolPolicy': 'https-only', 'OriginSslProtocols': {'Quantity': 1, 'Items': ['TLSv1.2']}, 'HTTPPort': 80, 'HTTPSPort': 443}, 'DomainName': 'test.com', 'Id': 'stacktestApiCloudFrontDistributionOrigin14911EF32'}]}, 'ViewerCertificate': {'MinimumProtocolVersion': 'TLSv1.2_2021', 'ACMCertificateArn': 'arn:aws:acm:eu-west-2:000000000000:certificate/569d197e-a2bc-4eef-af9e-2612c4cf2124', 'SSLSupportMethod': 'sni-only'}, 'CallerReference': 'af0ba54b', 'Comment': '', 'IsIPV6Enabled': True, 'OriginGroups': {'Quantity': 0, 'Items': []}, 'CustomErrorResponses': {'Quantity': 0, 'Items': []}, 'CacheBehaviors': {'Quantity': 0, 'Items': []}}, 'Tags': {'Items': []}}} for resource: {'Type': 'AWS::CloudFront::Distribution', 'Metadata': {'aws:cdk:path': 'stack/test/ApiCloudFrontDistribution/Resource'}, 'LogicalResourceId': 'testApiCloudFrontDistributionA3B25A8A', 'Properties': {'DistributionConfig': {'Aliases': {'Quantity': 1, 'Items': ['test.com']}, 'DefaultCacheBehavior': {'CachePolicyId': '658327ea-f89d-4fab-a63d-7e88639e58f6', 'Compress': True, 'TargetOriginId': 'stacktestApiCloudFrontDistributionOrigin14911EF32', 'ViewerProtocolPolicy': 'allow-all', 'TrustedSigners': {'Quantity': 0, 'Enabled': False}, 'MinTTL': 600, 'ForwardedValues': {'QueryString': False, 'Cookies': {'Forward': 'All'}}, 'AllowedMethods': {'Quantity': 0, 'Items': [], 'CachedMethods': {'Quantity': 0, 'Items': []}}}, 'Enabled': True, 'HttpVersion': 'http2', 'Logging': {'Bucket': 'stack-testapicloudfrontdistrib-da4dad12.s3.localhost.localstack.cloud'}, 'Origins': {'Quantity': 1, 'Items': [{'CustomOriginConfig': {'OriginProtocolPolicy': 'https-only', 'OriginSslProtocols': {'Quantity': 1, 'Items': ['TLSv1.2']}, 'HTTPPort': 80, 'HTTPSPort': 443}, 'DomainName': 'test.com', 'Id': 'stacktestApiCloudFrontDistributionOrigin14911EF32'}]}, 'ViewerCertificate': {'MinimumProtocolVersion': 'TLSv1.2_2021', 'ACMCertificateArn': 'arn:aws:acm:eu-west-2:000000000000:certificate/569d197e-a2bc-4eef-af9e-2612c4cf2124', 'SSLSupportMethod': 'sni-only'}, 'CallerReference': 'af0ba54b', 'Comment': '', 'IsIPV6Enabled': True, 'OriginGroups': {'Quantity': 0, 'Items': []}, 'CustomErrorResponses': {'Quantity': 0, 'Items': []}, 'CacheBehaviors': {'Quantity': 0, 'Items': []}}}, '_state_': {}}
2022-08-05T11:30:45.650 DEBUG --- [  Thread-279] l.u.c.template_deployer    : Error applying changes for CloudFormation stack "stack": Parameter validation failed:
Missing required parameter in DistributionConfigWithTags.DistributionConfig.Logging: "Enabled"
Missing required parameter in DistributionConfigWithTags.DistributionConfig.Logging: "IncludeCookies"
Missing required parameter in DistributionConfigWithTags.DistributionConfig.Logging: "Prefix" Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1551, in _run
    self.do_apply_changes_in_loop(changes, stack, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1628, in do_apply_changes_in_loop
    self.apply_change(change, stack=stack)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1701, in apply_change
    result = deploy_resource(self, resource_id)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 847, in deploy_resource
    result = execute_resource_action(resource_id, stack, ACTION_CREATE)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 888, in execute_resource_action
    result = configure_resource_via_sdk(
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1021, in configure_resource_via_sdk
    raise e
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1011, in configure_resource_via_sdk
    result = function(**params)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 878, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 939, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Missing required parameter in DistributionConfigWithTags.DistributionConfig.Logging: "Enabled"
Missing required parameter in DistributionConfigWithTags.DistributionConfig.Logging: "IncludeCookies"
Missing required parameter in DistributionConfigWithTags.DistributionConfig.Logging: "Prefix"
```

### Expected Behavior

I expect the CloudFront Distribution to be deployed without error

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
I have the following `docker-compose.yaml`:

```yaml
version: "3.5"
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "4571:4571"
    environment:
      - SERVICES=sqs, lambda, apigateway, s3, sts, ssm, cloudformation, ecr, kms, iam, rds
      - LOCALSTACK_HOSTNAME=172.26.0.1
      - HOSTNAME=172.26.0.1
      - HOSTNAME_EXTERNAL=172.26.0.1
      - SQS_PORT_EXTERNAL=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
      - TEST_AWS_ACCOUNT_ID=000000000000
      - DEBUG=1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Along with the following CDK stack:

```ts
import { App, Stack } from "aws-cdk-lib";
import { Construct } from "constructs";
import { Queue } from "aws-cdk-lib/aws-sqs";
import { Distribution } from "aws-cdk-lib/aws-cloudfront";
import { HttpOrigin } from "aws-cdk-lib/aws-cloudfront-origins";
import { Certificate } from "aws-cdk-lib/aws-certificatemanager";

class TestStack extends Stack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new TestConstruct(this, "test");
  }
}

class TestConstruct extends Construct {
  public readonly queue: Queue;

  constructor(scope: Construct, id: string) {
    super(scope, id);

    new Distribution(this, "ApiCloudFrontDistribution", {
      defaultBehavior: {
        origin: new HttpOrigin("test.com"),
      },
      enableLogging: true,
      domainNames: ["test.com"],
      certificate: new Certificate(this, "Cert", {
        domainName: "test.com",
      }),
    });
  }
}

const app = new App();

new TestStack(app, "stack");
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

`cdklocal bootstrap && cdklocal deploy --require-approval never`

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```

**Comment by whummer** [comment]
Thanks for reporting @Garethp . We have now pushed a few enhancements for the CloudFront CloudFormation integration which should (hopefully) get this issue resolved. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks!

**Comment by whummer** [comment]
Closing as resolved - please let us know if the problem persists, happy to look into it in more detail in that case.. Thanks
