### ISSUE TITLE
05.08.2022 release: the latest localstack started to fail on `FifoQueue` attribute of the SQS Queue

### ISSUE THREAD

**Issue by dmitry-weirdo** [localstack/localstack#6602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Stating with todays (05 Aug  2022) `latest` release, the creation of the SQS Fifo Queue started to fail

```java
[ERROR] testSendUnitToSnsTopic{Unit}  Time elapsed: 0.025 s  <<< ERROR!
com.amazonaws.services.sqs.model.InvalidAttributeNameException: Unknown Attribute FifoQueue. (Service: AmazonSQS; Status Code: 400; Error Code: InvalidAttributeName; Request ID: 28E86INVH39R2N3QJX2WJ48AL1CY12D1QMOY8W7DZVOO8IJU1URD; Proxy: null)
	at com.me.ins.adapter.xml.SnsTopicSenderTest.createTopicAndSubscribedQueue(SnsTopicSenderTest.java:168)
	at com.me.ins.adapter.xml.SnsTopicSenderTest.createTopicsAndQueues(SnsTopicSenderTest.java:141)
	at com.me.ins.adapter.xml.SnsTopicSenderTest.setUp(SnsTopicSenderTest.java:116)
```

The more complete stacktrace:
```java
com.amazonaws.services.sqs.model.InvalidAttributeNameException: Unknown Attribute FifoQueue. (Service: AmazonSQS; Status Code: 400; Error Code: InvalidAttributeName; Request ID: UAWVQFE48PFBZ64YHHLCDTSZMNW0Z3VWRA9SFUCBQR4DQ4FIT26I; Proxy: null)

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2329)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2296)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2285)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeCreateQueue(AmazonSQSClient.java:890)
	at com.amazonaws.services.sqs.AmazonSQSClient.createQueue(AmazonSQSClient.java:859)
	at com.me.ins.adapter.xml.SnsTopicSenderTest.createTopicAndSubscribedQueue(SnsTopicSenderTest.java:168)
	at com.me.ins.adapter.xml.SnsTopicSenderTest.createTopicsAndQueues(SnsTopicSenderTest.java:141)
	at com.me.ins.adapter.xml.SnsTopicSenderTest.setUp(SnsTopicSenderTest.java:116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeEachMethod(TimeoutExtension.java:76)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:506)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$21(ClassBasedTestDescriptor.java:491)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachMethods$3(TestMethodTestDescriptor.java:171)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$6(TestMethodTestDescriptor.java:199)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:199)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachMethods(TestMethodTestDescriptor.java:168)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

Queue Creation code is like this:
```java
        // create SQS queue
        CreateQueueRequest createQueueRequest = new CreateQueueRequest(queueName)
            .addAttributesEntry("FifoQueue", "true")
            .addAttributesEntry("MessageRetentionPeriod", "86400");

        CreateQueueResult createQueueResult = sqs.createQueue(createQueueRequest);
```

### Expected Behavior

Everything is working as it was before today's version. 

I've tested with the `1.0.3` version and it's working.

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

Java test with Testcontainers.

### Environment

```markdown
- OS: any
- LocalStack: latest
```

**Comment by bentsku** [comment]
Hello, thanks for your report!
Could you please run localstack with the environment variable `LS_LOG=trace`, run your example again, and then share the log output?
Thanks a lot!

**Comment by thrau** [comment]
Perhaps related to #6117 where i modified how attributes are validated. It's odd that our tests don't break. Logs would be very helpful!

**Comment by bentsku** [comment]
Thanks again for your report!
This should be fixed by #6622

**Comment by mvillafuertem** [comment]
Hi @baermat @bentsku, it seems I'm experiencing the same issues with the latest version of Localstack v4.0.3. it was working correctly in version v0.14.2. 

application logs
```shell
software.amazon.awssdk.services.sqs.model.InvalidAttributeNameException: Unknown Attribute FifoQueue
software.amazon.awssdk.services.sqs.model.InvalidAttributeNameException: Unknown Attribute ContentBasedDeduplication.
```

localstack logs
```shell
2025-01-13T13:37:16.814  INFO --- [et.reactor-1] localstack.request.aws     : AWS sqs.CreateQueue => 400 (InvalidAttributeName)
2025-01-13T13:37:58.493  INFO --- [et.reactor-2] localstack.request.aws     : AWS sqs.CreateQueue => 400 (InvalidAttributeName)
2025-01-13T13:38:02.566  INFO --- [et.reactor-0] localstack.request.aws     : AWS sqs.CreateQueue => 400 (InvalidAttributeName)
2025-01-13T13:39:12.946  INFO --- [et.reactor-1] localstack.request.aws     : AWS sqs.CreateQueue => 400 (InvalidAttributeName)
```

**Comment by bentsku** [comment]
Hello @mvillafuertem! Could you please set `LS_LOG=trace` and share the logs please? Is your queue name ending with `.fifo`? Thanks!

**Comment by mvillafuertem** [comment]
@bentsku Nope, it’s an automated integration tests, and to avoid naming conflicts, I use the following pattern: queue-{uuid}.

```shell
2025-01-13T16:09:27.245  INFO --- [et.reactor-0] localstack.request.aws     : AWS sqs.CreateQueue => 400 (InvalidAttributeName); 000000000000/eu-west-2; CreateQueueReques
t({'QueueName': 'queue-909e77c3-89cf-4268-bddb-d4d7c51ec1d7', 'Attributes': {'DelaySeconds': '0', 'MessageRetentionPeriod': '86400', 'ContentBasedDeduplication': 'false',
 'VisibilityTimeout': '30'}}, headers={'host': 'localstack.nonprod.inv.gbgplc.com', 'x-real-ip': '192.168.90.1', 'x-forwarded-proto': 'https', 'content-length': '327', 'a
mz-sdk-invocation-id': '3b70a273-4fde-3ea9-a465-93e2d01d4300', 'amz-sdk-request': 'attempt=1; max=4', 'authorization': 'AWS4-HMAC-SHA256 Credential=whatever/20250113/eu-w
est-2/sqs/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-type;host;x-amz-date, Signature=941dfc1f33e4c8c9dfdfe4b4d1db46b27525b19
36ce378b7b48b560b5ac45e15', 'content-type': 'application/x-www-form-urlencoded; charset=utf-8', 'user-agent': 'aws-sdk-java/2.17.113 Mac_OS_X/15.1.1 OpenJDK_64-Bit_Server
_VM/17.0.8.1+1-LTS Java/17.0.8.1 scala/2.13.14 vendor/Azul_Systems__Inc. io/async http/UNKNOWN cfg/retry-mode/legacy', 'x-amz-date': '20250113T160926Z', 'x-request-id': '
2194e429-d648-45e3-a408-6f48861f5e3e', 'x-envoy-expected-rq-timeout-ms': '15000', 'x-moto-account-id': '000000000000'}); InvalidAttributeName(Unknown Attribute ContentBas
edDeduplication., headers={'Content-Type': 'text/xml', 'Content-Length': '291'})
```

**Comment by mvillafuertem** [comment]
@bentsku But if I set the attributes `'Attributes': {'FifoQueue': 'false'}}`, I get the same error... 

```scala
  protected val defaultAttributes: Map[QueueAttributeName, String] = Map(
    QueueAttributeName.FIFO_QUEUE                  -> "false",
  )
```

```shell
software.amazon.awssdk.services.sqs.model.InvalidAttributeNameException: Unknown Attribute FifoQueue.
```

```shell
2025-01-13T16:22:11.782  INFO --- [et.reactor-0] localstack.request.aws     : AWS sqs.CreateQueue => 400 (InvalidAttributeName); 000000000000/eu-west-2; CreateQueueReques
t({'QueueName': 'queue-a6f015aa-4bfc-436c-9d5e-fa349b52709f', 'Attributes': {'FifoQueue': 'false'}}, headers={'host': 'localstack.nonprod.inv.com', 'x-real-ip': '1
92.168.90.1', 'x-forwarded-proto': 'https', 'content-length': '141', 'amz-sdk-invocation-id': '833dd365-614b-2df4-3a08-de2a7152f990', 'amz-sdk-request': 'attempt=1; max=4
', 'authorization': 'AWS4-HMAC-SHA256 Credential=whatever/20250113/eu-west-2/sqs/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;content-length;content-
type;host;x-amz-date, Signature=5d5ed5d303706c1a2e44a8105f0e5f649bb3c650b527302af1e6f50f1a0cff81', 'content-type': 'application/x-www-form-urlencoded; charset=utf-8', 'us
er-agent': 'aws-sdk-java/2.17.113 Mac_OS_X/15.1.1 OpenJDK_64-Bit_Server_VM/17.0.8.1+1-LTS Java/17.0.8.1 scala/2.13.14 vendor/Azul_Systems__Inc. io/async http/UNKNOWN cfg/
retry-mode/legacy', 'x-amz-date': '20250113T162211Z', 'x-request-id': 'a71b6143-e818-4cdf-8446-faff4d938163', 'x-envoy-expected-rq-timeout-ms': '15000', 'x-moto-account-i
d': '000000000000'}); InvalidAttributeName(Unknown Attribute FifoQueue., headers={'Content-Type': 'text/xml', 'Content-Length': '275'})
```

**Comment by bentsku** [comment]
@mvillafuertem yes, this is also AWS behavior. If the `FifoQueue` attribute is specified, the queue needs to end with `fifo`:
```sh
aws sqs create-queue --queue-name test-queue --attributes FifoQueue=false

> An error occurred (InvalidAttributeName) when calling the CreateQueue operation: Unknown Attribute FifoQueue.
```
