### ISSUE TITLE
Not able to use SSM DescribeInstanceInformation

### ISSUE THREAD

**Issue by aditya-dixit1** [localstack/localstack#6610]
**Is there an existing issue for this?**

- [x] I have searched the existing issues

**Current Behavior**
Getting below error when trying to use "DescribeInstanceInformation":

`software.amazon.awssdk.services.ssm.model.SsmException: API action 'DescribeInstanceInformation' for service 'ssm' not yet implemented (Service: Ssm, Status Code: 501, Request ID: UDFMZ46YIXZK7L2L93RRANSWDFVSJTXSBHYHOYRK540P4QLC78EO, Extended Request ID: null)
	at software.amazon.awssdk.services.ssm.model.SsmException$BuilderImpl.build(SsmException.java:95)
	at software.amazon.awssdk.services.ssm.model.SsmException$BuilderImpl.build(SsmException.java:55)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.unmarshall(AwsJsonProtocolErrorUnmarshaller.java:89)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.handle(AwsJsonProtocolErrorUnmarshaller.java:63)
	at software.amazon.awssdk.protocols.json.internal.unmarshall.AwsJsonProtocolErrorUnmarshaller.handle(AwsJsonProtocolErrorUnmarshaller.java:42)
	at software.amazon.awssdk.core.http.MetricCollectingHttpResponseHandler.lambda$handle$0(MetricCollectingHttpResponseHandler.java:52)
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:64)
`

**Expected Behavior**:

API should return instance information.

**How are you starting LocalStack?**

Through Docker. Localstack  docker image version "localstack/localstack:1.0.3"

**Steps To Reproduce**:

1. Create and start a localstack container :

```
val localstackImage = DockerImageName.parse("localstack/localstack:1.0.3")

val localStackContainer = LocalStackContainer(localstackImage).withServices(
            LocalStackContainer.Service.EC2,
            LocalStackContainer.Service.SSM,
        )
localStackContainer.start()
```

2. Build SSM Client:
`SsmAsyncClient.builder().region(Region.of(localStackContainer.region))
            .endpointOverride(localStackContainer.getEndpointOverride(LocalStackContainer.Service.SSM)).build()`

3. Call DescribeInstanceInformation API:

```
val instanceInformationFilter = InstanceInformationStringFilter.builder().key("InstanceIds").values(instanceIds).build()

val describeInstanceInfoRequest = DescribeInstanceInformationRequest.builder().filters(instanceInformationFilter).build()

val describeInstanceResponse = ssmAsyncClient.describeInstanceInformationPaginator(describeInstanceInfoRequest).await()
```

**Environment**
- OS: MacOS latest
- LocalStack: latest

**Comment by buddhics** [comment]
Hey, I would like to work on this issue.

**Comment by techrajdeep** [comment]
Hey @whummer @HarshCasper @silv-io @aditya-dixit1 , I am looking for an issue for my first contribution . Can you help me here.

**Comment by buddhics** [comment]
Hi @whummer , @HarshCasper , @silv-io , @aditya-dixit1 , I managed to set up the dev environment and recreate this error. Need your help to resolve this.

**Comment by HarshCasper** [comment]
Hi — @buddhics I have assigned you the issue. Please try to replicate the above issue before moving forward with solving the bug :)

**Comment by buddhics** [comment]
Hi @whummer and @HarshCasper 

I managed to replicate the exact issue and this can be seen in the debug console log.

`2022-10-16T01:26:13.443  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "_load_service_plugin" took 510.80ms
2022-10-16T01:26:13.444  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "require" took 512.70ms
2022-10-16T01:26:13.704  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS ec2.RunInstances => 200
2022-10-16T01:26:13.808  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS ec2.CreateTags => 200
2022-10-16T01:26:14.165  INFO --- [   asgi_gw_0] localstack.aws.skeleton    : API action 'DescribeInstanceInformation' for service 'ssm' not yet implemented or pro feature - check https://docs.localstack.cloud/aws/feature-coverage for further information
2022-10-16T01:26:14.175  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS ssm.DescribeInstanceInformation => 501 (InternalFailure)`

This is a pro feature according to the coverage document.

It has mentioned here: `https://docs.localstack.cloud/localstack/coverage/#ssm`

**Comment by HarshCasper** [comment]
Hi @buddhics — Thanks for verifying this. Unfortunately, Pro features are worked upon by LocalStack engineers on our private codebase. Thanks for triaging and I would further connect with you over this thread to help you record a contribution for the triage you made.

**Comment by buddhics** [comment]
Thanks @HarshCasper

**Comment by HarshCasper** [comment]
Hi — We have implemented this API as part of our [Pro coverage](https://docs.localstack.cloud/references/coverage/#ssm). I hope that solves the issue and we would appreciate if you can give this a run and share your feedback!
