### ISSUE TITLE
Support "ANY" HTTP method in API Gateway resources

### ISSUE THREAD

**Issue by Luxoboy** [localstack/localstack#667]
Hey,

Currently it is not possible to call an API Gateway which has a resource with its HTTP method set to `ANY`. It is however possible to create such a resource in localstack. The  implemented behavior seems to be that localstack actually expects the HTTP method of incoming requests to be `ANY` instead of interpreting `ANY` as "any HTTP methods".

 I quickly investigated and I believe the fix may be done either in [get_apigateway_integration](https://github.com/localstack/localstack/blob/master/localstack/utils/aws/aws_stack.py#L321-L335) or directly in [forward_request](https://github.com/localstack/localstack/blob/master/localstack/services/apigateway/apigateway_listener.py#L157-L169).

Thanks.

**Comment by whummer** [comment]
Thanks for reporting @Luxoboy - indeed [forward_request](https://github.com/localstack/localstack/blob/master/localstack/services/apigateway/apigateway_listener.py#L157-L169) would be a good starting point. Any chance you could create a pull request for this feature (including a few tests)? I'd be happy to help out with the implementation, if there are any questions. Thanks!

**Comment by crypticmind** [comment]
I'm trying to setup localstack on my machine (OSX) to give this issue a shot, but I cannot invoke a lambda via API gateway. I keep getting this error:
```
Error on request:
Traceback (most recent call last):
File "/Users/cryptic/dev/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
execute(self.server.app)
File "/Users/cryptic/dev/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
application_iter = app(environ, start_response)
File "/Users/cryptic/dev/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 93, in __call__
return backend_app(environ, start_response)
File "/Users/cryptic/dev/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/cryptic/dev/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/Users/cryptic/dev/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/cryptic/dev/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/Users/cryptic/dev/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/cryptic/dev/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/Users/cryptic/dev/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/cryptic/dev/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/cryptic/dev/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 139, in __call__
result = self.callback(request, request.url, {})
File "/Users/cryptic/dev/localstack/.venv/lib/python2.7/site-packages/moto/apigateway/responses.py", line 57, in resources
resources = self.backend.list_resources(function_id)
File "/Users/cryptic/dev/localstack/.venv/lib/python2.7/site-packages/moto/apigateway/models.py", line 491, in list_resources
api = self.get_rest_api(function_id)
File "/Users/cryptic/dev/localstack/.venv/lib/python2.7/site-packages/moto/apigateway/models.py", line 480, in get_rest_api
rest_api = self.apis[function_id]
KeyError: u'3574566326'
```

I works fine from the docker image though.

I put how I came up with the lambda and the API gateway integration in [this gist](https://gist.github.com/crypticmind/c75db15fd774fe8f53282c3ccbe3d7ad).
