### ISSUE TITLE
bug: Persistence problem for lambda authorizers in apigatewayv2

### ISSUE THREAD

**Issue by nerochiaro** [localstack/localstack#6690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems that authorizer lambdas for apigatewayv2 HTTP APIs are not properly persisted between restarts of localstack, or their state is corrupt and they can't be successfully invoked.

### Expected Behavior

I expect to be able to invoke authorizer lambdas correctly between restarts of localstack, in the same way they can be successfully invoked after having been created if localstack is not restarted.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I use the following docker compose file to run localstack:
```
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "443:443"
    networks:
      - localnet
    env_file:
      - localstack-secrets.env
    environment:
      - EAGER_SERVICE_LOADING=1
      - LOCALSTACK_SERVICES=apigateway,lambda

      - LAMBDA_DOCKER_NETWORK=localnet
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_EXECUTOR=docker-reuse
      - HOSTNAME_FROM_LAMBDA=localstack

      - PERSISTENCE=1
      - DEBUG=1

    volumes:
      - "./persist:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
    localnet:
        driver: bridge
        external: false
        name: localnet
```

Note that `localstack-secrets.env` has the key for a pro account.
Also note the mode I am using to execute the lambdas.
Finally, the directory mounted to `/var/lib/localstack` is initially non-existent (to make sure there is no previous persisted state).

I bring everything up with `docker compose up`.

Then I create two lambdas and attach them to an HTTP API in apigatewayv2 (one as authorizer and one as lambda proxy), using this script.
The script calls the API at the end.

```
#!/bin/bash

echo "creating Lambdas"
mkdir -p authf
echo 'exports.handler = async (event, context) => { return { "isAuthorized": true } }' > authf/index.js
zip -j authf.zip authf/index.js
awslocal --region=eu-west-3 lambda create-function --function-name=authf --role=whatever --zip-file fileb://./authf.zip --runtime=nodejs14.x --handler=index.handler

mkdir -p runf
echo 'exports.handler = async (event, context) => { return { "statusCode": 200, body: { foo: "bar" } } }' > runf/index.js
zip -j runf.zip runf/index.js
awslocal --region=eu-west-3 lambda create-function --function-name=runf --role=whatever --zip-file fileb://./runf.zip --runtime=nodejs14.x --handler=index.handler

API=$(awslocal apigatewayv2 create-api --name=test --protocol-type=http | jq -r '.ApiId')
echo "created API: ${API}"

AUTH=$(awslocal apigatewayv2 create-authorizer --api-id=${API} --authorizer-type=REQUEST --identity-source=$request.header.Authorization --name=lambdaauth --enable-simple-response --authorizer-uri=arn:aws:lambda:eu-west-3:000000000000:function:authf | jq -r '.AuthorizerId')
echo "created Authorizer: ${AUTH}"

INTEGR=$(awslocal apigatewayv2 create-integration --api-id=${API} --integration-type=AWS_PROXY --connection-type=INTERNET --integration-method=GET --integration-uri=arn:aws:lambda:eu-west-3:000000000000:function:runf | jq -r '.IntegrationId')
echo "created Integration: ${INTEGR}"

ROUTE=$(awslocal apigatewayv2 create-route --api-id=${API} --route-key='GET /foo' --authorization-type=CUSTOM --authorizer-id=${AUTH} --target=integrations/${INTEGR} | jq -r '.RouteId')
echo "created Route: ${ROUTE}"

ENDP=$(awslocal apigatewayv2 get-api --api-id=${API} | jq -r '.ApiEndpoint')
echo "calling API: ${ENDP}"
set +x
curl ${ENDP}/foo
```

The first time I call the API, everything goes well: the authorizer gets called, and the lambda proxy as well.

Then I stop localstack with `CTRL+C` on the localstack process and restart it with `docker compose up` again.
Then I call the API again, and get an error:
```
❯ curl 6bb66790.execute-api.localhost.localstack.cloud:4566/foo
<Response 174 bytes [409 CONFLICT]>%  
```

The log from localstack is as follows:
```
localstack  | Waiting for all LocalStack services to be ready
localstack  | 2022-08-17 13:19:17,672 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack  | 2022-08-17 13:19:17,675 INFO supervisord started with pid 14
localstack  | 2022-08-17 13:19:18,680 INFO spawned: 'infra' with pid 19
localstack  | 2022-08-17 13:19:19,683 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack  | 
localstack  | LocalStack version: 1.0.5.dev
localstack  | LocalStack Docker container id: 2c68796b7265
localstack  | LocalStack build date: 2022-08-16
localstack  | LocalStack build git hash: 7e3045dc
localstack  | 
localstack  | 2022-08-17T13:19:20.425 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='_patch_botocore_json_parser', value='localstack.aws.client:_patch_botocore_json_parser', group='localstack.hooks.on_infra_start')
localstack  | 2022-08-17T13:19:20.429 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='patch_get_account_id', value='localstack.aws.accounts:patch_get_account_id', group='localstack.hooks.on_infra_start')
localstack  | 2022-08-17T13:19:20.429 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_partition_adjusting_proxy_listener', value='localstack.plugins:register_partition_adjusting_proxy_listener', group='localstack.hooks.on_infra_start')
localstack  | 2022-08-17T13:19:20.429 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='add_aws_request_logger', value='localstack_ext.analytics.plugins:add_aws_request_logger', group='localstack.hooks.on_infra_start')
localstack  | 2022-08-17T13:19:20.430 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='add_custom_edge_routes', value='localstack_ext.plugins:add_custom_edge_routes', group='localstack.hooks.on_infra_start')
localstack  | 2022-08-17T13:19:20.434 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='add_iam_enforcement_listener', value='localstack_ext.services.iam.plugins:add_iam_enforcement_listener', group='localstack.hooks.on_infra_start')
localstack  | 2022-08-17T13:19:20.435 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='add_legacy_iam_enforcement_listener', value='localstack_ext.services.iam.plugins:add_legacy_iam_enforcement_listener', group='localstack.hooks.on_infra_start')
localstack  | 2022-08-17T13:19:20.435 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='extensions_on_infra_start', value='localstack_ext.extensions.plugins:extensions_on_infra_start', group='localstack.hooks.on_infra_start')
localstack  | 2022-08-17T13:19:20.437 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='patch_account_id_resolver', value='localstack_ext.plugins:patch_account_id_resolver', group='localstack.hooks.on_infra_start')
localstack  | 2022-08-17T13:19:20.437 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='patch_get_account_id_from_access_key_id', value='localstack_ext.plugins:patch_get_account_id_from_access_key_id', group='localstack.hooks.on_infra_start')
localstack  | 2022-08-17T13:19:20.437 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='patch_moto_backend_dict', value='localstack_ext.plugins:patch_moto_backend_dict', group='localstack.hooks.on_infra_start')
localstack  | 2022-08-17T13:19:20.437 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_pods_api', value='localstack_ext.persistence.plugins:register_pods_api', group='localstack.hooks.on_infra_start')
localstack  | 2022-08-17T13:19:20.438 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_state_serializer_handlers', value='localstack_ext.persistence.plugins:register_state_serializer_handlers', group='localstack.hooks.on_infra_start')
localstack  | 2022-08-17T13:19:20.438 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='setup_pro_infra', value='localstack_ext.plugins:setup_pro_infra', group='localstack.hooks.on_infra_start')
localstack  | 2022-08-17T13:19:20.439 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._patch_botocore_json_parser = <function _patch_botocore_json_parser at 0x7f6bfde6ae60>)
localstack  | 2022-08-17T13:19:20.439 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:_patch_botocore_json_parser
localstack  | 2022-08-17T13:19:20.440 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.patch_get_account_id = <function patch_get_account_id at 0x7f6bfe6c9c60>)
localstack  | 2022-08-17T13:19:20.440 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:patch_get_account_id
localstack  | 2022-08-17T13:19:20.440 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_partition_adjusting_proxy_listener = <function register_partition_adjusting_proxy_listener at 0x7f6bfde6b370>)
localstack  | 2022-08-17T13:19:20.440 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:register_partition_adjusting_proxy_listener is disabled
localstack  | 2022-08-17T13:19:20.440 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.add_aws_request_logger = <function add_aws_request_logger at 0x7f6bfde6b6d0>)
localstack  | 2022-08-17T13:19:20.440 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:add_aws_request_logger
localstack  | 2022-08-17T13:19:20.441 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.add_custom_edge_routes = <function add_custom_edge_routes at 0x7f6bfdeabf40>)
localstack  | 2022-08-17T13:19:20.441 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:add_custom_edge_routes
localstack  | 2022-08-17T13:19:20.441 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.add_iam_enforcement_listener = <function add_iam_enforcement_listener at 0x7f6bfdebd1b0>)
localstack  | 2022-08-17T13:19:20.441 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:add_iam_enforcement_listener
localstack  | 2022-08-17T13:19:20.441 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.add_legacy_iam_enforcement_listener = <function add_legacy_iam_enforcement_listener at 0x7f6bfdebd000>)
localstack  | 2022-08-17T13:19:20.441 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:add_legacy_iam_enforcement_listener is disabled
localstack  | 2022-08-17T13:19:20.441 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.extensions_on_infra_start = <function extensions_on_infra_start at 0x7f6bfdebd510>)
localstack  | 2022-08-17T13:19:20.442 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:extensions_on_infra_start
localstack  | 2022-08-17T13:19:20.442 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.patch_account_id_resolver = <function patch_account_id_resolver at 0x7f6bfdebc1f0>)
localstack  | 2022-08-17T13:19:20.442 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:patch_account_id_resolver is disabled
localstack  | 2022-08-17T13:19:20.442 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.patch_get_account_id_from_access_key_id = <function patch_get_account_id_from_access_key_id at 0x7f6bfdebc310>)
localstack  | 2022-08-17T13:19:20.442 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:patch_get_account_id_from_access_key_id is disabled
localstack  | 2022-08-17T13:19:20.443 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.patch_moto_backend_dict = <function patch_moto_backend_dict at 0x7f6bfdebc0d0>)
localstack  | 2022-08-17T13:19:20.443 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:patch_moto_backend_dict is disabled
localstack  | 2022-08-17T13:19:20.443 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_pods_api = <function register_pods_api at 0x7f6bfdebdbd0>)
localstack  | 2022-08-17T13:19:20.443 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:register_pods_api
localstack  | 2022-08-17T13:19:20.443 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_state_serializer_handlers = <function register_state_serializer_handlers at 0x7f6bfdebdcf0>)
localstack  | 2022-08-17T13:19:20.443 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:register_state_serializer_handlers
localstack  | 2022-08-17T13:19:20.443 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.setup_pro_infra = <function setup_pro_infra at 0x7f6bfdebc8b0>)
localstack  | 2022-08-17T13:19:20.443 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:setup_pro_infra
localstack  | 2022-08-17T13:19:20.445 DEBUG --- [  MainThread] l.bootstrap.install        : Using cached SSL certificate (less than 6hrs since last update).
localstack  | 2022-08-17T13:19:21.097  INFO --- [  MainThread] l.bootstrap.licensing      : Successfully activated API key
localstack  | 2022-08-17T13:19:21.210 DEBUG --- [  MainThread] l.a.p.service_router       : loading service catalog index cache file /var/lib/localstack/cache/service-catalog-1_0_5_dev-1_27_51.pickle
localstack  | 2022-08-17T13:19:21.230 DEBUG --- [  MainThread] localstack.utils.run       : Executing command: whoami
localstack  | 2022-08-17T13:19:21.239 DEBUG --- [  MainThread] localstack.utils.run       : Executing command:  python -c "import sys; f=open(sys.argv[1]).read(); open(sys.argv[1], 'w').write('\n' + f)" /etc/resolv.conf
localstack  | 2022-08-17T13:19:21.270 DEBUG --- [  MainThread] localstack.utils.run       : Executing command:  python -c "import sys; f=open(sys.argv[1]).read(); open(sys.argv[1], 'w').write('nameserver 0.0.0.0\n' + f)" /etc/resolv.conf
localstack  | 2022-08-17T13:19:21.293 DEBUG --- [  MainThread] localstack.utils.run       : Executing command:  python -c "import sys; f=open(sys.argv[1]).read(); open(sys.argv[1], 'w').write('# The following line is required by LocalStack\n' + f)" /etc/resolv.conf
localstack  | Waiting for all LocalStack services to be ready
localstack  | 2022-08-17T13:19:25.457  WARN --- [  MainThread] l.services.internal        : Enabling diagnose endpoint, please be aware that this can expose sensitive information via your network.
localstack  | 2022-08-17T13:19:25.948  INFO --- [  MainThread] l.extensions.platform      : loaded 0 extensions
localstack  | 2022-08-17T13:19:25.949 DEBUG --- [  MainThread] l.extensions.platform      : calling extensions on_platform_start
localstack  | 2022-08-17T13:19:25.949 DEBUG --- [  MainThread] l.extensions.platform      : calling extensions update_gateway_routes
localstack  | 2022-08-17T13:19:25.949 DEBUG --- [  MainThread] l.extensions.platform      : calling extensions update_request_handlers
localstack  | 2022-08-17T13:19:25.949 DEBUG --- [  MainThread] l.extensions.platform      : calling extensions update_response_handlers
localstack  | 2022-08-17T13:19:25.949  INFO --- [  MainThread] l.u.aws.metadata_service   : Starting AWS instance metadata service on port 80
localstack  | 2022-08-17T13:19:25.974  INFO --- [  MainThread] botocore.credentials       : Found credentials in environment variables.
localstack  | Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
localstack  | 2022-08-17T13:19:25.987 DEBUG --- [   Thread-10] l.bootstrap.install        : Using cached SSL certificate (less than 6hrs since last update).
localstack  | 2022-08-17T13:19:25.989  WARN --- [   Thread-13] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
localstack  | 2022-08-17T13:19:25.989  WARN --- [   Thread-13] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
localstack  | 2022-08-17T13:19:25.990 DEBUG --- [   Thread-10] l.bootstrap.install        : Using cached SSL certificate (less than 6hrs since last update).
localstack  | 2022-08-17T13:19:25.992  INFO --- [   Thread-13] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack  | 2022-08-17T13:19:25.992  INFO --- [   Thread-13] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack  | 2022-08-17T13:19:25.993  WARN --- [   Thread-15] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
localstack  | 2022-08-17T13:19:25.993  WARN --- [   Thread-15] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
localstack  | 2022-08-17T13:19:25.994  INFO --- [   Thread-15] hypercorn.error            : Running on https://0.0.0.0:443 (CTRL + C to quit)
localstack  | 2022-08-17T13:19:25.994  INFO --- [   Thread-15] hypercorn.error            : Running on https://0.0.0.0:443 (CTRL + C to quit)
localstack  | 2022-08-17T13:19:26.531 DEBUG --- [  MainThread] l.s.apigateway.router_asf  : Registering parameterized API gateway routes.
localstack  | 2022-08-17T13:19:27.757 DEBUG --- [   Thread-21] l.s.a.lambda_executors     : Cleaning up docker-reuse executor. Set arn: arn:aws:lambda:eu-west-3:000000000000:function:authf
localstack  | 2022-08-17T13:19:28.015  INFO --- [   Thread-20] botocore.credentials       : Found credentials in environment variables.
localstack  | 2022-08-17T13:19:28.037 DEBUG --- [uest_thread)] l.services.dns_server      : Determined fallback dns: 127.0.0.11
localstack  | 2022-08-17T13:19:28.260  INFO --- [  MainThread] l.s.awslambda.persistence  : Unable to load user code for Lambda function arn:aws:lambda:eu-west-3:000000000000:function:authf: 'arn:aws:lambda:eu-west-3:000000000000:function:authf'
localstack  | 2022-08-17T13:19:28.270 DEBUG --- [   Thread-28] l.s.a.lambda_executors     : Cleaning up docker-reuse executor. Set arn: arn:aws:lambda:eu-west-3:000000000000:function:runf
localstack  | 2022-08-17T13:19:28.776  INFO --- [  MainThread] l.s.awslambda.persistence  : Unable to load user code for Lambda function arn:aws:lambda:eu-west-3:000000000000:function:runf: 'arn:aws:lambda:eu-west-3:000000000000:function:runf'
localstack  | 2022-08-17T13:19:28.776  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "_load_service_plugin" took 2127.96ms
localstack  | 2022-08-17T13:19:28.776  INFO --- [  MainThread] localstack.services.infra  : Starting mock Lambda service on http ports 443/4566 ...
localstack  | 2022-08-17T13:19:28.778 DEBUG --- [   Thread-51] l.s.a.lambda_executors     : Cleaning up docker-reuse executor. Set arn: None
localstack  | 2022-08-17T13:19:28.778 DEBUG --- [   Thread-51] l.s.a.lambda_executors     : Destroying all running docker-reuse lambda containers
localstack  | 2022-08-17T13:19:28.780 DEBUG --- [   Thread-51] l.s.a.lambda_executors     : Getting all lambda containers names.
localstack  | 2022-08-17T13:19:28.780 DEBUG --- [   Thread-51] l.u.c.docker_sdk_client    : Listing containers with filters: {'name': 'localstack_lambda_*'}
localstack  | 2022-08-17T13:19:28.784 DEBUG --- [   Thread-51] l.s.a.lambda_executors     : Removing 0 containers.
localstack  | 2022-08-17T13:19:28.786 DEBUG --- [   Thread-51] l.s.a.lambda_executors     : Checking if there are idle containers ...
localstack  | 2022-08-17T13:19:28.787 DEBUG --- [   Thread-51] l.u.c.container_client     : Getting networks for container: localstack
localstack  | 2022-08-17T13:19:29.306  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "require" took 2658.52ms
localstack  | 2022-08-17T13:19:29.910  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "_load_service_plugin" took 603.33ms
localstack  | 2022-08-17T13:19:29.912  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "require" took 605.30ms
localstack  | 2022-08-17T13:19:30.286 DEBUG --- [  MainThread] l.s.apigateway.router_asf  : Skipped API gateway route registration (routes already registered).
localstack  | 2022-08-17T13:19:30.288  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "preload_services" took 4005.30ms
localstack  | 2022-08-17T13:19:30.288 DEBUG --- [  MainThread] l.utils.persistence        : saving startup info StartupInfo(timestamp='2022-08-17T13:19:30.288383', localstack_version='1.0.5.dev', localstack_ext_version='1.0.5.dev20220816135523', pro_activated=True)
localstack  | Ready.
localstack  | 2022-08-17T13:19:30.299 DEBUG --- [  MainThread] l.extensions.platform      : calling extensions on_platform_ready
localstack  | 2022-08-17T13:19:32.189 DEBUG --- [   asgi_gw_0] l.s.apigateway.invocations : No matching stage (None) for invocation path (falling back to $default stage): /foo
localstack  | 2022-08-17T13:19:32.189 DEBUG --- [   asgi_gw_0] l.s.apigateway.authorizers : Processing API V2 invocation
localstack  | 2022-08-17T13:19:32.190 DEBUG --- [   asgi_gw_0] l.s.apigateway.authorizers : Running authorization for request to API Gateway ID 6bb66790 - GET /foo
localstack  | 2022-08-17T13:19:32.835 DEBUG --- [   asgi_gw_0] l.s.awslambda.lambda_utils : The operation cannot be performed at this time. The function is currently in the following state: Failed
localstack  | 2022-08-17T13:19:32.839 DEBUG --- [   asgi_gw_0] l.s.apigateway.authorizers : Authorization failed: <Response 174 bytes [409 CONFLICT]> - Traceback (most recent call last):
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 272, in is_request_authorized
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 266, in is_request_authorized
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 162, in authorize
localstack  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 548, in run_lambda
localstack  |     raise ClientError(result)
localstack  | localstack.services.awslambda.lambda_utils.ClientError: <Response 174 bytes [409 CONFLICT]>
localstack  | 
localstack  | 2022-08-17T13:19:32.840  INFO --- [   asgi_gw_0] localstack.request.http    : GET /foo => 500
```

### Environment

```markdown
Running with the following version (from localstack/localstack:latest tag in docker hub)


LocalStack version: 1.0.5.dev
LocalStack Docker container id: b1029c89656c
LocalStack build date: 2022-08-16
LocalStack build git hash: 7e3045dc
```

- OS: Ubuntu 20.04
- Docker: 20.10.17, build 100c701
- Docker compose: v2.6.0
```


### Anything else?

_No response_

**Comment by HarshCasper** [comment]
Hi @nerochiaro — I gave your sample a run and can confirm that this is a bug. However, after restarting LocalStack via my `docker-compose` configuration, I saw that the requested URL was not found, because apparently after a restart it had a different URL altogether. I used `awslocal apigatewayv2 get-apis` and found the API endpoint that was persisted since the last run and I can confirm that it was working as expected. 

Can you please confirm this behavior by updating your LocalStack setup and giving this a run? We also have a `localstack-pro` image now that you can use for persistence (which is a Pro feature)!
