### ISSUE TITLE
bug: <APIGW Authorizers return Internal server error>

### ISSUE THREAD

**Issue by Guy7B** [localstack/localstack#6705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have the pro version, and I'm trying to use ApiGWV1 Authorizers in localstack:1.0.4.
Unfortunately, it doesn’t work, and I wasted hours trying to figure out what’s the issue.

I am getting 500 internal server errors when I am trying to reach one of my endpoints that is protected by an authorizer.
I can't see the lambda authorizer invoked.

### Expected Behavior

The authorizer should return the policy and then the protected lambda will be invoked.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I have created the lambda authorizer with terraform:
```
provider "archive" {}

data "archive_file" "zip" {
  type        = "zip"
  source_file = "tests_authorizer.py"
  output_path = "tests_authorizer.zip"
}

data "aws_iam_policy_document" "policy" {
  statement {
    sid    = ""
    effect = "Allow"

    principals {
      identifiers = ["lambda.amazonaws.com"]
      type        = "Service"
    }

    actions = ["sts:AssumeRole"]
  }
}

resource "aws_iam_role" "iam_for_lambda" {
  name               = "iam_for_lambda"
  assume_role_policy = data.aws_iam_policy_document.policy.json
}

resource "aws_lambda_function" "lambda" {
  function_name = "authorizer"

  filename         = data.archive_file.zip.output_path
  source_code_hash = data.archive_file.zip.output_base64sha256

  role    = aws_iam_role.iam_for_lambda.arn
  handler = "tests_authorizer.authorizer"
  runtime = "python3.8"
}

```

### Environment

```markdown
- OS: macOS Monterey 12.4
- LocalStack: 1.0.4 - errors for 0.14.3
```

### Anything else?

The log message:
```
- [   asgi_gw_8] l.s.a.lambda_executors     : writing log to file '/var/lib/localstack/tmp/lambda_70jxueun.log'

2022-08-19T14:07:28.419  INFO --- [   asgi_gw_8] l.s.awslambda.lambda_api   : Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:authorizer: Lambda process returned with error. Result: . Output:

 Traceback (most recent call last):

  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status

    response.raise_for_status()

  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/models.py", line 943, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.41/containers/ab6509bad8d8449ba30399967415956978e426a7179af7663c74b4ce9305f1cf/start


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 479, in start_container

    container.start()

  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/models/containers.py", line 404, in start

    return self.client.api.start(self.id, **kwargs)

  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped

    return f(self, resource_id, *args, **kwargs)

  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/container.py", line 1111, in start

    self._raise_for_status(res)

  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status

    raise create_api_error_from_http_exception(e)

  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception

    raise cls(e, response=response, explanation=explanation)

docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/containers/ab6509bad8d8449ba30399967415956978e426a7179af7663c74b4ce9305f1cf/start: Internal Server Error ("driver failed programming external connectivity on endpoint cbrix-ops-mocks_localstack_1_lambda_arn_aws_lambda_us-east-1_000000000000_function_authorizer (a50a5154cd1882209276317ecef5a2b8e9bebb37d8c93f8ff6151dc3f8947f09): Bind for 0.0.0.0:5678 failed: port is already allocated")


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 638, in run_lambda_executor

    result, log_output = self.execute_in_container(

  File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy

    return new(target, *args, **kwargs)

  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/awslambda/lambda_launcher.py.enc", line 76, in A

  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 818, in execute_in_container

    container_info = self.prime_docker_container(

  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 952, in prime_docker_container

    DOCKER_CLIENT.start_container(container_name)

  File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 484, in start_container

    raise ContainerException() from e

localstack.utils.container_utils.container_client.ContainerException


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 551, in run_lambda

    result = LAMBDA_EXECUTOR.execute(

  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 465, in execute

    return do_execute()

  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 455, in do_execute

    return _run(func_arn=func_arn)

  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 167, in wrapped

    raise e

  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 163, in wrapped

    result = func(*args, **kwargs)

  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 442, in _run

    raise e

  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 438, in _run

    result = self._execute(lambda_function, inv_context)

  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 902, in _execute

    return super(LambdaExecutorReuseContainers, self)._execute(func_arn, *args, **kwargs)

  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 761, in _execute

    result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)

  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 369, in run_lambda_executor

  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 683, in run_lambda_executor

    raise InvocationException(

localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: . Output:



2022-08-19T14:07:28.420  INFO --- [   asgi_gw_8] l.s.apigateway.authorizers : Received authorizer result: <Response 1822 bytes [500 INTERNAL SERVER ERROR]>

2022-08-19T14:07:28.421  INFO --- [   asgi_gw_8] localstack.request.http    : GET /restapis/1e8wungy6n/local/_user_request_/template/items => 500
```

**Comment by calvernaz** [comment]
Hi @Guy7B, thanks for reporting this. I couldn't reproduce it, and I created a [sample](https://github.com/localstack/troubleshooting-issues/tree/main/issue_6707) that I'd like you to try and see if the same happens.

Also, in case it's an issue with the lambda executors, have a look at this [page](https://docs.localstack.cloud/localstack/lambda-executors/) and try other executors and check if you have a different behaviour.
