### ISSUE TITLE
bug: KMS service cannot persist state

### ISSUE THREAD

**Issue by map34** [localstack/localstack#6753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever I try to create a new KMS key using docker-compose, I encounter this error: 
```
test-localstack-1  | 2022-08-24T22:23:48.016  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS kms.CreateKey => 200
test-localstack-1  | 2022-08-24T22:23:48.028 ERROR --- [   asgi_gw_1] l.utils.persistence        : Unable to persist backend state to path /var/lib/localstack/state/api_states/000000000000/kms/us-gov-west-1/backend_state
test-localstack-1  | Traceback (most recent call last):
test-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/persistence.py.enc", line 71, in persist_state
test-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/persistence.py.enc", line 59, in persist_object
test-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/persistence/utils.py.enc", line 12, in marshall_object
test-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/dill/_dill.py", line 265, in dumps
test-localstack-1  |     dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)
test-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/dill/_dill.py", line 259, in dump
test-localstack-1  |     Pickler(file, protocol, **_kwds).dump(obj)
test-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/dill/_dill.py", line 446, in dump
test-localstack-1  |     StockPickler.dump(self, obj)
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 487, in dump
test-localstack-1  |     self.save(obj)
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 603, in save
test-localstack-1  |     self.save_reduce(obj=obj, *rv)
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 717, in save_reduce
test-localstack-1  |     save(state)
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 560, in save
test-localstack-1  |     f(self, obj)  # Call unbound method with explicit self
test-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/dill/_dill.py", line 933, in save_module_dict
test-localstack-1  |     StockPickler.save_dict(pickler, obj)
test-localstack-1  |   File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
test-localstack-1  |     return new(target, *args, **kwargs)
test-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/persistence.py.enc", line 81, in save_dict
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 972, in save_dict
test-localstack-1  |     self._batch_setitems(obj.items())
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 998, in _batch_setitems
test-localstack-1  |     save(v)
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 560, in save
test-localstack-1  |     f(self, obj)  # Call unbound method with explicit self
test-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/dill/_dill.py", line 933, in save_module_dict
test-localstack-1  |     StockPickler.save_dict(pickler, obj)
test-localstack-1  |   File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
test-localstack-1  |     return new(target, *args, **kwargs)
test-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/persistence.py.enc", line 81, in save_dict
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 972, in save_dict
test-localstack-1  |     self._batch_setitems(obj.items())
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 1003, in _batch_setitems
test-localstack-1  |     save(v)
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 603, in save
test-localstack-1  |     self.save_reduce(obj=obj, *rv)
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 717, in save_reduce
test-localstack-1  |     save(state)
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 560, in save
test-localstack-1  |     f(self, obj)  # Call unbound method with explicit self
test-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/dill/_dill.py", line 933, in save_module_dict
test-localstack-1  |     StockPickler.save_dict(pickler, obj)
test-localstack-1  |   File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
test-localstack-1  |     return new(target, *args, **kwargs)
test-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/persistence.py.enc", line 81, in save_dict
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 972, in save_dict
test-localstack-1  |     self._batch_setitems(obj.items())
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 998, in _batch_setitems
test-localstack-1  |     save(v)
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 603, in save
test-localstack-1  |     self.save_reduce(obj=obj, *rv)
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 717, in save_reduce
test-localstack-1  |     save(state)
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 560, in save
test-localstack-1  |     f(self, obj)  # Call unbound method with explicit self
test-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/dill/_dill.py", line 933, in save_module_dict
test-localstack-1  |     StockPickler.save_dict(pickler, obj)
test-localstack-1  |   File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
test-localstack-1  |     return new(target, *args, **kwargs)
test-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/persistence.py.enc", line 81, in save_dict
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 972, in save_dict
test-localstack-1  |     self._batch_setitems(obj.items())
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 998, in _batch_setitems
test-localstack-1  |     save(v)
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 603, in save
test-localstack-1  |     self.save_reduce(obj=obj, *rv)
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 717, in save_reduce
test-localstack-1  |     save(state)
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 560, in save
test-localstack-1  |     f(self, obj)  # Call unbound method with explicit self
test-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/dill/_dill.py", line 933, in save_module_dict
test-localstack-1  |     StockPickler.save_dict(pickler, obj)
test-localstack-1  |   File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
test-localstack-1  |     return new(target, *args, **kwargs)
test-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/persistence.py.enc", line 81, in save_dict
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 972, in save_dict
test-localstack-1  |     self._batch_setitems(obj.items())
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 998, in _batch_setitems
test-localstack-1  |     save(v)
test-localstack-1  |   File "/usr/local/lib/python3.10/pickle.py", line 578, in save
test-localstack-1  |     rv = reduce(self.proto)
test-localstack-1  | TypeError: cannot pickle '_cffi_backend.FFI' object
```

This bug causes the persistence process not to work. Therefore, whenever we restart the localstack container, the references to the previously created KMS keys are missing.

### Expected Behavior

Localstack should persist state successfully when I create a KMS key

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

- Use the following docker-compose.yml
```
version: '3.9'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - SERVICES=kms,cognito
      - DEFAULT_REGION=us-gov-west-1
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:4566,https://localhost.localstack.cloud:4566
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
- Start localstack:
```
LOCALSTACK_API_KEY=<your_api_key> PERSISTENCE=1 docker-compose -p test up localstack
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

`awslocal kms create-key`

### Environment

```markdown
- OS: MacOS Monterey
- LocalStack version: 1.0.5.dev
- LocalStack build date: 2022-08-24
- LocalStack build git hash: 4c6166fc
- Docker Engine version: 20.10.17
- Docker Compose version: v2.6.1
```

**Comment by whummer** [comment]
Thanks for reporting @map34 , this should be (hopefully) fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

**Comment by whummer** [comment]
Closing this issue as resolved - @map34  please let us know if the problem persists with the `latest` Docker image.. Thanks
