### ISSUE TITLE
bug: got an error while running localstack as a container in CI

### ISSUE THREAD

**Issue by okkez** [localstack/localstack#6797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I got the following error while running localstack as a container.

```
Error starting infrastructure: Could not get list of releases from https://api.github.com/repos/etspaceman/kinesis-mock/releases/tags/0.2.5: {"message":"API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 419, in start_infra
    thread = do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/code/localstack/localstack/services/infra.py", line 520, in do_start_infra
    prepare_installation()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 77, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 474, in prepare_installation
    install.install_components(apis)
  File "/opt/code/localstack/localstack/services/install.py", line 750, in install_components
    parallelize(install_component, names)
  File "/opt/code/localstack/localstack/utils/threads.py", line 135, in parallelize
    return pool.map(func, arr)
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/opt/code/localstack/localstack/services/install.py", line 746, in install_component
    installer()
  File "/opt/code/localstack/localstack/services/install.py", line 364, in install_kinesis
    install_kinesis_mock(bin_path)
  File "/opt/code/localstack/localstack/services/install.py", line 427, in install_kinesis_mock
    raise ValueError(
ValueError: Could not get list of releases from https://api.github.com/repos/etspaceman/kinesis-mock/releases/tags/0.2.5: {"message":"API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```
In fact, I run many ECS tasks and run a localstack container within each ECS task for test isolation. I run 100 or more tasks at once.

### Expected Behavior

I expect followings:
- can skip installing all extra components from the internet
- can set GitHub access token via an environment variable and use it as Authorization header if set

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Access GitHub API and exceed rate limit and then run localstack container.
Or just run many localstack containers.

```
docker run localstack/localstack
```

### Environment

```markdown
- OS: AmazonLinux2
- LocalStack: 1.0.4
```

**Comment by thrau** [comment]
hi @okkez, thanks for reporting. kinesis-mock comes pre-built with the localstack image. if you aren't using any special type of configuration, or kinesalite, then this control path that's causing the errors shouldn't be called at all.

could you please share exactly how you are starting localstack, including all the configuration? thanks!

**Comment by okkez** [comment]
I executed following script to reproduce this issue.

```ruby
require "aws-sdk-ecs"

ecs = Aws::ECS::Client.new

if false # change this to register task definition
  ecs.register_task_definition(
    family: "okkez_test",
    container_definitions: [
      {
        name: "localstack",
        image: "localstack/localstack:1.0.4",
        cpu: 0,
        port_mappings: [],
        essential: true,
        environment: [],
        mount_points: [],
        volumes_from: [],
        log_configuration: {
          log_driver: "awslogs",
          options: {
            "awslogs-group": "/ecs/localstack",
            "awslogs-region": "ap-northeast-1",
            "awslogs-stream-prefix": "localstack"
          }
        }
      }
    ],
    task_role_arn: "arn:aws:iam::xxxxxxxxxxxx:role/TestTask",
    execution_role_arn: "arn:aws:iam::xxxxxxxxxxx:role/ecsTaskExecutionRole",
    network_mode: "awsvpc",
    volumes: [],
    placement_constraints: [],
    requires_compatibilities: ["FARGATE"],
    cpu: "2048",
    memory: "16384",
    tags: []
  )
end

N = 1
N.times do
  ecs.run_task(
    cluster: "localstack-test",
    task_definition: "arn:aws:ecs:ap-northeast-1:xxxxxxxxxxxxxx:task-definition/localstack_test",
    count: 1,
    enable_execute_command: true,
    launch_type: "FARGATE",
    network_configuration: {
      awsvpc_configuration: {
        subnets: ["subnet-a", "subnet-b", "subnet-c"],
        assign_public_ip: "DISABLED",
      }
    },
  )
  print "."
end

p :done
```

Default log here: This log reports localstack downloads kinesis-mock from github.com.

```console
Waiting for all LocalStack services to be ready
2022-09-02 04:21:20,595 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-09-02 04:21:20,596 INFO supervisord started with pid 17
2022-09-02 04:21:21,598 INFO spawned: 'infra' with pid 35
2022-09-02 04:21:22,600 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
LocalStack version: 1.0.4
LocalStack build date: 2022-08-08
LocalStack build git hash: 7a803308
2022-09-02T04:21:22.826  INFO --- [d-2 (worker)] l.services.install         : Downloading and installing local KMS server. This may take some time.
2022-09-02T04:21:22.828  INFO --- [d-7 (worker)] l.services.install         : Downloading and installing local DynamoDB server. This may take some time.
2022-09-02T04:21:22.829  INFO --- [d-6 (worker)] l.services.install         : Downloading and installing local Installing lambda runtime server. This may take some time.
2022-09-02T04:21:22.832  WARN --- [d-5 (worker)] l.services.install         : Docker not available - skipping installation of StepFunctions dependency
2022-09-02T04:21:23.099  INFO --- [d-3 (worker)] l.services.install         : downloading kinesis-mock binary from https://github.com/etspaceman/kinesis-mock/releases/download/0.2.5/kinesis-mock-linux-amd64-static
2022-09-02T04:21:26.391  INFO --- [  MainThread] l.services.install         : Downloading and installing LocalStack Java libraries. This may take some time.
Waiting for all LocalStack services to be ready
2022-09-02T04:21:28.126  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "prepare_installation" took 5311.03ms
2022-09-02T04:21:28.211  WARN --- [  Thread-110] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2022-09-02T04:21:28.211  WARN --- [  Thread-110] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2022-09-02T04:21:28.212  INFO --- [  Thread-110] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2022-09-02T04:21:28.212  INFO --- [  Thread-110] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
Ready.
```

Debug log with `| grep kinesis-mock` here:

```console
2022-09-02T04:10:41.506 DEBUG --- [d-2 (worker)] l.services.install         : getting kinesis-mock for linux x86_64
2022-09-02T04:10:41.772  INFO --- [d-2 (worker)] l.services.install         : downloading kinesis-mock binary from https://github.com/etspaceman/kinesis-mock/releases/download/0.2.5/kinesis-mock-linux-amd64-static
2022-09-02T04:10:42.454 DEBUG --- [d-2 (worker)] localstack.utils.http      : Starting download from https://github.com/etspaceman/kinesis-mock/releases/download/0.2.5/kinesis-mock-linux-amd64-static to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static (19823796 bytes)
2022-09-02T04:10:42.475 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 1048576) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:42.623 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 2097152) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:42.782 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 3145728) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:42.944 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 4194304) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:43.122 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 5242880) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:43.442 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 6291456) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:43.764 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 7340032) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:44.085 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 8388608) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:44.426 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 9437184) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:44.747 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 10485760) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:44.909 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 11534336) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:45.230 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 12582912) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:45.568 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 13631488) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:45.890 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 14680064) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:46.052 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 15728640) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:46.373 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 16777216) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:46.701 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 17825792) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:47.022 DEBUG --- [d-2 (worker)] localstack.utils.http      : Written 1048576 bytes (total 18874368) to /opt/code/localstack/.filesystem/usr/lib/localstack/kinesis-mock/kinesis-mock-linux-amd64-static
2022-09-02T04:10:47.220 DEBUG --- [d-2 (worker)] localstack.utils.http      : Done downloading https://github.com/etspaceman/kinesis-mock/releases/download/0.2.5/kinesis-mock-linux-amd64-static, response code 200, total bytes 19823796
```

**Comment by okkez** [comment]
On ECS, `in_docker` method returns `False` and calls `Directories.for_host`.
https://github.com/localstack/localstack/blob/4b221c70287a95a254e2466a4441210e6cc8ffa5/localstack/config.py#L279
https://github.com/localstack/localstack/blob/4b221c70287a95a254e2466a4441210e6cc8ffa5/localstack/config.py#L1034

But we can set `OVERRIDE_IN_DOCKER` environment variable to assume running localstack as docker container.
https://github.com/localstack/localstack/blob/4b221c70287a95a254e2466a4441210e6cc8ffa5/localstack/config.py#L284

Also, I can find it here: https://docs.localstack.cloud/localstack/configuration/#miscellaneous

**Comment by greg-md** [comment]
So what needs to be done to resolve this? To add `OVERRIDE_IN_DOCKER=true` in docker-compose file? or in the CI environment?

**Comment by pmcgaley** [comment]
Hi @thrau 

> kinesis-mock comes pre-built with the localstack image.

Is this still the case? I've had the same error occur with the 1.2.0 docker image. When I look in the container, `/usr/lib/localstack/` does not contain kinesis-mock, whereas it does on 1.1.0.

It seems as a result 1.2.0 attempts to download kinesis-mock from github and fails with a rate limit error.

I've worked around it locally by pinning to 1.1.0 for now, but it would be good to resolve properly.

**Comment by barryoneill** [comment]
Thank you so much @pmcgaley - I just got caught out by this, lost the last hour before I saw the rate limit messages inside the CI container, and then your message.

**Comment by Fatezhang** [comment]
Get same error when start localstack in the `docker-compose.yml`:

```
localstack.packages.api.PackageException: Could not get list of releases from https://api.github.com/repos/etspaceman/kinesis-mock/releases/tags/0.2.5: {"message":"API rate limit exceeded for 202.66.38.130. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

```yml
  localstack:
    image: localstack/localstack:1.2.0
    networks:
      - app_net
    ports:
      - "4567:4566"
    environment:
      - SERVICES=sns,cloudwatch,sqs,s3
      - DEFAULT_REGION=ap-southeast-2
      - DEBUG=1
```
but it works yesterday 🥲

**Comment by mohamedbanhawi** [comment]
Getting same error as op.
Issue started today.

`localstack`  logs
```bash
2022-10-19T09:18:41.087  INFO --- [-56 (worker)] l.services.install         : Downloading and installing local ElasticMQ server. This may take some time.
2022-10-19T09:18:43.325  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "prepare_installation" took 2445.17ms
Error starting infrastructure: Could not get list of releases from [https://api.github.com/repos/etspaceman/kinesis-mock/releases/tags/0.2.5:](https://api.github.com/repos/etspaceman/kinesis-mock/releases/tags/0.2.5) {"message":"API rate limit exceeded for 34.199.54.113. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

`Docker-Compose` File
Fixed by pinning `image: localstack/localstack:latest` to `1.1.0`
```yaml
services:
  localstack:
    image: localstack/localstack:1.1.0
    environment:
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=ap-southeast-2
      - SERVICES=dynamodb,s3,firehose,secretsmanager,athena
      - KINESIS_PROVIDER=kinesalite
      - KINESIS_ERROR_PROBABILITY=0.01
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4566-4583:4566-4583'
```

**Comment by mgrundie-r7** [comment]
Also seeing this issue on 1.2.0, launching with testcontainers
