### ISSUE TITLE
bug: LambdaExecutor.java:117 throws IllegalArgumentException: argument type mismatch

### ISSUE THREAD

**Issue by niqdev** [localstack/localstack#6835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the lambda is invoked with invalid parameters it succeeds, when it is invoked with a valid event it fails. See [LambdaExecutor.java#L117](https://github.com/localstack/localstack-java-utils/blob/master/src/main/java/cloud/localstack/LambdaExecutor.java#L117). I've tested it in multiple ways already, below the simplest possible way to reproduce the error.

Is there a way to debug the method invoked? I'm more than happy to open a pr or contribute to the repo.
Thanks in advance for your help

### Expected Behavior

The lambda should process valid events

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose.yml
```yaml
version: "3"

services:

  localstack:
    container_name: local-localstack
    image: localstack/localstack:1.1.0
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    hostname: localstack
    environment:
      - DEBUG=1
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
    volumes:
      - ".localstack:/var/lib/localstack"
```

Lambda implementation in Kotlin
```kotlin
import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.RequestHandler
import com.amazonaws.services.lambda.runtime.events.SQSEvent

class Handler : RequestHandler<SQSEvent?, String> {
    override fun handleRequest(input: SQSEvent?, context: Context): String {
        context.logger.log("SIZE: ${input?.records?.size}")
        input?.records?.map { it.body }?.forEach { context.logger.log("BODY: $it") }

        context.logger.log("TODO")
        return "SUCCESS"
    }
}
```

create function
```bash
aws lambda create-function \
  --endpoint-url=http://localhost:4566 \
  --function-name my-function \
  --runtime java11 \
  --handler com.example.Handler::handleRequest \
  --role arn:aws:iam::000000000000:role/localstack-role \
  --zip-file fileb://build/distributions/my-function.zip
```

invoke with invalid parameters: SUCCEED
```bash
aws lambda invoke \
  --endpoint-url=http://localhost:4566 \
  --function-name my-function  \
  --payload $(echo "{\"key\":\"value\"}" | base64) \
  my-function-output.json
```
Output success
```bash
local-localstack | 2022-09-07T09:53:51.241  INFO --- [uest_thread)] l.s.a.lambda_executors     : java  -cp /var/lib/localstack/tmp/function.zipfile.a22f84be/original_lambda_archive.zip:.:lib/annotations-13.0.jar:lib/aws-lambda-java-core-1.2.1.jar:lib/aws-lambda-java-events-3.11.0.jar:lib/joda-time-2.6.jar:lib/kotlin-stdlib-1.7.10.jar:lib/kotlin-stdlib-common-1.7.10.jar:lib/kotlin-stdlib-jdk7-1.7.10.jar:lib/kotlin-stdlib-jdk8-1.7.10.jar:original_lambda_archive.zip:.:*.jar:java/lib/*.jar:/usr/lib/localstack/localstack-utils-fat.jar cloud.localstack.LambdaExecutor /var/lib/localstack/tmp/lambda.event.f4bb7e76.json
local-localstack | 2022-09-07T09:53:51.241 DEBUG --- [uest_thread)] localstack.utils.run       : Executing command: java  -cp /var/lib/localstack/tmp/function.zipfile.a22f84be/original_lambda_archive.zip:.:lib/annotations-13.0.jar:lib/aws-lambda-java-core-1.2.1.jar:lib/aws-lambda-java-events-3.11.0.jar:lib/joda-time-2.6.jar:lib/kotlin-stdlib-1.7.10.jar:lib/kotlin-stdlib-common-1.7.10.jar:lib/kotlin-stdlib-jdk7-1.7.10.jar:lib/kotlin-stdlib-jdk8-1.7.10.jar:original_lambda_archive.zip:.:*.jar:java/lib/*.jar:/usr/lib/localstack/localstack-utils-fat.jar cloud.localstack.LambdaExecutor /var/lib/localstack/tmp/lambda.event.f4bb7e76.json
local-localstack | 2022-09-07T09:53:52.692 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Lambda arn:aws:lambda:us-east-1:000000000000:function:my-function result / log output:
local-localstack | "SUCCESS"
local-localstack | >Sep 07, 2022 9:53:52 AM cloud.localstack.LambdaContext$1 log
local-localstack | > INFO: SIZE: null
local-localstack | > Sep 07, 2022 9:53:52 AM cloud.localstack.LambdaContext$1 log
local-localstack | > INFO: TODO
local-localstack | 2022-09-07T09:53:52.709 DEBUG --- [   asgi_gw_1] plugin.manager             : instantiating plugin PluginSpec(localstack.aws.provider.logs:default = <function logs at 0x7f1db66d57e0>)
local-localstack | 2022-09-07T09:53:52.709 DEBUG --- [   asgi_gw_1] plugin.manager             : loading plugin localstack.aws.provider:logs:default
local-localstack | 2022-09-07T09:53:52.735 DEBUG --- [   asgi_gw_1] l.services.plugins         : checking service health logs:4566
local-localstack | 2022-09-07T09:53:52.821 DEBUG --- [   asgi_gw_1] plugin.manager             : instantiating plugin PluginSpec(localstack.aws.provider.cloudwatch:default = <function cloudwatch at 0x7f1db66d4940>)
local-localstack | 2022-09-07T09:53:52.821 DEBUG --- [   asgi_gw_1] plugin.manager             : loading plugin localstack.aws.provider:cloudwatch:default
local-localstack | 2022-09-07T09:53:52.840 DEBUG --- [   asgi_gw_1] l.services.plugins         : checking service health cloudwatch:4566
local-localstack | 2022-09-07T09:53:52.886 DEBUG --- [uest_thread)] l.s.awslambda.lambda_api   : Lambda invocation duration: 2215.35ms
```

invoke with a valid event: FAIL
```bash
aws lambda invoke \
  --endpoint-url=http://localhost:4566 \
  --function-name my-function  \
  --cli-binary-format raw-in-base64-out \
  --payload file://sqs-event.json \
  my-function-output.json
```
sqs-event.json (notification of ObjectCreated which triggers a sqs event)
```
{
  "Records": [
    {
      "body": "{\"Records\": [{\"eventVersion\": \"2.1\", \"eventSource\": \"aws:s3\", \"awsRegion\": \"us-east-1\", \"eventTime\": \"2022-09-06T16:34:59.955Z\", \"eventName\": \"ObjectCreated:Put\", \"userIdentity\": {\"principalId\": \"AIDAJDPLRKLG7UEXAMPLE\"}, \"requestParameters\": {\"sourceIPAddress\": \"127.0.0.1\"}, \"responseElements\": {\"x-amz-request-id\": \"b9159c9b\", \"x-amz-id-2\": \"eftixk72aD6Ap51TnqcoF8eFidJG9Z/2\"}, \"s3\": {\"s3SchemaVersion\": \"1.0\", \"configurationId\": \"d3a4a7f9-3666-4439-9da2-6154d900903e\", \"bucket\": {\"name\": \"my-bucket\", \"ownerIdentity\": {\"principalId\": \"A3NL1KOZZKExample\"}, \"arn\": \"arn:aws:s3:::my-bucket\"}, \"object\": {\"key\": \"README.md\", \"size\": 1269, \"eTag\": \"\\\"8d3cc26c8e99ddcf15b8384d55ddd1ef\\\"\", \"versionId\": null, \"sequencer\": \"0055AED6DCD90281E5\"}}}]}",
      "receiptHandle": "NTI5YjlmYWMtMGViOC00ODM4LThkY2YtMGFhYjAyNWJkYjA5IGFybjphd3M6c3FzOnVzLWVhc3QtMTowMDAwMDAwMDAwMDA6TXlRdWV1ZSAzMTI5MzBiZi1jNGQxLTQzZDktYTFiNy0xZGMxNTJjMTdkOGQgMTY2MjQ4MjEwMC40NDU3NTUy",
      "md5OfBody": "ab549787f02f837ce0be1b617bbae0d1",
      "eventSourceARN": "arn:aws:sqs:us-east-1:000000000000:MyQueue",
      "eventSource": "aws:sqs",
      "awsRegion": "us-east-1",
      "messageId": "312930bf-c4d1-43d9-a1b7-1dc152c17d8d",
      "attributes": {
        "SenderId": "000000000000",
        "SentTimestamp": "1662482099965",
        "ApproximateReceiveCount": "1",
        "ApproximateFirstReceiveTimestamp": "1662482100445"
      },
      "messageAttributes": {}
    }
  ]
}
```
Output failure
```
local-localstack | 2022-09-07T09:53:52.890  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS lambda.Invoke => 200
local-localstack | 2022-09-07T09:56:02.939  INFO --- [uest_thread)] l.s.a.lambda_executors     : java  -cp /var/lib/localstack/tmp/function.zipfile.a22f84be/original_lambda_archive.zip:.:lib/annotations-13.0.jar:lib/aws-lambda-java-core-1.2.1.jar:lib/aws-lambda-java-events-3.11.0.jar:lib/joda-time-2.6.jar:lib/kotlin-stdlib-1.7.10.jar:lib/kotlin-stdlib-common-1.7.10.jar:lib/kotlin-stdlib-jdk7-1.7.10.jar:lib/kotlin-stdlib-jdk8-1.7.10.jar:original_lambda_archive.zip:.:*.jar:java/lib/*.jar:/usr/lib/localstack/localstack-utils-fat.jar cloud.localstack.LambdaExecutor /var/lib/localstack/tmp/lambda.event.7ea37b62.json
local-localstack | 2022-09-07T09:56:02.939 DEBUG --- [uest_thread)] localstack.utils.run       : Executing command: java  -cp /var/lib/localstack/tmp/function.zipfile.a22f84be/original_lambda_archive.zip:.:lib/annotations-13.0.jar:lib/aws-lambda-java-core-1.2.1.jar:lib/aws-lambda-java-events-3.11.0.jar:lib/joda-time-2.6.jar:lib/kotlin-stdlib-1.7.10.jar:lib/kotlin-stdlib-common-1.7.10.jar:lib/kotlin-stdlib-jdk7-1.7.10.jar:lib/kotlin-stdlib-jdk8-1.7.10.jar:original_lambda_archive.zip:.:*.jar:java/lib/*.jar:/usr/lib/localstack/localstack-utils-fat.jar cloud.localstack.LambdaExecutor /var/lib/localstack/tmp/lambda.event.7ea37b62.json
local-localstack | 2022-09-07T09:56:03.900 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Lambda arn:aws:lambda:us-east-1:000000000000:function:my-function result / log output:
local-localstack |
local-localstack | >Exception in thread "main" java.lang.IllegalArgumentException: argument type mismatch
local-localstack | > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
local-localstack | > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
local-localstack | > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
local-localstack | > 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
local-localstack | > 	at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:117)
local-localstack | 2022-09-07T09:56:03.903  INFO --- [uest_thread)] l.s.a.lambda_executors     : writing log to file '/var/lib/localstack/tmp/lambda__i1gwmud.log'
```

if it can help I can provide more details or link a sample repo

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by whummer** [comment]
Hi @niqdev , thanks for reporting. Please note that the `local` Lambda executor has quite some gaps, and we generally don't recommend using it, particularly for Java Lambdas. 

Did you have a chance to test it with the default configuration, Docker-based Lambda execution? (`LAMBDA_EXECUTOR=docker`). Please note that this will require the Docker socket to be mounted into the LocalStack container:
```
    volumes:
      ...
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Hope that helps - please keep us posted on how it goes.. Thanks!

**Comment by niqdev** [comment]
Hi @whummer, thanks for taking the time to look into this! It actually worked, with some minor changes i.e. removed `hostname` which was causing errors with the executor

```bash
  localstack:
    image: localstack/localstack:1.1.0
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - PERSISTENCE=1
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_EXECUTOR=docker
      - DOCKER_SOCK=unix:///var/run/docker.sock
    volumes:
      - ".localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
I'll leave the linked pr with the steps in the readme to setup `s3 -> sqs -> lambda` for future reference.

Thanks a lot for the feedback and the project!
