### ISSUE TITLE
bug: Cognito: creating different usernames with the same email user attribute results in UsernameExistsException

### ISSUE THREAD

**Issue by cmagorian** [localstack/localstack#6848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After creating a UserPool with configurations to allow for only `preferredUsername` as the AliasAttributes and no `Username.CaseSensitivity` with:

```
AliasAttributes:
  - "preferred_username"
AutoVerifiedAttributes:
  - "email"
UsernameConfiguration:
  CaseSensitive: false
```

I get an error when creating two different usernames `username1` and `username2` that have the same `email` UserAttribute. The error:

```
An error occurred (UsernameExistsException) when calling the AdminCreateUser operation: An account with the given username already exists.
```

The command:

```
awslocal cognito-idp admin-create-user --user-pool-id <user-pool-id> --username username1 --user-attributes Name=email,Value=some@example.com
```

### Expected Behavior

I find that if I run `awslocal cognito-idp list-users --user-pool-id <user-pool-id>` that the user actually exists in the database, but the call returns an error.

When I run these same commands against a real AWS Cognito user pool, I do not see this behavior. I get the expected successful response body:

```
{
    "User": {
        "Username": "username1",
        "Attributes": [
            {
                "Name": "sub",
                "Value": "532cfc45-dbcf-4a98-91b3-d8a62caf1f7f"
            },
            {
                "Name": "email",
                "Value": "some@example.com"
            }
        ],
        "UserCreateDate": "2022-09-09T09:54:35.555000-07:00",
        "UserLastModifiedDate": "2022-09-09T09:54:35.555000-07:00",
        "Enabled": true,
        "UserStatus": "FORCE_CHANGE_PASSWORD"
    }
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up -d --force-recreate

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal cognito-idp admin-create-user --user-pool-id <user-pool-id> --username username1 --user-attributes Name=email,Value=some@example.com
    
    awslocal cognito-idp admin-create-user --user-pool-id <user-pool-id> --username username2 --user-attributes Name=email,Value=some@example.com

### Environment

```markdown
- OS: Mac 12.5.1 arm64
- LocalStack: latest
```

**Comment by MallikharjunaTeja** [comment]
hi @localstack-bot i want to work on this

**Comment by cmagorian** [comment]
Was anybody able to repro this?

**Comment by dominikschubert** [comment]
@cmagorian   This should be available soon via the latest image, might take a while currently since GitHub seems to have some connectivity issues today and the CI needs to run through for the latest image to be updated.

If you check tomorrow (use the newest latest then via `docker pull localstack/localstack`), it should be fixed :+1:

**Comment by cmagorian** [comment]
The latest version is breaking with:

```
2022-09-15T16:22:01.008 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:setup_pro_infra
2022-09-15T16:22:01.008 DEBUG --- [  MainThread] l.bootstrap.install        : Using cached SSL certificate (less than 6hrs since last update).
2022-09-15T16:22:01.764 ERROR --- [  MainThread] l.bootstrap.licensing      : exception while activating key
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/bootstrap/licensing.py", line 87, in prepare_environment
    B=fetch_key()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/bootstrap/licensing.py", line 46, in fetch_key
    if B.status_code==403:J=json.loads(to_str(E))['message'];raise InvalidKeyError('Activation key %s is invalid or expired! Reason: %s'%(truncate_api_key(A),J))
localstack_ext.bootstrap.licensing.InvalidKeyError: Activation key "4wk..."(10) is invalid or expired! Reason: Unable to verify API key
2022-09-15T16:22:01.766  WARN --- [  MainThread] localstack_ext.plugins     : error setting up dns server: cannot import name 'dns_server' from 'localstack_ext.services' (/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/__init__.py)
2022-09-15T16:22:01.825 DEBUG --- [  MainThread] l.a.p.service_router       : loading service catalog index cache file /var/lib/localstack/cache/service-catalog-1_1_1_dev-1_27_71.pickle
2022-09-15T16:22:01.831 ERROR --- [  MainThread] localstack_ext.plugins     : error enabling pro code
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/plugins.py", line 69, in setup_pro_infra
    try:from localstack_ext.aws.protocol import service_router as C;from localstack_ext.services import edge;from localstack_ext.utils.aws import aws_utils as D;C.patch_service_router();edge.patch_start_edge();patch_start_infra();D.patch_aws_utils();set_default_providers_to_pro()
ImportError: cannot import name 'edge' from 'localstack_ext.services' (/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/__init__.py)
2022-09-15T16:22:01.831 DEBUG --- [  MainThread] localstack.runtime.init    : Init scripts discovered: {BOOT: [], START: [], READY: [], SHUTDOWN: []}
2022-09-15T16:22:01.847  WARN --- [  MainThread] l.services.internal        : Enabling diagnose endpoint, please be aware that this can expose sensitive information via your network.
2022-09-15T16:22:01.849 DEBUG --- [  MainThread] localstack.services.infra  : [shutdown] Cleaning up services ...
2022-09-15T16:22:01.852 DEBUG --- [  MainThread] localstack.services.infra  : [shutdown] Cleaning up resources ...
2022-09-15T16:22:01.852 DEBUG --- [  MainThread] localstack.utils.threads   : [shutdown] Done cleaning up threads / processes / tasks
2022-09-15T16:22:01.854 DEBUG --- [  MainThread] localstack.utils.run       : Executing command: rm -rf "/var/lib/localstack/tmp"
2022-09-15T16:22:01.864 DEBUG --- [  MainThread] localstack.services.infra  : [shutdown] Force shutdown, not waiting for infrastructure to shut down
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/code/localstack/localstack/cli/main.py", line 10, in <module>
    main()
  File "/opt/code/localstack/localstack/cli/main.py", line 6, in main
    cli()
  File "/opt/code/localstack/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/code/localstack/localstack/utils/analytics/cli.py", line 66, in publisher_wrapper
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/cli/localstack.py", line 147, in cmd_start
    bootstrap.start_infra_locally()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 260, in start_infra_locally
    return infra.start_infra()
  File "/opt/code/localstack/localstack/services/infra.py", line 434, in start_infra
    raise e
  File "/opt/code/localstack/localstack/services/infra.py", line 417, in start_infra
    hooks.on_infra_start.run()
  File "/opt/code/localstack/localstack/runtime/hooks.py", line 64, in run_in_order
    fn_plugin(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/plugin/core.py", line 183, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/analytics/plugins.py", line 4, in add_aws_request_logger
    def add_aws_request_logger():from localstack.aws import handlers as A;from .aws_request_logger import RequestLoggerHandler as B;A.count_service_request=B()
ModuleNotFoundError: No module named 'localstack_ext.analytics.aws_request_logger'
2022-09-15 16:22:02,991 INFO spawned: 'infra' with pid 63
```
