### ISSUE TITLE
bug: Regression of localstack tooling in Github Actions

### ISSUE THREAD

**Issue by cefn** [localstack/localstack#6857]
### Current Behavior

I am getting a huge stack trace from any attempt to launch localstack in Github actions, which is fatal to my test suite. This worked last week. Since there has been a very recent release of the localstack docker image that's where my suspicion falls. I guess it could theoretically be a variation in ubuntu:latest (removing an SSL library ?!?) but that seems less likely.

The core issue seems to be...

```
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

I gave up and went back to the last passing commit, and found that exactly the same test suite on the same commit fails today which passed last week. 

This week, the attempt to launch localstack on Github actions using `localstack start -d` results in this traceback and a failing test suite instead.

```bash
modules/keystore-s3 test$ run-s localstack:up localstack:wait test:jest localstack:down
modules/keystore-s3 test: > @notesome/keystore-s3@0.1.0 localstack:up /home/runner/work/notesome/notesome/modules/keystore-s3
modules/keystore-s3 test: > localstack start -d
modules/keystore-s3 test: Traceback (most recent call last):
modules/keystore-s3 test:   File "/home/runner/.local/bin/localstack", line 23, in <module>
modules/keystore-s3 test:     main()
modules/keystore-s3 test:   File "/home/runner/.local/bin/localstack", line 19, in main
modules/keystore-s3 test:     main.main()
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/localstack/cli/main.py", line 3, in main
modules/keystore-s3 test:     from .localstack import create_with_plugins
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/localstack/cli/localstack.py", line 7, in <module>
modules/keystore-s3 test:     from localstack import config
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/localstack/config.py", line 11, in <module>
modules/keystore-s3 test:     from localstack.constants import (
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/localstack/constants.py", line 3, in <module>
modules/keystore-s3 test:     import localstack_client.config
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/localstack_client/config.py", line 7, in <module>
modules/keystore-s3 test:     from localstack_client.patch import patch_expand_host_prefix  # noqa
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/localstack_client/patch.py", line 3, in <module>
modules/keystore-s3 test:     import boto3
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/boto3/__init__.py", line 17, in <module>
modules/keystore-s3 test:     from boto3.session import Session
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/boto3/session.py", line 17, in <module>
modules/keystore-s3 test:     import botocore.session
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/session.py", line 26, in <module>
modules/keystore-s3 test:     import botocore.client
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/client.py", line 17, in <module>
modules/keystore-s3 test:     from botocore import waiter, xform_name
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/waiter.py", line 18, in <module>
modules/keystore-s3 test:     from botocore.docs.docstring import WaiterDocstring
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/docs/__init__.py", line 15, in <module>
modules/keystore-s3 test:     from botocore.docs.service import ServiceDocumenter
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/docs/service.py", line 14, in <module>
modules/keystore-s3 test:     from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/docs/client.py", line 14, in <module>
modules/keystore-s3 test:     from botocore.docs.example import ResponseExampleDocumenter
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/docs/example.py", line 13, in <module>
modules/keystore-s3 test:     from botocore.docs.shape import ShapeDocumenter
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/docs/shape.py", line 19, in <module>
modules/keystore-s3 test:     from botocore.utils import is_json_value_header
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/utils.py", line 34, in <module>
modules/keystore-s3 test:     import botocore.httpsession
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/httpsession.py", line 41, in <module>
modules/keystore-s3 test:     from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
modules/keystore-s3 test:     import OpenSSL.SSL
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
modules/keystore-s3 test:     from OpenSSL import crypto, SSL
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line [155](https://github.com/cefn/notesome/runs/8303101268?check_suite_focus=true#step:7:156)3, in <module>
modules/keystore-s3 test:     class X509StoreFlags(object):
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
modules/keystore-s3 test:     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
modules/keystore-s3 test: AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
modules/keystore-s3 test: Error in sys.excepthook:
modules/keystore-s3 test: Traceback (most recent call last):
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
modules/keystore-s3 test:     from apport.fileutils import likely_packaged, get_recent_crashes
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
modules/keystore-s3 test:     from apport.report import Report
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
modules/keystore-s3 test:     import apport.fileutils
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
modules/keystore-s3 test:     import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
modules/keystore-s3 test:     import requests
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
modules/keystore-s3 test:     from urllib3.contrib import pyopenssl
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
modules/keystore-s3 test:     import OpenSSL.SSL
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
modules/keystore-s3 test:     from OpenSSL import crypto, SSL
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
modules/keystore-s3 test:     class X509StoreFlags(object):
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
modules/keystore-s3 test:     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
modules/keystore-s3 test: AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
modules/keystore-s3 test: Original exception was:
modules/keystore-s3 test: Traceback (most recent call last):
modules/keystore-s3 test:   File "/home/runner/.local/bin/localstack", line 23, in <module>
modules/keystore-s3 test:     main()
modules/keystore-s3 test:   File "/home/runner/.local/bin/localstack", line 19, in main
modules/keystore-s3 test:     main.main()
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/localstack/cli/main.py", line 3, in main
modules/keystore-s3 test:     from .localstack import create_with_plugins
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/localstack/cli/localstack.py", line 7, in <module>
modules/keystore-s3 test:     from localstack import config
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/localstack/config.py", line 11, in <module>
modules/keystore-s3 test:     from localstack.constants import (
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/localstack/constants.py", line 3, in <module>
modules/keystore-s3 test:     import localstack_client.config
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/localstack_client/config.py", line 7, in <module>
modules/keystore-s3 test:     from localstack_client.patch import patch_expand_host_prefix  # noqa
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/localstack_client/patch.py", line 3, in <module>
modules/keystore-s3 test:     import boto3
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/boto3/__init__.py", line 17, in <module>
modules/keystore-s3 test:     from boto3.session import Session
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/boto3/session.py", line 17, in <module>
modules/keystore-s3 test:     import botocore.session
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/session.py", line 26, in <module>
modules/keystore-s3 test:     import botocore.client
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/client.py", line 17, in <module>
modules/keystore-s3 test:     from botocore import waiter, xform_name
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/waiter.py", line 18, in <module>
modules/keystore-s3 test:     from botocore.docs.docstring import WaiterDocstring
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/docs/__init__.py", line 15, in <module>
modules/keystore-s3 test:     from botocore.docs.service import ServiceDocumenter
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/docs/service.py", line 14, in <module>
modules/keystore-s3 test:     from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/docs/client.py", line 14, in <module>
modules/keystore-s3 test:     from botocore.docs.example import ResponseExampleDocumenter
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/docs/example.py", line 13, in <module>
modules/keystore-s3 test:     from botocore.docs.shape import ShapeDocumenter
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/docs/shape.py", line 19, in <module>
modules/keystore-s3 test:     from botocore.utils import is_json_value_header
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/utils.py", line 34, in <module>
modules/keystore-s3 test:     import botocore.httpsession
modules/keystore-s3 test:   File "/home/runner/.local/lib/python3.8/site-packages/botocore/httpsession.py", line 41, in <module>
modules/keystore-s3 test:     from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
modules/keystore-s3 test:     import OpenSSL.SSL
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
modules/keystore-s3 test:     from OpenSSL import crypto, SSL
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
modules/keystore-s3 test:     class X509StoreFlags(object):
modules/keystore-s3 test:   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line [157](https://github.com/cefn/notesome/runs/8303101268?check_suite_focus=true#step:7:158)3, in X509StoreFlags
modules/keystore-s3 test:     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
modules/keystore-s3 test: AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
modules/keystore-s3 test:  ELIFECYCLE  Command failed with exit code 1.
modules/keystore-s3 test: ERROR: "localstack:up" exited with 1.
modules/keystore-s3 test: Failed
undefined
/home/runner/work/notesome/notesome/modules/keystore-s3:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @notesome/keystore-s3@0.1.0 test: `run-s localstack:up localstack:wait test:jest localstack:down`
```

### Expected Behavior

The passing suite from last week would still pass with the latest Pypi and docker combination from localstack.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
localstack start -d
```

### Environment

```markdown
Github actions
```

### Anything else?

Below is some extra information about the suite and how I am invoking it via Github actions

#### Last week

This was the behaviour of the suite from last week, where the same localstack launch did exactly what was expected - and the test suite that relied on it also passed.

![image](https://user-images.githubusercontent.com/159819/189631194-fae89619-e3fc-4ac0-8809-defa2ecbc865.png)

#### Github workflow...

This is the workflow file which drives Github actions in the repo

```yml

name: Node.js Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install PNPM
        run: npm install -g pnpm@6
      - run: pnpm install
      - run: python3 -m pip install localstack
      - run: pnpm run qa
```

#### package.json (the targets that launch localstack)

```json
{
  "name": "@notesome/keystore-s3",
  "version": "0.1.0",
  "description": "",
  "main": "src/index.ts",
  "scripts": {
    "check": "tsc --noEmit",
    "localstack:up": "localstack start -d",
    "localstack:wait": "localstack wait",
    "localstack:down": "localstack stop",
    "localstack:reset": "run-s localstack:down localstack:up",
    "test:jest": "jest",
    "test": "run-s localstack:up localstack:wait test:jest localstack:down"
  },
  "author": "Cefn Hoile",
  "license": "MIT",
  "dependencies": {
    "@aws-sdk/client-s3": "^3.154.0",
    "@notesome/keystore": "workspace:^0.1.0"
  },
  "devDependencies": {
    "@notesome/nevermore": "workspace:^0.1.0",
    "@notesome/vault": "workspace:^0.1.0",
    "nanoid": "^3.0.0"
  }
}
```

**Comment by dominikschubert** [comment]
Duplicate #6831

Please check out the linked PR on how to resolve this issue!
