### ISSUE TITLE
Error upgrading Glue version 3.0 in localstack docker

### ISSUE THREAD

**Issue by daniel-e-r** [localstack/localstack#6873]
When trying to execute a job that uses glue version 3.0 I get the following error in localstack docker

2022-09-14T14:59:06.804:DEBUG:localstack_ext.services.glue.job_executor: Glue job execution failed: Failed to download https://aws-glue-etl-artifacts.s3.amazonaws.com/release/com/amazonaws/AWSGlueLineageCommons/1.0/AWSGlueLineageCommons-1.0.jarhttps://localstack-web-assets.s3.amazonaws.com/AWSGlueDataplane-1.0-Scala2.12.jar, response code 404 Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/glue/job_executor.py.enc", line 59, in G
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/glue/job_executor.py.enc", line 68, in H
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/glue/job_executor.py.enc", line 50, in get_job_cmd_pyspark
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/glue/job_executor.py.enc", line 82, in install_glue_spark_version
  File "/opt/code/localstack/localstack/utils/http.py", line 194, in download
    raise Exception("Failed to download %s, response code %s" % (url, r.status_code))
Exception: Failed to download https://aws-glue-etl-artifacts.s3.amazonaws.com/release/com/amazonaws/AWSGlueLineageCommons/1.0/AWSGlueLineageCommons-1.0.jarhttps://localstack-web-assets.s3.amazonaws.com/AWSGlueDataplane-1.0-Scala2.12.jar, response code 404

Steps to reproduce:
awslocal s3 mb s3://glue-test
awslocal s3 cp job.py s3://glue-test/job.py
awslocal glue create-job --name job2 --role r1   --command '{"Name": "pythonshell", "ScriptLocation": "s3://glue-test/job.py"}' --glue-version "3.0"
awslocal glue start-job-run --job-name job2

**Comment by daniel-e-r** [comment]
Issue was solved with latest localstack and localstack:bigdata images.
