### ISSUE TITLE
Unable to make a call to the rds-data api with aurora-mysql

### ISSUE THREAD

**Issue by Vizz85** [localstack/localstack#6887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After provisioning my resources with terraform, a call to 
`aws --endpoint-url http://localhost:4566 rds-data execute-statement --database identificators --resource-arn arn:aws:rds:eu-central-1:000000000000:cluster:identificators-cluster --secret-arn arn:aws:secretsmanager:eu-central-1:000000000000:secret:rds-credentials-DxaFDY --include-result-metadata --sql 'SELECT 123'` 
returns following error: 
`An error occurred (BadRequestException) when calling the ExecuteStatement operation: Unable to execute statement: received invalid response to SSL negotiation: c`

### Expected Behavior

The call should return a valid response

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    `docker compose -f docker-compose.local.yml up`

```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "53:53"                # only required for Pro (DNS)
      - "53:53/udp"            # only required for Pro (DNS)
      - "443:443"              # only required for Pro (LocalStack HTTPS Edge Proxy)
      - "4510-4559:4510-4559"  # external service port range
      - "4566:4566"            # LocalStack Edge Proxy
    environment:
      - LAMBDA_DOCKER_NETWORK=did-network
      - HOSTNAME_EXTERNAL=localhost
      - DNS_ADDRESS=0
      - LOCALSTACK_API_KEY=xxxxxx
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - sharednet

networks:
  sharednet:
    name: did-network
```

#### Terraform configuration

    `terraform apply`

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.12.0"
    }
  }

  required_version = "~> 1.1.0"
}

provider "aws" {
  region     = "eu-central-1"
  access_key = "my-access-key"
  secret_key = "my-secret-key"

  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    apigateway     = "http://localhost:4566"
    cloudformation = "http://localhost:4566"
    cloudwatch     = "http://localhost:4566"
    dynamodb       = "http://localhost:4566"
    ec2            = "http://localhost:4566"
    es             = "http://localhost:4566"
    elasticache    = "http://localhost:4566"
    firehose       = "http://localhost:4566"
    iam            = "http://localhost:4566"
    kinesis        = "http://localhost:4566"
    lambda         = "http://localhost:4566"
    rds            = "http://localhost:4566"
    rdsdata        = "http://localhost:4566"
    redshift       = "http://localhost:4566"
    route53        = "http://localhost:4566"
    s3             = "http://localhost:4566"
    secretsmanager = "http://localhost:4566"
    ses            = "http://localhost:4566"
    sns            = "http://localhost:4566"
    sqs            = "http://localhost:4566"
    ssm            = "http://localhost:4566"
    stepfunctions  = "http://localhost:4566"
    sts            = "http://localhost:4566"
  }
}

resource "random_password" "rds-master-password" {
  length           = 24
  special          = true
  override_special = "^*-=+"
}

resource "aws_secretsmanager_secret" "rds-credentials" {
  name                    = "rds-credentials"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "rds-credentials" {
  secret_id     = aws_secretsmanager_secret.rds-credentials.id
  secret_string = <<EOF
{
  "username": "${aws_rds_cluster.identificators.master_username}",
  "password": "${random_password.rds-master-password.result}",
  "engine": "mysql",
  "host": "${aws_rds_cluster.identificators.endpoint}",
  "port": ${aws_rds_cluster.identificators.port},
  "dbClusterIdentifier": "${aws_rds_cluster.identificators.cluster_identifier}"
}
EOF
}

resource "aws_ssm_parameter" "secret-rds-credentials-arn" {
  name      = "secret-rds-credentials-arn"
  type      = "String"
  value     = aws_secretsmanager_secret_version.rds-credentials.arn
  overwrite = true
}


resource "aws_rds_cluster" "identificators" {
  cluster_identifier      = "identificators-cluster"
  engine                  = "aurora-mysql"
  engine_mode             = "serverless"
  database_name           = "identificators"
  enable_http_endpoint    = true
  master_username         = var.db_master_username
  master_password         = random_password.rds-master-password.result
  backup_retention_period = 1

  skip_final_snapshot    = true

  scaling_configuration {
    auto_pause               = true
    min_capacity             = 1
    max_capacity             = 1
    seconds_until_auto_pause = 300
    timeout_action           = "ForceApplyCapacityChange"
  }
}

```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    `aws --endpoint-url http://localhost:4566 rds-data execute-statement --database identificators --resource-arn arn:aws:rds:eu-central-1:000000000000:cluster:identificators-cluster --secret-arn arn:aws:secretsmanager:eu-central-1:000000000000:secret:rds-credentials-DxaFDY --include-result-metadata --sql 'SELECT 123'`

### Environment

```markdown
- OS: MacOS 12.5.1
- LocalStack: 1.1.1.dev (localstack/localstack:latest)
```

### Anything else?

When invoking a GO 1.x lambda which access the rds data aws sdk I get following error output in the localstack logs:

```
localstack_main | 2022-09-14T14:45:06.229 DEBUG --- [uest_thread)] l.u.c.container_client     : Getting the entrypoint for image: localstack/lambda:go1.x
localstack_main | 2022-09-14T14:45:06.237 DEBUG --- [uest_thread)] l.u.c.docker_sdk_client    : Creating container with attributes: {'mount_volumes': None, 'ports': <PortMappings: {}>, 'cap_add': ['NET_ADMIN'], 'cap_drop': None, 'security_opt': None, 'dns': '', 'additional_flags': '', 'workdir': None, 'privileged': None, 'command': 'bin/id-generator-create-tables', 'detach': False, 'entrypoint': '/tmp/14bf5e8b.sh', 'env_vars': {'DB_ARN': 'arn:aws:rds:eu-central-1:000000000000:cluster:identificators-cluster', 'DB_NAME': 'identificators', 'SECRET_ARN': 'arn:aws:secretsmanager:eu-central-1:000000000000:secret:rds-credentials-RpvVpK', 'AWS_ACCESS_KEY_ID': 'test', 'AWS_SECRET_ACCESS_KEY': 'test', 'AWS_REGION': 'eu-central-1', 'DOCKER_LAMBDA_USE_STDIN': '1', 'LOCALSTACK_HOSTNAME': '172.18.0.2', 'AWS_ENDPOINT_URL': 'http://172.18.0.2:4566', 'EDGE_PORT': '443', '_HANDLER': 'bin/id-generator-create-tables', 'AWS_LAMBDA_FUNCTION_TIMEOUT': '6', 'AWS_LAMBDA_FUNCTION_NAME': 'did-id-generator-create-tables-testing-create-tables', 'AWS_LAMBDA_FUNCTION_VERSION': '$LATEST', 'AWS_LAMBDA_FUNCTION_INVOKED_ARN': 'arn:aws:lambda:eu-central-1:000000000000:function:did-id-generator-create-tables-testing-create-tables', 'LOCALSTACK_DEBUG': '1'}, 'image_name': 'localstack/lambda:go1.x', 'interactive': True, 'name': None, 'network': 'did-network', 'remove': True, 'self': <localstack.utils.container_utils.docker_sdk_client.SdkDockerClient object at 0x7fd37eb1d840>, 'tty': False, 'user': 'root'}
localstack_main | 2022-09-14T14:45:06.306 DEBUG --- [uest_thread)] l.u.c.docker_sdk_client    : Copying file /tmp/function.zipfile.49544d7e/. into 8780bb0ea06f788022aa710675a290d7483e750ed16a2ad74f76da85eb64785e:/var/task
localstack_main | 2022-09-14T14:45:06.696 DEBUG --- [uest_thread)] l.u.c.docker_sdk_client    : Copying file /var/lib/localstack/tmp/14bf5e8b.sh into 8780bb0ea06f788022aa710675a290d7483e750ed16a2ad74f76da85eb64785e:/tmp/14bf5e8b.sh
localstack_main | 2022-09-14T14:45:06.859 DEBUG --- [uest_thread)] l.u.c.docker_sdk_client    : Starting container 8780bb0ea06f788022aa710675a290d7483e750ed16a2ad74f76da85eb64785e
localstack_main | 2022-09-14T14:45:07.681 DEBUG --- [   asgi_gw_0] l.services.plugins         : checking service health rds-data:4566
localstack_main | 2022-09-14T14:45:07.688 DEBUG --- [   asgi_gw_0] l.s.rds_data.provider      : Fetching password from secret ARN "arn:aws:secretsmanager:eu-central-1:000000000000:secret:rds-credentials-RpvVpK" for accessing RDS DB "identificators"
localstack_main | 2022-09-14T14:45:07.764 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
localstack_main | Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/aws/chain.py", line 57, in handle
localstack_main |     handler(self, self.context, response)
localstack_main |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 122, in __call__
localstack_main |     handler(chain, context, response)
localstack_main |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 92, in __call__
localstack_main |     skeleton_response = self.skeleton.invoke(context)
localstack_main |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
localstack_main |     return self.dispatch_request(context, instance)
localstack_main |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
localstack_main |     result = handler(context, instance) or {}
localstack_main |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
localstack_main |     return self.fn(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/aws/api/core.py", line 115, in operation_marker
localstack_main |     return fn(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/rds_data/provider.py.enc", line 88, in begin_transaction
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/rds/engine_postgres.py.enc", line 64, in begin_transaction
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/rds/engine_postgres.py.enc", line 114, in _db_instance
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/postgres/__init__.py", line 322, in __init__
localstack_main |     self.pool = pool_class(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/psycopg2_pool/__init__.py", line 230, in __init__
localstack_main |     super(ThreadSafeConnectionPool, self).__init__(**kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/psycopg2_pool/__init__.py", line 90, in __init__
localstack_main |     self._connect()
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/psycopg2_pool/__init__.py", line 95, in _connect
localstack_main |     conn = psycopg2._connect(**self.connect_kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/postgres/__init__.py", line 599, in __init__
localstack_main |     psycopg2.extensions.connection.__init__(self, *a, **kw)
localstack_main | psycopg2.OperationalError: connection to server at "127.0.0.1", port 4510 failed: received invalid response to SSL negotiation: c
```

**Comment by steffyP** [comment]
Hi @Vizz85,

thanks for your report! We are able to reproduce your issue.
Currently we only support `aurora-postgresql` for the `rds-data` api. I tested your example with `aurora-postgresql` which seems to work. 
I hope this would be an acceptable workaround for you in the meantime.

**Comment by Vizz85** [comment]
Hi @steffyP,

Yes, I think we can handle it with this workaround.

Thank you for the quick response!

**Comment by darbinyanbabken** [comment]
Have the same issue. Using latest Localstack PRO

**Comment by hieudv91** [comment]
+1 👍

**Comment by whummer** [comment]
Hi @Vizz85 @darbinyanbabken @hieudv91 @capt4ce @hiru-vn @radmanz @garodaj24 @anton-hryshchanka quick update, we have now added initial support for targeting MySQL databases via the RDS-Data API. 

When you get a chance, can you please pull the `latest` Docker image and give it a try? Please keep us posted on how it goes.. Thanks!

**Comment by darbinyanbabken** [comment]
Hi @whummer. I can confirm it is working now. Thank you.
