### ISSUE TITLE
bug: SNS publish fails when MessageAttributeValue dataType is set

### ISSUE THREAD

**Issue by MhamedLmr** [localstack/localstack#6907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to publish a message using SNS, when I set the String Value for any particular data type (String, Number...) as the documentation explains the publish fails with the following error:

```java
PublishRequest publishRequest = new PublishRequest();
		publishRequest.setTopicArn(topicArn);
		publishRequest.setMessage(message);
		publishRequest.setMessageAttributes(Map.of("country",  new MessageAttributeValue().withDataType("String").withStringValue("country1")));
```

```
localstack_1        | 2022-09-20T16:04:40.049 ERROR --- [ Thread-3574] asyncio                    : Task exception was never retrieved

localstack_1        | future: <Task finished name='Task-27660' coro=<message_to_subscriber() done, defined at /opt/code/localstack/localstack/services/sns/provider.py:904> exception=KeyError('BinaryValue')>

localstack_1        | Traceback (most recent call last):

localstack_1        |   File "/opt/code/localstack/localstack/services/sns/provider.py", line 957, in message_to_subscriber

localstack_1        |     message_body = create_sns_message_body(subscriber, req_data, message_id, message_attributes)

localstack_1        |   File "/opt/code/localstack/localstack/services/sns/provider.py", line 1271, in create_sns_message_body

localstack_1        |     data["MessageAttributes"] = prepare_message_attributes(message_attributes)

localstack_1        |   File "/opt/code/localstack/localstack/services/sns/provider.py", line 1327, in prepare_message_attributes

localstack_1        |     val = base64.b64encode(attr["BinaryValue"]).decode()

localstack_1        | KeyError: 'BinaryValue'
```

**When I skip setting the dataType and use the withStringValue directly it works:**

```java
inal PublishRequest publishRequest = new PublishRequest();
		publishRequest.setTopicArn(topicArn);
		publishRequest.setMessage(message);
		publishRequest.setMessageAttributes(Map.of("country",  new MessageAttributeValue().withStringValue("country1")));
```

```
localstack_1        | 2022-09-21T15:31:15.544  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS sns.Publish => 200
```

### Expected Behavior

- The call to publish with dataType set explicitly should be successful

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up -d localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws --endpoint-url http://localhost:4566 sqs create-queue --queue-name "$QUEUE_NAME" --output text

    aws --endpoint-url http://localhost:4566 sns create-topic --name "$TOPIC_NAME" --output text
  
   aws --endpoint-url http://localhost:4566 sns subscribe --topic-arn "$TOPIC_ARN" --protocol sqs --notification-endpoint "$QUEUE_URL" --output text

### Environment

```markdown
- OS:MAC OS BIG SUR
- LocalStack: 1.1.0
```

**Comment by MhamedLmr** [comment]
Hello @bentsku thnak you for your feedback, I did as instructed and I experimented a bit and managed to figure out the issue.
Seems like this occurs when one of the `MessageAttributeValue` values is `null` the payload looks as fellow:
```
2022-09-23T13:16:05.477 DEBUG --- [   asgi_gw_0] l.aws.serving.wsgi         : POST localhost:4566/

2022-09-23T13:16:05.482 DEBUG --- [   asgi_gw_0] l.services.sns.provider    : Publishing message to TopicArn: arn:aws:sns:us-west-1:000000000000:my-event | Message: {"key1":data1}

2022-09-23T13:16:05.485 ERROR --- [  Thread-328] asyncio                    : Task exception was never retrieved

future: <Task finished name='Task-1667' coro=<message_to_subscriber() done, defined at /opt/code/localstack/localstack/services/sns/provider.py:904> exception=KeyError('BinaryValue')>

Traceback (most recent call last):

  File "/opt/code/localstack/localstack/services/sns/provider.py", line 957, in message_to_subscriber

    message_body = create_sns_message_body(subscriber, req_data, message_id, message_attributes)

  File "/opt/code/localstack/localstack/services/sns/provider.py", line 1271, in create_sns_message_body

    data["MessageAttributes"] = prepare_message_attributes(message_attributes)

  File "/opt/code/localstack/localstack/services/sns/provider.py", line 1327, in prepare_message_attributes

    val = base64.b64encode(attr["BinaryValue"]).decode()

KeyError: 'BinaryValue'

2022-09-23T13:16:05.485 DEBUG --- [   asgi_gw_0] l.aws.protocol.serializer  : No accept header given. Using request's Content-Type (application/x-www-form-urlencoded; charset=utf-8) as preferred response Content-Type.

2022-09-23T13:16:05.490  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS sns.Publish => 200; PublishInput({'TopicArn': 'arn:aws:sns:us-west-1:000000000000:my-event', 'Message': 'Message: {"key1":data1}', 'MessageAttributes': {'country': {'DataType': 'String', 'StringValue': 'Country1'}, 'region': {'DataType': 'String'}}, headers={'Host': 'localhost:4566', 'amz-sdk-invocation-id': 'cd6cf481-c70d-4754-33a5-4d3cb924395b', 'amz-sdk-request': 'attempt=1;max=4', 'amz-sdk-retry': '0/0/500', 'Authorization': 'AWS4-HMAC-SHA256 Credential=dummy/20220923/ap-southeast-1/sns/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;amz-sdk-retry;host;user-agent;x-amz-date;x-amz-security-token, Signature=6d6064eb7679b1c223e28e2d0c0dffccae6d88b9bb4289cb53fede5393815f1c', 'User-Agent': 'aws-sdk-java/1.12.272 Mac_OS_X/11.5.2 Java_HotSpot(TM)_64-Bit_Server_VM/11.0.16.1+1-LTS-1 java/11.0.16.1 kotlin/1.6.10 vendor/Oracle_Corporation cfg/retry-mode/legacy', 'X-Amz-Date': '20220923T131605Z', 'X-Amz-Security-Token': '', 'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'Content-Length': '1397', 'Connection': 'Keep-Alive', 'x-localstack-tgt-api': 'sns', 'x-moto-account-id': '000000000000'}); PublishResponse({'MessageId': 'b26d9889-7199-45bd-bab5-f1ce8528232b'}, headers={'Content-Type': 'text/xml', 'Content-Length': '325', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'etag,x-amz-version-id'})
```

As you can see here the region Attribute has no String Value, and when I make sure that nothing is null, the issue doesn't occur.
```
'MessageAttributes': {'country': {'DataType': 'String', 'StringValue': 'Country1'}, 'region': {'DataType': 'String'}}
```

**Comment by bentsku** [comment]
Awesome, thanks a lot @MhamedLmr !
I could test against AWS, and they will raise an `InvalidParameterValueException` when a `MessageAttributeValue`  is set to null. After the linked PR is merged, we will raise the proper exception.
Thank you again for taking the time to experiment and your detailed report. Much appreciated!
