### ISSUE TITLE
bug: Using EventBridge L2 construct Rule from aws-cdk-lib/aws-events produces an error

### ISSUE THREAD

**Issue by KurtMar** [localstack/localstack#6950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Deploying the provided stack in CDK with `cdklocal deploy` will produce the following in LocalStack logs:
`Unable to deploy resource type "CloudwatchLogResourcePolicy"`

The deployment will go through, but upon `cdklocal destroy` there will be an error in the logs:
`Action delete for resource type CloudwatchLogResourcePolicy not available`

While destruction seems to work, after running `cdklocal deploy` and `cdklocal destroy` again the process will be stuck in an infinite loop with the following repeated error in logs:
`exception during call chain: An error occurred (ResourceNotFoundException) when calling the ListTargetsByRule operation: Rule some-events-rule does not exist.`

### Expected Behavior

The L2 construct Rule should be deployed and destroyed without error just like the L1 construct CfnRule.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    LocalStack Cockpit

#### Stack for reproducing

```typescript
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { LogGroup, RetentionDays } from 'aws-cdk-lib/aws-logs'
import { EventBus, Rule, CfnRule } from 'aws-cdk-lib/aws-events'
import * as targets from 'aws-cdk-lib/aws-events-targets';
import { CfnOutput } from 'aws-cdk-lib'

export class CdkErrorStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // cloudwatch log group target
    const logGroup = new LogGroup(this, 'SomeEvents', {
      logGroupName: `/aws/events/some-events`,
      retention: RetentionDays.ONE_DAY
    });

    // eventbridge
    const bus = new EventBus(this, 'SomeEventBus', {
      eventBusName: `some-event-bus`
    });

    // Produces error
    new Rule(this, 'SomeEventsBusRule', {
      ruleName: `some-events-rule`,
      description: 'Rule matching some events',
      eventBus: bus,
      eventPattern: {
        source: ['some-source']
      },
      targets: [
        new targets.CloudWatchLogGroup(logGroup)
      ]
    });

    /* // No error produced
    new CfnRule(this, 'SomeEventsBusRule', {
      name: `some-events-rule`,
      eventBusName: bus.eventBusName,
      description: 'Rule matching some events',
      eventPattern: {
        source: ['some-source']
      },
      targets: [{
        id: `some-events-cw-logs`,
        arn: `arn:aws:logs:${logGroup.stack.region}:${logGroup.stack.account}:log-group:${logGroup.logGroupName}`
      }]
    });
    */
    
    new CfnOutput(this, 'LogGroupName', {
      value: logGroup.logGroupName,
      description: 'Name of the log group created to store events'
    });
  }
}
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
    mkdir cdk-error
    cd cdk-error
    cdk init app --language typescript
    cd cdk-error

    cdklocal bootstrap
    cdklocal deploy
    cdklocal destroy
    cdklocal deploy
    cdklocal destroy

### Environment

```markdown
- OS: MacOS Monterey 12.5.1
- LocalStack: 1.1.1.dev
- cdk CLI version: 2.43.0 (build 487870a)
- aws-cdk-lib version: 2.43.0
```

**Comment by jonathanswenson** [comment]
Ran into something similar, but not when using CDK. 

Have a rule that seems to continuously run (and throw this exception) every minute. 

```
2023-05-15 09:12:27 2023-05-15T16:12:27.189  INFO --- [thread903634] localstack.utils.threads   : Thread run method <function EventsProvider.get_scheduled_rule_func.<locals>.func at 0xffff6ecfb9a0>(None) failed: An error occurred (ResourceNotFoundException) when calling the ListTargetsByRule operation: Rule a299c9bf-c879-4cb6-803f-0d36a8d85028 does not exist. Traceback (most recent call last):
2023-05-15 09:12:27   File "/opt/code/localstack/localstack/utils/threads.py", line 58, in run
2023-05-15 09:12:27     result = self.func(self.params, **kwargs)
2023-05-15 09:12:27   File "/opt/code/localstack/localstack/services/events/provider.py", line 74, in func
2023-05-15 09:12:27     targets = client.list_targets_by_rule(Rule=rule_name)["Targets"]
2023-05-15 09:12:27   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
2023-05-15 09:12:27     return self._make_api_call(operation_name, kwargs)
2023-05-15 09:12:27   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
2023-05-15 09:12:27     raise error_class(parsed_response, operation_name)
2023-05-15 09:12:27 botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the ListTargetsByRule operation: Rule a299c9bf-c879-4cb6-803f-0d36a8d85028 does not exist.
2023-05-15 09:12:27 
```

Seems to be the only rule I have that does this.
