### ISSUE TITLE
bug: Unexpected error "Stack already exists" when deploying with cdklocal

### ISSUE THREAD

**Issue by aitouka21** [localstack/localstack#6961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Stack is stuck in REVIEW_IN_PROGRESS status after cdklocal deploy failed.

```
[nix-shell:~/local-stack-1]$ awslocal cloudformation list-stacks --region ap-southeast-1
{
    "StackSummaries": []
}

[nix-shell:~/local-stack-1]$ cdklocal bootstrap
 ⏳  Bootstrapping environment aws://000000000000/ap-southeast-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
CDKToolkit: creating CloudFormation changeset...
 ✅  Environment aws://000000000000/ap-southeast-1 bootstrapped.


[nix-shell:~/local-stack-1]$ cdklocal deploy

✨  Synthesis time: 4.38s

LocalStack1Stack: building assets...

[0%] start: Building 0e58bbcf7e4f2643911c8295c897a30a73f63b526da389eb36e485e2f8f12952:000000000000-ap-southeast-1
[100%] success: Built 0e58bbcf7e4f2643911c8295c897a30a73f63b526da389eb36e485e2f8f12952:000000000000-ap-southeast-1

LocalStack1Stack: assets built

This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

IAM Statement Changes
┌───┬─────────────────────────┬────────┬─────────────────┬───────────────────────────┬─────────────────────────────────────────────────────────┐
│   │ Resource                │ Effect │ Action          │ Principal                 │ Condition                                               │
├───┼─────────────────────────┼────────┼─────────────────┼───────────────────────────┼─────────────────────────────────────────────────────────┤
│ + │ ${LocalStack1Queue.Arn} │ Allow  │ sqs:SendMessage │ Service:sns.amazonaws.com │ "ArnEquals": {                                          │
│   │                         │        │                 │                           │   "aws:SourceArn": "${LocalStack1Topic}"                │
│   │                         │        │                 │                           │ }                                                       │
└───┴─────────────────────────┴────────┴─────────────────┴───────────────────────────┴─────────────────────────────────────────────────────────┘
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Do you wish to deploy these changes (y/n)? y
LocalStack1Stack: deploying...
[0%] start: Publishing 0e58bbcf7e4f2643911c8295c897a30a73f63b526da389eb36e485e2f8f12952:000000000000-ap-southeast-1
[100%] success: Published 0e58bbcf7e4f2643911c8295c897a30a73f63b526da389eb36e485e2f8f12952:000000000000-ap-southeast-1
LocalStack1Stack: creating CloudFormation changeset...

 ❌  LocalStack1Stack failed: Error [ValidationError]: Stack LocalStack1Stack already exists
    at Request.extractError (/home/user/.npm-global/lib/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/home/user/.npm-global/lib/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/user/.npm-global/lib/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/user/.npm-global/lib/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/home/user/.npm-global/lib/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/user/.npm-global/lib/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/user/.npm-global/lib/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/user/.npm-global/lib/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/user/.npm-global/lib/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/home/user/.npm-global/lib/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2022-10-02T14:10:54.942Z,
  requestId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 608.4892248195777
}

 ❌ Deployment failed: Error: Stack Deployments Failed: ValidationError: Stack LocalStack1Stack already exists
    at deployStacks (/home/user/.npm-global/lib/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/home/user/.npm-global/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:314:7)
    at initCommandLine (/home/user/.npm-global/lib/node_modules/aws-cdk/lib/cli.ts:357:12)

Stack Deployments Failed: ValidationError: Stack LocalStack1Stack already exists

[nix-shell:~/local-stack-1]$ awslocal cloudformation list-stacks --region ap-southeast-1
{
    "StackSummaries": [
        {
            "StackId": "arn:aws:cloudformation:ap-southeast-1:000000000000:stack/CDKToolkit/227a8928",
            "StackName": "CDKToolkit",
            "CreationTime": "2022-10-02T14:09:32.203000+00:00",
            "LastUpdatedTime": "2022-10-02T14:09:32.203000+00:00",
            "StackStatus": "CREATE_COMPLETE",
            "DriftInformation": {
                "StackDriftStatus": "NOT_CHECKED"
            }
        },
        {
            "StackId": "arn:aws:cloudformation:ap-southeast-1:000000000000:stack/LocalStack1Stack/1ec9031f",
            "StackName": "LocalStack1Stack",
            "CreationTime": "2022-10-02T14:10:54.101000+00:00",
            "LastUpdatedTime": "2022-10-02T14:10:54.101000+00:00",
            "StackStatus": "REVIEW_IN_PROGRESS",
            "DriftInformation": {
                "StackDriftStatus": "NOT_CHECKED"
            }
        }
    ]
}
```

ParameterNotFound is expected, but throwing `Deployment failed: Error: Stack Deployments Failed: ValidationError: Stack LocalStack1Stack already exists` instead.
```
2022-10-02T14:10:54.110 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: An error occurred (ParameterNotFound) when calling the GetParameter operation: Parameter non-existing-parameter not found.
2022-10-02T14:10:54.110  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.CreateChangeSet => 500 (InternalError)
2022-10-02T14:10:54.940  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.GetObject => 200
2022-10-02T14:10:54.941  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.CreateChangeSet => 400 (ValidationError)
```

### Expected Behavior

Once deployment failed, stack status should be changed to CREATE_FAILED.

### How are you starting LocalStack?

With a `docker run` command

### starting localstack
```
docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack
```
### cdk app
Created by `cdklocal init sample-app --language=typescript`
```
// bin/local-stack-1.ts
import { LocalStack1Stack } from "../lib/local-stack-1-stack";

const app = new cdk.App();
new LocalStack1Stack(app, "LocalStack1Stack", {
  env: {
    account: "000000000000",
    region: "ap-southeast-1",
  },
});

```
```
// lib/local-stack-1-stack.ts
import { Duration, Stack, StackProps } from "aws-cdk-lib";
import * as sns from "aws-cdk-lib/aws-sns";
import * as subs from "aws-cdk-lib/aws-sns-subscriptions";
import * as sqs from "aws-cdk-lib/aws-sqs";
import { Construct } from "constructs";
import * as ssm from "aws-cdk-lib/aws-ssm";

export class LocalStack1Stack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    const ssmParameter = ssm.StringParameter.valueForStringParameter(
      this,
      "non-existing-parameter"
    );

    const queue = new sqs.Queue(this, "LocalStack1Queue", {
      visibilityTimeout: Duration.seconds(300),
    });

    const topic = new sns.Topic(this, "LocalStack1Topic");

    topic.addSubscription(new subs.SqsSubscription(queue));
  }
}

```

### Environment

```markdown
- OS: Ubuntu 20.04, NixOS 22.05
- LocalStack: 1.1.1.dev
```

**Comment by whummer** [comment]
Hi @chomamaTheBest, thanks for reporting. It looks like your stack is depending on an SSM parameter here:
```
    const ssmParameter = ssm.StringParameter.valueForStringParameter(
      this,
      "non-existing-parameter"
    );
```

As this parameter is missing, we're seeing the following exception during deployment: 
```
2022-10-02T14:10:54.110 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: An error occurred (ParameterNotFound) when calling the GetParameter operation: Parameter non-existing-parameter not found.
```

Can you try creating this parameter in LocalStack SSM, and then deploy the stack again? Thanks

**Comment by chomamaTheBest** [comment]
> Hi @chomamaTheBest, thanks for reporting. It looks like your stack is depending on an SSM parameter here:
> 
> ```
>     const ssmParameter = ssm.StringParameter.valueForStringParameter(
>       this,
>       "non-existing-parameter"
>     );
> ```
> 
> As this parameter is missing, we're seeing the following exception during deployment:
> 
> ```
> 2022-10-02T14:10:54.110 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: An error occurred (ParameterNotFound) when calling the GetParameter operation: Parameter non-existing-parameter not found.
> ```
> 
> Can you try creating this parameter in LocalStack SSM, and then deploy the stack again? Thanks

I did that purposely. I did the same thing on both cdk and cdklocal but I got different results.
cdk:
```
❌ Deployment failed: Error: Stack Deployments Failed: ValidationError: Unable to fetch parameters [non-existing-parameter] from parameter store for this account.
    at deployStacks (/home/user/.npm-global/lib/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/home/user/.npm-global/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:314:7)
    at initCommandLine (/home/user/.npm-global/lib/node_modules/aws-cdk/lib/cli.ts:357:12)

Stack Deployments Failed: ValidationError: Unable to fetch parameters [non-existing-parameter] from parameter store for this account.
```
cdklocal:
```
❌ Deployment failed: Error: Stack Deployments Failed: ValidationError: Stack LocalStack1Stack already exists
    at deployStacks (/home/user/.npm-global/lib/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/home/user/.npm-global/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:314:7)
    at initCommandLine (/home/user/.npm-global/lib/node_modules/aws-cdk/lib/cli.ts:357:12)

Stack Deployments Failed: ValidationError: Stack LocalStack1Stack already exists
```
I have created the SSM parameter and then it still keeps throwing ChangeSetNotFound unless I restart localstack and deploy the stack again.
```
 ❌ Deployment failed: Error: Stack Deployments Failed: ChangeSetNotFound: ChangeSet [cdk-deploy-change-set] does not exist
    at deployStacks (/home/user/.npm-global/lib/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/home/user/.npm-global/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:314:7)
    at initCommandLine (/home/user/.npm-global/lib/node_modules/aws-cdk/lib/cli.ts:357:12)

Stack Deployments Failed: ChangeSetNotFound: ChangeSet [cdk-deploy-change-set] does not exist
```

```
2022-10-05T01:18:39.279  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DeleteChangeSet => 404 (ChangeSetNotFound)
```

```
awslocal cloudformation list-change-sets --stack-name LocalStack1Stack --region ap-southeast-1
{
    "Summaries": []
}
```

**Comment by dominikschubert** [comment]
Hi @aitouka21 ! Could you please try to pull the latest image and see if this errors has been resolved? We've fixed a few related issues in the past months.

Thanks!
