### ISSUE TITLE
bug: Cannot start localstack directly on the host

### ISSUE THREAD

**Issue by jhulme-ut** [localstack/localstack#6979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I install localstack via Pip, I then try and start it without docker: `localstack start --host`
I get an error complaining that it can't find the moto package
```
➜  ~ localstack start --help
Usage: localstack start [OPTIONS]

  Start LocalStack

Options:
  --docker        Start LocalStack in a docker container (default)
  --host          Start LocalStack directly on the host
  --no-banner     Disable LocalStack banner
  -d, --detached  Start LocalStack in the background
  --help          Show this message and exit.
➜  ~ localstack start --host

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 1.1.0

[16:20:19] starting LocalStack in host mode 💻                                                                                                                                               localstack.py:137
─────────────────────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/usr/local/bin/localstack", line 23, in <module>
    main()
  File "/usr/local/bin/localstack", line 19, in main
    main.main()
  File "/usr/local/lib/python3.10/site-packages/localstack/cli/main.py", line 6, in main
    cli()
  File "/usr/local/lib/python3.10/site-packages/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/localstack/utils/analytics/cli.py", line 66, in publisher_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/localstack/cli/localstack.py", line 147, in cmd_start
    bootstrap.start_infra_locally()
  File "/usr/local/lib/python3.10/site-packages/localstack/utils/bootstrap.py", line 258, in start_infra_locally
    from localstack.services import infra
  File "/usr/local/lib/python3.10/site-packages/localstack/services/infra.py", line 13, in <module>
    from moto.core import BaseModel
ModuleNotFoundError: No module named 'moto'
➜  ~
```

### Expected Behavior

Localstack starts

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start --host

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    n/a

### Environment

```markdown
- OS: macOS 12.6 (21G115)
- LocalStack: 1.1.0
```

### Anything else?

The output of the install:
```
➜  ~ python3 -m pip install localstack
Collecting localstack
  Using cached localstack-1.1.0-py3-none-any.whl (1.1 MB)
Collecting tailer>=0.4.1
  Using cached tailer-0.4.1-py3-none-any.whl
Collecting requests<2.26,>=2.20.0
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting semver>=2.10
  Using cached semver-2.13.0-py2.py3-none-any.whl (12 kB)
Collecting apispec>=5.1.1
  Using cached apispec-5.2.2-py3-none-any.whl (29 kB)
Collecting stevedore>=3.4.0
  Using cached stevedore-4.0.0-py3-none-any.whl (49 kB)
Collecting cachetools~=5.0.0
  Using cached cachetools-5.0.0-py3-none-any.whl (9.1 kB)
Collecting python-dotenv>=0.19.1
  Using cached python_dotenv-0.21.0-py3-none-any.whl (18 kB)
Collecting click>=7.0
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting localstack-ext==1.1.0
  Using cached localstack_ext-1.1.0-py3-none-any.whl
Collecting boto3>=1.20
  Using cached boto3-1.24.86-py3-none-any.whl (132 kB)
Collecting plux>=1.3.1
  Using cached plux-1.3.1-py3-none-any.whl (19 kB)
Collecting psutil<6.0.0,>=5.4.8
  Using cached psutil-5.9.2-cp310-cp310-macosx_10_9_x86_64.whl (239 kB)
Collecting pyyaml>=5.1
  Using cached PyYAML-6.0-cp310-cp310-macosx_10_9_x86_64.whl (197 kB)
Collecting rich>=12.3.0
  Using cached rich-12.6.0-py3-none-any.whl (237 kB)
Collecting localstack-client>=1.37
  Using cached localstack_client-1.39-py3-none-any.whl
Collecting tabulate
  Using cached tabulate-0.8.10-py3-none-any.whl (29 kB)
Collecting dnspython>=1.16.0
  Using cached dnspython-2.2.1-py3-none-any.whl (269 kB)
Collecting pyaes>=1.6.0
  Using cached pyaes-1.6.1-py3-none-any.whl
Collecting dill==0.3.2
  Using cached dill-0.3.2-py3-none-any.whl
Collecting dnslib>=0.9.10
  Using cached dnslib-0.9.22-py3-none-any.whl (59 kB)
Collecting python-jose[cryptography]<4.0.0,>=3.1.0
  Using cached python_jose-3.3.0-py2.py3-none-any.whl (33 kB)
Collecting localstack
  Using cached localstack-1.1.1.dev20220926183749-py3-none-any.whl (1.1 MB)
Collecting botocore<1.28.0,>=1.27.86
  Using cached botocore-1.27.86-py3-none-any.whl (9.2 MB)
Collecting s3transfer<0.7.0,>=0.6.0
  Using cached s3transfer-0.6.0-py3-none-any.whl (79 kB)
Collecting jmespath<2.0.0,>=0.7.1
  Using cached jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
Collecting pygments<3.0.0,>=2.6.0
  Using cached Pygments-2.13.0-py3-none-any.whl (1.1 MB)
Collecting commonmark<0.10.0,>=0.9.0
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting pbr!=2.1.0,>=2.0.0
  Using cached pbr-5.10.0-py2.py3-none-any.whl (112 kB)
Collecting python-dateutil<3.0.0,>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting ecdsa!=0.15
  Using cached ecdsa-0.18.0-py2.py3-none-any.whl (142 kB)
Collecting rsa
  Using cached rsa-4.9-py3-none-any.whl (34 kB)
Collecting pyasn1
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting cryptography>=3.4.0
  Using cached cryptography-38.0.1-cp36-abi3-macosx_10_10_x86_64.whl (2.8 MB)
Collecting cffi>=1.12
  Using cached cffi-1.15.1-cp310-cp310-macosx_10_9_x86_64.whl (179 kB)
Collecting six>=1.9.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Installing collected packages: tailer, pyasn1, pyaes, dnslib, commonmark, urllib3, tabulate, six, semver, rsa, pyyaml, python-dotenv, pygments, pycparser, psutil, pbr, jmespath, idna, dnspython, dill, click, chardet, certifi, cachetools, apispec, stevedore, rich, requests, python-dateutil, ecdsa, cffi, python-jose, plux, cryptography, botocore, s3transfer, boto3, localstack-client, localstack-ext, localstack
Successfully installed apispec-5.2.2 boto3-1.24.86 botocore-1.27.86 cachetools-5.0.0 certifi-2022.9.24 cffi-1.15.1 chardet-4.0.0 click-8.1.3 commonmark-0.9.1 cryptography-38.0.1 dill-0.3.2 dnslib-0.9.22 dnspython-2.2.1 ecdsa-0.18.0 idna-2.10 jmespath-1.0.1 localstack-1.1.0 localstack-client-1.39 localstack-ext-1.1.0 pbr-5.10.0 plux-1.3.1 psutil-5.9.2 pyaes-1.6.1 pyasn1-0.4.8 pycparser-2.21 pygments-2.13.0 python-dateutil-2.8.2 python-dotenv-0.21.0 python-jose-3.3.0 pyyaml-6.0 requests-2.25.1 rich-12.6.0 rsa-4.9 s3transfer-0.6.0 semver-2.13.0 six-1.16.0 stevedore-4.0.0 tabulate-0.8.10 tailer-0.4.1 urllib3-1.26.12
➜  ~
```

It does not mention moto.  If i install moto via pip then it complains about flask_cors

**Comment by whummer** [comment]
Hi @jhulme-ut , can you please try installing the `runtime` extra:
```
python3 -m pip install 'localstack[runtime]'
```
Please note that we do not officially support running LocalStack on the host - the preferred way to start up is inside Docker. This simplifies things for us, as we can rely on having a unified environment - otherwise debugging the different operating systems, user permissions, network settings etc on users' host machines simply becomes too difficult.

Hope it works! Please keep us posted... Thanks
