### ISSUE TITLE
bug: LocalStack 1.2.0 - Unable to start when behind corporate proxy w/ Custom CA

### ISSUE THREAD

**Issue by driverpt** [localstack/localstack#7000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently it's looping this error

```
LocalStack version: 1.2.0
LocalStack build date: 2022-10-07
LocalStack build git hash: 9be2a7aa

Error starting infrastructure: Installation of kinesis-mock failed. Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: MyHTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/etspaceman/kinesis-mock/releases/tags/0.2.5 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
```

### Expected Behavior

every call to work properly

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Test Containers Go

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

DynamoDb Connection:

```
        	Error:      	Received unexpected error:
        	            	operation error DynamoDB: CreateTable, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Post "http://localhost:53740/": EOF

```

### Environment

```markdown
- OS: MacOS
- LocalStack: 1.2.0
```

**Comment by thrau** [comment]
@driverpt thanks for reporting. are you using kinesis, or just dynamodb?

---

this may be due to the installer refactoring, where we now require a call to the github API to scrape the available versions. :eyes: @alexrashed, any ideas how we could address this?

* i understand the API call is now an integral part of the installer, but maybe we don't really need it?
* this may be a good opportunity to make localstack more fault tolerant towards installer errors. i guess we don't really need to retry forever, but just bail after a while. the service won't start up but if it's not needed :shrug:

**Comment by driverpt** [comment]
Hey @thrau , I'm using DynamoDb

**Comment by alexrashed** [comment]
Hey @driverpt!
Sorry for the inconvenience. I just merged a PR which should fix the issue.
As soon as the pipeline on our main branch ran through, the latest image contains the fix.
Please let us know if you still experience any issues.
Thanks!

**Comment by driverpt** [comment]
Hey folks,

Is there any ETA for this one?

**Comment by alexrashed** [comment]
Hi @driverpt!
The issue should already be fixed in the `latest` image of LocalStack.
The next tagged release will be `1.3.0` which is tracked in #7197. It will be created by the end of next week.
