### ISSUE TITLE
bug: Lambda function URL's don't work

### ISSUE THREAD

**Issue by TatoExp** [localstack/localstack#7009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I create a lambda function with function URL following the tutorial from https://docs.aws.amazon.com/lambda/latest/dg/urls-tutorial.html

However, I am using node 12.x rather than 14.x.

The lambda doesn't work, I have enabled CORS and debug mode and it appears I get a TypeError from python.

`--- Logging error ---
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1131, in json_or_eval
    return json.loads(body)
  File "/usr/local/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not Response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1134, in json_or_eval
    return ast.literal_eval(body)
  File "/usr/local/lib/python3.10/ast.py", line 108, in literal_eval
    return _convert(node_or_string)
  File "/usr/local/lib/python3.10/ast.py", line 107, in _convert
    return _convert_signed_num(node)
  File "/usr/local/lib/python3.10/ast.py", line 81, in _convert_signed_num
    return _convert_num(node)
  File "/usr/local/lib/python3.10/ast.py", line 72, in _convert_num
    _raise_malformed_node(node)
  File "/usr/local/lib/python3.10/ast.py", line 69, in _raise_malformed_node
    raise ValueError(msg + f': {node!r}')
ValueError: malformed node or string: <Response 114 bytes [500 INTERNAL SERVER ERROR]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/code/localstack/localstack/aws/serving/wsgi.py", line 50, in __call__
    self.gateway.process(request, response)
  File "/opt/code/localstack/localstack/aws/gateway.py", line 36, in process
    chain.handle(context, response)
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/routes.py", line 27, in __call__
    router_response = self.router.dispatch(context.request)
  File "/opt/code/localstack/localstack/http/router.py", line 234, in dispatch
    return self.dispatcher(request, handler, args)
  File "/opt/code/localstack/localstack/http/dispatcher.py", line 123, in _dispatch
    result = endpoint(request, **args)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1125, in handle_lambda_url_invocation
    response = lambda_result_to_response(result)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1155, in lambda_result_to_response
    parsed_result = json_or_eval(result) or {}
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1136, in json_or_eval
    LOG.error(f"Error parsing {body}", e)`

I can see that the function has been successfully invoked by using logging, and that the response is correct. But I am only returned a 200 with a empty object body of `{}`

### Expected Behavior

The function url should return the specified response body.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

Run localstack with `EXTRA_CORS_ALLOWED_ORIGINS="*" DEBUG=1 localstack start -d`
Follow the AWS guide above.

### Environment

```markdown
- OS: MacOS 12.6 M1 Pro
- LocalStack: latest
```

**Comment by HarshCasper** [comment]
Hi 👋 

We have a Lambda Function URL sample here for NodeJS: https://github.com/localstack/localstack-pro-samples/tree/master/lambda-function-urls/javascript

I decided to give it a run with Node.js 12.x and it didn't show me any potential errors. The tutorial has been implemented by following the AWS guide and is expected to work. Can you please pull the latest LocalStack Docker image and give this a run? 

I am closing this issue now but feel free to ping us here or create a new issue if the issue still persists!
