### ISSUE TITLE
Not able to install on Mac High Sierra

### ISSUE THREAD

**Issue by sincerekamal** [localstack/localstack#701]
I tried running 
`pip install localstack`
`pip install --user localstack`
`pip install --user --no-cache localstack`

All I get is the below error,

````
Collecting localstack
  Using cached localstack-0.8.6.tar.gz
Collecting airspeed==0.5.5.dev20160812 (from localstack)
  Using cached airspeed-0.5.5.dev20160812.tar.gz
Collecting awscli>=1.14.18 (from localstack)
  Using cached awscli-1.14.69-py2.py3-none-any.whl
Collecting boto==2.46.1 (from localstack)
  Using cached boto-2.46.1-py2.py3-none-any.whl
Collecting boto3>=1.4.4 (from localstack)
  Using cached boto3-1.6.22-py2.py3-none-any.whl
Collecting coverage==4.0.3 (from localstack)
  Using cached coverage-4.0.3-cp27-none-macosx_10_10_x86_64.whl
Collecting docopt==0.6.2 (from localstack)
  Using cached docopt-0.6.2.tar.gz
Collecting elasticsearch==6.2.0 (from localstack)
  Using cached elasticsearch-6.2.0-py2.py3-none-any.whl
Collecting flake8>=3.5.0 (from localstack)
  Using cached flake8-3.5.0-py2.py3-none-any.whl
Collecting flake8-quotes>=0.11.0 (from localstack)
  Using cached flake8-quotes-0.14.1.tar.gz
Collecting flask==0.10.1 (from localstack)
  Using cached Flask-0.10.1.tar.gz
Collecting flask-cors==3.0.3 (from localstack)
  Using cached Flask_Cors-3.0.3-py2.py3-none-any.whl
Collecting flask_swagger==0.2.12 (from localstack)
  Using cached flask-swagger-0.2.12.tar.gz
Collecting jsonpath-rw==1.4.0 (from localstack)
  Using cached jsonpath-rw-1.4.0.tar.gz
Collecting localstack-ext>=0.8.1 (from localstack)
  Using cached localstack-ext-0.8.1.tar.gz
Collecting localstack-client==0.4 (from localstack)
  Using cached localstack-client-0.4.tar.gz
Collecting moto-ext==1.2.0 (from localstack)
  Using cached moto_ext-1.2.0-py2.py3-none-any.whl
Collecting nose==1.3.7 (from localstack)
  Using cached nose-1.3.7-py2-none-any.whl
Collecting psutil==5.4.3 (from localstack)
  Using cached psutil-5.4.3.tar.gz
Collecting pyOpenSSL==17.0.0 (from localstack)
  Using cached pyOpenSSL-17.0.0-py2.py3-none-any.whl
Collecting python-coveralls==2.7.0 (from localstack)
  Using cached python_coveralls-2.7.0-py2.py3-none-any.whl
Collecting pyYAML==3.12 (from localstack)
  Using cached PyYAML-3.12.tar.gz
Collecting requests==2.18.4 (from localstack)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting requests-aws4auth==0.9 (from localstack)
  Using cached requests_aws4auth-0.9-py2.py3-none-any.whl
Collecting six==1.10.0 (from localstack)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting subprocess32-ext==3.2.8.2 (from localstack)
  Using cached subprocess32-ext-3.2.8.2.tar.gz
Collecting xmltodict==0.10.2 (from localstack)
  Using cached xmltodict-0.10.2.tar.gz
Collecting cachetools==0.8.0 (from airspeed==0.5.5.dev20160812->localstack)
  Using cached cachetools-0.8.0-py2.py3-none-any.whl
Collecting colorama<=0.3.7,>=0.2.5 (from awscli>=1.14.18->localstack)
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting docutils>=0.10 (from awscli>=1.14.18->localstack)
  Using cached docutils-0.14-py2-none-any.whl
Collecting rsa<=3.5.0,>=3.1.2 (from awscli>=1.14.18->localstack)
  Using cached rsa-3.4.2-py2.py3-none-any.whl
Collecting botocore==1.9.22 (from awscli>=1.14.18->localstack)
  Using cached botocore-1.9.22-py2.py3-none-any.whl
Collecting s3transfer<0.2.0,>=0.1.12 (from awscli>=1.14.18->localstack)
  Using cached s3transfer-0.1.13-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from boto3>=1.4.4->localstack)
  Using cached jmespath-0.9.3-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from elasticsearch==6.2.0->localstack)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting pyflakes<1.7.0,>=1.5.0 (from flake8>=3.5.0->localstack)
  Using cached pyflakes-1.6.0-py2.py3-none-any.whl
Collecting enum34; python_version < "3.4" (from flake8>=3.5.0->localstack)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting configparser; python_version < "3.2" (from flake8>=3.5.0->localstack)
  Using cached configparser-3.5.0.tar.gz
Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8>=3.5.0->localstack)
  Using cached pycodestyle-2.3.1-py2.py3-none-any.whl
Collecting mccabe<0.7.0,>=0.6.0 (from flake8>=3.5.0->localstack)
  Using cached mccabe-0.6.1-py2.py3-none-any.whl
Collecting Werkzeug>=0.7 (from flask==0.10.1->localstack)
  Using cached Werkzeug-0.14.1-py2.py3-none-any.whl
Collecting Jinja2>=2.4 (from flask==0.10.1->localstack)
  Using cached Jinja2-2.10-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from flask==0.10.1->localstack)
  Using cached itsdangerous-0.24.tar.gz
Collecting ply (from jsonpath-rw==1.4.0->localstack)
  Using cached ply-3.11-py2.py3-none-any.whl
Collecting decorator (from jsonpath-rw==1.4.0->localstack)
  Using cached decorator-4.2.1-py2.py3-none-any.whl
Collecting dnslib==0.9.7 (from localstack-ext>=0.8.1->localstack)
  Using cached dnslib-0.9.7.tar.gz
Collecting pyaes==1.6.0 (from localstack-ext>=0.8.1->localstack)
  Using cached pyaes-1.6.0.tar.gz
Collecting pyminifier==2.1 (from localstack-ext>=0.8.1->localstack)
  Using cached pyminifier-2.1.tar.gz
Collecting srp-ext==1.0.7.1 (from localstack-ext>=0.8.1->localstack)
  Using cached srp-ext-1.0.7.1.tar.gz
Collecting warrant-ext>=0.2.0.5 (from localstack-ext>=0.8.1->localstack)
  Using cached warrant-ext-0.2.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4y/_j2x8jg92257cth8yvmvyw9w0000gn/T/pip-install-J9tcNT/warrant-ext/setup.py", line 4, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4y/_j2x8jg92257cth8yvmvyw9w0000gn/T/pip-install-J9tcNT/warrant-ext/


````

**My System config:**

NPM: 5.8.0
Java: 1.8
MVN: 3.5.3
Make: GNU Make 3.81
pip: 10.0.0b2

**Comment by bhaskar20001** [comment]
Prefer running it in virtual environment. 

try running the following commands,
>> make install
>> make infra
