### ISSUE TITLE
bug: Cloudformation doesn't create s3 bucket

### ISSUE THREAD

**Issue by gavinvangent** [localstack/localstack#7048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was happily building and deploying a serverless app to localstack running in docker, went away for a couple hours, came back and tried to deploy it again without making changes, and it failed, repeatedly ... Long story short, when i start the localstack container, i start it with `:latest`. Didn't notice it fetched a new image and then started the container. I eventually tried to get an older image and noticed a new version was uploaded 4 hours ago (in the time that i was AFK). Used image 1.2.0, and no errors when deploying my stack. Went back to the `:latest` image and failed to deploy.

Here's a breakdown of what I get. From serverless:

```sh
Serverless: Stack create finished...
Serverless: Ensuring that deployment bucket exists
Serverless: [AWS cloudformation 200 0.017s 0 retries] describeStackResource({
  StackName: 'my-serverless-dev',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: [AWS s3 404 0.032s 0 retries] headBucket({ Bucket: 'my-serverless-dev-serverlessdeploymentbuck-9b742ad4' })
 
 Serverless Error ----------------------------------------
 
  ServerlessError: Deployment bucket has been removed manually. Please recreate it or remove your service and attempt to deploy it again
      at AwsDeploy.ensureValidBucketExists (/Users/me/src/my-sls/node_modules/serverless/lib/plugins/aws/deploy/lib/ensure-valid-bucket-exists.js:57:15)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async aws:deploy:deploy:checkForChanges (/Users/me/src/my-sls/node_modules/serverless/lib/plugins/aws/deploy/index.js:127:9)
      at async PluginManager.runHooks (/Users/me/src/my-sls/node_modules/serverless/lib/classes/PluginManager.js:601:35)
```

when i describe the stack events:

```sh
>  aws --endpoint-url http://localhost:4566 --region us-east-1 cloudformation describe-stack-events --stack-name my-serverless-dev
{
    "StackEvents": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/my-serverless-dev/d35247e1",
            "EventId": "3d8fcded-f4d8-4c9c-9513-5324658f61a1",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "my-serverless-dev",
            "PhysicalResourceId": "arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/my-serverless-dev/d35247e1",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:31:01.797000Z",
            "ResourceStatus": "CREATE_COMPLETE"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/my-serverless-dev/d35247e1",
            "EventId": "a5de2665-a0c0-4bd5-bb43-495975e4f64f",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "ServerlessDeploymentBucketPolicy",
            "PhysicalResourceId": "d6a39e8c071b8eaf86b809136de5dcf5",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:31:01.797000Z",
            "ResourceStatus": "CREATE_COMPLETE"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/my-serverless-dev/d35247e1",
            "EventId": "1b4acbf5-79aa-4274-bc86-4a65288a2630",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "ServerlessDeploymentBucket",
            "PhysicalResourceId": "my-serverless-dev-serverlessdeploymentbuck-9b742ad4",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:31:01.611000Z",
            "ResourceStatus": "CREATE_COMPLETE"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/my-serverless-dev/d35247e1",
            "EventId": "0b51aeb4-a31b-4ec4-893b-01b7962f9d31",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "ServerlessDeploymentBucketPolicy",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:31:00.687000Z",
            "ResourceStatus": "UPDATE_IN_PROGRESS"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/my-serverless-dev/d35247e1",
            "EventId": "7d59324f-5a21-4ac4-9368-fee2965fe6e1",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "ServerlessDeploymentBucket",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:31:00.687000Z",
            "ResourceStatus": "UPDATE_IN_PROGRESS"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/my-serverless-dev/d35247e1",
            "EventId": "97ace66f-1db0-4260-a189-aeea46d03308",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "my-serverless-dev",
            "PhysicalResourceId": "arn:aws:cloudformation:us-east-1:XXXXXXXXXXXX:stack/my-serverless-dev/d35247e1",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:31:00.686000Z",
            "ResourceStatus": "CREATE_IN_PROGRESS"
        }
    ]
}
```

However, when i list buckets, i get an empty array:

```sh
>  aws --endpoint-url http://localhost:4566 s3api list-buckets
{
    "Buckets": [],
    "Owner": {
        "DisplayName": "webfile",
        "ID": "bcaf1ffd86f41161ca5fb16fd081034f"
    }
}

>  aws --endpoint-url http://localhost:4566 s3api list-buckets --region us-east-1
{
    "Buckets": [],
    "Owner": {
        "DisplayName": "webfile",
        "ID": "bcaf1ffd86f41161ca5fb16fd081034f"
    }
}
```

Here's the localstack logs:

```sh
LocalStack version: 1.2.1.dev
LocalStack Docker container id: 9982e477bdff
LocalStack build date: 2022-10-19
LocalStack build git hash: 02e6c027

...

Ready.
2022-10-19T21:30:43.902 DEBUG --- [  MainThread] l.extensions.platform      : calling extensions on_platform_ready
2022-10-19T21:30:50.122 DEBUG --- [uest_thread)] l.services.dns_server      : Determined fallback dns: 192.168.65.5
2022-10-19T21:30:58.653 DEBUG --- [   asgi_gw_0] l.services.plugins         : checking service health sts:4566
2022-10-19T21:30:58.745  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS sts.GetCallerIdentity => 200
2022-10-19T21:31:00.587  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "_load_service_plugin" took 1811.29ms
2022-10-19T21:31:00.589 DEBUG --- [   asgi_gw_0] l.services.plugins         : checking service health cloudformation:4566
2022-10-19T21:31:00.590  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "require" took 1813.73ms
2022-10-19T21:31:00.671  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 400 (ValidationError)
2022-10-19T21:31:00.686 DEBUG --- [   asgi_gw_0] l.s.c.provider             : Creating stack "my-serverless-dev" with 2 resources ...
2022-10-19T21:31:00.688  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.CreateStack => 200
2022-10-19T21:31:01.078  INFO --- [functhread17] botocore.credentials       : Found credentials in environment variables.
2022-10-19T21:31:01.278  INFO --- [functhread20] l.services.motoserver      : starting moto server on http://0.0.0.0:47283
2022-10-19T21:31:01.280  INFO --- [   asgi_gw_0] localstack.services.infra  : Starting mock S3 service on http ports 443/4566 ...
2022-10-19T21:31:01.571 DEBUG --- [functhread17] l.u.c.template_deployer    : Handling "Add" for resource "ServerlessDeploymentBucket" (1/2) type "AWS::S3::Bucket" in loop iteration 1 (should_deploy=True)
2022-10-19T21:31:01.572 DEBUG --- [functhread17] l.u.c.template_deployer    : Running action "create" for resource type "S3::Bucket" id "ServerlessDeploymentBucket"
2022-10-19T21:31:01.755 DEBUG --- [functhread17] l.u.c.template_deployer    : Handling "Add" for resource "ServerlessDeploymentBucketPolicy" (1/1) type "AWS::S3::BucketPolicy" in loop iteration 1 (should_deploy=True)
2022-10-19T21:31:01.769 DEBUG --- [functhread17] l.u.c.template_deployer    : Running action "create" for resource type "S3::BucketPolicy" id "ServerlessDeploymentBucketPolicy"
2022-10-19T21:31:01.771 DEBUG --- [functhread17] l.u.c.template_deployer    : Request for resource type "S3::BucketPolicy" in region us-east-1: put_bucket_policy {'Policy': '{"Statement": [{"Action": "s3:*", "Effect": "Deny", "Principal": "*", "Resource": ["arn:aws:s3:::my-serverless-dev-serverlessdeploymentbuck-9b742ad4/*", "arn:aws:s3:::my-serverless-dev-serverlessdeploymentbuck-9b742ad4"], "Condition": {"Bool": {"aws:SecureTransport": false}}}]}', 'Bucket': 'my-serverless-dev-serverlessdeploymentbuck-9b742ad4'}
2022-10-19T21:31:05.719  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2022-10-19T21:31:05.740  WARN --- [   asgi_gw_0] l.aws.protocol.serializer  : Response object StackResourceDetail contains a member which is not specified: Timestamp
2022-10-19T21:31:05.740  WARN --- [   asgi_gw_0] l.aws.protocol.serializer  : Response object StackResourceDetail contains a member which is not specified: PreviousResourceStatus
2022-10-19T21:31:05.742  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStackResource => 200
2022-10-19T21:31:05.782  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.HeadBucket => 404 (404)
```

### Expected Behavior

Performing the same actions in 1.2.0, i get:

```sh
Serverless: Stack create finished...
Serverless: Ensuring that deployment bucket exists
Serverless: [AWS cloudformation 200 0.013s 0 retries] describeStackResource({
  StackName: 'my-serverless-dev',
  LogicalResourceId: 'ServerlessDeploymentBucket'
})
Serverless: [AWS s3 200 0.02s 0 retries] headBucket({ Bucket: 'my-serverless-dev-serverlessdeploymentbuck-442dc8a7' })
Serverless: [AWS s3 200 0.028s 0 retries] listObjectsV2({
  Bucket: 'my-serverless-dev-serverlessdeploymentbuck-442dc8a7',
  Prefix: 'serverless/my-serverless/dev'
})
```

when i describe the stack events:

```sh
>  aws --endpoint-url http://localhost:4566 --region us-east-1 cloudformation describe-stack-events --stack-name my-serverless-dev
{
    "StackEvents": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-serverless-dev/f4fd431c",
            "EventId": "5580cf74-0022-4d01-8d8e-387bbd703278",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "my-serverless-dev",
            "PhysicalResourceId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-serverless-dev/f4fd431c",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:54:33.122000Z",
            "ResourceStatus": "UPDATE_COMPLETE"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-serverless-dev/f4fd431c",
            "EventId": "2bd80a27-de80-4dd8-837e-dab91c790852",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "ServerlessDeploymentBucketPolicy",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:54:32.571000Z",
            "ResourceStatus": "UPDATE_COMPLETE"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-serverless-dev/f4fd431c",
            "EventId": "f4475c01-6e42-4e6c-aa8f-370016e47a3d",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "ServerlessDeploymentBucket",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:54:32.358000Z",
            "ResourceStatus": "UPDATE_COMPLETE"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-serverless-dev/f4fd431c",
            "EventId": "d33120c3-fbca-4e33-b235-b3a0ec91e852",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "ServerlessDeploymentBucketPolicy",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:54:27.892000Z",
            "ResourceStatus": "UPDATE_IN_PROGRESS"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-serverless-dev/f4fd431c",
            "EventId": "ba350ae4-84c2-4583-b28b-acc4806c6e1b",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "ServerlessDeploymentBucket",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:54:27.892000Z",
            "ResourceStatus": "UPDATE_IN_PROGRESS"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-serverless-dev/f4fd431c",
            "EventId": "0ca186cf-a15d-47ff-9a8c-c1b962d38c57",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "my-serverless-dev",
            "PhysicalResourceId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-serverless-dev/f4fd431c",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:54:27.892000Z",
            "ResourceStatus": "UPDATE_IN_PROGRESS"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-serverless-dev/f4fd431c",
            "EventId": "c9d1f969-7ec0-4fe1-8642-591d5f387745",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "my-serverless-dev",
            "PhysicalResourceId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-serverless-dev/f4fd431c",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:54:23.628000Z",
            "ResourceStatus": "CREATE_COMPLETE"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-serverless-dev/f4fd431c",
            "EventId": "739df106-2659-45ad-bc29-0fe060271c66",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "ServerlessDeploymentBucketPolicy",
            "PhysicalResourceId": "a8073b16259416bb8dc3866199aefda3",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:54:23.628000Z",
            "ResourceStatus": "CREATE_COMPLETE"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-serverless-dev/f4fd431c",
            "EventId": "3bb78e84-633e-42b2-9322-63079b7ea188",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "ServerlessDeploymentBucket",
            "PhysicalResourceId": "my-serverless-dev-serverlessdeploymentbuck-442dc8a7",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:54:23.248000Z",
            "ResourceStatus": "CREATE_COMPLETE"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-serverless-dev/f4fd431c",
            "EventId": "14a98091-130a-44c8-8704-bcacb8151680",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "ServerlessDeploymentBucketPolicy",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:54:22.693000Z",
            "ResourceStatus": "UPDATE_IN_PROGRESS"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-serverless-dev/f4fd431c",
            "EventId": "ebe831f0-5cb0-4829-9d92-818f0a0c7a02",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "ServerlessDeploymentBucket",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:54:22.693000Z",
            "ResourceStatus": "UPDATE_IN_PROGRESS"
        },
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-serverless-dev/f4fd431c",
            "EventId": "f1fc00e9-cbc7-415e-980e-c7b75bf51b09",
            "StackName": "my-serverless-dev",
            "LogicalResourceId": "my-serverless-dev",
            "PhysicalResourceId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-serverless-dev/f4fd431c",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-10-19T21:54:22.693000Z",
            "ResourceStatus": "CREATE_IN_PROGRESS"
        }
    ]
}
```

Listing buckets:

```sh
>  aws --endpoint-url http://localhost:4566 s3api list-buckets
{
    "Buckets": [
        {
            "Name": "my-serverless-dev-serverlessdeploymentbuck-442dc8a7",
            "CreationDate": "2022-10-19T21:54:23.000Z"
        },
        {
            "Name": "my-processed-bucket",
            "CreationDate": "2022-10-19T21:54:32.000Z"
        },
        {
            "Name": "my-storage-bucket",
            "CreationDate": "2022-10-19T21:54:32.000Z"
        },
        {
            "Name": "my-raw-bucket",
            "CreationDate": "2022-10-19T21:54:32.000Z"
        }
    ],
    "Owner": {
        "DisplayName": "webfile",
        "ID": "bcaf1ffd86f41161ca5fb16fd081034f"
    }
}

>  aws --endpoint-url http://localhost:4566 s3api list-buckets --region us-east-1
{
    "Buckets": [
        {
            "Name": "my-serverless-dev-serverlessdeploymentbuck-442dc8a7",
            "CreationDate": "2022-10-19T21:54:23.000Z"
        },
        {
            "Name": "my-processed-bucket",
            "CreationDate": "2022-10-19T21:54:32.000Z"
        },
        {
            "Name": "my-storage-bucket",
            "CreationDate": "2022-10-19T21:54:32.000Z"
        },
        {
            "Name": "my-raw-bucket",
            "CreationDate": "2022-10-19T21:54:32.000Z"
        }
    ],
    "Owner": {
        "DisplayName": "webfile",
        "ID": "bcaf1ffd86f41161ca5fb16fd081034f"
    }
}
```

Docker logs:

```sh
LocalStack version: 1.2.0
LocalStack Docker container id: 9135ea965465
LocalStack build date: 2022-10-07
LocalStack build git hash: 9be2a7aa

...

Ready.
2022-10-19T21:54:11.088 DEBUG --- [  MainThread] l.extensions.platform      : calling extensions on_platform_ready
2022-10-19T21:54:14.838 DEBUG --- [uest_thread)] l.services.dns_server      : Determined fallback dns: 192.168.65.5
2022-10-19T21:54:20.257 DEBUG --- [   asgi_gw_0] l.services.plugins         : checking service health sts:4566
2022-10-19T21:54:20.328  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS sts.GetCallerIdentity => 200
2022-10-19T21:54:22.125  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "_load_service_plugin" took 1688.08ms
2022-10-19T21:54:22.127 DEBUG --- [   asgi_gw_0] l.services.plugins         : checking service health cloudformation:4566
2022-10-19T21:54:22.129  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "require" took 1691.99ms
2022-10-19T21:54:22.668  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 400 (ValidationError)
2022-10-19T21:54:22.692 DEBUG --- [   asgi_gw_0] l.s.c.provider             : Creating stack "my-serverless-dev" with 2 resources ...
2022-10-19T21:54:22.696  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.CreateStack => 200
2022-10-19T21:54:22.910  INFO --- [  Thread-129] botocore.credentials       : Found credentials in environment variables.
2022-10-19T21:54:23.068  INFO --- [  Thread-133] l.services.motoserver      : starting moto server on http://0.0.0.0:59873
2022-10-19T21:54:23.070  INFO --- [   asgi_gw_0] localstack.services.infra  : Starting mock S3 service on http ports 443/4566 ...
2022-10-19T21:54:23.186 DEBUG --- [  Thread-129] l.u.c.template_deployer    : Handling "Add" for resource "ServerlessDeploymentBucket" (1/2) type "AWS::S3::Bucket" in loop iteration 1 (should_deploy=True)
2022-10-19T21:54:23.186 DEBUG --- [  Thread-129] l.u.c.template_deployer    : Running action "create" for resource type "S3::Bucket" id "ServerlessDeploymentBucket"
2022-10-19T21:54:23.550 DEBUG --- [  Thread-129] l.u.c.template_deployer    : Handling "Add" for resource "ServerlessDeploymentBucketPolicy" (1/1) type "AWS::S3::BucketPolicy" in loop iteration 1 (should_deploy=True)
2022-10-19T21:54:23.578 DEBUG --- [  Thread-129] l.u.c.template_deployer    : Running action "create" for resource type "S3::BucketPolicy" id "ServerlessDeploymentBucketPolicy"
2022-10-19T21:54:23.586 DEBUG --- [  Thread-129] l.u.c.template_deployer    : Request for resource type "S3::BucketPolicy" in region us-east-1: put_bucket_policy {'Policy': '{"Statement": [{"Action": "s3:*", "Effect": "Deny", "Principal": "*", "Resource": ["arn:aws:s3:::my-serverless-dev-serverlessdeploymentbuck-442dc8a7/*", "arn:aws:s3:::my-serverless-dev-serverlessdeploymentbuck-442dc8a7"], "Condition": {"Bool": {"aws:SecureTransport": false}}}]}', 'Bucket': 'my-serverless-dev-serverlessdeploymentbuck-442dc8a7'}
2022-10-19T21:54:27.719  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2022-10-19T21:54:27.738  WARN --- [   asgi_gw_0] l.aws.protocol.serializer  : Response object StackResourceDetail contains a member which is not specified: Timestamp
2022-10-19T21:54:27.738  WARN --- [   asgi_gw_0] l.aws.protocol.serializer  : Response object StackResourceDetail contains a member which is not specified: PreviousResourceStatus
2022-10-19T21:54:27.739  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStackResource => 200
2022-10-19T21:54:27.769  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.HeadBucket => 200
```

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

Simplest might be to create a serverless project using one of their example projects, and then running the deploy command. That will bundle a cloudformation package, which should fail to deploy.

### Environment

```markdown
- OS: MacOS Monterey 12.4
- LocalStack: latest (1.2.1.dev)
```

### Anything else?

Notice that the `:latest` image/container is using my default aws account id (i've masked with `XXXXXXXXXXXX`) whereas the old image/container (1.2.0) does not; it uses 000000000000. Not sure if this might be related, but thought it worth pointing out.

**Comment by matdodgson** [comment]
I have exactly the same issue but with DynamoDB. I was also using localstack:latest but have now switched to localstack:1.2.0 and the problem is fixed. With latest, I use the dynamo cli to create a table and get the right response from localstack. When I try to use the table from my code I get the error "Unknown table: redacted not found in dict_keys([])" from localstack.

**Comment by gavinvangent** [comment]
I looked through the github issues again now that I've got a better understanding of this issue. It appears this is related to: https://github.com/localstack/localstack/issues/7041

**Comment by dominikschubert** [comment]
This behavior recently introduced in the `latest` image has now been reverted and `latest` should now work again as you've noted that it previously did (use the account id of `000000000000` even if you have set your AWS credentials).
