### ISSUE TITLE
bug: CDK: cannot grant dynamodb access to a lambda function if the lambda function is defined before the dynamodb table

### ISSUE THREAD

**Issue by dpretty** [localstack/localstack#7050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using `cdklocal deploy` on a CDK project which grants dynamodb access to a lambda function defined before the dynamodb table causes the deploy to fail.

Deploying the following stack:

```python
from aws_cdk import Stack
from aws_cdk import aws_dynamodb as dynamodb
from aws_cdk import aws_lambda as lambda_
from aws_cdk import aws_lambda_python_alpha as lambda_python
from constructs import Construct


class LocalstackTestCdkConstructsStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        lambda_created_before = lambda_python.PythonFunction(
            self,
            "Before",
            runtime=lambda_.Runtime.PYTHON_3_8,
            entry="functions/python_lambda",
        )

        table = dynamodb.Table(
            self,
            "Table",
            partition_key=dynamodb.Attribute(
                name="keyName", type=dynamodb.AttributeType.STRING
            ),
        )

        lambda_created_after = lambda_python.PythonFunction(
            self,
            "After",
            runtime=lambda_.Runtime.PYTHON_3_8,
            entry="functions/python_lambda",
        )

        # This works
        table.grant_read_data(lambda_created_after)

        # This doesn't work.
        table.grant_read_data(lambda_created_before)

```

results in localstack producing the following error, causing the deploy to fail:

```
2022-10-20T07:34:33.974  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2022-10-20T07:34:34.315 DEBUG --- [   asgi_gw_0] l.services.plugins         : checking service health dynamodb:4566
2022-10-20T07:34:34.316  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "require" took 1989.33ms
2022-10-20T07:34:34.555 DEBUG --- [uncthread122] l.u.c.template_deployer    : Error applying changes for CloudFormation stack "LocalstackTestCdkConstructsStack": 'NoneType' object has no attribute 'split' Traceback (most recent call last):
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1411, in _run
self.do_apply_changes_in_loop(changes, stack)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1460, in do_apply_changes_in_loop
should_deploy = self.prepare_should_deploy_change(
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1526, in prepare_should_deploy_change
resolve_refs_recursively(stack, resource)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 61, in resolve_refs_recursively
File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func
return wrapped(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 410, in resolve_refs_recursively
result = _resolve_refs_recursively(stack, value)
File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func
return wrapped(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 606, in _resolve_refs_recursively
value[key] = resolve_refs_recursively(stack, val)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 61, in resolve_refs_recursively
File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func
return wrapped(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 410, in resolve_refs_recursively
result = _resolve_refs_recursively(stack, value)
File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func
return wrapped(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 606, in _resolve_refs_recursively
value[key] = resolve_refs_recursively(stack, val)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 61, in resolve_refs_recursively
File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func
return wrapped(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 410, in resolve_refs_recursively
result = _resolve_refs_recursively(stack, value)
File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func
return wrapped(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 606, in _resolve_refs_recursively
value[key] = resolve_refs_recursively(stack, val)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 61, in resolve_refs_recursively
File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func
return wrapped(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 410, in resolve_refs_recursively
result = _resolve_refs_recursively(stack, value)
File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func
return wrapped(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 616, in _resolve_refs_recursively
value[i] = resolve_refs_recursively(stack, value[i])
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 61, in resolve_refs_recursively
File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func
return wrapped(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 410, in resolve_refs_recursively
result = _resolve_refs_recursively(stack, value)
File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func
return wrapped(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 606, in _resolve_refs_recursively
value[key] = resolve_refs_recursively(stack, val)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 61, in resolve_refs_recursively
File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func
return wrapped(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 410, in resolve_refs_recursively
result = _resolve_refs_recursively(stack, value)
File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func
return wrapped(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 616, in _resolve_refs_recursively
value[i] = resolve_refs_recursively(stack, value[i])
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 61, in resolve_refs_recursively
File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func
return wrapped(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 410, in resolve_refs_recursively
result = _resolve_refs_recursively(stack, value)
File "/opt/code/localstack/localstack/utils/functions.py", line 80, in func
return wrapped(*args, **kwargs)
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 497, in _resolve_refs_recursively
return resolve_ref(stack, attr_ref[0], attribute=attr_ref[1])
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 371, in resolve_ref
return determine_resource_physical_id(
File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 988, in determine_resource_physical_id
result = resource_inst.get_physical_resource_id(attribute=attribute)
File "/opt/code/localstack/localstack/services/cloudformation/models/dynamodb.py", line 70, in get_physical_resource_id
return aws_stack.dynamodb_table_arn(table_name)
File "/opt/code/localstack/localstack/utils/aws/aws_stack.py", line 637, in dynamodb_table_arn
table_name = table_name.split(":table/")[-1]
AttributeError: 'NoneType' object has no attribute 'split'
```

### Expected Behavior

I would expect the deploy to succeed. The same stack is able to be deployed to aws using `cdk deploy`

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

I have created a minimal CDK stack which reproduces this issue: https://github.com/LaunchlabAU/localstack-test-cdk-constructs

```
DEBUG=1 localstack start
```

```
git clone https://github.com/LaunchlabAU/localstack-test-cdk-constructs
cd localstack-test-cdk-constructs
python -m venv .venv
. .venv/bin/activate
pip install -r ./requirements.txt 
cdklocal bootstrap
cdklocal synth
cdklocal deploy
```

### Environment

```markdown
- OS: Arch Linux
- LocalStack: latest
```

**Comment by pinzon** [comment]
The solution to this issue has been merged. Make sure to download the latest image of LocalStack.
