### ISSUE TITLE
feature request: Support Provisioned Concurrency Config in Lambda

### ISSUE THREAD

**Issue by HarshCasper** [localstack/localstack#7080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

From [Discussion Pages thread](https://discuss.localstack.cloud/t/is-provisioned-concurrency-config-lambda-feature-supported-by-localstack/117):

```
Hey, I would like to know if the localstack supports Provisioned Concurrency for lambda.

I’m trying to configure locally this to my lambda and it’s on an infinity loop at pulumi step. I have tried to configure it with the command “aws --endpoint-url=http://host.docker.internal:4566/ lambda put-provisioned-concurrency-config” and I’m getting a 404.

Thanks
Lucas Gauna dos Santos
```

**Comment by davecardwell** [comment]
It would work for us if this setting were allowed and validated, and the AWS APIs responded accordingly, but it did not actually change LocalStack’s behavior.

Currently we’re working around it by disabling the config in development, but I would prefer to keep this sort of environment difference to a minimum if possible:
```hcl
resource "aws_lambda_provisioned_concurrency_config" "myapp" {
  count = var.provisioned_concurrency > 0 ? 1 : 0

  function_name                     = aws_lambda_function.myapp.function_name
  provisioned_concurrent_executions = var.provisioned_concurrency
  qualifier                         = aws_lambda_alias.myapp.name
}
```

**Comment by dfangl** [comment]
Provisioned concurrency config CRUD should be supported by our new lambda provider (`PROVIDER_OVERRIDE_LAMBDA=asf`) already. It might not have full CRUD parity yet, but a basic implementation should work. Does this fix the issue you have in your terraform template @davecardwell ?

**Comment by davecardwell** [comment]
@dfangl oh perfect, thanks! I’ll try that out and will let you know if there are any issues.

**Comment by davecardwell** [comment]
@dfangl I have `PROVIDER_OVERRIDE_LAMBDA=v2` using `localstack/localstack-pro:latest` and my example Terraform config still results in errors:
```
2023-02-24T20:19:13.105  INFO --- [  asgi_gw_19] localstack.request.aws     : AWS lambda.GetProvisionedConcurrencyConfig => 500 (InternalError)
2023-02-24T20:19:27.156 ERROR --- [   asgi_gw_9] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 122, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 92, in __call__
    skeleton_response = self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/provider.py", line 2301, in get_provisioned_concurrency_config
    AvailableProvisionedConcurrentExecutions=ver_manager.provisioned_state.available,
AttributeError: 'LambdaVersionManager' object has no attribute 'provisioned_state'
2023-02-24T20:19:27.159  INFO --- [   asgi_gw_9] localstack.request.aws     : AWS lambda.GetProvisionedConcurrencyConfig => 500 (InternalError)
```

**Comment by joe4dev** [comment]
Hi @davecardwell, we [implemented provisioned concurrency](https://github.com/localstack/localstack/pull/7881) in March and released it with LocalStack 2.0. Check out the [Lambda highlights](https://docs.localstack.cloud/references/lambda-provider-v2/).

Please pull the LocalStack v2 image `docker pull localstack/localstack-pro` and give it another try.
We are looking forward to hearing your feedback!

**Comment by davecardwell** [comment]
@joe4dev Should `lambda.GetProvisionedConcurencyConfig` also be implemented?

I’m getting:
```
$ awslocal lambda get-provisioned-concurrency-config --function-name my-lambda --qualifier latest

An error occurred (InternalError) when calling the GetProvisionedConcurrencyConfig operation (reached max retries: 4): exception while calling lambda.GetProvisionedConcurrencyConfig: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 123, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 93, in __call__
    skeleton_response = self.skeleton.invoke(context)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 166, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/awslambda/provider.py", line 2483, in get_provisioned_concurrency_config
    AvailableProvisionedConcurrentExecutions=ver_manager.provisioned_state.available,
AttributeError: 'NoneType' object has no attribute 'available'
```

**Comment by davecardwell** [comment]
@joe4dev The above command works fine until I restart Localstack, after which I get the above error, so it may be a persistence-related issue. I am running `localstack-pro:2.0.1` with `PERSISTENCE: 1`.

**Comment by joe4dev** [comment]
> @joe4dev Should `lambda.GetProvisionedConcurencyConfig` also be implemented?

@davecardwell yes ✅ , our new [coverage documentation](https://docs.localstack.cloud/references/coverage/coverage_lambda/) shows that [GetProvisionedConcurrencyConfig](https://docs.localstack.cloud/references/coverage/coverage_lambda/#getprovisionedconcurrencyconfig) is implemented and tested.

**Comment by joe4dev** [comment]
> @joe4dev The above command works fine until I restart Localstack, after which I get the above error, so it may be a persistence-related issue. I am running `localstack-pro:2.0.1` with `PERSISTENCE: 1`.

@davecardwell Thank you for clarifying the context. Yes, I can confirm that persistence is not yet implemented for provisioned concurrency. I can reproduce the issue. It is in our Lambda backlog.
