### ISSUE TITLE
Unable to create sqs queue 

### ISSUE THREAD

**Issue by eston-p** [localstack/localstack#710]
Hi, im running latest version of localstack on windows 10 .

Steps to produce error:

1.  Git clone localstack
2. docker-compose up -d
3. aws --endpoint-url=http://<docker-machine-ip>:4576 sqs create-queue --queue-name test_queue

Below are my docker logs:

`$ docker logs localstack_localstack_1
2018-04-09 15:09:13,479 CRIT Supervisor running as root (no user in config file)
2018-04-09 15:09:13,481 INFO supervisord started with pid 1
2018-04-09 15:09:14,488 INFO spawned: 'dashboard' with pid 7
2018-04-09 15:09:14,524 INFO spawned: 'infra' with pid 8
(. .venv/bin/activate; exec bin/localstack start)
(. .venv/bin/activate; bin/localstack web)
2018-04-09 15:09:15,562 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-04-09 15:09:15,563 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting local dev environment. CTRL-C to quit.
2018-04-09T15:09:15:INFO:werkzeug:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
2018-04-09T15:09:15:INFO:werkzeug:  * Restarting with stat
Starting mock SQS (http port 4576)...
Starting mock SNS (http port 4575)...
2018-04-09T15:09:17:WARNING:werkzeug:  * Debugger is active!
2018-04-09T15:09:17:INFO:werkzeug:  * Debugger PIN: 101-445-352
Ready.
2018-04-09T15:11:13:ERROR:localstack.services.generic_proxy: Error forwarding request: syntax error: line 1, column 0 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 215, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/opt/code/localstack/localstack/services/sqs/sqs_listener.py", line 43, in return_response
    response_data = xmltodict.parse(response.content)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/xmltodict.py", line 311, in parse
    parser.Parse(xml_input, True)
ExpatError: syntax error: line 1, column 0

2018-04-09T15:12:14:ERROR:localstack.services.generic_proxy: Error forwarding request: syntax error: line 1, column 0 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 215, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/opt/code/localstack/localstack/services/sqs/sqs_listener.py", line 43, in return_response
    response_data = xmltodict.parse(response.content)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/xmltodict.py", line 311, in parse
    parser.Parse(xml_input, True)
ExpatError: syntax error: line 1, column 0

2018-04-09T15:13:16:ERROR:localstack.services.generic_proxy: Error forwarding request: syntax error: line 1, column 0 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 215, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/opt/code/localstack/localstack/services/sqs/sqs_listener.py", line 43, in return_response
    response_data = xmltodict.parse(response.content)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/xmltodict.py", line 311, in parse
    parser.Parse(xml_input, True)
ExpatError: syntax error: line 1, column 0

2018-04-09T15:14:18:ERROR:localstack.services.generic_proxy: Error forwarding request: syntax error: line 1, column 0 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 215, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/opt/code/localstack/localstack/services/sqs/sqs_listener.py", line 43, in return_response
    response_data = xmltodict.parse(response.content)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/xmltodict.py", line 311, in parse
    parser.Parse(xml_input, True)
ExpatError: syntax error: line 1, column 0

2018-04-09T15:15:25:ERROR:localstack.services.generic_proxy: Error forwarding request: syntax error: line 1, column 0 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 215, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/opt/code/localstack/localstack/services/sqs/sqs_listener.py", line 43, in return_response
    response_data = xmltodict.parse(response.content)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/xmltodict.py", line 311, in parse
    parser.Parse(xml_input, True)
ExpatError: syntax error: line 1, column 0`

Any help would be greatly appreciated.

**Comment by DrewDennison** [comment]
```aws --endpoint-url=http://localhost:4576 --region=us-west-1 sqs create-queue --queue-name myqueue```

I think you need `localhost` and --region

**Comment by mikeatlas-r7** [comment]
Were you able to resolve this @eston-p? I'm seeing the same exact error.

**Comment by eston-p** [comment]
@mikeatlas-r7 , sorry didnt resolve this issue, I decided to move over to ubuntu which solved my problems.

**Comment by yachaka** [comment]
Same issue here

**Comment by whummer** [comment]
Closing this issue as outdated/resolved. Please report here with detailed steps to reproduce if the problem persists. Thanks
