### ISSUE TITLE
bug: enabling persistence causes ResourceNotFoundException when calling BatchWriteItem

### ISSUE THREAD

**Issue by juansvasquez** [localstack/localstack#7118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When S3 persistence is enabled, calling the batch_writer() dynamoDB function returns a ResourceNotFoundException
(the test script provided below returns the following):

```
Traceback (most recent call last):
  File "dynamodb_table_update_test.py", line 26, in <module>
    Item=item,
  File "/Users/juanvasquez/projects/environments/app-state-service-tests/lib/python3.7/site-packages/boto3/dynamodb/table.py", line 156, in __exit__
    self._flush()
  File "/Users/juanvasquez/projects/environments/app-state-service-tests/lib/python3.7/site-packages/boto3/dynamodb/table.py", line 137, in _flush
    RequestItems={self._table_name: items_to_send})
  File "/Users/juanvasquez/projects/environments/app-state-service-tests/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/juanvasquez/projects/environments/app-state-service-tests/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the BatchWriteItem operation: Unknown table: CertificateTargets-local1 not found in dict_keys([])
```

### Expected Behavior

No errors on calling the batch_writer() function, as experienced currently when persistence is disabled.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose.yml:

```
localstack:
    container_name: localstack
    image: localstack/localstack:1.2.0-arm64
    restart: always
    ports:
    - "4566:4566"
    - "4567-4583:4567-4583"
    - "8081:${PORT_WEB_UI-8080}"
    environment:
    - DEFAULT_REGION=us-east-1
    - SERVICES=dynamodb,lambda,s3
    - DEBUG=1
    - LAMBDA_EXECUTOR=local
    - DATA_DIR=/tmp/localstack/data                    # comment out to disable persistence and get expected behavior
    - TEST_AWS_ACCOUNT_ID='123456'
    - AWS_ACCESS_KEY_ID=foobar
    - AWS_SECRET_ACCESS_KEY=foobar
    - LOCALSTACK_HOSTNAME=localhost
    - PORT_WEB_UI=${PORT_WEB_UI- }
    - EAGER_SERVICE_LOADING=1
    volumes:
    - "${DOCKER_LOCALSTACK_DATA}:/var/lib/localstack"  # comment out to disable persistence and get expected behavior
    - "/var/run/docker.sock:/var/run/docker.sock"
```
Run the below test script (create a table called CertificateTargets-local1 with hash key target_uuid)
Should error on line 23
(note that table.put_item() works on this table but batch.put_item() specifically does not)

```
from uuid import uuid4
import boto3

endpoint = 'http://localhost:4566'

target_uuid = str(uuid4())

dynamodb_resource = boto3.resource('dynamodb', endpoint_url=endpoint)
table_name = 'CertificateTargets-local1'
table = dynamodb_resource.Table(table_name)
table.put_item(
    Item={'target_uuid': target_uuid,},
)

items = []
for i in range(5):
    item_d = {'target_uuid': str(uuid4())}
    items.append(item_d)

dynamodb_resource = boto3.resource('dynamodb', endpoint_url=endpoint)
table_name = 'CertificateTargets-local1'
table = dynamodb_resource.Table(table_name)
with table.batch_writer() as batch:
    for item in items:
        batch.put_item(
            Item=item,
        )
```

### Environment

```markdown
- OS: macOS Monterey (Apple M1 Pro)
- LocalStack: 
1.2.0-arm64
latest-arm64
(reproduced on both)
```

**Comment by viren-nadkarni** [comment]
Hi @juansvasquez

Persistence is a Pro feature. Could you please try setting the environment variable `LOCALSTACK_API_KEY=<your Pro key>` and let us know if the issue persists?

**Comment by juansvasquez** [comment]
Hello @viren-nadkarni 
This behavior is not consistent if persistence were to be the issue. I don't think persistence not working is the issue here

**Comment by viren-nadkarni** [comment]
Hi @juansvasquez , we have pushed a fix that should prevent this inconsistency. Could you please give the `latest` image a go?

**Comment by lashd** [comment]
Hi, I have pulled the latest image and continue to see the same/a very similar problem.

```
LocalStack version: 1.3.1.dev
LocalStack build date: 2022-12-07
LocalStack build git hash: 4abe1966
```

Having created a DynamoDB table in localstack, this table is available to write and batchwrite to. After restarting localstack, whilst the table can still be written to, batchwrites no longer work with the server reporting:

```
2022-12-07T09:48:53.277  INFO --- [  Thread-513] l.services.dynamodb.server : 09:48:53.277 [qtp1639765351-14] WARN  com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler - DynamoDBLocalServiceException exception occured
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : com.amazonaws.services.dynamodbv2.exceptions.DynamoDBLocalServiceException: Cannot do operations on a non-existent table
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at com.amazonaws.services.dynamodbv2.exceptions.AWSExceptionFactory.buildLocalServiceException(AWSExceptionFactory.java:93) ~[DynamoDBLocal.jar:?]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at com.amazonaws.services.dynamodbv2.exceptions.AWSExceptionFactory.buildAWSException(AWSExceptionFactory.java:58) ~[DynamoDBLocal.jar:?]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at com.amazonaws.services.dynamodbv2.local.shared.access.api.DynamoDbApiFunction.validateTableExists(DynamoDbApiFunction.java:67) ~[DynamoDBLocal.jar:?]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at com.amazonaws.services.dynamodbv2.local.shared.access.api.dp.ScanFunction.apply(ScanFunction.java:54) ~[DynamoDBLocal.jar:?]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at com.amazonaws.services.dynamodbv2.local.shared.access.awssdkv1.client.LocalAmazonDynamoDB.scan(LocalAmazonDynamoDB.java:299) ~[DynamoDBLocal.jar:?]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.scan(LocalDynamoDBRequestHandler.java:371) ~[DynamoDBLocal.jar:?]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at com.amazonaws.services.dynamodbv2.local.dispatchers.ScanDispatcher.enact(ScanDispatcher.java:18) ~[DynamoDBLocal.jar:?]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at com.amazonaws.services.dynamodbv2.local.dispatchers.ScanDispatcher.enact(ScanDispatcher.java:12) ~[DynamoDBLocal.jar:?]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.packageDynamoDBResponse(LocalDynamoDBServerHandler.java:408) ~[DynamoDBLocal.jar:?]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.handle(LocalDynamoDBServerHandler.java:495) ~[DynamoDBLocal.jar:?]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:190) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[jetty-server-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[jetty-util-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[jetty-util-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[jetty-util-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[jetty-util-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[jetty-util-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[jetty-util-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[jetty-util-9.4.48.v20220622.jar:9.4.48.v20220622]
2022-12-07T09:48:53.278  INFO --- [  Thread-513] l.services.dynamodb.server : at java.lang.Thread.run(Unknown Source) ~[?:?]
2022-12-07T09:48:53.279  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.Scan => 400 (ResourceNotFoundException)
```

Meanwhile commands such as `awslocal dynamodb list-tables` work before and after the restart but commands such as `awslocal cloudformation describe-stacks` do not.

**Comment by fernandoalexandre** [comment]
I have hit this error when calling the BatchItemWriter in the latest code **after the LocalStack has restarted** (reset memory storage).

After some troubleshooting and testing this seems to be related to the way the `KeySchema` information is fetched from the Memory stores.

I was able to successfully avoid this error by implementing a fallback in `localstack/services/dynamodb/utils.py get_key_schema()`:

```
@classmethod
    def get_key_schema(
        cls, table_name: str, account_id: str = None, region_name: str = None
    ) -> Optional[List[Dict]]:
        from localstack.services.dynamodb.provider import get_store

        account_id = account_id or get_aws_account_id()
        region_name = region_name or aws_stack.get_region()

        table_definitions: Dict = get_store(
            account_id=account_id,
            region_name=region_name,
        ).table_definitions
        table_def = table_definitions.get(table_name)
        if not table_def:
            # Try fetching from the backend in case table_definitions has been reset
            schema = cls.get_table_schema(table_name=table_name, account_id=account_id, region_name=region_name)
            if not schema:
                raise ResourceNotFoundException(
                    f"Unknown table: {table_name} not found"
                )
            # Save the schema in the cache
            table_definitions[table_name] = schema["Table"]
            table_def = table_definitions[table_name]
        return table_def["KeySchema"]
```

Overall this seems to affect several functions, at first glance the BatchWriterItem, PutItem, TransactWriteItems and ExecuteStatement (if event_sources_or_streams_enabled).

Still figuring how to create a PR for this change (going through the contribution documentation), just wanted to share these findings.

**Comment by viren-nadkarni** [comment]
Closing as resolved. Please feel free to raise another issue if the this persists.

**Comment by igarabajiv-chwy** [comment]
(apologies for commenting on a resolved thread)
@juansvasquez Thanks for sharing your docker-compose. Commenting out persistent storage helped resolve the same error for me.
