### ISSUE TITLE
bug: HTTP API gateway failed to call Stepfunction

### ISSUE THREAD

**Issue by lee-butn** [localstack/localstack#7124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Could not call Step Function by HTTP API Gateway integration , keep getting stateMachineArn missing error.

### Expected Behavior

Execute state machine in given input

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Created HTTP API with StepFunction integration like following:
{
            "ConnectionType": "INTERNET",
            "IntegrationId": "35d497e9",
            "IntegrationSubtype": "StepFunctions-StartExecution",
            "IntegrationType": "AWS_PROXY",
            "IntegrationUri": "",
            "PayloadFormatVersion": "1.0",
            "RequestParameters": {
                "Input": "$request.body",
                "StateMachineArn": "arn:aws:states:ap-southeast-2:000000000000:stateMachine:localstack-registration-flow-95eb704"
            },
            "TimeoutInMillis": 30000
}
Which same one is working perfectly in real AWS Environment.

2. Call endpoint and get following error:

`` 2022-11-04T06:05:38.781 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/routes.py", line 27, in __call__
    router_response = self.router.dispatch(context.request)
  File "/opt/code/localstack/localstack/http/router.py", line 270, in dispatch
    return self.dispatcher(request, handler, args)
  File "/opt/code/localstack/localstack/http/dispatcher.py", line 123, in _dispatch
    result = endpoint(request, **args)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/router_asf.py.enc", line 21, in invoke_rest_api
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/integrations.py.enc", line 100, in invoke_api
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/integrations.py.enc", line 109, in invoke_http_api_v2
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/integrations.py.enc", line 130, in v2_invoke_integration_request
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/integrations.py.enc", line 138, in v2_do_invoke_integration_request
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/integrations.py.enc", line 180, in invoke
  File "/opt/code/localstack/localstack/services/apigateway/integration.py", line 467, in invoke
    result = method(**payload)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 901, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 962, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Missing required parameter in input: "stateMachineArn"
Unknown parameter in input: "version", must be one of: stateMachineArn, name, input, traceHeader
Unknown parameter in input: "id", must be one of: stateMachineArn, name, input, traceHeader
Unknown parameter in input: "detail-type", must be one of: stateMachineArn, name, input, traceHeader
Unknown parameter in input: "source", must be one of: stateMachineArn, name, input, traceHeader
Unknown parameter in input: "account", must be one of: stateMachineArn, name, input, traceHeader
Unknown parameter in input: "time", must be one of: stateMachineArn, name, input, traceHeader
Unknown parameter in input: "region", must be one of: stateMachineArn, name, input, traceHeader
Unknown parameter in input: "resources", must be one of: stateMachineArn, name, input, traceHeader
Unknown parameter in input: "detail", must be one of: stateMachineArn, name, input, traceHeader ``

4. When i locked into localstack/services/apigateway/integration.py , i don't see any code passing stateMachineArn

### Environment

```markdown
- OS: Ubuntu 20.04

- LocalStack: latest
```

**Comment by calvernaz** [comment]
Hi @lee-butn, thanks for reporting this. I could not reproduce the issue, and we have a sample for HTTP APIs and StepFunctions [here](https://github.com/localstack/localstack-terraform-samples/tree/master/apigatewayv2-state-machine) that works just fine 👍 

Looking at the logs and, in particular, the latest lines, it seems to complain about fields present on EventBridge events. I'm wondering if the problem stems from there and not from the StepFunctions integration. Could you provide a complete example?

**Comment by lee-butn** [comment]
Thanks @calvernaz  for looking into issue. I looked into your run.sh script and i think the problem is your input different from my:
Your: 
```{ "input": "{}", "name": "MyExecution", "stateMachineArn": "arn:aws:states:eu-west-1:000000000000:stateMachine:my-state-machine"}```
It does not make sense that we need to pass state machine name since it part of integration setup. 
This is my input without machine arn and it worked in real AWS environment. 

``` "version": "0",
    "id": "35af489f-37ad-48b3-197f-cc32dcadcd01",
    "detail": {}```

**Comment by calvernaz** [comment]
Hi @lee-butn I've adapted the sample to emulate your use case https://github.com/localstack/localstack-terraform-samples/tree/master/apigateway-step-functions-integration, please give it a try 👍
