### ISSUE TITLE
AWS Third Party Apache Dependency Failing To Attach to jar file in lambda. Throwing ClassNotFoundException

### ISSUE THREAD

**Issue by mongoDynamo** [localstack/localstack#713]
I'm trying to create a lambda that can interact with Kinesis, Dynamo, or S3. For some reason my lambda cannot communicate with any of these services because an error is being thrown : 
![image](https://user-images.githubusercontent.com/38298138/38639327-cd23c5a6-3d9e-11e8-8a2c-ccec77ad1063.png)
(Full log further down.)

I believe I've created the lambda's jar correctly using mvn package with the maven shade plugin, even going as far as including the entire AWS SDK in my POM in an attempt to get this jar to work.

Seems like what is making it fail is an Apache third party logger used by AWS with their communication methods. Whenever I try to create a Dynamoor S3 client, that is what is triggering the error.

If I were to only write a basic lambda to capture event data from a JSON file and then print it to a log file it works, but once I try intercommunication it fails. 

I'm using Windows 10 with docker-compose up to run localstack. So I don't know how to go about trying to include this dependency in the localstack environment. I was hoping to find a way to include this dependency in my POM and then have it in my jar, but no luck. 

Any advice or insight would be appreciated. 

Here's the simple lambda I was making, just something to delete an object in S3 : https://pastebin.com/8Ah2n3nZ

FULL TRACE : 
aws lambda --endpoint-url=http://localhost:4574  --region us-east-1 invoke --function-name dynamo
Function2 --payload file://input.json dynamoResult.log

An error occurred (InternalFailure) when calling the Invoke operation (reached max retries: 4): Error executing Lambda function: Lambda process returned error status code: 1. Output:
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.amazonaws.client.builder.AwsClientBuilder.<clinit>(AwsClientBuilder.java:58)
        at com.amazonaws.HelloWorld.handleRequest(HelloWorld.java:76)
        at com.amazonaws.HelloWorld.handleRequest(HelloWorld.java:26)
        at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:100)
Caused by: com.amazonaws.thirdparty.apache.codec.logging.LogConfigurationException: java.lang.ClassNotFoundException: com.amazonaws.thirdparty.apache.codec.logging.impl.LogFactoryImpl (Caused by java.lang.ClassNotFoundException: com.amazonaws.thirdparty.apache.codec.logging.impl.LogFactoryImpl)
        at com.amazonaws.thirdparty.apache.codec.logging.LogFactory.createFactory(LogFactory.java:1201)
        at com.amazonaws.thirdparty.apache.codec.logging.LogFactory$2.run(LogFactory.java:1003)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.amazonaws.thirdparty.apache.codec.logging.LogFactory.newFactory(LogFactory.java:1000)
        at com.amazonaws.thirdparty.apache.codec.logging.LogFactory.getFactory(LogFactory.java:626)
        at com.amazonaws.thirdparty.apache.codec.logging.LogFactory.getLog(LogFactory.java:657)
        at com.amazonaws.regions.AwsRegionProviderChain.<clinit>(AwsRegionProviderChain.java:33)
        ... 4 more
Caused by: java.lang.ClassNotFoundException: com.amazonaws.thirdparty.apache.codec.logging.impl.LogFactoryImpl
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.amazonaws.thirdparty.apache.codec.logging.LogFactory.createFactory(LogFactory.java:1063)
        ... 10 more
 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 255, in run_lambda
    event, context=context, version=version, async=async)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 460, in execute
    process.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 456, in do_execute
    result = lambda_function(event, context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 388, in execute
    handler=arn_to_lambda[arn].handler, main_file=main_file)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 481, in execute_java_lambda
    result, log_output = self.run_lambda_executor(cmd, async=async)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 67, in run_lambda_executor
    (return_code, log_output))
Exception: Lambda process returned error status code: 1. Output:
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.amazonaws.client.builder.AwsClientBuilder.<clinit>(AwsClientBuilder.java:58)
        at com.amazonaws.HelloWorld.handleRequest(HelloWorld.java:76)
        at com.amazonaws.HelloWorld.handleRequest(HelloWorld.java:26)
        at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:100)
Caused by: com.amazonaws.thirdparty.apache.codec.logging.LogConfigurationException: java.lang.ClassNotFoundException: com.amazonaws.thirdparty.apache.codec.logging.impl.LogFactoryImpl (Caused by java.lang.ClassNotFoundException: com.amazonaws.thirdparty.apache.codec.logging.impl.LogFactoryImpl)
        at com.amazonaws.thirdparty.apache.codec.logging.LogFactory.createFactory(LogFactory.java:1201)
        at com.amazonaws.thirdparty.apache.codec.logging.LogFactory$2.run(LogFactory.java:1003)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.amazonaws.thirdparty.apache.codec.logging.LogFactory.newFactory(LogFactory.java:1000)
        at com.amazonaws.thirdparty.apache.codec.logging.LogFactory.getFactory(LogFactory.java:626)
        at com.amazonaws.thirdparty.apache.codec.logging.LogFactory.getLog(LogFactory.java:657)
        at com.amazonaws.regions.AwsRegionProviderChain.<clinit>(AwsRegionProviderChain.java:33)
        ... 4 more
Caused by: java.lang.ClassNotFoundException: com.amazonaws.thirdparty.apache.codec.logging.impl.LogFactoryImpl
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.amazonaws.thirdparty.apache.codec.logging.LogFactory.createFactory(LogFactory.java:1063)
        ... 10 more

**Comment by andrezimmermann** [comment]
Can I have the dependencies (pom.xml) of the jar that originally caused the error? 
The general idea of the error is that your lambda is calling some class that is originally within the localstack lambda executor jar. Since the jar is created with the minimize jar as true, the class that is missing is removed because it's shade plugin heuristics doesn't detect usage.

**Comment by mongoDynamo** [comment]
@andrezimmermann Sure, here's the pom I was using : https://pastebin.com/NCezSPnf

**Comment by andrezimmermann** [comment]
Thanks, I will take a look tomorrow!

**Comment by mongoDynamo** [comment]
@andrezimmermann Thanks for the helping hand.

**Comment by andrezimmermann** [comment]
@mongoDynamo, as a workaround you can try using localstack version 0.8.5. I will need time to review the localstack code

**Comment by mongoDynamo** [comment]
@andrezimmermann How exactly could I run the 0.8.5 version on windows? Only way I've gotten it to work is by downloading the zip from the main page, and then running docker-compose up in the root directory.

**Comment by aggansu** [comment]
+1 

Facing similar issue with 0.8.6 version. Switched to 0.8.5 as recommended.

**Comment by ladams81** [comment]
Hi guys it appears i am having the same issue is 0.8.7 where dependencies living in the lib folder are not being picked up throwing ClassNotFoundExceptions

What is the current resolution?
