### ISSUE TITLE
bug: Docker not available in Drone CI with Pulumi

### ISSUE THREAD

**Issue by SanderHagen** [localstack/localstack#7145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm currently trying to implement Localstack into our Drone CI pipeline using Pulumi.
Locally I am able to do `pulumi up` to Localstack running locally.

In Drone, I am pulling the latest localstack/localstack image and running it as a service like this
```services:
  - name: localstack
    image: localstack/localstack
    environment:
      DEBUG: 1
      LOCALSTACK_API_KEY:
        from_secret: LOCALSTACK_API_KEY_TRIAL
```

However, when trying to deploy the application in Drone I get this error
```  aws:ecs:Service (admin-testing-ec2-service):
    error: 1 error occurred:
    	* error creating ECS service (admin-testing-ec2-service): ServerException: An error occurred (InternalError) when calling the RunTask operation (reached max retries: 4): exception while calling ecs.RunTask: Traceback (most recent call last):
      File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
        handler(self, self.context, response)
      File "/opt/code/localstack/localstack/aws/handlers/service.py", line 122, in __call__
        handler(chain, context, response)
      File "/opt/code/localstack/localstack/aws/handlers/service.py", line 92, in __call__
        skeleton_response = self.skeleton.invoke(context)
      File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
        return self.dispatch_request(context, instance)
      File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
        result = handler(context, instance) or {}
      File "/opt/code/localstack/localstack/aws/forwarder.py", line 56, in _call
        return handler(context, req)
      File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
        return self.fn(*args, **kwargs)
      File "/opt/code/localstack/localstack/aws/api/core.py", line 151, in operation_marker
        return fn(*args, **kwargs)
      File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/ecs/provider.py.enc", line 75, in run_task
      File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/ecs/provider.py.enc", line 172, in _do_run_task
      File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/ecs/provider.py.enc", line 187, in _determine_host_port
      File "/opt/code/localstack/localstack/utils/docker_utils.py", line 190, in reserve_available_container_port
        raise PortNotAvailableException(
    localstack.utils.net.PortNotAvailableException: Unable to determine available Docker container port after 10 retries
```

It seems to go wrong when trying to retrieve a port for an ECS service

```
2022-11-08T14:47:05.378  WARN --- [   asgi_gw_2] l.utils.docker_utils       : Unexpected error when attempting to determine container port status: Docker not available
```

The deploy step looks like this 
```  - name: localstack-testing-up
    image: pulumi/pulumi-nodejs
    pull: if-not-exists
    environment:
      PULUMI_ACCESS_TOKEN:
        from_secret: PULUMI_ACCESS_TOKEN  
    depends_on: [ install, localstack-wait ]
    commands:
    - npm install -g docker
    - docker info
    - cd src/Testing
    - pulumi login
    - AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION=eu-central-1 pulumi up --stack localstack --yes
```

So it looks like the container needs Docker, but it's not installed?

### Expected Behavior

I don't expect this error and would expect the deploy to succeed

### How are you starting LocalStack?

Custom
Using [Drone CI](https://www.drone.io/)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
``` 
 - name: localstack
    image: localstack/localstack
    environment:
      DEBUG: 1
      LOCALSTACK_API_KEY:
        from_secret: LOCALSTACK_API_KEY_TRIAL
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    - AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_DEFAULT_REGION=eu-central-1 pulumi up --stack localstack --yes

### Environment

```markdown
- OS:Debian 10
- LocalStack:latest
```

**Comment by viren-nadkarni** [comment]
Hi @SanderHagen , LocalStack needs access to the Docker socket for certain services.  For details, please take a look at our docs page [here](https://docs.localstack.cloud/ci/drone-ci/).

**Comment by SanderHagen** [comment]
> Hi @SanderHagen , LocalStack needs access to the Docker socket for certain services. For details, please take a look at our docs page [here](https://docs.localstack.cloud/ci/drone-ci/).

Thanks! It worked indeed by adding


```
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
```
and 
```
    volumes:
      - name: docker
        path: /var/run/docker.sock
```
to the service

**Comment by raymcdermott** [comment]
I know this is closed but this does not work for me. Drone will not start and complains:
> linter: untrusted repositories cannot mount host volumes

**Comment by raymcdermott** [comment]
Should I open a new issue?

**Comment by viren-nadkarni** [comment]
@raymcdermott : yes, please file a new issue with steps to reproduce
