### ISSUE TITLE
bug: Deploying VPC network stack with cdklocal fails unexpectedly

### ISSUE THREAD

**Issue by iulspop** [localstack/localstack#7167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I bootstrap the local environment using `cdklocal` successfully, but when I deploy my CloudFormation stacks using `cdklocal deploy --all` I get the error:
```
 ❌  network-stack-testing failed: Error: The stack named network-stack-testing failed to deploy: CREATE_FAILED (Deployment failed)
    at FullCloudFormationDeployment.monitorDeployment (/Users/iulspop/.nvm/versions/node/v18.10.0/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:505:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at deployStack2 (/Users/iulspop/.nvm/versions/node/v18.10.0/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:241:24)
    at /Users/iulspop/.nvm/versions/node/v18.10.0/lib/node_modules/aws-cdk/lib/deploy.ts:39:11
    at run (/Users/iulspop/.nvm/versions/node/v18.10.0/lib/node_modules/p-queue/dist/index.js:163:29)
```

The Localstack Docker process outputs these debug loggs:
```
localstack_main  | 2022-11-11T16:20:03.040 DEBUG --- [uncthread209] l.u.c.template_deployer    : Running action "create" for resource type "EC2::SubnetRouteTableAssociation" id "githubhardeningvpctestingPrivateIsolatedSubnet2RouteTableAssociationAB9CAE90"
localstack_main  | 2022-11-11T16:20:03.042 DEBUG --- [uncthread209] l.u.c.template_deployer    : Request for resource type "EC2::SubnetRouteTableAssociation" in region us-east-1: associate_route_table {'RouteTableId': 'rtb-25a45145', 'SubnetId': 'subnet-325240e1'}
localstack_main  | 2022-11-11T16:20:03.066 DEBUG --- [uncthread209] l.u.c.template_deployer    : Handling "Add" for resource "githubhardeningvpctestingIGW1ECB8530" (7/9) type "AWS::EC2::InternetGateway" in loop iteration 1 (should_deploy=True)
localstack_main  | 2022-11-11T16:20:03.066 DEBUG --- [uncthread209] l.u.c.template_deployer    : Running action "create" for resource type "EC2::InternetGateway" id "githubhardeningvpctestingIGW1ECB8530"
localstack_main  | 2022-11-11T16:20:03.071 DEBUG --- [uncthread209] l.u.c.template_deployer    : Request for resource type "EC2::InternetGateway" in region us-east-1: create_internet_gateway {'TagSpecifications': [{'ResourceType': 'internet-gateway', 'Tags': [{'Key': 'Name', 'Value': 'network-stack-testing/github-hardening-vpc-testing'}]}]}
localstack_main  | 2022-11-11T16:20:03.105 DEBUG --- [uncthread209] l.u.c.template_deployer    : Handling "Add" for resource "githubhardeningvpctestingVPCGW5281BB0A" (7/8) type "AWS::EC2::VPCGatewayAttachment" in loop iteration 1 (should_deploy=True)
localstack_main  | 2022-11-11T16:20:03.116 DEBUG --- [uncthread209] l.u.c.template_deployer    : Running action "create" for resource type "EC2::VPCGatewayAttachment" id "githubhardeningvpctestingVPCGW5281BB0A"
localstack_main  | 2022-11-11T16:20:03.170  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack_main  | 2022-11-11T16:20:03.250 DEBUG --- [uncthread209] l.u.c.template_deployer    : Extract resource attribute: Parameter Ref
localstack_main  | 2022-11-11T16:20:03.356 DEBUG --- [uncthread209] l.u.c.template_deployer    : Handling "Add" for resource "CDKMetadata" (7/7) type "AWS::CDK::Metadata" in loop iteration 1 (should_deploy=True)
localstack_main  | 2022-11-11T16:20:03.472 DEBUG --- [uncthread209] l.u.c.template_deployer    : Extract resource attribute: Parameter Ref
localstack_main  | 2022-11-11T16:20:03.573 DEBUG --- [uncthread209] l.u.c.template_deployer    : Running action "create" for resource type "CDK::Metadata" id "CDKMetadata"
localstack_main  | 2022-11-11T16:20:03.591 DEBUG --- [uncthread209] l.u.c.template_deployer    : Handling "Add" for resource "githubhardeningvpctestingPublicSubnet1DefaultRouteD6C047BC" (1/6) type "AWS::EC2::Route" in loop iteration 2 (should_deploy=True)
localstack_main  | 2022-11-11T16:20:03.611 DEBUG --- [uncthread209] l.u.c.template_deployer    : Running action "create" for resource type "EC2::Route" id "githubhardeningvpctestingPublicSubnet1DefaultRouteD6C047BC"
localstack_main  | 2022-11-11T16:20:03.615 DEBUG --- [uncthread209] l.u.c.template_deployer    : Request for resource type "EC2::Route" in region us-east-1: create_route {'DestinationCidrBlock': '0.0.0.0/0', 'RouteTableId': 'rtb-76f07ddc'}
localstack_main  | 2022-11-11T16:20:03.622 DEBUG --- [uncthread209] l.u.c.template_deployer    : Executing callback method for EC2::Route:githubhardeningvpctestingPublicSubnet1DefaultRouteD6C047BC
localstack_main  | 2022-11-11T16:20:03.627  WARN --- [uncthread209] l.u.c.template_deployer    : Unexpected resource type EC2::EIP when resolving references of resource githubhardeningvpctestingPublicSubnet1EIPF9A50011: {"Type": "AWS::EC2::EIP", "Metadata": {"aws:cdk:path": "network-stack-testing/github-hardening-vpc-testing/PublicSubnet1/EIP"}, "LogicalResourceId": "githubhardeningvpctestingPublicSubnet1EIPF9A50011", "Properties": {"Domain": "vpc", "Tags": [{"Key": "Name", "Value": "network-stack-testing/github-hardening-vpc-testing/PublicSubnet1"}]}, "PhysicalResourceId": null}. To find out if EC2::EIP is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
localstack_main  | 2022-11-11T16:20:03.628 DEBUG --- [uncthread209] l.u.c.template_deployer    : Dependencies for "githubhardeningvpctestingPublicSubnet1NATGateway5CDAFE80" not yet satisfied, retrying in next loop: Unable to fetch details for resource "githubhardeningvpctestingPublicSubnet1EIPF9A50011" (resolving attribute "AllocationId")
localstack_main  | 2022-11-11T16:20:03.647 DEBUG --- [uncthread209] l.u.c.template_deployer    : Handling "Add" for resource "githubhardeningvpctestingPublicSubnet2DefaultRoute62DF5813" (2/5) type "AWS::EC2::Route" in loop iteration 2 (should_deploy=True)
localstack_main  | 2022-11-11T16:20:03.667 DEBUG --- [uncthread209] l.u.c.template_deployer    : Running action "create" for resource type "EC2::Route" id "githubhardeningvpctestingPublicSubnet2DefaultRoute62DF5813"
localstack_main  | 2022-11-11T16:20:03.669 DEBUG --- [uncthread209] l.u.c.template_deployer    : Request for resource type "EC2::Route" in region us-east-1: create_route {'DestinationCidrBlock': '0.0.0.0/0', 'RouteTableId': 'rtb-3976abb7'}
localstack_main  | 2022-11-11T16:20:03.676 DEBUG --- [uncthread209] l.u.c.template_deployer    : Executing callback method for EC2::Route:githubhardeningvpctestingPublicSubnet2DefaultRoute62DF5813
localstack_main  | 2022-11-11T16:20:03.680  WARN --- [uncthread209] l.u.c.template_deployer    : Unexpected resource type EC2::EIP when resolving references of resource githubhardeningvpctestingPublicSubnet2EIPC808A2DD: {"Type": "AWS::EC2::EIP", "Metadata": {"aws:cdk:path": "network-stack-testing/github-hardening-vpc-testing/PublicSubnet2/EIP"}, "LogicalResourceId": "githubhardeningvpctestingPublicSubnet2EIPC808A2DD", "Properties": {"Domain": "vpc", "Tags": [{"Key": "Name", "Value": "network-stack-testing/github-hardening-vpc-testing/PublicSubnet2"}]}, "PhysicalResourceId": null}. To find out if EC2::EIP is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
localstack_main  | 2022-11-11T16:20:03.680 DEBUG --- [uncthread209] l.u.c.template_deployer    : Dependencies for "githubhardeningvpctestingPublicSubnet2NATGatewayA05C3667" not yet satisfied, retrying in next loop: Unable to fetch details for resource "githubhardeningvpctestingPublicSubnet2EIPC808A2DD" (resolving attribute "AllocationId")
localstack_main  | 2022-11-11T16:20:03.687  WARN --- [uncthread209] l.u.c.template_deployer    : Unexpected resource type EC2::EIP when resolving references of resource githubhardeningvpctestingPublicSubnet1EIPF9A50011: {"Type": "AWS::EC2::EIP", "Metadata": {"aws:cdk:path": "network-stack-testing/github-hardening-vpc-testing/PublicSubnet1/EIP"}, "LogicalResourceId": "githubhardeningvpctestingPublicSubnet1EIPF9A50011", "Properties": {"Domain": "vpc", "Tags": [{"Key": "Name", "Value": "network-stack-testing/github-hardening-vpc-testing/PublicSubnet1"}]}, "PhysicalResourceId": null}. To find out if EC2::EIP is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
localstack_main  | 2022-11-11T16:20:03.687 DEBUG --- [uncthread209] l.u.c.template_deployer    : Dependencies for "githubhardeningvpctestingPrivateSubnet1DefaultRouteB373DED8" not yet satisfied, retrying in next loop: Unable to fetch details for resource "githubhardeningvpctestingPublicSubnet1EIPF9A50011" (resolving attribute "AllocationId")
localstack_main  | 2022-11-11T16:20:03.694  WARN --- [uncthread209] l.u.c.template_deployer    : Unexpected resource type EC2::EIP when resolving references of resource githubhardeningvpctestingPublicSubnet2EIPC808A2DD: {"Type": "AWS::EC2::EIP", "Metadata": {"aws:cdk:path": "network-stack-testing/github-hardening-vpc-testing/PublicSubnet2/EIP"}, "LogicalResourceId": "githubhardeningvpctestingPublicSubnet2EIPC808A2DD", "Properties": {"Domain": "vpc", "Tags": [{"Key": "Name", "Value": "network-stack-testing/github-hardening-vpc-testing/PublicSubnet2"}]}, "PhysicalResourceId": null}. To find out if EC2::EIP is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
localstack_main  | 2022-11-11T16:20:03.694 DEBUG --- [uncthread209] l.u.c.template_deployer    : Dependencies for "githubhardeningvpctestingPrivateSubnet2DefaultRouteFA6DB14B" not yet satisfied, retrying in next loop: Unable to fetch details for resource "githubhardeningvpctestingPublicSubnet2EIPC808A2DD" (resolving attribute "AllocationId")
localstack_main  | 2022-11-11T16:20:03.697  WARN --- [uncthread209] l.u.c.template_deployer    : Unexpected resource type EC2::EIP when resolving references of resource githubhardeningvpctestingPublicSubnet1EIPF9A50011: {"Type": "AWS::EC2::EIP", "Metadata": {"aws:cdk:path": "network-stack-testing/github-hardening-vpc-testing/PublicSubnet1/EIP"}, "LogicalResourceId": "githubhardeningvpctestingPublicSubnet1EIPF9A50011", "Properties": {"Domain": "vpc", "Tags": [{"Key": "Name", "Value": "network-stack-testing/github-hardening-vpc-testing/PublicSubnet1"}]}, "PhysicalResourceId": null}. To find out if EC2::EIP is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
localstack_main  | 2022-11-11T16:20:03.697 DEBUG --- [uncthread209] l.u.c.template_deployer    : Dependencies for "githubhardeningvpctestingPublicSubnet1NATGateway5CDAFE80" not yet satisfied, retrying in next loop: Unable to fetch details for resource "githubhardeningvpctestingPublicSubnet1EIPF9A50011" (resolving attribute "AllocationId")
localstack_main  | 2022-11-11T16:20:03.701  WARN --- [uncthread209] l.u.c.template_deployer    : Unexpected resource type EC2::EIP when resolving references of resource githubhardeningvpctestingPublicSubnet2EIPC808A2DD: {"Type": "AWS::EC2::EIP", "Metadata": {"aws:cdk:path": "network-stack-testing/github-hardening-vpc-testing/PublicSubnet2/EIP"}, "LogicalResourceId": "githubhardeningvpctestingPublicSubnet2EIPC808A2DD", "Properties": {"Domain": "vpc", "Tags": [{"Key": "Name", "Value": "network-stack-testing/github-hardening-vpc-testing/PublicSubnet2"}]}, "PhysicalResourceId": null}. To find out if EC2::EIP is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
localstack_main  | 2022-11-11T16:20:03.701 DEBUG --- [uncthread209] l.u.c.template_deployer    : Dependencies for "githubhardeningvpctestingPublicSubnet2NATGatewayA05C3667" not yet satisfied, retrying in next loop: Unable to fetch details for resource "githubhardeningvpctestingPublicSubnet2EIPC808A2DD" (resolving attribute "AllocationId")
localstack_main  | 2022-11-11T16:20:03.707  WARN --- [uncthread209] l.u.c.template_deployer    : Unexpected resource type EC2::EIP when resolving references of resource githubhardeningvpctestingPublicSubnet1EIPF9A50011: {"Type": "AWS::EC2::EIP", "Metadata": {"aws:cdk:path": "network-stack-testing/github-hardening-vpc-testing/PublicSubnet1/EIP"}, "LogicalResourceId": "githubhardeningvpctestingPublicSubnet1EIPF9A50011", "Properties": {"Domain": "vpc", "Tags": [{"Key": "Name", "Value": "network-stack-testing/github-hardening-vpc-testing/PublicSubnet1"}]}, "PhysicalResourceId": null}. To find out if EC2::EIP is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
localstack_main  | 2022-11-11T16:20:03.707 DEBUG --- [uncthread209] l.u.c.template_deployer    : Dependencies for "githubhardeningvpctestingPrivateSubnet1DefaultRouteB373DED8" not yet satisfied, retrying in next loop: Unable to fetch details for resource "githubhardeningvpctestingPublicSubnet1EIPF9A50011" (resolving attribute "AllocationId")
localstack_main  | 2022-11-11T16:20:03.713  WARN --- [uncthread209] l.u.c.template_deployer    : Unexpected resource type EC2::EIP when resolving references of resource githubhardeningvpctestingPublicSubnet2EIPC808A2DD: {"Type": "AWS::EC2::EIP", "Metadata": {"aws:cdk:path": "network-stack-testing/github-hardening-vpc-testing/PublicSubnet2/EIP"}, "LogicalResourceId": "githubhardeningvpctestingPublicSubnet2EIPC808A2DD", "Properties": {"Domain": "vpc", "Tags": [{"Key": "Name", "Value": "network-stack-testing/github-hardening-vpc-testing/PublicSubnet2"}]}, "PhysicalResourceId": null}. To find out if EC2::EIP is supported in LocalStack Pro, please check out our docs at https://docs.localstack.cloud/aws/cloudformation
localstack_main  | 2022-11-11T16:20:03.713 DEBUG --- [uncthread209] l.u.c.template_deployer    : Dependencies for "githubhardeningvpctestingPrivateSubnet2DefaultRouteFA6DB14B" not yet satisfied, retrying in next loop: Unable to fetch details for resource "githubhardeningvpctestingPublicSubnet2EIPC808A2DD" (resolving attribute "AllocationId")
localstack_main  | 2022-11-11T16:20:03.713 DEBUG --- [uncthread209] l.u.c.template_deployer    : Error applying changes for CloudFormation stack "network-stack-testing": Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'githubhardeningvpctestingPublicSubnet1NATGateway5CDAFE80', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::NatGateway', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'githubhardeningvpctestingPublicSubnet2NATGatewayA05C3667', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::NatGateway', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'githubhardeningvpctestingPrivateSubnet1DefaultRouteB373DED8', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::Route', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'githubhardeningvpctestingPrivateSubnet2DefaultRouteFA6DB14B', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::Route', 'Scope': [], 'Details': []}}] Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1412, in _run
localstack_main  |     self.do_apply_changes_in_loop(changes, stack)
localstack_main  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1503, in do_apply_changes_in_loop
localstack_main  |     raise Exception(
localstack_main  | Exception: Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'githubhardeningvpctestingPublicSubnet1NATGateway5CDAFE80', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::NatGateway', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'githubhardeningvpctestingPublicSubnet2NATGatewayA05C3667', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::NatGateway', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'githubhardeningvpctestingPrivateSubnet1DefaultRouteB373DED8', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::Route', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'githubhardeningvpctestingPrivateSubnet2DefaultRouteFA6DB14B', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::Route', 'Scope': [], 'Details': []}}]
localstack_main  | 
localstack_main  | 2022-11-11T16:20:05.220  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack_main  | 2022-11-11T16:20:07.246  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack_main  | 2022-11-11T16:20:07.287  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
localstack_main  | 2022-11-11T16:20:07.299  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
```

I'm not sure which logs are relevant to the problem. The most pertinent seems to be:
```
localstack_main  |     raise Exception(
localstack_main  | Exception: Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'githubhardeningvpctestingPublicSubnet1NATGateway5CDAFE80', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::NatGateway', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'githubhardeningvpctestingPublicSubnet2NATGatewayA05C3667', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::NatGateway', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'githubhardeningvpctestingPrivateSubnet1DefaultRouteB373DED8', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::Route', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'githubhardeningvpctestingPrivateSubnet2DefaultRouteFA6DB14B', 'PhysicalResourceId': None, 'ResourceType': 'AWS::EC2::Route', 'Scope': [], 'Details': []}}]
```

### Expected Behavior

It should deploy my CloudFormations stack templates synthesized from the CDK successfully without error.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I'm using Docker Compose. My `docker-compose.yml` file:
```
version: "3.8"

services:
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - PERSISTENCE=0
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Then I run:
`docker-compose up`

Then I run:
`cdklocal boostrap` and `cdklocal deploy --all`

I cannot share my CloudFormation templates publically, unfortunately.

### Environment

```markdown
- OS: Mac OS Ventura 13
- LocalStack: localstack/localstack latest image, created one day ago (Nov 10)
```

### Anything else?

I would love to use LocalStack day-to-day if I can get it running! Our current development loop is extremely slow to deploy to CloudFormation.

Let me know if I can provide any additional information to help solve this problem. Thank you!

**Comment by iulspop** [comment]
Any follow-up on this? Happy to assist in debugging or to give more detail about my specific CDK setup if that's necessary. Either way, I'll try again in a couple of months and perhaps this issue will be fixed by other updates to LocalStack.

**Comment by jubis** [comment]
In the documentation it seems like EIP is only supported in the Pro/Enterprise version and not in the Community Edition. It seems like you're running the Community Edition.
https://docs.localstack.cloud/user-guide/aws/cloudformation/

**Comment by dominikschubert** [comment]
Hi @iulspop! As @jubis  already mentioned using PRO seems to be a requirement for this to work. There might still be some minor issues, that I'd be willing to assist you with, if you can share a stripped down CDK stack which reproduces your observed issue. 

You can get started with a trial license for LocalStack PRO on our website to try this :+1: 

Please let me know if you want to continue exploring this.

**Comment by iulspop** [comment]
That's helpful thanks! I will try again with the pro version :)

**Comment by dominikschubert** [comment]
@iulspop Did you get a chance to try this yet?
