### ISSUE TITLE
bug: localstack return EOF for aws:ecr/getCredentials

### ISSUE THREAD

**Issue by ToddG** [localstack/localstack#7186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**WHAT**
`pulumi` invokes `aws:ecr/getCredentials as part of awsx:

https://github.com/pulumi/pulumi-awsx/blob/ec3ee6d18087f1ac94bde9c609aadbf3ae9e4792/awsx/ecr/image.ts#L70
```ts
      const credentials = aws.ecr.getCredentialsOutput(
        { registryId: registryId },
        { parent, async: true },
      );
```

**ERROR**

Trying to build and deploy an image fails with:

```
View Live: https://app.pulumi.com/ToddG/component-project/localstack/updates/2

     Type                  Name                                                       Status              Info
     pulumi:pulumi:Stack   component-project-localstack                               **failed (1s)**     2 errors; 2 warnings; 34 messages
 +   ├─ aws:kms:Alias      localstack-component-project-kms-alias                     created (0.15s)     
 +   └─ aws:ssm:Parameter  /localstack/component/backend_project_microservice/db_uri  created (0.67s)     


Diagnostics:
  pulumi:pulumi:Stack (component-project-localstack):
    warning: provider config warning: Use s3_use_path_style instead.
    warning: provider config warning: Argument is deprecated
    dockerBuild: {"context":"/home/todd/tmp_5cuvoaql/backend-project-microservice/deploy/pulumi/./resources/../../docker/_build"}
    error: Error: invocation of aws:ecr/getCredentials:getCredentials returned an error: error reading from server: EOF
        at Object.callback (/snapshot/awsx/node_modules/@pulumi/pulumi/runtime/invoke.js:141:33)
        at Object.onReceiveStatus (/snapshot/awsx/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/snapshot/awsx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/snapshot/awsx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /snapshot/awsx/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:78:11)
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/home/todd/tmp_5cuvoaql/backend-project-microservice/deploy/pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 608, in do_rpc_call
        return monitor.RegisterResource(req)
      File "/home/todd/tmp_5cuvoaql/backend-project-microservice/deploy/pulumi/venv/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
        return _end_unary_response_blocking(state, call, False, None)
      File "/home/todd/tmp_5cuvoaql/backend-project-microservice/deploy/pulumi/venv/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
        raise _InactiveRpcError(state)
    grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    	status = StatusCode.UNKNOWN
    	details = "invocation of aws:ecr/getCredentials:getCredentials returned an error: error reading from server: EOF"
    	debug_error_string = "{"created":"@1668557391.399938162","description":"Error received from peer ipv4:127.0.0.1:40907","file":"src/core/lib/surface/call.cc","file_line":966,"grpc_message":"invocation of aws:ecr/getCredentials:getCredentials returned an error: error reading from server: EOF","grpc_status":2}"
    >
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/todd/.pulumi/bin/pulumi-language-python-exec", line 192, in <module>
        loop.run_until_complete(coro)
      File "/home/todd/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
        return future.result()
      File "/home/todd/tmp_5cuvoaql/backend-project-microservice/deploy/pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/todd/tmp_5cuvoaql/backend-project-microservice/deploy/pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/home/todd/tmp_5cuvoaql/backend-project-microservice/deploy/pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 110, in wait_for_rpcs
        raise exception
      File "/home/todd/tmp_5cuvoaql/backend-project-microservice/deploy/pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
        result = await rpc
      File "/home/todd/tmp_5cuvoaql/backend-project-microservice/deploy/pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 613, in do_register
        resp = await asyncio.get_event_loop().run_in_executor(None, do_rpc_call)
      File "/home/todd/.pyenv/versions/3.10.6/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/todd/tmp_5cuvoaql/backend-project-microservice/deploy/pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 610, in do_rpc_call
        handle_grpc_error(exn)
      File "/home/todd/tmp_5cuvoaql/backend-project-microservice/deploy/pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/settings.py", line 273, in handle_grpc_error
        raise grpc_error_to_exception(exn)
    Exception: invocation of aws:ecr/getCredentials:getCredentials returned an error: error reading from server: EOF

    panic: runtime error: index out of range [0] with length 0
    goroutine 83 [running]:
    github.com/hashicorp/terraform-provider-aws/internal/service/ecr.dataSourceAwsEcrCredentialsRead(0xc00232fd80, {0x7e70e80, 0xc000dc1500})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-provider-aws@v1.38.1-0.20220425115028-72c3a67ae4a7/internal/service/ecr/credentials_data_source.go:59 +0x3f6
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x9254241, {0xa33b938, 0xc0000520f8}, 0x7e70e80, {0x7e70e80, 0xc000dc1500})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20211230170131-3a7c83bfab87/helper/schema/resource.go:336 +0x178
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000d5f520, {0xa33b938, 0xc0000520f8}, 0xc00232fd00, {0x7e70e80, 0xc000dc1500})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20211230170131-3a7c83bfab87/helper/schema/resource.go:559 +0xf7
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.ReadDataApply({0xa49c048}, {0x92ad3eb, 0x13}, {0xa43f688, 0xc00232fd00})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.22.1/pkg/tfshim/sdk-v2/provider.go:143 +0xc5
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Invoke(0xc0006a78c0, {0xa33b9a8, 0xc00239e330}, 0xc00238a6c0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.22.1/pkg/tfbridge/provider.go:1187 +0x799
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler.func1({0xa33b9a8, 0xc00239e330}, {0x8d92900, 0xc00238a6c0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.31.1/proto/go/provider.pb.go:2521 +0x7b
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0xa33b9a8, 0xc00239e0c0}, {0x8d92900, 0xc00238a6c0}, 0xc0018b5ae0, 0xc002398420)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x406
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler({0x90f7860, 0xc0006a78c0}, {0xa33b9a8, 0xc00239e0c0}, 0xc00239c240, 0xc00198b680)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.31.1/proto/go/provider.pb.go:2523 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc001814540, {0xa43f8c0, 0xc0006b0680}, 0xc00239a480, 0xc001e46750, 0x112b7a60, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
    google.golang.org/grpc.(*Server).handleStream(0xc001814540, {0xa43f8c0, 0xc0006b0680}, 0xc00239a480, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x294

    Error: invocation of aws:ecr/getCredentials:getCredentials returned an error: error reading from server: EOF: Error: invocation of aws:ecr/getCredentials:getCredentials returned an error: error reading from server: EOF
        at Object.callback (/snapshot/awsx/node_modules/@pulumi/pulumi/runtime/invoke.js:141:33)
        at Object.onReceiveStatus (/snapshot/awsx/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/snapshot/awsx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/snapshot/awsx/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /snapshot/awsx/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:78:11)

Outputs:
  + alias_arn: "arn:aws:kms:us-east-1:000000000000:alias/localstack-component-project-kms-alias-6e2d695"
  + key_arn  : "arn:aws:kms:us-east-1:000000000000:key/abe9dc2f-800a-4593-bb33-359d108a250a"

Resources:
    + 2 created
    7 unchanged
```

**SLACK**
https://pulumi-community.slack.com/archives/C026EE6N2VB/p1668557766238449

### Expected Behavior

Dunno, as this is in-between pulumi and localstack... 

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

DNS_ADDRESS=127.0.0.1 localstack start -d
localstack dns systemd-resolved # this did not succeed btw 

```
$ localstack dns systemd-resolved
Configuring systemd-resolved...
[sudo] password for todd: 
Warning:  Error while configuring systemd-resolved: Failed to resolve interface "docker0": No such device
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
pulumilocal init
# remove the cruft of mobileanalytics # see https://github.com/localstack/pulumi-local/issues/5
# pulumi up
```

REPRO:

```
cd {existing project}
pulumilocal init
# remove the line with mobileanalytics in the Pulumi.localstack.yml file
pulumilocal up
```

CODE:
```
import os

import pulumi_awsx as awsx
from utils import resource_utils

# create an ecr repository in aws
repo = awsx.ecr.Repository(
    SOME_NAME,
)

# create an image and deploy to that repository
image = awsx.ecr.Image(
    ANOTHER_NAME,
    repository_url=repo.url,
    path=PATH_TO_DOCKER_FILE_AND_STUFF),
)
```

### Environment

```markdown
- OS: 

uname -a
Linux xdino 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

- LocalStack:

localstack --version
1.2.0
```

### Anything else?

https://pulumi-community.slack.com/archives/C026EE6N2VB/p1668557766238449

**Comment by ToddG** [comment]
I have narrowed this down a bit: ```invocation of aws:ecr/getCredentials:getCredentials returned an error: error reading from server: EOF```

Code
```python
import pulumi_awsx as awsx
import pulumi_aws as aws

repo = awsx.ecr.Repository(
    "some-name",
)
# THIS WILL FAIL
aws.ecr.get_credentials(registry_id=repo.repository.id)
```

Error
```bash
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/home/todd/tmp_5cuvoaql/backend-project-microservice/deploy/pulumi/./__main__.py", line 20, in <module>
        aws.ecr.get_credentials(registry_id=repo.repository.id)
      File "/home/todd/tmp_5cuvoaql/backend-project-microservice/deploy/pulumi/venv/lib/python3.10/site-packages/pulumi_aws/ecr/get_credentials.py", line 91, in get_credentials
        __ret__ = pulumi.runtime.invoke('aws:ecr/getCredentials:getCredentials', __args__, opts=opts, typ=GetCredentialsResult).value
      File "/home/todd/tmp_5cuvoaql/backend-project-microservice/deploy/pulumi/venv/lib/python3.10/site-packages/pulumi/runtime/invoke.py", line 144, in invoke
        raise invoke_error
    Exception: invoke of aws:ecr/getCredentials:getCredentials failed: invocation of aws:ecr/getCredentials:getCredentials returned an error: error reading from server: EOF

    panic: runtime error: index out of range [0] with length 0

```

**Comment by ToddG** [comment]
@dominikschubert You seem to be the export in this area... any interest in tackling this or suggestions?

**Comment by ToddG** [comment]
I may have a workaround... manually push the image:

So instead of using:

```
# create an image and deploy to that repository
image = awsx.ecr.Image(
    IMAGE_NAME,
    repository_url=repo.url,
    path=PATH_TO_DOCKER_FILE_AND_STUFF),
)
```

Use [docker](https://pypi.org/project/docker/) to push the image like this:

1. Set a flag in the `Pulumi.localstack.yaml` file:

```
config:
 app:localstack: "true"
```

1. Grab the flag in the `pulumi` __main__.py and use this to either deploy to aws.ecr or to the localstack:

```
import os

import docker
import pulumi
import pulumi_awsx as awsx

config = pulumi.Config()
localstack = config.get(key="localstack", default=None),


# create an ecr repository in aws
repo = awsx.ecr.Repository(
    REPO_NAME,
)

docker_build_dir = {path to docker build dir with Dockerfile, etc}

if localstack:
    # This code is a workaround for https://github.com/localstack/localstack/issues/7186

    client = docker.from_env()

    def build_and_push(build_dir: str, url: str, tag: str) -> None:
        client.images.build(path=build_dir, tag=tag)
        client.images.push(repository=url, tag=tag)

    repo.url.apply(
        lambda repo_url: build_and_push(build_dir=docker_build_dir, url=repo_url, tag="latest")
    )
else:
    # create an image and deploy to aws ecr
    image = awsx.ecr.Image(
        resource_utils.get_name(awsx.ecr.Image),
        repository_url=repo.url,
        path=docker_build_dir,
    )
```

I still need to launch the image. Will update ticket when done.

**Comment by whummer** [comment]
Hi @ToddG , thanks for reporting. We haven't been able to fully replicate this issue so far. Could this be related to diverging state - Pulumi recording a certain state, then LocalStack is restarted (with the ECR state flushed/removed), and then Pulumi makes a request to ECR `get_authorization_token` with a registry ID that is no longer valid?

When deploying the following script in a fresh install of LocalStack:
```
import pulumi_awsx as awsx
import pulumi_aws as aws
repo = awsx.ecr.Repository("some-name")
aws.ecr.get_credentials(registry_id=repo.repository.id)
```
... the following error is reported by Pulumi: 
```
$ pulumilocal up
Previewing update (localstack):
     Type                           Name                    Plan       Info
 +   pulumi:pulumi:Stack            new-project-localstack  create     1 error; 2 warnings
 +   └─ awsx:ecr:Repository         some-name               create
 +      ├─ aws:ecr:Repository       some-name               create
 +      └─ aws:ecr:LifecyclePolicy  some-name               create


Diagnostics:
  pulumi:pulumi:Stack (new-project-localstack):
    warning: provider config warning: Use s3_use_path_style instead.
    warning: provider config warning: Use s3_use_path_style instead.
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "./__main__.py", line 13, in <module>
        result = aws.ecr.get_credentials(registry_id=repo.repository.id)
      File "venv/lib/python3.10/site-packages/pulumi_aws/ecr/get_credentials.py", line 91, in get_credentials
        __ret__ = pulumi.runtime.invoke('aws:ecr/getCredentials:getCredentials', __args__, opts=opts, typ=GetCredentialsResult).value
      File "venv/lib/python3.10/site-packages/pulumi/runtime/invoke.py", line 144, in invoke
        raise invoke_error
    Exception: invoke of aws:ecr/getCredentials:getCredentials failed: Missing required argument: The argument "registry_id" is required, but no definition was found. ()
```

Are you able to replicate this behavior, when bootstrapping an entirely new Pulumi stack and a fresh LocalStack instance?

Also, can you please pull the `latest` Docker image and confirm if the problem still persists, also when using the latest pulumi version (`v3.50.2` at the time of writing). Thanks for your help!

**Comment by whummer** [comment]
Hi again @ToddG , quick follow-up on my message above. Does this problem still persist after pulling the `latest` Docker image? Please keep us posted on how it goes.. Thanks

**Comment by whummer** [comment]
Closing as resolved. Please do let us know if the problem persists. Happy to look into it further in that case! Thanks

**Comment by rportugal** [comment]
@whummer  I have a repo that reproduces this issue: https://github.com/rportugal/localstack-ecr-issue

**Comment by DavidHooper** [comment]
Issue appears to be with a Terraform go routine.

Registry ID is 000000000000 from localstack, it gets created fine and exists. The API call to get the authorisation token also works, however the Terraform go routine fails to parse it.

```
registryId: 000000000000
    error: Running program '<redacted>' failed with an unhandled exception:
    Error: invocation of aws:ecr/getCredentials:getCredentials returned an error: error reading from server: EOF
        at Object.callback (/'<redacted>/node_modules/.pnpm/@pulumi+pulumi@3.55.0/node_modules/@pulumi/runtime/invoke.ts:172:33)
        at Object.onReceiveStatus (/'<redacted>/node_modules/.pnpm/@grpc+grpc-js@1.3.8/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/'<redacted>/node_modules/.pnpm/@grpc+grpc-js@1.3.8/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/'<redacted>/node_modules/.pnpm/@grpc+grpc-js@1.3.8/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /'<redacted>/node_modules/.pnpm/@grpc+grpc-js@1.3.8/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:77:11)

    000000000000

    panic: runtime error: index out of range [0] with length 0
    goroutine 118 [running]:
    github.com/hashicorp/terraform-provider-aws/internal/service/ecr.dataSourceAwsEcrCredentialsRead(0xc002c2af00, {0xd3a9ee0?, 0xc0018bf800?})
        /home/runner/work/pulumi-aws/pulumi-aws/upstream/internal/service/ecr/credentials_data_source.go:60 +0x3f1
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xe907ed8?, {0xe907ed8?, 0xc000126008?}, 0xd?, {0xd3a9ee0?, 0xc0018bf800?})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220824175045-450992f2f5b9/helper/schema/resource.go:717 +0x178
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000d04d20, {0xe907ed8, 0xc000126008}, 0xc002c2ae80, {0xd3a9ee0, 0xc0018bf800})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220824175045-450992f2f5b9/helper/schema/resource.go:948 +0x145
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.ReadDataApply({0xe932be0?}, {0xd460ad4, 0x13}, {0xe918108?, 0xc002c2ae80})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.40.0/pkg/tfshim/sdk-v2/provider.go:153 +0xc5
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Invoke(0xc002ca6000, {0xe907f48, 0xc004ffe2a0}, 0xc004ff8400)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.40.0/pkg/tfbridge/provider.go:1216 +0x799
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler.func1({0xe907f48, 0xc004ffe2a0}, {0xc6c53e0?, 0xc004ff8400})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.53.1/proto/go/provider_grpc.pb.go:480 +0x7b
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0xe907f48, 0xc004ffe1e0}, {0xc6c53e0, 0xc004ff8400}, 0xc001dc89e0, 0xc000a892f0)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Invoke_Handler({0xd240900?, 0xc002ca6000}, {0xe907f48, 0xc004ffe1e0}, 0xc0044c7a40, 0xc0023c1f40)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.53.1/proto/go/provider_grpc.pb.go:482 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000550000, {0xe918be0, 0xc002d3c000}, 0xc004ff6a20, 0xc002c79dd0, 0x16fff000, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
    google.golang.org/grpc.(*Server).handleStream(0xc000550000, {0xe918be0, 0xc002d3c000}, 0xc004ff6a20, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:963 +0x28a
```

**Comment by chris-stetter** [comment]
This is still an issue on `localstack 2.0.2` and `pulumi-aws 5.37.0`.
