### ISSUE TITLE
bug: API Gateway websocket authorizer does not forward the request properly to the connect handler

### ISSUE THREAD

**Issue by fmaronnaud** [localstack/localstack#7191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When connecting to the websocket, the request is not properly forwarded to the connect handler (lambda), the connection is closed, and the following error is thrown:
```
localstack_main | 2022-11-16T14:30:43.756 DEBUG --- [uest_thread)] l.s.awslambda.lambda_api   : Lambda invocation duration: 1486.27ms
localstack_main | 2022-11-16T14:30:43.760  INFO --- [ncthread2918] l.s.apigateway.authorizers : Received authorizer result: {"context":{"booleanKey":true,"numberKey":123,"stringKey":"stringval"},"policyDocument":{"Statement":[{"Action":"execute-api:Invoke","Effect":"Allow","Resource":"*"}],"Version":"2012-10-17"},"principalId":"me"}
localstack_main |
localstack_main | 2022-11-16T14:30:43.761 DEBUG --- [uncthread710] l.utils.websockets         : Received error on $connect event handler - denying WebSocket connection: 'NoneType' object has no attribute 'get'
localstack_main | 2022-11-16T14:30:43.762  INFO --- [ncthread2918] localstack.utils.threads   : Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fc53a7d0ca0>(None) failed: 'NoneType' object has no attribute 'get' Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/utils/threads.py", line 58, in run
localstack_main |     result = self.func(self.params, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
localstack_main |     return fn(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/integrations.py.enc", line 86, in A
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/apigateway_utils.py.enc", line 237, in create_lambda_integration_payload_event
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/apigateway_utils.py.enc", line 303, in create_event_v1_integration_payload
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/apigateway_utils.py.enc", line 308, in _get_authorizer_context
localstack_main | AttributeError: 'NoneType' object has no attribute 'get'
localstack_main |
localstack_main | 2022-11-16T14:30:43.762 DEBUG --- [ncthread2918] localstack.utils.threads   : FINISHED: <Future at 0x7fc4fa3d7ee0 state=finished raised AttributeError>
localstack_main | 2022-11-16T14:30:43.766  INFO --- [uncthread710] websockets.server          : connection closed
```

### Expected Behavior

When connecting to the websocket, the request is properly forwarded to the connect handler (lambda), the connection is closed, and no error are thrown

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

- docker compose-up
- Create a custom authorizer for API Gateway websocket
- Add this custom authorizer on the connect handler
- Connect to the websocket

### Environment

```markdown
- OS: Windows
- LocalStack: 1.2.1.dev
```

### Anything else?

**Authorizer lambda event:**

Localstack: 
```
{
    "version": "1.0",
    "type": "REQUEST",
    "methodArn": "arn:aws:execute-api:us-east-1:000000000000:ea5b4b1c/None/$$connect",
    "identitySource": "route.request.querystring.token",
    "authorizationToken": "",
    "resource": "/",
    "path": "/",
    "httpMethod": null,
    "headers": {
        "sec-websocket-version": "13",
        "sec-websocket-key": "ABfuAsj8FjeD/6RHRBwaeA==",
        "connection": "Upgrade",
        "upgrade": "websocket",
        "sec-websocket-extensions": "permessage-deflate; client_max_window_bits",
        "host": "localhost:4511"
    },
    "queryStringParameters": {
        "token": "1234567"
    },
    "pathParameters": {},
    "stageVariables": null,
    "requestContext": {
        "path": "/",
        "accountId": "000000000000",
        "apiId": "ea5b4b1c",
        "resourcePath": "/",
        "domainPrefix": "localhost",
        "domainName": "localhost",
        "resourceId": null,
        "requestId": "929549dd",
        "identity": {
            "accountId": "000000000000",
            "sourceIp": "",
            "userAgent": null
        },
        "stage": null,
        "httpMethod": null
    }
}
```

AWS:
```
{
    "type": "REQUEST",
    "methodArn": "arn:aws:execute-api:us-east-1:412082536832:qwerty/dev/$connect",
    "headers": {
        "Connection": "upgrade",
        "content-length": "0",
        "Host": "qwerty.execute-api.us-east-1.amazonaws.com",
        "Sec-WebSocket-Extensions": "permessage-deflate; client_max_window_bits",
        "Sec-WebSocket-Key": "3e9EMziMv6WJxOkXQ==",
        "Sec-WebSocket-Version": "13",
        "Upgrade": "websocket",
        "X-Amzn-Trace-Id": "Root=1-6374f33e-0f3721a17111942153e576",
        "X-Forwarded-For": "XXX.XXX.XXX.XXX",
        "X-Forwarded-Port": "443",
        "X-Forwarded-Proto": "https"
    },
    "multiValueHeaders": {
        "Connection": [
            "upgrade"
        ],
        "content-length": [
            "0"
        ],
        "Host": [
            "qwerty.execute-api.us-east-1.amazonaws.com"
        ],
        "Sec-WebSocket-Extensions": [
            "permessage-deflate; client_max_window_bits"
        ],
        "Sec-WebSocket-Key": [
            "3e9EMziMv6WJxOkXQ=="
        ],
        "Sec-WebSocket-Version": [
            "13"
        ],
        "Upgrade": [
            "websocket"
        ],
        "X-Amzn-Trace-Id": [
            "Root=1-6374f33e-0f3721a1711194de2153e576"
        ],
        "X-Forwarded-For": [
            "XXX.XXX.XXX.XXX"
        ],
        "X-Forwarded-Port": [
            "443"
        ],
        "X-Forwarded-Proto": [
            "https"
        ]
    },
    "queryStringParameters": {
        "token": "1234567"
    },
    "multiValueQueryStringParameters": {
        "token": [
            "1234567"
        ]
    },
    "stageVariables": {},
    "requestContext": {
        "routeKey": "$connect",
        "eventType": "CONNECT",
        "extendedRequestId": "bsrxwHpHoAMF_1g=",
        "requestTime": "16/Nov/2022:14:27:10 +0000",
        "messageDirection": "IN",
        "stage": "dev",
        "connectedAt": 1668608830204,
        "requestTimeEpoch": 1668608830218,
        "identity": {
            "sourceIp": "XXX.XXX.XXX.XXX"
        },
        "requestId": "bsrxwHpHoAMF_1g=",
        "domainName": "qwerty.execute-api.us-east-1.amazonaws.com",
        "connectionId": "bsrxwZoAMCL3w=",
        "apiId": "qwerty"
    }
}
```

Simple authorizer javascript code (this will always allow the connection):
```
exports.authorizationHandler = function(event, context, callback) {        
  console.log('Received event:', JSON.stringify(event, null, 2));

 // A simple REQUEST authorizer example to demonstrate how to use request 
 // parameters to allow or deny a request. In this example, a request is  
 // authorized if the client-supplied HeaderAuth1 header and QueryString1 query parameter
 // in the request context match the specified values of
 // of 'headerValue1' and 'queryValue1' respectively.

 // Retrieve request parameters from the Lambda function input:
 var headers = event.headers;
 var queryStringParameters = event.queryStringParameters;
 var stageVariables = event.stageVariables;
 var requestContext = event.requestContext;
     
 // Parse the input for the parameter values
 var tmp = event.methodArn.split(':');
 var apiGatewayArnTmp = tmp[5].split('/');
 var awsAccountId = tmp[4];
 var region = tmp[3];
 var ApiId = apiGatewayArnTmp[0];
 var stage = apiGatewayArnTmp[1];
 var route = apiGatewayArnTmp[2];
     
 // Perform authorization to return the Allow policy for correct parameters and 
 // the 'Unauthorized' error, otherwise.
 var authResponse = {};
 var condition = {};
  condition.IpAddress = {};
  callback(null, generateAllow('me', '*'));
}
  
// Helper function to generate an IAM policy
var generatePolicy = function(principalId, effect, resource) {
 // Required output:
 var authResponse = {};
  authResponse.principalId = principalId;
 if (effect && resource) {
     var policyDocument = {};
      policyDocument.Version = '2012-10-17'; // default version
     policyDocument.Statement = [];
     var statementOne = {};
      statementOne.Action = 'execute-api:Invoke'; // default action
     statementOne.Effect = effect;
      statementOne.Resource = resource;
      policyDocument.Statement[0] = statementOne;
      authResponse.policyDocument = policyDocument;
  }
 // Optional output with custom properties of the String, Number or Boolean type.
 authResponse.context = {
     "stringKey": "stringval",
     "numberKey": 123,
     "booleanKey": true
  };
 return authResponse;
}
  
var generateAllow = function(principalId, resource) {
 return generatePolicy(principalId, 'Allow', resource);
}
  
var generateDeny = function(principalId, resource) {
 return generatePolicy(principalId, 'Deny', resource);
}
```

**Comment by whummer** [comment]
Thanks for reporting @fmaronnaud, and apologies for the long delay on this one. We have now pushed a couple of enhancements for API Gateway WebSocket authorizers, which should improve the parity of the event payload with real AWS. Can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

**Comment by fmaronnaud** [comment]
Hey there,
I was able to do some testing with the latest version of Localstack and I can confirm that the authorizer seems to work properly now!
Thank you for looking into this
