### ISSUE TITLE
Getting TooManyRedirects Error when installing with Pip

### ISSUE THREAD

**Issue by mugizico** [localstack/localstack#720]
When  I run `pip install localstack` on MacOS Sierra with `Python 3.6.5` installed I am getting this error message:
```jeanpaulmugizi$ pip install localstack
Collecting localstack
Exception:
Traceback (most recent call last):
  File "/Users/jeanpaulmugizi/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/jeanpaulmugizi/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/Users/jeanpaulmugizi/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/jeanpaulmugizi/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/Users/jeanpaulmugizi/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/Users/jeanpaulmugizi/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/Users/jeanpaulmugizi/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pip/download.py", line 853, in _download_http_url
    stream=True,
  File "/Users/jeanpaulmugizi/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Users/jeanpaulmugizi/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/Users/jeanpaulmugizi/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/jeanpaulmugizi/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/jeanpaulmugizi/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 640, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/jeanpaulmugizi/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 140, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
pip._vendor.requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
```

**Comment by mugizico** [comment]
working now. looks like it was just a `pypi` server issue.
