### ISSUE TITLE
[Pro] bug: GetAtt `CanonicalHostedZoneID` on ALB resource fails

### ISSUE THREAD

**Issue by gooftroop** [localstack/localstack#7210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following code:

```ts
const loadBalancer = new elbv2.ApplicationLoadBalancer(this, `${id}ALB`, {
            vpc,
            http2Enabled: true,
            internetFacing: true,
            loadBalancerName: `${serviceName.toLowerCase()}-alb`,
            securityGroup: new ec2.SecurityGroup(this, `${id}ALBSecurityGroup`, {
                vpc,
                allowAllOutbound: true,
                securityGroupName: `${serviceName.toLowerCase()}-alb-sg`,
            }),
            vpcSubnets: vpc.selectSubnets({
                subnetType: ec2.SubnetType.PUBLIC,
            }),
        });

new route53.ARecord(this, `${id}ARecord`, {
            recordName: '<hidden>',
            zone: hostedZone,
            target: route53.RecordTarget.fromAlias(new LoadBalancerTarget(loadBalancer)),
            ttl: Duration.minutes(1),
});
```

yields the following error: `Missing required parameter in ChangeBatch.Changes[0].ResourceRecordSet.AliasTarget: "HostedZoneId"`.

### Expected Behavior

An A Record is created

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up --build

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    cdklocal deploy --all

### Environment

```markdown
- OS: Windows 11, WSL2 Ubuntu 20
- LocalStack: latest
```

### Anything else?

**Stack Trace:**

ocalstack  | 2022-11-19T19:55:31.242 DEBUG --- [ Thread-1197] l.u.c.template_deployer    : Error applying changes for CloudFormation stack "TheSousChefWebFargateStackDevelopment": Parameter validation failed:
localstack  | Missing required parameter in ChangeBatch.Changes[0].ResourceRecordSet.AliasTarget: "HostedZoneId" Traceback (most recent call last):
localstack  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1018, in configure_resource_via_sdk
localstack  |     result = function(**params)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
localstack  |     return self._make_api_call(operation_name, kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 901, in _make_api_call
localstack  |     request_dict = self._convert_to_request_dict(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 962, in _convert_to_request_dict
localstack  |     request_dict = self._serializer.serialize_to_request(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
localstack  |     raise ParamValidationError(report=report.generate_report())
localstack  | botocore.exceptions.ParamValidationError: Parameter validation failed:
localstack  | Missing required parameter in ChangeBatch.Changes[0].ResourceRecordSet.AliasTarget: "HostedZoneId"
localstack  | 
localstack  | During handling of the above exception, another exception occurred:
localstack  | 
localstack  | Traceback (most recent call last):
localstack  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1569, in _run
localstack  |     self.do_apply_changes_in_loop(changes, stack)
localstack  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1646, in do_apply_changes_in_loop
localstack  |     self.apply_change(change, stack=stack)
localstack  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1723, in apply_change
localstack  |     result = deploy_resource(self, resource_id)
localstack  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 853, in deploy_resource
localstack  |     result = execute_resource_action(resource_id, stack, ACTION_CREATE)
localstack  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 896, in execute_resource_action
localstack  |     result = configure_resource_via_sdk(
localstack  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1035, in configure_resource_via_sdk
localstack  |     raise e
localstack  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1030, in configure_resource_via_sdk
localstack  |     result = function(**converted_params)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
localstack  |     return self._make_api_call(operation_name, kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 901, in _make_api_call
localstack  |     request_dict = self._convert_to_request_dict(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 962, in _convert_to_request_dict
localstack  |     request_dict = self._serializer.serialize_to_request(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
localstack  |     raise ParamValidationError(report=report.generate_report())

**CloudFormation snippet:**

```json
"TheSousChefWebFargateStackDevelopmentARecordAD1F1374": {
   "Type": "AWS::Route53::RecordSet",
   "Properties": {
    "Name": "sous-chef-web.thesouschef.local.",
    "Type": "A",
    "AliasTarget": {
     "DNSName": {
      "Fn::Join": ["", ["dualstack.", {"Fn::GetAtt": [
          "TheSousChefWebFargateStackDevelopmentALBBED554CE",
          "DNSName"
         ]
        }
       ]
      ]
     },
     "HostedZoneId": {
      "Fn::GetAtt": [
       "TheSousChefWebFargateStackDevelopmentALBBED554CE",
       "CanonicalHostedZoneID"
      ]
     }
    },
    "HostedZoneId": "/hostedzone/6MAR9YN56REMX5Y"
   },
   "Metadata": {
    "aws:cdk:path": "TheSousChefWebFargateStackDevelopment/TheSousChefWebFargateStackDevelopmentARecord/Resource"
   }
  },
```

**Comment by gooftroop** [comment]
This is preventing my team from testing various webserver deployments and integrations. We can continue testing locally for now, but will run into this as a blocker soon
