### ISSUE TITLE
bug: lambda code exception NoSuchMethodError for StringUtils class when using of route53 client

### ISSUE THREAD

**Issue by vetss** [localstack/localstack#7223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We use AWS SDK version 2.17.235 in our java lambda to access route53 localstack service.
When invoking of method route53.listResourceRecordSets(ListResourceRecordSetsRequest) we experiense a following Exception:

```
'java.lang.String software.amazon.awssdk.utils.StringUtils.replace(java.lang.String, java.lang.String, java.lang.String)': java.lang.NoSuchMethodError
java.lang.NoSuchMethodError: 'java.lang.String software.amazon.awssdk.utils.StringUtils.replace(java.lang.String, java.lang.String, java.lang.String)'
        at software.amazon.awssdk.protocols.core.PathMarshaller$NonGreedyPathMarshaller.marshall(PathMarshaller.java:64)
        at software.amazon.awssdk.protocols.xml.internal.marshall.SimpleTypePathMarshaller$SimplePathMarshaller.marshall(SimpleTypePathMarshaller.java:66)
        at software.amazon.awssdk.protocols.xml.internal.marshall.XmlProtocolMarshaller.doMarshall(XmlProtocolMarshaller.java:104)
        at software.amazon.awssdk.protocols.xml.internal.marshall.XmlProtocolMarshaller.marshall(XmlProtocolMarshaller.java:80)
        at software.amazon.awssdk.protocols.xml.internal.marshall.XmlProtocolMarshaller.marshall(XmlProtocolMarshaller.java:49)
        at software.amazon.awssdk.services.route53.transform.ListResourceRecordSetsRequestMarshaller.marshall(ListResourceRecordSetsRequestMarshaller.java:51)
        at software.amazon.awssdk.services.route53.transform.ListResourceRecordSetsRequestMarshaller.marshall(ListResourceRecordSetsRequestMarshaller.java:31)
        at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$finalizeSdkHttpFullRequest$0(BaseClientHandler.java:68)
        at software.amazon.awssdk.core.internal.util.MetricUtils.measureDuration(MetricUtils.java:50)
        at software.amazon.awssdk.core.internal.handler.BaseClientHandler.finalizeSdkHttpFullRequest(BaseClientHandler.java:67)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:151)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:175)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
        at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
        at software.amazon.awssdk.services.route53.DefaultRoute53Client.listResourceRecordSets(DefaultRoute53Client.java:5119)

```
Please note that **PathMarshaller** class is located in **/var/task/** folder but **StringUtils** is loaded from the jar **/var/runtime/lib/aws-lambda-java-core-1.2.0.jar** It looks like StringUtils is loaded from a wrong place out of a project classes.

Is there any way / workaround to avoid of such sort of Exceptions.

### Expected Behavior

No exception

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

localstack is run in a docker container from a golang application. 
Lambda function is invoked in a separate docker container.
runtime     = "java11"
LAMBDA_EXECUTOR=docker
LAMBDA_REMOTE_DOCKER=true

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

route53.listResourceRecordSets(ListResourceRecordSetsRequest.builder()
                        .hostedZoneId(env.get(HOSTED_ZONE_ID.name()))
                        .startRecordType(SRV)
                        .startRecordName(recordName)
                        .maxItems("1")
                        .build())

### Environment

```markdown
- OS:MacOS Monterey 12.6
- LocalStack: 1.2.0
```

**Comment by dfangl** [comment]
Hi!
Can you try setting `PROVIDER_OVERRIDE_LAMBDA=asf` to use our new lambda provider? It should provide way more parity in Lambda, especially in the environments, and might just fix your issue!
