### ISSUE TITLE
ImportError: No module named localstack_client.config

### ISSUE THREAD

**Issue by JsonFn** [localstack/localstack#724]
Every worked fine, but today it suddenly doesn't work. Even I install localstack-client (pip install localstack-client), it still doesn't work. But mainly it can't find module localstack_client.config. Searching comes with similar issues like

    https://github.com/localstack/localstack/issues/505 
    https://github.com/localstack/localstack/issues/593

But basically the problem remains.

Manually build from source throws other error which complains warrant-ext doesn't have requirements_test.txt 

`pip install localstack` throws 

    Downloading https://files.pythonhosted.org/packages/4e/74/003953e76b03c47b1355cbee7627fa939a290a4fc54c89b028d5b679d221/warrant-ext-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-U4q5kK/warrant-ext/setup.py", line 37, in <module>
        'test': parse_requirements('requirements_test.txt')
      File "/tmp/pip-install-U4q5kK/warrant-ext/setup.py", line 6, in parse_requirements
        lineiter = (line.strip() for line in open(filename))
    IOError: [Errno 2] No such file or directory: 'requirements_test.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-U4q5kK/warrant-ext/

My python version 2.7, localstack 0.1.11, and Java 1.8.0_151

    [info] Exception encountered when attempting to run a suite with class name: org.scalatest.DeferredAbortedSuite *** ABORTED ***
    [info]   java.lang.RuntimeException: java.lang.IllegalStateException: Failed to run command 'bash -c cd '/tmp/localstack_install_dir'; . .venv/bin/activate;  python -c 'import localstack_client.config; print(localstack_client.config.get_service_endpoint("s3"))'', return code 1.
    [info] STDOUT: 
    [info] STDERR: Traceback (most recent call last):
    [info]   File "<string>", line 1, in <module>
    [info] ImportError: No module named localstack_client.config
    [info]   at cloud.localstack.LocalstackTestRunner.exec(LocalstackTestRunner.java:235)
    [info]   at cloud.localstack.LocalstackTestRunner.exec(LocalstackTestRunner.java:204)
    [info]   at cloud.localstack.LocalstackTestRunner.getEndpoint(LocalstackTestRunner.java:195)
    [info]   at cloud.localstack.LocalstackTestRunner.ensureInstallationAndGetEndpoint(LocalstackTestRunner.java:177)
    [info]   at cloud.localstack.LocalstackTestRunner.getEndpointS3(LocalstackTestRunner.java:51)
    [info]   at cloud.localstack.TestUtils.getEndpointConfigurationS3(TestUtils.java:83)
    [info]   at cloud.localstack.TestUtils.getClientS3(TestUtils.java:54)
    [info]   ...
    [info]   Cause: java.lang.IllegalStateException: Failed to run command 'bash -c cd '/tmp/localstack_install_dir'; . .venv/bin/activate;  python -c 'import localstack_client.config; print(localstack_client.config.get_service_endpoint("s3"))'', return code 1.
    [info] STDOUT: 
    [info] STDERR: Traceback (most recent call last):
    [info]   File "<string>", line 1, in <module>
    [info] ImportError: No module named localstack_client.config
    [info]   at cloud.localstack.LocalstackTestRunner.exec(LocalstackTestRunner.java:222)
    [info]   at cloud.localstack.LocalstackTestRunner.exec(LocalstackTestRunner.java:204)
    [info]   at cloud.localstack.LocalstackTestRunner.getEndpoint(LocalstackTestRunner.java:195)
    [info]   at cloud.localstack.LocalstackTestRunner.ensureInstallationAndGetEndpoint(LocalstackTestRunner.java:177)
    [info]   at cloud.localstack.LocalstackTestRunner.getEndpointS3(LocalstackTestRunner.java:51)
    [info]   at cloud.localstack.TestUtils.getEndpointConfigurationS3(TestUtils.java:83)
    [info]   at cloud.localstack.TestUtils.getClientS3(TestUtils.java:54)
    [info]   ...

**Comment by jharriman** [comment]
This is potentially related to a fix for https://github.com/localstack/localstack/issues/721

**Comment by harsha-ravs** [comment]
> Should be fixed in the latest version on master. Closing this issue, please comment on #721 if the problem persists. Thanks

The same issue still persists. Any hints will be much appreciated. I will also provide this info in #721

I am 

`
C:\git_hr\localstack>pip show localstack
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
Name: localstack
Version: 1.1.0
Summary: LocalStack - A fully functional local Cloud stack
Home-page: https://github.com/localstack/localstack
Author: LocalStack Contributors
Author-email: info@localstack.cloud
License: Apache License 2.0
Location: c:\python310\lib\site-packages
Requires: apispec, boto3, cachetools, click, localstack-client, localstack-ext, plux, psutil, python-dotenv, pyyaml, requests, rich, semver, stevedore, tailer
Required-by: localstack-ext

C:\git_hr\localstack>localstack --version

C:\git_hr\localstack>python "C:\Python310\Scripts\\localstack" --version
Traceback (most recent call last):
  File "C:\Python310\Scripts\\localstack", line 23, in <module>
    main()
  File "C:\Python310\Scripts\\localstack", line 17, in main
    from localstack.cli import main
ImportError: No module named localstack.cli

C:\git_hr\localstack>
`
