### ISSUE TITLE
bug: Presigned URL post not saves nothing

### ISSUE THREAD

**Issue by nicolkill** [localstack/localstack#7247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Following the [next post](https://github.com/localstack/localstack/issues/6588) about solve issues related to presigned urls 

im uploading a file from code (Elixir) to a presigned url and gives me next log in docker container

```
WARNING:localstack.services.s3.s3_utils: Signatures do not match, but not raising an error, as S3_SKIP_SIGNATURE_VALIDATION=1
```

Checking the code says that its ok but using the next command

```
awslocal s3api list-objects --bucket my-bucket
```

its showing me empty response

### Expected Behavior

I dont know if its an issue with the presigned urls but i also testes with direct command `awslocal s3 cp /route/to/file s3://my-bucket` and saves the file and also the `list-objects` command shows me a record

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Upload to a presigned url an a file

### Environment

```markdown
- OS:Elementary OS 6.1
- LocalStack: 0.14.5
```

**Comment by thrau** [comment]
hey @nicolkill it seems you are using a pretty old version of localstack. could you give the latest docker image a try? if it doesn't work with the latest image, you could also try the latest image but start it with `PROVIDER_OVERRIDE_S3=asf`

**Comment by nicolkill** [comment]
@thrau stills without working, but its an different error

seems like the request its received to the localstack router but doesnt recognize the service or the order, i dont know if im using the right url format in this version

the docker-compose config

```
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
    environment:
      DEBUG: 1
      SERVICES: s3
      DISABLE_CORS_CHECKS: 1
      S3_SKIP_SIGNATURE_VALIDATION: 1
    volumes:
      - ./.localstack:/var/lib/localstack
      - ./scripts/init_localstack.sh:/docker-entrypoint-initaws.d/init_localstack.sh
    networks:
      default:
        aliases:
          - fraud-images-dev.s3.localhost.localstack
```

the requests

```
%{
 fields: %{
     "Policy" => "some_policy_extra_long_code",
     "X-Amz-Algorithm" => "AWS4-HMAC-SHA256",
     "X-Amz-Credential" => "some_credential/some_another_number/us-west-2/s3/aws4_request",
     "X-Amz-Date" => "20221128T173252Z",
     "X-Amz-Signature" => "some_another_string_that_its_the_signature",
     "key" => "my/route/to/file"
   },
   url: "http://my_container.s3.localhost.localstack:4566"
 }
```

```
"{\"message\": \"Unexpected exception\", \"error\": \"400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\", \"type\": \"ClientDisconnected\"}"
```

and the localstack container shows me this log, seems an error on python

```
2022-11-28T17:32:52.295 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 32, in __call__
    service = determine_aws_service_name(context.request)
  File "/opt/code/localstack/localstack/aws/protocol/service_router.py", line 358, in determine_aws_service_name
    values = request.values
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/utils.py", line 107, in __get__
    value = self.fget(obj)  # type: ignore
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 448, in values
    sources.append(self.form)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/utils.py", line 107, in __get__
    value = self.fget(obj)  # type: ignore
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 428, in form
    self._load_form_data()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 266, in _load_form_data
    data = parser.parse(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 263, in parse
    return parse_func(self, stream, mimetype, content_length, options)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 140, in wrapper
    return f(self, stream, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 290, in _parse_multipart
    form, files = parser.parse(stream, boundary, content_length)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 418, in parse
    for data in iterator:
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 653, in _make_chunk_iter
    item = _read(buffer_size)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 925, in read
    return self.on_disconnect()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 893, in on_disconnect
    raise ClientDisconnected()
werkzeug.exceptions.ClientDisconnected: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2022-11-28T17:32:52.296 DEBUG --- [   asgi_gw_0] l.aws.handlers.fallback    : setting internal failure response for 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2022-11-28T17:32:52.296 ERROR --- [   asgi_gw_0] localstack.aws.chain       : exception while running response handler
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 155, in _call_response_handlers
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/logging.py", line 47, in __call__
    self._log(context, response)
  File "/opt/code/localstack/localstack/aws/handlers/logging.py", line 142, in _log
    "input": restore_payload(context.request),
  File "/opt/code/localstack/localstack/http/request.py", line 222, in restore_payload
    data = request.data
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/utils.py", line 107, in __get__
    value = self.fget(obj)  # type: ignore
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 354, in data
    return self.get_data(parse_form_data=True)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 404, in get_data
    self._load_form_data()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 266, in _load_form_data
    data = parser.parse(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 263, in parse
    return parse_func(self, stream, mimetype, content_length, options)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 140, in wrapper
    return f(self, stream, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 290, in _parse_multipart
    form, files = parser.parse(stream, boundary, content_length)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/formparser.py", line 418, in parse
    for data in iterator:
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 653, in _make_chunk_iter
    item = _read(buffer_size)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 925, in read
    return self.on_disconnect()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/wsgi.py", line 893, in on_disconnect
    raise ClientDisconnected()
werkzeug.exceptions.ClientDisconnected: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

**Comment by nicolkill** [comment]
also created [this issue](https://github.com/localstack/localstack/issues/7256) that its the individual error log and some info to replicate

**Comment by bentsku** [comment]
Closing as it was part of #7256, see https://github.com/localstack/localstack/issues/7256#issuecomment-1361414622

Thanks for your report!
