### ISSUE TITLE
bug: API Gateway custom domain base path mapping error

### ISSUE THREAD

**Issue by davecardwell** [localstack/localstack#7288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using a custom domain with API gateway results in the following error response:

```sh
curl -k -H 'Content-Type: application/xml' -H 'Accept: application/json' -d '<foo>bar</foo>' https://api.example.test/v1/test
```
```json
{"message": "Unexpected exception", "error": "Parameter validation failed:\nInvalid type for parameter restApiId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>", "type": "ParamValidationError"}
``` 

And the follow exception in the Localstack debug log:

```
2022-12-06T04:42:18.882 DEBUG --- [uest_thread)] l.services.dns_server      : Trying to resolve AliasTarget for requested name 'api.example.test.'
2022-12-06T04:42:18.883 DEBUG --- [uest_thread)] l.services.dns_server      : Found entry for AliasTarget 'api.example.test.' ('dyk7bbe2tvs.cloudfront.net')
2022-12-06T04:42:18.932 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/routes.py", line 27, in __call__
    router_response = self.router.dispatch(context.request)
  File "/opt/code/localstack/localstack/http/router.py", line 270, in dispatch
    return self.dispatcher(request, handler, args)
  File "/opt/code/localstack/localstack/http/dispatcher.py", line 123, in _dispatch
    result = endpoint(request, **args)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/router_asf.py.enc", line 21, in invoke_rest_api
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/integrations.py.enc", line 101, in invoke_api
  File "/opt/code/localstack/localstack/services/apigateway/invocations.py", line 248, in invoke_rest_api
    authorize_invocation(invocation_context)
  File "/opt/code/localstack/localstack/services/apigateway/invocations.py", line 142, in authorize_invocation
    authorizers = client.get_authorizers(restApiId=invocation_context.api_id, limit=100).get(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 901, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 962, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter restApiId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
2022-12-06T04:42:18.932 DEBUG --- [   asgi_gw_0] l.aws.handlers.fallback    : setting internal failure response for Parameter validation failed:
Invalid type for parameter restApiId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
2022-12-06T04:42:18.933  INFO --- [   asgi_gw_0] localstack.request.http    : POST /v1/test => 500
```

### Expected Behavior

Calling the same URL on the execute URL works:

```sh
curl -k -H 'Content-Type: application/xml' -H 'Accept: application/json' -d '<?xml version="1.0"?><foo>bar</foo>' https://ixvzyf3jas.execute-api.localhost.localstack.cloud/v1/test
```
```xml
<foo>bar</foo>
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    # using https://github.com/localstack/localstack/blob/master/docker-compose.yml modified so the image is `localstack/localstack-pro`

    DEBUG=true LOCALSTACK_API_KEY={redacted} docker compose up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    terraform apply

With the following Terraform config:

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

provider "aws" {
  access_key = "test"
  secret_key = "test"
  region     = "us-east-1"

  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    acm        = "http://localhost:4566"
    apigateway = "http://localhost:4566"
    route53    = "http://localhost:4566"
    sts        = "http://localhost:4566"
  }
}

resource "aws_route53_zone" "example" {
  name = "example.test"
}

resource "aws_api_gateway_rest_api" "example" {
  name = "example"

  endpoint_configuration {
    types = ["EDGE"]
  }
}

resource "aws_acm_certificate" "example" {
  domain_name       = "api.example.test"
  validation_method = "DNS"
}

resource "aws_route53_record" "example" {
  name    = aws_api_gateway_domain_name.example.domain_name
  type    = "A"
  zone_id = aws_route53_zone.example.zone_id

  alias {
    evaluate_target_health = true
    name                   = aws_api_gateway_domain_name.example.cloudfront_domain_name
    zone_id                = aws_api_gateway_domain_name.example.cloudfront_zone_id
  }
}

resource "aws_route53_record" "example_validation" {
  for_each = {
    for dvo in aws_acm_certificate.example.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }

  allow_overwrite = true
  name            = each.value.name
  records         = [each.value.record]
  ttl             = 60
  type            = each.value.type
  zone_id         = aws_route53_zone.example.zone_id
}

resource "aws_acm_certificate_validation" "example" {
  certificate_arn         = aws_acm_certificate.example.arn
  validation_record_fqdns = [for record in aws_route53_record.example_validation : record.fqdn]
}

resource "aws_api_gateway_domain_name" "example" {
  certificate_arn = aws_acm_certificate_validation.example.certificate_arn
  domain_name     = "api.example.test"
}

resource "aws_api_gateway_deployment" "example" {
  rest_api_id = aws_api_gateway_rest_api.example.id

  triggers = {
    redeployment = sha1(jsonencode([
      aws_api_gateway_integration.test.id,
    ]))
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_api_gateway_stage" "example_v1" {
  rest_api_id   = aws_api_gateway_rest_api.example.id
  deployment_id = aws_api_gateway_deployment.example.id
  stage_name    = "v1"
}

resource "aws_api_gateway_base_path_mapping" "example" {
  api_id      = aws_api_gateway_rest_api.example.id
  domain_name = aws_api_gateway_domain_name.example.domain_name
  stage_name  = aws_api_gateway_stage.example_v1.stage_name
  base_path   = aws_api_gateway_stage.example_v1.stage_name
}

resource "aws_api_gateway_resource" "test" {
  rest_api_id = aws_api_gateway_rest_api.example.id
  parent_id   = aws_api_gateway_rest_api.example.root_resource_id
  path_part   = "test"
}

resource "aws_api_gateway_method" "test" {
  rest_api_id   = aws_api_gateway_rest_api.example.id
  resource_id   = aws_api_gateway_resource.test.id
  http_method   = "POST"
  authorization = "NONE"
}

resource "aws_api_gateway_integration" "test" {
  rest_api_id = aws_api_gateway_rest_api.example.id
  resource_id = aws_api_gateway_resource.test.id
  http_method = aws_api_gateway_method.test.http_method
  type        = "MOCK"

  request_templates = {
    "application/xml" = "{\"body\":$input.json('$')}"
  }
}
```

Then:
```sh
curl -ki -XPOST -H 'Content-Type: application/xml' -H 'Accept: application/json' -d '<foo>bar</foo>' https://api.example.test/v1/test
```

### Environment

```markdown
- OS: macOS
- LocalStack: latest (1.3.1.dev / git hash 3bdbf44a / image ID 0139e2c53893)
```

**Comment by davecardwell** [comment]
@calvernaz This still appears to be an issue using the Terraform config in my issue description with the latest `localstack/localstack-pro` image (`1.3.2.dev`, `sha256:afd8d645c52f5e4af898b12f2c2f8b5a9fe9551e3c477bdd8e35d564ff9b6fe9`).

```sh
curl \
  -vk \
  --resolve api.example.test:443:127.0.0.1 \
  -H 'Content-Type: application/xml' \
  -H 'Accept: application/json' \
  -d '<foo>bar</foo>' \
  https://api.example.test/v1/test
```
```
* Added api.example.test:443:127.0.0.1 to DNS cache
* Hostname api.example.test was found in DNS cache
*   Trying 127.0.0.1:443...
* Connected to api.example.test (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=localhost.localstack.cloud
*  start date: Dec 30 11:21:58 2022 GMT
*  expire date: Mar 30 11:21:57 2023 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x156014000)
> POST /v1/test HTTP/2
> Host: api.example.test
> user-agent: curl/7.79.1
> content-type: application/xml
> accept: application/json
> content-length: 14
> 
* We are completely uploaded and fine
< HTTP/2 500 
< content-type: application/json
< content-length: 213
< access-control-allow-origin: *
< access-control-allow-methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
< access-control-allow-headers: authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request
< access-control-expose-headers: etag,x-amz-version-id
< date: Sun, 01 Jan 2023 14:56:09 GMT
< server: hypercorn-h2
< 
* Connection #0 to host api.example.test left intact
{"message": "Unexpected exception", "error": "Parameter validation failed:\nInvalid type for parameter restApiId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>", "type": "ParamValidationError"}
```
```
2023-01-01T14:57:08.831 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/routes.py", line 27, in __call__
    router_response = self.router.dispatch(context.request)
  File "/opt/code/localstack/localstack/http/router.py", line 270, in dispatch
    return self.dispatcher(request, handler, args)
  File "/opt/code/localstack/localstack/http/dispatcher.py", line 123, in _dispatch
    result = endpoint(request, **args)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/router_asf.py.enc", line 21, in invoke_rest_api
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/integrations.py.enc", line 101, in invoke_api
  File "/opt/code/localstack/localstack/services/apigateway/invocations.py", line 248, in invoke_rest_api
    authorize_invocation(invocation_context)
  File "/opt/code/localstack/localstack/services/apigateway/invocations.py", line 142, in authorize_invocation
    authorizers = client.get_authorizers(restApiId=invocation_context.api_id, limit=100).get(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 919, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 990, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter restApiId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
2023-01-01T14:57:08.833 DEBUG --- [   asgi_gw_0] l.aws.handlers.fallback    : setting internal failure response for Parameter validation failed:
Invalid type for parameter restApiId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
2023-01-01T14:57:08.833  INFO --- [   asgi_gw_0] localstack.request.http    : POST /v1/test => 500
```

Adding in `-H 'Host: 6i9utfgwtk.execute-api.localhost.localstack.cloud'` _does_ work, but I was expecting the custom domain to be working now.
