### ISSUE TITLE
bug: GitHub Rate Limiting for Fetching Kinesis Mock Versions

### ISSUE THREAD

**Issue by musketyr** [localstack/localstack#7292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

LocalStack won't start with a following issue.

```
LocalStack version: 1.2.0
2022-12-06 11:28:30,319 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
LocalStack Docker container id: 146bee75e503
LocalStack build date: 2022-10-07
LocalStack build git hash: 9be2a7aa

Error starting infrastructure: Could not get list of releases from https://api.github.com/repos/etspaceman/kinesis-mock/releases/tags/0.2.5: {"message":"API rate limit exceeded for 34.252.28.125. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 420, in start_infra
    thread = do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/code/localstack/localstack/services/infra.py", line 516, in do_start_infra
    prepare_installation()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 77, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 470, in prepare_installation
    install.install_components(apis)
  File "/opt/code/localstack/localstack/services/install.py", line 411, in install_components
    parallelize(install_component, names)
  File "/opt/code/localstack/localstack/utils/threads.py", line 135, in parallelize
    return pool.map(func, arr)
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/opt/code/localstack/localstack/services/install.py", line 407, in install_component
    installer()
  File "/opt/code/localstack/localstack/packages/api.py", line 182, in install
    self.get_installer(version).install(target)
  File "/opt/code/localstack/localstack/packages/api.py", line 83, in install
    raise e
  File "/opt/code/localstack/localstack/packages/api.py", line 74, in install
    if not self.is_installed():
  File "/opt/code/localstack/localstack/packages/api.py", line 93, in is_installed
    return self.get_installed_dir() is not None
  File "/opt/code/localstack/localstack/packages/api.py", line 103, in get_installed_dir
    if directory and os.path.exists(self._get_install_marker_path(directory)):
  File "/opt/code/localstack/localstack/packages/core.py", line 172, in _get_install_marker_path
    url = self._get_download_url()
  File "/opt/code/localstack/localstack/packages/core.py", line 208, in _get_download_url
    raise PackageException(
localstack.packages.api.PackageException: Could not get list of releases from https://api.github.com/repos/etspaceman/kinesis-mock/releases/tags/0.2.5: {"message":"API rate limit exceeded for 34.252.28.125. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}


Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/code/localstack/localstack/cli/main.py", line 10, in <module>
    main()
  File "/opt/code/localstack/localstack/cli/main.py", line 6, in main
    cli()
  File "/opt/code/localstack/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/code/localstack/localstack/utils/analytics/cli.py", line 66, in publisher_wrapper
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/cli/localstack.py", line 148, in cmd_start
    bootstrap.start_infra_locally()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 260, in start_infra_locally
    return infra.start_infra()
  File "/opt/code/localstack/localstack/services/infra.py", line 434, in start_infra
    raise e
  File "/opt/code/localstack/localstack/services/infra.py", line 420, in start_infra
    thread = do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/code/localstack/localstack/services/infra.py", line 516, in do_start_infra
    prepare_installation()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 77, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 470, in prepare_installation
    install.install_components(apis)
  File "/opt/code/localstack/localstack/services/install.py", line 411, in install_components
    parallelize(install_component, names)
  File "/opt/code/localstack/localstack/utils/threads.py", line 135, in parallelize
    return pool.map(func, arr)
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/opt/code/localstack/localstack/services/install.py", line 407, in install_component
    installer()
  File "/opt/code/localstack/localstack/packages/api.py", line 182, in install
    self.get_installer(version).install(target)
  File "/opt/code/localstack/localstack/packages/api.py", line 83, in install
    raise e
  File "/opt/code/localstack/localstack/packages/api.py", line 74, in install
    if not self.is_installed():
  File "/opt/code/localstack/localstack/packages/api.py", line 93, in is_installed
    return self.get_installed_dir() is not None
  File "/opt/code/localstack/localstack/packages/api.py", line 103, in get_installed_dir
    if directory and os.path.exists(self._get_install_marker_path(directory)):
  File "/opt/code/localstack/localstack/packages/core.py", line 172, in _get_install_marker_path
    url = self._get_download_url()
  File "/opt/code/localstack/localstack/packages/core.py", line 208, in _get_download_url
    raise PackageException(
localstack.packages.api.PackageException: Could not get list of releases from https://api.github.com/repos/etspaceman/kinesis-mock/releases/tags/0.2.5: {"message":"API rate limit exceeded for 34.252.28.125. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

```

### Expected Behavior

LocalSlack starts without any issue

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    using [Testcontainers Localstack Module](https://www.testcontainers.org/modules/localstack/)

### Environment

```markdown
- OS:
- LocalStack: 1.2.0
```

**Comment by musketyr** [comment]
I'm sorry I think I have just found a issue related to this one https://github.com/localstack/localstack/issues/6797

**Comment by EAlf91** [comment]
I'd like to reopen this issue as it still exist and the related tickets are closed.

localstack conatiners used: 1.2.0, latest

**Comment by kappaj2** [comment]
And happening again this morning. Was fine yesterday. Super SUPER frustrating.
