### ISSUE TITLE
bug: Hot Swapping Python Lambda Fails on container creation

### ISSUE THREAD

**Issue by BollenK** [localstack/localstack#7319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to use hot swapping as explained in the documentation. I currently have my docker-compose file like this:
```yaml
version:"3.5"
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=....
      # - HOSTNAME_EXTERNAL=localstack
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_NETWORK=bridge
      - ENVIRONMENT=localstack
      - REQUIRE_PRO=1
      - LAMBDA_REMOTE_DOCKER=false
      - BUCKET_MARKER_LOCAL=hotcode2
      - LAMBDA_MOUNT_CWD=/absolute/path/to/folder/
      - LAMBDA_EXECUTOR=docker-reuse
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    tmpfs:
      - /tmp/localstack:exec,mode=600```
This is how I create the lambda function:
```python
def create_lambda_timestream(self, environment_variables):
        """
        This is a method for creating a Serverless Lambda function.
        """
        bucket = aws_s3.Bucket.from_bucket_name(self, "HotReloadingBucket", "hotcode2")
        return aws_lambda.Function(
            self,
            "test_lambda",
            function_name="test",
            runtime=aws_lambda.Runtime.PYTHON_3_9,
            handler="main.lambda_handler",
            code=aws_lambda.S3Code(bucket, "/absolute/path/to/folder/")
        )```

For developing purposes I made very simple Lambda function:
```python
def lambda_handler(event, context):
    return {"statusCode": 200, "body": "Success"}
```

When I call my lambda function: `awslocal lambda invoke --function-name test --payload {} response.json`, I get the following response: 
```json
{
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
```
In the response file it states the following:
```json
{
    "errorMessage": "Lambda process returned with error. Result: . Output:\n",
    "errorType": "InvocationException",
    "stackTrace": [
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 444, in run_lambda\n    result = LAMBDA_EXECUTOR.execute(\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 495, in execute\n    return do_execute()\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 485, in do_execute\n    return _run(func_arn=func_arn)\n",
        "  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 153, in wrapped\n    raise e\n",
        "  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 149, in wrapped\n    result = func(*args, **kwargs)\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 472, in _run\n    raise e\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 468, in _run\n    result = self._execute(lambda_function, inv_context)\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 932, in _execute\n    return super(LambdaExecutorReuseContainers, self)._execute(func_arn, *args, **kwargs)\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 791, in _execute\n    result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)\n",
        "  File \"/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc\", line 377, in run_lambda_executor\n",
        "  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 713, in run_lambda_executor\n    raise InvocationException(\n"
    ]
}
```
And the logs in the Localstack container:
```
2022-12-13T13:10:19.789 DEBUG --- [uest_thread)] l.s.awslambda.lambda_api   : Running lambda arn:aws:lambda:us-east-1:000000000000:function:test
2022-12-13T13:10:20.801  INFO --- [uest_thread)] l.s.a.lambda_executors     : Empty event body specified for invocation of Lambda "arn:aws:lambda:us-east-1:000000000000:function:test"
2022-12-13T13:10:20.801 DEBUG --- [uest_thread)] l.u.c.container_client     : Getting networks for container: localstack
2022-12-13T13:10:20.811  INFO --- [uest_thread)] l.u.container_networking   : Determined main container network: vi-historian-service_default
2022-12-13T13:10:20.811 DEBUG --- [uest_thread)] l.u.c.container_client     : Getting ipv4 address for container localstack in network vi-historian-service_default.
2022-12-13T13:10:20.826  INFO --- [uest_thread)] l.u.container_networking   : Determined main container target IP: 172.20.0.2
2022-12-13T13:10:20.827  INFO --- [uest_thread)] l.s.a.lambda_executors     : Running lambda: arn:aws:lambda:us-east-1:000000000000:function:test
2022-12-13T13:10:20.827 DEBUG --- [uest_thread)] l.s.a.lambda_launcher      : Executing docker-reuse Lambda container invocation
2022-12-13T13:10:20.827 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Priming docker container with runtime "python3.9" and arn "arn:aws:lambda:us-east-1:000000000000:function:test".
2022-12-13T13:10:20.831 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Priming Docker container (status "0"): localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test
2022-12-13T13:10:20.835 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Creating container: localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test
2022-12-13T13:10:20.836 DEBUG --- [uest_thread)] l.s.a.lambda_launcher      : Executing docker reuse container creation hook for function arn:aws:lambda:us-east-1:000000000000:function:test
2022-12-13T13:10:21.217 DEBUG --- [uest_thread)] l.u.c.container_client     : Getting the entrypoint for image: localstack/lambda:python3.9
2022-12-13T13:10:21.227  INFO --- [uest_thread)] l.s.a.lambda_launcher      : HOST_TMP_FOLDER not configured - this may break Lambda Docker container startup if LAMBDA_REMOTE_DOCKER=0
2022-12-13T13:10:21.227 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Creating docker-reuse Lambda container localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test from image localstack/lambda:python3.9
2022-12-13T13:10:21.227 DEBUG --- [uest_thread)] l.u.c.docker_sdk_client    : Creating container with attributes: {'mount_volumes': [('/Users/kasperbollen/Work/Alliander/vi-historian-service/historian/test_lambda/', '/var/task'), ('/tmp/localstack', '/tmp')], 'ports': None, 'cap_add': ['NET_ADMIN'], 'cap_drop': None, 'security_opt': None, 'dns': '127.0.0.1', 'additional_flags': None, 'workdir': None, 'privileged': None, 'command': ['main.lambda_handler'], 'detach': False, 'entrypoint': '/tmp/6cbe290a.sh', 'env_vars': {'AWS_ACCESS_KEY_ID': 'test', 'AWS_SECRET_ACCESS_KEY': 'test', 'AWS_REGION': 'us-east-1', 'LOCALSTACK_HOSTNAME': '172.20.0.2', 'AWS_ENDPOINT_URL': 'http://172.20.0.2:4566', 'EDGE_PORT': '443', '_HANDLER': 'main.lambda_handler', 'AWS_LAMBDA_FUNCTION_TIMEOUT': '3', 'AWS_LAMBDA_FUNCTION_NAME': 'test', 'AWS_LAMBDA_FUNCTION_VERSION': '$LATEST', 'AWS_LAMBDA_FUNCTION_INVOKED_ARN': 'arn:aws:lambda:us-east-1:000000000000:function:test', '_LAMBDA_SERVER_PORT': '5000', 'DOCKER_LAMBDA_STAY_OPEN': '1', 'LOCALSTACK_DEBUG': '1'}, 'image_name': 'localstack/lambda:python3.9', 'interactive': False, 'name': 'localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test', 'network': 'vi-historian-service_default', 'remove': True, 'self': <localstack.utils.container_utils.docker_sdk_client.SdkDockerClient object at 0xffffb05e5930>, 'tty': False, 'user': 'root'}
2022-12-13T13:10:21.280 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Starting docker-reuse Lambda container: localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test
2022-12-13T13:10:21.280 DEBUG --- [uest_thread)] l.u.c.docker_sdk_client    : Starting container localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test
2022-12-13T13:10:21.810 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Lambda arn:aws:lambda:us-east-1:000000000000:function:test result / log output:

>
2022-12-13T13:10:21.930 DEBUG --- [   asgi_gw_0] l.services.plugins         : checking service health logs:4566
2022-12-13T13:10:21.965  INFO --- [uest_thread)] l.s.a.lambda_executors     : writing log to file '/tmp/localstack/lambda_fa4d9bgq.log'
2022-12-13T13:10:21.980 DEBUG --- [   asgi_gw_1] l.services.plugins         : checking service health cloudwatch:4566
2022-12-13T13:10:22.019  INFO --- [uest_thread)] l.s.awslambda.lambda_api   : Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:test: Lambda process returned with error. Result: . Output:
 Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/dba73171ea29ece82a8e54ab64d6e34529632c7ac1c5d87c32d3335cc81834d4/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 479, in start_container
    container.start()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/models/containers.py", line 404, in start
    return self.client.api.start(self.id, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/container.py", line 1111, in start
    self._raise_for_status(res)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/dba73171ea29ece82a8e54ab64d6e34529632c7ac1c5d87c32d3335cc81834d4/start: Bad Request ("failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/tmp/6cbe290a.sh": stat /tmp/6cbe290a.sh: no such file or directory: unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 668, in run_lambda_executor
    result, log_output = self.execute_in_container(
  File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
    return new(target, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/awslambda/lambda_launcher.py.enc", line 77, in A
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 848, in execute_in_container
    container_info = self.prime_docker_container(
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 982, in prime_docker_container
    DOCKER_CLIENT.start_container(container_name)
  File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 484, in start_container
    raise ContainerException() from e
localstack.utils.container_utils.container_client.ContainerException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 444, in run_lambda
    result = LAMBDA_EXECUTOR.execute(
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 495, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 485, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 153, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 472, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 468, in _run
    result = self._execute(lambda_function, inv_context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 932, in _execute
    return super(LambdaExecutorReuseContainers, self)._execute(func_arn, *args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 791, in _execute
    result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 377, in run_lambda_executor
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 713, in run_lambda_executor
    raise InvocationException(
localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: . Output:


2022-12-13T13:10:22.019 DEBUG --- [uest_thread)] l.s.awslambda.lambda_api   : Lambda invocation duration: 2230.46ms
2022-12-13T13:10:22.023  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS lambda.Invoke => 200
2022-12-13T13:10:54.355 DEBUG --- [  Thread-176] l.s.a.lambda_executors     : Checking if there are idle containers ...
2022-12-13T13:11:54.362 DEBUG --- [  Thread-189] l.s.a.lambda_executors     : Checking if there are idle containers ...
2022-12-13T13:12:54.368 DEBUG --- [  Thread-195] l.s.a.lambda_executors     : Checking if there are idle containers ...
2022-12-13T13:13:54.375 DEBUG --- [  Thread-202] l.s.a.lambda_executors     : Checking if there are idle containers ...
2022-12-13T13:14:54.384 DEBUG --- [  Thread-209] l.s.a.lambda_executors     : Checking if there are idle containers ...
2022-12-13T13:15:54.392 DEBUG --- [  Thread-216] l.s.a.lambda_executors     : Checking if there are idle containers ...
2022-12-13T13:16:54.401 DEBUG --- [  Thread-222] l.s.a.lambda_executors     : Checking if there are idle containers ...
2022-12-13T13:17:07.717 DEBUG --- [uest_thread)] l.s.awslambda.lambda_api   : Running lambda arn:aws:lambda:us-east-1:000000000000:function:test
2022-12-13T13:17:07.719  INFO --- [uest_thread)] l.s.a.lambda_executors     : Empty event body specified for invocation of Lambda "arn:aws:lambda:us-east-1:000000000000:function:test"
2022-12-13T13:17:07.720  INFO --- [uest_thread)] l.s.a.lambda_executors     : Running lambda: arn:aws:lambda:us-east-1:000000000000:function:test
2022-12-13T13:17:07.720 DEBUG --- [uest_thread)] l.s.a.lambda_launcher      : Executing docker-reuse Lambda container invocation
2022-12-13T13:17:07.721 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Priming docker container with runtime "python3.9" and arn "arn:aws:lambda:us-east-1:000000000000:function:test".
2022-12-13T13:17:07.730 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Priming Docker container (status "0"): localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test
2022-12-13T13:17:07.735 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Creating container: localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test
2022-12-13T13:17:07.736 DEBUG --- [uest_thread)] l.s.a.lambda_launcher      : Executing docker reuse container creation hook for function arn:aws:lambda:us-east-1:000000000000:function:test
2022-12-13T13:17:08.090 DEBUG --- [uest_thread)] l.u.c.container_client     : Getting the entrypoint for image: localstack/lambda:python3.9
2022-12-13T13:17:08.099  INFO --- [uest_thread)] l.s.a.lambda_launcher      : HOST_TMP_FOLDER not configured - this may break Lambda Docker container startup if LAMBDA_REMOTE_DOCKER=0
2022-12-13T13:17:08.099 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Creating docker-reuse Lambda container localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test from image localstack/lambda:python3.9
2022-12-13T13:17:08.099 DEBUG --- [uest_thread)] l.u.c.docker_sdk_client    : Creating container with attributes: {'mount_volumes': [('/Users/kasperbollen/Work/Alliander/vi-historian-service/historian/test_lambda/', '/var/task'), ('/tmp/localstack', '/tmp')], 'ports': None, 'cap_add': ['NET_ADMIN'], 'cap_drop': None, 'security_opt': None, 'dns': '127.0.0.1', 'additional_flags': None, 'workdir': None, 'privileged': None, 'command': ['main.lambda_handler'], 'detach': False, 'entrypoint': '/tmp/e06def5f.sh', 'env_vars': {'AWS_ACCESS_KEY_ID': 'test', 'AWS_SECRET_ACCESS_KEY': 'test', 'AWS_REGION': 'us-east-1', 'LOCALSTACK_HOSTNAME': '172.20.0.2', 'AWS_ENDPOINT_URL': 'http://172.20.0.2:4566', 'EDGE_PORT': '443', '_HANDLER': 'main.lambda_handler', 'AWS_LAMBDA_FUNCTION_TIMEOUT': '3', 'AWS_LAMBDA_FUNCTION_NAME': 'test', 'AWS_LAMBDA_FUNCTION_VERSION': '$LATEST', 'AWS_LAMBDA_FUNCTION_INVOKED_ARN': 'arn:aws:lambda:us-east-1:000000000000:function:test', '_LAMBDA_SERVER_PORT': '5001', 'DOCKER_LAMBDA_STAY_OPEN': '1', 'LOCALSTACK_DEBUG': '1'}, 'image_name': 'localstack/lambda:python3.9', 'interactive': False, 'name': 'localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test', 'network': 'vi-historian-service_default', 'remove': True, 'self': <localstack.utils.container_utils.docker_sdk_client.SdkDockerClient object at 0xffffb05e5930>, 'tty': False, 'user': 'root'}
2022-12-13T13:17:08.148 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Starting docker-reuse Lambda container: localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test
2022-12-13T13:17:08.148 DEBUG --- [uest_thread)] l.u.c.docker_sdk_client    : Starting container localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test
2022-12-13T13:17:08.666 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Lambda arn:aws:lambda:us-east-1:000000000000:function:test result / log output:

>
2022-12-13T13:17:08.690  INFO --- [uest_thread)] l.s.a.lambda_executors     : writing log to file '/tmp/localstack/lambda_ewsb8na6.log'
2022-12-13T13:17:08.713  INFO --- [uest_thread)] l.s.awslambda.lambda_api   : Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:test: Lambda process returned with error. Result: . Output:
 Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/c6c767f30438a72847ba28f70d240a91a2c788358be0c24fc4334d9694d245c8/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 479, in start_container
    container.start()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/models/containers.py", line 404, in start
    return self.client.api.start(self.id, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/container.py", line 1111, in start
    self._raise_for_status(res)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/c6c767f30438a72847ba28f70d240a91a2c788358be0c24fc4334d9694d245c8/start: Bad Request ("failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/tmp/e06def5f.sh": stat /tmp/e06def5f.sh: no such file or directory: unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 668, in run_lambda_executor
    result, log_output = self.execute_in_container(
  File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
    return new(target, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/awslambda/lambda_launcher.py.enc", line 77, in A
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 848, in execute_in_container
    container_info = self.prime_docker_container(
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 982, in prime_docker_container
    DOCKER_CLIENT.start_container(container_name)
  File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 484, in start_container
    raise ContainerException() from e
localstack.utils.container_utils.container_client.ContainerException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 444, in run_lambda
    result = LAMBDA_EXECUTOR.execute(
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 495, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 485, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 153, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 472, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 468, in _run
    result = self._execute(lambda_function, inv_context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 932, in _execute
    return super(LambdaExecutorReuseContainers, self)._execute(func_arn, *args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 791, in _execute
    result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 377, in run_lambda_executor
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 713, in run_lambda_executor
    raise InvocationException(
localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: . Output: 
  ```

### Expected Behavior

I expect that when I invoke the lambda function via awslocal:
```awslocal lambda invoke --function-name test --payload {} response.json```
my lambda function returns:
```{"statusCode": 200, "body": "Success"}```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   ```docker-compose -f docker-compose.local.yml up -d localstack
	ENVIRONMENT=localstack cdklocal bootstrap
	ENVIRONMENT=localstack cdklocal synth
	ENVIRONMENT=localstack cdklocal deploy --require-approval never```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    ```awslocal lambda invoke --function-name test --payload {} response.json```


### Environment

```markdown
- OS: macOS Ventura
- LocalStack: 1.2.0
```

### Anything else?

I searched to open issues and also documentation and forums. However I could not find a solution and from what I could tell I setup the configurations the right way. That's why I think there maybe is a bug.

The path to where I am pointing with the LAMBDA_MOUNT_CWD variable is the folder where the main.py lambda file is.

Thanks!

**Comment by dfangl** [comment]
Hi!
Your specific issue seems to stem from the missing file mount of `/var/lib/localstack` to the host. Please check our default docker-compose.yml (https://github.com/localstack/localstack/blob/master/docker-compose-pro.yml) for reference. Without this file mount, localstack cannot mount some additional dependencies into the container, which leads to this error.
Please try using this docker compose file (with certain addtitions like LAMBDA_REMOTE_DOCKER=false and your bucket marker).
It also seems you might have misconfigured LAMBDA_DOCKER_NETWORK to bridge, as you run in docker compose, which per defaults creates its own bridge network (bridge is also the name of the default bridge in docker). Please delete this environment variable, LocalStack should pick up the correct network by itself. It is mostly useful when having the LocalStack container connected to multiple networks and wanting to use a specific one for lambdas.

I would, however, encourage you to try using our new (beta) lambda provider, by using `PROVIDER_OVERRIDE_LAMBDA=asf`. It also features hot reloading, but is a far improved implementation to our current one. However, there might still be bugs, so please report back if you encounter any.

**Comment by BollenK** [comment]
Hi dfangl! Thanks a lot for your detailed explanation, hot reloading works now (I did not try asf yet). It was indeed a problem in the configuration. I now have two weeks of holiday but after that I'm going to try the new lambda provider and will report back if I encounter some issues. Thanks again and have a good Christmas!

**Comment by dfangl** [comment]
Great to hear that! Thank you for your reply.
I will close this issue know. If you have any more problems, please raise another issue!
Looking forward to hearing for feedback for the new provider as well, as it is scheduled to become default in 2.0.
