### ISSUE TITLE
500 when creating SNS topic

### ISSUE THREAD

**Issue by rgladwell** [localstack/localstack#734]
Using the latest docker container (from `localstack/localstack`) I get 500 errors whenever I try to create new SNS topic.

```sh
> aws --endpoint-url=http://localhost:4575 sns create-topic --name test

Unable to parse response (syntax error: line 1, column 54), invalid XML received:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>\n'
```

Cannot see anything in the logs about why this should fail.

My `docker-compose.yml` looks likes this:

```yaml
version: "3"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4575:4575"
      - "4576:4576"
```

No obvious errors in stderr/stdout when I run `docker logs`.

**Comment by rgladwell** [comment]
This also appears to be occuring on the latest version of the code cloned from this repo.

**Comment by andrezimmermann** [comment]
I'm sorry, can you give a better detailed explanation? I don't see the issue running your command
```
PS [...]> docker pull localstack/localstack
Using default tag: latest
latest: Pulling from localstack/localstack
Digest: sha256:7edb6e1bd3b5b32f61ca36aa3c222123799cd4021b47c67
```

```
PS [...]> aws --endpoint-url=http://localhost:4575 sns create-topic --name test
{
    "TopicArn": "arn:aws:sns:ap-northeast-1:123456789012:test"
}
```

**Comment by rgladwell** [comment]
Not sure what other information to provide. I'm running docker off Mac OS X. I put dummy credentials in `aws configure`. Would that make a difference?

**Comment by rgladwell** [comment]
On manual testing it appears that putting an invalid region (i.e. `localhost`) in to the AWS CLI configuration causes this to occur.

**Comment by pingvinen** [comment]
I am also getting 500 errors with SNS, but I am only seeing it with `ListTopics` - `CreateTopic` works fine for me.

**Comment by lPegz** [comment]
I am getting the exact error.

```
com.amazonaws.services.sns.model.AmazonSNSException: null (Service: AmazonSNS; Status Code: 500; Error Code: 500 Internal Server Error; Request ID: null)

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1638)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1303)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.sns.AmazonSNSClient.doInvoke(AmazonSNSClient.java:2270)
	at com.amazonaws.services.sns.AmazonSNSClient.invoke(AmazonSNSClient.java:2246)
	at com.amazonaws.services.sns.AmazonSNSClient.executeCreateTopic(AmazonSNSClient.java:674)
	at com.amazonaws.services.sns.AmazonSNSClient.createTopic(AmazonSNSClient.java:651)
	at com.amazonaws.services.sns.AmazonSNSClient.createTopic(AmazonSNSClient.java:686)

```

And 

```
2018-06-22 16:24:27 [main] INFO  com.amazonaws.http.DefaultErrorResponseHandler - Unable to parse HTTP response (Invocation Id:b50db091-c5eb-a8e4-ddf2-299afd1c0e66) content to XML document '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
' 
org.xml.sax.SAXParseException: White spaces are required between publicId and systemId.
```

Does this help?

I am using the following version of the lib, it doesn't show any newer in gradle:
`integrationTestCompile group: 'cloud.localstack', name: 'localstack-utils', version: '0.1.13'`

My code is this: 
```
 DockerTestUtils.getClientSNS().createTopic(allocationTopic).getTopicArn()
```

Is there a new version with a fix for this?

**Comment by codeinaire** [comment]
I was getting this exact error when running this command:

`aws --endpoint-url=http://localhost:4575 sns create-topic --name "arntest"`

In my docker compose file I had `DEFAULT_REGION` set to `ap-southeast-2`. 

To get it to work I just added the region tag to the above command, like so:

`aws --endpoint-url=http://localhost:4575 sns create-topic --name "arntest" --region ap-southeast-2`

**Comment by whummer** [comment]
Thanks for reporting @giggluigg @codeinaire @pingvinen @rgladwell @andrezimmermann - this should be fixed in the latest version which now also honors DEFAULT_REGION for SNS requests (see #1744).

Closing this issue - please re-open if the problem persists. Thanks
