### ISSUE TITLE
Using read.csv from Pyspark

### ISSUE THREAD

**Issue by a3huang** [localstack/localstack#736]
I am trying to test a function that involves reading a file from S3 using Pyspark's `read.csv` function. I ran `localstack start` to spin up the mock servers and tried executing the following simplified example. The idea is to upload a small test file onto the mock S3 service and then call `read.csv` to see if I can read the file correctly.
```
from pyspark.sql import SparkSession
import pandas as pd
import boto3
import os

conn = boto3.resource(service_name='s3', region_name='us-east-1', endpoint_url='http://localhost:4572')
conn.create_bucket(Bucket='mybucket')

df = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})
file_path = 'test_folder/test.csv'
data_object = df.to_csv(index=False)
conn.Bucket('mybucket').put_object(Key=file_path, Body=data_object)

os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages com.amazonaws:aws-java-sdk:1.10.34,org.apache.hadoop:hadoop-aws:2.6.0 pyspark-shell'
spark = SparkSession.builder.getOrCreate()
spark._jsc.hadoopConfiguration().set("fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
spark._jsc.hadoopConfiguration().set("fs.s3a.awsAccessKeyId", "fake")
spark._jsc.hadoopConfiguration().set("fs.s3a.awsSecretAccessKey", "fake")
spark._jsc.hadoopConfiguration().set("fs.s3a.endpoint", 'http://localhost:4572')
spark._jsc.hadoopConfiguration().set("fs.s3a.path.style.access", "true")
spark.read.csv('s3a://mybucket/test_folder/test.csv', sep=',', header=True)
```
I get the following traceback:
```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-12-b099bb7b6458> in <module>()
      6 spark._jsc.hadoopConfiguration().set("fs.s3a.endpoint", 'http://localhost:4572')
      7 spark._jsc.hadoopConfiguration().set("fs.s3a.path.style.access", "true")
----> 8 spark.read.csv('s3a://mybucket/test_folder/test.csv', sep=',', header=True)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyspark/sql/readwriter.py in csv(self, path, schema, sep, encoding, quote, escape, comment, header, inferSchema, ignoreLeadingWhiteSpace, ignoreTrailingWhiteSpace, nullValue, nanValue, positiveInf, negativeInf, dateFormat, timestampFormat, maxColumns, maxCharsPerColumn, maxMalformedLogPerPartition, mode, columnNameOfCorruptRecord, multiLine)
    408         if isinstance(path, basestring):
    409             path = [path]
--> 410         return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    411 
    412     @since(1.5)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    317                 raise Py4JJavaError(
    318                     "An error occurred while calling {0}{1}{2}.\n".
--> 319                     format(target_id, ".", name), value)
    320             else:
    321                 raise Py4JError(

Py4JJavaError: An error occurred while calling o335.csv.
: com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3589)
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1041)
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1013)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:154)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$14.apply(DataSource.scala:350)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$14.apply(DataSource.scala:348)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:344)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:348)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:533)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
```
Am I using the local mock URL correctly?

**Comment by whummer** [comment]
Thanks for reporting @a3huang , can you try with the following configuration:
```
spark._jsc.hadoopConfiguration().set("fs.s3a.access.key", "fake")
spark._jsc.hadoopConfiguration().set("fs.s3a.secret.key", "fake")
```
Also, you may have to upgrade to a more recent version of `com.amazonaws:aws-java-sdk` (`1.10.x`)

**Comment by a3huang** [comment]
I upgraded my `aws-java-sdk` and updated the above code snippet with the suggested configuration:
```
from pyspark.sql import SparkSession
import pandas as pd
import boto3
import os

conn = boto3.resource(service_name='s3', region_name='us-east-1', endpoint_url='http://localhost:4572')
conn.create_bucket(Bucket='mybucket')

df = pd.DataFrame({'a': [1, 2], 'b': [3, 4]})
file_path = 'test_folder/test.csv'
data_object = df.to_csv(index=False)
conn.Bucket('mybucket').put_object(Key=file_path, Body=data_object)

os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages com.amazonaws:aws-java-sdk:1.11.329,org.apache.hadoop:hadoop-aws:2.6.0 pyspark-shell'
spark = SparkSession.builder.getOrCreate()
spark._jsc.hadoopConfiguration().set("fs.s3a.access.key", "fake")
spark._jsc.hadoopConfiguration().set("fs.s3a.secret.key", "fake")
spark.read.csv('s3a://mybucket/test_folder/test.csv', sep=',', header=True)
```
I now get the following traceback:
```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-23-795c14d1a828> in <module>()
     16 spark._jsc.hadoopConfiguration().set("fs.s3a.access.key", "fake")
     17 spark._jsc.hadoopConfiguration().set("fs.s3a.secret.key", "fake")
---> 18 spark.read.csv('s3a://mybucket/test_folder/test.csv', sep=',', header=True)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyspark/sql/readwriter.py in csv(self, path, schema, sep, encoding, quote, escape, comment, header, inferSchema, ignoreLeadingWhiteSpace, ignoreTrailingWhiteSpace, nullValue, nanValue, positiveInf, negativeInf, dateFormat, timestampFormat, maxColumns, maxCharsPerColumn, maxMalformedLogPerPartition, mode, columnNameOfCorruptRecord, multiLine)
    408         if isinstance(path, basestring):
    409             path = [path]
--> 410         return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    411 
    412     @since(1.5)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    317                 raise Py4JJavaError(
    318                     "An error occurred while calling {0}{1}{2}.\n".
--> 319                     format(target_id, ".", name), value)
    320             else:
    321                 raise Py4JError(

Py4JJavaError: An error occurred while calling o233.csv.
: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 2751BC5D9FDCD65E), S3 Extended Request ID: PoJAj+Io58yZBdCKxoaTO88mOaYyCPbDnHdGDQjMxj6jbWgWIcWpVoHOnBEdAsrYxEtUlI/ppnY=
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1239)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:823)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3595)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:999)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:977)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:688)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.getFileStatus(S3AFileSystem.java:71)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1426)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$14.apply(DataSource.scala:359)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$14.apply(DataSource.scala:348)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:344)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:348)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:533)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by samrogers226** [comment]
@a3huang did you ever find a solution here?

**Comment by whummer** [comment]
Thanks for the update @a3huang @samrogers226 . Seems like the client is configured to access the real AWS APIs, instead of the local ones:
```
: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 2751BC5D9FDCD65E), S3 Extended Request ID: PoJAj+Io58yZBdCKxoaTO88mOaYyCPbDnHdGDQjMxj6jbWgWIcWpVoHOnBEdAsrYxEtUlI/ppnY=
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1239)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:823)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)
```

This issue is pretty old and may have been fixed in the meantime - if you happen to have found a fix, then please share it here for reference. Thanks!
