### ISSUE TITLE
bug: Unable to create/list/get url function configuration for Lambda in localstack

### ISSUE THREAD

**Issue by spelexander** [localstack/localstack#7382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi! first off thanks for a useful library for emulating AWS resources locally.

The issue I'm encountering is using the nodejs aws-sdk to create resources in localstack.

If I create a lambda, and then try to create/list/get a URL config for the lambda I get the following error which provides nothing to go off of for investigation:

```
Error [UnknownError]
    at Object.extractError (/Users/aspence/src/canvas/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/Users/aspence/src/canvas/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8)
    at Request.callListeners (/Users/aspence/src/canvas/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/aspence/src/canvas/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/aspence/src/canvas/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/aspence/src/canvas/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/aspence/src/canvas/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/aspence/src/canvas/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/aspence/src/canvas/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/aspence/src/canvas/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/Users/aspence/src/canvas/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/Users/aspence/src/canvas/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/aspence/src/canvas/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/aspence/src/canvas/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/aspence/src/canvas/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/aspence/src/canvas/node_modules/aws-sdk/lib/state_machine.js:26:10 {
  code: 'UnknownError',
  statusCode: 404,
  time: 2022-12-22T01:19:24.624Z,
  requestId: undefined,
  retryable: false,
  retryDelay: 48.11161846934877
}
create-resources started 907
```

### Expected Behavior

I expect the url config to be created without errors, or some error description for why the operation failed.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml:

version: '3.9'
services:
  localstack_main:
    image: 'localstack/localstack:0.14.3'
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      SERVICES: 'dynamodb,lambda,s3'
      DEBUG: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    profiles:
      - default

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws-sdk nodejs client

```typescript
import { Lambda } from 'aws-sdk';

const lambda = new Lambda({
  region: 'us-east-1',
  endpoint: 'http://localhost:4566',
});

const name = 'test-lambda';

it('Test create resources', async () => {
  lambda.addPermission({
    FunctionName: name,
    Action: 'lambda:InvokeFunctionUrl',
    Principal: '*',
    FunctionUrlAuthType: 'NONE',
    StatementId: '/',
  });

  try {
    // THIS FAILS
    // So does the list, or get commands
    const result = await lambda
      .createFunctionUrlConfig({
        FunctionName: name,
        AuthType: 'NONE',
      })
      .promise();
    console.log('result: ', result);
  } catch (e) {
    console.error(e);
  }
});
```

### Environment

```markdown
- OS: Mac
- LocalStack: 0.14.3
```

**Comment by spelexander** [comment]
I see I'm using an old version of localstack and on the latest one it's no longer an issue
