### ISSUE TITLE
apigw authorizer not working -  b"'Authorizer' object is not subscriptable"

### ISSUE THREAD

**Issue by kingster307** [localstack/localstack#7391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever sending HTTP request to apigw authorized route the request fails due to TypeError. See below for specifics

```
2022-12-23 13:44:58 localstack  | 2022-12-23T18:44:57.600 DEBUG --- [   asgi_gw_4] l.s.apigateway.authorizers : Processing API V1 invocation
2022-12-23 13:44:58 localstack  | 2022-12-23T18:44:57.601 DEBUG --- [   asgi_gw_4] l.s.apigateway.authorizers : Authorization failed: 'Authorizer' object is not subscriptable - Traceback (most recent call last):
2022-12-23 13:44:58 localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 279, in is_request_authorized
2022-12-23 13:44:58 localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 264, in get_authorizer_configuration
2022-12-23 13:44:58 localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 264, in <genexpr>
2022-12-23 13:44:58 localstack  | TypeError: 'Authorizer' object is not subscriptable
```

Reproducer - [see reproducer here](https://github.com/kingster307/localstack_authorizer_bug) 

### Expected Behavior

The apigw should authorize the request & return specified data

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

reproducer - [See reproducer here](https://github.com/kingster307/localstack_authorizer_bug)

### Environment

```markdown
- OS: MAC M1 chip
- LocalStack: issue occurring in multiple LS versions. Current reproducer utilizes the latest LS pro image. Anything past 1.2.0 seems to have same error
```

**Comment by rondinellimorais** [comment]
Same problem here, I downgraded to version `localstack/localstack:1.1.0` and now I get error `401 {"message": "Unauthorized"}`, but when entering the user token in the header `Authorization:<id_token>` the request fails with the message:

```
Unable to find user <user_name> in configured user pools: []
```

To authenticate the user and get the token I am using this doc https://docs.localstack.cloud/user-guide/aws/cognito/
