### ISSUE TITLE
CloudWatch metrics: Support statistic-values in put-metric-data

### ISSUE THREAD

**Issue by barryoneill** [localstack/localstack#740]
It appears this may be a limitation of moto, but if you're putting statistic data (and not single values), localstack returns a 500 error.  

E.g. following the example from [Amazon's documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/PublishMetrics.html):

* when `--value` is being supplied, no error
```
17:05: $ aws --endpoint=http://localhost:4582 cloudwatch put-metric-data --metric-name RequestLatency --namespace GetStarted --timestamp 2016-10-14T20:30:00Z --value 235 --unit Milliseconds
```

* when `--statistic-values` is used and `--value` is not present,  a 500 error:
```
17:05 $ aws --endpoint=http://localhost:4582 cloudwatch put-metric-data --metric-name RequestLatency --namespace GetStarted --timestamp 2016-10-14T21:30:00Z --statistic-values Sum=577,Minimum=65,Maximum=189,SampleCount=5 --unit Milliseconds

Unable to parse response (syntax error: line 1, column 54), invalid XML received:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>\n'
```

The localstack logs show:

```
172.17.0.1 - - [27/Apr/2018 21:01:40] "POST / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
execute(self.server.app)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
application_iter = app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 93, in __call__
return backend_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 139, in __call__
result = self.callback(request, request.url, {})
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 116, in dispatch
return cls()._dispatch(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 199, in _dispatch
return self.call_action()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 273, in call_action
response = method()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 263, in _wrapper
response = f(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudwatch/responses.py", line 81, in put_metric_data
self.cloudwatch_backend.put_metric_data(namespace, metric_data)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudwatch/models.py", line 233, in put_metric_data
namespace, metric_member['MetricName'], float(metric_member['Value']), metric_member.get('Dimensions.member', _EMPTY_LIST), metric_member.get('Timestamp')))
KeyError: 'Value'
```

**Comment by barryoneill** [comment]
Added https://github.com/spulec/moto/issues/1615 to hopefully suppress the error at least.

**Comment by whummer** [comment]
Thanks for reporting @barryoneill . The upstream PR has been merged in the meantime, closing this issue. Thanks again
