### ISSUE TITLE
bug: athena: querying with awswrangler fails

### ISSUE THREAD

**Issue by yuvalshi0** [localstack/localstack#7414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to run an athena query through the awswrangler (https://github.com/aws/aws-sdk-pandas), yet it fails on two different changes in the localstack athena API:
* When using `ctas_approach=False` (not by default), localstack return an invalid output location:
![issue](https://user-images.githubusercontent.com/21289143/210219680-a368d560-d5b4-4ae8-b6f0-18693f8fc956.png)
Output location should be the full csv path! This causes the wrangler to return an empty dataframe all the time.
* When using `ctas_approach=True` (which is by default) the query fails on a parsing exception:
```
2023-01-02T10:20:40.593  INFO --- [   Thread-45] pyhive.hive                : USE `foobar`
2023-01-02T10:20:40.638  INFO --- [   Thread-45] pyhive.hive                : CREATE TABLE foobar.temp_table_31f414c72bd74a16ab57e62c93c98d5d
WITH(
    external_location = 's3://aws-athena-query-results-845160839676-eu-west-1/temp_table_31f414c72bd74a16ab57e62c93c98d5d',
    format = 'PARQUET')
AS SELECT 1 FROM test
2023-01-02T10:20:40.724  INFO --- [   Thread-45] l.services.athena.provider : Athena error for query "CREATE TABLE foobar.temp_table_31f414c72bd74a16ab57e62c93c98d5d
WITH(
    external_location = 's3://aws-athena-query-results-845160839676-eu-west-1/temp_table_31f414c72bd74a16ab57e62c93c98d5d',
    format = 'PARQUET')
AS SELECT 1 AS test":
TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: ParseException line 2:0 cannot recognize input near 'WITH' '(' 'external_location' in create table statement:17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1149', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:624', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.ParseException:line 2:0 cannot recognize input near 'WITH' '(' 'external_location' in create table statement:22:6", 'org.apache.hadoop.hive.ql.parse.ParseDriver:parse:ParseDriver.java:211', 'org.apache.hadoop.hive.ql.parse.ParseUtils:parse:ParseUtils.java:77', 'org.apache.hadoop.hive.ql.parse.ParseUtils:parse:ParseUtils.java:70', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:468', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1317', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1295', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:204'], sqlState='42000', errorCode=40000, errorMessage="Error while compiling statement: FAILED: ParseException line 2:0 cannot recognize input near 'WITH' '(' 'external_location' in create table statement"), operationHandle=None) Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/athena/provider.py.enc", line 30, in O
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/athena/query_utils.py.enc", line 24, in execute_query
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/hadoop.py.enc", line 222, in execute_hive_query
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/hadoop.py.enc", line 226, in execute_hive_queries
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/hadoop.py.enc", line 238, in _execute_hive_query
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/pyhive/hive.py", line 455, in execute
    _check_status(response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/pyhive/hive.py", line 585, in _check_status
    raise OperationalError(response)
pyhive.exc.OperationalError: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: ParseException line 2:0 cannot recognize input near 'WITH' '(' 'external_location' in create table statement:17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:206', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:290', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1149', 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:624', 'java.lang.Thread:run:Thread.java:748', "*org.apache.hadoop.hive.ql.parse.ParseException:line 2:0 cannot recognize input near 'WITH' '(' 'external_location' in create table statement:22:6", 'org.apache.hadoop.hive.ql.parse.ParseDriver:parse:ParseDriver.java:211', 'org.apache.hadoop.hive.ql.parse.ParseUtils:parse:ParseUtils.java:77', 'org.apache.hadoop.hive.ql.parse.ParseUtils:parse:ParseUtils.java:70', 'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:468', 'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1317', 'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1295', 'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:204'], sqlState='42000', errorCode=40000, errorMessage="Error while compiling statement: FAILED: ParseException line 2:0 cannot recognize input near 'WITH' '(' 'external_location' in create table statement"), operationHandle=None)

```

### Expected Behavior

The query should be successful 

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run -d -p 4566:4566 -e LOCALSTACK_API_KEY=******** -e DOCKER_HOST=unix:///var/run/docker.sock -v /var/run/docker.sock:/var/run/docker.sock -e EAGER_SERVICE_LOADING=1 -e SERVICES=s3,athena,glue localstack/localstack-pro:1.3.1

#### Run code:
```python
import awswrangler as wr

ENDPOINT = "http://localhost:4566"
DATABASE = "foobar"
CTAS_APPROACH = False  # change this to True to see both cases

wr.config.athena_endpoint_url = ENDPOINT
wr.config.glue_endpoint_url = ENDPOINT
wr.config.s3_endpoint_url = ENDPOINT


wr.catalog.create_database(DATABASE)

wr.athena.read_sql_query("SELECT 1 AS test", database=DATABASE, ctas_approach=CTAS_APPROACH)

```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 1.3.1
```

### Anything else?

See also:
https://aws-sdk-pandas.readthedocs.io/en/stable/stubs/awswrangler.athena.read_sql_query.html#awswrangler.athena.read_sql_query

_NOTE:_ I ran both of theses cases against the real AWS ant they work

**Comment by whummer** [comment]
Hi @yuvalshi0 , thanks for reporting. Just a quick heads-up - look like we've been able to reproduce this issue using the `awswrangler` library. We're working on a fix and will get back to you shortly. Thanks

**Comment by whummer** [comment]
Hi again @yuvalshi0 , apologies for the long delay. We have pushed a couple of enhancements which should (hopefully) get this issue resolved. Can you please pull the `latest` Docker image and give it another try? (using the `BIGDATA_MONO_CONTAINER=1` config). Please keep us posted on how it goes.. Thanks!

**Comment by yuvalshi0** [comment]
Hi @whummer, 
It seems now that localstack does run query (internally), yet the returned value is still empty:
This is what I ran:
```python
import awswrangler as wr

ENDPOINT = "http://localhost:4566"
DATABASE = "foobar"
CTAS_APPROACH = False  # change this to True to see both cases

wr.config.athena_endpoint_url = ENDPOINT
wr.config.glue_endpoint_url = ENDPOINT
wr.config.s3_endpoint_url = ENDPOINT


wr.catalog.create_database(DATABASE)

df = wr.athena.read_sql_query(
    "SELECT 1 AS test", database=DATABASE, ctas_approach=False
)
print(df)

# expected df to be
#    test
# 0     1
# but got
# Empty DataFrame
# Columns: []
# Index: []
```

Localstack relevant log:
```
2023-02-20T07:51:18.216 DEBUG --- [  Thread-159] l.services.athena.provider : Athena result for query "SELECT 1 AS test":
{'rows': [[1]], 'columns': [['test', 'integer']]}
2023-02-20T07:51:18.432  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS athena.GetQueryExecution => 200
2023-02-20T07:51:18.448  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS athena.GetQueryResults => 200
```

**Comment by HarshCasper** [comment]
Due to the forthcoming changes in our distribution and development model ([read more](https://blog.localstack.cloud/the-road-ahead-for-localstack/)), this issue tracker is no longer being maintained, and this issue is now being closed. If you'd like us to take a look or need further support, please reach out through one of our support channels:

-   💬 [GitHub Discussions](https://github.com/orgs/localstack/discussions)
-   📖 [Help & Support](https://docs.localstack.cloud/aws/getting-started/help-support/)
