### ISSUE TITLE
bug: `localstack status [docker]` throws `PermissionError`

### ISSUE THREAD

**Issue by adesso-os** [localstack/localstack#7428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```shell
$ localstack status docker
Traceback (most recent call last):
  File "/usr/lib/python3.9/pathlib.py", line 1312, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/oliver/.cache/localstack/image_metadata/0c6a4031efdd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oliver/.local/bin/localstack", line 23, in <module>
    main()
  File "/home/oliver/.local/bin/localstack", line 19, in main
    main.main()
  File "/home/oliver/.local/lib/python3.9/site-packages/localstack/cli/main.py", line 11, in main
    cli()
  File "/home/oliver/.local/lib/python3.9/site-packages/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/home/oliver/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/oliver/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/oliver/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/oliver/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/oliver/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/oliver/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/oliver/.local/lib/python3.9/site-packages/localstack/cli/localstack.py", line 82, in cmd_status_docker
    print_docker_status(format)
  File "/home/oliver/.local/lib/python3.9/site-packages/localstack/cli/localstack.py", line 453, in print_docker_status
    runtime_version=get_server_version(),
  File "/home/oliver/.local/lib/python3.9/site-packages/localstack/utils/bootstrap.py", line 152, in get_server_version
    version_cache.parent.mkdir(exist_ok=True, parents=True)
  File "/usr/lib/python3.9/pathlib.py", line 1316, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.9/pathlib.py", line 1312, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/oliver/.cache/localstack/image_metadata'
```

### Expected Behavior

As instructed, I installed localstack as a regular non-root user without `sudo`. So I'm expecting that all commands also work without elevated permissions. However, the directory referenced in the error is owned by `root`, which probably explains the permission error.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    localstack status

### Environment

```markdown
- OS: Debian 11
- LocalStack: 1.3.1
```

**Comment by dfangl** [comment]
Is it possible that you have started the LocalStack CLI as root at some point? That would explain the image_metadata having the wrong user.
Please try deleting this file as root with: `sudo rm -f /home/oliver/.cache/localstack/image_metadata` and try if this resolves your issue!

**Comment by adesso-os** [comment]
@dfangl I guess it might be possible, although I'm sure I didn't elevate at any point.

The file in question doesn't even exist:
```shell
╰─ ls -lha /home/oliver/.cache/localstack/
total 12K
drwxr-xr-x  3 root   root   4.0K Jan 10 15:38 .
drwxr-xr-x 13 oliver oliver 4.0K Jan 10 15:38 ..
drwxr-xr-x  6 root   root   4.0K Jan 10 15:38 volume
```
Maybe it wants to _write_ the file, but the folder is owned by `root`?

Just to be sure, I also deleted the entire `/home/oliver/.cache/localstack/`, but `localstack start -d` will bring it back, owned by `root`.

**Comment by dfangl** [comment]
Confirmed, this is not right. The localstack folder should be created under the user (`oliver` in your case) and only the volume should be created as root.
