### ISSUE TITLE
Localstack starting throwing HttpConnection Error

### ISSUE THREAD

**Issue by somu90091** [localstack/localstack#743]
Hi. I started localstack and below is the error. I went through issue no 368 and followed the steps. But still its throwing same error
localstack --debug start
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock DynamoDB (http port 4569)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudWatch (http port 4582)...
Starting mock CloudFormation (http port 4581)...
Starting mock SSM (http port 4583)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
module.js:328
throw err;
^
Initializing DynamoDB Local with the following configuration:
Port:	4564
InMemory:	true
DbPath:	null
SharedDb:	true
shouldDelayTransientStatuses:	false
CorsParams:	*

Error: Cannot find module 'core-util-is'
at Function.Module._resolveFilename (module.js:326:15)
at Function.Module._load (module.js:277:25)
at Module.require (module.js:354:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/home/som/.local/lib/python2.7/site-packages/localstack/node_modules/readable-stream/lib/_stream_readable.js:46:12)
at Module._compile (module.js:410:26)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Module.require (module.js:354:17)
09:45:08.649 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.13.8) ...
* Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4583/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4563/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4577/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4580/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4579/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
[2018-05-01T09:45:09,597][INFO ][o.e.n.Node               ] [] initializing ...
09:45:09.637 [elasticmq-akka.actor.default-dispatcher-3] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
[2018-05-01T09:45:09,727][INFO ][o.e.e.NodeEnvironment    ] [0e0vnnb] using [1] data paths, mounts [[/ (/dev/sda1)]], net usable_space [243.7gb], net total_space [263gb], types [ext4]
[2018-05-01T09:45:09,727][INFO ][o.e.e.NodeEnvironment    ] [0e0vnnb] heap size [483.3mb], compressed ordinary object pointers [true]
[2018-05-01T09:45:09,730][INFO ][o.e.n.Node               ] node name [0e0vnnb] derived from node ID [0e0vnnbAQK6mI6FzCuabYA]; set [node.name] to override
[2018-05-01T09:45:09,730][INFO ][o.e.n.Node               ] version[6.2.0], pid[16394], build[37cdac1/2018-02-01T17:31:12.527918Z], OS[Linux/4.13.0-36-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_162/25.162-b12]
[2018-05-01T09:45:09,731][INFO ][o.e.n.Node               ] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.mG6IVjre, -XX:+HeapDumpOnOutOfMemoryError, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Xms200m, -Xmx500m, -Des.path.home=/home/som/.local/lib/python2.7/site-packages/localstack/infra/elasticsearch, -Des.path.conf=/home/som/.local/lib/python2.7/site-packages/localstack/infra/elasticsearch/config]
[2018-05-01T09:45:10,525][INFO ][o.e.p.PluginsService     ] [0e0vnnb] loaded module [aggs-matrix-stats]
[2018-05-01T09:45:10,525][INFO ][o.e.p.PluginsService     ] [0e0vnnb] loaded module [analysis-common]
[2018-05-01T09:45:10,526][INFO ][o.e.p.PluginsService     ] [0e0vnnb] loaded module [ingest-common]
[2018-05-01T09:45:10,526][INFO ][o.e.p.PluginsService     ] [0e0vnnb] loaded module [lang-expression]
[2018-05-01T09:45:10,526][INFO ][o.e.p.PluginsService     ] [0e0vnnb] loaded module [lang-mustache]
[2018-05-01T09:45:10,526][INFO ][o.e.p.PluginsService     ] [0e0vnnb] loaded module [lang-painless]
[2018-05-01T09:45:10,526][INFO ][o.e.p.PluginsService     ] [0e0vnnb] loaded module [mapper-extras]
[2018-05-01T09:45:10,526][INFO ][o.e.p.PluginsService     ] [0e0vnnb] loaded module [parent-join]
[2018-05-01T09:45:10,526][INFO ][o.e.p.PluginsService     ] [0e0vnnb] loaded module [percolator]
[2018-05-01T09:45:10,526][INFO ][o.e.p.PluginsService     ] [0e0vnnb] loaded module [rank-eval]
[2018-05-01T09:45:10,527][INFO ][o.e.p.PluginsService     ] [0e0vnnb] loaded module [reindex]
[2018-05-01T09:45:10,527][INFO ][o.e.p.PluginsService     ] [0e0vnnb] loaded module [repository-url]
[2018-05-01T09:45:10,527][INFO ][o.e.p.PluginsService     ] [0e0vnnb] loaded module [transport-netty4]
[2018-05-01T09:45:10,527][INFO ][o.e.p.PluginsService     ] [0e0vnnb] loaded module [tribe]
[2018-05-01T09:45:10,527][INFO ][o.e.p.PluginsService     ] [0e0vnnb] no plugins loaded
09:45:10.539 [elasticmq-akka.actor.default-dispatcher-2] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:4561, visible server address http://localhost:4576
09:45:10.540 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.13.8) started in 2787 ms ===
[2018-05-01T09:45:12,644][INFO ][o.e.d.DiscoveryModule    ] [0e0vnnb] using discovery type [zen]
[2018-05-01T09:45:13,082][INFO ][o.e.n.Node               ] initialized
[2018-05-01T09:45:13,082][INFO ][o.e.n.Node               ] [0e0vnnb] starting ...
[2018-05-01T09:45:13,236][INFO ][o.e.t.TransportService   ] [0e0vnnb] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2018-05-01T09:45:13,248][WARN ][o.e.b.BootstrapChecks    ] [0e0vnnb] initial heap size [209715200] not equal to maximum heap size [524288000]; this can cause resize pauses and prevents mlockall from locking the entire heap
[2018-05-01T09:45:13,249][WARN ][o.e.b.BootstrapChecks    ] [0e0vnnb] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
2018-05-01T09:45:15:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4270467310>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/home/som/.local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 201, in forward
    headers=forward_headers)
  File "/home/som/.local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/som/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/som/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/som/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/som/.local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4565): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4270467310>: Failed to establish a new connection: [Errno 111] Connection refused',))

[2018-05-01T09:45:16,302][INFO ][o.e.c.s.MasterService    ] [0e0vnnb] zen-disco-elected-as-master ([0] nodes joined), reason: new_master {0e0vnnb}{0e0vnnbAQK6mI6FzCuabYA}{12ZPjQ0WQKuQWiS8f0NNwg}{127.0.0.1}{127.0.0.1:9300}
[2018-05-01T09:45:16,308][INFO ][o.e.c.s.ClusterApplierService] [0e0vnnb] new_master {0e0vnnb}{0e0vnnbAQK6mI6FzCuabYA}{12ZPjQ0WQKuQWiS8f0NNwg}{127.0.0.1}{127.0.0.1:9300}, reason: apply cluster state (from master [master {0e0vnnb}{0e0vnnbAQK6mI6FzCuabYA}{12ZPjQ0WQKuQWiS8f0NNwg}{127.0.0.1}{127.0.0.1:9300} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)]])
[2018-05-01T09:45:16,329][INFO ][o.e.h.n.Netty4HttpServerTransport] [0e0vnnb] publish_address {127.0.0.1:4560}, bound_addresses {[::1]:4560}, {127.0.0.1:4560}
[2018-05-01T09:45:16,330][INFO ][o.e.n.Node               ] [0e0vnnb] started
[2018-05-01T09:45:16,359][INFO ][o.e.g.GatewayService     ] [0e0vnnb] recovered [0] indices into cluster_state

**Comment by somu90091** [comment]
This is fixed now.

**Comment by petrogdev** [comment]
can you provide some details as to how this was fixed? Im experiencing same issue while running localstack within docker container.

**Comment by somu90091** [comment]
I had this "core-util-is" missing. I installed it using npm and make sure u have set global proxy.

**Comment by cdson** [comment]
@somu90091  I am getting a similar error. Can you please explain what do you mean by setting the global proxy? Thanks

**Comment by somu9009** [comment]
Basically global proxy is nothing but system wide proxy. It can be set in ubuntu. And make sure you install the core-util-is packages. 
Setting global proxy in ubuntu  - https://askubuntu.com/questions/664777/systemwide-proxy-settings-in-ubuntu
