### ISSUE TITLE
Unable to start localstack on Windows 10

### ISSUE THREAD

**Issue by Vignesh40** [localstack/localstack#745]
I have installed local stack on windows 10 successfully but when starting from command prompt getting permission denied error.
1.Running as Administrator.
2.Given full access to the folder.

```
C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\Scripts>python localstack start
Starting local dev environment. CTRL-C to quit.
2018-04-30T15:45:30:INFO:localstack.services.install: Downloading and installing local Elasticsearch server. This may take some time.
ERROR: 'cd C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack/infra && mv elasticsearch* elasticsearch': b"mv: cannot move 'elasticsearch-6.2.0' to 'elasticsearch': Permission denied\n"
Error starting infrastructure: Command 'cd C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack/infra && mv elasticsearch* elasticsearch' returned non-zero exit status 1. Traceback (most recent call last):
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\services\infra.py", line 465, in start_infra
    install.install_components(apis)
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\services\install.py", line 137, in install_components
    parallelize(install_component, names)
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\utils\common.py", line 751, in parallelize
    result = pool.map(func, list)
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\services\install.py", line 131, in install_component
    install_elasticsearch()
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\services\install.py", line 40, in install_elasticsearch
    run('cd %s && mv elasticsearch* elasticsearch' % (INSTALL_DIR_INFRA))
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\utils\common.py", line 653, in run
    return do_run(cmd)
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\utils\common.py", line 650, in do_run
    raise e
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\utils\common.py", line 635, in do_run
    output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'cd C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack/infra && mv elasticsearch* elasticsearch' returned non-zero exit status 1.

ERROR: Command 'cd C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack/infra && mv elasticsearch* elasticsearch' returned non-zero exit status 1.

C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\Scripts>python localstack start
Starting local dev environment. CTRL-C to quit.
2018-04-30T15:46:05:INFO:localstack.services.install: Downloading and installing local Elasticsearch server. This may take some time.
ERROR: 'cd C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack/infra && mv elasticsearch* elasticsearch': b"mv: cannot move 'elasticsearch-6.2.0' to 'elasticsearch': Permission denied\n"
Error starting infrastructure: Command 'cd C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack/infra && mv elasticsearch* elasticsearch' returned non-zero exit status 1. Traceback (most recent call last):
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\services\infra.py", line 465, in start_infra
    install.install_components(apis)
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\services\install.py", line 137, in install_components
    parallelize(install_component, names)
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\utils\common.py", line 751, in parallelize
    result = pool.map(func, list)
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\services\install.py", line 131, in install_component
    install_elasticsearch()
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\services\install.py", line 40, in install_elasticsearch
    run('cd %s && mv elasticsearch* elasticsearch' % (INSTALL_DIR_INFRA))
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\utils\common.py", line 653, in run
    return do_run(cmd)
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\utils\common.py", line 650, in do_run
    raise e
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack\utils\common.py", line 635, in do_run
    output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'cd C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack/infra && mv elasticsearch* elasticsearch' returned non-zero exit status 1.

ERROR: Command 'cd C:\Users\thangavi\AppData\Local\Programs\Python\Python36-32\lib\site-packages\localstack/infra && mv elasticsearch* elasticsearch' returned non-zero exit status 1
```

**Comment by whummer** [comment]
Thanks for reporting @Vignesh40 . Can you try reinstalling the latest version of the pip package:
```
pip uninstall localstack
pip install --no-cache --upgrade localstack 
```

**Comment by Vignesh40** [comment]
Installed with pip install --no-cache --upgrade localstack comment.

When starting localstack getting into another type of error.

Starting local dev environment. CTRL-C to quit.
ERROR: 'cd "C:\Python36\lib\site-packages\localstack/infra/dynamodb" && zip -u DynamoDBLocal.jar log4j2.xml || true': b"'zip' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n'true' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
Error starting infrastructure: Command 'cd "C:\Python36\lib\site-packages\localstack/infra/dynamodb" && zip -u DynamoDBLocal.jar log4j2.xml || true' returned non-zero exit status 1. Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\localstack\services\infra.py", line 465, in start_infra
    install.install_components(apis)
  File "C:\Python36\lib\site-packages\localstack\services\install.py", line 140, in install_components
    parallelize(install_component, names)
  File "C:\Python36\lib\site-packages\localstack\utils\common.py", line 751, in parallelize
    result = pool.map(func, list)
  File "C:\Python36\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Python36\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python36\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Python36\lib\site-packages\localstack\services\install.py", line 132, in install_component
    install_dynamodb_local()
  File "C:\Python36\lib\site-packages\localstack\services\install.py", line 102, in install_dynamodb_local
    run('cd "%s" && zip -u DynamoDBLocal.jar log4j2.xml || true' % INSTALL_DIR_DDB)
  File "C:\Python36\lib\site-packages\localstack\utils\common.py", line 653, in run
    return do_run(cmd)
  File "C:\Python36\lib\site-packages\localstack\utils\common.py", line 650, in do_run
    raise e
  File "C:\Python36\lib\site-packages\localstack\utils\common.py", line 635, in do_run
    output = subprocess.check_output(cmd, shell=True, stderr=stderr, env=env_dict, cwd=cwd)
  File "C:\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'cd "C:\Python36\lib\site-packages\localstack/infra/dynamodb" && zip -u DynamoDBLocal.jar log4j2.xml || true' returned non-zero exit status 1.

ERROR: Command 'cd "C:\Python36\lib\site-packages\localstack/infra/dynamodb" && zip -u DynamoDBLocal.jar log4j2.xml || true' returned non-zero exit status 1.

C:\Python36\Scripts>

**tried these steps also:**

del ....localstack\infra\dynamodb

del .....AppData\Local\Temp\localstack

python localstack start


And....

Installed 7ZIp and WinRAR in windows and path variable set in environmental variables.

because seeing this error in logs "'zip' is not recognized as an internal or external" but no luck.

**Comment by mihir83in** [comment]
+1 same error @Vignesh40  did you find a workaround?

**Comment by whummer** [comment]
Installation should work now under Windows (see also changes in #1631). Closing this issue - please re-open if the problem persists.
