### ISSUE TITLE
bug: Lambda Certficate did not match expected hostname 

### ISSUE THREAD

**Issue by ifzal-ahmed-npl** [localstack/localstack#7460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am getting the below error when triggering a Lambda using a stepMachine that triggers from an SQS message in a SQS queue -

```
2023-01-09 08:46:31 localstack_main  | 2023-01-09T08:46:31.120  WARN --- [uncthread860] urllib3.connection         : Certificate did not match expected hostname: states.us-east-1.amazonaws.com. Certificate: {'subject': ((('commonName', 'localhost.localstack.cloud'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', "Let's Encrypt"),), (('commonName', 'R3'),)), 'version': 3, 'serialNumber': '03277A0FC6E52672285BB7C86D0D6083A2D9', 'notBefore': 'Dec 30 11:21:58 2022 GMT', 'notAfter': 'Mar 30 11:21:57 2023 GMT', 'subjectAltName': (('DNS', '*.amplifyapp.localhost.localstack.cloud'), ('DNS', '*.cloudfront.localhost.localstack.cloud'), ('DNS', '*.execute-api.localhost.localstack.cloud'), ('DNS', '*.localhost.localstack.cloud'), ('DNS', '*.opensearch.localhost.localstack.cloud'), ('DNS', '*.s3-website.localhost.localstack.cloud'), ('DNS', '*.s3.localhost.localstack.cloud'), ('DNS', '*.scm.localhost.localstack.cloud'), ('DNS', 'localhost.localstack.cloud')), 'OCSP': ('http://r3.o.lencr.org',), 'caIssuers': ('http://r3.i.lencr.org/',)}
2023-01-09 08:46:31 localstack_main  | 2023-01-09T08:46:31.639  WARN --- [uncthread860] urllib3.connection         : Certificate did not match expected hostname: states.us-east-1.amazonaws.com. Certificate: {'subject': ((('commonName', 'localhost.localstack.cloud'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', "Let's Encrypt"),), (('commonName', 'R3'),)), 'version': 3, 'serialNumber': '03277A0FC6E52672285BB7C86D0D6083A2D9', 'notBefore': 'Dec 30 11:21:58 2022 GMT', 'notAfter': 'Mar 30 11:21:57 2023 GMT', 'subjectAltName': (('DNS', '*.amplifyapp.localhost.localstack.cloud'), ('DNS', '*.cloudfront.localhost.localstack.cloud'), ('DNS', '*.execute-api.localhost.localstack.cloud'), ('DNS', '*.localhost.localstack.cloud'), ('DNS', '*.opensearch.localhost.localstack.cloud'), ('DNS', '*.s3-website.localhost.localstack.cloud'), ('DNS', '*.s3.localhost.localstack.cloud'), ('DNS', '*.scm.localhost.localstack.cloud'), ('DNS', 'localhost.localstack.cloud')), 'OCSP': ('http://r3.o.lencr.org',), 'caIssuers': ('http://r3.i.lencr.org/',)}
2023-01-09 08:46:33 localstack_main  | 2023-01-09T08:46:33.449  WARN --- [uncthread860] urllib3.connection         : Certificate did not match expected hostname: states.us-east-1.amazonaws.com. Certificate: {'subject': ((('commonName', 'localhost.localstack.cloud'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', "Let's Encrypt"),), (('commonName', 'R3'),)), 'version': 3, 'serialNumber': '03277A0FC6E52672285BB7C86D0D6083A2D9', 'notBefore': 'Dec 30 11:21:58 2022 GMT', 'notAfter': 'Mar 30 11:21:57 2023 GMT', 'subjectAltName': (('DNS', '*.amplifyapp.localhost.localstack.cloud'), ('DNS', '*.cloudfront.localhost.localstack.cloud'), ('DNS', '*.execute-api.localhost.localstack.cloud'), ('DNS', '*.localhost.localstack.cloud'), ('DNS', '*.opensearch.localhost.localstack.cloud'), ('DNS', '*.s3-website.localhost.localstack.cloud'), ('DNS', '*.s3.localhost.localstack.cloud'), ('DNS', '*.scm.localhost.localstack.cloud'), ('DNS', 'localhost.localstack.cloud')), 'OCSP': ('http://r3.o.lencr.org',), 'caIssuers': ('http://r3.i.lencr.org/',)}
2023-01-09 08:46:36 localstack_main  | 2023-01-09T08:46:36.781  WARN --- [uncthread860] urllib3.connection         : Certificate did not match expected hostname: states.us-east-1.amazonaws.com. Certificate: {'subject': ((('commonName', 'localhost.localstack.cloud'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', "Let's Encrypt"),), (('commonName', 'R3'),)), 'version': 3, 'serialNumber': '03277A0FC6E52672285BB7C86D0D6083A2D9', 'notBefore': 'Dec 30 11:21:58 2022 GMT', 'notAfter': 'Mar 30 11:21:57 2023 GMT', 'subjectAltName': (('DNS', '*.amplifyapp.localhost.localstack.cloud'), ('DNS', '*.cloudfront.localhost.localstack.cloud'), ('DNS', '*.execute-api.localhost.localstack.cloud'), ('DNS', '*.localhost.localstack.cloud'), ('DNS', '*.opensearch.localhost.localstack.cloud'), ('DNS', '*.s3-website.localhost.localstack.cloud'), ('DNS', '*.s3.localhost.localstack.cloud'), ('DNS', '*.scm.localhost.localstack.cloud'), ('DNS', 'localhost.localstack.cloud')), 'OCSP': ('http://r3.o.lencr.org',), 'caIssuers': ('http://r3.i.lencr.org/',)}
2023-01-09 08:46:41 localstack_main  | 2023-01-09T08:46:41.104  INFO --- [uncthread860] l.s.a.lambda_executors     : Error executing Lambda "arn:aws:lambda:us-east-1:000000000000:function:bdm-dev-launch-compress": TimeoutError: Function execution timed out 
2023-01-09 08:46:41 localstack_main  | 2023-01-09T08:46:41.134  INFO --- [uncthread860] l.s.awslambda.lambda_api   : Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:bdm-dev-launch-compress: {"errorType": "TimeoutError", "errorMessage": "Function execution timed out", "stackTrace": []} Traceback (most recent call last):
2023-01-09 08:46:41 localstack_main  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 459, in run_lambda
2023-01-09 08:46:41 localstack_main  |     result = LAMBDA_EXECUTOR.execute(
2023-01-09 08:46:41 localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 351, in execute_local_executor
2023-01-09 08:46:41 localstack_main  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 494, in execute
2023-01-09 08:46:41 localstack_main  |     return do_execute()
2023-01-09 08:46:41 localstack_main  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 484, in do_execute
2023-01-09 08:46:41 localstack_main  |     return _run(func_arn=func_arn)
2023-01-09 08:46:41 localstack_main  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 183, in wrapped
2023-01-09 08:46:41 localstack_main  |     raise e
2023-01-09 08:46:41 localstack_main  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 179, in wrapped
2023-01-09 08:46:41 localstack_main  |     result = func(*args, **kwargs)
2023-01-09 08:46:41 localstack_main  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 471, in _run
2023-01-09 08:46:41 localstack_main  |     raise e
2023-01-09 08:46:41 localstack_main  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 467, in _run
2023-01-09 08:46:41 localstack_main  |     result = self._execute(lambda_function, inv_context)
2023-01-09 08:46:41 localstack_main  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1514, in _execute
2023-01-09 08:46:41 localstack_main  |     raise InvocationException(result, log_output=log_output, result=result)
2023-01-09 08:46:41 localstack_main  | localstack.services.awslambda.lambda_executors.InvocationException: {"errorType": "TimeoutError", "errorMessage": "Function execution timed out", "stackTrace": []}
```

### Expected Behavior

Lambda to execute without the Certificate error.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

- Create a Lambda function that is triggered from an SQS queue
- Send an SQS message to trigger the Lambda
- Look at docker logs and you will see that the Lambda has been executed but with a Certificate error and the Lambda has timed out

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   docker compose pull && docker compose up

docker compose file is below - 

```
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - DEBUG=1
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=local
      - DEFAULT_REGION=us-east-1
      - LOCALSTACK_API_KEY=***REMOVED API KEY***
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

(N.B. - not exact command due to confidentiality - this is just to trigger the Lambda)

awslocal sqs send-message --queue-url http://localhost:4566/000000000000/test-queue --message-body {"test-key/test-file"}

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by dfangl** [comment]
Hi!
It is possible that you haven't set the endpoint of the SDK client in your lambda correctly. If you are using Pro, a DNS based redirect will (currently) take place, which will lead to this problem.
Can you try manually setting the endpoint of the client to LocalStack, and see if this fixes your problem? Depending on your SDK, you can find the appropriate documentation here: https://docs.localstack.cloud/user-guide/integrations/sdks/

**Comment by ifzal-ahmed-npl** [comment]
Thanks @dfangl the above resolved this issue. Is there a way to use a custom endpoint for a service? - I am using the below docker compose file and trying to get the lambda function to send `stepfunctions`  requests to `http://localhost:8083` but it doesn't seem to be working.

```
version: "3.8"
services:
    localstack:
        container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
        image: localstack/localstack-pro
        ports:
            - "127.0.0.1:4566:4566"            # LocalStack Gateway
            - "127.0.0.1:4510-4559:4510-4559"  # external services port range
            - "127.0.0.1:53:53"                # DNS config (only required for Pro)
            - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
            - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
        environment:
            - STEPFUNCTIONS_BACKEND=http://localhost:8083
            - EAGER_SERVICE_LOADING=1
            - SERVICES=s3,lambda,rds,ecs,ecr,ec2,sns,sqs,stepfunctions
            - LAMBDA_RUNTIME_EXECUTOR=docker
            - DOCKER_HOST=unix:///var/run/docker.sock
            - DEFAULT_REGION=us-east-1
            - LS_LOG=trace_internal
            #- DATA_DIR=/var/lib/localstack/state
            #- DATA_DIR=/var/lib/localstack
            - LAMBDA_DOCKER_NETWORK=localstack_nw      
            - LOCALSTACK_API_KEY=5RK9q11nf2  # only required for Pro
            - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=50
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
        networks:
            default:
    stepfunctions:
        container_name: stepfunctions
        image: amazon/aws-stepfunctions-local:latest
        environment:
            - AWS_ACCESS_KEY_ID         = "test"
            - AWS_SECRET_ACCESS_KEY     = "test"
            - AWS_ACCOUNT_ID            = "000000000000"
            - LAMBDA_ENDPOINT           = http://localstack.localstack.cloud:4566
        ports:
            - '8083:8083'
volumes:
    localstack_data:
networks:
    default:
        external:
            name: localstack_nw
