### ISSUE TITLE
cannot invoke a lambda

### ISSUE THREAD

**Issue by mattbroekhuis** [localstack/localstack#749]
I am unable to get my java8 jar lambda to run.

I tried running directly, i get this error

`aws --endpoint-url=http://localhost:4574 lambda invoke --function lambdaname '{}'`

```
An error occurred (InternalFailure) when calling the Invoke operation (reached max retries: 4): Error executing Lambda function: argument of type 'NoneType' is not iterable Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 259, in run_lambda
    event, context=context, version=version, async=async)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 462, in execute
    process.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 458, in do_execute
    result = lambda_function(event, context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 399, in execute
    handler=arn_to_lambda[arn].handler, main_file=main_file)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 477, in execute_java_lambda
    if 'Records' in event:
TypeError: argument of type 'NoneType' is not iterable
```

I tried adding an sns topic and a subscription, the lambda is never invoked and there is nothing in the logs. 

I am running localstack in docker 

```
version: '2.1'
#you must run TMPDIR=/private$TMPDIR docker-compose up on a mac
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4583:4567-4583"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,sns,lambda,cloudwatch
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=local
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

**Comment by vsamofal** [comment]
I faced the same problem. I believe it's because of LAMBDA_EXECUTOR, it's not such easy to execute whatever you want locally. 
I changed this parameter to this: (and it's looks ok now)
`- LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- docker-reuse}`

**Comment by whummer** [comment]
Thanks for reporting @mattbroekhuis . Seems like you're not using the right CLI command - the following worked for me (note the `--payload` flag):
```
aws --endpoint-url=http://localhost:4574 lambda invoke --function lambdaname --payload '{}' /tmp/lambda.out
```
Closing this issue for housekeeping reasons, please reopen if the problem persists. Thanks
