### ISSUE TITLE
Error when start localstack on Windows 10

### ISSUE THREAD

**Issue by ngocmanh1712** [localstack/localstack#751]
Dear localstack team,

I am trying to install localstack but after run "localstack start" then an error occurs like below:
```
Error starting infrastructure: 'utf-8' codec can't decode byte 0x82 in position 6: invalid start byte Traceback (most recent call last):
  File "C:\users\manh_vietis\appdata\local\programs\python\python36\lib\site-packages\localstack\services\infra.py", line 465, in start_infra
    install.install_components(apis)
  File "C:\users\manh_vietis\appdata\local\programs\python\python36\lib\site-packages\localstack\services\install.py", line 137, in install_components
    parallelize(install_component, names)
  File "C:\users\manh_vietis\appdata\local\programs\python\python36\lib\site-packages\localstack\utils\common.py", line 751, in parallelize
    result = pool.map(func, list)
  File "C:\users\manh_vietis\appdata\local\programs\python\python36\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\users\manh_vietis\appdata\local\programs\python\python36\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\users\manh_vietis\appdata\local\programs\python\python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\users\manh_vietis\appdata\local\programs\python\python36\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\users\manh_vietis\appdata\local\programs\python\python36\lib\site-packages\localstack\services\install.py", line 129, in install_component
    install_dynamodb_local()
  File "C:\users\manh_vietis\appdata\local\programs\python\python36\lib\site-packages\localstack\services\install.py", line 99, in install_dynamodb_local
    run('cd "%s" && zip -u DynamoDBLocal.jar log4j2.xml || true' % INSTALL_DIR_DDB)
  File "C:\users\manh_vietis\appdata\local\programs\python\python36\lib\site-packages\localstack\utils\common.py", line 653, in run
    return do_run(cmd)
  File "C:\users\manh_vietis\appdata\local\programs\python\python36\lib\site-packages\localstack\utils\common.py", line 636, in do_run
    return output.decode(DEFAULT_ENCODING)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 6: invalid start byte

ERROR: 'utf-8' codec can't decode byte 0x82 in position 6: invalid start byte
```

I have searched this bug on Google but can't find anything useful.

**Comment by Blanderbuss** [comment]
I have similar problem here. Localstack version is 0.9.0
`Error starting infrastructure: 'utf-8' codec can't decode byte 0xad in position 6: invalid start byte Traceback (most recent call last):
  File "C:\users\user\appdata\local\programs\python\python36\lib\site-packages\localstack\services\infra.py", line 477, in start_infra
    install.install_components(apis)
  File "C:\users\user\appdata\local\programs\python\python36\lib\site-packages\localstack\services\install.py", line 159, in install_components
    parallelize(install_component, names)
  File "C:\users\user\appdata\local\programs\python\python36\lib\site-packages\localstack\utils\common.py", line 802, in parallelize
    result = pool.map(func, list)
  File "C:\users\user\appdata\local\programs\python\python36\lib\multiprocessing\pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\users\user\appdata\local\programs\python\python36\lib\multiprocessing\pool.py", line 670, in get
    raise self._value
  File "C:\users\user\appdata\local\programs\python\python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\users\user\appdata\local\programs\python\python36\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\users\user\appdata\local\programs\python\python36\lib\site-packages\localstack\services\install.py", line 155, in install_component
    installer()
  File "C:\users\user\appdata\local\programs\python\python36\lib\site-packages\localstack\services\install.py", line 118, in install_dynamodb_local
    run('cd "%s" && zip -u DynamoDBLocal.jar log4j2.xml || true' % INSTALL_DIR_DDB)
  File "C:\users\user\appdata\local\programs\python\python36\lib\site-packages\localstack\utils\common.py", line 704, in run
    return do_run(cmd)
  File "C:\users\user\appdata\local\programs\python\python36\lib\site-packages\localstack\utils\common.py", line 687, in do_run
    return output.decode(DEFAULT_ENCODING)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 6: invalid start byte

ERROR: 'utf-8' codec can't decode byte 0xad in position 6: invalid start byte
`

**Comment by whummer** [comment]
Thanks for reporting @ngocmanh1712 @Blanderbuss . 

Can you please try installing the latest version `0.10.0` under Windows. The installation has been refactored, and should hopefully fix this issue. Please report here - thanks.

**Comment by whummer** [comment]
Installation should work now under Windows (see also changes in #1631). Closing this issue - please re-open if the problem persists.
