### ISSUE TITLE
ValueError: time data '...' does not match format '%Y-%m-%dT%H:%M:%SZ' and a whole bunch of other errors in S3 object lock

### ISSUE THREAD

**Issue by Veetaha** [localstack/localstack#7517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When calling `DeleteObject` for an object protected by object lock `localstack` returns a 500 Internal Server Error instead of Access Denied error if we do a `PutObjectRetention` with the date that doesn't match the format specified in the issue title, but otherwise is a valid RFC3339 date-time. Note that `PutObjectRetention` succeeds, but `DeleteObject` fails with this error persistently:

```
<!doctype html><html lang=en><title>500 Internal Server Error</title><h1>Internal Server Error</h1><p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

### Expected Behavior

Localstack S3 should allow the date-times that contain nanoseconds and a non-utc time zone or a time zone `+00:00`.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
docker run \
  -p 4566:4566 \
  -e EDGE_PORT=4566 \
  -e DEBUG=1 \
  -e LAMBDA_EXECUTOR=docker-reuse \
  -e LAMBDA_REMOTE_DOCKER=false \
  -e LAMBDA_DOCKER_NETWORK=elastio-shared-docker-network \
  -e DOCKER_HOST=unix:///var/run/docker.sock \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --network-alias localstack \
  --network elastio-shared-docker-network \
  localstack/localstack:1.3.1
```

#### Client commands

Put the following terraform code into a `main.tf` file

```tf
resource "aws_s3_bucket" "this" {
  bucket              = "sample"
  force_destroy       = true
  object_lock_enabled = true
}

resource "aws_s3_bucket_versioning" "this" {
  bucket = aws_s3_bucket.this.id
  versioning_configuration {
    status = "Enabled"
  }

  depends_on = [aws_s3_bucket_object_lock_configuration.this]
}

resource "aws_s3_bucket_object_lock_configuration" "this" {
  bucket = aws_s3_bucket.this.id
  rule {
    default_retention {
      mode = "COMPLIANCE"
      days = 1
    }
  }
}

resource "aws_s3_object" "this" {
  depends_on = [aws_s3_bucket_object_lock_configuration.this]

  key    = "sample.tf"
  bucket = aws_s3_bucket.this.id
  source = "${path.module}/main.tf"
}

provider "aws" {
  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    acm              = "http://localhost:${var.localstack_port}"
    apigateway       = "http://localhost:${var.localstack_port}"
    cloudformation   = "http://localhost:${var.localstack_port}"
    cloudwatch       = "http://localhost:${var.localstack_port}"
    cloudwatchlogs   = "http://localhost:${var.localstack_port}"
    dynamodb         = "http://localhost:${var.localstack_port}"
    ec2              = "http://localhost:${var.localstack_port}"
    cloudwatchevents = "http://localhost:${var.localstack_port}"
    firehose         = "http://localhost:${var.localstack_port}"
    iam              = "http://localhost:${var.localstack_port}"
    kinesis          = "http://localhost:${var.localstack_port}"
    kms              = "http://localhost:${var.localstack_port}"
    lambda           = "http://localhost:${var.localstack_port}"
    redshift         = "http://localhost:${var.localstack_port}"
    route53          = "http://localhost:${var.localstack_port}"
    s3               = "http://localhost:${var.localstack_port}"
    secretsmanager   = "http://localhost:${var.localstack_port}"
    ses              = "http://localhost:${var.localstack_port}"
    sns              = "http://localhost:${var.localstack_port}"
    sqs              = "http://localhost:${var.localstack_port}"
    ssm              = "http://localhost:${var.localstack_port}"
    stepfunctions    = "http://localhost:${var.localstack_port}"
    sts              = "http://localhost:${var.localstack_port}"
  }
}

variable "localstack_port" {
  type    = number
  default = 4566
}
```

Then do the following:

```py
# Deploy the stack to localstack
terraform apply -auto-approve

# Get the object version
version_id=$(awslocal s3api list-object-versions --bucket sample --query 'Versions[0].VersionId' --output text)
```

At this point you will also notice one more bug that `get-object-retention` doesn't work. It returns the file contents, and the AWS CLI fails to parse the response:

```
awslocal s3api get-object-retention --bucket sample --key sample.tf --version-id $version_id        

Unable to parse response (syntax error: line 1, column 0), invalid XML received. Further retries may succeed:
b'resource "aws_s3_bucket" "this" {\n{SNIP}
```

I didn't create a separate issue for that, but I think it's enough to specify it here.

Then another bug here is when we try to `put-object-retention` for a non-existent key, we get a 500 error

```
awslocal s3api put-object-retention --bucket sample --key non-existent-key.tf --version-id $version_id --retention '{ "Mode": "COMPLIANCE", "RetainUntilDate": "2025-01-01T01:00:00.100100100+00:00" }'
```

<details>
<summary>Localstack logs</summary>

```
2023-01-18T20:46:43.634 ERROR --- [uest_thread)] werkzeug                   : Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/moto_server/werkzeug_app.py", line 239, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
    return new(target, *args, **kwargs)
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 174, in convert_to_flask_response_call
    return fn(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/utils.py", line 106, in __call__
    result = self.callback(request, request.url, dict(request.headers))
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/utilities/aws_headers.py", line 64, in _wrapper
    response = f(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1118, in key_response
    response = self._key_response(request, full_url, self.headers)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1209, in _key_response
    return self._key_response_put(request, body, bucket_name, query, key_name)
  File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
    return new(target, *args, **kwargs)
  File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 190, in s3_key_response_put
    result = fn(request, body, bucket_name, query, key_name, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1446, in _key_response_put
    self.backend.put_object_retention(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/models.py", line 1807, in put_object_retention
    key.lock_mode = retention[0]
AttributeError: 'NoneType' object has no attribute 'lock_mode'
```

</details>

Then, to reproduce the particular error with the date, we need to use the `rusoto_s3` SDK (we are using 0.46 version of it). For some reason, it doesn't reproduce with AWS CLI

⚠️ This isn't reproducible with AWS CLI, but it is with the custom SDK

```rs
s3.put_object_retention(PutObjectRetentionRequest {
        bucket: "sample".to_owned(),
        key: "sample.tf".to_owned(),
        retention: Some(ObjectLockRetention {
            mode: Some("COMPLIANCE".to_owned()),
            // Pay attention that date-time must be in this exact form with 9 digits for nanoseconds      
            retain_until_date: Some("2023-01-19T21:20:26.228480211+00:00".to_owned()),
        }),
        version_id: Some("d45b0af2-4718-4f51-92cb-c86d7ee764db".to_owned()),
        ..Default::default()
    })
    .await
    .unwrap();
```

After this, if we attempt to delete the object version we will also get a 500 error but with a different message:

```
awslocal s3api delete-object --bucket sample --key sample.tf --version-id $version_id
```

This fails with the following trace in localstack container

<details>
<summary>Localstack logs</summary>

```
2023-01-18T21:07:26.465  INFO --- [   asgi_gw_4] localstack.request.aws     : AWS s3.DeleteObjects => 500 (500)
2023-01-18T21:07:26.470 ERROR --- [uest_thread)] werkzeug                   : Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/models.py", line 331, in is_locked
    until = datetime.datetime.strptime(
  File "/usr/local/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2023-01-19T21:07:26.228480211+00:00' does not match format '%Y-%m-%dT%H:%M:%SZ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/moto_server/werkzeug_app.py", line 239, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
    return new(target, *args, **kwargs)
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 174, in convert_to_flask_response_call
    return fn(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/utils.py", line 106, in __call__
    result = self.callback(request, request.url, dict(request.headers))
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 245, in ambiguous_response
    return self.bucket_response(request, full_url, headers)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/utilities/aws_headers.py", line 64, in _wrapper
    response = f(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 251, in bucket_response
    response = self._bucket_response(request, full_url)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 296, in _bucket_response
    return self._bucket_response_post(request, bucket_name)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 968, in _bucket_response_post
    return self._bucket_response_delete_keys(bucket_name)
  File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 290, in s3_bucket_response_delete_keys
    success = self.backend.delete_object(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/models.py", line 2128, in delete_object
    hasattr(key, "is_locked")
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/models.py", line 335, in is_locked
    until = datetime.datetime.strptime(
  File "/usr/local/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2023-01-19T21:07:26.228480211+00:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```

</details>

### Environment

```markdown
- OS: `Ubuntu 20.04`
- LocalStack: `1.3.0`
```

### Anything else?

While debugging this I've figured out that `awslocal s3api get-object-retention` is also broken see the reproduction steps above.

**Comment by whummer** [comment]
Thanks for reporting @Veetaha . We have added a number of enhancements in S3 recently, and with our v2.0 release we have switched to our new S3 provider implementation. Can you please pull the `latest` Docker image and see if the problem persists? Thanks for your help!

**Comment by bentsku** [comment]
Hello @Veetaha and thanks again for your report. The issue should be fixed in the `latest` docker image. Could you update and give it a try to see if that fixes your issue? Thanks!

**Comment by bentsku** [comment]
I'll close this issue as it should now be fixed, but feel free to open another for the migration issue, or we could maybe help you on Slack. I hope you'll be able to upgrade, as we're release our next major release this week. Thanks again for the report
