### ISSUE TITLE
S3 Bucket creation not attaching bucket-notification (terraform)

### ISSUE THREAD

**Issue by jonaskint** [localstack/localstack#752]
Hi, I've been trying to setup the following setup with localstack:
[S3 Bucket] -> [Bucket Notification s3:ObjectCreated:*] -> [SNS Topic] -> [Lambda]

### The configuration
I'm currently using the lastest localstack docker image and the docker-compose file that was provided in the repo.

The complete setup is being set up with terraform. I've managed to change the configs for the different endpoints with the following implementation:
```hcl
terraform {
  required_version = "0.11.7"
}

provider "aws" {
  region                      = "us-east-1"
  access_key                  = "anaccesskey"
  secret_key                  = "asecretkey"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  s3_force_path_style         = true

  endpoints {
    s3     = "http://localhost:4572"
    sns    = "http://localhost:4575"
    sqs    = "http://localhost:4576"
    lambda = "http://localhost:4574"
  }
}
```

My bucket creation looks as following:
```hcl
resource "aws_s3_bucket" "assets" {
  bucket = "assets"
  acl = "private"

  server_side_encryption_configuration {
    "rule" {
      "apply_server_side_encryption_by_default" {
        sse_algorithm = "AES256"
      }
    }
  }

  versioning {
    enabled = true
  }

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = [
      "PUT",
      "POST",
      "HEAD",
      "GET",
      "DELETE"]
    allowed_origins = ["https://*.test-dev.biz", "http://localhost"]
    expose_headers = ["ETag", "Content-Range"]
    max_age_seconds = 3000
  }
}
```

The SNS topic:
```hcl
resource "aws_sns_topic" "assets_bucket_topic" {
  name         = "assets-bucket-changeset"
  display_name = "s3-changes"

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
  {
    "Effect": "Allow",
    "Principal": {
      "AWS": "*"
    },
    "Action": "SNS:Publish",
    "Resource": "arn:aws:sns:us-east-1:123456789012:assets-bucket-changeset",
    "Condition": {
      "ArnEquals": { "aws:SourceArn": "arn:aws:s3:*:*:${aws_s3_bucket.assets.bucket}" }
    }
  }
  ]
}
POLICY
}
```

And my bucket notification:
```hcl
# Send notifications from the bucket
resource "aws_s3_bucket_notification" "bucket_creations" {
  bucket = "${aws_s3_bucket.assets.id}"

  topic {
    topic_arn = "${aws_sns_topic.assets_bucket_topic.arn}"
    events    = ["s3:ObjectCreated:*", ""]
  }
}
```

### The problem
With this setup I'm running against some issues where for starters, the cors settings are not attached:
``` bash
λ jonas [~/] → aws --endpoint-url=http://localhost:4572 s3api get-bucket-cors --bucket assets

Unable to parse response (no element found: line 2, column 0), invalid XML received:
b'<?xml version="1.0" encoding="utf-8"?>\n'
```

And neither the notification configuration:
```
λ jonas [~/] → aws --endpoint-url=http://localhost:4572 s3api get-bucket-notification --bucket assets

λ jonas [~/] →
```
Is there anything that I'm overlooking or implementing in a bad way?
Note that the used terraform code is already being used against AWS so it should work as implemented here.

**Comment by jonaskint** [comment]
I've enabled debug logging to get some more insights.
```
10:55:03.553 [main] INFO  org.elasticmq.server.Main$ - === ElasticMQ server (0.13.8) started in 14686 ms ===
10:55:03.552 [elasticmq-akka.actor.default-dispatcher-4] INFO  o.e.rest.sqs.TheSQSRestServerBuilder - Started SQS rest server, bind address 0.0.0.0:4561, visible server address http://3b4fd18b198f:4576
127.0.0.1 - - [07/May/2018 10:55:07] "PUT /assets?cors= HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 10:55:07] "PUT /assets?versioning= HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 10:55:07] "PUT /assets?acl= HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 10:55:07] "PUT /assets?encryption= HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 10:55:07] "HEAD /assets HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 10:55:07] "GET /assets?cors= HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 10:55:07] "GET /assets?website= HTTP/1.1" 404 -
127.0.0.1 - - [07/May/2018 10:55:07] "GET /assets?versioning= HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 10:55:07] "GET /assets?accelerate= HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 10:55:08] "GET /assets?requestPayment= HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 10:55:08] "GET /assets?logging= HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 10:55:08] "GET /assets?lifecycle= HTTP/1.1" 404 -
127.0.0.1 - - [07/May/2018 10:55:08] "GET /assets?replication= HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 10:55:08] "GET /assets?encryption= HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 10:55:08] "GET /assets?location= HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2018 10:55:08] "GET /assets?tagging= HTTP/1.1" 404 -
```

It looks like the /assets?tagging, website and lifecycle are returning 404's. Is this expected?

**Comment by jonaskint** [comment]
When i try to attach the cors settings manually i get the following error:
```bash
2018-05-07T13:04:12:ERROR:localstack.services.generic_proxy: Error forwarding request: update() argument 1 must be string or buffer, not bool Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 215, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 500, in return_response
    append_cors_headers(bucket_name, request_method=method, request_headers=headers, response=response)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 227, in append_cors_headers
    response.headers[header] = md5(response._content)
  File "/opt/code/localstack/localstack/utils/common.py", line 229, in md5
    m.update(to_bytes(string))
TypeError: update() argument 1 must be string or buffer, not bool
```

The command i used is:
```bash
aws s3api --endpoint=http://localhost:4572  put-bucket-cors --bucket assets --cors-configuration file://config/s3/cors.json
```

Contents of the cors.json:
```json
{
  "CORSRules": [
    {
      "AllowedOrigins": ["*"],
      "AllowedHeaders": ["*"],
      "AllowedMethods": ["PUT", "POST", "DELETE", "HEAD", "GET"],
      "MaxAgeSeconds": 3000,
      "ExposeHeaders": ["ETag", "Content-Range"]
    }
  ]
}
```

**Comment by jonaskint** [comment]
Going to close this one as it's probably something terraform related.

**Comment by aldib** [comment]
Were you able to solve it? I have the same problem
