### ISSUE TITLE
bug: ApiGateway with SNS integration fails with cannot convert dictionary update sequence element to a sequence

### ISSUE THREAD

**Issue by romangarcia** [localstack/localstack#7525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After first deploy with `samlocal`, when testing the ApiGateway method it fails with 400. 

The error says something about:
`TypeError: cannot convert dictionary update sequence element #0 to a sequence`

Looking at logs from the docker container it seems this is happening when processing the response. Stack trace:
```
2023-01-18T17:18:19.792 ERROR --- [ asgi_gw_0] l.s.apigateway.invocations : Error invoking integration for API Gateway ID '2k5lhjvdrp': cannot convert dictionary update sequence element #0 to a sequence
Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/apigateway/invocations.py", line 290, in invoke_rest_api_integration
response = invoke_rest_api_integration_backend(invocation_context)
File "/opt/code/localstack/localstack/services/apigateway/invocations.py", line 441, in invoke_rest_api_integration_backend
return apply_request_response_templates(
File "/opt/code/localstack/localstack/services/apigateway/invocations.py", line 548, in apply_request_response_templates
result = VtlTemplate().render_vtl(template, content, as_json=as_json)
File "/opt/code/localstack/localstack/utils/aws/templating.py", line 77, in render_vtl
namespace = self.prepare_namespace(variables)
File "/opt/code/localstack/localstack/utils/aws/templating.py", line 97, in prepare_namespace
namespace = dict(variables or {})
TypeError: cannot convert dictionary update sequence element #0 to a sequence
2023-01-18T17:18:19.795 INFO --- [ asgi_gw_0] localstack.request.http : POST /local/ => 400
```

The error only happens after our first `samlocal deploy`. If we deploy a second time the error goes away.

This is the CFN template.yaml that we `samlocal build && samlocal deploy ....`:

```
Transform: AWS::Serverless-2016-10-31

Parameters:
  EnvironmentStackName:
    Type: String
    AllowedValues:
      - local
      - qa
      - prod

Mappings:
  Domain:
    Name:
      local: 'webhooks-local.xxx.gg'
      qa: 'webhooks-qa.xxx.gg'

Resources:
  MoodleWebhookTopicQueue:
    Type: AWS::SQS::Queue

  MoodleWebhookTopic:
    Type: AWS::SNS::Topic

  SnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !GetAtt MoodleWebhookTopicQueue.Arn
      TopicArn: !Ref MoodleWebhookTopic

  SQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MoodleWebhookTopicQueue
      PolicyDocument:
        Statement:
          - Action: "SQS:SendMessage"
            Effect: "Allow"
            Resource: "*"
            Principal:
              Service: sns.amazonaws.com

  MoodleWebhookApiGateway:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Sub "${EnvironmentStackName}-MoodleWebhookApiGateway"
      EndpointConfiguration:
        Types:
          - REGIONAL

  MoodleWebhookApiGatewayMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref MoodleWebhookApiGateway
      ResourceId: !GetAtt MoodleWebhookApiGateway.RootResourceId
      AuthorizationType: NONE
      HttpMethod: POST
      MethodResponses:
        - StatusCode: 200
      Integration:
        Type: AWS
        Credentials: !GetAtt ApiGatewayRole.Arn
        IntegrationHttpMethod: POST
        PassthroughBehavior: NEVER
        IntegrationResponses: #map all responses to a default response.
          - StatusCode: 200
            ResponseTemplates: #default response
              application/json: '{"status":"OK"}'
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:sns:path//"
        RequestParameters:
          integration.request.header.Content-Type: "application/x-www-form-urlencoded"
        RequestTemplates:
          "application/json": !Sub "Action=Publish&TopicArn=$util.urlEncode('${MoodleWebhookTopic}')&Message=$util.urlEncode($input.body)"

  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: GatewayRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sns:Publish
                Resource: !Ref MoodleWebhookTopic
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                  - logs:GetLogEvents
                  - logs:FilterLogEvents
                Resource: '*'

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Description: '1'
    DependsOn:
      - MoodleWebhookApiGatewayMethod
    Properties:
      RestApiId: !Ref MoodleWebhookApiGateway
      StageName: !Ref EnvironmentStackName

  Account:
    Type: 'AWS::ApiGateway::Account'
    Properties:
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

  CloudWatchRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - >-
          arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  CustomDomainName:
    Type: 'AWS::ApiGateway::DomainName'
    Properties:
      DomainName: !FindInMap [Domain, Name, !Ref "EnvironmentStackName"]
      CertificateArn: 'arn:aws:acm:us-east-1:xxxx:certificate/uuid'

  Mapping:
    Type: 'AWS::ApiGateway::BasePathMapping'
    Properties:
      DomainName: !Ref CustomDomainName
      RestApiId: !Ref MoodleWebhookApiGateway
      Stage: !Ref EnvironmentStackName

Outputs:
  MoodleWebhookTopicArn:
    Value: !Ref MoodleWebhookTopic
    Export:
      Name:
        Fn::Sub: ${EnvironmentStackName}-moodle-webhooks-TopicArn
  MoodleWebhookApiId:
    Value: !Ref MoodleWebhookApiGateway
```

### Expected Behavior

For ApiGateway to reply as expected. For the first deploy to work same as second deploy.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

 Both from TestContainers docker and from Docker Desktop extension. Fails on both the same.

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```
> samlocal build
> samlocal deploy --resolve-s3 --capabilities CAPABILITY_IAM --stack-name local-moodle-webhooks-docker --region us-east-1 -t .aws-sam/build/template.yaml --config-env=local --parameter-overrides EnvironmentStackName=local
```

### Environment

```markdown
- OS: MacOs Monterey 12.6
- LocalStack: 1.3.1 & 1.3.2-dev
```

**Comment by calvernaz** [comment]
Hi @romangarcia hope to find you well. I was trying to reproduce this issue and it's working fine for me, I wonder if this is not an issue anymore.

After following your instructions I ran this

```
curl -X POST <api-id>.execute-api.localhost.localstack.cloud:4566/local/ -d "this is a test"
```
and had no issues. Do you mind retry again?
