### ISSUE TITLE
bug: Lambda invokation fails with "Unhandled" response 

### ISSUE THREAD

**Issue by mishabruml** [localstack/localstack#7527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello world lambda built in typescript, bundled/zipped, and deployed to localstack via terraform. The lambda deploys succesfully and is there when running e.g. `awslocal lambda list-functions`, it even shows the correct sized code bundle.

Invokation does not work though:

```sh
root@engine-local-stack:/opt/code/localstack# awslocal lambda invoke --function-name test response.json
{
    "StatusCode": 200,
    "FunctionError": "Unhandled",
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
root@engine-local-stack:/opt/code/localstack# cat response.json 
{"errorMessage":"Lambda process returned with error. Result: . Output:\n","errorType":"InvocationException","stackTrace":["  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 459, in run_lambda\n    result = LAMBDA_EXECUTOR.execute(\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 494, in execute\n    return do_execute()\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 484, in do_execute\n    return _run(func_arn=func_arn)\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 183, in wrapped\n    raise e\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 179, in wrapped\n    result = func(*args, **kwargs)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 471, in _run\n    raise e\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 467, in _run\n    result = self._execute(lambda_function, inv_context)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 790, in _execute\n    result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 712, in run_lambda_executor\n    raise InvocationException(\n"]}
```

debug logs from localstack container:

```
2023-01-20T00:09:12.293  INFO --- [uest_thread)] l.s.a.lambda_executors     : Empty event body specified for invocation of Lambda "arn:aws:lambda:eu-west-1:000000000000:function:test"
2023-01-20T00:09:12.293 DEBUG --- [uest_thread)] l.u.c.container_client     : Getting ipv4 address for container engine-local-stack in network engine_default.
2023-01-20T00:09:12.319  INFO --- [uest_thread)] l.u.container_networking   : Determined main container target IP: 172.21.0.3
2023-01-20T00:09:12.319  INFO --- [uest_thread)] l.s.a.lambda_executors     : Running lambda: arn:aws:lambda:eu-west-1:000000000000:function:test
2023-01-20T00:09:12.319 DEBUG --- [uest_thread)] stevedore.extension        : found extension EntryPoint(name='docker_separate_lambda_execution', value='localstack_ext.services.awslambda.lambda_launcher:docker_separate_lambda_execution', group='localstack.hooks.on_docker_separate_execution')
2023-01-20T00:09:12.321 ERROR --- [uest_thread)] plugin.manager             : error importing entrypoint EntryPoint(name='docker_separate_lambda_execution', value='localstack_ext.services.awslambda.lambda_launcher:docker_separate_lambda_execution', group='localstack.hooks.on_docker_separate_execution'): No module named 'localstack_ext.services.awslambda.lambda_launcher'
2023-01-20T00:09:12.321 DEBUG --- [uest_thread)] plugin.manager             : no extensions found in namespace localstack.hooks.on_docker_separate_execution
2023-01-20T00:09:12.321 DEBUG --- [uest_thread)] l.u.c.docker_sdk_client    : Creating container with attributes: {'mount_volumes': None, 'ports': <PortMappings: {}>, 'cap_add': None, 'cap_drop': None, 'security_opt': None, 'dns': '', 'additional_flags': '', 'workdir': None, 'privileged': None, 'command': 'test.test', 'detach': False, 'entrypoint': None, 'env_vars': {'AWS_ACCESS_KEY_ID': 'test', 'AWS_SECRET_ACCESS_KEY': 'test', 'AWS_REGION': 'eu-west-1', 'DOCKER_LAMBDA_USE_STDIN': '1', 'LOCALSTACK_HOSTNAME': '172.21.0.3', 'EDGE_PORT': '4566', '_HANDLER': 'test.test', 'AWS_LAMBDA_FUNCTION_TIMEOUT': '3', 'AWS_LAMBDA_FUNCTION_NAME': 'test', 'AWS_LAMBDA_FUNCTION_VERSION': '$LATEST', 'AWS_LAMBDA_FUNCTION_INVOKED_ARN': 'arn:aws:lambda:eu-west-1:000000000000:function:test', 'NODE_TLS_REJECT_UNAUTHORIZED': '0'}, 'image_name': 'lambci/lambda:nodejs18.x', 'interactive': True, 'name': None, 'network': 'engine_default', 'remove': True, 'self': <localstack.utils.container_utils.docker_sdk_client.SdkDockerClient object at 0x7f80ef9b3b20>, 'tty': False, 'user': None}
2023-01-20T00:09:12.339 DEBUG --- [uest_thread)] l.u.c.docker_sdk_client    : Pulling Docker image: lambci/lambda:nodejs18.x
2023-01-20T00:09:17.141 DEBUG --- [uest_thread)] l.s.a.lambda_executors     : Lambda arn:aws:lambda:eu-west-1:000000000000:function:test result / log output:

>
2023-01-20T00:09:17.160 DEBUG --- [   asgi_gw_5] plugin.manager             : instantiating plugin PluginSpec(localstack.aws.provider.logs:default = <function logs at 0x7f80ec146c20>)
2023-01-20T00:09:17.160 DEBUG --- [   asgi_gw_5] plugin.manager             : loading plugin localstack.aws.provider:logs:default
2023-01-20T00:09:17.174 DEBUG --- [   asgi_gw_5] l.services.plugins         : checking service health logs:4566
2023-01-20T00:09:17.239  INFO --- [uest_thread)] l.s.a.lambda_executors     : writing log to file '/var/lib/localstack/tmp/lambda_c_saciys.log'
2023-01-20T00:09:17.275  INFO --- [uest_thread)] l.s.awslambda.lambda_api   : Error executing Lambda function arn:aws:lambda:eu-west-1:000000000000:function:test: Lambda process returned with error. Result: . Output:
 Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 555, in create_container
    container = create_container()
  File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 537, in create_container
    return self.client().containers.create(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/models/containers.py", line 870, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/containers/create: Not Found ("No such image: lambci/lambda:nodejs18.x")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/create?tag=nodejs18.x&fromImage=lambci%2Flambda

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 220, in pull_image
    self.client().images.pull(docker_image)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/models/images.py", line 446, in pull
    pull_log = self.client.api.pull(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/image.py", line 430, in pull
    self._raise_for_status(response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=nodejs18.x&fromImage=lambci%2Flambda: Not Found ("manifest for lambci/lambda:nodejs18.x not found: manifest unknown: manifest unknown")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 667, in run_lambda_executor
    result, log_output = self.execute_in_container(
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1276, in execute_in_container
    container_id = DOCKER_CLIENT.create_container(
  File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 557, in create_container
    self.pull_image(image_name)
  File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 224, in pull_image
    raise ContainerException() from e
localstack.utils.container_utils.container_client.ContainerException

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 459, in run_lambda
    result = LAMBDA_EXECUTOR.execute(
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 494, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 484, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 183, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 179, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 471, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 467, in _run
    result = self._execute(lambda_function, inv_context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 790, in _execute
    result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 712, in run_lambda_executor
    raise InvocationException(
localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: . Output:


2023-01-20T00:09:17.275 DEBUG --- [uest_thread)] l.s.awslambda.lambda_api   : Lambda invocation duration: 5361.89ms
2023-01-20T00:09:17.278  INFO --- [   asgi_gw_4] localstack.request.aws     : AWS lambda.Invoke => 200
```

### Expected Behavior

Expect to get a response from lambda, and for invokation to run packaged lambda code.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yml
local-stack:
    image: localstack/localstack:1.3.1
    hostname: engine-local-stack
    container_name: engine-local-stack
    restart: on-failure
    environment:
      - SERVICES=s3,sqs,lambda
      - DEFAULT_REGION=eu-west-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=true
      - LAMBDA_DOCKER_NETWORK=engine_default
    ports:
      - '4566:4566'
      - '4571:4571'
    volumes:
      - '${TMPDIR:-/tmp/localstack}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - docker-local-stack-events-listener
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

`awslocal lambda invoke --function-name test response.json`

### Environment

```markdown
- OS: MacOS
- LocalStack:latest
```

### Anything else?

The following shows the deployed lambda configuration: 
```
root@engine-local-stack:/opt/code/localstack# awslocal lambda get-function --function-name test
{
    "Configuration": {
        "FunctionName": "test",
        "FunctionArn": "arn:aws:lambda:eu-west-1:000000000000:function:test",
        "Runtime": "nodejs18.x",
        "Role": "fake-role",
        "Handler": "test.test",
        "CodeSize": 1351,
        "Description": "",
        "Timeout": 3,
        "MemorySize": 128,
        "LastModified": "2023-01-20T00:08:12.813+0000",
        "CodeSha256": "cpRim/sPfN7AfOp8Ou0BBrgyAZfV0IoWEia6h9DMvmY=",
        "Version": "$LATEST",
        "VpcConfig": {},
        "TracingConfig": {
            "Mode": "PassThrough"
        },
        "RevisionId": "4999a4dc-7ad0-4554-8635-9d0a7e9384f6",
        "State": "Active",
        "LastUpdateStatus": "Successful",
        "PackageType": "Zip",
        "Architectures": [
            "x86_64"
        ]
    },
    "Code": {
        "Location": "http://localhost:4566/2015-03-31/functions/test/code"
    },
    "Tags": {}
}
```

**Comment by mishabruml** [comment]
Since we're on node18.x runtime, I added `PROVIDER_OVERRIDE_LAMBDA=asf` to `docker-compose.yml` as per #7209 and its working now 😄
