### ISSUE TITLE
bug: replicate-key error for RSA multi-region KMS keys

### ISSUE THREAD

**Issue by gevans201** [localstack/localstack#7535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When calling `kms replicate-key` for `RSA_4096` keys the following error is thrown: 

`An error occurred (InternalError) when calling the ReplicateKey operation (reached max retries: 4): exception while calling kms.ReplicateKey: cannot pickle '_cffi_backend.FFI' object`.

### Expected Behavior

There should be a response containing the `ReplicaKeyMetadata` for the new replica key.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

awslocal kms create-key \
--key-spec RSA_4096 \
--multi-region

awslocal kms replicate-key \
--key-id `<KeyId from previous command response>` \
--replica-region eu-west-1

### Environment

```markdown
- OS: MacOS Ventura 13.1
- LocalStack: latest
```

**Comment by kingan379** [comment]
I have the same issue. Getting following error:

aws  kms --endpoint-url=http://localhost:4566 replicate-key --key-id mrk-ba534667009f4bc3b1e4c980d96d475c --replica-region ca-central-1

An error occurred (InternalError) when calling the ReplicateKey operation (reached max retries: 2): exception while calling kms.ReplicateKey: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 122, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 92, in __call__
    skeleton_response = self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/aws/api/core.py", line 151, in operation_marker
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/kms/provider.py", line 252, in replicate_key
    replica_key = copy.deepcopy(key)
  File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.10/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_cffi_backend.FFI' object

**Comment by sannya-singal** [comment]
Hi @gevans201, thanks for using localstack 🚀. Can you please pull the `latest` docker image and give it a try?
