### ISSUE TITLE
bug: ECS task execution from statemachine failing and not giving any meaningful error 

### ISSUE THREAD

**Issue by Hardeep-Dhillon-Nowp** [localstack/localstack#7542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 Issue is running running ECS task from the state-machine. It does not give any meaningful error and just shows below (code 1). I am using docker windows and WSL to test localstack pro. I treid using the stepfunction docker image as well, it builds and uploads/register the images to ECR. I could list the images with pointing the awslocal --endpoint-url=http://localhost:8083 but when running the tasks it's unable to find the images. 
 
 The current config as in the docker-compose.yml runs upto executing the ECS task. This same setup runs fine in the AWS but not in the localstack as below. 
 
 

```
INFO --- [   asgi_gw_2] l.request.internal.aws     : AWS cloudwatch.PutMetricData => 200
 DEBUG --- [   asgi_gw_0] l.aws.serving.wsgi         : POST localhost:4566/
 DEBUG --- [  Thread-481] l.u.c.docker_sdk_client    : Starting container 547ae6c735171b581d81ec0f83d060d0f2998b52460bad35e9afce9346e55f27
 2023-01-24T09:39:46.157 DEBUG --- [  Thread-481] l.u.c.docker_sdk_client    : Removing container: 547ae6c735171b581d81ec0f83d060d0f2998b52460bad35e9afce9346e55f27
 2023-01-24T09:39:46.187 ERROR --- [  Thread-481] l.services.ecs.provider    : Execution of ECS task arn:aws:ecs:us-east-1:000000000000:task/<omitted-taskname>/f7756d5b-3fbd-4443-aa7d-5b862559e53d failed: Docker container returned with exit code 1 - Output: 
 Traceback (most recent call last):
   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/ecs/provider.py.enc", line 170, in D
   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 615, in run_container
     result = self.start_container(
   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 473, in start_container
     raise ContainerException(
 localstack.utils.container_utils.container_client.ContainerException: Docker container returned with exit code 1`
 
 and the error when executing the ECS task:
`StartExecution => {"requestClientOptions":{"readLimit":131073,"skipAppendUriPath":false},"requestMetricCollector":null,"customRequestHeaders":null,"customQueryParameters":null,"cloneSource":null,"sdkRequestTimeout":null,"sdkClientExecutionTimeout":null,"stateMachineArn":"arn:aws:states:us-east-1:000000000000:stateMachine:<omitted-here>","name":null,"input":"{\"bucket\": \"<omitted-here>\", \"s3_keys\": [\"<omitted-here>.parquet\"]}","traceHeader":null,"requestCredentials":null,"cloneRoot":null,"requestCredentialsProvider":null,"generalProgressListener":{"syncCallSafe":true},"readLimit":131073}
 [AppClassLoader@7960847b] weaveinfo Join point 'method-execution(com.amazonaws.stepfunctions.local.runtime.executors.StateExecutor com.amazonaws.stepfunctions.local.runtime.executors.task.TaskStateExecutor.createExecutor(com.amazonaws.swf.auth.arn.ARN))' in Type 'com.amazonaws.stepfunctions.local.runtime.executors.task.TaskStateExecutor' (TaskStateExecutor.java:59) advised by around advice from 'cloud.localstack.RegionAspect' (RegionAspect.java)
 com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Class is not registered: java.util.ArrayList
 Note: To register this class use: kryo.register(java.util.ArrayList.class);
 Serialization trace:
 destinations (com.amazonaws.services.stepfunctions.model.LoggingConfiguration)
 loggingConfiguration (com.amazonaws.stepfunctions.local.model.StateMachineModel)
 stateMachineModel (com.amazonaws.stepfunctions.local.model.ExecutionModel)
 executions (cloud.localstack.PersistenceRegionState)
 state (cloud.localstack.PersistenceState)
 at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:101)
 at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:108)
 at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:642)
 at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
 at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:108)
 at com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Kryo.java:692)
 at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:79)
 at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:108)
 at com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Kryo.java:692)
 at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:158)
 at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
 at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:642)
 at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
 at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:108)
 at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:711)
 at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
 at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
 at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:642)
 at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
 at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:108)
 at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:627)
 at cloud.localstack.PersistenceContext.writeState(PersistenceContext.java:170)
 at cloud.localstack.PersistenceAspect.afterCreateExecution(PersistenceAspect.java:53)
 at com.amazonaws.stepfunctions.local.repo.ExecutionRepo.createExecution(ExecutionRepo.java:53)
 at com.amazonaws.stepfunctions.local.operation.StartExecution.handle(StartExecution.java:90)
 at com.amazonaws.stepfunctions.local.operation.StartExecution.handle(StartExecution.java:25)
 at com.amazonaws.stepfunctions.local.http.HttpRequestHandlers.handle_aroundBody0(HttpRequestHandlers.java:67)
 at com.amazonaws.stepfunctions.local.http.HttpRequestHandlers$AjcClosure1.run(HttpRequestHandlers.java:1)
 at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
 at cloud.localstack.RegionAspect.aroundHttpHandle(RegionAspect.java:75)
 at com.amazonaws.stepfunctions.local.http.HttpRequestHandlers.handle(HttpRequestHandlers.java:43)
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
 at org.eclipse.jetty.server.Server.handle(Server.java:505)
 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
 at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
 at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
 at java.base/java.lang.Thread.run(Unknown Source)
 Caused by: java.lang.IllegalArgumentException: Class is not registered: java.util.ArrayList
 Note: To register this class use: kryo.register(java.util.ArrayList.class);
 at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:579)
 at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:112)
 at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:613)
 at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:67)
 ... 40 more
```

### Expected Behavior

Expected to complete the ECS task and move on with statemachine execution. 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
# docker-compose.yaml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-pro  # required for Pro
    privileged: true
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      - SERVICES=iam,kms,secretsmanager,ssm,sts,s3,lambda,ecs,ecr,ec2,sns,sqs,stepfunctions,xray,cloudwatch,cloudwatchlogs
      - STEP_FUNCTIONS_ENDPOINT=http://localhost:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ACCOUNT_ID=000000000000
      - DEFAULT_REGION=us-east-1  
      #- DEBUG=${DEBUG-1}
      - LS_LOG=trace #trace, trace-internal, debug, info, warn, error, warning. Ignores DEBUG= 
      - LAMBDA_DOCKER_NETWORK=localstack_nw #network for lambda/ecs container
      - LAMBDA_DOCKER_FLAGS=-v /mnt/c/Users/<username>/localstack:/var/log -e network=localstack_nw -e STEP_FUNCTIONS_ENDPOINT=http://localhost:4566              
      - DOCKER_FLAGS=--privileged=true --volumes-from=localstack_main --network=localstack_nw --step-functions-endpoint=http://localhost:4566
      - PERSISTENCE=${PERSISTENCE-1} # keep the state of previous run 
      - LOCALSTACK_API_KEY=xxxxx
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
            - localstack_nw

networks:
    localstack_nw:
      name: localstack_nw
      external: true
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    using terraform to build the resources

### Environment

```markdown
- OS: Windows 10
- LocalStack:1.3.2.dev (2023-01-23)
```

### Anything else?

 Also seeing this error when terraforming the resources:
 
 ```
DEBUG --- [   asgi_gw_6] l.aws.serving.wsgi         : POST localhost:4566/2015-03-31/functions
  DEBUG --- [  asgi_gw_10] l.aws.serving.wsgi         : POST localhost:4566/
  DEBUG --- [uncthread777] localstack.utils.run       : Executing command: ['unzip', '-o', '-q', '/var/lib/localstack/tmp/function.zipfile.62f4620f/original_lambda_archive.zip']
 com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Class is not registered: java.util.ArrayList
 Note: To register this class use: kryo.register(java.util.ArrayList.class);
 Serialization trace:
 destinations (com.amazonaws.services.stepfunctions.model.LoggingConfiguration)
 loggingConfiguration (com.amazonaws.stepfunctions.local.model.StateMachineModel)
 stateMachines (cloud.localstack.PersistenceRegionState)
 state (cloud.localstack.PersistenceState)
 at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:101)
 at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:108)
 at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:642)
 at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
 at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:108)
 at com.esotericsoftware.kryo.Kryo.writeObjectOrNull(Kryo.java:692)
 at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:158)
 at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
 at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:642)
 at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
 at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:108)
 at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:711)
 at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:162)
 at com.esotericsoftware.kryo.serializers.MapSerializer.write(MapSerializer.java:42)
 at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:642)
 at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:70)
 at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:108)
 at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:627)
 at cloud.localstack.PersistenceContext.writeState(PersistenceContext.java:170)
 at cloud.localstack.PersistenceAspect.afterCreateStateMachine(PersistenceAspect.java:38)
 at com.amazonaws.stepfunctions.local.repo.StateMachineRepo.createStateMachine(StateMachineRepo.java:29)
 at com.amazonaws.stepfunctions.local.operation.CreateStateMachine.handle(CreateStateMachine.java:70)
 at com.amazonaws.stepfunctions.local.operation.CreateStateMachine.handle(CreateStateMachine.java:21)
 at com.amazonaws.stepfunctions.local.http.HttpRequestHandlers.handle_aroundBody0(HttpRequestHandlers.java:67)
 at com.amazonaws.stepfunctions.local.http.HttpRequestHandlers$AjcClosure1.run(HttpRequestHandlers.java:1)
 at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:167)
 at cloud.localstack.RegionAspect.aroundHttpHandle(RegionAspect.java:75)
 at com.amazonaws.stepfunctions.local.http.HttpRequestHandlers.handle(HttpRequestHandlers.java:43)
 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
 at org.eclipse.jetty.server.Server.handle(Server.java:505)
 at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
 at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
 at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
 at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
 at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
 at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
 at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
 at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
 at java.base/java.lang.Thread.run(Unknown Source)
 Caused by: java.lang.IllegalArgumentException: Class is not registered: java.util.ArrayList
 Note: To register this class use: kryo.register(java.util.ArrayList.class);
 at com.esotericsoftware.kryo.Kryo.getRegistration(Kryo.java:579)
 at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:112)
 at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:613)
 at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:67)
 ... 41 more
```

**Comment by devitt94** [comment]
Having the same issue using `localstack/localstack:latest` on macOS 12.3

**Comment by whummer** [comment]
Thanks for reporting @Hardeep-Dhillon-Nowp @devitt94 . Looks like this could be related to the persistence feature for StepFunctions. Can you please give it a try with persistence disabled, i.e., `PERSISTENCE=0`? We'll look into this issue in more detail shortly.. Thanks
