### ISSUE TITLE
S3 large file download issue resulting into InvalidRange error in GetObject operation: The requested range is not satisfiable

### ISSUE THREAD

**Issue by tejas03** [localstack/localstack#7585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is issue still happening for larger files as of 1/27/23. I am using boto3==1.21.35

[2023-01-10, 17:25:29 EST] "message": "multiprocessing.pool.RemoteTraceback: \n"""\nTraceback (most recent call last):\n File "/usr/lib64/python3.7/multiprocessing/pool.py", line 121, in worker\n result = (True, func(*args, **kwds))\n File "/usr/lib64/python3.7/multiprocessing/pool.py", line 47, in starmapstar\n return list(itertools.starmap(args[0], args[1]))\n File "fpcp_file_manager.py", line 655, in func_download_s3_files\n s3.download_file(awsbucket, key, dest_filename)\n File "/usr/local/lib/python3.7/site-packages/boto3/s3/inject.py", line 195, in download_file\n callback=Callback,\n File "/usr/local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 320, in download_file\n future.result()\n File "/usr/local/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result\n return self._coordinator.result()\n File "/usr/local/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result\n raise self._exception\n File "/usr/local/lib/python3.7/site-packages/s3transfer/tasks.py", line 139, in call\n return self._execute_main(kwargs)\n File "/usr/local/lib/python3.7/site-packages/s3transfer/tasks.py", line 162, in _execute_main\n return_value = self._main(kwargs)\n File "/usr/local/lib/python3.7/site-packages/s3transfer/download.py", line 570, in _main\n Bucket=bucket, Key=key, extra_args\n File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 415, in _api_call\n return self._make_api_call(operation_name, kwargs)\n File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 745, in _make_api_call\n raise error_class(parsed_response, operation_name)\nbotocore.exceptions.ClientError: An error occurred (InvalidRange) when calling the GetObject operation: The requested range is not satisfiable\n"""\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n File "fpcp_file_manager.py", line 1287, in \n main()\n File "fpcp_file_manager.py", line 1238, in main\n if download_s3_files == True: exec_download_s3_files()\n File "fpcp_file_manager.py", line 1088, in exec_download_s3_files\n pool.starmap(func_download_s3_files, zip(keys, repeat(download_destpath)), chunksize=10)\n File "/usr/lib64/python3.7/multiprocessing/pool.py", line 276, in starmap\n return self._map_async(func, iterable, starmapstar, chunksize).get()\n File "/usr/lib64/python3.7/multiprocessing/pool.py", line 657, in get\n raise self._value\nbotocore.exceptions.ClientError: An error occurred (InvalidRange) when calling the GetObject operation: The requested range is not satisfiable\n",

Another issue is while deleting the larger file. However for delete-file it is not throwing any error. It simply skip the file from deleting as below. First and last one were deleted. middle one was not deleted which is causing duplication issue in processing.

{'DeleteMarker': True,
'ResponseMetadata': {'HTTPHeaders': {'date': 'Tue, 17 Jan 2023 02:24:42 GMT',
'server': 'AmazonS3',
'x-amz-delete-marker': 'true',
'x-amz-id-2': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
'x-amz-request-id': 'ABCDEFG0123456',
'x-amz-version-id': 'zzzzzzzzzzzzzzzzzzzzzzzz'},
'HTTPStatusCode': 204,
'HostId': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
'RequestId': 'ABCDEFG0123456',
'RetryAttempts': 0},
'VersionId': 'zzzzzzzzzzzzzzzzzzzzzzzz'}
files to delete - abcxyz/test1.dat.gz
{'DeleteMarker': True,
'ResponseMetadata': {'HTTPHeaders': {'date': 'Tue, 17 Jan 2023 02:24:42 GMT',
'server': 'AmazonS3',
'x-amz-delete-marker': 'true',
'x-amz-id-2': 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
'x-amz-request-id': '0987654ABCDE',
'x-amz-version-id': 'xxxxxxxxxxxxxxxxxxyyyyyyyyyyyyyyyy'files to delete - abcxyz/test2.dat.gz
{'DeleteMarker': True,
'ResponseMetadata': {'HTTPHeaders': {'date': 'Tue, 17 Jan 2023 02:24:42 GMT',
'server': 'AmazonS3',
'x-amz-delete-marker': 'true',
'x-amz-id-2': 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
'x-amz-request-id': 'ABC123XYZ789',
'x-amz-version-id': 'yyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzzzz'},
'HTTPStatusCode': 204,
'HostId': 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
'RequestId': 'ABC123XYZ789',
'RetryAttempts': 0},
'VersionId': 'yyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzzzz'}
files to delete - abcxyz/test3.dat.gz

Can you please reopen this ticket and provide an assistance? Please let me know if you need further information. Thanks.

### Expected Behavior

Download and delete the expected file successfully from S3 without any error.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

running python boto3 commands using bash script

### Environment

```markdown
- OS: amazon Linux
- LocalStack: latest
```

### Anything else?

both download and delete are not working while working on with one of the largest files.

**Comment by tejas03** [comment]
Hi,  yes, I am referring to a closed issue.
Incorrect response code when Downloading S3 object with invalid range #2587

As I have highlighted, I am getting invalidRange error while trying to download large file from S3. "**raise self._value\nbotocore.exceptions.ClientError: An error occurred (InvalidRange) when calling the GetObject operation: The requested range is not satisfiable**". 

This is happening in production environment for one of the largest clients. I can not provide the reproducible data though since data is proprietary. Also I cant enable DEBUG mode or tracing on since its production. Files are usually more than few megabytes and the snippet of the code which I am using is as below. Thanks for your help and please let me know if you have further questions.

aws_session = boto3.session.Session(region_name = awsregion)
s3 = aws_session.client('s3')

def func_download_s3_files(key, download_destpath):
	"""
	params:
	- key: s3 key object to be downloaded
	- download_destpath: local path to folder where files to be downloaded into
	"""
	dest_filename = "{}/{}".format(download_destpath, basename(key))
	try:
		s3.download_file(awsbucket, key, dest_filename)
	except ClientError as e:
		if e.response['Error']['Code'] == "404":
			print("ERROR :: {} file does not exist in s3 for downloading".format(key))
			return False
		else:
			raise
	return True

def exec_download_s3_files():
	"""
	params:
	"""
	print("download_s3_files flag is true..")
.....
	keys = exec_list_s3_objects(s3_path, processed_sofar_list, 'download')
	
	if len(keys) > 0:
		print(str(keys))
		
		with multiprocessing.Pool() as pool:
			pool.starmap(func_download_s3_files, zip(keys, repeat(download_destpath)), chunksize=10)

#"""--Main--"""
def main():
....
	#"""--download pgp files from s3--"""
	if download_s3_files == True: exec_download_s3_files()
....

#"""--Execute Main--"""
if __name__ == "__main__":
	main()

**Comment by bentsku** [comment]
But is your error happening while targeting AWS S3? It seems from your logs that this issue is happening against AWS, from your headers: `server': 'AmazonS3'`

Which version of LocalStack are you using?

**Comment by bentsku** [comment]
Okay, sorry for the miscommunication here. I am afraid we won't be able to help, as it seems to be an issue either with AWS or `boto`. You might be able to find more help there. I'll close this issue. 

However, quickly looking at the sample code, it seems you're creating your S3 client once, and then using it in every process spawned by `multiprocessing.Pool()`. Your issue sounds a bit like a race condition, maybe you could try creating the S3 client inside `func_download_s3_files` so that your each of your process would use its own client, thus avoiding some shared resources? I'm not guaranteeing this is the issue, but it could help.

**Comment by tejas03** [comment]
agreed to your suggestion however S3 client is sharable I believe, isn't it? I am seeing the same usage of client in the boto3 coding around the community. Also this works fine with smaller files. it runs into an issue only with larger files.

https://www.learnaws.org/2022/10/12/boto3-download-multiple-files-s3/
https://emasquil.github.io/posts/multithreading-boto3/

**Comment by bentsku** [comment]
In the first link you've shared, they share only for multithreading, when using multiprocessing they create the client inside the function.

**Comment by tejas03** [comment]
Glad that you noticed it. So, to mention I have tried that both as below. Initially, I was using apply_asyc itself and then switched to starmap. it also failed with starmap_async.

		with multiprocessing.Pool() as pool: # *** doesnt work with starmap_async
			pool.starmap(func_download_s3_files, zip(keys, repeat(download_destpath)), chunksize=10)
		
		#download_pool = multiprocessing.Pool()
		#for k in keys:
		#	download_pool.apply_async(func_download_s3_files, args=(k, download_destpath), error_callback=error_on_apply_async)
		#download_pool.close()
		#download_pool.join()
