### ISSUE TITLE
bug: Failed to start standalone pulsar on Apple M1 Pro

### ISSUE THREAD

**Issue by imhamzaazam** [localstack/localstack#7591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I followed the document on my local machine, using pulsar version 2.11.0:

My macbook information: 
```
CHIP: M1 Pro
System Version: macOS 12.3 (21E230)
Kernel Version: Darwin 21.4.0
```

```
https://pulsar.apache.org/docs/2.11.x/getting-started-standalone/
```

but got an error:
```
2023-02-01T17:23:10,851+0500 [main] WARN  io.netty.resolver.dns.DnsServerAddressStreamProviders - Can not find io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'
2023-02-01T17:23:12,932+0500 [main] ERROR org.apache.pulsar.functions.worker.PulsarWorkerService - Error Starting up in worker
java.lang.ExceptionInInitializerError: null
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parseSilently(UnixResolverDnsServerAddressStreamProvider.java:80) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder$1.provider(DnsServerAddressStreamProviders.java:151) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder$1.<init>(DnsServerAddressStreamProviders.java:130) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder.<clinit>(DnsServerAddressStreamProviders.java:128) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.unixDefault(DnsServerAddressStreamProviders.java:117) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.platformDefault(DnsServerAddressStreamProviders.java:113) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsNameResolverBuilder.<init>(DnsNameResolverBuilder.java:60) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at org.apache.pulsar.client.impl.ConnectionPool.createAddressResolver(ConnectionPool.java:152) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ConnectionPool.lambda$new$1(ConnectionPool.java:126) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:126) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:95) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:90) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:198) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:154) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:63) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.functions.worker.WorkerUtils.getPulsarClient(WorkerUtils.java:327) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.functions.worker.PulsarWorkerService$1.newPulsarClient(PulsarWorkerService.java:165) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.functions.worker.PulsarWorkerService.start(PulsarWorkerService.java:443) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.broker.PulsarService.startWorkerService(PulsarService.java:1721) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:872) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:348) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:141) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
Caused by: java.lang.IllegalArgumentException: cannot use an unresolved DNS server address: [fe80::1%en0]/<unresolved>:53
	at io.netty.resolver.dns.DnsServerAddresses.sanitize(DnsServerAddresses.java:175) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddresses.sequential(DnsServerAddresses.java:67) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.<clinit>(DefaultDnsServerAddressStreamProvider.java:107) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	... 23 more
2023-02-01T17:23:12,941+0500 [main] ERROR org.apache.pulsar.broker.PulsarService - Failed to start Pulsar service: java.lang.ExceptionInInitializerError
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
	at org.apache.pulsar.functions.worker.PulsarWorkerService.start(PulsarWorkerService.java:589) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.broker.PulsarService.startWorkerService(PulsarService.java:1721) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:872) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:348) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:141) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
Caused by: java.lang.ExceptionInInitializerError
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parseSilently(UnixResolverDnsServerAddressStreamProvider.java:80) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder$1.provider(DnsServerAddressStreamProviders.java:151) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder$1.<init>(DnsServerAddressStreamProviders.java:130) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder.<clinit>(DnsServerAddressStreamProviders.java:128) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.unixDefault(DnsServerAddressStreamProviders.java:117) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.platformDefault(DnsServerAddressStreamProviders.java:113) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsNameResolverBuilder.<init>(DnsNameResolverBuilder.java:60) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at org.apache.pulsar.client.impl.ConnectionPool.createAddressResolver(ConnectionPool.java:152) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ConnectionPool.lambda$new$1(ConnectionPool.java:126) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:126) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:95) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:90) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:198) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:154) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:63) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.functions.worker.WorkerUtils.getPulsarClient(WorkerUtils.java:327) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.functions.worker.PulsarWorkerService$1.newPulsarClient(PulsarWorkerService.java:165) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.functions.worker.PulsarWorkerService.start(PulsarWorkerService.java:443) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	... 4 more
Caused by: java.lang.IllegalArgumentException: cannot use an unresolved DNS server address: [fe80::1%en0]/<unresolved>:53
	at io.netty.resolver.dns.DnsServerAddresses.sanitize(DnsServerAddresses.java:175) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddresses.sequential(DnsServerAddresses.java:67) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.<clinit>(DefaultDnsServerAddressStreamProvider.java:107) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parseSilently(UnixResolverDnsServerAddressStreamProvider.java:80) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder$1.provider(DnsServerAddressStreamProviders.java:151) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder$1.<init>(DnsServerAddressStreamProviders.java:130) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder.<clinit>(DnsServerAddressStreamProviders.java:128) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.unixDefault(DnsServerAddressStreamProviders.java:117) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.platformDefault(DnsServerAddressStreamProviders.java:113) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsNameResolverBuilder.<init>(DnsNameResolverBuilder.java:60) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at org.apache.pulsar.client.impl.ConnectionPool.createAddressResolver(ConnectionPool.java:152) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ConnectionPool.lambda$new$1(ConnectionPool.java:126) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:126) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:95) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:90) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:198) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:154) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:63) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.functions.worker.WorkerUtils.getPulsarClient(WorkerUtils.java:327) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.functions.worker.PulsarWorkerService$1.newPulsarClient(PulsarWorkerService.java:165) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.functions.worker.PulsarWorkerService.start(PulsarWorkerService.java:443) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	... 4 more
2023-02-01T17:23:12,942+0500 [main] ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.
org.apache.pulsar.broker.PulsarServerException: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:910) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:348) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:141) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
Caused by: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
	at org.apache.pulsar.functions.worker.PulsarWorkerService.start(PulsarWorkerService.java:589) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.broker.PulsarService.startWorkerService(PulsarService.java:1721) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:872) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
	... 2 more
Caused by: java.lang.ExceptionInInitializerError
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parseSilently(UnixResolverDnsServerAddressStreamProvider.java:80) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder$1.provider(DnsServerAddressStreamProviders.java:151) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder$1.<init>(DnsServerAddressStreamProviders.java:130) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder.<clinit>(DnsServerAddressStreamProviders.java:128) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.unixDefault(DnsServerAddressStreamProviders.java:117) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.platformDefault(DnsServerAddressStreamProviders.java:113) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsNameResolverBuilder.<init>(DnsNameResolverBuilder.java:60) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at org.apache.pulsar.client.impl.ConnectionPool.createAddressResolver(ConnectionPool.java:152) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ConnectionPool.lambda$new$1(ConnectionPool.java:126) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:126) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:95) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:90) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:198) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:154) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:63) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.functions.worker.WorkerUtils.getPulsarClient(WorkerUtils.java:327) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.functions.worker.PulsarWorkerService$1.newPulsarClient(PulsarWorkerService.java:165) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.functions.worker.PulsarWorkerService.start(PulsarWorkerService.java:443) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.broker.PulsarService.startWorkerService(PulsarService.java:1721) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:872) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
	... 2 more
Caused by: java.lang.IllegalArgumentException: cannot use an unresolved DNS server address: [fe80::1%en0]/<unresolved>:53
	at io.netty.resolver.dns.DnsServerAddresses.sanitize(DnsServerAddresses.java:175) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddresses.sequential(DnsServerAddresses.java:67) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.<clinit>(DefaultDnsServerAddressStreamProvider.java:107) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parseSilently(UnixResolverDnsServerAddressStreamProvider.java:80) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder$1.provider(DnsServerAddressStreamProviders.java:151) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder$1.<init>(DnsServerAddressStreamProviders.java:130) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder.<clinit>(DnsServerAddressStreamProviders.java:128) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.unixDefault(DnsServerAddressStreamProviders.java:117) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.platformDefault(DnsServerAddressStreamProviders.java:113) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.resolver.dns.DnsNameResolverBuilder.<init>(DnsNameResolverBuilder.java:60) ~[io.netty-netty-resolver-dns-4.1.86.Final.jar:4.1.86.Final]
	at org.apache.pulsar.client.impl.ConnectionPool.createAddressResolver(ConnectionPool.java:152) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ConnectionPool.lambda$new$1(ConnectionPool.java:126) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:126) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:95) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ConnectionPool.<init>(ConnectionPool.java:90) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:198) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.PulsarClientImpl.<init>(PulsarClientImpl.java:154) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.client.impl.ClientBuilderImpl.build(ClientBuilderImpl.java:63) ~[org.apache.pulsar-pulsar-client-original-2.11.0.jar:2.11.0]
	at org.apache.pulsar.functions.worker.WorkerUtils.getPulsarClient(WorkerUtils.java:327) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.functions.worker.PulsarWorkerService$1.newPulsarClient(PulsarWorkerService.java:165) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.functions.worker.PulsarWorkerService.start(PulsarWorkerService.java:443) ~[org.apache.pulsar-pulsar-functions-worker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.broker.PulsarService.startWorkerService(PulsarService.java:1721) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:872) ~[org.apache.pulsar-pulsar-broker-2.11.0.jar:2.11.0]
	... 2 more
2023-02-01T17:23:13,054+0500 [Thread-0] INFO  org.apache.pulsar.common.util.GracefulExecutorServicesTerminationHandler - Starting termination handler for 1 executors.



### Expected Behavior

_No response_

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

#### How are you starting Pulsar standalone cluster

    bin/pulsar standalone


### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by whummer** [comment]
Hi @imhamzaazam , thanks for reporting. Can you please share some details about your use case, how do you envision Pulsar to be integrated with LocalStack? From the docs, it seems that Pulsar is mostly a self-contained platform that does not have strong dependencies to AWS. 

Since LocalStack is a cloud emulator that emulates the AWS cloud APIs on your local machine, it would be interesting to understand a bit better what the exact setup is you're trying to achieve. Please elaborate, so we can provide better guidance. Thanks!
