### ISSUE TITLE
aws ec2 describe-account-attributes breaks pod save

### ISSUE THREAD

**Issue by mpatnode** [localstack/localstack#7608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

localstack pod save file://$(pwd)/test fails with a S3 pickle exception after running "ec2 describe-account-attributes"

Full stack trace
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/localstack", line 23, in <module>
    main()
  File "/opt/homebrew/bin/localstack", line 19, in main
    main.main()
  File "/opt/homebrew/Cellar/localstack/1.3.1/libexec/lib/python3.11/site-packages/localstack/cli/main.py", line 11, in main
    cli()
  File "/opt/homebrew/Cellar/localstack/1.3.1/libexec/lib/python3.11/site-packages/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/opt/homebrew/Cellar/localstack/1.3.1/libexec/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/1.3.1/libexec/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/1.3.1/libexec/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/1.3.1/libexec/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/1.3.1/libexec/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/1.3.1/libexec/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/1.3.1/libexec/lib/python3.11/site-packages/localstack/utils/analytics/cli.py", line 66, in publisher_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/1.3.1/libexec/lib/python3.11/site-packages/localstack_ext/cli/cloud_pods.py", line 67, in cmd_pod_save
    F=url or A;B=E.export_pod(target=F)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/1.3.1/libexec/lib/python3.11/site-packages/localstack_ext/bootstrap/pods_client.py", line 264, in export_pod
    D=get_state_zip_from_instance(get_content=_B);A=urlparse(target);B=os.path.abspath(os.path.join(A.netloc,A.path));C=Path(B).parent.absolute()
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/1.3.1/libexec/lib/python3.11/site-packages/localstack_ext/bootstrap/pods_client.py", line 45, in get_state_zip_from_instance
    if A.status_code>=400:raise Exception(f"Unable to get local pod state via management API {C} (code {A.status_code}): {A.content}")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: Unable to get local pod state via management API http://localhost:4566/_pods/state (code 500): b"<?xml version='1.0' encoding='utf-8'?>\n<Error><Code>InternalError</Code><Message>exception while calling s3 with unknown operation: cannot pickle 'generator' object</Message><RequestId>12HM326C2KB4FROLZCHFD8KYWTF4616GC3XD8HGZYZ4QQ8ANUEHZ</RequestId></Error>"
```

### Expected Behavior

The pod save command should succeed.  The "ec2 describe-account-attributes" command should not create ec2/s3 artifacts that affect pod save.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
localstack start -d
localstack pod save file://$(pwd)/test # happy
aws ec2 describe-account-attributes --region us-east-1 --endpoint http://localhost:4566/ > /dev/null
localstack pod save file://$(pwd)/test # sad
```

### Environment

```markdown
- OS: Mac Ventura 13.1
- LocalStack:1.3.1
```

### Anything else?

Note the trivial example was reduced from a much more complicated Terragrunt run.   The Terragrunt AWS driver makes the describe-account-attributes call which is a perfectly reasonable query for it to make to gather information.

**Comment by giograno** [comment]
Hi @mpatnode, thanks for reporting this issue. We released a fix. Please download the `latest` Docker image and give it a try. Please let us know if you are experiencing any other issues with Cloud Pods 🙏
