### ISSUE TITLE
Localstack pod load timing out

### ISSUE THREAD

**Issue by Travis-Kirton** [localstack/localstack#7673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running localstack using Terraform (with tflocal) to deploy multiple lambdas, sqs, sns & API Gateway. I can apply all the resources with no issues and my application is running as expected. 

I wanted to load/save the localstack state so I don't have to keep re-creating as it takes a long time. I can run the following command to save state with no issue: 
```
localstack pod save file://$HOME/localstack/my-file-name
```

however when restarting localstack and attempting to run `localstack pod load file://$HOME/localstack/my-file-name`

I seem to get a timeout of sorts. Some resources are created, not all and it isn't consistent. (stacktrace):

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/<myname>/Library/Python/3.9/lib/python/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=4566): Read timed out. (read timeout=7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/localstack", line 23, in <module>
    main()
  File "/usr/local/bin/localstack", line 19, in main
    main.main()
  File "/usr/local/lib/python3.9/site-packages/localstack/cli/main.py", line 11, in main
    cli()
  File "/usr/local/lib/python3.9/site-packages/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/localstack/utils/analytics/cli.py", line 66, in publisher_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/localstack_ext/cli/cloud_pods.py", line 94, in cmd_pod_load
    if B or G:H=B or A;C=E.import_pod(source=H,merge_strategy=D);F(C);return C
  File "/usr/local/lib/python3.9/site-packages/localstack_ext/bootstrap/pods_client.py", line 267, in import_pod
    def import_pod(source,merge_strategy):A=source;B=get_protocol_access(A);C=B(A);return inject_pod_endpoint(content=C,merge_strategy=merge_strategy)
  File "/usr/local/lib/python3.9/site-packages/localstack_ext/bootstrap/pods_client.py", line 268, in inject_pod_endpoint
    def inject_pod_endpoint(content,pod_name='community_pod',pod_version=1,merge_strategy=DEFAULT_MERGE_STRATEGY):A=get_pods_endpoint();B={_D:pod_name,_G:str(pod_version),_H:merge_strategy};C=requests.post(A,data=content,params=B,timeout=POD_INJECT_CLI_TIMEOUT);return C.ok
  File "/Users/<myname>/Library/Python/3.9/lib/python/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/<myname>/Library/Python/3.9/lib/python/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/<myname>/Library/Python/3.9/lib/python/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/<myname>/Library/Python/3.9/lib/python/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/<myname>/Library/Python/3.9/lib/python/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=4566): Read timed out. (read timeout=7)
```

I am running the latest localstack image & localstack cli version: 1.3.1

For the lambdas, 2 are nodejs and using zipped files as the source, the 3rd lambda is Java based using a built jar if that helps at all.

### Expected Behavior

I should be able to load state without issue.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

My compose file:
```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_FLAGS=-v /Users/<user>/localstack/vault/:/tmp/vault/
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### Environment

```markdown
- OS: MacOS Ventura 13.2
- LocalStack: Image (latest), CLI 1.3.1
```

**Comment by Travis-Kirton** [comment]
I have updated my localstack CLI to 1.4.0 and the error now suggests increasing the POD_LOAD_CLI_TIMEOUT which I have done. Functions are brought back but in a pending state.
