### ISSUE TITLE
KeyError: 'AWS::URLSuffix' when attempting to deploy lambda function

### ISSUE THREAD

**Issue by ghost** [localstack/localstack#770]
Update the moto library to address issue with `KeyError: 'AWS::URLSuffix'`.

Related Ticket: https://github.com/spulec/moto/issues/1649

In investigating why I couldn't deploy a lambda function to localstack, I managed to find my way back to the moto library. When attempting to deploy certain applications, I found the serverless would hang due to an error. After enabling DEBUG on localstack, I saw this stack trace come from the moto library:

```
127.0.0.1 - - [18/May/2018 17:12:02] "POST / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
execute(self.server.app)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
application_iter = app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 93, in __call__
return backend_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 139, in __call__
result = self.callback(request, request.url, {})
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 116, in dispatch
return cls()._dispatch(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 199, in _dispatch
return self.call_action()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 273, in call_action
response = method()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/responses.py", line 262, in update_stack
tags=tags,
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/models.py", line 241, in update_stack
stack.update(template, role_arn, parameters=parameters, tags=tags)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/models.py", line 112, in update
self.output_map = self._create_output_map()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/models.py", line 55, in _create_output_map
output_map.create()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 561, in create
self[output]
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 534, in __getitem__
output_logical_id, output_json, self._resource_map)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 342, in parse_output
output_json = clean_json(output_json, resources_map)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 220, in clean_json
cleaned_val = clean_json(value, resources_map)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 173, in clean_json
join_list = clean_json(resource_json['Fn::Join'][1], resources_map)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 227, in clean_json
return [clean_json(val, resources_map) for val in resource_json]
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 136, in clean_json
resource = resources_map[resource_json['Ref']]
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 383, in __getitem__
raise KeyError(resource_logical_id)
KeyError: 'AWS::URLSuffix'
```

This library hardcodes a map in it's constructor, but does not include an AWS::URLSuffix value. Once the linked issue is resolved, please update the library version.

**Comment by filipelenfers** [comment]
Same problem here.

**Comment by whummer** [comment]
Thanks for reporting @filipelenfers @ghost. Should be fixed in the meantime - please re-open this issue if the problem persists. Thanks
