### ISSUE TITLE
bug: [PRO] Long DBClusterIdentifier for AWS::RDS::DBCluster with MySQL engine in Cloudformation stack causes cluster creation error

### ISSUE THREAD

**Issue by hrishi-hugo** [localstack/localstack#7703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have the following Cloudformation step in which we create a AuroraV2 cluster and a AuroraV2DBInstance.
But when the DBClusterIdentifier is long (I am not able to determine what the limit is), but when we have a long DBClusterIdentifier property (Ex: examplestackhscmn-account-cluster) it causes a cluster creation error with the following stack trace. When I put a short value for DBClusterIdentifier, the stack creates without any issue.

CF snippet: 

```
AuroraV2Cluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Delete
    Properties:
      DatabaseName: hs
      DBClusterIdentifier: examplestackhscmn-account-cluster
      EnableCloudwatchLogsExports:
        - error
        - audit
        - slowquery
      EnableIAMDatabaseAuthentication: true
      Engine: aurora-mysql
      KmsKeyId:
        Ref: AuroraDbKmsKey
      MasterUsername: user
      MasterUserPassword: password
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5
        MaxCapacity: 1
      StorageEncrypted: true
      VpcSecurityGroupIds:
        - Fn::Sub: ${SG}
  AuroraV2DBInstance:
    Type: AWS::RDS::DBInstance
    DependsOn:
      - AuroraV2Cluster
    Properties:
      DBClusterIdentifier: examplestackhscmn-account-cluster
      DBInstanceClass: db.serverless
      Engine: aurora-mysql
      PubliclyAccessible: true
```

Stack Trace:

```2023-02-16T17:03:11.510 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:03:14.620 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:03:17.751 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:03:20.865 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:03:23.970 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:03:24.156  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS rds.DescribeDBClusters => 200
2023-02-16T17:03:27.059 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:03:30.172 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:03:33.290 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:03:36.383 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:03:39.508 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:03:42.623 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:03:45.751 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:03:48.860 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:03:51.975 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:03:55.091 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:03:58.204 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:04:01.341 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:04:04.485 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:04:07.564 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:04:10.676 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:04:13.792 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:04:16.925 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:04:20.047 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:04:23.159 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:04:26.260 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:04:29.367 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:04:32.546 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:04:35.681 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:04:38.789 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]
2023-02-16T17:04:41.914  WARN --- [uncthread111] l.services.rds.db_utils    : Unable to startup DB instance: ('Exec command returned with exit code 1', None, b"mysql: [Warning] Using a password on the command line interface can be insecure.\nERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)\n") Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/rds/db_utils.py.enc", line 50, in B
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/rds/engine_mysql.py.enc", line 30, in start_db_instance
  File "/opt/code/localstack/localstack/utils/sync.py", line 65, in retry
    raise raise_error
  File "/opt/code/localstack/localstack/utils/sync.py", line 61, in retry
    return function(**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/rds/engine_mysql.py.enc", line 29, in R
  File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 684, in exec_in_container
    raise ContainerException(
localstack.utils.container_utils.container_client.ContainerException: ('Exec command returned with exit code 1', None, b"mysql: [Warning] Using a password on the command line interface can be insecure.\nERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)\n")
 stdout: 'None' stderr: 'mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

This command seems to fail as it appears so many times and then raises the error.
```2023-02-16T17:03:27.059 DEBUG --- [uncthread111] l.u.c.docker_sdk_client    : Executing command in container ls-mysql-1f15ccdb: ['bash', '-c', "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"]```

But when I give a shorter value for DBClusterIdentifier this command only appears for 2 times and the cluster creates successfully.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Run Localstack with following command:
docker run \                  
  --rm -it \
  -p 4566:4566 \
  -p 4510-4559:4510-4559 \
  -e LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY:- } \
  -e DEBUG=${DEBUG:- } \
  -e RDS_MYSQL_DOCKER=${RDS_MYSQL_DOCKER:- } \
  -e MYSQL_IMAGE=${MYSQL_IMAGE:- } \
  -v /var/run/docker.sock:/var/run/docker.sock \
  localstack/localstack-pro

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by steffyP** [comment]
Hi @hrishi-hugo,

thanks for reporting. Unfortunately, I wasn't able to reproduce your issue yet. 
I used your sample to deploy the stack using `awslocal cloudformation deploy --stack-name cfn-quickstart-stack --template-file "./AuroraV2Cluster.yml"` and also tried with a even longer name, e.g `reaaaaaaallyyyyylooooooooong-examplestackhscmn-account-cluster`, but the container started up successfully. 

From what you describe, I would assume there is an error when starting the mysql image. Unfortunately, the container is removed automatically once it finished - which I assume it does due to an error. 

Could you please try to receive the logs of the container, so we can further investigate? 

The container name has a random-id at the end, but you could try to use this script to get the logs (start it before you deploy the stack):

```
#!/bin/bash

container_name=$(docker ps --filter "name=ls-mysql" --format "{{.Names}}")

while [ -z "$container_name" ]
do
      container_name=$(docker ps --filter "name=ls-mysql" --format "{{.Names}}")
done

docker logs $container_name -f
```

**Comment by steffyP** [comment]
On a side-note: I found another issue revealed by your example, for `awslocal cloudformation delete-stack` - we will provide a fix for that.

**Comment by hrishi-hugo** [comment]
Hi @steffyP 

I have checked it again and I still get the same error. The only thing I am changing in my whole stack is only the DBClusterIdentifier
> From what you describe, I would assume there is an error when starting the mysql image. Unfortunately, the container is removed automatically once it finished - which I assume it does due to an error.

This is not the case because I see that the MySQL docker container is spun up and still running after the `root@localhost` error which i gave above occurs.
When I check the status of the DB cluster with cli using `awslocal rds describe-db-clusters` I see that the status of the cluster is `"error"`

These are the logs from the MySQL container with the script you provided
```2023-02-20 15:51:04+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.32-1.el8 started.
2023-02-20 15:51:04+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2023-02-20 15:51:04+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.32-1.el8 started.
'/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
2023-02-20T15:51:05.468478Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
2023-02-20T15:51:05.471114Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.32) starting as process 1
2023-02-20T15:51:05.482772Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2023-02-20T15:51:05.671349Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2023-02-20T15:51:05.814308Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2023-02-20T15:51:05.814342Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2023-02-20T15:51:05.815272Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2023-02-20T15:51:05.828807Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
2023-02-20T15:51:05.828907Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.32'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.```

**Comment by steffyP** [comment]
Hi @hrishi-hugo,

thanks for clarifying! 
Taking another look on your initial logs: `ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)\n") Traceback (most recent call last)` seems like the password was not accepted. 🤔 

However, the container is started with ENVs that correspond to the cluster-configuration (db-name, user, password), and the container seem to start successfully.

As you describe the issue only happens for a certain length, my current best guess is an issue/limitation with the folder-names. 
A bit of background information: To prepare persistence support, the container uses a bind-mount for `/var/lib/mysql` which maps to the LocalStack persistence dir (or temp-dir), including the database-cluster-identifier as name (the entire pattern would be something like `<persistence-dir>/state/rds-data-mysql/cluster/<region>/<cluster-identifier>`). 
We recently identified another issue with this mount and the persistence feature, for which we will provide a fix in an upcoming version. 

However, I would have assumed that the MySQL container would not start successfully, if there is indeed an issue with the bind-mount in your case. 

To further investigate could you please provide the following information:
* On what platform are you experiencing this issue?
* Could you please check the env-settings and volume bind of the `ls-msql-...` container?
   * `docker inspect --format='{{json .Config.Env}}'  <container-name>`
      you should get some `MSQL_` envs that correspond to the cluster-settings, e.g.: `"MYSQL_ROOT_PASSWORD=password","MYSQL_PASSWORD=password","MYSQL_USER=user","MYSQL_DATABASE=hs"`
* Are you able to connect to the database with an external tool?
* If you exec into the container (`docker exec -it <container-name>  /bin/bash`), are you able to run `mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'` without any errors?

**Comment by hrishi-hugo** [comment]
@steffyP 

* Localstack Pro Docker image on M1 Mac

these are env variables in the container (I replaced the MYSQL_DATABASE with the no of chars in our db name)
```
["MYSQL_ROOT_PASSWORD=test","MYSQL_PASSWORD=test","MYSQL_USER=myadminuser,"MYSQL_DATABASE=XXXXXXXXXXXXXXXXXXXXXXXX","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","GOSU_VERSION=1.16","MYSQL_MAJOR=8.0","MYSQL_VERSION=8.0.32-1.el8","MYSQL_SHELL_VERSION=8.0.32-1.el8"]
```

and these are the mounts
```
/VAR/LIB/MYSQL            /var/lib/localstack/tmp/state/rds-data-mysql/cluster/us-east-1/XXXXXXXXXXXXXXXXX-account-cluster
```

* No I am not able to login with mysql cli
```ERROR 1045 (28000): Access denied for user 'myadminuser'@'172.17.0.1' (using password: YES)```

* inside the container with bash also gives an error
```
apple@apples-Air ~ % docker exec -it ls-mysql-aead3fb4 /bin/bash
bash-4.4# mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

**Comment by steffyP** [comment]
Hi @hrishi-hugo,

I tried the same thing on a M1 Mac, but couldn't reproduce it either 🙁 

However, in the meantime we released some slight changes on the volume bind for MySQL in the `latest` LocalStack image. 

Could you please try to pull `docker pull localstack/localstack-pro:latest`? 

And please also pull and use the `latest` MySQL image for your example. You will have to pull the `latest` manually, as LocalStack will only read the cached one otherwise: `docker pull mysql:latest`.

It seems like the startup of `latest` MySQL includes more details, and also logs when the database and user is created. This would be helpful in your case.
