### ISSUE TITLE
bug: Lambda is not able to connect S3 

### ISSUE THREAD

**Issue by irnmon** [localstack/localstack#7706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is the thrown error when Lambda tries to get object from S3(localstack)
```
{
  "errorType": "NetworkingError",
  "errorMessage": "connect ECONNREFUSED 127.0.0.1:4566",
  "code": "NetworkingError",
  "message": "connect ECONNREFUSED 127.0.0.1:4566",
  "errno": "ECONNREFUSED",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": 4566,
  "region": "eu-central-1",
  "hostname": "localhost",
  "retryable": true,
  "time": "2023-02-17T11:12:04.249Z",
  "stack": [
    "Error: connect ECONNREFUSED 127.0.0.1:4566",
    "    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)"
  ]
}
```

This the thrown error inside of localstack container itself
```
   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 667, in run_lambda_executor
     result, log_output = self.execute_in_container(
   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1295, in execute_in_container
     return DOCKER_CLIENT.start_container(
   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 474, in start_container
     raise ContainerException(
 localstack.utils.container_utils.container_client.ContainerException: Docker container returned with exit code 1

 The above exception was the direct cause of the following exception:

 Traceback (most recent call last):
   File "/opt/code/localstack/localstack/utils/threads.py", line 58, in run
     result = self.func(self.params, **kwargs)
   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 484, in do_execute
     return _run(func_arn=func_arn)
   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 183, in wrapped
     raise e
   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 179, in wrapped
     result = func(*args, **kwargs)
   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 471, in _run
     raise e
   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 467, in _run
     result = self._execute(lambda_function, inv_context)
   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 790, in _execute
     result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 712, in run_lambda_executor
     raise InvocationException(
 localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: {"errorType":"NetworkingError","errorMessage":"connect ECONNREFUSED 127.0.0.1:4566"}. Output:
 2023-02-17T11:12:03.731Z	undefined	ERROR	(node:15) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.
```

### Expected Behavior

I would like to download and process the file in S3 bucket.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Here is the localstack part of my docker-compose.yml
```
version: '3.9'
networks:
  test_nw_shared:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1

services:
  test_localstack:
    container_name: test_localstack
    image: localstack/localstack
    networks:
      test_nw_shared:
        ipv4_address: 172.18.0.38
    ports:
      - 4545:4566
    environment:
      - SERVICES=s3,lambda,logs,iam
      - EDGE_PORT=4566
      - DEFAULT_REGION=eu-central-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
    volumes:
      - ${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config-files/init_localstack.sh:/docker-entrypoint-initaws.d/init_localstack.sh
      - ./config-files/image-processing-lambda/function.zip:/function.zip:rw
```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
Here is my lambda code

```
require('dotenv').config();
const sharp = require('sharp');
const constants = require('./constants');
const aws = require('aws-sdk');

exports.handler = async (event, context) => {
    console.log('****** IMAGE PROCESSOR STARTED ******');

    const s3Config = {
        apiVersion: '2006-03-01',
        endpoint: 'http://localhost:4566',
        s3ForcePathStyle: true,
    };

    const s3 = new aws.S3(s3Config);
    const bucket = 'test-bucket-premium-content';

    await Promise.all(
        event.Records.map(async (record) => {
            console.log('----- record -----', record);
            const key = decodeURIComponent(record.s3.object.key.replace(/\+/g, ' '));

            const fileReqParams = {
                Bucket: bucket,
                Key: key,
            };
            const s3File = await s3.getObject(fileReqParams).promise();
            console.log('CONTENT TYPE:', s3File.ContentType);
        }),
    );
    console.log('****** IMAGE PROCESSOR ENDED ******');
};
```

### Environment

```markdown
- OS:MacOs Ventura
- LocalStack: localstack/localstack:latest
```

### Anything else?

When I access the terminal of localstack and list the uploaded objects with example below. I can see the results.
```
aws --endpoint-url=http://localhost:4566 s3api --bucket=test-bucket-premium-content list-objects
---------------------------------
{
    "Contents": [
        {
            "Key": "original/2023/02/test_media_gRfSPgh_LniVIv9ENoYAjARQ7Ft6jdBluoNPyrt3ug7rvurYAMIwzUPa_HJXC7bM.jpg",
            "LastModified": "2023-02-17T10:46:21.000Z",
            "ETag": "\"f09f35a5637839458e462e6350ecbce4\"",
            "Size": 128,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "webfile",
                "ID": "75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a"
            }
        },
        {
            "Key": "original/2023/02/test_media_l35_6xdXtEirY66dqQErui5P_XQMCDpvlqm8LLSCaqKweEFmdbmRe9cx_IsFmkgK.jpg",
            "LastModified": "2023-02-17T11:11:32.000Z",
            "ETag": "\"f09f35a5637839458e462e6350ecbce4\"",
            "Size": 128,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "webfile",
                "ID": "75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a"
            }
        },
        {
            "Key": "original/2023/02/test_media_qD4BzVvDcRER28m2vxMUoGtlKwEFaUWo57BseZUd5b4tileuyftBHRUrrjGNHWIC.jpg",
            "LastModified": "2023-02-17T11:06:37.000Z",
            "ETag": "\"f09f35a5637839458e462e6350ecbce4\"",
            "Size": 128,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "webfile",
                "ID": "75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a"
            }
        }
    ]
}
```

Also I can access one of the objects randomly within localstack terminal
```
aws --endpoint-url=http://localhost:4566 s3api --bucket=test-bucket-premium-content get-object --key=original/2023/02/test_media_l35_6xdXtEirY66dqQErui5P_XQMCDpvlqm8LLSCaqKweEFmdbmRe9cx_IsFmkgK.jpg outfile
---------------------------------
{
    "AcceptRanges": "bytes",
    "LastModified": "Fri, 17 Feb 2023 11:11:32 GMT",
    "ContentLength": 128,
    "ETag": "\"f09f35a5637839458e462e6350ecbce4\"",
    "VersionId": "null",
    "ContentLanguage": "en-US",
    "ContentType": "binary/octet-stream",
    "Metadata": {}
}
```

**Comment by dominikschubert** [comment]
Hi @irnmon 

Please change the following part in your lambda code:

```
    const localstackHost = process.env.LOCALSTACK_HOSTNAME;
    const edgePort = process.env.EDGE_PORT;
    const s3Config = {
        apiVersion: '2006-03-01',
        endpoint: `http://${localstackHost}:${edgePort}`,
        s3ForcePathStyle: true,
    };
```

`LOCALSTACK_HOSTNAME` and `EDGE_PORT` are automatically set by LocalStack when starting the Lambda.

I haven looked too much into your custom network setup but you might also have to explicitly set the corresponding configuration values for proper connectivity between the Lambda container and LocalStack (e.g. via `LAMBDA_DOCKER_NETWORK`). See here for more options: https://docs.localstack.cloud/references/configuration/

I'd also like to suggest trying out the new lambda implementation by setting `PROVIDER_OVERRIDE_LABMDA=v2` in your docker-compose file. There are a lot of smaller additional fixes included in this new implementation.

**Comment by irnmon** [comment]
> Hi @irnmon
> 
> Please change the following part in your lambda code:
> 
> ```
>     const localstackHost = process.env.LOCALSTACK_HOSTNAME;
>     const edgePort = process.env.EDGE_PORT;
>     const s3Config = {
>         apiVersion: '2006-03-01',
>         endpoint: `http://${localstackHost}:${edgePort}`,
>         s3ForcePathStyle: true,
>     };
> ```
> 
> `LOCALSTACK_HOSTNAME` and `EDGE_PORT` are automatically set by LocalStack when starting the Lambda.
> 
> I haven looked too much into your custom network setup but you might also have to explicitly set the corresponding configuration values for proper connectivity between the Lambda container and LocalStack (e.g. via `LAMBDA_DOCKER_NETWORK`). See here for more options: https://docs.localstack.cloud/references/configuration/
> 
> I'd also like to suggest trying out the new lambda implementation by setting `PROVIDER_OVERRIDE_LABMDA=v2` in your docker-compose file. There are a lot of smaller additional fixes included in this new implementation.

@dominikschubert   thank you for your reply and suggestions.

```
    if (constants.environment === 'development') {
        s3Config.endpoint = `http://${process.env.LOCALSTACK_HOSTNAME}:${process.env.EDGE_PORT}`;
        s3Config.s3ForcePathStyle = true;
    }
```
changed these lines with your example and it worked. Also in our docker-compose.yml, we set 
```
    networks:
      test_nw_shared:
        ipv4_address: 172.18.0.38
```
thus `process.env.LOCALSTACK_HOSTNAME` returns the same address.
