### ISSUE TITLE
localstack macOS 10.13.4 error 

### ISSUE THREAD

**Issue by humble14** [localstack/localstack#771]
Hi I consistently getting following error.

```
localstack --debug start
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock DynamoDB (http port 4569)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudWatch (http port 4582)...
Starting mock CloudFormation (http port 4581)...
Starting mock SSM (http port 4583)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Error: Invalid or corrupt jarfile DynamoDBLocal.jar
Starting mock SNS (http port 4575)...
Error: Unable to access jarfile /Users/user/Library/Python/2.7/lib/python/site-packages/localstack/infra/elasticmq/elasticmq-server.jar
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
Listening at http://:::4565
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
* Running on http://0.0.0.0:4579/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4563/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4577/ (Press CTRL+C to quit)
[2018-05-18T23:49:34,023][INFO ][o.e.n.Node               ] [] initializing ...
* Running on http://0.0.0.0:4583/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4580/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
[2018-05-18T23:49:34,178][INFO ][o.e.e.NodeEnvironment    ] [C-6ij7K] using [1] data paths, mounts [[/ (/dev/disk1s1)]], net usable_space [146gb], net total_space [233.5gb], types [apfs]
[2018-05-18T23:49:34,180][INFO ][o.e.e.NodeEnvironment    ] [C-6ij7K] heap size [483.3mb], compressed ordinary object pointers [true]
[2018-05-18T23:49:34,184][INFO ][o.e.n.Node               ] node name [C-6ij7K] derived from node ID [C-6ij7K6QhaeTbVGL34cpA]; set [node.name] to override
[2018-05-18T23:49:34,185][INFO ][o.e.n.Node               ] version[6.2.0], pid[1620], build[37cdac1/2018-02-01T17:31:12.527918Z], OS[Mac OS X/10.13.4/x86_64], JVM["Oracle Corporation"/Java HotSpot(TM) 64-Bit Server VM/10.0.1/10.0.1+10]
[2018-05-18T23:49:34,186][INFO ][o.e.n.Node               ] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/var/folders/f2/g24knyld6sb85cxfwfryg8340000gp/T/elasticsearch.DejMXh8i, -XX:+HeapDumpOnOutOfMemoryError, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -Xms200m, -Xmx500m, -Des.path.home=/Users/user/Library/Python/2.7/lib/python/site-packages/localstack/infra/elasticsearch, -Des.path.conf=/Users/user/Library/Python/2.7/lib/python/site-packages/localstack/infra/elasticsearch/config]
[2018-05-18T23:49:35,314][INFO ][o.e.p.PluginsService     ] [C-6ij7K] loaded module [aggs-matrix-stats]
[2018-05-18T23:49:35,315][INFO ][o.e.p.PluginsService     ] [C-6ij7K] loaded module [analysis-common]
[2018-05-18T23:49:35,315][INFO ][o.e.p.PluginsService     ] [C-6ij7K] loaded module [ingest-common]
[2018-05-18T23:49:35,315][INFO ][o.e.p.PluginsService     ] [C-6ij7K] loaded module [lang-expression]
[2018-05-18T23:49:35,316][INFO ][o.e.p.PluginsService     ] [C-6ij7K] loaded module [lang-mustache]
[2018-05-18T23:49:35,316][INFO ][o.e.p.PluginsService     ] [C-6ij7K] loaded module [lang-painless]
[2018-05-18T23:49:35,316][INFO ][o.e.p.PluginsService     ] [C-6ij7K] loaded module [mapper-extras]
[2018-05-18T23:49:35,316][INFO ][o.e.p.PluginsService     ] [C-6ij7K] loaded module [parent-join]
[2018-05-18T23:49:35,316][INFO ][o.e.p.PluginsService     ] [C-6ij7K] loaded module [percolator]
[2018-05-18T23:49:35,317][INFO ][o.e.p.PluginsService     ] [C-6ij7K] loaded module [rank-eval]
[2018-05-18T23:49:35,317][INFO ][o.e.p.PluginsService     ] [C-6ij7K] loaded module [reindex]
[2018-05-18T23:49:35,318][INFO ][o.e.p.PluginsService     ] [C-6ij7K] loaded module [repository-url]
[2018-05-18T23:49:35,319][INFO ][o.e.p.PluginsService     ] [C-6ij7K] loaded module [transport-netty4]
[2018-05-18T23:49:35,319][INFO ][o.e.p.PluginsService     ] [C-6ij7K] loaded module [tribe]
[2018-05-18T23:49:35,320][INFO ][o.e.p.PluginsService     ] [C-6ij7K] no plugins loaded
[2018-05-18T23:49:37,886][INFO ][o.e.d.DiscoveryModule    ] [C-6ij7K] using discovery type [zen]
[2018-05-18T23:49:38,502][INFO ][o.e.n.Node               ] initialized
[2018-05-18T23:49:38,502][INFO ][o.e.n.Node               ] [C-6ij7K] starting ...
[2018-05-18T23:49:38,706][INFO ][o.e.t.TransportService   ] [C-6ij7K] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2018-05-18T23:49:38,719][WARN ][o.e.b.BootstrapChecks    ] [C-6ij7K] initial heap size [209715200] not equal to maximum heap size [524288000]; this can cause resize pauses and prevents mlockall from locking the entire heap
2018-05-18T23:49:41:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c2d1210>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/localstack/services/generic_proxy.py", line 201, in forward
    headers=forward_headers)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c2d1210>: Failed to establish a new connection: [Errno 61] Connection refused',))

[2018-05-18T23:49:41,779][INFO ][o.e.c.s.MasterService    ] [C-6ij7K] zen-disco-elected-as-master ([0] nodes joined), reason: new_master {C-6ij7K}{C-6ij7K6QhaeTbVGL34cpA}{H5sZADg0S-GgN5KE4dItUw}{127.0.0.1}{127.0.0.1:9300}
[2018-05-18T23:49:41,785][INFO ][o.e.c.s.ClusterApplierService] [C-6ij7K] new_master {C-6ij7K}{C-6ij7K6QhaeTbVGL34cpA}{H5sZADg0S-GgN5KE4dItUw}{127.0.0.1}{127.0.0.1:9300}, reason: apply cluster state (from master [master {C-6ij7K}{C-6ij7K6QhaeTbVGL34cpA}{H5sZADg0S-GgN5KE4dItUw}{127.0.0.1}{127.0.0.1:9300} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)]])
[2018-05-18T23:49:41,847][INFO ][o.e.h.n.Netty4HttpServerTransport] [C-6ij7K] publish_address {127.0.0.1:4560}, bound_addresses {[::1]:4560}, {127.0.0.1:4560}
[2018-05-18T23:49:41,855][INFO ][o.e.n.Node               ] [C-6ij7K] started
[2018-05-18T23:49:41,858][INFO ][o.e.g.GatewayService     ] [C-6ij7K] recovered [0] indices into cluster_state
2018-05-18T23:50:41:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c2ef690>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/localstack/services/generic_proxy.py", line 201, in forward
    headers=forward_headers)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c2ef690>: Failed to establish a new connection: [Errno 61] Connection refused',))

2018-05-18T23:51:41:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c2ef890>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/localstack/services/generic_proxy.py", line 201, in forward
    headers=forward_headers)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c2ef890>: Failed to establish a new connection: [Errno 61] Connection refused',))

2018-05-18T23:52:41:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c2efa90>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/localstack/services/generic_proxy.py", line 201, in forward
    headers=forward_headers)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c2efa90>: Failed to establish a new connection: [Errno 61] Connection refused',))

2018-05-18T23:53:42:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c2efc90>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/localstack/services/generic_proxy.py", line 201, in forward
    headers=forward_headers)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c2efc90>: Failed to establish a new connection: [Errno 61] Connection refused',))

2018-05-18T23:54:42:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c2ef550>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/localstack/services/generic_proxy.py", line 201, in forward
    headers=forward_headers)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c2ef550>: Failed to establish a new connection: [Errno 61] Connection refused',))

2018-05-18T23:55:44:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c2ef5d0>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Users/user/Library/Python/2.7/lib/python/site-packages/localstack/services/generic_proxy.py", line 201, in forward
    headers=forward_headers)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c2ef5d0>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

**Comment by petrogdev** [comment]
experiencing the same issue while running it within docker container. For me it while trying to spin local kinesis service.

**Comment by vergnes** [comment]
You have an error `Error: Unable to access jarfile /Users/user/Library/Python/2.7/lib/python/site-packages/localstack/infra/elasticmq/elasticmq-server.jar`. Downloading the file from https://s3-eu-west-1.amazonaws.com/softwaremill-public/elasticmq-server-0.14.1.jar fixed the issue for me.
