### ISSUE TITLE
bug: v1.4 - Internal error while invoking image-based lambdas

### ISSUE THREAD

**Issue by bugfloyd** [localstack/localstack#7732]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

While invoking a local image-based lambda function, I am getting an internal error.

```
2023-02-22T16:41:38.801 ERROR --- [   asgi_gw_0] l.s.awslambda.provider     : Error while invoking lambda
2023-02-22T16:41:38.802335220Z Traceback (most recent call last):
2023-02-22T16:41:38.802338486Z   File "/opt/code/localstack/localstack/services/awslambda/provider.py", line 1078, in invoke
2023-02-22T16:41:38.802341351Z     invocation_result = result.result()
2023-02-22T16:41:38.802343919Z   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
2023-02-22T16:41:38.802346583Z     return self.__get_result()
2023-02-22T16:41:38.802349072Z   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
2023-02-22T16:41:38.802351723Z     raise self._exception
2023-02-22T16:41:38.802354243Z   File "/opt/code/localstack/localstack/services/awslambda/invocation/version_manager.py", line 266, in invocation_loop
2023-02-22T16:41:38.802357189Z     self.start_environment()
2023-02-22T16:41:38.802359660Z   File "/opt/code/localstack/localstack/services/awslambda/invocation/version_manager.py", line 224, in start_environment
2023-02-22T16:41:38.802362379Z     runtime_environment.start()
2023-02-22T16:41:38.802364829Z   File "/opt/code/localstack/localstack/services/awslambda/invocation/runtime_environment.py", line 134, in start
2023-02-22T16:41:38.802367518Z     self.runtime_executor.start(self.get_environment_variables())
2023-02-22T16:41:38.802370094Z   File "/opt/code/localstack/localstack/services/awslambda/invocation/docker_runtime_executor.py", line 252, in start
2023-02-22T16:41:38.802372782Z     lambda_hooks.start_docker_executor.run(container_config, self.function_version)
2023-02-22T16:41:38.802375374Z   File "/opt/code/localstack/localstack/runtime/hooks.py", line 63, in run_in_order
2023-02-22T16:41:38.802378036Z     fn_plugin(*args, **kwargs)
2023-02-22T16:41:38.802380512Z   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/plugin/core.py", line 183, in __call__
2023-02-22T16:41:38.802383194Z     return self.fn(*args, **kwargs)
2023-02-22T16:41:38.802385850Z   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/awslambda/invocation/docker_runtime_executor_hooks.py.enc", line 19, in start_docker_executor_hook
2023-02-22T16:41:38.802388768Z AttributeError: 'NoneType' object has no attribute 'startswith'
2023-02-22T16:41:38.802767252Z 2023-02-22T16:41:38.802  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS lambda.Invoke => 500 (ServiceException)
```

### Expected Behavior

The lambda function should be invoked without any errors.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up -d

With this compose file:
```
version: '3.7'

services:
  localstack:
    image: localstack/localstack-pro:1.4
    container_name: 'my-localstack'
    hostname: 'my-localstack'
    networks:
        my.localhost:
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=dynamodb,cloudwatch,ses,lambda,logs,s3,ecr
      - HOSTNAME=my-localstack
      - HOSTNAME_EXTERNAL=my-localstack
      - MAIN_CONTAINER_NAME=my-localstack
      - LOCALSTACK_API_KEY=XXXXXXXX
      - PERSISTENCE=1
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_RUNTIME_EXECUTOR=docker
      - PROVIDER_OVERRIDE_LAMBDA=asf
      - PROVIDER_OVERRIDE_S3=asf_pro
    volumes:
      - 'localstack_vol:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
    localstack_vol:

networks:
    my.localhost:
        external: true
```

#### Create a simple lambda image  
    npm init -f
index.js:
```
exports.handler = async (event, context) => {
  console.log(event);
  console.log(context);
  return "Hello World.";
}
```
Dockerfile:
```
FROM amazon/aws-lambda-nodejs:12
COPY index.js package.json ./
RUN npm install
CMD [ "index.handler" ]
```
#### Build and push the image to localstack ECR
    awslocal ecr create-repository --repository-name local-test-lambda --region eu-west-1
    awslocal ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin localhost.localstack.cloud:4510/local-test-lambda
    docker build -t localhost.localstack.cloud:4510/local-test-lambda:latest .
    docker push localhost.localstack.cloud:4510/local-test-lambda:latest

#### Create the lambda and invoke
    awslocal lambda create-function --function-name localTest --package-type Image --code ImageUri=localhost.localstack.cloud:4510/local-test-lambda:latest --role arn:aws:iam::000000000000:role/lambda-role --region eu-west-1
    awslocal lambda invoke --function-name localTest output.txt

    

### Environment

```markdown
- OS: Arch Linux (5.15.88-1-lts)
- LocalStack: 1.4 Pro (I also tested the free version image)
```

### Anything else?

The function seems to be created successfully. This is the output of `awslocal lambda list-functions`:

```
{
    "Functions": [
        {
            "FunctionName": "localTest",
            "FunctionArn": "arn:aws:lambda:eu-west-1:000000000000:function:localTest",
            "Role": "arn:aws:iam::000000000000:role/lambda-role",
            "CodeSize": 0,
            "Description": "",
            "Timeout": 3,
            "MemorySize": 128,
            "LastModified": "2023-02-22T16:40:21.684084+0000",
            "CodeSha256": "dc76017de81b85ff07abada510eb22e4763869b7c9757f98d2702ce8b3e2ffe7",
            "Version": "$LATEST",
            "TracingConfig": {
                "Mode": "PassThrough"
            },
            "RevisionId": "d5ab653c-bee1-49a5-8569-4a360fba9df3",
            "PackageType": "Image",
            "Architectures": [
                "x86_64"
            ],
            "EphemeralStorage": {
                "Size": 512
            }
        }
    ]
}
```

**Comment by bugfloyd** [comment]
I just checked this functionality over `localstack/localstack-pro:1.3` image, and it is working properly!!

**Comment by dfangl** [comment]
Hi! Sorry for this regression.
Please try setting `DNS_ADDRESS=0`, it should avoid the error being triggered, until a proper fix is available.
Thank you for reporting this!

**Comment by dfangl** [comment]
This error should be resolved with `:latest`. Thank you for reporting it!
