### ISSUE TITLE
S3 very slow when lots of images are in the bucket

### ISSUE THREAD

**Issue by daviddawson** [localstack/localstack#7769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we fill up a bucket with a substantial number of files (10k-50k). We get very slow responses from S3.  Files are from 50kb to 130kb in size.

These vary, a single request at a time with this number takes 7-10s.  Overlapping requests increase the time needed, and it appears to then reply in chunks.  So, first set that get a reply, 10s. Next set, 15s, next 25s and so on.  

We have tried with persistence enabled, and disabled. With persistence in the container FS, and in a volume, and in a host volume.   

All show the same slowdown. 

This isn't usable as is for our purposes (functional testing).

### Expected Behavior

S3 responds subsecond not matter how many files are in the bucket.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose. 

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Create a single bucket.

Put 20k files in it

Read 1 file back, see it run slowly (7-10s in our case)
Read 20 files in parallel, see it run even more slowly (7-10s for the first response, up to minutes for the last). 

### Environment

```markdown
- OS:Linux/ Mac
- LocalStack: 1.3/ 1.4.0
```

**Comment by rchincha** [comment]
Any suggested workarounds for this issue?

**Comment by peusebiu** [comment]
@bentsku Hello, I tried using PROVIDER_OVERRIDE_S3=v3 but it fails on multipart uploads.

I have this script which is using a package to communicate with s3, and it doesn't work with v3 provider.

```
package main

import (
	"bytes"
	"context"
	"fmt"
	"errors"

	_ "github.com/docker/distribution/registry/storage/driver/s3-aws"
	"github.com/docker/distribution/registry/storage/driver/factory"
)

func main() {
	params := map[string]interface{}{
		"name":          "s3",
		"rootdirectory": "/root",
		"regionendpoint": "localhost:4566",
		"region":        "us-east-2",
		"bucket":        "store",
		"secure":        true,
		"skipverify":    true,
	}

	store, err := factory.Create("s3", params)
	if err != nil {
		panic(err)
	}

	filepath := "/test/test"

	fileWriter, err := store.Writer(context.TODO(), filepath, false)
	if err != nil {
		panic(err)
	}

	if _, err = fileWriter.Write([]byte("first")); err != nil {
		panic(err)
	}

	fileWriter.Close()

	fileWriterAppend, err := store.Writer(context.TODO(), filepath, true)
	if err != nil {
		panic(err)
	}

	if _, err = fileWriterAppend.Write([]byte("second")); err != nil {
		panic(err)
	}

	fileWriterAppend.Commit()
	fileWriterAppend.Close()

	fileContent, err := store.GetContent(context.Background(), filepath)
	if err != nil {
		panic(err)
	}

	fmt.Println(string(fileContent))

	if string(fileContent) != "firstsecond" {
		panic(errors.New("not equal"))
	}

	fileReader, err := store.Reader(context.Background(), filepath, 0)
	if err != nil {
		panic(err)
	}

	buf := new(bytes.Buffer)
	buf.ReadFrom(fileReader)
	content := buf.String()

	if content != "firstsecond" {
		panic(errors.New("not equal"))
	}

	fmt.Println(string(content))
}
```
This is the output:
```
firstfirsts
panic: not equal

goroutine 1 [running]:
main.main()
        /home/peusebiu/localstack_test/main.go:62 +0x689
```

With v2 provider, script works as expected:
```
firstsecond
firstsecond
```

Also there is an error in localstack logs:
```
2023-10-18T11:05:04.365  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.GetObject => 200
2023-10-18T11:05:04.368 ERROR --- [-functhread6] hypercorn.error            : Error in ASGI Framework
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/http/asgi.py", line 548, in handle_http
    await response.write(packet)
  File "/opt/code/localstack/localstack/http/asgi.py", line 302, in write
    await self.send({"type": "http.response.body", "body": data, "more_body": True})
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/http_stream.py", line 178, in app_send
    await self.send(
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/h11.py", line 136, in stream_send
    await self._send_h11_event(h11.Data(data=event.data))
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event    data = self.connection.send(event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_writers.py", line 65, in __call__
    self.send_data(event.data, write)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_writers.py", line 91, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
  File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 70, in __call__
    return await self.adapter(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/http/asgi.py", line 490, in __call__
    return await self.handle_http(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/http/asgi.py", line 561, in handle_http
    await response.close()
  File "/opt/code/localstack/localstack/http/asgi.py", line 313, in close
    await self.send({"type": "http.response.body", "body": b"", "more_body": False})
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/http_stream.py", line 188, in app_send
    await self.send(EndBody(stream_id=self.stream_id))
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/h11.py", line 138, in stream_send
    await self._send_h11_event(h11.EndOfMessage())
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event    data = self.connection.send(event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_connection.py", line 527, in send_with_data_passthrough
    raise LocalProtocolError("Can't send data when our state is ERROR")
h11._util.LocalProtocolError: Can't send data when our state is ERROR
2023-10-18T11:05:04.368 ERROR --- [-functhread6] hypercorn.error            : Error in ASGI Framework
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/http/asgi.py", line 548, in handle_http
    await response.write(packet)
  File "/opt/code/localstack/localstack/http/asgi.py", line 302, in write
    await self.send({"type": "http.response.body", "body": data, "more_body": True})
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/http_stream.py", line 178, in app_send
    await self.send(
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/h11.py", line 136, in stream_send
    await self._send_h11_event(h11.Data(data=event.data))
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event    data = self.connection.send(event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_writers.py", line 65, in __call__
    self.send_data(event.data, write)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_writers.py", line 91, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/asyncio/task_group.py", line 23, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
  File "/opt/code/localstack/localstack/aws/serving/asgi.py", line 70, in __call__
    return await self.adapter(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/http/asgi.py", line 490, in __call__
    return await self.handle_http(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/http/asgi.py", line 561, in handle_http
    await response.close()
  File "/opt/code/localstack/localstack/http/asgi.py", line 313, in close
    await self.send({"type": "http.response.body", "body": b"", "more_body": False})
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/http_stream.py", line 188, in app_send
    await self.send(EndBody(stream_id=self.stream_id))
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/h11.py", line 138, in stream_send
    await self._send_h11_event(h11.EndOfMessage())
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/hypercorn/protocol/h11.py", line 240, in _send_h11_event    data = self.connection.send(event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/h11/_connection.py", line 527, in send_with_data_passthrough
    raise LocalProtocolError("Can't send data when our state is ERROR")
h11._util.LocalProtocolError: Can't send data when our state is ERROR
```

**Comment by bentsku** [comment]
Hi @peusebiu and thanks a lot for the feedback. Do you mind if I open a new GitHub issue from your comment as this seems like a different issue? I'll start working on it now. Thanks!

**Comment by peusebiu** [comment]
Hi @bentsku, yes, sure.

Thank you!
