### ISSUE TITLE
bug: policy statement sid should be treated as optional

### ISSUE THREAD

**Issue by dlutsch** [localstack/localstack#7804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an iam policy statement is created without explicitly defining a sid, the stack fails with the following error in localstack:

```
Invalid type for parameter StatementId, value: None, type: <class 'NoneType'>, valid types: <class 'str'> Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1335, in _run
    self.do_apply_changes_in_loop(changes, stack)
  File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1412, in do_apply_changes_in_loop
    self.apply_change(change, stack=stack)
  File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1498, in apply_change
    result = update_resource(resource_id, stack=stack)
  File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 638, in update_resource
    result = instance.update_resource(resource, stack_name=stack_name, resources=resources)
  File "/opt/code/localstack/localstack/services/cloudformation/models/awslambda.py", line 263, in update_resource
    client.remove_permission(FunctionName=update_config_props["FunctionName"], StatementId=sid)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 919, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 990, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter StatementId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

### Expected Behavior

stack should deploy without error, no sid should be assigned to the policy statement.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    ```
    new iam.PolicyStatement({
        effect: Effect.ALLOW,
        principals: [
            new iam.AnyPrincipal(),
        ],
        actions: [
            "execute-api:Invoke",
        ],
        resources: [
            "*",
        ]
        }
    });
    ```

### Environment

```markdown
- OS: macOS 12.6.3
- LocalStack: latest
```

### Anything else?

You can see here in the docs that sid is an optional property:
https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-iam.PolicyStatement.html#sid

**Comment by dlutsch** [comment]
This seems to happen to me only on subsequent runs. For some reason it is attempting to update these resources even when no change is present, then fails on the update: 

```
2023-03-06T03:21:20.328 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Action "update" not yet implemented for CF resource type AWS::ApiGateway::RestApi
2023-03-06T03:21:20.329 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Handling "Modify" for resource "crpaytransactionservicerestapi1D77F515" (1/35) type "AWS::ApiGateway::RestApi" in loop iteration 1 (should_deploy=False)
2023-03-06T03:21:20.410 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Handling "Modify" for resource "crpaytransactionservicerestapiCloudWatchRoleBBCEACF7" (1/34) type "AWS::IAM::Role" in loop iteration 1 (should_deploy=True)
2023-03-06T03:21:20.411  INFO --- [uncthread603] l.s.c.e.template_deployer  : Updating resource crpaytransactionservicerestapiCloudWatchRoleBBCEACF7 of type AWS::IAM::Role
2023-03-06T03:21:20.512 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Action "update" not yet implemented for CF resource type AWS::ApiGateway::Account
2023-03-06T03:21:20.512 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Handling "Modify" for resource "crpaytransactionservicerestapiAccountA635D52C" (1/33) type "AWS::ApiGateway::Account" in loop iteration 1 (should_deploy=False)
2023-03-06T03:21:20.574 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Action "update" not yet implemented for CF resource type AWS::ApiGateway::Deployment
2023-03-06T03:21:20.574 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Handling "Modify" for resource "crpaytransactionservicerestapiDeployment43B7F624e784e6ebb3d439aa726c5d55fa8327c9" (1/32) type "AWS::ApiGateway::Deployment" in loop iteration 1 (should_deploy=False)
2023-03-06T03:21:20.662 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Action "update" not yet implemented for CF resource type AWS::ApiGateway::Stage
2023-03-06T03:21:20.662 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Handling "Modify" for resource "crpaytransactionservicerestapiDeploymentStageprodEA8A9D72" (1/31) type "AWS::ApiGateway::Stage" in loop iteration 1 (should_deploy=False)
2023-03-06T03:21:20.678 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Extract resource attribute: AWS::ApiGateway::RestApi RootResourceId
2023-03-06T03:21:20.802 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Handling "Modify" for resource "crpaytransactionservicerestapiOPTIONS8BC5CB51" (1/30) type "AWS::ApiGateway::Method" in loop iteration 1 (should_deploy=True)
2023-03-06T03:21:20.810  INFO --- [uncthread603] l.s.c.e.template_deployer  : Updating resource crpaytransactionservicerestapiOPTIONS8BC5CB51 of type AWS::ApiGateway::Method
2023-03-06T03:21:20.839 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Extract resource attribute: AWS::ApiGateway::RestApi RootResourceId
2023-03-06T03:21:20.962 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Action "update" not yet implemented for CF resource type AWS::ApiGateway::Resource
2023-03-06T03:21:20.962 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Handling "Modify" for resource "crpaytransactionservicerestapiv1B7730837" (1/29) type "AWS::ApiGateway::Resource" in loop iteration 1 (should_deploy=False)
2023-03-06T03:21:21.092 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Handling "Modify" for resource "crpaytransactionservicerestapiv1OPTIONS67B3FBAC" (1/28) type "AWS::ApiGateway::Method" in loop iteration 1 (should_deploy=True)
2023-03-06T03:21:21.109  INFO --- [uncthread603] l.s.c.e.template_deployer  : Updating resource crpaytransactionservicerestapiv1OPTIONS67B3FBAC of type AWS::ApiGateway::Method
2023-03-06T03:21:21.270 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Action "update" not yet implemented for CF resource type AWS::ApiGateway::Resource
2023-03-06T03:21:21.271 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Handling "Modify" for resource "crpaytransactionservicerestapiv1invoice08341C8E" (1/27) type "AWS::ApiGateway::Resource" in loop iteration 1 (should_deploy=False)
2023-03-06T03:21:21.409 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Handling "Modify" for resource "crpaytransactionservicerestapiv1invoiceOPTIONS1B62AC16" (1/26) type "AWS::ApiGateway::Method" in loop iteration 1 (should_deploy=True)
2023-03-06T03:21:21.423  INFO --- [uncthread603] l.s.c.e.template_deployer  : Updating resource crpaytransactionservicerestapiv1invoiceOPTIONS1B62AC16 of type AWS::ApiGateway::Method
2023-03-06T03:21:21.563 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Extract resource attribute: AWS::EC2::SecurityGroup GroupId
2023-03-06T03:21:21.724 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Handling "Modify" for resource "crpaytransactionservicerestapiv1invoicePOSTApiPermissioncrpaytransactionservicemaccrpaytransactionservicerestapiACEDDFE2POSTv1invoice1D386C51" (1/25) type "AWS::Lambda::Permission" in loop iteration 1 (should_deploy=True)
2023-03-06T03:21:21.751  INFO --- [uncthread603] l.s.c.e.template_deployer  : Updating resource crpaytransactionservicerestapiv1invoicePOSTApiPermissioncrpaytransactionservicemaccrpaytransactionservicerestapiACEDDFE2POSTv1invoice1D386C51 of type AWS::Lambda::Permission
2023-03-06T03:21:21.754 DEBUG --- [uncthread603] l.s.c.e.template_deployer  : Error applying changes for CloudFormation stack "cr-pay-transaction-service-mac": Parameter validation failed:
Invalid type for parameter StatementId, value: None, type: <class 'NoneType'>, valid types: <class 'str'> Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1335, in _run
    self.do_apply_changes_in_loop(changes, stack)
  File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1412, in do_apply_changes_in_loop
    self.apply_change(change, stack=stack)
  File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1498, in apply_change
    result = update_resource(resource_id, stack=stack)
  File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 638, in update_resource
    result = instance.update_resource(resource, stack_name=stack_name, resources=resources)
  File "/opt/code/localstack/localstack/services/cloudformation/models/awslambda.py", line 263, in update_resource
    client.remove_permission(FunctionName=update_config_props["FunctionName"], StatementId=sid)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 919, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 990, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter StatementId, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

**Comment by pinzon** [comment]
Hi @dlutsch the UPDATE operation for the resources of type `AWS::Lambda::Permission` is working now. It probably got solve during some of the recent refactoring of the model. Thank you for reporting the issue.
