### ISSUE TITLE
bug: ECS Task Definition Environment variable type issue with AuroraDB port in Cloudformation

### ISSUE THREAD

**Issue by hrishi-hugo** [localstack/localstack#7806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have a CloudFormation stack in which we have a AuroraV2 DB and a ECS task definition in which I am passing an environment variable which is the port of the Aurora DB. 

I am passing it as `!Ref AuroraDB.Endpoint.Port` but I get an error saying that environment variable should be of type String and not Integer in the DEBUG logs of localstack.

I even tried using `!Sub '${AuroraDB.Endpoint.Port}'` or `!Join` using empty strings but the issue still persists

**Comment by deepak2431** [comment]
@hrishi-hugo Can you try passing the port environment variable in this way `!GetAtt MyAuroraDBCluster.Endpoint.Port`

**Comment by hrishi-hugo** [comment]
> @hrishi-hugo Can you try passing the port environment variable in this way `!GetAtt MyAuroraDBCluster.Endpoint.Port`

Thanks for the reply @deepak2431 . But the same error occurs with `!GetAtt` also

Error log :
```
2023-03-07 11:46:07 Invalid type for parameter containerDefinitions[0].environment[8].value, value: 4512, type: <class 'int'>, valid types: <class 'str'> Traceback (most recent call last):
2023-03-07 11:46:07   File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 850, in configure_resource_via_sdk
2023-03-07 11:46:07     result = function(**params)
2023-03-07 11:46:07   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
2023-03-07 11:46:07     return self._make_api_call(operation_name, kwargs)
2023-03-07 11:46:07   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 919, in _make_api_call
2023-03-07 11:46:07     request_dict = self._convert_to_request_dict(
2023-03-07 11:46:07   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 990, in _convert_to_request_dict
2023-03-07 11:46:07     request_dict = self._serializer.serialize_to_request(
2023-03-07 11:46:07   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
2023-03-07 11:46:07     raise ParamValidationError(report=report.generate_report())
2023-03-07 11:46:07 botocore.exceptions.ParamValidationError: Parameter validation failed:
2023-03-07 11:46:07 Invalid type for parameter containerDefinitions[0].environment[8].value, value: 4512, type: <class 'int'>, valid types: <class 'str'>
2023-03-07 11:46:07 
2023-03-07 11:46:07 During handling of the above exception, another exception occurred:
2023-03-07 11:46:07 
2023-03-07 11:46:07 Traceback (most recent call last):
2023-03-07 11:46:07   File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1304, in _run
2023-03-07 11:46:07     self.do_apply_changes_in_loop(changes, stack)
2023-03-07 11:46:07   File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1381, in do_apply_changes_in_loop
2023-03-07 11:46:07     self.apply_change(change, stack=stack)
2023-03-07 11:46:07   File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1461, in apply_change
2023-03-07 11:46:07     result = execute_resource_action(resource_id, self, ACTION_CREATE)
2023-03-07 11:46:07   File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 743, in execute_resource_action
2023-03-07 11:46:07     result = configure_resource_via_sdk(
2023-03-07 11:46:07   File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 867, in configure_resource_via_sdk
2023-03-07 11:46:07     raise e
2023-03-07 11:46:07   File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 862, in configure_resource_via_sdk
2023-03-07 11:46:07     result = function(**converted_params)
2023-03-07 11:46:07   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
2023-03-07 11:46:07     return self._make_api_call(operation_name, kwargs)
2023-03-07 11:46:07   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 919, in _make_api_call
2023-03-07 11:46:07     request_dict = self._convert_to_request_dict(
2023-03-07 11:46:07   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 990, in _convert_to_request_dict
2023-03-07 11:46:07     request_dict = self._serializer.serialize_to_request(
2023-03-07 11:46:07   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
2023-03-07 11:46:07     raise ParamValidationError(report=report.generate_report())
2023-03-07 11:46:07 botocore.exceptions.ParamValidationError: Parameter validation failed:
2023-03-07 11:46:07 Invalid type for parameter containerDefinitions[0].environment[8].value, value: 4512, type: <class 'int'>, valid types: <class 'str'>
```

**Comment by whummer** [comment]
Hi @hrishi-hugo , thanks for reporting. We have now pushed a few enhancements for ECS task deployment in CloudFormation - can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!
