### ISSUE TITLE
java.lang.NoSuchMethodError when running Java 11 lambda on Localstack Pro 1.4.0

### ISSUE THREAD

**Issue by patela** [localstack/localstack#7811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On Localstack Pro 1.4.0 (trial licesnse), invoking a Lambda through API gateway results in a `java.lang.NoSuchMethodError`.
Executing the same request with Localstack Community Edition succeeds.

The error on Pro is this:
```
'java.lang.String software.amazon.awssdk.utils.StringUtils.replaceOnce(java.lang.String, java.lang.String, java.lang.String)': java.lang.NoSuchMethodError
java.lang.NoSuchMethodError: 'java.lang.String software.amazon.awssdk.utils.StringUtils.replaceOnce(java.lang.String, java.lang.String, java.lang.String)'
        at software.amazon.awssdk.services.dynamodb.endpoints.internal.AwsEndpointProviderUtils.setUri(AwsEndpointProviderUtils.java:174)
        at software.amazon.awssdk.services.dynamodb.endpoints.internal.DynamoDbRequestSetEndpointInterceptor.modifyHttpRequest(DynamoDbRequestSetEndpointInterceptor.java:35)
        at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.modifyHttpRequestAndHttpContent(ExecutionInterceptorChain.java:90)
        at software.amazon.awssdk.core.internal.handler.BaseClientHandler.runModifyHttpRequestAndHttpContentInterceptors(BaseClientHandler.java:157)
        at software.amazon.awssdk.core.internal.handler.BaseClientHandler.finalizeSdkHttpFullRequest(BaseClientHandler.java:83)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:151)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
        at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
        at software.amazon.awssdk.services.dynamodb.DefaultDynamoDbClient.listTables(DefaultDynamoDbClient.java:3973)
        at software.amazon.awssdk.services.dynamodb.DynamoDbClient.listTables(DynamoDbClient.java:5771)
        at com.sample.SampleLambda.handleRequest(SampleLambda.java:53)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```

### Expected Behavior

I expect that the lambda is executed without a `java.lang.NoSuchMethodError` error.
In fact, executing the same request with Localstack Community Edition succeeds with no error.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

with the following docker-compose.yml file:

```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-pro:1.4.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=docker-reuse
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DYNAMODB_SHARE_DB=${DYNAMODB_SHARE_DB-1}
      - LAMBDA_STAY_OPEN_MODE=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

To deploy using serverless, use the following command:

```shell
serverless deploy --stage local --region us-east-1
```

After deploy completes, you should see a message in output like this:

```shell
✔ Service deployed to stack sample-app-local (28s)

endpoint: http://localhost:4566/restapis/u2cw487nt5/local/_user_request_
```

Use `curl` to request the /hello endpoint, like this:

```shell
curl http://localhost:4566/restapis/u2cw487nt5/local/_user_request_/hello
```

The response should be:

```shell
Hello World!
```

### Environment

```markdown
- OS: Windows 11
- LocalStack: 1.4.0 (Pro)
```

### Anything else?

Git repo with source code can be found here: https://github.com/patela/sample-lambda

**Comment by patela** [comment]
Similar to the workaround mentioned in #1160 I found that if I downgraded the AWS SDK v2 version in my sample code [here](https://github.com/patela/sample-lambda) to match the one used by the localstack-java-utils version [here](https://github.com/localstack/localstack-java-utils/blob/master/pom.xml#L33), then the error does not occur on Localstack Pro and the lambda works correctly. So the localstack-java-utils seems to have some affect on lambdas. I am using the `docker-reuse` lambda loading method.

The version of AWS SDK v2 that is used in localstack-java-utils was published 2 years ago.

**Comment by dfangl** [comment]
Hi @patela !
Please try setting `PROVIDER_OVERRIDE_LAMBDA=v2` in your environment variables.
This will activate our new lambda provider implementation, which should resolve these kind of problems.
