### ISSUE TITLE
bug: TypeError: context.getRemainingTimeInMillis is not a function

### ISSUE THREAD

**Issue by huangjimmy** [localstack/localstack#7873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[aws lambda context](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-context.html) provides getRemainingTimeInMillis() – Returns the number of milliseconds left before the execution times out.

I log this `getRemainingTimeInMillis()` after lambda completion, but with localstack I get `TypeError: context.getRemainingTimeInMillis is not a function`

When I check execution log I find 
```
2023-03-15T06:50:54.857  INFO --- [uncthread200] l.s.a.lambda_executors     : ['node', '-e', 'const res = require("/Users/jimmy/src/github.com/deliverr/freight-cdc-service/.build/src/cdc/dispatcher/CdcDispatcherLambda.js").handle({"Records": [{"eventID": "shardId-000000000000:49638895493627287214289606647071839137261472022538485762", "eventSourceARN": "arn:aws:kinesis:us-east-1:000000000000:stream/freight-cdc", "eventSource": "aws:kinesis", "eventVersion": "1.0", "eventName": "aws:kinesis:record", "invokeIdentityArn": "arn:aws:iam::000000000000:role/lambda-role", "awsRegion": "us-east-1", "kinesis": {"sequenceNumber": "49638895493627287214289606647071839137261472022538485762", "approximateArrivalTimestamp": 1678862793.247, "data": "eyJkYXRhYmFzZSI6InRyYW5zcG9ydGF0aW9uIiwidGFibGUiOiJGcmVpZ2h0VHJhY2tpbmdJbmZvIiwidHlwZSI6Imluc2VydCIsInRzIjoxNjc4ODYyNzkyLCJ4aWQiOjY2NSwiY29tbWl0Ijp0cnVlLCJkYXRhIjp7ImlkIjo4LCJzaGlwcGluZ1Byb3ZpZGVyIjpudWxsLCJlc3RpbWF0ZWRTaGlwRGF0ZSI6bnVsbCwiZXh0ZXJuYWxJZCI6IkVYVEVSTkFMMTY3ODg2Mjc5MiIsImV4dGVybmFsSWRUeXBlIjoiRlJFSUdIVF9TSElQTUVOVCIsImJvbElkIjoiU1cxNjc4ODYyNzkyIiwicHJvSWQiOm51bGwsImNyZWF0ZWRBdCI6IjIwMjMtMDMtMTUgMDY6NDY6MzIiLCJ1cGRhdGVkQXQiOiIyMDIzLTAzLTE1IDA2OjQ2OjMyIiwiYWNjZXB0ZWRBdCI6bnVsbCwiZGVsaXZlcmVkQXQiOm51bGwsImRlbGl2ZXJ5QXR0ZW1wdEF0IjpudWxsLCJlc3RpbWF0ZWREZWxpdmVyeURhdGUiOm51bGwsInRpbWVkT3V0QXQiOm51bGwsImxhc3RLbm93bkxvY2F0aW9uIjpudWxsfX0=", "partitionKey": "transportation"}}]},{"function_name": "freight-cdc-service-cdc-dispatcher-dev", "function_version": "$LATEST", "client_context": null, "invoked_function_arn": "arn:aws:lambda:us-east-1:000000000000:function:freight-cdc-service-cdc-dispatcher-dev", "cognito_identity": null, "aws_request_id": "55e6eb12-0468-4717-83f7-4011aa403488", "memory_limit_in_mb": 1024, "log_group_name": "/aws/lambda/freight-cdc-service-cdc-dispatcher-dev", "log_stream_name": "2023/03/15/[1]cf9ac6a0"}); const log = (rs) => console.log(JSON.stringify(rs)); res && res.then ? res.then(r => log(r)) : log(res)']
2023-03-15T06:50:54.857 DEBUG --- [uncthread200] localstack.utils.run       : Executing command: ['node', '-e', 'const res = require("/Users/jimmy/src/github.com/deliverr/freight-cdc-service/.build/src/cdc/dispatcher/CdcDispatcherLambda.js").handle({"Records": [{"eventID": "shardId-000000000000:49638895493627287214289606647071839137261472022538485762", "eventSourceARN": "arn:aws:kinesis:us-east-1:000000000000:stream/freight-cdc", "eventSource": "aws:kinesis", "eventVersion": "1.0", "eventName": "aws:kinesis:record", "invokeIdentityArn": "arn:aws:iam::000000000000:role/lambda-role", "awsRegion": "us-east-1", "kinesis": {"sequenceNumber": "49638895493627287214289606647071839137261472022538485762", "approximateArrivalTimestamp": 1678862793.247, "data": "eyJkYXRhYmFzZSI6InRyYW5zcG9ydGF0aW9uIiwidGFibGUiOiJGcmVpZ2h0VHJhY2tpbmdJbmZvIiwidHlwZSI6Imluc2VydCIsInRzIjoxNjc4ODYyNzkyLCJ4aWQiOjY2NSwiY29tbWl0Ijp0cnVlLCJkYXRhIjp7ImlkIjo4LCJzaGlwcGluZ1Byb3ZpZGVyIjpudWxsLCJlc3RpbWF0ZWRTaGlwRGF0ZSI6bnVsbCwiZXh0ZXJuYWxJZCI6IkVYVEVSTkFMMTY3ODg2Mjc5MiIsImV4dGVybmFsSWRUeXBlIjoiRlJFSUdIVF9TSElQTUVOVCIsImJvbElkIjoiU1cxNjc4ODYyNzkyIiwicHJvSWQiOm51bGwsImNyZWF0ZWRBdCI6IjIwMjMtMDMtMTUgMDY6NDY6MzIiLCJ1cGRhdGVkQXQiOiIyMDIzLTAzLTE1IDA2OjQ2OjMyIiwiYWNjZXB0ZWRBdCI6bnVsbCwiZGVsaXZlcmVkQXQiOm51bGwsImRlbGl2ZXJ5QXR0ZW1wdEF0IjpudWxsLCJlc3RpbWF0ZWREZWxpdmVyeURhdGUiOm51bGwsInRpbWVkT3V0QXQiOm51bGwsImxhc3RLbm93bkxvY2F0aW9uIjpudWxsfX0=", "partitionKey": "transportation"}}]},{"function_name": "freight-cdc-service-cdc-dispatcher-dev", "function_version": "$LATEST", "client_context": null, "invoked_function_arn": "arn:aws:lambda:us-east-1:000000000000:function:freight-cdc-service-cdc-dispatcher-dev", "cognito_identity": null, "aws_request_id": "55e6eb12-0468-4717-83f7-4011aa403488", "memory_limit_in_mb": 1024, "log_group_name": "/aws/lambda/freight-cdc-service-cdc-dispatcher-dev", "log_stream_name": "2023/03/15/[1]cf9ac6a0"}); const log = (rs) => console.log(JSON.stringify(rs)); res && res.then ? res.then(r => log(r)) : log(res)']
2023-03-15T06:51:46.331 DEBUG --- [uncthread200] l.s.a.lambda_executors     : Lambda arn:aws:lambda:us-east-1:000000000000:function:freight-cdc-service-cdc-dispatcher-dev result / log output:
{"name":"deliverr","hostname":"21c54829f653","pid":2799,"level":50,"err":{"message":"callback is not a function","name":"TypeError","stack":"TypeError: callback is not a function\n    at commons_logs_1.contextUtils.withContext.X-Request-Id (/Users/jimmy/src/github.com/deliverr/freight-cdc-service/.build/node_modules/@deliverr/commons-lambda/lib/BootstrapHandler.js:14:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"msg":"lambda failed","time":"2023-03-15T06:51:46.319Z","v":0}
>/Users/jimmy/src/github.com/deliverr/freight-cdc-service/.build/node_modules/@deliverr/commons-lambda/lib/BootstrapHandler.js:23
>         commons_logs_1.log.debug(Object.assign(Object.assign({}, ctx), { duration: (Date.now() - before) / 1000, timeLeft: context.getRemainingTimeInMillis() / 1000 }), "done");
>                                                                                                                                    ^
> 
> TypeError: context.getRemainingTimeInMillis is not a function
>     at commons_logs_1.contextUtils.withContext.X-Request-Id (/Users/jimmy/src/github.com/deliverr/freight-cdc-service/.build/node_modules/@deliverr/commons-lambda/lib/BootstrapHandler.js:23:132)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> Node.js v18.14.2
```

Turns out [LambdaContext](https://github.com/localstack/localstack/blob/e277a6c4f73c9f0b763959f0ad8a144979534379/localstack/services/awslambda/lambda_executors.py#L131) 's `get_remaining_time_in_millis ` is not exported/dumped as function `getRemainingTimeInMillis` when calling nodejs lambda in https://github.com/localstack/localstack/blob/e277a6c4f73c9f0b763959f0ad8a144979534379/localstack/services/awslambda/lambda_executors.py#L1570-L1586.  

### Expected Behavior

nodejs lambda can call `context.getRemainingTimeInMillis` inside localstack

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: macOS 13.2.1 (22D68)
- LocalStack: docker image docker.io/localstack/localstack:latest
```

**Comment by dfangl** [comment]
I answered in more detail here: https://github.com/localstack/localstack/pull/7887#issuecomment-1475373175 

In short: please mount your docker socket and enable the new lambda provider, this should lead to a way better experience and fix the issues you are having.

**Comment by joe4dev** [comment]
Hi @huangjimmy

Did our new Lambda implementation in LocalStack 2.0 solve your issue?

Please check out our documentation about [Lambda Provider Behavioral Changes](https://docs.localstack.cloud/references/lambda-provider-v2/)

> Docker socket mounting required: Mounting the Docker socket into the LocalStack container is now required to run lambda functions. Please add the Docker volume mount "/var/run/docker.sock:/var/run/docker.sock" to your LocalStack startup as exemplified in our official [docker-compose.yml](https://github.com/localstack/localstack/blob/master/docker-compose.yml).
