### ISSUE TITLE
bug: PutRecord throws Kinesis Error when it did not used to

### ISSUE THREAD

**Issue by daphnenhuch-at** [localstack/localstack#7924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An integration test that relied on `putRecord` which passed through localstack version 1.4.0 now fails on `latest` with the error

Unfortunately this has been failing for me in CI every time but is flaky to reproduce locally so it's difficult to have more details besidess the stacktrace

```
{
        message: "kinesis: exception while calling kinesis.PutRecord: MyHTTPConnectionPool(host='localhost', port=41855): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5661f2aef0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        stack: "InternalError: kinesis: exception while calling kinesis.PutRecord: MyHTTPConnectionPool(host='localhost', port=41855): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5661f2aef0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n" +
          '    at Request.extractError (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/protocol/json.js:52:27)\n' +
          '    at Request.callListeners (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n' +
          '    at Request.emit (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n' +
          '    at Request.emit (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/request.js:686:14)\n' +
          '    at Request.transition (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/request.js:22:10)\n' +
          '    at AcceptorStateMachine.runTo (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/state_machine.js:14:12)\n' +
          '    at /root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/state_machine.js:26:10\n' +
          '    at Request.<anonymous> (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/request.js:38:9)\n' +
          '    at Request.<anonymous> (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/request.js:688:12)\n' +
          '    at Request.callListeners (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n' +
          '    at Request.emit (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n' +
          '    at Request.emit (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/request.js:686:14)\n' +
          '    at Request.transition (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/request.js:22:10)\n' +
          '    at AcceptorStateMachine.runTo (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/state_machine.js:14:12)\n' +
          '    at /root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/state_machine.js:26:10\n' +
          '    at Request.<anonymous> (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/request.js:38:9)\n' +
          '    at Request.<anonymous> (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/request.js:688:12)\n' +
          '    at Request.callListeners (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n' +
          '    at callNextListener (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/sequential_executor.js:96:12)\n' +
          '    at IncomingMessage.onEnd (/root/hyperbase/node_modules/.store/aws-sdk-npm-2.1310.0-3ae1fbf51b/node_modules/aws-sdk/lib/event_listeners.js:417:13)\n' +
          '    at IncomingMessage.emit (node:events:525:35)\n' +
          '    at IncomingMessage.emit (node:domain:552:15)',
        code: 'InternalError',
        isSafeToKeepProcessAlive: true,
        log: { partitionKey: '0.24465931223756643' }
      },
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose -f localstack/docker-compose.yml up --wait

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Unfortunately this is flaky and only some of the time, some of the put-record commands result in the stacktrace above

### Environment

```markdown
- OS: Ventura 13.2.1
- LocalStack: 1.4.1:dev (latest)
```

**Comment by daphnenhuch-at** [comment]
Is there a way for me to pull different commits of localstack from between 1.4.0 and now to try and find which commit might be the breaking one?

**Comment by viren-nadkarni** [comment]
Hi there, you can get the diff since 1.4 [over here](https://github.com/localstack/localstack/compare/v1.4.0...master)

**Comment by daphnenhuch-at** [comment]
This is the stacktrace I'm seeing:
```
'kinesis: exception while calling kinesis.PutRecord: Traceback (most recent call last):\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn\n' +
          '    conn = connection.create_connection(\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection\n' +
          '    raise err\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection\n' +
          '    sock.connect(sa)\n' +
          'ConnectionRefusedError: [Errno 111] Connection refused\n' +
          '\n' +
          'During handling of the above exception, another exception occurred:\n' +
          '\n' +
          'Traceback (most recent call last):\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen\n' +
          '    httplib_response = self._make_request(\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request\n' +
          '    conn.request(method, url, **httplib_request_kw)\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request\n' +
          '    super(HTTPConnection, self).request(method, url, body=body, headers=headers)\n' +
          '  File "/usr/local/lib/python3.10/http/client.py", line 1283, in request\n' +
          '    self._send_request(method, url, body, headers, encode_chunked)\n' +
          '  File "/usr/local/lib/python3.10/http/client.py", line 1329, in _send_request\n' +
          '    self.endheaders(body, encode_chunked=encode_chunked)\n' +
          '  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders\n' +
          '    self._send_output(message_body, encode_chunked=encode_chunked)\n' +
          '  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output\n' +
          '    self.send(msg)\n' +
          '  File "/usr/local/lib/python3.10/http/client.py", line 976, in send\n' +
          '    self.connect()\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect\n' +
          '    conn = self._new_conn()\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn\n' +
          '    raise NewConnectionError(\n' +
          'urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f70804f0610>: Failed to establish a new connection: [Errno 111] Connection refused\n' +
          '\n' +
          'During handling of the above exception, another exception occurred:\n' +
          '\n' +
          'Traceback (most recent call last):\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/adapters.py", line 489, in send\n' +
          '    resp = conn.urlopen(\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen\n' +
          '    retries = retries.increment(\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment\n' +
          '    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n' +
          "urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='localhost', port=45527): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f70804f0610>: Failed to establish a new connection: [Errno 111] Connection refused'))\n" +
          '\n' +
          'During handling of the above exception, another exception occurred:\n' +
          '\n' +
          'Traceback (most recent call last):\n' +
          '  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle\n' +
          '    handler(self, self.context, response)\n' +
          '  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 123, in __call__\n' +
          '    handler(chain, context, response)\n' +
          '  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 93, in __call__\n' +
          '    skeleton_response = self.skeleton.invoke(context)\n' +
          '  File "/opt/code/localstack/localstack/aws/skeleton.py", line 154, in invoke\n' +
          '    return self.dispatch_request(context, instance)\n' +
          '  File "/opt/code/localstack/localstack/aws/skeleton.py", line 166, in dispatch_request\n' +
          '    result = handler(context, instance) or {}\n' +
          '  File "/opt/code/localstack/localstack/aws/forwarder.py", line 67, in _call\n' +
          '    return fallthrough_handler(context, req)\n' +
          '  File "/opt/code/localstack/localstack/aws/forwarder.py", line 92, in _forward_request\n' +
          '    return forward_request(context, forward_url_getter)\n' +
          '  File "/opt/code/localstack/localstack/aws/forwarder.py", line 103, in forward_request\n' +
          '    return dispatch_to_backend(context, _call_http_backend)\n' +
          '  File "/opt/code/localstack/localstack/aws/forwarder.py", line 120, in dispatch_to_backend\n' +
          '    http_response = http_request_dispatcher(context)\n' +
          '  File "/opt/code/localstack/localstack/aws/forwarder.py", line 101, in _call_http_backend\n' +
          '    return forward(context.request, forward_url_getter())\n' +
          '  File "/opt/code/localstack/localstack/http/proxy.py", line 24, in forward\n' +
          '    return proxy.forward(request, forward_path=forward_path, headers=headers)\n' +
          '  File "/opt/code/localstack/localstack/http/proxy.py", line 90, in forward\n' +
          '    return self.client.request(proxy_request, server=f"{target.scheme}://{target.netloc}")\n' +
          '  File "/opt/code/localstack/localstack/http/client.py", line 75, in request\n' +
          '    response = self.session.request(\n' +
          '  File "/opt/',
        stack: 'InternalError: kinesis: exception while calling kinesis.PutRecord: Traceback (most recent call last):\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn\n' +
          '    conn = connection.create_connection(\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection\n' +
          '    raise err\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection\n' +
          '    sock.connect(sa)\n' +
          'ConnectionRefusedError: [Errno 111] Connection refused\n' +
          '\n' +
          'During handling of the above exception, another exception occurred:\n' +
          '\n' +
          'Traceback (most recent call last):\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen\n' +
          '    httplib_response = self._make_request(\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request\n' +
          '    conn.request(method, url, **httplib_request_kw)\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request\n' +
          '    super(HTTPConnection, self).request(method, url, body=body, headers=headers)\n' +
          '  File "/usr/local/lib/python3.10/http/client.py", line 1283, in request\n' +
          '    self._send_request(method, url, body, headers, encode_chunked)\n' +
          '  File "/usr/local/lib/python3.10/http/client.py", line 1329, in _send_request\n' +
          '    self.endheaders(body, encode_chunked=encode_chunked)\n' +
          '  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders\n' +
          '    self._send_output(message_body, encode_chunked=encode_chunked)\n' +
          '  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output\n' +
          '    self.send(msg)\n' +
          '  File "/usr/local/lib/python3.10/http/client.py", line 976, in send\n' +
          '    self.connect()\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect\n' +
          '    conn = self._new_conn()\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn\n' +
          '    raise NewConnectionError(\n' +
          'urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f70804f0610>: Failed to establish a new connection: [Errno 111] Connection refused\n' +
          '\n' +
          'During handling of the above exception, another exception occurred:\n' +
          '\n' +
          'Traceback (most recent call last):\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/adapters.py", line 489, in send\n' +
          '    resp = conn.urlopen(\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen\n' +
          '    retries = retries.increment(\n' +
          '  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment\n' +
          '    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n' +
          "urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='localhost', port=45527): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f70804f0610>: Failed to establish a new connection: [Errno 111] Connection refused'))\n" +
          '\n' +
          'During handling of the above exception, another exception occurred:\n' +
          '\n' +
          'Traceback (most recent call last):\n' +
          '  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle\n' +
          '    handler(self, self.context, response)\n' +
          '  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 123, in __call__\n' +
          '    handler(chain, context, response)\n' +
          '  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 93, in __call__\n' +
          '    skeleton_response = self.skeleton.invoke(context)\n' +
          '  File "/opt/code/localstack/localstack/aws/skeleton.py", line 154, in invoke\n' +
          '    return self.dispatch_request(context, instance)\n' +
          '  File "/opt/code/localstack/localstack/aws/skeleton.py", line 166, in dispatch_request\n' +
          '    result = handler(context, instance) or {}\n' +
          '  File "/opt/code/localstack/localstack/aws/forwarder.py", line 67, in _call\n' +
          '    return fallthrough_handler(context, req)\n' +
          '  File "/opt/code/localstack/localstack/aws/forwarder.py", line 92, in _forward_request\n' +
          '    return forward_request(context, forward_url_getter)\n' +
          '  File "/opt/code/localstack/localstack/aws/forwarder.py", line 103, in forward_request\n' +
          '    return dispatch_to_backend(context, _call_http_backend)\n' +
          '  File "/opt/code/localstack/localstack/aws/forwarder.py", line 120, in dispatch_to_backend\n' +
          '    http_response = http_request_dispatcher(context)\n' +
          '  File "/opt/code/localstack/localstack/aws/forwarder.py", line 101, in _call_http_backend\n' +
          '    return forward(context.request, forward_url_getter())\n' +
          '  File "/opt/code/localstack/localstack/http/proxy.py", line 24, in forward\n' +
          '    return proxy.forward(request, forward_path=forward_path, headers=headers)\n' +
          '  File "/opt/code/localstack/localstack/http/proxy.py", line 90, in forward\n' +
          '    return self.client.request(proxy_request, server=f"{target.scheme}://{target.netloc}")\n' +
          '  File "/opt/code/localstack/localstack/http/client.py", line 75, in request\n' +
          '    response = self.session.request',
        code: 'InternalError',
```

**Comment by CGavrila** [comment]
@daphnenhuch-at Any luck with this one?

**Comment by daphnenhuch-at** [comment]
> @daphnenhuch-at Any luck with this one?

Nope not yet :( I'm not sure what else to do besides share the stacktrace. I can't seem to understand why the connection is failing in the new version. Any help would be GREAT!

**Comment by daphnenhuch-at** [comment]
@viren-nadkarni I added a more elaborate stacktrace. Is there any chance you could take a look or we could walk through this together. I'm stuck and I don't know what next steps I should take here

**Comment by viren-nadkarni** [comment]
@daphnenhuch-at: LocalStack uses [kinesis-mock](https://github.com/etspaceman/kinesis-mock) under the hood. Based on `ConnectionRefusedError`, it appears that LS fails to connect to kinesis-mock (which is also [auto-restarted in case of failures](https://github.com/localstack/localstack/blob/cf6dbfb/localstack/services/kinesis/kinesis_mock_server.py#L48-L56)). Are there any log messages that suggest kinesis-mock terminates?

Could the issue be with system resources? Kinesis-mock is rather resource-intensive the way it is used in LocalStack. If you are using multi-accounts, this may quickly lead to resource exhaustion.

The above stack trace doesn't contain any information to what might be the issue. And without steps to reproduce this issue, it will be difficult to help.

**Comment by daphnenhuch-at** [comment]
@viren-nadkarni What do you mean by multi-accounts? It's hard to give steps to reproduce as it only happens once in a blue moon locally but every time in CI. I think your suggestion about resource exhaustion makes sense but I'm not sure there's a good path forward in that case :(

**Comment by alexrashed** [comment]
HI @daphnenhuch-at!
This issue could also be caused by the fact that kinesis-mock, which we use under the hood, is now not contained in the image by default, but rather downloaded on demand when the service is actually used.
Once it's downloaded, these packages are reused across runs if you correctly configure the volume directory. You can find more details on that in our docs: https://docs.localstack.cloud/references/filesystem/#localstack-volume
If your CI has limited access to the public internet, or if you are running into a GitHub rate limit, kinesis-mock cannot be downloaded and also not be started.
Unfortunately, that's a bit hard to find with just the stacktrace. Is there a chance that you could give us access to the whole logs? Thanks!

**Comment by DavidZbarsky-at** [comment]
@alexrashed Hi, can you please reopen this issue?

I checked the stack traces daphne provided, and I see this in one of them:

```software.amazon.awssdk.services.kinesis.model.KinesisException: exception while calling kinesis.ListShards: Could not get list of releases from https://api.github.com/repos/etspaceman/kinesis-mock/releases/tags/0.3.10: {"message":"API rate limit exceeded for 135.84.167.43. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

I think that is a good indication that your guess in your last comment is correct. I understand that services are downloaded on-demand, but that's not a great fit in our case (we heavily shard tests across runners so we will hit the limits).

Since we can statically know which services we will need, is there an easy way we can force those to download at docker build time? We're happy to bake our own images based on the upstream one (we mirror the image anyway), but ideally you can provide some sort of script in the image so we can add an extra RUN directive to cache the services we need. Does that make sense?

**Comment by alexrashed** [comment]
Hi @DavidZbarsky-at!
You can find a detailed description on how to build your own image with Kinesis here: https://github.com/localstack/localstack/pull/8194#issuecomment-1522025328
For your specific issue, you could also set the `GITHUB_API_TOKEN` environment variable to a valid GitHub token. This will be picked up by LocalStack when downloading from GitHub, which increases the rate limit quite a lot (we also do this in our test pipelines).

**Comment by DavidZbarsky-at** [comment]
@alexrashed Thanks, that's exactly what I was looking for. Perhaps worth mentioning this in the localstack docs somewhere? I see this issue/similar has come up a few times, https://github.com/localstack/localstack/issues/7148, https://github.com/localstack/localstack/issues/7103, etc.

**Comment by alexrashed** [comment]
To be honest, the API of LPM is not yet stable enough (we would like to make it even easier, such that you do not have to know about the underlying packages being used). This is why we don't have it in our docs yet. Once the UX of the LPM API is smoother, we would like to explicitly advertise it. Until then, the API is not considered stable and might break.
