### ISSUE TITLE
Issue with Docker image

### ISSUE THREAD

**Issue by devil-Coder** [localstack/localstack#793]
I am unable to run the docker image. The complete log is below

```
$ docker run localstack/localstack
2018-05-30 10:21:06,064 CRIT Supervisor running as root (no user in config file)
2018-05-30 10:21:06,067 INFO supervisord started with pid 1
2018-05-30 10:21:07,070 INFO spawned: 'dashboard' with pid 8
2018-05-30 10:21:07,072 INFO spawned: 'infra' with pid 9
(. .venv/bin/activate; exec bin/localstack start)
(. .venv/bin/activate; bin/localstack web)
2018-05-30 10:21:08,090 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-05-30 10:21:08,090 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting local dev environment. CTRL-C to quit.
2018-05-30T10:21:08:INFO:werkzeug:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
2018-05-30T10:21:08:INFO:werkzeug:  * Restarting with stat
Starting mock API Gateway (http port 4567)...
Starting mock DynamoDB (http port 4569)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudWatch (http port 4582)...
Starting mock CloudFormation (http port 4581)...
Starting mock SSM (http port 4583)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
2018-05-30T10:21:11:WARNING:werkzeug:  * Debugger is active!
2018-05-30T10:21:11:INFO:werkzeug:  * Debugger PIN: 137-244-035
2018-05-30T10:21:33:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f51beae5110>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 201, in forward
    headers=forward_headers)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f51beae5110>: Failed to establish a new connection: [Errno 111] Connection refused',))

2018-05-30T10:22:48:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2018-05-30T10:22:51:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
Ready.
```

**Comment by whummer** [comment]
Thanks for reporting @devil-Coder . `Ready.` indicates that the services have spun up properly. Looks like this is only an error in the output, but should not affect the functionality. Closing this issue for housekeeping reasons, please report here if the problem persists. Thanks
