### ISSUE TITLE
Updating an event rule creates a new job without replacing the previous job and events are duplicated.

### ISSUE THREAD

**Issue by ccobos-beonx** [localstack/localstack#7932]
When you modify an existing cron-based event rule, put-rule is used, just like when you create a new one. The problem is that put-rule adds a job to the scheduler, without checking if there was already a previous job associated with the same rule, which causes events to be launched in both crons.

This also means that even if you delete the rule, the previous jobs will continue to be launched, because the delete-rule only deletes one jobid.

I think the code referring to this issue would be the one I show below. (I think in 'put_rule_job_scheduler' a 'cancel_job' should be done before the 'add_job' whena a previous jobid exists).

https://github.com/localstack/localstack/blob/805b4a5e76e48362dbe15de2b1fff145d59b0e35/localstack/services/events/provider.py#L116-L161

**UPDATE (with replication steps):**
One way to replicate this issue is to create a rule with a simple target, modify this rule, and show localstack log. For example:
- Create a rule with cron every 2 minutes:
`awslocal events put-rule --name test-rule --schedule-expression "cron(*/2 * * * ? *)" --state "ENABLED"`
- Add a target to a Lambda function:
`awslocal events put-targets --rule test-rule --targets "Id"="target1","Arn"="arn:aws:lambda:eu-west-1:000000000000:function:MyFunctionName"`
- Modify the rule to fire every minute:
`awslocal events put-rule --name test-rule --schedule-expression "cron(* * * * ? *)" --state "ENABLED"`

The `put-rule` should be an upsert operation. After these operations, the expected result is that Lambda is called only once every minute. However, if you check the log, you can see it is fired once every minute and twice every 2 minutes.

Additionally, if you delete the target and the rule:
`awslocal events remove-targets --rule test-rule --ids target1`
`awslocal events delete-rule --name test-rule`
The expected result is that the events stop happening. However, if you check the log, you will see an error is shown every minute:
> An error occurred (ResourceNotFoundException) when calling the ListTargetsByRule operation: Rule test-rule does not exist.

This happens because the first job continues trying to fire.

**Comment by jonathanswenson** [comment]
Ran into this as well, worked around it (kind of) by deleting and re-creating the rule. However, deleting the rule AFTER updating did (as you said) cause this error to be thrown every minute. 

```
2023-05-15 09:12:27 2023-05-15T16:12:27.189  INFO --- [thread903634] localstack.utils.threads   : Thread run method <function EventsProvider.get_scheduled_rule_func.<locals>.func at 0xffff6ecfb9a0>(None) failed: An error occurred (ResourceNotFoundException) when calling the ListTargetsByRule operation: Rule a299c9bf-c879-4cb6-803f-0d36a8d85028 does not exist. Traceback (most recent call last):
2023-05-15 09:12:27   File "/opt/code/localstack/localstack/utils/threads.py", line 58, in run
2023-05-15 09:12:27     result = self.func(self.params, **kwargs)
2023-05-15 09:12:27   File "/opt/code/localstack/localstack/services/events/provider.py", line 74, in func
2023-05-15 09:12:27     targets = client.list_targets_by_rule(Rule=rule_name)["Targets"]
2023-05-15 09:12:27   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
2023-05-15 09:12:27     return self._make_api_call(operation_name, kwargs)
2023-05-15 09:12:27   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
2023-05-15 09:12:27     raise error_class(parsed_response, operation_name)
2023-05-15 09:12:27 botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the ListTargetsByRule operation: Rule a299c9bf-c879-4cb6-803f-0d36a8d85028 does not exist.
2023-05-15 09:12:27 
```

**Comment by robertchinezon** [comment]
This is still an issue as I am still encountering it in LocalStack 3.0.2.
