### ISSUE TITLE
bug: `latest` image on docker hub fails to stand up

### ISSUE THREAD

**Issue by nickolasclarke** [localstack/localstack#7964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `latest` image pushed to docker hub fails to stand up with the following stacktrace: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/code/localstack/localstack/cli/main.py", line 21, in <module>
    main()
  File "/opt/code/localstack/localstack/cli/main.py", line 14, in main
    from .localstack import create_with_plugins
  File "/opt/code/localstack/localstack/cli/localstack.py", line 7, in <module>
    from localstack import config
  File "/opt/code/localstack/localstack/config.py", line 522, in <module>
    ) = populate_legacy_edge_configuration(os.environ)
  File "/opt/code/localstack/localstack/config.py", line 453, in populate_legacy_edge_configuration
    port = int(localstack_host.split(":")[-1])
ValueError: invalid literal for int() with base 10: 'localstack'
```

It looks like it expects LOCALSTACK_HOST to include a port which it doesn’t. 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: docker pull localstack/localstack
- LocalStack: latest
```

**Comment by thrau** [comment]
Hey Nick @nickolasclarke, this should be fixed in the meantime https://github.com/localstack/localstack/pull/7945. Could you try to pull latest again?
