### ISSUE TITLE
bug: Latest image errors when LOCALSTACK_HOST does not specify a port

### ISSUE THREAD

**Issue by kbret1** [localstack/localstack#7980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Specify LOCALSTACK_HOST=localhost in docker-compose.yml results in localstack erroring on start up.

ValueError: invalid literal for int() with base 10: 'localhost'
2023-03-27 12:21:02 localstack_kcm  | 2023-03-27 16:21:02,580 INFO spawned: 'infra' with pid 19
2023-03-27 12:21:02 localstack_kcm  | 2023-03-27 16:21:02,768 WARN exited: infra (exit status 1; not expected)
2023-03-27 12:21:02 localstack_kcm  | Traceback (most recent call last):
2023-03-27 12:21:02 localstack_kcm  |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2023-03-27 12:21:02 localstack_kcm  |     return _run_code(code, main_globals, None,
2023-03-27 12:21:02 localstack_kcm  |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
2023-03-27 12:21:02 localstack_kcm  |     exec(code, run_globals)
2023-03-27 12:21:02 localstack_kcm  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/cli/main.py", line 21, in <module>
2023-03-27 12:21:02 localstack_kcm  |     main()
2023-03-27 12:21:02 localstack_kcm  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/cli/main.py", line 14, in main
2023-03-27 12:21:02 localstack_kcm  |     from .localstack import create_with_plugins
2023-03-27 12:21:02 localstack_kcm  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/cli/localstack.py", line 7, in <module>
2023-03-27 12:21:02 localstack_kcm  |     from localstack import config
2023-03-27 12:21:02 localstack_kcm  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/config.py", line 519, in <module>
2023-03-27 12:21:02 localstack_kcm  |     ) = populate_legacy_edge_configuration(os.environ)
2023-03-27 12:21:02 localstack_kcm  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/config.py", line 450, in populate_legacy_edge_configuration
2023-03-27 12:21:02 localstack_kcm  |     port = int(localstack_host.split(":")[-1])
2023-03-27 12:21:02 localstack_kcm  | ValueError: invalid literal for int() with base 10: 'localhost'

Seems to be related to this commit: https://github.com/localstack/localstack/commit/77e4835a8dcc6177892ae6c581f9287c7bfb270c

### Expected Behavior

localstack starts normal as it did prior to the commit specified.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Can use our existing example:
https://github.com/joe4dev/localstack-test

### Environment

```markdown
- OS: mac
- LocalStack: pro latest
```

**Comment by kbret1** [comment]
Removing LOCALSTACK_HOST from docker compose file prevents the issue from happening.

**Comment by thrau** [comment]
hi @kbret1! thanks for reporting! this issue was fixed with the community image in https://github.com/localstack/localstack/pull/7945, and will be released with the latest pro in a few hours!

**Comment by thrau** [comment]
hey @kbret1, the latest localstack/localstack-pro image has now been updated and the fix should be deployed!

**Comment by kbret1** [comment]
Thanks for the quick turnaround.  The latest is working again!
