### ISSUE TITLE
bug: Error InvalidLocationConstraint when creating S3 bucket with aws-sdk-js

### ISSUE THREAD

**Issue by gsf4726** [localstack/localstack#8000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Recently, the `localstack/localstack:latest` docker image started returning the following exception when attempting to create an S3 bucket.

The error goes away with the `1.4` tag. I notice that the `latest` tag is now reporting version 2.0.0, so I'm assuming the error started when switching latest to 2.0.0.

```
InvalidLocationConstraint: The specified location-constraint is not valid
    at Request.extractError (/app/node_modules/aws-sdk/lib/services/s3.js:711:35)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/app/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/app/node_modules/aws-sdk/lib/event_listeners.js:417:13)
    at IncomingMessage.emit (node:events:539:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'InvalidLocationConstraint',
  region: null,
  time: 2023-03-29T11:19:28.112Z,
  requestId: 'I6RF1Q8RUYAVEOIJ273KFJ9ANXG6E49AP1KQXVRG4F7H5Z3QOFYZ',
  extendedRequestId: 'MzRISOwyjmnupI6RF1Q8RUYAVEOIJ273KFJ9ANXG6E49AP1KQXVRG4F7H5Z3QOFYZ7/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 6.0331350608730405,
  attemptNumber: 21,
  retriesLeft: 0
}
```

### Expected Behavior

The S3 bucket is created successfully.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "8081:8080"
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - HOSTNAME=localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
const AWS = require('aws-sdk');

const s3 = new AWS.S3({
  apiVersion: '2006-03-01',
  accessKeyId: 'test',
  secretAccessKey: 'test',
  s3ForcePathStyle: true,
  s3BucketEndpoint: false,
  endpoint: new AWS.Endpoint('http://localstack:4566'),
  sslEnabled: false
});

const params = { Bucket: bucket };

await s3.createBucket(params).promise();
```

### Environment

```markdown
- OS: OSX 13.2.1 (22D68)
- LocalStack: latest
```

**Comment by gsf4726** [comment]
From searching, I found that I reported this same error a couple years ago (https://github.com/localstack/localstack/issues/3774). Looking at the source that was changed in that case doesn't appear to have changed this time.

**Comment by bentsku** [comment]
Hello @gsf4726 and thanks for your report.

Could you try setting your endpoint differently and see if that would solve your issue?
```javascript
const AWS = require('aws-sdk');

const s3 = new AWS.S3({
  apiVersion: '2006-03-01',
  accessKeyId: 'test',
  secretAccessKey: 'test',
  s3ForcePathStyle: true,
  s3BucketEndpoint: false,
  endpoint: 'http://localstack:4566',
  sslEnabled: false
});

```
This is related with how the SDK internally checks if it needs to add a `LocationConstraint` to your request.
Basically, the SDK does some check against the endpoint instead of the region to know if it's targeting `us-east-1` or not, and adds a `LocationConstraint`. 

You can see how to set up the JS client here: https://docs.localstack.cloud/user-guide/integrations/sdks/javascript/

**Comment by gsf4726** [comment]
@bentsku appreciate the response. I tried to construct the S3 client exactly as you posted, but unfortunately see the same `InvalidLocationConstraint` error.

**Comment by bentsku** [comment]
Thanks, I can reproduce. I'll try to find a workaround in the client configuration and come back to you, thanks!

**Comment by bentsku** [comment]
Hi @gsf4726, I have an update on the issue.

Basically, the JS SDK v2 is checking if the hostname of the request (`localstack`) is equal to the globalEndpoint (`s3.amazonaws.com`), and if it is different, will add a LocationConstraint independently of the region, when it shouldn't against `us-east-1`.

The quick workaround for now is to override the `globalEndpoint` of your client, so that this check pass. 

```javascript
const AWS = require('aws-sdk');

const s3 = new AWS.S3({
  apiVersion: '2006-03-01',
  accessKeyId: 'test',
  secretAccessKey: 'test',
  s3ForcePathStyle: true,
  s3BucketEndpoint: false,
  endpoint: 'http://localstack:4566',
  sslEnabled: false
});

s3.api.globalEndpoint = 'localstack';

const params = { Bucket: bucket };

await s3.createBucket(params).promise();
```

I've just tried it locally and it fixes the issue for now. We're going to have a look at this issue and think what would be the best way to solve it.
I hope that it will solve your issue as well!

Here the code in the SDK which does the check:
```javascript
  createBucket: function createBucket(params, callback) {
    // When creating a bucket *outside* the classic region, the location
    // constraint must be set for the bucket and it must match the endpoint.
    // This chunk of code will set the location constraint param based
    // on the region (when possible), but it will not override a passed-in
    // location constraint.
    if (typeof params === 'function' || !params) {
      callback = callback || params;
      params = {};
    }
    var hostname = this.endpoint.hostname;
    // copy params so that appending keys does not unintentioinallly
    // mutate params object argument passed in by user
    var copiedParams = AWS.util.copy(params);
    if (hostname !== this.api.globalEndpoint && !params.CreateBucketConfiguration) {
      copiedParams.CreateBucketConfiguration = { LocationConstraint: this.config.region };
    }
    return this.makeRequest('createBucket', copiedParams, callback);
  }
```

**Comment by gsf4726** [comment]
Yep, that eliminated the error for me as well, even reverting the previously suggested changes. Was localstack just ignoring the location constraint in previous versions?

Thanks for the help!

**Comment by januszm** [comment]
Fresh installation of localstack and Docker, this is my first attempt to use localstack with S3 and I'm getting the error mentioned above

```
❯ awslocal  s3api create-bucket --bucket "mybucket-development"

An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to
```

When I try programmatically, using Ruby, it also complains that the PUT request is not acceptable

```ruby
require "aws-sdk-s3"

s3 = Aws::S3::Client.new(endpoint: "https://localhost.localstack.cloud:4566")
s3.create_bucket(bucket: "mybucket-development")
exception while calling s3 with unknown operation: Unable to find operation for request to service s3: PUT / (Aws::S3::Errors::InternalError)
```

log
```
ERROR --- [et.reactor-2] l.aws.handlers.logging     : exception during call chain: Unable to find operation for request to service s3: PUT /
INFO --- [et.reactor-2] localstack.request.http    : PUT / => 500
```

at the moment it's not possible to create an S3 bucket in localstack?

**Comment by januszm** [comment]
Well, ok it's a bit confusing but S3 is special and uses a different s3 endpoint, the key for this to work is to override the endpoint when working with s3 buckets on localstack

```ruby
  Aws.config.update(
    endpoint:  'http://s3.localhost.localstack.cloud:4566', # update with localstack endpoint
    access_key_id: 'test', # update with localstack credentials
    secret_access_key: 'test', # update with localstack credentials
    region: region,
    force_path_style: true, # Enable 'force_path_style' => true, if bucket name is non DNS compliant
  )
```
