### ISSUE TITLE
Next Auth cognito oauth flow support.

### ISSUE THREAD

**Issue by aarlight** [localstack/localstack#8010]
I've setup an authentication flow using AWS cognito and next-auth. I'm working on setting up localstack to streamline development. I've created a local stack instance using docker-compose, and configured localstack cognito using awslocal cli. The login page shows up and I'm able to input my username/password, but the login fails with the following error:

```
https://next-auth.js.org/errors#oauth_callback_error decryption operation failed {
  error: JWEDecryptionFailed: decryption operation failed
       ... stack trace
      at async Object.use (project/path/node_modules/next-auth/core/lib/oauth/checks.js:107:19) <- failing line
  },
  providerId: 'cognito',
  message: 'decryption operation failed'
}
```

The failing line is:
```
const value = await jwt.decode({ ...options.jwt,
      token: state
});
```

where state is:
```
eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..AKy8otlQTICtZ8H5.n1zKro6aL0B4bLTF9d2usLQRmFg_1t4C6Oz8IvfsaoR5rmFGB-C0QNN1a_rUAd0W3cSZm-Wu9ROnivAtk-cNCD7Q0I5SSTUUKRUrXgmFciZAEwgnw_3nhw-Fq2nr4Q94BgKXKtlMs55sh272d18sQA94GpvcFPA0Mws_JsXsdjdFzfFAqvQ.7qcw5fXWvNXvlhMPGjzioQ
```

Is localstack producing a JWT in a format that's different from what cognito produces? Why else would next-auth be having trouble decoding it?

**Comment by whummer** [comment]
Thanks for reporting @aarlight  . We've tried to reproduce your example, but unfortunately without success so far.

We've used this next-auth sample application: https://github.com/nextauthjs/next-auth-example - and added a cognito provider to `pages/api/auth/[...nextauth].ts`, which then seems to make the e2e auth flow run successfully:
```
import CognitoProvider from "next-auth/providers/cognito"
...
    CognitoProvider({
      clientId: process.env.COGNITO_CLIENT_ID,
      clientSecret: process.env.COGNITO_CLIENT_SECRET,
      issuer: process.env.COGNITO_ISSUER,
      idToken: true,
    }),
```

After debugging into the code a bit, it seems that the encoding/decoding of the token is happening within `next-auth` itself, so not sure if this is related to the Cognito token encoding in LocalStack itself.

It seems that a `options.jwt` object is passed to the `decode` call - can you please also print it and share it here (it should contain `secret`/`maxAge` attributes and `encode`/`decode` functions). Should be safe to share, as these should be mostly locally generated values.

Also, can you please share the full stack trace of the exception, as well as some snippets of the configuration of your client application, to help us replicate the issue. Thanks!

For easier debugging, it would be helpful if you could join our Slack channel and drop us a message there: https://slack.localstack.cloud/

**Comment by aarlight** [comment]
Hey @whummer, here are the details you requested:

```
options.jwt {
  secret: 'b03f7f8a5c8365ad1d6a22df09a91c6ef1c1ab90481c63e5d9354ead0bb58f26',
  maxAge: 2592000,
  encode: [AsyncFunction: encode],
  decode: [AsyncFunction: decode]
}
````

Full stack trace:
```
https://next-auth.js.org/errors#oauth_callback_error decryption operation failed {
  error: JWEDecryptionFailed: decryption operation failed
      at gcmDecrypt (/Users/Aaron.Light/Development/node_modules/jose/dist/node/cjs/runtime/decrypt.js:67:15)
      at decrypt (/Users/Aaron.Light/Development/node_modules/jose/dist/node/cjs/runtime/decrypt.js:92:20)
      at flattenedDecrypt (/Users/Aaron.Light/Development/node_modules/jose/dist/node/cjs/jwe/flattened/decrypt.js:119:52)
      at async compactDecrypt (/Users/Aaron.Light/Development/node_modules/jose/dist/node/cjs/jwe/compact/decrypt.js:18:23)
      at async jwtDecrypt (/Users/Aaron.Light/Development/node_modules/jose/dist/node/cjs/jwt/decrypt.js:8:23)
      at async Object.decode (/Users/Aaron.Light/Development/node_modules/next-auth/jwt/index.js:64:7)
      at async Object.use (/Users/Aaron.Light/Development/node_modules/next-auth/core/lib/oauth/checks.js:108:19)
      at async oAuthCallback (/Users/Aaron.Light/Development/node_modules/next-auth/core/lib/oauth/callback.js:89:5)
      at async Object.callback (/Users/Aaron.Light/Development/node_modules/next-auth/core/routes/callback.js:52:11)
      at async AuthHandler (/Users/Aaron.Light/Development/node_modules/next-auth/core/index.js:201:28)
      at async NextAuthHandler (/Users/Aaron.Light/Development/node_modules/next-auth/next/index.js:24:19)
      at async Object.apiResolver (/Users/Aaron.Light/Development/node_modules/next/dist/server/api-utils/node.js:372:9)
      at async DevServer.runApi (/Users/Aaron.Light/Development/node_modules/next/dist/server/next-server.js:514:9)
      at async Object.fn (/Users/Aaron.Light/Development/node_modules/next/dist/server/next-server.js:828:35)
      at async Router.execute (/Users/Aaron.Light/Development/node_modules/next/dist/server/router.js:243:32)
      at async DevServer.runImpl (/Users/Aaron.Light/Development/node_modules/next/dist/server/base-server.js:432:29)
      at async DevServer.run (/Users/Aaron.Light/Development/node_modules/next/dist/server/dev/next-dev-server.js:831:20)
      at async DevServer.handleRequestImpl (/Users/Aaron.Light/Development/node_modules/next/dist/server/base-server.js:375:20)
      at async /Users/Aaron.Light/Development/node_modules/next/dist/server/base-server.js:157:99 {
    name: 'OAuthCallbackError',
    code: 'ERR_JWE_DECRYPTION_FAILED'
  },
  providerId: 'cognito',
  message: 'decryption operation failed'
}
```

`docker-compose.yml`
```
  localstack:
    image: localstack/localstack-pro:latest
    container_name: localstack_main
    ports:
      - ${LOCALSTACK_PORT}:${LOCALSTACK_PORT}
    expose:
      - ${LOCALSTACK_PORT}
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - SERVICES=opensearch,cognito,s3
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DISABLE_CORS_CHECKS=true
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=*
      - LOCALSTACK_HOST=localstack
      - EDGE_PORT=${LOCALSTACK_PORT}
```

And I configure cognito locally using this script
```
#!/bin/bash

export user_pool_name=test-user-pool
export aws_endpoint_url=http://host.docker.internal:4566
export app_client_name=test-app-client 
export hosted_ui_domain=test-domain
export password=password

export pool_id=$(awslocal cognito-idp create-user-pool --pool-name $user_pool_name | jq -r '.UserPool.Id')
export client_secret=$(awslocal cognito-idp create-user-pool-client \
    --user-pool-id $pool_id \
    --client-name $app_client_name \
    --allowed-o-auth-scopes email \
    --callback-urls http://localhost:3000/api/auth/callback/cognito \
    --explicit-auth-flows ALLOW_USER_PASSWORD_AUTH \
    --supported-identity-providers COGNITO \
    --allowed-o-auth-flows code \
    --allowed-o-auth-flows-user-pool-client \
    --generate-secret | jq -r '.UserPoolClient.ClientSecret')
export domain=$(awslocal cognito-idp create-user-pool-domain --domain $hosted_ui_domain --user-pool-id $pool_id --no-verify-ssl | jq -r '.CloudFrontDomain')

awslocal cognito-idp create-group --group-name admin --user-pool-id $pool_id
awslocal cognito-idp create-group --group-name partner --user-pool-id $pool_id
# create admin user
awslocal cognito-idp admin-create-user --user-pool-id $pool_id --username admin --temporary-password $password
awslocal admin-add-user-to-group --user-pool-id $pool_id --username admin --group-name admin
awslocal admin-set-user-password --user-pool-id $pool_id --username admin --password $password --permanent 
# create partner user
awslocal cognito-idp admin-create-user --user-pool-id $pool_id --username partner --temporary-password $password
awslocal admin-add-user-to-group --user-pool-id $pool_id --username partner --group-name partner
awslocal admin-set-user-password --user-pool-id $pool_id --username admin --password $password --permanent 

export client_id=$(awslocal cognito-idp list-user-pool-clients --user-pool-id $pool_id | jq -r '.UserPoolClients[0].ClientId')


echo "pool id: ${pool_id}"
echo "client id: ${client_id}"
echo "client secret: ${client_secret}"
echo "admin user: admin, password: ${password}"
echo "partner user: partner, password: ${password}"
echo "https://${domain}:4566/login?response_type=code&client_id=${client_id}&scope=email+profile&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fauth%2Fcallback%2Fcognito" 
```

Here's a snippet of my `[...nextauth].ts` file
```
const verifier = CognitoJwtVerifier.create({
  region: process.env.COGNITO_REGION,
  userPoolId: process.env.COGNITO_POOL_ID,
  clientId: process.env.COGNITO_CLIENT_ID,
  tokenUse: "access",
});

export const options = {
  // Configure our Okta Auth provider
  providers: [
    CognitoProvider({
      clientId: process.env.COGNITO_CLIENT_ID,
      clientSecret: process.env.COGNITO_CLIENT_SECRET,
      issuer: process.env.COGNITO_ISSUER,
    }),
  ],
  debug: false,
  callbacks: {
    async session({ session, token }) {
      ...
    },
    async jwt({ token, account }) {
      ...
    },
  },
};

const nextAuth = (req, res) => NextAuth(req, res, options);

export default nextAuth;
```

And the env variables
```
COGNITO_CLIENT_ID=x6nbz6477p1x9hs8tahp9nagnr
COGNITO_CLIENT_SECRET=fc37359d
COGNITO_POOL_ID=us-east-1_1f8d9f10f82b49cbb1493269176aabd5
COGNITO_ISSUER=https://7d46c15a.cloudfront.localhost.localstack.cloud:4566/us-east-1_1f8d9f10f82b49cbb1493269176aabd5
````

I'm curious if we're using the same url pattern to connected to the localstack hosted UI. What are you using the for `COGNITO_ISSUER`?

Thanks for all your help on this so far.

**Comment by aarlight** [comment]
Just wanted to bump this... Are you able to share what value you're using for `COGNITO_ISSUER`?

**Comment by whummer** [comment]
Hi @aarlight , thanks for sharing the details. We are working on replicating the issue with the latest information provided, and will get back to you shortly! 👍 

For issuer, we've used the localhost representation of the user pool URL - in your case that would be:
```
COGNITO_ISSUER=http://localhost:4566/us-east-1_1f8d9f10f82b49cbb1493269176aabd5
```

**Comment by whummer** [comment]
Hi @aarlight, just wanted to briefly follow up on this issue. Looks like we haven't been able to replicate it so far - are you still facing this issue, or did you find a resolution/workaround in the meantime? Did it help using the correct value for the `COGNITO_ISSUER` environment variable? Apologies for the delay, and thanks for your help in resolving this!

**Comment by rbmdotdev** [comment]
I am also facing this issue
