### ISSUE TITLE
Cannot configure Kinesis to point to local DynamoDB for checkpointing from my Spark app.

### ISSUE THREAD

**Issue by 01streams** [localstack/localstack#802]
My Spark app is trying to read from a Localstack managed Kinesis stream similar to [this article](https://spark.apache.org/docs/2.2.0/streaming-kinesis-integration.html). I provided the Kinesis endpoint URL as http://localhost:4568 while creating the stream to point to my local Kinesis stream. However I could not find a way to configure the DynamoDB endpoint URL to point to my local DynamoDB instance for Kinesis checkpointing. For this reason when my Spark app runs, checkpointing fails with the below error. How do I configure the Kinesis stream to point to my local DynamoDB instance and not to the default  endpoint URL (dynamodb.us-east-2.amazonaws.com)?

```
ERROR LeaseManager: Failed to get table status for Dev
com.amazonaws.services.kinesis.leases.exceptions.DependencyException: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to dynamodb.us-east-2.amazonaws.com:443 [dynamodb.us-east-2.amazonaws.com/***.***.***.***] failed: connect timed out
        at com.amazonaws.services.kinesis.leases.impl.LeaseManager.tableStatus(LeaseManager.java:163)
        at com.amazonaws.services.kinesis.leases.impl.LeaseManager.createLeaseTableIfNotExists(LeaseManager.java:108)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibLeaseCoordinator.initialize(KinesisClientLibLeaseCoordinator.java:307)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:495)
        at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:436)
        at org.apache.spark.streaming.kinesis.KinesisReceiver$$anon$1.run(KinesisReceiver.scala:178)
		...
```

**Comment by 01streams** [comment]
Closing this issue - just noticed that what I'm facing is the same as [677](https://github.com/localstack/localstack/issues/677).
