### ISSUE TITLE
bug: ASGI Framework Lifespan error when running Localstack Docker instance

### ISSUE THREAD

**Issue by byteshiva** [localstack/localstack#8035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While running a Localstack Docker instance, the following warning message is displayed:

```
2023-04-01T01:34:09.207  WARN --- [-functhread5] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2023-04-01T01:34:09.207  WARN --- [-functhread5] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
```

This warning indicates that there is an issue with the ASGI Framework Lifespan, and that the instance will continue running without Lifespan support. While the instance appears to be running without issue, it would be helpful to have more information on why this warning is being displayed and if it could potentially cause any problems in the future.

### Expected Behavior

Expected behavior:

- The localstack instance should run without any warnings or errors, and the portal should be accessible at https://localhost:4566/ or https://127.0.0.1:4566/

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:


Linux mx-cloud 6.0.0-6mx-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1~mx21+1 (2022-12-15) x86_64 GNU/Linux

- LocalStack:

LocalStack version: 2.0.1.dev
LocalStack build date: 2023-03-31
LocalStack build git hash: d1d118ab
```

**Comment by simonrw** [comment]
Hi, thanks for reporting this.

The warnings should not be affecting the normal startup of LocalStack. If LocalStack is not starting for you, would you mind posting the entire log output?

The warning is unfortunate, but should have no effect on the startup of LocalStack. It's talking about a [part of the ASGI specification](https://asgi.readthedocs.io/en/latest/specs/lifespan.html) that we don't need.

**Comment by byteshiva** [comment]
> Hi, thanks for reporting this.
> 
> The warnings should not be affecting the normal startup of LocalStack. If LocalStack is not starting for you, would you mind posting the entire log output?


logs

```
./localstack start 

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 2.0.1.dev

[14:26:21] starting LocalStack in Docker mode 🐳                                                                                                        localstack.py:142
───────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ─────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/opt/code/localstack/bin/./localstack", line 23, in <module>
    main()
  File "/opt/code/localstack/bin/./localstack", line 19, in main
    main.main()
  File "/opt/code/localstack/localstack/cli/main.py", line 17, in main
    cli()
  File "/opt/code/localstack/localstack/cli/plugin.py", line 15, in __call__
    self.group(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/code/localstack/localstack/utils/analytics/cli.py", line 66, in publisher_wrapper
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/cli/localstack.py", line 168, in cmd_start
    bootstrap.start_infra_in_docker()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 585, in start_infra_in_docker
    prepare_docker_start()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 510, in prepare_docker_start
    if DOCKER_CLIENT.is_container_running(container_name):
  File "/opt/code/localstack/localstack/utils/container_utils/container_client.py", line 524, in is_container_running
    return container_name in self.get_running_container_names()
  File "/opt/code/localstack/localstack/utils/container_utils/container_client.py", line 518, in get_running_container_names
    result = self.list_containers(all=False)
  File "/opt/code/localstack/localstack/utils/container_utils/docker_cmd_client.py", line 214, in list_containers
    cmd_result = run(cmd).strip()
  File "/opt/code/localstack/localstack/utils/run.py", line 69, in run
    output = subprocess.check_output(cmd, shell=shell, stderr=stderr, env=env_dict, cwd=cwd)
  File "/usr/local/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker'
root@55cab9a132dd:/opt/code/localstack/bin# 

```

**Comment by byteshiva** [comment]
> 

I'm unable to execute localhost:4566/_localhost/health from my host machine.  

Based on my understanding of the `config.py` file, the `in_docker` method determines whether the hostname is set to 0.0.0.0 or 127.0.0.1. 

It seems that in the Docker instance, it is not set to 0.0.0.0, and `in_docker` is returning false.

However, I am able to execute the following command inside the Docker instance:

```
curl http://127.0.0.1:4566/_localstack/health
{"services": {"acm": "available", "apigateway": "available", "cloudformation": "available", "cloudwatch": "available", "config": "available", "dynamodb": "available", "dynamodbstreams": "available", "ec2": "available", "es": "available", "events": "available", "firehose": "available", "iam": "available", "kinesis": "available", "kms": "available", "lambda": "available", "logs": "available", "opensearch": "available", "redshift": "available", "resource-groups": "available", "resourcegroupstaggingapi": "available", "route53": "available", "route53resolver": "available", "s3": "available", "s3control": "available", "secretsmanager": "available", "ses": "available", "sns": "available", "sqs": "available", "ssm": "available", "stepfunctions": "available", "sts": "available", "support": "available", "swf": "available", "transcribe": "available"}, "version": "2.0.1.dev"}
```

**Comment by byteshiva** [comment]
> If there is anything sensitive in the logs, please feel free to send me a private message in our community slack. I can be found here: https://localstack-community.slack.com/team/U049YG976KY

I have sent the logs to you via a private message on the Slack Localstack community.

**Comment by byteshiva** [comment]
> 

Based on your suggestion, I added the `-e GATEWAY_LISTEN=0.0.0.0:4566` flag at the start of the Docker instance, and it started working by routing all traffic through 0.0.0.0 from any device on the host to the Docker instance.

Additionally, I am using the experimental features of containerd to pull and store images, as provided by the Docker Desktop

Steps:
```
$ docker run --rm -it -e GATEWAY_LISTEN=0.0.0.0:4566  --name localstack_main -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack:latest

LocalStack version: 2.0.1.dev
LocalStack build date: 2023-03-31
LocalStack build git hash: d1d118ab

2023-04-04T23:49:44.752  WARN --- [-functhread5] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2023-04-04T23:49:44.752  WARN --- [-functhread5] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan support
2023-04-04T23:49:44.753  INFO --- [-functhread5] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2023-04-04T23:49:44.753  INFO --- [-functhread5] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2023-04-04T23:49:44.789  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "start_runtime_components" took 903.12ms
Ready.
2023-04-04T23:50:25.233  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.ListObjects => 404 (NoSuchBucket)
2023-04-04T23:50:39.805  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.ListObjects => 404 (NoSuchBucket)

```

output
```
$ curl -v  http://127.0.0.1:4566/_localstack/health
*   Trying 127.0.0.1:4566...
* Connected to 127.0.0.1 (127.0.0.1) port 4566 (#0)
> GET /_localstack/health HTTP/1.1
> Host: 127.0.0.1:4566
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 
< Content-Type: application/json
< Content-Length: 874
< Connection: close
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
< Access-Control-Allow-Headers: authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request
< Access-Control-Expose-Headers: etag,x-amz-version-id
< date: Wed, 05 Apr 2023 00:04:27 GMT
< server: hypercorn-h11
< 
* Closing connection 0
{"services": {"acm": "available", "apigateway": "available", "cloudformation": "available", "cloudwatch": "available", "config": "available", "dynamodb": "available", "dynamodbstreams": "available", "ec2": "available", "es": "available", "events": "available", "firehose": "available", "iam": "available", "kinesis": "available", "kms": "available", "lambda": "available", "logs": "available", "opensearch": "available", "redshift": "available", "resource-groups": "available", "resourcegroupstaggingapi": "available", "route53": "available", "route53resolver": "available", "s3": "running", "s3control": "available", "secretsmanager": "available", "ses": "available", "sns": "available", "sqs": "available", "ssm": "available", "stepfunctions": "available", "sts": "available", "support": "available", "swf": "available", "transcribe": "available"}, "version": "2.0.1.dev"}

```
![image](https://user-images.githubusercontent.com/10637299/229948943-49a92514-838a-44b9-a4b4-f850573c4f88.png)

**Comment by simonrw** [comment]
I'm glad you have a solution that works. Thanks for raising this issue - we have removed an annoying warning, and improved our detection of whether LocalStack is running in a docker container 🎉  - see the mentioned PRs.

> Based on your suggestion, I added the -e GATEWAY_LISTEN=0.0.0.0:4566 flag at the start of the Docker instance, and it started working by routing all traffic through 0.0.0.0 from any device on the host to the Docker instance.

A minor point, but worth mentioning if people come across this issue in the future: `GATEWAY_LISTEN` configures the listen address of the LocalStack process _within the docker container_. This mostly affects other containers running in the same docker network.

Host -> container configuration is done via `docker` itself: when you specify `-p 4566:4566` that expands to `0.0.0.0:4566:4566` by default. In our documentation we do advocate for the flag `-p 127.0.0.1:4566:4566` which would mean that only the host running docker would be able to access LocalStack. I'm afraid I've not followed our advice, but generally unless you want to expose LocalStack or other docker containers to other hosts, it's best to specify `-p 127.0.0.1:<host port>:<container port>`.

I'll close this issue for now, and thanks again for raising it! If you have any further problems, please open another issue.
