### ISSUE TITLE
bug: LocalStack 2.0 create DynamoDB table just after start fails

### ISSUE THREAD

**Issue by xtaixe** [localstack/localstack#8054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating a table just after starting LocalStack fails with `An error occurred (ResourceInUseException) when calling the CreateTable operation: Table already exists: Music2`

### Expected Behavior

Table is created.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 -e DEBUG=1 localstack/localstack:2.0.0

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws --endpoint-url=http://localhost:4566 dynamodb create-table \                                                                                                                                                               
    --table-name Music2 \
    --attribute-definitions \
        AttributeName=Artist,AttributeType=S \
        AttributeName=SongTitle,AttributeType=S \
    --key-schema \
        AttributeName=Artist,KeyType=HASH \
        AttributeName=SongTitle,KeyType=RANGE \
    --provisioned-throughput \
        ReadCapacityUnits=5,WriteCapacityUnits=5 \
    --table-class STANDARD

### Environment

```markdown
- OS: macOS 12.6.3
- LocalStack: 2.0.0
```

### Anything else?

Logs of first time:

```
2023-04-03T16:14:33.619 DEBUG --- [   asgi_gw_0] localstack.packages.api    : Starting installation of dynamodb-local...
2023-04-03T16:14:34.593 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Starting download from https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip to /tmp/localstack.ddb.zip (42849335 bytes)
2023-04-03T16:14:35.680 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 1048576) to /tmp/localstack.ddb.zip
2023-04-03T16:14:35.900 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 2097152) to /tmp/localstack.ddb.zip
2023-04-03T16:14:37.415 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 3145728) to /tmp/localstack.ddb.zip
2023-04-03T16:14:42.095 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 4194304) to /tmp/localstack.ddb.zip
2023-04-03T16:14:44.293 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 5242880) to /tmp/localstack.ddb.zip
2023-04-03T16:14:45.009 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 6291456) to /tmp/localstack.ddb.zip
2023-04-03T16:14:46.126 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 7340032) to /tmp/localstack.ddb.zip
2023-04-03T16:14:47.933 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 8388608) to /tmp/localstack.ddb.zip
2023-04-03T16:14:50.238 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 9437184) to /tmp/localstack.ddb.zip
2023-04-03T16:14:52.764 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 10485760) to /tmp/localstack.ddb.zip
2023-04-03T16:14:56.132 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 11534336) to /tmp/localstack.ddb.zip
2023-04-03T16:14:58.814 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 12582912) to /tmp/localstack.ddb.zip
2023-04-03T16:15:01.146 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 13631488) to /tmp/localstack.ddb.zip
2023-04-03T16:15:04.127 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 14680064) to /tmp/localstack.ddb.zip
2023-04-03T16:15:06.240 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 15728640) to /tmp/localstack.ddb.zip
2023-04-03T16:15:08.683 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 16777216) to /tmp/localstack.ddb.zip
2023-04-03T16:15:10.974 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 17825792) to /tmp/localstack.ddb.zip
2023-04-03T16:15:13.154 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 18874368) to /tmp/localstack.ddb.zip
2023-04-03T16:15:15.396 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 19922944) to /tmp/localstack.ddb.zip
2023-04-03T16:15:17.277 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 20971520) to /tmp/localstack.ddb.zip
2023-04-03T16:15:20.454 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 22020096) to /tmp/localstack.ddb.zip
2023-04-03T16:15:24.124 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 23068672) to /tmp/localstack.ddb.zip
2023-04-03T16:15:27.358 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 24117248) to /tmp/localstack.ddb.zip
2023-04-03T16:15:30.429 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 25165824) to /tmp/localstack.ddb.zip
2023-04-03T16:15:32.887 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 26214400) to /tmp/localstack.ddb.zip
2023-04-03T16:15:35.348 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 27262976) to /tmp/localstack.ddb.zip
2023-04-03T16:15:38.304 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 28311552) to /tmp/localstack.ddb.zip
2023-04-03T16:15:42.423 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 29360128) to /tmp/localstack.ddb.zip
2023-04-03T16:15:46.408 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 30408704) to /tmp/localstack.ddb.zip
2023-04-03T16:15:50.031 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 31457280) to /tmp/localstack.ddb.zip
2023-04-03T16:15:54.422 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 32505856) to /tmp/localstack.ddb.zip
2023-04-03T16:15:58.489 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 33554432) to /tmp/localstack.ddb.zip
2023-04-03T16:16:01.941 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 34603008) to /tmp/localstack.ddb.zip
2023-04-03T16:16:02.767  INFO --- [   asgi_gw_1] localstack.utils.bootstrap : Execution of "require" took 29740.60ms
2023-04-03T16:16:02.768 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service_plugin.py", line 36, in __call__
    return self.require_service(chain, context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service_plugin.py", line 50, in require_service
    service_plugin: Service = self.service_manager.require(service_name)
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 69, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/plugins.py", line 301, in require
    raise TimeoutError("gave up waiting for service %s to start" % name)
TimeoutError: gave up waiting for service dynamodb to start
2023-04-03T16:16:02.780  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.CreateTable => 500 (InternalError)
2023-04-03T16:16:04.560 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 35651584) to /tmp/localstack.ddb.zip
2023-04-03T16:16:06.369 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 36700160) to /tmp/localstack.ddb.zip
2023-04-03T16:16:07.594 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 37748736) to /tmp/localstack.ddb.zip
2023-04-03T16:16:09.550 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 38797312) to /tmp/localstack.ddb.zip
2023-04-03T16:16:10.868 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 39845888) to /tmp/localstack.ddb.zip
2023-04-03T16:16:12.532 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 40894464) to /tmp/localstack.ddb.zip
2023-04-03T16:16:13.920 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 41943040) to /tmp/localstack.ddb.zip
2023-04-03T16:16:15.208 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Done downloading https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip, response code 200, total bytes 42849335
2023-04-03T16:16:15.216 DEBUG --- [   asgi_gw_0] localstack.utils.run       : Executing command: ['unzip', '-o', '-q', '/tmp/localstack.ddb.zip']
2023-04-03T16:16:15.630 DEBUG --- [   asgi_gw_0] localstack.utils.run       : Executing command: ['zip', '-u', 'DynamoDBLocal.jar', 'log4j2.xml']
2023-04-03T16:16:16.115 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Starting download from https://github.com/localstack/localstack-artifacts/raw/388cd73f45bfd3bcf7ad40aa35499093061c7962/dynamodb-local-patch/target/ddb-local-loader-0.1.jar to /var/lib/localstack/lib/dynamodb-local/latest/ddb-local-loader-0.1.jar (4226 bytes)
2023-04-03T16:16:16.120 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Done downloading https://github.com/localstack/localstack-artifacts/raw/388cd73f45bfd3bcf7ad40aa35499093061c7962/dynamodb-local-patch/target/ddb-local-loader-0.1.jar, response code 200, total bytes 4226
2023-04-03T16:16:16.394 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Starting download from https://repo1.maven.org/maven2/org/javassist/javassist/3.28.0-GA/javassist-3.28.0-GA.jar to /var/lib/localstack/lib/dynamodb-local/latest/javassist.jar (851531 bytes)
2023-04-03T16:16:16.545 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Done downloading https://repo1.maven.org/maven2/org/javassist/javassist/3.28.0-GA/javassist-3.28.0-GA.jar, response code 200, total bytes 851531
2023-04-03T16:16:16.729 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Starting download from https://repo1.maven.org/maven2/org/slf4j/slf4j-ext/1.8.0-beta4/slf4j-ext-1.8.0-beta4.jar to /var/lib/localstack/lib/dynamodb-local/latest/DynamoDBLocal_lib/slf4j-ext-1.8.0-beta4.jar (38652 bytes)
2023-04-03T16:16:16.769 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Done downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-ext/1.8.0-beta4/slf4j-ext-1.8.0-beta4.jar, response code 200, total bytes 38652
2023-04-03T16:16:16.790 DEBUG --- [   asgi_gw_0] localstack.utils.run       : Executing command: ['unzip', '-o', '/var/lib/localstack/lib/dynamodb-local/latest/DynamoDBLocal.jar', 'META-INF/MANIFEST.MF']
2023-04-03T16:16:16.796 DEBUG --- [   asgi_gw_0] localstack.utils.run       : Executing command: ['zip', 'DynamoDBLocal.jar', 'META-INF/MANIFEST.MF']
2023-04-03T16:16:16.854 DEBUG --- [   asgi_gw_0] localstack.packages.api    : Installation of dynamodb-local finished.
2023-04-03T16:16:16.855 DEBUG --- [   asgi_gw_0] l.services.dynamodb.server : starting dynamodb process ['java', '-Xmx256m', '-javaagent:/var/lib/localstack/lib/dynamodb-local/latest/ddb-local-loader-0.1.jar', '-Djava.library.path=/var/lib/localstack/lib/dynamodb-local/latest/DynamoDBLocal_lib', '-jar', '/var/lib/localstack/lib/dynamodb-local/latest/DynamoDBLocal.jar', '-port', '60531', '-dbPath', '/var/lib/localstack/tmp/state/dynamodb']
2023-04-03T16:16:16.855 DEBUG --- [functhread20] localstack.utils.run       : Executing command: ['java', '-Xmx256m', '-javaagent:/var/lib/localstack/lib/dynamodb-local/latest/ddb-local-loader-0.1.jar', '-Djava.library.path=/var/lib/localstack/lib/dynamodb-local/latest/DynamoDBLocal_lib', '-jar', '/var/lib/localstack/lib/dynamodb-local/latest/DynamoDBLocal.jar', '-port', '60531', '-dbPath', '/var/lib/localstack/tmp/state/dynamodb']
2023-04-03T16:16:17.000  INFO --- [functhread20] l.services.dynamodb.server : Initializing DynamoDB Local with the following configuration:
2023-04-03T16:16:17.000  INFO --- [functhread20] l.services.dynamodb.server : Port:	60531
2023-04-03T16:16:17.000  INFO --- [functhread20] l.services.dynamodb.server : InMemory:	false
2023-04-03T16:16:17.000  INFO --- [functhread20] l.services.dynamodb.server : DbPath:	/var/lib/localstack/tmp/state/dynamodb
2023-04-03T16:16:17.000  INFO --- [functhread20] l.services.dynamodb.server : SharedDb:	false
2023-04-03T16:16:17.000  INFO --- [functhread20] l.services.dynamodb.server : shouldDelayTransientStatuses:	false
2023-04-03T16:16:17.000  INFO --- [functhread20] l.services.dynamodb.server : CorsParams:	null
2023-04-03T16:16:17.005  INFO --- [functhread20] l.services.dynamodb.server :
2023-04-03T16:16:18.111 DEBUG --- [   asgi_gw_0] l.services.plugins         : checking service health dynamodb:4566
2023-04-03T16:16:18.112  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "require" took 104589.67ms
2023-04-03T16:16:18.247  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.CreateTable => 200
2023-04-03T16:16:18.322  INFO --- [   asgi_gw_2] localstack.utils.bootstrap : Execution of "require" took 14589.76ms
2023-04-03T16:16:18.330  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS dynamodb.CreateTable => 400 (ResourceInUseException)
```

Logs of another tried where `TimeoutError: gave up waiting for service dynamodb to start` doesn't happen, but still saw the same error:

```
2023-04-03T18:29:38.318 DEBUG --- [   asgi_gw_0] localstack.packages.api    : Starting installation of dynamodb-local...
2023-04-03T18:29:39.262 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Starting download from https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip to /tmp/localstack.ddb.zip (42849335 bytes)
2023-04-03T18:29:40.305 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 1048576) to /tmp/localstack.ddb.zip
2023-04-03T18:29:40.508 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 2097152) to /tmp/localstack.ddb.zip
2023-04-03T18:29:41.246 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 3145728) to /tmp/localstack.ddb.zip
2023-04-03T18:29:43.262 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 4194304) to /tmp/localstack.ddb.zip
2023-04-03T18:29:44.300 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 5242880) to /tmp/localstack.ddb.zip
2023-04-03T18:29:45.936 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 6291456) to /tmp/localstack.ddb.zip
2023-04-03T18:29:47.376 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 7340032) to /tmp/localstack.ddb.zip
2023-04-03T18:29:49.397 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 8388608) to /tmp/localstack.ddb.zip
2023-04-03T18:29:51.666 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 9437184) to /tmp/localstack.ddb.zip
2023-04-03T18:29:53.496 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 10485760) to /tmp/localstack.ddb.zip
2023-04-03T18:29:55.860 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 11534336) to /tmp/localstack.ddb.zip
2023-04-03T18:29:58.420 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 12582912) to /tmp/localstack.ddb.zip
2023-04-03T18:30:00.709 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 13631488) to /tmp/localstack.ddb.zip
2023-04-03T18:30:02.811 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 14680064) to /tmp/localstack.ddb.zip
2023-04-03T18:30:04.968 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 15728640) to /tmp/localstack.ddb.zip
2023-04-03T18:30:07.226 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 16777216) to /tmp/localstack.ddb.zip
2023-04-03T18:30:09.470 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 17825792) to /tmp/localstack.ddb.zip
2023-04-03T18:30:11.139 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 18874368) to /tmp/localstack.ddb.zip
2023-04-03T18:30:13.198 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 19922944) to /tmp/localstack.ddb.zip
2023-04-03T18:30:15.732 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 20971520) to /tmp/localstack.ddb.zip
2023-04-03T18:30:17.690 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 22020096) to /tmp/localstack.ddb.zip
2023-04-03T18:30:19.933 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 23068672) to /tmp/localstack.ddb.zip
2023-04-03T18:30:21.877 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 24117248) to /tmp/localstack.ddb.zip
2023-04-03T18:30:24.215 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 25165824) to /tmp/localstack.ddb.zip
2023-04-03T18:30:26.271 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 26214400) to /tmp/localstack.ddb.zip
2023-04-03T18:30:28.330 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 27262976) to /tmp/localstack.ddb.zip
2023-04-03T18:30:30.368 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 28311552) to /tmp/localstack.ddb.zip
2023-04-03T18:30:31.890 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 29360128) to /tmp/localstack.ddb.zip
2023-04-03T18:30:33.437 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 30408704) to /tmp/localstack.ddb.zip
2023-04-03T18:30:34.686 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 31457280) to /tmp/localstack.ddb.zip
2023-04-03T18:30:35.908 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 32505856) to /tmp/localstack.ddb.zip
2023-04-03T18:30:37.116 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 33554432) to /tmp/localstack.ddb.zip
2023-04-03T18:30:38.199 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 34603008) to /tmp/localstack.ddb.zip
2023-04-03T18:30:39.695 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 35651584) to /tmp/localstack.ddb.zip
2023-04-03T18:30:41.103 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 36700160) to /tmp/localstack.ddb.zip
2023-04-03T18:30:42.137 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 37748736) to /tmp/localstack.ddb.zip
2023-04-03T18:30:43.476 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 38797312) to /tmp/localstack.ddb.zip
2023-04-03T18:30:45.717 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 39845888) to /tmp/localstack.ddb.zip
2023-04-03T18:30:48.221 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 40894464) to /tmp/localstack.ddb.zip
2023-04-03T18:30:50.744 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Written 1048576 bytes (total 41943040) to /tmp/localstack.ddb.zip
2023-04-03T18:30:52.396 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Done downloading https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip, response code 200, total bytes 42849335
2023-04-03T18:30:52.406 DEBUG --- [   asgi_gw_0] localstack.utils.run       : Executing command: ['unzip', '-o', '-q', '/tmp/localstack.ddb.zip']
2023-04-03T18:30:52.813 DEBUG --- [   asgi_gw_0] localstack.utils.run       : Executing command: ['zip', '-u', 'DynamoDBLocal.jar', 'log4j2.xml']
2023-04-03T18:30:53.492 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Starting download from https://github.com/localstack/localstack-artifacts/raw/388cd73f45bfd3bcf7ad40aa35499093061c7962/dynamodb-local-patch/target/ddb-local-loader-0.1.jar to /var/lib/localstack/lib/dynamodb-local/latest/ddb-local-loader-0.1.jar (4226 bytes)
2023-04-03T18:30:53.506 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Done downloading https://github.com/localstack/localstack-artifacts/raw/388cd73f45bfd3bcf7ad40aa35499093061c7962/dynamodb-local-patch/target/ddb-local-loader-0.1.jar, response code 200, total bytes 4226
2023-04-03T18:30:53.757 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Starting download from https://repo1.maven.org/maven2/org/javassist/javassist/3.28.0-GA/javassist-3.28.0-GA.jar to /var/lib/localstack/lib/dynamodb-local/latest/javassist.jar (851531 bytes)
2023-04-03T18:30:53.917 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Done downloading https://repo1.maven.org/maven2/org/javassist/javassist/3.28.0-GA/javassist-3.28.0-GA.jar, response code 200, total bytes 851531
2023-04-03T18:30:54.070 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Starting download from https://repo1.maven.org/maven2/org/slf4j/slf4j-ext/1.8.0-beta4/slf4j-ext-1.8.0-beta4.jar to /var/lib/localstack/lib/dynamodb-local/latest/DynamoDBLocal_lib/slf4j-ext-1.8.0-beta4.jar (38652 bytes)
2023-04-03T18:30:54.105 DEBUG --- [   asgi_gw_0] localstack.utils.http      : Done downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-ext/1.8.0-beta4/slf4j-ext-1.8.0-beta4.jar, response code 200, total bytes 38652
2023-04-03T18:30:54.107 DEBUG --- [   asgi_gw_0] localstack.utils.run       : Executing command: ['unzip', '-o', '/var/lib/localstack/lib/dynamodb-local/latest/DynamoDBLocal.jar', 'META-INF/MANIFEST.MF']
2023-04-03T18:30:54.110 DEBUG --- [   asgi_gw_0] localstack.utils.run       : Executing command: ['zip', 'DynamoDBLocal.jar', 'META-INF/MANIFEST.MF']
2023-04-03T18:30:54.141 DEBUG --- [   asgi_gw_0] localstack.packages.api    : Installation of dynamodb-local finished.
2023-04-03T18:30:54.142 DEBUG --- [   asgi_gw_0] l.services.dynamodb.server : starting dynamodb process ['java', '-Xmx256m', '-javaagent:/var/lib/localstack/lib/dynamodb-local/latest/ddb-local-loader-0.1.jar', '-Djava.library.path=/var/lib/localstack/lib/dynamodb-local/latest/DynamoDBLocal_lib', '-jar', '/var/lib/localstack/lib/dynamodb-local/latest/DynamoDBLocal.jar', '-port', '39597', '-dbPath', '/var/lib/localstack/tmp/state/dynamodb']
2023-04-03T18:30:54.142 DEBUG --- [functhread26] localstack.utils.run       : Executing command: ['java', '-Xmx256m', '-javaagent:/var/lib/localstack/lib/dynamodb-local/latest/ddb-local-loader-0.1.jar', '-Djava.library.path=/var/lib/localstack/lib/dynamodb-local/latest/DynamoDBLocal_lib', '-jar', '/var/lib/localstack/lib/dynamodb-local/latest/DynamoDBLocal.jar', '-port', '39597', '-dbPath', '/var/lib/localstack/tmp/state/dynamodb']
2023-04-03T18:30:54.285  INFO --- [functhread26] l.services.dynamodb.server : Initializing DynamoDB Local with the following configuration:
2023-04-03T18:30:54.285  INFO --- [functhread26] l.services.dynamodb.server : Port:	39597
2023-04-03T18:30:54.285  INFO --- [functhread26] l.services.dynamodb.server : InMemory:	false
2023-04-03T18:30:54.285  INFO --- [functhread26] l.services.dynamodb.server : DbPath:	/var/lib/localstack/tmp/state/dynamodb
2023-04-03T18:30:54.285  INFO --- [functhread26] l.services.dynamodb.server : SharedDb:	false
2023-04-03T18:30:54.285  INFO --- [functhread26] l.services.dynamodb.server : shouldDelayTransientStatuses:	false
2023-04-03T18:30:54.285  INFO --- [functhread26] l.services.dynamodb.server : CorsParams:	null
2023-04-03T18:30:54.291  INFO --- [functhread26] l.services.dynamodb.server :
2023-04-03T18:30:55.413 DEBUG --- [   asgi_gw_0] l.services.plugins         : checking service health dynamodb:4566
2023-04-03T18:30:55.413  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "require" took 77221.51ms
2023-04-03T18:30:55.534  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS dynamodb.CreateTable => 200
2023-04-03T18:30:55.844  INFO --- [   asgi_gw_1] localstack.utils.bootstrap : Execution of "require" took 17081.74ms
2023-04-03T18:30:55.878  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS dynamodb.CreateTable => 400 (ResourceInUseException)
```

**Comment by xtaixe** [comment]
Also, is there a way to avoid these kinds of downloads for services every time LocalStack is started? I think this is going to be slow and a problem for a lot of users.

**Comment by simonrw** [comment]
There are two timeout/retry mechanisms possibly in play here. The first is LocalStack where it waits an amount of time for DynamoDB to download. If it can't be downloaded, it returns the 500 you see. The AWS CLI also has a timeout/retry mechanism, so after receiving the 500, it tries again by which time LocalStack has finished downloading the required .jar and created the table.

In the second case, it looks like the .jar downloads but after the CLI times out and retries, leading to a similar problem where LocalStack creates the table, but the CLI thinks the request has failed so tries again.

One workaround is to set the `LOCALSTACK_VOLUME_DIR` environment directory to somewhere on your computer. LocalStack will mount this directory into the container to store e.g. third party dependencies like DynamoDB. You can trigger the download with `aws --endpoint-url http://localhost:4566 dynamodb list-tables` which will then download the `.jar`. Once this has completed (watch the logs) then you should be able to interact with DynamoDB more quickly. Then the next time you start LocalStack, the jar will already be downloaded.

**Comment by alexrashed** [comment]
Hi @xtaixe!
This issue should have been resolved with https://github.com/localstack/localstack/pull/8194. This PR re-adds a package necessary for DynamoDB to the default Docker image (which removes the necessity of downloading it on demand when the DynamoDB service in LocalStack is initialized), as we also discussed in #8100.
The fix is already in localstack/localstack:latest on DockerHub. Could you maybe verify if this fix resolves your issue as well?
Thanks!
