### ISSUE TITLE
bug: Cannot connect to localstack v2.0 in EKS cluster

### ISSUE THREAD

**Issue by mikesmithxdesign** [localstack/localstack#8078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have the image localstack/localstack:latest-amd64 deployed into an EKS cluster running SNS and SQS - this picks up the version 2.0 release of localstack.

When the service we have deployed in the same cluster attempts to connect to localstack we receive an error - 

`Unable to execute HTTP request: Connect to aws:4566 [aws/172.20.92.156] failed: Connection refused `

It works fine if we revert back to the image - 

`localstack/localstack:1.4-amd64`

We have sen this error since the release of 2.0 (which our build picks up as being the latest version.

The full stack is attached.

### Expected Behavior

When the service in the EKS cluster starts up, it shoudl connect successfully to localstack.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

This is done using a helm chart which is passed into a docker run command - docker run -it

### Environment

```markdown
- OS:linux/amd64 JDK 17
- LocalStack:2.0 AMD64
```

### Anything else?

Don't seem able to attach log, but have pasted here - 

`Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to aws:4566 [aws/172.20.92.156] failed: Connection refused
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1219) ~[aws-java-sdk-core-1.12.232.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1165) ~[aws-java-sdk-core-1.12.232.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814) ~[aws-java-sdk-core-1.12.232.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781) ~[aws-java-sdk-core-1.12.232.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755) ~[aws-java-sdk-core-1.12.232.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715) ~[aws-java-sdk-core-1.12.232.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697) ~[aws-java-sdk-core-1.12.232.jar:?]
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561) ~[aws-java-sdk-core-1.12.232.jar:?]
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541) ~[aws-java-sdk-core-1.12.232.jar:?]
at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2329) ~[aws-java-sdk-sqs-1.12.232.jar:?]
at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2296) ~[aws-java-sdk-sqs-1.12.232.jar:?]
at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2285) ~[aws-java-sdk-sqs-1.12.232.jar:?]
at com.amazonaws.services.sqs.AmazonSQSClient.executeCreateQueue(AmazonSQSClient.java:890) ~[aws-java-sdk-sqs-1.12.232.jar:?]
at com.amazonaws.services.sqs.AmazonSQSClient.createQueue(AmazonSQSClient.java:859) ~[aws-java-sdk-sqs-1.12.232.jar:?]
at com.amazonaws.services.sqs.buffered.AmazonSQSBufferedAsyncClient.createQueue(AmazonSQSBufferedAsyncClient.java:325) ~[aws-java-sdk-sqs-1.12.232.jar:?]
                                            │
Caused by: java.net.ConnectException: Connection refused
at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) ~[?:?]
at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
at java.net.Socket.connect(Socket.java:633) ~[?:?]   
at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75) ~[httpclient-4.5.13.jar:4.5.13]  
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.13.jar:4.5.13] 
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar:4.5.13] 
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] 
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]  
at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[aws-java-sdk-core-1.12.232.jar:?]
at com.amazonaws.http.conn.$Proxy133.connect(Unknown Source) ~[?:?] 
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar:4.5.13] 
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar:4.5.13] 
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:4.5.13]
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13] 
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar:4.5.13]  
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.13.jar:4.5.13]  
at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[aws-java-sdk-core-1.12.232.jar:?] 
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346) ~[aws-java-sdk-core-1.12.232.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157) ~[aws-java-sdk-core-1.12.232.jar:?] 
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814) ~[aws-java-sdk-core-1.12.232.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781) ~[aws-java-sdk-core-1.12.232.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755) ~[aws-java-sdk-core-1.12.232.jar:?] 
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715) ~[aws-java-sdk-core-1.12.232.jar:?] 
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697) ~[aws-java-sdk-core-1.12.232.jar:?]  
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561) ~[aws-java-sdk-core-1.12.232.jar:?]
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541) ~[aws-java-sdk-core-1.12.232.jar:?] 
at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2329) ~[aws-java-sdk-sqs-1.12.232.jar:?] 
at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2296) ~[aws-java-sdk-sqs-1.12.232.jar:?] 
at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2285) ~[aws-java-sdk-sqs-1.12.232.jar:?]
at com.amazonaws.services.sqs.AmazonSQSClient.executeCreateQueue(AmazonSQSClient.java:890) ~[aws-java-sdk-sqs-1.12.232.jar:?] 
at com.amazonaws.services.sqs.AmazonSQSClient.createQueue(AmazonSQSClient.java:859) ~[aws-java-sdk-sqs-1.12.232.jar:?] 
at com.amazonaws.services.sqs.buffered.AmazonSQSBufferedAsyncClient.createQueue(AmazonSQSBufferedAsyncClient.java:325) ~[aws-java-sdk-sqs-1.12.232.jar:?] 
`

**Comment by simonrw** [comment]
Hi, thanks for reporting this issue. Did you use our helm chart from https://helm.localstack.cloud? You are accessing a service called `aws`: have you customised the installation? 

Do you have the logs from the LocalStack pod? Something like `kubectl logs deployment/aws`? I'm looking initially for a line that looks something like:

```
2023-04-05T20:23:30.072  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
```

I'm hoping the IP address is `0.0.0.0` :crossed_fingers:

**Comment by mikesmithxdesign** [comment]
Hi Simon,

No - our helm chart is our custom version. I just rolled the build back forward to use the image and reproduce the issue -

localstack/localstack:latest-amd64 

But it appears to working now and i can't reproduce the issue (unless there has been a fix added?) - 

These are the logs from the localstack container (inclluding the IP of 0.0.0.0) - 

```
SERVICES variable is ignored if EAGER_SERVICE_LOADING=0.   
 
LocalStack version: 2.0.1.dev
LocalStack build date: 2023-04-05
LocalStack build git hash: ae1dfbf9

2023-04-06T07:34:44.966  WARN --- [-functhread5] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan supp
2023-04-06T07:34:44.966  WARN --- [-functhread5] hypercorn.error            : ASGI Framework Lifespan error, continuing without Lifespan supp
2023-04-06T07:34:44.967  INFO --- [-functhread5] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
2023-04-06T07:34:44.967  INFO --- [-functhread5] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
Ready.
```

Cheers, Mike

**Comment by simonrw** [comment]
@mikesmithxdesign thanks for taking a look. I did put in a fix for containers running under `containerd` not detecting that they were in a docker environment - I don't know if that is relevant. Your build (git hash ae1dfbf9) includes that fix, but I think the issue would have been present in the earlier versions as well.

Regardless: I'm glad it is now working for you. Please don't hesitate to open any further issues if you have additional problems :+1:

**Comment by mikesmithxdesign** [comment]
ok, great - thanks simon - i'll keep an eye on it - hopefully, that has done the trick 👍
