### ISSUE TITLE
bug: Aws Athena, alter table add column fails

### ISSUE THREAD

**Issue by amineSt** [localstack/localstack#8098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Query for table creation :** 

``` sql
CREATE EXTERNAL TABLE IF NOT EXISTS `default`.`kb_13_fr` (
                      `current_url` string,
                      `origin` string,
                      `question_id` string,
                      `resource_id` string,
                      `resource2_id` string,
                      `event_type` string,
                      `event_name` string,
                      `knowledgebase_id` int,
                      `channel` string,
                      `device` string,
                      `resource_type` string,
                      `resource2_type` string,
                      `related_search_query` string,
                      `tags` string,
                      `count` int
                      )
                    PARTITIONED BY (`dt` string)
                    ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
                    WITH SERDEPROPERTIES ('separatorChar' = ',','quoteChar' = '\"','escapeChar' = '\"')
                    STORED AS TEXTFILE
                    LOCATION 's3://bucket-name/stats/dt=2022-11-21'
                    TBLPROPERTIES ('has_encrypted_data'='false');
```
**Query for alter table  :** 

```sql

ALTER TABLE `default`.`kb_13_fr`  ADD COLUMNS (testColumn string)

```

**Result : **

```
2023-04-07T14:02:37.602  INFO --- [  Thread-443] l.services.athena.provider : Athena error for query "ALTER TABLE aggregated_stats_dev.t2 ADD COLUMNS (test string)":
TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Error: type expected at the position 0 of '<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:string' but '<' is found.:17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:runQuery:SQLOperation.java:257', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:293', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker::-1', 'java.util.concurrent.ThreadPoolExecutor$Worker:run::-1', 'java.lang.Thread:run::-1', "*java.lang.IllegalArgumentException:Error: type expected at the position 0 of '<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:string' but '<' is found.:37:21", 'org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser:expect:TypeInfoUtils.java:372', 'org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser:expect:TypeInfoUtils.java:355', 'org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser:parseType:TypeInfoUtils.java:416', 'org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser:parseTypeInfos:TypeInfoUtils.java:329', 'org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils:getTypeInfosFromTypeString:TypeInfoUtils.java:814', 'org.apache.hive.hcatalog.data.JsonSerDe:initialize:JsonSerDe.java:130', 'org.apache.hadoop.hive.serde2.AbstractSerDe:initialize:AbstractSerDe.java:54', 'org.apache.hadoop.hive.serde2.SerDeUtils:initializeSerDe:SerDeUtils.java:533', 'org.apache.hadoop.hive.metastore.MetaStoreUtils:getDeserializer:MetaStoreUtils.java:453', 'org.apache.hadoop.hive.metastore.MetaStoreUtils:getDeserializer:MetaStoreUtils.java:440', 'org.apache.hadoop.hive.ql.metadata.Table:getDeserializerFromMetaStore:Table.java:281', 'org.apache.hadoop.hive.ql.metadata.Table:checkValidity:Table.java:199', 'org.apache.hadoop.hive.ql.exec.DDLTask:alterTable:DDLTask.java:3581', 'org.apache.hadoop.hive.ql.exec.DDLTask:execute:DDLTask.java:390', 'org.apache.hadoop.hive.ql.exec.Task:executeTask:Task.java:199', 'org.apache.hadoop.hive.ql.exec.TaskRunner:runSequential:TaskRunner.java:100', 'org.apache.hadoop.hive.ql.Driver:launchTask:Driver.java:2183', 'org.apache.hadoop.hive.ql.Driver:execute:Driver.java:1839', 'org.apache.hadoop.hive.ql.Driver:runInternal:Driver.java:1526', 'org.apache.hadoop.hive.ql.Driver:run:Driver.java:1237', 'org.apache.hadoop.hive.ql.Driver:run:Driver.java:1232', 'org.apache.hive.service.cli.operation.SQLOperation:runQuery:SQLOperation.java:255'], sqlState='08S01', errorCode=1, errorMessage="Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Error: type expected at the position 0 of '<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:string' but '<' is found."), operationHandle=None) Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/athena/provider.py.enc", line 31, in R
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/athena/query_utils.py.enc", line 25, in execute_query
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/hadoop.py.enc", line 233, in execute_hive_query
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/hadoop.py.enc", line 237, in execute_hive_queries
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/hadoop.py.enc", line 249, in _execute_hive_query
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/pyhive/hive.py", line 455, in execute
    _check_status(response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/pyhive/hive.py", line 585, in _check_status
    raise OperationalError(response)
pyhive.exc.OperationalError: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=["*org.apache.hive.service.cli.HiveSQLException:Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Error: type expected at the position 0 of '<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:string' but '<' is found.:17:16", 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380', 'org.apache.hive.service.cli.operation.SQLOperation:runQuery:SQLOperation.java:257', 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:293', 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530', 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506', 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280', 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437', 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422', 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', 'java.util.concurrent.ThreadPoolExecutor:runWorker::-1', 'java.util.concurrent.ThreadPoolExecutor$Worker:run::-1', 'java.lang.Thread:run::-1', "*java.lang.IllegalArgumentException:Error: type expected at the position 0 of '<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:string' but '<' is found.:37:21", 'org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser:expect:TypeInfoUtils.java:372', 'org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser:expect:TypeInfoUtils.java:355', 'org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser:parseType:TypeInfoUtils.java:416', 'org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils$TypeInfoParser:parseTypeInfos:TypeInfoUtils.java:329', 'org.apache.hadoop.hive.serde2.typeinfo.TypeInfoUtils:getTypeInfosFromTypeString:TypeInfoUtils.java:814', 'org.apache.hive.hcatalog.data.JsonSerDe:initialize:JsonSerDe.java:130', 'org.apache.hadoop.hive.serde2.AbstractSerDe:initialize:AbstractSerDe.java:54', 'org.apache.hadoop.hive.serde2.SerDeUtils:initializeSerDe:SerDeUtils.java:533', 'org.apache.hadoop.hive.metastore.MetaStoreUtils:getDeserializer:MetaStoreUtils.java:453', 'org.apache.hadoop.hive.metastore.MetaStoreUtils:getDeserializer:MetaStoreUtils.java:440', 'org.apache.hadoop.hive.ql.metadata.Table:getDeserializerFromMetaStore:Table.java:281', 'org.apache.hadoop.hive.ql.metadata.Table:checkValidity:Table.java:199', 'org.apache.hadoop.hive.ql.exec.DDLTask:alterTable:DDLTask.java:3581', 'org.apache.hadoop.hive.ql.exec.DDLTask:execute:DDLTask.java:390', 'org.apache.hadoop.hive.ql.exec.Task:executeTask:Task.java:199', 'org.apache.hadoop.hive.ql.exec.TaskRunner:runSequential:TaskRunner.java:100', 'org.apache.hadoop.hive.ql.Driver:launchTask:Driver.java:2183', 'org.apache.hadoop.hive.ql.Driver:execute:Driver.java:1839', 'org.apache.hadoop.hive.ql.Driver:runInternal:Driver.java:1526', 'org.apache.hadoop.hive.ql.Driver:run:Driver.java:1237', 'org.apache.hadoop.hive.ql.Driver:run:Driver.java:1232', 'org.apache.hive.service.cli.operation.SQLOperation:runQuery:SQLOperation.java:255'], sqlState='08S01', errorCode=1, errorMessage="Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. Error: type expected at the position 0 of '<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:<derived from deserializer>:string' but '<' is found."), operationHandle=None)
``` 

### Expected Behavior

Column added to the table

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:Linux Manjaro
- LocalStack:localstack/localstack-pro
```

**Comment by wassayd** [comment]
I also have the same probleme !

**Comment by whummer** [comment]
Hi @amineSt @wassayd , thanks for reporting. We have now pushed a few enhancements to improve the support for ALTER TABLE queries for different SerDe implementations (including `org.apache.hadoop.hive.serde2.OpenCSVSerde`).

Can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

**Comment by whummer** [comment]
Hi @amineSt , closing this issue as resolved - please let us know if the problem persists. Thanks!
