### ISSUE TITLE
bug: error with java11 lambda executing locally

### ISSUE THREAD

**Issue by nicofari** [localstack/localstack#8110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Invoking the lambda gives this error in localstack logs:

Executing command: ['unzip', '-o', '-q', '/tmp/tmpu3xd8b03']
multiprinter-localstack-1  | 2023-04-11T07:36:20.906 DEBUG --- [Executor-1_0] l.s.a.i.docker_runtime_exe : Version preparation of version arn:aws:lambda:eu-west-1:000000000000:function:multiprinter:$LATEST took 209.35ms
multiprinter-localstack-1  | 2023-04-11T07:36:20.907 DEBUG --- [Executor-1_0] l.s.a.i.version_manager    : Changing Lambda 'arn:aws:lambda:eu-west-1:000000000000:function:multiprinter:$LATEST' (id 5fab5ad3) to active
multiprinter-localstack-1  | 2023-04-11T07:36:20.907 DEBUG --- [Executor-1_1] l.s.a.i.version_manager    : Stopping lambda version 'arn:aws:lambda:eu-west-1:000000000000:function:multiprinter:$LATEST'
multiprinter-localstack-1  | 2023-04-11T07:36:20.907 DEBUG --- [functhread18] l.s.a.i.version_manager    : Invocation loop for lambda arn:aws:lambda:eu-west-1:000000000000:function:multiprinter:$LATEST stopped while waiting for invocations
multiprinter-localstack-1  | 2023-04-11T07:36:20.907 DEBUG --- [Executor-1_2] l.s.a.i.lambda_models      : Final code destruction for multiprinter-0be602f9-721d-46b4-aea0-5e1ae8c89359
multiprinter-localstack-1  | 2023-04-11T07:36:20.908 DEBUG --- [Executor-1_1] l.s.a.i.version_manager    : Thread stopped 'arn:aws:lambda:eu-west-1:000000000000:function:multiprinter:$LATEST'
multiprinter-localstack-1  | 2023-04-11T07:36:30.153  WARN --- [   asgi_gw_1] localstack.aws.accounts    : Ignoring production AWS credentials provided to LocalStack. Falling back to default account ID.
multiprinter-localstack-1  | 2023-04-11T07:36:30.155  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS lambda.GetFunction => 200
multiprinter-localstack-1  | 2023-04-11T07:37:10.636 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain
multiprinter-localstack-1  | Traceback (most recent call last):
multiprinter-localstack-1  |   File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
multiprinter-localstack-1  |     handler(self, self.context, response)
multiprinter-localstack-1  |   File "/opt/code/localstack/localstack/aws/handlers/routes.py", line 27, in __call__
multiprinter-localstack-1  |     router_response = self.router.dispatch(context.request)
multiprinter-localstack-1  |   File "/opt/code/localstack/localstack/http/router.py", line 440, in dispatch
multiprinter-localstack-1  |     return self.dispatcher(request, handler, args)
multiprinter-localstack-1  |   File "/opt/code/localstack/localstack/http/dispatcher.py", line 70, in _dispatch
multiprinter-localstack-1  |     result = endpoint(request, **args)
multiprinter-localstack-1  |   File "/opt/code/localstack/localstack/services/awslambda/urlrouter.py", line 77, in handle_lambda_url_invocation
multiprinter-localstack-1  |     match = FULL_FN_ARN_PATTERN.search(lambda_url_config.function_arn).groupdict()
multiprinter-localstack-1  | AttributeError: 'NoneType' object has no attribute 'function_arn'
multiprinter-localstack-1  | 2023-04-11T07:37:10.643  INFO --- [   asgi_gw_1] localstack.request.http    : POST /payment-render => 500

### How are you starting LocalStack?

With a docker-compose file

#### docker-compose.yml

version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - DEBUG=1
      - DEFAULT_REGION=eu-west-1
      - SERVICES=lambda,logs
      - LAMBDA_EXECUTOR=local
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volume:/volume

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

aws --endpoint-url=http://localhost:4566 \
lambda create-function --function-name multiprinter \
--memory-size 512 \
--zip-file fileb://mycode.zip \
--tracing-config Mode=Active \
--timeout 900 \
--environment Variables={NB_PORT="9001",NB_OUTPUT_PATH="/output}" \
--handler it.multidialogo.multiprinter.MyAwsLambdaExposedFunction --runtime java11 \
--role arn:aws:iam::000000000000:role/lambda-role

### Environment

```markdown
- OS: ubuntu 18.04
- LocalStack: 2.0.1.dev
```

### Anything else?

My function tries to write in a folder (the volume mapped resource you see in the docker compose yaml)

**Comment by nicofari** [comment]
Sorry my fault I forgot to create the function url
