### ISSUE TITLE
KCL SDKClientException: Unable to execute HTTP request: The target server failed to respond

### ISSUE THREAD

**Issue by justinborromeo-toast** [localstack/localstack#813]
I'm using the Kinesis Client Library to run Integration Tests against a Kinesis stream running locally using LocalStack.  The LocalStack container is running with SSL enabled as the Kinesis Producer Library requires that.  When I try to connect to my local kinesis streams and list the stream names, I receive `SDKClientException: Unable to execute HTTP request: The target server failed to respond` and `Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond` errors.`

My code is as follows:
````
@RunWith(LocalstackDockerTestRunner.class)
@LocalstackDockerProperties(services={"kinesis"}, environmentVariableProvider = LocalstackEnvironmentVariableProvider.class)
public class EmafIT{
    @Before
        public void setup() throws Exception {
            AmazonKinesis kinesis = DockerTestUtils.getClientKinesis();
            ListStreamsResult streams = kinesis.listStreams();
        }
}
````

Is this an issue with how I set my KCL or Localstack up?

If you need any more info, let me know.

UPDATE:

I tried running the sample test provided in the README and I'm getting 502 Bad Gateway responses.

````
import cloud.localstack.DockerTestUtils;
import cloud.localstack.docker.LocalstackDockerTestRunner;
import cloud.localstack.docker.annotation.LocalstackDockerProperties;
import com.amazonaws.services.kinesis.AmazonKinesis;
import com.amazonaws.services.kinesis.model.ListStreamsResult;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(LocalstackDockerTestRunner.class)
@LocalstackDockerProperties(services = { "kinesis"})
public class MyIT {
    @Test
    public void testKinesis() {
        AmazonKinesis kinesis = DockerTestUtils.getClientKinesis();

        ListStreamsResult streams = kinesis.listStreams();
        for(String stream : streams.getStreamNames()){
            String asdf = stream;
        }
    }
}
````

**Comment by bobtiernay-okta** [comment]
I'm also hitting this issue using `0.11.0` and KCL:
```
[ 29-04-2020 14:06:17.777 ] [ LeaseCoordinator-0000 ] [ ERROR ] [ LeaseRenewer ] - Encountered an exception while renewing a lease.
com.amazonaws.services.kinesis.leases.exceptions.DependencyException: com.amazonaws.SdkClientException: Unable to execute HTTP request: The target server failed to respond
	at com.amazonaws.services.kinesis.leases.impl.LeaseManager.convertAndRethrowExceptions(LeaseManager.java:578)
	at com.amazonaws.services.kinesis.leases.impl.LeaseManager.renewLease(LeaseManager.java:391)
	at com.amazonaws.services.kinesis.leases.impl.LeaseRenewer.renewLease(LeaseRenewer.java:176)
	at com.amazonaws.services.kinesis.leases.impl.LeaseRenewer.renewLease(LeaseRenewer.java:159)
	at com.amazonaws.services.kinesis.leases.impl.LeaseRenewer.access$000(LeaseRenewer.java:49)
	at com.amazonaws.services.kinesis.leases.impl.LeaseRenewer$RenewLeaseTask.call(LeaseRenewer.java:151)
	at com.amazonaws.services.kinesis.leases.impl.LeaseRenewer$RenewLeaseTask.call(LeaseRenewer.java:137)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: The target server failed to respond
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1189)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1135)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:784)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:752)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2186)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2162)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeUpdateItem(AmazonDynamoDBClient.java:1908)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.updateItem(AmazonDynamoDBClient.java:1884)
	at com.amazonaws.services.kinesis.leases.impl.LeaseManager.renewLease(LeaseManager.java:382)
	... 9 common frames omitted
Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1311)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1127)
	... 21 common frames omitted
```

Curious why this was closed @justinborromeo-toast?

**Comment by bobtiernay-okta** [comment]
Could this be related to https://github.com/localstack/localstack/blob/50926669d1ec003c04971c2c156c4d1c94a2c00f/localstack/services/generic_proxy.py#L178-L181 ?

**Comment by bobtiernay-okta** [comment]
For the benefit of others, I was able to workaround this issue by configuring the client as follows:

```java
AmazonDynamoDBClientBuilder.standard()
                    .withClientConfiguration(
                            new ClientConfiguration()
                                    .withValidateAfterInactivityMillis(200))
```
