### ISSUE TITLE
bug: Unable to deploy static website with S3, CloudFront and custom domain

### ISSUE THREAD

**Issue by dzmitry-kankalovich** [localstack/localstack#8136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a personal website deployed as a static website on S3 with CF distribution and custom domain attached - all via AWS CDK (Typescript).

The site is live and works just fine when I am using real AWS API.

However when I attempt to deploy my CDK project to the `localstack` - I always get timeout error related to one of CDK lambda functions. 

The whole stack source is this:
```typescript
import {
  Stack,
  StackProps,
  CfnOutput,
  RemovalPolicy,
  aws_s3 as s3,
  aws_s3_deployment as s3deploy,
  aws_route53 as route53,
  aws_route53_targets as targets,
  aws_cloudfront as cloudfront,
} from 'aws-cdk-lib';
import {SecurityPolicyProtocol, ViewerCertificate} from "aws-cdk-lib/aws-cloudfront";
import {Certificate} from "aws-cdk-lib/aws-certificatemanager";
import {Construct} from "constructs";

interface CvSiteProps extends StackProps {
  domainName: string,
  certificateArn: string
}

export class CvSiteStack extends Stack {
  constructor(scope: Construct, id: string, props: CvSiteProps) {
    super(scope, id, props);

    const domainName = props.domainName
    const certificateArn = props.certificateArn
    new CfnOutput(this, 'Site', {value: 'https://' + domainName});

    const zone = route53.HostedZone.fromLookup(this, 'CvZone', {domainName: domainName});

    // Content bucket
    const siteBucket = new s3.Bucket(this, 'CvSiteBucket', {
      bucketName: domainName,
      websiteIndexDocument: 'index.html',
      websiteErrorDocument: 'error.html',
      publicReadAccess: true,

      // The default removal policy is RETAIN, which means that cdk destroy will not attempt to delete
      // the new bucket, and it will remain in your account until manually deleted. By setting the policy to
      // DESTROY, cdk destroy will attempt to delete the bucket, but will error if the bucket is not empty.
      removalPolicy: RemovalPolicy.RETAIN, // NOT recommended for production code
    });
    new CfnOutput(this, 'SiteBucket', {value: siteBucket.bucketName});

    const certificate = Certificate.fromCertificateArn(
      this,
      'CvSiteCertificate',
      certificateArn);
    // CloudFront distribution that provides HTTPS
    const distribution
      = new cloudfront.CloudFrontWebDistribution(this, 'CvSiteDistribution', {
      viewerCertificate: ViewerCertificate.fromAcmCertificate(certificate, {
        aliases: [domainName],
        securityPolicy: SecurityPolicyProtocol.TLS_V1_2_2021,
      }),
      originConfigs: [
        {
          customOriginSource: {
            domainName: siteBucket.bucketWebsiteDomainName,
            originProtocolPolicy: cloudfront.OriginProtocolPolicy.HTTP_ONLY,
          },
          behaviors: [{isDefaultBehavior: true}],
        }
      ],
    });
    new CfnOutput(this, 'CvDistributionId', {value: distribution.distributionId});

    // Route53 alias record for the CloudFront distribution
    new route53.ARecord(this, 'CvSiteAliasRecord', {
      recordName: domainName,
      target: route53.RecordTarget.fromAlias(new targets.CloudFrontTarget(distribution)),
      zone
    });

    //  // Deploy site contents to S3 bucket
    new s3deploy.BucketDeployment(this, 'CvSiteDeployWithInvalidation', {
      sources: [s3deploy.Source.asset('../site/public')],
      destinationBucket: siteBucket,
      distribution,
      distributionPaths: ['/*'],
    });
  }
}
```

The CDK deployment fails with just generic `failed to deploy: CREATE_FAILED`

However upon inspecting debug logs I can see that main container has following entries:
```
2023-04-13T11:25:22.758 DEBUG --- [   asgi_gw_5] l.s.a.i.version_manager    : >   warnings.warn(
2023-04-13T11:25:22.758 DEBUG --- [   asgi_gw_5] l.s.a.i.version_manager    : > [ERROR]	2023-04-13T11:25:22.648Z	795e356f-2c8d-4d85-89d6-70a9f4e65439	Waiter InvalidationCompleted failed: Max attempts exceeded
2023-04-13T11:25:22.758 DEBUG --- [   asgi_gw_5] l.s.a.i.version_manager    : > Traceback (most recent call last):
2023-04-13T11:25:22.758 DEBUG --- [   asgi_gw_5] l.s.a.i.version_manager    : >   File "/var/task/index.py", line 121, in handler
2023-04-13T11:25:22.758 DEBUG --- [   asgi_gw_5] l.s.a.i.version_manager    : >     cloudfront_invalidate(distribution_id, distribution_paths)
2023-04-13T11:25:22.758 DEBUG --- [   asgi_gw_5] l.s.a.i.version_manager    : >   File "/var/task/index.py", line 206, in cloudfront_invalidate
2023-04-13T11:25:22.758 DEBUG --- [   asgi_gw_5] l.s.a.i.version_manager    : >     cloudfront.get_waiter('invalidation_completed').wait(
2023-04-13T11:25:22.759 DEBUG --- [   asgi_gw_5] l.s.a.i.version_manager    : >   File "/var/runtime/botocore/waiter.py", line 55, in wait
2023-04-13T11:25:22.759 DEBUG --- [   asgi_gw_5] l.s.a.i.version_manager    : >     Waiter.wait(self, **kwargs)
2023-04-13T11:25:22.759 DEBUG --- [   asgi_gw_5] l.s.a.i.version_manager    : >   File "/var/runtime/botocore/waiter.py", line 388, in wait
2023-04-13T11:25:22.759 DEBUG --- [   asgi_gw_5] l.s.a.i.version_manager    : >     raise WaiterError(
2023-04-13T11:25:22.759 DEBUG --- [   asgi_gw_5] l.s.a.i.version_manager    : > botocore.exceptions.WaiterError: Waiter InvalidationCompleted failed: Max attempts exceeded[ERROR]	2023-04-13T11:25:22.656Z	795e356f-2c8d-4d85-89d6-70a9f4e65439	| cfn_error: Waiter InvalidationCompleted failed: Max attempts exceeded
2023-04-13T11:25:22.759 DEBUG --- [   asgi_gw_5] l.s.a.i.version_manager    : > [INFO]	2023-04-13T11:25:22.659Z	795e356f-2c8d-4d85-89d6-70a9f4e65439	| response body:
2023-04-13T11:25:22.759 DEBUG --- [   asgi_gw_5] l.s.a.i.version_manager    : > {"Status": "FAILED", "Reason": "Waiter InvalidationCompleted failed: Max attempts exceeded", "PhysicalResourceId": "2023/04/13/[$LATEST]0ffdc6b700074a0c652b79e9847229f8", "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/CvSite/id-123", "RequestId": "b326dc20", "LogicalResourceId": "CvSiteDeployWithInvalidationCustomResourceF28230A9", "NoEcho": false, "Data": {}}
```

It seems like lambda container executes logic for CF distro invalidation and fails to do so. 

This may or may not be related to https://github.com/aws/aws-cdk/issues/15891

I wonder if there is any workaround to this?
 

### Expected Behavior

Deployment finishes without problems.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack 
```
localstack start
```
#### Client commands 
```
awslocal route53 create-hosted-zone --name ${DOMAIN_NAME} --caller-reference r1
./create-local-acm-certificate.sh ${DOMAIN_NAME} # see the exact snippet at https://gist.github.com/andrewodri/1d3c25b01f2b7b307f4b7b538ef36fff
cdklocal bootstrap aws://${AWS_ACCOUNT_ID_LOCAL}/${AWS_REGION}
CERTIFICATE_ARN=$$(awslocal acm list-certificates | jq -r '.CertificateSummaryList[0].CertificateArn') cdklocal deploy --all
```

### Environment

```markdown
- OS: macOS 13.3 (22E252)
- LocalStack: 2.0.1
- CDK: 2.73.0
```

**Comment by amay077** [comment]
I have same issue.

- https://stackoverflow.com/questions/72791021/localstack-with-cdk-is-not-deploying-directory-to-s3-bucket
- https://github.com/aws/aws-cdk/issues/21014

@dominikschubert  Does localstack supports BucketDeployment with aws cdk?

**Comment by amay077** [comment]
I understood that this is a feature that **can only be used with the Pro version**.

```
localstack_myapp01  | 2024-07-05T05:49:00.141  WARN --- [functhread44] l.s.c.deployment_utils     
  : No resource provider found for "Custom::CDKBucketDeployment". 
  To find out if Custom::CDKBucketDeployment is supported in LocalStack Pro, 
  please check out our docs at https://docs.localstack.cloud/user-guide/aws/cloudformation/#resources-pro--enterprise-edition

```
