### ISSUE TITLE
LocalStack with Docker Desktop wont start

### ISSUE THREAD

**Issue by pramineni01** [localstack/localstack#8164]
LocalStack with Docker Desktop wont start

Env:
Tried on 2 Macbook Pros (Apple chip and Intel chip)
Steps to reproduce:
1. Installed localstack extension for Docker Desktop.
2.Clicked on Start. And am seeing the error below:

2023-04-19T04:34:20.538 INFO --- [-functhread1] localstack.utils.threads : Thread run method <function Server.do_start_thread.<locals>._run at 0xffff8a4683a0>(None) failed: Traceback (most recent call last): File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status response.raise_for_status() File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.41/containers/create?name=localstack_main The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 613, in create_container container = create_container() File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 594, in create_container return self.client().containers.create( File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/models/containers.py", line 906, in create resp = self.client.api.create_container(**create_kwargs) File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/container.py", line 431, in create_container return self.create_container_from_config(config, name, platform) File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/container.py", line 448, in create_container_from_config return self._result(res, True) File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result self._raise_for_status(response) File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status raise create_api_error_from_http_exception(e) from e File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception raise cls(e, response=response, explanation=explanation) from e docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=localstack_main: Conflict ("Conflict. The container name "/localstack_main" is already in use by container "9d65f950461eeb8a86b986ef8626392372b66c82d36cd5cfc12baa64af18099a". You have to remove (or rename) that container to be able to reuse that name.") The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/opt/code/localstack/localstack/utils/threads.py", line 58, in run result = self.func(self.params, **kwargs) File "/opt/code/localstack/localstack/utils/serving.py", line 168, in _run return self.do_run() File "/opt/code/localstack/localstack/utils/bootstrap.py", line 475, in do_run return self.container.run() File "/opt/code/localstack/localstack/utils/bootstrap.py", line 407, in run return DOCKER_CLIENT.run_container( File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 661, in run_container container = self.create_container( File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 621, in create_container raise ContainerException() from e localstack.utils.container_utils.container_client.ContainerException

**Comment by MarcelStranak** [comment]
Hi @pramineni01, 

As the error indicates, please clear the previously started container. Open the Docker Desktop > Containers section, delete “localstack_main”. You will then be able to start a new LocalStack instance from the LocalStack Extension.

```("Conflict. The container name "/localstack_main" is already in use by container "9d65f950461eeb8a86b986ef8626392372b66c82d36cd5cfc12baa64af18099a". You have to remove (or rename) that container to be able to reuse that name.")```

**Comment by pramineni01** [comment]
When i list the images docker does not show any image by that name.
Did anyone try the steps on a macbook? Its happening consistently on 2 machines for me

**Comment by steffyP** [comment]
Hi @pramineni01,

thanks for reaching out! I was able to reproduce your issue, thanks for making is aware! 🙏 

Could you please go to the settings in your Docker Desktop app and enable the following:
`Settings -> Extensions -> Show Docker Extensions system containers in docker desktop`

You should then be able to start and see the running LocalStack container. 
Could you please let us know if this works for you?

**Comment by sergei-dorofeev** [comment]
The issue still have place, it wasn't solved.

**Comment by alanzhao81** [comment]
Same issue

**Comment by steffyP** [comment]
Hi @sergei-dorofeev, hi @alanzhao81,

please make sure you use the latest version of the extension `0.5.2`, and that you enabled the settings correctly for `Extensions` (see screenshot). 

![Screenshot 2023-12-15 at 10 55 44](https://github.com/localstack/localstack/assets/5726672/c10d899d-2541-4a9d-addf-42d79454cbf2)


If you still experience issues, please provide more details, including the OS you are on, the docker-desktop version, the localstack-extension version and non-default settings in docker-desktop you may have.

**Comment by GeneralNitin** [comment]
Hi,

I am having issue while running localstack on my machine.
So, I wanted to run localstack on docker and immediately run a script to created resources. I found a reference from [StackOverflow](https://stackoverflow.com/questions/53563942/running-shell-script-against-localstack-in-docker-container) and the [official docs](https://docs.localstack.cloud/references/init-hooks/#:~:text=Copy-,Start%20Localstack%3A,-docker%2Dcompose.yml) and made it to.
It worked fine on my trial project, but when I tried to run the same with my actual project, I am facing an error and now my trail project is also not working.

I have tried deleting the images, container, volumes but still facing the issue, please suggest where I am going wrong.



<details>

<summary>Error:</summary>

```
2024-06-17T07:48:20.252 DEBUG --- [ady_monitor)] localstack.runtime.init    : Running READY script /etc/localstack/init/ready.d/setup-localstack.sh
localstack-lol  | Starting LocalStack
localstack-lol  | 
localstack-lol  |      __                     _______ __             __
localstack-lol  |     / /   ____  _________ _/ / ___// /_____ ______/ /__
localstack-lol  |    / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
localstack-lol  |   / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
localstack-lol  |  /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|
localstack-lol  | 
localstack-lol  |  💻 LocalStack CLI 3.5.1.dev
localstack-lol  |  👤 Profile: default
localstack-lol  | 
localstack-lol  | [07:48:20] starting LocalStack in Docker mode 🐳               localstack.py:503
localstack-lol  |            preparing environment                               bootstrap.py:1283
localstack-lol  |            configuring container                               bootstrap.py:1291
localstack-lol  |            starting container                                  bootstrap.py:1301
localstack-lol  | Error while starting LocalStack container: Error during the communication with the docker daemon
localstack-lol  | None
localstack-lol  | Traceback (most recent call last):
localstack-lol  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/api/client.py", line 275, in _raise_for_status
localstack-lol  |     response.raise_for_status()
localstack-lol  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
localstack-lol  |     raise HTTPError(http_error_msg, response=self)
localstack-lol  | requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.45/containers/0526e372948c6f311eb931963ee8b0ddf8e5e93f6fa2e8b6747a4287f64ec397/start
localstack-lol  | 
localstack-lol  | The above exception was the direct cause of the following exception:
localstack-lol  | 
localstack-lol  | Traceback (most recent call last):
localstack-lol  |   File "/opt/code/localstack/localstack-core/localstack/utils/container_utils/docker_sdk_client.py", line 589, in start_container
localstack-lol  |     container.start()
localstack-lol  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/models/containers.py", line 420, in start
localstack-lol  |     return self.client.api.start(self.id, **kwargs)
localstack-lol  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-lol  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/utils/decorators.py", line 19, in wrapped
localstack-lol  |     return f(self, resource_id, *args, **kwargs)
localstack-lol  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-lol  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/api/container.py", line 1136, in start
localstack-lol  |     self._raise_for_status(res)
localstack-lol  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/api/client.py", line 277, in _raise_for_status
localstack-lol  |     raise create_api_error_from_http_exception(e) from e
localstack-lol  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-lol  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
localstack-lol  |     raise cls(e, response=response, explanation=explanation) from e
localstack-lol  | docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.45/containers/0526e372948c6f311eb931963ee8b0ddf8e5e93f6fa2e8b6747a4287f64ec397/start: Internal Server Error ("Mounts denied: 
localstack-lol  | The path /root/.cache/localstack/volume is not shared from the host and is not known to Docker.
localstack-lol  | You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
localstack-lol  | See https://docs.docker.com/desktop/mac for more info.")
localstack-lol  | 
localstack-lol  | The above exception was the direct cause of the following exception:
localstack-lol  | 
localstack-lol  | Traceback (most recent call last):
localstack-lol  |   File "/opt/code/localstack/localstack-core/localstack/utils/bootstrap.py", line 879, in start
localstack-lol  |     self.container_client.start_container(id, attach=attach)
localstack-lol  |   File "/opt/code/localstack/localstack-core/localstack/utils/container_utils/docker_sdk_client.py", line 594, in start_container
localstack-lol  |     raise ContainerException() from e
localstack-lol  | localstack.utils.container_utils.container_client.ContainerException
localstack-lol  | 2024-06-17T07:48:28.304 DEBUG --- [et.reactor-0] l.a.p.service_router       : building service catalog index cache file /var/lib/localstack/cache/service-catalog-3_5_1_dev-1_34_122.pickle
Gracefully stopping... (press Ctrl+C again to force)
EOF
```

</details>


Here is my docker-compose file:
<details>
<summary>V1: When it worked</summary>
```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main2}"
    image: localstack/localstack
    ports:
      # - "127.0.0.1:4566:4566"
      - '4566-4583:4566-4583'
    environment:
      - DEBUG=1
    volumes:
      - "./setup-localstack.sh:/etc/localstack/init/ready.d/setup-localstack.sh"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
</details>

<details>
<summary>V2: When this trial also started failing, I made change to my docker-compose, but same error</summary>
```
services:
  localstack-lol:
    container_name: "localstack-lol"
    image: localstack/localstack
    ports:
      # - "127.0.0.1:4566:4566"
      - '4566-4583:4566-4583'
    environment:
      - DEBUG=1
    volumes:
      - "./setup-localstack.sh:/etc/localstack/init/ready.d/setup-localstack.sh"
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
</details>

**Comment by steffyP** [comment]
Hi @GeneralNitin,
the issue you describe seems not to be related to the original reported issue here (e.g. it's not related to the Docker Desktop). Could you please create a new ticket for your issue so we can properly track and triage the issue. 
Thank you!
