### ISSUE TITLE
bug: S3(Access Denied) while trying to save file with PySpark/Apache Hudi

### ISSUE THREAD

**Issue by danfran** [localstack/localstack#8193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have the following configuration for my PySpark/Apache Hudi tests that run inside the Docker container `amazon/aws-glue-libs:glue_libs_4.0.0_image_01`:

```
conf = SparkConf()\
        .set('spark.jars', '/home/glue_user/spark/jars/spark-avro_2.12-3.3.0-amzn-1.jar,'
                           '/home/glue_user/aws-glue-libs/datalake-connectors/hudi-0.12.1/hudi-spark3-bundle_2.12-0.12.1.jar,'
                           '/home/glue_user/aws-glue-libs/jars/aws-java-sdk-1.12.128.jar,'
                           '/home/glue_user/aws-glue-libs/jars/aws-java-sdk-glue-1.12.128.jar,'
                           '/home/glue_user/spark/jars/hadoop-aws-3.3.3-amzn-0.jar'
             )\
        .set('spark.serializer', 'org.apache.spark.serializer.KryoSerializer')\
        .set('spark.sql.extensions', 'org.apache.spark.sql.hudi.HoodieSparkSessionExtension')
    spark_context = SparkContext(conf=conf)
    glue_context = GlueContext(spark_context)
    spark_session = glue_context.spark_session

    # HUDI S3 ACCESS
    spark_session.conf.set('fs.defaultFS', 's3://my_bucket')
    spark_session.conf.set('fs.s3.awsAccessKeyId', 'test')
    spark_session.conf.set('fs.s3.awsSecretAccessKey', 'test')
    spark_session.conf.set('fs.s3a.awsAccessKeyId', 'test')
    spark_session.conf.set('fs.s3a.awsSecretAccessKey', 'test')
    spark_session.conf.set('fs.s3a.endpoint', os.environ['EC2_ENDPOINT'])
    spark_session.conf.set('fs.s3a.connection.ssl.enabled', 'false')
    spark_session.conf.set('fs.s3a.path.style.access', 'true')
    spark_session.conf.set('fs.s3a.signing-algorithm', 'S3SignerType')
    spark_session.conf.set('spark.sql.legacy.setCommandRejectsSparkCoreConfs', 'false')

    spark_session.conf.set('spark.sql.shuffle.partitions', '2')
    spark_session.conf.set('spark.sql.crossJoin.enabled', 'true')
```

and when data get saved, I receive back the following error:

```
Py4JJavaError
An error occurred while calling o451.save.
: java.nio.file.AccessDeniedException: s3://my_bucket/my_path/my_data/.hoodie: getFileStatus on s3://my_bucket/my_path/my_data/.hoodie: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: C165R98PY0YKVSJ0; S3 Extended Request ID: IEzppjrFTbRadA3RBAThq6ejQ5ssZcMLPhLN0i43UiD5O+41xYB2odhA0xCwy1/Soio79gax3OTjevjudSMtOg==; Proxy: null), S3 Extended Request ID: IEzppjrFTbRadA3RBAThq6ejQ5ssZcMLPhLN0i43UiD5O+41xYB2odhA0xCwy1/Soio79gax3OTjevjudSMtOg==:403 Forbidden
        at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:255)
        at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:175)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:3796)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.innerGetFileStatus(S3AFileSystem.java:3688)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$exists$34(S3AFileSystem.java:4703)
        at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.lambda$trackDurationOfOperation$5(IOStatisticsBinding.java:499)
        at org.apache.hadoop.fs.statistics.impl.IOStatisticsBinding.trackDuration(IOStatisticsBinding.java:444)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.trackDurationAndSpan(S3AFileSystem.java:2337)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.trackDurationAndSpan(S3AFileSystem.java:2356)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.exists(S3AFileSystem.java:4701)
        at org.apache.hudi.HoodieSparkSqlWriter$.write(HoodieSparkSqlWriter.scala:86)
        at org.apache.hudi.DefaultSource.createRelation(DefaultSource.scala:144)
        at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:103)
        at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
        at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:224)
        at org.apache.spark.sql.execution.SQLExecution$.executeQuery$1(SQLExecution.scala:114)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$7(SQLExecution.scala:139)
        at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
        at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:224)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:139)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:245)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:138)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:68)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:100)
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:96)
        at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:615)
        at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:177)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:615)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
        at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
        at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:591)
        at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:96)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:83)
        at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:81)
        at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:124)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:860)
        at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:390)
        at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:363)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:239)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.lang.Thread.run(Thread.java:750)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: C165R98PY0YKVSJ0; S3 Extended Request ID: IEzppjrFTbRadA3RBAThq6ejQ5ssZcMLPhLN0i43UiD5O+41xYB2odhA0xCwy1/Soio79gax3OTjevjudSMtOg==; Proxy: null), S3 Extended Request ID: IEzppjrFTbRadA3RBAThq6ejQ5ssZcMLPhLN0i43UiD5O+41xYB2odhA0xCwy1/Soio79gax3OTjevjudSMtOg==
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1862)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1415)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1384)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5453)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5400)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1372)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.lambda$getObjectMetadata$10(S3AFileSystem.java:2545)
        at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:414)
        at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:377)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.getObjectMetadata(S3AFileSystem.java:2533)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.getObjectMetadata(S3AFileSystem.java:2513)
        at org.apache.hadoop.fs.s3a.S3AFileSystem.s3GetFileStatus(S3AFileSystem.java:3776)
        ... 56 more
```

so the issue looks related to the process trying to read back the metadata file `.hoodie`.

### Expected Behavior

Save both data and metadata info.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    `docker-compose.yml`: 

```
  localstack:
        container_name: localstack
        environment:
          DEBUG: 1
          LOCALSTACK_API_KEY: "{LOCALSTACK_API_KEY- }"
          SERVICES: "s3,cloudwatch"
        image: "localstack/localstack:latest"
        ports:
          - "53:53"
          - "443:443"
          - "4510-4520:4510-4520"
          - "4566-4620:4566-4620"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
 data_frame.write\
            .format('hudi')\
            .options(**hudi_options)\
            .mode(write_mode) \
            .save(target_uri)
```

### Environment

```markdown
- OS: MacOS Catalina v10.15.7
- LocalStack: latest
```

**Comment by bentsku** [comment]
Hi @danfran and thanks for your report!

From the 403 error, it could be that Hudi is trying to access the real AWS and not LocalStack. Could you share LocalStack logs when this error happens? You set the verbosity a bit higher by starting LocalStack with `LS_LOG=trace` and `DEBUG=1`. Thanks!

**Comment by danfran** [comment]
Hi @bentsku yes I had the same thought as from the full logs:

```
2023-04-25 16:39:06 2023-04-25T15:39:06.641  WARN --- [   asgi_gw_0] localstack.deprecations    : /health is deprecated (since 1.3.0) and will be removed in upcoming releases of LocalStack! Use /_localstack/health instead.
2023-04-25 16:39:07 2023-04-25T15:39:07.715  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.HeadBucket => 200
2023-04-25 16:39:07 2023-04-25T15:39:07.801  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.ListObjects => 200
2023-04-25 16:39:07 2023-04-25T15:39:07.816  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.DeleteObject => 204
2023-04-25 16:39:07 2023-04-25T15:39:07.825  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.DeleteObject => 204
2023-04-25 16:39:07 2023-04-25T15:39:07.835  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.DeleteObject => 204
2023-04-25 16:39:07 2023-04-25T15:39:07.847  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.DeleteBucket => 204
2023-04-25 16:39:07 2023-04-25T15:39:07.876  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.CreateBucket => 200
2023-04-25 16:39:07 2023-04-25T15:39:07.885  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.HeadBucket => 200
2023-04-25 16:39:07 2023-04-25T15:39:07.893  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.ListObjects => 200
2023-04-25 16:39:07 2023-04-25T15:39:07.901  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.DeleteBucket => 204
2023-04-25 16:39:07 2023-04-25T15:39:07.915  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.CreateBucket => 200
2023-04-25 16:39:07 2023-04-25T15:39:07.923  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.HeadBucket => 200
2023-04-25 16:39:07 2023-04-25T15:39:07.931  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.ListObjects => 200
2023-04-25 16:39:07 2023-04-25T15:39:07.939  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.DeleteBucket => 204
2023-04-25 16:39:07 2023-04-25T15:39:07.949  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.CreateBucket => 200
```

I can see only a part of the requests.

**Comment by bentsku** [comment]
I'll close the issue as this is related to a 3rd party library. Feel free to reopen if you have more informations concerning the issue. There is however some movement regarding configuration of the SDK endpoints, as we can see with https://github.com/aws/aws-sdk/issues/229#issuecomment-1626187889 and https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html. It is not available for Java yet, but let's hope it is coming soon!
