### ISSUE TITLE
bug: Localstack EMR library versions seem to be mismatched from cloud AWS EMR 

### ISSUE THREAD

**Issue by vdonets99** [localstack/localstack#8241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I create an EMR-6.7.0 cluster in Localstack it runs with Spark 3.1.2 and Hadoop 3.3.1.

### Expected Behavior

It should run with Spark 3.2.1 and Hadoop 3.2.1 as described here - https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-670-release.html

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    Docker compose with docker-compose.yml - 

```
version: "3.3"
services:
  localstack:
    image: localstack/localstack-pro:2.0.2
    environment:
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DEBUG=1
      - LOCALSTACK_API_KEY=.....
    ports:
      - '4566-4583:4566-4583'
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
    aws --endpoint-url=http://localhost:4566 emr create-cluster \
       --release-label "emr-6.7.0" \
       --configurations .... \
       --instance-groups ....\
       etc.... 
```

### Environment

```markdown
- OS: Mac OS (M1)
- LocalStack: 2.0.2
```

### Anything else?

Container will eventually log following lines:

```
uruyqbsgy7un-localstack-1  | 2023-05-03T06:15:52.482 DEBUG --- [functhread12] localstack.packages.api    : Starting installation of hadoop...
uruyqbsgy7un-localstack-1  | 2023-05-03T06:15:53.291 DEBUG --- [functhread12] localstack.utils.http      : Starting download from https://downloads.apache.org/hadoop/common/hadoop-3.3.1/hadoop-3.3.1.tar.gz to /var/lib/localstack/tmp/hadoop-3.3.1.tar.gz (605187279 bytes)
```
and 
```
uruyqbsgy7un-localstack-1  | 2023-05-03T06:18:05.325 DEBUG --- [functhread12] localstack.packages.api    : Starting installation of spark...
uruyqbsgy7un-localstack-1  | 2023-05-03T06:18:06.163 DEBUG --- [functhread12] localstack.utils.http      : Starting download from https://archive.apache.org/dist/spark/spark-3.1.2/spark-3.1.2-bin-without-hadoop.tgz to /var/lib/localstack/tmp/spark-3.1.2-bin-without-hadoop.tgz (160919814 bytes)
```

We can also check both versions in the container's lib directory (there are also 2 versions of spark installed for some reason):
```
user@host uruYQbSgY7un % docker ps
CONTAINER ID   IMAGE                             COMMAND                  CREATED          STATUS                    PORTS                                                                                                                           NAMES
c288dd1d4ad2   localstack/localstack-pro:2.0.2   "docker-entrypoint.sh"   13 minutes ago   Up 13 minutes (healthy)   127.0.0.1:53->53/tcp, 4510-4559/tcp, 127.0.0.1:443->443/tcp, 127.0.0.1:53->53/udp, 5678/tcp, 0.0.0.0:4566-4583->4566-4583/tcp   uruyqbsgy7un-localstack-1
user@host uruYQbSgY7un % docker exec -ti c288dd1d4ad2 bash
root@c288dd1d4ad2:/opt/code/localstack# cd /
.dockerenv  boot/       home/       mnt/        root/       srv/        usr/
.npm/       dev/        lib/        opt/        run/        sys/        var/
bin/        etc/        media/      proc/       sbin/       tmp/
root@c288dd1d4ad2:/opt/code/localstack# cd /var/lib/localstack/lib/
root@c288dd1d4ad2:/var/lib/localstack/lib# ls -l
total 16
drwxr-xr-x 2 root root 4096 May  3 06:19 bigdata-jars
drwxr-xr-x 2 root root 4096 May  3 06:19 gluePyspark
drwxr-xr-x 3 root root 4096 May  3 06:17 hadoop
drwxr-xr-x 4 root root 4096 May  3 06:18 spark
root@c288dd1d4ad2:/var/lib/localstack/lib# cd hadoop
root@c288dd1d4ad2:/var/lib/localstack/lib/hadoop# ls -l
total 4
**drwxr-xr-x 10 localstack localstack 4096 Jun 15  2021 3.3.1**
root@c288dd1d4ad2:/var/lib/localstack/lib/hadoop# cd ../spark
root@c288dd1d4ad2:/var/lib/localstack/lib/spark# ls -l
total 8
**drwxr-xr-x 13 localstack localstack 4096 May  1  2019 2.4.3
drwxr-xr-x 13 localstack localstack 4096 May 24  2021 3.1.2**
```

I am also having issues with a JAR that works just fine in AWS cloud EMR that Im trying to run locally dying with following exception:

`Exception in thread "main" org.apache.hadoop.yarn.exceptions.YarnRuntimeException: java.lang.reflect.InvocationTargetException
` 
that is caused by 
```
Caused by: java.lang.reflect.InvocationTargetException
  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
  at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
  at org.apache.hadoop.yarn.factories.impl.pb.RpcClientFactoryPBImpl.getClient(RpcClientFactoryPBImpl.java:78)
  ... 35 more
Caused by: java.lang.AbstractMethodError: Receiver class org.apache.hadoop.ipc.ProtobufRpcEngine2 does not define or inherit an implementation of the resolved method \'abstract org.apache.hadoop.ipc.ProtocolProxy getProxy(java.lang.Class, long, java.net.InetSocketAddress, org.apache.hadoop.security.UserGroupInformation, org.apache.hadoop.conf.Configuration, javax.net.SocketFactory, int, org.apache.hadoop.io.retry.RetryPolicy, java.util.concurrent.atomic.AtomicBoolean)\' of interface org.apache.hadoop.ipc.RpcEngine.
  at org.apache.hadoop.ipc.RPC.getProtocolProxy(RPC.java:583)
  at org.apache.hadoop.ipc.RPC.getProtocolProxy(RPC.java:549)
  at org.apache.hadoop.ipc.RPC.getProtocolProxy(RPC.java:496)
  at org.apache.hadoop.ipc.RPC.getProtocolProxy(RPC.java:461)
  at org.apache.hadoop.ipc.RPC.getProtocolProxy(RPC.java:647)
  at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:604)
  at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.<init>(ApplicationClientProtocolPBClientImpl.java:211)
  ... 40 more
```
I am not entirely convinced its specifically because of the Hadoop and Spark version mismatching, and Im not sure if any other libraries are different.

**Comment by HarshCasper** [comment]
Due to the forthcoming changes in our distribution and development model ([read more](https://blog.localstack.cloud/the-road-ahead-for-localstack/)), this issue tracker is no longer being maintained, and this issue is now being closed. If you'd like us to take a look or need further support, please reach out through one of our support channels:

-   💬 [GitHub Discussions](https://github.com/orgs/localstack/discussions)
-   📖 [Help & Support](https://docs.localstack.cloud/aws/getting-started/help-support/)
