### ISSUE TITLE
bug: s3.SelectObjectContent Does Not Support Nested JSON Objects

### ISSUE THREAD

**Issue by Trystan-C** [localstack/localstack#8249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Issuing `SelectObjectContentCommand` using the AWS Javascript SDK (`"@aws-sdk/client-s3": "^3.39.0"`) against a file of JSON lines containing nested JSON objects returns `500`.

### Expected Behavior

The request returns a `200` along with the expected content.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

 I'm using the following shell script to start `localstack`:
 ```shell
 #!/bin/sh

set -e

LOCALSTACK_CONTAINER_NAME="localstack-demo"

function stop_localstack() {
    echo "> Cleaning up localstack resources (if they exist)..."
    (docker container stop "${LOCALSTACK_CONTAINER_NAME}" >/dev/null 2>&1) || true
    (docker container rm "${LOCALSTACK_CONTAINER_NAME}" >/dev/null 2>&1) || true
}

function start_localstack() {
    echo "> Starting localstack resources..."

    docker run -it -d \
        -p 4566:4566 \
        --name="${LOCALSTACK_CONTAINER_NAME}" \
        localstack/localstack:2.0.2 >/dev/null

    echo "> Waiting for localstack to be ready..."
    check=0
    max_checks=12

    while true
    do
        localstack_log="$(docker logs ${LOCALSTACK_CONTAINER_NAME} | tail -n1 | tr -d '\r')"
        check=$(($check + 1))

        if [ "${localstack_log}" = "Ready." ]
        then
            echo "> Ready!"
            break
        else
            echo "> (${check}/${max_checks}) Waiting another 5 seconds..."
            sleep 5
        fi

        if [ "${check}" -ge "${max_checks}" ]
        then
            echo "> localstack was not ready in time"
            stop_localstack
            exit 1
        fi
    done
}

stop_localstack
start_localstack
 ```
 
 #### Demo
 
Using:

* `Node.js`: `16.16.0`
* `typescript`: `4.7.4`
* `@aws-sdk/client-s3`: `^3.39.0`
* `jest`: `28.1.3`
* `ts-jest`: `28.1.3`

```typescript
import {
    CreateBucketCommand,
    HeadObjectCommand,
    JSONType,
    PutObjectCommand,
    S3Client,
    SelectObjectContentCommand
} from "@aws-sdk/client-s3";

describe("Localstack Bug Demo", () => {
    describe("selecting content from an S3 object using the JSON output format", () => {
        it("does not return the content as JSON", async () => {
            const s3 = new S3Client({
                region: "us-west-2",
                endpoint: "https://s3.localhost.localstack.cloud:4566",
                credentials: {
                    accessKeyId: "AWSEXAMPLEKEY",
                    secretAccessKey: "AWSEXAMPLESECRET",
                },
            });

            // Create a new bucket.
            await s3.send(
                new CreateBucketCommand({
                    Bucket: "test-bucket"
                })
            );

            // Upload a small "JSON-line" file.
            const obj1 = { key: "value1", nested: { key: "value1" } };
            const obj2 = { key: "value2", nested: { key: "value2" } };
            await s3.send(
                new PutObjectCommand({
                    Bucket: "test-bucket",
                    Key: "test-file.jsonl",
                    Body: `${JSON.stringify(obj1)}\n${JSON.stringify(obj2)}\n`,
                })
            );

            // Determine the file's size in bytes for the "SelectObjectContent"
            // scan range.
            const sizeInBytes = (
                await s3.send(
                    new HeadObjectCommand({
                        Bucket: "test-bucket",
                        Key: "test-file.jsonl"
                    })
                )
            ).ContentLength!;

            // Attempt to select each JSON object from the file.
            const payload = (
                await s3.send(
                    new SelectObjectContentCommand({
                        Bucket: "test-bucket",
                        Key: "test-file.jsonl",
                        ExpressionType: "SQL",
                        Expression: "SELECT * FROM S3Object",
                        InputSerialization: { JSON: { Type: JSONType.LINES } },
                        OutputSerialization: { JSON: {} },
                        ScanRange: {
                            Start: 0,
                            End: sizeInBytes,
                        }
                    })
                )
            ).Payload!;

            // Buffer the bytes from each event returned from the
            // async iterator. The response will be incomplete
            // until we've exited this loop.
            let raw = "";
            for await (const event of payload) {
                if (event.Records?.Payload) {
                    raw += Buffer.from(
                        event.Records.Payload
                    ).toString("utf-8");
                }
            }

            // Let's see what we've got...
            console.log(raw);
        });
    });
});
```

**Actual Output:**
```text
UnknownError
  at at deserializeAws_restXmlSelectObjectContentCommandError (...)
  ...
```

**Expected Output:**
```text
{"key":"value1","nested":{"key":"value1"}}
{"key":"value2","nested":{"key":"value2"}}
```

### Environment

```markdown
- OS: macOS Ventura 13.3.1
- LocalStack: 2.0.2
```

### Anything else?

Output from `docker logs` on the `localstack` container:
```text
2023-05-03T23:43:56.125 ERROR --- [uest_thread)] werkzeug                   : Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/moto_server/werkzeug_app.py", line 239, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
    return new(target, *args, **kwargs)
  File "/opt/code/localstack/localstack/utils/aws/request_context.py", line 175, in convert_to_flask_response_call
    return fn(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/utils.py", line 106, in __call__
    result = self.callback(request, request.url, dict(request.headers))
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 247, in ambiguous_response
    return self.key_response(request, full_url, headers)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/utilities/aws_headers.py", line 64, in _wrapper
    response = f(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1131, in key_response
    response = self._key_response(request, full_url, self.headers)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1249, in _key_response
    return self._key_response_post(request, body, bucket_name, query, key_name)
  File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
    return new(target, *args, **kwargs)
  File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 172, in s3_key_response_post
    result = fn(request, body, bucket_name, query, key_name, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 2137, in _key_response_post
    results = self.backend.select_object_content(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/models.py", line 2348, in select_object_content
    return [
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/models.py", line 2349, in <listcomp>
    json.dumps(x, indent=None, separators=(",", ":")).encode("utf-8")
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CaseInsensitiveDict is not JSON serializable
2023-05-03T23:43:56.128  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.SelectObjectContent => 500
```

**Comment by steffyP** [comment]
Hi @Trystan-C, 

thanks for the detailed report and reproduction sample 🙏 we will look into it and get back to you if we need any more information.
