### ISSUE TITLE
localstack doesnt start on macOS Script 'scripts/localstack' not found in metadata

### ISSUE THREAD

**Issue by wa11a** [localstack/localstack#825]
installed localstack using pip install --user localstack.
using macOS High Sierra 10.13.4

```
localstack start 
Traceback (most recent call last):
  File "/usr/local/bin/localstack", line 4, in <module>
    __import__('pkg_resources').run_script('localstack==0.8.7', 'localstack')
  File "/Users/myuser/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/lidora/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 1425, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/localstack' not found in metadata at '/Users/myuser/Library/Python/2.7/lib/python/site-packages/localstack-0.8.7.dist-info'
```

**Comment by liangjacky** [comment]
Having the same issue even after following the re-installation steps. 

```
Traceback (most recent call last):
  File "/usr/local/bin/localstack", line 4, in <module>
    __import__('pkg_resources').run_script('localstack==0.8.10', 'localstack')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1425, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/localstack' not found in metadata at '/Users/myuser/Library/Python/2.7/lib/python/site-packages/localstack-0.8.10-py2.7.egg-info'
```

**Comment by bmore2019** [comment]
having the same issue @whummer 
tried the above steps and still getting an issue:

Traceback (most recent call last):
  File "/usr/local/bin/localstack", line 4, in <module>
    __import__('pkg_resources').run_script('localstack==0.9.1', 'localstack')
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1437, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/localstack' not found in metadata at '/Users/user/Library/Python/3.7/lib/python/site-packages/localstack-0.9.1-py3.7.egg-info'
