### ISSUE TITLE
bug: InternalError: exception while calling s3.UploadPart

### ISSUE THREAD

**Issue by eliellis** [localstack/localstack#8263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to upload a file using localstack S3 with `S3_DIR` set and `PERSISTENCE=0`, multipart uploads fail with:

```bash
InternalError: exception while calling s3.UploadPart: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 123, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 93, in __call__
    skeleton_response = self.skeleton.invoke(context)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 166, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/forwarder.py", line 67, in _call
    return fallthrough_handler(context, req)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/moto.py", line 83, in _proxy_moto
    return call_moto(context)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/moto.py", line 46, in call_moto
    return dispatch_to_backend(context, dispatch_to_moto, include_response_metadata)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/forwarder.py", line 120, in dispatch_to_backend
    http_response = http_request_dispatcher(context)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/moto.py", line 111, in dispatch_to_moto
    response = dispatch(request, request.url, request.headers)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/patch.py", line 38, in proxy
    return new(target, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/s3/provider.py", line 1360, in _fix_key_response
    status_code, resp_headers, key_value = fn(self, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/utilities/aws_headers.py", line 64, in _wrapper
    response = f(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1131, in key_response
    response = self._key_response(request, full_url, self.headers)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1241, in _key_response
    return self._key_response_put(request, body, bucket_name, query, key_name)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1422, in _key_response_put
    key = self.backend.upload_part(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/s3/models.py", line 2099, in upload_part
    multipart = bucket.multiparts[multipart_id]
KeyError: '4i0RHIsYtQgEgsFhDkkH485I5NR0s3VYInXEx6jI5rcoO3IUMA6nyCw'
```

This is regardless of file size or part count.

Setting `PERSISTENCE=1` and unsetting `S3_DIR` does not result in the same failure.

### Expected Behavior

Multipart uploads succeed with `S3_DIR` set.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

A full reproduction can be seen here: https://github.com/eliellis/localstack-multipart-issue-repro

### Environment

```markdown
- OS: macOS 13.2.1
- LocalStack: 2.0.3
```

### Anything else?

Pro User

**Comment by bentsku** [comment]
Hi @eliellis and thanks for your detailed report. As you realised, we have some limitations currently with `S3_DIR`, especially regarding multipart uploads. It is hard to map upload parts and multipart to file in the filesystem, and separate them from regular objects, so this is not supported yet. We will highlight some limitations on the documentation. Sorry for that, I won't have an ETA for this, and it would be better to use `PERSISTENCE=1` in the meantime. Do you have a specific use case for `S3_DIR`?

**Comment by eliellis** [comment]
Hey @bentsku! Thanks for taking the time to look into this. My specific use case here is having a large directory (in overall size) with many small to medium size files on my local fs where I'd like to pre-seed them into the simulated S3 setup using S3_DIR without having to duplicate into the pickled Localstack output. The folder in question can reach upwards of 100s of GBs, with files ranging in size from just a few KBs up to ~20 MBs (into multi-part territory). With S3_DIR, the ability to map a local folder directly into the LS container has a few benefits:

- No need to incur additional storage penalties from the duplicate / persisted LS copy of said folder
- It can be significantly speedier to build the bulk of this folder up outside LS rather than going through the S3 API, especially in the testing phase where the bucket in question is part of a CFN stack that may need to get blown away many times over while tweaking other things about the deployment stack
- It can be much easier (from the DX perspective) to validate everything is working correctly when everything is up and running if you can "see" the files in question without needing to do any Docker-fu

Again thanks for taking a look at this! I have been using `PERSISTENCE=1` in the meantime with just a subset of the folder in question as a workaround. I will continue with this until you talented folks get around to this one. Thanks for all your hard work. 🙂

**Comment by lazarkanelov** [comment]
📋 Copied to lazarkanelov/localstack#2

**Comment by HarshCasper** [comment]
Due to the forthcoming changes in our distribution and development model ([read more](https://blog.localstack.cloud/the-road-ahead-for-localstack/)), this issue tracker is no longer being maintained. We've migrated this issue to our internal tracker and will continue to work on it there. If you'd like to follow up on the status or expedite this, feel free to reach out through one of our support channels:

-   💬 [GitHub Discussions](https://github.com/orgs/localstack/discussions)
-   📖 [Help & Support](https://docs.localstack.cloud/aws/getting-started/help-support/)
