### ISSUE TITLE
bug: .NET 6 lambda triggered from SQS keeps firing multiple times for a single message

### ISSUE THREAD

**Issue by bdurrani** [localstack/localstack#8283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Set up a .NET 6 lambda to get triggered from SQS via an event source mapping.

When a message shows up in SQS, the lambda is triggered multiple times. This is because something is failing to remove the message from the queue after being successfully processed. 

Running localstack with DEBUG=1, I see the following log messages in the localstack docker container

```
2023-05-09 08:15:56 2023-05-09T12:15:56.298  WARN --- [   asgi_gw_0] localstack.aws.accounts    : Ignoring production AWS credentials provided to LocalStack. Falling back to default account ID.
2023-05-09 08:15:56 2023-05-09T12:15:56.305  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS logs.FilterLogEvents => 200
2023-05-09 08:16:01 2023-05-09T12:16:01.330  WARN --- [   asgi_gw_0] localstack.aws.accounts    : Ignoring production AWS credentials provided to LocalStack. Falling back to default account ID.
2023-05-09 08:16:01 2023-05-09T12:16:01.332  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS logs.FilterLogEvents => 200
2023-05-09 08:16:06 2023-05-09T12:16:06.345  WARN --- [   asgi_gw_1] localstack.aws.accounts    : Ignoring production AWS credentials provided to LocalStack. Falling back to default account ID.
2023-05-09 08:16:06 2023-05-09T12:16:06.346  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS logs.FilterLogEvents => 200
2023-05-09 08:16:11 2023-05-09T12:16:11.362  WARN --- [   asgi_gw_1] localstack.aws.accounts    : Ignoring production AWS credentials provided to LocalStack. Falling back to default account ID.
2023-05-09 08:16:11 2023-05-09T12:16:11.363  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS logs.FilterLogEvents => 200
2023-05-09 08:16:12 2023-05-09T12:16:12.381 DEBUG --- [-functhread9] l.services.sqs.models      : re-queueing inflight messages bcda565a-7081-4b06-9f85-a88085c4059d into queue arn:aws:sqs:ap-southeast-2:000000000000:text-extraction-dev-textract
2023-05-09 08:16:12 2023-05-09T12:16:12.644 DEBUG --- [   asgi_gw_0] l.services.sqs.models      : de-queued message bcda565a-7081-4b06-9f85-a88085c4059d from arn:aws:sqs:ap-southeast-2:000000000000:text-extraction-dev-textract
2023-05-09 08:16:12 2023-05-09T12:16:12.651 DEBUG --- [functhread38] l.s.a.e.sqs_event_source_l : Sending event from event source arn:aws:sqs:ap-southeast-2:000000000000:text-extraction-dev-textract to Lambda arn:aws:lambda:ap-southeast-2:000000000000:function:lambda-dotnet-function
2023-05-09 08:16:12 2023-05-09T12:16:12.652 DEBUG --- [functhread27] l.s.a.i.version_manager    : Got invocation event a24165c8-ad2d-421d-af12-8b136fa285b5 in loop
2023-05-09 08:16:12 2023-05-09T12:16:12.652 DEBUG --- [functhread27] l.s.a.i.docker_runtime_exe : Sending invoke-payload '{"invoke-id": "a24165c8-ad2d-421d-af12-8b136fa285b5", "invoked-function-arn": "arn:aws:lambda:ap-southeast-2:000000000000:function:lambda-dotnet-function", "payload": "{\"Records\": [{\"body\": \"Hello world\", \"receiptHandle\": \"NDEwYzRjMjQtZjUyOC00MzIzLWJmZDctZmRmOGYyZmU0ZTJjIGFybjphd3M6c3FzOmFwLXNvdXRoZWFzdC0yOjAwMDAwMDAwMDAwMDp0ZXh0LWV4dHJhY3Rpb24tZGV2LXRleHRyYWN0IGJjZGE1NjVhLTcwODEtNGIwNi05Zjg1LWE4ODA4NWM0MDU5ZCAxNjgzNjM0NTcyLjY0NDIwODc=\", \"md5OfBody\": \"3e25960a79dbc69b674cd4ec67a72c62\", \"eventSourceARN\": \"arn:aws:sqs:ap-southeast-2:000000000000:text-extraction-dev-textract\", \"eventSource\": \"aws:sqs\", \"awsRegion\": \"ap-southeast-2\", \"messageId\": \"bcda565a-7081-4b06-9f85-a88085c4059d\", \"attributes\": {\"SenderId\": \"000000000000\", \"SentTimestamp\": \"1683634138906\", \"ApproximateReceiveCount\": \"15\", \"ApproximateFirstReceiveTimestamp\": \"1683634139026\"}, \"messageAttributes\": {}}]}", "trace-id": "Root=1-645a398c-44c53f9d68b9e58f483c7878;Parent=6c984c731d8ae040;Sampled=0"}' to executor '06c0ef0eeb2c295641ebba7ec3e5817a'
2023-05-09 08:16:12 2023-05-09T12:16:12.657 DEBUG --- [functhread27] l.s.a.i.version_manager    : Invoke for request a24165c8-ad2d-421d-af12-8b136fa285b5 done
2023-05-09 08:16:12 2023-05-09T12:16:12.669 DEBUG --- [   asgi_gw_0] l.s.a.i.version_manager    : Got logs for invocation 'a24165c8-ad2d-421d-af12-8b136fa285b5'
2023-05-09 08:16:12 2023-05-09T12:16:12.669 DEBUG --- [   asgi_gw_0] l.s.a.i.version_manager    : > START RequestId: a24165c8-ad2d-421d-af12-8b136fa285b5 Version: $LATEST
2023-05-09 08:16:12 2023-05-09T12:16:12.669 DEBUG --- [   asgi_gw_0] l.s.a.i.version_manager    : > {"@t":"2023-05-09T12:16:12.6616448Z","@mt":"Processing {Number} messages for testing shit","Number":1}
2023-05-09 08:16:12 2023-05-09T12:16:12.669 DEBUG --- [   asgi_gw_0] l.s.a.i.version_manager    : > {"Timestamp":"2023-05-09T12:16:12.6616448+00:00","Level":"Information","MessageTemplate":"Processing {Number} messages for testing shit","Properties":{"Number":1}}
2023-05-09 08:16:12 2023-05-09T12:16:12.669 DEBUG --- [   asgi_gw_0] l.s.a.i.version_manager    : > {"@t":"2023-05-09T12:16:12.6623511Z","@mt":"Event {Body}","Body":"Hello world"}
2023-05-09 08:16:12 2023-05-09T12:16:12.669 DEBUG --- [   asgi_gw_0] l.s.a.i.version_manager    : > {"Timestamp":"2023-05-09T12:16:12.6623511+00:00","Level":"Information","MessageTemplate":"Event {Body}","Properties":{"Body":"Hello world"}}
2023-05-09 08:16:12 2023-05-09T12:16:12.669 DEBUG --- [   asgi_gw_0] l.s.a.i.version_manager    : > END RequestId: a24165c8-ad2d-421d-af12-8b136fa285b5
2023-05-09 08:16:12 2023-05-09T12:16:12.669 DEBUG --- [   asgi_gw_0] l.s.a.i.version_manager    : > REPORT RequestId: a24165c8-ad2d-421d-af12-8b136fa285b5      Duration: 10.18 ms      Billed Duration: 11 ms  Memory Size: 128 MB Max Memory Used: 128 MB
2023-05-09 08:16:12 2023-05-09T12:16:12.669  INFO --- [   asgi_gw_0] localstack.request.http    : POST /_localstack_lambda/06c0ef0eeb2c295641ebba7ec3e5817a/invocations/a24165c8-ad2d-421d-af12-8b136fa285b5/logs => 202
2023-05-09 08:16:12 2023-05-09T12:16:12.672 DEBUG --- [   asgi_gw_1] l.s.a.i.version_manager    : Got invocation result for invocation 'a24165c8-ad2d-421d-af12-8b136fa285b5'
2023-05-09 08:16:12 2023-05-09T12:16:12.672 DEBUG --- [   asgi_gw_1] localstack.utils.threads   : start_thread called without providing a custom name
2023-05-09 08:16:12 2023-05-09T12:16:12.673 DEBUG --- [   asgi_gw_1] l.s.a.e.adapters           : Encountered an exception while handling callback
2023-05-09 08:16:12 Traceback (most recent call last):
2023-05-09 08:16:12   File "/opt/code/localstack/localstack/services/awslambda/event_source_listeners/adapters.py", line 147, in mapped_callback
2023-05-09 08:16:12     result=to_str(json.loads(result.payload)),
2023-05-09 08:16:12   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
2023-05-09 08:16:12     return _default_decoder.decode(s)
2023-05-09 08:16:12   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
2023-05-09 08:16:12     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2023-05-09 08:16:12   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
2023-05-09 08:16:12     raise JSONDecodeError("Expecting value", s, err.value) from None
2023-05-09 08:16:12 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Note the following message in the above logs

```
2023-05-09 08:16:12 2023-05-09T12:16:12.673 DEBUG --- [   asgi_gw_1] l.s.a.e.adapters           : Encountered an exception while handling callback
2023-05-09 08:16:12 Traceback (most recent call last):
2023-05-09 08:16:12   File "/opt/code/localstack/localstack/services/awslambda/event_source_listeners/adapters.py", line 147, in mapped_callback
2023-05-09 08:16:12     result=to_str(json.loads(result.payload)),
2023-05-09 08:16:12   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
2023-05-09 08:16:12     return _default_decoder.decode(s)
2023-05-09 08:16:12   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
2023-05-09 08:16:12     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2023-05-09 08:16:12   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
2023-05-09 08:16:12     raise JSONDecodeError("Expecting value", s, err.value) from None
2023-05-09 08:16:12 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Expected Behavior

The Lambda is triggered just once per successfully processed message

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```shell
readonly TAG=2.0.2
readonly IMAGE="localstack/localstack:${TAG}"
readonly NAME=my_localstack
readonly S3_PORT=4566
readonly S3_ENDPOINT=http://localhost:$S3_PORT
readonly MY_QUEUE=myqueue
readonly ENDPOINT_URL="--endpoint-url=http://localhost:4566"

function stopIfRunning() {
  RUNNING_CONTAINER_NAME=$(docker ps -f name="${NAME}" --format '{{.Names}}')

  if [[ "${RUNNING_CONTAINER_NAME}" == "${NAME}" ]]; then
    echo "Stopping $(docker rm -f $NAME)"
  fi
}

function startLocalStack() {
  echo -e "Starting up $NAME"
  CONTAINER_ID=$(docker run --rm -d \
        --env SERVICES=s3,lambda,sns,sqs \
        --env S3_PORT_EXTERNAL=$S3_PORT \
        --env DEBUG=1 \
        -p $S3_PORT:$S3_PORT \
        -v /var/run/docker.sock:/var/run/docker.sock \
        --name $NAME $IMAGE | cut -c 1-8)

  echo "image: ${IMAGE}"
  echo "container-id: ${CONTAINER_ID}"
}


function createSqsQueue() {
  echo "Creating SQS queue $MY_QUEUE" 
  aws sqs $ENDPOINT_URL create-queue \
  --queue-name "$MY_QUEUE" \
  --attributes MessageRetentionPeriod=20
}

function setupLambda() {
  readonly LAMBDA_ROLE_NAME=lambda-dotnet-ex
  readonly LAMBDA_FUNCTION_NAME=lambda-dotnet-function
  
  aws --endpoint-url=http://localhost:4566 iam create-role \
  --role-name $LAMBDA_ROLE_NAME \
  --assume-role-policy-document \
  '{"Version": "2012-10-17", "Statement": [{ "Effect": "Allow", "Principal": {"Service": "lambda.amazonaws.com"}, "Action": "sts:AssumeRole"}]}'
  
  echo "Setting up IAM roles" 
  aws --endpoint-url=http://localhost:4566 iam attach-role-policy \
  --role-name $LAMBDA_ROLE_NAME \
  --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole
   
  aws --endpoint-url=http://localhost:4566 lambda create-function \
  --function-name $LAMBDA_FUNCTION_NAME \
  --zip-file fileb://package.zip \
  --handler TestProject.NotificationWorker::HandleNotification \
  --runtime dotnet6 \
  --role arn:aws:iam::000000000000:role/lambda-dotnet-ex
  
  aws --endpoint-url=http://localhost:4566 lambda wait function-active-v2 \
  --function-name $LAMBDA_FUNCTION_NAME
  
  aws --endpoint-url=http://localhost:4566 lambda create-event-source-mapping \
  --batch-size 1 \
  --enabled \
  --event-source-arn arn:aws:sqs:ap-southeast-2:000000000000:myqueue \
  --function-name lambda-dotnet-function
}

startLocalStack
waitForLocalstack
createSqsQueue
setupLambda
```

The .NET lambda package is built using the Amazon.Lambda.Tools global tools package for .NET

```shell
dotnet lambda package \
  --configuration Release \
  --framework "net6.0" \
  --project-location ./Test/ \
  --output-package "./Test/output/$LAMBDA_OUTPUT"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

 ```shell
# Post a message to the SQS queue as follows
aws --endpoint-url=http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/myqueue --message-body "Hello world"

# View the lambda logs to see that the message is being successfully processed by the lambda
aws --endpoint-url=http://localhost:4566 logs tail /aws/lambda/lambda-dotnet-function --follow

```

### Environment

```markdown
- OS: Mac OS M1
- LocalStack: 2.0.2
```

### Anything else?

Thanks for your help

**Comment by thrau** [comment]
Hey @bdurrani, thanks for reporting. It's a bit hard to tell what's going on without knowing what the lambda returns, since the error seems to be related to parsing of the lambda response. Can you share a minimal reproducible example of your lambda? Without that it's hard to reproduce the error. Thanks!
