### ISSUE TITLE
API Gateway Lambda integration throws 500

### ISSUE THREAD

**Issue by DmPanov** [localstack/localstack#831]
Reopen of #411 issue. Problem is still present

#### Versions
LocalStack docker image localstack/localstack:0.8.7
com.amazonaws:aws-java-sdk-api-gateway:1.11.355
Terraform v0.11.7
Terraform aws provider v1.25.0
#### How to reproduce
I use following terraform config (based on [this example](https://www.terraform.io/docs/providers/aws/guides/serverless-with-aws-lambda-and-api-gateway.html))
```
variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "s3" {}
variable "lambda" {}
variable "apigateway" {}

provider "aws" {
  version = "~> 1.25"
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region = "${var.region}"
  skip_credentials_validation = true
  skip_metadata_api_check = true
  s3_force_path_style = true
  endpoints {
    s3 = "${var.s3}"
    lambda = "${var.lambda}"
    apigateway = "${var.apigateway}"
  }
}

variable "function_name" {}
variable "handler" {}
variable "jar" {}

// java8 lambda returning "hello, world"
resource "aws_lambda_function" "hello" {
  function_name = "${var.function_name}"
  filename = "${var.jar}"
  handler = "${var.handler}"
  runtime = "java8"
  role = "r1"
}

// api gateway
resource "aws_api_gateway_rest_api" "gateway" {
  name = "rest-api"
}

resource "aws_api_gateway_resource" "proxy" {
  rest_api_id = "${aws_api_gateway_rest_api.gateway.id}"
  parent_id = "${aws_api_gateway_rest_api.gateway.root_resource_id}"
  path_part = "{proxy+}"
}

resource "aws_api_gateway_method" "proxy" {
  rest_api_id = "${aws_api_gateway_rest_api.gateway.id}"
  resource_id = "${aws_api_gateway_resource.proxy.id}"
  http_method = "POST"
  authorization = "NONE"
}

resource "aws_api_gateway_integration" "lambda" {
  rest_api_id = "${aws_api_gateway_rest_api.gateway.id}"
  resource_id = "${aws_api_gateway_method.proxy.resource_id}"
  http_method = "${aws_api_gateway_method.proxy.http_method}"
  integration_http_method = "POST"
  type = "AWS_PROXY"
  uri = "${aws_lambda_function.hello.invoke_arn}"
}

resource "aws_api_gateway_method" "proxy_root" {
  rest_api_id = "${aws_api_gateway_rest_api.gateway.id}"
  resource_id = "${aws_api_gateway_rest_api.gateway.root_resource_id}"
  http_method = "POST"
  authorization = "NONE"
}

resource "aws_api_gateway_integration" "lambda_root" {
  rest_api_id = "${aws_api_gateway_rest_api.gateway.id}"
  resource_id = "${aws_api_gateway_method.proxy_root.resource_id}"
  http_method = "${aws_api_gateway_method.proxy_root.http_method}"
  integration_http_method = "POST"
  type = "AWS_PROXY"
  uri = "${aws_lambda_function.hello.invoke_arn}"
}

resource "aws_api_gateway_deployment" "deployment" {
  depends_on = [
    "aws_api_gateway_integration.lambda",
    "aws_api_gateway_integration.lambda_root",
  ]
  rest_api_id = "${aws_api_gateway_rest_api.gateway.id}"
  stage_name = "test"
}
```
and call gateway using code:
```
val client = AmazonApiGatewayClientBuilder.standard()
                .withCredentials(...)
                .build()
val api = client.getRestApis(GetRestApisRequest()).items[0]
val resource = client.getResources(GetResourcesRequest().withRestApiId(api.id)).items[0]
val response = client.testInvokeMethod(TestInvokeMethodRequest()
                .withRestApiId(api.id)
                .withResourceId(resource.id)
                .withHttpMethod("POST")
                .withRequestCredentialsProvider<TestInvokeMethodRequest>(...)
                .withBody("..."))
```
but LocalStack responds to `testInvokeMethod` with:
```
127.0.0.1 - - [04/Jul/2018 08:13:26] "POST /restapis/4908804393/resources/6812926A-Z55/methods/POST HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
execute(self.server.app)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
application_iter = app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 93, in __call__
return backend_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 141, in __call__
if len(result) == 3:
TypeError: object of type 'NoneType' has no len()
```
Adding lambda calling permission
```
resource "aws_lambda_permission" "lambda_permission" {
  statement_id = "AllowAPIGatewayInvoke"
  action = "lambda:InvokeFunction"
  function_name = "${aws_lambda_function.hello.arn}"
  principal = "*"
  source_arn = "${aws_api_gateway_rest_api.gateway.execution_arn}/*/*/*"
}
```
gives following terraform error:
```
aws_lambda_permission.lambda_permission: Creating...
...
127.0.0.1 - - [04/Jul/2018 08:23:15] "POST /restapis/1014462339/resources/77117520A-Z8 HTTP/1.1" 200 -
2018/07/04 11:23:12 [DEBUG] [aws-sdk-go] DEBUG: Response lambda/AddPermission Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.0 404 NOT FOUND
Connection: close
Content-Length: 233
Access-Control-Allow-Origin: *
Content-Type: text/html
Date: Wed, 04 Jul 2018 08:23:15 GMT
Server: Werkzeug/0.14.1 Python/2.7.13


-----------------------------------------------------
2018/07/04 11:23:12 [DEBUG] [aws-sdk-go] <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
2018/07/04 11:23:12 [DEBUG] [aws-sdk-go] DEBUG: Validate Response lambda/AddPermission failed, not retrying, error SerializationError: failed decoding REST JSON error response
caused by: invalid character '<' looking for beginning of value
```

**Comment by whummer** [comment]
Thanks for reporting @DmPanov . The problem is that LocalStack expects a different URL for the invocation of the API gateway method.

Instead of calling this URL:
```
/restapis/1014462339/resources/77117520A-Z8
```
... you need to be calling this URL:
```
/restapis/1014462339/resources/_user_request_/77117520A-Z8
```
This is a limitation caused by the fact that all endpoints are bound to `localhost` and the system has no way of knowing whether the invocation is (1) a request to update the API gateway method resource, or (2) actually invoke the API gateway method.

One possible solution is to set up a small reverse proxy that listens on a different port and forwards any requests on `/restapis/1014462339/resources/77117520A-Z8` to `/restapis/1014462339/resources/_user_request_/77117520A-Z8` on the LocalStack API Gateway port (port 4567).

See here for reference: https://github.com/localstack/localstack/blob/master/localstack/services/apigateway/apigateway_listener.py#L161
https://github.com/localstack/localstack/blob/master/localstack/constants.py#L55

**Comment by DmPanov** [comment]
@whummer thank you very much for your answer, it works now.

**Comment by DmPanov** [comment]
@whummer after a few steps further I'm stuck again. 
My lambda uses path parameter as input. When I call Gateway using `http://<localstack>/restapis/<api_id>/resources/_user_request_/<resource_id>/methods/POST/<path>`  lambda is executed with map as argument containing `"path"` : `"<resource_id>/methods/POST/<path>"` instead of `"path"` : `"<path>"`. Is it possible to workaround this?

**Comment by DmPanov** [comment]
Never mind, correct url is: `http://<localstack>/restapis/<api_id>/<stage>/_user_request_/<path>`
