### ISSUE TITLE
bug: API Gateway websocket authorizer not passing principalId to $connect handler

### ISSUE THREAD

**Issue by devmau5** [localstack/localstack#8314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When connecting to a websocket API on localstack the principalId is not forwarded to the connect handler Lambda as expected. Relevant logs: 

```
INFO --- [uncthread464] l.s.apigateway.authorizers : Received authorizer result: {"principalId": "some_value", "policyDocument": {"Version": "2012-10-17", "Statement": [{"Action": "execute-api:Invoke", "Effect": "Allow", "Resource": "arn:aws:execute-api:*:*:*"}]}, "context": {"scope": "some_scopes"}}
INFO --- [   asgi_gw_6] localstack.request.aws     : AWS logs.CreateLogGroup => 400 (ResourceAlreadyExistsException)
INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudwatch.PutMetricData => 200
INFO --- [   asgi_gw_7] localstack.request.aws     : AWS logs.CreateLogStream => 200
INFO --- [   asgi_gw_0] localstack.request.aws     : AWS sts.AssumeRole => 200
INFO --- [   asgi_gw_4] localstack.request.aws     : AWS logs.PutLogEvents => 200
INFO --- [   asgi_gw_0] localstack.request.http    : POST /_localstack_lambda/5f2d035194bac49cbf82774dfaae29e0/status/5f2d035194bac49cbf82774dfaae29e0/ready => 202
WARN --- [   asgi_gw_0] l.s.a.i.executor_endpoint  : Execution environment startup failed: {"errorMessage": "'principalId'", "errorType": "KeyError", "requestId": "9fbee9ad-e687-46b0-b243-f9ac3b7fae2e", "stackTrace": ["  File \"/var/task/connection_handler.py\", line 15, in lambda_handler\n    print(event['requestContext']['authorizer']['principalId'])\n"]}
ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Runtime Handler can only error while starting
INFO --- [   asgi_gw_0] localstack.request.http    : POST /_localstack_lambda/5f2d035194bac49cbf82774dfaae29e0/status/5f2d035194bac49cbf82774dfaae29e0/error => 500
INFO --- [   asgi_gw_0] localstack.request.http    : POST /_localstack_lambda/5f2d035194bac49cbf82774dfaae29e0/invocations/9fbee9ad-e687-46b0-b243-f9ac3b7fae2e/logs => 202
INFO --- [   asgi_gw_0] localstack.request.http    : POST /_localstack_lambda/5f2d035194bac49cbf82774dfaae29e0/invocations/9fbee9ad-e687-46b0-b243-f9ac3b7fae2e/error => 202
INFO --- [uncthread464] l.s.a.integrations         : Lambda invocation reported error (statusCode=500)
INFO --- [uncthread464] l.s.a.integrations         : Error invoking integration request for route "$connect": Integration reported error (statusCode=500)
INFO --- [uncthread464] localstack.utils.threads   : Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fafa7993640>(None) failed: Exception during $connect action: Integration reported error (statusCode=500) Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/integrations.py.enc", line 134, in v2_invoke_action_from_websocket
    if B.status_code>=400:raise Exception(f"Integration reported error (statusCode={B.status_code})")
Exception: Integration reported error (statusCode=500)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/threads.py", line 58, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/asyncio.py", line 30, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/integrations.py.enc", line 95, in A
    with RequestContextManager(R):C=v2_invoke_action_from_websocket(A,D,E)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/apigateway/integrations.py.enc", line 137, in v2_invoke_action_from_websocket
    if E==_P:raise ConnectionDeniedException(f"Exception during $connect action: {K}")from K
localstack_ext.services.apigateway.models.ConnectionDeniedException: Exception during $connect action: Integration reported error (statusCode=500)

INFO --- [uncthread117] websockets.server          : connection closed
```

Payload from authorizer to $connect in localstack:

```
{
  'version': '1.0', 
  'resource': '/', 
  'httpMethod': None, 
  'path': '/?access_token=*****...', 
  'body': '{"action": "$connect"}', 
  'headers': 
    {
      'Sec-WebSocket-Version': '13', 
      'Sec-WebSocket-Key': '************************', 
      'Connection': 'Upgrade', 
      'Upgrade': 'websocket', 
      'Sec-WebSocket-Extensions': 'permessage-deflate; client_max_window_bits', 
      'Host': 'localhost:4510'
    },
  'multiValueHeaders': 
    {
      'Sec-WebSocket-Version': ['13'], 
      'Sec-WebSocket-Key': ['************************'], 
      'Connection': ['Upgrade'], 
      'Upgrade': ['websocket'], 
      'Sec-WebSocket-Extensions': ['permessage-deflate; client_max_window_bits'], 
      'Host': ['localhost:4510']
    }, 
  'requestContext': 
    {
      'accountId': '000000000000', 
      'apiId': '********', 
      'resourcePath': '/', 
      'domainPrefix': 'localhost', 
      'domainName': 'localhost', 
      'resourceId': None, 
      'requestId': 'a24e5714-ab3e-44b3-9119-6f63ec483236', 
      'identity': {'accountId': '000000000000', 'sourceIp': '', 'userAgent': None, 'cognitoIdentityId': None, 'cognitoIdentityPoolId': None},
      'httpMethod': None, 
      'protocol': 'HTTP/1.1', 
      'requestTime': '01/January/2000:12:00:00 +0000', 
      'requestTimeEpoch': 946684800, 
      'authorizer': 
        {
          'scope': 'some_scopes', 
          'claims': None, 
          'scopes': None
        },
      'connectionId': '********', 
      'path': '/', 
      'stage': '', 
      'routeKey': '$connect', 
      'messageId': None, 
      'eventType': 'CONNECT', 
      'version': '1.0'
    }, 
  'isBase64Encoded': False, 
  'queryStringParameters': {'access_token': '*****...'},
  'multiValueQueryStringParameters': {'access_token': ['*****...']},
  'pathParameters': {}, 
  'stageVariables': {}
}
```

### Expected Behavior

principalId should be returned as part of event.requestContext.authorizer when using the Lambda Proxy Integration. The only supporting documentation I could find was [this](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-mapping-template-reference.html). The only other mention of it seems to be  [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-lambda-auth.html), "The context variables in event.requestContext are different from those for REST APIs.". 

Here is the payload from the authorizer to $connect in AWS:

```
{
  'headers': 
    {
      'Host': 'api.example.com', 
      'Sec-WebSocket-Extensions': 'permessage-deflate; client_max_window_bits',
      'Sec-WebSocket-Key': '*********************', 
      'Sec-WebSocket-Version': '13', 
      'X-Amzn-Trace-Id': 'Root=***********************************', 
      'X-Forwarded-For': '0.0.0.0', 
      'X-Forwarded-Port': '443', 
      'X-Forwarded-Proto': 'https'
    },
  'multiValueHeaders': 
    {
      'Host': ['api.example.com'], 
      'Sec-WebSocket-Extensions': ['permessage-deflate; client_max_window_bits'], 
      'Sec-WebSocket-Key': ['*********************'], 
      'Sec-WebSocket-Version': ['13'], 
      'X-Amzn-Trace-Id': ['Root=***********************************'], 
      'X-Forwarded-For': ['0.0.0.0'], 
      'X-Forwarded-Port': ['443'], 
      'X-Forwarded-Proto': ['https']
    },
  'queryStringParameters': 
    {
      'access_token': '*****...'
    },
  'multiValueQueryStringParameters': 
    {
      'access_token': ['*****...']
    },
  'requestContext': 
    {
      'routeKey': '$connect', 
      'authorizer': 
        {
          'scope': 'some_scopes', 
          'principalId': 'some_principal_id', 
          'integrationLatency': 999
        },
      'eventType': 'CONNECT', 
      'extendedRequestId': '****************', 
      'requestTime': '01/January/2000:12:00:00 +0000', 
      'messageDirection': 'IN', 
      'stage': 'my_stage', 
      'connectedAt': 946684800, 
      'requestTimeEpoch': 946684800, 
      'identity': {'sourceIp': '0.0.0.0'}, 
      'requestId': '****************', 
      'domainName': 'api.example.com', 
      'connectionId': '****************', 
      'apiId': '**********'
    },
  'isBase64Encoded': False
}

```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    bin/localstack
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    
The following scripts can be used to reproduce the issue

Authroizer.py
```
def lambda_handler(event, context):
    return {
        "principalId": "foobar",
        "policyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": "execute-api:Invoke",
                    "Effect": "Allow",
                    "Resource": "arn:aws:execute-api:*:*:*"
                }
            ]
        },
        "context": {
            "scope": "some_scopes"
        }
    }
```

Connect.py:
```
def lambda_handler(event, context):
    print(event["requestContext"]['authorizer']['principalId'])
```

### Environment

```markdown
- OS: Linux (Kernel 6.3.1)
- Python: 3.11
- LocalStack: latest
```

### Anything else?

Related to the previously fixed issue: #7191

**Comment by devmau5** [comment]
I was able to work around the above issue temporarily in my authorizer function by explicitly returning the principalId in the context. 

However, it turns out that the requestContext piece is also included in subsequent calls to other routes, I do not see an obvious workaround for that since the above fix only works for the $connect route.

**Comment by calvernaz** [comment]
Duplicated https://github.com/localstack/localstack/issues/8314
