### ISSUE TITLE
bug: KMS create key with alias fails

### ISSUE THREAD

**Issue by gvagenas** [localstack/localstack#8338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Creating a KMS key with alias using the following code

```
const localAccount = {
    account: "000000000000",
    region: "us-east-1"
};

const app = new App();

const localKmsStack = new LocalKmsStack(app, "local-kms-stack", {
    env: localAccount
});
```

```
export class LocalKmsStack extends Stack {
    readonly dynamodbKey: Key;

    constructor(scope: Construct, id: string, props: StackProps) {
        super(scope, id, props);

        const keyProps: KeyProps = {
            enableKeyRotation: true,
            enabled: true,
            pendingWindow: Duration.days(7),
            removalPolicy: RemovalPolicy.DESTROY,
        };
        this.dynamodbKey = new Key(this, "DynamodbKey", {
            ...keyProps,
            description: "DynamoDB encryption key",
            alias: "alias/local-rsp/dynamodb",
        });
    }
}
```

deployment fails with the following error

```
$ cdklocal bootstrap && cdklocal deploy --all

....

local-kms-stack: deploying... [1/2]
[0%] start: Publishing 8d642efbcfdb72c182ee7931a67d2369eff0f832aa7e46d4fc45eaf12068d92a:000000000000-us-east-1
[100%] success: Published 8d642efbcfdb72c182ee7931a67d2369eff0f832aa7e46d4fc45eaf12068d92a:000000000000-us-east-1
local-kms-stack: creating CloudFormation changeset...

 ❌  local-kms-stack failed: Error: The stack named local-kms-stack failed to deploy: CREATE_FAILED (Deployment failed)
    at FullCloudFormationDeployment.monitorDeployment (/Users/gvagenas/.config/yarn/global/node_modules/aws-cdk/lib/index.js:397:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deployStack2 (/Users/gvagenas/.config/yarn/global/node_modules/aws-cdk/lib/index.js:400:145739)
    at async /Users/gvagenas/.config/yarn/global/node_modules/aws-cdk/lib/index.js:400:128776
    at async run (/Users/gvagenas/.config/yarn/global/node_modules/aws-cdk/lib/index.js:400:126782)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named local-kms-stack failed to deploy: CREATE_FAILED (Deployment failed)
    at deployStacks (/Users/gvagenas/.config/yarn/global/node_modules/aws-cdk/lib/index.js:400:129083)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdkToolkit.deploy (/Users/gvagenas/.config/yarn/global/node_modules/aws-cdk/lib/index.js:400:147788)
    at async exec4 (/Users/gvagenas/.config/yarn/global/node_modules/aws-cdk/lib/index.js:455:51984)

Stack Deployments Failed: Error: The stack named local-kms-stack failed to deploy: CREATE_FAILED (Deployment failed)
```

Localstack debug logs:

```
2023-05-19T07:51:54.816 DEBUG --- [   asgi_gw_0] plugin.manager             : instantiating plugin PluginSpec(localstack.aws.provider.kms:default = <function kms at 0x7f94404169e0>)
2023-05-19T07:51:54.816 DEBUG --- [   asgi_gw_0] plugin.manager             : loading plugin localstack.aws.provider:kms:default
2023-05-19T07:51:54.825 DEBUG --- [   asgi_gw_0] l.services.plugins         : checking service health kms:4566
2023-05-19T07:51:54.920  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS kms.ListKeys => 200
2023-05-19T07:51:54.922 DEBUG --- [functhread92] l.s.c.e.template_deployer  : Handling "Add" for resource "DynamodbKeyB62DF715" (1/3) type "AWS::KMS::Key" in loop iteration 1 (should_deploy=True)
2023-05-19T07:51:54.922 DEBUG --- [functhread92] l.s.c.e.template_deployer  : Running action "create" for resource type "AWS::KMS::Key" id "DynamodbKeyB62DF715"
2023-05-19T07:51:54.941 DEBUG --- [functhread92] l.s.c.e.template_deployer  : Executing callback method for AWS::KMS::Key:DynamodbKeyB62DF715
2023-05-19T07:51:54.949 DEBUG --- [functhread92] l.s.c.e.template_deployer  : Dependencies for "DynamodbKeyAlias1D81C3CF" not yet satisfied, retrying in next loop: Unresolved dependencies: DynamodbKeyB62DF715
2023-05-19T07:51:54.955 DEBUG --- [functhread92] l.s.c.e.template_deployer  : Handling "Add" for resource "CDKMetadata" (2/2) type "AWS::CDK::Metadata" in loop iteration 1 (should_deploy=False)
2023-05-19T07:51:54.963 DEBUG --- [functhread92] l.s.c.e.template_deployer  : Dependencies for "DynamodbKeyAlias1D81C3CF" not yet satisfied, retrying in next loop: Unresolved dependencies: DynamodbKeyB62DF715
2023-05-19T07:51:54.963 DEBUG --- [functhread92] l.s.c.e.template_deployer  : Error applying changes for CloudFormation stack "local-kms-stack": Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'DynamodbKeyAlias1D81C3CF', 'PhysicalResourceId': None, 'ResourceType': 'AWS::KMS::Alias', 'Scope': [], 'Details': []}}] Traceback (most recent call last):
File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1409, in _run
self.do_apply_changes_in_loop(changes, stack)
File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1503, in do_apply_changes_in_loop
raise Exception(
Exception: Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'DynamodbKeyAlias1D81C3CF', 'PhysicalResourceId': None, 'ResourceType': 'AWS::KMS::Alias', 'Scope': [], 'Details': []}}]

2023-05-19T07:51:56.783  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-05-19T07:51:58.828  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-05-19T07:51:59.799  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-05-19T07:51:59.821  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
```

If I remove alias, the KMS key is created with no errors

### Expected Behavior

Should be able to create KMS keys with alias

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

````
export DEBUG=1 && localstack start
````

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Using the above CDK code, I try to deploy using
```
cdklocal bootstrap && cdklocal deploy --alll
```

### Environment

```markdown
- OS: MacOS
- LocalStack: latest (ebf356b00741)
```

### Anything else?

Thanks for this amazing project !

**Comment by dominikschubert** [comment]
Hi @gvagenas! I've just tried reproducing your CDK sample with the latest version and couldn't reproduce your issue (unfortunately). 

Can you please check if your issue still occurs after pulling the latest version? If that's the case please set `LS_LOG=trace` and `CFN_VERBOSE_ERRORS=1` to get more additional debug logging.
