### ISSUE TITLE
bug: Java SDK error with LocalStack while trying to create an S3 bucket

### ISSUE THREAD

**Issue by kincsescsaba** [localstack/localstack#8341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get this exception when I'm trying to create a bucket:
Exception in thread "main" software.amazon.awssdk.services.s3.model.S3Exception: exception while calling s3 with unknown operation: Unable to find operation for request to service s3: PUT / (Service: S3, Status Code: 500

When I'm listing buckets, it works fine with a bucket being created from CLI.

### Expected Behavior

I'd expect both operations to work.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml:

version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    #hostname: localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

awslocal s3api create-bucket --bucket hello --region us-east-1

I used the latter to test if the list operation works.

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack:2.0.2
```

**Comment by bentsku** [comment]
Hello @kincsescsaba and thanks for your report!

Would it possible to have LocalStack logs when this issue happens? You can set the verbosity with `LS_LOG=trace` and `DEBUG=1`? 

It would also be nice if you could share a small Java snippet to be able to reproduce your issue, because currently I cannot reproduce. 

Thanks!

**Comment by kincsescsaba** [comment]
These are the LocalStack logs that I can see after running my JVM (more specifically: Scala - this compiles to Java bytecode) code:

[+] Running 1/0
 ✔ Container localstack_main  Created                                                                                                                                      0.0s 
Attaching to localstack_main
localstack_main  | 
localstack_main  | LocalStack version: 2.0.3.dev
localstack_main  | LocalStack Docker container id: eaa1b961f436
localstack_main  | LocalStack build date: 2023-05-19
localstack_main  | LocalStack build git hash: 6800861b
localstack_main  | 
localstack_main  | 2023-05-22T10:47:47.625  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "start_runtime_components" took 14736.71ms
localstack_main  | Unexpected exception while starting infrastructure: gave up waiting for edge server on 0.0.0.0:4566 Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/localstack/services/infra.py", line 395, in start_infra
localstack_main  |     thread = do_start_infra(asynchronous, apis, is_in_docker)
localstack_main  |   File "/opt/code/localstack/localstack/services/infra.py", line 487, in do_start_infra
localstack_main  |     thread = start_runtime_components()
localstack_main  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 70, in wrapped
localstack_main  |     return f(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/localstack/services/infra.py", line 480, in start_runtime_components
localstack_main  |     raise TimeoutError(
localstack_main  | TimeoutError: gave up waiting for edge server on 0.0.0.0:4566
localstack_main  | 
localstack_main  | 2023-05-22T10:47:50.984  INFO --- [-functhread2] localstack.utils.http      : Unable to download Github artifact from from https://cdn.jsdelivr.net/gh/localstack/localstack-artifacts@master/local-certs/server.key to /var/lib/localstack/cache/server.test.pem: MyHTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/localstack/localstack-artifacts@master/local-certs/server.key (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa0d2302b00>, 'Connection to cdn.jsdelivr.net timed out. (connect timeout=3)')) Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
localstack_main  |     conn = connection.create_connection(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
localstack_main  |     raise err
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
localstack_main  |     sock.connect(sa)
localstack_main  | TimeoutError: timed out
localstack_main  | 
localstack_main  | During handling of the above exception, another exception occurred:
localstack_main  | 
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
localstack_main  |     httplib_response = self._make_request(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
localstack_main  |     self._validate_conn(conn)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
localstack_main  |     conn.connect()
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
localstack_main  |     self.sock = conn = self._new_conn()
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
localstack_main  |     raise ConnectTimeoutError(
localstack_main  | urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fa0d2302b00>, 'Connection to cdn.jsdelivr.net timed out. (connect timeout=3)')
localstack_main  | 
localstack_main  | During handling of the above exception, another exception occurred:
localstack_main  | 
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
localstack_main  |     resp = conn.urlopen(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
localstack_main  |     retries = retries.increment(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
localstack_main  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
localstack_main  | urllib3.exceptions.MaxRetryError: MyHTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/localstack/localstack-artifacts@master/local-certs/server.key (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa0d2302b00>, 'Connection to cdn.jsdelivr.net timed out. (connect timeout=3)'))
localstack_main  | 
localstack_main  | During handling of the above exception, another exception occurred:
localstack_main  | 
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/localstack/utils/http.py", line 247, in do_download
localstack_main  |     download(download_url, target_file, timeout=timeout, request_headers=request_headers)
localstack_main  |   File "/opt/code/localstack/localstack/utils/http.py", line 198, in download
localstack_main  |     r = s.get(url, stream=True, verify=_verify, timeout=timeout, headers=request_headers)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
localstack_main  |     return self.request("GET", url, **kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
localstack_main  |     resp = self.send(prep, **send_kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
localstack_main  |     r = adapter.send(request, **kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
localstack_main  |     raise ConnectTimeout(e, request=request)
localstack_main  | requests.exceptions.ConnectTimeout: MyHTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/localstack/localstack-artifacts@master/local-certs/server.key (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa0d2302b00>, 'Connection to cdn.jsdelivr.net timed out. (connect timeout=3)'))
localstack_main  | 
localstack_main  | 2023-05-22T10:47:50.989  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main  | 2023-05-22T10:47:50.989  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main  | 2023-05-22T10:47:54.803 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Unable to find operation for request to service s3: PUT /
localstack_main  | 2023-05-22T10:47:54.807  INFO --- [   asgi_gw_0] localstack.request.http    : PUT / => 500
localstack_main  | 2023-05-22T10:47:54.960 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Unable to find operation for request to service s3: PUT /
localstack_main  | 2023-05-22T10:47:54.961  INFO --- [   asgi_gw_0] localstack.request.http    : PUT / => 500
localstack_main  | 2023-05-22T10:47:55.135 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Unable to find operation for request to service s3: PUT /
localstack_main  | 2023-05-22T10:47:55.137  INFO --- [   asgi_gw_0] localstack.request.http    : PUT / => 500
localstack_main  | 2023-05-22T10:47:55.368 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain: Unable to find operation for request to service s3: PUT /
localstack_main  | 2023-05-22T10:47:55.369  INFO --- [   asgi_gw_0] localstack.request.http    : PUT / => 500

**Comment by kincsescsaba** [comment]
And this is my Scala code, it uses the Java SDK for AWS:

`import cats.effect.{ExitCode, IO, IOApp}
import cats.implicits.toSemigroupKOps
import software.amazon.awssdk.auth.credentials.{AwsBasicCredentials, AwsCredentials, AwsCredentialsProvider}
import software.amazon.awssdk.regions.Region
import software.amazon.awssdk.services.s3.S3Client
import software.amazon.awssdk.services.s3.model.*

import java.net.URI

object Main2 extends IOApp {
  def run(args: List[String]): IO[ExitCode] = {
    val creds = AwsBasicCredentials.create("test", "test")
    val credProvider = new AwsCredentialsProvider:
      override def resolveCredentials(): AwsCredentials = creds
    val region: Region = Region.US_EAST_1
    val s3: S3Client = S3Client.builder().endpointOverride(new URI("http://localhost:4566")).region(region).credentialsProvider(credProvider).build()
    val res = s3.createBucket(CreateBucketRequest.builder().bucket("hello").build())
    println(res)
    s3.close()

    IO(ExitCode.Success)
  }
}`

**Comment by kincsescsaba** [comment]
JVM logs:

Exception in thread "main" software.amazon.awssdk.services.s3.model.S3Exception: exception while calling s3 with unknown operation: Unable to find operation for request to service s3: PUT / (Service: S3, Status Code: 500, Request ID: c4adfcf9-b0de-42b4-bae3-22ce6c02ac1a, Extended Request ID: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:85)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:43)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:95)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$7(BaseClientHandler.java:270)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.s3.DefaultS3Client.createBucket(DefaultS3Client.java:1149)
	at io.github.kincsescsaba.scalacms.Main2$.run(Main.scala:115)
	at cats.effect.IOApp.main(IOApp.scala:396)
	at cats.effect.IOApp.main$(IOApp.scala:143)
	at io.github.kincsescsaba.scalacms.Main2$.main(Main.scala:106)
	at io.github.kincsescsaba.scalacms.Main2.main(Main.scala)
	Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 1 failure: exception while calling s3 with unknown operation: Unable to find operation for request to service s3: PUT / (Service: S3, Status Code: 500, Request ID: 7f8b3d5a-ed35-47c0-83cf-2019e052921f, Extended Request ID: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=)
	Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 2 failure: exception while calling s3 with unknown operation: Unable to find operation for request to service s3: PUT / (Service: S3, Status Code: 500, Request ID: f9b2d6a4-9ec6-43fd-9593-bd0c6bfbfadf, Extended Request ID: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=)
	Suppressed: software.amazon.awssdk.core.exception.SdkClientException: Request attempt 3 failure: exception while calling s3 with unknown operation: Unable to find operation for request to service s3: PUT / (Service: S3, Status Code: 500, Request ID: df1868f0-815d-4113-9324-9a93b927a4f5, Extended Request ID: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=)

**Comment by bentsku** [comment]
Okay, so it seems you container has issue with external connectivity while trying to fetch the SSL certificates.
You can skip downloading those certs with `SKIP_SSL_CERT_DOWNLOAD =1` (see https://docs.localstack.cloud/references/configuration/#miscellaneous). 

Regarding the S3 issue, this looks like a virtual host addressing vs path addressing. It looks like your SDK is trying to prepend the host with the bucket name, however, that does not work the `localhost:4566` endpoint, only `s3.localhost.localstack.cloud:4566` (see the S3 note https://docs.localstack.cloud/user-guide/aws/s3/#getting-started).

You should try to configure your SDK to use the path addressing style, see this StackOverflow response: https://stackoverflow.com/a/24012996

This could look like, but I'm not an expert on the JVM ecosystem:
```scala
val s3: S3Client = S3Client.builder().withPathStyleAccessEnabled(true).endpointOverride(new URI("http://localhost:4566")).region(region).credentialsProvider(credProvider).build()
```

Hope that can solve your issue!

**Comment by kincsescsaba** [comment]
Great, thanks for checking!

Worked this way: `val s3: S3Client = S3Client.builder().forcePathStyle(true).endpointOverride(new URI("http://localhost:4566")).region(region).credentialsProvider(credProvider).build()`

**Comment by bentsku** [comment]
Awesome, glad it fixed your issue!

**Comment by utkarshgupta137** [comment]
We have the same problem with Rust SDK, what is the equivalent for it?
Relevant: https://docs.rs/aws-config/latest/aws_config/struct.ConfigLoader.html

**Comment by joeshin** [comment]
@utkarshgupta137 https://docs.localstack.cloud/user-guide/integrations/sdks/

Gotta set the base endpoint.  See examples from other langs.
