### ISSUE TITLE
bug: Installation 

### ISSUE THREAD

**Issue by Obasoro** [localstack/localstack#8342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

'''
Traceback (most recent call last):
  File "/opt/homebrew/bin/localstack", line 23, in <module>
    main()
  File "/opt/homebrew/bin/localstack", line 19, in main
    main.main()
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/localstack/cli/main.py", line 16, in main
    cli = create_with_plugins()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/localstack/cli/localstack.py", line 30, in create_with_plugins
    load_cli_plugins(cli)
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/localstack/cli/plugin.py", line 39, in load_cli_plugins
    loader.load_all()
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/plugin/manager.py", line 190, in load_all
    for name, container in self._plugins.items():
                           ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/plugin/manager.py", line 231, in _plugins
    self._plugin_index = self._init_plugin_index()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/plugin/manager.py", line 294, in _init_plugin_index
    return {plugin.name: plugin for plugin in self._import_plugins() if plugin}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/plugin/manager.py", line 294, in <dictcomp>
    return {plugin.name: plugin for plugin in self._import_plugins() if plugin}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/plugin/manager.py", line 297, in _import_plugins
    for spec in self.finder.find_plugins():
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/plugin/manager.py", line 333, in find_plugins
    manager = ExtensionManager(
              ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/stevedore/extension.py", line 118, in __init__
    extensions = self._load_plugins(invoke_on_load,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/stevedore/extension.py", line 206, in _load_plugins
    ext = self._load_one_plugin(ep,
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/stevedore/extension.py", line 240, in _load_one_plugin
    plugin = ep.load()
             ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/localstack_ext/cli/localstack.py", line 7, in <module>
    from localstack_ext.bootstrap.licensing import is_logged_in
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/localstack_ext/bootstrap/licensing.py", line 18, in <module>
    from localstack_ext import __version__,config
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/localstack_ext/config.py", line 224, in <module>
    out, _ = DOCKER_CLIENT.run_container(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/localstack/utils/container_utils/docker_cmd_client.py", line 543, in run_container
    result = self._run_async_cmd(cmd, stdin, kwargs.get("name") or "", image_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/localstack/2.0.2/libexec/lib/python3.11/site-packages/localstack/utils/container_utils/docker_cmd_client.py", line 611, in _run_async_cmd
    stdout, stderr = process.communicate(input=stdin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
'''

### Expected Behavior

'''
localstack status services

'''

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: MacOs
- LocalStack: latest
```

**Comment by thrau** [comment]
hi @Obasoro. we'll need some more details do be able to troubleshoot. could you please clarify the following things:
* what operating system are you on?
* how did you install the localstack CLI?
* could you please add the complete log output?

thanks

**Comment by alexrashed** [comment]
Hi @Obasoro!
It seems like you installed localstack using the community driven Homebrew tap, which seems to use Python 11 (which is currently not supported for running the host mode).
However, until just recently, we do have our own Homebrew tap which helps you to install our binary builds of the CLI (which contains its own Python runtime which is known to be supported). You can find instructions on how to install this on our docs pages: https://docs.localstack.cloud/getting-started/installation/
I'll close this issue for now, but please feel free to open a new issue if you are still experiencing any issues!
Thanks!

**Comment by Obasoro** [comment]
Apologies for responding late...I would check and revert back. I need to understand how it works. the demo have seen has been great.
