### ISSUE TITLE
bug: kinesis_mock_server fails and DDB Stream Lambda stops receiving change events 

### ISSUE THREAD

**Issue by cabeaulac** [localstack/localstack#8378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This seems very similar to #5182 

When the system sits idle for 30 minutes or more, the kinesis stream fails. And then my Lambda bound to my DynamoDB stream is never called again.

This project can replicate the issue
https://gitlab.com/ivtech-pub/blueprints/localstack-pro-gdc-bp1

CC: @HarshCasper  

### Expected Behavior

When changes occur in my DDB table, the Lambda that's subscribed to the DDB Steam is invoked.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Run the example app: https://gitlab.com/ivtech-pub/blueprints/localstack-pro-gdc-bp1

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Upload a couple items to S3 using the UI in the example app. Let the system sit for an hour or so. Try again. See that the DDB Stream Lambda is not called in Docker Desktop.

### Environment

```markdown
- OS: Mac M2
- Since LocalStack: 2.1.0-pro
- Latest test LocalStack: 2.2.1.dev20230810230304
```

**Comment by cabeaulac** [comment]
Just retested this. This ticket https://github.com/localstack/localstack/issues/5182
Did not fix this bug.

**Comment by cabeaulac** [comment]
LocalStack logs
```
localstack_lsgdc  | botocore.errorfactory.ExpiredIteratorException: An error occurred (ExpiredIteratorException) when calling the GetRecords operation: Shard iterator has expired
localstack_lsgdc  | 2023-08-14T16:34:57.749  INFO --- [uncthread652] localstack.utils.threads   : Thread run method <bound method StreamEventSourceListener._listen_to_shard_and_invoke_lambda of <localstack.services.lambda_.event_source_listeners.dynamodb_event_source_listener.DynamoDBEventSourceListener object at 0xffff40762380>>({'function_arn': 'arn:aws:lambda:us-west-2:000000000000:function:lsgdc-user-ddb-stream-handler-lambda-local-e3cb206', 'stream_arn': 'arn:aws:dynamodb:us-west-2:000000000000:table/db-user-table-local/stream/2023-08-14T15:51:04.360', 'batch_size': 100, 'parallelization_factor': 1, 'lock_discriminator': 'dffc796e-d8a1-46bd-88d1-b551f0c7cbe1/arn:aws:dynamodb:us-west-2:000000000000:table/db-user-table-local/stream/2023-08-14T15:51:04.360/shardId-00000001692000000000-000000000000', 'shard_id': 'shardId-00000001692000000000-000000000000', 'stream_client': <localstack.aws.connect.MetadataRequestInjector object at 0xfffecc53b490>, 'shard_iterator': 'arn:aws:dynamodb:us-west-2:000000000000:table/db-user-table-local/stream/2023-08-14T15:51:04.360|1|AAAAAAAAAAGEQt0AAgO/LZXzERTHrs7iE0m2aBR8qdYCx0YpvyWlqyNiJy/A0ZL72KTudb0W0McXGNEy0emItthgq95X/iFJOoejjYG+YaE6g+Ekr+hf5L51a2X8MOoAHNETK/SdgFU+ISncuunWHEVNDvcXlMYPF2UBrxGuVl2RU2DBXd3eeMpsC77MhWaCSvPIBSGJk3sQIAzU7SdV4Pd+FLBS7VBK5uBQg9W4OS0MpXlVnHoZJA==', 'failure_destination': None, 'max_num_retries': inf}) failed: An error occurred (ExpiredIteratorException) when calling the GetRecords operation: Shard iterator has expired Traceback (most recent call last):
localstack_lsgdc  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/threads.py", line 58, in run
localstack_lsgdc  |     result = self.func(self.params, **kwargs)
localstack_lsgdc  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/lambda_/event_source_listeners/stream_event_source_listener.py", line 204, in _listen_to_shard_and_invoke_lambda
localstack_lsgdc  |     records_response = stream_client.get_records(
localstack_lsgdc  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 535, in _api_call
localstack_lsgdc  |     return self._make_api_call(operation_name, kwargs)
localstack_lsgdc  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 980, in _make_api_call
localstack_lsgdc  |     raise error_class(parsed_response, operation_name)
localstack_lsgdc  | botocore.errorfactory.ExpiredIteratorException: An error occurred (ExpiredIteratorException) when calling the GetRecords operation: Shard iterator has expired
localstack_lsgdc  |
localstack_lsgdc  | 2023-08-14T16:34:57.749 DEBUG --- [uncthread652] localstack.utils.threads   : FINISHED: <Future at 0xffff48abb970 state=finished raised ExpiredIteratorException>
```

**Comment by dominikschubert** [comment]
As a workaround in the meantime, a user reported that using `LATEST` instead of `TRIM_HORIZON` apparently fixes this issue.
