### ISSUE TITLE
bug: Unable to create lambda in Bitbucket Pipelines (Localstack:2.1.0)

### ISSUE THREAD

**Issue by ayeganyan** [localstack/localstack#8414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Status of newly created function is `failed` in `localstack:2.1.0` with strange message `Error while creating lambda: Docker not available` when Run it on Bitbucket Pipelines (Linux).
Here is the response of `awslocal get-function`:
```yaml
{
    "Configuration": {
        "FunctionName": "testlambda",
        "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:testlambda",
        "Runtime": "java11",
        "Role": "arn:aws:iam::000000000000:role/DummyRole",
        "Handler": "com.atlassian.lambda.demo.SNSEventLambdaHandler",
        "CodeSize": 16879215,
        "Description": "",
        "Timeout": 20,
        "MemorySize": 1024,
        "LastModified": "2023-06-01T11:41:10.853199+0000",
        "CodeSha256": "UAUOdvQlpQ+0lMZrw0RKHtPoRXwUsbJtAU9HObjD5Bc=",
        "Version": "$LATEST",
        "TracingConfig": {
            "Mode": "PassThrough"
        },
        "RevisionId": "fd58d635-6494-496e-a5c6-b1353d6f40c1",
        "State": "Failed",
        "StateReason": "Error while creating lambda: Docker not available",
        "StateReasonCode": "InternalError",
        "LastUpdateStatus": "Failed",
        "PackageType": "Zip",
        "Architectures": [
            "x86_64"
        ],
        "EphemeralStorage": {
            "Size": 512
        },
        "SnapStart": {
            "ApplyOn": "None",
            "OptimizationStatus": "Off"
        },
        "RuntimeVersionConfig": {
            "RuntimeVersionArn": "arn:aws:lambda:us-east-1::runtime:8eeff65f6809a3ce81507fe733fe09b835899b99481ba22fd75b5a7338290ec1"
        }
    },
    "Code": {
        "RepositoryType": "S3",
        "Location": "http://s3.localhost.localstack.cloud:4566/awslambda-us-east-1-tasks/snapshots/000000000000/testlambda-9393386f-65c9-4cea-bc82-67340676c5f9?AWSAccessKeyId=000000000000&Signature=Fktf2JMNjrVW9%2BdDJcPLlJ%2BUqXQ%3D&Expires=1685623274"
    }
}
```

Also I have this error in localstack logs:
```
2023-06-01T12:33:40.073 ERROR --- [Executor-1_0] l.services.awslambda.hints : Failed to pull Docker image because Docker is not available in the LocalStack container but required to run Lambda functions. Please add the Docker volume mount "/var/run/docker.sock:/var/run/docker.sock" to your LocalStack startup. https://docs.localstack.cloud/user-guide/aws/lambda/#docker-not-available
```
But volume is mounted (checked also with docker inspect)

Note the same thing works for Mac/darwin22.0 and  localstack:2.1.0
and also it worked both in Pipelines and Mac for localstack:1.4.0

### Expected Behavior

`awslocal get-function` should have `Active` state after the function creation.

### How are you starting LocalStack?

With a `docker run` command

### Steps To Reproduce

I run in the different way in production and this is just a way to reproduce the issue:

```shell
#!/usr/bin/env bash

echo "OS type: $OSTYPE"
CONTAINER=$(docker run -d --rm \
        -v "$(pwd)":/hello \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -e DEBUG=1 \
        localstack/localstack:2.1.0)

echo "Creating function..."
docker exec "$CONTAINER" awslocal lambda create-function --function-name testlambda --role arn:aws:iam::000000000000:role/DummyRole --runtime java11 --handler com.atlassian.lambda.demo.SNSEventLambdaHandler --zip-file fileb:///hello/dx-ref-java-lambda.jar --memory-size 1024 --timeout 20
sleep 3

echo "The function is:"
docker exec "$CONTAINER" awslocal lambda get-function --function-name testlambda
```

Error in Localstack container:
```
2023-06-02T15:17:26.074 DEBUG --- [Executor-1_0] l.u.c.docker_sdk_client    : Creating Docker SDK client failed: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

```

### Environment

```markdown
- OS:linux-gnu
- LocalStack:2.1.0
```

**Comment by ayeganyan** [comment]
Added `-e DOCKER_HOST="$BITBUCKET_DOCKER_HOST_INTERNAL":2375` to run command and it does not fail anymore...
