### ISSUE TITLE
Can't send message to SQS via Lamdba | Connection refused

### ISSUE THREAD

**Issue by hpiatkowiak** [localstack/localstack#845]
Hi, 

i've worked with localstack for the last weeks without any problems (under MacOS). Now, I'm trying to setup the same stack under an Ubuntu OS. However, the connection from lambda to SQS does not work as it works under MacOS. 

When i try to invoke my function from my localhost, I receive an connection error. 

```
> 2018-07-10T08:08:14.873Z   67c2f323-3b06-184b-9fe2-1f6311874155    { Error: connect ECONNREFUSED 127.0.0.1:4576
>     at Object.exports._errnoException (util.js:1018:11)
>     at exports._exceptionWithHostPort (util.js:1041:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
>   message: 'connect ECONNREFUSED 127.0.0.1:4576',
>   code: 'NetworkingError',
>   errno: 'ECONNREFUSED',
>   syscall: 'connect',
>   address: '127.0.0.1',
>   port: 4576,
>   region: 'us-east-1',
>   hostname: '127.0.0.1',
>   retryable: true,
>   time: 2018-07-10T08:08:14.872Z } 'Error: connect ECONNREFUSED 127.0.0.1:4576\n    at Object.exports._errnoException (util.js:1018:11)\n    at exports._exceptionWithHostPort (util.js:1041:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)'
> 2018-07-10T08:08:14.875Z   67c2f323-3b06-184b-9fe2-1f6311874155    Processed data null
```

What I've found out is that the env variable LOCALSTACK_HOST is different under MacOS (192.168.x.x) as it is under Ubuntu (127.0.0.1). On both OS I'm using docker-compose to run localstack. 

```
version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4583:4567-4583"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG-1 }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Inside my lambda function, I'm using process.env.LOCALSTACK_HOSTNAME to address the right endpoint (as read in couple of issues here). However, the connection is still refused under Ubuntu.

```
exports.handler = (event, context, callback) => {
    const sqsUrl = process.env.LOCALSTACK_HOSTNAME + ":4576/queue/default";
    console.log("SQS_URL=" + sqsUrl);

    const sqsMessageGroupId = process.env.SQS_MESSAGE_GROUP_ID;
    console.log("SQS_MESSAGE_GROUP_ID=" + sqsMessageGroupId);
    console.log(process.env);
    if (event) {

        console.log(JSON.stringify(event));
        console.log(context);

        var SQS = new AWS.SQS();

        var sqsParams = {
            QueueUrl: sqsUrl,
            MessageGroupId: sqsMessageGroupId,
            MessageBody: JSON.stringify(event)
        };

        SQS.sendMessage(sqsParams, function (err, data) {
            if (err) {
                console.log(err, err.stack);
                callback(new Error(err));
            }

            console.log("Processed data", data);
            callback(null, `successfully processed ${event}.`);
        });

    } else {
        callback(null, "no records to sync");
    }


    callback(null, `Successfully processed ${event} records.`);
};
```

Is there any know issue with executing lambda and connecting to other AWS services. I already read about the usage of the process.env.LOCALSTACK_HOSTNAME but since I'm using it and the connection still does not work, I  wonder what I'm doing wrong. 

Does someone has any ideas or suggestions ?

**Comment by bnegrao** [comment]
Did you remove all the iptables rules from your ubuntu?

try this

```
# remove iptables rules
echo "Removing iptables rules, setting all default policies do ACCEPT..."
sudo iptables -F 
sudo iptables -P INPUT ACCEPT
sudo iptables -P FORWARD ACCEPT
sudo iptables -P OUTPUT ACCEPT
```
If that fixes the issue, try to use only "sudo iptables -P FORWARD ACCEPT", I think that should be the culprit.

**Comment by hpiatkowiak** [comment]
Thank you for getting back. 

I've removed all entries from my iptables and restarted docker. Docker has added a couple of new entries to the iptables. 

However, the problem still exists. Invoking the Lambda and trying to put a message into the queue produces the same connection error as mentioned above.
