### ISSUE TITLE
bug: Golang SNS client return KeyError: '' error 

### ISSUE THREAD

**Issue by Maxfer4Maxfer** [localstack/localstack#8504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I am trying to execute snsClient.ListTopics or snsClient.CreateTopic I've got the error:
```
operation error SNS: ListTopics, exceeded maximum number of attempts, 3, https response error StatusCode: 500, RequestID: 80f5e2c2-9f2e-4c6e-9f7f-5666f36dfecc, InternalError: exception while calling sns.ListTopics: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 123, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 93, in __call__
    skeleton_response = self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 166, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/forwarder.py", line 67, in _call
    return fallthrough_handler(context, req)
  File "/opt/code/localstack/localstack/services/moto.py", line 83, in _proxy_moto
    return call_moto(context)
  File "/opt/code/localstack/localstack/services/moto.py", line 46, in call_moto
    return dispatch_to_backend(context, dispatch_to_moto, include_response_metadata)
  File "/opt/code/localstack/localstack/aws/forwarder.py", line 120, in dispatch_to_backend
    http_response = http_request_dispatcher(context)
  File "/opt/code/localstack/localstack/services/moto.py", line 111, in dispatch_to_moto
    response = dispatch(request, request.url, request.headers)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/responses.py", line 231, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/responses.py", line 375, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/responses.py", line 464, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/sns/responses.py", line 125, in list_topics
    topics, next_token = self.backend.list_topics(next_token=next_token)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/sns/responses.py", line 24, in backend
    return sns_backends[self.current_account][self.region]
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/base_backend.py", line 247, in __getitem__
    return super().__getitem__(region_name)
KeyError: ''
```

But aws cli works correctly 
```
❯ aws --profile local --endpoint-url=http://localhost:4566  sns list-topics | cat
------------
|ListTopics|
+----------+

❯ cat ~/.aws/credentials
[local]
aws_access_key_id = dummy
aws_secret_access_key = dummy

❯ cat ~/.aws/config
[profile local]
region = eu-central-1
output = table

```

And also if I try execute another aws service with the same awsconfig from golang code (sqs list-queues) it works also.
The problem only with subcommand related to sns.

### Expected Behavior

snsClient.ListTopics returns actual list of SNS topics and there is no error

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)  

  docker-compose.yaml
```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=sns:4575,sqs:4576
      - DEFAULT_REGION=eu-central-1
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

  main.go
```
package main

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/sns"
	"github.com/aws/aws-sdk-go-v2/service/sqs"
)

func main() {
	awsconfig, _ := awscfg(context.Background(), "http://localhost:4566")

	sqsClient := sqs.NewFromConfig(awsconfig)
	// works
	queues, err := sqsClient.ListQueues(context.Background(), &sqs.ListQueuesInput{})

	fmt.Println(queues, err)

	snsClient := sns.NewFromConfig(awsconfig)

	// failure
	topics, err := snsClient.ListTopics(context.Background(), &sns.ListTopicsInput{})

	fmt.Println(topics, err)
}

func awscfg(ctx context.Context, endpointURL string) (aws.Config, error) {
	return awsconfig.LoadDefaultConfig(ctx,
		awsconfig.WithRegion("eu-central-1"),
		awsconfig.WithEndpointResolverWithOptions(
			aws.EndpointResolverWithOptionsFunc(func(service, region string, options ...interface{}) (aws.Endpoint, error) {
				return aws.Endpoint{
					URL: endpointURL,
				}, nil
			})),
		awsconfig.WithCredentialsProvider(
			aws.CredentialsProviderFunc(func(ctx context.Context) (aws.Credentials, error) {
				return aws.Credentials{
					AccessKeyID:     "dummy",
					SecretAccessKey: "dummy",
				}, nil
			}),
		),
	)
}
```

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS
- LocalStack:
LocalStack version: 2.1.1.dev
LocalStack build date: 2023-06-14
LocalStack build git hash: 7e002033
```

**Comment by Maxfer4Maxfer** [comment]
Finally I found the solution.
I miss the SigningRegion parameter when creating awsconfig.

The fully working sample:
```
package main

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/sns"
)

func main() {
	awsconfig, _ := awscfg(ctx, "us-west-2", "http://localhost:4566")

	snsClient := sns.NewFromConfig(awsconfig)

	topics, err := snsClient.ListTopics(context.Background(), &sns.ListTopicsInput{})

	fmt.Println(topics, err)
}

func awscfg(ctx context.Context, region string, endpointURL string) (aws.Config, error) {
	return awsconfig.LoadDefaultConfig(ctx,
		awsconfig.WithRegion(region),
		awsconfig.WithEndpointResolverWithOptions(
			aws.EndpointResolverWithOptionsFunc(func(service, region string, options ...interface{}) (aws.Endpoint, error) {
				return aws.Endpoint{
					SigningRegion: region,
					URL:           endpointURL,
				}, nil
			})),
		awsconfig.WithCredentialsProvider(
			aws.CredentialsProviderFunc(func(ctx context.Context) (aws.Credentials, error) {
				return aws.Credentials{
					AccessKeyID:     "dummy",
					SecretAccessKey: "dummy",
				}, nil
			}),
		),
	)
}
```
