### ISSUE TITLE
bug: Route53 create hosted zone route53.CreateHostedZone fails with 500

### ISSUE THREAD

**Issue by estebane-frb** [localstack/localstack#8514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 123, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 93, in __call__
    skeleton_response = self.skeleton.invoke(context)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 166, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/forwarder.py", line 60, in _call
    return handler(context, req)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/api/core.py", line 167, in operation_marker
    return fn(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/route53/provider.py.enc", line 22, in create_hosted_zone
    def create_hosted_zone(self,context,request):B=context;A=call_moto(B);C=route53_backends[B.account_id][_A];D=A['HostedZone']['Id'].split('/')[-1];E=C.zones[D];F=f"dns.{LOCALHOST_HOSTNAME}";E.delegation_set.name_servers=A['DelegationSet']['NameServers']=[F];return CreateHostedZoneResponse(**A)
KeyError: 'DelegationSet'

### Expected Behavior

Should be able to create private hosted zone with 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose file:

version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-pro # required for Pro
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
      - "127.0.0.1:53:53" # DNS config (required for Pro)
      - "127.0.0.1:53:53/udp" # DNS config (required for Pro)
      - "127.0.0.1:443:443" # LocalStack HTTPS Gateway (required for Pro)
    environment:
      - DEBUG=1
      - PERSISTENCE=${PERSISTENCE-}
      - LOCALSTACK_API_KEY=XXXXXXXXXXX # required for Pro - redacted
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    Terraform: 

    resource "aws_route53_zone" "private" {
    name = "example.com"
  
    vpc {
      vpc_id = aws_vpc.main.id
    }
  }

### Environment

```markdown
- OS:Debian Bullseye (with Latest Localstack-pro docker image). But also tried previous version: 2.1.0
- LocalStack:Localstack-pro docker image
```

### Anything else?

This is working fine when doing a **public** route53 hosted zone.

**Comment by estebane-frb** [comment]
It's fixed. Thank you so much @joe4dev !

**Comment by joe4dev** [comment]
You are welcome @estebane-frb 
We are excited everything is working 🚀
