### ISSUE TITLE
bug: lambda docker executor fails when using auto-generated port

### ISSUE THREAD

**Issue by LaurentGoderre** [localstack/localstack#8533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the Remote Debugging config from the docs for Lambda when debugging multiple lambda and trying to use random port, the containers fail to start.

docker-compose.yml

```yaml
localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - LAMBDA_DOCKER_FLAGS=-e NODE_OPTIONS=--inspect=0.0.0.0:9229 -p 9229
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMP_DIR:-./.localstack}:${TMP_DIR:-/tmp/localstack}"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Then

```bash
serverless deploy --stage local
serverless invoke --stage local --function hello
```

Localstack logs

```
fable-app-aws-1   | 2023-03-31T17:59:01.339  INFO --- [ncthread4223] localstack.utils.threads   : Thread run method <function LambdaExecutor.execute.<locals>.do_execute at 0x7f1eafddcca0>(None) failed: ('Invalid port string provided: %s', '9229') Traceback (most recent call last):
fable-app-aws-1   |   File "/opt/code/localstack/localstack/utils/threads.py", line 58, in run
fable-app-aws-1   |     result = self.func(self.params, **kwargs)
fable-app-aws-1   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 484, in do_execute
fable-app-aws-1   |     return _run(func_arn=func_arn)
fable-app-aws-1   |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 183, in wrapped
fable-app-aws-1   |     raise e
fable-app-aws-1   |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 179, in wrapped
fable-app-aws-1   |     result = func(*args, **kwargs)
fable-app-aws-1   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 471, in _run
fable-app-aws-1   |     raise e
fable-app-aws-1   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 467, in _run
fable-app-aws-1   |     result = self._execute(lambda_function, inv_context)
fable-app-aws-1   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 931, in _execute
fable-app-aws-1   |     return super(LambdaExecutorReuseContainers, self)._execute(func_arn, *args, **kwargs)
fable-app-aws-1   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 790, in _execute
fable-app-aws-1   |     result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
fable-app-aws-1   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 667, in run_lambda_executor
fable-app-aws-1   |     result, log_output = self.execute_in_container(
fable-app-aws-1   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 847, in execute_in_container
fable-app-aws-1   |     container_info = self.prime_docker_container(
fable-app-aws-1   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 978, in prime_docker_container
fable-app-aws-1   |     self.create_container(lambda_function, env_vars, lambda_cwd, docker_flags)
fable-app-aws-1   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1064, in create_container
fable-app-aws-1   |     container_id = DOCKER_CLIENT.create_container(
fable-app-aws-1   |   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 523, in create_container
fable-app-aws-1   |     parsed_flags = Util.parse_additional_flags(
fable-app-aws-1   |   File "/opt/code/localstack/localstack/utils/container_utils/container_client.py", line 978, in parse_additional_flags
fable-app-aws-1   |     raise ValueError("Invalid port string provided: %s", flag)
fable-app-aws-1   | ValueError: ('Invalid port string provided: %s', '9229')
```

Looking is this code, it expected a colon to split on https://github.com/localstack/localstack/blob/master/localstack/utils/container_utils/container_client.py#L1104-L1115

I then tried to use

```
 environment:
      - LAMBDA_DOCKER_FLAGS=-e NODE_OPTIONS=--inspect=0.0.0.0:9229 -p :9229
```

I then ended up with a different error

```
fable-app-aws-1   | 2023-06-20T14:41:18.409  INFO --- [ncthread8483] localstack.utils.threads   : Thread run method <function LambdaExecutor.execute.<locals>.do_execute at 0x7f93f7c8dbd0>(None) failed: invalid literal for int() with base 10: '' Traceback (most recent call last):
fable-app-aws-1   |   File "/opt/code/localstack/localstack/utils/threads.py", line 58, in run
fable-app-aws-1   |     result = self.func(self.params, **kwargs)
fable-app-aws-1   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 484, in do_execute
fable-app-aws-1   |     return _run(func_arn=func_arn)
fable-app-aws-1   |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 183, in wrapped
fable-app-aws-1   |     raise e
fable-app-aws-1   |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 179, in wrapped
fable-app-aws-1   |     result = func(*args, **kwargs)
fable-app-aws-1   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 471, in _run
fable-app-aws-1   |     raise e
fable-app-aws-1   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 467, in _run
fable-app-aws-1   |     result = self._execute(lambda_function, inv_context)
fable-app-aws-1   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 790, in _execute
fable-app-aws-1   |     result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
fable-app-aws-1   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 667, in run_lambda_executor
fable-app-aws-1   |     result, log_output = self.execute_in_container(
fable-app-aws-1   |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1276, in execute_in_container
fable-app-aws-1   |     container_id = DOCKER_CLIENT.create_container(
fable-app-aws-1   |   File "/opt/code/localstack/localstack/utils/container_utils/docker_sdk_client.py", line 514, in create_container
fable-app-aws-1   |     parsed_flags = Util.parse_additional_flags(
fable-app-aws-1   |   File "/opt/code/localstack/localstack/utils/container_utils/container_client.py", line 956, in parse_additional_flags
fable-app-aws-1   |     host_port = int(host_port)
fable-app-aws-1   | ValueError: invalid literal for int() with base 10: ''
```

### Expected Behavior

A new container is started for the function with an auto-assigned host port mapped to the container port.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

serverless deploy --stage local
serverless invoke --stage local --function hello

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by LaurentGoderre** [comment]
#7989 was closed while still experiencing the issue

**Comment by LaurentGoderre** [comment]
I also tried `LAMBDA_DOCKER_FLAGS: '-p :9229'` but it didn't work because it expected a non blank host port.

I tried an another way to get around that problem by using the Docker syntax that allows to specify a port range for a random port to be selected (`-p 8080-8090:8080` but this didn't work because instead it tried to bind all the ports in the range.

**Comment by LaurentGoderre** [comment]
Also tried `--expose 9229 -P` which would give the expected result but getting an error

```
Flag ---expose is currently not supported by this Docker client.
```
