### ISSUE TITLE
bug: Docker image fails to shutdown when not able to download SSL cert

### ISSUE THREAD

**Issue by toadzky** [localstack/localstack#8604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to run the localstack docker image (I'm using 2.0), it fails to start. The container doesn't error and shutdown like you would expect, it just sits there in a broken state refusing to shutdown. Settings the `SKIP_SSL_CERT_DOWNLOAD` property fixes the issue. I'm on Ubuntu 22.04. The problem exists on 2.0 and 2.1, but it didn't happen when I first started using the 2.x images.

### Expected Behavior

The container should download the SSL cert and start *or* show the error and terminate the container as a failed launch.

### How are you starting LocalStack?

With a docker command or using testcontainers in java.

### Steps To Reproduce

docker run -p 4566:4566 -e DEBUG=true localstack/localstack:2.1

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: 2.0, 2.1
```

### Anything else?

```
LocalStack supervisor: starting
LocalStack supervisor: localstack process (PID 15) starting

LocalStack version: 2.1.0
LocalStack build date: 2023-05-25
LocalStack build git hash: 67b55096

2023-07-03T15:39:57.846 DEBUG --- [  MainThread] stevedore._cache           : reading /root/.cache/python-entrypoints/ccd88d0aa2b1947f243f2cbc674104fe0eeb286df48ae4b431534e29c134a33c
2023-07-03T15:39:57.857 DEBUG --- [  MainThread] stevedore._cache           : writing to /root/.cache/python-entrypoints/ccd88d0aa2b1947f243f2cbc674104fe0eeb286df48ae4b431534e29c134a33c
2023-07-03T15:39:57.857 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='_patch_botocore_json_parser', value='localstack.aws.client:_patch_botocore_json_parser', group='localstack.hooks.on_infra_start')
2023-07-03T15:39:57.858 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='_publish_config_as_analytics_event', value='localstack.runtime.analytics:_publish_config_as_analytics_event', group='localstack.hooks.on_infra_start')
2023-07-03T15:39:57.858 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='_publish_container_info', value='localstack.runtime.analytics:_publish_container_info', group='localstack.hooks.on_infra_start')
2023-07-03T15:39:57.858 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='_run_init_scripts_on_start', value='localstack.runtime.init:_run_init_scripts_on_start', group='localstack.hooks.on_infra_start')
2023-07-03T15:39:57.859 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='deprecation_warnings', value='localstack.plugins:deprecation_warnings', group='localstack.hooks.on_infra_start')
2023-07-03T15:39:57.859 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_partition_adjusting_proxy_listener', value='localstack.plugins:register_partition_adjusting_proxy_listener', group='localstack.hooks.on_infra_start')
2023-07-03T15:39:57.859 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='validate_configuration', value='localstack.services.awslambda.plugins:validate_configuration', group='localstack.hooks.on_infra_start')
2023-07-03T15:39:57.862 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_pickle_patches_runtime', value='localstack_persistence.pickling.__plugins__:register_pickle_patches_runtime', group='localstack.hooks.on_infra_start')
2023-07-03T15:39:57.863 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_public_cloudpods_endpoints', value='localstack_persistence.pods.__plugins__:register_public_cloudpods_endpoints', group='localstack.hooks.on_infra_start')
2023-07-03T15:39:57.864 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_reset_state_resource', value='localstack_persistence.reset.__plugins__:register_reset_state_resource', group='localstack.hooks.on_infra_start')
2023-07-03T15:39:57.865 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_state_load_strategy', value='localstack_persistence.snapshot.__plugins__:register_state_load_strategy', group='localstack.hooks.on_infra_start')
2023-07-03T15:39:57.992  WARN --- [  MainThread] l.services.internal        : Enabling diagnose endpoint, please be aware that this can expose sensitive information via your network.
2023-07-03T15:39:57.994 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_state_resource', value='localstack_persistence.snapshot.__plugins__:register_state_resource', group='localstack.hooks.on_infra_start')
2023-07-03T15:39:57.994 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_state_save_strategy', value='localstack_persistence.snapshot.__plugins__:register_state_save_strategy', group='localstack.hooks.on_infra_start')
2023-07-03T15:39:57.994 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._patch_botocore_json_parser = <function _patch_botocore_json_parser at 0x7f3213e5ab00>)
2023-07-03T15:39:57.995 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:_patch_botocore_json_parser
2023-07-03T15:39:57.995 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._publish_config_as_analytics_event = <function _publish_config_as_analytics_event at 0x7f3213e5ae60>)
2023-07-03T15:39:57.995 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:_publish_config_as_analytics_event
2023-07-03T15:39:57.995 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._publish_container_info = <function _publish_container_info at 0x7f3213e5b130>)
2023-07-03T15:39:57.995 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:_publish_container_info
2023-07-03T15:39:57.995 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._run_init_scripts_on_start = <function _run_init_scripts_on_start at 0x7f3213e5bd90>)
2023-07-03T15:39:57.995 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:_run_init_scripts_on_start
2023-07-03T15:39:57.995 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.deprecation_warnings = <function deprecation_warnings at 0x7f3213e805e0>)
2023-07-03T15:39:57.995 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:deprecation_warnings
2023-07-03T15:39:57.995 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_partition_adjusting_proxy_listener = <function register_partition_adjusting_proxy_listener at 0x7f3213e804c0>)
2023-07-03T15:39:57.995 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:register_partition_adjusting_proxy_listener is disabled
2023-07-03T15:39:57.996 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.validate_configuration = <function validate_configuration at 0x7f3213e827a0>)
2023-07-03T15:39:57.996 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:validate_configuration
2023-07-03T15:39:57.996 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_pickle_patches_runtime = <function register_pickle_patches_runtime at 0x7f3213e829e0>)
2023-07-03T15:39:57.996 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:register_pickle_patches_runtime
2023-07-03T15:39:57.996 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_public_cloudpods_endpoints = <function register_public_cloudpods_endpoints at 0x7f3213e82d40>)
2023-07-03T15:39:57.996 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:register_public_cloudpods_endpoints
2023-07-03T15:39:57.996 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_reset_state_resource = <function register_reset_state_resource at 0x7f3213e82ef0>)
2023-07-03T15:39:57.996 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:register_reset_state_resource is disabled
2023-07-03T15:39:57.996 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_state_load_strategy = <function register_state_load_strategy at 0x7f3213b6a3b0>)
2023-07-03T15:39:57.996 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:register_state_load_strategy is disabled
2023-07-03T15:39:57.996 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_state_resource = <function register_state_resource at 0x7f3213b6a290>)
2023-07-03T15:39:57.996 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:register_state_resource is disabled
2023-07-03T15:39:57.996 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_state_save_strategy = <function register_state_save_strategy at 0x7f3213b6a5f0>)
2023-07-03T15:39:57.996 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:register_state_save_strategy is disabled
2023-07-03T15:39:57.997 DEBUG --- [  MainThread] localstack.runtime.init    : Init scripts discovered: {BOOT: [], START: [], READY: [], SHUTDOWN: []}
2023-07-03T15:39:57.997 DEBUG --- [  MainThread] localstack.plugins         : Checking for the usage of deprecated community features and configs...
2023-07-03T15:39:58.148 DEBUG --- [  MainThread] localstack.utils.threads   : start_thread called without providing a custom name
2023-07-03T15:39:58.155 DEBUG --- [-functhread2] localstack.utils.ssl       : Attempting to download local SSL certificate file
2023-07-03T15:40:12.874  WARN --- [  MainThread] localstack.utils.net       : Error connecting to TCP port localhost:4566 (result=111)
2023-07-03T15:40:12.874  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "start_runtime_components" took 14726.46ms
Unexpected exception while starting infrastructure: gave up waiting for edge server on 0.0.0.0:4566 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 395, in start_infra
    thread = do_start_infra(asynchronous, apis, is_in_docker)
  File "/opt/code/localstack/localstack/services/infra.py", line 487, in do_start_infra
    thread = start_runtime_components()
  File "/opt/code/localstack/localstack/utils/bootstrap.py", line 70, in wrapped
    return f(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/infra.py", line 480, in start_runtime_components
    raise TimeoutError(
TimeoutError: gave up waiting for edge server on 0.0.0.0:4566
```

**Comment by alexrashed** [comment]
Hi @toadzky!
I am not sure what your issue is currently.
The download of the keypair in the first place, or the fact that LocalStack does not shut down if it cannot start the HTTP server? How does your environment look like, which circumvents you from downloading the keypair?

The config (`SKIP_SSL_CERT_DOWNLOAD`) is there to circumvent this issue (with the obvious downside of potential issues with the TLS connections).
It's also best practice to mount the [LocalStack Volume directory](https://docs.localstack.cloud/references/filesystem/#localstack-volume), to allow LocalStack to cache / store artifacts across Docker container runs.

**Comment by toadzky** [comment]
the issue is more that it doesn't shut down correctly. the cause of the ssl download failure seems to be something with my docker process - restarting it makes the error go away - but when it happens, the localstack container just lives on as a zombie that can't do anything.

i'm using localstack for testing during my build processes and locally running those same tests - so no https is necessary and mounting a local volume doesn't really make much sense since i want a clean environment for each test run (i reuse the container for all the tests in a single run).

**Comment by alexrashed** [comment]
> the issue is more that it doesn't shut down correctly. the cause of the ssl download failure seems to be something with my docker process - restarting it makes the error go away - but when it happens, the localstack container just lives on as a zombie that can't do anything.

Okay, thanks for the clarification. It makes sense to terminate if we really can't start the server.

> i'm using localstack for testing during my build processes and locally running those same tests - so no https is necessary and mounting a local volume doesn't really make much sense since i want a clean environment for each test run (i reuse the container for all the tests in a single run).

It doesn't mean that LocalStack instances share the state, they share certain folders. You can find more info on that in the docs I linked. The main benefit is to reuse certain packages which are downloaded on demand each time otherwise. This would save quite some time and bandwidth in case you are using these services.

**Comment by HarshCasper** [comment]
Due to the forthcoming changes in our distribution and development model ([read more](https://blog.localstack.cloud/the-road-ahead-for-localstack/)), this issue tracker is no longer being maintained, and this issue is now being closed. If you'd like us to take a look or need further support, please reach out through one of our support channels:

-   💬 [GitHub Discussions](https://github.com/orgs/localstack/discussions)
-   📖 [Help & Support](https://docs.localstack.cloud/aws/getting-started/help-support/)
