### ISSUE TITLE
LocalstackDockerTestRunner in Windows

### ISSUE THREAD

**Issue by srep2512** [localstack/localstack#862]
I currently ran into the issue that my container is starting on my windows 10 machine but during startup it won't connect to it.

`` 
cloud.localstack.docker.exception.LocalstackDockerException: Could not start the localstack docker container.
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
Caused by: java.lang.IllegalStateException: Could not find token: Ready\. in docker logs.
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
``

i've already checked with docker that the container is running. Any suggests?

**Comment by srep2512** [comment]
Ok i used the following @LocalstackDockerProperties(randomizePorts = true, services = { "sqs", "s3" }) definition and figured out that sqs messed things up. Could anyone explain why? :)
