### ISSUE TITLE
Java Lambda runtime fails to start

### ISSUE THREAD

**Issue by alexmihai1984** [localstack/localstack#8637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Calling a Java Lambda errors out with the message bellow. I tried `java8`,` java11` and `java17` as runtimes, they all behave the same. Note that I also tried a `nodejs16.x` lambda and that one works. The request hangs forever, while the localstack logs show this error every second.

```
localstack_main  | 2023-07-06T11:09:15.755 DEBUG --- [da:$LATEST_0] l.s.a.i.docker_runtime_exe : Executing start docker executor pro-hook for function arn:aws:lambda:us-east-1:000000000000:function:my-lambda:$LATEST
localstack_main  | 2023-07-06T11:09:15.756  WARN --- [da:$LATEST_0] l.s.a.i.runtime_environmen : Failed to start runtime environment for ID=f03a4a00b064aa5a2f56fa7b30c56872 with: argument of type 'NoneType' is not iterable
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/awslambda/invocation/runtime_environment.py", line 172, in start
localstack_main  |     self.runtime_executor.start(self.get_environment_variables())
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/awslambda/invocation/docker_runtime_executor.py", line 299, in start
localstack_main  |     lambda_hooks.start_docker_executor.run(container_config, self.function_version)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/runtime/hooks.py", line 64, in run_in_order
localstack_main  |     fn_plugin(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/plugin/core.py", line 183, in __call__
localstack_main  |     return self.fn(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/awslambda/invocation/docker_runtime_executor_hooks.py.enc", line 20, in start_docker_executor_hook
localstack_main  |     if E in B.config.environment:LOG.warning(I)
localstack_main  | TypeError: argument of type 'NoneType' is not iterable
```

### Expected Behavior

The Lambda should run without errors (it works in AWS).

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - LS_LOG=trace-internal
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=<my-api-key>
      - LAMBDA_DOCKER_FLAGS="-e SUB_ENV=dev"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
aws --endpoint-url=http://localhost:4566\
  lambda create-function \
  --function-name my-lambda \
  --runtime java17 \
  --handler com.lambda.auth.AuthLambdaHandler::handleRequest \
  --memory-size 256 \
  --zip-file fileb://../target/my-lambda-1.0-SNAPSHOT.jar \
  --role arn:aws:iam::111111111111:role/apigw

aws --endpoint-url=http://localhost:4566\
  lambda invoke --function-name\
  my-lambda --invocation-type RequestResponse out
```

### Environment

```markdown
- OS: Win 10
- LocalStack: PRO Latest

Note that I'm behind a corporate firewall, which might block some stuff, but I can confirm it's able to pull AWS images (`docker pull public.ecr.aws/lambda/java:17` works).
```

**Comment by alexmihai1984** [comment]
Actually, I just tried and it works fine in community, the error only occurs in pro. I need to use pro for other features though. I'll try to reach out to support.

**Comment by dfangl** [comment]
I have a fix for this in the pipeline, which will fix this issue. Sorry for the inconvenience. For now, you can set `DNS_ADDRESS=0` when starting LocalStack, which should unblock you.

**Comment by dfangl** [comment]
This should be fixed now, even without the workaround. Thank you for reporting this!
