### ISSUE TITLE
bug: AppSync InternalError ("Unable to find operation for request to service appsync: POST /graphql")

### ISSUE THREAD

**Issue by sc0ttdav3y** [localstack/localstack#8656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi :wave: I'm new to LocalStack and am on the latest version 2.1.1. 

I have a basic serverless config with AppSync and a basic query and HTTP resolver, configured as a simple hello-world. It deploys okay in localstack. I've got a pro licence key installed and working and see `Successfully activated API key` in the debug logs.

When I hit the endpoint I get an internal error response as follows, and no traffic reaches the endpoint itself.

```json
{
  "__type": "InternalError",
  "message": "exception while calling appsync with unknown operation: Traceback...*snipped, see below*"
}
```

I have included the traceback and debug logs below. 

The endpoint is another docker container exposed to `http://host.docker.internal:3001`. I can manually connect to the resolver via `wget` from the `localstack-main` docker container so I know networking is fine.

I've spent 3 days digging, searching, simplifying and deep-diving in localstack code before coming here with an issue report. I'm trying to ascertain whether the problem is with LocalStack or my config, and how to get a working hello-world AppSync service. 

### Expected Behavior

* I expect AppSync will route my query to the my resolver
* I expect HTTP resolver to connect to the back-end 
* If this turns out to by my mistake, then I expect a clearer error message in the logs that can help me diagnose it ;-) 

### How are you starting LocalStack?

```
DEBUG=1 localstack start
```

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
DEBUG=1 localstack start
```

In the logs, it starts fine and I can see `Successfully activated API key` so I know i've got the pro extension.

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Deploying my stack

```
npx serverless deploy --stage=local --force  --verbose
```

This runs fine, and I see this at the end:

```

✔ Service deployed to stack blue-local (6s)


Stack Outputs:
  ServerlessDeploymentBucketName: blue-local-sls-deploy
  GraphQlApiKeyDefault: 12706ab2
  GraphQlApiId: 030ccdd4e08c48e39fe3a6e6f0
  GraphQlApiUrl: http://030ccdd4e08c48e39fe3a6e6f0.appsync-api.localhost.localstack.cloud:4566/graphql

```

Calling my HTTP endpoint using the provided URL:

```
POST http://XXX.appsync-api.localhost.localstack.cloud:4566/graphql
Accept: application/json
Content-Type: application/json;charset=UTF-8
x-api-key: XXXX

{
  "query": "{ ping(site: \"test1\") { userId } }"
}

```

This returns HTTP 500 to the client with the following output:

```
HTTP/1.1 500 
Content-Type: application/json
X-Amzn-Errortype: InternalError
Content-Length: 1907
x-amzn-requestid: 011a328e-9a7a-4764-a078-d14e3573e7e5
x-amz-request-id: 011a328e-9a7a-4764-a078-d14e3573e7e5
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Headers: authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request
Access-Control-Expose-Headers: etag,x-amz-version-id
date: Sat, 08 Jul 2023 04:00:35 GMT
server: hypercorn-h11

{
  "__type": "InternalError",
  "message": "exception while calling appsync with unknown operation: Traceback (most recent call last):\n  File \"/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/protocol/parser.py\", line 557, in parse\n    operation, uri_params = self._operation_router.match(request)\n  File \"/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/protocol/op_router.py\", line 317, in match\n    rule, args = matcher.match(path, method=method, return_rule=True)\n  File \"/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/routing/map.py\", line 655, in match\n    raise NotFound() from None\nwerkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/chain.py\", line 90, in handle\n    handler(self, self.context, response)\n  File \"/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py\", line 64, in __call__\n    return self.parse_and_enrich(context)\n  File \"/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py\", line 77, in parse_and_enrich\n    operation, instance = parser.parse(context.request)\n  File \"/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/protocol/parser.py\", line 172, in wrapper\n    return func(*args, **kwargs)\n  File \"/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/protocol/parser.py\", line 559, in parse\n    raise OperationNotFoundParserError(\nlocalstack.aws.protocol.parser.OperationNotFoundParserError: Unable to find operation for request to service appsync: POST /graphql\n"
}
```

In the logs:

```
2023-07-08T03:44:37.795 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/protocol/parser.py", line 557, in parse
operation, uri_params = self._operation_router.match(request)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/protocol/op_router.py", line 317, in match
rule, args = matcher.match(path, method=method, return_rule=True)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 655, in match
raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/chain.py", line 90, in handle
handler(self, self.context, response)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 64, in __call__
return self.parse_and_enrich(context)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 77, in parse_and_enrich
operation, instance = parser.parse(context.request)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/protocol/parser.py", line 172, in wrapper
return func(*args, **kwargs)
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/protocol/parser.py", line 559, in parse
raise OperationNotFoundParserError(
localstack.aws.protocol.parser.OperationNotFoundParserError: Unable to find operation for request to service appsync: POST /graphql
2023-07-08T03:44:37.802  INFO --- [   asgi_gw_1] localstack.request.http    : POST /graphql => 500
```

### Calling the endpoint using `localhost:4566`:

Interestingly, if I instead call `POST http://localhost:4566/graphql`, then it looks more promising to the client as I get a 200 response, but it still doesn't work.

```
HTTP/1.1 200 
Content-Type: text/plain; charset=utf-8
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Headers: authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request
Access-Control-Expose-Headers: etag,x-amz-version-id
Content-Length: 0
date: Sat, 08 Jul 2023 03:59:00 GMT
server: hypercorn-h11

<Response body is empty>
```

and in the debug logs:

```
2023-07-08T03:59:00.177 DEBUG --- [   asgi_gw_0] l.aws.handlers.service     : no service set in context, skipping request parsing
2023-07-08T03:59:00.178  INFO --- [   asgi_gw_0] localstack.request.http    : POST /graphql => 200
```

### Environment

- OS: MacOS Ventura 13.4.1 on an M2
- LocalStack: 2.1.1 with pro license 

#### My `serverless.yml`:

```
service: ${env:SERVICE}
frameworkVersion: '3'
useDotenv: true
plugins:
  - serverless-localstack
  - serverless-appsync-plugin
  - serverless-deployment-bucket
provider:
  name: aws
  region: ${env:REGION, 'ap-southeast-2'}
  stage: local
  deploymentBucket:
    name: "${self:service}-${sls:stage}-sls-deploy"
custom:
  appSync:
    name: test-api
    schema: ./serverless/local/schema.graphql
    authenticationType: API_KEY
    dataSources:
      - type: HTTP
        name: RestDataSource
        description: All the REST APIs delivered over API Gateway
        config:
          endpoint: "http://host.docker.internal:3001/"
    mappingTemplatesLocation: './appsync/resolvers'
    mappingTemplates:
      - type: Query
        field: ping
        dataSource: RestDataSource
        request: query/genericRestRequest.vtl
        response: query/genericRestResponse.vtl
        substitutions:
          url: "api/json/graphql-ping"
  localstack:
    stages:
      - local
```

I have also tried with this in the localstack config as per the appsync example in GitHub but it made no difference:

```
  localstack:
    endpoints:
      AppSync: http://localhost:4605
```

#### My schema

```
schema {
    query: Query
}

type Query {
    ping(site: String!): PingQResult!
}

type PingQResult {
    status: String!
    userId: String
    timestamp: AWSDateTime!
}
```

#### VTL Request Mapping Template

```
{
    "version": "2018-05-29",
    "method": "GET",
    "resourcePath": "/${stage}/${url}",
    "params": {
        "headers": {
            "Content-Type": "application/json",
            "X-Site": "$site"
        }
    }
}
```

### Anything else?

From my reading of `parser.py`, extraction of the error `Unable to find operation for request to service appsync: POST /graphql`, and the behaviour of the `http://localhost:4566/graphql` test, it seems to me as if `self._operation_router.match` may not be matching the URL `http://XXX.appsync-api.localhost.localstack.cloud:4566/graphql` to the appsync module.

Thanks for reading — I know it's been a long one :-)

**Comment by bentsku** [comment]
Hi @sc0ttdav3y and thanks for your report!

Could you try starting LocalStack with `GRAPHQL_ENDPOINT_STRATEGY=domain` and see if that resolves your issue? 
It seems the URL returned by Serverless matched this kind of endpoint, however the default configuration for the strategy is still `legacy`, see here: https://docs.localstack.cloud/user-guide/aws/appsync/#graphql-endpoints

Sorry for the inconvenience and the lost time, I hope this solves your issue.

**Comment by sc0ttdav3y** [comment]
Thanks, I'll try that out and report back.

**Comment by bentsku** [comment]
Hi @sc0ttdav3y, any update on this? I hope it was able to unblock you. Also, as you have a Pro license, feel free to join our [Slack Community](https://localstack.cloud/contact/) and drop a message to LocalStack Pro Support.

**Comment by sc0ttdav3y** [comment]
Hi @bentsku, I tried your advice and it fixed the problem I've reported in this ticket — thanks.

```
GRAPHQL_ENDPOINT_STRATEGY=domain DEBUG=1 localstack start
```

I'm now left with a bunch of other problems, but they don't relate to this ticket so I'll close it. Thanks for your help on this one.
