### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by jeropaul** [localstack/localstack#8683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm attempting to upload files directly to s3 localstack using using a presigned URL created by Rails ActiveStorage.

I currently get the following response: 

```
<?xml version='1.0' encoding='utf-8'?>
<Error><Code>InternalError</Code><Message>exception while calling s3 with unknown operation: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 769, in _parse_xml_string_to_dom
    parser.feed(xml_string)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 64, in __call__
    return self.parse_and_enrich(context)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 77, in parse_and_enrich
    operation, instance = parser.parse(context.request)
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 1061, in parse
    return super().parse(request)
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 567, in parse
    self._parse_payload(request, shape, shape.members, uri_params, final_parsed)
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 603, in _parse_payload
    original_parsed = self._initial_body_parse(request)
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 666, in _initial_body_parse
    return self._parse_xml_string_to_dom(body)
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 772, in _parse_xml_string_to_dom
    raise ProtocolParserError(
localstack.aws.protocol.parser.ProtocolParserError: Unable to parse request (syntax error: line 1, column 0), invalid XML received:
b'Hello S3 (Localstack) this is a test file \n'
</Message><RequestId>8bdc69cd-d5a9-48e2-9068-53562c259922</RequestId></Error>
```

Here are the request headers:

![image](https://github.com/localstack/localstack/assets/520985/0bcfe214-1ee0-4a99-8913-c1747bf90b55)

### Expected Behavior

I would expect the file to be uploaded to the bucket without failure!

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   `docker compose up dev`

localstack is listed as a dependency of the __dev__ service

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

No commands, upload is triggered by interacting with a browser.  

A request is made the to Rails ActiveStorage provided application URL

`rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                                    active_storage/direct_uploads#create`

This then returns a signed URL to browser where the file is directly uploaded to S3

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: 2.1.1.dev
```

### Anything else?

This could be related to or a regression of #6588 

Logs from the local stack pod 

```
2023-07-12T05:14:15.451 DEBUG --- [   asgi_gw_0] l.aws.serving.wsgi         : PUT assessment-engine-dev.host.docker.internal:4566/1ooatb36yo7f2pyojf6eyz5zv3of?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=test%2F20230712%2Fap-southeast-4%2Fs3%2Faws4_request&X-Amz-Date=20230712T051415Z&X-Amz-Expires=300&X-Amz-SignedHeaders=content-length%3Bcontent-md5%3Bcontent-type%3Bhost&X-Amz-Signature=861da9f5d8794e0d64a64cec15bd737c0b7f126e7a9a26cf89618dd60678b95e
2023-07-12T05:14:15.452 DEBUG --- [   asgi_gw_0] localstack.aws.accounts    : No Account ID in thread-local storage for thread 140429090612992
2023-07-12T05:14:15.453 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 769, in _parse_xml_string_to_dom
    parser.feed(xml_string)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 64, in __call__
    return self.parse_and_enrich(context)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 77, in parse_and_enrich
    operation, instance = parser.parse(context.request)
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 1061, in parse
    return super().parse(request)
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 567, in parse
    self._parse_payload(request, shape, shape.members, uri_params, final_parsed)
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 603, in _parse_payload
    original_parsed = self._initial_body_parse(request)
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 666, in _initial_body_parse
    return self._parse_xml_string_to_dom(body)
  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 772, in _parse_xml_string_to_dom
    raise ProtocolParserError(
localstack.aws.protocol.parser.ProtocolParserError: Unable to parse request (syntax error: line 1, column 0), invalid XML received:
b'Hello S3 (Localstack) this is a test file \n'
2023-07-12T05:14:15.455 DEBUG --- [   asgi_gw_0] l.aws.protocol.serializer  : No accept header given. Using request's Content-Type (text/plain) as preferred response Content-Type.
2023-07-12T05:14:15.455  INFO --- [   asgi_gw_0] localstack.request.http    : PUT /1ooatb36yo7f2pyojf6eyz5zv3of => 500; Request(b'Hello S3 (Localstack) this is a test file \n', headers={'Host': 'assessment-engine-dev.host.docker.internal:4566', 'Connection': 'keep-alive', 'Content-Length': '43', 'Content-Disposition': 'inline; filename="test.txt"; filename*=UTF-8\'\'test.txt', 'Content-MD5': 'ku2sfm5jZB+yDN6a7bQcWw==', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36', 'Content-Type': 'text/plain', 'Accept': '*/*', 'Referer': 'http://localhost:3000/', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8', 'x-localstack-tgt-api': 's3', 'Authorization': 'AWS4-HMAC-SHA256 Credential=injectedaccesskey/20160623/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=1234', 'x-moto-account-id': '000000000000'}); Response(b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<Error><Code>InternalError</Code><Message>exception while calling s3 with unknown operation: Traceback (most recent call last):\n  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 769, in _parse_xml_string_to_dom\n    parser.feed(xml_string)\nxml.etree.ElementTree.ParseError: syntax error: line 1, column 0\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle\n    handler(self, self.context, response)\n  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 64, in __call__\n    return self.parse_and_enrich(context)\n  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 77, in parse_and_enrich\n    operation, instance = parser.parse(context.request)\n  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 172, in wrapper\n    return func(*args, **kwargs)\n  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 1061, in parse\n    return super().parse(request)\n  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 172, in wrapper\n    return func(*args, **kwargs)\n  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 567, in parse\n    self._parse_payload(request, shape, shape.members, uri_params, final_parsed)\n  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 603, in _parse_payload\n    original_parsed = self._initial_body_parse(request)\n  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 666, in _initial_body_parse\n    return self._parse_xml_string_to_dom(body)\n  File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 772, in _parse_xml_string_to_dom\n    raise ProtocolParserError(\nlocalstack.aws.protocol.parser.ProtocolParserError: Unable to parse request (syntax error: line 1, column 0), invalid XML received:\nb\'Hello S3 (Localstack) this is a test file \\n\'\n</Message><RequestId>d693c774-3fc5-4b0b-868b-a8e5ba76ce5a</RequestId></Error>', headers={'Content-Type': 'application/xml', 'Content-Length': '2072', 'x-amz-request-id': 'd693c774-3fc5-4b0b-868b-a8e5ba76ce5a', 'x-amz-id-2': 's9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234='})
```

**Comment by bentsku** [comment]
Hello @jeropaul and thanks for your report. This is not a regression, but a limitation from the virtual host based addressing, see the note on the S3 documentation: https://docs.localstack.cloud/user-guide/aws/s3/

> **Note**
> Just like AWS, LocalStack differentiates between [Path-Style and Virtual Hosted-Style Requests](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html) depending on your Host header for a request.

> Example:

> `<bucket-name>.s3.<region>.localhost.localstack.cloud` # host-style request
> As a special case in LocalStack, leaving out <region> also works for the `s3.localhost.localstack.cloud` domain:

> `<bucket-name>.s3.localhost.localstack.cloud` is also a host-style request.

> All other requests will be considered path-style requests. It is advised to use the `s3.localhost.localstack.cloud` endpoint URL for all requests targeting S3.

Basically, you would either need to:
- configure your client generating the pre-signed URL to use path addressing, so that the bucket would be part of the path and not the host, and continue using `host.docker.internal:4566`. This would look like: `http://host.docker.internal:4566/assessment-engine-dev/1ooatb36yo7f2pyojf6eyz5zv3of`
- have a way to configure the host header so that it includes the `s3` prefix in it, like `assessment-engine-dev.s3.host.docker.internal:4566`. (The endpoint would look like `s3.host.docker.internal:4566`, but I'm not sure it would resolve?)

Basically, the LocalStack S3 services needs to know this is a virtual host based request somehow, and right now, it takes your request as they would not be any `Key` parameter, see this: `/1ooatb36yo7f2pyojf6eyz5zv3of`.

To configure the Ruby SDK to use `path-style` access, see https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#initialize-instance_method

> **:force_path_style** (Boolean) — default: false — When set to true, the bucket name is always left in the request URI and never moved to the host as a sub-domain.

Something like:
```ruby
client = Aws:::S3::Client.new(
  region: region_name,
  credentials: credentials,
  force_path_style: true
)
```

Hope that resolves your issue, keep me posted!

**Comment by jeropaul** [comment]
Okay yes thank you that has worked!

Just in case it helps anyone else, I defined the localstack service in docker compose as:
```
  localstack:
    image: localstack/localstack
    ports:
        - "4566:4566"            # LocalStack Gateway
        - "4510-4559:4510-4559"  # external services port range
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG="1"
      - LS_LOG=warn
      - HOSTNAME=localstack
      - LOCALSTACK_HOST=localstack
    volumes:
      - ./localstack_setup:/etc/localstack/init/ready.d
```

I've updated `etc/hosts` to include `127.0.0.1       localstack`

Rails configuration for my local storage is: 

```
local:
  service: S3
  access_key_id: <%= ENV.fetch('AWS_ACCESS_KEY_ID', nil) %>
  secret_access_key: <%= ENV.fetch('AWS_SECRET_ACCESS_KEY', nil) %>
  region: ap-southeast-4
  bucket: <%= ENV.fetch('S3_FILE_UPLOAD_BUCKET', nil) %>
  force_path_style: true
  endpoint: http://localstack:4566
```
