### ISSUE TITLE
bug: AWS lambda failed to start runtime environment

### ISSUE THREAD

**Issue by calvernaz** [localstack/localstack#8738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lambda fails to start and the error seems to stem from failing docker bridge object  `localstack.utils.container_utils.container_client.NoSuchObject: bridge`

However running the command `docker network ls -f driver=bridge` yields the following:
```
NETWORK ID    NAME        DRIVER
2f259bab93aa  podman      bridge
```

### Log Error

```
2023-07-23T11:01:29.889 DEBUG --- [lambda-exenv-lambda_auth-05658adc:$LATEST_2] localstack.utils.run       : Executing command: ['docker', 'inspect', '--format', '{{json .}}', 'localstack-main-lambda-lambda-auth-05658adc-05a86a91fdc46300848c350437502cc6']
2023-07-23T11:01:29.947 DEBUG --- [lambda-exenv-lambda_auth-05658adc:$LATEST_2] localstack.utils.run       : Executing command: ['docker', 'inspect', '--format', '{{json .}}', 'bridge']
2023-07-23T11:01:29.993 WARNING --- [lambda-exenv-lambda_auth-05658adc:$LATEST_2] localstack.services.awslambda.invocation.runtime_environment : Failed to start runtime environment for ID=05a86a91fdc46300848c350437502cc6 with: 
Traceback (most recent call last):
  File "/home/calvernaz/code/localstack-ext/.venv/lib/python3.10/site-packages/localstack/utils/container_utils/docker_cmd_client.py", line 417, in _inspect_object
    cmd_result = run(cmd)
  File "/home/calvernaz/code/localstack-ext/.venv/lib/python3.10/site-packages/localstack/utils/run.py", line 119, in run
    raise e
  File "/home/calvernaz/code/localstack-ext/.venv/lib/python3.10/site-packages/localstack/utils/run.py", line 69, in run
    output = subprocess.check_output(cmd, shell=shell, stderr=stderr, env=env_dict, cwd=cwd)
  File "/home/calvernaz/.pyenv/versions/3.10.9/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/calvernaz/.pyenv/versions/3.10.9/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'inspect', '--format', '{{json .}}', 'bridge']' returned non-zero exit status 125.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/calvernaz/code/localstack-ext/.venv/lib/python3.10/site-packages/localstack/utils/container_utils/docker_cmd_client.py", line 494, in inspect_network
    return self._inspect_object(network_name)
  File "/home/calvernaz/code/localstack-ext/.venv/lib/python3.10/site-packages/localstack/utils/container_utils/docker_cmd_client.py", line 421, in _inspect_object
    raise NoSuchObject(object_name_or_id, stdout=e.stdout, stderr=e.stderr)
localstack.utils.container_utils.container_client.NoSuchObject: bridge

During handling of the above exception, another exception occurred:
```

### Expected Behavior

It should be able to find the network object and be able to run the lambda.

### How are you starting LocalStack?

Host mode.

### Steps To Reproduce

Using the sample

  https://github.com/localstack/localstack-terraform-samples/tree/master/apigateway-rest-lambda-api-key

and the following command:

`tflocal init; tflocal plan; tflocal apply --auto-approve`

### Environment

```markdown
- OS: Linux Fedora release 37 (Thirty Seven)
- LocalStack: LocalStack version: 2.2.1.dev

Using Localstack on host mode
```

### Anything else?
```
$ podman --version
podman version 4.5.0
```

```
podman network inspect podman                        Wed 26 Jul 2023 10:36:25 PM +00
[
     {
          "name": "podman",
          "id": "2f259bab93aaaaa2542ba43ef33eb990d0999ee1b9924b557b7be53c0b7a1bb9",
          "driver": "bridge",
          "network_interface": "podman0",
          "created": "2023-07-25T13:58:16.505198864Z",
          "subnets": [
               {
                    "subnet": "10.88.0.0/16",
                    "gateway": "10.88.0.1"
               }
          ],
          "ipv6_enabled": false,
          "internal": false,
          "dns_enabled": false,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]

```

**Comment by dfangl** [comment]
I can see you are running podman. Can you try setting `MAIN_DOCKER_NETWORK=podman` when starting LocalStack and check if that fixes your issue?
