### ISSUE TITLE
[PRO] Failed to load config from LAMBDA_RUNTIME_IMAGE_MAPPING

### ISSUE THREAD

**Issue by atkinsonbg** [localstack/localstack#8745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We're behind a corporate proxy and can not hit DockerHub, but we run our own mirror from which I can pull Docker images. We're using the 2.2.0 LocalStack image and setting the LAMBDA_RUNTIME_IMAGE_MAPPING to the container to run the Lambda. However, LocalStack logs state "Failed to load config from LAMBDA_RUNTIME_IMAGE_MAPPING" and the container is not pulled.

### Expected Behavior

We expect the LAMBDA_RUNTIME_IMAGE_MAPPING property to pull the container we have listed.

### How are you starting LocalStack?

With a docker-compose file

### Compose file:
localstack:
    image: PRIVATE-HUB/localstack/localstack-pro:2.2.0
    networks:
      - bootstrap
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - LAMBDA_RUNTIME_IMAGE_MAPPING=PRIVATE_HUB/lambda/python:3.9
      - SNAPSHOT_SAVE_STRATEGY=MANUAL
      - MULTI_ACCOUNTS=1
      - PERSISTENCE=1
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - OUTBOUND_HTTP_PROXY=${HTTP_PROXY}
      - OUTBOUND_HTTPS_PROXY=${HTTPS_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

### Logs
`
07/25/2023 3:35:51 PM
2023-07-25T19:35:51.009  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS lambda.CreateFunction => 201
07/25/2023 3:35:51 PM
2023-07-25T19:35:51.045 DEBUG --- [Executor-2_0] l.s.a.i.docker_runtime_exe : Executing prepare docker executor pro-hook for function arn:aws:lambda:us-east-1:000000000000:function:service:$LATEST
07/25/2023 3:35:51 PM
2023-07-25T19:35:51.046 ERROR --- [Executor-2_0] l.s.a.i.docker_runtime_exe : Failed to load config from LAMBDA_RUNTIME_IMAGE_MAPPING=PRIVATE_HUB/lambda/python:3.9
07/25/2023 3:35:51 PM
2023-07-25T19:35:51.047 DEBUG --- [Executor-2_0] l.s.a.i.version_manager    : Changing Lambda 'arn:aws:lambda:us-east-1:000000000000:function:service:$LATEST' to failed. Reason: Expecting value: line 1 column 1 (char 0)
07/25/2023 3:35:51 PM
Traceback (most recent call last):
07/25/2023 3:35:51 PM
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/awslambda/invocation/version_manager.py", line 205, in start
07/25/2023 3:35:51 PM
    get_runtime_executor().prepare_version(self.function_version)
07/25/2023 3:35:51 PM
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/awslambda/invocation/docker_runtime_executor.py", line 393, in prepare_version
07/25/2023 3:35:51 PM
    image_name = resolver.get_image_for_runtime(function_version.config.runtime)
07/25/2023 3:35:51 PM
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/awslambda/invocation/docker_runtime_executor.py", line 157, in get_image_for_runtime
07/25/2023 3:35:51 PM
    resolved_image = self._resolve(runtime, config.LAMBDA_RUNTIME_IMAGE_MAPPING)
07/25/2023 3:35:51 PM
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/awslambda/invocation/docker_runtime_executor.py", line 134, in _resolve
07/25/2023 3:35:51 PM
    mapping: dict = json.loads(custom_image_mapping)
07/25/2023 3:35:51 PM
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
07/25/2023 3:35:51 PM
    return _default_decoder.decode(s)
07/25/2023 3:35:51 PM
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
07/25/2023 3:35:51 PM
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
07/25/2023 3:35:51 PM
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
07/25/2023 3:35:51 PM
    raise JSONDecodeError("Expecting value", s, err.value) from None
07/25/2023 3:35:51 PM
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
07/25/2023 3:35:51 PM
2023-07-25T19:35:51.064 DEBUG --- [Executor-2_1] l.s.a.i.version_manager    : Stopping lambda version 'arn:aws:lambda:us-east-1:000000000000:function:service:$LATEST'
07/25/2023 3:35:51 PM
2023-07-25T19:35:51.065 DEBUG --- [functhread30] l.s.a.i.version_manager    : Invocation loop for lambda arn:aws:lambda:us-east-1:000000000000:function:service:$LATEST stopped while waiting for invocations
`

### Environment

```markdown
- OS: macOS / Intel based
- LocalStack: Pro 2.2.0
```

**Comment by whummer** [comment]
Hey @atkinsonbg , thanks for creating the ticket. Already responded in Slack, but also adding my response here for better visibility: 

Please note that there are two ways to configure the `LAMBDA_RUNTIME_IMAGE_MAPPING` - either as an image name template that contains a `<runtime>` placeholder, or as a JSON mapping that maps runtime name to image name.

See also our docs for more details: https://docs.localstack.cloud/references/configuration/#lambda

We can see that your image name is `PRIVATE_HUB/lambda/python:3.9` - could you also push the image under the name `PRIVATE_HUB/lambda:python3.9` , by any chance? In that case you could define the mapping config as `PRIVATE_HUB/lambda:<runtime>`

Hope that helps - please keep us posted on how it goes.. Thanks

**Comment by atkinsonbg** [comment]
Hey @whummer thanks for the reply. Unfortunately that also does not work: 

`2023-07-26T12:08:32.405 ERROR --- [Executor-2_0] l.s.a.i.docker_runtime_exe : Failed to load config from LAMBDA_RUNTIME_IMAGE_MAPPING=......`

From the outside it definitely looks like it just can't reach our private DockerHub from inside the LocalStack container, but I'm speculating of course. I've verified that my proxy env vars are set to the correct values inside the LS container.

**Comment by atkinsonbg** [comment]
OK, made some progress:

`
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - 'LAMBDA_RUNTIME_IMAGE_MAPPING={"python3.9": "PRIVATE_HUB/lambda/python:3.9"}'
      `
This was able to pull the image and Lambda creation was successful. However, now when I go to invoke the Lambda I get the folllowing error:

`
07/26/2023 10:01:05 AM
2023-07-26T14:01:05.627 DEBUG --- [ce:$LATEST_0] localstack.packages.api    : Starting installation of awslambda-runtime...
07/26/2023 10:01:05 AM
2023-07-26T14:01:05.704  WARN --- [ce:$LATEST_0] l.s.a.i.runtime_environmen : Failed to start runtime environment for ID=a9d5eabc81e5e5798451b86a74f55283 with: Installation of awslambda-runtime failed.
......
07/26/2023 10:01:05 AM
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)
......
07/26/2023 10:01:05 AM
urllib3.exceptions.MaxRetryError: MyHTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /localstack/lambda-runtime-init/releases/download/v0.1.19-pre/aws-lambda-rie-x86_64 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)')))
`

**Comment by atkinsonbg** [comment]
Workaround for the above issue, not the official answer:

`
      - CURL_CA_BUNDLE=
      - REQUESTS_CA_BUNDLE=
`

This will basically turn off SSL validation which is not what you want, but this is getting me past the error until I can get my company cert injected and consumed correctly.

**Comment by atkinsonbg** [comment]
We solved our issue, by pulling all our corporate certs down and using the init hooks: https://docs.localstack.cloud/references/custom-tls-certificates/#custom-ssl-certificates-with-init-hooks

We then set the CURL_CA_BUNDLE and REQUESTS_CA_BUNDLE env vars to point to that corporate cert now in the container.
