### ISSUE TITLE
bug: Initialization hooks FileNotFoundError

### ISSUE THREAD

**Issue by BennoDev** [localstack/localstack#8797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

None of the scripts in the initialization hooks are running. Initially I had a permission denied error, which was solved by updating the permissions as documented, however currently I'm getting the following error every time:

`FileNotFoundError: [Errno 2] No such file or directory: '/etc/localstack/init/ready.d/01_setup-sqs.sh'`.

I've verified the presence of the file in the container both via the Docker GUI as via terminal, so the volume is properly mapped. I also made sure that the line endings are correct as per [this comment in another issue](https://github.com/localstack/localstack/issues/7289#issuecomment-1367181135). I've also tried renaming the files and adding new ones, they all have the same issue.

We can manually create the SQS queues currently but this is not very scalable or portable. Our team has an older setup using localstack 0.1.14 where it worked with the `docker-entrypoint-initaws.d` 

Our new setup:

```
# docker-compose.yml
version: '3.8'
service:  
  localstack:
    image: localstack/localstack:2.2.0
    container_name: localstack_main_${COMPOSE_PROJECT_NAME} # provided by .env, can be anything for purpose of reproducing
    ports:
      - 4566:4566
    network_mode: bridge
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./volumes/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/localstack:/etc/localstack/init/ready.d
```

### Expected Behavior

It should find and execute the file properly.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

For full completeness, our docker compose yml file is in a docker sub folder, and we launch it from the root using a yarn script that runs the following: `docker compose -f ./docker/docker-compose.yml up -d`

### Environment

```markdown
- OS: MacOS & Windows (for my colleague, who has the same issue)
- LocalStack: 2.2.0
```

**Comment by alexrashed** [comment]
Hi @BennoDev!
Sorry for the late answer. I just tried to reproduce your issue, where I performed the following tasks:
- Create a new `docker-compose.yml`
- Add your example compose file.
- Fix the `service` tag by renaming it to `services`.
- Execute the following commands:
  ```bash
  mkdir -p scripts/localstack
  cat <<EOF > scripts/localstack/echo.sh
  #!/bin/bash
  echo "Test"
  EOF
  chmod +x scripts/localstack/echo.sh
  docker-compose up
  ```

The script is then executed just fine:
```
...
localstack_main  | 2023-09-13T08:46:23.419 DEBUG --- [  MainThread] localstack.runtime.init    : Running READY script /etc/localstack/init/ready.d/echo.sh
localstack_main  | Test
...
```

Could you maybe give us some more info on your scripts?
What are the permissions of your scripts?
Could you give us, for example. the output of `ls -al ./scripts/localstack`?
And could you please add some more logs than just the one line?

Thanks!

**Comment by ubiuser** [comment]
All of a sudden this started to be an issue for me too. It was working before, so not sure what's changed.

Running with docker compose: `docker compose up localstack`

Relevant part in docker compose config:
```
  localstack:
    image: "localstack/localstack"
    ports:
      - "4566:4566"
    env_file:
      - ./aws/local.env
    environment:
      DEBUG: 1
      DEFAULT_REGION: eu-west-2
      SERVICES: sns,sqs
      LOCALSTACK_HOST: localstack
    volumes:
      - './aws:/etc/localstack/init/ready.d'
```

This is my log:
```
acc-hmrc-localstack-1  | LocalStack supervisor: starting
acc-hmrc-localstack-1  | LocalStack supervisor: localstack process (PID 15) starting
acc-hmrc-localstack-1  | 
acc-hmrc-localstack-1  | LocalStack version: 2.0.3.dev
acc-hmrc-localstack-1  |
acc-hmrc-localstack-1  | LocalStack build date: 2023-05-16
acc-hmrc-localstack-1  | LocalStack build git hash: b9992fd0
acc-hmrc-localstack-1  |
acc-hmrc-localstack-1  |
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.231 DEBUG --- [  MainThread] stevedore._cache           : reading /root/.cache/python-entrypoints/5fe4f86d8bf7b3e1ce483c1ce36cfad44db40835d6793171669790e74c57b456
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.240 DEBUG --- [  MainThread] stevedore._cache           : writing to /root/.cache/python-entrypoints/5fe4f86d8bf7b3e1ce483c1ce36cfad44db40835d6793171669790e74c57b456
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.242 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='_patch_botocore_json_parser', value='localstack.aws.client:_patch_botocore_json_parser', group='localstack.hooks.on_infra_start')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.243 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='_publish_config_as_analytics_event', value='localstack.runtime.analytics:_publish_config_as_analytics_event', group='localstack.hooks.on_infra_start')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.244 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='_publish_container_info', value='localstack.runtime.analytics:_publish_container_info', group='localstack.hooks.on_infra_start')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.244 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='_run_init_scripts_on_start', value='localstack.runtime.init:_run_init_scripts_on_start', group='localstack.hooks.on_infra_start')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.246 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='deprecation_warnings', value='localstack.plugins:deprecation_warnings', group='localstack.hooks.on_infra_start')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.246 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_partition_adjusting_proxy_listener', value='localstack.plugins:register_partition_adjusting_proxy_listener', group='localstack.hooks.on_infra_start')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.246 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='validate_configuration', value='localstack.services.awslambda.plugins:validate_configuration', group='localstack.hooks.on_infra_start')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.250 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_pickle_patches_runtime', value='localstack_persistence.pickling.__plugins__:register_pickle_patches_runtime', group='localstack.hooks.on_infra_start')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.251 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_public_cloudpods_endpoints', value='localstack_persistence.pods.__plugins__:register_public_cloudpods_endpoints', group='localstack.hooks.on_infra_start')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.251 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_reset_state_resource', value='localstack_persistence.reset.__plugins__:register_reset_state_resource', group='localstack.hooks.on_infra_start')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.252 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_state_load_strategy', value='localstack_persistence.snapshot.__plugins__:register_state_load_strategy', group='localstack.hooks.on_infra_start')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.379  WARN --- [  MainThread] l.services.internal        : Enabling diagnose endpoint, please be aware that this can expose sensitive information via your network.
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.382 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_state_resource', value='localstack_persistence.snapshot.__plugins__:register_state_resource', group='localstack.hooks.on_infra_start')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.382 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_state_save_strategy', value='localstack_persistence.snapshot.__plugins__:register_state_save_strategy', group='localstack.hooks.on_infra_start')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.382 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._patch_botocore_json_parser = <function _patch_botocore_json_parser at 0x7fbd44f84f70>)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.383 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:_patch_botocore_json_parser
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.383 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._publish_config_as_analytics_event = <function _publish_config_as_analytics_event at 0x7fbd44f852d0>)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.383 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:_publish_config_as_analytics_event
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.383 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._publish_container_info = <function _publish_container_info at 0x7fbd44f855a0>)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.383 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:_publish_container_info
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.383 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._run_init_scripts_on_start = <function _run_init_scripts_on_start at 0x7fbd44f86200>)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.383 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:_run_init_scripts_on_start
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.384 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.deprecation_warnings = <function deprecation_warnings at 0x7fbd44f869e0>)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.384 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:deprecation_warnings
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.384 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_partition_adjusting_proxy_listener = <function register_partition_adjusting_proxy_listener at 0x7fbd44f868c0>)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.384 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:register_partition_adjusting_proxy_listener is disabled
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.384 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.validate_configuration = <function validate_configuration at 0x7fbd44fb4c10>)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.384 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:validate_configuration
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.384 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_pickle_patches_runtime = <function register_pickle_patches_runtime at 0x7fbd44fb4e50>)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.384 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:register_pickle_patches_runtime
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.385 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_public_cloudpods_endpoints = <function register_public_cloudpods_endpoints at 0x7fbd44fb51b0>)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.385 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:register_public_cloudpods_endpoints
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.385 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_reset_state_resource = <function register_reset_state_resource at 0x7fbd44fb5360>)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.385 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:register_reset_state_resource is disabled
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.385 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_state_load_strategy = <function register_state_load_strategy at 0x7fbd44c98820>)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.385 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:register_state_load_strategy is disabled
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.385 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_state_resource = <function register_state_resource at 0x7fbd44c98700>)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.385 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:register_state_resource is disabled
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.385 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_state_save_strategy = <function register_state_save_strategy at 0x7fbd44c98a60>)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.385 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:register_state_save_strategy is disabled
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.396 DEBUG --- [  MainThread] localstack.runtime.init    : No runner available for script /etc/localstack/init/ready.d/local.env
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.396 DEBUG --- [  MainThread] localstack.runtime.init    : Init scripts discovered: {BOOT: [], START: [], READY: [Script(path='/etc/localstack/init/ready.d/init.sh', stage=READY, state=UNKNOWN)], SHUTDOWN: []}
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.396 DEBUG --- [  MainThread] localstack.plugins         : Checking for the usage of deprecated community features and configs...
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.396  WARN --- [  MainThread] localstack.deprecations    : DEFAULT_REGION is deprecated (since 0.12.7) and will be removed in upcoming releases of LocalStack! LocalStack now has full multi-region support. Please remove this environment variable.
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.538 DEBUG --- [  MainThread] localstack.utils.threads   : start_thread called without providing a custom name
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.544 DEBUG --- [-functhread2] localstack.utils.ssl       : Using cached SSL certificate (less than 6hrs since last update).
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.547  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.547  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.841 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='acm:default', value='localstack.services.providers:acm', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.847 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='apigateway:default', value='localstack.services.providers:apigateway', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.848 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='cloudformation:default', value='localstack.services.providers:cloudformation', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.848 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='cloudwatch:default', value='localstack.services.providers:cloudwatch', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.849 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='config:default', value='localstack.services.providers:awsconfig', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.849 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='dynamodb:default', value='localstack.services.providers:dynamodb', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.849 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='dynamodbstreams:default', value='localstack.services.providers:dynamodbstreams', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.849 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='ec2:default', value='localstack.services.providers:ec2', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.849 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='es:default', value='localstack.services.providers:es', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.849 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='events:default', value='localstack.services.providers:events', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.850 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='firehose:default', value='localstack.services.providers:firehose', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.850 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='iam:default', value='localstack.services.providers:iam', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.850 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='kinesis:default', value='localstack.services.providers:kinesis', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.850 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='kms:default', value='localstack.services.providers:kms', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.850 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='lambda:asf', value='localstack.services.providers:awslambda_asf', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.850 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='lambda:default', value='localstack.services.providers:awslambda', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.850 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='lambda:legacy', value='localstack.services.providers:awslambda_legacy', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.851 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='lambda:v1', value='localstack.services.providers:awslambda_v1', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.851 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='lambda:v2', value='localstack.services.providers:awslambda_v2', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.851 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='logs:default', value='localstack.services.providers:logs', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.851 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='opensearch:default', value='localstack.services.providers:opensearch', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.851 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='redshift:default', value='localstack.services.providers:redshift', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.851 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='resource-groups:default', value='localstack.services.providers:resource_groups', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.851 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='resourcegroupstaggingapi:default', value='localstack.services.providers:resourcegroupstaggingapi', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.852 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='route53:default', value='localstack.services.providers:route53', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.852 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='route53resolver:default', value='localstack.services.providers:route53resolver', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.852 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='s3:asf', value='localstack.services.providers:s3_asf', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.852 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='s3:default', value='localstack.services.providers:s3', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.852 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='s3:legacy', value='localstack.services.providers:s3_legacy', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.852 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='s3:v1', value='localstack.services.providers:s3_v1', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.852 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='s3:v2', value='localstack.services.providers:s3_v2', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.853 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='s3control:default', value='localstack.services.providers:s3control', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.853 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='secretsmanager:default', value='localstack.services.providers:secretsmanager', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.853 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='ses:default', value='localstack.services.providers:ses', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.853 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='sns:default', value='localstack.services.providers:sns', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.853 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='sqs:default', value='localstack.services.providers:sqs', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.853 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='ssm:default', value='localstack.services.providers:ssm', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.853 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='stepfunctions:default', value='localstack.services.providers:stepfunctions', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.854 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='stepfunctions:v1', value='localstack.services.providers:stepfunctions_v1', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.854 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='stepfunctions:v2', value='localstack.services.providers:stepfunctions_v2', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.854 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='sts:default', value='localstack.services.providers:sts', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.854 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='support:default', value='localstack.services.providers:support', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.854 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='swf:default', value='localstack.services.providers:swf', group='localstack.aws.provider')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.854 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='transcribe:default', value='localstack.services.providers:transcribe', group='localstack.aws.provider')
acc-hmrc-localstack-1  | Ready.
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.855 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='_run_init_scripts_on_ready', value='localstack.runtime.init:_run_init_scripts_on_ready', group='localstack.hooks.on_infra_ready')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.855 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_virtual_host_routes', value='localstack.services.s3.virtual_host:register_virtual_host_routes', group='localstack.hooks.on_infra_ready')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.881 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='do_run_state_load_all', value='localstack_persistence.snapshot.__plugins__:do_run_state_load_all', group='localstack.hooks.on_infra_ready')
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.881 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_ready._run_init_scripts_on_ready = <function _run_init_scripts_on_ready at 0x7fbd44f86320>)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.882 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_ready:_run_init_scripts_on_ready
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.882 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_ready.register_virtual_host_routes = <function register_virtual_host_routes at 0x7fbd43041750>)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.882 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_ready:register_virtual_host_routes
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.882 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_ready.do_run_state_load_all = <function do_run_state_load_all at 0x7fbd44c98940>)
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.882 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_ready:do_run_state_load_all is disabled
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.882 DEBUG --- [  MainThread] localstack.runtime.init    : Running READY script /etc/localstack/init/ready.d/init.sh
acc-hmrc-localstack-1  | 2023-09-29T08:57:23.886 ERROR --- [  MainThread] localstack.runtime.init    : Error while running script Script(path='/etc/localstack/init/ready.d/init.sh', stage=READY, state=ERROR)
acc-hmrc-localstack-1  | Traceback (most recent call last):
acc-hmrc-localstack-1  |   File "/opt/code/localstack/localstack/runtime/init.py", line 136, in run_stage
acc-hmrc-localstack-1  |     runner.run(script.path)
acc-hmrc-localstack-1  |   File "/opt/code/localstack/localstack/runtime/init.py", line 69, in run
acc-hmrc-localstack-1  |     exit_code = subprocess.call(args=[], executable=path)
acc-hmrc-localstack-1  |   File "/usr/local/lib/python3.10/subprocess.py", line 345, in call
acc-hmrc-localstack-1  |     with Popen(*popenargs, **kwargs) as p:
acc-hmrc-localstack-1  |   File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
acc-hmrc-localstack-1  |     self._execute_child(args, executable, preexec_fn, close_fds,
acc-hmrc-localstack-1  |   File "/usr/local/lib/python3.10/subprocess.py", line 1863, in _execute_child
acc-hmrc-localstack-1  |     raise child_exception_type(errno_num, err_msg, err_filename)
acc-hmrc-localstack-1  | FileNotFoundError: [Errno 2] No such file or directory: '/etc/localstack/init/ready.d/init.sh'
acc-hmrc-localstack-1  | 2023-09-29T08:57:32.819 DEBUG --- [   asgi_gw_0] l.a.p.service_router       : loading service catalog index cache file /var/lib/localstack/cache/service-catalog-2_0_3_dev-1_29_121.pickle
```

It has `Init scripts discovered: {BOOT: [], START: [], READY: [Script(path='/etc/localstack/init/ready.d/init.sh', stage=READY, state=UNKNOWN)], SHUTDOWN: []}`, but then `Error while running script Script(path='/etc/localstack/init/ready.d/init.sh', stage=READY, state=ERROR)`.

When I log into the pod's terminal I can list the file:
```
# ls -l /etc/localstack/init/ready.d
total 0
-rwxrwxrwx 1 root root 720 Sep 29 07:48 init.sh
-rwxrwxrwx 1 root root 111 Sep 28 12:14 local.env
```

**Comment by ubiuser** [comment]
I re-pulled the init.sh from my repo, made a small change to it and it's all working again. Not sure what just happened, but it would be great to understand why it failed before.

**Comment by alexrashed** [comment]
To be honest, that's hard to tell, but looks like a permission issue.
For now, I will close this issue. If you experience this issue again, please open a new ticket describing your exact environment and the exact file permissions on the init script on your host system. Thanks!

**Comment by BennoDev** [comment]
Apologies @alexrashed, I lost track of this issue myself. We are still facing this for another new codebase but are indeed looking at the permissions first. Thanks for your answers.

**Comment by lvond** [comment]
@BennoDev I just encountered the same issue as my shell script used windows style line endings. Make sure to use LF unix line ends. Hope it helps.

**Comment by vadzim-z** [comment]
@alexrashed It doesn't work for me also. Just yesterday everything was fine. No changes were made in the file itself. Today I'm getting the same error message:
```
FileNotFoundError: [Errno 2] No such file or directory: '/etc/localstack/init/ready.d/init-s3.sh'
```
LF unix line endings didn't work either

Permissions to file:

<img width="1162" height="766" alt="Image" src="https://github.com/user-attachments/assets/228cf17c-4ae7-439d-b886-67b605b1fe50" />

**Comment by alexrashed** [comment]
> LF unix line endings didn't work either

Are you sure this isn't the case? This is often re-written by editors transparently, and the result would be the same issue.

As mentioned above, this issue has been closed (and therefore has limited visibility).
If this doesn't solve your issue, please create a new GitHub issue and thoroughly describe how you start and configure LocalStack, together with more detailed log output. Feel free to directly ping me in a new issue, and you can also link this issue for reference / context.

Thanks!
