### ISSUE TITLE
bug: CDK Table build with replicationRegions failing on latest

### ISSUE THREAD

**Issue by listenrightmeow** [localstack/localstack#8833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to deploy a [CDK Table](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_dynamodb.Table.html) to a localstack environment results in the following:

```
stack | 0/3 | 8:56:58 PM | CREATE_FAILED        | AWS::CloudFormation::Stack | stack Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "CREATE_FAILED" at least once
```

```
localstack  | 2023-08-06T03:56:28.709 DEBUG --- [   asgi_gw_4] localstack.packages.api    : Installation of dynamodb-local skipped (already installed).
localstack  | 2023-08-06T03:56:28.709 DEBUG --- [   asgi_gw_4] l.services.dynamodb.server : Starting DynamoDB Local: ['java', '-Xmx256m', '-javaagent:/usr/lib/localstack/dynamodb-local/latest/ddb-local-loader-0.1.jar', '-Djava.library.path=/usr/lib/localstack/dynamodb-local/latest/DynamoDBLocal_lib', '-jar', '/usr/lib/localstack/dynamodb-local/latest/DynamoDBLocal.jar', '-port', '35799', '-dbPath', '/var/lib/localstack/tmp/state/dynamodb']
localstack  | 2023-08-06T03:56:28.710 DEBUG --- [uncthread160] localstack.utils.run       : Executing command: ['java', '-Xmx256m', '-javaagent:/usr/lib/localstack/dynamodb-local/latest/ddb-local-loader-0.1.jar', '-Djava.library.path=/usr/lib/localstack/dynamodb-local/latest/DynamoDBLocal_lib', '-jar', '/usr/lib/localstack/dynamodb-local/latest/DynamoDBLocal.jar', '-port', '35799', '-dbPath', '/var/lib/localstack/tmp/state/dynamodb']
localstack  | 2023-08-06T03:56:28.939 DEBUG --- [uncthread160] l.services.dynamodb.server : Initializing DynamoDB Local with the following configuration:
localstack  | 2023-08-06T03:56:28.939 DEBUG --- [uncthread160] l.services.dynamodb.server : Port:	35799
localstack  | 2023-08-06T03:56:28.939 DEBUG --- [uncthread160] l.services.dynamodb.server : InMemory:	false
localstack  | 2023-08-06T03:56:28.939 DEBUG --- [uncthread160] l.services.dynamodb.server : DbPath:	/var/lib/localstack/tmp/state/dynamodb
localstack  | 2023-08-06T03:56:28.940 DEBUG --- [uncthread160] l.services.dynamodb.server : SharedDb:	false
localstack  | 2023-08-06T03:56:28.940 DEBUG --- [uncthread160] l.services.dynamodb.server : shouldDelayTransientStatuses:	false
localstack  | 2023-08-06T03:56:28.940 DEBUG --- [uncthread160] l.services.dynamodb.server : CorsParams:	null
localstack  | 2023-08-06T03:56:28.950 DEBUG --- [uncthread160] l.services.dynamodb.server :
localstack  | 2023-08-06T03:56:29.715  INFO --- [   asgi_gw_4] botocore.credentials       : Found credentials in environment variables.
localstack  | 2023-08-06T03:56:30.532 DEBUG --- [   asgi_gw_4] l.services.plugins         : checking service health dynamodb:4566
localstack  | 2023-08-06T03:56:30.534  INFO --- [   asgi_gw_4] localstack.utils.bootstrap : Execution of "require" took 1887.18ms
localstack  | 2023-08-06T03:56:30.879 DEBUG --- [   asgi_gw_1] l.services.plugins         : checking service health kinesis:4566
localstack  | 2023-08-06T03:56:30.886  INFO --- [   asgi_gw_1] l.s.k.kinesis_mock_server  : Creating kinesis backend for account 000000000000
localstack  | 2023-08-06T03:56:30.887 DEBUG --- [   asgi_gw_1] localstack.packages.api    : Starting installation of kinesis-local...
localstack  | 2023-08-06T03:56:30.887 DEBUG --- [   asgi_gw_1] localstack.utils.run       : Executing command: ['npm', 'install', '--prefix', '/var/lib/localstack/lib/kinesis-local/0.4.2', 'kinesis-local@0.4.2']
localstack  | 2023-08-06T03:56:32.575 DEBUG --- [   asgi_gw_1] localstack.packages.core   : Setting ownership root:root on /var/lib/localstack/lib/kinesis-local/0.4.2
localstack  | 2023-08-06T03:56:32.575 DEBUG --- [   asgi_gw_1] localstack.packages.api    : Installation of kinesis-local finished.
localstack  | 2023-08-06T03:56:32.576 DEBUG --- [   asgi_gw_1] l.s.k.kinesis_mock_server  : starting kinesis process ['node', PosixPath('/var/lib/localstack/lib/kinesis-local/0.4.2/node_modules/kinesis-local/main.js')] with env vars {'KINESIS_MOCK_CERT_PATH': '/var/lib/localstack/lib/kinesis-local/0.4.2/node_modules/kinesis-local/server.json', 'KINESIS_MOCK_PLAIN_PORT': 42209, 'KINESIS_MOCK_TLS_PORT': 34279, 'SHARD_LIMIT': '100', 'ON_DEMAND_STREAM_COUNT_LIMIT': '10', 'AWS_ACCOUNT_ID': '000000000000', 'CREATE_STREAM_DURATION': '500ms', 'DELETE_STREAM_DURATION': '500ms', 'REGISTER_STREAM_CONSUMER_DURATION': '500ms', 'START_STREAM_ENCRYPTION_DURATION': '500ms', 'STOP_STREAM_ENCRYPTION_DURATION': '500ms', 'DEREGISTER_STREAM_CONSUMER_DURATION': '500ms', 'MERGE_SHARDS_DURATION': '500ms', 'SPLIT_SHARD_DURATION': '500ms', 'UPDATE_SHARD_COUNT_DURATION': '500ms', 'UPDATE_STREAM_MODE_DURATION': '500ms', 'SHOULD_PERSIST_DATA': 'true', 'PERSIST_PATH': '../../../var/lib/localstack/tmp/state/kinesis', 'PERSIST_FILE_NAME': '000000000000.json', 'PERSIST_INTERVAL': '5s', 'LOG_LEVEL': 'INFO'}
localstack  | 2023-08-06T03:56:32.576 DEBUG --- [uncthread166] localstack.utils.run       : Executing command: ['node', PosixPath('/var/lib/localstack/lib/kinesis-local/0.4.2/node_modules/kinesis-local/main.js')]
localstack  | 2023-08-06T03:56:32.834  INFO --- [uncthread166] l.s.k.kinesis_mock_server  : [info] kinesis.mock.KinesisMockService$ 2023-08-06T03:56:32.823005Z contextId=6956dd23-c61e-4aa1-80ce-b8bfc8d0894b, cacheConfig={"awsAccountId":"000000000000","awsRegion":"us-east-1","createStreamDuration":{"length":500,"unit":"MILLISECONDS"},"deleteStreamDuration":{"length":500,"unit":"MILLISECONDS"},"deregisterStreamConsumerDuration":{"length":500,"unit":"MILLISECONDS"},"initializeStreams":null,"logLevel":"INFO","mergeShardsDuration":{"length":500,"unit":"MILLISECONDS"},"onDemandStreamCountLimit":10,"persistConfig":{"fileName":"000000000000.json","interval":{"length":5,"unit":"SECONDS"},"loadIfExists":true,"path":"../../../var/lib/localstack/tmp/state/kinesis","shouldPersist":true},"registerStreamConsumerDuration":{"length":500,"unit":"MILLISECONDS"},"shardLimit":100,"splitShardDuration":{"length":500,"unit":"MILLISECONDS"},"startStreamEncryptionDuration":{"length":500,"unit":"MILLISECONDS"},"stopStreamEncryptionDuration":{"length":500,"unit":"MILLISECONDS"},"updateShardCountDuration":{"length":500,"unit":"MILLISECONDS"}} Logging Cache Config
localstack  | 2023-08-06T03:56:32.986  INFO --- [uncthread166] l.s.k.kinesis_mock_server  : [info] kinesis.mock.KinesisMockService$ 2023-08-06T03:56:32.986197Z  Starting Kinesis TLS Mock Service on port 34279
localstack  | 2023-08-06T03:56:32.987  INFO --- [uncthread166] l.s.k.kinesis_mock_server  : [info] kinesis.mock.KinesisMockService$ 2023-08-06T03:56:32.986862Z  Starting Kinesis Plain Mock Service on port 42209
localstack  | 2023-08-06T03:56:32.994  INFO --- [uncthread166] l.s.k.kinesis_mock_server  : [info] kinesis.mock.KinesisMockService$ 2023-08-06T03:56:32.994001Z contextId=1d81ef53-1648-4fbc-8b16-f09375d77ece Starting persist data loop
localstack  | 2023-08-06T03:56:33.215 DEBUG --- [uncthread158] l.s.c.resource_provider    : Executing callback method for AWS::DynamoDB::Table:ddbFooTabletable735E488F
localstack  | 2023-08-06T03:56:33.330 DEBUG --- [uncthread158] l.s.c.e.template_deployer  : Error applying changes for CloudFormation stack "stack-ddbFooTableNestedStackdd-f1d922ad": 'NoneType' object has no attribute 'get' Traceback (most recent call last):
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 965, in _run
localstack  |     self.do_apply_changes_in_loop(changes, stack)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1011, in do_apply_changes_in_loop
localstack  |     should_deploy = self.prepare_should_deploy_change(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1105, in prepare_should_deploy_change
localstack  |     resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 35, in resolve_refs_recursively
localstack  |     A=resolve_refs_recursively_orig(*E,**F)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 178, in resolve_refs_recursively
localstack  |     result = _resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 478, in _resolve_refs_recursively
localstack  |     value[key] = resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 35, in resolve_refs_recursively
localstack  |     A=resolve_refs_recursively_orig(*E,**F)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 178, in resolve_refs_recursively
localstack  |     result = _resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 478, in _resolve_refs_recursively
localstack  |     value[key] = resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 35, in resolve_refs_recursively
localstack  |     A=resolve_refs_recursively_orig(*E,**F)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 178, in resolve_refs_recursively
localstack  |     result = _resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 497, in _resolve_refs_recursively
localstack  |     value[i] = resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/cloudformation/cloudformation_extended.py.enc", line 35, in resolve_refs_recursively
localstack  |     A=resolve_refs_recursively_orig(*E,**F)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 178, in resolve_refs_recursively
localstack  |     result = _resolve_refs_recursively(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/functions.py", line 80, in func
localstack  |     return wrapped(*args, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 290, in _resolve_refs_recursively
localstack  |     resolved_getatt = get_attr_from_model_instance(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 102, in get_attr_from_model_instance
localstack  |     attribute = attribute.get(part)
localstack  | AttributeError: 'NoneType' object has no attribute 'get'
localstack  |
localstack  |
localstack  | 2023-08-06T03:56:33.426  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack  | 2023-08-06T03:56:33.445  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
localstack  | 2023-08-06T03:56:38.447  INFO --- [   asgi_gw_4] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack  | 2023-08-06T03:56:38.458  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
localstack  | 2023-08-06T03:56:43.464  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack  | 2023-08-06T03:56:43.473  INFO --- [   asgi_gw_4] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
localstack  | 2023-08-06T03:56:48.479  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack  | 2023-08-06T03:56:48.489  INFO --- [   asgi_gw_4] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
localstack  | 2023-08-06T03:56:53.495  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack  | 2023-08-06T03:56:53.502  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
localstack  | 2023-08-06T03:56:58.487  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack  | 2023-08-06T03:56:58.495  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
localstack  | 2023-08-06T03:56:58.743 DEBUG --- [uncthread154] l.s.c.e.template_deployer  : Error applying changes for CloudFormation stack "stack": Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "CREATE_FAILED" at least once Traceback (most recent call last):
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 965, in _run
localstack  |     self.do_apply_changes_in_loop(changes, stack)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1039, in do_apply_changes_in_loop
localstack  |     self.apply_change(change, stack=stack)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1152, in apply_change
localstack  |     progress_event = executor.deploy_loop(resource_provider_payload)  # noqa
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/resource_provider.py", line 572, in deploy_loop
localstack  |     event = self.execute_action(resource_provider, payload)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/resource_provider.py", line 638, in execute_action
localstack  |     return resource_provider.create(request)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/resource_provider.py", line 350, in create
localstack  |     return self.create_or_delete(request)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/resource_provider.py", line 499, in create_or_delete
localstack  |     result_handler(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/cloudformation/models/cloudformation.py", line 55, in _handle_result
localstack  |     connect_to().cloudformation.get_waiter("stack_create_complete").wait(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/waiter.py", line 55, in wait
localstack  |     Waiter.wait(self, **kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/waiter.py", line 375, in wait
localstack  |     raise WaiterError(
localstack  | botocore.exceptions.WaiterError: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "CREATE_FAILED" at least once
localstack  |
localstack  |
localstack  | 2023-08-06T03:57:03.504  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack  | 2023-08-06T03:57:03.511  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
localstack  | 2023-08-06T03:57:03.520  INFO --- [   asgi_gw_4] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
```

I am using the CDK Table class with a stream enabled, which requires replicas to enable the stream. There's no creative way around this issue that I'm aware of, due to the stack failing before the fully deployment of the Table class.

### Expected Behavior

I'm expecting the build to succeed locally, so I can continue with our stack deployment chain for our local environments.

The behavior is not present on `localstack/localstack-pro:2.2.0` or any release prior to the update this week. I am successfully able to deploy to live environments with the same CDK stack without error.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose up
    
```
version: "3.8"

networks:
  ls:
    name: ls

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    environment:
      - DEBUG=${DEBUG-1}
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_APIGATEWAY=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - MAIN_DOCKER_NETWORK=ls
      - PERSISTENCE=${PERSISTENCE-}
    env_file:
      - ./localstack.local.env
    image: "localstack/localstack-pro:${LOCALSTACK_VERSION-latest}"
    networks:
      - ls
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
      - "127.0.0.1:53:53" # DNS config (required for Pro)
      - "127.0.0.1:53:53/udp" # DNS config (required for Pro)
      - "127.0.0.1:443:443" # LocalStack HTTPS Gateway (required for Pro)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

```

.env file contains:

```
LOCALSTACK_API_KEY=xxxxxxxxxx
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

npx cdklocal deploy api

```
const account = process.env.CDK_ACCOUNT || "000000000000";
const region = "us-west-2";

new APIStack(app, "api", {
  crossRegionReferences: true,
  env: { account, region },
  stackName: "api",
});
```

```
new DynamoStack(this, "ddbFooTable", {
  billingMode: BillingMode.PROVISIONED,
  deletionProtection: false,
  encryption: TableEncryption.AWS_MANAGED,
  partitionKey: { name: "id", type: AttributeType.STRING },
  pointInTimeRecovery: false,
  removalPolicy: false
    ? RemovalPolicy.RETAIN
    : RemovalPolicy.DESTROY,
  replicationRegions: ["us-west-1"],
  stream: StreamViewType.NEW_AND_OLD_IMAGES,
  tableName: "foo",
});
```

### Environment

```markdown
- OS: OSX 13.4
- LocalStack: latest (70e077bf43491cc0954698c1240159caa9cecc0ac6652b890b52aaf0801d5fcb)
- aws-cdk-lib: 2.90.0
- aws-cdk-local: 2.18.0
```

### Anything else?

Unfortunately, I'm in a position where I need the latest update due to Cognito User Pool domains not being functional in prior releases. I'm trying to get our devs to authenticate locally with an Oauth2 IDP flow instead of forcing them to authenticate with a live-stable environment. More information [here](https://github.com/localstack/localstack/issues/8700).

**Comment by laas29** [comment]
+1

**Comment by dominikschubert** [comment]
The issue you've been seeing should've been fixed with https://github.com/localstack/localstack/pull/8882 and available in our latest images.

Also, please let us know if you're still experiencing the reported exception, then we can re-open the issue here if needed :+1:
