### ISSUE TITLE
bug: --extra-py-files does not function as expected when referencing a ZIP file in S3

### ISSUE THREAD

**Issue by snhardin** [localstack/localstack#8862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi all. This is a follow-up to #8335. I was informed that this functionality already exists in Localstack, but as of v2.1.0, I'm not seeing correct behavior here.

Please reference #8335 for current behavior.

### Expected Behavior

Please reference #8335 for expected behavior.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
version: "3.8"

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:443:443"              # LocalStack https
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SQS_ENDPOINT_STRATEGY=domain
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Here are the default args for the glue job as specified by our Terraform:

```
    "--class"                     = "GlueApp"
    "--additional-python-modules" = "s3://${var.code_bucket_name}/resources/PyMySQL-1.0.3-py3-none-any.whl,s3://${var.code_bucket_name}/resources/dependency_injector-4.41.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl,s3://${var.code_bucket_name}/resources/six-1.16.0-py2.py3-none-any.whl,s3://${var.code_bucket_name}/resources/Jinja2-3.1.2-py3-none-any.whl,s3://${var.code_bucket_name}/resources/MarkupSafe-2.1.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
    "--mysql_dev_url"           = var.dev_url_arn
    "--mysql_dev_secret"        = var.dev_secret_arn
    "--max_retries"               = 1
    "--shard_number"              = 1
    "--shard_count"               = 1
    "--custom_jdbc_path"          = ""
    "--s3_write_bucket"           = var.write_bucket_name
    "--localstack"                = 1
    "--extra-py-files"            = "s3://${var.code_bucket_name}/dist/MY_LIBRARY_HERE.zip"
```

The Glue job was then triggered using the following command:

```
awslocal glue start-job-run --job-name 'my-glue-job' --arguments '{"--s3_manifest_url": "s3://sensitive/path/omitted.json"}'
```

### Environment

```markdown
- OS: Mac OS Monterey 12.6.8
- LocalStack: v2.1.0
```

### Anything else?

Opening a new issue per @alexrashed. Happy to follow up on Slack if needed.

**Comment by snhardin** [comment]
Hey @alexrashed. Thanks for the changes! My colleagues report that they see new functionality. However, it's still not 1:1 with functionality available in AWS Glue.

We are seeing the Localstack-pro image attempting to install our zipped code via `pip install`. However, our code is not a PyPi or Wheel package, so this step fails. The code is meant to be included adjacent to our entrypoint script, which is [functionality supported out-of-the-box by AWS](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-libraries.html#extra-py-files-support). I have attached the log below.

```
park/3.1.1/jars/joda-time-2.9.3.jar
localstack_main  | 2023-09-12T17:43:35.731 DEBUG --- [ncthread3337] localstack.utils.http      : Done downloading https://repo1.maven.org/maven2/joda-time/joda-time/2.9.3/joda-time-2.9.3.jar, response code 200, total 613K
localstack_main  | 2023-09-12T17:43:35.867 DEBUG --- [ncthread3337] localstack.utils.http      : Starting download from https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.23/mysql-connector-java-8.0.23.jar to /var/lib/localstack/lib/spark/3.1.1/jars/mysql-connector-java-8.0.23.jar
localstack_main  | 2023-09-12T17:43:36.024 DEBUG --- [ncthread3337] localstack.utils.http      : Written 1024K (total 1024K of 2358K) to /var/lib/localstack/lib/spark/3.1.1/jars/mysql-connector-java-8.0.23.jar
localstack_main  | 2023-09-12T17:43:36.075 DEBUG --- [ncthread3337] localstack.utils.http      : Written 1024K (total 2048K of 2358K) to /var/lib/localstack/lib/spark/3.1.1/jars/mysql-connector-java-8.0.23.jar
localstack_main  | 2023-09-12T17:43:36.091 DEBUG --- [ncthread3337] localstack.utils.http      : Done downloading https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.23/mysql-connector-java-8.0.23.jar, response code 200, total 2358K
localstack_main  | 2023-09-12T17:43:36.096 DEBUG --- [ncthread3337] localstack.packages.api    : Installation of spark skipped (already installed).
localstack_main  | 2023-09-12T17:43:36.096 DEBUG --- [ncthread3337] localstack.packages.api    : Performing runtime setup for already installed package.
localstack_main  | 2023-09-12T17:43:36.344 DEBUG --- [ncthread3337] localstack.utils.run       : Executing command: rm -rf "/tmp/tmp7ae5pv_l"
localstack_main  | 2023-09-12T17:43:36.348 DEBUG --- [ncthread3337] localstack.utils.run       : Executing command: ['pip', 'install', '/tmp/PyMySQL-1.0.3-py3-none-any.whl']
localstack_main  | 2023-09-12T17:43:37.031 DEBUG --- [ncthread3337] localstack.utils.run       : Executing command: rm -rf "/tmp/tmpz_qb3uzp"
localstack_main  | 2023-09-12T17:43:37.034 DEBUG --- [ncthread3337] localstack.utils.run       : Executing command: ['pip', 'install', '/tmp/dependency_injector-4.41.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl']
localstack_main  | 2023-09-12T17:43:37.713 DEBUG --- [ncthread3337] localstack.utils.run       : Executing command: rm -rf "/tmp/tmpofm23lxe"
localstack_main  | 2023-09-12T17:43:37.715 DEBUG --- [ncthread3337] localstack.utils.run       : Executing command: ['pip', 'install', '/tmp/six-1.16.0-py2.py3-none-any.whl']
localstack_main  | 2023-09-12T17:43:38.311 DEBUG --- [ncthread3337] localstack.utils.run       : Executing command: rm -rf "/tmp/tmpfcthm3_f"
localstack_main  | 2023-09-12T17:43:38.313 DEBUG --- [ncthread3337] localstack.utils.run       : Executing command: ['pip', 'install', '/tmp/Jinja2-3.1.2-py3-none-any.whl']
localstack_main  | 2023-09-12T17:43:38.916 DEBUG --- [ncthread3337] localstack.utils.run       : Executing command: rm -rf "/tmp/tmpgkq0dgxf"
localstack_main  | 2023-09-12T17:43:38.917 DEBUG --- [ncthread3337] localstack.utils.run       : Executing command: ['pip', 'install', '/tmp/MarkupSafe-2.1.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl']
localstack_main  | 2023-09-12T17:43:39.549 DEBUG --- [ncthread3337] localstack.utils.run       : Executing command: rm -rf "/tmp/tmpfsno29ai"
localstack_main  | 2023-09-12T17:43:39.551 DEBUG --- [ncthread3337] localstack.utils.run       : Executing command: ['pip', 'install', '/tmp/snhardin_library.zip']
localstack_main  | ERROR: '['pip', 'install', '/tmp/snhardin_library.zip']': exit code 1; output: b"Processing /tmp/snhardin_library.zip\nERROR: file:///tmp/snhardin_library.zip does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.\n"
localstack_main  | 2023-09-12T17:43:39.814 ERROR --- [ncthread3337] l.s.glue.job_executor      : Glue job execution failed: Command '['pip', 'install', '/tmp/snhardin_library.zip']' returned non-zero exit status 1.
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/glue/job_executor.py.enc", line 73, in J
localstack_main  |     try:K();D[A][G]=JobRunState.SUCCEEDED
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/glue/job_executor.py.enc", line 82, in K
localstack_main  |     if not L:LOG.debug('Scala class name is not set. Executing as Python command.');E=f"/tmp/script-{short_uid()}.py";J=get_job_cmd_pyspark(F,G,C,B,E)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/glue/job_executor.py.enc", line 61, in get_job_cmd_pyspark
localstack_main  |     if G:install_user_defined_python_modules(I,J,G,B,K)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/glue/job_executor.py.enc", line 102, in install_user_defined_python_modules
localstack_main  |     H=['pip','install',A];run_in_spark(H)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/bigdata/bigdata_utils.py.enc", line 84, in run_in_spark
localstack_main  |     def run_in_spark(command,**A):return run_in_container(command,SPARK_CONTAINER_NAME,**A)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/bigdata/bigdata_utils.py.enc", line 88, in run_in_container
localstack_main  |     if ext_config.BIGDATA_MONO_CONTAINER:A=select_attributes(A,[C]);return run(B,**A)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/run.py", line 119, in run
localstack_main  |     raise e
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/run.py", line 69, in run
localstack_main  |     output = subprocess.check_output(cmd, shell=shell, stderr=stderr, env=env_dict, cwd=cwd)
localstack_main  |   File "/usr/local/lib/python3.10/subprocess.py", line 421, in check_output
localstack_main  |     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
localstack_main  |   File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
localstack_main  |     raise CalledProcessError(retcode, process.args,
localstack_main  | subprocess.CalledProcessError: Command '['pip', 'install', '/tmp/snhardin_library.zip']' returned non-zero exit status 1.
localstack_main  | 2023-09-12T17:43:39.869 DEBUG --- [ncthread3337] l.s.glue.job_executor      : Stdout/stderr logs from Glue job run: Processing /tmp/snhardin_library.zip
localstack_main  | ERROR: file:///tmp/snhardin_library.zip does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
localstack_main  | 
localstack_main  | None
localstack_main  | 2023-09-12T17:43:39.968 DEBUG --- [  asgi_gw_13] l.services.plugins         : checking service health logs:4566
```

**Comment by macnev2013** [comment]
Hi @snhardin , Thanks for reporting the issue. This should be fixed in the `latest` version of `localstack/localstack-pro` image. Can you try once again after pulling the `latest` docker image? Thanks.
