### ISSUE TITLE
bug: AWS Glue job run language type based on "--class" default argument instead of "--job-language" in v2.2.0

### ISSUE THREAD

**Issue by zachtayl** [localstack/localstack#8874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In localstack v2.2.0, I have a python Glue job defined via Terraform. I specify the "--class" default argument, though it is executing a python script. I do not include the "--job-language" default argument.

When starting the glue job via boto3 or awslocal commands, I see the job attempted to be run as a scala script, due to the presence of the "--class" default argument. In the following error output, line 2 shows where the script is picked up as Scala, despite the referenced .py file in line 1.

```
localstack_main  | 2023-08-08T17:05:45.648 DEBUG --- [uncthread614] l.s.glue.job_executor      : Attempting to download Glue job script file from S3 location: s3://<bucket>/<path>.py
localstack_main  | 2023-08-08T17:05:45.684 DEBUG --- [uncthread614] l.s.glue.job_executor      : Scala class name is set (App). Executing as Scala script.
localstack_main  | 2023-08-08T17:05:45.685 DEBUG --- [uncthread614] l.s.glue.job_executor      : Running command for Glue job: ['bash', '-c', 'echo "App.main(Array())" | AWS_ACCESS_KEY_ID=<key> AWS_SECRET_ACCESS_KEY=<key> AWS_REGION=<region> SPARK_CONF_DIR=/tmp/aws-glue-libs/conf java -Dcom.amazonaws.sdk.disableCertChecking=true -cp /tmp/aws-glue-libs/conf/:/usr/local/spark-2.4.3-bin-without-hadoop-scala-2.12/jars/*:/tmp/aws-glue-libs/jarsv1/* -Dscala.usejavacp=true -Xmx1g org.apache.spark.deploy.SparkSubmit --class org.apache.spark.repl.Main spark-shell -i /tmp/script-e9205878.scala']
localstack_main  | 2023-08-08T17:05:45.686 DEBUG --- [uncthread614] localstack.utils.run       : Executing command: ['bash', '-c', 'echo "App.main(Array())" | AWS_ACCESS_KEY_ID=<key> AWS_SECRET_ACCESS_KEY=<key> AWS_REGION=<region> SPARK_CONF_DIR=/tmp/aws-glue-libs/conf java -Dcom.amazonaws.sdk.disableCertChecking=true -cp /tmp/aws-glue-libs/conf/:/usr/local/spark-2.4.3-bin-without-hadoop-scala-2.12/jars/*:/tmp/aws-glue-libs/jarsv1/* -Dscala.usejavacp=true -Xmx1g org.apache.spark.deploy.SparkSubmit --class org.apache.spark.repl.Main spark-shell -i /tmp/script-e9205878.scala']
localstack_main  | ERROR: '['bash', '-c', 'echo "App.main(Array())" | AWS_ACCESS_KEY_ID=<key> AWS_SECRET_ACCESS_KEY=<key> AWS_REGION=<region> SPARK_CONF_DIR=/tmp/aws-glue-libs/conf java -Dcom.amazonaws.sdk.disableCertChecking=true -cp /tmp/aws-glue-libs/conf/:/usr/local/spark-2.4.3-bin-without-hadoop-scala-2.12/jars/*:/tmp/aws-glue-libs/jarsv1/* -Dscala.usejavacp=true -Xmx1g org.apache.spark.deploy.SparkSubmit --class org.apache.spark.repl.Main spark-shell -i /tmp/script-e9205878.scala']': exit code 1; output: b'Error: Could not find or load main class org.apache.spark.deploy.SparkSubmit\nCaused by: java.lang.ClassNotFoundException: org.apache.spark.deploy.SparkSubmit\n'
localstack_main  | 2023-08-08T17:05:45.801 DEBUG --- [uncthread614] l.s.glue.job_executor      : Glue job execution failed: Command '['bash', '-c', 'echo "App.main(Array())" | AWS_ACCESS_KEY_ID=<key> AWS_SECRET_ACCESS_KEY=<key> AWS_REGION=<region> SPARK_CONF_DIR=/tmp/aws-glue-libs/conf java -Dcom.amazonaws.sdk.disableCertChecking=true -cp /tmp/aws-glue-libs/conf/:/usr/local/spark-2.4.3-bin-without-hadoop-scala-2.12/jars/*:/tmp/aws-glue-libs/jarsv1/* -Dscala.usejavacp=true -Xmx1g org.apache.spark.deploy.SparkSubmit --class org.apache.spark.repl.Main spark-shell -i /tmp/script-e9205878.scala']' returned non-zero exit status 1. Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/glue/job_executor.py.enc", line 72, in G
localstack_main  |     try:H();D[A][E]=JobRunState.SUCCEEDED
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/glue/job_executor.py.enc", line 83, in H
localstack_main  |     copy_into_spark_container(G,A);LOG.debug('Running command for Glue job: %s',F);D=run_in_spark(F);M='SSL Certificate checking for endpoints has been explicitly disabled.';D=D.partition(M)[2]or D;LOG.debug('Received result for Glue job: %s',D)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/bigdata/bigdata_utils.py.enc", line 83, in run_in_spark
localstack_main  |     def run_in_spark(command,**A):return run_in_container(command,SPARK_CONTAINER_NAME,**A)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/utils/bigdata/bigdata_utils.py.enc", line 87, in run_in_container
localstack_main  |     if ext_config.BIGDATA_MONO_CONTAINER:A=select_attributes(A,[C]);return run(B,**A)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/run.py", line 119, in run
localstack_main  |     raise e
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/run.py", line 69, in run
localstack_main  |     output = subprocess.check_output(cmd, shell=shell, stderr=stderr, env=env_dict, cwd=cwd)
localstack_main  |   File "/usr/local/lib/python3.10/subprocess.py", line 421, in check_output
localstack_main  |     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
localstack_main  |   File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
localstack_main  |     raise CalledProcessError(retcode, process.args,
localstack_main  | subprocess.CalledProcessError: Command '['bash', '-c', 'echo "App.main(Array())" | AWS_ACCESS_KEY_ID=<key> AWS_SECRET_ACCESS_KEY=<key> AWS_REGION=<region> SPARK_CONF_DIR=/tmp/aws-glue-libs/conf java -Dcom.amazonaws.sdk.disableCertChecking=true -cp /tmp/aws-glue-libs/conf/:/usr/local/spark-2.4.3-bin-without-hadoop-scala-2.12/jars/*:/tmp/aws-glue-libs/jarsv1/* -Dscala.usejavacp=true -Xmx1g org.apache.spark.deploy.SparkSubmit --class org.apache.spark.repl.Main spark-shell -i /tmp/script-e9205878.scala']' returned non-zero exit status 1.
localstack_main  | 
localstack_main  | 2023-08-08T17:05:45.801 DEBUG --- [uncthread614] l.s.glue.job_executor      : Stdout/stderr logs from Glue job run: Error: Could not find or load main class org.apache.spark.deploy.SparkSubmit
localstack_main  | Caused by: java.lang.ClassNotFoundException: org.apache.spark.deploy.SparkSubmit
localstack_main  | 
localstack_main  | None
```

### Expected Behavior

In previous versions of Localstack used, specifically v2.1.0, I have the same configuration, Glue 3.0 defined via terraform with "--class" = "App", also not including the "--job-language" default argument.

When starting the job via boto3 or awslocal commands, The job is started and successfully identified as a python job, then the required dependencies begin download.

```
localstack_main  | 2023-08-08T19:35:50.502 DEBUG --- [uncthread287] l.s.glue.job_executor      : Attempting to download Glue job script file from S3 location: s3://<bucket>/<glue_fn>.py
localstack_main  | 2023-08-08T19:35:50.513 DEBUG --- [uncthread287] l.s.glue.job_executor      : Getting job command to run for job type 'pythonshell'
localstack_main  | 2023-08-08T19:35:50.514 DEBUG --- [uncthread287] localstack.packages.api    : Starting installation of hadoop...
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose file used
```
version: "3.8"

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:443:443"              # LocalStack https
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SQS_ENDPOINT_STRATEGY=domain
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
   ```
 
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Default args for the glue job as specified by our Terraform:

```
    "--class"                     = "App"
    "--additional-python-modules" = "s3://${var.code_bucket_name}/resources/PyMySQL-1.0.3-py3-none-any.whl,s3://${var.code_bucket_name}/resources/dependency_injector-4.41.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl,s3://${var.code_bucket_name}/resources/six-1.16.0-py2.py3-none-any.whl,s3://${var.code_bucket_name}/resources/Jinja2-3.1.2-py3-none-any.whl,s3://${var.code_bucket_name}/resources/MarkupSafe-2.1.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl"
    "--mysql_dev_url"           = var.dev_url_arn
    "--mysql_dev_secret"        = var.dev_secret_arn
    "--max_retries"               = 1
    "--shard_number"              = 1
    "--shard_count"               = 1
    "--custom_jdbc_path"          = ""
    "--s3_write_bucket"           = var.write_bucket_name
    "--localstack"                = 1
```

   Job started either with boto3 or awslocal glue start-job-run

### Environment

```markdown
- OS: MacOs Ventura 13.4.1
- LocalStack: v2.2.0
```

### Anything else?

The following is a summary of experimentation regarding how these default arguments have behaved in different localstack versions

|  | Localstack Version | "--class" value | "--job-language" value | Job recognized as |
|---|--------|--------|--------|--------|
| 1 | v2.1.0 | "App" | "python" | Python job |
| 2 | v2.2.0 | "App" | Omitted | Scala job |
| 3 | v2.2.0 | "App" | "python" | Scala job |
| 4 | v2.2.0 | Omitted | "python" | Python Job |
| 5 | v2.2.0 | Omitted | "scala" | Python Job | 

2, 3, 5 all exhibit behavior that does not align with the descriptions for --class and --job-language given in this 
[documentation](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-glue-arguments.html)

**Comment by zachtayl** [comment]
I have confirmed that this is still present in the `latest` version of localstack.

**Comment by macnev2013** [comment]
Hello, we are pleased to inform you that we have implemented changes that should resolve your reported issue. Kindly update to the latest LocalStack container image and let us know if your issue has been resolved. Thank you!
