### ISSUE TITLE
bug: Localstack v2.2.0/v2.1.0 Glue Job dependency downloading from depreciated source

### ISSUE THREAD

**Issue by zachtayl** [localstack/localstack#8875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On v2.1.0 and v2.2.0, after starting a python AWS Glue 3.0/4.0 job, localstack attempts to download dependencies from adoptopenjok.jfrog.io. These downloads fail during brownout periods currently ongoing.

```
localstack_main  | 2023-08-09T14:50:26.820 DEBUG --- [uncthread341] localstack.packages.api    : Starting installation of java...
localstack_main  | 2023-08-09T14:50:26.820  WARN --- [uncthread341] l.packages.core            : java will be installed as an OS package, even though install target is _not_ set to be static.
localstack_main  | 2023-08-09T14:50:27.171 DEBUG --- [uncthread341] l.s.glue.job_executor      : Glue job execution failed: Installation of java failed. Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/packages/api.py", line 89, in install
localstack_main  |     self._prepare_installation(target)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/packages/core.py", line 24, in _prepare_installation
localstack_main  |     A._os_switch(debian=A._debian_prepare_install,redhat=A._redhat_prepare_install,target=B)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/packages/core.py", line 18, in _os_switch
localstack_main  |     if is_debian()or not in_docker()and debian_fallback:return debian(**A)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/packages/java.py", line 25, in _debian_prepare_install
localstack_main  |     download(f"{B}/api/gpg/key/public",A);run(['apt-key','add',A])
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/utils/http.py", line 201, in download
localstack_main  |     raise Exception("Failed to download %s, response code %s" % (url, r.status_code))
localstack_main  | Exception: Failed to download https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public, response code 503
localstack_main  | 
```

### Expected Behavior

Typically, and during periods where these brownouts are not in effect, the required dependencies will be downloaded and the job run successfully.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker compose file used

```
version: "3.8"

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:443:443"              # LocalStack https
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SQS_ENDPOINT_STRATEGY=domain
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

with boto3 or awslocal glue start-job-run. 
Occurs to jobs defined as 3.0/4.0 and on both v2.1.0 and v2.2.0

### Environment

```markdown
- OS: Mac Os Ventura 13.4.1
- LocalStack: v2.1.0/v2.2.0
```

### Anything else?

Reference of depreciation and brownout schedule: https://adoptium.net/blog/2023/07/adoptopenjdk-jfrog-io-has-been-deprecated/

**Comment by dfangl** [comment]
Thank you for bringing this to our attention!
We will adapt our installers accordingly.

**Comment by dfangl** [comment]
Hi @zachtayl !
In our latest `localstack/localstack-pro` image, we migrated to using the new eclipse temurin jdk distributions, and it should not be affected by the brownout anymore.
Thank you again for reporting this!
