### ISSUE TITLE
bug: Connection error to analytics.localstack.cloud on startup

### ISSUE THREAD

**Issue by kristallizer** [localstack/localstack#8877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```shell
DEBUG=1 localstack start
Process Process-1:
Traceback (most recent call last):
  File "urllib3/connection.py", line 203, in _new_conn
  File "urllib3/util/connection.py", line 85, in create_connection
  File "urllib3/util/connection.py", line 73, in create_connection
ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 790, in urlopen
  File "urllib3/connectionpool.py", line 491, in _make_request
  File "urllib3/connectionpool.py", line 467, in _make_request
  File "urllib3/connectionpool.py", line 1092, in _validate_conn
  File "urllib3/connection.py", line 611, in connect
  File "urllib3/connection.py", line 218, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x1104a2e60>: Failed to establish a new connection: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests/adapters.py", line 486, in send
  File "urllib3/connectionpool.py", line 844, in urlopen
  File "urllib3/util/retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='analytics.localstack.cloud', port=443): Max retries exceeded with url: /v1/events (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1104a2e60>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing/process.py", line 314, in _bootstrap
  File "multiprocessing/process.py", line 108, in run
  File "localstack/utils/analytics/cli.py", line 28, in _publish_cmd_as_analytics_event
  File "localstack/utils/analytics/publisher.py", line 39, in publish
  File "localstack/utils/analytics/client.py", line 89, in append_events
  File "requests/sessions.py", line 637, in post
  File "requests/sessions.py", line 589, in request
  File "requests/sessions.py", line 703, in send
  File "requests/adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='analytics.localstack.cloud', port=443): Max retries exceeded with url: /v1/events (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1104a2e60>: Failed to establish a new connection: [Errno 61] Connection refused'))

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 2.2.0

[15:02:14] starting LocalStack in Docker mode 🐳    
```

### Expected Behavior

Those errors shouldn't occur.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack  # installed via homebrew

### Environment

```markdown
- OS: MacOS Ventura
- LocalStack CLI: 2.2.0
```

**Comment by kristallizer** [comment]
Never mind, I think this is on me. These requests are being blocked my local network's content blocker.
