### ISSUE TITLE
bug: cdklocal deploy is failing

### ISSUE THREAD

**Issue by ivann1990** [localstack/localstack#8883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

_command I am running:_

**cdklocal deploy**

_console output I got:_

This deployment will make potentially sensitive changes according to your current security approval level (--require-approval broadening).
Please confirm you intend to make the following modifications:

IAM Statement Changes
...... table is shown here ...... 
(NOTE: There may be security-related changes not in this list. See https://github.com/aws/aws-cdk/issues/1299)

Do you wish to deploy these changes (y/n)? y
ProjectNameLocalStack: deploying... [1/1]
ProjectNameLocalStack: creating CloudFormation changeset...
ProjectNameLocalStack | 0/5 | 1:36:41 PM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack | ProjectNameLocalStack
ProjectNameLocalStack | 1/5 | 1:36:41 PM | CREATE_COMPLETE      | AWS::SQS::Queue       
     | DeadLetterQueuelocal (DeadLetterQueuelocalB4CF5548)
ProjectNameLocalStack | 1/5 | 1:36:41 PM | CREATE_FAILED        | AWS::SQS::QueuePolicy 
     | DeadLetterQueuelocal/Policy (DeadLetterQueuelocalPolicy9551067A) 'NoneType' object has no attribute 'get'
ProjectNameLocalStack | 1/5 | 1:36:41 PM | CREATE_FAILED        | AWS::CloudFormation::Stack | ProjectNameLocalStack 'NoneType' object has no attribute 'get'

Failed resources:
ProjectNameLocalStack | 1:36:41 PM | CREATE_FAILED        | AWS::SQS::QueuePolicy      | DeadLetterQueuelocal/Policy (DeadLetterQueuelocalPolicy9551067A) 'NoneType' object has no attribute 'get'

 ❌  ProjectNameLocalStack failed: Error: The stack named ProjectNameLocalStack failed to d
eploy: CREATE_FAILED ('NoneType' object has no attribute 'get'): 'NoneType' object has no attribute 'get'
    at FullCloudFormationDeployment.monitorDeployment (D:\ProjectNameApp\CDK\node_modules\aws-cdk\lib\index.js:426:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)     
    at async Object.deployStack2 [as deployStack] (D:\ProjectNameApp\CDK\node_modules\aws-cdk\lib\index.js:429:153307)
    at async D:\ProjectNameApp\CDK\node_modules\aws-cdk\lib\index.js:429:136985

 ❌ Deployment failed: Error: The stack named ProjectNameLocalStack failed to deploy: CRE
ATE_FAILED ('NoneType' object has no attribute 'get'): 'NoneType' object has no attribute 'get'
    at FullCloudFormationDeployment.monitorDeployment (D:\ProjectNameApp\CDK\node_modules\aws-cdk\lib\index.js:426:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)     
    at async Object.deployStack2 [as deployStack] (D:\ProjectNameApp\CDK\node_modules\aws-cdk\lib\index.js:429:153307)
    at async D:\ProjectNameApp\CDK\node_modules\aws-cdk\lib\index.js:429:136985

The stack named ProjectNameLocalStack failed to deploy: CREATE_FAILED ('NoneType' object has no attribute 'get'): 'NoneType' object has no attribute 'get'

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands 
    
    cdklocal bootstrap
    cdklocal deploy

### Environment

```markdown
- OS: Windows 10 Home
- LocalStack: latest
```

**Comment by ivann1990** [comment]
the issue was present when using the docker image `localstack/localstack:latest`
but it was fixed by using the docker image `localstack/localstack:2.2.0`
