### ISSUE TITLE
bug: Api Gateway Rest won't load openapi file

### ISSUE THREAD

**Issue by juicyarts** [localstack/localstack#8930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to feed `aws_api_gateway_rest_api` (using terraform) with an openapi file, localstack throws errors related to not being able to parse the version information of the openapi file. The error thrown looks like this:

```shell
issue-reproduction-localstack-1  | Traceback (most recent call last):
issue-reproduction-localstack-1  |   File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
issue-reproduction-localstack-1  |     handler(self, self.context, response)
issue-reproduction-localstack-1  |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 123, in __call__
issue-reproduction-localstack-1  |     handler(chain, context, response)
issue-reproduction-localstack-1  |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 93, in __call__
issue-reproduction-localstack-1  |     skeleton_response = self.skeleton.invoke(context)
issue-reproduction-localstack-1  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 154, in invoke
issue-reproduction-localstack-1  |     return self.dispatch_request(context, instance)
issue-reproduction-localstack-1  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 166, in dispatch_request
issue-reproduction-localstack-1  |     result = handler(context, instance) or {}
issue-reproduction-localstack-1  |   File "/opt/code/localstack/localstack/aws/forwarder.py", line 60, in _call
issue-reproduction-localstack-1  |     return handler(context, req)
issue-reproduction-localstack-1  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 118, in __call__
issue-reproduction-localstack-1  |     return self.fn(*args, **kwargs)
issue-reproduction-localstack-1  |   File "/opt/code/localstack/localstack/aws/api/core.py", line 167, in operation_marker
issue-reproduction-localstack-1  |     return fn(*args, **kwargs)
issue-reproduction-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/provider.py", line 351, in put_rest_api
issue-reproduction-localstack-1  |     rest_api = import_api_from_openapi_spec(rest_api, openapi_spec, context=context)
issue-reproduction-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 823, in import_api_from_openapi_spec
issue-reproduction-localstack-1  |     rest_api.version = str(resolved_schema.get("info", {}).get("version")) or None
issue-reproduction-localstack-1  | AttributeError: 'str' object has no attribute 'get'
```

### Expected Behavior

Localstack should not complain about a valid openapi specificaion

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

* docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    terraform

#### Example

I have created a minimal repo to reproduce the problem:

* https://github.com/juicyarts/localstack-openapi-minimal 

### Environment

```markdown
- OS: Mac M2 Pro / MacOS Ventura 13.0
- LocalStack: latest
```

### Anything else?

Localstack is awesome, thanks for your efforts, and if i can provide more information let me know (i will also dive deeper into the code and see if i can provide a fix, but that might take some time)!

**Comment by bentsku** [comment]
Hello @juicyarts and thanks for your report. Does your Terraform deploys successfully against AWS? 

It seems LocalStack is not able to get the data from the template:
```hcl
locals {
  stage_name = "local"
  region     = "eu-central-1"
  account_id = "000000000000"
  template   = "../openapi.yml"
}


resource "aws_api_gateway_rest_api" "users_api" {
  name        = "vnls-local-users-api"
  description = "API for VNLS Users"
  body        = local.template
}
```
I don't think the `local.template` is being mapped to the file here, I'm not an expert in Terraform, but I think we're simply passing `../openapi.yml` to the body of the API? 
Isn't it missing the `file` method around the path?
https://developer.hashicorp.com/terraform/language/functions/file

Could you try to run this against AWS and see if it works?

We also have a sample here with an OpenAPI import with a .yaml file, maybe this could help?
https://github.com/localstack/localstack-terraform-samples/tree/master/apigateway-openapi-3.0-import

**Comment by juicyarts** [comment]
I was able to identify the issue and it seems like i mixed up the error outputs and the issues were completely unrelated. But to give you an insight:

In the openapi spec we are using component references e.g `$ref: '#/components/schemas/User'`. It seems that for whatever reason one of the references was pointing at `'#/components/responses/UserResponse/content/application~1json/schema'` which localstack was unable to reference and was throwing:

```shell
vnls-user-tenant-management-localstack-1  | 2023-08-17T15:37:22.564 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
vnls-user-tenant-management-localstack-1  | Traceback (most recent call last):
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
vnls-user-tenant-management-localstack-1  |     handler(self, self.context, response)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 123, in __call__
vnls-user-tenant-management-localstack-1  |     handler(chain, context, response)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 93, in __call__
vnls-user-tenant-management-localstack-1  |     skeleton_response = self.skeleton.invoke(context)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 154, in invoke
vnls-user-tenant-management-localstack-1  |     return self.dispatch_request(context, instance)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 166, in dispatch_request
vnls-user-tenant-management-localstack-1  |     result = handler(context, instance) or {}
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/aws/forwarder.py", line 60, in _call
vnls-user-tenant-management-localstack-1  |     return handler(context, req)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 118, in __call__
vnls-user-tenant-management-localstack-1  |     return self.fn(*args, **kwargs)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/aws/api/core.py", line 167, in operation_marker
vnls-user-tenant-management-localstack-1  |     return fn(*args, **kwargs)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/provider.py", line 351, in put_rest_api
vnls-user-tenant-management-localstack-1  |     rest_api = import_api_from_openapi_spec(rest_api, openapi_spec, context=context)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 817, in import_api_from_openapi_spec
vnls-user-tenant-management-localstack-1  |     resolved_schema = resolve_references(copy.deepcopy(body), rest_api_id=rest_api.id)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 468, in resolve_references
vnls-user-tenant-management-localstack-1  |     return resolver.resolve_references()
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 247, in resolve_references
vnls-user-tenant-management-localstack-1  |     return self._resolve_references(self.document)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 239, in _resolve_references
vnls-user-tenant-management-localstack-1  |     data[k] = self._namespaced_resolution(k, v)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 231, in _namespaced_resolution
vnls-user-tenant-management-localstack-1  |     return self._resolve_references(data)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 239, in _resolve_references
vnls-user-tenant-management-localstack-1  |     data[k] = self._namespaced_resolution(k, v)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 231, in _namespaced_resolution
vnls-user-tenant-management-localstack-1  |     return self._resolve_references(data)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 239, in _resolve_references
vnls-user-tenant-management-localstack-1  |     data[k] = self._namespaced_resolution(k, v)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 231, in _namespaced_resolution
vnls-user-tenant-management-localstack-1  |     return self._resolve_references(data)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 239, in _resolve_references
vnls-user-tenant-management-localstack-1  |     data[k] = self._namespaced_resolution(k, v)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 231, in _namespaced_resolution
vnls-user-tenant-management-localstack-1  |     return self._resolve_references(data)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 239, in _resolve_references
vnls-user-tenant-management-localstack-1  |     data[k] = self._namespaced_resolution(k, v)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 231, in _namespaced_resolution
vnls-user-tenant-management-localstack-1  |     return self._resolve_references(data)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 239, in _resolve_references
vnls-user-tenant-management-localstack-1  |     data[k] = self._namespaced_resolution(k, v)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 231, in _namespaced_resolution
vnls-user-tenant-management-localstack-1  |     return self._resolve_references(data)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 239, in _resolve_references
vnls-user-tenant-management-localstack-1  |     data[k] = self._namespaced_resolution(k, v)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 231, in _namespaced_resolution
vnls-user-tenant-management-localstack-1  |     return self._resolve_references(data)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 239, in _resolve_references
vnls-user-tenant-management-localstack-1  |     data[k] = self._namespaced_resolution(k, v)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 231, in _namespaced_resolution
vnls-user-tenant-management-localstack-1  |     return self._resolve_references(data)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 239, in _resolve_references
vnls-user-tenant-management-localstack-1  |     data[k] = self._namespaced_resolution(k, v)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 231, in _namespaced_resolution
vnls-user-tenant-management-localstack-1  |     return self._resolve_references(data)
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 235, in _resolve_references
vnls-user-tenant-management-localstack-1  |     return self._resolve_refpath(data["$ref"])
vnls-user-tenant-management-localstack-1  |   File "/opt/code/localstack/localstack/services/apigateway/helpers.py", line 219, in _resolve_refpath
vnls-user-tenant-management-localstack-1  |     cur = cur.get(step)
vnls-user-tenant-management-localstack-1  | AttributeError: 'NoneType' object has no attribute 'get'
```

I'm sorry for creating efforts on your side and want to thank you for the support!
