### ISSUE TITLE
bug: Running docker lambda outside localstack causes "Custom images are currently not supported" error

### ISSUE THREAD

**Issue by ozeta** [localstack/localstack#9028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

invoke a lambda that is deployed outside localstack, but on localhost, in a docker container.
server logs this error  "Custom images are currently not supported" and server goes into "Failed to start runtime environment" loop

### Expected Behavior
server start lambda without looping over runtime start
lambda invokation command doesnt fail

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml

```
version: "3.8"

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - LOCALSTACK_DEBUG=1
      - DEBUG=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_REGION=us-east-1
      - LAMBDA_IGNORE_ARCHTIECTURE=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

run with
`docker-compose up`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

lambda code:

```
def handler:
    return {"statusCode": 200, "body": "OK"}
```

lambda Dockerfile:

```
FROM public.ecr.aws/lambda/python:3.9
COPY . ./
CMD ["handler"]
```

and finally, initialization commands:

```
awslocal ssm put-parameter --name "queue-name" --value "request-queue"
awslocal sqs create-queue --queue-name "request-queue"
awslocal lambda create-function --no-cli-pager \
    --function-name lambda-provisioning \
    --package-type Image \
    --code ImageUri="192.168.86.20.nip.io:15000/lambda:latest" \
    --role arn:aws:iam::000000000000:role/lambda-role \
    --handler="handler"
```
  

invoke the lambda
`
 awslocal lambda invoke --function-name lambda-provisioning out --log-type Tail
`

what i'm getting is:

```terraform-aws-hxp-subcription-delivery-pipeline-localstack-1  | 2023-08-30T17:01:01.377  WARN --- [ng:$LATEST_0] l.s.l.i.runtime_environmen : Failed to start runtime environment for ID=f0cf30b475f3e844783f1e6cad1009d8 with: Custom images are currently not supported
terraform-aws-hxp-subcription-delivery-pipeline-localstack-1  | Traceback (most recent call last):
terraform-aws-hxp-subcription-delivery-pipeline-localstack-1  |   File "/opt/code/localstack/localstack/services/lambda_/invocation/runtime_environment.py", line 172, in start
terraform-aws-hxp-subcription-delivery-pipeline-localstack-1  |     self.runtime_executor.start(self.get_environment_variables())
terraform-aws-hxp-subcription-delivery-pipeline-localstack-1  |   File "/opt/code/localstack/localstack/services/lambda_/invocation/docker_runtime_executor.py", line 302, in start
terraform-aws-hxp-subcription-delivery-pipeline-localstack-1  |     container_config.image_name = self.get_image()
terraform-aws-hxp-subcription-delivery-pipeline-localstack-1  |   File "/opt/code/localstack/localstack/services/lambda_/invocation/docker_runtime_executor.py", line 231, in get_image
terraform-aws-hxp-subcription-delivery-pipeline-localstack-1  |     raise NotImplementedError("Custom images are currently not supported")
terraform-aws-hxp-subcription-delivery-pipeline-localstack-1  | NotImplementedError: Custom images are currently not supported```

### Environment

```markdown
- OS: MacOs 13.5.1
- LocalStack: latest
```

**Comment by dominikschubert** [comment]
I apologize for the misleading message here, we'll update this message to be more clear in the future. Using container images for Lambda functions is actually a feature that is only available in the `localstack/localstack-pro` image which requires a paid subscription. In the free version we currently only support managed runtimes.

**Comment by ozeta** [comment]
hi @dominikschubert thanks!
