### ISSUE TITLE
Spring Cloud Stream kinesis KPL issue writing to kinesis InvalidClientTokenId

### ISSUE THREAD

**Issue by kothapet** [localstack/localstack#9110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to run a SCS (spring cloud stream) application with kinesis binder using KPL (Kinesis Producer Library). It works fine when I am connecting to AWS kinesis, but doesn't work when I point my application to localstack. I created the @bean to override the kinesis producer config for kinesis/cloudwatch/sts endpoints like below based on https://github.com/localstack/localstack/issues/507.

Full code at https://github.com/kothapet/ScsKinesisProj1

```
	@Bean
	public KinesisProducerConfiguration kinesisProducerConfiguration()  {
		
		return new KinesisProducerConfiguration()
				.setCredentialsProvider(DefaultAWSCredentialsProviderChain())
				.setRegion("us-east-1")
				.setStsEndpoint("localhost")
				.setStsPort(4566)
				.setKinesisEndpoint("localhost")
				.setKinesisPort(4566)
				.setCloudwatchEndpoint("localhost")
				.setCloudwatchPort(4566)
				.setVerifyCertificate(false);
	}	

```
However I am getting the following error InvalidClientTokenId.
In the log there are two places where it shows which endpoint it is using. First time around it shows localhost:4566 (kinesis/cloudwatch/sts), however second time it show using default endpoint for all. And the IP address it shows for STS is AWS not localstack.

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.2)

2023-09-11T16:45:10.138-04:00  INFO 36207 --- [           main] c.g.k.scs.ScsKinesisProj1Application     : Starting ScsKinesisProj1Application using Java 17.0.8 with PID 36207 (/media/anand/DATA/EclipseWSLx/git/ScsKinesisProj1/target/classes started by anand in /media/anand/DATA/EclipseWSLx/git/ScsKinesisProj1)
2023-09-11T16:45:10.143-04:00  INFO 36207 --- [           main] c.g.k.scs.ScsKinesisProj1Application     : The following 1 profile is active: "local"
2023-09-11T16:45:11.272-04:00  INFO 36207 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2023-09-11T16:45:11.282-04:00  INFO 36207 --- [           main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
**** KinesisProducer ***
getAWSAccessKeyId : test
getAWSSecretKey   : test
2023-09-11T16:45:12.097-04:00  INFO 36207 --- [           main] c.a.s.kinesis.producer.KinesisProducer   : Extracting binaries to /tmp/amazon-kinesis-producer-native-binaries
2023-09-11T16:45:13.122-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.114058] [0x00008db2][0x00007fd8aac86840] [info] [logging.cc:89] Set boost log level to info
2023-09-11T16:45:13.123-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.114132] [0x00008db2][0x00007fd8aac86840] [info] [logging.cc:179] Set AWS Log Level to INFO
2023-09-11T16:45:13.128-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.128031] [0x00008db2][0x00007fd8aac86840] [info] [AWS Log: WARN](ClientConfiguration)Retry Strategy will use the default max attempts.
2023-09-11T16:45:13.129-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.129627] [0x00008db2][0x00007fd8aac86840] [info] [main.cc:257] Region has been successfully set to us-east-1 from user's input configuration
2023-09-11T16:45:13.130-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.129879] [0x00008db2][0x00007fd8aac86840] [info] [main.cc:348] Setting CA path to /tmp/amazon-kinesis-producer-native-binaries/cacerts
2023-09-11T16:45:13.130-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.129900] [0x00008db2][0x00007fd8aac86840] [info] [main.cc:383] Starting up main producer
2023-09-11T16:45:13.130-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.129926] [0x00008db2][0x00007fd8aac86840] [info] [AWS Log: WARN](ClientConfiguration)Retry Strategy will use the default max attempts.
2023-09-11T16:45:13.130-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.129945] [0x00008db2][0x00007fd8aac86840] [info] [kinesis_producer.cc:111] Using Region: us-east-1
2023-09-11T16:45:13.131-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.129956] [0x00008db2][0x00007fd8aac86840] [info] [kinesis_producer.cc:134] Using per request threading model.
2023-09-11T16:45:13.131-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.129969] [0x00008db2][0x00007fd8aac86840] [info] [kinesis_producer.cc:185] Using Kinesis endpoint localhost:4566
2023-09-11T16:45:13.131-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.130904] [0x00008db2][0x00007fd8aac86840] [info] [AWS Log: WARN](ClientConfiguration)Retry Strategy will use the default max attempts.
2023-09-11T16:45:13.131-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.130952] [0x00008db2][0x00007fd8aac86840] [info] [kinesis_producer.cc:111] Using Region: us-east-1
2023-09-11T16:45:13.131-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.130967] [0x00008db2][0x00007fd8aac86840] [info] [kinesis_producer.cc:134] Using per request threading model.
2023-09-11T16:45:13.132-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.130982] [0x00008db2][0x00007fd8aac86840] [info] [kinesis_producer.cc:200] Using CloudWatch endpoint localhost:4566
2023-09-11T16:45:13.133-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.133131] [0x00008db2][0x00007fd8aac86840] [info] [AWS Log: WARN](ClientConfiguration)Retry Strategy will use the default max attempts.
2023-09-11T16:45:13.133-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.133177] [0x00008db2][0x00007fd8aac86840] [info] [kinesis_producer.cc:111] Using Region: us-east-1
2023-09-11T16:45:13.134-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.133192] [0x00008db2][0x00007fd8aac86840] [info] [kinesis_producer.cc:134] Using per request threading model.
2023-09-11T16:45:13.134-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.133204] [0x00008db2][0x00007fd8aac86840] [info] [kinesis_producer.cc:215] Using STS endpoint localhost:4566
2023-09-11T16:45:13.134-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:13.134092] [0x00008db2][0x00007fd8aac86840] [info] [main.cc:394] Entering join
2023-09-11T16:45:13.742-04:00  INFO 36207 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2023-09-11T16:45:13.742-04:00  INFO 36207 --- [           main] o.s.i.channel.PublishSubscribeChannel    : Channel 'ScsKinesisProj1.errorChannel' has 1 subscriber(s).
2023-09-11T16:45:13.743-04:00  INFO 36207 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started bean '_org.springframework.integration.errorLogger'
2023-09-11T16:45:13.743-04:00  INFO 36207 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : Adding {router} as a subscriber to the 'mySupplier_integrationflow.channel#0' channel
2023-09-11T16:45:13.743-04:00  INFO 36207 --- [           main] o.s.integration.channel.DirectChannel    : Channel 'ScsKinesisProj1.mySupplier_integrationflow.channel#0' has 1 subscriber(s).
2023-09-11T16:45:13.743-04:00  INFO 36207 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started bean 'mySupplier_integrationflow.org.springframework.integration.config.ConsumerEndpointFactoryBean#0'
2023-09-11T16:45:13.745-04:00  INFO 36207 --- [           main] o.s.c.s.binder.DefaultBinderFactory      : Creating binder: kinesis
2023-09-11T16:45:13.745-04:00  INFO 36207 --- [           main] o.s.c.s.binder.DefaultBinderFactory      : Constructing binder child context for kinesis
2023-09-11T16:45:14.432-04:00  INFO 36207 --- [           main] o.s.c.s.binder.DefaultBinderFactory      : Caching the binder: kinesis
2023-09-11T16:45:14.443-04:00  INFO 36207 --- [           main] o.s.c.s.b.k.p.KinesisStreamProvisioner   : Using Kinesis stream for outbound: my-test-stream
2023-09-11T16:45:14.985-04:00  INFO 36207 --- [           main] o.s.c.s.b.k.p.KinesisStreamProvisioner   : Stream 'my-test-stream' not found. Create one...
2023-09-11T16:45:16.513-04:00  INFO 36207 --- [           main] c.a.s.kinesis.producer.KinesisProducer   : Extracting binaries to /tmp/amazon-kinesis-producer-native-binaries
2023-09-11T16:45:17.616-04:00  INFO 36207 --- [           main] c.a.s.kinesis.producer.HashedFileCopier  : '/tmp/amazon-kinesis-producer-native-binaries/kinesis_producer_D5ABD98FE80AEB7D01B0CA5245015A8257154BA3' already exists, and matches.  Not overwriting.
2023-09-11T16:45:17.642-04:00  INFO 36207 --- [           main] o.s.c.s.m.DirectWithAttributesChannel    : Channel 'ScsKinesisProj1.mySupplier-out-0' has 1 subscriber(s).
2023-09-11T16:45:17.646-04:00  INFO 36207 --- [           main] o.s.i.e.SourcePollingChannelAdapter      : started bean 'mySupplier-out-0_spca'
mySupplier creating payload 55
2023-09-11T16:45:17.660-04:00  INFO 36207 --- [           main] c.g.k.scs.ScsKinesisProj1Application     : Started ScsKinesisProj1Application in 8.019 seconds (process running for 8.503)
2023-09-11T16:45:17.661-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.661008] [0x00008de5][0x00007f0c7e66d840] [info] [logging.cc:89] Set boost log level to info
2023-09-11T16:45:17.661-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.661074] [0x00008de5][0x00007f0c7e66d840] [info] [logging.cc:179] Set AWS Log Level to INFO
2023-09-11T16:45:17.673-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.672809] [0x00008de5][0x00007f0c7e66d840] [info] [AWS Log: WARN](ClientConfiguration)Retry Strategy will use the default max attempts.
2023-09-11T16:45:17.674-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.674381] [0x00008de5][0x00007f0c7e66d840] [info] [main.cc:257] Region has been successfully set to us-east-1 from user's input configuration
2023-09-11T16:45:17.674-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.674603] [0x00008de5][0x00007f0c7e66d840] [info] [main.cc:348] Setting CA path to /tmp/amazon-kinesis-producer-native-binaries/cacerts
2023-09-11T16:45:17.675-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.674627] [0x00008de5][0x00007f0c7e66d840] [info] [main.cc:383] Starting up main producer
2023-09-11T16:45:17.675-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.674657] [0x00008de5][0x00007f0c7e66d840] [info] [AWS Log: WARN](ClientConfiguration)Retry Strategy will use the default max attempts.
2023-09-11T16:45:17.675-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.674676] [0x00008de5][0x00007f0c7e66d840] [info] [kinesis_producer.cc:111] Using Region: us-east-1
2023-09-11T16:45:17.675-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.674687] [0x00008de5][0x00007f0c7e66d840] [info] [kinesis_producer.cc:134] Using per request threading model.
2023-09-11T16:45:17.675-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.674697] [0x00008de5][0x00007f0c7e66d840] [info] [kinesis_producer.cc:62] Using default Kinesis endpoint
2023-09-11T16:45:17.675-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.675573] [0x00008de5][0x00007f0c7e66d840] [info] [AWS Log: WARN](ClientConfiguration)Retry Strategy will use the default max attempts.
2023-09-11T16:45:17.675-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.675608] [0x00008de5][0x00007f0c7e66d840] [info] [kinesis_producer.cc:111] Using Region: us-east-1
2023-09-11T16:45:17.676-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.675625] [0x00008de5][0x00007f0c7e66d840] [info] [kinesis_producer.cc:134] Using per request threading model.
2023-09-11T16:45:17.676-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.675635] [0x00008de5][0x00007f0c7e66d840] [info] [kinesis_producer.cc:62] Using default CloudWatch endpoint
2023-09-11T16:45:17.676-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.675998] [0x00008de5][0x00007f0c7e66d840] [info] [AWS Log: WARN](ClientConfiguration)Retry Strategy will use the default max attempts.
2023-09-11T16:45:17.676-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.676025] [0x00008de5][0x00007f0c7e66d840] [info] [kinesis_producer.cc:111] Using Region: us-east-1
2023-09-11T16:45:17.676-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.676036] [0x00008de5][0x00007f0c7e66d840] [info] [kinesis_producer.cc:134] Using per request threading model.
2023-09-11T16:45:17.676-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.676046] [0x00008de5][0x00007f0c7e66d840] [info] [kinesis_producer.cc:62] Using default STS endpoint
2023-09-11T16:45:17.676-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.676676] [0x00008de5][0x00007f0c7e66d840] [info] [main.cc:394] Entering join
2023-09-11T16:45:17.703-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.703457] [0x00008de5][0x00007f0c6e7fc6c0] [info] [kinesis_producer.cc:226] Created pipeline for stream "my-test-stream"
2023-09-11T16:45:17.828-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.828242] [0x00008de5][0x00007f0c6e7fc6c0] [info] [AWS Log: WARN](AWSErrorMarshaller)Encountered AWSError 'InvalidClientTokenId': The security token included in the request is invalid.
2023-09-11T16:45:17.829-04:00  WARN 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.828337] [0x00008de5][0x00007f0c6e7fc6c0] [warning] [AWS Log: ERROR](AWSXmlClient)HTTP response code: 403
Resolved remote host IP address: 52.119.199.66
Request ID: baf09e0a-46e2-49f8-a871-3a3af0b732a3
Exception name: InvalidClientTokenId
Error message: The security token included in the request is invalid.
4 response headers:
content-length : 306
content-type : text/xml
date : Mon, 11 Sep 2023 20:45:17 GMT
x-amzn-requestid : baf09e0a-46e2-49f8-a871-3a3af0b732a3
2023-09-11T16:45:17.830-04:00  INFO 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.828495] [0x00008de5][0x00007f0c6e7fc6c0] [info] [AWS Log: WARN](AWSClient)If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2023-09-11T16:45:17.830-04:00 ERROR 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : [2023-09-11 16:45:17.828613] [0x00008de5][0x00007f0c6e7fc6c0] [error] [pipeline.h:228] Failed to get StreamARN using STS GetCallerIdentity | Code: InvalidClientTokenId | Message: The security token included in the request is invalid. | Request was: Action=GetCallerIdentity&Version=2011-06-15
2023-09-11T16:45:17.831-04:00  WARN 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    : terminate called after throwing an instance of 'boost::wrapexcept<boost::exception_detail::error_info_injector<boost::log::v2s_mt_posix::system_error> >'
2023-09-11T16:45:17.831-04:00  WARN 36207 --- [kpl-daemon-0003] c.a.s.k.producer.LogInputStreamReader    :   what():  Failed to set TLS value: Invalid argument
mySupplier creating payload 127
2023-09-11T16:45:18.708-04:00 ERROR 36207 --- [   scheduling-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.integration.aws.outbound.KplMessageHandler@61545d9d], failedMessage=GenericMessage [payload=byte[3], headers={contentType=application/json, id=9033805c-4f94-7a8f-d978-c0539a1ae96a, timestamp=1694465118704}]
	at org.springframework.integration.support.utils.IntegrationUtils.wrapInHandlingExceptionIfNecessary(IntegrationUtils.java:191)
	at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:108)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:73)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$SendingHandler.handleMessageInternal(AbstractMessageChannelBinder.java:1185)
	at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:105)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:73)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.sendInternal(AbstractMessageChannel.java:373)
	at org.springframework.integration.channel.AbstractMessageChannel.sendWithMetrics(AbstractMessageChannel.java:344)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:324)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.router.AbstractMessageRouter.doSend(AbstractMessageRouter.java:217)
	at org.springframework.integration.router.AbstractMessageRouter.handleMessageInternal(AbstractMessageRouter.java:199)
	at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:105)
	at org.springframework.integration.handler.AbstractMessageHandler.handleWithMetrics(AbstractMessageHandler.java:90)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:70)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
	at org.springframework.integration.channel.AbstractMessageChannel.sendInternal(AbstractMessageChannel.java:373)
	at org.springframework.integration.channel.AbstractMessageChannel.sendWithMetrics(AbstractMessageChannel.java:344)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:324)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:297)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.SourcePollingChannelAdapter.handleMessage(SourcePollingChannelAdapter.java:196)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.messageReceived(AbstractPollingEndpoint.java:474)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:460)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:412)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$4(AbstractPollingEndpoint.java:348)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:57)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:55)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$5(AbstractPollingEndpoint.java:341)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:96)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.amazonaws.services.kinesis.producer.DaemonException: The child process has been shutdown and can no longer accept messages.
	at com.amazonaws.services.kinesis.producer.Daemon.add(Daemon.java:173)
	at com.amazonaws.services.kinesis.producer.KinesisProducer.flush(KinesisProducer.java:916)
	at com.amazonaws.services.kinesis.producer.KinesisProducer.flush(KinesisProducer.java:936)
	at org.springframework.integration.aws.outbound.KplMessageHandler.handleMessageToAws(KplMessageHandler.java:301)
	at org.springframework.integration.aws.outbound.AbstractAwsMessageHandler.handleMessageInternal(AbstractAwsMessageHandler.java:116)
	at org.springframework.integration.handler.AbstractMessageHandler.doHandleMessage(AbstractMessageHandler.java:105)
	... 49 more

2023-09-11T16:45:18.993-04:00 ERROR 36207 --- [kpl-daemon-0005] c.a.s.kinesis.producer.KinesisProducer   : Error in child process

java.lang.RuntimeException: EOF reached during read
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:532) ~[amazon-kinesis-producer-0.15.7.jar:na]
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:508) ~[amazon-kinesis-producer-0.15.7.jar:na]
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:504) ~[amazon-kinesis-producer-0.15.7.jar:na]
	at com.amazonaws.services.kinesis.producer.Daemon.readSome(Daemon.java:553) ~[amazon-kinesis-producer-0.15.7.jar:na]
	at com.amazonaws.services.kinesis.producer.Daemon.receiveMessage(Daemon.java:243) ~[amazon-kinesis-producer-0.15.7.jar:na]
	at com.amazonaws.services.kinesis.producer.Daemon.access$500(Daemon.java:61) ~[amazon-kinesis-producer-0.15.7.jar:na]
	at com.amazonaws.services.kinesis.producer.Daemon$3.run(Daemon.java:298) ~[amazon-kinesis-producer-0.15.7.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]


```

### Expected Behavior

Should produce messages into Kinesis localstack

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEFAULT_REGION=us-east-1
      - AWS_CBOR_DISABLE=true
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```

```
docker compose -f localstack-compose.yaml up
```
Clone project https://github.com/kothapet/ScsKinesisProj1

build project
```
mvn clean install
```
run the project
```
java -Dspring.profiles.active=local -jar target/ScsKinesisProj1-0.0.1-SNAPSHOT.jar
```

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: 3.8
- Java/JDK: 17
```

**Comment by kothapet** [comment]
Actually I figured it out. Instead of bean returning the KinesisProducer, return the KinesisProducerConfiguration.
Hopefully this helps someone in the future.

This works

```
	@Bean
	public KinesisProducerConfiguration kinesisProducerConfiguration() {
		System.out.println("**** KinesisProducerConfiguration ***");
		return new KinesisProducerConfiguration().setCredentialsProvider(getCredentialsProvider())
				.setKinesisEndpoint("localhost").setKinesisPort(4566)
				.setStsEndpoint("localhost").setStsPort(4566)
				.setCloudwatchEndpoint("localhost").setCloudwatchPort(4566)
				.setRegion(region).setVerifyCertificate(false);
	}
```
