### ISSUE TITLE
bug: Api-Gateway Get-Export Fails if given an api with resource with no methods defined

### ISSUE THREAD

**Issue by Fulgar** [localstack/localstack#9145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I create a REST API in API GW with any resources that do not contain any methods, and try to export the JSON schema, it fails due to:
```python
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/apigateway/helpers.py", line 1468, in _add_paths
    for method, method_config in item.get("resourceMethods").items():
AttributeError: 'NoneType' object has no attribute 'items'
```

Resource Structure:
/ - no methods defined
/{somethingId} - GET method defined

### Expected Behavior

I should be able to export an API that contains resources that do not contain any methods, just like in AWS.

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

I start localstack:
`localstack start`

I create some lambda that prints hello world:

lambda.js
```javascript
'use strict'

const apiHandler = (payload, context, callback) => {
    callback(null, {
        statusCode: 200,
        body: JSON.stringify({
            message: 'Hello from Lambda'
        }),
    }); 
}
    
module.exports = {
    apiHandler,
}

```

```bash
zip function.zip lambda.js
awslocal lambda create-function \
  --function-name apigw-lambda \
  --runtime nodejs16.x \
  --handler lambda.apiHandler \
  --memory-size 128 \
  --zip-file fileb://function.zip \
  --role arn:aws:iam::111111111111:role/apigw
```

I create the REST api:
```bash
awslocal apigateway create-rest-api --name 'API Gateway Lambda integration' --tags '{"_custom_id_": "test-api"}'
```

I get the root resource ID:
```bash
awslocal apigateway get-resources --rest-api-id test-api
```

Create a child resource:
```bash
awslocal apigateway create-resource \
  --rest-api-id test-api \
  --parent-id 4hvslaey04 \
  --path-part "{somethingId}"
```

Create method (ONLY FOR THE CHILD NODE):
```bash
awslocal apigateway put-method \
  --rest-api-id test-api \
  --resource-id oxykf16mty \
  --http-method GET \
  --request-parameters "method.request.path.somethingId=true" \
  --authorization-type "NONE"
```

Create Integration (ONLY FOR THE CHILD NODE):
```bash
awslocal apigateway put-integration \
  --rest-api-id test-api \
  --resource-id oxykf16mty \
  --http-method GET \
  --type AWS_PROXY \
  --integration-http-method POST \
  --uri arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:apigw-lambda/invocations \
  --passthrough-behavior WHEN_NO_MATCH
```

Create Deployment:
```bash
awslocal apigateway create-deployment \
  --rest-api-id test-api \
  --stage-name test
```

Try to export OpenAPI 3.0 Schema
```bash
awslocal apigateway get-export --parameters extensions='apigateway' --rest-api-id test-api --stage-name test --export-type oas30 oasTest.json --d
```

Gets the following in return:
```python
An error occurred (InternalError) when calling the GetExport operation (reached max retries: 4): exception while calling apigateway.GetExport: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 123, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/handlers/service.py", line 93, in __call__
    skeleton_response = self.skeleton.invoke(context)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 166, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/forwarder.py", line 60, in _call
    return handler(context, req)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/apigateway/provider.py", line 1765, in get_export
    result = openapi_exporter.export_api(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/apigateway/helpers.py", line 1462, in export_api
    return self.exporters.get(export_type)(api_id, stage, export_format)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/apigateway/helpers.py", line 1515, in _oas30_export
    self._add_paths(spec, resources)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack/services/apigateway/helpers.py", line 1468, in _add_paths
    for method, method_config in item.get("resourceMethods").items():
AttributeError: 'NoneType' object has no attribute 'items'
```

### Environment

```markdown
- OS: Both Windows 10 and MacOS Ventura 13.4.1(Intel CPU)
- LocalStack: latest
```

### Anything else?

I've tested this on Windows with "localstack start" script. And I have tested this on Mac with terraform docker_container. Same results.

**Comment by Fulgar** [comment]
@bentsku It's working now. Thanks for the quick fix!

**Comment by bentsku** [comment]
@Fulgar awesome, thanks for the quick feedback! Please note that we're still missing most API Gateway extensions for the `GetExport` operation, and we will work to implement them in the future. Feel free to open a new issue if you need some specific one from the following list: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html

We currently support `x-amazon-apigateway-integration`. 

Thanks!
