### ISSUE TITLE
bug: boto parameters are not fixed when nested

### ISSUE THREAD

**Issue by eXamadeus** [localstack/localstack#9164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to deploy through localstack using aws-cdk-local, I ran into an issue where the parameter validation logic was failing. The error I was seeing was:

```
 ❌ Deployment failed: Error: The stack named TestStack failed to deploy: CREATE_FAILED (Parameter validation failed:
Invalid type for parameter LaunchTemplate.Version, value: 1, type: <class 'int'>, valid types: <class 'str'>): Parameter validation failed:
Invalid type for parameter LaunchTemplate.Version, value: 1, type: <class 'int'>, valid types: <class 'str'>
    at FullCloudFormationDeployment.monitorDeployment (<projDir>/node_modules/aws-cdk/lib/index.js:443:10232)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (<projDir>/node_modules/aws-cdk/lib/index.js:446:153546)
    at async <projDir>/node_modules/aws-cdk/lib/index.js:446:136809
```

Basically, the parameters being sent are of the wrong type. This isn't an issue when using aws-cdk directly, as the actual deployment to AWS works fine. It is only happening in localstack.

By turning on `DEBUG` mode in localstack, I was able to see this issue in the logs:

```
localstack_main  | 2023-09-15T14:24:32.925 DEBUG --- [functhread86] l.s.c.resource_provider    : Converting parameters to allowed types
localstack_main  | 2023-09-15T14:24:32.925 DEBUG --- [functhread86] l.s.c.resource_provider    : Original parameters:  {'LaunchTemplate': {'LaunchTemplateId': 'lt-68a5be63ac0438a79', 'Version': 1}, 'MaxSize': 2, 'MinSize': 1, 'Tags': [{'Key': 'Name', 'PropagateAtLaunch': True, 'Value': 'TestStack/Cluster/ASGCapacity'}], 'VPCZoneIdentifier': 'subnet-0fb5a52e,subnet-18b570e2', 'AutoScalingGroupName': 'ClusterASGCapacityASGB1FEE0DD-c703f313', 'DefaultCooldown': 300}
localstack_main  | 2023-09-15T14:24:32.925 DEBUG --- [functhread86] l.s.c.resource_provider    : Converted parameters: {'LaunchTemplate': {'LaunchTemplateId': 'lt-68a5be63ac0438a79', 'Version': 1}, 'MaxSize': 2, 'MinSize': 1, 'Tags': [{'Key': 'Name', 'PropagateAtLaunch': True, 'Value': 'TestStack/Cluster/ASGCapacity'}], 'VPCZoneIdentifier': 'subnet-0fb5a52e,subnet-18b570e2', 'AutoScalingGroupName': 'ClusterASGCapacityASGB1FEE0DD-c703f313', 'DefaultCooldown': 300}
```

The `resource_provider` tries to convert the parameters to the proper type, but fails when the values are nested, in this case `params['LaunchTemplate']['Version']` which shows in the error message as `LaunchTemplate.Version`.

### Expected Behavior

I expect the [`fix_boto_parameters_based_on_report`](https://github.com/localstack/localstack/blob/858bbf28f04d8271bfe9ef97b5233f5f55e6dbe9/localstack/services/cloudformation/deployment_utils.py#L194-L213) function to properly coerce the types of nested parameter values.

### How are you starting LocalStack?

With a docker-compose file (pro setup)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```shell
docker compose up -f docker-compose.yml # using the pro image
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```ts
#!/usr/bin/env node
import 'source-map-support/register'
import * as cdk from 'aws-cdk-lib'
import { Stack, StackProps } from 'aws-cdk-lib'
import { Construct } from 'constructs'
import { InstanceClass, InstanceSize, InstanceType, Vpc } from 'aws-cdk-lib/aws-ec2'
import { Cluster } from 'aws-cdk-lib/aws-ecs'

const app = new cdk.App()
class TestStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props)

    // Create a simple VPC & security group
    const vpc = new Vpc(this, 'Vpc', { maxAzs: 2 })

    // Create an ECS Cluster
    const cluster = new Cluster(this, 'Cluster', { vpc })

    // Attach the capacity provider to the cluster
    cluster.addCapacity('ASGCapacity', {
      instanceType: InstanceType.of(InstanceClass.T2, InstanceSize.MICRO),
      minCapacity: 1,
      maxCapacity: 2,
    })
  }
}

new TestStack(app, 'TestStack', {})
```

### Environment

```markdown
- OS: macOS 13.5.2 (22G91)
- LocalStack: 2.2.0
```

### Anything else?

See #9165 for a PR with a fix.

**Comment by dominikschubert** [comment]
Fixed in https://github.com/localstack/localstack/pull/9165

Thanks again for the report and fix :+1:
