### ISSUE TITLE
bug: wrong behavior in step function when a lambda fails raising an exception without arguments

### ISSUE THREAD

**Issue by jairov4** [localstack/localstack#9169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In a Step function with a Lambda function that raises an exception without arguments the wrapper of the lambda function fails, then the Step function controller take 5 minutes to mark the execution as failed.

### Expected Behavior

The lambda funtion raise and exception, then step function fails fast and the error type is propagated correctly to Step Functions.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

# Create a simple lambda function

```python
def handler(event, context):
    raise ValueError()
```

Invoke it from a Step Function

### Environment

```markdown
- OS: Windows
- LocalStack: v2.0.0
```

### Anything else?

The execution log shows the failure point as:

```
2023-09-15T15:35:29.315  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS stepfunctions.DescribeExecution => 200
2023-09-15 10:35:30 2023-09-15T15:35:30.179  INFO --- [   asgi_gw_6] localstack.request.aws     : AWS lambda.GetFunction => 200
2023-09-15 10:35:30 Process Process-2:
2023-09-15 10:35:30 Traceback (most recent call last):
2023-09-15 10:35:30   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1423, in do_execute
2023-09-15 10:35:30     execute_result = lambda_function_callable(inv_context.event, context)
2023-09-15 10:35:30   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 796, in exec_local_python
2023-09-15 10:35:30     return inner_handler(event, context)
2023-09-15 10:35:30   File "/var/lib/localstack/tmp/lambda_script_l_730d619f.py", line 218, in workflow_handler
2023-09-15 10:35:30     return handler.handle(event, context)
2023-09-15 10:35:30   File "/tmp/function.zipfile.e4c1e650/cloudwiry_workflow/executors/aws_step_functions.py", line 860, in handle
2023-09-15 10:35:30     result = e.method(input_state)
2023-09-15 10:35:30   File "/tmp/function.zipfile.e4c1e650/cloudwiry_workflow/executors/aws_step_functions.py", line 766, in wrapper
2023-09-15 10:35:30     return xray_recorder.record_subsegment(
2023-09-15 10:35:30   File "/tmp/function.zipfile.e4c1e650/aws_xray_sdk/core/recorder.py", line 456, in record_subsegment
2023-09-15 10:35:30     return_value = wrapped(*args, **kwargs)
2023-09-15 10:35:30   File "/var/lib/localstack/tmp/lambda_script_l_730d619f.py", line 500, in step00_dummy
2023-09-15 10:35:30     raise ValueError()
2023-09-15 10:35:30 ValueError
2023-09-15 10:35:30 
2023-09-15 10:35:30 During handling of the above exception, another exception occurred:
2023-09-15 10:35:30 
2023-09-15 10:35:30 Traceback (most recent call last):
2023-09-15 10:35:30   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-09-15 10:35:30     self.run()
2023-09-15 10:35:30   File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-09-15 10:35:30     self._target(*self._args, **self._kwargs)
2023-09-15 10:35:30   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 1431, in do_execute
2023-09-15 10:35:30     "errorMessage": e.args[0],
2023-09-15 10:35:30 IndexError: tuple index out of range
2023-09-15 10:35:30 2023-09-15T15:35:30.358  INFO --- [   asgi_gw_8] localstack.request.aws     : AWS stepfunctions.DescribeExecution => 200
2023-09-15 10:35:31 2023-09-15T15:35:31.398  INFO --- [   asgi_gw_9] localstack
```

**Comment by dominikschubert** [comment]
Fixed in https://github.com/localstack/localstack/pull/9168

Thanks for tackling this :+1:
