### ISSUE TITLE
bug: error invoking lambdas in localstack tip (not present in 2.2.0)

### ISSUE THREAD

**Issue by brucekaufman** [localstack/localstack#9172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

running our integration test suite which is 100% passing in localstack version 2.2.0 fails almost 100% against localstack tip.  In the localstack logs I see the following errors - this repeats for nearly all of our lambda functions.

```2023-09-18 12:42:12 localstack  | 2023-09-18T16:42:12.511  INFO --- [uest_thread)] l.s.lambda_.lambda_api     : Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:communication-domain-local-phoneConfigCrud: unsupported operand type(s) for +=: 'VolumeMappings' and 'list' Traceback (most recent call last):
2023-09-18 12:42:12 localstack  |   File "/opt/code/localstack/localstack/services/lambda_/lambda_api.py", line 464, in run_lambda
2023-09-18 12:42:12 localstack  |     result = LAMBDA_EXECUTOR.execute(
2023-09-18 12:42:12 localstack  |   File "/opt/code/localstack/localstack/services/lambda_/lambda_executors.py", line 492, in execute
2023-09-18 12:42:12 localstack  |     return do_execute()
2023-09-18 12:42:12 localstack  |   File "/opt/code/localstack/localstack/services/lambda_/lambda_executors.py", line 482, in do_execute
2023-09-18 12:42:12 localstack  |     return _run(func_arn=func_arn)
2023-09-18 12:42:12 localstack  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 180, in wrapped
2023-09-18 12:42:12 localstack  |     raise e
2023-09-18 12:42:12 localstack  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 176, in wrapped
2023-09-18 12:42:12 localstack  |     result = func(*args, **kwargs)
2023-09-18 12:42:12 localstack  |   File "/opt/code/localstack/localstack/services/lambda_/lambda_executors.py", line 469, in _run
2023-09-18 12:42:12 localstack  |     raise e
2023-09-18 12:42:12 localstack  |   File "/opt/code/localstack/localstack/services/lambda_/lambda_executors.py", line 465, in _run
2023-09-18 12:42:12 localstack  |     result = self._execute(lambda_function, inv_context)
2023-09-18 12:42:12 localstack  |   File "/opt/code/localstack/localstack/services/lambda_/lambda_executors.py", line 788, in _execute
2023-09-18 12:42:12 localstack  |     result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
2023-09-18 12:42:12 localstack  |   File "/opt/code/localstack/localstack/services/lambda_/lambda_executors.py", line 665, in run_lambda_executor
2023-09-18 12:42:12 localstack  |     result, log_output = self.execute_in_container(
2023-09-18 12:42:12 localstack  |   File "/opt/code/localstack/localstack/services/lambda_/lambda_executors.py", line 1275, in execute_in_container
2023-09-18 12:42:12 localstack  |     container_config.volumes += container_config.required_files
2023-09-18 12:42:12 localstack  | TypeError: unsupported operand type(s) for +=: 'VolumeMappings' and 'list'
2023-09-18 12:42:12 localstack  | 
```

our localstack config:
```
version: "3.9"
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LOCALSTACK GLOBAL
      - SERVICES=lambda,s3,dynamodb,sns,sqs,ssm,apigateway,cloudformation,cloudwatch,sts,iam,events
      - ENFORCE_IAM=1
      - DEBUG=0
      # LAMBDA
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_DOCKER_FLAGS=-e NODE_OPTIONS=${LAMBDA_DEBUG_CONFIG} ${DEBUG_PORTS} ${TIMEOUT}
      - LAMBDA_IGNORE_ARCHITECTURE=1
      - PROVIDER_OVERRIDE_LAMBDA=legacy
      # SQS
      - SQS_DISABLE_CLOUDWATCH_METRICS=1
      # CREDENTIALS
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=us-east-1
      # SERVICE SPECIFIC
      - TWILIO_SID=${TWILIO_SID}
      - TWILIO_TOKEN=${TWILIO_TOKEN}
      - TWILIO_TEST_SID=${TWILIO_TEST_SID}
      - TWILIO_TEST_TOKEN=${TWILIO_TEST_TOKEN}
      - TUNNEL_URL=${TUNNEL_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - '${PWD}/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh'
```

### Expected Behavior

our test suite should pass 100%, since with zero changes to the implementation it passes with `[local/stack](image: localstack/localstack:2.2.0)`

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

i haven't attempted to reproduce this outside of our integration test suite

**Comment by brucekaufman** [comment]
just to update on this, I was able to get our integration test suite passing with release `2.3.0` and the new lambda provider.  So from my perspective this bug is not critical to fix.

**Comment by joe4dev** [comment]
Hi @brucekaufman
We are excited to hear everything is working with the latest LocalStack 2.3 release and the new Lambda provider 🚀 

I suggest closing this issue because it only affects the legacy Lambda provider, which we plan to remove with LocalStack 3.0. Please let us know if you experience any issues with the new Lambda provider 👂
