### ISSUE TITLE
bug: crash when assigning tags to some ec2

### ISSUE THREAD

**Issue by RaJiska** [localstack/localstack#9195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
awslocal ec2 create-vpc --cidr-block 10.0.0.0/16
awslocal ec2 create-subnet --vpc-id "$VPC_ID" --cidr-block 10.0.20.0/20 --tag-specifications '{"Tags":[{"Key":"Name","Value":"ok"},{"Key":"Hello","Value":"World"}]}'
```

Output (through docker compose, latest version):
```
An error occurred (InternalError) when calling the CreateSubnet operation (reached max retries: 2): exception while calling ec2.CreateSubnet: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 123, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 93, in __call__
    skeleton_response = self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 166, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/forwarder.py", line 60, in _call
    return handler(context, req)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/aws/api/core.py", line 167, in operation_marker
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/ec2/provider.py", line 280, in create_subnet
    response = call_moto(context)
  File "/opt/code/localstack/localstack/services/moto.py", line 47, in call_moto
    return dispatch_to_backend(context, dispatch_to_moto, include_response_metadata)
  File "/opt/code/localstack/localstack/aws/forwarder.py", line 120, in dispatch_to_backend
    http_response = http_request_dispatcher(context)
  File "/opt/code/localstack/localstack/services/moto.py", line 115, in dispatch_to_moto
    response = dispatch(request, request.url, request.headers)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/responses.py", line 231, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/responses.py", line 375, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/responses.py", line 464, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/ec2/responses/subnets.py", line 18, in create_subnet
    tags = tags[0].get('Tags')
AttributeError: 'list' object has no attribute 'get'
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal ec2 create-vpc --cidr-block 10.0.0.0/16
    awslocal ec2 create-subnet --vpc-id "$VPC_ID" --cidr-block 10.0.20.0/20 --tag-specifications '{"Tags":[{"Key":"Name","Value":"ok"},{"Key":"Hello","Value":"World"}]}'

### Environment

```markdown
- OS:
- LocalStack:
```

### Anything else?

The issue seems to be coming from `moto` library. I opened a PR that fixes the issue https://github.com/getmoto/moto/pull/6839

**Comment by pinzon** [comment]
The Pr that adds the validation for the input has been merged. Soon it will be available in LocalStack. Thank you for reporting the problem.
