### ISSUE TITLE
Unable to start Localstack on windows 

### ISSUE THREAD

**Issue by ss207210** [localstack/localstack#922]
While starting the command  "py localstack -d start" getting below error : 
Starting local dev environment. CTRL-C to quit.
Starting mock ES service (http port 4578)...
Starting local Elasticsearch (http port 4571)...
'ES_JAVA_OPTS' is not recognized as an internal or external command,

operable program or batch file.

Starting mock S3 (http port 4572)...
'VALIDATE_LAMBDA_S3' is not recognized as an internal or external command,

operable program or batch file.

Starting mock SNS (http port 4575)...
Starting mock SQS (http port 4576)...
'VALIDATE_LAMBDA_S3' is not recognized as an internal or external command,

operable program or batch file.

12:31:38.594 [main] INFO  org.elasticmq.server.Main$ - Starting ElasticMQ server (0.13.10) ...

12:31:39.396 [elasticmq-akka.actor.default-dispatcher-2] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started

12:31:40.711 [elasticmq-akka.actor.default-dispatcher-2] ERROR akka.io.TcpListener - Bind failed for TCP channel on endpoint [/0.0.0.0:4561]

java.net.BindException: Address already in use: bind

at sun.nio.ch.Net.bind0(Native Method)

at sun.nio.ch.Net.bind(Unknown Source)

at sun.nio.ch.Net.bind(Unknown Source)

at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)

at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)

at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:56)

at akka.io.TcpListener.<init>(TcpListener.scala:53)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

at java.lang.reflect.Constructor.newInstance(Unknown Source)

at akka.util.Reflect$.instantiate(Reflect.scala:65)

at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)

at akka.actor.Props.newActor(Props.scala:213)

at akka.actor.ActorCell.newActor(ActorCell.scala:626)

at akka.actor.ActorCell.create(ActorCell.scala:652)

at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:525)

at akka.actor.ActorCell.systemInvoke(ActorCell.scala:547)

at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)

at akka.dispatch.Mailbox.run(Mailbox.scala:223)

at akka.dispatch.Mailbox.exec(Mailbox.scala:234)

at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)

at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)

at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)

at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

12:31:40.711 [elasticmq-akka.actor.default-dispatcher-5] ERROR o.e.rest.sqs.TheSQSRestServerBuilder - Cannot start SQS rest server, bind address 0.0.0.0:4561

akka.stream.impl.io.ConnectionSourceStage$$anon$2$$anon$1: Bind failed because of Address already in use: bind

Caused by: java.net.BindException: Address already in use: bind

at sun.nio.ch.Net.bind0(Native Method)

at sun.nio.ch.Net.bind(Unknown Source)

at sun.nio.ch.Net.bind(Unknown Source)

at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)

at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)

at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:56)

at akka.io.TcpListener.<init>(TcpListener.scala:53)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

at java.lang.reflect.Constructor.newInstance(Unknown Source)

at akka.util.Reflect$.instantiate(Reflect.scala:65)

at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)

at akka.actor.Props.newActor(Props.scala:213)

at akka.actor.ActorCell.newActor(ActorCell.scala:626)

at akka.actor.ActorCell.create(ActorCell.scala:652)

at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:525)

at akka.actor.ActorCell.systemInvoke(ActorCell.scala:547)

at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)

at akka.dispatch.Mailbox.run(Mailbox.scala:223)

at akka.dispatch.Mailbox.exec(Mailbox.scala:234)

at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)

at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)

at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)

at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

12:31:40.710 [main] ERROR org.elasticmq.server.Main$ - Uncaught exception in thread: main

akka.stream.impl.io.ConnectionSourceStage$$anon$2$$anon$1: Bind failed because of Address already in use: bind

Caused by: java.net.BindException: Address already in use: bind

at sun.nio.ch.Net.bind0(Native Method)

at sun.nio.ch.Net.bind(Unknown Source)

at sun.nio.ch.Net.bind(Unknown Source)

at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)

at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)

at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:56)

at akka.io.TcpListener.<init>(TcpListener.scala:53)

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

at java.lang.reflect.Constructor.newInstance(Unknown Source)

at akka.util.Reflect$.instantiate(Reflect.scala:65)

at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)

at akka.actor.Props.newActor(Props.scala:213)

at akka.actor.ActorCell.newActor(ActorCell.scala:626)

at akka.actor.ActorCell.create(ActorCell.scala:652)

at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:525)

at akka.actor.ActorCell.systemInvoke(ActorCell.scala:547)

at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)

at akka.dispatch.Mailbox.run(Mailbox.scala:223)

at akka.dispatch.Mailbox.exec(Mailbox.scala:234)

at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)

at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)

at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)

at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

---------------------------------------------------------------------------------
When I tried to access the S3 service from browser I got additional error mentioned below 

2018-09-07T08:07:54:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03BA6C10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)) Traceback (most recent call last):
  File "c:\python36-32\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "c:\python36-32\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "c:\python36-32\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36-32\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "c:\python36-32\lib\site-packages\urllib3\connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\python36-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "c:\python36-32\lib\http\client.py", line 964, in send
    self.connect()
  File "c:\python36-32\lib\site-packages\urllib3\connection.py", line 166, in connect
    conn = self._new_conn()
  File "c:\python36-32\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x03BA6C10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36-32\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "c:\python36-32\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\python36-32\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03BA6C10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36-32\lib\site-packages\localstack\services\generic_proxy.py", line 201, in forward
    headers=forward_headers)
  File "c:\python36-32\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "c:\python36-32\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\python36-32\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python36-32\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "c:\python36-32\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03BA6C10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

**Comment by whummer** [comment]
Installation should work now under Windows (see also changes in #1631). Closing this issue - please re-open if the problem persists. Thanks
