### ISSUE TITLE
Serverless CloudFormation templates using AWS::Partition fail

### ISSUE THREAD

**Issue by justinm** [localstack/localstack#925]
CloudFormation templates generated with Serverless fail due to a KeyError being thrown in moto, `KeyError: 'AWS::Partition'`. I've submitted an issue and PR upstream with moto here https://github.com/spulec/moto/issues/1816. This issue is to track bringing this fix into LocalStack.

For an example of the CloudFormation template that's failing, see: https://gist.github.com/justinm/91a315ec604fc7c6c33ff89f7ce7fff8

**Comment by daviskoh** [comment]
Seems the moto fix has been merged. Should the moto version for localstack be updated now or are there other dependencies?

**Comment by mosesyu** [comment]
With [moto 1.3.7](https://pypi.org/project/moto/1.3.7/), I get the error from test.

```
======================================================================
FAIL: tests.integration.test_integration.test_kinesis_lambda_sns_ddb_sqs_streams
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/code/localstack/tests/integration/test_integration.py", line 267, in test_kinesis_lambda_sns_ddb_sqs_streams
    stats1 = get_lambda_metrics(TEST_LAMBDA_NAME_STREAM)
  File "/opt/code/localstack/tests/integration/test_integration.py", line 322, in get_lambda_metrics
    Statistics=['Sum']
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 71, in get_metric_statistics
    assert all_metrics.status_code == 200
AssertionError: 
-------------------- >> begin captured logging << --------------------
KCL: CRITICAL: Nov 22, 2018 12:08:49 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShutdownTask call
KCL: CRITICAL: SEVERE: Caught exception: 
KCL: WARNING: Nov 22, 2018 12:08:58 PM com.amazonaws.http.AmazonHttpClient createSocketFactoryRegistry
KCL: WARNING: WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
KCL: WARNING: Nov 22, 2018 12:08:58 PM com.amazonaws.http.AmazonHttpClient createSocketFactoryRegistry
KCL: WARNING: WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
KCL: WARNING: Nov 22, 2018 12:08:58 PM com.amazonaws.http.AmazonHttpClient createSocketFactoryRegistry
KCL: WARNING: WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
KCL: WARNING: Nov 22, 2018 12:08:58 PM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker build
KCL: WARNING: WARNING: Received configuration for both region name as us-east-1, and Amazon Kinesis endpoint as http://a6ffa37ca5e9:4568. Amazon Kinesis endpoint will overwrite region name.
localstack.services.awslambda.lambda_api: WARNING: Function already exist: test_lambda_ddb
localstack.services.awslambda.lambda_api: WARNING: Error executing Lambda function: Test exception (this is intentional) Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 301, in run_lambda
    event, context=context, version=version, asynchronous=asynchronous)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 466, in execute
    process.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 462, in do_execute
    result = lambda_function(event, context)
  File "/tmp/localstack/lambda_script_l_d944862c.py", line 59, in handler
    raise Exception('Test exception (this is intentional)')
Exception: Test exception (this is intentional)

--------------------- >> end captured logging << ---------------------

```

**Comment by whummer** [comment]
Thanks for reporting @justinm @daviskoh @mosesyu . This should be fixed in the latest version. An integration test has been added in #2283 to cover this functionality. Please let us know if the problem persists. Thanks
