### ISSUE TITLE
Error on localstack setup in github actions - LocalStack/setup-localstack@v0.1.2

### ISSUE THREAD

**Issue by stephe92** [localstack/localstack#9253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

yml file configured as - 
```
name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.1.2
        with:
          image-tag: 'latest'
          install-awslocal: 'true'
```

Github action job failing with following error

```
error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in __init__
          req = REQUIREMENT.parseString(requirement_string)
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
          raise exc
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
          loc, tokens = self._parse( instring, 0 )
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
          loc,tokens = self.parseImpl( instring, preloc, doActions )
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
          loc, exprtokens = e._parse( instring, loc, doActions )
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
          loc,tokens = self.parseImpl( instring, preloc, doActions )
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3205, in parseImpl
          raise ParseException(instring, loc, self.errmsg, self)
      pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 16), (line:1, col:17)
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 4, in <module>
          setup()
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in _install_setup_requires
          dist.parse_config_files(ignore_option_errors=True)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 807, in parse_config_files
          self._finalize_requires()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 533, in _finalize_requires
          self._convert_extras_requirements()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 547, in _convert_extras_requirements
          for r in pkg_resources.parse_requirements(v):
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line [309](https://github.com/goSprinto/sprinto/actions/runs/6342783695/job/17229787576#step:11:311)9, in parse_requirements
          yield Requirement(line)
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line [310](https://github.com/goSprinto/sprinto/actions/runs/6342783695/job/17229787576#step:11:312)9, in __init__
          super(Requirement, self).__init__(requirement_string)
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 104, in __init__
          raise InvalidRequirement(
      pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "','": Expected stringEnd
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

start localstack by adding as a job in github actions which uses
LocalStack/setup-localstack@v0.1.2

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by ningziwen** [comment]
+1
We started to run into this error without change. https://github.com/aws/shim-loggers-for-containerd/actions/runs/6345755890/job/17238266367

**Comment by dfangl** [comment]
Hi @stephe92 @ningziwen !
We think we have identified the root cause of this, and will publish a post release soon. Thank you for bringing it to our attention!

**Comment by dfangl** [comment]
Version 2.3.1 was just released, which should fix this issue. Thank you for reporting it!
