### ISSUE TITLE
AttributeError: module 'httpcore' has no attribute 'NetworkBackend'

### ISSUE THREAD

**Issue by agn-7** [localstack/localstack#9266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just installed `localstack` via `pip` and got the following error during `localstack` commands:

`localstack start -d`

Out:
```
Traceback (most recent call last):
  File "/home/benyamin/.local/bin/localstack", line 23, in <module>
    main()
  File "/home/benyamin/.local/bin/localstack", line 19, in main
    main.main()
  File "/home/benyamin/.local/lib/python3.10/site-packages/localstack/cli/main.py", line 14, in main
    from .localstack import create_with_plugins
  File "/home/benyamin/.local/lib/python3.10/site-packages/localstack/cli/localstack.py", line 12, in <module>
    from localstack.utils.analytics.cli import publish_invocation
  File "/home/benyamin/.local/lib/python3.10/site-packages/localstack/utils/analytics/__init__.py", line 1, in <module>
    from .logger import EventLogger
  File "/home/benyamin/.local/lib/python3.10/site-packages/localstack/utils/analytics/logger.py", line 7, in <module>
    from .metadata import get_session_id
  File "/home/benyamin/.local/lib/python3.10/site-packages/localstack/utils/analytics/metadata.py", line 9, in <module>
    from localstack.utils.bootstrap import Container
  File "/home/benyamin/.local/lib/python3.10/site-packages/localstack/utils/bootstrap.py", line 18, in <module>
    from localstack.utils.container_networking import get_main_container_name
  File "/home/benyamin/.local/lib/python3.10/site-packages/localstack/utils/container_networking.py", line 9, in <module>
    from localstack.utils.docker_utils import DOCKER_CLIENT
  File "/home/benyamin/.local/lib/python3.10/site-packages/localstack/utils/docker_utils.py", line 15, in <module>
    from localstack.utils.net import IntOrPort, Port, PortNotAvailableException, PortRange
  File "/home/benyamin/.local/lib/python3.10/site-packages/localstack/utils/net.py", line 10, in <module>
    import dns.resolver
  File "/home/benyamin/.local/lib/python3.10/site-packages/dns/resolver.py", line 30, in <module>
    import dns._ddr
  File "/home/benyamin/.local/lib/python3.10/site-packages/dns/_ddr.py", line 12, in <module>
    import dns.nameserver
  File "/home/benyamin/.local/lib/python3.10/site-packages/dns/nameserver.py", line 5, in <module>
    import dns.asyncquery
  File "/home/benyamin/.local/lib/python3.10/site-packages/dns/asyncquery.py", line 38, in <module>
    from dns.query import (
  File "/home/benyamin/.local/lib/python3.10/site-packages/dns/query.py", line 67, in <module>
    _CoreNetworkBackend = httpcore.NetworkBackend
AttributeError: module 'httpcore' has no attribute 'NetworkBackend'
```

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: latest
- Python: 3.10
```

**Comment by agn-7** [comment]
I fixed the issue by updating the packages `httpx` and `httpcore` respectively. 
The problem was related to a package named `googletrans` that needed a specific version of `httpx` and it also needed a specific version of `httpcore`!
Therefore, I updated the `httpx` first then updated the `httpcore` to latest version but I lost the `googltrans` package.

```
pip install httpx -U
pipi install httpcpre -U
```

```
pip show httpcore
pip show httpcore
Name: httpcore
Version: 0.18.0
Summary: A minimal low-level HTTP client.
Home-page: 
Author: 
Author-email: Tom Christie <tom@tomchristie.com>
License: 
Location: /home/benyamin/.local/lib/python3.10/site-packages
Requires: anyio, certifi, h11, sniffio
Required-by: httpx
```

__The `httpcore` version before was 0.9.0__
