### ISSUE TITLE
bug: cdk deploy to localstack fails when 5th lambda is added to the stack 

### ISSUE THREAD

**Issue by VoVaVc** [localstack/localstack#9291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to deploy an AWS CDK project to LocalStack, the project contains 3 RestApi lambdas and one authorizer lambda. Once I add the 4th lambda to the stack, the deploy process breaks saying the CoudFormation template can't be downloaded from the s3 bucket because it doesn't exist. The bucket name equals the name I provide to the stack with lambdas.

```
portals-localstack-1  | 2023-10-04T15:42:44.939  INFO --- [   asgi_gw_5] localstack.request.aws     : AWS s3.GetObject => 404 (NoSuchBucket)
portals-localstack-1  | 2023-10-04T15:42:44.940 DEBUG --- [   asgi_gw_1] l.s.c.api_utils            : Download CloudFormation template content from local S3: cdk - api-stack-local/822c3610cfb039dedd358b9a2793cebf625e15281cd06469141d067a37eb87bb.yml
portals-localstack-1  | 2023-10-04T15:42:44.953  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.ListBuckets => 200
portals-localstack-1  | 2023-10-04T15:42:45.016 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain
portals-localstack-1  | Traceback (most recent call last):
portals-localstack-1  |   File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
portals-localstack-1  |     handler(self, self.context, response)
portals-localstack-1  |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 123, in __call__
portals-localstack-1  |     handler(chain, context, response)
portals-localstack-1  |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 93, in __call__
portals-localstack-1  |     skeleton_response = self.skeleton.invoke(context)
portals-localstack-1  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
portals-localstack-1  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 154, in invoke
portals-localstack-1  |     return self.dispatch_request(context, instance)
portals-localstack-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
portals-localstack-1  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 166, in dispatch_request
portals-localstack-1  |     result = handler(context, instance) or {}
portals-localstack-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
portals-localstack-1  |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 118, in __call__
portals-localstack-1  |     return self.fn(*args, **kwargs)
portals-localstack-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^
portals-localstack-1  |   File "/opt/code/localstack/localstack/aws/api/core.py", line 160, in operation_marker
portals-localstack-1  |     return fn(*args, **kwargs)
portals-localstack-1  |            ^^^^^^^^^^^^^^^^^^^
portals-localstack-1  |   File "/opt/code/localstack/localstack/services/cloudformation/provider.py", line 509, in create_change_set
portals-localstack-1  |     api_utils.prepare_template_body(
portals-localstack-1  |   File "/opt/code/localstack/localstack/services/cloudformation/api_utils.py", line 24, in prepare_template_body
portals-localstack-1  |     modified_template_body = get_template_body(req_data)
portals-localstack-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
portals-localstack-1  |   File "/opt/code/localstack/localstack/services/cloudformation/api_utils.py", line 55, in get_template_body
portals-localstack-1  |     result = client.get_object(Bucket=parts[0], Key=parts[2])
portals-localstack-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
portals-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
portals-localstack-1  |     return self._make_api_call(operation_name, kwargs)
portals-localstack-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
portals-localstack-1  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 980, in _make_api_call
portals-localstack-1  |     raise error_class(parsed_response, operation_name)
portals-localstack-1  | botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the GetObject operation: The specified bucket does not exist
portals-localstack-1  | 2023-10-04T15:42:45.019  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.CreateChangeSet => 500 (InternalError)
```

### Expected Behavior

Deploy process shouldn't fail, all lambdas should be settled to the LocalStack.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

`docker-compose.yml`

```
version: "3.9"

services:
  localstack:
    image: localstack/localstack:latest
    restart: on-failure
    environment:
      DATA_DIR: /tmp/localstack/data
      DEBUG: 1
      DOCKER_HOST: unix:///var/run/docker.sock
      LOCALSTACK_SERVICES: s3,lambda,sqs
      LOCALSTACK_DEFAULT_REGION: us-west-1
      EXTRA_CORS_ALLOWED_ORIGINS: http://localhost:3000
      DISABLE_CORS_CHECKS: 1
      DISABLE_CUSTOM_CORS_S3: 1
    ports:
      - "4566:4566"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

command: `docker compose up`

### Environment

```markdown
- OS: Ubuntu 22.04.3
- LocalStack: 2.3.2
```

**Comment by simonrw** [comment]
Thanks @VoVaVc for reporting. Do you have an minimal example CDK stack that we can use to reproduce the issue?

**Comment by VoVaVc** [comment]
@simonrw sure! Here is the [repo representing an issue](https://github.com/VoVaVc/localstack-lambda-bug-reproduction)

**Comment by simonrw** [comment]
Thanks @VoVaVc for the reproduction case, it replicates the problem perfectly.

From my initial exploration I think this is due to the cloudformation template becoming too big for an embedded `create_changeset` call, and it's getting uploaded to S3 but we cannot find the template in S3. I have not gotten any further yet.

**Comment by simonrw** [comment]
Possibly related: https://github.com/localstack/localstack/pull/9329
