### ISSUE TITLE
bug: CloudFormation Conditions not working with !Select 

### ISSUE THREAD

**Issue by Chad-Bailer** [localstack/localstack#9300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cloudformation templates are failing in Conditions that use `!Select` function within the `!Equals`. 

```
Error: Failed to create changeset for the stack: select-test, An error occurred (InternalError) when calling the CreateChangeSet operation (reached max retries: 4): exception while calling cloudformation.CreateChangeSet: Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 123, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 93, in __call__
    skeleton_response = self.skeleton.invoke(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(context, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 166, in dispatch_request
    result = handler(context, instance) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/api/core.py", line 160, in operation_marker
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/provider.py", line 602, in create_change_set
    resolved_stack_conditions = resolve_stack_conditions(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_utils.py", line 109, in resolve_stack_conditions
    result[condition_name] = resolve_condition(
                             ^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_utils.py", line 231, in resolve_condition
    left = resolve_condition(
           ^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_utils.py", line 347, in resolve_condition
    raise Exception(f"Invalid condition structure encountered: {condition=}")
Exception: Invalid condition structure encountered: condition={'Fn::Select': [1, ['apples', 'grapes', 'bananas']]}
```

### Expected Behavior

We should be able to utilize the !Select function within conditions in order to have feature parity with native cloudformation

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

 awslocal cloudformation deploy \
    --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
    --stack-name chad-select-conditional \
    --template-file infra/templates/templatetesting.yaml

Here's a super basic example file. What we are trying to do is a bit more complicated than this, but this highlights the bug.       
#####  templatetesting.yaml:
```
AWSTemplateFormatVersion: '2010-09-09'
  
Conditions:
  IsGrapes: !Equals [!Select [ 1, ['apples', 'grapes', 'bananas']], 'grapes']  

Resources:
  StreamWriterPolicy2:
    Type: 'AWS::IAM::ManagedPolicy'
    Condition: IsGrapes
    Properties:
      ManagedPolicyName: Test2
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: "kinesis:PutRecord"
            Resource: !Join
              - ':'
              - - arn:aws:kinesis
                - !Ref AWS::Region
                - !Ref AWS::AccountId
                - !Sub stream/${AWS::StackName}-*
```

### Environment

```markdown
- OS: OSX
- LocalStack: latest localstack-pro
```

### Anything else?

This does work when not in a Condition. For an example the following resource works when there is no Condition.
```
  StreamWriterPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName:  !Select [ 1, ['apples', 'grapes', 'bananas']]
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          # Can write to the stream
          - Effect: Allow
            Action: "kinesis:PutRecord"
            Resource: !Join
              - ':'
              - - arn:aws:kinesis
                - !Ref AWS::Region
                - !Ref AWS::AccountId
                - !Sub stream/${AWS::StackName}-*
```

**Comment by dominikschubert** [comment]
Fixed in https://github.com/localstack/localstack/pull/9311
