### ISSUE TITLE
Dockerfile no longer builds

### ISSUE THREAD

**Issue by danonorato** [localstack/localstack#931]
STRs.
1) Attempt a docker build. 
``` docker build -t localstack/localstack:latest .```
2) Notice the following error
```  Cache entry deserialization failed, entry ignored
Command "/opt/code/localstack/.venv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-QAOpFo/pycryptodome/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-azVSeM-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/code/localstack/.venv/include/site/python2.7/pycryptodome" failed with error code 1 in /tmp/pip-build-QAOpFo/pycryptodome/
Traceback (most recent call last):
  File "localstack/services/install.py", line 9, in <module>
    from localstack.constants import (DEFAULT_SERVICE_PORTS, ELASTICMQ_JAR_URL, STS_JAR_URL,
  File "/opt/code/localstack/localstack/constants.py", line 2, in <module>
    import localstack_client.config
ImportError: No module named localstack_client.config
make: *** [Makefile:14: install] Error 1
The command '/bin/sh -c make install' returned a non-zero code: 2```

**Comment by adriangalera** [comment]
Same here, I had to add the following lines before RUN make install:
```
# Delete me!
RUN pip install localstack-client
RUN apk update
RUN apk add build-base
```
Additionally the tests were not working either, so I had to comment them out:
```
# run tests (to verify the build before pushing the image)
#ADD tests/ tests/
#RUN make test
```

**Comment by mattvaughan** [comment]
This is still an issue, but the changes from @adriangalera worked for me. What's strange is that I was able to build it fine yesterday. Then I did a `docker system prune --all --force`, `git clean -fd` and `git clean -fXd` and all of the sudden i got the error @danonorato posted.

**Comment by adriangalera** [comment]
Same as @mattvaughan.
I needed to modify the fix:
```
# Delete me!
RUN apk update
RUN apk add build-base python-dev libressl-dev linux-headers
RUN pip install localstack-client
RUN pip install -r requirements.txt
```

**Comment by whummer** [comment]
Thanks for reporting. This error is usually related to changes in the python dependencies (`requirements.txt`).

As a workaround, running `make docker-build-base` and then `make docker-build` should fix this issue.
