### ISSUE TITLE
DynamoDBLocal throws exception after persisting for a minute or so

### ISSUE THREAD

**Issue by nterry** [localstack/localstack#934]
Specifically, I am using the kinesis client library (which uses Dynamo for its shard leasing). After leasing and renewing for a small time, localstack starts to spit out the following repeatedly:

```
WARN  com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler - DynamoDBLocalServiceException exception occured
com.amazonaws.services.dynamodbv2.exceptions.DynamoDBLocalServiceException: The conditional request failed
at com.amazonaws.services.dynamodbv2.exceptions.AWSExceptionFactory.buildAWSException(AWSExceptionFactory.java:55) ~[DynamoDBLocal.jar:?]
at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBClient$11.criticalSection(LocalDynamoDBClient.java:1663) ~[DynamoDBLocal.jar:?]
at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDBAccess$WriteLockWithTimeout.execute(LocalDBAccess.java:356) ~[DynamoDBLocal.jar:?]
at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBClient.updateItem(LocalDynamoDBClient.java:1713) ~[DynamoDBLocal.jar:?]
at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.updateItem(LocalDynamoDBRequestHandler.java:369) ~[DynamoDBLocal.jar:?]
at com.amazonaws.services.dynamodbv2.local.dispatchers.UpdateItemDispatcher.enact(UpdateItemDispatcher.java:18) ~[DynamoDBLocal.jar:?]
at com.amazonaws.services.dynamodbv2.local.dispatchers.UpdateItemDispatcher.enact(UpdateItemDispatcher.java:12) ~[DynamoDBLocal.jar:?]
at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.packageDynamoDBResponse(LocalDynamoDBServerHandler.java:364) [DynamoDBLocal.jar:?]
at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.handle(LocalDynamoDBServerHandler.java:451) [DynamoDBLocal.jar:?]
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1024) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.Server.handle(Server.java:370) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) [jetty-http-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668) [jetty-io-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) [jetty-io-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.12.v20130726.jar:8.1.12.v20130726]
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.12.v20130726.jar:8.1.12.v20130726]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]Dynam
```

This started in the latest version. 0.8.7 never exhibited this behaviour

**Comment by nakedcity** [comment]
Any update on this one?

**Comment by whummer** [comment]
@nakedcity @nterry Are you (still) experiencing this issue? Haven't seen many user requests around this issue - do you think you could share a small sample project to reproduce this? Thanks

**Comment by anekar3416** [comment]
@whummer I am seeing this error very frequently. 
I have started Localstack DynamoDB and Kinesis services. My application is trying to capture the DynamoDB changes via Kinesis Client Library from the Kinesis Streams. I am frequently getting this error:

`localstack.services.dynamodb.server: com.amazonaws.services.dynamodbv2.exceptions.DynamoDBLocalServiceException: The conditional request failed`

**Comment by macsj200** [comment]
I have also been seeing this error lately. I updated our project to use `localstack/localstack:1.0.1`.
