### ISSUE TITLE
bug: Api Gateway V2 HTTP API with Cognito Authorizer not working

### ISSUE THREAD

**Issue by vt-rcheng** [localstack/localstack#9353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to test api gateway http api with Cognito authorizer.

I have configured my apigateway

```
root@0602af4d9b80:/opt/code/localstack# awslocal apigatewayv2 get-apis
{
    "Items": [
        {
            "ApiEndpoint": "apigw_http_id.execute-api.localhost.localstack.cloud:4566",
            "ApiId": "apigw_http_id",
            "DisableExecuteApiEndpoint": true,
            "Name": "awaken-dev-http-api",
            "ProtocolType": "HTTP",
            "RouteSelectionExpression": "${request.method} ${request.path}",
            "Tags": {
                "_custom_id_": "apigw_http_id"
            }
        }
    ]
}


root@0602af4d9b80:/opt/code/localstack# awslocal apigatewayv2 get-authorizers --api-id apigw_http_id
{
    "Items": [
        {
            "AuthorizerId": "da7037dd",
            "AuthorizerPayloadFormatVersion": "2.0",
            "AuthorizerResultTtlInSeconds": 3600,
            "AuthorizerType": "JWT",
            "EnableSimpleResponses": false,
            "IdentitySource": [
                "route.request.header.Authorization"
            ],
            "JwtConfiguration": {
                "Audience": [
                    "h5un41lp8nqva2p5wu3cc8gupk"
                ],
                "Issuer": "127.0.0.1:4566"
            },
            "Name": "http-auth"
        }
    ]
}

{
    "Items": [
        {
            "IntegrationId": "17ceada1",
            "IntegrationMethod": "ANY",
            "IntegrationType": "AWS_PROXY",
            "IntegrationUri": "arn:aws:lambda:us-east-1:000000000000:function:awaken-localstack-lambda-router",
            "PayloadFormatVersion": "2.0",
            "TimeoutInMillis": 30000
        }
    ]
}


root@0602af4d9b80:/opt/code/localstack# awslocal apigatewayv2 get-routes --api-id apigw_http_id
{
    "Items": [
        {
            "AuthorizerId": "da7037dd",
            "RouteId": "fd709cc1",
            "RouteKey": "$default",
            "Target": "integrations/17ceada1"
        }
    ]
}

```

when I try to make a request to the apigateway I get the following error...
It complains about invalid REST API id, but I am using HTTP API.....

```
awaken-cloud-container-localstack  | 2023-10-16T04:49:24.700 DEBUG --- [   asgi_gw_1] l.s.apigateway.authorizers : Authorization failed: An error occurred (NotFoundException) when calling the GetResources operation: Invalid Rest API Id specified - Traceback (most recent call last):
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 339, in is_request_authorized
awaken-cloud-container-localstack  |     try:AuthorizerService().check_request_authorization(invocation_context)
awaken-cloud-container-localstack  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/authorizers.py.enc", line 315, in check_request_authorization
awaken-cloud-container-localstack  |     try:I=get_target_resource_method_or_route(A)
awaken-cloud-container-localstack  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/apigateway/apigateway_utils.py.enc", line 227, in get_target_resource_method_or_route
awaken-cloud-container-localstack  |     if(B:=get_target_resource_method(A)):return B
awaken-cloud-container-localstack  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/apigateway/helpers.py", line 1366, in get_target_resource_method
awaken-cloud-container-localstack  |     _, resource = get_target_resource_details(invocation_context)
awaken-cloud-container-localstack  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/apigateway/helpers.py", line 1337, in get_target_resource_details
awaken-cloud-container-localstack  |     path_map = get_rest_api_paths(
awaken-cloud-container-localstack  |                ^^^^^^^^^^^^^^^^^^^
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/apigateway/helpers.py", line 679, in get_rest_api_paths
awaken-cloud-container-localstack  |     resources = apigateway.get_resources(restApiId=rest_api_id, limit=100)
awaken-cloud-container-localstack  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
awaken-cloud-container-localstack  |     return self._make_api_call(operation_name, kwargs)
awaken-cloud-container-localstack  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 980, in _make_api_call
awaken-cloud-container-localstack  |     raise error_class(parsed_response, operation_name)
awaken-cloud-container-localstack  | botocore.errorfactory.NotFoundException: An error occurred (NotFoundException) when calling the GetResources operation: Invalid Rest API Id specified
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by bentsku** [comment]
Hi @vt-rcheng and thanks for your report!

I believe the issue could be avoided if you choose a different api id, I believe with custom tags? I believe the `_` character is not allowed (it's not allowed in host normally, it violates RFC 1123, and it will lead to issue when trying to access some resources. Could you try it with `apigw-http-id` instead of `apigw_http_id` and see if that fixes your issue?

We will add validation when setting the custom ID so that this issue wouldn't appear.

**Comment by vt-rcheng** [comment]
thanks for the reply. you suggestion did get me further, but now I am getting the following issue.

I do have routekey $default added, which is suppose to be a wildcard path, but it is not being recognized.


```

awaken-cloud-container-localstack  | 2023-10-16T22:58:38.333 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
awaken-cloud-container-localstack  | Traceback (most recent call last):
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/protocol/parser.py", line 558, in parse
awaken-cloud-container-localstack  |     operation, uri_params = self._operation_router.match(request)
awaken-cloud-container-localstack  |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/protocol/op_router.py", line 321, in match
awaken-cloud-container-localstack  |     rule, args = matcher.match(path, method=method, return_rule=True)
awaken-cloud-container-localstack  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match
awaken-cloud-container-localstack  |     raise NotFound() from None
awaken-cloud-container-localstack  | werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
awaken-cloud-container-localstack  | 
awaken-cloud-container-localstack  | The above exception was the direct cause of the following exception:
awaken-cloud-container-localstack  | 
awaken-cloud-container-localstack  | Traceback (most recent call last):
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/chain.py", line 90, in handle
awaken-cloud-container-localstack  |     handler(self, self.context, response)
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 64, in __call__
awaken-cloud-container-localstack  |     return self.parse_and_enrich(context)
awaken-cloud-container-localstack  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 77, in parse_and_enrich
awaken-cloud-container-localstack  |     operation, instance = parser.parse(context.request)
awaken-cloud-container-localstack  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/protocol/parser.py", line 173, in wrapper
awaken-cloud-container-localstack  |     return func(*args, **kwargs)
awaken-cloud-container-localstack  |            ^^^^^^^^^^^^^^^^^^^^^
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/protocol/parser.py", line 560, in parse
awaken-cloud-container-localstack  |     raise OperationNotFoundParserError(
awaken-cloud-container-localstack  | localstack.aws.protocol.parser.OperationNotFoundParserError: Unable to find operation for request to service apigateway: GET /test
awaken-cloud-container-localstack  | 2023-10-16T22:58:38.337  INFO --- [   asgi_gw_0] localstack.request.http    : GET /test => 500
awaken-cloud-container-localstack  | 2023-10-16T23:00:01.677 ERROR --- [   asgi_gw_4] l.aws.handlers.logging     : exception during call chain
awaken-cloud-container-localstack  | Traceback (most recent call last):
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/protocol/parser.py", line 558, in parse
awaken-cloud-container-localstack  |     operation, uri_params = self._operation_router.match(request)
awaken-cloud-container-localstack  |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/protocol/op_router.py", line 321, in match
awaken-cloud-container-localstack  |     rule, args = matcher.match(path, method=method, return_rule=True)
awaken-cloud-container-localstack  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match
awaken-cloud-container-localstack  |     raise NotFound() from None
awaken-cloud-container-localstack  | werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**Comment by vt-rcheng** [comment]
my expected result for this

`curl apigw-http-id.execute-api.localhost.localstack.cloud:4566/test`

is an unauthorized request response as I did not pass in my cognito access token

**Comment by bentsku** [comment]
Thanks for your response! After checking again, it seems `-` might be an issue as well. I'll work on adding validation for the custom id tags, as it seems it complicates things quite a bit.

You could try something like `apigwhttpid` and see if that solves the second issue?

**Comment by vt-rcheng** [comment]
yes I can confirm that fixed the problem. thank you

**Comment by vt-rcheng** [comment]
but Cognito Authorizer doesn't seem to be working. I didn't pass in jwt token, the request still went through....


awaken-cloud-container-localstack  | 2023-10-17T10:37:38.833 DEBUG --- [   asgi_gw_0] l.s.apigateway.authorizers : Processing API V2 invocation

**Comment by calvernaz** [comment]
Hi @vt-rcheng, I'll look into this and come back with to you 👍

**Comment by calvernaz** [comment]
Hi @vt-rcheng the identitySource should be,

```
"IdentitySource": [
                "$request.header.Authorization"
],
```

https://docs.aws.amazon.com/apigatewayv2/latest/api-reference/apis-apiid-authorizers.html

I'm also pushing a fix to handle cases when the token is not present and throws the correct error

**Comment by vt-rcheng** [comment]
hmmm if I change the IdentitySource, I get


```
awaken-cloud-container-localstack  | Traceback (most recent call last):
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/runtime/init.py", line 136, in run_stage
awaken-cloud-container-localstack  |     runner.run(script.path)
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/runtime/init.py", line 81, in run
awaken-cloud-container-localstack  |     exec(fd.read(), {})
awaken-cloud-container-localstack  |   File "<string>", line 246, in <module>
awaken-cloud-container-localstack  |   File "<string>", line 181, in create_websocket_api
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
awaken-cloud-container-localstack  |     return self._make_api_call(operation_name, kwargs)
awaken-cloud-container-localstack  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
awaken-cloud-container-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 983, in _make_api_call
awaken-cloud-container-localstack  |     raise error_class(parsed_response, operation_name)
awaken-cloud-container-localstack  | botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the CreateAuthorizer operation: Invalid request identity source expression: $request.header.Authorization. The sources must be separated by comma, and each source must be either a request parameter, matching 'route.request.querystring|header.[a-zA-Z0-9._-]+', or a stage variable, matching 'stageVariables.[a-zA-Z0-9._-]+', or a context parameter, matching 'context.[a-zA-Z0-9._-]+'
```


what the error message states differs from the aws docs.

**Comment by vt-rcheng** [comment]
@calvernaz any update on this?

**Comment by calvernaz** [comment]
Hi @vt-rcheng, after my post, I haven't look into this. Will try again and see what's going on

**Comment by calvernaz** [comment]
Hi @vt-rcheng, still not getting any error, so I would recommend checking if you have the latest version and have checked the complete example https://github.com/localstack/localstack-terraform-samples/tree/master/apigatewayv2-http-cognito-authorizer.

`awslocal apigatewayv2 get-authorizers --api-id e50ab79a`

```
{
    "Items": [
        {
            "AuthorizerId": "8d5cdc81",
            "AuthorizerPayloadFormatVersion": "2.0",
            "AuthorizerType": "JWT",
            "IdentitySource": [
                "$request.header.Authorization"
            ],
            "JwtConfiguration": {
                "Audience": [
                    "audience"
                ],
                "Issuer": "https://issuer"
            },
            "Name": "bursting-hawk"
        }
    ]
}
```

and 

`awslocal apigatewayv2 get-routes --api-id e50ab79a`

```
{
    "Items": [
        {
            "ApiKeyRequired": false,
            "AuthorizationType": "JWT",
            "AuthorizerId": "8d5cdc81",
            "RouteId": "61e68005",
            "RouteKey": "$default",
            "Target": "integrations/9c9384a2"
        }
    ]
}
```
