### ISSUE TITLE
bug: Unable to startup DB instance(Waiter DBClusterAvailable failed: Max attempts exceeded)

### ISSUE THREAD

**Issue by rishabhAjay** [localstack/localstack#9392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get the following error while trying to create a DocumentDB cluster on localstack(pro) via CDK:

<img width="849" alt="image" src="https://github.com/localstack/localstack/assets/63163183/1b36a3ea-7170-4178-9216-591eea31671a">

Logs generated in the docker container:

```
Unable to startup DB instance:  Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.43/images/sha256:a054a71d2bebd4c5cbffa0b9fedc753c65461223845eed070a080307f26ebaab/json
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/container_utils/docker_sdk_client.py", line 330, in get_docker_image_names
    images = self.client().images.list()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/models/images.py", line 383, in list
    return [self.get(r["Id"]) for r in resp]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/models/images.py", line 383, in <listcomp>
    return [self.get(r["Id"]) for r in resp]
            ^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/models/images.py", line 335, in get
    return self.prepare_model(self.client.api.inspect_image(name))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/api/image.py", line 251, in inspect_image
    return self._result(
           ^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.43/images/sha256:a054a71d2bebd4c5cbffa0b9fedc753c65461223845eed070a080307f26ebaab/json: Internal Server Error ("readlink /var/lib/docker/overlay2: invalid argument")
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/rds/db_utils.py.enc", line 63, in B
    try:A and A(status='creating');G=E.start_db_instance(*D,**F);A and A(status=_D);LOG.debug('DB started successfully.');return G
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/docdb/docdb_api.py.enc", line 20, in start_db_instance
    def start_db_instance(E,req_data,region_name=None):A=req_data;install_doc_db();B=get_db_port_cache_key(A);C=A['Port'];D=start_server(C);DB_STATE_CACHE[B]=D
                                                                  ^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/docdb/docdb_api.py.enc", line 23, in install_doc_db
    if MONGO_DOCKER_IMAGE not in DOCKER_CLIENT.get_docker_image_names():DOCKER_CLIENT.pull_image(MONGO_DOCKER_IMAGE)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/container_utils/docker_sdk_client.py", line 340, in get_docker_image_names
    raise ContainerException() from e
localstack.utils.container_utils.container_client.ContainerException
 stdout: 'None' stderr: 'None'
2023-10-18T17:48:11.388 DEBUG --- [uncthread187] l.s.c.resource_provider    : Executing callback method for AWS::DocDB::DBCluster:primarydbcluster65E4ACBD
2023-10-18T17:48:14.222  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:48:14.242  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:48:19.241  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:48:19.255  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:48:24.276  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:48:24.279  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:48:29.313  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:48:29.315  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:48:34.350  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:48:34.352  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:48:39.378  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:48:39.380  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:48:44.418  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:48:44.422  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:48:49.461  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:48:49.464  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:48:54.490  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:48:54.494  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:48:59.521  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:48:59.525  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:49:04.554  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:49:04.558  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:49:09.582  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:49:09.584  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:49:14.615  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:49:14.618  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:49:19.649  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:49:19.650  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:49:24.674  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:49:24.677  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:49:29.707  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:49:29.708  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:49:34.741  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:49:34.743  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:49:39.773  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:49:39.774  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:49:44.790  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:49:44.791  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:49:49.812  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:49:49.813  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:49:54.833  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:49:54.834  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:49:59.856  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:49:59.857  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:50:04.885  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:50:04.888  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:50:09.924  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
2023-10-18T17:50:09.926  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
2023-10-18T17:50:11.675 DEBUG --- [uncthread187] l.s.c.e.template_deployer  : Error applying changes for CloudFormation stack "database-stack": Waiter DBClusterAvailable failed: Max attempts exceeded Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1171, in _run
    self.do_apply_changes_in_loop(changes, stack)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1245, in do_apply_changes_in_loop
    self.apply_change(change, stack=stack)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1360, in apply_change
    progress_event = executor.deploy_loop(resource_provider_payload)  # noqa
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/resource_provider.py", line 647, in deploy_loop
    event = self.execute_action(resource_provider, payload)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/resource_provider.py", line 716, in execute_action
    return resource_provider.create(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/resource_provider.py", line 397, in create
    return self.create_or_delete(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/resource_provider.py", line 566, in create_or_delete
    result_handler(
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/cloudformation/models/rds.py.enc", line 103, in C
    def C(account_id,region_name,result,logical_resource_id,resource):C='DBCluster';B=result;A=resource;F=A[_A][_F];connect_to(aws_access_key_id=account_id,region_name=region_name).rds.get_waiter(waiter_name='db_cluster_available').wait(DBClusterIdentifier=F);D=B[C][_Q];E=D.split(':')[0];G=B[C].get(_T)or D.split(':')[-1];A[_A][_W]=B[C][_W];A[_A][_Q]=B[C][_Q];A[_A]['Endpoint.Address']=E;A[_A][_s]=G;A[_A]['ReadEndpoint.Address']=E;A[_H]=A[_A][_F]
                                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/waiter.py", line 55, in wait
    Waiter.wait(self, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/patch.py", line 38, in proxy
    return new(target, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/connect.py", line 59, in my_patch
    return fn(self, **patched_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/waiter.py", line 388, in wait
    raise WaiterError(
botocore.exceptions.WaiterError: Waiter DBClusterAvailable failed: Max attempts exceeded
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    through the docker compose yml(pro version)

#### Client commands

1. I have made a repository to reproduce the bug. Please find it [here](https://github.com/rishabhAjay/docdb-bug).
2. ran `set AWS_PROFILE=localstack`
3. In the directory of the project, ran `cdklocal bootstrap`
4. Finally, `cdklocal deploy --all`

### Environment

```markdown
- OS: Windows 10
- LocalStack: 2.3.2
```

**Comment by rishabhAjay** [comment]
Is there a possibility of this issue being resolved at your earliest convenience? Would be really helpful for me and my team to get things up.

**Comment by rishabhAjay** [comment]
Was able to resolve it by running: `docker images --digests` and deleting the image that was throwing the error(log search string: `requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: ....`) with `docker rmi <image_id>`. I suppose this was because the said image had gone corrupt.

**Comment by steffyP** [comment]
Hi @rishabhAjay, 
could you let us know if your issue was resolved?

**Comment by rishabhAjay** [comment]
@steffyP Yeah. The issue has been resolved. Thank you
