### ISSUE TITLE
bug: Lambda cannot connect to OpenSearch domain

### ISSUE THREAD

**Issue by trinm12** [localstack/localstack#9397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi all,

While trying to use OpenSearch inside Lambda function, I got the connection error like this

```
ERROR   Unhandled Promise Rejection     {"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"ConnectionError: connect ECONNREFUSED ::1:4566","reason":{"errorType":"ConnectionError","errorMessage":"connect ECONNREFUSED ::1:4566","name":"ConnectionError","meta":{"body":null,"statusCode":null,"headers":null,"meta":{"context":null,"request":{"params":{"method":"PUT","path":"/offers/_doc/619dd09b-4290-4e49-9b46-e07c801ddbf5","body":"{\"trackingUrl\":\"https://api.staging.pokitpal.com/v1/affiliate/b704852a-6e43-49bc-97a0-2bc6c4c50d6f/919653/1549678\",\"offerDetails\":null,\"advertiserAboutUs\":null,\"about\":\"We’re one of Australia’s leading online prescription eyewear stores, and we’re proud to boast an extensive range of quality products, together with the expert, experienced staff to match you up with a custom optical solution.\",\"description\":\"If you’re looking for sleek and stylish designer glasses or sunglasses to upgrade any look, then you won’t be disappointed with what’s on offer at 1001 Optical. \\n\\nShop big names such as Ray-Ban, Prada, Tom Ford, Oakley, Gucci and many more. \",\"isAGiftCard\":false,\"title\":\"6% Cashback on All Purchases\",\"ratingScore\":4,\"termsAndConditions\":\"To be eligible for Cashback you must access the partner site through the button / link provided. No Cashback on Gift Card Purchases.\\n\",\"createdAt\":\"2023-10-18T19:17:05.407Z\",\"giftCardId\":null,\"logo\":\"https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/Logos/advertiser-0d277746-39d1-48e2-8f7b-144ab894ee80.jpg\",\"promoCode\":null,\"id\":\"619dd09b-4290-4e49-9b46-e07c801ddbf5\",\"isFavourite\":false,\"ctaDetails\":null,\"offerUseTypeId\":1,\"updatedAt\":\"2023-10-18T19:17:05.407Z\",\"advertiser\":\"1001 Optical\",\"howItWorks\":\"To receive Cashback on your purchases, click the button provided to access the retailer’s  confirming the Cashback amount due. If you have not received a notification within 5 days from the date of your online purchase, please let us know. Depending on the retailer’s returns policy, it may take up to 90 days for the Cashback to be settled and deposited in your personal Wallet.\\n\",\"campaignId\":null,\"externalAdvertiserId\":null,\"storeDomain\":null,\"coverArt\":\"https://pokitpal-images.s3-ap-southeast-2.amazonaws.com/stage/UploadFiles/CoverShot/advertiser-9f553d7f-d517-4268-a09e-8d6b7fa5521d.jpg\",\"url\":null,\"cashback\":\"6%\",\"searchTag\":\"1001 optical glasses specatcles sunglasses sunnies\",\"offerUseType\":\"multi\",\"createdDate\":null,\"offerKind\":null,\"isCardLinkedOffer\":false,\"externalOfferId\":null,\"category\":\"Food & Drink\",\"categoryId\":1}","querystring":"refresh=true","headers":{"user-agent":"opensearch-js/2.4.0 (linux 6.5.5-200.fc38.aarch64-x64; Node.js v18.18.0)","content-type":"application/json","content-length":"2225"},"timeout":30000},"options":{},"id":1},"name":"opensearch-js","connection":{"url":"http://ebenefits.ap-southeast-2.opensearch.localhost.localstack.cloud:4566/","id":"http://ebenefits.ap-southeast-2.opensearch.localhost.localstack.cloud:4566/","headers":{},"deadCount":1312,"resurrectTimeout":1697660089628,"_openRequests":436,"status":"dead","roles":{"data":true,"ingest":true}},"attempts":3,"aborted":false}},"stack":["ConnectionError: connect ECONNREFUSED ::1:4566","    at ClientRequest.onError (/var/task/node_modules/@opensearch-project/opensearch/lib/Connection.js:129:16)","    at ClientRequest.emit (node:events:517:28)","    at Socket.socketErrorListener (node:_http_client:501:9)","    at Socket.emit (node:events:517:28)","    at emitErrorNT (node:internal/streams/destroy:151:8)","    at emitErrorCloseNT (node:internal/streams/destroy:116:3)","    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: ConnectionError: connect ECONNREFUSED ::1:4566","    at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)","    at process.emit (node:events:517:28)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
```

The domain that I used is `http://ebenefits.ap-southeast-2.opensearch.localhost.localstack.cloud:4566`

I'm currently running the localstack image inside Podman. Here is the run command
```
podman run \
      --detach --tty --rm \
      --privileged \
      --publish $PORT:4566/tcp \
      --name $localstack_name \
      --volume /var/run/docker.sock:/var/run/docker.sock \
      --env SERVICES=dynamodb,events,lambda \
      --env DEFAULT_REGION=ap-southeast-2 \
      localstack/localstack:latest
```

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
```
podman run \
      --detach --tty --rm \
      --privileged \
      --publish $PORT:4566/tcp \
      --name $localstack_name \
      --volume /var/run/docker.sock:/var/run/docker.sock \
      --env SERVICES=dynamodb,events,lambda \
      --env DEFAULT_REGION=ap-southeast-2 \
      localstack/localstack:latest
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
OpenSearch:
`awslocal opensearch create-domain --domain-name ebenefits --region ap-southeast-2`

Lambda
```
const asset = new TerraformAsset(scope, 'lambda-asset', {
    path: path.resolve(__dirname, '../../../lambda/indexData'),
    type: AssetType.ARCHIVE,
  });
new LambdaFunction(scope, 'UserTableIndexingFunction', {
    functionName: 'UserTableIndexingFunction',
    filename: asset.path,
    handler: 'build/index.handler',
    runtime: 'nodejs18.x',
    role: role.arn,
    timeout: 30,
    // layers: [layer.arn],
  });
```

### Environment

```markdown
- OS: macOS Ventura 13.4.1
- LocalStack:latest
```

**Comment by simonrw** [comment]
Hi @trinm12, thanks for reporting this issue.

It looks like you have IPv6 enabled in your podman configuration. The domain name `ebenefits.ap-southeast-2.opensearch.localhost.localstack.cloud` is resolving to `::1` which is localhost in IPv6. LocalStack does not support IPv6 at this time. Can you try disabling it, and try again?
