### ISSUE TITLE
bug: Scheduling secret rotation causes 500 error

### ISSUE THREAD

**Issue by cowlingj** [localstack/localstack#9485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Setting up secret rotation using the AWS CLI returns a 500 error and fails to setup rotation.

### Expected Behavior

Secret rotation to be setup successfully.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: "localstack"
    restart: on-failure:10
    privileged: true
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${DOCKER_HOST}:/var/run/docker.sock"
 ```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
aws --endpoint http://localhost:4566 secretsmanager create-secret --name test-secret --description "LocalStack Secret" --secret-string "localstack"
aws --endpoint http://localhost:4566 lambda create-function --function-name rotcli --runtime nodejs18.x --zip-file fileb://./terraform/test/.functions/rotation.zip --handler index.handler --role arn:aws:iam::000000000000:role/service-role/rotation-lambda-role
aws --endpoint http://localhost:4566 secretsmanager rotate-secret --secret-id test-secret --rotation-lambda-arn arn:aws:lambda:eu-west-1:000000000000:function:rotcli --rotation-rules "{\"ScheduleExpression\": \"rate(4 hours)\", \"Duration\": \"2h\"}"
```

### Environment

```markdown
- OS: Manjaro (`uname -r` 6.1.55-1-MANJARO)
- LocalStack: latest
- Docker: podman version 4.7.1
- Docker Compose: podman-compose version 1.0.6
- AWS CLI: 2.13.28 (aws-cli/2.13.28 Python/3.11.6 Linux/6.1.55-1-MANJARO exe/x86_64.manjaro.23 prompt/off)
```

### Anything else?

I'm largely following the guide in the [docs](https://docs.localstack.cloud/user-guide/aws/secretsmanager/) with my own nodejs rotation lambda (I've managed to invoke the lambda via the AWS CLI without issue, but it looks like localstack doesn't get as far as invoking the lambda).

Stacktrace:
```
[localstack] | 2023-10-26T21:03:39.627 ERROR --- [   asgi_gw_2] l.aws.handlers.logging     : exception during call chain
[localstack] | Traceback (most recent call last):
[localstack] |   File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
[localstack] |     handler(self, self.context, response)
[localstack] |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 123, in __call__
[localstack] |     handler(chain, context, response)
[localstack] |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 93, in __call__
[localstack] |     skeleton_response = self.skeleton.invoke(context)
[localstack] |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 154, in invoke
[localstack] |     return self.dispatch_request(context, instance)
[localstack] |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 166, in dispatch_request
[localstack] |     result = handler(context, instance) or {}
[localstack] |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/aws/forwarder.py", line 135, in _call
[localstack] |     return handler(context, req)
[localstack] |            ^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 118, in __call__
[localstack] |     return self.fn(*args, **kwargs)
[localstack] |            ^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/aws/api/core.py", line 160, in operation_marker
[localstack] |     return fn(*args, **kwargs)
[localstack] |            ^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/services/secretsmanager/provider.py", line 243, in rotate_secret
[localstack] |     return call_moto(context, request)
[localstack] |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/services/moto.py", line 48, in call_moto
[localstack] |     return dispatch_to_backend(context, dispatch_to_moto, include_response_metadata)
[localstack] |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/aws/forwarder.py", line 183, in dispatch_to_backend
[localstack] |     http_response = http_request_dispatcher(context)
[localstack] |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/services/moto.py", line 119, in dispatch_to_moto
[localstack] |     response = dispatch(request, raw_url, request.headers)
[localstack] |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/core/responses.py", line 245, in dispatch
[localstack] |     return cls()._dispatch(*args, **kwargs)
[localstack] |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/core/responses.py", line 441, in _dispatch
[localstack] |     return self.call_action()
[localstack] |            ^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/core/responses.py", line 534, in call_action
[localstack] |     response = method()
[localstack] |                ^^^^^^^^
[localstack] |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/secretsmanager/responses.py", line 118, in rotate_secret
[localstack] |     return self.backend.rotate_secret(
[localstack] |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
[localstack] |     return new(target, *args, **kwargs)
[localstack] |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/services/secretsmanager/provider.py", line 614, in backend_rotate_secret
[localstack] |     rotation_func.invoke(
[localstack] |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/awslambda/models.py", line 1013, in invoke
[localstack] |     res, errored, logs = self._invoke_lambda(event=body)
[localstack] |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/awslambda/models.py", line 897, in _invoke_lambda
[localstack] |     with _DockerDataVolumeContext(
[localstack] |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/awslambda/models.py", line 145, in __enter__
[localstack] |     with zip2tar(self._lambda_func.code_bytes) as stream:
[localstack] |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/awslambda/models.py", line 71, in zip2tar
[localstack] |     with zipfile.ZipFile(io.BytesIO(zip_bytes), "r") as zipf:
[localstack] |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/usr/local/lib/python3.11/zipfile.py", line 1302, in __init__
[localstack] |     self._RealGetContents()
[localstack] |   File "/usr/local/lib/python3.11/zipfile.py", line 1369, in _RealGetContents
[localstack] |     raise BadZipFile("File is not a zip file")
[localstack] | zipfile.BadZipFile: File is not a zip file
[localstack] | 2023-10-26T21:03:39.632  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS secretsmanager.RotateSecret => 500 (InternalError)
[localstack] | 2023-10-26T21:03:54.398 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
[localstack] | Traceback (most recent call last):
[localstack] |   File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
[localstack] |     handler(self, self.context, response)
[localstack] |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 123, in __call__
[localstack] |     handler(chain, context, response)
[localstack] |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 93, in __call__
[localstack] |     skeleton_response = self.skeleton.invoke(context)
[localstack] |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 154, in invoke
[localstack] |     return self.dispatch_request(context, instance)
[localstack] |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 166, in dispatch_request
[localstack] |     result = handler(context, instance) or {}
[localstack] |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/aws/forwarder.py", line 135, in _call
[localstack] |     return handler(context, req)
[localstack] |            ^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/aws/skeleton.py", line 118, in __call__
[localstack] |     return self.fn(*args, **kwargs)
[localstack] |            ^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/aws/api/core.py", line 160, in operation_marker
[localstack] |     return fn(*args, **kwargs)
[localstack] |            ^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/services/secretsmanager/provider.py", line 243, in rotate_secret
[localstack] |     return call_moto(context, request)
[localstack] |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/services/moto.py", line 48, in call_moto
[localstack] |     return dispatch_to_backend(context, dispatch_to_moto, include_response_metadata)
[localstack] |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/aws/forwarder.py", line 183, in dispatch_to_backend
[localstack] |     http_response = http_request_dispatcher(context)
[localstack] |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/services/moto.py", line 119, in dispatch_to_moto
[localstack] |     response = dispatch(request, raw_url, request.headers)
[localstack] |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/core/responses.py", line 245, in dispatch
[localstack] |     return cls()._dispatch(*args, **kwargs)
[localstack] |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/core/responses.py", line 441, in _dispatch
[localstack] |     return self.call_action()
[localstack] |            ^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/core/responses.py", line 534, in call_action
[localstack] |     response = method()
[localstack] |                ^^^^^^^^
[localstack] |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/secretsmanager/responses.py", line 118, in rotate_secret
[localstack] |     return self.backend.rotate_secret(
[localstack] |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
[localstack] |     return new(target, *args, **kwargs)
[localstack] |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/localstack/services/secretsmanager/provider.py", line 614, in backend_rotate_secret
[localstack] |     rotation_func.invoke(
[localstack] |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/awslambda/models.py", line 1013, in invoke
[localstack] |     res, errored, logs = self._invoke_lambda(event=body)
[localstack] |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/awslambda/models.py", line 897, in _invoke_lambda
[localstack] |     with _DockerDataVolumeContext(
[localstack] |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/awslambda/models.py", line 145, in __enter__
[localstack] |     with zip2tar(self._lambda_func.code_bytes) as stream:
[localstack] |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/awslambda/models.py", line 71, in zip2tar
[localstack] |     with zipfile.ZipFile(io.BytesIO(zip_bytes), "r") as zipf:
[localstack] |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[localstack] |   File "/usr/local/lib/python3.11/zipfile.py", line 1302, in __init__
[localstack] |     self._RealGetContents()
[localstack] |   File "/usr/local/lib/python3.11/zipfile.py", line 1369, in _RealGetContents
[localstack] |     raise BadZipFile("File is not a zip file")
[localstack] | zipfile.BadZipFile: File is not a zip file
[localstack] | 2023-10-26T21:03:54.403  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS secretsmanager.RotateSecret => 500 (InternalError)
```

I've seen the issue #5279, but it looks like the underlying problem is unrelated.

**Comment by cowlingj** [comment]
I've retried with the new latest docker image just to see if things are any different and with the exception of a couple lines of the stack trace being shifted down 5 lines (/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/core/responses.py 441->446, 534 -> 539) the issue and logs are the same (the v3 release issue didn't suggest this will be affected, but thought I'd give it a shot anyway)

**Comment by cockscomb** [comment]
I also encountered the same error. After trying multiple versions, it seems to occur in LocalStack 2.0 and later.

Upon examining the code a bit, it appears that the following section is related.

https://github.com/localstack/localstack/blob/86c9642b03de69e1b8c2f190af45609014ae6ccf/localstack/services/secretsmanager/provider.py#L555

https://github.com/getmoto/moto/blob/4e1ea0bb6f983451b6ae1525594e5a5af5254cc7/moto/awslambda/models.py#L771
https://github.com/getmoto/moto/blob/4e1ea0bb6f983451b6ae1525594e5a5af5254cc7/moto/awslambda/models.py#L144
