### ISSUE TITLE
bug: Unable to startup DB instance, password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by Nikola-Milovic** [localstack/localstack#9499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to deploy an RDS instance with CDK and Localstack, if I add custom credentials to the CDK, similarly [to the examples](https://github.com/localstack-samples/sample-cdk-rds/blob/main/demos/rds-init-example.ts#L20)

```typescript
		const credsSecretName = `/${id}/rds/creds/main-rds`.toLowerCase()
		const creds = new rds.DatabaseSecret(this, 'MainRDSCredentials', {
			secretName: credsSecretName,
			username: 'postgres'
		})

		const engine = rds.DatabaseInstanceEngine.postgres({ version: rds.PostgresEngineVersion.VER_14 });

		const instanceType = isDev(props.deployEnv) ?
			ec2.InstanceType.of(ec2.InstanceClass.T4G, ec2.InstanceSize.MICRO) :
			ec2.InstanceType.of(ec2.InstanceClass.T4G, ec2.InstanceSize.SMALL)
```

I get the following failure

```console
localstack_main  | 2023-10-29T17:00:37.254  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack_main  | 2023-10-29T17:00:37.281  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS sts.AssumeRole => 200
localstack_main  | 2023-10-29T17:00:37.294  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.GetBucketLocation => 200
localstack_main  | 2023-10-29T17:00:37.306  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS s3.ListObjectsV2 => 200
localstack_main  | 2023-10-29T17:00:37.316  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.GetBucketEncryption => 404 (ServerSideEncryptionConfigurationNotFoundError)
localstack_main  | 2023-10-29T17:00:37.337  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS s3.PutObject => 200
localstack_main  | 2023-10-29T17:00:37.354  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStacks => 400 (ValidationError)
localstack_main  | 2023-10-29T17:00:37.369  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.GetObject => 200
localstack_main  | 2023-10-29T17:00:37.380  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.CreateChangeSet => 200
localstack_main  | 2023-10-29T17:00:37.386  WARN --- [   asgi_gw_1] l.aws.protocol.serializer  : Response object DescribeChangeSetOutput contains a member which is not specified: RoleARN
localstack_main  | 2023-10-29T17:00:37.386  WARN --- [   asgi_gw_1] l.aws.protocol.serializer  : Response object DescribeChangeSetOutput contains a member which is not specified: ClientToken
localstack_main  | 2023-10-29T17:00:37.387  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeChangeSet => 200
localstack_main  | 2023-10-29T17:00:37.396 DEBUG --- [   asgi_gw_2] l.s.c.provider             : Executing change set "cdk-deploy-change-set" for stack "RDSStack" with 6 resources ...
localstack_main  | 2023-10-29T17:00:37.397  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.ExecuteChangeSet => 200
localstack_main  | 2023-10-29T17:00:37.406  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
localstack_main  | 2023-10-29T17:00:37.468 DEBUG --- [uncthread280] l.s.c.e.template_deployer  : Handling "Add" for resource "MainRDSCredentials83D37796" (1/6) type "AWS::SecretsManager::Secret" in loop iteration 1 (should_deploy=True)
localstack_main  | 2023-10-29T17:00:37.468 DEBUG --- [uncthread280] l.s.c.resource_provider    : Running action "Add" for resource type "AWS::SecretsManager::Secret" id "MainRDSCredentials83D37796"
localstack_main  | 2023-10-29T17:00:37.474 DEBUG --- [uncthread280] l.s.c.resource_provider    : Request for resource type "AWS::SecretsManager::Secret" in account 000000000000 region eu-central-1: create_secret {'Description': 'Generated by the CDK fo
localstack_main  | 2023-10-29T17:00:37.995  INFO --- [   asgi_gw_2] localstack.utils.bootstrap : Execution of "_load_service_plugin" took 510.10ms
localstack_main  | 2023-10-29T17:00:37.995  INFO --- [   asgi_gw_2] localstack.utils.bootstrap : Execution of "require" took 510.59ms
localstack_main  | 2023-10-29T17:00:38.036 DEBUG --- [uncthread280] l.s.c.resource_provider    : Executing callback method for AWS::SecretsManager::Secret:MainRDSCredentials83D37796
localstack_main  | 2023-10-29T17:00:38.047  WARN --- [   asgi_gw_0] l.aws.protocol.serializer  : Response object DescribeSecretResponse contains a member which is not specified: ResponseMetadata
localstack_main  | 2023-10-29T17:00:38.086 DEBUG --- [uncthread280] l.s.c.e.template_deployer  : Unable to resolve Ref for resource "MainRDSA6A6C95C" (yet) - {'Type': 'AWS::RDS::DBInstance', 'UpdateReplacePolicy': 'Snapshot', 'DeletionPolicy': 'Snapsho
localstack_main  | 2023-10-29T17:00:38.086 DEBUG --- [uncthread280] l.s.c.e.template_deployer  : Dependencies for "MainRDSCredentialsAttachment7F20A339" not yet satisfied, retrying in next loop: Unable to resolve Ref for resource "MainRDSA6A6C95C" (yet
localstack_main  | 2023-10-29T17:00:38.137 DEBUG --- [uncthread280] l.s.c.e.template_deployer  : Handling "Add" for resource "MainRDSSubnetGroupBE274511" (2/5) type "AWS::RDS::DBSubnetGroup" in loop iteration 1 (should_deploy=True)
localstack_main  | 2023-10-29T17:00:38.137 DEBUG --- [uncthread280] l.s.c.resource_provider    : Running action "Add" for resource type "AWS::RDS::DBSubnetGroup" id "MainRDSSubnetGroupBE274511"
localstack_main  | 2023-10-29T17:00:38.154 DEBUG --- [uncthread280] l.s.c.resource_provider    : Request for resource type "AWS::RDS::DBSubnetGroup" in account 000000000000 region eu-central-1: create_db_subnet_group {'DBSubnetGroupDescription': 'Subne
localstack_main  | 2023-10-29T17:00:38.695 DEBUG --- [uncthread280] l.s.c.resource_provider    : Executing callback method for AWS::RDS::DBSubnetGroup:MainRDSSubnetGroupBE274511
localstack_main  | 2023-10-29T17:00:38.784 DEBUG --- [uncthread280] l.s.c.e.template_deployer  : Handling "Add" for resource "MainRDSSecurityGroup67B550ED" (2/4) type "AWS::EC2::SecurityGroup" in loop iteration 1 (should_deploy=True)
localstack_main  | 2023-10-29T17:00:38.784 DEBUG --- [uncthread280] l.s.c.resource_provider    : Running action "Add" for resource type "AWS::EC2::SecurityGroup" id "MainRDSSecurityGroup67B550ED"
localstack_main  | 2023-10-29T17:00:38.785 DEBUG --- [uncthread280] l.s.c.resource_provider    : Request for resource type "AWS::EC2::SecurityGroup" in account 000000000000 region eu-central-1: create_security_group {'GroupName': 'RDSStack-MainRDSSecur
localstack_main  | 2023-10-29T17:00:38.798 DEBUG --- [uncthread280] l.s.c.resource_provider    : Executing callback method for AWS::EC2::SecurityGroup:MainRDSSecurityGroup67B550ED
localstack_main  | 2023-10-29T17:00:38.888  WARN --- [   asgi_gw_2] l.aws.protocol.serializer  : Response object GetSecretValueResponse contains a member which is not specified: ResponseMetadata
localstack_main  | 2023-10-29T17:00:38.931  WARN --- [   asgi_gw_2] l.aws.protocol.serializer  : Response object GetSecretValueResponse contains a member which is not specified: ResponseMetadata
localstack_main  | 2023-10-29T17:00:38.959 DEBUG --- [uncthread280] l.s.c.e.template_deployer  : Handling "Add" for resource "MainRDSA6A6C95C" (2/3) type "AWS::RDS::DBInstance" in loop iteration 1 (should_deploy=True)
localstack_main  | 2023-10-29T17:00:38.959 DEBUG --- [uncthread280] l.s.c.resource_provider    : Running action "Add" for resource type "AWS::RDS::DBInstance" id "MainRDSA6A6C95C"
localstack_main  | 2023-10-29T17:00:38.960 DEBUG --- [uncthread280] l.s.c.resource_provider    : Request for resource type "AWS::RDS::DBInstance" in account 000000000000 region eu-central-1: create_db_instance {'DBName': 'seolitic', 'DBInstanceIdentifi
localstack_main  | 2023-10-29T17:00:39.106 DEBUG --- [   asgi_gw_0] l.services.rds.db_utils    : Determined and reserved port 4512 (requested port None) for RDS database
localstack_main  | 2023-10-29T17:00:39.512  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack_main  | 2023-10-29T17:00:39.529  INFO --- [   Thread-27] l.utils.postgresql         : Starting PostgreSQL query listener/rewriter on port 4512->51181
localstack_main  | 2023-10-29T17:00:40.530 DEBUG --- [   Thread-27] l.utils.postgresql         : Connection refused in Postgres proxy server - instance not (yet) available
localstack_main  | 2023-10-29T17:00:40.531 DEBUG --- [uncthread297] localstack.packages.api    : Installation of postgresql skipped (already installed).
localstack_main  | 2023-10-29T17:00:40.531 DEBUG --- [uncthread297] localstack.packages.api    : Performing runtime setup for already installed package.
localstack_main  | 2023-10-29T17:00:40.531  INFO --- [uncthread297] l.s.rds.engine_postgres    : Starting RDS server on port 4512 (backend port 51181) - database "seolitic", user "postgres" - data dir /var/lib/localstack/tmp/state/rds/postgres/00000000
localstack_main  | 2023-10-29T17:00:41.526  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack_main  | 2023-10-29T17:00:42.417  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
localstack_main  | 2023-10-29T17:00:43.333  WARN --- [uncthread297] l.services.rds.db_utils    : Unable to startup DB instance: {'S': 'FATAL', 'V': 'FATAL', 'C': '28P01', 'M': 'password authentication failed for user "postgres"', 'F': 'auth.c', 'L': '3
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/pg8000/legacy.py", line 443, in __init__
localstack_main  |     super().__init__(*args, **kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/pg8000/core.py", line 382, in __init__
localstack_main  |     raise e
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/pg8000/core.py", line 378, in __init__
localstack_main  |     raise context.error
localstack_main  | pg8000.exceptions.DatabaseError: {'S': 'FATAL', 'V': 'FATAL', 'C': '28P01', 'M': 'password authentication failed for user "postgres"', 'F': 'auth.c', 'L': '335', 'R': 'auth_failed'}
localstack_main  |
localstack_main  | During handling of the above exception, another exception occurred:
localstack_main  |
localstack_main  | Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/rds/db_utils.py.enc", line 63, in B
localstack_main  |     try:A and A(status='creating');G=E.start_db_instance(*D,**F);A and A(status=_D);LOG.debug('DB started successfully.');return G
localstack_main  |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/rds/engine_postgres.py.enc", line 61, in start_db_instance
localstack_main  |     define_postgres_extensions(C[_B],pg_version=K);return C
localstack_main  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/rds/extensions_postgres.py.enc", line 23, in define_postgres_extensions
localstack_main  |     try:A.run_query(f"CREATE EXTENSION IF NOT EXISTS {PG_EXTENSION_PLPYTHON}")
localstack_main  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/utils/postgresql.py.enc", line 105, in run_query
localstack_main  |     D=B.connect(database,admin=admin)
localstack_main  |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/utils/postgresql.py.enc", line 112, in connect
localstack_main  |     return pg8000.connect(**C)
localstack_main  |            ^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/pg8000/__init__.py", line 111, in connect
localstack_main  |     return Connection(
localstack_main  |            ^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/pg8000/legacy.py", line 456, in __init__
localstack_main  |     raise cls(msg)
localstack_main  | pg8000.dbapi.ProgrammingError: {'S': 'FATAL', 'V': 'FATAL', 'C': '28P01', 'M': 'password authentication failed for user "postgres"', 'F': 'auth.c', 'L': '335', 'R': 'auth_failed'}
localstack_main  |
localstack_main  |
localstack_main  | 2023-10-29T17:00:43.535 DEBUG --- [uncthread280] l.s.c.resource_provider    : Executing callback method for AWS::RDS::DBInstance:MainRDSA6A6C95C
localstack_main  | 2023-10-29T17:00:43.543  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack_main  | 2023-10-29T17:00:45.557  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack_main  | 2023-10-29T17:00:47.431  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
localstack_main  | 2023-10-29T17:00:47.568  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack_main  | 2023-10-29T17:00:49.581  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack_main  | 2023-10-29T17:00:51.594  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack_main  | 2023-10-29T17:00:52.445  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
localstack_main  | 2023-10-29T17:00:53.608  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack_main  | 2023-10-29T17:00:55.625  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStackEvents => 200
localstack_main  | 2023-10-29T17:00:57.456  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS cloudformation.DescribeStacks => 200
localstack_main  | 2023-10-29T17:02:46.558 DEBUG --- [uncthread280] l.s.c.e.template_deployer  : Error applying changes for CloudFormation stack "RDSStack": Waiter DBInstanceAvailable failed: Max attempts exceeded Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1172, in _run
localstack_main  |     self.do_apply_changes_in_loop(changes, stack)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1246, in do_apply_changes_in_loop
localstack_main  |     self.apply_change(change, stack=stack)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/engine/template_deployer.py", line 1361, in apply_change
localstack_main  |     progress_event = executor.deploy_loop(resource_provider_payload)  # noqa
localstack_main  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/resource_provider.py", line 678, in deploy_loop
localstack_main  |     event = self.execute_action(resource_provider, payload)
localstack_main  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/resource_provider.py", line 746, in execute_action
localstack_main  |     return resource_provider.create(request)
localstack_main  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/resource_provider.py", line 432, in create
localstack_main  |     return self.create_or_delete(request)
localstack_main  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/cloudformation/resource_provider.py", line 597, in create_or_delete
localstack_main  |     result_handler(
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/cloudformation/models/rds.py.enc", line 145, in C
localstack_main  |     def C(account_id,region_name,result,logical_resource_id,resource):G='DBSystemId';F='DbiResourceId';E='DBInstanceArn';D='CertificateDetails';C=resource;B='DBInstance';A=result;H=A[B][_M];connect_to(aws_access_key_id=account_id,region_name=region_name).rds.get_waiter('db_instance_available').wait(DBInstanceIdentifier=H);C[_A][D]=A[B].get(D);C[_A][E]=A[B][E];C[_A][F]=A[B][F];C[_A][_Q]=A[B].get(_Q);I=A[B].get('DbInstancePort');C[_A][_s]=A[B].get(_Q,{}).get(_T)or I;C[_A][G]=A[B].get(G);C[_A]['MasterUserSecret.SecretArn']=A[B].get('MasterUserSecret',{}).get('SecretArn');C[_H]=A[B][_M]
localstack_main  |                                                                                                                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/waiter.py", line 55, in wait
localstack_main  |     Waiter.wait(self, **kwargs)
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/patch.py", line 38, in proxy
localstack_main  |     return new(target, *args, **kwargs)
localstack_main  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/connect.py", line 59, in my_patch
localstack_main  |     return fn(self, **patched_kwargs)
localstack_main  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/waiter.py", line 388, in wait
localstack_main  |     raise WaiterError(
localstack_main  | botocore.exceptions.WaiterError: Waiter DBInstanceAvailable failed: Max attempts exceeded
localstack_main  |
localstack_main  |
```

### Expected Behavior

RDS instance startups as expected

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Start `localstack-pro` in docker compose

2. Create a RDS CDK stack

```typescript
import { ConstValues, StackProps, isDev } from "@/consts";
import { Stack } from "aws-cdk-lib";
import { Construct } from "constructs";
import * as rds from 'aws-cdk-lib/aws-rds';
import * as ec2 from 'aws-cdk-lib/aws-ec2';

type RDSStackProps = {
	vpc: ec2.Vpc;
} & StackProps;

export class RDSStack extends Stack {
	public rds: rds.DatabaseInstance;

	constructor(scope: Construct, id: string, props: RDSStackProps) {
		super(scope, id, props);

		const credsSecretName = `/${id}/rds/creds/main-rds`.toLowerCase()
		const creds = new rds.DatabaseSecret(this, 'MainRDSCredentials', {
			secretName: credsSecretName,
			username: 'postgres'
		})

		const engine = rds.DatabaseInstanceEngine.postgres({ version: rds.PostgresEngineVersion.VER_14 });

		const instanceType = isDev(props.deployEnv) ?
			ec2.InstanceType.of(ec2.InstanceClass.T4G, ec2.InstanceSize.MICRO) :
			ec2.InstanceType.of(ec2.InstanceClass.T4G, ec2.InstanceSize.SMALL)

		this.rds = new rds.DatabaseInstance(this, 'MainRDS', {
			vpcSubnets: {
				subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
			},
			vpc: props.vpc,
			credentials: rds.Credentials.fromSecret(creds),
			databaseName: ConstValues.database.backend.name,
			engine: engine,
			instanceType: instanceType,
			allocatedStorage: 10,
		})
	}
}
```

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: latest
```

**Comment by steffyP** [comment]
Hi @Nikola-Milovic,

thanks for reporting! Please be aware that the username `postgres` cannot be used for LocalStack. The user will be created implicitly. You need to select a different `MasterUserName`. 
Please also check our [docs](https://docs.localstack.cloud/user-guide/aws/rds/#default-usernames-and-passwords).
