### ISSUE TITLE
bug: Unable to start up localstack pro: Unexpected exception while starting infrastructure

### ISSUE THREAD

**Issue by theogravity** [localstack/localstack#9524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Something seems to have broken recently and trying older images down to 2.2 no longer works. I made sure to clear out my containers / images / volumes. 

```
023-10-31T18:55:17.205 DEBUG --- [  MainThread] localstack.dns.server      : Adding skip pattern ^localstack-assets\.s3(\.[^\.]+)?\.amazonaws\.com
Unexpected exception while starting infrastructure: Expecting ',' delimiter: line 1 column 281 (char 280) Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/infra.py", line 390, in start_infra
    hooks.on_infra_start.run()
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/runtime/hooks.py", line 64, in run_in_order
    fn_plugin(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/plugin/core.py", line 180, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_persistence/snapshot/__plugins__.py", line 27, in register_state_resource
    def register_state_resource():from localstack.services.internal import get_internal_apis as A;from.endpoints import StateResource as B;C=B(get_service_state_manager());A().add(C)
                                                                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/objects.py", line 203, in _singleton_factory
    instance.set(factory())
                 ^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_persistence/snapshot/__plugins__.py", line 25, in get_service_state_manager
    def get_service_state_manager():from localstack import config as A;from localstack.services.plugins import SERVICE_PLUGINS as B;from.manager import SnapshotManager as C;return C(B,A.dirs.data)
                                                                                                                                                                                    ^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_persistence/snapshot/manager.py", line 23, in __init__
    def __init__(A,service_manager,data_dir,service_sorter=None):B=data_dir;super().__init__(service_manager);A.data_dir=B;A.tracker=FileMappedDocument(os.path.join(B,constants.API_STATES_JSON));A.persistence_plugin_manager=PluginManager(SnapshotPersistencePlugin.namespace);A.service_sorter=service_sorter or DefaultPrioritySorter()
                                                                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/json.py", line 71, in __init__
    self.load()
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/json.py", line 81, in load
    self.update(json.load(fd))
                ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 281 (char 280)
```

### Expected Behavior

Should load.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

dockerfile:

```
FROM localstack/localstack-pro:latest
```

docker-compose file:

```
version: "3.7"
services:
  localstack:
    build:
      context: .
      dockerfile: docker/localstack/Dockerfile.localstack-pro
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - DISABLE_CORS_CHECKS=1
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - PERSISTENCE=1
      - SNAPSHOT_SAVE_STRATEGY=ON_SHUTDOWN
      - SNAPSHOT_LOAD_STRATEGY=ON_STARTUP
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY:- }
      - LAMBDA_IGNORE_ARCHITECTURE=1
      - AWS_DEFAULT_REGION=us-east-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-~/.localstack-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### Environment

```markdown
- OS: MacOS 14.0
- LocalStack: Latest 2.3
- Arm-based M2
```

**Comment by theogravity** [comment]
@bentsku I'm canceling my localstack pro subscription until this is fixed because I can't use pro at all since it can't start

**Comment by bentsku** [comment]
Hello @theogravity,

If you'd like better support, you can contact us via Slack as said the bot message:
> We recommend joining our [Slack Community](https://localstack.cloud/contact/) for real-time help and drop a message to LocalStack Pro Support if you are a Pro user!

However, this seems related to persistence, because your `docker-compose` config seems quite normal, and the image is working currently, I'm unable to reproduce given the informations here, I can start LocalStack, create some state and shutdown/restart and the state is still present.

All the trace points to a singular file named `api_states.json`, that would be located at this path in the container: `/var/lib/localstack/state/api_states.json` and this path in your mounted volume `./state/api_states.json`.
It looks like the JSON file might be malformed?

**Comment by theogravity** [comment]
Thanks, your comment really helped. Even though I removed the volumes when troubleshooting, it seems my mounted directory `~/.localstack-volume" was still intact. Removing the dir and rebuilding fixed the issue!

**Comment by bentsku** [comment]
Awesome, thanks for the feedback and I'm glad your issue is solved!
