### ISSUE TITLE
bug: Error [ValidationError]: Stack <my stack> already exists

### ISSUE THREAD

**Issue by anentropic** [localstack/localstack#9564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Can't deploy with cdklocal

I get `Error [ValidationError]: Stack <my stack> already exists`

I have tried `localstack stop` and then start up again. I run `cdklocal bootstrap` and then `cdklocal deploy`

Running deploy with `-v` shows:

```
Do you wish to deploy these changes (y/n)? y
Website-EU-localstack: deploying... [1/1]
[17:03:24] Retrieved account ID 000000000000 from disk cache
[17:03:24] Call failed: describeStacks({"StackName":"Website-EU-localstack"}) => Stack with id Website-EU-localstack does not exist (code=ValidationError)
[17:03:24] Website-EU-localstack: checking if we can skip deploy
[17:03:24] Website-EU-localstack: no existing stack
[17:03:24] Website-EU-localstack: deploying...
[17:03:24] Attempting to create ChangeSet with name cdk-deploy-change-set to create stack Website-EU-localstack
Website-EU-localstack: creating CloudFormation changeset...
[17:03:25] Call failed: createChangeSet({"StackName":"Website-EU-localstack","ChangeSetName":"cdk-deploy-change-set","ChangeSetType":"CREATE","Description":"CDK Changeset for execution 19473ef6-e18a-4ee7-bfc1-58abde2dc6aa","ClientToken":"create19473ef6-e18a-4ee7-bfc1-58abde2dc6aa","Capabilities":["CAPABILITY_IAM","CAPABILITY_NAMED_IAM","CAPABILITY_AUTO_EXPAND"],"Parameters":[],"RoleARN":"arn:aws:iam::000000000000:role/cdk-hnb659fds-cfn-exec-role-000000000000-eu-west-1","TemplateURL":"https://s3.eu-west-1.amazonaws.com/cdk-hnb659fds-assets-000000000000-eu-west-1/6b122f69311cfde98398c46c5af54e1a4afcb3aff109c18281a2bb60347ae310.json","Tags":[{"Key":"App","Value":"Triage reporting"},{"Key":"BuiltBy","Value":"CDK"},{"Key":"Environment","Value":"localstack"},{"Key":"Service","Value":"website"}]}) => Stack Website-EU-localstack already exists (code=ValidationError)

 ❌  Website-EU-localstack failed: Error [ValidationError]: Stack Website-EU-localstack already exists
    at Request.extractError (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:46430)
    at Request.callListeners (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:90083)
    at Request.emit (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:89531)
    at Request.emit (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:196289)
    at Request.transition (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:189841)
    at AcceptorStateMachine.runTo (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:154713)
    at /Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:155043
    at Request.<anonymous> (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:190133)
    at Request.<anonymous> (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:196364)
    at Request.callListeners (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:90251) {
  code: 'ValidationError',
  time: 2023-11-06T17:03:25.647Z,
  requestId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 498.4710745870995
}

 ❌ Deployment failed: Error [ValidationError]: Stack Website-EU-localstack already exists
    at Request.extractError (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:46430)
    at Request.callListeners (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:90083)
    at Request.emit (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:89531)
    at Request.emit (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:196289)
    at Request.transition (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:189841)
    at AcceptorStateMachine.runTo (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:154713)
    at /Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:155043
    at Request.<anonymous> (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:190133)
    at Request.<anonymous> (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:196364)
    at Request.callListeners (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:90251) {
  code: 'ValidationError',
  time: 2023-11-06T17:03:25.647Z,
  requestId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 498.4710745870995
}
[17:03:25] Reading cached notices from /Users/anentropic/.cdk/cache/notices.json

Stack Website-EU-localstack already exists
[17:03:25] ValidationError: Stack Website-EU-localstack already exists
    at Request.extractError (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:46430)
    at Request.callListeners (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:90083)
    at Request.emit (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:89531)
    at Request.emit (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:196289)
    at Request.transition (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:189841)
    at AcceptorStateMachine.runTo (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:154713)
    at /Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:155043
    at Request.<anonymous> (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:190133)
    at Request.<anonymous> (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:196364)
    at Request.callListeners (/Users/anentropic/.nvm/versions/node/v18.18.0/lib/node_modules/aws-cdk/lib/index.js:366:90251)
```

### Expected Behavior

it works

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`localstack start -d`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

`cdklocal bootstrap`

`cdklocal deploy -v`

### Environment

```markdown
- OS: macOS 14.1
- LocalStack: 2.2.0
```

### Anything else?

looks similar to this https://github.com/localstack/localstack/issues/6961 which got closed for lack of activity

**Comment by anentropic** [comment]
What seems to be happening is there is an error in my stack that is getting obscured... I tried commenting out parts of the stack. If I comment out enough it succeeds. If I comment out a bit less I get something like:

```
Website-EU-localstack | 25/46 | 18:31:17 | CREATE_FAILED        | AWS::EC2::Subnet                      | Database/DB Private Subnet/Subnet (DatabaseDBPrivateSubnet37478003) An error occurred (InvalidSubnet.Conflict) when calling the CreateSubnet operation: The CIDR '10.0.0.0/16' conflicts with another subnet
Website-EU-localstack | 25/46 | 18:31:17 | CREATE_FAILED        | AWS::CloudFormation::Stack            | Website-EU-localstack An error occurred (InvalidSubnet.Conflict) when calling the CreateSubnet operation: The CIDR '10.0.0.0/16' conflicts with another subnet

Failed resources:
Website-EU-localstack | 18:31:17 | CREATE_FAILED        | AWS::EC2::Subnet                      | Database/DB Private Subnet/Subnet (DatabaseDBPrivateSubnet37478003) An error occurred (InvalidSubnet.Conflict) when calling the CreateSubnet operation: The CIDR '10.0.0.0/16' conflicts with another subnet
```

(I've obviously done something wrong there)

And if I comment out even less then I get the original "Stack already exists" symptom.

**Comment by dominikschubert** [comment]
Hi @anentropic ! Do you maybe have a sample template that can trigger this behavior you're describing?
