### ISSUE TITLE
enhancement request: AWS::SecretsManager::SecretTargetAttachment for AWS::RDS::DBInstance

### ISSUE THREAD

**Issue by anentropic** [localstack/localstack#9565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Judging by this issue: https://github.com/localstack/localstack/issues/6748

specifically the closing comment:

> We've added support for the AWS::RDS::DBCluster target type. This should already be available in the latest image.
>
> If you need other target types, please open a separate feature request so we can track their implementation status.

...I think the error I am getting may be due to lack of support currently in localstack?

```
Website-EU-localstack | 33/36 | 19:22:26 | CREATE_FAILED        | AWS::CloudFormation::Stack                  |
Website-EU-localstack Resource deployment loop completed, pending resource changes:
[{
  'Type': 'Resource',
  'ResourceChange': {
    'Action': 'Add',
    'LogicalResourceId': 'DatabaseDBConnectionSecretAttachment47F76E29',
    'PhysicalResourceId': None,
    'ResourceType': 'AWS::SecretsManager::SecretTargetAttachment',
    'Scope': [],
    'Details': []
  }
},
{
  'Type': 'Resource',
  'ResourceChange': {
    'Action': 'Add',
    'LogicalResourceId': 'DatabaseMySQLADA28B0A',
    'PhysicalResourceId': None,
    'ResourceType': 'AWS::RDS::DBInstance',
    'Scope': [],
    'Details': []
  }
}]
```
(reformatted for readability)

**Comment by PierFio** [comment]
Hello,

I have the same issue when executing a cdk deployment.

This is the generated template:
```
{
 "Resources": {
  "DatabaseSubnetsEDC9F96E": {
   "Type": "AWS::RDS::DBSubnetGroup",
   "Properties": {
    "DBSubnetGroupDescription": "Subnets for Database database",
    "SubnetIds": [
     {
      "Fn::ImportValue": "CoreStack:ExportsOutputRefvpcPrivateSubnet1Subnet934893E8236E2271"
     },
     {
      "Fn::ImportValue": "CoreStack:ExportsOutputRefvpcPrivateSubnet2Subnet7031C2BA60DCB1EE"
     },
     {
      "Fn::ImportValue": "CoreStack:ExportsOutputRefvpcPrivateSubnet3Subnet985AC459F9514491"
     }
    ]
   },
   "Metadata": {
    "aws:cdk:path": "StorageStack/Database/Subnets/Default"
   }
  },
  "DatabaseSecurityGroup722FD5AF": {
   "Type": "AWS::EC2::SecurityGroup",
   "Properties": {
    "GroupDescription": "RDS security group",
    "SecurityGroupEgress": [
     {
      "CidrIp": "0.0.0.0/0",
      "Description": "Allow all outbound traffic by default",
      "IpProtocol": "-1"
     }
    ],
    "VpcId": {
     "Fn::ImportValue": "CoreStack:ExportsOutputRefvpcA2121C384D1B3CDE"
    }
   },
   "Metadata": {
    "aws:cdk:path": "StorageStack/Database/SecurityGroup/Resource"
   }
  },
  "StorageStackDatabaseSecretD5AE10DD3fdaad7efa858a3daf9490cf0a702aeb": {
   "Type": "AWS::SecretsManager::Secret",
   "Properties": {
    "Description": {
     "Fn::Join": [
      "",
      [
       "Generated by the CDK for stack: ",
       {
        "Ref": "AWS::StackName"
       }
      ]
     ]
    },
    "GenerateSecretString": {
     "ExcludeCharacters": " %+~`#$&*()|[]{}:;<>?!'/@\"\\",
     "GenerateStringKey": "password",
     "PasswordLength": 30,
     "SecretStringTemplate": "{\"username\":\"postgres\"}"
    },
    "Name": "rds_admin_password"
   },
   "UpdateReplacePolicy": "Delete",
   "DeletionPolicy": "Delete",
   "Metadata": {
    "aws:cdk:path": "StorageStack/Database/Secret/Resource"
   }
  },
  "DatabaseSecretAttachmentDCE8F846": {
   "Type": "AWS::SecretsManager::SecretTargetAttachment",
   "Properties": {
    "SecretId": {
     "Ref": "StorageStackDatabaseSecretD5AE10DD3fdaad7efa858a3daf9490cf0a702aeb"
    },
    "TargetId": {
     "Ref": "Database0B038F44"
    },
    "TargetType": "AWS::RDS::DBCluster"
   },
   "Metadata": {
    "aws:cdk:path": "StorageStack/Database/Secret/Attachment/Resource"
   }
  },
  "Database0B038F44": {
   "Type": "AWS::RDS::DBCluster",
   "Properties": {
    "CopyTagsToSnapshot": true,
    "DBClusterParameterGroupName": "default.aurora-postgresql13",
    "DBSubnetGroupName": {
     "Ref": "DatabaseSubnetsEDC9F96E"
    },
    "DatabaseName": "core",
    "Engine": "aurora-postgresql",
    "EngineMode": "serverless",
    "EngineVersion": "13.12",
    "MasterUserPassword": {
     "Fn::Join": [
      "",
      [
       "{{resolve:secretsmanager:",
       {
        "Ref": "StorageStackDatabaseSecretD5AE10DD3fdaad7efa858a3daf9490cf0a702aeb"
       },
       ":SecretString:password::}}"
      ]
     ]
    },
    "MasterUsername": "postgres",
    "ScalingConfiguration": {
     "AutoPause": true,
     "MaxCapacity": 4,
     "MinCapacity": 2,
     "SecondsUntilAutoPause": 300
    },
    "StorageEncrypted": true,
    "VpcSecurityGroupIds": [
     {
      "Fn::GetAtt": [
       "DatabaseSecurityGroup722FD5AF",
       "GroupId"
      ]
     }
    ]
   },
   "UpdateReplacePolicy": "Snapshot",
   "DeletionPolicy": "Snapshot",
   "Metadata": {
    "aws:cdk:path": "StorageStack/IncubationDatabase/Resource"
   }
  }
}
```

The cluster is correctly created and the secret is generated. But the instance is not created:
cdklocal output:
```
StorageStack: creating CloudFormation changeset...
10:01:57 AM | UPDATE_FAILED        | AWS::RDS::DBCluster                         | Database0B038F44
Unexpected status error


 ❌  StorageStack failed: Error: The stack named StorageStack failed to deploy: CREATE_FAILED (Unexpected status error): Unexpected status error
    at FullCloudFormationDeployment.monitorDeployment (/home/pierre/.nvm/versions/node/v20.10.0/lib/node_modules/aws-cdk/lib/index.js:421:10934)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/home/pierre/.nvm/versions/node/v20.10.0/lib/node_modules/aws-cdk/lib/index.js:424:180618)
    at async /home/pierre/.nvm/versions/node/v20.10.0/lib/node_modules/aws-cdk/lib/index.js:424:163866

```

The log shows the problem stems with the credentials to access the database:

![image](https://github.com/localstack/localstack/assets/11286090/b8bf643a-840b-49e4-ac89-c8649dc38193)
