### ISSUE TITLE
Error when start localstack on Windows 10 with ES

### ISSUE THREAD

**Issue by parthiban45** [localstack/localstack#963]
2018-10-15T16:13:36:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2018-10-15T16:13:40:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2018-10-15T16:13:43:ERROR:localstack.services.es.es_starter: Elasticsearch health check failed (retrying...): TransportE
rror(502, u'') Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/es/es_starter.py", line 59, in check_elasticsearch
    out = es.cat.aliases()
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/client/cat.py", line 23, in aliases
    'aliases', name), params=params)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignor
e, timeout=timeout)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 90, in p
erform_request
    self._raise_error(response.status_code, raw_data)
  File "/opt/code/localstack/.venv/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_er
ror
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
TransportError: TransportError(502, u'')

2018-10-15T16:13:43:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
2018-10-15T16:13:43:ERROR:infra.pyc: Error checking state of local environment (after some retries): Traceback (most rec
ent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 348, in check_infra
    raise e
AssertionError

Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
Error starting infrastructure:  Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 486, in start_infra
    check_infra(apis=apis)
  File "/opt/code/localstack/localstack/services/infra.py", line 357, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 357, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 357, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)
  File "/opt/code/localstack/localstack/services/infra.py", line 357, in check_infra
    check_infra(retries - 1, expect_shutdown=expect_shutdown, apis=apis, additional_checks=additional_checks)

**Comment by whummer** [comment]
Installation should work now under Windows (see also the recent changes in #1631). Closing this issue - please re-open if the problem persists. Thanks
