### ISSUE TITLE
bug: Error thrown when starting EKS cluster

### ISSUE THREAD

**Issue by leviem1** [localstack/localstack#9657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When deploying an EKS node group, I get the following errors in the LocalStack console:
```text
2023-11-16T05:17:07.634 DEBUG --- [   asgi_gw_2] localstack.packages.api    : Installation of k3d skipped (already installed).
2023-11-16T05:17:07.634 DEBUG --- [   asgi_gw_2] localstack.packages.api    : Performing runtime setup for already installed package.
2023-11-16T05:17:07.634 DEBUG --- [   asgi_gw_2] localstack.utils.run       : Executing command: ['/var/lib/localstack/lib/k3d/v5.6.0/k3d-linux-arm64', 'node', 'list', '-o', 'json']
2023-11-16T05:17:07.665 ERROR --- [   asgi_gw_2] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 123, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/handlers/service.py", line 93, in __call__
    skeleton_response = self.skeleton.invoke(context)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 154, in invoke
    return self.dispatch_request(context, instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 166, in dispatch_request
    result = handler(context, instance) or {}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/skeleton.py", line 118, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/aws/api/core.py", line 160, in operation_marker
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/eks/provider.py.enc", line 74, in create_nodegroup
    create_nodegroup(C,E);A.pop(_M,_A);A[_G]=timestamp_millis();A['nodegroupArn']=eks_nodegroup_arn(D,B.account_id,B.region);A[_B]=_H;G[D]=A;return CreateNodegroupResponse(nodegroup=A)
    ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/eks/provider.py.enc", line 127, in create_nodegroup
    def create_nodegroup(cluster_name,request):A=request;B=select_kube_provider();C=A.get(_S,{}).get('desiredSize',1);D=NodeSettings(labels=A.get('labels',{}));B.set_number_of_nodes(cluster_name,D,count=C)
                                                                                                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/eks/k8s_utils.py.enc", line 146, in set_number_of_nodes
    E='agent';C=count;A=cluster_name;D=len(list(B._nodes(A,node_role=E)))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/eks/k8s_utils.py.enc", line 155, in _nodes
    if B is not _A and A['role']!=B:continue
                       ~^^^^^^^^
KeyError: 'role'
2023-11-16T05:17:07.702  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS eks.CreateNodegroup => 500 (InternalError)
```

### Expected Behavior

I expect the operation to return a success status.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
```yaml
services:
  localstack:
      image: localstack/localstack-pro
      ports:
        - "4510-4560:4510-4560"
        - "4566:4566"
      environment:
        - DOCKER_HOST=unix:///var/run/docker.sock
        - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
        - DEBUG=1
        - AWS_ACCESS_KEY_ID=test
        - AWS_SECRET_ACCESS_KEY=test
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./bin/init-aws.sh:/etc/localstack/init/ready.d/01-init-aws.sh
        - ./bin/init-docker.sh:/etc/localstack/init/ready.d/02-init-docker.sh
```

#### API Calls (from Terraform)
```text
POST /clusters/orchestration-services-0e7a8b8/node-groups HTTP/1.1
{"amiType":"AL2_x86_64","clientRequestToken":"terraform-20231116062720073900000001","instanceTypes":["m7a.medium"],"nodeRole":"arn:aws:iam::000000000000:role/orchestration-services-node20231116051324161900000003","nodegroupName":"core-c233153","scalingConfig":{"desiredSize":2,"maxSize":2,"minSize":1},"subnets":["subnet-179f1406","subnet-9bb158ea"],"tags":{"project":"orchestration-eks-cluster"},"updateConfig":{"maxUnavailable":1}}
```

### Environment

```markdown
- OS: macOS Sonoma 14.1.1
- LocalStack: latest (as of posting)
```

### Anything else?

This worked before the v3 branch merge.

**Comment by lakkeger** [comment]
Hi @leviem1,
Thanks for reporting this issue, but unfortunately EKS node groups at this time not supported yet, however our engineers tirelessly working on to reach parity as soon as possible.
As an alternative solution you might can use Fargate which has a better coverage.
https://docs.localstack.cloud/user-guide/aws/feature-coverage/

**Comment by simonrw** [comment]
Hi @leviem1, we have merged some changes in that we think should solve your issue. After resolving this specific error, we uncovered further problems with the way that terraform and k3d interact with LocalStack - specifically a race condition that was definitely worth fixing! Thank you again for raising this issue.

**Comment by leviem1** [comment]
@simonrw Sorry for not getting back to you sooner, I've been on vacation. Looks like your changes worked! Thanks for your hard work and for tracking this down.
