### ISSUE TITLE
Can't start localstack community

### ISSUE THREAD

**Issue by fernao** [localstack/localstack#9674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After starting with localstack, I've got and auth_token and runned
    export LOCALSTACK_AUTH_TOKEN="my-auth-token-xxxxx"
    export ACTIVATE_PRO=0
    localstack start

The response was the following:

`
 💻 LocalStack CLI 3.0.0

[11:41:15] starting LocalStack in Docker mode 🐳                                                                                                                                                  localstack.py:495
────────────────────────────────────────────────────────────────────────────────── LocalStack Runtime Log (press CTRL-C to quit) ──────────────────────────────────────────────────────────────────────────────────

LocalStack version: 3.0.0
LocalStack Docker container id: 1bd7e942cbdc
LocalStack build date: 2023-11-16
LocalStack build git hash: 6dd3f3d

Unexpected exception while starting infrastructure: No module named 'localstack_ext.persistence.pickling.reducers.botocore' Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/infra.py", line 258, in start_infra
    hooks.on_infra_start.run()
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/runtime/hooks.py", line 64, in run_in_order
    fn_plugin(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/plugin/core.py", line 223, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/persistence/pickling/plugins.py", line 3, in register_pickle_patches_runtime
    def register_pickle_patches_runtime():from.reducers import register as A;A()
                                                                             ^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/objects.py", line 203, in _singleton_factory
    instance.set(factory())
                 ^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/persistence/pickling/reducers/__init__.py", line 25, in register
    import localstack_ext.persistence.pickling.reducers.botocore  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'localstack_ext.persistence.pickling.reducers.botocore'

2023-11-17T14:41:19.622  INFO --- [  MainThread] l.runtime.shutdown         : [shutdown] Stopping all services
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/runtime/main.py", line 28, in <module>
    main()
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/runtime/main.py", line 20, in main
    infra.start_infra(asynchronous=False)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/infra.py", line 280, in start_infra
    raise e
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/infra.py", line 258, in start_infra
    hooks.on_infra_start.run()
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/runtime/hooks.py", line 64, in run_in_order
    fn_plugin(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/plugin/core.py", line 223, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/persistence/pickling/plugins.py", line 3, in register_pickle_patches_runtime
    def register_pickle_patches_runtime():from.reducers import register as A;A()
                                                                             ^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/objects.py", line 203, in _singleton_factory
    instance.set(factory())
                 ^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/persistence/pickling/reducers/__init__.py", line 25, in register
    import localstack_ext.persistence.pickling.reducers.botocore  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'localstack_ext.persistence.pickling.reducers.botocore'
2023-11-17T11:41:25.862  INFO --- [-functhread1] localstack.utils.threads   : Thread run method <function Server.do_start_thread.<locals>._run at 0x7fe1bc5cc4a0>(None) failed: ('Docker process returned with errorcode 1', None, b'') Traceback (most recent call last):
  File "localstack/utils/container_utils/docker_cmd_client.py", line 683, in _run_async_cmd
subprocess.CalledProcessError: Command '['docker', 'attach', '1bd7e942cbdc2306895e2a8a6d97be34e411bb38244ae0e8a3e02988414aa03c']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "localstack/utils/threads.py", line 58, in run
  File "localstack/utils/serving.py", line 168, in _run
  File "localstack/utils/bootstrap.py", line 1065, in do_run
  File "localstack/utils/bootstrap.py", line 939, in attach
  File "localstack/utils/container_utils/docker_cmd_client.py", line 666, in attach_to_container
  File "localstack/utils/container_utils/docker_cmd_client.py", line 699, in _run_async_cmd
localstack.utils.container_utils.container_client.ContainerException: ('Docker process returned with errorcode 1', None, b'')

❌ Error: Docker process returned with errorcode 1
`

### Expected Behavior

According to the docs, localstack should load everything it needs and start.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Downloaded it:

    curl -Lo localstack-cli-3.0.0-linux-amd64-onefile.tar.gz \
    https://github.com/localstack/localstack-cli/releases/download/v3.0.0/localstack-cli-3.0.0-linux-amd64-onefile.tar.gz
    
Then runned:

    export LOCALSTACK_AUTH_TOKEN="my-auth-token-xxxxx"
    export ACTIVATE_PRO=0
    localstack start

### Environment

```markdown
- OS: Debian 12.0
- LocalStack: 3.0.0
```

**Comment by fernao** [comment]
worked well:

![Captura de tela de 2023-11-21 15-06-01](https://github.com/localstack/localstack/assets/4325697/a6d89c36-c71b-4105-b082-f9be00a9b95a)

Thank you so much!
