### ISSUE TITLE
bug: Issue starting localstack 3.0.0 in CI

### ISSUE THREAD

**Issue by peterabbott** [localstack/localstack#9688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On startup in CircleCI I am getting an error at startup 
```
Unable to start DNS: can't start new thread
Unexpected exception while starting infrastructure: can't start new thread Traceback (most recent call last):
```

After reading around I saw some mentions of using `DNS_ADDRESS=0` but that resulted same result, but slightly different error message.

```
Unexpected exception while starting infrastructure: can't start new thread Traceback (most recent call last):
```

Complete trace below. Have updated everything relevant in the release notes. But event ssh on to the CIrcle executor and doing `docker run localstack:localstack:3.0.0` results in the same error. 

THoughts on what we might be missing? 

### Expected Behavior

Localstack starts up successfully.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   ` docker run localstack/localstack` or `docker compose up localstack` (with minimal compose taking from docs).

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

n/a

### Environment

```markdown
- OS: Remote Docker 19 on CircleCI launching from `cimg/base:2023.11-20.04`
- LocalStack: 3.0.0
```

### Anything else?

Complete error listing 

```
LocalStack supervisor: starting
LocalStack supervisor: localstack process (PID 15) starting

LocalStack version: 3.0.0
LocalStack Docker container id: 556ffd5612d1
LocalStack build date: 2023-11-16
LocalStack build git hash: 3cd32364

2023-11-20T07:48:34.006 DEBUG --- [  MainThread] stevedore._cache           : reading /root/.cache/python-entrypoints/84931680eb339bf02832634d953210dc7b295fac63cfdb20c612fc9a94b2114a
2023-11-20T07:48:34.013 DEBUG --- [  MainThread] stevedore._cache           : writing to /root/.cache/python-entrypoints/84931680eb339bf02832634d953210dc7b295fac63cfdb20c612fc9a94b2114a
2023-11-20T07:48:34.015 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='_patch_botocore_json_parser', value='localstack.aws.client:_patch_botocore_json_parser', group='localstack.hooks.on_infra_start')
2023-11-20T07:48:34.016 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='_publish_config_as_analytics_event', value='localstack.runtime.analytics:_publish_config_as_analytics_event', group='localstack.hooks.on_infra_start')
2023-11-20T07:48:34.017 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='_publish_container_info', value='localstack.runtime.analytics:_publish_container_info', group='localstack.hooks.on_infra_start')
2023-11-20T07:48:34.017 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='_run_init_scripts_on_start', value='localstack.runtime.init:_run_init_scripts_on_start', group='localstack.hooks.on_infra_start')
2023-11-20T07:48:34.019 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='deprecation_warnings', value='localstack.plugins:deprecation_warnings', group='localstack.hooks.on_infra_start')
2023-11-20T07:48:34.019 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='register_partition_adjusting_proxy_listener', value='localstack.plugins:register_partition_adjusting_proxy_listener', group='localstack.hooks.on_infra_start')
2023-11-20T07:48:34.019 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='setup_dns_configuration_on_host', value='localstack.dns.plugins:setup_dns_configuration_on_host', group='localstack.hooks.on_infra_start')
2023-11-20T07:48:34.020 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='start_dns_server', value='localstack.dns.plugins:start_dns_server', group='localstack.hooks.on_infra_start')
2023-11-20T07:48:34.020 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='validate_configuration', value='localstack.services.lambda_.plugins:validate_configuration', group='localstack.hooks.on_infra_start')
2023-11-20T07:48:34.024 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._patch_botocore_json_parser = <function _patch_botocore_json_parser at 0x7fbc69012340>)
2023-11-20T07:48:34.024 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:_patch_botocore_json_parser
2023-11-20T07:48:34.024 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._publish_config_as_analytics_event = <function _publish_config_as_analytics_event at 0x7fbc69012660>)
2023-11-20T07:48:34.024 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:_publish_config_as_analytics_event
2023-11-20T07:48:34.024 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._publish_container_info = <function _publish_container_info at 0x7fbc69012980>)
2023-11-20T07:48:34.024 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:_publish_container_info
2023-11-20T07:48:34.024 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start._run_init_scripts_on_start = <function _run_init_scripts_on_start at 0x7fbc69013920>)
2023-11-20T07:48:34.024 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:_run_init_scripts_on_start
2023-11-20T07:48:34.025 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.deprecation_warnings = <function deprecation_warnings at 0x7fbc690580e0>)
2023-11-20T07:48:34.025 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:deprecation_warnings
2023-11-20T07:48:34.025 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.register_partition_adjusting_proxy_listener = <function register_partition_adjusting_proxy_listener at 0x7fbc69013f60>)
2023-11-20T07:48:34.025 DEBUG --- [  MainThread] plugin.manager             : plugin localstack.hooks.on_infra_start:register_partition_adjusting_proxy_listener is disabled
2023-11-20T07:48:34.025 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.setup_dns_configuration_on_host = <function setup_dns_configuration_on_host at 0x7fbc69058400>)
2023-11-20T07:48:34.025 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:setup_dns_configuration_on_host
2023-11-20T07:48:34.025 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.start_dns_server = <function start_dns_server at 0x7fbc690582c0>)
2023-11-20T07:48:34.025 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:start_dns_server
2023-11-20T07:48:34.026 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_start.validate_configuration = <function validate_configuration at 0x7fbc6905bce0>)
2023-11-20T07:48:34.026 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_start:validate_configuration
2023-11-20T07:48:34.052 DEBUG --- [  MainThread] localstack.dns.server      : Not starting DNS. DNS_ADDRESS=0
Unexpected exception while starting infrastructure: can't start new thread Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/infra.py", line 258, in start_infra
    hooks.on_infra_start.run()
  File "/opt/code/localstack/localstack/runtime/hooks.py", line 64, in run_in_order
    fn_plugin(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/plugin/core.py", line 223, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/runtime/analytics.py", line 86, in _publish_config_as_analytics_event
    log.event("config", env_vars=env_vars, set_vars=present_env_vars)
  File "/opt/code/localstack/localstack/utils/analytics/logger.py", line 39, in event
    self._log(event, payload=payload)
  File "/opt/code/localstack/localstack/utils/analytics/logger.py", line 42, in _log
    self.handler.handle(Event(name=event, metadata=self._metadata(), payload=payload))
  File "/opt/code/localstack/localstack/utils/analytics/publisher.py", line 235, in handle
    self._start()
  File "/opt/code/localstack/localstack/utils/analytics/publisher.py", line 250, in _start
    start_worker_thread(self._do_start_retry)
  File "/opt/code/localstack/localstack/utils/threads.py", line 109, in start_worker_thread
    return start_thread(method, *args, _shutdown_hook=False, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/utils/threads.py", line 101, in start_thread
    thread.start()
  File "/usr/local/lib/python3.11/threading.py", line 964, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

2023-11-20T07:48:34.486 DEBUG --- [  MainThread] localstack.services.infra  : [shutdown] Running shutdown hooks ...
2023-11-20T07:48:34.487 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='_run_init_scripts_on_shutdown', value='localstack.runtime.init:_run_init_scripts_on_shutdown', group='localstack.hooks.on_infra_shutdown')
2023-11-20T07:48:34.487 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='run_on_after_service_shutdown_handlers', value='localstack.runtime.shutdown:run_on_after_service_shutdown_handlers', group='localstack.hooks.on_infra_shutdown')
2023-11-20T07:48:34.488 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='run_shutdown_handlers', value='localstack.runtime.shutdown:run_shutdown_handlers', group='localstack.hooks.on_infra_shutdown')
2023-11-20T07:48:34.489 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='shutdown_services', value='localstack.runtime.shutdown:shutdown_services', group='localstack.hooks.on_infra_shutdown')
2023-11-20T07:48:34.489 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_shutdown._run_init_scripts_on_shutdown = <function _run_init_scripts_on_shutdown at 0x7fbc69013ba0>)
2023-11-20T07:48:34.489 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_shutdown:_run_init_scripts_on_shutdown
2023-11-20T07:48:34.489 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_shutdown.run_on_after_service_shutdown_handlers = <function run_on_after_service_shutdown_handlers at 0x7fbc68f3b920>)
2023-11-20T07:48:34.489 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_shutdown:run_on_after_service_shutdown_handlers
2023-11-20T07:48:34.489 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_shutdown.run_shutdown_handlers = <function run_shutdown_handlers at 0x7fbc68f3b6a0>)
2023-11-20T07:48:34.489 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_shutdown:run_shutdown_handlers
2023-11-20T07:48:34.489 DEBUG --- [  MainThread] plugin.manager             : instantiating plugin PluginSpec(localstack.hooks.on_infra_shutdown.shutdown_services = <function shutdown_services at 0x7fbc68f3b7e0>)
2023-11-20T07:48:34.489 DEBUG --- [  MainThread] plugin.manager             : loading plugin localstack.hooks.on_infra_shutdown:shutdown_services
2023-11-20T07:48:34.490 DEBUG --- [  MainThread] localstack.runtime.init    : Init scripts discovered: {BOOT: [], START: [], READY: [Script(path='/etc/localstack/init/ready.d/001-s3.sh', stage=READY, state=UNKNOWN), Script(path='/etc/localstack/init/ready.d/002-lambda.sh', stage=READY, state=UNKNOWN), Script(path='/etc/localstack/init/ready.d/010-dynamodb.sh', stage=READY, state=UNKNOWN), Script(path='/etc/localstack/init/ready.d/011-sns.sh', stage=READY, state=UNKNOWN), Script(path='/etc/localstack/init/ready.d/012-sqs.sh', stage=READY, state=UNKNOWN), Script(path='/etc/localstack/init/ready.d/013-s3-notifications.sh', stage=READY, state=UNKNOWN)], SHUTDOWN: []}
2023-11-20T07:48:34.490  INFO --- [  MainThread] l.runtime.shutdown         : [shutdown] Stopping all services
2023-11-20T07:48:34.490 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='acm:default', value='localstack.services.providers:acm', group='localstack.aws.provider')
2023-11-20T07:48:34.496 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='apigateway:default', value='localstack.services.providers:apigateway', group='localstack.aws.provider')
2023-11-20T07:48:34.496 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='cloudformation:default', value='localstack.services.providers:cloudformation', group='localstack.aws.provider')
2023-11-20T07:48:34.496 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='cloudwatch:default', value='localstack.services.providers:cloudwatch', group='localstack.aws.provider')
2023-11-20T07:48:34.496 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='config:default', value='localstack.services.providers:awsconfig', group='localstack.aws.provider')
2023-11-20T07:48:34.496 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='dynamodb:default', value='localstack.services.providers:dynamodb', group='localstack.aws.provider')
2023-11-20T07:48:34.497 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='dynamodbstreams:default', value='localstack.services.providers:dynamodbstreams', group='localstack.aws.provider')
2023-11-20T07:48:34.497 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='ec2:default', value='localstack.services.providers:ec2', group='localstack.aws.provider')
2023-11-20T07:48:34.497 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='es:default', value='localstack.services.providers:es', group='localstack.aws.provider')
2023-11-20T07:48:34.497 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='events:default', value='localstack.services.providers:events', group='localstack.aws.provider')
2023-11-20T07:48:34.497 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='firehose:default', value='localstack.services.providers:firehose', group='localstack.aws.provider')
2023-11-20T07:48:34.497 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='iam:default', value='localstack.services.providers:iam', group='localstack.aws.provider')
2023-11-20T07:48:34.497 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='kinesis:default', value='localstack.services.providers:kinesis', group='localstack.aws.provider')
2023-11-20T07:48:34.497 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='kms:default', value='localstack.services.providers:kms', group='localstack.aws.provider')
2023-11-20T07:48:34.497 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='lambda:asf', value='localstack.services.providers:lambda_asf', group='localstack.aws.provider')
2023-11-20T07:48:34.497 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='lambda:default', value='localstack.services.providers:lambda_', group='localstack.aws.provider')
2023-11-20T07:48:34.497 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='lambda:v2', value='localstack.services.providers:lambda_v2', group='localstack.aws.provider')
2023-11-20T07:48:34.498 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='logs:default', value='localstack.services.providers:logs', group='localstack.aws.provider')
2023-11-20T07:48:34.498 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='opensearch:default', value='localstack.services.providers:opensearch', group='localstack.aws.provider')
2023-11-20T07:48:34.498 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='redshift:default', value='localstack.services.providers:redshift', group='localstack.aws.provider')
2023-11-20T07:48:34.498 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='resource-groups:default', value='localstack.services.providers:resource_groups', group='localstack.aws.provider')
2023-11-20T07:48:34.498 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='resourcegroupstaggingapi:default', value='localstack.services.providers:resourcegroupstaggingapi', group='localstack.aws.provider')
2023-11-20T07:48:34.498 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='route53:default', value='localstack.services.providers:route53', group='localstack.aws.provider')
2023-11-20T07:48:34.498 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='route53resolver:default', value='localstack.services.providers:route53resolver', group='localstack.aws.provider')
2023-11-20T07:48:34.498 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='s3:asf', value='localstack.services.providers:s3_asf', group='localstack.aws.provider')
2023-11-20T07:48:34.498 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='s3:default', value='localstack.services.providers:s3', group='localstack.aws.provider')
2023-11-20T07:48:34.498 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='s3:legacy_v2', value='localstack.services.providers:s3_legacy_v2', group='localstack.aws.provider')
2023-11-20T07:48:34.498 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='s3:stream', value='localstack.services.providers:s3_stream', group='localstack.aws.provider')
2023-11-20T07:48:34.499 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='s3:v2', value='localstack.services.providers:s3_v2', group='localstack.aws.provider')
2023-11-20T07:48:34.499 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='s3:v3', value='localstack.services.providers:s3_v3', group='localstack.aws.provider')
2023-11-20T07:48:34.499 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='s3control:default', value='localstack.services.providers:s3control', group='localstack.aws.provider')
2023-11-20T07:48:34.499 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='scheduler:default', value='localstack.services.providers:scheduler', group='localstack.aws.provider')
2023-11-20T07:48:34.499 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='secretsmanager:default', value='localstack.services.providers:secretsmanager', group='localstack.aws.provider')
2023-11-20T07:48:34.499 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='ses:default', value='localstack.services.providers:ses', group='localstack.aws.provider')
2023-11-20T07:48:34.499 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='sns:default', value='localstack.services.providers:sns', group='localstack.aws.provider')
2023-11-20T07:48:34.499 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='sqs-query:default', value='localstack.services.providers:sqs_query', group='localstack.aws.provider')
2023-11-20T07:48:34.499 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='sqs:default', value='localstack.services.providers:sqs', group='localstack.aws.provider')
2023-11-20T07:48:34.499 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='ssm:default', value='localstack.services.providers:ssm', group='localstack.aws.provider')
2023-11-20T07:48:34.499 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='stepfunctions:default', value='localstack.services.providers:stepfunctions', group='localstack.aws.provider')
2023-11-20T07:48:34.499 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='stepfunctions:legacy', value='localstack.services.providers:stepfunctions_v1', group='localstack.aws.provider')
2023-11-20T07:48:34.500 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='stepfunctions:v1', value='localstack.services.providers:stepfunctions_legacy', group='localstack.aws.provider')
2023-11-20T07:48:34.500 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='stepfunctions:v2', value='localstack.services.providers:stepfunctions_v2', group='localstack.aws.provider')
2023-11-20T07:48:34.500 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='sts:default', value='localstack.services.providers:sts', group='localstack.aws.provider')
2023-11-20T07:48:34.500 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='support:default', value='localstack.services.providers:support', group='localstack.aws.provider')
2023-11-20T07:48:34.500 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='swf:default', value='localstack.services.providers:swf', group='localstack.aws.provider')
2023-11-20T07:48:34.500 DEBUG --- [  MainThread] stevedore.extension        : found extension EntryPoint(name='transcribe:default', value='localstack.services.providers:transcribe', group='localstack.aws.provider')
2023-11-20T07:48:34.500 DEBUG --- [  MainThread] localstack.services.infra  : [shutdown] Cleaning up resources ...
2023-11-20T07:48:34.500 DEBUG --- [  MainThread] localstack.utils.threads   : [shutdown] Done cleaning up threads / processes / tasks
2023-11-20T07:48:34.501 DEBUG --- [  MainThread] localstack.utils.run       : Executing command: rm -rf "/tmp/localstack"
2023-11-20T07:48:34.509 DEBUG --- [  MainThread] localstack.utils.run       : Executing command: rm -rf "/var/lib/localstack/tmp"
2023-11-20T07:48:34.511 DEBUG --- [  MainThread] localstack.services.infra  : [shutdown] Force shutdown, not waiting for infrastructure to shut down
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/code/localstack/localstack/runtime/main.py", line 28, in <module>
    main()
  File "/opt/code/localstack/localstack/runtime/main.py", line 20, in main
    infra.start_infra(asynchronous=False)
  File "/opt/code/localstack/localstack/services/infra.py", line 280, in start_infra
    raise e
  File "/opt/code/localstack/localstack/services/infra.py", line 258, in start_infra
    hooks.on_infra_start.run()
  File "/opt/code/localstack/localstack/runtime/hooks.py", line 64, in run_in_order
    fn_plugin(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/plugin/core.py", line 223, in __call__
    return self.fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/runtime/analytics.py", line 86, in _publish_config_as_analytics_event
    log.event("config", env_vars=env_vars, set_vars=present_env_vars)
  File "/opt/code/localstack/localstack/utils/analytics/logger.py", line 39, in event
    self._log(event, payload=payload)
  File "/opt/code/localstack/localstack/utils/analytics/logger.py", line 42, in _log
    self.handler.handle(Event(name=event, metadata=self._metadata(), payload=payload))
  File "/opt/code/localstack/localstack/utils/analytics/publisher.py", line 235, in handle
    self._start()
  File "/opt/code/localstack/localstack/utils/analytics/publisher.py", line 250, in _start
    start_worker_thread(self._do_start_retry)
  File "/opt/code/localstack/localstack/utils/threads.py", line 109, in start_worker_thread
    return start_thread(method, *args, _shutdown_hook=False, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/localstack/utils/threads.py", line 101, in start_thread
    thread.start()
  File "/usr/local/lib/python3.11/threading.py", line 964, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
LocalStack supervisor: localstack process (PID 15) returned with exit code 1
LocalStack supervisor: exiting
```

**Comment by peterabbott** [comment]
I should have tried this before, but it might be the Docker version. It gets further when bumping to `20.10.24`, we had been reluctant to upgrade as it causes headaches in other areas. Might be the nudge we need to figure out the other stuff
