### ISSUE TITLE
HTTP body could not be parsed as CBOR

### ISSUE THREAD

**Issue by lengyuewuhua** [localstack/localstack#9699]
When using apache flink and running the code locally, below error happened  in the localstack from docker console - 

localstack.aws.protocol.parser.ProtocolParserError: HTTP body could not be parsed as CBOR.
localstack-main  | 2023-11-21T05:35:06.808  INFO --- [   asgi_gw_2] localstack.request.http    : POST / => 500
localstack-main  | 2023-11-21T05:35:06.908 ERROR --- [   asgi_gw_6] l.aws.handlers.logging     : exception during call chain
localstack-main  | Traceback (most recent call last):
localstack-main  |   File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 862, in _parse_body_as_json
localstack-main  |     return cbor2.loads(body_contents)
localstack-main  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  | ValueError: year 55858 is out of range
localstack-main  |
localstack-main  | The above exception was the direct cause of the following exception:
localstack-main  |
localstack-main  | Traceback (most recent call last):
localstack-main  |   File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
localstack-main  |     handler(self, self.context, response)
localstack-main  |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 64, in __call__
localstack-main  |     return self.parse_and_enrich(context)
localstack-main  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/localstack/aws/handlers/service.py", line 77, in parse_and_enrich
localstack-main  |     operation, instance = parser.parse(context.request)
localstack-main  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 172, in wrapper
localstack-main  |     return func(*args, **kwargs)
localstack-main  |            ^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 903, in parse
localstack-main  |     final_parsed = self._do_parse(request, shape, uri_params)
localstack-main  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 915, in _do_parse
localstack-main  |     parsed = self._handle_json_body(request, shape, uri_params)
localstack-main  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/localstack/aws/protocol/parser.py", line 927, in _handle_json_body
localstack-main  |     parsed_json = self._parse_body_as_json(request)
localstack-main  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Program arguments - 
-aws.region us-east-1 -aws.endpoint localhost.localstack.cloud:4566 -kinesis.source.stream ExampleInputStream -kinesis.sink.stream ExampleOutputStream

Error at the client side - 

Caused by: java.lang.RuntimeException: Retries exceeded for getShardIterator operation - all 3 retry attempts failed.
	at org.apache.flink.streaming.connectors.kinesis.proxy.KinesisProxy.getShardIterator(KinesisProxy.java:409)
	at org.apache.flink.streaming.connectors.kinesis.proxy.KinesisProxy.getShardIterator(KinesisProxy.java:374)
	at org.apache.flink.streaming.connectors.kinesis.internals.publisher.polling.PollingRecordPublisher.getShardIterator(PollingRecordPublisher.java:195)
	at org.apache.flink.streaming.connectors.kinesis.internals.publisher.polling.PollingRecordPublisher.<init>(PollingRecordPublisher.java:96)
	at org.apache.flink.streaming.connectors.kinesis.internals.publisher.polling.PollingRecordPublisherFactory.create(PollingRecordPublisherFactory.java:86)
	at org.apache.flink.streaming.connectors.kinesis.internals.publisher.polling.PollingRecordPublisherFactory.create(PollingRecordPublisherFactory.java:34)
	at org.apache.flink.streaming.connectors.kinesis.internals.KinesisDataFetcher.createRecordPublisher(KinesisDataFetcher.java:497)
	at org.apache.flink.streaming.connectors.kinesis.internals.KinesisDataFetcher.createShardConsumer(KinesisDataFetcher.java:466)
	at org.apache.flink.streaming.connectors.kinesis.internals.KinesisDataFetcher.runFetcher(KinesisDataFetcher.java:591)
	at org.apache.flink.streaming.connectors.kinesis.FlinkKinesisConsumer.run(FlinkKinesisConsumer.java:392)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:332)

**Comment by alexrashed** [comment]
Hi @lengyuewuhua!
Would it be possible to provide a minimum reproducible sample for this issue?
We have some tests in place which try to cover the CBOR protocol for Kinesis, but it always depends on the client (i.e. your flink code) if it sends the request in a specific manner. These cases are hard to debug without a specific reproducible client environment...
Thanks!
