### ISSUE TITLE
bug: MySql container is created then destroyed immediately when creating RDS instance

### ISSUE THREAD

**Issue by Timmoth** [localstack/localstack#9770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to create a MySql RDS instance the newly created community MySql container is destroyed immediately and so the database does not work.

(Just to clarify the localstack container is created and stays up and it does seem to create the MySql container, but it is removed too quickly to even screen shot / inspect)

Further output:
```
localstack-main  | 2023-11-29T17:04:51.227  INFO --- [functhread14] l.s.rds.engine_mysql       : Starting MySQL server on port 4510 (backend port 44748) - database "sb_stage_clone", user "root"
localstack-main  | 2023-11-29T17:04:57.443  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS rds.CreateDBInstance => 200
localstack-main  | {
localstack-main  |     "DBInstance": {
localstack-main  |         "DBInstanceIdentifier": "mydb",
localstack-main  |         "DBInstanceClass": "db.t3.small",
localstack-main  |         "Engine": "mysql",
localstack-main  |         "DBInstanceStatus": "creating",
localstack-main  |         "MasterUsername": "root",
localstack-main  |         "DBName": "sb_stage_clone",
localstack-main  |         "Endpoint": {
localstack-main  |             "Address": "localhost.localstack.cloud",
localstack-main  |             "Port": 4510
localstack-main  |         },
localstack-main  |         "AllocatedStorage": 20,
localstack-main  |         "InstanceCreateTime": "2023-11-29T17:04:49.589000Z",
localstack-main  |         "PreferredBackupWindow": "13:14-13:44",
localstack-main  |         "BackupRetentionPeriod": 1,
localstack-main  |         "DBSecurityGroups": [],
localstack-main  |         "VpcSecurityGroups": [
localstack-main  |             {
localstack-main  |                 "VpcSecurityGroupId": "sg-8c1fd554c7d01f0df",
localstack-main  |                 "Status": "active"
localstack-main  |             }
localstack-main  |         ],
localstack-main  |         "DBParameterGroups": [
localstack-main  |             {
localstack-main  |                 "DBParameterGroupName": "default.mysql5.6",
localstack-main  |                 "ParameterApplyStatus": "in-sync"
localstack-main  |             }
localstack-main  |         ],
localstack-main  |         "AvailabilityZone": "us-east-1a",
localstack-main  |         "PreferredMaintenanceWindow": "wed:06:38-wed:07:08",
localstack-main  |         "MultiAZ": false,
localstack-main  |         "EngineVersion": "5.6.21",
localstack-main  |         "AutoMinorVersionUpgrade": false,
localstack-main  |         "ReadReplicaDBInstanceIdentifiers": [],
localstack-main  |         "LicenseModel": "license-included",
localstack-main  |         "OptionGroupMemberships": [
localstack-main  |             {
localstack-main  |                 "OptionGroupName": "default.mysql5.6",
localstack-main  |                 "Status": "in-sync"
localstack-main  |             }
localstack-main  |         ],
localstack-main  |         "PubliclyAccessible": false,
localstack-main  |         "StatusInfos": [],
localstack-main  |         "StorageType": "gp2",
localstack-main  |         "DbInstancePort": 4510,
localstack-main  |         "StorageEncrypted": false,
localstack-main  |         "DbiResourceId": "db-B5BAB4CD",
localstack-main  |         "CopyTagsToSnapshot": false,
localstack-main  |         "DBInstanceArn": "arn:aws:rds:us-east-1:000000000000:db:mydb",
localstack-main  |         "IAMDatabaseAuthenticationEnabled": false,
localstack-main  |         "EnabledCloudwatchLogsExports": [],
localstack-main  |         "DeletionProtection": false,
localstack-main  |         "TagList": []
localstack-main  |     }
localstack-main  | }
localstack-main  | 2023-11-29T17:04:57.904  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS rds.DescribeDBInstances => 200
localstack-main  | 2023-11-29T17:04:58.296  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS rds.DescribeDBInstances => 200
localstack-main  | 4510
localstack-main  | localhost.localstack.cloud
...
localstack-main  | 2023-11-29T16:56:26.691  INFO --- [functhread44] localstack.utils.threads   : Thread run method <function start_tcp_proxy.<locals>.<lambda> at 0x7ff340f26700>(None) failed: [Errno 111] Connection refused Traceback (most recent call last):
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/threads.py", line 58, in run
localstack-main  |     result = self.func(self.params, **kwargs)
localstack-main  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/server/proxy_server.py", line 73, in <lambda>
localstack-main  |     start_worker_thread(lambda *args, _thread: handle_request(src_socket, _thread))
localstack-main  |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/server/proxy_server.py", line 44, in handle_request
localstack-main  |     s_dst.connect(ip_to_tuple(dst))
localstack-main  | ConnectionRefusedError: [Errno 111] Connection refused
localstack-main  |
localstack-main  | 2023-11-29T16:57:40.762  WARN --- [functhread14] l.services.rds.db_utils    : Unable to startup DB instance:  Traceback (most recent call last):
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/api/client.py", line 268, in _raise_for_status
localstack-main  |     response.raise_for_status()
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
localstack-main  |     raise HTTPError(http_error_msg, response=self)
localstack-main  | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.43/containers/ls-mysql-ff5862d4/json
localstack-main  |
localstack-main  | The above exception was the direct cause of the following exception:
localstack-main  |
localstack-main  | Traceback (most recent call last):
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/container_utils/docker_sdk_client.py", line 792, in exec_in_container
localstack-main  |     container: Container = self.client().containers.get(container_name_or_id)
localstack-main  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/models/containers.py", line 936, in get
localstack-main  |     resp = self.client.api.inspect_container(container_id)
localstack-main  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/utils/decorators.py", line 19, in wrapped
localstack-main  |     return f(self, resource_id, *args, **kwargs)
localstack-main  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/api/container.py", line 784, in inspect_container
localstack-main  |     return self._result(
localstack-main  |            ^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/api/client.py", line 274, in _result
localstack-main  |     self._raise_for_status(response)
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/api/client.py", line 270, in _raise_for_status
localstack-main  |     raise create_api_error_from_http_exception(e) from e
localstack-main  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
localstack-main  |     raise cls(e, response=response, explanation=explanation) from e
localstack-main  | docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.43/containers/ls-mysql-ff5862d4/json: Not Found ("No such container: ls-mysql-ff5862d4")
localstack-main  |
localstack-main  | The above exception was the direct cause of the following exception:
localstack-main  |
localstack-main  | Traceback (most recent call last):
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/rds/db_utils.py.enc", line 60, in B
localstack-main  |     try:A and A(status='creating');G=F.start_db_instance(*E,**C);A and A(status=_D);LOG.debug('DB started successfully.');return G
localstack-main  |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/rds/engine_mysql.py.enc", line 29, in start_db_instance
localstack-main  |     retry(S,sleep=3,retries=30,sleep_before=2);D.stop_collecting_logs();return O
localstack-main  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/sync.py", line 62, in retry
localstack-main  |     raise raise_error
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/sync.py", line 58, in retry
localstack-main  |     return function(**kwargs)
localstack-main  |            ^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/rds/engine_mysql.py.enc", line 28, in S
localstack-main  |     def S():A="mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'";A=['bash','-c',A];assert DOCKER_CLIENT.exec_in_container(K,command=A)
localstack-main  |                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/container_utils/docker_sdk_client.py", line 834, in exec_in_container
localstack-main  |     raise ContainerException() from e
localstack-main  | localstack.utils.container_utils.container_client.ContainerException
localstack-main  |  stdout: 'None' stderr: 'None'
```

### Expected Behavior

I expect the MySql container to stay up for as long as the localstack container exists and be able to query it without any errors in the console.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

./Dockerfile
```
FROM localstack/localstack-pro:latest
RUN curl -L -o /usr/bin/jq https://github.com/jqlang/jq/releases/download/jq-1.6/jq-linux64
RUN chmod u+x /usr/bin/jq
```

./docker-compose.yml
```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack-main}"
    image: custom-localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_AUTH_TOKEN="<Auth Token>"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
```

./scripts/init-aws.sh
```
#!/usr/bin/env bash
 
awslocal rds create-db-instance \
    --master-username root \
    --master-user-password root \
    --db-instance-identifier mydb \
	--engine mysql \
    --db-name sb_stage_clone \
    --db-instance-class db.t3.small
	
PORT=$(awslocal rds describe-db-instances --db-instance-identifier mydb | jq -r ".DBInstances[0].Endpoint.Port")
HOST=$(awslocal rds describe-db-instances --db-instance-identifier mydb | jq -r ".DBInstances[0].Endpoint.Address")

echo $PORT
echo $HOST
```

Build:
```
docker build -t custom-localstack .
```

Run:
```
docker-compose up
```

### Environment

```markdown
- OS: Windows 11
- LocalStack: localstack/localstack-pro:latest
```

**Comment by Timmoth** [comment]
Some progress this morning. 
It looks like I forgot to create the cluster, I didn't think it was necessary since this example doesn't have a '--db-cluster-identifier' parameter.

![image](https://github.com/localstack/localstack/assets/21103223/47f58486-5e9a-4331-a71b-224b6d797f9f)

Also I had to use 'aurora-mysql' as the database engine, it wouldn't work with just 'mysql' set for the engine. (I'm not sure the docs mention this any where)

My new script looks like this: 

```
awslocal rds create-db-cluster \
    --db-cluster-identifier db1 \
    --engine aurora-mysql \
    --database-name sb_stage_clone \
    --master-username root \
    --master-user-password root

awslocal rds create-db-instance \
    --db-instance-identifier db1-instance \
    --db-cluster-identifier db1 \
    --engine aurora-mysql \
    --db-instance-class db.t3.large
```

The spawned mysql container now stays up, so thats an improvement, I just need to figure out the connection string so my app can connect to it from the host.

**Comment by alexrashed** [comment]
Hi @Timmoth!
Seems like your issue has already been resolved? Or do you have another concrete issue?

**Comment by Timmoth** [comment]
Hey @alexrashed, I think I've partially resolved the issue. 

I believe the issue with the container stopping immediately was due to me using:
```
    --master-username root \
    --master-user-password root
```
It seems swapping just those lines to:
```
    --master-username myuser \
    --master-user-password mypassword
```

Allows the container to start, but I'm still unable to connect. When I try I still get the huge wall of cryptic errors in the console:

```
localstack-main  | 2023-11-30T09:25:24.893  INFO --- [functhread54] localstack.utils.threads   : Thread run method <function start_tcp_proxy.<locals>.<lambda> at 0x7fd048b6dc60>(None) failed: [Errno 110] Connection timed out Traceback (most recent call last):
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/threads.py", line 58, in run
localstack-main  |     result = self.func(self.params, **kwargs)
localstack-main  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/server/proxy_server.py", line 73, in <lambda>
localstack-main  |     start_worker_thread(lambda *args, _thread: handle_request(src_socket, _thread))
localstack-main  |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/server/proxy_server.py", line 44, in handle_request
localstack-main  |     s_dst.connect(ip_to_tuple(dst))
localstack-main  | TimeoutError: [Errno 110] Connection timed out
localstack-main  |
localstack-main  | 2023-11-30T09:25:55.436  INFO --- [   asgi_gw_0] localstack.request.http    : GET / => 200
localstack-main  | 2023-11-30T09:25:55.546  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.ListObjects => 404 (NoSuchBucket)
localstack-main  | 2023-11-30T09:26:26.456  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS ssm.GetParametersByPath => 200
localstack-main  | 2023-11-30T09:27:38.012  INFO --- [functhread70] localstack.utils.threads   : Thread run method <function start_tcp_proxy.<locals>.<lambda> at 0x7fd048b6fba0>(None) failed: [Errno 110] Connection timed out Traceback (most recent call last):
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/threads.py", line 58, in run
localstack-main  |     result = self.func(self.params, **kwargs)
localstack-main  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/server/proxy_server.py", line 73, in <lambda>
localstack-main  |     start_worker_thread(lambda *args, _thread: handle_request(src_socket, _thread))
localstack-main  |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/server/proxy_server.py", line 44, in handle_request
localstack-main  |     s_dst.connect(ip_to_tuple(dst))
localstack-main  | TimeoutError: [Errno 110] Connection timed out
localstack-main  |
localstack-main  | 2023-11-30T09:27:48.252  INFO --- [functhread72] localstack.utils.threads   : Thread run method <function start_tcp_proxy.<locals>.<lambda> at 0x7fd048b6fce0>(None) failed: [Errno 110] Connection timed out Traceback (most recent call last):
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/threads.py", line 58, in run
localstack-main  |     result = self.func(self.params, **kwargs)
localstack-main  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/server/proxy_server.py", line 73, in <lambda>
localstack-main  |     start_worker_thread(lambda *args, _thread: handle_request(src_socket, _thread))
localstack-main  |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/server/proxy_server.py", line 44, in handle_request
localstack-main  |     s_dst.connect(ip_to_tuple(dst))
localstack-main  | TimeoutError: [Errno 110] Connection timed out
localstack-main  |
localstack-main  | 2023-11-30T09:28:39.452  INFO --- [functhread80] localstack.utils.threads   : Thread run method <function start_tcp_proxy.<locals>.<lambda> at 0x7fd0885cc900>(None) failed: [Errno 110] Connection timed out Traceback (most recent call last):
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/threads.py", line 58, in run
localstack-main  |     result = self.func(self.params, **kwargs)
localstack-main  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/server/proxy_server.py", line 73, in <lambda>
localstack-main  |     start_worker_thread(lambda *args, _thread: handle_request(src_socket, _thread))
localstack-main  |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/server/proxy_server.py", line 44, in handle_request
localstack-main  |     s_dst.connect(ip_to_tuple(dst))
localstack-main  | TimeoutError: [Errno 110] Connection timed out
```

Any direction here would be greatly appreciated!

**Comment by Timmoth** [comment]
Adding 'network_mode: bridge' to the docker-compose got rid of those errors and i've now been able to successfully connect to the database. 

The final config:
docker-compose.yml
```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack-main}"
    image: custom-localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_AUTH_TOKEN="<TOKEN>"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
```
 init-aws.sh
```
#!/usr/bin/env bash
 
# DB
awslocal rds create-db-cluster \
    --db-cluster-identifier db1 \
    --engine aurora-mysql \
    --database-name test \
    --master-username myuser \
    --master-user-password mypassword

awslocal rds create-db-instance \
    --db-instance-identifier db1-instance \
    --db-cluster-identifier db1 \
    --engine aurora-mysql \
    --db-instance-class db.t3.large
	
PORT=$(awslocal rds describe-db-instances --db-instance-identifier db1-instance | jq -r ".DBInstances[0].Endpoint.Port")
HOST=$(awslocal rds describe-db-instances --db-instance-identifier db1-instance | jq -r ".DBInstances[0].Endpoint.Address")

awslocal ssm put-parameter \
    --name "/api/local/ConnectionStrings/ConnectionString" \
    --value "Server=$HOST;Port=$PORT;User ID=myuser;Password=mypassword;Database=test;SSL Mode=None;Persist Security Info=True;AllowPublicKeyRetrieval=True;" \
    --type String
```

The bits I couldn't find in the documentation:
- You must create a cluster to create a db instance
- Use 'aurora-mysql' as the db engine
- Add 'network_mode: bridge' to the docker compose otherwise connections to the db time out
- You cannot use 'root' as the master-username or master-user-password
- For EFCore to connect you must add 'AllowPublicKeyRetrieval=True;' to the connection string.

Since its now working I'm happy for you to close, but I would really appreciate validation on the points I've listed above.
