### ISSUE TITLE
SQS cannot be used unless created on the us-east-1 region when using aws-sdk for Node - Inaccessible host: '127.0.0.1' at port '4566' (only when using LocalStack, it works on production)

### ISSUE THREAD

**Issue by kazazor** [localstack/localstack#9791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an SQS entity is being created in a region OTHER than `us-east-1` the following happens when trying to receive messages:
- Using `awslocal` - works as expected and the message is being returned.
```
awslocal sqs receive-message --queue-url http://localhost:4566/000000000000/S3AssetsNotificationQueue-development
```
- Using `aws-sdk` for Node - The error: `Inaccessible host: '127.0.0.1' at port '4566'` is being returned
```js
{
  name: "S3AssetsNotificationQueue-development",
  queueUrl: "http://localhost:4566/000000000000/S3AssetsNotificationQueue-development",
  region: "us-west-2"
 }
```

# Why is that not just a problem for aws-sdk for Node?
This is happening only with LocalStack. In production, we see no problems with having the SQS in another region.
So something is related to the way LocalStack works and its compatibility with the SDK.
As this package is one of the most highly used all around, LocalStack should have high interest solving this issue.

# Did I find something similar in the issues?
Kind of. I saw this comment from 8 months ago: https://github.com/localstack/localstack/issues/7720#issuecomment-1449579117
It seems the subject got left behind as it wasn't related to the original title of the issue.

# More info
- I actually use `@ssut/nestjs-sqs` which uses `aws-sdk` but I also verified it with just using the sdk.
- I tested the same thing only with `us-east-1` and then everything worked.
- I have localstack DNS enabled using this docker-compose settings (and I know it works as expected as S3 uploads using it works just fine)
```
localstack:
    image: localstack/localstack-pro
    restart: always
    profiles: ["local"]
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
      - "127.0.0.1:53:53" # DNS config (required for Pro) - https://docs.localstack.cloud/user-guide/tools/transparent-endpoint-injection/
      - "127.0.0.1:53:53/udp" # DNS config (required for Pro) - https://docs.localstack.cloud/user-guide/tools/transparent-endpoint-injection/
      - "127.0.0.1:443:443" # LocalStack HTTPS Gateway (required for Pro)
    environment:
      DEBUG: 1 # Change to 0 if you would like to have less noise in the LocalStack container's logs
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN} # Add it to your .env file at the root of the project
      PERSISTENCE: 1
      ENFORCE_IAM: 0 # https://docs.localstack.cloud/references/configuration/#iam
      EXTRA_CORS_ALLOWED_ORIGINS: "*" # https://docs.localstack.cloud/references/configuration/#security
      DOCKER_HOST: unix:///var/run/docker.sock
      DNS_LOCAL_NAME_PATTERNS: ".*(secretsmanager).*.amazonaws.com" # The services that we would like their requests be redirected to AWS instead of Localstack. This is done via https://docs.localstack.cloud/user-guide/tools/dns-server/#skip-localstack-dns-resolution
      DNS_SERVER: 8.8.8.8 # DNS fallback server, all the non AWS requests will be forwarded to it
      DNS_ADDRESS: 127.0.0.1 # The LocalStack local DNS server address
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock" # Enable to use services that use external docker images, like Lambda functions
```

### Expected Behavior

Both `awslocal` and when using `aws-sdk` for Node should work without throwing any exceptions.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Just run the docker-compose file I shared
2. Create an SQS queue in a region not in `us-east-1`
3. Try accessing it using the Node aws-sdk package

### Environment

```markdown
- OS: macOS 14.1.1
- LocalStack: latest docker image
```

**Comment by kazazor** [comment]
Updating once again:
One time, you run your code, and it works, and then it doesn't work again. And as mentioned, using `awslocal` it does work.

**Comment by kazazor** [comment]
You can reproduce it with aws-sdk V2 (this is what we use, but looking online it's also happening on V3):
```js
import { SQS } from "aws-sdk";

// Set up AWS SQS client
const sqs = new SQS({
  region: "us-east-1", // Replace with your AWS region, e.g., 'us-east-1'
  accessKeyId: "test", // Replace with your AWS access key ID
  secretAccessKey: "test" // Replace with your AWS secret access key
});

// Define the SQS queue URL
const queueUrl =
  "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/S3AssetsNotificationQueue-development"; // Replace with your SQS queue URL

// Function to send an SQS message
async function sendMessage(message: string): Promise<void> {
  const params = {
    MessageBody: message,
    QueueUrl: queueUrl
  };

  try {
    const result = await sqs.sendMessage(params).promise();
    console.log("Message sent:", result.MessageId);
  } catch (error) {
    console.error("Error sending message:", error);
  }
}

// Function to receive SQS messages
async function receiveMessages(): Promise<void> {
  const params = {
    QueueUrl: queueUrl,
    MaxNumberOfMessages: 1,
    VisibilityTimeout: 10,
    WaitTimeSeconds: 10
  };

  try {
    const result = await sqs.receiveMessage(params).promise();

    if (result.Messages && result.Messages.length > 0) {
      const message = result.Messages[0];
      console.log("Received message:", message.Body);

      // Delete the received message from the queue
      await sqs
        .deleteMessage({
          QueueUrl: queueUrl,
          ReceiptHandle: message.ReceiptHandle!
        })
        .promise();
    } else {
      console.log("No messages available");
    }
  } catch (error) {
    console.error("Error receiving messages:", error);
  }
}

// Example usage
(async () => {
  const messageToSend = "Hello, SQS with v2 SDK!";
  await sendMessage(messageToSend);

  // Wait for a moment to ensure the message is processed
  await new Promise(resolve => setTimeout(resolve, 2000));

  await receiveMessages();
})();
```
Which results with:
```js
Error sending message: UnknownEndpoint: Inaccessible host: `sqs.us-east-1.localhost.localstack.cloud' at port `4566'. This service may not be available in the `us-east-1' region.
    at Request.ENOTFOUND_ERROR (/Users/orkazaz/Development/api/node_modules/aws-sdk/lib/event_listeners.js:611:46)
    at Request.callListeners (/Users/orkazaz/Development/api/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/orkazaz/Development/api/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/orkazaz/Development/api/node_modules/aws-sdk/lib/request.js:686:14)
    at error (/Users/orkazaz/Development/api/node_modules/aws-sdk/lib/event_listeners.js:443:22)
    at ClientRequest.<anonymous> (/Users/orkazaz/Development/api/node_modules/aws-sdk/lib/http/node.js:99:9)
    at ClientRequest.emit (node:events:517:28)
    at ClientRequest.emit (node:domain:489:12)
    at Socket.socketErrorListener (node:_http_client:501:9)
    at Socket.emit (node:events:517:28) {
  code: 'UnknownEndpoint',
  region: 'us-east-1',
  hostname: 'sqs.us-east-1.localhost.localstack.cloud',
  retryable: true,
  originalError: Error: connect ECONNREFUSED ::1:4566
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -61,
    code: 'NetworkingError',
    syscall: 'connect',
    address: '::1',
    port: 4566,
    region: 'us-east-1',
    hostname: 'sqs.us-east-1.localhost.localstack.cloud',
    retryable: true,
    time: 2023-12-04T12:48:10.268Z
  },
  time: 2023-12-04T12:48:10.268Z
}
Error receiving messages: UnknownEndpoint: Inaccessible host: `sqs.us-east-1.localhost.localstack.cloud' at port `4566'. This service may not be available in the `us-east-1' region.
    at Request.ENOTFOUND_ERROR (/Users/orkazaz/Development/api/node_modules/aws-sdk/lib/event_listeners.js:611:46)
    at Request.callListeners (/Users/orkazaz/Development/api/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/orkazaz/Development/api/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/orkazaz/Development/api/node_modules/aws-sdk/lib/request.js:686:14)
    at error (/Users/orkazaz/Development/api/node_modules/aws-sdk/lib/event_listeners.js:443:22)
    at ClientRequest.<anonymous> (/Users/orkazaz/Development/api/node_modules/aws-sdk/lib/http/node.js:99:9)
    at ClientRequest.emit (node:events:517:28)
    at ClientRequest.emit (node:domain:489:12)
    at Socket.socketErrorListener (node:_http_client:501:9)
    at Socket.emit (node:events:517:28) {
  code: 'UnknownEndpoint',
  region: 'us-east-1',
  hostname: 'sqs.us-east-1.localhost.localstack.cloud',
  retryable: true,
  originalError: Error: connect ECONNREFUSED ::1:4566
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -61,
    code: 'NetworkingError',
    syscall: 'connect',
    address: '::1',
    port: 4566,
    region: 'us-east-1',
    hostname: 'sqs.us-east-1.localhost.localstack.cloud',
    retryable: true,
    time: 2023-12-04T12:48:12.402Z
  },
  time: 2023-12-04T12:48:12.402Z
}
```

**Comment by kazazor** [comment]
In my case the problem got resolved.
The issue is adding 127.0.0.1 to the ports in docker-compose.

It uses IPv6 which local stack does not support.
The documentation about it needs to be much clearer IMO. Both in the network troubleshooting page and the GATEWAY_LISTEN description.
Even if it's a section only around macOS

**Comment by jacekgajek** [comment]
I also experience this issue on [3.4.0](https://hub.docker.com/layers/localstack/localstack/3.4.0/images/sha256-21afce828890539367762975918654e45336e3b024571d98b1bf3b0791ef04b3?context=explore)

Even after creating a queue in `eu-central-1`, I must set region to `us-east-1` to get queues with SQS ListQueues request.

**Comment by fenric** [comment]
MacOS: 12.7.5
LocalStack Desktop: 1.0.7

The issue is still relevant. For local development, I use us-east-1, it's not a problem, but still :)

**Comment by stephenmontgomery** [comment]
Yes getting this here. 

MacOS: 15.5
LocalStack version: 4.5.0

```
UnknownEndpoint: Inaccessible host: `sqs.eu-central-1.localstack.localstack.cloud' at port `undefined'. This service may not be available in the `eu-central-1' region.
    at Request.ENOTFOUND_ERROR (/usr/app/node_modules/aws-sdk/lib/event_listeners.js:612:46)
    at Request.callListeners (/usr/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/app/node_modules/aws-sdk/lib/request.js:686:14)
    at error (/usr/app/node_modules/aws-sdk/lib/event_listeners.js:443:22)
    at ClientRequest.<anonymous> (/usr/app/node_modules/aws-sdk/lib/http/node.js:100:9)
    at ClientRequest.emit (node:events:390:28)
    at ClientRequest.emit (node:domain:475:12)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28) {
  code: 'UnknownEndpoint',
  region: 'eu-central-1',
  hostname: 'sqs.eu-central-1.localstack.localstack.cloud',
  retryable: true,
  originalError: Error: getaddrinfo ENOTFOUND sqs.eu-central-1.localstack.localstack.cloud
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
    errno: -3008,
    code: 'NetworkingError',
    syscall: 'getaddrinfo',
    hostname: 'sqs.eu-central-1.localstack.localstack.cloud',
    region: 'eu-central-1',
    retryable: true,
    time: 2025-06-20T13:16:46.442Z
  },
  time: 2025-06-20T13:16:46.442Z
}
```

```
$ curl http://localhost:4566/_localstack/health
{"services": {"acm": "disabled", "apigateway": "disabled", "cloudformation": "disabled", "cloudwatch": "running", "config": "disabled", "dynamodb": "running", "dynamodbstreams": "available", "ec2": "disabled", "es": "disabled", "events": "running", "firehose": "disabled", "iam": "running", "kinesis": "available", "kms": "running", "lambda": "running", "logs": "disabled", "opensearch": "disabled", "redshift": "disabled", "resource-groups": "disabled", "resourcegroupstaggingapi": "disabled", "route53": "disabled", "route53resolver": "disabled", "s3": "running", "s3control": "disabled", "scheduler": "disabled", "secretsmanager": "disabled", "ses": "disabled", "sns": "running", "sqs": "running", "ssm": "running", "stepfunctions": "running", "sts": "running", "support": "disabled", "swf": "disabled", "transcribe": "disabled"}, "edition": "community", "version": "4.5.0"}SMONTGOMERY-L2369NCV4Q:~/git-other/cn-mono/local-env
```

**Comment by stephenmontgomery** [comment]
What does "not planned" mean?

**Comment by JGitHub01** [comment]
> In my case the problem got resolved. The issue is adding 127.0.0.1 to the ports in docker-compose.
> 
> It uses IPv6 which local stack does not support. The documentation about it needs to be much clearer IMO. Both in the network troubleshooting page and the GATEWAY_LISTEN description. Even if it's a section only around macOS.
> 
> Being 100% transparent here, I did end up doing it on us-east-1, I might be able to revert it now but maybe there is a problem still that got masked here.
> 
> So I would still just verify that everything works as expected on other regions, just because others mentioned it as well in the issue I linked to in the description.

Can you share your docker-compose.yml to show how you resolved it? Thanks.
