### ISSUE TITLE
bug: NodeJS - Hot reload - Encountered an exception while handling callback

### ISSUE THREAD

**Issue by exasky** [localstack/localstack#9793]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I deploy my infra with serverless-localstack 1.1.2 (serverless 3.38.0)
I have an SQS where I push a message. This SQS is linked to a nodeJS lambda.

Most of the time (but not always), after hot reloading my lambda, I got this error :
```
localstack  | 2023-12-04T11:06:24.284 DEBUG --- [  Thread-161] l.s.l.i.version_manager    : Got logs for invocation 'c6300d03-0469-4ecd-9310-4af131ce201c'
localstack  | 2023-12-04T11:06:24.284 DEBUG --- [  Thread-161] l.s.l.i.version_manager    : > START RequestId: c6300d03-0469-4ecd-9310-4af131ce201c Version: $LATEST
localstack  | 2023-12-04T11:06:24.285 DEBUG --- [  Thread-161] l.s.l.i.version_manager    : > END RequestId: c6300d03-0469-4ecd-9310-4af131ce201c
localstack  | 2023-12-04T11:06:24.285 DEBUG --- [  Thread-161] l.s.l.i.version_manager    : > REPORT RequestId: c6300d03-0469-4ecd-9310-4af131ce201c        Duration: 248.64 ms     Billed Duration: 249 ms Memory Size: 1024 MB    Max Memory Used: 1024 MB
localstack  | 2023-12-04T11:06:24.285 DEBUG --- [  Thread-161] l.s.l.e.adapters           : Encountered an exception while handling callback
localstack  | Traceback (most recent call last):
localstack  |   File "/opt/code/localstack/localstack/services/lambda_/event_source_listeners/adapters.py", line 99, in _invoke
localstack  |     result=to_str(json.loads(result.payload)),
localstack  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack  |   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
localstack  |     return _default_decoder.decode(s)
localstack  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack  |   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
localstack  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
localstack  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack  |   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
localstack  |     raise JSONDecodeError("Expecting value", s, err.value) from None
localstack  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Sometimes, the execution is ok.

I'm using Localstack/serverless Hot reload:
LAMBDA_MOUNT_CWD=/${HOME_FOLDER} serverless deploy --force --stage local --verbose

### Expected Behavior

After hot reloading nodeJS lambda, this lambda should be executed.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
docker-compose.yml

```
version: '3.8'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:3.0.2
    environment:
      - SERVICES=sqs,lambda,s3,cloudformation,logs,iam
      - DEBUG=1
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - DISABLE_CORS_CHECKS=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_LIMITS_CONCURRENT_EXECUTIONS=1
      - NODE_TSL_REJECT_UNAUTHORIZED=0

    ports:
      - '4566-4583:4566-4583'
      - '8000:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '${HOME_FOLDER}:${HOME_FOLDER}'
```

serverless.yml

```
service: main
frameworkVersion: '3'

plugins:
  - serverless-localstack

provider:
  name: aws
  region: us-east-1
  stage: local

custom:
  localstack:
    stages:
      - local
    host: http://localhost 
    edgePort: 4566
    autostart: true 
    debug: true
    lambda:
      mountCode: True

resources:
  Resources:
    MySqs:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: MySqs
        VisibilityTimeout: 30
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [MyDlq, Arn]
          maxReceiveCount: 1
    MyDlq:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: MyDlq

functions:
  MyFunction:
    runtime: nodejs16.x
    handler: myFunction/dist/index.handler
    timeout: 25
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MySqs
              - Arn
```

Lambda Code:

```
import { Handler } from 'aws-lambda';
import { SQSClient, GetQueueUrlCommand } from '@aws-sdk/client-sqs';
const sqsEndpoint = process.env['AWS_ENDPOINT_URL'];
const region = process.env['AWS_REGION'];

export const handler: Handler = async (event: any) => {
  console.log('START');
  console.log('env', process.env);
  const sqsClient = new SQSClient({
    endpoint: sqsEndpoint,
    region: region,
  });
  const sqsUrl= await sqsClient.send(
    new GetQueueUrlCommand({ QueueName: 'MySqs' }),
  );
  console.log('sqsUrl', sqsUrl);
  return null;
}
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    N/A

### Environment

```markdown
- OS: Amazon Linux 2
- LocalStack: 3.0.2 Docker
```

**Comment by joe4dev** [comment]
Hi @exasky . The code causing the abovementioned error is now gone 🧹 and replaced with a new Lambda Event Source Mapping implementation. It's worth giving it another try 🚀 

Check out our new Lambda event source mapping (ESM) implementation in [LocalStack v4](https://blog.localstack.cloud/announcing-localstack-40-general-availability/) offering better functional and non-functional support for ESM 🚀 . The behavioral coverage documentation provides more details for your use case https://docs.localstack.cloud/user-guide/aws/lambda/#lambda-event-source-mappings

Feel free to open another issue or share your feedback if you experience any challenges👂
