### ISSUE TITLE
bug: Unable to start when there is no internet connection

### ISSUE THREAD

**Issue by AntonioCS** [localstack/localstack#9794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hey,

So I have the following in a `docker-compose.yml` file:
```
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=1
    volumes:
      - "${CUSHON_LOCALSTACK_VOLUME_DIR:-./localstack/volume}:/var/lib/localstack"
      - "${CUSHON_LOCALSTACK_READY_DIR:-./localstack/init/ready.d}:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

To start I just do `docker-compose up`. If I have an internet connection there is no issue but sometimes when I don't have an internet connection the container doesn't start and I see the following in the `docker-compose logs` of the container:
```
 2023-12-04T11:02:41.119  WARN --- [  MainThread] localstack.dns.server      : Error starting the DNS server: No upstream dns server found.
 2023-12-04T11:03:08.177  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "start_runtime_components" took 27041.13ms
 Unexpected exception while starting infrastructure: gave up waiting for edge server on 0.0.0.0:4566 Traceback (most recent call last):
   File "/opt/code/localstack/localstack/services/infra.py", line 261, in start_infra
     thread = do_start_infra(asynchronous, apis, is_in_docker)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/localstack/services/infra.py", line 356, in do_start_infra
     thread = start_runtime_components()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 81, in wrapped
     return f(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/localstack/services/infra.py", line 349, in start_runtime_components
     raise TimeoutError(
 TimeoutError: gave up waiting for edge server on 0.0.0.0:4566
 
 2023-12-04T11:03:23.196  INFO --- [-functhread2] localstack.utils.http      : Unable to download Github artifact from from https://cdn.jsdelivr.net/gh/localstack/localstack-artifacts@master/local-certs/server.key to /var/lib/localstack/cache/server.test.pem: MyHTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/localstack/localstack-artifacts@master/local-certs/server.key (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8e52b14bd0>: Failed to resolve 'cdn.jsdelivr.net' ([Errno -2] Name or service not known)")) Traceback (most recent call last):
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
     sock = connection.create_connection(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection
     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 socket.gaierror: [Errno -2] Name or service not known
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen
     response = self._make_request(
                ^^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 492, in _make_request
     raise new_e
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 468, in _make_request
     self._validate_conn(conn)
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
     conn.connect()
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 611, in connect
     self.sock = sock = self._new_conn()
                        ^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 210, in _new_conn
     raise NameResolutionError(self.host, self, e) from e
 urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f8e52b14bd0>: Failed to resolve 'cdn.jsdelivr.net' ([Errno -2] Name or service not known)
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
     resp = conn.urlopen(
            ^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 845, in urlopen
     retries = retries.increment(
               ^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 urllib3.exceptions.MaxRetryError: MyHTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/localstack/localstack-artifacts@master/local-certs/server.key (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8e52b14bd0>: Failed to resolve 'cdn.jsdelivr.net' ([Errno -2] Name or service not known)"))
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/opt/code/localstack/localstack/utils/http.py", line 264, in do_download
     download(download_url, target_file, timeout=timeout, request_headers=request_headers)
   File "/opt/code/localstack/localstack/utils/http.py", line 198, in download
     r = s.get(url, stream=True, verify=_verify, timeout=timeout, headers=request_headers)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
     return self.request("GET", url, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
     resp = self.send(prep, **send_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
     r = adapter.send(request, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
     raise ConnectionError(e, request=request)
 requests.exceptions.ConnectionError: MyHTTPSConnectionPool(host='cdn.jsdelivr.net', port=443): Max retries exceeded with url: /gh/localstack/localstack-artifacts@master/local-certs/server.key (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8e52b14bd0>: Failed to resolve 'cdn.jsdelivr.net' ([Errno -2] Name or service not known)"))
 
 2023-12-04T11:03:23.202  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
 2023-12-04T11:03:23.202  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
 Traceback (most recent call last):
   File "/opt/code/localstack/localstack/services/infra.py", line 280, in start_infra
     raise e
   File "/opt/code/localstack/localstack/services/infra.py", line 261, in start_infra
     thread = do_start_infra(asynchronous, apis, is_in_docker)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/localstack/services/infra.py", line 356, in do_start_infra
     thread = start_runtime_components()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 81, in wrapped
     return f(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/localstack/services/infra.py", line 349, in start_runtime_components
     raise TimeoutError(
 TimeoutError: gave up waiting for edge server on 0.0.0.0:4566
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
     sock = connection.create_connection(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection
     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 socket.gaierror: [Errno -3] Temporary failure in name resolution
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen
     response = self._make_request(
                ^^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 492, in _make_request
     raise new_e
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 468, in _make_request
     self._validate_conn(conn)
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
     conn.connect()
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 611, in connect
     self.sock = sock = self._new_conn()
                        ^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 210, in _new_conn
     raise NameResolutionError(self.host, self, e) from e
 urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f8e52af6e10>: Failed to resolve 'analytics.localstack.cloud' ([Errno -3] Temporary failure in name resolution)
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
     resp = conn.urlopen(
            ^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 845, in urlopen
     retries = retries.increment(
               ^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 urllib3.exceptions.MaxRetryError: MyHTTPSConnectionPool(host='analytics.localstack.cloud', port=443): Max retries exceeded with url: /v1/events (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8e52af6e10>: Failed to resolve 'analytics.localstack.cloud' ([Errno -3] Temporary failure in name resolution)"))
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "<frozen runpy>", line 198, in _run_module_as_main
   File "<frozen runpy>", line 88, in _run_code
   File "/opt/code/localstack/localstack/runtime/main.py", line 28, in <module>
     main()
   File "/opt/code/localstack/localstack/runtime/main.py", line 20, in main
     infra.start_infra(asynchronous=False)
   File "/opt/code/localstack/localstack/services/infra.py", line 284, in start_infra
     stop_infra()
   File "/opt/code/localstack/localstack/services/infra.py", line 130, in stop_infra
     usage.aggregate_and_send()
   File "/opt/code/localstack/localstack/utils/analytics/usage.py", line 119, in aggregate_and_send
     publisher.publish(
   File "/opt/code/localstack/localstack/utils/analytics/publisher.py", line 39, in publish
     self.client.append_events(events)
   File "/opt/code/localstack/localstack/utils/analytics/client.py", line 96, in append_events
     response = self.session.post(
                ^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
     return self.request("POST", url, data=data, json=json, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
     resp = self.send(prep, **send_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
     r = adapter.send(request, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
     raise ConnectionError(e, request=request)
 requests.exceptions.ConnectionError: MyHTTPSConnectionPool(host='analytics.localstack.cloud', port=443): Max retries exceeded with url: /v1/events (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8e52af6e10>: Failed to resolve 'analytics.localstack.cloud' ([Errno -3] Temporary failure in name resolution)"))
 ´´´
 This seems to occur after I've rebooted the machine only. So if I have an internet connection after this occurs and I start the container all is well and then if I remove my internet connection and start the container again this issue does not seem to happen.

### Expected Behavior

The container to start without internet

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

The command above but after you rebooted the machine and you don't have an internet connection.

### Environment

```markdown
- OS: Linux xx 5.4.0-139-generic #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- LocalStack: From `docker compose images` I just see `latest`
```

### Anything else?

I have discussed this issue on the slack channel the previous week, hopefully today I have provided more information to debug the issues

**Comment by HenriqueDelben** [comment]
I'm having the same problem.... Were you able to fix it? Thanks in advance...

**Comment by AntonioCS** [comment]
@HenriqueDelben I did mention this issue in the localstack slack server and the devs just told me that in the free version internet is required.
So this is not a bug but a feature (a lousy one).

**Comment by HarshCasper** [comment]
Due to the forthcoming changes in our distribution and development model ([read more](https://blog.localstack.cloud/the-road-ahead-for-localstack/)), this issue tracker is no longer being maintained, and this issue is now being closed. If you'd like us to take a look or need further support, please reach out through one of our support channels:

-   💬 [GitHub Discussions](https://github.com/orgs/localstack/discussions)
-   📖 [Help & Support](https://docs.localstack.cloud/aws/getting-started/help-support/)
