### ISSUE TITLE
Does localstack support S3 select?

### ISSUE THREAD

**Issue by christophersbarrett** [localstack/localstack#980]
^^^ ?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-320) by [Unito](https://www.unito.io/learn-more)

**Comment by christophersbarrett** [comment]
Any update on this? Does localstack support s3 select?

**Comment by gyuki1029** [comment]
I have a same problem!

This error returns when I use aws cli command. 
```
An error occurred (500) when calling the SelectObjectContent operation (reached max retries: 4): Internal Server Error
```

The commands is follows.
```
aws s3api select-object-content 													\
--bucket MY_BUCKET_DUMMY 														\
--key MY_DATA_DUMMY.csv 												\
--expression "select _1 as data_time from s3object s" 											\
--expression-type SQL 															\
--input-serialization '{ "CSV":{ "FileHeaderInfo": "NONE", "RecordDelimiter": "\n", "FieldDelimiter": ","}, "CompressionType": "NONE"}' \
--output-serialization  '{"CSV": {"RecordDelimiter": "\n","FieldDelimiter": ","}}' 							\
--region ap-northeast-1															\
--output json outfile2 															
--endpoint-url=http://localhost:4572
```

**Comment by photonicworld** [comment]
I see this problem still present in localstack version 1.12.5

**Comment by chenavazer** [comment]
Any news about S3 select?

**Comment by DavideMontersino** [comment]
Note: this is a pro feature.
Infact, I activated localstack pro only to be able to use s3 select.. but still it is not working. Would be nice to know if there's any update on this.

**Comment by gnwlyonme** [comment]
Still seeing this issue in v 0.12.16.
I also activated localstack pro but still seeing the following:

2021-08-24 14:34:52,518:API: 127.0.0.1 - - [24/Aug/2021 14:34:52] "POST /localstack-bucket/test.csv.gz?select&select-type=2 HTTP/1.1" 500 -
2021-08-24 14:34:52,529:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 181, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 148, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py", line 1005, in key_or_control_response
    response = self._key_response(request, full_url, headers)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py", line 1176, in _key_response
    return self._key_response_post(request, body, bucket_name, query, key_name)
  File "/opt/code/localstack/localstack/services/s3/s3_starter.py", line 171, in s3_key_response_post
    request, body, bucket_name, query, key_name, *args, **kwargs
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py", line 1769, in _key_response_post
    self._set_action("KEY", "POST", query)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/s3/responses.py", line 546, in _set_action
    self.data["Action"] = ACTION_MAP[action_resource_type][method]["DEFAULT"]
KeyError: 'DEFAULT'


Any ETA on this feature being available?

Thanks

**Comment by thrau** [comment]
S3 select is indeed supported in pro, so will close this issue. we're happy to take a look at the specific issue you're having @gnwlyonme, it would be great if you could create a new bug report with more details on how we can reproduce the issue. thanks!
