### ISSUE TITLE
bug: Service 'secretsmanager' is not enabled

### ISSUE THREAD

**Issue by aka-ao** [localstack/localstack#9811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Secrets manager can not use.
Run this command in my pc. But errors are occurring.
Restarting localstack did not solve the problem.
> awslocal secretsmanager list-secrets

- run result
```
An error occurred (InternalFailure) when calling the ListSecrets operation: Service 'secretsmanager' is not enabled. Please check your 'SERVICES' configuration variable.
```
- localstack log
```
2023-12-06 10:58:27 2023-12-06T01:58:27.635 DEBUG --- [   asgi_gw_0] l.aws.serving.wsgi         : GET localhost.localstack.cloud:4566/_localstack/health
2023-12-06 10:58:31 2023-12-06T01:58:31.949 DEBUG --- [   asgi_gw_1] l.aws.serving.wsgi         : POST localhost:4566/
2023-12-06 10:58:31 2023-12-06T01:58:31.956 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain
2023-12-06 10:58:31 Traceback (most recent call last):
2023-12-06 10:58:31   File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
2023-12-06 10:58:31     handler(self, self.context, response)
2023-12-06 10:58:31   File "/opt/code/localstack/localstack/aws/handlers/service_plugin.py", line 35, in __call__
2023-12-06 10:58:31     return self.require_service(chain, context, response)
2023-12-06 10:58:31            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-12-06 10:58:31   File "/opt/code/localstack/localstack/aws/handlers/service_plugin.py", line 45, in require_service
2023-12-06 10:58:31     raise NotImplementedError(
2023-12-06 10:58:31 NotImplementedError: Service 'secretsmanager' is not enabled. Please check your 'SERVICES' configuration variable.
2023-12-06 10:58:31 2023-12-06T01:58:31.957  INFO --- [   asgi_gw_1] l.aws.handlers.service     : Service 'secretsmanager' is not enabled. Please check your 'SERVICES' configuration variable.
2023-12-06 10:58:31 2023-12-06T01:58:31.958 DEBUG --- [   asgi_gw_1] l.aws.protocol.serializer  : No accept header given. Using request's Content-Type (application/x-amz-json-1.1) as preferred response Content-Type.
2023-12-06 10:58:31 2023-12-06T01:58:31.959  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS secretsmanager.ListSecrets => 501 (InternalFailure); 000000000000/ap-northeast-1; ListSecretsRequest({}, headers={'Host': 'localhost:4566', 'Accept-Encoding': 'identity', 'X-Amz-Target': 'secretsmanager.ListSecrets', 'Content-Type': 'application/x-amz-json-1.1', 'User-Agent': 'aws-cli/2.9.12 Python/3.9.11 Darwin/22.4.0 exe/x86_64 prompt/off command/secretsmanager.list-secrets', 'X-Amz-Date': '20231206T015831Z', 'Authorization': 'AWS4-HMAC-SHA256 Credential=dummy/20231206/ap-northeast-1/secretsmanager/aws4_request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, Signature=a9c150eefb355d000ba53cfd575d3b810d4ac6f08b0555a518c406cbaf1424c5', 'Content-Length': '2', 'x-localstack-tgt-api': 'secretsmanager', 'x-moto-account-id': '000000000000'}); InternalFailure(Service 'secretsmanager' is not enabled. Please check your 'SERVICES' configuration variable., headers={'Content-Type': 'application/json', 'X-Amzn-Errortype': 'InternalFailure', 'Content-Length': '137', 'x-amzn-requestid': 'c22f7a4c-4a52-4271-a6e1-60c1effc4918', 'Connection': 'close'})
```

### Expected Behavior

I hope Secrets manager is available.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal secretsmanager list-secrets

### Environment

```markdown
- OS: mac 13.3.1(m1 pro)
- LocalStack: localstack/localstack:3.0.2
```

**Comment by aka-ao** [comment]
Sorry bad my settings.
Added secretsmanager to SERVICES.
```
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - 4566:4566
    environment:
      - SERVICES=ssm,s3,dynamodb,secretsmanager
```
