### ISSUE TITLE
DDB Connection Intermitent Failure

### ISSUE THREAD

**Issue by teroxik** [localstack/localstack#984]
Hello there, with the **latest** docker image my java app which is using the AWS SDK intermittently looses and drops the connections. 

This doesn't happen with the previous version of the image or with the ddb running locally outside docker.

Some logs:

```
Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
        at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1236)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
        ... 15 common frames omitted
```

Will provide more info if needed.

**Comment by neilg** [comment]
I'm seeing the same issue with the docker images localstack/localstack:0.8.7 and localstack/localstack:0.8.8 but not with earlier versions.

The logs show no issues.
`$ docker-compose logs localstack
Attaching to optabookmakeradaptor_localstack_1
localstack_1  | 2018-11-28 12:47:10,115 CRIT Supervisor running as root (no user in config file)
localstack_1  | 2018-11-28 12:47:10,123 INFO supervisord started with pid 1
localstack_1  | 2018-11-28 12:47:11,127 INFO spawned: 'dashboard' with pid 8
localstack_1  | 2018-11-28 12:47:11,133 INFO spawned: 'infra' with pid 9
localstack_1  | (. .venv/bin/activate; bin/localstack web)
localstack_1  | (. .venv/bin/activate; exec bin/localstack start)
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  | 2018-11-28T12:47:11:INFO:werkzeug:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
localstack_1  | 2018-11-28T12:47:11:INFO:werkzeug:  * Restarting with stat
localstack_1  | 2018-11-28T12:47:12:WARNING:werkzeug:  * Debugger is active!
localstack_1  | 2018-11-28 12:47:12,495 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 2018-11-28 12:47:12,495 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 2018-11-28T12:47:12:INFO:werkzeug:  * Debugger PIN: 147-749-810
localstack_1  | Starting mock DynamoDB (http port 4569)...
localstack_1  | Ready.`

**Comment by teroxik** [comment]
Seems to be fixed as informed above.

**Comment by bobtiernay-okta** [comment]
Seeing a similar `The target server failed to respond` issue with DynamoDB in 0.11.0 as described in https://github.com/localstack/localstack/issues/813
