### ISSUE TITLE
cannot seem to start `localstack`

### ISSUE THREAD

**Issue by ababkin** [localstack/localstack#990]
```
$ localstack start --docker
Traceback (most recent call last):
  File "/usr/local/bin/localstack", line 30, in <module>
    from localstack.services import infra
  File "/usr/local/lib/python3.7/site-packages/localstack/services/infra.py", line 69
    def start(self, async):
                        ^
SyntaxError: invalid syntax
```
any way I could troubleshoot this?

**Comment by ababkin** [comment]
looks like a duplicate https://github.com/localstack/localstack/issues/958
