### ISSUE TITLE
bug: ERROR Deploying on localstack PRO

### ISSUE THREAD

**Issue by gustavo-yance-ikon** [localstack/localstack#9980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Im using open-next package to build and deploy my project: https://open-next.js.org/advanced/architecture
I have tested it on the real cloud and it works perfect so wondering if Im doing something wrong with Localstack or maybe what Im trying to do is not supported yet.

`cdklocal bootstrap` works fine.
`cdklocal synth` works also fine.

but when I run `cdklocal deploy` and confirm the changes I get errors on the latests steps of the deployment.
```

ar: deploying... [1/1]
ar: creating CloudFormation changeset...

 ❌  ar failed: Error: The stack named ar failed to deploy: CREATE_FAILED (Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'nextjsDistributionE6151954', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::Distribution', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'nextjsInvalidationAwsCRF3AE8CE7', 'PhysicalResourceId': None, 'ResourceType': 'Custom::AWS', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'nextjsInvalidationAwsCRCustomResourcePolicyEF1FFDC3', 'PhysicalResourceId': None, 'ResourceType': 'AWS::IAM::Policy', 'Scope': [], 'Details': []}}])
    at FullCloudFormationDeployment.monitorDeployment (/Users/gustavoyance/.nvm/versions/node/v18.18.2/lib/node_modules/aws-cdk/lib/index.js:421:10708)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/Users/gustavoyance/.nvm/versions/node/v18.18.2/lib/node_modules/aws-cdk/lib/index.js:424:180618)
    at async /Users/gustavoyance/.nvm/versions/node/v18.18.2/lib/node_modules/aws-cdk/lib/index.js:424:163866

 ❌ Deployment failed: Error: The stack named ar failed to deploy: CREATE_FAILED (Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'nextjsDistributionE6151954', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::Distribution', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'nextjsInvalidationAwsCRF3AE8CE7', 'PhysicalResourceId': None, 'ResourceType': 'Custom::AWS', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'nextjsInvalidationAwsCRCustomResourcePolicyEF1FFDC3', 'PhysicalResourceId': None, 'ResourceType': 'AWS::IAM::Policy', 'Scope': [], 'Details': []}}])
    at FullCloudFormationDeployment.monitorDeployment (/Users/gustavoyance/.nvm/versions/node/v18.18.2/lib/node_modules/aws-cdk/lib/index.js:421:10708)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/Users/gustavoyance/.nvm/versions/node/v18.18.2/lib/node_modules/aws-cdk/lib/index.js:424:180618)
    at async /Users/gustavoyance/.nvm/versions/node/v18.18.2/lib/node_modules/aws-cdk/lib/index.js:424:163866

The stack named ar failed to deploy: CREATE_FAILED (Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'nextjsDistributionE6151954', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::Distribution', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'nextjsInvalidationAwsCRF3AE8CE7', 'PhysicalResourceId': None, 'ResourceType': 'Custom::AWS', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'nextjsInvalidationAwsCRCustomResourcePolicyEF1FFDC3', 'PhysicalResourceId': None, 'ResourceType': 'AWS::IAM::Policy', 'Scope': [], 'Details': []}}])
```

Also, from the docker container logs Im getting this: 
```
localstack-main  | During handling of the above exception, another exception occurred:
localstack-main  |
localstack-main  | Traceback (most recent call last):
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/services/lambda_/invocation/event_manager.py", line 141, in run
localstack-main  |     messages = sqs_client.receive_message(
localstack-main  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
localstack-main  |     return self._make_api_call(operation_name, kwargs)
localstack-main  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 963, in _make_api_call
.....
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/httpsession.py", line 501, in send
localstack-main  |     raise ReadTimeoutError(endpoint_url=request.url, error=e)
localstack-main  | botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "http://localhost:4566/"
```
which makes me think that maybe the error is only because  `http://localhost:4566` is not reachable inside docker by cdklocal or something? To be honest not completely sure Im relatively new using Localstack pro like this. 

### Expected Behavior

Should work without throwing an error

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    add your PRO token to .env.docker based on .env.docker.example and run `docker compose up`; to run this project you will need node 18 and yarn. I tried to set this example in a monorepo so you could only run `sh init.sh` 
    to install dependencies where its needed. 
   

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    cdklocal bootstrap
    cdklocal deploy

### Environment

```markdown
- OS: Mac OS M2 MAX
- LocalStack: latest
```

### Anything else?

Have tried different  setups and always fails the same `AWS::CloudFront::Distribution` and I also have found this PR https://github.com/localstack/localstack/pull/9807 so wondering if this has to do with my code failing 🤔  Maybe some stuff is not supported yet? Or maybe Im just doing something wrong? 
Thanks in advance for the help!

**Comment by gustavo-yance-ikon** [comment]
Basic repo example: https://github.com/gustavo-yance-ikon/localstack-next-example

**Comment by flaxpanda** [comment]
i am also experiencing this

```
ap-test-localstack |  0/34 | 9:35:48 PM | CREATE_IN_PROGRESS   | AWS::CloudFormation::Stack                      | ap-test-localstack 
ap-test-localstack |  1/34 | 9:35:48 PM | CREATE_COMPLETE      | AWS::Route53::HostedZone                        | hosted-zone (hostedzone0562BB58) 
ap-test-localstack |  2/34 | 9:35:48 PM | CREATE_COMPLETE      | AWS::Events::EventBus                           | event-bus (eventbus7CF8FDD5) 
ap-test-localstack |  3/34 | 9:35:48 PM | CREATE_COMPLETE      | AWS::S3::Bucket                                 | bucket-activity-stream (bucketactivitystreamCC00E179) 
ap-test-localstack |  4/34 | 9:35:49 PM | CREATE_COMPLETE      | AWS::IAM::Role                                  | Custom::S3AutoDeleteObjectsCustomResourceProvider/Role (CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092) 
ap-test-localstack |  5/34 | 9:35:54 PM | CREATE_COMPLETE      | AWS::Lambda::Function                           | Custom::S3AutoDeleteObjectsCustomResourceProvider/Handler (CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F) 
ap-test-localstack |  6/34 | 9:35:54 PM | CREATE_COMPLETE      | AWS::S3::Bucket                                 | bucket-files (bucketfiles4A78EEAE) 
ap-test-localstack |  7/34 | 9:35:54 PM | CREATE_COMPLETE      | AWS::CloudFront::CloudFrontOriginAccessIdentity | files-distro/files-distro-oai (filesdistrofilesdistrooai641CD55C) 
ap-test-localstack |  8/34 | 9:35:55 PM | CREATE_COMPLETE      | AWS::CertificateManager::Certificate            | files-distro/cert (filesdistrocert30011301) 
ap-test-localstack |  9/34 | 9:35:55 PM | CREATE_COMPLETE      | AWS::IAM::ManagedPolicy                         | EC2-Key-Pair-Manager-Policy (EC2KeyPairManagerPolicyEBBC1576) 
ap-test-localstack | 10/34 | 9:35:55 PM | CREATE_COMPLETE      | AWS::IAM::Role                                  | EC2-Key-Pair-Manager-Role (EC2KeyPairManagerRoleB243C519) 
ap-test-localstack | 11/34 | 9:36:00 PM | CREATE_COMPLETE      | AWS::Lambda::Function                           | EC2-Key-Name-Manager-Lambda (EC2KeyNameManagerLambdaBE629145) 
ap-test-localstack | 12/34 | 9:36:00 PM | CREATE_COMPLETE      | AWS::S3::Bucket                                 | bucket-import (bucketimport291F23B2) 
ap-test-localstack | 13/34 | 9:36:00 PM | CREATE_COMPLETE      | AWS::S3::BucketPolicy                           | bucket-import/Policy (bucketimportPolicy49364FF3) 
ap-test-localstack | 14/34 | 9:36:02 PM | CREATE_COMPLETE      | Custom::S3AutoDeleteObjects                     | bucket-import/AutoDeleteObjectsCustomResource/Default (bucketimportAutoDeleteObjectsCustomResourceB55A5E1B) 
ap-test-localstack | 15/34 | 9:36:02 PM | CREATE_COMPLETE      | AWS::IAM::Role                                  | BucketNotificationsHandler050a0587b7544547bf325f094a3db834/Role (BucketNotificationsHandler050a0587b7544547bf325f094a3db834RoleB6FB88EC) 
ap-test-localstack | 16/34 | 9:36:02 PM | CREATE_COMPLETE      | AWS::IAM::Policy                                | BucketNotificationsHandler050a0587b7544547bf325f094a3db834/Role/DefaultPolicy (BucketNotificationsHandler050a0587b7544547bf325f094a3db834RoleDefaultPolicy2CF63D36) 
ap-test-localstack | 17/34 | 9:36:08 PM | CREATE_COMPLETE      | AWS::Lambda::Function                           | BucketNotificationsHandler050a0587b7544547bf325f094a3db834 (BucketNotificationsHandler050a0587b7544547bf325f094a3db8347ECC3691) 
ap-test-localstack | 18/34 | 9:36:08 PM | CREATE_COMPLETE      | AWS::S3::Bucket                                 | bucket-meta (bucketmeta8A2EBF5F) 
ap-test-localstack | 19/34 | 9:36:08 PM | CREATE_COMPLETE      | AWS::S3::BucketPolicy                           | bucket-meta/Policy (bucketmetaPolicyE0565CC9) 
ap-test-localstack | 20/34 | 9:36:10 PM | CREATE_COMPLETE      | Custom::S3AutoDeleteObjects                     | bucket-meta/AutoDeleteObjectsCustomResource/Default (bucketmetaAutoDeleteObjectsCustomResource676AB55F) 
ap-test-localstack | 21/34 | 9:36:10 PM | CREATE_COMPLETE      | AWS::S3::Bucket                                 | bucket-temp (buckettemp182C9A53) 
ap-test-localstack | 22/34 | 9:36:10 PM | CREATE_COMPLETE      | AWS::S3::BucketPolicy                           | bucket-temp/Policy (buckettempPolicy3EFA3EB0) 
ap-test-localstack | 23/34 | 9:36:12 PM | CREATE_COMPLETE      | Custom::S3AutoDeleteObjects                     | bucket-temp/AutoDeleteObjectsCustomResource/Default (buckettempAutoDeleteObjectsCustomResource9A2B5270) 
ap-test-localstack | 24/34 | 9:36:12 PM | CREATE_COMPLETE      | AWS::S3::BucketPolicy                           | bucket-activity-stream/Policy (bucketactivitystreamPolicyA744A069) 
ap-test-localstack | 25/34 | 9:36:14 PM | CREATE_COMPLETE      | Custom::S3AutoDeleteObjects                     | bucket-activity-stream/AutoDeleteObjectsCustomResource/Default (bucketactivitystreamAutoDeleteObjectsCustomResourceC996450B) 
ap-test-localstack | 26/34 | 9:36:14 PM | CREATE_COMPLETE      | AWS::S3::BucketPolicy                           | bucket-files/Policy (bucketfilesPolicyDD239D57) 
ap-test-localstack | 27/34 | 9:36:16 PM | CREATE_COMPLETE      | Custom::S3AutoDeleteObjects                     | bucket-files/AutoDeleteObjectsCustomResource/Default (bucketfilesAutoDeleteObjectsCustomResource8BB414CC) 
ap-test-localstack | 28/34 | 9:36:18 PM | CREATE_COMPLETE      | Custom::EC2-Key-Pair                            | files-distro/files-distro-keypair/EC2-Key-Pair-ap-test-files-test-com-keypair/Default (filesdistrofilesdistrokeypairEC2KeyPairaptestfilestestcomkeypairFDBEAF8D) 
ap-test-localstack | 29/34 | 9:36:18 PM | CREATE_COMPLETE      | AWS::CloudFront::PublicKey                      | files-distro/files-distro-publickey (filesdistrofilesdistropublickeyDE1296FA) 
ap-test-localstack | 30/34 | 9:36:21 PM | CREATE_COMPLETE      | Custom::S3BucketNotifications                   | bucket-import/Notifications (bucketimportNotifications48525747) 
ap-test-localstack | 30/34 | 9:36:21 PM | CREATE_FAILED        | AWS::CloudFormation::Stack                      | ap-test-localstack Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'filesdistrofilesdistrokeygroup1CF1D296', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::KeyGroup', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'filesdistroaliasfilestestcom108EABB5', 'PhysicalResourceId': None, 'ResourceType': 'AWS::Route53::RecordSet', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'filesdistrodistro440E49E5', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::Distribution', 'Scope': [], 'Details': []}}]
Failed resources:

 ❌  ap-test-localstack failed: Error: The stack named ap-test-localstack failed to deploy: CREATE_FAILED (Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'filesdistrofilesdistrokeygroup1CF1D296', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::KeyGroup', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'filesdistroaliasfilestestcom108EABB5', 'PhysicalResourceId': None, 'ResourceType': 'AWS::Route53::RecordSet', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'filesdistrodistro440E49E5', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::Distribution', 'Scope': [], 'Details': []}}])
    at FullCloudFormationDeployment.monitorDeployment (/Users/name/code/node_modules/aws-cdk/lib/index.js:426:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/Users/name/code/node_modules/aws-cdk/lib/index.js:429:153380)
    at async /Users/name/code/node_modules/aws-cdk/lib/index.js:429:137002

 ❌ Deployment failed: Error: The stack named ap-test-localstack failed to deploy: CREATE_FAILED (Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'filesdistrofilesdistrokeygroup1CF1D296', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::KeyGroup', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'filesdistroaliasfilestestcom108EABB5', 'PhysicalResourceId': None, 'ResourceType': 'AWS::Route53::RecordSet', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'filesdistrodistro440E49E5', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::Distribution', 'Scope': [], 'Details': []}}])
    at FullCloudFormationDeployment.monitorDeployment (/Users/name/code/node_modules/aws-cdk/lib/index.js:426:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/Users/name/code/node_modules/aws-cdk/lib/index.js:429:153380)
    at async /Users/name/code/node_modules/aws-cdk/lib/index.js:429:137002
The stack named ap-test-localstack failed to deploy: CREATE_FAILED (Resource deployment loop completed, pending resource changes: [{'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'filesdistrofilesdistrokeygroup1CF1D296', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::KeyGroup', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'filesdistroaliasfilestestcom108EABB5', 'PhysicalResourceId': None, 'ResourceType': 'AWS::Route53::RecordSet', 'Scope': [], 'Details': []}}, {'Type': 'Resource', 'ResourceChange': {'Action': 'Add', 'LogicalResourceId': 'filesdistrodistro440E49E5', 'PhysicalResourceId': None, 'ResourceType': 'AWS::CloudFront::Distribution', 'Scope': [], 'Details': []}}])
Warning: run-commands command "npx cdklocal deploy --app 'npx ts-node --project packages/infra/localstack/tsconfig.app.json packages/infra/localstack/src/main.ts' --require-approval=never" exited with non-zero status code
 
 >  NX   Running target cdklocal for project infra-localstack failed
   Failed tasks:
   
   - infra-localstack:cdklocal
   
   Hint: run the command with --verbose for more details.
Warning: run-commands command "npx nx run infra-localstack:cdklocal --cmd deploy" exited with non-zero status code
```
